### ISSUE TITLE
pkg:front_end: Remove isOptOutPackage logic

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40775]
https://github.com/dart-lang/sdk/blob/550ac009b3950a463baf5264a15114584f9ee5a0/pkg/front_end/lib/src/fasta/source/source_library_builder.dart#L385-L389

This blocks our ability to start experimenting with migrating core packages

**Comment by johnniwinther** [comment]
@kevmoo: Is there an issue for adding the needed packages.json files to the repo to avoid this work-around?

**Comment by kevmoo** [comment]
What's `packages.json`? What's the format? Where do I put it?

**Comment by kevmoo** [comment]
@johnniwinther – also, what's left to fix before we can just remove this? T'would be better!

**Comment by johnniwinther** [comment]
@sigmundch - do you know if there's plan to remove the need for this work-around?

**Comment by sigmundch** [comment]
I saw the message from Bob that we just added the .dart-tool/packages.json file to the repo.

As soon as all of our tools switch to use it by default, we can delete the workaround. If I understand correctly, we explicitly pass `--packages=path/to/.packages` in various places and we need to be update them before we can switch. This includes when building snapshots for our tools, when launching test.dart, when launching tools from sources (e.g. test.dart runs dart2js with assertions by launching a vm and running the compiler from sources), and when compiling tests (e.g. dart2js needs packages that are used by tests to be opted out).

@kevmoo @munificent - do you know if someone is actively working on this?

**Comment by kevmoo** [comment]
I don't know if anyone is working on this. Someone should be. This will block us starting to migrate core packages

CC @vsmenon

**Comment by vsmenon** [comment]
@johnniwinther - do you know what is blocking removal of the whitelist at this point?

**Comment by sigmundch** [comment]
I chatted briefly with @johnniwinther about it - from the CFE perspective, there is nothing blocking if I recall correctly. The main thing is our internal plumbing:
 - test.dart needs to use packages.json
 - all tools need to be run passing the new packages.json
 - if any test depends on a package, then we need to add a packages.json for those tests as well (technically I thought we could remove the whitelist for packages before removing tests, but if any tests depend on packages we need to keep pushing on that first)
 - eventually we should not have any references to .packages around
 - I guess we also need to do some downstream work in the flutter repo, but that could be done after removing the whitelist (but must be done before we unfork)

**Comment by kevmoo** [comment]
🤦‍♂ that's a lot of stuff, @sigmundch 

@vsmenon @munificent @leafpetersen @natebosch – could we get some eng help here?

**Comment by jakemac53** [comment]
Note that passing the original `.packages` works fine _if_ there is a `.dart_tool/package_config.json` file next to it that will be loaded instead. This might help ease the transition.

**Comment by kevmoo** [comment]
Note also: tried a presubmit

https://dart-review.googlesource.com/c/sdk/+/138110

mostly green. Would be good to debug the failures!

**Comment by sigmundch** [comment]
quick update that I started looking at this, but I still don't have enough progress to report on how quickly we can move here. There is potential that the fallback mechanism will work in a lot of contexts out of the box.

**Comment by vsmenon** [comment]
Should we consider landing `// @dart = 2.7` in all these packages to unblock us?  That should keep tests working until they are ported.

**Comment by kevmoo** [comment]
Why doesn't the SDK constraint in the pubspec take care of this?

Fix that – or the package_config.json file seems a better use of time!

**Comment by vsmenon** [comment]
I believe because we don't run `pub get` in packages in our own sdk tests / bot - no `packages.json` is created.  It just defers to the top-level `.packages` file.

**Comment by kevmoo** [comment]
> I believe because we don't run `pub get` in packages in our own sdk tests / bot - no `packages.json` is created. It just defers to the top-level `.packages` file.

@munificent did the work to add a package_config.json file to the repo!

See https://github.com/dart-lang/sdk/commit/4b7ba5a72fd1897fa6954f924b6d49389cea819f#diff-b709a02b5c5d49f6d7050b0aa4749aaa

**Comment by vsmenon** [comment]
Ahh, nice.  I missed that.  Are we not picking that up then?

**Comment by kevmoo** [comment]
I did a test run CL w/ the list removed and it had failures – so there are clearly things still broken

**Comment by vsmenon** [comment]
Per Siggi's comment, this might be because `test.dart` is using `.packages` explicitly.

**Comment by kevmoo** [comment]
Let's fix that!

We have a package for it!

**Comment by vsmenon** [comment]
Actually, taking a look at the failures on your CL:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8886824004272670784/+/steps/test_results/0/logs/new_test_failures/0

I think it is picking up the `package_config.json` in general.

The `service` tests are probably breaking because there is a separate `.packages` file in `runtime/observatory/.packages`.  The others may be similar.

**Comment by kevmoo** [comment]
It'd be easy to start running on it again!

**Comment by vsmenon** [comment]
@munificent - it looks like your script is reading from `runtime/observatory` already.  Should it be writing a `runtime/observatory/.dart_tool/package_config.json` too?

**Comment by sigmundch** [comment]
I also believe the vm failures are likely an easy fix (sprinlke a few more package_config files, possibly opt out manually some code that is a package within the test.

The dart2js and cfe bots concern me more. I tried running them locally and they appear to be running, however they are running a lot slower. The dart2js timed out after running roughly for an hour about half of the tests.

Next I plan to do a side-by-side comparison locally to get a better idea of what's going on.

**Comment by sigmundch** [comment]
So far I haven't determined the cause of the slow down locally.

@athomas - other than the general timeout at the top-level, do you see other insights from https://dart-review.googlesource.com/c/sdk/+/138901 that can give us a clue into what is going wrong?

**Comment by athomas** [comment]
I see [shards completing, but then somehow timing out](https://chromium-swarm.appspot.com/task?id=4adaad8c3cd64010). I see [a lot of crashes](https://isolateserver.appspot.com/browse?namespace=default-gzip&digest=595c466f71d1ded8df554282966852655b535311&as=results.json). That suggest that something in test.py is not coping well with the amount of crashes.

When you ran locally, what was the exact command line you used?

Just in case it's helpful, here is one of the [logs of those crashes](https://isolateserver.appspot.com/browse?namespace=default-gzip&digest=22bcbe1656abd544e70777298204951cf8d41eb7&as=logs.json):
```
--- Command \"fasta\" (took 16.000883s):
(cd /b/s/w/ir/ ; DART_CONFIGURATION=ReleaseX64NNBD ./out/ReleaseX64NNBD/dart ./pkg/front_end/tool/_fasta/compile.dart --verify -o ./out/ReleaseX64NNBD/generated_compilations/fasta/tests_corelib_2_expression_test/out.dill --platform ./out/ReleaseX64NNBD/vm_platform_strong.dill --enable-experiment=non-nullable --packages=./.packages ./tests/corelib_2/expression_test.dart )

exit code:
253

stderr:
pkg/front_end/lib/src/fasta/incremental_compiler.dart:1569:39: Error: The function expression type 'Future<FutureOr<Procedure>> Function(CompilerContext)' isn't of expected type 'Future<Procedure> Function(CompilerContext)'.
 - 'Future' is from 'dart:async'.
 - 'FutureOr' is from 'dart:async'.
 - 'Procedure' is from 'package:kernel/ast.dart' ('pkg/kernel/lib/ast.dart').
 - 'CompilerContext' is from 'package:front_end/src/fasta/compiler_context.dart' ('pkg/front_end/lib/src/fasta/compiler_context.dart').
Change the type of the function expression or the context in which it is used.
    return await context.runInContext((_) async {
                                      ^
pkg/front_end/lib/src/base/libraries_specification.dart:151:29: Error: The function expression type 'dynamic Function(String, dynamic)' isn't of expected type 'void Function(dynamic, dynamic)'.
Change the type of the function expression or the context in which it is used.
      librariesData.forEach((String name, data) {
                            ^
pkg/front_end/lib/src/api_prototype/kernel_generator.dart:60:57: Error: The function expression type 'Future<FutureOr<CompilerResult>> Function(CompilerContext)' isn't of expected type 'Future<CompilerResult> Function(CompilerContext)'.
 - 'Future' is from 'dart:async'.
 - 'FutureOr' is from 'dart:async'.
 - 'CompilerResult' is from 'package:front_end/src/api_prototype/kernel_generator.dart' ('pkg/front_end/lib/src/api_prototype/kernel_generator.dart').
 - 'CompilerContext' is from 'package:front_end/src/fasta/compiler_context.dart' ('pkg/front_end/lib/src/fasta/compiler_context.dart').
Change the type of the function expression or the context in which it is used.
  return await CompilerContext.runWithOptions(pOptions, (context) async {
                                                        ^
pkg/_fe_analyzer_shared/lib/src/util/link_implementation.dart:131:43: Error: The getter 'isNotEmpty' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isNotEmpty'.
    while (myElements.isNotEmpty && other.isNotEmpty) {
                                          ^^^^^^^^^^
pkg/_fe_analyzer_shared/lib/src/util/link_implementation.dart:132:36: Error: The getter 'head' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'head'.
      if (myElements.head != other.head) {
                                   ^^^^
pkg/_fe_analyzer_shared/lib/src/util/link_implementation.dart:136:21: Error: The getter 'tail' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'tail'.
      other = other.tail;
                    ^^^^
pkg/_fe_analyzer_shared/lib/src/util/link_implementation.dart:138:40: Error: The getter 'isEmpty' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isEmpty'.
    return myElements.isEmpty && other.isEmpty;
                                       ^^^^^^^

--- Re-run this test:
python tools/test.py -n cfe-weak-linux corelib_2/expression_test
```

**Comment by kevmoo** [comment]
Started another test CL – https://dart-review.googlesource.com/c/sdk/+/138906 – rebased on master

**Comment by sigmundch** [comment]
@athomas thanks so much, this was very helpful. I should have realized this from the previous time that when I can't repro locally it is usually a fileset issue.

I believe we need to add the package_config.json to the fileset to get rolling. I'm about to try that out.

**Comment by sigmundch** [comment]
That did it! - the new run https://dart-review.googlesource.com/c/sdk/+/138901/2 completed on both CFE and dart2js bots cleanly!

**Comment by sigmundch** [comment]
And... turns out all the vm failures were for the same reason. The failures were not about the test-specific .packages file, but about the test harness itself, which was using the default .packages at the top.

CL is finally out for review

**Comment by kevmoo** [comment]
Woo hoo!
