### ISSUE TITLE
[Quick Fixes...] Imports in catch clause doesn't show (on Foo catch)

### ISSUE THREAD

**Issue by bounty1342** [dart-lang/sdk#40778]
Dear all,

I came accross this issue today. When missing an import for a class in a catch clause, there is no quick-fixes :
![](https://cdn.discordapp.com/attachments/615553440969392151/681927284453802015/unknown.png)

The quick-fixes is well activated, as you can see below :
![](https://cdn.discordapp.com/attachments/615553440969392151/681929585826594837/Screenshot_2020-02-25_at_18.24.27.png)

Also the quick-fixes works well outside a catch clause :
![](https://cdn.discordapp.com/attachments/615553440969392151/681927963029012480/unknown.png)

Finally, this is not platform specific or related to a special class (Tested with PlatformException, MissingPluginException...)

Let me know if you need more info.
Regards

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/137423
