### ISSUE TITLE
[DDC] Provide metadata to help filter JS scopes for debugging

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#40774]
In package:dwds we manually filter out the two outer most scopes:
https://github.com/dart-lang/webdev/blob/446fb9d63875a765fa3704c71ed76ede61a51325/dwds/lib/src/debugging/dart_scope.dart#L23

This is brittle and can be broken given changes to the root bootstrap logic. I will soon update the logic to filter scopes until we find where the Dart SDK is defined. This will be done by looking for `core` and `dart` on a JS scope. Although a bit better, this too seems brittle.

It'd be great if DDC provided metadata to help determine if a scope should be considered for debugging.

**Comment by annagrin** [comment]
We can name the library closures (all of them with some detectable from the debugger name), and   only display the scopes that come after the library one. 

This requires exposing scope name in WipScope class though - see https://github.com/google/webkit_inspection_protocol.dart/pull/56
