### ISSUE TITLE
Flutter app crashes in release mode on arm64 if certain debug-only fields are removed.

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#40787]
Flutter app crashes when it is running in release mode on arm64 (iOS) when the following debug-only fields are removed from `RenderObject` (https://github.com/flutter/flutter/blob/64c5a434d09264454ab6e9d36a25ed6f64344bc2/packages/flutter/lib/src/rendering/object.dart#L1210):

```
bool _debugDoingThisResize = false;
bool _debugDoingThisLayout = false;
bool _debugDoingThisPaint = false;
```

These fields are only used from asserts. Crash happens on if these fields are removed manually from `RenderObject`. The same crash also happens if they are removed by tree-shaker with ff34fd81106dbd4c2a341f5545e5f900b591ebfa.

More details about reproducing the crash: b/149399743, https://github.com/flutter/flutter/issues/50745.

/cc @mraleph @mkustermann @rmacnak-google @aam

**Comment by mraleph** [comment]
I suspect this has the same underlying cause as https://github.com/dart-lang/sdk/issues/41910 - so we can probably close it.

**Comment by alexmarkov** [comment]
We got a confirmation that the app no longer crashes with tree-shaking of write-only fields.
