### ISSUE TITLE
Unable to use break out of nested for loop when using .Then function inside

### ISSUE THREAD

**Issue by joabh** [dart-lang/sdk#40784]
This is a simplified version of what I am trying to achieve. I have noticed that it is the .then function that is causing the for loop to not work as expected, however I need the .then function as it returns a new Future from a firestore database each time the outer for-loop runs.

`
```
      bool isUniqueName;

      for(var n = 0; n<5; n++){
        artistID = getRandomArtistID(); // returns Future<string>
        artistID.then((value) {
          artist = value;
          print(artist);
          for (var j = 0; j < 2; j++) {
            if (artist == 'qXeTKQ22KgdNM21t3m3BenBh7Ro4') {
              print('Found Unique Artist');
              isUniqueName = true;
              break;
            }
          } // inner for-loop
          if (isUniqueName == true) {
            //break not working here
            print('The Unique Name is: $artist');
          }
        }); // .Then function
      } // Outer for-loop
```
`

If I try to use the if statement outside of the .then function it doesn't work, but the break no longer errors.

**Comment by eernstg** [comment]
A `break` statement will not unwind the run-time stack, it is only allowed when there is an enclosing target (such as a `for` statement) which is in the body of the innermost enclosing function. So the `break` at the comment `// break not working here` is a compile-time error.

**Comment by mraleph** [comment]
@joabh One important thing that you seem to be missing is that a function passed to `then(...)` will normally be executed at some later point - when your outer loop has already finished executing - so `break` there is meaningless. 

You could rewrite your function as an async function and use `await`, like so:

```
      bool isUniqueName;

      for(var n = 0; n<5; n++){
        artistID = await getRandomArtistID();
        print(artistID);
        for (var j = 0; j < 2; j++) {
          if (artistID == 'qXeTKQ22KgdNM21t3m3BenBh7Ro4') {
            print('Found Unique Artist');
            isUniqueName = true;
            break;
          }
        } // inner for-loop
        if (isUniqueName == true) {
          print('The Unique Name is: $artist');
          break;
        }
      } // Outer for-loop
```

I suggest going though some codelabs (e.g. https://dart.dev/codelabs/async-await) to get the grasp of how asynchronous programming model works.
