### ISSUE TITLE
[vm] Handle late fields in type propagation

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#40796]
Currently we're just setting late fields to nullable in the type propagator, because otherwise all the sentinel comparison logic gets optimised out. This works, but is not optimal.

We'll need to extend CompileType to be able to handle lateness.

**Comment by mraleph** [comment]
I don't think you should extend `CompileType` for this purpose. I suggest instead look at unifying late field lowering and `InitStaticField` and then either write a specialized data flow pass which removes redundant `Init*` instructions (if we want to handle complicated cases) or just permit CSE to remove `Init*` by dominance.
