### ISSUE TITLE
The dartdev tool should print a warning if there is a file name that is the same as the command being executed

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#40791]
The dartdev tool should print a warning if there is a file name that is the same as the command being executed.  Example, users types:

`dart analyze`

If there is a dart file named `analyze` that the user was intending to execute, there should be some error message such as:

`Warning: there is a file named analyze (/absolute/file/path/to/analyze) in the current working directory.`

**Comment by jwren** [comment]
@bkonyi fyi

**Comment by jwren** [comment]
https://dart-review.googlesource.com/c/sdk/+/137844

**Comment by jwren** [comment]
@mit-mit / @kevmoo  See the comment in the PR from Devon.  This bug and fixing PR should be landed and closed, or not landed and fixed, please advise.

**Comment by mit-mit** [comment]
Quoting @devoncarew from the review:

> I'm not certain that this is actually necessary. I've never expected to be able to run a dart file that didn't have a .dart extension. Do we think this is really a requirement (handling this case, and emitting an error)?

**Comment by jwren** [comment]
Thanks @mit-mit

**Comment by mit-mit** [comment]
Like Devon above, I'm unconcerned with developers trying to run a Dart source code file that 1) doesn't have a `.dart` extension, and 2) happens to have the same name as a subcommand. It just seems entirely unlikely.

The one case I'm pondering is for snapshots. I don't think we have extensions for those?

**Comment by jwren** [comment]
That last question is a good one, @bkonyi ?

**Comment by bkonyi** [comment]
Snapshots generated during the SDK build always have the `.dart.snapshot` extension.

**Comment by jwren** [comment]
I know that, did you add logic to detect if something was a `*.dart` or not to run the dartdev snapshot versus executing the file on the VM?  If so, it should check for additional patterns, such as `.dart.snapshot`, others for AOT, etc?

**Comment by bkonyi** [comment]
Nope, currently we just check to see if the first non-flag argument to `dart` is a path to a file that exists or is of a specific URI scheme (e.g., http, https, file, package, google3). If so, we try and run the file. If that's not the case, we just assume it's a command and forward it to dartdev.

**Comment by jwren** [comment]
Thanks Ben.  Closing issue.

**Comment by mit-mit** [comment]
sgtm
