### ISSUE TITLE
Should extension methods be "expired" in experimental_features.yaml?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40794]
https://github.com/dart-lang/sdk/blob/c9884ccf525b78a48930b70fc2e2e95951ca66b5/tools/experimental_features.yaml#L73-L75

CC @munificent @eernstg

**Comment by kevmoo** [comment]
CC @johnniwinther , who landed the CL that enable the feature

**Comment by lrhn** [comment]
It should be retired. There is (or should be) no way to disable extension methods any more.

**Comment by kevmoo** [comment]
> It should be retired. There is (or should be) no way to disable extension methods any more.

I pondered creating a CL for this, but wasn't sure of the consequences.

If an experiment has a shipped version, it should be required to be 'expired', right?

**Comment by lrhn** [comment]
Adding @athomas. I believe the flag should have been disabled as part of the release process.

**Comment by athomas** [comment]
We shouldn't change behavior when we release. So this should be the last step in the implementation plan (probably landed together with the flag flip).

As a failsafe, I added a "Verify that all enabled experiment flags have been removed" to the go/dart-release-checklist (could be deleted if we come up with a way to test this). @franklinyow

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/152296e642f367c8054ce42c6224ac1118017f59
