### ISSUE TITLE
Parser requiring gratuitious parens with `x.y! < a`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40793]
Around SDK commit 9c05fde96b62556944befd18ec834c56d6854fda

@munificent said I shouldn't need parens in this case

```dart
void testFunc() {
  var sample = Sample();

  if (sample.value != null && (sample.value!) < 10) {
    //                                ^ fine!
    print('thing!');
  }
  if (sample.value != null && sample.value! < 10) {
    //                               ^ error: Expected an identifier. missing_identifier
    print('thing!');
  }
}

class Sample {
  int? value;
}
```

**Comment by bwilkerson** [comment]
I'm not sure this has anything to do with NNBD, so I left that label, but the diagnostic you're seeing is coming from the parser.

**Comment by lrhn** [comment]
It has something to do with NNBD because the `!` suffix operator is only allowed in NNBD code.

**Comment by jensjoha** [comment]
This will be fixed with https://dart-review.googlesource.com/c/sdk/+/137784 and https://dart-review.googlesource.com/c/sdk/+/137789

**Comment by kevmoo** [comment]
Awesome!

**Comment by jensjoha** [comment]
This should now be fixed.
