### ISSUE TITLE
flutter create should use a recent minimum version

### ISSUE THREAD

**Issue by vogella** [dart-lang/sdk#40803]
if I create a new flutter program with flutter create I expect a relative recent version as minimum. Currently I get:

environment:
  sdk: ">=2.1.0 <3.0.0"

I suggest to upgrade to at least 2.7 to use interesting features.

environment:
  sdk: ">=2.7.0 <3.0.0"

**Comment by mraleph** [comment]
This issue should be filed on the flutter/flutter repository. This issue tracker covers pure Dart SDK issues.

**Comment by mraleph** [comment]
(Unfortunately I can't just transfer it there because that does not work across organization boundaries on GitHub)

**Comment by vogella** [comment]
Thanks, recreated https://github.com/flutter/flutter/issues/51622
