### ISSUE TITLE
Front-end does not allow covariant late final variables.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#40805]
Example:
```dart
main() {
  D().x = 3.14;
}

class C {
  covariant late final int x;
}

class D extends C {
  set x(num value) { super.x = value.toInt(); }
}
```
This gives an error saying that a variable cannot be both `final` and `covariant`. That's the rule pre-Null Safety Dart because `covariant` affects only the setter and final fields do not have a setter.

However, a `late` instance variable with no initializer *does* have a setter, and as such, it should also be allowed to be modified by `covariant` to make that setter's parameter covariant.

I also get an error assigning to `super.x`, saying that there is no setter. Again, a late instance variable with no initializer does have a setter, so it should work.

VM errors:
```dart
covar.dart:6:3: Error: Members can't be declared to be both 'final' and 'covariant'.Try removing either the 'final' or 'covariant' keyword.
  covariant late final int x;
  ^^^^^^^^^
covar.dart:9:28: Error: Superclass has no setter named 'x'.
  set x(num value) { super.x = value.toInt(); }
                           ^
```

(The analyzer gives similar errors:
```
Analyzing covar.dart...
  error - Members can't be declared to be both 'final' and 'covariant'. - covar.dart:6:3 - final_and_covariant
  error - The setter 'x' isn't defined in a superclass of 'D'. - covar.dart:9:28 - undefined_super_setter
2 errors found.
```
but I'm not sure whether that comes from the front-end or from the analyzer itself).

**Comment by jensjoha** [comment]
I've fixed the first part in https://dart-review.googlesource.com/c/sdk/+/137796/.

I still get the `Error: Superclass has no setter named 'x'.` error. I'll refer to @johnniwinther  on that one.
