### ISSUE TITLE
Remove uses of  setNotNullableParameter in all the dart:core library code

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#40810]
setNotNullableParameter was introduced to enable porting of the following code pattern
void set isHead(bool value) => _noMessageBody = value ?? false

to avoid errors from CFE when --force-nnbd-checks option is used.

**Comment by lrhn** [comment]
@a-siva Is this obsolete now? I can't find any occurrences of the string `setNotNullabelparameter` in the SDK.

**Comment by a-siva** [comment]
All uses of it have been removed, closing this issue.
