### ISSUE TITLE
Add a "lock down this library" feature to the web UI

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#40823]
Add a button to the web UI that will migrate and opt-in a single library, or possibly apply hints (details TBD)

**Comment by stereotype441** [comment]
@a14n indicated in Discord chat yesterday that this would help streamline his process for migrating Flutter.  I'll try to get to work on this soon.

**Comment by stereotype441** [comment]
The work we're doing on incremental migration (#44124) should make this unnecessary, so I'm going to close this feature request.
