### ISSUE TITLE
Add unit testing for edge origins in edge_builder instead of integration testing them with InfoBuilder

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40833]
The migration tool currently generates EdgeOrigin objects when it draws edges, but there isn't much (or perhaps any?) tests that these origins are drawn correctly.

There are tests for this in info_builder, but that is second degree testing.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
