### ISSUE TITLE
[sdk] provide a common way to resolve uri's based on .packages

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#40835]
We have code in flutter and webdev/dwds tests (copy of flutter's) for class PackageMap that resolves uri's based on provided .packages file:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/package_map.dart

would be great to provide it in the sdk to the other projects can reuse.

**Comment by bwilkerson** [comment]
Having a common implementation is a good idea, but there is already support for reading and using the `.packages` file in the `package_config` package, which is vended into the SDK.

Also, the `.package` file is being replaced by the `.dart_tool/package_config.json` file, so your existing support will need to be updated. The good news is that the `package_config` package already has support for the new format, so you won't need to implement it yourself.

At the moment, tools should support both formats, favoring the new when its available, with plans to drop support for the old one in the future.
