### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by bangbiggy** [dart-lang/sdk#40846]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, FATAL error:
```

For additional log information, please append the contents of
file://C:\Users\DANIEL\AppData\Local\Temp\report1.txt.

**Comment by keertip** [comment]
@bangbiggy , there is not enough information to take any action here. Closing issue, reopen with details.
