### ISSUE TITLE
[Analyzer] Incorrect Refactor when adding a type to a getter

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#40842]
![2020-02-29 18 56 02](https://user-images.githubusercontent.com/23037821/75618583-726ec100-5b25-11ea-938c-289b7b9f45b1.gif)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/139260

**Comment by ThinkDigitalSoftware** [comment]
Thank you, Sue
