### ISSUE TITLE
Is json.decode lazy-loaded?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#40848]
Assume that we have such JSON:

```json
{
  "property": 42,
  "list": [ 0, 1, 2 ] 
}
```

Then we do:

```dart
String myJson;

final result = json.decode(myJson);
print(result['property']);
```

Then, was `list` parsed or not?
Because we never accessed `result['list']`, then the decoder may be clever enough to not decode it, and do so only when requested.

The documentation doesn't state anything about it, so it is unclear.

**Comment by rrousselGit** [comment]
Note that this question originates from me realizing that on dart-pad, `json.decode` returns a `_JsonMap` instead of your typical `_InternalHashMap` – and the implementation seems to have some lazy-loading

https://github.com/dart-lang/sdk/blob/a75ffc89566a1353fb1a0f0c30eb805cc2e8d34c/sdk/lib/_internal/js_dev_runtime/patch/convert_patch.dart#L146

**Comment by mraleph** [comment]
Both Dart VM and dart2js parse JSON eagerly. 

dart2js is lazy with regards to creating Dart objects from the underlying JavaScript objects. dart2js uses JS'es `JSON.parse` underneath which returns JS objects not Dart `Map`/`List` types.
