### ISSUE TITLE
improve testing of `dartdev test`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#40854]
We're currently hampered for our integration tests of `dartdev test`; the current tests want to run `pub get` on the pubspec in order to provision the package:test dependency for the tests.

A few options are:
- have the test infra create synthetic files instead of running `pub get` (pubspec.lock, .packages, .dart_tool/package_config.json`)
- mock out the use of Process and executing `pub run test` in the `test` command implementation, and have the tests send in mocks that don't spawn process. This would test the logic of the command, but would not tell us whether what we ship to end users works (if say package:test changes some conventions)

cc @jwren

**Comment by jwren** [comment]
@mit-mit reminded me this morning that it is his intention that with time that `dartdev` will have tools removed from their current repos, and included inline in `dartdev`, making this potential work mute.

Between the two options listed, neither would be trivial to implement, and neither would give me any additional confidence that a version of `dartdev` wouldn't ship that wouldn't break `dart test`.
