### ISSUE TITLE
Some tests need to be updated during/after NNBD unforking

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#40867]
There are some tests that are failing in NNBD mode because they test details of the API that are going to change but are insignificant enough to not be considered breaking:
service/step_through_mixin_from_sdk_test: update stack trace line numbers.

**Comment by a-siva** [comment]
Can you specify which tests need to be updated?

**Comment by liamappelbe** [comment]
I only know of service/step_through_mixin_from_sdk_test. I thought there might be more when I filed the bug, but I haven't seen any more.

@sstrickl mentioned that standalone_2/dwarf_stack_traces also depends on line numbers, but probably only the line numbers of the test itself, so it shouldn't be affected

**Comment by franklinyow** [comment]
Any update on this?

**Comment by liamappelbe** [comment]
Not really. There's nothing to be done until we unfork, then we just need a small change to update the test.

**Comment by franklinyow** [comment]
Moving to D29

**Comment by a-siva** [comment]
The unfork commit https://dart.googlesource.com/sdk/+/03ce33f80c50e1f8168fa4e61468969d8bd4eda5
contained changes for this test
