### ISSUE TITLE
annotated EnumConstantDeclaration nodes have null documentationComments

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#40865]
From, https://github.com/dart-lang/linter/issues/1396.

`EnumConstantDeclaration` AST nodes return a null `documentationComment` when constants are annotated.

Repro:

```dart
class A {
  const A([String msg]);
}

enum E {
  /// This doc is missing.
  @A('msg')
  e,
}
```

/fyi @stereotype441

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/138246

**Comment by pq** [comment]
Thanks @scheglov!
