### ISSUE TITLE
Analyzer defines bogus feature descriptions

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40860]
The file `pkg/analyzer/lib/src/dart/analysis/experiments.g.dart` defines two non-existent language features: `bogus-disabled`, a non-existent feature that is in the "disabled" state, and `bogus-enabled`, a non-existent feature that is in the "enabled" state.

These bogus features were not intended to be kept around in the long term; they were created solely to illustrate the file format while it was being developed.  However, at least one client (dartdoc) has begun to rely on them, so it is a breaking change to remove them.  (Issue to make dartdoc stop using these bogus features is here: https://github.com/dart-lang/dartdoc/issues/2156)
  
We should remove these "features" so that they don't become a source of confusion to clients.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/153707
