### ISSUE TITLE
Add group/filter parameter to TimelineTask API

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#40861]
It would be useful to have a `String filter` / `String group` parameter added to the [TimelineTask]( https://api.flutter.dev/flutter/dart-developer/TimelineTask/TimelineTask.html) constructor:

```
TimelineTask({
    TimelineTask parent,
    String filter,
})
```

The ability to group / filter async timeline events has been requested by dream (g3), and would be a useful feature in general. This would also be useful for HTTP timeline logging. Instead of manually having to pass a "filterKey" arg, we could pass the filter / group arg in from the specified parameter (like we do for `parent`).

In trace viewers (both chrome://tracing and DevTools), the events are grouped by name. If you want to group events by a custom category where many events with many names can be in the same group, there is no way for the trace viewer to understand that based on the trace. Adding this filter / group key would let us do this in DevTools.

**Comment by bkonyi** [comment]
I'm guessing we would want this functionality in the synchronous API as well?

**Comment by kenzieschmoll** [comment]
Wouldn't hurt to do so for consistency. The async API is probably higher priority as that is the one we are getting requests for, so this could be done in two stages: async first, sync second (since it sounds like that implementation may be a bit more involved).

**Comment by bkonyi** [comment]
Reopening to track the `Timeline` functionality.

**Comment by bkonyi** [comment]
Given our move to Perfetto, which doesn't support the `TimelineTask` parent functionality at this point in time, I'm going to assume we won't move forward with adding this property to `Timeline`'s APIs.
