### ISSUE TITLE
Dartpad shows error, Flutter ignores the error

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#40879]
I am not sure where to open this issue, apologies if this is the wrong place, but I think I discovered an inconsistency on the dart compiler.

On Flutter we have a `WillPopScope` that takes a callback on the form of `Future<bool> Function()`, like this:

```dart
...
WillPopScope(
  onWillPop: () async => false,
  child: new AlertDialog(
...
```

But I found someone on stackoverflow claiming we could just make it like this and it would work the same:

```dart
...
WillPopScope(
  onWillPop: () {},
  child: new AlertDialog(
...
```

This will return `null` and not a `bool`, so I got curious and tried it at Flutter and it really works, but on Dartpad I get an assertion error using this code:

```dart
typedef WillPopCallback = Future<bool> Function();
void main() async {  
  WillPopCallback call = () {};
  
  if (!await call()) {
    print('hi');
  }
}
```

>Error: Error: Assertion failed: "boolean expression must not be null"

And and info notification saying:

>This function has a return type of 'Future<bool>', but doesn't end with a return statement - line 4

I tried to investigate this further and Flutter calls this callback as this at `widgets\routes.dart`:

```dart
  @override
  Future<RoutePopDisposition> willPop() async {
    final _ModalScopeState<T> scope = _scopeKey.currentState;
    assert(scope != null);
    for (WillPopCallback callback in List<WillPopCallback>.from(_willPopCallbacks)) {
      if (!await callback())
        return RoutePopDisposition.doNotPop;
    }
    return await super.willPop();
  }
```

But on Flutter I get no warnings from the compiler nor any errors.

Are the lint options for the Dartpad different then the Dart compiler for Flutter? Even so, how could `if (!await callback())` even work if this is not a `bool`?

**Comment by mraleph** [comment]
> But on Flutter I get no warnings from the compiler nor any errors.

Could you provide a standalone repro? Running this

```dart
typedef WillPopCallback = Future<bool> Function();
void main() async {  
  WillPopCallback call = () {};
  
  if (!await call()) {
    print('hi');
  }
}
```

Yields `boolean expression must not be null` as it should. The `This function has a return type of 'Future', but doesn't end with a return statement` message is a _hint_ from an analyzer. You should get it if you run `flutter analyze` on your repo.

**Comment by feinstein** [comment]
Try this:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',      
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () {},
      child: Scaffold(
        appBar: AppBar(
          title: Text('My App'),
        ),
        body: Center(
          child: Text('Hi'),
        ),
      ),
    );
  }
}
```

The Analyzer should show the warning, but there will be no errors when you try to use the back button in an Android phone, and the app will behave as if the back button command was ignored, this way `() {}` behaves as `() async => false`.

**Comment by mraleph** [comment]
The exception is thrown, you can wrap `willPop` in the try catch and you will see that it happens. Then exception gets caught in `MethodChannel._handleAsMethodCall` which routes it back to the caller, which I suspect just drops in on the floor somewhere in the Flutter engine. 

Seems like Flutter bug to me.

**Comment by mraleph** [comment]
Yeah, you can look at https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/systemchannels/NavigationChannel.java - none of these handle error responses.

**Comment by feinstein** [comment]
Hmm, interesting, I couldn't see this bubbling on my debugger, I will open this at the Flutter repo than, thanks!
