### ISSUE TITLE
Performance regressions when iterating

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#40877]
In NNBD core libraries `get current` in iterators have additional cast `_current as E`.
The following benchmarks regress due to such cast in `_SyncIterator.current`:

```
ForInGeneratedLoop
Calls.IterableSyncStarIterablePolymorphic
Iteration.deeptree.syncstar
```

/cc @a-siva @rakudrama @lrhn @mraleph

**Comment by alexmarkov** [comment]
We can fix this regression by rewriting `return _current as E` in the following way:

```
final cur = _current;
return (cur != null) ? cur : cur as E;
```

**Comment by mraleph** [comment]
Should we have a separate issue to track if such pattern arises in user code and potential mitigations in compiler pipeline? 

If language level decision is made to prohibit mixed strong mode then we can add backend optimizations for this particular pattern and revert this change.

**Comment by alexmarkov** [comment]
Filed https://github.com/dart-lang/sdk/issues/40892.

**Comment by rakudrama** [comment]
@mraleph there would be two changes to revert 65254a4 since dart2js would be negatively impacted by reverting before it too can handle the case. This is why I want this solved in the CFE if possible.
