### ISSUE TITLE
Performance regression in List.generate with NNBD core libraries

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#40878]
Benchmark `Dromaeo.ObjectString` regressed with NNBD core libraries because `List.generate` factory constructor now uses `List<E>.filled` which makes another pass over elements, instead of `<E>[]..length = length`.

**Comment by rakudrama** [comment]
Where is `List.generate` used in `Dromaeo.ObjectString`?

**Comment by alexmarkov** [comment]
It is used in `String.split` if splitting by empty pattern.

**Comment by rakudrama** [comment]
Ok, that is only on the VM then since dart2js uses JavaScript's `String.split` where it can.
