### ISSUE TITLE
[DDC] `getLibraryUri` on a reified generic class type doesn't work

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#40883]
This is a recent regression with `Dart VM version: 2.8.0-dev.11.0 (Tue Mar 3 09:48:16 2020 +0100) on "linux_x64"`.

`package:dwds` uses the reified type to get the corresponding library URI:
https://github.com/dart-lang/webdev/blob/ec1ae51f5079bc9b948ab2cbef8ccbd4a7edf771/dwds/lib/src/debugging/metadata.dart#L62

**Comment by grouma** [comment]
cc @vsmenon

**Comment by sigmundch** [comment]
@nshahan - was this removed as part of deleting dart:mirrors?

**Comment by nshahan** [comment]
No it's still there. https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart#L259
