### ISSUE TITLE
Improve assist "Convert to single/double quoted string"

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#40888]
The assist _Convert to single/double quoted string_ is not available for some cases that could be handled. Moreover the convertion should remove backslashes when they are useless.

Here's what should works for _Convert to double quoted string_:

- `'it\'s'` -> `"it's"` (currently convert to `"it\'s"`)
- `'it"s'` -> `"it\"s"` (currently no assist suggested)

**Comment by FMorschel** [comment]
Fixed with https://dart-review.googlesource.com/c/sdk/+/384962.

**Comment by srawlins** [comment]
Excellent, thanks!
