### ISSUE TITLE
Remove the CFE package opt-out whitelist

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#40885]
"/sdk/pkg/front_end/lib/src/fasta/source/source_library_builder.dart" currently has a whitelist of packages that live in the SDK in order to opt them out of NNBD. I think this was set up before CFE had support for the package_config.json file.

It does support that now, I believe, and there is a package_config.json file checked in for the repo that sets every package to a language version that matches what its pubspec requests. Can we remove this whitelist? We are starting to trial migrate packages to null-safety, and right now we have to comment them out in CFE in order to get it to treat them as opted in.

cc @stereotype441

**Comment by johnniwinther** [comment]
Duplicate of #40775
