### ISSUE TITLE
SplayTreeMap ignores given comparator.

### ISSUE THREAD

**Issue by janniklind** [dart-lang/sdk#40891]
I am using a SplayTreeMap<String, dynamic>((s1, s2) => s2.compare(s1)) and when I get the keys in it, I expect them to be sorted by the comparator. However it seems that the strings are always sorted ascending, i.e. it default to the default Comparable implementation on the string.

**Comment by mraleph** [comment]
I am not sure I understand: in the code like this `SplayTreeMap<String, dynamic>((s1, s2) => s2.compare(s1))` you are using `String.compare` as a comparator - which is exactly what you get as the result, no?

**Comment by janniklind** [comment]
I would expect descending order and not ascending.

**Comment by janniklind** [comment]
@mraleph

**Comment by mraleph** [comment]
```dart
import 'dart:collection';

void main() {
  final x = SplayTreeMap<String, dynamic>((s1, s2) => s2.compareTo(s1));
  x["b"] = 1;
  x["c"] = 1;
  x["a"] = 1;
  print(x.keys);
}
```

Prints `(c, b, a)` just like you would expect. 

Can you provide a reproduction where it does not?
