### ISSUE TITLE
Optimize 'E? x; x as E' pattern in dart2js

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#40893]
With null safety this pattern is useful in certain cases, for example when implementing get current in iterator.

In weak mode this cast can be eliminated.
If we disallow opted-out libraries, then in strong mode we can optimize it to x != null ? x : null as E, which eliminates expensive cast in common case. (With opted-out libraries in strong mode eliminating redundant casts changes the semantics.)

See also VM sister issue to #40892

**Comment by alexmarkov** [comment]
This optimization was implemented in the VM a while ago, and I'd like to remove the workaround from core libraries (65254a45188a7813e8884573ca6974110abb80bf). Is it going to affect performance on dart2js? Are there any plans for implementing this optimization in dart2js, so we could be confident that dart2js performance is not affected by removing the workaround?

**Comment by rakudrama** [comment]
We will use the same optimization.
CL: https://dart-review.googlesource.com/c/sdk/+/172381

**Comment by rakudrama** [comment]
Implemented by 5d02bc0a0a6f132882ba9449a10fb98815a0a1e7
