### ISSUE TITLE
Do not check for existence of .analysis_options

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#40895]
When the analyzer is looking for the default analysis options for a package, it checks against `analysis_options.yaml` and `.analysis_options`. `.analysis_options` has been deprecated for a while. There is also a hint that shows up in the IDE asking users to migrate to `analysis_options.yaml`. 

So it should be safe at this time to remove the checks for `.analysis_options` while trying to find the default options file.

**Comment by keertip** [comment]
@kevmoo, wdyt?

/cc, @stereotype441 , @scheglov

**Comment by kevmoo** [comment]
@keertip – is this pretty well contained or is this something causing complexity and issues elsewhere?

Might be a good thing to take care if in Vnull-safety+1

**Comment by keertip** [comment]
This is well contained, will not cause complexity elsewhere. 

Looking at this now since it impacts the number of file access a stateless analysis would do every time it has to analyze a file. In a distributed system file access is more expensive than on a local machine.

**Comment by keertip** [comment]
https://dart-review.googlesource.com/c/sdk/+/138660

**Comment by kevmoo** [comment]
@keertip points for including the SHA where it was closed, too – 8329bd7ca81e4ff0706cbc9603e2a1ca295ee3a8 – makes it easier to find which release it's in!

**Comment by keertip** [comment]
Thanks Kevin!
