### ISSUE TITLE
Lose generic information across isolate

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#40919]
**code:** 
```
import 'dart:isolate';

void _process<T, U>(SendPort sendPort) async {
  var receivePort = new ReceivePort();
  sendPort.send(receivePort.sendPort);
  U Function(T input) mapper;
  await for (dynamic input in receivePort) {
    if (mapper == null) {
      mapper = input;
    } else {
      sendPort.send(mapper(input as T));
    }
  }
}

Stream<U> pmap<T, U>(List<T> list, U Function(T input) mapper, {int parallel = 1}) async* {
  ReceivePort receivePort = new ReceivePort();
  Isolate isolate = await Isolate.spawn(_process, receivePort.sendPort);
  SendPort sendPort;
  await for (dynamic result in receivePort) {
    if (sendPort == null) {
      sendPort = result;
      sendPort.send(mapper);
      for (T item in list) {
        sendPort.send(item);
      }
    } else {
      yield result;
    }
  }
  isolate.kill();
}

int mapper(int x) => x * x;

void main() async {
  List<int> foo = [1, 2, 3, 4];
  Stream<int> results = pmap(foo, mapper);
  await for (int value in results) {
    print(value);
  }
}
```

**Runtime exception:**
```type '(int) => int' is not a subtype of type '(dynamic) => dynamic'``` is generated when we execute ```mapper = input;```

**Expected:**
Ideally I could say something like: ```Isolate.spawn(_process<T, U>, receivePort.sendPort);``` so I wouldn't lose that type information when the function is executed in the other isolate.

**Comment by lrhn** [comment]
There is currently no way to specify a non-constant function reference as the isolate entry point. That means that `_process<T, U>` cannot be sent, only the reference to the generic `_process` function.
So, when the new isolate needs to call that function, it defaults to instantiating it to `_process<dynamic, dynamic>`.

What you *can* do is to send the function as *data* instead of as entry point.
```dart
class _Parameter2<T, U, P> {
  final P parameter;
  final void Function<T, U>(P) function;
  _Parameter2(this.function, this.parameter);
  void call() {
    _function<T, U>(parameter);  
  }
  static void entry(_Parameter2 parameters) {
    parameters();
  }
}
...

  Isolate.spawn(_Parameters2.entry, 
      _Parameters2<T, U, SendPort>(_process, receivePort.sendPort));
```

**Comment by PlugFox** [comment]
> What you _can_ do is to send the function as _data_ instead of as entry point.

Works great and solves all problems! Thank you very much!

**Comment by mkustermann** [comment]
We'll solve this issue as part of https://github.com/dart-lang/sdk/issues/36097.

**Comment by PlugFox** [comment]
> We'll solve this issue as part of #36097.

We are waiting for the addition of this feature, it will make possible to use isolates more often!
Thank you so much!

**Comment by mkustermann** [comment]
Closing this issue, merge into the more general https://github.com/dart-lang/sdk/issues/46623.
