### ISSUE TITLE
migration tool reanalyzes all `part`s in a library every time it analyzes one

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#40915]
In the debugger, I have seen AnalysisDriver._computeAnalysisResult calls with `withUnit = true` for every file in a multi-part library, which appears to force re-analysis of the full library.  Exactly why we are doing this and what we might do instead is TBD.  This is a big reason migration of web_ui is so slow.

**Comment by bwilkerson** [comment]
If you're using an `AnalysisSession` to perform analysis, then you can use `getSourceKind` to determine whether a file is a part. If you then use `getResolvedLibrary` for libraries and iterate over the already analyzed parts, you can keep track of which part's you didn't find a library for and analyze only those at the end (or signal an error if that's more appropriate).

**Comment by jcollins-g** [comment]
The pipeline migration uses is somewhat different.  The dartfix (shared with dartdev) pipeline uses `AnalysisServer.getResolvedUnit` recursively over a file tree built with Resource.getChildren().    The way the resolved units are processed is going to be challenging to build a similar fix for as a lot of context information isn't in the right place for us to dedupe the `getResolvedUnit` calls.... at least, so far.  Still looking.

**Comment by jcollins-g** [comment]
https://dart-review.googlesource.com/c/sdk/+/138940 now has a proposed fix.
