### ISSUE TITLE
dartdev does not notice if the analysis server disappears

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#40910]
If I kill -9 the analysis server dartdev launches, dartdev continues on waiting for a response from the analysis server.  Presumably other sorts of server problems (hangs, for instance) are also undetected.

**Comment by mit-mit** [comment]
cc @jwren shouldn't this be in the sept. list?

**Comment by mit-mit** [comment]
Tentatively tracking for Sept. to make sure this get's actively considered

**Comment by devoncarew** [comment]
@jwren - I believe that the two commands that currently launch an analysis server sub process are `analyze` and `migerate`.

Can you verify the behavior here for `dart analyze`? If you kill the analysis server process part way through analysis, does the analyze command behave reasonably (notice that the process terminated, print an error, fail w/ an error code, ...).

**Comment by jwren** [comment]
Working on this now.

**Comment by jwren** [comment]
Testing `analyze` and `migrate`, I was not able to reproduce this:

`    69193 killed     dart ~/src/github/dart-sdk/sdk/pkg/dartdev/bin/dartdev.dart migrate`

`    68830 terminated  dart ~/src/github/dart-sdk/sdk/pkg/dartdev/bin/dartdev.dart analyze`

Whenever I terminated the `dartdev` dart process with `killall dart` or `kill -9 <pid>`, I got the messages above, no hanging.
