### ISSUE TITLE
Unboxed instance calls are incompatible with no-table-dispatch

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#40911]
There are several runtime entries (and possibly a few stubs) which need to be updated, either to not use `ArgumentsDescriptor::NewBoxed` or to use `ArgumentsDescriptor::size_offset()` instead of `ArgumentsDescriptor::count_offset()`.

/cc @mkustermann @victoragnez @mraleph

**Comment by sjindel-google** [comment]
Currently we avoid this problem by disabling all unboxed calls if either `FLAG_use_table_dispatch` or `FLAG_use_bare_instructions` is false.

**Comment by mraleph** [comment]
The option to disable table dispatch is being removed by @alexmarkov

**Comment by mraleph** [comment]
https://dart-review.googlesource.com/c/sdk/+/225360
