### ISSUE TITLE
Analyzer gives `Object?` instead of `dynamic` for unspecified generic type.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#40928]
Repro example:

```
bool Function(T) predicate<T>(bool Function(T) fn) => (T val) => fn(val);

void main() {
  print(predicate((v) => v % 2 == 1)(3));
}
```
## Expected Result:

`dynamic` is inferred as the generic type and the code is warning/error free.

## Actual Result

`Object?` gets inferred for the generic type, and the following error is shown for the `v % 2` expression:

`error • The expression is nullable and must be null-checked before it can be used`

## Dart version:

2.8.0-edge.60a81b0f513d0baf3825955fdb834bed7ca04e23

**Comment by jakemac53** [comment]
cc @leafpetersen

**Comment by scheglov** [comment]
It looks as an intentional type inference change in NNBD.
https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#least-and-greatest-closure

**Comment by jakemac53** [comment]
Note that there are multiple methods in the `matcher` package which will be negatively affected by this, `predicate` in the example is a trimmed down version of a real method that has pretty heavy usage, almost all of which will be broken by this change.

I expect there is a lot of non-testing related code that would be broken by this as well, really any invocation of a generic function which takes a `Function(T)` as an argument is pretty likely to get broken (if the generic type argument is not able to be inferred or is not explicitly specified).

**Comment by natebosch** [comment]
> almost all of which will be broken by this change

Do we get the error in an opted out library?

**Comment by jakemac53** [comment]
> Do we get the error in an opted out library?

I would assume not, no. But this will still cause a lot of additional breakage when opting in.

**Comment by natebosch** [comment]
> this will still cause a lot of additional breakage when opting in.

FWIW I'd prefer to have that breakage (it's statically detectable and easy to fix by annotating with an explicit `dynamic`) if it means we can make this type of thing safer by default.

**Comment by jakemac53** [comment]
> FWIW I'd prefer to have that breakage (it's statically detectable and easy to fix by annotating with an explicit `dynamic`) if it means we can make this type of thing safer by default.

Ya, I could see that. Its annoying for tests specifically but for real code the safety would be nice.

**Comment by leafpetersen** [comment]
Sorry, I'd forgotten I made this change.  I do feel this change is an overall net positive, even if it causes more pain during the migration.  In general, the places where we still produce `dynamic` implicitly are all pain points for our users, and I'd like to keep moving the language away from this.

**Comment by jakemac53** [comment]
OK, closing then as WAI. I was not getting any warnings/errors from the VM so I think the CFE might still need to implement this.

**Comment by natebosch** [comment]
> I think the CFE might still need to implement this

Does anyone have a link handy to a tracking issue?
