### ISSUE TITLE
Rethrow is not working in a cascade try and catch

### ISSUE THREAD

**Issue by newbieflutter** [dart-lang/sdk#40942]
I have the following function. What is does is call the api and send the relevant information. Then if there is error code like 401 etc. Then I try to process the json message. Thus if it fails I do a try and catch. Eg. this is throw throw UnknownError('$code. Server error: Error in first catch'); but then it caught by the this outer try catch. The problem it stops there and complains exception occurred. How to overcome this issue of rethrow not working ?

```
catch (exception) {
  if(exception.toString().contains('SocketException')) {
    throw UnknownError('Network error: check connection');
  } else { 
    print("About to send unknownError ready");
    if(exception is UnknownError) {
      rethrow;
    }
```

```
static dynamic post(String url, String authToken, Map body) async {
    var uri = host + '/api1/' + url;
    print("uri is :" + uri);

    var fullToken = 'Bearer $authToken';
    try {
      final response = await http.post(uri,
                                       headers: {
                                         'Authorization': fullToken,
                                         'content-type': 'application/json'
                                         },
                                       body: json.encode(body));
      final code = response.statusCode;
      var errorCatch = "";
      if (code == 401 || code >= 500 || code >= 400) {
        try {
          var x = json.decode(response.body) as Map<String, dynamic>;
          try {
            var message = "";
            final responseJson = json.decode(response.body);
            if (responseJson != null) {
              message = responseJson['message'];
              if (code == 401) {
                throw AuthError('$code Auth Error: ' + message);
              } else if (code >= 500) {
                throw UnknownError('$code. Server error: ' + message);
              } else if (code >= 400) {
                throw Error4xx(' $code Wrong request : ' + message);
              }
            }
          } catch (err) {
            errorCatch = '$code. Server error: Error in first catch';
            print("couldn't extract err message from ${body ?? 'null'}");
            throw UnknownError('$code. Server error: Error in second catch');
            //'$code. Server error: ';
          }
        } catch (err) {
          errorCatch = '$code. Server error: Error in first catch';
          print("couldn't extract err message from ${body ?? 'null'}");
          throw UnknownError('$code. Server error: Error in first catch');
        }
      }
      return response.body;
    } catch (exception) {
      if (exception.toString().contains('SocketException')) {
        throw UnknownError('Network error: check connection');
      } else {
        print("About to send unknownError ready");
        if (exception is UnknownError) {
          rethrow;
        }
      }
    }
  }
```

**Comment by lrhn** [comment]
Can you be more precise with what you are experiencing? Which errors are reported? Can you add a `print` statement just before the `rethrow` to see that it does reach there?

When I test the code, it works and the `rethrow` is actually rethrowing the `UnknownError` it received from the `throw UnknownError('$code. Server error: Error in first catch');`. Since there is no catch around that `rethrow`, the error becomes uncaught.

**Comment by newbieflutter** [comment]
Hi Lrhn,
             Ok let me explain. I have this scenario where this happens throw UnknownError('$code. Server error: Error in first catch');. So then when this is thrown it reach here. Yes I have added a print print("About to send unknownError ready"); and yes it reaches there thats confirmed. So I dont get you no catch around rethrow ? Cause there is catch on top where else to add the catch?

```
catch (exception) {
      if (exception.toString().contains('SocketException')) {
        throw UnknownError('Network error: check connection');
      } else {
        print("About to send unknownError ready");
        if (exception is UnknownError) {
          rethrow;
        }
      }
```

**Comment by lrhn** [comment]
In the example code you provided, the `rethrow` is in the `catch` of the outer-most/top `try`/`catch` of the code.
```dart
   try {
     // rest of code here.
    } catch (exception) {
      if (exception.toString().contains('SocketException')) {
        throw UnknownError('Network error: check connection');
      } else {
        print("About to send unknownError ready");
        if (exception is UnknownError) {
          rethrow;
        }
      }
    }
```
That means that when the `rethrow` executes, it will re-throw the `exception` and stack trace that was caught by that `catch`. the `rethrow` thrown error will become the effect of that entire `try`/`catch` statement. That code is not inside another `try` body, so the (re-)thrown exception becomes an uncaught error.

What  did you *expect* the code to do?

**Comment by newbieflutter** [comment]
Hi Lrhn,
             Yes you are right. The rethrow is in the outer-most try/catch of the codes. Actually let me explain what I am trying to achieve is simple.

1. I first call the `http.post `so I send the parameters to my api server.

```
final response = await http.post(uri,
                                       headers: {
                                         'Authorization': fullToken,
                                         'content-type': 'application/json'
                                         },
                                       body: json.encode(body));
```
2. I get this results and I check the results status code.  final code = response.statusCode;

3. If the status code is` if (code == 401 || code >= 500 || code >= 400)` {

4. I will do this that is to json.decode the `final responseJson = json.decode(response.body);`

5. If so happens the `json.decode(response.body)` fails because the return results is not in json format.  Then I catch in the first try/catch inside the outer try/catch. So it generates this throw UnknownError('$code. Server error: Error in first catch');. So this is where I am stuck? How to send it without any issue like how I am getting stuck now. The problem now is that when this is thrown its caught by the catch of the most outer try/catch?

```
try {
   // json processing codes.
} catch (err) {
          errorCatch = '$code. Server error: Error in first catch';
          print("couldn't extract err message from ${body ?? 'null'}");
          throw UnknownError('$code. Server error: Error in first catch');
        }
```

I hope I am clear now with the steps being broken down.

**Comment by newbieflutter** [comment]
Hi Lrhn,
              Is my explanation above is better now? Else do let me know how to correct it further?

**Comment by newbieflutter** [comment]
Hi Guys,
               Any help on this issue ? Thank you.

**Comment by lrhn** [comment]
Still not entirely sure I understand what it is that you want to achieve, and what it is that is happening instead. Everything up to step 5 is clear from the code, but then it's hard for me to figure out what you *want* to happen ("not being stuck" isn't descriptive enough, sorry :smile:).

Which throws should be caught where, and what should the end result of the code be?

**Comment by newbieflutter** [comment]
Hi Lrhn,
            Ok let me focus on step 5. 
Example say the result code is 404.

```
<!DOCTYPE html>
<html>
    <head>
....
...
 </head>
    <body>
                    <div class="exception-summary">
                <div class="container">
                    <div class="exception-message-wrapper">
                        <h1 class="break-long-words exception-message">Sorry, the page you are looking for could not be found.</h1>
```
So the above will be the content of the response.body. Thus next I will run this code
`var x = json.decode(response.body) as Map<String, dynamic>;` and it fails right cause its not in a json format.
and it will be caught here.

```
catch (err) {
            errorCatch = '$code. Server error: Error in first catch';
            print("couldn't extract err message from ${body ?? 'null'}");
            throw UnknownError('$code. Server error: Error in second catch');
            //'$code. Server error: ';
          }
```
then next its caught by the most outer try/catch that is so here its where I get the exception error at the rethrow?
```
 catch (exception) {
      if (exception.toString().contains('SocketException')) {
        throw UnknownError('Network error: check connection');
      } else {
        print("About to send unknownError ready");
        if (exception is UnknownError) {
          rethrow;
        }
      }
    }
```
Hope I am more clearer now. Thank you lrhn for helping me out.

**Comment by lrhn** [comment]
Currently, the error thrown by `jsonDecode` is caught by the innermost catch. It then throws an `UnknownError` containing the text "Error in second catch".
That error is thrown by the middle catch. That code throws an `UnknownError` containing the text "Error in first catch".
That error is caught by the outermost catch. It is then rethrown (because it's an `UnknownError`) and becomes uncaught.

Do you want the error to skip past the middle catch?
If so, there are a number of possible approaches.

If you want all `UnknownError` objects to pass the middle catch, you can do add an extra case to the middle try/catch:
```dart
try { 
   ....
} on UnknownError {
  rethrow;
} catch (err) {
  ... all the rest ...
}
```
This will avoid any `Unknown` error from being caught by the middle catch.
I think that's the simplest approach.

Alternatively, you can have a boolean variable, say `ignoreError`, which you can set to true before throwing an error which the middle catch should ignore, and then start the middle catch block with:
```dart
  if (ignoreError) rethrow;
```

**Comment by newbieflutter** [comment]
Hi Lrhn,
              I dont get you when you say this` That error is caught by the outermost catch. It is then rethrown (because it's an UnknownError) and becomes uncaught.`". Why is it uncaught when its  catching?  I dont get is why when it firstly  throw this `throw UnknownError('$code. Server error: Error in first catch');` it does go to the source of it meaning the code which call this function? Why is it caught by the outer most try/catch ?

Secondly another scenario say if the error is only caught in the middle part of the try/catch so then in this scenario what is to be done? 

What is the most complete solution where I can cater for all scenario 
1. Error originated by the inner most try/catch
2. Error originated by the middle try/catch

**Comment by newbieflutter** [comment]
Hi Lrhn,
             I tried this.

```
try {
     // rest of code here.
    } 
  on UnknownError {
       print("special on unkwonerrro");
       throw UnknownError("TEST");
    } 
   catch (exception) {
      if (exception.toString().contains('SocketException')) {
        throw UnknownError('Network error: check connection');
      } else {
        print("About to send unknownError ready");
        if (exception is UnknownError) {
          try{
             print("try in the catch");
             throw ("error");
          }
          catch(exception){
                print("Catch in catch ");
                throw UnknownError('Unknown connection');
          }
        }
      }
    }
```
In the outer most try/catch I put another try/catch in to work out the throw but still same issue. Now it comes and stop here  throw UnknownError('Unknown connection'); and give same error.  Exception has occurred. UnknownError.

Even I added this ```
on UnknownError {
       print("special on unkwonerrro");
       throw UnknownError("TEST");
    } 
```

Its really weird why it does go pass this section of the codes and stucked always there with the exception.

**Comment by newbieflutter** [comment]
Hi Lrhn,
              I even tried just raw. Still it fails example . Whenever I generated the throw it get stucked and say exception occured. How to resolve this weird behavior?
```
static dynamic post(String url, String authToken, Map body ) async {
		var uri = host + '/api1/'+ url;
    print("uri is :"+uri);
   
    var fullToken = 'Bearer $authToken';
    // print("fullToken send"+authToken);
		try {

			final response = await http.post(
				uri,
        headers: {
					'Authorization': fullToken,
          'content-type': 'application/json'
				},
				body: json.encode(body)
			);

			final code = response.statusCode;
      //print("Network util post reply code:"+code.toString());
      //print("Network util post reply response body:"+response.body);
			if(code==401){

				throw AuthError('$code Auth Error: '+response.body);
			}
			else if(code>=500){

				throw UnknownError('$code. Server error: '+response.body);
			}
			else if(code>=400){

				throw Error4xx(' $code Wrong request : '+response.body);
			}


			return response.body;

		} 
    on UnknownError{
        throw UnknownError('Unknown');    
    }
    on AuthError{
       throw AuthError('AuthErro'); 
    }
    on Error4xx{
       throw Error4xx('Er4xxx');  
    }
    on SocketException {
        throw UnknownError('Network error: check connection');
    }
    /*catch (exception) {
			print(exception);
			if(exception.toString().contains('SocketException')) {
				 throw UnknownError('Network error: check connection');
			} else {
				 throw exception;
			}
		}*/
	}

```

**Comment by lrhn** [comment]
Sorry I did not come back to this. Does this still need resolution?
After reading the last messages, I'm still a not sure what behavior you *want*, and what it means to be "stuck".

Your examples all throw (or rethrow) an `UnknownError` and do not *catch* that `UnknownError`, so the system reports that an (uncaught) exception has happened. Uncaught in the sense that the exception was thrown and wasn't caught again until it hit the event loop.

**Comment by mit-mit** [comment]
Closing as assumed stale
