### ISSUE TITLE
NNBD. No error in analyzer for initialized covariant final late variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40941]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables)

> An instance variable declaration may be declared covariant iff it introduces an implicit setter.

But, analyzer does not report an error for the following code

`covariant late final int v1 = 42; // error in VM, no error in analyzer`

Here we have late final variable with an initializing expression, so no implicit setter introduced and therefore there must be a compile time error

dartanalyzer version 2.8.0-dev.12.0

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/139322
