### ISSUE TITLE
NNBD. No error in VM for getter and setter with the same basename but different types

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40945]
NNBD [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings) reads

> It is an error if a class has a setter and a getter with the same basename where the return type of the getter is not a subtype of the argument type of the setter. Note that this error specifically requires subtyping and not assignability and hence makes no exception for dynamic.

Analyzer correctly reports an error in the code below but VM does not

```dart
class C {
  void set test(int v) {}
  dynamic get test => 3.14;
}

main() {
  C c = new C();
  c.test = 1;
  c.test;
}
```
There must be an error in VM as well

Tested on `Dart VM version: 2.8.0-dev.12.0 (Thu Mar 5 11:45:50 2020 +0100) on "windows_x64"`

**Comment by franklinyow** [comment]
@a-siva The description suggest this is a VM issue, can you take a look and give it a priority label?

**Comment by eernstg** [comment]
This is a missing compile-time error concerned with member signature constraints, and I would expect that to be handled by the common front end. @johnniwinther, the priority of this issue would essentially be the same as the priority of https://github.com/dart-lang/sdk/issues/41623; do you agree?

**Comment by johnniwinther** [comment]
Yes. It's a P2.

**Comment by franklinyow** [comment]
@johnniwinther Since it's a P2, do we intended to resolve this in Jan?

**Comment by johnniwinther** [comment]
It has been fixed for some time. Adding a test to verify: https://dart-review.googlesource.com/c/sdk/+/177606
