### ISSUE TITLE
NNBD. No error in VM for class with generative constructor and non-initialized variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40951]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings)

> It is an error if a class declaration declares an instance variable with a potentially non-nullable type and no initializer expression, and the class has a generative constructor where the variable is not initialized via an initializing formal or an initializer list entry, unless the variable is marked with the late modifier

This error is reported in analyzer but no error in VM. For example, the following code works without any errors in VM

```dart
class A {}

class C1 {
  A a;
  String s;

  C1() {}
//^^
// [analyzer] unspecified
// [cfe] unspecified
}

abstract class C2 {
  A a;
  String s;

  C2() {}
//^^
// [analyzer] unspecified
// [cfe] unspecified
}

class C3 extends C2 {}

main() {
  new C1();
  new C3();
}
```
Dart VM version: 2.8.0-dev.12.0 (Thu Mar 5 11:45:50 2020 +0100) on "windows_x64"

**Comment by johnniwinther** [comment]
An error is report now, but not at the line that the test expects! We report on the field and not on the constructor.

**Comment by stefantsov** [comment]
Should we update the line on which the error is reported or the test?

**Comment by johnniwinther** [comment]
This is mostly done. Test update requested in https://github.com/dart-lang/co19/issues/588

Note that co19/LanguageFeatures/nnbd/static_errors_A05_t14 not fixed yet because of the pending language issue https://github.com/dart-lang/language/issues/868

**Comment by leafpetersen** [comment]
Is this still open?

**Comment by sgrekhov** [comment]
Retested on `Dart SDK version: 2.10.0-79.0.dev (dev) (Mon Aug 31 17:07:47 2020 -0700) on "windows_x64"`
There are errors in CFE now, but CFE reports 4 errors here and analyzer only 2
```dart
class A {}

class C1 {
  A a;  // VM Error: Field 'a' should be initialized because its type 'A' doesn't allow null. 
  String s; // VM Error: Field 's' should be initialized because its type 'String' doesn't allow null.

  C1() {} // Analyzer error - Non-nullable instance field 's' must be initialized.
}

abstract class C2 {
  A a;  // VM Error: Field 'a' should be initialized because its type 'A' doesn't allow null. 
  String s; // VM Error: Field 's' should be initialized because its type 'String' doesn't allow null.

  C2() {} // Analyzer error - Non-nullable instance field 'a' must be initialized.
}

class C3 extends C2 {}

main() {
  new C1();
  new C3();
}
```

**Comment by scheglov** [comment]
It seems that this is a presentation artifact in analyzer cli.
We do report all errors, but them they are probably coalesced into one.
![image](https://user-images.githubusercontent.com/384794/92197159-d603df00-ee25-11ea-8604-c5d6e35751b4.png)

**Comment by stefantsov** [comment]
Resolved by https://github.com/dart-lang/sdk/commit/734da2ca2cd0119140a00340ee2ffe47372fc956.
