### ISSUE TITLE
NNBD. No error in VM if optional non-nullable parameter has no default value

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40954]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings)

> It is an error if an optional parameter (named or otherwise) with no default value has a potentially non-nullable type except in the parameter list of an abstract method declaration.

In fact, analyzer reports this error but VM doesn't. For example, the following code works in VM without any error

```dart
class A {}

class C {
  static void test1(var v, [A a]) {}
//                            ^
// [analyzer] unspecified
// [cfe] unspecified

  static void test2(var v, {A a}) {}
//                            ^
// [analyzer] unspecified
// [cfe] unspecified

  void test11(var v, [A a]) {}
//                      ^
// [analyzer] unspecified
// [cfe] unspecified

  void test22(var v, {A a}) {}
//                      ^
// [analyzer] unspecified
// [cfe] unspecified
}

void test1(var v, [A a]) {}
//                   ^
// [analyzer] unspecified
// [cfe] unspecified

void test2(var v, {A a}) {}
//                   ^
// [analyzer] unspecified
// [cfe] unspecified

main() {
}

```

Dart VM version: 2.8.0-dev.12.0 (Thu Mar 5 11:45:50 2020 +0100) on "windows_x64"

**Comment by a-siva** [comment]
I believe this needs the --force-nnbd-checks guard in CFE to be removed which is tracked in https://github.com/dart-lang/sdk/issues/40980.
This issue can be closed a dup of that issue.
