### ISSUE TITLE
[regression] new analyzer error with for_in_of_invalid_element_type in 2.8.0-dev.13.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40962]
```dart
void func(List errorReports) {
  for (final List error in errorReports.skip(1)) {
    print(error);
  }
}
```

```
  error • The type 'Iterable<dynamic>' used in the 'for' loop must implement Iterable with a type argument that can be assigned to 'List<dynamic>'. • lib/silly.dart:2:28 • for_in_of_invalid_element_type
```

This did not cause errors in previous SDKs!

**Comment by scheglov** [comment]
I see no errors in my test package with this code.
Do you have implicit downcasts disabled?

**Comment by kevmoo** [comment]
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

**Comment by scheglov** [comment]
I fixed this case to report the warning in this case.
The reason is that `for-in` is specified as semantically equivalent to other Dart code, for which we would report the warning.
See `17.6.2 For-in` in https://spec.dart.dev/DartLangSpecDraft.pdf

**Comment by kevmoo** [comment]
@scheglov so we're calling this "by design"?

**Comment by kevmoo** [comment]
although this is an "error" not a warning

**Comment by scheglov** [comment]
Yes, WAI, by design, etc.

**Comment by kevmoo** [comment]
> Yes, WAI, by design, etc.

Should it be a warning or an error?

**Comment by scheglov** [comment]
The spec does not say.
In this code, with implicit casts disabled, it is an error:
```dart
main(dynamic a) {
  int b = a;
}
```

So, for consistency, it should be an error for `for-in`.

**Comment by kevmoo** [comment]
Closing as "by design"
