### ISSUE TITLE
NNBD: Dart crashes in the recent roll with co19/LanguageFeatures/nnbd/exports_A01_functions_t16

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40973]
Dart crashes in the recent roll with co19/LanguageFeatures/nnbd/exports_A01_functions_t16 test in cfe-strong-linux mode.

Here is a link to the log file:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8886683934903408992/+/steps/test_results/0/logs/new_test_failures__logs_/0

There is no problem in dartdevk-strong-linux-release-chrome and analyzer-asserts-strong-linux results. I am also not able to reproduce it on the recent release (2.8.0-dev.12.0) on my Windows desktop.

Sample output is:

> --- Command "fasta" (took 150ms):
> (cd /b/s/w/ir/cache/builder/sdk/ ; DART_CONFIGURATION=ReleaseX64NNBD ./out/ReleaseX64NNBD/dart ./pkg/front_end/tool/_fasta/compile.dart --verify -o ./out/ReleaseX64NNBD/generated_compilations/fasta/tests_co19_src_LanguageFeatures_nnbd_exports_A01_functions_t16/out.dill --platform ./out/ReleaseX64NNBD/vm_platform_strong.dill --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong --packages=./.packages ./tests/co19/src/LanguageFeatures/nnbd/exports_A01_functions_t16.dart )
> 
> exit code:
> 253
> 
> stdout:
> tests/co19/src/LanguageFeatures/nnbd/exports_A01_functions_t16.dart:23:3: Error: Type argument 'Null?' doesn't conform to the bound 'Never' of the type variable 'T' on 'testGenericNever'.
> Try changing type arguments so that they conform to the bounds.
>   testGenericNever<Null>();
>   ^
> tests/co19/src/LanguageFeatures/nnbd/exports_A01_opted_in_lib.dart:115:23: Context: This is the type variable whose bound isn't conformed to.
> void testGenericNever<T extends Never>() { Expect.equals(typeOf<Never>(), T);}
>                       ^
> 
> stderr:
> Unhandled exception:
>   Crash when compiling file:///b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/exports_A01_functions_t16.dart,
> at character offset 794:
> type 'WhereIterable<TypeArgumentIssue>' is not a subtype of type 'Set<TypeArgumentIssue>'
> #0      SourceLibraryBuilder.checkBoundsInStaticInvocation (package:front_end/src/fasta/source/source_library_builder.dart:3454:9)
> #1      InferenceVisitor.visitStaticInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:5025:24)
> #2      StaticInvocation.accept1 (package:kernel/ast.dart:3582:9)
> #3      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2002:27)
> #4      InferenceVisitor.visitExpressionStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:707:49)
> #5      ExpressionStatement.accept (package:kernel/ast.dart:4731:43)
> #6      TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3393:24)
> #7      InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:303:20)
> #8      InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:324:30)
> #9      Block.accept (package:kernel/ast.dart:4759:43)
> #10     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3393:24)
> #11     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:2043:39)
> #12     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:957:28)
> #13     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:916:14)
> #14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:954:7)
> #15     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:353:5)
> #16     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2544:14)
> #17     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2382:14)
> #18     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:500:14)
> #19     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
> #20     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:349:14)
> <asynchronous suspension>
> #21     Loader.buildBodies (package:front_end/src/fasta/loader.dart:238:15)
> #22     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:344:20)
> #23     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> #24     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:342:12)
> #25     CompileTask.compile (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:321:28)
> <asynchronous suspension>
> #26     BatchCompiler.batchCompileImpl (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:189:16)
> #27     BatchCompiler.batchCompileArguments.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:164:39)
> #28     withGlobalOptions.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/command_line.dart:530:13)
> #29     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
> <asynchronous suspension>
> #30     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
> #31     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
> #32     new Future.sync (dart:async/future.dart:222:31)
> #33     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
> #34     _rootRun (dart:async/zone.dart:1134:13)
> #35     _CustomZone.run (dart:async/zone.dart:1038:19)
> #36     _runZoned (dart:async/zone.dart:1537:10)
> #37     runZoned (dart:async/zone.dart:1480:12)
> #38     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
> #39     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
> #40     withGlobalOptions (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/command_line.dart:523:26)
> #41     BatchCompiler.batchCompileArguments.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:163:15)
> #42     runProtectedFromAbort (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/command_line.dart:578:24)
> #43     BatchCompiler.batchCompileArguments (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:162:12)
> #44     BatchCompiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:144:19)
> <asynchronous suspension>
> #45     batchEntryPoint (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:129:8)
> #46     main (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/batch.dart:7:33)
> #47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
> #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
> 
> 
> #0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:959:7)
> #1      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:353:5)
> #2      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2544:14)
> #3      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2382:14)
> #4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:500:14)
> #5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
> #6      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:349:14)
> <asynchronous suspension>
> #7      Loader.buildBodies (package:front_end/src/fasta/loader.dart:238:15)
> #8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:344:20)
> #9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
> #10     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:342:12)
> #11     CompileTask.compile (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:321:28)
> <asynchronous suspension>
> #12     BatchCompiler.batchCompileImpl (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:189:16)
> #13     BatchCompiler.batchCompileArguments.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:164:39)
> #14     withGlobalOptions.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/command_line.dart:530:13)
> #15     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
> <asynchronous suspension>
> #16     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
> #17     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
> #18     new Future.sync (dart:async/future.dart:222:31)
> #19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
> #20     _rootRun (dart:async/zone.dart:1134:13)
> #21     _CustomZone.run (dart:async/zone.dart:1038:19)
> #22     _runZoned (dart:async/zone.dart:1537:10)
> #23     runZoned (dart:async/zone.dart:1480:12)
> #24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
> #25     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
> #26     withGlobalOptions (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/command_line.dart:523:26)
> #27     BatchCompiler.batchCompileArguments.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:163:15)
> #28     runProtectedFromAbort (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/command_line.dart:578:24)
> #29     BatchCompiler.batchCompileArguments (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:162:12)
> #30     BatchCompiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:144:19)
> <asynchronous suspension>
> #31     batchEntryPoint (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/entry_points.dart:129:8)
> #32     main (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/batch.dart:7:33)
> #33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
> #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
> 

>

**Comment by johnniwinther** [comment]
This has been fixed.
