### ISSUE TITLE
VM should report null safety compilation errors

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#40972]
`main.dart`:
```dart
void main() {
  int number = null;

  print(number);
}
```

Repro steps:
1. `./tools/build.py --mode release --arch x64 --nnbd create_sdk`
1. `sdk/xcodebuild/ReleaseX64NNBD/dart-sdk/bin/dart --enable-experiment=non-nullable main.dart`

**Expected result**:

```
main.dart:2:16: Error: A value of type 'Null' can't be assigned to a variable of type 'int'.
  int number = null;
               ^
```

**Actual result**:
```
null
```

**Comment by mit-mit** [comment]
cc @johnniwinther, @a-siva mentioned that the CFE might need to set some flag?

**Comment by johnniwinther** [comment]
The CFE currently do not show errors/warnings by default. These will be enable once sdk_nnbd builds without warnings, if enabled.

**Comment by a-siva** [comment]
I believe the sdk_nndb builds for the VM do not show any warnings now, let us know if you still see warnings.

**Comment by mit-mit** [comment]
@johnniwinther any news on this?

**Comment by johnniwinther** [comment]
The warnings/errors are now shown by default. The CL for turning warnings into errors is in review.

**Comment by johnniwinther** [comment]
This is done.

**Comment by mit-mit** [comment]
Working great now, thanks!

```console
mit-macbookpro4:sdkrepo mit$ sdk/xcodebuild/ReleaseX64NNBD/dart-sdk/bin/dart --enable-experiment=non-nullable repro/main.dart
repro/main.dart:2:16: Error: A value of type 'Null?' can't be assigned to a variable of type 'int'.
  int number = null;
```
