### ISSUE TITLE
dartdevc, compiling only rxdart with --modules es6 exports window instead of window$

### ISSUE THREAD

**Issue by MagicPoulp** [dart-lang/sdk#40976]
* dev_compiler
I must use dartdevc because dart2js has no option that I know for es6.
Compiling only rxdart with --modules es6 exports window instead of $window. If I rewrite the code with window$, then some complex code could be run without issues.

make a file base_bloc.dart that contains only the following:
import 'package:rxdart/rxdart.dart';

Compile it. It is required to put the option --modules es6
dartdevc --modules es6 base_bloc.dart -o out.js

and open the file and search for window as
prerequisites:
Make a very basic empty fold with a pub.yaml
name: bloc
description: Bloc Dart package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.23.1
  tuple: ^1.0.3
  meta: ^1.1.8

dev_dependencies:
----
run pub get

**Comment by nshahan** [comment]
Apologies for the late response here. Can you share a little more about your use case? What you are describing seems related to our variable renaming when there is already a symbol with the same name in scope.

It sounds like you might be trying to compile a deployable es6 module that will just work with the ecosystem of other es6 modules. That isn't a supported use case for the dev_compiler and we strongly recommend against deploying a development build.

**Comment by MagicPoulp** [comment]
Too old I close
