### ISSUE TITLE
NNBD: dartdevk-strong-linux-release-chrome build fails with assert when compare non-nullable variable with null.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40978]
Dartdevk-strong-linux-release-chrome build fails with assert when compare non-nullable variable with null in the recent roll.

Here is a link to the log file:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8886683934903409008/+/steps/test_results/0/logs/new_test_failures__logs_/0

Failing co19 tests are:
- LanguageFeatures/nnbd/overriding/override_checking_A03_t01
- LanguageFeatures/nnbd/overriding/override_checking_A03_t04

The same tests passes in cfe-strong-linux and analyzer-asserts-strong-linux results. I am also not able to reproduce it on the recent release (2.8.0-dev.12.0) on my Windows desktop.

Sample output is:

> --- Command "dartdevk" (took 203ms):
> DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart-sdk/bin/dartdevc --enable-experiment=non-nullable --enable-experiment=non-nullable --ignore-unrecognized-flags --no-summarize -o /b/s/w/ir/cache/builder/sdk/out/ReleaseX64NNBD/generated_compilations/dartdevk-checked-sdk/tests_co19_src_LanguageFeatures_nnbd_overriding_override_checking_A03_t01/override_checking_A03_t01.js /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A03_t01.dart -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/async_helper.dill=async_helper -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/expect.dill=expect -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/js.dill=js -s /b/s/w/ir/cache/builder/sdk/out/ReleaseX64NNBD/gen/utils/dartdevc/pkg_kernel/meta.dill=meta (working directory: /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/overriding)
> 
> exit code:
> 0
> 
> --- Command "chrome" (took 493ms):
> /b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:46327/root_build/generated_tests/dartdevk-chrome-checked-sdk/tests_co19_src_LanguageFeatures_nnbd_overriding_override_checking_A03_t01/test.html?crossOriginPort=45323
> 
> Runtime error:
> Error: Assertion failed: org-dartlang-app:/tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A03_opted_in_lib.dart:21:26
> i != null
> "A null value was passed into a non-nullable parameter i"
> i != null
> "A null value was passed into a non-nullable parameter i"
>     at Object.throw_ [as throw] (http://127.0.0.1:46327/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:3957:11)
>     at Object.nullFailed (http://127.0.0.1:46327/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:3895:17)
>     at override_checking_A03_opted_out_lib.LEGACY_ARGS_2.new.test_int (http://127.0.0.1:46327/root_dart/out/ReleaseX64NNBD/generated_compilations/dartdevk-checked-sdk/tests_co19_src_LanguageFeatures_nnbd_overriding_override_checking_A03_t01/override_checking_A03_t01.js:92:27)
>     at Object.main (http://127.0.0.1:46327/root_dart/out/ReleaseX64NNBD/generated_compilations/dartdevk-checked-sdk/tests_co19_src_LanguageFeatures_nnbd_overriding_override_checking_A03_t01/override_checking_A03_t01.js:57:8)
>     at testMainWrapper (http://127.0.0.1:46327/root_build/generated_tests/dartdevk-chrome-checked-sdk/tests_co19_src_LanguageFeatures_nnbd_overriding_override_checking_A03_t01/test.html?crossOriginPort=45323:103:124)
> 
> Deobfuscated error and stack:
> Error: Assertion failed: org-dartlang-app:/tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A03_opted_in_lib.dart:21:26
> i != null
> "A null value was passed into a non-nullable parameter i"
> i != null
> "A null value was passed into a non-nullable parameter i"
>     at Object.throw_                                                  out/ReleaseX64NNBD/gen/utils/dartdevc/kernel/amd/dart_sdk.js 3957:11
>     at Object.nullFailed                                              ../../../../../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 32:5
>     at override_checking_A03_opted_out_lib.LEGACY_ARGS_2.new.test_int ../../../../../tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A03_opted_in_lib.dart 21:26
>     at Object.main                                                    ../../../../../tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A03_t01.dart 42:5
>     at testMainWrapper                                                out/ReleaseX64NNBD/generated_tests/dartdevk-chrome-checked-sdk/tests_co19_src_LanguageFeatures_nnbd_overriding_override_checking_A03_t01/test.html 103:124
> 
> 
> exit code:
> 0
>

**Comment by eernstg** [comment]
It looks like this dynamic error is justified by the program: A null is passed, and the inherited method declares that it accepts an `int` (a non-nullable type). So maybe this issue is arising because DDC has introduced dynamic checks in a number of situations where the unsoundness justifies a check, but there used to be no such checks because they are not required by null-safety rules as such.

Cf. https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#automatic-debug-assertion-insertion.

If so, then similar issues would be expected in a number of tests where unsound situations have previously been allowed to exist, but where these checks are now failing.

**Comment by nshahan** [comment]
There are no longer any failing tests under `co19/LanguageFeatures/nnbd/overriding`. 

I believe this is due to tests be reworked, and we have since scaled back on the settings where we insert non-null assertions by default in DDC.
