### ISSUE TITLE
pub get does not run pub get on dependencies

### ISSUE THREAD

**Issue by MagicPoulp** [dart-lang/sdk#40979]
Not sure if this is a real issue.

if I have a library in a folder bloc, with a pubspec.yaml
it will start with library 'block'; and then an export not an import.

in another folder app, I can define a dependency to ../bloc
dependencies:
  bloc:
    path: ../bloc

if I run pub get in the app folder, it will only get the dependencies locally. I must go myself in bloc and run pub get again here.

Would be much nicer if one could have a recursive pub get in all subfolders.
and also one must run cd to move into the directory before pub get works.

**Comment by srawlins** [comment]
Sorry, this is not a feature that pub will support. The pubspec.lock file, and the downloaded packages that each package depends on, needs to be maintained package-by-package. `pub get` needs to be run within each package.
