### ISSUE TITLE
Spurious 'constant constructor can't call a non-constant superconstructor' error

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#40982]
Cf. https://github.com/dart-lang/sdk/issues/32223#issuecomment-596677710, the front end seems to get confused about constructors during mixin application if there is a static variable declaration in a mixin:

```dart
class A {
  const A();
}

mixin B {
  static const int value=1; // This causes the error, with and without `const`.
  void printStuff() => print('Hello from B!');
}

class C extends A with B {
  const C();
}
```

The response with a fresh front end (commit 5ae444877974f72457c32a1519fa9aee33e9da4a) is as follows:

```
n002.dart:14:9: Error: A constant constructor can't call a non-constant super constructor.
  const C();
        ^
```

**Comment by lrhn** [comment]
It's a sympton of the mixin application constructor not being const.
Example:
```dart
class C {
  final x;
  const C([this.x = 0]) : assert(x != null);
}
mixin M {}
class D = C with M;
main() {
  print(const D().x);
}
```
The analyzer warns that "The constructor being called isn't a const constructor - line 8". That constructor is the constructor of the mixin application, which should be constant.

**Comment by scheglov** [comment]
BTW, @srawlins fixed this in analyzer in 9f6c372228162140d87c883b6077cca84b89d7e6.

**Comment by srawlins** [comment]
Ah ha, so I did!

**Comment by scheglov** [comment]
Hm... This issue is for CFE, but it references another issue that says that analyzer reports an error. So, I just provided some context. But I think we should leave this CFE issue open.

**Comment by srawlins** [comment]
Oops; thanks

**Comment by artob** [comment]
Running into this with my Flutter plugin, on the beta channel. Is this fixed on any Flutter release channel as yet?

**Comment by Miiite** [comment]
I just encountered this, on the stable channel (v1.22.2)

**Comment by marcglasberg** [comment]
I am also having this problem.
