### ISSUE TITLE
Make all NNBD-related warnings into errors in weak mode

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#40981]
Context: https://github.com/dart-lang/language/issues/851

**Comment by dcharkes** [comment]
@stefantsov why did some ffi_2 tests turn red here? https://dart-ci.firebaseapp.com/cl/139463/6

tests/ffi_2/* tests are the legacy tests, the tests/ffi/* tests are the tests which are migrated to NNBD.

Does that mean the CFE FFI tests are set up wrongly?

**Comment by stefantsov** [comment]
Yep, that's an issue with correctly opting in and out the tests.  We're currently working on solving it.  The affected tests and the CLs that surfaced the issue are listed here: https://github.com/dart-lang/sdk/issues/41053.
