### ISSUE TITLE
Support beta channel on chocolatey

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#40995]

**Comment by timsneath** [comment]
Consider addressing #41138 at the same time?

**Comment by athomas** [comment]
> Consider addressing #41138 at the same time?

I did a minimal fix replacing it with the non-deprecated alias. Hopefully, that will make the warning go away.

**Comment by athomas** [comment]
Implemented in:
https://dart-review.googlesource.com/c/recipes/+/143741
https://dart-review.googlesource.com/c/recipes/+/143921

I didn't create a true beta channel on chocolatey. Instead, the beta versions are uploaded as additional versions. To install a beta version with choco, you'll need to do this:
```
choco install dart-sdk --pre --version 2.8.0.20-c-011-beta
```

The pre-release version scheme for Dart's chocolatey package has also changed. This is how Dart Semver 2 versions are translated to chocolatey 4 component versions:
```
[x].[y].[z]-[m].[n].[dev|beta] -> [x].[y].[z]-c-[m].[n: padded with zeros to 3 chars].[dev|beta]
Example: 2.9.0-1.4.dev -> 2.9.0.1-c-004-dev
```
