### ISSUE TITLE
Consider adding an "exceptions" panel to migration tool

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41002]
We do currently recover from and save exceptions/stack traces in the tool.

Its currently very feasible to get exceptions from users who run the tool by asking them to run "--debug" (thanks @jcollins-g !), but the rerun step does not report over dartfix (see #41001).

It might be a good idea to have a panel that appears when exceptions occurred during migration. This will serve a few purposes: letting people know the output may be bad, letting us know when our tool is broken as we develop on it, and letting people file bug reports with stack traces.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
