### ISSUE TITLE
Tech debt: dartfix uses a switch on an integer to identify task phases

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41003]
Currently, the dartfix task design is something like

```dart
class MyTask implements Task {
  @override
  int get phases => 2;

  @override
  run(ResolveResult unit, int phase) {
    switch(phase) {
      case 0:
        doFirstThing(unit);
        break;
      case 1:
        doSecondThing(unit);
        break;
    }
  }
}
```

A better design would be:

```dart
class MyTask extends MultiplePhaseTask {
  List<Function(ResolveResult)> get tasks => [doFirstThing, doSecondThing];
}
```

**Comment by srawlins** [comment]
Note that @stereotype441 recently refactored the phases code.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
