### ISSUE TITLE
dart2js should throw TypeErrorImplementation for both Cast and Type errors

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41007]
Per https://github.com/dart-lang/sdk/issues/40763, I landed the change to make the dart2js implementation classes TypeErrorImplementation and CastErrorImplementation both implement TypeError and CastError [here](https://dart-review.googlesource.com/c/sdk/+/138670/).  

CastError will be deprecated in a follow up CL.  The web compilers should be changed to throw instances of a single implementation class (TypeErrorImplementation) for all implicit and explicit casts.  This change should be non-breaking given the changes in my CL.

cc @sigmundch @rakudrama @fishythefish @nshahan

**Comment by rakudrama** [comment]
`js_runtime` now has a single `_TypeError` class that implements both `TypeError` and `CastError` interfaces.

`js_dev_runtime` has two 'Impl' classes, both implementing `TypeError` and `CastError`.
@nshahan perhaps these could be merged.

**Comment by nshahan** [comment]
All uses of `CastErrorImpl` were already migrated to `TypeErrorImpl` in https://dart-review.googlesource.com/c/sdk/+/139490. I'm sending out a change to finally delete `CastErrorImpl` and close this issue.
