### ISSUE TITLE
FileLock.shared lock mode doesn't allow to write to a file

### ISSUE THREAD

**Issue by alexgoussev** [dart-lang/sdk#41009]
**1** 
Open a file with [openSync](https://api.dart.dev/stable/dart-io/File/openSync.html) method in any of three modes: FileMode.write, FileMode.writeOnly or FileMode.writeOnlyAppend. Then lock it with [lockSync](https://api.dart.dev/stable/dart-io/RandomAccessFile/lockSync.html) using FileLock.shared mode and try to write something to it.
You will get unhandled exception: "FileSystemException: writeFrom failed, path = '...' (OS Error: The process cannot access the file because another process has locked a portion of the file., errno = 33)"

To reproduce the problem please try the code below.

It stops on the line 2 if you comment out nothing.
It stops on the line 4 if you:
comment out line 1 or 2;
comment out lines 2 and 3;

The code completes successfully only if you comment out lines 1 and 3.
```
import 'dart:io';
void main(List<String> arguments) {
  String fpath = 'testfile.txt';

  File file1 = File(fpath);
  file1.createSync();

  RandomAccessFile raf1 = file1.openSync(mode: FileMode.write);
  raf1.lockSync(FileLock.shared); // line 1
  raf1.writeFromSync([1, 2, 3]); // line 2
  raf1.flushSync();
  raf1.setPositionSync(0);
  print(raf1.readSync(3));

  File file2 = File(fpath);
  RandomAccessFile raf2 = file2.openSync(mode: FileMode.write);
  raf2.lockSync(FileLock.shared); // line 3
  raf2.writeFromSync([3, 4, 5]); // line 4
  raf2.flushSync();
  raf2.setPositionSync(0);
  print(raf2.readSync(3));

  raf1.closeSync();
  raf2.closeSync();
} 
```

**2**
Open a file with [openSync](https://api.dart.dev/stable/dart-io/File/openSync.html) method in FileMode.read mode. Then lock it with [lockSync](https://api.dart.dev/stable/dart-io/RandomAccessFile/lockSync.html) using FileLock.shared mode. Then open it again in any of three modes: FileMode.write, FileMode.writeOnly or FileMode.writeOnlyAppend and try to write something to it.
You will get unhandled exception: "FileSystemException: writeFrom failed, path = '...' (OS Error: The process cannot access the file because another process has locked a portion of the file., errno = 33)"

To reproduce the problem please try the code below.

It stops on the line 3 if you:
comment out nothing;
comment out line 1 or 2.

The code completes successfully only if you comment out lines 1 and 2.
```
import 'dart:io';
void main(List<String> arguments) {
  String fpath = 'testfile.txt';

  File file1 = File(fpath);
  file1.createSync();

  RandomAccessFile raf1 = file1.openSync(mode: FileMode.read);
  raf1.lockSync(FileLock.shared); // line 1

  File file2 = File(fpath);
  RandomAccessFile raf2 = file2.openSync(mode: FileMode.write);
  raf2.lockSync(FileLock.shared); // line 2
  raf2.writeFromSync([3, 4, 5]); // line 3
  raf2.flushSync();
  raf2.setPositionSync(0);
  print(raf2.readSync(3));

  raf1.closeSync();
  raf2.closeSync();
}
```

So if you need to write to a file you have only two choices at present: do an exclusive lock or don't lock it at all.

_Windows 7 x64, Dart SDK 2.8.0-dev.13.0_

**Comment by ZichangG** [comment]
This is designed behavior on Windows. According to [LockFileEx](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-lockfileex)

> Locking a portion of a file for shared access denies all processes write access to the specified region of the file, including the process that first locks the region. All processes can read the locked region.
