### ISSUE TITLE
Canonicalize phi(x, redefinition(x)) to x when x and redefintion(x) have the same effects

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#41004]
With the NNBD unfork, code like ListIterator.current can wind up with floating pieces of flow graph that refine a type, and then discard the refinement.

```
B1:
  ...
  x := ... (type = E?)
  StrictCompare(x, null, B2, B3)
B2[target]:
  y := Redefinition(x) (type = E ^ *)
  goto B3
B3[join]: B1, B2
  z := phi(x, y) (type = E?)
```

Here we can replace use of z with uses of x, because B2 and the strict compare have no effects.

Currently the phi and the branch stick around, reducing performance in benchmarks like MegaNeverOverridden and ForInLoop.

**Comment by alexmarkov** [comment]
This pattern is probably a result of 65254a45188a7813e8884573ca6974110abb80bf. We can revert that change after fixing https://github.com/dart-lang/sdk/issues/40892.
