### ISSUE TITLE
Migration preview: "Apply migration" / "Add hint" do not work well with dartfix API

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41001]
Currently, "dart migrate" ignores the edits it gets back unless run with "--apply-changes" (in which case it also does not show the preview server).

This is a fortunate design that enables us to get away with a hacky design elsewhere: When you apply a migration, the fact that you have applied it is not sent over the dartfix/analysis server API.

We will have a similar problem shortly with the "add hint" workflow, where the migration edits will change after rerun, but no message will be sent over the API with the new changes.

Likely, we want to make this model explicit and codify it so that when a preview server is requested, the dartfix API does not return any edits/explanations.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
