### ISSUE TITLE
Ensure "rerun migration" can pick up on added/removed files, etc

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41017]
Currently "rerun migration" is expected only to be called when users add a hint. This means we _can_ skip a lot of the steps that DartFix runs, like finding packages and files in those packages etc.

However, if we add some kind of "rerun migration from disk" button to the UI, users may conceivably perform larger refactors etc.

We should confirm this works with my initial rerun implementation. I'm pretty sure it currently won't.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
