### ISSUE TITLE
Unexpected inference for map index operator followed by `!` in nnbd

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41019]
Repro program (note you must disable implicit casts to see the error):

```
void main() {
  var x = <String, String>{'a': 'b'};
  // The following gives: A value of type 'dynamic' can't be assigned to a variable of type 'String'.
  String y = x['a']!;
}
```

Assigning `x['a']` to a local variable first solves the problem, or wrapping it in parens but that is ugly (`(x['a'])!`).

Feel free to close if this is WAI but it seems unexpected.

cc @scheglov

**Comment by scheglov** [comment]
It is a bug in analyzer.
https://dart-review.googlesource.com/c/sdk/+/139821
