### ISSUE TITLE
Tech debt: Improve the way that `dart migrate` runs the preview server for NNBD

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41018]
Currently, the dartfix engine works like this:

- the nnbd task starts up a preview server as part of normal operations
- the dartfix engine attempts to find the NNBD task, and if it exists, uses it to get the port to return in a response.

With apply hints, this is getting worse. The NNBD engine needs to also set the "rerun function" on the preview site, which is considered part of the NNBD task (which is a singleton despite potentially rerunning).

A better design is to do something like:

```dart
abstract class FixCodeTask {
  HttpPreviewServer/*?*/ beginPreview(void Fuction() rerunFunction) => null;
}
```

```dart
class NNBDTask {
  ...
  HttpPreviewServer beginPreview(void Function() rerunFunction) => HttpServer(PreviewSite(state, rerunFunction));
  ...
}
```

```
class EditDartFix {
  ...
    runAllTasks();
    ports = tasks.map((task) => task.beginPreview(runAllTasks).port);
    return DartFixResult(
      ...
      ports: ports
      ...
   });
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
