### ISSUE TITLE
FileStat.mode always gets the same file permissions bits regardless of real ones

### ISSUE THREAD

**Issue by alexgoussev** [dart-lang/sdk#41012]
Create file 'testfile.txt' in test project folder and try to set several different file permissions and run the code below. You'll see that FileStat.mode property is the same and equals 666 in oct. 
```
import 'dart:io';
void main() {
  FileStat fileinfo = File('testfile.txt').statSync();
  print((fileinfo.mode & 0x1FF).toRadixString(8));
}
```

_Windows 7 x64, Dart SDK 2.8.0-dev.13.0_

**Comment by ZichangG** [comment]
I played a bit with my windows machine. I think this is something wrong with [_wstat64](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=vs-2019). `statSync` will call `_wstat64` and return `st_mode`.
We probably can't do much about that.
My Windows 10 version is 10.0.18362.

**Comment by sortie** [comment]
Zichang, can you clarify that this is a bug in Windows and maybe link to some advisory about it?

**Comment by ZichangG** [comment]
I think it is a bug.  But I didn't find any detailed information on file permissions. These observation came from my experiments.

From `_wstat64`
> Bit mask for file-mode information. The _S_IFDIR bit is set if path specifies a directory; the _S_IFREG bit is set if path specifies an ordinary file or a device. User read/write bits are set according to the file's permission mode; user execute bits are set according to the filename extension.

"execute bits" purely depends on file extension. Regarding `read` and `write`, it will always return 666 if file permissions are readable.
