### ISSUE TITLE
Provide a wrap-in-text fix

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#41014]
Given an invocation of a method that requires a `Widget` where the argument has the type `String`,
provide a fix to wrap the string in a constructor invocation for `Text`.

**Comment by bwilkerson** [comment]
@devoncarew Are there likely to be situations in which the `Widget` parameter won't be a named parameter?

**Comment by devoncarew** [comment]
Not that I have run into.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/139480
