### ISSUE TITLE
First time deploys flutter android studio in ubuntu

### ISSUE THREAD

**Issue by ariezhujan** [dart-lang/sdk#41026]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Linux(amd64) v5.3.0-40-generic, screens 1366x768`

**Comment by keertip** [comment]
Closing this as there are no details to figure out what might be the problem. Please reopen with more details.
