### ISSUE TITLE
Is it impossible to export a class using package:js and dart2js?

### ISSUE THREAD

**Issue by MagicPoulp** [dart-lang/sdk#41028]
* dart2js

https://github.com/sass/dart-sass.git
shows a good example of how to make a dart function callable from javascript
See node.dart

But how can I export a dart class? Is it impossible?
the code below compiled with dart2js returns a generated code that does not contain the content of the class.

```
import 'dart:async';
import 'dart:convert';
import 'dart:js_util';
import 'dart:typed_data';

import 'package:js/js.dart';

class ImageGalleryBloc {
  void showImagesList() {
    print("HERE");
  }
}

@JS()
class Exports {
  external set ImageGalleryBloc(Type imageGalleryBloc);
}

@JS()
external Exports get exports;

void main() {
  exports.ImageGalleryBloc = allowInterop(ImageGalleryBloc);
}


```

**Comment by fishythefish** [comment]
It depends on what you mean by "export a dart class". Some Dart classes are compiled to JS classes, but general JS code doesn't interoperate with Dart classes and instances out of the box. JS code expects JS objects, and you **can** use a Dart class to create JS object literals: [example](https://pub.dev/packages/js#passing-object-literals-to-javascript).

**Comment by MagicPoulp** [comment]
This is too old. I close. Reopen if the issue persists.
