### ISSUE TITLE
add a quick fix for the error `const_with_non_const`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#41034]
We should add a quick fix for the error `const_with_non_const`:

```
error: The constructor being called isn't a const constructor. (const_with_non_const at [devtools_app] lib/src/flutter/scaffold.dart:296)
```

<img width="306" alt="Screen Shot 2020-03-13 at 8 26 41 AM" src="https://user-images.githubusercontent.com/1269969/76635323-87bff400-6504-11ea-951c-fe2e0fe7d8cb.png">

cc @pq, @bwilkerson

**Comment by bwilkerson** [comment]
Is the fix you're proposing to make the constructor a const constructor?

**Comment by devoncarew** [comment]
Ah, I should have specified - I was expecting to see a quick fix that offered to remove the `const` keyword.

**Comment by devoncarew** [comment]
I ran into the above error after doing refactoring of the `StatusLine` class - it could no longer have a const constructor.

**Comment by bwilkerson** [comment]
That would certainly be an easier fix to implement, and would always apply.

**Comment by pq** [comment]
Good catch.  Taking a look now. 👍

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/139487

**Comment by pq** [comment]
Fixed w/ https://dart-review.googlesource.com/c/sdk/+/139487.
