### ISSUE TITLE
Migrator adds `!` inside `null.hashCode`.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41037]
For instance it will convert [this line](https://github.com/dart-lang/collection/blob/bfe17fe4779b27a59e651c93a31185d6f1c17186/lib/src/equality.dart#L134):

```
    if (elements == null) return null.hashCode;
``` 

To

```
    if (elements == null) return null!.hashCode;
```

But `null` actually does have a `hashCode`, and the null check will now fail.

**Comment by srawlins** [comment]
Possibly solved during https://github.com/dart-lang/sdk/issues/42263.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
