### ISSUE TITLE
Code completion bug - dynamic and void not provided as return types of methods

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#41039]
`dynamic` and `void` aren't provided as return types for method declarations and function declarations if there is a comment or annotation on the declaration.

**Comment by jwren** [comment]
Just FYI for history and reference going forward.  @bwilkerson @pq 

The source of this bug is in the expectation from the `visitClassDeclaration(ClassDeclaration)` in `lib/src/services/completion/dart/keyword_contributor.dart`.  The `ClassDeclaration` visits call `_addClassBodyKeywords();` which accurately adds all first tokens that class members can have (including `dynamic` and `void`), when the cursor is determine to be at the beginning of such a member:

```
| method_name() {}
```

**does** have the correct completion values (from `_addClassBodyKeywords()`).  The bug is that:

```
@override
| method_name() {}
```

**does not** have the correct set of completions, here the completion location, `|`, is in a `MethodDeclaration`, `visitClassDeclaration(ClassDeclaration)` is never called.

After this bug is fixed, it would be an improvement on code completion to remove the call from `visitClassDeclaration(ClassDeclaration)`, and implement a more specific version of `_addClassBodyKeywords()` for each kind of class member.

**Comment by jwren** [comment]
https://dart-review.googlesource.com/c/sdk/+/140360 -- fixes the `MethodDeclaration` case, additional cases to follow.

**Comment by bwilkerson** [comment]
We are now suggesting both `void` and `dynamic`.
