### ISSUE TITLE
`dart help <verb>` is very lacking (compare to e.g. dart <verb> help)

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#41041]
`dart help <verb>` is very lacking (compare to e.g. `dart <verb> help`)

**Comment by jwren** [comment]
@mit-mit @devoncarew 

I opened this after https://github.com/dart-lang/sdk/issues/41040 (case for `pub`) was opened.

Some of the commands (`migrate`, `analyze`, `help`) do not have thee `help` verb on them (i.e. `dart analyze help`, `dart migrate help`, ...), but they do have the flag `-h` and `--help`.

Does it seem reasonable to change this assertion of `dart help <verb> == dart <verb> help` should be changed to `dart help <verb> == dart <verb> [--help | -h]`?

**Comment by devoncarew** [comment]
I don't believe that subcommands generally support `help`. Composite commands (like `dartdev`), I believe to support help.

Having the sub-commands just support `-h` and `--help` seems fine.

**Comment by jwren** [comment]
https://dart-review.googlesource.com/c/sdk/+/140144 -- test to verify this for all commands, except `test`.

**Comment by jwren** [comment]
https://dart-review.googlesource.com/c/sdk/+/141220 - fix for `test`
