### ISSUE TITLE
Where is the Dart .gclient file?

### ISSUE THREAD

**Issue by liudonghua123** [dart-lang/sdk#41055]
I want to build an android dart sdk, I read the https://github.com/dart-lang/sdk/wiki/Building-Dart-SDK-for-Android.

> Download and install the Dart source tree using the standard instructions for building Dart.
> 
> Use a text editor to add the following line to the very bottom of your Dart .gclient file (which is located in the directory that contains the main 'dart' directory):
> 
> target_os = ['android']

But I can't find and edit this file, so what's the location of this file?

**Comment by rmacnak-google** [comment]
It will be in the parent directory of the SDK repository.

```
$ mkdir workspace
$ cd workspace
workspace$ fetch dart
workspace$ cat .gclient
solutions = [
  {
    "url": "https://dart.googlesource.com/sdk.git",
    "managed": False,
    "name": "sdk",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
```
