### ISSUE TITLE
`dart no-such-file.dart` complains that it doesn’t understand that command

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#41058]
In the Dart VM logic for running some action:

`dart no-such-file.dart`

yields and error message that the VM doesn’t understand that [`no-such-file.dart`] command.

Instead if a command ends with `.dart`, a message that the file doesn't exist should be printed out.

**Comment by whesse** [comment]
This bug is not completely fixed.  If options are passed to dart, and the dart file is not found, we get:
````
>dart --enable-experiment=non-nullable --null-safety foo.dart
Warning: The following flags were passed as VM options and are being ignored: --enable-experiment=non-nullable, --null-safety
These flags should be passed after the dart command (e.g., 'dart run --enable-asserts foo.dart' instead of 'dart --enable-asserts run foo.dart').
Error when reading 'foo.dart': No such file or directory.
````
If there are no command-line options, the correct error, "Error when reading 'foo.dart': No such file or directory" is returned.

Using "dart run" instead of "dart" eliminates the problem.

**Comment by mit-mit** [comment]
@bkonyi can you take another look?

**Comment by bkonyi** [comment]
@mit-mit this should be resolved once I move dartdev in-process. Is this issue a blocker for the 2.9 release?

**Comment by bkonyi** [comment]
Also, this issue will be fixed as a side effect of [this CL](https://dart-review.googlesource.com/c/sdk/+/152588) which will remove the need to spawn a separate process from DartDev.

**Comment by mit-mit** [comment]
I'm OK with a slight regression in experience here for 2.9 if this is expected to be fixed shortly after.

**Comment by bkonyi** [comment]
Should be resolved by https://github.com/dart-lang/sdk/commit/157ebfe50f399c59a20d603acdf5143ceaa4cccf
