### ISSUE TITLE
Backporting .fromEnvironment updates: Get default values from element model, support `hasEnvironment`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41050]
Cf. breaking change #40678, https://dart-review.googlesource.com/c/sdk/+/139286 introduced `bool.hasEnvironment` into the sdk/sdk_nnbd.

The next step would be to make the analyzer obtain the default value for the named parameter `defaultValue` of the `bool`, `int`, `String` constructors named `fromEnvironment` from the element model, such that it would work with both the sdk and the sdk_nnbd defaults without special casing.

Next again, evaluation of constant expressions of the form `const bool.hasEnvironment(...)` should be implemented, and this would then make the tests `language{,_2}/bool/has_environment_{,not_new_}test.dart` succeed.

@stereotype441, can you help finding a way to fit this into the analyzer team work plan?

**Comment by stereotype441** [comment]
@scheglov can you give this a priority?  Thanks!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/139661
