### ISSUE TITLE
"Add explicit 'show' combinator" doesn't work for setters

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#41069]
Say I have these files:

`tmp2.dart`:
```
int get getter => 42;
void set setter(int value) {}
int field;
int method() {}
class Class {}
```

and `tmp.dart`:
```
import "tmp2.dart";

main() {
  print(getter);
  setter = 42;
  print(field);
  print(method());
  Class c;
}
```

then ask for available code actions in the import statement in `tmp.dart` and chose "Add explicit 'show' combinator".
The import statement becomes `import "tmp2.dart" show Class, field, getter, method;` and there's now an error (`Undefined name 'setter'.`).

**Comment by jensjoha** [comment]
I've tried fixing this myself in https://dart-review.googlesource.com/c/sdk/+/139802.

**Comment by kibugenzaKing** [comment]
i think if you add the show by quick fix, some code might not work. so to solve this issue follow these steps: 
ex: i added
 import 'package:get/get.dart' show Get, GetBuilder, Inst;

and after here Get.toNamed is not working (toNamed) has an error so left click on toNamed and import the addition package,

so the import will look like this after ::

import 'package:get/get.dart' show Get, GetBuilder, /* this one has been added -> */GetNavigation, Inst; more like that
