### ISSUE TITLE
SecureSocket connection to TLSv1.3 not working

### ISSUE THREAD

**Issue by alokraop** [dart-lang/sdk#41061]
Hi, i'm trying to write a secure dart client for a TCP server with a min version of TLSv1.3.

The connection errors out with:

```
HandshakeException: Handshake error in client (OS Error: 
        TLSV1_ALERT_PROTOCOL_VERSION(tls_record.cc:587))
      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:103:51)
      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:832:21)
      _RawSecureSocket._closeHandler (dart:io/secure_socket.dart:825:9)
      _RawSecureSocket._eventDispatcher (dart:io/secure_socket.dart:768:9)
      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
      _StreamController._add (dart:async/stream_controller.dart:649:7)
      _StreamController.add (dart:async/stream_controller.dart:595:5)
      new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1422:35)
      _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:912:18)
     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
I checked the documentation for `SecurityContext`, but doesn't look like i can explicitly ask it to use 1.3. Even if i don't, TCP negotiations will default to the highest supported version right? Does this mean that Dart does not support anything above `TLSV1`? 

```
dart --version
Dart VM version: 2.8.0-dev.8.0.flutter-514a8d4c84 (Fri Feb 7 13:36:03 2020 +0000) on "windows_x64"
```

I have tested both on an android device with flutter, an on a Windows and Mac system. The error persists.

TLSv1 contains multiple known vulnerabilities and has been deprecated in most places for a over a year now, so i would really prefer not to downgrade.

**Edit**: I just downgraded the server to accept TLSv1.2, and the client seems to be working. The error message had me thinking that the client could only handle TLSv1, but looks like the error only prints the major version?

**Comment by kw2019ltd** [comment]
Non-fatal Exception: java.lang.Exception: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))

**Comment by zichangg** [comment]
I think this is relative. https://github.com/dart-lang/sdk/issues/37173

**Comment by nicoroy2561** [comment]
I would be interested in 1.3 support as well. When I open a websocket connection with a server that accepts only 1.3 it says that it failed the negotiation (as the dart side doesn't support it, apparently)

**Comment by mraleph** [comment]
I did a quick look at the sources. The version of boringssl we are using is not enabling TLS1.3 by default (though it is supported and thus can be enabled by calling `SSL_CTX_set_max_proto_version` with `TLS1_3_VERSION`). BoringSSL at master seems to enable the support by default. 

@aam could you attempt to roll boringssl forward? We have not rolled it since Sep 2019.  

/cc @a-siva

**Comment by aam** [comment]
@rmacnak-google started boringssl roll couple weeks ago https://dart-review.googlesource.com/c/boringssl_gen/+/182980.

**Comment by rmacnak-google** [comment]
Rolling boringssl creates new test failures that start at the commit that enables TLS 1.3; https://dart-review.googlesource.com/c/sdk/+/182961. I don't understand TLS well enough to say if dart:io is doing something wrong and failing notice a handshake failure somewhere, or if TLS 1.3 exchanges fewer messages in the handshake such that the client is expected to speculate the handshake worked until a later read error.

**Comment by aam** [comment]
I think it's benign and as expected https://stackoverflow.com/questions/62459802/tls-1-3-client-does-not-report-failed-handshake-when-client-certificate-verifica.

When server needs clients certificate, but client doesn't provide any, client used to(before TLS 1.3) fail immediately, but with TLS 1.3 client reports successful connection, yet it gets disconnected right away since server dropped the connection on its side.

**Comment by mraleph** [comment]
@aam and @rmacnak-google have rolled boringssl which made things work. 

Verified using the following test to connect to TLS 1.3 only server:

```dart
import 'dart:convert';
import 'dart:io';

void main() async {
  final client = HttpClient();
  try {
    final req = await client.getUrl(Uri.parse('https://tls13.1d.pw/'));
    final res = await req.close();
    print(res.statusCode);
    print(await res.transform(utf8.decoder).join(''));
  } finally {
    client.close();
  }
}
```

before

```console
$ dart /tmp/tls13-test.dart
Unhandled exception:
HandshakeException: Handshake error in client (OS Error: 
        TLSV1_ALERT_PROTOCOL_VERSION(tls_record.cc:587))
```

Now 

```console
$ dart /tmp/tls13-test.dart
200
<!DOCTYPE html><html><head><link rel="stylesheet" href="/assets/styles.css" /><title>TLS 1.3 connection test server at tls13.1d.pw</title></head><body>
...
```

**Comment by gustav3d** [comment]
You're awesome !
Thanks
