### ISSUE TITLE
NNBD. An error for missed required parameter in DDC

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41067]
The code below produces the following error in DDC

```
named != null
"A null value was passed into a non-nullable parameter named"
```

```dart
opted_in.dart
library opted_in_lib;
class A {
  static void bar({required String named}) {}
}

opted_out.dart
// @dart=2.6
import "opted_in.dart";

main() {
  A.bar();
}
```
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#legacy-libraries)

> All required named parameters are treated as optional named parameters.

**Comment by sgrekhov** [comment]
See also #40978

**Comment by sigmundch** [comment]
@Markzipan could you take a look?

**Comment by Markzipan** [comment]
On it. This issue seems to have been introduced when we added null assertions to everything.

**Comment by Markzipan** [comment]
From what I understand, we're disabling mixed-mode execution like this.
