### ISSUE TITLE
Failures on [cfe] Remove flag --force-nnbd-checks...Add a fix for the prefer_interpolation_to_compose_strings lint

### ISSUE THREAD

**Issue by ZichangG** [dart-lang/sdk#41063]
There are new test failures on [[cfe] Remove flag --force-nnbd-checks...Add a fix for the prefer_interpolation_to_compose_strings lint](https://github.com/dart-lang/sdk/compare/8929bbfbe1fd5cd09b52b808b196e671e1e8e0d4~...928f9fc9325e2cf31cba89904b39aaee5d4efa74).

The tests
```
ffi/structs_test CompileTimeError (expected Pass)
standalone/io/http_server_early_client_close_test/0 CompileTimeError (expected Pass)
```
are failing on configurations
```
dartkp-strong-linux-release-x64
```

Logs: https://dart-ci.appspot.com/log/vm-kernel-precomp-nnbd-linux-release-x64/dartkp-strong-linux-release-x64/217/ffi/structs_test

https://dart-ci.appspot.com/log/vm-kernel-precomp-nnbd-linux-release-x64/dartkp-strong-linux-release-x64/217/standalone/io/http_server_early_client_close_test/0

**Comment by ZichangG** [comment]
@stefantsov

**Comment by stefantsov** [comment]
Thanks for filing the issue!  It seems that the errors on the bot are the same as those I pre-approved on the trybots.  So, I approved the new failures on the bot.

The overall issue with the failures is handled here: https://github.com/dart-lang/sdk/issues/41053.
