### ISSUE TITLE
VM + NNBD: Generic type cannot be converted to its nullable equivalent

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41060]
repro program:

```dart
main() {
  List<int?> l = foo<int>();
  print(l.runtimeType); // prints `List<int>` (expected `List<int?>`)
  l.add(null); // throws (expected it to be ok)
}

List<T?> foo<T>() => <T?>[];
```

This appears to be vm-specific as it has the expected behavior in ddc.

**Comment by alexmarkov** [comment]
Looks like the case which was fixed in cfc006a8f4ac804ca1e3b7c0b42a5ab9d4052f57.
@crelier could you please take a look?

**Comment by jakemac53** [comment]
Oh - I haven't rebuilt my sdk today so I can rebuild it and check as well

**Comment by crelier** [comment]
I just verified that it prints List<int?> as expected.

**Comment by jakemac53** [comment]
awesome thanks 👍
