### ISSUE TITLE
Migration tool: Apply hint links should be buttons

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41078]

**Comment by stereotype441** [comment]
Also consider changing the text to be clearer.  Maybe something like "Add /*?*/ hint" etc.

Also: we should only display buttons that will have an effect

**Comment by stereotype441** [comment]
Note: after working further with the tool, I no longer think we should only display buttons that will have an effect.  Being able to add a "/*?*/" comment to confirm that the tool has correctly inferred something to be nullable is sometimes really nice.

**Comment by stereotype441** [comment]
Fixed in 5d9eb40f20c1c27cc0df200c179433669e0214a8
