### ISSUE TITLE
Integrate hint actions into the stacktrace view

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41077]

**Comment by stereotype441** [comment]
This came up twice yesterday in my attempt to use the migration tool on package:csslib.  It was confusing that when I navigated through the trace I would get somewhere else, then decide to add a hint at the spot I had navigated to, but the "Add /*!*/" and "Add /*?*/" buttons didn't apply to the trace step I was looking at; they applied to the point I started at.
