### ISSUE TITLE
Failures on [cfe] Handle bool.hasEnvironment constructor in constant evaluation

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#41075]
There are new test failures on [[cfe] Handle bool.hasEnvironment constructor in constant evaluation](https://github.com/dart-lang/sdk/commit/4aba58122c3070d5effef416d52cb4f74b7bd253).

The tests
```
lib_2/isolate/string_from_environment_default_value_test/0 RuntimeError (expected Pass)
lib_2/isolate/string_from_environment_default_value_test/1 RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-weak-asserts-linux-release-x64
```

**Comment by eernstg** [comment]
Cf. https://dart-review.googlesource.com/139811.

**Comment by eernstg** [comment]
Done in https://dart-review.googlesource.com/c/sdk/+/139811.
