### ISSUE TITLE
StreamBuilder's stream property is not currently marked @required in Flutter 1.15.23-pre.6

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#41088]
I can't think of an instance when this widget is useful without having a Stream provided.     

> Flutter 1.15.23-pre.6 • channel master • https://github.com/flutter/flutter.git
> Framework • revision 028b7dced1 (29 hours ago) • 2020-03-16 11:33:00 -0700
> Engine • revision a9d49a0f6e
> Tools • Dart 2.8.0 (build 2.8.0-dev.14.0 d2950737b8)

**Comment by mit-mit** [comment]
Is this for https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html ?

If so, please file a bug in the flutter issue tracker, as that would be a Flutter framework issue.

**Comment by ThinkDigitalSoftware** [comment]
Oops, will do.

On Mar 18, 2020 5:57 AM, Michael Thomsen <notifications@github.com> wrote:

Is this for https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html ?

If so, please file a bug in the flutter issue tracker, as that would be a Flutter framework issue.
