### ISSUE TITLE
dart2native fails Unexpected object (Class with illegal cid, full-aot)

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#41082]
I'm trying to compile a dart script under windows:

dart2native -v log.dart
Generating AOT kernel dill.
Generating AOT snapshot.

Unexpected object (Class with illegal cid, full-aot): 0x1f79ed954b1 Library:'dart:collection' Class: _CompactLinkedHashSet@3220832

Failed to generate native files:
Generating AOT snapshot failed!

The following script is sufficient to generate the error:

Create the script:

`log.dart`

```

import 'package:logger/logger.dart';

void main() {
 Log.e();
}

class Log extends Logger {
  Log();

  factory Log.e() {
    var self = Log();
    self.e('a');
    return self;
  }
}

```

Then run:
```
dart2native log.dart
```

OS                       : windows
OS Version               : "Windows 10 Enterprise Evaluation" 10.0 (Build 18363)
Path separator           : \

dart version             : 2.7.1

dart exe path            : c:\program files\dart\dart-sdk\bin\dart.exe
dart path                : c:\program files\dart\dart-sdk\bin\dart.exe 
dart2Native path         : c:\program files\dart\dart-sdk\bin\dart2native.bat : 

pub get path             : c:\program files\dart\dart-sdk\bin\pub.bat : c:\program files\dart\dart-sdk\bin\pub.bat
Pub cache                : c:\users\user\appdata\roaming\pub\cache
Package Config           : c:\users\user\file:\c:\users\user\dshell\.packages

**Comment by bsutton** [comment]
I just tried another google seach and it looks like this is a duplicate of:
#40083

**Comment by mkustermann** [comment]
@bsutton Thank you for the report.

It seems like it's the same issue. Closing in favor of  #40083 .
