### ISSUE TITLE
co19 tests should be backported to expect TypeErrors instead of AssertionErrors at boolean conversion boundaries.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#41086]
See the following issues:
* https://github.com/dart-lang/sdk/issues/40317
* https://github.com/dart-lang/sdk/issues/40763

Tests that should be fixed:
```
co19_2/Language/Expressions/Unary_Expressions/variable_negative_t03
co19_2/Language/Statements/Assert/execution_t03
co19_2/Language/Statements/Assert/execution_t11
co19_2/Language/Statements/If/condition_evaluation_t02
```

**Comment by mit-mit** [comment]
cc @eernstg

**Comment by eernstg** [comment]
The required updates occurred in https://github.com/dart-lang/co19/commit/88acb3b8285561916403446a2f4ffbed88fdf42f and https://github.com/dart-lang/co19/commit/1d5f31be0d5a8a3635fc5047e3399700361a0bac, resolving https://github.com/dart-lang/co19/issues/583.

So I believe this should be closed as a duplicate.

@Markzipan, did you have any further actions in mind for this issue? In that case please re-open, and indicate what you had in mind.
