### ISSUE TITLE
Improve error message when ui-as-code features are used with incorrect SDK version constraints

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#41096]
We should show a meaningful error message if ui-as-code features are used with SDK version `>=2.1.0 <3.0.0` (the constraint generated by `flutter create` )

## Steps to reproduce
1. Create a new Flutter project
2. Observe that pubspec.yaml specifies SDK version `>=2.1.0 <3.0.0`
3. Use update `main.dart` to use ui-as-code features:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var otherWidgets = <Widget>[];
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            ...otherWidgets
          ],
        ),
      ),
    );
  }
}

```
4. Observe analyzer errors: `error • This requires the 'spread-collections' experiment to be enabled • lib/main.dart:15:13 • experiment_not_enabled`

## Proposal

Instead of this type of error, we should let users know that they need to update their SDK version constraint to `>=2.3.0 <3.0.0` in `pubspec.yaml`

**Comment by mit-mit** [comment]
Oddly, the output for Dart and Flutter seems to differ.

I created this main.dart inside both a small Dart app and Flutter app:
```dart
main() {
  var l = [...[1,2,3], 4];
  print(l);
}
```

The output is different:

```console
$ dartanalyzer bin/main.dart
Analyzing bin/main.dart...
  hint • The for, if, and spread elements weren't supported until version 2.3.0, but this code is required to be able to run on earlier versions. • bin/main.dart:2:12 • sdk_version_ui_as_code

$ flutter analyze .
Analyzing testapp2...

  error • This requires the 'spread-collections' experiment to be enabled • lib/main.dart:2:12 • experiment_not_enabled
```

**Comment by mit-mit** [comment]
Adjusting the templates in https://github.com/flutter/flutter/pull/52879

**Comment by bwilkerson** [comment]
The hint is coming from analyzer (of course); the error is coming from the parser.

I'm not sure why there's a difference between `dartanalyzer` and `flutter analyze`, but a version skew might explain it.

**Comment by johnpryan** [comment]
This can be closed now, I just re-tested this on Flutter's master channel

1. The template uses the correct sdk versions (`>=2.7.0 <3.0.0`)
2. when it's changed to `>=2.1.0 <3.0.0` I'm correctly seeing the `sdk_version_ui_as_code` hint.

**Comment by mit-mit** [comment]
Given this works in the Dart SDK, but fails (to give the expected message) in the Flutter SDK, I'm going to move this over to Flutter

**Comment by mit-mit** [comment]
Flutter bug is https://github.com/flutter/flutter/issues/52826
