### ISSUE TITLE
add a quick fix for `prefer_const_constructors_in_immutables`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#41097]
When refactoring some code, I added a constructor to a class that previously only had an implicit constructor. It was a relatively simple class (a stateless widget). After adding a ctos with a named param, I saw the `prefer_const_constructors_in_immutables` warning. When I selected the quick fix options in IntelliJ, I only saw the 'ignore this warning' fix.

```
info: Prefer declaring const constructors on `@immutable` classes. (prefer_const_constructors_in_immutables at [devtools_app] lib/src/flutter/common_widgets.dart:289)
```

It would be nice to have a quick fix here (to I assume add a `const` to the ctor).

<img width="649" alt="Screen Shot 2020-03-18 at 10 05 32 AM" src="https://user-images.githubusercontent.com/1269969/76987419-5e3a0a80-6900-11ea-8ebc-3f0b390e6078.png">

cc @pq @bwilkerson

**Comment by pq** [comment]
For unrelated reasons I was poking around in this vicinity.

I'll take a look.

Thanks for the report!

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/140163
