### ISSUE TITLE
NoSuchMethodError when calling extension method against a dynamic

### ISSUE THREAD

**Issue by awhitford** [dart-lang/sdk#41094]
Consider the following code that extends `GeoPoint` to add a translation method `toGeoFirePoint`:
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geoflutterfire/geoflutterfire.dart';

extension GeoPoints on GeoPoint {
  /// Translate a [GeoPoint] into a [GeoFirePoint]
  GeoFirePoint toGeoFirePoint() => GeoFirePoint(latitude, longitude);
}
```

This extension does not seem to be recognized when the value is dynamic (even though it matches the correct type at runtime).  I am receiving a `NoSuchMethodError`:
```
flutter: NoSuchMethodError: Class 'GeoPoint' has no instance method 'toGeoFirePoint'.
Receiver: Instance of 'GeoPoint'
Tried calling: toGeoFirePoint()
```

Note that the code does successfully compile.  Besides the `NoSuchMethodError` runtime error, another symptom is that VS Code is not able to recognize the method either.

This code fails:
```dart
  factory MyObject.fromSnapshot(DocumentSnapshot snapshot) {
    return MyObject.fromMap({
      ...snapshot.data,
      'geoLocation': snapshot['geoLocation']['geopoint']?.toGeoFirePoint(),
    }, snapshot.reference);
  }
```

This code works:
```dart
  factory MyObject.fromSnapshot(DocumentSnapshot snapshot) {
    final GeoPoint gp = snapshot['geoLocation']['geopoint'];
    return MyObject.fromMap({
      ...snapshot.data,
      'geoLocation': gp?.toGeoFirePoint(),
    }, snapshot.reference);
  }
```

The difference between the two code snippets is that `snapshot['geoLocation']['geopoint']` has a `dynamic` type at compile time, so the first code snippet is trying to call `toGeoFirePoint()` on a dynamic and it isn't finding the extension method, while the second code snippet knows how to resolve the extension method.

I am using **Dart 2.7.0** on a MacOS 10.15.3.

**Comment by awhitford** [comment]
Note that adding a `cast` did not solve the issue either:
```
snapshot['geoLocation']['geopoint'].cast<GeoPoint>()?.toGeoFirePoint()
```

I would have thought that the _cast_ would constrain the type so that the compiler could successfully apply the extension method, but that did not help.

**Comment by mraleph** [comment]
Extension methods are based on the static type of the receiver - so this is working as intended. 

If you want to down cast an expression of super type to a subtype you should use `as` and not `cast`, e.g.

```dart
(snapshot['geoLocation']['geopoint'] as GeoPoint)?.toGeoFirePoint()
```

`cast<T>` is a method on `Iterable` which is essentially equivalent to `.map((e) => e as T)`.

**Comment by awhitford** [comment]
@mraleph Thank you for the quick clarification.  I see now that the documentation clearly states, "[You can’t invoke extension methods on variables of type dynamic.](https://dart.dev/guides/language/extension-methods#static-types-and-dynamic)"
