### ISSUE TITLE
Awaiting a `Future<T>?` infers `T` instead of `T?`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41095]
```dart
main() async {
  List y = await l(); // should be a List?
}

Future<List>? l() => null;
```

cc @scheglov

**Comment by natebosch** [comment]
This is also the behavior of the cfe.

**Comment by johnniwinther** [comment]
Created #41108 for CFE

**Comment by scheglov** [comment]
@leafpetersen @lrhn What is the expected semantics here? [The spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md) does not say about `await` changes.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/140220
