### ISSUE TITLE
Awaiting a `Future<T>?` infers `T` instead of `T?`

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#41108]
CFE issue for #41095 

```Dart
main() async {
  List y = await l(); // should be a List?
}

Future<List>? l() => null;
```

**Comment by johnniwinther** [comment]
Also see #41107

**Comment by natebosch** [comment]
Note that in some case this causes incorrect errors where there should be none instead of a missing error as in #41107

**Comment by jakemac53** [comment]
I noticed that with the latest SDK it appears this issue is now resolved, can this be closed? cc @johnniwinther

**Comment by jakemac53** [comment]
Nevermind I still see a warning from the CFE, just not analyzer
