### ISSUE TITLE
Update '--write-service-info=<filename>' to '--write-service-info=<file-uri>' to reduce ambiguity for Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#41109]
On Windows, using `--write-service-info` with a file path (which is what the info suggests it expects), it fails:

```
dart "--enable-vm-service=0" "--write-service-info=C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\dart-vm-service-37f0.json" "bin\\main.dart"

[stderr] vm-service: Error: Unhandled exception:
[stderr] Unsupported operation: Cannot extract a file path from a c URI
[stderr] [38;5;244m#0      _Uri.toFilePath  (dart:core/uri.dart:2727:7)[39;49m
[stderr] [38;5;244m#1      new File.fromUri  (dart:io/file.dart:267:49)[39;49m
[stderr] [38;5;244m#2      Server._dumpServiceInfoToFile  (dart:vmservice_io/vmservice_server.dart:388:23)[39;49m
[stderr] [38;5;244m#3      Server.startup  (dart:vmservice_io/vmservice_server.dart:454:13)[39;49m
[stderr] [38;5;244m<asynchronous suspension>[39;49m
[stderr] #4      main (dart:vmservice_io:262:12)
```

Seems to be calling `File.fromUri` which appears towork for Linux/Mac paths, but fail with Windows paths. I'm not sure whether the fix is to change the code, or just document that it expects a file URI rather than a file path (currently it says `<filename>`).

@bkonyi

**Comment by DanTup** [comment]
For now I'm going to assume we should pass file URIs here (since the code seems fairly explicit). If it's decided to change to a file path (and can't also support `file://` URIs), please let me know as I'll need to change things in VS Code.

**Comment by bkonyi** [comment]
Hey Danny, sorry for the delay. Using a `file://` URI is the safest and most consistent option for sure as you have to do some strange stuff with Windows paths to conform to the URI spec (did you try adding a leading `/`?). Take a look at the `toFilePath` documentation for more details on how Windows paths are handled: https://api.dart.dev/stable/2.7.2/dart-core/Uri/toFilePath.html.

**Comment by DanTup** [comment]
> Using a `file://` URI is the safest

Cool, I'll stick with that.

> did you try adding a leading `/`?

I didn't, though this issue was more a request to make it clearer what should be passed (the code calls `File.fromUri` suggesting a URI is expected, but the switch says `=<filename>` which suggests - at least to me - a standard/native file path would work). I think it would be better to tweak it to say `=<file-uri>` (or to remove `File.fromUri`and expect a path - though that would be breaking now).

**Comment by bkonyi** [comment]
> I didn't, though this issue was more a request to make it clearer what should be passed (the code calls File.fromUri suggesting a URI is expected, but the switch says =<filename> which suggests - at least to me - a standard/native file path would work). I think it would be better to tweak it to say =<file-uri> (or to remove File.fromUriand expect a path - though that would be breaking now).

Oh gotcha! Yes, that's a good suggestion. I'll go ahead and do that.
