### ISSUE TITLE
Do garbage `Dart_Handle`s invoke UB in the VM?

### ISSUE THREAD

**Issue by OptimisticPeach** [dart-lang/sdk#41101]
* Dart SDK Version `Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "windows_x64"`
* Windows primarily, but Mac and Linux too.

I'm writing an api for using the native-extensions api in Rust. Since I'm trying to be idiomatic, I would like to avoid declaring my api `unsafe`. But, if the user provides garbage pointers for `Dart_Handle`s, and a variety of other pointers, then does the VM validate them before dereferencing them/using them (And therefore causing UB)?

I can only declare the api safe if there's 0% chance that _any_ combination of parameters will cause UB, and creating garbage handles is safe in rust, so, is it safe to give those potentially garbage handles to the VM?

**Comment by rmacnak-google** [comment]
Yes, providing garbage handles to the VM invokes undefined behavior. There is some degree of checking around persistent handles in a debug build of the VM, but generally the VM trusts they are valid.

Beware exposing Dart_Handles or Dart_* functions upward in any API. The VM's embedding API is not versioned and changes without notice.

**Comment by OptimisticPeach** [comment]
Alright, thank you. I find that the api isn't stable and somewhat undocumented, and will try to monitor changes to the api and modify my api from time to time. 

I presume that the same applies to all pointers passed between extension code and the VM.

Please correct me if I'm wrong though, in that the VM will never return a garbage handle, and will only ever return an error handle (Which can be checked by `Dart_IsError`).

Thank you for your time.
