### ISSUE TITLE
Incorrect error from CFE: Non-nullable variable used before it's assigned.

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#41103]
We currently crash when trying to report this: https://github.com/dart-lang/sdk/issues/41102

I can fix the crash with `inferrer.helper?.uri` around here:

https://github.com/dart-lang/sdk/blob/a5704eaca39b2d28fec0e1f26d9b808743f74c68/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart#L5553

This error doesn't make sense to me.

Repro:

```dart
import 'dart:async';

void main() {}
final t = StreamTransformer.fromHandlers(
    handleData: (data, sink) => Future.microtask(() => sink.add(data)),
    handleDone: (sink) => Future.microtask(() => sink.close()));
```

Output:

```
foo.dart:5:56: Warning: Non-nullable variable 'sink' is used before it's assigned.
    handleData: (data, sink) => Future.microtask(() => sink.add(data)),
                                                       ^^^^
foo.dart:6:50: Warning: Non-nullable variable 'sink' is used before it's assigned.
    handleDone: (sink) => Future.microtask(() => sink.close()));
                                                 ^^^^
```

`sink` is an argument. How can it be unassigned? The analyzer doesn't report this error.

**Comment by natebosch** [comment]
Found a workaround, if you specify the types that would be inferred on the constructor call this doesn't happen.

```dart
import 'dart:async';

void main() {}
final t = StreamTransformer<Object?, Object?>.fromHandlers(
    handleData: (data, sink) => Future.microtask(() => sink.add(data)),
    handleDone: (sink) => Future.microtask(() => sink.close()));
```

**Comment by lrhn** [comment]
Parameter variables are always definitely assigned (even optional ones), so this is a bug. They work the same as variables with initializers, which are always definitely assigned.
