### ISSUE TITLE
Flutter converting String to Array then compare two array

### ISSUE THREAD

**Issue by sivapictuscode** [dart-lang/sdk#41117]
I'm trying to convert strings to arrays then compare two arrays. If same value need to remove from both arrays. Then finally merge two arrays and find array length. Below is my code

     String first_name = "siva";
     String second_name = "lovee";
     List<String> firstnameArray=new List();
     List<String> secondnameArray=new List();
     firstnameArray = first_name.split('');      
     secondnameArray = second_name.split('');
     var totalcount=0;
     for (int i = 0; i < first_name.length; i++) {
      for (int j = 0; j < second_name.length; j++) {
        if (firstnameArray[i] == secondnameArray[j]) {
            print(firstnameArray[i] + "" + " == " + secondnameArray[j]);
            firstnameArray.removeAt(i); 
            secondnameArray.removeAt(i); 
            break;

          }
         }
       }
      var finalList = new List.from(firstnameArray)..addAll(secondnameArray);
     print(finalList);
     print(finalList.length);
But always getting this error Unsupported operation: Cannot remove from a fixed-length list can you help me how to fix this issue. Thanks.

**Comment by Jahnavi-Jonnalagadda** [comment]
@sivapictuscode I would like to work on this issue.

**Comment by mit-mit** [comment]
Sorry, this issue tracker is meant for tracking defects and enhancements to the core Dart SDK, not for support question. For those please consider StackOverflow and similar.
