### ISSUE TITLE
GLFW window cleanup causes a Segmentation Fault on exit

### ISSUE THREAD

**Issue by FeatherRune0** [dart-lang/sdk#41125]
Creating a window with `glfwCreateWindow()` and  wrapping up with `glfwTerminate()` works fine in C:
```
#include <stdio.h>
#include <GLFW/glfw3.h>

void main() {
    glfwInit();
    GLFWwindow *window = glfwCreateWindow(640, 480, "GLFW Test", NULL, NULL);
    glfwDestroyWindow(window);
    glfwTerminate();
}
```

With bindings for the same:
[glfwtest.txt](https://github.com/dart-lang/sdk/files/4359310/glfwtest.txt)

I get a segmentation fault when main() exits (not on glfwTerminate()):
```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7fc4008b24e0
version=2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "linux_x64"
thread=9226, isolate=(null)((nil))
Stack dump aborted because GetAndValidateThreadStackBounds failed.
zsh: abort (core dumped)  dart glfwtest.txt
```
There is no segmentation fault if no window is created.

### System Details
OS: Arch Linux, Gnome on Wayland
Using Dart 2.7.1 from the archive:
`Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "linux_x64"`
The glfw library is `glfw-wayland` from the arch community repository.

**Comment by dcharkes** [comment]
@FeatherRune0 can we repro this with https://github.com/FeatherRune0/dart-experiments/tree/master/glfw ?

**Comment by FeatherRune0** [comment]
> @FeatherRune0 can we repro this with https://github.com/FeatherRune0/dart-experiments/tree/master/glfw ?

Yes, simple.dart will crash in a similar manner on closing the window(Esc if the titlebar is not shown on wayland environments).
glfwtest.txt is just a minimal version of simple.dart.

**Comment by dcharkes** [comment]
It does not reproduce for me on a build from yesterday or 2.7.1.

```
dacoharkes@dacoharkes-l:~/ffi_samples/FeatherRune0/dart-experiments/glfw$ ~/master/sdk/out/DebugX64/dart simple.dart
[does not crash on closing window]
dacoharkes@dacoharkes-l:~/ffi_samples/FeatherRune0/dart-experiments/glfw$ ~/master/sdk/out/DebugX64/dart --version
Dart VM version: 2.8.0-edge.3b6935f30e6f020e47eb8f455208bf6e532085e2 (Thu Mar 19 11:26:39 2020 +0000) on "linux_x64"
dacoharkes@dacoharkes-l:~/ffi_samples/FeatherRune0/dart-experiments/glfw$ ~/Downloads/dart-sdk/bin/dart simple.dart
[does not crash on closing window]
dacoharkes@dacoharkes-l:~/ffi_samples/FeatherRune0/dart-experiments/glfw$ ~/Downloads/dart-sdk/bin/dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "linux_x64"
```

**Comment by FeatherRune0** [comment]
> I'm using the libglfw3 that gets installed from apt-get on Debian.

Now I am not sure if it's a bug in dart, glfw's wayland implementation, or Arch's glfw build.

I retested it in an xorg environment with glfw-x11 instead of glfw-wayland, and:
- The C version does not segfault with glfw-x11 and glfw-wayland
- The Dart version segfaults with glfw-wayland only

I will do some further tests with my own glfw builds tomorrow.

**Comment by FeatherRune0** [comment]
On testing with local glfw builds, I get the same results as before, so it's not Arch-specific but almost certainly related to wayland.

This was confirmed when I used a Ubuntu 18.04 vm and tested it with the Ubuntu on Wayland session:
- With `libglfw3` from the repositories, no segfault
- With `libglfw3-wayland`, segfault on exit
```
pulak@pulak-VirtualBox:~/dart-experiments/glfw$ ~/dart-sdk/bin/dart simple.dart 

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7f267b8320d0
version=2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "linux_x64"
thread=6744, isolate=(null)((nil))
Stack dump aborted because InitialRegisterCheck failed.
Aborted (core dumped)
```

**Comment by a-siva** [comment]
Based on your comment above this does not seem to be a Dart issue, can we close this issue.
