### ISSUE TITLE
loadLibrary() return type

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#41122]
What is the return type of `deferredPrefix.loadLibrary()` when NNBD?
Currently in analyzer it is `Future<dynamic>`.
But this does not match CFE.
@leafpetersen @lrhn Could you clarify this?

```dart
import self as self;
import "dart:async" as asy;
import "dart:core" as core;

import "dart:math" deferred as math;

static method main() → dynamic {
  asy::Future<dynamic>? v = LoadLibrary(math);
  core::print(v);
}
```

**Comment by scheglov** [comment]
See the [test log ](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8885368700577466912/+/steps/test_results/0/logs/new_test_failures__logs_/0) and [the CL](https://dart-review.googlesource.com/c/sdk/+/139980) where is causes issues.

**Comment by lrhn** [comment]
The spec is (yet) silent on the type of the future returned, and doesn't specify the static type of the `loadLibrary` function. We are [aware of that](https://github.com/dart-lang/language/issues/567)
and have a CL to fix it: https://github.com/dart-lang/language/pull/568

The change will make the static signature `Future<void> loadLibrary()` and it must return a future of `void`, `dynamic` or `Object?` (a top type) at run-time,  and it is completed with `null`.

**Comment by scheglov** [comment]
Thank you.

So, `lib.loadLibrary()` returns a non-nullable type (`Future<void>`), and the null check in [isolate tests](https://dart-review.googlesource.com/c/sdk/+/139980/4/tests/lib/isolate/deferred_in_isolate2_test.dart) is not necessary. Probably something to fix in CFE. @a-siva
