### ISSUE TITLE
gen_snapshot --print-instructions-sizes-to prints duplicate symbol names

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#41137]
For example, in the dump for the `hello_world` app from the Flutter repo, there are three entries for `dart:ui/ChannelBuffers._onDropItem`:

```
{
    "l": "dart:ui",
    "c": "ChannelBuffers",
    "n": "[Optimized] ChannelBuffers._onDropItem",
    "s": 56
  },
  {
    "l": "dart:ui",
    "c": "ChannelBuffers",
    "n": "[Optimized] ChannelBuffers._onDropItem",
    "s": 224
  },
...
  {
    "l": "dart:ui",
    "c": "ChannelBuffers",
    "n": "[Optimized] ChannelBuffers._onDropItem",
    "s": 100
  },
```

Using the https://github.com/dart-lang/sdk/blob/master/pkg/vm/bin/run_binary_size_analysis.dart script just takes the _last_ value. This doesn't seem to happen often, and looking at the code my only guess is that it's somehow related to tearoffs.  It'd be nice if the output named these uniquely though to avoid overwriting.

/cc @alexmarkov @mraleph @rmacnak-google

**Comment by dnfield** [comment]
Alternatively, are they just supposed to be combined?

**Comment by mraleph** [comment]
Combining them would be misleading - we should just produce proper names for them. I will take a look at this.
