### ISSUE TITLE
It is an error to call the default List constructor.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#41132]
With the analyzer [issue](https://github.com/dart-lang/sdk/issues/41130) fixed many existing tests started to fail.

See [the log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8885272659621380848/+/steps/test_results/0/logs/new_test_failures/0).
I will open a separate issue for the co19 failures.

**Comment by athomas** [comment]
These tests are passing on most configurations, so I'm assuming the tests are fixed.

https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LanguageFeatures/nnbd/null_aware_operator_A12_t01,corelib/collection_length_test,corelib/expando_test,corelib/iterable_contains_test,corelib/iterable_fold_test,corelib/iterable_reduce_test,corelib/iterable_return_type_test/01,corelib/iterable_return_type_test/02,corelib/iterable_return_type_test/none,corelib/linked_hash_map_test,corelib/list_as_map_test,corelib/list_concurrent_modify_test,corelib/list_fixed_test,corelib/list_for_each_test,corelib/list_growable_test,corelib/list_index_of_test,corelib/list_insert_test,corelib/list_iterators_test,corelib/list_removeat_test,corelib/list_set_range_test,corelib/list_test/01,corelib/list_test/none,corelib/list_to_string2_test,corelib/range_error_test,corelib/string_base_vm_test,corelib/string_from_list_test,language/assert/assignable_type_test,language/assert/with_type_test_or_cast_test,language/nnbd/static_errors/default_list_constructor_test/none,lib/async/future_or_type_test,lib/async/slow_consumer_test,lib/async/slow_consumer2_test,lib/convert/json_lib_test,standalone/array_bounds_check_generalization_test,standalone/io/addlatexhash_test,standalone/io/directory_test,standalone/io/file_test,standalone/io/http_read_test,standalone/io/http_reuse_server_port_test,standalone/io/http_server_early_client_close_test,standalone/io/regress_8828_test,standalone/io/socket_finalizer_test,standalone/io/web_socket_typed_data_test
