### ISSUE TITLE
It is an error to call the default List constructor

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#41130]
The spec [was changed](https://github.com/dart-lang/language/commit/579155976e4e1778cb96baedcbe3da5d9b6d8aa9#diff-dcbb29985b096645570ae14645f65d53R296). No matter, with nullable type argument, or length.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/140363

**Comment by scheglov** [comment]
The CL fixes two co19 tests, but [breaks a lot](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8885272659621380848/+/steps/test_results/0/logs/new_test_failures/0) of other tests, mostly library, some language tests. @leafpetersen @munificent Are we still OK to make this change? What do we do with tests - who will update them? Should I open new issues (with which area?) and approve the bot failures?

**Comment by leafpetersen** [comment]
@scheglov Go ahead and approve the failures.   File an issue with the list of tests you're approving, area-test.   You can assign it to me, I'll find an owner or fix them myself.
