### ISSUE TITLE
Dart2js the Future in JavaScript

### ISSUE THREAD

**Issue by Dorbmon** [dart-lang/sdk#41146]
I looked over a lot of document about dart web.
And I still dont know how to deal with Future Object from dart in Javascript.
I am sorry to ask this problem here but I wanna know the answer.Thanks.

**Comment by mit-mit** [comment]
Can you clarify your question with a few more details and if possible a small code snippet?

**Comment by Dorbmon** [comment]
@mit-mit 
```
import 'dart:html';
import 'dart:js_util';
import 'dart:js' as js;

import 'normalHttp.dart';
Future<String> getUserData () async {
  //do someting....
  return 'tmp';
}


void main() async {
  js.context ['getUserData'] = getUserData;
}
```
Like this.When I call getUserData () in JavaScript,How Can I get the real data instead of Future Object?

**Comment by Dorbmon** [comment]
@mit-mit In dart I can use await to resolve this.But how to do it in JavaScript?
