### ISSUE TITLE
MSAN Failures on [dart:io] support Unix domain communications

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#41143]
There are new test failures on [[dart:io] support Unix domain communications](https://github.com/dart-lang/sdk/commit/ed83a28d3ee46437dcd624300ec6c003093a6659).

The tests
```
standalone_2/io/socket_from_raw_path_test Crash (expected Pass)
standalone_2/io/unix_socket_test Crash (expected Pass)
```
are failing on configurations
```
dartk-msan-linux-release-x64
```

**Comment by ZichangG** [comment]
I'll track the failure in https://github.com/dart-lang/sdk/issues/41141.
