### ISSUE TITLE
service/dominator_tree tests failing

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#41144]
@rakudrama (causing committer) @bkonyi (last change to tests): I'm not sure whether these failures warrant a revert or not. Please investigate.

=====================================================================

There are new test failures on [[dart2js] Handle NullableType from createFromStaticType](https://github.com/dart-lang/sdk/commit/ff43aa3285cbf566bc41ba3ec4df7ca64599eedf).

The tests
```
service/dominator_tree_vm_test/1 RuntimeError (expected Pass)
service/dominator_tree_vm_test/2 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-debug-x64
```

stderr:
Unhandled exception:
Dummy exception to set exit code.
https://dart-ci.appspot.com/log/vm-kernel-linux-debug-x64/dartk-linux-debug-x64/9204/service/dominator_tree_vm_test/1
https://dart-ci.appspot.com/log/vm-kernel-linux-debug-x64/dartk-linux-debug-x64/9204/service/dominator_tree_vm_test/2

=====================================================================

Most likely that commit is also the culprit in the failure below.

There are new test failures on [[tests] Add language version comment ddc tests...null-safety fixes for ListCopy benchmark setup](https://github.com/dart-lang/sdk/compare/13e56c6a3a5972c044da5c3d0c3352ca607387b4~...9b26e2dbffdbcb318ff7cf15aec141f5bbaa6ead).

The tests
```
service/dominator_tree_vm_with_double_field_test/2 RuntimeError (expected Pass)
```
are failing on configurations
```
app_jitk-linux-debug-x64
```

 segfault:
https://dart-ci.appspot.com/log/app-kernel-linux-debug-x64/app_jitk-linux-debug-x64/5628/service/dominator_tree_vm_with_double_field_test/2

**Comment by bkonyi** [comment]
I think that these tests might have been previously marked as failing and we're only seeing this issue now because of the reverts I had done. @rmacnak-google can you take a look when you get a chance?
