### ISSUE TITLE
dartk-weak-asserts-linux-release-x64 uses the upcoming default value in `fromEnvironment`, not the current one

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41145]
In commit cbd67124d10e277e52e94f37d32aa517afeb549a, the following command succeeds:

```
> tools/test.py -n dartk-weak-asserts-linux-release-x64 lib_2/isolate/string_from_environment_default_value_test
```

In that test it is tested (where the environment does not contain a declaration named 'NOT_FOUND') that

```dart
Expect.equals('', const String.fromEnvironment('NOT_FOUND'));
 ```

This test was expected to fail until we introduce the breaking change where the default value of `defaultValue` of `String.fromEnvironment` is changed to the empty string.

However, the behavior of dartk-weak-asserts-linux-release-x64 seems to have been updated such that the test succeeds now, even though no changes have been made to the default value of `defaultValue` in sdk/lib/core/string.dart.

The same issue exists with `int.fromEnvironment`, in the test 'lib_2/isolate/int_from_environment_default_value_test'.

**Comment by johnniwinther** [comment]
`dartk-weak-asserts-linux-release-x64` runs with `sdk_nnbd` and therefore uses the new default values.

**Comment by eernstg** [comment]
OK, but then it's surprising that it is running a test in lib_2.

**Comment by eernstg** [comment]
OK, clarified: The test run is performed as it would be after unforking, that is, using declarations from sdk_nnbd and opting out the test (because it is in a `_2` directory).
