### ISSUE TITLE
Building Flutter assets on virtual system takes a long time

### ISSUE THREAD

**Issue by kf6gpe** [dart-lang/sdk#41153]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=48828.

https://github.com/flutter/flutter/issues/53098.

**Comment by mit-mit** [comment]
@kf6gpe what leads us to believe this is a Dart issue?

**Comment by kf6gpe** [comment]
Initial reports on the linked bug looked like it occurred with a minimal
dart reproducible case.


Ray Rischpater, KF6GPE | kf6gpe.org | @kf6gpe
<http://www.twitter.com/kf6gpe>

**Comment by liamappelbe** [comment]
cc @ZichangG

**Comment by ZichangG** [comment]
From the description, I can only tell It tried to `connect` to a link-local address and succeeded.  Something went wrong after that.
I don't have environment to reproduce. It will be helpful if someone from flutter team can triage the problem.

**Comment by pylaligand** [comment]
The connection timed out after an hour.

**Comment by srawlins** [comment]
Triaging this to area-vm for now. Please re-label if inappropriate.

**Comment by mraleph** [comment]
As far as I understand there is no reason to suspect that there is a bug in Dart at this stage.
