### ISSUE TITLE
Please merge 6a5d73dfe7 into stable channel

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41157]
**commit(s) to merge**: 6a5d73dfe7

**merge instructions**: clean merge

**reason**: Needed for 2.7.2

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by mit-mit** [comment]
Merge approved, @athomas are you doing the merge?

**Comment by athomas** [comment]
This change was released in 2.7.2.
