### ISSUE TITLE
Allocations in old space for promoted objects should not be aggressively growth limited

### ISSUE THREAD

**Issue by lexprfuncall** [dart-lang/sdk#4116]
The old space allocations used to reserve storage for promoted new space objects are currently subject to growth control.  As such, only allocations that may fill the available space in free lists and the current bump allocate page are guaranteed to be satisfied.

Ideally, the page space controller would allocate storage more liberally during promotion.  For example, it might be helpful to exhaust all of the pages in the growth entitlement before failing the allocation.

**Comment by iposva-google** [comment]
Stale.

**Comment by iposva-google** [comment]
Stale.

**Comment by iposva-google** [comment]
Scavenger forces growth when promoting objects and has been for quite a while.
