### ISSUE TITLE
Make class-specific allocation stubs call a shared stub for the actual bump pointer allocation and slow path

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#41175]
To reduce code size we can make our existing class-specific allocation stubs call a shared stub. The shared stub can have the actual bump pointer allocation and slow path.

**Comment by zoeyfan** [comment]
Roughly 3% reduction in uncompressed size when testing on Flutter gallery.

**Comment by zoeyfan** [comment]
The remaining work is lower priority now. Will come back to it later.

**Comment by zoeyfan** [comment]
The remaining work is not size-related.

**Comment by mkustermann** [comment]
This has been implemented and there's no further work planned atm.
