### ISSUE TITLE
Migration should have a way to preview usages to see whether nullability makes sense

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41186]
Sometimes the only way to really know whether something should or shouldn't be nullable is to see how its used. Add a way to see that.

**Comment by MichaelRFairhurst** [comment]
Hopefully this can solve a similar problem: helping users know whether it would be ok to make something late. (Or, in the case that we infer late, showing them why we did not infer it as late?)

If these seem like different ideas as this gets worked on, the above should be split into its own ticket for potential solutions.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
