### ISSUE TITLE
Migration should consistently comment out or delete @ on @required

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41181]
It seems like the migration tool is commenting out the `@` in `@required` regardless of whether fix builder is set to delete or not. Investigate.

**Comment by srawlins** [comment]
Is the general idea behind "removeViaComments" that the tool should not be overly-destructive? Or is it about removing code that may still be live in weak null-checking mode? If it's the former, we may want to keep the existing behavior. i.e. if we change `@required` to `required` and then remove the `import "package:meta/meta.dart` import, that seems on the same order-of-destruction as removing dead code branches. WDYT?

**Comment by srawlins** [comment]
Oh, I ask also because there is a comment in edit_plan.dart:

> // TODO(paulberry): don't remove comments

and comments cannot affect strong/weak checking; their removal only affects how destructive the tool is...
