### ISSUE TITLE
Migration: Move edit list panel to the left of the UI

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41185]
So that the right is the stack trace, the left is only nav

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
