### ISSUE TITLE
Migration should handle && in assert statements

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41184]
We have already seen at least one example in dart:ui for web with a compound assert statement:

```dart
assert(x != null && x > 0);
```

We should handle this like

```dart
assert(x != null);
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
