### ISSUE TITLE
dart2js should determine null safe "strongness" based upon entrypoint language version

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41208]
Enabled #41203
Requires #41205

**Comment by johnniwinther** [comment]
CFE now supports computing the language version for an entrypoint (https://dart-review.googlesource.com/c/sdk/+/141250) and .dill files now contain a `Component.mode` that matches the nnbd compilation mode for the entry-point when present (https://dart-review.googlesource.com/c/sdk/+/142149).
