### ISSUE TITLE
NNBD: Isolate.packageConfig is null unless `--packages` is explicitly supplied

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41200]
This only happens in the NNBD sdk.

Repro program:

```dart
import 'dart:isolate';

void main() async {
  print(await Isolate.packageConfig);
}
```

## Expected behavior

prints the uri for the loaded package config

## Actual behavior

prints `null` unless the program is invoked with `--packages=<some-path>`.

## Impact

You cannot create a `PackageConfig` that matches the current isolate, since you cannot know what package config file was used to run the current isolate.

cc @lrhn

**Comment by a-siva** [comment]
Why do you say this happens only in the NNBD sdk, I tried this example on the regular Dart SDK and got the same result.

**Comment by a-siva** [comment]
Ok, I  was trying a case where there was no .packages file in the directory, with a file I see a difference between the regular SDK and the NNBD sdk.

**Comment by a-siva** [comment]
This  has been fixed here https://dart-review.googlesource.com/c/sdk/+/140773
