### ISSUE TITLE
CFE: add API to return language version of a URI

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41205]
Enables https://github.com/dart-lang/sdk/issues/41203

**Comment by johnniwinther** [comment]
The API is added in `package:front_end/src/api_prototype/language_version.dart`.

The method `languageVersionForUri(Uri uri, CompilerOptions options)` should be called with the entry-point URI and the `CompilerOptions` normally passed to the CFE. It'll return a `LanguageVersionForUri` object that holds the major and minor version number of the `uri`.

**Comment by jakemac53** [comment]
@johnniwinther are we still publishing `package:front_end` on pub? We need to somehow have access to this from a package as well (build_test, build_web_compilers, build_vm_compilers).

**Comment by kevmoo** [comment]
`package:front_end` is NOT published (any more) – https://pub.dev/packages/front_end

`_fe_analyzer_shared` IS – https://pub.dev/packages/_fe_analyzer_shared

I wonder if that's where this should go.

@MichaelRFairhurst has been doing work there related to language version, too – https://github.com/dart-lang/sdk/commit/3095a082cd1d747e090581e244d0a731544c3a0c#diff-7aad7314584f4b59d3a9e31b8a4b1745

**Comment by johnniwinther** [comment]
`_fe_analyzer_shared` is not published for end users dependencies.

cc @stereotype441

**Comment by kevmoo** [comment]
> `_fe_analyzer_shared` is not published for end users dependencies.
> 
> cc @stereotype441

`test` and `build` things need this API *somewhere*.  Could it be plumbed through `pkg:analyzer`?

**Comment by jakemac53** [comment]
We could re-implement it ourselves as well but I am concerned about getting out of date and any discrepancies that might arise between the implementations.

**Comment by stereotype441** [comment]
> We could re-implement it ourselves as well but I am concerned about getting out of date and any discrepancies that might arise between the implementations.

Agreed.  We should plumb this through `pkg:analyzer`.  In fact, I *think* Konstantin recently did so (or possibly he was planning to do so soon).  @scheglov is that correct?

**Comment by jakemac53** [comment]
One problem is we need to do this cheaply - as in something that only requires reading the package_config.json file and the entrypoint.

So the api we discussed previously on LibraryElement is not something we can use as it would be to expensive.

The reason is we have to get this information before we even start compiling, so it needs to be very fast.

**Comment by scheglov** [comment]
Do you want this API to get the language version for a file as a replacement for the API on `LibraryElement`, or in addition to it?

Do you want to use URI or file path? If it is URI, the API will require also `SourceFactory` to convert it into the file path, because `package_config.json` if file path based. In the most cases the `package_config.json` itself is the way to resolve `package:` URIs, and there are no other URI schemes. So, I think it would be easier to work with file paths, unless you have a requirement to work with URIs, then we need to discuss details.

Analyzer already has `lib/dart/analysis/utilities.dart` with `parseFile(path, resourceProvider)`. We could add `LanguageVersion getFileLanguageVersion(path, resourceProvider)`.

**Comment by jakemac53** [comment]
> Do you want this API to get the language version for a file as a replacement for the API on `LibraryElement`, or in addition to it?

Ideally in addition to it, this api is essentially only for things that invoke the CFE/compilers, while the `LibraryElement` api is for builder authors and more general use.

> Do you want to use URI or file path?

Uri (we don't have access to a path always), or the file might not even be on disk.

> If it is URI, the API will require also `SourceFactory` to convert it into the file path, because `package_config.json` if file path based.

Alternatively if its easier we could give you the contents of the file (something like the old parseMetadata api?).

> In the most cases the `package_config.json` itself is the way to resolve `package:` URIs, and there are no other URI schemes. So, I think it would be easier to work with file paths, unless you have a requirement to work with URIs, then we need to discuss details.

We will definitely have some other schemes in some cases, custom ones like `org-dartlang-app` and `asset`.

> Analyzer already has `lib/dart/analysis/utilities.dart` with `parseFile(path, resourceProvider)`. We could add `LanguageVersion getFileLanguageVersion(path, resourceProvider)`.

That seems pretty close to what we would want except with a uri instead (or accepting file contents).

**Comment by scheglov** [comment]
Hm... Analyzer searches for `package_config.json` that governs analysis of a file by looking up from the file into parent directories. And this uses analyzer's `ResourceProvider` abstraction over the file system. I'm not sure how to reconcile custom URIs and the file system abstraction.

**Comment by jakemac53** [comment]
I suppose we could simply fake everything as long as we supply a resource provider of our own? But I don't know how that api would determine the language version if it isn't given a package: uri? Or would you look up which package the file is a part of by iterating all the packages? Note that internally that is several thousand packages.

**Comment by scheglov** [comment]
Well, if it all will look as files in a `ResourceProvider` for analyzer, then it will work. It is just that at some point for clients adapting to requirements might be more work than not using some APIs.

In analyzer `Package` has `Folder rootFolder` and `Folder libFolder`. We indeed iterate over every `Package` in the `Packages` container class and check if the path of a file is in the `rootFolder`. We could organize packages in a prefix tree if optimization is necessary. If we expect that the same `package_config.json` will be used for multiple files, we should consider searching for this `package_config.json` once, and reuse for multiple requests.

**Comment by jensjoha** [comment]
> > `_fe_analyzer_shared` is not published for end users dependencies.
> > cc @stereotype441
> 
> `test` and `build` things need this API _somewhere_. Could it be plumbed through `pkg:analyzer`?

I don't know about package:test; but package:build already builds stuff, so it can obviously talk to the front-end somehow (as I recall through bazel builder or whatnot).

**Comment by jakemac53** [comment]
> I don't know about package:test; but package:build already builds stuff, so it can obviously talk to the front-end somehow (as I recall through bazel builder or whatnot).

The build_web_compilers/build_vm_compilers packages could use something exposed by the kernel bazel worker, yes. We would have to multiple commands to that which would complicate it a bit, but it would be doable.

For the test/build_test it would require spinning up a new process just to do this check which would be unfortunate.
