### ISSUE TITLE
Isolate.spawnUri should determine runtime null safe "strongness" from entrypoint library

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41207]
Enables https://github.com/dart-lang/sdk/issues/41203
Requires https://github.com/dart-lang/sdk/issues/41205
Replaces https://github.com/dart-lang/sdk/issues/40632

**Comment by johnniwinther** [comment]
CFE now supports computing the language version for an entrypoint (https://dart-review.googlesource.com/c/sdk/+/141250) and .dill files now contain a `Component.mode` that matches the nnbd compilation mode for the entry-point when present (https://dart-review.googlesource.com/c/sdk/+/142149).
