### ISSUE TITLE
VM: determine entrypoint strong runtime based on entrypoint language version

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41206]
Enabled https://github.com/dart-lang/sdk/issues/41203
Requires https://github.com/dart-lang/sdk/issues/41205

**Comment by a-siva** [comment]
Can you add a link to the proposal here so we can evaluate if this is feasible .

**Comment by kevmoo** [comment]
The proposal was verbal is a conversation with SWEs. @johnniwinther should populate the root issue (#41203 ) with details!

**Comment by johnniwinther** [comment]
CFE now supports computing the language version for an entrypoint (https://dart-review.googlesource.com/c/sdk/+/141250) and .dill files now contain a `Component.mode` that matches the nnbd compilation mode for the entry-point when present (https://dart-review.googlesource.com/c/sdk/+/142149).
