### ISSUE TITLE
VM exiting prematurely without message [Dart VM]

### ISSUE THREAD

**Issue by shyndman** [dart-lang/sdk#41213]
I'm running an async heavy program via Dart version `2.8.0-dev.16.0.flutter-ba8baa46b4`.

When run, it appears to do work for awhile, then exits with a successful return code, but much of the code is never run. If I write a print statement on the last line of my `main`, it never executes.

Any suggestions on how to narrow this down further? I'd like to provide useful information for debugging, but a repro would be very difficult.

**Comment by shyndman** [comment]
Ah, I've found the line it's not getting past. I'm going to close this until I have more info.

**Comment by shyndman** [comment]
OK, so the last line executed is something like this:

```dart
for (final source in sources) {
    print(source); // prints Future<String>
    print(await source); // stops execution, but not abruptly. stack unwinds
  }
```

**Comment by shyndman** [comment]
Alright, so I found the _logic_ problem. I still don't understand the VM behaviour.

That `source` variable, the `Future`, was never resolving. That's it. But why the immediate exit?

**Comment by devoncarew** [comment]
> That source variable, the Future, was never resolving

By resolving, do you mean completing? `await foo` should wait until that future completes. async await is implemented by re-writing functions to be switch statements; they will unwind the stack until the next portion of the function is ready to execute.

You may try some of the community resources (https://dart.dev/community) for general questions; this issue tracker is good for bugs in the implementations and feature requests. Thanks!

**Comment by shyndman** [comment]
Hi Devon,

Sorry, I don't think I've been clear. I'm encountering strange VM behavior that I can't explain, and I'm looking for help diagnosing the issue. Not _my_ issue, but why the VM is behaving as it is. As far as I can tell, this problem goes beyond my code.

It's entirely likely that I'm wrong, of course, but I think I've been at least somewhat reliable in my reports. Please reopen and give people an opportunity to comment.

**Comment by shyndman** [comment]
In summary, what I'm seeing is this — a premature exiting of the VM, with a zero exit code, no exception.

**Comment by shyndman** [comment]
Ah, I've got a dead simple repro. https://gist.github.com/shyndman/3835509059e9c651d86a5ed166eac399

**Comment by shyndman** [comment]
Don't worry about it @devoncarew. I filed a new issue. It's more to the point, and without the running commentary.

**Comment by devoncarew** [comment]
👍 thanks
