### ISSUE TITLE
Please focus on windows 10 apps using UWP

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/sdk#41220]
Please make it easier to make simple UWP apps easier andautomatic

**Comment by devoncarew** [comment]
Do you mean this for Dart command line apps, or Flutter desktop apps>

**Comment by fisforfaheem** [comment]
desktop apps

**Comment by devoncarew** [comment]
Great, thanks. Can you re-file this issue at flutter/flutter? Thanks where Flutter desktop work happens.
