### ISSUE TITLE
VM exiting prematurely without error when awaiting unresolvable future [Dart VM]

### ISSUE THREAD

**Issue by shyndman** [dart-lang/sdk#41225]
Encountered with Dart `2.8.0-dev.16.0.flutter-ba8baa46b4`.

awaiting on an unresolvable Future is exiting the application, without an error. 0 exit code.

Here's a reproduction:
https://gist.github.com/shyndman/3835509059e9c651d86a5ed166eac399

**Comment by lrhn** [comment]
This is known behavior.

The Dart VM terminates when there are tasks left in its task queues and no open ports that it can receive events on. At that point, it is guaranteed that nothing will ever happen again in that program.

If your program is waiting for a future at that point, the VM can't see that. All it sees is that the program is not going to do anything (including ever completing that future).
Effectively, your entire program can be garbage collected at this point, which the VM does by exiting.

To take your code as example, slightly modified:
```dart
main() {
  something();
}
void something() async {
  final c = Completer();
  try {
    await c.future;
  } catch (e) {
    print('exception');
  } finally {
    print('finally');
  }
}
```
Here the `main` method calls a function which immediately returns a future.
The `main` method ignores that future.
Behind the scenes, a completer has been created, and a listener has been added to its future, and ... that's it. Nothing else is scheduled to happen, and the program just ends.


The only real alternative to ending the program would be to make it block. However, that's not what you want your normal successful programs to do when there is nothing more to do, so it should only block if you are waiting for a future. That's not something the VM tracks, and not something that would be particularly useful in most cases, so there is very little incentive to change the current behavior.

**Comment by shyndman** [comment]
Thanks.

Do you think it would be worthwhile to print something to the console? The issue can be quite baffling in a real codebase.

**Comment by shyndman** [comment]
Just from an ergonomics standpoint, there's not a lot presented to the user to help them debug the issue.

**Comment by lrhn** [comment]
That has been suggested before (for example https://github.com/dart-lang/sdk/issues/23797).
I'll just mark this issue as a duplicate of that enhancement request..

**Comment by shyndman** [comment]
Cool. Thanks @lrhn

**Comment by devoncarew** [comment]
I think this is working as intended, if a bit counter intuitive.

I believe there's no task on the task queue for the VM to perform; now waiting callback to call or I/O to wait for. @a-siva can confirm the VM behavior.

It doesn't reach the finally clause below as for async code, that's re-written into a function with a switch statement - a case for each async break. The VM does exit the method at an async ketword.

Here's your example in-lined.

```
import 'dart:async';

void main() async {
  final c = Completer();

  try {
    // I would expect this to either fail noisely because it can't complete OR
    // stall endlessly, but instead it triggers a silent exit. VM exits with a 0.
    await c.future;
  } catch (e) {
    // Nope. Never hit.
    print('exception');
  } finally {
    // This either.
    print('finally');
  }
}
```

**Comment by devoncarew** [comment]
Ah, looks like Lasse has answered above.
