### ISSUE TITLE
analyzer publish required before unforking SDK

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#41222]
The head analyzer contains many fixes from #40192  that will be necessary to produce correct results for clients, including dartdoc, when the SDK is unforked.  We need to publish a new version of the analyzer before that happens.

Note: Analyzer need to publish before any unforked SDK (dev release included) release

**Comment by stereotype441** [comment]
This is currently blocked on a change to pub (https://github.com/dart-lang/pub/pull/2400) to make it use a new analyzer API for accessing language versions (the new API was added here: https://dart-review.googlesource.com/c/sdk/+/140768/8/pkg/analyzer/lib/dart/ast/ast.dart)

I'm assuming that once the pub change lands, we'll need a follow-up change to remove the old API from the analyzer.  Is that correct, @MichaelRFairhurst?

After that, do we need to do anything further before we can publish the analyzer?  (@jcollins-g @scheglov)

**Comment by scheglov** [comment]
I don't have anything to do before publishing a new version.

**Comment by jcollins-g** [comment]
I had thought I saw use of some unpublished dart:async APIs (runZonedGuarded) but those are all in analysis_server.  So I know of nothing else to do prior to publish.

**Comment by kevmoo** [comment]
> This is currently blocked on a change to pub ([dart-lang/pub#2400](https://github.com/dart-lang/pub/pull/2400)) to make it use a new analyzer API

This is in and has been synced to the SDK!

**Comment by MichaelRFairhurst** [comment]
Unfortunately it got rolled back.

Flutter apparently also has somewhere importing some version of pub that
needs to be updated.

**Comment by franklinyow** [comment]
@athomas for awareness

**Comment by stereotype441** [comment]
Analyzer version 0.39.5 was published on Friday, so I believe this is taken care of.
