### ISSUE TITLE
aot:  Discontinue `--package-root=`

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41245]
Dart tools have historically supported two flags for specifying the location of packages:

--package-root= or -p
--packages=
The first option (--package-root=) does not support language versioning, and has very lacking test coverage (and thus likely is already broken), so we should remove it.

This is a work issue under #41197
[source code](https://github.com/search?q=org%3Adart-lang+package-root&type=Code)

**Comment by mit-mit** [comment]
@mkustermann did you fix this?

**Comment by mkustermann** [comment]
I've made the VM use the new `.dart_tool/package_config.json` (if available) instead of the old `.packages`.

There's still some left-over code regarding the actual parameter (which is ignored). Let me make a CL to remove the code.
