### ISSUE TITLE
dart: Discontinue `--package-root=`

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41246]
Dart tools have historically supported two flags for specifying the location of packages:

--package-root= or -p
--packages=

The first option (--package-root=) does not support language versioning, and has very lacking test coverage (and thus likely is already broken), so we should remove it.

This is a work issue under #41197
[source code](https://github.com/search?q=org%3Adart-lang+package-root&type=Code)

**Comment by franklinyow** [comment]
Is this done?

**Comment by mkustermann** [comment]
Yes, the flag has been removed from `dart` binary. In 39577ea564597f1834b0794db30833370365fb56

See the same bug in https://github.com/dart-lang/sdk/issues/41245.
