### ISSUE TITLE
js-interop: @JS() annotated class with "internal" method

### ISSUE THREAD

**Issue by davystrong** [dart-lang/sdk#41250]
When adapting a JS library to Dart, I would like to provide ```Future```s instead of a dynamic that is an actual JS promise, that then has to be converted with ```promiseToFuture```. Basically, I'd like to convert it internally:

```
@JS()
class PDFDocumentLoadingTask {
  @JS('promise')
  external dynamic get _promise;
  Future get future => promiseToFuture(_promise);
}
```

However, this throws an error saying ```Member 'future' in js-interop class PDFDocumentLoadingTask' is not external.```.

Unfortunately, I don't remotely understand how the whole JS interop works internally, so there may be some reason this can't be done, but if this could be added it would be very helpful.

**Comment by devoncarew** [comment]
cc @natebosch

**Comment by davystrong** [comment]
I found a Typescript version of the library I was working on so I tried using the js_facade_gen command to create the Dart bindings. To get past the problem I had it creates two classes and an extension: The main (normal JS) class, a private class with the promises, also pointing to the JS class and an extension to the main class that converts all the promises to futures. It works well but seems like a lot of extra work...

**Comment by natebosch** [comment]
The workaround you found is the correct one. We agree that it is a lot of boilerplate, unfortunately we don't have an ability to do it automatically or add non-extension members to reduce the boilerplate with our current JS interop design.

This is something we'll keep in mind if we are able to ship significant changes to our JS interop design, but it's not something we'll be able to address in the short term.

cc @sigmundch

**Comment by davystrong** [comment]
Ok, thanks for the reply!
