### ISSUE TITLE
Failures on [nnbd_migration] Save line number of details to preserve on reload.

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#41262]
There are new test failures on [[nnbd_migration] Save line number of details to preserve on reload.](https://github.com/dart-lang/sdk/commit/0943e6136d4272e64a7666a9d11532863f4eff3e).

The tests
```
service/dominator_tree_vm_test/2 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-debug-x64
```

/cc @rmacnak-google @MichaelRFairhurst

**Comment by rmacnak-google** [comment]
Another instance of https://github.com/dart-lang/sdk/issues/41144
