### ISSUE TITLE
"Drop some Function objects not needed at runtime" causes failures

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#41261]
After https://dart-review.googlesource.com/c/sdk/+/137104 landed the following tests started failing

ffi_2/null_regress_39068_test broke (Pass -> Crash, expected Pass)
ffi_2/variance_function_test/0 broke (Pass -> Crash, expected Pass)
ffi_2/variance_function_test/1 broke (Pass -> Crash, expected Pass)
ffi_2/variance_function_test/2 broke (Pass -> Crash, expected Pass)
samples/ffi/samples_test broke (Pass -> Crash, expected Pass)

Please see for details 
[steps/test_results/0/logs/new_test_failures__logs_/0](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8884376574725308960/+/steps/test_results/0/logs/new_test_failures__logs_/0)

Instead of reverting the CL, I have filed this issue and approved the failures.

**Comment by sstrickl** [comment]
Thanks, Siva! I'll take a look, since this is all
