### ISSUE TITLE
GZipCodec().decoder.convert should throw a known exception on failure.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#41270]
This program:

```dart
import 'dart:io';

main() async {
  try {
    print(GZipCodec().decoder.convert([10, 20, 30]));
  } catch (e, _) {
    print(e);
    print(e.runtimeType);
    print(e.runtimeType is Exception);
  }
}

```
prints:
```
InternalError: 'Filter error, bad data'
_InternalError
false
```

I would expect a `FormatException` or `IOException` of some sort because one cannot really know up-front if some input represents a correct gzip encoding.
Also it should be mentioned in the documentation somewhere.

**Comment by sortie** [comment]
`FormatException` would be consistent with the other decoders in `dart:convert`. Alternatively a special kind of exception could provide internal zlib error codes although that feels a bit bloated.

@ZichangG Do you want to take this issue?
