### ISSUE TITLE
Failures on "[tests/nnbd] Fork language/bool tests for weak and strong mode"

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#41278]
There are new test failures on [[tests/nnbd] Fork language/bool tests for weak and strong mode](https://dart-review.googlesource.com/c/sdk/+/141800).

The tests
```
language/bool/check_weak_test RuntimeError (expected Pass)
language/bool/condition_check_weak_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartdevk-weak-linux-release-chrome
```

In that CL I split NNBD tests to expect different exceptions if condition is null in strong mode (TypeError) and weak mode (AssertionError). The weak mode matches pre-NNBD behavior.

It looks like DDC is throwing TypeError both in strong and weak mode.

Context: https://groups.google.com/a/google.com/g/dart-nnbd-core/c/8zp4xh9kOTU/m/1rEy2_LPAQAJ

/cc @sigmundch @nshahan

**Comment by nshahan** [comment]
Related: TypeErrors are no longer AssertionErrors https://github.com/dart-lang/sdk/issues/40317.

**Comment by nshahan** [comment]
Spec clarification here: https://github.com/dart-lang/language/pull/917

**Comment by nshahan** [comment]
I'm working on a fix.
