### ISSUE TITLE
NNBD: Future flattening works incorrectly for non-nullable Object type.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41272]
Dart VM version: 2.8.0-dev.18.0 (dev) (Fri Mar 27 11:10:52 2020 +0100) on "windows_x64"

The following sample code example should throw a runtime error in "--enable-experiment=non-nullable --null-safety" mode, but it does not:
``` dart
import "dart:async";

dynamic getNull() => null;

Future<Object> test() async {
  Object o = await getNull();
  return o;
}

main() {
  test().then((value) { print(value); });
}
```
Sample output is:
> $> dart --enable-experiment=non-nullable --null-safety test.dart
> null

Please note that it works correctly for other non-nullable types, for example the following code throws error expectedly:
``` dart
import "dart:async";

dynamic getNull() => null;

Future<int> test() async {
  int o = await getNull();
  return o;
}

main() {
  test().then((value) { print(value); });
}
```
Sample output is:
> $> dart --enable-experiment=non-nullable --null-safety test.dart
> Unhandled exception:
> type 'Null' is not a subtype of type 'int'
> #0      test (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/test.dart:6:7)
> <asynchronous suspension>
> #1      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/test.dart:11:3)
> #2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
> #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
>

**Comment by eernstg** [comment]
@johnniwinther, is it the CFE that omits a cast, or is this a backend issue?

**Comment by johnniwinther** [comment]
It is a backend issue. The CFE adds an implicit `as` expression, `as{TypeError,ForDynamic,ForNonNullableByDefault} core::Object`, to the `await` expression.

**Comment by alexmarkov** [comment]
The following code

https://github.com/dart-lang/sdk/blob/43115b0f754c17857e2b198131d331301c556043/runtime/vm/compiler/backend/flow_graph_compiler_x64.cc#L436-L440

tests if class id of supertype of an instance's class matches the tested class. `Null` has `Object` as a supertype, so this code concludes that `Null` is assignable to `Object`.
