### ISSUE TITLE
Would like to send notifications via dart:developer

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#41277]
I would like to be able to send structured messages using `dart:developer` that are driven by the application instead of in response to a VM service extension call. These messages could be subscribed to by VM service clients, but would otherwise be ignored.

### Background

I'm currently exploring whether it is possible to drive a test script via the VM service. In this world, a test is a top level function such as:

```
void testFoo() {
  assert(Foo().isFoo(), 'expected foo to be foo');
}
```

The test runner would be a separate Dart program which connects to the VM service of a Dart VM. The test could be executed using the VM service `invoke` method, and the result inspected for an exception. This works until we consider tests that are async:

```
Future<void> testFoo() async {
  assert(await Foo().isFoo(), 'expected foo to be foo');
}
```

Now the `invoke` method will only tell the test runner that an instance of a Future has returned. (There are other issues too, such as handling a Future that never returns). To solve this, I could create a runtime test execution function and instead invoke this with the argument as the test to be executed:

```
Future<void> executeTest(Function test) async {
  try {
    await test().timeout(kTimeout);
  } catch (err) {
    /* send notification? */
  }
}
```

The only way I have found so far to notify the test runner, would be to log a message and wait for it. If I don't want to worry about confusing messages from the test itself with test results, I could instead send a notification

```
registerExtensionNotification('ext.example');

...
  } catch (err) {
     sendNotification('ext.example', {"pass": false});
 }

```

### Alternatives considered

Instead of trying to use the VM service to entirely drive tests, I could codegen some combination of service extension registration and test function registries. This induces a significantly larger amount of complexity:

1. If the tool generates a service extension per test or uses a registry of known test functions, then changing the number of tests requires a restart of the test isolate (loss of simple hot reload). Generating these in the first place will require either the analyzer to run over the test library, or the injection of another kernel transformer.

2. If the tool uses mirrors to locate test functions roughly equivalent to using the VM service, then we need to specifically configure Flutter test runners to allow the import. It may never work for web tests (though I'm unsure if `invoke` is supported on the web either). 

@bkonyi

**Comment by devoncarew** [comment]
We have some test fixtures in the devtools repo that drives out of process tests via using the service protocol and expressions evaluation.

I don't believe we handle async tests? I'm not up-to-speed on the current state of testing there.

I think you can just use the existing https://api.dart.dev/stable/2.7.2/dart-developer/postEvent.html dart:developer call to allow apps to send service protocol events.

**Comment by jonahwilliams** [comment]
Perfect, this is actually working great ... so I guess I don't need anything else :D
