### ISSUE TITLE
NNBD. Support new const objects syntax

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41286]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#const-objects)

> ...the following is a valid migration of this code:
> 
> ```dart
> const num three = 3;
> 
> class ConstantClass<T extends num> {
>   final T w;
>   const ConstantClass() : w = three as T;
> }
> 
> void main() {
>   print(const ConstantClass<int>());
> }
> ```
> 
But now this code produces an error in both analyzer and CFE

`dartanalyzer version 2.8.0-dev.18.0`

**Comment by johnniwinther** [comment]
Created #41305 for the CFE

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/142449
