### ISSUE TITLE
PADDING

### ISSUE THREAD

**Issue by matinsyn** [dart-lang/sdk#41280]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

**Comment by a-siva** [comment]
It is unclear what problem is being reported here, could you add some details on the problem encountered.
