### ISSUE TITLE
Align implementation of late fields with ordinary static fields in the VM.

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#41299]
Currently we use 2 entirely different approaches for initializing late static fields and non-late static fields. For late static fields we explicitly build flow graph which would read field's value, compare it to sentinel and call initializer function. For ordinary static fields we generate `InitStaticField` IL instructions which are generated to machine code as a test of a field value and a call to a stub/runtime.

We can choose one approach and use it for late and non-late static fields consistently (for example `InitStaticField` for late fields could omit checks for transition_sentinel and do more checks at runtime entry).

We can also align how we implement initialization of late instance fields with hot-reload field load guards (`InitInstanceField` instruction).

/cc @liamappelbe @mkustermann @a-siva @rmacnak-google @mraleph

**Comment by mkustermann** [comment]
Right now there is a semantic different between static fields in opted-out and opted-in libraries. For opted-out libraries we have to check for both sentinels in the fast path.

To avoid this difference, I've just earlier today filed a breaking change request, which would allow us to align the implementations with opted-in semantics: https://github.com/dart-lang/sdk/issues/41285

**Comment by alexmarkov** [comment]
@mkustermann We can test for that difference (e.g. `field.is_late()`) when generating code and omit checking for transition_sentinel. We can also test that at runtime entry when doing an assignment to a late final field to do extra checks. So I don't think this slight difference in semantics is blocking unification. There are more similarities than differences, so it makes sense to unify the code anyway.

**Comment by alexmarkov** [comment]
I created [CL](https://dart-review.googlesource.com/c/sdk/+/143100) which switches static late field implementation to use `InitStaticField` instruction.

The following code is generated for inlined static field getter in AOT mode on arm64:

Ordinary (non-late) static field: 12 instructions (with [this CL](https://dart-review.googlesource.com/c/sdk/+/143161))
```
        ;; InitStaticField:4()
        ;; Inlined [::.get_x]
0x14    f9404740               ldrx r0, [thr, #136]
0x18    f94d3c00               ldrx r0, [r0, #6776]
0x1c    f9416370               ldrx ip0, [pp, #704]
0x20    eb10001f               cmp r0, ip0
0x24    54000080               beq +16
0x28    f9646770               ldrx ip0, [pp, #18632]
0x2c    eb10001f               cmp r0, ip0
0x30    54000061               bne +12
0x34    f9646b60               ldrx r0, [pp, #18640]
0x38    94000000               bl +0
        ;; v6 <- LoadStaticField(x) T{int?}
        ;; Inlined [::.get_x]
0x3c    f9404741               ldrx r1, [thr, #136]
0x40    f94d3c20               ldrx r0, [r1, #6776]
```

Late static fields after switching to `InitStaticField` (both final and non-final): 9 instructions
```
        ;; InitStaticField:4()
        ;; Inlined [::.get_x]
0x14    f9404740               ldrx r0, [thr, #136]
0x18    f94d4000               ldrx r0, [r0, #6784]
0x1c    f9416370               ldrx ip0, [pp, #704]
0x20    eb10001f               cmp r0, ip0
0x24    54000061               bne +12
0x28    f964ab60               ldrx r0, [pp, #18768]
0x2c    94000000               bl +0
        ;; v6 <- LoadStaticField(x) T{int?}
        ;; Inlined [::.get_x]
0x30    f9404741               ldrx r1, [thr, #136]
0x34    f94d4020               ldrx r0, [r1, #6784]
```

Non-final late static fields with current IL implementation: 8 instructions
```
        ;; v6 <- LoadStaticField(x) T{int?}
        ;; Inlined [::.get_x]
0x14    f9404741               ldrx r1, [thr, #136]
0x18    f94d3c20               ldrx r0, [r1, #6776]
        ;; Branch if StrictCompare:4(===, v6, v13) goto (4, 5)
        ;; Inlined [::.get_x]
0x1c    f9416370               ldrx ip0, [pp, #704]
0x20    eb10001f               cmp r0, ip0
0x24    54000081               bne +16
        ;; B4
        ;; v11 <- StaticCall:14( init:x<0> ) T{int?}
        ;; Inlined [::.get_x]
0x28    94000000               bl +0
        ;; ParallelMove r0 <- r0
        ;; StoreStaticField(x, v11)
        ;; Inlined [::.get_x]
0x2c    f9404741               ldrx r1, [thr, #136]
0x30    f90d3c20               strx r0, [r1, #6776]
```

Final late static fields with current IL implementation: 19 instructions
```
        ;; v6 <- LoadStaticField(x) T{int?}
        ;; Inlined [::.get_x]
0x18    f9404741               ldrx r1, [thr, #136]
0x1c    f94d3c20               ldrx r0, [r1, #6776]
        ;; Branch if StrictCompare:4(===, v6, v16) goto (4, 5)
        ;; Inlined [::.get_x]
0x20    f9416370               ldrx ip0, [pp, #704]
0x24    eb10001f               cmp r0, ip0
0x28    540001e1               bne +60
        ;; B4
        ;; v11 <- StaticCall:14( init:x<0> ) T{int?}
        ;; Inlined [::.get_x]
0x2c    94000000               bl +0
        ;; ParallelMove r0 <- r0
        ;; ParallelMove S-1 <- r0
        ;; Inlined [::.get_x]
0x30    f81f83a0               strx r0, [fp, #-8]
        ;; v13 <- LoadStaticField(x) T{int?}
        ;; Inlined [::.get_x]
0x34    f9404742               ldrx r2, [thr, #136]
0x38    f94d3c41               ldrx r1, [r2, #6776]
        ;; Branch if StrictCompare:16(===, v13, v16) goto (7, 8)
        ;; Inlined [::.get_x]
0x3c    f9416370               ldrx ip0, [pp, #704]
0x40    eb10003f               cmp r1, ip0
0x44    540000c0               beq +24
        ;; B7
        ;; B8
        ;; PushArgument(v17)
        ;; Inlined [::.get_x]
0x48    f9646770               ldrx ip0, [pp, #18632]
0x4c    f81f8df0               strx ip0, [r15, #-8] !
        ;; StaticCall:28( _throwNew@0150898<0> v17)
        ;; Inlined [::.get_x]
0x50    94000000               bl +0
0x54    910021ef               addi r15, r15, 0x8
        ;; ParallelMove r0 <- S-1 goto:30 B9
        ;; Inlined [::.get_x]
0x58    f85f83a0               ldrx r0, [fp, #-8]
        ;; B9
        ;; StoreStaticField(x, v11)
        ;; Inlined [::.get_x]
0x5c    f9404741               ldrx r1, [thr, #136]
0x60    f90d3c20               strx r0, [r1, #6776]
```
