### ISSUE TITLE
DateTime bug when subtracting a month on march 31st

### ISSUE THREAD

**Issue by Fernandomr88** [dart-lang/sdk#41296]
I openned this same issue at flutter repo (https://github.com/flutter/flutter/issues/53671), guess this is the correct channel to do it.

So I have this code to subtract a month using DateTime.

```
   String _getMonthName({int fator}) {
    DateTime today = new DateTime.now();
    if (fator != null) {
      today = new DateTime(today.year, today.month + fator, today.day);
    }
    String mes = DateFormat("MMMM", "pt_BR").format(today);
    return '${mes[0].toUpperCase()}${mes.substring(1)}';
   }
```

Check that today is correct:
![image](https://user-images.githubusercontent.com/14304128/78056475-922f1a00-735b-11ea-95c2-a539d55b29b6.png)

**Then, with _factor of -1_ month, after using 'month -1' instead of going go february 28th or 29th, depending of the year, I go to march 02..check the image:**

![image](https://user-images.githubusercontent.com/14304128/78056747-fe118280-735b-11ea-9c5c-a8b1a4b0e953.png)

DateTime should be able to deal with this. I'm using a third party package to handle it instead (Jiffy)

**Comment by kevmoo** [comment]
CC @lrhn

**Comment by lrhn** [comment]
This is working as intended.

You are asking for `DateTime(2020, 2, 31)`. That day does not exist because month 2 only has 29 days in 2020. So, the result becomes two days after the 29th of February, also known as second of March.

**Comment by Fernandomr88** [comment]
```
void main() {
  DateTime time = DateTime(2020, 10, 31);
  print(time);
  print(DateTime(time.year, time.month-1, time.day));
}
```

this returns:
Oct 31
Oct 1

```
void main() {
  DateTime time = DateTime(2020, 10, 20);
  print(time);
  print(DateTime(time.year, time.month-1, time.day));
}
```

this returns:
Oct 20
Sept 20

So, basically what this method does is try to get the same date from the previous month, if it doesn't exists it returns some random not asked date?

I don't see as logical since i asked "MONTH - 1", I didn't ask for Feb 31st.

The whole point of it is that the method is supposed to subtract a month from the date and instead of returning me february 28 or 29 (correcting since 31st doesnt exist), it returned me the same month that I needed to subtract from.

The method is not reliable if it works on all days of the year but not at 3 of them (march 29[one year it will work], 30 and 31).

The logical to me is that IF the day doesn't exist, it returns the closest one from month - 1, not some totally random date like `DateTime(2020, 3, 2)`, i mean, if you have to deal with the issue of non existing days at least give the month intended.

**Comment by lrhn** [comment]
It's clear to you that you are asking for "one month less", but the constructor doesn't know that.
All it knows is that you are asking for a date that does not exist.

The `DateTime` constructor uses an overflow algorithm to handle invalid dates.
If you have a day-in-month value that is *n* days larger than the final day of the month, it instead picks the calendar date that is *n* days later. Similarly if the date is less than 1. That allows you to use *day* increments correctly: 
```dart
var today = DateTime.now();
var oneWeekLater = DateTime(today.year, today.month, today.day + 7);  // Wraps into next month.
```

If your month is too large or too small, it also overflows into the year. This happens before handling the day overflow.

So, when you ask for  `DateTime(2020, 2, 31)`, the constructor does not know what you're really asking for. It only sees the numbers. So, it gives you the day that is two days later than 2020-02-29.
This is quite consistent, there is nothing random about it.

There is no built-in way to ask for a day overflow/underflow to be capped at the end of the month.
It's also not entirely clear - would the end of the month be 2020-02-29, or 2020-02-29T23:59:59.999999999? Depends on whether you're talking dates only or date+time.
So, nothing built-in. 

If you want to cap the date, then I'd use something like:
```dart
DateTime cappedDate(int year, int month, int day) {
  var result = DateTime.utc(year, month, day);
  if (result.month > month) {
    result = DateTime.utc(year, month + 1. 0);  // last day 
  } else if (result < month) {
    result = DateTime.utc(year, month, 1); // first day.
  }
  return result;
}
```
