### ISSUE TITLE
Failed to load libffi_test_functions.so

### ISSUE THREAD

**Issue by micrcx** [dart-lang/sdk#41306]
When executing **_sample_ffi_functions_callbacks.dart_**, an error occurs due to the lack of the **_libffi_test_functions.so_** library:

```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (libffi_test_functions.so: cannot open shared object file: No such file or directory)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      dlopenPlatformSpecific (file:///home/micrcx/IdeaProjects/test_ffi/bin/dylib_utils.dart:19:25)
#3      main (file:///home/micrcx/IdeaProjects/test_ffi/bin/main.dart:35:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

Is there any source code for this library in C/C ++, how to build it, and where can I find it?

**Comment by a-siva** [comment]
Please refer to https://dart.dev/guides/libraries/c-interop for instructions on how FFI works and how to build the native library.

**Comment by a-siva** [comment]
I hope that link answered your question, please reopen a documentation issue if you feel more information is needed.

**Comment by LLLLL72** [comment]
I have the same problem.  It seems that the source code from that link doesn't match the dart samples. Where can I get the source code of  "libffi_test_functions.so".
