### ISSUE TITLE
Migrate runtime/tests/vm/dart to NNBD

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#41314]
We need to migrate tests in `runtime/tests/vm/dart` to NNBD. As they are still used in legacy mode, we might need to make a copy of those tests.

/cc @a-siva

**Comment by a-siva** [comment]
If we are able to migrate the tests without using any of the NNBD syntax then we could potentially get away without making a copy.

**Comment by alexmarkov** [comment]
`vm/cc` tests are not migrated too.

**Comment by alexmarkov** [comment]
All `vm` tests are now migrated to NNBD.
Remaining strong mode compile-time errors due to non-migrated dependencies are tracked in https://github.com/dart-lang/sdk/issues/42146.
