### ISSUE TITLE
Can I set environment variable like PUB_CACHE for .dartServer (and .dart too) folder

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#41316]
My current dev. env. placed to separated SDD without indexing and defender scanning.

**Comment by a-siva** [comment]
You should be able to use the Platform class to access environemnt variables, see the API documentation at https://api.dart.dev/stable/2.7.2/dart-io/Platform-class.html

**Comment by ykmnkmi** [comment]
No, I ask for SDK config/setup part, moving analyzer cache from user home folder to different place.
Like [here](https://dart.dev/tools/pub/glossary#system-cache)
