### ISSUE TITLE
RegExp named capture groups are not supported in Firefox

### ISSUE THREAD

**Issue by mdebbar** [dart-lang/sdk#41327]
Dart supports named capture groups in regular expressions (e.g. `(?<identifier>[_a-z]+)`). Both DDC and dart2js compile them to JavaScript unchanged. This feature is supported in all modern browsers except Firefox.

![image](https://user-images.githubusercontent.com/1278212/78385882-744afa80-7591-11ea-9dcb-eee2e775ee82.png)
_https://caniuse.com/#search=regexp%20named%20capture%20groups_

This is crashing Flutter gallery when running in Firefox. Here's [the line](https://github.com/flutter/gallery/blob/e8880f683cbd8a6738ecc38a7b2aa887ff7d9865/lib/routes.dart#L41) that's causing the exception. Issue: https://github.com/flutter/flutter/issues/53786

**Comment by sigmundch** [comment]
Thanks for all the details. Our current inclination is to not try to polifyll this missing feature. However, we may want to try to detect when this occurs (e.g. when the RegExp constructor directly shows the pattern as is the case you linked above) so we can warn developers about it.

@srawlins - what would it take to introduce a lint to detect whether a regexp is using this feature, so users are aware when they use it?

**Comment by srawlins** [comment]
I think this could be tricky to lint for. It's worth requesting at https://github.com/dart-lang/linter, but I think such a rule would be implemented with its own regex, which would just be very tricky to write, I think. I could be wrong.

**Comment by mdebbar** [comment]
Given that this is an issue in dart2js, not only DDC, it breaks [Dart's promise](https://dart.dev/faq#q-what-browsers-do-you-support-as-javascript-compilation-targets) to its users that it supports Firefox as a compilation target. We should at least clarify that Firefox isn't 100% supported.

**Comment by lrhn** [comment]
Firefox released support in version 78, on June 30th this year..
