### ISSUE TITLE
Please merge #8df9c9408b14507e0e0b9007b093353ebff6d021 into beta channel

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#41320]
**commit(s) to merge**: `8df9c9408b14507e0e0b9007b093353ebff6d021`

**merge instructions**: `git checkout origin/beta; git cherry-pick 8df9c9408b14507e0e0b9007b093353ebff6d021` (merges clean)

**reason**: Fixed issues in `pub outdated --no-dev-dependencies` contained transitive `dev_dependencies` without a headline. Essentially garbled output when `--no-dev-dependencies` is used.

------

Pub Issue: https://github.com/dart-lang/pub/issues/2426
Pub PR:  https://github.com/dart-lang/pub/pull/2427

Current `beta` has:
https://github.com/dart-lang/sdk/blob/da04c13b08e5688284e1c55cb6b08ec3a935d582/DEPS#L121

Commit https://github.com/dart-lang/sdk/commit/8df9c9408b14507e0e0b9007b093353ebff6d021 will bump this to: `3606265962da4248d34d352aa3d170aae4496a90`

Diff in [`pub` between the two commits](https://github.com/dart-lang/pub/compare/978cc9c4be7d8978348e56d4ae82be8257a59579...3606265962da4248d34d352aa3d170aae4496a90). This is only https://github.com/dart-lang/pub/pull/2427.

-------------

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by franklinyow** [comment]
Can we get more info on the description?

**Comment by vsmenon** [comment]
Assigning to @jonasfj for description.

**Comment by jonasfj** [comment]
Sorry for the slow turn around time.

**Comment by vsmenon** [comment]
@mit-mit - is this something we need in 2.8?

**Comment by mit-mit** [comment]
Yes, please, https://github.com/dart-lang/pub/issues/2426 is a bad issue that I found while testing the content for the 2.8 blog post.

**Comment by athomas** [comment]
I've merged this to beta in [2.8.0-dev.20.7](https://github.com/dart-lang/sdk/commit/1e81d677f731f6ea58786e20b4ec3e809aab8366).
