### ISSUE TITLE
Please merge #795c0b1 into dev/beta channel

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#41326]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/795c0b1b64ce563e8924e0d0b7ed0bde98c1cef3

**merge instructions**: clean merge

**reason**:  The CFE landed a bug fix to ignore "implements Function" (to comply with the Dart 2 spec), the fix implied some breaking changes and revealed a bug in the `js_util` library. The commits above fixes the bug in the API. Context: https://github.com/dart-lang/sdk/issues/41259

Note: we separately want to make another change to add a breaking change line in the CHANGELOG referring to the original CFE bug fix. When that's ready, I'll file a separate cherry-pick as well.

Question: are we now requesting merges to dev or beta?

/cc @vsmenon @kevmoo @mit-mit @whesse @athomas

**Comment by athomas** [comment]
We should now request merges to beta. The dev channel will not receive
cherry-picks under normal circumstances.

**Comment by franklinyow** [comment]
Removed merge-to-bet label, the original issue should have the merge label following the cherrypick process

**Comment by kevmoo** [comment]
Should this issue just be deleted now? What's the purpose?

**Comment by sigmundch** [comment]
Mmmm- might be worth syncing up later about processes - when I read the updated steps, it wasn't clear to me that the label would go on the original bug. I understood it as "every request should have a bug" and in this case I created one because the original had a lot of noise and would be hard to see what was being requested.

Until we get a chance to chat, if you don't mind I'll readd the label so we don't miss this merge request for 2.8

**Comment by sigmundch** [comment]
Update for the changelog just sent out for review as well: https://dart-review.googlesource.com/c/sdk/+/143332

I'll update the list of commits above once once it lands

**Comment by athomas** [comment]
I will merge 7baa21d97a3d07c5837cdac79bf406f36b878279 as well (only a changelog change, so that's harmless).

**Comment by athomas** [comment]
I've merged this to beta in [2.8.0-dev.20.7](https://github.com/dart-lang/sdk/commit/1e81d677f731f6ea58786e20b4ec3e809aab8366).
