### ISSUE TITLE
NNBD: Analyzer does not throw error for Future<T>(() => null) when T is non-nullable type

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41339]
Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"

The following source code example throws a compile error for the line 4 and does not throw error for the line 5:
``` dart
import "dart:async";

main() {
  Future<int>(() => "");
  Future<int>(() => null);
}
```
Seems like error should be thrown for the line 5 too.

Sample output is:
> $> dartanalyzer --enable-experiment=non-nullable test.dart 
> Analyzing test.dart...
>   error - The return type 'String' isn't a 'FutureOr<int*>*', as required by the closure's context. - test.dart:4:21 - return_of_invalid_type_from_closure
> 1 error found.

**Comment by a-siva** [comment]
with the NNBD sdk this example of yours works fine. This issue will get fixed when the unfork CL https://dart-review.googlesource.com/c/sdk/+/138902 lands.
