### ISSUE TITLE
[dart2js] lib_2/html/js_interop_constructor_name/error2_test Crash (expected Pass)

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#41330]
There are new test failures on [[dart2js] createFromStaticType for LegacyType](https://dart-review.googlesource.com/c/sdk/+/141960).

The test
```
lib_2/html/js_interop_constructor_name/error2_test Crash (expected Pass)
```
is failing on configuration
```
dart2js-hostasserts-weak-linux-x64-chrome
```

```
org-dartlang-sdk:///sdk_nnbd/lib/_internal/js_runtime/lib/interceptors.dart@15497+1:
Internal Error: Cannot create subclass type mask for uninstantiated class j:class(JavaScriptObject).
```

This appears to be an 'impacts' inconsistency.
Prior to the change no calls were generated to `getNativeInterceptor`.
After the change, `getInterceptor` calls called `getNativeInterceptor`.

**Comment by sigmundch** [comment]
@joshualitt or @fishythefish - could one of you take a look?

It appears this failure is a new regression in weak mode.

Here is an example stack trace from the bots:
https://dart-ci.appspot.com/log/dart2js-nnbd-linux-x64-chrome/dart2js-hostasserts-weak-linux-x64-chrome/1164/lib_2/html/js_interop_constructor_name/error2_test

**Comment by franklinyow** [comment]
Please update if this is a blocker for the unfork.  Thanks!

**Comment by fishythefish** [comment]
Is @rakudrama already investigating? If not, I can try poking at it.

**Comment by sigmundch** [comment]
Go for it, thanks!

**Comment by franklinyow** [comment]
Any update?

**Comment by fishythefish** [comment]
Still investigating. I've been juggling multiple bugs this week and haven't gotten around to all of them yet.

**Comment by sigmundch** [comment]
@fishythefish one question we have: is this affecting only weak mode or also the legacy+unforked mode? If only the former is affected, we could consider this a non-blocker.

**Comment by fishythefish** [comment]
Unfortunately, this does affect legacy+unforked as well. I've narrowed down the root cause, working on a fix today.
