### ISSUE TITLE
Please merge 05e43cff921c23cdf52558538ecf84d8091d3cdb into beta channels

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#41332]
**commit(s) to merge**: 05e43cff921c23cdf52558538ecf84d8091d3cdb

**merge instructions**: clean merge

**reason**: Reverted change was breaking Brew installations of the Dart SDK on MacOS. See https://github.com/dart-lang/sdk/issues/41329

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by kevmoo** [comment]
FYI the dev channel is broken now, so I'd love to have this in the dev channel AND beta channel

**Comment by franklinyow** [comment]
This should also merge to beta branch.

**Comment by franklinyow** [comment]
Removed Merge-to-beta and Merge-to-dev labels.  The label should applied to the original bug #41329

**Comment by athomas** [comment]
Merged this to beta in [2.8.0-dev.20.7](https://github.com/dart-lang/sdk/commit/1e81d677f731f6ea58786e20b4ec3e809aab8366) even though there is a newer fix on master (to ensure that beta isn't broken on HEAD).
