### ISSUE TITLE
Regex expression does not work the same as in Javascript

### ISSUE THREAD

**Issue by DziugasMolis** [dart-lang/sdk#41342]
I have regex expression:
**/^$|(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?|^((http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(:[0-9]{1,5})?(\/.*)?$/**

When I pass a string **http://192.168.1.22/login** it returns that it does not have any matches, while using the same regex for example in regex101: https://regex101.com/r/Kwn9Kq/1 it has the match.

It seems like it is a bug or am I missing something?

This tracker is for issues related to:
* Dart VM

* Dart SDK Version 3.9
* Windows
* Flutter Android app

**Comment by mraleph** [comment]
Could you provide more information, because when I test this:

```dart
void main() {
  final re = RegExp(r'^$|(http://www.|https://www.|http://|https://)?[a-z0-9]+([-.]{1}[a-z0-9]+).[a-z]{2,5}(:[0-9]{1,5})?(/.)?|^((http://www.|https://www.|http://|https://)?([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(:[0-9]{1,5})?(/.*)?$');
  print(re.allMatches('http://192.168.1.22/login'));
}
```

it seems to work just fine.

```console
$ dart --version
Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"
$ dart /tmp/test.dart
(Instance of '_RegExpMatch')
```

Please provide the code that does not work and information about the environment you are running it in (e.g. if you use `dart` on the command line then provide output of the `--version`, if you use it in Flutter please provide output of the `flutter doctor -v`).

**Comment by DziugasMolis** [comment]
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (6 days ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.720], locale lt-LT)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[!] Android Studio (version 3.6)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.43.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.


Code which does not work: 


String validateURL(String value) {
    RegExp regex = new RegExp(
        r"/^$|(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?|^((http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(:[0-9]{1,5})?(\/.*)?$/");

    if (value.length == 0) {
      return 'URL can not be empty';
    } else if (!regex.hasMatch(value)) {
      return 'Enter Valid URL';
    }return null;
}

**Comment by mraleph** [comment]
> Code which does not work: 

Note that you have redundant `/` around your regexp. Remove them and things would start working. These `/` are not part of the regular expression itself - they are like quotes wrapping regular expression - so you should not include them when passing regular expression to `RegExp` constructor.

**Comment by kechankrisna** [comment]
Here is my sample code i wrote in flutter
```
final re =  new RegExp(r"(?<=\()(.*)(?=\))");
String str = " Hello (world)";
print( str.replaceAll(re, "").replaceAll("()", "") ); 
```
I tested it in dart-pad, either chrome, firefox, and safari . Here the result:
- Chrome: Hello
- Safari: Script error.
- Firefox: Error: Error: FormatException: Illegal RegExp pattern (SyntaxError: invalid regexp group)
(?<=\()(.*)(?=\))

**Comment by mraleph** [comment]
@kechankrisna This is completely unrelated to this issue. Firefox and Safari simply don't support _lookbehind assertions_ (see https://caniuse.com/#feat=js-regexp-lookbehind). Firefox implementation bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1225665, WebKit implementation bug: https://bugs.webkit.org/show_bug.cgi?id=174931

Dart RegExp falls back to JavaScript regexp in the browser - so you can only use those features that are supported by the browsers.

**Comment by DziugasMolis** [comment]
> > Code which does not work:
> 
> Note that you have redundant `/` around your regexp. Remove them and things would start working. These `/` are not part of the regular expression itself - they are like quotes wrapping regular expression - so you should not include them when passing regular expression to `RegExp` constructor.

Thanks for help. After removing it, regex started working.
