### ISSUE TITLE
NNBD. Extension for nulable type must be taken into account on CFE

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41349]
Now, the code below works in Analyzer but fails on CFE
```dart
extension on int? {
  bool get isEven => this?.isEven ?? true;
}

void main() {
  int? i = null;
  i.isEven; // Ok in Analyzer, in VM Error: Property 'isEven' cannot be accessed on 'int?' because it is potentially null.
}

```
Expected result. No error. `i.isEven` must return `true` as defined by extension
`Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"`

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/761#issuecomment-580025312.

**Comment by leafpetersen** [comment]
I think the behavior here is covered by the spec: https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#extension-method-resolution .  Let me know if I've missed something in the writeup.

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/144761
