### ISSUE TITLE
Add @mustOverride annotation

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#41347]
It some cases it would be useful to have an annotation that tells subclasses that they need to override a method even if it is already implemented in the parent `abstract` class. For example:

```dart
abstract class Baz {
  @mustOverride
  @mustCallSuper
  Context setup(Context context) {
    assert(context != null);
    return null;
  }
}
```

---

This was already proposed by @Hixie [as a comment](https://github.com/dart-lang/sdk/issues/28250#issuecomment-270523406) in #28250. I think that there should be a dedicated issue for this because Hixie's request is hard to find and only the comment received upvotes on that issue.

**Comment by srawlins** [comment]
Looks like a duplicate of https://github.com/dart-lang/sdk/issues/30175

**Comment by creativecreatorormaybenot** [comment]
@srawlins Thanks.
