### ISSUE TITLE
Support for rawmode or window resize in terminal

### ISSUE THREAD

**Issue by erf** [dart-lang/sdk#41344]
Hi, 

I'm interested in command line apps, and i'm wondering if you have any plans to support "rawmode" or terminal resize events in core libraries, for more interactive command line apps?

**Comment by mraleph** [comment]
Terminal resize (at least on non-Windows systems) can be detected by listening to `SIGWINCH` signal, which we already support. I don't know if there is a very reliable way to detect it on Windows though (IIRC not really).

You can enter raw mode by setting `lineMode` and `echoMode` to `false` on `stdin`. 

I recommend checking out [`console` package](https://pub.dev/packages/console) - it already has a lot of necessary primitives for writing TUI for command line apps.

**Comment by erf** [comment]
@mraleph how do you support `SIGWINCH` ? can i subscribe to a callback for window resize events? Thanks, i did not know you could enter raw mode without ffi in dart core libs. I know there are some libraries, but they usually are very complex and do some ffi calls so im just curious if you would support this via dart core.

These two libraries are also very interesting:
https://github.com/timsneath/dart_console
https://github.com/timsneath/win32

**Comment by erf** [comment]
I figured out `SIGWINCH`:
```
ProcessSignal.sigwinch.watch()
```
