### ISSUE TITLE
PROPOSAL to cache imported modules

### ISSUE THREAD

**Issue by cindRoberta** [dart-lang/sdk#41351]
Dart currently import from http, but not cache the module

My proposal inspired on https://deno.land:

you don't need to eliminate pubspec.yaml, you can mantain the 2

______________________________________________________________

Dart already do:

```dart
// main.dart
import "https://gist.githubusercontent.com/mraleph/7f937d8545f247f98de78e323cdbc3f1/raw/4165c1202b5882558952ea1894de5528ece3b41c/test.dart";

void main()=> sayHello();
```

___________________________________________________________________________

to cache fragmenteded on .pub-cache, you could do like this:

```dart
// main.dart
import ".pub-cache/${SOURCEFRAGMENTED}/testrenamed.dart" source "https://gist.githubusercontent.com/mraleph/7f937d8545f247f98de78e323cdbc3f1/raw/4165c1202b5882558952ea1894de5528ece3b41c/test.dart";

void main()=> sayHello();
```

this would be cached on .pub-cache/https/gist.githubusercontent.com/mraleph/7f937d8545f247f98de78e323cdbc3f1/raw/4165c1202b5882558952ea1894de5528ece3b41c/testrenamed.dart

___________________________________________________________________________

to cache on a folder inside .pub-cache, you could do like this:

```dart
// main.dart
import ".pub-cache/module/version/testrenamed.dart" source "https://gist.githubusercontent.com/mraleph/7f937d8545f247f98de78e323cdbc3f/raw/4165c1202b5882558952ea1894de5528ece3b41c/test.dart";

void main()=> sayHello();
```

this would be cached on .pub-cache/module/version/testrenamed.dart

___________________________________________________________________________

to cache fragmenteded in other folder out of .pub-cache, would be:

```dart
// main.dart
import "/home/user/folder/${SOURCEFRAGMENTED}/testrenamed.dart" source "https://gist.githubusercontent.com/mraleph/7f937d8545f247f98de78e323cdbc3f1/raw/4165c1202b5882558952ea1894de5528ece3b41c/test.dart";

void main()=> sayHello();
```

this would be cached on /home/user/folder/https/gist.githubusercontent.com/mraleph/7f937d8545f247f98de78e323cdbc3f1/raw/4165c1202b5882558952ea1894de5528ece3b41c/testrenamed.dart

___________________________________________________________________________

to cache in other folder out of .pub-cache, would be:

```dart
// main.dart
import "/home/user/folder/module/version/testrenamed.dart" source "https://gist.githubusercontent.com/mraleph/7f937d8545f247f98de78e323cdbc3f1/raw/4165c1202b5882558952ea1894de5528ece3b41c/test.dart";

void main()=> sayHello();
```

this would be cached on /home/user/folder/module/version/testrenamed.dart

___________________________________________________________________________

$ dart main.dart

only would download for test.dart if it didn't exist in the local path on import

it would create the path if not exists

___________________________________________________________________________

for: to apply diff between the local and remote files -> to download and to overwrite on cache, would be:

$ dart --recache main.dart

**Comment by a-siva** [comment]
It is unclear from your description above as to what exactly you are proposing, can you make a small write up describing the enhancement you are proposing and what use case/problem it solves.

**Comment by cindRoberta** [comment]
> It is unclear from your description above as to what exactly you are proposing, can you make a small write up describing the enhancement you are proposing and what use case/problem it solves.

@a-siva ok, let's go

nowadays to use `@required` in Dart I need:

1: create a pubspec.yaml

```yaml
name: "myproject"

dependencies:
  meta: ^1.1.8
```

2: create the main.dart

```dart
import "package:meta/meta.dart";
```

2 files, 4 lines

________________________________________

would be:

```dart
import ".pubcache/${SOURCEFRAGMENTED}/meta.dart" source "https://github.com/dart-lang/sdk/tree/master/pkg/meta/lib/meta.dart";
```

or

```dart
import ".pubcache/modules/meta/1.1.8/meta.dart" source "https://github.com/dart-lang/sdk/tree/master/pkg/meta/lib/meta.dart";
```

1 file, 1 line, 2 options

**Comment by vsmenon** [comment]
Issue moved to [dart-lang/language #919](https://github.com/dart-lang/language/issues/919) via [**ZenHub**](https://www.zenhub.com/)
