### ISSUE TITLE
Issues building SDK on Windows

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#41356]
I tried compiling the SDK this weekend on Windows. I followed the directions [here](https://github.com/dart-lang/sdk/wiki/Building#windows)

I was able to set up the depot tools correctly (I think).

However, I was getting errors when attempting to build the sdk with:
`.\tools\build.py --mode release --nnbd --arch x64  create_sdk`

Eventually, I got to a point where I was getting this error:

```
Exception: Visual Studio Version 2017 (from GYP_MSVS_VERSION) not found.
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
```

So, I edited `vs_toolchain.py` and made the following change (commented out 2017 line):

```python
# VS versions are listed in descending order of priority (highest first).
MSVS_VERSIONS = collections.OrderedDict([
    # ('2017', '15.0'),
    ('2019', '16.0'),
])
```

I have VS 2019 community, not 2017.

After I made the above edit, and re-issued the build command, it seemed to build ok.

One other issue that tripped me up for quite a while, is there is an `--executable` flag mentioned in the wiki entry. I was getting an error that that flag does not exist, and I don't see it in `build.py`.

> Your Visual Studio executable command may have a different name from the standard Visual Studio installations. You can specify the name for that executable by passing the additional flag "--executable=$VS_EXECUTABLE_NAME" to build.py. The executable name will probably be something like "VSExpress.exe".

I'm not 100%, but I couldn't find a `VSExpress.exe` on my machine. I did find `devenv.exe`. Anyway, it may be a moot point if that flag is no longer required.

**Comment by slightfoot** [comment]
Just got caught out by this one. Thanks @mnordine for the workaround.
