### ISSUE TITLE
Analyzer: implementation for spec change to GLB

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41363]
A specification change to the lower bound computation landed [here](https://github.com/dart-lang/language/pull/903) , with new tests [here](https://dart-review.googlesource.com/c/sdk/+/141841).

Note the behavior specified here is already implement in the analyzer lower bound computation for inference as a special case.  This change eliminates the special case in favor of a uniform approach both during inference and in normal lower bound computations.

cc @scheglov @lrhn @eernstg @munificent @stereotype441 @stefantsov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/141846
