### ISSUE TITLE
Failures on Migrate language_2/constants_2018 to NNBD....Update language/constructor/return_test

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#41367]
There are new test failures on [Migrate language_2/constants_2018 to NNBD....Update language/constructor/return_test](https://github.com/dart-lang/sdk/compare/4558607b052e7bdb3d18e726e821ee975c48118f~...8f85a9efe412d3a671ee87b3a7ccdbb37459935c).

The tests
```
language/constants_2018/constant_types_test/02 Pass (expected CompileTimeError)
```
are failing on configurations
```
analyzer-asserts-strong-linux
analyzer-asserts-weak-linux
cfe-strong-linux
cfe-weak-linux
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
dartkp-strong-linux-release-x64
dartkp-weak-asserts-linux-release-x64
```

\cc @munificent

**Comment by munificent** [comment]
This started failing because of https://dart-review.googlesource.com/c/sdk/+/142568. I believe the changes to the test are correct and the failures now indicate that some implementations are missing the correct behavior.

**Comment by alexmarkov** [comment]
This test is now passing on all of the configurations listed above.
