### ISSUE TITLE
a little bit problem here. I cant run this.

### ISSUE THREAD

**Issue by hosainanwar** [dart-lang/sdk#41368]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

**Comment by a-siva** [comment]
It is unclear from the description what kind of problem you ran into. Could you reopen the issue if there is a real problem.
