### ISSUE TITLE
[linux] pub global activateis not work

### ISSUE THREAD

**Issue by godot0413301** [dart-lang/sdk#41364]
```bash
flutter@flutter-System-Product-Name:~$aqueduct
aqueduct：未找到命令
```
I input ```pub global activate aqueduct``` and input ```aqueduct``` do not work,I see this is no dir "$HOME/.pub-cache/bin" in "$HOME/.pub-cache"
but in project,run ```pub run  aqueduct``` is work

My os is ubuntu1804, the ~/.profile is like this
```bash
export PATH="$PATH:/home/flutter/development/flutter/bin"
export PATH="$PATH:/home/flutter/development/flutter/bin/cache/dart-sdk/bin"
export PUB_HOSTED_URL=https://mirrors.tuna.tsinghua.edu.cn/dart-pub
export FLUTTER_STORAGE_BASE_URL=https://mirrors.tuna.tsinghua.edu.cn/flutter
```
This tracker is for issues related to:

Dart VM

Flutter: https://github.com/flutter/flutter

 Dart SDK Version (`dart --version`):
Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "linux_x64"
I am using ubuntu18.04lts

**Comment by a-siva** [comment]
Issue moved to [dart-lang/pub #2440](https://github.com/dart-lang/pub/issues/2440) via [**ZenHub**](https://www.zenhub.com/)
