### ISSUE TITLE
Missing check on sufficiency of bounds in generic local function

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41372]
Consider the following program:

```dart
class C<X extends int> {}

void main() {
  void f<X extends num>(C<X> Function() g) {}
  f(() => throw 1);
}
```

Using `dart` from a31781f737db20becfa97e27d1602fb53a47fbce (of Apr 7), the above program executes without compile-time or run-time errors.

However, the bound on `X` of `f` does not ensure that `C<X>` is a well-bounded type.

This depends on the location of the declaration of `f`: If it is moved to the top level then the check is performed, and the program is rejected with a compile-time error.

**Comment by stefantsov** [comment]
This seems to be fixed some time ago.  This is what I see on the current HEAD:

```
$ xcodebuild/ReleaseX64/dart /tmp/asdf.dart
/tmp/asdf.dart:4:41: Error: Type argument 'X' doesn't conform to the bound 'int' of the type variable 'X' on 'C'.
Try changing type arguments so that they conform to the bounds.
  void f<X extends num>(C<X> Function() g) {}
                                        ^
/tmp/asdf.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
class C<X extends int> {}
        ^
```
