### ISSUE TITLE
Allow `dynamic` and other nullable types in catch clauses

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#41378]
If I analyze this opted-in library:

```dart
main() {
  try {
    throw "ok";
  } on dynamic catch (error) {
    print(error);
  }
}
```

I get:

```
$ dartanalyzer --enable-experiment=non-nullable temp.dart
Analyzing temp.dart...
  error • A nullable type can't be used in an 'on' clause because it isn't valid to throw 'null'. • temp.dart:4:8 • nullable_type_in_catch_clause
1 error found.
```

From the discussion [here](https://github.com/dart-lang/language/issues/916), this should be allowed.

**Comment by munificent** [comment]
cc @stereotype441 @leafpetersen

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/143220

**Comment by scheglov** [comment]
Analyzer was updated to report errors when throwing expressions with types not assignable to `Object`.
The catch error was downgraded to a hint.
