### ISSUE TITLE
Migration: add a button to create a "/*late*/" hint

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41389]
Probably we should highlight the space right before a variable declaration in gray (and add a space if one isn't present), so the user has a good click target to add the hint.

**Comment by srawlins** [comment]
I've encountered a field or two that I'd like to mark late. :)

**Comment by stereotype441** [comment]
@tvolkert made a similar suggestion recently.

**Comment by michalt** [comment]
I've also run into this more than once. :)
