### ISSUE TITLE
Failures on [tests] Remove more deprecated List constructor usage in tests...Fix LinterContext().canBeConst() - compute dependencies.

### ISSUE THREAD

**Issue by ZichangG** [dart-lang/sdk#41382]
There are new test failures on [[tests] Remove more deprecated List constructor usage in tests...Fix LinterContext().canBeConst() - compute dependencies.](https://github.com/dart-lang/sdk/compare/91b581fb2c8568cb429380292bfbda9c7f55d9b7~...ed086f0f95122662a8bc761b2f10c4f230edcc64).

The tests
```
vm/dart/splay_test/13 CompileTimeError (expected Pass)
vm/dart/splay_test/14 CompileTimeError (expected Pass)
vm/dart/splay_test/15 CompileTimeError (expected Pass)
vm/dart/splay_test/16 CompileTimeError (expected Pass)
```
are failing on configurations
```
dartkp-asan-linux-release-x64
dartkp-msan-linux-release-x64
dartkp-tsan-linux-release-x64
```

`
Error: SDK summary not found: out/ReleaseTSANX64/vm_platform_strong.dill.
Error: Error when reading 'out/ReleaseTSANX64/vm_platform_strong.dill': No such file or directory
Error: Error when reading 'out/ReleaseTSANX64/vm_platform_strong.dill': No such file or directory
`

Logs: 
https://dart-ci.appspot.com/log/vm-kernel-precomp-tsan-linux-release-x64/dartkp-tsan-linux-release-x64/16/vm/dart/splay_test/13
https://dart-ci.appspot.com/log/vm-kernel-precomp-msan-linux-release-x64/dartkp-msan-linux-release-x64/16/vm/dart/splay_test/13
https://dart-ci.appspot.com/log/vm-kernel-precomp-asan-linux-release-x64/dartkp-asan-linux-release-x64/16/vm/dart/splay_test/13

bots are building with `ninja -C out/ReleaseASANX64 -j200 -l64 runtime_precompiled`.
Is it supposed to also pass `create_sdk` flag?

@rmacnak-google @athomas  Do you have any idea?

**Comment by rmacnak-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/142804
