### ISSUE TITLE
Migration tool should cast to non-nullable types rather than casting and then adding a null check

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41397]
When attempting to use the migration tool to migrate package csslib, line 469 of lib/src/analyzer.dart was migrated from:
```dart
var rulesetDirect = currDef as MixinRulesetDirective;
```
to:
```dart
var rulesetDirect = (currDef as MixinRulesetDirective?)!;
```
This is silly.  Rather than cast to a nullable type and then null check, we should just cast to a non-nullable type.

**Comment by a14n** [comment]
It still happens with the following repro:

```
void repro(){
  List<dynamic> l = <dynamic>[];
  for(final dynamic e in l) {
    final List<String> a = (e['query'] as String).split('&');
  }
}
```

suggests:

```
void repro(){
  List<dynamic>  l = <dynamic>[];
  for(final dynamic e in l) {
    final List<String >  a = (e['query'] as String?)!.split('&');
  }
}
```

(Tools • Dart 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b))

**Comment by stereotype441** [comment]
https://dart-review.googlesource.com/c/sdk/+/150540 adds @a14n's repro as a test case.

**Comment by srawlins** [comment]
@MichaelRFairhurst fixed this in https://github.com/dart-lang/sdk/commit/e11eb2cd0834804a9a4f3f09f7868f531ff470db
