### ISSUE TITLE
In migration tool, pane size jumps around, making it difficult to keep context

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41404]
When attempting to migrate package csslib, if I navigate to lib/src/analyzer.dart and click on the proposed edit for line 199, the right hand pane is wide, showing one line per proposed edit.  If I then click on the proposed edit for line 237, the right hand pane is narrow, showing two lines per proposed edit.  This makes it difficult to keep track of where I am in the file.

(Note that the manifestation of this bug may be window size dependent).

**Comment by srawlins** [comment]
Clicking on the proposed edit on line 199 puts text in the side panel like "ExpandNestedSelectors.visitDeclarationGroup.selectorGroup" which doesn't wrap, so the panel gets expanded compared to the center panel.

We solve this in the navigation panel by inserting zero-width spaces after `/` characters; I think it would be fine to do the same for `.` characters in that panel.
