### ISSUE TITLE
Support --enable-experiment flag on pub/pub.bat scripts

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41403]

**Comment by kevmoo** [comment]
CC @natebosch @jakemac53

**Comment by natebosch** [comment]
The idea here is that we'd support a minimal amount of arg parsing in the script so that `pub --enable-experiment=non-nullable run` gets turned into VM argument correctly.

**Comment by kevmoo** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/41355 – since it waas first!
