### ISSUE TITLE
language/closure/param_null_to_object_test is failing in NNBD strong mode

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#41415]
language/closure/param_null_to_object_test is failing in strong mode, and it seems to be a front end issue. The runtime type of `int Function(Null)` is `int Function(Object?)`, and in strong mode this is also supposed to happen for `int Function(Never)` but that part isn't working:
https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-debug-x64/dartk-strong-linux-debug-x64/1064/language/closure/param_null_to_object_test

**Comment by nshahan** [comment]
I'm seeing the same problem in DDC.

**Comment by johnniwinther** [comment]
The test has these declarations:
```Dart
  // Pre-NNBD bottom type.
  int Function(Null) f = (x) => 1; // Runtime type is int Function(Object?)
  ...
  // NNBD bottom type.
  int Function(Never) g = (x) => 1; // Runtime type is int Function(Object?)
  ...
  int Function(String) h = (x) => 1; // Runtime type is int Function(String)
```

@leafpetersen: I don't see this in the rule for function literal type parameter inference in https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#function-literal-return-type-inference : 
```
Each parameter is
assumed to have its declared type if present, or the type taken from the
corresponding parameter (if any) from the typing context if not present.
```

And what should we infer in this case:
```Dart
  int Function(Never?) g = (x) => 1;
```

**Comment by nshahan** [comment]
Related discussion here: https://github.com/dart-lang/language/issues/910

**Comment by liamappelbe** [comment]
language/covariant/subtyping_test is also failing for a similar looking reason: https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-debug-x64/dartk-strong-linux-debug-x64/1064/language/covariant/subtyping_test

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/143812

**Comment by liamappelbe** [comment]
The param_num_to_object_test is now passing, but the subtyping_test is still failing, so it must be a different problem. I filed a separate issue for it: https://github.com/dart-lang/sdk/issues/41697
