### ISSUE TITLE
Could not find a file named "pubspec.yaml" error when running dart tests.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#41416]
Could not find a file named "pubspec.yaml" in "/Users/thinkdigital/IdeaProjects/zoom_sdk_dart/null/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-2.1.0".

I was running tests in my dart package and restarted and it wouldn't finish initializing, so I stopped the tests, ran flutter clean, pub get, and run again and I continuously get this error.

What stands out to me is the null in the path.

> Dart VM version: 2.8.0-dev.20.0.flutter-e736495eb7 (be) (Fri Apr 3 00:56:36 2020 +0000) on "macos_x64"

**Comment by vsmenon** [comment]
What's you exact set of steps?  If you are using flutter, you should be using `flutter pub get` not `pub get`:

https://flutter.dev/docs/development/tools/sdk/upgrading#upgrading-packages-only

Flutter sets the .pub_cache a bit differently.

**Comment by ThinkDigitalSoftware** [comment]
Which steps? And this was a pure Dart package. However, I ran both get commands to no avail

On Apr 9, 2020 6:22 AM, vsmenon <notifications@github.com> wrote:

What's you exact set of steps? If you are using flutter, you should be using flutter pub get not pub get:

https://flutter.dev/docs/development/tools/sdk/upgrading#upgrading-packages-only

Flutter sets the .pub_cache a bit differently.

**Comment by mraleph** [comment]
Delete `/Users/thinkdigital/IdeaProjects/zoom_sdk_dart/null/.pub-cache` - it seems to be corrupted. Then run `pub get` again, things should work.

**Comment by ThinkDigitalSoftware** [comment]
No such folder existed, I checked

On Apr 9, 2020 9:25 AM, Vyacheslav Egorov <notifications@github.com> wrote:

Delete /Users/thinkdigital/IdeaProjects/zoom_sdk_dart/null/.pub-cache - it seems to be corrupted. Then run pub get again, things should work.

**Comment by vsmenon** [comment]
Not sure why your `.pub_cache` is pointing to that path.  A normal Dart install would add that to your home directory:

https://dart.dev/tools/pub/environment-variables

Are you setting the PUB_CACHE variable?

**Comment by ThinkDigitalSoftware** [comment]
No, I haven't set that variable manually. And, mind you, this is after a "Restart Debug Session" button press, not a configuration change

**Comment by mraleph** [comment]
Unfortunately I don't think we really have enough information to diagnose this issue.

The best recommentation we can give you is to search through your project file and IDE configuration trying to figure out where this path comes from.
