### ISSUE TITLE
Potential breaking changes in sdk_nnbd/lib/_http/http.dart

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41429]
HttpClentResponse and others seem to have come in as part of the migration effort, see CLs below

https://dart-review.googlesource.com/c/sdk/+/126649
https://dart-review.googlesource.com/c/sdk/+/140103

Full discussion on the issue here:
[https://groups.google.com/a/google.com/g/dart-platform-scrum/c/QzaExmp1VRI/m/FC-FBpkEBQAJ](https://groups.google.com/a/google.com/g/dart-platform-scrum/c/QzaExmp1VRI/m/FC-FBpkEBQAJ)

**Comment by leafpetersen** [comment]
This is currently blocked on https://github.com/dart-lang/sdk/issues/41436 .

**Comment by franklinyow** [comment]
Siva mentioned he has a work around in the discussion.
Is this something that will block the unfork?

**Comment by leafpetersen** [comment]
> Siva mentioned he has a work around in the discussion.
> Is this something that will block the unfork?

It's a breaking change.  The fix from @a-siva I believe fixes the breakage in Flutter, but there still can be arbitrary unknown breakage elsewhere.  If we want to ship it as a breaking change, we should go through the breaking change process.  To me though, this doesn't feel like a *necessary* breaking change.  I may be missing something, but so far working through the changes I think there are perfectly fine non-breaking alternatives.  I'll have a CL ready for comment soon.

**Comment by leafpetersen** [comment]
Still blocked.

**Comment by leafpetersen** [comment]
This is still blocked on the spurious errors above.

**Comment by leafpetersen** [comment]
I sent the CL out for [review](https://dart-review.googlesource.com/c/sdk/+/143184) since @lrhn should be back shortly.  It can't land until the CFE issues are resolved however.

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/143184 has landed, this should be fixed.
