### ISSUE TITLE
dart2js test failure on unfork cl

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41428]
Tracking all failure from the unfork CL 
[https://dart-review.googlesource.com/c/sdk/+/138902](https://dart-review.googlesource.com/c/sdk/+/138902)

**Comment by joshualitt** [comment]
fix for one test landed, fix for another is up for review. Currently looking at a regression on the production bot.

**Comment by joshualitt** [comment]
all non-unit-test failures have been triaged, and fixes are underway for many. The two remaining issues are:
dart2js-production-linux-d8:dart2js_extra/dummy_compiler_test
dart2js_extra/rti/variance_subtype_test

variance_subtype_test is an experiment we will probably ignore for the time being. The dummy_compiler_test is crashing on TOT, so we will have to decide exactly what we want to do there.

In addition, we have 30-40 unit test failures. I am starting to triage them now.

**Comment by vsmenon** [comment]
Thanks!  Yes, I think we can ignore non-nnbd experiment tests for unforking.

**Comment by joshualitt** [comment]
Still triaging unit test failures, they are a very different style of test from the language level tests so there is some bringup effort. No change in the number of failures.

**Comment by joshualitt** [comment]
Did a high level triage with @fishythefish and fixed a test. Investigating a few tests that may just need expectations rebased.

**Comment by joshualitt** [comment]
Create a rebase cl which would fix 6 tests. Triaging of the tricky tests continues.

**Comment by joshualitt** [comment]
Pivoting to try and fork these remaining tests so that we can both reduce churn on the unfork cl, and give better insight into the remaining workload. This will also set us up well for nnbd strong mode, where we will need to continue running unit tests in legacy mode.

**Comment by joshualitt** [comment]
Okay, still working on adding nnbd unittests to our trybots. I have a cl, but there is probably going to be back and forth. I suspect another few days on this, and then I can start burning down the unit tests again. I don't have a great estimate for how long it will take to fix all of the unit tests, but I wouldn't be surprised if there is still a few weeks left of work there.

**Comment by vsmenon** [comment]
Thanks!  Do you have a list of the breaking tests?

Have the recent fixes been addressing bugs in dart2js itself or configuration issues (e.g., flags, expectations)?

**Comment by sigmundch** [comment]
@vsmenon - there are about 40 unit tests in dart2js that are failing. We were covering language/corelib/lib/co19 suites in the nnbd bots, but not the low level unit tests.

Part of the challenge here is that each test is unique and making them work with NNBD requires either some refactoring or porting of individual tests. Joshua is working on making that possible so we can more easily triage, whitelist, or fix each failure

From a recent run, the list includes these tests:
```
dart2js/analyses/api_dynamic_test
dart2js/codegen/array_static_intercept_test
dart2js/codegen/equals_test
dart2js/codegen/gvn_test
dart2js/codegen/model_test
dart2js/codegen/strength_eq_test
dart2js/codegen/variance_subtype_cast_test
dart2js/deferred_loading/deferred_loading_test
dart2js/field_analysis/jfield_analysis_test
dart2js/generic_methods/function_type_variable_test
dart2js/impact/impact_test
dart2js/inference/inference0_test
dart2js/inference/inference2_test
dart2js/inference/inference3_test
dart2js/inference/trivial_abstract_value_domain_test
dart2js/inlining/inlining_test
dart2js/model/cfe_annotations_test
dart2js/model/cfe_constant_evaluation_test
dart2js/model/cfe_constant_swarm_test
dart2js/model/cfe_constant_test
dart2js/model/future_or_test
dart2js/model/mixin_typevariable_test
dart2js/model/no_such_method_forwarders_test
dart2js/model/strong_mode_impact_test
dart2js/model/subtype_test
dart2js/model/type_substitution_test
dart2js/rti/rti_emission_test
dart2js/rti/rti_need0_test
dart2js/rti/rti_need1_test
dart2js/rti/type_representation_test
dart2js/serialization/in_memory_split_test
dart2js/serialization/on_disk_split_test
dart2js/sourcemaps/stepping_test
```

There may be a couple more, we should be able to update the list soon. All failures except the api_dynamic_test require more in depth review and triage.

**Comment by vsmenon** [comment]
Any updates here?  Is there anything you all consider blocking?

**Comment by sigmundch** [comment]
Lots of progress rebasing and updating tests.  @joshualitt has been actively pushing forward here, @fishythefish just joined him on the effort. I'll get an updated list later today.

**Comment by franklinyow** [comment]
Is this done?

**Comment by sigmundch** [comment]
I believe so.
