### ISSUE TITLE
dart2js unfork performance regression

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41432]
This issue track dart2js performance regression.
Unfork performance should meet performance metric

**Comment by rakudrama** [comment]
Spec mode aggregate: -8.76%

Production mode aggregate: -4.62%
Concerns:
 - extra casts in SplayTree
 - Future / Stream slower by 50% (undiagnosed)

**Comment by vsmenon** [comment]
Any updates here?

**Comment by rakudrama** [comment]
@leafpetersen has a CL that addresses most of the SplayTree regression.

**Comment by leafpetersen** [comment]
The CL that ported dart:async is [here](https://dart-review.googlesource.com/c/sdk/+/122786) .  I see some new casts in there, and some uses of late (which may not be well-optimized yet).  Some of the new casts are of the `T?` -> `T` variety that we can rewrite to a different pattern.  Others can probably be turned back into implicit casts if needed by casting through dynamic.  It would be good to have something slightly more targeted - do we have benchmarks for Future/Stream that we're targetting.

**Comment by rakudrama** [comment]
@leafpetersen AsyncStressTest is a group of benchmarks that are currently ~2x slower. They tend to be noisy but the run-by-run bar graphs can be used to judge that.

**Comment by rakudrama** [comment]
Spec mode aggregate: -8.55%
Production mode aggregate: -4.43%

Currently investigating if the use of more lazy initializers is responsible for some of the regressions.

**Comment by rakudrama** [comment]
CssLib benchmark regression understood. Working on a fix.

**Comment by rakudrama** [comment]
Changes for CssLib landed. No numbers yet.

**Comment by leafpetersen** [comment]
I landed the [SplayTree CL](https://dart-review.googlesource.com/c/sdk/+/143200) which restored parity with the pre-nnbd sdk for the relevant benchmark.

**Comment by leafpetersen** [comment]
I've looked at the AsyncStressTest issues, I think they'll be easy to resolve.

**Comment by rakudrama** [comment]
Spec mode aggregate: -8.21%
Production mode aggregate: -4.07%

I have a CL out that makes some spec mode improvements.

**Comment by franklinyow** [comment]
What is the minimum acceptable number we are targeting?

**Comment by rakudrama** [comment]
Spec mode aggregate:  -3.656%
Production mode aggregate: -3.142%

**Comment by rakudrama** [comment]
No update

**Comment by leafpetersen** [comment]
I have a CL for the AsyncStressTest regressions [here](https://dart-review.googlesource.com/c/sdk/+/144302) that will go out tonight.  Initial golem results [here](https://golem.corp.goog/Comparison#targetA%3Ddart2js-production%3BmachineTypeA%3Dlinux-x64%3BrevisionA%3D84799%3BpatchA%3Dleafp-leafp-async-final%3BtargetB%3Ddart2js-production%3BmachineTypeB%3Dlinux-x64%3BrevisionB%3D84799%3BpatchB%3DNone) show the suite in aggregate at 1% faster than the non-nnbd SDK, but with a spread of about -15% to +17% .

**Comment by mit-mit** [comment]
With the AsyncStressTest having a fix landed, and the spec mode and production mode cases within a few percent (~3), is this no longer a blocker for unforking? Or are there other severe regressions?

**Comment by rakudrama** [comment]
Not quite done. There are some benchmarks outside the AsyncStressTest that are not yet acceptable. I have a CL for one issue and then we need to reassess.

**Comment by mit-mit** [comment]
OK, once we reassess, can we please provide an update here with a specific list of issues?

**Comment by rakudrama** [comment]
There is one remaining issue which is esoteric enough to be non-blocking.

Partial results which may improve marginally:
spec mode aggregate: -4.27%
prod mode aggregate: -0.67%
