### ISSUE TITLE
Internal run setup and tested

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41430]
Create internal unfork CL and pass presubmit

Tracking bug: [b/153397493](https://b.corp.google.com/issues/153397493)

**Comment by vsmenon** [comment]
@sigmundch @davidmorgan - can we get an update here?

**Comment by sigmundch** [comment]
Actually, can we keep the updates on the internal bug linked above so we have it all in one place?

We have a CL that can be patched, but we are hitting early blockers:
* we've seen issues when running tests via package:test - I'll look into whether we can replicate it externally without much work to make investigation easier.
* dump-info is not working #41459 
* analyzer couldn't find annotations ([fix][1] already landed)

[1]: https://dart-review.googlesource.com/c/sdk/+/143250

**Comment by franklinyow** [comment]
I'm ok with internal if that works better for you.  I'll pull it daily at the same time (late afternoon)
