### ISSUE TITLE
CFE: spurious error only when building the core library sdk

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41436]
The following class hierarchy is correctly accepted by the CFE when compiled in user code:

```dart
abstract class A {
  late int x;
}

class _B implements A {
  int x = 3;
}
```

However, the same two classes, when placed in one of the core library files, causes the build to fail with the following spurious error:

```
output: org-dartlang-sdk:///sdk_nnbd/lib/_http/http.dart:40:7: Error: The non-abstract class '_B' is missing implementations for these members:
 - A.x
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _B implements A {
      ^^
org-dartlang-sdk:///sdk_nnbd/lib/_http/http.dart:37:12: Context: 'A.x' is defined here.
  late int x;
```

Code to reproduce this uploaded to a CL [here](https://dart-review.googlesource.com/c/sdk/+/143008).

Try bot build failure showing the error [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8883452206842524208/+/steps/build_dart/0/stdout?format=raw).

This is currently blocking my proposed resolution of https://github.com/dart-lang/sdk/issues/41429 .

**Comment by johnniwinther** [comment]
A CL is in the pipeline: https://github.com/dart-lang/sdk/issues/41436

**Comment by leafpetersen** [comment]
This seems to have fixed my reproduction example, but not the original CL that I ran into the problem on.  The CL is [here](https://dart-review.googlesource.com/c/sdk/+/143184), with failures I'm currently seeing [here](https://dart-review.googlesource.com/c/sdk/+/143184).  Error I'm seeing is:

```
Error: The non-abstract class '_StdSink' is missing implementations for these members:
 - IOSink._#IOSink#encoding
org-dartlang-sdk:///sdk_nnbd/lib/io/io_sink.dart@1264+17:
Info: 'IOSink._#IOSink#encoding' is defined here.
org-dartlang-sdk:///sdk_nnbd/lib/io/stdio.dart@6870+6:
Error: The non-abstract class 'Stdout' is missing implementations for these members:
 - IOSink._#IOSink#encoding
org-dartlang-sdk:///sdk_nnbd/lib/io/io_sink.dart@1264+17:
Info: 'IOSink._#IOSink#encoding' is defined here.
```

I'll try to get a more compact reproduction.
