### ISSUE TITLE
VM aot unfork code size regression

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41434]
This issue track the unfork VM-aot code size
The regression need to met performance metric

**Comment by vsmenon** [comment]
Any updates here?  Are we waiting for anything beyond flutter gallery size numbers?

**Comment by a-siva** [comment]
Haven't built flutter gallery and determined the size yet.

**Comment by a-siva** [comment]
Building the flutter gallery app for android/arm with a local engine that has the unfork CL and flutter libraries.yaml file adjusted to point to the NNBD sdk directory shows the following sizes

aot_arm_profile : 29.87 MB
aot_arm_release : 20.57 MB

The base flutter gallery size from top to tree flutter shows the following numbers

aot_arm_profile : 29.87 MB
aot_arm_release : 20.6 MB

It appears we don't seem to have a code size regression.

Will measure the arm64 sizes as well and we should keep the issue open until measurement is done for arm64 as well.

**Comment by a-siva** [comment]
I tried a run again this morning, updating to the latest sources and patching in the following

engine/src/flutter is patched with the following PR flutter/engine#17721

engine/src/third_party/dart with the Dart NNBD unfork CL https://dart-review.googlesource.com/c/sdk/+/138902

Built the AOT flutter apps as follows
flutter/bin/flutter --local-engine=android_release build aot
.....
and measured the size of build/aot/app.so

Flutter Gallery from https://github.com/flutter/gallery

With the NNBD changes patched in:
  android_release_arm64 - 20.702048 MB
  android_profile_arm64 - 30.106464 MB
  android_release_arm - 20.472360 MB
  android_profile_arm - 29.508136 MB

From TOT flutter tree:
  android_release_arm64 - 20.689760 MB
  android_profile_arm64 - 30.090080 MB
  android_release_arm - 20.525608 MB
  android_profile_arm - 29.577768 MB

Flutter Gallery from flutter/dev/integration_tests/flutter_gallery

With the NNBD changes patched in:
  android_release_arm64 - 8.422240 MB
  android_profile_arm64 - 12.243808 MB
  android_release_arm - 8.696360 MB
  android_profile_arm - 12.411432 MB

From TOT flutter tree:
  android_release_arm64 - 8.422240 MB
  android_profile_arm64 - 12.239712 MB
  android_release_arm - 8.692264 MB
  android_profile_arm - 12.399144 MB

We don't appear to see any major regressions in the AOT code sizes.

**Comment by franklinyow** [comment]
Great new!!

**Comment by franklinyow** [comment]
I think the result is good enough to close this issue.  Anything else on this will block the unfork?
