### ISSUE TITLE
CFE: spurious error in mixed mode assignability

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41435]
The new test never_null_assignability_weak_test.dart out for review[here](https://dart-review.googlesource.com/c/sdk/+/143040) is failing on CFE based platforms because of a spurious static error.    Reproduction:

//opted_in.dart
```dart
Never x = throw "Unreachable";
void takesNever(Never x) {}
void takesTakesNull(void Function(Null) f) {}
void Function(Null) f = (n) {};
```

// opted_out.dart
```dart
// @dart=2.7
import 'opted_in.dart';

void main() {
  Null nil;
  x = null;
  x = nil;
  takesNever(null);
  takesNever(nil);
  takesTakesNull(takesNever); // Spurious error here
  f = (Never x) {};
}
```

cc @johnniwinther @stefantsov

**Comment by nshahan** [comment]
The same issue is also causing a compile time failure in language/nnbd/boolean_conversion/boolean_conversion_weak_test.dart. 

cc @liamappelbe
