### ISSUE TITLE
Flutter run with no failure

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41431]
Tracking issue for flutter bot run. 

- Engine build rules need to account for the changes made in the unfork CL, it would be preferable to change the engine build to allow for switching on/off NNBD at build time as we may have to enable/disable NNBD in the engine a few times before it sticks.
- dart:ui has to be migrated for NNBD so that the platform file of Flutter can be built as an opted in library non blocking for unfork  
- Engine and Framework tests run as part of the roll CL should pass
-

**Comment by vsmenon** [comment]
@a-siva - any update here?

**Comment by a-siva** [comment]
Seeing errors in the test runs which are being investigated

00:20 +1170 ~6 -6: /usr/local/google/home/asiva/workspace/flutter-roll/flutter/packages/flutter/test/widgets/platform_view_test.dart: UiKitView UiKitView accepts gestures
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following PlatformException was thrown running a test:
PlatformException(error, unreachable, null)

When the exception was thrown, this was the stack:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:162:41)
#4      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:623:71)
#5      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:573:5)
#6      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:583:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4661:12)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
...     Normal element mounting (7 frames)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
#17     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1129:16)
#18     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1107:5)
#19     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1121:7)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
#22     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1006:18)
#23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#26     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:879:9)
#29     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#30     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:866:27)
#31     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:441:22)
#34     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#35     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:438:27)
#36     main.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/asiva/workspace/flutter-roll/flutter/packages/flutter/test/widgets/platform_view_test.dart:1211:20)
#37     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
<asynchronous suspension>
#38     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#39     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:703:19)
<asynchronous suspension>
#42     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
#43     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1083:24)
#49     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1080:15)
#50     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:133:24)
#51     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#52     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#53     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#58     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#59     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#64     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#65     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
(elided 35 frames from class _FakeAsync, class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  UiKitView accepts gestures

**Comment by a-siva** [comment]
test run updates
debug mode - 23 failures out of 6579 tests
release mode - 1244 failures out of 5332 tests and flutter tester appears to hang after that

A triage needs to be done to categorize the different failures and investigate

**Comment by a-siva** [comment]
I tried a run again this morning, updating to the latest sources and patching in the following

- engine/src/flutter is patched with the following PR [https://github.com/flutter/engine/pull/17721](https://github.com/flutter/engine/pull/17721)

- engine/src/third_party/dart with the Dart NNBD unfork CL [https://dart-review.googlesource.com/c/sdk/+/138902](https://dart-review.googlesource.com/c/sdk/+/138902)

- run the flutter host side testing as follows (flutter/packages/flutter)
```
flutter/bin/flutter -v --local-engine=host_debug test
.....
......
00:46 +2999 ~20: flutter-roll/flutter/packages/flutter/test/gestures/force_press_test.dart: A pressure outside of the device reported min and max pressure will not give an error
The reported device pressure 8.0 is outside of the device pressure range where: 0.0 <= pressure <= 6.66
01:27 +6597 ~23: All tests passed!  
```

**Comment by vsmenon** [comment]
Quick note: I ran flutter web tests on Linux.

```
SHARD=web_tests ../engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart --enable-asserts dev/bots/test.dart --local-engine=host_debug_unopt
...
04:19 +614 ~28 -1: Some tests failed.
```

Result is the same with or without @a-siva 's CL, so this looks good as far as null safety.

I also ran `felt` tests which exercise dart2js:
```
lib/web_ui/dev/felt test
```
Similar - one common failure and several hundred passes.
  
I verified that flutter gallery builds and runs in debug and release.  Release size is well within 1%.

**Comment by vsmenon** [comment]
I believe this is the best status here:

https://github.com/flutter/engine/pull/17818

**Comment by franklinyow** [comment]
flutter/flutter/pull/55813

**Comment by vsmenon** [comment]
@a-siva - what's the status here?  Do we have any blockers beyond internal testing?

**Comment by franklinyow** [comment]
Latest run has no issues https://github.com/flutter/flutter/pull/56309
Closing
