### ISSUE TITLE
Don't report RETURN_OF_INVALID_TYPE when already reported ILLEGAL_ASYNC_RETURN_TYPE

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#41439]
Probably also `ILLEGAL_ASYNC_GENERATOR_RETURN_TYPE`, or `ILLEGAL_SYNC_GENERATOR_RETURN_TYPE` - check if we report `RETURN_OF_INVALID_TYPE` in these cases.

**Comment by srawlins** [comment]
Looks like a duplicate of #38188. I also don't think we report duplicate errors in generators, since they're just not supposed to return anything.

**Comment by scheglov** [comment]
Seems different than https://github.com/dart-lang/sdk/issues/38188, even if in the same are.
The other issue is about saying a wrong type, and this one - about reporting an error at all.
