### ISSUE TITLE
Several dart2js language tests import internal libraries

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41440]
The analyzer classifies importing an internal library as a Compile-time _error_. We wish to no longer allow `// ignore`-ing such errors. There are some dart2js language tests that import internal libraries, and then ignore the error:

```shell
$ git grep -A 1 import_internal_library tests/compiler/dart2js
tests/compiler/dart2js/codegen/model_data/native.dart:// ignore: import_internal_library
tests/compiler/dart2js/codegen/model_data/native.dart-import 'dart:_js_helper';
--
tests/compiler/dart2js/codegen/model_data/native_inlined.dart:// ignore: import_internal_library
tests/compiler/dart2js/codegen/model_data/native_inlined.dart-import 'dart:_js_helper';
--
tests/compiler/dart2js/codegen/model_data/native_unused_parameters.dart:// ignore: import_internal_library
tests/compiler/dart2js/codegen/model_data/native_unused_parameters.dart-import 'dart:_js_helper';
--
tests/compiler/dart2js/member_usage/data/native.dart:// ignore: import_internal_library
tests/compiler/dart2js/member_usage/data/native.dart-import 'dart:_js_helper';
--
tests/compiler/dart2js/rti/emission/native.dart:// ignore: import_internal_library
tests/compiler/dart2js/rti/emission/native.dart-import 'dart:_js_helper' show Native;
tests/compiler/dart2js/rti/emission/native.dart:// ignore: import_internal_library
tests/compiler/dart2js/rti/emission/native.dart-import 'dart:_foreign_helper' show JS;
```

This can be remedied in 1 of 3 ways:

1. The analyzer should not report errors for these imports; in which case the analyzer is just missing some condition that would allow a library to import internal libraries.
2. Importing internal libraries should not be a compile-time error; I doubt this is the solution.
3. The tests should not contain the imports; I assume they contain the imports for important reasons.

**Comment by srawlins** [comment]
Assigning to @sigmundch for triage.

**Comment by sigmundch** [comment]
Indeed - many dart2js unit tests and internal end-to-end tests purposely allow these imports to be able to test low-level features of dart2js.

We'd need something like (1) above. We [whitelist these locations by folder][1] when we configure the CFE, so we'd be OK with a similar solution for analyzer or a general rule that allows using this ignore within the sdk repro only?

[1]: https://github.com/dart-lang/sdk/blob/5ddea4b8f64e0e2b3e46e4aa083603094cd98ffb/pkg/compiler/lib/src/kernel/dart2js_target.dart#L80

**Comment by srawlins** [comment]
Yeah I created a similar whitelist for analyzer:

https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/analysis/library_analyzer.dart#L433

So 1. is what we're doing now. I wish there was a more general solution :/. I'll close this for now, and I'll link to it in our code.
