### ISSUE TITLE
SDK Download Problem from Bangladesh

### ISSUE THREAD

**Issue by DLSHAMIMKAFI** [dart-lang/sdk#41448]
I am trying to install dart-sdk for windows (stable version Link: https://gekorm.com/dart-windows/) but it doesn't download.it always show a message,download failed:The operation timed out.

**Comment by vsmenon** [comment]
Note, the link above is community supported, i.e., not supported by the dart team.

You can install the builds we create from:

https://dart.dev/tools/sdk/archive
