### ISSUE TITLE
[dev_compiler] Expression evaluation tests fail after unforking

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#41443]
Expression evaluation tests in DWDS fail after unforking the SDK due to DDC adding a cast but not the type definition for a case inside the evaluation function:

**Example code:**

some library

```
int testLibraryFunction(int formal) {
  return formal;
}
```

main library
```
void printLocal() {
  var local = 42;
  print('Local is: $local'); // Breakpoint: printLocal
}
```

**Expression evaluated at the breakpoint above:** 

`testLibraryFunction(local)`

**Generated JavaScript:**

```
(function(local) {
  let dart = require('dart_sdk').dart;
  let core = require('dart_sdk').core;
  let test_library = require('packages/_testPackage/test_library.dart').test_library;
  let library = require('packages/_test/library.dart').library;
  let main = require('web/main.dart').web__main;
  return test_library.testLibraryFunction(intL().as(local));
}(
local
))
```

**Evaluation result in chrome:**

`ReferenceError: intL is not defined`

Need to figure out how to define intL inside the fake library and function generated for evaluation.

**Comment by sigmundch** [comment]
/cc @nshahan - FWIW DDC used to create that definition directly where it was used, but we hoisted them out for performance reasons. 

One option to consider is to configure DDC to emit the code differently instead (e.g. add an option to ddc to **not** hoist these when generating code for eval)

**Comment by annagrin** [comment]
Thanks @sigmundch  this sounds exactly what is needed here, plus probably more definitions (such as private symbols and function types)
