### ISSUE TITLE
VM AOT crash in collection tests with NNBD changes

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41452]
[This](https://dart-review.googlesource.com/c/sdk/+/143200/4) CL makes some changes to the core libraries to [eliminate casts](https://github.com/dart-lang/sdk/issues/41445) in the NNBD splay tree code.  The AOT compiled code for `corelib/collection_length_test` seems to be crashing on the nnbd try bot.  See log [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8883339101303531168/+/steps/test_results/0/logs/new_test_failures__logs_/0)

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/143310 should fix the tests failing on vm-kernel-precomp-nnbd-linux-release-x64-try bot.
