### ISSUE TITLE
Fully document ext.dart.io Dart VM Service Protocol extensions.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#41455]
I'm working on third party Dart VM dev tooling and not all discoverable ext.dart.io extensions are fully documented at [service_extension.md](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service_extension.md).

```
ext.dart.io.getHttpEnableTimelineLogging, // Documented
ext.dart.io.setHttpEnableTimelineLogging, // Documented
ext.dart.io.getSocketProfile, // Documented
ext.dart.io.startSocketProfiling, // Documented
ext.dart.io.pauseSocketProfiling, // Documented
ext.dart.io.clearSocketProfile,  // Documented
ext.dart.io.getVersion, // Documented
ext.dart.io.getOpenSockets, // ?
ext.dart.io.getSocketByID, // ?
ext.dart.io.getOpenFiles,  // ?
ext.dart.io.getFileByID // ?
ext.dart.io.getProcesses // ?
```

Is there a more up-to-date protocol extension reference somewhere? If not, could the existing reference be updated to allow for stable consumption of all extensions?

Thanks!

/cc @bkonyi 

Edit: added another undocumented extension

**Comment by bkonyi** [comment]
Hey @modulovalue thanks for reaching out!

To be completely honest, I'm not familiar with the undocumented `dart:io` service extensions that you're listing as they were added quite awhile ago. I'll check where these are used and determine whether or not they're still relevant or if they should be marked as private. If they appear to be useful for tooling purposes, I'll add them to the `service_extension.md` documentation.

**Comment by bkonyi** [comment]
So it looks like these extensions were intended to be private as they return private types (e.g., prefaced with a `_`). Are these extensions required by whatever tooling you're working on? If not, you should be safe to ignore them.

**Comment by modulovalue** [comment]
`ext.dart.io.getOpenSockets` & `ext.dart.io.getSocketByID` are of no interest to us since that space is already covered by the documented calls.

However, our users would greatly benefit from `ext.dart.io.getOpenFiles` & `ext.dart.io.getFileByID` and I strongly believe that these extensions should stay and be made public (not removed or broken without further notice).

**Comment by ZichangG** [comment]
> So it looks like these extensions were intended to be private as they return private types (e.g., prefaced with a _). 

Is it private? Correct me if I'm wrong. It looks like the same as network profiler, which return a json-encoded `ServiceExtensionResponse`. We should probably add those methods into `DartIOExtension`.  @bkonyi

**Comment by bkonyi** [comment]
@ZichangG yes, [these types are private](https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/io_resource_info.dart#L118) which leads me to believe were intended to be private extensions. However, it does seem like they might be useful for external tools as well so it's probably worth "exposing" them officially and having them documented.

@modulovalue in the meantime, I'd recommend avoiding the use of any of the undocumented RPCs as it looks like they'll need to be cleaned up (e.g., creating proper types instead of `_file`) before being documented which means we'll end up breaking things on your end. Do you have any urgent need for these undocumented RPCs to be made official?

**Comment by ZichangG** [comment]
@bkonyi Thanks for explanation. Looks like external tools are able to call these methods. Private return types can't stop users from calling. Can we make extension methods `private`(not exposed outside)?  I guess the answer is no. If so, we probably need to document those methods.

**Comment by modulovalue** [comment]
No, it’s not urgent. Just please, prefer  replacing and not removing them. Advanced debugging capabilities are very helpful to professional users and therefore the whole ecosystem and I hope decisions will be made with that in mind.

**Comment by bkonyi** [comment]
> @bkonyi Thanks for explanation. Looks like external tools are able to call these methods. Private return types can't stop users from calling. Can we make extension methods `private`(not exposed outside)? I guess the answer is no. If so, we probably need to document those methods.

@ZichangG we don't really have a simple way to enforce privacy for a JSON-RPC so the VM service protocol (and by extension the dart:io service extensions) preface private RPC names and types with an underscore to indicate they're private. While this does nothing to prevent users from finding these RPCs from the code base and then using them, we don't provide any compatibility guarantees and can break or remove them when needed.

> No, it’s not urgent. Just please, prefer replacing and not removing them. Advanced debugging capabilities are very helpful to professional users and therefore the whole ecosystem and I hope decisions will be made with that in mind. 

@modulovalue I wouldn't worry about us removing them, especially if they don't expose platform specific details or details about internal VM data structures (I don't think these extensions do either). However, we will have to make at least some minor breaking changes in the process of officially making them public.

**Comment by bkonyi** [comment]
This will be resolved by [this CL](https://dart-review.googlesource.com/c/sdk/+/157160).
