### ISSUE TITLE
Couldn't find the gn binary at path "dart-sdk/buildtools/gn"

### ISSUE THREAD

**Issue by dehengxu** [dart-lang/sdk#41453]
I clone dart-sdk from https://github.com/dart-lang/sdk.git to dart-sdk, checkout tag 2.7.2
Run `./tools/build.py  --mode release --arch=x64 create_sdk` in dart-sdk.
Prompts error:
```
Running python mypath/dart-sdk/tools/generate_buildfiles.py
Couldn't find the gn binary at path: mypath/dart-sdk/buildtools/gn
Couldn't find the gn binary at path: mypath/dart-sdk/buildtools/gn
Tried to run GN, but it failed. Try running it manually:
	$ python mypath/dart-sdk/tools/gn.py -m debug -a x64 --os host -v
```

**Comment by vsmenon** [comment]
Note, you cannot clone the git repo directly and build.  You need to follow the instructions here (`gclient`) here: 

https://github.com/dart-lang/sdk/wiki/Building
