### ISSUE TITLE
Need a new ErrorCode for Security

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41468]
The analyzer should export a security-specific class which extends ErrorCode so that various security-related lint codes can be altered to be Security codes (perhaps SecurityCode). This class should contains `ErrorSeverity get errorSeverity => ErrorSeverity.ERROR;`.

Alternatively, we could provide a subclass to LintCode (perhaps SecurityLintCode) which would just include that `errorSeverity` getter.

**Comment by bwilkerson** [comment]
Have you considered alternatives, and if so what are the advantages of this approach over other possible approaches? (Some examples of alternatives you might consider are (a) adding a getter like `ErrorCode.isSecurityRelated` or (b) adding an `ErrorType.SECURITY` constant.)

**Comment by srawlins** [comment]
I had not considered either of those alternatives, bot they seem fine.

* `ErrorType.SECURITY` can be used in the un-`//ignore`-able logic just as easily as `ErrorSeverity.ERROR`. The current ErrorTypes are:

   ```
   TODO,
   HINT,
   COMPILE_TIME_ERROR,
   CHECKED_MODE_COMPILE_TIME_ERROR,
   STATIC_WARNING,
   STATIC_TYPE_WARNING,
   SYNTACTIC_ERROR,
   LINT
   ```

* `ErrorCode.isSecurityRelated` can be a new field/getter on all subclasses.

In my original suggestion, ErrorSeverity.SECURITY, this seems more like an inappropriate extension of ErrorSeverity, which only has 3 values, ERROR, WARNING, INFO.

Of the three alternatives here, I think I like `ErrorType.SECURITY` best.

Would you want this to be configurable on LintCode, or still a new class like SecurityLintCode with this one getter overridden?

**Comment by bwilkerson** [comment]
I like the new `ErrorType` constant best too.

I'd probably create a new class because the original implementation attempted to minimize the size of the `ErrorCode` objects, but it's not super critical to me because there aren't that many of them so the memory size isn't all that important.

**Comment by srawlins** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/143331
