### ISSUE TITLE
Analyzer doesn't treat on-catch variables as final

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41460]
According to the dart specificztion 17.11
> An on-catch clause of the form on T catch (p1, p2) s introduces a new
> scope CS in which final local variables specified by p1 and p2 are defined
> 
But analyzer doesn't recognize these variables as final. For example

```dart
main() {
  try {
    throw "foo";
  } on String catch (p1, p2) {
    p1 = "";
//  ^^
// [analyzer] unspecified
// [cfe] unspecified
    p2 = new StackTrace.fromString("");
//  ^^
// [analyzer] unspecified
// [cfe] unspecified
  }
}
```
Dart VM produces an errors on the code above (`Error: Can't assign to the final variable 'p1'` (and 'p2' as well)) but in Analyzer the code above works without any issues.

There must be an error in analyzer as well

Tested on `dartanalyzer version 2.8.0-dev.20.0`

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/143243
