### ISSUE TITLE
Conflicting superinterface type arguments not detected

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41475]
Consider the following program:

```dart
class A<T> { T member() => throw "Unreachable"; }
class B<T> { T member() => throw "Unreachable"; }
class Merge<S extends T, T> extends A<S> implements B<T> {}

void main() {
  Merge<int, int>(); // Potential conflict, not actual.
  Merge<int, num>(); // Actual conflict.
}
```

The class `Merge` has the potential to give rise to instances of a class like `Merge<int, num>` which has two distinct generic instantiations of a superinterface (namely `A<int>` and `A<num>`), which is clearly [specified](https://github.com/dart-lang/language/blob/9c63d7c28b5369255fb143fb3675c6b63e370095/specification/dartLangSpec.tex#L3933) to be a compile-time error.

Surprisingly, neither the CFE nor the analyzer detect and report this error as of today (commit 208ab625c159ccefedea58709f9a15ea5e441b19).

We could consider whether the class `Merge` itself could be allowed, because it is not guaranteed to contain this conflict (for instance `Merge<int, int>()` is an instance which does not have the conflict), and then only instance creations like `Merge<int, num>()` where the conflict is real would be flagged as an error.

However, this is clearly an aggressive interpretation of the existing specification, and it seems more in line with the rest of Dart if we maintain that even a possible conflict (as implied by the declaration of `Merge`) is a compile-time error, and then we don't need to worry about tracking down the actual conflicts, they are simply prevented as a consequence of outlawing the potential conflicts.

So my conclusion is that all tools must detect these cases where a class declaration can give rise to a class that implements the same generic class with multiple non-identical type arguments, and report an error.

With null-safety there is a [specified](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#classes-defined-in-opted-in-libraries) approach to conflict resolution when these discrepancies consist of different nullability properties (so a legacy class can implement `A<int*>` and have both `A<int>` and `A<int?>` as superinterfaces). The conflicts that are resolved based on this mechanism are not errors, and the above error detection step must take that into account.

Note that if the program is adjusted such that `S` does not have a bound then both `dart` and `dartanalyzer` report an error, but only in relation to `member`: The error which is caused by having both `A<S>` and `A<T>` as a superinterface remains undetected (at least, no error message talks about it).

**Comment by johnniwinther** [comment]
Shouldn't `B` extend `A` for the example to work?

**Comment by eernstg** [comment]
It certainly should, but it used to do that! Rechecking the example.

**Comment by eernstg** [comment]
Indeed, the issue goes away when we have the intended superinterface connection. It was present in a CL where similar code was added in some tests, but later removed. When I tested that we do get the expected errors they didn't occur, but, obviously, that was because the subtype graph had been changed. So there is no issue. Closing.
