### ISSUE TITLE
Analyzer: Cascade with null-aware selector seems to spuriously make type nullable

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41479]
Consider the following program:

```dart
class C<X> {
  X x;
  C(this.x);
}

void main() {
  C c = C<String?>('Hello!')..x?.length;
}
```

With a fresh `dartanalyzer` from commit 208ab625c159ccefedea58709f9a15ea5e441b19, we get the following response:

```
> dartanalyzer --enable-experiment=non-nullable n019.dart
ERROR|STATIC_TYPE_WARNING|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/lang/dart/scratch/202004/n019.dart|7|9|31|A value of type 'C<String?>?' can't be assigned to a variable of type 'C<dynamic>'.
```

However, the expression `C<String?>('Hello!')..x?.length` evaluates to the newly created instance of `C<String?>`, and there is no way it could be null. The fact that the cascade section uses a null-aware selector `?.length` seems to spuriously make the type of the cascade as a whole nullable.

In support of that assumption, the following variant has no error:

```dart
class C<X> {
  X x;
  C(this.x);
}

void main() {
  C c = C<String?>('Hello!')..x.toString;
}
```

I thought this could be a duplicate and searched, but did not find an existing issue on the same topic.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/144672
