### ISSUE TITLE
Please merge f64f22f66845d7b79448797be11bc6528f53c25f into beta channels

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#41472]
**commit(s) to merge:** f64f22f

**merge instructions:** clean merge

**reason:** Addresses a possible crash in the precompiled runtime when loading snapshots built in Product mode, due to those snapshots including invalid object references

/cc @athomas @mkustermann

**Comment by a-siva** [comment]
Please follow the new merge request process which is described here go/dart-cherry-pick-process

**Comment by mit-mit** [comment]
This was approved in scrum April 14th

**Comment by franklinyow** [comment]
Can we have the original issue# link?

**Comment by athomas** [comment]
@franklinyow There may not be an original issue, I didn't see any mentioned on the commit or the review.

**Comment by sstrickl** [comment]
There isn't an original issue. The bug was found during follow up work, as that followup work increased the likelihood of it happening, and so I immediately created a separate CL with the one line fix to get the fix in ASAP.

**Comment by athomas** [comment]
Merged into beta with 41d42f81f73ae2a161984809fd75be62a8d0f2b7.
