### ISSUE TITLE
Front-end test started to timeout

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#41489]
This test reports a timeout since Apr 8, but there may be an underlying issue that should be investigated, since marking it as "Slow" does not help.

(unittest-asserts-debug-linux):
    pkg/vm/test/kernel_front_end_test   (RuntimeError -> Timeout, expected Pass) at ed0f2a

**Comment by alexmarkov** [comment]
The test `pkg/vm/test/kernel_front_end_test` doesn't time out if it runs in isolation. In fact, its execution time didn't increase since March 31.

This might be related to the other tests running concurrently.

**Comment by alexmarkov** [comment]
I can reproduce timeout on `pkg/vm/test/kernel_front_end_test` if I run

```
tools/test.py --print-passing-stdout  -n dartk-linux-debug-x64 pkg/vm
```

This command runs all `pkg/vm` and `pkg/vm_service` tests.

From the output I can see that a lot of `pkg/vm_service` tests are running concurrently with `pkg/vm/test/kernel_front_end_test`. I think execution of `pkg/vm_service` tests may slow down `kernel_front_end_test` so it doesn't finish in 30 seconds (default timeout used by package:test).
