### ISSUE TITLE
Rework migration tool README prior to shipping tech preview

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41487]
When the user clicks on "Null safety migration help" in the migration preview tool, they are taken to https://github.com/dart-lang/sdk/blob/master/pkg/nnbd_migration/README.md.  We should make sure this text is up to date and accurate prior to shipping the null safety tech preview.

**Comment by srawlins** [comment]
Also need to add text about the user running `pub upgrade` before migrating. Maybe text about ensuring that you are depending on Null Safety-enabled versions of dependencies.

**Comment by stereotype441** [comment]
We believe we've addressed this adequately at this point.  We'll continue tweaking the README as needed, but there's no reason to track this in an open issue anymore.
