### ISSUE TITLE
Migration tool should have a "report an issue" button

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41485]
This button should take the user to a new github issue, prepopulated with information about the version of the tool being run, as well as appropriate labels (if the user is logged in and has the right to add labels).  Preferably it should go through a URL shortening service so that we can update the link after shipment if needed.

@kevmoo can help with the creation of a github URL as well as the URL shortening.

Additionally, if the server reported a stacktrace to the client (see #41392), the stacktrace should be included in the generated issue.

**Comment by stereotype441** [comment]
Note that @kevmoo is experimenting with the URL shortener.  It may not be possible to include a stacktrace in the generated issue after all.

**Comment by stereotype441** [comment]
It looks like there may have been some miscommunication about this feature.  My understanding from talking to @kevmoo is that since we discovered that the URL shortener won't pass through query parameters, we want to go back to the idea of using a direct link.  That way we can pre-populate the bug report with the SDK version, and a stack trace if that's relevant.

Currently the bug is just pre-populated with text that says `Please include your Dart SDK version`, which I don't think is what we want.

**Comment by srawlins** [comment]
I thought that was a separate issue. I thought that this issue was just for a button that the user can press at any time. Then separately there was an issue that, when the preview tool hit a 500, the user was prompted to report this issue, with a stack trace pre-populated.

But I'm happy to add the SDK version to this link.

**Comment by srawlins** [comment]
I'm working on this.

**Comment by stereotype441** [comment]
Thanks Sam!  You're right that the "report an issue when the preview tool hits a 500" feature and the "report an issue because the user just wants to report an issue" appear to be implemented as separate pieces of code, and have different behaviors.  The "report an issue when the preview tool hits a 500" does seem to populate the stack trace.  But it doesn't seem to populate the SDK version (instead asking the user to fill it in).  It seems to me that since we know the SDK version, we ought to populate it.

Do you want to do that as part of addressing this issue, or do you want me to file a separate issue for it?

**Comment by srawlins** [comment]
I've addressed both in https://dart-review.googlesource.com/c/sdk/+/146461.
