### ISSUE TITLE
NNBD. CFE allows non initialized top-level legacy function-type variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41496]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings)

> It is an error if a top level variable or static variable with a non-nullable type has no initializer expression unless the variable is marked with the late modifier.

The code below shows an example when it doesn't work in CFE
```dart
// opted_out_lib.dart
// @dart=2.6
library opted_out_lib;

typedef void LegacyFoo();

// opted_in
import "opted_out_lib.dart";

LegacyFoo f1;
//        ^^
// [analyzer] unspecified
// [cfe] unspecified

class C {
  static LegacyFoo f2;
//                 ^^
// [analyzer] unspecified
// [cfe] unspecified
}

main() {
  new C();
}
```
The code above produce expected errors in analyzer but no any error in VM

Tested on `Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"`

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/927.

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/143811
