### ISSUE TITLE
Migration should add `on dynamic` to bare catch clauses

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41490]
The language team will soon be changing the behavior of opted-in code so that a `catch` clause with no type defaults to type `Object`.  (In opted-out code it will remain `dynamic`).  See https://github.com/dart-lang/language/pull/924.

This means that when migrating code like this:

```dart
void f() {
  try {
    ...
  } catch (e) {
    e.foo();
  }
}
```

we'll need to make some sort of adjustment, since changing the type of `e` from `dynamic` to `Object` would cause the call to `foo` to become a static error.

After some discussion with Leaf, we believe the best way to migrate this code is to add `on dynamic` before the word `catch`, since this preserves pre-NNBD semantics.

Note that it would be nice to avoid making the change when it's unnecessary, e.g. where the exception variable isn't used.

**Comment by leafpetersen** [comment]
The spec change has landed.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
