### ISSUE TITLE
NNBD. CFE allows tear-off method on nullable type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41495]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings)

> It is an error to read a field or tear off a method from an expression whose type is potentially nullable and not dynamic, except for the methods and fields on Object.

But CFE allows to tear off a method

```dart
class A {
  int c1 = 1;
  int test() => 2;
}

main() {
  A? a1 = new A();
  a1.c1;    // Error in analyser and CFE
  a1.test;  // Error in analyzer only
}
```
Tested on `Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"`

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/144761
