### ISSUE TITLE
NNBD. No error in CFE when non-nullable variable is used before it is definitely assigned

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41498]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings)

> It is an error if a potentially non-nullable local variable which has no initializer expression and is not marked late is used before it is definitely assigned

The code below shows the case when it is not so in CFE

```dart
// opted_out_lib.dart
// @dart=2.6
library opted_out_lib;
typedef void LegacyFoo();

// opted in
import "opted_out_lib.dart";

class C {
  static void test() {
    LegacyFoo f;

    f.toString();
//  ^
// [analyzer] unspecified
// [cfe] unspecified
  }

  void test2() {
    LegacyFoo f;

    f.toString();
//  ^
// [analyzer] unspecified
// [cfe] unspecified
  }
}

main() {
  LegacyFoo f;

  f.toString();
//^
// [analyzer] unspecified
// [cfe] unspecified

  Function foo = () {
    LegacyFoo f;

    f.toString();
//  ^
// [analyzer] unspecified
// [cfe] unspecified
  };
  C.test();
  new C().test2();
}
```
The code above produces all expected errors in analyzer but none of them in VM
Tested on `Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"`

Similar issue #41496

**Comment by eernstg** [comment]
It's all about ensuring that `LegacyFoo` means `void Function()` rather than `void Function()*`. Cf. https://github.com/dart-lang/language/issues/927.

**Comment by johnniwinther** [comment]
A Cl is in progress: https://dart-review.googlesource.com/c/sdk/+/143811
