### ISSUE TITLE
Rename null safety strong mode flag

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#41497]
Currently the null safety strong mode flag is controlled by the flag `--no-null-safety` / `--null-safety`.

From offline discussion, we find that this is suboptimal: When a developer opts out of sound/strong checking with `--no-null-safety` they will still get some null safety (e.g. static analysis), but the flag name makes it sound like they are loosing all of null safety.

We'd thus like to rename this flag to `--no-sound-null-safety` / `--sound-null-safety`.

Code search for incorrect terminology:
[Source for --no-null-safety](https://github.com/search?q=org%3Adart-lang+--no-null-safety&type=Code)
[Source for --null-safety](https://github.com/search?q=org%3Adart-lang+--null-safety&type=Code)

**Comment by vsmenon** [comment]
Is this for all tools?  Do we have a source of truth doc on the correct flags for null safety across all tools?

@leafpetersen

**Comment by mit-mit** [comment]
Yes, this is for all tools.

**Comment by mit-mit** [comment]
@franklinyow can you turn this into a meta-bug and file an actual bug per tool?

**Comment by franklinyow** [comment]
@mit-mit I search the code (link in description), so I need one bug for vm and one for dart2js?

**Comment by mit-mit** [comment]
Sounds good

**Comment by leafpetersen** [comment]
> @mit-mit I search the code (link in description), so I need one bug for vm and one for dart2js?

I don't think dart2js is special here.  I think there is one for the CFE (which consumes the flag), and possibly one for the VM, dart2js, and ddc which may (or may not) pass the flag to the CFE.

There is also coordination to be done with whatever is passing those flags in the build files and on the bots.

I'd probably start by checking with @athomas and @johnniwinther .

**Comment by leafpetersen** [comment]
> @mit-mit I search the code (link in description),

p.s. you probably also need to search for `--null-safety` since the flag is negatable.

**Comment by athomas** [comment]
This should be in the test matrix, e.g.:
https://github.com/dart-lang/sdk/blob/c5a5884b7ff58794e9ac921e0537353323282189/tools/bots/test_matrix.json#L628

**Comment by franklinyow** [comment]
Should I move this and all the sub-issues to the beta?

**Comment by franklinyow** [comment]
Renaming is done, closing
