### ISSUE TITLE
NNBD. No error on CFE when function with non-nullable return type may complete normally

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41499]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings)

> It is an error if the body of a method, function, getter, or function expression with a potentially non-nullable return type may complete normally.

The following code shows a case where this statement doesn't work on CFE

```dart
// oped_out_lib.dart
// @dart=2.6
typedef void LegacyFoo();

// opted in
import "opted_out_lib.dart";

class C {
  static LegacyFoo sTest() {}
//                 ^^^^^
// [analyzer] unspecified
// [cfe] unspecified

  LegacyFoo mTest() {}
//          ^^^^^
// [analyzer] unspecified
// [cfe] unspecified

  LegacyFoo get gTest {}
//              ^^^^^
// [analyzer] unspecified
// [cfe] unspecified
}

LegacyFoo test() {}
//        ^^^^
// [analyzer] unspecified
// [cfe] unspecified


main() {
  C.sTest();
  C c = new C();
  c.mTest();
  c.gTest;
  test();
}
```

The code above produces all expected errors in analyzer but none of them in VM
Tesed on `Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"`

Similar  issues #41496, #41498

**Comment by eernstg** [comment]
I believe the expected errors will be emitted when #41505 is implemented.

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/143811
