### ISSUE TITLE
NNBD. In CFE non-nullable type imported from opted out library is treated as nullable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41501]
Code example

```dart
// opted_out_lib.dart
// @dart 
library opted_out_lib;

class A {}
typedef AAlias = A;

// opted in
import "dart:async";
import "opted_out_lib.dart";

main() {
  FutureOr<AAlias> fo = null;
//                      ^^^^
// [analyzer] unspecified
// [cfe] unspecified
}
```

There is no expected error in `Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64" `

Simlar issues  #41496, #41498

**Comment by eernstg** [comment]
I'd prefer that a type alias introduces a type with no nullability into the library namespace, which would imply that we should get the error you mention. I raised this issue in https://github.com/dart-lang/language/issues/927, with an example that does not rely on using non-function type aliases (the case can be made already with an old-fashioned type alias, but it gets even stronger with non-function type aliases).

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/143811
