### ISSUE TITLE
A legacy type alias should introduce a non-nullable type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41505]
Cf. https://github.com/dart-lang/language/issues/927 which describes the situation in more detail, and https://github.com/dart-lang/language/issues/868#issuecomment-600999013 where the language team conclusion was reached and an nnbd spec update planned:

If a type alias `typedef F<...> = T`  in a legacy library is used in a context where null-safety is enabled (that is, `--enable-experiment=non-nullable`), it denotes a type which has had `*` added on all subterms of `T`, but not on `T` itself. For example:

```dart
// @dart = 2.6
typedef F = int Function({String s});
```

When used from a library which enables null-safety, `F` denotes the type `int* Function({String* s})`, not the type `int* Function({String* s})*`.

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/143811
