### ISSUE TITLE
.forEach ~4x slower than equivalent fori

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#41508]
Naive benchmark:

```dart
int sumFori(List<int> list) {
  int x = 0;
  for (int i = 0; i < list.length; i++) x += list[i];
  return x;
}

int sumListFor(List<int> list) {
  int x = 0;
  for (final element in list) x += element;
  return x;
}

int sumForEach(List<int> list) {
  int x = 0;
  list.forEach((element) => x += element);
  return x;
}

void main() {
  final to = 10000000;
  final list = List.generate(to, (a) => a);
  print("sumFori:          ${measure(() => sumFori(list))}");
  print("sumListFor:       ${measure(() => sumListFor(list))}");
  print("sumForEach:       ${measure(() => sumForEach(list))}");
}

MapEntry<String, T> measure<T>(T Function() action) {
  final watch = Stopwatch();
  watch.start();
  final res = action();
  watch.stop();
  return MapEntry(watch.elapsedMicroseconds.toString(), res);
}
```

```
... dart test.dart 
sumFori:          MapEntry(16719: 49999995000000)
sumListFor:       MapEntry(24819: 49999995000000)
sumForEach:       MapEntry(59526: 49999995000000)
```

dart2native is even worse

```
dart2native test.dart -o test
...
... ./test
sumFori:          MapEntry(44480: 49999995000000) // ?
sumListFor:       MapEntry(92430: 49999995000000) // ?
sumForEach:       MapEntry(54395: 49999995000000)
```

`Dart VM version: 2.8.0-dev.17.0 (dev) (Tue Mar 24 16:38:30 2020 +0100) on "macos_x64"`

Does that mean we should, in general, avoid higher-order functions if high performance is needed?

**Comment by lrhn** [comment]
Yes. And no. You should write your code to be efficient, but not at the cost of readability.

Higher order functions are convenient, especially when you already have the argument function available, but they do require a function call per element, and function calls are not free. Nothing is.
A function call isn't necessarily *expensive* either, but for a function as simple as `(element) => x += element`, where the body operation takes almost no time at all, the overhead is clearly visible.
(An add operation like `x += element` can be one machine instruction if at least one of `x` and `element` are in a register and known to be non-`null`).

If you were doing something significant inside the body, the overhead of the call would be much less noticeable. If you really do need the sum of a long list of numbers, and needs it to be very efficient, then yes, you should use the `for` loop with an index.

Also see: https://dart.dev/guides/language/effective-dart/usage#avoid-using-iterableforeach-with-a-function-literal.

**Comment by modulovalue** [comment]
> but they do require a function call per element, and function calls are not free

@lrhn shouldn't the compiler be able to just inline the .forEach call to allow .forEach to be as fast as its for-in equivalent?

especially since .forEach is just defined as
```
  void forEach(void f(E element)) {
    for (E element in this) f(element);
  }
```

I there a reason why `@pragma("vm:prefer-inline")` can't be used to reduce the overhead?

**Comment by lrhn** [comment]
It might be technically possible for a simple program like the one above, but in general, it's very hard to know for sure that `sumForEach` is only ever called with an implementation of `List` which uses that exact implementation of `forEach`. 

And that's actually not the definition of `forEach` for the list that you pass. What the definition is depends on the platform, for the VM it is [this one](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/array.dart#L110).
It happens to be already annotated with the pragma, but that only works when the call point can statically ensure that it knows which exact method implementation is being called.

Inlining of virtual methods only really works when you call the method close to where you create the object. Then the compiler has a chance of tracking the exact type of the object from where it's created to where it's used, and then it can know for certain which method implementation will be called.
Passing the list through a parameter with type `List<int>` means that inside that function, the compiler has to assume *any* list can show up, with any user-defined implementation of `forEach`.

**Comment by modulovalue** [comment]
Thank you.
