### ISSUE TITLE
Add a quick fix to import libraries with prefixes when the library name matches

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#41515]
Given the following code:
```
var min = math.min(0, 1);
```
there should be a quick fix to define `math` by importing `dart:math`. This should minimally work for all of the `dart:` libraries, but it would also be good if it worked for packages that are already listed as dependencies. For example,
```
var current = path.current;
```
should have a quick fix to import `package:path/path.dart`.

**Comment by FMorschel** [comment]
Related to:

- https://github.com/dart-lang/sdk/issues/55863
- https://github.com/dart-lang/sdk/issues/24338
