### ISSUE TITLE
Need a quick fix to remove unnecessary null check

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#41513]
Given the following code:
```
class C {
  C m(C c) => c!;
}
```
analyzer will produce a diagnostic saying that the `!` is unnecessary.

We should have a quick fix to remove it.

**Comment by pq** [comment]
![image](https://user-images.githubusercontent.com/67586/102850517-86debb80-43ce-11eb-975c-cc4619a3b86c.png)

**Comment by pq** [comment]
This one's done. ✅
