### ISSUE TITLE
Add a way to obtain a global `sys::ComponentContext` when building for Fuchsia

### ISSUE THREAD

**Issue by filmil** [dart-lang/sdk#41523]
At the moment, the dart runner for Fuchsia creates and owns one `sys::ComponentContext`, which allows a component to register its functionality with Fuchsia.

However, `sys::ComponentContext::Create()` method returns a valid context only on first call, effectively making the result of *first* call to it a singleton.  This makes it difficult for fuchsia-specific code in `runtime/vm/os_fuchsia.cc`, for example, to use this context, as there is no platform-specific way to pass the context into `OS`.  And having the context available there would be most useful as it would allow us to add Fuchsia-specific diagnostics.

I'd like to make a platform-specific function available which would return a valid singleton on each call, which can then be used where needed in fuchsia-specific code.

Once that is available, I'd like to modify the flutter and dart runners to make use of the new code.  I would also like to add inspect diagnostics into `os_fuchsia.cc`.

**Comment by filmil** [comment]
I'd like to work on this myself; but seems I don't have permission to assign the bug to self.

**Comment by filmil** [comment]
Sent for review: https://dart-review.googlesource.com/c/sdk/+/136524

**Comment by devoncarew** [comment]
cc @cbracken @a-siva to help find a reviewer for the CL above.

**Comment by filmil** [comment]
This is now fixed.
