### ISSUE TITLE
Analyzer: implement change to default type of error variable in catch clauses in null safe code

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41521]
This [pull request](https://github.com/dart-lang/language/pull/924) specifies a change to the default type of the error variable in catch clauses in code that has opted in to null safety.  This change is ready for implementation.

Tests for this change are out for review [here](https://dart-review.googlesource.com/c/sdk/+/143329).

cc @eernstg @lrhn @munificent @natebosch

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/143980
