### ISSUE TITLE
 -fstrict-vtable-pointers is going to break VM handle system

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#41522]
There is an optimization in clang which is currently disabled, but might be enabled in the future which is going to break our handle system.

This optimization makes compiler treat vtables as immutable pointers - allowing it to load vtable just once and cache it in a register. 

Our handle system is largely based on changing vtables based on the class id of the referent. 

I am filing this so that we could start contemplating mitigations. This might entail some large refactoring of our object model so we could also consider fixing UB associated with pointer tagging as part of the same refactoring. 

/cc @a-siva @alexmarkov @mkustermann @rmacnak-google

**Comment by rmacnak-google** [comment]
9166b3eb9d3963cc06f020b90a790992fdd18771
