### ISSUE TITLE
prefer_const_constructors missing in dartfix

### ISSUE THREAD

**Issue by davidmartos96** [dart-lang/sdk#41536]
I have recently discovered the tool `dartfix` and I successfully used it to apply some quick fixes to a moderate size project after including more strict lint rules from the package [lint](https://pub.dev/packages/lint).

The issue is that some fixes that are implemented already in the SDK, are not available in `dartfix`. 
One that I found which I think is pretty useful for Flutter projects is the fix for `prefer_const_constructors`. I've built the SDK from source and I included a `LintFixInfo` for that rule in the `allFixes` variable in https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/edit/fix/dartfix_info.dart 

With that simple change I was able to use `dartfix` to modify the whole project using `dartfix --overwrite --fix prefer_const_constructors`

Other fix that I found missing is the one for the rule `prefer_const_declarations`. I opted to file the issue because I don't know if simply adding fixes to that list can have other implications in other places. 

Thanks for all the tooling available!

Dart SDK: `2.8.0-dev.20.0`

**Comment by bwilkerson** [comment]
No, adding fixes to the list of `allFixes` doesn't impact other tooling and is the correct way to add new fixes to `dartfix`. We'd be happy to take your contribution if you're interested in making one.

**Comment by davidmartos96** [comment]
@bwilkerson Ok, thanks! I have just submitted the changes for review.
