### ISSUE TITLE
Map<K, V> is not using generic types in some of its methods

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/sdk#41544]
In `map.dart`, regarding `abstract class Map<K, V>`, some methods are not using the generic type.

Is there a point of having a generic `Map<K, V>` and then the generic types not being used everywhere?

Instead of:

`V operator [](Object key);`
`bool containsValue(Object value);`
`bool containsKey(Object key);`
`V remove(Object key);`

It should be:

`V operator [](K key);`
`bool containsValue(V value);`
`bool containsKey(K key);`
`V remove(K key);`

If you have some `Map<String, bool> myMap = HashMap();` it never makes sense to ask for `myMap[123]`, since it would always return null.

I keep having bugs because of this.

**Comment by mraleph** [comment]
This is by design and is a not likely to change because it is massive breaking change. see for example #22781 #37685 #30405
