### ISSUE TITLE
lib/math/implement_rectangle_test failing in NNBD strong mode

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#41541]
lib/math/implement_rectangle_test is failing in strong mode. It looks like some sort of type inference issue in the CFE. `T` is declared as `T extends num`, but these errors say `Error: A value of type 'num' can't be assigned to a variable of type 'T'`. It doesn't seem to be a nullability issue, because when I tried adding a `!` after some of these variables in case that was the issue, I got a bunch of warnings saying that `T` can't be null.

Logs:
https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-debug-x64/dartk-weak-asserts-linux-debug-x64/1064/lib/math/implement_rectangle_test

**Comment by whesse** [comment]
Fixing, using the same code that is used in math.Rectangle implementation.
Even though int + int => int and double + double => double, there is no support for saying that for all T extends num, T + T => T, even though it is in fact the case.  So we need to add the cast.
https://dart-review.googlesource.com/c/sdk/+/144942
