### ISSUE TITLE
Please merge #eac545a00da71f1d48a70c1da2720c8badf7356c into beta channel

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#41553]
**commit(s) to merge**: eac545a00da71f1d48a70c1da2720c8badf7356c

**merge instructions**: clean merge

**reason**: fixes an old bug that recently resurfaced and started causing nasty OOMs during Flutter builds.  Original bug: [https://github.com/flutter/flutter/issues/53903](https://github.com/flutter/flutter/issues/53903 )

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by franklinyow** [comment]
cherrypick approved

**Comment by athomas** [comment]
Merged into beta with 91f39d8eb15aad876332637eea090e196ad295ff (2.8.0-20.10.beta).
