### ISSUE TITLE
Please merge #2cf981f354e15a9a88cec0b5c534c01aa55828c9 into dev channel

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#41550]
**commit(s) to merge**: 2cf981f354e15a9a88cec0b5c534c01aa55828c9

**merge instructions**: `git cherry-pick 2cf981f354e15a9a88cec0b5c534c01aa55828c9`

**reason**: Makes VM no longer segfault during hot-reload (in common cases, which flutter users are hitting). See https://github.com/dart-lang/sdk/issues/41482 . There might be follow-up work to handle the issue better, but this change makes the situation already much better

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by mkustermann** [comment]
@franklinyow I tentatively added the `merge-to-beta` label as well.

**Comment by franklinyow** [comment]
cherrypick approved

**Comment by athomas** [comment]
Merged into beta with 91f39d8eb15aad876332637eea090e196ad295ff (2.8.0-20.10.beta).
