### ISSUE TITLE
CFE Support for Null Safety Tech Preview

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#41565]

**Comment by kevmoo** [comment]
@johnniwinther – I remove the flutter package dependency white list item from this epic – that's needed for tech preview 2 (w/ flutter).

I think we should close this epic down and create another one for preview 2 – reasonable?

CC @franklinyow @mit-mit

**Comment by kevmoo** [comment]
I'm going to close now – feel free to reopen – or let's discuss!

AFAIK there are no blocking issues for preview 1 – at least related to the CFE
