### ISSUE TITLE
NNBD_TOP_MERGE(dynamic, Object*) produces incorrect result with analyzer 

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41566]
Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"

NNBD_TOP_MERGE(dynamic, Object*) produces incorrect result.

Please run analyzer with the following code source:
**test_out_lib.dart**
``` dart
// @dart=2.6

class A<T> {}

class out_int extends A<int> {}
class out_Object extends A<Object> {}
```
**test.dart**
``` dart
import 'test_out_lib.dart';

class B extends A {}

class in1 extends out_Object implements B {}
class in2 extends B implements out_Object {}

class in3 extends out_int implements B {}
class in4 extends B implements out_int {}

main() {}
```
Sample output is:
> $> dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error - The class 'in3' cannot implement both 'A<int*>*' and 'A<dynamic>' because the type arguments are different. - test.dart:8:1 - conflicting_generic_interfaces
>   error - The class 'in4' cannot implement both 'A<dynamic>' and 'A<int*>*' because the type arguments are different. - test.dart:9:1 - conflicting_generic_interfaces
> 2 errors found.

Seems like declarations of the classes `in1` and `in2` should produce compile errors like `in3` and `in4`.

**Comment by scheglov** [comment]
I think `in1` and `in2` are fine. [`NNBD_TOP_MERGE`](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#classes-defined-in-opted-in-libraries) has `NNBD_TOP_MERGE(Object*, dynamic) = Object?`.
