### ISSUE TITLE
NNBD: Inaccurate error diagnostic for Null type parameter.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41563]
Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"

The following source code example throws expected compile error:
``` dart
class A<T> {}
class B extends A<Null> {}
class C extends A<void> implements B {}

main() {}
```
Dart sample output is:
> $> dart --enable-experiment=non-nullable test.dart
> test.dart:3:7: Error: 'C' can't implement both 'A<void>' and 'A<Null?>'
>  - 'A' is from 'test.dart'.
> class C extends A<void> implements B {}
>       ^
> 
> Process finished with exit code 254

Seems like error message inaccurate: it should contain `'C' can't implement both 'A<void>' and 'A<Null>'` instead of `'C' can't implement both 'A<void>' and 'A<Null?>'`

`Null` already is a nullable type, so `Null?` in the error diagnostic looks like a nonsense.

Please also note that analyzer error looks correct.

**Comment by devoncarew** [comment]
@johnniwinther @a-siva - I triage to area-front-end; not sure if this should instead be area-vm

**Comment by johnniwinther** [comment]
This is a front-end issue.

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/145461
