### ISSUE TITLE
NNBD_TOP_MERGE(dynamic, Object*) produces incorrect result in runtime

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41567]
Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"

NNBD_TOP_MERGE(dynamic, Object*) produces incorrect result with Dart.

Please run dartr with the following code source:

**test_out_lib.dart**
``` dart
// @dart=2.6

class A<T> {}

class out_int extends A<int> {}
class out_Object extends A<Object> {}
```
**test.dart**
``` dart
import 'test_out_lib.dart';

class B extends A {}

class in1 extends out_Object implements B {}
class in2 extends B implements out_Object {}

class in3 extends out_int implements B {}
class in4 extends B implements out_int {}

main() {}
```
Sample output is:
> $> dart --enable-experiment=non-nullable test.dart
> test.dart:8:7: Error: 'in3' can't implement both 'A<int>' and 'A<dynamic>'
>  - 'A' is from 'test_out_lib.dart'.
> class in3 extends out_int implements B {}
>       ^
> test.dart:9:7: Error: 'in4' can't implement both 'A<dynamic>' and 'A<int>'
>  - 'A' is from 'test_out_lib.dart'.
> class in4 extends B implements out_int {}
>       ^

Seems like declarations of the classes `in1` and `in2` should produce compile errors like `in3` and `in4`.

**Comment by iarkh** [comment]
See also similar bug against analyzer: #41566

**Comment by devoncarew** [comment]
@johnniwinther @a-siva - I triage to area-front-end; not sure if this should instead be area-vm

**Comment by johnniwinther** [comment]
This is a front-end issue

**Comment by eernstg** [comment]
Just checking: The discussions that lead to the `NNBD_TOP_MERGE` adjustments were framed in terms of `void`, `dynamic` and `Object?`, but we do have `NNBD_TOP_MERGE(Object*, dynamic) = Object?` as well, and the reverse.

**Comment by johnniwinther** [comment]
We do: https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#classes-defined-in-opted-in-libraries

**Comment by eernstg** [comment]
Yes, that's what I just checked. ;-)

**Comment by johnniwinther** [comment]
Closing this issue since we now have `NNBD_TOP_MERGE(dynamic, Object*) = Object?` meaning that no error should be reported on `in1` and `in2`.
