### ISSUE TITLE
Inconsistent type-inference for generic parameters based on the variable location

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#41572]
Related to #41571 

Consider the initial code:

```dart
class Provider<Res> {
  Provider(Res Function(ProviderState<Res>) create);
}

class Provider1<First, Res> {
  Provider1(
    Provider<First> provider,
    Res Function(ProviderState<Res>, ProviderState<int>) create,
  );
}

class ProviderState<Res> {
  Res state;
}
```

Then, used as such:

```dart
final otherProvider = Provider((_) => 42);

final provider1 = Provider1(otherProvider, (state, otherState) {
  return 'Hello world';
});

void main() {
  ...
}
```

Then the parameters `state`/`otherState` of`provider1` are inferred as `ProviderState<String>` and `ProviderState<int>`, which is fine.

On the other hand, if we move the declaration of these two variable to a different block like so:

```dart
void main() {
  final otherProvider = Provider((_) => 42);

  final provider1 = Provider1(otherProvider, (state, otherState) {
    return 'Hello world';
  });
}
```

Then now `state` and `otherState` of `provider1` are both inferred as `ProviderState<dynamic>`.

**Comment by rrousselGit** [comment]
The irony is that when the inference is correct, this generates a `top_level_function_literal_block` warning of incorrect inference.

But when used inside a code block, the inference is incorrect and doesn't trigger a `top_level_function_literal_block`.

**Comment by rrousselGit** [comment]
It's also worth nothing that while the inference fails and the type resolve to `ProviderState<dynamic>`, this does not trigger the `implicit-dynamic` error

**Comment by devoncarew** [comment]
@rrousselGit - are you seeing these issues from the analyzer or the runtime (the VM)?

**Comment by rrousselGit** [comment]
Both the analyzer and the runtime

**Comment by srawlins** [comment]
At this time, analyzer infers `ProviderState<Object?>` and `ProviderState<int>` for `state` and `otherState`, respectively, _in either test case_. Meaning, when `otherProvider` and `provider1` are declared top-level, or as local variables, they have the same inferred type arguments.

Weirdly, `provider1` is inferred as `Provider1<int, String>`. You'd think `String` would match `Object1` but 🤷 

In any case, the inference matches, and `implicit-dynamic` is retired, so I'm going to close this.
