### ISSUE TITLE
False positive with top_level_function_literal_block

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#41571]
Consider the following code:

```dart
class Provider<Res> {
  Provider(Res Function() create);
}

// Fine, no warning
final provider = Provider(() => 42);

// Triggers top_level_function_literal_block but correctly inferred as Provider<String>
final otherProvider = Provider(() {
  return 'Hello world';
});
```

The line `otherProvider = Provider(...0` triggers a `top_level_function_literal_block` (The type of the function literal can't be inferred because the literal has a block as its body) when the inference worked. 

Since the inference worked, this shouldn't trigger the warning.

**Comment by scheglov** [comment]
With https://dart-review.googlesource.com/c/sdk/+/198920 we stopped reporting `StrongModeCode`.
We have been doing inference with block bodied function expressions for some time, since summary2.
