### ISSUE TITLE
ExperimentStatus.currentVersion does not reflect the current sdk version

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41583]
This number is not taken from the current running SDK and it is not configurable through analysis options or any other mechanism - it is hardcoded [here](https://github.com/dart-lang/sdk/blob/b774160615a741ce40ff6fd8f3bf7bf5f78556c4/pkg/analyzer/lib/src/dart/analysis/experiments.g.dart#L11).

This, combined with a wide sdk constraint on the sdk, means that the language versions reported by `LibraryElement.languageVersionMinor` is often incorrect (unless it just happens to be right by chance).

Codegen authors need to know the correct language version to be able to generate compatible code, so this is probably a blocker for any codegen migrating to NNBD etc, hence the P1 priority.

I would suggest either reading this from the current SDK version file or making it explicitly configurable (preferably both).

**Comment by scheglov** [comment]
@stereotype441

**Comment by stereotype441** [comment]
Hi @jakemac53, the intent of `ExperimentStatus.currentVersion` is to let the analyzer advertise the version of Dart which it *implements*.  If you like, we could also add an API to allow you to query the version of the SDK that the user is currently performing analysis against.  But in that case I wonder if you might be better off just using `Platform.version`, which tells you the version of the SDK that the currently executing Dart VM supports.  What do you think about that?

**Comment by jakemac53** [comment]
The actual problem here is that `LibraryElement.languageVersion{Major,Minor}` returns `ExperimentStatus.currentVersion` if the language version was null for that library. We don't have the ability to change how that works, so our users (code generators) are getting the wrong version - and the library itself is being treated as having the wrong version.

It might be worth doing a quick video chat or something - I am not sure how the analyzer can actually do anything correct here outside of having more restrictive sdk constraints. This would solve a lot of other problems as well.

**Comment by stereotype441** [comment]
@jakemac53 @scheglov 
Ok, I've set up a VC for this afternoon.

**Comment by jakemac53** [comment]
Closing in favor of https://github.com/dart-lang/build/issues/2673.

We will also suggest that when writing language version comments into part files a builder author should look at the compilation unit ast node for an override comment, and only copy it over if one is present.
