### ISSUE TITLE
Migration tool should understand when migration a bazel package, as opposed to pub

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41584]
The big item that the migration tool should do here is enable Null Safety via the BUILD file, rather than the pubspec.yaml file.

**Comment by devoncarew** [comment]
@srawlins - is this complete now, now that we understand the dart_library mechanism to opt a package into nnbd?

**Comment by srawlins** [comment]
I doubt it... The tool actually parses the pubspec.yaml file. @stereotype441 have you been using it in google3? The main question I think is whether we need to block people from using the tool when their BUILD is in the wrong opt in/out state.

**Comment by stereotype441** [comment]
Emmanuel Pellereau is working on an internal migrator that wraps the migration tool and does additional things like updating the BUILD file.  I'm not sure what its state is, but the work to implement it is bing tracked elsewhere, so in any case I think it would be ok to close this issue.
