### ISSUE TITLE
Flow analysis. No hint for unreachable code

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41593]
Consider the following code
```dart
Never get n => throw "me";

main() {
  try {
    n;
    n;
  } catch (_) {}
}
```
It produces no issues in VM and Analyzer. But according to the [flow analysys](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md#expressions) execution flow after variable or getter of type Never is unreachable. So, the second call of `n` is a dead code. Currently analyzer produces a hint for the dead code. It should produce this hint in this case as well.
Tested on `dartanalyzer version 2.9.0-1.0.dev `

**Comment by devoncarew** [comment]
cc @stereotype441

**Comment by bwilkerson** [comment]
@scheglov Who might have recently fixed this.

**Comment by scheglov** [comment]
It almost work in this case.
One more fix is necessary though.
https://dart-review.googlesource.com/c/sdk/+/144348
