### ISSUE TITLE
@sealed annotation has no effect

### ISSUE THREAD

**Issue by ValeriusGC** [dart-lang/sdk#41591]
In some package:
```
import 'package:meta/meta.dart';
@sealed
class SealedTest<T> {}
```
In another:
`class SNPath2 extends SealedTest<String>{}`

and no any warnings.

`@immutable`, `@protected`, etc work

--

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2019.3)

```

**Comment by srawlins** [comment]
@ValeriusGC Can you say specifically the two files you mention? The one which declares the sealed class and the one which extends it? This should be working, and you should get a report from analyzer if the two files are in different Dart packages, indicated by pubspec files.

**Comment by ValeriusGC** [comment]
> @ValeriusGC Can you say specifically the two files you mention? The one which declares the sealed class and the one which extends it? This should be working, and you should get a report from analyzer if the two files are in different Dart packages, indicated by pubspec files.

Yes it should but... Nope, alas.
![Screenshot from 2020-06-18 14-57-12](https://user-images.githubusercontent.com/3320861/85006931-3c0c8e80-b174-11ea-9696-fc2ada3f41d4.png)

As you can see, analyzer had found no issues.

my **pubspec:**
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

```

**Comment by mraleph** [comment]
Your files in the **same package**. Note this part (emphasis mine):

>  This should be working, and you should get a report from analyzer **if the two files are in different Dart packages**

**Comment by ValeriusGC** [comment]
> Your files are in the **same package**. Note this part (emphasis mine):
Really?
`lib/first/base` & `lib/second/derived` has only common **lib** as root for **all dart code**.
In this case there has no any possibility to use `@sealed` inside the same project ))))

**Comment by srawlins** [comment]
The pubspec file, specifying a package root, is above `lib/`, so they are in the same package.

`@sealed` has no effect here. And there is no similar annotation which would ban sub-classing within a package.
