### ISSUE TITLE
在创建的Flutter插件上，dart解析器不工作了

### ISSUE THREAD

**Issue by changleibox** [dart-lang/sdk#41598]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.9.0-edge.4814f000de2b12405c0da02047b99c41dd957b33`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.4, screens 1680x1050  Retina`

**Comment by devoncarew** [comment]
Was there a stack trace associated with this error report?

**Comment by changleibox** [comment]
不好意思，并没有错误日志，但是我可以描述一下错误发生的过程：
在我开发Flutter插件的时候，发现所有的代码链接都失效了，查看源码，代码提示这些都没有任何反应，代码错误也不会实时检查，当我尝试重启dart解析器，重启Android Studio，重启电脑都不能解决这个问题，但是在我运行项目的时候，编辑器会提示我代码错误。此问题只在我开发Flutter插件的时候出现，开发app的时候，没有这个问题。

**Comment by changleibox** [comment]
> Was there a stack trace associated with this error report?

不好意思，并没有错误日志，但是我可以描述一下错误发生的过程：
在我开发Flutter插件的时候，发现所有的代码链接都失效了，查看源码，代码提示这些都没有任何反应，代码错误也不会实时检查，当我尝试重启dart解析器，重启Android Studio，重启电脑都不能解决这个问题，但是在我运行项目的时候，编辑器会提示我代码错误。此问题只在我开发Flutter插件的时候出现，开发app的时候，没有这个问题。

**Comment by changleibox** [comment]
> Was there a stack trace associated with this error report?

不好意思，并没有错误日志，但是我可以描述一下错误发生的过程：
在我开发Flutter插件的时候，发现所有的代码链接都失效了，查看源码，代码提示这些都没有任何反应，代码错误也不会实时检查，当我尝试重启dart解析器，重启Android Studio，重启电脑都不能解决这个问题，但是在我运行项目的时候，编辑器会提示我代码错误。此问题只在我开发Flutter插件的时候出现，开发app的时候，没有这个问题。

**Comment by srawlins** [comment]
Apologies that we did not get a chance to look at this crash. Please re-open if you see this again with a recent version of Dart.
