### ISSUE TITLE
Write failed (OS Error: Broken pipe, errno = 32), port = 0

### ISSUE THREAD

**Issue by huaji249** [dart-lang/sdk#41594]
when try use pub on android arm64
version: 2.7.2

**Comment by devoncarew** [comment]
What were you doing when this occurred? Are there any steps to reproduce the issue?

**Comment by huaji249** [comment]
use --trace option
I found error from Process.start

**Comment by huaji249** [comment]
dart pub.dart.snapshot global activate stagehand

**Comment by mraleph** [comment]
> when try use pub on android arm64

Are you trying to literally use `pub` on the android device? 

Or are you using it on desktop?

You need to provide full error log - this unfortunately does not contain enough information.

Also if you are using Flutter from China make sure you follow [these guidelines](https://flutter.dev/community/china) and use the pub mirror rather than using normal pub server.

**Comment by huaji249** [comment]
on android device
FINE: Extracting .tar.gz stream to /data/data/com.termux/files/home/.pub-cache/_temp/dirQPYTKD.     IO  : Spawning "tar --extract --gunzip --no-same-owner --no-same-permissions --directory /data/data/com.termux/files/home/.pub-cache/_temp/dirQPYTKD" in /storage/emulated/legacy/dart/.
ERR : Write failed (OS Error: Broken pipe, errno = 32), port = 0                                    FINE: Exception type: SocketException
FINE: dart:io                                              Process.start                                | package:pub/src/io.dart 800:12                       _doProcess                                   | package:pub/src/io.dart 674:27                       _startProcess.<fn>
    | ===== asynchronous gap ===========================                                                | dart:async                                           Future.then                                  | package:pub/src/io.dart 673:36                       _startProcess
    | package:pub/src/io.dart 861:23                       extractTarGz                                 | package:pub/src/source/hosted.dart 323:11            BoundHostedSource._download                  | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper                      | package:pub/src/source/hosted.dart                   BoundHostedSource._download                  | package:pub/src/source/hosted.dart 217:13            BoundHostedSource.downloadToSystemCache
    | package:pub/src/global_packages.dart 202:50          GlobalPackages._installInCache.<fn>.<fn>     | package:pub/src/http.dart 271:51                     withDependencyType                           | package:pub/src/global_packages.dart 198:14          GlobalPackages._installInCache.<fn>
    | dart:async                                           Future.wait                                  | package:pub/src/global_packages.dart 197:18          GlobalPackages._installInCache               | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/version_solver.dart           VersionSolver.solve                          | dart:async                                           _completeOnAsyncReturn                       | package:pub/src/solver/version_solver.dart           VersionSolver._result
    | ===== asynchronous gap ===========================                                                | dart:async                                           _asyncThenWrapperHelper                      | package:pub/src/global_packages.dart                 GlobalPackages._installInCache
    | package:pub/src/global_packages.dart 125:11          GlobalPackages.activateHosted                | package:pub/src/command/global_activate.dart 114:24  GlobalActivateCommand.run                    | package:args/command_runner.dart 197:27              CommandRunner.runCommand
    | package:pub/src/command_runner.dart 171:39           PubCommandRunner.runCommand.<fn>             | dart:async                                           new Future.sync                              | package:pub/src/utils.dart 109:12                    captureErrors.<fn>
    | package:stack_trace                                  Chain.capture                                | package:pub/src/utils.dart 122:11                    captureErrors                                | package:pub/src/command_runner.dart 171:13           PubCommandRunner.runCommand

**Comment by mraleph** [comment]
Does your android device have `tar` installed on it? 

I don't think we really support `pub` on mobile devices - its intended to be used on desktops and servers (CI).

Though error message could be more clear /cc @jonasfj

**Comment by huaji249** [comment]
install tar in termux
it run successfully
