### ISSUE TITLE
CFE: Failure to infer correct type

### ISSUE THREAD

**Issue by siqwin** [dart-lang/sdk#41601]
Code:

```
abstract class IContainer {}
abstract class Container {}

abstract class ITestContainer implements IContainer {}
class TestContainer extends Container implements ITestContainer {}

abstract class BaseTest {
  Container _p = TestContainer();
  T getP<T extends IContainer>() => _p as T;
}

class Test extends BaseTest {
  ITestContainer get p => super.getP<ITestContainer>();
  void start() => print(p.runtimeType);
}

void main() => Test().start();
```

I find it strange that this code throws an error:

`Uncaught Error: TypeError: The type argument 'dynamic' is not a subtype of the type variable bound 'IContainer' of type variable 'T' in 'getP'.`

But if I change this line:
`ITestContainer get p => super.getP<ITestContainer>();`
to this one:
`ITestContainer get p => getP<ITestContainer>();`
then it works.

I would be grateful if someone would explain what was the matter.

**Comment by eernstg** [comment]
The error occurs with dart2js (not dart), so it's dart2js-specific and not a front-end thing. I'll change the label.

However, it doesn't occur with the version of dart2js that is part of commit e6baa97e9adcd7908fee7ea8cf509445c2506876, so it seems to be a problem that will go away soon.

**Comment by eernstg** [comment]
I'll close this because the bug has been fixed in recent versions. But thanks for the input, and don't hesitate to create a new issue if something comes up!
