### ISSUE TITLE
Errors remain after running "flutter generate" to generate files in .dart_tool

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#41605]
This was raised by @szotp at https://github.com/Dart-Code/Dart-Code/issues/1970 but it seems like an analysis server bug.

The [sample project](https://github.com/Dart-Code/Dart-Code/issues/1970#issuecomment-528333884) uses the `r_flutter` package which generates a class for all Flutter assets when you run `flutter generate`. The `lib/main.dart` file looks like this:

```
import 'package:flutter/material.dart';
import 'assets.dart';

void main() {
  print(Assets.main);
  runApp(SizedBox());
}
```

The `assets.dart` file does not exist, but after running `flutter generate` it gets created at `.dart_tool/build/generated/generation_sample/lib/assets.dart`. If you start the server when the file already exists, the server (though some mechanism I'm not familiar with) knows that `import "asserts.dart"` refers to the file inside the `_dart.tool` folder and everything works.

However, if the file doesn't exist when the server starts, and you run `flutter generate` while the server is running, it does not seem to locate the file or remove the errors. The new file does show in the instrumentation log (though doesn't seem to trigger any analysis or anything):

```
1587477792255:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/flutter_tool/pubspec.yaml:add
1587477794124:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/flutter_tool/pubspec.lock:add
1587477794124:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/flutter_tool/.packages:add
1587477794124:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/build/entrypoint/id:add
1587477794124:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/flutter_tool/.dart_tool/package_config.json:add
1587477805034:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/flutter_tool/.dart_tool/pub/bin/build_runner/build_runner.dart.snapshot.dart2:add
1587477805615:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/flutter_tool/.dart_tool/build/entrypoint/build.dart:add
1587477814083:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/build/entrypoint/build.dart.snapshot:add
1587477814974:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/build/generated/generation_sample/lib/assets.dart:add
1587477814975:Watch:/Users/danny/Desktop/generation_sample:/Users/danny/Desktop/generation_sample/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/asset_graph.json:add
```

**Comment by devoncarew** [comment]
Interesting, I did not know about `flutter generate`. I wonder when it got added? The docs:

```
run code generators.
```

don't seem particularly extensive.

**Comment by DanTup** [comment]
Yeah, I couldn't find much on it either - I think it may have been to support codegen during hot reloads? (it [came up in Dart-Code before](https://github.com/Dart-Code/Dart-Code/issues/1976) because of some issues hitting breakpoints with it).

I'm not sure if the mechanism for generating the files matters here though - I suspect creating that file manually would show the same issue.

I don't know why the `import "asserts.dart"` can act like `import "../.dart_tool/build/generated/generation_sample/lib/assets.dart";. I presume it's deliberate, but I'm not sure what the rules are (so I'm not sure where to start to understand why the late-generated file doesn't work).

**Comment by DanTup** [comment]
`flutter generate` was removed in https://github.com/flutter/flutter/pull/61475, so this doesn't seem like it can be an issue anymore.
