### ISSUE TITLE
Change distribution model for migration tool to allow for updates after SDK ships

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41604]
Currently `dart migrate` works by spawning the analysis server shipped with the SDK, connecting to it, and asking it to do the migration.  We'd like to change this so that:
- It runs the tool using `pub run`
- The first thing the tool does is attempt to query the pub website to see if a newer version of itself is available, and alert the user if so.

This will take some nontrivial refactoring--in particular, all of the migration logic needs to be moved out of the analysis server (since we don't want to publish the analysis server on pub).

**Comment by stereotype441** [comment]
I'm currently working on a timeboxed experiment to determine how feasible this is.

**Comment by mnordine** [comment]
Is there a better way to run the `migrate` tool than the instructions here?  
https://github.com/dart-lang/sdk/tree/master/pkg/nnbd_migration

Is there a package that could be run that I'm not finding on https://pub.dev?

**Comment by stereotype441** [comment]
> Is there a better way to run the `migrate` tool than the instructions here?
> https://github.com/dart-lang/sdk/tree/master/pkg/nnbd_migration
> 
> Is there a package that could be run that I'm not finding on https://pub.dev?

Those instructions are the best way to run the `migrate` tool.  The goal of this issue is to make internal changes so that the internals of the migration tool get pulled from https://pub.dev, but even after it is done, the user experience will be to run the tool using `dart migrate`.

**Comment by srawlins** [comment]
This issue is obsolete, I think. We're sticking with `dart migrate`.

**Comment by stereotype441** [comment]
> This issue is obsolete, I think. We're sticking with `dart migrate`.

Yes.  We abandoned plans to ship the tool on pub.  If we need to make updates after the SDK ships we'll have to cherry-pick them.
