### ISSUE TITLE
An unnamed ExtensionElement has a non-null, blank name.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41614]
An unnamed ExtensionElement has a non-null, blank `name` (`""`). I suspect that this is intentional. However, the documentation for `Element.name` says:

> Return the name of this element, or `null` if this element does not have a name.

It would be helpful if this comment were updated to include the second caveat that an "unnamed" extension (or an extension whose declaration "omits the name identifier") (both terms are used in [the spec](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md)), for the purposes of this field, is not _unnamed_, but rather has a blank name.

**Comment by bwilkerson** [comment]
It would be more consistent with the rest of the API if the `name` were `null` in the case where no name is given.
