### ISSUE TITLE
SDK build fails if a file is modified in Emacs, creating #file#.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#4162]
If a source code file has been modified in Emacs, but not saved, and build.py is run, the SDK builder fails because of the file

/tmp/tmpRHMzrr/lib/dart2js/runtime/bin/.#socket_impl.dart

is missing (for example).  The SDK builder should be able to ignore files starting and ending with #, which are the temporary files created by Emacs while editing.

**Comment by athomas** [comment]
Assuming this is no longer an issue. Re-open if I'm mistaken.
