### ISSUE TITLE
Buildbot stays red after failing test is fixed

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#41627]
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-win-debug-x64/7491 is still red after CL that fixes the failures landed.

Not clear how to turn the bot green.

cc @athomas @whesse

**Comment by whesse** [comment]
There is some failure of our logic that made that build red.  It correctly
detected that those failures were fixed.  Compare to the stdout of the test
results step of the previous build.  That one listed the two unfixed
tests.  And this one doesn't list any unfixed failures.

The logic is supposed to turn it red if there are any unfixed, unapproved
failures, and list those failures in the stdout.  I'll look into how it can
report that there are some, but not print any.

Another strange thing is that there is an approval comment with a bug
listed on the commit with the failures, but the failures aren't actually
approved - no check marks. Did you unselect them before hitting approve?.

**Comment by aam** [comment]
> Another strange thing is that there is an approval comment with a bug
listed on the commit with the failures, but the failures aren't actually
approved - no check marks. Did you unselect them before hitting approve?.

No, I approved different test failure on another (reload) buildbot on the same CL. I did that before two other failures on windows buildbots showed up.
