### ISSUE TITLE
AVD manager is not showing for clicking.

### ISSUE THREAD

**Issue by satyam440** [dart-lang/sdk#41631]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.7.2`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

**Comment by mraleph** [comment]
Could you clarify your problem? Current bug report does not really have any actionable information.
