### ISSUE TITLE
Type normalization doesn't work for FutureOr<Never> in Analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41632]
According to the Type normalization [specification](https://github.com/dart-lang/language/blob/master/resources/type-system/normalization.md)

> NORM(FutureOr< T >) =
> let S be NORM(T)
> ...
> if S is Never then Future< Never >

This works in dart VM but doesn't work in analyzer
```dart
import 'dart:async';

class A<X> {}
class B<X> implements A<X> {}

class C extends B<FutureOr<Never>> implements A<Future<Never>> {} 

main() {
  new C();
}
```
Analyzer produces
`error - The class 'C' cannot implement both 'A<Future<Never>>' and 'A<Future<Never>>' because the type arguments are different`

Tested with `dartanalyzer version 2.9.0-2.0.dev`

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/144661
