### ISSUE TITLE
Code size increase due to inlined method extractors

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#41647]
The recent change to [handle tearoffs in the dispatch table](https://dart-review.googlesource.com/c/sdk/+/142155) involved creating the method extractors for all torn off methods up front, during the dispatch table layout computation. This had the side effect of making these method extractors inlineable.

This in turn caused a size regression of around 1% in Flutter apps due to many inlined method extractors.

It could be worth taking a look at these in connection with the inlining heuristics work.

**Comment by mkustermann** [comment]
@sstrickl For some important customer this has increased code size by 1.7%. Letting @askeksa-google look into it, since his CL also uncovered this issue.
