### ISSUE TITLE
Analyzer allows null to be assigned to `Never`

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41645]
The following code should be an error in an opted in library: the analyzer reports no errors.

```dart
Never x = throw "error";
void foo() {
   x = null;
 }
```

Tested in tests/language/nnbd/never/never_null_assignability_strong_test.dart landed in https://dart-review.googlesource.com/c/sdk/+/143040 .

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/144811
