### ISSUE TITLE
Reporting this fatal error at Android Studio

### ISSUE THREAD

**Issue by mikechari** [dart-lang/sdk#41658]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.7.2`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.2, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

1587778349634 => {"id":"7","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["C:\\Petrolog\\Flutter\\MikeChaRi\\neibor\\lib\\main.dart","C:\\Petrolog\\Flutter\\MikeChaRi\\neibo
1587778349650 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[]}}
1587778349650 <= {"id":"1"}
1587778349661 <= {"id":"2"}
1587778349666 <= {"id":"3","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1587778350314 <= {"event":"analysis.errors","params":{"file":"C:\\Petrolog\\Flutter\\MikeChaRi\\neibor\\pubspec.yaml","errors":[]}}
1587778350319 <= {"event":"analysis.errors","params":{"file":"C:\\Petrolog\\Flutter\\MikeChaRi\\neibor\\android\\app\\src\\debug\\AndroidManifest.xml","errors":[]}}
1587778350321 <= {"event":"analysis.errors","params":{"file":"C:\\Petrolog\\Flutter\\MikeChaRi\\neibor\\android\\app\\src\\main\\AndroidManifest.xml","errors":[]}}
1587778350326 <= {"event":"analysis.errors","params":{"file":"C:\\Petrolog\\Flutter\\MikeChaRi\\neibor\\android\\app\\src\\profile\\AndroidManifest.xml","errors":[]}}
1587778350580 <= {"id":"4"}
1587778350583 <= {"id":"5"}
1587778350593 <= {"id":"6"}
1587778350597 <= {"id":"7"}
1587778350598 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[]}}
1587778352994 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":0,"uri":"package:neybor/widgets/text_message.dart","items":[{"label":"TextMessage","declaringLibraryUri"
1587778353004 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1,"uri":"package:google_sign_in/widgets.dart","items":[{"label":"GoogleUserCircleAvatar","declaringLibra
1587778353022 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":2,"uri":"package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart","items":[{"la
1587778353041 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":5,"uri":"package:google_sign_in/google_sign_in.dart","items":[{"label":"GoogleUserCircleAvatar","declari
1587778353051 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":7,"uri":"package:quiver/core.dart","items":[{"label":"hashObjects","declaringLibraryUri":"package:quiver
1587778353061 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":10,"uri":"package:firebase_core_platform_interface/firebase_core_platform_interface.dart","items":[{"lab
1587778353069 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":14,"uri":"package:firebase_core/firebase_core.dart","items":[{"label":"FirebaseApp","declaringLibraryUri
1587778353076 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":16,"uri":"package:plugin_platform_interface/plugin_platform_interface.dart","items":[{"label":"MockPlatf
1587778353091 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":17,"uri":"package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart","items":[{"lab
1587778353121 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":20,"uri":"package:firebase_auth/firebase_auth.dart","items":[{"label":"IdTokenResult","declaringLibraryU
1587778353126 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":36,"uri":"package:neybor/models/firebase_login.dart","items":[{"label":"user","declaringLibraryUri":"pac
1587778353128 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":37,"uri":"package:neybor/screens/register_screen.dart","items":[{"label":"RegisterScreen","declaringLibr
1587778353137 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":38,"uri":"package:nested/nested.dart","items":[{"label":"Nested","declaringLibraryUri":"package:nested/n
1587778353175 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":39,"uri":"package:provider/provider.dart","items":[{"label":"Selector","declaringLibraryUri":"package:pr
1587778353181 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":50,"uri":"package:neybor/models/data.dart","items":[{"label":"Data","declaringLibraryUri":"package:neybo
1587778353286 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":65,"uri":"dart:nativewrappers","items":[]}],"removedLibraries":[]}}
```

**Comment by devoncarew** [comment]
I believe this is a dup of https://github.com/dart-lang/sdk/issues/38405.

cc @stereotype441 for whether we think this issue has been addressed.

**Comment by mikechari** [comment]
Any updates on this one? i can no longer program flutter in android studio, is there anything else that i can try?, kinda stuck here.

Thanks a lot

**Comment by MichaelRFairhurst** [comment]
Hi @mikechari, it looks like you're using an older version of Dart:

```Dart analysis server, SDK version 2.7.2```

Can you try upgrading flutter and see if the latest versions still crash for your?

**Comment by mikechari** [comment]
I tried to upload flutter but it says that i have the latest version:

![image](https://user-images.githubusercontent.com/64236324/80626752-2698a500-8a0c-11ea-9998-234eba4fdc10.png)

Also tried using the windows console:

![image](https://user-images.githubusercontent.com/64236324/80626883-534cbc80-8a0c-11ea-9c90-f06e08470069.png)

In both cases i had to use --force

Thanks for the reply

**Comment by devoncarew** [comment]
@mikechari - that is the most recent stable version of flutter. To try out a newer version, you'd need to change the channel that you're on:

```
flutter channel beta
flutter upgrade
```

If you could then re-test (and verify the version of flutter you're on via `flutter --version`) that would be great.

**Comment by mikechari** [comment]
That fixed the problem: 

![image](https://user-images.githubusercontent.com/64236324/80630695-db819080-8a11-11ea-993b-43a54aeee11c.png)

I will remain in beta for now then?

Thanks a lot for the support!

**Comment by mikechari** [comment]
Now i did a roll back to the latest stable version with `flutter channel stable
flutter upgrade --force`

And the error is not coming back, and i am on the stable version again, some how the flutter sdk got messed up and with a change of versions it got fixed.

**Comment by MichaelRFairhurst** [comment]
I will mark this as closed. Since it seems to perhaps come and go, please re-open if you experience this on bleeding edge. It's likely the same issue as the one linked, which was fixed between the last stable release and bleeding edge.

**Comment by brandondiamond** [comment]
I'm hitting this, too. It seems to be a legit bug in the dart analyzer. My disk filled up just before I hit this error; perhaps that's a contributing factor -- seems that something is corrupted.

## Dart analysis issue

NoSuchMethodError: The getter 'isEof' was called on null.

## Version information

- Dart SDK 2.8.3
- Dart IntelliJ 192.8052
- Android Studio 3.6.3
- Mac OS X 10.15.4

## Details

NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof

```
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## Debug log

```
1591134770262 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":788,"uri":...
1591134770266 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":789,"uri":...
1591134770268 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":790,"uri":...
1591134770272 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":791,"uri":...
1591134770274 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":792,"uri":...
1591134770278 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":793,"uri":...
1591134770279 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":794,"uri":...
1591134770283 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":750,"uri":...
1591134770284 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":795,"uri":...
1591134770286 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":796,"uri":...
1591134770323 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":797,"uri":...
1591134770337 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":798,"uri":...
1591134770339 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":799,"uri":...
1591134770355 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":800,"uri":...
1591134770355 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":801,"uri":...
1591134770357 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":802,"uri":...
1591134770362 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":803,"uri":...
1591134770362 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":804,"uri":...
1591134770362 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":805,"uri":...
1591134770366 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":806,"uri":...
1591134770366 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":807,"uri":...
1591134770371 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":808,"uri":...
1591134770376 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":809,"uri":...
1591134770376 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":810,"uri":...
1591134770377 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":811,"uri":...
1591134770382 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":812,"uri":...
1591134770383 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":813,"uri":...
1591134770425 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":814,"uri":...
1591134770433 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":815,"uri":...
1591134770461 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":816,"uri":...
```

**Comment by brandondiamond** [comment]
It seems that the IDE can insert invalid characters into certain files (i.e., null) which breaks the analyzer. Rebuilding the file that was open when the IDE crashed seems to be helping...

**Comment by brandondiamond** [comment]
Yup, that did it.

FWIW, this was a pretty unpleasant crash. There aren't many resources on the web dealing with this issue -- I think it's worth the effort to dig into the analysis server and try to report the exact file, line, and column with the unexpected token. It would also be great to include instructions: "It's possible your file was corrupted on disk and includes an invalid character. Please inspect the file to ensure that only valid characters and encodings are included."

**Comment by srawlins** [comment]
Closing as stale. Please re-open if you see this issue again on a recent version of Dart.
