### ISSUE TITLE
DomException is not an Object according to dartjs under NNBD

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#41654]
Take the following program:

```dart
main() {
  try {
    window.crypto.getRandomValues(Float32List(100));
  } on Object catch (e) {
    print("Caught Object");
  } catch (e) {
    print("Not Object?! $e");
  }
}
```

Compile it with dart2js as opted in to NNBD and run it in a browser. I would expect the first catch clause to capture the exception, but it does not. Instead, the second clause is the one that gets the thrown DomException.

**Comment by fishythefish** [comment]
Should be fixed by 7ac53f182561a35ad932f39f1183988bb23ef1ff.
