### ISSUE TITLE
HTML TouchEvent not firing as expected 

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#41653]
@srujzs 

This is a minimal repro from a test blocking the NNBD unfork. Repros in both DDC and dart2js.

```dart 
import 'dart:html';
import 'dart:js' as js;

main() {
  var touchKey = 'touch-key';
  js.context[touchKey] = false;

  document.onTouchStart.first.whenComplete(() {
    js.context[touchKey] = true;
  });

  print(js.context[touchKey]);
  document.dispatchEvent(TouchEvent('touchstart'));
  print(js.context[touchKey]);
}
```

Compiled with the existing SDK it prints:
```
false
true
```

Compiled with the NNBD SDK running in weak mode it prints:
```
false
false
```

**Comment by srujzs** [comment]
Seems like it's not tied to `TouchEvent`s specifically either, I can reproduce this with other `EventStream`s. I'm still digging through this, and trying to figure out where `first` fails and why on `EventStream`s with different Events.

**Comment by franklinyow** [comment]
Any update?

**Comment by srujzs** [comment]
Yup, found the root cause in https://github.com/dart-lang/sdk/blob/8c96812bec49947e2e70c788568fac9e36d33814/tools/dom/nnbd_src/EventStreamProvider.dart#L250. The return value used to be null and is now returning a void Future instead, and now the subscription never completes. I'm still trying to dig deeper and figure out how to fix this.

**Comment by natebosch** [comment]
I think it was a bug that this code ever worked as it did. It should not be possible to rely on _synchronous_ side effects for a stream listener.

My preference would be to fix the code in question rather than retain the bug.

**Comment by vsmenon** [comment]
Is the fix here in the sdk or in internal test code?

**Comment by vsmenon** [comment]
I.e., is there anything to fix in the SDK still?

**Comment by nshahan** [comment]
Our plan is to land a change to the SDK that restores the original behavior only when running in weak mode. This will unblock the unfork and gives us more time to investigate and fix the client code that accidentally depends on the synchronous timing.

**Comment by srujzs** [comment]
Change is pushed in, will document in CHANGELOG and mark this as fixed.
