### ISSUE TITLE
[analysis_server] Completion not working on named parameters

### ISSUE THREAD

**Issue by ericdallo** [dart-lang/sdk#41652]
#### Info
* Dart SDK Version: `Dart VM version: 2.8.0-dev.10.0 (Thu Feb 20 16:03:17 2020 +0100) on "linux_x64"`
* OS: `Linux` - `NixOS`
#### Bug
As mentioned [here](https://github.com/emacs-lsp/lsp-mode/issues/1608#issuecomment-619121207), it looks like the analysis_server for LSP is not working for completions on named parameters.

![](https://user-images.githubusercontent.com/7820865/80236115-10b46a00-8631-11ea-9e1d-68a71fdffc1a.png)

<details>
<summary><b>Server error log</b></summary>
<br>
<pre>
An error occurred while handling textDocument/completion request: RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
#1      getDeclarationCompletionDetail (package:analysis_server/src/lsp/mapping.dart:478:22)
#2      declarationToCompletionItem (package:analysis_server/src/lsp/mapping.dart:237:5)
#3      CompletionHandler._getItems.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:230:26)
#4      MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#5      List.addAll (dart:core-patch/growable_array.dart:201:17)
#6      CompletionHandler._getItems.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:243:17)
#7      List.forEach (dart:core-patch/growable_array.dart:282:8)
#8      CompletionHandler._getItems (package:analysis_server/src/lsp/handlers/handler_completion.dart:187:30)
<asynchronous suspension>
#9      CompletionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:83:41)
#10     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#11     CompletionHandler.handle (package:analysis_server/src/lsp/handlers/handler_completion.dart:83:19)
<asynchronous suspension>
#12     MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:101:12)
#13     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:140:36)
<asynchronous suspension>
#14     LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:251:49)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#16     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:246:50)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     LspAnalysisServer.handleMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:245:5)
#22     LspByteStreamServerChannel._readMessage.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:87:18)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#24     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:83:47)
#25     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:55:24)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#30     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#31     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#32     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#33     _rootRun (dart:async/zone.dart:1122:38)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#37     _rootRun (dart:async/zone.dart:1126:13)
#38     _CustomZone.run (dart:async/zone.dart:1023:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

An error occurred while handling textDocument/completion request: RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
#1      getDeclarationCompletionDetail (package:analysis_server/src/lsp/mapping.dart:478:22)
#2      declarationToCompletionItem (package:analysis_server/src/lsp/mapping.dart:237:5)
#3      CompletionHandler._getItems.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:230:26)
#4      MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#5      List.addAll (dart:core-patch/growable_array.dart:201:17)
#6      CompletionHandler._getItems.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:243:17)
#7      List.forEach (dart:core-patch/growable_array.dart:282:8)
#8      CompletionHandler._getItems (package:analysis_server/src/lsp/handlers/handler_completion.dart:187:30)
<asynchronous suspension>
#9      CompletionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:83:41)
#10     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#11     CompletionHandler.handle (package:analysis_server/src/lsp/handlers/handler_completion.dart:83:19)
<asynchronous suspension>
#12     MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:101:12)
#13     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:140:36)
<asynchronous suspension>
#14     LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:251:49)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#16     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:246:50)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     LspAnalysisServer.handleMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:245:5)
#22     LspByteStreamServerChannel._readMessage.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:87:18)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#24     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:83:47)
#25     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:55:24)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#30     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#31     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#32     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#33     _rootRun (dart:async/zone.dart:1122:38)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#37     _rootRun (dart:async/zone.dart:1126:13)
#38     _CustomZone.run (dart:async/zone.dart:1023:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

An error occurred while handling textDocument/completion request: RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
#1      getDeclarationCompletionDetail (package:analysis_server/src/lsp/mapping.dart:478:22)
#2      declarationToCompletionItem (package:analysis_server/src/lsp/mapping.dart:237:5)
#3      CompletionHandler._getItems.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:230:26)
#4      MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#5      List.addAll (dart:core-patch/growable_array.dart:201:17)
#6      CompletionHandler._getItems.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:243:17)
#7      List.forEach (dart:core-patch/growable_array.dart:282:8)
#8      CompletionHandler._getItems (package:analysis_server/src/lsp/handlers/handler_completion.dart:187:30)
<asynchronous suspension>
#9      CompletionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:83:41)
#10     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#11     CompletionHandler.handle (package:analysis_server/src/lsp/handlers/handler_completion.dart:83:19)
<asynchronous suspension>
#12     MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:101:12)
#13     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:140:36)
<asynchronous suspension>
#14     LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:251:49)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#16     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:246:50)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     LspAnalysisServer.handleMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:245:5)
#22     LspByteStreamServerChannel._readMessage.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:87:18)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#24     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:83:47)
#25     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:55:24)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#30     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#31     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#32     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#33     _rootRun (dart:async/zone.dart:1122:38)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#37     _rootRun (dart:async/zone.dart:1126:13)
#38     _CustomZone.run (dart:async/zone.dart:1023:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
</pre>
</details>

This is impacting [lsp-dart](https://github.com/emacs-lsp/lsp-dart) for Emacs :pensive:

**Comment by ericdallo** [comment]
c/c @DanTup

**Comment by DanTup** [comment]
Thanks for the report! It looks like this has been fixed in v2.8.0-dev.11.0 and you're on v2.8.0-dev.10.0:

https://github.com/dart-lang/sdk/commit/d1689fe748aaec2b27fbed4c269ec89550bf9776

Please try a newer version of the SDK and let me know if you're still seeing this.

**Comment by ericdallo** [comment]
Thanks, I'll give a try!

**Comment by ericdallo** [comment]
Tested on `2.9.0-4.0.dev` and it works, thanks!

**Comment by DanTup** [comment]
Great, thanks for confirming!
