### ISSUE TITLE
no code completion suggestions for the `on` type of an extension class definition

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#41665]
I don't see code completion suggestions for the `on` type of an extension methods class definition:

<img width="512" alt="Screen Shot 2020-04-25 at 12 44 29 PM" src="https://user-images.githubusercontent.com/1269969/80289349-b380ed00-86f2-11ea-8819-03bd3cbbd604.png">

This is for

```
Flutter 1.18.0-9.0.pre.12 • channel master • https://github.com/flutter/flutter
Tools • Dart 2.9.0 (build 2.9.0-3.0.dev 94178e920e)
```

**Comment by bwilkerson** [comment]
@jwren

**Comment by jwren** [comment]
Looking at this now.

**Comment by jwren** [comment]
https://dart-review.googlesource.com/c/sdk/+/144980
