### ISSUE TITLE
No promotion via initialization 

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41669]
Flow analysis [specification](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md#promotion) reads

> We say that a variable x is promotable via initialization given variable model VM if x is a local variable (not a formal parameter) and:

> VM = VariableModel(declared, promoted, tested, assigned, unassigned, captured)
> and captured is false
> and promoted is empty
> and x is declared with no explicit type and no initializer
> and assigned is false and unassigned is true
> 

But it doesn't happen

```dart
class S {}
class T extends S {
  int foo() => 42;
}

main() {
  var x;
  x = new T();
  x.foo();  // Ok
  x.bar();  // Expecting an error here
}
```
The code above has no compile time error in CFE and has no issues in analyzer. Only runtime error in CFE. That means that `x` is not promoted to `T` and still has type `dynamic`. There must be a type promotion here

Tested with `dartanalyzer version 2.9.0-2.0.dev`

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/145502 will fix this.
