### ISSUE TITLE
Analyzer: Wrong error message about `async` return type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41670]
Consider the following library:

```dart
Future<bool> f() async => Future<int>.value(42);
```

`dartanalyzer --enable-experiment=non-nullable` from commit d5310cb2d6c781e4c456aced9956c9f6a74f8fb0 (of today) responds with the following error message:

```
ERROR|STATIC_TYPE_WARNING|RETURN_OF_INVALID_TYPE|/usr/local/google/home/eernst/lang/dart/scratch/202004/n039.dart|1|27|21|A value of type 'int' can't be returned from function 'f' because it has a return type of 'bool'.
```

This error message indicates that the return type of `f` is `bool`, but it is actually declared as `Future<bool>`, so that error message needs to be adjusted. The same behavior exists also without `--enable-experiment=non-nullable`.

Discussions about `async` returns are ongoing, cf. https://github.com/dart-lang/language/pull/941. However, I do not think that the outcome of that PR will invalidate a fix for this issue.

**Comment by scheglov** [comment]
With 08614701972af690fcd9b9b70516b26d4d3cfbd0 analyzer now reports:
`ERROR|STATIC_TYPE_WARNING|RETURN_OF_INVALID_TYPE|/Users/scheglov/dart/test/bin/test.dart|1|27|21|A value of type 'Future<int>' can't be returned from function 'f' because it has a return type of 'Future<bool>'.`
