### ISSUE TITLE
Add option to analyzer, to skip rules

### ISSUE THREAD

**Issue by HerrNiklasRaab** [dart-lang/sdk#41673]
Hey,

we have the analyzer in our git pre-push hook, but there seems to be nowhere to exclude some rules from the command line. For example, we want to skip the rule `deprecated_member_use_from_same_package`, but we don't want to exclude the rule in our analysis file, because it should still be visible in the ide.

Anyone's thoughts about this?

Thanks,

Niklas

**Comment by bwilkerson** [comment]
The command-line analyzer allows you to specify an analysis options file that is different from the one found automatically by the IDE by using the `--options` flag. That allows you to have two separate sets of options for command-line use and IDE use.
