### ISSUE TITLE
Docs - Incorrect format for VM experiment flag

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#41676]
https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md#flag-format-for-cli-based-tools

Our docs show:

```
dart --enable-experiment super-mixins
```

This format does not work on the VM. It should be:

```
dart --enable-experiment=super-mixins
```

**Comment by cv692001** [comment]
Hey @natebosch I am interested can I contribute in this :)

**Comment by natebosch** [comment]
I suspect we could take a contribution for this 😄 

See https://github.com/dart-lang/sdk/blob/master/CONTRIBUTING.md for docs on getting started.

**Comment by cv692001** [comment]
Okay @natebosch  , So can you please explain what can be the reason behind this so that I can get a better idea  also if contribution will not be accepted it is better to close the issue  👍

**Comment by natebosch** [comment]
> So can you please explain what can be the reason behind this so that I can get a better idea

If I understand the question you are asking why it was originally written without the `=` in those docs? I think the author may have assumed it would work that way.

> if contribution will not be accepted it is better to close the issue

I don't see any reason why we wouldn't be able to accept a fix for this, should be a small change. If you don't want to go through the overhead of getting set up to contribute to the SDK I could also submit the patch for this (not sure why I didn't when I filed, I may have been in a rush for something else and forgot about it).

**Comment by cv692001** [comment]
@natebosch  Okay I will be happy to do it 👍 . So , can you please assign this to me I will complete this As Soon As Possible !

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-lang/sdk/commit/ec51b7a866275e84da091c718b7dd172fffcdfe1
