### ISSUE TITLE
Migration: flutter still crashes on a strange usage of parts for privacy

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41685]
animated_icons_private_test.dart in package:flutter still crashes

from trial_migration:

```
  #0      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:358:7) (/home/mfairhurst/projects/dart/flutter/packages/flutter x11)
```

This is because it uses an older approach of getting library level privacy out of part files, by using them in strange ways. I believe the issue is that there is one library that refers to a part, but multiple parts that refer to that library. This is used to access private fields and mock out other behavior, and its challenging or impossible for the migration tool to handle because the migration tool sees it as two different migrations for one file.

I believe @Hixie has said it seems like it should be OK to manually migrate these files. Nevertheless, until that happens, we can consider this an open issue. Filing this so its in our planning etc.

**Comment by leafpetersen** [comment]
Is this still an issue?

**Comment by mit-mit** [comment]
@MichaelRFairhurst ?

**Comment by franklinyow** [comment]
Any update on this? @MichaelRFairhurst

**Comment by MichaelRFairhurst** [comment]
I don't know if this is still an issue but I don't think it's a risk.

To be clear: the tool crashes on _one file_ (or something) while _migrating_ flutter. And Hixie confirmed it was ok to migrate that one file (or so) by hand.

Once it is migrated, we will fundamentally have the same issue for those who abuse `part`s in other projects: they'll have to migrate the abuses by hand.

The abuse in question is:

a.dart
```dart
library abuse;
part 'part.dart';

...
```

b.dart
```
library abuse;
part 'part.dart';

...
```

part.dart
```
part of abuse;
// the analysis of this file depends on the context, whether its being
// referenced from a.dart or b.dart. We cannot create one migration
// for this file. We cannot create two. What to do here is unclear.
```

I believe the answer is that we don't want to support this, we want to encourage people to use different patterns to accomplish whatever they're accomplishing. Certainly if users hit this issue commonly in the wild (not observed as such so far) we can reconsider, and try crazy ideas such as copying `part.dart` into two different migrated files (`part_from_a.dart`, `part_from_b.dart`).

I'm not working on the migration tool any more though. If this has been an issue or has been fixed or there's some new reason why it's a priority, then @stereotype441 or maybe @srawlins would know better than me.

**Comment by devoncarew** [comment]
Thanks for the update!

Given the comment above, I don't think this is a beta blocker; I'll update this in the epics.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
