### ISSUE TITLE
dart:html Element.setInnerHtml signature accepts null but throws if passed

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#41699]
The new signature is in the Null Safe SDK is
```dart
void setInnerHtml(String? html,
      {NodeValidator? validator, NodeTreeSanitizer? treeSanitizer})
```

But within the body `html!` appears which causes an error when you pass null.

Repro:

```dart
import 'dart:html';

main() {
  document.body!.setInnerHtml(null);
}
```

Compiling with DDC and running in a browser will cause the error:
`Uncaught Error: NoSuchMethodError: '<Unexpected Null Value>'`

cc @srujzs

**Comment by nshahan** [comment]
I forgot to mention it looks like with the current SDK this would result in the string "null" being inserted as the inner HTML.

**Comment by srujzs** [comment]
Thanks for filing this. We've discussed potentially either clearing the `innerHtml` string or forwarding the `null` string to `createFragment` but it's not sure what the effects of either of these decisions are. It's possible `createFragment` is typed incorrectly as well.
