### ISSUE TITLE
DDC has no compile time null safety mode flag

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#41694]
DDC has been relying on a runtime mode flag for null safety that gets set by all the build/test systems and bootstrapping logic but isn't using any flag for compile time.

DDC doesn't need this information itself but should pass the mode along to the CFE to ensure correct compile time semantics are enforced. 

The CFE defaults to weak mode. Other backends are using the flag `--null-safety` to signal the strong/strict null safety mode.

**Comment by leafpetersen** [comment]
Note that @mit-mit recently filed an issue to change the name of the null safety flag, so if you're visiting that code consider folding that work into it.  :)

**Comment by mit-mit** [comment]
https://github.com/dart-lang/sdk/issues/41497

**Comment by rileyporter** [comment]
Affects DDC strong mode failing these 3 co19 tests:

- [tests/co19/LanguageFeatures/nnbd/const_evaluation_A01_t18](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/const_evaluation_A01_t18.dart), failing [logs](https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/3098/co19/LanguageFeatures/nnbd/const_evaluation_A01_t18)
- [tests/co19/LanguageFeatures/nnbd/const_evaluation_A01_t12](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/const_evaluation_A01_t12.dart), failing [logs](https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/3098/co19/LanguageFeatures/nnbd/const_evaluation_A01_t12)
- [tests/co19/LanguageFeatures/nnbd/const_evaluation_A01_t10](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/const_evaluation_A01_t10.dart), failing [logs](https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/3098/co19/LanguageFeatures/nnbd/const_evaluation_A01_t10)

**Comment by mit-mit** [comment]
@nshahan any news on this one? Is this on track for completion this week?

**Comment by nshahan** [comment]
@mit-mit I should be landing the necessary bits today.
https://dart-review.googlesource.com/c/sdk/+/146962
https://dart-review.googlesource.com/c/sdk/+/149080
