### ISSUE TITLE
Bad State: Future already completed when using FileSystemEntity.watch() on linux

### ISSUE THREAD

**Issue by ja2375** [dart-lang/sdk#41690]
I am using Debian to deploy a dart console app and it is throwing an exception.

This is my code:
```
final watcher = File('file.txt').watch();
    watcher.listen((event) async {
      if(event.type == FileSystemEvent.create) {
        // Some unrelated code here...
      }
    });
```

This code works just fine on macOS (where i'm actually coding and testing), but it throws this exception when it is deployed to a debian 10 server:
```
Unhandled exception:
Bad state: Future already completed
#0      _Completer.completeError (dart:async/future_impl.dart:23:31)
#1      ApplicationIsolateSupervisor._handleIsolateException (package:aqueduct/src/application/isolate_supervisor.dart:129:24)
#2      ApplicationIsolateSupervisor.listener (package:aqueduct/src/application/isolate_supervisor.dart:102:7)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#7      _StreamController._add (dart:async/stream_controller.dart:642:7)
#8      _StreamController.add (dart:async/stream_controller.dart:588:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
Is this a bug? As per the [docs](https://api.flutter.dev/flutter/dart-io/FileSystemEntity/watch.html), it says that detecting file creation is supported on linux. And FYI i installed the inotify-tools package (maybe i didn't install it rthe right way?).

Dart version installed on the debian server:
`Dart VM version: 2.7.2 (Unknown timestamp) on "linux_x64"`

**Comment by julemand101** [comment]
Are the file your are watching already on the filesystem or is it going to be created at some point?

**Comment by ja2375** [comment]
It will be created at some point in the future. The file does not exist when the application is first started.

**Comment by julemand101** [comment]
Well, there is your problem. The Linux kernel inotify API does not support watching a specific full path to a file there does not exists yet. There are a more detailed answer why here:
https://unix.stackexchange.com/questions/154004/can-inotify-be-used-to-watch-for-a-specific-file-to-be-created-without-monitorin

Instead, you need to watch the directory and filter out other file creations.

**Comment by ja2375** [comment]
OK, many many thanks for your help!!
