### ISSUE TITLE
TypeError: Instance of 'cp': type 'cp' is not a subtype of type 'minified:n'

### ISSUE THREAD

**Issue by insinfo** [dart-lang/sdk#41708]
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "windows_x64"
 Windows 10 , macOS Catalina, or Linux Debian 10
 Chrome 81.0.4044.122 64 bits

EXCEPTION TypeError on dart2js

webdev serve --hostname localhost --release

VM3327 main.dart.js:5232 EXCEPTION: TypeError: Instance of 'cp': type 'cp' is not a subtype of type 'minified:n'
STACKTRACE: 
TypeError: Instance of 'cp': type 'cp' is not a subtype of type 'minified:n'
    at Object.b (http://localhost:8080/main.dart.js:193:3)
    at Object.m (http://localhost:8080/main.dart.js:545:48)
    at eI.$0 (http://localhost:8080/main.dart.js:5788:34)
    at hJ.$0 (http://localhost:8080/main.dart.js:5975:14)
    at i9.k4 [as $1$4] (http://localhost:8080/main.dart.js:1066:9)
    at b9.cr (http://localhost:8080/main.dart.js:5916:79)
    at Object.eval (eval at lf (http://localhost:8080/main.dart.js:333:8), <anonymous>:3:43)
    at j0.C (http://localhost:8080/main.dart.js:3472:79)
    at j0.W (http://localhost:8080/main.dart.js:3440:10)
    at eJ.$1 (http://localhost:8080/main.dart.js:5785:5)

$1 @ VM3327 main.dart.js:5232
$1 @ VM3327 main.dart.js:5984
k5 @ VM3327 main.dart.js:1078
ct @ VM3327 main.dart.js:5926
eval @ VM3359:3
a5 @ VM3327 main.dart.js:3479
aU @ VM3327 main.dart.js:3446
ai @ VM3327 main.dart.js:3356
bU @ VM3327 main.dart.js:3340
ai @ VM3327 main.dart.js:3093
k @ VM3327 main.dart.js:3059
eu @ VM3327 main.dart.js:5944
eval @ VM3351:3
a2 @ VM3327 main.dart.js:3464
W @ VM3327 main.dart.js:3442
$1 @ VM3327 main.dart.js:5785
oj @ VM3327 main.dart.js:266
(anonymous) @ VM3327 main.dart.js:274
Navigated to http://localhost:8080/?

project for reproducer bug
https://github.com/insinfo/angular_form_bug

the exception occurs when you click save

### It works:

Microsoft Edge 44.18362.449.0 Windows 10 64-bit;
Firefox 72.0.2 64-bit Windows 10 64-bit;
Firefox Developer 72.0b5 64-bit Windows 10 64-bit;
Internet Explorer 11.657.18362.0 Windows 10 64-bit
Safari 5.1.7 (7534.57.2) Windows 10 64-bit
Google Chrome iphone 6S ios 13.3.1
Google Chrome Linux Ubuntu 18
Google Chrome Android 9
### Does not work:

New Microsoft Edge 81.0.416.64 Windows 10 64-bit
Google Chrome 81.0.4044.122 64-bit Windows 10 64-bit
Brave 1.7.98 Chromium: 81.0.4044.113 64-bit Windows 10 64-bit
Opera 68.0.3618.63 Windows 10 64-bit
Vivaldi  3.0.1874.33 64-bit Windows 10 64-bit
Firefox  75.0 64bits Linux Ubuntu 18

**Comment by thiagosantoscunha** [comment]
I had the same problem. I did the test using Angular / Typescript rehearsing a scenario similar to the previous comment sent by @insinfo

I will share the scenario on github, and you can open it on Gitpod if you wish. But, in summary, and I submit the forms through ** FormsModule **, and also another scenario with ** ReactiveFormsModule **.

Test project:
[https://github.com/codenome-trainings/cenario](https://github.com/codenome-trainings/cenario
)
### Note!!! Important!!!
It seems that there was a change in the new one in Chrome 81, and it needs to be resolved as soon as possible at the Angular / Dart core level. Many applications are breaking because of this, and I will need to overwrite an event in each project. What appears to be a unnecessary patches.

**Comment by sigmundch** [comment]
Thank you @insinfo and @thiagosantoscunha for your comments.

As @ganigeorgiev mentioned in the other bug (https://github.com/dart-lang/angular/issues/1891), a fix was landed has been released in 2.8.0-dev.20.7 . If you find it hard to update to that version at this time, there is a workaround available on this comment: https://github.com/dart-lang/sdk/issues/40901#issuecomment-611102767

**Comment by sigmundch** [comment]
Oops, mean to close this with the last comment.
