### ISSUE TITLE
Test that HTTP header values are decoded as Latin-1

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#41706]
The accidental breaking change in https://github.com/dart-lang/sdk/issues/41688 happened because there is no dart:_http test that checks that our parser decodes header values as Latin-1.

We need to make such a test to avoid a similar regression from happening unintentionally again.

Also, what does the HTTP specification say about the character set for header values?

cc @zichangg @mraleph

**Comment by zichangg** [comment]
According to [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2.4),
>    Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
   through use of [RFC2047] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [USASCII].
   Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.

**Comment by sortie** [comment]
In that case, I recommend we still add a test that Dart decodes as ISO-8859-1 as that's the behavior we implement and we won't want to break it unintentionally. Can you do that?
