### ISSUE TITLE
nhandled exception: Bad state: StreamSink is bound to a stream #0      _StreamSinkImpl.close (dart:io/io_sink.dart:204:7)

### ISSUE THREAD

**Issue by kaisersakhi** [dart-lang/sdk#41707]
/*im trying to download from a link which is progressive 
and i want it to stop downloading on an event but it throws this exception.
but it downloads the file sucessfully*/

Unhandled exception:
Bad state: StreamSink is bound to a stream
#0      _StreamSinkImpl.close (dart:io/io_sink.dart:204:7)
#1      Mp3Downloader.stopDownload (package:DartLearning/Mp3Downlaoder.dart:27:20)
#2      main.<anonymous closure> (file:///E:/Projects/Online%20Library%20Management%20System/Online%20Library%20Management%20System/DartLearning/bin/main.dart:19:21)
#3      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by lrhn** [comment]
This seems to be working as intended. Calling `close` while an `addStream` is still active will give this result, not close the `addStream`.
I've been wanting to change that, allowing you to use `add`, `addError` and `close` during an `addStream`, but it has not been a high priority.
