### ISSUE TITLE
[CP] Please merge #64c9984ecfd531eb381a56eacac8b8b8fc83dfb6 into [beta/stable] channel

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#41701]
**commit(s) to merge**: https://dart-review.googlesource.com/c/sdk/+/145244

*NOTE*: Update: landed

**merge instructions**: clean merge or patch CL

**reason**: Unintended breaking change (see https://github.com/dart-lang/sdk/issues/41688).

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by sortie** [comment]
64c9984ecfd531eb381a56eacac8b8b8fc83dfb6 has landed and this cherry-pick can go ahead.

**Comment by franklinyow** [comment]
Marked cp-approved as no objection in Virtual Scrum meeting
@athomas FYI

**Comment by pcsosinski** [comment]
approved from Flutter standpoint

**Comment by athomas** [comment]
This will go straight to stable.

**Comment by athomas** [comment]
This has been merged to stable in f12284ca12b9076dcc86f1524fefd57a7318ee52.
