### ISSUE TITLE
Migration: figure out the workflow if analysis errors occur during rerun

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41712]
If the user invokes the migration tool on a package that has analysis errors, and they haven't specified `--ignore-errors` on the command line, the migration tool will print out a summary of the errors and abort migration.  However, if the user introduces an error after the migration tool has run, and then clicks "rerun", we don't check for errors.

We should surface the errors somehow in the migration preview so that the user isn't confused by incorrect results.

**Comment by srawlins** [comment]
Flutter devs have been hitting this repeatedly.
