### ISSUE TITLE
Tried to initialize from a previous compilation but the file was not self-contained. 

### ISSUE THREAD

**Issue by Linhof666** [dart-lang/sdk#41713]
Hi,
Developing a tutorial about Bloc, I've got the following warning

Compiler message:
Warning: Tried to initialize from a previous compilation (file:///Users/ericfillatre/AndroidStudioProjects/good_design_ex/build/testfile.dill.track.dill), but the file was not self-contained. This might be a bug.

Following instruction I sent you the file
[initialize_from.dill.gz]

**Comment by keertip** [comment]
@Linhof666, this looks like a flutter issue. Please open issue at [flutter/issues](https://github.com/flutter/flutter/issues) with more details.
