### ISSUE TITLE
Failures on "Add InternetAddress.tryParse"

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#41727]
There are new test failures on [Add InternetAddress.tryParse](https://github.com/dart-lang/sdk/commit/9b34bee90b69bb4f6c25c6c421bf25b31c7f7c09).

The tests
```
standalone_2/io/internet_address_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-mac-product-x64
dartk-mac-release-x64
```

**Comment by alexmarkov** [comment]
Failure log:

```
/===================================================================================\
| standalone_2/io/internet_address_test broke (Pass -> RuntimeError, expected Pass) |
\===================================================================================/

--- Command "vm" (took 01.000603s):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/internet_address_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.isNull(actual: <InternetAddress('01.02.03.04', IPv4)>) fails.
#0      Expect._fail (package:expect/expect.dart:679:5)
#1      Expect.isNull (package:expect/expect.dart:153:5)
#2      testTryParse (file:///b/s/w/ir/tests/standalone_2/io/internet_address_test.dart:120:10)
#3      main (file:///b/s/w/ir/tests/standalone_2/io/internet_address_test.dart:215:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-mac-release-x64 standalone_2/io/internet_address_test
```

**Comment by natebosch** [comment]
It looks like mac and linux have different behaviors around addresses with leading 0's.

This behavior difference applies also to the `InternetAddress` constructor. I think the best thing to do for now is to remove the conditions which are not identical across platforms. We'll need to decide if we want to try to remove this inconsistency.

cc @zichangg @lrhn

**Comment by zichangg** [comment]
Here is another case for different behaviors for underlying system. https://github.com/dart-lang/sdk/issues/41663

For this special case, we can format the string in dart side before passing into native calls. But I'm afraid there are too many inconsistencies. Most of them are very subtle and hard to find.

**Comment by lrhn** [comment]
I'd prefer to just require a strict input format (no unnecessary leading zeros), and reject bad inputs early, before passing them to native code.
It's usually never a good idea to change user input. If nothing else, it makes it hard to report errors afterwards, if the errors are reported on a different string than what the user provided.
