### ISSUE TITLE
Analyzer: Implement change in static checks on `e1 == e2`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41724]
The update to the static analysis of equality expressions in dart-lang/language#940 requires an update to the implementation of the analyzer in the situation where the left operand has a type which is nullable, and whose non-nullable interface has a non-`Object` parameter type:

```dart
abstract class A { operator ==(covariant A other); }

void main() {
  A? a = null;
  a == a;
  a == true; // Compile-time error: `true` does not have type `A`.
}
```

The analyzer does not report this error.

CL https://dart-review.googlesource.com/c/sdk/+/145582 adds a test that contains several variants of the relevant situation.

**Comment by scheglov** [comment]
The spec says: "Consider an expression `e` of the form `e1 == e2` where the static type of
`e1` is `T1` and the static type of `e2` is `T2`. Let `S` be the type of the formal parameter of `operator ==` in the interface of **NonNull**(`T1`). It is a compile-time error unless `T2` is assignable to `S?`."

I don't understand the `NonNull` part. Is there semantic meaning for it? I understand that `operator==` will be invoked only when both `T1` and `T2` are not `null`. But is the type of the formal parameter of `operator==` different in `T1` and `NonNull(T1)`?

**Comment by eernstg** [comment]
I was surprised to see that @lrhn objected to this part. He'll create a new issue to discuss this.

The point is that it is possible for an `operator ==` to have a formal parameter type which is covariant, which can be used to get a static check that an object of a given type must be equals-tested against an object of some specific type:

```dart
class A { operator ==(covariant A other) => super == other; }
void main() => A() == 2;
```

Equality tests support null for both operands, so it's not unlikely that the left operand has type `A?` rather than `A`. The use of **NonNull** ensures that the compile-time error will also occur in this case (otherwise the statically known `operator ==` would be the one from `Object`). This is sound, as you mention, because we will only call that operator when the receiver isn't null.

**Comment by scheglov** [comment]
Ah, of course, otherwise we will find `operator==` from `Object`.
Thank you.

https://dart-review.googlesource.com/c/sdk/+/146040

**Comment by eernstg** [comment]
Thanks! The issue where we're sorting out this question is https://github.com/dart-lang/language/issues/949.
