### ISSUE TITLE
Autocomplete auto-enters override of operator== in many inappropriate places

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#41723]
At many places today, including inside a triple-quoted string, an automatic suggest for "==(other) { ... }" is popping up in an autocompletion list, and whenever I hit enter, it is automatically inserting an override for that function:
@override
  bool operator ==(other) {
    // TODO: implement ==
    return super == other;

At 4 or 5 different places today, both inside string literals and when writing getters, this has happened, and I have had spurious code inserted when I type a newline.

This is in Intellij IDEA 2019.3.3 (Ultimate Edition) build #IU-193.6494.35, with Dart SDK version 2.9.0-4.0.dev and Dart plugin 193.6494.35.

I have a screenshot available upon request.  The example place it happens is when typing the line
```
<material-chip
```
in
```
@Component(selector: 'filter-row', exports: [
  allConfigurationGroups
], directives: [
  coreDirectives,
  MaterialChipComponent,
  MaterialChipsComponent,

  NgModel,
], template: '''
  <material-chips>
   Filter: 
   <material-chip
      [removable]="false"
     >+</material-chip>
  </material-chips>
  <material-chip@override
  bool operator ==(other) {
    // TODO: implement ==
    return super == other;
  }
  }
''',
    styleUrls: [
    'package:angular_components/app_layout/layout.scss.css',
    'filter_row_component.css'
    ])
class FilterRowComponent {
  static const allConfigurationGroups = Filter.allConfigurationGroups;
...
```

@jwren

**Comment by jwren** [comment]
This was fixed yesterday with https://dart-review.googlesource.com/c/sdk/+/145481.  Thanks for reporting.
