### ISSUE TITLE
[CP] Please merge #5ed1850 into [stable] 2.7 channel

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#41726]
commit(s) to merge: 5ed1850

merge instructions: clean merge

reason: A recent update on all major browsers changed the event triggered on a submit button, and dart:html doesn't handle it properly. The cherry-pick fixes our implementation.

This issue has now been reported multiple times: https://github.com/dart-lang/sdk/issues/40901, https://github.com/dart-lang/angular/issues/1889, https://github.com/dart-lang/angular/issues/1881

We've seen this issue before and we previously merged this to the dev channel (https://github.com/dart-lang/sdk/issues/41446) only. I know we plan to release 2.8 shortly, but given the severity of the issue and how small the fix is, I'd like us to cherry-pick this also on 2.7 if that's possible (especially considering that 2.8 carries breaking changes as well, so upgrading is not as trivial as it would be to upgrade to 2.7.4).

/cc @vsmenon @kevmoo @mit-mit @whesse @athomas @franklinyow

**Comment by franklinyow** [comment]
Denied:  Technically complicated to support a hot fix from info-structure side.

**Comment by sigmundch** [comment]
Thanks for the discussion earlier today - for anyone following here, at this time 2.8 is already about to be released we don't have the right setup to release a hotfix in 2.7 simultaneously. The fix is alredy in the dev and beta channels, and there is a workaround available for users that need to remain in 2.7 a bit longer.
