### ISSUE TITLE
Why is String.length property not read-only?

### ISSUE THREAD

**Issue by kayvij** [dart-lang/sdk#41746]
So I had a mistake in my code where I added to the length property of the String like this:

str.length += new_length; 

And this ended up adding new_length many nulls into the String. 

It took me hours to debug this. 

Wondering, if this is a feature or a bug? Shouldn't length property be read-only and we should not be able to set it explicitly...

**Comment by lrhn** [comment]
`String.length` is read only. Are you thinking of `List.length`?

The latter is writable because that's one way to increase the length of a growable list. A fixed length list does not allow you to grow it (but it does allow you to try).

**Comment by kayvij** [comment]
Oops! my bad... it was a List, not a String. But it still leaves room for unintentional coding. May be the syntax for growing a list should be a bit different?

**Comment by kayvij** [comment]
I believe any length property should always be read-only..

**Comment by lrhn** [comment]
The length property of lists is still writable. It's much less useful with null-safety, and we might want to reconsider that in the future, but for now we are not changing the `List` interface.
