### ISSUE TITLE
Implement NNBD allow list for flutter tech preview (analyzer portion)

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41741]
In order to allow Flutter (and the packages it depends on) to ship a tech preview of their NNBD support, we need to have a allowlist that allows those packages to opt into NNBD even if the NNBD experiment flag isn't enabled (much in the same way that after unforking the SDK, the SDK libraries are considered opted in even if the experiment isn't enabled).  This issue tracks the analyzer work necessary to make that happen.

Note that we should coordinate with the front-end team (@johnniwinther FYI) so that we can share code as much as possible, and so that the allowlist is maintained in a single canonical location.

**Comment by kevmoo** [comment]
@stereotype441 – we should be working off the same list, right?

See https://github.com/dart-lang/sdk/issues/41538

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/148648

**Comment by scheglov** [comment]
Support in analyzer is done.

`lib/_internal/allowed_experiments.json` should be updated to include specific packages once we know what and when.
