### ISSUE TITLE
Dart HTTP Server Publish

### ISSUE THREAD

**Issue by Abdusin** [dart-lang/sdk#41742]
Hello everybody, i code a http server with dart and i have an linux server, how can i run my 'dart http server' in linux server

**Comment by num8er** [comment]
1. ISSUES page is for issues (bugs, feature requests) in repository, such questions should be asked in stackoverflow
2. You can deploy Your app in following services **AWS** (beanstalk, ec2), **Google Cloud** (Google Kubernetes Engine), Heroku
3. You can put Your app in **Docker container** and orchestrate it using **Docker Compose**
4. You can use `supervisord` tool
5. You can create `systemd` daemon
6. You can use `screen` tool and run Your app in "screened" terminal
7.  You can run it in background using `nohup`: `nohup your command here &`
