### ISSUE TITLE
[wiki] Kernel Documentation/Transformations and Linking > You do not have permission to update this wiki.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#41744]
Clicking on 'Transformations and Linking' [here](https://github.com/dart-lang/sdk/wiki/Kernel-Documentation)
leads to the root wiki page that says "You do not have permission to update this wiki."

Is this just a bug or Is this part of the wiki hidden from the public, if so, why?

**Comment by mraleph** [comment]
This wiki page does not exist - so when you click on it you are offered to create the content- but you don’t have permissions to create or edit - so you get an error.
