### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by ENGMElaraby** [dart-lang/sdk#41745]
## Version information

- `IDEA IU-201.7223.91`
- `2.7.2`
- `IU-201.7223.91, JRE 11.0.6+8-b765.40x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

**Comment by keertip** [comment]
@ENGMElaraby, there is not enough information here to proceed (no logs). Closing issue.
