### ISSUE TITLE
Iterable#take tolerates null

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#41743]
the following program
```dart
void main() {
  print([1, 2].take(null));
}
```
surprisingly prints (1, 2).  i expected it to throw.
nothing about the [take docs](https://api.dart.dev/stable/2.7.2/dart-core/Iterable/take.html) hint that it wouldn't throw nor what the behavior would be if given a null.  the param isn't optional.

in fact, the take docs seem to hint that it would throw - it says that it's implemented as
`TakeIterable<E>(this, count)` and, poking around `dart-sdk/lib/internal/iterable.dart` it seems like `TakeIterable`'s constructor is supposed to throw an `ArgumentError` if it's given a null.

i suspect that the docs are wrong and that `Iterable#take` is actually implemented as `SubListIterable`, which accepts a null.

but regardless of how it's implemented, it looks like a bug for `Iterable#take` to accept a null, especially considering that `TakeIterable` doesn't tolerate it.

> dart --version
Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"

**Comment by lrhn** [comment]
I shouldn't accept `null`.
