### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by sagarpatel115** [dart-lang/sdk#41754]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.7.2`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

**Comment by keertip** [comment]
@sagarpatel115 , sorry, there is not enough information here (no logs) to proceed. Closing issue.
