### ISSUE TITLE
Unexpected analyzer message when using unary minus and list access operators together

### ISSUE THREAD

**Issue by Blimster** [dart-lang/sdk#41759]
I have this code:
```
void main() {
  final a = <num>[1];
  final b = -a[0];
  print(b);
}
```
Additionally, implicit dynamic and implicit casts are disabled in `analysis_options.yaml`. 

Running dartanalyzer gives the message `Missing variable type for 'b'.`. Expected behavior is no message.

Executing the code prints `-1` as expected.

Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"

**Comment by srawlins** [comment]
Perhaps the same issue as https://github.com/dart-lang/sdk/issues/36055

**Comment by srawlins** [comment]
This has been fixed.
