### ISSUE TITLE
Migration tool should edit package_config.json

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41765]
The migration tool should set the language version in the new [package_config.json](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md) file.

I believe it should suss out _this_ package's name, find it in the file, and change the `languageVersion` field to something like 2.9.0, in order to enable Null Safety.

The goal is to allow users to begin running tests and `dartanalyzer` as soon as the migration tool exits.

**Comment by mit-mit** [comment]
I'm probably missing some basic detail, but why not just update the version in `pubspec.yaml` and have the update to `package_config.json` be written by `pub get`?

**Comment by srawlins** [comment]
It's nothing super exciting; editing `package_config.json` is just to do the same job that `pub get` would do. We can also instruct the user to run `pub get`.

**Comment by srawlins** [comment]
Done.
