### ISSUE TITLE
Type promotion broken when null check includes assignment

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#41762]
Simplified from some code in Observatory

```
class A {
 int foo() => 0;
}

A? getA() {
  return (new DateTime.now()).second == 0 ? null :new A();
}

main() {
  A? a;
  while ((a = getA()) != null) {
     print(a.foo());
  }
}
```

This was accepted last week, but today it wants `a!.foo()`.

**Comment by johnniwinther** [comment]
The change is probably the effect of a missing check added. Promotion cannot promote `a` to non-nullable  when it is nested in `(a = getA()) != null`. Promotion works if the code is written as 

```Dart
main() {
  A? a;
  a = getA();
  while (a != null) {
     print(a.foo());
     a = getA();
  }
}
```
