### ISSUE TITLE
stdout.supportsAnsiEscapes doesn't recognize TERM=screen-256color

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#41770]
This program prints `false` when run with `TERM=screen-256color`

That setting is used by GNU screen which indeed supports ansi escapes.

```
import 'dart:io';

main() {
  print(stdout.supportsAnsiEscapes);
}
```

Terminal ansi support detection is probably not easy to get right :(

**Comment by jonasfj** [comment]
Also used by `tmux`.

**Comment by jonasfj** [comment]
Hmm, `man 7 term` suggests the `TERM` env var can be looked up in `infocmp`, which is probably the right thing to do.

**Comment by sortie** [comment]
Sigh.

```dart
static bool TermHasXTerm() {
  const char* term = getenv("TERM");
  if (term == NULL) {
    return false;
  }
  return strstr(term, "xterm") != NULL;
}

bool Stdin::AnsiSupported(intptr_t fd, bool* supported) {
  *supported = (isatty(fd) != 0) && TermHasXTerm();
  return true;
}
```

This is so wrong. Dart needs proper support for terminfo(5). Like it would be good if it e.g. exposed `tgetstr()` from `termcap(3NCURSES) `.

**Comment by wesleym** [comment]
This seems to be a duplicate of #31606.

**Comment by sigurdm** [comment]
Agree, closing as duplicate.
