### ISSUE TITLE
Pine Script: Highest and Lowest bar within the completed MACD histogram

### ISSUE THREAD

**Issue by kysup2000** [dart-lang/sdk#41775]
I have started to learn pine scripting since last month and as you can expect, I am a beginner.
For the last few days, I've been trying to plot specific information on the chart but it did not go through well.. I would be grateful if you could help me with that...

I am trying to spot the highest bar within the completed MACD histogram(above 0), and the lowest bar within the completed MACD histogram(below 0). I have attached a screenshot for reference.
After spotting the last 2 highests, I would draw a trend line of them.. 

I know it would sound funny to you...but if someone can help with it or link me a reference, I would be very appreciated. Thank you!

![Highest and Lowest bar within the completed MACD histogram](https://user-images.githubusercontent.com/50862449/81098082-dc656700-8ed6-11ea-9340-f39083650418.png)
[My MACD histogram Pine Script.txt](https://github.com/dart-lang/sdk/files/4582731/My.MACD.histogram.Pine.Script.txt)

**Comment by mraleph** [comment]
This has nothing to do with Dart.

**Comment by weljC** [comment]
Have you solved this bro? can you help me? i am also trying to figure this out
