### ISSUE TITLE
Failures on Allow `NoSuchMethodError.withInvocation` to accept any `Invocation`.

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#41771]
There are new test failures on [Allow `NoSuchMethodError.withInvocation` to accept any `Invocation`.](https://github.com/dart-lang/sdk/commit/2ca3555c44ac7b98bb366e19ff891c4b4c4940e7).

The tests
```
standalone_2/no_such_method_error_with_invocation_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-obfuscate-linux-release-x64
```

This test should either be modified to work with obfuscation or SkipByDesign'd in the status file.

**Comment by lrhn** [comment]
We still have status files? What year is this?!? 😄 

It should be skipped by design. Not sure how to select for "obfuscate" in the status file, though.

**Comment by lrhn** [comment]
Fixed.
