### ISSUE TITLE
Frequent crash of Dart Analysis Server in Android Studio

### ISSUE THREAD

**Issue by rgisi** [dart-lang/sdk#41773]
This pops up about every minute or so. It's quite annoying, as code completion depends on it (and therefore mostly returns the circular progress indicator...)

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.8.0`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

## Exception
```
Dart analysis server, SDK version 2.8.0, server version 1.27.4, FATAL error:
```
Logs:
[report.txt](https://github.com/dart-lang/sdk/files/4580987/report.txt)
[report1.txt](https://github.com/dart-lang/sdk/files/4580988/report1.txt)
.

**Comment by srawlins** [comment]
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/41658; please follow along there.

**Comment by srawlins** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/41658
