### ISSUE TITLE
Migrator can add double null-checks when a parenthesized expression has a null-check hint

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41788]
Currently the migrator will migrate this:

```dart
int/*!*/ f(int/*?*/ i) => (i)/*!*/;
```

to this:

```dart
int f(int? i) => i!!;
```

I think it wants to add a null-check for the hint, and one for the return type.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
