### ISSUE TITLE
No error in analyzer for super.call

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41782]
According to the https://github.com/dart-lang/language/issues/734#issuecomment-565487654 calling a `call` method via `super` call is an error for now. But analyzer still accepts the following code
```dart
class A {
  String call() => "A.call!";
}

class B extends A {
  String foo() => super();  // error in CFE, no error in analyzer
}

main() => print(B().foo());
```
Tested with `dartanalyzer version 2.9.0-5.0.dev `

**Comment by srawlins** [comment]
Still no error in analyzer.

**Comment by srawlins** [comment]
I think the rules changed; CFE now allows this as well. Likely this can be closed.

**Comment by lrhn** [comment]
I don't remember the rules changing, but if it already works, maybe we can change them now.

**Comment by eernstg** [comment]
https://github.com/dart-lang/language/issues/1631
