### ISSUE TITLE
`breakpoint_non_debuggable_library_test.dart` makes it hard to update `package:path`

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#41785]
The test hardcodes references to lines in `path.dart`, so these need updating whenever `package:path` gets updated

https://dart-review.googlesource.com/c/sdk/+/144722

would it be possible to either remove the dependency or make it smarter, please? (...it could search the src for the right line, I guess, on the assumption that the public interface is not going to change).

**Comment by davidmorgan** [comment]
@bkonyi thanks!

**Comment by bkonyi** [comment]
Not a problem! It was a quick fix :-)
