### ISSUE TITLE
package:analyzer When the parameter type is Function type , type.element is getting 'null'

### ISSUE THREAD

**Issue by nateshmbhat** [dart-lang/sdk#41798]
I am using package:analyzer to do custom static analysis.

when I have dart code like below : 

    class MyType{
    
        final void Function(MyItemType) callback ;
    }

When I try to access the `element` of the callback type : I am getting `null`

That is :

`parameterElement.type.element` evaluates to be `null` .
Therefore I cannot get the `source` file of the Types involved in the Function to import those source files. 

This issue happens only when I use a `Function` type that is anything other than just `Function()`.

`parameterElement` is of Type ParameterElement from `analyser` package.

My requirement is that I want to import all the files that contain the Types involved in the Function. In my example code shown above , I wish to import the file that contains the `MyItemType` class.

Also if the return type of the function was some other Type other than `void` , I want to import the corresponding source file. 

Please see this SO question here : https://stackoverflow.com/questions/61651285/dart-analyser-when-the-parameter-type-is-function-type-type-element-is-getting

**Comment by srawlins** [comment]
Sorry, very late answer to your question:

Yes, function types (`FunctionType`) do not have Elements. But you should not need that to get the elements of any `InterfaceType`s in their signature. If `.returnType` is an InterfaceType, then `.returnType.element` gives you its element. Each parameter in `.parameters` (ParameterElements) should have a `.type`, and for each of those that is an `InterfaceType`, `.element` will get you its element.

For future reference, usage questions like this are best asked on our user mailing list, analyzer-discuss@dartlang.org.
