### ISSUE TITLE
Supporting files for the `ddc` module format are not shipped with the sdk

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41790]
In order to use the `ddc` module format we need the corresponding `dart_library.js` and `dart_sdk.js` files shipped with the SDK, but it looks like they are missing today, I only see `amd`, `common`, and `es6` directories under `lib/dev_compiler/kernel` in the shipped SDK.

This is a blocker for us migrating to that format externally.

**Comment by nshahan** [comment]
With the release of the null safety feature we started requiring build system integrations to compile the `dart_sdk.js` files on demand. The existing precompiled versions for weak null safety are still included in the SDK for backwards compatibility but I suspect most use cases are no longer using them and we plan to remove them in the future.

For that reason I don't believe this is still a blocker for migrating to use the ddc module format externally.
