### ISSUE TITLE
Analyzer: How to obtain the generic parameters of a ParameterElement?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#41794]
Hello!

Consider the following:

```dart
abstract class Outer with _$Outer {
  const factory Outer({
    Whatever<int> innerData,
  }) = _Outer;
}
```

From the `ParameterElement` of `innerData`, how to obtain the generic parameters of `Whatever` (here `int`)?

`parameterElement.typeParameters` explicitly says that it works only for functions, and `parameterElement.type` doesn't seem to expose any way to read generic arguments.

I need to parse these generic parameters to fix a bug for a code-generator I maintain: https://github.com/rrousselGit/freezed/issues/128.

**Comment by rrousselGit** [comment]
Actually I found the solution:

cast `parameterElement.type` to `InterfaceType`

We can then do:

```dart
InterfaceType type;
print(type.typeArguments); // [int]
```

**Comment by bwilkerson** [comment]
Note that `parameterElement.type as InterfaceType` will sometimes throw a cast exception.

The getter `parameterElement.type` returns a `DartType`. You'll need to test the type to see whether it's a `ParameterizedType`. If it is, then you can use `typeArguments` to get the type arguments on the type.

**Comment by rrousselGit** [comment]
Good to know.

In which situation would a `parameterElement.type` not be a `ParameterizedType`?

**Comment by bwilkerson** [comment]
When it's neither a class nor a function, such as `dynamic`.
