### ISSUE TITLE
Migration tool should open a browser window to the preview app

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41809]
We should discuss this I suppose, as its a big UX change. But the general idea is that, in addition to printing out the URL of the preview app on the console, the migrator should just open a browser window, using [browser_launcher](https://pub.dev/packages/browser_launcher) (not in DEPS, but Dart-team-authored, and few deps itself).

**Comment by srawlins** [comment]
To make this more feasible, this could be an internal-only feature, as we have browser_launcher internally.

**Comment by lrhn** [comment]
The `browser_launcher` package is owned by dart.tools.dev, so it should be fine for the SDK to depend on &mdash; and we [already do](https://github.com/dart-lang/sdk/blob/8bd17aaacdf7b33e02dfece01d5de9b02acf7eee/DEPS#L89).

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
