### ISSUE TITLE
ring_gc_test, ring_gc_sendAndExit_test are hanging on precomp bots.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#41813]
ring_gc_test, ring_gc_sendAndExit_test are hanging on precomp bots.
For example, https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-linux-debug-simarm_x64/1999

**Comment by aam** [comment]
the test seems to hang after one of the isolates receives Tree instead of expected List<dynamic>

**Comment by mkustermann** [comment]
@aam already has CL out: https://dart-review.googlesource.com/c/sdk/+/147329

**Comment by mkustermann** [comment]
@aam fixed it so we can close it :)
