### ISSUE TITLE
[NNBD] Analyzer and CFE allow use of not initialized non nullable variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41815]
The code when the issue occurs is the following

```dart
void test(Never n) {
  int i;
  do {
    n;
    i = 42; // hint - Dead code
  } while (false);
  i;  // No error
}

main() {
  try {
    test(throw "Lily was here");
  } catch (_) {
  }
}
```
Code after variable or getter of type Never is unreachable, so `i` must be still not initialized after the loop. but there is no error in both Analyzer and CFE.
Note that behavior is correct (I believe) in the following cases
```dart
void test(Never n) {
  int i;
  do {
    i; // error - The non-nullable local variable 'i' must be assigned before it can be used.
    n;
    i = 42; // hint - Dead code
  } while (false);
}
```
```dart
void test(Never n) {
  int i;
  if (true) {
    n;
    i = 42;  // hint - Dead code
  }
  i;  // hint - Dead code
}

```
Tested on `Dart VM version: 2.9.0-7.0.dev (dev) (Thu May 7 09:17:54 2020 +0200) on "windows_x64"`

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
This area of the flow analysis is not fully specified.
I opened https://github.com/dart-lang/sdk/issues/42193 when discovered this and similar issues.

I will keep that more general issue open, and subsume this one.
