### ISSUE TITLE
Tried to initialize from a previous compilation (build/cache.dill), but the file was not self-contained. This might be a bug.

### ISSUE THREAD

**Issue by ZheKOs** [dart-lang/sdk#41838]
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/4608323/initialize_from.dill.gz)

**Comment by ZheKOs** [comment]
Oh, looks like I have 30mb on my disk 'C' (I'm using Windows).
Maybe that's the problem

**Comment by ZheKOs** [comment]
Yeap, the only 3 things that I did to fix this problem is I reported this bug, cleared some space on my disk 'C' and build my app again. xD

**Comment by jensjoha** [comment]
Hmm... It looks like it was trying to initialize from a partial compilation instead of a full one.
Considering the dill file is actually valid, I don't think the lack of disk space is the culprint.

What version of flutter are you using?
What commands did you run?

**Comment by ZheKOs** [comment]
@jensjoha here is the response on `flutter --version`:

> Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision e6b34c2b5c (10 days ago) • 2020-05-02 11:39:18 -0700
> Engine • revision 540786dd51
> Tools • Dart 2.8.1

I just made some changes in my Test Application using Android Studio and build & run it on Android

**Comment by ZheKOs** [comment]
I just checked and looks like I didn't make any changes in the code, I just compiled and run the app, so I can Hot Reload and work with my "Test App", but got such exception during compilation. The app is simple just to Text widgets and that's all :)

**Comment by jensjoha** [comment]
Thank you for your report and for answering my questions :)
 
Unfortunatly I can't seem to reproduce it --- until proven otherwise I'll assume it was caused by something that was already fixed.

**Comment by SyedAbdullah58-dev** [comment]
If someone is having a similar problem in flutter web, go for the command "flutter clean". This will solve your problem.
