### ISSUE TITLE
webdev not escaping file names correctly?

### ISSUE THREAD

**Issue by my2iu** [dart-lang/sdk#41834]
I was doing some web development in Windows. I wanted to make some quick changes to `web/main.dart` so I made a copy in Windows called `web/main - Copy.dart`.

I ran `webdev build` and it seemed that `webdev` tried to pass the file with the dash in it to dart2js without escaping it, so the dash was interpreted as an argument.

**Comment by sigmundch** [comment]
Issue moved to [dart-lang/webdev #1001](https://github.com/dart-lang/webdev/issues/1001) via [**ZenHub**](https://www.zenhub.com/)
