### ISSUE TITLE
Audio processing is web only

### ISSUE THREAD

**Issue by SwissCheese5** [dart-lang/sdk#41837]
Digging through the sdk, it seems audio can only be handled and processed on the browser
https://api.dart.dev/stable/2.8.1/dart-web_audio/dart-web_audio-library.html

There is no io equivalent it seems. This is very odd as most audio processing will be done on servers/desktops/apps.

**Comment by mit-mit** [comment]
There are many packages to choose from in the pub.dev repository: https://pub.dev/packages?q=audio

Closing the present bug; this is not a core SDK issue.

**Comment by SwissCheese5** [comment]
@mit-mit I would like to clarify I did not mean audio PLAYING.
The web package in dart let's you load audio and read it's bytes and extract audio data. No existing package will do this for servers/desktop/io

**Comment by mit-mit** [comment]
I see. That is still a capability we would expect a package for, and not a core SDK capability.

**Comment by SwissCheese5** [comment]
@mit-mit in that case, why does the audio web package exist? Perhaps it's best moved into its own package as well.

**Comment by mit-mit** [comment]
Solely for historical reasons.
