### ISSUE TITLE
[NNBD] Analyzer doesn't flag `int = (int? + int?)` as an error

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/sdk#41831]
I'm using:

```
Dart VM version: 2.9.0-7.0.dev (dev) (Thu May 7 09:17:54 2020 +0200) on "macos_x64"
```

And I have the following code in a file:

```dart
// @dart=2.9
// Just want a function that static analysis can't know for a fact isn't going
// to return null, but will not, in fact, return null.
int? _couldReturnNull() {
  if (DateTime.now().year != 1996) {
    return 3;
  }

  return null;
}


void main() {
  int? couldBeNullButIsnt = _couldReturnNull();

  int a = couldBeNullButIsnt;
  int b = (couldBeNullButIsnt + _couldReturnNull());

  print('a is $a.');
  print('b is $b.');
}
```

When I run dartanalyzer on the command line, I get the following errors, both of which make sense:

```
Analyzing blah.dart...
  error • A value of type 'int?' can't be assigned to a variable of type 'int'. • blah.dart:16:11 • invalid_assignment
  error • An expression whose value can be 'null' must be null-checked before it can be dereferenced. • blah.dart:17:12 • unchecked_use_of_nullable_value
2 errors found.
```

When I add the assertion operator to line 16 (the declaration of `a`):

```
  int a = couldBeNullButIsnt!;
```

The analyzer no longer produces any errors. That seems weird (at least to me), since the second call to `_couldReturnNull` should be considered a nullable value.

I have enough faith in the SDK that I assume it's correct and I'm not. That said, what am I missing here? 😄 

Does adding the assertion on `couldBeNullButIsnt` on line 16 cause it to be promoted to non-nullability afterward? If so, why do I not get a different warning about attempting to add `(int + int?)`?

Does adding the two values cause promotion as well, since otherwise an exception is thrown?

**Comment by srawlins** [comment]
> Does adding the assertion on `couldBeNullButIsnt` on line 16 cause it to be promoted to non-nullability afterward?

No, the type annotation in the declaration (`int a =`) causes `a` to be a non-nullable int. The null-assertion does not change the return type of later calls to `couldBeNullButIsnt`

> If so, why do I not get a different warning about attempting to add `(int + int?)`?

Maybe this was fixed recently. On a recent version of the analyzer,  I get 3 errors with your original code:

> error • A value of type 'int?' can't be assigned to a variable of type 'int'. • 41831.dart:16:11 • invalid_assignment

> error • An expression whose value can be 'null' must be null-checked before it can be dereferenced. • 41831.dart:17:12 • unchecked_use_of_nullable_value

> error • The argument type 'int?' can't be assigned to the parameter type 'num'. • 41831.dart:17:33 • argument_type_not_assignable

After inserting the null-check operator, I still see the third:

> error • The argument type 'int?' can't be assigned to the parameter type 'num'. • 41831.dart:17:33 • argument_type_not_assignabl

**Comment by scheglov** [comment]
Works for me, I get one error after changing `int a = couldBeNullButIsnt;` to `int a = couldBeNullButIsnt!;`. When you do this, you promote `couldBeNullButIsnt` to be non-nullable.
