### ISSUE TITLE
CFE: Emit a compile-time error for wrong placement of type arguments in factory

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41842]
Consider the following program:

```dart
class A<T> {
  A();
  factory A.foo(int x) = B.foo<T>; // No error.
}

class B<T> extends A<T> {
  B.foo(int x) {}
}

void main() {
  new B.foo<int>(24); // Error.
}
```

This program is rejected by the front end (using `dart` from a6d06b59ec4b65fefa173a25458fde6f098a3510 and from 2.8.0-dev.20.0) with a compile-time error in `main`, but no error on the redirecting factory constructor declaration.

This issue is concerned with implementing a check on the factory body corresponding to the check which is currently applied to the instance creation, such that the non-standard placement of the actual type arguments is reported in both cases.

**Comment by lrhn** [comment]
Seems like a case of #34159 that was missed.

**Comment by eernstg** [comment]
Thanks, I was looking for related issues and missed that one!

Issue #34159 (very pi-ish, btw ;-) explicitly targets the parser, though, and we can't ask the parser to reject `B.foo<T>` as a redirecting factory body (`B` could be an import prefix and `foo` could be a class name).

In any case, the compile-time error should be emitted, and it's missing, so we need an issue for the task.
