### ISSUE TITLE
dartpad "compiling to javascript xmlhttprequest" error

### ISSUE THREAD

**Issue by amiver** [dart-lang/sdk#41848]
OS: Windows 8.1
Browser: Chrome
![darterror](https://user-images.githubusercontent.com/37574926/81588492-3930b800-93d6-11ea-83d3-aa047d4698a4.jpg)

**Comment by domesticmouse** [comment]
This was correctly raised as https://github.com/dart-lang/dart-pad/issues/1558

**Comment by mit-mit** [comment]
Closing as duplicate
