### ISSUE TITLE
Web : Rename null safety strong mode flag

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41854]
Currently the null safety strong mode flag is controlled by the flag `--no-null-safety` / `--null-safety`.

From offline discussion, we find that this is suboptimal: When a developer opts out of sound/strong checking with `--no-null-safety` they will still get some null safety (e.g. static analysis), but the flag name makes it sound like they are loosing all of null safety.

We'd thus like to rename this flag to `--no-sound-null-safety` / `--sound-null-safety`.
[Source for --no-null-safety](https://github.com/search?q=org%3Adart-lang+--no-null-safety&type=Code)
[Source for --null-safety](https://github.com/search?q=org%3Adart-lang+--null-safety&type=Code)

**Comment by sigmundch** [comment]
both DDC and dart2js have been renamed to `--sound-null-safety` and `--no-sound-null-safety`.
