### ISSUE TITLE
`dart migrate` tool UX feedback

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#41851]
Various bits of feedback from running the `dart migrate` tool:

### Unclear chars in the migration code view

It's not clear why the square ansi chars are in the code view, or more specifically, when the tool initially opened it looked like the foreground and background colors of that char had inadvertently been made the same:

<img width="290" alt="Screen Shot 2020-05-09 at 9 43 46 PM" src="https://user-images.githubusercontent.com/1269969/81608341-fb5a7200-938a-11ea-863b-52c16d040149.png">

I think the intent is to have a place - where no code change was made - for the user to click on so they can see why no change was inferred here.

### Items look checkable but aren't

These items:

<img width="317" alt="Screen Shot 2020-05-09 at 9 46 02 PM" src="https://user-images.githubusercontent.com/1269969/81608466-2a70e380-938b-11ea-9450-66ba8d92b60d.png">

Look like they are something you can interact with to check and un-check them, but aren't meant to be checked. Perhaps choose another ansi char for the list symbol?

### Misc

- in the 'nullability reasons' section, some of the type names in the start of the description end with a period and some don't
<img width="150" alt="Screen Shot 2020-05-11 at 1 31 45 PM" src="https://user-images.githubusercontent.com/1269969/81608889-d5819d00-938b-11ea-9343-3188ed49fd97.png">

**Comment by jcollins-g** [comment]
@MichaelRFairhurst @stereotype441 @srawlins

**Comment by srawlins** [comment]
> Items look checkable but aren't

Yeah these were meant to look like the stack frame icons in IntelliJ. I'll replace with... probably nothing.

> in the 'nullability reasons' section, some of the type names in the start of the description end with a period and some don't

I believe things that end with `.` are referring to an unnamed constructor. Can fix.
