### ISSUE TITLE
When performing the test, it prompts me that there is a problem with the compilation

### ISSUE THREAD

**Issue by fengwuxp** [dart-lang/sdk#41859]
use
  flutter_sdk: 1.12.13+hotfix.9
  flutter_test

`
Compiler message:
Warning: Tried to initialize from a previous compilation (file:///E:/workspace/idea/github/flutter/fengwuxp_dart_feign/example/build/testfile.dill.track.dill), but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file /C:/Users/11096/AppData/Local/Temp/initialize_from.dill77d1156c-9408-11ea-82e8-e4b3181cbd6d/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.
`

**Comment by jensjoha** [comment]
Inactionable.
