### ISSUE TITLE
Test : Rename null safety strong mode flag

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41855]
Currently the null safety strong mode flag is controlled by the flag `--no-null-safety` / `--null-safety`.

From offline discussion, we find that this is suboptimal: When a developer opts out of sound/strong checking with `--no-null-safety` they will still get some null safety (e.g. static analysis), but the flag name makes it sound like they are loosing all of null safety.

We'd thus like to rename this flag to `--no-sound-null-safety` / `--sound-null-safety`.
[Source for --no-null-safety](https://github.com/search?q=org%3Adart-lang+--no-null-safety&type=Code)
[Source for --null-safety](https://github.com/search?q=org%3Adart-lang+--null-safety&type=Code)

**Comment by franklinyow** [comment]
@munificent  Can you help assign this to the right person?

**Comment by munificent** [comment]
Sorry for the delay. I'm not sure what the task is here. What tools is this about?

**Comment by franklinyow** [comment]
> Sorry for the delay. I'm not sure what the task is here. What tools is this about?

I think there are test or test related files that has the old flag that need a search and replace.

**Comment by munificent** [comment]
The test runner doesn't have a separate flag for this. Instead, it has three modes:

```
--nnbd=legacy // Opted out.
--nnbd=weak // Opted in, weak checking.
--nnbd=strong // Opted in, string checking.
```

I can change this if you think it's important, but this tool is only used internally by people on the Dart team, so I don't think it adds much value.

**Comment by franklinyow** [comment]
@mit-mit WDYT?

**Comment by munificent** [comment]
Closing this because I don't think we plan to or need to take action on it.
