### ISSUE TITLE
dart2js: Evaluation of `e1 == e2` invokes `operator ==` prematurely

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#41867]
Consider the following program (which is a slice of `language/operator/equality_covariant_test.dart`, which is added by https://dart-review.googlesource.com/c/sdk/+/145582):

```dart
import "package:expect/expect.dart";

class EqNever {
  operator ==(covariant Never other) => throw "unreachable";
}

void main() {
  Object oNever = EqNever();
  Object? myNull = null;
  Expect.isFalse(oNever == myNull);
}
```

This test fails on the configuration dart2js-nnbd-linux-x64-chrome-try ([log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8880504577943494352/+/steps/test_results/0/logs/new_test_failures__logs_/0)), throwing the string `"unreachable"` with the following stack trace:

```
Deobfuscated error and stack:
unreachable
    at wrapException          org-dartlang-sdk:///sdk_nnbd/lib/_internal/js_runtime/lib/js_helper.dart 1348:37
    at throwExpression        org-dartlang-sdk:///sdk_nnbd/lib/_internal/js_runtime/lib/js_helper.dart 1379:25
    at ==(inlined)            ../../../../../tests/language/operator/equality_covariant_test.dart 11:41
    at main                   ../../../../../tests/language/operator/equality_covariant_test.dart 36:18
    at action                 sdk_nnbd/lib/_internal/js_runtime/lib/preambles/d8.js 275:31
    at eventLoop              sdk_nnbd/lib/_internal/js_runtime/lib/preambles/d8.js 258:9
    at self.dartMainRunner    sdk_nnbd/lib/_internal/js_runtime/lib/preambles/d8.js 276:5
    at <fn>                   out/ReleaseX64/generated_compilations/dart2js/tests_language_operator_equality_covariant_test/equality_covariant_test.js 3049:7
    at <fn>                   out/ReleaseX64/generated_compilations/dart2js/tests_language_operator_equality_covariant_test/equality_covariant_test.js 3035:7
    at dartProgram            out/ReleaseX64/generated_compilations/dart2js/tests_language_operator_equality_covariant_test/equality_covariant_test.js 3046:5
    at <fn>                   out/ReleaseX64/generated_compilations/dart2js/tests_language_operator_equality_covariant_test/equality_covariant_test.js 3053:3
```

This seems to indicate that the `operator ==` of the value of `oNever` (which is an instance of `EqNever`) is being executed.

However, evaluation of an expression of the form `e1 == e2` is specified to run in phases where null is processed first. In particular, `oNever == myNull` should evaluate `oNever` to an object different from null, and evaluate `myNull` to null, and then yield false. Maybe the inlining step yields code that doesn't check for null?

Testing locally, the issue arises with a strong configuration:

```
> tools/test.py -n dart2js-hostasserts-strong-linux-x64-chrome language/scratch_test
```

The corresponding `-weak-` configuration does not throw. Also, the `-d8` configurations behave like the `-chrome` configurations (throwing with `-strong-`, not with `-weak-`).

I haven't chosen a label for the area because `area-dart2js` is gone and there doesn't seem to be any labels for "wrong run-time semantics of dart2js"; also, other choices like `dart2js-compile-time` and `dart2js-crash` are misleading.

@rakudrama, maybe you could choose suitable labels?

**Comment by rakudrama** [comment]
dart2js fakes handling `null` at the call site by handling `null` immediately in every `==` method.

Since the `==` method has this implicit injected test, we should not be inlining if the argument is possibly `null`.
The error is likely in the inlining decision for a `==` method.

@fishythefish if the type test at the inlining decision bad?

**Comment by fishythefish** [comment]
Yes, the abstract value domain thinks that `isNull` is definitely false for the argument even though we  identify it as `[subtype=Null]`. I'm investigating, but strong mode failures (particularly surrounding type tests/nullability) are not surprising given that we're just starting the burndown.

**Comment by fishythefish** [comment]
Okay, so this is something I ran into back in January when I was working on https://dart-review.googlesource.com/c/sdk/+/130462 - our type masks represent nullability (this predates NNBD) as a bit, and we use only this bit to determine nullability. The mask `[subtype=Null]` is a *non-null* subtype mask, even though the class itself is only inhabited by `null`.

It's easy enough to insert a check for this case in `createFromStaticType`, but it would be nice to have the typemasks normalize how we represent `Null`. For example, if we end up with a union of `Null` and some other typemask `T`, can/should we normalize that to `T.nullable()`?

@rakudrama WDYT?

**Comment by fishythefish** [comment]
I basically added canonicalization for union typemasks back in January, so here's a tentative fix for flat typemasks: https://dart-review.googlesource.com/c/sdk/+/148182
