### ISSUE TITLE
dart2js: support for strong and weak mode

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#41869]
Missing work:
* [x] add build rules to generate a second platform dill file in strong mode
* [x] include two both dill files in the shipped SDK
* [x] add logic in dart2js to choose between the .dill files depending on the mode

We don't need new plumbing or flags because we had support for something very similar in the Dart1-Dart2 migration.

**Comment by fishythefish** [comment]
Fixed in e16b45c5508f9bf4851e1e48656864046542ee5b.
