### ISSUE TITLE
Global variable seems to be created twice in tests if files are imported relatively

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#41865]
* Dart SDK Version (`dart --version`)
Dart VM version: 2.9.0-7.0.dev.flutter-617bc54b71 (be) (Thu May 7 23:23:09 2020 +0000) on "windows_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows

while trying to replicate another bug I found this here. Please clone 

https://github.com/escamoteur/type_import_test/tree/different_global_instances_in_tests

and try to run the only test in the project and it will throw an exception.
If you set a breakpoint at the end of `init` in `type_name_map.dart` you will see that `typeNameMap` is initialized and has a value.
If you check again in `access_map.dart` line 10 you will see that the map is empty.

If you either change the import in `access_map.dart` or in `import_test.dart` from relative to a package reference the test works.

**Comment by mit-mit** [comment]
Same root issue as 41868; tests should avoid relative imports.

I recommend using this lint to detect this: https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html
