### ISSUE TITLE
[vm_service] Upgrading vm_service causes service extension calls to fail

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#41879]
Upgrading flutter to vm_service package (version 4.0.3) makes `callServiceExtension` fail if called with no args. Version 4.0.2 does not have the issue.

See initial CI failures and comments in 
https://github.com/flutter/flutter/pull/56958

Exception happens if the following line gets executed (empty args map is created with incorrect type):
https://github.com/dart-lang/sdk/blob/3aa7484f6a61b5d04365075ab4f0371cc50deb9e/pkg/vm_service/lib/src/vm_service.dart#L1958

I suspect one of the following changes (diff between 4.0.2 and 4.0.3)

```
2086c2098
<     final Map m = await _routeRequest(json['method'], json['params']);
---
>     final Map m = await _routeRequest(json['method'], json['params'] ?? {});
2096c2108
<     final Map params = json['params'];
---
>     final Map params = json['params'] ?? {};
```

**Comment by bkonyi** [comment]
`package:vm_service` v4.0.4 is released. Try updating to that version to hopefully fix the failures you're seeing.

**Comment by annagrin** [comment]
It works now, thanks!
