### ISSUE TITLE
Running a .dill with opted-out libraries in strong mode crashes the VM

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#41870]
Trying to run a `.dill` file that contains opted-out libraries using the `--null-safety` flag crashes the VM (on Windows at least):

```
c:\src\dart-repo1b\sdk\runtime\vm\kernel_loader.cc: 1044: error: Library 'file:///c:/src/dart-repo1b/sdk/pkg/front_end/testcases/nnbd/strong_lib_not_ok_from_dill/strong_lib.dart' was compiled without null safety (in weak mode) and it cannot be used with --null-safety at
runtime
version=2.9.0-edge.fb11d6399c7742333ab3ea9abe6d8ac88466dc4b (be) (Fri May 8 05:45:49 2020 +0000) on "windows_x64"
pid=9036, thread=17796, isolate=main(000002A48752B360)
isolate_instructions=7ff646071000, vm_instructions=7ff646071010
  pc 0x00007ff646272afc fp 0x000000e8b30fea50 dart::Profiler::DumpStackTrace+0x1c
  pc 0x000000000000005d fp 0x000000e8b30fec58 Unknown symbol
-- End of DumpStackTrace
```

I'm seeing this when running
```dart pkg/front_end/tool/fasta.dart testing strong/nnbd/strong_lib_not_ok_from_dill/strong```
on https://dart-review.googlesource.com/c/sdk/+/140868/

**Comment by alexmarkov** [comment]
@johnniwinther Are you sure that library (dill file) was compiled in strong mode?
We have this check to ensure that strong/weak compilation mode matches runtime mode. This check looks at strong/weak mode (nnbdModeBit1, nnbdModeBit2 bits of library flags) and not at the opt-in/opt-out status of a library (isNonNullableByDefault bit).

**Comment by johnniwinther** [comment]
What happens is that a precompiled weak-mode dill is used as an input to a strong-mode compilation. This leads to the reported error but also to a dill that contains some weak-mode libraries despite the component mode being strong.

The repro is (using https://dart-review.googlesource.com/c/sdk/+/140868/):
```
dart pkg/pkg/front_end/tool/fasta.dart compile --out=lib.dill pkg/front_end/testcases/nnbd/strong_lib_not_ok_from_dill/strong_lib.dart --enable-experiment=non-nullable --nnbd-weak --dump-ir
dart pkg/pkg/front_end/tool/fasta.dart compile --link-dependencies=lib.dill --out=out.dill pkg/front_end/testcases/nnbd/strong_lib_not_ok_from_dill/strong.dart --enable-experiment=non-nullable --nnbd-strong
dart out.dill
```

**Comment by alexmarkov** [comment]
@johnniwinther I think such dill file is not correct, and a fatal error issued by the VM is valid. Error message clearly indicates what is the problem. Do you think we should support running such dill file?

In weak mode VM doesn't accept libraries compiled in strong mode, and in strong mode VM doesn't accept libraries compiled in weak or disabled mode. We don't really know what to do with such discrepancy between compilation mode and runtime mode.

I think we should fix how those dill files are produced to avoid these errors. And maybe CFE should catch this situation earlier and issue compile-time errors.

**Comment by johnniwinther** [comment]
I agree that the file is not correct but should the vm _crash_ instead of just reporting the error and stopping?

https://dart-review.googlesource.com/c/sdk/+/140868/ has landed so the CFE now reports a compile-time error when trying to include opted-out libraries in strong mode.

**Comment by alexmarkov** [comment]
That's how VM reports _fatal_ errors. Fatal error is used because this code can be called very early during bootstrapping (in gen_snapshot, when bootstrapping from kernel) and proper error handling is not set up at that point. My thinking is that this error is internal (indicates a bug in our tools) and not user-visible anyway - it is more like an assertion.

Maybe we can set up error handling for bootstrapping to make this error look less like a crash, if it is actually user-visible.

**Comment by johnniwinther** [comment]
It is very much user visible. On Windows I get the "dart.exe has stopped working"-popup even when running from the command-line.
