### ISSUE TITLE
Passing type-parameterized function to ArgumentError.checkNotNull broken in 2.8.1

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#41871]
I might be using more type-parameters than is useful :)
But I ran into this curious case, and wonder if it's a known regression.

```dart
typedef WrapperFn = Future<T> Function<T>(Future<T> Function() fn);

void acceptsWrapper(WrapperFn wrap) async {
  // This works on Dart 2.7.0, but not Dart 2.8.1
  ArgumentError.checkNotNull(wrap);

  // This works fine on both Dart 2.7.0 and 2.8.1
  if (wrap == null) {
    throw ArgumentError.notNull();
  }

  await wrap(() async {
    // Do something async that we want [wrap] to be able to initiate and
    // return the result from, including catching exceptions.
  });
}

void main() => print('hello world');
```
On dart `2.7.0` it works, but on `2.8.1` I get (before it starts running):

```
hack.dart:5:17: Error: Generic function type 'Future<T> Function<T>(Future<T> Function())' inferred as a type argument.
 - 'Future' is from 'dart:async'.
Try providing a non-generic function type explicitly.
  ArgumentError.checkNotNull(wrap);
)
```

**Comment by jonasfj** [comment]
@lrhn might this have to do with signature change from dart 2.7.1 which has:
```dart
static void checkNotNull(Object argument, [String name]);
```
to dart 2.8.1 which has:
```dart
static T checkNotNull<@Since("2.8") T>(T argument, [String name]);
```

**Comment by lrhn** [comment]
It is because of that change, yes.

Dart prohibits a generic function type from being a type argument.
However, it does not stop itself from inferring such a type as a type argument. 

We should just stop having that restriction, or at least stop inferring generic types as arguments (just inferring `Function` would work).

The workaround would be to pass an explicit type argument (just `void` would be fine, since no-one is using the return value).

**Comment by jonasfj** [comment]
For work around, one can also do:
```dart
if (wrap == null) {
  throw ArgumentError.notNull();
}
```

That works fine :)

But for existing code fixing this would be nice, at it's a static error for any code using `package:acyclic_steps` (I'll probably publish a patch version with the work around).

**Comment by lrhn** [comment]
Closing in favor of https://github.com/dart-lang/language/issues/496

**Comment by mit-mit** [comment]
This is supported as of Dart 2.14.
