### ISSUE TITLE
Migration: stack trace edits should include 'add ! to expression'

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41875]
This should likely be done by calling out to EditPlanner on demand, so this may be a bit of work. Otherwise we may have cases such as

```dart
a + b!;// instead of
(a + b)!;
```

and doing this eagerly is probably too slow to start with.

Should be careful to avoid (as much as possible) instances where a ! is not correct for an edge:

```dart
List<int/*!*/> intList = <int/*?*>[];
```

This needs a cast, or something funky like a `.cast`, so this should not suggest adding a !.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
