### ISSUE TITLE
enum values don't canonicalize correctly when passing through a port on some ARM devices

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#41888]
I am getting reports from the users that they observe strange behaviour when passing enum values through ports. If the receiving side tries to compare received value with enum values - they don't compare equal. However this behaviour only occurs on some ARM devices and not others - with the same application. 

e.g. this happens on Samsung A10, but not on Samsung A40.

This is similar to a bug reported by @simolus3 regarding moor package. https://github.com/simolus3/moor/issues/514

~~I am starting to suspect a CPU bug, because otherwise I find it hard to explain why would behaviour be different running the same code on two different phones.~~

~~We are aware at least about one such bug affecting Dart VM before (namely Cortex A53 Erratum 843419) and there is another erratum which affects multiply-accumulate instruction (Erratum 835769) - but mitigations for both of these are built into the compiler and should be enabled by default when targeting Android.~~

~~It is unclear for me what we could do to help users diagnose the problem - because we currently don't have access to the similar hardware.~~

/cc @mkustermann @rmacnak-google

**Comment by mkustermann** [comment]
We know that there's an issue - @aam has started investigating it a few days ago.

**Comment by mkustermann** [comment]
When I landed 8d1c4c555ce808b0a8ba2c513d25ca86d5b48f74 it added a number of new isolate tests, there @aam noticed that on simarm the enums don't get canonicalized correctly.
So we do have a repro.

**Comment by mraleph** [comment]
@mkustermann do you know if simarm64 exhibit similar behaviour? is it ARM vs ARM64 issue? that would explain why it reproduces on some devices (ARM) but not others (ARM64).

**Comment by mkustermann** [comment]
Last time @aam mentioned the difference in behavior seems to show with using `simarm_x64` vs `simarm`. So that would mean a bug in our cross configuration. Maybe different canonicalization hash codes or bug in generated code.

**Comment by aam** [comment]
@mraleph see dartbug.com/41824

**Comment by mraleph** [comment]
Duplicate of #41824
