### ISSUE TITLE
info: Name types using UpperCamelCase. (camel_case_types at [camaraapp] lib/tela_4.dart:3)

### ISSUE THREAD

**Issue by renatomanocchio** [dart-lang/sdk#41886]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.8.1`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1920x1080`

**Comment by srawlins** [comment]
I don't think there is anything usable in this report. Please re-open with more details if you see an issue again.
