### ISSUE TITLE
Dart should use inference rather than instantiation-to-bound for the factory of generic class.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41895]
Dart VM version: 2.9.0-8.0.dev (dev) (Mon May 11 11:05:18 2020 +0200) on "windows_x64"

The following code sample passes with analyzer and throws a compile time error with dart:
``` dart
class A<X> {
  A() {}
  factory A.foo1() = C;
}

class C<X> extends A<X> {
  C() {}
}

main() {}
```
This happens both with nnbd turned off and on.

Seems like according to dart-lang/sdk#34714 dart should not throw a compile error here.

Sample output is:
> $> dartanalyzer test.dart
> Analyzing test.dart...
> No issues found!
> 
> $> dart test.dart
> test.dart:3:22: Error: The constructor function type 'C<dynamic> Function()' isn't a subtype of 'A<X> Function()'.
>  - 'C' is from 'test.dart'.
>  - 'A' is from 'test.dart'.
>   factory A.foo1() = C;
>                      ^

**Comment by eernstg** [comment]
I believe this can be closed: The work was done in https://dart-review.googlesource.com/c/sdk/+/147181, and a fresh `dart` from commit e0257265d34efffc845ea88643e183dc3cc5bb0e does not emit the error.
