### ISSUE TITLE
Migration: potential source code restructure

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#41891]
After consolidating all code into pkg/nnbd_migration, we should consider restructures of the source accordingly.

One proposal: engine, server, front_end ?

We could put their public APIs (for instance, instrumentation.dart is sort of the public API to engine) in lib.

So
lib/src/engine/nullability_node.dart
lib/engine/nullability_node_info.dart
lib/src/server/preview_site.dart
lib/server/trace_entry_info.dart
lib/src/front_end/migration.dart

Now that we're in one package, more code sharing is I think better. A good example I think is that the const routes strings used in PreviewSite for routing should be used to generate URLs in web/migration.dart. This format would allow us to still share code, and still maintain boundaries between the components.

Another option to consider is engine/, preview/back_end, and preview/front_end.

**Comment by srawlins** [comment]
I think at this point we'll leave the structure alone.
