### ISSUE TITLE
DDC does not properly reset late fields after a hot restart.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#41892]
Accessing a late instance field after a hot restart doesn't throw a LateInitializationError. If this is intended behavior, we can close the issue.

**Comment by Markzipan** [comment]
@johnniwinther can you verify that class fields are being annotated with `isLate` in the CFE? These are all showing up as `false` locally. Simple snippet:
```
class L {
  lazy String s;
}
main() {}
```

**Comment by johnniwinther** [comment]
DDC uses the late lowering provided by the CFE which doesn't itself use late fields and therefore leaves all `isLate` properties `false`.

**Comment by Markzipan** [comment]
Is there a way to toggle this mode?

**Comment by Markzipan** [comment]
Yep - that exactly

**Comment by johnniwinther** [comment]
Do you need to reset both instance fields and static fields?

**Comment by Markzipan** [comment]
Yes, but we already have a mechanism for handling non-late fields. Our issue is that we can't differentiate late instance fields from non-late ones. Top-level and static members can already be detected and emitted lazily, but it seems like lazy fields have some extra logic that might not be properly reset.

It might not actually be too difficult to implement lazies in DDC now that I think of it.

**Comment by johnniwinther** [comment]
I'll add a way to recognize late lowered fields in the backends.

**Comment by johnniwinther** [comment]
I add a predicate for detecting late lowered fields in https://dart-review.googlesource.com/c/sdk/+/148321

**Comment by Markzipan** [comment]
Thanks, Johnni!

**Comment by Markzipan** [comment]
This has been fixed for late static fields and late top-level fields. We can reprioritize this issue if hot restart requires late instance fields to be reset as well.

**Comment by sigmundch** [comment]
after discussing this offline last week, we believe we can close this. @Markzipan please correct me if I misunderstood.
