### ISSUE TITLE
NNBD migration tool inserting annotations at wrong locations

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#41894]
Here's an example of a bad case:

```dart
  static Color? lerp(Color/*!*/  a, /*?*//*?*/C/*!*/olor  b, double  t) {
```

To get into this state start with this code:

```dart
  static Color lerp(Color a, Color b, double t) {
```

Then use the migration tool to perform the following actions:

1. Add `/*?*/` to parameter `a`
1. Add `/*?*/` to parameter `b` (observe things going off the rails a bit)
1. Add `/*?*/` to parameter `b` again
1. Add `/*!*/` to parameter `t`

/cc @stereotype441 @MichaelRFairhurst

**Comment by MichaelRFairhurst** [comment]
Is it doing this incorrectly in the preview? or in the file system?

Had you edited the disk contents at all or was this all done through the tool?

There are also extra spaces in the top vs the bottom, is that a copy-paste error or something the tool did, something else?

**Comment by MichaelRFairhurst** [comment]
I couldn't reproduce on this exact example; however playing around I was able to occasionally get it to produce `/*?/*?*/*/` in a more complicated project.

What's strange about this is that I'd expect that to mean that the migration suggestion offset mapper is wrong, only, and that that would mean it actually was put on the right place on disk. And then I checked the disk, and it was wrong on disk. That would indicate that either the edit link was wrong originally or the disk offset mapper is incorrect.

In any case, this is clearly dependent upon pretty particular OffsetMapper circumstances.

**Comment by MichaelRFairhurst** [comment]
Seems like an intermittent issue. I am able to get it to appear at different times for the same program if I reset the file and rerun. Most likely explanation is double clicking

**Comment by MichaelRFairhurst** [comment]
Should have a CL out soon.

**Comment by yjbanov** [comment]
> Is it doing this incorrectly in the preview? or in the file system?

Both

> Had you edited the disk contents at all or was this all done through the tool?

I have not edited anything on the disk while using the tool.

> There are also extra spaces in the top vs the bottom, is that a copy-paste error or something the tool did, something else?

It's probably because I copied the top one from the tool (it uses a space in type annotations to mean "I decided this should not be null"), and the bottom from VSCode.

**Comment by MichaelRFairhurst** [comment]
https://dart-review.googlesource.com/c/sdk/+/148026

**Comment by MichaelRFairhurst** [comment]
> It's probably because I copied the top one from the tool (it uses a space in type annotations to mean "I decided this should not be null"), and the bottom from VSCode.

Ha! I forgot our own tool did this. Not having highlighting on the spaces was all it took for me to get suspicious :)
