### ISSUE TITLE
Failures on [CFE] Error when strong mode mixed with non-opted-in

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#41896]
There are new test failures on [[CFE] Error when strong mode mixed with non-opted-in](https://dart-review.googlesource.com/c/sdk/+/140868).

The tests
```
co19/LanguageFeatures/nnbd/expression_typing_A06_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/expression_typing_A06_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/expression_typing_A06_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A01_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A01_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A01_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A01_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A01_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A01_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t04 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t04 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t04 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t05 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t05 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/legacy_libraries_A04_t05 MissingCompileTimeError (expected Pass)
    and 2853 more tests
```
are failing on configurations
```
cfe-strong-linux
dart2js-hostasserts-strong-linux-x64-chrome
dart2js-hostasserts-strong-linux-x64-d8
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
```

**Comment by johnniwinther** [comment]
cc @munificent Failures are seen in ffi, standalone and co19 tests
cc @sigmundch Failures are seen in dart2js_extra tests

**Comment by eernstg** [comment]
Certainly any test with both `// Requirements=nnbd-strong` and `// @dart = 2.6` needs to be changed to require `nnbd-weak` (or if there is a strong and a weak version of that test then the strong version should probably simply be deleted), but that's only a few tests:

```
expression_typing_A06_t01.dart
future_flattening_legacy_lib.dart
overriding/override_checking_A03_opted_out_lib.dart
overriding/override_checking_A05_t01.dart
overriding/override_checking_A05_t02.dart
overriding/override_checking_A05_t03.dart
overriding/override_checking_A05_t04.dart
overriding/override_checking_A05_t05.dart
overriding/override_checking_A05_t06.dart
overriding/override_checking_A05_t07.dart
overriding/override_checking_A05_t08.dart
overriding/override_checking_A05_t09.dart
overriding/override_checking_A06_opted_out_lib.dart
type-aliases/type_reification_legacy_aliases_lib.dart
type_reification_legacy_lib.dart
```

Looks like many (about 686) others have `@dart = 2.6` and `SharedOptions=--enable-experiment=non-nullable`, so with each test mentioned 3 times that's probably it.

I'm not sure, but my first guess would be that they also need to have `// Requirements=nnbd-weak` added.

If that is all true then this issue is actually a co19 issue.

@johnniwinther, do you consider this issue to contain work which is different from the above? Otherwise I think we should create a co19 issue, link to this one for details, and close this one because the task is now maintained as a co19 task.

**Comment by johnniwinther** [comment]
All failures should be for the above reason(s).

**Comment by eernstg** [comment]
I'm closing this issue because the work is done in context of https://github.com/dart-lang/co19/issues/644. That issue refers to this one for information about which tests are affected.

**Comment by munificent** [comment]
Re-opening because Johnni says there are also non-co19 failures. I'll look into this.

**Comment by munificent** [comment]
I emailed @dcharkes about the FFI failures. I have a CL out to fix the failures under language/nnbd: https://dart-review.googlesource.com/c/sdk/+/148234

**Comment by munificent** [comment]
This should fix the dart2js failures: https://dart-review.googlesource.com/c/sdk/+/148280

**Comment by dcharkes** [comment]
I have [a CL](https://dart-review.googlesource.com/c/sdk/+/148242) that fixes `dart:ffi` in weak mode. I'll take a look today at strong mode.

**Comment by munificent** [comment]
The /nnbd/ failures are fixed by https://dart-review.googlesource.com/c/sdk/+/148234. The HTML and dart2js failures should be fixed by https://dart-review.googlesource.com/c/sdk/+/148280. The FFI failures should be covered by https://dart-review.googlesource.com/c/sdk/+/148404.

I think that's everything?

**Comment by munificent** [comment]
Oops, reopening since the first CL hasn't landed yet.

**Comment by munificent** [comment]
Closing now that that CL has landed.
