### ISSUE TITLE
Cannot infer generic class when calling generic method from generic method

### ISSUE THREAD

**Issue by marcosmko** [dart-lang/sdk#41909]
Hello! I am having some problems with flutter and this is probably related to dart.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Copy paste the following code inside `main.dart`
```dart
abstract class Bar {
}

class Foo extends Bar {
}

class SomeClass {
  T doSomething<T>() {
    return AnotherClass.doSomething();
  }
}

class AnotherClass {
  static T doSomething<T extends Bar>() {
    print(T);
    return null;
  }
}
```

3. Call 
```dart
Foo bar = SomeClass().doSomething();
```

**Expected results:** 
```I/flutter (16374): Foo```

**Actual results:** 
```I/flutter (16374): Null```

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

• No issues found!
```

</details>

It seems it works normally when I switch the 
```dart
static T doSomething<T extends Bar>() {
  print(T);
  return null;
}
```

for
```dart
static T doSomething<T>() {
  print(T);
  return null;
}
```

Is this the intended behaviour?
I noticed this behaviour occurs when one of the methods has the generic class extending another class, doesn't matter the order the functions are called.

**Comment by eernstg** [comment]
Try this:

```dart
class SomeClass {
  T doSomething<T extends Bar>() {
    return AnotherClass.doSomething();
  }
}
```

This makes it possible for the inference step to find a type (namely `T`) which will satisfy the bound on the `AnotherClass.doSomething`.

**Comment by marcosmko** [comment]
yeah @eernstg this solves the problem but I need to access the `AnotherClass.doSomething` from both 

```dart
class SomeClass {
  T doSomething<T>() {
    return AnotherClass.doSomething();
  }
}
```
and
```
class OtherClass {
  T doSomething<T extends Bar>() {
    return AnotherClass.doSomething();
  }
}
```

**Comment by eernstg** [comment]
If you call `AnotherClass.doSomething<T>()` where `T` doesn't satisfy the constraint (`T extends Bar`), as in `SomeClass.doSomething` then you simply have a compile-time error. Type inference won't use `T` as the type argument when it is a compile-time error, and that's the reason why you get `Null` (which is a subtype of the bound, until you enable null-safety).

At run time, `AnotherClass.doSomething` might rely on `T` being a subtype of `Bar`, so it's simply unsafe to call it with a type argument that violates the bound.

You can still do it dynamically, and pay the price that it might fail at run time:

```dart 
class SomeClass {
  T doSomething<T>() {
    return (AnotherClass.doSomething as Function)<T>();
  }
}
```

But the statically safe approach where you have `T extends Bar` also in `SomeClass` is of course preferable, if possible.

**Comment by marcosmko** [comment]
Ohh it worked as expected!

I'm doing some type checks before calling function, no problem if this breaks at runtime as I'm handling errors at some point.

What I'm doing is checking if T is a known type (String, int, etc) and in last case it will try to use do `AnotherClass.doSomething`.

I tried using
```
T is Bar
T == Bar
```
but the result is always false, even if T _does_ subclass Bar.

I think this happens due to flutter/dart not supporting Mirroring, though?

**Comment by eernstg** [comment]
If you want to check whether `T` is a subtype of `Bar` you can do `<T>[] is List<Bar>`.

Checking `T is Bar` is always false because `T` evaluates to an instance of `Type` that reifies the value of `T`, and `Type` is not a subtype of `Bar`. `T == Bar` is tricky (comparison of reified types for equality contains all kinds of twists), but it will evaluate to `true` when `T` is actually `Bar` (and false in other cases, including the case where `T` is a subtype of `Bar` which is not `Bar` itself).

There is no need for mirrors in order to check this, but you do pay at run time for the creation of an empty list if you use `<T>[] is List<Bar>`.

**Comment by marcosmko** [comment]
It seems it worked!!! Thank you very much!
