### ISSUE TITLE
[CP] Please partially merge #17f62d3f3ae56a1d76cbcb4410ea0ca884677c45 into stable channel

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#41907]
**commit(s) to merge**: 17f62d3f3ae56a1d76cbcb4410ea0ca884677c45

**merge instructions**: https://dart-review.googlesource.com/c/sdk/+/148127 - to limit cherry pick to a single line flag change 

**reason**: This change addresses regression in stack trace quality on Flutter stable channel - without this change users will see "optimized out" instead of function names for some of the frames in the stack trace.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @vsmenon  @franklinyow  @pcsosinski

**Comment by franklinyow** [comment]
Approved: regression, low risk
Wait for join approval, do not merge yet

**Comment by tvolkert** [comment]
flutter eng approval +1

**Comment by franklinyow** [comment]
closing
