### ISSUE TITLE
[Breaking Change Request] Support abort() in HttpClientRequest in Dart:IO

### ISSUE THREAD

**Issue by zichangg** [dart-lang/sdk#41904]
# Summary
With current APIs in Dart:IO, there is no way to abort the `HttpClientRequest`. Once `HttpClientRequest` has been sent, the request cannot be canceled until `HttpClientResponse` comes back. See the example below:

```dart 
HttpClient client = new HttpClient();
client.getUrl(Uri.parse("http://www.example.com/"))
   .then((HttpClientRequest request) {
     // Optionally set up headers...
     request.write();
     // Optionally write to the request object...
     // Then call close.
     ...
     return request.close();
   })
   .then((HttpClientResponse response) {
     // Process the response.
     ...
   });
```

Abort() will allow users to stop waiting for `HttpClientResponse`, so users can abort the request if it takes too long.

# Function signature
```dart
  abort([Object? exception, StackTrace? stackTrace]);
```

# The intended behavior
* The future returned by `close()` will complete with `exception` and `stackTrace` if abort() is called prior to `HttpClientResponse` being available. The default value for `exception` and `stackTrace` will be `HttpException` and `StackTrace.empty`.
* Data cannot be sent through `IOSink`'s API after abort().
* In case of `HttpClientResponse` returning before `abort`, abort() will not make any effect.

# Expected use case
```dart 
HttpClient client = new HttpClient();
client.getUrl(Uri.parse("http://www.example.com/"))
   .then((HttpClientRequest request) {
     // Optionally set up headers...
     request.write();
     // Optionally write to the request object...
     // Then call close.
     Timer(Duration(seconds: 1), () {
       request.abort(Exception("Customized value"));
     }); 
     return request.close();
   })
   .then((HttpClientResponse response) {
     // Process the response.
     ...
   }, onError: (e) {
      // e will be `Exception("Customized value")`
   });
```

# Expected impact
All classes extends or implements `HttpClientRequest` in Dart:IO will need to update accordingly.

# Proposed Implementation
https://dart-review.googlesource.com/c/sdk/+/147339

# Relative discussions
https://github.com/dart-lang/sdk/issues/22265

**Comment by zichangg** [comment]
@lrhn @mit-mit @sortie

**Comment by franklinyow** [comment]
Please announce your breaking change using the breaking change process
https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md

**Comment by zichangg** [comment]
@franklinyow I tried to send email to `announce@dartlang.org`. But I got "the group you tried to contact (announce) may not exist".

**Comment by franklinyow** [comment]
I'm not sure what is the problem, it may be temporary because it has announcement earlier today.  Maybe wait a bit and try tomorrow.

**Comment by zichangg** [comment]
@franklinyow I tried again with `announce@dartlang.org` and still got back the same error. Any workaround for this?

**Comment by mit-mit** [comment]
lgtm, @franklinyow can you enquire with partner teams?

**Comment by franklinyow** [comment]
cc @Hixie @matanlurey @vsmenon for review and approval.

**Comment by Hixie** [comment]
An `abort` method on the request object seems like an elegant solution.

**Comment by zichangg** [comment]
Based on some discussion in draft cl, abort() now will accept two optional parameters. Users are allowed to provide customized exception and stackTrace, which will trigger onError() callback.
@Hixie @matanlurey @vsmenon

**Comment by Hixie** [comment]
SGTM.

**Comment by zichangg** [comment]
A friendly ping. @matanlurey @vsmenon 
If it looks good, I can starting preparing fixing patch on packages and flutter. ^_^

**Comment by vsmenon** [comment]
lgtm

**Comment by matanlurey** [comment]
lgtm

**Comment by franklinyow** [comment]
Mark Approved
@zichangg Please go ahead
