### ISSUE TITLE
dart:html APIs unsupported on some browser should be nullable

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#41905]
In debugging some internal apps I've come across several APIs that are not supported in FF and Safari. These are currently marked as non-nullable because they aren't nullable in Chrome, but in those browsers they are.

So far I've run into:
* `Performance.memory`  (see https://developer.mozilla.org/en-US/docs/Web/API/Performance)
* `navigator.connection` in Safary (see https://developer.mozilla.org/en-US/docs/Web/API/Navigator)
* `navigator.connection.downlink` in FF (see https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation)

Short term we need to mark all those APIs as nullable. We should however discuss whether we should change our default (being more lax about nullability, or cross referencing them with some other database).

**Comment by sigmundch** [comment]
@srujzs could you take a look at making those APIs nullable for now?

We should meet to discuss the possibility of being more conservative at first (sprinkle more nullable APIs for now) or to validate with something like the dom d.ts or a way to load the MDN in an automated fashion.

/cc @rakudrama

**Comment by sigmundch** [comment]
@vsmenon @jacob314 - are you aware of a location where the MDN information can be downloaded in a machine format that we can use as input for this?

For what it's worth, none of the APIs above that have issues appear in the typescript d.ts file: https://github.com/microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts

**Comment by sigmundch** [comment]
Another one: `HtmlElement.nonce` and `NonceElement.nonce` getters

**Comment by srujzs** [comment]
Dart changes have been merged. Closing.
