### ISSUE TITLE
ensure hot restart on flutter web is as smooth as before the unfork

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#41917]
For context see: https://github.com/flutter/flutter/issues/56844

@Markzipan @nshahan @jonahwilliams

**Comment by jonahwilliams** [comment]
I'm not able to reproduce any problems with hot restart on the latest master, beyond the extra warnings in the console.

**Comment by Markzipan** [comment]
Likewise. As far as I can tell, hot restart with text works as expected, and image asset restart behavior matches that of 1.17.1. I'm digging into the mouseover issues but will follow up if assets start poofing.

**Comment by sigmundch** [comment]
Thanks @jonahwilliams and @Markzipan - sounds like the only remaining work item then would be to hide the warnings unless the user intended to enable the non-nullable experiment?

**Comment by devisions** [comment]
@jonahwilliams @Markzipan Please note that #56844 was opened considering version `1.19.0-1.0.pre.26` and the latest reported state of unfunctional hot reload was on `1.19.0-2.0.pre.71`.
Therefore, why this issue is related to that and at the same time referring the `1.17.1`?
Just asking to understand. Thanks

**Comment by Markzipan** [comment]
I have a poor mental model of the intended hot restart behavior across our various platforms, so I was running Flutter Gallery at both 1.17.1 and master for comparison purposes. I chose 1.17.1 since this was well before any of DDC's changes were in.

The only differences I observed were the errors mentioned above, but I didn't test extremely holistically. But agreed that we should hide weak mode errors from users who aren't explicitly opted in to them @sigmundch

**Comment by devisions** [comment]
No worries. Moreover, the initial issue was strictly related to the Web side.
Now, switching back to stable channel, the setting initially configured at the project level while being on that 1.19 version (being in channel beta and using `flutter config --enable-web`) is not available in 1.17:
```shell
$ flutter config
...
Settings:
  enable-web: true (Unavailable)
```
Again, just trying to help here clarifying the scope.

**Comment by Markzipan** [comment]
From the master channel, using `flutter version 1.17.1` makes that option available. I can verify that the dart sdk between these two settings were pre and post null-safety fork, so the observations should still be valid.

**Comment by devisions** [comment]
Understood. Can you please share how to downgrade to that version?
Currently, on master there is version `1.19.0-2.0.pre.73`.

**Comment by devisions** [comment]
Just tested with `1.17.1` from master and indeed the only remaining issue is related to hot reload/restart. Currently, it clears the state (just like a standard (non-hot) restart).

Now, looking more carefully on reload vs restart, I would conclude that:
- Flutter for Mobile can do _hot reload_
  - started using `flutter run -d 15EE266C-5835-4AB4-B78C-7F7FA80C6876`
  - that `15EE...` being the identifier of a Simulator (I'm on macOS)
  - the output mentions about using "r" for hot reload (that keeps the state)
  - and this is correctly aligned with [website's "Hot reload" article](https://flutter.dev/docs/development/tools/hot-reload)
- Flutter for Web can do only _hot restart_
  - started using `flutter run -d chrome`
  - the output mentions about using "r" for hot restart (that doesn't keep the state)

The same ["Hot reload" article](https://flutter.dev/docs/development/tools/hot-reload) explictly mentions that:
> Flutter web currently supports hot restart but not hot reload.

So, I would say that IDE's should explicitly reflect that capability or the lack of it.

Currently, VSCode's toolbar mentions about "Hot reload" even when selecting "chrome" device, and that definitely is misleading. And people - myself included - would quickly conclude that there's a Flutter bug. Which is not. At least not for now.

**Comment by jonahwilliams** [comment]
@devisions this is not an issue about clarity of hot restart or hot reload. If you have concerns whether the IDEs are surfacing the information correctly, please file an issue there.

**Comment by Markzipan** [comment]
The mouse errors are independent of this change. I think there was a regression in flutter. See: https://github.com/flutter/flutter/issues/57347

**Comment by sigmundch** [comment]
closing this issue now that I believe there are no pending action items (@nshahan  / @Markzipan  please reopen if I'm mistaken)
