### ISSUE TITLE
Notification.permission not accessible

### ISSUE THREAD

**Issue by vekexasia** [dart-lang/sdk#41911]
It looks like there is a regression since: https://github.com/dart-lang/sdk/issues/20585#issuecomment-629234693
as Notification.permission cannot be accessed statically.

**Comment by srawlins** [comment]
Looks like @srujzs committed this change here: https://github.com/dart-lang/sdk/commit/80f84e19421ed813e1d2961466d45c11c2229f4e#diff-2326766614acd647cd69f60e35033cc2

Possibly inadvertent to drop the `static`?

**Comment by srujzs** [comment]
Yeah, this is an issue. This was missed during the transformation of fields to natives. I'll take this on to handle this and similar transformations of static fields.
