### ISSUE TITLE
TSAN failure in limited_active_mutator_test

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#41916]
limited_active_mutator_test is a new test introduced by [this cl](https://dart-review.googlesource.com/c/sdk/+/148121), and it's failing on the AOT tsan bot.

Logs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8880231086170148016/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by mkustermann** [comment]
Merging into existing https://github.com/dart-lang/sdk/issues/41912
