### ISSUE TITLE
Let Duration() implement num

### ISSUE THREAD

**Issue by ChristianKleineidam** [dart-lang/sdk#41929]
Currently functions of the _math_ package like `sum` can't be used with `Duration()` because `Duration()` doesn't implement `num`. It feels strange that I have to implement my own function to sum durations in dart. 

`.toInt()` and `.toDouble()` could call `.inMicroseconds()`. Addition of substraction with other nums could also call them so that the result is `int` or `double`.

**Comment by znjameswu** [comment]
Then you need to justify every num-related operation for Duration. Including, 5.0 / duration,  duration * duration and pow(duration1, duration2). A type system is meant to eliminate those erroneous invocations, and subclassing must strictly follows "is-a" relationship. 

For a list of durations, you can simply `durations.map((duration) => duration.inMicroseconds())` and continue to process them as numbers.

**Comment by ChristianKleineidam** [comment]
I think you can simply throw `UnsupportedError` for those operation.

If I want a sum you are right that I can define sum as:
```
sumDurations(List<Duration> durations){
  return Duration(microseconds: sum(durations.map((duration) => duration.inMicroseconds()))
}
```
I however don't see why such an operation is not supported by the standard library and the developer should have to define his own functions for common operations like this.

If it's not desired to throw any  `UnsupportedError` it might be useful to define an abstract class `numerical` that defines behavior for `+` and `-` but not `*` and `/` which `num` implements and define operations such as sum over `numerical` instead of `num`. That we any custom class that wants to be able to be summed can also implement `numerical`.

**Comment by alfinbi** [comment]
it means we will have no benefits of type system if 'simply throw', we will only know the error at runtime, and not while writing the code. [package:time](https://pub.dev/packages/time) and [package:basics](https://pub.dev/packages/basics) should do the jobs you need without sacrificing static type

**Comment by mraleph** [comment]
I'd say it is extremely unlikely that any new types would be made to extend `num`. 

but I let @lrhn make the final call and close this issue.

**Comment by lrhn** [comment]
Making `Duration` implement `num` won't happen for many reasons, including those mentioned by @znjameswu.

Dart does not have an interface like `abstract class Addable<T> { T operator+(T other); }` so that we can write `T sum<T extends Addable<T>>(Iterable<T> values) => values.fold((a, b) => a + b);`.
No current plans to add it either, it's too specialized.
(No Monoid class. It would make a great trait).
