### ISSUE TITLE
Analyzer crashes on migrated if_null tests

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#41920]
There are new test failures on [Migrate language_2/if_null to NNBD.](https://github.com/dart-lang/sdk/compare/02b50e40791bee4acf77237405bca561ad2b9e72~...80bd1d5970be9962aa033f7825b95c49fd1299b5).

The tests

```
language/if_null/assignment_behavior_runtime_26_test Crash (expected Pass)
language/if_null/assignment_behavior_runtime_27_test Crash (expected Pass)
language/if_null/assignment_behavior_test Crash (expected Pass)
```

are failing on configurations

```
analyzer-asserts-strong-linux
analyzer-asserts-weak-linux
```

**Comment by scheglov** [comment]
Fixed in 08bad91aa3a5e3edf6004fe690f4ee6eaf33fe81.
