### ISSUE TITLE
Hide console window in dart2native executable on Windows?

### ISSUE THREAD

**Issue by anirudhrata** [dart-lang/sdk#41926]
Hello guys, I just started using dart2native to build executables on Windows platform. Is there a way to run the executable without the cmd console window popping? My use case is that I want to run a slightly time taking process like few file and network operations without having a console window showing up on user's desktop.

Thanks

**Comment by mraleph** [comment]
Right now the simplest way to do it is to flip bit in PE header of the resulting binary using a third party tool. See [answers here](https://stackoverflow.com/questions/2435816/how-do-i-poke-the-flag-in-a-win32-pe-that-controls-console-window-display/14806704).

**Comment by anirudhrata** [comment]
Thanks a ton @mraleph. This is exactly what I was looking for. Hopefully there will be no impact on any functionality that I've.
