### ISSUE TITLE
DDC strong mode failing late initialization with init function called twice

### ISSUE THREAD

**Issue by rileyporter** [dart-lang/sdk#41922]
DDC is failing for these two co19 tests on an edge case with late initialization:

- [co19/LanguageFeatures/nnbd/late_A04_t04.dart](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/late_A04_t04.dart), failing ddc strong mode [logs](https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/3098/co19/LanguageFeatures/nnbd/late_A04_t04)
- [co19/LanguageFeatures/nnbd/late_A05_t02.dart](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/late_A05_t02.dart), failing ddc strong mode [logs](https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/3098/co19/LanguageFeatures/nnbd/late_A05_t02)

A small repro is: 
```
import "package:expect/expect.dart";

bool _called = false;

String init(String val) {
  if (!_called) {
    _called = true;
    throw new Exception();
  }
  return val;
}

class C {
  static late String? s = init("lateValue");
}

main() {
  Expect.throws(() {C.s;});
  Expect.equals("lateValue", C.s);
}
```

Where the `Expect.equals("lateValue", C.s)` fails because `C.s` is null after the second call to the `init` function.  This test passes if `String? s` is declared as non-nullable `String s` or `final String? s`. 

This test also passes if the second call to `init` is removed with the logic for throwing an exception. For example, this passes:
```
import "package:expect/expect.dart";

String init(String val) {
  return val;
}

class C {
  static late String? s = init("lateValue");
}

main() {
  Expect.equals("lateValue", C.s);
}
```

**Comment by Markzipan** [comment]
CFE lowers these late constructs to something like:
```
  class C extends core::Object {
    static field core::String? _#s = null;
    static field core::bool _#s#isSet = false;
    synthetic constructor •() → test::C
      : super core::Object::•()
      ;
    static get s() → core::String? {
      if(!test::C::_#s#isSet) {
        test::C::_#s#isSet = true;
        test::C::_#s = test::init("lateValue");
      }
      return test::C::_#s;
    }
    static set s(core::String? #t1) → void {
      test::C::_#s#isSet = true;
      test::C::_#s = #t1;
    }
  }
```
@johnniwinther, what do you think about setting the `isSet` flag after running the initializer expr? E.g.,
```
  class C extends core::Object {
    static field core::String? _#s = null;
    static field core::bool _#s#isSet = false;
    synthetic constructor •() → test::C
      : super core::Object::•()
      ;
    static get s() → core::String? {
      if(!test::C::_#s#isSet) {
        test::C::_#s = test::init("lateValue"); // swapped
        test::C::_#s#isSet = true;              // swapped
      }
      return test::C::_#s;
    }
    static set s(core::String? #t1) → void {
      test::C::_#s#isSet = true;
      test::C::_#s = #t1;
    }
  }
```

**Comment by johnniwinther** [comment]
We should. I've created https://dart-review.googlesource.com/c/sdk/+/148800 that fixes this.
