### ISSUE TITLE
dart2js: DeferredLoadTask takes too much memory

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#41925]
A large app compile was exhausting allocated process memory

Basic statistics:
- 401 deferred libraries (_N_)
- 5682 output units (_U_) (about 4000 non-empty)
- 2.9M ImportSet instances (_S_)
- 283M List elements in import sets (_E_)

The number of output units is not the problem discussed here - this can be addressed by merging (See https://github.com/dart-lang/sdk/issues/29686)

### Memory leak
The 5GB of heap data allocated for the above structures appears not to be freed. https://dart-review.googlesource.com/c/sdk/+/148226 allows the 5GB to be recovered.

### Too many lists
The number of List elements E appears to be O(_N_<sup>3</sup>).

Each `ImportSet` is built from a predecessor by adding one element in a canonical order.
```
{} → {3} → {3,7} → {3,7,10} → {3,7,10,11}
```
Each node is storing a list of the elements thus far. This is clearly O(_L_<sup>2</sup>) where _L_ is the length/size of the set.  This information is redundant with the derivation of the set and can be recovered with a back- or parent- pointer:
```
                  11    {3,7,10,11}
                 ↙
              10        {3,7,10}
             ↙
           7            {3,7}
         ↙
       3                {3}
     ↙
   -                    {}
```

### The worklist algorithm creates 'unnecessary' ImportSets.
The original algorithm would visit all dependencies for import#1, then all the dependencies for import#2, etc. This would never create an ImportSet that was not a prefix of some final ImportSet.
Handling each import separately is slow because many deferred imports have the same transitive imports and these dependencies are re-visited for each import.

To solve the slow performance due to repeated work, the worklist algorithm works on sets of imports. It is seeded by the entry point for each deferred import, and does a breadth-first traversal of the dependencies. Elements that are already pending in the worklist aggregate the set of imports which depend on them, so when they are removed from the worklist for processing, the dependency traversal is batched, reducing the overhead.

This seems to work well, but does generate 'unnecessary' intermediate ImportSets that are not a prefix of any OutputUnit's ImportSet.
We can see this if we histogram ImportSets by size. These are the most common sizes:
```
[count]          [size]
19371	ImportSet 43
19400	ImportSet 49
19430	ImportSet 48
19433	ImportSet 44
19441	ImportSet 45
19460	ImportSet 47
19462	ImportSet 46
```
There are 19462 distinct import sets of size 46, but only 5682 output units. At most 5682/19462 of the import sets of size 46 can be prefixes of the import sets characterizing the output units. (It is likely that almost none of these are prefixes of an output unit). What I believe is happening is that the FIFO worklist tends to collect some of the imports, but not all. (Analogous to first computing, say, `{7,11}` in the above representation example and then having to add 3 and 11 later).

_Is there some way of prioritizing the worklist to reduce computation and memory?_

Prioritizing the worklist item with the lowest unprocessed import# will devolve to the original algorithm, processing each import through the dependencies
Prioritizing the worklist item with the most unprocessed imports will devolve into processing pairs.
The FIFO BFS-like worklist might be the best option.

### Alternative ImportSet implementations
An interesting observation is that only 103189 of the 2.9M ImportSets (3.5%) are the result of a union operation. The rest must be prefixes of a union result.
The node-and-prefix representation can be thought of as a poorly balanced tree, making a random single 'insertion' be O(N). We could use a canonicalizing tree structure by adapting a Treap or a Big-endian Patricia Tree where a random single 'insertion' would be O(log N). The logarithmic advantage might not materialize as the worst-case union is O(N+M) rebuilding the whole tree, no advantage over a list.

### Alternative overall algorithm
The partitioning works on the dependency graph. It is somewhat on-line since new 'roots', the deferred-loaded libraries, are discovered on-line. It might still be possible to do a DFS search from a fake 'root' that calls `main`, with the discovered imports being added as edged from the root. The DFS could construct a DAG of strongly connected components that could be used as a single pass to compute and assign the partition. What is not clear is
- how much extra storage is required to maintain per-node information for the DFS
- whether the dependencies are structured so that strongly connected components offer enough summarization to be worthwhile. Inheritance, for example, is not cyclic.

**Comment by rakudrama** [comment]
Memory leak fixed by 516ad5ce1c5f2a6dde4b616a76a159256c105baf

**Comment by rakudrama** [comment]
Too many Lists fixed by c1486bcb2433089db71e129df6be0222fb42938a

**Comment by joshualitt** [comment]
I'm closing this issue because I believe we've done a lot of work trimming the memory usage of this task and reducing the memory further is not currently a priority.

**Comment by sigmundch** [comment]
I'm wondering if we should consider keeping this open but in an icebox instead.
