### ISSUE TITLE
Implicit downcast on assert message

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#41923]
Given:

```dart
main() {
  Object obj = "message";
  assert(true, obj);
}
```

It looks like neither analyzer nor CFE report an error on the message when treating this as an opted in library. Since we're getting rid of implicit downcasts, I would expect an error here. Is this an omission in the spec? Implementations? Both?

@leafpetersen

**Comment by leafpetersen** [comment]
The spec says:

```
It is a compile-time error if the type of $c$ may not be assigned to \code{bool}.
```

So I think this is a bug in the implementations.

**Comment by munificent** [comment]
I do get an error if the *condition* argument isn't a bool. This is about the second optional *message* argument.

**Comment by rakudrama** [comment]
I though that the 'message' argument to `assert` could be any type.
It is a shame to force computing a message string (which could throw, obscuring the problem).
The AssertionError can attempt the .toString() while guarding against exceptions.

**Comment by leafpetersen** [comment]
> I do get an error if the _condition_ argument isn't a bool. This is about the second optional _message_ argument.

Sorry for the noise - I lost track of what was being asked.  There are no specified errors and warnings around the second argument that I can see.  The specified semantics are just that the second argument is interpolated into a String.

**Comment by munificent** [comment]
Ah, OK. So everything is working as intended then. Thanks!
