### ISSUE TITLE
`print-instructions-sizes-to` prints hashcode

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#41934]
Sometime between May 2 and today, `print-instructions-sizes-to` behavior has changed. Looking at the output of `compare_sizes` script back back in May 2:

```
+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+--------------+
| Library                                                    | Method                                                                                                           | Diff (Bytes) |
+------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+--------------+
| package:flutter/src/rendering/flex.dart                    | RenderFlex.performLayout                                                                                         |        +8740 |
| package:flutter/src/rendering/flex.dart                    | ContainerRenderObjectMixin._insertIntoChildList                                                                  |        +1312 |
| package:flutter/src/rendering/flex.dart                    | RenderBoxContainerDefaultsMixin.defaultPaint                                                                     |         +680 |
| package:flutter/src/widgets/overlay.dart                   | _RenderTheatre.computeDistanceToActualBaseline                                                                   |         +596 |
| package:flutter/src/rendering/stack.dart                   | RenderBoxContainerDefaultsMixin.defaultComputeDistanceToHighestActualBaseline                                    |         +588 |
```

Now, I see what looks like `hashCode`s in the method strings.

```
+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------------+
| Library                                             | Method                                                                                                                     | Diff (Bytes) |
+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------------+
| package:flutter/src/widgets/navigator.dart          | NavigatorState._flushHistoryUpdates@424124995                                                                              |        +5272 |
| package:flutter/src/material/scaffold.dart          | _ScaffoldLayout@212420462.performLayout                                                                                    |        +4132 |
| package:flutter/src/rendering/mouse_tracking.dart   | MouseTracker._dispatchDeviceCallbacks@310325758                                                                            |        +3576 |
| package:flutter/src/widgets/focus_traversal.dart    | FocusTraversalPolicy._sortAllDescendants@423280150                                                                         |        +3216 |
| package:flutter/src/widgets/app.dart                | _WidgetsAppState@421236006.basicLocaleListResolution                                                                       |        +3128 |
| package:flutter/src/rendering/object.dart           | _SwitchableSemanticsFragment@311266271.compileChildren.<anonymous closure @143276>                                         |        +2692 |
```

Since these are dynamic, it leads to wrong reports. I see biggest positive delta as:

```
| package:flutter/src/widgets/navigator.dart          | NavigatorState._flushHistoryUpdates@424124995                                                                              |        +5272 |
```

biggest negative delta as:

```
| package:flutter/src/widgets/navigator.dart          | NavigatorState._flushHistoryUpdates@429124995                                                                              |        -5272 |
```

Note the single digit change (4 -> 9) in the ID.

**Comment by mehmetf** [comment]
FYI @mraleph

**Comment by mraleph** [comment]
Yeah, this is the result of fixing an issue with duplicated names. I am going to update comparison script next.

**Comment by mehmetf** [comment]
Thanks! Please /cc me on the PR. I am re-implementing the comparison script in Java because we need to integrate with some other infra framework which does not support running Dart code. The comparison script is relatively stable and not a lot of code so I am willing to maintain it. We will put checks in google3 so that we get alerted when its code changes.

**Comment by mehmetf** [comment]
@mraleph We have released the comparison script to production. While this is not a very high impact, I would like to fix it asap.

Is it just a matter of stripping `@[0-9]*` from the symbol name? If yes, I can go ahead and fix this in the Java implementation.

**Comment by mraleph** [comment]
I have a work in process CL here now: https://dart-review.googlesource.com/c/sdk/+/150101. It is in "dirty state" - needs few refactorings and cleanups, but it reflects where the comparison script is going.

> Is it just a matter of stripping `@[0-9]*` from the symbol name?

If you want a simple solution you need to do equivalent of `name.replaceAll(RegExp(r'\s*@\d+|\(H[a-f\d]+\) '))` - that should remove the unstable portion of the name. 

Note: this would also introduce duplicated names into the output - so you need to be able to handle that.

**Comment by mehmetf** [comment]
Thanks for this. It seems like if I generate a class level report, I don't need to deal with any function name massaging, right? I will do that for now and will add function level report later if needed. TBH, we can create the automated report at class level and instruct users to run this tool if they want more detailed comparison.

**Comment by mraleph** [comment]
> It seems like if I generate a class level report, I don't need to deal with any function name massaging, right?

Yep, that is correct.

**Comment by mraleph** [comment]
`package:vm_snapshop_analysis` now handles the output gracefully by scraping private library key from names (see `class Name` for details).
