### ISSUE TITLE
i have switch stable to beta channel but still facing this issue

### ISSUE THREAD

**Issue by junaidhashmi** [dart-lang/sdk#41931]
Compiler message:
/Users/qasimali/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;

**Comment by srawlins** [comment]
Thank you for opening this bug; please indicate how you were presented with this error message. Did this print while running the analyzer? While running `flutter test`? Did IntelliJ or Android Studio print this message? Are you writing a Flutter app? A Flutter-for-web app?

**Comment by junaidhashmi** [comment]
when i run the application then i face this issue
![Screenshot 2020-05-16 at 1 37 09 PM](https://user-images.githubusercontent.com/17546523/82176855-5e9b5580-98f1-11ea-9dc1-a448d59c477a.png)

**Comment by srawlins** [comment]
What application are you running?

**Comment by a-siva** [comment]
@junaidhashmi can you provide us with detailed instructions on how we can reproduce the error you are encountering, that would help us investigate and have a solution for you.

**Comment by mraleph** [comment]
Closing as stale.
