### ISSUE TITLE
Access from static members to members from extensions.

### ISSUE THREAD

**Issue by vr19860507** [dart-lang/sdk#41938]
It crashes during compilation, but does not show an error while writing code.

```
void main() {
  print(A.meth);
}

extension ExtA on A {
  String get value => '777';
}

class A {
  static String get meth => value;
}
```

**Comment by Abdusin** [comment]
You cannot access the data in the extension class from the main class.
```
void main() {
  A a =A();
  print(a.value);
}

extension ExtA on A {
  String get value => '777';
}

class A {
  //somethink
}
```
you can use Like this

**Comment by mraleph** [comment]
Seems like a missing compile time error in the analyzer, it seems to resolve `value` in a static method thinking that it refers to the extension member, which does not seem to be correct to me /cc @scheglov

**Comment by vr19860507** [comment]
> You cannot access the data in the extension class from the main class.
> 
> ```
> void main() {
>   A a =A();
>   print(a.value);
> }
> 
> extension ExtA on A {
>   String get value => '777';
> }
> 
> class A {
>   //somethink
> }
> ```
> 
> you can use Like this

Of course I can’t. That's why I created this issue. Because the analyzer allows this.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/148501

**Comment by srawlins** [comment]
The analyzer now reports:

> error • Instance members can't be accessed from a static method. • a.dart:10:29 • instance_member_access_from_static
