### ISSUE TITLE
i have switched stable to beta channel but still facing this issue

### ISSUE THREAD

**Issue by junaidhashmi** [dart-lang/sdk#41932]
Compiler message:
/Users/qasimali/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;****

**Comment by srawlins** [comment]
Duplicate of #41931
