### ISSUE TITLE
[analyzer] Support external fields.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#41940]
[Edit eernstg May 20: Updated links.]

The analyzer does not support `external` fields yet.

The CFE does as of last week (383a8ea85736229217f0dc8fdd825533b8004104).

Language proposal: https://github.com/dart-lang/language/pull/969, tests: https://dart-review.googlesource.com/c/sdk/+/148324.

Creating an issue to point to and track progress.

cc @stereotype441

**Comment by eernstg** [comment]
This work still needs to be prioritized and planned., but the proposal itself is taking shape: cf. the feature spec in https://github.com/dart-lang/language/pull/969 and the tests in https://dart-review.googlesource.com/c/sdk/+/148324.

**Comment by stereotype441** [comment]
As of 33849927c97af61d65931cf06eb025b74c6987e2, the analyzer fully supports abstract fields and external fields/variables.
