### ISSUE TITLE
Migrator: Fix Variables._createDecoratedElementType crash

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41957]
This is the 4th most frequent crash on the p2 trial migration list. Here is the line printed by trial_migration:

> Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:364:7) (pageloader x2338, intl_translation x4)stream_transform x1)

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
