### ISSUE TITLE
'dart analyze' fails to launch the analysis_server on Windows

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#41953]
Fails with the following error:

```
C:\Users\bkonyi\dart-sdk\sdk>out\ReleaseX64\dart-sdk\bin\dart analyze
Analyzing sdk...
CreateProcessW failed 2
ProcessException: The system cannot find the file specified.

  Command: .\bin\dart.exe .\bin\snapshots\analysis_server.dart.snapshot --disable-server-feature-completion --disable-server-feature-search --sdk .
```

cc/ @devoncarew @jwren

**Comment by srawlins** [comment]
@devoncarew do we need a new pkg-dartdev label, or some such thing?

**Comment by devoncarew** [comment]
Michael created an `area-dart-cli` (I updated the labels for this issue).

**Comment by devoncarew** [comment]
@jwren - perhaps this path - `.\bin\snapshots\analysis_server.dart.snapshot` - should be an absolute path (joined with the sdk resolved path)?

**Comment by jwren** [comment]
https://dart-review.googlesource.com/c/sdk/+/148660

**Comment by jwren** [comment]
I believe that this should be fixed, @bkonyi -- can you confirm when you have the SDK on Windows next?

**Comment by bkonyi** [comment]
Confirmed to be working on Windows. Thanks!
