### ISSUE TITLE
[frontend_server] ExpressionCompiler tests should evaluate javascript

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#41959]
ExpressionCompiler currently has tests that match javascript generated by DDC, which is unnecessarily inflexible with changes in DDC, and also does not always ensure the code would run as expected. Replace matching javascript by actual evaluation of javascript and checking the result.

Pointers to existing libraries and existing tests with a similar architecture:
`package:webdriver`: a library to control the browser externally, works with chrome and FF deobfuscation end-to-end tests. Currently we have them in google3, ideally we'd like to have a similar test in our SDK:
test live in: `http://google3/javatests/com/google/dart/debugging/`
it uses webdriver to launch each test
tests are specified as input + expect golden files: `http://google3/javatests/com/google/dart/debugging/input`

**Comment by annagrin** [comment]
@Markzipan should we close this now that you have implemented the e2e tests?

**Comment by Markzipan** [comment]
Yes - closing this!
