### ISSUE TITLE
Is it allowed to define a setter in extension on class that has the getter ?

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#41967]
I get an error with the following code but I would have guess it worked. Is it the expected behaviour?

```dart
class A {
  String get a => null;
}
extension on A {
  set a(String value) {}
}

main(){
  A().a = ''; // error: There isn’t a setter named 'a' in class 'A'
}
```

**Comment by eernstg** [comment]
Yes, getters and setters are bundled into a single entity in the sense that a lookup for any of the two will find either kind, and commit to using the scope where it was found.

So if you look for a setter `a=`  and find an instance getter `a` in the enclosing scope, then the setter _must_ also be an instance setter (that is: it must come from the same scope):

```dart
void set a(_) {}

class A {
  String get a => '';
  void foo() { a = 'Hello'; } // Error!
}
```

**Comment by a14n** [comment]
Thanks for the explanation!
