### ISSUE TITLE
[CP] Please merge 2fa4d3e4d88cf1b0b34f98392e43c3d1ff4723c7 into stable channel #41928

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#41972]
**commit(s) to merge:** 2fa4d3e4d88cf1b0b34f98392e43c3d1ff4723c7

**merge instructions:** Conflicts resolved in https://dart-review.googlesource.com/c/sdk/+/148645

**reason:** Crashes due to assertion failure. E.g., b/156940113

@franklinyow @pcsosinski @a-siva

**Comment by pcsosinski** [comment]
any indication that this is affecting 1.17 flutter users?

**Comment by mit-mit** [comment]
Yes, this affects Flutter apps (we're seeing a number of crashes internally in a Flutter app)

**Comment by franklinyow** [comment]
Dart approved

**Comment by tvolkert** [comment]
It looks like 2fa4d3e contains no tests?

**Comment by franklinyow** [comment]
@rmacnak-google @mkustermann Can you sync with @tvolkert about the test?

**Comment by athomas** [comment]
@franklinyow Since this is not approved by Flutter, yet, I removed the `cp-approved` label.

**Comment by mkustermann** [comment]
@rmacnak-google Did you manage to make a reproduction test case for this?

**Comment by franklinyow** [comment]
Ping @rmacnak-google

**Comment by a-siva** [comment]
Writing a reproducible unit test case that reliably triggers this condition is hard, I don't think we can come up with such a test case.
The fix was made based on the assertion seen and code inspection around the assertion.

**Comment by pcsosinski** [comment]
I'm not seeing enough issues reported in the wild to think we need this for a cherrypick to stable.  if you are seeing something different, please add the issues in this bug.  thanks

**Comment by franklinyow** [comment]
Marked cp-denied because it didn't get join approval
