### ISSUE TITLE
SSALivenessAnalysis compute parameters with the UnboxedInt64 representation incorrectly

### ISSUE THREAD

**Issue by linzj** [dart-lang/sdk#41977]
SSALivenessAnalysis forgets to handle pair representation when handing BlockEntryWithInitialDefs.

**Comment by mraleph** [comment]
Good catch. I will fix this.

**Comment by linzj** [comment]
I have submitted a review:
https://dart-review.googlesource.com/c/sdk/+/148602

So the system is isolated here and googlesource?

**Comment by mraleph** [comment]
Thanks for the fix! I approved it and it is going through the CQ now. 

GitHub is used as a mirror and for issue tracking, Gerrit (googlesource) is used for code reviews, CQ (commit queue) and as a primary Git repository. 

You can also make PRs against this repository (if you think PR workflow is simpler) they will be automatically mirrored to Gerrit.

**Comment by mraleph** [comment]
@linzj if you have a minimal regression test (e.g. was this causing a crash or assertion failure?) then you should submit it as a separate change as well.

**Comment by linzj** [comment]
I met this bug when testing my llvm code gen. 
When collecting stack map information,  the function entry required the higher bits in a int64 parameter live in from the predecessor block.  But this value was not defined(killed)  in the predecessor block.  So triggered my assert.
