### ISSUE TITLE
NNBD. No compile time error when read of local late definitely unassigned variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41981]
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings)

> It is a compile time error to read a local variable marked late when the variable is definitely unassigned

But in the following code it's not true

```dart
main() {
  late int i;
  Null n = null;
  if (n != null) {
    i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
  }
  i;  // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
This code produces no Issues in analyzer and `LateInitializationError` in CFE. There must be a compile time error here

`Dart VM version: 2.9.0-10.0.dev (dev) (Tue May 19 15:16:48 2020 +0200) on "windows_x64"`

**Comment by mkustermann** [comment]
In this case it's easy to see the code is dead, but in general, it is undecidable whether certain code is dead or not.

/cc @lrhn @eernstg

**Comment by eernstg** [comment]
I believe the rules in [flow-analysis.md](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md) about `if` statements and the `notNull` continuation of `n` and the `true` continuation of `n != null` should make the `unreachable` bit for the "then" branch of the `if` true, so the flow analysis should conclude that `i` is definitely unassigned after the `if`.

**Comment by eernstg** [comment]
I think we should use area-front-end for this, because it is about the implementation of flow-analysis.md.

**Comment by stereotype441** [comment]
Finally getting a chance to look at this.  I believe what's happening is that `if (n != null)` is promoting `n` to type `Never`, but we don't have any logic that says "if we promote a variable to type `Never`, then consider the code to be unreachable", so we don't recognize that the body of the `if` is dead code.  (We have logic that says "if an expression has type `Never`, then consider the code to be unreachable", which is very similar, but not exactly the same).

I think this corner case is worth fixing.  I'll try to get it fixed soon.
