### ISSUE TITLE
What is the purpose of const[] 

### ISSUE THREAD

**Issue by revenantcoder** [dart-lang/sdk#41995]
Hi, 

Can anyone please tell me the purpose of the following statement

**var list = const[1, 2, 3];**
or
**var list = const [];**

Thanks and regards,
Amit Verma

**Comment by a-siva** [comment]
Please see https://dart.dev/guides/language/language-tour#final-and-const for an explanation of `const`.
The gist of it is
 'Use const for variables that you want to be compile-time constants. If the const variable is at the class level, mark it static const. Where you declare the variable, set the value to a compile-time constant such as a number or string literal, a const variable, or the result of an arithmetic operation on constant numbers'

**Comment by revenantcoder** [comment]
@a-siva you didn't get my Question and you closed the issue.. If you don't know the answer then please don't reply and close it.. i know what const, final and static are... 
Now i know the Answer to my Question, i found out yesterday but i want you to reply bcoz you closed it... 
**WHAT IS THE _PURPOSE_ OF THIS STATEMENT ?**
var list = const[1, 2, 3];

**Comment by a-siva** [comment]
It is great that you found the answer to your question.
Please refrain from such comments that serve no purpose.

**Comment by revenantcoder** [comment]
@a-siva Did I ask what are const variables ? NO.. my question was "what is the purpose of var list = const []; and you explained me about const variables and closed the issue.. that's what i didn't like.. So, please close the issue when the creator of the issue is satisfied..

**Comment by Michael35699** [comment]
In my understanding, `var list = const[]` just assigns an immutable `List<dynamic>` to variable named `list`, but you can reassign for later.
