### ISSUE TITLE
nnbd: return type of dart:io exit should be Never

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42006]
Since no code will run after it, etc.

**Comment by kevmoo** [comment]
CC @natebosch 

Thoughts @lrhn @a-siva ?

**Comment by lrhn** [comment]
Agree.
Any function which will definitely not return a value should have type `Never`.

**Comment by a-siva** [comment]
Is this what you had in mind https://dart-review.googlesource.com/c/sdk/+/148920

**Comment by natebosch** [comment]
That LGTM.

I _think_ this is only breaking if you consider new dead code warnings breaking which AFAIK we don't. We might want to do a trial in google3 to verify if any cleanup needs to happen first.

cc @davidmorgan

**Comment by davidmorgan** [comment]
Actually we do--we are strict about dead code. Flutter likely is too: dead code is a hint, not a lint, so enabled by default.

I'd say it's pretty low risk--looking at uses of `exit` in google3 I didn't see any obvious issues. There's one case in `package:test_runner` but that's only used in the SDK itself, where it will be harmless as we don't insist on the SDK passing analysis.

```
    }).catchError((e) {
      // TODO(floitsch): should we try to report the stacktrace?
      print("Process error:");
      print("  Command: $executable ${arguments.join(' ')} ($_arguments)");
      print("  Error: $e");
      // If there is an error starting a batch process, chances are that
      // it will always fail. So rather than re-trying a 1000+ times, we
      // exit.
      io.exit(1);
      return true;
    });
```
