### ISSUE TITLE
regress_194523002_test should not use registerElement

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#42008]
`lib/html/custom/regress_194523002_test` uses `registerElement` which has been deprecated and removed in Chrome 80. In order to replicate the same behavior, window.customElements.define is preferred instead. See https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement for more details.

**Comment by sigmundch** [comment]
Note that currently we don't support customElements.define, so we may need to drop this test or use the web_components polyfill to run it.

For context, CustomElements were implemented for Dart when the spec was at version 0.5. It was later noticed that the newer APIs required defining ES6 classes in a way that was not easily compatible with Dart, so we are not fully supporting the new API in Dart at this time.

I am not sure, but I don't believe window.customElements.define will work from Dart at this time. IIRC, our proposal was to rely on JS-interop for custom elements in the future.

**Comment by sigmundch** [comment]
Here is the issue describing our decision on not adding support for custom-elements v1 (dart-lang/sdk#27445)

**Comment by kevmoo** [comment]
We're going to deprecate registerElement
