### ISSUE TITLE
Types from non-opted in libraries can appear non-nullable when they should be nullable

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#42003]
In the migrated test package, we have [this code](https://github.com/dart-lang/test/blob/2f03205233da3fddd004ad2781287ad236ab974e/pkgs/test_core/lib/src/runner/parse_metadata.dart#L56). This is an opted in library calling a getter from a legacy library. It gives the following warning from the cfe:

```
/test/pkgs/test_core/lib/src/runner/parse_metadata.dart:56:43: Warning: Operand of null-aware operation '?.' has type 'LanguageVersionToken' which excludes null.
- 'LanguageVersionToken' is from 'package:_fe_analyzer_shared/src/scanner/token.dart' ('/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-3.0.0/lib/src/scanner/token.dart').
     _languageVersionComment = result.unit.languageVersionToken?.value();
                                           ^
```

However, this getter is explicitly documented to be potentially null, and it is corresponding library is not opted in, so the null check does need to be there.

cc @leafpetersen I am not sure exactly what the semantics are supposed to be for these legacy types, but it at least should not complain about doing null checks etc?

**Comment by leafpetersen** [comment]
The relevant section of the spec says

> It is a warning to use a null aware operator (`?.`, `?[]`, `?..`, `??`, `??=`, or
`...?`) on an expression of type `T` if `T` is **strictly non-nullable**.

Where strictly-nonullable doesn't include legacy types, so I believe this is an erroneous diagnostic.  

Per offline discussion, this seems to be a  CFE only issue, the analyzer doesn't issue a warning here.
