### ISSUE TITLE
unnecessary_cast false positive casting a Legacy type to a Nullable type.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#42007]
When calling into a legacy API from an opted in (nnbd) api, the default type inference is to convert legacy types to their _non-nullable_ variants. When they may actually contain null, you need to explicitly specify that at the call site. 

Today the only way you can do it is by putting a type on the LHS of a declaration:

```
// assume `bar` is from some legacy library, and `baz` is of type `int*`
int? foo = bar.baz; 
```

If you attempt to do it with a cast to `int?` instead, the `unnecessary_cast` lint triggers, which is a false positive as this does affect behavior:

```
// triggers unnecessary cast lint :(
var foo = bar.baz as int?;
```

I propose that the unnecessary cast lint should thus never warn when casting a legacy type to a nullable type, as that does affect behavior.

**Comment by jakemac53** [comment]
The more I think about this the more I actually think that Inference on Legacy types should not be converting to a non-nullable type, but to a nullable one.

This should hopefully be a fairly rare scenario anyways, but it is significantly safer to do it this way, because legacy APIs can explicitly have null as a _valid value_. Assuming non-nullable therefore while more ergonomic seems pretty likely to cause problems. Forcing an explicit `!` when calling legacy apis from an opted in library seems pretty acceptable to me, personally.

cc @leafpetersen

**Comment by leafpetersen** [comment]
On the main subject of the issue, note that this affects casts in the other direction as well, which is probably a larger issue.  In an opted in library, casting from `int*` to `int` is something I may very legitimately want to do to eliminate the possibility of getting a `null` value instead of an int.

**Comment by leafpetersen** [comment]
> The more I think about this the more I actually think that Inference on Legacy types should not be converting to a non-nullable type, but to a nullable one.

I can see arguments either way - we discussed both options.

**Comment by leafpetersen** [comment]
> If you have a link to the discussion I would be interested in it :).

I'm not sure it was discussed in the issue tracker, so not sure there's a record.  It might be discussed in pull requests or the original roadmap, not sure.  I'd rather not side-track this issue, but if you want to open an issue in the language repo issue tracker, I'll put down my thoughts there for the record plus any further discussion?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/153000
