### ISSUE TITLE
co19_2 tests should not use document.registerElement

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#42005]
`document.registerElement` (or `document.register` in the `dart:html` library) has been deprecated and removed in Chrome 80. In order to replicate the same behavior, `window.customElements.define` is preferred instead. See https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement for more details.

This currently affects the following tests as they now are failing:

co19_2/LibTest/html/Element/attributeChanged_A01_t01
co19_2/LibTest/html/Element/enteredView_A01_t01
co19_2/LibTest/html/Element/leftView_A01_t01
co19_2/LibTest/html/Element/tagName_A01_t03
co19_2/LibTest/html/IFrameElement/IFrameElement.created_A01_t01
co19_2/LibTest/html/IFrameElement/tagName_A01_t03

The error looks like:
```
TypeError: receiver.registerElement is not a function
TypeError: receiver.registerElement is not a function
    at HtmlDocument.registerElement2  org-dartlang-sdk:///sdk_nnbd/lib/html/dart2js/html_dart2js.dart 17723:5
    at registerElement(inlined)       org-dartlang-sdk:///sdk_nnbd/lib/html/dart2js/html_dart2js.dart 10392:5
    at register(inlined)              org-dartlang-sdk:///sdk_nnbd/lib/html/dart2js/html_dart2js.dart 17729:12
```

**Comment by srujzs** [comment]
Issue filed in co19 repo instead, closing.

**Comment by sigmundch** [comment]
cross reference for quick access: https://github.com/dart-lang/co19/issues/673
