### ISSUE TITLE
Bounds check elimination confused by List.filled?

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#42019]
After `new List` is changed to `new List.filled`, we fail to eliminate all bounds checks from` BCEListNamedAndPlainLength`. We should still know the array's (symbolic) length after this change.

https://dart-review.googlesource.com/c/sdk/+/148685/9/runtime/vm/compiler/backend/bce_test.cc#b277

**Comment by mraleph** [comment]
We probably simply don't recognise `List.filled`. @alexmarkov could you add the recognition and necessary forwarding rules to forward the length? You can also add forwarding rules to forward initial values as well - though that might not really benefit anything.
