### ISSUE TITLE
Unexpected behavior of analyzer for checked nullable type

### ISSUE THREAD

**Issue by vanesyan** [dart-lang/sdk#42033]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Dart VM

* Version: `Dart VM version: 2.9.0-10.0.dev (dev) (Tue May 19 15:16:48 2020 +0200) on "windows_x64"`
* Windows

NNDB does not infer none nullability to given variable inside of `if` statement with not `null` check.

Code to reproduce:
```dart
class A {
  A(this.strings);

  final Set<String>? strings;
  Set<String> get values {
    return {
      "hello",
      if (strings != null) ...strings, // expected here an auto-cast strings to non-nullable type
    };
  }
}
```

Actual result:
![image](https://user-images.githubusercontent.com/18165039/82735444-48e7bf00-9d3b-11ea-9df4-efe321cf1fb4.png)

Expected result:
Analyzer infers non-nullable behavior itself

How it can be fixed today:
Currently it is possible to fix it by explicitly cast to non-nullable type by postfixing with `!`

**Comment by lrhn** [comment]
Promotion only works for local variables. Global variables are assumed to be able to change at any time, so checking them at one point doesn't guarantee that they still have the same value when you later use them.

You can use null-checking spread instead: 
```dart
return {"hello", ...?strings};
```
