### ISSUE TITLE
Warning: Tried to initialize from a previous compilation (build/cache.dill), but the file was not self-contained.

### ISSUE THREAD

**Issue by TheKetan2** [dart-lang/sdk#42038]
Launching lib\main.dart on Google Pixel 3a in debug mode...

Compiler message:
Warning: Tried to initialize from a previous compilation (build/cache.dill), but the file was not self-contained. This might be a bug.

**Comment by mkustermann** [comment]
@jensjoha @johnniwinther Could this be CFE related?

**Comment by jensjoha** [comment]
Yes. This is a message from the CFE. Unfortunately this bug report is not actionable in itself though.

**Comment by johnniwinther** [comment]
Do we have a way of (easily) obtaining more information about the cause in these cases?

**Comment by jensjoha** [comment]
We could perhaps extend the error message --- but we do ask the user to upload the dill (if they are comfortable with it).
