### ISSUE TITLE
Problem installing flutter

### ISSUE THREAD

**Issue by franquicidad** [dart-lang/sdk#42041]
Hello i have a big issue installing flutter i have the latest flutter version and it is Dart VM version: 2.6.0 "macos_x64" with macOs Catalina on mac book pro. The error is... ./flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.0.6/lib/src/resolver.dart:9:8: Error: Error when reading '../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.36.4/lib/src/dart/analysis/driver.dart': No such file or directory
import 'package:analyzer/src/dart/analysis/driver.dart' show AnalysisDriver;

**Comment by lrhn** [comment]
I recommend asking about this in the [Flutter repository](https://github.com/flutter/flutter).

**Comment by vsmenon** [comment]
Flutter packages Dart (and pub-cache) a little differently.  Please open the issue there if you are still having problems.  Thanks!
