### ISSUE TITLE
 Uri.http query parameters doesn't accept Map<String, dynamic>.

### ISSUE THREAD

**Issue by preetshah21699** [dart-lang/sdk#42054]
The query parameters in uri.http should accept inputs of the type Map<String, dynamic> so as to accommodate arrays.
```
E/flutter ( 9433): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>'
```
I get the above error when I try and pass a query parameter that is of the type array, it gives me this error. 
Flutter version: 1.17.1

**Comment by nathantew14** [comment]
@preetshah21699 did you find a solution for this? I'm having the same problem.
