### ISSUE TITLE
Whether the MIPs architecture machine can install dart by compiling

### ISSUE THREAD

**Issue by yanqingdi** [dart-lang/sdk#42056]
![image](https://user-images.githubusercontent.com/38172449/82921779-5b682f80-9fab-11ea-840b-70bf4b7e71ee.png)
in the Wiki , MIPS are supported when compiling and installing.But the fact is not the case.
![image](https://user-images.githubusercontent.com/38172449/82922244-eba67480-9fab-11ea-8715-b5dfb11e6994.png)
I wanted to make sure that I wasn't doing something wrong

**Comment by a-siva** [comment]
Support for MIPS in the Dart SDK has been dropped, see
https://github.com/dart-lang/sdk/issues/29678

The wiki pages need to be updated, we will use this issue as a tracker to update the wiki page.

**Comment by a-siva** [comment]
Updated the Wiki page to remove references to mips architecture.

**Comment by yanqingdi** [comment]
&nbsp;&nbsp;Hello?&nbsp;If I want to install DART on the MIPS CPU.Is there an alternative solution and is it possible to modify the code if necessary




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Siva"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 凌晨1:46
收件人:&nbsp;"dart-lang/sdk"<sdk@noreply.github.com&gt;;
抄送:&nbsp;"颜庆頔"<2597892733@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dart-lang/sdk] Whether the MIPs architecture machine can install dart by compiling (#42056)





 
Closed #42056.
