### ISSUE TITLE
Breaking Change Request: Remove support for armv6

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#42069]
**Intended change in behavior**: Remove support for ARMv6 in Dart VM.

**Justification/rationale**: Flutter doesn't officially support ARMv6 (see also [flutter faq](https://flutter.dev/docs/resources/faq#what-devices-and-os-versions-does-flutter-run-on)) and neither does Dart. We have no test coverage of it either (afaik).

**Expected impact of this change**: Should not impact any direct users of Flutter / Dart SDK. It will no longer be possible build custom Dart VM for ARMv6 and run on ARMv6 devices (known affected devices: old Raspberry Pi 1 & Zero).

**Clear steps for mitigating the change**: None

/cc @Hixie @vsmenon @mit-mit @a-siva  @franklinyow

**Comment by mkustermann** [comment]
Related 2.5 year old flutter issue: https://github.com/flutter/flutter/issues/22380

**Comment by mkustermann** [comment]
Breaking change email has been sent to dart-announce@

**Comment by JakeSays** [comment]
can we trade armv6 support for thumb2 only support? windows arm devices don't support anything but.

**Comment by franklinyow** [comment]
cc @Hixie @matanlurey @vsmenon for review and approval.

**Comment by Hixie** [comment]
I'm all for deleting code in principle. Have we check with Alibaba and other companies that asked for this feature? They may be building custom engines with it. cc @zoeyfan

**Comment by zoeyfan** [comment]
Hey Kang,

I want to bring this to your attention since this is a breaking change. Let
me know if you have any concerns.

Thanks,
Zoey

**Comment by mit-mit** [comment]
> Have we check with Alibaba and other companies that asked for this feature?

We've reached to a number of entities offline and have not heard any concerns. I also see no concerns listed in the present issue. @Hixie @matanlurey @vsmenon can we approve this change?

**Comment by mit-mit** [comment]
Note: once/if you agree, we still need to get this posted on dart-announce for broad feedback.

**Comment by Hixie** [comment]
I defer to @zoeyfan; I have no personal objection.

**Comment by franklinyow** [comment]
It's already announced:
https://groups.google.com/a/google.com/g/dart-announce/c/3UJRSrIq7-0

**Comment by mit-mit** [comment]
@vsmenon can you give the final approval?

**Comment by sebe** [comment]
> It's already announced:
> https://groups.google.com/a/google.com/g/dart-announce/c/3UJRSrIq7-0

Hey is that a google only group, I can't access it and can't see any see any ARMv6 announcement in
https://groups.google.com/a/dartlang.org/forum/#!forum/announce 

I don't have an issue with the removal of armv6 support, I do wish the Raspberry Pi people would stop selling armv6 boards, maybe some part of google could somehow help the Pi people to move the pi zero to a more modern processor.

**Comment by franklinyow** [comment]
@sebe You are right, the announcement went to the wrong group.

I copied the announcement over:
https://groups.google.com/a/dartlang.org/g/announce/c/U50WhgzD8t0

**Comment by JakeSays** [comment]
@sebe Heh. I second the RPI idea. It's a real pain having two architectures to deal with.

**Comment by JakeSays** [comment]
The one thing I would ask about this change is that you guys tag the commit before the first change in some way that is easy to find. I do have a couple of armv6 devices that run flutter. I don't mind sticking to an older version for them, but it'd be helpful to be able to easily find the end commit.

**Comment by mkustermann** [comment]
@JakeSays Due to the lack of current build/testing on our continuous integration system, it might already be broken. If not you could take any commit atm.

We haven't removed the code in the Dart VM yet - though I've made now a CL to do that which will probably land soon [cl/152322](https://dart-review.googlesource.com/c/sdk/+/152322)

**Comment by mit-mit** [comment]
@vsmenon @franklinyow can we get this marked approved? The CL is ready to be landed.

**Comment by vsmenon** [comment]
lgtm

@franklinyow - are we clear to land?

**Comment by franklinyow** [comment]
Mark this as approved.  @mkustermann please go ahead and land.

**Comment by talksik** [comment]
can someone please clarify this in the docs: https://docs.flutter.dev/reference/supported-platforms

I am unsure what "support for the platforms on which built Flutter might be deployed" means. What is built flutter? Does it mean that the table is regarding which platforms are supported to build the app? Or does it mean these are the target platforms that are supported? Or is it that this entire page is just talking about support for host machines that deploy the app? I'm super confused and need clarification which Raspberry pi OS and cpu would run a flutter app that I code on my macbook and cross compile with docker.

Why is there no mention of CPU architectures supported if the latter is true?

Thank you

**Comment by mit-mit** [comment]
Hi @talksik. Yeah, that sentence wasn't so easy to read. I'm updating it in https://github.com/flutter/website/pull/9005/files

Yes, this page lists the supported target platforms, i.e. the platforms on which we support running apps that have been built with Flutter.

**Comment by talksik** [comment]
awesome thank you for the edit and clarification!

**Comment by bvoq** [comment]
It would be good to keep ARMv6 support. I would also like to write an embedder of flutter for the Nintendo 3ds.
It shouldn't be that difficult to keep it backwards compatible.
