### ISSUE TITLE
isDart2jsNnbd prevents some tests from running outside the test runner

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#42063]
We usually run our tests via the test runner, but not always. In particular, a handful of tests can be run as a standalone Dart program, updating expectation files if `-g` is passed. These tests throw if run this way because we end up calling `null.endsWith("Legacy")`.

Example: `dart tests/compiler/dart2js/analyses/dart2js_dynamic_test.dart [-g]`

/cc @sigmundch

**Comment by fishythefish** [comment]
Bump - I've been working around this by specifying `DART_CONFIGURATION` on the command line, but we should clean this up.

**Comment by sigmundch** [comment]
Note: now that the unfork is done and the sdk_nnbd folder moved back to sdk, we should be able to replace the variable with `true` and delete all prennbd expectation comments.
