### ISSUE TITLE
Exhaustive switch statement produces warning: "This function has a return type of 'XXXX', but doesn't end with a return statement."

### ISSUE THREAD

**Issue by matthew-carroll** [dart-lang/sdk#42087]
I have an exhaustive switch statement that produces the following warning within Android Studio: 

"This function has a return type of 'XXXX', but doesn't end with a return statement."

I'm posting here because I'm assuming that this warning is coming from the language analyzer.

In situations where I have exhaustively covered the possible `enum` values, I really don't want to add a `default` case because if it ever did execute, it would be an error.

**Comment by srawlins** [comment]
Thanks for filing this issue; this does sound like an analyzer issue. Can you show a minimal reproduction of your exhaustive switch statement? Does it include catching `null`?

**Comment by matthew-carroll** [comment]
Can you describe what you mean by "catching `null`"? I don't expect that the incoming value is ever `null`, so I don't do anything for that situation. Is there an annotation or some such approach to make it clear that it's non-null? I'd prefer not to add an if-statement...

Here is a repro:

```
enum MyEnum {
  option1,
  option2,
  option3,
}

int myExhaustiveFunction(MyEnum theEnumValue) {
  switch (theEnumValue) {
    case MyEnum.option1:
      return 1;
    case MyEnum.option2:
      return 2;
    case MyEnum.option3:
      return 3;
  }
}
```

**Comment by srawlins** [comment]
>  I don't expect that the incoming value is ever null, so I don't do anything for that situation.

Be that as it may, it could be null.

Looks like a duplicate of https://github.com/dart-lang/sdk/issues/35710.

**Comment by srawlins** [comment]
We are implementing a new type system with non-nullable types, as you desire here. Stay tuned. One of the next few releases should let you try the non-nullable type system, and you will not need to handle `null` in your cases.

**Comment by matthew-carroll** [comment]
Ok. I'll close this issue as a dup of the other and wait for NNBD.
