### ISSUE TITLE
Analyzer soundness problem: Return void to Null allowed.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42093]
Consider the following program:

```dart
void v = "Hello";

Null test() {
  return v;
}

void main() {
  int? i = test();
  if (i != null) {
    i.isEven;
  }
}
```

The analyzer (2.9.0-11.0.dev and 2eaac80e1a968b0219793df296e38003f97ede7d) accepts this program with no errors, but it is not sound to allow an expression of type `void` to be returned when the return type is `Null`, because the returned object could have any type whatsoever.

A similar issue arises with the asynchronous form:

```dart
import 'dart:async';

void v = "Hello";

Future<Null> test() async {
  return v;
}

void main() async {
  int? i = await test();
  if (i != null) {
    i.isEven;
  }
}
```

**Comment by scheglov** [comment]
I believe that the issue was fixed by implementing changes requested in https://github.com/dart-lang/sdk/issues/41803.

I added a new test in https://dart-review.googlesource.com/c/sdk/+/149604.
