### ISSUE TITLE
[DartFix] omit_local_variable_types doesn't work with final or const

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/sdk#42099]
## Example
When running `dartfix --fix=omit_local_variable_types` on the following snippet
```dart
final bool foo = true;
const double bar = 3.0;
```

### Expected
```dart
final foo = true;
const bar = 3.0;
```

### Actual
```dart
final var foo = true;
const var bar = 3.0;
```

Which produces errors.

## Version
`Dart VM version: 2.9.0-11.0.dev.flutter-e007545c42 (be) (Tue May 26 22:17:42 2020 +0000) on "macos_x64"`

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/149361
