### ISSUE TITLE
Can't pass `ByteData` to JS-interop

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#42101]
The docs for `dart:js` say:

> The following types are transferred directly and not proxied:
>
> * Basic types: null, bool, num, String, DateTime
> * *TypedData*, including its subclasses like Int32List, but not ByteBuffer
> * When compiling for the web, also: Blob, Event, ImageData, KeyRange, Node, and Window.

So, `ByteData` should be allowed according to the docs since it is a subclass of `TypedData` but not `ByteBuffer`. However, `ByteData` is proxied by DDC.

This can be fixed by adding a check for `# instanceof DataView` here: https://github.com/dart-lang/sdk/blob/20745941ad6da9d1307e07e15e6b39acd9f4a071/sdk/lib/_internal/js_dev_runtime/patch/js_patch.dart#L307

In dart2js, this already works because it checks for `TypedData` here: https://github.com/dart-lang/sdk/blob/20745941ad6da9d1307e07e15e6b39acd9f4a071/sdk/lib/_internal/js_runtime/lib/js_patch.dart#L424

**Comment by natebosch** [comment]
cc @srujzs

**Comment by sigmundch** [comment]
@hterkelsen with your change now landed, is it safe to mark this as fixed?

**Comment by hterkelsen** [comment]
Yes.

**Comment by hterkelsen** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/c3986418a013cb616e68bcc65e0948866b0a5845
