### ISSUE TITLE
Missing analyzer error on self-assignment with custom index operators

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42100]
I ran into this when [migrating](https://dart-review.googlesource.com/c/sdk/+/148286) language/implicit_downcast_during:

```dart
class A {}
class B extends A {}

class C {
  int operator [](B b) => 0;
  //              ^------------------- Not A!
  void operator []=(A a, int o) {}
}

void main() {
  C()[A()] += 1;
}
```

This should have a static error because it's passing an `A` to the index getter which expects a `B`. Instead, I get:

```
$ dartanalyzer --enable-experiment=non-nullable temp.dart
Analyzing temp.dart...
No issues found!
```

cc @stereotype441

**Comment by scheglov** [comment]
I believe that this ffbe30f8907c83a663688327f754736e99ec37fe this is fixed now.
We check the index expression with both read and write elements.
