### ISSUE TITLE
API Docs return a 404 for some packages 

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#42105]
The "API Documentation" link is broken on some packages for me.

Here's a few that return a 404:

- https://pub.dev/documentation/google_fonts/latest/
- https://pub.dev/documentation/http/latest/
- https://pub.dev/documentation/mobx/latest/

Meanwhile, others are being served normally:

- https://pub.dev/documentation/redux/latest/
- https://pub.dev/documentation/url_launcher/latest/

**Comment by johnpryan** [comment]
cc: @jonasfj

**Comment by jonasfj** [comment]
Thanks, duplicate of https://github.com/dart-lang/pub-dev/issues/3669.
We are investigating.
