### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by lovepreet221** [dart-lang/sdk#42106]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.8.2`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

**Comment by parlough** [comment]
@lovepreet221 Was any more information provided and/or could you provide any additional context?

**Comment by srawlins** [comment]
Please re-open if you can capture a crash stack trace, or what you were doing at the time.
