### ISSUE TITLE
Analyzer doesn't properly compute static type of `Object` members on `dynamic` receivers

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42114]
Dart VM version: 2.9.0-11.0.dev (dev) (Tue May 26 12:14:57 2020 +0200) on "windows_x64".

The following source code example causes a compile error with dart and passes with analyzer:
``` dart
main() {
  dynamic o = 1;
  print(o.runtimeType.nonexistent);
}
```
Both tools should behave in a similar way.

Sample output is:

> $> dartanalyzer test.dart
> Analyzing test.dart...
> No issues found!
> 
> $> dart test.dart
> test.dart:3:23: Error: The getter 'nonexistent' isn't defined for the class 'Type'.
>  - 'Type' is from 'dart:core'.
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'nonexistent'.
>   print(o.runtimeType.nonexistent);
>                       ^^^^^^^^^^^
>

**Comment by vsmenon** [comment]
Interesting case: should `o.runtimeType` have static type `Type` or `dynamic`?  @eernstg @leafpetersen

**Comment by lrhn** [comment]
It should have type `Type`.

When invoking a member of `Object` on a receiver of type `dynamic`, we trust and use the return type from the `Object` member (since any class must satisfy that).

**Comment by vsmenon** [comment]
Thanks @lrhn !  Filing as analyzer bug then.

**Comment by vsmenon** [comment]
Changed the title to reflect my understanding.

**Comment by eernstg** [comment]
Right; we did have to make an exception: The return type from `Object` can only be used when the invocation is statically correct for the `Object` signature, so `o.toString()` has type `String`, but `o.toString(42)` has type `dynamic`.

**Comment by lrhn** [comment]
Correct. If the invocation can potentially hit `noSuchMethod` directly, then we cannot assume anything about the return type. If it cannot, which means that a dynamic invocation calls a declared member of `Object` with no more, and no fewer, parameters than they requires, then we can also assume that the return type is correct (because it either calls such a method or it throws a type error).

**Comment by srawlins** [comment]
This has been fixed recently. The analyzer now reports, for the example:

> error • The getter 'nonexistent' isn't defined for the type 'Type'. • a.dart:3:23 • undefined_getter
