### ISSUE TITLE
Dart outputs stdout to stderr

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#42123]
Is dart supposed to put standard command output to `stderr`?
This is what you get from running
```dart
Process.runSync('dart', ['--version']);
```
<img width="1082" alt="Screen Shot 2020-05-29 at 9 54 35 PM" src="https://user-images.githubusercontent.com/23037821/83319925-4aabf980-a1f7-11ea-84ba-2427b3c87417.png">

**Comment by srawlins** [comment]
`dart --version` only prints to stderr:

```none
$ dart --version 2>/dev/null
$
```

(nothing is printed)

Are you saying you think that the version number should be printed to stdout?

**Comment by ThinkDigitalSoftware** [comment]
I do. Am I mistaken? Isn’t stderr for errors?

On May 30, 2020, at 4:40 PM, Sam Rawlins <notifications@github.com<mailto:notifications@github.com>> wrote:



dart --version only prints to stderr:

$ dart --version 2>/dev/null
$


(nothing is printed)

Are you saying you think that the version number should be printed to stdout?

**Comment by mraleph** [comment]
Some tools output `--version` and `--help` to stderr. There is no clear convention - so this is working as intended.
