### ISSUE TITLE
homebrew installed analysis server crashes when passed --completion-model flag

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#42121]
When I install the SDK by unpacking the zip from https://dart.dev/tools/sdk/archive the analysis server works fine. When I install the SDK with `brew install dart` using that flag causes the analysis server to crash. It never responds to the initialization request.

**Comment by jasonclouse-wk** [comment]
I'm seeing this as well.

**Comment by natebosch** [comment]
@bwilkerson - do you know who would be able to look in to this?

**Comment by natebosch** [comment]
I think this flag no longer exists
