### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by JuniaKE** [dart-lang/sdk#42126]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.8.3`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

**Comment by srawlins** [comment]
No feedback is fond in this bug report.
