### ISSUE TITLE
Output to stderr if stdin closes unexpectedly in analysis server --lsp

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#42120]
I'm trying to help debug a problem using the analysis server with `--lsp`. It's not clear if there is a bug in the client or the server, but one thing that could help is if we get more output from the server when the client does something unexpected like close `stdin` before sending the shutdown and exit messages. I don't know for sure if that is happening, but I can tell from other testing that when it does happen there isn't any way to tell, the process exits cleanly.

**Comment by DanTup** [comment]
Sorry - didn't see this until now. Would this help?

<img width="806" alt="Screenshot 2020-08-03 at 11 46 39" src="https://user-images.githubusercontent.com/1078012/89175137-09312500-d57f-11ea-9e5e-df8022c25856.png">

I test this with a script that closed stdin:

```dart
import 'dart:io';

Future<void> main() async {
  final proc = await Process.start(
    '/Users/danny/Dev/Dart SDKs/nightly-2020-07-29/bin/dart',
    [
      '/Users/danny/Dev/Google/dart-sdk/sdk/pkg/analysis_server/bin/server.dart',
      '--lsp',
      '--instrumentation-log-file=/tmp/danny/foo.txt',
    ],
    workingDirectory:
        '/Users/danny/Dev/Google/dart-sdk/sdk/pkg/analysis_server',
  );
  print('Waiting...');
  await Future.delayed(Duration(seconds: 30));
  print('Closing stdin');
  await proc.stdin.close();
  print('Waiting...');
  await Future.delayed(Duration(seconds: 3));
  print('Done!');
}
```

And it showed up in the instrumentation log:

```
danny@Dannys-MBP analysis_server % cat /tmp/danny/foo.txt    
1596451474737:Ver:1576335109950827824173:unknown.client.lsp:unknown:1.28.0:2.10.0-edge.35a8b1ec280cf8717f341014f301eebe059cbe2f
1596451497666:Info:Input stream closed 
```

The instrumentation log would also show shutdown/exit calls, so you'd be able to see if they were called prior to this.

(and out of interest, what's the issue you're seeing?)

**Comment by natebosch** [comment]
I'm pretty sure this turned out to be a crash that doesn't relate to the input stream closing. https://github.com/dart-lang/sdk/issues/42121

I'm not confident that adding more here would actually help anything so I think we can skip this one.

**Comment by DanTup** [comment]
Ok cool. By complete coincidence, I just closed https://github.com/Dart-Code/Dart-Code/issues/2694 which seems to be the same as that issue!
