### ISSUE TITLE
vs code 

### ISSUE THREAD

**Issue by Anirudh123ani123** [dart-lang/sdk#42128]
![connectingpic](https://user-images.githubusercontent.com/38275342/83353579-33911700-a371-11ea-98fa-cc29fe01ec89.png)

when I am running the app then in debug console I am getting following message:
Connecting to VM Service at ws://127.0.0.1:57714/kOYGq91qB-o=/ws   what does it mean?

**Comment by julemand101** [comment]
It's mean the Dart VM has been started with the flag "--observe" which allows you to access the Dart Observatory which gives additional data about how the Dart VM are running your code. You can e.g. see memory consumption, how much time Dart are using in each method, see the assembly code which your program has been compiled into and much much more.
