### ISSUE TITLE
Analyzer: Propagate `dynamic` as the future value type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42133]
Cf. https://github.com/dart-lang/language/pull/997, a return type of `dynamic`, `dynamic?`, or `dynamic*` is now propagated such that the future value type will be `dynamic` (before that spec change, it was specified to be `Object?`, which caused unintended breakage).

This issue exists in order to keep track of the implementation changes corresponding to this spec change. @scheglov, I believe the implementation already includes this update, in which case this issue can be closed immediately.

**Comment by scheglov** [comment]
Correct, it was implemented already in analyzer.
