### ISSUE TITLE
"argument_type_not_assignable" when changing filename casing.

### ISSUE THREAD

**Issue by emme1444** [dart-lang/sdk#42130]
In your issue, please include:

* Dart SDK Version (`dart --version`): `Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"`
* Whether you are using Windows, MacOSX, or Linux (if applicable): `macOS`

I use flutter, but think this issue has to do with dart itself. 

I changed the name of a file to start with a lowercase letter instead of an uppercase letter. However, upon running, I get this error:
```
$ flutter run

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Compiler message:
lib/widgets/modal/ModalWrapper.dart:152:18: Error: The argument type 'Modal/*1*/<dynamic>' can't be assigned to the parameter type 'Modal/*2*/<dynamic>'.
 - 'Modal/*1*/' is from 'package:app/widgets/modal/modal.dart' ('lib/widgets/modal/modal.dart').
 - 'Modal/*2*/' is from 'package:app/widgets/modal/Modal.dart' ('lib/widgets/modal/Modal.dart').
          modal: modal,
                 ^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.
```

Even though there's only one import in the conflicting file, I still see this. 

First I thought maybe it's just to do with `vscode` or some caching, but then running the app revealed this, which feels kind of odd. The odd thing being the fact that I'm only importing one of them. 

Would appreciation an explanation.

**Comment by bwilkerson** [comment]
My guess is that you have another import of that library somewhere in your code that is still using the uppercase version of the URI.

Dart uses the URI to determine whether two libraries are the same rather than looking to see whether the URIs resolve to the same file. So, if you import a single file using two textually distinct URIs, Dart will treat the imports as if you had imported two different libraries.

**Comment by emme1444** [comment]
Aha! Looking into it further, turns out that I was importing a file that had the old name imported in itself. Weird? Also, weird that `vscode` didn't highlight that error, since the file with that name no longer exists.

Oh well, thank you for your fast reply @bwilkerson!

**Comment by bwilkerson** [comment]
The reason there was no error is that the macOS file system is case insensitive, so when the analyzer asked whether the file existed, even though the case of the file name was different, the OS said "yes". But Dart is case sensitive on all platforms.
