### ISSUE TITLE
dart2native: Clarify usage of -D/environment variables/environment declarations

### ISSUE THREAD

**Issue by knaeckeKami** [dart-lang/sdk#42136]
`dart2native --help` prints:

```
dart2native --help
Usage: dart2native <main-dart-file> [<options>]

Generates an executable or an AOT snapshot from <main-dart-file>.

-D, --define=<key=value>       Set values of environment variables. To specify multiple variables, use multiple options or use commas to separate key-value pairs.
                               E.g.: dart2native -Da=1,b=2 main.dart
```

I was confused by this. I didn't think of environment declarations that will be read via [int|String...].fromEnvironment, but of actual OS environment variables, so that option did not make much sense for me.
This wording is also not very googleable, as "dart environment variables" returns no related result.

I suggest replacing "environment variables" with "environment declarations". This is consistent with the documentation of String.fromRuntime for example:

> Returns the string value of the environment declaration name. Environment declarations are provided by the surrounding system compiling or running the Dart program. Declarations map a string key to a string value.

https://api.flutter.dev/flutter/dart-core/String/String.fromEnvironment.html

Related: https://github.com/dart-lang/sdk/issues/17262

## Dart Version

> ./dart --version
Dart VM version: 2.8.3 (stable) (Tue May 26 18:39:38 2020 +0200) on "macos_x64"

**Comment by mkustermann** [comment]
Tentatively assigning @mit-mit, since you were looking at this recently IIRC

**Comment by mit-mit** [comment]
CL in https://dart-review.googlesource.com/c/sdk/+/149595/1

**Comment by mit-mit** [comment]
Thanks @knaeckeKami for bringing this to our attention, we've updated both our product help and dart.dev documentation!

**Comment by mit-mit** [comment]
Follow-up CL in https://dart-review.googlesource.com/c/sdk/+/161107
