### ISSUE TITLE
problem with extension method for operator +

### ISSUE THREAD

**Issue by thumbert** [dart-lang/sdk#42132]
Hi, 

I have run into an issue when implementing an extension method for operator +. 

I have a time-series class based on a list as such:
```dart
class TimeSeries<K> extends ListBase<IntervalTuple<K>> {...}
```
Where IntervalTuple is a pairing of a time interval and a value K. 

For two numeric time series, it make sense to define the '+' operator as element-wise addition as long as the corresponding intervals match.  
```dart
  TimeSeries<num> operator +(TimeSeries<num> other) {
    var _aux = merge(other, f: (x,y) => [x, y]);
    return TimeSeries.fromIterable(
        _aux.map((e) => IntervalTuple(e.interval, e.value[0] + e.value[1])));
  }
```
The surprising thing is that the result is not a TimeSeries, but an List<IntervalTuple<num>>.
If I change the extension method name to 'plus' instead of 'operator +', everything works as expected.  I can also define element-wise multiplication '*' fine.

https://dart.dev/guides/language/extension-methods specifies that you can define extension methods on operators. 

Any suggestions on how I can fix this issue?  I would like to be able to define '+'.

Thank you,
Tony

Dart VM version: 2.8.3 (stable) (Unknown timestamp) on "linux_x64"

**Comment by vsmenon** [comment]
Note that `+` is already defined on `TimeSeries` via `List`/`ListBase`.  You may be hitting this:

https://dart.dev/guides/language/extension-methods#api-conflicts

**Comment by eernstg** [comment]
Then we should probably mention one more thing (which does not seem to be mentioned at https://dart.dev/guides/language/extension-methods#api-conflicts):

An extension method cannot be invoked if the receiver type has an instance method with the same name (unless the explicit extension method invocation syntax is used):

```dart
extension E on int {
  // Return bool such that we can easily see which `+` is called.
  bool operator +(int other) => true;
}

void main() {
  int i = 1 + 1; // Call instance method.
  bool b = E(1) + 1; // Call extension method.
}
```

So, basically, instance methods have higher priority than extension methods. But given that you have written the `TimeSeries` class yourself (if I understood that correctly), you could make your `operator +` an instance method, but you would then need to use `covariant` on the parameter type, unless you are willing to use parameter type `List<IntervalTuple<K>>`.

**Comment by vsmenon** [comment]
@lrhn @leafpetersen 

Should this be closed as working as intended?  Is there something we should update in terms of documentation or analysis hints/warnings?

**Comment by lrhn** [comment]
It's working as intended, and there isn't any good place to put documentation.

One option would be the analyzer being clever and recognizing that an instance member invocation is shadowing an extension, and if there are any type issues with the instance member, then check if the extension member would fix them.

Probably a fairly complex piece of heuristics, though.

**Comment by thumbert** [comment]
Thanks for the answers.  I got it working using @eernstg's suggestion:
 ```dart
  @override
  TimeSeries<K> operator +(covariant TimeSeries<K> other) {
    if (K == num) {
      var _aux = merge(other, f: (x,y) => [x, y]);
      return TimeSeries.fromIterable(
          _aux.map((e) => IntervalTuple(e.interval, e.value[0] + e.value[1])));
    }
    return this..addAll(other);
  }
```
Not the cleanest, but it gets the job done.  

Thanks,
Tony
