### ISSUE TITLE
Compile-time errors on vm/dart/* tests in strong mode due to dependencies on legacy packages

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#42146]
After `vm/dart` tests are migrated to NNBD, there are still compile-time errors in strong mode due to dependencies on packages which are not migrated yet.

The following tests are failing:
```
dartk-strong-linux-debug-x64:vm/dart/appjit_bytecode_simple_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/appjit_cha_deopt_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/appjit_determinism_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/appjit_load_static_licm_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/bytecode_and_ast_mix_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/causal_stacks/async_throws_stack_lazy_non_symbolic_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/causal_stacks/async_throws_stack_lazy_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/causal_stacks/async_throws_stack_no_causal_non_symbolic_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/causal_stacks/async_throws_stack_no_causal_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/causal_stacks/async_throws_stack_non_symbolic_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/causal_stacks/async_throws_stack_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/causal_stacks/sync_async_start_pkg_test_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/compilation_trace_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/disassemble_determinism_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/issue32950_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/kernel_determinism_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/print_flow_graph_determinism_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/product_aot_kernel_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/redirection_type_shuffling_test/none is new and failed (RuntimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/snapshot_depfile_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/0 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/1 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/10 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/11 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/12 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/13 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/14 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/15 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/16 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/2 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/3 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/4 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/5 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/6 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/7 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/8 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/splay_test/9 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/type_feedback_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/use_dwarf_stack_traces_flag_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/use_save_debugging_info_flag_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-debug-x64:vm/dart/use_strip_flag_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/appjit_bytecode_simple_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/appjit_cha_deopt_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/appjit_determinism_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/appjit_load_static_licm_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/bytecode_and_ast_mix_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/causal_stacks/async_throws_stack_lazy_non_symbolic_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/causal_stacks/async_throws_stack_lazy_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/causal_stacks/async_throws_stack_no_causal_non_symbolic_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/causal_stacks/async_throws_stack_no_causal_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/causal_stacks/async_throws_stack_non_symbolic_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/causal_stacks/async_throws_stack_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/causal_stacks/sync_async_start_pkg_test_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/compilation_trace_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/disassemble_determinism_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/issue32950_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/kernel_determinism_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/minimal_kernel_bytecode_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/minimal_kernel_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/null_safety_autodetection_in_kernel_compiler_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/print_flow_graph_determinism_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/product_aot_kernel_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/redirection_type_shuffling_test/none is new and failed (RuntimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/snapshot_depfile_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/0 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/1 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/10 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/11 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/12 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/13 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/14 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/15 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/16 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/2 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/3 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/4 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/5 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/6 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/7 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/8 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/splay_test/9 is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/type_feedback_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/use_dwarf_stack_traces_flag_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/use_save_debugging_info_flag_test is new and failed (CompileTimeError, expected Pass)
dartk-strong-linux-release-x64:vm/dart/use_strip_flag_test is new and failed (CompileTimeError, expected Pass)
```

**Comment by alexmarkov** [comment]
Current list of tests failing in strong mode due to dependencies on legacy packages:

suite | test | bot | configuration | dependencies
-- | -- | -- | -- | --
lib | mirrors/library_uri_package_test | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:args
lib | mirrors/library_uri_package_test | vm-release | dartk-strong-linux-release-x64 | Depends on package:args
standalone | io/addlatexhash_test | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/addlatexhash_test | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/http_auth_digest_test | vm-aot-release | dartkp-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/http_auth_digest_test | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/http_auth_digest_test | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/http_auth_test | vm-aot-release | dartkp-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/http_auth_test | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/http_auth_test | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/http_proxy_advanced_test | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/http_proxy_advanced_test | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/http_proxy_test | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/http_proxy_test | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/shared_socket_test/0 | vm-aot-release | dartkp-strong-linux-release-x64 | Depends on package:http, http_parser
standalone | io/shared_socket_test/0 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:http, http_parser
standalone | io/shared_socket_test/0 | vm-release | dartk-strong-linux-release-x64 | Depends on package:http, http_parser
standalone | io/shared_socket_test/1 | vm-aot-release | dartkp-strong-linux-release-x64 | Depends on package:http, http_parser
standalone | io/shared_socket_test/1 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:http, http_parser
standalone | io/shared_socket_test/1 | vm-release | dartk-strong-linux-release-x64 | Depends on package:http, http_parser
standalone | io/web_socket_compression_test/0 | vm-aot-release | dartkp-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/0 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/0 | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/1 | vm-aot-release | dartkp-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/1 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/1 | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/2 | vm-aot-release | dartkp-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/2 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/2 | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/3 | vm-aot-release | dartkp-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/3 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/web_socket_compression_test/3 | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_test/0 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/web_socket_test/0 | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_test/1 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/web_socket_test/1 | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_test/2 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/web_socket_test/2 | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto
standalone | io/web_socket_test/3 | vm-debug | dartk-strong-linux-debug-x64 | Depends on package:convert, crypto
standalone | io/web_socket_test/3 | vm-release | dartk-strong-linux-release-x64 | Depends on package:convert, crypto

**Comment by alexmarkov** [comment]
vm/* tests which are still failing in strong mode due to dependencies on legacy packages:

```
vm/dart/causal_stacks/async_throws_stack_no_causal_non_symbolic_test
vm/dart/causal_stacks/async_throws_stack_no_causal_test
vm/dart/causal_stacks/async_throws_stack_non_symbolic_test
vm/dart/causal_stacks/async_throws_stack_test
vm/dart/causal_stacks/async_throws_stack_lazy_non_symbolic_test
vm/dart/causal_stacks/async_throws_stack_lazy_test
vm/dart/product_aot_kernel_test
vm/dart/run_appended_aot_snapshot_test
vm/dart/use_dwarf_stack_traces_flag_test
vm/dart/use_save_debugging_info_flag_test
vm/dart/v8_snapshot_profile_writer_test
```

**Comment by alexmarkov** [comment]
As of today, the following `vm/dart/*` tests are still failing with compile-time errors in strong mode due to dependencies on not yet migrated packages:

`vm/dart/product_aot_kernel_test` - depends on opted-out libraries in pkg/kernel.
`vm/dart/run_appended_aot_snapshot_test` - depends on package:dart2native.
`vm/dart/v8_snapshot_profile_writer_test` - depends on package:vm_snapshot_analysis.

**Comment by a-siva** [comment]
pkg/kernel has been migrated,  have dart2native and vm_snapshot_analysis packages been migrated ?

**Comment by alexmarkov** [comment]
Migrated `pkg/dart2native` in 846af57d996d5d07758043772f4445b42ecc1ddd.
`pkg/vm_snapshot_analysis` was migrated earlier.

Waiting for the nightly bots to cycle and then we can verify that the remaining test `vm/dart/run_appended_aot_snapshot_test` passes in all configurations.

**Comment by alexmarkov** [comment]
All remaining tests are now passing.
