### ISSUE TITLE
runZoned/runZonedGuarded body can continue executing after the error callback fires

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#42150]
See https://github.com/flutter/flutter/issues/56406 for a case and a small reproduction where the `runZoned`/`runZonedGuarded` body continues executing if it *indirectly* throws an uncaught exception (e.g. via a `Timer` callback).

I'm not sure if that's the intended behavior, but if it is, it would be nice if the documentation for `runZoned`/`runZonedGuarded` described this.

**Comment by lrhn** [comment]
That is the intended behavior.

You are catching uncaught asynchronous errors, which is one of the most common reasons for running code in a zone to begin with.

In fact, for `runZoned`, that's the only way the error handler gets called. For `runZonedGuarded`, a synchronous error (one that actually stops execution) can also be caught by the error handler.

**Comment by jamesderlin** [comment]
Can we at least document it better?

**Comment by lrhn** [comment]
I'm not sure what to write for this.

If you spin off an asynchronous task which throws, but you don't wait for it, then the error will be unhandled and caught by the current error zone. That's just how asynchronous errors work. The async task is completely independent of whatever else you do, it cannot prevent the other code from completing.
