### ISSUE TITLE
Add transparent pagination support for getVMTimeline

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#42161]
As described in https://github.com/flutter/flutter/issues/57756, it's possible for `getVMTimeline` to cause a Dart process on a low-memory device to crash when requesting a large number of timeline events. DDS should intercept `getVMTimeline` requests and break the requested timeline range into multiple blocks that can be retrieved through separate `getVMTimeline` requests. The results of these requests can be stitched back together by DDS, off device, and sent to the requesting client.

cc/ @jonahwilliams @zanderso

**Comment by zanderso** [comment]
If all vm service clients will be mediated by DDS in the future this seems fine, but if there still might be direct clients of the vm service, then I think it could be valuable to ensure somehow that internal VM allocations are bounded while constructing the response to any `getVMTimeline` request.

**Comment by bkonyi** [comment]
DevTools is already doing this when the performance page has recording enabled, so I don't think there's currently a need for paging functionality for the timeline RPCs. We can always revisit this if it ends up being something we're interested in.
