### ISSUE TITLE
Implement null safety package allow list for (CFE portion)

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42162]
This is a tracking issue for the CFE side of [this](https://github.com/dart-lang/sdk/issues/41741) work.

**Comment by leafpetersen** [comment]
@johnniwinther can you give an estimate of when you expect this to be finished?

**Comment by johnniwinther** [comment]
I'll take -1 days (I landed it but cautiously reverted). Will reland (today?) in https://dart-review.googlesource.com/c/sdk/+/149588
