### ISSUE TITLE
Regression - web builds failing under analyzer 0.39.9 / _fe_analyzer_shared 4.0.0

### ISSUE THREAD

**Issue by tonyclickspace** [dart-lang/sdk#42163]
Dart VM version: 2.8.2 (stable) (Mon May 11 15:06:42 2020 +0200) on "macos_x64"

analyzer was updated from 0.39.8 to 0.39.9 today, to match  _fe_analyzer_shared going from 3.0.0 to 4.0.0

But running webdev build in a web project returns the following:
```
Working dir: /Volumes/CSTV/Development/ProjectName
/usr/local/opt/dart/libexec/bin/pub global run webdev build --output=web:build
[SEVERE] Failed to precompile build_runner:build_runner:
[SEVERE] /Users/tonydowney/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.9/lib/src/resolver.dart:340:10: Error: Method not found: 'SummaryBuilder'.
[SEVERE]   return SummaryBuilder(sdkSources, sdk.context).build(
[SEVERE]          ^^^^^^^^^^^^^^
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      BuildCommand.run (package:webdev/src/command/build_command.dart:57:26)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///Users/tonydowney/.pub-cache/hosted/pub.dartlang.org/webdev-2.5.8/bin/webdev.dart:17:22)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Process finished with exit code 255
```

Regression - last known working version was analyzer 0.39.8 / _fe_analyzer_shared 3.0.0

**Comment by tonyclickspace** [comment]
For anyone finding this issue and looking for a temporary solution - add this to `pubspec.yaml`
```
dev_dependencies:
  _fe_analyzer_shared: ^3.0.0 #temporary, see https://github.com/dart-lang/sdk/issues/42163
```

**Comment by smaifullerton-wk** [comment]
Same here at Workiva. All of our projects are currently not building.

**Comment by smaifullerton-wk** [comment]
@stereotype441

**Comment by devoncarew** [comment]
I believe we're running into this with devtools as well: https://travis-ci.org/github/flutter/devtools/jobs/694012773#L689

**Comment by scheglov** [comment]
I'm going to resolve the unnamed constructor that I removed in `SummaryBuilder`.
Then we will publish another `analyzer` version.

Then we will work with the authors of `build_resolvers` to reduce the amount of internals that they use from `analyzer`.

**Comment by scheglov** [comment]
With https://dart-review.googlesource.com/c/sdk/+/149781, and `dependency_overrides` in `build_resolves` tests pass, so hopefully we can publish this change in a new version of `analyzer` and so fix the issue.

**Comment by stereotype441** [comment]
Ok, analyzer 0.39.10 is published.  This should fix the problem.  If it doesn't, feel free to re-open.

**Comment by devoncarew** [comment]
Just to follow up, the devtools builds are passing agin.

**Comment by smaifullerton-wk** [comment]
Same. Thanks for the quick fix!
