### ISSUE TITLE
Dart Analysis / Compiler wrongly accepts function with no parantheses

### ISSUE THREAD

**Issue by stephan-gruen** [dart-lang/sdk#42170]
dart-sdk 2.9.0-13.0.dev

This behavior makes it very hard to find typos! Dart Analysis thinks this is okay and no compiler error, but function will not be called.

```
List<String> myList = [];
myList.clear;  // this list will not be cleared!
```

**Comment by xvrh** [comment]
There is a lint available to catch this kind of mistake: https://dart-lang.github.io/linter/lints/unnecessary_statements.html

You can enable it with a file `analysis_options.yaml` at the root of your project
```yaml
linter:
 rules:
   - unnecessary_statements
```

**Comment by devoncarew** [comment]
@xvrh - thanks for the triage and response!

@munificent and @mit-mit for possible inclusion in our list of recommended lints.
