### ISSUE TITLE
Attempt to call external function which is not connected to the body does not cause error.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42182]
Dart VM version: 2.9.0-13.0.dev (dev) (Fri May 29 15:59:05 2020 +0200) on "windows_x64"

Dart Language Specification reads:

> An external function is connected to its body by an implementation specific mechanism. Attempting to invoke an external function that has not been connected to its body will throw a NoSuchMethodError or some subclass thereof.

Seems like the following source code example should throw error according to the rule above, however it does not happen:
``` dart
external int unexistent();

main() {
  print(unexistent());
}
```
Dart just goes through and prints `null` here.

**Comment by lrhn** [comment]
It should really fail at compile-time.

I guess the compiler phases don't agree on which one needs to report the error. After all, a later phase might add the implementation (like the VM does for dart:ffi).
Still, if the back-end specific compiler sees an `external` that it doesn't know what to do about, it should fail.

**Comment by mkustermann** [comment]
> It should really fail at compile-time. Throwing at run-time is a Dart 1 left-over.

@lrhn If it should fail at compile-time, shouldn't this issue be marked as CFE?

/cc @johnniwinther

**Comment by johnniwinther** [comment]
Only the backends know for which external functions an implementation exist. Therefore the CFE cannot report an error unless we can query the backend as to whether a particular external function is allowed. 

Patched functions are declared as external and the implementation is provided in terms of Dart code in the patch files. These are delivered as non-external functions to the backends and the CFE can only check that only external functions are patched (a check I'm not sure that we currently do) and the reverse (that all external functions are patched, which they are not).

Native methods for the VM, dart2js and ddc, and foreign and js-interop functions for dart2js and ddc are all external and delivered as such to the backends. The CFE currently knows nothing about how to recognize and verify these supported cases of external functions.

**Comment by eernstg** [comment]
The connection between an external declaration and an implementation is specific to each tool, so it is hardly possible to emit a compile-time error which is valid for all backends. Also, it would be a link-time property in any case. I think it makes sense to expect that a NoSuchMethodError is throw n at run time, as specified.

**Comment by lrhn** [comment]
I definitely want to emit compile-time errors *where possible*.

For example, we *promise* that all external members of the platform libraries are patched up, and we won't (mustn't) build the SDK if they are not.

If a back-end sees an `external` declaration and has no clue to where the implementation is, it should fail as early as possible. If it sees `@JS` or `@ffi` or something that suggests that it should provide the implementation, then it's fine to go on (and potentially do a nSMError later if it fails to link up with something anyway).

So, I want the specification to at least *allow* compile-time errors for unknown `external` declarations.

**Comment by mkustermann** [comment]
The VM uses the `native` syntax for natives (both in our patch files as well as for native extensions):

```dart
int foo() native "Foo_native";
```

So I believe from the VM point of view, an unpatched `external` can be a compile-time error.

**Comment by lrhn** [comment]
On the other hand, it sure would be nice if our common front-end didn't have to support a VM-only syntax extension. Have you considered no using `native` :smile:?

**Comment by mkustermann** [comment]
> On the other hand, it sure would be nice if our common front-end didn't have to support a VM-
> only syntax extension. Have you considered no using native 😄?

Well, we have to attach the native name somehow. In kernel it's basically represented as:
```
@ExternalName("Foo_native")
external int foo();
```

We could allow Dart to do the same. Then the rule would be: If an patched `external` member does not have an `ExternalName` annotation it should be a compile-time error.
