### ISSUE TITLE
[NNBD] No static warning for overriding parameter default value

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42195]
According to the Dart [specification](https://spec.dart.dev/DartLangSpecDraft.pdf) (Version 2.8.0-dev, April 22, 2020) 11.2.2 Correct Member Overrides

> • If m and m0 are both methods, p is an optional parameter of m, p0 is the parameter of m0
> corresponding to p, p has default value d and p0 has default value d0, then d and d0 must be identical, or a static warning occurs

It's true for non-NNBD, but not so when analyzer is run with `--enable-experiment=non-nullable` option. In this case there is no warning at all
```dart
class A {
  foo([x = 1]) {}
}

class C extends A {
  foo([x]); /// static type warning
}

main() {
  new C().foo(1);
}
```
Analyzer with `--enable-experiment=non-nullable` finds no issues in the code above
Please see also https://github.com/dart-lang/sdk/issues/34437
`dartanalyzer version 2.9.0-13.0.dev `

**Comment by scheglov** [comment]
I believe this WAI, because `C.foo` is abstract.

It was updated in 85c197a848a3083f2870e0e448d3603ec37cf073, as clarified by @eernstg [here](https://github.com/dart-lang/co19/issues/516#issuecomment-582039754).

**Comment by eernstg** [comment]
Right, an abstract method declaration with an optional parameter that does not specify a default value does not have a default value, so there is no conflict.
