### ISSUE TITLE
No static warning for not void user-defined []= operator

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42198]
According to the Dart specification (10.1.1 Operators)

> It is a static warning if the return type of a user-declared operator ‘[]=’ is
> explicitly declared and not void.

In fact, there is an error in analyzer and no issues in VM
```dart
class C {
  int operator []=(index, value) => 42;
  operator[](index) {}
}

main() {
  C c = new C();
  c[0] = new C();
}
```
The program above produces
` error - The return type of the operator []= must be 'void'`
in analyzer and no errors or warnings in VM

`Dart VM version: 2.9.0-13.0.dev (dev) (Fri May 29 15:59:05 2020 +0200) on "windows_x64"`

**Comment by devoncarew** [comment]
@sgrekhov - it sounds like the analyzer has correct behavior here, and we'll need to update the VM / CFE to have the same behavior?

**Comment by sgrekhov** [comment]
@devoncarew specifications states 'static warning' but analyzer produces 'compile error'. @eernstg  please confirm if it is correct

**Comment by eernstg** [comment]
This discrepancy has been known for a long time, cf. https://github.com/dart-lang/sdk/issues/36127 and https://github.com/dart-lang/sdk/issues/36126. Created https://github.com/dart-lang/language/issues/1012 to settle the issue in the way that is based on discussions is the language team over time.

**Comment by johnniwinther** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/161165
