### ISSUE TITLE
Incorrect analyzer error - extension method loses generic

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#42201]
This surfaces with `implicit-casts: false`, but the underlying loss of a generic type may happen regardless.

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

```dart
extension E<T> on List<T> {
  List<T> a() => this;
  List<T> b(List<T> other) => other.a(); // Error here
}
```

```
  error • A value of type 'List<dynamic>' can't be returned from method 'b' because it has a return type of 'List<T>'. • foo.dart:3:31 • return_of_invalid_type
1 error found.
```

This only happens on recent dev SDKs.

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/150271

**Comment by mmcdon20** [comment]
I think I have encountered the same issue, or possibly something similar.
I also have `implicit-casts: false` in analysis_options.
Though in my case it might be related to nested generics such as `Iterable<Iterable<T>>`.
```dart
extension DoubleIterable<T> on Iterable<Iterable<T>> {
  Iterable<Iterable<T>> test1() {
    if (isNotEmpty) {
      Iterable<Iterable<T>> x = skip(1).test1();
    }
    return [];
  }
}
```
```
error: A value of type 'Iterable<Iterable<dynamic>>' can't be assigned to a variable of type 'Iterable<Iterable<T>>'. 
```
However when I try to do the same thing on `Iterable<T>` rather than `Iterable<Iterable<T>>` there are no errors.
```dart
extension SingleIterable<T> on Iterable<T> {
  Iterable<T> test2() {
    if (isNotEmpty) {
      Iterable<T> x = skip(1).test2();
    }
    return [];
  }
}
```

**Comment by scheglov** [comment]
Yes, I think this is caused by the same issue.

However I see the error for both `DoubleIterable` and `SingleIterable` without the fix.
With the fix there are no errors in both.
