### ISSUE TITLE
Extension methods have different hashCode for the same instance

### ISSUE THREAD

**Issue by MHShetty** [dart-lang/sdk#42208]
```
class SomeType{}

extension Something on SomeType
{
void someFunction(){}
}

void main()
{
SomeType st = SomeType();
print(st.someFunction.hashCode); // Some value
print(st.someFunction.hashCode); // Some other value
}
```

Is there some way to ensure that the hashCode in both the cases remain same or can this be considered as a feature request?

**Comment by eernstg** [comment]
This is working as intended, cf. [this section](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md#tearoffs). The point is that a tear-off of an extension method may depend on static typing properties of the call site (as well as the receiver and the extension), so it cannot be justified in general to make tear-offs of extension methods equal in the case where they have the same receiver and resolve to the same extension method, that is, we can't treat them in the same way as torn off instance methods.

So these tear-offs ended up being non-equal, (except of course in the case where the comparison `e1 == e2` is evaluated and `e1` and `e2` evaluate to the exact same object, that is, the case where `identical(e1, e2)`).
