### ISSUE TITLE
Null safety migration tool not replacing /*required*/ correctly

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#42211]
The tool adds the `required` keyword, but does not remove the temporary annotation.

![required-replacement](https://user-images.githubusercontent.com/211513/83951975-652f3580-a7ea-11ea-9f02-33bdddea2139.png)

This happens when migrating https://github.com/flutter/engine/blob/c0365be2ab70836f2d53c8d6ab89fa9774be3ac5/lib/web_ui/lib/src/ui/semantics.dart#L669

/cc @stereotype441 @MichaelRFairhurst

**Comment by stereotype441** [comment]
@yjbanov
We never built in support for a `/*required*/` hint because we figured people would rather use the `@required` annotation (from `package:meta`).  Would that work just as well for you, or do you really need support for `/*required*/`?

**Comment by yjbanov** [comment]
> @yjbanov
> We never built in support for a `/*required*/` hint because we figured people would rather use the `@required` annotation (from `package:meta`). Would that work just as well for you, or do you really need support for `/*required*/`?

`package:meta` doesn't work because I'm migrating `dart:ui`, which doesn't have access to packages. Since this is a one-off library, let's keep it as is. I can migrate these manually.

**Comment by stereotype441** [comment]
> `package:meta` doesn't work because I'm migrating `dart:ui`, which doesn't have access to packages. Since this is a one-off library, let's keep it as is. I can migrate these manually.

Ah, that makes sense.  Sounds like a good plan.

**Comment by MichaelRFairhurst** [comment]
For what it's worth, you don't need to add /* required */ at all here. Just
the fact that the named argument is non nullable with no default value will
mean it gets migrated to a required named argument.

>
