### ISSUE TITLE
dart:html `window.console` log, error, info should take Object?, not Object

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#42213]
The JS version of `window.consol.log` and its siblings happily accept `null`. Why is the `dart:html` version restricting to non-null `Object`?

**Comment by devoncarew** [comment]
@vsmenon @sigmundch - I'm not sure who's migrating the dart:html APIs.

**Comment by vsmenon** [comment]
@srujzs

**Comment by srujzs** [comment]
Thanks for filing. These are hand-written and the current IDL checked in to Dart third_party doesn't have information on them, so Console methods were missed. You're correct that these should not be restricted to nullable; I'll modify `log` and similar methods and update this.
