### ISSUE TITLE
aot and docker

### ISSUE THREAD

**Issue by DavidBernal** [dart-lang/sdk#42215]
Hi, I detected some problems dockerizing a dart server.

I created a simple server:
```
import 'dart:io';

Future main() async {
  var server = await HttpServer.bind(
    InternetAddress.loopbackIPv4,
    4040,
  );
  print('Listening on localhost:${server.port}');

  await for (HttpRequest request in server) {
    request.response.write('Hello, world!');
    await request.response.close();
  }
}
```
When I compile to aot and execute the binary, all works as expected.
But when I put the binary in a docker container, exposing needed ports, I can't access to server.

**Comment by devoncarew** [comment]
@DavidBernal - is this issue specific to the AOT compiled version, or do you see this with a non-AOT compiled dart app as well?

**Comment by DavidBernal** [comment]
Is a AOT compiled version problem. Same server.dart running on a docker works fine. I have a little example here:
https://github.com/DavidBernal/dart-aot-docker

There are 4 possible scenario:
- Running dart on pc
- Running aot on pc
- Running dart on docker
- Running aot on docker

All works correctly except last one scenario.

**Comment by devoncarew** [comment]
Thanks!

**Comment by devoncarew** [comment]
@mraleph - where's the best place to triage AOT items?

**Comment by DavidBernal** [comment]
I can improve the repo example if you need.

**Comment by aam** [comment]
@DavidBernal can you try generating aot snapshot and running that (via `dartaotruntime`) in the docker?

```
$ dart-sdk/bin/dart2native -k aot server.dart 
Generated: /usr/local/google/home/aam/p/d/dart-sdk/sdk/server.aot
$ dart-sdk/bin/dartaotruntime server.aot     
Listening on localhost:4040
```

Also when you can't connect to the server, does it still produce "Listening on..." message?

**Comment by DavidBernal** [comment]
I finally found my problem. The simple example uses `InternetAddress.loopbackIPv4`. For running on docker must be `InternetAddress.anyIPv4`.

Sorry for wasted time.
