### ISSUE TITLE
Null safety: late non-null variables should not complain about null checking

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#42214]
Late non-null variables complain when they are null-checked: "Condition will always be true in strong checking mode".

It is common to lazy initialize a variable to a non-null value, but the initialization code must be able to check if the variable is already initialized:

![late-non-null](https://user-images.githubusercontent.com/211513/83952491-0b306f00-a7ee-11ea-9c3c-a6d88519dd6f.png)

**Comment by devoncarew** [comment]
cc @eernstg @stereotype441 - I'm not sure of this is a usability issue with `late` or an analyzer issue.

**Comment by leafpetersen** [comment]
> It is common to lazy initialize a variable to a non-null value, but the initialization code must be able to check if the variable is already initialized:

There is no way to tell if a `late` variable is initialized (other than trying to read it and catching the resulting exception, I suppose).  We discussed adding support for this, but chose not to.

**Comment by yjbanov** [comment]
Ok, I guess we can use a `bool` variable next to the `late` variable to tell if it was initialized.
