### ISSUE TITLE
Const constructor can't be declared for a class with a mixin that declares an instance field

### ISSUE THREAD

**Issue by vr19860507** [dart-lang/sdk#42218]
Is it a bug or a feature?

```
mixin A {
  int get prop => 1;
}

class B with A {
  const B();
}
```
_-> Const constructor can't be declared for a class with a mixin that declares an instance field_

But this works!

```
class A {
  const A();
  int get prop => 1;
}

class B extends A {
  const B();
}
```

**Comment by eernstg** [comment]
This is a bug, `int get prop => 1;` does not declare an instance field.

**Comment by srawlins** [comment]
Thanks for reporting this issue! This is a duplicate of https://github.com/dart-lang/sdk/issues/37810

**Comment by srawlins** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/37810
