### ISSUE TITLE
Dart2js error when calling toString() on Null

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42219]
The following program produces an error on dart2js
```dart
class A {}

main() {
  A? a = null;
  var x = a.toString();
}
```
```
Runtime error:
TypeError: C.JSNull_methods.toString$0 is not a function
```
Calling of Object methods on Null is not an error in Dart
`Dart VM version: 2.9.0-13.0.dev (dev) (Fri May 29 15:59:05 2020 +0200) on "windows_x64"`

**Comment by fishythefish** [comment]
There seems to be a tree-shaking issue here. If we `print(x);` (or just `print(a.toString());`), then the code runs properly.

**Comment by rakudrama** [comment]
This no longer reproduces.
```js
X = {
    main: function() {
      C.JSNull_methods.toString$0(null);
    }
  };
...
  J.JSNull.prototype = {
    toString$0: function(receiver) {
      return "null";
    }
  };
```
