### ISSUE TITLE
CFE error in type inference for ArgumentError.checkNotNull 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#42227]
See this dartpad example (reproduces at head) https://nullsafety.dartpad.dev/a4772f72bd4d0f58a04356efd0f43355.

It infers the T type to be the nullable variant of the arg instead of the non-nullable variant.

This is likely a result of the `T?` type specified for the first argument not playing nicely with an already nullable T.

cc @johnniwinther can you have somebody take a look at this?

**Comment by johnniwinther** [comment]
@stefantsov is working on it. See #41447

**Comment by jakemac53** [comment]
Sounds good, closing this as a dupe then
