### ISSUE TITLE
Problem with analyzer for generic recursive static extension methods

### ISSUE THREAD

**Issue by jackdreilly** [dart-lang/sdk#42225]
`Dart VM version: 2.9.0-13.0.dev.flutter-02915ec5ce (be) (Wed Jun 3 21:58:10 2020 +0000) on "macos_x64"`

After updating flutter (and dart in turn I imagine), I started getting this error on dartanalyzer:

```dart
import 'package:flutter_test/flutter_test.dart';

Iterable<T> _sidestep<T>(Iterable<T> t) =>
    t.isEmpty ? null : t.skip(1).recursive;

extension<T> on Iterable<T> {
  Iterable<T> get recursiveSidestep => _sidestep(this);
  // Shows error "A value of type 'Iterable<dynamic>' can't be returned from function 'recursive' because it has a return type of 'Iterable<T>'"
  Iterable<T> get recursive => this.isEmpty ? null : skip(1).recursive;
}

void main() {
  test("recursiveSidestep", () => expect([3].recursiveSidestep, isNull));
  test("recursive", () => expect([3].recursive, isNull));
}
```

the code compiles, both tests pass, and `recursiveSidestep` does not report any analyzer errors, but `recursive` does report analyzer error shown

**Comment by devoncarew** [comment]
@jackdreilly - is this the same as https://github.com/dart-lang/sdk/issues/42201 ?

**Comment by jackdreilly** [comment]
Yes looks like the same symptoms

**Comment by devoncarew** [comment]
Thanks; that issue has been fixed in master. I'll close this one as a dupe.
