### ISSUE TITLE
int and double with the same value are identical on dart2js and dartdevk

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42222]
The following test fails on dart2js and dartdevk

```dart
import "../../../Utils/expect.dart";

var i1 = 2;
var d2 = 2.0;

main() {
  Expect.isFalse(identical(i1, d2));
}
```
Here `i1` is integer and `d2` is double. They cannot be identical

`SDK version 2.9.0-13.0.dev `

**Comment by eernstg** [comment]
Yes, compilation to JavaScript turns all numbers into JavaScript numbers, so the `int` value 2 and the `double` value 2.0 have the same representation. So any test doing this should be skipped by design with configurations that compile to JavaScript.

**Comment by eernstg** [comment]
Said test is skipped in https://dart-review.googlesource.com/c/sdk/+/207130.
