### ISSUE TITLE
Failures on [vm] IL instruction for UTF-8 scan.

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#42226]
There are new test failures on [[vm] IL instruction for UTF-8 scan](https://dart-review.googlesource.com/c/sdk/+/148762) when combined with https://github.com/dart-lang/sdk/commit/3451c348dbed2d80632f8141d6ab69651442eabc.

The tests
```
vm/cc/DartAPI_CollectOneNewSpacePeer Fail (expected Pass)
vm/cc/DartAPI_WeakPersistentHandle Fail (expected Pass)
vm/cc/WeakProperty_PreserveCrossGen Fail (expected Pass)
```
are failing on configurations
```
dartk-linux-debug-ia32-canary
```

It looks like the failures are not directly related to the `Utf8Scan` instruction. They occur even if the instruction is never generated.

**Comment by rmacnak-google** [comment]
These tests are currently passing.
