### ISSUE TITLE
Dart Analyzer goes into an infinite loop if file contains `Stream<List<>>`

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#42229]
Reproducible with Dart SDK 2.8.4 and 2.9.0-13.0.dev. Create file `foo.dart` with the following content 
```
Stream<List<>>
```
and run `dartanalyzer foo.dart`. Dart Analyzer runs some infinite calculations which never end.

The same with Dart Analysis Server, so to reproduce just type `Stream<List<>>` in an empty file in any IDE.

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by scheglov** [comment]
When we parse this file, the parser invokes `endTypeVariables` with invalid `endToken`. It should be `>`, but it is `EOF`.
![image](https://user-images.githubusercontent.com/384794/84058819-9d5f8100-a96e-11ea-888c-3863c34214d6.png)

When I tried to reproduce this in a unit test, the `assert` was triggered, and we end up with an empty unit, as a safeguard against exceptions in the parser. Maybe `assert` is not enough and we should check tokens always.

Anyway, I think this is a bug in the parser.

**Comment by bwilkerson** [comment]
@jensjoha
