### ISSUE TITLE
yield* cannot be used to yield a more specific iterator type

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42234]
I would expect the following code to print `1` and then `2`:
```dart
Iterable<Object> f() sync* {
  yield* g();
}

Iterable<int> g() sync* {
  yield 1;
  yield 2;
}

main() {
  for (var i in f()) {
    print(i);
  }
}
```
But instead it produces this exception when run under the VM:
```
Unhandled exception:
type '() => (_SyncIterator<int>) => bool' is not a subtype of type '() => (_SyncIterator<Object>) => bool'
#0      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:186:39)
#1      main (file:///usr/local/google/home/paulberry/tmp/test.dart:11:17)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
If replace `yield* g();` with `for (var value in g()) yield value;` (which I believe should be equivalent), then the program works as intended.

Digging through the code in `core_patch.dart`, it looks like the functionality of `yield*` has been implemented in such a way that it requires the runtime types of the two iterators to be the same, but as far as I can tell from reading the spec, that shouldn't be required.

**Comment by stereotype441** [comment]
@a-siva FYI

**Comment by mkustermann** [comment]
Maybe this is related to the recent sync* optimizations @cskau-g was working on.

**Comment by stereotype441** [comment]
Any update on this?  I'm still running into this problem.

**Comment by cskau-g** [comment]
Work is in progress. My hope is I'll be able to land something next week.
