### ISSUE TITLE
Passing mp3 asset from Flutter to Oboe

### ISSUE THREAD

**Issue by ffarall** [dart-lang/sdk#42233]
I'm trying to use Google Oboe for a 3D audio processing app due to it's low latency. The app will have a C++ backend, which does the processing, and the frontend is done with Flutter. I'm running a couple of tests to see if it'll work but I'm having issues loading assets from Flutter to Oboe. I checked the example RhythmGame in Oboe's [repo](https://github.com/google/oboe), done with Java, but couldn't quiet find a way of doing that straight from Dart to C++. The connection between front and backend is through [dart::ffi](https://dart.dev/guides/libraries/c-interop)

**Comment by dcharkes** [comment]
(answer in other issue)
