### ISSUE TITLE
Analyzer throws a compile error when async function with Future<bool> return type returns dynamic.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42237]
Dart VM version: 2.9.0-13.0.dev (dev) (Fri May 29 15:59:05 2020 +0200) on "windows_x64"

This issue is related with SDK Issues #41266, #41437, as well as with co19 issues [#603](https://github.com/dart-lang/co19/issues/603) and [703](https://github.com/dart-lang/co19/issues/#703).

It is similar with #42236, but it's agains analyzer, not dart.

Seems like after the [#941](https://github.com/dart-lang/language/pull/941)  the following code should not throw compile error:
``` dart
import "dart:async";
dynamic getNull() => null;
Future<bool> test1() async => await getNull();
main() {}
```
However, still dartanalyzer behaves in such a way.

Sample output is:

> $> dartanalyzer --enable-experiment=non-nullable test.dart 
> Analyzing test.dart...
>   error - A value of type 'dynamic' can't be returned from function 'test1' because it has a return type of 'Future<bool>'. - test.dart:3:31 - return_of_invalid_type
> 1 error found.
>

**Comment by scheglov** [comment]
This was fixed in 89782c96d9d02dd0c4758d3b285dd57fb32745be, the same day as the SDK build that you are trying.
But maybe a few hours later?

Works for me with the bleeding edge SDK.
![image](https://user-images.githubusercontent.com/384794/84815806-6d485b80-afc8-11ea-81ed-899658257570.png)
