### ISSUE TITLE
Remove the use of `fuchsia.deprecatedtimezone`

### ISSUE THREAD

**Issue by filmil** [dart-lang/sdk#42245]
This is re-attempting https://github.com/dart-lang/sdk/issues/39650.  Previous attempt broke important downstream tests, and had to be rolled back to unblock work.  These tests are now being fixed, and I want to proceed with this change once downstream is all updated.

Could you please assign me to this issue?

Original issue below.

---
This is related to issue #39174.

Now that we've removed the use of fuchsia.timezone, we're on to removing the uses of fuchsia.deprecatedtimezone. I'll be working on this, and unless someone else is really eager to take it over, you can expect a pull request from me soon.

**Comment by devoncarew** [comment]
cc'ing @rmacnak-google and @iskakaushik, who reviewed the original CL.

**Comment by filmil** [comment]
FYI: https://dart-review.googlesource.com/c/sdk/+/150662

**Comment by chinmaygarde** [comment]
Assuming this as stale and not planned.

**Comment by filmil** [comment]
This was long done I think.
