### ISSUE TITLE
Use 21st century terms in the SDK repo

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42247]
See https://developers.google.com/style/word-list RE allow/block list, master/slave alternatives etc

Will require work items across different components.

**Comment by kevmoo** [comment]
CC @vsmenon

**Comment by mit-mit** [comment]
First CL: https://dart-review.googlesource.com/c/sdk/+/150623

**Comment by mit-mit** [comment]
Second CL: https://dart-review.googlesource.com/c/sdk/+/150626

**Comment by mit-mit** [comment]
@mraleph did you have an alternate PR for https://dart-review.googlesource.com/c/sdk/+/150630 ?

**Comment by mit-mit** [comment]
I believe this is now complete
