### ISSUE TITLE
Confusing type inference

### ISSUE THREAD

**Issue by edwjusti** [dart-lang/sdk#42243]
Dart version: 2.8.4
OS: Linux

I've noticed that the dart analyzer is inferring incorrect argument types in closure scope when inferring from named arguments. I'm using VS Code but I also 
tested on Android Studio and the problem still happens.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17240777/84159237-395abc80-aa43-11ea-8678-6f656d12e06a.gif)

**Comment by devoncarew** [comment]
cc @jwren @bwilkerson

**Comment by bwilkerson** [comment]
@scheglov Is this a bug in type inference, a bug in the way server is displaying information, or the correct behavior?

**Comment by eernstg** [comment]
https://github.com/dart-lang/language/issues/731 describes the issue about not transferring information between arguments during type inference.

**Comment by leafpetersen** [comment]
Yeah, sorry, the style of inference we use doesn't do a good job of moving information between arguments.  There are some heuristics I'd like to implement which would improve examples like this a lot, but it's a breaking change so we need to pick the right time to roll them out.  Closing in favor of the existing tracking issue.
