### ISSUE TITLE
Add quick fix to switch from default List constructor to a better one

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42251]
With null safety enabled, it is an error to call the default List constructor.  Currently the analyzer reports this error as follows:

```dart
leafp-macbookpro:sdk leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable  ~/tmp/test.dart
Analyzing /Users/leafp/tmp/test.dart...
  error • Calling the default 'List' constructor causes an error. • /Users/leafp/tmp/test.dart:2:15 • default_list_constructor
```

This is a not very helpful error, since it doesn't make it clear what the error is.  It would be better to say something like "error: The default `List` constructor is not available when null safety is enabled" that makes it clear that it is the use of the constructor itself that is no longer valid.

As an aside, if not already implemented, this would be a great candidate for a quick fix: that is, suggest replacing `List<T?>(count)` with  `List<T?>.filled(count, null, growable:false)`.

cc @yjbanov @a14n

**Comment by bwilkerson** [comment]
I like that much better, thanks! The current correction advice is:

> Try using a list literal, 'List.filled' or 'List.generate'.

We don't currently have a quick fix for it, but it's on my list of fixes to try to add for Null Safety.

**Comment by srawlins** [comment]
The message has been fixed. New issue for quick fix?

**Comment by bwilkerson** [comment]
The message was fixed by https://dart-review.googlesource.com/c/sdk/+/150692.

**Comment by scheglov** [comment]
@bwilkerson You added a quick fix for this. Can we close the issue?

**Comment by bwilkerson** [comment]
I haven't actually gotten back to committing it yet. I think I want to experiment with turning it into an assist instead of a fix.

**Comment by scheglov** [comment]
OK
I thought `ReplaceWithFilled` is the fix for it.

**Comment by bwilkerson** [comment]
Oh, you're right. I was confusing it with a different fix.
