### ISSUE TITLE
Wrong error in analyzer for mixins calling 'super'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42255]
The following code has no issues in VM but error in analyzer
```dart
class M {
  String get s => super.toString();
}

class SuperA {
}

class A = SuperA with M;  // error - The class 'M' can't be used as a mixin because it references 'super'

main() {
  A a = new A();
}
```
Mixins can only be extracted from classes with superclass `Object`. Therefore `super` calls of members of `Object` are allowed. There must be no such error in analyzer

See https://github.com/dart-lang/sdk/issues/42239 discussion for more details

Tested on `Dart VM version: 2.9.0-13.0.dev (dev) (Fri May 29 15:59:05 2020 +0200) on "windows_x64"`

**Comment by srawlins** [comment]
An error is no longer reported.
