### ISSUE TITLE
Ensure programs compiled with DDC can compile and run with sound null safety

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42253]
To compile DDC needs a sound .dill file of the sdk libraries.

To run compiled code the build/test/run systems needs access to a sound version of the sdk libraries compiled to Javascript.

**Comment by sigmundch** [comment]
Will we need additional changes in frontend server to support this in flutter web?

**Comment by nshahan** [comment]
https://github.com/flutter/engine/pull/19162 is in progress to build the sound js file but I think there will need to be more work to make sure the right version is being used when running with `--sound-null-saftety`.

**Comment by nshahan** [comment]
Tracking issue in the build repo: https://github.com/dart-lang/build/issues/2723

**Comment by leafpetersen** [comment]
This is a blocker for the beta release, yes?  Status on it?

**Comment by nshahan** [comment]
@jakemac53 Where do we stand at this point with the branch you were working on in the build repo?

**Comment by jakemac53** [comment]
I got blocked for a bit waiting for an sdk release and got side-tracked with some other things. I could pick it back up soon though.

**Comment by sigmundch** [comment]
@jakemac53 - just curious if you have any updates or if you need anything from us

**Comment by jakemac53** [comment]
I have started back on this, hit another blocker on our end which I have a PR out for and then I can resume.

**Comment by franklinyow** [comment]
Is this still a Beta issue?  The issue that block this  (#43097) is in post Beta.  So we need to decide which is the correct timeframe.

**Comment by nshahan** [comment]
Yeah that probably isn't a good blocker issue. I can adjust but I'm waiting for some feedback from emails I sent to @jakemac53 (build_web_compilers support) and @jonahwilliams (flutter web support) before I file more issues.

**Comment by jakemac53** [comment]
Sound null safety is implemented now in build_web_compilers - but we don't support the runtime toggles for other modes.

**Comment by jonahwilliams** [comment]
The flutter engine compiles additional sound mode dills for ddc, and we support null-assertions in debug modes.

**Comment by nshahan** [comment]
After some experiments and a fix https://github.com/flutter/engine/pull/21784, I am going to close this issue. I believe we have all uses of DDC supporting the option for sound null safety. If we find another example of it not working we should treat it as a bug and file a new issue.

Now tracking the support for toggling the native null asserts in a new issue https://github.com/dart-lang/sdk/issues/43780.
