### ISSUE TITLE
Null safety migration tool does not highlight all insertions

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#42265]
Typically the migration tool highlights all `?`, `!`, and `required` that it inserts into the code, like this:

![highlighted insertions](https://user-images.githubusercontent.com/211513/84300155-c581e800-ab06-11ea-9ba1-8e51f0bb5580.png)

However, sometimes it doesn't. For example, notice that below the `!` in `o!.hashCode` was not highlighted:

![dart migration unmarked insertions](https://user-images.githubusercontent.com/211513/84300236-df232f80-ab06-11ea-8e94-b548fc507700.png)

**Comment by srawlins** [comment]
It appears to happen when the null check was added due to a member access / method call of a member on Object (like `hashCode` or `toString`).

**Comment by srawlins** [comment]
@MichaelRFairhurst fixed this in https://github.com/dart-lang/sdk/commit/e11eb2cd0834804a9a4f3f09f7868f531ff470db
