### ISSUE TITLE
Turning reified types into legacy types for constant expressions

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42262]
Thanks to @fishythefish for noting this. Consider the following program:

```dart
typedef T = int? Function();
const t = T;

void main() {
  print(T);
  print(t);
}
```

This prints `() => int?` and `() => int` with `dart --enable-experiment=non-nullable --no-null-safety` from c800b8d19caec71b354edcee207c405173dffafb.

However, https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#const-evaluation-and-canonicalization only specifies that _type arguments_ passed to collection literals and constant object expressions should be turned into legacy types in weak checking mode, but the above doesn't include any type arguments, and there does not seem to be a rule that turns function types into legacy types for constant expressions.

**Comment by fishythefish** [comment]
IMO, we should update the CFE to match what's currently in the spec and only perform the legacy erasure where needed to improve canonicalization.

Tentative fix: https://dart-review.googlesource.com/c/sdk/+/150821

**Comment by alexmarkov** [comment]
@crelier VM also applies legacy erasure to core libraries when loading them from agnostic platform dill file in weak mode. Do we need to avoid applying legacy erasure when handling `kTypeLiteralConstant` in `ConstantReader::ReadConstantInternal` ?

**Comment by crelier** [comment]
@alexmarkov We indeed apply legacy erasure to type literals, which, according to this report is wrong.
I'll send a CL. Thanks for noticing.

**Comment by crelier** [comment]
VM fix: https://dart-review.googlesource.com/c/sdk/+/151020
