### ISSUE TITLE
Analyzer suggests non-constant expressions in auto-complete

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#42264]
Simple reproduction case:

```dart
class Component {
  const Component(List<Object> any);
}

class NotAConst {}

@Component([
  NotA^
])
class Example {}
```

Auto-completes with:

* `NotAConst()`
* `NotAConst`

Only the latter is valid, `NotAConst()` is not a valid expression in that context.

**Comment by srawlins** [comment]
Great suggestion. I wonder if the proper enhancement would be to _reduce the rank_ of `NotAConst`? Or remove it from the suggestions? I don't know what the general philosophy is.

**Comment by bwilkerson** [comment]
The `isConstant` feature is intended to take into account whether completion is happening in a constant context.
