### ISSUE TITLE
Analyzer: Incorrect function literal inference when in a legacy context 

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42278]
Consider the following program:

out_of_order.dart
```
// @dart = 2.7

void foo(int Function(int) x) {}
```

in_order.dart
```
import 'out_of_order.dart';

void test() {
  int? s = null;
  foo((x) => s);
}
```

I believe that as specified, we should be inferring the argument to `foo` in a context where the return type is `int*` (that is, legacy `int`).  The inferred return type of the body is `int?`, which is a subtype of `int*`, and so by my read we should be choosing `int?` as the inferred return type for the function literal.  As a result, the function literal should have inferred type `int? Function(int)` which is assignable to `int* Function(int*)`, and the body of the function should have no errors, since the return value and the return type are compatible.  

The analyzer currently seems to be inferring the non-nullable type `int` as the return type for the function literal:

```
leafp-macbookpro:sdk leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable ~/tmp/opted_out.dart
Analyzing /Users/leafp/tmp/opted_out.dart...
  error • The return type 'int?' isn't a 'int', as required by the closure's context. • /Users/leafp/tmp/opted_in.dart:5:14 • return_of_invalid_type_from_closure
```

cc @yjbanov @scheglov

**Comment by leafpetersen** [comment]
@scheglov yes, sorry, that's a little unclear.  My intent was that inference uses whatever type it is given, but that at the point that you actually have to "write down" an inferred type in an opted in library, you erase it. It's possible that I have incoherent expectations here, but it looks like the CFE is doing what I expect on this, so in any case we have an inconsistency to sort out. 

I'll try to make some time to write a few tests to poke corners of this.  I'll have to think about where else it's observable.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/151000
