### ISSUE TITLE
Feature request: lint about imports not in your direct dependencies

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#42286]
`pub publish` will bark at you if you try to publish with an import from a transitive dependency.

But it would be nice to get an upfront alert from a lint that you are importing from a package that is not in the direct dependencies in your pubspec.yaml.

**Comment by bwilkerson** [comment]
I like that idea.

On a related note, we've talked in the past about having a lint to check for imports inside `lib` of packages that are only in the dev dependencies. Not sure whether we want one rule that does both or two separate rules.

@pq

**Comment by pq** [comment]
👍

See these lint requests (w/ discussion): https://github.com/dart-lang/linter/issues/29 and https://github.com/dart-lang/linter/issues/30.
