### ISSUE TITLE
"old_dill" tests fail after moving `BytesBuilder`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#42288]
The CL https://dart-review.googlesource.com/c/sdk/+/150523 moves the `BytesBuilder` class to `dart:_internal` and exports it from both `dart:io` and `dart:typed_data`.

Almost all tests succeed, except tests similar to
```
cfe-unittest-asserts-release-linux:pkg/front_end/test/old_dill/dart2js.version.29.compile.1
```
(version 29 through 42) which fail with:
```
stderr: ../../runtime/vm/object.cc: 4175: error: Unable to use class Library:'dart:io' Class: BytesBuilder which is not loaded yet.
version=2.9.0-edge.9cca0f733a04f821188309738c21982fba34e4c0 (be) (Wed Jun 10 11:04:37 2020 +0000) on "linux_x64"
pid=14522, thread=14522, isolate_group=main(0x562d2d338a00), isolate=main(0x562d2ba6a900)
isolate_instructions=562d29a72e20, vm_instructions=562d29a72e20
...
```
(https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8877883394430548816/+/steps/test_results/0/logs/new_test_failures__logs_/0)

I'm guessing this is a VM issue since there is no way to change the old `.dill` files.

**Comment by alexmarkov** [comment]
This change breaks running old dill files (which still reference BytesBuilder from dart:io) on the new VM. Maybe we should purge all old dill files from that test and/or bump kernel version. In any case, this should be fixed on the front-end side, if we want to proceed with this change.

@jensjoha @johnniwinther

**Comment by jensjoha** [comment]
I suppose the only solution, if wanting to land this, would be to
* Bump the kernel version number
* Bump the VMs `static const uint32_t kMinSupportedKernelFormatVersion = 29;` to match the new version number
* Delete all old dills in the test

Someone else should make a decision about dropping backwards compatibility though.

This is probably also in line with https://github.com/dart-lang/sdk/issues/41802

**Comment by mkustermann** [comment]
@cskau-g is preparing a CL for embedding SDK hash into the kernel files for https://github.com/dart-lang/sdk/issues/41802. If we can find agreement to move forward with that then we can turn off checking for old dill files - simplifying our lives a little more :)

**Comment by lrhn** [comment]
So, if I land this tomorrow (which I won't because that's Saturday, but hypothetically ...), would it be a problem, and whose problem would it be?
(That is: Am I blocked making the platform library change, and if so, whose decision will unblock it?)

I'd obviously pre-approve the failures and refer to the issue.

**Comment by alexmarkov** [comment]
Embedding hashes into kernel files would break compatibility on many commits in Dart SDK. If we're planning to do https://github.com/dart-lang/sdk/issues/41802 anyway, we could use this case as an opportunity to test if anyone relies on backwards compatibility by doing what @jensjoha suggested above and unblocking @lrhn . This would break backwards compatibility once, even without embedding hashes into kernel files and may help us discover possible downstream dependencies on binary compatibility.

**Comment by mkustermann** [comment]
> If we're planning to do #41802 anyway, we could use this case as an opportunity to test if 
> anyone relies on backwards compatibility 

Yes, landing the sdk hash CL will bump the kernel version number and sets min supported version to the same, i.e. a breaking backwards compatibility. So we'll notice any issues when we land it and roll it to flutter / fuchsia / g3.

**Comment by lrhn** [comment]
Any progress here, or should I just mark it as failing and commit?

**Comment by mkustermann** [comment]
@cskau-g  has landed the CL in https://github.com/dart-lang/sdk/commit/edde575dcd6eb98bc7735693b2bfd92cd2a552f0 but it got reverted. Once it re-lands and sticks we could disable those old dill tests.

**Comment by mkustermann** [comment]
The SDK hash related changes have landed now, see https://github.com/dart-lang/sdk/issues/41802

We are still waiting until it rolls upstream and gets corresponding changes made in google3. Once this has happened, we could remove these old dill tests - which seemingly causes a lot of struggle for people.

**Comment by jensjoha** [comment]
I think this is obsolete. If nothing else the old_dill test was deleted in d69a2110ef92d79d91320196223ab2bd6ee68af8.
