### ISSUE TITLE
some dart2js_2/native/ not allowed to import private libraries

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#42292]
I noticed this after Stephen's change reverting a commit yesterday. Here are the details from the approval workflow:

There are new test failures on [Revert "[dart2js] Delete unused old-rti helpers"](https://github.com/dart-lang/sdk/commit/96fc158e4e1851472faa1fcc4d53500df54649b7).

The tests
```
dart2js_2/native/inference_of_helper_methods_test CompileTimeError (expected Pass)
```
are failing on configurations
```
unittest-weak-asserts-no-sdk-linux
```

Link to the failure log: https://dart-ci.appspot.com/log/dart2js-nnbd-linux-x64-chrome/unittest-weak-asserts-no-sdk-linux/1914/dart2js_2/native/inference_of_helper_methods_test

**Comment by joshualitt** [comment]
Turns out this configuration runs on the vm. I am landing a cl to stop running internal dart2js tests on the vm. Most likely this is just a holdover from when the unittests lived in tests/compiler/dart2js.
