### ISSUE TITLE
incorrect definitely unassigned error with late

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#42301]
Although it looks correct the following code triggers an error : 

> The late local variable 'i' is definitely unassigned at this point - line 11

```dart
main() {
  late int i;
  bool b = true;
  while(true) {
    switch (b) {
      case true:
        i = 1;
        b = false;
        break;
      case false:
        print(i);
        return;
    }
  }
}
```

Tested on https://nullsafety.dartpad.dev/ (Based on Dart SDK 2.9.0-edge.2ed302bfbbbad1d10f6c839c504ae3871fc96dc2)

**Comment by lrhn** [comment]
The example proves that `i` is not definitely unassigned, so there is a bug in the analysis.
Do we think it's in the specification or the implementation?

I'm guessing we're not going for a fixed-point when we analyse loops for *type**, but reachability and definite assignment should be binary properties, so my hunch is that we should be able to find the fixed point of the reachability/assignment analysis in two iterations. (It doesn't depend on types or values, right?)

**Comment by leafpetersen** [comment]
> The example proves that `i` is not definitely unassigned, so there is a bug in the analysis.

@scheglov this looks like a bug in the analysis.  The analysis may approximate, but it should be sound (that is, it may say something is potentially assigned when it isn't, but it shouldn't say something is definitely unassigned when it isn't).

**Comment by scheglov** [comment]
Right, just as we demote all variables potentially assigned in a loop, we should remove "definitely unassigned" from them.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/151047
