### ISSUE TITLE
Future.timeout documention is misleading

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#42318]
The documentation for [`Future.timeout`](https://api.dart.dev/stable/2.8.4/dart-async/Future-class.html) states:

> If this future does not complete before `timeLimit` has passed, the `onTimeout` action is executed instead, and its result (whether it returns or throws) is used as the result of the returned future. 

That it says the `onTimeout` action is executed *instead* implies that the original `Future` computation will be cancelled.  This isn't true; AFAICT there is no way to cancel a pending `Future`, and misunderstanding this can matter if the original `Future`'s computation has side effects.  This can be observed in the following code:

```dart
Future<void> main() async {
  await Future<void>.delayed(
    const Duration(seconds: 2),
    () => print('Normal computation completed'),
  ).timeout(
    const Duration(seconds: 1),
    onTimeout: () => print('Future timed out'),
  );
}
```
which eventually prints:

```
Future timed out
Normal computation completed
```

A simple fix could be to just replace "instead" with "first" ("... the `onTimeout` action is executed first, ..."), although it probably would be clearer to explain that the original `Future` could still eventually complete, which can be observed if it has side effects.

* Dart SDK: 2.8.4 on Linux

**Comment by happy-san** [comment]
[check this out](https://medium.com/flutter-community/a-guide-to-using-futures-in-flutter-for-beginners-ebeddfbfb967#9bc2) 😆

**Comment by brunovsiqueira** [comment]
@happy-san you can go to https://dartpad.dev/ and runs the code in the article you referenced. It gives the exact opposite result that the guy in the article states. @jamesderlin is correct. Both codes are almost the same. Give it a try, runs the code in dartpad and see what happens: the future is not canceled and "Normal computation completed" is printed.

In my opinion it is a critical issue and Dart should be given the due importance to it.

**Comment by lrhn** [comment]
The "instead" is ambiguous, it doesn't say what the alternative behavior replaces.
It's not the original future completing, but the new future completing with the original's value.

It can be made clearer. I'll try to do so.
