### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by seabhra** [dart-lang/sdk#42311]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.7.0`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

**Comment by lrhn** [comment]
I think some information is missing here. Do you have more information about the problem?

**Comment by srawlins** [comment]
Please re-open if you see this problem again.
