### ISSUE TITLE
Analyzer does not make forwarding constructor const in mixin application class.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#42315]
Example:
```dart
class C {
  final x;
  const C([this.x = 0]) : assert(x != null);
}
mixin M {}
class D = C with M;
main() {
  print(const D().x);
}
```
The analyzer warns that "The constructor being called isn't a const constructor - line 8". That constructor is the constructor of the mixin application, which should be a constant constructor.

**Comment by srawlins** [comment]
Was this on a recent build? I've fixed a few bugs on forwarding const constructors recently. I don't see any errors at 213f80529429f28efc577246388b5c9568a94f55.

**Comment by lrhn** [comment]
I was testing using DartPad, so it might not be the most recent build.
(Is DartPad always the most recent stable?)
I was testing for something else when this got in the way, so this is not the bug I came there for. My bad, will remember testing locally first :)
