### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by aliannus2** [dart-lang/sdk#42319]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.8.0-edge.c547f5d933e5a10e18b1b26b54a6249e88fa0f1c`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

**Comment by srawlins** [comment]
Please provide the crash stack trace that was presented, or some other detail.

**Comment by srawlins** [comment]
Please re-open if you see this problem again.
