### ISSUE TITLE
Named parameters should add default value when given null

### ISSUE THREAD

**Issue by jacobaraujo7** [dart-lang/sdk#42316]
Named parameters use default values in the constructor when they receive null, but when the null value is explicitly set, the default value is not added.

```dart
class MyClass{
   final int num;
  
    MyClass({this.num = 1});
}

void main() {
    
  var myClass = MyClass();
  print(myClass.num); //print 1
  
  myClass = MyClass(num: null);
  print(myClass.num); //print null
  
}
```
Dartpad [link](https://dartpad.dartlang.org/2170eb30bb8951708a59bf4e51726eea)

Is this behavior correct?
Shouldn't it return the default value when it explicitly receives the null?

**Comment by srawlins** [comment]
This behavior is correct. Default values are used when a value is not passed in for an optional parameter. When you pass in `null`, you are passing in a value.
