### ISSUE TITLE
Confusing CFE output when package language version is too old for null safety

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#42323]
In a package where the language version in package_config.json is < 2.9 and a library with a // @dart = 2.9 comment, running `dart --enable-experiment=non-nullable foo.dart` prints:

```
foo.dart:1:1: Error: A library can't opt out of non-nullable by default, when in nnbd-strong mode.
// @dart = 2.9
^
```

There are no `import` directives, this is the only library in the entire package.

This gives the impression that:

- The CFE/VM is deciding that the library _is_ opted in to null safety, and hence deciding to run in strong mode.
- The CFE is also deciding that the library _isn't_ opted in to null safety, and hence printing an error about running an opt-out library in strong mode.

Changing the language version to `2.9` in `package_config.json` resolves the issue (and removes the need for the language version comment).

**Comment by natebosch** [comment]
See also https://github.com/dart-lang/sdk/issues/42321 where the analyzer has similarly confusing output.

If we don't allow using a newer language version in a `// @dart = ` comment than what is in `package_config.json`, I think the error should state that explicitly.

**Comment by leafpetersen** [comment]
@munificent @lrhn @jakemac53 I think this *is* supposed to be allowed, to support the code generator use case right?

**Comment by lrhn** [comment]
Yes. We originally didn't allow libraries to require newer versions than the package itself, but that was dropped as a language requirement.
Pub should still prevent you from *publishing* something like that, but generating code locally based on the actual SDK is allowed.

**Comment by johnniwinther** [comment]
@jensjoha can you take a look at this?

**Comment by jensjoha** [comment]
Will be fixed with https://dart-review.googlesource.com/c/sdk/+/153769.
