### ISSUE TITLE
Migration: should sort files before processing them

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#42328]
Internally, b/158730342 was not 100% reliable. It seemed that on different runs it would raise one of two different exceptions.

This is likely because the processed resources are not consistently ordered.

This is a risk and files should probably be sorted before being processed to ensure all migrations get the same result.

**Comment by devoncarew** [comment]
@MichaelRFairhurst - I see the internal issue is fixed; I assume this can be closed?

**Comment by srawlins** [comment]
Closing for now; re-open if non-sorting is still an issue.
