### ISSUE TITLE
nnbd: dart2js leaks `_Required` placeholder values

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#42324]
I caught dart2js outputting code like this: https://gist.github.com/yjbanov/75c18b235a8dff8906a4a92182d67b36

Notice how `updateNode$5$actions$flags$id$rect$transform` passes `C.C__Required` to `updateNode$11$actions$childrenInHitTestOrder$childrenInTraversalOrder$decreasedValue$flags$id$increasedValue$label$rect$transform$value`
Then inside `updateNode$11$actions$childrenInHitTestOrder$childrenInTraversalOrder$decreasedValue$flags$id$increasedValue$label$rect$transform$value` it uses the value without any pre-processing.

This code is compiled from the following Dart code:

`dart:ui` opted into nnbd via `/// @dart = 2.9`:

```dart
class SemanticsUpdateBuilder {
  /// Creates an empty [SemanticsUpdateBuilder] object.
  SemanticsUpdateBuilder();

  final List<engine.SemanticsNodeUpdate> _nodeUpdates =
      <engine.SemanticsNodeUpdate>[];

  void updateNode({
    required int id,
    required int flags,
    required int actions,
    required int maxValueLength,
    required int currentValueLength,
    required int textSelectionBase,
    required int textSelectionExtent,
    required int platformViewId,
    required int scrollChildren,
    required int scrollIndex,
    required double scrollPosition,
    required double scrollExtentMax,
    required double scrollExtentMin,
    required double elevation,
    required double thickness,
    required Rect rect,
    required String label,
    required String hint,
    required String value,
    required String increasedValue,
    required String decreasedValue,
    TextDirection? textDirection,
    required Float64List transform,
    required Int32List childrenInTraversalOrder,
    required Int32List childrenInHitTestOrder,
    required Int32List additionalActions,
  }) {
    if ('$label'.contains('_Required')) {
      throw Exception('Value of label is "$label" of type ${label.runtimeType}');
    }
    if (transform.length != 16)
      throw ArgumentError('transform argument must have 16 entries.');
    _nodeUpdates.add(engine.SemanticsNodeUpdate(
      id: id,
      flags: flags,
      actions: actions,
      maxValueLength: maxValueLength,
      currentValueLength: currentValueLength,
      textSelectionBase: textSelectionBase,
      textSelectionExtent: textSelectionExtent,
      scrollChildren: scrollChildren,
      scrollIndex: scrollIndex,
      scrollPosition: scrollPosition,
      scrollExtentMax: scrollExtentMax,
      scrollExtentMin: scrollExtentMin,
      rect: rect,
      label: label,
      hint: hint,
      value: value,
      increasedValue: increasedValue,
      decreasedValue: decreasedValue,
      textDirection: textDirection,
      transform: engine.toMatrix32(transform),
      elevation: elevation,
      thickness: thickness,
      childrenInTraversalOrder: childrenInTraversalOrder,
      childrenInHitTestOrder: childrenInHitTestOrder,
      additionalActions: additionalActions,
      platformViewId: platformViewId,
    ));
  }

  ... rest omitted ...
}
```

Unit-test opted out via `// @dart = 2.6`, calling the `updateNode` method above like so:

```dart
    final ui.SemanticsUpdateBuilder builder = ui.SemanticsUpdateBuilder();
    builder.updateNode(
      id: 0,
      actions: 0,
      flags: 0 | ui.SemanticsFlag.isLiveRegion.index,
      transform: Matrix4.identity().toFloat64(),
      rect: const ui.Rect.fromLTRB(0, 0, 100, 50),
    );
```

I was not able to reduce this to a small example as the problem goes away when I isolate it into a small program. However, the complete code is available in this PR: https://github.com/flutter/engine/pull/19027. The files in question are:

- https://github.com/flutter/engine/pull/19027/files#diff-9dff65ff2b72217ebf48ff1f3f4b0358 (look for `updateNode` that's gaining a lot of `required` parameters.
- https://github.com/flutter/engine/blob/7cb7003a1190d24a76c57973170514303c3e2220/lib/web_ui/test/engine/semantics/semantics_test.dart#L1305 one of the failing tests.

/cc @vsmenon @sigmundch @leafpetersen

**Comment by leafpetersen** [comment]
cc @franklinyow this is blocking the flutter engine migration

**Comment by rakudrama** [comment]
Please send me the whole .js file.

**Comment by leafpetersen** [comment]
@yjbanov thinks they can continue to make progress, so maybe not blocking.

**Comment by yjbanov** [comment]
The whole JS file: https://drive.google.com/file/d/1mS8V2l7gCs2Q_lVAaI6-HjJerQhSKVxP/view?usp=sharing

**Comment by rakudrama** [comment]
Fix in review: https://dart-review.googlesource.com/c/sdk/+/151096

**Comment by yjbanov** [comment]
Thanks for the quick fix!

**Comment by rakudrama** [comment]
The fix is landed. @yjbanov  can you close this issue when you verify on your example?

**Comment by sigmundch** [comment]
@yjbanov was the issue resolved on your end?

**Comment by yjbanov** [comment]
Verified. This is fixed now. Thanks again!
