### ISSUE TITLE
Flaky failure on lib_2/async/stream_state_nonzero_timer_test

### ISSUE THREAD

**Issue by zichangg** [dart-lang/sdk#42331]
```
lib_2/async/stream_state_nonzero_timer_test Pass (expected Crash)
```
are failing on configurations
```
dartkb-abi-linux-release-x64
```

This test is flaky.

log: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8877650167666169536/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.
