### ISSUE TITLE
No error in analyzer when static private variable is accessed

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42338]
```dart
// file lib.dart
library lib;
class C {
  static String _s = "";
}

// file test.dart
import 'lib.dart'
main() {
  C._s = "Lily was here";
}
```
The code above produces no issues in analyzer. In VM it is an error
```dart
test.dart: Error: Setter not found: '_s'.
C._s = "Lily was here";
  ^^
```
There must be an error in analyzer as well. Please note, that this issue exists for static variables only. Attempt to call private static function results in an error in analyzer
`dartanalyzer version 2.9.0-15.0.dev`

**Comment by srawlins** [comment]
The analyzer now reports the following diagnostic:

> error • The setter '_s' is private and can't be accessed outside of the library that declares it. • b.dart:4:5 • private_setter
