### ISSUE TITLE
dart analyzer

### ISSUE THREAD

**Issue by samire24** [dart-lang/sdk#42333]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.8.2`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.2, server version 1.27.4, FATAL error:
```

For additional log information, please append the contents of
file://C:\Users\Highrate\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment]
Thanks for filing this issue, but please include the attached stack trace or log file when sending feedback.
