### ISSUE TITLE
New `dart` command should support experiment flags

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#42339]
The new `dart` tool should support `--enable-experiment` flags (needed e.g. for null safety preview)

**Comment by bkonyi** [comment]
Work in the VM is done](https://dart-review.googlesource.com/c/sdk/+/151890). Let me know if you need anything else @jwren.

**Comment by jwren** [comment]
Thank you @bkonyi, I will work on getting the change into `dartdev` tomorrow.

**Comment by jwren** [comment]
I started this work, but it will take more time than I originally thought. For each sub-command, we'll need to reach out to each owner to either allow an API to enable the experiments or to receive the flag and enable the specified experiment:

- [ ] analyze - ignored
- [ ] create - ignored
- [ ] format - "Could not find an option named "enable-experiment"."
- [ ] migrate - command current ignored
- [ ] pub - exception, unknown flag
- [ ] run - ignored
- [ ] test - "Could not find an option named "enable-experiment"."

**Comment by mit-mit** [comment]
`run` seems to work for me:


```
$ dart run
../test_pkg/lib/test_pkg.dart:5:4: Error: This requires the 'non-nullable' language feature to be enabled.
Try updating your pubspec.yaml to set the minimum SDK constraint to 2.9 or higher, and running 'pub get'.
int? nullableBar() {
   ^

$ dart run --enable-experiment=non-nullable
Hello: null, 42, null, 42, null, -1.

```

**Comment by mit-mit** [comment]
While we need the flags working generally, for here and now (i.e. for null safety) I would prioritize getting `test` & `pub (run)` working; they and run are the most important.

`analyze` works indirectly via the flag in `analysis-options.yaml`.

`create` & `format` doesn't do anything wrt. null safety.

`migrate` is run prior to null safety being there.

**Comment by devoncarew** [comment]
@jwren - I took a stab at some of this in https://dart-review.googlesource.com/c/sdk/+/152960; the technique I'm using won't need modification of the underlying tools (hopefully, just adopting their wrapper commands).

**Comment by devoncarew** [comment]
I think we can move this out of the `P1` category - all the critical commands support '--enable-experiment' now. `analyze` does not, but people can enable analysis experiments via the analysis-options.yaml file.

**Comment by mit-mit** [comment]
> I think we can move this out of the P1 category 

sgtm!

**Comment by devoncarew** [comment]
I'm going to close this as assumed complete; please re-open (or file more specific issues) if there is remaining work to do.
