### ISSUE TITLE
[CP] Please merge 8d4d3a33adcf579babfc1f2fd628768d481ac96c into stable/beta/dev

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#42342]
commit(s) to merge: 8d4d3a33adcf579babfc1f2fd628768d481ac96c

merge instructions: Should merge without conflicts

reason: All builds are broken due to the tag being pointed to in the DEPS file having multiple hashes with that tag. CIPD does not support removing tags or uploads, so this commit pins to a working hash instead.

cause: https://github.com/dart-lang/sdk/issues/42349

@athomas @whesse @franklinyow

**Comment by athomas** [comment]
We won't be able to reliably make builds on the release branches until this is merged in. For dev, we might pickup the change in tomorrow's release, anyway.

**Comment by franklinyow** [comment]
@dcharkes 
Is there a original issue? Need more information on why all build is broken

**Comment by franklinyow** [comment]
removing merge-to-dev

**Comment by franklinyow** [comment]
So both beta, and stable has this problem?

**Comment by athomas** [comment]
Yes, this is an infrastructure issue that wasn't introduced by a commit. This is rather different from other cherry-picks.

**Comment by franklinyow** [comment]
Let's hold on this one since this is an infrastructure issue, and has no user impact.

**Comment by athomas** [comment]
Ok, the cleanup mentioned in the linked issue worked, today's dev release built without problems. Most likely, we won't need this CP.
