### ISSUE TITLE
`dart migrate` should depend on `dart pub`, not `pub.bat`

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#42343]
Currently `dart migrate` tries to invoke `pub.bat`:

```
C:\Users\mit\tmp\foobar>dart migrate
CreateProcessW failed 2
ProcessException: The system cannot find the file specified.

  Command: "C:\Program Files\Dart\dart-sdk\bin\pub.bat" outdated --mode=null-safety --json
```

Also, it refers to `pub.bat` in it's user facing output:
https://github.com/dart-lang/sdk/blob/master/pkg/nnbd_migration/lib/migration_cli.dart#L159

This is not a good idead for Flutter users who are using the embedded Dart SDK. They will have the `flutter` and `dart` commands in path, but no `pub` command. It would be better to depend on, and direct users towards, using the `dart pub` command, which they will have available.

**Comment by srawlins** [comment]
Is the `dart` command on windows something like `dart.exe`?

**Comment by mit-mit** [comment]
No, they are bat scripts:
https://github.com/flutter/flutter/tree/master/bin

However, on Windows `.exe` and `.bat` extensions are recognized and expanded, so you can just type `dart` (for `dart.bat`) or `notepad` (for `notepad.exe`).

**Comment by mit-mit** [comment]
For technical details, see "PATHEXT" under Remarks in this article:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start
