### ISSUE TITLE
[vm/ffi] Optimize ffi calls with multiple Dart_Handle arguments

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#42341]
FfiCall.Handlex01(RunTime): 347.8671304347826 us.
FfiCall.Handlex02(RunTime): 384.86376755820663 us.
FfiCall.Handlex04(RunTime): 492.896007885658 us.
FfiCall.Handlex10(RunTime): 846.1214043993232 us.
FfiCall.Handlex20(RunTime): 1193.412291169451 us.

We currently call into C for every handle with

https://github.com/dart-lang/sdk/blob/755686e5b21665c239f4207116fc5976d7b493ee/runtime/vm/compiler/frontend/kernel_to_il.cc#L2750-L2764

https://github.com/dart-lang/sdk/blob/755686e5b21665c239f4207116fc5976d7b493ee/runtime/vm/runtime_entry.cc#L3559-L3570

Instead, we can extend the EnterHandleScope with an int how many handles we want, and do some integer arithmetic in IL to compute the addresses of those handles. (Up to the number of handles that fit into one single block.)

https://github.com/dart-lang/sdk/blob/755686e5b21665c239f4207116fc5976d7b493ee/runtime/vm/compiler/frontend/kernel_to_il.cc#L2731-L2736

**Comment by dcharkes** [comment]
When using a lot of handles, the old `native` calls are faster (AOT).

```
NativeCall.Handlex01(RunTime): 735.7863184994483 us.
NativeCall.Handlex20(RunTime): 836.6783772480134 us.

FfiCall.Handlex01(RunTime): 357.4213724088635 us.
FfiCall.Handlex20(RunTime): 1152.427995391705 us.
```

source: https://dart-review.googlesource.com/c/sdk/+/218920

@cskau-g What is the distribution of the number of handle arguments in the `dart:ui` conversion from `native`s to `dart:ffi`?

If we have a lot of calls with many handles, we should address this issue.

Related PR (pre-work for `dart:ui` conversion):

* https://github.com/flutter/engine/pull/29405

**Comment by cskau-g** [comment]
> What is the distribution of the number of handle arguments in the `dart:ui` conversion from `native`s to `dart:ffi`?

Quickly ran the numbers for the 169 APIs I've had a look at and see:
- 71 interfaces taking and returning no Handles at all (potential leaf calls).
- 91 interfaces taking 0 Handles among their parameters.
- 36 interfaces taking 1 Handle ...
- 27 interfaces taking 2 Handles ...
- 8 interfaces taking 3 Handles ...
- a few rare interfaces taking more (up to a maximum of 15) Handles ...

So I imagine optimising for lots of handles won't have a measurable impact on `dart:ui` in practice.

**Comment by mkustermann** [comment]
The handles for arguments are now allocated efficiently on the stack (see https://github.com/dart-lang/sdk/commit/4258a597893ec9e6434aa5d0557c24343a5e238d). Further work about Enter/Exit scope is tracked at https://github.com/dart-lang/sdk/issues/48989
