### ISSUE TITLE
CIPD package duplicate-tag causes builds to fail.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#42349]
**Impact**: All builds were broken.

**Cause**: Accidentally uploading a CIPD package with the same `version`-tag as that was already uploaded. This causes `gclient sync` during builds to fail due to ambiguity in resolving.

**Fix**: CIPD does not support removing uploads, nor removing tags. So the only fix is a fix-forward fix in which we update the DEPS file to something that is not ambiguous. The fix landed in master in https://github.com/dart-lang/sdk/commit/8d4d3a33adcf579babfc1f2fd628768d481ac96c. stable/beta require cherry picking [CP request](https://github.com/dart-lang/sdk/issues/42342), dev requires rolling.

(Making old builds reproducible can only be done by asking chrome infra to manually delete the upload or tag, and manually purging the CIPD package manager locally. See https://crbug.com/1094879.)

**Background**: We use the CIPD package manager to "check in" large files to the repository. `gclient sync` pulls in packages (with these larger files). The DEPS file specifies which version of a package should be pulled in. `gclient` caches packages locally, just deleting the bad upload will still keep everything in a broken state.

Having duplicate tags on CIPD package uploads is a CIPD-feature, some teams have workflows which use this. Dart does not.

**Mitigation**: Use hashes instead of version tags for this specific CIPD package, landed in d87046342fc3f78b86a1631579c9b793b6ea1280.

Further mitigation to consider, prefer using version hashes always over tags, but that also makes the DEPS file harder to read.

@franklinyow @athomas

**Comment by dcharkes** [comment]
Commit has landed with fix-forward, and the bad tag has been removed which fixes old build reproducibility (when locally purging the cipd cache).

**Comment by athomas** [comment]
The cherry-pick was not needed, because the removal of the duplicate tag was sufficient to be able to do a dev release (and there is no reason to believe it would fail for beta or stable).

I reached out to the Luci team, and the current recommendation is to use instance ids. There is, however, a plan to improve this in Q3.
