### ISSUE TITLE
[Triple shift] No error in analyzer if user-defined >>> operator has not one parameter

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42353]
According to the Dart Language specification (10.1.1 Operators)

> It is a compile-time error if the arity of a user-declared operator with
> one of the names: ‘<’, ‘>’, ‘<=’, ‘>=’, ‘==’, ‘-’, ‘+’, ‘~/’, ‘/’, ‘*’, ‘%’, ‘|’, ‘ˆ’,
> ‘&’, ‘<<’, ‘>>’, ‘>>>’, ‘[]’ is not 1

But the following code produces no issues in analyzer with `--enable-experiment=triple-shift` option
```dart
class C {
  operator >>>(var val, var val2) {}
}

main() {
  new C() >>> new C();
}
```
VM produces an error here `Error: Operator '>>>' should have exactly one parameter.`

`Dart VM version: 2.9.0-15.0.dev (dev) (Thu Jun 11 10:03:39 2020 +0200)`

**Comment by lrhn** [comment]
I just wrote a test for that today too, and found the same discrepancy. It also doesn't complain on zero arguments, `operator >>>() {...}`.
