### ISSUE TITLE
Analyzer fails to report an error when key in a constant map overrides operator ==

### ISSUE THREAD

**Issue by spkersten** [dart-lang/sdk#42356]
In the following code:

```dart
void main() {
  final foo1 = Bar({const Foo(): ""});  // 1
  final foo2 = const Bar({Foo(): ""});  // 2
}

class Foo {
  const Foo();
  
  bool operator==(dynamic other) => false;
  
  int get hashCode => 1;
}

class Bar {
  const Bar(Map<Foo, String> x);
}
```

I get a warning for the `foo1`: 

> info: Prefer const with constant constructors. (prefer_const_constructors ... 

But, with `const` at `foo2`, there is an error:

> Error compiling to JavaScript:
> main.dart:4:22:
> Error: Constant evaluation error:
>   final foo2 = const Bar({Foo(): ""});
>                      ^
> main.dart:4:27:
> Info: The key 'Foo {}' does not have a primitive operator '=='.
>  - 'Foo' is from 'main.dart'.
>   final foo2 = const Bar({Foo(): ""});
>                           ^
> Error: Compilation failed.

Dart 2.7.0

**Comment by bwilkerson** [comment]
Thanks!

@scheglov Looks like analyzer is failing to report an error.

**Comment by mraleph** [comment]
@bwilkerson I took a liberty to rename the issue to reflect the actual bug - previous title confused me (that's why I moved it to linter).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/151623
