### ISSUE TITLE
modular test suite does not support package_config.json

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#42367]
While trying to opt in package:js to nnbd, and add packages to the allow list, I got a failure on the  [tests/modular/js_interop](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8877297936444534768/+/steps/test_results/0/logs/new_test_failures__logs_/0) test. It looks like the modular test infrastructure depends heavily on the old .packages format and does not support package_config.json at all.

My plan for now is to accept this failure, as it cannot be resolved until support for that exists, and we don't want to block on that.

I don't know what area to assign this to, so assigning to @sigmundch who I believe is the most familiar with the internals of this. It looks like it needs a pretty big overhaul though.

**Comment by leafpetersen** [comment]
cc @nshahan @joshualitt @rakudrama

**Comment by sigmundch** [comment]
Thanks Jake - bypassing the failure is perfect for now.

@joshualitt did a short term fix for dart2js's modular tests (https://dart-review.googlesource.com/c/sdk/+/152361), we will properly integrate this into the modular framework, but meanwhile it may be worth looking at a similar workaround in ddc's modular tests.

**Comment by leafpetersen** [comment]
Is this fixed?  If not, is it a blocker for beta or can it slip?

**Comment by sigmundch** [comment]
We have a good enough workaround yes so the suites support package_config.json at this time. Eventually we should clean up how that's done, so that the modular_test framework does the work instead of the individual suites.
