### ISSUE TITLE
Failures on [Core Libraries] Eliminate the fork in the core libraries.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42365]
cc @johnniwinther @joshualitt @rakudrama 

There are new test failures on [[Core Libraries] Eliminate the fork in the core libraries.](https://dart-review.googlesource.com/c/sdk/+/151121).

The tests
```
pkg/compiler/test/end_to_end/no_platform_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-no-sdk-linux
unittest-weak-asserts-no-sdk-linux
```

**Comment by sigmundch** [comment]
@joshualitt fixed this in fd1556c1e4a0804c56a655d2f2799e2c08540c70
