### ISSUE TITLE
No error in CFE for wrong override of Object.==

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42377]
The following code produces an error in analyzer and no issues in VM
```dart
class C {
  bool operator ==(C val) => true; // Analyzer error - 'C.==' ('bool Function(C)') isn't a valid override of 'Object.==' ('bool Function(Object)').
}

main() {
  new C();
}
```
There must be an error in CFE as well

`Dart VM version: 2.9.0-16.0.dev (dev) (Tue Jun 16 10:35:10 2020 +0200) on "windows_x64"`

**Comment by johnniwinther** [comment]
Related to #42199

**Comment by leafpetersen** [comment]
I believe this is fixed?

**Comment by sgrekhov** [comment]
Yes this is fixed. Retested on `Dart SDK version: 2.10.0-79.0.dev (dev) (Mon Aug 31 17:07:47 2020 -0700) on "windows_x64"`. There are expected error in both analyzer and VM
