### ISSUE TITLE
Migration tool insert unnecessary cast with FutureOr<FutureOr<X>>

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#42376]
With the following code:

```dart
import 'dart:async';

FutureOr<FutureOr<int>> m() => 1;

main() async {
  final FutureOr<int> v = await m();
}
```

the migration tool suggests:

```dart
import 'dart:async';

FutureOr<FutureOr<int > >  m() => 1;

main() async {
  final FutureOr<int >  v = await (m() as FutureOr<int>);
}
```

but the `as FutureOr<int>` shouldn't be added and the migrated code should be:

```dart
import 'dart:async';

FutureOr<FutureOr<int>> m() => 1;

main() async {
  final FutureOr<int> v = await m();
}
```

**Comment by stereotype441** [comment]
I'm having trouble imagining why anyone would want to write the type `FutureOr<FutureOr<int>>` in real-world code (it's equivalent to `FutureOr<int>`, right?)  Did this come up in some code you were migrating?

**Comment by a14n** [comment]
See https://github.com/flutter/flutter/blob/37cb7b7b48c2257e0f90f01ba0ebc8a8d5378d55/packages/flutter/lib/src/foundation/_isolates_io.dart#L85

**Comment by stereotype441** [comment]
To clarify (since I got confused): in @a14n's example code posted above, the type `FutureOr<FutureOr<...>>` arises since the parameter `_IsolateConfiguration<Q, FutureOr<R>> configuration` substitutes `FutureOr<R>` for `R` in the `_IsolateConfiguration` class; as a result, the substituted return type of `Configuration.apply` is `FutureOr<FutureOr<R>>`.

**Comment by stereotype441** [comment]
Changing priority back to P3 since this did arise in real world code

**Comment by stereotype441** [comment]
Unassigning myself because I'm not actively working on the migration tool right now.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
