### ISSUE TITLE
Fail to run "run_offsets_extractor.sh"

### ISSUE THREAD

**Issue by wqyfavor** [dart-lang/sdk#42372]
My computer is MacbookPro. I followed this doc to build dart and succeeded. https://github.com/dart-lang/sdk/wiki/Building

But I fail to run "./tools/run_offsets_extractor.sh". The error shows there is no "mac-x86" related library files in buildtools.

I checked buildtools directory there is only mac-x64 related library files.
I do not think we need 32bit executable but why this script is building such kind of executable.

<img width="921" alt="截屏2020-06-17 19 05 22" src="https://user-images.githubusercontent.com/113776/84890842-838c0f80-b0cd-11ea-995e-7dbc5e95dbe8.png">

**Comment by wqyfavor** [comment]
@victoragnez I check the commit record of 'run_offsets_extractor.h'. Could you please help solving this problem?

**Comment by mraleph** [comment]
You need to use an operating system that allows building 32-bit executables (e.g. Linux) to be able to run `./tools/run_offsets_extractor.sh`. This is currently working as intended.
