### ISSUE TITLE
Migrate packages needed by the benchmarks

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#42395]
The benchmarks use these packages. These need to be migrated and rolled into the SDK DEPS to complete the benchmark migration:

- [x] async
- [X] benchmark_harness
- [x] box2d (this is "vendored" in some benchmarks)
- [ ] compiler
- [x] convert
- [x] crypto
- [x] csslib
- [x] ffi
- [x] fixnum
- [ ] intl
- [x] js
- [x] meta
- [x] pedantic
- [x] unittest (vendored in a single benchmark, will not be migrated, benchmarks need to stop using this)
- [x] vector_math (this is "vendored" in some benchmarks)
- [ ] vm_service

**Comment by athomas** [comment]
Note: migrated packages will have languageVersion `2.9` in https://github.com/dart-lang/sdk/blob/master/.dart_tool/package_config.json.

**Comment by kevmoo** [comment]
`unittest` is dead. 
Do we really need box2d here? Could we use something else? That's going to be a bear, I think!

**Comment by athomas** [comment]
Only a single benchmark `DependencyInjection` depended on `unittest` (and that benchmark is also broken). I left a note on go/dart-null-safety-package-migration-tracking and marked it as complete in the list above.

**Comment by athomas** [comment]
`box2d` benchmarks are currently working (they actually benchmark `box2d` but some or all seem to be using a specific pinned version which is not going to work for the migration). So either we delete them or we migrate `box2d`.

**Comment by kevmoo** [comment]
On Fri, Jun 19, 2020 at 12:31 AM Alexander Thomas <notifications@github.com>
wrote:

> box2d benchmarks are currently working (they actually benchmark box2d but
> some or all seem to be using a specific pinned version which is not going
> to work for the migration). So either we delete them or we migrate box2d.
>
Okay...

**Comment by mraleph** [comment]
Box2D is a very good example of good sized computationally heavy code. We sadly don't have any other examples like that in our benchmark corpus. Rive engine is another good example - but that's Flutter dependent. 

So I think we should make an effort and port Box2D to null safety.

**Comment by athomas** [comment]
I've gone through all benchmarks and added a "Dependencies" column to go/dart-nnbd-benchmark-migration. Note that some the packages in my original list are forked in the benchmark.

**Comment by whesse** [comment]
Box2D has a third-party branch by Flame at https://github.com/flame-engine/box2d.dart/.
They have added fixes, lint cleanup, and interop with their framework on top of the google version of box2d.
If it is for internal benchmarking use, and vendored, we could use that.  Don't know if we want to duplicate all their work.

**Comment by leafpetersen** [comment]
cc @natebosch @jakemac53 @lrhn

**Comment by crelier** [comment]
I looked at our 3 variants of box2d benchmarks. I came to the same conclusion as athomas@: they are redundant, each one being pinned to a different state of box2d in time.

It would make sense to keep only one of them and free some golem resources.

I was able to update our Box2DOctane benchmark to run on the current version of Flame's box2d at https://github.com/flame-engine/box2d.dart/ pointed to by whesse@.

Now, the analyzer still reports 2377 lints for this box2d version prior to a NNBD migration. I suppose we could ignore these lints and just perform a migration, possibly an automated one using the migration tool.
I actually gave it a try, but immediately got a NoSuchMethodError in the tool. It may be user error. I'll follow up offline.

Flame's box2d is a branch of google's box2d (pub.dartlang.org/packages/box2d). It should not be a problem to "vendor" (and migrate) this version in the internal benchmarks repo.

What do you think? Should I give it a try?

**Comment by whesse** [comment]
Since the third-party box2d is being maintained and used, I think we should anticipate that it will need to be migrated to null safety.
In that case, if we migrate it, we should offer the migrated version back to the open-source project we are forking it from.
Then the only question is whether it is worth our migrating - I think it probably is, it is good benchmark code and people use this sort of code in game engines.

**Comment by natebosch** [comment]
Are any of the existing 3 variants the version from `flame-engine` or is that a 4th variant?

**Comment by crelier** [comment]
None of the 3 are currently using the version from `flame-engine`, but a version by Google on github frozen at different points in time. `flame-engine` forked that unmaintained version some time ago and improved it. I updated one of the 3 benchmarks (`Box2DOctane`) to use the current `flame-engine` version. It is fairly easy to do. My plan is to migrate `flame-engine`'s `Box2D` to NNBD and to check in that migrated version with `Box2DOctane` and to delete the other 2 redundant benchmarks. It is better for our benchmarks to be stable and self-contained, and not to directly depend on `flame-engine` modifying their packages.

**Comment by natebosch** [comment]
> They have added fixes, lint cleanup, and interop with their framework on top of the google version of box2d.



> It is better for our benchmarks to be stable and self-contained, and not to directly depend on `flame-engine` modifying their packages.


Are there any conflicts between these? Does the "interop with their framework" imply any dependency on their other code?

I'm wondering whether starting from the latest version in the google repo and doing our own fixes from there will be a smoother path.

In any case, I think it would be much better to get everything migrated to a consistent single copy _first_, and then migrating that single copy to null safety. Mixing both migrations will make things more confusing.

**Comment by crelier** [comment]
I think the idea was to drop Google's version altogether, since it has not been maintained in ages.

**Comment by crelier** [comment]
See the separate email thread about the migration of `Box2DOctane` benchmark using a mostly automated migration of Flame's box2d package (non-public repo).

**Comment by natebosch** [comment]
I think these packages also all need to be in the allow list for the experiment.

**Comment by mit-mit** [comment]
@athomas what's the plan for getting the three remaining listed packages (vm_service, intl, vm_service) migrated to null safety? Is your team doing that, or are you expecting someone else to do that?

**Comment by athomas** [comment]
@mit-mit We have almost all benchmarks and their dependencies migrated, so I will close this issue.

The compiler, vm_service and intl packages (intl has been migrated internally, and will soon be available) will have to be migrated by their respective teams and that should be tracked elsewhere. This may take awhile, especially for compiler.
