### ISSUE TITLE
Null safety: incorrect error and warning on this in extension

### ISSUE THREAD

**Issue by spkersten** [dart-lang/sdk#42396]
I would expect this code to work:

```dart
extension W<T> on T? {
  R? map<R>(R Function(T) f) => this != null ? f(this) : null; // 2
}

void main() {
  final int? y = 6;
  
  print(y.map((q) => 2*q)); // 8
}
```

Yet, line 1 generates a warning: `The argument type 'T?' can't be assigned to the parameter type 'T' - line 2`
And line 8 an error:
```
Error compiling to JavaScript:
/tmp/dartpadETAATW/main.dart:8:24: Error: A value of type 'int?' can't be assigned to a variable of type 'num'.
  print(y.map((q) => 2*q));
```

Tested on https://nullsafety.dartpad.dev
Based on Dart SDK 2.9.0-edge.2ed302bfbbbad1d10f6c839c504ae3871fc96dc2

**Comment by leafpetersen** [comment]
We don't currently support promotion of `this`.  There's no fundamental reason that I know of, it's just a pre-existing limitation that's been around since Dart 1.  We discussed fixing this in the null safety release but couldn't fit it in.  The common workaround currently is to do:

```
  var self = this;
  return if (self != null) ? f(self) : null;
```
