### ISSUE TITLE
DDC does not correctly check types in late setters

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42407]
The migrated test language/this/as_covariant_call_checks_test.dart fails on DDC. On [the code review](https://dart-review.googlesource.com/c/sdk/+/151625/1..2), @nshahan says:

> This is interesting. After looking at the DDC failure I see that there is a problem with type checking in the setters for late fields. 

I couldn't find an issue to track that, so filing this one. I'll approve the failure and link to this.

**Comment by nshahan** [comment]
@johnniwinther

I was inspecting the front end output and it looks like the setter for late fields with a TypeParameterType are not getting the flag `isGenericCovariantImpl` set. That missing flag is causing ddc to skip outputting a type check for the setter parameter. You can observe the difference when you compile these two classes:

```dart
class A<T> {
  late T x;
}

class B<T> {
  T? _y;
  set y(T? val) {
    _y = val;
  }
}
```

```
class A<T extends core::Object? = dynamic> extends core::Object {
  field tes::A::T? _#A#x = null;
  field core::bool _#A#x#isSet = false;
  synthetic constructor •() → tes::A<tes::A::T%>
    : super core::Object::•()
    ;
  get x() → tes::A::T%
    return this.{tes::A::_#A#x#isSet} ?{tes::A::T%} let final tes::A::T? #t1 = this.{tes::A::_#A#x} in #t1{tes::A::T%} : throw new _in::LateInitializationErrorImpl::•("Field 'x' has not been initialized.");
  set x(tes::A::T% #t2) → void {
    this.{tes::A::_#A#x#isSet} = true;
    this.{tes::A::_#A#x} = #t2;
  }
}
class B<T extends core::Object? = dynamic> extends core::Object {
  field tes::B::T? _y = null;
  synthetic constructor •() → tes::B<tes::B::T%>
    : super core::Object::•()
    ;
  set y(generic-covariant-impl tes::B::T? val) → void {
    this.{tes::B::_y} = val;
  }
}
```

**Comment by johnniwinther** [comment]
The flag is set by the CFE but overridden by the `_CovarianceTransformer`.

I've added the test in https://dart-review.googlesource.com/c/sdk/+/151821 and you can see the CFE output in https://dart-review.googlesource.com/c/sdk/+/151821/1/pkg/front_end/testcases/late_lowering/issue42407.dart.strong.expect

**Comment by nshahan** [comment]
Thanks, I'll look more into our `_CovarianceTransformer` to see if I can fix it there. I left a comment in the example you linked but it looks like it is still missing the flag on the type of the parameter in the setter.

**Comment by johnniwinther** [comment]
A CL is cooking for setting the setter parameter, maybe it'll fix the DDC issue: https://dart-review.googlesource.com/c/sdk/+/151842

**Comment by johnniwinther** [comment]
The CL fixes the issue for DDC.
