### ISSUE TITLE
Unsound unboxing optimization in AOT

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#42418]
The unboxing optimization for AOT partitions methods into groups such that any two methods that can potentially be called from the same call site are in the same group. Unboxing decisions are then taken on a group-by-group basis.

This is done by a union-find computation where two methods are united if one overrides the other. This algorithm fails to unite methods in cases where they are both inherited by a third class that does not override them.

Example:
```dart
import 'dart:math';

class A {
  @pragma("vm:never-inline")
  void foo(int x) {
    print(x);
  }
}

class B {
  @pragma("vm:never-inline")
  void foo(int x) {
    print(x);
  }
}

class C extends A implements B {}

main() {
  Random r = Random();
  new A().foo(r.nextInt(10));
  new B().foo(r.nextInt(10));
  new A().foo(null);
  List<B> l = [new B(), new C()];
  for (B b in l) {
    b.foo(4);
  }
}
```
The AOT compiler will unbox the parameter to `B.foo()`, but not the one to `A.foo()` (since it can be `null`). As a result, the program prints `2` instead of `4` as the last printed value. If the argument to `b.foo(4)` is odd, it will segfault, due to interpreting the value as an object reference. If `new A().foo(null);` is replaced by `new B().foo(null);`, the last value will be doubled instead of halved.

One way to fix this is for the CFE to insert [signature stubs](https://github.com/dart-lang/sdk/issues/40412), since this will make the union-find computation, as written, correctly group methods that may be called via the same call site.

**Comment by alexmarkov** [comment]
Another option is to group all methods for each _interface_ member and its implementation in every class. In this case class C should contain `B.foo()` in its interface and `A.foo()` is the corresponding implementation. Maybe we can even use `ClassHierarchy.forEachOverridePair` for that purpose.

**Comment by askeksa-google** [comment]
`ClassHierarchy.forEachOverridePair` reports no overrides for `foo` in this example. Signature stubs will change that, since a signature stub will be inserted in `C`, overriding the implementations in `A` and `B`.

**Comment by alexmarkov** [comment]
Yeah, out of the box `ClassHierarchy.forEachOverridePair` doesn't work. We might need a slightly modified version which would use `_buildImplementedMembers` instead of `_buildDeclaredMembers`.

A slightly less efficient version which would report all corresponding interface-implementation pairs but uses only public `ClassHierarchy` API:

```dart
void forEachOverridePair(ClassHierarchy hierarchy, Class class_,
    callback(Member implementationMember, Member interfaceMember)) {
  for (var supertype in class_.supers) {
    var superclass = supertype.classNode;

    reportOverrides(List<Member> interfaceMembers, bool isSetter) {
      for (var intf in interfaceMembers) {
        var impl = hierarchy.getDispatchTarget(class_, intf.name, setter: isSetter);
        if (!identical(intf, impl)) {
          callback(impl, intf);
        }
      }
    }

    reportOverrides(hierarchy.getInterfaceMembers(superclass), false);
    reportOverrides(hierarchy.getInterfaceMembers(superclass, setters: true), true);
  }
}
```

This implementation doesn't need any stubs inserted by the front-end.
