### ISSUE TITLE
Analyzer throws error when declare a correctly super bounded variable

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42415]
Dart VM version: 2.9.0-16.0.dev (dev) (Tue Jun 16 10:35:10 2020 +0200) on "windows_x64"

This issue is similar with #36959, however now it's reproducible with a variable if a class (not alias only).

Here is a source code example:
``` dart
class A<T extends A<T>> {}

main() {
  A<dynamic> a1;
  A<Object?> a2;
  A<Object>  a3;
  A<void>    a4;
  A<Never>   a5;

  A<A<dynamic>> a6;
  A<A<Object?>> a7;
  A<A<Object>>  a8;
  A<A<void>>    a9;
  A<A<Never>>   a10;
}
```
Dart passes with this whereas analyzer throws errors for `a2`, `a3`, `a4`, `a7`, `a8`, `a9`. 

It seems like analyzer should not throw exceptions here, or at least both tools should behave in the same way.

Sample output is:
$> dart --enable-experiment=non-nullable test.dart 

$> dartanalyzer --enable-experiment=non-nullable test.dart 

> Analyzing class_A01_t01.dart...
>   error - 'Object?' doesn't extend 'A<Object?>'. - class_A01_t01.dart:21:5 - type_argument_not_matching_bounds
>   error - 'void' doesn't extend 'A<void>'. - class_A01_t01.dart:22:5 - type_argument_not_matching_bounds
>   error - 'A<Object?>' doesn't extend 'A<A<Object?>>'. - class_A01_t01.dart:26:5 - type_argument_not_matching_bounds
>   error - 'Object?' doesn't extend 'A<Object?>'. - class_A01_t01.dart:26:7 - type_argument_not_matching_bounds
>   error - 'A<void>' doesn't extend 'A<A<void>>'. - class_A01_t01.dart:27:5 - type_argument_not_matching_bounds
>   error - 'void' doesn't extend 'A<void>'. - class_A01_t01.dart:27:7 - type_argument_not_matching_bounds
>   hint - The value of the local variable 'a1' isn't used. - class_A01_t01.dart:18:5 - unused_local_variable
>   hint - The value of the local variable 'a2' isn't used. - class_A01_t01.dart:20:14 - unused_local_variable
>   hint - The value of the local variable 'a3' isn't used. - class_A01_t01.dart:21:14 - unused_local_variable
>   hint - The value of the local variable 'a4' isn't used. - class_A01_t01.dart:22:11 - unused_local_variable
>   hint - The value of the local variable 'a5' isn't used. - class_A01_t01.dart:23:12 - unused_local_variable
>   hint - The value of the local variable 'a6' isn't used. - class_A01_t01.dart:25:17 - unused_local_variable
>   hint - The value of the local variable 'a7' isn't used. - class_A01_t01.dart:26:17 - unused_local_variable
>   hint - The value of the local variable 'a8' isn't used. - class_A01_t01.dart:27:14 - unused_local_variable
>   hint - The value of the local variable 'a9' isn't used. - class_A01_t01.dart:28:15 - unused_local_variable
>   hint - The value of the local variable 'a10' isn't used. - class_A01_t01.dart:30:8 - unused_local_variable
>   hint - The value of the local variable 'a11' isn't used. - class_A01_t01.dart:31:11 - unused_local_variable
> 6 errors and 11 hints found.

The same is true for `is` and `as` constructions, for example the following example fails in the similar way:
``` dart
class A<T extends A<T>> {}

main() {
  bool b1 = 1 is A<Object?>;
  bool b2 = 1 is A<void>;

  var o1 = null as A<Object?>?;
  try { var o2 = null as A<void>; } catch(e) {}
}

```

**Comment by eernstg** [comment]
The declared type of `a3` and `a8` are errors, because `Object` is not a top type with null-safety enabled, but the types of `a2`, `a4`, `a7`, and `a9` are correctly super-bounded and should be accepted.

**Comment by scheglov** [comment]
With https://github.com/dart-lang/sdk/issues/42196 fixed, analyzer reports only `a3` and `a8` as errors.
So, I suppose that this issue is fixed as well.
