### ISSUE TITLE
AOT compiler looses track of list's type argument in the for-in loop

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#42413]
```dart
class B {
  get x => 0;
}

class A {
  var list;
  A() { list = <B>[B()]; }

  @pragma('vm:never-inline')
  void forIn() {
    for (var e in list)
      print(e.x);
  }

  @pragma('vm:never-inline')
  void cLoop() {
    for (var i = 0; i < list.length; i++) {
      final e = list[i];
      print(e.x);
    }
  }

}

void main() {
    A().forIn();
    A().cLoop();
}
```

In `cLoop` `e.x` will be inlined and in `forIn` `e.x` will be a dynamic call.

Most likely a TFA problem /cc @alexmarkov

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/151889 fixes the problem.

However, this improvement revealed bug https://github.com/dart-lang/sdk/issues/42423, which causes `co19_2/LanguageFeatures/Spread-collections/TypeInference_A01_t02` test to fail in AOT mode.
