### ISSUE TITLE
CONST_SET_ELEMENT_TYPE_IMPLEMENTS_EQUALS is checked for list element

### ISSUE THREAD

**Issue by Anushi1998** [dart-lang/sdk#42425]
The dart analyzer error code `CONST_SET_ELEMENT_TYPE_IMPLEMENTS_EQUALS` is misleading because it checks equal override for both lists & set elements. Or should the error be triggered only for set/map elements? 

**Sample Code**
```
const a = [1.0, 2.0];
const b = [3.0, ...a];
```

**Comment by lrhn** [comment]
It should only be an error for set literals. List literals do not care whether their elements implements `==`.

**Comment by Anushi1998** [comment]
@lrhn Dartpad is showing me error.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/16550254/85225396-7ed99b00-b3ee-11ea-8856-d7fbc1b94f37.png">

Version - 2.9.0-316591527  (Google internal)

Looks like problem is [here](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/constant/constant_verifier.dart#L828-L830).

**Comment by lrhn** [comment]
ACK, it's the spread. And yes, the lie you are pointing to could very well be the reason.

**Comment by Anushi1998** [comment]
So the fix should be trigger this only for the set? I could help with a fix :-)

**Comment by h65wang** [comment]
This actually has real-world use cases, for example, I cannot specify a const matrix using spread operators as such:

```
  static const filter = ColorFilter.matrix([
    ...[0.2126, 0.7152, 0.0722, 0, 0],
    ...[0.2126, 0.7152, 0.0722, 0, 0],
    ...[0.2126, 0.7152, 0.0722, 0, 0],
    ...[0, 0, 0, 0.4, 0],
  ]); // this code fails to compile
``` 
But if I don't use the spread operator, the array will be auto-formatted into a single column 🤣

**Comment by eernstg** [comment]
Considering the formatting part alone (that is, ignoring the actual topic of this issue for a moment ;-) you can use `//` to mark each desired line break:

```dart
class ColorFilter {
  const ColorFilter.matrix(_);
}

class A {
  static const filter = ColorFilter.matrix([
    0.2126, 0.7152, 0.0722, 0, 0, //
    0.2126, 0.7152, 0.0722, 0, 0, //
    0.2126, 0.7152, 0.0722, 0, 0, //
    0, 0, 0, 0.4, 0,
  ]);
}
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/211880
