### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by vishalrajbh** [dart-lang/sdk#42420]
## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.7.0-edge.16cbabec3a00e715173c68e8f761a8e1296cc9e5`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

**Comment by keertip** [comment]
@vishalrajbh , closing this issue there is no information listed for us to follow up. Do reopen if you have more info.
