### ISSUE TITLE
Unexpected compile error during the generic non-function type alias object creation

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42432]
Dart VM version: 2.9.0-17.0.dev (dev) (Thu Jun 18 10:22:39 2020 +0200) on "windows_x64"

The following source code example calls generic type alias constructor without type parameter specified:
``` dart
class C<T> {}
typedef CAlias<T extends num> = C<T>;

main() {
  CAlias ca1 = new CAlias();
  print(ca1 is C<num>);
}
```
Seems like dart should print `true`, however it throws a compile error instead.

Sample output is:
> $> dart --enable-experiment=nonfunction-type-aliases test.dart
> test.dart:5:20: Error: The constructor returns type 'C<dynamic>' that isn't of expected type 'C<num>'.
>  - 'C' is from 'test.dart'.
> Change the type of the object being constructed or the context in which it is used.
>   CAlias ca1 = new CAlias();
>                    ^

**Comment by alexmarkov** [comment]
Looks like a CFE issue. /cc @johnniwinther

**Comment by leafpetersen** [comment]
@eernstg is this still an issue?

**Comment by eernstg** [comment]
Closing: No, it prints true today, as it should.
