### ISSUE TITLE
NNBD: Unexpected unhandled exception during the generic contravariant function variable assigning 

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42433]
Dart VM version: 2.9.0-17.0.dev (dev) (Thu Jun 18 10:22:39 2020 +0200) on "windows_x64"

The following source code throws unexpected unhandled error when assign generic contravariant function variable:
``` dart
class X {}

checkme<T extends X>(T? t) {}
typedef Test<T extends X>(T? t);

main() {
  Test<X> t2 = checkme;
}
```
Sample output is:
> $> dart --enable-experiment=nonfunction-type-aliases,non-nullable test.dart
> Unhandled exception:
> type 'X?' is not a subtype of type 'X' of 'T'
> #0      _boundsCheckForPartialInstantiation (dart:_internal-patch/internal_patch.dart:146:57)
> #1      main (file:///D:/DART/sdk/tests/co19/src/Language/Generics/test.dart)
> #2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
> #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Please note that dart passes with covariant case, i.e. the following source example passes:
``` dart
class X {}

T? checkme<T extends X>() {}
typedef T? Test<T extends X>();

main() {
  Test<X> t2 = checkme;
}
```

**Comment by crelier** [comment]
The kernel file for the `bug.dart` source above looks as follows:

```
main = bug::main;
library from "file:///usr/local/google/home/regis/bug.dart" as bug {

  typedef Test<contravariant T extends bug::X = bug::X> = (T?) → dynamic;
  class X extends core::Object {
    synthetic constructor •() → bug::X
      : super core::Object::•()
      ;
  static method checkme<T extends bug::X
  } = bug::X>(bug::checkme::T? t) → dynamic {}
  static method main() → dynamic {
    (bug::X?) → dynamic t2 = #C1<bug::X?>;
  }
}
[...]

constants  {
  #C1 = tearoff bug::checkme
[...]
```
The inferred type argument `X?` used in the assignment of the tearoff does not seem correct.
At least, it explains the TypeError reported by the VM.
This looks like a CFE issue. /cc @johnniwinther

**Comment by johnniwinther** [comment]
Likely related to #41447
