### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by prakash-cr7** [dart-lang/sdk#42439]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.7.0-dev.2.1`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

**Comment by prakash-cr7** [comment]
I am not able to use flutter outline.

**Comment by keertip** [comment]
@prakash-cr7, can you add more details? Is the flutter outline view empty? What do you mean when you cannot use it?

**Comment by prakash-cr7** [comment]
well it shows empty screen on beginning but i found solution on stackoverflow. its working after pressing ctrl+enter.
