### ISSUE TITLE
Dart does not throw error if function type alias type parameter does not match bounds

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42436]
Dart VM version: 2.9.0-17.0.dev (dev) (Thu Jun 18 10:22:39 2020 +0200) on "windows_x64"

The following source code example passes with dart and throws a compile error with analyzer:
``` dart
class A<X extends int> {}
typedef AAlias<X extends String> = Function<Y extends A<X>> ();
main() {}
```
Seems like dart should throw a compile error here too.

Sample output is:
```
$> dart test.dart

$> dartanalyzer test.dart
Analyzing test.dart...
  error - 'X' doesn't extend 'int'. - test.dart:2:57 - type_argument_not_matching_bounds
1 error found.
```

**Comment by alexmarkov** [comment]
This is probably a front-end issue if compile-time error is missing.
/cc @johnniwinther @stefantsov

**Comment by johnniwinther** [comment]
Likely related to #41684

**Comment by eernstg** [comment]
Given that the example does not contain any non-function type aliases (only a regular type alias), I think this issue should be removed from the non-function type alias epic.

**Comment by leafpetersen** [comment]
@eernstg is this still an issue?  it's independent, but perhaps we should fix as part of this release?

**Comment by stefantsov** [comment]
This appears to be fixed some time ago.  This is what I see at the current HEAD.

```
$ xcodebuild/ReleaseX64/dart /tmp/asdf.dart
/tmp/asdf.dart:2:36: Error: Type argument 'X' doesn't conform to the bound 'int' of the type variable 'X' on 'A'.
Try changing type arguments so that they conform to the bounds.
typedef AAlias<X extends String> = Function<Y extends A<X>> ();
                                   ^
/tmp/asdf.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
class A<X extends int> {}
        ^
```

I'm closing the issue.  Feel free to re-open if needed.

**Comment by eernstg** [comment]
Thanks @stefantsov!
