### ISSUE TITLE
NNBD: Dart does not throw a compile error when declare a non-function typedef variable with unacceptable nullable type parameter

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42449]
Dart VM version: 2.9.0-18.0.dev (dev) (Mon Jun 22 16:07:30 2020 +0200) on "windows_x64"

The following source code example declares a `A<num?>` variable for `typedef A<X extends num>`
``` dart
class C<X> {}
typedef A<X extends num> = C<X?>;

main() {
  A<num?>? aaa = throw "Here is me";
}
```
`Num?` is not assignable to `num`, so compile error should be thrown here. However, dart does not throw it.

Sample output is:
> $> dart --enable-experiment=nonfunction-type-aliases,non-nullable test.dart
> Unhandled exception:
> Here is me
> #0      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Simple-bounds/static/type-aliases/test.dart:5:18)
> #1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
> #2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
>

**Comment by alexmarkov** [comment]
This looks like a front-end issue as there is a missing compile-time error.
/cc @johnniwinther

**Comment by johnniwinther** [comment]
Removing from NNBD since this requires `nonfunction-type-aliases`.

**Comment by leafpetersen** [comment]
@eernstg is this still an issue?

**Comment by eernstg** [comment]
Yes, the error message is still missing. The following variant avoids the throw (which helps avoid some potential confusion):

```dart
class C<X> {}
typedef A<X extends num> = C<X?>;

main() {
  A<num?>? aaa = null;
}
```

The following one _does_ report the error, so this issue is associated with non-function type aliases:

```dart
class C<X> {}
typedef A<X extends num> = C<X?> Function();

main() {
  A<num?>? aaa = null;
}
```

**Comment by johnniwinther** [comment]
@eernstg Are you looking into this or should someone from the CFE take over?

**Comment by eernstg** [comment]
I think it would be nice if someone else took over&mdash;I'm trying to get the 2.11 stable spec done, and that keeps getting pushed ahead for various reasons. ;)

**Comment by johnniwinther** [comment]
Sounds good.

**Comment by leafpetersen** [comment]
This now works.

**Comment by stefantsov** [comment]
The fix for this issue was reverted due to a crash in google3, but will be re-landed soon. The re-landing CL is here: https://dart-review.googlesource.com/c/sdk/+/193401.
