### ISSUE TITLE
Throw TypeError instead of NoSuchMethodError on `!`

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42443]
If I run this program:

```dart
main() {
  null!;
}
```

On the VM, it throws a TypeError (which is also a CastError). On DDC, it throws a NoSuchMethod Error. The language spec is agnostic as to the concrete error type, but I think it's good for our users if the implementations agree. Pragmatically, I'm trying to migrate some affected tests that validate the exception type being thrown, and I'd like them to check for a specific type and not consider the test to pass if any old error is thrown.

My preference is for `!` to always throw a TypeError. I don't think NoSuchMethodError makes much sense because the user hasn't actually tried to call a method. Unless I hear otherwise, I'll have the tests to look for TypeError and approve the DDC failure with a link to this issue.

cc @leafpetersen in case he has an opinion.

**Comment by rakudrama** [comment]
There is a similar issue open for dart2js: https://github.com/dart-lang/sdk/issues/39978

For optimized code on dart2js we reduce  `o!.foo()` to `o.foo()` and will be able to distinguish the TypeError from NoSuchMethodError only to the degree that information can be extracted from the JavaScript TypeError message string.

**Comment by leafpetersen** [comment]
My vague recollection (backed up somewhat by [this issue](https://github.com/dart-lang/language/issues/806)) is that we had agreed that dart2js would make NoSuchMethodError implement TypeError.
