### ISSUE TITLE
Package config setup changes broke some il serialization tests

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#42441]
After 03777dba313fe258ab1e51beaed9c305732ece11,

dartk-optcounter-linux-release-ia32
Timeout -> RuntimeError (expected Pass)
vm/dart_2/il_round_trip_deserialization_test/3

dartk-optcounter-linux-release-ia32
RuntimeError -> Timeout (expected Pass)
vm/dart_2/il_round_trip_deserialization_test/1

**Comment by a-siva** [comment]
This change was reverted in order to understand the above issues
