### ISSUE TITLE
Migrate package:dart_internal to null safety

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42440]
The "extract_type_arguments.dart" library in the weird "dart_internal" package is not null safe yet. The package is just a thin wrapper around the hidden "dart:_internal" library. That library *has* been correctly migrated. It's just the wrapper that has not. The only changes needed are turning a couple of `Object` return types to `Object?`.

The challenging part is that this package is versioned and published so figuring out when to release the migrated version may be difficult. I'll own this but I'm filing the issue to make sure it's visible.

cc @leafpetersen

**Comment by nshahan** [comment]
cc @davidmorgan 

I believe this package is now auto rolled into Google with the SDK so you might also be blocked by the internal support for a null safe package.

**Comment by leafpetersen** [comment]
cc @jakemac53

**Comment by davidmorgan** [comment]
Internal support is ready to go--please migrate as needed :)

**Comment by munificent** [comment]
Thanks! I'll try to get to this very soon.

**Comment by munificent** [comment]
[This patch](https://dart-review.googlesource.com/c/sdk/+/153021) migrates the package, but we can't land that yet. First, dart_internal needs to be in the allowlist and we need to get a dev release out that includes that change. [This patch](https://dart-review.googlesource.com/c/sdk/+/152987) adds the package to the allow list.

**Comment by nshahan** [comment]
Is the migration unblocked now?

**Comment by munificent** [comment]
I think so. I will try to please the bot lords today and land the migration.

**Comment by munificent** [comment]
Done: https://dart-review.googlesource.com/c/sdk/+/153021
