### ISSUE TITLE
Null safety feedback: [issue summary]

### ISSUE THREAD

**Issue by jose-airspace** [dart-lang/sdk#42445]
Null safety is huge! Can't wait for this feature, I played around with it and it looks really nice. Really brings dart in line with swift and eliminates one of the biggest causes of crashes

**Comment by jose-airspace** [comment]
Is there a target release date?

**Comment by keertip** [comment]
You can follow the announcements in the [Dart blog](https://medium.com/dartlang) or on our [website](https://dart.dev/community).
