### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by kamoliddin98uz** [dart-lang/sdk#42453]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.8.4`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

**Comment by keertip** [comment]
@kamoliddin98uz , there are no details attached to this issue that can be worked on, so closing. Feel free to open a new issue or reopen this one with more details.
