### ISSUE TITLE
Dart language tools should error if libraries and parts have inconsistent language versions

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42456]
Per spec:

> Part files **must** be marked with the same version as their library. They must always be treated the same way as the library they belong to, so it is a compile-time error if a part file has a different language version override than its library. It is also a compile-time error if a part file has no language version marker, and the importing library does, or vice versa. Tools that work on individual part files, like the formatter, need a marker in the part file. If there isn't one, the tool can assume that the default language version of the package applies.

There should be language tests here with implementations in our compilers (CFE) and analyzer.

CC @leafpetersen @lrhn

**Comment by kevmoo** [comment]
CC @scheglov @bwilkerson @devoncarew – It'd be nice to get this error into analyzer soonish.

Do you want to track it as a separate (child) issue?

**Comment by scheglov** [comment]
Analyzer implementation landed as 849cdb2ab40218585e235c87cf8ba43bac7011f0.

**Comment by franklinyow** [comment]
Anything left to do here?

**Comment by kevmoo** [comment]
I believe needs to do work here – this should be an error in the compliers, etc

**Comment by johnniwinther** [comment]
Is the needed work tests or implementation? As far as I know CFE has handled this for a long time, but maybe there is a case I'm missing.

**Comment by kevmoo** [comment]
If we have tests to validate this and they are passing, I guess we're good.
We can close it

**Comment by johnniwinther** [comment]
I don't think we have test, say, in the language folder that are shared between analyzer and CFE. 

CFE has it's own unittest-suite for language versioning.

**Comment by kevmoo** [comment]
Would it be good to have tests in the language folder?

Seems the type of thing we should validate across all impls – consistently, right?

**Comment by johnniwinther** [comment]
Yes. That's probably for the language team. @lrhn can you look into this?

**Comment by lrhn** [comment]
Will do.

**Comment by kevmoo** [comment]
Dropping priority to P2 since (we hope) everything is implemented correctly.

**Comment by franklinyow** [comment]
@kevmoo Is this something we still need to track for TP2?

**Comment by kevmoo** [comment]
Nope. For beta, certainly!

**Comment by leafpetersen** [comment]
@lrhn are you working on tests for this?

**Comment by lrhn** [comment]
Landed as https://dart-review.googlesource.com/c/sdk/+/154462

**Comment by mit-mit** [comment]
Can we mark the present issue resolved then?

**Comment by lrhn** [comment]
A quick checks shows the front-end giving errors on the test, and the analyzer crashing (failing to read the some `sdk/version` file), both on a fresh build of the SDK.

@johnniwinther @scheglov  Are the bugs in the test or in the implementations?

**Comment by lrhn** [comment]
All tests run, so can be closed.
