### ISSUE TITLE
CFE uses internal terms for sound null safety

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#42464]
The message here uses internal language:
_"Error: A library can't opt out of non-nullable by default, when in nnbd-strong mode"_
https://github.com/dart-lang/sdk/blob/master/pkg/front_end/messages.yaml#L1189

Please change this to use the external terms (sound null safety for strong, unsound null safety for weak, null safety for non-nullable):
_"Error: A library can't opt out of null safety by default, when in using sound null safety"_

A code search in the source shows several uses of the terms 'nndb-strong' and 'non-nullable' beyond this one.

**Comment by mit-mit** [comment]
cc @leafpetersen to confirm terminology

**Comment by mit-mit** [comment]
As for this specific error, this is the one I see when I have an app that is opened in which depends on a package which is not. I think we want to rephrase that a bit to something like:

```
ERROR: Cannot run with sound null safety as one or more dependencies do not support null safety. 

<list of offending dependencies>

Run 'pub outdated --mode=null-safety' to determine if versions of your dependencies
supporting null safety are available. 
```

**Comment by leafpetersen** [comment]
Terminology SGTM.

**Comment by johnniwinther** [comment]
Reopening for support of the more elaborate message.

**Comment by johnniwinther** [comment]
@mit-mit How do you trigger this error? I think that we need to handle the messaging based on how we trigger it; telling the user to run `pub` in a context where that does not apply is unhelpful.

**Comment by mit-mit** [comment]
I create an app (i.e. a package with an entry-point), and then make it depend on a second package that hasn't opted into null safety. 

I have a test app you can use here: https://github.com/mit-mit/null-safety-test

**Comment by johnniwinther** [comment]
So do you see the error when you run the code with `dart` from the command-line, running it through your editor, or some other way of invoking Dart?

Actually, if in an editor, we should probably have `dartanalyzer` complain about entry-points, that, if run, would be run in sound null-safety and fail with this error.

**Comment by mit-mit** [comment]
If you change main to this, you should see it:

```dart
import 'package:test_pkg_unmigrated/test_pkg_unmigrated.dart' as pkg2;

void main(List<String> arguments) {
  // Nullable variable from unmigrated library function.
  int i6 = pkg2.bar2();

  print('Hello: $i6.');
}
```

```
$ ~/sdk/be/dart-sdk/bin/dart --null-safety --enable-experiment=non-nullable ./test_app/bin/test_app.dart

test_pkg_unmigrated/lib/test_pkg_unmigrated.dart:1:1: Error: A library can't opt out of non-nullable by default, when in nnbd-strong mode.
int bar2() {
^
```

**Comment by johnniwinther** [comment]
I've updated the reporting of opt-out packages in https://dart-review.googlesource.com/c/sdk/+/153964

@mit-mit please try it and see if it helps in your use case.
