### ISSUE TITLE
Create missing override quick fix generates wrong code

### ISSUE THREAD

**Issue by maaeps** [dart-lang/sdk#42468]
This tracker is for issues related to:
* Analyzer (I think)

I've encountered a problem while using the 'Create missing overrides'-feature of IntelliJ and Android Studio.

When creating a new dart file with this content
```
abstract class A {
  foo(int foo);
  bar(String bar);
}

class B extends A {
}
```
, there are obviously two overrides missing in 'B'.

When using the 'Create 2 missing override(s)'-feature, I get this red cursor, used in the LiveTemplates, around the 'Str' in 'String'. This also changes the 'int' to 'Str'.

When changing the code slightly (like changing all 'foo' to 'bar' and vice versa), it suddenly works as expected.

I thought this was an issue with the IntelliJ dart plugin, but on [stackoverflow](https://stackoverflow.com/questions/62484595/intellij-idea-android-studio-dart-plugin-missing-overrides-created-wrong-is?noredirect=1#comment110621522_62484595) I was told, this is a problem with the dart sdk.

dart version : 2.8.4
os: MacOSX

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/152400
