### ISSUE TITLE
pub is missing the --(no-)sound-null-safety flags

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#42465]
Pub should support the null safety mode flags:  `--no-sound-null-safety` / `--sound-null-safety`.

When used, they should be passed on to the VM (note that the flag there is yet to be renamed: https://github.com/dart-lang/sdk/issues/41853)

**Comment by kevmoo** [comment]
@mit-mit should this be filed on the `pub` repo? Or are you talking about `dartdev`?

**Comment by mit-mit** [comment]
I'm not sure actually. Don't we generally need this flag in all binaries that run/compile code + on all dartdev verbs that run/compile code? cc @leafpetersen

**Comment by sigurdm** [comment]
* What is the timing of this. Can this be available already?
* Will the old names still be available, or do we have to transition how we forward the flag?

**Comment by mit-mit** [comment]
We will simply rename the existing flags, they have not been mentioned in public documentation yet, and the rename is thus not considered breaking.

@a-siva when do you plan on renaming https://github.com/dart-lang/sdk/issues/41853? The pub flag should probably be landed after that item is done.

**Comment by mit-mit** [comment]
@sigurdm the VM flag has now been renamed

**Comment by kevmoo** [comment]
Has a CL gone through the SDK to bring in this version of pub?

Perhaps we should wait to close it until that happens @sigurdm
