### ISSUE TITLE
I want dispose Stream without StreamController or StreamSubscription

### ISSUE THREAD

**Issue by Kangyeongwoo** [dart-lang/sdk#42480]
I want dispose Stream without StreamController or StreamSubscription.

How can i do that?

**Comment by Kangyeongwoo** [comment]
@lrhn 
Thank for your comment :)

Now I listen to stream with StreamSubscription.

But When i use StreamSubscription.cancel() that Stream still working on background at once.

Can't stop stream immediately.

I want stop stream immediately include background or memory.

**Comment by lrhn** [comment]
Calling `cancel` is all you *can* do. There is no way to stop code from running if it wants to run, so what you do by calling `cancel` is to inform it that you no longer care for the events.

If it's a broadcast stream, then it will likely keep working at some level, even if there are no listeners (but preferably it should stop doing anything while nobody's listening). The stream creator is the only one who knows how long it makes sense to keep working. In most situations the stream is associated with some other object, and when that object goes out of scope, the stream controller might be garbage collected along with it.

For a single-subscription stream, the stream creator *should* clean up when the listener cancels. It might take some time to release all resources, and in that case you should wait for the future returned by `cancel` to know when it's done cleaning up.
If it doesn't do that, then the stream is behaving badly.

If you are really insistent, and you are running on a platform supporting isolates, you could run the stream in a different isolate and send the events to your isolate, and then kill the isolate. It's still not *instant*, and it might not be possible if you are not in control of the code creating the stream.

**Comment by Kangyeongwoo** [comment]
@lrhn
Thanks for your support :)
I use isolate and isolate.kill.
Finally, I solved my problem.
Im really thank you!!
