### ISSUE TITLE
`dart --version` talks about the VM

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#42486]
Running `dart --version` prints:

```
$ dart --version
Dart VM version: 2.9.0-19.0.dev (dev) (Thu Jun 25 10:48:31 2020 +0200) on "macos_x64"
```

I'd expect this to talk about the `Dart SDK version`, not the `Dart VM version`

**Comment by jwren** [comment]
Assigning to @bkonyi.  Would `VM` -> `SDK`, be sufficient?

`Dart SDK version: 2.9.0-19.0.dev (dev) (Thu Jun 25 10:48:31 2020 +0200) on "macos_x64"`

**Comment by mit-mit** [comment]
> Would VM -> SDK, be sufficient?

Yes, I think so.
