### ISSUE TITLE
`dart help run` shows too many options

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#42483]
`dart help run` shows a bunch of options I think we should remove or hide and only show with `-v`:

```
--package-root=<path> or -p<path>
  Where to find packages, that is, "package:..." imports.
```
=> remove, see https://github.com/dart-lang/sdk/issues/41197

```
--write-service-info=<file_uri>
  Outputs information necessary to connect to the VM service to the
  specified file in JSON format. Useful for clients which are unable to
  listen to stdout for the Observatory listening message.
```

=> move to `-v`, this is rarely needed by end users

```
--snapshot-kind=<snapshot_kind>
--snapshot=<file_name>
  These snapshot options are used to generate a snapshot of the loaded
  Dart script:
    <snapshot-kind> controls the kind of snapshot, it could be
                    kernel(default) or app-jit
    <file_name> specifies the file into which the snapshot is written
```
=> remove, we now have `dart compile` for this

```

**Comment by jwren** [comment]
This conversation was originally around issue https://github.com/dart-lang/sdk/issues/40953, where we negotiated which processes would print out the help, at the time we negotiated and reduced the number of options and flags down to what we have today.

At the time though `dart compile` wasn't landed yet.  Assigning to Ben to remove any flags that can be removed from the Dart VM (in the default, non-`-v`, case).
