### ISSUE TITLE
Is ListMixin fully usable for non-nullable typed elements?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42496]
The migrated implementations of ListMixin documentation says:
> This implements all read operations using only the `length` and `operator[]` members. It implements write operations using those and `length=` and `operator[]=`

To preserve soundness the NNBD spec requires that lists of non-nullable elements throw a runtime exception when expanding the size of the list using the length setter https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#core-library-changes.

I've heard it's a known issue that classes that mixin `ListMixin` also need to override `add()` after the null safety migration. Are we committing to that requirement? **_This needs to be in the documentation._** I know we want to preserve backwards compatibility but it's a little scary there is no way to know you have a problem until you get an exception at runtime. Hopefully everyone has good test suites. Are there plans to make `add()` abstract in the future?

Similar to `add()`, the `insert()` operation in `ListMixin` is another a source of problems because it calls `this.length++`:
https://github.com/dart-lang/sdk/blob/3b67681bcc4627b46656215a1a9a56138ca3f3f0/sdk/lib/collection/list.dart#L505-L515

This means you can't insert into a list of non-nullable elements if your implementation delegates to the built in list. See the `MyList` class from our tests: https://github.com/dart-lang/sdk/blob/a9bef090e8cbda6a21cedbcd9f745149a5350ba4/tests/corelib/list_test.dart#L548-L564 

I have a potential fix that rewrites the implementation of `insert()` to depend on `add()` but that only works if we commit to requiring users to override it. Should I send it out for review?

**_NOTE:_** there is a separate bug that hides this error in the VM so don't depend on what you see when running the VM. @leafpetersen can link the issue when it gets filed. 

cc @lrhn @natebosch

**Comment by natebosch** [comment]
I think the "safe" thing to do is to update the documentation to say "To implement a list that supports a non-nullable element type the `add` method must be overridden.". For the implementation of `insert` we might have to do something like `if (null is E) { /* old approach using length++ */ } else { /* new approach using add() */ }`.

The other option would be to announce a breaking change, remove the implementation of `add()` to force it's implementation, and try to determine the scale of the impact.

**Comment by lrhn** [comment]
Yes, there is no sound way to implement `add` using the `[]=` and `length=` setters any more. You really have to implement it manually. It's has to be a primitive operation now.

**Comment by natebosch** [comment]
@lrhn - are you OK with my proposed solution of having 2 implementations of `insert` in `ListMixin` with a conditional on `if (null is E)`? Do you think that would maintain backwards compatibility or am I overlooking something?

**Comment by lrhn** [comment]
I want both: 
* Define non-`add`` methods that increase the length, in terms of `add`, whether `null is E` or not, and then have an `add` which only works when `null is E`. 
* Then try to go for a breaking change which removes that `add` implementation and makes `add` a primitive operation that must be implemented.
