### ISSUE TITLE
Non-function type aliases may need work for null safety

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42498]
I've migrated the non-function type alias tests to null safety. I'm seeing a few failures that look like bugs to me:

https://ci.chromium.org/p/dart/builders/try/front-end-nnbd-linux-release-x64-try/4474

I'll approve the failures since the feature isn't shipped yet anyway, but this issue is a reminder to look at them when work on that language feature resumes.

cc @eernstg

**Comment by eernstg** [comment]
That's fine, thanks!

**Comment by eernstg** [comment]
Closing: these failures do not occur with a fresh CFE.
