### ISSUE TITLE
Include a simple README.txt in $HOME/.dart

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42500]
Tell folks looking around their directory

* when this directory was created
* by what tool
* What it's for – with a link to our web site?

CC @jwren @mit-mit

**Comment by jwren** [comment]
If the idea sounds good to you @mit-mit, please provide a the `README.md` contents here and I'll make the change.

**Comment by mit-mit** [comment]
Current contents:

```
$ ls -l ~/.dart
total 8
-rw-r--r--  1 mit  primarygroup   0 Jun 25 14:56 analytics.json
-rw-r--r--  1 mit  primarygroup  97 Jun 25 14:49 dartdev.json
```

**Comment by mit-mit** [comment]
So this is basically a Dart-wide directory containing various settings.

**Comment by kevmoo** [comment]
> So this is basically a Dart-wide directory containing various settings.

Yup.

One could argue we could/should move `.pubCache` here, too! Not now...but...someday

**Comment by mit-mit** [comment]
Draft CL in https://dart-review.googlesource.com/c/sdk/+/158521

**Comment by jwren** [comment]
@mit-mit @kevmoo any changes before LGTM so we can land the PR and close out this issue?

**Comment by mit-mit** [comment]
+1'ed the cl
