### ISSUE TITLE
[QuickFix] Support more detected lint fix (like prefer_final_in_for_each)

### ISSUE THREAD

**Issue by bounty1342** [dart-lang/sdk#42510]
Hi,

When adding a linter on a projet, you might get a lot of lint, and the analysis server already does a pretty good job at giving fixes, but some that seems trivial are not pick up.

As an example, there is prefer_final_in_for_each : 
![Screenshot 2020-06-27 at 18 01 57](https://user-images.githubusercontent.com/6307253/85927341-c3a97a00-b8a5-11ea-8341-e03c806bd2b1.png)

I'll update when I encounter more.

**Comment by bwilkerson** [comment]
Thanks for pointing out the opportunity to add a fix. This has now been added and should be available in the next release (https://dart-review.googlesource.com/c/sdk/+/152618).

When you find others, please do report them. We value the feedback.
