### ISSUE TITLE
Help text for `migrate` is Null Safety-specific

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#42511]
The `dart migrate` command is documented as upgrading to null safety.

While that's currently true, we will likely want it to keep upgrading to the newest/next Dart language version in the future.

It's not entirely clear how it picks which migration to apply, Currently it's easy because there is only one.

Maybe the command should have a `--version=2.10` flag to select the language version to migrate to.
Then it defaults to the current SDK version. For a dev-version, it will include the expected features for the next v ersion,
for a  stable release, it will upgrade code to the current language version.
And you'll at some point be able to do `--version=2.10` and not migrate to 2.11 features yet.

**Comment by mit-mit** [comment]
I suggest we change the description to be more generic ("Migrate source code to a new language version"), but for now assume that we're always upgrading to the current version of the SDK. We can then later add a `--version` flag (which can default to the current SDK version).

@jwren @devoncarew WDYT?

**Comment by jwren** [comment]
Assigned @stereotype441  and @devoncarew who have thought more about and own `dart migrate`

**Comment by devoncarew** [comment]
I think we should leave it as is; it's easy enough to change in the future, and we could make that change if it ever supports other migrations.

> It's not entirely clear how it picks which migration to apply, Currently it's easy because there is only one.

Yes, there's no mechanism to select migrations - it just works to migrate code to support null safety.

**Comment by mit-mit** [comment]
OK, fair enough, closing.
