### ISSUE TITLE
Front end flags use of `Future<void>` and `FutureOr<void>` as use of `void`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42527]
Cf. the following tests: `language/invalid_returns/async_invalid_return_{2{7,8},3{0,1}}_test.dart`.

The front end flags an error with "This expression has type 'void' and can't be used" in some cases where the expression actually does not have that type. This probably only occurs when the function is `async`, where the type of the returned expression may be flattened before it is tested whether the return statement is statically correct (so we get an error for returning a `Future<void>` or `FutureOr<void>` because we've reduced it to `void` and forgotten that this is not the actual type of the returned expression).

Those tests should still have an error, but it is concerned with the downcast.

**Comment by lrhn** [comment]
It might be worth noting that **NORM**(`FutureOr<void>`) is `void`. If anything does premature normalization, it might seem that the type is `void`.
