### ISSUE TITLE
Failures on "[vm/corelib/nnbd] Fix null check in _GrowableList.length="

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#42521]
There are new test failures on [[vm/corelib/nnbd] Fix null check in _GrowableList.length=](https://dart-review.googlesource.com/c/sdk/+/152900).

The tests
```
corelib/list_concurrent_modify_test RuntimeError (expected Pass)
corelib/list_test/01 RuntimeError (expected Pass)
corelib/list_test/none RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartkp-strong-linux-release-x64
```

These tests use `List.length=` to grow lists of non-nullable types, so they should be updated. The tricky cases is when they use `ListBase` / `ListMixin` to implement the list, and `length=` setter is used from `ListMixin`.

Related: https://github.com/dart-lang/sdk/issues/42496

/cc @leafpetersen @munificent @lrhn

**Comment by munificent** [comment]
I'll take this.

(But note that in general, the language and core library tests are owned by the entire Dart team and anyone can and should feel empowered to fix them when they discover errors in them.)

**Comment by leafpetersen** [comment]
@munificent you may want to hold off until we resolve https://github.com/dart-lang/sdk/issues/42496 .  Basically, those tests use `insert` and `add` from ListMixin.  add will never work without a custom implementation, but insert can possibly be made to work.  @lrhn and @natebosch are you handling the ListMixin issue?  

Alternatively, if you think better feel free to just change the expectation of the tests for now, and we can change them back if/when the library implementation changes.

**Comment by alexmarkov** [comment]
@munificent I understand that. This is not just errors in tests - I think this is blocked on https://github.com/dart-lang/sdk/issues/42496 which is definitely a core library issue.

(Also, I was following Leaf's suggestion https://github.com/dart-lang/sdk/issues/42502#issuecomment-649834067, so please don't hold a grudge against me.)

**Comment by leafpetersen** [comment]
> (Also, I was following Leaf's suggestion [#42502 (comment)](https://github.com/dart-lang/sdk/issues/42502#issuecomment-649834067), so please don't hold a grudge against me.)

Yeah, sorry, I meant to mention that here as well - while I 100% agree with the sentiment that we all own the tests, in this case I did suggest that @alexmarkov pass this off to us to resolve.  And as I recall, @alexmarkov hasn't been shy about fixing up language tests in the past, so no grudges held... :)

**Comment by whesse** [comment]
I noticed this new failure when it entered the new dev release I am making.  Make sure this issue is triaged as blocking/non -blocking for the next stable release.  I considered it non-blocking for the dev release.

**Comment by athomas** [comment]
The tests are passing now on the VM: https://dart-ci.firebaseapp.com/current_results/#/filter=corelib/list_concurrent_modify_test,corelib/list_test,dartk,dartkp&showAll
