### ISSUE TITLE
dart2js adds null checks on return values of non-nullable native APIs

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#42536]
this is to ensure that MDN-based APIs are correct.

Our plan is to have a flag to include or exclude them so we can assess how much overhead they add.

If optimizations break due to a bad nullable annotatoin, users can turn on weak mode as a workaround until a fix in dart:html is shipped.

We should make sure the error message includes details to discover the workaround easily.

**Comment by leafpetersen** [comment]
@sigmundch is this a blocker for beta or can this slip to beta2 or stable?

**Comment by sigmundch** [comment]
I'd prefer to keep it on for beta: we want to know as early as possible if any DOM/native API is incorrect with respect to null safety, so the earlier we get this out, the longer we'll have to detect and fix that.

**Comment by franklinyow** [comment]
Is this done?

**Comment by sigmundch** [comment]
implementation is in place, but we are actively testing it out internally before enabling this by default

**Comment by sigmundch** [comment]
We decided we'll not enable it by default, but will eventually let tools enable it instead.

Since the change will not be in the sdk proper, this is no longer blocking the october release.

**Comment by jakemac53** [comment]
As I was enabling support in build_web_compilers I noticed this is not a negatable flag - do we have a commitment that this will _never_ be enabled by default by dart2js? Otherwise we will be left with configuration that is not respected (essentially, passing an explicit `false` on our end for this won't do anything). Or if that is the behavior we want then that also works, but that seems less than ideal to me.

**Comment by sigmundch** [comment]
Good question, we should give you an answer shortly.

/cc @srujzs 

We are in the process of changing the default for ddc on a library by library basis (on if the library is opted-in to null safety, off when it's not), and the ability to turn it off with `--no-native-null-assertions`. I don't believe we intend to change the dart2js default right now, but I'm not opposed to having the negated flag available so we have that flexibility in the future.

Even if we don't turn it on by default within the sdk, we may want to consider turning it on by default on some build systems.

**Comment by vsmenon** [comment]
Do we have an owner / action on this?  Beta cut is in a few days.

**Comment by sigmundch** [comment]
@srujzs is driving on the sdk changes and @jakemac53 on the build_web_compilers side.

It's quite possible this is all done by now, but I'll let them confirm

**Comment by jakemac53** [comment]
We support _enabling_ these assertions in build_web_compilers now, yes.

**Comment by srujzs** [comment]
There's still the question of the discrepancy between the two compilers regarding opt-in/opt-out that I don't think there was a resolution for. Ultimately, after talking it over, I don't think we can make that distinction currently in dart2js, but unlike ddc, there are no potential breakages either way.

dart2js has to choose between either allowing these in unsound regardless of opt-in and sound null-safety, or just sound null-safety. ddc has to choose between making this in both unsound (which could be breaking) and sound null-safety, opt-in and sound null-safety, or just sound null-safety.

Once we can decide there, it's just a matter of landing CLs.

**Comment by srujzs** [comment]
Changes here and in #42535 have landed for sound null-safety only. Marking them closed now. #43780 will track the work related to enable in various build systems.
