### ISSUE TITLE
ddc adds null checks on return values of non-nullable native APIs

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#42535]

**Comment by leafpetersen** [comment]
@sigmundch also here, blocker for beta?

**Comment by sigmundch** [comment]
Similar to https://github.com/dart-lang/sdk/issues/42536 - we'd like it as part of beta if at all possible. This is less critical than the dart2js one because DDC is mostly used together with chrome, which is where most of the non-nullable bits are derived from, but I'd prefer to keep it.

**Comment by franklinyow** [comment]
Is this done?

**Comment by sigmundch** [comment]
We discovered through testing some changes that need to be made for this bug, so it's still in progress. It is OK if this slips and 
and when it lands it will be under a flag, so it's ok if it lands hot. We'll keep it in the current milestone for now and adjust early next week if needed.

**Comment by franklinyow** [comment]
Move it to the next milestone

**Comment by franklinyow** [comment]
Any update?  Thx

**Comment by franklinyow** [comment]
@sigmundch It's been reverted.  Who's working on this one?

**Comment by sigmundch** [comment]
@srujzs is pushing forward with the original change, but will make the behavior only to be enabled on libraries that are opted in. This strategy doesn't change the essence of the change, but will make it less disruptive and will allow the roll to happen without issues.

There are a couple changes involved here (relanding the change, adding a flag), but our expectation is that we'll manage to land it this week.

**Comment by franklinyow** [comment]
@srujzs any update?

**Comment by srujzs** [comment]
More info in https://github.com/dart-lang/sdk/issues/42536 that's directly related. Adding on to that, we're planning on only including this in sound null-safety for now with maybe the potential for opt-in unsound null-safety for DDC only. My goal is to land CLs related to this ASAP.
