### ISSUE TITLE
pkg:analyzer - ParameterElement.type is dynamic for required positional params w/ null safety enabled

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42552]
```dart
// @dart=2.9

class Person {
  final String firstName;
  final String lastName;
  final DateTime? dateOfBirth;

  Person({
    this.firstName = 'unknown',
    required this.lastName,
    this.dateOfBirth,
  });
}
```

This code, without the `2.9` override (and the required bits) `ParamaterElement.type` is `String`.
WITH `// @dart=2.9` the `firstName` param has a type `String`, `lastName` (with required) has a type `dynamic`

This is w/ pkg:analyzer `0.39.11`

CC @scheglov

**Comment by scheglov** [comment]
With `// @dart=2.9` using `required` is a syntactic error, so I'm not surprised that you get strange types.
It is probably parsed as `Person({required this, lastName})`, so `lastName` has no declared type.

**Comment by kevmoo** [comment]
Without `required` I get `error: The parameter 'lastName' can't have a value of 'null' because of its type, and no non-null default value is provided. (missing_default_value_for_parameter at [json_serializable] example/example.dart:19)`

It actually TELLS ME to add `required` in a fix!!

**Comment by scheglov** [comment]
Ah, sorry.
With `// @dart=2.9` it also should work, it is the current language version in analyzer.
That is, if `non-nullable` experiment is enabled for this file.

How do you analyze it?

**Comment by scheglov** [comment]
Here is a unit test for element model for you code.

When `non-nullable` experiment is enabled and the language override is `2.9`, we parse it correctly, and infer types.

```dart
  solo_test_issue42552() async {
    featureSet = enableNnbd;
    var library = await checkLibrary('''
// @dart=2.9

class Person {
  final String firstName;
  final String lastName;
  final DateTime? dateOfBirth;

  Person({
    this.firstName = 'unknown',
    required this.lastName,
    this.dateOfBirth,
  });
}
''');
    checkElementText(library, r'''
class Person {
  final String firstName;
  final String lastName;
  final DateTime dateOfBirth;
  Person({String this.firstName: 'unknown'}, {String this.lastName}, {DateTime this.dateOfBirth});
}
''');
  }
```

Without the experiment enabled, or when the language override is for example `2.8`, we get:
```dart
class Person {
  final String firstName;
  final String lastName;
  final DateTime dateOfBirth;
  Person({String this.firstName: 'unknown'}, {dynamic this.lastName}, {DateTime this.dateOfBirth});
}
```

**Comment by kevmoo** [comment]
Okay – so I have to run `pub run build_runner build --enable-experiment non-nullable` – and everything works as expected.

Weird, but okay...
