### ISSUE TITLE
[CP] merge #a114b165 into [stable] channel: fixes broken compilation when importing dart:mirrors on the web

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#42553]
**commit(s) to merge**: a114b165e5b20700628eb43d8d918c49ab44fa49

**merge instructions**: clean merge

**reason**: our compilers stopped compiling some applications and this small change will make them compile again. This was an unintentional breaking change and we'd like to undo it.

Risk is very low, the change is very small and has a very limited surface area and mostly only affects users whose apps got broken.

In more detail: `dart:mirrors` is unsupported on the web, but we allow imports to it. All APIs throw at runtime, but apps can be compiled and if they don't access the mirrors APIs at runtime, the apps work.

Eventually we'd like to make a breaking change to fully remove the support for dart:mirrors and make it a static error to import it, but we didn't intended to do so in 2.8. A couple months ago we removed it, saw some breakage, and added it back. When it was added back it was not tested and after the CFE added a few more static checks it broke without it being noticed.

Recently users ran into this problem and reported it to us https://github.com/dart-lang/sdk/issues/42475.

The commit above fixes the static errors and adds unit tests to ensure we continue to allow imports to `dart:mirrors` until we are ready to make the breaking change.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by vsmenon** [comment]
@sigmundch is this a regression?  If not, is there a reason to cherry-pick?

**Comment by sigmundch** [comment]
Yes - it was a regression, code compiling under 2.7.2 now reported compile-time errors in 2.8.1 (example in #42475)

**Comment by athomas** [comment]
FYI, we've already entered the stabilization phase for 2.9, we can still do a 2.8 hotfix but the window will close in a couple days.

**Comment by franklinyow** [comment]
@sigmundch  Do you want to move forward?

**Comment by sigmundch** [comment]
I'm torn, honestly.

@mit-mit @kevmoo @leafpetersen  I'd love to hear your thoughts, especially that if we don't cherry-pick this for 2.8, we likely need to take action and cherry-pick for 2.9.

Bottom-line we need to decide: do we want to make an import of `dart:mirrors` a static compile-time error on the web? For consistency, does flutter complain at compile-time or latter?

To rephrase the situation in terms of the new template questions:

**what's the problem**: dart2js used to accept programs that imported `dart:mirrors`. If the code was tree-shaken, there was no issue. A runtime error would have only been visible if the code was invoked. We accidentally introduced a breaking change and made it a compile-time error.

The story is more complex because in 2.8.0-dev.9.0 we made it a compile time error on purpose, then reverted it on a subsequent dev release because it broke dart-sass. Since then, dart-sass landed a workaround on their end, and we accidentally broke it again (in the commit + partial revert we accidentally lost test coverage of building dart:mirrors, so when the CFE later started reporting error messages on patch files it was undetected, as a result `dart:mirrors` always gives compile-time errors in 2.8).

**why is that a problem**: it's an unintended breaking change. We do want to make the breaking change, but in this case it was accidental.

**fix to the problem**: the change is simple (a114b16), mostly deleting lines and adding two `?` annotations. This only affects the patch of `dart:mirrors` on web clients.

**risk**: extremely low given the limited scope of the change.

**how does this improve 2.8**: it removes an unintended breaking change.

**why are we torn**:

We do want to make the breaking change eventually. Our biggest concern is whether this kind of breaking change could slow down adoption of null-safety: these imports can be derived from a transitive dependency, so removing them from an application might require coordination across package authors or big refactoring changes (especially if the culprit package was general purpose and not tested on the web).

There is very low cost for us to maintain the old behavior, so we only want to introduce the breaking change if we decide it is worth it and OK to accept.

At the same time, we believe flutter web doesn't allow it, pub.dev labels packages that import mirrors as only supported on "native", and build_web_compilers doesn't allow the imports when compiling with DDC. Given that only one user has reported the issue, we think we could take this moment to embrace the breaking change.

Note that we did land the fix and it is already part of 2.9 (in 2.9 there is no compile-time error), so if we decide to embrace the breaking change now, we'd may want to cherry-pick a separate change to 2.9-beta to reintroduce the compile-time error.

Thoughts?

**Comment by kevmoo** [comment]
I'm absolutely torn, too.

So, at this point: what's the absolute least amount of work we can do here?

We either cherry pick this to stable (2.8, right?) and do a roll there.
Or we cherry pick this to beta.

The last thing we want to do is be inconsistent.

I also echo the desire to completely eliminate this codepath in dart2js

**Comment by sigmundch** [comment]
The amount of work is probably all similar.

Options in order of amount of work are:
 * (a) unbreak future stable: no work, 2.8 stays broken, 2.9 will allow imports again (this punts when to break dart mirrors until later)
 * (b) unbreak current stable: cherry-pick change to 2.8 so both 2.8 and 2.9 accept imports to dart:mirrors
 * (c) embrace break in future stable: leave 2.8 as is, land a new change to re-break 2.9 and cherry-pick that change.

but (c) is pretty small amount of extra work (2-line change), so it's not that much more really.

**Comment by kevmoo** [comment]
(a) leaves us with some bouncing behavior, which is weird
(b) cherry pick to stable is more annoying than to beta IMHO
(c) I vote for this one!

**Comment by sigmundch** [comment]
We decided to to with (c), so I'm closing this request and filed https://github.com/dart-lang/sdk/issues/42715 instead
