### ISSUE TITLE
Mac: Wiki instructions for installing dev channel with homebrew not working

### ISSUE THREAD

**Issue by hpoul** [dart-lang/sdk#42562]
It looks like the wiki for installing the dev release of dart is not quite working: https://github.com/dart-lang/sdk/wiki/Installing-beta-and-dev-releases-with-brew,-choco,-and-apt-get#installing

> $ brew install dart -- --head
> Error: No available formula with the name "--head" 

I think i should be `brew install --head dart`

And the upgrade does not work for me.

I have installed:  2.9.0-19.0.dev (dev)

```
brew upgrade --fetch-HEAD dart
Warning: dart-lang/dart/dart HEAD already installed
```

I had to use reinstall (after brew upgrade):

```
$ brew reinstall dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/dev/release/2.9.0-20.0.dev/sdk/dartsdk-macos-x64-release.zip
######################################################################## 100.0%
==> Reinstalling dart-lang/dart/dart 
```

(running Homebrew 2.4.3 on MacOS 10.15.5 (19F101))

**Comment by athomas** [comment]
I updated the install command, not sure what happened there.

For upgrading, when installed with `--head` `brew reinstall dart` worked for me. `brew install -f dart` worked for me to switch from dev to stable (the wiki page has been updated with that info as well). Unfortunately, brew is a bit awkward to use with `head` versions (see also https://github.com/Homebrew/legacy-homebrew/issues/13197)...
