### ISSUE TITLE
Dart's Await keyword is not working as expected in flutter web.

### ISSUE THREAD

**Issue by AchalYash** [dart-lang/sdk#42569]
While trying to implement Firebase login, Dart's await keyword is not functioning as intended.

Dart version:  2.9.0-14.1.beta.
Flutter version: 1.19.0-4.2.pre ; channel Beta.

OS: Windows.
Browser: Chrome.

Here's the Login Function - Firebase Login : 

```dart
  Future<int> userLogin(String mail, String password) async {

    int loginStatus = -5;
    print("Logging User In");

    try {

      print("Connecting to Firebase");
      _auth.signInWithEmailAndPassword(email: mail, password: password).then((firebaseUser)  {

        if(firebaseUser != null)  {

          UserDetails.currentUser = firebaseUser.user;
          loginStatus = 1;
          print("Login Successful");
          print("Current User - ${UserDetails.currentUser.email}");
        }
        else  {

          print("Login Failed - Null User");
          loginStatus = -2;
        }
      });
    } catch (loginError)  {

      print("Login Failed\n$loginError");
      loginStatus = -1;
    }

    return loginStatus;
  }
```

Here's the Hash Function - Writes data into FireStore : 

```dart
  Future<int> writeHash ()  async {

    print("Writing Hash Document");

    DocumentReference studentHash = _firestoreInstance.collection("HashData").document("H");
    try{
      studentHash.setData({"ABCDEFG" : [UserDetails.currentUser.uid, "ABC", "123"]}).then((value) {
        print("Hash Document Updated\nvalue");
      });
    } catch (hashError) {
      print("Hash Document Updation Error\n$hashError");
    }

    return 1;
  }
```

This is how they are being called on button press:
```dart
onPressed: () async {
          loginStatus =  await fireBaseOperations.userLogin("random-email@mail.com", "RandomPassword");
          print("loginStatus $loginStatus");
          await fireStoreOperations.writeHash();
        },
```

And here's the OutPut :

```
Logging User In
Connecting to Firebase
loginStatus -5
Writing Hash Document
Hash Document Updation Error
NoSuchMethodError: invalid member on null: 'uid'
Login Successful
Current User - random-email@mail.com
```

Here's flutter doctor in case it's of any relevance here:

[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.19.0-4.2.pre at C:\flutter
    • Framework revision 9b9b543d92 (11 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Achal\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

[√] Connected device (2 available)
    • Web Server       • web-server • web-javascript • Flutter Tools
    • Chrome           • chrome     • web-javascript • Google Chrome 83.0.4103.116

**Comment by lrhn** [comment]
Neither `userLogin` nor `writeHash` contains any `await`. Most likely they should.
It means that whatever asynchronous operations you are doing inside those functions, are not being waited for, and the functions return as soon as possible.

**Comment by AchalYash** [comment]
Tried it, and yes it worked. Thank you so much :)
