### ISSUE TITLE
Required annotation not working when it placed only in a parent class

### ISSUE THREAD

**Issue by alphamikle** [dart-lang/sdk#42561]
Hello, the problem is described at screenshots, code, and title of this issue.

[Dart Pad](https://drive.google.com/file/d/1w9sMWYLGxOmq0Bsr4LKuaoMPEZx2GrNH/view?usp=sharing)
[VS Code](https://drive.google.com/file/d/1rmUeT9KEcyy61ODnnQDvFwllC9OVRcRE/view?usp=sharing)
[Android Studio](https://drive.google.com/open?id=1ppmWKJ6jTtA8XXEtiJZDyuua9zYxQtJJ)

```dart
import 'package:flutter/foundation.dart';

void main() {
  final secondClass = SecondClass(); // <- Not showing error at empty @required prop
  final thirdClass = ThirdClass(); // same problem
  final fifthClass = FifthClass(); // it's ok (showing error)
  final sixthClass = SixthClass(); // it's ok (showing error)
  final zeroClass = SeventhClass(); // same problem
  print(secondClass);
  print(thirdClass);
  print(fifthClass);
  print(sixthClass);
  print(zeroClass);
}

class ZeroClass {
  ZeroClass({@required this.prop}); // dyplicate code

  final String prop;

  @override
  String toString() => 'zero class with prop "$prop"';
}

abstract class FirstClass {
  FirstClass({@required this.prop}); // duplicate code

  final String prop;

  @override
  String toString() => 'first class with prop "$prop"';
}

abstract class FourthClass {
  FourthClass(this.prop);

  final String prop;

  @override
  String toString() => 'fourth class with prop "$prop"';
}

mixin FirstClassMixin {}

class SecondClass = FirstClass with FirstClassMixin;

class ThirdClass extends FirstClass with FirstClassMixin {}

class SixthClass extends FirstClass with FirstClassMixin {
  SixthClass({@required String prop}) : super(prop: prop); // duplicate code
}

class FifthClass = FourthClass with FirstClassMixin;

class SeventhClass = ZeroClass with FirstClassMixin;
```

* dart >= 2* (maybe in 1X, but not tested)
* MacOS, Windows, DartPad

**Comment by eernstg** [comment]
Thanks for reporting this!

However, the `@required` annotation was never a part of the language and the support for static checks could not be made sound and complete. With the upcoming null-safety feature you will be able to use `required` as a regular keyword (technically it's a built-in identifier), and this is a feature that is integrated into the language and its type system.

This means that it is not planned to resolve the issues with `@required`, but you will get a proper mechanism for this purpose when you migrate to use null-safety. Based on that I'll close the issue.
