### ISSUE TITLE
Implement external and abstract variables

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42560]
This is the tracking issue for implementing external variables and abstract instance variables, as specified [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/feature-specification.md). The implementation plan is [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/implementation-plan.md).

Subtasks (with check boxes for the ones that aren't issues in this epic):

- [Front end](https://github.com/dart-lang/sdk/issues/42718)
- [Analyzer](https://github.com/dart-lang/sdk/issues/41940)
- [Dartfmt](https://github.com/dart-lang/dart_style/issues/946)
- [Formal specification](https://github.com/dart-lang/language/issues/1157)
- [Codemirror (Cider, DartPad)](https://github.com/dart-lang/dart-pad/issues/1614)
- [Dartdoc](https://github.com/dart-lang/dartdoc/issues/2310)
- [Co19 tests](https://github.com/dart-lang/co19/issues/912)
- [x] IntelliJ
- [x] Grok
- [x] Analysis server
- [x] Update github syntax highlighting (https://github.com/dart-lang/dart-syntax-highlight)
- [x] VS Code
- [ ] Other Tools: Validate that build systems, code generators, Angular compiler all work and are updated.

**Comment by vsmenon** [comment]
@leafpetersen @franklinyow - do we have a particular release we're aiming for yet?

**Comment by eernstg** [comment]
The feature is controlled by the `non-nullable` experiment flag, so presumably it's synchronized with null safety.

**Comment by leafpetersen** [comment]
Yes, this feature is intended to ship with the null safety release, and both the analyzer and the CFE are on board with that timing (@stereotype441 will contribute substantially to the analyzer implementation, which I believe is already in progress).

**Comment by vsmenon** [comment]
Thanks.

@franklinyow - are we tracking this for null safety beta work?

**Comment by franklinyow** [comment]
Added this under Beta Epic

**Comment by leafpetersen** [comment]
Looks like this is close to done.  Other than dartpad, any other work we're tracking?

**Comment by eernstg** [comment]
The language specification work will be done after the stable 2.8 spec is out, and we don't otherwise consider that step to be blocking.

**Comment by leafpetersen** [comment]
I think this is done.
