### ISSUE TITLE
[analysis_server] There's no Revision History on changes to the Analysis Server API.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#42572]
The [Analysis Server API](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html) has bee updated to version 1.28.0 recently.

I'd like to ask if a revision history (for example in a simple table at the bottom of the spec) could be updated on each change to the protocol.
See [Dart VM Service Protocol (end of page)](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md) for an example.

**Comment by modulovalue** [comment]
@DanTup, you have recently updated the Analysis Aerver API. See https://github.com/dart-lang/sdk/commit/a0cc6c981923f6b1283f5e157eb358d8594adbd2
Could you please add a revision history section for this and/or future changes?

**Comment by DanTup** [comment]
@bwilkerson I don't think there's anything existing for this - would it be best to add something directly in https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/spec/spec_input.html (maybe after the `Enumerations` section)?

**Comment by DanTup** [comment]
I also realise I didn't change the version number on the change above - it's non-breaking based on the description of enums being open-ended, though the version should've still changed. Should I change it now, or would it be more confusing to describe 1.32.1 as including a change that was actually patched into 1.32.0? 😔

**Comment by bwilkerson** [comment]
Yes, it's probably easiest to add it to the spec. I don't have a strong opinion about where.

We should probably update the version number so that clients can know whether it's safe to depend on it, though I honestly don't think this will impact existing clients. And I expect that the change log should indicate what version number clients need to use in order to depend on a feature rather than what version number it first appeared in.

**Comment by DanTup** [comment]
I realised as I made the change, that we're not actually using this value yet (the completion work is waiting on a Pub API), so now I've updated the version, no client using 1.32.0 would receive that `kind` in any case.

https://dart-review.googlesource.com/c/sdk/+/174803/
