### ISSUE TITLE
NNBD: Least and greatest closure algorythm does not substitute Object? instead of dynamic

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42579]
Dart VM version: 2.9.0-20.0.dev (dev) (Wed Jul 1 11:29:16 2020 +0200) on "windows_x64"

Here is a sample code example according to the [co19 Issue #575 evaluation](https://github.com/dart-lang/co19/issues/575#issuecomment-613542349):
``` dart
Type? _capturedTypeArgument;

X captureTypeArgument<X>() {
  _capturedTypeArgument = X;
  throw 1;
}

Type? get capturedTypeArgument {
  var result = _capturedTypeArgument;
  _capturedTypeArgument = null;
  return result;
}

class C<X> {}

void main() {
  void f<X>(C<X> Function() g) => g();
  try { f(() => captureTypeArgument()); } catch(e) {}
  print(capturedTypeArgument);
}
```
[NNBD Spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#least-and-greatest-closure) reads:
> The definitions of least and greatest closure are changed in null safe libraries to substitute `Never` in positions where previously `Null` would have been substituted, and `Object?` in positions where previously `Object` or `dynamic` would have been substituted.

However, dart prints `C<dynamic>` for the source above.

According to the Spec, `capturedTypeArgument` should be C<Object?> instead.

**Comment by eernstg** [comment]
I believe this is correct: The returned expression `captureTypeArgument()` should be inferred with context type `C<_>` which is taken from the imposed return type schema where `_` is the unknown type (aka `?` in some documents, although this has nothing to do with nullability). So we should get `captureTypeArgument<C<Object?>>()` from inference.

This is then most likely a bug in the common front end computation of context types for returned expressions in function literals, or the computation of the inferred return type of function literals.

@johnniwinther, do you agree?

**Comment by johnniwinther** [comment]
cc @stefantsov
