### ISSUE TITLE
[NNBD] Analyzer and CFE behave differently for implicit return

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42581]
The following code produces an error in VM and no issues in analyzer (both with `--enable-experiment=non-nullable`)
```dart
main() {
  (x) {
    if (x)
      return 1;
  } (true);
}
```
VM output is
```
D:\co19\Language\Statements\Return>dart --enable-experiment=non-nullable,nonfunction-type-aliases many_return_statements_t04.dart
many_return_statements_t04.dart:21:3: Error: A non-null value must be returned since the return type 'int' doesn't allow null.
(x) {                                                                                                                                              
^
```
`Dart VM version: 2.9.0-20.0.dev (dev) (Wed Jul 1 11:29:16 2020 +0200) on "windows_x64"`

@eernstg please clarify what is an expected behavior here

**Comment by sgrekhov** [comment]
See also https://github.com/dart-lang/sdk/issues/39476

**Comment by eernstg** [comment]
Blocked on https://github.com/dart-lang/language/issues/1063: the current specification makes the function literal an error,  and I'm proposing that we keep it like that even though it means that the analyzer will reject more programs.

**Comment by mit-mit** [comment]
@eernstg did we determine what the right behavoir is?

**Comment by eernstg** [comment]
Yes, when the end of a function with inferred return type can be reached (and `null` is implicitly returned), the inferred return type is made nullable and there is no error.

Implementation issue for CFE, https://github.com/dart-lang/sdk/issues/42743, is closed. The analyzer already did this.
