### ISSUE TITLE
WebGLRenderingContext pixelStorei second param should be Dynamic

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#4258]
Currently, the second param is an int

See http://api.dartlang.org/html/WebGLRenderingContext.html#pixelStorei

However, according to http://www.khronos.org/registry/webgl/specs/1.0/#PIXEL_STORAGE_PARAMETERS the second param can be a boolean or an unsigned long.

**Comment by terrylucas** [comment]
The IDL defines as:

    void pixelStorei(GLenum pname, GLint param);

Both are ints

The 2nd value can behave as a boolean zero is false. Any non-zero value is interpreted as true.

I don't think there's anything we have to do here.
