### ISSUE TITLE
NNBD: Dart does not throw a compile error when checks least and greatest closures

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42580]
Dart VM version: 2.9.0-20.0.dev (dev) (Wed Jul 1 11:29:16 2020 +0200) on "windows_x64"

This issue is similar with the Issue #42579, but affects static check of the least and greatest closures.

Here is a sample code example according to the [co19 Issue #575 evaluation](https://github.com/dart-lang/co19/issues/575#issuecomment-613542349):
``` dart
X captureTypeArgument<X>() => throw "OK";

abstract class C<X> {
  X get x;
  set x(X value);
}

void main() {
  void f<X>(C<X> Function() g) => g();
  f(() => captureTypeArgument()..x?.unknownMember);
}
```

Analyzer throws a compile error here.

Seems like dart should throw a compile error too, however it does not happen and runtime exception gets thrown here instead.

 Sample output is:
> $> dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error - The getter 'unknownMember' isn't defined for the type 'Object'. - test.dart:10:37 - undefined_getter
> 1 error found.
> 
> $> dart --enable-experiment=non-nullable test.dart
> Unhandled exception:
> OK
> #0      captureTypeArgument (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/test.dart:1:31)
> #1      main.<anonymous closure> (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/test.dart:10:11)
> #2      main.f (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/test.dart:9:36)
> #3      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/test.dart:10:4)
> #4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
> #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by johnniwinther** [comment]
cc @stefantsov

**Comment by johnniwinther** [comment]
Closed by https://dart-review.googlesource.com/c/sdk/+/156240
