### ISSUE TITLE
Instruction for building the Dart SDK on Linux are outdated

### ISSUE THREAD

**Issue by buergerling** [dart-lang/sdk#42588]
The Instructions for building the Dart SDK on Linux that can be found in https://github.com/dart-lang/sdk/wiki/Building seem to be outdated. The main problem seems to be that gn cannot be found. But there are more problems ...

Please try to build it according to these instructions. You will see what the problem is.

**Comment by mraleph** [comment]
- Do you have `depot_tools` installed? 
- How did you get Dart SDK sources (e.g. did you do `fetch dart`?)

If you follow instructions precisely as they are written then you should get `depot_tools` `gn` wrapper in your `PATH` (can be checked with `which gn`) as well as `gn` binary in `buildtools/gn` in the root directory of the SDK checkout. 

```console
$ which gn
.../tools/depot_tools/gn
$ which fetch
.../tools/depot_tools/fetch
$ mkdir temp
$ cd temp
$ fetch dart
Running: gclient root
...
Syncing projects: 100% (97/97), done.
...
Running hooks: 100% (10/10), done.
$ cd sdk
$ file buildtools/gn
buildtools/gn: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[xxHash]=cc455d8db8098d21, stripped 
$ tools/gn.py -a x64 -m release
$ tools/build.py -a x64 -m release create_sdk
... building ...
```

**Comment by buergerling** [comment]
From a technical point of view, this procedure works. 

```
$ virtualenv .env -p python2
$ source .env/bin/activate
$ sudo apt-get install g++-multilib git python curl
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ export PATH="$PATH:$PWD/depot_tools"
$ mkdir buildDart
$ cd buildDart/
$ virtualenv .env -p python2
$ source .env/bin/activate
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ export PATH="$PATH:$PWD/depot_tools"
(.env)  ... $ mkdir dart-sdk
(.env)  ... $ cd dart-sdk
(.env)  ... $ fetch dart
(.env)  ... $ which gn
(.env)  ... $ which fetch
(.env)  ... $ cd sdk/
(.env)  ... /sdk$ file buildtools/gn 
(.env)  ... /sdk$ tools/gn.py -a x64 -m release 
(.env)  ... /sdk$ tools/build.py -a x64 -m release create_sdk
```
However, a user looking for instructions may start with the instructions after downloading the SDK as zip from github. In order to make things clear early on, it would be useful to include a note at the beginning of the instruction that the described build process is not applicable to an unzipped archive.  

Finally, it is difficult to realize that one needs ~ 10 GB of data in order to get a tool that maps dart code to javascript code.

**Comment by mraleph** [comment]
> it would be useful to include a note at the beginning of the instruction that the described build process is not applicable to an unzipped archive.

Added a note.
