### ISSUE TITLE
getCpuSamples has zero samples list length in debug mode

### ISSUE THREAD

**Issue by arturk** [dart-lang/sdk#42591]
https://github.com/dart-lang/sdk/blob/5d1fbe049755a77d59f8b07dc441d067b1d3cd2e/pkg/vm_service/test/get_cpu_samples_rpc_test.dart#L27

I am writing profiling tests for the app in android emulator.
Connection to the app happens in this code
```
    String vmUrl = Platform.environment['VM_SERVICE_URL'].replaceFirst(new RegExp(r'http:'), 'ws:') + "ws";
    driver = await FlutterDriver.connect(printCommunication: true).timeout(appConnectTimeout);
    await driver.waitUntilNoTransientCallbacks();
    vms = await vmServiceConnectUri(vmUrl);
    expect((await vms.setFlag("profiler", "true")), isA<vm_service.Success>());
```
Emulator runs debug version of the app.
Later in test tear down I have this code:
`vm_service.CpuSamples cpuSamples = await vms.getCpuSamples(isolate.id, startTime, endTime);`
Here startTime and endTime are the test start and end times as `DateTime.now().microsecondsSinceEpoch`.
In cpuSamples I have a populated list of functions after the getCpuSamples call is returned. But I have samples list equal to 0. Is it so that this call is not capable to get the samples list from debug build and only profile build is necessary? I cannot test this as I don't have physical device at the moment. But can you please enable these events in debug build also if this is the case? Sometime people just need to create profiling tests before running those on real devices so I think profiling mode for this call should be totally right place to use.

**Comment by mraleph** [comment]
It would be great if you could provide a runnable example so that we could reproduce the problem on our end with exactly the code you are trying to run. You could make a driver test for hello world flutter application and add your custom profiling logic to it.

I would like to note that debug and profile/release builds might have drastically different profiles for a couple of reasons:

- debug is JIT, while profile/release is AOT 
- debug has assertions enabled (some a very expensive!)

Also collecting profiles on emulator has questionable utility. 

So overall I’d say if you want something useful then you should be collecting profiles from profile builds. 

/cc @bkonyi FYI

**Comment by arturk** [comment]
@mraleph @bkonyi 
I tried to recreate the test using some random app from the samples in github, I've also added flutter driver extensions to it and packaged into the apk. The prepared apk, test file, run script are here:
https://github.com/arturk/dart-temp-test
You need to have active emulator or android device in order to execute the run_tests.sh (it should install and start app, get observatory url, forward port and run the test automatically).
BUT with this small test example I was not able to recreate the issue. I've used same test script that I am using in our environment but with this apk sample I was able to retrieve the cpu samples successfully. While in our real test env I have only cpuSamples.functions populated and cpuSamples.samples remains empty.
Maybe you can give me a suggestion here on where to look next?

P.S.:
I understand that profiling must be done with profile mode binary and I will use it when I will finish creating the test. But while I am creating tests I still want to work with emulator which does not allow using --profile mode as it is only for real devices.

**Comment by arturk** [comment]
Also are there any plans to add import capabilities to the observatory? Like if I dump CPU, memory, source coverage, etc, using the VmService I would like to feed this information into offline observatory and be able to view the results same way as with live app after the app was executed for example during night tests.

**Comment by arturk** [comment]
Small update. We use Python+Appium to launch the app on the device. Apparently it has something to do with that. If I just launch the app and run dart test then cpu samples are collected. If I do the full test flow which start app using Appium then getCpuSamples does not populate samples part

**Comment by arturk** [comment]
Small update. After preparing test sample for you in the above comment now my real test perfectly capable of collecting the cpu samples. It just started working. No code changes were done to it. I don't know what was causing it in the device cache but now the problem is gone.

**Comment by mraleph** [comment]
Based on the last comment I assume this is resolved. Let us know if you start hitting this again.
