### ISSUE TITLE
Dart command tool should include Windows targeting manifest

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#42598]
Per this doc:
   https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1

Windows apps that support Windows 8.1 or above should include an application manifest to indicate their support. Individual apps cannot presently demonstrate this support from Dart, as far as I can tell, since the Dart linker doesn't provide a way for applications to include assembly manifest resources.

As a result, Windows API calls will result in legacy behavior where there is a difference between Windows 7 or Windows 10. This also makes it hard for apps to consume newer APIs in certain places (for example, the modern MessageBox equivalent [TaskDialog](https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-taskdialog) is not accessible without an assembly manifest.

We should link a manifest into dart.exe and the executables dart2native produces.

**Comment by rmacnak-google** [comment]
6cec462d24ad9ef817f666a4f3e9b5bc3bdba8ad
