### ISSUE TITLE
Parser treats `void Function()` as function parameter

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#42609]
Example:
```dart
foo(void Function()) {}
main() {
 foo(() => 42);
}
```
The declaration of `foo` should parse `void Function()` as a function type, and then complain that there is no identifier.
Instead the analyzer warns that:
```
Name non-constant identifiers using lowerCamelCase - line 1
```
and it's possible to call `foo`. It seems like the parameter is parsed as a function parameter named `Function`, which can be verified by adding `print(Function)` to the body of `foo` and running the code.

The parsing rule is that whenever `Function` is followed by `(` or `<`, then it is not parsed as an *identifier*, but instead it must be parsed as the "function type syntax".

@eernstg

**Comment by eernstg** [comment]
I did write the following in [`docs/language/informal/generic-function-type-alias.md`](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generic-function-type-alias.md):

```
The modification of the rule for the nonterminal `type` causes parsing
ambiguities. The following disambiguation rule applies:
If the parser is at a location L where the tokens starting
at L may be a `type` or some other construct (e.g., in the body of a
method, when parsing something that may be a statement and may also be a
declaration), the parser must commit to parsing a `type` if it
is looking at the identifier `Function` followed by `<` or `(`, or it
is looking at a `type` followed by the identifier `Function` followed by `<`
or `(`.
```

However, that rule did not survive the reviews when that feature spec was integrated into the language specification. Maybe we should add it now?

**Comment by lrhn** [comment]
So this is actually not a bug, it's implementing the spec as written?

In that case, I don't think we should require anyone to do more work, unless the implementations *want* us to make that change.
