### ISSUE TITLE
New unawaited annotation in meta package conflicts with the one from test_api

### ISSUE THREAD

**Issue by aaronlademann-wf** [dart-lang/sdk#42604]
Using `meta ^1.2.0`, the following error occurs when precompiling the `test` package in our CI builds:

```
Failed to precompile test:test:
/root/.pub-cache/hosted/pub.dartlang.org/test_core-0.3.7/lib/test_core.dart:69:5: Error: 'unawaited' is imported from both 'package:meta/meta.dart' and 'package:test_api/src/utils.dart'.
unawaited(Future.error('Dummy exception to set exit code.'));
^^^^^^^^^
```

**Comment by whesse** [comment]
Already fixed in https://github.com/dart-lang/test/pull/1290.

If this problem is in your own packages, you can require package:test at least 1.15.2

The copy of package test in the SDK source repository has already been updated to this version.
