### ISSUE TITLE
Failures on [dart2js] Support conversion of local function type variables from K to J model

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#42608]
There are new test failures on [[dart2js] Support conversion of local function type variables from K to J model](https://dart-review.googlesource.com/c/sdk/+/153080).

The tests
```
language/nnbd/normalization/type_object_normalization_test RuntimeError (expected Pass)
language/nnbd/normalization/type_object_normalization_weak_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-weak-linux-x64-d8
```

**Comment by fishythefish** [comment]
These should also be fixed by https://dart-review.googlesource.com/c/sdk/+/153386.
