### ISSUE TITLE
Analyzer false negative with async* functions + generic classes

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#42616]
I found a scenario where the analyzer/IDE doesn't report any error on a code that doesn't compile, when using a generic class + async* functions.

Here's a snippet showing the bug:

```dart
class Generic<T> {
  Generic(this.cb);
  final Stream<T> Function() cb;
}

final shouldReportAnError = Generic<String>(() async* {
  yield 42;
});
```

In this snippet, we assigned `Stream<int> Function()` to `Stream<String> Function()` – which isn't valid. But the analyzer doesn't complain.

The code properly does not compile, but `dart analyze` and the IDE report no errors.

```
Dart SDK version: 2.9.0-20.0.dev.flutter-8afe9875a6 (be) (Thu Jul 2 04:17:09 2020 +0000) on "macos_x64"
```

**Comment by srawlins** [comment]
Still an issue at head.

**Comment by srawlins** [comment]
Analyzer now reports:

> A yielded value of type 'int' must be assignable to 'String'.
