### ISSUE TITLE
Failures when rolling migrated `meta` package into flutter 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#42611]
See https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8875484204299041760/+/steps/build_host_profile_unopt/0/stdout

**Comment by jakemac53** [comment]
My assumption is that the failing target is not passing in a package_config.json file, which we ran into a similar issue with for package:collection.

A package_config.json file will need to be generated and passed.

**Comment by jakemac53** [comment]
See https://github.com/flutter/engine/pull/19428 for how this was fixed in the past.

**Comment by bwilkerson** [comment]
For ease of reference, the failing target is
```
[5826/5831] ACTION //flutter/tools/const_finder:const_finder_dill(//build/toolchain/linux:clang_x64)
FAILED: gen/flutter/tools/const_finder/const_finder.dart.dill 
python ../../third_party/dart/build/gn_run_binary.py compiled_action /b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dart --depfile=/b/s/w/ir/cache/builder/src/out/host_profile_unopt/gen/flutter/tools/const_finder/const_finder.dart.dill.d --depfile_output_filename=gen/flutter/tools/const_finder/const_finder.dart.dill --dfe=/b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/gen_kernel.dart --packages=/b/s/w/ir/cache/builder/src/flutter/tools/const_finder/.packages --platform=/b/s/w/ir/cache/builder/src/out/host_profile_unopt/vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=/b/s/w/ir/cache/builder/src/out/host_profile_unopt/gen/flutter/tools/const_finder/const_finder.dart.dill /b/s/w/ir/cache/builder/src/flutter/tools/const_finder/bin/main.dart
Command failed: /b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dart --depfile=/b/s/w/ir/cache/builder/src/out/host_profile_unopt/gen/flutter/tools/const_finder/const_finder.dart.dill.d --depfile_output_filename=gen/flutter/tools/const_finder/const_finder.dart.dill --dfe=/b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/gen_kernel.dart --packages=/b/s/w/ir/cache/builder/src/flutter/tools/const_finder/.packages --platform=/b/s/w/ir/cache/builder/src/out/host_profile_unopt/vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=/b/s/w/ir/cache/builder/src/out/host_profile_unopt/gen/flutter/tools/const_finder/const_finder.dart.dill /b/s/w/ir/cache/builder/src/flutter/tools/const_finder/bin/main.dart
output: ../../third_party/dart/pkg/meta/lib/meta.dart:288:28: Error: Null safety features are disabled for this library.
Try removing the `@dart=` annotation or setting the language version higher.
void unawaited(Future<void>? future) {}
```

@jonahwilliams I don't know anything about flutter/engine, so I'm guessing here, but at this point our best guess is that we might have a similar issue to the one you fixed for `package:collection` in which the `package_config.json` file that enables nnbd is missing.

Any information you can provide to help me figure out how to resolve this issue would be greatly appreciated.

Also, is there any way to solve the problem more generally so that all targets generate a `package_config.json` file? This issue is likely to come up repeatedly as packages are converted, and it would be useful to address them all at once rather than one at a time if that's possible.

**Comment by jonahwilliams** [comment]
Will take a look shortly. I didn't see this package in the runhooks generation so it is possible that it is using a handwritten packages file

**Comment by bwilkerson** [comment]
In case it's useful information, `package:meta` doesn't have any dependencies (normal or dev), so the `.packages` file would only have contained a self reference.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/19576

**Comment by bwilkerson** [comment]
Wow, that was fast. Thanks!

**Comment by jonahwilliams** [comment]
Change has landed. I'll look at the rest of our dart rules that are using .packages today so that this doesn't come up in the future

**Comment by vsmenon** [comment]
@jakemac53 - is this obsolete now?
