### ISSUE TITLE
Dart migrate crashes with 'too many elements'

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#42613]
Attempting to migrate https://github.com/timsneath/win32: 

```
[C:\src\win32] dart migrate --skip-pub-outdated               
Migrating C:\src\win32

Generating migration suggestions...
Bad state: Too many elements
#0      List.single (dart:core-patch/growable_array.dart:237:5)
#1      MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:378:38)
#2      MigrationCli.run.<anonymous closure> (package:nnbd_migration/migration_cli.dart:372:67)
#3      MigrationCli._withProgress (package:nnbd_migration/migration_cli.dart:627:21)
#4      MigrationCli.run (package:nnbd_migration/migration_cli.dart:371:11)
#5      MigrateCommand.run (package:nnbd_migration/migration_cli.dart:205:15)
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      DartdevRunner.runCommand (package:dartdev/dartdev.dart:62:24)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:222:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:14:35)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## Dart version
```
Dart VM version: 2.9.0-13.0.dev (dev) (Fri May 29 15:59:05 2020 +0200) on "windows_x64"
```

**Comment by lrhn** [comment]
`Bad state: Too many elements` suggests someone using `.single` or `.singleWhere` on an iterable with more than one (matching) element.

The lines numbers do not match the current `migration_cli.dart` file (and it has no `_withProgress` method at all), so this might be from an older version.

**Comment by timsneath** [comment]
Thanks Lasse. This is from the Dart SDK checked into Flutter master; so a
version at least this old will be in this month’s stable release. Flagging
@mit-mit.

**Comment by mit-mit** [comment]
@timsneath did you mean flutter **master**? In my flutter master I see:
```
C:\Users\mit\tmp\win32>dart --version
Dart SDK version: 2.9.0-20.0.dev.flutter-69aba23371 (be) (Sun Jul 5 16:44:59 2020 +0000) on "windows_x64"
```

And, just tried to clone your repo, and the migration tool seems to work.

**Comment by timsneath** [comment]
Hmmm. Ok, checking: looks like I must have got a stale Dart in my path
somehow.

**Comment by mit-mit** [comment]
Yes, you should see:

```
C:\Users\mit\tmp\win32>where dart
C:\Users\mit\dev\flutter\bin\dart
C:\Users\mit\dev\flutter\bin\dart.bat
```

**Comment by timsneath** [comment]
Damn, yeah -- that was it :( I've been running flutter upgrade almost
religiously every day on this machine, but I also have 32-bit and 64-bit
versions of Dart so I can test my FFI stuff on both architectures without
changing commands.

[C:\src\win32] where dart
C:\tools\dart64\bin\dart.exe
C:\tools\flutter\bin\dart
C:\tools\flutter\bin\dart.bat

OK, false alarm. Apologies.

**Comment by mit-mit** [comment]
I had a similar issue myself earlier, which is the reason why I suspected that is what was going on :-)

Since then I've started having only the Flutter SDK in path, and then I use aliases for other SDKs (like `alias dartbeta="~/sdk/beta/dart-sdk/bin/dart`) and leave them out of path.
