### ISSUE TITLE
Mixing nullable cast with cascades yields invalid code?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42621]
This is on `2.9.0-20.0.dev`

This code is fine
```dart
Order jsonThing(Map<String, dynamic> json) {
  return Order()
    ..items = json['items'] as List
    ..price = json['price'] as int;
}

class Order {
  List? items;
  int? price;
}
```

But adding the cast to `List?` – see below

```dart
Order jsonThing(Map<String, dynamic> json) {
  return Order()
    ..items = json['items'] as List?
    ..price = json['price'] as int;
}
```

yields...

The work around is easy – wrap the whole in `()` – but it seems...weird

```
error: Conditions must have a static type of 'bool'. (non_bool_condition at [json_serializable] example/example.dart:26)
error: A value of type 'dynamic' can't be assigned to a variable of type 'List<dynamic>?'. (invalid_assignment at [json_serializable] example/example.dart:26)
error: Expected to find ':'. (expected_token at [json_serializable] example/example.dart:27)
error: Expected an identifier. (missing_identifier at [json_serializable] example/example.dart:27)
```

**Comment by kevmoo** [comment]
FYI – this is fine

```dart
Order jsonThing(Map<String, dynamic> json) {
  return Order()
    ..items = json['items'] as List?;
}
```

So it's just the cascade that messes things up.

Is this more a CFE issue than an analyzer issue?

**Comment by stereotype441** [comment]
Does it work under the VM?  If so, then it's almost certainly an analyzer issue.  If the VM also reports issues, then it's probably a parser issue and belongs in CFE.

**Comment by bwilkerson** [comment]
I believe that `expected_token` and `missing_identifier` are both being reported by the parser.

**Comment by kevmoo** [comment]
Running in the VM

```
issue_fun.dart:10:5: Error: Expected an identifier, but got '..'.
    ..price = 42;
    ^^
issue_fun.dart:10:5: Error: Expected ':' before this.
    ..price = 42;
    ^^
issue_fun.dart:9:29: Error: A value of type 'List<dynamic>' can't be assigned to a variable of type 'bool'.
 - 'List' is from 'dart:core'.
    ..items = json['items'] as List?
                            ^
```

@stereotype441 – seems a CFE issue then – we agree this is a bug?

**Comment by stereotype441** [comment]
> @stereotype441 – seems a CFE issue then – we agree this is a bug?

Agreed that this is a bug.  Unless there's some grammatical subtlety I'm not aware of, your code definitely should be accepted by the parser.

**Comment by eernstg** [comment]
The grammar does allow a `<typeCast>` like `as List` to be used in a cascade like `Order()..items = json['items'] as List`. It's only required that the part after `=` is an `<expressionWithoutCascade>`, and that derives almost all expressions, including this one.

**Comment by jensjoha** [comment]
Will be fixed with https://dart-review.googlesource.com/c/sdk/+/153773.
