### ISSUE TITLE
Wrong documentation for Iterable.iterator

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42623]
`Iterable.iterator` documentation reads
https://github.com/dart-lang/sdk/blob/05003ab60d4f015b4eee30e29940201fad87f99c/sdk/lib/core/iterable.dart#L139-L140

This is not true if iterator instance is created by `Iterator.empty()`. In this case instance of `EmptyIterable` is returned which doesn't create a new object each time
https://github.com/dart-lang/sdk/blob/05003ab60d4f015b4eee30e29940201fad87f99c/sdk/lib/internal/iterable.dart#L692

**Comment by lrhn** [comment]
The important part is that each returned iterator will start a new iteration from the start if the elements. 

It's technically true that it's not a new instance here, and the documentation could probably be tweaked to not say that.
If we do that, we should be very careful to not make the documentation harder to understand for all the other cases.
