### ISSUE TITLE
Analyzer falsely reports incompatible Mixins in No-Sound mode

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#42624]
The analyzer and compiler do not agree on what mixins are allowed when running with `--no-sound-null-safety`.

```
Dart 2.9.0 (build 2.9.0-20.0.dev 69aba23371)
```

The analyzer says that the following is an error:

```dart
class _ExampleState extends State<Example> with SingleTickerProviderStateMixin<Example>, _ExampleMixin {}

mixin _ExampleMixin on State<Example> {}
```

```
Type parameters couldn't be inferred for the mixin '_ExampleMixin' because the base class implements the mixin's supertype constraint 'State<Example>' in multiple conflicting ways.
```

It obviously compiles fine. When reversing some of it, is it exactly the other way around.

I encountered a lot of these issues with mixins, e.g. also that implicit mixins do not work when working with non-migrated code:

```dart
class _ExampleState extends State<Example> with SingleTickerProviderStateMixin {}
```

**Comment by srawlins** [comment]
Unsound mode is no longer supported.
