### ISSUE TITLE
Implement null safe numbers in the analyzer

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42629]
This is the analyzer implementation issue for https://github.com/dart-lang/language/issues/1078.  See that issue for details.

**Comment by stereotype441** [comment]
FYI @scheglov.  I've begun prototyping analyzer support for this, so I'm assuming I'll finish out the implementation.  But I'm happy to split up the work with you if you'd prefer.

**Comment by scheglov** [comment]
SG, if you have time, sure, finish it :-)

**Comment by leafpetersen** [comment]
Any updates on this?

**Comment by stereotype441** [comment]
Not at the moment.  This week I am trying to focus on external and abstract fields.  I hope to return to this next week.

**Comment by stereotype441** [comment]
Fixed in 2cb426f9fcd0c9728ac99b1c160a90d0a18c579a.
