### ISSUE TITLE
[NNBD] Differences in weak mode on CFE and dart2js, dartk, dartdevk and dartkp for function types

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42648]
The following tests work on CFE (both weak and strong modes) but fail on dart2js, dartk, dartdevk and dartkp in a weak mode (work in a strong mode)

```dart
typedef t4(var v);

f34(Object a) {}

main() {
  Expect.isFalse(f34 is t4);
}
```
```dart
typedef int t3();

main() {
  Expect.isFalse(() {} is t3);
}
```
```dart
typedef Object returnsObject();

Map<int, List<List<List>>>? f16() {}

main() {
  Expect.isFalse(f16 is returnsObject);
}
```
```dart
class A {}
class A1 {}
class A2 {}
class B implements A, A1, A2 {}
class C implements B {}
class D implements C {}

typedef B t1(int i, B b, Map<int, num> m, var x, {
  required var ox, required B ob, required List<num> ol, required bool obool});

C f3(num i, A b, Map<Object, Object> m, var x, {
  required var ox, required extraParam, required A2 ob, required List ol, required Object obool}) => new C();

main() {
  Expect.isFalse(f3 is t1);
}
```

**Comment by eernstg** [comment]
This is a bit confusing. `f34 is t4` is true in weak mode (because `dynamic* <: Object*`), `() {} is t3` is true in week mode (because the inferred return type of the function literal is `Null`), `f16 is returnsObject` is true in weak mode (because `Map<...>* <: Object*`), and `f3 is t1` is true in weak mode (because of a bunch of subtype relationship holds, and `required` is ignored when checking subtype relationships in weak mode).

So it looks like dart2js and the other tools behave correctly, but "CFE" fails to report the errors in weak mode. So what does CFE mean in this context? Maybe the errors fail to arise simply because the CFE test is a compilation without execution?

**Comment by sgrekhov** [comment]
@eernstg thank you for clarification. It seems that you are right. I'll add //Requirements=nnbd-strong to these tests. As for CFE and weak mode I don't know if tryjobs run the tests in a weak mode or simply compiles. I just see that there are no failures in CFE weak mode and output contains the following (this is the test containig the first example)
```
{"name":"co19/Language/Types/Function_Types/subtype_required_args_t01","configuration":"analyzer-asserts-weak-linux","suite":"co19","test_name":"Language/Types/Function_Types/subtype_required_args_t01","time_ms":74,"result":"Pass","expected":"Pass","matches":true,"bot_name":"luci-dart-try-xenial-51-tbju","commit_hash":"refs/changes/153760/1","commit_time":1594258913,"build_number":"1843","builder_name":"analyzer-nnbd-linux-release-try","flaky":false,"previous_flaky":false,"previous_commit_hash":"e3a682480aad59de0de678856a2c968d8d6665d5","previous_commit_time":1594258913,"previous_build_number":"3674","changed":true}
```
Is there a way to run the tests locally in a weak mode?

**Comment by eernstg** [comment]
I think it should work to simply say it like `Expect.equals(isWeakMode, f34 is t4);` (where `isWeakMode` and `isStrongMode` are declared in expect.dart, so you may need to copy those declarations into Utils/expect_common.dart).

About execution: The configurations `cfe-strong-linux` and `cfe-weak-linux` do not run programs, they just compile them (cf. the `--verbose` output from a local `tools/test.py -n cfe-strong-linux ...`). So we have the explanation if that's what the trybot is running.

**Comment by sgrekhov** [comment]
Thank you. Closing this issue
