### ISSUE TITLE
jsonDecode with large data sets

### ISSUE THREAD

**Issue by snevetssirk** [dart-lang/sdk#42647]
the jsonDecode function fails on large data sets.

For example, when pulling data from a publicly available source, jsonDecode works when parsing the 673,043 byte output of:

'https://api.covid19api.com/country/united-states/status/confirmed/live?from=2020-06-01T00:00:00Z&to=2020-06-01T23:59:59Z'; 

but never returns when parsing the 2,019,199 byte output of the same API (for a larger date range):

https://api.covid19api.com/country/united-states/status/confirmed/live?from=2020-06-01T00:00:00Z&to=2020-06-03T23:59:59Z

Sample trivial program:

```
import 'dart:io';
import 'package:http/http.dart' as http;
import 'dart:convert';

Future main(List<String> arguments) async {
  await getCovidData();
  exit(1);
}

Future<List> getCovidData() async {
  try {
    /// change data size by varying the from/to dates in this api call
    /// three days of data will fail json parsing, two days will work.
    var query =
        'https://api.covid19api.com/country/united-states/status/confirmed/live?from=2020-06-01T00:00:00Z&to=2020-06-03T23:59:59Z';

    var results = await http.get(query);

    if (results.statusCode != 200) {
      return [];
    } else {
      return jsonDecode(results.body);
    }
  } catch (error) {
    //Todo
    return [];
  }
}
```

**Comment by lrhn** [comment]
The problem doesn't reproduce for me on tip-of-tree or version 2.9.0-21.0.dev.

Running the example program successfully fetches the text and decodes it in 50-60 milliseconds on my local Windows machine.

Can you tell us more about what you are doing (which platform, which SDK version)?

**Comment by snevetssirk** [comment]
> The problem doesn't reproduce for me on tip-of-tree or version 2.9.0-21.0.dev.
> 
> Running the example program successfully fetches the text and decodes it in 50-60 milliseconds on my local Windows machine.
> 
> Can you tell us more about what you are doing (which platform, which SDK version)?

The problem I reported happens when using 2.8.4 on Mac OS

I tried it on 2.9.0-21.0.dev and you're right jsonDecode comes back almost immediately even with a 40mb result set.

I won't close this yet in case you have other questions but certainly the problem seems to be resolved in the dev version of the SDK. Thanks for checking into it.

**Comment by snevetssirk** [comment]
I just discovered that the problem is with the integrated debugger in VS Code, and not with Dart at all.
