### ISSUE TITLE
Converting previously error diagnostics to warnings breaks several tests

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#42650]
See https://dart-ci.firebaseapp.com/cl/153742/1

language_2/super/setter_test
language_2/unsorted/index_assign_operator_infer_return_type_test

language/unsorted/index_assign_operator_infer_return_type_test

See also https://github.com/dart-lang/co19/issues/805

**Comment by eernstg** [comment]
Please note that I'm gathering support for changing several specified warnings to errors, in which case there is no need to change the analyzer in the opposite direction: https://github.com/dart-lang/language/issues/1012.

**Comment by scheglov** [comment]
OK, I will postpone landing my CL.
I started looking on issues because of our progress report for "NNBD regressions" in analyzer was not moving into the right direction :-)

**Comment by eernstg** [comment]
I hope I can soon make this move without any effort from you! ;-)

**Comment by scheglov** [comment]
OK, there is nothing to do here then.
