### ISSUE TITLE
[CP] Change `pub get` to remove output that advertizes prerelease null safety packages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#42657]
**What is the problem**: When `pub get` runs it resolves package versions that are compatible with the `pubspec.yaml`. If for any package resolved there is a more recent version on pub.dev, which the developer could upgrade their `pubspec.yaml` to use, then it prints a suggestion to do that.

We recently discovered that this logic also includes prerelease versions. This was not a problem before, as prerelease versions were rare, or only used in less commonly used packages. With the new core packages (collection, characters, typed_data, vector_math) migrated to null safety and published to pub.dev, any app or package depending on either of these will see output like this:

```
Resolving dependencies... (2.6s)
+ analyzer 0.39.12
+ args 1.6.0
...
+ collection 1.14.13 (1.15.0-nullsafety available)
...
```

**Why is this a problem**: The `-nullsafety` prerelease package versions are not intended for general consumption until no sooner than null safety beta. They have been published to unblock the migration of the Flutter framework (which gets it dependencies from pub.dev).

Showing these in the `pub get` output is very confusing to developers that are not yet using null safety. If they inadvertently follow the recommendation they will get very confusing failures:

```
[testapp] flutter pub get
Running "flutter pub get" in testapp...                         
Because every version of flutter_test from sdk depends on collection 1.14.13 and testapp depends on collection 1.15.0-nullsafety, flutter_test from sdk is forbidden.

So, because testapp depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because testapp depends on flutter_test any from sdk, version solving failed.)
```

**Fix to the problem**: Change `pub get` to never advertize prerelease versions of a package to someone who is using a stable version. This change was landed in https://github.com/dart-lang/pub/commit/36c195b94defbde355fe570a9d7563d85fb6e533. NOTE: The diff here looks very large, but note that the vast majority of the changes are in test files. The only change to product code is:

```
-      } else if (newerUnstable) {
+      } else if (
+          // Only show newer prereleases for versions where a prerelease is
+         // already chosen.
+          newId.version.isPreRelease && newerUnstable) {
```

**Risk**: Very low risk. This removes a small bit of status output, but there is no change to how the pub resolver works or what packages it resolves to.

**How does this improve the release**: With this fix we prevent that developers see the advertized null safety prerelease versions and will start to use them in their apps. This ensures that migration to null safety doesn't start before we want it to.

**Commit(s) to merge**: https://github.com/dart-lang/sdk/commit/66cb8a8ed841a3a245f07aa878de311e8c60988f

This is a DEPS roll that picks up *just* the change mentioned above: [git diff](https://github.com/dart-lang/pub/compare/6178cdf284baf2345d1ea578b7176a754aa576fe..85bdb898aeb2ac7cea76489ba0bf4e52ff7a79bf)

**Link to issue**: https://github.com/dart-lang/pub/issues/2555

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by kevmoo** [comment]
👍 💯  – we should absolutely do this!

**Comment by franklinyow** [comment]
Approved

**Comment by franklinyow** [comment]
@pcsosinski

**Comment by pcsosinski** [comment]
lgtm

**Comment by whesse** [comment]
Cherry-picked to 2.9.0-21.4.beta
