### ISSUE TITLE
DDC should return true for any check and allow casting between any JS type

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#42654]
dart2js treats `is` checks as essentially a no-op by returning true between JS types. Similarly, casting between any JS types is allowed. ddc currently does more intuitive type checking/casting for certain scenarios that naturally do not always return true or allow a cast. We'd like to make this behavior consistent between both compilers. It is possible that this work can be avoided if we add a static error disallowing the usage of these checks and casts, however.

For more context, see `tests/lib/js/is_check_and_as_cast_test.dart`. This test is currently marked as failing for ddc.

**Comment by srujzs** [comment]
cc @sigmundch @nshahan @Markzipan

**Comment by nshahan** [comment]
Is ddc failing some tests `is` checks or casts that are actually safe? I'm wondering if we should consider those cases bugs and fix them instead of the anything goes, always return true approach.

**Comment by srujzs** [comment]
ddc seems to be doing the intuitive things in the tested cases e.g. can't cast a JS type to another one if they're not related, so I don't think there's actually a "bug" there. It's just the expected behavior is inconsistent with dart2js, and I think the goal here is to avoid having people use checks and casts for JS types.

**Comment by srujzs** [comment]
This has landed as part of https://dart-review.googlesource.com/c/sdk/+/173140.
