### ISSUE TITLE
Poor recovery for extension methods with null safety enabled

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#42663]
Given a library that is opted in to null safety with the following code
```
class C {
}
extension E on C {
  int get g => 0;
}
void f(C? c) {
  print(c.g); // <-- diagnostics
}
```
There are two diagnostics produced at the commented line:
```
error: An expression whose value can be 'null' must be null-checked before it can be dereferenced. (unchecked_use_of_nullable_value at [nnbd_test_package] lib/test.dart:7)
error: The getter 'g' isn't defined for the type 'C?'. (undefined_getter at [nnbd_test_package] lib/test.dart:7)
```
In this particular case, fixing the first will fix the second, so there ought to be a single diagnostic.

However, the first diagnostic's message is less than ideal. Given that we can know that the user is trying to invoke an extension method, it would be better if that single diagnostic made it clear that the problem is a mismatch between the type of the expression `c` and the extended type `C`.

After this is fixed, we should add three fixes to server: one to change `.` to `?.`, one to change `.` to `!.` and one to change `C` to `C?` on the extension.

**Comment by davidmorgan** [comment]
Maybe the error message should be exactly the same as if you'd tried to call a normal method on a nullable type? i.e., prompting you to add '!' without mentioning that it's an extension method?

**Comment by srawlins** [comment]
There is now just one error:

> The property 'g' can't be unconditionally accessed because the receiver can be 'null'.
>
> Try making the access conditional (using '?.') or adding a null check to the target ('!').

OK to close?
