### ISSUE TITLE
Weird error when trying to execute a non-existent file with experiment enabled

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42664]
Reproduced with 57cf6ebbd5729782822f772e587e2c617973ede9

Observed behavior:
```
paulberry@paulberry-cloudtop:~/dart-new/sdk$ out/ReleaseX64/dart-sdk/bin/dart non_existent_file.dart
Error when reading 'non_existent_file.dart': No such file or directory.
paulberry@paulberry-cloudtop:~/dart-new/sdk$ out/ReleaseX64/dart-sdk/bin/dart --enable-experiment=non-nullable non_existent_file.dart
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
```

Expected behavior: I would expect to see the same `No such file or directory` message regardless of whether I supply the `--enable-experiment=non-nullable` flag.

**Comment by stereotype441** [comment]
@a-siva FYI

**Comment by simolus3** [comment]
I'm getting the same error for existing files when enabling the observatory.

To reproduce: 
```bash
echo "void main() { print(0); }" > test.dart
dart --enable-experiment=non-nullable --enable-vm-service:43847 test.dart
```

My Dart version is `Dart SDK version: 2.9.0-21.0.dev (dev) (Wed Jul 8 10:54:08 2020 +0200) on "linux_x64"`.

**Comment by bkonyi** [comment]
This will be resolved when [this CL](https://dart-review.googlesource.com/c/sdk/+/152588) is landed.

**Comment by bkonyi** [comment]
Resolved in https://github.com/dart-lang/sdk/commit/157ebfe50f399c59a20d603acdf5143ceaa4cccf
