### ISSUE TITLE
Extension applicability checks some times do not erase nullability in legacy context

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42660]
Thanks to David Morgan for noticing this. Consider the following program:

```dart
// ----- Library 'lib.dart'.
// @dart=2.9

extension E on int {
  String m() => 'm';
}

int? f() => 4;

// ----- Library 'main.dart'.
// @dart=2.8
import 'lib.dart';

void main() {
  f().m();
}
```

This program is accepted by the dartanalyzer (from 145d4585e7012aeba584d26d0a03c8fcadccdc0a), but rejected by `dart` (same commit), with the following message:

```
main.dart:5:7: Error: The method 'm' isn't defined for the class 'int'.
Try correcting the name to the name of an existing method, or defining a method named 'm'.
  f().m();
      ^
```

It seems likely that this error arises as follows: The function `f` is declared in a library with null-safety, so the type of `f()` in the legacy library should be obtained from the type `int?` by erasing the `?` and getting `int` (as if it had occurred in `main.dart`, so it means `int*`). That type should then be used to check the applicability of the extension. But, most likely, the front end does not erase the type, so it ends up checking applicability of the extension relative to a receiver type of `int?`, and fails.

It is not possible to use `!` in legacy code. Interestingly, `f()?.m()` is accepted (both by the analyzer and the CFE), but `?.` should not be subject to different static analysis in legacy code than a plain `.`, and in other cases (say, `C<int?>`) there would not be a way in the legacy code to write an expression with a type that matches the extension.

**Comment by lrhn** [comment]
The extension should apply.

```dart
var x = f();
if (x == null) return;
x.m();
```
It should be uncontested that the above legacy code *should* work. It's perfectly good null-safe (but not Null Safe) code, and there is no better way to write the same thing.

The type of `x` is not changed by the `null` test, so `x.m()` would have to apply before the `x==null` test too.
The type of `x` is the type of `f()`, so `f().m()` should also work.

The `f().m()` call might not be safe, but legacy code is not safe. Presumably the author knows that `f()` won't return `null` in this case, and they can't write `f()!.m()`, and don't have to, so `f().m()` should be a way to call `m`.
