### ISSUE TITLE
Bad patch file for `inspect` method from `dart:developer` in the vm

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#42676]
~The CFE does not allow nullable argument types to be passed for nullable parameters of external functions.~

The [vm patch file](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/developer.dart#L24) for the `inspect` method from `dart:developer` has the type `Object Function(Object)` instead of `Object? Function(Object?)`.

Repro program (must be opted in to nnbd):

```dart
import 'dart:developer';

void main() {
  int? x;
  inspect(x);
}
```

Results in:

```
lib/example.dart:5:11: Error: The argument type 'int?' can't be assigned to the parameter type 'Object'.
 - 'Object' is from 'dart:core'.
  inspect(x);
```

**Comment by jakemac53** [comment]
Actually it looks like this is caused by a bad patch file for the vm, https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/developer.dart#L24

**Comment by jakemac53** [comment]
I will take a shot at just updating the type, should be easy enough.

**Comment by franklinyow** [comment]
@jakemac53 fixed?
