### ISSUE TITLE
NNBD: Analyzer does not throw a compile error when checks least and greatest closures for the function with required non-nullable parameter

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42682]
Dart SDK version: 2.9.0-21.0.dev (dev) (Wed Jul 8 10:54:08 2020 +0200) on "windows_x64"

Here is a sample code example according to the [co19 Issue #575 evaluation](https://github.com/dart-lang/co19/issues/575#issuecomment-613542349) (static case for the `Function` type):
``` dart
Type? _capturedTypeArgument;

X captureTypeArgument<X>() {
  _capturedTypeArgument = X;
  throw 1;
}

typedef check = void Function({bool x});

void main() {
  void f(check Function() g) => g();
  f(() => captureTypeArgument()..call());   /// compile error should be thrown here
}
```
`bool x` is a required non-nullable function parameter, so it seems like it should be clearly set when the function is called and compile error should be thrown if this is not so. 

However this does not happen, analyzer passes with the `The declaration '_capturedTypeArgument' isn't referenced. - test.dart:1:7 - unused_element` hint instead here.

**Comment by eernstg** [comment]
Same situation as #42683.
