### ISSUE TITLE
NNBD: Dart does not throw a compile error when checks least and greatest closures for the function with required or optional non-nullable parameter

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42683]
Dart SDK version: 2.9.0-21.0.dev (dev) (Wed Jul 8 10:54:08 2020 +0200) on "windows_x64"

This issue is similar with the Issue #42682, but it's against dart whereas #42682 is against the analyzer.

Here is a sample code example according to the [co19 Issue #575 evaluation](https://github.com/dart-lang/co19/issues/575#issuecomment-613542349) (static case for the `Function` type):
``` dart
Type? _capturedTypeArgument;

X captureTypeArgument<X>() {
  _capturedTypeArgument = X;
  throw 1;
}

typedef check = void Function({bool x});

void main() {
  void f(check Function() g) => g();
  f(() => captureTypeArgument()..call());   /// compile error should be thrown here
}
```
`bool x` is a required non-nullable function parameter, so it seems like it should be clearly set when the function is called and compile error should be thrown if this is not so. 

However this does not happen, dart throws a runtime exception instead here.

Sample output is:

> $> dart --enable-experiment=non-nullable test.dart
> Unhandled exception:
> 1
> #0      captureTypeArgument (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/Least-greatest-closure/typedef/test.dart:5:3)
> #1      main.<anonymous closure> (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/Least-greatest-closure/typedef/test.dart:12:11)
> #2      main.f (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/Least-greatest-closure/typedef/test.dart:11:34)
> #3      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/nnbd/Least-greatest-closure/typedef/test.dart:12:4)
> #4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
> #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
>

**Comment by eernstg** [comment]
We need to have `required` on `bool b` in order to express the requirement that the parameter is required. As long as this is not true we won't get a compile-time error at `call`.
