### ISSUE TITLE
Analyzer: Remove error for library name clash

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42699]
The analyzer reports an error for the following situation:

```dart
// Library 'lib1.dart'.
library clashing.nonempty.name;

// Library 'lib2.dart'.
library clashing.nonempty.name;

// Library 'main.dart'.
import 'lib1.dart';
import 'lib2.dart';

void main() {}
```

This was specified as a warning, but was removed from the language specification in dart-lang/language#1083, so the analyzer should no more report this error, with or without null-safety.

**Comment by eernstg** [comment]
@johnniwinther found an extra error which is very similar. Cf. https://github.com/dart-lang/language/pull/1096.

**Comment by eernstg** [comment]
dart-lang/language#1096 has now been landed, so the error for library name clashes in exports should also be eliminated.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/154540

**Comment by scheglov** [comment]
I opened a new co19 issue https://github.com/dart-lang/co19/issues/837
