### ISSUE TITLE
Unexpected compile time errors for language/operator/number_operator tests

### ISSUE THREAD

**Issue by rileyporter** [dart-lang/sdk#42695]
There are compile time errors for these new tests for ddc in strong and weak mode:
```
operator/number_operator_typing_test
operator/number_operator_context_test
```

The test failures were approved on [Add test for new numeric operator typing rules.](https://dart-review.googlesource.com/c/sdk/+/153200)

@lrhn are these expected failures? It looks like these tests are new, so is this a new feature that is not supported yet? Is there a tracking bug for that work that I can link to for these failures?

Failure logs:

https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/3979/language/operator/number_operator_typing_test

https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/3979/language/operator/number_operator_context_test

**Comment by johnniwinther** [comment]
The CFE issue implementing the new rules is #42577

**Comment by lrhn** [comment]
As Johnni says, these are tests for new behavior, and they are expected to fail until that behavior is implemented.

**Comment by rileyporter** [comment]
Perfect, thanks!
