### ISSUE TITLE
Flutter/VSCode/Dart : unused_field and unused_element errors for private fields in classes

### ISSUE THREAD

**Issue by vin-fandemand** [dart-lang/sdk#42690]
**Describe the issue**
Consider the following snippet
```
class TestClass {
  final String field;
  String _field;

  TestClass(this.field);

  void method() {
    _field = '';
  }
}
```
The private field `_field` is not detected as being used although it is being used inside one of the methods. I have seen it quite often when I develop in Flutter where I often initialize a private field inside an `initState` method for a `StatefulWidget`. Is this a bug or am I not understanding it correctly?
![image](https://user-images.githubusercontent.com/64597233/87196444-0157cb00-c2c8-11ea-875d-633be2868168.png)

**To Reproduce**
```
class TestClass {
  final String field;
  String _field;

  TestClass(this.field);

  void method() {
    _field = '';
  }
}
```

**Expected behavior**
The private field is used in the methods. So ideally shouldn't show as unused.

**Additional context**
https://github.com/Dart-Code/Dart-Code/issues/2630

**Comment by srawlins** [comment]
It is not being used. It is only being assigned to.

**Comment by vin-fandemand** [comment]
> It is not being used. It is only being assigned to.

Sorry, I don't see the difference. Can you please explain? 

Being assigned to is also use correct? If we follow the rule and remove the field, the program would fail to compile. I feel that is misleading.

**Comment by srawlins** [comment]
The goal of the hint is to indicate code which is not used, and can therefore be removed without changing the behavior of the code. So if you remove the field (and any assignments), the behavior doesn't change. Such a field serves no purpose, and may be leading to bloat. Removing the field may allow an import to be removed, a pub dependency to be removed, etc.

Sometimes the RHS of such an assignment has side effects, so perhaps that should remain. For example:

```dart
class C {
  final int _x;
  C() : this._x = sideEffect();

  static int sideEffect() {
    print('something');
    return 1;
  }
}
```

Removing _x and its assignment would change the behavior by no longer printing, so the RHS would have to remain, and a bit of rearranging:

```dart
class C {
  C() {
    sideEffect();
  }

  static int sideEffect() {
    print('something');
    return 1;
  }
}
```

**Comment by mkustermann** [comment]
@vin-fandemand I suppose the analyzer is working as intended here. If you prefer not seeing this warning, you may consider disabling the `unused_field` hint in your analysis options.

Should this issue be closed with working-as-intended ?

**Comment by vin-fandemand** [comment]
Yes please, thanks for the clarification.
