### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by snmn** [dart-lang/sdk#42697]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.9.0-8.2.beta`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.9.0-8.2.beta, server version 1.27.4, FATAL error:
```

For additional log information, please append the contents of
file://C:\Users\seaso\AppData\Local\Temp\report.txt.

**Comment by mkustermann** [comment]
@snmn Could you provide us with more information, e.g. what is in the mentioned error log?
