### ISSUE TITLE
Missing Compile time errors in co19/Language/Generics/Superbounded_types

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42692]
The following tests are missing compile time errors in sound and weak modes.

co19/Language/Generics/Superbounded_types/class_A01_t06/02
co19/Language/Generics/Superbounded_types/class_A01_t06/01
co19/Language/Generics/Superbounded_types/class_A01_t04/02
co19/Language/Generics/Superbounded_types/class_A01_t04/01
co19/Language/Generics/Superbounded_types/class_A01_t01/02
co19/Language/Generics/Superbounded_types/class_A01_t01/01

During the migration these were turned into multi-tests.

**Comment by eernstg** [comment]
The problem is that `Object` is not a top type any more, so `A<Object>` is an error (it is not a correctly super-bounded type), and that error is not reported.

**Comment by johnniwinther** [comment]
This has been fixed.
