### ISSUE TITLE
Flow analysis - reachability test failures

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42693]
~~The following tests are missing compile time errors in sound mode:~~
The following tests are generating unexpected compile time errors in sound mode:
```
LanguageFeatures/nnbd/flow-analysis/reachability_A07_t10
LanguageFeatures/nnbd/flow-analysis/reachability_A07_t09
LanguageFeatures/nnbd/flow-analysis/reachability_A07_t06
LanguageFeatures/nnbd/flow-analysis/reachability_A07_t05
LanguageFeatures/nnbd/flow-analysis/reachability_A06_t02
LanguageFeatures/nnbd/flow-analysis/reachability_A05_t06
LanguageFeatures/nnbd/flow-analysis/reachability_A05_t04
LanguageFeatures/nnbd/flow-analysis/reachability_A05_t02
LanguageFeatures/nnbd/flow-analysis/reachability_A04_t02
LanguageFeatures/nnbd/flow-analysis/reachability_A01_t09
LanguageFeatures/nnbd/flow-analysis/reachability_A01_t07
LanguageFeatures/nnbd/flow-analysis/reachability_A01_t06
LanguageFeatures/nnbd/flow-analysis/reachability_A01_t04
```

Related flow analysis discussions are possibly still ongoing for the analyzer:
https://github.com/dart-lang/sdk/issues/42232
https://github.com/dart-lang/sdk/issues/42193

I'm not sure if this is now shared code between the CFE and analzyer.

**Comment by leafpetersen** [comment]
Discussion is happening on https://github.com/dart-lang/sdk/issues/42232 , closing this in favor of that issue.

**Comment by franklinyow** [comment]
Close as dup
