### ISSUE TITLE
Bug using Dart API with double value.

### ISSUE THREAD

**Issue by wqyfavor** [dart-lang/sdk#42703]
This tracker is for issues related to:

* Dart VM on iOS in AOT release mode

Reproduce. Using Dart API with flutter library.

            Dart_Handle colorCls = Dart_GetClass(theDartUILibrary, "Color");
            Dart_Handle i = Dart_NewInteger(0xffffffff);
            Dart_Handle c = Dart_New(colorCls, Dart_Null(), 1, &i);

            const char* desc1 = "";
            Dart_StringToCString(Dart_ToString(c), &desc1);
            printf("Color: %s\n", desc1);
            
            Dart_Handle d = Dart_NewDouble(0.5);
            Dart_Handle c2 = Dart_Invoke(c, Dart_NewStringFromCString("withOpacity"), 1, &d);
            
            const char* desc2 = "";
            Dart_StringToCString(Dart_ToString(c2), &desc2);
            printf("Color withCapacity: %s\n", desc2);

Prints
Color: Color(0xffffffff)
Color withCapacity: Color(0x00ffffff)

Get 'Color' class from "dart:ui" library.
Create with initial value 0xffffffff.
Call withOpacity(0.5) and assign to color2.

The value of color2 is wrong. (Alpha value should not be 0x00)

I put a breakpoint in AOT compiled Color.withCapacity method and find that the double value loaded from stack is not 0.5

d0 is OK which is the constant 255. d1 is not 0.5

  Color withOpacity(double opacity) {
    assert(opacity >= 0.0 && opacity <= 1.0);
    return withAlpha((255.0 * opacity).round());
  }

<img width="1291" alt="截屏2020-07-15 21 17 02" src="https://user-images.githubusercontent.com/113776/87550478-a405b480-c6e1-11ea-9d43-6eefd659cb44.png">

**Comment by mraleph** [comment]
This method is not marked as an entry point so it is illegal to call it though C API. Hence this is working as intended and not a bug. We should really start enforcing this rule though to prevent surprises like this.

**Comment by wqyfavor** [comment]
> te

@mraleph 

This feature is very important for us. Is there a way to fix it or can you name some functions or the code which caused this problem so that I can further dig into this issue.

By disabling function signature shaking and global constant propagation, we almost achieve the goal that we can invoke aot method by C api except this double proble.

**Comment by mkustermann** [comment]
> You mentioned that this function is not an entry point. Will the assembly for this function be different if
> I set it as an entry point and then be able to invoke it by C API? Which part of Dart compiler is responsible
> for this difference?

Yes, adding `@pragma('vm:entry-point')` to a function can cause us to disable some optimizations (e.g. passing int/double arguments unboxed). To avoid that you could add a new Dart function which calls `Color.withOpacity`, put an entrypoint annotation on the new function and call that one from C.

Adding entry point annotations can also cause our global type flow analysis to no longer be able to proof that certain parameters will receive non-nullable values, which can also disable unboxing of int/double fields/parameters. You can help our analysis by checking for `null` and e.g. throwing, ...

With the upcoming NNBD (non-nullable by-default) language change this issue will go away, since it allows expression non-nullable int/double in the Dart code (by-default all types are nullable atm).

**Comment by wqyfavor** [comment]
> > You mentioned that this function is not an entry point. Will the assembly for this function be different if
> > I set it as an entry point and then be able to invoke it by C API? Which part of Dart compiler is responsible
> > for this difference?
> 
> Yes, adding `@pragma('vm:entry-point')` to a function can cause us to disable some optimizations (e.g. passing int/double arguments unboxed). To avoid that you could add a new Dart function which calls `Color.withOpacity`, put an entrypoint annotation on the new function and call that one from C.
> 
> Adding entry point annotations can also cause our global type flow analysis to no longer be able to proof that certain parameters will receive non-nullable values, which can also disable unboxing of int/double fields/parameters. You can help our analysis by checking for `null` and e.g. throwing, ...
> 
> With the upcoming NNBD (non-nullable by-default) language change this issue will go away, since it allows expression non-nullable int/double in the Dart code (by-default all types are nullable atm).

OK, Thanks for your explanation.
I know this issue is related to optimization, especially related to int/double boxing.

But for integer argument I can successfully call from C API. For example, 
        Dart_Handle i = Dart_NewInteger(0xffffffff);
        Dart_Handle c = Dart_New(colorCls, Dart_Null(), 1, &i);
For double argument the call fails.
        Dart_Handle d = Dart_NewDouble(0.5);
        Dart_Handle c2 = Dart_Invoke(c, Dart_NewStringFromCString("withOpacity"), 1, &d);

The constructor receives one integer and withOpacity receives one double.
Why the constructor can be successfully called from C without being set as entry-point?

**Comment by mkustermann** [comment]
> By the way. When will NNBD language feature be ready?

The core NNBD support is mostly ready already - available under an experimental flag.

> Will Flutter switch to NNBD mode?

Absolutely. Flutter has started NNBD migrating their code (see e.g. https://github.com/flutter/flutter/commit/978a2e7bf6a2ed287130af8dbd94cef019fb7bef)

Though only once an entire application's code (and all transitive dependencies) has been migrated to NNBD will the type system be sound and only then can our compilers rely on a non-nullable `int` to actually be non-nullable.

It will take some time until the Dart package ecosystem has migrated most important packages to allow bigger applications to be fully sound NNBD.
