### ISSUE TITLE
CFE: Emit errors for non-void setters and for incompatible setter/getter types

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42702]
Based on the spec changes in dart-lang/language#1083, a compile-time error should be emitted for a declaration of a setter whose return type is declared and not `void`; and, before null-safety: for a setter/getter pair where the getter return type is not assignable to the setter parameter type; and, with null-safety: for a getter/setter pair where the getter return type is not a subtype of the setter parameter type. The CFE currently does not emit these errors.

**Comment by johnniwinther** [comment]
Non-void setter return types are reported in https://dart-review.googlesource.com/c/sdk/+/161165

Getter/setter type conflict reporting is still missing.
