### ISSUE TITLE
CFE: Remove error for library name clash

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42700]
The CFE reports a warning in the following situation:

```dart
// Library 'lib1.dart'.
library clashing.nonempty.name;

// Library 'lib2.dart'.
library clashing.nonempty.name;

// Library 'main.dart'.
import 'lib1.dart';
import 'lib2.dart';

void main() {}
```

The response with `dart` from commit a48bebea1ed8dd0d3950e6120057a3a5bdae5518 is as follows:

```
tests/language_2/import/name_clash_test.dart:7:1: Warning: A library with name 'clashing.nonempty.name' is imported more than once.
import "name_clash_lib1.dart";
^
tests/language_2/import/name_clash_test.dart:8:1: Context: 'clashing.nonempty.name' is also imported here.
import "name_clash_lib2.dart";
^
```

This warning was removed from the language specification in dart-lang/language#1083, so the CFE should no more report this warning, with or without null-safety.

**Comment by johnniwinther** [comment]
What about export of libraries with library name clashes?

**Comment by eernstg** [comment]
Good catch!

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/pull/1096/files.

**Comment by eernstg** [comment]
dart-lang/language#1096 has now been landed, so the error for library name clashes in exports should also be eliminated.

**Comment by eernstg** [comment]
'name_clash_test' with/without null safety updated [here](https://dart-review.googlesource.com/c/sdk/+/153963).
