### ISSUE TITLE
Failures on Move `BytesBuilder` class and implementation to `dart:typed_data`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#42705]
There are new test failures on [Move `BytesBuilder` class and implementation to `dart:typed_data`.](https://dart-review.googlesource.com/c/sdk/+/150523).

The tests
```
pkg/front_end/test/old_dill/dart2js.version.43.compile.1 Fail (expected Pass)
```
are failing on configurations
```
cfe-unittest-asserts-release-linux
```

**Comment by lrhn** [comment]
The CL was reverted because it changed the ABI without updating ... possibly the kernel version number?
That might be related to this error.

**Comment by cskau-g** [comment]
As also mentioned on the other issue, I believe the offending CL should simply have bumped the ABI version:
https://github.com/dart-lang/sdk/blob/bec928c89f596ee651ae1c7238a0eb6aa5ce4013/tools/VERSION#L38

This is not related to the recently added SDK hash, so I'll unassign myself.

**Comment by lrhn** [comment]
ACK. Working on the ABI version increment (it's *not* just that file).
