### ISSUE TITLE
[CP] merge into [beta] channel: disallows imports to dart:mirrors on the web 

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#42715]
**commit(s) to merge**: c632a629ffa47182dc74a024a12928bb3fc23ac0

**merge instructions**: clean merge

**what's the problem**:

In 2.8 there is a static error on web compilers (dart2js and ddc) when apps import `dart:mirrors`. This was unintended (bug #42475).

In 2.9-beta this error is gone. We debated removing the error in 2.8 (#42553) and decided to embrace the breaking change instead (#42714) and readd the error to 2.9 (c632a629ffa47182dc74a024a12928bb3fc23ac0)

**why cherry-pick**:

We want to avoid being inconsistent: no error in 2.7, error in 2.8, no error in 2.9, error in 2.10. To prevent that, we'd like to cherry-pick this change to 2.9-beta and eventually 2.9 stable.

Note: since 2.8 already has this breaking change, this cherry-pick is effectively only improving the error message, it shouldn't affect anything that the 2.8 breaking change didn't before.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
scrum team approved

**Comment by franklinyow** [comment]
@pcsosinski @whesse

**Comment by whesse** [comment]
Cherry-picked to 2.9.0-21.10.beta.
