### ISSUE TITLE
Provide webdriver support for non-Linux LUCI bots

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#42713]
Currently webdriver tests can only be run on Linux configurations. We should run on OSX and Windows when possible.

**Comment by athomas** [comment]
@bkonyi What prevents you from doing so? The work done for https://github.com/dart-lang/sdk/issues/42417 should work on OSX and Windows as well.

**Comment by bkonyi** [comment]
I thought you had mentioned that this would only work on Linux for some reason? :-) I created this issue to tie to an approval for failing SSE tests on Windows / OSX which I assumed were due to lack of support. If that's not the case I'll update this issue to reflect the actual problem and assign to myself.

**Comment by athomas** [comment]
Pretty sure this was done a long time ago. Closing.
