### ISSUE TITLE
Add a "times" extension to int

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#42729]
As discussed [here](https://github.com/dart-lang/language/issues/983) I think a `times` extension function to `int` would be very helpful addition to the SDK.

This is just syntactic sugar, but it would be useful if instead of:

```dart
for(int i = 0; i < 5; i++) {
  print(i); // prints 0, 1, 2, 3, 4
}
```

We could just do:

```dart
5.times(print); // prints 0, 1, 2, 3, 4
```

I know this is something small, but it's in the little things, on the little details, that we measure quality and care :)

**Comment by julemand101** [comment]
You can already do this:
```
Iterable<int>.generate(5).forEach(print);
```

I am not a fan of putting too much stuff on the `int` type. Especially since this can easily be solved by just adding the following extension to your own project if you want this feature:
```
extension TimesOnIntExtension on int {
  void times(void Function(int) fun) =>
      Iterable<int>.generate(this).forEach(fun);
}
```

**Comment by feinstein** [comment]
Yeah, I know, but I don't like all that boilerplate for a simple `times` and I also don't like to have the same copy-paste utility code in every project and I also don't like to make tiny packages that do one small thing. I just thought this was a neat feature and other languages have it, but if this is eventually refused, then I will go and make a package for it.

**Comment by lrhn** [comment]
We are unlikely to put that method on `int`. We could do it without using extensions if we wanted to, but I don't think it's a particularly useful function with all the existing alternatives available. It just repeats, but doesn't return anything.

I'd be more interested in a shorter syntax for `Iterable.generate`, like `1.to(5)`, so you could do `1.to(5).forEach(print)` *or* `1.to(5).map(...)`.
(But not actually `1.to(5)`, that's a little too ugly.)

**Comment by feinstein** [comment]
I came up with this proposal precisely because I am kinda tired of the boilerplate in `Iterable.generate`, as you are, or the `for` loop. The `times` extension wasn't even my idea (as can be seen in the original issue), I honestly don't care how it's done, as long we have a quick, small, concise way to generate a finite number of repetitions.
