### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by singhrajshree** [dart-lang/sdk#42722]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.9.0-14.1.beta`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

**Comment by lrhn** [comment]
Can you say something more about the issue?

**Comment by singhrajshree** [comment]
my AVD  manger is not working properly while running the programme .
