### ISSUE TITLE
Wrong interpretation of "\path" on Windows

### ISSUE THREAD

**Issue by zichangg** [dart-lang/sdk#42731]
A path having a starting backslash represents an absolute path.

```python
f = open('\\test.txt', 'w+')
```
Python will create the file under C:\\.

```dart
print(File("\\test.txt").absolute.path); // output on my local machine: "C:\Users\zichangguo\dart-sdk\sdk\\test.txt"
File("\\test.txt").createSync(); // The file will be created to the same location, which is "C:\\test.txt"
```
Dart will print a path which is under current directory.

**Comment by lrhn** [comment]
Fixed (hopefully) with https://github.com/dart-lang/sdk/commit/69ba6e5f80e25cea566f6eb0dfb1c81e9ec78980.
