### ISSUE TITLE
[CP] Merge into [beta] channel: Bad identifier for async closure generator body names in extension methods.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#42735]
**commit(s) to merge**: a38e265f04d8976d226c3d966de2d9070a5c0941

**merge instructions**: clean merge

**what's the problem**:

Bad JavaScript code generation when extension methods are used with generators (async, async*, sync*).

**why cherry-pick**:

- The issue has come up twice already. #42531 and #42712.
- Low impact - it is a one-line change (plus new tests).

**Comment by franklinyow** [comment]
@rakudrama Can you update the request to look something like https://github.com/dart-lang/sdk/issues/42715

**Comment by sigmundch** [comment]
Note:  this issue is more visible in 2.9. The problem is exposed more often in the presence of legacy types, and since 2.9.* is the first release with the unforked SDK, we are noticing this issue a lot more than before.

**Comment by vsmenon** [comment]
lgtm
- risk seems low
- customers are hitting this
- per @sigmundch 's last comment, it's effectively a regression

**Comment by franklinyow** [comment]
Approved

**Comment by whesse** [comment]
Cherry-picked to 2.9.0-21.10.beta.
