### ISSUE TITLE
[CP] merge into [beta] channel: [vm/aot] Drop Library::dependencies_ early

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#42734]
**commit(s) to merge**: [7e5ac71ff3](https://github.com/dart-lang/sdk/commit/7e5ac71ff390bd140ebe77b19e698bd808d8b927)

**merge instructions**: clean merge

**what's the problem**:

[62893f9b00](https://github.com/dart-lang/sdk/commit/62893f9b00a6c8ccc3c0394406eff9e37dd1ec36) introduced a size regression in the gPay app as follows:

Baseline:
VMIsolate(CodeSize): 5117
Isolate(CodeSize): 7521914
ReadOnlyData(CodeSize): 8987328
Instructions(CodeSize): 16505256
Total(CodeSize): 33019615

VMIsolate(CodeSize): 5113
Isolate(CodeSize): 7516127
ReadOnlyData(CodeSize): 8863552
Instructions(CodeSize): 16503760
Total(CodeSize): 32888552

This change fixes the size regression.

**why cherry-pick**:

There could be similar size regressions in other apps too, the change itself is a minor and would help us avoid any potential size regressions.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by vsmenon** [comment]
Do we know whether this rolled into flutter and/or internal successfully?

**Comment by a-siva** [comment]
It has made it to the flutter framework, that version of flutter has not been rolled into google3 yet.

**Comment by franklinyow** [comment]
Approved

**Comment by whesse** [comment]
Cherry-picked to 2.9.0-21.10.beta.
