### ISSUE TITLE
[CP] Merge 90bba3ae277da into beta - avoids future issues with accidentally running incompatible kernel files on VM

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#42741]
**Commit(s) to merge**: 90bba3ae277da

**Merge instructions**: clean merge

**What's the problem**:

For many years the VM only validated the kernel format version of kernel files it was given. Though the kernel format version is not updated on various non-format changes. This can cause the VM to seemingly accept kernel files that are incompatible.

This manifests in `pub run` / `flutter packages pub run` using a cached kernel file to run on the VM. The VM can misbehave, throw exceptions or could even crash.

To avoid this going forward, we embed the `dart-lang/sdk` commit hash into kernel files produced and verify when consuming them, therefore avoiding the VM accepting non-compatible kernel files.

There was one missing piece for this which is not in the beta branch, which we'd like to cherry-pick.

See also https://github.com/dart-lang/sdk/issues/41802 for more information.

**Why cherry-pick**:

To ensure future releases of Dart SDK no longer have issues like these:

* https://github.com/dart-lang/build/issues/2748
* https://github.com/dart-lang/build/issues/2738
* https://github.com/flutter/flutter/issues/59245

/cc @kevmoo @mit-mit @whesse @athomas @a-siva  @franklinyow

**Comment by vsmenon** [comment]
We're getting late into cherry-pick season and this isn't a regression.  

@mkustermann - do you consider this low risk?  Has it rolled into flutter and/or internal successfully?

@kevmoo - how important is this to get into the current beta?  ( fyi - @jonahwilliams @natebosch )

**Comment by kevmoo** [comment]
We're getting a BUNCH of failures in CI without this fix. This is with any
precompiled binaries (pkg test, build runner, etc)

This is a regression that's hard to debug unless you have context.

Nake/Jake would be good to discuss risk with, too – although Martin has
most of the context, I think.

**Comment by natebosch** [comment]
> and this isn't a regression.

This is a regression. Old SDKs do not have this problem.

**Comment by vsmenon** [comment]
Thanks for the clarifications!  lgtm

**Comment by whesse** [comment]
Cherry-picked to 2.9.0-21.10.beta.
