### ISSUE TITLE
Analyzer server error in AddDiagnosticPropertyReference

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#42749]
I can't reproduce this right now (and don't now which file/location the cursor was at when it happened), but I was using a recent nightly build and had the Analyzer server code itself open, and this error occurred when the editor requested code actions.

@bwilkerson it seems like this code (in `AddDiagnosticPropertyReference`) got a null for `classDeclaration`:

```
final classDeclaration = parent.thisOrAncestorOfType<ClassDeclaration>();
    final debugFillProperties =
        classDeclaration.getMethod('debugFillProperties')
```

Any thoughts on might cause that? I think I was just browsing around the server code (not typing invalid code) at the time it occurred, but I could be mistaken.

```
[Error - 5:09:05 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'getMethod' was called on null.
Receiver: null
Tried calling: getMethod("debugFillProperties")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AddDiagnosticPropertyReference.compute (package:analysis_server/src/services/correction/dart/add_diagnostic_property_reference.dart:102:26)
#2      AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:253:24)
#3      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:173:11)
#4      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:168:39)
#5      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:197:7)
#6      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:69:18)
#7      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:66:26)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#10     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:65:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#12     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:62:17)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
```

**Comment by bwilkerson** [comment]
Yes. Because of the call to `_getReturnType` on line 33 we know that `parent` is either a `MethodDeclaration` or a `VariableDeclaration`. The `classDeclaration` will be `null` if `parent` isn't inside a `ClassDeclaration`. That could happen if it's inside a mixin or an extension.

We could fix the first case by changing line 101 to `parent.thisOrAncestorOfType<ClassOrMixinDeclaration>();`, but I doubt that we expect to find a `debugFillProperties` method in either a mixin or an extension, so the better fix is probably to return if `classDeclaration` is `null`.

**Comment by DanTup** [comment]
Thanks! Fix/test at https://dart-review.googlesource.com/c/sdk/+/154883/.

**Comment by srawlins** [comment]
Looks like this can be closed.
