### ISSUE TITLE
DateTime.add adds extra 1 hour

### ISSUE THREAD

**Issue by ymdarake** [dart-lang/sdk#42740]
# What I found

`DateTime add(Duration(days: N))` sometimes adds extra 1 hour as we can see in the screen shot below.

<img width="1440" alt="DateTime add" src="https://user-images.githubusercontent.com/19996540/87774929-60de4980-c879-11ea-98ab-07213d8cb24e.png">

# Repro step
https://dartpad.dev/
```
void main() {
  var date = DateTime(2020, 7, 11, 20, 50);
  for (int i = 0; i < 10; i++) {
    print(date);
    date = date.add(Duration(days: 14));
  }
}
```

**Comment by julemand101** [comment]
Could it be daylight saving time in your region?

> Notice that the duration being added is actually 50 * 24 * 60 * 60 seconds. If the resulting DateTime has a different daylight saving offset than this, then the result won't have the same time-of-day as this, and may not even hit the calendar date 50 days later.
>
>Be careful when working with dates in local time.

https://api.dart.dev/stable/2.8.4/dart-core/DateTime/add.html

**Comment by ymdarake** [comment]
@julemand101 Ah, I see. Thank you for pointing it out. Much appreciated.

--
I'll close this issue, sorry for being noisy!
