### ISSUE TITLE
DDC still tests non-nullable values for null when running with sound null safety

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42754]
DDC always inserts some null checks that behave differently in sound and weak mode.

This is left over from when `--sound-null-safety` was just a runtime option and the ability to run in sound mode with opted in and opted out sources. Now that it is a compile time option and we produce different .dill and .js files in sound and weak modes. Additionally we don't expect to run with mixed libraries in sound mode. 

DDC should just skip the some null checks in sound mode when we know the value is non-nullable. Right now I can think of: 

- Non-nullable method arguments
- Non-nullable booleans in conditionals

**Comment by franklinyow** [comment]
What's the status on this?  Is this required for Beta?

**Comment by nshahan** [comment]
The fixes are out for review now. I would like the change to land so we can get feedback during the beta.

**Comment by nshahan** [comment]
Fixed be the chain of commits:

e92b1b30b02a19031f718a685f482ea703b23b22
e2a4906c51a16739e0637b4b0b3c328e92e42f3f
ed8933db3f73effbf82083dad27e287fb08c6de5
4cb164215fc024ea6486b7d1fcdabf63746453c7
bef5ffde1ea417c40b01878b5d9e678a88e27633
885cc8ce1871a18a94b20e3f57580dcfc91dc1f2
