### ISSUE TITLE
CFE or VM: Execution of unbound external should throw

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42750]
The test outcome expectations in `tests/language/external_abstract_fields/external_fields_test.dart` have been corrected to match the [specified behavior](https://github.com/dart-lang/language/blob/2a8bff58e78fa90e3edebe9ef09392ec011caff6/specification/dartLangSpec.tex#L1931): Throwing a `NoSuchMethodError` when an external function with no binding is called.

This makes the configurations dartk-strong-linux-debug-x64, dartk-strong-linux-release-x64, dartk-weak-asserts-linux-debug-x64, dartk-weak-asserts-linux-release-x64 fail, because they don't throw.

@johnniwinther, @mkustermann: I'm not sure about the label on this issue, is it up to the CFE to generate code that makes this happen, or is this handled in the backend?

**Comment by johnniwinther** [comment]
Labeling as area-vm for now since we do not have a way for backends to tell which external members are allowed and which are not.

**Comment by eernstg** [comment]
Right. The behavior is actually [specified](https://github.com/dart-lang/language/blob/5001616a0ece31b686b48a34d931fcfa9cb3134a/specification/dartLangSpec.tex#L1930) in a way that allows many things:

> An external function is connected to its body by an implementation specific
> mechanism. Attempting to invoke an external function that has not been
> connected to its body will throw a `NoSuchMethodError` or some subclass thereof.

I made the tests expect a `NoSuchMethodError` because it seems reasonable that the implementation specific mechanism would bind external declarations to callable entities for a specific reason (e.g., FFI would use metadata and a marker supertype to request a binding from an external getter to a compiler-generated native function reading some non-Dart memory).

With no specific reason to perform a binding of any kind (which is the situation we have in the test), I'd assume that we are in the case where the external declaration "has not been connected to its body", so invocations should throw a `NoSuchMethodError`.

That's outside the language, however, because an 'implementation specific mechanism' _could_ have a way to bind these particular external declarations to a body (FFI uses metadata, but it could also be based on extra command line arguments, etc). An external declaration could also be bound to different callable entities at different times during an execution. So it seems impossible for the front end, but natural for the back end, to determine whether each individual external function is unbound and should throw.
