### ISSUE TITLE
[CP] merge into [beta] channel: Create a CL to disable dartdev in 2.9

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#42755]
commit(s) to merge: [f6a82443e4](https://github.com/dart-lang/sdk/commit/f6a82443e47a17be471ef104b5de2549fdf797e9)

link to issue: https://github.com/dart-lang/sdk/issues/42748

merge instructions: clean merge

what's the problem:

dartdev has some open issues which are being addressed in https://dart-review.googlesource.com/c/sdk/+/154706
https://github.com/dart-lang/sdk/issues/42630
https://github.com/dart-lang/sdk/issues/42092
https://github.com/dart-lang/sdk/issues/42664
https://github.com/dart-lang/sdk/issues/41978

why cherry-pick:

Cherry picking this change would ensure that we don't release the dartdev feature in a state that can cause annoying problems to the users.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by vsmenon** [comment]
lgtm per discussion today

@pcsosinski @franklinyow - are we set on this and/or do we need @whesse do to anything besides merge this in?

**Comment by pcsosinski** [comment]
lgtm

**Comment by whesse** [comment]
Cherry-picked to 2.9.0-21.10.beta.
