### ISSUE TITLE
Document if DateTime.difference can be negative

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#42756]
I am always confused whether `myDate.difference(myOtherDate)` can return a negative value, depending on the order of the dates. I assume not, but the [API docs](https://api.dart.dev/stable/2.8.4/dart-core/DateTime/difference.html) say nothing.

This is important, because I remember dealing with this at least two times already, and the only way to check is through experimentation (Dart SDK doesn't show the code of the method, it's `external`).

Similarly, `Duration` doesn't say if it ever can be negative. Again, my assumption is that it cannot, and that `myDate.difference(myOtherDate) == myOtherDate.difference(myDate)`. But clarity would be good.

I can make the PR if needed.

* Dart SDK Version (`dart --version`)

2.8.4

**Comment by lrhn** [comment]
A `Duration` can be negative, and `difference` can return a negative difference.

So yes, documentation saying that would be nice.

**Comment by filiph** [comment]
I went to make the change and realized it has been recently fixed (https://github.com/dart-lang/sdk/commit/af054ee91cb32d0890d8639bdddcbf892f5db7d2) and is merged into `master` now. Closing.
