### ISSUE TITLE
Analyzer: Implement null spread element typing with null-safety

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42757]
Cf. https://github.com/dart-lang/language/pull/1079, `Never` is the inferred element/key/value type of a spread element of the form `...?e` where the static type of `e` is a potentially nullable subtype of `Null`, and `Never` is also the inferred element/key/value type of `...e` where the static type of `e` is a subtype of `Never`.

The analyzer currently reports several errors for the associated tests: https://dart-review.googlesource.com/c/sdk/+/154693.

**Comment by scheglov** [comment]
I don't understand what "potentially nullable subtype thereof" means in "With null-safety, when the static type of `e` is `Null` or a potentially nullable subtype thereof". I have two issues: 
1. Is there any special meaning of "thereof"?
2. Is there any special meaning of "potentially nullable"? So, `e` should be not just subtype of `Null`, but also **potentially nullable**?

**Comment by eernstg** [comment]
"`Null` or a potentially nullable subtype thereof" simply means "a potentially nullable subtype of `Null`", but I singled out that `Null` is included because it may be tempting to think that "a subtype of `T`" means "a proper subtype of `T`", that is, it doesn't include `T` itself. I don't know if that amounts to a _special_ meaning of 'thereof'. ;)

So this is concerned with types like `Null`, `X extends Null`, and `X & Null`. The next paragraph is concerned with `e` whose type is `Never`, `X extends Never`, and `X & Never`.

There would not have been a contradiction if we had included all subtypes of `Null` in the first paragraph, but we would then cover the cases with `...?e` where `e` has a subtype of `Never` twice, and it is confusing and error-prone to specify any rule twice.

**Comment by scheglov** [comment]
Thank you.
So, it seems to me that just a simple `X <: Null` will work.

Another related question.
Is this code valid in Null Safety and legacy?
```dart
void f<T extends Iterable<int>>(T a) {
  // ignore:unused_local_variable
  var v = [...a];
}
```
The spec says that `S` should implement `Iterable`.
But both analyzer and CFE report an error.
![image](https://user-images.githubusercontent.com/384794/87974970-c6038c00-ca7f-11ea-8ec1-8549bb83c5b3.png)

**Comment by eernstg** [comment]
> a simple `X <: Null` will work.

Right, and you don't have to worry about not including `...e` where the static type of `e` is potentially nullable (some other piece of code will catch that), so you can just handle both cases together.

> Is this code valid in Null Safety and legacy?

Good catch! It _should_ be valid, because it is clearly an anomaly if an expression whose static type is a type variable `X` is rejected for a usage which is allowed if the static type is the bound of `X`.

We have [this](https://github.com/dart-lang/language/blob/b196daf6bdeb6e591fd90a3a683d736365cb8526/specification/dartLangSpec.tex#L4176) paragraph, which is needed in order to allow the above for method invocations and property extractions.

Created https://github.com/dart-lang/language/pull/1106 in order to allow expressions whose type `U` is a type variable `X extends B` to be used in cases where we require that `U implements S` for some type `S` (because we now have that `X implements S` if `B implements S`).

**Comment by eernstg** [comment]
dart-lang/language#1106 has landed, so the following is no longer an error:

```dart
void f<T extends Iterable<int>>(T a) {
  var v = [...a]; // OK, because `T` implements `Iterable<int>`, with updated spec.
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/155680
