### ISSUE TITLE
DDC: Implement null spread element typing with null-safety

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42759]
Cf. https://github.com/dart-lang/language/pull/1079, `Never` is the inferred element/key/value type of a spread element of the form `...?e` where the static type of `e` is a potentially nullable subtype of `Null`, and `Never` is also the inferred element/key/value type of `...e` where the static type of `e` is a subtype of `Never`.

DDC currently reports several errors for the associated tests: https://dart-review.googlesource.com/c/sdk/+/154693.

**Comment by eernstg** [comment]
Note, cf. https://github.com/dart-lang/sdk/issues/42760#issuecomment-661083979, that this issue might be resolved automatically when https://github.com/dart-lang/sdk/issues/42758 is resolved.

**Comment by sigmundch** [comment]
Closing since the fix fffd0d04b19d6c88e41d01a55db153d426fc89fa for the CFE addressed all the ddc failures as well.
