### ISSUE TITLE
[ffi] Loads and stores sensitive to inlining budget

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#42767]
Source code 1x benchmark invocation.

```
dacoharkes@dacoharkes-l:~/dart-sdk/sdk$ DART_CONFIGURATION=ReleaseX64 pkg/vm/tool/precompiler2 benchmarks/FfiMemory/dart/FfiMemory.dart fo1
dacoharkes@dacoharkes-l:~/dart-sdk/sdk$ DART_CONFIGURATION=ReleaseX64 pkg/vm/tool/dart_precompiled_runtime2 fo1
FfiMemory.PointerInt8(RunTime): 16.5978771431891 us.

```

Source code 3x benchmark invocation.

```
dacoharkes@dacoharkes-l:~/dart-sdk/sdk$ DART_CONFIGURATION=ReleaseX64 pkg/vm/tool/precompiler2 benchmarks/FfiMemory/dart/FfiMemory2.dart fo2
dacoharkes@dacoharkes-l:~/dart-sdk/sdk$ DART_CONFIGURATION=ReleaseX64 pkg/vm/tool/dart_precompiled_runtime2 fo2
FfiMemory.PointerInt8(RunTime): 19.26282180935595 us.
FfiMemory.PointerInt8(RunTime): 19.252543727077576 us.
FfiMemory.PointerInt8(RunTime): 19.258232869853252 us.
```

Upon inspection of the flow graph, the main method of the benchmark has different inlining behavior. (All the relevant FFI methods have no differences in flow graph and machine code.)

**Comment by mkustermann** [comment]
Not sure if it's beneficial to have a separate issue for this. We will holistically look into performance and code size of ffi related.

The inliner is independent of ffi and we have open issues for that already.

@dcharkes Can we close this issue?
