### ISSUE TITLE
dart2js: Implement null spread element typing with null-safety

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42760]
Cf. https://github.com/dart-lang/language/pull/1079, `Never` is the inferred element/key/value type of a spread element of the form `...?e` where the static type of `e` is a potentially nullable subtype of `Null`, and `Never` is also the inferred element/key/value type of `...e` where the static type of `e` is a subtype of `Never`.

`dart2js` currently reports several errors for the associated tests: https://dart-review.googlesource.com/c/sdk/+/154693.

**Comment by fishythefish** [comment]
The spread operator is currently desugared by the CFE, which is why there are errors on the CFE, DDC, and VM bots as well. Once the CFE issue is fixed, the backend failures will likely be resolved automatically.

**Comment by eernstg** [comment]
Given that the CFE issue is #42758, we should just close this issue rather than making it a duplicate. Of course, that's only true if 'failures will likely be resolved automatically' means 'failures will definitely be resolved automatically', but that seems to be likely at this point. ;)

**Comment by fishythefish** [comment]
FWIW, if these tests don't get fixed by the CFE change, they'll continue to show up in the list of NNBD test failures and I'll end up handling them in the burndown anyway.
