### ISSUE TITLE
Add support for ARM macOS host 

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#42775]
This is the meta issue for tracking all items related to having Dart SDK support for ARM macOS host and target
(please see related flutter issues https://github.com/flutter/flutter/issues/60118, https://github.com/flutter/flutter/issues/60113)

1. https://github.com/dart-lang/sdk/issues/42772 Dart SDK (unchanged version) should run on macOS ARM host machines (Rosetta Translation Environment)
2. https://github.com/dart-lang/sdk/issues/42773 Dart SDK version is built for macOS ARM host
3. https://github.com/dart-lang/sdk/issues/42774 AOT apps generated for macOS ARM run correctly (dart2native)

**Comment by alexmarkley** [comment]
I'm happy to help with testing or development on this, so any portions of this work that could be carved out for the community to tackle would be great.

**Comment by mateusfccp** [comment]
Can this be closed?
