### ISSUE TITLE
Command line script name not recognized as Windows UNC path

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#42779]
A command line like:
```
dart \\?\d:\something\something\lang\dart\temp\pwd.dart
```
gives the error:
```
Crash when compiling file://?/d:/something/something/lang/dart/temp/pwd.dart,
at character offset null:
Unsupported operation: Cannot extract a file path from a URI with a query component
#0      _Uri.toFilePath (dart:core/uri.dart:2713:7)
#1      new File.fromUri (dart:io/file.dart:265:49)
...
```

The path is a valid Windows path. It is treated as a *URI*, which is wrong, it should be *converted* to a URI explicitly in a way which preserves the `?`, likely `file://%25/d:/something/something/lang/dart/temp\pwd.dart` or just `file:///d:/something/something/lang/dart/temp/pwd.dart`.

**Comment by a-siva** [comment]
This has been labelled as area-dart-cli but I presume this fails irrespective of whether dartdev is enabled or not?

**Comment by zichangg** [comment]
I think this is a problem at frontend.

`\\?\` is a special prefix.

> For file I/O, the "\\\\?\\" prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system.

The path in the example is a regular path. But It can also be used together with UNC path.

> The "\\?\" prefix can also be used with paths constructed according to the universal naming convention (UNC). To specify such a path using UNC, use the "\\?\UNC\" prefix. For example, "\\?\UNC\server\share", where "server" is the name of the computer and "share" is the name of the shared folder.

Frontend should treat it as a regular path and Windows API is able to recognize.

Ref: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces

**Comment by johnniwinther** [comment]
@lrhn Can you provide more of the stack trace?

When it try `dart \\?\c:\src\dart-repo2\temp\abstract.dart` on bleeding edge I get
```
c:\src\dart-repo2\sdk>out\ReleaseX64\dart.exe \\?\c:\src\dart-repo2\temp\abstract.dart
Error when reading '\\?\c:\src\dart-repo2\temp\abstract.dart': No such file or directory.
Could not find a command named "\\?\c:\src\dart-repo2\temp\abstract.dart".

Usage: dart [<vm-flags>] <command|dart-file> [<arguments>]

Global options:
-h, --help                              Print this usage information.
-v, --verbose                           Show additional command output.
    --version                           Print the Dart SDK version.
    --enable-analytics                  Enable anonymous analytics.
    --disable-analytics                 Disable anonymous analytics.
    --enable-experiment=<experiment>    Enable one or more experimental features.
                                        [extension-methods, non-nullable, nonfunction-type-aliases, triple-shift, variance]

Available commands:
  analyze   Analyze the project's Dart code.
  compile   Compile Dart to various formats.
  create    Create a new project.
  format    Idiomatically formats Dart source code.
  migrate   Perform a null safety migration on a project or package.
  pub       Work with packages.
  run       Run a Dart file.
  test      Runs tests in this project.

Run "dart help <command>" for more information about a command.
```

and when I run `dart run \\?\c:\src\dart-repo2\temp\abstract.dart` I get
```
c:\src\dart-repo2\sdk>out\ReleaseX64\dart.exe run \\?\c:\src\dart-repo2\temp\abstract.dart
Unsupported operation: Cannot extract a file path from a URI with a query component
#0      _Uri.toFilePath (dart:core/uri.dart:2713:7)
#1      RunCommand.run (package:dartdev/src/commands/run.dart:130:10)
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#3      DartdevRunner.runCommand (package:dartdev/dartdev.dart:238:24)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:223:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      runDartdev (package:dartdev/dartdev.dart:107:27)
#8      main (file:///c:/src/dart-repo2/sdk/pkg/dartdev/bin/dartdev.dart:12:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
which doesn't match yours (at `#1`).

So it seems we have multiple entry points that need fixing.

**Comment by zichangg** [comment]
@johnniwinther 
I'm able to repro on my gWin machine using cmd.exe.

This is the stacktrace I got:
> Crash when compiling file://?/C:/Users/zichangguo/dart-sdk/sdk/Junk/main.dart,
at character offset null:
Unsupported operation: Cannot extract a file path from a URI with a query component
#0      _Uri.toFilePath (dart:core/uri.dart:2713:7)
#1      new File.fromUri (dart:io/file.dart:260:49)
#2      _IoFileSystemEntity.readAsBytes (package:front_end/src/api_prototype/standard_file_system.dart:66:18)
#3      HybridFileSystemEntity.readAsBytes (package:front_end/src/fasta/hybrid_file_system.dart:54:61)
asynchronous suspension
#4      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:249:55)
#5      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:417:26)
#6      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:254:13)
#7      SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:343:17)
#8      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:301:20)
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#10     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:300:12)
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:119:28)
asynchronous suspension
#12     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#14     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#15     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#16     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
asynchronous suspension
#17     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#18     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#19     new Future.sync (dart:async/future.dart:223:31)
#20     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#21     _rootRun (dart:async/zone.dart:1190:13)
#22     _CustomZone.run (dart:async/zone.dart:1093:19)
#23     _runZoned (dart:async/zone.dart:1630:10)
#24     runZoned (dart:async/zone.dart:1550:10)
#25     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#26     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#27     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#28     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#29     SingleShotCompilerWrapper.compileInternal (file:///C:/Users/zichangguo/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:441:17)
#30     Compiler.compile.<anonymous closure> (file:///C:/Users/zichangguo/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:208:45)
#31     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#32     _rootRun (dart:async/zone.dart:1182:47)
#33     _CustomZone.run (dart:async/zone.dart:1093:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#36     _rootRun (dart:async/zone.dart:1190:13)
#37     _CustomZone.run (dart:async/zone.dart:1093:19)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#39     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#40     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#41     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by johnniwinther** [comment]
The input has already been processed when it reaches `pkg/vm/bin/kernel_service.dart:208:45`. When I supply `\\?\c:\src\dart-repo2\sdk\temp\abstract.dart` to `dart.exe` at the command line the `inputFileUri` in `_processLoadRequest` is changed to `//?/c:/src/dart-repo2/sdk/temp/abstract.dart`. I don't know how `_processLoadRequest` is called but the caller needs to change processing to fix the issue for entry point. @zichangg Do you know how `_processLoadRequest` is called?

**Comment by johnniwinther** [comment]
Running `dart run` with Windows paths is generally broken. See #42874

**Comment by franklinyow** [comment]
@zichangg We have a branch cut next week for Aug.  Is this something we can fix before that?

**Comment by lrhn** [comment]
I think the any change here needs to happen very early in the pipeline. The command line argument can traditionally be either a local path or a URI, and we have never been very good at deciding. It's then converted to (or parsed as) a URI in order to have a single type internally in the front-end.

It think we should take some time to figure out what we really want to do about the command line interpretation. Perhaps we can even disallow URIs completely and always treat the command line argument as a local file path, unless there are still people compiling from HTTP URIs. 
Then we should ensure that *all* our tools behave the same (see also #42864)

**Comment by a-siva** [comment]
@franklinyow based on the comments above it looks like this is going take longer to get a clean fix and will not be fixed in time for the beta branch next week. I propose that as a first step we report all paths with "\\?\" as unsupported and not crash. We can include this change for beta and then work on a proper fix for it.

**Comment by franklinyow** [comment]
I will remove the P1 label for now.  As @zichangg said this is not a common use case, and we need more time to come up with the right solution

**Comment by a-siva** [comment]
Looks like we have landed the fix for preventing a crash, can the rest of the work indicated in the comment above from @lrhn be tracked in #42864 ? Also should this be tracked in the September 2020 milestone ?

**Comment by franklinyow** [comment]
https://github.com/dart-lang/sdk/issues/42923 tracks the work @lrhn mentioned.
This one can be closed.
