### ISSUE TITLE
Analyzer fails to recognize static function calling a non-static function inside an anonymous function.

### ISSUE THREAD

**Issue by JSANL** [dart-lang/sdk#42770]
```dart
import 'package:test/test.dart';

void main() {
  test('static bug', () {
    expect(Foo().baz, 3);
  });
}

class FooBase {
  final int baz;

  FooBase(this.baz);
}

class Foo extends FooBase {
  Foo() : super(_bar());

  static int _bar() {
    return () {
      // Analyzer should show an error here
      return _foo();
    }();
  }

  int _foo() {
    return 3;
  }
}
```

Expected Behavior:  
Analyzer showing that foo() can't be called from _bar();

Actual Behavior:   
Compilation Error "Method not found: foo()"

The weird thing is that the analyzer in dartpad works correctly: https://dartpad.dev/b35639b80e1af9750dd00b97142131ef
although I have Dart 2.9.0 and Dartpad says "Based on Dart SDK 2.8.4".

Dart Version:
`Dart VM version: 2.9.0-5.0.dev.flutter-4da5b40fb6 (be) (Wed May 6 16:59:45 2020 +0000) on "macos_x64"`

**Comment by srawlins** [comment]
@scheglov might this be addressed by the scoping work you are doing now? Just a thought.

**Comment by bwilkerson** [comment]
My expectation (and hope :-)) is that the answer is "no". The analyzer is correctly resolving the reference to `_foo` to the instance member. This is necessary for the IDE experience. The only thing wrong is that it isn't producing the necessary diagnostic (which should use the error code is `CompileTimeErrorCode.INSTANCE_MEMBER_ACCESS_FROM_STATIC`). I don't know why the diagnostic isn't being produced, but it isn't likely to be a result of the structure of the name scopes.

**Comment by scheglov** [comment]
Brian is right, it is not related to name scopes, but I think I know when I might have broken it, or failed to fix at least.
We have a single "enclosing executable", and "the most enclosing" here is not a static method.
So, we probably should just chain them and check if we are inside of a chain that has a static member.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/155144

**Comment by srawlins** [comment]
Ah, I understand the difference; that's super interesting. Thanks!
