### ISSUE TITLE
Dart SDK (unchanged version) should run on macOS ARM host machines using Rosetta Translation Environment

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#42772]
This issue is to track work that ensures Dart SDK runs on macOS ARM host machines using Rosetta Translation Environment.

Related issues
- https://github.com/dart-lang/sdk/issues/42534

**Comment by franklinyow** [comment]
Do we have more information on what need to be done? And when are we targeting to be done with this work?

**Comment by a-siva** [comment]
Ideally we should have a build bot configuration that is able to do the following runs
- builds a macOS X64 version of the SDK and runs it unchanged on macOS ARM

when we have made changes to build the SDK for macOS ARM the bot would have to add a configuration
to build the Dart SDK for macOS ARM and run it on that machine.

**Comment by a-siva** [comment]
After discussion with @athomas yesterday we decided that it is best to plan for manual testing of Dart on this platform for this release. Work on getting the necessary infra set up to add this configuration to the bots will continue but would probably complete only after the release.

**Comment by mit-mit** [comment]
@a-siva @athomas any news on this one?

**Comment by franklinyow** [comment]
Related bug:
https://github.com/flutter/flutter/issues/65133
https://github.com/flutter/flutter/issues/65132
https://github.com/flutter/flutter/issues/65131

**Comment by franklinyow** [comment]
The flutter bus are closed, anything left here?
@a-siva

**Comment by jmagman** [comment]
I've been able to `flutter run` on physical iOS and Android devices with Rosetta, I'm not aware of any additional dart issues.
Hopefully https://github.com/dart-lang/sdk/issues/42773 is up soon in the docket!

**Comment by a-siva** [comment]
Closing issue based on all the tests done running Dart with Rosetta.
