### ISSUE TITLE
Dart SDK support for macOS arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#42773]
Dart SDK support for macOS arm64 ([Apple Silicon](https://developer.apple.com/documentation/xcode/porting_your_macos_apps_to_apple_silicon)):

   - [X] Fix issues in `fetch dart`: https://github.com/dart-lang/sdk/issues/43488
   - [X] Build support: Dart SDK build rules are updated to build a version of the Dart SDK for macOS ARM host (runs natively without any translation environment needed for it).
   - [X] Automated testing: build bots to build and test this variant.
   - [X] Support in `dart compile`: https://github.com/dart-lang/sdk/issues/44001

**Comment by athomas** [comment]
Note, we won't have the build and test infrastructure set up until Q1, see https://crbug.com/1147828.

**Comment by mit-mit** [comment]
Related specific issue for Dart native compilation to executables: https://github.com/dart-lang/sdk/issues/44001

**Comment by a-siva** [comment]
Work on native compilation of Dart SDK for macOS ARM is progressing and we hope to have an initial build done in Q4, for full fledged support of builds and tests please see https://github.com/dart-lang/sdk/issues/42773#issuecomment-727931080

**Comment by acoutts** [comment]
@a-siva is there anything we can try yet for building dart ourselves on ARM macOS? I tried following the build instructions but ran into the same issue as #43488

**Comment by mraleph** [comment]
Blocked on https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=67614 (our toolchain does not properly support Mac ARM64 target yet).

**Comment by vsmenon** [comment]
@a-siva @mit-mit - are we comfortable punting this to the next milestone?  I think we discussed that since we're blocked.

**Comment by mit-mit** [comment]
I don't think we have much choice currently, and I'm not aware of any hard deadlines, so yes

**Comment by franklinyow** [comment]
@a-siva Should this move out of April?  Which Milestone we're looking at?

**Comment by a-siva** [comment]
We are able to build locally, for this to be complete we need to set up the bots to build/test for this configuration. We expect this setup to be ready and done by end of June. So yes the milestone needs to be moved. I will drop April, do you have a milestone for activities to be done by end of June ?

**Comment by franklinyow** [comment]
@a-siva We have June Milestone open

**Comment by alhafoudh** [comment]
Sorry for maybe dump and naive question, but will this enable us to run dart analyzer natively on Apple Silicon CPU?

**Comment by mraleph** [comment]
> Sorry for maybe dump and naive question, but will this allow us to run dart analyzer natively on Apple Silicon CPU?

Yes. Once we have a native SDK for Apple Silicon everything will run natively.

**Comment by a-siva** [comment]
We now have an initial build bot setup for building and testing this variant, see https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-release-arm64

**Comment by acoutts** [comment]
@a-siva is it possible to download arm64 builds yet?

**Comment by mraleph** [comment]
@acoutts We don't yet have official SDK builds released for ARM64 Macs AFAIK. You can download and try one produced by CI bot if you want, latest build is always available from this bucket: `gs://dart-archive/channels/be/raw/latest/sdk/dartsdk-macos-arm64-release.zip` ( [HTTPS link](https://storage.googleapis.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-macos-arm64-release.zip) )

**Comment by lesnitsky** [comment]
jit mode works
executable produced by `dart compile exe` exits immediately

**Comment by premkumar5012002** [comment]
When dart sdk will release in stable for mac os arm64

**Comment by franklinyow** [comment]
@a-siva Are we done?  Should this move to the next milestone?

**Comment by a-siva** [comment]
@mit-mit can you add a comment here on when PM would like to announce availability of this configuration.

**Comment by mit-mit** [comment]
I'm happy to comment that arm64/M1 support is now available in the dev and beta channels from https://dart.dev/tools/sdk/archive

If you experience any problems, kindly file new issues in the present bug tracker. Thanks!

**Comment by mit-mit** [comment]
@a-siva I think we can close this issue now?
