### ISSUE TITLE
NNBD: Analyzer does not throw a compile error when checks least and greatest closures for the function with required parameter

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42788]
Dart SDK version: 2.9.0-21.0.dev (dev) (Wed Jul 8 10:54:08 2020 +0200) on "windows_x64"

Here is a source code example which demonstrates the problem:
``` dart
Type? _capturedTypeArgument;

X captureTypeArgument<X>() {
  _capturedTypeArgument = X;
  throw 1;
}

typedef check = void Function({required bool x});

void main() {
  void f(check Function() g) => g();
  f(() => captureTypeArgument()..call());   
}
```
Dart throws a compile error here whereas analyzer does not.

Sample output is:
> $> dart --enable-experiment=non-nullable test.dart
> test.dart:12:38: Error: Required named parameter 'x' must be provided.
>   f(() => captureTypeArgument()..call());
>                                      ^
> $> dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   hint - The declaration '_capturedTypeArgument' isn't referenced. - test.dart:1:7 - unused_element
> 1 hint found.

Failing co19 tests are:
- co19/LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_static_t06
- co19/LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_static_t07

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/156841
