### ISSUE TITLE
dart:ffi crashes on allocating big arrays (stack limit Dart main thread)

### ISSUE THREAD

**Issue by sashko** [dart-lang/sdk#42805]
Using the [dart:ffi hello_world](https://github.com/dart-lang/samples/tree/master/ffi/hello_world) example, create a shared library with the following function:

```
void hello_world()
{
    int a[1000000];
}
```

Result:

`[2]    1022487 segmentation fault (core dumped)  dart test.dart`

Decreasing size of the array, by 10 makes code work. Tried on 64-bit Linux with 64 Gb of RAM, so memory shouldn't be an issue.

**Comment by mkustermann** [comment]
@sashko It is not important how much RAM a machine has. What is important is the maximum stack size for the thread used to execute the code. Depending on operating system, configuration and various other conditions the stack size can vary. But it usually is a few MB.

Running any C code which uses too much stack space can crash a program. In this particular example the C code uses `sizeof(int) * 1000 * 1000` in a frame which can be 4 MB. That can easily exhaust default stack size limits.

It's the responsibility of the C programmer to ensure not to use too much stack space. So this is not really a `dart:ffi` issue .

**Comment by sashko** [comment]
@mkustermann thanks for the fast reply.

> Running any C code which uses too much stack space can crash a program. In this particular example the C code uses `sizeof(int) * 1000 * 1000` in a frame which can be 4 MB. That can easily exhaust default stack size limits.

I do not know how `dart:ffi` works but talking about the C code in question: my system's stack limit is 8MB and the array's size if `sizeof(int) * 100 * 1000 = ~4 MB` which is less than a half of the limit.

Increasing process stack size with `ulimit` tenfold makes no difference.

**Comment by mkustermann** [comment]
@sashko I believe the `ulimit` only influences the main thread's limits. Real pthreads created have a different default size.

You can try running this example to see what the pthreads stack size is on your machine:
```dart
import 'dart:ffi';
import 'package:ffi/ffi.dart';

class PThreadAttr extends Struct {
  @Int64()
  int a1;
  @Int64()
  int a2;
  @Int64()
  int a3;
  @Int64()
  int a4;
  @Int64()
  int a5;
  @Int64()
  int a6;
  @Int64()
  int a7;
}

final syms = DynamicLibrary.process();

typedef SelfNative = IntPtr Function();
typedef Self = int Function();
final self = syms.lookupFunction<SelfNative, Self>('pthread_self');

typedef GetAttrNative = IntPtr Function(
  IntPtr pthread,
  Pointer<PThreadAttr> attr,
);

typedef GetAttr = int Function(
  int pthread,
  Pointer<PThreadAttr> attr,
);
final getAttr =
    syms.lookupFunction<GetAttrNative, GetAttr>('pthread_getattr_np');

typedef GetStackNative = IntPtr Function(
  Pointer<PThreadAttr> attr,
  Pointer<Pointer<Void>> saddr,
  Pointer<Int64> ssize,
);

typedef GetStack = int Function(
  Pointer<PThreadAttr> attr,
  Pointer<Pointer<Void>> saddr,
  Pointer<Int64> ssize,
);
final getstack =
    syms.lookupFunction<GetStackNative, GetStack>('pthread_attr_getstack');

main() {
  final attr = allocate<PThreadAttr>();
  final address = allocate<Pointer<Void>>();
  final size = allocate<Int64>();
  getAttr(self(), attr);
  getstack(attr, address, size);
  print('Address: 0x${address.value.address.toRadixString(16)}');
  print('Stack size: ${size.value / 1024} kb');
  free(attr);
  free(address);
  free(size);
}
```

For me it prints:
```
% dart printstack.dart
Address: 0x7faf5d9ff000
Stack size: 1024.0 kb
```
1 MB is actually quite a lot of stack space.

Are you requesting that the Dart VM explicitly sets a higher limit?
