### ISSUE TITLE
Bring up DartDev isolate from kernel instead of an AppJIT snapshot

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#42804]
Using a snapshot to bring up the DartDev isolate can cause a failure if incompatible VM flags are provided. We should change to using a kernel file instead to avoid these incompatibilities.

**Comment by mit-mit** [comment]
This is a bit hard to understand; can you explain the issue in a bit more detail?

**Comment by bkonyi** [comment]
An example from #42958 where passing `--sound-null-safety` causes dartdev to fail to load:

```
out/ReleaseX64/dart --observe --enable-experiment=non-nullable --sound-null-safety test_hello.dart 
Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-dwarf_stack_traces_mode
causal_async_stacks no-lazy_async_stacks lazy_dispatchers use_bare_instructions no-dedup_instructions no-"asserts"
"use_field_guards" "use_osr" no-code-comments x64-sysv no-null-safety' but the VM has 'release no-dwarf_stack_traces_mode
causal_async_stacks no-lazy_async_stacks lazy_dispatchers use_bare_instructions no-dedup_instructions no-"asserts"
"use_field_guards" "use_osr" no-code-comments x64-sysv null-safety'
Observatory listening on http://127.0.0.1:8181/3JgcHLS6A2Q=/
```

Basically, AppJIT snapshots require that certain VM flags used to generate the snapshot must also be set identically in the VM the snapshot is being loaded into; if they don't match, the snapshot won't be loaded. We have the same issue when we load the kernel isolate, but we fall back to using the kernel snapshot if the AppJIT snapshot fails to load.

**Comment by mit-mit** [comment]
So here specifically the VM is running with sound null safety and thus cannot load an AppJit snapshot that has unsound null safety? Why is that? 

I understand that other "low level" VM flags can affect the snapshot format, but why does something like null safety impact it?

**Comment by bkonyi** [comment]
I'm not 100% confident (@a-siva, please correct me if I'm wrong) but I believe that what determines whether or not a flag is compatible with a snapshot is if the flag changes behavior or memory layout in an incompatible way. For the example above we're trying to load a snapshot which was not generated with strong null safety enabled into a VM which expects strong null safety which would break assumptions made by the VM.

**Comment by a-siva** [comment]
app JIT snapshots contains code.
The code/runtime stubs that are generated for sound null safety is different from unsound null safety, so it would be incorrect to load up an app JIT snapshot generated in unsound null safety mode into a VM that is expected to run in sound null safety mode and vice-versa.
