### ISSUE TITLE
http_client_connect_test failing on windows bots

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#42818]
A few windows bots turned red due to failures in http_client_connect_test. I think this is due to https://dart-review.googlesource.com/c/sdk/+/147339, though deflaking meant that the actual redness didn't start until a few CLs later than this.

https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-win-debug-x64/8907
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-win-release-x64/12494
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-win-product-x64/10281

**Comment by zichangg** [comment]
The cl has been reverted. I'll close the issue.
