### ISSUE TITLE
dartdevc_patch_sdk build target fails

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#42825]
The build target dartdevc_patch_sdk fails to build.
No build target that we commonly use includes that target, maybe it is unused.
The build targets create_sdk, runtime, and most do not build it.
Running build.py with no target specified runs all targets in our build files, and so runs it and fails.
Of course, nobody should be running build.py with no target, but people do by accident.

The build fails with:
sdk$ tools/build.py -mrelease dartdevc_patch_sdk

FAILED: gen/utils/dartdevc/patched_sdk/version 
python ../../build/gn_run_binary.py compiled_action /src/dart/sdk/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=4c74ebb367 --dfe=/src/dart/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /src/dart/sdk/pkg/dev_compiler/tool/patch_sdk.dart --libraries /src/dart/sdk/sdk/lib/libraries.json --target dartdevc --out /src/dart/sdk/out/ReleaseX64/gen/utils/dartdevc/patched_sdk/
Command failed: /src/dart/sdk/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=4c74ebb367 --dfe=/src/dart/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /src/dart/sdk/pkg/dev_compiler/tool/patch_sdk.dart --libraries /src/dart/sdk/sdk/lib/libraries.json --target dartdevc --out /src/dart/sdk/out/ReleaseX64/gen/utils/dartdevc/patched_sdk/
output: Unhandled exception:
Invalid argument(s): Content produced diagnostics when parsed
#0      parseString (package:analyzer/dart/analysis/utilities.dart:134:5)
#1      _parseString (file:///src/dart/sdk/pkg/dev_compiler/tool/patch_sdk.dart:477:10)
#2      main (file:///src/dart/sdk/pkg/dev_compiler/tool/patch_sdk.dart:64:14)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by vsmenon** [comment]
@nshahan @sigmundch - is this dead code now with ddk?

**Comment by nshahan** [comment]
We are still using that script in that target to create a patched SDK to check for analysis errors but AFAIK we are not using that build target. I'll talk with @sigmundch and make sure we do some cleanup.
