### ISSUE TITLE
Move all compile-time errors to CompileTimeErrorCode

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#42821]
See https://github.com/dart-lang/sdk/issues/42787#issuecomment-662269577 for the context.
We are lying about the kind of the diagnostics, and people try to depend on it.

**Comment by munificent** [comment]
Yes, this would be great. I'll work around in the in the meantime in the test runner.

**Comment by scheglov** [comment]
Done.
We have only a handful of items left in [StaticWarningCode](https://github.com/dart-lang/sdk/blob/c21128767e2db715af0d5cc830f068891efefbea/pkg/analyzer/lib/src/error/codes.dart#L10311).
