### ISSUE TITLE
Delete the '--custom_for_pub' argument from make_version.py

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#42820]
The option '--custom_for_pub' was added to make_version.py to enable Flutter to invoke the Dart build using this option
(see https://github.com/flutter/flutter/issues/14751 for more details on why this was done).

This option causes problems as we end up with Flutter building a Dart SDK that pretends to be a version that it is not
(please see https://github.com/flutter/flutter/issues/62146 for the kind of issues using the '--custom_for_pub' option to 
create a version string causes).

This is set up in the flutter engine build as follows: 
tools/gn has this line
  gn_args['dart_custom_version_for_pub'] = 'flutter'

and the Dart build rules have this line
  if (dart_custom_version_for_pub != "") {
    args += [
      "--custom_for_pub",
      dart_custom_version_for_pub,
    ]
  }

This option needs to be removed from make_version.py as we do not want the Dart SDK reporting a version that it is not.

**Comment by whesse** [comment]
Sounds good to me, we should land it.  But then we need to roll, to get it, right?

**Comment by a-siva** [comment]
> Sounds good to me, we should land it. But then we need to roll, to get it, right?

Yes, it is not going to help the current situation but it will avoid such issues in the future.

**Comment by natgross** [comment]
Same problem on Windows when doing 'flutter upgrade'

**Comment by franklinyow** [comment]
@a-siva 
Please re-evaluate this and do one of the following:

1. Add it to a milestone if it is still P1
2. Change priority label and add milestone if no longer P1
3. Close, if this issue is no longer needed

**Comment by vsmenon** [comment]
@athomas - are we clear to do this?  if so, can you reassign to @a-siva to land a fix?  if not, can you bump from Sept?

**Comment by athomas** [comment]
I did trigger the 3xH tryjob on asiva's CL to remove the flag and it was
green. So maybe we can just remove it? I'm not sure when this flag makes a
difference in our infrastructure, though.

In any case, this is hardly a P1 because Flutter infrastructure no longer
relies on this code path anymore. This is now only used in our 3xH infra.

**Comment by athomas** [comment]
a-siva has landed the CL.
