### ISSUE TITLE
Static updater tool get confused about error width when updating

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42835]
The updater tool is getting confused about the width of errors in the following program:

```dart
int fairlyLongNamedIntVariable = 3;
double longNamedDoubleVariable = 3.0;
void test(bool b) {
  bool numVariable = (b ? fairlyLongNamedIntVariable : longNamedDoubleVariable)
  ..notAMethod();
}
```

After the first run:

`tools/sdks/dart-sdk/bin/dart pkg/test_runner/tool/update_static_error_tests.dart --update-all ~/tmp/test.dart`

```dart
int fairlyLongNamedIntVariable = 3;
double longNamedDoubleVariable = 3.0;
void test(bool b) {
  bool numVariable = (b ? fairlyLongNamedIntVariable : longNamedDoubleVariable)
  //                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  // [analyzer] STATIC_TYPE_WARNING.INVALID_ASSIGNMENT
  //                    ^
  // [cfe] A value of type 'num' can't be assigned to a variable of type 'bool'.
  ..notAMethod();
  //^^^^^^^^^^
  // [analyzer] STATIC_TYPE_WARNING.UNDEFINED_METHOD
  // [cfe] The method 'notAMethod' isn't defined for the class 'num'.
}
```

A second run:

```dart
int fairlyLongNamedIntVariable = 3;
double longNamedDoubleVariable = 3.0;
void test(bool b) {
  bool numVariable = (b ? fairlyLongNamedIntVariable : longNamedDoubleVariable)
  //                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  // [analyzer] STATIC_TYPE_WARNING.INVALID_ASSIGNMENT
  //                    ^
  // [cfe] A value of type 'num' can't be assigned to a variable of type 'bool'.
  ..notAMethod();
  //^^^^^^^^^^
  // [analyzer] STATIC_TYPE_WARNING.UNDEFINED_METHOD
  // [cfe] The method 'notAMethod' isn't defined for the class 'num'.
}
```

A third run:

```dart
int fairlyLongNamedIntVariable = 3;
double longNamedDoubleVariable = 3.0;
void test(bool b) {
  bool numVariable = (b ? fairlyLongNamedIntVariable : longNamedDoubleVariable)
  //                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  // [analyzer] STATIC_TYPE_WARNING.INVALID_ASSIGNMENT
  //                    ^
  // [cfe] A value of type 'num' can't be assigned to a variable of type 'bool'.
  ..notAMethod();
  //^^^^^^^^^^
  // [analyzer] STATIC_TYPE_WARNING.UNDEFINED_METHOD
  // [cfe] The method 'notAMethod' isn't defined for the class 'num'.
}
```

Note: this was discovered because dartfmt chooses a different indentation depth for the comment above, so the tool was being re-run to update the offsets.

**Comment by leafpetersen** [comment]
Ok, turns out this is not an issue with the updater tool, per se.  It's much, much, better than that.  Per [this](https://github.com/dart-lang/sdk/issues/42865) issue, the analyzer, when it discovers an error on a cascade target, emits the error span using the `..` as the end token.  If there is a comment between the target and the end token, then it includes the length of the comment in the span.  If that comment happened to, say, include a unary encoding of that length, then the length that it spits out will be 2*old_length + a constant.  And if someone (or some static updater tool) were foolish enough to then update that comment with the new span, then... well... a second run would result in a span measuring.... yep.  4*old_length (plus a constant).

**Comment by leafpetersen** [comment]
This does cause some real difficulties, however, since not only can't use the static updater tool, but in fact, there's no way to encode a correct error expectation (since any expectation I encode contains the unary encoding of the correct expectation of running the code **without** the expectation, or with the last version of the expectation).  

I can probably work around this, possibly by keeping the code un-formattted, or possibly by using the non-unary syntax.

**Comment by munificent** [comment]
This doesn't help you use the automatic updater tool, but the static error syntax does support an explicit error location notation to help you work around weird cases like this. Instead of the `^^^` comment line, you can do a line like:

```dart
// [error line 123, column 45, length 678]
// [analyzer] CompileTimeErrorCode.FIRST
```

I think that's probably a sufficient workaround, though it does mean you'll have to manually maintain any static error test that uses this.
