### ISSUE TITLE
Chrome 85 has trouble to display the migration tool

### ISSUE THREAD

**Issue by sma** [dart-lang/sdk#42838]
#### Steps to reproduce

Just for fun, I tried to convert [this old code](http://sma.github.io/articles/2013/04/11/conquest-in-dart.html) but the web UI became completely unresponsive when trying to display the single 3486 lines long file. After a while I saw some code, but as soon as a started scrolling, the display of lines stopped after a 300+ lines before becoming unresponsive again and then spitting out a few more lines. I'm using Chrome 85, latest dev build.

I also tested Firefox 78.0.0.2 and while that Browser complained about "starting slow" it managed to display the file.

#### What did you expect to happen?

It should also work in Chrome, I guess.

#### What actually happened?

_Screenshots are appreciated_

![image](https://user-images.githubusercontent.com/14989/88465148-ee94e700-cec0-11ea-9001-eb51502128f9.png)

**Dart SDK version**: 2.9.0-21.0.dev

Thanks for filing!

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
