### ISSUE TITLE
--disable-dart-dev now required for running Dart sources in IntelliJ

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#42831]
Right clicking in IntelliJ and running some test now yields the error below:

`Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-dwarf_stack_traces_mode causal_async_stacks no-lazy_async_stacks lazy_dispatchers use_bare_instructions no-dedup_instructions no-"asserts" "use_field_guards" "use_osr" no-code-comments x64-sysv no-null-safety' but the VM has 'release no-dwarf_stack_traces_mode causal_async_stacks no-lazy_async_stacks lazy_dispatchers use_bare_instructions no-dedup_instructions "asserts" "use_field_guards" "use_osr" no-code-comments x64-sysv no-null-safety'`

The CLI is the same: `/path/to/sdk/ReleaseX64/dart-sdk/bin/dart --enable-asserts --enable-vm-service:57039 /Users/jwren/src/github/dart-sdk/sdk/pkg/analyzer/test/src/diagnostics/missing_return_test.dart`

The work-around for the time being is to manually change the run configuration to include the Dart VM option `--disable-dart-dev`

**Comment by bkonyi** [comment]
Already have a partial fix [here](https://dart-review.googlesource.com/c/sdk/+/155545). We're also going to need to switch from using a snapshot to a kernel file to handle mismatches between other flags that we can't change on a per-isolate basis: https://github.com/dart-lang/sdk/issues/42804.

**Comment by bkonyi** [comment]
This should be fixed for the `assert` case. The general fix will be tracked in #42804.

**Comment by devoncarew** [comment]
@johnniwinther - this might be the issue you saw? If it looks similar, can you re-test from the latest from master?

**Comment by johnniwinther** [comment]
It works both with the latest dev-release and with bleeding edge. Thanks!
