### ISSUE TITLE
Unable to pass --enable-experiement=non-nullable to `dart2native`

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#42849]
I am trying to build an AOT executable on Linux from an app that has been updated to be compatible with NNBD using `dart --enable-experiment=non-nullable`, which works fine, but when I try and build a standalone executable from that code, I am unable to.

When I build the executable using `dart2native`, I get the following error:

```
Error: This requires the 'non-nullable' language feature to be enabled.
Try updating your pubspec.yaml to set the minimum SDK constraint to 2.9 or higher, and running 'pub get'
```

My pubspec constraints are set to:
```
environment:
 sdk: '>=2.9.0 <2.11.0'
```

And I re-ran `pub get` before trying it (for both the dependent package I built, as well as for the executable). I also tried blowing away the `.dart_tool` directories.

I downloaded the dev SDK from the website:
`Dart SDK version: 2.10.0-0.0.dev (dev) (Wed Jul 22 19:58:38 2020 +0200) on "linux_x64"`

It seems like `dart2native` needs an `--enable-experiment` flag for this to work.

**Comment by mkustermann** [comment]
@cskau-g Could you look at this?

**Comment by HIHIQY1** [comment]
Any update on this issue?

**Comment by cskau-g** [comment]
I've had a look at it and it looks like a quick fix. A change is in review now.

**Comment by cskau-g** [comment]
[The fix](https://dart-review.googlesource.com/c/sdk/+/157963) has been merged.

Anyone interested can test it at HEAD now, but there will naturally be a little bit of time as the change makes its way into the next dev and stable releases.

There's nothing more to do from our side so I'll close this issue.

Thanks
