### ISSUE TITLE
--disassemble-optimized shows no output

### ISSUE THREAD

**Issue by dolpheen** [dart-lang/sdk#42841]
OS: MacOS
Dart Version: Tested on Dart VM version: 2.8.4 (stable) & Dart SDK version: 2.9.0-21.0.dev.flutter-20bf2fcf56

Using 

> ./dart --print-flow-graph-optimized --disassemble-optimized test.dart
Shows only
```
4
6
10
10
104
Instance of 'ClassSample'
Instance of 'ClassSample'
Instance of 'ClassSample'
```

While 
> ./dart --print-flow-graph --disassemble test.dart
Is OK and shows IL and ASM

**Comment by mkustermann** [comment]
@dolpheen Would you mind explaining what you are trying to do?

Our JIT is first compiling unoptimized code and runs this for some time to learn more about the program behavior. When functions were called enough times it will start optimizing such functions. Maybe that doesn't happen on your example?

**Comment by dolpheen** [comment]
@mkustermann
Just exploring Dart VM as mentioned in [https://github.com/dart-lang/sdk/blob/master/runtime/docs/index.md](url)
At the moment mostly interested in boxing/unboxing optimization of Ints.
Just wanted to see the optimized disassembly code for this with --disassemble-optimized, but no outputs. 
But if I understand you correctly - the optimization is not done on single run of code.

The code is simple,  
```dart
main()
{
  testFunction();
}

testFunction()
{
  // Local variables stored on Stack
  int k;
  int i = 4;
  int j = 6;
  k = i + j;
  
  print(i);
  print(j);
  print(k);
}
```

Thank you, I suppose then to close the question.
