### ISSUE TITLE
"Add missing required argument" fix does not appear for named constructor

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#42843]
(Extracted from https://github.com/Dart-Code/Dart-Code/issues/2643#issuecomment-664027590)

```dart
import 'package:flutter/widgets.dart';
import 'package:meta/meta.dart';

class MyWidget extends Widget {
  MyWidget({@required List<Widget> children});
  MyWidget.named({@required List<Widget> children});
}

Widget build() {
  return MyWidget.na^med(); // The parameter 'children' is required.
}
```

The "Add missing required argument" fix does not appear at the location of `^`, however if you use the default constructor, it does.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/156061
