### ISSUE TITLE
wrong type of class when using `IterableMixin` via `with` when used as value in a map while having NNBD enabled and implicit casts disabled

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/sdk#42848]
I'd expect this code to work, as `Foo` is an `Iterable<String>`, but the analyzer only sees an `Object` and results in a `return_of_invalid_type` error.

```dart
class Foo with IterableMixin<String> {
  @override
  Iterator<String> get iterator => ['foobar'].iterator;
}

class Bar {
  Map<String, Foo> things = {};

  Iterable<String> getThings(String id) => things[id] ?? <String>[];
}
````

The analyzer says: 
> error: A value of type 'Object' can't be returned from method 'getThings' because it has a return type of 'Iterable\<String\>'.

I am running `dartanalyzer --no-implicit-casts --enable-experiment non-nullable .` and this error isn't reported when running with implicit casts. I guess the implicit cast is from `Iterable<String>?` to `Iterable<String>`, but an explicit casts would get an `unnecessary_cast` hint.

Expanding the `??` and writing this works without any error:

```dart
Iterable<String> getThings(String id) {
  if (things[id] != null) return things[id];
  return <String>[];
}
````

If I extend `IterableMixin` instead of using `with` there is no error either.
````dart
class Foo extends IterableMixin<String> {
  @override
  Iterator<String> get iterator => ['foobar'].iterator;
}
````

So it seems like something is missing in handling `??` in combination with classes included via `with`.

EDIT: I am not sure if this happens because `IterableMixin` isn't actually a `mixin` but an `abstract class` instead.
EDIT 2: The error does not occur when using `ListMixin` instead of `IterableMixin`.

Dart version: Dart SDK version: 2.10.0-0.0.dev (dev) (Wed Jul 22 19:58:38 2020 +0200) on "windows_x64"

**Comment by lrhn** [comment]
My best guess is that it's a failure of the LUB (least upper bound) that is used to find the type of `things[id] ?? <String>[]`.

The least upper bound of `Foo` and `List<String>`, the two types which are the possible results of the expression, is apparently not recognized to be `Iterable<String>`. I'm guessing it *should* be, but the LUB computation is notoriously fickle.

**Comment by denniskaselow** [comment]
Seems to be the case. `things[id] ?? Iterable.castFrom(<String>[])` does work.

**Comment by srawlins** [comment]
This code works under the new type analysis in null safety.
