### ISSUE TITLE
shadowing of generic types 

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#42854]
While writing an extension method for Flutter's ValueListenable I ran into an error message that I couldn't understand because the error message:

'argument of type T can' be assigned to parameter of type T' wasn't helpful. 
It turned out that I had defined another gerneric parameter called T inside a generic extension method that used T too.

![image](https://user-images.githubusercontent.com/16635729/88590326-cc36d100-d05a-11ea-9c94-a5428cef296c.png)

You can see the behavior on this branch of my repository

https://github.com/escamoteur/listenable_pipe/tree/generic-type-shadowing

It would be very helpful if the compiler or linter could give more help here.

* Dart SDK Version (`dart --version`)
 Dart version 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows

**Comment by srawlins** [comment]
There is a lint rule for this: https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html
