### ISSUE TITLE
create a style guide for the command line UI for dart

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#42864]
There's more discussion here: https://github.com/dart-lang/sdk/issues/42484, but generally, we'd like a style guide for the command line UI for the dart tool. This will help us ensure that we have a consistent UI between commands, and can help guide us when adding new commands or options.

Here's one item we've found for the style guide:

```
If the verb cannot have side effects (such as analyze) then the argument for what to operate on should default to the CWD, but if the verb can have side effects (such as format or fix) then the argument for what to operate on should be required.
```

cc @mit-mit @jwren @munificent @bwilkerson 

I'd suggest we just start a markdown file at https://github.com/dart-lang/sdk/tree/master/pkg/dartdev as that's pretty low cost to get started.

**Comment by bwilkerson** [comment]
I've started a doc with https://dart-review.googlesource.com/c/sdk/+/156380. It needs to be more fully fleshed out, but there's a start, so I'm going to close this issue.
