### ISSUE TITLE
Analyzer produces very long offsets for some error messages

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42865]
Not sure if this is at all important or not, but I noticed this anomaly, and it occurred to me that it might affect the UX in IDEs as well.  Consider the following program:

```dart
void main(int x) {
  {
    List<int> y = ((x == x) ? "hello" : "world")
    // Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
    // tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
    // veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
    // commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
    // velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
    // occaecat cupidatat non proident, sunt in culpa qui officia deserunt
    // mollit anim id est laborum.
      ..toString();
  }
}
```

When analyzer using the `--format=machine` option, the analyzer produces the following result:

```
ERROR|COMPILE_TIME_ERROR|INVALID_ASSIGNMENT|/Users/leafp/tmp/test.dart|3|19|544|A value of type 'String' can't be assigned to a variable of type 'List<int>'.
```

Note the width of the error, `544`.  I believe the analyzer is using the span to the `..` token as the width of the error, thereby including all of the intervening comment in the error.  Interestingly, if I eliminate the cascade leaving only the semicolon, the span appears "correct".

**Comment by leafpetersen** [comment]
Hilariously, this causes a classic self-reference bug in the [static updater tool](https://github.com/dart-lang/sdk/issues/42835#issuecomment-665387117).

**Comment by bwilkerson** [comment]
In most places we attempt to highlight a single token, but in a few places it isn't clear how to do that or that that's the best UX. In this case we _could_ highlight the assignment operator, but consider the analogous situation where the assignment is to a parameter:
```
void f(List<int> y) {}
void g(int x) {
  f(((x == x) ? "hello" : "world")
    // Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
    // tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
    // veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
    // commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
    // velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
    // occaecat cupidatat non proident, sunt in culpa qui officia deserunt
    // mollit anim id est laborum.
      ..toString());
}
```

It isn't clear in this case what to highlight other than the entire argument expression. For consistency we chose to highlight the entire right-hand side of an assignment expression.

I'm not super happy with highlighting an arbitrary amount of code like this and would love to hear suggestions for how to improve the highlighting.

**Comment by leafpetersen** [comment]
If cascades are the only thing example of something where the thing being assigned is different from the syntactic expression in the assignment position, then it seems like special casing cascades could work: given an invalid assignment where `e..<cascades>` is the thing being assigned, report the error on `e` only.  Don't know if that's pragmatically feasible.  Interestingly, if I take your argument example and remove the `..toString()` then the error gets reported without including the comment, which is good - that's probably a much more common case.

I don't feel strongly that this needs to be fixed, so feel free to close out as infeasible.  I just filed it since I happened to notice it and it seemed worth mentioning.

**Comment by bwilkerson** [comment]
It's definitely feasible to fix this (analyzer has all the position information it needs), we'd "just" need to define what behavior we want.

**Comment by scheglov** [comment]
I actually noticed this issue in the new LUB tests, and started a change to analyzer to alleviate this.
So, with cascade expressions the type issue is in the target, and with this change to analyzer it will highlight the target.
And also diving into parenthesized expressions.

https://dart-review.googlesource.com/c/sdk/+/156067

**Comment by leafpetersen** [comment]
@scheglov I think you fixed this, can I close it?
