### ISSUE TITLE
Missing exclamation mark in override (Null Safety migration tool)

### ISSUE THREAD

**Issue by michalt** [dart-lang/sdk#42862]
Consider the following snippet:

```dart
dynamic doSth() => 'something';

abstract class Foo {
  String /*!*/ foo();
}

class Bar extends Foo {
  @override
  String foo() => doSth()?.toString();
}
```

The migration tool correctly sets the return type of the `Bar.foo` to be `String` since it's explicitly hinted. But it does not add an exclamation mark to the body, which means that the generated code doesn't compile:

```dart
dynamic doSth() => 'something';

abstract class Foo {
  String /*!*/ foo();
}

class Bar extends Foo {
  @override
  String  foo() => doSth()?.toString();
}
```

**Comment by michalt** [comment]
@stereotype441

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
