### ISSUE TITLE
Don't reset the source view when applying a hint (Null Safety Migration tool)

### ISSUE THREAD

**Issue by michalt** [dart-lang/sdk#42861]
#### Steps to reproduce & what happened

1. Click to apply the hint
2. Source viewer is reset and shows the top of the file

#### What did you expect to happen?

I would like if the source viewer continued showing the location where I was clicking to apply the hint. Otherwise, applying a bunch of hints is very tedious (since one needs to scroll back down from the top after each hint application)

**Dart SDK version**: 2.10.323325861-edge+google3-v2

**Comment by michalt** [comment]
@stereotype441

**Comment by stereotype441** [comment]
@Hixie is running into this as well when trying to use the tool on Flutter

**Comment by srawlins** [comment]
This should be fixed.
