### ISSUE TITLE
dartdev run command doesn't handle Windows drive letters

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#42874]
Running `dart run c:\src\dart-repo2\sdk\temp\abstract.dart` results in 
```
Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2710:7)
#1      RunCommand.run (package:dartdev/src/commands/run.dart:132:10)
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#3      DartdevRunner.runCommand (package:dartdev/dartdev.dart:238:24)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:223:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      runDartdev (package:dartdev/dartdev.dart:107:27)
#8      main (file:///c:/src/dart-repo2/sdk/pkg/dartdev/bin/dartdev.dart:13:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by johnniwinther** [comment]
See also #42779 for the unhandled corner case of running `dart run \\?\c:\src\dart-repo2\sdk\temp\abstract.dart`.

**Comment by franklinyow** [comment]
FYI @devoncarew

**Comment by devoncarew** [comment]
Assigning to Ben for triage.

**Comment by bkonyi** [comment]
@zichangg is investigating #42779 which this is related to. Zichang, feel free to reach out to me if you need any help with this. I'm guessing we'll just need to update some logic in `pkg/dartdev/lib/src/commands/run.dart` to handle this case.

**Comment by devoncarew** [comment]
Thanks! Franklin brings up the good point that this may be something that we'd want to have in for the coming branch for trhe next beta, ~monday next week.

**Comment by devoncarew** [comment]
@zichangg - I believe this is fixed now?

**Comment by zichangg** [comment]
Yes.
For "\\?\" prefixed string, it needs some works in frontend to get it fixed and it will be tracked in the other issue.
