### ISSUE TITLE
Coverage collection fails with 2.10.0-1.0.dev

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#42876]
`package:coverage` tests have been failing at head with the dev SDK for a couple days now. See: https://travis-ci.org/github/dart-lang/coverage/jobs/712777426

It appears the test application does not exit as this never returns here:
https://github.com/dart-lang/coverage/blob/7e18328a0fcb9353d2ad68748b66f5f5cb7c253c/test/lcov_test.dart#L184

Running the test application directly works as expected so something very odd is happening. To make things even more peculiar, my machine will eventually run out of memory due to a rogue Dart process, presumably the one started by the coverage test.

**Comment by a-siva** [comment]
This might be a duplicate of https://github.com/dart-lang/sdk/issues/42819, are you able to reproduce this on bleeding edge ?

//cc @bkonyi

**Comment by bkonyi** [comment]
Yes, this is likely a duplicate of #42819 and should be fixed on bleeding edge.

**Comment by grouma** [comment]
Great. Thanks!
