### ISSUE TITLE
How i can to read .P7M ssl files ?

### ISSUE THREAD

**Issue by maurobotta** [dart-lang/sdk#42897]
Hi

For invoice electronic i need read and decrypt inside a Dart Http Server a p7m files,

How i can have this decode on Dart ?

openssl.exe cms -verify -noverify -in xxxxxxxxxxxxxxxxx.xml.p7m -inform DER -out zzzzzzzzzzzzzzzzzzzzz.xml

**Comment by srawlins** [comment]
General help questions should be posted on a forum like StackOverflow or [Dart Misc](https://groups.google.com/a/dartlang.org/g/misc). The GitHub issue tracker is not a good place to ask questions.
