### ISSUE TITLE
Different values for Error.stackTrace and IndexError.stackTrace in VM and dart2js

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42896]
The following test works in VM but fails on dart2js
```dart
import "../../../Utils/expect.dart";

main() {
  Error e = new Error();
  Expect.isNull(e.stackTrace); 
}
```
dart2js output is
```
Runtime error:
Expect.isNull(actual: <>) fails.
```

**Comment by lrhn** [comment]
That's a dart2js bug, already reported as #41763. 
The stack trace should be filled in when the error is *thrown*, not when the `stackTrace` getter is first read.
