### ISSUE TITLE
Automate dev rolls

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#42917]
See go/aligning-dart-dev-releases-with-rolls for additional context.

- [x] Create a recipe that calculates the last known good revision (LKGR) based on a configured subset of builders to dev (https://dart-review.googlesource.com/c/recipes/+/157501, https://dart-review.googlesource.com/c/sdk/+/157491).
- [x] Create a recipe that merges the latest LKGR to dev (https://dart-review.googlesource.com/c/recipes/+/157960, https://dart-review.googlesource.com/c/sdk/+/158000, https://dart-review.googlesource.com/c/sdk/+/157983).
- [x] Make external/g3 builder integration work to enable integration with internal smoke tests (internal part: b/162701896).
- [x] Add ACLs to allow roll gardeners to trigger a manual roll with `bb add` (https://dart-review.googlesource.com/c/sdk/+/158391).
- [x] Update the release tooling to no longer merge to dev (cl/326215543).
- [x] Fix https://github.com/dart-lang/sdk/issues/42820 (Optional).

**Comment by franklinyow** [comment]
Moving this Sept milestone.

**Comment by athomas** [comment]
@pcsosinski FYI

**Comment by athomas** [comment]
Done
