### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by leyeisaac** [dart-lang/sdk#42914]
## Version information

- `IDEA AI-193.6911.18.40.6626763`
- `2.8.4`
- `AI-193.6911.18.40.6626763, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

**Comment by srawlins** [comment]
Thanks for opening an issue! Please share any stack traces you that IntelliJ shows when crashing in this manner.

**Comment by srawlins** [comment]
Closing for now; feel free to re-open if this is seen on the latest version of Dart.
