### ISSUE TITLE
double.toStringAsFixed fails on dartdevk weak mode failure

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42919]
The following code fails on dartdevk weak mode and works on all onther NNBD platforms
```dart
import "../../../Utils/expect.dart";

dynamic getNull() => null;

check(double val) {
  Expect.throws(() => val.toStringAsFixed(getNull()), null, "Failed for '$val'");
}

main() {
  check(0.0);
}
```

**Comment by lrhn** [comment]
Seems the dartdevk implementation doesn't check the nullability of the non-nullable parameter. 
I think that's acceptable behavior in weak mode, but we might want to keep consistency across our compilers anyway.
