### ISSUE TITLE
Expected a value of type 'int', but got one of type 'double'

### ISSUE THREAD

**Issue by SongHuaixu** [dart-lang/sdk#42913]
```
  List<int> ints = [];

  void func() {
    List<num> nums = ints;
    nums.add(3.14);
  }
```

Flutter 1.21.0-6.0.pre.141 • channel master •
https://github.com/flutter/flutter.git
Framework • revision c748f1a7aa (31 hours ago) • 2020-07-31 17:45:18 -0700
Engine • revision 280bbfc763
Tools • Dart 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)

**Comment by mraleph** [comment]
Generics in Dart are covariant - so this is working as expected.
