### ISSUE TITLE
"Uncaught Error: TypeError [...]" at runtime - Inference issue?

### ISSUE THREAD

**Issue by iapicca** [dart-lang/sdk#42925]
Hi all,
I don't know if this was always the case or it's me noticing only now;

this [code](https://dartpad.dartlang.org/5a530835418d126a2543df453a785f29) doesn't throw any error until runtime,
then at runtime then throws  `Uncaught Error: TypeError: Instance of 'Square': type 'Square' is not a subtype of type 'Circle'`

Shouldn't this error be cough before?
Thank you

**Comment by srawlins** [comment]
See https://github.com/dart-lang/language/issues/1124; Dart currently has implicit casts. Fixed with a few things mentioned in the response.
