### ISSUE TITLE
tests/kernel is unmigrated

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#42926]
The `tests/kernel` suite is unmigrated (maybe because it was never called `kernel_2`?) and therefore fails on NNBD builders.

@johnniwinther: Does someone own this suite and its migration?

**Comment by johnniwinther** [comment]
@stefantsov @jensjoha Do you know about this suite (origin, purpose, ...) ?

**Comment by jensjoha** [comment]
I think it's from the good old days. Most was landed here I think: https://codereview.chromium.org/2451623006

**Comment by johnniwinther** [comment]
Does it still serve a purpose or should be remove it?

**Comment by jensjoha** [comment]
That's probably anyones best guess.

**Comment by johnniwinther** [comment]
@mraleph Do you have any insight here?

**Comment by mraleph** [comment]
These are micro regressions tests written during initial Kernel development (and its integration with VM). 

You can see their history on the file by file basis here: https://github.com/dart-archive/kernel_sdk/tree/aot/tests/dill

I don't know how to assess whether they are still useful or not, but I think we might be able to delete them without any coverage loss if we don't to migrate them.

**Comment by johnniwinther** [comment]
Thanks. I'll look into whether we should migrate or remove them.

**Comment by fishythefish** [comment]
Friendly bump. :)
