### ISSUE TITLE
Memory leak in vm/dart_2/scavenger_abort_test

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#42934]
The asan bot turned red recently due to this failure:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8872940304329006048/+/steps/test_results/0/logs/new_test_failures__logs_/0

From the results feed, the culprit seems to be [d3945b](https://github.com/dart-lang/sdk/commit/d3945b56f737ccaf55c86ef0795fce931f44ee7e), but this CL doesn't seem very suspicious to me.

**Comment by rmacnak-google** [comment]
This would have been introduced flakily with 3a821631fb3cecebd74825c98edd08204e3f6b3f.
