### ISSUE TITLE
VM const evaluation fails to recognize `2 == 2.0`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#42946]
See: https://stackoverflow.com/questions/63261894/int-and-double-equality-with-const-in-dart

Example:
```dart
main() {
  const x = (2 == 2.0);
  print(x); // prints `false`
}
```
This should print `true`, and it does so for dart2js (according to dartpad), so it seems to be a VM issue.

Tested with the following VMs:
* 2.10.0-3.0.dev
* 2.9.0-21.4-beta

on Windows (Chocolatey installs).

**Comment by mraleph** [comment]
Constant evaluation is done in the front-end, so it's a front-end issue.

**Comment by lfkdsk** [comment]
fix it https://github.com/dart-lang/sdk/pull/42949
