### ISSUE TITLE
HTTP request profiling should surface body information

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#42952]
The HTTP request profiling code currently surfaces request/response metadata and headers via the timeline. We'd also like to be able to surface the body of the request/response in some fashion.

**Comment by bkonyi** [comment]
@zichangg I'm a bit bogged down with other work right now, think you can take this on for me?

**Comment by zichangg** [comment]
sure thing!

**Comment by yy1300326388** [comment]
Hope to see the response data, this is a very urgent need.
