### ISSUE TITLE
Strange (and breaking) behavior for _AllMatchesIterator

### ISSUE THREAD

**Issue by znjameswu** [dart-lang/sdk#42950]
Dart sdk version: 2.9.0
Platform: Win10 x64

There is an undocumented breaking changes introduced for `_AllMatchesIterator` (returned by `RegExp.allMatches().iterator`)

```dart
void main() {
  final regex = RegExp('[0-9]');
  final it = regex.allMatches('0').iterator;
  final pos = it.current; // exception!
  it.moveNext();
  it.moveNext();
}
```
The above code will throw `_CastError`: Null check operator used on a null value.

This is caused by https://github.com/dart-lang/sdk/blob/d44457f79d087b52a0468609d44013e5fd9f09f0/sdk/lib/_internal/vm/lib/regexp_patch.dart#L379

I understand that iterators need to perform at least one `moveNext()` to start reading. However, other iterators don't have this kind of issue:
```dart
void main() {
  final it = [1,2].iterator;
  it.current; // perfectly fine
}
```

And I think it is an widely-used pattern to check for `Iterator.current`'s nullability (at least in my code). Throwing null exception inside an internal implementation is really to hard to track for users. So please offer more detailed information for this change.

**Comment by znjameswu** [comment]
Found the announcement. https://github.com/dart-lang/sdk/issues/40674

Seems resonable. And the reason that the second example passed seems to be related to this coding style:
https://github.com/dart-lang/sdk/blob/d44457f79d087b52a0468609d44013e5fd9f09f0/sdk/lib/internal/iterable.dart#L330

I think I understand the design now. However I think the discrepency between those examples should be sorted out.

**Comment by lrhn** [comment]
Agree, the list iterator should probably also be throwing in Null Safety mode.

**Comment by znjameswu** [comment]
> Agree, the list iterator should probably also be throwing in Null Safety mode.

One thing I forgot to mention is the above behavior is not inside Null Safety mode. I didn't turn on non-nullable features and get this error in my code.
