### ISSUE TITLE
CFE lowering for statics with initilizers?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42956]
The NNBD spec states
> A toplevel or static variable with an initializer is evaluated as if it was marked `late`.

https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables

Right now the web backends are failing co19 tests because they are failing to throw a `LateInitializationError` when final static fields are being set multiple times. 
https://github.com/dart-lang/co19/blob/master/Language/Variables/Evaluation_of_Implicit_Variable_Getters/definition_t02.dart

I think it would be helpful if the CFE provided the same lowering as if it were marked `late`.

@johnniwinther @fishythefish WDYT?

**Comment by fishythefish** [comment]
+1 from me. I think this should be treated as syntactic sugar and desugared by the CFE accordingly. dart2js and DDC have essentially identical failures on these co19 tests.

**Comment by johnniwinther** [comment]
Sounds like a good idea. I'll look into if this is feasible within a short time span so that you can avoid the work on both backends.

**Comment by johnniwinther** [comment]
I've created https://dart-review.googlesource.com/c/sdk/+/160724 that adds a `Target.useStaticFieldLowering` flag that, when enabled, encodes top-level/static fields with initializers in opt-in libraries as late fields.

I don't think it is useful for dart2js, at least, since the lowering invalidates the eager static field optimization.

Try it out and let me know what you think.

**Comment by nshahan** [comment]
@johnniwinther I tried flipping the flag in the `DevCompilerTarget` and building the sdk. I got a wall of errors that is too long to post here. Many of them look like:

```
org-dartlang-sdk:///lib/_internal/js_dev_runtime/patch/core_patch.dart:173:14: Context: The invocation of 'patch' is not allowed in a constant expression.
  static int parse(String source,
             ^
```

Is there anything else I need to do when setting `Target.useStaticFieldLowering` to `true`?

**Comment by johnniwinther** [comment]
I lowering const fields as well - I shouldn't have. Working on a fix.

**Comment by johnniwinther** [comment]
The fix: https://dart-review.googlesource.com/c/sdk/+/161505

**Comment by johnniwinther** [comment]
... and a fix for that: https://dart-review.googlesource.com/c/sdk/+/161700

**Comment by leafpetersen** [comment]
Is this fixed?

**Comment by nshahan** [comment]
> Is this fixed? 

Not yet. I'm still investigating the lowering with the latest fix linked above and there are still crashed in DDC. AFAIK the test is still failing on dart2js but they might be opting to implement it themselves.
