### ISSUE TITLE
dart:developer ServiceProtocolInfo class should include the ws url

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#42968]
The dart:developer ServiceProtocolInfo class has a field for the Observatory (http) url to connect to, to see the web client:

https://api.dart.dev/stable/2.9.0/dart-developer/ServiceProtocolInfo-class.html

but it doesn't include the `ws:` url to use to connect to from tools (DevTools, IntelliJ, ...). We should include that field so that people using this API don't have to form the ws: url from the http: one.

**Comment by devoncarew** [comment]
cc @bkonyi

**Comment by bkonyi** [comment]
@rmacnak-google any objection to this?
