### ISSUE TITLE
"--enable-vm-service=0" prevents setting JSON test reporter when running with pub snapshot

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#42963]
Using a recent nightly build, this command runs a test as expected:

```
export DartPath="/Users/danny/Dev/Dart SDKs/nightly-2020-08-04/bin/"
$DartPath/dart $DartPath/snapshots/pub.dart.snapshot run test -r json -j1 test/danny_test.dart
```

However if you add `--enable-vm-service=0` (which is what VS Code does), it fails:

```
export DartPath="/Users/danny/Dev/Dart SDKs/nightly-2020-08-04/bin/"
$DartPath/dart --enable-vm-service=0 $DartPath/snapshots/pub.dart.snapshot run test -r json -j1 test/danny_test.dart

Could not find an option or flag "-r".
```

I'm not really sure why this happens (the `-r` flag is in the first command too), but it's preventing running tests from VS Code.

(cc @bkonyi - not sure if this is dartdev/dds related?)

**Comment by bkonyi** [comment]
Yup, this is dartdev related. Tracking here: https://github.com/dart-lang/sdk/issues/42941.

**Comment by DanTup** [comment]
Oops - not sure how I missed that one! Thanks!
