### ISSUE TITLE
Package:js Browser Refresh Callback

### ISSUE THREAD

**Issue by sidrao2006** [dart-lang/sdk#42978]
## Use case

This feature can be very useful to detect browser refreshes especially for forms or text inputs. The users can be notified that their data will be lost. Also (in my case) when use packages like [flutter_screenutil](https://pub.dev/packages/flutter_screenutil), the draft data is lost upon browser refresh and errors are logged.

## Proposal

I think this feature can be added to the `package:js`. Using dart for this feature would solve this issue.
A dart (through `package:js`) callback would do. In flutter, setState can be called in the callback, to update changes.
Or in my case, I can call navigator.push in the callback to go back to the home screen from where I will navigate back to the screen.

This issue was opened as a [feature request](https://github.com/flutter/flutter/issues/63085) in the flutter repository.

#### `dart --version`

`Dart SDK version: 2.9.0-21.10.beta (beta) (Tue Jul 21 10:46:30 2020 +0200) on "windows_x64"`

#### `flutter --version`

```
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (6 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)
```

#### `flutter doctor `

```
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (3 available)
```

**Comment by natebosch** [comment]
This is exposed through `dart:html`. The name you are looking for is `onBeforeUnload` - this is the capability provided by the browser.

https://api.dart.dev/stable/2.9.0/dart-html/Window/onBeforeUnload.html

**Comment by sidrao2006** [comment]
@natebosch, `dart:html` package cannot be called from flutter as the dart sdk that ships with flutter does not include `dart:html`

Please reopen this issue

**Comment by natebosch** [comment]
@jonahwilliams - is `dart:html` usable in flutter web or was that removed?

@sidrao2006 - if `dart:html` is not available you could try using `package:js` style interop. See the README for usage instructions. We don't add specific APIs in `package:js`. The following seems to work for me:

```dart
@JS()
library onBeforeUnload;

import 'package:js/js.dart';

@JS('onbeforeunload')
external set _onBeforeUnload(String Function(dynamic) callback);

void onBeforeUnload(String Function() callback) {
  _onBeforeUnload = allowInterop((_) => callback());
}

void main() {
  onBeforeUnload(() {
    return '';
  });
}
```

With `return '';` the browser will show an alert to confirm before navigating away. With `return null;` the navigation is allowed.

**Comment by jonahwilliams** [comment]
dart:html is still available
