### ISSUE TITLE
Unexpected type inference difference with `dynamic` and `Object`.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#42970]
The following / [attached bug1b6n.dart.txt](https://github.com/dart-lang/sdk/files/5036549/bug1b6n.dart.txt) program
produces this output (VM and dart2js):
```
CR<int>
CR<int>
Object
Object
Object
Object
[CS([]), CS([]), CS([]), CS([]), CS([]), CS([])]
[CR<int>, CR<int>, CR<int>, CR<int>, CR<int>, CR<int>]
```
The first six types printed are from the statement `print(R);`.
The type argument passed to `AR.run.R` is inferred differently depending on whether the result of `run` is passed to a `castXX` method with a `dynamic` or `Object` parameter type.
This seems like it must be a bug to treat two 'top' types differently.
- enabling nnbd and using `Object?` has the same discrepancy
- adding an explicit cast to the `dynamic` case (i.e. `T cast1o<T>(dynamic any) => any as T;`) makes no difference.

/cc @leafpetersen @johnniwinther 

`bug1b6m.dart`:
```dart
import 'dart:async';

@pragma('dart2js:tryInline')
T cast1i<T>(dynamic any) => any;

@pragma('dart2js:noInline')
T cast1o<T>(dynamic any) => any;

@pragma('dart2js:as:trust')
@pragma('dart2js:tryInline')
T cast2i<T>(Object any) => any as T;

@pragma('dart2js:as:trust')
@pragma('dart2js:noInline')
T cast2o<T>(Object any) => any as T;

@pragma('dart2js:as:check')
@pragma('dart2js:tryInline')
T cast3i<T>(Object any) => any as T;

@pragma('dart2js:as:check')
@pragma('dart2js:noInline')
T cast3o<T>(Object any) => any as T;

class CR<T> {
  List<T> _a;
  CR(this._a);
  toString() => 'CS($_a)';
}

class AR {
  @pragma('dart2js:noInline')
  FutureOr<R> run<R>(FutureOr<R> Function() callback) {
    print(R);
    return callback();
  }

  CR<T> boot1i<T>(List<T> a) {
    return cast1i(run(() {
      return CR(a);
    }));
  }

  CR<T> boot1o<T>(List<T> a) {
    return cast1o(run(() {
      return CR(a);
    }));
  }

  CR<T> boot2i<T>(List<T> a) {
    return cast2i(run(() {
      return CR(a);
    }));
  }

  CR<T> boot2o<T>(List<T> a) {
    return cast2o(run(() {
      return CR(a);
    }));
  }

  CR<T> boot3i<T>(List<T> a) {
    return cast3i(run(() {
      return CR(a);
    }));
  }

  CR<T> boot3o<T>(List<T> a) {
    return cast3o(run(() {
      return CR(a);
    }));
  }
}

main() {
  var ar = AR();
  var c1i = ar.boot1i(<int>[]);
  var c1o = ar.boot1o(<int>[]);
  var c2i = ar.boot2i(<int>[]);
  var c2o = ar.boot2o(<int>[]);
  var c3i = ar.boot3i(<int>[]);
  var c3o = ar.boot3o(<int>[]);
  var L = [c1i, c1o, c2i, c2o, c3i, c3o];
  print(L);
  print(L.map((x) => x.runtimeType).toList());
}
```

**Comment by leafpetersen** [comment]
Yes, this is expected.  Simpler example:

```dart
R run<R>(R Function() callback) {
  print(R);
  return callback();
}
main() {
  dynamic x = run(() => 3);
  Object y = run(() => 3);
}
```

Downwards inference in general takes preference over upwards inference because of unsound covariance.  (Arguably we should not do so for generic functions since they are soundly variant, and I've been considering changing it in a future language release, but currently it does.)  However, a downwards context of `dynamic` is not treated as a constraint, but rather as a lack of constraints.  So for the first line, the call to `run` is inferred with no downwards constraints, which means that upwards inference is used to choose `R` and `int` is the result.  For the second line, the call to `run` is inferred with a downwards constraint of `Object`, which constrains `R` to be `Object`, and upwards inference is not allowed to further refine the  result.

**Comment by rakudrama** [comment]
Thanks for the explanation.

To confirm we understand, a `T cast<T>(...)...` method that is intended to replace an `as` expression should be written with a `dynamic` parameter type to prevent the addition of a constraint that could modify the operation of type inference.

**Comment by leafpetersen** [comment]
Yes using `dynamic` as the parameter type should do what you want.

**Comment by johnniwinther** [comment]
Closing this issue as there seems to be no action item.
