### ISSUE TITLE
NNBD. Analyzer error for non-nullable abstract field

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42979]
According to the https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/feature-specification.md abstract fields are allowed. But the following programm works in CFE but fails in analyzer
```dart
abstract class C {
  abstract int x; // Analyzer error - Non-nullable instance field 'x' must be initialized.
}

class D extends C {
  int x = 1;
}

main() {
  new D();
}
```
There must be no analyzer error
`Dart SDK version: 2.10.0-3.0.dev (dev) (Tue Aug 4 12:29:57 2020 +0200) on "windows_x64"`

**Comment by stereotype441** [comment]
Fixed by 8076c9efd73e5b8c1ff00bb5bd87c741ad4d0172
