### ISSUE TITLE
remove the bin/model/lexeme/model.tflite model file from the dart sdk

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#42988]
We're not currently using the ML completion model file from the SDK. We should remove it - to save size for the user on SDK downloads - and re-add once we're consuming this file again.

There are some related (smaller) metadata files, that we may also consider removing.

```
dart-sdk/bin/model/lexeme/
  model.tflite, ~110MB
  idx2word.json, ~2.5MB
  word2idx.json, ~2.5MB
```

**Comment by bwilkerson** [comment]
Removing the `model.tflite` file appears to be non-breaking (that is, I can still build locally). Removing all three files causes a local build to break.

The reason is that the build scripts depend on these files and I don't yet know enough about the build system to know how to change it. I know that `sdk/BUILD.gn` defines a target named `copy_language_model` that references those files, but removing that reference doesn't appear to be sufficient. Who would I talk to to learn more? @dart-engprod

**Comment by devoncarew** [comment]
I don't see references to the word2idx.json or idx2word.json from from https://github.com/dart-lang/sdk/blob/master/sdk/BUILD.gn. I suspect that the copy_language_model task can be removed from the build script. It may be necessary to do a full rebuild of the gn build then given that some of the previous build targets no longer exist.

**Comment by bwilkerson** [comment]
Ok, I'm confused. I removed the file `bin/model/lexeme/model.tflite` from the SDK. I also removed two places to which it appeared to have been copied (both in directories that were being ignored). `git` tells me that there are no changes on my branch. Running `gclient hooks` causes the file (and one of the copies) to be reinstalled.

@whesse Any idea what's going on here and how I can remove this file?

**Comment by devoncarew** [comment]
I believe it's being brought in via the DEPS file: https://github.com/dart-lang/sdk/blob/master/DEPS#L486. It's a CIPD dependency - we'e copying from the dart/language_model CIPD bucket into the //pkg/analysis_server/language_model/ directory.

I think we'll need to remove the provisioning step in the DEPS file and the copy_language_model step in the sdk/BUILD.gn file.

**Comment by bwilkerson** [comment]
> I believe it's being brought in via the DEPS file ...

Yes, @whesse just IM'd be the same information.

> I think we'll need to remove the provisioning step in the DEPS file and the copy_language_model step in the sdk/BUILD.gn file.

If that proves to be insufficient, the other possibility is to remove model.tflite from the CIPD bucket. I believe that doing so would have the effect of removing that one file, which is the minimum goal here.

**Comment by devoncarew** [comment]
This is complete now.
