### ISSUE TITLE
consider making dart_api_dl.cc a pure C file

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#42982]
Currently it is a C++ file - which makes it impossible to reuse it in languages which allow simple consumption of C code (e.g. Go).

**Comment by mraleph** [comment]
I made an example of making it a pure C file here: https://github.com/mraleph/go_dart_ffi_example/blob/master/dart_api_dl/include/dart_api_dl.c - so maybe we should just land it unless there is any opposition. 

/cc @dcharkes

**Comment by dcharkes** [comment]
sgtm

**Comment by dcharkes** [comment]
@mraleph, I adapted your solution to https://dart-review.googlesource.com/c/sdk/+/157965.
