### ISSUE TITLE
Cannot compile with dart2native using sdk 2.9.0

### ISSUE THREAD

**Issue by l7ssha** [dart-lang/sdk#42983]
After updating sdk to 2.9.0 I cannot compile my project with `dart2native` tool.

Slice of the total output:

```
bin/running_on_dart.dart:136:9: Error: This requires the 'non-nullable' language feature to be enabled.
Try updating your pubspec.yaml to set the minimum SDK constraint to 2.9 or higher, and running 'pub get'.
  String? avatarUrl;
        ^
bin/running_on_dart.dart:321:19: Error: This requires the 'non-nullable' language feature to be enabled.
Try updating your pubspec.yaml to set the minimum SDK constraint to 2.9 or higher, and running 'pub get'.
    context.author!.id == 302359032612651009;
                  ^
bin/running_on_dart.dart:325:26: Error: This requires the 'non-nullable' language feature to be enabled.
Try updating your pubspec.yaml to set the minimum SDK constraint to 2.9 or higher, and running 'pub get'.
    return context.author!.id == Platform.environment["ROD_ADMIN_ID"];
                         ^


Failed to generate native files:
Generating AOT kernel dill failed!
```

It throws such errors for any nnbd related stuff in project I tried to compile and my other project that is used by application.

Links:
 - project i tried to compile: https://github.com/l7ssha/running_on_dart
 - other project with nndb features enabled Im using: https://github.com/l7ssha/nyxx

* Dart SDK: `2.9.0`
* `Linux lusha-pc 5.7.12-1-MANJARO #1 SMP PREEMPT Fri Jul 31 21:27:16 UTC 2020 x86_64 GNU/Linux`

**Comment by a-siva** [comment]
The non-nullable language feature is not supported in Dart SDK 2.9.0 version.

You would have to update the sdk constraint in the pubspec.yaml file in your package for this to work.

**Comment by l7ssha** [comment]
but i do have set sdk contraint to 2.9.0. I sent link to my code
