### ISSUE TITLE
No error in analyzer if abstract field is declared in an non-abstract class

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42980]
According to the https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/feature-specification.md abstract fields are allowed. But they must be declared in an abstract class. The following program produces an error in CFE but no issues in analyzer
```dart
class C {
//    ^
// [analyzer] unspecified
// [cfe] unspecified
  abstract int? x;
}

main() {
  new C();
}
```
Class `C` here is not an abstract therefore it must be an error in analyzer
`Dart SDK version: 2.10.0-3.0.dev (dev) (Tue Aug 4 12:29:57 2020 +0200) on "windows_x64"`

**Comment by stereotype441** [comment]
Fixed by 8b2576fe66999ba8874ecabd52d22d13c25fc68b
