### ISSUE TITLE
Unexpected compile time errors for abstract fields

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42984]
See tests:

```
co19/Language/Variables/syntax_t15
co19/Language/Variables/syntax_t18
```

I'm adding the "NNBD" label since as we discussed yesterday that the feature should be supported in the same release. Feel free to update if you have a different way to track it.

**Comment by johnniwinther** [comment]
The tests are invalid. See https://github.com/dart-lang/co19/issues/889
