### ISSUE TITLE
No error in analyzer if abstract field do have an initializer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42981]
According to the https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/feature-specification.md abstract fields are allowed. But they must have no initializers. The following programm produces an error in CFE but no issues in analyzer
```dart
abstract class C {
  abstract int x = 42;
//                 ^^
// [analyzer] unspecified
// [cfe] unspecified
}

main() {
  C? c;
}
```
There must be analyzer error as well
`Dart SDK version: 2.10.0-3.0.dev (dev) (Tue Aug 4 12:29:57 2020 +0200) on "windows_x64"`

**Comment by stereotype441** [comment]
Will be addressed by https://dart-review.googlesource.com/c/sdk/+/157664
