### ISSUE TITLE
Can't use the same type returned from factory constructor

### ISSUE THREAD

**Issue by hsul4n** [dart-lang/sdk#42992]
Is there any problem because I have inherited `Foo` & implements `Parent`:

```dart
/// file_a.dart
abstract class Parent {}

abstract class Foo extends Parent {
  factory Foo() => _Foo();
}

class _Foo extends Parent implements Foo {
  _Foo(){
    print('Welcome to private constructor');
  }
}

/// file_b.dart
class MyClass extends Foo implements Parent {
  factory MyClass() {
    return Foo();
  }
}

void main() {
  MyClass(); // TypeError: Instance of '_Foo': type '_Foo' is not a subtype of type 'MyClass'
}
```

* Dart SDK Version (`2.6`)

**Comment by julemand101** [comment]
A factory constructor must return an object instance which has the same type as the class which it is part of or a class which extends/implements this class.

In your case, you are trying to return `_Foo` from `MyClass` but `_Foo` does not extend or implement `MyClass`. So your instance you get from calling the `_Foo` constructor will not evaluate the following to true: `(myFooObject is MyClass)`.

Another way to look at it is you are allowed to define your own variables and methods on `MyClass` but these will not be required to be implemented on `_Foo` or ´Foo` since either have any bound to `MyClass`.

**Comment by hsul4n** [comment]
> A factory constructor must return an object instance which has the same type as the class which it is part of or a class which extends/implements this class.
> 
> In your case, you are trying to return `_Foo` from `MyClass` but `_Foo` does not extend or implement `MyClass`. So your instance you get from calling the `_Foo` constructor will not evaluate the following to true: `(myFooObject is MyClass)`.
> 
> Another way to look at it is you are allowed to define your own variables and methods on `MyClass` but these will not be required to be implemented on `_Foo` or ´Foo`since either have any bound to`MyClass`.

So as you say, the best solution is to use my own methods & variables for that case.

**Comment by julemand101** [comment]
Sorry, I don't understand what you are saying.

I am saying that just because two classes have the same methods and properties, it does not mean it is the same. In your case, `_Foo` is not a `MyClass` and therefore `_Foo` is not a valid type to return from a factory constructor inside `MyClass`.

**Comment by hsul4n** [comment]
> Sorry, I don't understand what you are saying.
> 
> I am saying that just because two classes have the same methods and properties, it does not mean it is the same. In your case, `_Foo` is not a `MyClass` and therefore `_Foo` is not a valid type to return from a factory constructor inside `MyClass`.

Sorry @julemand101 for bad explanation, anyway I got it. The factory needs to return `Foo` rather than `_Foo`.

**Comment by julemand101** [comment]
No... It needs to return an instance of `MyClass` or some other class which extends or implements `MyClass`. Neither are `Foo` or `_Foo` doing so you cannot return a `Foo` or `_Foo` instance in your `MyClass` factory constructor.

**Comment by hsul4n** [comment]
Big thanks bro.
