### ISSUE TITLE
How to import dart:html in dart without flutter

### ISSUE THREAD

**Issue by diydyq** [dart-lang/sdk#43003]
This tracker is for issues related to:

* Dart core libraries ("dart:async", "dart:io", etc.)

The source code of file: main.dart

```dart
import "dart:html";
```

When I try to run it: `dart lib/main.dart`

The compilation output error: 
------
lib/main.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';

So what's the reason? thanks!

**Comment by mraleph** [comment]
You can only use `dart:html` when you are targeting the web through `dart2js` or `dartdevc` compilers. You can't use it on the native VM. If you want to develop a Web application with Dart see https://dart.dev/web

In the future I also would recommend to use other channels for questions (e.g. StackOverflow, Discord or Gitter). This is issue tracker for problems with Dart SDK not questions.

**Comment by diydyq** [comment]
got it, sorry for the troubles, thanks!
