### ISSUE TITLE
Flow analysis incorrectly joins unassigned info at the bottom of closures.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43006]
(Thanks to @leafpetersen for discovering this)
Consider the following code:
```dart
main() {
  late int x;
  late int y;
//   var f = () => x;
  int z0 = x;
  int z1 = y;
  x = 3;
  y = 3;
}
```
As expected, this produces errors at the site of the declarations of `z0` and `z1`, because `x` and `y` (respectively) are _definitely unassigned_ at those sites.

Surpsisingly, uncommenting the line `//   var f = () => x;` makes these errors go away.  This shouldn't happen.

The reason this is happening is that upon reaching the end of a closure, flow analysis joins the "unassigned" state from the body of the closure with the "unassigned" state from the enclosing function, so as a result, any variables considered "possibly assigned" at the bottom of the closure body are considered "possibly assigned" after creation of the closure.  But since closures may be executed at any time, both `x` and `y` are considered "possibly assigned" at the top of the closure (because the closure might get invoked after the assignments to `x` and `y`); therefore they are possibly assigned at the bottom of the closure.

I think that joining unassigned info at the bottom of closures is unnecessary (I suspect we accidentally over-generalized logic that did this sort of thing in loops).

(Edit: some joining is necessary, though; see https://github.com/dart-lang/language/issues/1138)

**Comment by eernstg** [comment]
Sounds right: When analyzing the body of `f`, `x` needs to be considered possibly assigned because `f` could in principle be invoked after the assignment to `x` in the enclosing function. But I don't see the need to add the 'possibly assigned' bit to any variables at the end of the declaration of `f`: Even though `f` may in principle be invoked at any point starting from that location, that won't cause the whole body of `main` to run with the current activation record (and it doesn't assign anything to the `x` and `y` that are in scope here if `f` calls `main` and hence runs it with some other activation record).

**Comment by leafpetersen** [comment]
> I think that joining unassigned info at the bottom of closures is unnecessary (I suspect we accidentally over-generalized logic that did this sort of thing in loops).

Some kind of joining is necessary, I think:

```
main() {
  late int x;
  late int y;
  late int z;
  var f = () { 
    x; // This is neither definitely assigned, nor definitely unassigned
    y; // This is neither definitely assigned, nor definitely unassigned
    z; // This is neither definitely assigned, nor definitely unassigned
    x = 3; // x is definitely assigned
    if (x == 3) y = 3;
    // y is neither definitely assigned, nor definitely unassigned
  }
  x; // This is neither definitely assigned, nor definitely unassigned
  y; // This is neither definitely assigned, nor definitely unassigned
  z; // This is definitely unassigned 
  x = 3;
  y = 3;
  z = 3;
}
```

Not sure if this is included in your thinking or not?

**Comment by eernstg** [comment]
The last parameter of a `VariableModel` is named `writeCaptured` in the definition, with the following description:

> `writeCaptured` is a boolean value indicating whether a closure might exist at
> the given point in the source code, which could potentially write to the variable.

This means that the variable model for `x` and for `y` in [the example](https://github.com/dart-lang/sdk/issues/43006#issuecomment-672418756) should have a true `writeCaptured` property after the declaration of `f`, and no such variable can be considered definitely unassigned.

Wouldn't that be the information that needs to be added by the join? Looks like `conservativeJoin(M, emptySet, captured)` could do this, where `captured` is the set of variables that are potentially written by the function body.

**Comment by stereotype441** [comment]
@eernstg Agreed, `conservativeJoin(M, emptySet, captured)` solves the problem (where `M` is the flow model before the function expression).  @leafpetersen Yes, your example is included in my thinking, it just got left out of the spec somehow.  See https://github.com/dart-lang/language/issues/1138#issuecomment-671397427, in particular the equation `after(N) = conservativeJoin(before(N), {}, capturedHere)` (which matches Erik's suggestion).

I'll update the issue description to clarify that some joining is necessary, and include a pointer to https://github.com/dart-lang/language/issues/1138.

**Comment by leafpetersen** [comment]
@stereotype441 What's the status on this?

**Comment by stereotype441** [comment]
> @stereotype441 What's the status on this?

This is still open.  I have a prototype fix here: https://dart-review.googlesource.com/c/sdk/+/162661, but I haven't had a chance to investigate the trybot failures yet.  Hopefully I can get back to it this week or next.
