### ISSUE TITLE
Generic method runtime error

### ISSUE THREAD

**Issue by canitez** [dart-lang/sdk#43002]
Hi,

I was using a method to convert to json.It was running smoothly until very recently. probably this error occurred after dart update. When I call the generic method, the types I sent disappear.

![image](https://user-images.githubusercontent.com/8152086/89763277-de088180-dafa-11ea-80cd-ebb146a5b292.png)

![image](https://user-images.githubusercontent.com/8152086/89763321-f1b3e800-dafa-11ea-8bd5-415409c1c22c.png)

What could be the reason for this? The only change I made was to get the latest updates.

**Comment by canitez** [comment]
Thank you for your help.However, this situation does not appear on the console or throw an error. How can I get more detailed information.

**Comment by eernstg** [comment]
There could be a lot of different issues, but one surprising thing is that you are calling `Parser.fromJson(json)`, that is, you are not passing any actual type arguments to `fromJson`. The inferred type arguments will then be `<dynamic, dynamic>`, so you're allowed to treat the returned value as if it were a generic function, so you can pass it the actual type arguments `<T, K>` and value argument `(json.decode(response.body))`.

But it seems much, much more likely that you actually meant to say `Parser.fromJson<T, K>(json)`.

The returned result is then a `T`, but then I don't see any reason why you would expect an instance of `T` (which is a type variable that has no bounds, so you basically only know that it is an `Object`) to be a function, and a function that accepts `json.decode(response.body)`.

So if you actually intend to do `Parser.fromJson<T, K>(json)` then the program would need to be adjusted in several ways.

If you actually intend to do `Parser.fromJson(json)<T, K>(json.decode(response.body))` then you could motivate why you're doing that, and what you expect the IDE, analyzer, compiler, or similar tools to do.
