### ISSUE TITLE
dartdev --disable-dartdev-analytics on travis

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#43017]
When running on travis [environment variables](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) such as:
 * `CI=true`
 * `TRAVIS=true`
 * `CONTINUOUS_INTEGRATION=true`

are set.

It's probably best to disable analytics collection when any of these environment variables are set.
Analytics messages is likely to break test cases, which nobody wants :D

Note: I'm suggesting that we disable analytics collection in `dartdev` whenever any of the env vars above are given.
Not that we customize the "dart travis" environment to have analytics disabled (although that's probably also a smart move, but orthogonal to this issue).

/cc @jwren

**Comment by jonasfj** [comment]
Note. other CI systems also have the environment variable `CI=true` or `CI=True` (or similar).
 * [circle-ci](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables)
 * [appveyor](https://www.appveyor.com/docs/environment-variables/).
 * [codemagic](https://docs.codemagic.io/building/environment-variables/)
 * [bitrise](https://devcenter.bitrise.io/builds/available-environment-variables/)

Just to mention a few.

**Comment by mit-mit** [comment]
@jonahwilliams how does the Flutter tool handle this?

**Comment by devoncarew** [comment]
dartdev uses this logic to identify bots (and automatically suppress analytics):

https://github.com/dart-lang/sdk/blob/master/pkg/telemetry/lib/telemetry.dart#L167

We manually keep that in sync with similar code from the flutter tool.

**Comment by devoncarew** [comment]
@jwren - I don't think there's anything to do here.

**Comment by jonasfj** [comment]
can we change:
```dart
  if (analytics.firstRun) {
    io.stderr.writeln(analyticsNoticeOnFirstRunMessage);
  }
```
into:
```dart
  if (analytics.firstRun && analytics.enabled) {
    io.stderr.writeln(analyticsNoticeOnFirstRunMessage);
  }
```

**Comment by jonahwilliams** [comment]
Currently bot detection is handled by https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/bot_detector.dart . There has been some discussion on changing bot behavior to add a flag to all recorded analytics, to allow after-the-fact filtering of bots.

**Comment by jwren** [comment]
As @devoncarew pointed out there is nothing to do here.  Also if `analytics.firstRun` is true, then `analytics.enabled` is false-- we never collect on the first run.
