### ISSUE TITLE
cherry pick dart-lang/sdk@ac4de98 to stable branch

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#43013]
**commit(s) to merge:**  https://github.com/dart-lang/sdk/commit/ac4de98a294eee5a745e67a3a2d5f15d6e499f2d

**merge instructions:** The change does not merge cleanly, please see
https://dart-review.googlesource.com/c/sdk/+/158102 for a patch CL

**What is the issue:** Applications run into the following unhandled exception
Unsupported operation: serialization of generic DartType: UnknownType(?) (UnknownType)

**What is the fix:** CFE Eliminates UnknownType in async type downcasts

**Why cherrypick:** A number of flutter users (almost 21 upvotes for the issue) have run into this issue, please see
https://github.com/flutter/flutter/issues/63038

**Risk:** The fix landed in the Dart tree on Jul 14th and has been rolled into bleeding edge Flutter. It has been in the
bleeding edge branch for over 3 weeks now and the risk is pretty low.
Number of lines of code change 2 and there is a CFE unit test case for the change.

**Link to original issue(s):**
Flutter : https://github.com/flutter/flutter/issues/63038
Dart : https://github.com/dart-lang/sdk/issues/42615

**Comment by johnniwinther** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved in SCRUM
@pcsosinski @athomas

**Comment by pcsosinski** [comment]
fixed in 2.9.1
