### ISSUE TITLE
[Dart FFI] How to return a string list from a native library via nativeport?

### ISSUE THREAD

**Issue by ganeshrvel** [dart-lang/sdk#43011]
I am trying to send a struct from my native library back to Dart (using nativeport). The struct has a field which is a **string list**. I understand that C doesn't have string arrays like we have in Dart. 

What is the common practice in Dart FFI to receive a list of strings from the native library? I can only find `Pointer<Utf8>` which is closest to handling the strings in the response message. Can `Pointer<Utf8>` handle string list as well?

Are there any examples that I could refer to (both **C and Dart side** of it)? I couldn't find any such example in the [samples directory](https://github.com/dart-lang/sdk/tree/master/samples/ffi) as well.

Ref question: https://github.com/dart-lang/sdk/issues/37022#issuecomment-671293952

ps: I am still trying to understand the concepts of FFI and C.

cc @dcharkes

**Comment by dcharkes** [comment]
Hi @ganeshrvel,

C does not have lists, did you mean an array or pointer?

Given a struct will a null-terminated string in C such as the following:

```c
struct MyStruct {
   char* some_string;
   int some_int;
};
```

The Dart binding for that would be as follows:

```dart
class MyStruct extends Struct {
  Pointer<Utf8> some_string;

  @Int32()
  int some_int;
}
```

Note you can also use https://pub.dev/packages/ffigen to not write your bindings by hand but generate them.

**Comment by ganeshrvel** [comment]
@dcharkes I meant array, array of strings to be precise.
 
Something like:
```dart
items_array = ["item 1",  "item 2", "item 3"]
```

```c
struct MyStruct {
   char** some_string_array;
   int some_int;
};
```

I have to pass this array down from C to dart. How's it done?

> Note you can also use https://pub.dev/packages/ffigen to not write your bindings by hand but generate them.
I am already using that 👍 . It's a life saving package!

**Comment by dcharkes** [comment]
> ```c
> struct MyStruct {
>   char** some_string_array;
>   int some_int;
> };
> ```

For `...**` one uses `Pointer<Pointer<...>>`:

```dart
class MyStruct extends Struct {
  Pointer<Pointer<Utf8>> some_string_array;

  @Int32()
  int some_int;
}
```

(`ffigen` generates a `Pointer<Pointer<Int8>>` so you have to Utf8 encode/decode manually. See https://github.com/dart-lang/ffi/blob/master/lib/src/utf8.dart on how to do that.)

**Comment by ganeshrvel** [comment]
Hey @dcharkes, thanks.

Unfortunately, ffigen isn't able to generate the binding for C code in the Go (like structs and stuffs).

But I made my code working, I tried something like this:

```dart
class Work extends Struct {
  Pointer<Utf8> name;

  @Int64()
  int age;

  Pointer<Pointer<Utf8>> string_list;

  factory Work.allocate(
          Pointer<Utf8> name, int age, Pointer<Pointer<Utf8>> string_list) =>
      allocate<Work>().ref
        ..name = name
        ..age = age
        ..string_list = string_list;
}

// ....

    final interactiveCppRequests = ReceivePort();

    final interactiveCppSub = interactiveCppRequests.listen((data) {
      final work = Pointer<Work>.fromAddress(data as int);
      print(work.ref.name.ref.toString());
      print(work.ref.age);

      final _string_list_ptr = work.ref.string_list;

      print(_string_list_ptr.elementAt(0).value.ref.toString());
      print(_string_list_ptr.elementAt(1).value.ref.toString());
    });

// ....
```


In the Go side:
```go
//	typedef struct WorkStruct{
//		char *name;
//		int64_t age;
//		char ** string_list;
//	}WorkStruct;
//
//	int64_t GetWork(void **ppWork, char* name, int64_t age, char* string_list) {
//		WorkStruct *pWork= (WorkStruct *)malloc(sizeof(WorkStruct));
//		pWork->name=name;
//		pWork->age=age;
//		pWork->string_list= malloc( 1* sizeof(char*));
//		pWork->string_list[0] = malloc( 5 * sizeof(char));
//		pWork->string_list[0] = "item 3";
//		pWork->string_list[1] = malloc( 5 * sizeof(char));
//		pWork->string_list[1] = "item 4";
//
//		*ppWork = pWork;
//
//		int64_t ptr = (int64_t)pWork;
//
//		return ptr;
//	}
```

**But I do have a question.**
- How do I get the length of the `work.ref.string_list`? Right now I am manually printing out the indices. Is there any generic way to get the length of the `string_list`?

**Comment by dcharkes** [comment]
> Unfortunately, ffigen isn't able to generate the binding for C code in the Go (like structs and stuffs).

Is this because there is no separate C header file available? Can the Go compiler output such a header file that could be consumed by ffigen (which uses clang to consume header files). If it is a C header file but ffigen doesn't accept it, please file an issue on the ffigen repo.

> How do I get the length of the work.ref.string_list so that I can iterate over it? Right now I am manually printing out the values using the indices. Is there any generic way to get the length of string_list?

You should either have a length in C, or the list is null-terminated. Null-termination you can check by checking `pointer.address == 0`.

> Will freeing the pointer 'work' de-allocate the memory of the string_list too? Or do I need to manually free string_list too?

No, the C `free` does not follow pointers to free what is referenced by them. So you need to manually free. I suggest writing a function in C (or Go) that takes a pointer to the struct and `free`s everything.

**Comment by ganeshrvel** [comment]
Awesome! Thanks a lot!

**Comment by dcharkes** [comment]
I'll go ahead and close the issue. Feel free to reopen or open a new one if you have further questions.

**Comment by ganeshrvel** [comment]
For anyone else who might be looking for figure how to free the memory after use, this is what I did. Taking cues from https://github.com/dart-lang/sdk/issues/43011#issuecomment-671852985

Dart side:
```dart
    final interactiveCppRequests = ReceivePort();

    final interactiveCppSub = interactiveCppRequests.listen((address) {
      final _address = address as int;

      final work = Pointer<Work>.fromAddress(_address);

      print(work.ref.name.ref.toString()); // name
      print(work.ref.age); // age

      final _string_list_ptr = work.ref.string_list;

      var count = 0;
      while (true) {
        final _value = _string_list_ptr.elementAt(count).value;

        if (_value.address == 0) {
          break;
        }

        print(_value.ref.toString()); // Work.string_list value

        count += 1;
      }

      _squashArchiverLib.FreeWorkStructMemory(Pointer<Int64>.fromAddress(
        _address,
      ));
    });
```

```go
//	typedef struct WorkStruct{
//		char *name;
//		int64_t age;
//		char ** string_list;
//	}WorkStruct;
//
//	void clearWorkStructMemory(WorkStruct pWork) {
//		free(&pWork.name);
//		free(&pWork.age);
//		free(&pWork.string_list);
//		free(&pWork);
//	}

func FreeWorkStructMemory(pointer *int64) {
	ptr := (*C.struct_WorkStruct)(unsafe.Pointer(pointer))

	C.clearWorkStructMemory(*ptr);
}
```

**Comment by Xwnine** [comment]
Cpp side:

```
struct MyStruct {
  char* address;
  int32_t port;
};

bool Connect(MyStruct address[], uint32_t address_sizes) = 0;
```

## Dart side:
```
class MyStruct extends Struct {
  Pointer<Utf8> address;

  @Int32()
  int port;
}
````

How to pass Struct list from Dart to C/C++ Using FFI?

**Comment by dcharkes** [comment]
@Xwnine, please open new issues for new questions.

You'd pass `Pointer<MyStruct>` as the argument.
