### ISSUE TITLE
Add real errors for web static error tests for JS interop

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#43022]
Currently, any web static error tests added don't run and instead have TODOs to add errors where necessary. Once the infra for web static error tests lands, they need to be migrated to the correct error reported by the web compilers.

Only affected tests should all reside within `tests/lib/js`.

**Comment by munificent** [comment]
Most of these are now fixed in https://dart-review.googlesource.com/c/sdk/+/158100.

**Comment by srujzs** [comment]
I'll assign this to you since you're the one who actually did the work :)

**Comment by munificent** [comment]
Assigning it back to you since there is still one TODO left and I probably won't be the one to fix it. :)
