### ISSUE TITLE
Wrong lists values

### ISSUE THREAD

**Issue by MPi3D** [dart-lang/sdk#43020]
Hello,
When I'm running the following code, I don't have the expected result.
It looks like it doesn't copy the value of `a` but a pointer of `a`.
I think it's a bug.

* Code

``` dart
void main() {
  var a = [[false, false], [false, false]];
  var b = [a, a];
  print(b);
  b[0][0] = [true, true];
  print(b);
}
```

* Expected Result

```
[[[false, false], [false, false]], [[false, false], [false, false]]]
[[[true, true], [false, false]], [[false, false], [false, false]]]
```

* Current Result

```
[[[false, false], [false, false]], [[false, false], [false, false]]]
[[[true, true], [false, false]], [[true, true], [false, false]]]
```

* Dart SDK Version

```
Dart SDK version: 2.9.0-21.10.beta (beta) (Tue Jul 21 10:46:30 2020 +0200) on "linux_x64"
```

**Comment by JacobBangSSE** [comment]
That is the correct behavior. What you are doing is creating a List `b` containing two references to List `a`. If you want to create a copy of List `a` you need to call `toList()` on `a` or `[...a]` like this:
```dart
void main() {
  var a = [
    [false, false],
    [false, false]
  ];
  var b = [[...a], [...a]];
  print(b);
  b[0][0] = [true, true];
  print(b);
}
```

This will output:
```lang-none
[[[false, false], [false, false]], [[false, false], [false, false]]]
[[[true, true], [false, false]], [[false, false], [false, false]]]
```

Note, that you are just copying the list itself but not each element so each element in the two lists will still point to the same object instances. You need to manually code some deep copy function if you want a complete deep copy of each list.

**Comment by julemand101** [comment]
That is the correct behavior. What you are doing is creating a List `b` containing two references to List `a`. If you want to create a copy of List `a` you need to call `toList()` on `a` or `[...a]` like this:
```dart
void main() {
  var a = [
    [false, false],
    [false, false]
  ];
  var b = [[...a], [...a]]; // or: var b = [a.toList(), a.toList()];
  print(b);
  b[0][0] = [true, true];
  print(b);
}
```

This will output:
```lang-none
[[[false, false], [false, false]], [[false, false], [false, false]]]
[[[true, true], [false, false]], [[false, false], [false, false]]]
```

Note, that you are just copying the list itself but not each element so each element in the two lists will still point to the same object instances. You need to manually code some deep copy function if you want a complete deep copy of each list.

**Comment by MPi3D** [comment]
OK, thanks for your helping.
