### ISSUE TITLE
Failures on [cfe] Insert forward stub only in the first class that needs it

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#43027]
There are new test failures on [[cfe] Insert forward stub only in the first class that needs it](https://dart-review.googlesource.com/c/sdk/+/157322).

The tests
```
language/mixin/implicit_covariance_test RuntimeError (expected Pass)
language_2/mixin/implicit_covariance_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartdevk-checked-linux-release-chrome
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
```

**Comment by johnniwinther** [comment]
These started failing on the CFE change - dart2js started passing on the same CL.

The CL removes forward stubs for which an equivalent forwarding stub has already been inserted in the superclass so there seems to be something wrong in how ddc and dart2js handles forwards stubs or expects forwarding stubs to be inserted. (dart2js started passing but should already have been passing).

**Comment by nshahan** [comment]
@johnniwinther I looked a little into this issue and the failing tests. The code for unrolling mixins in DDC right now expects the `generic-covariant-impl` to appear on the class itself and as you mentioned it does not appear if it already appears on the superclass. 

There is a related TODO in this code:

https://github.com/dart-lang/sdk/blob/56423666114759da57d41462d92a0e0a5c343ccc/pkg/dev_compiler/lib/src/kernel/compiler.dart#L823-L826 

but I don't know what that means specifically. Does it mean anything to you? Is there a description of mixins or technique I should start using when applying mixins to a class? 

If not, I can try to fit in a way to make sure we check the members of the superclass for the flag and emit a covariant check and a call to super when needed.

**Comment by johnniwinther** [comment]
It might be referring to `Class.superclassConstraints` which returns the types in the `on` clause on a mixin declaration.
