### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by wellWINeo** [dart-lang/sdk#43021]
Hi! I am trying to make ebuild of dart for gentoo linux, i found a ebuild for old version and addatping it for newer version. But at compile phase i have this error:
`[49/3432] /usr/lib/llvm/10/bin/clang++ -MMD -MF obj/runtime/bin/gen_snapshot_dart_io.filter.o.d -DDART_IO_SECURE_SOCKET_DISABLED -DNDEBUG -DNDEBUG -DDART_USE_TCMALLOC -DDART_PRECOMPILER -DTARGET_ARCH_X64 -DTARGET_OS_LINUX -I../runtime -I../third_party -I.. -Igen -I../runtime/include -I../third_party/tcmalloc/gperftools/src -I../third_party/zlib -m64 -march=x86-64 -msse2 -fno-exceptions -fPIC -fcolor-diagnostics -Wall -Wextra -Werror -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wno-tautological-constant-compare -fdebug-prefix-map=/home/wneo/tmp/path_for_dart/dart-2.9.0/dart=.. -no-canonical-prefixes -Wheader-hygiene -Wstring-conversion -O3 -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++11 -fno-rtti -fno-exceptions -c ../runtime/bin/filter.cc -o obj/runtime/bin/gen_snapshot_dart_io.filter.o
ninja: build stopped: subcommand failed.`

for build i use this `ninja -v -j17 -l0 most`
Also i tried to do it manually (not by portage and ebuild) and have same error. Will pleasure for any advices)

**Comment by a-siva** [comment]
The actual error from the compilation is not captured in your description above, could you elaborate a bit more on the kind of error you are seeing. Also please note gentoo linux is not a supported host configuration.

**Comment by wellWINeo** [comment]
Here a full build log https://pastebin.com/LNpH6brF
Also i forgot to say, that i try to build 2.9.0 version

**Comment by a-siva** [comment]
I do not see any error in your full build log from any of the compilation lines.

I see this text in the log, do you know what it means ?
 /bin/sh: /usr/lib/llvm/10/llvm-ar: Нет такого файла или каталога

**Comment by athomas** [comment]
Нет такого файла или каталога means "No such file or directory" according to Google translate.

**Comment by wellWINeo** [comment]
@athomas right in translation
I found llvm-ar on that path: usr/lib/llvm/10/bin, what i should do?

**Comment by a-siva** [comment]
See this command in your build log
rm -f obj/runtime/bin/libcrashpad.a && /usr/lib/llvm/10/llvm-ar rcs obj/runtime/bin/libcrashpad.a

figure out where it is getting generated from and replace /usr/lib/llvm/10/llvm-ar with /usr/lib/llvm/10/bin/llvm-ar
