### ISSUE TITLE
Treat `required` as `@required` for hinting

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#43026]
When a package is migrated to null safety, `@required` might be replaced with `required`. Currently, non-migrated packages do not then get an analyzer finding if they omit a `required` field.

The analyzer should in this case (legacy depends on migrated) treat `required` the same as `@required`.

**Comment by bwilkerson** [comment]
@devoncarew @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/158343

**Comment by scheglov** [comment]
This is currently blocked on necessary Flutter fixes.
