### ISSUE TITLE
Dart language comment doesn't disable Future import from dart:core

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#43023]
```dart
// @dart=2.0

Future f;                                                                        
void main() {                                                                    
  print('here');                                                                 
} 
```

In a project with a pubspec set to `>2.1.0`, this analyzes cleanly, and also runs and prints 'here'. But of course, it would not work on a 2.0 VM because it doesn't import `dart:async`.

If I change my pubspec to 2.0, the analyzer reports a hint about the missing import. The VM however run the code with no issue.

Not sure if the CFE should handle this @leafpetersen @johnniwinther, for now I labeled it an analyzer issue.

**Comment by MichaelRFairhurst** [comment]
Related: setting the version constraint to 2.1 or higher does not make this hint go away:

"The class 'Future' wasn't exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions."

in analyzer.

**Comment by leafpetersen** [comment]
If I recall correctly, this changed predates the existence of the versioning mechanism whereby we guarded non-breaking changes by a min sdk constraint.  In fact, I think inadvertent breakage from this may have been a motivation for the language versioning feature.  See specifically this comment: https://github.com/dart-lang/language/issues/286#issuecomment-503614115 .

**Comment by srawlins** [comment]
Closing as stale; language versioning would not apply to SDK library changes.
