### ISSUE TITLE
instruction_sizes_test is brittle to compiler changes

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#43030]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8872222452579434720/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by mraleph** [comment]
I guess I could add some "sensitivity threshold" to the test (e.g. ignore sizes change < 16 bytes).

**Comment by mraleph** [comment]
Uploaded CL for review https://dart-review.googlesource.com/c/sdk/+/158386
