### ISSUE TITLE
FFI callbacks are broken with --no-use-bare-instructions

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#43035]
From a try job that changes the default value of use-bare-instructions to false:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8872134829871217264/+/steps/test_results/0/logs/new_test_failures__logs_/0

Snapshot splitting includes generating code this way, initially for all calls and later for calls between loading units.

@dcharkes

**Comment by dcharkes** [comment]
For reference, the CL: https://dart-review.googlesource.com/c/sdk/+/154343

**Comment by dcharkes** [comment]
It triggers this in AOT (only with --use-bare-instructions=false), but all callbacks should have been precompiled. We should never hit `PatchStaticCall` in AOT.

I will investigate.

> Snapshot splitting includes generating code this way, initially for all calls and later for calls between loading units.

Just to clarify, "this way" == `--use-bare-instructions=false`? Or did you mean generating calls to `PatchStaticCall`?

**Comment by dcharkes** [comment]
--use-bare-instructions (aot)
```
        ;; v21 <- StaticCall:10( simpleAddition<0> v15, v19) T{int?}
0x7fe13782d2af    e8fbffffff             call 0x00007fe13782d2af
0x7fe13782d2b4    59                     pop rcx
0x7fe13782d2b5    59                     pop rcx
```

--no-use-bare-instructions (aot)
```
        ;; v21 <- StaticCall:10( simpleAddition<0> v15, v19) T{int?}
0x7f9a7eaa6514    4533d2                 xorl r10,r10
0x7f9a7eaa6517    4d8b670f               movq r12,[pp+0xf]   Code([Stub] CallStaticFunction)
0x7f9a7eaa651b    41ff542407             call [r12+0x7]
0x7f9a7eaa6520    59                     pop rcx
0x7f9a7eaa6521    59                     pop rcx
```

**Comment by dcharkes** [comment]
N.b. https://dart-review.googlesource.com/c/sdk/+/158165 does not fix it.

cc @sstrickl
