### ISSUE TITLE
Ship the `experimental_features.yaml` file with the SDK

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#43040]
See the meta issue https://github.com/dart-lang/sdk/issues/43031

We currently do not ship this file with the SDK but we will need to for some tools to consume so that they can properly detect what the experiment release version should be for a given experiment (and thus, whether it is enabled or not).

Note that this also means the format of that file would become a public facing API, and we would have to be more careful not to change it.

cc @johnniwinther @scheglov @jonasfj

**Comment by lrhn** [comment]
Should we take a little time to consider the format.
For example, the "current version" field seems like a *very general* field, something that almost all tools need to know, so why are we putting it into a file called "experimental_features.yaml". 
Should the file itself be more general? maybe be called "language_config.yaml", and be prepared for other things than just experiments?

**Comment by johnniwinther** [comment]
The current format is very ad-hoc, and not all ready for the scrutiny of a public release nor to be restricted by (backwards) compatibility constraints.

It has served us well that we have been able to modify this file to fit the changing needs with the analyzer and cfe. We've for instance recently added the 'category' as a way to distinguish language and tool experiments. Since the scope of this non-language use is not known yet, the addition was deliberately and purposefully very ad-hoc. 

I'm also worried that publishing this makes it harder to add experiments, which is intended purpose of the experimental flags; that we can easily try out, test, release or abandon experiments.


Maybe what we publish should instead be only what we need for this problem, namely the experiment release version for the experiments that have been released.

**Comment by jakemac53** [comment]
Another potential option here would be to expose this information through some package which is tightly versioned with the SDK to allow for format changes and not expose this file itself. The package would be code generated based on the file but with a tighter api than the other code generated files.

It would however have to be published on every minor sdk release, and is yet another package to manage etc.

**Comment by jakemac53** [comment]
@jcollins-g for dartdoc
@jonasfj @sigurdm for pub

What logic/apis are you all using to detect whether null safety is enabled or not? Are you going through the analyzer or some other api or using your own custom logic?

**Comment by devoncarew** [comment]
@srawlins is handling dartdoc while @jcollins-g is out, however, from my understanding dartdoc just uses the analyzer APIs.

**Comment by vsmenon** [comment]
@jakemac53 - listing you as the here for now.

**Comment by jakemac53** [comment]
Assigned jonasfj@ and sigurdm@ since this is currently blocked on feedback from the pub/pana side of things.

We would like to actually avoid shipping this file at all and instead rely on those packages using the analyzer to determine if null safety is enabled, if possible.

**Comment by jonasfj** [comment]
> What logic/apis are you all using to detect whether null safety is enabled or not?
> Are you going through the analyzer or some other api or using your own custom logic?

We have null-safety analysis in:
 * `pub`, for warnings in `pub get`,  `pub publish` and annotation in `pub outdated --mode=null-safety`.
 * `pana`, for tagging on `pub.dev` (and eventually search filtering).

In both cases, we decide that package is _null-safety compliant_, if:
 * (i) the package has a _default language version_ `>= 2.11`, and,
 * (ii) no library in the contains _language version markers_ (`//@dart=2.10`) opting-out of null-safety, and,
 * (iii) all _dependencies_ of the package are _null-safety compliant_ (following this recursive definition). 

--------------

We've currently hardcoded `2.11` into `pub` and `pana` (including our test cases), and we manually bumped it from `2.10` after `2.9.0` shipped. Getting this number from `experimental_features.yaml` might be nice, on the other hand once we ship `non-nullable` this number won't change. So hardcoding might be fine.

It is debatable to what extend `pub` and `pana` will need to understand experiments. I suspect that it's attractive to do this correctly in `pub outdated --mode=null-safety` as this tool is used by the migration tool, and is currently unaware of `allowed_experiments.json`. So packages from the _non-nullable allow-list_ published on `pub.dev` will not be considered null-safe by `pub outdated`, and dependency upon them will stop the migration tool during the preview phase.

**Comment by jakemac53** [comment]
Had an offline discussion with @jonasfj about this - we decided that _if_ pub/pana want to understand this (unclear if they need to or not), then they will just hardcode the knowledge like the existing language version for nnbd is hard coded.

Given that I am going to close this issue as we will not need to ship this file with the SDK.
