### ISSUE TITLE
dartdev prints analyticsNoticeOnFirstRunMessage when CI=true

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#43046]
@jwren, This is what I suggested we fix in https://github.com/dart-lang/sdk/issues/43017#issuecomment-672033050:

```
[~]$rm -rf .dart/
[~]$CI=true /source/flutter/bin/dart --help
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to anonymously report feature usage    ║
  ║ statistics, and crash reporting to send basic crash reports. This data is  ║
  ║ used to help improve the Dart platform and tools over time.                ║
  ║                                                                            ║
  ║ To disable reporting of anonymous tool usage statistics in general, run    ║
  ║ the command: `dart --disable-analytics`.                                   ║
  ╚════════════════════════════════════════════════════════════════════════════╝
```

We do not record any analytics when the env var `CI=true`.
But it would be nice, if we did not print the analyticsNoticeOnFirstRunMessage when `CI=true`.

Notably, this is likely to break tests in some CI environments :)

**Comment by jwren** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/158920.

`rm ~/.dart/dartdev.json; dart ~/src/github/dart-sdk/sdk/pkg/dartdev/bin/dartdev.dart --help`

now yields

```
A command-line utility for Dart development.
...
```

**Comment by vsmenon** [comment]
@jwren - can we close this?

**Comment by jwren** [comment]
We can now, PR is in the CQ.
