### ISSUE TITLE
when nnbd TypeMirror need support isNullable api

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#43063]
like title

**Comment by mraleph** [comment]
Please stop spamming issue tracker with new one sentence issues (which are essentially all connected) and treating issue tracker as a chat app.

If you wish to ask questions: use StackOverflow, Discord or mailing list dart-misc@dartlang.org. 

If you wish to provide feedback on language design and request language enhancements: use dart-land/language repository. Note that in general issues should be informative and not one liners - if you wish to provide language feedback or request language features you will need to explain the problem and motivation in details.

Thanks for understanding

**Comment by Silentdoer** [comment]
VariableMirror should support a api to get field's type when it's default null;
like this code:
class Foo {
int? kk;
}
kk is default null, so instanceMirror.getField(#kk).type is Null, we can not get kk's declare type int?

**Comment by lrhn** [comment]
Sounds like a duplicate of #40510.
