### ISSUE TITLE
analyzer does not detect when constant is being modified

### ISSUE THREAD

**Issue by smac89** [dart-lang/sdk#43067]
* Dart SDK Version (`dart --version`)
```
Dart SDK version: 2.9.0 (stable) (Fri Jul 31 10:59:48 2020 +0200) on "linux_x64"
```

The code:

```
void modl(List<int> l) {
  l.add(90);
  print(l);
}

class Foo {
  final List<int> bar;
  const Foo(this.bar);

  @override
  String toString() => 'Foo{bar: $bar}';
}

void main() {
  var foo = const Foo([1,2,3,4]);
  modl(foo.bar); // unhandled exception here
  print (foo);
}
```

With regards to this question on [stackoverflow](https://stackoverflow.com/questions/63442051/detecting-when-a-const-object-is-passed-to-a-function-that-mutates-it-in-dart), I think this is a bug because the compiler should have given a compile-time error if the constant is being modified by the function.

**Comment by lrhn** [comment]
Dart does not have a "constant propagation analysis" which generally allows it to predict when a value is a const value.
To do that, it would have to track which variables definitely refer to constant objects, and which constant object it might be.
That's probably doable, but unlikely to provide much value in 99% of the cases.


So the compiler has no way to know that `foo.bar` is a constant list.

It can probably be derived in this exceedingly simple example, by doing some flow analysis, but the type of `var foo` is just `Foo`, and that type can contain non-constant objects as well. And even if it doesn't, it's possible to have getters on constant objects which return mutable objects (using `Expando` for storage, returning a shared static object, or just creating a new object each time). It really would mean that the compiler would need to know which constant `foo` is, and recognize that `foo` is an instance variable, and see that the value stored in there is a constant built-in list object. And then recognize that calling `add` on a constant built-in list object is wrong, even in a non-`const` setting.
