### ISSUE TITLE
Compile time error in a code snippet provided in the documentation. 

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/sdk#43069]
Referring the code in the documentation [here](https://dart.dev/null-safety/understanding-null-safety#nullability-and-generics)

```
// Using null safety:
class Box<T> {
  final T? object;
  Box.empty();
  Box.full(this.object);
}
```

>Note the ? on the declaration of object. Now the field has an explicitly nullable type, so it is fine to leave it uninitialized.

But when I run this code in null safety DarPad, I get compile time error. 

> All final variables must be initialized, but 'object' isn't.

**Comment by eernstg** [comment]
That is indeed not allowed, a final instance variable must be initialized in all generative constructors (here: `Box.empty` and `Box.full`), and it is a compile-time error that `Box.empty` doesn't do that. I can't move this issue to the site-www, so I created a new issue there with a link to this issue, and then I'll close this one.
