### ISSUE TITLE
[front-end/vm] How to run benchmark test for front-end module ?

### ISSUE THREAD

**Issue by lfkdsk** [dart-lang/sdk#43068]
I wanna to run benchmark test for my pr that just merged in.

https://github.com/dart-lang/sdk/pull/42943

How to get the benchmark result like this `list factory specializer` in this pr ?

just like：

```
Migrated NNBD benchmarks in AOT mode on x64:
Sudoku +11%
DartMicroBenchMM.{Min,Max}Lib +11-13%
DartMicroBenchMM.{Min,Max}Code +19-27%
ForInGeneratedLoop +19%
ForEachLoop +85%
ForInLoop +64%
ForLoop +680%

```

https://dart-review.googlesource.com/c/sdk/+/153388

@alexmarkov

**Comment by mraleph** [comment]
Unfortunately our continuous performance tracking infrastructure and most of the benchmarks are not public at the moment. Some of benchmarks have been open sourced (https://github.com/dart-lang/sdk/tree/master/benchmarks), and we are looking at open sourcing most others - but it is a lengthy process (/cc @mkustermann who is driving that). 

At some point we plan to integrate our performance tracking with Gerrit (code review system) in a way similar to how CQ works - but it is somewhere in the distant future.
