### ISSUE TITLE
Inconsistent behavior in `dart:mirrors`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#43070]
Example:
```dart
import"dart:mirrors";

typedef F1 = int Function(int);
typedef F2 = int Function(int);

main() {
 var m1 = reflectType(F1);
 var m2 = reflectClass(F2);
 print(m1.runtimeType); // _ClassMirror
 print(m1.simpleName);  // Symbol("_Closure");
 print(m2.runtimeType); // _ClassMirror
 print(m2.simpleName);  // Symbol("_Closure");
}
```
Now, if I *only* change the declaration of `m1` to use `reclectType` instead, I get:
```dart
import"dart:mirrors";

typedef F1 = int Function(int);
typedef F2 = int Function(int);

main() {
 var m1 = reflectType(F1);
 var m2 = reflectClass(F2);
 print(m1.runtimeType); // _FunctionTypeMirror
 print(m1.simpleName);  // Symbol("(dart.core.int) -> dart.core.int")
 print(m2.runtimeType); // _FunctionTypeMirror
 print(m2.simpleName);  // Symbol("(dart.core.int) -> dart.core.int")
}
```
That is, it changes the behavior of `m2` as well, probably because it's really the same type, and somehow the operation caches the result.

This probably means that at least one of the results for `m2` is wrong.
(Also, the "function type as text" is not a valid `Symbol`, so the `simpleName` is highly suspect as well).

**Comment by a-siva** [comment]
At this point we have no plans for working on the `dart:mirrors` library.
Please see https://github.com/dart-lang/sdk/issues/44489 which is investigating a path towards discontinuing support for `dart:mirrors`
