### ISSUE TITLE
The mirrors library does not understand extensions

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#43086]
The `dart:mirrors` library has no notion of extensions.

It doesn't expose an `extension` declaration as a member of the library it's declared in. Instead it exposes the synthetic top-level declarations that the extension is desugared into. Exposing those is definitely wrong.

Example:
```dart
library name;
import"dart:mirrors";

extension Foo<T> on T {
  static int foo() => 42;
  T get log {
    print(this); 
    return this;
  }
}

main() {
 var library = reflectClass(Hook).owner as LibraryMirror;
 print("Library name: ${library.simpleName}"); // Sanity check, it's the current library.
 print("Library declares Foo: ${library.declarations[#Foo]}"); // No
 print("Library leaks Foo.log: ${library.declarations[#Foo.log]}"); // Yes, it does.
 print("Library leaks Foo.foo: ${library.declarations[#Foo.foo]}"); // Yes, it does.
}
class Hook {}
```

The mirrors library should either be deprecated or be made compatible with new language features.

**Comment by a-siva** [comment]
At this point we have no plans for enhancing the `dart:mirrors` library to account for new language features.
Please see https://github.com/dart-lang/sdk/issues/44489 which is investigating a path towards discontinuing support for `dart:mirrors`
