### ISSUE TITLE
Const class cannot remove fields in hot reload

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#43083]
Currently if you remove a field from a const class and try to hot reload you get:

```
Hot reload received invalid response: {type: ReloadReport, success: false, notices: [{type: ReasonForCancelling, class: {type: @Class, fixedId: true, id:
classes/3988, name: ItemGeometry}, message: Const class cannot remove fields: Library:'package:plexiglass/rendering/items/common.dart' Class: ItemGeometry}]}
```

The ugliness of the message is https://github.com/flutter/flutter/issues/64027, but more importantly, we shouldn't fail for removing a const class field. If we must, we should just rename the field something that cannot be expressed in Dart, and pretend...

**Comment by alexmarkov** [comment]
@rmacnak-google @mkustermann

**Comment by rmacnak-google** [comment]
https://github.com/dart-lang/sdk/issues/40442
