### ISSUE TITLE
Support the `--{no-}sound-null-safety` flags in the kernel worker 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#43091]
The kernel worker (used by build_runner and google3) does not currently plumb through or support the --{no-}sound-null-safety flag, this will be a requirement for running in sound null safety mode with our modular builds.

There are some open questions as to exactly how it should be implemented:

- Should we throw away all cached modules if the flag changes from one invocation to the next?
  - If we do this then probably blaze and build_runner would run twice as many workers, keeping a set for each mode and delegating requests to the respective workers.
- Or should we keep two incremental compilers around, and two caches of components, so that we can more efficiently switch back and forth?

I believe DDC already supports this flag, but I don't know how it is handling invalidation issue listed above, cc @nshahan @Markzipan 

cc @jensjoha @sigmundch @natebosch @davidmorgan

**Comment by jakemac53** [comment]
assigned to the `area-front-end` for right now for a lack of a more obvious area to assign it to

**Comment by nshahan** [comment]
> I believe DDC already supports this flag, but I don't know how it is handling invalidation issue listed above

I haven't tested it properly in the worker configuration but I added checks to invalidate if the mode changes and to error if you try to compile with `--sound-null-safety` and use weak summary .dills for the sdk or dependencies. 
https://dart-review.googlesource.com/c/sdk/+/146962/17/pkg/front_end/lib/src/api_unstable/modular_incremental_compilation.dart

I might have missed something though if we find the invalidation isn't enough.

**Comment by jakemac53** [comment]
Nice @nshahan that is a fine option I think - and that is shared code so we just need to plumb the flag through then. I can work on that.

**Comment by jakemac53** [comment]
This was resolved in https://github.com/dart-lang/sdk/commit/1522a867ca7e4e6a5804c4333b09b325a2450c4b
