### ISSUE TITLE
API doc issue: Web-only warning doesn't mention desktop

### ISSUE THREAD

**Issue by Merrit** [dart-lang/sdk#43095]
The warning here: https://api.dart.dev/stable/2.9.1/dart-io/dart-io-library.html

> Important: Browser-based applications can't use this library. Only servers, command-line scripts, and Flutter mobile apps can import and use dart:io.

The warning doesn't mention desktop apps, though they do seem to be supported:

> The system encoding is the current code page on Windows and UTF-8 on Linux and Mac.

The warning should be changed to reflect this, for example:

> Important: Browser-based applications can't use this library. Only servers, command-line scripts, as well as Flutter mobile & desktop apps can import and use dart:io.

Perhaps even better with such a long list might be something like:

> Important: Browser-based applications can't use this library. Only the following can import and use dart:io
> - Servers
> - Command-line scripts
> - Flutter mobile apps
> - Flutter desktop apps

**Comment by a-siva** [comment]
@kwalrath if you think this change looks fine to you we can make the change in sdk/lib/io/io.dart

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/159590
