### ISSUE TITLE
Can no longer ignore argument_type_not_assignable

### ISSUE THREAD

**Issue by shyndman** [dart-lang/sdk#43092]
Hi there,

After a recent upgrade from Dart 2.8.1 to 2.9.1, I've found that I can no longer ignore the `argument_type_not_assignable` error. Was this intentional?

The reason I ask: I have several generated files where I took a shortcut by omitting casts, and including a file-level ignore. Do I need to go back and fix the generation to include casts?

Thanks!

**Comment by shyndman** [comment]
It appears that `implicit_dynamic_type` cannot be ignored either.

**Comment by bwilkerson** [comment]
Yes, 2.9.1 contains a change that makes it impossible to ignore any diagnostic with a severity of `error`. That has caused some difficulties for several people, so a discussion is going on as to the best way to address the situation. See #42977 for more details.

**Comment by shyndman** [comment]
Aha! Well that's no problem at all for me. Thanks Brian!
