### ISSUE TITLE
[CFE] Implement changes to null safety checking for local variables

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43099]
Small set of changes to the errors and warnings around local variables landed [here](https://github.com/dart-lang/language/pull/1091).  

Tests for the the definite assignment based errors landed [here](https://dart-review.googlesource.com/c/sdk/+/157881).

Tests for the inference and promotion section to follow.

**Comment by leafpetersen** [comment]
Note that I believe these tests should be fixed by this work as well:

co19/Language/Variables/final_t04
co19/Language/Variables/final_t05
co19/Language/Variables/final_t06
co19/Language/Variables/final_t07

**Comment by leafpetersen** [comment]
These tests should also be fixed with this work:

language/final/syntax_test/01
language/final/syntax_test/02

**Comment by leafpetersen** [comment]
@johnniwinther I believe this issue covers the tests you have marked with "Late assignment of final variable: Not sure if spec is ready yet." in our tracking spreadsheet.  As far as I know, the spec for this is complete and landed, are there open issues I'm forgetting?

**Comment by johnniwinther** [comment]
Thanks for the clarification. At this point we're then waiting for the flow analysis to be updated according to the spec. After that we might have some additional integration work on the CFE side.

**Comment by leafpetersen** [comment]
New tests for the inference and initialization portion landed [here](https://dart.googlesource.com/sdk/+/041261f92f588e8c410058a0a22a325e7d5e4962)

Failing: language/nnbd/inference/variable_initialization_promotion_test
Passing: language/nnbd/inference/variables_initialized_to_null_test

**Comment by stereotype441** [comment]
Reopening since https://dart-review.googlesource.com/c/sdk/+/165564 reverted the fix
