### ISSUE TITLE
expose GC events through a native C API directly bypassing service stream 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#43106]
We have internal embedders streaming GC events from their services into monitoring by listening to GC stream via `Dart_SetNativeServiceStreamCallback`. However they want to run their servers using `PRODUCT` builds - which excludes this functionality. 

Amount of information exposed though this API is very minimal - so we could simply extend our C API to expose the very same events using a pure C API along the lines of 

```
typedef struct {
   ...
} Dart_GCStats;

typedef struct {
  const char* reason;
  Dart_GCStats new_space;
  Dart_GCStats old_space;
  ... 
} Dart_GCEvent;

typedef void (*Dart_GCEventCallback)(Dart_GCEvent* event);
void Dart_SetGCEventCallback(Dart_GCEventCallback callback);
```

**Comment by mraleph** [comment]
@cskau-g Clement could you take a stub at this whenever you have the next free cycle?

**Comment by cskau-g** [comment]
I'll have a look.

**Comment by cskau-g** [comment]
Do we know which specific information we want to expose through this API?
The Heap `GCStats` collect {before,after} x {new,old} x {capacity_in_words,used_in_words,external_in_words} as well as some high level stats like GCType and GCReason.
Do we just want to mirror this, or are going for a sub-/superset?

**Comment by mraleph** [comment]
@cskau-g I think we should mirror whatever information is exposed through JSON events you get via `Dart_SetNativeServiceStreamCallback` - because this is what we stream out of the live service.

**Comment by cskau-g** [comment]
This feature has landed and appears to have stuck. Closing.
