### ISSUE TITLE
[Analyzer] Implement changes to null safety checking for local variables.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43100]
Small set of changes to the errors and warnings around local variables landed [here](https://github.com/dart-lang/language/pull/1091).  

Tests for the the definite assignment based errors landed [here](https://dart-review.googlesource.com/c/sdk/+/157881).

Tests for the inference and promotion section to follow.

cc @scheglov

**Comment by scheglov** [comment]
First portion - reading.
https://dart-review.googlesource.com/c/sdk/+/159382

`co19` should be updated.
https://github.com/dart-lang/co19/issues/913

**Comment by scheglov** [comment]
We have one test that fails: `tests/language/nnbd/definite_assignment/definite_assignment_error_test.dart`
AFAIK this is https://github.com/dart-lang/sdk/issues/42990

**Comment by leafpetersen** [comment]
New tests for the inference and initialization portion landed [here](https://dart.googlesource.com/sdk/+/041261f92f588e8c410058a0a22a325e7d5e4962)

Failing: language/nnbd/inference/variable_initialization_promotion_test
Passing: language/nnbd/inference/variables_initialized_to_null_test

**Comment by stereotype441** [comment]
All of these tests are now passing.
