### ISSUE TITLE
nnbd migration tool doesn't recognize `switch {return in all cases} return null` pattern

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#43123]
Consider the following code:

```dart
enum Enum { a, b }
int test(Enum enum) {
  switch (enum) {
    case enum.a: return 0;
    case enum.b: return 1;
  }
  return null; // in case enum is null, but it never is; Dart today requires this line
}
```

If the migration tool decides `enum` is non-nullable, it still decides `test`'s return value is `int?`, even though the only reason is that the function ends with a return that, once `enum` is non-nullable, becomes dead code.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
