### ISSUE TITLE
Not possible to switch off "Dart ML completion"

### ISSUE THREAD

**Issue by petro-i** [dart-lang/sdk#43134]
Thank you for taking the time to file an issue!

This tracker is for issues related to:
Analysis server version: 1.28.0
Dart SDK: 2.10.0-11.0.dev (dev) (Tue Aug 11 02:21:48 2020 -0700) on "windows_x64"
Android-Studio, AI-193.6911.18

Due to bad standard code completions I have been recklessly enabled the "Dart ML completion" by editing the dart.server.additional.arguments configuration value to include the command-line argument: --enable-completion-model in Android studio. 
Then I observed abnormal memory consumption by Android Studio (reported by AS), I suggested that this option changed almost nothing in prediction and tried to clear mentioned parameter, it cleared, but memory leak still took place. Now it looks like code completion still behaves as "Dart ML completion" option not switched off  - slow, consumes memory, high CPU usage).

Is there any special steps to switch off mentioned option?

BTW the status of  ML code completion never reported as "enabled" in on Analysis Server Diagnostics page, but something was changing memory consumption at least.

**Comment by lrhn** [comment]
(I have no idea, but try clearing your cache. Seems to be the equivalent to "turn it off and on again" for the analyzer :grin:).

**Comment by srawlins** [comment]
@bwilkerson this feature and issue are obsolete, correct?

**Comment by bwilkerson** [comment]
Yes. It's no longer possible to enable the feature.
