### ISSUE TITLE
Null safety feedback: Any ETA?

### ISSUE THREAD

**Issue by ollydixon** [dart-lang/sdk#43133]
We are really looking forwards to this feature, it's probably the most important feature this year for Dart (for us!)
Any idea of how close we are too releasing it?

**Comment by devoncarew** [comment]
Hi - the latest update we announced was here: https://medium.com/dartlang/announcing-sound-null-safety-defd2216a6f3 (~June 10th).

You could reach out to some of the resources on https://dart.dev/community - for instance, the misc discussion forum - to see if there are any further updates (this issue tracker is better for bugs and feature requests). Thanks!
