### ISSUE TITLE
Late fields can't refer to instance variables without `this.`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43137]
The following code is accepted by the analyzer but rejected by the CFE.  I believe it is valid:
```dart
class B {
  final int x;

  B(this.x);
}

class C extends B {
  late final y = x + 1;

  C(int x) : super(x);
}

main() {
  print(C(1).y);
}
```
The CFE says:
```
test.dart:8:18: Error: Getter not found: 'x'.
  late final y = x + 1;
                 ^
```
Interestingly, changing `x` to `this.x` works around the problem.

**Comment by stereotype441** [comment]
@johnniwinther FYI

**Comment by lfkdsk** [comment]
@stereotype441 
Hi, I try to fix this by this pr : https://github.com/dart-lang/sdk/pull/43156
