### ISSUE TITLE
keyword 'is', 'as' has little chaos when import a class use unregular path.

### ISSUE THREAD

**Issue by liuyang-kevin** [dart-lang/sdk#43158]
In My project, i use "is" check class type. there was a chaos result when I import a class use unregular path.

here is a Exception for this question. I use runtimeType toString, check its type equel. and cast it. 
```
type 'RedPointVM' is not a subtype of type 'RedPointVM' in type cast where
  RedPointVM is from package:dacall/model/view/global.dart
  RedPointVM is from package:dacall/model/view//global.dart
```

```dart
  VM get<VM>({Function(VM) run}) {
    for (var _vm in dataSet) {
      if (_vm is VM) {    //  <------ when import path has “//”， this result is false
        if (run != null) run(_vm as VM);
        return _vm as VM;
      }
    }
    throw Exception('GlobalViewModel.dataSet中找不到 ${VM} 实例对象');
  }
```

**Comment by lrhn** [comment]
Don't do that, then.

Dart identifies libraries by their import URIs. If the same library is imported using two different URIs, then it becomes two different libraries, declaring different types with the same name.
The language does not understand file systems. Originally, Dart could load source from `http://` URIs, and the web server could return different files for different URIs, no matter how the URIs differed. The only way to be safe was to treat the two URIs as importing different libraries.

It's annoying, and we might want to open up for the compilers to allow more libraries to be considered equivalent (allow some kind of canonicalization of different URIs which can be detected as denoting the same file), but currently that's how it works.
