### ISSUE TITLE
No code completion for super constructor parameter names

### ISSUE THREAD

**Issue by totalerex** [dart-lang/sdk#43159]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Analyzer
the IDE you are using and it's version (Android-Studio, AI-193.6911.18)
Analysis server version: 1.28.0
Dart SDK: 2.10.0-11.0.dev (dev) (Tue Aug 11 02:21:48 2020 -0700) on "windows_x64"s)

![image](https://user-images.githubusercontent.com/42652300/91027546-e980a000-e604-11ea-8994-a0492c957e31.png)

I afraid that I could be wrong but, it was working earlier, isn't?

**Comment by bwilkerson** [comment]
I don't know whether it was working before, but it certainly ought to work. Thanks for letting us know.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/159964
