### ISSUE TITLE
How FutureOr<T> works?

### ISSUE THREAD

**Issue by guangmingzizai** [dart-lang/sdk#43160]
I want to define a type like `FutureOr`, for example:
```dart
@pragma("vm:entry-point")
abstract class PromiseOr<T> {
  // Private generative constructor, so that it is not subclassable, mixable, or
  // instantiable.
  PromiseOr._() {
    throw new UnsupportedError("PromiseOr can't be instantiated");
  }
}
```
The code is identical to `FutureOr`, but it doesn't work.

**Comment by eernstg** [comment]
`FutureOr` is a built-in type which is basically a union type for the special case where the union has the form `Future<T> | T` for some `T`. So you can't get the same special treatment of any type that a non-system library can define.

You might have some plans to create your own fork of the Dart system and SDK (I can see that you're using `@pragma("vm:entry-point")`), but you would then need to introduce a treatment of types like `PromiseOr` which is similar to the many special exceptions with `FutureOr` in the common front end and the analyzer, and probably in additional tools such as dart2js.

**Comment by AsteriskZuo** [comment]
sdk/runtime/vm/class_id.h
sdk/runtime/vm/object.h
FutureOr implement  in C++ native code.
FutureOr define in object.h
I hope this is helpful.
I am also a curious person.
