### ISSUE TITLE
Quick fix "Create constructor for final fields" should ignore "late final" fields

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43161]
In a library that's opted into null safety, if I start with code like this:
```dart
class A {
  late final int x; // (1)
  final int y; // (2)
}
```
I get an error "The final variable 'y' must be initialized" at (2), but no error at (1).  This is expected, because "late final" fields don't have the strict initialization requirements of non-late final fields.

However, if I select the analysis server quick fix: "create constructor for final fields", the generated code tries to initialize both fields:
```dart
  A(this.x, this.y);
```
Although this is semantically valid Dart, it's definitely not what I want.  The only reason to make a final variable `late` is so that it's possible to initialize later.  I believe this quick fix should ignore late fields and simply generate:
```dart
  A(this.y);
```

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/159962
