### ISSUE TITLE
Directory().list can't recurse past directories that report permission denied

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#43179]
I'm essentially trying to re-implement the linux `find` command in dart (this is part of a console  api that I'm writing).

The problem that I'm encountering is that the Directory().list command throws an exception when it encounters a directory for which it doesn't have permission to access.

The standard linux `find` command simply reports an error and continues scanning for additional files.

Like the linux find command I'm looking to be able to continue listing directories even if a permission denied error occurs.

The dart Directory.list command throws an exception :
```
FileSystemException: Directory listing failed, path = '/usr/lib/ssl/private' (OS Error: Permission denied, errno = 13)
```

```
void main(List<String> args) {
  var listener = Directory('/').list(recursive: true);
  listener.listen((entity) {
  });
}
```
Note: the listener is required to reproduce the error.

The current implementation means that its impossible to guarantee a complete directory listing if there is just one file or directory for which the user doesn't have access.

Not certain of the best way to solve the problem but a couple of possibilities:

1) additional named argument - skip/suppressPermissionDenied - it would be nice if these were reported through the onError mechanism or some info on the produced 'FileSystemEntity'.
2) honour the cancelOnError flag
 - I'm probably mis-understanding this but I thought if cancelOnError was false that the stream would keep running even if an error was produced. I guess the exception isn't considered a recoverable error?

Option 2 feels like it might cause breakage in the api contact.

System info.
```
dcli doctor
DCli version      0.21.0                                                 

OS                linux                                                  
OS Version        Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
Path separator    /                                                      

dart version      2.9.1                                                  

dcli path         /<HOME>/.pub-cache/bin/dcli                            
dart exe path     /usr/bin/dart                                          
dart path         /usr/bin/dart                                           which: /usr/bin/dart                                   
dart2Native path  /usr/lib/dart/bin/dart2native                           which: /usr/lib/dart/bin/dart2native                   

pub path          /usr/lib/dart/bin/pub                                   which: /usr/lib/dart/bin/pub                           
Pub cache         /<HOME>/.pub-cache                                     

Package Config    /tmp/temp/file:/<HOME>/git/dcli/.packages              

PATH
                  /usr/local/sbin                                        
                  /usr/local/bin                                         
                  /usr/sbin                                              
                  /usr/bin                                               
                  /sbin                                                  
                  /bin                                                   
                  /usr/games                                             
                  /usr/local/games                                       
                  /snap/bin                                              
                  /usr/lib/dart/bin                                      
                  /<HOME>/apps/flutter/bin                               
                  /<HOME>/.pub-cache/bin                                 
                  /<HOME>/.dcli/bin                                      

$SHELL            /bin/bash                                              
Detected SHELL    bash                                                   
Shell Start Scrip Not Found                                              

Dart location(s)
                  /usr/bin/dart                                          

Permissions
HOME              rwxr-xr-x <user>:<user> /<HOME> 
.dcli             rwxrwxr-x <user>:<user> /<HOME>/.dcli 
cache             rwxrwxr-x <user>:<user> /<HOME>/.dcli/cache 
dependencies.yaml rw-rw-r-- <user>:<user> /<HOME>/.dcli/dependencies.yaml 
templates         rwxrwxr-x <user>:<user> /<HOME>/.dcli/templates 

.dcli/dependencies.yaml
  dcli            dcli: ^0.20.0                                          
  args            args: ^1.5.2                                           
  path            path: ^1.6.4               
```

**Comment by devoncarew** [comment]
Thanks for the report! My read on the above is that we don't have a way to return a partial directory listing (of the items we can see), or, that we don't list everything in a directory (but wouldn't allow you to get additional info about items that we don't have permissions for)?

**Comment by bsutton** [comment]
I'm not looking for additional info just for the listing to continue and
ideally report that permission was denied.

The current implementation severely restricted the usefulness of the list
method.

**Comment by bsutton** [comment]
If you run the linux find command you see output as follows:

```
find / -name 'fred'

/run/libvirt/nwfilter-binding
find: ‘/run/libvirt/nwfilter-binding’: Permission denied
/run/libvirt/nwfilter
find: ‘/run/libvirt/nwfilter’: Permission denied
/run/libvirt/nodedev
find: ‘/run/libvirt/nodedev’: Permission denied`
```

To get a similar result I'm thinking that the returned FileSystemEntry should return the name of the entity and a 'code' to indicate that the permission was denied.

Obviously if we see a directory for which we don't have permissions then we can't recurse into the directory. This is fine. I just need the directory name reported and the fact that I don't have permissions to access it and then the list command continues on reporting other entries.

I'm not looking for you to break the permission model (given that would actually be impossible) just to report what you can see and if a permission error occurred and then continue listing files/directories that you can see.

It should be really simple :D

**Comment by devoncarew** [comment]
>  I'm not looking for you to break the permission model (given that would actually be impossible) just to report what you can see and if a permission error occurred and then continue listing files/directories that you can see.

Sure makes sense. Thanks again for the report; I've added the labels so that the right team will see this. The complexity would probably be around whether we needed API changes in order to support this.

**Comment by bsutton** [comment]
I have a compromise position.

Simply report the directory as you do any other directory and continue with the listing of files/directories.

If I need to know if the directory is accessible I can do a subsequent call to determine this myself.

This results in no change to the api.

You could argue that it is a change in the contract i.e. currently a permission denied exception is thrown,
but I would argue that the current implementation is faulty is it makes the Directory.list command very limited in its usefulness.

**Comment by zichangg** [comment]
"Permission denied" is not as fatal as other errors. I think it is safe to make permission errors not stopping the listing.
@lrn @sortie Any thought?

**Comment by sortie** [comment]
Hiding operating system errors is not a good design. It's important that callers are able to distinguish "this is the correct result" from "something went wrong". Subtly sometimes omitting results under certain conditions means the caller can't do that.

The useful low level primitive is Directory.list(recursive: false) that reads a directory and corresponds to the appropriate readdir(3) system calls on the operating system. This corresponds to what command line tools like find(1) uses. It will fail if there is an error. You will have to use it repeatedly to recurse.

Directory.list(recursive: true) is a utility feature that doesn't correspond to any low level system call. It's for convenience for circumstances where someone wants to list recursively as a single call, but that means listing operations are combined and might fail together. It means it's really only useful for circumstances where the caller knows the whole operation is going to succeed, such as subdirectories made by the current program for the current user. Arguably we could ignore certain errors, but there's any number of those and these are difficult choices to make properly, and we would have to pretend to the caller that certain directories didn't exist or were empty. That means returning a false result as if it was the truth, which it isn't. Callers would in principle want any sort of policy regarding how to handle error which could complicate the API, which is why it's best to provide a good low level API like Directory.list(recursive: false) that callers can use to their preferences.

There's nothing special about Directory.list(recursive: true) that you can't do yourself and handle errors as you see fit. You can write recursive code that recurses on directory listings. Alternatively you can wrap the list stream to expand it with subdirectory results. This design would correspond to how tools like find(1) are implemented.

**Comment by bsutton** [comment]
I hadn't thought of the manual recursion path however your logic is still problematic.

The current list(recursion: false) still doesn't allow me to get a list of directories or files if there is a single file or directory that has permission issues. The list command throws as soon as it sees the first file/directory that is permission denied and there is no way to get a list of the remaining files/directories.

As such there is no way that I can implement `ls` or `find`.

Essentially the list(recusive: false) isn't low level enough.


>  Arguably we could ignore certain errors
The simple answer here is that the low level api should  report every file/directory that the user has permission to see.
(I have permission to see a directory but not the contents so return the directory but not the contents - this is forced on us by the OS anyway)

We then provide additional api's that let the user ask questions about the system entity to determine if there are problems such as if they have access.

> would have to pretend to the caller that certain directories didn't exist or were empty
Your not pretending, you are simply providing a list of the visible directories/files. This is what I expect of ls/find or any other tool. It should be left up to the tool implementer to decide how to present additional information about those files directories.
The current implementation takes those decisions out of the hands of the tool developers (e.g. me :) )


So the  policy should be changed to 'return every file/directory' that we can see and then the user can use a subsequent call if they need to determine any additional status information of a file/directory.

In this way we now have an appropriate low level api.

As its stands the dart api does not provide a general purpose api.

**Comment by sortie** [comment]
@bsutton `Directory.list(recursive: false)` has the right behavior for me when I test it:

```
echo foo > foo
mkdir bar
echo cool > bar/cool
chmod 000 foo bar
sudo chown root:root foo bar
```

And then:

```
import 'dart:io';
Future<void> main() async { 
  print(await new Directory(".").list(recursive: false).toList());
}
```

Writes `[File: './foo', Directory: './bar']`.

Do you have any reproducible cases where `Directory.list(recursive: false)` has the wrong behavior where ls on the directory would succeed, i.e. you actually have permission to iterate it? Otherwise it seems to me that `Directory.list(recursive: false)` provides exactly the low level behavior you can build on top of it.

**Comment by bsutton** [comment]
Apologies, my mistake.
I interpreted your earlier statement that it would throw if it encounter an error, to mean that it would throw on Permission denied.

I've just ran a test and got the same results as you.

As such I'm happy to leave this issue closed.
