### ISSUE TITLE
High variability when running simple code using dart2native and AOT

### ISSUE THREAD

**Issue by jeanbez** [dart-lang/sdk#43182]
Hi! I'm using Dart SDK version 2.9.1 (stable) on a LXC container in Ubuntu 20 and I've observed some variations in runtime using Dart. For instance, this simple code that reads two numbers and print the sum has runtimes of 0.0s up to 0.9s. I noticed the same runtime variability with and without AOT. Is this normal, or there is something that can be done to make the runtime more consistent between consecutive runs?

```
import 'dart:io';

void main()
{
    int a = int.parse(stdin.readLineSync());
    int b = int.parse(stdin.readLineSync());

    int soma = a + b;

    print("X = $soma");
}   
```

Time: 0.008
Time: 0.973
Time: 0.000
Time: 0.000
Time: 0.000

This is using a couple of repetitions only, but the same behavior is observed when repeating 100 times or more, with the random high runtime randomly being observed.

**Comment by lrhn** [comment]
This high a variability is unlikely to come from the execution of the code shown here. It's more likely that it's I/O based, so maybe something is holding up the input lines that you read from stdin.

**Comment by mraleph** [comment]
There is some natural variability in execution. I don't think there is anything we can do here.
