### ISSUE TITLE
Could split dill (kernel or bytecode) into some dills and load them separately？

### ISSUE THREAD

**Issue by lfkdsk** [dart-lang/sdk#43183]
split `Component` by library and save as `xxx.dill` and load them separately.

**Comment by mraleph** [comment]
You need to clarify this a bit (e.g. is this a request to VM or something else)?

In general we support this and use it in some environments - for example you can give VM a list of dill binaries to load, for that you create a file in the following format:

```
#@dill
<path-to-dill1>
...
<path-to-dillN>
```

Alternatively can also just concatenate two dill files into a single one - result is a valid dill file with multiple components.

For VM there is just a requirement that dill files are sorted in reverse topological order according to their dependencies.

Let me know if you have any further questions.
