### ISSUE TITLE
dart:mirrors. Metadata is not reflected

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43186]
The following code shows no metadata before type parameter reflected
```dart
import 'dart:mirrors';

class A {
  const A();
}

class B<@A() T> {
}

main() {
  print(reflectClass(B).typeVariables[0].metadata); // prints []
}
```
The second example shows no metadata before typedef
```dart
import 'dart:mirrors';

class A {
  const A();
}

@A()
typedef void f(int, String);

main() {
  print(reflectType(f).metadata); // prints []
}
```

`Dart SDK version: 2.10.0-56.0.dev (dev) (Mon Aug 24 09:17:19 2020 -0700) on "windows_x64"`

**Comment by a-siva** [comment]
dart:mirrors is not an actively supported library and issues against it may not be addressed unless the failure is deemed to be a regression.

**Comment by a-siva** [comment]
At this point we have no plans for enhancing the `dart:mirrors` library.
Please see https://github.com/dart-lang/sdk/issues/44489 which is investigating a path towards discontinuing support for `dart:mirrors`
