### ISSUE TITLE
Breaking change request:SplayTreeSet, generic type E should extends Comparable<E>

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#43187]
consider this case:
var set = SplayTreeSet();
  set.add("ss");
  set.add(8);

it will not wrong by static analyze, but will throw ex in runtime, if E extends Comparable<E>,
user must use a explict type for SplayTreeSet initialize

**Comment by lrhn** [comment]
Dart 2 has inherited some code from Dart 1 which doesn't play well with strong typing.
This is one of them (`List.sort` is similar).

The `SplayTreeSet` *does work* for non-comparable elements, as long as you provide a `compare` function. Restricting it to non-`Comparable` types would be massively breaking.

What Dart doesn't have is a way to make the constructor parameter optional only in some cases. For example, if we could say that `SplayTreeMap([int Function(E, E) compare])` made the parameter required if `E` was not `Comparable<E>`, but optional when it did implement `Comparable<E>`, then the code would both work the same way it does today, and it would catch some run-time errors at compile time.

Another option is to change the constructor to two factories:
```dart
SplayTreeSet(int compare(E a, E b)) : ....;
static SplayTreeSet<T> comparable<T extends Comparable<T>>() => SplayTreeSet<T>(compareComparable);
```
Still, that would be too breaking for us to just slip it in. It could requires a significant migration, and it's not been considered high enough a priority to actually do that.
(And it won't fix the other similar cases, like `List.sort`).

So, unless we get some language support for forcing the parameter to be required in some cases, we don't plan to change the API, and we'll have to live with some run-time errors for APIs that can't be soundly typed statically.
