### ISSUE TITLE
Unexpected message for unnecessary null-aware operator

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#43189]
Repro code:

```dart
void main() {
  const s = 'foo bar';
  print(s?.length);
}
```

Analyzer message:
```
The receiver can't be null, so the null-aware operator '?.' can't be used.
Try replacing the operator '?.' with '.'.
```

I find this phrasing a bit odd; is this actually disallowed? The code runs just fine. I'd expect something like:

```
The receiver can't be null, so the null-aware operator '?.' is unnecessary.
Try replacing the operator '?.' with '.'.
```

**Comment by mraleph** [comment]
Specification says: 

> It is a warning to use a null aware operator (?., ?[], ?.., ??, ??=, or ...?) on an expression of type T if T is strictly non-nullable.

So the phrasing it indeed odd.

**Comment by mit-mit** [comment]
cc @bwilkerson

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/169962
