### ISSUE TITLE
show the 'dart migrate' command in the stable release channel in the null safety TP2 / null safety beta timeframe

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43194]
The `dart migrate` command is currently hidden for users on the stable release channel. This tracks showing it the stable channel in the null safety TP2 / null safety beta timeframe.

We should evaluate whether to show it in the TP2 or null safety beta timeframes.

**Comment by mit-mit** [comment]
@devoncarew I'll move this to the stable Epic as it doesn't block the beta launch (for that we need `migrate` exposed in beta builds, which it already is.

**Comment by devoncarew** [comment]
This was addressed.
