### ISSUE TITLE
Wrong error is thrown by ByteData.view constructor on dart2js and dartdevk

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43196]
According to the ByteData.view constructor [documentation](https://api.dart.dev/stable/2.9.1/dart-typed_data/ByteData/ByteData.view.html)

> Throws RangeError if offsetInBytes or length are negative, or if offsetInBytes + (length * elementSizeInBytes) is greater than the length of buffer.

In fact, `ArgumentError` is thrown on dart2js and `JSRangeError` on dartdevk

The same issue exists for any ByteData getXXX/setXXX methods. For example
```dart
var byteData = new ByteData(5);
byteData.setUint16( 4, 0);
```
Produces `ArgumentError` instead of `RangeError`

Upd. This is true for any `XXXList.view` constructor from `typed_data` library as well. For example `Float32x4List.view()`

**Comment by nshahan** [comment]
In DDC the `JSRangeError` is an `ArgumentError`.

@sgrekhov Can you take a look at `co19/LibTest/typed_data/Float32List/Float32List.view_A06_t01.dart` and `co19/LibTest/typed_data/Int32List/Int32List.view_A06_t01.dart` help me clarify the expectations?

According to the comments in the test file and `.view()` methods the expected error should be `ArgumentError` but the tests expects a `RangeError`.  

cc @fishythefish These tests are also failing in dart2js for a similar reason.

**Comment by nshahan** [comment]
@alexmarkov The tests I mentioned above are passing in the VM. Is it throwing the wrong type of error based on the comment in the `view()` methods?

**Comment by sgrekhov** [comment]
@nshahan These expectations were wrong. According to the documentation there must be an `ArgumentError`. Fixed by https://github.com/dart-lang/co19/commit/28c6cdf1ca543d07662ac4dec227f2881302db40. Thank you for pointing

**Comment by lrhn** [comment]
The documentation should he changed to not specify which `Error` is thrown.
The format we typically use for documenting error conditions is "must"-clauses:
> The [offsetInBytes] and [length] must be non-negative, 
> and `offsetInBytes + (length * elementSizeInBytes)` must be no greater than the length of the buffer.

**Comment by nshahan** [comment]
@sgrekhov Given that you updated the tests, is this still an issue? Was the original issue tied to the same tests?

**Comment by sgrekhov** [comment]
@nshahan it is still an issue. Only 
```
LibTest/typed_data/Float32List/Float32List.view_A06_t01.dart
LibTest/typed_data/Int32List/Int32List.view_A06_t01.dart
```
were updated in https://github.com/dart-lang/co19/commit/28c6cdf1ca543d07662ac4dec227f2881302db40 to expect `ArgumentError` instead of `RangeError` according to [Float32List.view](https://api.dart.dev/stable/2.9.3/dart-typed_data/Float32List/Float32List.view.html) and [Int32List.view](https://api.dart.dev/stable/2.9.3/dart-typed_data/Int32List/Int32List.view.html) documentation (documentation for these constructors states `ArgumentError`). The issue is still actual for the following tests (theyr documentation states `RangeError`)
```
ByteData.view_A05_t01.dart
ByteData.view_A05_t02.dart
ByteData.view_A05_t03.dart
Float32List.view_A05_t01.dart
Float32List.view_A05_t02.dart
Float32List.view_A05_t03.dart
Float32List.view_A06_t01.dart
Float32x4List.view_A05_t01.dart
Float32x4List.view_A05_t02.dart
Float32x4List.view_A05_t03.dart
Float64List.view_A05_t01.dart
Float64List.view_A05_t02.dart
Float64List.view_A05_t03.dart
Float64x2List.view_A05_t03.dart
getFloat32_A02_t01.dart
getFloat32_A02_t02.dart
getFloat64_A02_t01.dart
getFloat64_A02_t02.dart
getInt16_A02_t01.dart
getInt16_A02_t02.dart
getInt32_A02_t01.dart
getInt32_A02_t02.dart
getInt8_A02_t01.dart
getInt8_A02_t02.dart
getUint16_A02_t01.dart
getUint16_A02_t02.dart
getUint32_A02_t01.dart
getUint32_A02_t02.dart
getUint8_A02_t01.dart
getUint8_A02_t02.dart
Int16List.view_A05_t01.dart
Int16List.view_A05_t02.dart
Int16List.view_A05_t03.dart
Int32List.view_A05_t01.dart
Int32List.view_A05_t02.dart
Int32List.view_A05_t03.dart
Int32x4List.view_A05_t01.dart
Int32x4List.view_A05_t02.dart
Int32x4List.view_A05_t03.dart
Int8List.view_A05_t01.dart
Int8List.view_A05_t02.dart
Int8List.view_A05_t03.dart
setFloat32_A02_t01.dart
setFloat32_A02_t02.dart
setFloat64_A02_t01.dart
setFloat64_A02_t02.dart
setInt16_A02_t01.dart
setInt16_A02_t02.dart
setInt32_A02_t01.dart
setInt32_A02_t02.dart
setInt8_A02_t01.dart
setInt8_A02_t02.dart
setUint16_A02_t01.dart
setUint16_A02_t02.dart
setUint32_A02_t01.dart
setUint32_A02_t02.dart
setUint8_A02_t01.dart
setUint8_A02_t02.dart
Uint16List.view_A05_t01.dart
Uint16List.view_A05_t02.dart
Uint16List.view_A05_t03.dart
Uint32List.view_A05_t01.dart
Uint32List.view_A05_t02.dart
Uint32List.view_A05_t03.dart
Uint8ClampedList.view_A05_t01.dart
Uint8ClampedList.view_A05_t02.dart
Uint8ClampedList.view_A05_t03.dart
Uint8List.view_A05_t01.dart
Uint8List.view_A05_t02.dart
Uint8List.view_A05_t03.dart
```

**Comment by nshahan** [comment]
@sgrekhov Thanks for the list of failing tests. I'll take a look and see if there is a simple fix that would bring DDC closer to the other implementations.

@lrhn Do you feel the same way about the entire typed_data API? Should we be updating the comments throughout the library so that they don't mention a specific error/exception class?

**Comment by lrhn** [comment]
@nshahan I feel that way about the entire SDK. We shouldn't specify which `Error` is thrown. It's something I often fix when I touch code for other reasons, but I haven't made it a priority to fix everything once and for all. It's not a *big* issue, just a slight annoyance.
Errors shouldn't happen. When they do, it doesn't matter which class we use to report the error, that's just a convenience to get better and more consistent error messages (and maybe make debugging a little easier).
Specifying precisely which error is thrown is unnecessary and restrictive, and has caused us unnecessary extra work when JS compiled code needs to convert a JS exception to a specific Dart error.

We should specify exactly which `Exception`s are thrown, because users are expected to catch those precisely by name.

**Comment by nshahan** [comment]
The documentation has been updated in the typed data library to be more general. I'll close this issue since we are not planning on updating the web backends to throw these specific errors.

I opened https://github.com/dart-lang/co19/issues/955 to track updating the tests accordingly.
