### ISSUE TITLE
Fix the dartdev analytics reporting logic to include Events and CustomDimensions

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#43198]
- Remove the current way that we collect flags in the `dartdev` analytics logic
- Add event types like the `flutter` cli tool does
- Add custom dimensions like the `flutter` cli tool does for dashboard purposes

**Comment by franklinyow** [comment]
Ready to close?

**Comment by jwren** [comment]
@franklinyow No, this was a new requirement that we put on `dartdev` last week, I am actively working on it now.  https://dart-review.googlesource.com/c/sdk/+/161200 for the latest.

**Comment by devoncarew** [comment]
Moving to P2 - I think we'd like this for the Sept. release but it's not blocking; will work w/ Jaime for additional triage.

**Comment by devoncarew** [comment]
Closing - this has been addressed.
