### ISSUE TITLE
ByteBuffer.asFloat32List() error on dart2js and dartdevk

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43204]
The following programm works in Dart VM but on dart2js and dartdevk produces an error
```
Runtime error:
RangeError: byte length of Float32Array should be a multiple of 4
```
```dart
import "dart:typed_data";

main() {
  var list1 = new List.filled(5, 0);
  ByteBuffer buffer = new Int8List.fromList(list1).buffer;
  int bufSizeInBytes = buffer.lengthInBytes;
  print(bufSizeInBytes); // 5
  Float32List res = buffer.asFloat32List(0); 
}
```

Similarly in case of `Float64List res = buffer.asFloat64List(0);` there will be an error on dart2js and dartdevk `RangeError: byte length of Float64Array should be a multiple of 8` and no error in VM

`Dart SDK version: 2.10.0-56.0.dev (dev) (Mon Aug 24 09:17:19 2020 -0700) on "windows_x64" `

**Comment by lrhn** [comment]
It seems the underlying `Float32Array(buffer, 0)` bails out if the third argument, length, is not provided and `buffer.lengthInBytes` is not a multiple of 4.
