### ISSUE TITLE
Null safety feedback: Any release ETA

### ISSUE THREAD

**Issue by ollydixon** [dart-lang/sdk#43205]
By far the most important feature for many developers who are doing Flutter right now, even Java had null safety back in 2004 (via annotations), something that every modern language has.

Do we have any ETA on this feature? I can't seem to find anything; just some post back in June! 👍

**Comment by mraleph** [comment]
Please don't repeatedly file the same issues: you have already asked in #43133 and got as much of a reply as we can give you. We don't share any ETAs externally as a rule. 

NNBD is currently in tech preview for Dart. It is being validated and bootstrapped by porting significant part of the ecosystem (which includes Flutter framework itself and related packages maintained by Flutter and Dart teams) to NNBD - it's a LOT of work as one might imagine. The only thing you can do is try it out yourself (though it's not recommended to use it production code or in Flutter apps), report issues and wait for announcement.

**Comment by ollydixon** [comment]
@mraleph so a couple of years. Got it.
