### ISSUE TITLE
Failures on [co19] enable isolate and mirrors tests...[dart2js] Flip new deferred split flag.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#43219]
There are new test failures on [[co19] enable isolate and mirrors tests...[dart2js] Flip new deferred split flag.](https://github.com/dart-lang/sdk/compare/29c0795f48ff8c12aa0793c0fbfef201eb423aed~...86785537001570c4eaf8291b2c66807fdbc30cfb).

The tests
```
co19/LibTest/isolate/Isolate/spawnUri_A05_t04 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-weak-asserts-linux-debug-x64
```
It looks like the test is timing out:
```
--- Command "vm" (took 07.000946s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --enable_asserts --no-sound-null-safety --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawnUri_A05_t04.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <ping>, actual: <timeout>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:20:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:30:5)
#2      test (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawnUri_A05_t04.dart:30:12)
<asynchronous suspension>
#3      main (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawnUri_A05_t04.dart:41:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-weak-asserts-linux-debug-x64 co19/LibTest/isolate/Isolate/spawnUri_A05_t04
```
There is still an old related issue pending:  https://github.com/dart-lang/sdk/issues/15974

**Comment by aam** [comment]
I believe the test has to be adjusted as it is racy - it is possible that the spawned isolate exits after sending 'finish' message before it had a chance to respond to ping message. Following seems to fix the test(prevents spawned isolate from exiting after it sends 'finish' message)
```
--- a/LibTest/isolate/Isolate/spawnUri_A05_t04_isolate.dart
+++ b/LibTest/isolate/Isolate/spawnUri_A05_t04_isolate.dart
@@ -11,6 +11,7 @@ import "dart:async";
 import "IsolateUtil.dart";
 
 main(List<String> args, SendPort sendPort) {
+  final rp = ReceivePort();
   dynamic i1 = 1, i2 = 2, i3 = 3, i4 = 4;
```

cc @sgrekhov

**Comment by sgrekhov** [comment]
@aam thank you! Test was updated https://github.com/dart-lang/co19/commit/a825e7eb8486dee8390fc678d43c1576662f344c

**Comment by aam** [comment]
Thanks @sgrekhov . The fix to the test made it to dart tests/co19, but not to tests/co19_2, which results in previously observed failures: https://dart-ci.appspot.com/log/vm-dartkb-linux-release-x64/dartkb-mixed-linux-release-x64/8770/co19_2/LibTest/isolate/Isolate/spawnUri_A05_t04.

What is the process to get tests/co19_2 updated?

**Comment by eernstg** [comment]
That's handled by creating an issue on the co19 repo; I just created https://github.com/dart-lang/co19/issues/940 for this.

**Comment by sgrekhov** [comment]
@aam missed co19_2, sorry. Fixed by https://github.com/dart-lang/co19/commit/7a8ae3ee87bbb1163fbf6deadb98185abd7e7d63
