### ISSUE TITLE
[NNBD] No static warning in analyzer for explicit member invocation and null-aware member access

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43217]
The following code produces a warning in VM and no issues in analyzer
```dart
class C {
}

extension Ext on C {
  int id() => 42;
}

main() {
  C c = C();
  Ext(c)?.id(); // In VM Warning: Operand of null-aware operation '?.' has type 'C' which excludes null
}
```
There must be a warning in analyzer as well

`Dart SDK version: 2.10.0-56.0.dev (dev) (Mon Aug 24 09:17:19 2020 -0700) on "windows_x64"`

**Comment by srawlins** [comment]
Analyzer now reports:

> warning • The receiver can't be null, so the null-aware operator '?.' is unnecessary. • a.dart:10:9 • invalid_null_aware_operator
