### ISSUE TITLE
Flow analysis handling of `??=` should use read type rather than write type

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43222]
Once https://dart-review.googlesource.com/c/sdk/+/160440 lands, flow analysis in the analyzer will determine whether the RHS of a `??=` expression is reachable based on the "write type" of the LHS; it should use the "read type".  So for example, in this code:
```dart
String get x => '';
set x(String? value) {}
num f(Object o) {
  if (o is num) {
    x ??= (o = 'bad');
    return 1 + o;
  } else {
    return 0;
  }
}
main() {
  print(f(1));
}
```
although the analyzer correctly reports that the right operand of `??=` is never executed, flow analysis fails to understand that this is the case, so it believes that `o = 'bad'` un-does the promotion of `o`, and therefore `1 + o` gives an error.

To fix this, the analyzer needs to record the "read type" of the LHS in the AST; I believe @scheglov is working on that.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/160444 landed, so the portion for `AssignmentExpression` in implemented.
I'm working on `PostfixExpression` and `PrefixExpression`.

**Comment by stereotype441** [comment]
Thanks @scheglov.  I'll rebase my CL and assuming everything works I'll close this bug.

**Comment by stereotype441** [comment]
Ok, I've rebased my CL and everything works.
