### ISSUE TITLE
expand allocation sinking to arrays

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#43228]
Currently allocation sinking can only handle objects allocated by `AllocateObject` and `AllocateUninitializedContext`.

We should expand it to the all array types (including typed arrays) when all loads/stores can be fully forwarded (e.g. length is a constant  and indices of accesses are constants as well).

Areas where this is expected to help:
- fully eliminating temporary matrices and vectors (vector_math)
- removing dead `CreateArray` instructions left behind after folding fully constant string interpolations.

/cc @mkustermann @alexmarkov

**Comment by alexmarkov** [comment]
I saw this problem on `ParticleSystem` benchmark, after it was updated to use current version of `package:vector_math`. We should also make sure that load forwarding works across typed data allocation.

I'd like to try this out.
