### ISSUE TITLE
constant fold StringInterpolate kernel nodes consisting only of string constants 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#43229]
CFE tends to produce `StringInterpolate` nodes when it encounters multiple consecutive string constants, e.g. 

```
var s = 'aaaa'
        'bbbb'
        'cccc';
``` 

We have constant folding rules for `StringInterpolate`, but we don't remove dead `CreateArray` and `StoreIndexed` instructions (https://github.com/dart-lang/sdk/issues/43228).

As a workaround we should at least add a simple constant folding to the kernel to IL translation. We have records of the following patterns produced by CFE (though it's a bit date information and some of this might have been already fixed)

```
StringInterpolate("...", StringInterpolate(...))
StringInterpolate(..., "")
StringInterpolate(Const1, …, ConstN)
```

All of these should be folded like this: 

```
StringInterpolate("...", StringInterpolate(strings)) => StringInterpolate("...", ...strings)
StringInterpolate(...strings, "") => StringInterpolate(...strings)
StringInterpolate(Const1, …, ConstN) => Const
```

**Comment by mkustermann** [comment]
@cskau-g Could you look into this one after finishing the outstanding tasks?

**Comment by cskau-g** [comment]
Sure.
I will update this issue again when I start work on it.

**Comment by mraleph** [comment]
Bumping the priority of this to P1 because multiple internal users are affected and overall solution is simple to implement on our side.

**Comment by cskau-g** [comment]
AFAICT, the above example - which matches the third pattern above - is currently being optimised by the 'Canonicalize' pass into the folded const.
As also mentioned above, the dead `CreateArray` and `StoreIndexed` are _not_ removed, so the original, unfolded consts are there too.
Unless I'm misunderstanding that should already satisfy the suggested optimisation for this pattern.

I will have a look at the other two patterns.

**Comment by mraleph** [comment]
> Unless I'm misunderstanding that should already satisfy the suggested optimisation for this pattern.

Just to clarify - I realized now that the issue is not very clear about that - we would like to fold it very early in the pipeline (at the kernel to il translation phase) so that original constants disappear and are not retained by the generated code through StoreIndexed instructions. Retaining original constants causes information leaks when interpolation itself is not used anywhere.

See https://b/160842614#comment23 for more context.

**Comment by cskau-g** [comment]
Are we interested in doing as much string interpolation at kernel->IR time as possible?
I.e. do we want to try handle cases other than str/str interpolation, such as `'hi ${123} $some_const'`?

**Comment by mraleph** [comment]
@cskau-g I feel we should not worry about other cases for now. I'd handle trees of string interpolations with string literals at leafs, and keep the rest out of scope for now.

**Comment by alexmarkov** [comment]
@mraleph @cskau-g We can also do this kind of early constant folding as a kernel AST transformation, maybe during https://github.com/dart-lang/sdk/blob/master/pkg/vm/lib/transformations/lowering.dart pass. This would be much more simple than matching patterns during kernel->flow graph translation.

**Comment by mraleph** [comment]
@cskau-g has landed the change. closing.
