### ISSUE TITLE
Odd type inference for Future.wait if any of the futures is Future<void>

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#43226]
Consider:

```dart
import 'dart:async';

Future<void> main() async {
  final results = await Future.wait([
    Future<void>.value(null),
    Future<int>.value(5),
  ]);
  print(results[1]);
}
```

This gives an error saying `results[1]` is void. Apparently, if I mix in a `Future<void>` anywhere in the list given to `Future.wait` the entire list is inferred to be `List<void>`. If I mix any any other types, it correctly becomes `List<dynamic>`.

**Comment by lrhn** [comment]
This is expected behavior. 

The value if a `Future,void>` must not be used. If we hide its result in a `List<dynamic>`, it can be used. So, if any of the values of the list has type `void`, the list has element type `void` to preserve the unusability of that element.

**Comment by mehmetf** [comment]
Interesting. A couple of comments:

I came across this issue when I changed a library API from `Future<Null>` to `Future<void>`. It broke some client code. They were doing something like this:

```dart
final results = await Future.wait([list with 4 elements one of which was the API I changed]);
...
...
final someResult = results[0]; // Not the index of the API I changed
...
// <14 lines later>
...
processResult(someResult);
...
```

The analyzer complained at the `processResult` call site about someResult being void whereas a cursory glance to code left me perplexed. An error at `final someResult = results[0];` with a message "`List<void>` results cannot be used" would have helped me identify the problem sooner.

Secondly, what is the idiomatic way of doing this? Waiting for a collection of Future's whether they are void or not is expected. Using the non-void values is also expected. We also ban not awaiting a future in an async function. Should the apps instead do:

```dart
import 'dart:async';

Future<void> main() async {
  final result = unawaited(Future<int>.value(5));
  await Future.wait([
    Future<void>.value(null),
    result,
  ]);
  print(await result);
}
```

This is awkward. Do you have any recommendations?
