### ISSUE TITLE
Every on empty array returns true

### ISSUE THREAD

**Issue by dmitryuck** [dart-lang/sdk#43236]
var result = [].every((e) => e == true);

print(result); // true

is it correct?

**Comment by mraleph** [comment]
> is it correct?

Yes. 

One way to look at this is to ask: is there any element in the list which does not satisfy the predicate? No. That means that all elements in list satisfy it.

**Comment by dmitryuck** [comment]
> does not satisfy the predicate

Very strange.

[].every should return true to satisfy, why need to think "not satisfy"

and the empty list doesn't have any elements, who should satisfy/not satisfy

please open again, so other members can get to think and discuss

**Comment by mraleph** [comment]
> [].every should return true to satisfy, why need to think "not satisfy"

There is a duality here which I tried to use to explain logic behind it. 

The duality is between `list.every((e) => predicate(e))` and `list.any((e) => predicate(e))` they are connected by an easy relationship: `list.every((e) => predicate(e)) == !list.any((e) => !predicate(e))` or in normal words: if every element of the list satisfies the predicate then no element of the list satisfies negation of the predicate and vice versa.

It's rather easy to understand why for any empty list `list.any(...)` always returns `false` - and from there it follows (by duality) that for empty list `list.every(...)` always returns `true`.

> please open again, so other members can get to think and discuss

There is nothing to really discuss here. That's how things work in any other programming language or mathematics (given any predicate and an empty set you can say that "every element of the set satisfies the predicate").

JavaScript: `[].every((e) => e === 0)` returns `true`. C# `Array.TrueForAll(new int[0], y => y == 0)` returns true as well, and so on.
