### ISSUE TITLE
Working with JSON

### ISSUE THREAD

**Issue by meisterfranz** [dart-lang/sdk#43237]
Today it isn't possible to imagine development without JSON. PLEASE add normal JSON serialization/deserialization like newtonsoft json.

**Comment by Peng-Qian** [comment]
hey mate,

You can try these awesome plugins:[built_value](https://pub.dev/packages/built_value) or [json_annotation](https://pub.dev/packages/json_annotation)

**Comment by mraleph** [comment]
We are aware of the problem and desire for language level solution in the space. There are other issues requesting similar, e.g. https://github.com/dart-lang/sdk/issues/36066. Consider giving thumbs up there.

**Comment by meisterfranz** [comment]
Thanks, @Peng-Qian. But working with these all packages is not comfortable (I mean generated files, writing factory constructors, etc.). It will be good to use something like this
```
class User{
  String firstName;
  String lastName;

  User(this.firstName, this.lastName);
}
```

`User user = User('John', 'Smith');`

**Serialization** 

`String jsonFromInstance = JsonConvert.serialize(user);`

**Deserialization** 

```
String jsonString = '''
{
  "firstName" : "John",
  "lastName" : "Smith"
}
''';
```

`User user = JsonConvert.deserialize<User>(jsonString);`
