### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by kalaiarasi12** [dart-lang/sdk#43248]
## Version information

- `IDEA AI-193.6911.18.40.6626763`
- `2.10.0-7.2.beta`
- `AI-193.6911.18.40.6626763, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1440x900`

**Comment by bwilkerson** [comment]
I'm going to close this as non-actionable.
