### ISSUE TITLE
new installation of flutter does not create test project

### ISSUE THREAD

**Issue by michaelu123** [dart-lang/sdk#43249]
Just installed flutter/dart on Android Studio and VS Code. Creating a new (test drive) project crashes in both ide's:

```
[flutter2] flutter create --ios-language swift --android-language kotlin .
Waiting for another flutter command to release the startup lock...
Creating project ....
../../third_party/dart/runtime/vm/compiler/frontend/kernel_translation_helper.cc: 2018: error: Unexpected tag 0 (Nothing) in ?, expected expression
version=2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "windows_x64"
```
Nowhere on my computer can I see a directory third_party/dart/runtime/vm/compiler/frontend/ or a file kernel_translation_helper.cc. flutter doctor does not complain.

**Comment by mraleph** [comment]
Please report all Flutter related issue to Flutter SDK issue tracker: http://github.com/flutter/flutter/issues

In this particular case your flutter installation is most likely damaged. Try deleting `flutter/bin/cache` (where `flutter` is the directory containing Flutter SDK and running `flutter doctor`).

**Comment by michaelu123** [comment]
Sorry that I bothered you. The SSD was corrupt.
