### ISSUE TITLE
Export static class constant to JS

### ISSUE THREAD

**Issue by vladimircores** [dart-lang/sdk#43244]
Good day Dart Compiler team,

Could you help me to figure out how to export static const String from Dart class to use in JavaScript? 
Tried a lot of different combination, even exporting with Map, but have no positive results. With function it works, but with Objects and Maps, I'm stuck ... Please help.
```dart
class DataKeys {
  static const String
    LIST = 'DATA_TODO__ALL_LIST',
    COUNT = 'DATA_TODO__NOT_COMPLETED_COUNT',
    FILTER = 'DATA_TODO__FILTER',
    STATE = 'DATA_TODO__STATE'
  ;
}
```
<img width="1112" alt="Screenshot 2020-08-29 at 00 57 14" src="https://user-images.githubusercontent.com/442111/91621337-14ffe380-e993-11ea-8354-c8c2b416628b.png">

**Comment by vladimircores** [comment]
And actually what I need is a way to export Dart classes to JS. Is it possible at all?

**Comment by vladimircores** [comment]
And actually I find one way to pass these constants from Dart to JS, it's not optimal and require more code, but it works:
<img width="960" alt="Screenshot 2020-08-30 at 17 23 16" src="https://user-images.githubusercontent.com/442111/91662920-bc8d2b00-eae5-11ea-80fb-36a94fe445fa.png">
encoding to strings, export strings, and then decode them back and make a mapping.

**Comment by sigmundch** [comment]
Thanks for your question!

Indeed, your solution is similar to what I'd suggest. There is currently no support to export Dart classes or methods automatically. You can however export data and functions explicitly via our JS-interop APIs. 

You don't necessarily have to serialize/deserialize Similar to you suggestion, you can also do:

**a.js**:
```js
window.JsDataKeys = {};
```

**a.dart**:
```dart
@JS()
@anonymous
class JsDataKeys {
  external int set LIST;
  ...
}

@JS('JsDataKeys')
external JsDataKeys get keys;

enum DataKeys {
   LIST,
   ...
}
...
main() {
  keys
    ..LIST = DataKeys.LIST.index
    ..COUNT = DataKeys.COUNT.index
    ..FILTER = DataKeys.FILTER.index
    ..STATE = DataKeys.STATE.index;

  ...
}
```

In some cases, sometimes it makes sense to switch the source-of-truth to generate smaller bindings. For example, define a json map in JS with the enum values, and translate them on the Dart side instead.

Hope this helps! Feel free to follow #35084 if you are interested in the many changes and enhancements we are looking into in JS-interop

**Comment by sigmundch** [comment]
oops, updated the example not to use enum:

```
@JS()
@anonymous
class JsDataKeys {
  external int String LIST;
  ...
}

@JS('JsDataKeys')
external JsDataKeys get keys;

class DataKeys {
   const String LIST = ...;
}
...
main() {
  keys
    ..LIST = DataKeys.LIST
    ..COUNT = DataKeys.COUNT
    ..FILTER = DataKeys.FILTER
    ..STATE = DataKeys.STATE;

  ...
}
```
