### ISSUE TITLE
VM is not using opt-in status to default sound mode with a package in the allow list

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#43243]
The allow list signals that any file within a package (including outside of it's `lib/`) may use the non-nullable experiment. This is working correctly in the CFE - the code is parsed as opted in.

This is not working correctly to choose whether to run with sound null safety or not. The intended behavior is that if the entrypoint library is opted in, then run with sound null safety. This was the behavior before. With the latest dev SDK the actual behavior is that `--enable-experiment=non-nullable` is still required.

**Comment by a-siva** [comment]
I believe this is a CFE issue not a VM issue and is probably a moot point as we are in the process of flipping` --enable-experiment=non-nullable` to be on by default

**Comment by johnniwinther** [comment]
With the flipping of the flag we now also default to sound mode for auxiliary files in allowed packages when explicitly or implicitly using the experiment release version.
