### ISSUE TITLE
No error in analyzer for invalid constant value

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43258]
The following code produces expected errors in VM but no errors in analyzer
```dart

dynamic nonConst;
const int i = 5;
bool bb = true;

main() {
  const bool a1 = (i < 0) && nonConst;
//                           ^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified

  const bool a2 = false && bb;
//                         ^^
// [analyzer] unspecified
// [cfe] unspecified

  const bool a3 = false && i < nonConst;
//                             ^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
}
```

`Dart SDK version: 2.10.0-59.0.dev (dev) (Tue Aug 25 18:05:44 2020 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
This depends on the word ['further'](https://github.com/dart-lang/language/blob/471a98ca0dd5b02d194ffad0dc128065771253a0/specification/dartLangSpec.tex#L6478) in the language specification.

I think it's reasonable to interpret that word as implying that `e1 && e2` is a constant expression _if it is a potentially constant expression and also_ `$e_1$ evaluates to \FALSE` (the other branch becomes: if it is a potentially constant expression and also `$e_1$ evaluates to \TRUE{} and $e_2$ is a constant expression that evaluates to an instance of type \code{bool}`).

So `e1 && e2` is not a constant expression unless `e2` is a potentially constant expression. So we should have the error.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/205662
