### ISSUE TITLE
this is a list bug? mention tag prints

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#43251]
class Piece {
  String pic = '  ';

  Piece({String pic = '  '}) {}
}

class Context {
  var pieces = List<List<Piece>>.filled(12, List<Piece>.filled(18, Piece()));

  void init() {
    for (var i = 0; i < 18; i++) {
      for (var j = 0; j < 12; j++) {
        if (i == 0 || j == 0) {
          this.pieces[j][i].pic = 'KK';
        } else {
          this.pieces[j][i].pic = 'SS';
        }
      }
    }
    // tag: prints SS, but should be KK
    print(this.pieces[0][0].pic);
  }
}

void main() {
  var c = Context();
  c.init();
}

**Comment by lrhn** [comment]
This is working as intended for the code you have written.
All your 12&times;18 slots contain the same instance of `Piece` (and 12 times the same instance of an 18-element list).

You may want to change the creation to:
```dart
var pieces = List<List<Piece>>.generate(12, () => List.generate(18, () => Piece()));
```
or
```
var pieces = [for (var i = 0; i < 12; i++) [for (var i = 0; i < 18; i++) Piece()]];
```
