### ISSUE TITLE
[NNBD] No error in CFE for left hand of ??= operator

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43278]
The following code produces an error in analyzer and no issues in VM
```dart
class C {
  int? x;
}

main() {
  C? c = new C();
  c.x ??= 42;  // Analyzer error - An expression whose value can be 'null' must be null-checked before it can be dereferenced.
}
```
There must be an error in CFE as well

`Dart SDK version: 2.10.0-59.0.dev (dev) (Tue Aug 25 18:05:44 2020 -0700) on "windows_x64"`

**Comment by stefantsov** [comment]
The CL is in progress: https://dart-review.googlesource.com/c/sdk/+/162160.
