### ISSUE TITLE
Feature request: HttpClient should accept existing Socket objects to establish the connection

### ISSUE THREAD

**Issue by zichangg** [dart-lang/sdk#43277]
`HttpClient` is not able to reuse existing `sockets`. It will always use `_SecureSocket` or `_Socket` (dart:io implementation of `SecureSocket`/`Socket`). Self-written `Socket`s are not allowed. Users will have to use `IOOverride` as a workaround.

With this feature, it grants the freedom to users to choose the underlying connection. e.g. Unix domain sockets, which was supported a while ago, can be easily installed  to `HttpClient`.

It also potential boosts the performance if used properly.

**Comment by hacker1024** [comment]
`IOOverride` does not even allow overriding `SecureSocket.startConnect` or `SecureSocket.connect`, so there's no workaround at all to use a custom socket with HTTPS.

**Comment by inst-cicada** [comment]
@zichangg can you please elaborate the problem? The one I am getting is that if you are unable to use existing sockets for eg. you are getting error wile connecting with locally hosted API and getting Socket Exception Error. Then to fix those issue follow the steps given below:

<Make sure you have adb installed in your machine.>

1. Open Android Studio and open your Flutter Project.
2. Start your Android Emulator.
3. Start your API in local server and note the host url along with port. e.g. http://xxx.xxx.xx.x:5000
4. After hosting the API open Command Line and run the following code:
                                `adb reverse tcp:<hosting port here> tcp:<hosting port here>`
    eg. suppose you have hosted your api in http://xxx.xxx.xx.x:5000 then put 5000 in <hosting port> and use 
    http://xxx.xxx.xx.x:5000 in HttpClient to get or post.
5. Go to your dart file and run the code.


It worked for me.
Sorry If I got your problem wrong. I'm new to developing so.
And if I got it right. Cheers.

**Comment by brianquinlan** [comment]
I'm going to mark this as fixed by a0aeed9faad4c793c7679db3b8eed58ab1be6d5c - if that is not sufficient, please reopen.

**Comment by brianquinlan** [comment]
Hi @hacker1024  - if you change the code to *not* use `connectionFactory` does this work? ie

```dart
final client = IOClient(HttpClient()
  ..findProxy = ((_) => 'PROXY username:password@au755.nordvpn.com:89');
await client.read(Uri.parse('https://dart.dev'))
```

If so, could you file another bug to track this issue?

**Comment by hacker1024** [comment]
@brianquinlan It does not. See: #43876.
