### ISSUE TITLE
Failures on Roll dart_style 1.3.7 into the SDK. front_end fasta expected output files incorrect.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#43270]
There are new test failures on [Roll dart_style 1.3.7 into the SDK.](https://dart-review.googlesource.com/c/sdk/+/160981).

The tests
```
pkg/front_end/test/fasta/textual_outline/nnbd/abstract_fields Fail (expected Pass)
pkg/front_end/test/fasta/textual_outline/nnbd/abstract_fields_spec Fail (expected Pass)
pkg/front_end/test/fasta/textual_outline/nnbd/external_fields_spec Fail (expected Pass)
```
are failing on configurations
```
cfe-unittest-asserts-release-linux
```

I cannot make these tests pass by making the changes recommended in the failure logs from the test runs.
With the changes in this patchset, the test front_end/test/fasta/textual_outline/nnbd/external_fields_spec
claims in the results.json that it is failing, but claims in the logs.json that it is passing, even when run locally, so I don't know how to fix the test.

@jensjoha @munificent

**Comment by jensjoha** [comment]
Will be fixed with https://dart-review.googlesource.com/c/sdk/+/161163.

**Comment by jensjoha** [comment]
And then I completely forgot about it :x

it was fixed/landed with https://dart-review.googlesource.com/c/sdk/+/161945.
