### ISSUE TITLE
[CP][stable channel] Fix regression due to Chrome breaking change

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#43287]
**commit(s) to merge**: e33f84d0812a99ff1bafdbf925b24dccef31b85c

**merge instructions**: clean merge

**What is the issue**: Chrome made a breaking change on `MemoryInfo`. This trips DDC, causing it to improperly associate regular objects as instances of `MemoryInfo`, and as a result applications fail in arbitraty ways when performing a dynamic call.

**What is the fix**: `MemoryInfo` is a special type that is not exposed by Chrome, so DDC has special logic to associate its type information on the side. The fix updates the logic to be resilient to this breaking change.

**Why cherrypick**: This will be a very visible regression. The breaking change is currently in Chrome canary, once it gets released, this is likely going to break most Dart web development workflows. We've seen this break simple AngularDart apps, and expect this will affect Flutter Web development as well.

Luckily, production builds with dart2js are not affected, unless they run side-by-side with a DDC app, in which case the fix will also restore dart2js to work properly.

This should be cherry-picked to the current stable channel 2.9, be part of the upcoming beta and stable release. If we have the ability, I'd even consider cherry-picking 2.8, if not we should send an announcement with some mitigation instructions.

**Risk**: low. The change is small (2 lines) and works with both old and new versions of chrome. The code path is covered by all of our unit tests running in chrome browsers already.

**Link to original issue(s)**: https://github.com/dart-lang/sdk/issues/43193

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
Approved in SCRUM 
@athomas @pcsosinski

**Comment by pcsosinski** [comment]
current expectation is that a Flutter hotfix for this specific issue is necessary - we will pick it up if we have a need for a 1.20 hotfix prior to 1.22.

**Comment by sigmundch** [comment]
@pcsosinski - just to be clear, at the scum you mentioned that we only need this for flutter-beta, since this only affects flutter-web development with ddc but wont affect the rest of flutter. Did I misunderstand?

**Comment by pcsosinski** [comment]
ah sorry I've updated that comment to to say 'stable.'  regarding beta, the branch we cut next week will be in beta the week of sept 14 - my understanding was that that timing fits for this issue?

**Comment by pcsosinski** [comment]
updated comment to say that a flutter hotfix is *not* necessary

**Comment by athomas** [comment]
Released in 2.9.3 (091c8559e30b764118e6cae612da4fdf0f6d7b81).
