### ISSUE TITLE
Analysis Server doesn't find enum usage in extension

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#43297]
```dart
enum FooEnum {x}
extension FooEnumExt on FooEnum {}
```
Analysis Server provides reference for `FooEnum` in `extension FooEnumExt on FooEnum` but doesn't provide any results if we ask it to find `FooEnum` usages (`server.search_findElementReferences()`). Also, reference to enum is not updated if we rename the enum using Analysis Server.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by srawlins** [comment]
This has been fixed. Find usages, with the cursor at `FooEnum` in `enum FooEnum {x}` now shows `FooEnum` in `extension on FooEnum {}` as a use.

A rename of the enum also results in a rename of the enum name in the `on` clause.

Tested in IntelliJ and VS Code, with Dart 2.16.
