### ISSUE TITLE
Http header test timing out on bytecode mode

### ISSUE THREAD

**Issue by zichangg** [dart-lang/sdk#43291]
https://github.com/dart-lang/sdk/commit/a6db069971796cf793976c07875ff447ee4a15da introduce the test.

The tests
```
standalone_2/io/http_big_header_test Timeout (expected Pass)
```
are failing on configurations
```
dartkb-interpret-linux-release-x64
```

log: https://dart-ci.appspot.com/log/vm-dartkb-linux-release-x64/dartkb-interpret-linux-release-x64/8627/standalone_2/io/http_big_header_test

@alexmarkov The test is working on the other configs and the cl is pure dart code. Do you think this has anything to do with bytecode?

**Comment by alexmarkov** [comment]
The test might be too slow to run in the interpreter-only mode. I would suggest to approve this failure or skip this test in the interpreter mode (using `$builder_tag == bytecode_interpreter` condition in `tests/standalone_2/standalone_2_kernel.status` file).

Another option is to reduce amount of work performed by the test, e.g. revise number of iterations in the loops such as

https://github.com/dart-lang/sdk/blob/42dfb9d3046fa75d30faf270e05878cbe4557fa3/tests/standalone/io/http_big_header_test.dart#L16
