### ISSUE TITLE
Failures on [ package:dds ] Add IPv6 support; 1.3.2 release

### ISSUE THREAD

**Issue by zichangg** [dart-lang/sdk#43292]
There are new test failures on [[ package:dds ] Add IPv6 support; 1.3.2 release](https://github.com/dart-lang/sdk/commit/23f80fb7fdb231375834d145371cdc2165752433).

The tests
```
pkg/dds/test/sse_smoke_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac
```

Log: https://dart-ci.appspot.com/log/pkg-mac-release/unittest-asserts-release-mac/13725/pkg/dds/test/sse_smoke_test

**Comment by bkonyi** [comment]
Reverted in https://dart-review.googlesource.com/c/sdk/+/161450
