### ISSUE TITLE
Document.registerElement() doesn't work

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43293]
Consider the following code
```dart
import "dart:html";

class Foo extends HtmlElement {
  Foo.created() : super.created()
}

main() {
  var tag = 'x-foo';
  document.registerElement(tag, Foo);
}
```
Output is
```
js_helper.dart:1129 Uncaught TypeError: null: type 'JSNull' is not a subtype of type 'String'
    at Object.wrapException (js_helper.dart:1129)
    at Object._asString (rti.dart:1219)
    at Object.main (html_dart2js.dart:40141)
    at js_helper.dart:2677
    at js_helper.dart:2677
    at dartProgram (js_helper.dart:2677)
    at js_helper.dart:2677
wrapException @ js_helper.dart:1129
_asString @ rti.dart:1219
main @ html_dart2js.dart:40141
(anonymous) @ js_helper.dart:2677
(anonymous) @ js_helper.dart:2677
dartProgram @ js_helper.dart:2677
(anonymous) @ js_helper.dart:2677
```
Is this a bug in dart2js or I'm doing anything wrong?
`Dart SDK version: 2.10.0-59.0.dev (dev) (Tue Aug 25 18:05:44 2020 -0700) on "windows_x64"`

**Comment by sigmundch** [comment]
There happen to be two issues at hand:
 - custom elements has evolved. This the old (v0.5) API that was removed from browsers so it wont work anymore. We need to do some clean up to remove it, though. This code fails in weak mode for this reason.
- In addition, a local variable in this code is inferred as `String`, but should be `String?` (see https://dart-review.googlesource.com/c/sdk/+/164641/1). This code fails in strong mode for this reason. The CL above will make the failures consistent.

**Comment by kevmoo** [comment]
We're going to deprecate this API.
