### ISSUE TITLE
Dart VM embedded in Chrome browser

### ISSUE THREAD

**Issue by vladimircores** [dart-lang/sdk#43305]
As a user of Chrome browser and Dart language programmer I want to ship my web application to Chrome browser without additional steps in transpilation of the language - **I want to have Dart VM embedded in Chrome browser with the same level of access to browser features as JavaScript (engine V8)**, basically interchangeable with JavaScript.

**Comment by a-siva** [comment]
We do not plan on supporting this configuration.
