### ISSUE TITLE
Internal Error: The compiler crashed when compiling this element.

### ISSUE THREAD

**Issue by lyetor** [dart-lang/sdk#43310]
OS: Ubuntu 16.04 

Dart SDK build number: 2.10.0-77.0.dev

The compiler crashed: Crash when compiling dart:ui,
at character offset null:
NoSuchMethodError: The getter 'forSetter' was called on null.
Receiver: null
Tried calling: forSetter
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ClassHierarchyNodeBuilder.build.implement
(package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1530:36)
#2      ClassHierarchyNodeBuilder.build
(package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1605:16)
#3      ClassHierarchyBuilder.build
(package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:599:14)
#4      SourceLoader.buildClassHierarchy
(package:front_end/src/fasta/source/source_loader.dart:1127:46)
#5      KernelTarget.buildOutlines.<anonymous closure>
(package:front_end/src/fasta/kernel/kernel_target.dart:327:14)
<asynchronous suspension>
#6      KernelTarget.buildOutlines.<anonymous closure>
(package:front_end/src/fasta/kernel/kernel_target.dart)
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#8      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:302:12)
#9      generateKernelInternal.<anonymous closure>
(package:front_end/src/kernel_generator_impl.dart:119:28)
<asynchronous suspension>
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#12     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#13     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:192:43)
#14     CompilerContext.runWithOptions.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runWithOptions.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart)
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
#17     new Future.sync (dart:async/future.dart:223:31)
#18     CompilerContext.runInContext.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:19)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _runZoned (dart:async/zone.dart:1630:10)
#22     runZoned (dart:async/zone.dart:1550:10)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#24     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#25     compile (package:front_end/src/api_unstable/dart2js.dart:190:57)
#26     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:183:27)
<asynchronous suspension>
#27     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart)
#28     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#29     KernelLoaderTask.load (package:compiler/src/kernel/loader.dart:60:12)
#30     Compiler.runInternal (package:compiler/src/compiler.dart:247:48)
#31     Compiler.run.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:221:38)
#32     new Future.sync (dart:async/future.dart:223:31)
#33     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:221:20)
#34     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#35     Compiler.run (package:compiler/src/compiler.dart:218:41)
#36     CompilerImpl.run.<anonymous closure>.<anonymous closure>
(package:compiler/src/apiimpl.dart:96:22)
#37     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#42     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ClassHierarchyNodeBuilder.build.implement
(package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1530:36)
#2      ClassHierarchyNodeBuilder.build
(package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1605:16)
#3      ClassHierarchyBuilder.build
(package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:599:14)
#4      SourceLoader.buildClassHierarchy
(package:front_end/src/fasta/source/source_loader.dart:1127:46)
#5      KernelTarget.buildOutlines.<anonymous closure>
(package:front_end/src/fasta/kernel/kernel_target.dart:327:14)
<asynchronous suspension>
#6      KernelTarget.buildOutlines.<anonymous closure>
(package:front_end/src/fasta/kernel/kernel_target.dart)
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#8      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:302:12)
#9      generateKernelInternal.<anonymous closure>
(package:front_end/src/kernel_generator_impl.dart:119:28)
<asynchronous suspension>
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#12     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#13     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:192:43)
#14     CompilerContext.runWithOptions.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runWithOptions.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart)
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
#17     new Future.sync (dart:async/future.dart:223:31)
#18     CompilerContext.runInContext.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:19)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _runZoned (dart:async/zone.dart:1630:10)
#22     runZoned (dart:async/zone.dart:1550:10)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#24     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#25     compile (package:front_end/src/api_unstable/dart2js.dart:190:57)
#26     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:183:27)
<asynchronous suspension>
#27     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart)
#28     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#29     KernelLoaderTask.load (package:compiler/src/kernel/loader.dart:60:12)
#30     Compiler.runInternal (package:compiler/src/compiler.dart:247:48)
#31     Compiler.run.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:221:38)
#32     new Future.sync (dart:async/future.dart:223:31)
#33     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:221:20)
#34     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#35     Compiler.run (package:compiler/src/compiler.dart:218:41)
#36     CompilerImpl.run.<anonymous closure>.<anonymous closure>
(package:compiler/src/apiimpl.dart:96:22)
#37     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#42     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by sigmundch** [comment]
Seems likely like a CFE issue, but hard to say.

@lyetor - could you provide some additional context on how to reproduce this failure locally so we can investigate more easily?

Thanks
