### ISSUE TITLE
snapshot's symbol table should be computed as snapshot is being written

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#43319]
Our current approach to symbol table is somewhat deficient. We are currently trying to pre-drop various links that can pull strings in and then run `Symbols::Compact` - but in the presence of weak links which snapshotter ignores, we potentially can retain symbols in the symbol table which are not going to be referenced from any other object in the snapshot. 

@rmacnak-google has pointed out before that a better approach would be to collect a separate symbol table as we are writing snapshot. 

I have done on the napkin calculation and it seems that for a large Flutter application around 10% of strings (in terms of size) are not reachable from any object in the snapshot except for symbol table itself. 

```
16071 (764199) out of 96760 (8096175) are reachable through symbol table only 
```

If we can drop these strings that would result in a good size saving.

**Comment by rmacnak-google** [comment]
These unused strings are directly visible looking at either the heap snapshot in Observatory or the snapshot's v8-format dump in Graph Explorer: they are the objects dominated by the symbol table. The symbol table should not dominate any objects. In these tools one can also see we have unused types reachable from the canonical type table.
