### ISSUE TITLE
analyzer should warning sub class method if the method have not @override annotation but the method is actually override base class method

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#43328]
like title.

**Comment by lrhn** [comment]
I believe that is what the  [annotate_overrides](https://dart-lang.github.io/linter/lints/annotate_overrides.html) lint does for you.

The language itself does not care about annotations, and using `@override` is not required, but the analyzer/linter can warn you if you choose to require `@override` annotations. You just have to enable the lint.
I believe that would mean adding the following to `analysis_options.yaml`:
```yaml
linter:
  rules:
    - annotate_overrides
```

**Comment by Silentdoer** [comment]
it could be a default analysis behavior?

**Comment by lrhn** [comment]
No. Lints are never on by default. They are for optional coding style choices that are not enforced by the language.

It's perfectly reasonable to write Dart code without using `@override` at all. If you *want* the analyzer to warn you about unintended overrides, then you can opt in to lints *and* start adding `@override`, but you can also choose to do neither.
The `@override` is not part of the language, any more than `@visibleForTesting`.
