### ISSUE TITLE
Type propagation for final fields

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#43334]
I think the type system is too conservative for final fields:

```dart
class Foo {
  final Object object;

  Foo(this.object);

  void bar() {
    if (object is String) {
      print(object.length);  // The getter 'length' isn't defined for the type 'Object'. 
    }
  }
}
```

Similarly for null type promotion:

```dart
class Bar {
  final String? message;

  Bar([this.message]);

  void bar() {
    if (message != null) {
      print(message.length);  // An expression whose value can be 'null' must be null-checked before it can be dereferenced.
    }
  }
}
```

Having to copy to a local variable before testing and accessing is cumbersome.

```
$ dart --version
Dart SDK version: 2.10.0-92.0.dev (dev) (Wed Sep 2 22:28:32 2020 -0700) on "macos_x64"
```

**Comment by mraleph** [comment]
Final fields can still be overriden by a getter making any sort of static promotion without checks unsound. 

```dart
class Bar extends Foo {
  @override
  Object get object => 
    Random.nextBool() ? 'today I am a string, some day I am ' : 42 ;
}
```

There are multiple threads going on about potential ways to tackle this on the language repo: 

- https://github.com/dart-lang/language/issues/1187
- https://github.com/dart-lang/language/issues/1188
- https://github.com/dart-lang/language/issues/1191
- https://github.com/dart-lang/language/issues/1201
