### ISSUE TITLE
Incorrect ambiguous_extension_member_access error

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#43339]
* Dart SDK version: 2.9.2
* MacOS

I'm not sure if this is the correct repository, but the following snippet:
```Dart
library minimal;

import './minimal.dart';

extension Something on String {
  bool operator < (String other) => true;
}

void main() => print('a' < 'b');
```
produces the following error in IntelliJ,  ```error: A member named '<' is defined in extensions 'Something' and 'Something' and neither is more specific. (ambiguous_extension_member_access at [something] lib/minimal.dart:9)```. It however, runs perfectly fine.

**Comment by srawlins** [comment]
I think someone else reported this recently, and it has been fixed at HEAD.
