### ISSUE TITLE
[analyzer 0.40.2][BUG]Can't work for localization files

### ISSUE THREAD

**Issue by shinriyo** [dart-lang/sdk#43344]
I want to ignore for localization files.

`analysis_options.yaml`

```
analyzer:
  exclude:
    - "lib/generated/l10n.dart"
    - "lib/intl/*.dart”
```

but not work

**Comment by srawlins** [comment]
Sorry for the (year long!) delay, but are you still encountering this issue? Can you explain what is not working? What do you expect to happen and what is actually happening?

**Comment by srawlins** [comment]
Please re-open if you see this problem again.
