### ISSUE TITLE
wrong subtraction

### ISSUE THREAD

**Issue by apangaribuan** [dart-lang/sdk#43340]
void main() {
  print(8.2 - 1);
  print(8.2 - 1.0);
  print(8.3 - 1);
  print(8.3 - 1.0);
}

It will print:
7.199999999999999
7.199999999999999
7.300000000000001
7.300000000000001

tested on dart 2.9.2

**Comment by leecommamichael** [comment]
https://floating-point-gui.de/

**Comment by lrhn** [comment]
This is correct behavior. You get the same results in JavaScript or Java, it's just how floating point numbers work.

**Comment by apangaribuan** [comment]
@lrhn sorry if its same as JavaScript and Java, but why this code below works?

`void main() {
  print(7.2 - 1);
  print(7.2 - 1.0);
  print(7.3 - 1);
  print(7.3 - 1.0);
}`

It will print:
6.2
6.2
6.3
6.3

And I've tested it on golang and c#, and it works. Can we solve this?

**Comment by leecommamichael** [comment]
> @lrhn sorry if its same as JavaScript and Java, but why this code below works?
> 
> `void main() { print(7.2 - 1); print(7.2 - 1.0); print(7.3 - 1); print(7.3 - 1.0); }`
> 
> It will print:
> 6.2
> 6.2
> 6.3
> 6.3
> 
> And I've tested it on golang and c#, and it works. Can we solve this?

Printing characters to a terminal is not simple and many printing functions hide a lot of work to make your life easier. Meditate on this:
```go
package main

import "fmt"

func main() {
  result := 7.2 - 1
  
  println(result)
  fmt.Println(result)
}
```
