### ISSUE TITLE
Best way to work with list of bytes: Uint8List, BytesBuilder or something else?

### ISSUE THREAD

**Issue by giacomok** [dart-lang/sdk#43341]
Hi,  
I would like to know what is the best way to work with list of bytes.

I get a code (wrote by someone else) that reads from socket and uses `Uint8List`, but I suspect its a slow code.  How can I edit it?  
I saw `BytesBuilder`, but I need to search in the list and the BytesBuilder does not let you to perform research.  

If you need I can paste the code (its a single small file) right here.

**Comment by lrhn** [comment]
This is a rather vague question. In general, using `Uint8List` is not necessarily slow, so how to make the code faster depends very much on why the code is slow (if it is).
If you are reading data from a socket, then the overhead of communication is likely to dwarf anything you do with the bytes afterwards.

For something which can contain bytes , be searched, and grow, the `package:typed_data` has [`Uint8Buffer`](https://pub.dev/documentation/typed_data/latest/typed_data.typed_buffers/Uint8Buffer-class.html). That won't necessarily be any faster than working directly with `Uint8List` - probably the opposite - but it can be more convenient.
