### ISSUE TITLE
CFE fails to account for null when checking whether a switch statement as exhaustive

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43348]
The following program is accepted by the CFE:
```dart
enum A {
  b, c
}

int f(A? a) {
  switch (a) {
    case A.b:
    case A.c:
    return 0;
  }
}

main() {
  f(A.b);
}
```
It should be rejected, since the `switch` statement is non-exhaustive (it doesn't handle `null`), and therefore `null` might be returned from `f`, in violation of its static type.  This is a soundness issue.

**Comment by stereotype441** [comment]
See also https://github.com/dart-lang/language/issues/1143#issuecomment-688398869

**Comment by franklinyow** [comment]
@leafpetersen Can you triage this?  Thx
