### ISSUE TITLE
Uri.https doesn't parse special characters

### ISSUE THREAD

**Issue by Zazo032** [dart-lang/sdk#43355]
We can't parse a `Map<String, String>` of `queryParams` in which one of the keys has a value with special characters: `:`, `,`.

https://api.dart.dev/stable/2.9.2/dart-core/Uri/Uri.https.html

## Sample code

```dart
void main() {
  final Uri uri = Uri.https(
    'test.com',
    'sample',
    <String, String>{
      'param': 'ABC:0,BCD:1,CDE:2',
    },
  );
  
  print(uri);
}
```
Output:
```
https://test.com/sample?param=ABC%3A0%2CBCD%3A1%2CCDE%3A2
```

This happens with both stable (`2.9.2`) and latest Flutter master roll versions:
```
Dart SDK version: 2.10.0-86.0.dev (dev) (Tue Sep 1 21:44:16 2020 -0700) on "windows_x64"
```

**Comment by lrhn** [comment]
That looks like the correct result. The query parameters are encoded using [URL-encoding](https://en.wikipedia.org/wiki/Query_string#URL_encoding), which means that both `:` and `,` are replaced with numeric character escapes.

If you parse the result back as a `Uri`, you get the original string from the `Uri.queryParameters`:
```dart
main() {
  var uri = Uri.parse("https://test.com/sample?param=ABC%3A0%2CBCD%3A1%2CCDE%3A2");
  print(uri.queryParameters["param"]); // prints "ABC:0,BCD:1,CDE:2"
}
```

What did you expecting to be different?

**Comment by Zazo032** [comment]
Hi @lrhn, we managed to solved this on our side. Sorry for the inconvenience.
