### ISSUE TITLE
Failures on [ VM / Service ] Roll back major revision, update to 3.39...[vm/compiler] Add type testing stubs to allow TypeParameter types to be called indirectly

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#43369]
There are new test failures on [[ VM / Service ] Roll back major revision, update to 3.39...[vm/compiler] Add type testing stubs to allow TypeParameter types to be called indirectly](https://github.com/dart-lang/sdk/compare/f6906f856ebb96274b53367f3abe7c6adb778d6e~...e3fcee331dbd5aa08474959ce7e2b7106b479904).

The tests
```
vm/cc/TTS_TypeParameter Crash (expected Pass)
vm/cc/TTS_TypeParameter Crash (expected Pass)
```
are failing on configurations
```
dartkb-interpret-linux-release-simarm64
dartkb-interpret-linux-release-x64
dartkb-mixed-linux-release-simarm64
dartkb-mixed-linux-release-x64
```

**Comment by bkonyi** [comment]
This is almost certainly not related to e3fcee331dbd5aa08474959ce7e2b7106b479904.

**Comment by mkustermann** [comment]
The newly added `vm/cc/TTS_TypeParameter` test - which I've added - which seemingly fails in bytecode/interpreter mode. Guess there's some minor difference with bytecode - possibly due to more lazy behavior.
