### ISSUE TITLE
Dart toDisplayString should be defensive against seeing non-legacy types in legacy mode

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#43360]
We've seen a few issues where we print NNBD types in legacy mode. For instance https://github.com/dart-lang/sdk/issues/43029

In general, non-legacy types should never be available to legacy libraries.

Therefore, my proposal is that whenever we call toDisplayString without nullability, that we:

1. assert that every type in the tree is a legacy type.
2. if any type is not a legacy type, override with nullability to true.

(Note: this should not be a recursive process. The root of the toDisplayString() call should perform step 1 and 2, and the leaves/branches should not).

This way, we will never accidentally print "int" instead of "int?" (which is probably something we _never_ want to do), and reveal bugs in legacification (print "List*<int>" instead of "List<int>" if that slips into a legacy library), and remain somewhat consistent in the face of bugs (print "List*<int?>" in an NNBD library rather than "List<int?>").

**Comment by scheglov** [comment]
If we have a bug that we don't call `DartType.toDisplayString()` without the required `withNullability`, or provide incorrect value of `withNullability`, we should fix these bugs. We should not try to dig them deeper.

**Comment by scheglov** [comment]
Sorry, I realize that pure criticism is not helpful.

I suspect that we do pass `withNullability` because it is required now.
We probably should audit all places from where it is provided, and check that we provide right values.
I suspect that we have many places where we decided to pass `false` for some time, and need to get back to them.

**Comment by MichaelRFairhurst** [comment]
Yeah, I agree Konstantin that we should do that. I think this is about making it defensive against bugs, rather than assuming we can eliminate all of them in an audit.

**Comment by srawlins** [comment]
I'm going to close this as stale; we're not going to put effort into legacy types.
