### ISSUE TITLE
Symbol should support a field to get String name

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#43375]
like title

**Comment by mraleph** [comment]
The whole idea behind symbols is that they do not have to keep their original string names around - adding such a field would defeat this idea.

**Comment by Silentdoer** [comment]
please following code:
`
import 'dart:async';
import 'dart:mirrors';

/**
 * like java's reflectASM
 */
abstract class MethodAccess {
  static Future<MethodAccess> get(ClassMirror classMirror) async {
    var methods = classMirror.declarations.values.where((element) => element is MethodMirror && element.isRegularMethod);

    // FIXME
    var methodMirror = methods.toList()[0] as MethodMirror;
    var named = methodMirror.parameters.where((element) => element.isNamed).toList();
    // TODO e.simpleName.name
    var namedStr = named.map((e) => '${_parseSymbolName(e.simpleName)}: namedArguments[${e.simpleName}]').join(", ");
    var nonNamed = methodMirror.parameters.where((element) => !element.isNamed).toList();
    // args[0], args[1]
    var nonNamedStr = nonNamed.asMap().keys.map((e) => 'args[${e}]').join(", ");
    var code = '''
library generated;
import '../lib/reflect_asm.dart';

class ${_parseSymbolName(classMirror.simpleName)}MethodAccess extends MethodAccess {

  @override
  dynamic invoke(dynamic obj, Symbol methodName, List<dynamic> args, Map<Symbol, dynamic> namedArguments) {
    switch (methodName) {
      // FIXME use template to archive for
      case ${methodMirror.simpleName}:
        return obj.${_parseSymbolName(methodMirror.simpleName)}(${nonNamedStr}, ${namedStr});
        break;
      default:
        throw 'no such method..';
    }
  }
}''';
    ...
  }

  /**
   * TODO, if Symbol has not name field, we must use this code fetch name
   */
  static String _parseSymbolName(Symbol symbol) {
    return symbol.toString().replaceAll('Symbol', "").replaceAll("\"", "").replaceAll("(", "").replaceAll(")", "");
  }
  
  dynamic invoke(dynamic obj, Symbol methodName, List<dynamic> args, Map<Symbol, dynamic> namedArguments);
}
`

**Comment by Silentdoer** [comment]
if Symbol can support name field, we can get name without _parseSymbolName(...)

**Comment by Silentdoer** [comment]
@mraleph @lrhn

**Comment by mraleph** [comment]
I am not entirely sure what you are trying to achieve here but the code above is not compatible with AOT compilation (`dart:mirrors` is not really supported by our AOT backends) and in general we see `dart:mirrors` library almost as deprecated/unsupported feature of the language which even might be removed in the future.

Lets go to the beginning: what are you trying to achieve? Are you using `dart:mirrors` for code generation?

**Comment by Silentdoer** [comment]
yes, i want use dart:mirrors to generate code

**Comment by lrhn** [comment]
If you have `dart:mirrors` available, then you can get the name of a symbol using `MirrorSystem.getName(symbol)`.
You can even introduce an extension for that:
```dart
extension SymbolName on Symbol { String get name => MirrorSystem.getName(this); }
```

**Comment by Silentdoer** [comment]
Oh, thank you, this is what i want
