### ISSUE TITLE
remove "Warning: This VM has been configured to produce stack traces that violate the Dart standard"

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#43388]
Language team has confirmed in https://github.com/dart-lang/language/issues/1212 that stack trace format is an implementation detail so obfuscation and/or changes to stack trace format (e.g. non symbolic stack traces) do not violate Dart language specification. 

We should remove/replace these warnings with something less confusing.

/cc @mkustermann

**Comment by mkustermann** [comment]
I think we should do the following:

* [ ] Add a `dart symbolize` command (analogous to `flutter symbolize`) - should be quite simple using `package:native_stacktraces`
* [ ] Possibly finish `dart compile aot-snapshot` / `dart compile exe` with support for dwarf stack traces
* [ ] Possibly update dart.dev with a page similar to [flutter.dev/docs/deployment/obfuscate](https://flutter.dev/docs/deployment/obfuscate)
* [ ] change the description of the error message to point to either `flutter symbolize` / `dart symbolize` and/or to the two flutter.dev/dart.dev articles

@sstrickl Could you look into that?
