### ISSUE TITLE
`StreamIterator.current` docs need updating for null safety

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#43380]
Like `Iterator.current`, the interface of `StreamIterator.current` changes for null safety: it can no longer return `null`.

This change appears to have been made, but the docs are out of date :)

```
   * Is `null` before the first call to [moveNext] and after a call to
   * `moveNext` completes with a `false` result or an error.
```
https://api.dart.dev/stable/2.9.3/dart-async/StreamIterator/current.html

Thanks.

**Comment by munificent** [comment]
CL out: https://dart-review.googlesource.com/c/sdk/+/170142
