### ISSUE TITLE
Analyzer treats required named parameters in superclasses as non-optional from legacy libraries

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#43397]
Given this legacy library:

```dart
// @dart=2.8
import 'null_safe.dart';

class Legacy extends NullSafe {}

main() {
  Legacy();
}
```

// And this null-safe one:

```dart
class NullSafe {
  NullSafe({required String s});
}
```

I would expect this code to be OK. The implicit `super()` call in Legacy to call `NullSafe()` should be allowed because NullSafe's required named parameter [should be treated as optional from the context of a legacy library](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#legacy-libraries).

Instead, I get:

```
Analyzing /Users/rnystrom/Documents/legacy.dart...
  error • The superclass 'NullSafe' doesn't have a zero argument constructor. • /Users/rnystrom/Documents/legacy.dart:4:7 • no_default_super_constructor
1 error found.
```

**Comment by nshahan** [comment]
And a reference to required parameters being optional in the definition of `LEGACY_SUBTYPE(S, T)` https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#subtyping.

**Comment by leafpetersen** [comment]
@munificent we evidently don't have a test for this, any chance you could add one?

**Comment by munificent** [comment]
How did I know you were going to say that? :) @scheglov, would you like me to write a test for this or will you in the process of fixing it? I won't get to it until Monday, but I'm happy to then.

**Comment by scheglov** [comment]
This should fix the issue in the analyzer. 

https://dart-review.googlesource.com/c/sdk/+/162584

**Comment by munificent** [comment]
Language test: https://dart-review.googlesource.com/c/sdk/+/163740
