### ISSUE TITLE
[CP][stable channel] Spurious spurious analysis errors when using analysis server's LSP mode

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43394]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/afc2778802422204f48b7918962dbd74bc1a348e

**merge instructions**: clean merge

**What is the issue**: Navigating source code from VS Code, when using the LSP mode, will create new, unintentional analysis roots; users will see hundreds of spurious analysis errors. There's no user workaround for this.

**What is the fix**: Avoid creating these unintentional analysis roots in the LSP implementation in the analysis server.

**Why cherrypick**: This makes the LSP mode in VS Code unusable. We have a few users on this mode now, but want to make it the default for VS Code users in the next month or two. If we had a stable coming up in a month or two, we wouldn't need to cherry pick. With a new stable ~5 months out, we definitely do.

**Risk**: Low risk for patching; this is a 1 line change in the analysis server.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/43393

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by devoncarew** [comment]
Note that this cherry pick is intended for the 2.10 stable branch.

**Comment by devoncarew** [comment]
From checking, this did not make the stable branch point.

**Comment by franklinyow** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in 52130c19ca593b185ea9cf72b26b1d02455551ef (2.10.0-110.3.beta).

**Comment by DanTup** [comment]
Thanks (and sorry for the added hassle)! 🙂
