### ISSUE TITLE
Why the Type Declaration String is starts with Capital when double is with small?

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [dart-lang/sdk#43396]
For the variable declaration, Why dart having different case types between declarations.
Ex.
**S**tring name;
**d**ouble price;

Why this difference ?
Any reason behind this?

**Comment by lrhn** [comment]
Familiarity.

Dart was intended to be familiar to users of Java, where `int` and `double` were lower-case, but `String` was upper-case.

**Comment by shankarThiyagaraajan** [comment]
Interesting, thanks for the info.
