### ISSUE TITLE
How to pass String list from Dart to C using FFI

### ISSUE THREAD

**Issue by ganeshrvel** [dart-lang/sdk#43403]
I am looking way to pass a list of array from Dart to C using FFI. 

For passing strings I do something like this. How  
 
```dart
  final _value = Utf8.toUtf8("abcd");
  final _ptr = _value.cast<Int8>();
  
  _nativeLib.doWork(_ptr);

  free(_ptr)
```

How to I pass a list of Strings from Dart to native library using FFI?

cc @dcharkes

**Comment by dcharkes** [comment]
Hey @ganeshrvel,

Did you not already ask that question before?

> > ```c
> > struct MyStruct {
> >   char** some_string_array;
> >   int some_int;
> > };
> > ```
> 
> For `...**` one uses `Pointer<Pointer<...>>`:
> 
> ```dart
> class MyStruct extends Struct {
>   Pointer<Pointer<Utf8>> some_string_array;
> 
>   @Int32()
>   int some_int;
> }
> ```
> 
> (`ffigen` generates a `Pointer<Pointer<Int8>>` so you have to Utf8 encode/decode manually. See https://github.com/dart-lang/ffi/blob/master/lib/src/utf8.dart on how to do that.)

_Originally posted by @dcharkes in https://github.com/dart-lang/sdk/issues/43011#issuecomment-671852985_

Is there anything besides the `Pointer<Pointer<...>>` part that you would need?

**Comment by ganeshrvel** [comment]
@dcharkes that question was about passing a list of strings from C to Dart, which I was able to do it.

This time I am trying to figure out a way to send a list of strings from Dart to C.

Something like this:

Dart side
```dart
final _list = ['abc', 'xyz'];

 _nativeLib.doWork(_list);
```

**Comment by ganeshrvel** [comment]
Right now, I am attempting something like this:

Dart side:
```dart
    final list1 = 'abc'.codeUnits;
    final list2 = 'xyz'.codeUnits;
    final ptr = allocate<Int8>(count: list1.length + list2.length);
    final pointerList = ptr.asTypedList(list1.length + list2.length);
    pointerList.setAll(0, [...list1, ...list2]);

   _nativeLib.doWork(port, ptr);
```

```c
for (int i = 0; i < size; i++){
    printf("\n%d", ptr[i]);
}
```

Is this the right way?

**Comment by dcharkes** [comment]
I would do something like this.

```dart
DynamicLibrary dylib;

final doWork = dylib.lookupFunction<Int32 Function(Pointer<Pointer<Utf8>>),
    int Function(Pointer<Pointer<Utf8>>)>("SumManyIntsOdd");

void test() {
  final myStrings = ['asdf', 'fsda'];
  final List<Pointer<Utf8>> myPointers = myStrings.map(Utf8.toUtf8);
  final Pointer<Pointer<Utf8>> pointerPointer =
      allocate(count: myStrings.length);
  for (int i = 0; i < myStrings.length; i++) {
    pointerPointer[i] = myPointers[i];
  }
  final result = doWork(pointerPointer);
  free(pointerPointer);
  myPointers.forEach(free);
  print(result);
}
```

**Comment by ganeshrvel** [comment]
And in the C side should the parameter be **char to accept the pointer?

C:
```c
func doWork(port int64, stringPtr **C.char) {
   //do something
}
```


Interestingly FFIGEN generates `ffi.Pointer<ffi.Pointer<ffi.Int8>>` and it isn't compatible with `Pointer<Pointer<Utf8>> pointerPointer`

FFIGEN:
```dart
  void doWork(
    int port,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> stringPtr,
    int recursive,
  ) {
    _doWork ??=
        _dylib.lookupFunction<_c_doWork, _dart_doWork>('doWork');
    return _doWork(
      stringPtr,
    );
  }

```

Any suggestion?

**Comment by ganeshrvel** [comment]
I got it working by passing struct instead of UTF pointer.

Dart side
```dart
class StringList extends Struct {
  Pointer<Pointer<Utf8>> list;

  @Int64()
  int size;

  Pointer<StringList> fromList(List<String> arr) {
    final utfPtrs = arr.map(Utf8.toUtf8).toList();

    // ignore: omit_local_variable_types
    final Pointer<Pointer<Utf8>> list = allocate(count: arr.length);

    for (var i = 0; i < arr.length; i++) {
      list[i] = utfPtrs[i];
    }

    final pStrList = allocate<StringList>().ref;
    pStrList.list = list;
    pStrList.size = arr.length;

    return pStrList.addressOf;
  }
}

```

```dart
    final arr = ['asdf', 'fsda', 'abcdefg'];
    final pStrList = allocate<StringList>().ref;
    final listPtr = pStrList.fromList(arr);

    final result = doWork(port, listPtr.address);
```

C side
```C
     typedef struct StrList{
		char **list;
		int64_t size;
    }StrList;

    func doWork(int64_t port, int64_t listPtrAddr) {
         StrList *pPattern = (struct StrList *) listPtrAddr;

	 for (int i = 0; i < pPattern->size; i++){
	       printf("\n%s", pPattern->list[i]);
	 }
    }
```

**Comment by mkustermann** [comment]
@ganeshrvel It seems like you have solved your problem. You could also avoid the struct by letting making the array by larger by one entry and add a `nullptr` entry to the end (which signals end of array). 

Closing this issue since there's nothing actionable for us to do.

For FFI related questions I can recommend posting them on our mailing list `dart-ffi@googlegroups.com`, the issue tracker is more suited for feature requests or bug reports.

**Comment by listepo** [comment]
@dcharkes how to convert from `ffi.Pointer<ffi.Pointer<ffi.Int8>>` into `List<String>`? is there any documentation with these examples?

**Comment by ganeshrvel** [comment]
@listepo is this what you are looking for: [https://github.com/dart-lang/sdk/issues/43011](https://github.com/dart-lang/sdk/issues/43011)?

**Comment by ganeshrvel** [comment]
@listepo is this what you are looking for: [https://github.com/dart-lang/sdk/issues/43011](https://github.com/dart-lang/sdk/issues/43011)?

**Comment by listepo** [comment]
@ganeshrvel in my case, the function returns an array of strings: 
```dart
  ffi.Pointer<ffi.Pointer<ffi.Int8>> PQsslAttributeNames(
    ffi.Pointer<pg_conn> conn,
  ) {
    _PQsslAttributeNames ??= _dylib.lookupFunction<_c_PQsslAttributeNames,
        _dart_PQsslAttributeNames>('PQsslAttributeNames');
    return _PQsslAttributeNames(
      conn,
    );
  }
```

**Comment by jorgegaticav** [comment]
> @dcharkes how to convert from `ffi.Pointer<ffi.Pointer<ffi.Int8>>` into `List<String>`? is there any documentation with these examples?

Could you solve this?

**Comment by dcharkes** [comment]
```dart
import 'dart:ffi';

import 'package:ffi/ffi.dart';

Iterable<String> toStringList(Pointer<Pointer<Utf8>> charPointerPointer) sync* {
  int index = 0;
  while (true) {
    final charPointer = charPointerPointer[index];
    if (charPointer == nullptr) {
      break;
    }
    yield charPointer.toDartString();
    index++;
  }
}
```

**Comment by jorgegaticav** [comment]
> ```dart
> import 'dart:ffi';
> 
> import 'package:ffi/ffi.dart';
> 
> Iterable<String> toStringList(Pointer<Pointer<Utf8>> charPointerPointer) sync* {
>   int index = 0;
>   while (true) {
>     final charPointer = charPointerPointer[index];
>     if (charPointer == nullptr) {
>       break;
>     }
>     yield charPointer.toDartString();
>     index++;
>   }
> }
> ```

Thank you very much! It works like a charm!
