### ISSUE TITLE
[CP][stable channel] fix dart2js unsoundness for `is Foo?`

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#43413]
**commit(s) to merge**: 8d68480746dbb7878bdc6e3926d0324760af6c5f

**merge instructions**: clean merge on current origin/beta, it is already included in origin/dev.

_Note: this is a request to merge for the 2.10 stable release, which is about to be created._

**What is the issue**: dart2js generated invalid code on programs using `is Foo?`. This regression was visible to flutter users.

**What is the fix**: The bug was an unsoundness in the implementation of dart2js global inference, where we incorrectly promoted `x` to be non null when testing `x is Foo?`, this was because in legacy semantics, `null is Foo` was practically false always. The fix was to properly model the semantics in our global analysis.

**Why cherrypick**: Highly visible regression, the generated code is invalid, likely affects lots of users once the null-safe implementation of `dart:ui` ships (even with null-safety disabled). This issue has not been triggered from the dart-sdk library because the affected feature is not in use.

**Risk**: medium-low - the change is pretty localized, but the CL is medium size. We feel OK with the risk level because:
* the change reuses logic that was used in later parts of the optimizer, so most code is not new
* the change has been rolled to all internal customers with no visible effect.

**Link to original issue(s)**: https://github.com/dart-lang/sdk/issues/43366

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
Marked approved

**Comment by athomas** [comment]
Merged to beta in 52130c19ca593b185ea9cf72b26b1d02455551ef (2.10.0-110.3.beta).
