### ISSUE TITLE
Migration preview should have a favicon

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43438]
This would make it easier for users to find the tool in a sea of tabs.

Probably it should be a dart logo, or some variation of it.

**Comment by natebosch** [comment]
In case it helps, here is an easy to use Dart icon if you are OK with the default.

https://github.com/dart-lang/webdev/blob/bea35d067bff5444b9156f2a192e9ee5d09e23a4/webdev/lib/src/serve/handlers/favicon_handler.dart#L24-L41

**Comment by johnpryan** [comment]
Submitted a quick fix here: https://dart-review.googlesource.com/c/sdk/+/163500/
