### ISSUE TITLE
Analyzer doens't warn about not implemented interfaces.

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#43444]
Consider this code:

```dart
void main() async {
  var b = Base();
  print('${Base.myValue}'); // ERROR HERE!
}

class Base implements MyInterface {
  static String myOtherValue = '2';
}

class MyInterface {
    static int myValue = 1;
}
```

`Base` declares it implements `MyInterface`, but it doesn't and there are no warnings whatsoever about it. I get an error if I try to use it as `MyInterface` though, but I expected the compiler to say "hey, you declared you are implementing MyInterface, but you didn't".

This probably also blocks my IDE from having the ability to generate a nice "implement missing implementations" button or something.

Is this intended behavior? Are there any reasons behind it?

**Comment by lrhn** [comment]
This is working as intended.

Static members are not part of interfaces in Dart, same as other similar languages like Java and C#.
Unlike Java, Dart also doesn't allow access to superclass static members through subclass types.

You only inherit instance members, and since `MyInterface` declares no instance members, `Base` is perfectly implementing `MyInterface`.

**Comment by feinstein** [comment]
I see... maybe you could help me with an idea then?

I am using `built_value`'s serializers, so my class looks like this:

```dart
abstract class Trip implements Built<Trip, TripBuilder> {
  static Serializer<Trip> get serializer => _$tripSerializer;
....
}
```

I wanted to create an interface `Serializable`, so classes that implement `Serializable` are known to have a `serializer` getter, like `Trip` does.

This way I could abstract a bunch of value objects into a list of `Serializable` and serialize them all, create a Repository of `Serializable`s and etc. But right now I am dealing with lots of boilerplate, having to call each class by it's type. 

Thanks in advance  @lrhn :)
