### ISSUE TITLE
"ignore_for_file: argument_type_not_assignable" is not working anymore in Dart 2.9

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#43451]
With the declaration of `ignore_for_file: argument_type_not_assignable` in Dart 2.9 version, the dart analyzer still hints the error about `The argument type 'dynamic' can't be assigned to the parameter type X`.
But the same code works well in Dart 2.8 version.

**Comment by bwilkerson** [comment]
@srawlins @devoncarew

**Comment by srawlins** [comment]
Sorry, I've meant to put this in the release notes. Since `argument_type_not_assignable` is an error, it is no longer supported to ignore.

**Comment by Qubits-01** [comment]
argument_type_not_assignable is giving me false error.

Refer to the image below.
![image](https://user-images.githubusercontent.com/50437107/107846059-acf76980-6e1b-11eb-8e0d-e47db9a4669a.png)

I'm passing an argument with type 'void Function(bool)'
Dart's type inference can not recognize it properly.
![image](https://user-images.githubusercontent.com/50437107/107846022-538f3a80-6e1b-11eb-93c0-85e2daf460a0.png)

Are there any workaround/s for this (aside from refactoring the code)?
Thank you.

P.S. I tried running the flutter app (with that false alarm error) and it works properly.
