### ISSUE TITLE
[CP][Beta Channel] Can't recover from being offline [iOS only]

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#43473]
**commit(s) to merge**: https://dart.googlesource.com/sdk/+/433fcd09d91677ec9a747506e2095f7c708a0672

**merge instructions**: clean merge

**What is the issue**:  A new Flutter roll looks to be causing an uncaught socket exception when offline, which prevents resuming when wifi reconnects. This doesn't occur in the immediate preceding Flutter version.

**What is the fix**: Investigation by change bisection revealed that the regression was caused because of https://dart-review.googlesource.com/q/commit:d7483c330c6d6eddced5d59b2ac2d1fd08352321

**Why cherrypick**: A similar problem could be encountered by other apps on iOS.

**Risk**: Low risk for patching this as it is a revert of a change.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
@a-siva Do we have a link to the original flutter issue?  
FYI @pcsosinski

**Comment by a-siva** [comment]
> @a-siva Do we have a link to the original flutter issue?
The original issue is in the CL that was reverted but here it is again https://github.com/flutter/flutter/issues/15838

**Comment by athomas** [comment]
Approved in scrum.

**Comment by athomas** [comment]
Merged to beta in 4215dca724fb80de592f51a6cdba51e7638d1723 (2.10.0-110.5.beta).
