### ISSUE TITLE
dart2native produces non-functional (crashing) binaries on Apple Silicon / DTK

### ISSUE THREAD

**Issue by alexmarkley** [dart-lang/sdk#43477]
This may be related to my feature request for dart2native to generate (actually) native binaries on this machine: https://github.com/dart-lang/sdk/issues/43476

**Observed Result**
Generated dart2native binaries crash instead of running successfully.

```
DTK:darttest alex$ dart hello.dart
Hello, World!
DTK:darttest alex$ dart2native hello.dart
Generated: /REDACTED/darttest/hello.exe
DTK:darttest alex$ ./hello.exe 

===== CRASH =====
si_signo=Bus error: 10(10), si_code=1, si_addr=0x10d2a1000
Abort trap
DTK:darttest alex$ 
```

**Expected Result**
Generated binaries should run successfully, even if they require Rosetta2.

**Environment**
```
DTK:darttest alex$ uname -a
Darwin DTK.mylocal 20.1.0 Darwin Kernel Version 20.1.0: Fri Aug 28 20:45:29 PDT 2020; root:xnu-7195.40.65.0.2~61/RELEASE_ARM64_T8020 arm64
DTK:darttest alex$
```

```
DTK:darttest alex$ dart --version
Dart SDK version: 2.10.0-136.0.dev (dev) (Wed Sep 16 13:30:26 2020 -0700) on "macos_x64"
DTK:darttest alex$ 
```

I installed dart via flutter master branch, which probably means my dart is old, and it almost certainly downloaded dart built for the wrong architecture. Would love clarification on the "correct" way to set up dart (and I guess Flutter also) for this environment.

**Comment by mit-mit** [comment]
cc @a-siva

**Comment by mkustermann** [comment]
Let's merge this into https://github.com/dart-lang/sdk/issues/42774.
