### ISSUE TITLE
dart2native produces a Mach-O x86_64 binary even on Apple Silicon / DTK

### ISSUE THREAD

**Issue by alexmarkley** [dart-lang/sdk#43476]
This is probably a feature request, but I'm going to open it here anyway because I didn't see mention of it elsewhere.

**Observed Result**
When running `dart2native` on apple silicon, the produced binary is an x86_64 binary:

```
DTK:darttest alex$ dart2native hello.dart
Generated: /REDACTED/darttest/hello.exe
DTK:darttest alex$ file hello.exe
hello.exe: Mach-O 64-bit executable x86_64
DTK:darttest alex$ lipo hello.exe -detailed_info
input file hello.exe is not a fat file
Non-fat file: hello.exe is architecture: x86_64
DTK:darttest alex$ 
```

**Expected Result**
I would like to be able to generate native binaries for my machine. (Universal binaries would be even better.)

**Environment**
```
DTK:darttest alex$ uname -a
Darwin DTK.mylocal 20.1.0 Darwin Kernel Version 20.1.0: Fri Aug 28 20:45:29 PDT 2020; root:xnu-7195.40.65.0.2~61/RELEASE_ARM64_T8020 arm64
DTK:darttest alex$
```

```
DTK:darttest alex$ dart --version
Dart SDK version: 2.10.0-136.0.dev (dev) (Wed Sep 16 13:30:26 2020 -0700) on "macos_x64"
DTK:darttest alex$ 
```

I installed dart via flutter master branch, which probably means my dart is old, and it almost certainly downloaded dart built for the wrong architecture. Would love clarification on the "correct" way to set up dart (and I guess Flutter also) for this environment.

**Comment by mit-mit** [comment]
cc @a-siva

**Comment by mkustermann** [comment]
I think we can merge this into https://github.com/dart-lang/sdk/issues/42774
