### ISSUE TITLE
Default type behind a nullable `?`

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#43472]
@johnniwinther @eernstg 

There are two failing tests from the recent co19 roll on all backends.
```
co19/Language/Generics/typedef_A05_t04
co19/Language/Generics/typedef_A05_t05
```
I'm not sure if the test or the CFE is correct. Extracting out the main cause of the failures give something like:

```dart
import "../../Utils/expect.dart";

class X {}

void checkme1<T>(expected, [T? t]) {
  Expect.equals(expected, T);
}

typedef void Test1<T>(dynamic, [T? t]);

main() {
  Test1 t1 = checkme1;
  t1(dynamic, dynamic);
  t1(dynamic);
}
```

What should the type of `T` (without `?`) be in `checkme1()` when it's called without providing a type argument? The test expects `dynamic` but the CFE says it is `Object`.

@fishythefish suspected there was already a discussion about this somewhere but we could not find it.

**Comment by fishythefish** [comment]
I believe the discussion I'm thinking of was about constraint solving, but I can't remember where it is. Essentially, given `T? == Object?` (or maybe it was a subtype constraint), when can we conclude `T == Object`?

I suspect that the type argument is being inferred based on `[T? t]` and we're running into a similar issue.

**Comment by johnniwinther** [comment]
@stefantsov can you take a look at this?

**Comment by lrhn** [comment]
I really can't read the inference spec, so I'll only try to guess the result.
My guess is that it depends on what we do when inferencing an unconstrained type argument, and I'd expect us to instantiate to bounds. That would mean `dynamic`. I see no reason to try *solving* for `T` without any constraints, and passing no second argument should mean that there are no constraints on `T` at all.

The method is written badly, it really should have `<T extends Object>` as type parameter since `T` *only* occurs with a `?` on.

**Comment by eernstg** [comment]
@fishythefish wrote:
> Essentially, given `T? == Object?` (or maybe it was a subtype constraint), when can we conclude `T == Object`?

That could be the inference spec change in https://github.com/dart-lang/language/pull/1200; it's been reopened because of some unexpected failures, and this could be the same situation.

**Comment by stefantsov** [comment]
I think I have an explanation about why we see what we see here.  It's an interplay between instantiate-to-bound, type inference, and the new spec update.

1. It starts with `Test1 t1` part in the first line in main (`Test1 t1 = checkme1;`).  Instantiate-to-bound provides `dynamic` as the type argument to `Test1` there.
2. `Test1<dynamic>` is used as a type context in type inference for the initializer of `t1`.  That is, `void Function(dynamic, dynamic)` is used as the type context.
3. The initializer is a tear-off with generic function type `void Function<T>(dynamic, [T?])`.  The context is not generic, so we try to instantiate the generic function.  For that we try to constrain `T`, which leads us to constraining `T?` with `dynamic` from left (`dynamic <# T?`).
4. According to the spec update, such constraints are resolved by providing `Object` as the value for `T`.

When compiled to Kernel, this line looks as follows:

```
  (dynamic, [dynamic]) → void t1 = #C2<core::Object>;
```

On the LHS we see dynamic as the type of the second optional argument in the type, but on the RHS the tear-off constant with generic function type is instantiated with `Object`.

FWIW, When I was working on implementing the spec update, I filed an issue for the co19 tests in question: https://github.com/dart-lang/co19/issues/936.

I'm closing this as a non-issue.  Please re-open if needed.
