### ISSUE TITLE
Better List assignment error message

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#4348]
[floitsch]

From time to time I write something like the following:
List&lt;js.Init&gt; inits = List&lt;js.Init&gt;[];
(instead of:
List&lt;js.Init&gt; inits = &lt;js.Init&gt;[];
)
The error message from the editor is pretty misleading since it signals errors on the left side of the expression.
////////////////////////////////////////////////////////////////////////////////////
Editor: 10220
OS: Linux - amd64 (3.2.5-gg886)
JVM: 1.6.0-google-v4

SDK installed: true
Dartium installed: true
////////////////////////////////////////////////////////////////////////////////////

**Comment by srawlins** [comment]
The warnings are now:

> warning: The operator '<' is not defined for the class 'Type'.
> error: Expected to find ';'
> error: Expected an identifier

https://dartpad.dartlang.org/4826757158fbefcf4e6b0d103fd7ad40

Good enough?

**Comment by bwilkerson** [comment]
Less than perfect is never good enough :-)

Ideally we'd have a single message similar to:

The type 'List' is implied here. Remove it.

**Comment by srawlins** [comment]
I agree. Just a few implementations of List and Map to catch, and then we can make a specific warning like your example.
