### ISSUE TITLE
CFE fails on co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t157

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#43499]
CFE fails to report an error on `co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t157`

**Comment by johnniwinther** [comment]
The test has
```Dart
// opt-out:
class A_OUT<T> { T Function(T) get f => (x) => x; }
class out_Never extends A_OUT<Never> {}

// opt-in:
class CHECK_TOP_MERGE<T> {
  T Function(T) get f => (x) => x;
}
class B extends CHECK_TOP_MERGE<Never> {}
class C1 extends B implements out_Never {}
class C2 extends out_Never implements B {}
```
and expects a compile-time error on `C1` and `C2` for an invalid override of `f`.

The type of `f` in `B` is `Never Function(Never) Function()` and the type of `f` in `out_Never` is `Never* Function(Never*) Function()*`. 

These are mutual subtypes so I don't see why one shouldn't be a valid override of the other.

@eernstg What do you think?

Note that analyzer _does_ produce an error _and_ computes the type of `f` in `out_Never` to be `Null* Function(Null*)* Function()*`.

**Comment by eernstg** [comment]
We actually concluded, cf. https://github.com/dart-lang/language/issues/825#issuecomment-637429210, that when `Never` occurs in a legacy library it should be treated as `Null`. So the analyzer behavior follows that decision.

**Comment by johnniwinther** [comment]
Seems like an odd decision given we have `Never*`.

**Comment by eernstg** [comment]
Perhaps, but it does allow the statement 'The type `Never` is treated as the type `Null`' about legacy libraries to apply consistently, which may be helpful.

**Comment by johnniwinther** [comment]
Does this apply to `Never` as a type literal as well?

**Comment by eernstg** [comment]
I don't see any justification for not applying that rule to the type literal `Never`.

**Comment by eernstg** [comment]
This could be a breaking change: Even though the analyzer already seems to apply this rule, the run-time behavior of a program could change.
