### ISSUE TITLE
Future not working on mac  ("dart:async" library)

### ISSUE THREAD

**Issue by fuadnassar90** [dart-lang/sdk#43492]
IDE: IntelliJ 
OS: Mac 10.15.15

hi,
i have test the bellow code on my windows and it's work as fine and print event1 in output, but when i tried to run the same **this code on mac output be empty**.

Dart Console Application:
`main() {
  Future(() => print('event1'));
}`

**Comment by mraleph** [comment]
You would need to provide more detailed instructions on how to reproduce this issue because basic testing does not reproduce it.

**Comment by a-siva** [comment]
I tried your example above with the bleeding edge version of Dart on OS:Mac 10.15.6 and it worked fine.
We need more information to act on it.
