### ISSUE TITLE
Unnecessary cast inserted by the Null Safety migration tool

### ISSUE THREAD

**Issue by michalt** [dart-lang/sdk#43501]
Consider the following code with Null Safety hints:

```dart
Point<int> foo() {
  var rect = Rectangle(1, 2, 3, 4);
  var point = <Point<int> /*?*/ >[
    Point(1, 2),
    Point(2, 3),
  ].firstWhere(((p) => !rect.containsPoint(p /*!*/)), orElse: () => null);
  return point;
}
```

The output of the migration tool:

```dart
Point<int >? foo() {
  var rect = Rectangle(1, 2, 3, 4);
  var point = <Point<int > /*?*/ >[
    Point(1, 2),
    Point(2, 3),
  ].firstWhere((((p) => !rect.containsPoint(p /*!*/)) as bool Function(Point<int>?)), orElse: () => null);
  return point;
}
```

AFACS the inserted function cast is unnecessary.

CC @stereotype441

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
