### ISSUE TITLE
Dart using * for making some methods instead definition itself

### ISSUE THREAD

**Issue by MahdiPishguy** [dart-lang/sdk#43506]
you suppose i have this extension:

    extension MyWidget on Widget {
      Widget p(double padding) => Padding(padding: EdgeInsets.all(padding), child: this);
      Widget p0(double padding) => Padding(padding: EdgeInsets.zero, child: this);
      Widget p1(double padding) => Padding(padding: EdgeInsets.all(1), child: this);
      Widget p2(double padding) => Padding(padding: EdgeInsets.all(2), child: this);
      Widget p3(double padding) => Padding(padding: EdgeInsets.all(3), child: this);
      Widget p4(double padding) => Padding(padding: EdgeInsets.all(4), child: this);
      Widget p5(double padding) => Padding(padding: EdgeInsets.all(5), child: this);
      Widget p6(double padding) => Padding(padding: EdgeInsets.all(6), child: this);
      Widget p7(double padding) => Padding(padding: EdgeInsets.all(7), child: this);
      Widget p8(double padding) => Padding(padding: EdgeInsets.all(8), child: this);
      Widget p9(double padding) => Padding(padding: EdgeInsets.all(9), child: this);
      Widget p10(double padding) => Padding(padding: EdgeInsets.all(10), child: this);
    
      Widget center() => Center(child: this);
    }

how can i have this sample method instead of all definitions?

    /* Center().p2 */
    /* Center().p8 */
    extension MyWidget on Widget {
      Widget p(double padding) => Padding(padding: EdgeInsets.all(padding), child: this);
      Widget p*() => Padding(padding: *, child: this);
    
      Widget center() => Center(child: this);
    }

i know, i can make this below extension, but i want to know this implementation can be define in dart or not

    /* Center().p(2) */
    extension MyWidget on Widget {
      Widget p(double padding) => Padding(padding: EdgeInsets.all(padding), child: this);
    
      Widget center() => Center(child: this);
    }

**Comment by lrhn** [comment]
There is nothing in the Dart language giving you this ability. You cannot abstract over source names.
That would require some kind of meta-programming functionality, which Dart currently doesn't have.

You can obviously use off-line code generation to generate the file (a `for` loop with a print statement can give you the text), but that's not a feature of Dart.

**Comment by mkustermann** [comment]
@MahdiPishguy I guess @lrhn has answered your original question. 

If you have a specific request to how the Dart language can be extended, I would encourage you to file an issue under the https://github.com/dart-lang/language repository, which tracks evolution of the Dart language.

Hope it's all right if I close this issue.

**Comment by MahdiPishguy** [comment]
> 
> 
> @MahdiPishguy I guess @lrhn has answered your original question.
> 
> If you have a specific request to how the Dart language can be extended, I would encourage you to file an issue under the https://github.com/dart-lang/language repository, which tracks evolution of the Dart language.
> 
> Hope it's all right if I close this issue.

Yes, thanks a lot. i think this is good ability for dart, but i'm not sure is this right or not
