### ISSUE TITLE
Map operator [] is not type-safe

### ISSUE THREAD

**Issue by devxpy** [dart-lang/sdk#43517]
The following code compiles successfully, but in my mind, it should have not -

```dart
void main() {
  Map<int, String> myIntMap = {5: "hello!"};
  print(myIntMap["5"]);
}
```
Output -
```
null
```

At compile time, Is there any way to make dart ensure that the type of key that I'm passing is the correct type for that Map?

As one can imagine, this kind of mistake is very easy to make, and also easily preventable at compile time. (We just encountered a hard to track bug in our app because of it!)

[dartpad](https://dartpad.dev/9e998892582f02f222fa0b633817061a)

**Comment by lrhn** [comment]
There is no way to avoid an incompatible type being allowed, while also allowing a `Map<String, String>` to be used as a `Map<Object, Object>`. Dart has covariant generics, so the string map is assignable to the object map type. By allowing any value to be used as key in lookup (and a few other methods), you *can* use the map at the supertype, as long as you only use it for *reading*. Writing will still necessarily throw.

There are some lints for similar situations ([iterable_contains_unrelated_type](https://dart-lang.github.io/linter/lints/iterable_contains_unrelated_type.html), [list_remove_unrelated_type](https://dart-lang.github.io/linter/lints/list_remove_unrelated_type.html)), but nothing for map indexing.

**Comment by kevmoo** [comment]
I agree this is weird. We should do something like https://github.com/dart-lang/linter/issues/1307

@lrhn – there's no action for us here, right?

**Comment by devxpy** [comment]
Thanks, the linter issue seems like a nice to have :)
