### ISSUE TITLE
Analyzer: Implementation of super-bounded types with null safety

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#43524]
With null safety, the spec update in dart-lang/language#1133 calls for the use of `Never` rather than `Null` during instantiation to bound, and during the checks for being a correctly super-bounded type.

Some work was done on this in https://github.com/dart-lang/sdk/commit/744e34aec07a2bbe982deb32ca6307b54003c1db, but the following example illustrates that the analyzer still uses `Null`:

```dart
class A<X extends void Function(X)> {}

void main() {
  A a = A<Never>();
}
```

The response (with the analyzer from commit ecc87a177fad538728998b4c49f043b4bf9212bd) is as follows:

```
ERROR|COMPILE_TIME_ERROR|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/202009/n025.dart|4|3|1|'void Function(Null)' doesn't extend 'void Function(void Function(Null))'.
```

This shows that the raw `A` is expanded by i2b to `A<void Function(Null)>`, and then the bounds check fails.

When `A` is expanded to `A<void Function(Never)>` the type is correctly super-bounded and the raw `A` is allowed, and this is the expected outcome after #1133.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/164860
