### ISSUE TITLE
Non Nullable doesn't work with 2.10 beta version

### ISSUE THREAD

**Issue by enyo** [dart-lang/sdk#43522]
I installed with `homebrew install dart-beta` and setting the sdk version constraint to `>=2.10.0-110.3.beta <3.0.0` doesn't work.

I then installed the `--dev` version, and set the version constraint to `sdk: ">=2.10.0-0.0.dev` and it worked fine.

**Comment by mkustermann** [comment]
@enyo To clarify: Do you mean `--enable-experiment=non-nullable` does not work for you? Or do you expect the experiment to be enabled by-default in 2.10 beta?

/cc @mit-mit Can you clarify from which point on the experiment is available and from which point on it will be on by-default?

**Comment by enyo** [comment]
No I wasn't talking about `--enable-experiment=non-nullable`. I was expecting it to work by setting the constraint to `>=2.10` and the appropriate settings in `analysis_options.yaml`.

With the `dev` version it did work.

**Comment by mit-mit** [comment]
I believe you need to change your SDK constraint slightly to `sdk: ">=2.10.0-0.0`

**Comment by mit-mit** [comment]
Closing as I don't think there is an issue here. @enyo if you still see an issue, please reopen and provide concrete repro steps.

**Comment by enyo** [comment]
Just tested it and it works. Thanks @mit-mit
