### ISSUE TITLE
Error requesting code fixes for file outside of analysis roots: NoSuchMethodError: The method 'packagesAvailableTo' was called on null

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#43521]
This exception occurs in both LSP and the original protocol, though using the original protocol it seems like I never get a response from the server (I got the error/stack by attaching the debugger).

I don't know whether it's valid to try and get fixes for a file outside the analysis roots, but in the case of LSP we can't control the editor.

@bwilkerson do you think it would be better to skip this for files outside the root, or handle this specific error better (I'm not sure how much functionality we would expect for files outside of roots)?

```
Exception has occurred.
CaughtExceptionWithFiles (NoSuchMethodError: The method 'packagesAvailableTo' was called on null.
Receiver: null
Tried calling: packagesAvailableTo("/Users/danny/Desktop/dart_sample/lib/foo1.dart")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TransformSetManager.forLibrary (package:analysis_server/src/services/correction/fix/data_driven/transform_set_manager.dart:28:30)
#2      DataDriven._availableTransformSetsForLibrary (package:analysis_server/src/services/correction/dart/data_driven.dart:72:41)
#3      DataDriven.producers.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:32:21)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:165:25)
#5      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1146:46)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1079:11)
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:175:35)
#8      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:646:48)
<asynchronous suspension>
#9      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:757:14)
#10     EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:301:32)
#11     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:396:9)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:239:38)
```

LSP:
```
An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'packagesAvailableTo' was called on null.
Receiver: null
Tried calling: packagesAvailableTo("/Users/danny/Desktop/dart_sample/lib/foo1.dart")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TransformSetManager.forLibrary (package:analysis_server/src/services/correction/fix/data_driven/transform_set_manager.dart:28:30)
#2      DataDriven._availableTransformSetsForLibrary (package:analysis_server/src/services/correction/dart/data_driven.dart:72:41)
#3      DataDriven.producers.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:32:21)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:165:25)
#5      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1146:46)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1079:11)
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:175:35)
#8      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:244:46)
<asynchronous suspension>
#9      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:205:7)
#10     CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:73:18)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#12     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:70:26)
#13     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#14     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:69:26)
#15     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#16     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:66:17)
```

**Comment by bwilkerson** [comment]
> do you think it would be better to skip this for files outside the root, or handle this specific error better (I'm not sure how much functionality we would expect for files outside of roots)?

Given that we only analyze files inside analysis roots, I think it's reasonable to not support functionality that depends on analysis in files outside any root.

In the original protocol, the consistent way to handle this is to introduce a new error (`GET_FIXES_INVALID_FILE`) to return when `edit.getFixes` is invoked on a non-analyzed file.

Do you want to update the handlers, or would you like me to do so?

I'll update `forLibrary` to not throw an exception in this case.

**Comment by DanTup** [comment]
I've got changes for both servers here:

https://dart-review.googlesource.com/c/sdk/+/164088/

https://dart-review.googlesource.com/c/sdk/+/164089/

**Comment by bsutton** [comment]
Is there an update on this.

I'm seeing this error on vscode 1.53.2/ Dart code 3.20.0/flutter 1.22.4/Dart 2.10.4.

I also have Dart sdk installed which is 2.10.5 but I assume vscode/lsp isn't using that version.

**Comment by DanTup** [comment]
This was fixed by the changes above, however they were made after the branch for Dart 2.10/Flutter 1.22. They'll be included in the next (major) Flutter stable release (and should already be on beta/dev/master).

> I also have Dart sdk installed which is 2.10.5 but I assume vscode/lsp isn't using that version.

If you have a Flutter project open it'll use the Dart SDK embedded inside Flutter. If it's a non-Flutter app, it'll use the first Dart SDK it can find from `PATH`. You can check which version it's using by running **Dart: Capture Extension Logs** then immediately clicking **Cancel** which will open a log with the header, which includes the Dart SDK location.

In this case, your Flutter/Dart SDKs are roughly in sync though, and neither of them contain the fix (but the next major versions of each should).
