### ISSUE TITLE
[DDC] Crash on Safari: "Duplicate parameter 'char' not allowed in function with default parameter values."

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#43520]
# Bug

When running a Flutter Web app that uses [`petitparser`](https://pub.dev/packages/petitparser) (a _Dart only_ package), the app crashes immediately when starting **on Safari**.

The app does not need to call any `petitparser` code - it just needs to reference the dependency in order to include it in the app.

## Reproducible steps

The reproducible steps on the Flutter side can be [found here](https://github.com/flutter/flutter/issues/66286#issuecomment-696582022). They are simply adding the `petitparser` dependency, referencing it, and running it on Safari.

## Error

The error logs are the following:

<details>
  <summary>Logs</summary>

```
[Error] SyntaxError: Duplicate parameter 'char' not allowed in function with default parameter values.
	(anonymous function) (optional.dart.lib.js:376)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__combinator__delegate')
	load__packages__petitparser__src__parser__action__cast_dart (cast.dart.lib.js:6:84)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__parser__action__pick_dart (pick.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__combinator__delegate')
	load__packages__petitparser__src__parser__action__flatten_dart (flatten.dart.lib.js:6:84)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__xml__src__xml__utils__character_data_parser_dart (character_data_parser.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__repeater__possesive')
	load__packages__petitparser__src__parser__repeater__separated_by_dart (separated_by.dart.lib.js:7:85)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__parser__misc__epsilon_dart (epsilon.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__definition__reference_dart (reference.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__parser__predicate__predicate_dart (predicate.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__parser__repeater__limited_dart (limited.dart.lib.js:7:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__character__parser')
	load__packages__petitparser__src__parser__character__whitespace_dart (whitespace.dart.lib.js:7:82)
	execCb (require.js:1696)
	check (require.js:883)
	(anonymous function) (require.js:1139)
	(anonymous function) (require.js:134)
	(anonymous function) (require.js:1189)
	each (require.js:59)
	emit (require.js:1188)
	check (require.js:938)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__character__parser')
	load__packages__petitparser__src__parser__character__range_dart (range.dart.lib.js:7:82)
	execCb (require.js:1696)
	check (require.js:883)
	(anonymous function) (require.js:1139)
	(anonymous function) (require.js:134)
	(anonymous function) (require.js:1189)
	each (require.js:59)
	emit (require.js:1188)
	check (require.js:938)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
```
</details>

**Comment by sigmundch** [comment]
Thanks for filing the issue. 

I should point out that support for the development compiler (DDC) in Safari is not complete and we have several known issues there. We usually recommend running apps in development mode in Chrome or FF, and only run the release/deploy version (dart2js) of the program in Safari.

Sounds from your other bug that you also run into issues in Safari with the release version? I sense it may be higher priority to investigate that first?

**Comment by creativecreatorormaybenot** [comment]
@sigmundch Yes, that is correct. The release bug has to be something different and that is high priority while the debug one was only relevant because I am trying to debug the release one.

I am having a really hard time debugging it because I either get nothing from the console or logs that I do not know exactly how to work with (not human readable or not verbose).

**Comment by smunozp** [comment]
any update on this? I'm having this issue as well in the production release of our app.

[Error] SyntaxError: Duplicate parameter 'char' not allowed in function with default parameter values.
	(anonymous function) (optional.dart.lib.js:408)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__combinator__delegate')
	load__packages__petitparser__src__parser__action__cast_dart (cast.dart.lib.js:6:84)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__xml__src__xml__utils__character_data_parser_dart (character_data_parser.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__parser__action__pick_dart (pick.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__combinator__delegate')
	load__packages__petitparser__src__parser__action__flatten_dart (flatten.dart.lib.js:6:84)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__combinator__sequence')
	load__packages__petitparser__src__parser__repeater__separated_by_dart (separated_by.dart.lib.js:7:84)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__parser__misc__epsilon_dart (epsilon.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__parser__predicate__predicate_dart (predicate.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__parser__repeater__limited_dart (limited.dart.lib.js:7:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__character__parser')
	load__packages__petitparser__src__parser__character__whitespace_dart (whitespace.dart.lib.js:7:82)
	execCb (require.js:1696)
	check (require.js:883)
	(anonymous function) (require.js:1139)
	(anonymous function) (require.js:134)
	(anonymous function) (require.js:1189)
	each (require.js:59)
	emit (require.js:1188)
	check (require.js:938)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__parser__character__parser')
	load__packages__petitparser__src__parser__character__range_dart (range.dart.lib.js:7:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)
[Error] TypeError: undefined is not an object (evaluating 'packages__petitparser__src__parser__combinator__optional$46dart.src__core__parser')
	load__packages__petitparser__src__definition__reference_dart (reference.dart.lib.js:6:82)
	execCb (require.js:1696)
	check (require.js:883)
	enable (require.js:1176)
	init (require.js:788)
	callGetModule (require.js:1203)
	completeLoad (require.js:1590)
	onScriptLoad (require.js:1717)

**Comment by sigmundch** [comment]
Sorry, we don't have any updates at the moment, we have prioritized work on other areas and have not yet looked into this issue.

I worry about the problems you mention on the production version of the app though. When we fix the issue in DDC, it will not help with the error you may be hitting in production (which uses a different compiler pipeline).

@creativecreatorormaybenot was seeing a blank console in production. @smunozp  - do you happen to have errors from your production version of your app? Any tips on how to create a small repro for that?

**Comment by smunozp** [comment]
I was able to do a workaround to make the app work on safari...

I had an async function on main to initialize firebase that was without a try-catch, 
I had to delete flutter_svg and use png instead,
and I had to modify a regex on dotenv package that was not supported by safari.

hope this helps others facing a similar issue
