### ISSUE TITLE
Analysis Server fix for adding missing overrides sometimes generates invalide code

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#43535]
For example, starting with the file:

```dart
class A {
  void doSomething(Map<String, dynamic>? m) {}
}

class B implements A {}
```

If my cursor is on `B` and I run the action "Create 1 missing override(s)" the end result is:

```dart
class B implements A {
  @override
  void doSomething(Map?<String, > m) {
    // TODO: implement doSomething
  }
}
```

There are two problems:

- The `dynamic` disappeared.
- The `?` moved from after the `>` to after the `Map`.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/164260
