### ISSUE TITLE
No error if library exports declaration 'main' which is not a function

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43549]
According to the recent [update](https://github.com/dart-lang/language/pull/1146) of the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#the-main-function)

> Let L be a library that exports a declaration D named main. It is a compile-time error unless D is a function declaration.

But, in fact, there are no errors nor in analyzer nor in CFE in all of the cases below
```dart
void getVoid() {}
void main = getVoid();
```
```dart
int get main => 42;
```
```dart
class main {}
```
```dart
typedef void main(List<String> args);
```
```dart
class C {
}
mixin main on C {}
```
`Dart SDK version: 2.10.0-110.0.dev (dev) (Wed Sep 9 17:51:43 2020 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
Created #43556/#43557 specific to CFE/analyzer, moved CFE epic link to #43556.

**Comment by franklinyow** [comment]
Any work left? Can we close this now?

**Comment by eernstg** [comment]
No more work here, it's covered by sub-issues and they're closed.
