### ISSUE TITLE
remove the --dartpad command line option for the analysis server

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43540]
This was only ever used by dartpad, and it's since moved off using the flag (https://github.com/dart-lang/dart-services/pull/604).

When we remove it, we should consider changing the `UriContributor` code completion contributor to not suggest file paths outside of analysis context roots; the `--dartpad` cli option was intended to prevent arbitrary exploration of the files on a filesystem.

https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/completion/dart/uri_contributor.dart#L19

**Comment by srawlins** [comment]
Looks like this was removed.
