### ISSUE TITLE
HttpClient does not redirect when it sees a HTTP 308 response

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#43548]
The [`HTTP 308 Permanent Redirect`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) status code "indicates that the resource requested has been definitively moved to the URL given by the Location headers". It's basically another version of HTTP 301, [proposed](https://tools.ietf.org/html/rfc7538#section-3) in 2015 and currently [supported by all browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308#Browser_compatibility) and [preferred over HTTP 301](https://stackoverflow.com/a/42138726/1416886).

It [was added](https://github.com/dart-lang/sdk/blob/272f39a1964e97a6f1c9d60e2c509b58e0b99681/sdk/lib/internal/internal.dart#L285-L286) to the list of `HttpStatus` constants in Dart 2.1. But [it is not](https://github.com/dart-lang/sdk/blob/e85e5b6264edf554c13d328a0af9c38672c4a0c3/sdk/lib/_http/http.dart#L1944-L1949) documented as one of the supported redirects, and [it is not implemented](https://github.com/dart-lang/sdk/blob/35680f0193656f9408384306a67524e65b5d85b5/sdk/lib/_http/http_impl.dart#L352-L355) as such.

I think that's a serious omission, as this HTTP code is starting to [get seen in the wild](https://github.com/filiph/linkcheck/issues/55). Right now, a redirect chain including an HTTP 308 response will stop at that redirect and won't continue when using Dart.

If this is something the maintainers agree with, I can take a stab at implementing the change.

---

* Dart SDK Version (`dart --version`)
Dart SDK version: 2.9.3 (stable) (Tue Sep 8 11:21:00 2020 +0200) on "macos_x64"

**Comment by mit-mit** [comment]
@bkonyi @a-siva WDYT?

**Comment by bkonyi** [comment]
We should definitely be redirecting for a 308. @filiph if you want to take a swing at a fix and have some time, go for it. Otherwise I can pick it up at some point soon.

**Comment by filiph** [comment]
Ok, I took a stab at the fix just now: https://dart-review.googlesource.com/c/sdk/+/165404. I have no idea what I'm doing. This is my first commit to the SDK so I won't be offended if you reject the change and do it the proper way. It's not a lot of code.

One thing that I don't understand is that tests in places like `tests/co19_2/src/LibTest/io/HttpClientResponse/redirects_A01_t02.dart` did not get attached to the CL, even though I changed them. I tried to read the READMEs but didn't find anything that'd help. Once again, I realize it may be easier for you to do it yourself then to try to educate me, and I won't be offended.

**Comment by filiph** [comment]
I see you already LGTM'd. I don't have commit rights. Should I be doing anything or do I just wait?

**Comment by bkonyi** [comment]
> Ok, I took a stab at the fix just now: https://dart-review.googlesource.com/c/sdk/+/165404. I have no idea what I'm doing. This is my first commit to the SDK so I won't be offended if you reject the change and do it the proper way. It's not a lot of code.
> 
> One thing that I don't understand is that tests in places like `tests/co19_2/src/LibTest/io/HttpClientResponse/redirects_A01_t02.dart` did not get attached to the CL, even though I changed them. I tried to read the READMEs but didn't find anything that'd help. Once again, I realize it may be easier for you to do it yourself then to try to educate me, and I won't be offended.

I don't see anything wrong with your change :-). Also, `co19_2` tests aren't part of the repo as they're externally maintained. If there's a bug in one of those tests, you'll want to file an issue [here](https://github.com/dart-lang/co19).

**Comment by bkonyi** [comment]
> I see you already LGTM'd. I don't have commit rights. Should I be doing anything or do I just wait?

I'll handle merging once the CQ finishes.
