### ISSUE TITLE
No error if the first argument of 'main' is not supertype of 'List<String>'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43552]
With the recent [change](https://github.com/dart-lang/language/pull/1146) in NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#the-main-function)

> Let L be a library that exports a declaration D named main. ... It is a compile-time error if D declares at least one positional parameter, and the first positional parameter has a type which is not a supertype of List< String >.

In fact, there is no error in analyzer and runtime error in VM
```dart
main(String args) {}
```
There must be a compile error in both analyzer and CFE
`Dart SDK version: 2.10.0-110.0.dev (dev) (Wed Sep 9 17:51:43 2020 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
Thanks! I've created tool specific issues #43554, #43555 and made this one an epic containing those.

**Comment by eernstg** [comment]
@johnniwinther, I created a CFE specific issue for this, #43554, and made it part of the epic 'CFE Null Safety Beta 2', then removed this one from that epic to avoid the duplication.

**Comment by sgrekhov** [comment]
@eernstg, thank you. Please see also https://github.com/dart-lang/sdk/issues/43551 and
https://github.com/dart-lang/sdk/issues/43549

**Comment by eernstg** [comment]
Transformed #43551 and #43549 similarly: If one issue has `area-analyzer` and `area-front-end` at the same time then the status (open/closed) is ambiguous. So it's better to have one issue for each, and the common text can be an epic, `area-meta`.

**Comment by mit-mit** [comment]
@eernstg looks like this was resolved?

**Comment by eernstg** [comment]
Indeed. It might be useful if an epic could be marked to auto-close when the last of its sub-epics/issues is closed.
