### ISSUE TITLE
[NNBD] No compile error if function 'main()' has more than two required positional parameters

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43551]
Accordint to the recent [change](https://github.com/dart-lang/language/pull/1146) in NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#the-main-function)

> Let L be a library that exports a declaration D named main. ... It is a compile-time error if D declares more than two required positional parameters, or if there are any required named parameters.

In fact, there are no issues in analyzer and runtime `NoSuchMethodError` in VM in both cases below
```dart
void main(List<String> args, var i, var j) {}
```
```dart
void main({required List<String> args}) {}
```
There must be a compile error in both analyzer and CFE
`Dart SDK version: 2.10.0-110.0.dev (dev) (Wed Sep 9 17:51:43 2020 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
Created #43558/#43559 specific to CFE/analyzer, moved CFE epic link to #43558.

**Comment by franklinyow** [comment]
Any work left? Can we close this now?

**Comment by eernstg** [comment]
No more work here, it's covered by sub-issues and they're closed.
