### ISSUE TITLE
Need an analyzer version published for 2.11 dev releases

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#43550]
Now that we have a 2.11 dev sdk we need an analyzer that supports that language version.

See https://travis-ci.org/github/dart-lang/build/jobs/730147024#L413 - nothing is broken other than our tests, but users will start seeing this warning on the 2.11 dev sdk.

**Comment by jakemac53** [comment]
This also does seem like something which will happen on each sdk version bump, so open to suggestions for how/if we should change our validation etc.

**Comment by bwilkerson** [comment]
@devoncarew

**Comment by jakemac53** [comment]
Skipping the test in `build_resolvers` for now, and will restore it once we have something published.

We also don't currently allow enabling of experiments if the `ExperimentStatus.currentVersion` doesn't exactly match the current sdk version, I am updating that to only require that the sdk version is not greater than that version.

See https://github.com/dart-lang/build/pull/2840.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/164600
