### ISSUE TITLE
Analyzer: No error if library exports declaration 'main' which is not a function

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#43557]
This is the analyzer specific issue for #43549, which has the details.

**Comment by scheglov** [comment]
Do we perform these new checks only when null safety is enabled, or always?

**Comment by eernstg** [comment]
This is a null safety only update ([here](https://github.com/dart-lang/language/pull/1146)).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/165960
