### ISSUE TITLE
Comparing 04/10/2020 with 05/10/2020 is failing

### ISSUE THREAD

**Issue by ssivagnanam** [dart-lang/sdk#43562]
Hi Team,

When i compare two DateTime objects (04/10/2020 with 05/10/2020) using difference() method.  I am getting Duration result as 23:30:0:00.00000. 
Note : This issue occurs only in Australian Eastern Time Zone. Only for above two dates.

Flutter : 1.17.5
Dart SDK : 2.8.4
Environment : VS Code (Mac OS).

**Comment by mit-mit** [comment]
cc @lrhn 

I tried `print(DateTime.parse("2020-10-05 00:00:00").difference(DateTime.parse("2020-10-04 00:00:00")));` in DartPad with my time zone set to Sydney, and that printed `23:00:00.000000`

**Comment by lrhn** [comment]
The Dart VM doesn't actually understand time zones, it relies on the operating system for local time.

If you get a difference which is not a full hour between daylight saving time and non-daylight saving time, then your operating system appears to think that you are in a time zone with a half-hour change. Such places exist. It's not Australian Eastern time, but could be [Lord Howe Island](https://www.timeanddate.com/time/time-zones-interesting.html#:~:text=Lord%20Howe) time. Or it could perhaps, for some reason, think you moved between eastern time and central time.

Can you see the same difference in non-Dart programs?
