### ISSUE TITLE
[dart2js] assigning a null value in one variable to a different variable breaks the assigned null value, so that null != null

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/sdk#43579]
When assigning a static or global variable that hasn't been initialized (or is set to `null`) to a local variable the local variable will have a different kind/value of `null` when compiled with dart2js. This started happening with the current dev release: `Dart SDK version: 2.11.0-161.0.dev (dev) (Thu Sep 24 17:00:45 2020 -0700) on "windows_x64"`

```dart
String bar;

void main() {
  final foo = bar;

  print('bar: $bar');
  print('bar == null: ${bar == null}');

  print('foo: $foo');
  print('foo == null: ${foo == null}');

  print('foo == bar: ${foo == bar}');
}
```

Output with dart2js:
```
bar: null
bar == null: true
foo: null
foo == null: false
foo == bar: false
```

Output with ddc (correct and expected output):

```
bar: null
bar == null: true
foo: null
foo == null: true
foo == bar: true
```

The same thing happens if bar is declared like this:

```dart
class Foo {
   static String bar;
}
```

And `bar == Foo.bar` will be true, but assigning either of them to `foo` will result in `foo == null` returning false.

This behavior breaks the current/old 6.0.0-alpha+1 of AngularDart, because Angular does this:

```dart
  @override
  void initComponentStyles() {
    var styles = _componentStyles;
    if (identical(styles, null)) {
      (_componentStyles = (styles = (_componentStyles = import4.ComponentStyles.scoped(styles$AppComponent, _debugComponentUrl))));
    }
    this.componentStyles = styles;
  }
```

And the `if` branch will not be entered because the `null` value in styles is a different kind of `null` (`_componentStyles` is static).

**Comment by denniskaselow** [comment]
Bug is still present in `Dart SDK version: 2.11.0-176.0.dev (dev) (Mon Sep 28 19:05:52 2020 -0700) on "windows_x64"`.

I was also able to narrow it down even more. The bug happens if the involved variables are declared in different scopes and the left hand side variable is not declared as `var` or `Object`. It does not matter which variable is from higher/lower scope.

```dart
void main() {
  // when using Object or var here, the bug will not trigger
  List foo;
  {
    List bar;

    foo = bar;

    print('foo == null: ${foo == null}');
    print('bar == null: ${bar == null}');
    print('foo == bar: ${foo == bar}');
  }
}
```

Output:
```
foo == null: false
bar == null: true
foo == bar: false
```

**Comment by eernstg** [comment]
Same issue arises on Linux with dart2js. The results in compiled code have been evaluated at compile-time:

```JS
    main: function() {
      P.print("bar: null");
      P.print("bar == null: true");
      P.print("foo: " + null);
      P.print("foo == null: false");
      P.print("foo == bar: false");
    }
```

With an older version of dart2js (dart-sdk-2.8.0-dev.10.0) we get the expected results:

```JS
    main: function() {
      P.print("bar: null");
      P.print("bar == null: true");
      P.print("foo: null");
      P.print("foo == null: true");
      P.print("foo == bar: true");
    }
```

**Comment by fishythefish** [comment]
This is fixed on master, likely due to https://dart-review.googlesource.com/c/sdk/+/164941.
