### ISSUE TITLE
Type isn't inferred for extension members on a generic parameter

### ISSUE THREAD

**Issue by frmrgr** [dart-lang/sdk#43575]
Problem is observed for both generic functions and classes.
Dart SDK Version 2.9.3

Repro:

    extension Ext<T> on T {
      T get foo => null;
    }
    class Cls<T> {
      T t;
      T get tFoo => t.foo; // does not compile in strong mode
    }
    void f<T>(T t) {
      t = t.foo; // does not compile in strong mode
    }

Each `t.foo` call is inferred to `Object` instead of `T`. This is mostly a problem for proto messages, which have a `deepCopy()` inside an extesion, so code like this

    import 'package:protobuf/protobuf.dart';
    
    abstract class BaseModel<V extends GeneratedMessage> {
      V _value;
      void init(V value) => _value = value.deepCopy();
    }

fails with error: `A value of type 'GeneratedMessage' can't be assigned to a variable of type 'V'.`

**Comment by lrhn** [comment]
Reproduces in nullsafety.dartpad.dev, but not in plan dartpad.dev, so seems like an issue with the null safe type system.

**Comment by frmrgr** [comment]
Sorry for not being clear. For this to turn into an error,

    analyzer:
      strong-mode:
        implicit-casts: false

needs to be added. But I don't think it has anything to do with null safe thing. I think that outside strong mode the same happens, but automatic downcast fixes it.

**Comment by johnniwinther** [comment]
This is related to #43177

**Comment by lrhn** [comment]
Good point, the reason it works in legacy DartPad is that it allows implicit casts. The error is still there, `T` is bound to `Object`.
It's all the same problem, probably the one @johnniwinther linked to.

**Comment by frmrgr** [comment]
I didn't find that issue. This can be closed as a dupe of https://github.com/dart-lang/language/issues/1182

**Comment by scheglov** [comment]
Yes, fixed as ba9355624cb2bc6d4b0b00b31631ab6b7a170227.
