### ISSUE TITLE
[Gardening] Failures on Remove unnecessary getStaticType().

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#43587]
There are new test failures on [Remove unnecessary getStaticType().](https://github.com/dart-lang/sdk/commit/6fce77010a935c6d8782315c1c805ef47ac5b751).

The tests
```
co19_2/LibTest/io/FileSystemMoveEvent/isDirectory_A01_t03 RuntimeError (expected Pass)
co19_2/LibTest/io/FileSystemMoveEvent/path_A01_t03 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-mac-release-x64
```

It appears that these tests changed from flaky to permanent RuntimeError.

**Comment by crelier** [comment]
Could this be a mac builder issue, as @askeksa-google  points out?

**Comment by askeksa-google** [comment]
Yes, those are the failures I noticed. It seems highly implausible that these would be caused by a change in the analyzer.

**Comment by alexmarkov** [comment]
These tests are now passing on all configurations and not flaky.
