### ISSUE TITLE
Parameter mismatch issue with Isolate.spawn on dart2js and dart 2

### ISSUE THREAD

**Issue by mathatan** [dart-lang/sdk#43581]
I'm trying to compile a flutter app to web-app but I keep running into following compile errors:

```
Target dart2js failed: Exception: lib/core/data_structures/deal_data.dart:167:9:
Error: No named parameter with the name 'debugName'.
       debugName: _debugName,
       ^^^^^^^^^
org-dartlang-sdk:///lib/_internal/js_runtime/lib/isolate_patch.dart@1002+5:
Info: Found this candidate, but the arguments don't match.
../../../../.pub-cache/hosted/pub.dartlang.org/computer-1.0.2/lib/src/worker.dart:45:7:
Error: No named parameter with the name 'debugName'.
     debugName: name,
     ^^^^^^^^^
org-dartlang-sdk:///lib/_internal/js_runtime/lib/isolate_patch.dart@1002+5:
Info: Found this candidate, but the arguments don't match.
Error: Compilation failed.
```

I've narrowed the issue to be `sdk/lib/_internal/js_runtime/lib/isolate_patch.dart:40-45` in the spawn method definition, which doesn't specify debugName parameter. While I know dart2js don't support isolates it's something I can work around, but bc of this I cannot currently compile the code at all.

**Comment by fishythefish** [comment]
Looks like an oversight - when `debugName` was added in 2.3, we added a throwing getter for it and included the parameter in `spawnUri`, but it's missing in `spawn`. Created https://dart-review.googlesource.com/c/sdk/+/164940 to fix.
