### ISSUE TITLE
isolate/nnbd_spawnuri_autodetect tests are timing out on windows shards

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#43583]
These tests leak processes running e.g. strong_strong.dart or strong_weak.dart scripts and cause builders to go purple on windows.

```
--- Command "vm" (took 01:00.000031s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\dart.exe --enable_asserts --no-sound-null-safety --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\tests\lib\isolate\nnbd_spawnuri_autodetect_1_test.dart

exit code:
null

diagnostics:
win_sdk_path not found

--- Re-run this test:
python tools/test.py -n dartk-weak-asserts-win-release-x64 lib/isolate/nnbd_spawnuri_autodetect_1_test
```

**Comment by mkustermann** [comment]
@athomas IMHO the builder shouldn't go purple because there's one misbehaving test. Can the test framework take care of killing the subprocesses and clean up?

**Comment by athomas** [comment]
I agree. There's poor support for doing that in Dart but it can be done by shelling out to Windows commands. Nevertheless, the test is broken on windows would be so even if the test runner was improved (it would kill it and report a timeout).

**Comment by aam** [comment]
@a-siva has https://dart-review.googlesource.com/c/sdk/+/169407 in the works that fixes the tests.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/169407 should account for the hangs.
