### ISSUE TITLE
Types "Null?" and "dynamic?" should probably be a hint/auto-fix

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#43593]
The following program produces no diagnostics:

```dart
void main() {
  Null? x = null;
  dynamic? y = null;
  print(x == y);
}
```

I imagine that `Null?` and `dynamic?` should never really happen, and are deserving of being a HINT in the analyzer.

**Comment by srawlins** [comment]
Landed a Hint in https://github.com/dart-lang/sdk/commit/d693078bbfef7bd2f5ad9735b17058271d9b28e2
