### ISSUE TITLE
[CFE] Fix incorrect extension method resolution for generics

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43591]
Per discussion in dart-lang/language#1182, there is a bug in extension method resolution in both the analyzer and the CFE. Since both front ends already have fixes essentially ready to go, I'd like to roll this out behind the null safety flag. If we need to push this off to beta 2 and roll it out as a breaking change in the feature, that's fine as well.

cc @johnniwinther

**Comment by alexmarkov** [comment]
The test `language/extension_methods/static_extension_resolution_7_test` (which was added in cd280a3f26e05ba9347df91a4b8d988d7077c507 to test this case) is still failing.
