### ISSUE TITLE
Please triage the failures on the additional nnbd VM builders

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#43597]
These tests weren't run before, so this is the initial state. @a-siva 

There are new test failures on [[infra] Add additional nnbd VM builders](https://dart-review.googlesource.com/c/sdk/+/164164).

The tests
```
samples/ffi/async/async_test CompileTimeError (expected Pass)
samples/ffi/resource_management/resource_management_test CompileTimeError (expected Pass)
samples/ffi/samples_test CompileTimeError (expected Pass)
samples/ffi/sqlite/test/sqlite_test CompileTimeError (expected Pass)
samples/sample_extension/test/sample_extension_app_snapshot_test CompileTimeError (expected Pass)
samples/sample_extension/test/sample_extension_test CompileTimeError (expected Pass)
standalone/package/package1_test CompileTimeError (expected Pass)
standalone/package/package_isolate_test CompileTimeError (expected Pass)
standalone/package/package_test CompileTimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

**Comment by dcharkes** [comment]
Am I correct in assuming we now run the `samples` both in legacy and NNBD mode? Let me see if I can migrate the files in a way such that they are accepted both in legacy and NNBD.

**Comment by athomas** [comment]
You can also fork them and make, e.g. a samples_2 or copy the individual tests and skip the legacy one on nnbd and the migrated on legacy.

**Comment by a-siva** [comment]
JIT configuration

Tests that are also similarly failing in vm-kernel-nnbd-linux-release-x64 and need to be approved
language/string/interpolation_and_buffer_legacy_test
language/variance/variance_inout_inference_test
language/variance/variance_downwards_inference_test
language/nnbd/flow_analysis/never_runtime_check_test

samples/sample_extension/test/sample_extension_app_snapshot_test
samples/sample_extension/test/sample_extension_test
samples/ffi/resource_management/resource_management_test

co19/LibTest/mirrors/before_type_param_t01
co19/LibTest/math/Rectangle/Rectangle_A03_t04
co19/LibTest/convert/ByteConversionSink/ByteConversionSink_class_A01_t01
co19/Language/Generics/typedef_A05_t04
co19/Language/Generics/typedef_A09_t03
co19/Language/Statements/Yield_and_Yield_Each/Yield_Each/execution_async_t09
co19/LibTest/async/StreamController/stream_all_A02_t03
co19/LanguageFeatures/Set-literals/disambiguating_A02_t02
co19/Language/Generics/Superbounded_types/typedef1_A01_t01/20
co19/Language/Generics/Superbounded_types/class_A01_t01/01
co19/Language/Generics/Superbounded_types/class_A01_t06/01
co19/LibTest/math/MutableRectangle/MutableRectangle_A03_t04
co19/LanguageFeatures/nnbd/tripple-shift/null_aware_operator_A15_t12
co19/LanguageFeatures/nnbd/tripple-shift/null_aware_operator_A09_t12
co19/LanguageFeatures/nnbd/tripple-shift/null_aware_operator_A11_t12
co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A01_t10
co19/LibTest/io/WebSocket/connect_A01_t02
co19/LibTest/io/Directory/statSync_A01_t05
co19/LibTest/collection/DoubleLinkedQueue/removeWhere_A02_t03
co19/Language/Classes/Superclasses/wrong_superclass_t08
co19/LanguageFeatures/Super-mixins/covariance_t07
co19/LibTest/async/Stream/Stream.periodic_all_t03
co19/LibTest/async/StreamController/stream_all_A01_t03   
co19/LibTest/async/Stream/Stream.periodic_all_t03

New Failures that need investigations (co19_2 tests are not being run against simarm targets so no comparison here)
(simarm64)
co19/LibTest/io/RawSecureServerSocket/last_A02_t01
co19/LibTest/io/RawSecureServerSocket/isEmpty_A01_t02
co19/LibTest/io/RawSecureServerSocket/single_A01_t03
co19/LibTest/io/RawSecureServerSocket/single_A02_t01

(ia32)
vm/dart/type_casts_with_null_safety_autodetection_test
vm/dart/appjit_determinism_test
vm/dart/appjit_load_static_licm_test
vm/dart/product_aot_kernel_test
lib/isolate/nnbd_spawn_autodetect_1_test
lib/isolate/detect_nullsafety_1_test

Timeout on slower bots and probably need approval (simarm)
co19/LibTest/collection/ListBase/ListBase_class_A01_t01
vm/dart/type_casts_with_null_safety_autodetection_test

**Comment by a-siva** [comment]
AOT Configuration

Tests that are also similarly failing in vm-kernel-precomp-nnbd-linux-release-x64 and need to be approved
```
language/variance/variance_downwards_inference_test
language/variance/variance_inout_inference_test
language/variance/variance_in_inference_test
language/nnbd/inference/variable_initialization_promotion_test 
language/mixin_constructor_forwarding/mixin_constructor_parameter_forwarding_test
language/variance/variance_upper_lower
language/class/override_inference_test
language/string/interpolation_and_buffer_legacy_test
language/nnbd/flow_analysis/never_runtime_check_test
language/nnbd/inference/variable_initialization_promotion_test
vm/dart/product_aot_kernel_test
standalone/io/shared_socket_test/0
standalone/io/shared_socket_test/1
```

New failures
(simarm)
`language/mixin_constructor_forwarding/const_constructor_test/issue38304 (crashes instead of RuntimeError)
`

**Comment by a-siva** [comment]
I have created two issues for the new failures

https://github.com/dart-lang/sdk/issues/43613
https://github.com/dart-lang/sdk/issues/43614

and approved the failures in the new nnbd bots, hopefully they will cycle green after this.

**Comment by a-siva** [comment]
@athomas I also noticed that in the new nnbd bots for simarm and simarm-x64 configurations we seem to be running all the co19 tests and this is not the case in the non nnbd simarm simarm-x64 configurations, is this intentional ?

**Comment by athomas** [comment]
> @athomas I also noticed that in the new nnbd bots for simarm and simarm-x64 configurations we seem to be running all the co19 tests and this is not the case in the non nnbd simarm simarm-x64 configurations, is this intentional ?

It was what's specified in go/dart-testing-unforked. The reason why the old ones aren't running it because it was too heavy to trigger this per commit. It's less of an issue to do this nightly (and the new builders are all running nightly).

**Comment by a-siva** [comment]
> > @athomas I also noticed that in the new nnbd bots for simarm and simarm-x64 configurations we seem to be running all the co19 tests and this is not the case in the non nnbd simarm simarm-x64 configurations, is this intentional ?
> 
> It was what's specified in go/dart-testing-unforked. The reason why the old ones aren't running it because it was too heavy to trigger this per commit. It's less of an issue to do this nightly (and the new builders are all running nightly).

Sounds good.

**Comment by alexmarkov** [comment]
Created https://github.com/dart-lang/sdk/issues/43711 to track migration of all `samples/`.

**Comment by a-siva** [comment]
We have created issues for what was considered as unique failures in the various new bots and results of the other failures were approved (same as existing configurations). Closing this issue.
