### ISSUE TITLE
Compile-time error message for nullable->non-nullable is hard to understand

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#43592]
I _believe_ this is the CFE:

```
Error: The argument type 'HtmlElement?' can't be assigned to the parameter type 'Object'.
 - 'HtmlElement' is from 'dart:html'.
 - 'Object' is from 'dart:core'.
    this.initRootNode(_el_0);
```

It took me quite a while to realize the reason I couldn't assign `HtmlElement` to `Object` is it was `HtmlElement?`.

I think the error message should note that prominently (more than assuming I saw the `?` in the first line).

**Comment by johnniwinther** [comment]
@stefantsov Maybe we should special-case the message when there is a difference between subtyping with and ignoring nullabilities.

**Comment by stefantsov** [comment]
Yes, we have the machinery to do that without additional computation (the tri-state isSubtypeOf).  But I guess we need to agree on the text of the new message with the Analyzer.  I tried to run both of the tools over the following program:

```dart
class A {}

class B extends A {}

foo(A a) {}

bar(B? b) {
  foo(b);
}
```

The CFE gives the following:

```
/tmp/asdf.dart:8:7: Error: The argument type 'B?' can't be assigned to the parameter type 'A'.
 - 'B' is from '/tmp/asdf.dart'.
 - 'A' is from '/tmp/asdf.dart'.
  foo(b);
      ^
```

The Analyzer gives the following:

```
Analyzing /tmp/asdf.dart...
  error • The argument type 'B?' can't be assigned to the parameter type 'A'. • /tmp/asdf.dart:8:7 • argument_type_not_assignable
1 error found.
```

So right now both tools produce the same compile-time error.

**Comment by johnniwinther** [comment]
@devoncarew we need to coordinate a better message for nullability-only subtype/assignment problem. Who should handle the changes in the analyzer?

@matanlurey What message would you have helped you in this situation? Would it suffice to augment the message with something like "because 'HtmlElement?' is nullable and 'Object' is not nullable" ?

**Comment by devoncarew** [comment]
wrt error messages, I would coordinate with @bwilkerson.

**Comment by matanlurey** [comment]
@johnniwinther I think nullability should be called out explicitly if that is the reason for the invalid assignment:

```
The argument type `HtmlElement?` can't be assigned to the parameter type `Object`:
  - `HtmlElement?` is nullable
  - `Object` is not nullable

See dart.dev/understanding-null-safety#cannot-be-assigned for details.
```

**Comment by matanlurey** [comment]
(Or notionally like that, I admit I am not good at writing error messages either!)

**Comment by stefantsov** [comment]
> I think nullability should be called out explicitly if that is the reason for the invalid assignment:
> 

Yes, this error message reads much better than what we currently have.  But what should the tools report when the nullability doesn't match on a deeper level of a compound type, for example, in case of `List<HtmlElement?>` vs `List<Object>`?  One possibility is to say that a part of one type is nullable and the corresponding part of the other type is not nullable.

```
The argument type `List<HtmlElement?>` can't be assigned to the parameter type `List<Object>`:
  - part `HtmlElement?` of type `List<HtmlElement?>` is nullable
  - corresponding part `Object` of type `List<Object>` is not nullable

See dart.dev/understanding-null-safety#cannot-be-assigned for details.
```

Of course, when the nullability issue happens at the top level of a type, the message can mention types as a whole, not their parts.

@bwilkerson WDYT?

**Comment by stefantsov** [comment]
The proposed fix for the issue is here: https://dart-review.googlesource.com/c/sdk/+/168860/.
