### ISSUE TITLE
Dart and analyzer produces different types for typedef G<X, Y extends X> = X Function(Y)

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#43599]
Dart SDK version: 2.11.0-161.0.dev (dev) (Thu Sep 24 17:00:45 2020 -0700) on "windows_x64"

Here is a test example:
``` dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => <Y extends X>() {};

typedef G<X, Y extends X> = X Function(Y);

test(G source) {
  var fsource = toF(source);

  F<G<dynamic, Never>> target = fsource;
  F<G<dynamic, dynamic>> target3 = fsource;
}

main() {}
```
Both analyzer and dart throw a compile error here, but for the different lines:  dart treats `G<dynamic, Never>` as a correct declaration and throws a compile error for `G<dynamic, dynamic>` whereas analyzer produces opposite result, all checked with nnbd turned on.

Both tools should behave in the similar ways.

Sample output is:

> $> dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error - A value of type 'void Function<Y extends dynamic Function(dynamic)>()' can't be assigned to a variable of type 'void Function<Y extends dynamic Function(Never)>()'. - test.dart:9:33 - invalid_assignment
>   hint - The value of the local variable 'target' isn't used. - test.dart:9:24 - unused_local_variable
>   hint - The value of the local variable 'target3' isn't used. - test.dart:10:26 - unused_local_variable
> 1 error and 2 hints found.
> 
> $> dart --enable-experiment=non-nullable test.dart
> test.dart:10:36: Error: A value of type 'void Function<Y extends dynamic Function(Never)>()' can't be assigned to a variable of type 'void Function<Y extends dynamic Function(dynamic)>()'.
>   F<G<dynamic, dynamic>> target3 = fsource;

**Comment by eernstg** [comment]
I believe the discrepancy has been eliminated by https://dart-review.googlesource.com/c/sdk/+/164860, where the analyzer starts using the variance of type parameters during i2b. Did you try to run it with a fresh `dartanalyzer`? I get an error on line 10 from the analyzer (as well as the CFE) with a dartanalyzer from 8b567447dc93a08603a273d610edcfa8cefd6539.
