### ISSUE TITLE
There is a compilation performance issue after update to 2.8.4 sdk

### ISSUE THREAD

**Issue by svarl** [dart-lang/sdk#43598]
We have a large project. We've migrated the project from 2.7.2 to 2.8.4 version. And after it we've faced with a compilation performance issue. Project builds have taken a lot longer after upgrade (+3m14s or +18%). 

There are two samples:

Before update (dart sdk 2.7.2):
```
Compiled 99,450,093 characters Dart to 24,501,614 characters JavaScript in 332 seconds
Info: 5,458,280 characters JavaScript in web/wrike_ws.dart.js
Emitted file 358 JavaScript files.
...
[INFO] Succeeded after 18m 12s with 81926 outputs (310180 actions)
```

After update (dart sdk 2.8.4):
```
Compiled 99,684,061 characters Dart to 24,448,699 characters JavaScript in 340 seconds
Info: 5,410,649 characters JavaScript in web/wrike_ws.dart.js
Dart file web/wrike_ws.dart compiled to JavaScript: web/wrike_ws.dart.js
Emitted file 359 JavaScript files.
...
[INFO] Succeeded after 21m 26s with 81928 outputs (310174 actions)
```

What can we do with it? If it's required we can provide more information about our project.

**Comment by mnordine** [comment]
First of all, looks like you're not comparing apples to apples. Are you sure you're compiling the exact same code? Your character count says otherwise.

And what about latest stable release, `2.9.3`?

**Comment by svarl** [comment]
Looks like there is no problem on 2.10.0 sdk 

```
----- 2.7.2
Compiled 99,518,496 characters Dart to 24,521,532 characters JavaScript in 334 seconds
[INFO] Succeeded after 18m 46s with 81992 outputs (310467 actions)

----- 2.10.0
Compiled 99,860,110 characters Dart to 24,153,148 characters JavaScript in 302 seconds
[INFO] Succeeded after 19m 5s with 82000 outputs (310461 actions)
```

I think I can close the issue
