### ISSUE TITLE
offer a quick fix to remove dead code (code that's now a no-op due to null safety)

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43604]
After some null safe migrations, I see several places in my code where null checks are now dead code:

```
The operand can't be null, so the condition is always true.
Remove the condition.
```

<img width="402" alt="Screen Shot 2020-09-29 at 9 22 54 AM" src="https://user-images.githubusercontent.com/1269969/94585856-6bcc3780-0235-11eb-8bae-46ef9a68ec04.png">

We should offer a quick fix to remove these.

**Comment by bwilkerson** [comment]
We have a fix for some forms of dead code, but either it isn't associated with the specific diagnostic or it doesn't handle the specific case.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/165481

**Comment by devoncarew** [comment]
Thanks!
