### ISSUE TITLE
Sound null safety opt in does not respect experiment release versions

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#43605]
See https://travis-ci.org/github/dart-lang/fixnum/jobs/731298814 - this test is failing because it is not opted in when it should be.

I have confirmed this happens on both dart2js and the vm (you can test dart2js by running with `-p chrome`), so assigning to area-front-end for now under the assumption it is a cfe issue, but we may instead need two separate issues for the backends.

The test is running on the 2.11 dev sdk, and has a language version of `2.10`. This _should_ opt it in because the experiment release version for null safety is `2.10`, so the entrypoint _is_ opted in.

cc @a-siva @fishythefish for vm/dart2js

**Comment by johnniwinther** [comment]
I cannot reproduce this. Using `2.11.0-161.0.dev` I just get "All tests passed!". Without `--enable-experiement=non-nullable` I _do_ get the errors shown in the log. Since `pub` automagically calls `dart` the problem might be in how this is done.

**Comment by jakemac53** [comment]
Oh, I landed a change to update the language version to 2.11 in order to get us unblocked, so if you tried running the tests in that package at head you will need to remove the language version override comments from the test to repro.
