### ISSUE TITLE
quick fix to convert `@required` to `required`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43603]
When migrating code to null safety, I see error messages around `@required` parameters, in this case used in the definition of Flutter widgets:

```
The parameter 'title' can't have a value of 'null' because of its type, and no non-null default value is provided.
Try adding either a default value or the 'required' modifier.
```

<img width="969" alt="Screen Shot 2020-09-29 at 9 05 02 AM" src="https://user-images.githubusercontent.com/1269969/94583972-eb0c3c00-0232-11eb-9b0e-4a480e2ecd13.png">

The fix is to change the `@required` annotation to a `required` keyword. It would be great to offer a quick fix for this.

cc @pq @bwilkerson

**Comment by bwilkerson** [comment]
We have a fix to add the required keyword. We might want to enhance it to remove the annotation (after ensuring that we're treating a required keyword as if it were a required annotation when analyzing code in opted out libraries).

We might also want a hint/lint to flag uses of the annotation in opted-in libraries.

**Comment by bwilkerson** [comment]
Not that it's also possible that the fix isn't associated with the diagnostic shown above.

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/171420
