### ISSUE TITLE
[nnbd/ffi] Migrate samples when NNBD is available in stable release

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#43600]
When NNBD is available in the stable release, we should migrate the samples in https://github.com/dart-lang/sdk/tree/master/samples/ffi to NNBD (and remove them from legacy bots).

Triaging issue: https://github.com/dart-lang/sdk/issues/43597

Alternatively, duplicate the samples.

**Comment by a-siva** [comment]
@dcharkes your comment states when NNBD is available in a stable release .... do you think it is worth considering this for the beta release when the experimental flag is being turned on by default.
