### ISSUE TITLE
Unclear where to put --enable-experiment

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#43623]
I've made this error several times now: I put the `--enable-experiment` flag in the wrong place in the command line tool, and then I'm confused. For example:

1. Migrate a library to null safety
2. Run `pub --enable-experiment=non-nullable run test` (I put the flag as close to the "top" as possible because I assume that's where it belongs.)

I get this error:

    Could not find an option named "enable-experiment".

The first time this happened, I just assumed `pub` doesn't yet support null safety, so I ran `dart --enable-experiment=non-nullable test/xyz_test.dart` instead. But, in fact, the correct invocation is `pub run --enable-experiment=non-nullable test`. This runs fine.

I was even more confused when trying to use the new `dart compile exe` command, as evidenced in https://github.com/dart-lang/sdk/issues/43594. That command doesn't complain about a missing option named "enable-experiment", and it has 3 places to place a flag, compared to the two here.

* Dart SDK Version (`dart --version`)

  Dart SDK version: 2.10.0-110.0.dev (dev) (Wed Sep 9 17:51:43 2020 -0700) on "macos_x64

* Whether you are using Windows, MacOSX, or Linux (if applicable)

  MacOSX

cc @mit-mit

**Comment by mit-mit** [comment]
cc @bkonyi

**Comment by dragonfax** [comment]
I too would like to enable null-safety in my executables. This was added to `dart2native` back in august. It seems to be missing from `dart compile exe`

**Comment by bkonyi** [comment]
It looks like we're not giving an error since `--enable-experiment` is a global option for the CLI. Even though we haven't added experiment support for the `compile` command yet, we're not failing because parsing is successful but we're just ignoring what we parsed. We should probably cleanup all references to `--enable-experiment` in subcommands except for the global option.
