### ISSUE TITLE
[fuchsia] Propagate UTC clock when spawning processes

### ISSUE THREAD

**Issue by adamlesinski** [dart-lang/sdk#43629]
Fuchsia is transitioning away from tracking UTC time in the kernel to tracking UTC time as a userspace clock object. In order to have access to this clock object (and UTC time), it must be propagated whenever a new process is created.

This is done via the helper API `fdio_spawn_vmo` and the new flag `FDIO_SPAWN_CLONE_UTC_CLOCK`.

**Comment by mit-mit** [comment]
cc @a-siva, not entirely clear what the Dart change for this is?

**Comment by adamlesinski** [comment]
I made the change here: https://dart-review.googlesource.com/c/sdk/+/165500

**Comment by mit-mit** [comment]
Ah, thanks

**Comment by a-siva** [comment]
that cl has landed so closing this issue.
