### ISSUE TITLE
Front end expectation-file update script should be mentioned in error reports.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#43633]
These tests fail because the output doesn't match a "golden" expect file, not because there is anything wrong.

When using golden files that contain *anything* outside of the test itself (even if it's a reference to `Object::hashCode`), you *must* provide a script that can update the file, and link to that script in the test failure message.
Even if it's only running `git apply` on the error text in some directory and with some set of parameters, specify which. The updating of the files must be automatable by someone with no understanding of your tests. (The only real alternative is that they simply mark your tests as failing and let you fix it).

There are new test failures on [Add documentation to the `Type` class.](https://dart-review.googlesource.com/c/sdk/+/108804).

The tests
```
pkg/front_end/test/fasta/fast_strong/general/error_recovery/issue_26810 Fail (expected Pass)
pkg/front_end/test/fasta/fast_strong/general/expressions Fail (expected Pass)
pkg/front_end/test/fasta/fast_strong/rasta/type_literals Fail (expected Pass)
pkg/front_end/test/fasta/fast_strong/rasta/typedef Fail (expected Pass)
pkg/front_end/test/fasta/strong/general/error_recovery/issue_26810 Fail (expected Pass)
pkg/front_end/test/fasta/strong/general/expressions Fail (expected Pass)
pkg/front_end/test/fasta/strong/rasta/type_literals Fail (expected Pass)
pkg/front_end/test/fasta/strong/rasta/typedef Fail (expected Pass)
pkg/front_end/test/fasta/text_serialization/general/error_recovery/issue_26810 Fail (expected Pass)
pkg/front_end/test/fasta/text_serialization/general/expressions Fail (expected Pass)
pkg/front_end/test/fasta/text_serialization/rasta/type_literals Fail (expected Pass)
pkg/front_end/test/fasta/text_serialization/rasta/typedef Fail (expected Pass)
pkg/front_end/test/fasta/weak/general_nnbd_opt_out/expressions Fail (expected Pass)
```
are failing on configurations
```
cfe-unittest-asserts-release-linux
```

**Comment by johnniwinther** [comment]
There is a script but we don't mention it and we should.
