### ISSUE TITLE
I don't understand python2 virtual env setup

### ISSUE THREAD

**Issue by zmdk0913** [dart-lang/sdk#43635]
I found this command 
virtualenv .env -p python2
$ source .env/bin/activate
# Can now run Dart SDK build scripts
but i don know how to run dart sdk build scripts.

**Comment by mit-mit** [comment]
@zmdk0913 can you clarify what you are trying to do? Is this related to https://github.com/dart-lang/sdk/issues/43634 ?

**Comment by mit-mit** [comment]
closing as unactionable
