### ISSUE TITLE
Failures new nnbd VM builders on mac host 

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#43630]
There are new test failures on [[infra] Add additional nnbd VM builders](https://github.com/dart-lang/sdk/commit/c3d37c1ad6d937a9cef1c1e4579f3ca4090fab72)

`vm/dart/thread_priority_macos_test`

**Comment by a-siva** [comment]
Another failure` standalone/io/shared_socket_test/0`

**Comment by a-siva** [comment]
Another failure `co19/LibTest/io/Link/watch_A01_t01`

**Comment by alexmarkov** [comment]
`vm/dart/thread_priority_macos_test` is currently passing.
`standalone/io/shared_socket_test/0` is flaky both on NNBD and non-NNBD bots.
`co19/LibTest/io/Link/watch_A01_t01` is currently failing both on NNBD and non-NNBD bots.
