### ISSUE TITLE
[analyzer] Test failure implies missing promotion based on initialization

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#43649]
This is the analyzer specific issue for #43647, which has the details.

**Comment by srawlins** [comment]
Er, the epic, #43647, is closed. This is complete then?

**Comment by eernstg** [comment]
@stereotype441, I'm closing this issue: The test `language/nnbd/inference/variable_initialization_promotion_test.dart` has no failures today, which is the topic of #43647. This is also consistent with [this comment](https://github.com/dart-lang/sdk/issues/43647#issuecomment-705590173).
