### ISSUE TITLE
[cfe] Test failure implies missing promotion based on initialization

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#43648]
This is the CFE specific issue for #43647, which has the details.

**Comment by stereotype441** [comment]
language/nnbd/inference/variable_initialization_promotion_test.dart is passing on all platforms except web as of e933e91aaa29531ccb32d5adec853270eedbedae.  I believe the web problem is unrelated to flow analysis, and I'm tracking it in https://github.com/dart-lang/sdk/issues/43723.
