### ISSUE TITLE
can't build or serve web app with 2.10

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#43659]
when I do a pub get with 2.10 it upgrades dart_internal to nullsafety:

```
pub get
Resolving dependencies... (1.9s)
> dart_internal 0.1.12-nullsafety (was 0.1.10)
```

then I try to serve with pub build_runner:

```
pub run build_runner serve web:8091

[INFO] Building new asset graph completed, took 3.7s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] build_web_compilers:ddc on package:dart_internal/extract_type_arguments.ddc.module:
Error compiling dartdevc module:dart_internal|lib/extract_type_arguments.ddc.js

packages/dart_internal/extract_type_arguments.dart:25:7: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
Object? extractIterableTypeArgument(
```

if I go back to 2.9.3 and do a pub get:

```
pub get
Resolving dependencies... (2.7s)
< dart_internal 0.1.10 (was 0.1.12-nullsafety)
``` 

then my build_runner works again

**Comment by mit-mit** [comment]
You likely need a new version of `build_runner`; did you try to try `pub upgrade`?

**Comment by jodinathan** [comment]
I remember doing the pub upgrade, but I am not sure.
Later this day I will try to change some versions and see what happens

**Comment by mit-mit** [comment]
If you get a repro, please share the `pubspec.yaml` file.

**Comment by jakemac53** [comment]
I agree that it sounds like you need to upgrade your packages - specifically you will need `build_web_compilers` version `2.10.0` or greater.

**Comment by jodinathan** [comment]
It worked after upgrading ```build_web_compilers```.
