### ISSUE TITLE
Incorrect sorting of Ukrainian alphabet

### ISSUE THREAD

**Issue by alekseichuk** [dart-lang/sdk#43668]
The problem occures if to sort a list of strings in Ukrainian.
 
I encountered this issue on Windows, though the snippet of the code below was tested in dartpad.dev and it occures there too.

```
void main() {
  // Ukrainian alphabet pre-ordered, taken from https://en.wikipedia.org/wiki/Ukrainian_alphabet
  var ukrainianAlphabet = "а,б,в,г,ґ,д,е,є,ж,з,и,і,ї,й,к,л,м,н,о,п,р,с,т,у,ф,х,ц,ч,ш,щ,ь,ю,я";  
  
  var original = ukrainianAlphabet.split(",");
  var sorted = ukrainianAlphabet.split(",")..sort();
  
  print(original);
  print(sorted); // So letters є, і, ї, ґ sunk to bottom of the list.
}
```

Thanks.

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
Dart string ordering is not locale aware, it just sorts lexically by code units. 
So, this is expected behavior.

I'm not aware of a way to get an ordering (`Comparator`) for strings which is locale aware, or specialized to specific alphabets, though, so I can't point to a solution.

**Comment by mmalkush** [comment]
+1

**Comment by mraleph** [comment]
If you are targeting web you can use `Intl.Collator` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator) through JS interop. 

Unfortunately I don't think there is anything ready made for any other platform. You would need to use FFI to bind to a library like ICU.

**Comment by pavloslav** [comment]
Non-English sorting is PAIN :(

**Comment by lrhn** [comment]
For the record, so is sorting English, since it has accents, foreign proper names, and ... well ... both upper and lower case letters!

The standard string ordering is a total ordering of strings, no more and no less. It's completely unaware of what the contents actually mean.
