### ISSUE TITLE
[CP][stable channel] revert previous cherry-pick for DDC

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#43661]
**commit(s) to merge**: 350481a93cd6e9e8c5e387f3feca80f6beb2178a (https://dart-review.googlesource.com/c/sdk/+/165873 in the CQ, which reverts 53895b2)

**merge instructions**: expect a clean merge

**What is the issue**: A fix of a previous issue that we cherry-picked introduced additional problems.

**What is the fix**: Revert the previous cherry-pick (#43453) and work on an alternative solution to the original problem.

**Why cherrypick**: We think removing the old cherry-pick is a safer path forward.

The bug in question has existed for years, only recently a flutter package with unique code-generation patterns triggered the bug (https://github.com/flutter/flutter/issues/64011). The fix revealed new failures like (https://github.com/flutter/flutter/issues/66859) that affect simpler packages and we are afraid the scope of the failures could potentially be a lot wider. To prevent further regressions and disruptions, we prefer to remove the earlier "fix" until we find a proper solution.

**Risk**: Low, this brings the behavior back to what it was before.

**Link to original  issue(s)**: 
https://github.com/flutter/flutter/issues/64011 - the original problem
https://github.com/flutter/flutter/issues/66859 - an example new problem from the earlier fix

The intent is to include this in the next 2.10.0 stable hotfix release

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @Markzipan

**Comment by franklinyow** [comment]
Is this a revert of #43453 ?
@sigmundch Please fix the title.  I can approve this after the CL merged

**Comment by sigmundch** [comment]
Precisely.

Sorry I missed the title, I just updated it.

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved

**Comment by franklinyow** [comment]
close
