### ISSUE TITLE
Let's make new Feature ?== or ??=

### ISSUE THREAD

**Issue by Hellomik2002** [dart-lang/sdk#43664]
```
a == null ? null : something(a)
```
let's change to 
```
a ?== something(a)

```
it is a little fun feature like this
```
a ?? false
```

**Comment by znjameswu** [comment]
FYI, ??= is an existing operator for nullable assignment.

**Comment by mit-mit** [comment]
Yes, I think you are describing the current null-aware assignment operator:
https://dart.dev/guides/language/language-tour#assignment-operators

```dart
// Assign value to a
a = value;
// Assign value to b if b is null; otherwise, b stays the same
b ??= value;
```

**Comment by Hellomik2002** [comment]
```final a = null``` or ```'some string'``` 
I don't want to assign value to ```a```,
I mean 
```final c = a == null ? null : something(a)```
use like
```final c  = a ?== something(a)```
```??=``` can not change value of ```final``` variable

**Comment by mit-mit** [comment]
Sorry, I don't understand. Can you specify in a bit more detail what the semantics of this proposed construct are?

**Comment by eernstg** [comment]
I think the proposal is to have syntax for evaluating `something(a)` if `a` is non-null, like

```dart
((v) => v != null ? something(v) : null)(a)
```

and, in general, to enable "subexpression null shorting" in the sense that an expression is evaluated only if certain subexpressions are non-null.

We have had some discussions about this before (but there doesn't seem to be an issue specifically on that, so it must have been individual comments in other discussions, e.g., [this one](https://github.com/dart-lang/language/issues/219#issuecomment-476720274)).
