### ISSUE TITLE
Prevent dart reformart with better align ext in VS code

### ISSUE THREAD

**Issue by InuyasaDev** [dart-lang/sdk#43671]
I use "better align" extension to align colon, assignment and arrow.
How to prevent "dart" to reformat document?
or can I custom reformatting code?

Thank you

![Screenshot_1](https://user-images.githubusercontent.com/72384450/95065697-9afa1180-072b-11eb-8481-b4351dfc0690.png)

![Screenshot_2](https://user-images.githubusercontent.com/72384450/95065747-a8af9700-072b-11eb-93e6-af601bd05e48.png)

**Comment by mit-mit** [comment]
You generally can't. The [dart formatter](https://dart.dev/tools/dartfmt) is designed to apply whitespace formatting according to the Dart guidelines, and they don't have a concept of aligning like that.
