### ISSUE TITLE
[dartdevc] Add location of full dill file to the metadata

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#43684]
The debugger needs to read full metadata for expression evaluation feature. Currently debugger assumes that the full dill file has a .full.dill extension and is located next to the produced .js file. 

Add this information to the metadata file instead to prevent debugger from breaking on dartdevc or build_web_compilers changes.

**Comment by nshahan** [comment]
@annagrin

Does it make sense to use `--experimental-emit-debug-metadata` without `--experimental-output-compiled-kernel`? In my WIP change I added an assert that if you pass the metadata flag you also pass the flag to output a full dill. I am seeing that some of the javascript tests from `frontend_server_test.dart` are not passing through the flag for the full dill file when compiling to JS.

Would it be better for DDC to write `'fullDillUri' : null` if it was invoked without the `--experimental-output-compiled-kernel` flag?

**Comment by annagrin** [comment]
@nshahan frontend server does not need to read full dill files, as it has full kernel of the whole app in memory at all times, so there is no need to produce them in the ddc compilation (in order to save time).
