### ISSUE TITLE
IDE auto-completion suggests the same class 2 or more times

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#43680]
![image](https://user-images.githubusercontent.com/168174/95124925-08e11180-0709-11eb-9e40-52a63a98757a.png)

I realize there are cases where it's ambiguous where to import a symbol (such as in Flutter where tons of classes and types are exported through multiple libraries), but if the class is _already_ in scope (i.e. already imported), suggesting to import _another_ library to access it ... seems wrong:

![image](https://user-images.githubusercontent.com/168174/95124984-29a96700-0709-11eb-90b8-8179dbfc5c5e.png)

**Comment by DanTup** [comment]
@matanlurey can you still reproduce this? I can reproduce it if there are two classes with the same name, but when they're the same underlying class (exported from multiple files), I only see one. I'm using latest code with LSP enabled.

Without an import:

<img width="1344" alt="Screenshot 2021-03-02 at 12 24 23" src="https://user-images.githubusercontent.com/1078012/109648257-52b41380-7b52-11eb-9cda-d3952c7c7714.png">

With an import:

<img width="1345" alt="Screenshot 2021-03-02 at 12 24 36" src="https://user-images.githubusercontent.com/1078012/109648281-56e03100-7b52-11eb-976e-137176b308fe.png">

**Comment by srawlins** [comment]
You already opened this here: https://github.com/dart-lang/sdk/issues/37075

**Comment by CMMT20** [comment]
> @CMMT20 That sounds like a separate issue than the issue of suggesting a class twice rather than once. Please file a new issue for this request.

Yeah, you are right, thanks for the warning.

**Comment by CMMT20** [comment]
@srawlins you are right, sorry and thanks for the warning
