### ISSUE TITLE
[CP][stable channel] Fix for VM crash with type mis-match https://github.com/dart-lang/sdk/issues/43464

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#43685]
commit(s) to merge: [68fd2a9](https://dart.googlesource.com/sdk/+/68fd2a9d52802bdcc2db31d9b31a2e128b392f30)

merge instructions: clean merge

What is the issue: type assumption could lead to unsound optimizations. This leads to program crashes when flutter users are developing applications.  

What is the fix: The code was reworked to make pessimistic type assumptions that will not lead to unsound optimizations.

Why cherrypick: Flutter users can hit this bug which developing applications resulting in crashes that could be hard to diagnose down to this issue, the fix itself is small and safe.

Risk: Low risk, patch is self-contained as validated for some time.

Link to original issue(s): https://github.com/dart-lang/sdk/issues/43464

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by vsmenon** [comment]
Have we validated that this commit rolled successfully into Flutter master and into g3?

**Comment by a-siva** [comment]
The change has rolled into flutter and google3 (the last google3 roll done today was with dart version [9560a32779](https://github.com/dart-lang/sdk/commit/9560a32779fc966349dd2d719b76aee49fb6a1de) which includes this change

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved
