### ISSUE TITLE
Dart rejects B<X extends A<A<X>>>

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#43687]
Dart SDK version: 2.11.0-180.0.dev (dev) (Tue Sep 29 19:40:19 2020 -0700) on "windows_x64"

This issue is similar with #34726, but it's against dart, and #34726 is against analyzer.

Please note that issue #34264 mentioned in #34726 comments is not reproducible now as well as issue #34948.

Here is a source code example:
``` dart
class A<X extends A<X>> {}
class B<X extends A<A<X>>> {}
main() {}
```
Seems like the test should pass, however dart throws a compile error here.

Sample output is:
> test.dart:2:9: Error: Type argument 'A<X/*1*/>' doesn't conform to the bound 'A<X/*2*/>' of the type variable 'X' on 'A'.
>  - 'A' is from 'test.dart'.
>  - 'X/*1*/' is from 'test.dart'.
>  - 'X/*2*/' is from 'test.dart'.
> Try changing type arguments so that they conform to the bounds.
> class B<X extends A<A<X>>> {}
>         ^
> test.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
> class A<X extends A<X>> {}
>         ^
> test.dart:2:9: Error: Type argument 'X/*1*/' doesn't conform to the bound 'A<X/*2*/>' of the type variable 'X' on 'A'.
>  - 'X/*1*/' is from 'test.dart'.
>  - 'A' is from 'test.dart'.
>  - 'X/*2*/' is from 'test.dart'.
> Try changing type arguments so that they conform to the bounds.
> class B<X extends A<A<X>>> {}
>         ^
> test.dart:1:9: Context: This is the type variable whose bound isn't conformed to.
> class A<X extends A<X>> {}
>         ^

Failing co19 test is: LanguageFeatures/Instantiate-to-bound/class/static/class_l1_t04.dart

**Comment by eernstg** [comment]
I do not think we can prove `X <: A<X>` using only the assumption `X <: A<A<X>>`, which makes it correct to report this compile-time error. @iarkh, why should we expect that property to hold?

**Comment by lrhn** [comment]
Not only can we not prove that `X <: A<A<X>>` implies `X <: A<X>`, we can disprove it.
```dart
class A<X> {
  X get value;
}
class D implements A<C> {
  C get value => C();
}
class C implements A<D> {
  C get value => D();
}
X f<X extends A<A<X>>(X value) => g(value); // If we allowed it.
X g<X extends A<X>>(X value) => value.value;
/// 
main() {
  C value = f<C>(C());  // ~~ g(C()) ~~ C().value ~~ D()  // would assign D to C, so not sound.
}
```

That is, `X = C <: A<D> <: A<A<C>>` satisfies `C <: A<A<C>>`, but `C <: A<C>` is not true.

**Comment by eernstg** [comment]
Class `A` should be abstract, otherwise I think it works.

**Comment by lrhn** [comment]
Hereby abstracted.
