### ISSUE TITLE
FFI: Wrong alignment of Uint64 on Android x86 simulator

### ISSUE THREAD

**Issue by nmbus** [dart-lang/sdk#43693]
Hi,

I am currently making a plugin using dart:ffi, and testing the latter with a C struct like this:
```
struct MyStruct {
    OtherStruct* pSomePtr;
    uint64_t someValue;  
}
```
(size of 12 on x86 Android emulator).

with its (unless I misunderstood how to make them ?) dart:ffi alter ego:
```
class MyStruct extends Struct {
  Pointer<OtherStruct> somePtr;

  @Uint64()
  int someValue;
}
```

Causes the 'someValue' to contain bogus values after being returned from C to a FFI Struct, or after being passed as an argument to C after being allocated on the Dart side, e.g. setting the someValue field to "0xAAAAAAAABBBBBBBB" on the Dart side gives "0xBBBBBBBBFFFFFFFF" on the C side, and does the same the other way around.
Seems to me it is an alignment issue, as forcing the uint64 field to be aligned at 8 bytes, or flipping the order of the arguments (uint64 first, pointer next) fixes the issue.

**Comment by dcharkes** [comment]
Thanks for reporting, I'll investigate.

**Comment by dcharkes** [comment]
@nmbus what host OS are you using? Windows by any chance?

The constants used for alignment check for Windows vs non-windows (MacOS/Linux/Android/iOS), but they don't use the `TARGET_OS` macros.

https://github.com/dart-lang/sdk/blob/a80f9d7da84ef0549e1d52b4044ba2ae6a7e79ba/runtime/vm/constants_ia32.h#L251-L257

Some manual testing:

```c
struct MyStruct {
  void* pSomePtr;
  uint64_t someValue;
};

DART_EXPORT intptr_t Int64StructField() {
  return offsetof(struct MyStruct, someValue);
}
```

This returns 4 on an android x86 emulator.
This returns 8 on Windows x86.
This returns 4 on Linux x86.

On Windows, the alignment should be 8, on all other OSes, the alignment should be 4.

@nmbus is your host OS indeed Windows?

If so, it's a similar issue to https://github.com/dart-lang/sdk/issues/42185.

**Comment by nmbus** [comment]
Hi,

No my Host OS is MacOS 10.15.7 Catalina.

**Comment by dcharkes** [comment]
I'm able to repro it on multiple ABIs, and have a fix https://dart-review.googlesource.com/c/sdk/+/166843.

This only affected `uint64_t` not `int64_t` as it was missing from the alignment rules in the compiler.

Affected ABIs: ia32 Linux, ia32 Android, ia32 MacOS, and arm32 iOS.
