### ISSUE TITLE
language/nnbd/flow_analysis/never_runtime_check_test is failing

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#43707]
After https://github.com/dart-lang/language/issues/1143 was fixed, the test `language/nnbd/flow_analysis/never_runtime_check_test` is still failing in weak mode with runtime error on the VM, DDC and dart2js: https://dart-ci.firebaseapp.com/current_results/#/filter=language/nnbd/flow_analysis/never_runtime_check_test

```
Unhandled exception:
Expect.throws fails: Did not throw
#0      Expect._fail (package:expect/expect.dart:704:5)
#1      Expect.throws (package:expect/expect.dart:593:5)
#2      main (file:///b/s/w/ir/tests/language/nnbd/flow_analysis/never_runtime_check_test.dart:25:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-weak-asserts-linux-release-x64 language/nnbd/flow_analysis/never_runtime_check_test
```

It looks like the test was not updated after changing behavior in the front-end.

@stereotype441 @johnniwinther @leafpetersen @lrhn

**Comment by johnniwinther** [comment]
The test needs update. I'll fix it.

**Comment by stereotype441** [comment]
> The test needs update. I'll fix it.

Thanks Johnni!
