### ISSUE TITLE
[CP][beta channel] Fix for DDC crash (second attempt)

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#43705]
**commit(s) to merge**: 38667e5667788afab883d80b4cb7e85e619aa4ef

(we are not sure if the hash for beta was already selected. We'd like https://github.com/dart-lang/sdk/issues/43661 and this to be included in the next beta release)

**merge instructions**: clean merge

**What is the issue**: DDC had an old undiscovered bug. A certain rare code pattern triggers the issue and in that case the app cannot be loaded for development (the code crashes while loading). The pattern involves an inheritance chain that forms a cycle between classes and type parameters.

Recently a Flutter Web app encountered this pattern and started hitting this issue (https://github.com/flutter/flutter/issues/64011). Our first fix was simple but unfortunately revealed other issues (https://github.com/flutter/flutter/issues/66859) and had to be reverted.

The new fix takes a different approach and we believe it to be lower risk than the first.

**What is the fix**: The compiler has logic to break cycles by generating multiple lines for a class declaration. These multiple lines, however, were computed eagerly. The eager code generation was not necessary and it was the reason why some declarations were still out of order in the output. The fix was to ensure the compiler deferred generating the code as well, so that it is created at the time it would be emitted.

**Why cherrypick**: We only know of one affected customer, but the result makes the product unusable in that case.

**Risk**: low - unlike the previous fix, the change no longer changes the content of what's emitted, only the order.

**Link to original  issue(s)**: https://github.com/flutter/flutter/issues/64011, https://github.com/flutter/flutter/issues/66859

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @pcsosinski

**Comment by franklinyow** [comment]
1. igure out if this is already in the hash 
2. Let's validate the fix and come back

**Comment by sigmundch** [comment]
Re (2) - the original user that reported the issues has verified that the fix works, see https://github.com/flutter/flutter/issues/66859#issuecomment-705764523

**Comment by pcsosinski** [comment]
we haven't branched for the October 2.11 beta yet.

**Comment by sigmundch** [comment]
Sounds like we are branching off from https://github.com/dart-lang/sdk/commit/e256855d07ba9cad5048f012f38a05446ca2fe09, which I believe includes this commit, if so @athomas feel free to close this issue.

@athomas - btw, I noticed that the tag 2.11.0-213.0.dev is not recorded in the git repo, so I couldn't verify as easily that the cherry-pick commit above was actually already in that tag.
