### ISSUE TITLE
Analyzer highlights wrong span for "must be null-checked"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#43708]
![Screen Shot 2020-10-07 at 11 20 23 AM](https://user-images.githubusercontent.com/168174/95371480-1c1de980-088f-11eb-9f9a-aebf136794e9.png)

This was/is fixable by null-asserting `querySelector`, _not_ `rootElement`:

![Screen Shot 2020-10-07 at 11 20 23 AM](https://user-images.githubusercontent.com/168174/95371558-3657c780-088f-11eb-87a5-d7fc6411fce2.png)

![Screen Shot 2020-10-07 at 11 21 01 AM](https://user-images.githubusercontent.com/168174/95371561-36f05e00-088f-11eb-8f89-fc22b500d649.png)

**Comment by srawlins** [comment]
I think I have a minimal repro here:

```dart
class C {
  D d() => D('');
}

class D {
  String? s;
  D(this.s);
}

main() {
  C()..d()
    .s.length;
}
```

The highlighted region is between `>>>` and `<<<`:

```
main() {
  C()>>>..d()
    .s.length;<<<
}

**Comment by srawlins** [comment]
Oops, I spoke too soon. @matanlurey the vertical tab stops tell me you are using VS Code?

In VS Code, I see that only the first line is highlighted, between `>>>` and `<<<`:

```dart
main() {
  C()>>>..d()<<<
    .s.length;
}
```

Does VS Code not highlight any lines from multiline spans past the first line?

In IntelliJ, I see the above multiline highlighting. But I think in this situation, I would expect to only see either `s.` highlighted, or `.length` highlighted. But `dartanalyzer` also reports the problem as being on line 11 (`C()..d()`), not line 12 (`.s.length;`)

@bwilkerson WDYT? Do you know about multiline highlights in VS Code? Would you expect just `s.` to be highlighted with the "UNCHECKED_USE_OF_NULLABLE_VALUE" diagnostic, or `.length`? The message reads:

> The property 'length' can't be unconditionally accessed because the receiver can be 'null'.

**Comment by bwilkerson** [comment]
> Do you know about multiline highlights in VS Code?

No, I don't. But @DanTup will know.

> Would you expect just s. to be highlighted with the "UNCHECKED_USE_OF_NULLABLE_VALUE" diagnostic, or .length?

My preference would be for `length` to be highlighted (without the `.`). That's the member that being accessed, so I think that's what we want to draw the user's attention to. If the member is a method, we should highlight the method name (and not the argument list).

**Comment by DanTup** [comment]
This is a known issue in the (non-LSP) diagnostic implementation in Dart-Code. Multi-line diagnostics are truncated to the first line. This doesn't happen when using LSP:

LSP disabled:

<img width="290" alt="Screenshot 2021-01-29 at 12 40 24" src="https://user-images.githubusercontent.com/1078012/106276225-2ba2b300-622f-11eb-93d0-1ac3d04ac4d5.png">

LSP enabled:

<img width="302" alt="Screenshot 2021-01-29 at 12 40 51" src="https://user-images.githubusercontent.com/1078012/106276255-3cebbf80-622f-11eb-87c8-af7dc8c53614.png">

Given the goal of making LSP default soon after the next stable releases (and actively encouraging people to enable the preview now), I'm not sure it's worth trying to fix in the non-LSP code - it would cause [this common issue](https://github.com/dart-lang/sdk/issues/44598) to appear for all non-LSP stable users (which are the majority) in the meantime.

I would definitely recommend most users (particularly those using recent builds) enable the LSP Preview (the `dart.previewLsp` setting). If there are any remaining issues when using LSP, the sooner they're identified/resolved the better.

**Comment by srawlins** [comment]
Thanks a hundred, @DanTup . I agree.
