### ISSUE TITLE
Implement FutureOr related rules of least upper bound

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#43719]
The spec change in dart-lang/language#1254, dart-lang/language@ae340c7dcc62d375bd8df9fd4cb0d669d84478d2, introduces rules about how to compute the function **UP** when at least one argument is a type of the form `FutureOr<T>`. This issue is concerned with implementing these new rules.

**Comment by eernstg** [comment]
Tests under review [here](https://dart-review.googlesource.com/c/sdk/+/166626).

**Comment by franklinyow** [comment]
Anything left here to do?

**Comment by eernstg** [comment]
I think it's complete, thanks!
