### ISSUE TITLE
observatory_ui_2 and service_2 tests failing

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#43713]
[165420](https://dart-review.googlesource.com/c/sdk/+/165420) introduced two new *_2 duplicate test sets, which largely passes with the exception of:

- [ ] service_2/dds_log_history_size_simple_test/dds
- [ ] observatory_ui_2/app_test
- [ ] service_2/get_cpu_samples_rpc_test/service
- [x] service_2/get_isolate_after_language_error_test/dds
- [x] service_2/get_isolate_after_language_error_test/service
- [x] service_2/get_version_rpc_test/dds
- [x] service_2/get_version_rpc_test/service
- [x] service_2/library_dependency_test/dds
- [x] service_2/library_dependency_test/service
- [x] service_2/mirror_references_test/dds
- [x] service_2/mirror_references_test/service
- [x] service_2/weak_properties_test/dds
- [x] service_2/weak_properties_test/service
- [ ] service_2/get_cpu_profile_timeline_rpc_test/service
- [ ] service_2/next_through_simple_async_test_0

as seen in:

- [ ] [app-kernel-linux-debug-x64/7204](https://ci.chromium.org/p/dart/builders/ci.sandbox/app-kernel-linux-debug-x64/7204)
- [ ] [vm-kernel-precomp-win-release-x64/10491](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-win-release-x64/10491)
- [ ] [vm-kernel-precomp-win-release-x64/10494](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-win-release-x64/10494)
- [ ] [vm-kernel-mac-debug-x64/9603](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-debug-x64/9603)

I'm creating this issue to track fixing these failing tests, but I'll approve the failures to unblock the bots for now.

**Comment by cskau-g** [comment]
@rmacnak-google, @bkonyi FYI

**Comment by aam** [comment]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8866907665759648816/+/steps/test_results/0/logs/new_test_failures__logs_/0

```
/========================================================================================\
| service_2/get_cpu_samples_rpc_test/service broke (Pass -> RuntimeError, expected Pass) |
\========================================================================================/

--- Command "vm_compile_to_kernel" (took 17.000466s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & C:\b\s\w\ir\pkg\vm\tool\gen_kernel.bat --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp\short312_ice_2_get_cpu_samples_rpc_test\out.dill C:\b\s\w\ir\runtime\observatory_2\tests\service_2\get_cpu_samples_rpc_test.dart --packages=C:\b\s\w\ir\.packages -Ddart.vm.product=false -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "precompiler" (took 10.000262s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\gen_snapshot --snapshot-kind=app-aot-elf --elf=C:/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp/short312_ice_2_get_cpu_samples_rpc_test/out.aotsnapshot --loading-unit-manifest=C:/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp/short312_ice_2_get_cpu_samples_rpc_test/ignored.json --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp\short312_ice_2_get_cpu_samples_rpc_test\out.dill

exit code:
0

--- Command "remove_kernel_file" (took 43ms):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & cmd.exe /c del C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp\short312_ice_2_get_cpu_samples_rpc_test\out.dill

exit code:
0

--- Command "vm" (took 946ms):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\dart_precompiled_runtime.exe --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp/short312_ice_2_get_cpu_samples_rpc_test/out.aotsnapshot

exit code:
255

stdout:
00:00 [32m+0[0m: out.aotsnapshot (VM Service)[0m

** Launching SERVICE_TEST_TESTEE=true out\ReleaseX64\dart_precompiled_runtime.exe --disable-dart-dev --write-service-info=file:///C:/b/s/w/ithhxdxf/dart_serviceceab36a5/service_info.json --profiler --profiler=true --profile-vm=false --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages --enable-vm-service:0 C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp\short312_ice_2_get_cpu_samples_rpc_test\out.aotsnapshot

>testee>out> Observatory listening on http://127.0.0.1:62762/vgzBSq47jTQ=/

>testee>out> Testee doing something.

>testee>out> Testee did something.

>testee>out>

** Signaled to run test queries on http://127.0.0.1:62762/vgzBSq47jTQ= (VM Service)

Loading VM...

Done loading VM

Running out.aotsnapshot [1/1]

00:00 [32m+0[0m[31m -1[0m: out.aotsnapshot (VM Service) [1m[31m[E][0m[0m

  Expected: a value greater than <10>
    Actual: <1>
     Which: is not a value greater than <10>
  Should have many samples


  package:test_api/src/frontend/expect.dart 155                           fail
  package:test_api/src/frontend/expect.dart 150                           _expect
  package:test_api/src/frontend/expect.dart 59                            expect
  runtime\observatory_2\tests\service_2\get_cpu_samples_rpc_test.dart 38  checkSamples
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1129                                               _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 94                                    _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                               Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1190                                               _rootRun
  dart:async/zone.dart 1093                                               _CustomZone.run
  dart:async/zone.dart 1630                                               _runZoned
  dart:async/zone.dart 1550                                               runZoned
  package:test_api/src/backend/invoker.dart 228                           Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 383                           Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121                                               _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83                                    _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                               Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190                                               _rootRun
  dart:async/zone.dart 1093                                               _CustomZone.run
  dart:async/zone.dart 1630                                               _runZoned
  dart:async/zone.dart 1550                                               runZoned
  package:test_api/src/backend/invoker.dart 370                           Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 415                           Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 369                           Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 104                                  Chain.capture.<fn>
  dart:async/zone.dart 1190                                               _rootRun
  dart:async/zone.dart 1093                                               _CustomZone.run
  dart:async/zone.dart 1630                                               _runZoned
  dart:async/zone.dart 1550                                               runZoned
  package:stack_trace/src/chain.dart 102                                  Chain.capture
  package:test_api/src/backend/invoker.dart 368                           Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 153              LiveTestController.run
  dart:async/future.dart 201                                              new Future.microtask.<fn>
  dart:async/zone.dart 1182                                               _rootRun
  dart:async/zone.dart 1093                                               _CustomZone.run
  dart:async/zone.dart 997                                                _CustomZone.runGuarded
  dart:async/zone.dart 1037                                               _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190                                               _rootRun
  dart:async/zone.dart 1093                                               _CustomZone.run
  dart:async/zone.dart 997                                                _CustomZone.runGuarded
  dart:async/zone.dart 1037                                               _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                                   _microtaskLoop
  dart:async/schedule_microtask.dart 50                                   _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118                               _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 438                                  _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428                                  _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168                               _RawReceivePortImpl._handleMessage


** Killing script

00:00 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python tools/test.py -n dartkp-win-release-x64 service_2/get_cpu_samples_rpc_test/service

This is LogDog
Rendering took 0.09s
```

**Comment by aam** [comment]
More flaky service_2 tests turned stable errors:
* service_2/bad_reload_test/service
* service_2/get_allocation_samples_test/service
* service_2/get_source_report_test/service
* service_2/bad_reload_test/dds
* service_2/get_allocation_samples_test/dds
* service_2/get_source_report_test/dds

**Comment by a-siva** [comment]
Additional flaky tests that started to consistently fail [app-kernel-linux-debug-x64](https://ci.chromium.org/p/dart/builders/ci.sandbox/app-kernel-linux-debug-x64/7301)
- service_2/coverage_optimized_function_test/dds
- service_2/coverage_optimized_function_test/service

**Comment by askeksa-google** [comment]
The tests
- service_2/get_vm_timeline_rpc_test/dds
- service_2/get_vm_timeline_rpc_test/service

have gone from flaky to timeout on [vm-kernel-linux-debug-ia32](https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-linux-debug-ia32/7041/overview) and [vm-kernel-linux-release-ia32](https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-linux-release-ia32/8207/overview).

**Comment by sstrickl** [comment]
The tests

* [service/evaluate_activation_test/instance/dds](https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-release-ia32/dartk-weak-asserts-linux-release-ia32/120/service/evaluate_activation_test/instance/dds)
* [service/evaluate_activation_test/scope/dds](https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-release-ia32/dartk-weak-asserts-linux-release-ia32/120/service/evaluate_activation_test/scope/dds)

have gone from flaky to timeout on dartk-weak-asserts-linux-release-ia32.

**Comment by askeksa-google** [comment]
The tests

- service_2/get_allocation_samples_test/dds
- service_2/get_allocation_samples_test/service

have gone from flaky to runtime error on app_jitk-linux-release-x64.

**Comment by cskau-g** [comment]
[service_2/get_vm_timeline_rpc_test/service](https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/app-kernel-linux-release-x64/11337/overview)   flaky -> Timeout

**Comment by dcharkes** [comment]
Again get_vm_timeline_rpc_test https://dart-ci.appspot.com/log/app-kernel-linux-release-x64/app_jitk-linux-release-x64/11792/service_2/get_vm_timeline_rpc_test/service

The history is also quite colorful: https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=service_2/get_vm_timeline_rpc_test/service&configurations=app_jitk-linux-release-x64

**Comment by dcharkes** [comment]
service_2/rewind_optimized_out_test/service flaky -> Timeout again

log: https://dart-ci.appspot.com/log/vm-kernel-linux-release-ia32/dartk-linux-release-ia32/8476/service_2/rewind_optimized_out_test/service
history: https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=service_2/rewind_optimized_out_test/service&configurations=dartk-linux-release-ia32
current results: https://dart-ci.firebaseapp.com/current_results/#/filter=service_2/rewind_optimized_out_test/service&showAll (Timeout on 2 archs, flaky on 1 arch).

**Comment by liamappelbe** [comment]
service/get_source_report_test/dds went from flaky to timeout on vm-linux-release-arm64

log: https://dart-ci.appspot.com/log/vm-linux-release-arm64/vm-linux-release-arm64/502/service/get_source_report_test/dds

**Comment by bkonyi** [comment]
These tests no longer exist.
