### ISSUE TITLE
missing async causes "missing return" lint

### ISSUE THREAD

**Issue by gkrawiec** [dart-lang/sdk#43726]
**Describe the issue**

Once in a while I will forget to add `async` to a function with a return defined as `Future<void>` and the lint that comes up is "missing return" instead of something liker "missing async"
**To Reproduce**

 ```
 Future<void> onChange({@required Activity newActivity}) {
    activityController.add(newActivity);
  }
```

gives me
```
This function has a return type of 'Future<void>', but doesn't end with a return statement.
Try adding a return statement, or changing the return type to 'void'.dartmissing_return

```
but it's just missing `async`

I am pretty new at this, but I haven'f found a lint that would apply to missing async, so maybe its a new lint that's required?

**Comment by bwilkerson** [comment]
I will note that this currently impacts both `HintCode.MISSING_RETURN` (the diagnostic referenced above) and `CompileTimeErrorCode BODY_MIGHT_COMPLETE_NORMALLY`, depending on whether Null Safety has been enabled. In both cases the suggestion to add `async` ought to only be provided if the return type is `Future<void>` and there are no other `return` statements in the body.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/172028
