### ISSUE TITLE
[cfe] Report error for type which is not well-bounded

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#43735]
This is the front end specific issue for #43724.

```dart
class A<X> {}
typedef G<X extends Y, Y extends A<X>> = void Function();

main() {
  late G<A<dynamic>, A<Null>> x;
  late G<A<Null>,  A<Null>> y;
}
```

The front end (`dart`) as of b2e33ee5509210c84f640ba0ad28649c0e8d4dea does not report an error for the types 
`G<A<dynamic>, A<Null>>` and `G<A<Null>,  A<Null>>`, even though they are not well-bounded. Details in https://github.com/dart-lang/sdk/issues/43724#issuecomment-706058315.

**Comment by stefantsov** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/425e4dbe094ceed123690d6a5822d8d97d203d55.
