### ISSUE TITLE
standalone_2/out_of_memory_slow_growth_test/0 fails with runtime error

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#43739]
On https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-win-debug-x64/10056

The tests
```
standalone_2/out_of_memory_slow_growth_test/0 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-win-debug-x64
```

```
--- Command "vm" (took 31.000281s):
set DART_CONFIGURATION=DebugX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64\crashpad_handler.exe & out\DebugX64\dart.exe --old_gen_heap_size=20 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\tests\standalone_2\out_of_memory_slow_growth_test.dart

exit code:
255

stderr:
Exhausted heap space, trying to allocate 32 bytes.
Exhausted heap space, trying to allocate 80 bytes.
Unhandled exception:
Out of Memory
#0      main (file:///C:/b/s/w/ir/tests/standalone_2/out_of_memory_slow_growth_test.dart:18:5)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n dartk-win-debug-x64 standalone_2/out_of_memory_slow_growth_test/0
```

cc @rmacnak-google

**Comment by aam** [comment]
The underlying problem in this test failure seems to be addressed by https://dart-review.googlesource.com/c/sdk/+/165862 and is more generally tracked in https://github.com/dart-lang/sdk/issues/43543 and https://github.com/dart-lang/sdk/issues/43642.

**Comment by aam** [comment]
Similar issue on https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-debug-x64/9640

**Comment by sstrickl** [comment]
Also went from flaky to RTE in the /1 configuration today on mac-debug ([log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8866478839819480256/+/steps/test_results/0/stdout)).

**Comment by dcharkes** [comment]
I also observed crashes on Windows IA32 ([log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865906532835110640/+/steps/vm_tests_shard_8/0/logs/task_stdout_stderr:_vm_tests_shard_8/0)). These show up as purple because archiving core dumps fails.

**Comment by alexmarkov** [comment]
`standalone/out_of_memory_slow_growth_test/0` went flaky -> RuntimeError on dartk-strong-linux-release-x64.

**Comment by rmacnak-google** [comment]
c8dea19836d95c0cc548def26a20b9e6a79d3ba2
