### ISSUE TITLE
TimelineEvent not accurately

### ISSUE THREAD

**Issue by fredlee12345678** [dart-lang/sdk#43730]
**Describe the issue**
I found that timeline in dart is not accurately. I use the same demo, if I don't connect to devtools (TimelineEvent not work). The performance of Raster thread is 7ms. But When I connect to devtools (TimelineEvent is working), the cost of Raster thread up to 12-15ms. it almost double!!

And I found the root cause is there is a mutex lock in StartEvent, here is code: 

```
TimelineEvent* TimelineEventFixedBufferRecorder::StartEvent() {
  return ThreadBlockStartEvent();
}
```

```
TimelineEvent* TimelineEventRecorder::ThreadBlockStartEvent() {
  if ((thread_block != NULL) && thread_block->IsFull()) {
    **MutexLocker ml(&lock_);**
    // Thread has a block and it is full:
    // 1) Mark it as finished.
    thread_block->Finish();
    // 2) Allocate a new block.
    thread_block = GetNewBlockLocked();
    thread->set_timeline_block(thread_block);
  } else if (thread_block == NULL) {
    **MutexLocker ml(&lock_);**
    // Thread has no block. Attempt to allocate one.
    thread_block = GetNewBlockLocked();
    thread->set_timeline_block(thread_block);
  }
 ....
}
```

The fluctuant result make more difficult to analyze performance. Could some one check it?

* Dart SDK Version (`dart --version`)
dart --version
Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "macos_x64"

**Comment by alexmarkov** [comment]
@rmacnak-google @bkonyi

**Comment by rmacnak-google** [comment]
Timeline performance was significantly improved in 08634ec4ee3efb2b574d8da22bae58ead0d5be62.
