### ISSUE TITLE
[analyzer] Report error for type which is not well-bounded

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#43734]
This is the analyzer specific issue for #43724.

```dart
class A<X> {}
typedef G<X extends Y, Y extends A<X>> = void Function();

main() {
  late G<A<Null>,  A<dynamic>> x;
}
```

The analyzer as of b2e33ee5509210c84f640ba0ad28649c0e8d4dea does not report an error for the type `G<A<Null>,  A<dynamic>>` even though that type is not well-bounded. Details in https://github.com/dart-lang/sdk/issues/43724#issuecomment-706058315.

**Comment by iarkh** [comment]
Here is a similar source code example where analyzer similarly does not produce expected compile time error:
``` dart
class A<X> {}
typedef G<X extends A<X>, Y extends X> = X Function();

main() {
  late G<A<dynamic>, A<Null>> x;
}
```
@eernstg, is this a same issue or I need to file another issue here?

**Comment by eernstg** [comment]
It is again a type which is not well-bounded (`A<dynamic> <: A<A<dynamic>>` does not hold; then substitute to `G<A<Never>, A<Null>>`, but now `A<Null> <: A<Never>` does not hold), so I think it fits as a single issue.

**Comment by srawlins** [comment]
@eernstg  Analyzer now reports:

> 'A&lt;Null>' doesn't conform to the bound 'A&lt;Never>' of the type parameter 'X'.

Is this the appropriate error?

**Comment by eernstg** [comment]
Yes, that's a good error message. I'd recommend that error messages involving malformed types that might be intended to be super-bounded should just report the basic errors (like "doesn't satisfy the declared bound"), rather than making an attempt to consider the type to be super-bounded, and then recommending how to fix it as such.

The reason for this preference is that super-bounded types are somewhat complex and would presumably be used by developers who are aware of the typing structure with so much detail that they'll know what to do. Conversely, developers who do not know about super-bounded types at all wouldn't gain anything useful from a message about how to specify a super-bounded type correctly.

I'll close the issue. @srawlins, please reopen if you disagree.
