### ISSUE TITLE
provide a way to be aware of what changes `dart fix` would make

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43746]
We might consider having a way to be aware of what changes running `dart fix` would make. This could be `dart fix --preview`, `dart fix --dry-run`, ...

`dart fix` could potential make a lot of changes to a project; having a mechanism to be aware of the scope of the changes, and which kinds, that would be made could be useful.

**Comment by devoncarew** [comment]
This could just be a summary of the changes, or it could be a diff-like view.

**Comment by pq** [comment]
A few `--dry-run` variations.

1. List of fixes.
2. List of files.
3. List of fixes and files.
4. List of files with corresponding fixes.

@InMatrix: I'd be curious to get your 2 cents?

**Comment by bwilkerson** [comment]
Alternatively, we could wait until we have a user request for such a feature. That would allow us to get an actual (as opposed to a theoretic) use case.

But for the record, if there _is_ a use case for listing fixes, I would propose listing the number of each diagnostic that would be fixed rather than some kind of diff of each fix.

**Comment by devoncarew** [comment]
> we could wait until we have a user request for such a feature

I agree with this generally - it's easy to end up with too many options and flags otherwise.

However, note that this is feedback from me when I was first using the tool. I noticed the lack of some kind of preview of what the tool would do.

For comparison, some related tooling is `go fix` (https://golang.org/cmd/fix/). It has a `-diff` flag to print a git diff of the changes that would be made (and, an `-r` flag to scope the changes to only listed ast re-writes).

**Comment by pq** [comment]
I was looking at `go fix` actually.  I wonder if a `git diff` is really what folks would want.  Alone it doesn't answer, for example, what fixes were applied and in the case of many could be pretty overwhelming.  Dunno!

📟 @InMatrix

**Comment by bwilkerson** [comment]
> I noticed the lack of some kind of preview of what the tool would do.

To help me understand better, what goal did you have that caused you to want a preview as part of the tool (as opposed to using something like `git diff` to see the changes)?

> I wonder if a `git diff` is really what folks would want.

I definitely agree that we need to understand what use case `git diff` doesn't cover, if any. (Hence the question above.)

I find it interesting that `go tool fix` provides a flag to print the same thing as `git diff` and then turns around and tells users that they should be using a source code control tool like git so that they can do a diff before committing. I have to wonder whether that's an historical accident more than an intentional design decision.

**Comment by InMatrix** [comment]
It's hard to give a quick comment without further investigation (e.g., looking at how similar tools do this). My 2 cents are the user probably cares more about the types of automatic fixes to be applied than the scope of those changes. For example, if a fix is about renaming a Class, the user might have a lot of confidence in the tool's ability to do it right and just let it apply all the changes. But if a fix involves some complicated logic, the user might want to try the fix in one place or even manually and examine its correctness.

**Comment by devoncarew** [comment]
Just for clarification, I don't know that we want a git diff like view (like `go fix`), but do think that we'll likely want some useful preview of changes we might make (probably w/ some info about the error codes we're matching against, or the framework refactorings we'll run).

**Comment by devoncarew** [comment]
This may be complete now?

**Comment by pq** [comment]
Yep.  A few tweaks in flight but functionally I think we're there modulo summaries for data-driven fixes.

@bwilkerson: should we open a separate issue for that?

**Comment by bwilkerson** [comment]
> ... modulo summaries for data-driven fixes.

Sorry, but I think I lost some context. What summary information are we talking about?

**Comment by pq** [comment]
> What summary information are we talking about?

The proposal was something like this:

```
lib/foo.dart
  empty_statements • 1 change
  unused_imports • 3 changes
  package:flutter updates • 4 changes
```

but I don't think we'll see anything like "package:flutter updates" for data-driven fixes?

**Comment by bwilkerson** [comment]
Not the way it's currently implemented, no. We could probably find a way to get that information back, but I don't have any ideas for how to do that that don't feel like they're just bolted on the side.

But the downside of not addressing that probably means that it will report the underlying language diagnostic (such as too_many_positional_arguments) the same way it currently reports lints.

**Comment by devoncarew** [comment]
> But the downside of not addressing that probably means that it will report the underlying language diagnostic (such as too_many_positional_arguments) the same way it currently reports lints.

That doesn't sound too bad - they'd still see fixes for these items, and would have error codes which would make sense to the user.

Longer term, we may want some way to identify whether a fix is from a data driven framework file, and perhaps, more context on the fix ("Update to the latest MaterialButtonFoo API"). This would help distinguish between lint issues and items which are about migrating between two versions of a framework.

**Comment by bwilkerson** [comment]
> Longer term, we may want some way to identify whether a fix is from a data driven framework file, and perhaps, more context on the fix ("Update to the latest MaterialButtonFoo API").

That seems reasonable. It will be both valuable and interesting to get feedback from our users.

> This would help distinguish between lint issues and items which are about migrating between two versions of a framework.

But I will point out that this framework is _not_ limited to applying fixes for lints and fixes from data files. Any fix for any diagnostic can be bulk fixed (if we've first determined that it's safe for it to be applied in bulk). For example, the null safety spec says that it's a warning to have a null check (`!`) where it isn't needed (a `StaticWarningCode.UNNECESSARY_NON_NULL_ASSERTION` diagnostic), and the tool, as of today, will fix that by removing the null check operator.

**Comment by pq** [comment]
As per conversation, closing out as initial implementation complete.

**Comment by oceanseth** [comment]
wanted to provide a comment here that I was very much expecting to see the actual diffs, and disappointed that the summary was mostly useless and does not make me feel safe to run the fix.
