### ISSUE TITLE
Field not initialized warning on a comment line

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#43748]
#### Steps to reproduce
Migrating github.com/timsneath/win32

#### What actually happened?
Two separate / interrelated issues:

1. Bottom right pane complains that field is not initialized at line 461. But this line is a comment.
2. Text for this row is strangely formatted -- looks like two separate fonts overlaid. 

See screenshot:
![image](https://user-images.githubusercontent.com/2319867/95638059-4cf54e80-0a48-11eb-80cc-909954fbc51b.png)

**Dart SDK version**: 2.11.0-203.0.dev

Thanks for filing!

**Comment by timsneath** [comment]
Ah -- looking at this row more, it seems like the `_` in `SECURITY_ATTRIBUTES` is being interpreted as the beginning of an italics section (Markdown?) We should sanitize inputs better.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
