### ISSUE TITLE
Flutter web fails to compile for web

### ISSUE THREAD

**Issue by AshfaqAshi** [dart-lang/sdk#43755]
Windows 10

Dart 2.9.1

Error:
Target dart2js failed: Exception: ../../Documents/Flutter%20SDK/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+4/lib/cloud_firestore_web.dart:90:13:
Internal Error: Runtime type information not available for type_variable_local(j:type_variable(runTransaction.T)) in (local(FirebaseFirestoreWeb.runTransaction#transaction),
j:anonymous_closure_local(FirebaseFirestoreWeb_runTransaction_closure)) for j:closure_call(FirebaseFirestoreWeb_runTransaction_closure.call).
  Future<T> runTransaction<T>(TransactionHandler<T> transactionHandler,

StackTrace
Unhandled exception:
Assertion failure: Runtime type information not available for type_variable_local(j:type_variable(runTransaction.T)) in (local(FirebaseFirestoreWeb.runTransaction#transaction),
j:anonymous_closure_local(FirebaseFirestoreWeb_runTransaction_closure)) for j:closure_call(FirebaseFirestoreWeb_runTransaction_closure.call).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:49:3)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:326:11)
#2      TypeBuilder._buildEnvironmentForType (package:compiler/src/ssa/type_builder.dart:280:12)
#3      TypeBuilder.analyzeTypeArgumentNewRti (package:compiler/src/ssa/type_builder.dart:198:9)
#4      KernelSsaGraphBuilder._buildGenerator (package:compiler/src/ssa/builder_kernel.dart:1332:31)
#5      KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder_kernel.dart:1231:7)
#6      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder_kernel.dart:476:13)
#7      CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#8      KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder_kernel.dart:428:21)
#9      KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:500:22)
#10     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#11     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:483:18)
#12     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:346:21)
#13     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:80:29)
#14     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:454:30)
#15     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:319:43)
#16     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:450:29)
#17     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#18     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#19     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#20     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#22     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#24     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:266:12)
#25     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:282:5)
#26     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#27     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#28     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#29     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#31     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#32     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:382:5)
#33     Compiler.generateJavaScriptCode (package:compiler/src/compiler.dart:284:9)
#34     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:432:9)
#35     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#36     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#37     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#38     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#39     new Future.sync (dart:async/future.dart:223:31)
#40     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#41     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#42     Compiler.run (package:compiler/src/compiler.dart:209:41)
#43     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#44     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#45     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#47     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#48     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#49     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by AshfaqAshi** [comment]
> @AshfaqAshi we may need some additional details. Do you have a small example we could use to help us reproduce the failure locally?
> 
> Also, does this issue still exist in the latest stable release (Dart 2.10.1)?
> 
> I ask because some changes have been made recently that could potentially also fix this, but I'm not sure. For example, there is a possibility that the change @fishythefish made in [7e8348f](https://github.com/dart-lang/sdk/commit/7e8348f4ce87f89235154e974c799de57473c4f4) could help here (which was released in 2.10.0 for the first time).

@sigmundch I was working in beta channel when the issue happened. I then switched to the dev channel and now the issue seems to be gone

**Comment by sigmundch** [comment]
Good to hear. I'll close the issue, but let us know if you still run into trouble.
