### ISSUE TITLE
Migration tool is setting outdated sdk constraints

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43757]
Running the migration tool from bleeding edge or flutter master, dart version:

Dart SDK version: 2.11.0-207.0.dev (dev) (Fri Oct 9 09:16:09 2020 -0700) on "macos_x64"

The migration tool is setting a pub sdk constraint as follows:

+ sdk: '>=2.9.0 <2.10.0'

This should be updated for the current dev releases, and will need another update when we go to beta.

cc @srawlins @timsneath

**Comment by devoncarew** [comment]
Sam, I think this is something we'll want to get in for TP2.

**Comment by srawlins** [comment]
Is `sdk: '>=2.11.0 <2.12.0'` or do I need to include `-dev.0` or something?

**Comment by devoncarew** [comment]
From a discussion:
- we'll want the lower bounds to work in the SDK that they're using to migrate (so, if using something like `2.11.0-207.0.dev`, the lower bounds should work for that version)

And some thoughts:
- if the feature has been released, we should use that version (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/analysis/experiments.g.dart#L101) as the lower bounds
- else, we should use the experimental release version (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/analysis/experiments.g.dart#L100) as the lower bounds
- for both of those, we may want to do something to ensure that the sdk used to perform the migration is included in the version range (i.e., lower the range slightly to capture a dev version of the sdk range)

**Comment by leafpetersen** [comment]
What @devoncarew says above about lower bounds seems right to me.  For upper bounds, post-stable we should probably use <3.0, but for beta we may want to use < 2.12 .  @natebosch @jakemac53 @mit-mit  WDYT?

**Comment by srawlins** [comment]
Well I landed a bandaid but I like the idea of maybe just taking the current 2.11 dev version if that's easy? And I'll wait for an answer about the upper bound

**Comment by devoncarew** [comment]
You might choose to use `releaseVersion` (from the generated experiments file) if it's not null, and short of that use the value from `experimentalReleaseVersion` (which is at `2.10.0`).

```dart
  static final non_nullable = ExperimentalFeature(
    index: 3,
    enableString: EnableString.non_nullable,
    isEnabledByDefault: IsEnabledByDefault.non_nullable,
    isExpired: IsExpired.non_nullable,
    documentation: 'Non nullable by default (null safety)',
    experimentalReleaseVersion: Version.parse('2.10.0'),
    releaseVersion: null,
  );
```

**Comment by srawlins** [comment]
Ah, so I can still use `>=2.10.0`? That works, since its released as final, and covers all 2.11 dev versions.

**Comment by leafpetersen** [comment]
`>=2.10.0` will work when the experiment flag is passed, or the package is in the allow list.  For TP2, the former will always be true.  For beta, I think the lower bound needs to be a 2.12 dev release.

**Comment by pcsosinski** [comment]
unless we change our versioning for beta on the way to our Q1-21 release, we will be some version of 2.11 up to (and including) that stable.

**Comment by leafpetersen** [comment]
> unless we change our versioning for beta on the way to our Q1-21 release, we will be some version of 2.11 up to (and including) that stable.

@pcsosinski No, we always bump the minor version when we flip an experiment flag to avoid various issues, so the first null safety beta will be a 2.12 beta, and 2.12 will be the stable release.

**Comment by pcsosinski** [comment]
> @pcsosinski No, we always bump the minor version when we flip an experiment flag to avoid various issues, so the first null safety beta will be a 2.12 beta, and 2.12 will be the stable release.

thanks @leafpetersen, makes sense.   i guess we haven't touched any experiment flags in a while?

**Comment by timsneath** [comment]
This seems problematic, though. Are we really going to invalidate all null
safe code with a 2.10<=x<2.11 constraint?

It feels like we're causing major package ecosystem churn. I understand the
value of doing so if we *know *it's a breaking change, but I'd love it if
the default were less invasive.

**Comment by leafpetersen** [comment]
> This seems problematic, though. Are we really going to invalidate all null safe code with a 2.10<=x<2.11 constraint?

Any null safe code that has been published with this constraint is under the supervision of the Dart team (it has to be explicitly on the allow list) and yes, one of the beta and stable checklist items is to re-publish all of these packages.  We've already rolled this once, it's tedious, but doable.  So I'm not concerned about that.

A more real concern is what to do about packages published during the beta release, since we have no control over them.  I believe that our planned guidance for publishing pre-stable is:
  - Publish as a pre-release with a tight upper SDK constraint of `<2.12`
  - When stable rolls, publish a stable release with an SDK constraint of `>=2.12 < 3.0.0`

@natebosch @jakemac53 does that agree with your thinking?

There is a legitimate tradeoff here between the chance of a package being in a broken state because of breaking bug fixes/changes during beta vs a package author not knowing (or forgetting) to republish their package when stable is released.  We could choose to instead recommend that:
  - Publish as a pre-release with a constraint of `>=2.12.0-beta.whatever < 3.0.0` (and make dart migrate issue this)
  - When stable rolls, publish a stable release with an SDK constraint of `>=2.12 < 3.0.0`

The main benefit of the latter workflow is that because of the dart migrate default, packages that don't follow our recommendation to publish separate pre-release and stable versions will still be available in a null safe version in stable, albeit with some chance of being broken.
