### ISSUE TITLE
Progress bar inserts unnecessary newlines during migration analysis

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#43752]
#### Steps to reproduce
On Mac default terminal, running migration analysis causes multiple rows of spew while presenting progress bar:
![image](https://user-images.githubusercontent.com/2319867/95638882-1f5dd480-0a4b-11eb-8933-8aa4dcb3e8ac.png)

**Dart SDK version**: 2.11.0-203.0.dev

Thanks for filing!

**Comment by srawlins** [comment]
I've seen before, this and didn't think this was a big deal, but when you re-run the migration and it shows up over and over, it is definitely distracting and confusing.

**Comment by srawlins** [comment]
I figured this one out. Mailing a fix.
