### ISSUE TITLE
Adding tool-recommended @required annotation causes failure

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#43751]
#### Steps to reproduce
In package win32, file test/wincreds_test.dart, migration tool proposed adding `required` keyword:
![image](https://user-images.githubusercontent.com/2319867/95638806-cd1cb380-0a4a-11eb-9563-8b75256ad9bc.png)

Clicked on the action: 
![image](https://user-images.githubusercontent.com/2319867/95638814-d6a61b80-0a4a-11eb-9105-12b2d0cd8533.png)

Clicked "rerun with changes"
Received static analysis error message:
![image](https://user-images.githubusercontent.com/2319867/95638754-9f376f00-0a4a-11eb-91e3-b41f213f13e6.png)

**Dart SDK version**: 2.11.0-203.0.dev

Thanks for filing!

**Comment by srawlins** [comment]
CC @stereotype441 who has just landed some support for adding imports.

**Comment by srawlins** [comment]
@stereotype441 and I found some awkward cases when following this `@required` hint all the way down:

* As @timsneath found, above, we may need to add an import of `package:meta/meta.dart`,
* This means we might need to add `meta` to the pubspec, under dependencies (or dev_dependencies),
* But even then, after adding to pubspec, we'd have to tell the user to run `pub get` (in a new terminal window) before clicking "Re-run with changes". Ouch!
* Even if you do that, then after the migration runs, you're new `package:meta/meta.dart` import is now unused, and your new dependency in pubspec is unused; you only needed them very temporarily.

Instead, we're going to support another comment directive in the migration tool, `/*required*/`. The tool will have a button, "Add /*required*/ hint". No imports or dependencies required.

**Comment by stereotype441** [comment]
@srawlins sounds good!  I can't remember if I mentioned this idea in our meeting just now, but how about if we make it so that the migration tool decides whether to offer `Add /*required*/ hint` or `Mark with @required` based on whether the user's project already has a dependency on `package:meta`.  That way we won't be placing a burden on users to figure out whether `/*required*/` or `@required` makes sense for their particular project.

**Comment by srawlins** [comment]
I think that's fine.

**Comment by srawlins** [comment]
Ah, slight change from @stereotype441 's suggetsion: We'll prefer `/*required*/` over `@required` if the individual _library_ already imports meta, rather than whether the package already depends on meta. This will reduce flip-flop changes during migration.
