### ISSUE TITLE
No published analyzer available for language version 2.11.0

### ISSUE THREAD

**Issue by wechatobok** [dart-lang/sdk#43758]

**Comment by sanekyy** [comment]
same issue

**Comment by ghanshyam1898** [comment]
same here

**Comment by sanfrnds9** [comment]
Same here:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.9.0
SDK language version: 2.11.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.11.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[INFO] Generating SDK summary...
[SEVERE] functional_data_generator:functional_data on test/mocks/app_settings_store_mock.dart:

Bad state: Unexpected diagnostics:
/Users/sandeep/flutterdevelopment/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:152:17 - This requires the 'non-nullable' language feature to be enabled.
/Users/sandeep/flutterdevelopment/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:119:41 - This requires the 'non-nullable' language feature to be enabled.

**Comment by sanfrnds9** [comment]
Any update? facing same issue

**Comment by srawlins** [comment]
One has since been published.
