### ISSUE TITLE
dart migrate 2.11 updates pubspec.yaml to 2.10 maxver

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#43753]
After running `dart migrate` on my win32 package and choosing apply migration, pubspec.yaml is updated to:

```yaml
environment:
  sdk: '>=2.9.0 <2.10.0'
```

However, I'm running it from:
```bash
$ dart --version
Dart SDK version: 2.11.0-203.0.dev (dev) (Thu Oct 8 16:48:33 2020 -0700) on "macos_x64"
```

which means that the resultant package won't work on the build I ran the migration from. 

That seems wrong, no?

**Comment by parlough** [comment]
Perhaps the upper constraint should be `<3.0.0` unless they already have a max that is equal to or greater than their current sdk version.

**Comment by timsneath** [comment]
Duplicate of #43757
