### ISSUE TITLE
Windows: Add support for a UWP target

### ISSUE THREAD

**Issue by clarkezone** [dart-lang/sdk#43762]
In order to land the following Flutter change : https://github.com/flutter/engine/pull/21754 that is the first step towards addressing https://github.com/flutter/flutter/issues/14967 it is necessary to add Windows UWP support to Dart.  This constitutes

1. supporting a new target_os of  type winuwp
2. conditionally excluding win32 API calls that are not supported in the AppContainer API partition for that target
3. updating linker settings to conditionally exclude libraries relating to 2

**Comment by a-siva** [comment]
Do we need a full Dart SDK built for a new target_os type winuwp or is it just sufficient to have the ability to build a flutter engine for winuwp.

The CL https://dart-review.googlesource.com/c/sdk/+/167041 attempts to use a new target_os type and I was wondering if that was necessary. Instead could we just add a define SUPPORT_WINUWP and define this in the flutter engine build rules and conditionally compile out the code in process_win.cc, secutiry_context-win.cc and native_symbol_win.cc using this define.

**Comment by stuartmorgan** [comment]
`target_os == "winuwp"` is how Chromium's build system expresses UWP builds, and we use Chromium's build files for various third-party dependencies. Maintaining a completely different way of expressing UWP builds in Flutter would have ripple effects and require more ongoing maintenance.

**Comment by a-siva** [comment]
The Dart SDK is typically built, tested and released currently on the following hosts Linux(ia32,x64,ARMv7,ARMz8), Mac(x64) and Windows (ia32/x64). This would mean a new host flavor to build, test, release and maintain for Dart. Adding @athomas here for his opinions on that.

cc @athomas

**Comment by stuartmorgan** [comment]
It's not clear to me why the details of how the configuration is expressed in GN would be linked to the level of support (especially a full Dart SDK release; I don't think there's really any reason to do that with a UWP variant right now).

Having it built and tested in Dart's CI would be ideal certainly, but landing these minimal changes necessary for us to be able to build a UWP engine variant would unblock development, and would therefore be very useful even without that.

**Comment by a-siva** [comment]
That was my initial question - do you need a full Dart SDK or just an engine variant that was built for UWP.

**Comment by stuartmorgan** [comment]
I believe all we'll need is the ability to build Dart in this configuration within the context of a Flutter engine build. That's definitely all we need in the short term.

**Comment by clarkezone** [comment]
This is now landed: https://github.com/dart-lang/sdk/commit/50a2216b31cf7089802687d3b90878dd9497a248
