### ISSUE TITLE
Deflaking doesn't work on certain service tests

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#43768]
Consider the following build:
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-linux-release-x64/12913

It turned red because of the failure of `service_2/next_through_simple_async_test_0` test:
```
The following tests began failing:

service_2/next_through_simple_async_test_0 broke (Pass -> Timeout, expected Pass)
```

The test is flaky and passes most of the time. However, it looks like bot has not attempted to run it multiple times.

Note that there is actually `service_2/next_through_simple_async_test` test which contains multiple variants of `VMOptions`, but there is no `service_2/next_through_simple_async_test_0` test. Re-run command printed by the failing test doesn't work.

`list tests to deflake` step has this test:
```
service_2/next_through_simple_async_test_0
```

However, deflaking shard didn't run any tests:
```

/b/s/swarming_bot.1.zip/third_party/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
Test configuration:
    dartk-linux-release-x64(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: linux)
Suites tested: service_2

--- Total time: 00:00 ---

=== All 0 tests passed ===
INFO: Core dump archiving is activated
INFO: No unexpected crashes recorded
```

`update flakiness information` step doesn't mention this test.

This might be the reason for flaky bot redness.

@athomas @whesse @bkonyi

**Comment by athomas** [comment]
Looks like a problem in test.py:

```
$ tools/test.py --progress=status --report --time -ndartk-linux-release-x64 --tests service_2/next_through_simple_async_test_0
Test configuration:
    dartk-linux-release-x64(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: linux)
Suites tested: service_2

--- Total time: 00:00 ---

=== All 0 tests passed ===
```

**Comment by athomas** [comment]
This is a test that has multiple VMOptions lines:
```
// VMOptions=--no-causal-async-stacks --lazy-async-stacks
// VMOptions=--causal-async-stacks --no-lazy-async-stacks
```

That causes the test name generated to be different from the file name, which is probably why the selector doesn't work (that needs to be handled in test.py).

**Comment by athomas** [comment]
Most likely this was broken by https://dart-review.googlesource.com/c/sdk/+/143961:
```
        var variantTestName =
            testFile.name + '/${emitDdsTest ? 'dds' : 'service'}';
        if (vmOptionsList.length > 1) {
          variantTestName = "${testFile.name}_$vmOptionsVariant";
        }
```
variantTestName doesn't include the dds/service part if there are multiple vmOptions.

**Comment by bkonyi** [comment]
> variantTestName doesn't include the dds/service part if there are multiple vmOptions.

Good catch! Thanks for noticing @alexmarkov and thanks for the fix @athomas!
