### ISSUE TITLE
Migrator should not check pub outdated until Beta

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#43774]

**Comment by devoncarew** [comment]
I think we can check the flag here - beta will update the sdk version and the experimental features info: https://dart-review.googlesource.com/c/sdk/+/166790

**Comment by devoncarew** [comment]
Thanks for the fix! We should likely keep this issue open, so we remember to revert this change after TP2 (before beta).

**Comment by mit-mit** [comment]
I think it's time to enable this again?

**Comment by stereotype441** [comment]
> I think it's time to enable this again?

Yes.  https://dart-review.googlesource.com/c/sdk/+/169124 will re-enable it.  I plan to land it right after the flag flip CL lands.

**Comment by franklinyow** [comment]
Seems like a dup of #41769,  keep this one and close #41769?
Is it ok @stereotype441 ?
