### ISSUE TITLE
[Analyzer] Analyzer unit tests need updating for null safety release

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43777]
The analyzer has various unit tests that define and analyze Dart code.  Currently, that code is treated as opted out of null safety.  When the experiment flag is flipped, that code becomes treated as opted in, and some of it is no longer valid (it also arguable is no longer testing the same thing).  [This CL](https://dart-review.googlesource.com/c/sdk/+/166790) flips the experiment flag, and can be used to test this out.  For a concrete example, see [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8866542632837672304/+/steps/test_results/0/logs/new_test_failures__logs_/0) which shows a failure on `pkg/analysis_server/test/analysis/reanalyze_test.dart`  (as well as others).

cc @scheglov @bwilkerson @devoncarew

**Comment by bwilkerson** [comment]
If we simply update all of the tests to be valid under Null Safety then we will have very little coverage of legacy code. If that's a concern, then we might need to do something more complex. We haven't really worried about this in the past, but most of the other features that were enabled were additive while this one is breaking.

**Comment by leafpetersen** [comment]
Keeping the legacy coverage seems useful.  Ideally, there is a solution which doesn't require adding `// @dart = 2.9` to every code snippet (e.g. setting the language version in the setup code in some way).  Assuming this is possible, you could initially run all of the tests in legacy mode (keeping the existing coverage) and then either now or later port the unit tests to get additional coverage on null safe code, possibly running both a legacy and a ported set?

**Comment by scheglov** [comment]
Yes, all our `analyzer` tests are now based on `PubPackageResolutionTest`, and we then mix `WithNullSafetyMixin` that updates `analysis_options.yaml` to enable the experiment. For the case when Null Safety is enabled by default, we could change `PubPackageResolutionTest` to write `.dart_tool/package_config.json` with `2.8` (?) as the language version for the test package, and `WithNullSafetyMixin` to set the language version to `2.12` (?). Then we will able to run in both modes, or migrate to null safety.

**Comment by franklinyow** [comment]
Move this under the Analyzer Epic

**Comment by leafpetersen** [comment]
Is someone working on this?  We will be blocked on this in the not too distant future.

**Comment by scheglov** [comment]
The update for `analyzer/` is here: https://dart-review.googlesource.com/c/sdk/+/168240

It was relatively easy to do, because we switched analyzer/ to using `.dart_tool/package_config.json`, so we can control language versions.

But `analysis_server/` is still using old `.packages` files, and not just for the package under test, but also to add dependencies. So, we will need to update all these places, possibly switch `analysis_server/` also to [PubPackageResolutionTest](https://github.com/dart-lang/sdk/blob/524f739e0bde9a9b75419559236f6b3018b97d51/pkg/analyzer/test/src/dart/resolution/context_collection_resolution.dart#L323).

**Comment by franklinyow** [comment]
Move this back out to Beta2 epic, remove type-enhancement label

**Comment by leafpetersen** [comment]
Any updates on this?

**Comment by srawlins** [comment]
@bwilkerson would you be able to look at this? I am not so familiar with analysis_server, but Konstantin mentions the fix may be to use PubPackageResolutionTest, which I am planning on using in my fix for #43883, the sibling bug for nnbd_migration.

**Comment by bwilkerson** [comment]
Based on the comments in https://dart-review.googlesource.com/c/sdk/+/168920, I'm not sure what approach I should be implementing. But once we know what needs to be done I can assess how big the task is and whether I can take it on.

**Comment by srawlins** [comment]
I was able to fix the nnbd_migration tests with a smaller arc. https://dart-review.googlesource.com/c/sdk/+/168900

The trick is to also write a package config file expressing the languageVersion of each package involved (possibly just one package, the one for the individual test file...).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/169141 for `analysis_server/`.

**Comment by srawlins** [comment]
I believe there are 13 tests that turn red in analyzer_plugin. Grep for `test_nodeInList_argumentList_only_named_trailingComma` for example. I can look at these.

**Comment by leafpetersen** [comment]
Still seeing some failures [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865236512862064880/+/steps/test_results/0/logs/new_test_failures__logs_/0).

**Comment by scheglov** [comment]
Fixes for integration tests in `analyzer/` and `analysis_server/`.
https://dart-review.googlesource.com/c/sdk/+/169286

**Comment by leafpetersen** [comment]
Looks like we're down to these failures:

pkg/analysis_server/test/integration/analysis/highlights2_test
pkg/analysis_server/test/integration/analysis/highlights_test
pkg/analysis_server/test/integration/analysis/navigation_test
pkg/analysis_server/test/integration/edit/get_assists_test
pkg/analyzer/test/src/summary2/ast_text_printer_integration_test
pkg/analyzer_cli/test/driver_test

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/169286 landed to fix `analysis_server/` integration tests and `ast_text_printer_integration_test`.
https://dart-review.googlesource.com/c/sdk/+/169440 should fix `analyzer_cli/`.

**Comment by leafpetersen** [comment]
Looks green now, thanks!
