### ISSUE TITLE
Dart run does not support -D or --define command-line options

### ISSUE THREAD

**Issue by alanknight-wk** [dart-lang/sdk#43779]
Dart SDK version: 2.10.0 (stable) (Mon Sep 28 09:21:23 2020 +0200) on "macos_x64"

In 2.10, with the consolidation of commands, Dart run is now expected to be used for commands. However, it doesn't include command-line options that were previously present, such as -D or --define. Those are unrecognized options using `dart run`. They exist if you just use the previous form of `dart sourcefile.dart`, but are mentioned nowhere in the list of options. These are required, as far as I can tell, to set constants to be used with the fromEnvironment methods.

**Comment by srawlins** [comment]
I assume `dart run`  falls under the purview of VM; please re-assign if I am mistaken.

**Comment by alexmarkov** [comment]
@bkonyi
