### ISSUE TITLE
Enable native null assertions flag in various build systems

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#43780]
#42536 and #42535 adds a flag to enable null assertions on native methods to ensure soundness in DDC and dart2js respectively.

As part of this, we'd like to enable this flag _by default_ in various build systems that use DDC and dart2js. Examples include build_web_compilers, google3, and Flutter web. However, since the assertions are directly related to SDK code i.e. `dart:html`, if an assertion is thrown, the end user has no path forward to avoid it. As such, these build systems/entry points should be configured to include an option to explicitly disable this flag in order to unblock the user until the next SDK release.

This bug tracks the overall work needed there, and we might need separate bugs to track individual work in each of the build systems, which may require this to be an epic.

**Comment by srujzs** [comment]
cc @nshahan @sigmundch

**Comment by jakemac53** [comment]
My biggest concern here is the discoverability of this option - what do the exceptions look like today? How can we make sure most users can resolve this on their own regardless of the build system they use?

**Comment by srujzs** [comment]
Yeah, I think it might be worthwhile to make it more descriptive so users know exactly how to disable the flag. Currently, DDC throws an `Unexpected null check.` with the stack trace pointing to the `checkNativeNonNull` function. Maybe a sentence here mentioning it would be useful for them to file a bug on our sdk, and to disable `native-null-assertions` if they want to silence the error.

**Comment by jakemac53** [comment]
I think we will need some really specific links here to documentation for internal and external users (hopefully an internal only link is OK for this?). Exactly _how_ you disable these assertions is different for different people - flutter web, general dart web, and internal equivalents will all be different.

**Comment by srujzs** [comment]
If we are going the route of writing documentation for disabling this check for different entry points, I think we'd need it to be external as well. I wonder if we can place a markdown file in the sdk for this.

**Comment by jakemac53** [comment]
I was a bit unclear :). What I was really suggesting is we print out two links - one for internal and one for external users. So for instance the message could be something like this:

```
It looks like you have discovered an internal issue with the Dart html bindings :(. Please file an issue at <link>.

You can work around this issue by removing these non-null assertions for native web apis by following the instructions in one of these links:

Open source users: <link>
Internal google users: <link> 
```

**Comment by srujzs** [comment]
Ah, I see. Yeah, that makes sense considering we probably don't want to publish information about google3.

**Comment by sigmundch** [comment]
We can also keep it with just the external link and patch the message internally (I believe we have done similar patches in the past)

**Comment by vsmenon** [comment]
Do we have an owner / action here as well?  We're aiming to cut soon for beta.

**Comment by srujzs** [comment]
Sorry, though this was the DDC bug. This will be rolled out incrementally in build systems external to the SDK (I think Flutter and google3 are the only others ones besides build_web_compilers I can think of). Can this be untied from the November release, Siggi?

**Comment by franklinyow** [comment]
@sigmundch Does this need to move out of the Oct milestone?

**Comment by sigmundch** [comment]
@franklinyow do you prefer we keep this with a milestone or without one? The work is no longer bound to changes in the SDK repo and therefore are not blocking any SDK release. For now I moved them to the november milestone (december release) to track that we intend to have this done soon, but it would be fine to drop the milestone too.

**Comment by franklinyow** [comment]
@sigmundch LGTM.

**Comment by srujzs** [comment]
https://github.com/flutter/flutter/issues/71614 tracks the Flutter work. The flag is enabled by default for the Flutter tool, so I think with that, build_web_compilers, and google3, the work here is done.
