### ISSUE TITLE
Dart_NewWeakPersistentHandle finalizer throws errors

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#4378]
If a persistent Dart_Handle is passed as a peer to Dart_NewWeakPersistentHandle, accessing that handle in the finalizer callback causes the following error:

&nbsp;&nbsp;&nbsp;&nbsp;runtime/vm/handles_impl.h:66: error: expected: isolate-&gt;no_handle_scope_depth() == 0

Note that this only reproduces in the debug build of the VM; the no_handle_scope_depth check is compiled out in the release build.

Here's code that demonstrates the issue: https://gist.github.com/03dfc77504c534cf16eb

**Comment by iposva-google** [comment]
Verified that the documentation now states that "It is illegal to call into the VM from the callback."
