### ISSUE TITLE
User reported issue: weird text highlighting drift with inserted cast.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#43804]
See @DanTup 's [comment here](https://github.com/dart-lang/sdk/issues/43178#issuecomment-709333383), point 2.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
