### ISSUE TITLE
dart migrate should update the user's analysis_options.yaml file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43806]
When running `dart migrate` on a pre-nnbd-flag-flip sdk, we should insert the correct null safety opt-in into the user's analysis options file.

We've had this feature previously (https://www.google.com/url?q=https://github.com/dart-lang/sdk/commit/4f2e21b351dcd730ba28d1f4f85bf0edb0ae9272%23diff-dc8e2853c1073e53d0065716c282a204cf4801122990ae7c7ebfbfb13d89ec40&sa=D&ust=1602698527784000&usg=AOvVaw0C_kCAns2zYImIwRj7AdoP)

**Comment by srawlins** [comment]
CL is out for review. https://dart-review.googlesource.com/c/sdk/+/167862
