### ISSUE TITLE
[vm] Ensure that all intrinsics support unboxed parameters and return value

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#43819]
With null safety compiler has more opportunities to unbox parameters and return values.

We need to carefully check that all our intrinsics (both graph and asm) support unboxed parameters and return values. Intrinsics should either handle both unboxed and boxed, or issue a fatal error to avoid silently generating incorrect code.

Example of missing support for unboxed parameter: https://github.com/dart-lang/sdk/issues/43810.

@mkustermann @mraleph

**Comment by mkustermann** [comment]
As a conservative mechanism, I have suggested recently to add a bidirectional mapping between recognized methods in VM and in Dart source code by adding a pragma and checking it. @askeksa-google is working on this and will take advantage of it in the signature shaker and the plan is to also do this for unboxing implementation in TFA.

We can then re-visit this to allow more precision without the existing fragile code.

**Comment by mkustermann** [comment]
One possible way for graph intrinsics in particular, would be to either run a select representations pass and/or add a flow graph checker verification pass to ensure representations match.
