### ISSUE TITLE
[VM] VM test failures with null safety enabled

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43817]
I'm tracking down failures with the [flag flip CL](https://dart-review.googlesource.com/c/sdk/+/166790) and am seeing some failures (for example [here](https://ci.chromium.org/p/dart/builders/try/vm-canary-linux-debug-try/38866?)).  

Looking into it briefly, I see tests that look like this:

```
TEST_CASE(DartAPI_ExternalStringIndexOf) {
  const char* kScriptChars =
      "main(String pattern) {\n"
      "  var str = 'Hello World';\n"
      "  return str.indexOf(pattern);\n"
      "}\n";
  Dart_Handle lib = TestCase::LoadTestScript(kScriptChars, NULL);
```

The failures indicate that the script being built up there is not being treated as opted in, which makes sense.  Presumably this needs to be opted out - either by including an opt out string in the code there (`// @dart = 2.9`) or probably better by programmatically calling the compiler with a language version of 2.9 (I'm assuming such APIs exist).

cc @a-siva @munificent @franklinyow

**Comment by leafpetersen** [comment]
Any updates on this?

**Comment by franklinyow** [comment]
Any update?  Thx

**Comment by leafpetersen** [comment]
These seemed to be green in the latest run, thanks!

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/169144 accounted for the failures.
