### ISSUE TITLE
[CP][beta channel][stable channel] Fix for bug in the optimizing compiler in the write barrier elimination

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#43822]
**Commit(s) to merge**: 32dfefbea17d92302147bec203324606200315f9

**Merge instructions**: Merges cleanly.

**What's the problem**:

We had a bug in the optimizing compiler in the write barrier elimination which can cause memory corruption and therefore undefined behavior, possibly leading to crashes.

**What is the fix**: 

Correctly handle arrays in write-barrier elimination in presense of phis.

**Why cherry-pick**:

To avoid flaky crashes or undefined behavior.

**Risk**: Low

**Link to original  issue(s)**:
* https://github.com/dart-lang/sdk/issues/43770
* https://github.com/dart-lang/sdk/issues/43786

/cc @a-siva @athomas @franklinyow

**Comment by franklinyow** [comment]
@mkustermann Can you edit this request with our new template?  It will help the scrum team to approve this faster without going back for more information.  You can find the link to the template at the bottom of this page : https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel

**Comment by franklinyow** [comment]
@vsm @pcsosinski

**Comment by pcsosinski** [comment]
based on https://github.com/dart-lang/sdk/issues/43770, should we pick this to stable?  @dnfield for thoughts on whether this is needed for Flutter 1.22

**Comment by dnfield** [comment]
I'm having a little trouble getting a sense of how many Flutter customers this would actually impact.

Once it rolls into the engine I'll see if I can run a couple tests on some memory related issues we've been looking at.

**Comment by franklinyow** [comment]
@dnfield An update on if we need it in stable?

**Comment by franklinyow** [comment]
Approval for beta, OK if flutter want to bring to stable

**Comment by athomas** [comment]
Merged to beta in bba1aeca3a6062bbedb0147a39c093a9ff7291b2 (2.11.0-213.4.beta). The issue will be left open until merged to stable (there is no separate tracking issue for the merge-to-beta).

**Comment by athomas** [comment]
Merged to stable for 2.10.3 (ecf9ce8ef42de11033801b2870e8b310c3722902).
