### ISSUE TITLE
include the stack depth (the frame count) in the vm service protocol's pause event

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#43829]
The vm service protocol's pause event (see https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md, `class Event`) contains information about the top stack frame when an isolate is paused.

Some clients need a bit more information in order to efficiently render a view of the stack frames when paused. VS Code for example, wants to know the total number of stack frames. This allows it to page through the frames, requesting 10 at a time.

The VS Code dart integration currently implements this via calling `getStack()` when paused to get the count of the total number of frames. It then call `getStack()` whenever VS Code requests 10 additional frames.

For some vm service protocol implementations (specifically, the dart web `package:dwds` implementation), `getStack()` can be very slow to return, on the order of ~4-5 seconds for some very deep stacks. We could double the speed of the VS Code implementation if the pause event included the depth of the stack - the number of frames.

cc @bkonyi @DanTup @grouma

**Comment by grouma** [comment]
Related to the following:
https://github.com/dart-lang/sdk/issues/43826
https://github.com/dart-lang/sdk/issues/43827
https://github.com/dart-lang/webdev/issues/993

**Comment by bkonyi** [comment]
Is this issue relevant anymore @grouma @DanTup?

**Comment by grouma** [comment]
I believe this is not required anymore given the new `limit` parameter. Closing.

**Comment by DanTup** [comment]
Yup, we have a workaround for VS Code that no longer requires it. If for some reason that stops working in future (it's not technically to-spec), I think it'd be better to try to get VS Code to remove the requirement for this (there's an open issue at https://github.com/microsoft/vscode/issues/31851).
