### ISSUE TITLE
[CP] Cherry-pick for AOT compiler assertion preventing certain apps from compiling

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#43835]
**commit(s) to merge**: 13d2937f768180b083ce6ffdcf7d3cd9a4c5440a

**merge instructions**: clean (auto)merge

**What is the issue**: Compiling AOT applications that have classes with many fields where our whole-world analysis tells us that the 65+th field can be unboxed and an implicit getter function is needed, will hit a too conservative release assertion, thereby not allowing compiling those applications. The assertion assumes we never have unboxed return values of implicit getter functions if the field itself is boxed - though this can happen if the field is outside a 64-bitmap (in which case we box the field).

**What is the fix**: Removing the release assertion and allowing boxed-field+unboxed-return situation.

**Why cherrypick**: Allows AOT compiling applications that wouldn't compile otherwise.

**Risk**: Low.

**Link to original  issue(s)**:

* https://github.com/flutter/flutter/issues/67803

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
@pcsosinski

**Comment by franklinyow** [comment]
Approved

**Comment by athomas** [comment]
Merged to beta in bba1aeca3a6062bbedb0147a39c093a9ff7291b2 (2.11.0-213.4.beta). The issue will be left open until merged to stable (there is no separate tracking issue for the merge-to-beta).

**Comment by athomas** [comment]
Merged to stable for 2.10.3 (ecf9ce8ef42de11033801b2870e8b310c3722902).
