### ISSUE TITLE
Support for nonfunction type aliases

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43832]
This is the overall epic for nonfunction type aliases.

Main language issue: https://github.com/dart-lang/language/issues/65
Specification: https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md

**Comment by MrBirb** [comment]
@stereotype441 Looks like main language issue is closed.

**Comment by eernstg** [comment]
Yes, this feature has been shipped in 2.13.
