### ISSUE TITLE
The mssql database connection fails.

### ISSUE THREAD

**Issue by ebubekirb** [dart-lang/sdk#43846]
libdart_mssql.so: cannot open shared object file: No such file or directoryerror: library handler failed. When I try to connect to the mssql database, I get an error like this.

import 'package:dart_mssql/dart_mssql.dart';  the only library I use.

**Comment by ebubekirb** [comment]
Thank you @a-siva but nothing changed.

flutter doctor command output: 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.23.0-19.0.pre.80, on Linux, locale tr_TR.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (4 available)

I am working on a Linux machine, but I tried it on a Windows machine and encountered the same error.

I'm not sure if there is a problem as I am using a Linux machine.

**Comment by vanesyan** [comment]
If you trying to connect from the Flutter application it is not possible according to the README from the https://github.com/MoacirSchmidt/dart_mssql.
> This package is not suitable for flutter or web projects. It only runs on server-side apps.
this line in the **Important** section

**Comment by dcharkes** [comment]
There's already an issue on the issue tracker of dart_mssql to track Flutter support for Windows https://github.com/MoacirSchmidt/dart_mssql/issues/5.

High level remark, Flutter packages using `dart:ffi` need linking and shipping configurations, while Dart standalone packages do not. (They can just use `dlopen` and require no linking / shipping steps). See Flutter [documentation](https://flutter.dev/docs/development/platform-integration/c-interop).
