### ISSUE TITLE
[pkg/frontend_server] frontend_server unit tests failing with null safety enabled

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43844]
[This CL](https://dart-review.googlesource.com/c/sdk/+/166790) tests out flipping on the experiment flag and bumping the SDK version.  I see failures on frontend_server unit tests [here](https://ci.chromium.org/p/dart/builders/try/pkg-linux-release-try/42754?) . 

cc @alexmarkov can you triage and help find the right person to work on this (you're the last committer I see in the log)?

**Comment by leafpetersen** [comment]
cc @munificent @franklinyow

**Comment by alexmarkov** [comment]
Fronted-server tests create and compile standalone Dart scripts, so we should adjust those unit tests in one of the following ways:
* migrate generated Dart scripts to null safety;
* opt-out generated Dart scripts by adding `// @dart=2.xx' comments;
* opt-out by passing `--enable-experiment=no-non-nullable` to the front-end server.

**Comment by aam** [comment]
@alexmarkov wrote

> migrate generated Dart scripts to null safety;

How does one do this? There is nothing null-unsafe in the code. The tests currently use `.packages` file, [changing then to use `.dart_tool/package_config.json`](https://gist.github.com/aam/ffb2dd3246f7ff815dd55177bc9177d5) file fixes few test failures, but two are still failing with `  CompilationModeError[Mixed compilation mode found: NonNullableByDefaultCompiledMode.Disabled and NonNullableByDefaultCompiledMode.Strong.]
` reported by frontend.

**Comment by aam** [comment]
Adding @jensjoha for those:
```
00:02 +23 -1: full compiler tests unsafe-package-serialization [E]

  CompilationModeError[Mixed compilation mode found: NonNullableByDefaultCompiledMode.Disabled and NonNullableByDefaultCompiledMode.Strong.]

  package:kernel/binary/ast_from_binary.dart 778:11              BinaryBuilder._readOneComponent
  package:kernel/binary/ast_from_binary.dart 548:33              BinaryBuilder.readComponent.<fn>
...

00:02 +23 -2: full compiler tests incremental-serialization [E]

  CompilationModeError[Mixed compilation mode found: NonNullableByDefaultCompiledMode.Disabled and NonNullableByDefaultCompiledMode.Strong.]

  package:kernel/binary/ast_from_binary.dart 778:11              BinaryBuilder._readOneComponent
  package:kernel/binary/ast_from_binary.dart 548:33              BinaryBuilder.readComponent.<fn>

```

**Comment by alexmarkov** [comment]
Which unit tests are failing with that error? Could you post full log? It looks like that error may indicate a mismatch between null safety modes of dill files being loaded. Please check that all tests are generating and using dill files in the same mode (sound null safety is enabled if `--sound-null-safety` option is specified or main script is opted-in).

@jensjoha

**Comment by alexmarkov** [comment]
These errors might be actually bugs in incremental-serialization and unsafe-package-serialization: they don't set Component._mode when creating and serializing a new component.

@aam Could you try something like

```patch
diff --git a/pkg/front_end/lib/src/fasta/incremental_serializer.dart b/pkg/front_end/lib/src/fasta/incremental_serializer.dart
index 59d84880a4f..87ca25a61f8 100644
--- a/pkg/front_end/lib/src/fasta/incremental_serializer.dart
+++ b/pkg/front_end/lib/src/fasta/incremental_serializer.dart
@@ -301,7 +301,8 @@ class IncrementalSerializer {
     Component singlePackageLibraries = new Component(
         libraries: libraries,
         uriToSource: component.uriToSource,
-        nameRoot: component.root);
+        nameRoot: component.root)
+      ..setMainMethodAndMode(null, false, component.mode);
 
     ByteSink byteSink = new ByteSink();
     final BinaryPrinter printer = new BinaryPrinter(byteSink);
diff --git a/pkg/frontend_server/lib/frontend_server.dart b/pkg/frontend_server/lib/frontend_server.dart
index ee3f98e87d0..841d3b8e110 100644
--- a/pkg/frontend_server/lib/frontend_server.dart
+++ b/pkg/frontend_server/lib/frontend_server.dart
@@ -1090,7 +1090,8 @@ class FrontendCompiler implements CompilerInterface {
       Component singleLibrary = Component(
           libraries: libraries,
           uriToSource: deltaProgram.uriToSource,
-          nameRoot: deltaProgram.root);
+          nameRoot: deltaProgram.root)
+        ..setMainMethodAndMode(null, false, deltaProgram.mode);
       ByteSink byteSink = ByteSink();
       final BinaryPrinter printer = printerFactory.newBinaryPrinter(byteSink);
       printer.writeComponentFile(singleLibrary);
```

**Comment by jensjoha** [comment]
Related: https://github.com/dart-lang/sdk/issues/43807#issuecomment-712021584

I'll look into it.

**Comment by mraleph** [comment]
(I assigned @aam & @jensjoha just so that it is clear that somebody is looking at this just by looking at this list of issues in the Epic)

**Comment by jensjoha** [comment]
https://dart-review.googlesource.com/c/sdk/+/168482 will fix at least some of this.

**Comment by leafpetersen** [comment]
Still seeing one failure [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865884803271263264/+/steps/test_results/0/logs/new_test_failures__logs_/0).

**Comment by aam** [comment]
@leafpetersen no fixes landed yet, so the failures in frontend_server_test you are seeing are the same as before.
I believe @jensjoha is still looking at two failures https://github.com/dart-lang/sdk/issues/43844#issuecomment-712490243

**Comment by aam** [comment]
https://dart.googlesource.com/sdk/+/deba2f7e6505e94496d25b58b6e262c96bb4ad39 landed few fixes mentioned in https://github.com/dart-lang/sdk/issues/43844#issuecomment-712484531

**Comment by leafpetersen** [comment]
Thanks all!  Confirmed that I'm not seeing any more frontend_server unit test failures on the pkg-linux-release-try bot.  🎉

**Comment by leafpetersen** [comment]
I'm seeing one of these failures [pop back up now](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865340169017615360/+/steps/test_results/0/logs/new_test_failures__logs_/0).

**Comment by a-siva** [comment]
Please see comment in https://github.com/dart-lang/sdk/issues/43845

**Comment by jensjoha** [comment]
pkg/frontend_server/test/frontend_server_test.dart failures can be "fixed" with something like
```
diff --git a/pkg/frontend_server/test/frontend_server_test.dart b/pkg/frontend_server/test/frontend_server_test.dart
index 470e340b00a..153e13e0090 100644
--- a/pkg/frontend_server/test/frontend_server_test.dart
+++ b/pkg/frontend_server/test/frontend_server_test.dart
@@ -1726,6 +1726,9 @@ class BarState extends State<FizzWidget> {
         '--sdk-root=${sdkRoot.toFilePath()}',
         '--incremental',
         '--platform=${ddcPlatformKernel.path}',
+        // The platform is not found null safe so we can't compile it as such
+        // either.
+        '--no-sound-null-safety',
         '--output-dill=${dillFile.path}',
         '--packages=${packages.path}',
         '--target=dartdevc',
@@ -1912,6 +1915,9 @@ class BarState extends State<FizzWidget> {
         '--sdk-root=${sdkRoot.toFilePath()}',
         '--incremental',
         '--platform=${ddcPlatformKernel.path}',
+        // The platform is not found null safe so we can't compile it as such
+        // either.
+        '--no-sound-null-safety',
         '--output-dill=${dillFile.path}',
         '--target=dartdevc',
         '--packages=${tempDir.path}/.packages',
```

It doesn't seem great, though, that the platform is not agnostic (I'm guessing now that that's only the VMs platform?) --- and that when given a platform that is either strong or weak, autodetection of the entry point is still performed (
```
    if (nullSafety == null &&
        compilerOptions.isExperimentEnabled(ExperimentalFlag.nonNullable)) {
      await autoDetectNullSafetyMode(_mainSource, compilerOptions);
    }
```
in pkg/frontend_server/lib/frontend_server.dart), which can then disagree with the platform that is loaded.

**Comment by leafpetersen** [comment]
Thanks @jensjoha .  @johnniwinther do you want me to keep this open to track any issues with sound mode detection, or is this WAI?

**Comment by a-siva** [comment]
The VM's platform dill file is built in agnostic mode, not sure what you mean by the platform is not agnostic.

**Comment by annagrin** [comment]
@a-siva those tests use `ddc_sdk.dill` which is compiled in weak mode. I've been struggling to fix the same issue in https://dart-review.googlesource.com/c/sdk/+/169249 - any ideas?

**Comment by leafpetersen** [comment]
These started failing again after being green.  @annagrin is that expected?

**Comment by leafpetersen** [comment]
Ok, fix for this is in the CL, seems to be green again.
