### ISSUE TITLE
[pkg/dev_compiler] dev_compiler unit tests failing with null safety enabled

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43843]
[This CL](https://dart-review.googlesource.com/c/sdk/+/166790) tests out flipping on the experiment flag and bumping the SDK version.  I see failures on pkg/dev_compiler unit tests [here](https://ci.chromium.org/p/dart/builders/try/pkg-linux-release-try/42754?) .  

@sigmundch @nshahan can you triage and find the right person to look into this?

**Comment by leafpetersen** [comment]
cc @munificent @franklinyow

**Comment by nshahan** [comment]
A fix is out for review to add the language version comment to some synthetic test files https://dart-review.googlesource.com/c/sdk/+/168441.

**Comment by leafpetersen** [comment]
Thanks!  I think I'm still seeing [one failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865963650562053056/+/steps/test_results/0/logs/new_test_failures__logs_/0) though.

**Comment by leafpetersen** [comment]
Oddly, I now seem to be seeing failures on an expression_compiler test again, was there a regression?  https://ci.chromium.org/p/dart/builders/try/pkg-linux-release-try/42881?

**Comment by nshahan** [comment]
😕 

Strange, I'll take another look.

**Comment by nshahan** [comment]
A few new test cases landed with source code that needs to be opted out. I'll update the test, hopefully the third time is a charm.

**Comment by leafpetersen** [comment]
Thanks, confirmed no more failures!

**Comment by leafpetersen** [comment]
The expression compiler test seems to have [gone red again](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865340169017615360/+/steps/test_results/0/logs/new_test_failures__logs_/0).

**Comment by leafpetersen** [comment]
Actually, no they haven't, apparently I can't read.
