### ISSUE TITLE
Android Studio Dart analyzer erroneously shows 'colors' property of LinearGradient class as non-existent

### ISSUE THREAD

**Issue by MikeCamino** [dart-lang/sdk#43847]
Android Studio Dart analyzer erroneously shows 'colors' property of LinearGradient class as non-existent.
Try to write something like
`LinearGradient(colors: [Color(0xFFFF4F4F), Color(0xFFB454FF)])`
and you will see the following error: "The named parameter 'colors' isn't defined."

At the same time CLI `dart analyze` doesn't include this error

Also autosuggest shows strange list of available fields
<img width="467" alt="Screenshot 2020-10-19 at 14 39 09" src="https://user-images.githubusercontent.com/1525248/96445680-fa225080-1218-11eb-8bf4-de581c472f3f.png">

## Version information
- `Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-RU)`
- `Dart SDK version: 2.10.2 (stable) (Tue Oct 13 15:50:27 2020 +0200) on "macos_x64"`
- `IDEA Dart plugin 201.9002`
- `IDEA Flutter plugin 50.0.2`
- `IDEA AI-201.8743.12.41.6858069`
- `2.10.2`
- `AI-201.8743.12.41.6858069, JRE 1.8.0_242-release-1644-b3-6222593x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.7, screens 1440x900  Retina`

**Comment by ajain-bst** [comment]
For me, its the opposite behaviour. `dartanalyze` does report this incorrect error, but VScode doesnt raise it.

**Comment by srawlins** [comment]
I suspect something thinks this is a null safe library, and something else thinks this is not a null safe library. So the parameters of [LinearGradient](https://api.flutter.dev/flutter/painting/LinearGradient/LinearGradient.html) are being read as

* `begin` (with type `AlignmentGeometry`)
* `end` (with type `AlignmentGeometry`)
* `List` (with type `required`)

**Comment by srawlins** [comment]
Closing as stale, since we now only support null-safe libraries; but please re-open if you can reproduce this with a recent version of Dart.
