### ISSUE TITLE
[pkg/vm] vm pkg unit tests failing with null safety enabled

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43845]
[This CL](https://dart-review.googlesource.com/c/sdk/+/166790) tests out flipping on the experiment flag and bumping the SDK version.  I see failures on dartdev unit tests [here](https://ci.chromium.org/p/dart/builders/try/pkg-linux-release-try/42754?) .  

cc @alexmarkov @a-siva can you triage and find the right person to look into this?

**Comment by leafpetersen** [comment]
cc @munificent @franklinyow

**Comment by leafpetersen** [comment]
Just checking in on this, any updates?

**Comment by franklinyow** [comment]
Any update? Thx.

**Comment by leafpetersen** [comment]
I think this is fixed, I don't see this in the logs.

**Comment by leafpetersen** [comment]
Oops, sorry, I misread the log, still seeing one [failure here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865332807421763408/+/steps/test_results/0/logs/new_test_failures__logs_/0).

**Comment by a-siva** [comment]
The failures in pkg/vm/test/incremental_compiler_test are fixed by
https://dart-review.googlesource.com/c/sdk/+/169144
and one change that needs to be made in the flag flip CL

```
--- a/pkg/vm/test/incremental_compiler_test.dart
+++ b/pkg/vm/test/incremental_compiler_test.dart
@@ -71,7 +71,7 @@ main() {

           .writeLibraryFile(component.mainMethod.enclosingLibrary);
       expect(
           buffer.toString(),
equals('library;\n'
+          equals('library /*isNonNullableByDefault*/;\n'

               'import self as self;\n'
               '\n'
               'static method main() → dynamic {}\n'));
@@ -93,7 +93,7 @@ main() {
           .writeLibraryFile(component.mainMethod.enclosingLibrary);
       expect(
           buffer.toString(),
equals('library;\n'
+          equals('library /*isNonNullableByDefault*/;\n'

               'import self as self;\n'
               '\n'
               'static method main() → dynamic {}\n'));
@@ -642,7 +642,7 @@ main() {
           "}\n");
```

The other failure in test pkg/frontend_server/test/frontend_server_test seems to be a dart2js issue and @annagrin is going to look into it tomorrow.

**Comment by leafpetersen** [comment]
Awesome thanks!  Confirmed that this test is no longer failing.
