### ISSUE TITLE
[pkg/dartdev] dartdev pkg tests are failing with null safety enabled

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43842]
[This CL](https://dart-review.googlesource.com/c/sdk/+/166790) tests out flipping on the experiment flag and bumping the SDK version.  I see failures on dartdev unit tests [here](https://ci.chromium.org/p/dart/builders/try/pkg-linux-release-try/42754?) .  Looking at the first one, it appears that the analysis_server is being called programmatically, and most likely needs to set a language version.

@devoncarew can you triage and find the right person to fix this?

**Comment by leafpetersen** [comment]
cc @munificent @franklinyow

**Comment by devoncarew** [comment]
I see many other failures on that referenced builder, but I assume this issue is only about the pkg/dartdev failures?

```
pkg/dartdev/test/commands/analyze_test
pkg/dartdev/test/commands/migrate_test
pkg/dartdev/test/commands/pub_test
pkg/dartdev/test/smoke/smoke_test
```

FYI, I'm OOO this week.

When you say set a language version I'm confused - I would have thought that would only be necessary for raw scripts, not for things in directories with pubspec files?

cc @scheglov for general triage. If this turns out to be an issue with how dartdev is invoking the kernel snapshots (for pub, the analysis server, ...), then @bkonyi would be the best person to triage (he may be OOO the first few days of this week).

**Comment by leafpetersen** [comment]
> I see many other failures on that referenced builder, but I assume this issue is only about the pkg/dartdev failures?

Yes, I filed separate issues for each of the different `pkg/X` failure categories that I saw.



> When you say set a language version I'm confused - I would have thought that would only be necessary for raw scripts, not for things in directories with pubspec files?

I haven't triaged this deeply, but it looks to me like these tests are calling the analysis server with a fragment of dart code, e.g:

```
  test('one error', () {
    p = project(mainSrc: "int get foo => 'str';\n");
    var result = p.runSync('analyze', [p.dirPath]);

    expect(result.exitCode, 3);
    expect(result.stderr, isEmpty);
    expect(result.stdout, contains('A value of type '));
    expect(result.stdout, contains('lib/main.dart:1:16 '));
    expect(result.stdout, contains('return_of_invalid_type'));
    expect(result.stdout, contains('1 issue found.'));
  });
```

This dart code would, prior to the flag flip, be interpreted as non-null safe, and now once the flag is flipped will be interpreted as null safe.  These fragments would presumably need to either be marked with a language version `// @dart = 2.9` or possibly the analysis server should be set up to programatically treat the snippets as opted out.

**Comment by scheglov** [comment]
Looking at [the code](https://github.com/dart-lang/sdk/blob/157ebfe50f399c59a20d603acdf5143ceaa4cccf/pkg/dartdev/test/utils.dart#L29) that is preparing the file system, it seems to me that it should not also write the `.dart_tool/package_config.json`, and configure the current package to have the language version `2.9`. This will opt this package out of Null Safety.

**Comment by devoncarew** [comment]
OK, sounds like the tests would be made to specify a language version (or perhaps, updated so they they return the same results for both pre and post nnbd).

With me out, @jwren has the most familiarity with the tests for `dart analyze`.

**Comment by leafpetersen** [comment]
I'm still seeing failures here, any updates?

**Comment by devoncarew** [comment]
@jwren, ping - it doesn't look like your CL had landed?

**Comment by jwren** [comment]
The PR needs a review... Leaf- adding you.  Also I realized that the smoke tests aren't covered by `test_all.dart` so I will need to follow up.  If I can get a PR reviews early tomorrow I can have it all resolved tomorrow morning.

**Comment by franklinyow** [comment]
How are we doing on this?

**Comment by leafpetersen** [comment]
Confirmed that these are all green now.

**Comment by jwren** [comment]
Thank you @leafpetersen for confirming!  Let myself and @bkonyi know if there are any other issues that come up with NNBD.
