### ISSUE TITLE
Migration tool outputs a large diff for .dart_tool/package_config.json

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43850]
Steps to repro:
- Check out https://github.com/dart-lang/collection/commit/00540dce43a9bc778bfa55935a182799ff00044d (which is just prior to migration to null safety)
- Run `pub get`
- Run `dart migrate . --no-web-preview`

Expected result: the vast majority of the output diff should be lines of code that the tool is going to change, that the user cares about.

Observed result: of the 1261 lines of output, 618 of them appear to be a wholesale replacement of the contents of `.dart_tool/package_config.json`.  This is problematic because (1) this is a generated file that the user doesn't care strongly about, and (2) actually just a single line is being changed.

The migration tool should be modified so that either it just shows the one line that is being changed, or the entire change to `.dart_tool/package_config.json` should be suppressed from the diff output entirely.

Argument in favor of showing just the one line that is being changed: consistent with the rest of the behavior of the tool, so avoids user surprise (shows all changes the tool would make if `--apply-changes` were supplied)
Argument in favor of suppressing this file from the output entirely: easier to implement, avoids showing the user a diff they probably don't care about.

**Comment by stereotype441** [comment]
@mit-mit FYI

**Comment by mit-mit** [comment]
I think there's an additional argument for suppressing the file entirely: This is not a file we want most developers to care about. It's an implementation detail that the majority will happily go about their coding without ever getting exposed to. Thus, not shining any light on it is helpful.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
