### ISSUE TITLE
In migration tool, `--apply-changes` should imply `--no-web-preview`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43866]
Currently if you run `dart migrate --apply-changes`, you get the message `--apply-changes requires --no-web-preview`, which is just annoying.

**Comment by srawlins** [comment]
I can take this on.

**Comment by srawlins** [comment]
To be specific, here's what I propose:

* `--apply-changes` and no value passed for `web-preview`: assume `--no-web-preview`
* `--apply-changes` and `--web-preview` (each explicitly passed): error
* `--no-apply-changes` (or not passed) and no value passed for `web-preview`: assume `--web-preview`
* `--no-apply-changes` and `--no-web-preview` (each explicitly passed): error

**Comment by stereotype441** [comment]
Fixed by 5ac5b710ee826635fd7c9d2839cc6940664cb712
