### ISSUE TITLE
[Flutter/Fuschia] Flutter/Fuschia build failing with the null safety flag flip CL

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43868]
Running [the CL](https://dart-review.googlesource.com/c/sdk/+/166790) to flip the null safety flag on the [flutter-engine-linux-try bot](https://ci.chromium.org/p/dart/builders/try/flutter-engine-linux-try/389?)  I'm seeing [build failures](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865910649982144784/+/steps/build_fuchsia_debug_x64_flutter_shell_platform_fuchsia:fuchsia_fuchsia_tests/0/stdout?format=raw).  From a quick look, my guess is that there are standalone scripts that will need to be opted out of null safety until the can be ported (e.g. by marking them with `// @dart = 2.9`.  Note that I have a script to automatically do this available [here](https://github.com/dart-lang/sdk/blob/master/tools/opt_out_files.dart).

cc @zanderso @jakemac53

**Comment by leafpetersen** [comment]
@chaselatta will take a look at this.

**Comment by chaselatta** [comment]
Added a fix in https://github.com/flutter/engine/pull/22009.

**Comment by chaselatta** [comment]
This has been fixed but I don't seem to be able to close the issue.

**Comment by leafpetersen** [comment]
Thanks!  Closing out.
