### ISSUE TITLE
[flutter-engine] Null safety failures with flag flip on flutter-engine-linux-try

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43872]
I'm seeing some additional failures with the flag flip.  @jakemac53 can you look into any failures [here](https://ci.chromium.org/p/dart/builders/try/flutter-engine-linux-try/391?) that aren't already covered by your PR?  This link is a build from the 2.11 based CL to avoid breakage from the lack of 2.12 compatible packages.

**Comment by jakemac53** [comment]
Yep taking a look now

**Comment by jakemac53** [comment]
Update: I landed a bunch of forward fixes in flutter last week, but the last bot run had an infra failure. Retrying now to see if that is resolved to get the latest results here. The flutter-analyze job is green with the changes made there.

**Comment by jakemac53** [comment]
And on the re-run of course I see failures for flutter-analyze again so looking into those and other remaining failures.

**Comment by jakemac53** [comment]
Still have some remaining failures here https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865360821001700848/+/steps/flutter_test_tool_tests/0/stdout, prs out for the other known issues. Likely won't get around to this one until tomorrow.

**Comment by leafpetersen** [comment]
These seem to be green now.
