### ISSUE TITLE
Expose a SendPort.fromAddress constructor

### ISSUE THREAD

**Issue by long1eu** [dart-lang/sdk#43877]
I'm trying to create another `Isolate` that can register and call plugins in Flutter. While I can create an isolate on the Dart side, there is no way to get a handler of that Isolate and pass it to Java for example and register it with a `FlutterEngine` or with the `PluginRegistry`.

Another way to do it would be to create a `FlutterEngine` on the Java side and then call a Dart callback. This creates a new `Isolate` which is good. But now there is no way for the Dart code from this callback to communicate with the main Isolate.

The Dart ffi exposes a `SendPort` pointer using the `nativePort` getter in the `NativePort` extension. I can send this port address to the second Isolate via platform channel. But there is no way to get the `SendPort` object back from the pointer address.

A simplified example would be this:
```dart
// File created by
// Lung Razvan <long1eu>
// on 21/10/2020

import 'dart:ffi';
import 'dart:isolate';

Future<void> main() async {
  final ReceivePort receivePort = ReceivePort();
  final int port = receivePort.sendPort.nativePort;
  print(port);

  Isolate.spawn(_second, port);
  receivePort.listen((message) {
    print(['received on ${Isolate.current.hashCode}']);
  });
}

Future<void> _second(int message) async {
  print(['started with port $message']);
  final SendPort port = SendPort.fromAddress(message);
  port.send('new message');
}
```  
The limitation that this use-case imposes is that you can not send a `SendPort` to the second `Isolate`.
(`SendPort.fromAddress` does not exists yet).

@dcharkes 

https://github.com/dart-lang/ffi/issues/54

**Comment by mkustermann** [comment]
You can send `receivePort.sendPort` directly instead of `receivePort.sendPort.nativePort`. The purpose of the latter is to be able to send messages to dart from C only.

**Comment by long1eu** [comment]
You can not send a SendPort through PlatformChannel.

**Comment by jayjah** [comment]
why not? please look at the following code:
intern Isolate Communication
```dart
//anywhere in your code, start you isolate
    Isolate isolate = await Isolate.spawn(anotherIsolateCommunication, ourFirstReceivePort.sendPort);

  static anotherIsolateCommunication(SendPort sendPort) async {
    // open our receive port. this is like turning on
    // our cellphone.
    var ourReceivePort = ReceivePort();

    // tell whoever created us what port they can reach us on
    // (like giving them our phone number)
    sendPort.send(ourReceivePort.sendPort);

    // listen for text messages that are sent to us,
    // and respond to them with this algorithm
    await for (var msg in ourReceivePort) {
      var data = msg[0];                // the 1st element we receive should be their message
      print('IsolateHandler received "$data"');

      SendPort replyToPort = msg[1];    // the 2nd element should be their port

      // add a little delay to simulate some work being done
      if (data != null && data is String && data.length>1) {

      } else replyToPort.send("");

      // you can close the ReceivePort if you want
      if (data == "bye") ourReceivePort.close();
    }
  }
```

**Comment by long1eu** [comment]
I think that my example code made things worse. I'm not creating the Isolate from Dart I'm creating it from Java using the FlutterEngine class.

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java

**Comment by ds84182** [comment]
Since this is in Flutter, shouldn't you use [IsolateNameServer](https://api.flutter.dev/flutter/dart-ui/IsolateNameServer-class.html)?

**Comment by long1eu** [comment]
@ds84182 You are a genius. I know there was a way to register SendPorts, but I thought it belonged to ffi and that it might have been removed in preview. Thank you so much.
