### ISSUE TITLE
Migration tool should understand built_value @nullable annotations

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43878]
When a class implements `Built` (from `package:built_value`), the migration tool should interpret all getters in it that are annotated with `@nullable` to have nullable types, and all other getters to have non-nullable types.  It should also remove the `@nullable` annotations as part of the migration process.

(Note that use of `@nullable` outside of a class implementing `Built` is outside recommended usage, so it's not too critical what the tool does in this situation.)

**Comment by davidmorgan** [comment]
Slight clarification, this only applies to abstract getters in `Built` classes; non-abstract getters should be treated as normal.

Thanks!

**Comment by stereotype441** [comment]
> Slight clarification, this only applies to abstract getters in `Built` classes; non-abstract getters should be treated as normal.
> 
> Thanks!

Got it, thanks!

**Comment by michalt** [comment]
This is causing some ongoing pain when migrating code internally, would it be possible to bump the priority a bit?

**Comment by iinozemtsev** [comment]
I've hit this issue today while migrating some code with dozens of built value fields, is it possible to prioritize this?

**Comment by stereotype441** [comment]
@iinozemtsev sure.  I'm looking for a change of pace today, and it seems like a good time to take this on.
