### ISSUE TITLE
DDC should add a flag to turn weakNullSafetyWarnings into errors

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#43882]
`weakNullSafetyWarnings` is used to enable warnings in unsound mode that would be errors in sound null-safety. DDC uses this runtime flag to toggle this behavior. In order to support/encourage internal library migration, there should exist a flag to turn these warnings into errors. There is concern here, however, of using this flag on tests whose legacy library dependencies would be blocked during the libraries' migration by these tests.

cc @nshahan @jakemac53 @davidmorgan 

I'm not sure if there was a consensus for this, but it seems like we still want this feature with the caveat that this flag should be used with care.

**Comment by davidmorgan** [comment]
Thanks!

In google3 we can completely control where the flag is used :) for example requiring particular migration state of dependencies. So, no downside :)

**Comment by jakemac53** [comment]
Could I get some clarification on what the difference would be between this and `--null-safety-asserts`?

**Comment by nshahan** [comment]
Enabling the `--null-safety-asserts` flag adds assertions that values are not null when passed as method parameters that have been statically typed as non-nullable in opted-in libraries.

The weak mode warnings (or optionally changed into errors) discussed here will trigger whenever a subtype check is allowed to pass that would have failed if this were running in sound mode. Some cases will overlap, for example performing subtype checks when passing values that are statically typed as dynamic to non-nullable method arguments will catch the same null value error. The weak mode warnings/errors will trigger in subtype checks for types like function types or generic types that can contain other types embedded in them. The value may not be null but the type might not be correct in terms of the nullability of types embedded within. They will also trigger in cases like `[1, 2, null] as List<int>`. Explicit casts that should fail will not be caught by enabling the `--null-safety-asserts`.

@davidmorgan One important interaction we should focus on are instance of checks. For example `[1, 2, null] is List<int>` will be `true` (with a warning) in weak mode and `false` in sound mode. Turning the warnings into errors will make the check throw in weak mode, not change the result to false. Is that what you are expecting here?

**Comment by davidmorgan** [comment]
Thanks Nick.

Stricter type checks sound good and what I was expecting.

Thanks for the detail on `is` checks. Did I understand correctly: the warning is issued when the result of the check is going to change under sound mode?

That's not part of what I was expecting :) but we do definitely want to catch those somehow.

Would it be possible to make a PR/CL turning these warnings into errors, please, so I can try it and see how it interacts with some existing tests? Doesn't have to be a flag, since I'll patch it, it can just be hardcoded .Thanks!

**Comment by nshahan** [comment]
> Did I understand correctly: the warning is issued when the result of the check is going to change under sound mode?

Yes, exactly.

> Would it be possible to make a PR/CL turning these warnings into errors, please, so I can try it and see how it interacts with some existing tests? Doesn't have to be a flag, since I'll patch it, it can just be hardcoded .Thanks!

I created https://dart-review.googlesource.com/c/sdk/+/169120.

**Comment by nshahan** [comment]
The option was added in https://github.com/dart-lang/sdk/commit/bfe8aa8d5bcbc3a4fe858faf8c6a3150ddc9ab4a.
