### ISSUE TITLE
fix for `omit_local_variable_types` can leave unused imports

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#43887]
Any fix that removes a type reference (or API call) might leave dead imports.

We might consider removing the (newly) unneeded import when performing the fix.

This is especially impacting in applying bulk fixes.

Related to: #43886.

**Comment by srawlins** [comment]
With _so many_ lints and _so many_ fixes (I love it), I think a more general solution might be needed.

1. Would it be too crazy to repeatedly fix until stability is reached? In round one, a type might be removed; in round two an import might be removed; in round three a pub dependency might be removed.
2. Are there not too many rules that a fix might trigger? unused_xyz, unnecessary_xyz? A second round could be triggered that just fixes those.

**Comment by bwilkerson** [comment]
I had forgotten about (or never known about) this issue. The `dart fix` tool has already been updated to do just the kind of iteration you suggested. I'm going to close this issue with the assumption that there isn't any additional work required.

**Comment by srawlins** [comment]
That's excellent, I had no idea!
