### ISSUE TITLE
[nnbd_migration] unit tests fail with null safety enabled

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43883]
See failures [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865798738483684272/+/steps/test_results/0/logs/new_test_failures__logs_/0) .  It looks like these tests are generating snippets of dart code and running them through the migration tool, and when the experiment flag is turned on by default these snippets get treated as already opted in and the tests fail.

cc @srawlins @stereotype441 @devoncarew

**Comment by leafpetersen** [comment]
These are green now, thanks!

**Comment by leafpetersen** [comment]
I'm seeing this test failing still:

analyzer-unittest-asserts-release-win:pkg/nnbd_migration/test/front_end/region_renderer_test

**Comment by leafpetersen** [comment]
Logs [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865236512862064912/+/steps/test_results/0/logs/new_test_failures__logs_/0) and [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865236512862065120/+/steps/test_results/0/logs/new_test_failures__logs_/0).

**Comment by stereotype441** [comment]
I have a fix baking on trybots now: https://dart-review.googlesource.com/c/sdk/+/169421

**Comment by leafpetersen** [comment]
Confirmed, thanks!
