### ISSUE TITLE
Provide custom headers for the websocket in vm_service

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#43898]
Specifically this function: https://github.com/dart-lang/sdk/blob/master/pkg/vm_service/lib/vm_service_io.dart#L31

Blocks https://github.com/flutter/flutter/pull/68654

Some internal customers at google currently pass custom headers to the web service protocol, which flutter_driver is able to support because it owns the websocket.

@bkonyi

**Comment by bkonyi** [comment]
You can provide [VmService](https://github.com/dart-lang/sdk/blob/master/pkg/vm_service/lib/src/vm_service.dart#L1553) with an input stream and a writer callback which can be used to provide your own `WebSocket`.
