### ISSUE TITLE
Separate TypeArguments into separate TypeParameters (binding) and TypeArguments (use) classes.

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#43901]
In CL [168101](https://dart-review.googlesource.com/c/sdk/+/168101), we save the default arguments (i.e., results of [instantiating to bounds](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md)) calculated by the CFE in `TypeParameter` objects. However, these default arguments are only needed when the instantiator of a `TypeArguments` object containing only `TypeParameter`s has not provided any explicit type arguments, and won't be used when instantiating individual `TypeParameter`s.

Instead, we should separate out binding and use occurrences of `TypeArguments` into two classes, `TypeParameters` and `TypeArguments`. The former will replace the use of TypeArguments to store the type parameters of classes and functionss, and it can store a vector that represents the entire vector instantiated to bounds without adding overhead to _all_ `TypeArguments` objects. We can also move any methods on `TypeArguments` that only make sense for binding positions to the new `TypeParameters` class.

**Comment by crelier** [comment]
@sstrickl Now that my CL introducing a proper `FunctionType` has [landed](https://dart-review.googlesource.com/c/sdk/+/176981), I wanted to tackle this refactoring, unless you feel strongly about doing it yourself, of course.
This would also resolve the proper canonicalization of function type literals, for which I recently committed a temporary [workaround](https://dart-review.googlesource.com/c/sdk/+/179060).

**Comment by sstrickl** [comment]
No worries, I have other things to focus on at the moment, go for it! :)

(Yaaaaaaay, separating binding and use!)

**Comment by crelier** [comment]
Great! Thanks. I am on it.
