### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by sujayarvind28** [dart-lang/sdk#43915]
## Version information

- `IDEA AI-201.8743.12.41.6858069`
- `2.10.1`
- `AI-201.8743.12.41.6858069, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

**Comment by vsmenon** [comment]
Closing due to lack of info.  Please re-open with error details.
