### ISSUE TITLE
Auto completion difference between a function and variable as a function

### ISSUE THREAD

**Issue by Manuelbaun** [dart-lang/sdk#43919]
Hello, 

I encountered a different behavior of the auto-completion when I use a regular `function` vs a `variable` as a `function`.

```dart
int Function({int a}) create = ({int a}) => a + 10;

int create2({int a}) => a + 1;

void main() {
  create2(a: 20);

  create(/** no auto completion */);
}
```

When I use the `create2` function, IntelliSense shows me the option to pass the named parameter `a` to the function. That is not the case when I try to call `create`. It does not show me any suggestions.
This was discussed in the dart-lang/sdk channel on gitter:  [Gitter-Link](https://gitter.im/dart-lang/sdk?at=5f95811e7be0d67d279702ca)

Is that supposed to behave like that? My Motivation is, I want to forward function calls, to other classes. But if the auto-suggestion doesn't work "correctly" it decreases the developer experience.

![image](https://user-images.githubusercontent.com/8715085/97109553-27b54100-16d4-11eb-82f7-a8fffe864c33.png)

**Comment by bwilkerson** [comment]
No, that isn't intentional, it's an oversight. Thanks for bring it to our attention.

**Comment by nigel-gott** [comment]
Related to this I tried to get around this lack of autocomplete by instead using callable classes, which helps somewhat if you are OK with users having to type '.call' to get autocompletion for your api:

```dart
class CallableCreate{
  int call(int a){
    return a + 10;
  }
}
CallableCreate create = CallableCreate();

int create2({required int a}) => a + 1;

// Using .call makes nice autocompletion
var x = create.call(10);

// There is no help at all however when I directly call the class :(
var y = create(10);
```

However if you do not start typing .call on the callable class but instead start to directly call it, you get no autocompletion help. If this is also an oversight I am happy to open a new issue for it if you would like? Or perhaps it fits nicely into this issue already.

**Comment by bwilkerson** [comment]
That is also a bug, but slightly different because instances of implicit subclasses of `Function` look slightly different to the analyzer than function-valued variables. I created https://github.com/dart-lang/sdk/issues/45595 to capture it.

**Comment by asashour** [comment]
I am unable to reproduce with

```dart
void Function({int? a}) create = ({int? a}) {};

void main() {

  create(|);
}
```

with
`Dart SDK version: 2.18.0-43.0.dev (dev) (Thu Apr 21 10:35:29 2022 -0700) on "windows_x64"`

**Comment by scheglov** [comment]
I'm surprised that this still does not work.
We have a few CLs that get formal parameters for various targets.
I did one a few days ago da488fdb78958990c19d708c9e6c6fe2cfe3d9fd.
Apparently, something more to fix :-)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/357221
