### ISSUE TITLE
`invalid_use_of_visible_for_testing_member` for `integration_test/` directory

### ISSUE THREAD

**Issue by jiahaog** [dart-lang/sdk#43921]
In `package:integration_test`, we [recommend](https://pub.dev/packages/integration_test#usage) Flutter users place their test files in the `integration_test/` subdirectory of their package, to avoid confusion with tests executed by `package:flutter_test` in the `test/` directory. 

However, the `invalid_use_of_visible_for_testing_member` analyzer rule does not allow symbols marked with `@visibleForTesting` from being accessed in this directory – the analyzer only treats `test/`, `test_driver/` and `testing/` directories as test directories (see below). Would it be reasonable to add `integration_test/` to the list as well? Happy to submit a patch if so. Thanks!

https://github.com/dart-lang/sdk/blob/235453a9c9b3c59ba269e317e9a5c94ea10b5166/pkg/analyzer/lib/src/error/best_practices_verifier.dart#L1827-L1829

**Comment by bwilkerson** [comment]
Given that we recommend this practice to users, yes, it would be reasonable to support it cleanly.

**Comment by jiahaog** [comment]
Sent https://dart-review.googlesource.com/c/sdk/+/169180, please take a look 🙂
