### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Akhileshpraza** [dart-lang/sdk#43936]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.8.4`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

**Comment by vsmenon** [comment]
Hi, please file information with the bug.  We cannot see if anything is wrong from the above.
