### ISSUE TITLE
Null safety feedback: [issue summary]

### ISSUE THREAD

**Issue by ngxingyu** [dart-lang/sdk#43934]
The initializer type 'Color?' can't be assigned to the field type 'Color'.

**Comment by vsmenon** [comment]
This is by design. 

You have a few ways to check for null to allow the assignment:

```dart
Color? c1 = ...;
Color c2 = c1!; // Throws if c1 is null.
```

or

```dart
Color? c1 = ...;
if (c1 != null) {
  Color c2 = c1;
} 
```

**Comment by ngxingyu** [comment]
Alright thank you!
