### ISSUE TITLE
[app_jitk] app_jitk try bot failures with null safety flag flip

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43947]
I'm seeing failures on the app_jitk bots as follows on some standalone_2/io tests:  

From [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865236512862064928/+/steps/test_results/0/logs/new_test_failures__logs_/0)

From [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865271264922456528/+/steps/test_results/0/logs/new_test_failures__logs_/0)

@lrhn @mkustermann any chance you can look at these on Wednesday your time?

**Comment by mkustermann** [comment]
Made [cl/169321](https://dart-review.googlesource.com/c/sdk/+/169321) which should address the 3 test failures. One of those tests is flakily triggering a crash, which is addressed by [cl/166790](https://dart-review.googlesource.com/166790)

The flaky crash of `lib_2/isolate/message3_test/fun/0` can be ignored / approved.
