### ISSUE TITLE
How can I get run_binary_size_analysis.dart after flutter1.22.2

### ISSUE THREAD

**Issue by kangwang1988** [dart-lang/sdk#43946]
```shell
kylewong@KyleWongs-Work-MBP src % /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/flutter doctor -v
[✓] Flutter (Channel unknown, 1.24.0-4.0.pre.106, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-CN)
    • Flutter version 1.24.0-4.0.pre.106 at
      /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision fb508db94d (3 hours ago), 2020-10-27 17:16:24 -0700
    • Engine revision 64e6599910
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror http://flutter-storage.alibaba-inc.com/taobao
```

Previously,run_binary_size_analysis.dart is available at:
![image](https://user-images.githubusercontent.com/817851/97386934-eb6e2480-190f-11eb-88cc-f32d30fc6aee.png)

However, now it's missing and the alternative one seems deleted also.

@mraleph

**Comment by mraleph** [comment]
The code has moved into its own package: https://github.com/dart-lang/sdk/blob/master/pkg/vm_snapshot_analysis and is published on pub as well. 

Furthermore it is deeply integrated with Flutter tooling through Dev Tools: https://flutter.dev/docs/development/tools/devtools/app-size
