### ISSUE TITLE
Failures on Reland "[ Service / dart:isolate ] Added getPorts RPC and 'debugName' optional"

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#43952]
There are new test failures on [Reland "[ Service / dart:isolate ] Added getPorts RPC and 'debugName' optional"](https://github.com/dart-lang/sdk/commit/a5d451184769833bd0c6c4b5d74ca96c1649fb63). (Was in a larger group, but consistent reproduction let me bisect it to this change).

The tests
```
standalone_2/io/unix_socket_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-reload-linux-debug-x64
dartk-reload-linux-release-x64
```

/cc @bkonyi

**Comment by sstrickl** [comment]
Actually, just going to revert since this failure (in reload mode, not reload-rollback mode) is directly related to the content of the CL, not just incidental.

**Comment by sstrickl** [comment]
[Example logs](https://dart-ci.appspot.com/log/vm-kernel-reload-linux-debug-x64/dartk-reload-linux-debug-x64/8917/standalone_2/io/unix_socket_test), since I forgot those in the original comment. Have sent revert to CL, so closing.

**Comment by bkonyi** [comment]
I don't think those tests failing are directly related to this CL, but I'll take a look.
