### ISSUE TITLE
migration tool recommends `return null!` for async function

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#43960]
I've converted the `StageXL` library to non-nullable. I've run into a runtime error that occurs that is puzzling.  
It occurs when the overridden `cancel()` method runs.  

The nnbd migration tool added a `return null!` to that method, but I'm unclear why: https://github.com/mnordine/StageXL/blob/non-nullable/lib/src/events/event_stream_subscription.dart#L73

Removing that line results in a static error: `error: The body might complete normally, causing 'null' to be returned, but the return type is a potentially non-nullable type. (body_might_complete_normally at [stagexl] lib\src\events\event_stream_subscription.dart:67)`

This is very puzzling because the return type of that method is `Future<void>`.

Steps to reproduce:
- Create project from https://gist.github.com/mnordine/7deaaa9dff8bc56d568c600ed8b61b35
- `pub get`
- `pub run build_runner serve web:8090 --enable-experiment=non-nullable`
- Open http://localhost:8090
- Click red button

Notice the runtime error that occurs:

```
errors.dart:167 Uncaught Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:213)
    at Object.nullCheck (operations.dart:518)
    at EventStreamSubscription.__.cancel (event_stream_subscription.dart:73)
    at Object._cancelAndValue (stream_pipe.dart:57)
    at stream.dart:1302
    at EventStream.__.[_dispatchEventInternal] (event_stream.dart:208)
    at display.Sprite.new.dispatchEventRaw (event_dispatcher.dart:143)
    at display.Sprite.new.dispatchEvent (display_object.dart:957)
    at display.Stage.new.[_onMouseEvent] (stage.dart:800)
    at Object._checkAndCall (operations.dart:324)
    at Object.dcall (operations.dart:329)
    at HTMLCanvasElement.<anonymous> (html_dart2js.dart:37283)
DartError @ errors.dart:167
throw_ @ errors.dart:213
nullCheck @ operations.dart:518
cancel @ event_stream_subscription.dart:73
_cancelAndValue @ stream_pipe.dart:57
(anonymous) @ stream.dart:1302
[_dispatchEventInternal] @ event_stream.dart:208
dispatchEventRaw @ event_dispatcher.dart:143
dispatchEvent @ display_object.dart:957
[_onMouseEvent] @ stage.dart:800
_checkAndCall @ operations.dart:324
dcall @ operations.dart:329
(anonymous) @ html_dart2js.dart:37283
```

**Comment by kevmoo** [comment]
@mnordine – this seems like a bug in the migration tool.

No return should be required.

Which version of dart are you using?

**Comment by mnordine** [comment]
Sorry, I should have mentioned, I compiled the sdk locally on my Windows machine:

`Dart SDK version: 2.11.0-edge.3b58a4adcd1085296463625c291cf5f019796ba7 (be) (Mon Oct 26 19:03:16 2020 +0000)
 on "windows_x64"`

**Comment by mnordine** [comment]
I'll try the latest dev channel release

**Comment by mnordine** [comment]
Same result with with latest dev release: `Dart SDK version: 2.11.0-240.0.dev (dev) (Tue Oct 20 16:27:23 2020 -0700) on "windows_x64"`

**Comment by kevmoo** [comment]
What happens if you delete the `return null!` ?

**Comment by mnordine** [comment]
> Removing that line results in a static error: error: The body might complete normally, causing 'null' to be returned, but the return type is a potentially non-nullable type. (body_might_complete_normally at [stagexl] lib\src\events\event_stream_subscription.dart:67)

**Comment by kevmoo** [comment]
Does compilation work?

**Comment by kevmoo** [comment]
Have you tried adding `async` to the function?

**Comment by mnordine** [comment]
I just did, and it works. Completely missed that, sorry about that.

**Comment by mnordine** [comment]
I closed this, but I wonder if the migration tool could've handled this better?

**Comment by kevmoo** [comment]
This is a good bug for the migration tool. Re-opening!

**Comment by devoncarew** [comment]
possibly related to https://github.com/dart-lang/sdk/issues/43972

**Comment by stereotype441** [comment]
I'm re-closing this since #43972 has been fixed, and I think that addresses the desire for the migration tool to handle this better.
