### ISSUE TITLE
Enable native null assertions by default in build_web_compilers

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#43961]
This bug tracks work to enable `native_null_assertions` by default and provide a way for users to disable if they come across these assertions. Note that DDC points to this file (which doesn't exist) currently:

`https://github.com/dart-lang/build/tree/master/docs/native_null_assertions.md`

This doc needs to be populated with the aforementioned instructions (likely will just point at the configuration instructions of build_web_compilers).

cc @jakemac53

**Comment by mnordine** [comment]
I see there are instructions to enable/disable `native_null_assertions`, but I don't know *what they are*, why I'd want them, an example of what they look like, impact on code, etc...

**Comment by jakemac53** [comment]
@mnordine The end goal here is they are enabled by default, that is what most people expect. If one of these assertions is tripped, the compiler links to a doc in the SDK which describes fully what they are, and links to our doc on how to disable them.

**Comment by mnordine** [comment]
> a doc in the SDK which describes fully what they are

Does that doc exist now?

Will they be enabled for all types of builds in both ddc and dart2js?

**Comment by jakemac53** [comment]
@srujzs can link the doc, I don't know exactly where it is. He can also confirm the intention regarding all the compilers and optimization levels.

**Comment by srujzs** [comment]
It doesn't answer all your questions, but the doc exists here currently: https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/doc/NATIVE_NULL_ASSERTIONS.md

Optimization levels is an interesting question, and we discussed it briefly but put this feature under any other flag/optimization level. Currently, if we enable it by default, it will be available for all optimization levels in sound null-safety. This made sense since it's testing soundness. Is there a preference to do it one way or the other?

**Comment by jakemac53** [comment]
My main concern with changing the default in different optimization modes is that `build_web_compilers` does not know the current optimization mode today, so it wouldn't be able to easily set the mode based on that.

We would need to go back to the compilers setting the defaults, which is fine but I would then need the ability to negate the option in dart2js.

**Comment by srujzs** [comment]
Right, I assumed the ask was to limit the feature such that it would only trigger those assertions if the feature was enabled by default by build_web_compilers _and_ if there was a certain optimization level set. I wouldn't want dart2js to set it to true by default.

**Comment by srujzs** [comment]
@jakemac53 is there any work left here to enable this by default?

**Comment by jakemac53** [comment]
Does dart2js accept `--no-native-null-assertions` now? If so its just a matter of us flipping the switch.

**Comment by srujzs** [comment]
Yep, the associated flag is here: https://github.com/dart-lang/sdk/blob/8cba879f46cb6626f10c1b570f0cf826e7ffd7a6/pkg/compiler/lib/src/commandline_options.dart#L80.

**Comment by jakemac53** [comment]
Ok I can go ahead and swap this over then

**Comment by jakemac53** [comment]
@srujzs just to confirm should we always enable this? Or only for debug mode?

**Comment by srujzs** [comment]
Thanks! Yeah, I think we'd want this to always be enabled. Is there an argument as to why it should not be/only be in debug mode? I'm not familiar with the build_web_compilers workflow.

**Comment by jakemac53** [comment]
We don't have opinions really on this, but we do have the two modes. Right now release mode basically just passes --minify and doesn't produce source maps.

**Comment by srujzs** [comment]
Ah, I see. I'm okay with always enabling this, then.

**Comment by mnordine** [comment]
> Is there an argument as to why it should not be/only be in debug mode?

Does this impact performance?

**Comment by jakemac53** [comment]
> Does this impact performance?

You will always have the ability to disable it - note that we don't enable other performance optimizations that come at the cost of correctness by default either.

**Comment by mnordine** [comment]
As long as it's documented in `dart2js -vh`, or `dart compile js -vh`, sounds good to me.

(`dart compile js -vh` still doesn't work like `dart2js -vh` btw, it doesn't print any extra help)
