### ISSUE TITLE
Change migration tool to produce `null /*no valid migration*/` instead of `null!`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#43972]
Rationale: `null!` fails at runtime but is statically ok; leaving a literal `null` produces a static error, which is more noticable.  We have reason to suspect that people usually run into `null!` because they're trying to manually override the behavior of the tool, e.g.:

Implementation file:
```dart
// User added `/*!*/` to stop the tool from making `x` nullable
foo(int/*!*/ x) { ... }
```

Test file:
```dart
  foo(null);
```

In this case producing a result with a static error seems preferable, since it alerts the user immediately that they have to change their test.

I'm going to try to make this change before the beta release is cut so that we can get some good user feedback about it.

**Comment by mit-mit** [comment]
Agreed, this would be a great change

**Comment by stereotype441** [comment]
Fix out for review: https://dart-review.googlesource.com/c/sdk/+/169600
