### ISSUE TITLE
[dev_compiler] Support enabling asserts for expression evaluation

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#43986]
Ddc relies on source information during compilation for creating assert statements. This information is not available if the kernel is loaded from dill, as in expression compilation  provided by the expression compilation worker.

Suggestion: store needed source text for asserts in kernel instead.
Alternative suggestion: source information (such as file and offsets)  and invoke some post-failure step to add source text to the failure message.

See:

https://github.com/dart-lang/sdk/blob/2259593f836cf975f8d9aa86b3134f0c8748acd7/pkg/dev_compiler/lib/src/kernel/compiler.dart#L3617

**Comment by devoncarew** [comment]
@annagrin - when creating an issue on the sdk repo - if you know the area for it (like `area-web` for this item) - can you add the area label? It'll reduce the work for the issue triagers; thanks!

**Comment by nshahan** [comment]
One reason that compiling an assertion requires the source is that flutter requested when assertions fail the error message includes the source code that failed. The VM does this, but I don't know if the VM does this for assertions written in debugger expressions. We could double check if they do and if so how do they get the source code?

I think another possibility here would be to just not include that information in the error message if there isn't a valid source location available. We could have a separate path when compiling assertions in the expression compiler that is more forgiving and not expect source location to be available. I think it would be understandable if you were to write a failing assertion expression in the debugger and you didn't get back source information when it failed. A message that just says something like "Assertion failed. Error from compiled expression."

**Comment by annagrin** [comment]
Update: I am changing the DDC compiler code to be resilient to this failure - ie have some reporting with missing information. This allows us to enable asserts in the expression compiler and add tests in the SDK that match the CI bot configurations.

Note that VM does something similar:
```
Unhandled exception:
'': Failed assertion: line -1: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      Eval.<anonymous closure> ()
#3      Eval ()
```

**Comment by annagrin** [comment]
Closed in https://dart-review.googlesource.com/c/sdk/+/317448
