### ISSUE TITLE
num toStringFixed does not produce required output

### ISSUE THREAD

**Issue by MohiuddinM** [dart-lang/sdk#43983]
The following code instead of printing `2.12` prints `2.124671744860683e+38`:
```
void main() {
  final x = 2.124671744860683e+38;
  
  print(x.toStringAsFixed(2));
}
```

This tracker is for issues related to:
* Dart core libraries ("dart:async", "dart:io", etc.)

* Dart SDK Version (`dart --version`)
Dart version 2.10.2

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Mac OS X 10.15.7 19H2

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

**Comment by devoncarew** [comment]
I believe this is correct as `xxxe+38` is just a very large number w/o any decimal positions.

If you run:

```
void main() {
  final x = 2.124671744860683;
  
  print(x.toStringAsFixed(2));
}
```

You'll see the behavior you're expecting - `2.12`.
