### ISSUE TITLE
Migration tool fails when experiment is enabled

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#43992]
When I was migrating a package, I enabled the experiment in my `analysis_options.yaml`:

```
analyzer:
  enable-experiment:
    - non-nullable
```

Then I ran `dart migrate`, which failed because there were now analyzer warnings.

Instead, is it possible to disable the experiment before `dart migrate` runs the analysis on the project?

**Comment by devoncarew** [comment]
We should likely minimally warn the user that they should comment out the opt-in for best results.

However, we likely want our primary use case to be:
- people running on a 2.12 SDK (with the flag flipped, and no analyzer opt-in necessary), on a project w/ pre-2.12 pubspec sdk constraints, and
- people running on a 2.12 SDK (with the flag flipped, and no analyzer opt-in necessary), on a project w/ 2.12 or greater pubspec sdk constraints

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
