### ISSUE TITLE
reading file bytes is 5x slower compared to java

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#44006]
Reading bytes of a 150M file with the following code is 5x slower in dart compared to java

Dart reads the file in 150ms:

```dart
final sw = Stopwatch()..start();
final file = File(path);
final fileStream = file.openRead();
await for (var bytes in fileStream) { }
print('time: ${sw.elapsed}');
```

Java reads the file in 30ms:

```java
var start = System.currentTimeMillis();
var input = new FileInputStream(path);
var buffer = new byte[65536];
while (input.read(buffer) != -1) {}
input.close();
System.out.println("time:" + (System.currentTimeMillis() - start));
```

```
$ dart --version
Dart SDK version: 2.10.2 (stable) (Tue Oct 13 15:50:27 2020 +0200) on "linux_x64"
$ java --version
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.18.04.1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.18.04.1, mixed mode, sharing)
```

**Comment by devoncarew** [comment]
Thanks for the report!

It might be interesting to do a few more benchmarks to know where the slowdown is. Do some of the sync read methods show the same performance difference for instance?

**Comment by a14n** [comment]
Sync read is worse. It reads the file in 250ms.

```dart
final sw = Stopwatch()..start();
final file = File(path);
final bytes = file.readAsBytesSync();
print('done : ${sw.elapsed}');
```

**Comment by lrhn** [comment]
The comparison is a little unfair. The Java code reads blocks of 64k at a time, while the Dart code reads one byte at a time. If nothing else, the *loop* code is executed 64k times more often in the Dart version.

**Comment by devoncarew** [comment]
Note that the 'fileStream' result above is a `Stream<List<int>>`, so I assume is reading through the data in chunks of some (greater than 1 byte) size.

**Comment by lrhn** [comment]
Good point. Also, I tried reading in chunks of 64K, using `File.open`/`RandomAccessFile.read` instead of `openRead`/stream listen, and it still takes 88ms for sync-reading and 130-170ms for async reading 150Mb (on my personal machine, don't have Java to compare to).

**Comment by a14n** [comment]
I used `new byte[65536]` in my java test because the `bytes.length` in Dart was 65536.

**Comment by a14n** [comment]
Should this issue be labelled with _area-vm_ ? /cc @mraleph

**Comment by mraleph** [comment]
I would not be surprised if most of the performance difference between sync reading in Dart and sync reading in Java comes from the fact that we read into temporary buffer and then perform the copy in pure Dart.

**Comment by brianquinlan** [comment]
async calls in `dart:io` are slower than synchronous ones because:
1. they require copying memory
2. they send the results over a port

This might be obvious but the overhead of using asynchronous calls goes down the few calls we make e.g.

Java:

```java
import java.nio.file.Files;
import java.nio.file.*;
import java.io.IOException;

public class read  {

    public static void main(String[] args) throws IOException {
        byte[] content = null;
        var start = System.currentTimeMillis();
        for (int i = 0; i < 1000; ++i) {
            content = Files.readAllBytes(Paths.get("/tmp/150MB.txt"));
        }
        System.out.println("time:" + (System.currentTimeMillis() - start));
        System.out.println(content.length);
    }
}
```
time:24502
157286400

```dart
import 'dart:io';
import 'dart:typed_data';

void main() async {
  Uint8List? bytes;
  final start = DateTime.now();
  for (var i = 0; i < 1000; ++i) {
    bytes = await File("/tmp/150MB.txt").readAsBytes();
  }
  print("time:${DateTime.now().difference(start).inMilliseconds}");
  print(bytes!.length);
}
```
time:29169 (19% slower than Java)
157286400

And the synchronous Dart version is only slightly slower than the Java version:

```dart
import 'dart:io';
import 'dart:typed_data';

void main() {
  Uint8List? bytes;
  final start = DateTime.now();
  for (var i = 0; i < 1000; ++i) {
    bytes = File("/tmp/150MB.txt").readAsBytesSync();
  }
  print("time:${DateTime.now().difference(start).inMilliseconds}");
  print(bytes!.length);
}
```
time:25410 (3.7% slower than Java)
157286400

I think that the most equivalent comparison (both synchronously reading into a reused buffer) would be:

```java
import java.io.FileInputStream;
import java.io.IOException;

public class read  {

    public static void main(String[] args) throws IOException {
        var start = System.currentTimeMillis();
        for (int i = 0; i < 1000; ++i) {
            var input = new FileInputStream("/tmp/150MB.txt");
            var buffer = new byte[65536];
            while (input.read(buffer) > 0) {}
            input.close();
        }
        System.out.println("time:" + (System.currentTimeMillis() - start));
    }
}
```
time:18246

```dart
import 'dart:io';
import 'dart:typed_data';

void main() async {
  final start = DateTime.now();
  for (var i = 0; i < 1000; ++i) {
    final input = await File("/tmp/150MB.txt").open();
    final buffer = Uint8List(65536);
    while (input.readIntoSync(buffer) > 0);
    input.closeSync();
  }
  print("time:${DateTime.now().difference(start).inMilliseconds}");
}
```
time:13363 (Dart @ HEAD - *Java* 36% slower)
time:37817 (Dart 2.19.1 - *Dart* 107% slower)

The async version is still slow:

```
--     while (input.readIntoSync(buffer) > 0);
++    while (await input.readInto(buffer) > 0);
```
time:56255 (Dart @ HEAD - 208% slower)

**Comment by brianquinlan** [comment]
So, using equivalent **sync** constructs, Dart's file I/O performance seems about the same as Java's.

I don't think that there is much that we can do to improve async performance without massive changes.

Do we think that this issue can be closed or is there something that we can do?
