### ISSUE TITLE
Analyzer reports on @deprecated field formal parameter at its declaration

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#44004]
See:

```dart
class C {
  String s;
  C({@deprecated this.s});
}
```

Analyzer reports:

> hint • 's' is deprecated and shouldn't be used. • a.dart:4:24 • deprecated_member_use_from_same_package

o_O

**Comment by scheglov** [comment]
I have some tweaks for it :-)
https://dart-review.googlesource.com/c/sdk/+/169921
