### ISSUE TITLE
[FFI] Work with a pointer to a string

### ISSUE THREAD

**Issue by listepo** [dart-lang/sdk#44017]
I am facing a problem when working with strings. For example: 
https://github.com/postgres/postgres/blob/8a15e735be00f156a7227741c0ce88702e6de099/src/interfaces/libpq/fe-connect.c#L6535
```
char *
PQpass(const PGconn *conn)
{
	char	   *password = NULL;

	if (!conn)
		return NULL;
	if (conn->connhost != NULL)
		password = conn->connhost[conn->whichhost].password;
	if (password == NULL)
		password = conn->pgpass;
	/* Historically we've returned "" not NULL for no password specified */
	if (password == NULL)
		password = "";
	return password;
}
```
when I use https://github.com/dart-lang/ffigen/issues/72#issuecomment-673328056
I get an error 
```
art(11490,0x7000070ec000) malloc: *** error for object 0x10fcb0efc: pointer being freed was not allocated
dart(11490,0x7000070ec000) malloc: *** set a breakpoint in malloc_error_break to debug
```
I guess the error occurs when the function returns an empty string(`password = "";`) and I try to free memory.(for strings without `malloc`)
How can I understand when I need to free up memory, and when not?(`password = conn->pgpass;` with `malloc`)

_Originally posted by @listepo in https://github.com/dart-lang/sdk/issues/34452#issuecomment-720339303_

@dcharkes can you help me? thanks in advance

**Comment by dcharkes** [comment]
If you'd remove 

```c++
	if (password == NULL)
		password = "";
```

then you could just check in dart if the pointer equals `nullptr` and only free if it does not.

Note that is perfectly possible to free `""` if it is actually allocated in the program. `""` will still be 1 byte long, and contain the termination byte as first byte, which still needs to be freed when allocated. However, in your code the `""` will be a constant which is part of your compiled program and cannot be freed at runtime.

**Comment by dcharkes** [comment]
I completely missed that this is the Postgres API (thanks @mraleph for pointing that out)!

When using an existing library, the existing library has a policy about its resource management. The postgres documentation on the function does not mention resource management at all: https://www.postgresql.org/docs/12/libpq-status.html. However, given that the implementation directly returns `conn->connhost[conn->whichhost].password` without any copying, freeing that value would likely lead to undefined behavior as well. So I'd infer from this that the callee never has to free a string returned from this function.

**Comment by listepo** [comment]
@dcharkes thanks a lot
