### ISSUE TITLE
fetch dart fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [dart-lang/sdk#44018]
$ fetch dart
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "name": "sdk",
    "url": "https://dart.googlesource.com/sdk.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Running: gclient sync

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://dart.googlesource.com/sdk.git /data/jw/dart-sdk/_gclient_sdk_s2nsqn9_' in '/data/jw/dart-sdk'
Cloning into '/data/jw/dart-sdk/_gclient_sdk_s2nsqn9_'...
remote: Sending approximately 1.07 GiB ...
remote: Counting objects: 1587, done
remote: Finding sources: 100% (13/13)
remote: Total 1062694 (delta 811062), reused 1062690 (delta 811062)
Receiving objects: 100% (1062694/1062694), 1.06 GiB | 5.15 MiB/s, done.
Resolving deltas: 100% (811062/811062), done.
Syncing projects:  98% (100/102) sdk/third_party/mdn/browser-compat-data/src
[0:07:27] Still working on:
[0:07:27]   sdk/third_party/icu
[0:07:27]   sdk/third_party/boringssl/src

[0:07:37] Still working on:
[0:07:37]   sdk/third_party/icu
[0:07:37]   sdk/third_party/boringssl/src

[0:07:47] Still working on:
[0:07:47]   sdk/third_party/icu
[0:07:47]   sdk/third_party/boringssl/src

[0:07:54] Still working on:
[0:07:54]   sdk/third_party/icu
[0:07:54]   sdk/third_party/boringssl/src
Syncing projects:  99% (101/102) sdk/third_party/boringssl/src
[0:08:54] Still working on:
[0:08:54]   sdk/third_party/icu

[0:09:04] Still working on:
[0:09:04]   sdk/third_party/icu

[0:09:08] Still working on:
[0:09:08]   sdk/third_party/icu
Syncing projects: 100% (102/102), done.

________ running 'cipd ensure -log-level error -root /data/jw/dart-sdk -ensure-file /tmp/tmp7enszi9y.ensure' in '.'
Errors:
  failed to resolve gn/gn/linux-arm64@git_revision:1e3fd10c5df6b704fc764ee388149e4f32862823 (line 10): no such tag
  failed to resolve flutter/android/ndk/linux-arm64@version:r21.0.6113669 (line 25): no such package: flutter/android/ndk/linux-arm64
  failed to resolve flutter/android/sdk/build-tools/linux-arm64@version:30.0.1 (line 28): no such package: flutter/android/sdk/build-tools/linux-arm64
  failed to resolve flutter/android/sdk/platform-tools/linux-arm64@version:29.0.2 (line 31): no such package: flutter/android/sdk/platform-tools/linux-arm64
  failed to resolve flutter/android/sdk/tools/linux-arm64@version:26.1.1 (line 37): no such package: flutter/android/sdk/tools/linux-arm64
Error: Command 'cipd ensure -log-level error -root /data/jw/dart-sdk -ensure-file /tmp/tmp7enszi9y.ensure' returned non-zero exit status 1
Subprocess failed with return code 1.

Thanks.

**Comment by devoncarew** [comment]
Thanks for the report. I don't think this is actionable for us though - this might be a network issues, or something to do with how the underlying packages are tagged. Closing but we can re-open if its more widespread or something that we should address on our end.

**Comment by LutzWeischerFujitsu** [comment]
I retried right now and get this: 

(.env) [jw@cn06 dart-sdk]$ fetch dart
Running: gclient root
OK to update it to https://chromium.googlesource.com/chromium/tools/depot_tools.git ? [Y/n] n
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "name": "sdk",
    "url": "https://dart.googlesource.com/sdk.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Your copy of depot_tools is configured to fetch from an obsolete URL:

  https://chromium.googlesource.com/chromium/tools/depot_tools

OK to update it to https://chromium.googlesource.com/chromium/tools/depot_tools.git ? [Y/n]
Remote URL updated.
Running: gclient sync

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://dart.googlesource.com/sdk.git /data/jw/dart-sdk/_gclient_sdk_heh0yptg' in '/data/jw/dart-sdk'
Cloning into '/data/jw/dart-sdk/_gclient_sdk_heh0yptg'...
remote: Counting objects: 1971, doneiB ...Counting objects: 1
remote: Total 1106049 (delta 836948), reused 1106049 (delta 836948)
Receiving objects: 100% (1106049/1106049), 1.13 GiB | 5.33 MiB/s, done.
Resolving deltas: 100% (836948/836948), done.
Syncing projects:  98% (103/105) sdk/third_party/boringssl
[0:06:11] Still working on:
[0:06:11]   sdk/third_party/icu
[0:06:11]   sdk/third_party/boringssl/src

[0:06:21] Still working on:
[0:06:21]   sdk/third_party/icu
[0:06:21]   sdk/third_party/boringssl/src

[0:06:31] Still working on:
[0:06:31]   sdk/third_party/icu
[0:06:31]   sdk/third_party/boringssl/src

[0:06:41] Still working on:
[0:06:41]   sdk/third_party/icu
[0:06:41]   sdk/third_party/boringssl/src

[0:06:50] Still working on:
[0:06:50]   sdk/third_party/icu
[0:06:50]   sdk/third_party/boringssl/src
Syncing projects: 100% (105/105), done.

________ running 'cipd ensure -log-level error -root /data/jw/dart-sdk -ensure-file /tmp/tmp480dgbdf.ensure' in '.'
Errors:
  failed to resolve gn/gn/linux-arm64@git_revision:1e3fd10c5df6b704fc764ee388149e4f32862823 (line 10): no such tag
  failed to resolve flutter/android/ndk/linux-arm64@version:r21.0.6113669 (line 25): no such package: flutter/android/ndk/linux-arm64
  failed to resolve flutter/android/sdk/build-tools/linux-arm64@version:30.0.1 (line 28): no such package: flutter/android/sdk/build-tools/linux-arm64
  failed to resolve flutter/android/sdk/platform-tools/linux-arm64@version:29.0.2 (line 31): no such package: flutter/android/sdk/platform-tools/linux-arm64
  failed to resolve flutter/android/sdk/tools/linux-arm64@version:26.1.1 (line 37): no such package: flutter/android/sdk/tools/linux-arm64
Error: Command 'cipd ensure -log-level error -root /data/jw/dart-sdk -ensure-file /tmp/tmp480dgbdf.ensure' returned non-zero exit status 1
Subprocess failed with return code 1.
(.env) [jw@cn06 dart-sdk]$
