### ISSUE TITLE
`class F implements Function(int)` crashes analyzer

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#44011]
I tried to find out how dart handles the attempt of a class to implement Function(int), and now I know :-)
It crashes the analyzer! ("The Dart analyzer has terminated"). On dartpad, the error message is "XMLHttpRequest error" (tested also on "dartpad nullsafety" - same thing).
```
class Q implements Function(int) {
   call(int x)=>0;
}
```

EDIT: some symptoms of the trouble, albeit in a less lethal form, manifest themselves in a variant where Function is replaced by some random Foo:
```
class Foo 
{ 
  Foo(int x){} // ERROR: int isn't a type
}
// stupid declaration just to find out whether parentheses are the culprit
class Q implements Foo(int) { 
   
}
```
Here, the analyzer reports 2 errors, one of which is strange: int isn't a type. (not sure the effect is related to the Function problem though)

**Comment by devoncarew** [comment]
Using:

```
class Q implements Function(int) {
   call(int x)=>0;
}
```

Here's the crash I see locally:

```
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'TypeName' of 'value'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:730:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:999:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _s…
```

That is for `2.11.0-213.0.dev`.

**Comment by srawlins** [comment]
Crash no longer occurs in 2.12 head.
