### ISSUE TITLE
[dart CLI] `dart --no-sound-null-safety test` and `dart test --no-sound-null-safety` should pass the option.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#44022]
`dart test` currently runs a subprocess with `pub run test`.

The sound-null-safety option should be passed correctly

Currently:
```
$ dart test --no-sound-null-safety
Could not find an option named "sound-null-safety".

Usage: pub run test [files or directories...]

-h, --help                            Shows this usage informat
```

**Comment by mit-mit** [comment]
A work around for this is to use:
```
$ dart --no-sound-null-safety test 
```

I have an example of this here:
https://github.com/mit-mit/null-safety-test/blob/master/README.md#running-tests

**Comment by bkonyi** [comment]
This seems to be an issue with the `pub` command parser as there's no option for `--[no-]sound-null-safety` cc/ @jonasfj

**Comment by sigurdm** [comment]
It does have that:
```
pub run --help
Run an executable from a package.

Usage: pub run <executable> [arguments...]
-h, --help                              Print this usage information.
    --[no-]enable-asserts               Enable assert statements.
    --enable-experiment=<experiment>    Runs the executable in a VM with the given experiments enabled.
                                        (Will disable snapshotting, resulting in slower startup).
    --[no-]sound-null-safety            Override the default null safety execution mode.

Run "pub help" to see global options.
See https://dart.dev/tools/pub/cmd/pub-run for detailed documentation.
```

However `dart test` no longer invokes `pub run`, so the solution has to be different.

Currently we are taking all arguments after `dart test <args>` and passing them straight to the invocation of dart <snapshot> <args>`.

We would probably have to fish out `--no-sound-null-safety` and put it in front of `<snapshot>`:

`dart --no-sound-null-safety <snapshot> <args without '--no-sound-null-safety'>`

Is it enough to invoke the test runner with `--no-sound-null-safety` to get the behavior from the test that it in turn runs?

**Comment by bkonyi** [comment]
@sigurdm ah right, I forgot that's how things are implemented now... `dart test` doesn't seem to provide any special handling for arguments at all:

```
$ dart test --help

Run tests in this package.

Usage: dart test [arguments]


Run "dart help" to see global options.
```

I'll look into updating the command to support the null safety flag and experiments.

**Comment by sigurdm** [comment]
Perhaps we should do like I suggested in: https://github.com/dart-lang/sdk/issues/44200: make a separation between the arguments to the VM and the arguments to test.

**Comment by bkonyi** [comment]
Related: https://github.com/dart-lang/sdk/issues/45436

**Comment by bkonyi** [comment]
No longer relevant now that Dart 3 has shipped.
