### ISSUE TITLE
runDartdev dereferences null in edge case w/analytics

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#44027]
Reproduction on 2.11.0-266.0.dev under Linux but I believe this to be in head as well.

From dart-lang/dartdoc#2412:

```
dart2-model_test.dart: + DARTDOC_COVERAGE_DATA=/tmp/dartdoc_coverage_dataIPQYRN /home/travis/dart-sdk/bin/dart --disable-service-auth-codes --enable-vm-service:0 --pause-isolates-on-exit --enable-asserts test/end2end/model_test.dart
dart2-model_test.dart: NoSuchMethodError: The getter 'enabled' was called on null.
dart2-model_test.dart: Receiver: null
dart2-model_test.dart: Tried calling: enabled
dart2-model_test.dart: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
dart2-model_test.dart: #1      runDartdev (package:dartdev/dartdev.dart:114:19)
dart2-model_test.dart: #2      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
dart2-model_test.dart: #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
dart2-model_test.dart: #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

The call to https://github.com/dart-lang/sdk/blob/2.11.0-266.0.dev/pkg/dartdev/lib/dartdev.dart#L49 seems to assume that createAnalyticsInstance can never return null.  However, analytics is null under this circumstance and so we crash at https://github.com/dart-lang/sdk/blob/2.11.0-266.0.dev/pkg/dartdev/lib/dartdev.dart#L114.

I think the bug is here:  https://github.com/dart-lang/sdk/blob/2.11.0-266.0.dev/pkg/dartdev/lib/src/analytics.dart#L72

If the settings directory does not exist, but can be created, we can fall out of this else block and not assign a value to `_instance`.

**Comment by jcollins-g** [comment]
Rerunning the command will work (since the directory gets created and we bypass the case).  But on a continuous build infrastructure where the directory is not precreated, the crash comes up like in dart-lang/dartdoc#2412.

**Comment by jcollins-g** [comment]
@sigurdm @bkonyi

**Comment by devoncarew** [comment]
Possibly related to https://github.com/dart-lang/linter/pull/2319#issuecomment-720610121.

@sigurdm - I'm assuming this is related to your recent work on analytics. Can you take a look? We're seeing this issue on most external CI systems using the dev channel.

**Comment by jonasfj** [comment]
https://dart-review.googlesource.com/c/sdk/+/170088

**Comment by jonasfj** [comment]
@franklinyow @pcsosinski I would love to get this in next beta / dev release, I think it breaks `dart` for anyone who doesn't have a  `$HOME/.dart/` folder, which is effectively all new users (or any environment that is constantly reset, like CI systems).

**Comment by pcsosinski** [comment]
@jonasfj to be clear this is currently affecting dev/beta but we shouldn't roll w/o it?

**Comment by jonasfj** [comment]
Yes, this is affecting the dev release of 2.12 that came out Monday...

I would advise that include the fix in the next dev and beta releases.
