### ISSUE TITLE
`dart format` should support returning non-zero return code on changes for CI uses

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44023]
The `flutter format` command supports returning a non-null exit code if there were formatting changes:

```
Usage: flutter format <one or more paths>
-h, --help                   Print this usage information.
-n, --dry-run                Show which files would be modified but make no changes.
    --set-exit-if-changed    Return exit code 1 if there are any formatting changes.

```

This is often used in CI systems to check that files are formatted. This issues tracks a similar flag in `dart format`

**Comment by mit-mit** [comment]
cc @munificent @bkonyi

**Comment by mit-mit** [comment]
Actually, from a [Github Action sample](https://github.com/dart-lang/usage/blob/master/.github/workflows/build.yaml#L23) @devoncarew just shared, looks like we already support this flag! Can we add it to documentation, please?

**Comment by julemand101** [comment]
You can see the flag by using `--help --verbose`:
```lang-none
> dartfmt --help --verbose
Idiomatically format Dart source code.

Usage:   dartfmt [options...] [files or directories...]

Example: dartfmt -w .
         Reformats every Dart file in the current directory tree.

-h, --help                             Show this usage information.
                                       (pass "--verbose" or "-v" to see all options)

Common options:
-w, --overwrite                        Overwrite input files with formatted output.
-n, --dry-run                          Show which files would be modified but make no changes.

Non-whitespace fixes (off by default):
    --fix                              Apply all style fixes.
    --fix-doc-comments                 Use triple slash for documentation comments.
    --fix-function-typedefs            Use new syntax for function type typedefs.
    --fix-named-default-separator      Use "=" as the separator before named parameter default values.
    --fix-optional-const               Remove "const" keyword inside constant context.
    --fix-optional-new                 Remove "new" keyword.
    --fix-single-cascade-statements    Remove unnecessary single cascades from expression statements.

Other options:
-l, --line-length                      Wrap lines longer than this.
                                       (defaults to "80")
-i, --indent                           Add this many spaces of leading indentation.
                                       (defaults to "0")
-m, --machine                          Produce machine-readable JSON output.
    --set-exit-if-changed              Return exit code 1 if there are any formatting changes.
    --follow-links                     Follow links to files and directories.
                                       If unset, links will be ignored.
    --version                          Show dart_style version.

Options when formatting from stdin:
    --preserve                         Track selection (given as "start:length") through formatting.
    --stdin-name                       Use this path in error messages when input is read from stdin.
                                       (defaults to "stdin")
```

**Comment by devoncarew** [comment]
Dart format supports this via `dart format --output=none --set-exit-if-changed .`.

Those options aren't in the default help output however, so are a bit hard to discover.

I like the `flutter format` alias of `--dry-run` however - that's very clear what it'll do.

**Comment by johnpryan** [comment]
I would also like to see `--set-exit-if-changed` added the usage info.

I've found the `--dry-run` flag is useful for CI tools. Maybe we should add it `dart format` too?

**Comment by munificent** [comment]
> I would also like to see `--set-exit-if-changed` added the usage info.

As @devoncarew said, you can accomplish that with `--output=none`. That's maybe a little less clear than `--dry-run` but the new CLI arguments are more composable than the ad hoc arguments that got weird if you tried strange combinations like JSON output with dry-run, etc.

> I would also like to see `--set-exit-if-changed` added the usage info.

SGTM. https://github.com/dart-lang/dart_style/pull/973

**Comment by johnpryan** [comment]
I see,  `dart format --output=none --set-exit-if-changed .` it is.

**Comment by johnpryan** [comment]
Small nitpick: `--output=none` prints `Formatted <filename>` instead of something more CI-friendly like `Needs formatting: <filename>`

```
dart format --output=none --set-exit-if-changed .
Changed lib/main.dart
Formatted 2 files (1 changed) in 0.21 seconds.
```

This could be fixed with additional 3rd party tooling, though.

**Comment by munificent** [comment]
Yeah, the output is a little confusing. By "changed", it means "this would be changed if dartfmt overwrite the file". I tried to figure out a better wording that still plays nice with all of the other combinations of `--output`, `--show`, and `--summary`, but it was the best I could come up with. :-/

**Comment by bkonyi** [comment]
@munificent should `--set-exit-if-changed` be visible as a default visible option for `dart format` now? I'm not seeing that change locally.

**Comment by munificent** [comment]
No, I haven't released and rolled that into the SDK. I didn't consider it super urgent because it's literally just moving a bit of help text from the verbose output to the normal.

I'm happy to if you'd like that. Want me to cut a release?

**Comment by mit-mit** [comment]
Yes, please. Not that long until the next release, and it'd be sad if we forgot to include it.

**Comment by munificent** [comment]
It's [in as of last week](https://dart-review.googlesource.com/c/sdk/+/173141). :) Sorry I forgot to update the bug here.
