### ISSUE TITLE
Roll dartdoc for null safety beta

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44035]
We need the [this dartdoc fix](https://github.com/dart-lang/dartdoc/pull/2411), so need a new version [published](https://pub.dev/packages/dartdoc/versions) and rolled to [DEPS](https://github.com/dart-lang/sdk/blob/master/DEPS)

**Comment by mit-mit** [comment]
Hi Janice, logged this issue just to keep track of where we are (I know you already said you were planning on doing this)

**Comment by devoncarew** [comment]
@mit-mit - you've added this to the null safety beta epic, but we don't need the dartdoc roll to the sdk to make the beta epic branch. api.pub.dev uses the published version of dartdoc, not the version from the sdk.

**Comment by mit-mit** [comment]
Oh, I see. What do we use the one in DEPS for? Just some testing?

**Comment by devoncarew** [comment]
That is to bring the latest dartdoc into the sdk - for `bin/dartdoc` in the built sdk. That version does built the api.dart.dev docs. They won't have this issue as all the libs there are null safe. Flutter uses the published dartdoc package - so can get the fix out of band of an sdk release - as does pub.dart.dev.

We'll still want to roll this into the sdk but getting it in by a branch is not a blocker.

**Comment by jcollins-g** [comment]
The one in DEPS is used to build the SDK docs themselves.  (It also ships with the SDK for historical reasons but all important users don't use that version).  dart-lang/dartdoc#2403 doesn't apply to the SDK so even if I don't get this roll in you should be good.

**Comment by mit-mit** [comment]
Got it, thanks for explaining. I'll close this issue then!
