### ISSUE TITLE
Consider forcing nullability to match between redirecting factory constructors and their targets

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44032]
(Based on a problem reported by @mehmetf and Emmanuel Pellereau)

Consider the following code:
```dart
class A {
  factory A(int x) = B;
}
class B implements A {
  B(int x);
}
f() {
  B(null);
}
```
As currently implemented, flow analysis will make the constructor argument of `B` nullable (because it sees an example of code passing in `null`), but it won't make the constructor argument of `A` nullable (because strictly speaking it's not necessary).  But this seems unlikely to be what the user intended.  It would probably be better for the migration tool to try to constrain the parameters of redirecting factory constructors to match the nullabilities of their targets unless specifically overridden by hints.

**Comment by srawlins** [comment]
> It would probably be better for the migration tool to try to constrain the parameters of redirecting factory constructors to match the nullabilities of their targets unless specifically overridden by hints.

Is the "target" of a redirecting factory constructor the redirectee? Is that not what the tool is doing today?

**Comment by stereotype441** [comment]
> > It would probably be better for the migration tool to try to constrain the parameters of redirecting factory constructors to match the nullabilities of their targets unless specifically overridden by hints.
> 
> Is the "target" of a redirecting factory constructor the redirectee? Is that not what the tool is doing today?

Yeah, "redirectee" is what I meant.  It's not precisely what it's doing today because today the tool is only doing what's required for soundness, which is a one-way relationship (if the redirector's parameter is nullable, then the redirectee's parameter needs to be nullable).  This issue is proposing that we have a two way relationship, so if the redirectee's parameter is nullable, then we go ahead and make the redirector's parameter nullable, even though it's not strictly speaking necessary for soundness, because it's very likely to be what the user wants

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
