### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Insider-MY** [dart-lang/sdk#44036]
## Version information

- `IDEA AI-193.6911.18.40.6514223`
- `2.12.0-3.0.dev`
- `AI-193.6911.18.40.6514223, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720, 1920x1080`

**Comment by devoncarew** [comment]
@Insider-MY - if there was a crash or exception associated with this report, can you attach that to this issue? Thanks!
