### ISSUE TITLE
Find usages now hangin in latest Dart plugin for IntelliJ

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#44044]
Just upgraded to plugin 201.9245

Find usages in a Dart project just...doesn't work any more

Currently using Dart 2.12.0-0.0.dev on Mac

**Comment by jwren** [comment]
I tried it with a few IJ versions and SDK versions, but couldn't reproduce, I got results from `Find Usages` on each attempt.  Perhaps this is a problem with this particular SDK version? `2.12.0-0.0.dev`

Dart SDKs
`2.8.0`
`2.11.0-edge....1003db`
`2.12.0-edge...SHA`

IntelliJ:
```
IntelliJ IDEA 2020.1.4 (Ultimate Edition)
Build #IU-201.8743.12, built on July 21, 2020

Runtime version: 11.0.7+10-b765.65 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 5053M
Cores: 8
Non-Bundled Plugins: Dart

Dart plugin version `201.9245`
```

**Comment by kevmoo** [comment]
Let me be more clear about the case I'm hitting.

I'm using CMD-B for find usings on a field – like `job` below. Still reproducing w/ the latest dev release

```dart
class CIJobEntry {
  final CIJob job;
  final List<String> commands;

  CIJobEntry(this.job, this.commands);

  String jobName(List<String> packages) {
    final pkgLabel = packages.length == 1 ? 'PKG' : 'PKGS';

    return 'SDK: ${job.sdk}; $pkgLabel: ${packages.join(', ')}; '
        'TASKS: ${job.name}';
  }
}
```

**Comment by kevmoo** [comment]
Hrm...now I'm not hitting it.

Will reopen if/when I get a repro
