### ISSUE TITLE
Migration tool not using `late`, suggesting changes that don't compile

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#44048]
Run the migration tool on the following code:

```dart
// @dart=2.9

import 'package:flutter/material.dart';

class Foo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => FooState();
}

class FooState extends State<Foo> {
  TextEditingController _controller;

  void init() {
    _controller = TextEditingController(text: 'foo');
  }

  @override
  Widget build(BuildContext context) {
    return TextField(controller: _controller);
  }
}
```

It initially suggests that `_controller` should be `TextEditingController?`

So then you give it a hint to be non-null, like so:

```dart
// @dart=2.9

import 'package:flutter/material.dart';

class Foo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => FooState();
}

class FooState extends State<Foo> {
  TextEditingController/*!*/ _controller;

  void init() {
    _controller = TextEditingController(text: 'foo');
  }

  @override
  Widget build(BuildContext context) {
    return TextField(controller: _controller);
  }
}
```

The tool then suggests just making it non-null outright (by simply removing the `/*!*/`).  This doesn't compile.

What it should do is insert the `late` keyword.

**Comment by srawlins** [comment]
The tool does accept a late hint.

```
/*late*/ TextEditingController _controller;
```

Also `/*late final*/`

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
