### ISSUE TITLE
Failures on "[vm] Enable non-nullable experiment in the VM by default"

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#44049]
There are new test failures on [[vm] Enable non-nullable experiment in the VM by default](https://dart-review.googlesource.com/c/sdk/+/170201).

The tests
```
lib_2/isolate/issue_6610_test/0 RuntimeError (expected Pass)
lib_2/isolate/issue_6610_test/1 RuntimeError (expected Pass)
standalone_2/http_launch_test/0 RuntimeError (expected Pass)
standalone_2/http_launch_test/1 RuntimeError (expected Pass)
standalone_2/http_launch_test/2 RuntimeError (expected Pass)
standalone_2/http_launch_test/3 RuntimeError (expected Pass)
standalone_2/io/named_pipe_script_test RuntimeError (expected Pass)
standalone_2/io/test_extension_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-release-x64
```

/cc @a-siva

**Comment by alexmarkov** [comment]
Logs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8864624609608953696/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/170201 should fix these issues.
