### ISSUE TITLE
Add TargetKind for top-level variable

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#44046]
[TargetKind](https://pub.dev/documentation/meta/latest/meta_meta/TargetKind-class.html) lacks an entry for top-level variables. This makes it impossible to indicate that an `@Target()`-annotated annotation class is intended for use on top-level variables.

This is preventing AngularDart from annotating our `@GenerateInjector()` annotation class with `@Target()`, because it's most often used on top-level variables:

```dart
@GenerateInjector([
  ...
])
final injectorFactory = injectorFactory$Injector;
```

We _could_ enforce that it only be used on `TargetKind.getter` (which works for top-level getters), but this would be breaking for most, if not all, existing uses and require a migration:

```dart
@GenerateInjector([
  ...
])
InjectorFactory get injectorFactory => injectorFactory$Injector;
```

Since `TargetKind.function` already exists for distinguishing top-level functions from methods, I imagine adding a `TargetKind` for top-level variables would be reasonable?

**Comment by devoncarew** [comment]
cc @bwilkerson

**Comment by bwilkerson** [comment]
Yes, we can add a new constant to `TargetKind` and fix analyzer to handle it correctly.

How urgent is this? The main reason I ask is that it's a bit harder to modify the `meta` package right now because we have to maintain two versions: the pre null safety version and the migrated preview version. I'm willing to do the extra work, but if this isn't causing significant problems for your users and we can wait then I'd prefer to do that.

**Comment by leonsenft** [comment]
It's not urgent – we've been able to enforce the correct target kinds for all of our annotations except for the one blocked on this issue (19/20).

**Comment by bwilkerson** [comment]
Ok, thanks. Let me know if that changes.

**Comment by natebosch** [comment]
> The main reason I ask is that it's a bit harder to modify the `meta` package right now because we have to maintain two versions: the pre null safety version and the migrated preview version.

FWIW adding this only to the null safe version has the same result as waiting until we aren't maintaining both and adding it. Internal users will be able to use the migrated version.

**Comment by pq** [comment]
This was added as part of owrk to support `@useResult`.  (See: https://dart-review.googlesource.com/c/sdk/+/200301.)
