### ISSUE TITLE
VM doesn't properly enable sound null safety

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44043]
After removing the experiment flag, the VM no longer seems to correctly run with sound null safety.

### Repro

1. Create an empty directory
1. Create a file repro.dart containing:
```
void main(List<String> arguments) {
  print('Hello, ${<int?>[] is! List<int>} world!');
}
```
1. Run it: `dart run repro.dart`

Expected result: prints "hello true world" as we're running with sound null safety (we have no deps.

Actual result: runs with partial/unsound null safety
```
$ dart repro.dart
Hello, false world!
```

Also observe that `dart --enable-experiment=non-nullable repro.dart` runs with soundness.

**Comment by mit-mit** [comment]
cc @leafpetersen can you please confirm that I'm correct here?
cc @a-siva can you assign an owner?

**Comment by jakemac53** [comment]
Fwiw I did locally confirm the issue

**Comment by johnniwinther** [comment]
I think this is the same problem as in https://github.com/dart-lang/sdk/issues/44026

**Comment by alexmarkov** [comment]
VM still performs sound null safety mode auto-detection only if `--enable-experiment=non-nullable` is specified.
Duplicate to https://github.com/dart-lang/sdk/issues/44026.
