### ISSUE TITLE
Dart 2.10.3 rollout failed on Chocolatey

### ISSUE THREAD

**Issue by Sominemo** [dart-lang/sdk#44052]
Dart SDK 2.10.3 is unavailable to be downloaded from chocolatey because of an error:
https://chocolatey.org/packages/dart-sdk/2.10.3
![image](https://user-images.githubusercontent.com/19842935/98081202-5aeb9300-1e7f-11eb-86fb-b303e6c6fbae.png)

Log:
https://gist.github.com/choco-bot/31962ded3c14bab330576190c3880d19

**Comment by athomas** [comment]
Looks like another flake in chocolatey. I re-triggered the verification.

**Comment by athomas** [comment]
This is fixed now, thanks for the report!
