### ISSUE TITLE
File name is case insensitive

### ISSUE THREAD

**Issue by nikitadol** [dart-lang/sdk#44059]
```console
dart --version
Dart SDK version: 2.10.3 (stable) (Tue Oct 27 14:44:30 2020 +0100) on "macos_x64"
```

```dart
import 'dart:io';

void main() {
  File('L.txt').createSync();
  File('l.txt').createSync();
}
```

Expected Result:
2 files named 'L' and 'l' will be created

Actual result:
One file was created called 'L'

**Comment by nikitadol** [comment]
Perhaps this is a problem with the macos file system

**Comment by sortie** [comment]
macOS filesystems are case insensitive by default. Can you confirm whether your macOS filesystem in question is configured to be case sensitive or not? Unless the macOS filesystem is case sensitive, this is not a Dart problem.

**Comment by nikitadol** [comment]
@sortie 
You're right
![Screen Shot 2020-11-09 at 17 00 20](https://user-images.githubusercontent.com/16593680/98557573-0dbb5700-22ad-11eb-92b5-153395397665.png)

**Comment by sortie** [comment]
In that case, I'm closing this issue. You can reconfigure your filesystem to be case sensitive if you want case sensitive semantics in Dart.
