### ISSUE TITLE
expect.dart uses deprecated null safety terminology

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44062]
[expect.dart](https://github.com/dart-lang/sdk/blob/master/pkg/expect/lib/expect.dart) uses deprecated null safety terminology:

```dart
/// Whether the program is running with weak null safety checking.
bool get isWeakMode => const <Null>[] is List<Object>;

/// Whether the program is running with strong null safety checking.
bool get isStrongMode => !isWeakMode;)
```

I'd like to use the terminology we use elsewhere, from https://github.com/dart-lang/sdk/issues/42464#issue-644591561:

strong mode => sound null safety
weak mode => unsound null safety

**Comment by eernstg** [comment]
Done in https://dart-review.googlesource.com/c/sdk/+/170424; cf. https://dart-review.googlesource.com/c/sdk/+/170430 as well.
