### ISSUE TITLE
Null safety feedback: When using ?: operator,  the null safety state of variable is not recognized 

### ISSUE THREAD

**Issue by unalone** [dart-lang/sdk#44068]
Thinking this code:
var someVar = someObj.someFunctionWhichMayReturnANullResult();
if (someVar != null) {
  ...some code
}

......

In this situation, the code running within block can safety assume that the someVar is not null.

But if we write this code in such way:
var someVar = someObj.someFunctionWhichMayReturnANullResult();
var someOtherVar = someVar == null ? someDefaultValue : someVar.someMethod();
........

Complier will report error that someVar maybe null, and so someVar.someMethod() should be written in someVar!.someMethod().

Is it a bug?

**Comment by nshahan** [comment]
Does this code replicate the issue you are seeing? I don't see any compiler errors for this code.

```dart
class A {
  int? foo() => null;
}

void main() async {
  var i = A().foo();
  var x = i == null ? 10 : i.abs();
}
```

**Comment by mraleph** [comment]
@unalone please provide as many details as possible e.g. Flutter/Dart SDK versions, code to reproduce the issue, which tool is reporting an error (dart2js, ddc, dart vm, dartanalyzer, IDE, etc). With the current amount of information we can't make much progress on this.

**Comment by mraleph** [comment]
Given no response, I am going to close the issue.
