### ISSUE TITLE
FFI cause OS halt

### ISSUE THREAD

**Issue by herehere** [dart-lang/sdk#44067]
* Dart SDK Version : Dart SDK version: 2.10.0-107.0.dev (dev) (Wed Sep 9 05:37:05 2020 -0700) on "windows_x64"
* Using Windows
* dart:ffi

I'm testing dart ffi for callback function, but I don't know if this is a bug or just I write the wrong statement. The situation will cause the OS halt thus I need to reset the computer. Sample is something like below:

[native]
![native](https://user-images.githubusercontent.com/10718801/98186420-a9fdfa80-1f49-11eb-9b0b-fff73bb908b8.png)

[dart]
![dart](https://user-images.githubusercontent.com/10718801/98186427-ad918180-1f49-11eb-8859-4245b4f5fa6f.png)

But if I change to passing a parameter to native as below, that will work through.

[native]
![native_good](https://user-images.githubusercontent.com/10718801/98186441-b2563580-1f49-11eb-8695-cd96309c9ea1.png)

[dart]
![dart_good](https://user-images.githubusercontent.com/10718801/98186455-b7b38000-1f49-11eb-9b8a-a966d33993eb.png)

**Comment by dcharkes** [comment]
> ```c
> void CBTest(void) { ... }
> ```
>
> ```dart
> cffi_VoidVoid = Void Function(Void);
> dffi_VoidVoid = void Function(void);
> ```

We have not implemented support for `void` in parameter positions in the FFI. We should either add support for this, or make it an error. I've opened https://github.com/dart-lang/sdk/issues/44090 to address this. Thanks for reporting!

Try using the following instead for now:

```c
void CBTest() { ... }
```

```dart
cffi_VoidVoid = Void Function();
dffi_VoidVoid = void Function();
```

**Comment by herehere** [comment]
Thanks, that clear my confuse.
