### ISSUE TITLE
Migration tool should suggest casting for-loop iterables

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44075]
When encountering code like this:
```dart
void f(Iterable<Object> iterable) {
  for (String s in iterable) {
    ...
  }
}
```
the migration tool should suggest the use of `.cast` in order to preserve semantics, i.e.:
```dart
void f(Iterable<Object> iterable) {
  for (var s in iterable.cast<String>) {
    ...
  }
}
```

**Comment by srawlins** [comment]
Right now I think the analyzer suggests the following:

```dart
void f(Iterable<Object> iterable) {
  for (String s in iterable as Iterable<String>) {
    ...
  }
}
```

**Comment by stereotype441** [comment]
> Right now I think the analyzer suggests the following:
> 
> ```dart
> void f(Iterable<Object> iterable) {
>   for (String s in iterable as Iterable<String>) {
>     ...
>   }
> }
> ```

Yeah, that sounds plausible.  And it's definitely not what we want, because the insterted `as` check will fail if the type of the *iterable* is wrong, whereas the pre-migration semantics were to fail only if iteration yields a *value* whose type is wrong.

**Comment by lrhn** [comment]
Using `.cast` is possible (and probably optimal apart from the memory overhead).
The preserve-existing-semantics translation would be
```dart
for (var s in iterable) {
  s as String;
  ...
}
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
