### ISSUE TITLE
fixes with overlapping source edits create un-analyzable results

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#44080]
Some fixes (such as `unnecessary_new` and `prefer_collection_literals`) might have overlapping source edits which when applied produce mangled source.

**Comment by bwilkerson** [comment]
I believe that this has now been fixed, so I'm going to close this issue. If we see cases where that isn't true then we should open new issues for the specific cases.

**Comment by pq** [comment]
Yes.  Thanks!
