### ISSUE TITLE
Have some way to interrupt a chain of Futures?

### ISSUE THREAD

**Issue by huanghui1998hhh** [dart-lang/sdk#44085]
```
funcA().then((bool value){
    if(value){
      return x;
    }else{
      break;       //break at this
    }})
  .then((value)=>funcC())
```
I want to make a judgment, based on the results of the funcA() whether to interrupt the chain.So how to implement the interrupt.

**Comment by mraleph** [comment]
You can't really interrupt the chain of futures. You could however throw an exception if you don't want to complete the future successfully. /cc @lrhn

**Comment by lrhn** [comment]
As @mraleph says, you can't interrupt anything here.
Or, rather, that depends on what you mean by "interrupt", but most likely it's not going to do what you want.

The second `.then` is waiting for the future result of the first `then` to complete. The future already exists, and and when the callback of the first `then` completes, that future is completed, and then the second `then`'s callback is called.

If the first `then`'s future completes with a value, then the second `then`'s callback will be called. There is no way to avoid that.
If the first `then`'s future completes with an error, then the second `then'`s callback is *not* called, and its future completes with the same error. You then have to catch that error. You can do something like:
```dart
funcA().then((bool value) {
  if (value) {
    return x;
  } else {
    throw _BailOut();
  }
}).then((value) => funcC())
.catchError((error) => error is _BailOut ? null : (throw error));

...
// Exception class used to represent bailing out of a computation.
class _BailOut {}
```

If the first `then`'s future *never completes*, then the second `then'`s callback is *not* called and its future also never completes.
If that's acceptable to you, you can create and return a future which never competes as:
```dart
funcA().then((bool value) {
  if (value) {
    return x;
  } else {
    return Completer().future; // Never completed.
  }
}).then((value) => funcC())
```

I highly discourage introducing futures which never complete into your program. The results might be that some code that your users *expect* to run will never run. For example, if you return the result of the code above to someone else, and they do;
```dart
var future = ... your future ...;
var resource = allocateResource();
try {
  await future;
} finally {
  resource.dispose();
}
```
then the `finally` will never be executed. That has happened before, and it has consistently baffled users that it happens to.
You can end up with your program terminating and never getting into the `finally` block.
