### ISSUE TITLE
Nullable stream subscription triggers unavoidable "cancel_subscriptions" lint warning

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#44087]
Consider the following code:

```dart
  StreamSubscription<int>? _subscription;
  void _register() {
    _subscription = _myIntStream.listen(_onInt);
  }
  void _cancel() {
    if (_subscription != null) {
      _subscription!.cancel();
      _subscription = null;
    }
  }
```

This will trigger the `cancel_subscriptions` lint warning - because the linter doesn't see the `_subscription!.cancel()` call as a valid cancelation.  It only sees the cancelation if there's no `!` operator.

**Comment by tvolkert** [comment]
FYI @stereotype441

**Comment by stereotype441** [comment]
FYI @pq
