### ISSUE TITLE
[cfe] Missing bounds check on local function invocation

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#44092]
Consider the following program:

```dart
X whateverYouWant<X>() => throw "Not reached";

void main() {
  void f<X extends num>(X Function() g) => print(X);
  f(() => whateverYouWant());
}
```

With `dart` from cc853ee3e3f07dcf08c37cfdc01371d3349240d8, this program is accepted, runs without dynamic errors, and prints `dynamic`.

This shows that the type inference applied to `f(() => whateverYouWant())` chose the type argument `dynamic` for `f`, and subsequently did not detect that this is a bound violation.

If `f` is moved out to the top level then the check is performed and the program has a compile-time error.

With the given specification of the inference of the return type of a function literal, `() => whateverYouWant()` should get the return type `Object?`, and this may or may not give rise to `dynamic` for the invocation of `f` (I'd actually expect the result to be `Object?`), but the fact remains that the chosen type argument violates the bound, which is not allowed for an invocation of a generic function.

**Comment by eernstg** [comment]
NB: It seems likely that the core of the issue reported as #44073 is the issue described here.

**Comment by stefantsov** [comment]
This appears to be fixed now.
