### ISSUE TITLE
Add a quick fix to make a type nullable

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#44098]
I'm not 100% sure about this quick fix, but wanted to bring it up for consideration:

I ran into this where I had an optional, named param to a method. When I enabled NNBD, I saw an error that the type was not nullable and that no default param was supplied.

```
error: The parameter 'label' can't have a value of 'null' because of its type, and no non-null default value is provided. (missing_default_value_for_parameter at [dartdev] lib/src/events.dart:52)
```

We give users a quick fix to make the param `required` - by inserting the keyword. That's not the resolution I wanted in this case however - I did want the param to be optional. We might also give the user a quick fix to make the type nullable - `String? label`. This would save them a bit of typing but also help them understand about the different possible resolutions for this case.

cc @srawlins 

<img width="198" alt="Screen Shot 2020-11-06 at 8 17 29 AM" src="https://user-images.githubusercontent.com/1269969/98389163-8b126d80-2008-11eb-8166-73de790675dc.png">

ed: also, note that the error message: `'The parameter 'label' can't have a value of 'null' because of its type, and no non-null default value is provided'` - implies that the correct resolution might be to add a non-null default value.

**Comment by srawlins** [comment]
We have a MakeVariableNullable correction, but not one for parameters. I don't have a sense of how much code the two would share, but I do see a lot of code sharing in, e.g. AddTypeAnnotation.

cc @bwilkerson before I work too much in one direction, do you have a sense of whether it would be good to expand MakeVariableNullable (and possibly rename it) or to make a new CorrectionProducer specifically for paramters?

**Comment by bwilkerson** [comment]
I would start by trying to generalize what's there. The `FixKind` is appropriate (the message is already general enough and parameters are variables) and we generally have one `CorrectionProducer` per fix kind. It probably won't share a lot of code, but I still think it makes sense.

**Comment by srawlins** [comment]
Ah excellent, thanks much. I was honestly mostly worried about the naming, haha.
