### ISSUE TITLE
compile dart to assembly/microcontroller

### ISSUE THREAD

**Issue by aasirmutwalli22** [dart-lang/sdk#44099]
Using dartlang for programming microcontroller

**Comment by mraleph** [comment]
Sorry it is a very loosely defined feature request. Could you clarify?

**Comment by aasirmutwalli22** [comment]
> Sorry it is a very loosely defined feature request. Could you clarify?

If dart-lang can be used to program microcontrollers like arduino, esp32, etc.

**Comment by mraleph** [comment]
Short answer is no.
