### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by libindstme** [dart-lang/sdk#44108]
## Version information

- `IDEA AI-201.8743.12.41.6858069`
- `2.10.3`
- `AI-201.8743.12.41.6858069, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows Server 2016(amd64) v10.0 , screens 1920x1080`

**Comment by mraleph** [comment]
Please add feedback if any. This report just contains version information.
