### ISSUE TITLE
Migration tool should have an undo button

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#44106]
#### Steps to reproduce

run `dart/migrate <path to package>`
open link to tool
add some hints

#### What did you expect to happen?

I want to be able to click button 'Undo'

#### What actually happened?

There is no button 'Undo'

_Screenshots are appreciated_

**Dart SDK version**: 2.12.340990508-edge+google3-v2

Thanks for filing!

**Comment by polina-c** [comment]
I cot it converting https://pub.dev/packages/self_storing_input

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
