### ISSUE TITLE
Migration tool UI should distinguish files being migrated from those already migrated or not being migrated yet

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44101]
(Reported by Tijo Jose)

When partially migrating a package, either for the first time or for an already partially migrated package, it would be helpful to be able to see which files are being migrated within the tool itself.

Currently, the left pane of the tool shows all files in the package with no way of distinguishing files that are already migrated, files that will be migrated in this run of the migration tool, and files that won't be migrated until later.

(Note that the functionality of having files that won't be migrated until later isn't currently exposed in the public-facing migration tool; exposing that publicly should be part of addressing this issue.)

**Comment by devoncarew** [comment]
This is complete.
