### ISSUE TITLE
the 'remove comparison' quick fix removes too much text

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#44102]
The 'remove comparison' quick fix can remove too much text - for my case, it removed a leading line comments in the body expression.

In this example, `locale` is now non-nullable:

<img width="538" alt="Screen Shot 2020-11-06 at 2 29 12 PM" src="https://user-images.githubusercontent.com/1269969/98422288-21ae5100-2040-11eb-8491-476e00502d08.png">

Here's the quick fix that's offered:

<img width="282" alt="Screen Shot 2020-11-06 at 2 29 17 PM" src="https://user-images.githubusercontent.com/1269969/98422313-34c12100-2040-11eb-9967-3d924e96a350.png">

And the result:

<img width="535" alt="Screen Shot 2020-11-06 at 2 29 23 PM" src="https://user-images.githubusercontent.com/1269969/98422335-40144c80-2040-11eb-94ae-671728052ef1.png">

Note that the leading line comment of the body expression has been removed.

cc @srawlins

**Comment by shilangyu** [comment]
This seems to affect any leading/trailing trivia of the `if` body (block or not). So these two are affected:

```dart
if (locale != null) {
	// leading comment
	final body = 'asd';
	// trailing comment
}
```

```dart
if (locale != null)
	// leading comment
	final body = 'asd';
```

Both will produce just `final body = 'asd';` after applying the fix to the `if` statement. It also trims any whitespace, but this is probably expected.

Can I work on this bug? I'd appreciate some links to dart's quick-fix contribution documentation.

**Comment by bwilkerson** [comment]
Contributions are always welcome.

The documentation for the implementation of quick fixes is in https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/implementation/quick_fix.md. The implementation for that specific fix is in https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/dart/remove_comparison.dart, and the tests are in https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/test/src/services/correction/fix/remove_comparison_test.dart.

If you have any questions we'll be happy to answer them.

**Comment by shilangyu** [comment]
Forgive the ping, I am unsure what the process for reviewal is: https://dart-review.googlesource.com/c/sdk/+/306220

**Comment by shilangyu** [comment]
Fixed in https://github.com/dart-lang/sdk/pull/52544
