### ISSUE TITLE
[CP][Stable] da133e5 DirectoryWatchHandle::Stop() is invoked after handle is released

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44104]
commit(s) to merge: da133e5047e0fb447af20cd142fc0cf8363487e6

merge instructions: merges cleanly into the stable branch and the beta branch 

What is the issue: DirectoryWatchHandle::Stop() is invoked after handle is released, crashing vm [43941](https://github.com/dart-lang/sdk/issues/43941)

What is the fix: Don't attempt to close already closed DirectoryWatchHandle

Why cherrypick: This has been broken for some time and we are getting frequent reports from the field regarding this.

Risk: Low based on the fact that the change has landed, been rolled internally and verified to fix the issue. We have not heard of any new issues appearing from those using the master branch. The fix is also targeted only for the Windows platform.

Link to original issue(s): https://github.com/dart-lang/sdk/issues/43941, https://github.com/flutter/flutter/issues/43620,  https://github.com/Dart-Code/Dart-Code/issues/2814

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @sigmundch @aam

**Comment by franklinyow** [comment]
CC: @pcsosinski

**Comment by franklinyow** [comment]
I support cherrypick to stable based on the number of users it hit over time.
I have reservation about a Beta pick because of a new Beta going to be cut next week.

**Comment by a-siva** [comment]
Beta is going to be cut next week but will it be available to external users immediately ?

**Comment by franklinyow** [comment]
Approved for stable

**Comment by franklinyow** [comment]
Target 11/12, so we should start build
@athomas, will this work?

This is a patch release that fixes a crash in vm runtime (#43941, flutter/flutter#43620, Dart-Code/Dart-Code#2814)

**Comment by athomas** [comment]
@franklinyow I will create the build tomorrow morning.

**Comment by athomas** [comment]
Cherry-picked to stable in 2.10.4 (7c148d029de32590a8d0d332bf807d25929f080e).

**Comment by aam** [comment]
@pcsosinski Perhaps this should stay opened until dart stable hotfix is cherry-picked into flutter stable?
