### ISSUE TITLE
'dart test' prints a pub deprecation notice

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#44105]
Running `dart test` results in the following output to console:

`The `pub` command is deprecated. Run `dart pub` instead.`

This is due to the fact that the test command is still running pub from snapshot whereas the pub command is embedded from package:pub as of [this change](https://dart-review.googlesource.com/c/sdk/+/168347).

We should either update the test command to not run from the pub snapshot or we should disable the deprecation notice until we can update the command.

cc/ @jonasfj @sigurdm

**Comment by pq** [comment]
See also: https://github.com/dart-lang/pub/issues/2734.

**Comment by mit-mit** [comment]
Being worked on in https://github.com/dart-lang/pub/pull/2735

**Comment by franklinyow** [comment]
Is there any work left for this one?

**Comment by bkonyi** [comment]
No this is complete.
