### ISSUE TITLE
Customer-reported issue with NNBD migration tool

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#44107]
The tool adds '!' after `Theme.of(context)` and `MediaQuery.of(context)`, then compiler gives error `The '!' will have no effect because the receiver can't be null. #unnecessary_non_null_assertion`

**Comment by srawlins** [comment]
Thanks for filing, @polina-c , can you give an example of code where the tool wishes to add a `!` which is then unnecessary? Thanks!

**Comment by polina-c** [comment]
I got it converting https://pub.dev/packages/self_storing_input

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
