### ISSUE TITLE
[windows][FFI] ffi call by pointer fail on active call function

### ISSUE THREAD

**Issue by herehere** [dart-lang/sdk#44113]
- Dart SDK Version : Dart SDK version: 2.10.0-107.0.dev (dev) (Wed Sep 9 05:37:05 2020 -0700) on "windows_x64"
- Using Windows
- dart:ffi

I'm not sure if I write a wrong statement or that is a bug.
I can success retrieve structure pointer from c++ native to dart in callback function's pointer parameter like this:
![callback](https://user-images.githubusercontent.com/10718801/98491908-3faec800-2271-11eb-9200-af01ccfe3c5d.png)

and success too at return value like this:
![returnValue](https://user-images.githubusercontent.com/10718801/98491952-5ead5a00-2271-11eb-8dd2-adf609a5ae54.png)

but if I using active call by pointer, it's fail neither following ways:
![callByPointer](https://user-images.githubusercontent.com/10718801/98492255-412cc000-2272-11eb-9d86-b222e4be8bb9.png)
![callByPointer_dart1](https://user-images.githubusercontent.com/10718801/98492265-44c04700-2272-11eb-8ea1-fce59439d173.png)
![callByPointer_dart2](https://user-images.githubusercontent.com/10718801/98492269-4722a100-2272-11eb-86c2-4f44ef5d8e0b.png)

**Comment by mraleph** [comment]
When you have a variable `void* p` and you do `p = something` you are just changing the value of the variable `p`. What you are probably looking for is `void** p` and `*p = something`.

**Comment by mraleph** [comment]
In future I recommend you to post code as text, rather than pictures. Text is much easier to read.

**Comment by herehere** [comment]
here is the code of native:

        #define LIST_LENGTH 5
	static int iList[LIST_LENGTH] = { 100, 101, 102, 103, 104 };

	int GetArray(int* pArr, int* length){
		if (pArr==nullptr){
			return false;
		}
		pArr = iList;
		*length = LIST_LENGTH;
		return true;
	}

	int GetpArray(int** pArr, int* length){
		if (pArr == nullptr){
			return false;
		}
		*pArr = iList;
		*length = LIST_LENGTH;
		return true;
	}

	int* GetArrayReturn(int* re, int* length){
		*length = LIST_LENGTH;
		*re = true;
		return iList;
	}

and the test code of dart:

typedef cffi_GetArray = ffi.Uint32 Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
typedef dffi_GetArray = int Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
dffi_GetArray gGetArrayFunc;

typedef cffi_GetArrayReturn = Pointer<ffi.Uint32> Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
typedef dffi_GetArrayReturn = Pointer<ffi.Uint32> Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
dffi_GetArrayReturn gGetArrayReturnFunc;

  Pointer<ffi.Uint32> getArray = allocate();
  Pointer<ffi.Uint32> getArrayLeng = allocate();

  getArray.value = 0;
  getArrayLeng.value = 0;
  var re = gGetArrayFunc(getArray, getArrayLeng);
  print("\n ($re)getArray(${getArrayLeng.value})[${getArray[0]}, ${getArray[1]}, ${getArray[2]}, ${getArray[3]}, ${getArray[4]}]");

  free(getArray);
  free(getArrayLeng);

  Pointer<ffi.Uint32> getpArray = allocate();
  Pointer<ffi.Uint32> getpArrayLeng = allocate();

  getpArray.value = 0;
  getpArrayLeng.value = 0;
  re = gGetpArrayFunc(getpArray, getpArrayLeng);
  print("\n ($re)getpArray(${getpArrayLeng.value})[${getpArray[0]}, ${getpArray[1]}, ${getpArray[2]}, ${getpArray[3]}, ${getpArray[4]}]");

  free(getpArray);
  free(getpArrayLeng);

  Pointer<ffi.Uint32> getpArrayReturnState = allocate();
  Pointer<ffi.Uint32> getpArrayReturnLeng = allocate();

  getpArrayReturnState.value = 0;
  getpArrayReturnLeng.value = 0;
  final Pointer<ffi.Uint32> getpArrayReturn = gGetArrayReturnFunc(getpArrayReturnState, getpArrayReturnLeng);
  print("\n (${getpArrayReturnState.value})getArrayReturn(${getpArrayLeng.value})[${getpArrayReturn[0]}, ${getpArrayReturn[1]}, ${getpArrayReturn[2]}, ${getpArrayReturn[3]}, ${getpArrayReturn[4]}]");

  free(getpArrayReturnState);
  free(getpArrayReturnLeng);

and i got the output:

flutter:
 (1)getArray(5)[0, 0, 889060994, 2147489778, 3487823424]
flutter:
 (1)getpArray(5)[871809024, 32760, 886570680, 2147495410, 3486704128]
flutter:
 (1)getArrayReturn(5)[100, 101, 102, 103, 104]

so currently i just can use return value to get the list from native, there are something i wrote the wrong statements?
