### ISSUE TITLE
Migration tool should recommend `flutter pub outdated` for Flutter projects

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44119]
Currently, when the migration tool detects unmigrated dependencies, it outputs an error message suggesting the user run `dart pub outdated --mode=null-safety --prereleases` to find newer versions of dependencies.  ~~This doesn't work for Flutter projects, since for a Flutter project, `dart pub outdated --mode=null-safety --prereleases` simply outputs `Package doesn't exist (the Flutter SDK is not available).`.~~ (Edit: this works provided that the `dart` command that is run is the one shipped with Flutter.  But I still think it would be nice if the tool would suggest running `flutter pub outdated` anyhow, because that's how Flutter users are probably used to running pub).

**Comment by devoncarew** [comment]
>  simply outputs Package doesn't exist (the Flutter SDK is not available).

That's especially unfortunate, given that that version of pub is actually running from the Flutter SDK - it should trivially be able to locate the Flutter SDK.

I think another resolution to this issue is for `dart pub outdated` to work correctly for flutter projects (when run from the dart sdk within the flutter sdk).

I'd thought we'd resolved this with https://github.com/dart-lang/pub/issues/2307 but apparently not. @mit-mit for thoughts

**Comment by mit-mit** [comment]
I cannot repro this:

```
mit-macbookpro4:tmp mit$ cd flu88
mit-macbookpro4:flu88 mit$ dart pub outdated --mode=null-safety --prereleases
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

All your dependencies declare support for null-safety.
```

Are you sure you don't have another `dart` in your path, which isn't the one from Flutter?

**Comment by stereotype441** [comment]
@mit-mit you're right, I was running `dart` from a local build of the SDK that was unconnected to Flutter--I didn't realize that `dart pub` behaves differently when invoked from an SDK inside flutter 😃

I personally would still like the migration tool to suggest `flutter pub outdated` when migrating a flutter project, because I think it would lead to less user confusion.  But it's way lower priority than I thought it was.

**Comment by stereotype441** [comment]
After further discussion I've learned that the flutter folks are moving away from having `flutter foo` commands that simply wrap the corresponding `dart foo` command.  So I now think that what the tool is doing is just fine.  Closing this issue.
