### ISSUE TITLE
dart_api_dl.c compilation failed

### ISSUE THREAD

**Issue by freetonsurfer** [dart-lang/sdk#44112]
Try to import dart_api_dl.c in my c++ library and have error:
./include/dart_api_dl.c:25:59: error: invalid conversion from ‘void (*)()’ to ‘DartApiEntry_function {aka void*}’ [-fpermissive]

gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

**Comment by dcharkes** [comment]
@freetonsurfer could you provide some more details? What compiler are you using? Do you have a minimal example that reproduces this?

**Comment by dcharkes** [comment]
Possibly your issue might already have been addressed in https://github.com/dart-lang/sdk/commit/30897929fc012602dc540a87fa1cb9b5e7db368d#diff-cf314b41711cfeb9fba4678f5b24aa1fc57ebc25bb69b2a80d8accf67ff8b700.

This has not been released in stable or beta yet. You can either switch to master, or apply the fix yourself for the time being.

**Comment by freetonsurfer** [comment]
compiler: gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

if change 
typedef void* DartApiEntry_function;
 to 
typedef void (*DartApiEntry_function)();
it compile.

 But i get include folder from this repository https://github.com/dcharkes/go_dart_ffi_example/tree/master/dart_api_dl
