### ISSUE TITLE
have a way to integration test a 'dart fix' fix

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#44129]
We should have a way to integration test a data-driven fix. This will likely look like a set of command line flags to `dart fix`, and will probably use a golden master testing technique (being able to provide both the source before the fix and the expected source after the fix).

cc @bwilkerson @goderbauer

**Comment by bwilkerson** [comment]
I believe that this is done by https://dart-review.googlesource.com/c/sdk/+/172684.
