### ISSUE TITLE
FFI documentation missing instructions for static libraries

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#44126]
Relevant documentation: https://dart.dev/guides/libraries/c-interop

The FFI documentation is missing any mention of calling into C functions in the current executable and only shows examples of looking up functions that live in shared libraries.  Other languages like C# support looking up symbols in the current executable (example `DllImport("__Internal")` for Mono).

If we don't support calling c functions in the current executable (ie static libraries) we should explicitly say we don't support it.  If we do support it, we should provide guidance on how it's done.

**Comment by gaaclarke** [comment]
Dart does support it, you have to use `DynamicLibrary.executable()`:

c:
```c
extern "C" {
  __attribute__((used, visibility("default"))) void Foobar(Dart_Handle arg) {
    FML_LOG(ERROR) << "aaclarke: foobar " << arg;
  }
}
```

dart:
```dart
typedef foobar_func = ffi.Void Function(ffi.Handle);
typedef Foobar = void Function(Isolate);

@pragma('vm:entry-point')
void _spawn() async {
  Future<Isolate> isolate = Isolate.spawn(spawned, 1234);
  ffi.DynamicLibrary lib = ffi.DynamicLibrary.executable();
  final Foobar foobar = lib
      .lookup<ffi.NativeFunction<foobar_func>>('Foobar')
      .asFunction();
  foobar(await isolate);
}
```

**Comment by maks** [comment]
Should this be closed now that this is documented or at least its documented in the context of iOS where static lib usage is common: https://docs.flutter.dev/development/platform-integration/c-interop#ios-and-macos 
and https://api.dart.dev/dev/2.18.0-54.0.dev/dart-ffi/DynamicLibrary/DynamicLibrary.executable.html

**Comment by gaaclarke** [comment]
I think it's a problem that google search for "dart ffi static library" probably wouldn't hit either of those.

**Comment by gaaclarke** [comment]
I updated the docstring: https://dart-review.googlesource.com/c/sdk/+/242242
