### ISSUE TITLE
Changing sdk constraint doesn't affect analysis

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#44131]
It's going to be very common in the coming few releases for people to find that they need to update their "sdk" constraint in their pubspec.yaml. Currently, this does not affect `flutter analyze --watch` results, but it should have a serious effect on that. (In particular, switching between nnbd-enabled and nnbd-disabled versions.)

cc @devoncarew @mit-mit @leafpetersen

**Comment by mit-mit** [comment]
https://github.com/dart-lang/sdk/issues/44131 is a similar issue where changing the constraint doesn't affect analysis in vscode

**Comment by mit-mit** [comment]
cc @bwilkerson

**Comment by bwilkerson** [comment]
Do the results get updated after running `flutter pub get` (or `upgrade`)? I believe that the analyzer uses the content of the `package_config.json` file as the source of truth rather than the `pubspec.yaml` file. But it would be useful to know if the server isn't watching the `package_config.json` file as it should be.

@scheglov

**Comment by mit-mit** [comment]
It does not, see detailed steps in https://github.com/dart-lang/sdk/issues/44139

**Comment by devoncarew** [comment]
@mit-mit - I would close one of these two issues as effective dups of each other.

It sounds like we don't switch expectations for nnbd analysis with a pubspec change, which is expected, but we also don't switch after `pub get` writes the new values into the package_config.json file, which we probably should do. We have similar watching set up for the analysis options file. That's user authored - unlike package_config.json. For that file, we don't change analysis modes as people type, but update after the file is changed on disk (that's pragmatic, given how expensive it is to change analysis modes).

**Comment by mit-mit** [comment]
I'll close the other bug; here are the repro step from that:

1. Setup vscode to use a `2.12.0` dev release.
2. Open a project with a Dart package without an SDK constraint and add some code that isn't migrated to null safety.
3. Notice that vscode correctly adds errors for the unmigrated code (language version defaults to `2.12`).
4. Add an SDK constraint to the pubspec.yaml: `sdk: '>=2.10.0 <3.0.0'`.
5. pub get (vscode does this automatically).
6. Even though the language version should now be `2.10`, the null-safety errors still show and null-safety syntax is accepted.
7. Restart vscode, and observe how the editor flips to `2.10` mode an no longer accepts null-safety syntax.

**Comment by devoncarew** [comment]
@scheglov - can you do a rough cost estimate here? To watch the package_config.json and do something like restart analysis / re-analyze if a large enough semantic change happens.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/171360

**Comment by leafpetersen** [comment]
Cherry pick filed [here](https://github.com/dart-lang/sdk/issues/44184).

**Comment by franklinyow** [comment]
I think we can closed this one?
