### ISSUE TITLE
`dart pub --disable-dartdev-analytics` works but `dart --disable-dartdev-analytics pub` doesn't

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#44135]
This is because the vm doesn't recognize the flag, but this flag belongs to the main dart command, not the subcommand.

This might not be urgent, as this flag is not exposed by default.

But it makes embedding the dart tool into eg. flutter awkward.

See https://github.com/dart-lang/pub/issues/2736

**Comment by sigurdm** [comment]
Filed: https://dart-review.googlesource.com/c/sdk/+/171284

**Comment by bkonyi** [comment]
@sigurdm is this still relevant?

**Comment by sigurdm** [comment]
No! It was fixed with: https://dart-review.googlesource.com/c/sdk/+/171284 !
