### ISSUE TITLE
VM incorrectly equates generic types with top bounds

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#44136]
Consider the following program:

```dart
typedef Foo = void Function<X extends dynamic>();
typedef Bar = void Function<X extends Object?>();

void main() {
  print(Foo == Bar);
}
```

dart2js prints `false`, but the VM prints `true`, which I think is incorrect based on the [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-type-equality-operator) and the discussion at https://github.com/dart-lang/language/issues/818 and elsewhere.

Primitive top types are not made equivalent by normalization or `*`-erasure, so these function types should be treated as having different bounds. (We treat these bounds as equal during *subtyping*, but not for *type equality*.)

**Comment by eernstg** [comment]
`Foo == Bar` should evaluate to false based on the requirement that equal types have equal top-type components, e.g.,

> `List<void>` and `List<dynamic>` are still considered distinct runtime type objects

So wouldn't this be 'correct' rather than 'incorrect'?:

> The VM prints `false`, which I think is incorrect

**Comment by fishythefish** [comment]
@eernstg Whoops, typo'd that in the course of editing. Fixed.

**Comment by eernstg** [comment]
OK, thanks!

**Comment by alexmarkov** [comment]
@crelier

**Comment by crelier** [comment]
This wrong behavior only happens when the bound is `dynamic`. It is due to this special handling code in runtime/vm/compiler/frontend/kernel_translation_helper.cc:3341:

```
    // TODO(github.com/dart-lang/kernel/issues/42): This should be handled
    // by the frontend.
    parameter ^= type_parameters.TypeAt(i);
    const Tag tag = helper_->PeekTag();  // peek ith bound type.
    if (tag == kDynamicType) {
      helper_->SkipDartType();  // read ith bound.
      parameter.set_bound(
          Type::Handle(Z, nnbd_mode == NNBDMode::kOptedInLib
                              ? I->object_store()->nullable_object_type()
                              : I->object_store()->legacy_object_type()));
    } else {
      AbstractType& bound = BuildTypeWithoutFinalization();  // read ith bound.
      parameter.set_bound(bound);
    }
```

The mentioned issue github.com/dart-lang/kernel/issues/42 is still open. Let me look into it before removing the code above.

**Comment by crelier** [comment]
The mentioned kernel issue is in an archived repository and not relevant anymore.
If the bound is not specified, CFE will use `Object*` in an opted-out library or `Object?` in an opted-in library. So I am pretty sure that the above workaround is not needed anymore. It is actually harmful in case the bound was written as `dynamic`, as shown in this issue.
I will remove it and send a CL.
