### ISSUE TITLE
Failures on [vm/concurrency] Remove code duplication in isolate shutdown code

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#44141]
The [cl/170984](https://dart-review.googlesource.com/c/sdk/+/170984) I made is removing some code duplication. To keep validation of canonical constants (which we currently only do in helper isolate shutdown), I've moved the validation logic to a place where it's run for any isolate shutdown (even main isolate).

Doing so seems to reveal existing bugs that trigger during the canonicalization visitor checks:

The tests
```
language/closure/tearoff_bounds_instantiation_test Crash (expected Pass)
language/least_upper_bound/expansive_runtime_test Crash (expected Pass)
language/nnbd/normalization/generic_function_type_object_normalization_test Crash (expected Pass)
language_2/closure/tearoff_bounds_instantiation_test Crash (expected Pass)
language_2/least_upper_bound/expansive_runtime_test Crash (expected Pass)
vm/cc/CleanupBequestNeverReceived Crash (expected Pass)
vm/cc/CustomIsolates Crash (expected Pass)
vm/cc/ManySimpleTasksWithZones Crash (expected Pass)
vm/cc/ReceivesSendAndExitMessage Crash (expected Pass)
```
are failing on `-n dartk-linux-debug-x64` and all other debug configurations.

Some are due to `TypeParameter` objects of signature functions (e.g. the `language_2/closure/tearoff_bounds_instantiation_test`).
Some are due to `Type` parameter objects (e.g. `vm/cc/CleanupBequestNeverReceived`)

@crelier Could you maybe take a look at those failures?

**Comment by crelier** [comment]
Some of these failures are not reproducible in my pending CL introducing a proper FunctionType. However, since the CL is not ready yet, I'll have a look in the current tree, sure.

**Comment by sstrickl** [comment]
Also marking these as approved where they show up on other bots post-landing.

**Comment by mkustermann** [comment]
> However, since the CL is not ready yet, I'll have a look in the current tree, sure.

@crelier sounds good.

The CL landed today. The first failure e.g. can be reproduced via:
```
% out/DebugX64/dart tests/language/closure/tearoff_bounds_instantiation_test.dart
../../runtime/vm/object.cc: 6518: error: expected: (index >= 0) && (index < Length())
version=2.12.0-edge.ea9a4b1a7850a36e58cafae7631674839501a359 (be) (Wed Nov 11 09:14:08 2020 +0000) on "linux_x64"
pid=3946134, thread=3946134, isolate_group=main(0x556c24bfb600), isolate=main(0x556c24c08900)
isolate_instructions=556c23409180, vm_instructions=556c23409180
  pc 0x0000556c238a7776 fp 0x00007ffc925c71b0 dart::Profiler::DumpStackTrace(bool)+0x26
  pc 0x0000556c238a76b4 fp 0x00007ffc925c72f0 dart::Profiler::DumpStackTrace(void*)+0x24
  pc 0x0000556c23f66af5 fp 0x00007ffc925c7310 Dart_DumpNativeStackTrace+0x15
  pc 0x0000556c23409437 fp 0x00007ffc925c74d0 dart::Assert::Fail(char const*, ...)+0x187
  pc 0x0000556c237e659f fp 0x00007ffc925c7510 dart::TypeArguments::TypeAddr(long) const+0x6f
  pc 0x0000556c237d26a1 fp 0x00007ffc925c7550 dart::TypeArguments::TypeAt(long) const+0x71
  pc 0x0000556c2383bb77 fp 0x00007ffc925c76d0 dart::TypeParameter::CheckIsCanonical(dart::Thread*) const+0x1b7
  pc 0x0000556c239f5e55 fp 0x00007ffc925c7720 dart::VerifyCanonicalVisitor::VisitObject(dart::ObjectPtr)+0xb5
...
```

**Comment by crelier** [comment]
I have a [CL](https://dart-review.googlesource.com/c/sdk/+/171807) out fixing the language and language_2 tests, but not the vm/cc tests. I do not think these fail because of issues in type finalization or canonicalization.

**Comment by mkustermann** [comment]
> I have a CL out fixing the language and language_2 tests, but not the vm/cc tests. I do not think these fail because
> of issues in type finalization or canonicalization.

Thanks, @crelier ! I'll fix the remaining ones in [cl/171886](https://dart-review.googlesource.com/c/sdk/+/171886)
