### ISSUE TITLE
Missing null check in AOT when calling override of Object method with changed signature

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#44140]
```dart
// @dart = 2.10

class A {
  String toString({String extra = "x"}) => "A: $extra";
}

void foo(A a) {
  print(a.toString());
  print(a.toString(extra: "y"));
}

void main() {
  foo(A());
  foo(null);
}
```
When run in AOT mode, this prints:
```
A: x
A: y
null
null
```
The correct behavior would be to throw `NoSuchMethodError` on the second `null`, since `Null` does not have a `toString` method with the extended signature.

The bug was introduced with the table dispatch. The code generation for `DispatchTableCall` should insert a null check if the selector is understood by `Object` but the signature is different, and the receiver is nullable.

The problem does not affect opted-in code, since calling an `Object` method on a nullable value is only allowed if the signature matches.

**Comment by mkustermann** [comment]
@askeksa-google Nice catch! Could you take a look at it, since it was introduced by the dispatch table work?

**Comment by lrhn** [comment]
It does affect null safe ("opted in") code in _unsound null-safe_ mode because non-nullably typed expressions can still end up being `null`.
It doesn't affect sound null-safe programs.

**Comment by a-siva** [comment]
this seems to have slipped through the cracks, has this been fixed ?

**Comment by askeksa-google** [comment]
It has not. I was working on a [fix](https://dart-review.googlesource.com/c/sdk/+/172761), but it was not clear in general what the correct behavior should be. The specific problem mentioned here is part of a wider [unsoundness issue at the language level](https://github.com/dart-lang/language/issues/1322) which has not been solved. So the fix was postponed waiting for a decision from the language team about how this should behave.

The [suggestion](https://github.com/dart-lang/language/issues/1322#issuecomment-733714383) from @eernstg seems easy to implement, especially after the recent function signature refactoring.

**Comment by mkustermann** [comment]
@a-siva I think this issue can be summarised as follows:

  * **NNBD strong mode**:
    * No issue. This will become the default.
  * **NNBD weak / legacy mode**:
    * Possibility to cause a crash by overriding `Type get runtimeType` ...  - we are unaware of anyone doing this and seems very unlikely
       => As part of https://github.com/dart-lang/language/issues/1322 the language team could decide to make those overrides a compile-time error.
    * Incorrect semantics for methods like `toString()` if interface target has arguments: When called on `null` it should throw NSM, but instead returns `Null.toString()`.
      => Would be a breaking change, as part of https://github.com/dart-lang/language/issues/1322 the language team could decide on that.

Given that it's only problematic in legacy / unsound mode, the former issue seems very unlikely to happen in practice, the latter issue seems benign, so we don't intend to do anything for the time being.

If the language team decides it's worthwhile to makes concrete decisions on https://github.com/dart-lang/language/issues/1322 we could implement them.

/cc @leafpetersen

**Comment by askeksa** [comment]
Since we now only support sound null safety, this issue is obsolete.
