### ISSUE TITLE
js-interop: ensure function arguments passed to setProperty use `allowInterop`

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#44145]
Earlier this year @natebosch [added checks][1] to ensure that DDC didn't allow passing through callbacks via `package:js` that were not wrapped with allowInterop. We'd like to do the same with `js_util.setProperty`.

[1]: https://dart-review.googlesource.com/c/sdk/+/128462

**Comment by natebosch** [comment]
Might also want to check the list of arguments when using `js_util.callMethod`.
