### ISSUE TITLE
[windows][FFI] ffi retrieve value without initialized cause error

### ISSUE THREAD

**Issue by herehere** [dart-lang/sdk#44147]
Dart SDK Version : Dart SDK version: 2.10.0-107.0.dev (dev) (Wed Sep 9 05:37:05 2020 -0700) on "windows_x64"
Using Windows
dart:ffi

I think that is a bug issue, cause dart retrieve c native value by pointer return wrong value.
my native value is initialized to zero.
![native_output](https://user-images.githubusercontent.com/10718801/98756829-49b5ff80-2406-11eb-85dc-5a0b549df3b2.png)

if i initialize the value before call ffi, i can get the right value, like this:
![initialized_code](https://user-images.githubusercontent.com/10718801/98756735-1bd0bb00-2406-11eb-9ebe-52a0392a2a35.png)
![initialized_output](https://user-images.githubusercontent.com/10718801/98756753-225f3280-2406-11eb-94f7-eb73177f577f.png)

but if i didn't initialize it, i will get the wrong return, like this:
![uninitialized_code](https://user-images.githubusercontent.com/10718801/98756842-4fabe080-2406-11eb-8af1-8142cb10add0.png)
![uninitialized_output](https://user-images.githubusercontent.com/10718801/98756852-54709480-2406-11eb-9d97-06216fb91d42.png)

**Comment by mraleph** [comment]
Hard to say what exactly is going wrong without seeing what `getBitmapInfo` does - please include that into the report. However most likely the problem is in your code. 

Additionally I highly encourage you to stop posting picture and start posting *code as text*.

**Comment by herehere** [comment]
I write a simple sample for you, maybe you can figure out what is wrong for it.

test func in native:

	bool GetWH(int* w, int* h){
		if (w==nullptr || h==nullptr){
			return false;
		}
		*w = 0;
		*h = 0;
		return true;
	}

	bool GetpWH(int** w, int** h){
		if (w == nullptr || h == nullptr){
			return false;
		}
		*w = 0;
		*h = 0;
		return true;
	}

test code at dart:

  Pointer<ffi.Uint64> getW = allocate();
  Pointer<ffi.Uint64> getH = allocate();

  print("\n getWH: ${getW.value} x ${getH.value}");
  gGetWHFunc(getW, getH);
  print("\n getWH: ${getW.value} x ${getH.value}");

  free(getW);
  free(getH);

  Pointer<ffi.Uint64> getWIni = allocate();
  Pointer<ffi.Uint64> getHIni = allocate();

  getWIni.value = 100;
  getHIni.value = 100;
  print("\n getWHIni: ${getWIni.value} x ${getHIni.value}");
  gGetWHFunc(getWIni, getHIni);
  print("\n getWHIni: ${getWIni.value} x ${getHIni.value}");

  free(getWIni);
  free(getHIni);

  Pointer<ffi.Uint64> getpW = allocate();
  Pointer<ffi.Uint64> getpH = allocate();

  print("\n getpWH: ${getpW.value} x ${getpH.value}");
  gGetpWHFunc(getpW, getpH);
  print("\n getpWH: ${getpW.value} x ${getpH.value}");

  free(getpW);
  free(getpH);

  Pointer<ffi.Uint64> getpWIni = allocate();
  Pointer<ffi.Uint64> getpHIni = allocate();

  print("\n getpWHIni: ${getpWIni.value} x ${getpHIni.value}");
  gGetpWHFunc(getWIni, getHIni);
  print("\n getpWHIni: ${getpWIni.value} x ${getpHIni.value}");

  free(getpWIni);
  free(getpHIni);

and i got the output like this:

flutter:
 getWH: 2390724684320 x 2390724687408
flutter:
 getWH: 2388001816576 x 2388001816576
flutter:
 getWHIni: 100 x 100
flutter:
 getWHIni: 0 x 0
flutter:
 getpWH: 2390724684272 x 5567
flutter:
 getpWH: 0 x 0
flutter:
 getpWHIni: 2390833968544 x 2390724684288
flutter:
 getpWHIni: 2390833968544 x 2390724684288

obviously difference on the value is initialized or not.

**Comment by mraleph** [comment]
There is no reason to file multiple issues for the same thing. 

Can you provide full runnable code for both C++ and Dart (e.g. if you are using flutter for desktop create a sample project and put it on github). Otherwise it is hard to figure out what is going on. The code you provided works just fine for me on Mac - so this might be some Windows specific issue, but I don't have access to Windows machine to verify.  

Side note: your `GetpWH` has signature mismatch for Dart FFI vs C++. C++ declares pointer-to-pointer-to-int parameters, while in Dart you specify pointer-to-int parameters.

As a debugging measure you can try to do the following:

```dart
print('Dart pointers: ${getW.address.toRadixString(16)} ${getW.address.toRadixString(16)}');
gGetWHFunc(getW, getH);
```

```cpp
bool GetWH(int* w, int* h){
    printf("C++ pointers: %p %p", w, h);
	if (w==nullptr || h==nullptr){
		return false;
	}
	*w = 0;
	*h = 0;
	return true;
}
```



/cc @dcharkes

**Comment by dcharkes** [comment]
> Can you provide full runnable code for both C++ and Dart (e.g. if you are using flutter for desktop create a sample project and put it on github).

This would make it much easier to help you indeed.

Please note that `int` is signed and `uint32_t` (`Uint32`) is not, so this will cause values to be zero extended instead of sign extended. You should use `Int32` in Dart instead, or change the C code to use `uint32_t`.

**Comment by herehere** [comment]
@dcharkes  You're right, this is type issue. I change to Int32 than get the right retrieve value, but as my image signed/unsigned just the sign bit difference description, why that cause retrieve fail?
Thanks for the replay.

**Comment by dcharkes** [comment]
@herehere We're not just talking about a sign bit. Integers in C and Dart are two's complement: https://en.wikipedia.org/wiki/Two%27s_complement.
