### ISSUE TITLE
Tweak migration tool language

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#44146]
Output of `dart --version`

```
Dart SDK version: 2.12.0-31.0.dev (dev) (Mon Nov 9 16:07:01 2020 -0800) on "macos_x64"
```

Here are some places we can improve the output:

OLD:
```
Analyzing project...
[----------------------------------------------------------------------------------------\]No analysis issues found.
```

NEW:
* `\]` -> `]`?
* Linefeed before `No analysis issues found.`

-----------

OLD:
```
View the migration suggestions by visiting:
...
Use this interactive web view to review, improve, or apply the results.
```

NEW:
How about deleting the bottom line and changing the top line to: `Interactively migrate by visiting the following URL in a Chrome browser:`

-----------

OLD:
```
When finished with the preview, hit ctrl-c to terminate this process.
```

NEW:
`hit ctrl-c to terminate` -> `press Control+C to end`

(per google style: https://developers.google.com/style/ui-elements#keyboard, https://developers.google.com/style/word-list#letter-t)

**Comment by Sakshi725744** [comment]
can someone guide me approximate path to this file for changes?

**Comment by devoncarew** [comment]
cc @srawlins @stereotype441

**Comment by devoncarew** [comment]
@Sakshi725744 - I believe that most of the messages you'll want are in the https://github.com/dart-lang/sdk/blob/master/pkg/nnbd_migration/lib/migration_cli.dart file.

If you do make changes, note that much of the messages are under test; you'd want to grep through pkg/nnbd_migration/test/migration_cli_test.dart (and related) to see any tests need to be updated.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
