### ISSUE TITLE
dartdevk produces no error for external variable with no body invocation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#44148]
dartdevk produces no error in the following case
```dart
external int i1;

main() {
  Expect.throws(() { i1;}, (e) => e is NoSuchMethodError);
}
```
Here we provide no body for the external getter `i1` so `NoSuchMethodError` must be thrown. But there is no such error on dardevk on the edge version of SDK (2.12)

**Comment by nshahan** [comment]
I believe our plan here is that we want to produce compile time errors when the external members are missing JS interop annotations.

**Comment by sigmundch** [comment]
this also appears very related to https://github.com/dart-lang/sdk/issues/42730, should we merge the two?

**Comment by nshahan** [comment]
Yeah hopefully the fix for #42730 would be general enough to fix this as well. I'll just mention this example case there so we don't miss it.

**Comment by annagrin** [comment]
Looks like the issue is not yet fixed: 

See results for `co19/LanguageFeatures/Abstract-external-fields/static_analysis_external_A01_t03.dart` in `https://dart-ci.firebaseapp.com/current_results/#/filter=dartdevk-strong-linux-release-chrome`

**Comment by sigmundch** [comment]
Correct, let's however close this issue as a duplicate of #42730 and track the work there.
