### ISSUE TITLE
Dart incorrectly infers type as `dynamic` when a generic function is given a value

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#44153]
Very similar to issuse #36749 but the solution explained by @eernstg on that issue does not work in this scenario.

I have created a minimal reproducible example. Please note that this does not work on dart pad - it says 'no issues' but does code not run or provide error output.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(title: Text("Issue")),
        body:InifityLoader<String>(
        transformDoc: (m) => m.toString(),
        toInt: (String s) => s.hashCode
      )),
    );
  }
}

class InifityLoader<T> extends StatefulWidget {
  InifityLoader({
    @required this.transformDoc,
    @required this.toInt,
  });
  
  final T Function(Map d) transformDoc;
  final int Function(T) toInt;

  @override
  _InfinityLoaderState createState() => _InfinityLoaderState<T>();
}

class _InfinityLoaderState<T> extends State<InifityLoader> {
  
  @override
  Widget build(BuildContext context) {
    var testData = {'uid':123, 'name': 'jimmy'};
    var t = widget.transformDoc(testData);
    var i = widget.toInt(t);
    return Container(child: Text('out: $t $i'));
  } 
}

```

This fails with the error:
```
The following _TypeError was thrown building InifityLoader<String>(dirty, state: _InfinityLoaderState<String>#620c3):
type '(String) => int' is not a subtype of type '(dynamic) => int'
```

I have also tried to reproduce this without flutter, but this seems to work however this was with a single class for InifityLoader rather than having the two in flutter (StatefulWidget & State).

Thanks

**Comment by lrhn** [comment]
This looks like expected behavior. 
The issue might be that the declaration of `InfinityLoaderState` should be:
```dart
class _InfinityLoaderState<T> extends State<InifityLoader<T>> {
  ...
}
```
adding a `<T>` after `InfinityLoader`. 
Without that `<T>`, you have a `State<InfinityLoader<dynamic>>`, which means that it expects to read a `int Function(dynamic)` from `widget.transformDoc`. Since that read can fail at run-time due to covariant generics being unsound, the compiler inserts a run-time check at the read, which I'm guessing is what you see as the failure.

**Comment by jimmyff** [comment]
Ahhh you are correct! that explains why when I made a none-flutter version it worked.

Thanks for the assistance.
