### ISSUE TITLE
pub analysis (wrongly?) warns on paths in example pubspecs

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#44155]
```
[~/tmp/repos/google-fonts-flutter] (develop) $ flutter analyze
Analyzing google-fonts-flutter...

warning • Publishable packages can't have path dependencies • example/pubspec.yaml:15:5 • invalid_dependency

1 issue found. (ran in 19.3s)
```

See: https://github.com/material-foundation/google-fonts-flutter/blob/develop/example/pubspec.yaml

On the one hand, folks could mark examples `publish_to: none` to make this go away but that feels heavy handed.

@jonasfj, @sigurdm  : thoughts?

**Comment by sigurdm** [comment]
Hmm, the example could also remove the `version` field to become 'implicit publish_to: none".

It seems surprising to version the example independently of the main package.

**Comment by pq** [comment]
> It seems surprising to version the example independently of the main package.

I totally agree.  As a general rule I expect there to be very few instances where people _intend_ to version examples and expect this was not thought out.  It'd be interesting to do a scan of pub packages to see how many actually do though.  (Or I guess we'll find out soon if folks start hollering!)

**Comment by jonasfj** [comment]
I think flutter uses the `version` key in apps to communicate something else.
But many of the templates have been updated to carry `publish_to: none`, which helps prevent accidental publication.

**Comment by pq** [comment]
> many of the templates have been updated to carry publish_to: none, which helps prevent accidental publication.

I favor this in general for being explicit.

**Comment by pq** [comment]
In summary, I think we're in agreement that the analysis should stay as implemented and

1. templates updated where appropriate, and
2. existing projects updated

**Comment by DFelten** [comment]
We're currently using a specific branch of a repository via Git, but because of this there are now warnings

`warning: Publishable packages can't have git dependencies. (invalid_dependency at [tmx_core_dependencies] pubspec.yaml:25)`

Is it somehow possible to deactivate this warning?

**Comment by pq** [comment]
Adding `publish_to: none` (or removing the version info) should do it.

**Comment by DFelten** [comment]
> Adding `publish_to: none` (or removing the version info) should do it.

As far as I know this is not possible when using a Git repository which is from someone else. Of course we could make a fork and change the pubspec there, but is there also an other solution?

**Comment by pq** [comment]
Sorry, I meant in _your_ package.  It can't be published w/ git dependencies can it?  (Sorry if I'm remembering wrong.)

**Comment by jonasfj** [comment]
@pq, perhaps it fine to just close this issue?
