### ISSUE TITLE
Least and greatest closures are incorrect for covariant generic typedef check<X> = X Function()

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#44162]
Dart SDK version: 2.12.0-29.0.dev (dev) (Mon Nov 9 06:42:00 2020 -0800) on "windows_x64"

Here is a source code example:
``` dart
Type? _capturedTypeArgument;

X captureTypeArgument<X>() {
  _capturedTypeArgument = X;
  throw "Error";
}

Type? get capturedTypeArgument {
  var result = _capturedTypeArgument;
  _capturedTypeArgument = null;
  return result;
}

typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => <Y extends X>() {};
Type typeOf<X>() => X;

typedef check<X> = X Function();

void main() {
  void f<X>(check<X> Function() g) => g();
  try { f(() => captureTypeArgument()); } catch(_) {};
  print (typeOf<check>());
  print(capturedTypeArgument);
}
```
Seems like `Object?` should be substituted as a bound both for `check` and `capturedTypeArgument` here, however this is not so and sample output is:
> () => dynamic
> () => Object?

Please note that for another covariant case - `typedef check<X> = X Function()` - greatest closure is `Object?` in both cases.

See also similar issue against contravariant case: #44161.

**Comment by eernstg** [comment]
Cf. #44161 for a bit more detail.

This is working as intended: `typeOf<check>()` is obtained by applying i2b on the raw type `check`, and the resulting type is `dynamic Function()`. `capturedTypeArgument` is the greatest closure of `_ Function()` with respect to `{_}`, which is `Object? Function()`.
