### ISSUE TITLE
Analyzer throws unexpected compile error when checks least and greatest closures for contravariant generic typedef

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#44165]
Dart SDK version: 2.12.0-29.0.dev (dev) (Mon Nov 9 06:42:00 2020 -0800) on "windows_x64"

This issue is similar with #44161, but it's against the analyzer whereas #44161 is about the dart behavior.

Here is a source code example:

``` dart
X captureTypeArgument<X>() => throw "Error";

typedef check<X> = void Function(X x);

void main() {
  void f<X>(check<X> Function() g) => g();
  f(() => captureTypeArgument()..call(true));
}
```
Seems like analyzer should pass here, however it throws a compile error.  Analyzer sample output is:
> Analyzing test.dart...
>   error - The argument type 'bool' can't be assigned to the parameter type 'Never'. - test.dart:7:39 - argument_type_not_assignable
> 1 error found.

**Comment by eernstg** [comment]
Cf. #44161 for a bit more detail.

This is working as intended: The context type used for inference of `captureTypeArgument()` is the imposed return type schema `void Function(_)`, so the actual returned type is `void Function(Never)`, and the inferred return type of `() => captureTypeArgument()` is `void Function(Never)`, so the invocation of `call` with an actual argument of type `bool` is an error.
