### ISSUE TITLE
Can console.log(...) support multiple params?

### ISSUE THREAD

**Issue by chenenyu** [dart-lang/sdk#44168]

**Comment by Silentdoer** [comment]
dart has console.log(..) ?

**Comment by chenenyu** [comment]
@Silentdoer `dart:html`

**Comment by kevmoo** [comment]
We'll likely wait until we have https://github.com/dart-lang/language/issues/1014 – same for `print`

**Comment by sigmundch** [comment]
Thanks for filing the issue.

Until this is addressed, note you can use JS-interop to circumvent the problem:
```dart
@JS()
library foo;
import 'package:js/js.dart'
...

@JS('window.console')
external myConsole(arg1, arg2, arg3);

...
main() {
  myConsole(a, b, c);
}
```

or:
```dart
import 'dart:js_util' as js_util;
import 'dart:html';
...
main() {
  js_util.callMethod(window, 'console', [a, b, c]);
}
```
I was able to find a very similar and old request here: https://github.com/dart-lang/sdk/issues/19977, so I'll close this as a duplicate of that.
