### ISSUE TITLE
Wrong Calculations on floating point (double)

### ISSUE THREAD

**Issue by ahmedsalamay** [dart-lang/sdk#44167]
Thank you for taking the time to file an issue!

This tracker is for issues related to:
* dev_compiler

Simple just try to run the code below on dart pad or any ide 
void main() {
  var x= 4.235;
  var y=100;
  var result= x * y;
   print(result); //423.50000000000006
}

![test](https://user-images.githubusercontent.com/12111775/98918299-1a6ec380-24d6-11eb-9ce6-b13d9829c1d0.PNG)

**Comment by mraleph** [comment]
That's how floating point works. See https://floating-point-gui.de/ for more details.
