### ISSUE TITLE
[CP][beta channel] Add default language version 2.7 in 'dart pub get'

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#44176]
**commit(s) to merge**: 4b3840d01ddfed57374b872927a03921077614b0

**merge instructions**: clean merge

**What is the issue**: Packages without lower-bound SDK constraint are broken.

**What is the fix**: Adds default language version 2.7 when there is no lower-bound SDK constraint in dependencies.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44013#issuecomment-726166990

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
I'm marking this approved as this is part of Beta release blocker 
@pcsosinski

**Comment by athomas** [comment]
Merged to beta in 6fee8e27b8206acd82cd7ed6204941916a2568e5  (2.12.0-29.7.beta).
