### ISSUE TITLE
[analyzer] Spurious error about UNDEFINED_CLASS

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#44179]
The analyzer reports for a `typedef F<T> = ;` that the empty identifier is an undefined class.

The reason may be that the parser inserts an empty synthetic identifier between `=` and `;` in order to recover. But it should be detected that this identifier is synthetic, and hence the UNDEFINED_CLASS error should not be emitted.

The test `test_missingGenericFunction` in `GenericTypeAliasDriverResolutionTest` was adjusted to expect this behavior by adding

```dart
      error(CompileTimeErrorCode.UNDEFINED_CLASS, 15, 0),
```

and this line should be removed again when the spurious error is no longer reported.

**Comment by srawlins** [comment]
We now just report, "Expected a type name." 🎉
