### ISSUE TITLE
[vm] TARGET_ARCH_IS_32_BIT and TARGET_ARCH_IS_64_BIT can be true at the same time

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44177]
Both `TARGET_ARCH_IS_32_BIT` and `TARGET_ARCH_IS_64_BIT` can be defined in `runtime/platform/globals.h` at the same time.

https://github.com/dart-lang/sdk/blob/c209f1c1b82ed9f5fe39ee23f2586d2793c7528a/runtime/platform/globals.h#L331-L337

https://github.com/dart-lang/sdk/blob/c209f1c1b82ed9f5fe39ee23f2586d2793c7528a/runtime/platform/globals.h#L377-L381

`runtime/vm/compiler/runtime_api.h` expects only one of them to be set:

https://github.com/dart-lang/sdk/blob/c209f1c1b82ed9f5fe39ee23f2586d2793c7528a/runtime/vm/compiler/runtime_api.h#L277-L287

Second set of defines was introduced in https://dart-review.googlesource.com/c/sdk/+/105500.

@liamappelbe was having both defined intentional?

If not, I can clean it up.

**Comment by liamappelbe** [comment]
Nope, not intentional. For simarmX64, only `TARGET_ARCH_IS_32_BIT` should be set. Looks like we need to move `|| defined(IS_SIMARM_X64)` to line 331. These macros are a mess. Definitely could use a clean up. Thanks.
