### ISSUE TITLE
Measure impact of embedding pub into dartdev/dart CLI

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#44170]
If we are having a big overhead, we might be able to embed only the CLI options, and open pub as a sub-process if the command was `dart pub`.

**Comment by sigurdm** [comment]
With embedding (master + https://dart-review.googlesource.com/c/sdk/+/171284/4):
```
$ /usr/bin/time -p out/ReleaseX64/dart-sdk/bin/dart --help > /dev/null
real 0.20
user 0.22
sys 0.09
```
Before embedding: (git co cd970af91ad3635637799ad1e5644c6d55ad5208^)
```
/usr/bin/time -p out/ReleaseX64/dart-sdk/bin/dart --help > /dev/null
real 0.21
user 0.21
sys 0.10
```

Both are after a few runs.

It seems the pub embedding made no big difference.

**Comment by jonasfj** [comment]
cc @bkonyi
