### ISSUE TITLE
Migration tool: "Add hint" button behaviors should update immediately after clicking

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44172]
Pressing the `Add /*!*/ hint` and `Add /*?*/ hint` buttons in sequence results in both hints being added, e.g.:
```dart
final String/*!*//*?*/ title;
```
It would be better if after the first button press:
- The `Add /*!*/ hint` button changes to a `Remove /*!*/ hint` button
- The `Add /*?*/ hint` button behavior changes so that it transforms the hint from `/*!*/` to `/*?*/`

**Comment by kwalrath** [comment]
This would greatly help usability! I've accidentally added two `/*!*/` markers several times, and it was annoying. I tried to warn about this in the doc, but it'd be better to fix the tool.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
