### ISSUE TITLE
[windows][FFI] ffi call by pointer fail on active call function

### ISSUE THREAD

**Issue by herehere** [dart-lang/sdk#44187]
Dart SDK Version : Dart SDK version: 2.10.0-107.0.dev (dev) (Wed Sep 9 05:37:05 2020 -0700) on "windows_x64"
Using Windows
dart:ffi

As no response for the #44113  , I create a new request here.

here is the code of native:

        #define LIST_LENGTH 5
	static int iList[LIST_LENGTH] = { 100, 101, 102, 103, 104 };

	int GetArray(int* pArr, int* length){
		if (pArr==nullptr){
			return false;
		}
		pArr = iList;
		*length = LIST_LENGTH;
		return true;
	}

	int GetpArray(int** pArr, int* length){
		if (pArr == nullptr){
			return false;
		}
		*pArr = iList;
		*length = LIST_LENGTH;
		return true;
	}

	int* GetArrayReturn(int* re, int* length){
		*length = LIST_LENGTH;
		*re = true;
		return iList;
	}

and the test code of dart:

    typedef cffi_GetArray = ffi.Uint32 Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
    typedef dffi_GetArray = int Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
    dffi_GetArray gGetArrayFunc;
    dffi_GetArray gGetpArrayFunc;

    typedef cffi_GetArrayReturn = Pointer<ffi.Uint32> Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
    typedef dffi_GetArrayReturn = Pointer<ffi.Uint32> Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
    dffi_GetArrayReturn gGetArrayReturnFunc;

    gGetArrayFunc = myDylib.lookupFunction<cffi_GetArray, dffi_GetArray>('GetArray');
    gGetpArrayFunc = myDylib.lookupFunction<cffi_GetArray, dffi_GetArray>('GetpArray');
    gGetArrayReturnFunc = myDylib.lookupFunction<cffi_GetArrayReturn, dffi_GetArrayReturn>('GetArrayReturn');

      Pointer<ffi.Uint32> getArray = allocate();
      Pointer<ffi.Uint32> getArrayLeng = allocate();

      getArray.value = 0;
      getArrayLeng.value = 0;
      var re = gGetArrayFunc(getArray, getArrayLeng);
      print("\n ($re)getArray(${getArrayLeng.value})[${getArray[0]}, ${getArray[1]}, ${getArray[2]}, ${getArray[3]}, ${getArray[4]}]");

      free(getArray);
      free(getArrayLeng);

      Pointer<ffi.Uint32> getpArray = allocate();
      Pointer<ffi.Uint32> getpArrayLeng = allocate();

      getpArray.value = 0;
      getpArrayLeng.value = 0;
      re = gGetpArrayFunc(getpArray, getpArrayLeng);
      print("\n ($re)getpArray(${getpArrayLeng.value})[${getpArray[0]}, ${getpArray[1]}, ${getpArray[2]}, ${getpArray[3]}, ${getpArray[4]}]");

      free(getpArray);
      free(getpArrayLeng);

      Pointer<ffi.Uint32> getpArrayReturnState = allocate();
      Pointer<ffi.Uint32> getpArrayReturnLeng = allocate();

      getpArrayReturnState.value = 0;
      getpArrayReturnLeng.value = 0;
      final Pointer<ffi.Uint32> getpArrayReturn = gGetArrayReturnFunc(getpArrayReturnState, getpArrayReturnLeng);
      print("\n (${getpArrayReturnState.value})getArrayReturn(${getpArrayLeng.value})[${getpArrayReturn[0]}, ${getpArrayReturn[1]}, ${getpArrayReturn[2]}, ${getpArrayReturn[3]}, ${getpArrayReturn[4]}]");

      free(getpArrayReturnState);
      free(getpArrayReturnLeng);

and i got the output:

    flutter:
     (1)getArray(5)[0, 0, 889060994, 2147489778, 3487823424]
    flutter:
     (1)getpArray(5)[871809024, 32760, 886570680, 2147495410, 3486704128]
    flutter:
     (1)getArrayReturn(5)[100, 101, 102, 103, 104]

so currently i just can use return value to get the list from native, is there something wrong?

**Comment by mraleph** [comment]
You code is wrong. Similar to another issue you have filed your have misaligned signatures, e.g. if you have `int** pArr` you need `Pointer<Pointer<Int32>> pArr`. And if you store `*pArr = iList` then on the Dart side you need `pArr.value` to get `Pointer<Int32> arr` from which you can then get elements.

**Comment by herehere** [comment]
I change gGetpArrayFunc code like this work good

    Pointer<Pointer<ffi.Int32>> getpArrayList = allocate();
    Pointer<ffi.Int32> getpArrayLeng = allocate();

    getpArrayLeng.value = 0;
    re = gGetpArrayFunc(getpArrayList, getpArrayLeng);
    final Pointer<ffi.Int32> getpArray = getpArrayList.value;
    print("\n ($re)getpArray(${getpArrayLeng.value})[${getpArray[0]}, ${getpArray[1]}, ${getpArray[2]}, ${getpArray[3]}, ${getpArray[4]}]");

, but why gGetArrayFunc can't work?

anyway I got right way to retrieve array from native, thanks for the reply!

**Comment by mraleph** [comment]
> , but why gGetArrayFunc can't work?

Because it just updates the pointer `pArr`, not what it points to. It's the same as writing in Dart

```dart
void foo(x) {
  x = 10;
}

var y = 0;
foo(y);
// y is still 0 here not 10
```

**Comment by herehere** [comment]
I have last question for it:
why getpArrayReturn can work? return value is difference for the parameters?

**Comment by mraleph** [comment]
Using the same Dart analogy:

```dart
void foo(x) {
  x = 10;
}

var y = 0;
foo(y);
// y is still 0 here not 10
```

compare with:

```dart
int foo() {
  return 10;
}

var y = foo();
// y is 10 here.
```

Do you understand why the second version results in `y` being `10` and the first does not? The same happens in you C++ code.

**Comment by herehere** [comment]
Oh, I got the point, the ffi.Pointer<T> is not the pointer as c++, it's the value object has pointer property. So the right mapping for c++ pointer is ffi.Pointer<ffi.Pointer<T>>. Thanks for your reply again.

**Comment by mraleph** [comment]
> So the right mapping for c++ pointer is ffi.Pointer<ffi.Pointer>. 

No, that's not what I say. `Pointer<X>` is `X*` and `Pointer<Pointer<X>>` corresponds to `X**` in C++. 

Maybe you are a bit confused with how for example references work in C++, e.g. if you do 

```cpp
// C++
void foo(int& x) {
  x = 10;
}

int y = 0;
foo(y);
// y is actually 10 here.
```

but

```cpp
// C++
void foo(int* x) {
  *x = 10; // need * to update the value through the pointer
}

int y = 0;
foo(y);
// y is actually 10 here.
```
