### ISSUE TITLE
[CP][beta channel] Changing sdk constraint doesn't affect analysis

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44184]
**commit(s) to merge**: b16c6a82921b7268db8bf8837d92b806e8059a82

**merge instructions**: clean merge onto 2.12.0-29.0.dev +https://github.com/dart-lang/sdk/issues/44182 + https://github.com/dart-lang/sdk/issues/44183

**What is the issue**: Changing sdk constraint doesn't affect analysis

**What is the fix**: https://dart-review.googlesource.com/c/sdk/+/171360

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44131

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @pcsosinski

**Comment by franklinyow** [comment]
As we have already discussed this as necessary for beta release, mark as approved

**Comment by athomas** [comment]
Merged to beta in 6fee8e27b8206acd82cd7ed6204941916a2568e5  (2.12.0-29.7.beta).
