### ISSUE TITLE
[CP][beta channel] Fail early when running `dart migrate` with too-high min SDK constraint

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44185]
**commit(s) to merge**: da029c6ef365b18c3dabeded33b344f4a0b2c4d3 , 83cf6d67dc36152abe68ef529e8c2d1575ed9610 in that order

**merge instructions**: clean merge onto 2.12.0-29.0.dev +https://github.com/dart-lang/sdk/issues/44182 + https://github.com/dart-lang/sdk/issues/44183 + https://github.com/dart-lang/sdk/issues/44184

**What is the issue**: Fail early when running `dart migrate` with too-high min SDK constraint

**What is the fix**: https://dart-review.googlesource.com/c/sdk/+/171624, https://dart-review.googlesource.com/c/sdk/+/171643

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44144

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @pcsosinski @stereotype441

**Comment by franklinyow** [comment]
As we have already discussed this as necessary for beta release, mark as approved

**Comment by athomas** [comment]
Merged to beta in 6fee8e27b8206acd82cd7ed6204941916a2568e5  (2.12.0-29.7.beta).
