### ISSUE TITLE
[CP][beta channel] Errors don't inform the user of --no-sound-null-safety

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44183]
**commit(s) to merge**: 15c35c2f8824bdc443a4ac9cb12493a5e2fda85d

**merge instructions**: clean merge onto 2.12.0-29.0.dev + https://github.com/dart-lang/sdk/issues/44182

**What is the issue**: Errors don't inform the user of --no-sound-null-safety

**What is the fix**: https://dart-review.googlesource.com/c/sdk/+/171594

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44149

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @pcsosinski

**Comment by franklinyow** [comment]
As we have already discussed this as necessary for beta release, mark as approved

**Comment by athomas** [comment]
Merged to beta in 6fee8e27b8206acd82cd7ed6204941916a2568e5  (2.12.0-29.7.beta).
