### ISSUE TITLE
[CP][beta channel] Report hint when importing legacy library into null safe library

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44182]
**commit(s) to merge**: a0227f5902ff50fee88c12c78070461f2d8007a2

**merge instructions**: clean merge onto 2.12.0-29.0.dev

**What is the issue**: Issue 44063. Report IMPORT_OF_LEGACY_LIBRARY_INTO_NULL_SAFE hint

**What is the fix**: https://dart-review.googlesource.com/c/sdk/+/170441

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44063

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @pcsosinski

**Comment by franklinyow** [comment]
As we have already discussed this as necessary for beta release, mark as approved

**Comment by athomas** [comment]
Merged to beta in 6fee8e27b8206acd82cd7ed6204941916a2568e5  (2.12.0-29.7.beta).
