### ISSUE TITLE
[Gardening] dart_api_create_lightweight_isolate_test causing failures

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#44180]
For example: https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-win-debug-x64/10533

and https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8863821357325980736/+/steps/vm_tests_shard_13/0/logs/task_stdout_stderr:_vm_tests_shard_13/0

**Comment by mkustermann** [comment]
Thanks, @bkonyi . Will take a look at it.

**Comment by dcharkes** [comment]
Test is failing on all reload bots.

**Comment by mkustermann** [comment]
@dcharkes Could you approve the failures? The JIT / reload support for isolate groups is not still in development.

**Comment by dcharkes** [comment]
I already did, pointing to this issue.

**Comment by mkustermann** [comment]
Closing this one. This is all part of https://github.com/dart-lang/sdk/issues/36097.
