### ISSUE TITLE
Migration tool could support pressing `q` to quit

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44194]
Currently `dart migrate` prints this output when run:

```
$ dart migrate
Migrating /Users/mit/tmp/today3/lib
...
Use this interactive web view to review, improve, or apply the results.
When finished with the preview, hit ctrl-c to terminate this process.
```

When the user is done, they are expected to press `ctrl-c`. Usually that keycombo is used for things that hang. It would be nice to change it to support just pressing `q` like the flutter tool:

```
$ flutter run
...
For a more detailed help message, press "h". To quit, press "q".

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
