### ISSUE TITLE
`import .. show ..` doesn't warn of non-existing identifier

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#44197]
When using `import '..' show SomeIndentifier` Dart does not appear to validate that the identifier given actually matches anything in the given import.

Example:
```dart
import 'dart:math' show MyNonExistingIdentifier;
main() => 'This is fine!';
```

I would expect Dart to at least print a warning that `MyNonExistingIdentifier` doesn't exist in `dart:math`, but the above happily executes with no errors or warnings whatsoever.
Instead I would have expected something similar to the error for importing a non-existing package:

```
src/import_not_exist.dart:4:8: Error: Not found: 'dart:math_does_not_exist'
import 'dart:math_does_not_exist' show MyDoesNotExist;
```

This creates a usability issue as the import silently failing can cause use of the missing identifier to result in some unexpected and confusing errors.

**Comment by eernstg** [comment]
This is actually working as intended, show and hide clauses are not required to specify names that are actually exported by the given library. One motivation for this behavior is that it would not be helpful to require a library to be updated if it hides an imported name, and later that declaration is removed.

However, it could be helpful to lint the case `show name` where `name` isn't exported.

**Comment by bwilkerson** [comment]
The analyzer does indeed provide a hint for this case, producing a message of the form:
```
The library 'dart:math' doesn't export a member with the shown name 'MyNonExistingIdentifier'.
```
It also contains hints for
- names in a hide combinator that are not exported,
- duplicated names in both hide and show combinators, and
- names in show combinators that are not referenced within the importing library.
