### ISSUE TITLE
Migration: better handling of list constructor invocations

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44198]
Currently when the migration tool encounters a list constructor invocation, it leaves it alone, ~~because it doesn't know how to migrate it without help from the user~~.  This leads to a bad user experience because the user sees compilation errors and doesn't know why.

~~It would be a lot nicer if the migration tool could add a TODO comment along with a link to some documentation of how list constructors should be migrated.~~

Edit: as @lrhn points out below, there actually is a reasonable thing the migration tool can do:
- Migrate `List()` to `[]`
- Migrate `List<T>()` to `<T>[]`
- Migrate `List(n)` to `List.filled(n, null)`
- Migrate `List<T>(n)` to `List<T?>.filled(n, null)`

Of course the migrations with `List.filled` result in the list element type being nullable, but that's the sort of thing they'll be fixing anyway as part of the migration process.

**Comment by lrhn** [comment]
How about migrating `List()`/`List<T>()` to `[]`/`<T>[]` and `List(n)`/`List<T>(n)` to `List.filled(n, null)`/`List<T?>.filled(n, null)`.

The latter two can be wrong when nullability of the result doesn't line up, but that problem is inherent in having a null-filled array, and something they'll have to fix one way or another.

**Comment by stereotype441** [comment]
> How about migrating `List()`/`List<T>()` to `[]`/`<T>[]` and `List(n)`/`List<T>(n)` to `List.filled(n, null)`/`List<T?>.filled(n, null)`.
> 
> The latter two can be wrong when nullability of the result doesn't line up, but that problem is inherent in having a null-filled array, and something they'll have to fix one way or another.

You're right, @lrhn.  That's a better approach.  I'll update the issue description accordingly.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
