### ISSUE TITLE
Migration tool crashes with "already migrated" error

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44193]
Sorry, I cannot get a repro for this, but I've seen this twice now:

```
Generating migration suggestions...
[---------------------------------------------------------------------------------------------------------------------------------------------------]

Compiling instrumentation information...
Bad state: Seem to be migrating code that's already migrated
#0      NullabilityMigrationImpl.finish (package:nnbd_migration/src/nullability_migration_impl.dart:204:7)
#1      NonNullableFix.finish (package:nnbd_migration/src/front_end/non_nullable_fix.dart:116:15)
#2      _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1078:29)
<asynchronous suspension>
#3      MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:670:24)
<asynchronous suspension>
#4      MigrateCommand.run (package:nnbd_migration/migration_cli.dart:183:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:249:24)
<asynchronous suspension>
#7      runDartdev (package:dartdev/dartdev.dart:112:14)
<asynchronous suspension>
#8      main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

```

@stereotype441 is there anything to go by in this stack track ?

### Version info

Dart from Flutter master:

```
mit-macbookpro4:ffi mit$ dart --version
Dart SDK version: 2.12.0-31.0.dev (dev) (Mon Nov 9 16:07:01 2020 -0800) on "macos_x64"
```

**Comment by stereotype441** [comment]
Yes, it looks like some logic got moved around the circumstance where the exception can happen is no longer guarded by the appropriate try/catch block.  I'm surprised this wasn't caught by a unit test.  I'll try to get to this today.

**Comment by mit-mit** [comment]
I think the repro steps might be something like this:

1. start migration
2. hit apply
3. fix something manually in code
4. start migration again

Does that sound possible?

**Comment by stereotype441** [comment]
> I think the repro steps might be something like this:
> 
> 1. start migration
> 2. hit apply
> 3. fix something manually in code
> 4. start migration again
> 
> Does that sound possible?

Yes, that sounds likely.

**Comment by mit-mit** [comment]
OK, that sounds pretty common, so I'm tagging this as a beta blocker, @leafpetersen fyi

**Comment by stereotype441** [comment]
Fix out for review: https://dart-review.googlesource.com/c/sdk/+/171960

**Comment by franklinyow** [comment]
@stereotype441 Can you file a [cherrypick request](https://github.com/dart-lang/sdk/issues/new?title=%5BCP%5D%5Bbeta+channel%5D%20Please%20add%20descriptive%20title%20for%20the%20pick%20here%20&labels=merge-to-beta,cherry-pick-review&body=%2A%2Acommit%28s%29+to+merge%2A%2A%3A+COMMIT-HASH%0A%0A%2A%2Amerge+instructions%2A%2A%3A+clean+merge+or+patch+CL%0A%0A%2A%2AWhat%20is%20the%20issue%2A%2A%3A+Brief+description+of+the+problem%0A%0A%2A%2AWhat%20is%20the%20fix%2A%2A%3A+Brief+description+of+the+fix%0A%0A%2A%2AWhy%20cherrypick%2A%2A%3A+Describe+the+reasons,+like+many+users+impacted,+or+serious+functional+issues,+for+example%0A%0A%2A%2ARisk%2A%2A%3A%0A%0A%2A%2ALink%20to%20original%20+issue(s)%2A%2A%3A%0A%0A%2Fcc+%40kevmoo+%40mit-mit+%40whesse+%40athomas+%40vsmenon+%40franklinyow%0A%0A--------%0AThank+you+for+filing+a+cherrypick+request%2C+please%3A%0A++%2A+fill+in+the+data+above%0A++%2A+set+a+milestone,+and+area+label+%28e.g.+area-dart2js+for+a+dart2js+fix%29,+and+%E2%80%9Dmerge-to-beta%E2%80%9D+label+%0A++%2A+attempt+to+do+the+merge+%28%60git+checkout+origin%2Fbeta%3B+git+cherry-pick+HASH%60%29+to+ensure+the+merge+instructions+are+accurate.%0A++%2A+delete+this+comment+and+examples+%3A%29%0A%0AEXAMPLE+1%3A%0A%3E+%2A%2Acommit+to+merge%2A%2A%3A+a7e511f+%28Should+match+the+hash+in+the+title.+It%27s+OK+to+have+more+than+one+commit%2C+but+please+explain.%29%0A%3E%0A%3E+%2A%2Amerge+instructions%2A%2A%3A+merges+cleanly+in+%60origin%2Fbeta%60%0A%3E%0A%3E+%2A%2Areason%2A%2A%3A+fixes+bug+with+nsm-forwarders+with+named+arguments.+Affects+customers+unit+tests+that+use+mockito.%0A%0AEXAMPLE+2%3A%0A%3E+%2A%2Acommit+to+merge%2A%2A%3A+a7e511f%0A%3E%0A%3E+%2A%2Amerge+instructions%2A%2A%3A+patch+%5BCL%2Fxyz%5D%28link%29+%28merge+had+conflicts%2C+CL+resolves+them%29.%0A%3E%0A%3E+%2A%2Areason%2A%2A%3A+fixes+bug+with+nsm-forwarders+with+named+arguments.+Affects+%3E+customers+unit+tests+that+use+mockito.) Thanks!

**Comment by stereotype441** [comment]
> @stereotype441 Can you file a [cherrypick request](https://github.com/dart-lang/sdk/issues/new?title=%5BCP%5D%5Bbeta+channel%5D%20Please%20add%20descriptive%20title%20for%20the%20pick%20here%20&labels=merge-to-beta,cherry-pick-review&body=%2A%2Acommit%28s%29+to+merge%2A%2A%3A+COMMIT-HASH%0A%0A%2A%2Amerge+instructions%2A%2A%3A+clean+merge+or+patch+CL%0A%0A%2A%2AWhat%20is%20the%20issue%2A%2A%3A+Brief+description+of+the+problem%0A%0A%2A%2AWhat%20is%20the%20fix%2A%2A%3A+Brief+description+of+the+fix%0A%0A%2A%2AWhy%20cherrypick%2A%2A%3A+Describe+the+reasons,+like+many+users+impacted,+or+serious+functional+issues,+for+example%0A%0A%2A%2ARisk%2A%2A%3A%0A%0A%2A%2ALink%20to%20original%20+issue(s)%2A%2A%3A%0A%0A%2Fcc+%40kevmoo+%40mit-mit+%40whesse+%40athomas+%40vsmenon+%40franklinyow%0A%0A--------%0AThank+you+for+filing+a+cherrypick+request%2C+please%3A%0A++%2A+fill+in+the+data+above%0A++%2A+set+a+milestone,+and+area+label+%28e.g.+area-dart2js+for+a+dart2js+fix%29,+and+%E2%80%9Dmerge-to-beta%E2%80%9D+label+%0A++%2A+attempt+to+do+the+merge+%28%60git+checkout+origin%2Fbeta%3B+git+cherry-pick+HASH%60%29+to+ensure+the+merge+instructions+are+accurate.%0A++%2A+delete+this+comment+and+examples+%3A%29%0A%0AEXAMPLE+1%3A%0A%3E+%2A%2Acommit+to+merge%2A%2A%3A+a7e511f+%28Should+match+the+hash+in+the+title.+It%27s+OK+to+have+more+than+one+commit%2C+but+please+explain.%29%0A%3E%0A%3E+%2A%2Amerge+instructions%2A%2A%3A+merges+cleanly+in+%60origin%2Fbeta%60%0A%3E%0A%3E+%2A%2Areason%2A%2A%3A+fixes+bug+with+nsm-forwarders+with+named+arguments.+Affects+customers+unit+tests+that+use+mockito.%0A%0AEXAMPLE+2%3A%0A%3E+%2A%2Acommit+to+merge%2A%2A%3A+a7e511f%0A%3E%0A%3E+%2A%2Amerge+instructions%2A%2A%3A+patch+%5BCL%2Fxyz%5D%28link%29+%28merge+had+conflicts%2C+CL+resolves+them%29.%0A%3E%0A%3E+%2A%2Areason%2A%2A%3A+fixes+bug+with+nsm-forwarders+with+named+arguments.+Affects+%3E+customers+unit+tests+that+use+mockito.) Thanks!

Ok, filed https://github.com/dart-lang/sdk/issues/44207.
