### ISSUE TITLE
dart migrate bug

### ISSUE THREAD

**Issue by rafalbednarczuk** [dart-lang/sdk#44201]
I was following [migration guide](https://kw-www-dartlang-1.firebaseapp.com/null-safety/migration-guide) with my package [curved_navigation_bar](https://pub.dev/packages/curved_navigation_bar). I wanted to try migration tool.

<details>
<summary>Here first run of `dart migrate`</summary>
<p>

```
Migrating /home/rafal/AndroidStudioProjects/curved_navigation_bar

See https://dart.dev/go/null-safety-migration for a migration guide.

Note: more than one project found; migrating the top-level project.

Analyzing project...
[-----------------------------------------------------------------------------|]
16 analysis issues found:
  error • The parameter 'key' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/curved_navigation_bar.dart:18:9 • (missing_default_value_for_parameter)
  error • The parameter 'items' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/curved_navigation_bar.dart:19:20 • (missing_default_value_for_parameter)
  error • The parameter 'buttonBackgroundColor' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/curved_navigation_bar.dart:22:10 • (missing_default_value_for_parameter)
  error • The parameter 'onTap' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/curved_navigation_bar.dart:24:10 • (missing_default_value_for_parameter)
  error • Non-nullable instance field '_startingPos' must be initialized at lib/curved_navigation_bar.dart:40:10 • (not_initialized_non_nullable_instance_field)
  error • Non-nullable instance field '_pos' must be initialized at lib/curved_navigation_bar.dart:42:10 • (not_initialized_non_nullable_instance_field)
  error • Non-nullable instance field '_icon' must be initialized at lib/curved_navigation_bar.dart:44:10 • (not_initialized_non_nullable_instance_field)
  error • Non-nullable instance field '_animationController' must be initialized at lib/curved_navigation_bar.dart:45:23 • (not_initialized_non_nullable_instance_field)
  error • Non-nullable instance field '_length' must be initialized at lib/curved_navigation_bar.dart:46:7 • (not_initialized_non_nullable_instance_field)
  error • The parameter 'onTap' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/src/nav_button.dart:10:19 • (missing_default_value_for_parameter)
  error • The parameter 'position' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/src/nav_button.dart:10:31 • (missing_default_value_for_parameter)
  error • The parameter 'length' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/src/nav_button.dart:10:46 • (missing_default_value_for_parameter)
  error • The parameter 'index' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/src/nav_button.dart:10:59 • (missing_default_value_for_parameter)
  error • The parameter 'child' can't have a value of 'null' because of its type, and no non-null default value is provided at lib/src/nav_button.dart:10:71 • (missing_default_value_for_parameter)
  error • Non-nullable instance field 's' must be initialized at lib/src/nav_custom_painter.dart:9:3 • (not_initialized_non_nullable_instance_field)
  error • Non-nullable instance field 'loc' must be initialized at lib/src/nav_custom_painter.dart:9:3 • (not_initialized_non_nullable_instance_field)

The migration tool didn't start, due to analysis errors.

The following steps might fix your problem:
1. Set the lower SDK constraint (in pubspec.yaml) to a version before 2.12.
2. Run `dart pub get`.
3. Try running `dart migrate` again.
```

</p>
</details>  

I expected migration suggestions with an UI as described in the guide.

I decided to fix the errors by myself.
<details>
<summary>Here is the run of `dart migrate` after fixing errors</summary>
<p>

```
Migrating /home/rafal/AndroidStudioProjects/curved_navigation_bar

See https://dart.dev/go/null-safety-migration for a migration guide.

Note: more than one project found; migrating the top-level project.

Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|]No analysis issues found.

Generating migration suggestions...
[-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]

Compiling instrumentation information...
Bad state: Seem to be migrating code that's already migrated
#0      NullabilityMigrationImpl.finish (package:nnbd_migration/src/nullability_migration_impl.dart:204:7)
#1      NonNullableFix.finish (package:nnbd_migration/src/front_end/non_nullable_fix.dart:108:15)
#2      _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1109:29)
<asynchronous suspension>
#3      MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:674:24)
<asynchronous suspension>
#4      MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:249:24)
<asynchronous suspension>
#7      runDartdev (package:dartdev/dartdev.dart:112:14)
<asynchronous suspension>
#8      main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

```

</p>
</details>  

At the end `dart migrate` didn't help me at all. Errors given by `dart migrate` were the same as provided by `dart analysis` so I had them in my IDE anyway.

```
Dart SDK version: 2.12.0-37.0.dev (dev) (Thu Nov 12 14:03:34 2020 -0800) on "linux_x64"
```

**Comment by mit-mit** [comment]
This resolved in https://github.com/dart-lang/sdk/commit/cf4d300c0bfd0eba3df5979f5c242d212b1f47a8

Can you try to upgrade to the most recent Flutter dev-channel release (`flutter channel dev; flutter upgrade`) or the latest Dart beta release.

I'm going to close this as believed resolved. If you can repro in any of those builds above, let is know and we'll reactivate.

**Comment by RobertBrunhage** [comment]
@mit-mit I tried to do it in a personal package that I had and get the same behavior on Flutter version `1.24.0.10.2.pre` (dev branch).

I have the following in my pubspec.yaml

```
environment:
  sdk: ">=2.12.0-0 <3.0.0"
```

```
Analyzing project...
[---------------------------------------------------------------------------------------------------------------------------------------------]4 analysis issues found:
  error • The parameter 'items' can't have a value of 'null' because of its type, and no non-null default value is provided at lib\lexo_rank.dart:10:44 • (missing_default_value_for_parameter)
  error • The parameter 'firstRank' can't have a value of 'null' because of its type, and no non-null default value is provided at lib\lexo_rank.dart:23:43 • (missing_default_value_for_parameter)
  error • The parameter 'secondRank' can't have a value of 'null' because of its type, and no non-null default value is provided at lib\lexo_rank.dart:23:71 • (missing_default_value_for_parameter)
  error • The parameter 'items' can't have a value of 'null' because of its type, and no non-null default value is provided at lib\lexo_rank.dart:62:56 • (missing_default_value_for_parameter)

The migration tool didn't start, due to analysis errors.

The following steps might fix your problem:
1. Set the lower SDK constraint (in pubspec.yaml) to a version before 2.12.
2. Run `dart pub get`.
3. Try running `dart migrate` again.

More information: https://dart.dev/go/null-safety-migration
```

**Comment by mit-mit** [comment]
Flutter master is unfortunately still on an old build (76.0.dev is 12 days old). A new roll should be here soon.

**Comment by mit-mit** [comment]
Actually @RobertBrunhage, Flutter master rolled over the weekend, so if you upgrade to latest master you should have Dart 120.0.dev:

```
$ dart --version
Dart SDK version: 2.12.0-120.0.dev (dev) (Fri Dec 4 22:54:14 2020 -0800) on "mac
```

**Comment by RobertBrunhage** [comment]
Thanks for the info @mit-mit!

I change the sdk to 2.11 and then `Dart migrate` worked. Does it need to have the latest 2.12 to actually work?

**Comment by mit-mit** [comment]
We've made a lot of fixes over the past few weeks, so I would recommend using a recent build. We'll have an updated 2.12 beta build in the next 1-2 weeks.

**Comment by je-west** [comment]
Good Morning,
I present the same problem, I have not been able to migrate my app, I am in the beta channel and my version in the pubspec.yaml is the sdk: "> = 2.12.0 <3.0.0", any idea how to solve this problem.

Thanks a lot

**Comment by craigomac** [comment]
> I changed the sdk to 2.11 and then `dart migrate` worked.

This is what also worked for me. It looks like the migrator wants to see that you're not yet on 2.12, otherwise it considers that your code should already be null-safe.

**Comment by shantanugodbole** [comment]
2.11 is not available on the stable branch, do I need to use dev or beta branch sdk?

**Comment by mit-mit** [comment]
I recommend using 2.12 stable to perform the migration.

Do not change your SDK constraint to `>=2.12.0` in the pubspec manually; the migration tool will take care of that during the migration.

**Comment by shantanugodbole** [comment]
should I keep it >=2.0.0 itself?

**Comment by mit-mit** [comment]
Yes, you should leave your lower constraint to whatever it is currently (prior to null safety). The migration tool will update that to >= 2.12 during the migration.

**Comment by jnknewaj** [comment]
Running it from Flutter stable channel, version : Flutter 2.0.1 • channel stable, dart : 2.12.0 (stable) [sdk: ">=2.12.0 <3.0.0"]

Got the following error : 

The migration tool didn't start, due to analysis errors.

The following steps might fix your problem:
1. Set the lower SDK constraint (in pubspec.yaml) to a version before 2.12.
2. Run `dart pub get`.
3. Try running `dart migrate` again.

More information: https://dart.dev/go/null-safety-migration.

If change dart version to >=2.12 <3.0.0 manually, **flutter pub get** gives the following error : 
Invalid version constraint: Expected version number after ">=" in ">=2.12 <3.0.0", got "2.12 <3.0.0".

Migration tool! Its a total mess up.

**Comment by shantanugodbole** [comment]
@mit-mit's response helped me out. Make sure your project has no errors, and don't manually set the `sdk >= 2.12`, dart migrate does that for you. Also make sure all your dependencies have been upgraded to their null-safe version

**Comment by Manasmd** [comment]
@shantanugodbole Thanks!
keeping the version to how it was and doing `dart migrate`works

**Comment by AAverin** [comment]
Running on `Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"` I get the same issue.
Lots of analysis issues that I expected to be fixed automatically, like setting `required` on fields and so on.
I am on latest stable Flutter/Dart at the moment.

**Comment by AAverin** [comment]
Ok, it seems that having 
```
environment:
  sdk: ">=2.10.0 <3.0.0"
```
with sdk < 2.12 is critically important for any migration to work.

**Comment by JrmyDev** [comment]
> Running on `Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"` I get the same issue.
> Lots of analysis issues that I expected to be fixed automatically, like setting `required` on fields and so on.
> I am on latest stable Flutter/Dart at the moment.

Same problem

**Comment by madara134** [comment]
same problem

**Comment by mit-mit** [comment]
If anyone is having issues, please file a *new* issues that has detailed information (repro steps, SDK version, code, etc.)

**Comment by jinliyuelong** [comment]
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (5 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

dart migrate error  as below

dart migrate  
Migrating /Users/liyanjun43/work/02jingyitruck/02code/02flutter/mrd_flutter_framworks

See https://dart.dev/go/null-safety-migration for a migration guide.

Note: more than one project found; migrating the top-level project.

Analyzing project...
[----------------------------------------------------------------------------------------------|]
331 analysis issues found:
  error • The parameter 'key' can't have a value of 'null' beca
  ……
  error • The argument type 'Widget Function(BuildContext, Widget)' can't be assigned to the parameter type 'Widget Function(BuildContext, Widget?)' at lib/widget/widget_expansion_tile.dart:594:7 • (argument_type_not_assignable)

The migration tool didn't start, due to analysis errors.

The following steps might fix your problem:
1. Run `dart pub get`.
2. Try running `dart migrate` again.

**Comment by mit-mit** [comment]
Please file **a new issue**. This issue is a historical, closed issue.
