### ISSUE TITLE
[CP][beta channel] Cherry pick fix for migration tool crash when code is already migrated

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44207]
**commit(s) to merge**: cf4d300c0bfd0eba3df5979f5c242d212b1f47a8

**merge instructions**: The commit does not cherry-pick cleanly.  I've resolved the merge conflicts and uploaded a CL based on the `beta` branch here: https://dart-review.googlesource.com/c/sdk/+/172064.

**What is the issue**: If the user runs `dart migrate` on an already-migrated package, they see a stacktrace.

**What is the fix**: Leverage logic for detecting already-migrated code that was developed for https://github.com/dart-lang/sdk/issues/44144; if code is already migrated, and there are no errors, output a friendly message indicating there is nothing to be done.

**Why cherrypick**: @mit-mit tagged the issue as a beta-blocker (https://github.com/dart-lang/sdk/issues/44193#issuecomment-726748091)

**Risk**: Some small risk due to merge conflicts in the cherry-pick, mitigated by manually running all nnbd_migration unit tests and manually testing the fixed behavior after resolving conflicts.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44193

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
@leafpetersen @pcsosinski @mit-mit 
I'm marking this as approved because the original was marked as beta blocker

**Comment by mit-mit** [comment]
When picking this, please include these two string changes:

https://github.com/dart-lang/sdk/commit/0258778e3b20d1f9b2c656b0793322d3c9fa8178
https://github.com/dart-lang/sdk/commit/e205acb506cca15228da56b26693e3339a22058a

**Comment by athomas** [comment]
Merged to beta in 09481aa6ca60a12a5885db108aa5152cecb73fb1 (2.12.0-29.10.beta).
