### ISSUE TITLE
alternatives to upgrade dart - macOS Big Sur incompatibility 

### ISSUE THREAD

**Issue by CavalcanteLeo** [dart-lang/sdk#44203]
I cannot upgrade dart with homebrew on my mac anymore until they fix it (macOS 11.0.1 Big Sur)
https://github.com/Homebrew/brew/issues/7857

Is there a way to upgrade dart without brew?

<img width="716" alt="Captura de Tela 2020-11-13 às 15 18 50" src="https://user-images.githubusercontent.com/1735944/99106789-9135ba80-25c3-11eb-8fb2-36c18fde6037.png">

Also they say we need to figure it out by ourself:
https://github.com/Homebrew/brew/issues/8797

> Sorry folks, we're not here to provide support for Big Sur. You'll have to figure this out yourself until we officially support it.

And since the official release of Big Sur was yesterday, many user may be affected. I'm facing this issue since Big Sur beta 3. I thought with the official release it might be fixed, I removed the beta from my mac and installed Big Sur from Apple Store, but still

**Comment by kaiwoods** [comment]
Are you using CLT for latest Xcode? The error "Your CLT does not support macOS 11.0." makes me think not, I'd suggest trying Command Line Tools for Xcode 12.2 [from here](https://developer.apple.com/download/more/) - alternatively, there's CLT for Xcode 12.3 beta that might work too (from the same location).

**Comment by CavalcanteLeo** [comment]
i will try Command Line Tools for Xcode 12.3 beta

**Comment by CavalcanteLeo** [comment]
worked on 12.3 beta
