### ISSUE TITLE
Local variables disappear from IntelliJ debugger

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44206]
Commit c209f1c1b82ed9f5fe39ee23f2586d2793c7528a seems to have broken the IntelliJ debugger's display of local variables when debugging with the VM.

Steps to reproduce:
- Check out the Dart SDK as of c209f1c1b82ed9f5fe39ee23f2586d2793c7528a.  Open up a project in IntelliJ containing `pkg/nnbd_migration`.
- Place a breakpoint on line 382 of `pkg/nnbd_migration/lib/src/fix_builder.dart` (I've seen the failure at locations in various different files, so I don't think there's anything special about this line; I'm just including it for concreteness)
- Execute `pkg/nnbd_migration/test/fix_builder_test.dart` in the IntelliJ debugger.

Expected result: when the breakpoint is hit, local variables should be seen.

Observed result: local variables show up for a second or so, and then disappear and don't return.

I've confirmed that going back to the previous commit (44e680ac539509222c3ac64c96d3054d0b569d95) works around the problem.

**Comment by stereotype441** [comment]
@bkonyi @cskau-g FYI

**Comment by cskau-g** [comment]
I'm not an IntelliJ user myself, so I'm not familiar with how the described case is supposed to work.
But from how you describe the local variables showing up for a brief moment, it sounds like the VM Service _is_ serving them, but something then happens on the client (IntelliJ?) side, which doesn't show them correctly.

c209f1c only affects the stack trace, so I'm guessing something about the new traces makes IntelliJ fall over.

Does anyone know who maintains the IntelliJ code for this?

**Comment by stereotype441** [comment]
> I'm not an IntelliJ user myself, so I'm not familiar with how the described case is supposed to work.
> But from how you describe the local variables showing up for a brief moment, it sounds like the VM Service _is_ serving them, but something then happens on the client (IntelliJ?) side, which doesn't show them correctly.
> 
> [c209f1c](https://github.com/dart-lang/sdk/commit/c209f1c1b82ed9f5fe39ee23f2586d2793c7528a) only affects the stack trace, so I'm guessing something about the new traces makes IntelliJ fall over.
> 
> Does anyone know who maintains the IntelliJ code for this?

@jwren I believe

**Comment by cskau-g** [comment]
Alright, I skimmed through some of the [Dart plugin code](https://github.com/JetBrains/intellij-plugins/blob/79e8b970bc99e303e6afc4ba37fd224c489e1a37/Dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/VmServiceWrapper.java) and had another look at the triggering CL.
I didn't notice anything terribly obvious with the way the plugin is handling the Service Protocol output, but I did notice one thing that might cause it to behave differently.
Before, we used to do un-inlining of frames for inlined code, which ended up in the `AsyncCausal` stack, which I believe is what the plugin uses.
So my current guess is that the frames don't line up with what the plugin expects, which makes it think it has no variables.

I've got a CL to do the un-inlining again, which I've confirmed addresses the issue for this case.

But it is a bit suspicious to me that the plugin is able to correctly show the variables, only to then hide them - someone might want to look into that separately.

**Comment by cskau-g** [comment]
Stack fix has landed so I'll close this issue here.
Any potential work on the plugin should probably be tracked separately.

**Comment by devoncarew** [comment]
@cskau-g - I was seeing this when debugging a Flutter app as well. They use separate (but similar) debuggers.

I don't have context for what this change did but am happy to talk to see if there are changes that IDE clients should make here.

Is this commit (https://github.com/dart-lang/sdk/commit/75a5ba9a21947e91e8771f160462497543d67dfc) scheduled for a cherry to beta? If this was picked up by the dart 2.12 beta (2.12.0-29.10.beta ?), we'll want to cherry pick the fix into it for the next beta release. cc @a-siva

**Comment by a-siva** [comment]
> Stack fix has landed so I'll close this issue here.
> Any potential work on the plugin should probably be tracked separately.

Can you add a link to the CL that fixed the stack trace here.
Is there an issue tracking the work needed in the plugin ?

**Comment by a-siva** [comment]
> @cskau-g - I was seeing this when debugging a Flutter app as well. They use separate (but similar) debuggers.
> 
> I don't have context for what this change did but am happy to talk to see if there are changes that IDE clients should make here.
> 
> Is this commit ([75a5ba9](https://github.com/dart-lang/sdk/commit/75a5ba9a21947e91e8771f160462497543d67dfc)) scheduled for a cherry to beta? If this was picked up by the dart 2.12 beta (2.12.0-29.10.beta ?), we'll want to cherry pick the fix into it for the next beta release. cc @a-siva

Agree it needs to be in the cherry pick list, can you confirm if there are any additional changes needed elsewhere for this.

**Comment by devoncarew** [comment]
> Is there an issue tracking the work needed in the plugin ?

I'm not certain from the info here that there is work to do. If we are consuming the data incorrectly I'm happy to organize fixes to the various tools.

**Comment by devoncarew** [comment]
I believe that tools currently use:
- `Regular` for regular frames
- `AsyncSuspensionMarker` to indicate breaks between groups of sync and async frames, or, between groups of async and async frames
- `AsyncCausal` for an async frame. For an async frame, we do not expect to get (and I don't think look for) it to contain local variables

**Comment by cskau-g** [comment]
> Is this commit ([75a5ba9](https://github.com/dart-lang/sdk/commit/75a5ba9a21947e91e8771f160462497543d67dfc)) scheduled for a cherry to beta? 

I have not scheduled anything, but I agree that this might be good to cherry pick, so let me know if there's anything I can do on that front.

> Can you add a link to the CL that fixed the stack trace here.

Sorry, I was referring to dart-bot posting the commit, but I realise that might not have been clear. I've added links to my comment as well.

> * `AsyncCausal` for an async frame. For an async frame, we do not expect to get (and I don't think look for) it to contain local variables

Ah, this does explain why there were no variables shown for the frames then.
Prior to the fix, all frames in `getStack`'s `asyncCausalFrames` would be `AsyncCausal`, where-as now they're `Regular` up until the first `AsyncSuspensionMarker` (after which they're `AsyncCausal`).

So if that is the case, then the tools are likely fine as is.

**Comment by devoncarew** [comment]
> I have not scheduled anything, but I agree that this might be good to cherry pick, so let me know if there's anything I can do on that front.

Thanks for the quick fix! Can you request a cherry-pick to beta (https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel)?

**Comment by a-siva** [comment]
I have created https://github.com/dart-lang/sdk/issues/44255 for the cherry pick request

**Comment by cskau-g** [comment]
Thanks, Siva!
