### ISSUE TITLE
Support worker-thread-priority

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#44209]
See https://dart-review.googlesource.com/c/sdk/+/150560

This currently works on Windows/Android/Mac/iOS/Linux, but not Fuchsia.

Flutter wants to use this flag and make sure that Fuchsia benefits as well.

**Comment by a-siva** [comment]
Consider adding a worker thread priority value to Dart_InitializeParams which is passed into Dart_Initialize.

**Comment by dnfield** [comment]
What would the error handling look like for moving this to Dart_InitializeParams?

**Comment by a-siva** [comment]
I presume you are referring to an invalid priority value being passed in, the function Dart_Initialize returns null if successful else if returns an error string. We could check the passed in priority value during this initialization. Note: the valid values seem to be different for the various OS supported.

**Comment by dnfield** [comment]
Yes - what we'll really want to know is whether the priority value was something that could actually be set or not on the thread.

On different OSes, the priority value will have to be different. And for a particular user on a particular OS, they might not have permissions to change thread priorities and it could fail for that reason.

**Comment by xster** [comment]
We should keep track of lightweight isolate thread pool priority too

**Comment by a-siva** [comment]
I presume work being done for https://github.com/dart-lang/sdk/issues/44228 would enable the embedders to set thread priorities directly in the embedder itself and this would not be required.

**Comment by dnfield** [comment]
Agreed - I think we can close this.
