### ISSUE TITLE
Allow the embedder to supply worker threads

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#44228]
When the Dart VM needs to create a worker thread, the embedder has very little control over prioritization. The VM team added a flag to set priority, but if that fails the process will crash with no option to recover.

Flutter would like to be able to either recover (and set a different priority), or just provide the thread to begin with.

@zanderso @mkustermann @chinmaygarde

Some more context at https://github.com/flutter/engine/pull/22512

**Comment by mkustermann** [comment]
@dnfield Is there any clear indication that changing thread priorities (e.g. via the `--worker-thread-priority` flag) improves UI jank?

Also be aware: If GC is down prioritised and UI is higher prioritised - it might make GC slower thereby making the application use more RAM, something many customers already have a problem with.

**Comment by dnfield** [comment]
Waiting for customer to verify. Maybe it would be good to create some benchmarks around memory usage for this.

**Comment by dnfield** [comment]
Customer feedback is indicating this may not be the cause of the jank they're seeing - I still think this would be nice to rework, but for now there does not seem to be pressing customer need. If that changes I'll update this.

**Comment by Hixie** [comment]
Mostly the idea here would just be to guide the OS into making these threads do the work between frames rather than while a frame is being computed. I think it would be fine for the GC system to be able to push back and say "look, things are getting out of hand, I need to really get on this, don't lower my priority any more".

**Comment by dnfield** [comment]
I'm not sure if we'll be able to communicate with the GC about priority - it will eventually just block the main thread if it can't do enough work though. Or, worse, crash due to OOM.

I'm also not sure if we can feasibly raise and lower the priority between frames - I somehow suspect that would actually make things worse than if we just found a good slightly lower priority to use and just stick with. Moving it up and down between frames might create more scheduling issues though I would think.

**Comment by Hixie** [comment]
Yeah I dunno how much overhead there is in telling the OS about priority changes. If the lag on that is a millisecond or more then that wouldn't be worth it. If it's, like, a nanosecond then that's a different matter altogether.

**Comment by maks** [comment]
I would like to present another possible use case for being able to provide worker threads for new Isolates: being able to provide a thread with a very high priority set. 

Why would you want to do this? 

Well I'm trying to use Dart (on Linux) for audio DSP applications (eg, synthezisers, audio fx processing, etc) and it seems the [recommnded way to do low latency audio output applications](http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing) is to use a high priority thread to feed the OS's audio api while trying to ensure that thread never blocks. Given its currently not possible to use FFI with async callbacks into Dart Isolates and that most cross-platform audio libs (libsoundio, jack, miniaudio) use callbacks from their own high priority "RT" thread, my thought was the next best thing could be to be able to provide a high priority thread for a single Dart Isolates group, which would then have at least 1 isolate calling a sync audio (eg ALSA) api via FFI with audio samples generated in other isolates supplied via its SendPort or FFI pointers if the sendport mechanism itself is too slow.

**Comment by dnfield** [comment]
@maks I think for your case you'd need a new api on `Isolate` that would allow setting the priority of an isolate. This bug specifically is about Dart VM embedders being able to set the priority of specific threads, which wouldn't help unless you're writing a custom Linux embedding for Dart (as opposed to using `dart` directly).

**Comment by maks** [comment]
@dnfield yes I came to the same conclusion after thinking about this some more. I was aware this was for Dart embeddings and that's what I was contemplating having to do as the target for my application is RPI, but I think that's not the right way to go and I would much rather be able to simply use a standard Dart SDK, so I'll raise a separate issue for this.

**Comment by a-siva** [comment]
Initial work https://dart-review.googlesource.com/c/sdk/+/215941

**Comment by a-siva** [comment]
Is this something we still want to pursue or can we close this issue ?
