### ISSUE TITLE
[vm] TARGET_OS_IOS and TARGET_OS_MACOS_IOS defines

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44230]
We're using defines `TARGET_OS_IOS` and `TARGET_OS_MACOS_IOS` in our code base.

The former seems to never be defined, neither in the Dart code base nor in Flutter. ~This might make these things dead code.~
The former is defined by Xcode toolchain https://github.com/dart-lang/sdk/issues/24453. Which makes these things actually not dead code.

We should go and clean these cases up, so that we are consistent in our codebase. We should be careful and test them manually in Flutter because we do not have iOS on the Dart CI.

Two most important uses:

https://github.com/dart-lang/sdk/blob/53807c1d791dbc0746233cbd2c27e6ace4e43f57/runtime/vm/cpu_arm.cc#L59-L65

https://github.com/dart-lang/sdk/blob/73160d74bc6916e66ac0bd4f624308bcd4f079f2/runtime/vm/compiler/ffi/abi.cc#L48-L62

All uses: https://github.com/dart-lang/sdk/search?q=TARGET_OS_IOS

**Comment by dcharkes** [comment]
@mkustermann did you intentionally want to use the Xcode define in `cpu_arm.cc`? Or should I go ahead and change it to `TARGET_OS_MACOS_IOS` to be dependent on our own defines. If it was intentional we should probably add a comment why we diverge there from our own defines.

**Comment by mkustermann** [comment]
@dcharkes I haven't actually introduced the usage of this define (in e82fedc34544481c2c3c330908928b5189028620 I only removed code :) ). It seems 29d6e963702fcbb0ed0d5ca67d6b5f977ac0c328 has introduced this.

**Comment by dcharkes** [comment]
cc @rmacnak-google
