### ISSUE TITLE
Referencing a top-level variable in its own initializer makes its inferred type dynamic

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#44236]
Contrived example:
```dart
final stream = Stream.fromIterable([1, 2, 3]);
// Static type of sub: dynamic
final sub = stream.listen((_) {
  sub.cancel();
});
```

When not referencing `sub` within its own initializer variable, the static type is `StreamSubscription<int>` as expected.

<img width="383" alt="Screen Shot 2020-11-17 at 9 56 04 AM" src="https://user-images.githubusercontent.com/1713967/99421304-7ad97880-28bb-11eb-9da2-d9115e57ca5d.png">

When referencing it, however, it becomes `dynamic` (and you can also see the no-implicit-dynamic errors):

<img width="664" alt="Screen Shot 2020-11-17 at 9 56 35 AM" src="https://user-images.githubusercontent.com/1713967/99463031-1dace980-28f2-11eb-8d58-9b543e9b60ee.png">

...even though the typing on the method call is correct and non-`dynamic`:

<img width="821" alt="Screen Shot 2020-11-17 at 4 29 27 PM" src="https://user-images.githubusercontent.com/1713967/99463035-1f76ad00-28f2-11eb-81ee-4d9e2ac06fed.png">

Adding typing on the left-hand-side works around the issue:
```dart
final stream = Stream.fromIterable([1, 2, 3]);
final StreamSubscription<int> sub = stream.listen((_) {
  sub.cancel();
});
```
...but what's kind of strange is that it actually prevents the issue from happening, since I don't get any implicit-cast warnings about implicitly casting from `dynamic` to the LHS type.

I was able to reproduce on all the Dart versions I tried: 2.9.3, 2.10.4, 2.12.0-33.0.dev

I see two potentially separate issues here:
- The type of the variable in this case is dynamic
- If this is expected behavior, it's unclear why it's dynamic, and it would be helpful to have a lint or something explaining to not reference the variable inside itself

---

For additional context, the real-world scenario I'm hitting it in looks more like this:
```dart
final Toolbar = connect<ToolbarState, ToolbarProps>(
  mapStateToProps: (state) => (Toolbar()..disabled = state.disabled),
)(_$Toolbar as UiFactory<ToolbarProps>);
```
...and the workaround is a little unfortunate because you have to repeat the generic parameter typing on the LHS:
```dart
final UiFactory<ToolbarProps> Toolbar = connect<ToolbarState, ToolbarProps>(
  mapStateToProps: (state) => (Toolbar()..disabled = state.disabled),
)(_$Toolbar as UiFactory<ToolbarProps>);
```

In this specific case another workaround would be to use `_$Toolbar` instead inside the initializer, but it's generated and thus is dynamic (see https://github.com/dart-lang/sdk/issues/42832#issuecomment-670276298 for more info), so you'd need yet another variable to not have to explicitly cast everywhere:
```dart
final _Toolbar = _$Toolbar as UiFactory<ToolbarProps>;

final Toolbar = connect<ToolbarState, ToolbarProps>(
  mapStateToProps: (state) => (_Toolbar()..disabled = state.disabled),
)(_Toolbar);
```

**Comment by scheglov** [comment]
This is a know limitation of the analyzer's implementation of type inference.
I tried and failed to find the existing (old) issue.

In general case this requires recursive inference, which make it an error when you actually try to use the type of a variable when you are inferring its type. So, this is an error:

```dart
var v = () {
  return v + 1;
}();
```

But this is fine:
```dart
var v = () {
  v;
  return 1;
}();
```
Currently in the analyzer we use an approximation - if we see a reference from the initializer to the variable, we make it `dynamic`.

**Comment by srawlins** [comment]
Our behavior has changed to now always report that we couldn't infer the type, due to a cycle. I believe the compilers do the same.
