### ISSUE TITLE
Migrating a running app to sound nnbd doesn't change mode

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#44233]
If I have a flutter app running in mixed mode while I'm migrating, and I land changes to get into sound mode, hot restart/reload doesn't appear to do the right thing.

On my first try, hot restart / web got stuck.

After, I added `// @dart=2.10` to the app entry file, relaunched, removed the line, and did a hot restart/reload.  On Web and iOS, the app restarts fine but silently stays in unsound mode.  I need to stop and relaunch to get sound mode.

It'd nice to either:
- switch modes
- print an error and fail, suggesting a restart (this happens when you're in sound mode and add a `// @dart=2.10` line).
- at least print a warning

Not sure if that would be in the CFE or flutter tool?

@mit-mit @johnniwinther @jonahwilliams

**Comment by johnniwinther** [comment]
cc @jensjoha

**Comment by jonahwilliams** [comment]
I think staying in unsound mode is the best we're going to do for web, given that we need to provide a specific platform dill and serve a specific prebuilt SDK.

**Comment by jensjoha** [comment]
Getting stuck isn't great, but the soundness is a setting in the options - and the options doesn't change on reload.

Can you provide example code of it getting stuck? I can certainly look into that, but I don't think that dynamically shifting to sound mode is something we're going to get.

**Comment by vsmenon** [comment]
Getting stuck only happened once.  I'll see if I can repro and file a separate bug if I can.  It may also be web specific.

I don't think we need dynamic shifting of modes.  I'm also not sure this is high priority - depends if folks commonly have the app running in debug mode while they migrate.  If they do, an error may be better than silently staying in unsound mode.

An easy repro on not changing modes:
- Open the the flutter hello app (`examples/hello_world`) - I'm on the current dev channel (`Flutter 1.24.0-10.1.pre / Dart 2.12.0 (build 2.12.0-29.7.beta)`).
- Run it in debug mode - I'm using the iOS emulator on a Mac.
- Change `main.dart` to 
```
void main() => runApp(Center(
    child: Text('Sound mode is ${[1, null] is! List<int>}',
        key: const Key('title'), textDirection: TextDirection.ltr)));
```
- Hot restart (reload won't re-render title)
- Change the `pubspec.yaml` SDK lower bound to: `>=2.12.0-0.0`
- The app should be immediately null safe (ignore tests) - hot restart.
- Will still see "Sound mode is false"
- Stop app and restart.  Will see "Sound mode is true".
- Change the `pubspec.yaml` back to the original value.  No change on hot restart.
- Add `// @dart=2.10` to `main.dart` - will see compilation error (I think this is good.)
- Stop app and restart.  Will see "Sound mode is false".

**Comment by jensjoha** [comment]
If I recall correctly there is some auto detect thing in play when starting up... When you launch first it concludes it's not sound and sets those settings; shutting down and starting up again re-does that and concludes that it is sound and sets those settings...

**Comment by mit-mit** [comment]
I'm seeing some pretty confusing behavoir around steps 5-9. Specifically this set of steps:

1.  Open the the flutter hello app (`examples/hello_world`)
1.  Change the `pubspec.yaml` SDK lower bound to: `>=2.12.0-0.0` to opt-in
1. `flutter run`
1.  Add `// @dart=2.10` to `main.dart`
1. Hit 'hot reload'

=>

```
Performing hot reload...
Reloaded 1 of 364 libraries in 213ms.

lib/main.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
//@dart=2.9
^^^^^^^^^^^
Performing hot reload...
Try again after fixing the above error(s).
```

If you quit and restart, it works as expected (runs in unsound null safety).

This is especially confusing as our docs recommend this approach (using a 2.9 language marker in the entry point) to enable unsound null safety.

Can we detect when this happens during a reload, and throw a more explicit error?

**Comment by a-siva** [comment]
Closing this issue as we are moving to sound null safety by default.
