### ISSUE TITLE
[CFE] Web eval fails on non-nullable variables

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#44235]
This issue is originally opened in webdev repo but the underlying problem is in the CFE, so moving the issue to the SDK.

(old issue: https://github.com/dart-lang/webdev/issues/1178)

I'm running a Flutter Web app on master, ported to null safety. If I step past an assignment to a non-null typed variable and try to evaluate it, I get an error.

E.g., I'm stepping past:

var choices = buildChoices(); // Returns a non-null List
On the variables window, I can see choices and drill into its contents. If I enter:
> choices
in the REPL, I get:

CompilationError: Non-nullable variable 'choices' must be assigned before it can be used.
choices
^^^^^^^
If I hover on choices (in VSCode) if doesn't do anything (I assume silently swallowing the exception). This appears to be an error triggered by the CFE. FWIW, I don't see any error (i.e., it works as expected) on Flutter mobile.

This is on Flutter / Dart version:

Flutter 1.24.0-8.0.pre.117 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8cb2665118 (14 hours ago) • 2020-11-06 16:02:19 +0800
Engine • revision 0693ee04d1
Tools • Dart 2.12.0 (build 2.12.0-21.0.dev)
I'm using VSCode - Dart/Flutter plugin 3.16.0.

**Standalone compiler repro**

See disabled tests in:
https://dart-review.googlesource.com/c/sdk/+/172689

**Comment by annagrin** [comment]
@johnniwinther is this the issue you mentioned caused by the flow analysis bug in IncrementalCompiler.compileExpression?

**Comment by johnniwinther** [comment]
Yes. I'll look into it.
