### ISSUE TITLE
consider `--set-exit-if-changed` flag

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#44242]
Useful for scripting. Consider:

```
--set-exit-if-changed              Return exit code 1 if there are any proposed changes.
```

(a la `dart format`).

/cc @bwilkerson @devoncarew

**Comment by devoncarew** [comment]
Would this return different results then `dart analyze`? `dart analyze` might fail on a broader set of analysis issues, whereas `dart fix --set-exit-if-changed` would just fail if some of those issues had associated fixes?

**Comment by pq** [comment]
Ah, right. Maybe orthogonal to `analyze` output? I was thinking specifically about a way to signal that there are changes you _could_ apply so you could run dry-mode in, for example, a pre-submit. 

It'd be good to a survey of prior art.

/fyi @InMatrix

**Comment by bwilkerson** [comment]
Given that the exit code would be set for a subset of the cases in which `dart analyze` exit code is set, how likely is it that users would want this feature? (I'd like to reduce feature creep if possible.)

Also, we need to use the exit code when running the tool in testing mode, so it would be nice if it was consistent between the two.

**Comment by pq** [comment]
Presubmit or CI is the use-case I was imagining, similar to `dartfmt`: fail if there are fixes that can be automatically applied.  Having said that, you're right, if builds are already failing on all analyzer warnings, this wouldn't be useful.

**Comment by bwilkerson** [comment]
Yeah, it's hard for me to imagine anyone wanting to stop commits when there are automatically fixable diagnostics but to allow them when there are diagnostics that can't be automatically fixed.

**Comment by pq** [comment]
Closing for now.  If there's interest, we can re-open.
