### ISSUE TITLE
[CP][beta channel] Roll pub to fix issue when IDEs debug 'pub run test'

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#44245]
**commit(s) to merge**: `4e175b2d1ab99674b0db204ac9acc89f74d4dd3b`

**What is the issue**: IDEs running a debugger on `pub run test` had problems with us using exceptions to communicate exit codes internally.

**What is the fix**: We don't use exceptions to communicate exit code, instead we just set a property.

**Why cherrypick**: This affects Dart-Code when user is running a debugger on a test case from the IDE.

**Risk**: Small, the roll of pub only includes one commit.

**Link to original  issue(s)**: https://github.com/dart-lang/pub/issues/2753

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
@pcsosinski FYI

**Comment by franklinyow** [comment]
This is a regression in the test execution user experience.

**Comment by franklinyow** [comment]
Approved but hold

**Comment by franklinyow** [comment]
No patch release before the next beta, closing
