### ISSUE TITLE
[dart2js] js-interop was broke when i try to set value for 8s member of class

### ISSUE THREAD

**Issue by Atom735** [dart-lang/sdk#44244]
i use my Dart class and dart code on React client who compiled with TypeScript. And i use dart classes for some funcs, who create msgs and send it to server.

i had some class members, and whe i try to set value for last member, dart2js throw exception. I'm tryed to rename class member. it's not work. And i tryed to set value at another line with trivial string, it's not working, too. How i can fix that problem?

```
PS D:\ARGilyazeev\github\KNC> dart2js -O4 -o lib/src/userbase/index.dart.js lib/src/userbase/index.js.dart -v
Info: Compiling file:///D:/ARGilyazeev/github/KNC/lib/src/userbase/index.js.dart (2.10.4)
Warning: Interpreting this as package URI, 'package:knc/src/userbase/index.js.dart'.
Info: Kernel load complete
Info: Resolved 1167 elements.
Info: Resolved 17 native elements used, 765 native elements dead.
Info: Performing global type inference
Info: Added 1138 elements in inferencing graph.
Info: Inferred 20372 types.
Info: Compiling methods
lib/src/userbase/index.js.dart:12:7:
Internal Error: The compiler crashed when compiling this element.
class JsUser {
      ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.10.4), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
```

```dart
@JS()
library mydart_userbase;

import 'dart:convert';
import 'dart:html';

import 'package:js/js.dart';

import 'index.dart' show passwordEncode;

@JS()
class JsUser {
  /// name (full name)
  ///
  /// Полное имя
  @JS()
  String /*?*/ name;

  /// given-name (first name)
  ///
  /// Имя
  @JS()
  String /*?*/ fname;

  /// additional-name (middle name)
  ///
  /// Отчество
  @JS()
  String /*?*/ mname;

  /// family-name (last name)
  ///
  /// Фамилия
  @JS()
  String /*?*/ lname;

  /// Почта пользователя
  @JS()
  String /*?*/ email;

  /// Номер телефона
  @JS()
  String /*?*/ phone;

  /// Пароль незашифрованный
  @JS()
  String /*?*/ pass;

  /// Символы доступа пользователя
  @JS()
  String /*?*/ access;

  /// Создаёт экземпляр из данных сообщения
  static JsUser create(String str) {
    final o = JsUser();
    if (str.isNotEmpty) {
      final map = jsonDecode(str) as Map;
      o.name = map['name'];
      o.fname = map['fname'];
      o.mname = map['mname'];
      o.lname = map['lname'];
      o.email = map['email'];
      o.phone = map['phone'];

      /// NEXT LINE SET BROKE COMPILE
      o.access = map['access'];
    }
    o.genJsonStringReg = allowInteropCaptureThis((JsUser _) {
      jsonEncode({
        'pass': passwordEncode(_.pass ?? ''),
        'name': _.name ?? '',
        'fname': _.fname ?? '',
        'mname': _.mname ?? '',
        'lname': _.lname ?? '',
        'email': _.email ?? '',
        'phone': _.phone ?? '',
      });
    });
    o.genJsonStringPass = allowInteropCaptureThis((JsUser _) {
      jsonEncode({
        'pass': passwordEncode(_.pass ?? ''),
        'email': _.email ?? '',
      });
    });

    return o;
  }

  /// Сгенерировать сообщение для регистрации в системе,
  /// поле [access] игнорируется
  external set genJsonStringReg(String Function(JsUser) f);

  /// Сгенерировать сообщение для входа в систему,
  /// используются только поля [email] и [pass]
  external set genJsonStringPass(String Function(JsUser) f);
}

@JS('JsUser')
external set _JsUser(JsUser Function([String]) f);

void main() {
  _JsUser = allowInterop(([String str]) => JsUser.create(str ?? ''));
}
```

**Comment by sigmundch** [comment]
Thanks for your question and bug report!

The sample code above needs a few tweaks:

* I believe your class needs to be annotated with `@anonymous`, to indicate that the class has no prototype associated on the JavaScript side
* I believe all your fields should actually be external getters and setters
* you may need to also declare an external constructor `external factory JsUser();` Given that you always initialize all values right after construction, you could remove the setters and add initializers instead, like in [this example](https://pub.dev/packages/js#passing-object-literals-to-javascript)

In any case, the compiler should not be crashing, but detect when the code is not adhering to the js-interop conventions and report and error message instead. Good news is that recently we've been working on that. I expect you'll start seeing those compiler messages on a future release of the Dart SDK. /cc @srujzs @rileyporter - is the example above a case we'd start reporting errors with our current changes?

**Comment by srujzs** [comment]
Agreed with all your tweaks, with a few comments on the errors side:

> I believe your class needs to be annotated with `@anonymous`, to indicate that the class has no prototype associated on the JavaScript side.

I don't think there's anything we can do to enforce this in the general case.

> I believe all your fields should actually be external getters and setters.

We couldn't report an error here since there was widespread usage of Dart fields with a JS annotation (likely that usage was trying to use external fields). We could transition all of these internally but we'd have to treat it as a breaking change.

> declare an external constructor `external factory JsUser()`

This is an interesting case that we can add an error for. Similar proposal here: https://github.com/dart-lang/sdk/issues/32929#issuecomment-416425217. I think maybe the right way to report an error is to check if an implicit constructor is used on a JS interop class, and if so, report an error indicating that they should define an external constructor/factory.

It's still strange why it crashes on a field access after multiple similar field accesses for a JS interop object that was instantiated via an implicit constructor.

**Comment by sigmundch** [comment]
Just tried it locally and it seems only the third change was necessary (adding the external constructor).

This is helping me remember that we wanted to change the default so that synthetic constructors behave as if they were external factory constructors. I think @natebosch also prefers that. We already disallow non-external explicit constructors, so we just need some special handling for the default one (see https://github.com/dart-lang/sdk/issues/38875)

**Comment by natebosch** [comment]
> Are we assuming such a constructor would always be available in JS?

It is still up to the author to write the _correct_ interface against the JS. What this proposal would do is to ensure that when the constructor is callable in Dart statically, that it will still be treated as JS and not a real Dart class.

**Comment by Atom735** [comment]
`@anonymous` annotation do nothing... Oke, at now, i know where i need to use it.

I rewrite one member of class called `access` to externals setter/getter and it now working. Thanks!

But one quastion. I think so, at Dart i can only declarate JS object type, like typescript *.d.ts?

P.S. Do we have a tools for generate typescript types for dart classes and funcs?
I was thinking, to create annotation for generate Dart code without non-annotated members and funcs from main code at server VM with funcs, which translated to js with dart2js tool and generate typescript interfaces with my dart script. I trying to use mirror, but i hadn't results, becouse i coldn't get doc comments. At next time, i tryed to use dart_analizer, and it completed. I had AST with all code, including comments and annotations. I can write dart script which can generate dart code for js from it and generate *.d.ts for typescript... But i think in my work at now, i can write all by my hand.
