### ISSUE TITLE
[CP][beta channel] VM incorrectly equates generic types with top bounds

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44253]
**commit(s) to merge**: 9711b9a331ade1c033967ac8ca665123dc58e6e1
The change merges cleanly.

**What is the issue**: VM incorrectly equates generic types with top bounds

**What is the fix**: Remove obsolete workaround when reading dynamic bound from kernel

**Why cherrypick**: The VM interprets the spec incorrectly leading to incorrect behavior and divergence from other tools like dart2js

**Risk**: Small, this change has already rolled to google3 and flutter

**Link to original issue(s)**: https://github.com/dart-lang/sdk/issues/44136

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
new bug, not regression, NNBD related
approve but hold

**Comment by franklinyow** [comment]
No release before the next beta, closing
