### ISSUE TITLE
[CP] [beta channel] Fix generic signature instantiation and type parameter canonicalization check

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44254]
commit(s) to merge: b92f6a6622bb7d708dd85030e69111c3ea0586a1
The change merges cleanly.

What is the issue: Canonicalization verifier fails on AppJIT which means we have entries that are not canonical

What is the fix: correctly finalizes and canonicalizes type parameters

Why cherrypick: Incorrect canonicalization could lead to unpredictable behavior and also results in extra objects (memory footprint).

Risk: Small, this change has already rolled to google3 and flutter

Link to original issue(s): https://github.com/dart-lang/sdk/issues/43537

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
Newly discovered bug, no external report yet
Defer decision for more evident

**Comment by franklinyow** [comment]
Mark not approved.  Re-open if more evident surface
