### ISSUE TITLE
[CP][Beta channel] Fix invisible frames in CollectAsyncLazyStackTrace()

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44255]
commit(s) to merge: c209f1c1b82ed9f5fe39ee23f2586d2793c7528a
The change merges cleanly.

What is the issue: asyncCausalFrames contains many more frames than expected

What is the fix:  Fix invisible frames in CollectAsyncLazyStackTrace()

Why cherrypick: Incorrect stack traces causes confusion when debugging

Risk: Small, this change has already rolled to google3 and flutter

Link to original issue(s): https://github.com/dart-lang/sdk/issues/44138

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
Regression.
Approve and hold

**Comment by franklinyow** [comment]
No release before the next beta, closing
