### ISSUE TITLE
Support apply-all quick-fix for non-LSP clients (Android Studio / IntelliJ)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44258]
I [recently added](https://github.com/dart-lang/sdk/commit/3bf25c6c406e06b5b446ce949181d9bd106738c3) support for fixing a specific error in a whole file.

![Nov-17-2020 16-28-53](https://user-images.githubusercontent.com/1078012/99703151-acef0400-2a8e-11eb-8862-2705d1ffa89e.gif)

This is handled in the LSP server which means IntelliJ/Android Studio do not currently get these fixes. The original server protocol's `edit.getFixes()` call does not support "lazy" fixes, so the edits (for the whole file) would need to computed up-front or the protocol (and clients) updated. I don't know which would be best (I'm not sure of the relative performance of computing the edits versus the other work). I'm also not sure if other editors work like VS Code, where fixes are fetched whenever the cursor moves (to know whether to show a lightbulb icon, and to remove any delay when trying to open the menu) - if so, that might be a considering factor too.

@devoncarew @pq @bwilkerson

**Comment by bwilkerson** [comment]
@jwren @alexander-doroshko

**Comment by pq** [comment]
This just came up yesterday in conversation.  Looks fantastic and, yes, would be great to explore how we can enjoy similar in non-LSP clients. Thanks! 👍

**Comment by alexander-doroshko** [comment]
In IntelliJ / Android Studio, we need quick fix name (`SourceChange.getMessage`) when caret moves (to show lightbulb and to show popup on Alt+Enter). And we need other stuff (`SourceChange.getMessage()` and `SourceChange.getLinkedEditGroups()`) later, only if a specific quick fix is invoked. 

Current Analysis Server protocol gives everything in one shot (`SourceChange` object returned by `AnalysisServer.edit_getFixes()`). If it's a bottleneck, especially for 'fix all' type of fixes, I'm happy to adjust our clients to work with "lazy" fixes. This may mean splitting `AnalysisServer.edit_getFixes()` in 2 methods and splitting `SourceChange` in 2 objects.

**Comment by devoncarew** [comment]
From discussions earlier, the normal way something like this would be exposed in IntelliJ is off a sub-menu from the fix for the item:

<img width="743" alt="Screen Shot 2020-11-19 at 12 40 01 PM" src="https://user-images.githubusercontent.com/1269969/99721706-756b6200-2a64-11eb-852f-cd89f103536c.png">

**Comment by alexander-doroshko** [comment]
> a sub-menu from the fix

I looked through the code and noticed that 'fix all' options currently exist only for Quick Fixes provided by Inspections. Inspections are those that are listed in Settings/Preferences -> Editor -> Inspections.

In Dart these Quick Fixes come from the Annotator and accompany errors/warnings/hints. As I understand, there are no other examples of Quick Fixes in IntelliJ that come from Annotator and provide 'fix all' functionality.

We may decide as we want - place 'Fix All' right on the first-level popup, next to a 'single' quick fix. Or we may add it to the second level where we have 'Suppress' actions.

![image](https://user-images.githubusercontent.com/4499789/99722773-3835bd00-2ac2-11eb-87dd-3b7afcbdc0e8.png)

**Comment by devoncarew** [comment]
Ah, good to know.

I'm not sure performance of calculating the fixes is a consideration, but if it is, we could do something like:

- have `edit.getFixes` (https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#request_edit.getFixes) return metadata for a fix (AnalysisErrorFixes) about whether there's a 'fix all in file' variant of the fix
- have an additional param to `edit.getFixes` which would specify whether to return just fixes, or fixes and 'fix all in file' versions of those fixes

**Comment by bwilkerson** [comment]
Is there any remaining work to be done on this?

**Comment by DanTup** [comment]
I don't know if there's anything specific for IntelliJ/Android Studio, but VS Code/LSP has been using the generic server fix-alls for a while with no issues (the LSP-specific implementation was removed in https://github.com/dart-lang/sdk/commit/8f9cdb3b2f846a146ea29d41f1c7b79e9b280c4e).

**Comment by alexander-doroshko** [comment]
What should I check or fix in the Dart plugin?
I tried multiple 'unused variable' warnings but I don't see 'fix all' suggestions (SDK 2.14.0-dev).
![image](https://user-images.githubusercontent.com/4499789/123958067-47181280-d9b5-11eb-94e3-db0d970fec49.png)

**Comment by alexander-doroshko** [comment]
Ok, I tried an example from this issue description and I do get `Remove '!'s in file` suggestion.
![image](https://user-images.githubusercontent.com/4499789/123958733-11bff480-d9b6-11eb-9060-704775bfdf83.png)

**Comment by bwilkerson** [comment]
It sounds like everything is working and that the last step is to decide when we want to remove the IntelliJ added actions (and whether we need to include additional information in the legacy protocol so that IntelliJ can produce the standard UX where these appear on a submenu).

**Comment by alexander-doroshko** [comment]
>  when we want to remove the IntelliJ added actions

Which actions do you mean? IntelliJ doesn't add own 'Fix all' actions in Dart.

> whether we need to include additional information in the legacy protocol so that IntelliJ can produce the standard UX where these appear on a submenu

If everyone is fine with having 'Fix all' actions on the top level then we don't have to change this. As long as the top-level menu is not overcrowded, I'm ok with it.

**Comment by bwilkerson** [comment]
> Which actions do you mean?

Sorry, I was confusing the "Ignore '...' for this line/file" items with the "in file" items. I believe that we have a different issue open to move the generation of the ignore action to server as well.

> As long as the top-level menu is not overcrowded, I'm ok with it.

I'm also fine with it. Again, the comment came from a confusion on my part.

Given that, I'm closing this as completed.

**Comment by alexander-doroshko** [comment]
> Given that, I'm closing this as completed.

Just curious, how many Quick Fixes (in total or in %) are also accompanied with 'Fix all in file' suggestions?

**Comment by DanTup** [comment]
I don't know if this is a particularly accurate way to count, but https://github.com/dart-lang/sdk/blob/47da8db2f67cf90e2189777794b5736ef71371d2/pkg/analysis_server/lib/src/services/correction/fix.dart there are 83 instances of `.multi` and 245 instances of `FixKind(`. If accurate, that's about a third. Some of those without  probably don't make sense to have fix-all for (for example "remove dead code" is probably something you'd probably only invoke at a specific location), though I don't know if that accounts for all of those without.
