### ISSUE TITLE
_UnmodifiableMapMixin.remove should return Object? – right?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#44264]
https://github.com/dart-lang/sdk/blob/818b66544c2363209c2a33926128b6da4990b530/sdk/lib/collection/maps.dart#L287-L290

The return signature should be `Object?` – right?

Inconsistent with other impls right now

**Comment by kevmoo** [comment]
CC @lrhn

**Comment by lrhn** [comment]
It should be `V?`.

**Comment by kevmoo** [comment]
Yeah, That 😁

**Comment by lrhn** [comment]
Let's try how changing them to `Never` works out: https://dart-review.googlesource.com/c/sdk/+/173266

**Comment by kevmoo** [comment]
Could we do the simple fix? I'd love to get this in ASAP – one of those weird corner things I'd rather not hit later!
