### ISSUE TITLE
False positive `unused_element` hint

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#44268]
With `dartanalyzer` live internally and on the currently live dartpad:

```
class _Foo {
  factory _Foo([int x]) => _Foo._();
  
  _Foo._();
}

void main() {
  _Foo(3);
}
```

--> `A value for optional parameter `x` isn't ever given.`

**Comment by bwilkerson** [comment]
@srawlins

**Comment by srawlins** [comment]
o_O Hrm... No bueno.

**Comment by srawlins** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/173420
