### ISSUE TITLE
Please follow semantic versioning for the meta package

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#44277]
A number of versions of the `meta` package have introduced new features in patch versions (e.g. 1.2.4 added `@internal`, 1.2.3 added `@Target`, 1.2.8 added `@nonVirtual`, and so on). This violates [semantic versioning](https://semver.org/spec/v2.0.0-rc.1.html):

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

As a package author, this makes using `meta` confusingly different from the rest of the package ecosystem. For future releases, can you bump the minor version when you add a new feature?

**Comment by bwilkerson** [comment]
Closing, because although the request is completely reasonable, it isn't actionable in the sense that we can do something to close it. Hopefully we have been, and will continue to be, better about following semantic versioning.
