### ISSUE TITLE
Adding a lint: Extension methods crashed when called on a dynamic object

### ISSUE THREAD

**Issue by chickenblood** [dart-lang/sdk#44270]
Happens on MacOSX / Linux and reproducible in DartPad.

Dart version: Based on Flutter 1.23.0-18.1.pre Dart SDK 2.10.4

Consider the following code:

```
class MyClass {
  void foo() => print('foo');
}

extension Bar on MyClass {
  void bar() => print('bar');
}

void main() {
  dynamic val = MyClass();
  val.foo();
  val.bar(); // crashes
}
```

This compiles fine, but crashes at runtime because the extension method bar() cannot be found. The compiler should either fail with an error, or better still valid code should be generated that invokes the method at runtime.

**Comment by dnfield** [comment]
This is by design: https://dart.dev/guides/language/extension-methods#static-types-and-dynamic

I have no idea if or how this could be turned into a runtime error - someone from the language team could better answer that.

**Comment by dnfield** [comment]
It could _probably_ at least be a lint.

**Comment by dnfield** [comment]
@leafpetersen would know the langauge question, @pq the lint

**Comment by leafpetersen** [comment]
For better or worse the contract with dynamic is that the compiler just believes that you know what you're doing.  I think this would be a fine candidate for an opt in lint though.

**Comment by pq** [comment]
Yeah.  This seems to fit in a general category of advice that recommends avoiding `dynamic` almost altogether.

@chickenblood: can you provide some context?  Why would you type `val` dynamic in practice?

**Comment by chickenblood** [comment]
I try to avoid dynamic altogether. In this case I was consuming a Flutter API that returns a dynamic type.

https://api.flutter.dev/flutter/widgets/DragTargetMove.html

I did not realize this since most of the callbacks for this class are typed <T>

I plan to file a bug on that API. However, I would still hope that the linter could help us in cases like this. It is often not apparent that an implicit conversion is taking place.

**Comment by vsmenon** [comment]
There are a couple lints around implicit dynamics.  I'm not sure they capture this case.  @chickenblood - do you have an example of where the dynamic call is coming from?  The `dynamic` here is the type parameter, so not obvious.

**Comment by chickenblood** [comment]
Sure. I provided a callback for DragTarget.onMove and in there called details.data.doThing() (doThing() being the extension method). Because details.data is dynamic, the failure occurs.

DragTarget.onAccept and DragTarget onAcceptWithDetails do not have this problem because the argument is typed.

The lint sounds like a very good idea here (as well as fixing the DragTarget API).

**Comment by devoncarew** [comment]
@franklinyow - it sounds like the resolution for this issue is for a lint request? If that's the case, I'd update the title to reflect that, and move the issue to the dart-lang/linter repo.

**Comment by franklinyow** [comment]
Issue moved to [dart-lang/linter #2379](https://github.com/dart-lang/linter/issues/2379) via [**ZenHub**](https://www.zenhub.com/)
