### ISSUE TITLE
base64Url.normalize raises FormatException: Invalid base64 data for %0A

### ISSUE THREAD

**Issue by radeksvarz** [dart-lang/sdk#44275]
Issue with dart:convert

base64Url.normalize raises FormatException: Invalid base64 data for source string having %0A in it.

While the documentation states 

> Normalization will:
>  Unescape any %-escapes.

https://api.dart.dev/stable/2.10.4/dart-convert/Base64Codec/normalize.html

**Comment by lrhn** [comment]
It probably does unescape `%0A`, then it complains because the result, a line feed character, is not allowed.

> Only allow valid characters (`A`-`Z`, `a`-`z`, `0`-`9`, `/` and `+`).

So while `%`-escapes are unescaped, the result must still be valid base64 encoded data.

**Comment by radeksvarz** [comment]
> It probably does unescape `%0A`, then it complains because the result, a line feed character, is not allowed.

You are correct. I did throughout tests and it is working as documented. 

Even though I would expect normalize to silently skip CR/LF characters as the line feed is common for base64 data (typically at col 76).
