### ISSUE TITLE
Wrong compiler null promotion warnings in `??` expressions

### ISSUE THREAD

**Issue by znjameswu** [dart-lang/sdk#44276]
## Demo code
```dart
void main() {
  fun();
}

class Base {
  int? value1;
  int? value2;
}

int? fun() {
  Base? a;
  final b = a?.value1 ?? a?.value2;
  return b;
}
```
Run `dart run`

## Expected result
No warning as suggested by the analyzer

## Actual Result
```
bin/dart.dart:13:26: Warning: Operand of null-aware operation '?.' has type 'Base' which excludes null.
 - 'Base' is from 'bin/dart.dart'.
  final b = a?.value1 ?? a?.value2;
                         ^
```

## Impact
In large projects, this absolutely spams the console when running tests. For every test file, this compiler warning will be emitted once.

## Environment
Tested on Dart 2.12.0-62.0.dev & 2.12.0-29.10.beta

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.630], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2020.1)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.51.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by johnniwinther** [comment]
@stereotype441 I looks like `a?.value1` promoted `a` to non-nullable in the rest of the `??` expression. What is the intended promotion scope and why do analyzer and CFE disagree?

**Comment by stereotype441** [comment]
@johnniwinther I ran this example through the analyzer and CFE id tests (see https://dart-review.googlesource.com/c/sdk/+/173580 if you want to reproduce), and I used the `FlowAnalysisDebug` class to figure out what was different between the two implementations.  Here's what I found.

Filtering out irrelevant calls and munging the output a bit, the analyzer is making these calls to flow analysis:
```
FlowAnalysisDebug()
variableRead(VariableGetImpl(a), VariableDeclaration(Base? a))
nullAwareAccess_rightBegin(VariableGetImpl(a), InterfaceType(Base?))
nullAwareAccess_end()
ifNullExpression_rightBegin(NullAwarePropertyGet(a?.value1), InterfaceType(int?))
  variableRead(VariableGetImpl(a), VariableDeclaration(Base? a))
  nullAwareAccess_rightBegin(VariableGetImpl(a), InterfaceType(Base?))
  nullAwareAccess_end()
ifNullExpression_end()
variableRead(VariableGetImpl(b), VariableDeclaration(final int? b))
handleExit()
finish()
```
Whereas the CFE is making these calls:
```
FlowAnalysisDebug()
variableRead(VariableGetImpl(a), VariableDeclaration(Base? a))
nullAwareAccess_rightBegin(VariableGetImpl(a), InterfaceType(Base?))
  variableRead(VariableGet(#0), VariableDeclaration(final Base? #0))
  nullAwareAccess_rightBegin(VariableGet(#0), InterfaceType(Base?))
    ifNullExpression_rightBegin(NullAwarePropertyGet(a?.value1), InterfaceType(int?))
      variableRead(VariableGetImpl(a), VariableDeclaration(Base? a))
      nullAwareAccess_rightBegin(VariableGetImpl(a{Base}), InterfaceType(Base))
        variableRead(VariableGet(#0), VariableDeclaration(final Base #0))
        nullAwareAccess_rightBegin(VariableGet(#0), InterfaceType(Base))
        ifNullExpression_end()
      nullAwareAccess_end()
    nullAwareAccess_end()
  nullAwareAccess_end()
nullAwareAccess_end()
variableRead(VariableGetImpl(b), VariableDeclaration(final int? b))
handleExit()
finish()
```
Ignoring the variables called `#0` (which I think are an artifact of CFE lowering and not relevant to this bug), the key differences I see are that the CFE:
- Mixes up calls to ifNullExpression and nullAwareAccess.  This is a known issue (https://github.com/dart-lang/sdk/issues/43725) but maybe it's contributing to the problem somehow?
- Doesn't close the first null aware access until the end of the expression.  In effect the CFE is telling flow analysis that the null shorting for the first `?.` extends all the way through to the `;`.  But it shouldn't; null shorting should terminate at the `??`.

Does that help?
