### ISSUE TITLE
run the dart fix tool through a large set of existing applications

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#44272]
We should run the dart fix tool through a large set of existing applications. Perhaps using a corpus of apps from the itsallwidgets set of apps?

**Comment by devoncarew** [comment]
@pq @bwilkerson - is there additional work / testing expected here?

**Comment by bwilkerson** [comment]
It wouldn't hurt, but there's no clear criteria for deciding when we've done enough, so it's a hard question to answer.

**Comment by pq** [comment]
I think we can close this one.  There's always more to do but we did complete a concerted first wave of testing.
