### ISSUE TITLE
[dart2js] The highest supported language version is 2.10

### ISSUE THREAD

**Issue by sgehrman** [dart-lang/sdk#44287]
I'm on the latest flutter.  This use to work on older flutter versions:

$ dart2js -o test.js test.dart
../../../../.pub-cache/hosted/pub.dartlang.org/js-0.6.3-nullsafety.3/lib/js.dart:1:1:
Error: The specified language version is too high. The highest supported language version is 2.10.

test.dart:

@JS()
library worker;

// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;
import 'package:js/js.dart';

@JS('self')
external html.DedicatedWorkerGlobalScope get self;

void main() {
  UploadWebWorker().setup();
}

class UploadWebWorker {
  void setup() {}
}

$ flutter doctor -v
[✓] Flutter (Channel dev, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/steve/google/flutter
    • Framework revision 022b333a08 (5 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/steve/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 13.0.1+9)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Linux (desktop)                       • linux         • linux-x64      • Linux
    • Web Server (web)                      • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 87.0.4280.66

! Doctor found issues in 1 category.

**Comment by jakemac53** [comment]
@sgehrman It sounds like you probably have both a `flutter` and `dart` sdk, and your `dart` sdk is older than your flutter one which was used to fetch your dependencies. So it got some dependencies which require the 2.12 sdk, but you are trying to run the app with `dart2js` from a 2.10 sdk.

I would update your dart checkout, or make sure you run `dart2js` from your flutter sdk (at `<flutter-sdk>/bin/cache/dart-sdk/bin/dart2js`).

**Comment by sgehrman** [comment]
thanks, I found that I did have another dart installed.
