### ISSUE TITLE
migrate analyzer to nullsafety

### ISSUE THREAD

**Issue by vanlooverenkoen** [dart-lang/sdk#44290]
I am upgrading my package (Kiwi) vanlooverenkoen/kiwi#51

But it seems that analyzer is not yet migrated to support nullsafety. Is there a timeline on when this could be added?

**Comment by srawlins** [comment]
Optimistically speaking, this will be completed by the end of March 2021.

**Comment by vanlooverenkoen** [comment]
Is that before or after the stable release of nullsafety? Or is that not clear yet?

**Comment by srawlins** [comment]
It could happen before or after the stable release.

**Comment by scheglov** [comment]
Version `1.0.0` was published.
