### ISSUE TITLE
Analyzer does not infer type when required type is `dynamic` 

### ISSUE THREAD

**Issue by andcea** [dart-lang/sdk#44338]
This tracker is for issues related to:
* Analyzer

```
Map<String, dynamic> map1 = Map.of({});
Map<String, String> map2 = Map.of({});
```
```
error: Missing type arguments for map literal. (implicit_dynamic_map_literal)
error: Missing type arguments for generic type 'Map<String, dynamic>'. (implicit_dynamic_type)
```
<img width="330" alt="Screenshot 2020-11-29 at 15 54 54" src="https://user-images.githubusercontent.com/2134605/100546845-5c7c6100-325b-11eb-96d3-ec807ac37cff.png">

Using `Map<String, dynamic> map1 = Map<String, dynamic>.of(<String, dynamic>{});` fixes it, but it's way too verbose;

```
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
`Dart SDK version: 2.12.0-29.10.beta (beta) (Tue Nov 17 10:50:22 2020 +0100) on "macos_x64"`

**Comment by srawlins** [comment]
Inference does not flow from expressions to declarations in the way you are expecting. In:

```dart
Map<String, dynamic>/*1*/ map1 = Map.of/*2*/({});
```

inference does not flow from `/*2*/` to `/*1*/`. Inference does, however, flow in the other direction, so:

```dart
var map1 = Map.of<String, dynamic>({});
```

will infer the type of `map1` to be a `Map<String, dynamic>`.

> Using Map<String, dynamic> map1 = Map<String, dynamic>.of(<String, dynamic>{}); fixes it, but it's way too verbose;

When you use the `implicit-dynamic: false` option, you are very much explicitly opting into more verbose code.
