### ISSUE TITLE
Expando is really slow

### ISSUE THREAD

**Issue by MarvinHannott** [dart-lang/sdk#44333]
I just did a simple benchmark on how `Expando` performs compared to `Hashmap`, and it is much, much slower.

````Dart
import 'dart:collection';

import 'package:benchmark_harness/benchmark_harness.dart';

final objs = List.generate(1000, (index) => Object());

class MapInsertBenchmark extends BenchmarkBase {
  MapInsertBenchmark() : super('MapInsertBenchmark');
  final map = HashMap<Object, dynamic>.identity();
  @override
  void run() {
    for (final obj in objs) {
      map[obj] = 42;
    }
  }
}

class ExpandoInsertBenchmark extends BenchmarkBase {
  ExpandoInsertBenchmark() : super('ExpandoInsertBenchmark');
  final expando = Expando<int>();

  @override
  void run() {
    for (final obj in objs) {
      expando[obj] = 42;
    }
  }
}

class MapReadBenchmark extends BenchmarkBase {
  MapReadBenchmark() : super('MapReadBenchmark');
  final map = HashMap<Object, dynamic>.identity();
  bool isInMap = false;
  @override
  void setup() {
    for (final obj in objs) {
      map[obj] = 42;
    }
  }

  @override
  void run() {
    for (final obj in objs) {
      isInMap = map[obj] == 42;
    }
  }
}

class ExpandoReadBenchmark extends BenchmarkBase {
  ExpandoReadBenchmark() : super('ExpandoReadtBenchmark');
  final expando = Expando<int>();
  bool objInExpando = false;

  @override
  void setup() {
    for (final obj in objs) {
      expando[obj] = 42;
    }
  }

  @override
  void run() {
    for (final obj in objs) {
      objInExpando = expando[obj] == 42;
    }
  }
}

void main() {
  ExpandoInsertBenchmark().report();
  MapInsertBenchmark().report();
  ExpandoReadBenchmark().report();
  MapReadBenchmark().report();
}
````
Results:
Expando Insert: 2716.099050203528 us
Map Insert: 118.57262271757173 us
Expando Read: 2770.045643153527 us
Map Read: 88.0883946267342 us

This was measured on a PC with an Intel i7-7700-K, Windows 10 and Dart 2.10.4.

This really goes against common intuition, as I would have expected `Expando` to be at least as fast as a `HashMap`.

**Comment by mraleph** [comment]
(Assigned Ryan just to reflect the fact that he already landed some changes to improve performance)

**Comment by rmacnak-google** [comment]
ExpandoInsertBenchmark(RunTime): 1560.6653666146647 us.
MapInsertBenchmark(RunTime): 138.7020110957004 us.
ExpandoReadtBenchmark(RunTime): 1432.4824624194703 us.
MapReadBenchmark(RunTime): 113.23619996603068 us.
->
ExpandoInsertBenchmark(RunTime): 159.12300103429072 us.
MapInsertBenchmark(RunTime): 137.99372153994756 us.
ExpandoReadtBenchmark(RunTime): 145.94257570229843 us.
MapReadBenchmark(RunTime): 109.81518695437325 us.
