### ISSUE TITLE
[TOOLING] Debugger is not showing variables when on a breakpoint.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#44344]
I've tried this on stable and master, and in Intellij (primary IDE) and VS Code with the same results. (duplicate information was removed in output for brevity) and flutter info was included just in case.
When it stops, it doesn't show the variable, even though one is there. I also had a breakpoint that was skipped over.
To illustrate, 
```dart 
myFunction() {
     final response = await http.get('something');
     final body = response.body;
🔴 final json = jsonDecode(body); // will not show me body
     return;
```
❯ flutter doctor -v

[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/thinkdigital/development/flutter_stable
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Flutter (Channel master, 1.24.0-8.0.pre.244, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 1.24.0-8.0.pre.244 at /Users/thinkdigital/fvm/versions/master
    • Framework revision 6e84a14294 (2 weeks ago), 2020-11-13 16:04:53 -0800
    • Engine revision 63a6fe3cf9
    • Dart version 2.12.0 (build 2.12.0-38.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM N975U (mobile) • R38M906TG0Z • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web)  • web-server  • web-javascript • Flutter Tools
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 86.0.4240.198
    ! Error: Think Digital’s iPhone is not connected. Xcode will continue when Think Digital’s iPhone is connected. (code -13)

• No issues found!
<img width="1136" alt="Screen Shot 2020-11-30 at 9 02 08 AM" src="https://user-images.githubusercontent.com/23037821/100640103-ddcf0480-32ea-11eb-957b-bd3204db0d60.png">

**Comment by ThinkDigitalSoftware** [comment]
After further testing, I get variables in the same project in another area. But not in certain spots

**Comment by bkonyi** [comment]
This sounds like it might be related to https://github.com/flutter/flutter/issues/66832, especially if breakpoints aren't being hit. Is it possible for you to provide a small sample with reproduction steps @ThinkDigitalSoftware?

**Comment by ThinkDigitalSoftware** [comment]
This isn't showing up as an issue currently. I haven't noticed any issues In my recent development

**Comment by bkonyi** [comment]
Okay, I'm going to close this for now then. If you run into this again, please feel free to reopen. Thanks!

**Comment by ThinkDigitalSoftware** [comment]
Thank you as well
