### ISSUE TITLE
The number of available suggestions the analysis server sends grows over time when using parts

### ISSUE THREAD

**Issue by AndriiChuzhynov** [dart-lang/sdk#44353]
Analyzer - performance
Hello, I faced with the problem that similar to [flutter-intellij/issues/4849](https://github.com/flutter/flutter-intellij/issues/4849).

After some investigation I found that problem is related with big sized responses from Analysis server to the IDE.
Initially each response of event type `completion.availableSuggestions` was ~350k lines and ~26MB.

Content of the response mostly similar relevanceTags (see attached file).
After deletion of `~/.dartServer/.analysis-driver/` number of tags dropped.
But on each autocompletion action in IDE grows by one or more tags. 

This issue related only to the classes that extend `Bloc` from bloc package. 
It's reproducible on with my project code, but I can, also, try to create example code that reproduces this behavior.

bloc version: "6.1.0"
Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
MacOS Catalina 10.15.7

[completion.availableSuggestions_event.json.zip](https://github.com/dart-lang/sdk/files/5619445/completion.availableSuggestions_event.json.zip)

**Comment by AndriiChuzhynov** [comment]
Ok, looks like it's not related to bloc. But it's related with how bloc tutorials are done. 
Some bloc tutorials contains examples with `part ''` and `part of ''` statements. 
And if files are composed as parts, this issue arises. 

Using this example https://gist.github.com/AndriiChuzhynov/3f9f47a1158d4af6d5285163db164842
And doing some work in IDE (Intelij IDEA in my case) with this files. 
After some time `completion.availableSuggestion` events becomes 3k+ lines long. 
[completion.availableSuggestions.txt](https://github.com/dart-lang/sdk/files/5624765/completion.availableSuggestions.txt)

**Comment by devoncarew** [comment]
Thanks for the report! It sounds like the number of available completions we send can grow over time based on the use of parts.

cc @bwilkerson @scheglov

**Comment by bwilkerson** [comment]
@AndriiChuzhynov Which IDE are you using? Not all IDEs use the same protocol to communicate with the analysis server, so knowing this will help us identify the cause of the problem.

**Comment by AndriiChuzhynov** [comment]
Hi @bwilkerson, I'm using Intelij Idea with Flutter (52.0.5) plugin

**Comment by bwilkerson** [comment]
Thanks! That helps.

**Comment by devoncarew** [comment]
Due to several memory related reports from IntelliJ users, I'm raising this to a P1.

**Comment by scheglov** [comment]
I can reproduce it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/177640
