### ISSUE TITLE
provide user friendly messages for 'dart test' when pub has not yet been run or when there's no package:test dep 

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#44369]
We should provide user friendly messages for 'dart test' when pub has not yet been run or when there's no package:test dep. Specifically, the way this command is implemented, we can't provide the same help until pub has been run and there's a dep on package:test - the help contents comes from package:test itself.

Previously, we'd handled several of these (more common) corner cases, and provided messages to the user to let them know how to proceed.

The use cases we'd covered can be seen in the test cases in this CL: https://dart-review.googlesource.com/c/sdk/+/161763, as well as the help text we provide when there's not a package:test dep.

@sigurdm @jonasfj

**Comment by sigurdm** [comment]
https://dart-review.googlesource.com/c/sdk/+/175060 addresses this

**Comment by devoncarew** [comment]
@sigurdm - thanks for following up w/ those CLs!

**Comment by bkonyi** [comment]
@sigurdm can this issue be closed?
