### ISSUE TITLE
IsolateSpawn benchmark is failing to run with null safety

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#44375]
We are getting a bad result from our benchmark runner when it is running the IsolateSpawn benchmark on dart-aot-null configuration.  The runner should be using the benchmark in benchmarks/IsolateSpawn/dart/, not benchmarks/IsolateSpawn/dart2/, because the target name contains '-null', so that should not be the problem.

These are the commands it claims to be running, followed by the command it runs on dart-null x64, where it also fails:

DART_CONFIGURATION=ReleaseX64 pkg/vm/tool/precompiler2 --sound-null-safety --enable-experiment=non-nullable --packages=.packages benchmarks/IsolateSpawn/dart/IsolateSpawn.dart benchmarks/IsolateSpawn/dart/IsolateSpawn.dart.bin && DART_CONFIGURATION=ReleaseX64 pkg/vm/tool/dart_precompiled_runtime2 --profile-period=10000 benchmarks/IsolateSpawn/dart/IsolateSpawn.dart.bin

on dart-null:
out/ReleaseX64/dart --profile-period=10000 --packages=.packages --sound-null-safety --enable-experiment=non-nullable benchmarks/IsolateSpawn/dart/IsolateSpawn.dart

Here is the error:
Bad result from XXX running BenchmarkRunIdentifier('dart-aot-null', 'linux-x64', '89531', 'Intel Xeon', 'IsolateSpawn'):
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:compiler
- package:front_end
- package:_fe_analyzer_shared
- package:kernel
- package:package_config
- package:js_ast
- package:dart2js_info
- package:_js_interop_checks

For solutions, see https://dart.dev/go/unsound-null-safety

@mkustermann

**Comment by mkustermann** [comment]
This is only a benchmark for which we have non-null-safety tracking already. It uses `dart2js` in it's code and therefore won't be able to run in null-safety until CFE is migrated.

Very low priority.

**Comment by franklinyow** [comment]
Remove this from Stable tracking

**Comment by whesse** [comment]
The reason I reported this is that it is filling up our error logs with multiple copies of this benchmark error, making it difficult to see any other errors occuring on benchmarks.  Could we stop running it until it is fixed?

**Comment by mkustermann** [comment]
@whesse Feel free to disable this particular (i.e. null safety) benchmark (e.g. by setting starting revision to max-int)

**Comment by parlough** [comment]
Seems this was resolved in edaaa70e31e07ce1002cd2a1a16a488d6c60bdfd which switched the benchmark to running a tool that supported null safety.
