### ISSUE TITLE
Using late in a library without null safety gives surprising error

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44379]
The `late` keyword is only available when using language version 2.12 or later. However, when moving code around, you might end up with a late keyword in a library that is using 2.11 or lower. When that happens, the error is surprising and does little to help the developer realise the `late` keyword is the issue, by providing 5 errors of which none point out the issue:

`lib/foo.dart:`
```dart
class foo {
  int i;
  late int j;

  foo({this.i = 1, this.j = 2});
}
```

=>

```
$ dart analyze lib
Analyzing lib...                       1.0s

  error • The instance member 'int' can't be accessed in an initializer at foo.dart:2:3 • (implicit_this_reference_in_initializer)
  error • int isn't a type at foo.dart:2:3 • (not_a_type)
  error • Undefined class 'late' at foo.dart:3:3 • (undefined_class)
  error • Expected to find ';' at foo.dart:3:8 • (expected_token)
  error • Variables must be declared using the keywords 'const', 'final', 'var' or a type name at foo.dart:3:12 •
```

**Comment by mit-mit** [comment]
Is this in the CFE @johnniwinther or analyzer @bwilkerson ?

**Comment by johnniwinther** [comment]
It is likely both. The scanner and parser (which are shared) special case the `late` modifier.

**Comment by johnniwinther** [comment]
@jensjoha We should probably do better recovery here; special-casing `late` in these situations.

**Comment by mit-mit** [comment]
I'm going to move this to P1; seems a bit egregious. Let me know if you disagree.

**Comment by jensjoha** [comment]
Let me know if this is not fixed to your satisfaction @mit-mit (and note that a similar thing for `required` is fixed with https://dart-review.googlesource.com/c/sdk/+/175307).

**Comment by mit-mit** [comment]
Looks much better now, thanks!
