### ISSUE TITLE
Constructors referencing deprecated fields with initializing formals do not generate hints at invocations

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44373]
This came up at https://github.com/Dart-Code/Dart-Code/issues/2966. The following code doesn't generate any warnings about the deprecated field:

```dart
final c = MyClass(deprecatedField: 'b');
//                ^^^^^^^^^^^^^^^ Expect warning here? 

class MyClass {
  MyClass({this.deprecatedField});

  @Deprecated('this member is deprecated')
  final String deprecatedField;
}
```

It seems like a warning should be generated at the call site as for all intents and purposes, it's referencing a deprecated field.

I have a CL to fix this (https://dart-review.googlesource.com/c/sdk/+/174805), though it could generate a lot of new warnings that weren't there before, so this may warrant some discussion.

@bwilkerson

**Comment by bwilkerson** [comment]
@leafpetersen @lrhn @davidmorgan In case you have thoughts about this.

**Comment by davidmorgan** [comment]
No worries from my side--we never treat deprecation warnings as breaking. Thanks.

**Comment by lrhn** [comment]
As I see it, the invocation *does not* refer to the field. The name written in the invocation is the name of a formal parameter of the constructor, and that parameter is all it refers to. The fact that that parameter is an initializing formal for a field of the same name, is an implementation detail.
It's possible for the class to remove the field and retain the constructor parameter if it wants to, so it is at least one step removed from the deprecated field. Perhaps they're not removing the field, merely making it private, but they still need to initialize it.

So, I'd say no warning here. If the class author is planning on removing the constructor parameter too, they should deprecate that as well. (We might want to figure out if there is any way we can tell them *that*: "You're deprecating a field, but not the associated initializing formal. What's up with that?" - maybe make that a warning, and the workaround is to split it into `({String name}) : name = name;` which will have to become `_name = name` anyway when the field is made private).

**Comment by DanTup** [comment]
> Perhaps they're not removing the field, merely making it private, but they still need to initialize it.

Good point - accessing the field as - er, the field - had completely slipped my mind.

I went back and checked the original issue at https://github.com/Dart-Code/Dart-Code/issues/2966 and it looks like the code example given (which fails to generate a warning based on the above) isn't actually the same as the issue described (Flutter's `showDialog` - which is a function), so I'll abort this and try to get a repro of that (since in my testing, showDialog *is* correctly reporting its deprecated fields).

> We might want to figure out if there is any way we can tell them that: "You're deprecating a field, but not the associated initializing formal. What's up with that?" - maybe make that a warning, and the workaround is to split it into `({String name}) : name = name;`

If there's value in this (though I don't know how common it is, given the example I had was misleading), I can have a go at it (w/ a fix to do the change). Let me know if you think so and I'll file a separate issue for it to avoid confusion with this one. Thanks!
