### ISSUE TITLE
Repeated initialization of final late local variable does not cause an exception

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#44372]
Spec:
```
Let D be a late and final local variable declaration named v. It is a run-time error, throwing an instance of LateInitializationError, to assign a value to v if a value has previously been assigned to v.
```

Example:
```dart
main(List<String> args) {
  late int Function() recursiveInitLocal;
  late final int local = recursiveInitLocal();

  bool doRecursiveInitLocal = true;
  recursiveInitLocal = () {
    print('Executing initializer');
    if (doRecursiveInitLocal) {
      doRecursiveInitLocal = false;
      print('Trigger recursive initialization');
      int val = local;
      print('Final local has value $val');
      print('Returning 4 from initializer');
      return 4;
    }
    print('Returning 3 from initializer');
    return 3;
  };

  int val = local;
  print('Final local has value $val');
}
```

It prints
```
Executing initializer
Trigger recursive initialization
Executing initializer
Returning 3 from initializer
Final local has value 3
Returning 4 from initializer
Final local has value 4
```

Expected behavior is to throw `LateInitializationError` exception when assigning a value after returning from the initializer for the 2nd time. The incorrect behavior happens both in the VM and in DDC, so this bug is probably present both in the VM and CFE lowering.

@leafpetersen @johnniwinther @nshahan

**Comment by johnniwinther** [comment]
Sneaky code! I'll update the late lowering to handle this.

**Comment by johnniwinther** [comment]
I've created https://dart-review.googlesource.com/c/sdk/+/174923 for the CFE late lowering used in dart2js and DDC.

**Comment by nshahan** [comment]
@alexmarkov Do you want to add a test for this pattern to the language suite since it seems it is missing? 

I don't want to regress on the web compilers if we start opting out of the CFE lowering in some cases.

**Comment by alexmarkov** [comment]
@johnniwinther Thank you for the quick fix!

@nshahan This test case was submitted in commented form in `language/nnbd/syntax/late_modifier_runtime_error_test.dart` test:

https://github.com/dart-lang/sdk/blob/3f2e5d8a90288f7d17d295e1302edd46141df689/tests/language/nnbd/syntax/late_modifier_runtime_error_test.dart#L79-L89

https://github.com/dart-lang/sdk/blob/3f2e5d8a90288f7d17d295e1302edd46141df689/tests/language/nnbd/syntax/late_modifier_runtime_error_test.dart#L109-L111

I'll uncomment it after fixing the VM.
