### ISSUE TITLE
Creating new Dart project UI has gone on Intellij

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#44387]
Trying to create a new Dart project, it won't show up. Flutter shows up but not plain `dart`!

![image](https://user-images.githubusercontent.com/1146982/101093605-cf5a4480-3599-11eb-83c6-577647271e73.png)
![image](https://user-images.githubusercontent.com/1146982/101093763-13e5e000-359a-11eb-8f89-8c11fc4bc0bb.png)

My Intellij IDEA version is `2020.3`
My Dart plugin version is `203.5981.152`

**Comment by alexander-doroshko** [comment]
@shinayser @franklinyow This issue has been fixed quite a quite ago (https://youtrack.jetbrains.com/issue/WEB-48717). Please close it here as I have no permissions. 

Dart plugin is developed by JetBrains, so the issues with Dart plugin are tracked in https://youtrack.jetbrains.com/issues/WEB?q=Subsystem:%20Dart
