### ISSUE TITLE
support data driven fixes in dart: libraries

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#44382]
Currently for the data driven fixes tool (`dart fix`), we look for a declarative file in the `lib/` directory of a package. We'd like to support data driven fixes for `dart:` libraries; they don't currently have `lib/` directories, so this will likely mean a different discovery mechanism.

**Comment by devoncarew** [comment]
@pq - I think this is done now?

**Comment by pq** [comment]
Yep.  Thanks for tidying up!
