### ISSUE TITLE
ffi callback crashes when callback returns handle

### ISSUE THREAD

**Issue by ele828** [dart-lang/sdk#44392]
I was using dart ffi native callback feature performing a sync callback from native C++ to dart and encountered a crash on Android arm64.

dart callback is something like this:
```dart
class Foo {}

Object callback() {
  return Foo();
}
```

callback is like this:
```c++
// Calling ffi callback when dart isolate has exited
// e.g. posting task to UI thread from another thread
// or yield to run on next runloop
Dart_EnterIsolate(isolate);
Dart_EnterScope();
Dart_Handle handle = callback();  // crashed
Dart_ExitScope();
Dart_ExitIsolate();
```

When the call path is from `dart` to `c++` and `c++` callback to dart synchronously (without leaving dart isolate), the code above works fine.

However, when `c++` makes a callback by yielding to next runloop, it crashes on Android ARM-64 (same code works on mac x64 though)

stacktrace:
![image](https://user-images.githubusercontent.com/8534639/101118886-00cc2200-3625-11eb-9c6e-dd34817b0f9e.png)

![image](https://user-images.githubusercontent.com/8534639/101118903-0aee2080-3625-11eb-81c5-f15f05c2b3d2.png)

* dart version: bbf711f08f7e45404

**Comment by dcharkes** [comment]
> ```
> // Calling ffi callback when dart isolate has exited
> // e.g. posting task to UI thread from another thread
> // or yield to run on next runloop
> Dart_EnterIsolate(isolate);
> Dart_EnterScope();
> Dart_Handle handle = callback();  // crashed
> Dart_ExitScope();
> Dart_ExitIsolate();
> ```

This is an interesting pattern. So far I've been recommending using `Dart_PostCObject` for asynchronous callbacks, rather than `Dart_EnterIsolate(isolate)` and then doing a synchronous callback. I will have to investigate this pattern.

Another question I have about this is, are you using this in Flutter? Or standalone Dart? In Flutter the symbol `Dart_EnterIsolate` is not exposed if I'm not mistaken. (And therefore we have dart_api_dl.h to be able to dynamically bind to dart_api symbols, but with a `_DL` suffix.)

Could upload the source code of a minimal reproduction?

**Comment by ele828** [comment]
Thanks for your reply, `Dart_PostCObject` is a really good recommendation, I'll try this one.

And yes, I am using dart ffi along with flutter engine, `Dart_EnterIsolate` and other apis are from `dart_api.h`, these apis and dart isolate are exported from flutter engine to ffi library.

I'll provide sample code later but I'm afraid it won't run without dart isolate and dart apis. Hope this helps.

**Comment by ele828** [comment]
Hi @dcharkes  I added another runnable code to reproduce this issue using dart embedder api. It should be run on iOS arm64 or simulator with x86 static library. Btw, besides the aforementioned crash, there is another one somewhere around FlowGraphBuilder on iOS arm64.

https://drive.google.com/file/d/1-5Ap4eO30-AzvwoH5tNPpcFpdW41Muaz/view?usp=sharing

**Comment by ele828** [comment]
@dcharkes Any updates on this issue? we are still highly relying on this pattern
