### ISSUE TITLE
Iterable.firstWhere is hard to use

### ISSUE THREAD

**Issue by marcelgarus** [dart-lang/sdk#44402]
In 2013, #7939 highlighted that it's hard to use `firstWhere`, because it throws if it fails. I'm generally not a fan of `Exception`s, because they make local error handling hard to do.
But with NNBD, the usage got even worse.

Before NNBD, I used the following code to get a `baz` that's either the first one matching or `null` if none matches:
```dart
Foo baz = someFoos.firstWhere(
  (foo) => condition(foo, bar),
  orElse: () => null,
)
```
With NNBD, this doesn't compile anymore, because `orElse` should be a `Foo Function()`, not a `Foo? Function()`.
You could work around this, but it looks even worse:
```dart
Foo? baz = someFoos.cast<Foo?>().firstWhere(
  (foo) => condition(foo!, bar),
  orElse: () => null,
)
```

There should be a better way to get the first element or `null` if none matches.

**Comment by lrhn** [comment]
We've added extension methods in `package:collection` for this use-case, for example [`firstWhereOrNull`](https://pub.dev/documentation/collection/1.15.0-nullsafety.5/collection/IterableExtension/firstWhereOrNull.html).

They're being released along with null safety, and have a dev-release available for now which is null-safety compatible, so they should be usable when you migrate, if you make sure to depend on the 1.15.0-nullsafety version of package:collection.
