### ISSUE TITLE
problems with Null safety

### ISSUE THREAD

**Issue by iLnaar** [dart-lang/sdk#44408]
I am having problems with "Null safety" on the latest versions of dart_sdk. Here's a sample app from flutter:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.onWeightChanged}) : super(key: key);
  final ValueChanged<double>? onWeightChanged;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        if (widget.onWeightChanged != null) {
          widget?.onWeightChanged(10); // variant 1
          //widget.onWeightChanged(10); // variant 2
        }
        return Column();
      },
    );
  }
}
```
The code marks lines as "variant 1" and "variant 2". Both options cause opposite errors:

The first option causes errors:

> lib/main.dart:34:11: Warning: Operand of null-aware operation '?.' has type 'MyHomePage' which excludes null.
> 'MyHomePage' is from 'package:flutter_app/main.dart' ('lib/main.dart').
>           widget?.onWeightChanged(10); // variant 1
>           ^
> lib/main.dart:34:34: Error: Can't use an expression of type 'void Function(double)?' as a function because it's potentially null.
> Try calling using ?.call instead.
>           widget?.onWeightChanged(10); // variant 1

The second option throws the opposite error:

> lib/main.dart:35:33: Error: Can't use an expression of type 'void Function(double)?' as a function because it's potentially null.
> Try calling using ?.call instead.
>           widget.onWeightChanged(10); // variant 2
 
I have the following versions installed:
Android studio 4.1.1
Flutter 1.25.0-5.0.pre.87 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5b6b67aeaf (7 hours ago) • 2020-12-04 19:31:05 -0800
Engine • revision 59b4baea51
Tools • Dart 2.12.0 (build 2.12.0-113.0.dev)

Earlier versions of dart_sdk had the same errors, so I updated to the latest versions

**Comment by RedBrogdon** [comment]
Interesting. The issue with the first one is that the `widget` reference isn't the part that's potentially null -- it's the property `onWeightChanged`. The issue with the second is that because `onWeightChanged` may be null, it can't simply be invoked as a non-nullable function would. There has to be a check to handle the null case.

I can think of two ways to deal with this, though neither is that great:

```dart
final local = widget.onWeightChanged;
if (local != null) {
  local(10);
}
```

```dart
widget.onWeightChanged?.call(10)
```

What's the preferred (read: "real" 😄 ) way of handling something like this?

**Comment by iLnaar** [comment]
Thanks. Both of your suggested methods work. Although I don't like them either. But I think the second way is better, because no need to create an additional variable. :thumbsup:
