### ISSUE TITLE
webview_flutter , platformview consumes a lot of memory in ios

### ISSUE THREAD

**Issue by wanjm** [dart-lang/sdk#44400]
when use webview_flutter  or widgets depends on platformview, it will consume about 150M memory; but use webview in ios directory by objectC, it comsumes only 15M meomory; 
why does platformview use so much memory;  as my app need to show native views by using platformview, then it crashes for  short of memory;

is there any plan to optimize it?

**Comment by mraleph** [comment]
Flutter bug reports which are not directly related to Dart should be filed at flutter/flutter repository.
