### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Yangzhuren** [dart-lang/sdk#44401]
## Version information

- `IDEA AI-201.8743.12.41.6953283`
- `2.10.3`
- `AI-201.8743.12.41.6953283, JRE 1.8.0_242-release-1644-b3-6915495x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.16, screens 1440x900  Retina`

**Comment by srawlins** [comment]
Please include any details you see in the log from IntelliJ on this report if you see it again.
