### ISSUE TITLE
Dart Analyzer crashes or stops working randomly

### ISSUE THREAD

**Issue by azimuthdeveloper** [dart-lang/sdk#44410]
* Dart SDK Version: Dart SDK version: 2.12.0-76.0.dev (dev) (Wed Nov 25 05:22:28 2020 -0800) on "windows_x64"
* Whether you are using Windows, MacOSX, or Linux: Windows

The dart analyzer stops working randomly, and autocomplete in Android Studio or IntelliJ IDEA stops working at the same time. Restarting the Analyzer manually seems to resolve the issue.

Also, the Analyzer will crash at various times, but won't report on exceptions that it has encountered (I suppose this is because the exceptions are only listed for the current running session, and exceptions encountered *before* the last crash aren't showing up).

I'm sorry about the complete lack of logs or actionable information on this issue - I'm happy to try to create a repro project or give logs but I couldn't see where the dart analyzer normally produces error logs to supply.

Tagging @domesticmouse as per his request :) Thanks Brett :)

**Comment by jamiethain** [comment]
Same Same 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.51.1)
[√] Connected device (4 available)

• No issues found!

================ near the bottom of the log ======================== 

[12:26:23 PM] [Analyzer] [Info] ==> {"id":"104","method":"edit.getFixes","params":{"file":"C:\\Users\\jamie\\develop\\flmobile\\lib\\views\\HistoryActiveFuture\\historyactivefuture.dart","offset":1634},"clientRequestTime":1607448383134}
[12:26:23 PM] [Analyzer] [Info] ==> {"id":"105","method":"edit.getAssists","params":{"file":"C:\\Users\\jamie\\develop\\flmobile\\lib\\views\\HistoryActiveFuture\\historyactivefuture.dart","length":0,"offset":1634},"clientRequestTime":1607448383135}
[12:26:23 PM] [Analyzer] [Info] ==> {"id":"106","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\jamie\\develop\\flmobile\\lib\\views\\HistoryActiveFuture\\historyactivefuture.dart","length":0,"offset":1634},"clientRequestTime":1607448383135}
[12:26:23 PM] [Analyzer] [Info] <== {"id":"104","result":{"fixes":[]}}
[12:26:23 PM] [Analyzer] [Info] <== {"id":"106","result":{"kinds":["EXTRACT_METHOD","RENAME"]}}
[12:26:23 PM] [Analyzer] [Info] <== {"id":"105","result":{"assists":[]}}
[12:26:42 PM] [Analyzer] [Info] Process terminated! 3221225477, null

**Comment by scheglov** [comment]
Without repro there is not much that we can do :-(

**Comment by jamiethain** [comment]
Well my computer does it 100% of the time, I moved to a Mac, lots of people
in our group have the analyzer crash all the time.

What would you like me to do?

**Comment by scheglov** [comment]
Ideally, I'd like to have code base and steps to reproduce (i.e. just open this project, or open and make this change, etc).
Send it to `scheglov@google.com`.
Of course any this data will not go anywhere from me, and I will remove it once I'm done fixing the issue.

**Comment by lewcianci** [comment]
Hey @scheglov, where does the analyzer write logs to? I understand that a repro would be most beneficial, but surely if I could supply logs that show what crashed and why, that would at least help us get started.

Perhaps a better question to ask, does the analyzer produce logs that persist between sessions? And if it does, where can I find these logs?

If it doesn't produce logs that I can attach to issues like these, then that's something that I feel like is fairly critical to implement (especially as frameworks like Flutter become more widespread and more people have more chance of running into issues with the analyzer).

**Comment by scheglov** [comment]
When the analyzer has an exception during analysis, it should store some data into files named `exception_*` in `~/.dartServer/.analysis-driver`.

**Comment by srawlins** [comment]
Closing as stale; if this can be reproduced with logs or a minimal reproduction, please feel free to open a new issue.
