### ISSUE TITLE
Incorrect unnecessary_cast from analyzer when cast influences type inference

### ISSUE THREAD

**Issue by MohiuddinM** [dart-lang/sdk#44411]
This code doesn't work: The argument type 'SizedBox' can't be assigned to the parameter type 'Text'.
```
final items = [1, 2, 3].map((e) => Text(e.toString())).toList();
items.add(SizedBox());
```

Adding a cast `as List<Widget>` solves the problem, but then it asks to remove unnecessary cast.

**Comment by mraleph** [comment]
`items` is a `List<Text>` because of how `map` is defined: if you give `map` a function which returns `T` you get an `Iterable<T>` as a result. 

There are few ways to fix it:

```dart
final items = [1, 2, 3].map<Widget>((e) => Text(e.toString())).toList();
items.add(SizedBox());
```

or alternatively:

```dart
final items = [
  for (var e in [1, 2, 3])
    Text(e.toString());
  SizedBox(),
]
```

> Adding a cast as `List<Widget>` solves the problem, but then it asks to remove unnecessary cast.

That's wrong message from the analyzer though. Self contained repro:

```dart
class A {}

class B extends A {}

class C extends A {}

void main() {
  final items = [1, 2, 3].map((e) => B()).toList() as List<A>;
  items.add(C());
}
```

Produces `unnecessary_cast` but clearly should not because cast influences inference.

**Comment by eernstg** [comment]
The syntactic context `e as T` actually does not provide a context type for `e`, so we will create a `List<B>` and then perform the upcast to `List<A>`. So the inference applied to `[1, 2, 3].map((e) => B()).toList()` works as it would have worked with `final items = [1, 2, 3].map((e) => B()).toList();`.

But I agree that the cast does have an effect: The type of `items` is `List<A>` with the cast and `List<B>` without it.

**Comment by mraleph** [comment]
Thanks for clarification @eernstg. Yeah, now that I actually run the code I see that it only affects the static type of `items` but not its runtime type. I am a bit puzzled why it solved an issue for the reporter then:

> Adding a cast as List<Widget> solves the problem, but then it asks to remove unnecessary cast.

Given your explanation it is is clearly "redundant cast", though it might have downstream effects on the inference.

**Comment by eernstg** [comment]
I suspect that it didn't resolve the problem: The compile-time error was gone, because we're no more trying to add a `SizedBox` to a `List<Text>` according to the static types, but it will still do exactly that in terms of the types at run time, and then there will be a downcast failure.

**Comment by MohiuddinM** [comment]
You are right, cast doesn't solve the problem. It only helps with compilation. This is the error I get at runtime:
`type 'SizedBox' is not a subtype of type 'Text' of 'value'`

**Comment by scheglov** [comment]
@bwilkerson @pq
