### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by hibkh** [dart-lang/sdk#44424]
## Version information

- `IDEA AI-201.8743.12.41.6953283`
- `2.10.4`
- `AI-201.8743.12.41.6953283, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1360x768`

**Comment by eernstg** [comment]
@hibkh, I think you pressed "send" a bit too early? I'll close this one. If you have noticed an issue, please create a new issue and provide some more information, and thanks in advance for doing so!
