### ISSUE TITLE
Disable auto update of chrome on bots

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44430]
There are new test failures on [Flow analysis: Track expression variables separately from promotion info.](https://github.com/dart-lang/sdk/commit/fd2a6c68153bd1d0740e638df8fb8a7b1d7ed70d).

The tests
```
pkg/dds/test/sse_smoke_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux
unittest-asserts-release-mac
```

According to @bkonyi, this is an infrastructure issue and is unrelated to the CL that was blamed.  He says:

> The Chrome version is supposed to be pinned but we run into issues once in awhile where the bots decide they're going to update themselves.

**Comment by athomas** [comment]
https://dart-ci.appspot.com/log/pkg-mac-release/unittest-asserts-release-mac/15179/pkg/dds/test/sse_smoke_test
```
00:02 [32m+0[0m[31m -1[0m: DDS SSE Smoke Test with authentication codes [1m[31m[E][0m[0m
  SessionNotCreatedException (500): session not created: This version of ChromeDriver only supports Chrome version 83
```

@bkonyi the linux issue is different, though:
https://dart-ci.appspot.com/log/pkg-linux-debug/unittest-asserts-debug-linux/9059/pkg/dds/test/sse_smoke_test
```
00:30 [32m+0[0m[31m -1[0m: DDS SSE Smoke Test with authentication codes [1m[31m[E][0m[0m

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts

  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1178:47                      _rootRun
  dart:async/zone.dart 1090:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1186:13                      _rootRun
  dart:async/zone.dart 1090:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 395:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 426:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePortImpl._handleMessage
```

**Comment by bkonyi** [comment]
Strange. These errors came up at the same time so I assumed they were related. Nothing changed in DDS with the change made by @stereotype441 and there's no DDS changes in the failure range... Was this marked as flaky before?

**Comment by athomas** [comment]
Ah, yes, it was marked as flaky before.

**Comment by athomas** [comment]
https://dart-review.googlesource.com/c/sdk/+/301520 switched us to chrome for testing which doesn't autoupdate.
