### ISSUE TITLE
The getter 'type' isn't defined for the class 'TypeDefiningElement'

### ISSUE THREAD

**Issue by hemantsavkar** [dart-lang/sdk#44433]
Getting Below Issues With analyzer

[SEVERE] ../../Installations/flutter_1.22.4/.pub-cache/git/inject.dart-7c3cbf6a4da2bc8357152b9c7bbcb9891cbfa320/package/inject_generator/lib/src/build/summary_builder.dart:289:31: Error: **The getter 'type' isn't defined for the class 'TypeDefiningElement'. - 'TypeDefiningElement' is from 'package:analyzer/dart/element/element.dart**' ('../../Installations/flutter_1.22.4/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.            returnTypeElement.type.isDynamic) {                              ^^^^../../Installations/flutter_1.22.4/.pub-cache/git/inject.dart-7c3cbf6a4da2bc8357152b9c7bbcb9891cbfa320/package/inject_generator/lib/src/build/summary_builder.dart:306:45: Error: The getter 'type' isn't defined for the class 'ClassElement'. - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('../../Installations/flutter_1.22.4/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.  var returnType = element.enclosingElement.type;                                            ^^^^../../Installations/flutter_1.22.4/.pub-cache/git/inject.dart-7c3cbf6a4da2bc8357152b9c7bbcb9891cbfa320/package/inject_generator/lib/src/analyzer/visitors.dart:120:18: Error: The getter 'constantValue' isn't defined for the class 'ElementAnnotation'. - 'ElementAnnotation' is from 'package:analyzer/dart/element/element.dart' ('../../Installations/flutter_1.22.4/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'constantValue'.      annotation.constantValue.getField('modules').toListValue();                 ^^^^^^^^^^^^^../../Installations/flutter_1.22.4/.pub-cache/git/inject.dart-7c3cbf6a4da2bc8357152b9c7bbcb9891cbfa320/package/inject_generator/lib/src/analyzer/visitors.dart:143:63: Error: The getter 'isObject' isn't defined for the class 'InterfaceType'. - 'InterfaceType' is from 'package:analyzer/dart/element/type.dart' ('../../Installations/flutter_1.22.4/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/type.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'isObject'.    for (var supertype in clazz.allSupertypes.where((t) => !t.isObject)) {                                                              ^^^^^^^^../../Installations/flutter_1.22.4/.pub-cache/hosted/pub.dartlang.org/json_serializable-3.4.1/lib/src/shared_checkers.dart:66:47: Error: The getter 'isObject' isn't defined for the class 'DartType'. - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../Installations/flutter_1.22.4/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/type.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'isObject'.bool isObjectOrDynamic(DartType type) => type.isObject || type.isDynamic;                                              ^^^^^^^^

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
`TypeDefiningElement.type` was deprecated more than a year ago, in decca61f8c01cc4dbe483549bccaeb1c583ea4a2.
It was removed in `analyzer 0.40.0` in a51f1747e0a6b99215a3f03ceee6d6af1ce3f0ba.

It looks that `inject_generator` is not compatible with newer versions of `analyzer`.
You need to see why newer `analyzer` was used with `inject_generator`.
I see `analyzer: ^0.34.0` in its `pubspec.yaml`.
