### ISSUE TITLE
Allow sending a generic object with a function type parameter between isolates

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#44431]
See https://github.com/dart-lang/sdk/issues/37294

This code fails, now with a meaningful error message:

```dart
import 'dart:isolate';

void fun() {
 print('hi from fun');
}

Future<void> main() async {
  final x = <void Function()>[fun];
  await Isolate.spawn(isolate, x);
}

void isolate(List<void Function()> foo) async {
  print('Tick: $foo');
  foo.first();
}
```

But this code works:

```dart
import 'dart:isolate';

void fun() {
  print('hi from fun');
}

Future<void> main() async {
  final x = <dynamic>[fun];
  await Isolate.spawn(isolate, x);
}

void isolate(List<dynamic> foo) async {
  print('Tick: $foo');
  (foo.first as void Function())();
}
```

It'd be nice to let the typed version work too.

**Comment by dnfield** [comment]
(it also works with a `List<Object>`)

**Comment by mkustermann** [comment]
After we're done with https://github.com/dart-lang/sdk/issues/36097 this would probably implicitly work because we we'll share function type objects across isolates.

**Comment by mkustermann** [comment]
Closing this issue into the more general https://github.com/dart-lang/sdk/issues/46623.
