### ISSUE TITLE
Null safety feedback: [ retrieving value from map in a null safe way ]

### ISSUE THREAD

**Issue by SebastianJL** [dart-lang/sdk#44444]
I am not sure if this belongs here. I also posted it as a [question](https://stackoverflow.com/questions/65235879/dart-null-safety-retrieving-value-from-map-in-a-null-safe-way) on Stackoverflow. So you might feel better deleting it here and answering it over there.

I had code similar to this example code (never mind that it makes no sense):
```dart
void foo(Map<int, String> myMap) {
  String s = myMap[1];
}
```

The dart analyzer warns me about the line `String s = myMap[1];` with the following warning:

> A value of type 'String?' can't be assigned to a variable of type
> 'String'.  Try changing the type of the variable, or casting the
> right-hand type to 'String'.

I see that this is happening because retrieving a value from a map can result in `null`. Why does the following snippet give me the same warning? 

```dart
void foo(Map<int, String> myMap) {
  if (myMap.containsKey(1)) {
    String s = myMap[1];
  }
}
```

Is the dart analyzer not smart enough or is this really an error from my side?

**Comment by Jjagg** [comment]
The analyzer can’t know that `containsKey(1)` returning true means `[1]` does not return null. And even if it could, the value might be removed from the map in between the two invocations.

This is exactly what the bang is for, you know it won’t return null: 

```
String s = myMap[1]!;
```

You can also just try to get the value and check for null: 

```
void foo(Map<int, String> myMap) {
  final s = myMap[1];
  if (s != null) {
    // analyzer knows s is not null here
    final l = s.length;
  }
}
```

This only does 1 lookup instead of 2.

**Comment by SebastianJL** [comment]
Thanks a lot. I will link here from StackOverflow and now close this issue.
