### ISSUE TITLE
[vm/ffi] Expose Dart_TypedDataAcquireData and Dart_TypedDataReleaseData in dart_api_dl.h

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44442]
To enable copy-free access of `Uint8List` in native code through `Object` -> `Dart_Handle` in trampolines we should expose `Dart_TypedDataAcquireData` and `Dart_TypedDataReleaseData` in `dart_api_dl.h` so that those symbols are available in Flutter.

Background: https://stackoverflow.com/questions/65194980/search-for-sequence-in-uint8list
Background: https://github.com/dart-lang/sdk/issues/40607

**Comment by mraleph** [comment]
I would suggest not to expose them if possible. Instead we should prefer implementing typed data -> pointer unwrapping on leaf calls.

**Comment by dcharkes** [comment]
I agree that would be the cleaner solution.

**Comment by dcharkes** [comment]
I filed https://github.com/dart-lang/sdk/issues/44589 to implement @mraleph's suggestion instead.
