### ISSUE TITLE
[CP][beta channel] fix for recent regression to expression evaluation in DDC

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#44452]
**commit(s) to merge**: 2e97d91dcd6676e32a87a4c0707d73493f14f7cf

**merge instructions**: N/A - beta hash has not been selected yet so I couldn't try it out, but likely a clean merge.

**What is the issue**: A change landed last week to fix a long standing bug (https://github.com/dart-lang/sdk/issues/39187) where stepping speed when debugging flutter-web apps was very slow (a single step could be longer than 15s). The change was a large (~20x) improvement, but it involved some non-trivial reorganization of symbols in the DDC output.

The change indirectly broke expression evaluation in some cases (e.g. when the expression being evaluated used indirectly types or constants.)

**What is the fix**: Further changes to adjust the implementation and the expression evaluator to work well together.

**Why cherrypick**: Regression on eval. This and a previous change from last week (37d8c78237e875355ffe36d6b2b33c29606a43fa) should be shipped together on the same release to prevent a regression on expression evaluation.

We'd prefer to include both in this beta release to get feedback from users before the upcoming stable release next year. If we feel the risk is too high, we should then revert the previous change as well to prevent the regression.

**Risk**: medium - both this and the other change are fairly recent and have little coverage beyond manual testing. Even though the first change is already covered by bots and internal users, the coverage depends on their use of debugging features like stepping and evaluation.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/39187

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @Markzipan

**Comment by franklinyow** [comment]
We have a branch point this morning--a92baed5f8e23759b4d0dbd45ea19c597b1d95b9   
@sigmundch  What is the risk of do nothing?  I'm worry about medium risk change when we are so close to holiday.

@pcsosinski  FYI

**Comment by sigmundch** [comment]
Given that we have known regressions with 37d8c78 I feel it is a higher risk doing nothing. If we wanted to go with the lowest risk, then reverting 37d8c78 would be the safest.

@mariamhas @kevmoo  - I'm also curious to hear your thoughts on the product perspective here: Is it better to wait or is it better to get this out to get more coverage prior to the upcoming stable release?

**Comment by kevmoo** [comment]
I'd love to keep the improvement. Do we feel good about the regression tests, @sigmundch ?

**Comment by pcsosinski** [comment]
i agree it's better to keep the improvements, but this is also an example of why we should revert rather than fix forward.  off my soapbox, how long do you need internal users / whatever criteria to have confidence in https://github.com/dart-lang/sdk/commit/2e97d91dcd6676e32a87a4c0707d73493f14f7cf @sigmundch?  we'll likely get a beta build Monday CET.

**Comment by mariamhas** [comment]
+1 to keeping improvement and getting more coverage before stable release.

**Comment by sigmundch** [comment]
It's hard to get any coverage in the wild because evaluation is not yet supported internally, so we rely mostly on our test coverage, external usage, and manual validation.

I was torn earlier today to be honest, so I tried some additional manual testing this afternoon and I unfortunately still found cases where we need an additional fix (likely very small). I'm tempted to go the safe route here and hold off on the feature for a bit longer (keep it in master, but cherry-pick a revert for the beta cut).

@mariamhas @kevmoo - I assume we don't want any regression on the eval functionality, correct?  As an example a regressions without the cherry-pick would be that anything that needs types or constants may fail. This includes things like typing a function name, like `main` in the eval console (its type is computed when evaluating it as an expression)

@Markzipan - I'll try to create a small repro for you on Monday.

**Comment by sigmundch** [comment]
After further discussion, we are inclined to take the safe route and release the current beta without the improvements. I filed a request to cherry-pick the revert here: https://github.com/dart-lang/sdk/issues/44471
