### ISSUE TITLE
'List' is deprecated and shouldn't be used

### ISSUE THREAD

**Issue by aliyazdi75** [dart-lang/sdk#44468]
I know we can use `<String>[]` instead of using `List<String>`, but how to implement `List<String>(length)`?
As [doc](https://dart.dev/guides/language/effective-dart/usage#do-use-collection-literals-when-possible) says:

> Note that this guideline doesn’t apply to the named constructors for those classes. List.from(), Map.fromIterable(), and friends all have their uses. Likewise, if you’re passing a size to List() to create a non-growable one, then it makes sense to use that.

**Comment by eernstg** [comment]
The problem with `List<T>(length)` is that it needs to contain `length` elements initially, and when the type `T` is non-nullable it can't be null. `List<String>.filled(length, "")` is the typical replacement, and it allows you to specify which element to use (and, if needed, `growable: true`).

**Comment by aliyazdi75** [comment]
@eernstg 
Thanks for your response. I think I'm so confused these days about null and non-null :smile:
It's better that the doc covers new depreciation and suggests its replacement.

**Comment by eernstg** [comment]
Thanks! I think everybody needs some time to get used to a lot of new properties, nothing wrong in that :smile:

The DartDoc comment in the bleeding edge `list.dart` has the following:

```
   * Creates a list of the given length.
   *
   * **NOTICE**: This constructor cannot be used in null-safe code.
   * Use [List.filled] to create a non-empty list.
   * This requires a fill value to initialize the list elements with.
   * To create an empty list, use `[]` for a growable list or
   * `List.empty` for a fixed length list (or where growability is determined
   * at run-time).
```

so it's a matter of getting that text through the pipeline, and then we will have the information where it should be.

**Comment by rjvysakh** [comment]
List(1 * 192).reshape([1, 192]);  can be chaged as List.filled(1 * 192, null, growable: false).reshape([1, 192]);
