### ISSUE TITLE
Null safety feedback: [some packages will need some updates]

### ISSUE THREAD

**Issue by benedicte69** [dart-lang/sdk#44462]
It seems that some packages refer to other packages but not to their null safety version

For example Flutter devtool package refers to the non nullsafety version of the following package:

package:devtools_server
package:args
package:browser_launcher
package:devtools_shared
package:http_multi_server
package:meta
package:shelf
package:vm_service
package:async
package:collection
package:http_parser
package:stack_trace
package:stream_channel
package:sse
package:shelf_proxy
package:shelf_static
package:usage
package:webkit_inspection_protocol
package:http
package:pedantic
package:string_scanner
package:logging
package:convert
package:mime
package:source_span
package:charcode
package:typed_data
package:term_glyphDescribe the issue or potential improvement in detail here

**Comment by srawlins** [comment]
Please open a bug against the flutter repository which contains the code that needs updating, at github.com/flutter.
