### ISSUE TITLE
Add Stream.whereType

### ISSUE THREAD

**Issue by marcelgarus** [dart-lang/sdk#44469]
Most of the `Iterable` methods are also available on `Stream`s.
But `whereType` isn't, which means developers have to write code like the following:

```
someStream.where((item) => item is T).cast<T>()
```

I'd really like it if a `Stream.whereType` method would also be provided by the standard library.

See #44443

**Comment by lrhn** [comment]
We are aware of the problem (#34050). It was an oversight with the 2.0 release.
Would be nice, but would also be a breaking change to add now.
