### ISSUE TITLE
analyzer complains even when checking for null values

### ISSUE THREAD

**Issue by MohiuddinM** [dart-lang/sdk#44463]
I get an error even when checking for null value:
An expression whose value can be 'null' must be null-checked before it can be dereferenced at
```
class T {
  final String? s;

  T(this.s);

  void f() {
    if (s != null && s.length > 3) {}
  }
}
```

**Comment by lrhn** [comment]
The reason that a test for null can sometimes cause a later use of a nullable variable to be allowed, is that it causes a *type promotion* from the nullable type to the non-nullable (sub-)type. This is the same as any other type promotion, say having a `num` and checking that it's an `int`.

Dart *only* performs type promotion when it's guaranteed to be safe, when the compiler is absolutely certain that the value you *check* is also the value you *use* later. 
That currently means that you can only promote local variables. Even a private field might be overridden by a getter in a subclass, so the compiler cannot locally determine for sure that the value won't change between check and use.

You can copy the variable to a local variable:
```dart
void f() {
  var s = this.s;
  if (s != null && s.length > 3) { /*...*/ }
}
```
or you can add a `null` check to the `length` access:
```dart
void f() {
  if (s != null && s!.length > 3) { /*...*/ }
}
```

**Comment by lrhn** [comment]
Could the analyzer give a different error message when something looks like the user wanted it to promote, but it doesn't for non-local variables.

**Comment by eernstg** [comment]
@stereotype441, would it be overkill to let the analyzer maintain the same information about non-local variables (that is, instance and static variables of the enclosing class and top-level variables) as the information which is currently maintained for local variables, and then check for each failing member lookup whether the member is statically known based on the would-be promoted type? We could then report that the failure could be caused by a lack of promotion.

**Comment by stereotype441** [comment]
@eernstg not at all.  We have been talking about similar ideas for a while, just haven't gotten time to work on it.  Main tracking issue is here: https://github.com/dart-lang/sdk/issues/38773

**Comment by srawlins** [comment]
Follow #38773 for the resolution to this issue.
