### ISSUE TITLE
File.rename across volumes

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#44464]
Right now, on Linux, using `File.rename` fails when trying to move the file to a different volume (`OS Error: Invalid cross-device link, errno = 18`). We should either document this limitation or handle it.

**Comment by sortie** [comment]
This is how the operating systems work in the underlying rename(2) system call. The restriction is important as it means one can trust the renames are atomic with respect to the filesystem and it shouldn't be worked around in Dart. A higher level API could provide such rename support across filesystems, although it is tricky to also properly preserve the file meta-information with the APIs currently exposed to Dart.

Documenting this behavior is meaningful and would avoid confusion, so I recommend doing that, although there has to be a fine line with how much the documentation of the underlying operating systems are repeated.

**Comment by Hixie** [comment]
If we don't want to duplicate the documentation we should at a minimum link to that documentation, because right now there's nothing that says what lower-level calls our APIs map to.

**Comment by brianquinlan** [comment]
I think that we shouldn't do worse than other programming languages e.g.
https://docs.python.org/3/library/os.html#os.rename

**Comment by brianquinlan** [comment]
Fixed in Ibbc692545af636e33cfa7f5946480d3640d95b5c
