### ISSUE TITLE
`dart analyze` should add a machine readable output option

### ISSUE THREAD

**Issue by Wikiwix** [dart-lang/sdk#44465]
The old `dartanalyzer` cli has an option `--format machine` which is not available for `dart analyze`.

I personally want to use it to display [code quality in GitLab](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html) which would be a simple task if I get easily parseable input from the analysis.

**Comment by bwilkerson** [comment]
@devoncarew

**Comment by devoncarew** [comment]
A not-yet-released version of the SDK does add the `--machine` option to the `dart analyze` command:

```
    --format=<value>         Specifies the format to display errors.

          [default]          The default output format. This format is intended to be user consumable.
                             The format is not specified and can change between releases.
          [machine]          A machine readable output. The format is:
                             
                             SEVERITY|TYPE|ERROR_CODE|FILE_PATH|LINE|COLUMN|LENGTH|ERROR_MESSAGE
                             
                             Note that the pipe character is escaped with backslashes for the file path and error message fields.
```

Note that the 'machine' format is specific to Dart. We'd be interested to know if there are any pseudo industry formats that we could also emit - it may make the analyze command easier to plug into existing systems / CIs.

**Comment by Wikiwix** [comment]
The coming `machine` option is already a win, but how will newlines be treated? (As CSV or PSV in this case has quite some variable parts, I guess providing the same with a JSON for every line would be a win as well?

### Regarding the *industry standard*, at least GitLab uses an open third party format by Code Climate

* I would really love if you could provide this expected output from Code Climate (I guess if this was available it could even be added into the GitLab default/example `.gitlab-ci.yml` for Dart
* GitLab follows [this Code Climate spec](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types) which should be easy enough to follow, based on the values you already provide.
* Using this properly in a GitLab CI pipeline will lead to the [following view in Merge Requests](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#code-quality-widget).
* More details [further down the page](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) (with information on what part of the general spec of Code Climate, GitLab actually uses and expects).

**Comment by bkonyi** [comment]
@devoncarew is there anything actionable left for this issue?

**Comment by bwilkerson** [comment]
> ... how will newlines be treated?

There are no newlines within any of the fields that we print, so all of the fields will be on a single line. Each diagnostic is printed on a separate line.

> I guess providing the same with a JSON for every line would be a win as well?

We have been discussing that as a possible future format, but don't have any concrete plans or timeframe for having one.

> I would really love if you could provide this expected output from Code Climate ...

Unfortunately, that format wouldn't meet some of the requirements that prompted the ongoing discussion of providing a json format, so if we do have a json format it probably won't be compatible. But it might have enough information to be easily converted to the Code Climate format, for what that's worth.

**Comment by devoncarew** [comment]
Closing this as dart analyze now does support a machine format. There's discussion in https://github.com/dart-lang/sdk/issues/44905 about possibly also adding JSON as an output format.

**Comment by Wikiwix** [comment]
> Closing this as dart analyze now does support a machine format. There's discussion in #44905 about possibly also adding JSON as an output format.

Ok, thanks for the update. Just tested this in Dart `2.12.0-259.12.beta` where it already works, but the new option is missing in the help text:

```plaintext
$ dart analyze -hv
Analyze the project's Dart code.

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options.
```

**Comment by bwilkerson** [comment]
The message should be displayed if you run `dart analyze -h -v`. I don't believe that the `dart` tool supports merging options in the way you were trying to use it.

@bkonyi Is that intensional or is that a bug?

**Comment by Wikiwix** [comment]
> The message should be displayed if you run `dart analyze -h -v`. I don't believe that the `dart` tool supports merging options in the way you were trying to use it.
> 
> @bkonyi Is that intensional or is that a bug?

Ah, that explains part of it. I just thought there are no verbose flags, because the `verbose` flag is not displayed in the normal help text.
