### ISSUE TITLE
Dart fails to evaluate expressions that call on extension methods when using the debugger

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#44472]
Say I have the following code.

```Dart
main(){
  final two = 1.plusOne;
}

extension on int {
  int get plusOne => this + 1;
}
```

if I put a breakpoint here and try to evaluate `1.plusOne`, it'll throw an
> Unhandled exception:
> NoSuchMethodError: Class 'int' has no instance method 'plusOne'.

This is the case in IntelliJ and VS Code
Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"

**Comment by Daniel-Glucksman** [comment]
+1

**Comment by thiago-bardez-iteris** [comment]
+1

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by johnniwinther** [comment]
cc @jensjoha

**Comment by jensjoha** [comment]
@bkonyi I see you have self-assigned, but this is basically what I'm adding in https://dart-review.googlesource.com/c/sdk/+/215760 .

**Comment by bkonyi** [comment]
> @bkonyi I see you have self-assigned, but this is basically what I'm adding in https://dart-review.googlesource.com/c/sdk/+/215760 .

Awesome! I'll reassign to you then.

**Comment by a-siva** [comment]
Can we just mark this as a duplicate of the other issue and close this.

**Comment by a-siva** [comment]
@jensjoha  Can this be closed ?

**Comment by jensjoha** [comment]
I believe it can.
