### ISSUE TITLE
Observatory: programatic access to all instances of a class

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#44479]
I'm trying to find big Strings, but the UI to access instances is tedious (show next 100, 200, etc elements) and when I find an instance, often the ObjectId has expired, making it impossible to inspect the instances.

What would be better is if there was a way to return an array of all instances. Then I could evaluate an expression to find the big strings, and there would be ObjectIds only for the filtered results.

The class view could have a ↺ link that is replace by the array.

**Comment by rakudrama** [comment]
I have been experimenting with a prototype.
It is very useful!

- Make clear that 'all subinstances' is the subclasses and not all subtypes (a tool-tip perhaps, mentioning 'extends'?). Perhaps call it 'all + extends'.
- All subtypes would also be useful. A class-id predicate could be synthesized for all classes that 'implements' the class for an efficient test during the scan.
- There have been some difficulties writing expression that work for my queries. I'll file separate issues for 'evaluate'
-

**Comment by rmacnak-google** [comment]
f54bb55244d008718e684b20047969bd2543aa27
