### ISSUE TITLE
[CP][beta channel] revert change to prevent regression on DDC's eval

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#44471]
**commit to revert**: 37d8c78

**what's the issue**: the commit above landed mostly well, but it regressed some behavior on expression evaluation. There is a fix in 2e97d91 but there may be another smaller fix in the works.

**What is the fix**: revert from the beta channel a recent change that caused the regression.

**Why cherrypick**: a regression that may be visible on expression evaluation in flutter web

**Risk**: low - this is a revert to how the system worked before Friday last week

**See also**: https://github.com/dart-lang/sdk/issues/44452 - we eventually want to bring this back in to give time for testing before the upcoming stable release.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @Markzipan @pcsosinski @mariamhas

**Comment by sigmundch** [comment]
There is a small merge conflict in that one file that was introduced in 37d8c78 was edited later. The resolution is to delete the file anyways. I'll put together a CL with the details.

**Comment by sigmundch** [comment]
https://dart-review.googlesource.com/c/sdk/+/176141 has the revert in CL form

**Comment by franklinyow** [comment]
Marking it approved.
@athomas Please include in new build

**Comment by athomas** [comment]
CP'ed in cbd08e5c567353709a0db3692caa984dbcd9aeb7 (2.12.0-133.2.beta).
