### ISSUE TITLE
List() is deprecated but does not provide a deprecation message

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#44483]
The default List (`List()`) constructor is deprecated, but there's no deprecation message associated with the annotation. We should provide one with a brief description, and / or a link to the hosted docs (which do provide a reason for the deprecation and how to switch to a supported version).

If we link to a url, we could use something like `https://api.dart.dev/stable/dart-core/List/List.html`.

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
It has a deprecation message now.
