### ISSUE TITLE
Evaluate cost and benefit of pointer compression

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#44481]
Dart uses 64 bit pointers on 64 bit architectures, even if the device is a small mobile device with less than 4GB of addressable ram.

Enabling pointer compression could substantially reduce memory consumption, but carries a maintenance burden for the VM team - it cannot be the only option since Dart still would need to be able to address >4GB on the server/desktop, and would not want to pay a performance penality for doing so.

Related to https://github.com/dart-lang/sdk/issues/31960

**Comment by dnfield** [comment]
@rmacnak-google this is probably done right?

**Comment by dnfield** [comment]
At least in terms of evluation? :)

**Comment by a-siva** [comment]
Let us use this issue for tracking the feature landing and not close it yet.

**Comment by a-siva** [comment]
Pointer compression work has landed.
