### ISSUE TITLE
[CP][beta channel] Verify consistent null safety modes of JavaScript modules

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#44498]
**commit(s) to merge**: d0ee5dbe4088f5b1cd0ccda04e9f7d87fe9a9be6

**merge instructions**: patch [CL/176504](https://dart-review.googlesource.com/c/sdk/+/176504) (merge had conflicts, CL resolves them).

**What is the issue**: If the build/test infra is misconfigured JavaScript modules compiled with different null safety modes could be loaded in the browser as part of a single app.

**What is the fix**: Verify the null safety mode each module was compiled with matches the mode of the dart sdk module loaded in the browser.

**Why cherrypick**: To catch any infrastructure errors before the stable release. The priority of this cherry pick should be considered low and we only hope to include this with other cherry picks if they happen.

**Risk**: Low, we have not seen any signs of errors.

**Link to original  issue(s)**: NA

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @sigmundch

**Comment by franklinyow** [comment]
@pcsosinski

**Comment by athomas** [comment]
Merged in 01bc1f5083950751261af2219b65df445ad8f83f (2.12.0-133.6.beta).
