### ISSUE TITLE
[CP][beta channel] Change in timing for dart:html `_EventStreamSubscription.cancel()`

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#44496]
**commit(s) to merge**: 4c2edfd5b9fe33139aad7e9ca021bd8530f47986

**merge instructions**: clean merge onto 2.12.0-133.2.beta

**What is the issue**: The timing of `_EventStreamSubscription.cancel()` is synchronous in weak mode and asynchronous in sound mode.

**What is the fix**: Reversal of the decision to change the timing of this method (a breaking change) when opting into sound null safety. We are going to keep the existing synchronous timing in weak and sound modes.

**Why cherrypick**: To prevent packages from migrating to null safety and making changes to accommodate the asynchronous timing we introduced when migrating the SDK to null safety.

**Risk**: Low, only specific uses of DOM event streams in dart:html in packages that have already migrated to null safety will be at risk for noticing the change.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44157

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @sigmundch

**Comment by franklinyow** [comment]
Approved in SCRUM
@pcsosinski

**Comment by athomas** [comment]
Merged in 01bc1f5083950751261af2219b65df445ad8f83f (2.12.0-133.6.beta).
