### ISSUE TITLE
Failure in pkg/vm_snapshot_analysis/test/instruction_sizes_test

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44507]
The test
```
pkg/vm_snapshot_analysis/test/instruction_sizes_test RuntimeError (expected Pass)
```
is failing on configuration
```
unittest-asserts-release-linux
```

The trybot infrastructure classified this test as going from "flaky" to "RuntimeError (expected Pass)" in one of my 5 cls:
- 6853db8e7716979ed9a0bd3e74c9249a7c31301d
- 4510f1dc984c3412d36c11223d40b64192f34a7e
- 5c19c9f5e4b0659205e102c70aa444aba8fa0a9e
- c64842e582aaca210f6d072d7041b30f9748a600
- afc9a4eeffae5d7e59a41c2cd18a6f89361c241d

However I find the test to be just as flaky both before and after my CLs:
- With bb7081c6c759d9b827fba19cce2500c6a0aec14f (the CL just before mine), I see 10 failures out of 10 runs
- With 6853db8e7716979ed9a0bd3e74c9249a7c31301d (the last of my 5 CLs), I also see 10 failures out of 10 runs

**Comment by mraleph** [comment]
(Assigning the actual failure to myself so that I remember to take a look at it when I come back from holidays)
