### ISSUE TITLE
[DDS] support requesting stream history on stream subscription to historical streams

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#44505]
Streams for which we have historical data: https://github.com/dart-lang/sdk/blob/master/pkg/dds/dds_protocol.md#streams

Right now, DDS sends historical events upon the first stream subscription per client. In DevTools, we have multiple subscriptions from the same client, and would like to be able to request history upon stream subscription. I think adding an optional `sendHistory` param for `onExtensionEvent`, `onLoggingEvent`, `onStderrEvent`, and `onStdoutEvent` would work. Then DDS could send all history to the subscription based on the value of this parameter.

**Comment by bkonyi** [comment]
As discussed offline, DevTools subscribes to its streams immediately after the VM service connection is established and never resubscribes. I've gone ahead and [added](https://dart-review.googlesource.com/c/sdk/+/177182) a `getStreamHistory` RPC instead which allows for clients to manually request history for a stream.

**Comment by kenzieschmoll** [comment]
Would it be possible to add additional methods to dds `onLoggingEventWithHistory` for example, that stitch together the historical events and the new events? This would take the responsibility off the clients to do this manual stitching and could reduce the risk of dropping events or getting events out of order.
