### ISSUE TITLE
Object with function type bounded type does not get its interface from bound

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#44506]
Consider the following library:

```dart
void test<F extends Function()>(F Function() getFunction) {
  late F f1 = throw 0;
  final f2 = getFunction();

  getFunction().call(); // Error.
  f1.call(); // Error.
  f2.call(); // Error.
}
```

This library is accepted by the common front end, but it is rejected by the analyzer (from bb7081c6c759d9b827fba19cce2500c6a0aec14f) with the following compile-time errors:

```
ERROR|COMPILE_TIME_ERROR|INVOCATION_OF_NON_FUNCTION|/usr/local/google/home/eernst/lang/dart/scratch/202012/n018.dart|6|6|4|'call' isn't a function.
ERROR|COMPILE_TIME_ERROR|INVOCATION_OF_NON_FUNCTION|/usr/local/google/home/eernst/lang/dart/scratch/202012/n018.dart|5|17|4|'call' isn't a function.
ERROR|COMPILE_TIME_ERROR|INVOCATION_OF_NON_FUNCTION|/usr/local/google/home/eernst/lang/dart/scratch/202012/n018.dart|7|6|4|'call' isn't a function.
```

However, we have a [general rule](https://github.com/dart-lang/language/blob/988d82bd0f126192fa4af8616654f75e76f675eb/specification/dartLangSpec.tex#L4321) saying that a type which is _T_ bounded for some type _T_ gets the interface from _T_. For example, `X extends int` is considered to have an `isEven` method because `int` has an `isEven` method.

This implies that an object with static type `F` should be considered to have a `.call` method with signature `dynamic call()`.

**Comment by srawlins** [comment]
Note the very similar https://github.com/dart-lang/sdk/issues/42975. Both would be fixed with a "function-type-bounded" fix.

**Comment by srawlins** [comment]
Solved 🎉
