### ISSUE TITLE
"Set the lower SDK constraint" message isn't very clear

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#44519]
When I run `dart migrate` on Dart projects, I sometimes get this message:

```
Migrating /home/ianh/dev/foo

See https://dart.dev/go/null-safety-migration for a migration guide.

[...analysis errors...]

The migration tool didn't start, due to analysis errors.

The following steps might fix your problem:
1. Set the lower SDK constraint (in pubspec.yaml) to a version before 2.12.
2. Run `dart pub get`.
3. Try running `dart migrate` again.

More information: https://dart.dev/go/null-safety-migration
```

I have no idea haw to do the first step, "Set the lower SDK constraint (in pubspec.yaml) to a version before 2.12". (I know, because of working on Flutter and Dart as my day job, that I can figure out how to do this by copying and pasting from the pubspec.yaml created by `flutter create`, but I don't expect most people to know that.)

We should say something more helpful, like:

```
1. Set the lower SDK constraint of the package to a version before 2.12, by including the following in your pubspec.yaml:
   environment:
     sdk: <2.10
```
...or whatever the syntax is (I don't remember what it is).

If there is no pubspec.yaml at all, the message should probably acknowledge that. (Not having a pubspec.yaml is a common cause of this message.)

If there is one, maybe it should offer to just make the change for you.

**Comment by Hixie** [comment]
cc @leafpetersen

**Comment by bwilkerson** [comment]
@stereotype441 @srawlins

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
