### ISSUE TITLE
Observatory metrics page does not show graph

### ISSUE THREAD

**Issue by maks** [dart-lang/sdk#44520]
Per the documentation for the Observatory I was expecting to [see a graph for Metrics](https://dart-lang.github.io/observatory/metrics.html).

But when i tried this with current dev channel sdk I don't see any graph, only a text value for my custom "Results" metric:

![image](https://user-images.githubusercontent.com/71999/102707803-2e39f080-42f2-11eb-9d63-2e70f763cc7c.png)

This is also the case for all the builtin metrics.

Im using:
```
dart --version
Dart SDK version: 2.12.0-133.0.dev (dev) (Unknown timestamp) on "linux_x64"
```

**Comment by bkonyi** [comment]
Sorry for the delay on this. It must have slipped under our radar :(

For anyone else who comes across this issue, unfortunately we no longer provide support for charts/graphs in Observatory as the graphing package we were using is no longer maintained. We're in the middle of migrating Observatory functionality to Dart DevTools, and we have an outstanding issue to surface `Metric`s there (see https://github.com/flutter/devtools/issues/3859).
