### ISSUE TITLE
The Dart Analyzer has terminated 

### ISSUE THREAD

**Issue by yx-mike** [dart-lang/sdk#44524]
Analyzer Feedback from VSCode

flutter doctor -v

`[✓] Flutter (Channel unknown, v1.17.0-4.0.pre.9, on Mac OS X 10.15.7 19H15, locale zh-Hans-CN)
    • Flutter version 1.17.0-4.0.pre.9 at /Users/yangxin02/Library/Flutter/1.17.0+vddev006/flutter
    • Framework revision 8258e6493d (8 weeks ago), 2020-10-27 15:47:39 +0800
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yangxin02/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /usr/libexec/java_home/bin/java
    ✗ Cannot execute /usr/libexec/java_home/bin/java to determine the version

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 6s • CB629FC5-40E1-438B-A8C7-E6E311A49426 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)`

[log.txt](https://github.com/dart-lang/sdk/files/5723513/log.txt)

**Comment by srawlins** [comment]
Looking at the log, the only useful text is the following:

```none
[4:59:09 PM] [Analyzer] [Error] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
[4:59:09 PM] [Analyzer] [Info] Process terminated! 255, null
```

Sorry we didn't get to addressing this issue. I'm closing this issue for now, but if you can reproduce on a recent version of Dart, please re-open.
