### ISSUE TITLE
Flutter hot reload on certain files crashes Dart compiler

### ISSUE THREAD

**Issue by shihaohong** [dart-lang/sdk#44523]
## Description

I ran into a situation where a Flutter app would build and run without any issues until hot reloading certain files that were changed.

First discovered when migrating the Flutter Gallery to make use of state restoration: https://github.com/flutter/gallery/pull/389. 

This also only happens upon hot reload involves changed Dart files containing the class that extends `RestorableListenable`. The sample app only has one Dart file, but in the gallery app, this is more apparent since changes to files that do not contain the extended `RestorableListenable` class do not trigger the crash.

This issue was originally discovered while migrating the Reply and Shrine mini apps to use state restoration, both of which use state management packages (provider and scoped_model).

## Steps to Reproduce

Reproducible sample: https://github.com/shihaohong/state_restoration_provider_crash

Steps to reproduce: 
1. Run the Flutter application
2. Make any changes to the code containing the `_RestorableCounterState` class in the IDE (ie. adding spaces after a line of code) and save
3. Hot Reload and the Dart compiler crashes

Stack trace:
```bash
Unhandled exception:
root::package:hot_reload_crash/main.dart::_RestorableCounterState::@methods::package:flutter/src/widgets/restoration.dart::_debugAssertNotDisposed is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:192:7)
#1      Class.computeCanonicalNames (package:kernel/ast.dart:1201:51)
#2      Library.computeCanonicalNames (package:kernel/ast.dart:559:14)
#3      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:10821:13)
#4      Component.computeCanonicalNames (package:kernel/ast.dart:10783:7)
#5      sortComponent (package:vm/kernel_front_end.dart:679:13)

#6      FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:656:5)
#7      FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:766:13)
```

**Comment by johnniwinther** [comment]
I guess this is the same issue as https://github.com/flutter/flutter/issues/72700, right?

**Comment by shihaohong** [comment]
It is -- I filed an issue both here and there because at the time I wasn't sure if it was a Dart or Flutter issue

**Comment by jensjoha** [comment]
I can't reproduce. What version (commit) of flutter did this happen on?

**Comment by jensjoha** [comment]
Scratch that. When I said `flutter run` it did a web-version (which does other things with mixins) and it didn't reproduce. Specifying linux and I can reproduce (I suppose android/ios would also 'work' (i.e. crash)). I'll investigate!
