### ISSUE TITLE
js-interop: generate optimal code for js_util methods

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#44533]
We'd like to generate compact and efficient code for `js_util.getProperty`, `js_util.setProperty`, `js_util.callConstructor`, and `js_util.callMethod`  whenever possible.

We believe we can recognize certain patterns and apply a kernel transformation to lower them to more efficient inlined code. For example:

```dart
get T name => js_util.getProperty(x, 'name')
```

could be compiled to:
```dart
get T name => foreign_helper.JS<T>('', '#.#', x, 'name')
```

This may be done in a few steps:
* [ ] make all these js_util methods generic, so that the CFE can infer the return type. This may be handy since for dart2js it is useful to have a bound on the return type of JS foreign functions.
* [ ] run a kernel transformation that replaces the js-util expression with a new simpler expression. The simpler expression will:
  * detect patterns that can be simplified. We need to be able to recognize:
    * the name of the member (it should be a constant string)
    * the arguments in the case of a method or constructor (it needs to be an inline array literal)
    * the return type (it needs to be non-dynamic, otherwise it may affect tree-shaking in dart2js)
    
  * import directly the "foreign helper" JS (defined in `dart:_foreign_helper`), which is not exposed to external users
  * replace the expression with a call node, using the appropriate type in the `JS` type parameter.

**Comment by franklinyow** [comment]
@sigmundch This probably need a milestone if this is a P1

**Comment by franklinyow** [comment]
Is this still a P1 issue? Any update?

**Comment by sigmundch** [comment]
P1 in our internal prioritization (the sense that we are actively working on it), but not a release blocker. We'll move it to the next milestone if we come close to the cut date.

**Comment by rileyporter** [comment]
After adding the js_util optimizations, we can probably clean up some code in dart2js that used to handle the optimizations. Needs some investigation to determine how much code we can clean up.

**Comment by jodinathan** [comment]
is this in 2.15?

**Comment by kevmoo** [comment]
I *think* so – it's in the changelog. @rileyporter ? @sigmundch ?

**Comment by sigmundch** [comment]
Indeed - @rileyporter landed support for lowering the js-util methods mentioned above (getproperty, setproperty, callmethod, callconstructor) a few weeks back and the changes are expected to be part of the 2.15.0 stable release.

A couple quick notes:
* Some js-util methods are not optimized at the moment (like `jsify`). Let us know if those become more relevant to you.
* The end goal is the same, but the implementation was different than what was described in the original description above. When using DDC for development, you will still notice the indirection of js-util calls in the emitted code. However, that code is optimized away when using dart2js.

**Comment by rileyporter** [comment]
Yep, this is all submitted. :)

Making the `js_util` methods generic caused some issues with the flutter analyzer and dart linter, but it is fully rolled now. This isn't a breaking change, but it allowed the analyzer to identify more `implicit-dynamic` cases, which caused the analyzer to trigger and break the flutter analyzer bots. We added the note about the generic return type to the changelog as a reference in case users hit similar issues with their analyzer usage.

I'll close this bug to reflect that the work we planned here is done and you can re-open it if you need it open for tracking.

**Comment by jodinathan** [comment]
> I _think_ so – it's in the changelog. @rileyporter ? @sigmundch ?

do you mean this "The js_util methods getProperty, setProperty, callMethod, callConstructor, and newObject now support a generic type argument to specify the return type." ?  

I guess we could add a bit more of info in the changelog as this seems a reasonable change in the js_util.  
From what I understand the methods will be a lot lighter than the current state thus allowing more JS packages to rely on it.

**Comment by rileyporter** [comment]
That's true, I'll add more to the changelog highlighting the optimizations.
