### ISSUE TITLE
dart-lang/http - Header injection and path forgery [Security Issue]

### ISSUE THREAD

**Issue by n0npax** [dart-lang/sdk#44539]
### This tracker is for issues related to:
Dart core liblaries ->  'package:http/http.dart' == `dart-lang/http`

### If you aren't sure, file the issue here and we'll find the right home for it.
I've created an issue on https://github.com/dart-lang/http/issues/511 but I'm not sure if this repo is a better place.

### In your issue, please include:
I've tested this using:
* Dart SDK Version (`dart --version`)
```bash
Dart SDK version: 2.12.0-133.2.beta (beta) (Unknown timestamp) on "linux_x64"
Dart SDK version: 2.10.4 (stable) (Unknown timestamp) on "linux_x64"
```
* Whether you are using Windows, MacOSX, or Linux (if applicable)
```
2.12.0 Linux
2.10.4 Mac & Linux
```

Full description:
https://github.com/dart-lang/http/issues/511

**Comment by srawlins** [comment]
The issue at dart-lang/http#511 is just fine. Thanks for reporting.
