### ISSUE TITLE
Execution stops without any warning or error

### ISSUE THREAD

**Issue by MohiuddinM** [dart-lang/sdk#44536]
Execution of the program stops, when assigning a value of one type to a variable of another type, in a constructor.

```
class T {
  final int i;

  T.fromJson(Map<String, dynamic> json) : i = json['i'];
}

void main() {
  final a = {'i': 0};
  final b = {'i': 'null'};

  final good = T.fromJson(a);
  print('good done = $good');
  final bad = T.fromJson(b);
  print('bad done = $bad');
}
```

In the above example, execution stops at `final bad = T.fromJson(b);`, and the last line in never printed. Also, no error is ever shown.

Tested on **Dart SDK 2.10.4** on https://dartpad.dev/

**Comment by srawlins** [comment]
I see an error printed to the console:

![7CbSuMjMHeBmVi2](https://user-images.githubusercontent.com/103167/103099461-6deb2b80-45c3-11eb-8f97-c03149a18f45.png)

**Comment by MohiuddinM** [comment]
How are you running the code? I am running dartpad with `Flutter 1.23.0-18.1.pre Dart SDK 2.10.4` and do not see any error. The same is the case when I run the code in a local flutter application!

**Comment by MohiuddinM** [comment]
This is weird, on Firefox and on Flutter application no error gets printed. But I just tried it on Chrome and I see the same error as you.

**Comment by srawlins** [comment]
Ooh, that's not good. ☹️ . I'm going to pass this to the Dartdev team, but I suppose it could still be a dart2js issue...

**Comment by sigmundch** [comment]
mmm, that's odd.

@MohiuddinM - we will need some additional help to repro this locally. I tried dartdev with the same version in firefox and I also saw the error displayed in that case. When using a flutter dartdev example, the error also shows, but in a more obscure way (it simply says "script error"). Is it possible that the error is being caught by the framework code and not surfaced properly?

**Comment by MohiuddinM** [comment]
Last time I tried on Firefox, it didn't print anything. But now it prints the error twice, on Chrome the behavior is the same from @srawlins picture.

![error](https://user-images.githubusercontent.com/5729291/103247155-359e7100-4966-11eb-816e-11eef0a1ada7.png)

**Comment by MohiuddinM** [comment]
@sigmundch I have just tested using Flutter on DartPad and I would say its quite shaky. Sometimes it prints the "script error", sometimes it just stops the executions without an error.

I have written some Flutter code where it stops without any error:
```
import 'package:flutter/material.dart';

class T {
  final int i;

  T.fromJson(Map<String, dynamic> json) : i = json['i'];
}

void main() {
  final a = {'i': 0};
  final b = {'i': 'null'};

  final good = T.fromJson(a);
  print('good done = $good');
  final bad = T.fromJson(b);
  print('bad done = $bad');
  
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        builder: (_, __) {
          return Container(color: Colors.red);
        });
  }
}
```

**Comment by sigmundch** [comment]
very strange indeed - thanks for your patience helping us try to isolate what's wrong.

I'm starting to think the issue here may be more on the dartpad side of things. @redbrogdon - Any thoughts?

**Comment by RedBrogdon** [comment]
This looks like a DartPad issue. There was a (necessary) change in how we bootstrap the user's code a while back, and it's caused DartPad to fail to report some errors properly to the console.

I'll reference this issue in our existing bug report, but you can probably close this one.

**Comment by sigmundch** [comment]
Thanks @RedBrogdon!

**Comment by MohiuddinM** [comment]
@RedBrogdon I do not think its only a dartpad issue. Originally I encountered this error while developing a Flutter application on Stable channel.
