### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by jafar260698** [dart-lang/sdk#44549]
## Version information

- `IDEA AI-201.8743.12.41.6858069`
- `2.10.3`
- `AI-201.8743.12.41.6858069, JRE 1.8.0_242-release-1644-b3-6222593x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-123-generic, screens 1366x768, 1024x768`

**Comment by srawlins** [comment]
Please re-open if you find any more details. This report as it is contains no information.
