### ISSUE TITLE
toStringAsFixed rounds incorrectly

### ISSUE THREAD

**Issue by vi-k** [dart-lang/sdk#44552]
1.005.toStringAsFixed(2) -> 1.00

**Comment by tatumizer** [comment]
The value 1.005 cannot be exactly represented as double. Internal representation turns to be indeed closer to 1.00 than to 1.01:
print(1.005.toStringAsFixed(20)); // 1.00499999999999989342

**Comment by vi-k** [comment]
I know. I've been programming in Microsoft JScript. Its toFixed returned 1.01. But Chrome's toFixed returns 1.00. And Python's "{:.2f}" returns 1.00 too. This is unusual for me.

**Comment by srawlins** [comment]
Dart's will also continue to return 1.00.
