### ISSUE TITLE
Dart does not recognise nullable value in extension at runtime 

### ISSUE THREAD

**Issue by javiermrz** [dart-lang/sdk#44558]
The problem is pretty straightforward. I have the following extension: 
```dart
extension NullableListExtension on List<dynamic>? {
  String getOrEmptyString(int index) =>
      this == null || index >= this!.length ? "" : this![index]!.toString();
}
```

When editing, compiler shows no error. However, the following warning appears at runtime:
```
Warning: Operand of null-aware operation '!' has type 'List<dynamic>' which excludes null.
 - 'List' is from 'dart:core'.
      this == null || index >= this!.length ? "" : this![index];
```
(With `^` symbol pointing to the exclamation in `this![index]`).
But if I actually were to remove the `!` from the `this![index]`, it would ask me to introduce the symbol again (which I think is the correct thing to do).

**Comment by lrhn** [comment]
I never remember whether we can promote `this` or not, but in either case we should be consistent.

(Also, the code won't work because the empty string is not assignable to `T`).

**Comment by javiermrz** [comment]
@Irhn yep, that was an error of my own, thanks for pointing it out, instead of `T` there should be a `String` there, I will update that. However, the error still persists.

I don't know if `this` can be promoted either, but when adding the `!` the compiler seems to be happy (not at runtime though).

**Comment by tatumizer** [comment]
It's easy to verify that the reason is the lack of promotion of `this`. After a trivial modification, the error is gone:
```dart
extension NullableListExtension on List<dynamic>? {
  String getOrEmptyString(int index) {
     var self = this;
     return self == null || index >= self.length ? "" : self[index].toString();
  }  
}
```

**Comment by javiermrz** [comment]
You are right, the error is gone, thanks. Shouldn't the compiler show an error warning the developer about this?

**Comment by leafpetersen** [comment]
I believe that there is a known issue where the analyzer incorrectly promotes `this` only in extension methods (it is specified never to promote).  I can't find the issue we discussed this in at the moment.  We had considered fixing this forward by making `this` promotable everywhere, but this looked to be too long of an arc of work in the CFE, so for the time being this is a known errata.  cc @scheglov @johnniwinther 

Related:

https://github.com/dart-lang/sdk/issues/39959
https://github.com/dart-lang/sdk/issues/32120

**Comment by javiermrz** [comment]
Great then. Thanks all for your fast answers, I'll close this issue as everything was solved. Happy Holidays :)

**Comment by scheglov** [comment]
@leafpetersen actually, it worked in the CFE, and required some additional work in the analyzer. IIRC, I prototyped a solution for the analyzer, but at the end we decided that we don't want such promotion. It seems that in the CFE promotion still works though.

**Comment by leafpetersen** [comment]
@scheglov I'm probably misremembering details.  I'm pretty sure that we do want the promotion, but decided that the implementation cost was too high somewhere to do it now (perhaps the CFE only promotes `this` in extensions, and making it do so in classes was going to be hard?).

**Comment by scheglov** [comment]
Ah, yes, it is quite possible that `this` promotion in CFE works only in extensions because it has an artificial variable for `this` in extensions.
