### ISSUE TITLE
dart2native doesn't support --no-sound-null-safety

### ISSUE THREAD

**Issue by Timmmm** [dart-lang/sdk#44553]
Using `dart2native` 2.12.0-133.2.beta on "mixed" null safe code I get the following error:

```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:async
 - package:stream_transform
 - package:path
 - package:crypto
 - package:collection
 - package:convert
 - package:typed_data
 - package:charcode

For solutions, see https://dart.dev/go/unsound-null-safety
```

That page mentions `--no-sound-null-safety` which sounds like exactly what I want, however it isn't a valid parameter to `dart2native`. So there's no way to compile my code with `dart2native`.

**Comment by lslv1243** [comment]
The same problem is happening to me while trying to use `dart compile exe`, when I try to use the flag `--no-sound-null-safety` it does not work
