### ISSUE TITLE
Unify syntax to define environment declarations (`--define`)

### ISSUE THREAD

**Issue by Mabsten** [dart-lang/sdk#44562]
The syntax to define environment declarations (to read with [`String.fromEnvironment()`](https://api.dart.dev/stable/2.10.4/dart-core/String/String.fromEnvironment.html) method and relateds) is very divergent between the various tools/dart sub-commands:
(I tested the flags with Dart Sdk 2.12 (2.12.0-133.2.beta, on Windows x64))

**`dart2native`** /  **`dart compile exe`**
use the `-D`/`--define` flag
(cfr https://dart.dev/tools/dart2native );

**~~`dart`~~** / `dart run`
does not support the define flags
UPDATE:
**`dart`**
supports the -D flag (also `dart -D run` is ok)
although it is not mentioned in the help and in the doc
(cfr https://dart.dev/tools/dart-vm );

**`dart2js`**
use only the `-D` flag;
(cfr https://dart.dev/tools/dart2js#options );

**`dart compile js`**
does not even support the `-D` flag, despite it being the substitute of the `dart2js` command (I think);

**`dartdevc`** -using **`webdev`**-
require to use a build.yaml file or this command-line syntax (not tested):
`webdev serve -- '--define=build_web_compilers:ddc=environment={"SOME_VAR":"some_value"}'`
(cfr https://dart.dev/tools/webdev and https://pub.dev/packages/build_web_compilers );

**flutter** (from the Sdk 1.17)
use the `--dart-define` flag.
The `--dart-define` flag is very useful in Flutter, for example to set a log level or an api token.

Wouldn't it be useful if all the sub-commands of the new dart tool supported the define flag? Or maybe I'm missing an alternative that already exists?

**Comment by srawlins** [comment]
I'll initially tag this as dart-cli; @devoncarew is there a plan to unify this flag?

**Comment by bkonyi** [comment]
There should be an effort to make this more consistent, and it's definitely an oversight that `dart run -D` isn't valid. At the very least, we should make sure that `-D` is accepted by the relevant commands (e.g., `run`, `compile`, `test`).

**Comment by bkonyi** [comment]
@sigmundch can you or someone else take a look at the `dart compile js` case?

**Comment by Mabsten** [comment]
Thank you for the attention and for the tip about `dart -D`, I didn't know that (it was not mentioned in the help); then the `-D` flag is available for all the old tools, except dartdevc/webdev (which however supports the build.yaml approach).

This flag is very important in the build pipeline because it provides (in pair with `fromEnvironment()`) an equivalent of BuildConfig fields in the Android (Gradle) development and of environment variables in the Node/Javascript build pipeline (I think to Js package to inline env vars like [envify](https://www.npmjs.com/package/envify)).

That the need for such a mechanism is strongly felt in the Dart community is testified by the multitude of related issues opened (as [Please document {String|int|bool}.fromEnvironment](https://github.com/dart-lang/site-www/issues/404#)) and of Dart packages that try to emulate it in various ways (with code generation, multiple entry point files, etc.), but all with severe drawbacks (i.e. [dotenv](https://pub.dev/packages/dotenv), flutter_dotenv, envify, dynamic_config_generator, flutter_config, env_vars, dotenv2dart, etc).
Dart's *environment declarations*, now that they are also supported in flutter, can replace all previous workarounds.
It would be great if with the introduction of the new general-purpouse `dart` tool the syntax were unified, in order to make `-D` similar to `--dart-define` in `flutter run` and `flutter build`.

**Comment by Mabsten** [comment]
Another syntax-related issue concerns **comma** support:

**`dart2js` and `dart` (VM tool)**
allow to insert the comma in an environment declaration value, using the quotes.

**`dart2native` and `dart compile exe` (as `flutter`)**
doesn't allow to insert the comma, not even using the quotes.
This has already been [reported](https://github.com/flutter/flutter/issues/72105) for the flutter tool.
`dart2native` and `dart compile exe` (as `flutter`) on the other hand allow the definition of many variables without repeating the flag, using the comma: example: `dart compile exe --dart-define=MY_VAR1="first value",MY_VAR2="second value"`.

Reproducible test:

```
//main.dart

void main() {
  const my_var = String.fromEnvironment("my_var", defaultValue: "not found");
  print("my_var: $my_var");
}
```

Compile the source with:
`dart -Dmy_var="first value,second value" main.dart`
`dart2js -Dmy_var="first value,second value" main.dart`
`dart2native -Dmy_var="first value,second value" main.dart`
`dart compile exe -Dmy_var="first value,second value" main.dart`

Output using `dart` and `dartsjs`:
```
my_var: first value,second value
```

Output using `dart2native` and `dart compile exe`:
```
my_var: first value
```

**Comment by bkonyi** [comment]
Closing this issue as --define support has been improved across all tools. Filed #44995 for the issue described by @Mabsten above.

**Comment by jodinathan** [comment]
how to add environment variables to `dart run` to start a VM console app?

this works: `dart -Dconsole=true bin/pagebuilder_api.dart`

this doesn't: `dart -Dconsole=true run -Dconsole=true`

**Comment by pak3nuh** [comment]
I don't think the `define` flag is supported across all commands evenly. I'm using dart SDK 2.19 and the `test` command doesn't respect the flag. For it to work, I need to run each test file individually with the `run` command.

Is this happening to anyone else?

**Comment by bkonyi** [comment]
@pak3nuh would you mind filing a new issue? This one has been closed for quite awhile.

**Comment by pak3nuh** [comment]
Sure. Created issue #51791
