### ISSUE TITLE
Dart Analyzer output result format

### ISSUE THREAD

**Issue by fartem** [dart-lang/sdk#44576]
Hi. It is possible to create Dart Analyzer report in JSON or other standard format? Default console utility (`dart analyze`) cannot format output to structured format.

**Comment by bwilkerson** [comment]
There's a `--format=machine` that provides a machine readable format. I don't know whether that format would meet your needs.

@devoncarew

**Comment by fartem** [comment]
@bwilkerson `--format=machine` cannot support by Dart Analyzer (I'm trying call `dart analyze --format=machine`).

**Comment by devoncarew** [comment]
`dart analyze` does support this option but likely just in dev channel versions currently. The option should be available in the next beta and stable versions of the SDK.

**Comment by fartem** [comment]
@devoncarew Thanks. What is difference between calling `dart analyze` and `dartanalyzer`?

**Comment by devoncarew** [comment]
`dartanalyzer` is our original command line analysis tool. `dart analyze` is a subcommand of the new combined `dart` tool. It supports an updated command-line interface. In the fullness of time we'll deprecate dartanalyze in favor of `dart analyze` (and eventually remove the older tool).

**Comment by devoncarew** [comment]
Closing this as `dart analyze` now supports a --format=machine format. There's some discussion in https://github.com/dart-lang/sdk/issues/44905 about adding a JSON format as well.
