### ISSUE TITLE
bug in list

### ISSUE THREAD

**Issue by Xstar97** [dart-lang/sdk#44579]
flutter doctor:
 Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale
    en-US)

ide: android studio, jetbrains/toolbox ver 4.1.1

issue: i declare 2 list in my project the init list with "blank" data and the actual list that I manipulate.

for some odd reason i been seeing a weird bug whenever i try to reset the actual list  with the initial list when declaring the list in a variable like below, but it modifies the initial list, which is not suppose to do.

i verified multiple times that the code isnt suppose to change the initial list and only referenced once in the replacerange function to take the data and copy over the main list.

class CustomModel
{
String string;
bool bool1, bool2;

CustomModel(this.string1, this.bool1, this.bool2);
}

var initList= <CustomModel>[
    CustomModel("1", false, false),
    CustomModel("2", false, false),
    CustomModel("3", false, false),
    CustomModel("4", false, false),
    CustomModel("5", false, false),
    CustomModel("6", false, false),
    CustomModel("7", false, false),
    CustomModel("8", false, false),
    CustomModel("9", false, false)
  ];
var mList = <CustomModel>[
    CustomModel("1", false, false),
    CustomModel("2", false, false),
    CustomModel("3", false, false),
    CustomModel("4", false, false),
    CustomModel("5", false, false),
    CustomModel("6", false, false),
    CustomModel("7", false, false),
    CustomModel("8", false, false),
    CustomModel("9", false, false)
  ];

these methods were called when the logic has ended and needs to be reset.
method 1
mList.clear();
mlist.addAll(initialList);
failed

method 2
mList = initialList();
failed
method 3
moveList.replaceRange(0, mList.length, initialList);
failed

the only solution that work was to not declare the initial list as variable but add the data directly shown below:

moveList.replaceRange(0, mList.length, <CustomModel>[
    CustomModel("1", false, false),
    CustomModel("2", false, false),
    CustomModel("3", false, false),
    CustomModel("4", false, false),
    CustomModel("5", false, false),
    CustomModel("6", false, false),
    CustomModel("7", false, false),
    CustomModel("8", false, false),
    CustomModel("9", false, false)
  ]);
worked!

my code worked before when it was mixed with the ui, but i separated the logic and view code into separate files.

my main thing here is i wanted to declare an initial list into a variable that will be used to reset the actual list because of user/logic action.

**Comment by julemand101** [comment]
What do you mean by "failed"? Are there some stacktrace? I have tried to the following and do not see any problem?
```
class CustomModel {
  String string;
  bool bool1, bool2;

  CustomModel(this.string, this.bool1, this.bool2);
}

var initList = [
  CustomModel("1", false, false),
  CustomModel("2", false, false),
  CustomModel("3", false, false),
  CustomModel("4", false, false),
  CustomModel("5", false, false),
  CustomModel("6", false, false),
  CustomModel("7", false, false),
  CustomModel("8", false, false),
  CustomModel("9", false, false)
];
var mList = [
  CustomModel("1", false, false),
  CustomModel("2", false, false),
  CustomModel("3", false, false),
  CustomModel("4", false, false),
  CustomModel("5", false, false),
  CustomModel("6", false, false),
  CustomModel("7", false, false),
  CustomModel("8", false, false),
  CustomModel("9", false, false)
];

void main() {
  mList.clear();
  mList.addAll(initList);
}
```

**Comment by Xstar97** [comment]
I updated everything,  reset everything,  seems to work without issue now... i was probably having issues with the syntax lang missing : somewhere or something,  will close it now, sorry.
