### ISSUE TITLE
Dart Analyze error on Pointer<NativeFunction>

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#44584]
In recent builds, `dart analyze` throws a error at FFI parameters declared as `Pointer<NativeFunction>` or `Pointer<Void>`:
```
  error • The type 'Int32 Function(Pointer<NativeFunction<Function>>, IntPtr)' given to 'lookupFunction' must be a valid 'dart:ffi' native function type at test\api_test.dart:1886:11 • (must_be_a_native_function_type)
```

This is either a regression or a breaking change.

The code itself continues to run successfully, as far as I can tell.

## Repro
Open https://github.com/timsneath/win32 in Visual Studio Code with LSP mode enabled. 

## Dart Version
```
[C:\src\win32] dart --version
Dart SDK version: 2.12.0-179.0.dev (dev) (Wed Dec 23 21:08:22 2020 -0800) on "windows_x64"
```

**Comment by devoncarew** [comment]
I'm assuming this is an issue the the `must_be_a_native_function_type` hint logic.

**Comment by dcharkes** [comment]
3e7cda8a4ebd3a7f3dfa6fc3505b790b969a1d81 and b6b82dd3ac756b39e7fe9cab21f060fae74e358d touched `ffi_verifier.dart`, both are included in `2.12.0-179.0.dev`.  I'll take a look.

**Comment by dcharkes** [comment]
```dart
typedef _Read_Native = Int32 Function(
    Pointer obj, Pointer<void> pv, Uint32 cb, Pointer<Uint32> pcbRead);
typedef _Read_Dart = int Function(
    Pointer obj, Pointer<void> pv, int cb, Pointer<Uint32> pcbRead);
```

The error is using `Pointer<void>` rather than `Pointer<Void>` in for example lib/src/generated/ISequentialStream.dart.

This one is kind of hard to spot.

And, the CFE does not catch this one.

====

Whether `Pointer<NativeFunction>` should work, I don't know. I've filed https://github.com/dart-lang/sdk/issues/44594 to discuss that.

Also here the behavior of the analyzer and CFE are not consistent.

**Comment by timsneath** [comment]
Doh! Yeah, the `Pointer<void>` is clearly my mistake, as you rightly note. A typo on my part in some generated code for a COM interface that I don't use. Fixed and added an issue to test scenarios like this in the future.

Added a comment on the other bug with a motivating use case for `Pointer<NativeFunction>`. Thanks!

Closing this bug on the assumption that #44593 and #44594 cover all the cases enumerated here.

**Comment by office1-themedev** [comment]
`class User32 {
  static final ffi.DynamicLibrary user32 = ffi.DynamicLibrary.open('user32.dll');

  static ffi.IntPtr GetForegroundWindow() {
    return user32.lookupFunction<ffi.IntPtr Function(), ffi.IntPtr Function()>('GetForegroundWindow')();
  }
}`

This shows `The type 'IntPtr Function()' must be a subtype of 'IntPtr Function()' for 'lookupFunction'` 
Any solution? Please

**Comment by office1-themedev** [comment]
```dart
class User32 {
  static final ffi.DynamicLibrary user32 = ffi.DynamicLibrary.open('user32.dll');

  static ffi.IntPtr GetForegroundWindow() {
    return user32.lookupFunction<ffi.IntPtr Function(), ffi.IntPtr Function()>('GetForegroundWindow')();
  }
}
``` 
This code shows `The type 'IntPtr Function()' must be a subtype of 'IntPtr Function()' for 'lookupFunction'.`
Any solution? Please
