### ISSUE TITLE
Failures on Test for avoiding exponential tree traversal of DAG constants...[vm/ffi] Document marking struct fields as external

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#44592]
There are new test failures on [Test for avoiding exponential tree traversal of DAG constants...[vm/ffi] Document marking struct fields as external](https://github.com/dart-lang/sdk/compare/0d7cdcbcce127e98da314104854b9a66503697e9~...cd2258572de9feeacc423eaaddf62cf5ff69e3b9).

The tests
```
standalone_2/io/socket_close_test/0 Crash (expected Pass)
```
are failing on configurations
```
dartk-tsan-linux-release-x64
```

Log is [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8858881507489855280/+/steps/test_results/0/logs/new_test_failures__logs_/0). The `/0` version of this test is with --enable-isolate-groups.

/cc @mkustermann

**Comment by mkustermann** [comment]
This failure is flaky and unrelated to the CL. It happens for the multitest that opt-in via `--enable-isolate-groups` in JIT mode (which is still under development).

**Comment by mkustermann** [comment]
This is unrelated to `--enable-isolate-groups` per se, it's already tracked here: https://github.com/dart-lang/sdk/issues/45641
