### ISSUE TITLE
Front-end doesn't implement new number operation typing rules completely.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44595]
Example:
```dart
import "dart:async";
T id<T>(T value) => value;

main() async {
  FutureOr<int> x = 1 + id(1);  // Should work, gives error.
  
  // Checking it!
  FutureOr<int> y = 1 + id(1)..checkStaticType<Exactly<int>>();
  FutureOr<int> z = 1 + contextType(1)..checkStaticType<Exactly<int>>();
}

extension <T> on T {
  void checkStaticType<R extends Exactly<T>>() {}
}
typedef Exactly<T> = T Function(T);
T contextType<T>(Object? o) => o as T;
```

When compiling this in `nullsafety.dartpad.dev`, there is a type error at `1 + id(1)`. It appears the context type of `id(1)` is `num`, not `int` as required by the ["new number typing"](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/number-operation-typing.md#improved-context-type).

This only appears to happen when the context type of the `+` expression is `FutureOr<int>` (and likely any number of `FutureOr<FutureOr<...<int>...>>`s). It works correctly if the context type is `int`.

The analyzer does not give any warnings or errors (except unused variables).

When I add the `..checkStaticType<Exactly<int>>()` above, the front end complains, and if I change it to `Exactly<num>`, it stops complaining, so the type is definitely `num`. Ditto for checking the context type (the `contextType` function captures the context type and makes it the static type of the expression).  That error looks curious, though, because it refers to the type variable of `contextType`, not its value.

**Comment by dskloetg** [comment]
Do you know in what sort of time frame I can expect the fix to be available in google3?

**Comment by srawlins** [comment]
I think within a day or two. Rolls are happening approximately daily again.
