### ISSUE TITLE
Range for diagnostic extra_positional_arguments_could_be_named seems much larger than it needs to be

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44598]
I [saw this on Reddit](https://www.reddit.com/r/vscode/comments/kn274o/multiple_red_lines_while_typing_code_in_flutter/). Flutter code that has a partially-typed named parameter generates a red squiggle under a lot of code:

<img width="681" alt="Screenshot 2021-01-06 at 15 40 06" src="https://user-images.githubusercontent.com/1078012/103787437-7ae13380-5035-11eb-948b-880a21d39e86.png">

It's very distracting while typing, and it seems like the range is covering much more than is necessary (or useful). I would expect only the arguments that are "extra" (in this case, just `ke`) to be included in the diagnostic range.

Before LSP, this wouldn't be seen in VS Code as we would (accidentally) truncate diagnostic ranges to a single line when converting from offset/len to line/col. We could do the same again with some LSP middleware, though since Android Studio shows the same (albeit with less contrast in my theme) I wonder if it would make sense changing here.

@bwilkerson I'm happy to try to change this if it seems like a reasonable change (I'm not sure if there are good reasons for it to work this way though).

**Comment by bwilkerson** [comment]
I agree, the highlighting range here is not helpful. I agree that we should either highlight the positional arguments that don't correspond to a positional parameter, or possibly even just the first such argument, as it's probably clear to the user that the following arguments would also be included.

The code that would need to be updated is in `pkg/analyzer/lib/src/generated/resolver.dart` on line 2305. There are several tests that will likely also need to be updated to have different expectations for which range of characters is highlighted.

**Comment by DanTup** [comment]
@bwilkerson thanks! Changing the node that was used for the error also breaks some additional tests related to quick-fixes, for example the `AddMissingParameter` fix test. [It expects](https://github.com/dart-lang/sdk/blob/d63d5d93a59b370bf5f5c277109110cb67a96b75/pkg/analysis_server/lib/src/services/correction/dart/add_missing_parameter.dart#L15) `node` to be the `ArgumentList` whereas now it's the first unmatched argument. Fixing that check is easy, but the other classes also read `node` and expect the same.

Some ideas:

- update them all to assume the `node` is an argument rather than the argument list
- add the `ArgumentList` to `ExecutableParameters` and use it from there (instead of `node`) in the fixes

Or is there a better way?

Thanks!

**Comment by bwilkerson** [comment]
Interesting. I hadn't thought about the impact on fixes.

> update them all to assume the `node` is an argument rather than the argument list

I don't know how many other places we'd need to update, so it's hard to evaluate this option.

> add the `ArgumentList` to `ExecutableParameters` and use it from there (instead of `node`) in the fixes

That seems wrong to me because the class is explicitly holding information about the element being invoked rather than the invocation site.

> Or is there a better way?

I'm not thinking of one at the moment.

**Comment by DanTup** [comment]
> I don't know how many other places we'd need to update, so it's hard to evaluate this option.

I went through the failures and added fixes here - some fixes are used for multiple error codes so could now get either an ArgumentList or an expression from within. There weren't many changes, though I'm not sure if it's a bit weird:

https://github.com/DanTup/sdk/commit/36707fb0e31681a5fad87be89ff25146b30b8e97

There was one test I wasn't able to understand why it fails though:

> 02:46 [32m+8870[0m[33m ~10[0m[31m -1[0m: analysis_server | src | services | correction | fix | EndToEndTest | test_removeParameter [1m[31m[E][0m[0m

(with my change, it didn't seem to get into the fix code, but I'm not very familiar with how the data driven fixes work)

> That seems wrong to me because the class is explicitly holding information about the element being invoked rather than the invocation site.

Ah yes - I'd seen `AstNode invocation` in the constructor, but it's just used to get the element being invoked. I agree that doesn't seem to make sense.

**Comment by bwilkerson** [comment]
Like other fixes, the data-driven fixes validate that the diagnostic is in a place that they know how to fix, but the code structure is a little different. In this case I believe that the code path that needs to be updated is in `pkg/analysis_server/lib/src/services/correction/fix/data_driven/modify_parameters.dart` in the function on line 230. Specifically, `fix.node` is the node that is now a single argument rather than being an argument list, so the `parent` is the argument list rather than the invocation expression. It's probably safest to just add another case: `else if (parent.parent is InvocationExpression) {` in order to avoid breaking other code paths that might be triggering this code with a different diagnostic and hence are still generating a node that _is_ an argument list. (You can add a TODO with my name if you want to verify whether the old code path is still being used.)

I also added a comment to your PR in case you didn't get notified.

**Comment by DanTup** [comment]
> In this case I believe that the code path that needs to be updated is in `pkg/analysis_server/lib/src/services/correction/fix/data_driven/modify_parameters.dart` in the function on line 230.

That's where I'd ended up, but that code wasn't executing with my change and I'd been struggling to understand why. I did some more digging this afternoon and found that the problem was that `Transform.appliesTo` was filtering it out because it no longer computer a `name` (`DataDriven._name`).

> I also added a comment to your PR in case you didn't get notified.

Got it, and changed it - thanks!

I fixed everything up and believe all the tests pass now (though I'm not certain if the changes all make sense or there may be edge cases I've missed):

https://dart-review.googlesource.com/c/sdk/+/178020/

<img width="989" alt="Screenshot 2021-01-07 at 18 14 00" src="https://user-images.githubusercontent.com/1078012/103928713-2496f200-5114-11eb-8c27-2978bed62492.png">

(there are three diagnostics generated which seems a lot, though I'm not sure there's much to do about that, as they all seem somewhat valid).

**Comment by bwilkerson** [comment]
It would be nice if it didn't complain about a positional argument being after named arguments when it clearly isn't a valid positional argument because there aren't enough positional parameters for it to be one. But that's a whole different issue.

Anyway, the CL looks good. Thanks!
