### ISSUE TITLE
Dart analyzer doesn't show error on `Platform.isAndroid` in const, which will be thrown when build app

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [dart-lang/sdk#44597]
# This tracker is for issues related to:
* Analyzer

# Environemt
* Dart SDK Version (`dart --version`)
`Dart SDK version: 2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "windows_x64"`
* Flutter
Flutter 1.25.0-8.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b0a2299859 (19 hours ago) • 2021-01-05 12:34:13 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)

# Issue
I have this code:

```
FirebaseFirestore.instance.settings = const Settings(
          host: !kIsWeb && Platform.isAndroid
              ? '10.0.2.2:9001'
              : 'localhost:9001',
          sslEnabled: false,
          persistenceEnabled: false,
        );
```

Dart analyzer doesn't show any error, but when I build the app to run on android emulator, I get this error:
`Context: The invocation of 'isAndroid' is not allowed in a constant expression.`

Web build still works.

**Comment by srawlins** [comment]
This appears to have been fixed, maybe last year with @kallentu's work. I cannot reproduce it, and there are many test cases in `evaluation_test` that seem to cover this.
