### ISSUE TITLE
[CP][beta channel] cherry pick a fix to OOM situations for IDE clients

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#44600]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/17b43ca84677781ade9d4da48d32d0ea950ea2e0 

**merge instructions**: clean merge

**What is the issue**: IntelliJ can run out of memory for users making heavy use of parts in their projects

**What is the fix**: The number of 'available declarations' - used for code completion - for libraries using parts would grow unbounded; this was causing IDEs to retain increasing numbers of available suggestions.

**Why cherrypick**: 
- this affects users of IntelliJ who use parts in their projects; their IDEs will crash with OOM errors
- we want to cherry pick as we want to get this fix to a more stable channel

**Risk**: low - the patch is small

**Link to original  issue(s)**:
- https://github.com/dart-lang/sdk/issues/44353
- https://github.com/flutter/flutter-intellij/issues/5108

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

--------

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by vsmenon** [comment]
lgtm.  does this only affect beta channel (and not stable)?

**Comment by devoncarew** [comment]
It effects both. I'm suggesting beta as we want at least one channel, more stable than master/dev, that we can recommend affected users switch to.

**Comment by scheglov** [comment]
Note also that there was a small mistake in tests, causing a failure on Windows bots.
It was fixed separately in abe144c30fdcdfba3573a36a59da5d0ac6e28c5f.

**Comment by franklinyow** [comment]
> Note also that there was a small mistake in tests, causing a failure on Windows bots.
> It was fixed separately in [abe144c](https://github.com/dart-lang/sdk/commit/abe144c30fdcdfba3573a36a59da5d0ac6e28c5f).

So we need to pick this test also to avoid Windows bots failure, correct?

**Comment by scheglov** [comment]
That would be ideal, yes.
I was just not sure if we run `analyzer-win-release`.
But to make everything right we need both.

**Comment by devoncarew** [comment]
We only need that second commit if we run the bots on the beta channel; otherwise, we just need the first commit.

**Comment by athomas** [comment]
We do run most configurations on the beta channel, see https://ci.chromium.org/p/dart/g/beta/console. However, a single test failure does not block a release unless we declare it a blocker. So from my we can go either way, but abe144c only affects a single test so the risk of picking it as well is near 0.

**Comment by franklinyow** [comment]
I'm marking this as approved
CC: @pcsosinski

**Comment by athomas** [comment]
Merged in 01bc1f5083950751261af2219b65df445ad8f83f (2.12.0-133.6.beta).
