### ISSUE TITLE
[CP][stable channel] Attach unboxing info to unreachable members

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44609]
**commit(s) to merge**: 3bef6cf639610ea542d7eb64b37d84289ab2899e

**merge instructions**: clean merge

**What is the issue**: https://github.com/dart-lang/sdk/issues/44563

**What is the fix**: Unreachable members could be used as interface targets of dispatch
table calls, so they should have correct unboxing metadata

**Why cherrypick**: The bug manifests as a core dump and could potentially happen in the field, the cost of evaluating crashes and root causing it is high, proactively fixing bugs that lead to crashes generally helps.

**Risk**: Low

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44563
https://github.com/wm17/flutter_switch_segfault

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
Approved in SCRUM meeting.

**Comment by franklinyow** [comment]
For changelog.md:
This is a patch release that fixes a condition that result in a crash in the VM.  (#44563 )

**Comment by athomas** [comment]
Merged to beta in 2b88e9de118097d12183aa30ec9f8c6bed9d64fc (2.12.0-133.7.beta).

Issue will remain open until merged to stable as well.

**Comment by athomas** [comment]
Merged to stable in 2ea318b540948b55306bf82fd34b2c84ec634f48 (2.10.5).
