### ISSUE TITLE
js-interop: accept rejecting promises with null in promiseToFuture 

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#44602]
The `promiseToFuture` API needs to adjust for the possible nullability of errors. 

Promises can be rejected with a null value, however `dart:async` expects errors to be non null. Elsewhere in Dart we wrap null errors with a `NullError` to comply with `dart:async`, so we expect something similar should be possible here.

small repro:
```dart
@JS()
library foo;

import 'package:js/js.dart';
import 'dart:js_util';

@JS('self.Promise.reject')
external reject(value);

main() {
  promiseToFuture(reject(null));
}
```

More convoluted repro showing how this can come up when rejecting a promise after it is created:
```dart
@JS()
library foo;

import 'package:js/js.dart';
import 'dart:js_util' show promiseToFuture;

@JS() external void eval(String s);
@JS() external void fulfill(v);
@JS() external void reject(v);
@JS() external dynamic get promise;

main() async {
  eval('''
      self.promise = new Promise(function (fulfill, reject) {
        self.fulfill = fulfill;
        self.reject = reject;
      });
      ''');
  Future f = promiseToFuture(promise)
      .then((_) => "1")
      .catchError((_) => "2");
  reject(null);
  print(await f);
}

```

See original report from flutter at: https://github.com/flutter/flutter/issues/73114

/cc @srujzs @rileyporter

**Comment by srujzs** [comment]
This would just be modifying the `error` wrapper to check for `null` and passing in a `NullError` instead to the completer, right? The `success` case would also need to be modified similarly.

**Comment by srujzs** [comment]
Yeah I think you're right, `complete` allows a nullable, so this only needs to be done for the `error` case.
