### ISSUE TITLE
double values with all-zero decimal part are represented as int instead of double

### ISSUE THREAD

**Issue by jolleekin** [dart-lang/sdk#44615]
```dart
void main() {
  // These statements print "int" instead of "double".
  print(123.0.runtimeType);
  print(123.toDouble().runtimeType);
  print((1.23 / 1.23).runtimeType);
  print(double.parse('123.0').runtimeType);
  print(double.parse('123.0e2').runtimeType);
  print(double.infinity.runtimeType);
  print(double.maxFinite.runtimeType);

  // These statements print "double" as expected.
  print(double.nan.runtimeType);
  print(double.minPositive.runtimeType);
  print(1.23.runtimeType);

  // These statements print "true" instead of "false".
  print(123 is double);
  print(123.0 is int);

  // Prints "123" instead of "123.0".
  print(123.0);
}
```

[Spec v2.2](https://dart.dev/guides/language/specifications/DartLangSpec-v2.2.pdf), page 83, says
> A double literal always contains either a decimal point or an exponent part.

* Dart SDK Version (`dart --version`): 2.10.4
* Whether you are using Windows, MacOSX, or Linux (if applicable): Windows
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): Edge

**Comment by eernstg** [comment]
This is working as intended.

The implementation of `int` and `double` on platforms where Dart is translated to JavaScript relies (for performance reasons) on the underlying JavaScript numbers. Check out 'Appendix: Integer Implementations' in [the current language specification](https://spec.dart.dev/DartLangSpecDraft.pdf), available from [here](https://dart.dev/guides/language/spec) as the 'in-progress specification'.
