### ISSUE TITLE
deprecate and remove standalone dartdoc tool

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#44610]
The dartdoc tool needs to be removed as a standalone tool in the SDK.

Checklist:

- [x] 2.16 - Add new `dart doc` command: https://dart-review.googlesource.com/c/sdk/+/220744
- [x] 2.16 - Add deprecation warning to `bin/dartdoc`: https://dart-review.googlesource.com/c/sdk/+/221948
- [ ] 2.17, beta 1 - Remove `bin/dartdoc`

---

Possible alternatives include:

~~1) Simply deprecating/deleting it and taking no further action, requiring users to use pub global activate dartdoc to install a package to document code.  This is a straightforward approach that matches with recommended best practice for using dartdoc.
2) Deprecating the standalone tool, and replacing it with a wrapper inside dartdev that uses pub global activate internally to install dartdoc, then pass dartdoc the command line parameters.~~
3) Deprecating the standalone tool, and replacing it with a full version of dartdoc linked into dartdev as a library.

2 and 3 look largely the same to the user, 2 being more fragile and requiring network access but also more compact for SDK size.

My inclination is to go with option 1, funneling all users to the pub package.
**edit**:   option 3 was chosen.

cc @mit-mit, @devoncarew, @bkonyi  for input

**Comment by jcollins-g** [comment]
Adding area-build as well since dartdoc-in-the-SDK's most important user is the SDK build system itself.

**Comment by mit-mit** [comment]
My preference is option 3, which is what we're doing for other tools (dartfmt, analyzer, pub). I really like the consistency of that.

Yes, that has the disadvantage that it becomes a bit harder to use bleeding edge versions of `dartdoc`, as you have to wait for a roll, but looking at the global activate stats, I see less than 100 activates of dartdoc a week, which is a very small fraction of our overall user base.

**Comment by bkonyi** [comment]
+1 to option 3. We're trying our best to stay consistent and embed tooling into dartdev when it makes sense to. However, option 2 would allow for us to dynamically install dartdoc which has the nice property of not using extra disk space for users that never run the tool, which I think was an original goal for the CLI unification effort. Is that something we'd still be interesting in doing @mit-mit or did we shelve the idea for some particular reason?

**Comment by jcollins-g** [comment]
+1 for consistency -- will go for option 3 then unless there's a strong reason to do otherwise.

**Comment by mit-mit** [comment]
> the nice property of not using extra disk space for users that never run the tool, which I think was an original goal for the CLI unification effort

Yes, that is correct, but that was more in the context of very large and rarely used features; say downloading an 100MB linker for building a custom embedder, og something like that.

**Comment by mit-mit** [comment]
@jcollins-g is there a known timeline for this deprecation?

**Comment by jcollins-g** [comment]
@mit-mit It is on the Q3 OKRs but not at a high priority (P2)

**Comment by mit-mit** [comment]
New CL in https://dart-review.googlesource.com/c/sdk/+/220744

**Comment by bkonyi** [comment]
The new changes LGTM. I'm assuming there's corresponding changes in dart-lang/dartdoc (maybe https://github.com/dart-lang/dartdoc/pull/2857?)

**Comment by mit-mit** [comment]
> I'm assuming there's corresponding changes in dart-lang/dartdoc

You, that issue you're linking needs to land first, then we'll roll dartdoc, and then my CL should work.

**Comment by mit-mit** [comment]
The new `dart doc` command was manually tested and confirmed working on Linux, macOS, and Windows with a bleeding edge build from http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/

**Comment by mit-mit** [comment]
Deprecation message was added in https://dart-review.googlesource.com/c/sdk/+/221948

**Comment by mit-mit** [comment]
Discontinuation in https://dart-review.googlesource.com/c/sdk/+/228647

**Comment by DanTup** [comment]
@mit-mit is it intended/expected that the input directory is mandatory using the new command (but wasn't before)?

```
danny@Dannys-MacBook-Pro hello_world % ~/Dev/Dart\ SDKs/stable/bin/dartdoc 
Documenting hello_world...
-^C

danny@Dannys-MacBook-Pro hello_world % ~/Dev/Dart\ SDKs/nightly/bin/dart doc
Error: Input directory not specified

Usage: dart doc [arguments] <input directory>
-h, --help                   Print this usage information.
-o, --output-dir             Output directory
                             (defaults to "doc/api")
    --[no-]validate-links    Display context aware warnings for broken links (slow)
```

I noticed this while moving VS Code over. It's no bother for me to pass `.` (esp. since that works with both old and new) although it's more to type when invoking manually and seems like it could be inferred?

**Comment by mit-mit** [comment]
Yes, that is intentional. It was something we discussed a bit back and forth, and agreed to require given the command has a side effect that it changes the input directory (by writing a lot if files to it). This is consistent with the `dart format` command.
