### ISSUE TITLE
Debug ARM64 is not tested on any bot

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#44623]
Once we had every architecture running in both debug and release modes on Linux. Currently debug [sim]arm64 is not run on any bot, even though we implement fewer architectures, and we have observed ARM64 assertion rotting (https://dart-review.googlesource.com/c/sdk/+/178263).

**Comment by whesse** [comment]
@mkustermann 
I notice there is debug-precomp-simarm64 running for both nnbd and legacy, so is it just jit-debug-[sim]arm64 we are talking about being missing?  There are only one arm hardware device for CI, which I think is why we are only running release on arm64 for both jit and aot.  There are also android devices, where we are also running only release.  But I suppose debug would be slow on both simarm64 and arm64, on linux and android.

**Comment by rmacnak-google** [comment]
This is now covered by mac-arm64.
