### ISSUE TITLE
static extension methods won't work, but the analyzer won't complain about declaring one

### ISSUE THREAD

**Issue by NANASHI0X74** [dart-lang/sdk#44620]
so, this is my dart version string:
`Dart SDK version: 2.10.0 (stable) (Mon Sep 28 09:21:23 2020 +0200) on "linux_x64"`
I've been able to reproduce the same as well in a dartpad though...

So the problem is: I was trying to add a static method to a class via extensions, something like this:
```dart
class A {
  int a = 1;
}

extension B on A {
  static A of(String c){ //no error here
    if(c == "a"){
      final a = A();
        a.a=2;
      return a;
    }else{
      return A();
    }
  }
}

int i = A.of("a"); //error here
```
this fails to compile because the of method isn't found:
```
Error compiling to JavaScript:
Warning: Interpreting this as package URI, 'package:dartpad_sample/main.dart'.
lib/main.dart:17:9:
Error: Method not found: 'A.of'.
A i = A.of("a");
        ^^
Error: Compilation failed.
```
So it looks like dart doesn't support static extension methods, that's fine, but in that case I would expect to get a compiler/analyzer error already when declaring the method.

**Comment by vsmenon** [comment]
A static method on an extension can be called directly, e.g.,:

```dart
  var a = B.of("a");
```

so the declaration is valid / usable.

**Comment by vsmenon** [comment]
I'll mark this as a lint request for consideration.  FYI - @lrhn @leafpetersen

**Comment by NANASHI0X74** [comment]
> A static method on an extension can be called directly, e.g.,:
> 
> ```dart
>   var a = B.of("a");
> ```
> 
> so the declaration is valid / usable.

ah, I see.
Thanks for clearing that up

**Comment by srawlins** [comment]
@vsmenon what would the lint rule report? Any static declaration on an extension?

**Comment by srawlins** [comment]
Apologies, stale.
