### ISSUE TITLE
Support relative imports for extensions on quick-fixes + auto-imports

### ISSUE THREAD

**Issue by danielgomezrico** [dart-lang/sdk#44626]
When you declare an extension in your project like:

```dart
extension MyExtension on String {
    void fixCapitals() {}
}
```

It is not recognized by the import hints when you try to use them from your own project files, say that you have a file in other folder like:

```dart
class Person {
    String _name;

    String get name {
         // You get a compilation error since you has not import the extension yet
         _name.fixCapitals();
    }
}
```

The only fix to this is to add the import by yourself and it's a little bit painful, I come from Kotlin where this works and it improves my productivity a lot.

I expect this to work:
- As a "fix issue hint" on the IDE (I use IntelliJ) like this one:
![image](https://user-images.githubusercontent.com/76348/104102718-296eb980-526c-11eb-9f04-71cb6cf81fc8.png)

- On project files and on test files, so you can have extensions for your project and also for your test code.

**Comment by danielgomezrico** [comment]
Related to this https://github.com/dart-lang/sdk/issues/32916

**Comment by feltcorgi4114** [comment]
Yes, this is very true... It is actually very annoying that auto-completion doesn't work for extension methods, and it has led me to repeat certain functionalities a number of times now. It would be great if this is resolved as quickly as possible.

**Comment by cdmunoz** [comment]
I have felt ashamed with myself when facing some errors like this in particular, because firts, I reformat my code reorganizing the imports and the error is there. 
Then after I regenerate my code, and run Dart Analysis again (just thinking that this would clean everything a solve the problem) I realize the error is still there. 
Finally I remember that I have to do the import manually 🤦‍♂️

**Comment by softronaut** [comment]
A simplest workaround I've realized:
```
class MyExtensionExporter {}
```
Import this before using extension method then you are good to go.

**Comment by DanTup** [comment]
FWIW if you enable the lint `prefer_relative_imports`, then the quick-fix will use a relative import:

<img width="712" alt="Screenshot 2023-03-28 at 11 06 22" src="https://user-images.githubusercontent.com/1078012/228202870-9222c20f-a43e-45b3-acdc-ae3b5190a1c0.png">

I don't know if this solves the whole issue - I think in some places both options are shown (and the preferred one - based on lints - is at the top).

**Comment by bwilkerson** [comment]
As far as I can tell, this issue has been resolved. If that's not the case, please let us know what's not yet working. I'm happy to reopen.
