### ISSUE TITLE
dart2js: "Maximum call stack size exceeded" when getter & setter for private fields in mixins

### ISSUE THREAD

**Issue by noliran** [dart-lang/sdk#44636]
Hi folks,

**Background:**
Working on getting an iOS and Android Flutter project that uses MobX to work with Flutter Web.

When I building the project with `flutter build web` and serving it, everything's fine.
However, when I try to run it with `flutter run -d chrome` I get a "Maximum call stack size exceeded" error:
```======== Exception caught by widgets library =======================================================
The following JSRangeError was thrown building MyApp(dirty):
Invalid argument: Maximum call stack size exceeded

The relevant error-causing widget was: 
  MyApp file:///Users/_/git/js_bug_repro/lib/main.dart:34:10
When the exception was thrown, this was the stack: 
packages/js_bug_repro/main.dart 14:5                                     get [_test]
packages/js_bug_repro/main.dart 14:18                                    get [_test]
packages/js_bug_repro/main.dart 14:18                                    get [_test]
packages/js_bug_repro/main.dart 14:18                                    get [_test]
packages/js_bug_repro/main.dart 14:18                                    get [_test]
...
====================================================================================================
```

**Steps to reproduce:**
I've been able to peel away all the wizardry around MobX and reproduce the bug consistently in this gist: https://gist.github.com/noliran/27d10d009f847f55c232df0bc8353763
* `flutter run -d chrome`

**Potential workarounds:**
--> Making the field public (`_test` -> `test`) solves the problem
--> Removing the `Store` mixin solves the problem
--> Running the output of `flutter build web` directly

**Notes:**
* This might be related to issue #36217 but I can't tell for sure.
* This is the cause of issue https://github.com/mobxjs/mobx.dart/issues/438

**Environment:**
* `Dart SDK version: 2.12.0-141.0.dev (dev) (Thu Dec 10 06:04:48 2020 -0800) on "macos_x64"`
* `Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en)`
* Mac OS X, Chrome

**Comment by sigmundch** [comment]
Thanks for the bug report, and thank you so much for the small reproduction case. That was really helpful!

Good news is that this was fixed very recently and you'll find the fix in an upcoming dev release! The fix landed in  52db62dd65284192755906691baf66c47a43f47e, which will be part of any future Dart release higher than 2.12.0-180.0.dev.

We will add a regression test just in case, since I don't see this covered by the existing unit tests.

**Comment by sigmundch** [comment]
CL to add the regression test in https://dart-review.googlesource.com/c/sdk/+/178900

**Comment by noliran** [comment]
Thanks @sigmundch! great to hear. Let me know if I should close this issue then :)

**Comment by noliran** [comment]
closing
