### ISSUE TITLE
Dart migrate positions its markers not correctly in FireFox and Safari

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#44635]
Hi,

while trying to migrate my get_it_mixin package on my MBA M1 I found this effect here

<img width="851" alt="grafik" src="https://user-images.githubusercontent.com/16635729/104136298-83b76980-5395-11eb-97a7-b1a0490ad77b.png">

´´´
[✓] Flutter (Channel master, 1.26.0-2.0.pre.17, on macOS 11.1 20C69 darwin-arm, locale de-DE)
    • Flutter version 1.26.0-2.0.pre.17 at /Users/escmoteur/Entwicklung/flutter
    • Framework revision e74712c4d6 (4 weeks ago), 2020-12-15 12:48:05 -0500
    • Engine revision cca6ab654e
    • Dart version 2.12.0 (build 2.12.0-153.0.dev)
´´´
I have no Chrome installed here so that I can't tell you if it would work there

What I realized is that the tool adds a lot of type information where before only a ´var´ was and for that type you can't set any hint

Also it would be helpful if it where possible also to set ´late´hints

**Comment by stereotype441** [comment]
@srawlins would you mind having a look at this?  I suspect there's probably a fairly easy CSS fix

**Comment by srawlins** [comment]
You can set late hints (either `/*late*/` or `/*late final*/` but the tool does not have buttons for those yet.

**Comment by srawlins** [comment]
I can reproduce the visual issue in Firefox
