### ISSUE TITLE
Analysis Server doesn't provide navigation information for non-imported dartdoc symbols in comments

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#44637]
Dart SDK 2.10.4 or 2.12.0-198.0.dev. Sample code:
```
/// See class [FutureOr]
class Foo {}
```
Analysis Server doesn't provide navigation information for `FutureOr` unless `dart:async` is explicitly imported.

AFAIU, unambiguous references in docs should be resolved even without imports. This functionality has been discussed in https://github.com/dart-lang/dartdoc/issues/1153 and fixed by https://github.com/dart-lang/dartdoc/pull/1298. Probably this regressed.

**Comment by bwilkerson** [comment]
Actually, it isn't a regression. In pre-Dart 1 days the specification actually included references in documentation comments and it didn't allow references to things that hadn't been imported. When dartdoc was implemented that behavior was extended (and the spec wording was removed), but analyzer has just never been updated. It's still unfortunate that the two tools don't agree, and this should be addressed if possible.

**Comment by srawlins** [comment]
Closing this in favor of the new `@docImport` feature, which works at HEAD. https://github.com/dart-lang/sdk/issues/50702
