### ISSUE TITLE
Support testing for `bulkApply: false` fixes

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#44639]
Opening for reference in https://github.com/flutter/flutter/pull/73604

We need a way to test dart fixes that that are only applied in the IDE. These fixes are not done using the `dart fix` command, and so the current `dart fix --compare-to-golden` testing does not cover these fixes.

These cases are most easily identified by the `bulkApply: false` setting in `fix_data.yaml`
In the case of https://github.com/flutter/flutter/pull/73604, there is more than one option for fixing, so the tool cannot decide automatically which path to take. 

I think @bwilkerson already has some ideas/designs in mind for supporting this. :)

**Comment by devoncarew** [comment]
Is this item complete now?

**Comment by bwilkerson** [comment]
Yes, support has now been added.
