### ISSUE TITLE
VM service does not hot reload non-main Isolates

### ISSUE THREAD

**Issue by maks** [dart-lang/sdk#44640]
Using the vm service package it should be possible to use the [`reloadSources`](https://pub.dev/documentation/vm_service/latest/vm_service/VmService/reloadSources.html) to hot reload an Isolate from changes made to the src file on disk.

With current master of the Dart SDK this seems to work fine using the DartVM in JIT mode on the commandline with the main isolate but not with any isolate's spawned from the main isolate.

This seems to have been reported in several different Flutter issues:
* https://github.com/flutter/flutter/issues/18600
* https://github.com/flutter/flutter/issues/20743

This was supposedly fixed for Flutter in this [change](https://github.com/flutter/flutter/pull/52149/files#diff-944d5cfb6162f7069741ffcec6a139e93ecd3b38b543b6a948c10317a513cf0fR286-R287) as part of https://github.com/flutter/flutter/pull/52149 but I don't see how that could actually be working at the moment as I am seeing that it  doesn't work with just the standalone Dart SDK.

I created [a modified version of the recharge package](https://github.com/maks/recharge/tree/background-isolate-test) that demonstrates this issue.

To reproduce:
1. clone the above repo and use the `background-isolate-test` branch, run: `dart  --enable-vm-service example/hello.dart`
2. edit `hello.dart` changing the value returned by `mesg()` and the print inside `worker()`
3. note the pid printed out from step 1 and send it a sigusr1, eg `kill -n 10 <pid-of-example>`
4. notice that the output will show the new value of `mesg()` but NOT of the worker's `print()`

The version I have been testing with is built locally:
```
dart --version
Dart SDK version: 2.12.0-edge.30c4006d52fad4ee8b92025933b9f17af7a8740f (be) (Thu Dec 31 00:48:50 2020 +0000) on "linux_x64"
```

**Comment by mkustermann** [comment]
This is due to https://github.com/dart-lang/sdk/issues/36648. We intend to solve as part of https://github.com/dart-lang/sdk/issues/36097

**Comment by aam** [comment]
Just to clarify - the issue demonstrated above with `recharge` package is not that non-main isolates are not hot-reloaded, rather that after a hot-reload, isolates spawned _after_that_(`worker` isolate in the repro above) don't have that hot-reload updates, instead spawned with the original source.

**Comment by gnprice** [comment]
> This is due to #36648. We intend to solve as part of #36097

Those two issues have been resolved. I just tried the repro recipe above, and confirmed that it no longer reproduces — at step 4, I see the new version of both strings.

That's with:
```
$ dart --version
Dart SDK version: 2.18.6 (stable) (Unknown timestamp) on "linux_x64"
```

So I believe this issue can be closed.

**Comment by maks** [comment]
yes sorry I forgot about this issue. 
I just retested myself with 2.18.6 on linux and concur its now fixed so I'll close this now.
