### ISSUE TITLE
Platform depending conditional import

### ISSUE THREAD

**Issue by bambinoua** [dart-lang/sdk#44644]
It is known how to import conditionally using web and non-web. Is it possible to make conditional import depending on `Platform`?

```dart
import 'file_web.dart';
if (Platform.isAndroid) import 'file_android.dart';
if (Platform.isiOs) import 'file_ios.dart';
````

**Comment by jonasfj** [comment]
You can do: `if (dart.library.io) import ...` and it conditional on which core libraries are available.
See also: https://dart.dev/guides/libraries

But there is nothing for OS'es... maybe there should be?

**Comment by vsmenon** [comment]
Can you let us know more about your use case?  E.g., for Flutter, we recommend a plugin approach instead of conditional imports:

https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins

**Comment by bambinoua** [comment]
For example, I create a framework for our future apps. I have classes like:
```dart
abstract class Settings {}

abstract class App {
  Settings get settings;
}

class WebApp extends App {
  WebSettings get settings() => WebSettings();
}

class AndroidApp extends App {
  AndroidSettings get settings() => AndroidSettings();
}

class IosApp extends App {
  IosSettings get settings() => IosSettings();
}
```
Somewhere in the code I want to import the settings only for app which I am working on. So if I am working on web I import web settings and when I type `settings.` the intellisense will show my members of `WebSettings` class, etc. But after reconsidering my idea I realized maybe I wanted something wrong. For now I use this "woraround" - I created two files settings.dart in different directories `app` and `web` which contains the code like:
```dart
final settings = WebSettings();
```
```dart
final settings = AppSettings();
```
And when I type `settings.` I can select the required file (web or app) which gives me an ability to use only settings for concrete `App`.
So maybe my request was to "greedy".

**Comment by devoncarew** [comment]
Sounds reasonable. Another way to do it is to have a global `settings` variable which implements an interface like `Settings`. Some step in general early app initialization would be responsible for filling in the settings variable with the most appropriate implementation for the app type. You could use config specific imports for some apps - web vs. mobile. You could also use more dynamic detection for things you won't know at compile time, like iOS vs Android.

Other portions of the app could then just read from the variable and assume that it had been inited w/ the correct subclass of Settings.

**Comment by xuzhongpeng** [comment]
I think this idea is very useful. We use "if else" will compile the code in kernel. It should have some way to make import depending on custom conditional.
