### ISSUE TITLE
CFE: Implement type literal and constant object expression canonicalization

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44641]
I landed some changes to the type literal and constant object expression canonicalization semantics [here](https://github.com/dart-lang/language/pull/1389).  This issue tracks CFE work to implement this.

cc @johnniwinther

**Comment by franklinyow** [comment]
@sigmundch Please update this issue

**Comment by sigmundch** [comment]
@nshahan found that there were several regressions some on performance some on correctness from @stefantsov change.

@nshahan and I created two changes on the DDC side to address the correctness problems, but we will continue to fix the performance issues throughout the day.

A stack with the two changes is here: https://dart-review.googlesource.com/c/sdk/+/180266/3 and they appear to make @stefantsov changes complete the ddc bots without failures.

We'll send another update later in the day as things land.

**Comment by vsmenon** [comment]
Thanks!  @sigmundch - you mentioned VM failures.  Is there anything to sanity check here (fyi - @a-siva )?

**Comment by sigmundch** [comment]
DDC changes are now in the submit queue (all in a stack CL: https://dart-review.googlesource.com/c/sdk/+/180444).

@stefantsov - once it lands, we believe you should be able to rebase from master and your CL will no longer have ddc-related failures.

**Comment by sigmundch** [comment]
quick update: ddc changes landed in
6854871069eaa5fe56f24bada4325f9aef23888b on master
