### ISSUE TITLE
Analyzer: Implement new type literal and constant object expression canonicalization

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44642]
I landed some changes to the type literal and constant object expression canonicalization semantics [here](https://github.com/dart-lang/language/pull/1389).  This tracks analyzer work to implement these semantics.

cc @scheglov

**Comment by scheglov** [comment]
I believe aaabc7537d10774588f7bb05aa15b09bf1490b5b fixed type literals.
And we already use [runtime type equality](https://github.com/dart-lang/sdk/blob/c393930f59e61624aa5651655f6ef38022be2326/pkg/analyzer/lib/src/dart/constant/value.dart#L531) for types when checking constant values identity.
