### ISSUE TITLE
VM/AOT: Implement new type literal and constant object canonicalization

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44643]
I landed some changes to the type literal and constant object expression canonicalization semantics [here](https://github.com/dart-lang/language/pull/1389).  This tracks work in the VM/AOT to implement this.

cc @crelier @alexmarkov

**Comment by crelier** [comment]
See https://dart-review.googlesource.com/c/sdk/+/178927

**Comment by crelier** [comment]
See also https://dart-review.googlesource.com/c/sdk/+/179060

**Comment by crelier** [comment]
Tentatively closing this issue, as the remaining issues should get fixed by CFE.
