### ISSUE TITLE
Exception does not include line number of the causing statement when null aware operator inside an if inside a list literal resolves to null

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44654]
The following test program

```
// @dart = 2.9

void test2() {
  String string = null;
  if (string?.isNotEmpty);
}
void main() {
  try {
    test2();
  } catch (e, s) {
    print(s);
  }
}
```
prints

#0 test2 (test.dart)
#1 main (test.dart:9:5)

instead it should print

#0 test2 (test.dart:5:14)
#1 main (test.dart:9:5)

**Comment by a-siva** [comment]
This issue was derived from https://github.com/flutter/flutter/issues/70302

**Comment by liamappelbe** [comment]
@stefantsov Does the CFE lower `x?.y` to `(x != null) ? x.y : null`? If so it might be loosing the line number along the way.

**Comment by stefantsov** [comment]
That's interesting.  I think we're pretty consistent with threading through the offset.  It looks like @johnniwinther implemented the last incarnation of that encoding.  Johnni, do you know what that could be?

**Comment by johnniwinther** [comment]
The condition of the if statement is a `Let` expression and file offsets are currently not serialized on those.

It probably should be, but the CFE has, for reason of the size of .dill files, never stored offsets on all expressions. We for instance also don't store the file offset on literals, so you'll the same result for `if (null);`.

**Comment by liamappelbe** [comment]
So what's the fix? Can we add the offset to this expression?

**Comment by johnniwinther** [comment]
I'll add a file offset to the `Let` expression. It'll solve this particular issue, but the problem would still occur for other expressions for which the file offset isn't serialized.

Ideally all expression should have a file offset but we need to ensure that it carries its weight in terms of add code size. For the `Let` expression I'm sure it does.
