### ISSUE TITLE
`dart analyze` doesn't recognize single files

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44655]
Perhaps this is working as intended, but it was quite surprising to me.  On current bleeding edge build:

```
leafp-macbookpro:const leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer type_literals.dart
Analyzing type_literals.dart...
No issues found!
```

```
leafp-macbookpro:const leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart analyze type_literals.dart
Directory doesn't exist: type_literals.dart

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options
```

Is this WAI?

cc @devoncarew

**Comment by bwilkerson** [comment]
No, the analysis server specification states that single files can be analyzed. Unfortunately the original implementation did not satisfy the spec and has not yet been enhanced to do so. There is a technical debt task to replace the current implementation with an implementation that uses the newer analyzer APIs, which do correctly handle this case. When that work item is done then this bug will be fixed. It is an unfortunate regression from `dartanalyze`.

**Comment by devoncarew** [comment]
Yup, this is something we expect to get to. Closing this issue as a dup of https://github.com/dart-lang/sdk/issues/43891.
