### ISSUE TITLE
Code completion stops returning some results sometimes after running a Flutter app on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44650]
Moving from https://github.com/Dart-Code/Dart-Code/issues/2973. On Windows, running a Flutter app sometimes causes the analysis server to stop returning some completions (those that are part of suggestion sets).

From https://github.com/Dart-Code/Dart-Code/issues/2973#issuecomment-758780756:

I was able to fairly reliably reproduce this issue in a script which repeatedly spawns a Flutter app, stops it, deletes the `build` folder. After a number of times, completions no longer include any suggestion sets with them.

I narrowed it down to occurring whenever the following is printed to the analysis server instrumentation log:

```
1610465348830:Err:Watcher error; refreshing contexts.
FileSystemException:: Directory watcher closed unexpectedly, path = 'M::\Dev\TestStuff\foo'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart::io-patch/file_patch.dart::330::11)
#1      _ExpandStream._handleData (dart::async/stream_pipe.dart::240::30)
#2      _rootRunUnary (dart::async/zone.dart::1202::13)
#3      _CustomZone.runUnary (dart::async/zone.dart::1097::19)
#4      _CustomZone.runUnaryGuarded (dart::async/zone.dart::1002::7)
#5      _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::357::11)
#6      _BufferingStreamSubscription._add (dart::async/stream_impl.dart::285::7)
#7      _SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::807::19)
#8      _StreamController._add (dart::async/stream_controller.dart::681::7)
#9      _StreamController.add (dart::async/stream_controller.dart::624::5)
#10     new _RawSocket.<anonymous closure> (dart::io-patch/socket_patch.dart::1683::35)
#11     _NativeSocket.issueReadEvent.issue (dart::io-patch/socket_patch.dart::1181::18)
#12     _microtaskLoop (dart::async/schedule_microtask.dart::41::21)
#13     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50::5)
#14     _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::120::13)
#15     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::185::5)
```

After this occurs ([handled here](https://github.com/dart-lang/sdk/blob/78956cb8d4ed90ce3a1e94763b907964df20a4c6/pkg/analysis_server/lib/src/context_manager.dart#L1421-L1427)) calls to `computeIncludedSetList` get a `null` from `tracker.getContext(analysisContext)` which results in failing to add the completions here (which seems to be because the context is destroyed and/or recreated):

https://github.com/dart-lang/sdk/blob/d63d5d93a59b370bf5f5c277109110cb67a96b75/pkg/analysis_server/lib/src/domains/completion/available_suggestions.dart#L24-L25

If I trigger `_handleWatchInterruption` in code (for example by setting a timer to call it after 10 seconds in the `ContextManagerImpl` constructor), it reproduces reliably without needing to spawn Flutter or trigger lots of filesystem activity (presumably this will also happen on macOS).

**Comment by bwilkerson** [comment]
My understanding is that this isn't a code completion issue. This is a "server doesn't work when the file watcher dies" issue.

**Comment by DanTup** [comment]
When this happens, it looks like the server recovers by re-reading the files from disk (via the `refresh` call on line 1426 [here](https://github.com/dart-lang/sdk/blob/78956cb8d4ed90ce3a1e94763b907964df20a4c6/pkg/analysis_server/lib/src/context_manager.dart#L1421-L1427)). As far as I can, this works with the exception of resetting the declarations tracker correctly, so it seems to only affect completion.

I found many issues between the SDK and watcher issues about issues like this but they're all closed. I'm not sure if there's anything tracking this issue - should I open one somewhere? (I'm not entirely sure where the issue lies)/

If it's not likely to be an easy/quick fix, is there value in seeing if the recovery code above can be made to handle declarations? I think I can create a failing test for this (forcing the recovery without needing to reproduce the watcher error) and I can have a stab at it if it seems feasible/a good idea.

**Comment by DanTup** [comment]
I had a go at this and may have a fix:

https://dart-review.googlesource.com/c/sdk/+/178981/

**Comment by devoncarew** [comment]
@DanTup - thanks for the fix!
