### ISSUE TITLE
Comments in IntelliJ, can we have line breaks please, the comments are rather difficult to read!

### ISSUE THREAD

**Issue by atreeon** [dart-lang/sdk#44661]
Using the latest Dart and IntelliJ as of 13/1/2021

![Screenshot 2021-01-13 at 20 21 04](https://user-images.githubusercontent.com/4139336/104507045-1c402a80-55de-11eb-81b9-f7b4ed1082c7.png)

**Comment by bwilkerson** [comment]
Documentation comments follow markdown conventions. To have two separate paragraphs, add a blank line between them:
```
/// stuff1
///
/// stuff2
class MyClass {}
```
