### ISSUE TITLE
http2 error in http2 connection cause websocket receives no message

### ISSUE THREAD

**Issue by wanjm** [dart-lang/sdk#44665]
reproduce step

1. set up web socket (in dart:io) and echo message;
```
socket = await WebSocket.connect(strUrl);
    recorder.ready();
    await for (String message in socket) {
     print("get $message");
...
}
```
```
another timer to send message to server using the socket;
```
every thing works well;

2. use http2 in flutter plugin to send http request, but the server doesn't support http protocal(reset the connection)
3. websocket will not get message from server again, but server will still receive message from client;

**Comment by sortie** [comment]
Hi, your reproduction instructions are too short. Can you provide a full example that can be run? Can you say exactly what goes wrong and what should have happened instead?

**Comment by wanjm** [comment]
@sortie it is a bug of http2. please close it. 
but is there any one take care of http2? 
https://github.com/dart-lang/http2/issues/80
