### ISSUE TITLE
Error during http request (in Firebase function) generated by dart2js: ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by stefano2012** [dart-lang/sdk#44668]
# Common problems:

- when using with dart2js for firebase functions all requests crashes with ReferenceError: XMLHttpRequest is not defined

# Diagnosing:

import 'package:http/http.dart' as http;
class ExecuteHttpRequest {
  Future<void> execute() async {
    Uri getUri = Uri.https('www.google.com', '');
    final response = await http.get(getUri);
    if (response.statusCode == 200) print('success');
  }
}

import 'package:node_io/node_io.dart';
import 'package:firebase_functions_interop/firebase_functions_interop.dart';
import 'package:nodejs_test/ExecuteHttpRequest.dart';

void main() {
  functions['executeHttpRequest'] = functions.https.onRequest((ExpressHttpRequest request) async {
    await ExecuteHttpRequest().execute();
    request.response
      ..headers.contentType = ContentType.text
      ..write("success :-)")
      ..close();
  });
}

ERROR:
i  functions: Beginning execution of "executeHttpRequest"
>  /Users/stefano/development/nodejs-test/functions/build/index.dart.js:8378
>        throw error;
>        ^
>  
>  ReferenceError: XMLHttpRequest is not defined
>      at /Users/stefano/development/nodejs-test/functions/build/index.dart.js:10055:15
>      at _wrapJsFunctionForAsync_closure.$protected (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3431:15)
>      at _wrapJsFunctionForAsync_closure.call$2 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7301:12)
>      at _awaitOnObject_closure.call$1 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7287:32)
>      at _RootZone.runUnary$2$2 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:8450:18)
>      at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7689:61)
>      at Object._Future__propagateToListeners (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3530:104)
>      at _Future._completeWithValue$1 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7502:9)
>      at _Future__asyncComplete_closure.call$0 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7604:10)
>      at Object._microtaskLoop (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3593:21) {
>    dartException: <ref *1> ReferenceError: XMLHttpRequest is not defined
>        at /Users/stefano/development/nodejs-test/functions/build/index.dart.js:10055:15
>        at _wrapJsFunctionForAsync_closure.$protected (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3431:15)
>        at _wrapJsFunctionForAsync_closure.call$2 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7301:12)
>        at _awaitOnObject_closure.call$1 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7287:32)
>        at _RootZone.runUnary$2$2 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:8450:18)
>        at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7689:61)
>        at Object._Future__propagateToListeners (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3530:104)
>        at _Future._completeWithValue$1 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7502:9)
>        at _Future__asyncComplete_closure.call$0 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7604:10)
>        at Object._microtaskLoop (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3593:21) {
>      '$cachedTrace': _StackTrace {
>        _exception: [Circular *1],
>        _trace: 'ReferenceError: XMLHttpRequest is not defined\n' +
>          '    at /Users/stefano/development/nodejs-test/functions/build/index.dart.js:10055:15\n' +
>          '    at _wrapJsFunctionForAsync_closure.$protected (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3431:15)\n' +
>          '    at _wrapJsFunctionForAsync_closure.call$2 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7301:12)\n' +
>          '    at _awaitOnObject_closure.call$1 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7287:32)\n' +
>          '    at _RootZone.runUnary$2$2 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:8450:18)\n' +
>          '    at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7689:61)\n' +
>          '    at Object._Future__propagateToListeners (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3530:104)\n' +
>          '    at _Future._completeWithValue$1 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7502:9)\n' +
>          '    at _Future__asyncComplete_closure.call$0 (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:7604:10)\n' +
>          '    at Object._microtaskLoop (/Users/stefano/development/nodejs-test/functions/build/index.dart.js:3593:21)'
>      }
>    }
>  }

**Comment by natebosch** [comment]
What browser are you using?

I'm not sure that we support making Http requests in a browser that does not have `XMLHttpRequest` support.

**Comment by sigmundch** [comment]
Another thought, based on the fact that your snippet and code mentions node.js, are you running the code in node.js instead of a browser? If so, how are you invoking dart2js to build your application?

For example, I'd like to confirm that you are specifying `--server-mode`. I recall `package:http` has conditional imports and will use different code for browsers than for nodejs, but only if the right mode is specified when building with dart2js in the first place.

**Comment by natebosch** [comment]
Closing since I don't think this is actionable.
