### ISSUE TITLE
[Suggestions] add sum function to math

### ISSUE THREAD

**Issue by erf** [dart-lang/sdk#44674]
Have you considered adding a `sum(a, b)` function to the `math`package for adding two numbers together.

Example implementation:

```
T sum<T extends num>(T lhs, T rhs) => (lhs + rhs) as T;
```

Nice to to have if you'd like to e.g. `list.reduce(sum)`

**Comment by lrhn** [comment]
Dart has fairly short first class function expressions, so `list.reduce((a, b) => a + b)` has been considered usable and readable enough that we don't need extra top-level functions that emulate the binary operators.

If we get an even shorter syntax for simple functions (see #8), perhaps like `=>_1+_2`, then it would be even briefer: `list.reduce(=>_1+_2)`. Having to give that a name, and take up space in the global namespace, feels like unnecessary overhead.

**Comment by erf** [comment]
Ok, thanks. I like the shorthand syntax, but the link seem to point to wrong issue?

**Comment by lrhn** [comment]
Fixed link, forgot I wasn't in the language repo.
