### ISSUE TITLE
Migration tool unnecessarily makes extended type nullable

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44675]
Given this code:

```dart
extension E on ClassName {
  String display() => this.method();
}

class ClassName {
  String method() => null;
}

void test() {
  ClassName c = null;
  c.display();
}
```

the migration tool is suggesting the following output:

```dart
extension E on ClassName? {
  String? display() => this!.method();
}

class ClassName {
  String? method() => null;
}

void test() {
  ClassName? c = null;
  c!.display();
}
```

Note that it is *both* choosing to add a `!` on `c` and making the extension nullable.  Either would work, though the unconditional method call in the definition of `display` strongly points towards the extension not expecting to be applied to `null`.

cc @stereotype441 @srawlins

**Comment by stereotype441** [comment]
After discussion with Leaf I'm going to consider this a P2.  I'll still try to get to it before we make the stable branch cut but no guarantees

**Comment by stereotype441** [comment]
I'm working on this now.
