### ISSUE TITLE
member type is not inferred after is

### ISSUE THREAD

**Issue by Producer86** [dart-lang/sdk#44672]
Hello,
So I have a 
```Dart
class Location<R> {
  final Tree<R> tree;
  final Path<R> path;

  Location(this.tree, this.path);
}
```
and something like this in a Location method
```Dart
Location<R> goLeft() {
  if (path is Node<R>) {
    final left = path.l;
}
```
gives `The getter 'l' isn't defined for the type 'Path<R>'.`
but this is fine
```Dart
Location<R> goLeft() {
  final p = path;
  if (p is Node<R>) {
    final left = p.l;
}
```

Id guess its because `path` resolves to `this.path` and as such doesn't have its local symbol to store type information so we need to make one manually, or am I missing something else?

**Comment by eernstg** [comment]
This is working as intended, instance variables cannot be promoted; cf. https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion.
