### ISSUE TITLE
relative `lib` imports are not resolving correctly in tests

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#44673]
Noted in https://github.com/dart-lang/sdk/blob/7f95c18812945ffab70418583e3b19c3a77cd06f/pkg/analysis_server/test/src/services/correction/fix/convert_to_package_import_test.dart#L29-L31

And has come up again when testing bulk-fixes.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Seems for work as intended.
Resolving such relative URI in a package `lib/` makes us to leave the package.
The fact that there is some file system where it could bring us back does not matter IMHO.

**Comment by bwilkerson** [comment]
If we don't support URIs of that form, then I have to question the value of the lint (as currently defined and implemented).

**Comment by srawlins** [comment]
Maybe working as intended.
