### ISSUE TITLE
INVALID_USE_OF_VISIBLE_FOR_TESTING_MEMBER shouldn't trigger on a `hide` combinator

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44671]
The following code triggers the analyzer hint INVALID_USE_OF_VISIBLE_FOR_TESTING_MEMBER:

a.dart:
```dart
import 'b.dart' hide Foo;
```

b.dart:
```dart
import 'package:meta/meta.dart';
@visibleForTesting
class Foo {}
```

I think this should be permitted, because the reference to `Foo` in the `hide` combinator isn't really *using* `Foo`; in fact it's *excluding* `Foo` from the namespace so that it can't be used.

This is especially frustrating when the reason for wanting to use the `hide` combinator is to avoid an ambiguous reference (because a symbol is defined in two imported libraries, and the one that's marked as "visible for testing" is the one I *don't* want).

See https://dart-review.googlesource.com/c/sdk/+/179280/1..2 for the concrete situation where this came up.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/179420
