### ISSUE TITLE
[dartdevc] Undefined symbol when evaluating 'main'

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#44686]
**Repro**

- debug flutter's example/hello_world
- put a breakpoint on a line that contains 'runApp'
- type expression `main` in expression evaluation box

**Result**:

`main is not defined`

**Verbose output of generated JavaScript**

[        ] 0:16:51.729288: Compiled expression
[        ] main to
[        ] try {
[        ]   (function() {
[        ]     return C[13] || CT.C13;
[        ]   }(
[        ]   ))
[        ] } catch (error) {
[        ]   error.name + ": " + error.message;
[        ] } in 0ms.

**Expected:**

Javascript for `main`

**Comment by jacob314** [comment]
Does the issue impact other top level methods or just main?

**Comment by annagrin** [comment]
The is due to a missing variable for the current library, not a function. The error would appear in any expression referencing the library. The missing definition would look like:

`var main = require('web/main.dart').web_main`

This will be fixed when `evaluate()` works (see issue collection above). The work is currently in progress (for amd modules only for now).
