### ISSUE TITLE
list map function doesnt work (dart2js) just freezes

### ISSUE THREAD

**Issue by cyberpwnn** [dart-lang/sdk#44684]
# Broken

```dart
List<dynamic> data = getSomeData();
return data.map((e) => e.toString());
```

# This works

```dart
List<dynamic> data = getSomeData();
List<String> dartIsBad = List<String>();

for (int i = 0; i < data.length; i++) {
    dartIsBad.add(data[i].toString());
}

return dartIsBad;
```

Using Flutter latest (beta), There isnt a dart version command so just look at flutter

**Comment by sigmundch** [comment]
do you see any errors in the console or any signal other feedback? Is this using `flutter run -d chrome` in debug or release mode? (each uses a different compiler to JavaScript).

One thing I noticed that is different between the two programs above is that the former returns an Iterable, and the latter a List. Maybe there is a type error down the line that for some reason is not shown or propagated (e.g. I would hope such errors would be visible at least in the browser console).

If that's the case, maybe it would work to add `toList`, as in:

```dart
return getSomeData().map((e) => '$e').toList();
```
