### ISSUE TITLE
package:vm_service use of late final for optional constructor arguments problematic

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#44683]
`package:vm_service` version `6.0.0-nullsafety-dev` makes heavy use of the `late` field pattern for optional constructor arguments. This is problematic as users of the package like `package:dwds` actually set these late fields outside of the constructor.

For [example](https://github.com/dart-lang/sdk/blob/73bd44d3638ba7aac553576f8fa19253ae3f75e0/pkg/vm_service/lib/src/vm_service.dart#L5015).

**Comment by bkonyi** [comment]
Resolved in [this CL](https://dart-review.googlesource.com/c/sdk/+/180089).
