### ISSUE TITLE
Invalid Dart code doesn't analyze/generate errors correctly

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44699]
The following code does not produce any diagnostics in my IDE:

```dart
const dirHandle = await a.b();
```

Instead, it produces errors from the LSP server that suggest the file has not been analyzed. If I reproduce this in a test like this:

```dart
Future<void> test_danny2() async {
  createProject();
  addTestFile('const dirHandle = await a.b();');

  await waitForTasksFinished();
  await pumpEventQueue(times: 5000);
  expect(filesErrors[testFile], isNotEmpty);
}
```

It triggers the following exception during analysis:

<img width="1026" alt="Screenshot 2021-01-18 at 14 30 50" src="https://user-images.githubusercontent.com/1078012/104928007-05148a80-599a-11eb-85ce-e4e9ea771844.png">

This seems to occur because `AstBinaryWriter` doesn't have an implementation of `visitAwaitExpression`. I don't know if that's the problem, or if it's not supposed to have gotten here.

@bwilkerson

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/180460
