### ISSUE TITLE
Redirected factory constructor compiles with non-nullable types when invalid

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#44693]
Consider the following code:

```dart
class Foo {
  factory Foo({String a}) = Bar;
}

class Bar implements Foo {
  Bar({Object? a});
}

void main() {
  Foo();
}
```

This code compiles with non-nullable types, when it doesn't make sense.

```dart
Foo({String a})
```

is not valid. It should either be:

```dart
Foo({required String a})
```

or:

```dart
Foo({String? a})
```

___

Dart version used:

```
Dart SDK version: 2.12.0-179.0.dev (dev) (Wed Dec 23 21:08:22 2020 -0800) on "macos_x64"
```

**Comment by rrousselGit** [comment]
Thinking about it, this may be caused by default values, as the following should be valid:

```dart
class Foo {
  factory Foo({String a}) = Bar;
}

class Bar implements Foo {
  Bar({String a = ''});
}
```

**Comment by eernstg** [comment]
This is actually working as intended:

It is a [compile-time error](https://github.com/dart-lang/language/blob/2875787f82f848158025e2d8f1f9899f7049d6af/specification/dartLangSpec.tex#L3657) to specify a default value for an optional parameter of a redirecting factory constructor. The rationale is slightly vague, but the basic point is that a redirecting factory should correspond to the redirectee, so it cannot choose a different default value.

This reduces the flexibility of redirecting factories, but it also allows the ones that will use the same default to (1) be more concise, and (2) remain consistent with the redirectee even if and when the default value in the redirectee is updated.
