### ISSUE TITLE
Observatory:

### ISSUE THREAD

**Issue by JimmyKent** [dart-lang/sdk#44697]
Observatory Feedback
![image](https://user-images.githubusercontent.com/17265973/104898582-c8a25800-59b4-11eb-854e-f2c54aa1c15c.png)
I can't find the Pie chart.

flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by a-siva** [comment]
Yes the pie chart functionality has been removed from Observatory, it was dependent on package:charted which is not maintained anymore.
