### ISSUE TITLE
Migration tool doesn't understand list conditional elements

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44702]
Given this code:

```dart
void bar(List<String> l) {}

void test({String foo}) {
    bar([if (foo != null) foo]);
}
```

The migration tool produces the following:

```dart
void bar(List<String?>  l) {}

void test({String? foo}) {
    bar([if (foo != null) foo]);
}
```

The analysis doesn't seem to understand that in the case that `foo` is null, no elements are added (rather than a null element).

cc @stereotype441

**Comment by stereotype441** [comment]
This should be a pretty simple fix.  Working on it now.
