### ISSUE TITLE
Issue with dart:convert and http

### ISSUE THREAD

**Issue by Cali0707** [dart-lang/sdk#44701]
I am running into problems importing dart:convert and HTTP into a file where I want to retrieve a json object from the web

## Steps to Reproduce

The code causing the problem is as follows:

```dart
import 'dart:convert' as convert;
import 'package:http/http.dart' as http;

Future<void> getData(){
  final response = http.get("https://cali0707.github.io/covid_cases.json");
  final exctractedData = json.decode(response.body) as <Map, dynamic>;
//do something with the data
  return null;
}

void main(){
  getData();
}
```

**Expected results:** 
I am expecting to retrieve a json file and convert it into a map.
**Actual results:**
../../../../.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.3/lib/path.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0-nullsafety.3/lib/string_scanner.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/collection-1.15.0-nullsafety.5/lib/collection.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.3/lib/src/context.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.3/lib/src/style.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.3/lib/src/path_exception.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.3/lib/src/path_map.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.3/lib/src/path_set.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0-nullsafety.3/lib/src/exception.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../../../.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0-nullsafety.3/lib/src/line_scanner.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^

I'm using Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"

**Comment by devoncarew** [comment]
Interesting. It looks like several packages in use locally are specifying an sdk version that's newer than the version you're running. It'd try running pub get with the 2.10.4 version you have, and seeing if it doesn't bring down different versions of the packages. It's also possible that some packages misidentified their sdk requirements, but it seems unlikely that several packages did that. You could also check to see if you don't have multiple versions of the dart/flutter sdks installed.

**Comment by Cali0707** [comment]
@devoncarew thank you so much for your help! It looks like the problem was that I had already installed the dart sdk when I originally installed flutter (before it came with the dart sdk). So removing that fixed everything :)
