### ISSUE TITLE
VM test has started failing

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44709]
A VM test has started failing after a [change](https://dart-review.googlesource.com/c/sdk/+/179770) which affected stack traces.

See: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8857679151829657616/+/steps/test_results/0/logs/new_test_failures__logs_/0

The test has very specific regexps to match particular stack traces. Those stack traces no longer match, and I'm not in a position to guess which changes are needed. 
If your test depends on recognizing specific structure which is not guaranteed to be stable against changes outside of your code, you need to have a script that can automatically update the expectations, and link to that script in the error message. Alternatively, you can modify the regexps to be more permissive and only check for the parts that you *are* in control of.

I'll mark the failures as accepted for now, so you can update the tests at your leisure. The affected tests are:
* `vm/dart_2/causal_stacks/async_throws_stack_no_causal_non_symbolic_test`
* `vm/dart_2/causal_stacks/async_throws_stack_no_causal_test`

**Comment by a-siva** [comment]
The original CL has been reverted here https://dart-review.googlesource.com/c/sdk/+/180142, so closing the issue.

**Comment by lrhn** [comment]
Please do consider whether this test can be improved, otherwise I'll file this again next time I refactor `dart:async`.

**Comment by cskau-g** [comment]
The tests have been made more lenient (ignoring any frames not part of the test), and I don't believe the tests are failing at this point, so I'll close this issue here.
