### ISSUE TITLE
AppJIT Assertion Failure: ../../runtime/vm/object.h: 4177: error: expected: !IsOriginal() || is_static() || thread->IsMutatorThread() || thread->IsAtSafepoint()

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#44714]
We're hitting an assertion failure [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8857777525685062496/+/steps/test_results/0/logs/new_test_failures__logs_/0) after submitting [this change](https://dart-review.googlesource.com/c/sdk/+/178990) which should be unrelated to the failing assert.

This is blocking https://github.com/dart-lang/sdk/issues/44234.

cc/ @alexmarkov @rmacnak-google @aam 

FYI @johnniwinther

**Comment by franklinyow** [comment]
@a-siva @bkonyi 
Who is looking at this issue?

**Comment by a-siva** [comment]
CL in progress https://dart-review.googlesource.com/c/sdk/+/180084
