### ISSUE TITLE
Source location out of range in kernel verifier.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44719]
The CL https://dart-review.googlesource.com/c/sdk/+/151512/6 seems to trigger a bug in the kernel.
The CL introduces an `extension` on `Future` to `dart:async` (and exports it from `dart:core` along with `Future`). This may be the first extension in the core platform libraries, and the first extension to be available in *all* libraries (because every library imports `dart:core`).

Errors start with:
```
Unhandled exception:
Crash when compiling null,
at character offset null:
RangeError (offset): Invalid value: Not in inclusive range 0..4554: 28611
#0      RangeError.checkValueInInterval (dart:core/errors.dart:277:7)
#1      Source.getLocation (package:kernel/ast.dart:11108:16)
#2      Component.getLocation (package:kernel/ast.dart:10842:31)
#3      _getLocationInComponent (package:kernel/ast.dart:11401:22)
#4      Library._getLocationInEnclosingFile (package:kernel/ast.dart:650:12)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:204:20)
#6      TreeNode.location (package:kernel/ast.dart:200:12)
#7      TreeNode.location (package:kernel/ast.dart:199:48)
#8      FastaVerifyingVisitor._hasLocation (package:front_end/src/fasta/kernel/verifier.dart:98:17)
```

I'm willing to accept those errors and land the CL (which I want to this week if possible) if it's not something that happens to real users. If it breaks everybody, we need to fix this issue first.

**Comment by johnniwinther** [comment]
It looks like locations on extensions in parts wasn't supported. A fix is brewing.

**Comment by johnniwinther** [comment]
A CL is in the pipeline: https://dart-review.googlesource.com/c/sdk/+/180181

@lrhn To land your CL you need to run `dart pkg/front_end/test/extensions/extensions_test.dart -g` to update the expectations, given that the new extension from `dart:async` is now available in all user libraries.
