### ISSUE TITLE
Failures on Making `_propagateToListeners` not recurse unboundedly.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44710]
There are new test failures on [First attempt at making `_propagateToListeners` not recurse unbounded.](https://dart-review.googlesource.com/c/sdk/+/179770).

The tests
```
service/regress_28443_test/dds RuntimeError (expected Pass)
service/regress_28443_test/service RuntimeError (expected Pass)
service_2/regress_28443_test/dds RuntimeError (expected Pass)
service_2/regress_28443_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

It appears to pick up the wrong line in the breakpoint.

**Comment by a-siva** [comment]
We seem to have two kinds of failures

vm/dart_2/causal_stacks/async_throws_stack_no_causal_test
`Expected line 15 to be `^#14     Future._completeWithValue ` but was `#14     Future._complete (dart:async/future_impl.dart:533:7)``


service_2/regress_28443_test
```
00:36 [32m+0[0m[31m -1[0m: regress_28443_test.dart (VM Service) [1m[31m[E][0m[0m
   Expected to be at line 33 but actually at line 31
   Full stack trace:
    Frame([FrameKind.regular] collect.async_op regress_28443_test.dart:token(844)) [31]
    Frame([FrameKind.regular] _asyncErrorWrapperHelper.errorCallback async_patch.dart:token(2426)) [48]
```

//cc @cskau-g

**Comment by lrhn** [comment]
CL has been reverted, but will probably reland again later.

**Comment by a-siva** [comment]
The original CL has been reverted here https://dart-review.googlesource.com/c/sdk/+/180142, so closing the issue.
