### ISSUE TITLE
Intellij code navigation doesn't seem to index extensions

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44723]
Using Intellij IDEA Ultimate, latest Dart and Flutter plugins, if I hit cmd-O to open the code navigation window and type the name of an extension in my file, it doesn't show up in any of the tabs (not classes, symbols, nor anywhere else that I can find).

cc @jwren @devoncarew

**Comment by devoncarew** [comment]
Jaime, is the indexing here done via the analysis server or the Dart IntelliJ plugin? If the latter, can you re-file this at the YouTrack tracker?

**Comment by jwren** [comment]
Opened https://youtrack.jetbrains.com/issue/WEB-49248, closing this issue
