### ISSUE TITLE
Dart compiler should offer suppression of info messages

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#44727]
We should suppress the output when the compile isn't something the user asked for - e.g. where running any flutter command requires compiling flutter_tools. This could be done e.g. with an undocumented `--silent` flag that can be used by Flutter. 

See https://github.com/flutter/flutter/issues/74366 for the current output.

**Comment by timsneath** [comment]
@mit-mit to make sure this lands, given the tight timescale for the next beta cut-off.

**Comment by mit-mit** [comment]
@johnniwinther is looking at adding a new verbosity option to the CFE, after that we'll need a flag in the VM to pass on that option, cc @bkonyi

**Comment by johnniwinther** [comment]
The plan is to add a `--verbosity` option with values `error`, `warning`, `info`, and `all` similar to https://github.com/dart-lang/pub/commit/97555de11adbcd775a3288fb39a57de830d16727 with the default value `all`.

@mit-mit Do you agree?

**Comment by mit-mit** [comment]
sgtm!

**Comment by vsmenon** [comment]
Marking as a P2.

What's the expected timeline for a fix?  It'd be nice to get this in pre cut, but I don't think we need to block.  It should be a low risk cherry pick if needed.  FYI - @franklinyow

**Comment by johnniwinther** [comment]
I expect to have CL for the CFE implementation ready today. This includes handling of the `dart compile js`,  `dart compile exe` and  `dart compile aot-snapshot` commands.

**Comment by johnniwinther** [comment]
The CFE CL is in the pipeline: https://dart-review.googlesource.com/c/sdk/+/180566

**Comment by johnniwinther** [comment]
The CFE CL has landed.

**Comment by bkonyi** [comment]
VM CL up for review: https://dart-review.googlesource.com/c/sdk/+/180605

**Comment by franklinyow** [comment]
Any update on this?  Thx
