### ISSUE TITLE
support dart:developer Service.getInfo()

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#44736]
Support the following RPC on the web https://api.dart.dev/stable/2.10.5/dart-developer/Service/getInfo.html

The VM service was originally written specifically for the VM, but dart2js doesn't actually provide a service. Plus, `getInfo` uses a ReceivePort to communicate with the VM, which is part of dart:isolate which no longer has web support.

@grouma

**Comment by grouma** [comment]
@nshahan I'm not sure how we'd support this. The information would exist in `package:dwds` but I imagine the support would have to come through DDC. Thoughts?

**Comment by nshahan** [comment]
We can add a patch to the dart:developer library for DDC to handle the API but I don't know how to pass along to package:dwds to retrieve them. Maybe some hook that gets added to the page? That feels a little brittle to me. Want to schedule a sync to discuss?

**Comment by grouma** [comment]
I've had a few discussions with folks and I think what you outlined is really the only approach. This information is already essentially injected into the application and is available at the global level. See [this](https://github.com/dart-lang/webdev/blob/9b66ccd3073031001ff9cd61f64462e92d46013f/dwds/lib/src/handlers/injector.dart#L185). The Dart Debug Extension uses this information along with the injected client to enable debugging features. I agree it is somewhat brittle but we can extend this approach and have DDC pull this information for the `getInfo` API. Thoughts?

**Comment by nshahan** [comment]
Ok, if the information is already there at the global level then we could make it accessible through an implementation of getInfo. I'll add this to our task list. A few more questions:

- Is there any need for dart2js to implement this?
- What is the priority of this request, do we need it for the upcoming stable release?

**Comment by grouma** [comment]
> Ok, if the information is already there at the global level then we could make it accessible through an implementation of getInfo. I'll add this to our task list. A few more questions:
> 
> Is there any need for dart2js to implement this?

No. This information won't be there anyway as `package:dwds` only supports DDC.

> What is the priority of this request, do we need it for the upcoming stable release?

I'll let @kenzieschmoll comment on this.

**Comment by kenzieschmoll** [comment]
It is not critical that this makes it into the upcoming stable. There would be another change on the flutter side that would be required to enable web support for where we are using `getInfo()`and that likely wouldn't make the cut since we'd need to wait on the changes upstream in ddc.

**Comment by grouma** [comment]
@nshahan and I chatted offline. It looks like this is slightly more difficult than expected. The information injected by the handler is not sufficient to implement the `getInfo` API. The information we need is actually lazily produced so we don't have it at the time of injection. However, one potential solution is to use the injected client connection to write global state when debugging is initiated. This would allow DDC to pull the required information. That being said, it's possible there is no debugging instance so the underlying API should be updated to return a nullable value.

cc @bkonyi

**Comment by nshahan** [comment]
> That being said, it's possible there is no debugging instance so the underlying API should be updated to return a nullable value.

I looked a little deeper into the return value type https://api.dart.dev/stable/2.10.5/dart-developer/ServiceProtocolInfo-class.html and it looks like it can contain a nullable URI. So maybe the right answer is to always return a `SeriveProtocalInfo` but the `serverUri` field can be null if the debugging service has not yet started.

**Comment by kenzieschmoll** [comment]
FYI due to a race condition, we went with the approach instead of adding a service extension to flutter to set the vm service uri (https://github.com/flutter/flutter/pull/74534). That may change priority of this issue.

**Comment by grouma** [comment]
If I read your PR right does that mean Flutter Tools provides the service URI to the running app through the service extension? If so, what's preventing this approach from working within the context of Flutter Web? Wouldn't that make this issue unnecessary?

**Comment by kenzieschmoll** [comment]
The functionality in my PR works from the context of flutter web - so yes that would make this issue obsolete, unless this is functionality that would be useful for other use cases.

**Comment by grouma** [comment]
Closing this for now then. If we need to implement this UI for some other reason in the future we can re-open.
