### ISSUE TITLE
crash when no metrics got registered

### ISSUE THREAD

**Issue by uppet** [dart-lang/sdk#44743]
This tracker is for issues related to:

* Dart VM

crash when no metrics got registered

run the following program,
click 'metrics' page on observatory to trigger a crash
  import 'dart:async';
  main() {
    new Timer.periodic(new Duration(seconds: 1), (t) {});
  }

I have sent a patch with git-cl upload -s in
https://dart-review.googlesource.com/c/sdk/+/180300

**Comment by bkonyi** [comment]
Closed by https://github.com/dart-lang/sdk/issues/44859.
