### ISSUE TITLE
Failures on Reland "[vm] Pass snapshot flag to kernel_service"...DEPS bring in latest sync_http

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#44744]
There are new test failures on [Reland "[vm] Pass snapshot flag to kernel_service"...DEPS bring in latest sync_http](https://github.com/dart-lang/sdk/compare/4dde43218b0d8df3c62a3db24d7771b137800939~...55b34a467c9f522f99511fe77b4b48ca47143f96).

The tests
```
vm/dart_2/kernel_determinism_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-release-simarm
dartk-linux-release-simarm64
```

**Comment by johnniwinther** [comment]
This test depends on the stdout and when compiling to a snapshot the CFE is now emitting a message showing the null safety compilation mode.

**Comment by johnniwinther** [comment]
See also https://github.com/dart-lang/sdk/issues/44738

**Comment by a-siva** [comment]
the simarm tests run the tests in two steps first generating the kernel using gen_kernel and then runnning the test from the generated dill file, the new output shows up in the first step where the CFE runs and not in the second step as the VM is running from a dill file, hence we see these failures only in the simarm configurations.

**Comment by johnniwinther** [comment]
As for #44738, when #44727 has landed we can avoid the extra info when running this test.

**Comment by crelier** [comment]
Also failing on:
dartk-strong-linux-release-simarm
dartk-strong-linux-release-simarm64
dartk-weak-asserts-linux-release-simarm64
dartk-weak-asserts-linux-release-simarm
