### ISSUE TITLE
Add shorthand for null-aware List/Map index access

### ISSUE THREAD

**Issue by enloc-port** [dart-lang/sdk#44752]
In order to avoid a TypeError when trying to access an index on a nullable List or Map, we usually do this:

```Dart
List<String> list;
String s1 = list[0]; // error
String s2 = list?.isNotEmpty ?? false ? list[0] : null; // works
```

But it would be handy, to have a shorthand null-check like this:

```Dart
List<String> list;
String s2 = list?[0]; // s2 == null
```

Since `list` is `null` in this example, index 0 won't even be tried, hence `s2` will be `null`.

**Comment by enloc-port** [comment]
If a distinction between `list == null` and `list[0]` should be made, that should be up to the developer. Hence, I don't see an issue with that syntax in that regard.

**Comment by enloc-port** [comment]
This is somewhat related to #43275 and #44698

**Comment by tatumizer** [comment]
You need to fix your program, then it will work (in dart-nullsafety)
```
main() {
  List<String>? list;
  String? s2 = list?[0];
  print(s2); // null
} 
```

**Comment by enloc-port** [comment]
@tatumizer You're right, this syntax works with null-safety. Nevermind then.
