### ISSUE TITLE
Why List.filled(1, 4, growable: true).runtimeType is List<int> not _GrowableList<int>?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#44757]
void main(List<String> arguments) {
  var ss = List.filled(1, 4, growable: true);
  // prints List<int>, but List<E> is a abstract class
  print(ss.runtimeType);
}

List is a abstract class, so ss.runtimeType should be  _GrowableList<int> ?

**Comment by Silentdoer** [comment]
and in the array_patch.dart, List.filled(1, 4, growable: true) returns a  _GrowableList<int> object actually.

**Comment by mraleph** [comment]
String representation returned by `Type.toString` is implementation dependant and can be anything. `[].runtimeType.toString` returns `List` (in non-PRODUCT builds) to be more user friendly.

**Comment by Silentdoer** [comment]
but Map will prints it actual type, it is not consistent..

var map = Map();
print(map.runtimeType)

prints: _InternalLinkedHashMap< dynamic,dynamic>

**Comment by mraleph** [comment]
It does not have to be consistent. `[].runtimeType.toString()` can also print `asdasdas` and it will be perfectly fine. `Type.toString()` is not intended to be used for anything but debug logging.

**Comment by rakudrama** [comment]
Using `.runtimeType` is not portable. If you compile your code to JavaScript to run on the web (e.g. using dartpad) you will get different results.
```dart
void main(List arguments) {
  var ss = List.filled(1, 4, growable: true);
  print(ss.runtimeType);
  ss = List.filled(1, 4, growable: false);
  print(ss.runtimeType);
}
```
Console:
```
JSArray<int>
JSArray<int>
```

**Comment by Silentdoer** [comment]
> 
> 
> Using `.runtimeType` is not portable. If you compile your code to JavaScript to run on the web (e.g. using dartpad) you will get different results.
> 
> ```dart
> void main(List arguments) {
>   var ss = List.filled(1, 4, growable: true);
>   print(ss.runtimeType);
>   ss = List.filled(1, 4, growable: false);
>   print(ss.runtimeType);
> }
> ```
> 
> Console:
> 
> ```
> JSArray<int>
> JSArray<int>
> ```

Yes, you are right, but why not prints : _GrowableList<int> and _List<int> on dart vm platform? it is more consistent with Map and clearly，and it's useful to debug.

**Comment by Silentdoer** [comment]
what's more, _GrowableList and _List is the actually runtimeType on dart vm platform
