### ISSUE TITLE
[cfe] Correct treatment of mixin application superclass in LUB

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#44769]
Correction: Closing this issue, the current behavior is correct after all. Cf. https://github.com/dart-lang/sdk/issues/44767#issuecomment-766823770 for details.

**Comment by johnniwinther** [comment]
cc @stefantsov

**Comment by eernstg** [comment]
@stefantsov, if it is manageable, it would be great if we could get some data on the breakage caused by fixing this issue, if any. It shouldn't be landed until we know that it's a (sufficiently) safe thing to do.

**Comment by eernstg** [comment]
The current behavior turns out to be correct after all, so I'm closing this issue. Sorry about the noise.
