### ISSUE TITLE
[vm/ffi] Add `Pointer<Struct>.value =` for copying full structs

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44768]
We do not have a way of bulk-copying the full contents of a `Struct` in `dart:ffi`.

One use case where this is creating the need for boilerplate is when getting passed a struct by value from C, and having to pass back a pointer to a struct. @TimWhiting can you quantify how common this pattern is? https://github.com/dart-lang/sdk/issues/36730#issuecomment-757400876

A workaround currently is to define a struct that nests the struct by value.

```dart
class MyStruct {
  // Many native fields.
}

class MyStruct2 {
  MyStruct myStruct
}

Pointer<MyStruct> allocateAndCopy(MyStruct source, Allocator allocator){
  final result = allocator<MyStruct>();
  result.cast<MyStruct2>().ref.myStruct = source;
  return result;
}
```

This accesses the `TypedData` and/or `Pointer` objects wrapped by the `Struct`s and uses `sizeOf<NativeType>()` and `_memCopy` to copy the bytes:

https://github.com/dart-lang/sdk/blob/ba0159688e1ae9cd4b10513d4f4647009f51dfe7/sdk/lib/_internal/vm/lib/ffi_patch.dart#L127-L162

We should enable using this `_memCopy` for full `Struct`s instead of only fields.

https://github.com/dart-lang/sdk/blob/ba0159688e1ae9cd4b10513d4f4647009f51dfe7/sdk/lib/ffi/ffi.dart#L540-L551

```dart
extension StructPointer<T extends Struct> on Pointer<T> {
  /// This extension method must be invoked with a compile-time constant [T].
  external void set value(T value); 
}
```

For the specific use case the code would look like:

```dart
final pointer = allocator<MyStruct>()..value = source;
```

**Comment by dcharkes** [comment]
@lrhn what do you think about `.value = ...`? Using `.ref = ...` is not really appropriate, but it would be symmetric with the getter.

**Comment by TimWhiting** [comment]
Sorry for the delayed response. I see it at least 6 times in this library with 5 different structs. So it isn't as common as I thought, but this still would be a nice addition to the ffi api I think.

**Comment by richardheap** [comment]
@dcharkes I found a similar example to @TimWhiting 's use case. This one comes from the AWS C core library that, for me, is used by the AWS encryption SDK (partial, but sufficient and workable, implementation coming to pub.dev shortly).

From its hash table implementation: https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/hash_table.h

The function to `begin` iteration of a map returns a structure by value, but the `done` and `next` functions expect that passed back by pointer.

I could wrap this in my own function, but the SDK already builds dynamic libraries for Windows, Linux and MacOS which I've been able to use directly (up to this point) by simply `load`ing the library. I can make do without this iteration right now, but I remembered you'd wanted examples.

``` C
struct aws_hash_iter {
    const struct aws_hash_table *map;
    struct aws_hash_element element;
    size_t slot;
    size_t limit;
    enum aws_hash_iter_status status;
    // some lines deleted
};

/**
 * Returns an iterator to be used for iterating through a hash table.
 * Iterator will already point to the first element of the table it finds,
 * which can be accessed as iter.element.
 *
 * This function cannot fail, but if there are no elements in the table,
 * the returned iterator will return true for aws_hash_iter_done(&iter).
 */
AWS_COMMON_API
struct aws_hash_iter aws_hash_iter_begin(const struct aws_hash_table *map);

/**
 * Returns true if iterator is done iterating through table, false otherwise.
 * If this is true, the iterator will not include an element of the table.
 */
AWS_COMMON_API
bool aws_hash_iter_done(const struct aws_hash_iter *iter);

/**
 * Updates iterator so that it points to next element of hash table.
 *
 * This and the two previous functions are designed to be used together with
 * the following idiom:
 *
 * for (struct aws_hash_iter iter = aws_hash_iter_begin(&map);
 *      !aws_hash_iter_done(&iter); aws_hash_iter_next(&iter)) {
 *     const key_type key = *(const key_type *)iter.element.key;
 *     value_type value = *(value_type *)iter.element.value;
 *     // etc.
 * }
 *
 * Note that calling this on an iter which is "done" is idempotent:
 * i.e. it will return another iter which is "done".
 */
AWS_COMMON_API
void aws_hash_iter_next(struct aws_hash_iter *iter);
```
