### ISSUE TITLE
[observatory] feature request: upload result to a local server, so that we can analyse offline

### ISSUE THREAD

**Issue by macarthor** [dart-lang/sdk#44761]
it's a feature request instead of a bug, so i don't post the environment variables. but i'll do that if you need it.

for the great profiler observatory, we can only analysis on the fly in a single device, and it's up to the single developer/tester to care about the profiling data. he may or may not do it. we cannot analysis the profiling data for all the test devices of developers and testers as a whole. so i believe it's a giant waste of the profiling data.

i wonder if it's possible to upload the profiling data to a local server, so that we as a team can analyse the profiling data offline and don't waste the data.

l'll edit my post if it's wrong or not clear. 

thanks for reading.

**Comment by mraleph** [comment]
I don't think this is within scope for Dart SDK. vmservice protocol provides you a way to automatically pull profiling data from a running program, but we have no plans to build ready made server side solutions for aggregating profiling data from a fleet of devices. You would have to build something like this yourself.
