### ISSUE TITLE
typesafe checks for "T is int?" do not seem to work correctly.

### ISSUE THREAD

**Issue by pinkfish** [dart-lang/sdk#44777]
Running this snippet in the nullsafe dartpad and both of those prints return false.  I am not sure how to check the type of the input type here?  What should it be an 'is' of?  I think is 'int?' should work?

----

class Froggy<T extends num?> {
  Froggy(this.a, this.b);
  
  T a;
  T b;
  
  T doStuff() {
    print(T is int);
    print(T is int?);
    return (a??0 + (b??0)!) as T;  
  }
}

void main() {
  var a = Froggy<int?>(12, 10);
  print(a.doStuff());
}

**Comment by pinkfish** [comment]
I get an output of:
false
false
12

**Comment by mraleph** [comment]
Expression `T` evaluates to an instance of `Type`. So you are asking `(instance-of-Type) is int` and `(instance-of-Type) is int?` and correctly getting `false` for both of these questions.

You can do something like this 

```dart
bool isSubtype<S, T>() => <S>[] is List<T>;
// ...
T doStuff() {
  print(isSubtypeOf<T, int>());
  print(isSubtypeOf<T, int?>());
  return (a??0 + (b??0)!) as T;
}
```
