### ISSUE TITLE
interop error on flutter compile from PWA service_worker from isomorphic_fetch.dart

### ISSUE THREAD

**Issue by DoctorVirginia** [dart-lang/sdk#44778]
I am getting this error on compilation:
Target dart2js failed: Exception: /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/service_worker-0.2.4/lib/src/js_facade/isomorphic_fetch.dart:70:7:
Error: JS interop class 'Headers' conflicts with natively supported class 'Headers' in 'dart:html'.
class Headers implements HeadersInterface {
^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/service_worker-0.2.4/lib/src/js_facade/isomorphic_fetch.dart:97:7:
Error: JS interop class 'Body' conflicts with natively supported class 'Body' in 'dart:html'.
class Body implements BodyInterface {
^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/service_worker-0.2.4/lib/src/js_facade/isomorphic_fetch.dart:190:7:
Error: JS interop class 'Request' conflicts with natively supported class '_Request' in 'dart:html'.
class Request extends Body implements RequestInterface {
^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/service_worker-0.2.4/lib/src/js_facade/isomorphic_fetch.dart:270:7:
Error: JS interop class 'Response' conflicts with natively supported class '_Response' in 'dart:html'.
class Response extends Body implements ResponseInterface {
^
Error: Compilation failed.

And thereafter, the recurring error:
\src\flutter.pub-cache\hosted\pub.dartlang.org\service_worker-0.2.4\lib\src\js_facade\isomorphic_fetch.dart
[Error - 12:26:26 pm] Request textDocument/hover failed.
Message: Invalid file path
Code: -32003

Removing **only** all references to PWA package resolves the issue.

**Comment by sigmundch** [comment]
@DoctorVirginia - can you share details on the flutter/Dart SDK versions? (from `flutter doctor`)

/cc @kevmoo  - it appears like `package:service_worker` was using Js-interop on native types - maybe the package requires fixes?

/cc @srujzs - it's possible that the new validation is more breaking than we expected. It may be worth brainstorming whether to hide it under a flag and release it gradually with a new language version in the future.

**Comment by DoctorVirginia** [comment]
@sigmundch 
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.26.0-13.0.pre.178, on Microsoft Windows [Version 10.0.19041.746], locale en-AU)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.52.1)
[√] Connected device (2 available)

• No issues found!

**Comment by DoctorVirginia** [comment]
@sigmundch
and pubspec.yaml
pwa: ^0.2.0

**Comment by sigmundch** [comment]
Thanks @DoctorVirginia - sorry for the trouble, it looks like the details we want to see are hidden and we'd need the verbose output of `flutter doctor -v` (we'd like to see what's the hash/version of the Dart SDK embedded in flutter)

**Comment by srujzs** [comment]
Yeah, I think it makes sense to push it under a language version and declare it as a potential breaking change. I was hoping that almost all uses of a JS-interop class with a native class name would already be breaking on use, but maybe that isn't the case.

**Comment by DoctorVirginia** [comment]
No problem!

PS D:\flutter\nganka_wip5> flutter doctor -v
[√] Flutter (Channel master, 1.26.0-13.0.pre.178, on Microsoft Windows [Version 10.0.19041.746], locale en-AU)
    • Flutter version 1.26.0-13.0.pre.178 at C:\src\flutter
    • Framework revision 22f1700427 (17 hours ago), 2021-01-26 14:34:03 +0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!

**Comment by srujzs** [comment]
This change was language-versioned to 2.13. Depending on what your code is like, `@anonymous` classes be the best alternative here going forward if you can't use the native classes in `dart:html` directly.
