### ISSUE TITLE
[vm/ffi] Verify FFI calling conventions on Mac M1 in arm64 mode

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44772]
With the new hardware available we should check that the calling conventions on iOS arm4 and MacOS arm64 are identical.

**Comment by dcharkes** [comment]
@a-siva do we have an issue tracking building the Dart SDK for Mac M1 in arm64 mode?

**Comment by rmacnak-google** [comment]
FFI tests have been running on ARM64 Mac since 09fbf1ce60d3998665aef7e78ad0634c53290093
