### ISSUE TITLE
Typo crashes parser.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44781]
I wrote `class FB<T extends F> = S Function<S extends T>(S);` while writing a test. I meant to write `typedef` instead of `class`, but the result was that the analyzer crashed. The analysis server error contained:
```
type 'GenericFunctionTypeImpl' is not a subtype of type 'TypeName'

#0      AstBuilder.endNamedMixinApplication (package:analyzer/src/fasta/ast_builder.dart:1915:14)
#1      Parser.parseNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1886:14)
#2      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1866:14)
#3      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:580:14)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:476:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
```

If I try the line in `nullsafety.dartpad.dev`, I end up with XMLHttpRequest` errors for both analyzer and compiler, also supporting that it's a shared parser error.

**Comment by johnniwinther** [comment]
The crash happens on the analyzer side of things.

**Comment by lrhn** [comment]
Something also happens on the dart2js side when compiling in dartpad, which is why I assumed it to be shared code. It might just be a more widespread issue.

**Comment by johnniwinther** [comment]
Yes. Clearly _also_ a CFE issue.

**Comment by asashour** [comment]
This seems to be fixed.

**Comment by johnniwinther** [comment]
@asashour Thank for checking.
