### ISSUE TITLE
[Analyzer] Instance members mistakenly allowed by analyzer in static method anonymous function

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#44780]
I'm not sure of the exact intricacies of when/how this occurs, but refer to this [dartdoc PR issue](https://github.com/dart-lang/dartdoc/pull/2487#discussion_r564195710) for an actual example.

It seems that it at least occurs within a static method initial variable declaration(not assignment) where the instance member is being accessed within an anonymous function.

@scheglov @srawlins

**Comment by srawlins** [comment]
Here's a minimal repro:

```dart
class C {
  int get _i => 7;
  
  static _m() {
    [].firstWhere((e) => e == _i); // error on accessing _i.
    var x = [].firstWhere((e) => e == _i); // No error.
  }
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/181305
