### ISSUE TITLE
Dart2js running on ia32 is timing out after 1 minute when compiling a test

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#44793]
The dart2js compiler running on ia32 is timing out after a minute when compiling this test.
It passes on all other configurations.  Maybe we need to increase the timeout for dart2js compilation on ia32.

![image](https://user-images.githubusercontent.com/4905639/106063700-eed4a000-60f8-11eb-810e-5acae1d7aa3b.png)
This test has been timing out flakily for 8 months, is now timing out steadily.

The tests
```
pkg/js_ast/test/deferred_expression_test Timeout (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-linux-ia32-d8
```

**Comment by sigmundch** [comment]
@rakudrama - now that we no longer run the compiler in a browser, do we get any value out of running this package's tests in dart2js, should we just skip it there and focus on running them in the vm only?

**Comment by rakudrama** [comment]
This is not a big test - the generated JS is <400K unminified.
I would not want to close this out without understanding why the compile time is so long that it times out.
On my x64 workstation it compiles in 7.8s with a x64 vm, and in 8.8s with the ia32 vm.

What is the timeout duration?

**Comment by rakudrama** [comment]
We don't run dart2js on an ia32 VM in the real world, perhaps all the `-ia32-(d8|chrome|etc)` tests should be `-x64-` tests.
Tests would compile slightly faster since x64 has an advantage over ia32.

**Comment by sigmundch** [comment]
The timeout is 1 minute.

@rileyporter saw this happening also on her CL, so there may have been some general regression on the VM side?

I suggested to increase the limit to match what we do with the other bots. Her CL to increase the limit is here: https://dart-review.googlesource.com/c/sdk/+/181523

**Comment by rakudrama** [comment]
`dart2js-hostasserts-*` should uniformly have a timeout that is ~2x the non-`hostasserts`.
I guess 4x (240) is OK, but should not really be necessary.  I guess we get the 4x from 'Slow' in the old status files.

While we don't use `js_ast` in the browser, if it works we should keep it working and it might make a nice blob of code to add to a compile benchmark.

**Comment by rakudrama** [comment]
@whesse, did @rileyporter 's changes fix the timeouts?

**Comment by whesse** [comment]
Yes they did, this can be seen in both the results feed and the current results:

https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=pkg/js_ast/test/deferred_expression_test

https://dart-ci.firebaseapp.com/current_results/#/filter=pkg/js_ast/test/deferred_expression_test&showAll
