### ISSUE TITLE
[CP][beta channel] hide JS-interop breaking change

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#44796]
**commit(s) to merge**: e0cd4b37cfc8a1fbc205fa1fd89c082c439db4ad 

**merge instructions**: likely clean merge

**What is the issue**: A change was more breaking than intended and we want to undo that in 2.12. We'll introduce the breaking change gradually in the future (separate from the null safe release).

Additional details: We added new checks to DDC/dart2js to complain about invalid js-interop patterns. One pattern that is extremely buggy is to use JS-interop to use APIs also exposed in `dart:html`. The checks are a breaking change that affects buggy code. However, we found that sometimes the buggy code is in a lucky state and side-steps other issues. For those users the new checks became an unintended breaking change.

**What is the fix**: To hide the breaking change for now, and reintroduce it with language versioning in 2.13 or later.

**Why cherrypick**: prevent an unintended breaking change together with the null safe stable release.

**Risk**: low, cherry pick is very small and simple.

**Link to original  issue(s)**:  https://github.com/dart-lang/sdk/issues/44778

/cc @srujzs  @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by srujzs** [comment]
#44797 for the future fix.

**Comment by mit-mit** [comment]
sgtm

**Comment by vsmenon** [comment]
lgtm

**Comment by vsmenon** [comment]
( pending offline discussion )

**Comment by sigmundch** [comment]
update on offline discussion: we decided to move forward with this cherry-pick. /cc @franklinyow @athomas

Without the cherry-pick, the breaking change would be too broad. It breaks apps that work under 2.11 that transitively have an upstream dependency on a package using the invalid pattern. It would be hard to fix those apps because it involves coordination with package owners many levels away from the app's code.

We plan to add this breaking change via language versioning instead. Doing so will allow apps to continue to build without errors, since errors will only be provided on libraries that are updated to the latest version (with an sdk constraint in their pubspec, for example). In essence, language versioning makes the break lazy, and developers can fix them as needed.

The breaking change may still be part of 2.12 (we will discuss that separately), in which case we'll follow up with a cherry-pick that tweaks this change a bit further. If we decide to make the breaking change part of 2.13, then the other changes will not need to be cherry-picked.

**Comment by athomas** [comment]
Merged to beta with e5dd92c3ca766810e0e5a02d8725b1cebc19f564 (2.12.0-259.8.beta).
