### ISSUE TITLE
StreamController#addError talks about passing null, but null is forbidden

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#44795]
https://github.com/dart-lang/sdk/blob/7c148d029de32590a8d0d332bf807d25929f080e/sdk/lib/async/stream_controller.dart#L243

the docs say
```
If [error] is `null`, it is replaced by a [NullThrownError].
```
but this isn't true.  passing null is a static type error:
```
Error: The argument type 'Null' can't be assigned to the parameter type 'Object'.
```

**Comment by lrhn** [comment]
I believe that documentation has been updated on tip of tree: https://github.com/dart-lang/sdk/commit/4563164eec32b64ff99c18e4611195a38f3c72da
