### ISSUE TITLE
Address performance regression introduced in 63d17b0

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44799]
Address performance regression introduced in 63d17b0
(Please see https://github.com/flutter/flutter/issues/73794 for more details)

This issue has been created to track the Dart side changes to address the regression.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/181542 is the CL to revert the changes (63d17b0 and 0bf8d38).

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/181542 has landed

**Comment by mit-mit** [comment]
Is this still a P0 now that the revert has landed?

**Comment by a-siva** [comment]
I wanted it to be a P0 until I got the cherry pick request into the beta branch completed.

**Comment by a-siva** [comment]
A cherry pick request for this change into the beta branch has been created https://github.com/dart-lang/sdk/issues/44807,

lowering the priority and changing the milestone to reflect the forward fix that @rmacnak-google is working on.

**Comment by franklinyow** [comment]
@rmacnak-google Any update?  Are we on track for Feb. milestone?

**Comment by a-siva** [comment]
The revert addressed this performance issue and other changes will be tracked in https://github.com/dart-lang/sdk/issues/41974
