### ISSUE TITLE
[CP][Beta] - Revert changes that cause performance regression in Flutter benchmark

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44807]
Please cherry pick 27deca1457ad6b79eb3d22f16ab45b30b754e2eb into the beta branch

Reason : We had a performance regression in one of the Flutter benchmarks, please see
https://github.com/flutter/flutter/issues/73794

Impact: The change is a revert of two CLs 0bf8d38b3dbf498ad2e0d28116b673b9cb6d9c2f and 63d17b0ad85d87cc4911fa0f18dc7cf01a186c68.
The change has landed in master and has been rolled into Flutter framework without any issues.

The change merges cleanly into the beta branch and builds fine.

Risk: Low, has been merged into master and rolled into Flutter

Link to original issue https://github.com/flutter/flutter/issues/73794

**/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @sigmundch**

**Comment by vsmenon** [comment]
lgtm

**Comment by vsmenon** [comment]
fyi - @pcsosinski

**Comment by pcsosinski** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved

**Comment by athomas** [comment]
Merged to beta with e5dd92c3ca766810e0e5a02d8725b1cebc19f564 (2.12.0-259.8.beta).
