### ISSUE TITLE
add toSortedList method to Iterable

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#44802]
Right now, when we have a chained operation on Iterable, it's impossible to get the stuff sorted without interrupting the chain. 
Please consider adding `toSortedList([int compare(E a, E b)])`. (Contrived) example: 
`[5, 10, 0, 1].map((x)=>x*x).toSortedList().first`

**Comment by lrhn** [comment]
It's already doable as `.toList()..sort()`, so it's at most a convenience.
We've added that convenience as extensions to `package:collection:
* [`Iterable.sorted`](https://pub.dev/documentation/collection/1.15.0-nullsafety.5/collection/IterableExtension/sorted.html)
* [`Iterable<Comparable>.sorted`](https://pub.dev/documentation/collection/1.15.0-nullsafety.5/collection/IterableComparableExtension/sorted.html)

**Comment by tatumizer** [comment]
Won't it be a good idea to somehow include the reference to all package:collection methods into dart main documentation - maybe in a special section of the left panel ("standard extensions"). I encountered this (non-)problem when I had to help someone write a java interview test, where I used java "streams" (javaspeak for dart's Iterables), and one of the methods I used was "sorted", and it occurred to me that I don't know how to do it in dart nicely. 
There's a large collection of useful methods in "package:collection", but they are not discoverable. As an experiment, please try googling "iterable sorted dart".  Then you can go to the pub and enter "sorted" and see what you get.
