### ISSUE TITLE
package:vm_service does not properly parse fields among other properties

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#44800]
This [change](https://github.com/dart-lang/sdk/commit/fb5ffc827580ae49cd4611d3ddf0ad3c7c592c54#diff-60648d19c0fe66d08d01fb7a449378bb80241a95601fe86b3d34962586abb886) to null safety removed a bunch of property parsing logic for the `Instance` class. Thus `fields` among other properties are always null.

**Comment by grouma** [comment]
Note this will have a negative impact on debugging, both for native and web, through Dart DevTools and IDEs.

**Comment by jonahwilliams** [comment]
We should consider rolling back to a previous version of vm_service, if possible
