### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by todaelapps** [dart-lang/sdk#44803]
## Version information

- `IDEA AI-201.8743.12.41.7042882`
- `2.12.0-224.0.dev`
- `AI-201.8743.12.41.7042882, JRE 1.8.0_242-release-1644-b3-6915495x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.16, screens 1920x1080`

**Comment by todaelapps** [comment]
error: The function 'run' isn't defined. (undefined_function at [epctutor] integration_test/app_test.dart:14)

**Comment by keertip** [comment]
@todaelapps , can you give more information? Steps to reproduce?

**Comment by srawlins** [comment]
Please re-open if you get more information.
