### ISSUE TITLE
Explicit VM C API for setting up / tearing down the timeline recorder

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#44814]
If one thread calls `Dart_TimelineEvent` while another thread is calling `Dart_Cleanup`, a racy crash is possible: https://github.com/flutter/flutter/issues/74134. Gating the call to `Dart_TimelineEvent` on a lock introduces the potential for deadlock because `Dart_Cleanup` may be waiting on that thread as part of its work (e.g. if that thread hosted an isolate). Gating the call to `Dart_TimelineEvent` on a flag toggled just before the `Dart_Cleanup` call reduces the likelihood of a race, but the possibility still exists. An explicit call to shutdown the timeline recorder, would allow clients to avoid races altogether.

See the discussion on the PR https://github.com/flutter/engine/pull/24007#issuecomment-770141888 for details.

/cc @a-siva @rmacnak-google

**Comment by chinmaygarde** [comment]
Another case where fixing this bug would help https://github.com/flutter/flutter/issues/78936.

**Comment by a-siva** [comment]
A [CL](https://dart-review.googlesource.com/c/sdk/+/209761) to fix racy access to the timeline recorder through the Dart API has been landed. Closing this issue.
