### ISSUE TITLE
[CP][beta channel] DDC fix for async methods with `Object` return type

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#44812]
**commit(s) to merge**: f5743e6c66d8cf4460bc1e09454d1130827f46b3

**merge instructions**: Merges cleanly

**What is the issue**: In DDC compiled applications running in sound mode, async methods explicitly typed to return `Object` would produce a type error on code paths that return `null`.

**What is the fix**: Detect async methods explicitly typed to return `Object` and update the Future value type of the returned value to be `Object?`. This was an addition to the null safety spec https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#the-future-value-type-of-an-asynchronous-non-generator-function.

**Why cherrypick**: Fixes a bug in DDC's null safety implementation when running in sound mode.

**Risk**: Low. The fix only triggers when the return type of an async method is explicitly `Object`. Code that exercises this bug is broken now in sound mode with DDC. We have not received any bug reports other than the one filed by our external test suite writers.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44745

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @sigmundch

**Comment by franklinyow** [comment]
@sigmundch @vsmenon Do you want to approve this ?

**Comment by vsmenon** [comment]
lgtm

**Comment by sigmundch** [comment]
lgtm as well

**Comment by athomas** [comment]
Merged to beta with e5dd92c3ca766810e0e5a02d8725b1cebc19f564 (2.12.0-259.8.beta).
