### ISSUE TITLE
flutter-analyze bot (or similar) should analyze flutter/cocoon

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#44811]
Some flutter rolling process somewhere analyzes flutter/cocoon. If analysis reports anything, a bot turns red.

Given this situation, the flutter-analyze bot (or something similar) should analyze flutter/cocoon (presumably just on analyzer and _fe_analyzer CLs).

I think the philosophy is that anything which can break the flutter roll, and which will strongly prompt a rollback, must be presubmitted with a bot, like flutter-analyze. Without this check, nothing stops a swift roll-forward to re-break.

**Comment by srawlins** [comment]
CC @devoncarew

**Comment by aam** [comment]
Once https://dart-review.googlesource.com/c/recipes/+/186780 lands hhh will flutter-plugins that should analyze flutter/cocoon as well.

**Comment by devoncarew** [comment]
Closing this issue in favor of the fix in 5fe21f2ec1415aa45653eea2a7b9c186dc6d6722. I think the flutter-analyze bot is good for a 95% gut check of analysis changes to flutter repos, but the HHH bot will be more canonical.
