### ISSUE TITLE
[dev_compiler] Support widget inspector via expression compilation

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#44813]
**Issue**

Widget inspector for web platform does not show layout

**Repro**

- Create a flutter project with following code:
```
// @dart=2.9

import 'package:flutter/widgets.dart';

void main() {
  return runApp(
    Column(children: [
    const Center(
      child:
        Text('Hello, world!',
          key: Key('title'),
          textDirection: TextDirection.ltr
        )
      )
    ]
    ));
}
```

- Start debugging in VSCode (for web plaftorm)
- Open devtools widget inspector page
- Observe empty layout

![image](https://user-images.githubusercontent.com/12737689/106344575-67557100-625f-11eb-9092-16005fa0a5e3.png)

Expected result (from iPhone simulator):

![image](https://user-images.githubusercontent.com/12737689/106343858-5c4d1180-625c-11eb-9c3e-a92698d4fa01.png)

**How to see the evaluated expression and result in chrome**

- Start VSCode on the app code above
- Set the verbose mode in launch.json flutter configuration:
```
{
  "name": "Flutter",
  "request": "launch",
   "type": "dart",
    "args": ["-v"],
}
```

- Set a breakpoint inside `initServiceExtensions` in 
 `flutter/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart`
- Set flutter to run in chrome (web-javascript)
- Start debugging
- On breakpoint, copy and paste the dart expression (starting after `return library.` and ending before next line) from the information in the following bug:

https://github.com/flutter/devtools/issues/2627

- Copy and paste the JS expression from the VCCode debug console window to the chrome console window
- Observe result:
`VM973:50 Uncaught SyntaxError: Identifier 'e' has already been declared`

**Comment by annagrin** [comment]
Work needed for this:
- SDK: (ExpressionCompiler, FrontendServer, ExpressionCompilerWorker) support expression compilation in library scope (no line)
- SDK (ddc) make sure we generate JS expression that evaluates correctly and matches VM functionality
- dwds: use expression compiler in the implementation of the VM Service `evaluate()` API
- flutter tools: update dwds

**Comment by jacob314** [comment]
You should be able to get past the `e` has already been declared error by renaming the `(e)` in the various catch blocks to each have unique names in the expression being evaluated.

**Comment by franklinyow** [comment]
@sigmundch Can you assign an owner?
