### ISSUE TITLE
[CP][beta channel] merge a fix to 'flutter fix' related to parameter ordering into the upcoming 2.12 stable release

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#44810]
commit(s) to merge: 53f5179b45911fd1f937239f91e55ec8badd7975

merge instructions: clean merge

What is the issue:

Flutter contributed fixes that add a named argument insert the argument at the end of the argument list, which is often after the `children` argument.

What is the fix:

Arguments are added where the Flutter contributed fix indicates that they should be placed.

https://dart-review.googlesource.com/c/sdk/+/181820

Why cherrypick:

This will impact all flutter users using most of the Flutter provided quick fixes, both in the IDE and in the `dart fix` command-line tool.

Risk:

Low; it's a small delta to the code, and the fix was submitted just a few days after we branched

Link to original issue(s):

There was no issue, this was discovered during a dry run of the tooling talk.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
@bwilkerson, without an original issue, it will be really helpful to have a more descriptive title, and more context for the scrum to decided on the issue.

**Comment by devoncarew** [comment]
@franklinyow - I support this cherry pick

**Comment by vsmenon** [comment]
lgtm

**Comment by athomas** [comment]
Merged to beta with e5dd92c3ca766810e0e5a02d8725b1cebc19f564 (2.12.0-259.8.beta).
