### ISSUE TITLE
dart run hides part of error output

### ISSUE THREAD

**Issue by tslominski** [dart-lang/sdk#44823]
Dart version: Dart SDK version: 2.12.0-237.0.dev (dev) (Unknown timestamp) on "linux_x64"
OS: Ubuntu 18.04.5 LTS

Problem:
dart run hides part of error information normally shown by dart pub run

I've a syntax error in my pubspec.yaml

When I run 
`dart pub run test`
output is 

`Deprecated. Use dart run instead

Error on line 13, column 1 of pubspec.yaml: Expected ':'.

   ╷
13 │ dev_dependencies:
   │ ^
   ╵
`

But when I run 

`$ dart run test`
the only output is  
`Expected ':'.`

**Comment by bkonyi** [comment]
I'm able to reproduce when running `dart test` vs `pub run test`. I would expect that these would be consistent, but it looks like we aren't providing as much detail in the `CommandResolutionFailedException`'s `message`.
