### ISSUE TITLE
[CP] [Beta] Revert "[cfe] Handle conditional await in CFE" 

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44827]
Please cherry pick 34f9734b417ea281bf70422128ec9d3dc1c50f00 into the beta branch

Reason : We had some test failures after this change was rolled into Flutter, please see
flutter/flutter#75155

@dnfield has verified that the original CL has caused the test breakage.

The change does not merge cleanly into the beta branch, a CL with the merge conflicts resolved has been
created at https://dart-review.googlesource.com/c/sdk/+/182200

Risk: The intended spec change proposed in https://github.com/dart-lang/sdk/issues/44395 will not happen
stability risk is low, the revert has been merged into master and rolled into Flutter Engine.

Link to original issue flutter/flutter#75155

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @leafpetersen @sigmundch

**Comment by franklinyow** [comment]
I'm approving this, I believe there are enough eyes on this one.

**Comment by athomas** [comment]
Merged to beta with e5dd92c3ca766810e0e5a02d8725b1cebc19f564 (2.12.0-259.8.beta).
