### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by ujas-m-simformsolutions** [dart-lang/sdk#44820]
https://fartlang.org/guides/language/analysis-options.html 
in this page everywhere is written fart instead of dart and even in the url it's fart.

**Comment by athomas** [comment]
That page is not affiliated with the Dart project, but describes the fictional "Fart" language which happens to be very similar to Dart. The dart project is hosted at https://dart.dev but some URLs refer to our old site https://www.dartlang.org.
