### ISSUE TITLE
Cause "null pointer dereference" when call dart-side function in c-side Dart_HandleFinalizer 

### ISSUE THREAD

**Issue by xuchaoqian** [dart-lang/sdk#44833]
**### 1. Code as following:** 
`
typedef void (*FinalizerImpl)(void *);

struct _finalizable_pointer_t {
  void* pointer;
  FinalizerImpl finalizer;
};

void _finalizer_callback(void* isolate_callback_data, void* peer) {
  _finalizable_pointer_t* peer2 = (_finalizable_pointer_t*)peer;
    peer2->finalizer(peer2->pointer); // **_Causes "null pointer dereference" here, this is a dart-side function._**
    peer2->pointer = NULL;
    peer2->finalizer = NULL;
    delete peer2;
}

int attach_finalizer(Dart_Handle object,
                                       void* pointer,
                                       FinalizerImpl finalizer,
                                       intptr_t external_allocation_size) {
  _finalizable_pointer_t* peer = new _finalizable_pointer_t();
  peer->finalizer = finalizer;
  peer->pointer = pointer;
  // peer->finalizer(peer->pointer); // **_Works fine here._**
  Dart_FinalizableHandle handle = NULL;
  handle = Dart_NewFinalizableHandle_DL(object, (void*)peer, external_allocation_size, _finalizer_callback);
  if (handle == NULL) {
    delete peer;
    return -1;
  }
  return 1;
}
`

**### 2. Environment as following:** 
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (11 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

@dcharkes

**Comment by mraleph** [comment]
You can't call back into Dart from finalizers, this is not allowed.
