### ISSUE TITLE
Null safety - beta vs stable channel

### ISSUE THREAD

**Issue by bermanapps** [dart-lang/sdk#44836]
I'm new to dart, and I'm starting off with learning about the new null safety in dart.

What I understand is that its only working when I'm on the dart channel beta, but when I'm on the stable version it doesn't work. Meaning the terms: ? and !, and late, etc, when I'm on the stable version causes all errors in my code. It only works if I'm on the beta version.

Is this OK that all my code will only be working on the beta version? When I want to publish my app, etc, is this ok that its written in the beta version, not stable.

Sorry for the basic quetsion, but I cannot get to the bottom of this.

**Comment by keertip** [comment]
@bermanapps , see that there are some responses to your question on [stackoverflow](https://stackoverflow.com/questions/66016083/flutter-using-null-safety-beta-vs-stable-channel), with reccomendations on what to follow.

Closing this as answered.
