### ISSUE TITLE
Analyzer support for type arguments on annotations

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44838]
(Parent issue #44917)

This issue tracks the analyzer work necessary to support type arguments on annotations, for example:
```dart
@TypeHelper<int>(42, "The meaning")
```
For justification and additional planning details, please see:
- The feature request in the language issue tracker: https://github.com/dart-lang/language/issues/1297
- The feature specification: https://github.com/dart-lang/language/blob/master/accepted/future-releases/small-features-21Q1/feature-specification.md
- The implementation plan: https://github.com/dart-lang/language/blob/master/accepted/future-releases/small-features-21Q1/implementation-plan.md
- The implementation plan PR: https://github.com/dart-lang/language/pull/1417

**Comment by scheglov** [comment]
@leafpetersen @eernstg  Are we allowed to combine generic metadata and generic functions as type arguments? Is this valid code?
```dart
class A<T> {
  const A();
}

@A<U Function<U>()>()
void f() {}
```
Or with inference?
```dart
class A<T> {
  const A(T _);
}

@A(g)
void f() {}

U g<U>() => throw 0;
```

**Comment by eernstg** [comment]
I see no reason to make that combination an error, whether inferred or written explicitly.

**Comment by scheglov** [comment]
AFAIK this is done.

**Comment by leafpetersen** [comment]
https://github.com/dart-lang/sdk/issues/45579

**Comment by scheglov** [comment]
#45579 was fixed.
