### ISSUE TITLE
js-interop: 

### ISSUE THREAD

**Issue by marqueetest** [dart-lang/sdk#44832]
**Error: Not found: 'dart:js'**

**run time issue**

* Dart SDK version: *2.10.5*
* pkg/js version: *0.6.2*

Failing code:
```
 getCurrentPosition(allowInterop((pos) => success(pos)));
```

![Screenshot 2021-02-02 162936](https://user-images.githubusercontent.com/59277680/106591115-e1456d00-6573-11eb-8755-f538174d97bc.jpg)

**Comment by natebosch** [comment]
It looks like you are trying to use a web only package on the flutter mobile or the VM. That is not expected to work, but also shouldn't give a stack trace.

Please file an issue at https://github.com/flutter/flutter. Be sure to include the command you ran. If possible include a minimal reproduction.
