### ISSUE TITLE
Windows failures on standalone/io/large_file_read_small_file_test

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#44846]
There are new test failures on [[package:js] Added checks for external non-JS members....[VM] Adds Debugger break for Future.catchError](https://github.com/dart-lang/sdk/compare/dfd5413952ee5232235adf460575a1a7c2674874~...cfa35be6f03d7bca902d66f1497cc7f71edb3c3f).

The tests
```
standalone/io/large_file_read_small_file_test RuntimeError (expected Pass)
standalone_2/io/large_file_read_small_file_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-win-release-ia32
dartk-weak-asserts-win-release-ia32
dartk-win-debug-ia32
dartk-win-release-ia32
```

[Example log](https://dart-ci.appspot.com/log/vm-kernel-nnbd-win-release-ia32/dartk-strong-win-release-ia32/125/standalone/io/large_file_read_small_file_test):

```
--- Command "vm" (took 06.000593s):
set DART_CONFIGURATION=ReleaseIA32 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseIA32\crashpad_handler.exe & out\ReleaseIA32\dart.exe --sound-null-safety --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\tests\standalone\io\large_file_read_small_file_test.dart

exit code:
255

stderr:
Unhandled exception:
FileSystemException: read failed, path = 'C:\b\s\w\itpckxdq\large_file_read85c458f0\hello_world.txt' (OS Error: Not enough storage is available to process this command.

, errno = 8)
#0      _RandomAccessFile.read.<anonymous closure> (dart:io/file_impl.dart:746:9)
<asynchronous suspension>
#1      main.<anonymous closure> (file:///C:/b/s/w/ir/tests/standalone/io/large_file_read_small_file_test.dart:38:21)
<asynchronous suspension>
#2      runWithTempDir (file:///C:/b/s/w/ir/tests/standalone/io/large_file_read_small_file_test.dart:13:5)
<asynchronous suspension>
#3      main (file:///C:/b/s/w/ir/tests/standalone/io/large_file_read_small_file_test.dart:25:3)
<asynchronous suspension>

--- Re-run this test:
python tools/test.py -n dartk-strong-win-release-ia32 standalone/io/large_file_read_small_file_test
```

/cc @mkustermann

**Comment by mkustermann** [comment]
I hope the 2 CLs I landed will get rid of this issue.

**Comment by sstrickl** [comment]
Noting that it went from RuntimeError -> Timeout on dartk-win-release-ia32 last night after these changes ([logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8853807781782426352/+/steps/test_results/0/logs/new_test_failures__logs_/0)).

**Comment by mkustermann** [comment]
I'll have to get a windows machine and try to debug it. Possibly I'll just skip the tests on windows then. They are fulfilling their purpose on linux where the issue was observed.
