### ISSUE TITLE
Ambiguity on `BoundField.value`

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#44842]
`BoundField.value` claims to be one of a few non-null types, but is itself nullable:

https://github.com/dart-lang/sdk/blob/e1273e96e8234e919e4738d2ab2c85b5b545ec31/pkg/vm_service/lib/src/vm_service.dart#L2660-L2661

I was surprised to find for null values returned over the VM service protocol that `value` is indeed just plain `null`, and not an `InstanceRef` of `InstanceKind.kNull`.

Is this intended or a bug? If intentional, perhaps the field should be documented to explain when it's null (and if it can ever be an `InstanceRef` of `InstanceKind.kNull`).

@bkonyi @jacob314 @grouma

**Comment by grouma** [comment]
This sounds like a bug within `package:dwds` if it should be `InstanceKind.kNull`. I'll let @bkonyi provide input before moving it over to `package:dwds`.

**Comment by bkonyi** [comment]
I think this is a `package:vm_service` issue that's flown under the radar for awhile. We check for a null `@Instance` [here](https://github.com/dart-lang/sdk/blob/e1273e96e8234e919e4738d2ab2c85b5b545ec31/pkg/vm_service/lib/src/vm_service.dart#L39) but then end up checking if `@Instance` is a member of `['InstanceRef', 'TypeArgumentsRef', 'Sentinel']` which obviously fails, so we always end up returning `null` if we see an `@Instance` with type `Null`.
