### ISSUE TITLE
Assign void to a field on constructor

### ISSUE THREAD

**Issue by pak3nuh** [dart-lang/sdk#44865]
[Edit by eernstg: This is labeled as an analyzer bug because there is a missing error, cf. [this comment](https://github.com/dart-lang/sdk/issues/44865#issuecomment-773976031).]

This tracker is for issues related to:
* Analyzer

Hello,

In every IDE I've used, the following snippet was not an error detected by the analyzer, but the compilation still fails because I'm trying to assign void to a `List<int>`:
```dart
class Sorter {
  final List<int> sorted;
  Sorter(List<int> list) : this.sorted = list.sort(Comparable.compare);
}
```

I'm using a Linux machine with Flutter 1.22.5 and Dart 2.10.4.

This issue is also visible on the [Dartpad](https://dartpad.dev), but only when null safety is false. When null safety is enabled, it picks the error correctly.

Thanks

**Comment by eernstg** [comment]
It is a compile-time error to evaluate an expression of type void (like `list.sort(Comparable.compare)`, unless the result is used in specific ways (cf. [this specification rule](https://github.com/dart-lang/language/blob/5172c69f3918996908b844a6bba64a5115c9d444/specification/dartLangSpec.tex#L18708)).

**Comment by eernstg** [comment]
Just tried out a variant of the example as follows:

```dart
// @dart = 2.9

class Sorter {
  final List<int> sorted;
  Sorter(List<int> list) : this.sorted = list.sort(Comparable.compare);
}

void main() {}
```

This program does indeed get accepted by the `dartanalyzer` from c88171c8af52aaae166d2fcd0a4f7c75bf6a0a5b, so there's a missing compile-time error. Added labels for that.

**Comment by pak3nuh** [comment]
Actually, I assumed that `sort` would produce e new sorted list, only to realize the opposite when I tried to launch the app.
I do understand that `void` is a valid type and can be assigned, and that is why I got confused as to why the analyzer didn't complain.

Thanks for the info :)

**Comment by lrhn** [comment]
What I'd write in this situation is:
```dart
  Sorter(List<int> list) : sorted = list..sort();
```
The cascade evocation `list..sort()` sorts the list the same ways as `list.sort()`, but then evaluates to the list again. It's why Dart generally doesn't have methods return the object itself again, like other languages where that's the way to do method chaining.

The `Comparable.compare` is not needed, it's the default for `sort`. If you want to improve performance slightly, use `(int a, int b)=>a.compareTo(b)` to avoid doing dynamic calls.

**Comment by eernstg** [comment]
@pak3nuh, I've edited your initial text of this issue, in order to ensure that the analyzer team can see why it is labeled as a bug.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/183763
