### ISSUE TITLE
[CP] [frontend_server] Don't print `Severity.info` messages

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44869]
**commit(s) to merge**: 5bfeed21c1af642d97d0ff5f8d9ba47d3af1181e

The frontend_server emitted `info`s on the output stream (stderr in Flutters case). The CLs I landed earlier were the first use of emitting `info`s, and we would not like to emit `info`s from the frontend_server because it clutters the stderr when running Flutter apps.

**Merge instructions**: Merges cleanly.

**Why cherrypick**: P0 in Flutter https://github.com/flutter/flutter/issues/75429.

**Risk**: Low, no other `info`s are ever emitted from the frontend_server.

Link to original issue(s): https://github.com/flutter/flutter/issues/75429 and https://github.com/dart-lang/sdk/issues/44867.

**Comment by dcharkes** [comment]
@franklinyow @vsmenon @mit-mit @kevmoo @a-siva @athomas

**Comment by a-siva** [comment]
lgtm

**Comment by franklinyow** [comment]
@pcsosinski @johnniwinther

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved

**Comment by athomas** [comment]
Merged to beta in bc1fa173477efb6192bddd5f95c1ad0cccbc8d6f (2.12.0-259.9.beta).
