### ISSUE TITLE
[CP] [Beta] - Add back accidentally removed pragma on scheduleMicrotask

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44873]
Please cherry pick 98d5ecb5533d20677430b168e6672260cf2c2b4e into the beta branch

Reason : We had a fix for 177110012 in daef1f0dbf8a35c689ad478ce320eb452525af9b but that was inadvertently removed in b837038cf9ca8f3556b82c5056a29a126e7d6915

Impact: Some of the tests were timing out before this fix was made. All embedder code that uses the scheduleMicrotask could get affected

The change merges cleanly into the beta branch and builds fine.

Risk: Low, the change was in master and rolled into Flutter/Google3 before it was inadvertently deleted. The change is a one liner.

Link to original issue : 177110012

**/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @regis**

**Comment by franklinyow** [comment]
Approved in SCRUM meeting

**Comment by athomas** [comment]
Merged to beta in cc15e7439ae2c596b2ca0c5c032e294a20843e30 (2.12.0-259.12.beta).
