### ISSUE TITLE
Suppress `invalid_use_of_visible_for_testing_member` with @visibleForTesting

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/sdk#44870]
It seems like we should be able to suppress the `invalid_use_of_visible_for_testing_member` linter warning by tagging the member with `@visibleForTesting` 

<img width="1192" alt="Screen Shot 2021-02-05 at 10 31 07 AM" src="https://user-images.githubusercontent.com/666539/107053935-72e3f300-679d-11eb-873a-9d667b74f43b.png">

## MCVE

```dart
import 'package:flutter/foundation.dart';

class Foo {
  @visibleForTesting
  String get value => 'foo';
}
```

```dart
import 'package:flutter/foundation.dart';

import 'foo.dart';

class Bar implements Foo {
  Bar(this.foo);

  final Foo foo;

  @override
  @visibleForTesting
  String get value => foo.value;
}
```

**Comment by lukepighetti** [comment]
Looks like this might be two issues wrapped in one.

1. suppress `invalid_use_of_visible_for_testing_member` warning with use of `@visibleForTesting`
2. not triggering `invalid_use_of_visible_for_testing_member` on implementing classes

**Comment by srawlins** [comment]
Sorry to not look at this for a year 😞 . But this is working as expected. If `Bar.value` should not access `Foo.value` because `Bar.value` is not in the same library, nor is it in a test. Whether `Bar.value` is public, private, or visible-for-testing is not relevant.

**Comment by lukepighetti** [comment]
Agreed
