### ISSUE TITLE
It's very troublesome to import extension method.

### ISSUE THREAD

**Issue by SuperBeagleDog** [dart-lang/sdk#44875]
**Code Snippet.**
`  extension Foo on String{
    void test(){}
 }`

**In this case,** 
we can't simply use test() function on an instance of String, 
Like this ` "test".test()` with **"alt+Enter" automatically importing**:

We can't use **"quickly import"** feature in Android Studio to give an instance of String the ability to call test() method in Dart.

**Kotlin can do this but Dart can't!** 

To import this extension function, I either copy the path of "Foo" , or type Foo name in another file to get "quickly import feature" and then delete this useless name.

Therefore, I hope you can improve this issue as quickly as you can, or give us an easier way to import extension functions.

**Thanks.**

**Comment by scheglov** [comment]
@bwilkerson

**Comment by The-Redhat** [comment]
https://github.com/dart-lang/sdk/issues/38894 is similar

**Comment by DanTup** [comment]
This was implemented a while ago - both in code completion as an auto-import, and as a quickfix:

https://github.com/user-attachments/assets/2c7ff5ed-eecc-412d-8aa5-4271569f6e8d
