### ISSUE TITLE
Nothing to repeat at Regex (*SKIP)(*F)

### ISSUE THREAD

**Issue by sushilbalami** [dart-lang/sdk#44878]
I am using Regex this way

```
  var str = "r\(.*?;.*?\)(*SKIP)(*F)|;"; 
  RegExp _regExp = RegExp(str);
  html = html.replaceAllMapped(_regExp, (Match m) => ";\n");
```
Tried by putting
```"r\\(.*?;.*?\\)(*SKIP)(*F)|;";```
```"r\\(.*?;.*?\\)(*SKIP)(*FAIL)|;";```
but cannot be resolved.
working well while testing see here: https://regex101.com/r/x63m3p/1
how to resolve it. any bug or I couldn't figure out.
I want to figure out this thing: https://stackoverflow.com/questions/66076472/selecting-semi-colon-except-of-small-brackets
one person gave the answer but that regex not working on a dart.
I think (*SKIP) & (*FAIL) is not supported on dart it what.
can anyone resolve it?

**Comment by lrhn** [comment]
You're using PCRE syntax in the regex101.com link. Dart use JavaScript regular expression syntax. It does not have something corresponding to `*SKIP` or `*FAIL`.

To avoid semicolons inside parentheses, I'd use a negative lookbehind instead.

Try:
```dart
var str = r"(?<!\([^)]*);";
```
([regex101](https://regex101.com/r/nJl2OO/1))

That's probably not particularly efficient, so what I'd really do, to match your original behavior, is:
```dart
var re = RegExp(r"\(.*?\)|;");
html = html.replaceAllMapped(_regExp, (Match m) => m[0].startWith("(") ? m[0] : ";\n");
```
(That is: Just match the parenthesized groups, and then ignore them in the replace).

**Comment by sushilbalami** [comment]
var html =
      """//exampleint g; String a="random";int j=0; for (int i = 1; i <= 10; ++i){
    printf("Random");
}""";
so i want to break on before int except small brackets () 
Expected output:
```
//example
int g; String a="random";
int j=0; for (int i = 1; i <= 10; ++i){
    printf("Random");
}
```

except inside small brackets ...

**Comment by lrhn** [comment]
Breaking before `int`, except inside parentheses. I'd do that as:
```dart
var re = RegExp(r"\(.*?\)|(?=int\b)");
html = html.replaceAllMapped(re, (Match m) => m[0].startsWith("(") ? m[0] : "\n");
```
I *wanted* to add `\b` before `int` too, but the "exampleint` prevented that. I added it after to avoid breaking inside `printf`, but that's just getting lucky (if it had been `print`, it wouldn't have worked).

**Comment by sushilbalami** [comment]
Sorry to bother you .. and maybe the last question from mine
```
#include <stdio.h>\n

int main() {
  int number1, number2, sum;
  printf("Enter two integers:\n ");
  scanf("%d %d", & number1, & number2);
  sum = number1 + number2;
  printf("%d + %d = %d", number1, number2, sum);
  return 0;
}
```

I want to replace the \n that are inside small brackets  this ->  ` printf("Enter two integers:\n ");`  with `\\n`  and left others as it is.
actually, I don't know regex much.

**Comment by lrhn** [comment]
You have the same issue of recognizing matching pairs of quotes, made worse by not being able to distinguish start and end quotes.

I'd probably do something like:
```dart
// Match string literals. (Not completely safe, might match `"` inside comments.
var re = RegExp(r'"(?:[^"\\\n]|\\[^])*"');
input = input.replaceAllMapped(re, (m) => m[0].replaceAll(r"\n", r"\\n"));
```
That is, try to find string literals, from `"` to the next matching `"`.
Then replace the string literal with itself, except replacing `\n` by `\\n`.

The input looks like C code, so I won't assume that string literals can be `'` or `"""` quoted like in Dart.
They can be multiline, but only if a line ends in `\`.

There are still lots of ways that that can fail: A `"` inside a comment looks like it starts a comment.
The way to avoid *that* is to also detect comments:

// Match string literals and comments (`//` to EOL, `/*` to next `*/`).
var re = RegExp(r'"(?:[^"\\\n]|\\[^])*"|/(?:/.*\n|\*(?:[^*]+\*+?)*\*/');
input = input.replaceAllMapped(re, (m) {
  var c = m[0];
  if (c.startsWith("/")) return c; // it's a comment
  return c.replaceAll(r"\n", r"\\n"));
});
```

Probably massive overkill. :)

**Comment by sushilbalami** [comment]
`int main(){ int array[] = {2,3,4,5}; }`
this is the code and i want to put {\n so after { line breaks 
i want to put on only those 
now i am doing 
```
  html = html.replaceAll(") {", ") {\n");
  html = html.replaceAll("){", "){\n");
  html = html.replaceAll("}", "}\n");
  html = html.replaceAll("{", "{\n");
```

so I want to break line on `){` or `) {` or `{` 
except for these curly braces
`{2,3,4,5};`

**Comment by lrhn** [comment]
Challenge accepted.

Your problem is that `{` and `}` can occur in expressions like `{2,3,4,5}` as well, so you have to somehow make a distinction between those that are statement blocks and those that are expressions. That's non-trivial, so let's go with a heuristic approach (something that usually works, but not always. I'm again assuming this is C or C++ syntax (so I won't try to match Dart syntax).
I think you actually want a newline *before* a final `}`, not after.

If it's C, then `{2,3,4,5}` is an array literal, and those can only occur after a `=`, and can therefore only be followed by `,` or `;`,
except that they can be nested and comma separated, so a literal `{` can also follow a `{` or `,` and a `}` can be followed by a `}` or `,`.
Since valid block can also have `}}`, like `for (int i = 0; i < 10; i++) { while (true) {}}` (notice last two chars), we can't generally treat `}` followed by `}` as an expression `}`. Heuristically, let's go with splitting at those.
```dart
// Any `{` not preceded by `=`, `{` or `m` and any `}` not followed by `;` or `,`..
var re = RegExp(r"(?<![={,]\s*)\{|\}(?!\s*[;,])");
// Add `\n` after matched `{`, or before matched or `}`.
var replacement = const {"{": "{\n", "}": "\n}"};
html = html.replaceAllMapped(re, (m) => replacement[m[0]]);
```
I'd probably also check that the brace isn't already followed/preceded by a newline.
```dart
// `{` not following `=`, `,` or `{` and not already followed by `\n`,
//  or `}` not followed by `;`, `,` or `}`, and not already preceded by `\n`.
// Or: whitespace at beginning of line.
var re = RegExp(r"(?<![={,]\s*)\{(?!\s*?\n)|(?<!\n\s*?)\}(?!\s*[;,])");
```

And then it's might be worth considering indentation, but that's a much bigger can of worms.
