### ISSUE TITLE
Analyzer assist test starts failing with CL 117542

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44871]
Test pkg/analysis_server/test/src/services/correction/assist/convert_to_package_import_test starts failing when committing https://dart-review.googlesource.com/c/sdk/+/117542
@pq believes it to be a problem in the test.

**Comment by pq** [comment]
Thanks!

**Comment by DanTup** [comment]
I don't know if there's a race here, but between yesterday and today I've seen this test both pass and fail at least twice each when running the analysis_server/test_all.dart locally without any related changes.
