### ISSUE TITLE
detached console windows do not shows on Process.start

### ISSUE THREAD

**Issue by bubnenkoff** [dart-lang/sdk#44884]
I need to run external python script from Dart. I want to see it console window at start. But the process window do not shows even if I am running process as detached.
```
import 'dart:io';

main() async {
    String python_script_path = "D:/code/test.py";
    await Process.start("python", [python_script_path], workingDirectory: "D:/code/", mode: ProcessStartMode.detached);
}
```

test.py:
```
import time
print("Hello")
time.sleep(10)
print("World")

with open('my_file.txt', 'w') as f:
    f.write('some text')  # 
```

And it's very strange that `my_file.txt` get text too fast. Like `time.sleep(10)` not work.

```
dart --version
Dart SDK version: 2.12.0-133.7.beta (beta) (Tue Jan 12 09:25:38 2021 +0100) on "windows_x64"
```

**Comment by mit-mit** [comment]
Sorry, it's not clear what the Dart issue is. Closing as un-actionable.
