### ISSUE TITLE
[dart2native] generates .exe by default on macos.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#44891]
`dart2native my_dart_file.dart` generates a `.exe` on macos.

`Dart SDK version: 2.12.0-259.8.beta (beta) (Tue Feb 2 15:59:29 2021 +0100) on "macos_x64"`

**Comment by julemand101** [comment]
Can you execute the file? The .exe file extension is typical for Windows but does just indicate the file is an executable. I know on Linux the default are also to have .exe as extension but it is a fully functional Linux binary.

**Comment by modulovalue** [comment]
> Can you execute the file?

Yes

**Comment by mkustermann** [comment]
The fact that `dart2native` always uses `.exe` as default extension on all platforms is controversial. Though now that it is the default we'd need to do a breaking change, possibly breaking many people's shell scripts, so I'm not sure if we want to do so.
This issue has been reported before, e.g. https://github.com/dart-lang/sdk/issues/39282.

It's possible to specify a different output filename by using the `-o` option. @modulovalue Would that work for you?

If you feel strongly about it, you could try to make a case for it in a breaking change request (see [docs/process/breaking-changes.md](https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md)).

**Comment by modulovalue** [comment]
It is saddening to read in #39282 that this could've been fixed over a year ago.

> @modulovalue Would that work for you?

Yes, thank you.

**Comment by mkustermann** [comment]
> It is saddening to read in #39282 that this could've been fixed over a year ago.

@modulovalue I agree.
