### ISSUE TITLE
Expose "why not promoted" information in VSCode

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44902]
(Parent issue #44897)

As of a42244f73b27256eca44def4daa552e91c2dbc55, the analyzer now generates context messages in some circumstances explaining why type promotion failed.  We would like these messages to show up in VSCode in a way that's easily discoverable.

**Comment by bwilkerson** [comment]
@DanTup

**Comment by devoncarew** [comment]
I filed https://github.com/Dart-Code/Dart-Code/issues/3136 (and will close this issue in favor of that one).
