### ISSUE TITLE
Make "why not promoted" information more discoverable in IntelliJ

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44901]
(Parent issue #44897)

As of a42244f73b27256eca44def4daa552e91c2dbc55, the analyzer now generates context messages in some circumstances explaining why type promotion failed.  IntelliJ integration exposes these messages to the user via a right click on the error message.  We would like these messages to show up in a way that's more easily discoverable.

Yesterday we discussed some possibilities for how to do this.  In an ideal world we'd like the "problems" view to have a tree structure so that the user can see context messages as collapsible leaves underneath the error messages.  Unfortunately there are performance limitations getting in the way of doing this when the error count is large.  Possible ways around the performance issues include:

- Switching to a table view when the error count is large
- Automatically filtering to just the current file (or perhaps folder) when the error count is large
- displaying the context messages as a new, third column in the problems view

In addition, we might want to display the context messages in the tooltips for the analysis errors.

**Comment by stereotype441** [comment]
@jwren any progress on this?

**Comment by jwren** [comment]
Yes, the content is now shown, it was not in IJ, but now is:

![pkfphcocockpbiao](https://user-images.githubusercontent.com/1533520/108762157-9a102380-7504-11eb-81f2-506d167a52ce.png)

Other opportunities still exist to make it better which can be tracked with other issues as needed.
