### ISSUE TITLE
Expose "why not promoted" information in DartPad

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44903]
(Parent issue #44897)

As of a42244f73b27256eca44def4daa552e91c2dbc55, the analyzer now generates context messages in some circumstances explaining why type promotion failed.  We would like these messages to show up in DartPad in a way that's easily discoverable.

**Comment by johnpryan** [comment]
This is related to https://github.com/dart-lang/dart-pad/issues/1676, which will show the context / diagnostic messages.

**Comment by bwilkerson** [comment]
Yes, it's exactly the same work.

**Comment by devoncarew** [comment]
I'm going to close this in favor of the existing dartpad issue (https://github.com/dart-lang/dart-pad/issues/1676).
