### ISSUE TITLE
Handle the unsigned shift, triple-shift, >>> operator in analyzer

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#44908]
This is the analyzer implementation subtask under https://github.com/dart-lang/language/issues/478. Broad feature here: https://github.com/dart-lang/language/issues/120.

Here is the accepted feature: https://github.com/dart-lang/language/tree/master/accepted/future-releases/small-features-21Q1

* [x] Implementation in Analyzer (dart-lang/sdk#44908)
  * [x] analysis_server core features (~Go To Definition~ (does not work for operators broadly; https://github.com/dart-lang/sdk/issues/39911), Find References, Sort Declarations)
  * [x] analyzer: include triple shift test cases in existing diagnostic tests
  * [x] linter: consider existing lints; add test cases regarding triple shift

**Comment by srawlins** [comment]
After reviewing the existing lint rules, I see none which need new test cases or implementation for triple-shift.

**Comment by franklinyow** [comment]
Any update here?

**Comment by srawlins** [comment]
I'll call this done. I don't think there is any analysis_server work to be done.
