### ISSUE TITLE
Implement the Q1 2021 small features release in the VM/AOT

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44914]
Implementation issue for [this set of features](https://github.com/dart-lang/sdk/issues/44911).

cc @a-siva @mkustermann @mraleph @franklinyow

**Comment by leafpetersen** [comment]
See [also](https://github.com/dart-lang/sdk/issues/30892).

**Comment by a-siva** [comment]
Here are the 3 sub tracking issues for this

- Implement the triple shift operator https://github.com/dart-lang/sdk/issues/30892
- Allow generic function types as type arguments https://github.com/dart-lang/sdk/issues/44930
- Allow type arguments on annotations https://github.com/dart-lang/sdk/issues/44931

**Comment by leafpetersen** [comment]
@a-siva any updates here?

**Comment by a-siva** [comment]
@crelier is waiting for the CFE implementation for generic types as type arguments to be done so he can verify it on the VM

**Comment by franklinyow** [comment]
#44930 is closed.

**Comment by a-siva** [comment]
The language features are all implemented, we will be tracking test failures in these new features in individual issues for each failure.
