### ISSUE TITLE
Implement the Q1 2021 small features release in the CFE

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44916]
Implementation issue for [this set of features](https://github.com/dart-lang/sdk/issues/44911).

See [also](https://github.com/dart-lang/sdk/issues/30888).

cc @johnniwinther @franklinyow

**Comment by leafpetersen** [comment]
@stefantsov any updates?

**Comment by stefantsov** [comment]
The support for GFT in type arguments and bounds landed as https://dart-review.googlesource.com/c/sdk/+/188701.

**Comment by nshahan** [comment]
@stefantsov @eernstg 
I'm seeing compile time errors for the tests that were landed for the Generic Function Types in type arguments and bounds feature. https://dart-ci.firebaseapp.com/current_results/#/filter=language/generic/generic_function_type_argument_test&showAll

Is there an experiment flag we need to turn on at this point?

**Comment by leafpetersen** [comment]
I think that test is still failing in the front ends.

**Comment by eernstg** [comment]
I think the test `language/generic/generic_function_type_argument_test.dart` requires that

```
FB<F> <: F   // That is:
S Function<S extends X Function<X>(X)>(S) <: X Function<X>(X)   // Which is not true.
```

So the test and the analyzer need to be adjusted.

**Comment by crelier** [comment]
@stefantsov  I'm seeing an error reported by CFE on annotations:
```
$ out/DebugX64/dart --enable-experiment=generic-metadata tests/language/generic/generic_function_type_argument_test.dart
tests/language/generic/generic_function_type_argument_test.dart:48:2: Error: Type argument 'S Function<S extends T Function<T>(T)>(S)' doesn't conform to the bound 'T Function<T>(T)' of the type variable 'T' on 'CB'.
Try changing type arguments so that they conform to the bounds.
@CB<FB<F>>(fb)
 ^
tests/language/generic/generic_function_type_argument_test.dart:31:10: Context: This is the type variable whose bound isn't conformed to.
class CB<T extends F> {
         ^
```

**Comment by stefantsov** [comment]
> @stefantsov I'm seeing an error reported by CFE on annotations:
> 

I think that error reporting is correct, as @eernstg wrote above. The bound is `T Function<T>(T)`, and the type argument is `S Function<S extends T Function<T>(T)>(S)`. The type parameters in the two have different bounds, so they are incomparable: neither is a subtype of the other, and the error should be reported.

**Comment by leafpetersen** [comment]
The test needs adjustment.  I'll work on getting that done.

**Comment by crelier** [comment]
> I think that error reporting is correct, as @eernstg wrote above. 

Sorry, I totally missed Erik's post. My comment was sitting in a draft tab for too long.
Thanks all!

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/192261
