### ISSUE TITLE
Implement the Q1 2021 small features release in IntelliJ

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44918]
Implementation issue for [this set of features](https://github.com/dart-lang/sdk/issues/44911).

cc @devoncarew @jwren @franklinyow

**Comment by devoncarew** [comment]
@jwren - the feature spec is here: https://github.com/dart-lang/language/tree/master/accepted/future-releases/small-features-21Q1

**Comment by jwren** [comment]
Thanks Leaf, this was not forgotten.  When I sync with Alex at JetBrains next I'll make sure that he is iterating on this, otherwise I'll make sure it get into the Dart Plugin.

**Comment by jwren** [comment]
@leafpetersen @devoncarew 

> Allow type arguments on annotations (#1297).

Implemented with https://github.com/JetBrains/intellij-plugins/pull/794, not yet landed at this point.

> Allow generic function types as type arguments and bounds (#496).

There doesn't appear to be any changes required in the Dart Plugin PSI parser for this change.

> Allow `>>>` as an overridable operator (#120).

Implemented with https://github.com/JetBrains/intellij-plugins/pull/792, this change did land in the `master` branch last Friday.

Alexander is aware that we'll need these pushed into older versions of IDEA platform.

**Comment by jwren** [comment]
All PRs landed, closing issue.
