### ISSUE TITLE
Implement the Q1 2021 small features release in external syntax highlighting tools.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44919]
Implementation issue for syntax highlighting associated with [this set of features](https://github.com/dart-lang/sdk/issues/44911).

- [x] Issue for implementation in [Github syntax highlighting](https://github.com/dart-lang/dart-syntax-highlight/):
- [x] Issue for copying Github grammar for use with VS Code:
- [x] Issue for [highlight.js support](https://github.com/highlightjs/highlight.js) (api.dart.dev, api.pub.dev, Dartdoc):
- [x] Issue for [codemirror support](https://github.com/codemirror/CodeMirror/) (Cider, dartpad):

cc @devoncarew @franklinyow

**Comment by lrhn** [comment]
The Github syntax highlighting appears to be trivially satisfied:
```dart
@Annot<T Function<T>(T)>()
void main() {
  var c = Annot<T Function<T>(T)>();
  c >> 2;
  c >>> 3;
}
class Annot<T extends T Function<T>(T)> {
  const Annot();
  int operator >>>(int x) => x;
  int operator >>(int x) => x;
}
```
It's not complicated enough to recognize that type arguments belong to an annotation, or that they can't be generic function types, so those already worked like any other type argument.
There does not appear to be any highlighting of operators to begin with.

**Comment by devoncarew** [comment]
I believe we're good from the POV of codemirror as well; this is from dartpad:

<img width="493" alt="Screen Shot 2021-02-09 at 1 06 48 PM" src="https://user-images.githubusercontent.com/1269969/107428595-bc9f4700-6ad7-11eb-9321-05f774af799e.png">

**Comment by devoncarew** [comment]
@srawlins - do you mind confirming that highlight.js is good as is (doesn't need any changes)?

**Comment by srawlins** [comment]
Agree.
