### ISSUE TITLE
Implement Q1 2020 Small features release in the core libraries

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44912]
This tracks the implementation work in the core libraries for [this feature](https://github.com/dart-lang/sdk/issues/44911).

cc @lrhn @franklinyow

**Comment by alexmarkov** [comment]
Optimized implementation of `>>>` in the VM (https://github.com/dart-lang/sdk/issues/30892) is blocked on changes in core libraries (we need to add `operator >>>` to `int` class first).

**Comment by leafpetersen** [comment]
@lrhn @alexmarkov where are we with this?

**Comment by alexmarkov** [comment]
VM fully implements `int.operator >>>` (7f8001218bc2ca326b6acc62d190e726cfb98a25).

**Comment by franklinyow** [comment]
Any other work still needed?

**Comment by leafpetersen** [comment]
I think we can close this.
