### ISSUE TITLE
Language tests for the Q1 2021 small features release.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44926]
This tracks writing language tests for [this feature set](https://github.com/dart-lang/sdk/issues/44911).

cc @lrhn @eernstg @franklinyow

**Comment by leafpetersen** [comment]
Making a note that we may need additional test coverage for any spec updates based on [this issue](https://github.com/dart-lang/language/issues/1476).

**Comment by leafpetersen** [comment]
cc @srawlins @stefantsov @johnniwinther @scheglov @devoncarew for visibility on anything landed here.

**Comment by eernstg** [comment]
Note that @lrhn did much of this work already:

Landed: https://dart-review.googlesource.com/c/sdk/+/180844 adds tests for https://github.com/dart-lang/language/issues/496, https://dart-review.googlesource.com/c/sdk/+/180843 adds tests for https://github.com/dart-lang/language/issues/120.

Under review: https://dart-review.googlesource.com/c/sdk/+/185583 adds tests for https://github.com/dart-lang/language/issues/1297.

**Comment by leafpetersen** [comment]
I think we seriously need some more test coverage here.  There are no static error tests at all that I see in the language directory for this.  c.f. https://github.com/dart-lang/sdk/issues/45394 for an issue found accidentally.

**Comment by leafpetersen** [comment]
It would also be good to get more runtime type test coverage for this, e.g. tests that  casts to generic type parameters work correctly (both pass when appropriate, and throw when appropriate) when the parameter is instantiated with a generic function.
