### ISSUE TITLE
Implement the Q1 2021 small features release in the VM service

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44924]
This tracks any work required to support [this feature](https://github.com/dart-lang/sdk/issues/44911) in the VM service.

cc @a-siva @jacob314 @franklinyow who should own this?

**Comment by leafpetersen** [comment]
@bkonyi any updates?

**Comment by bkonyi** [comment]
No updates. Not sure I see anything there that would require new support in the service protocol.

**Comment by franklinyow** [comment]
Should we closed this then?

**Comment by a-siva** [comment]
@bkonyi tested that this feature works in expression evaluation inside the debugger so yes we can close this item, it any issues are uncovered we can create specific issues for each failure.
