### ISSUE TITLE
Implement the Q1 2021 small features release in AngularDart

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44923]
This tracks any implementation work in the angular compiler to support [this feature set](https://github.com/dart-lang/sdk/issues/44911).

cc @matanlurey @franklinyow

**Comment by matanlurey** [comment]
Thanks for the heads up Leaf. I filed internal issue b/180125796.

I am going to close this external issue as I don't see anything else worth tracking in the OSS space.

**Comment by leafpetersen** [comment]
@matanlurey I'm going to leave this open as a marker for us to validate that the internal work has been completed prior to release.  Thanks!
