### ISSUE TITLE
Update documentation for the Q1 2021 small features release.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44927]
This tracks any documentation updates required for [this feature set](https://github.com/dart-lang/sdk/issues/44911).

cc @kwalrath @franklinyow

**Comment by leafpetersen** [comment]
@kwalrath any updates?

**Comment by leafpetersen** [comment]
@kwalrath Any concerns about this being ready for stable?

**Comment by kwalrath** [comment]
> @kwalrath Any concerns about this being ready for stable?

No, no concerns.

**Comment by franklinyow** [comment]
Any update on this?

**Comment by franklinyow** [comment]
Synced with @kwalrath, moving to a later milestone

**Comment by mit-mit** [comment]
fyi @kwalrath these features are on track for next stable

**Comment by vsmenon** [comment]
Moving this to the August milestone - is this still open?

**Comment by kwalrath** [comment]
We'll publish the `>>>` docs when 2.14 goes stable

**Comment by MrBirb** [comment]
@kwalrath I believe this was done [here](https://github.com/dart-lang/site-www/pull/3541) ?

**Comment by kwalrath** [comment]
> @kwalrath I believe this was done [here](https://github.com/dart-lang/site-www/pull/3541) ?

Correct!
