### ISSUE TITLE
Implement the Q1 2021 small features release in internal tools.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44920]
This tracks internal tooling support [for this set of features](https://github.com/dart-lang/sdk/issues/44911).  

cc @devoncarew @keertip @davidmorgan @franklinyow

**Comment by devoncarew** [comment]
@davidmorgan - I'm assigning to you (but there may be someone better / more specific).

**Comment by leafpetersen** [comment]
@keertip any updates?

**Comment by devoncarew** [comment]
My expectation is that there will be no impact here for Cider. We might want to confirm that there will / won't be any impact for Kythe; cc @davidmorgan @srawlins.

**Comment by keertip** [comment]
Right, as Devon mentions, as long as the analyzer has the support it should automatically roll into Cider.

**Comment by devoncarew** [comment]
I'm going to un-assign Keerti w/ there being no assumed work for Cider. @davidmorgan, we probably still need to investigate this for Kythe.

In the future we might want to have separate issues for Cider and Kythe - they have different owners and will likely need different types of changes depending in the specific language feature.

**Comment by leafpetersen** [comment]
@davidmorgan do we have an internal bug for this?
