### ISSUE TITLE
Implement the Q1 2021 small features release in the web debuggers

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44925]
This tracks implementation work for [this feature set](https://github.com/dart-lang/sdk/issues/44911).

cc @sigmundch @annagrin @franklinyow

**Comment by leafpetersen** [comment]
@sigmundch any work planned here?

**Comment by sigmundch** [comment]
I don't believe there is any work needed here. Just to be sure @grouma @jacob314 - can you confirm?

**Comment by grouma** [comment]
There shouldn't be any work on our end.

**Comment by sigmundch** [comment]
Thanks!
