### ISSUE TITLE
[CP][beta channel] fix a hint and two refactoring tests in analysis server

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#44945]
**commit(s) to merge**: https://dart-review.googlesource.com/c/sdk/+/183960

**merge instructions**: clean merge

**What is the issue**: 

- https://github.com/dart-lang/sdk/issues/44809 was incomplete and had one hint, and 2 DAS refactoring tests failing.

**What is the fix**: fix the hint and include two small changes to indexing and search that fix the 2 failing tests.

**Why cherrypick**:

- this will fix the previous CP, and rename refactoring for required named parameters in null safe code

**Risk**:

- low; it's a small delta to the implementation, most changes are to tests

**Link to original  issue(s)**:

https://github.com/dart-lang/sdk/issues/44805

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @devoncarew

**Comment by athomas** [comment]
Merged to beta in cc15e7439ae2c596b2ca0c5c032e294a20843e30 (2.12.0-259.12.beta).
