### ISSUE TITLE
[vm] BitmapBuilder backing store growth

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#44946]
ffi_2/function_structs_by_value_generated_test/0 is crashing on app_jitk-linux-debug-x64.

Log: https://dart-ci.appspot.com/log/app-kernel-linux-debug-x64/app_jitk-linux-debug-x64/7942/ffi_2/function_structs_by_value_generated_test/0

The failure doesn't look related to the reported culprit CLs: https://dart-ci.firebaseapp.com/#showLatestFailures=true&configurations=app_jitk-linux-debug-x64

**Comment by dcharkes** [comment]
This might not be `dart:ffi` related. The function being compiled is `Function 'visitFunctionType':.`. It just happens to be a `dart:ffi` test that catches this.

`--deterministic` makes this error go away, so it only occurs on the background compiler.
