### ISSUE TITLE
Implement non-function type alias support in syntax highlighters

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44956]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

  - [x] [Github syntax highlighting](https://github.com/dart-lang/dart-syntax-highlight/).
    - [x] Github grammar for use with VS Code.
  - [x] [highlight.js support](https://github.com/highlightjs/highlight.js) (api.dart.dev, api.pub.dev, Dartdoc):
  - [x] [CodeMirror support](https://github.com/codemirror/CodeMirror/) (DartPad).

cc @devoncarew @srawlins @mit-mit @keertip @franklinyow

**Comment by srawlins** [comment]
Looks fine in CodeMirror

**Comment by srawlins** [comment]
Also looks fine in highlight.js

**Comment by devoncarew** [comment]
VS Code / the textmate grammar looks good as well.
