### ISSUE TITLE
Implement non-function type alias support in Kythe

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44957]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @davidmorgan @mit-mit @franklinyow

**Comment by davidmorgan** [comment]
Thanks; b/179969218

**Comment by leafpetersen** [comment]
This is tracked internally and my understanding is that we will not block on this - indexing will land after we turn this on internally.
