### ISSUE TITLE
Implement non-function type alias support in Cider

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44958]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @keertip @devoncarew @mit-mit @franklinyow

**Comment by leafpetersen** [comment]
@keertip any updates on this?

**Comment by franklinyow** [comment]
@keertip any updates?  Thx

**Comment by keertip** [comment]
As long as the analyzer has support for this, Cider will have support. It takes about a week after the analyzer support rolls into g3 to get it into Cider.
