### ISSUE TITLE
Implement non-function type alias support in Intellij

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44955]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @devoncarew @jwren @mit-mit @franklinyow 

@bwilkerson do you want a separate issue to track any other tooling support that you expect to want to do?

**Comment by jwren** [comment]
This was completed by JetBrains with:

https://github.com/JetBrains/intellij-plugins/commit/1884755e304919d249e02c5eca503a222cc19371

https://youtrack.jetbrains.com/issue/WEB-49464
