### ISSUE TITLE
Analytics flags do not work correctly in dev branches

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44968]
In current stable, the `--enable-analytics` and `--disable-analytics` flags print output like this:

```
$ ./stable/dart-sdk/bin/dart --disable-analytics
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ Anonymous analytics disabled. To enable again, run the command:            ║
  ║ `dart --enable-analytics`                                                  ║
  ╚════════════════════════════════════════════════════════════════════════════╝
```

In the current dev & beta channels, it just prints help:

```
$ ./dart --disable-analytics
A command-line utility for Dart development.

Usage: dart [<vm-flags>] <command|dart-file> [<arguments>]
```

Thanks to @iamchathu for reporting via https://github.com/dart-lang/site-www/pull/2765#issuecomment-777253087

**Comment by mit-mit** [comment]
cc @bkonyi @a-siva @devoncarew

**Comment by iamchathu** [comment]
I got this issue to I'm using flutter SDK on beta channel

**Comment by bkonyi** [comment]
Looks like this was broken in https://github.com/dart-lang/sdk/commit/f3fe9dc3b3392a5e5442535c9fe265fbfc977d15#diff-d2c73d2163def9f30c2610b1c47804f258a27bb96abc731ce4eeadfe778333f6L516.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/184502 from @bkonyi
