### ISSUE TITLE
Implement non-function type alias support in AngularDart

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44961]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

@matanlurey Just a tracking issue for us to validate any work needed in the angular compiler to support this feature.

cc @matanlurey @franklinyow

**Comment by franklinyow** [comment]
@matanlurey Is there work we need here?

**Comment by matanlurey** [comment]
We don't track internal issues on GitHub, sorry.

**Comment by matanlurey** [comment]
Un-assigning as I'm going OOO for quite some time and I don't think there is anything actionable here for us.
