### ISSUE TITLE
Implement non-function type alias support in VM Service

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44962]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @franklinyow @a-siva @bkonyi

**Comment by leafpetersen** [comment]
@a-siva anything we're tracking here or should I close this out?

**Comment by a-siva** [comment]
There is no work in VM so closing this, we will track individual test failures by creating new issues for each failure.
