### ISSUE TITLE
Implement non-function type alias support in language/co19 tests

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44964]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @franklinyow @eernstg @mit-mit

**Comment by eernstg** [comment]
The CFE implementation was considered complete as of https://dart-review.googlesource.com/175642.

**Comment by eernstg** [comment]
@sgrekhov, @iarkh, what is the current status?

**Comment by sgrekhov** [comment]
@eernstg we have non-function type aliases tests in co19. We simply need to enable these tests in .status files. Do you want me to do it now?

**Comment by eernstg** [comment]
@sgrekhov, yes please!

**Comment by sgrekhov** [comment]
https://dart-review.googlesource.com/c/sdk/+/185082

**Comment by eernstg** [comment]
I'll make sure that we have language tests for cyclicity.

**Comment by eernstg** [comment]
Type alias cyclicity tests landed as https://dart-review.googlesource.com/186290.
