### ISSUE TITLE
Add any desired non-function type alias uses to core libraries.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44967]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

@lrhn anything we want to do here?

cc @franklinyow @lrhn @natebosch @mit-mit

**Comment by lrhn** [comment]
I'd love `typedef any = Object?;` in `dart:core`. Should probably be `Any` to avoid conflicts, though. 

We could defined `typedef JsonMap = Map<String, Object?>;`, maybe also `typedef JsonList = List<Object?>;`.

Other than that, I'm not sure there's anything which belongs in the platform libraries.

(Other people have requested capitalized `Int` and `Bool`, others have requested lower-case `string`. Not something I think we should do in the platform libraries).

**Comment by lrhn** [comment]
Does anybody else have an idea for a typedef that would belong in the core platform libraries (`core`, `async`, `convert`, `collection`, `math` or `typed_data`)?

I'll collect ideas here (no promises to actually add them):

- [ ] `typedef Any = Object?;` in `dart:core`.
- [ ] `typedef JsonMap = Map<String, Object?>; typedef JsonList = List<Object?>;` in `dart:convert`.
- [ ] `typedef Int = int; typedef Double = double; typedef Num = num; typedef Bool = bool;` in `dart:core` (for cosistency).
- [ ] `typedef string = String;` in `dart:core` (for a different kind of consistency).

**Comment by franklinyow** [comment]
Do we know how much work we're doing here?

**Comment by leafpetersen** [comment]
I think nothing is planned here.

**Comment by mit-mit** [comment]
@leafpetersen not even `typedef JsonMap = Map<String, Object?>; typedef JsonList = List<Object?>;` in `dart:convert` ?

That one seemed obvious. But I could be missing something?

**Comment by lrhn** [comment]
I personally don't care about `JsonX` types. I'd like the `Any` type, but that's the only one I'd use myself.
There has been absolutely no visible interest about any of these types, so I'm fine with doing nothing.

**Comment by natebosch** [comment]
@mit-mit - I don't think we're likely to get any clear consensus on these to the point where we'd take action. Should we close again?
