### ISSUE TITLE
Update documentation to cover non-function type aliases

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44965]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

@kwalrath @davidmorgan do you want separate issues for internal/external docs?  Who else should I loop in here?

cc @franklinyow @mit-mit

**Comment by davidmorgan** [comment]
We don't have any internal documentation about general language features--except for null safety. So I think there's nothing to do for internal documentation.Thanks.

**Comment by mit-mit** [comment]
For external docs, I think we need to update https://dart.dev/guides/language/language-tour#typedefs

**Comment by eernstg** [comment]
@kwalrath, perhaps we should communicate a bit about this?

The text in https://dart.dev/guides/language/language-tour#typedefs needs a few updates, and then an extension:

At first, we should be a bit more general now that a type alias can define an alias for any type, not just a function type. Maybe we could do something like the following:

> A typedef, or function-type alias, gives a function type a name that you
> can use when declaring fields and return types. A typedef retains type
> information when a function type is assigned to a variable.

--> 

> A type alias, which is declared by a declaration starting with the keyword `typedef`, gives
> a type a name that you can use as a type, e.g., when declaring fields and return types.
> A type alias can have type parameters. A type alias can be convenient because it is more
> concise than the type that it denotes. Also, a type alias with type parameters can remove
> even more verbosity, and ensure consistency, if it uses the same type parameter more
> than once.

> ```dart
> typedef ListMapper<X> = Map<X, List<X>>;
> Map<StatelessWidget, List<StatelessWidget>> m1; // Verbose.
> ListMapper<StatelessWidget> m2; // Same thing, less verbose, less redundant.
> ```

We may be able to reuse the old example using `Function`, but it's not very relevant (the description assumes that there is no other way to write the precise function type, but we can do that inline today: `int Function(Object, Object)`).

**Comment by mit-mit** [comment]
I'd love to use a simple example, like:

```dart
typedef IntList = List<int>;
IntList il = [1,2,3];
```

**Comment by leafpetersen** [comment]
@kwalrath any updates?

**Comment by kwalrath** [comment]
This won't be in a stable release for a while, correct? We often don't cover features until they're in a stable release (with the exception of features where we want feedback or that need a lot of work to implement).

**Comment by franklinyow** [comment]
@kwalrath This is targeting the next dart stable release

**Comment by leafpetersen** [comment]
@kwalrath @mit-mit we should add the 2.13 features to [this](https://dart.dev/guides/language/evolution) as well.

**Comment by leafpetersen** [comment]
@kwalrath Any concerns about this being ready for when we hit stable?

**Comment by kwalrath** [comment]
> @kwalrath Any concerns about this being ready for when we hit stable?

Nope

**Comment by franklinyow** [comment]
Moving this to April

**Comment by franklinyow** [comment]
@kwalrath Any update on this doc?

**Comment by kwalrath** [comment]
We expect to have the docs for stable, not beta.

**Comment by franklinyow** [comment]
@kwalrath I'm moving this to June

**Comment by kwalrath** [comment]
> I'd love to start with a simple example, like:
> 
> ```dart
> typedef IntList = List<int>;
> IntList il = [1,2,3];
> ```

@mit-mit we'd talked about maybe using JsonMap instead. Did you find that example?

**Comment by franklinyow** [comment]
Link to site-www
https://github.com/dart-lang/site-www/issues/2937

**Comment by franklinyow** [comment]
closing as dart-lang/site-www#2937 is closed
