### ISSUE TITLE
Validate that all tests are passing for non-function type aliases prior to release.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44966]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @franklinyow @eernstg @mit-mit

**Comment by eernstg** [comment]
As of Feb 11 2021, https://dart-review.googlesource.com/c/sdk/+/184460 migrates all non-function type alias legacy tests to mixed-version tests where the non-function type aliases are declared in an opted-in library and the remaining code is in an opted-out library.

They are all passing, except `language/nonfunction_type_aliases/mixed/aliased_cyclic_superclass_error_test.dart`, whose failure seems to be a bug in test.py, cf. https://github.com/dart-lang/sdk/issues/44990.

**Comment by eernstg** [comment]
@leafpetersen, do you expect this check to be repeated up to the release event, or is it a one-shot validation? If it is the latter then I believe that we can close this.

**Comment by leafpetersen** [comment]
I'd like to leave this open until we're sure that we've landed all of the tests that we're going to land.  I'm assuming we will need (at least) tests for the new cyclic typedef resolution rules?

**Comment by leafpetersen** [comment]
Also, this is intended to cover co19 tests as well, are those all passing?

**Comment by leafpetersen** [comment]
Looking good here, zero failing tests except the known bad co19 tests waiting a roll.
