### ISSUE TITLE
Implement non-function type alias support in Dartdoc

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44960]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @franklinyow @mit-mit @jcollins-g @devoncarew

**Comment by leafpetersen** [comment]
@jcollins-g any updates here?

**Comment by jcollins-g** [comment]
https://github.com/dart-lang/dartdoc/pull/2558 implemented most of this.  There are some analyzer changes landed today that will make the rest of the planned support possible.  Once that's published I can land the remaining changes.

**Comment by franklinyow** [comment]
Any updates?

**Comment by jcollins-g** [comment]
i am working on getting this published through the ecosystem as I write this.

**Comment by jcollins-g** [comment]
This is now published and propagated through Dart and Flutter.
