### ISSUE TITLE
Implement non-function type alias support in web debuggers

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44963]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @franklinyow @sigmundch @mit-mit

**Comment by sigmundch** [comment]
I don't believe there is any specific work required for this, other than validating that the feature works as expected.

@jacob314 @grouma - do you agree?

**Comment by grouma** [comment]
Yeah I think we just need to validate that it works and if it doesn't, likely make edits to the logic [here](https://github.com/dart-lang/webdev/blob/83f661c80b902e8bd7186e9739a7bcb9c22bef8e/dwds/lib/src/debugging/instance.dart#L321).

**Comment by leafpetersen** [comment]
@grouma do we have a plan for validating this?

**Comment by grouma** [comment]
I think making use of the feature in a `package:dwds` smoke test, along with some specific VM Service protocols, should give us enough confidence.

**Comment by sigmundch** [comment]
Maybe it is worth also adding a couple tests to cover https://github.com/dart-lang/sdk/issues/44925 as well?

**Comment by grouma** [comment]
Wouldn't hurt. We'll need to know the SDK version that contains these features.

**Comment by leafpetersen** [comment]
@grouma this will be released in 2.13 are you waiting on a dev build or can you go ahead and validate?  [This](https://dart-review.googlesource.com/c/sdk/+/192948) CL can be patched in to build a version with the feature on by default.

**Comment by grouma** [comment]
Ping me when a dev build is available. It's much easier to validate that way.

**Comment by franklinyow** [comment]
It seems we won't have a dev build this week due to Easter holiday in Europe , can we validate with the CL?

**Comment by leafpetersen** [comment]
@grouma this has landed, can you please test on master (I don't expect we will have a dev build before the branch cut window opens).

**Comment by grouma** [comment]
I downloaded the latest SDK:
`Dart SDK version: 2.13.0-203.0.dev (dev) (Mon Apr 5 09:39:33 2021 -0700) on "macos_x64"`

I updated the minimum SDK for my example project and included this:
```Dart
typedef JsonMap = Map<String, dynamic>;
```
There are no errors with analysis, however  I'm having issues building: 

```
[SEVERE] build_web_compilers:entrypoint on web/main.dart: This builder requires Dart inputs without syntax errors.
However, asset:webdev_example_app/web/main.dart (or an existing part) contains the following errors.
main.dart:11:17: Invalid generic function type.

Try fixing the errors and re-running the build.


[INFO] Running build completed, took 3.7s
[INFO] Caching finalized dependency graph completed, took 180ms
[SEVERE] Failed after 3.9s
[INFO] ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

cc @jakemac53 

Without being able to build it's impossible for me to validate.

**Comment by leafpetersen** [comment]
@grouma This is not in any dev build and I don't think it will be until AAR is back from vacation which will be too late.  I think you need to test this out on **master**.

**Comment by grouma** [comment]
I'll build from master locally but I'm confused as to why this isn't in the latest `raw` SDK. I thought raw corresponded to master. The given timestamp says it was built this morning. Correct my understanding.

**Comment by leafpetersen** [comment]
@grouma is this a pkg:analyzer issue then?  You may need a version of pkg:analyzer with this enabled - cc @scheglov .

**Comment by grouma** [comment]
I don't think this is an analyzer issue. There are no analysis errors. (There were some until I upgraded the SDK and updated the pubspec). I think this may be a `package:build` issue. cc @natebosch

**Comment by scheglov** [comment]
FYI, I'm waiting for the flag switch to be rolled into google3, and will publish `package:analyzer` then.

**Comment by natebosch** [comment]
@grouma `webdev serve` works for me.

I had to ensure that the language version is `2.13`, and use a `dependency_override` on `analyzer` from my local SDK checkout since it isn't published yet. It also took a few other overrides to get a valid solve. Here is the pubspec I used in a project where this worked:

```yaml
name: dart_repro

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dev_dependencies:
  build_runner: any
  build_web_compilers: any

dependency_overrides:
  analyzer:
    path: ../dart-sdk/sdk/pkg/analyzer
  front_end:
    path: ../dart-sdk/sdk/pkg/front_end
  _fe_analyzer_shared:
    path: ../dart-sdk/sdk/pkg/_fe_analyzer_shared
  package_config: 2.0.0
```

**Comment by grouma** [comment]
Thanks @natebosch, I was able to get it working.

Debugging doesn't blow up so that's good. I'm not sure what the intended behavior is here though. The displayed types are desugared. Look at the variables and console in the screenshot below. I suppose that's the desired behavior?

<img width="1291" alt="Screen Shot 2021-04-05 at 4 31 52 PM" src="https://user-images.githubusercontent.com/1840773/113638826-9e178100-962c-11eb-8017-5126e8f6a625.png">

**Comment by leafpetersen** [comment]
Expanding the types seems like fine behavior to me.
