### ISSUE TITLE
Potential memory leak in `VirtualMemory::AllocateAligned`

### ISSUE THREAD

**Issue by iskakaushik** [dart-lang/sdk#44974]
When running a Flutter app with memory stack logging enabled on an iOS device. I ran into the following leak:

![image](https://user-images.githubusercontent.com/1006071/107667225-3b18f780-6c44-11eb-89b1-0c3336243d2b.png)

Unclear if this was expected or not as given the class name, looks like a lot of allocations go through it. As I navigated through the app over a few minutes, steady state usage kept going up. I did notice the memory go down a little periodically presumably due to GC, but overall the memory kept going up. Here is the stack trace:

![image](https://user-images.githubusercontent.com/1006071/107667146-25a3cd80-6c44-11eb-9353-43a948143bd8.png)

- Dart version: ebcb7aee8c0ddf26addb8e7c472a6866eb60b16b
- iOS version: 14.2
- Host: macOS

Repro instructions:

1. Clone the flutter repository.
2. Open flutter gallery: `cd dev/integration_tests/flutter_gallery`.
3. Do a `flutter run -d $IOS_DEVICE`
4. Open x-code, edit scheme, enable `MallocStackLogging`, see: https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/MallocDebug.html.
5. Navigate to `Media > Video` in the app, let the video run for a minute.
6. Collect memory graph.

**Comment by zanderso** [comment]
Looks like it might be the expected allocations from JIT compilation, which could look like leaks because they live a long time in old gen. @a-siva @alexmarkov

**Comment by iskakaushik** [comment]
I ran the app for some more time and noticed the allocations climbing without getting collected. I am suspecting it's the same code being compiled, but could be wrong. Given that i'm cycling between views of the same app and not opening new content.

**Comment by a-siva** [comment]
Is it possible to get a timeline trace of your run after the initial warm up to see if there is still compilation happening.

**Comment by a-siva** [comment]
any more updates on this ?

**Comment by a-siva** [comment]
@iskakaushik do you have a chance to foillow up on this to confirm if there was a leak or just a case of methods being compiled causing the footprint to go up ?

**Comment by chinmaygarde** [comment]
These seems like WAI as I was able to spot reductions after some time. Closing as WAI as this seemed to be a bit of an open-ended exploration.
