### ISSUE TITLE
[vm/ffi] Struct subtype can be created by generative constructor

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#44987]
According to the `Struct` [documentation](https://api.dart.dev/dev/2.13.0-21.0.dev/dart-ffi/Struct-class.html) 

> Instances of a subclass of Struct have reference semantics and are backed by native memory. The may allocated via allocation or loaded from a Pointer, but cannot be created by a generative constructor.

But they can. The following code produces no error
```dart
class S1 extends Struct {
  S1() : super();

  @Int32()
  external int a;

  @Float()
  external double b;

  external Pointer<Void> c;
}

void main() {
  S1 s1 = new S1();
  Expect.equals(nullptr.address, StructAddressOf(s1).addressOf.address);
}
```
There must be an error, according to the documentation. If this behaviour is Ok, then, please, change the documentation

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/205740
