### ISSUE TITLE
pkg/dartdev/test/analytics_test fails on Windows

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#44981]
There are new test failures on [Use extensions in FfiVerifier....[ DartDev / CLI ] Fixed issue where analytics flags were not being forwarded to the CLI](https://github.com/dart-lang/sdk/compare/7ce8e3ba2e224f36441e0f0c833a5eb7a1111e0b~...6944a2c1ec9c2c6018e21c27ed868ff1ad6cfb1a).

The test
```
pkg/dartdev/test/analytics_test RuntimeError (expected Pass)
```
is failing on configuration
```
unittest-asserts-release-win
```

Log: https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/15011/pkg/dartdev/test/analytics_test

This failure looks related to 7ce8e3ba2e224f36441e0f0c833a5eb7a1111e0b

@bkonyi Could you please take a look?

**Comment by athomas** [comment]
@bkonyi: @whesse is working on a fix for this test bug.

**Comment by bkonyi** [comment]
Thanks @whesse and @athomas!
