### ISSUE TITLE
The CHANGELOG.md doesn't mention sdk: '>2.10.0, <=2.12.0' with respect to null safety

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#44984]
I can guess what happens with `sdk: 2.10.5`, but the CHANGELOG.md doesn't mention it, anyway.

**Comment by mit-mit** [comment]
Hi @Cat-sushi can you elaborate on what the question is that you feel should be covered?

**Comment by Cat-sushi** [comment]
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md
>You can opt out of null safety and preserve your code's previous behavior by setting the lower bound of the SDK constraint in your pubspec to 2.11.0 or earlier to request an earlier language version. You can opt out individual Dart files by adding // @dart=2.11 to the beginning of the file.

Former versions of the CHANGELOG.md used 2.9.0 but not 2.11.0 as an example, so I couldn't be sure what happened with SDK constraints of 2.10.0 or 2.11.0.
Now, I think current version of CHANGELOG.md with the snippet above is good enough.

**Comment by mit-mit** [comment]
Language versions are incremental, so you can always use a smaller language version in the lower bound.
