### ISSUE TITLE
[CP] {Beta] Fixed issue where analytics flags were not being forwarded to the CLI

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44982]
Please cherry pick 7ce8e3ba2e224f36441e0f0c833a5eb7a1111e0b into the beta branch

Reason : analytics flags was not working correctly, please see https://github.com/dart-lang/sdk/issues/44968

Impact: The change will fix the issue and has minimal impact on other functionality.

The change merges cleanly into the beta branch and builds fine.

Risk: Low, has been merged into master

Link to original issue https://github.com/dart-lang/sdk/issues/44968

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @bkonyi

**Comment by bkonyi** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/44980.
