### ISSUE TITLE
[CP][beta channel] Fix Dart CLI analytics control flags not working

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#44980]
**commit(s) to merge**: 7ce8e3ba2e224f36441e0f0c833a5eb7a1111e0b

**merge instructions**: Clean merge

**What is the issue**: `--disable-analytics` and `--enable-analytics` were not being forwarded to the Dart CLI isolate, resulting in analytics always being enabled regardless of user preference.

**What is the fix**: Added code to VM options parser to forward these flags to the Dart CLI isolate.

**Why cherrypick**: Without this fix users have no way to disable Dart CLI analytics.

**Risk**: Low

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/44968

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by mit-mit** [comment]
SGTM, we have to take this

**Comment by a-siva** [comment]
lgtm

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Marked approved. Thanks!

**Comment by athomas** [comment]
Merged to beta in cc15e7439ae2c596b2ca0c5c032e294a20843e30 (2.12.0-259.12.beta).
