### ISSUE TITLE
[CP][beta channel] Fix null-safety type bug in HTTP code

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44989]
**commit(s) to merge**: 9cbed612045f455f5fd315392e3fe2e3be9c130d

**merge instructions**: clean merge

**What is the issue**: Fix null-safety type bug in HTTP code. Triggers if passing a timeout.

**What is the fix**: Refactor the code to avoid using `null` as a signal that a timeout happened. Catch `TimeoutException` instead.

**Why cherrypick**: It's a bug that prevents all use of the `timeout` parameter. It was introduced in null safety migration.

**Risk**: Very little to none. The fix should not change the behavior of any existing code, except where it would otherwise hit the bug.

**Link to original issue(s)**: http://dartbug.com/44895

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by vsmenon** [comment]
lgtm
