### ISSUE TITLE
safepoint lockers are unsafe when used in functions returning raw pointers

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#44998]
Consider the code like this: 

```dart
FunctionPtr ClosureFunctionsCache::LookupClosureFunction(
    const Class& owner,
    TokenPosition token_pos) {
  auto thread = Thread::Current();
  SafepointReadRwLocker ml(thread, thread->isolate_group()->program_lock());
  return LookupClosureFunctionLocked(owner, token_pos);
}
```

This code might look safe, but in reality it is not because `~SafepointReadRwLocker` might enter a safepoint: `LeaveRead` grabs monitor and grabbing the contended monitor triggers safepoint on the slow path. However at entering safepoint in `~SafepointReadRwLocker` is not safe because there is a raw pointer on the stack. It can very well be that another thread is preparing for GC and thus we can hit GC with raw value on the stack - which might cause issues. 

We are currently observing some really obscure crashes internally on `flutter_tester` which I think are caused by this issue (see b/176441206 for repro steps). I have made some changes to the lockers to catch when GC happens in destructor and have confirmed that we are indeed hitting this case:

<details>
<summary>patch to catch GC in `~SafepointReadRwLocker`</summary>

```diff
diff --git a/runtime/vm/lockers.cc b/runtime/vm/lockers.cc
index cb040061e32..fc1ad4eb0a1 100644
--- a/runtime/vm/lockers.cc
+++ b/runtime/vm/lockers.cc
@@ -6,9 +6,16 @@
 #include "platform/assert.h"
 #include "vm/heap/safepoint.h"
 #include "vm/isolate.h"
+#include "vm/heap/heap.h"
 
 namespace dart {
 
+intptr_t SafepointReadRwLocker::CurrentEpoch() {
+  if (!abort_on_gc_) return 0;
+  auto heap = static_cast<Thread*>(thread())->heap();
+  return heap->Collections(Heap::kNew) + heap->Collections(Heap::kOld);
+}
+
 Monitor::WaitResult MonitorLocker::WaitWithSafepointCheck(Thread* thread,
                                                           int64_t millis) {
   ASSERT(thread == Thread::Current());
diff --git a/runtime/vm/lockers.h b/runtime/vm/lockers.h
index d5b25760b20..bd9a2ce18e2 100644
--- a/runtime/vm/lockers.h
+++ b/runtime/vm/lockers.h
@@ -454,8 +454,8 @@ class ReadRwLocker : public StackResource {
  */
 class SafepointReadRwLocker : public StackResource {
  public:
-  SafepointReadRwLocker(ThreadState* thread_state, SafepointRwLock* rw_lock)
-      : StackResource(thread_state), rw_lock_(rw_lock) {
+  SafepointReadRwLocker(ThreadState* thread_state, SafepointRwLock* rw_lock, bool abort_on_gc = false)
+      : StackResource(thread_state), abort_on_gc_(abort_on_gc), rw_lock_(rw_lock) {
     ASSERT(rw_lock_ != nullptr);
     if (!rw_lock_->EnterRead()) {
       // if lock didn't have to be acquired, it doesn't have to be released.
@@ -464,11 +464,16 @@ class SafepointReadRwLocker : public StackResource {
   }
   ~SafepointReadRwLocker() {
     if (rw_lock_ != nullptr) {
+      const intptr_t epoch = CurrentEpoch();
       rw_lock_->LeaveRead();
+      RELEASE_ASSERT(epoch == CurrentEpoch());
     }
   }
 
+  intptr_t CurrentEpoch();
+
  private:
+  bool abort_on_gc_ = false;
   SafepointRwLock* rw_lock_;
 };
 
diff --git a/runtime/vm/object.cc b/runtime/vm/object.cc
index 7ad31370594..c9dc15dfbb0 100644
--- a/runtime/vm/object.cc
+++ b/runtime/vm/object.cc
@@ -5412,7 +5412,7 @@ FunctionPtr Class::LookupFunctionAllowPrivate(const String& name,
   ASSERT(!IsNull());
   Thread* thread = Thread::Current();
   RELEASE_ASSERT(is_finalized());
-  SafepointReadRwLocker ml(thread, thread->isolate_group()->program_lock());
+  SafepointReadRwLocker ml(thread, thread->isolate_group()->program_lock(), /*abort_on_gc=*/true);
   REUSABLE_ARRAY_HANDLESCOPE(thread);
   REUSABLE_FUNCTION_HANDLESCOPE(thread);
   REUSABLE_STRING_HANDLESCOPE(thread);
```

</details>

I think the best way to fix this code is to move away from scoped objects to a lambda based API which would handlify results across safepoints if necessary e.g.

```cpp
FunctionPtr ClosureFunctionsCache::LookupClosureFunction(
    const Class& owner,
    TokenPosition token_pos) {
  auto thread = Thread::Current();
  return WithSafepointReadRwLock(thread, thread->isolate_group()->program_lock(), [&]() {
    return LookupClosureFunctionLocked(owner, token_pos);
  });
}
```

<details>
<summary>Potential implementation of `WithSafepointReadRwLock`</summary>

```cpp
#include <type_traits>
#include <utility>

template<typename T, typename U = void>
struct HandleIfPtr {
    template<typename F>
    void wrapResultOf(F&& action) { value = std::move(action()); }
    T&& unwrap() { return std::move(value); }
    T value;
};

template<>
struct HandleIfPtr<void> {
    template<typename F>
    void wrapResultOf(F&& action) { action(); }
    void unwrap() { }
};

template<typename T>
struct HandleIfPtr<T, typename std::enable_if<std::is_base_of<ObjectPtr, T>::value>::type> {
    template<typename F>
    void wrapResultOf(F&& action) { handle = action(); }
    T unwrap() { return static_cast<T>(handle.ptr()); }

    Object& handle = Object::Handle();
};

template<typename F>
typename std::result_of<F()>::type WithSafepointReadRwLock(Thread* thread, Monitor* monitor, F&& action) {
  HandleIfPtr<typename std::result_of<F()>::type> handle;
  {
    // Note: we should probably make SafepointReadRwLocker constructor private 
    // to ensure that it is only ever used through WithSafepointReadRwLock
    SafepointReadRwLocker locker(thread, monitor);
    handle.wrapResultOf(action);
  }
  return handle.unwrap();
}
```

</details>

@aam @mkustermann could one of you take over this refactoring if you have cycles? 

/cc @rmacnak-google

**Comment by mraleph** [comment]
if neither @aam nor @mkustermann have cycles I can take on this myself, just let me know.

**Comment by aam** [comment]
Awesome work! 

>     // Note: we should probably make SafepointReadRwLocker constructor private 
>    // to ensure that it is only ever used through WithSafepointReadRwLock

It seems there are only handful of places where SafepointReadRwLocker scope returns a raw pointer, more places where use of SafepointReadRwLocker is safe(for example, https://github.com/dart-lang/sdk/blob/master/runtime/vm/compiler/call_specializer.cc#L1523). Given that I'm not sure it's worth hiding SafepointReadRwLocker.

**Comment by mraleph** [comment]
> It seems there are only handful of places where SafepointReadRwLocker scope returns a raw pointer, more places where use of SafepointReadRwLocker is safe.

My concern here would be that it is easy to forget and make a mistake.

Hiding constructor is a preventing measure. An alternative would be to have some sort of lint, but it seems better to just prevent accidental misuse. Though I can see that we have a lot of safepoint lockers in the code base and rewriting all of the occurances might be a huge change.

**Comment by aam** [comment]
Yeah, I've got only 13 places (out of ~100) that had to be fixed https://dart-review.googlesource.com/c/sdk/+/184920

**Comment by aam** [comment]
though still see the crash reported originally with patched flutter_tester

**Comment by mraleph** [comment]
Looking at the CL - you have not migrated `SafepointReadRwLocker` cases which have the same problem AFAIK, e.g. I have traced some of the crashes to `Class::LookupFunctionAllowPrivate`.

**Comment by aam** [comment]
Ah, true. Fixed those few places and test passes now.
