### ISSUE TITLE
Analyzer: Remove a widget from widget tree

### ISSUE THREAD

**Issue by khoadng** [dart-lang/sdk#45002]
**Problem**
I don't know if this is possible but it would be nice to have a quick code action to remove a widget from the widget tree for fast coding and refactoring, especially when the widget tree is heavily nested, so we don't have to waste time manually finding matching brackets.

**Possible solution**
Something like the opposite of "Wrap with widget..." would be cool.

**Dart version**
`Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"`

**Comment by bwilkerson** [comment]
There is already a quick assist (code action) for that. The menu label is "Remove this widget".

If there's a place where it ought to be showing up but isn't, please send us a short piece of code that illustrates where it fails to appear.

**Comment by khoadng** [comment]
Hmm, somehow I missed that menu label. I must be blind then.
Anyway, thanks for your help.
