### ISSUE TITLE
dart analyze command does not have --format parameter like dartanalyzer

### ISSUE THREAD

**Issue by bitsydarel** [dart-lang/sdk#45001]
This tracker is for issues related to:

Analyzer

Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
MacOSX

dart analyze does not support the command **--format machine** which is needed for utilities that parse the analyzer output.

**Comment by bwilkerson** [comment]
Actually, it does support the `--format` option, it just isn't included in the help text unless you ask for `--verbose` help.

**Comment by bitsydarel** [comment]
@bwilkerson 

$ dart analyze -h
Analyze the project's Dart code.

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options.

#########################

$ dart analyze -h --verbose
Analyze the project's Dart code.

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options.

##########################

$ dart help
A command-line utility for Dart development.

Usage: dart [<vm-flags>] <command|dart-file> [<arguments>]

Global options:
-h, --help                 Print this usage information.
-v, --verbose              Show additional command output.
    --version              Print the Dart SDK version.
    --enable-analytics     Enable anonymous analytics.
    --disable-analytics    Disable anonymous analytics.

Available commands:
  analyze   Analyze the project's Dart code.
  compile   Compile Dart to various formats.
  create    Create a new project.
  format    Idiomatically format Dart source code.
  pub       Work with packages.
  run       Run a Dart program.
  test      Run tests in this package.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.

###########################

y$ dart help --verbose
A command-line utility for Dart development.

Usage: dart [<vm-flags>] <command|dart-file> [<arguments>]

Global options:
-h, --help                              Print this usage information.
-v, --verbose                           Show additional command output.
    --version                           Print the Dart SDK version.
    --enable-analytics                  Enable anonymous analytics.
    --disable-analytics                 Disable anonymous analytics.
    --enable-experiment=<experiment>    Enable one or more experimental features
                                        (see dart.dev/go/experiments).

          [extension-methods]           Extension Methods (no-op - enabled by
                                        default)
          [non-nullable]                Non Nullable by default
          [nonfunction-type-aliases]    Type aliases define a <type>, not just a
                                        <functionType>
          [triple-shift]                Triple-shift operator
          [value-class]                 Value class
          [variance]                    Sound variance

    --diagnostics                       Show tool diagnostic output.

Available commands:
  analyze   Analyze the project's Dart code.
  compile   Compile Dart to various formats.
  create    Create a new project.
  format    Idiomatically format Dart source code.
  pub       Work with packages.
  run       Run a Dart program.
  test      Run tests in this package.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.

**Comment by bitsydarel** [comment]
@bwilkerson As you can see none, it's not specified in the help.

**Comment by bitsydarel** [comment]
```shell
dart analyze --format machine
Could not find an option named "format".

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options.
```

**Comment by bitsydarel** [comment]
Can we please re-open this issue ? as it's obviously not working as expected.

**Comment by bwilkerson** [comment]
According to `git blame`, it was added three months ago (https://github.com/dart-lang/sdk/blob/master/pkg/dartdev/lib/src/commands/analyze.dart#L46). I can only assume that it hasn't made it into a stable build yet.

When I use an SDK built from master, I see
```
$ dart analyze -h -v
Analyze the project's Dart code.

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)
    --format=<value>         Specifies the format to display errors.

          [default]          The default output format. This format is intended to be user consumable.
                             The format is not specified and can change between releases.
          [machine]          A machine readable output. The format is:
                             
                             SEVERITY|TYPE|ERROR_CODE|FILE_PATH|LINE|COLUMN|LENGTH|ERROR_MESSAGE
                             
                             Note that the pipe character is escaped with backslashes for the file path and error
                             message fields.

Run "dart help" to see global options.
```

So I believe that the feature has been implemented and we're just waiting for a stable build to be released.

**Comment by bitsydarel** [comment]
Thanks, this completely  answer my question.
