### ISSUE TITLE
 calculation bug

### ISSUE THREAD

**Issue by ivsaneesh** [dart-lang/sdk#45019]
This is very interesting result :

print('result ${43.12 - 93.12 + 50}');
output -> result -7.105427357601002e-15

 print('result ${43.12  + 50 - 93.12}');
output -> result 0

**Comment by mraleph** [comment]
That's how floating point arithmetic works. See https://floating-point-gui.de/ for more details. 

If you want precise decimal arithmetic you need to use an appropriate package for that, e.g. https://pub.dev/packages/decimal
