### ISSUE TITLE
Assignments to .length of list with non-nullable element type present in kernel

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#45013]
This causes problems with strict checking. For instance, this `.length` assignment:
https://github.com/dart-lang/sdk/blob/77da201b19eaf23185465a90492a211bb6a3e978/pkg/kernel/lib/class_hierarchy.dart#L1285-L1286
causes the test
```
vm/dart/strict_null_safety_checks_in_weak_mode_test DartkCrash (expected Pass)
```
to fail on configurations
```
dartk-weak-asserts-linux-debug-ia32
dartk-weak-asserts-linux-release-ia32
dartk-weak-asserts-win-release-ia32
```

**Comment by lrhn** [comment]
@bwilkerson Would it be possible for the analyzer to warn about the pattern `<PotentiallyNonNullableType>[]..length = ...`? 
It's was common pattern pre-null safety, and it should be easily detectable.
