### ISSUE TITLE
co19_2/LibTest/io/FileSystemMoveEvent/destination_A01_t02 turned stable RuntimeError from flaky on dartk-mac-release-x64

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#45016]
```
--- Command "vm" (took 45.000825s):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/destination_A01_t02.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
NoSuchMethodError: The getter 'destination' was called on null.
Receiver: null
Tried calling: destination
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _main.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/destination_A01_t02.dart:32:44)
#2      testFileSystemEvent (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:56:7)
<asynchronous suspension>
#3      _main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/destination_A01_t02.dart:28:3)
<asynchronous suspension>
#4      inSandbox (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:24:12)
<asynchronous suspension>
#5      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemMoveEvent/destination_A01_t02.dart:20:3)
<asynchronous suspension>

--- Re-run this test:
python tools/test.py -n dartk-mac-release-x64 co19_2/LibTest/io/FileSystemMoveEvent/destination_A01_t02
```

https://dart-ci.appspot.com/log/vm-kernel-mac-release-x64/dartk-mac-release-x64/12898/co19_2/LibTest/io/FileSystemMoveEvent/destination_A01_t02

@stefantsov, this happened on your commit. Any chances it's related?

There are new test failures on [[cfe] Disallow super-bounded aliased constructor invocations](https://github.com/dart-lang/sdk/commit/b994d51d98b7ba139f69ee3901742050cb80db43).

The tests
```
co19_2/LibTest/io/FileSystemMoveEvent/destination_A01_t02 RuntimeError (expected Pass)
language_2/async/return_throw_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartdevk-checked-linux-release-firefox
dartk-mac-release-x64
```

**Comment by mkustermann** [comment]
Looking at this it seems to have absolutely nothing todo with CFE.

The test is ensuring a file system watch of directory reports a `FileSystemMoveEvent`. Though on MacOS our file system watcher implementation will never report move events. Instead it will report a pair of delete/create events.

This makes the test hit an internal timeout - after 45 seconds - after which it reports a `null` event. This is where the null NSM exception happens.

The bug has been fixed for `co19` in https://github.com/dart-lang/co19/commit/4e57666c36552ef3fc0f6fd988c5bf0e103c64b3 but is not present in our `co19_2` suite.

The MacOS file system watcher apparently intentionally doesn't report move events, see 79cf8dc61f6272b41359c9b8fc2d228beb945c89
