### ISSUE TITLE
Failures on [ VM / Service ] Added getAllocationTraces and setTraceClassAllocation RPCs and identity hash support

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#45017]
There are new test failures on [[ VM / Service ] Added getAllocationTraces and setTraceClassAllocation RPCs and identity hash support](https://github.com/dart-lang/sdk/commit/3e83400e0f77518cb4009ed0b52e30f3c327233b).

The tests
```
service_2/get_allocation_traces_test/dds RuntimeError (expected Pass)
service_2/get_allocation_traces_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
app_jitk-linux-debug-x64
app_jitk-linux-release-x64
dartk-linux-debug-simarm64c
dartk-linux-release-simarm
dartk-linux-release-simarm64
```

cc @bkonyi @rmacnak-google

**Comment by bkonyi** [comment]
I can't find these failures anywhere on the bots from around the time this issue was filed. These tests should be skipped on app_jit and simarm configurations.

Can you link the failure logs @dcharkes?

**Comment by dcharkes** [comment]
@bkonyi https://dart-ci.firebaseapp.com/#showLatestFailures=false and search for 45017.

**Comment by bkonyi** [comment]
This was resolved in https://github.com/dart-lang/sdk/commit/7315480f5d8eba30ed455d83344daa1108627157.
