### ISSUE TITLE
No published analyzer available for language version 2.13.0

### ISSUE THREAD

**Issue by ripeyd** [dart-lang/sdk#45011]
[INFO] Running build...
[WARNING] json_serializable:json_serializable on lib/main.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.12.0
SDK language version: 2.13.0

**Comment by ripeyd** [comment]
Version issue resolved.

**Comment by wenbo-ya** [comment]
How to solve it？

**Comment by ripeyd** [comment]
Flutter分支错误，将Flutter切换到stable就可解决

$ flutter channel stable




发件人: 王文博 <notifications@github.com>
答复: dart-lang/sdk <reply@reply.github.com>
日期: 2021年3月1日 星期一 下午6:00
收件人: dart-lang/sdk <sdk@noreply.github.com>
抄送: ripeyd <ripeyd@hotmail.com>, State change <state_change@noreply.github.com>
主题: Re: [dart-lang/sdk] No published analyzer available for language version 2.13.0 (#45011)


How to solve it？
