### ISSUE TITLE
CFE: incorrect return type inference for non-local variables initialized with function literals

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45029]
All of the function literals (and the local function) in the example below should have inferred type `Never Function()` per the [spec here](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#function-literal-return-type-inference).  

The CFE correctly infers this for `a` and `b` (the local variables) but incorrectly infers `Null Function()` for the top level variable, the static class variable, and the instance variable.

```dart
var c = () {
  throw "Baz";
};

class C {
  static var d = () {
    throw "Baz";
  };
  var e = () {
    throw "Baz";
  };
}
void main() {
  var a = () {
    throw "Hello";
  };
  b() {
    throw "World";
  }

  int x;
  x = a; // Correct
  x = b; // Correct
  x = c; // Incorrect
  x = C.d; // Incorrect
  x = C().e; // Incorrect
}
```

The analyzer infers this correctly, and the fix should be almost entirely non-breaking.

**Comment by johnniwinther** [comment]
cc/ @stefantsov

**Comment by leafpetersen** [comment]
@stefantsov Shall we go ahead and slip this to the next release?

**Comment by johnniwinther** [comment]
I think we can make this slip.

**Comment by johnniwinther** [comment]
cc @stereotype441

**Comment by franklinyow** [comment]
@johnniwinther @stefantsov What's the status of this?

**Comment by johnniwinther** [comment]
This is rooted in the language issue https://github.com/dart-lang/language/issues/1650

I'll remove the milestone since we need to resolve the language issue before fixing this.
