### ISSUE TITLE
Analyzer does not report unused dart:cli import if waitFor is used from another library

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#45028]
```dart
import 'dart:cli'; // Unused import expected, not reported

import 'some_other.dart'; // Exports the `waitFor` we are using

void main() {
  waitFor();
}
```

**Comment by bwilkerson** [comment]
@srawlins Who's done some work in this area.

**Comment by srawlins** [comment]
Is `waitFor` also exported from `dart:cli`? I can't find dart:cli at the docs. https://api.dart.dev/stable/2.10.5/index.html

In any case this may be a case of https://github.com/dart-lang/sdk/issues/44569

**Comment by natebosch** [comment]
There is a different `waitFor` in `dart:cli` than the one in my example. It isn't an export, it is a completely separate function.

`dart:cli` was the case I stumbled across, but trying now it looks like you can do this with any `dart:` import.

```dart
import 'dart:math';  // Unused import expected, not reported

import 'bar.dart';

void main() {
  max();
}
```

```dart
// bar.dart
void max() {}
```

**Comment by natebosch** [comment]
> I can't find `dart:cli` at the docs.

It's hidden from the docs. It is an experimental API.

**Comment by srawlins** [comment]
One issue is that it is generally illegal to have two imports which each contain an element of the same name (`ambiguous_import`). The one exception is if one import is a "system library" (any thing `dart:` I think), then the non-system import elements take priority; they override any elements of the same name from the system library.

The analyzer's concepts of namespaces doesn't necessarily take this into account right now. I think I can put together a fix.

**Comment by bwilkerson** [comment]
> One issue is that it is generally illegal to have two imports which each contain an element of the same name (`ambiguous_import`).

Minor point of clarification, but it's only an error if the conflicting name is referenced in the library containing those imports.

> The analyzer's concepts of namespaces doesn't necessarily take this into account right now.

I'd be somewhat surprised if it fails and nobody had noticed. Do you have a test case that fails?
