### ISSUE TITLE
[vm/ffi] Different results when reading 64-bit integer as Int16 and Int8

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#45025]
The following test works
```dart
import "dart:ffi";
import "../ffi_utils.dart";
import "../../../Utils/expect.dart";

class S1 extends Struct {
  @Int64()
  external int x;
}

class S2 extends Struct {
  @Int16()
  external int x;
}

class S3 extends Struct {
  @Int8()
  external int x;
}

void main() {
  Pointer<S1> s1 = calloc<S1>();
  try {
    s1.ref.x = 0x1122334455667788;
    Expect.equals(0x1122334455667788, s1.ref.x);

    Pointer<S2> s2 = new Pointer.fromAddress(s1.address);
    Expect.equals(0x0000000000007788, s2.ref.x);

    Pointer<S3> s3 = new Pointer.fromAddress(s1.address);
    Expect.equals(0xFFFFFFFFFFFFFF88, s3.ref.x);
  } finally {
    calloc.free(s1);
  }
}
```
Why when we read 64-bit integer as Int16, then it is read as `0x0000000000007788` but when we read it as Int8 it is read as `0xFFFFFFFFFFFFFF88`, not as `0x0000000000000088`?

Tested on `Dart SDK version: 2.13.0-edge.34ce22dcc1e8637e3034f600dcc42c7e7b5df808 (be) (Thu Feb 11 16:33:43 2021 +0000) on "linux_x64"`

**Comment by TimWhiting** [comment]
This is because you are reading it as a signed integer not an unsigned integer. The bit representation of it is:
`10001000` so it gets sign-extended. (A one in the first bit means that the integer is negative for signed integers).

**Comment by sgrekhov** [comment]
@TimWhiting thank you. Indeed. Closed as Work as designed
