### ISSUE TITLE
[CP][beta channel] A few pub client fixes

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#45022]
**commit(s) to merge**: https://dart-review.googlesource.com/c/sdk/+/185100

**merge instructions**: clean merge 

**What is the issue**: This fixes 
* https://github.com/dart-lang/pub/issues/2854 that would lead `pub get` to require network access even if the cache is pupulated.
* An issue with argument parsing where `pub broken_argument` would show a stack trace in addition to the nice error message

**Why cherrypick**: These seem low-risk but high-value polish for the pub client.

**Risk**: The fixes themselves might be buggy.

**Link to original  issue(s)**:
* https://github.com/dart-lang/pub/issues/2854
* https://github.com/dart-lang/pub/issues/2868 lead to the second fix. It is however not the reason for cherry-picking.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by vsmenon** [comment]
@sigurdm @jonasfj - do you have specific concerns on "The fixes themselves might be buggy" beyond the usual risk of a cherry pick?

**Comment by vsmenon** [comment]
lgtm
