### ISSUE TITLE
Wrong analyzer suggestion for conditional operator

### ISSUE THREAD

**Issue by SashaFarkas** [dart-lang/sdk#45030]
Dart plugin 3.19.2
Dart SDK version: 2.10.4 (stable)
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64)
[✓] VS Code (version 1.53.2)
```

Analyzer says, that I can replace this code with "if-else" condition.
`final isInitialized = state is ReadyState ? state.isInitialized : false;`

When I choose "replace with if-else", it becomes this:
```
        final isInitialized;
        if (state is ReadyState) {
          isInitialized = state.isInitialized;
        } else {
          isInitialized = false;
        }
```

Which is incorrect, of course.

**Comment by lrhn** [comment]
I agree that the suggestion doesn't work for initializer expressions, especially with null safety.

The rewrite is wrong on multiple points: 
* Doesn't type the variable as `bool`,
* Makes the variable final and late-initialized, but not marked `late`.

(What the analyzer should warn about, IMO, is to never use a conditional expression where one of the branches is a boolean literal. Such can always be written shorter using `||`, `&&` and `!` instead: `final isInitialized = state is ReadyState && state.isInitialized;`)

**Comment by bwilkerson** [comment]
The analyzer doesn't produce a diagnostic for the OP's case (either by default or via lint). What it does do is offer a code transformation option (which we refer to as a "quick assist"). The assist needs to be fixed to either not appear for conditionals in initializers or to add a type annotation and `late` modifier. For future reference, the class that implements the assist is `ReplaceConditionalWithIfElse`.

> What the analyzer should warn about, IMO, is to never use a conditional expression where one of the branches is a boolean literal.

The lint `avoid_bool_literals_in_conditional_expressions` does that.

**Comment by bwilkerson** [comment]
Failing test added in https://dart-review.googlesource.com/c/sdk/+/185493.

**Comment by scheglov** [comment]
I think `late` is not necessary here.
The variable is initialized on both branches of the `if` statement.
So, it has better speed, and provides better guarantees (IMHO) without `late`.

```dart
void f(bool c) {
  int a;
  if (c) {
    a = 111;
  } else {
    a = 222;
  }
  print(a);
}
```

**Comment by bwilkerson** [comment]
Fixe by https://dart-review.googlesource.com/c/sdk/+/186200.
