### ISSUE TITLE
How to call the object

### ISSUE THREAD

**Issue by absc** [dart-lang/sdk#45038]
I don’t know how to use it when I using leafLet。
in leafLet，an object has been defined，how can i use it with js 0.6.2 like  this:
`var EPSG4326  = extend({},Earth,{
     code:'EPSG:4326',
     projection:LonLat,
     transformation:toTransformation(1/180,1,-1/180,0.5)
})`
EPSG4326  object in L.CRS

**Comment by lrhn** [comment]
I'm not sure how to answer this question. 
You might have more luck if you ask in a forum related to leafLet (is that the [Dart package](https://github.com/rwl/leaflet.dart) or something else?)

**Comment by absc** [comment]
> I'm not sure how to answer this question.
> You might have more luck if you ask in a forum related to leafLet (is that the [Dart package](https://github.com/rwl/leaflet.dart) or something else?)

i am use flutter to develop web programs with js 0.6.2,but i don't know how to call object in web

**Comment by mit-mit** [comment]
Sorry, this issue tracker is meant for filing known issues, not for asking questions. Please consider using a community site like StackOverflow or similar.
