### ISSUE TITLE
Error in sha256 calculation

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/sdk#45039]
I have a quite strange case calculating the sha256 hash of a password.
If I use it on the server side, it works, on a web (with angular) application, it doesn't.
I tried to replicate the case creating a new web project, but in this new project the error does not happen.
I recently moved to dart 2.6.1, with dart 2.5.2 everything was working fine.
As I was afraid that the cause could be some dirty cache, I cleaned the pub/cache folder, and deleted the project .dart_tool one, but nothing helped.
So, I started debugging.
I got the point that is generating the problem, but I could not understand what's going on.
The problem is in the `HashSink` class, in the `_finalizeData()` method.
```
    if (_endian == Endian.big) {
      byteData.setUint32(offset, highBits, _endian);
      byteData.setUint32(offset + bytesPerWord, lowBits, _endian);
    } else {
      byteData.setUint32(offset, lowBits, _endian);
      byteData.setUint32(offset + bytesPerWord, highBits, _endian);
    }
```
When the program checks `Endian.big`, the check fails and the else block is performed.
I cannot understand why. If I look in the IDE debugger (webStorm), both `_endian` and `Endian.big` have the `_littleEndian` field = `false`. The type of `_endian` is "`Endian`", the type of `Endian.big` is "`typed_data.Endian`". If I look in the chrome debugger, both are of type `Endian`, but the `_endian._littleEndian` field is `null`.
I'm getting crazy...

**Comment by lrhn** [comment]
I've moved this to be a bug-report against the dev-compiler.

**Comment by giorgiofran** [comment]
I'm sorry, I forgot to report that from release 2.8 everything is working again. I close this issue
