### ISSUE TITLE
Rename DirectoryEntry and similar classes in dart:html to new class names

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#45036]
Chromium has changed the native type name for these classes (`Entry`, `DirectoryEntry`, `DirectoryReader`, etc.) to prepend `FileSystem` over concerns about those original names in the global scope. These classes have not been updated in `dart:html`, and as such, the native type fails to be intercepted.

They need to be renamed and refactored to use the updated native type names.

Context: https://bugs.chromium.org/p/chromium/issues/detail?id=652814

**Comment by xfoldvar** [comment]
ping

**Comment by srujzs** [comment]
Have a CL changing the bindings, currently testing, and I'll report back when it's reviewed and landed.
