### ISSUE TITLE
[CP][beta channel] Fix for possible heap corruption

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#45031]
**commit(s) to merge**: 1e114a88d069d2bd7101ad3f5f68e4bd4612bc17

**merge instructions**: Clean merge.

**What is the issue**: C++ code that uses a `SafepointRwLocker` in a scope that contains a return statement (and the function returns a raw object pointer) can cause heap corruption if the destructor is forced into a slow path and GC happens.

**What is the fix**: Refactor `SafepointRwLocker` to guarantee no safepoint transition can happen in the destructor.

**Why cherrypick**: It can cause heap corruption and therefore undefined behavior.

**Risk**: Low.

**Link to original  issue(s)**: 
 * [b/176441206](https://b.corp.google.com/issues/176441206)
 * https://github.com/dart-lang/sdk/issues/44998

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @mraleph

**Comment by mraleph** [comment]
I support cherry pick due to severity of the issue. Flutter users will experience it as random crashes in development and testing.

**Comment by vsmenon** [comment]
lgtm

**Comment by a-siva** [comment]
lgtm

**Comment by franklinyow** [comment]
@whesse 
Please start a new build with this new CP

**Comment by whesse** [comment]
Beta build started with this cherry pick.

**Comment by pcsosinski** [comment]
in .15
