### ISSUE TITLE
network_policy.dart is missing from Flutter SDK sources which prevents navigating to some functions

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45041]
Originally raised at https://github.com/flutter/flutter/issues/76228. @jonahwilliams looked into it and found:

> The problem is network_policy.dart is missing from the io_sources.gni rule, so this file isn't getting copied into the right place:
> 
> https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/io_sources.gni

I'm not familiar with this file so I don't know whether there's a reason for this or it's an oversight, but it seems like here may be the right place for that question.

-- original issue --

This could be deliberate, but it seems a bit strange. There's a function called `isInsecureConnectionAllowed` in the `dart:io` library when using the Dart SDK directly, but missing when using it via Flutter:

<img width="973" alt="Screenshot 2021-02-17 at 19 34 17" src="https://user-images.githubusercontent.com/1078012/108257788-3332e900-7157-11eb-8f33-d7dcbf2abb53.png">

The function is defined in the file `network_policy.dart` which does not appear in the `sky_engine` package inside Flutter, which means the analysis server doesn't discover it/can't navigate to it:

<img width="1011" alt="Screenshot 2021-02-17 at 18 01 05" src="https://user-images.githubusercontent.com/1078012/108247145-307dc700-714a-11eb-8063-c47a7f711ea7.png">

It seems like maybe this function isn't available, however if you step into the HttpClient class while debugging, the function actually _does_ exist in the VM (and the source code can be downloaded from the VM so you can step into it):

<img width="635" alt="Screenshot 2021-02-17 at 18 07 42" src="https://user-images.githubusercontent.com/1078012/108247851-185a7780-714b-11eb-8232-e740e53fd09f.png">

I don't know if this is a bug, but it is a little confusing when debugging - you can step into functions but can't use Go-to-Definition in the editor to get to them. (This originally came up at https://github.com/Dart-Code/Dart-Code/issues/3017).

**Comment by jonahwilliams** [comment]
I opened a small CL to add this file, if that is the right answer: https://dart-review.googlesource.com/c/sdk/+/185489

**Comment by DanTup** [comment]
The change above was merged (https://github.com/dart-lang/sdk/commit/91ae755c3534d8eb0e1490d30ccaf05229aae0f2). Thanks!
