### ISSUE TITLE
Consider removing hard-coded experimental flags for core libraries from pkg/dev_compiler/tool/patch_sdk.dart

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#45042]
When trying to enable `triple-shift` experiment for core libraries (in order to add `int.operator>>>`), I discovered that it was not enough to enable the experiment in `sdk/lib/_internal/allowed_experiments.json`.

There is another place where those experimental flags should be updated - in `pkg/dev_compiler/tool/patch_sdk.dart`:

https://github.com/dart-lang/sdk/blob/6c4f354458dc5f42c6bad44d7edb1082777ece52/pkg/dev_compiler/tool/patch_sdk.dart#L479-L482

This code also uses a fixed language version which can become outdated.

We should probably remove these hard-coded values and obtain them from `sdk/lib/_internal/allowed_experiments.json` and `tools/experimental_features.yaml`.

/cc @nshahan @sigmundch

**Comment by sigmundch** [comment]
We went ahead and deleted this script in 06a4b109bce970fbd98bf72774a8787124900dee

It was used by a single test and recently we reached a point were the test was no longer providing much value.
