### ISSUE TITLE
[CP][beta channel] Update CHANGELOG for 2.12.0.

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#45048]
**commit(s) to merge**: [e962528](https://dart.googlesource.com/sdk/+/e962528c413683d79e6141f72367d7f97d858759)

**merge instructions**: clean merge

**What is the issue**: update/clean up of changelog for 2.12.0 release

**What is the fix**:  
- Reword null safety prose some.
- Mention other new language features.
- Clean up verbiage and formatting of other entries.

**Why cherrypick**: Part of release checklist task

**Risk**: low

**Link to original  issue(s)**: N/A

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @munificent

**Comment by kevmoo** [comment]
FYI: this is kinda nice, but AFAIK we ONLY reference the changelog in
github @master.

Getting this into the branch is of...not a lot of value.

Historical accuracy, maybe.

**Comment by franklinyow** [comment]
Ok, in that case I will close this.

**Comment by kevmoo** [comment]
@munificent – okay with you?
