### ISSUE TITLE
Dart command no longer supports running kernel files directly

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#45040]
See failing CI run here https://github.com/dart-lang/build/runs/1928577350?check_suite_focus=true#step:6:42

Previously you could run a dill file like `dart <dill-file>` but now you get a message like `Could not find a command named "<path-to-dill-file>"`. It looks like it thinks the dill file is a command and not a script. 

I am pretty sure this is a very recent breakage (last 24 hours)

cc @jwren @devoncarew

**Comment by jakemac53** [comment]
Or actually ya it must have landed between the last dev releases actually, so not necessarily the last 24 hours but fairly recent

**Comment by devoncarew** [comment]
cc @bkonyi

**Comment by a-siva** [comment]
which version of Dart is this failing on ?

I synched up to TOT, did a build and it seems to work.

**Comment by bkonyi** [comment]
I can't reproduce at ToT either. It's 2.13.0-38.0.dev that we're seeing the failure, although I'm still building and haven't had a chance to try that revision yet.

**Comment by jakemac53** [comment]
I am seeing this with the most recent dev release (2.13.0-48.0.dev)

**Comment by bkonyi** [comment]
> I am seeing this with the most recent dev release (2.13.0-48.0.dev)

Is that in addition to 2.13.0-38.0.dev? That's what's in the logs from the GitHub check.

**Comment by jakemac53** [comment]
It looks like I can reproduce this on `2.13.0-38.0.dev` as well actually - we only just started seeing the error today though as far as I am aware.

**Comment by bkonyi** [comment]
Strange... I didn't see anything on 2.13.0-38.0.dev either, but I was using a debug build. I'll try again with release.

**Comment by bkonyi** [comment]
`2.13.0-48.0.dev` debug seems to work too.

**Comment by jakemac53** [comment]
@bkonyi I wonder if there is some detection going on which doesn't support modular dill files specifically? Or maybe it has to do with the output extension you are using (ours use the `.dill` extension).

You can repro this specifically by checking out the build repo https://github.com/dart-lang/build and doing:

```
cd build_vm_compilers
pub upgrade
pub run build_runner build - out
dart test/out/vm_kernel_integration_test.vm.dill
```

I noticed actually when doing this specific workflow on the latest dev I actually see this error:

```
Unhandled exception:
Unimplemented handling of missing static target
#0      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by jakemac53** [comment]
Sorry ignore the last part of my last comment, I had slightly incorrect repro instructions, the correct instructions are this:

```
cd build_vm_compilers
pub upgrade
pub run build_runner build - out
dart out/test/vm_kernel_integration_test.vm_test.vm.app.dill
```

**Comment by jakemac53** [comment]
Sorry, I keep getting confused by the output from the tool here because it gives the above message when the file passed does not exist. I had the path wrong again, I updated the previous method with the new path.

Once I do that it looks like things are working, so what seems like has happened is that maybe paths changed for the files that we are outputting or something. I am going to close this issue for now as I think this is something on our end that has changed.

**Comment by bkonyi** [comment]
Ah yeah, that was going to be my next question since I still couldn't reproduce the failure but was getting a `NoSuchMethodError` thrown. Thanks for following up!
