### ISSUE TITLE
Difference in NNBD weak mode behavior between ia32 and x64

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#45050]
An existing test started failing on `ia32` that passes on `x64`, from [this log](https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-release-ia32/dartk-weak-asserts-linux-release-ia32/135/vm/dart/strict_null_safety_checks_in_weak_mode_test)
```
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --enable_asserts --strict_null_safety_checks --optimization_counter_threshold=10 --deterministic --no-sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/tests/vm/dart/strict_null_safety_checks_in_weak_mode_test.dart

exit code:
252

stderr:
Crash when compiling file:///b/s/w/ir/runtime/tests/vm/dart/strict_null_safety_checks_in_weak_mode_test.dart,
at character offset null:
type 'Null' is not a subtype of type 'Uri'
#0      _LinkedHashMapMixin._init (dart:collection-patch/compact_hash.dart:227:16)
#1      _LinkedHashMapMixin._rehash (dart:collection-patch/compact_hash.dart:199:7)
#2      _LinkedHashMapMixin._insert (dart:collection-patch/compact_hash.dart:247:7)
#3      _LinkedHashMapMixin.[]= (dart:collection-patch/compact_hash.dart:296:7)
#4      MapMixin.addAll (dart:collection/maps.dart:129:11)
#5      BinaryBuilder._mergeUriToSource (package:kernel/binary/ast_from_binary.dart:948:11)
#6      BinaryBuilder._readOneComponent (package:kernel/binary/ast_from_binary.dart:838:5)
#7      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:605:33)
#8      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#9      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:575:21)
#10     ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:482:10)
#11     ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:429:13)
<asynchronous suspension>
#12     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:82:28)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#14     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#15     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#16     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#17     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:397:11)
<asynchronous suspension>
#18     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:212:45)
<asynchronous suspension>
#19     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:872:37)
<asynchronous suspension>


#0      _LinkedHashMapMixin._init (dart:collection-patch/compact_hash.dart:227:16)
#1      _LinkedHashMapMixin._rehash (dart:collection-patch/compact_hash.dart:199:7)
#2      _LinkedHashMapMixin._insert (dart:collection-patch/compact_hash.dart:247:7)
#3      _LinkedHashMapMixin.[]= (dart:collection-patch/compact_hash.dart:296:7)
#4      MapMixin.addAll (dart:collection/maps.dart:129:11)
#5      BinaryBuilder._mergeUriToSource (package:kernel/binary/ast_from_binary.dart:948:11)
#6      BinaryBuilder._readOneComponent (package:kernel/binary/ast_from_binary.dart:838:5)
#7      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:605:33)
#8      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#9      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:575:21)
#10     ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:482:10)
#11     ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:429:13)
<asynchronous suspension>
#12     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:82:28)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#14     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#15     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#16     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#17     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:397:11)
<asynchronous suspension>
#18     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:212:45)
<asynchronous suspension>
#19     _processLoadRequest (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:872:37)
<asynchronous suspension>

--- Re-run this test:
python tools/test.py -n dartk-weak-asserts-linux-release-ia32 vm/dart/strict_null_safety_checks_in_weak_mode_test
```

I've bisected it and it seems to have started after partial NNBD migration of `package:kernel` in 8467186ca0aa1d2b716ed00cb9bc55f74d9ddda9.

Given that it fails on `ia32` but not `x64` there's a good chance this is a VM bug.

/cc NNBD team @alexmarkov @crelier @a-siva

**Comment by alexmarkov** [comment]
The failing test enables `--strict_null_safety_checks` option which makes type checks more strict, respecting non-nullability of types coming from migrated libraries. It is useful in NNBD weak mode (without sound null safety) in order to provide more strict testing of the migrated code when there is still some unmigrated code left. It allows users to detect and fix some violations of null-safety at run time before everything is migrated and they can run in sound mode. This is an opt-in flag.

On x64 VM use kernel service as a snapshot, while on IA32 VM doesn't use snapshot. Snapshot is created during the Dart SDK build, which is done without `--strict_null_safety_checks` option. When VM uses kernel service without snapshot on IA32, it also compiles and runs migrated CFE code with `--strict_null_safety_checks` option. The same behavior can be reproduced on x64 if `create_kernel_service_snapshot` is set to `false` on x64 here:

https://github.com/dart-lang/sdk/blob/29ed048cf2d38f08c137b23dad708a8d6e6dd3e3/runtime/runtime_args.gni#L89-L90

@johnniwinther This stack trace indicates a real violation of non-nullability of types in CFE: `Component.uriToSource` is `Map<Uri, Source>`, but code from `ast_from_binary.dart` puts `null` into that map. Would you like to fix CFE code to avoid violating non-nullability? Longer term, is it useful to have more strict testing of CFE code until it switches to sound mode? If you don't want to see errors coming from a more strict null safety on CFE code, I can suppress this option for kernel service isolate or disable this test on IA32.

Tentatively assigning this to @johnniwinther. Please reassign this issue to me if you'd like to opt out CFE code in kernel service from more strict checks.

**Comment by johnniwinther** [comment]
I'm partway migrating `package:kernel`. `ast.dart` has been migrated, but not the use cases (from `ast_to_binary.dart` and `ast_from_binary.dart`) that show that `Component.uriToSource` should support `null` keys. This will be updated shortly.

**Comment by mkustermann** [comment]
> On x64 VM use kernel service as a snapshot, while on IA32 VM doesn't use snapshot. 

@alexmarkov Can we use the same flags when training & running the kernel isolate, independent of whether a snapshot is used or not? This would prevent such differences in the future.

**Comment by alexmarkov** [comment]
Yes, we can enforce more strict null safety checking during training of kernel service too (after this non-nullability violation is fixed).

@johnniwinther Would you like CFE to opt-in to more strict checks or prefer to opt out? This may affect how much code you would need to touch in one go during migration, but it may also provide more confidence that you will not see errors at run time after enabling sound null safety.

**Comment by a-siva** [comment]
Removing February milestone as this is a special case issue.

**Comment by aam** [comment]
The test is failing on newly added arm64 bots: https://dart-ci.appspot.com/log/vm-kernel-nnbd-mac-debug-arm64/dartk-weak-asserts-mac-debug-arm64/1/vm/dart/strict_null_safety_checks_in_weak_mode_test

**Comment by alexmarkov** [comment]
CFE and kernel service were fully migrated to null safety and now kernel service runs in sound mode. `vm/dart/strict_null_safety_checks_in_weak_mode_test` passes on all bots.
