### ISSUE TITLE
nnbd: Dart does not throw a compile error for the `Never` constant canonical type in no-sound null safety mode.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45067]
Dart SDK version: 2.13.0-48.0.dev (dev) (Wed Feb 17 19:36:03 2021 -0800) on "windows_x64"

Here is a code source sample:
``` dart
class C<T> {
  final T x;
  const C(Object? o) : x = o as T;
}

const c = C<Never>(null);

main() {}

```
Both dart and analyzer throw error for the line 6 here because according to the Spec `CONST_CANONICAL_TYPE(Never)` is `Never`.

As this is a static case, seems like in no-sound null safety dart should throw error too.

However this is not so, test example above passes without errors or warnings.

Sample output is:
```
$> dartanalyzer test.dart
Analyzing test.dart...
  error - Evaluation of this constant expression throws an exception. - test.dart:6:11 - const_eval_throws_exception
1 error found.

$> dart test.dart
test.dart:6:11: Error: Constant evaluation error:
const c = C<Never>(null);
          ^
test.dart:3:30: Context: Expected constant 'null' to be of type 'Never', but was of type 'Null'.
  const C(Object? o) : x = o as T;
                             ^
test.dart:6:7: Context: While analyzing:
const c = C<Never>(null);
      ^

$dart --no-sound-null-safety test.dart

$>
```

**Comment by lrhn** [comment]
I non-sound null safety mode, the `as` check allows `null`. You can see that from: 
```dart
main() {
 foo<Never>(null);
}
void foo<T>(Object? o) {
  print(o as T);
}
```
when in unsound mode.

That's what's happening here too. The `o as T` is checking whether `o` is `null` or `Never`, which it is.

Non sound null-safety makes a distinction between `o is T` and `o as T`, where the latter implicitly allows `null` and the former doesn't, just like pre-null-safety `is` checks and `as` casts did.

**Comment by eernstg** [comment]
Note that this looks like a bug in the analyzer (the semantics of constant expression evaluation is specified in terms of the semantics of normal run-time expression evaluation; so when `null is Never` completes normally during an execution with unsound null safety, it should not be a compile-time error as part of constant expression evaluation). However, we will not change the analyzer.

That is precisely the topic of https://github.com/dart-lang/language/issues/1346, and the currently adopted approach is (cf. https://github.com/dart-lang/language/issues/1346#issuecomment-739680187) that the analyzer will treat constant evaluation as if the execution would use sound null checking.
