### ISSUE TITLE
Dart doesn't fully support encapsulation through different files

### ISSUE THREAD

**Issue by AerLiberum** [dart-lang/sdk#45062]
I starter a thread on stackoverflow and I think that overriding through different files (even with library keyword) doesn't work because of a flaw.
https://stackoverflow.com/questions/66277583/how-to-override-private-fields-and-methods-in-dart/66288141#66288141

**Comment by lrhn** [comment]
This is working as intended.

Dart *library privacy* is library based. You cannot refer to a name which is private to a different library.
Libraries can be one file or multiple files (using the `part` declaration), but code belongs to only one library.

**Comment by AerLiberum** [comment]
Do you mean that every project, that uses private methods and fields, must be a library? Why private keyword is binded for libraries only? I think, it's not ok. If inheritance of private fields and methods works in one file, why doesn't it work through many files of the SAME project? Isn't project's scope a library automatically? This is not logical...
