### ISSUE TITLE
Keyboard shortcuts in the migration tool would help a lot

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#45066]
Trying to use the NNBD migration tool on a large project where the tool made hundreds of changes: my preferred approach is to go through each change and to add explicit hints`/*?*/` and `/*!*/` to mark each case that I've reviewed.  This helps me keep track of my progress, allows me to easily stop and restart later, and allows me to commit hints to source control progressively.  However, clicking on the `Add /*?*/ hint` and `Add /*!*/ hint` buttons is physically tedious and bad for accessibility.  It would be great if there were keyboard shortcuts (e.g. `?` and `!`) to add a hint at the current location.

Keyboard shortcuts to navigate to the previous/next change and previous/next file would be most welcome too.

**Dart SDK version**: 2.13.358331929-edge+google3-v2

**Comment by esDotDev** [comment]
Also some sort of moveNext / movePrev would be appreciated, then we could conceivable hint the entire file without using the mouse.

**Comment by jamesderlin** [comment]
The migration tool no longer exists.
