### ISSUE TITLE
`singleWhere` and `firstWhere` behavior on null-safety list

### ISSUE THREAD

**Issue by aliyazdi75** [dart-lang/sdk#45064]
Consider this `List<T>`, I used to define the `orElse` function with `null` return for `singleWhere` and `firstWhere` like this `orElse: () => null`.
But as `T` is not a nullable value, this can't be happening and must define `List<T?>` to do so, although `T` is not a nullable value.

Is this an expected behavior?

**Comment by mehcode** [comment]
https://dart.dev/null-safety/faq#the-iterablefirstwhere-method-no-longer-accepts-orelse---null

> Import package:collection and use the extension method firstWhereOrNull instead of firstWhere.

**Comment by aliyazdi75** [comment]
@mehcode 
Oh, sorry I didn't check that first.
Thanks.
