### ISSUE TITLE
Missing compile-time errors on co19 tests on cfe

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#45075]
There are new test failures on [[co19] Roll co19 to 88b4f0556b0889067efcac45f2b96bc630e5b96c](https://dart-review.googlesource.com/c/sdk/+/186146).

The tests
```
co19/LanguageFeatures/Instantiate-to-bound/class/static/class_typedef_l1_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Instantiate-to-bound/class/static/class_typedef_l2_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Instantiate-to-bound/class/static/class_typedef_l2_t07 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Instantiate-to-bound/typedef/static/typedef_typedef_l1_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/regression/34560_t02 MissingCompileTimeError (expected Pass)
co19/LibTest/ffi/Struct/Struct_A02_t01

are failing on cfe-strong and cfe-weak configurations,
and the tests

co19/LanguageFeatures/nnbd/const_evaluation_A03_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/const_evaluation_A03_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/const_evaluation_A04_t04 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/const_evaluation_A04_t08 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/const_evaluation_A06_t01 MissingCompileTimeError (expected Pass)
```
are failing on cfe-weak configurations

Approving the failures to land the co19 roll

**Comment by johnniwinther** [comment]
cc @stefantsov

**Comment by sgrekhov** [comment]
Failures triage results

co19/LanguageFeatures/Instantiate-to-bound/class/static/class_typedef_l1_t03 MissingCompileTimeError (expected Pass) #44786
co19/LanguageFeatures/Instantiate-to-bound/class/static/class_typedef_l2_t03 MissingCompileTimeError (expected Pass) #44786
co19/LanguageFeatures/Instantiate-to-bound/class/static/class_typedef_l2_t07 MissingCompileTimeError (expected Pass) #44786
co19/LanguageFeatures/Instantiate-to-bound/typedef/static/typedef_typedef_l1_t03 MissingCompileTimeError (expected Pass) #44786
co19/LanguageFeatures/regression/34560_t02 MissingCompileTimeError (expected Pass) #45065
co19/LibTest/ffi/Struct/Struct_A02_t01 #44987

are failing on cfe-strong and cfe-weak configurations,
and the tests

co19/LanguageFeatures/nnbd/const_evaluation_A03_t01 MissingCompileTimeError (expected Pass) #45067
co19/LanguageFeatures/nnbd/const_evaluation_A03_t03 MissingCompileTimeError (expected Pass) #45067
co19/LanguageFeatures/nnbd/const_evaluation_A04_t04 MissingCompileTimeError (expected Pass) #45067
co19/LanguageFeatures/nnbd/const_evaluation_A04_t08 MissingCompileTimeError (expected Pass) #45067
co19/LanguageFeatures/nnbd/const_evaluation_A06_t01 MissingCompileTimeError (expected Pass) #45067
