### ISSUE TITLE
Improve testing of CLI analytics integration

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#45078]
We've hit a few P0/P1 issues in the analytics code that have all come from a single change. This code needs to be more thoroughly tested to ensure user analytics preferences are always respected.

See https://github.com/dart-lang/sdk/issues/45077.

**Comment by vsmenon** [comment]
@bkonyi - any update here?  Is this still a P1?

**Comment by bkonyi** [comment]
No update, can definitely be lower priority.

**Comment by bkonyi** [comment]
This functionality is tested in [package:unified_analytics](https://github.com/dart-lang/tools/tree/main/pkgs/unified_analytics).
