### ISSUE TITLE
New ffi co19 tests crashing on simarm VMs

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#45073]
The new ffi tests in the co19 suite are crashing on simarm architectures.

If this is working as intended, then there should be a Skip added for these tests on these architectures in the status file.

The architectures
dartk-strong-linux-release-simarm
dartk-strong-linux-release-simarm64
dartk-weak-asserts-linux-release-simarm
dartk-weak-asserts-linux-release-simarm64
dartkp-strong-linux-release-simarm64
dartkp-weak-asserts-linux-release-simarm64

are crashing on the tests
co19/LibTest/ffi/Int16/Int16_A01_t01
co19/LibTest/ffi/Int16/Int16_A01_t02
co19/LibTest/ffi/Int16/Int16_A02_t01
co19/LibTest/ffi/Int32/Int32_A01_t01
co19/LibTest/ffi/Int32/Int32_A01_t02
co19/LibTest/ffi/Int32/Int32_A02_t01
co19/LibTest/ffi/Int64/Int64_A01_t01
co19/LibTest/ffi/Int64/Int64_A02_t01
co19/LibTest/ffi/Int8/Int8_A01_t01
co19/LibTest/ffi/Int8/Int8_A01_t02
co19/LibTest/ffi/Int8/Int8_A02_t01
co19/LibTest/ffi/Struct/Struct_A03_t01
co19/LibTest/ffi/Struct/Struct_A03_t02
co19/LibTest/ffi/Struct/Struct_A04_t01
co19/LibTest/ffi/Struct/Struct_A04_t02
co19/LibTest/ffi/Struct/Struct_A05_t01
co19/LibTest/ffi/Struct/Struct_A05_t02
co19/LibTest/ffi/Struct/Struct_A05_t03
co19/LibTest/ffi/Struct/Struct_A05_t04
co19/LibTest/ffi/Struct/Struct_A05_t05
co19/LibTest/ffi/Struct/Struct_A05_t06
co19/LibTest/ffi/Struct/Struct_A05_t07
co19/LibTest/ffi/Struct/Struct_A05_t08
co19/LibTest/ffi/Uint16/Uint16_A01_t01
co19/LibTest/ffi/Uint16/Uint16_A01_t02
co19/LibTest/ffi/Uint16/Uint16_A02_t01
co19/LibTest/ffi/Uint32/Uint32_A01_t01
co19/LibTest/ffi/Uint32/Uint32_A01_t02
co19/LibTest/ffi/Uint32/Uint32_A02_t01
co19/LibTest/ffi/Uint64/Uint64_A01_t01
co19/LibTest/ffi/Uint64/Uint64_A02_t01
co19/LibTest/ffi/Uint8/Uint8_A01_t01
co19/LibTest/ffi/Uint8/Uint8_A01_t02
co19/LibTest/ffi/Uint8/Uint8_A02_t01

A log is:
stderr:
Simulator hit Unimplemented instruction: at 0x5563a68e78e0, last_pc=0x7f68a8306624

0x5563a68e78e0    e5894855               unknown
sim> ../../runtime/vm/simulator_arm64.cc: 479: error: ReadLine failed
version=2.13.0-edge.55766c387a3f5bd82cfff4fe9b5fb90babca3d30 (be) (Mon Feb 22 11:17:48 2021 +0000) on "linux_simarm64"
pid=29245, thread=29256, isolate_group=main(0x5563a87ae300), isolate=main(0x5563a8e06300)
isolate_instructions=5563a61ac8e0, vm_instructions=5563a61ac8e0
  pc 0x00005563a6427dbc fp 0x00007f68a67fe340 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x00005563a61aca92 fp 0x00007f68a67fe420 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x00005563a6493c3c fp 0x00007f68a67fe6e0 dart::SimulatorDebugger::Debug()+0xb5c
  pc 0x00005563a64954b8 fp 0x00007f68a67fe7a0 dart::Simulator::UnimplementedInstruction(dart::Instr*)+0x48

**Comment by dcharkes** [comment]
FFI is not supported on simulators. So all the test can be skipped there.
