### ISSUE TITLE
[CP][beta channel] Fix analytics preferences not being saved

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#45079]
**commit(s) to merge**: 410f242ebc1efd81cf800ada54f5311e6f895c58

**merge instructions**: Clean merge

**What is the issue**: analytics preferences were not being respected by the CLI if `--analytics` or `--no-analytics` were not explicitly provided.

**What is the fix**: Ensure `false` is passed as a default for `disableAnalytics` if `--analytics` or `--no-analytics` aren't provided.

**Why cherrypick**: Without this fix users have no way to control Dart CLI analytics.

**Risk**: Low

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/45077

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
cc: @pcsosinski

**Comment by vsmenon** [comment]
lgtm

**Comment by pcsosinski** [comment]
lgtm

**Comment by franklinyow** [comment]
Reviewed online, mark as approved

**Comment by whesse** [comment]
Cherry-picked in beta 2.12.0-259.16.beta.
Beta currently being built.
