### ISSUE TITLE
Analyzer missing compile-time error on two new co19 tests

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#45076]
Two new co19 tests are reporting a missing compile-time error on analyzer:
co19/LibTest/ffi/sizeOf/sizeOf_A01_t03
co19/LibTest/ffi/Struct/Struct_A02_t01

The logs are
/=================================================================================================================================\
| analyzer-asserts-strong-linux:co19/LibTest/ffi/Struct/Struct_A02_t01 is new and failed (MissingCompileTimeError, expected Pass) |
\=================================================================================================================================/

--- Command "dart2analyzer" (took 32ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=machine --no-hints /b/s/w/ir/cache/builder/sdk/tests/co19/src/LibTest/ffi/Struct/Struct_A02_t01.dart

static error failures:
Missing static error at line 27, column 15, length 2:
- Expected unspecified analyzer error.
- Expected unspecified CFE error.

--- Re-run this test:
python tools/test.py -n analyzer-asserts-strong-linux co19/LibTest/ffi/Struct/Struct_A02_t01

/=================================================================================================================================\
| analyzer-asserts-strong-linux:co19/LibTest/ffi/sizeOf/sizeOf_A01_t03 is new and failed (MissingCompileTimeError, expected Pass) |
\=================================================================================================================================/

--- Command "dart2analyzer" (took 94ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=machine --no-hints /b/s/w/ir/cache/builder/sdk/tests/co19/src/LibTest/ffi/sizeOf/sizeOf_A01_t03.dart

static error failures:
Missing static error at line 18, column 3, length 16:
- Expected unspecified analyzer error.
- Expected unspecified CFE error.

--- Re-run this test:
python tools/test.py -n analyzer-asserts-strong-linux co19/LibTest/ffi/sizeOf/sizeOf_A01_t03

**Comment by sgrekhov** [comment]
co19/LibTest/ffi/sizeOf/sizeOf_A01_t03 - #45100
co19/LibTest/ffi/Struct/Struct_A02_t01 - #44987
Closing this issue
