### ISSUE TITLE
triple-shift co19 tests failing on ia32

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#45074]
The triple-shift tests changed from compile-time error to runtime error on the ia32 architectures, saying "not implemented yet"

The tests
co19/LanguageFeatures/nnbd/triple-shift/local_variable_read_A01_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/triple-shift/local_variable_read_A02_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/triple-shift/null_aware_operator_A09_t12 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/triple-shift/null_aware_operator_A11_t12 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/triple-shift/null_aware_operator_A13_t12 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/triple-shift/null_aware_operator_A15_t12 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/triple-shift/local_variable_read_A01_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/triple-shift/local_variable_read_A02_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/triple-shift/null_aware_operator_A09_t12 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/triple-shift/null_aware_operator_A11_t12 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/triple-shift/null_aware_operator_A13_t12 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/triple-shift/null_aware_operator_A15_t12 RuntimeError (expected Pass)
co19/Language/Expressions/Shift/integer_t04/01
co19/Language/Expressions/Shift/integer_t04/02
co19/Language/Expressions/Shift/integer_t04/03
co19/Language/Expressions/Shift/integer_t04/04
co19/Language/Expressions/Shift/integer_t04/05
co19/Language/Expressions/Shift/integer_t04/06
co19/Language/Expressions/Shift/integer_t04/07

on configurations
dartk-strong-linux-debug-ia32
dartk-weak-asserts-linux-debug-ia32

are failing with errors like

stderr:
Unhandled exception:
UnimplementedError: int.>>> is not implemented yet
#0      int.>>> (dart:core-patch/integers.dart:110:5)
#1      main (file:///b/s/w/ir/out/DebugIA32/generated_tests/co19/Language/Expressions/Shift/integer_t04_01.dart:19:17)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python tools/test.py -n dartk-strong-linux-debug-ia32 co19/Language/Expressions/Shift/integer_t04/01

**Comment by alexmarkov** [comment]
That's an expected improvement in behavior after I added `operator >>>` to `int` class. That operator is not implemented yet, hence run-time error.

**Comment by alexmarkov** [comment]
Duplicate to https://github.com/dart-lang/sdk/issues/30892.
