### ISSUE TITLE
TransitionToGenerated not handling all cases

### ISSUE THREAD

**Issue by wqyfavor** [dart-lang/sdk#45087]
This tracker is for issues related to:
* Dart VM

In my project, I use Dart API to interact with VM and generated AOT code. But in some cases the App is crashing with message:

../../third_party/dart/runtime/vm/symbols.cc: 644: error: expected: group->safepoint_handler()->IsOwnedByTheThread(thread)

I figured out the reason is that the thread is at "Safepoint" status when running AOT code.

The following code is responsible for this issue.
https://github.com/dart-lang/sdk/blob/master/runtime/vm/heap/safepoint.h#L346

```
class TransitionToGenerated : public TransitionSafepointState {
 public:
  explicit TransitionToGenerated(Thread* T)
      : TransitionSafepointState(T), execution_state_(T->execution_state()) {
    ASSERT(T == Thread::Current());
    ASSERT((execution_state_ == Thread::kThreadInVM) ||
           (execution_state_ == Thread::kThreadInNative));
    if (execution_state_ == Thread::kThreadInNative) {
      T->ExitSafepoint();
    }
    T->set_execution_state(Thread::kThreadInGenerated);
  }

```
I think when going back to 'Generated', thread should always exit safepoint. Is that right?
But why ASSERT is using condition `Thread::kThreadInVM || Thread::kThreadInNative)`, while `ExitSafepoint` is only called when `execution_state_ == Thread::kThreadInNative`.

**Comment by wqyfavor** [comment]
@mraleph

**Comment by mraleph** [comment]
When you are in `Thread::kThreadInVM` state you are not at safepoint (with the exception of the case when you are the thread that asked all other threads to safepoint), hence no need to exit safepoint. We should not ever call generated code from `kThreadInVM` state while also holding safepoint - this sounds like a recipe for disaster.

Are you by chance trying to call back into the Dart code from a weak handle finaliser or something like that? That's not allowed. You can only use C/C++ code there. 

Do you have a full stack trace for the crash? The comment in `symbols.cc` indicates that calling that function at safepoint should be rather uncommon occurrence (which makes sense).

**Comment by wqyfavor** [comment]
That's my problem. I implemented a new RUNTIME_ENTRY and in this entry function I did my logic of Dart API calls.

 After adding TransitionVMToNative, everything works fine.

Thanks a lot.
