### ISSUE TITLE
length incorrect error

### ISSUE THREAD

**Issue by aitch-3** [dart-lang/sdk#45109]
Below code snippet demonstrates list length error.

Length does not update as data added to List.

if `List<int> a;` is initialized as `List<int> a = []` then the length gets updated.

```
List<int> a;


void init() {
  a = List.filled(100, 0, growable: true);
}

void calc() {
  print('--checkpoint1---');
  print(a.length);
  
  a.add(3);
  
  print('--checkpoint2---');
  print(a.length);
  print('');
  print('');
}


void main() {
  init();
  calc();
}
```

**Comment by mit-mit** [comment]
Not repro with the information provided.

**Comment by mateusfccp** [comment]
@mit-mit It's very reproducible in the Dartpad link I posted above: https://dartpad.dev/c434787216848a7dfa5aebeb71375f1e

<img width="916" alt="image" src="https://user-images.githubusercontent.com/4605213/109152101-cd8fbf80-7749-11eb-94c0-254f971eb66c.png">

**Comment by mit-mit** [comment]
It does seem reproducible, but only if one toggles the "Null safety" toggle at the bottom to off. I cannot reproduce in neither the Dart VM JIT or AOT modes.

I wonder if this was a dart2js issue in older builds. When null safety is off, DartPad uses `Dart SDK 2.10.4`.

**Comment by mit-mit** [comment]
cc @sigmundch

**Comment by rakudrama** [comment]
ec4ccb7051bffbf8c24adfd2031b92fe913849ad says "Fixes a bug where it was assumed that List.filled was always fixed length."
The code is not in the 2.10.4 tree, so 2.10.4 would have the bug.
