### ISSUE TITLE
Renaming a variable to match a named constructor being called incorrectly reports constructor will be shadowed

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45105]
Given the following:

```dart
class Foo {
  Foo.now();
}

test() {
  final foo = Foo.now(); // rename "foo" here to "now"
}
```

Renaming the variable `foo` to `now` reports:

> Usage of constructor "Foo.now" declared in "test.dart" will be shadowed by renamed local variable.

This is not correct as the call to the constructor is prefixed with the class name.

The message is coming from `visitSimpleIdentifier` [here](https://github.com/dart-lang/sdk/blob/d63d5d93a59b370bf5f5c277109110cb67a96b75/pkg/analysis_server/lib/src/services/refactoring/rename_local.dart#L135-L147).

@bwilkerson that code has a check for `isQualified` but it returns `false` for this node, although the description of `isQualified` says:

>   Return `true` if this identifier is the "name" part of a prefixed identifier or a method invocation.

Is it correct that this is `false` for the constructor name?

**Comment by bwilkerson** [comment]
> Is it correct that this is `false` for the constructor name?

I believe that it's a bug that `isQualified` returns `false` when the identifier is the `name` in a constructor name.
