### ISSUE TITLE
Migration tool panes should be resizable

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#45110]
Using the  existing `/*?*/` and `/*!*/` buttons are harder to use than necessary because the buttons to add a hint to the current site are at the *bottom* of the Edit Details pane, so in many cases, I need to scroll past the various nullability reasons to add a hint for the current site.  It would be nice if the panes at least were resizable to reduce the need for scrolling much of the time.

(Moving the hint buttons for the current location to the top of the Edit Pane also would help, as would [adding keyboard shortcuts](https://github.com/dart-lang/sdk/issues/45066).)

Dart SDK version: 2.13.359222839-edge+google3-v2 (google3) (google3) on "linux_x64"

**Comment by mit-mit** [comment]
cc @stereotype441

**Comment by jamesderlin** [comment]
I seriously doubt that any further work will ever be done on `dart migrate` since it's been removed in Dart 3.
