### ISSUE TITLE
LibTest/isolate/Isolate/ping_A03_t01, t02 are failing due to ping message racing isolate startup message

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45111]
From https://dart-ci.appspot.com/log/any/dartkp-strong-linux-debug-x64/142/co19/LibTest/isolate/Isolate/ping_A03_t01
```
Unhandled exception:
Expect.equals(expected: <timeout>, actual: <null>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:20)
#1      Expect.equals (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:30)
#2      test (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/ping_A03_t01.dart:61)
<asynchronous suspension>
```

and from [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8854451138417650288/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0)
```
--- Command "vm" (took 03.000706s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/ping_A03_t02.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <timeout>, actual: <null>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:20:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:30:5)
#2      test (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/ping_A03_t02.dart:65:12)
<asynchronous suspension>

--- Re-run this test:
python tools/test.py -n dartk-strong-linux-debug-x64 co19/LibTest/isolate/Isolate/ping_A03_t02
```

The culprit is that `ping` message races with isolate startup message, ends up being processed even if it should not(due to tight loop in worker isolate body).

Similar issue should affect `kill` messages. Raised https://github.com/dart-lang/co19/issues/1003 to have such a test built up.

**Comment by mkustermann** [comment]
I've filed https://github.com/dart-lang/co19/issues/1095 with the underlying problem, which seems to have been fixed.

There is no guarantee that no other messages can be received by an isolate before the `entrypoint` is invoked. In fact, it is intentional to delay the invocation of the `entrypoing` by enqueuing it's invocation in the message loop (which might already contain some messages (e.g. `ping`) at that point in time), see [sdk/lib/_internal/vm/lib/isolate_patch.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/isolate_patch.dart#L247)

```dart
@pragma("vm:entry-point", "call")
void _startMainIsolate(Function entryPoint, List<String> args) { 
  _delayEntrypointInvocation(entryPoint, args, null, true);
}
```

**Comment by aam** [comment]
>  (which might already contain some messages (e.g. `ping`)

I understand it's current behavior of the vm, I am surprised it is deemed correct.
I think developer-originated(ping/kill) messages to an isolate should not race with isolate startup messages as startup mechanism is internal to the vm, not visible to the developer.

**Comment by dcharkes** [comment]
https://github.com/dart-lang/sdk/issues/46541 started crashing again:

https://dart-ci.appspot.com/log/vm-kernel-precomp-nnbd-win-release-x64/dartkp-strong-win-release-x64/263/co19/LibTest/isolate/Isolate/kill_A01_t04

**Comment by aam** [comment]
Tests were updated to reflect current behavior, unlikely to be revisited
