### ISSUE TITLE
InconsistentAnalysisException: always with an annotated enum value + source_gen + json_serializable

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#45127]
```
enum StatusCode {
  @JsonValue(200)
  success,
}
```

It only happens in build for json_serializable.

It starts with an annotation that has a `null` element.

* Sync https://github.com/google/json_serializable.dart/
* cd `json_serializable`
* `pub upgrade`
* `pub run build_runner watch --verbose --delete-conflicting-outputs`
* If you don't get the error right away, go edit a file – like 'example/example.dart` – just enough to make build kick off

If you want a process to attach to – once the first build is ran

`dart .dart_tool/build/entrypoint/build.dart watch --verbose --delete-conflicting-outputs`

**Comment by srawlins** [comment]
Is there any stacktrace? Still digging?

**Comment by kevmoo** [comment]
```
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

package:analyzer/src/dart/analysis/session.dart 145:7      AnalysisSessionImpl._checkConsistency
package:analyzer/src/dart/analysis/session.dart 92:5       AnalysisSessionImpl.getParsedLibraryByElement
package:source_gen/src/type_checker.dart 297:10            UnresolvedAnnotationException._findSpan
package:source_gen/src/type_checker.dart 316:24            new UnresolvedAnnotationException._from
package:source_gen/src/type_checker.dart 107:43            TypeChecker._computeConstantValue
package:source_gen/src/type_checker.dart 132:21            TypeChecker._annotationsWhere.sync_op
dart:core                                                  Iterable.isEmpty
package:source_gen/src/type_checker.dart 87:20             TypeChecker.firstAnnotationOfExact
package:json_serializable/src/utils.dart 148:34            _getAnnotationOfElement
package:json_serializable/src/utils.dart 165:24            enumFieldsMap._generateEntry
dart:core                                                  new Map.fromEntries
package:json_serializable/src/utils.dart 193:9             enumFieldsMap
package:json_serializable/src/utils.dart 205:5             iterateEnumFields
package:json_serializable/src/json_key_utils.dart 122:11   _from._annotationValue
package:json_serializable/src/json_key_utils.dart 177:35   _from
package:json_serializable/src/json_key_utils.dart 18:32    jsonKeyForField
package:json_serializable/src/helper_core.dart 51:45       HelperCore.jsonKeyFor
package:json_serializable/src/generator_helper.dart 71:20  GeneratorHelper.generate.sync_op.<fn>
dart:collection                                            ListMixin.fold
package:json_serializable/src/generator_helper.dart 61:43  GeneratorHelper.generate.sync_op

```

This is secondary, though. The primary issue is that I cannot commute the value of the annotation.

then `source_gen` goes off and tries to create a helpful error, which leads to this stack

**Comment by gustavogamino** [comment]
Hey @kevmoo, I am getting the same error intermittently. 

I've opened an issue [google/json_serializable.dart#847](https://github.com/google/json_serializable.dart/issues/847#issue-838355535) with all the information you've asked. There is also an example that usually fails after a few tries. Let me know if that works on your side too.

**Comment by kevmoo** [comment]
@gustavogamino – I'm escalating w/ the analyzer folks. Thanks!

**Comment by scheglov** [comment]
I can reproduce it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/192763

**Comment by scheglov** [comment]
CL to publish `analyzer 1.3.0`, probably will land tomorrow.
https://dart-review.googlesource.com/c/sdk/+/192862

**Comment by scheglov** [comment]
Published.
