### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by deafjava** [dart-lang/sdk#45123]
## Version information

- `IDEA IC-203.7148.57`
- `2.10.5`
- `IC-203.7148.57, JRE 11.0.9.1+11-b1145.77x64 JetBrains s.r.o., OS Mac OS X(x86_64) v10.16, screens 1920.0x1080.0, 3360.0x2100.0  Retina`

**Comment by parlough** [comment]
Thanks for the report! Do you have any more information about the issue you faced? Such as a log or an explanation of what failed to happen?
