### ISSUE TITLE
Migration tool incorrectly assumes that a type parameter to a generic is non-nullable

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#45129]
Try to migrate the following code:

```dart
bool isNull<T>(T x) {
  if (x == null) { // Migration tool claims this condition is always false.
    return true;
  } else {
    return false;
  }
}

void main() {
  print(isNull<int>(null)); // Migration tool changes `int` to `int?`
  print(isNull<int>(42)); 
}
```
The migration tool reports:

> line 2: Condition will always be false in strong checking mode

That seems wrong since `T` can be a nullable type (and the migration tool even suggests using `int?` for `T`).

**Dart SDK version**: 2.12.0-133.7.beta

**Comment by leafpetersen** [comment]
cc @stereotype441 @srawlins

**Comment by stereotype441** [comment]
Thanks for the report @jamesderlin!  I'm classifying this bug as P2 because I believe it doesn't affect the accuracy of the final migrated code.  But it's definitely likely to confuse people so I'll try to look at it soon.

**Comment by jamesderlin** [comment]
Yeah, thankfully the migration tool doesn't actually remove the condition when the migration is applied, but people might follow its advice and remove the condition manually, which could result in a change to runtime behavior.

**Comment by stereotype441** [comment]
> Yeah, thankfully the migration tool doesn't actually remove the condition when the migration is applied, but people might follow its advice and remove the condition manually, which could result in a change to runtime behavior.

Agreed, there's a big footgun here.
