### ISSUE TITLE
No published analyzer available for language version 2.13.0"

### ISSUE THREAD

**Issue by wenbo-ya** [dart-lang/sdk#45130]
[WARNING] json_serializable:json_serializable on lib/http/rest_client.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.12.0
SDK language version: 2.13.0

**Comment by mit-mit** [comment]
@wenbo-ya can you please update the bug description (which currently is 100% template text)?

**Comment by mit-mit** [comment]
@bwilkerson have we published an analyzer compatible with Dart 2.13.x?

**Comment by devoncarew** [comment]
@mit-mit - these messages are automatically kicked out by package build, are super noisy, and are not de-duped. I've been triaging them to the `area-build` area.

**Comment by srawlins** [comment]
Analyzer 1.0.0 understands the current language version to be 2.13.0:

```none
$ grep -rn " _currentVersion = '2" ~/.pub-cache/hosted/pub.dartlang.org/analyzer-1.0.0
/Users/srawlins/.pub-cache/hosted/pub.dartlang.org/analyzer-1.0.0/lib/src/dart/analysis/experiments.g.dart:11:const _currentVersion = '2.13.0';
```
