### ISSUE TITLE
False positive from import_deferred_library_with_load_function

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#45141]
Given a file `a.dart` containing
```
void loadLibrary(Library library) {}

class Library {}
```
and a second file containing
```
import 'a.dart' deferred as a hide loadLibrary;

void f() {
  a.Library();
}
```
the analyzer produces a HintCode.import_deferred_library_with_load_function diagnostic. The function from the imported library is hidden, so there is no conflict.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/189320
