### ISSUE TITLE
Incorrect indentation of multiline code completions in LSP

### ISSUE THREAD

**Issue by iamcco** [dart-lang/sdk#45147]
This tracker is for issues related to:

* Analyzer

Dart sdk version and system:

* Dart SDK Version (`dart --version`): `Dart SDK version: 2.12.0-259.12.beta (beta) (Fri Feb 12 11:00:34 2021 +0100) on "macos_x64"`
* MacOSX: 10.15.7 

**Describe the bug**

in the following code, if I type setState the completed code inserts the number of spaces that exist before the cursor, in this example there are six spaces which are inserted after what I believe would be the correct indentation
space represented by ˽
extra space represented by ˟
```
Widget _createInput() {
  return TextField(
    textCapitalization: TextCapitalization.sentences,
    decoration: InputDecoration(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(20),
      ),
      labelText: 'Name',
    ),
    onChanged: (value) {
˽˽˽˽˽˽setState(() {
˽˽˽˽˽˽˽˽˟˟˟˟˟˟
˽˽˽˽˽˽˟˟˟˟˟˟});
    }
  );
}

```
**Expected behavior**
```
˽˽˽˽˽˽setState(() {
˽˽˽˽˽˽˽˽
˽˽˽˽˽˽});
```

**Output channel:**

Log:

```
    {
        "label": "setState(() {});",
        "kind": 2,
        "tags": [],
        "detail": "(void Function() fn) → void",
        "documentation": {
            "kind": "markdown",
            "value": "..."
        },
        "sortText": "999627",
        "filterText": "setState(() {\n        \n      });",
        "insertText": "setState(() {\n        ${1:}\n      \\});",
        "insertTextFormat": 2,
        "textEdit": {
            "range": {
                "start": {
                    "line": 58,
                    "character": 6
                },
                "end": {
                    "line": 58,
                    "character": 7
                }
            },
            "newText": "setState(() {\n        ${1:}\n      \\});"
        }
    },

```

Dart language server should not add the extra indentation for snippets.

refer issue https://github.com/iamcco/coc-flutter/issues/95

**Comment by Kavantix** [comment]
Just to put some extra info here:
This issue is about the lsp version of the analyzer and impacts *both the vim extension and vscode*.
Also the fix is not to remove all the indentation but just the indentation that goes to where `setState` starts.
So the fix is to instead make the `newText` and the `insertText` be:
```
"setState(() {\n  ${1}\n});"
```

**Comment by scheglov** [comment]
FWIW, it works fine in IntelliJ.

The snippet `setState(() {\n        ${1:}\n      \\});` looks correct to me. We start `setState(() {\n`, then insert necessary count of spaces and put the caret mark `        ${1:}\n`, then again necessary number of spaces and close the invocation `      \\});`.

I suspect that the issue is related to the way VS Code or Vim process the snippet. If they add automatic indentation, I can see why "extra" spaces cause the issue. @DanTup

**Comment by DanTup** [comment]
Yep, VS Code (and presumably other editors building on top of LSP to match) re-indent the code assuming the servers did not already indent it correctly (they add the current indent level to each line).

The latest version of VS Code has a flag we can use to inform the client the indenting is already done (`insertTextMode` in https://microsoft.github.io/language-server-protocol/specifications/specification-current/). I thought I'd added this recently, though can't see it in the code, so I'll use this issue to track fixing it.

**Comment by DanTup** [comment]
Btw - if you're seeing it an editor other than VS Code, that editors LSP client will also need to add support for `InsertTextMode.asIs` and advertise it in the `textDocument.completion.insertTextMode` client capability.

**Comment by cncsl** [comment]
> Btw - if you're seeing it an editor other than VS Code, that editors LSP client will also need to add support for `InsertTextMode.asIs` and advertise it in the `textDocument.completion.insertTextMode` client capability in order for the fix to work once implemented here.

hello @DanTup , I'm trying to fix this incorrect indentation problem and found this issue. I don't know how to "advertise it in the textDocument.completion.insertTextMode client capability." I tried a few possible solutions, but none of them worked for me. Can you provide more details? (I'm using nvim-lspconfig https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#dartls)

**Comment by DanTup** [comment]
@cncsl I'm not very familiar with neovim, but you would need to advertise this in _capabilities_. There are some language servers in the nvim config that mention capabilities, such as here:

https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#helm_ls

At a guess, I'd say that `default_config` in https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/dartls.lua maybe could contain something like (I don't know if this is valid, but you should get the idea):

```
    capabilities = {
      textDocument = {
        completion = {
          insertTextModeSupport: {
            valueSet: [1, 2], // asIs, adjustIndentation
          }
        },
      },
    },
```

However, advertising this support is only half the job, the editor needs to actually support `asIs` as an option too (and if it did, then it should probably be advertised in the global default capabilities and not language-specific ones).

It's not clear to me if neovim does support this (or even if it's necessary - does it also adjust whitespace by default? I thought that was an odd choice on VS Code's part.

**Comment by cncsl** [comment]
> @cncsl I'm not very familiar with neovim, but you would need to advertise this in _capabilities_. There are some language servers in the nvim config that mention capabilities, such as here:
> 
> https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#helm_ls
> 
> At a guess, I'd say that `default_config` in https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/dartls.lua maybe could contain something like (I don't know if this is valid, but you should get the idea):
> 
> ```
>     capabilities = {
>       textDocument = {
>         completion = {
>           insertTextModeSupport: {
>             valueSet: [1, 2], // asIs, adjustIndentation
>           }
>         },
>       },
>     },
> ```
> 
> However, advertising this support is only half the job, the editor needs to actually support `asIs` as an option too (and if it did, then it should probably be advertised in the global default capabilities and not language-specific ones).
> 
> It's not clear to me if neovim does support this (or even if it's necessary - does it also adjust whitespace by default? I thought that was an odd choice on VS Code's part.

thx for reply, let me try.
