### ISSUE TITLE
Running dart build in Windows Subsystem for Linux (WSL) compiles Windows binaries. 

### ISSUE THREAD

**Issue by parkeradam** [dart-lang/sdk#45146]
Issue with tool
* dart2native

Dart SDK Version : I have included output from terminal when using dart verison in both Windows and WSL
```
PS C:\Users\mrpar> dart --version
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "windows_x64"
PS C:\Users\mrpar> wsl
test@DESKTOP-9FDE8EJ:/mnt/c/Users/mrpar$ dart --version
Dart SDK version: 2.10.5 (stable) (Unknown timestamp) on "linux_x64"
test@DESKTOP-9FDE8EJ:/mnt/c/Users/mrpar$
```

Both of these dart installations have been installed using the Windows/Linux installations on the dart SDK website. 

the output of `which dart` command in WSL is `/usr/bin/dart`

Having created a new console-simple app using stagehand (stagehand console-simple) i navigated to this folder in WSL.
While in WSL , I tried to use dart2native to produce a Linux Binary  using the command
`dart2native bin/main.dart`

The output was 
`Generated: /mnt/c/Users/mrpar/Desktop/Test/bin/Test.exe`

I would've expected the toolchain to compile to a native Linux x86-64 executable. Instead it has produced a Windows .exe file. 

I am using Windows 10 build 19042 with a newly activated WSL, Ubuntu-20.04 in WSL . 

Unsure if this is a bug or expected outcome and was hoping to shed some light as it would be great to be able to compile down and deploy apps pre-compiled to my Linux environments.

**Comment by julemand101** [comment]
The `.exe` extension is the default for all platforms when compiling Dart programs to native using dart2native. So you cannot just look at the extension and conclude it is a Windows binary. See also this issue where another person thought the .exe file was not OSX binary compatible: https://github.com/dart-lang/sdk/issues/44891

Yes, is is confusing and unexpected behavior. You can use the `-o` option to give a name of the compiled program.

**Comment by parkeradam** [comment]
@julemand101 Thank you very much for explaining this. Makes a lot more sense. Seems a bit of odd behviour. Do you know of there are any plans to update this so it outputs the different file extensions accordingly or not?

**Comment by julemand101** [comment]
@parkeradam 
I don't think there are any plans for changing this behavior since it would be a breaking change as it also stated in https://github.com/dart-lang/sdk/issues/44891. Personally, I cannot say this problem is big enough for me for introducing a breaking change for other people. But it would be a nice change for fixing the usability issue since multiple people does think the `dart2native` always generate Windows binaries. :)
