### ISSUE TITLE
[CP][stable channel] Fix null-safety issue in VM's typed-data + operators.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#45156]
**commit(s) to merge**: eb6b474d7a8c0d34b536a803f9752b9429629259 

**merge instructions**: clean merge

**What is the issue**: VM typed_data. The typed data list `+` operator did not work.

**What is the fix**: Fixes bug in null safety migration of VM typed_data. The typed data list `+` operator did not work.
See issue #45140.

**Why cherrypick**: It's a broken feature in the platform libraries. Any code which uses the feature will crash at run-time. 
There is likely not much code which uses the feature, since we haven't discovered the bug earlier, but at least one user 
has hit it.

**Risk**: Low

**Link to original  issue(s)**: #45140 

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

@whesse

**Comment by athomas** [comment]
@franklinyow @mit-mit

**Comment by franklinyow** [comment]
@lrhn I switched out to the current version of template.  Can you add a line for the **Why cherrypick** section?

**Comment by franklinyow** [comment]
The early consensus from offline chat is that this is not very urgent.

**Comment by franklinyow** [comment]
@mraleph
FYI: @kf6gpe @pcsosinski

**Comment by kevmoo** [comment]
Is this a known regression from 2.10? Seems a reasonable thing to queue up for a dot-1 release

**Comment by franklinyow** [comment]
ping:  @vsmenon @a-siva @mit-mit

**Comment by a-siva** [comment]
lgtm

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Hot fixed approved.

Text description:  This fix a bug in the VM typed_data operator that result in runtime crash, see issue #45140.

**Comment by franklinyow** [comment]
Hot fix 2.12.1
