### ISSUE TITLE
LSP server provides bad filterText for @override completions

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45157]
Given the following code:

```
abstract class Person {
  String get name;
}

class Student extends Person {
  nam// complete here
}
```

The completion for the name override has bad `filterText` which includes everything that will be inserted:

```js
{
	"label": "name => …",
	"kind": 10,
	"tags": [],
	"detail": "String",
	"sortText": "999250",

        // This is not ideal
	"filterText": "@override\n  // TODO: implement name\n  String get name => throw UnimplementedError();",

	"insertText": "@override\n  // TODO: implement name\n  String get name => ${0:throw UnimplementedError()};",
	"insertTextFormat": 2,
	"textEdit": {
		"newText": "@override\n  // TODO: implement name\n  String get name => ${0:throw UnimplementedError()};",
		// snip
	}
},
```

This can result in bad ranking in VS Code, as `filterText` is being (not the label) to decide how relevant something is:

![Screenshot 2021-03-02 at 15 28 41](https://user-images.githubusercontent.com/1078012/109672184-af242c80-7b6c-11eb-85b3-757e3dcf83d5.png)

**Comment by bwilkerson** [comment]
Is this something we can (and should) fix in the lsp layer, or should we compute the filter text as part of building the suggestion? I could imagine having a similar issue in the following case
```
import 'dart:io' as io;

void f(F^) {}
```
where we're going to suggest `io.File`. If that kind of completion is also a problem, then that might argue that we need to compute the filter text when we still have some semantic information.

**Comment by DanTup** [comment]
I would expect the `filterText` to generally be the same as the visible label (although in the LSP layer we do truncate it on some characters like `(` so if we showed `print(Foo foo)` we wouldn't start match on `foo`).

In the case above, if the displayed label is only `File` then I would expect the filter text to match, and if the label is `io.File` I would expect it to match there. I think the user assumes that what they see is what's being filtered, so including anything they _don't_ see could be confusing (it leads to issues like this, or the opposite - where something might rank at the top because of some invisible text the user doesn't see).

I think this is just a simple bug (in the LSP mappings) where `insertText`/`filterText` are being computed similarly, but `filterText` should be more like the displayed label.
