### ISSUE TITLE
test.py incorrectly classifies crashes in tests with error expectations

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#45162]
Steps to repro:
- Download patchset 2 of https://dart-review.googlesource.com/c/sdk/+/188160 (this is some work in progress code of mine that triggers a compile error)
- Run `python tools/test.py -n cfe-strong-linux co19/LanguageFeatures/Set-literals/disambiguating_A01_t02` (this is a test that triggers the compile error)

In the output of this command we can see the stacktrace of the crash (which is good!), however before the stacktrace the tool outputs this:
```
FAILED: fasta-none release_x64 co19/LanguageFeatures/Set-literals/disambiguating_A01_t02
Expected: Pass
Actual: MissingCompileTimeError
```
This is wrong.  The failure isn't a missing compile time error; it's a crash.  This is a problem for two reasons:
- It makes the failure appear to be a non-crash in the dart-ci webapp (https://dart-ci.firebaseapp.com/cl/188160/2) which could cause someone to underestimate its severity.
- I worry that if the crash had happened later (after all the expected compile time errors were already reported) that this test might have been misclassified as passing.

**Comment by munificent** [comment]
FYI, I probably won't have much time to get to this until my IO talk is closer to being done. Is this urgent?
