### ISSUE TITLE
Customer-reported issue with NNBD migration tool

### ISSUE THREAD

**Issue by kevindmoore** [dart-lang/sdk#45187]
#### Steps to reproduce
Start migration tool. go to file with multiple changes. Click on line # to go to line.
Click on /*?*/ action

#### What did you expect to happen?
Be able to change the nullability of a field.

#### What actually happened?
Kept changing the first entry over and over
No way to undo

_Screenshots are appreciated_

**Dart SDK version**: 2.12.0

Thanks for filing!

**Comment by srawlins** [comment]
Thanks for filing an issue!

Can you point us to an example library which we can use to reproduce? Perhaps the pub package if you are referring to some open source code?

**Comment by kevindmoore** [comment]
You shouldn't need an example library. I only ran this on one project that
didn't have that many changes. The migration tool doesn't feel finished.
1. Why do you need to put in comments for a change?
2. Why does it keep adding multiple comments
3. Why can't you undo?
4. You should have a next/previous button
Thanks,
Kevin Moore

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
