### ISSUE TITLE
Inconsistent behavior of classes declared as class A = Object with Mixin

### ISSUE THREAD

**Issue by gaetschwartz** [dart-lang/sdk#45193]
## Background

I was playing with mixins and discovered that you could declare classes as objects with mixins like so : 

```dart
class Mixed = Object with N, M;
```
This syntax is pretty undocumented, I remember seeing a reference to it in a lint rule and that's how discovered it but that's it.

## The issue

You can use this newly created class we called `Mixed` as a mixin, and it works. Only there is an issue, this example doesn't run because for some reason the compiler says the class `A` declared as being mixed with `Mixed` has missing implementations even though it shouldn't (as far as I understand).

You can try this example here: https://dartpad.dev/97285babbffb11219b5298224c51e805?null_safety=true

```dart
void main() async {
  final a = A();
  print(a is N);
  print(a is M);
}

mixin M {
  int get number => 20;
}

mixin N {
  String get text => 'Foo';
}

class Mixed = Object with N, M;

class A with Mixed {}
```

Ran we get: 
```
bin/main.dart:17:7: Error: The non-abstract class 'A' is missing implementations for these members:
 - N.text
Try to either
 - provide an implementation,

 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class A with Mixed {}
      ^
bin/main.dart:12:14: Context: 'N.text' is defined here.
  String get text => 'Foo';

```

Dart version: `Dart SDK version: 2.13.0-77.0.dev (dev) (Thu Feb 25 00:41:11 2021 -0800) on "windows_x64"`

**Comment by mraleph** [comment]
Notably analyzer and CFE seem to behave differently on this one. Is this possibly a CFE bug?

/cc @eernstg

**Comment by eernstg** [comment]
Yes, this is a bug in both the analyzer and the CFE: The class `Mixed` has superclass `Object with N`, and hence it cannot be used to derive a mixin (so `Anything with Mixed` is an error).

The analyzer does not report this error at all, and the CFE reports an error that seems to indicate that it accepts the derivation of a mixin from `Mixed`, but it considers that mixin to be `N` (so we have `number`, but `text` is unimplemented because it is inherited from the superclass of `Mixed`).

**Comment by mraleph** [comment]
You are not really combining mixins in this example, because you fully override the implementation. If so, this would work: 

```dart
class A {}
class B {}
class MyClass implements A, B {
}
```

**Comment by gaetschwartz** [comment]
@mraleph Obviously, but it allows some nice syntax to specify MyClass's methods. Doing `MyClass with AB` allows us to know it is both an `A` and a `B`. If I now had a `MySecondClass with AB`, I could write 👍🏻 
```dart
final AB ab = MyClass();
final AB ab2 = MySecondClass();
```

**Comment by mraleph** [comment]
You can also do: 

```
abstract class AB implements A, B { }
class MyClass implements AB { }
```

**Comment by eernstg** [comment]
@gaetschwartz, mixin composition is not available in Dart, but&mdash;as @mraleph mentioned&mdash;you can compose interfaces. An interface is a set of member signatures that a class must implement, it doesn't include any implementations at all.

Mixin composition as a language feature was proposed in https://github.com/dart-lang/language/issues/541. You might want to contribute to the discussion there (and/or add a thumbs up if you wish to promote that idea).
