### ISSUE TITLE
[Analyzer] dart2: null check with IF statement

### ISSUE THREAD

**Issue by tcd93** [dart-lang/sdk#45190]
In Kotlin we can run this code without errors:
```kotlin
class Test(val d: (() -> String)?) {  
    fun print_d() {
        if (d != null) {
            println(d.invoke())
        }
    }
}
fun main() {
    Test({ "Hello" }).print_d();
}
```
The compiler knows that there was a null check on `d` before invoking, so it compiles

Similar code in Dart:
```dart
class Test {
  final String Function()? d;
  Test(this.d);

  void print_d() {
    if (d != null) {
      print(d.call());
    }
  }
}

void main() {
  Test(() => 'Hello').print_d();
}
```
The analyzer now complains although this code is safe
![image](https://user-images.githubusercontent.com/17901180/109928974-9c3e6300-7cf8-11eb-9286-2c7c9bc2e7fd.png)

```
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "windows_x64"
```

**Comment by SashaFarkas** [comment]
It would be great, if there would be a swift "if assignment":
```
if ((final a = A.a) != null) {
   print(a + 3); // non-nullable
}
```

**Comment by mit-mit** [comment]
Please see: https://dart.dev/guides/language/effective-dart/usage#consider-copying-a-nullable-field-to-a-local-variable-to-enable-type-promotion

cc @munificent for thoughts on a short-hand notation for promoting into a fresh variable.

**Comment by eernstg** [comment]
You may also be interested in various proposals [here](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion).

**Comment by mit-mit** [comment]
Thanks Erik. This is the one I had in mind: https://github.com/dart-lang/language/issues/1201

I'm going to close this issue. Let's continue the discussion in the language issues.
