### ISSUE TITLE
Can't find the migration command

### ISSUE THREAD

**Issue by chingpaq** [dart-lang/sdk#45199]
Im currently on Flutter version 2.0.0 on a Mac Pro on Catalina V10.15.7

flutter --version
Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (22 hours ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

Was trying to use migrate but when i checked its not on the list of available

![image](https://user-images.githubusercontent.com/4299333/109986680-ee0adb80-7d40-11eb-86bb-bd21c75b8fa1.png)

Nothing unusual in Flutter doctor

![image](https://user-images.githubusercontent.com/4299333/109986878-1d214d00-7d41-11eb-964e-7011094a7c94.png)

Can anyone help me on this? Thanks!

**Comment by bkonyi** [comment]
You're looking for `dart migrate` not `flutter migrate` :-)

**Comment by chingpaq** [comment]
Thanks bkonyi. That's an epic fail on my part =) Hands getting ahead faster than my eyes reading. Thanks again.
