### ISSUE TITLE
Confusing CFE error message on extension method invocation with too few arguments

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45204]
When an extension method is invoked with too few arguments, the error message emitted by the CFE claims that there are `n+1` missing arguments where `n` is the number of parameters of the method:

```dart
extension S on int {
  void test(int x) {}
}
void main() {
  3.test();
}
```

```
Error: Too few positional arguments: 2 required, 1 given.
  3.test();
```

**Comment by johnniwinther** [comment]
cc @stefantsov Can you look into this? We'll have similar problems wrt. extension types.
