### ISSUE TITLE
[vm/ffi] No compile error when Array<Pointer> is used

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#45200]
The following program produces no compile error nor in CFE nor in Analyzer
```dart
import "dart:ffi";

class MyStruct extends Struct {
  @Array(2)
  external Array<Pointer> a0;
}

void main() {
  final pointer = calloc<MyStruct>();
  try {
    final array = pointer.ref.a0;
    array[0];
  } finally {
    calloc.free(pointer);
  }
}
```
Here we have `Array<Pointer>` without specification of `Pointer` type. I don't think that `Array<Pointer<NativeType>>` is a valid type

`Dart SDK version: 2.13.0-edge.d901f7326a86cecf53ae312a31d2d435d3c773e5 (be) (Wed Mar 3 17:12:58 2021 +0000) on "linux_x64"`

**Comment by dcharkes** [comment]
This is working as intended. `Pointer` is defaulted to `Pointer<NativeType>` and is an underspecified `Pointer` allowing for generic programming.

It doesn't matter whether it's nested in an `Array` or not.

```dart
class MyStruct extends Struct {
  @Array(2)
  external Array<Pointer> a0;

  external Pointer a1;
}
```

Thanks for reporting @sgrekhov!
