### ISSUE TITLE
Dart migrate does not detect .dart files under dot folders

### ISSUE THREAD

**Issue by Stargator** [dart-lang/sdk#45205]
This tracker is for issues related to:

* dart migrate

* Dart SDK Version (`dart --version`): 2.12
* Whether you are using Windows, MacOSX, or Linux (if applicable) - > MaxOSX
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) -> N/A

Description:

https://github.com/exercism/dart has a folder structure where the example solution to a given problem are under a .meta/lib directory. This is due to recent architectural changes through Exercism.

The `dart migrate` tool is not detecting the dart file under .meta/lib and thus provides no analysis on the compatibility with null safety.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.

**Comment by Stargator** [comment]
Unfortunately, the repo in question has not been migrated to the latest Dart version due to the issue outlined above. I suppose we will just have to run tests and make sure nothing is broken. If this is still a blocking issue, I will an update here.
