### ISSUE TITLE
[migrate] Bad state: Unrelated types: double, List<E>

### ISSUE THREAD

**Issue by jifalops** [dart-lang/sdk#45206]
Ran into this while migrating from 2.11. Reproducible via https://github.com/jifalops/geomag/tree/c3d26f7c207ce0e5502e94ce4fabe61042ebfbc7

<details>
<summary>Bad state: Unrelated types: abstract class double extends num and abstract class List<E> implements EfficientLengthIterable<E></summary>
Bad state: Unrelated types: abstract class double extends num and abstract class List<E> implements EfficientLengthIterable<E> at offset 1740 in /home/jacob/code/geomag/lib/src/geomag.dart (z.sublist(1))

#0      DecoratedClassHierarchy.getDecoratedSupertype (package:nnbd_migration/src/decorated_class_hierarchy.dart:67:10)
#1      DecoratedClassHierarchy.asInstanceOf (package:nnbd_migration/src/decorated_class_hierarchy.dart:38:18)
#2      EdgeBuilder.getOrComputeElementType (package:nnbd_migration/src/edge_builder.dart:259:16)
#3      EdgeBuilder.visitMethodInvocation (package:nnbd_migration/src/edge_builder.dart:1284:20)
#4      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#6      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#7      EdgeBuilder._handleCollectionElement (package:nnbd_migration/src/edge_builder.dart:2436:14)
#8      ListMixin.forEach (dart:collection/list.dart:86:13)
#9      EdgeBuilder.visitListLiteral (package:nnbd_migration/src/edge_builder.dart:1224:21)
#10     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6757:49)
#11     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#12     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#13     EdgeBuilder.visitVariableDeclarationList (package:nnbd_migration/src/edge_builder.dart:1924:11)
#14     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10655:15)
#15     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#16     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#17     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#18     GeneralizingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:589:7)
#19     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10705:15)
#20     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#21     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#22     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#23     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#24     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#25     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#26     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#27     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#28     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#29     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#30     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#31     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2488:7)
#32     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#33     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#34     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#35     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#36     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#37     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#38     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#39     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#40     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#41     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#42     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#43     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#44     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#45     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#46     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#47     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#48     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#49     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#50     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#51     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#52     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#53     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#54     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#55     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#56     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#57     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
</details>

```
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "linux_x64"
```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
