### ISSUE TITLE
Dart Analyzer Diagnostic Message: unused_field weird warning message

### ISSUE THREAD

**Issue by umermasood** [dart-lang/sdk#45215]
* `Dart SDK version: 2.12.0 (stable)`
* Using Ubuntu Linux

I don't know if this is the right place to address this issue and I don't know if this isn't an issue at all but this is weird

```
class Foo {
  var _index = 0;
  void increment() {
    ++_index; // Using the variable like this gives me warning
    _index += 1; // Using the variable like this also gives me warning
    // _index = _index + 1; // This doesn't give me any warning
  }
}
```
Above snippet gives me this warning:
```
The value of the field '_index' isn't used.
Try removing the field, or using it. dart(unused_field) [2, 7]
```
 which doesn't make any sense because I am using the `_index` variable in my code

**Comment by bwilkerson** [comment]
This is working as intended.

The unused_field hint considers any private field whose value isn't being read for some purpose other than to compute a new value for the field to be unused. The purpose of the hint is to help you find bugs in your code and/or to help you identify dead code. In the snippet above, if you removed the field `_index` and all of the code that references it the semantics of your code would not change.
