### ISSUE TITLE
[cp][stable] Cherry-pick fix to secure socket connection unhandled exception

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45214]
Please cherry-pick https://dart.googlesource.com/sdk/+/ea3dfc9ac4617ad0346b515596636a1089ecc8a1 into stable.

This fixes "Bad state: Future already completed" unhandled exception that arises in cases when https connection attempt errors out or is aborted shortly after it started, before name resolution had a chance to complete. Original issue https://github.com/dart-lang/sdk/issues/45047.

The commit merges cleanly into stable.

/cc @mraleph @a-siva @franklinyow @vsmenon

**Comment by mraleph** [comment]
Note for CP approvers: the reason for requesting a cherry pick is because this can cause sporadic crashes on `pub` (most likely because `pub` speculatively fans out multiple concurrent requests and sometimes cancels them). Sporadic crashes when running `pub` is bad user experience.

**Comment by a-siva** [comment]
lgtm

**Comment by franklinyow** [comment]
Hot-fix approved.

Text: This fixes "Bad state: Future already completed" unhandled exception that when https connection attempt errors out, or is aborted shortly after it started, before name resolution had a chance to complete, see issue #45047.

**Comment by franklinyow** [comment]
Hot fix 2.12.1
