### ISSUE TITLE
Is it possible for me to depend on pkg:kernel or pkg:front_end without being a package in the SDK repo?

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#45231]
If I try to depend on these through either git dependencies it doesn't work due to relative paths and I can't seem to correct this with dependency overrides. Do I just have to develop my package embedded in my local checkout of the SDK or can I do something fancy with a package config?

**Comment by mraleph** [comment]
At the moment these packages are not meant for external consumption and are considered an implementation detail. So yeah if you want to write code using these packages you would have to be part of SDK.
