### ISSUE TITLE
dart analytics hangs when there's no internet in wsl2

### ISSUE THREAD

**Issue by jeiea** [dart-lang/sdk#45235]
## What I did
- Install archwsl (did not test other distro).
- Install flutter 2.0.1 by asdf-vm.
- Disconnect host internet by `ipconfig /release`.
- Execute any of `dart`, `dart pub outdated`, `dart pub upgrade`.

## Expected behavior
Normal behavior (help output) or at least error message.

## Actual behavior
No output, command does not finish.

## Additional context
```
✗ dart --version
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "linux_x64"
✗ uname -a
Linux DESKTOP-10AAD8A 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
```
After I executed `dart --disable-analytics`, `dart` command exited normally.

**Comment by bkonyi** [comment]
@sigurdm is it possible to add a timeout or network check when executing analytics code? What about pub?

**Comment by sigurdm** [comment]
Hmm - it should time out: https://github.com/dart-lang/sdk/blob/master/pkg/dartdev/lib/dartdev.dart#L254 .

I wonder what goes wrong.

@jonasfj any ideas?

**Comment by jonasfj** [comment]
hmm, if we're not cancelling the TCP connections, and we're not doing a force `exit(0)` from `dart:io`, then I suppose it could hang,

**Comment by sigurdm** [comment]
This should be fixed in the sdk master as of: https://dart-review.googlesource.com/c/sdk/+/192686
