### ISSUE TITLE
Add flutter's compute function

### ISSUE THREAD

**Issue by Ascenio** [dart-lang/sdk#45245]
This tracker is for issues related to:

* Analyzer
* Common Front End (CFE) and kernel
* **Dart core libraries ("dart:async", "dart:io", etc.)**
* Dart VM
* dart2js
* dev_compiler

Is there any reason flutter's [compute()](https://api.flutter.dev/flutter/foundation/compute.html) function isn't a part of dart's core libraries? It seems like the only dependency is Isolate, which is already a part of core.

**Comment by lrhn** [comment]
The `dart:isolate` library is only concerned with creating isolates and port communication. It's very much a low-level library. 
For higher level APIs, `package:isolate` provides some higher level abstractions.

For example, you can create an [IsolateRunner](https://pub.dev/documentation/isolate/latest/isolate.isolate_runner/IsolateRunner/spawn.html) and run commands in the created isolate. It doesn't (necessarily) create a new isolate per request, so you can improve performance by reusing isolates.

You can implement `compute` using it:
```dart
import "dart:isolate";

Future<R> compute<Q, R>(FutureOr<R> computation(Q argument), Q argument) {
  var runner = await IsolateRunner.spawn();
  try {
    return await runner.run(computation, argument);
  } finally {
    await runner.close();
  }
}
```

**Comment by Ascenio** [comment]
Sure. But as you can see it's a very simple function, I still think there's not a strong reason for it not being a part of core. It's not even high level.

My motivation is mostly simplicity, it would be very useful for libraries for example. Take a look at [image](https://pub.dev/packages/image#example)'s sample. It could be a lot more concise.

**Comment by Ascenio** [comment]
Sure, you have a good point. I would still like to have a function available. Anyway, thanks for your time.
