### ISSUE TITLE
When stable channel is updated, beta channel becomes outdated/older until next release

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/sdk#45243]
I noticed this after opening a PR to migrate one of our packages to NNBD. In doing so, the minimum Dart SDK constraint was updated to `>=2.12.0`. This works fine when running on either the stable or dev channel. But the latest release on the beta channel is still `2.12.0-259.16.beta`, which is `<2.12.0` and thus causes the CI run on the beta channel to fail the `pub get` step.

Presumably this will be fixed as soon as a new release is rolled out on the beta channel, but it doesn't make much sense to me to ever have a beta channel that is behind stable. Should the beta channel be updated with the same revision as stable as soon as stable is released so that this is avoided?

**Comment by athomas** [comment]
Often, pushing the latest stable to beta makes sense. The only exception would be if we publish a beta and then do a stable patch release (we don't want to rollback beta).

For 2.12.0, this should be resolved now so I'm closing that issue. I've also added it to our checklist for the next version bump.
