### ISSUE TITLE
Warning: `dart pub outdated --mode=null-safety` exited with exit code 69 and stderr:, My framework&dart path already detected androidSDK

### ISSUE THREAD

**Issue by stvhrs** [dart-lang/sdk#45257]
Warning: `dart pub outdated --mode=null-safety` exited with exit code 69 and stderr:

Package doesn't exist (the Flutter SDK is not available).

Migrating E:\development\project\Gubuk_Bonsai

Analyzing project...
[------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\]14 analysis issues found:
  error • The named parameter 'providers' isn't defined at lib\main.dart:38:9 • (undefined_named_parameter)
  error • The named parameter 'create' isn't defined at lib\main.dart:39:34 • (undefined_named_parameter)
  error • The named parameter 'create' isn't defined at lib\main.dart:41:13 • (undefined_named_parameter)
  error • The named parameter 'update' isn't defined at lib\main.dart:42:13 • (undefined_named_parameter)
  error • The named parameter 'child' isn't defined at lib\main.dart:48:9 • (undefined_named_parameter)
  error • The named parameter 'source' isn't defined at lib\screens\profile_screen.dart:27:9 • (undefined_named_parameter)
  error • The named parameter 'imageQuality' isn't defined at lib\screens\profile_screen.dart:28:9 • (undefined_named_parameter)
  error • The named parameter 'sourcePath' isn't defined at lib\screens\profile_screen.dart:69:7 • (undefined_named_parameter)
  error • The named parameter 'aspectRatioPresets' isn't defined at lib\screens\profile_screen.dart:70:7 • (undefined_named_parameter)
  error • The named parameter 'androidUiSettings' isn't defined at lib\screens\profile_screen.dart:73:7 • (undefined_named_parameter)
  error • The named parameter 'cropStyle' isn't defined at lib\screens\profile_screen.dart:80:7 • (undefined_named_parameter)
  error • The named parameter 'child' isn't defined at lib\screens\video_screen.dart:79:7 • (undefined_named_parameter)
  error • The named parameter 'value' isn't defined at lib\widgets\products_grid.dart:27:9 • (undefined_named_parameter)
  error • The named parameter 'child' isn't defined at lib\widgets\products_grid.dart:28:9 • (undefined_named_parameter)

Note: analysis errors will result in erroneous migration suggestions.

Please fix the analysis issues (or, force generation of migration suggestions by re-running with --ignore-errors).
PS E:\development\project\Gubuk_Bonsai> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.1)
[√] Connected device (3 available)

• No issues found!

**Comment by davidB** [comment]
I got the same error, due to an old "dart" version (from nix profile in my case) used instead of the one provided by flutter.
Try to check if the `dart` executable is from flutter distribution `command -v dart` & `command -v flutter`, and then maybe fix your `$PATH`.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
