### ISSUE TITLE
[analyzer] dart --packages my_package_config.json analyze doesn't honor the passed in package_config file

### ISSUE THREAD

**Issue by chaselatta** [dart-lang/sdk#45267]
* Dart SDK Version (`dart --version`): Dart SDK version: 2.13.0-116.0.dev (dev) (Sun Mar 7 18:57:20 2021 -0800) on "linux_x64"

I was experimenting with migrating the Fuchsia build rules from using `dartanalyzer` to `dart analyze`. We generate our package_config.json files on demand based on the BUILD.gn rules and then pass the location of this file to the dartanalyzer tool directly. It looks like the analyze subcommand doesn't have this flag but it is available as a global flag to the dart command. However, when I pass this flag like `dart --packages my_package_config.json analyze` the package config is ignored and we get errors about missing packages.

Can this flag either be propagated to the subcommand or fail with an error saying that the flag is not going to be used?

**Comment by bkonyi** [comment]
`dart --packages=config.json analyze` is passing the configuration file to be interpreted by the VM, not the analyzer. It looks like we don't currently support `--packages` with `dart analyze`.

@devoncarew I think we should have support for `--packages` under the `analyze` command.

**Comment by devoncarew** [comment]
I assume this is a flag that all backends need to / should support? dart2js, ddc, `dart compile`? If so, they having parity wrt supporting it in `dart analyze` makes sense.

cc @lrhn in case the package_config spec says anything in this area

**Comment by lrhn** [comment]
All tools should support the flag.
It's the official way to specify the package resolution configuration, with a fallback of finding a file relative to the entry point.

https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md#specifying-the-file

**Comment by scheglov** [comment]
Support for `--package` in `analysis_server`.
https://dart-review.googlesource.com/c/sdk/+/212271

**Comment by scheglov** [comment]
Support for `--packages` in `dart analyze`.
