### ISSUE TITLE
Null safety migration tool doesn't explain why it sometimes add explicit types

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#45268]
I'm trying to migrate some code that looks like:
```dart
    seriesList.forEach((MutableSeries<D> series) {
      final domainFn = series.domainFn;
```
The migration tool wants to add explicit types:
```dart
    seriesList.forEach((MutableSeries<D> series) {
      final D Function(int)? domainFn = series.domainFn;
```
but the details pane doesn't provide any rationale.  It'd be really helpful if it could (like DartPad) show me what type it thinks a particular variable is (or rather, what it would be without the explicit type).  While I could click on the right-hand-side to see the corresponding declaration, in this case it's not obvious since the declaration is for a generic type.

Dart SDK version: 2.13.361763185-edge+google3-v2 (google3) (google3) on "linux_x64"

**Comment by srawlins** [comment]
That assignment might be a bug; I know that was (and may still be) a bug where it unnecessarily adds a cast for function types.

**Comment by jamesderlin** [comment]
I seriously doubt that any further work will ever be done on `dart migrate` since it's been removed in Dart 3.
