### ISSUE TITLE
Fast recompiles to JavaScript

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#4527]
Use Case from existing customer:

Developing with Dartium works well enough. At the end of the development, the engineer needs to compile to JavaScript for final testing. Often times, this code works fine, but the troubles appear when testing across different browsers.

Once cross-browser testing enters into the picture, compiling to JavaScript occurs frequently and often. The current dart2js compile time is slower than we wish.

Feature Request:

Make recompiles to JavaScript much much faster. This will significantly speed up cross-browser testing (an important step in any major web app development cycle)

**Comment by matanlurey** [comment]
So uh, @vsmenon do we want to close this as "DDC"? :)

**Comment by vsmenon** [comment]
sgtm
