### ISSUE TITLE
Improvement - apply to selected files and continue

### ISSUE THREAD

**Issue by apetroaeiandrei** [dart-lang/sdk#45275]
In a few words, I'd like to apply the migration to a file, rerun, apply to another file and so on but I have to run dart migrate again, every time I apply some changes.

#### Steps to reproduce
Select just a couple of files and apply migration to them.

#### What did you expect to happen?
Being able to analyse another file after applying migration to a selected batch of files.

#### What actually happened?
Clicking on another file after applying migration shows errors.
Migration stops, I have to run "dart migrate" again.

_Screenshots are appreciated_

**Dart SDK version**: 2.12.0

Thanks for filing!

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
