### ISSUE TITLE
Dart: SignalException in dart bin/server.dart

### ISSUE THREAD

**Issue by matheuskildere** [dart-lang/sdk#45278]
occurs when I try to execute the command to run my backend:
K:\iCode\guia-do-aluguel\test> dart bin/server.dart

Unhandled exception:
SignalException: Failed to listen for SIGTERM, osError: OS Error: Não há suporte para o pedido.
, errno = 50

**Comment by a-siva** [comment]
Please also see https://github.com/dart-lang/sdk/issues/28603
