### ISSUE TITLE
Change `dart create` to enable null safety (language version 2.12.) by default

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#45282]
With the 2.12.1 release, if I create a new package using `dart create`, the created pubspec contains:
```yaml
environment:
  sdk: '>=2.10.0 <3.0.0'
```
I expect the null safety release to create projects with null safety enabled by default.

**Comment by mit-mit** [comment]
This is something we're considering for 2.13. We want to make sure we have a sufficient ecosystem first.

**Comment by bkonyi** [comment]
cc @devoncarew since [this CL](https://dart-review.googlesource.com/c/sdk/+/192944) updates the default language version to be 2.12.

**Comment by devoncarew** [comment]
I _believe_ I've captured the latest from this PR into that CL into dart-lang/sdk.

**Comment by devoncarew** [comment]
I believe this is complete; closing.
