### ISSUE TITLE
Analyzer & CFE(w/NNBD) fails to resolve ternary expression type, CFE (w/o NNBD) succeeds

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#45289]
Repro:
```
abstract class A<T> {}
abstract class D {}

class B extends D implements A<bool> {}
class C extends D implements A<bool> {}

T foo<T>(A<T> a) {
  throw 'foo';
}

void main() {
  const a = false;
  foo(a ? B() : C()); // line 13 • The argument type 'Object' can't be assigned to the parameter type 'A<bool>'.
}
```

This code shows an analysis error on the ternary expression. Removing `extends D` from class B/C fixes the analysis error. The expression is Object here, when it really should be `A<bool>`.

This code works fine in CFE without Null Safety enabled, and the type of T can be successfully inferred. Enabling Null Safety results in the CFE outputting the same error.

**Comment by eernstg** [comment]
This is working as intended.

**Comment by ds84182** [comment]
Sure. But this also means that extending a private class, implementing a private interface, or applying a private mixin, is a breaking change, as LUB does not ignore them.

**Comment by eernstg** [comment]
That is true. However, I think it would be dangerously clever to make the type of `a ? B() : C()` depend on whether the expression occurs in the library where one or more of those private classes is declared, or it occurs in some other library. Would we also ignore superinterfaces that aren't imported?

**Comment by ds84182** [comment]
Hm. LUB assumes there isn't a context type involved, which is useful for variable declaration type inference.

There are two cases where this can come up:
```dart
final decl = a ? B() : C();
function(a ? B() : C());
```

In the declaration's case, the type is an open-ended problem. You can choose `D`, or `A<bool>`, or even `D & A<bool>`.

For the function call's case, there is a required subtype. In the case of LUB failure (since we can't select `D & A<bool>`), wouldn't the next best case be to assume the context type `A<T>` for the ternary expression? The arms can then be treated as subtypes of `A<T>`. This would also enable better error reporting in the case where the two types are incompatible, as you can receive an error for the incompatible arm, instead of the whole expression.

**Comment by eernstg** [comment]
In principle, LUB could take the context type into account, but I suspect that this is not a tractable approach in general.

In concrete terms, you could change `C` and `D` to avoid the ambiguous superinterfaces:

```dart
abstract class A<T> {}
abstract class D {}
abstract class D1 extends D implements A<bool> {}

class B extends D1 {}
class C extends D1 {}
```

and then you'd have `D1` as the least upper bound of `B` and `C`.
