### ISSUE TITLE
Observatory doesn't print where it's listening when receiving SIGQUIT

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#45283]
One can make observatory start by sending (at least on Linux) SIGQUIT to it.
Back in the day it printed to the terminal where it was listening so one could open it up and be on ones way.

Now, however, nothing is printed.
Sending SIGQUIT again and it prints something like
```
Observatory no longer listening on http://127.0.0.1:36721/VPYtH1GXBBY=/
```
but considering it's no longer listening that's not all that useful.

(a workaround for me for now is that while the port changes when sending SIGQUIT again, the auth code does not, so sending SIGQUIT a third time and running `lsof -Pnl +M -i4 | grep dart | grep LISTEN` can give me a port so I can recreate the url myself --- it's not very user-friendly though).

Please make it print the url again.

**Comment by a-siva** [comment]
@jensjoha can you elaborate on what feature of Observatory you rely on that is not available in [devtools](https://dart.dev/tools/dart-devtools).

//cc @bkonyi

**Comment by jensjoha** [comment]
I have no experience with `devtools` --- from the link I
a) Need to install something extra, and
b) Still need to uri to observatory for it to do anything which is what this issue is about: I don't have that.
