### ISSUE TITLE
Allow unmarking all files or by folders in NNBD migration tool

### ISSUE THREAD

**Issue by expilu** [dart-lang/sdk#45295]
#### Steps to reproduce
In the list of files to be migrated or unmarked for pending migration there is no way to unmark all files or complete folders.

#### What did you expect to happen?

It would be nice to be able to unmark all files or folders and subfolders. Our project has upwards of 500 files, unmarking them to work in migrating specific files progessively is unbearable. Specially when the tool marks them all again every time you open it, so we would have to unmark hundreds of checkboxes each time.

**Dart SDK version**: 2.12.0

**Comment by petrnymsa** [comment]
I am currently migrating large code-base to null-safety and this missing feature is really needed.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
