### ISSUE TITLE
Dart 2.12.1 analyzer is suggesting to enable non-nullable experiment flag when flag is deprecated

### ISSUE THREAD

**Issue by Stargator** [dart-lang/sdk#45302]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Analyzer

* Dart SDK Version (`dart --version`) - 2.12.1
* Whether you are using Windows, MacOSX, or Linux (if applicable) MacOSX

Exercism's Dart track has an exercise that contains a method in the test file. This method has two named parameters.

The input for the named parameters is never null, so I tried to use the `required` annotation. But the analyzer says:

> 4 analysis issues found:
>   error • Unexpected text 'required' at test/robot_simulator_test.dart:126:29 • (unexpected_token)
>   error • This requires the 'non-nullable' language feature to be enabled at test/robot_simulator_test.dart:126:29 • (experiment_not_enabled)
>   error • Unexpected text 'required' at test/robot_simulator_test.dart:126:53 • (unexpected_token)
>   error • This requires the 'non-nullable' language feature to be enabled at test/robot_simulator_test.dart:126:53 • (experiment_not_enabled)

So I refactored the named parameters to normal parameters. Ran `dart migrate`, nothing special needed to be changed so I applied the migration tool's changes (which were none).

Then I went back to the test file and refactored the parameters back to named parameters. Ran `dart migrate`:

> Analyzing project...
> [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------]
> 2 analysis issues found:
>   error • The parameter 'beAt' can't have a value of 'null' because of its type, but the implicit default value is 'null' at test/robot_simulator_test.dart:126:38 • (missing_default_value_for_parameter)
>   error • The parameter 'faceTo' can't have a value of 'null' because of its type, but the implicit default value is 'null' at test/robot_simulator_test.dart:126:56 • (missing_default_value_for_parameter)

I then added the `required` annotation to the two named parameters. The analyzer was satisfied and when I ran `dart migrate` again:

`All sources appear to be already migrated.  Nothing to do.`

Expected outcome:

I would have expected that I could add the required annotations to the parameters as **part** of the suggested changes from the migration tool. So it took some work to get the code migrated while keeping the named parameters.

In Order to Reproduce:

[Link to the impacted exercise/dart project](https://github.com/exercism/dart/tree/44f4241fc0b64644794930095a5ef93bfb2c7bb8/exercises/practice/robot-simulator). Note that this is **not** the most recent version as I may merge my branch that migrates the code to 2.12.0. So if you need to clone it I recommend running:

`git clone https://github.com/exercism/dart.git` or `git clone git@github.com:exercism/dart.git`

and then run `git checkout 44f4241fc0b646` or `git switch -d 44f4241fc0b646`

Then you will need to go into exercises/practice/robot-simulator in order to run the `dart migrate` command

**Comment by Stargator** [comment]
Missed the part [in the docs that discusses this](https://dart.dev/null-safety/migration-guide#migration-tool)

**Comment by srawlins** [comment]
Sorry, it looks like you were having issues running the migration tool multiple times, which changes the language version as part of its changes. `required` cannot be added before null safety, and was, as you saw, necessary, when using null safety. I think everything here was working as intended.
