### ISSUE TITLE
Generic function type as a type argument of the generic function type alias works incorrectly.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45313]
Dart SDK version: 2.13.0-114.0.dev (dev) (Sat Mar 6 18:27:50 2021 -0800) on "windows_x64"

The following code example declares generic function typedef `TEST_TYPEDEF` and then try to assign `TEST_TYPEDEF` variable and check its type:
``` dart
typedef TEST_TYPEDEF<TT extends T Function<T>(T)> = void Function<TTT extends TT>();
void  testme<TT extends T Function<T>(T)>() {}

main() {
  print(testme is TEST_TYPEDEF);
  TEST_TYPEDEF ttttt = testme;
  print(ttttt is TEST_TYPEDEF);
}
```
It's expected that if I succssffully assign `testme`  to the variable of the type `TEST_TYPEDEF`, `ttttt is TEST_TYPEDEF` should report `true`. However, this is not so here: there are no errors and the example above twice prints `false` unexpectidly.

**Comment by eernstg** [comment]
Agreed, `TEST_TYPEDEF` means `TEST_TYPEDEF<T Function<T>(T)>` means `void Function<TTT extends T Function<T>(T)>()`, same as `void Function<TT extends T Function<T>(T)>()`, so  we should get true, twice.

```
library /*isNonNullableByDefault*/;
import self as self;
import "dart:core" as core;

typedef TEST_TYPEDEF<invariant TT extends <T extends core::Object? = dynamic>(T%) → T% = <T extends core::Object? = dynamic>(T%) → T%> = <TTT extends TT = dynamic>() → void;
static method testme<TT extends <T extends core::Object? = dynamic>(T%) → T% = <T extends core::Object? = dynamic>(T%) → T%>() → void {}
static method main() → dynamic {
  core::print((#C1) is{ForNonNullableByDefault} <TTT extends <T extends core::Object? = dynamic>(T%) → T% = dynamic>() → void);
  <TTT extends <T extends core::Object? = dynamic>(T%) → T% = dynamic>() → void ttttt = #C1;
  core::print(ttttt is{ForNonNullableByDefault} <TTT extends <T extends core::Object? = dynamic>(T%) → T% = dynamic>() → void);
}
constants  {
  #C1 = tearoff self::testme
}
```

@johnniwinther, does this look like a front-end issue? I suspect it's a vm issue, but `TTT extends TT = dynamic` looks a bit surprising to me.

**Comment by a-siva** [comment]
//cc @crelier

**Comment by stefantsov** [comment]
@eernstg I think the suspicious `TTT extends TT = dynamic` part is because the default types (those the follow `=` in the declarations of type variables) don't really make sense for function types, only for classes and functions, because instantiate-to-bound doesn't apply to them. We see them there only because we use the same `TypeParameter` node kind for all of class, function, typedef, and function type type parameters. It likely doesn't affect the execution.

**Comment by johnniwinther** [comment]
I don't think it's a front end issue.
