### ISSUE TITLE
[analysis_server_client] Migrate and publish a null safe version to pub.dev

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#45311]

**Comment by bwilkerson** [comment]
This will need to be coordinated with the migration of the `analysis_server` package because all of the code defining the protocol is generated and the generator is also used for the corresponding classes in the `analysis_server` package.

**Comment by osaxma** [comment]
Looks like the package in the main branch is already migrated to null-safety but that version is not available on `pub.dev`.

**Comment by AlexeyBukin** [comment]
Yeah, apart from `dev_dependencies` on unpublished `analysis_server` and `analyzer_utilities` packages it seems to do it's work. Can it be published, maybe like a `dev` version?

**Comment by devoncarew** [comment]
This has been migrated and a new version published.

However, we're considering discontinuing the package - no longer publishing versions of it. I'll open an issue to track that, and gather feedback on current usage of it as well as the use cases for that.

**Comment by devoncarew** [comment]
Here's the issue tracking discontinuing the package (and for gathering the current use cases for people using it): https://github.com/dart-lang/sdk/issues/50262.
