### ISSUE TITLE
Add addAllIf method to Map<K, V>

### ISSUE THREAD

**Issue by guilhermeagostinelli** [dart-lang/sdk#45312]
What about adding a new `addAllIf` method to the `Map<K, V>` class?

Its signature could be something like:

```dart
void addAllIf(bool test(), Map<K, V> other);
```

This could be useful for example when we have a function that expects a Map because we could use the the cascade notation on the argument itself without having to store the map in a temporary variable.

```dart
void doSomethingWithTheMap(Map<String, dynamic> m) {
  // Do something with m...
}

final bool anyCondition = true;
```

So we could use this:
```dart
doSomethingWithTheMap({ 'a': 'abc', 'b': 15 }..addAllIf(() => anyCondition, {'c': 10}));
```

instead of this:
```dart
final Map<String, dynamic> m = { 'a': 'abc', 'b': 15 };
if (anyCondition) m['c'] =  10;
doSomethingWithTheMap(m);
```

Well, at the end it is just syntactic sugar. Not really sure if it is worth it.

Currently I'm using an extension in order to accomplish that:

```dart
extension AddAllIf<K,V> on Map<K,V> {
  void addAllIf(bool test(), Map<K,V> other) {
    if (test()) this.addAll(other);
  }
}
```

Anyway, looking forward to getting your opinion on this.

**Comment by rakudrama** [comment]
You might consider the following:

Adding an empty map:
```dart
doSomethingWithTheMap({ 'a': 'abc', 'b': 15 }..addAll(anyCondition ? {'c': 10} : {})
```

Constructing the map with conditional elements:
```dart
doSomethingWithTheMap(
  { 'a': 'abc',
    'b': 15,
    if (anyCondition) 'c': 10
  });
```
The second one is described [here](https://medium.com/dartlang/making-dart-a-better-language-for-ui-f1ccaf9f546c) and [here](https://medium.com/dartlang/exploring-collections-in-dart-f66b6a02d0b1).

**Comment by guilhermeagostinelli** [comment]
Perfect, these alternatives are great. Thanks for your suggestion @rakudrama!
