### ISSUE TITLE
[vm/ffi] Compiler intrinsics function support

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/sdk#45314]
Add InterlockedIncrement/InterlockedDecrement to win32api.json doen't work: https://github.com/timsneath/win32/issues/181

```json
    "InterlockedDecrement": {
        "prototype": "LONG _InterlockedDecrement(\n        LONG *Addend\n      );",
        "dllLibrary": "kernel32",
        "comment": "Decrements (decreases by one) the value of the specified 32-bit variable as an atomic operation."
    },
    "InterlockedIncrement": {
        "prototype": "LONG _InterlockedIncrement(\n        LONG *Addend\n      );",
        "dllLibrary": "kernel32",
        "comment": "Increments (increases by one) the value of the specified 32-bit variable as an atomic operation."
    },
```

According to [InterlockedIncrement](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockedincrement-intrinsic-functions?view=msvc-160) and [InterlockedDecrement](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockeddecrement-intrinsic-functions?view=msvc-160), they are **Microsoft-specific** [Compiler intrinsics](https://docs.microsoft.com/en-us/cpp/intrinsics/compiler-intrinsics?view=msvc-160)

**Comment by a-siva** [comment]
//cc @dcharkes

**Comment by dcharkes** [comment]
@Sunbreak it is unclear to me what you are suggesting.

`dart:ffi` does not compile any C code, it calls into it. Compiler intrinsics are inlined in C code somewhere. If you'd want to invoke such an intrinsic from Dart via `dart:ffi` you would need to create a C wrapper function which executes the intrinsic and call that from Dart. There's nothing to do on the `dart:ffi` side.

**Comment by Sunbreak** [comment]
Got it. I'll try to wrap it somehow
