### ISSUE TITLE
[analyzer] Closures in static methods shouldn't have access to class scope.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#45310]
```dart
class MyClass {
  final int i;

  const MyClass(this.i);

  static void fn() {
    final _ = () => i; // The analyzer should emit an error here
  }
}
```

**Comment by srawlins** [comment]
I swear I've fixed this like three times. ☹️ . This remaining bug might just be for closures in static functions...

**Comment by srawlins** [comment]
This was fixed by @scheglov at the end of January with https://github.com/dart-lang/sdk/commit/934980be801c8007189500ee6980fd81b9eca079.

It should go out in Dart 2.13.
