### ISSUE TITLE
[analyzer] Should not call null

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45318]
Consider the following program:

```dart
// @dart = 2.9

void main() {
  null();
}
```

The analyzer from commit 11d6203130004d0e3efff70f7873933fb53945b9 (of today) accepts the above program. However, calling null should be an error, cf. https://github.com/dart-lang/language/blob/893d59be1bfa403d93b4f500122f9288adf9b169/specification/dartLangSpec.tex#L12172.

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/191181

**Comment by scheglov** [comment]
I see that we start failing `co19_2/Language/Expressions/Function_Expressions/syntax_t05`, but you have already opened the [issue](https://github.com/dart-lang/co19/issues/1011).

**Comment by eernstg** [comment]
Yes, it's probably turning green after the next co19 roll.
