### ISSUE TITLE
Dart throws unexpected unhandled exception when checks bounds of function type alias with invariant generic function type parameter.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45322]
Dart SDK version: 2.13.0-114.0.dev (dev) (Sat Mar 6 18:27:50 2021 -0800) on "windows_x64"

Here is a source code example which demonstrates the failure:
``` dart
typedef void TEST<T extends void Function<TT>(TT)>();
void testme<T extends void Function<TT>(TT)>() {}

main() {
  TEST t = testme;
}
```
Sample output is:
```
$>dart --enable-experiment=generic-metadata test.dart
Unhandled exception:
type '<X0>(X0) => void' is not a subtype of type '<X1>(dynamic) => void' of 'T'
#0      _boundsCheckForPartialInstantiation (dart:_internal-patch/internal_patch.dart:147:57)
#1      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Generic-functions-as-type-args/test.dart)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
Similar covariant case passes OK without any errors or warnings.

**Comment by eernstg** [comment]
@mkustermann, I think this is a VM issue, do you agree?

**Comment by lrhn** [comment]
This uses the old-style `typedef` syntax which makes the typedef generic, not the function it aliases.
This code is equivalent to:
```dart
typedef TEST<T extends void Function<TT>(TT)> = void Function();
void testme<T extends void Function<TT>(TT)>() {}

main() {
  TEST t = testme;
}
```
Meaning it's really doing `void Function() t = testme;`.
That should cause an instantiated tear-off, with no constraints on the instantiation.
I'd expect that to perform instantiate-to-bounds, with `void Function<TT>(TT)` as the implied type argument to `testme`.

Shouldn't be an error, as I understand how things work, and the `dynamic` in the error message feels spurious.

The test does look suspiciously like it thinks something else is going on.

**Comment by eernstg** [comment]
Thanks, I had exactly the same analysis! I noted that the generated kernel code looks right, so it seems to be an issue that arises in the backend:

```
library /*isNonNullableByDefault*/;
import self as self;
import "dart:core" as core;

typedef TEST<unrelated T extends <TT extends core::Object? = dynamic>(TT%) → void = <TT extends core::Object? = dynamic>(TT%) → void> = () → void;
static method testme<T extends <TT extends core::Object? = dynamic>(TT%) → void = <TT extends core::Object? = dynamic>(TT%) → void>() → void {}
static method main() → dynamic {
  () → void t = #C1<<TT extends core::Object? = dynamic>(TT%) → void>;
}
constants  {
  #C1 = tearoff self::testme
}
```

**Comment by crelier** [comment]
Sure.
