### ISSUE TITLE
[CP] [Stable] - Retain certificates used by trust certification evaluation

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#45325]
Please cherry pick [937a716b09](https://dart.googlesource.com/sdk/+/937a716b095c4803750ed5013706cccd07dc613c) into the stable branch

Reason : Crashes have been reported in Flutter after transition to Flutter 2

Impact: This change will fix the crashes reported in Flutter by users after they have transitioned to Flutter 2

The change merges cleanly into the stable branch.

Risk: Low, the change is in master and rolled into Flutter/Google3 and is also in the latest Flutter dev channel

Link to original issue : https://github.com/flutter/flutter/issues/78167

/cc @kevmoo @mit-mit @athomas @vsmenon @franklinyow @kf6gpe @aam

**Comment by mraleph** [comment]
Strong support for cherrypicking this from me.

**Comment by athomas** [comment]
FYI, this fix is included in `2.13.0-116.1.beta` so it only needs to be CP'ed to stable.

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved in SCRUM

**Comment by franklinyow** [comment]
Text:
This change will fix the crashes reported in Flutter by users after they have transitioned to Flutter 2, see flutter#78167

**Comment by athomas** [comment]
Merged to stable in 65376c07234d1df472662d21dff2498ab2d3cdda (2.12.2).
