### ISSUE TITLE
NPE in _attemptPrecedenceLevelRecovery

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#45327]
See https://github.com/dart-lang/sdk/issues/45233#issuecomment-797478566

@jensjoha

**Comment by troelsbjerre** [comment]
Small code snippet that reproduces the error for all commandline tools, including dartfmt:
```
main() {
  if (n is int or
}
```

**Comment by jensjoha** [comment]
Fantastic! Thanks --- I'll get that fixed =)

**Comment by jensjoha** [comment]
What version of dart are you seeing this on?

**Comment by troelsbjerre** [comment]
Dart SDK version: 2.12.1 (stable) (Unknown timestamp) on "linux_x64"

**Comment by jensjoha** [comment]
Thanks! This was fixed in 16a66c89025ad330844a07baf76553c45cfbf7b8.
For good measure I'll add these examples as tests though.
