### ISSUE TITLE
dart2js: cleanup after `>>>` is enabled by default

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#45335]
See https://github.com/dart-lang/sdk/issues/30890#issuecomment-794197803:

* [x] remove `triple-shift` flags added to the codegen and optimization tests
* [x] run dartfmt on the test code containing `>>>`.

**Comment by sigmundch** [comment]
FYI @rakudrama - this may be unblocked since 9443e248ee9ff3514362ff9bce425c1eaffe3f3a

**Comment by rakudrama** [comment]
Still need analyzer/dartfmt to refault to triple-shift.

**Comment by vsmenon** [comment]
@sigmundch - this is in the July milestone - can we close now?

**Comment by sigmundch** [comment]
Not sure, @rakudrama - is it possible to do the cleanup at this time? Or do we need to wait until the feature hits stable?

**Comment by rakudrama** [comment]
There are now no dart2js-specific files that need reformatting.
