### ISSUE TITLE
Static error testing doesn't handle error in imported libraries

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#45333]
The test `language/nonfunction_type_aliases/mixed/aliased_cyclic_superclass_error_test` assumes errors reported in an imported library. The static error tests framework doesn't seem to handle that.

**Comment by johnniwinther** [comment]
cc @eernstg @munificent

**Comment by eernstg** [comment]
True, this has been reported as #44990 (so I think this one is a duplicate). I also changed said test in https://dart-review.googlesource.com/c/sdk/+/191365, such that we can see the actual behavior of tools as intended.
