### ISSUE TITLE
Add option to disable breakpoints

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#45336]
We should provide a service RPC to allow for enabling and disabling breakpoints without having to remove and recreate them each time.

VM tracking issue for https://github.com/flutter/devtools/issues/696.

**Comment by a-siva** [comment]
Why does this have to go in at the service RPC level, can this not be a functionality handled by DDS ?

**Comment by bkonyi** [comment]
This would be simpler to add to the service since we already have a way to enable/disable breakpoints in the VM, it's just functionality that isn't currently exposed.

**Comment by a-siva** [comment]
I was wondering about whether you would provide the capability of multiple clients to have their own enable/disable state for the breakpoints in which case the VM state would not help.
