### ISSUE TITLE
[proposal] [dart 2.12] `Iterable<E>` methods `first` and `last` should return `E?` 

### ISSUE THREAD

**Issue by iapicca** [dart-lang/sdk#45337]
### use case

currently an empty [iterable](https://api.dart.dev/stable/2.12.1/dart-core/Iterable-class.html) just throws if [first](https://api.dart.dev/stable/2.12.1/dart-core/Iterable/first.html) and [last](https://api.dart.dev/stable/2.12.1/dart-core/Iterable/last.html) are called 
allowing to **_inadvertently_** assigning a `null` value to a `non-nullable` variable

```dart
final int first = <int>[].first;
```

### proposal

I feel it would be coherent and consistent if
`Iterable<E>` methods `first` and `last` return `E?` rather than `E` or `Error`

**Comment by RandalSchwartz** [comment]
How would a throw cause a null to be assigned, except through bad logic?

**Comment by nt4f04uNd** [comment]
see https://github.com/dart-lang/sdk/issues/42583#issuecomment-711146248

i don't understand though, why would `first` and `last` behave different than `elementAt`?

**Comment by iapicca** [comment]
@nt4f04uNd 
> > see [#42583 (comment)](https://github.com/dart-lang/sdk/issues/42583#issuecomment-711146248)
> 
> There is a `firstOrNull` and `lastOrNull` extension method in the tip-of-tree version of `package:collection`.
> It will be released along with null safety.

thanks I'll definitely use that
> regarding your proposal: i don't understand, why would `first` and `last` behave different than `elementAt`?

good point, same for `elementAt` 
I would imagine that a method that might return a `null` should not just `throw at runtime`, but return `E?`
**_just my opinion_**
