### ISSUE TITLE
nnbd bug in Service.getIsolateID in compiled apps.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#45347]
I have code which uses Service.getIsolateID which I use to obtain inter-isolate and inter-process locks.

The code works fine if I run the script using jit?

```
dart named_lock.dart
```

However if I compile the script the call to Service.getIsolateID is throwing the following exception:

```
type 'Null' is not a subtype of type 'String' of 'function result'
#0      _getIsolateIDFromSendPort (dart:developer-patch/developer.dart)
#1      Service.getIsolateID (dart:developer/service.dart:86)
#2      NamedLock._takeLock.<anonymous closure>
```

In previous versions of dart the call would just return null if the app was compiled.

dart --version
Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "linux_x64"

**Comment by a-siva** [comment]
Would it be possible to share a snippet of code from named_lock.dart that reproduces the problem.
By 'compile the script' do you mean compiled to JS using dart2js or compiled to an AOT snapshot using dart2native ?

**Comment by bsutton** [comment]
I'm using dart compile.

I did try to reproduce it in a code snippet but unfortunately I can't
reproduce it on machine.
One of our dev team members reported it.

**Comment by vsmenon** [comment]
@a-siva - it looks like the VM patch for `_getIsolateIDFromSendPort` returns a `String` but the main declaration returns a `String?`:

https://github.com/dart-lang/sdk/search?q=_getIsolateIDFromSendPort

Should they both be `String?` ?

**Comment by maks** [comment]
@vsmenon  exactly right, they should both be `String?` because the issue seems to be that when compiling to AOT, the patch returns null, which is what the signature for the public API `Service.getIsolateID()` is anyway.

@a-siva the minimal repro here is trivial:
```
import 'dart:developer';
import 'dart:isolate';

void main() {
  final id = Service.getIsolateID(Isolate.current) ?? "NA";
  print(id);
}
```
it will be fine in JIT, but AOT compile then run the exe and see it blow up and the public API caller never gets a chance to use a default value like I try to do above with the "NA" string.

**Comment by maks** [comment]
In Dart 3.1.2 I'm seeing this behaviour also for `.debugName` for Isolate references to Isolates that have exited, even when running in JIT mode which means careful tracking of an Isolate references state via listening to its onExit 😢 .

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/329784
