### ISSUE TITLE
[dart migrate] can't migrate because of flutter_driver

### ISSUE THREAD

**Issue by johngithubby** [dart-lang/sdk#45355]
I'm trying to migrate a flutter app, but I'm getting this when I dart migrate:

> Bad state: Error: package has unmigrated dependencies.
> 
> Before migrating your package, we recommend ensuring that every library it
> imports (either directly or indirectly) has been migrated to null safety, so
> that you will be able to run your unit tests in sound null checking mode.  You
> are currently importing the following non-null-safe libraries:
> 
>   package:flutter_driver/flutter_driver.dart
>   ...

`dart pub outdated --mode=null-safety` says everything is fine:

> Showing dependencies that are currently not opted in to null-safety.
> [✗] indicates versions without null safety support.
> [✓] indicates versions opting in to null safety.
> 
> Package Name  Current  Upgradable  Resolvable  Latest  
> 
> direct dependencies: all support null safety.
> 
> dev_dependencies: all support null safety.
> You are already using the newest resolvable versions listed in the 'Resolvable' column.
> Newer versions, listed in 'Latest', may not be mutually compatible.
> 

Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "macos_x64"

**Comment by stereotype441** [comment]
@jonasfj any idea what might be happening here?  I'm trying to figure out whether this is a bug in the migration tool or in pub.

**Comment by jonasfj** [comment]
try: `dart pub outdated --mode=null-safety --transitive` that should show the transitive dependencies too.

**Comment by stereotype441** [comment]
@johngithubby which version of Flutter are you using?  It's possible that could have an impact.

**Comment by johngithubby** [comment]
> @johngithubby which version of Flutter are you using? It's possible that could have an impact.

Here you are @stereotype441 

Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (11 days ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1

**Comment by johngithubby** [comment]
> try: `dart pub outdated --mode=null-safety --transitive` that should show the transitive dependencies too.

This is the result @jonasfj :

dart pub outdated --mode=null-safety --transitive
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name                   Current    Upgradable  Resolvable  Latest    

direct dependencies: all support null safety.

dev_dependencies: all support null safety.

transitive dev_dependencies:  
_fe_analyzer_shared            ✗14.0.0    ✗14.0.0     ✗14.0.0     ✓18.0.0   
analyzer                       ✗0.41.2    ✗0.41.2     ✗0.41.2     ✓1.2.0    
archive                        ✗2.0.13    ✗2.0.13     ✗2.0.13     ✓3.1.2    
args                           ✗1.6.0     ✗1.6.0      ✗1.6.0      ✓2.0.0    
build                          ✗1.6.2     ✗1.6.2      ✗1.6.2      ✓2.0.0    
code_builder                   ✗3.7.0     ✗3.7.0      ✗3.7.0      ✗3.7.0    
convert                        ✗2.1.1     ✗2.1.1      ✗2.1.1      ✓3.0.0    
coverage                       ✗0.15.2    ✗0.15.2     ✗0.15.2     ✓1.0.2    
crypto                         ✗2.1.5     ✗2.1.5      ✗2.1.5      ✓3.0.0    
dart_style                     ✗1.3.12    ✗1.3.12     ✗1.3.12     ✓2.0.0    
fuchsia_remote_debug_protocol  ✗(sdk)     ✗(sdk)      ✗(sdk)      ✗(sdk)    
node_preamble                  ✗1.4.13    ✗1.4.13     ✗1.4.13     ✓2.0.0    
package_config                 ✗1.9.3     ✗1.9.3      ✗1.9.3      ✓2.0.0    
shelf_packages_handler         ✗2.0.1     ✗2.0.1      ✗2.0.1      ✓3.0.0    
shelf_static                   ✗0.2.9+2   ✗0.2.9+2    ✗0.2.9+2    ✓1.0.0    
shelf_web_socket               ✗0.2.4+1   ✗0.2.4+1    ✗0.2.4+1    ✓1.0.1    
source_gen                     ✗0.9.10+3  ✗0.9.10+3   ✗0.9.10+3   ✓1.0.0    
sync_http                      ✗0.2.0     ✗0.2.0      ✗0.2.0      ✓0.3.0    
vm_service                     ✗5.5.0     ✗5.5.0      ✗5.5.0      ✓6.1.0+1  
web_socket_channel             ✗1.2.0     ✗1.2.0      ✗1.2.0      ✓2.0.0    
webdriver                      ✗2.1.2     ✗2.1.2      ✗2.1.2      ✓3.0.0    
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
![Screen Shot 2021-03-22 at 12 42 25](https://user-images.githubusercontent.com/11788725/112026030-2dd90d80-8b0c-11eb-8e00-bac01e7cea85.png)

**Comment by stereotype441** [comment]
@johngithubby

Hmm, it's curious that `flutter_driver` is the package being complained about, but it doesn't appear in the list of transitive dev dependencies.  Is it possible that you're depending on the `flutter_driver` but didn't list it in your `pubspec.yaml` file?

**Comment by johngithubby** [comment]
> @johngithubby
> 
> Hmm, it's curious that `flutter_driver` is the package being complained about, but it doesn't appear in the list of transitive dev dependencies. Is it possible that you're depending on the `flutter_driver` but didn't list it in your `pubspec.yaml` file?

@stereotype441 yeah, I thought that was weird, I was looking for it in the list. It is listed in my pubspec:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.5
  effective_dart: ^1.3.1
  mockito: ^5.0.0-nullsafety.7

**Comment by stereotype441** [comment]
Weird.  Are you referencing `flutter_driver` from inside the `lib` directory of your project?  If so, it should probably be listed as an ordinary dependency rather than a dev dependency.  (@jonasfj can you confirm this?)

**Comment by johngithubby** [comment]
@stereotype441 no, I'm not using flutter_driver from inside lib, just from outside of it. But I'm told that "dev_dependencies: all support null safety." anyway.
Here's the full list of packages dart migrate is complaining about:

Before migrating your package, we recommend ensuring that every library it
imports (either directly or indirectly) has been migrated to null safety, so
that you will be able to run your unit tests in sound null checking mode.  You
are currently importing the following non-null-safe libraries:

  package:flutter_driver/flutter_driver.dart
  package:flutter_driver/src/common/fuchsia_compat.dart
  package:flutter_driver/src/driver/common.dart
  package:flutter_driver/src/driver/driver.dart
  package:flutter_driver/src/driver/percentile_utils.dart
  package:flutter_driver/src/driver/profiling_summarizer.dart
  package:flutter_driver/src/driver/scene_display_lag_summarizer.dart
  package:flutter_driver/src/driver/timeline.dart
  package:flutter_driver/src/driver/timeline_summary.dart
  package:flutter_driver/src/driver/vmservice_driver.dart
  package:flutter_driver/src/driver/web_driver.dart
  package:fuchsia_remote_debug_protocol/fuchsia_remote_debug_protocol.dart
  package:fuchsia_remote_debug_protocol/src/common/logging.dart
  package:fuchsia_remote_debug_protocol/src/common/network.dart
  package:fuchsia_remote_debug_protocol/src/dart/dart_vm.dart
  package:fuchsia_remote_debug_protocol/src/fuchsia_remote_connection.dart
  package:fuchsia_remote_debug_protocol/src/runners/ssh_command_runner.dart
  package:vm_service/src/dart_io_extensions.dart
  package:vm_service/src/service_extension_registry.dart
  package:vm_service/src/snapshot_graph.dart
  package:vm_service/src/stream_helpers.dart
  package:vm_service/src/vm_service.dart
  package:vm_service/vm_service.dart
  package:webdriver/async_core.dart
  package:webdriver/async_io.dart
  package:webdriver/src/async/alert.dart
  package:webdriver/src/async/common.dart
  package:webdriver/src/async/common_stub.dart
  package:webdriver/src/async/cookies.dart
  package:webdriver/src/async/keyboard.dart
  package:webdriver/src/async/logs.dart
  package:webdriver/src/async/mouse.dart
  package:webdriver/src/async/stepper.dart
  package:webdriver/src/async/target_locator.dart
  package:webdriver/src/async/timeouts.dart
  package:webdriver/src/async/web_driver.dart
  package:webdriver/src/async/web_element.dart
  package:webdriver/src/async/window.dart
  package:webdriver/src/common/by.dart
  package:webdriver/src/common/capabilities.dart
  package:webdriver/src/common/command_event.dart
  package:webdriver/src/common/cookie.dart
  package:webdriver/src/common/exception.dart
  package:webdriver/src/common/log.dart
  package:webdriver/src/common/mouse.dart
  package:webdriver/src/common/request.dart
  package:webdriver/src/common/request_client.dart
  package:webdriver/src/common/session.dart
  package:webdriver/src/common/spec.dart
  package:webdriver/src/common/utils.dart
  package:webdriver/src/common/web_element.dart
  package:webdriver/src/common/webdriver_handler.dart
  package:webdriver/src/handler/infer_handler.dart
  package:webdriver/src/handler/json_wire/alert.dart
  package:webdriver/src/handler/json_wire/cookies.dart
  package:webdriver/src/handler/json_wire/core.dart
  package:webdriver/src/handler/json_wire/element.dart
  package:webdriver/src/handler/json_wire/element_finder.dart
  package:webdriver/src/handler/json_wire/frame.dart
  package:webdriver/src/handler/json_wire/keyboard.dart
  package:webdriver/src/handler/json_wire/logs.dart
  package:webdriver/src/handler/json_wire/mouse.dart
  package:webdriver/src/handler/json_wire/navigation.dart
  package:webdriver/src/handler/json_wire/session.dart
  package:webdriver/src/handler/json_wire/timeouts.dart
  package:webdriver/src/handler/json_wire/utils.dart
  package:webdriver/src/handler/json_wire/window.dart
  package:webdriver/src/handler/json_wire_handler.dart
  package:webdriver/src/handler/w3c/alert.dart
  package:webdriver/src/handler/w3c/cookies.dart
  package:webdriver/src/handler/w3c/core.dart
  package:webdriver/src/handler/w3c/element.dart
  package:webdriver/src/handler/w3c/element_finder.dart
  package:webdriver/src/handler/w3c/frame.dart
  package:webdriver/src/handler/w3c/keyboard.dart
  package:webdriver/src/handler/w3c/mouse.dart
  package:webdriver/src/handler/w3c/navigation.dart
  package:webdriver/src/handler/w3c/session.dart
  package:webdriver/src/handler/w3c/timeouts.dart
  package:webdriver/src/handler/w3c/utils.dart
  package:webdriver/src/handler/w3c/window.dart
  package:webdriver/src/handler/w3c_handler.dart
  package:webdriver/src/request/async_io_request_client.dart
  package:webdriver/src/sync/alert.dart
  package:webdriver/src/sync/common.dart
  package:webdriver/src/sync/common_stub.dart
  package:webdriver/src/sync/cookies.dart
  package:webdriver/src/sync/keyboard.dart
  package:webdriver/src/sync/logs.dart
  package:webdriver/src/sync/mouse.dart
  package:webdriver/src/sync/target_locator.dart
  package:webdriver/src/sync/timeouts.dart
  package:webdriver/src/sync/web_driver.dart
  package:webdriver/src/sync/web_element.dart
  package:webdriver/src/sync/window.dart
  package:webdriver/support/async.dart
  package:webdriver/sync_core.dart

**Comment by johngithubby** [comment]
BTW, I ran `dart pub outdated --mode=null-safety --transitive` above after running `dart migrate --skip-import-check`, I'm in the middle of migrating now.

**Comment by jonasfj** [comment]
quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by jonasfj** [comment]
By default `dart pub outdated --mode=null-safety` doesn't show null-safety compatible dependencies, hence, you won't see `flutter_driver`.

I'm guessing `flutter_driver` was migrated before its dependencies.
Indeed if you look at `package:flutter_driver/flutter_driver.dart` as shipped with Flutter 2.0.3, you'll see:

`// @dart = 2.8` meaning the file `flutter_driver.dart` is opting out of null-safety.

Hence, any code that imports `flutter_driver` in Flutter 2.0.3 cannot be fully migrated to null-safety.

From what I understand, `flutter_driver` is only used in test driving files... So you'll have to not migrate those files.

It looks like this is resolved in newer flutter versions, checking Flutter master.

**Comment by stereotype441** [comment]
> By default `dart pub outdated --mode=null-safety` doesn't show null-safety compatible dependencies, hence, you won't see `flutter_driver`.
> 
> I'm guessing `flutter_driver` was migrated before its dependencies.
> Indeed if you look at `package:flutter_driver/flutter_driver.dart` as shipped with Flutter 2.0.3, you'll see:
> 
> `// @dart = 2.8` meaning the file `flutter_driver.dart` is opting out of null-safety.
> 
> Hence, any code that imports `flutter_driver` in Flutter 2.0.3 cannot be fully migrated to null-safety.
> 
> From what I understand, `flutter_driver` is only used in test driving files... So you'll have to not migrate those files.
> 
> It looks like this is resolved in newer flutter versions, checking Flutter master.

Ok, given that this is resolved in newer flutter versions, I'm going to close this issue.
