### ISSUE TITLE
Problem while fetching dart repo stuck at 'running: gclient sync'

### ISSUE THREAD

**Issue by vaibhav135** [dart-lang/sdk#45364]
OS: Ubuntu 20.04LTS
Goal: To build the dart-SDK.
Instructions followed: `https://github.com/dart-lang/sdk/wiki/Building`

Problem: 
After executing fetch dart or fetch --nohooks dart. The result is stuck at gclient sync. I've waited for around 5 hours and still showing that the gclient sync is running.
After interrupting it the following message appears:

```
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://dart.googlesource.com/sdk.git /home/dev135/Downloads/OpenSource/dart-sdk/_gclient_sdk_bn93xeeb' in '/home/dev135/Downloads/OpenSource/dart-sdk'
Cloning into '/home/dev135/Downloads/OpenSource/dart-sdk/_gclient_sdk_bn93xeeb'...
```

Internet speed is fine. So the internet is not the problem.

**Comment by mraleph** [comment]
Try running this Git command in isolation `GIT_CURL_VERBOSE=1 GIT_TRANSFER_TRACE=1 GIT_TRACE=1 git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://dart.googlesource.com/sdk.git` and see what happens.

**Comment by vaibhav135** [comment]
@mraleph It says : "We are completely uploaded and fine"

**Comment by vaibhav135** [comment]
19:32:14.011165 git.c:439               trace: built-in: git clone --no-checkout --progress https://dart.googlesource.com/sdk.git
Cloning into 'sdk'...
19:32:14.014035 run-command.c:663       trace: run_command: git-remote-https origin https://dart.googlesource.com/sdk.git
* Couldn't find host dart.googlesource.com in the .netrc file; using defaults
*   Trying 74.125.68.82:443...
* TCP_NODELAY set
*   Trying 2404:6800:4003:c01::52:443...
* TCP_NODELAY set
* Immediate connect fail for 2404:6800:4003:c01::52: Network is unreachable
* Connected to dart.googlesource.com (74.125.68.82) port 443 (#0)
* found 391 certificates in /etc/ssl/certs
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.3 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.googlecode.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC/ECDSA
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=Mountain View,O=Google LLC,CN=*.googlecode.com
* 	 start date: Tue, 23 Feb 2021 15:41:08 GMT
* 	 expire date: Tue, 18 May 2021 15:41:07 GMT
* 	 issuer: C=US,O=Google Trust Services,CN=GTS CA 1O1
* ALPN, server accepted to use h2
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55687fe077f0)
> GET /sdk.git/info/refs?service=git-upload-pack HTTP/2
Host: dart.googlesource.com
user-agent: git/2.25.1
accept: */*
accept-encoding: deflate, gzip, br
accept-language: en-IN, en;q=0.9, *;q=0.8
pragma: no-cache

* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< cache-control: no-cache, max-age=0, must-revalidate
< content-encoding: gzip
< content-security-policy-report-only: script-src 'nonce-YeEwa+jCD9amzi+jk5pjEw' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval';object-src 'none';base-uri 'self';report-uri https://csp.withgoogle.com/csp/gerritcodereview/1
< content-type: application/x-git-upload-pack-advertisement
< expires: Fri, 01 Jan 1980 00:00:00 GMT
< pragma: no-cache
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 0
< date: Thu, 18 Mar 2021 14:02:15 GMT
< alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< 
* Connection #0 to host dart.googlesource.com left intact
19:32:18.432805 run-command.c:663       trace: run_command: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning https://dart.googlesource.com/sdk.git/
19:32:18.436910 git.c:439               trace: built-in: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning https://dart.googlesource.com/sdk.git/
* Couldn't find host dart.googlesource.com in the .netrc file; using defaults
* 17 bytes stray data read before trying h2 connection
* Found bundle for host dart.googlesource.com: 0x55687fe0dd30 [can multiplex]
* Re-using existing connection! (#0) with host dart.googlesource.com
* Connected to dart.googlesource.com (74.125.68.82) port 443 (#0)
* Using Stream ID: 3 (easy handle 0x55687fe077f0)
> POST /sdk.git/git-upload-pack HTTP/2
Host: dart.googlesource.com
user-agent: git/2.25.1
accept-encoding: deflate, gzip, br
content-type: application/x-git-upload-pack-request
accept: application/x-git-upload-pack-result
content-encoding: gzip
content-length: 44041

* We are completely uploaded and fine

< HTTP/2 499 
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< content-security-policy-report-only: script-src 'nonce-8Ncj47hVe/Nf/xxO53zqFw' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval';object-src 'none';base-uri 'self';report-uri https://csp.withgoogle.com/csp/gerritcodereview/1
< content-type: application/x-git-upload-pack-result
< date: Thu, 18 Mar 2021 14:12:19 GMT
< expires: Mon, 01 Jan 1990 00:00:00 GMT
< pragma: no-cache
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< x-errorid: 499, STHH-28,EPRRS-199,EPRRS-168,EPRRS-115,EPR-103,FHEH-39,GSI-278,GSI-124,GSI-161,RR-116;RSH-144,RIS-86,RIS-78,RIS-47,TTLFTDRTDSIS-272,UP-1073,UP-838,UPS-184,GGFUPPEH-368,UPS-201,UPC-211,RKITNF-43,UPC-209,UPSF-137,UPC-209,RF-112,UPC-209,NCF-53,UPC-209,UP-188,SP-70,MF-150,GGF-179,EBQCF-45,OGCWF-48,HMF-142,STQF-42,AF-178,AF-123,GFF-164,STSFSPSF-172,GFFFCW-265,GFFFCW-265,GFFFCW-265,GFFFCW-265,GFFFCW-265,GFFFCW-265,GFFFCW-265,STSFSPSF-172,GFFGAF-240,AF-119,SCZFI-168,CRF-89,SSF-25,GUUAF-116,MHF-106,EF-83,GAEF-72,GBLHCF-111,SCF-61,STSF-131,SF-54,TTLF-153,DF-170,DF-60,GSI-246,GSI-124,GSI-161,RR-116
< x-frame-options: SAMEORIGIN
< x-request-id: 1e2a1bafadb84423aa39205ac63036c4
< x-xss-protection: 0
< alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<

**Comment by vaibhav135** [comment]
It's still doing some stuff. By the way what is the size of the sdk.

**Comment by mraleph** [comment]
`sdk/.git` takes around 1G on disk, but that's just SDK repo. Full checkout would take at least 10G.

**Comment by vaibhav135** [comment]
By the now I am stuck at this:
```

19:32:14.011165 git.c:439               trace: built-in: git clone --no-checkout --progress https://dart.googlesource.com/sdk.git
Cloning into 'sdk'...
19:32:14.014035 run-command.c:663       trace: run_command: git-remote-https origin https://dart.googlesource.com/sdk.git
* Couldn't find host dart.googlesource.com in the .netrc file; using defaults
*   Trying 74.125.68.82:443...
* TCP_NODELAY set
*   Trying 2404:6800:4003:c01::52:443...
* TCP_NODELAY set
* Immediate connect fail for 2404:6800:4003:c01::52: Network is unreachable
* Connected to dart.googlesource.com (74.125.68.82) port 443 (#0)
* found 391 certificates in /etc/ssl/certs
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.3 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.googlecode.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC/ECDSA
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=Mountain View,O=Google LLC,CN=*.googlecode.com
* 	 start date: Tue, 23 Feb 2021 15:41:08 GMT
* 	 expire date: Tue, 18 May 2021 15:41:07 GMT
* 	 issuer: C=US,O=Google Trust Services,CN=GTS CA 1O1
* ALPN, server accepted to use h2
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55687fe077f0)
> GET /sdk.git/info/refs?service=git-upload-pack HTTP/2
Host: dart.googlesource.com
user-agent: git/2.25.1
accept: */*
accept-encoding: deflate, gzip, br
accept-language: en-IN, en;q=0.9, *;q=0.8
pragma: no-cache

* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< cache-control: no-cache, max-age=0, must-revalidate
< content-encoding: gzip
< content-security-policy-report-only: script-src 'nonce-YeEwa+jCD9amzi+jk5pjEw' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval';object-src 'none';base-uri 'self';report-uri https://csp.withgoogle.com/csp/gerritcodereview/1
< content-type: application/x-git-upload-pack-advertisement
< expires: Fri, 01 Jan 1980 00:00:00 GMT
< pragma: no-cache
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 0
< date: Thu, 18 Mar 2021 14:02:15 GMT
< alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< 
* Connection #0 to host dart.googlesource.com left intact
19:32:18.432805 run-command.c:663       trace: run_command: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning https://dart.googlesource.com/sdk.git/
19:32:18.436910 git.c:439               trace: built-in: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning https://dart.googlesource.com/sdk.git/
* Couldn't find host dart.googlesource.com in the .netrc file; using defaults
* 17 bytes stray data read before trying h2 connection
* Found bundle for host dart.googlesource.com: 0x55687fe0dd30 [can multiplex]
* Re-using existing connection! (#0) with host dart.googlesource.com
* Connected to dart.googlesource.com (74.125.68.82) port 443 (#0)
* Using Stream ID: 3 (easy handle 0x55687fe077f0)
> POST /sdk.git/git-upload-pack HTTP/2
Host: dart.googlesource.com
user-agent: git/2.25.1
accept-encoding: deflate, gzip, br
content-type: application/x-git-upload-pack-request
accept: application/x-git-upload-pack-result
content-encoding: gzip
content-length: 44041

* We are completely uploaded and fine

< HTTP/2 499 
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< content-security-policy-report-only: script-src 'nonce-8Ncj47hVe/Nf/xxO53zqFw' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval';object-src 'none';base-uri 'self';report-uri https://csp.withgoogle.com/csp/gerritcodereview/1
< content-type: application/x-git-upload-pack-result
< date: Thu, 18 Mar 2021 14:12:19 GMT
< expires: Mon, 01 Jan 1990 00:00:00 GMT
< pragma: no-cache
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< x-errorid: 499, STHH-28,EPRRS-199,EPRRS-168,EPRRS-115,EPR-103,FHEH-39,GSI-278,GSI-124,GSI-161,RR-116;RSH-144,RIS-86,RIS-78,RIS-47,TTLFTDRTDSIS-272,UP-1073,UP-838,UPS-184,GGFUPPEH-368,UPS-201,UPC-211,RKITNF-43,UPC-209,UPSF-137,UPC-209,RF-112,UPC-209,NCF-53,UPC-209,UP-188,SP-70,MF-150,GGF-179,EBQCF-45,OGCWF-48,HMF-142,STQF-42,AF-178,AF-123,GFF-164,STSFSPSF-172,GFFFCW-265,GFFFCW-265,GFFFCW-265,GFFFCW-265,GFFFCW-265,GFFFCW-265,GFFFCW-265,STSFSPSF-172,GFFGAF-240,AF-119,SCZFI-168,CRF-89,SSF-25,GUUAF-116,MHF-106,EF-83,GAEF-72,GBLHCF-111,SCF-61,STSF-131,SF-54,TTLF-153,DF-170,DF-60,GSI-246,GSI-124,GSI-161,RR-116
< x-frame-options: SAMEORIGIN
< x-request-id: 1e2a1bafadb84423aa39205ac63036c4
< x-xss-protection: 0
< alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< 



```

**Comment by vaibhav135** [comment]
@mraleph  Is there any way that I can build the sdk from the git repo although the build-guide suggests we cannot.

**Comment by mraleph** [comment]
Looking around indicates that there might be some problem with CURL handling of HTTP/2 connections. Try the following: 

```
$ git config --global http.version HTTP/1.1
```

Then run `fetch dart` again it should work.

**Comment by vaibhav135** [comment]
Ohh It seems like working Thanks. Once it completes I will inform you
Thank you so much.

**Comment by vaibhav135** [comment]
@mraleph Now I am getting this error message:


```
 ________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --auto_platform --extract --directory sdk/third_party/firefox_jsshell' in '/home/dev135/Downloads/OpenSource/dart-sdk'
/home/dev135/Downloads/OpenSource/depot_tools/download_from_google_storage: line 8: exec: python: not found
Error: Command 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --auto_platform --extract --directory sdk/third_party/firefox_jsshell' returned non-zero exit status 127 in /home/dev135/Downloads/OpenSource/dart-sdk

```

**Comment by mraleph** [comment]
You need `python` or more specifically python 2. See https://github.com/dart-lang/sdk/wiki/Building#python-2

**Comment by vaibhav135** [comment]
But I am actually running this is in python 2 venv

**Comment by vaibhav135** [comment]
This is the result of python --version 

```
~/Downloads/OpenSource/dart-sdk ❯ python --version                                                                                                                                  Py .env
Python 2.7.18
```

**Comment by mraleph** [comment]
I wonder if you have something in your `~/.bashrc` that breaks out of `venv`. What happens if you do 

```console
$ echo $PATH
$ bash
$ python --version
$ echo $PATH
```

**Comment by vaibhav135** [comment]
No worries worked after executing :
`sudo apt install python-minimal` seems like I didn't have python-minimal (= 2.7.11-1) and libpython-stdlib (= 2.7.11-1) which was necessary I guess
