### ISSUE TITLE
Migration tool exception when code contains an unreferenced part file

### ISSUE THREAD

**Issue by nstrelow** [dart-lang/sdk#45369]
Migration branch: https://github.com/parse-community/Parse-SDK-Flutter/pull/579

I have annotated a lot and now clicking migrate it just crashes. Restarted multiple times. Tried on MacOs and Windows.
Tried 2.12.2 (newest stable) and dev on Mac.

Could not apply migration

Error: NoSuchMethodError: The method 'hadDiskContent' was called on null.
Receiver: null
Tried calling: hadDiskContent("part of flutter_parse_sdk;\n\nabstract class AppInfo {\n  Future<String> getLanguage();\n\n  Future<String> getAppName();\n\n  Future<String> getPackageName();\n\n  Future<String> getVersion();\n\n  Future<String> getBuildNumber();\n}\n")

Stacktrace: _auto populated by migration preview tool._

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      PreviewSite.performApply (package:nnbd_migration/src/preview/preview_site.dart:501:35)
#2      PreviewSite.handlePostRequest (package:nnbd_migration/src/preview/preview_site.dart:449:9)
<asynchronous suspension>
#3      HttpPreviewServer._handlePostRequest (package:nnbd_migration/src/preview/http_preview_server.dart:109:5)
<asynchronous suspension>
#4      HttpPreviewServer._handleServer.<anonymous closure> (package:nnbd_migration/src/preview/http_preview_server.dart:119:9)
<asynchronous suspension>

```

EDIT: Works when using `dart migrate --apply-changes`!

### Env
**Dart**: 2.12.2 (macos, windows), 2.13.0-144.0.dev(macos, windows)
**Chrome**: Version 91.0.4449.6 (Official Build) dev (64-bit) Windows. (on mac it was the stable version).

**Comment by stereotype441** [comment]
I'm able to reproduce this.  Investigating now...

**Comment by stereotype441** [comment]
Aha, I see the problem!  The migration tool gets confused when it sees an unreferenced part file.  The file in question, `packages/dart/lib/src/data/app_info.dart` claims to be a part of `flutter_parse_sdk`, but the definition of that library (in `packages/dart/lib/parse_server_sdk.dart`) doesn't list it as a part file.

Downgrading priority since this is a pretty rare corner case, but I'll still try to get a fix out soon.

**Comment by nstrelow** [comment]
Uhh interesting. Will fix that then.

Pretty frustrating case though.

Since `dart migrate --apply-changes` was working , maybe it makes sense to add a disclaimer: "Please try it in cli as well"
Just for less frustration, if somebody has a similar issue.

**Comment by stereotype441** [comment]
> Uhh interesting. Will fix that then.
> 
> Pretty frustrating case though.
> 
> Since `dart migrate --apply-changes` was working , maybe it makes sense to add a disclaimer: "Please try it in cli as well"
> Just for less frustration, if somebody has a similar issue.

Yeah, if fixing the bug were difficult I would definitely consider this.  Fortunately the fix isn't too difficult.  I'm already most of the way through it :)
