### ISSUE TITLE
Mac BigSur - Flutter makes Mac OS extremely slow.

### ISSUE THREAD

**Issue by maheshkumar2150** [dart-lang/sdk#45363]
There is an issue already posted

https://github.com/Dart-Code/Dart-Code/issues/3005
But It was closed. So I have to post a new bug report.

Everything is good in Mac.

1. I open the terminal.
2. I open the simulator (open -a simulator)
3. I open the code (code .)
4. after I type flutter run

Then the problem starts.
Mac hangs a lot. Becomes very slow.

It was working good with previous version of Mac and flutter.
I upgraded both at the same time and I don't know which one is causing the problem.

**Comment by DanTup** [comment]
Could you post the full output of running:

- `flutter doctor -v`
- `code --status` (run this during the performance issue)

And can you also confirm when you're running `code .` to open Code, are you running this just in the folder for your project, or a large folder? If you're opening something like your home folder in VS Code, that can result in a lot of work for the analysis server.

**Comment by maheshkumar2150** [comment]
`[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/mahesh/DevLibrary/flutter_sdk/flutter
    • Framework revision c5a4b4029c (2 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/DevLibrary/android_sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 89.0.4389.90

`

using code . only for the project folder.

**Comment by DanTup** [comment]
@maheshkumar2150 can you also include the output of running `code --status` while the performance issues are occurring?

**Comment by maheshkumar2150** [comment]
> @maheshkumar2150 can you also include the output of running `code --status` while the performance issues are occurring? Thanks!

Okay

I was using android studio, android emulator, code and terminal along with safari.
There is no lag. Mac was doing good.

Now I closed android studio and emulator and opened apple simulator 
There is no problem with the performance.

I just hit the flutter run in terminal.

Version:          Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS Version:       Darwin x64 20.3.0
CPUs:             Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)
Memory (System):  8.00GB (1.08GB free)
Load (avg):       62, 32, 19
VM:               0%
Screen Reader:    no
Process Argv:     . --crash-reporter-id f0e784de-c0b6-466b-a5e8-864f29c4d637
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	    57	   895	code main
    4	    25	   898	   gpu-process
    0	    16	   900	   utility
    0	    49	   909	   shared-process
    0	    16	   910	     ptyHost
   12	   180	  4387	   window (Welcome — test_app)
    8	    82	  4390	     extensionHost
    0	    41	  4391	     watcherService
    0	    33	  4404	     searchService

Workspace Stats: 
|  Window (Welcome — test_app)
|    Folder (test_app): 137 files
|      File types: png(26) xml(12) json(4) plist(4) gitignore(3) gradle(3)
|                  properties(3) xcconfig(3) md(2) iml(2)
|      Conf files:

**Comment by DanTup** [comment]
@maheshkumar2150 to be clear - VS Code and Android Studio were _not_ open when you reproduced it above?

Does it only occur when running on the iOS Simulator? Can you check Activity Monitor and see how much CPU is being used by what processes and how much memory is used while it's happening?

**Comment by maheshkumar2150** [comment]
VS Code and Android Studio were open sir.
Today only I tried android studio and android emulator with VS Code.

I am facing this problem mostly or only with iso simulator
I will share the picture which I took yesterday during the performance issue.

**Comment by maheshkumar2150** [comment]
[https://discussions.apple.com/content/attachment/1a12d752-291c-439b-afe7-e80811430bbc](url)

**Comment by maheshkumar2150** [comment]
`Version:          Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS Version:       Darwin x64 20.3.0
CPUs:             Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)
Memory (System):  8.00GB (0.49GB free)
Load (avg):       8, 9, 7
VM:               0%
Screen Reader:    no
Process Argv:     . --crash-reporter-id f0e784de-c0b6-466b-a5e8-864f29c4d637
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    1	    57	   895	code main
    0	    16	   898	   gpu-process
    0	     8	   900	   utility
    0	    33	   909	   shared-process
    0	     8	   910	     ptyHost
    0	   115	  4550	   window (deep_link.dart — quiz_for_friends)
    0	    25	  4554	     extensionHost
    0	   205	  4567	       /Users/mahesh/DevLibrary/flutter_sdk/flutter/bin/cache/dart-sdk/bin/dart /Users/mahesh/DevLibrary/flutter_sdk/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.20.1
    0	     0	  4570	       bash /Users/mahesh/DevLibrary/flutter_sdk/flutter/bin/flutter daemon
    2	    57	  4587	         /Users/mahesh/DevLibrary/flutter_sdk/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/mahesh/DevLibrary/flutter_sdk/flutter/packages/flutter_tools/.packages /Users/mahesh/DevLibrary/flutter_sdk/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	  4646	           /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
    0	     0	  4647	             /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0	     0	  9576	           /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/Resources/bin/simctl list --json devices
    0	     0	  4610	       /Users/mahesh/DevLibrary/flutter_sdk/flutter/bin/cache/dart-sdk/bin/dart /Users/mahesh/DevLibrary/flutter_sdk/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot global run devtools --machine --try-ports 10 --allow-embedding
    0	     8	  4557	     watcherService

Workspace Stats: 
|  Window (deep_link.dart — test_app)
|    Folder (quiz_for_friends): 6894 files
|      File types: png(2474) h(686) jar(496) json(270) xml(201) jpg(126)
|                  m(104) flat(97) plist(90) class(68)
|      Conf files:
`

**Comment by DanTup** [comment]
@maheshkumar2150 if you create a new sample flutter app with `flutter create` and run that instead, do you see the same problem? Or does it only occur in one specific project?

**Comment by maheshkumar2150** [comment]
Just tested with empty newly created app. Same problem

**Comment by maheshkumar2150** [comment]
If I press ctrl + c, it becomes normal.
If I close the simulator, it becomes normal

**Comment by vsmenon** [comment]
I'm assigning this to `area-analyzer` based on the upstream ( https://github.com/Dart-Code/Dart-Code/issues/3005 ), but it's not clear they are related.

**Comment by DanTup** [comment]
I'm not sure this is analyzer related now either. From the screenshots above, it seems like the simulator is consuming a lot of the CPU. If it occurs in a newly created Flutter sample, it's probably nothing specific to the app so it maybe it's a Simulator/Xcode issue, or a Flutter issue.

@maheshkumar2150 does the same occur if you use an Android Emulator instead of the iOS Simulator?

**Comment by srawlins** [comment]
Yeah I don't see anything for the analyzer, based on the discussion and screenshot.

**Comment by MustafaYusef** [comment]
when I run a flutter project my mac becomes very slow even the browser .

**Comment by micimize** [comment]
I found today that [using the 6s simulator](https://stackoverflow.com/a/57937309/2234013) solves the issue almost entirely for me, although I did also run `xcrun simctl erase all` beforehand.

I don't think this is a flutter-specific issue as I have seen many threads on iOS simulator slowness elsewhere.

**Comment by srawlins** [comment]
As this seems pretty isolated to the simulator, I'm tentatively assigning this to VM team.

**Comment by a-siva** [comment]
This seems to be a pretty old issue,
@maheshkumar2150 are you still having slowness issues ?

I am going to mark this issue as stale. If you still have problems please reopen it.
