### ISSUE TITLE
[Analyzer] Dart code to AST

### ISSUE THREAD

**Issue by qcks** [dart-lang/sdk#45361]
* Analyzer*
I want to use analyzer to convert Dart code to AST, but I can't find the documentation (Google & github). Reading comments from its source code is very obscure.

**Comment by bwilkerson** [comment]
You can find the documentation for the package in the `doc` directory, as is typical for most packages, specifically under `tutorial` (https://github.com/dart-lang/sdk/tree/master/pkg/analyzer/doc/tutorial).

If you have additional questions you can either open an issue or use the mailing list at https://groups.google.com/a/dartlang.org/g/analyzer-discuss.

**Comment by qcks** [comment]
thanks
