### ISSUE TITLE
vm_snapshot_analysis package is preventing flutter from upgrading test deps.

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#45367]
package:vm_snapshot_analysis needs to be updated with the latest versions of several packages (specifically args) since there have been some major releases since it was last published. This is currently one of the packages constraining the Flutter SDK 

https://github.com/flutter/flutter/issues/77856

I tried to update the deps myself, but I noticed beforehand that many of the tests were already failing. I'm not sure if that is a known issue, or something caused by a different Dart update.

cc @kenzieschmoll @mraleph

**Comment by jonahwilliams** [comment]
oh, turns out I was on a bad revision. I'll open a PR

**Comment by kenzieschmoll** [comment]
published 0.6.0
