### ISSUE TITLE
Getting to know about dart-sdk (for begginer)

### ISSUE THREAD

**Issue by vaibhav135** [dart-lang/sdk#45379]
Hi,
I have recently build the dart-sdk and now I want to contribute to it but now I am totally confused, I have seen the Contributing.MD and also the issues but  I am confused with the directories as to where should I make the code changes. By the way, my motive here is to participate in GSoC 2021 with dart if possible. 
I have run some tests but all of them failed but up till now and I have no idea what I am doing. I know a fair amount of dart, c++ and I've also used flutter.
I would also like to know where I can ask my questions related to dart-sdk since this may not be the ideal way.
I would like to work on this [idea](https://github.com/dart-lang/sdk/wiki/Dart-GSoC-2021-Project-Ideas#idea-extends-git-source-in-pubspecyaml-to-understand-tags) but I don't know how exactly should I start. I would also like to know where can I get my knowledge regarding the directories and other stuff.
Thank you

**Comment by Enigma04** [comment]
I am having the same issue so if anyone can solve this doubt for us then it will be great! Though GSoC isn't the only goal I have to be honest. I am aiming to continue to support since I work on flutter for developing my apps so.

**Comment by mraleph** [comment]
I think the best is to use GSoC specific mailing list (https://groups.google.com/g/dart-gsoc). @jonasfj @dcharkes might suggest other possible approaches.

There is no document that describes SDK source tree structure. Different parts of the SDK use different workflows, etc. You need to work with the respective mentor to figure out where to start, e.g. if your project concerns `pubspec.yaml` format then you most likely going to be working on `pub` tool. `pub` source lives in a separate repo (https://github.com/dart-lang/pub) which gets pulled into `sdk/third_party/pkg/pub` in the overall SDK checkout.

**Comment by vaibhav135** [comment]
@mraleph  is there any way to contact the mentors because the mailing list https://groups.google.com/g/dart-gsoc is not helping much. Because someone just replied this:

> Hi Vaibhav,
> 
> The Dart SDK consists of a lot of different things. You can look at it as a collection of smaller components that work together
> but are independent of each other. I don't think there's any beginner-friendly way to approach the dart SDK because it's simply too vast.
> 
> So as a beginner, I'd recommend you to start with contributing to packages published by dart.dev or flutter.dev on pub. You can browse through
> issues and try to solve some.
> 

which really didn't help me much and by the looks of it, It seems like the mentors are not active in the group.
Please tell me if there is any way to ask the mentors for the directions.
Thank you

**Comment by mraleph** [comment]
@vaibhav135 mentors email is listed in the ideas page you have linked to. 

fwiw, I also linked you to the code of the `pub` tool which is the code base you would have to work on if you were to work on the idea you have linked to, as an exercise try looking around in that code. Where is `pubspec.yaml` parsed? Where is support for `git` dependencies implemented? How `pubspec.yaml` version constraints feed into version solver? etc. 

Try to answer these questions without asking a mentor for help. It's a very good exercise to develop an extremely important skill - jumping into unfamiliar code base and figuring things out.
