### ISSUE TITLE
Failures in compressed pointers mode.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#45383]
There are new test failures on [[vm, compiler] Convert binary Smi ops to graph intrinsics....Update the server protocol to support passing back the line and column numbers for the end of a range](https://github.com/dart-lang/sdk/compare/d00ef8611a79b44f18f854bb4e73b35bee1176f3~...051ec30ff04d98064305e94118f612d9a5c113b1).

The tests
```
vm/dart_2/deferred_loading_and_weak_serialization_references_test/0 Crash (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-simarm-crossword
dartkp-linux-debug-simarm64c
dartkp-linux-debug-x64c
dartkp-linux-release-simarm-crossword
```

There are new test failures on [Adding SDK dependencies required for expression evaluation tests....Reorganize language/nonfunction_type_aliases/mixed/aliased_cyclic*](https://github.com/dart-lang/sdk/compare/97e8837f12d09d8af2d35f736f976636bd1da12a~...e692b26c7ebe97a3fb79b94aaec5a9d810d30cee).

The tests
```
co19_2/LibTest/core/Uri/queryParametersAll_A01_t04 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-debug-x64c
```

Will approve those failures.

/cc @rmacnak-google @liamappelbe

**Comment by rmacnak-google** [comment]
This test is now passing with compressed pointers at top-of-tree.
