### ISSUE TITLE
standalone_2/io/large_file_read_small_file_test flaky -> Timeout on dartk-win-release-x64

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#45388]
CQ results: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-win-release-x64/15889/overview

**Comment by alexmarkov** [comment]
This test went from flaky to Timeout on dartk-win-debug-x64 as well.

**Comment by dcharkes** [comment]
Today again on release: https://dart-ci.appspot.com/log/vm-kernel-win-release-x64/dartk-win-release-x64/16719/standalone_2/io/large_file_read_small_file_test

**Comment by sstrickl** [comment]
Again today on release: https://dart-ci.appspot.com/log/vm-kernel-win-release-x64/dartk-win-release-x64/16933/standalone_2/io/large_file_read_small_file_test

**Comment by sstrickl** [comment]
Again today on debug: https://dart-ci.appspot.com/log/vm-kernel-win-debug-x64/dartk-win-debug-x64/13107/standalone_2/io/large_file_read_small_file_test

**Comment by alexmarkov** [comment]
Happened once again on dartk-win-release-x64: https://dart-ci.appspot.com/log/vm-kernel-win-release-x64/dartk-win-release-x64/17084/standalone_2/io/large_file_read_small_file_test.

**Comment by alexmarkov** [comment]
Somehow after the failure was approved it went `Timeout -> Pass` and then `Pass -> Timeout` again: https://dart-ci.appspot.com/log/vm-kernel-win-release-x64/dartk-win-release-x64/17101/standalone_2/io/large_file_read_small_file_test
