### ISSUE TITLE
Why is `Never` allowed by the analyzer pretty much anywhere?

### ISSUE THREAD

**Issue by SteveAlexander** [dart-lang/sdk#45399]
Dartpad in null safe mode, and the Analyzer in Dart 2.13.0-137.0.dev, both allow code like `var x = 1 + 2 + Never;`.

When it runs, there's an error like "Error: A value of type 'Type' can't be assigned to a variable of type 'num'."

Consider this code:

```dart
void main() {
  1 + 2 + String;
  1 + 2 + Object;
  1 + 2 + dynamic;
  1 + 2 + void;
  1 + 2 + Null;
  1 + 2 + Never;
}
```

The analyzer catches each of these, except `Never`.

![image](https://user-images.githubusercontent.com/4321921/111873263-c433f480-898f-11eb-8450-b0207c8e1fbb.png)

`Never` is a Type object, so why is it being analyzed like it's a value of type `Never` ?

I came across this with some code where the programmer was trying to use Never with streams where we care about the fact that a stream event occurred, but not about its value. In null safe Dart, adding `null` to a `Stream<String>` doesn't work. But, adding `Never` to it seems to... at least until you run it. This doesn't happen with any other Type as far as I can see.

Perhaps this is intentional for some esoteric reason? Or perhaps it's a mistake and `Never` is being treated like "instance of Never"?

![image](https://user-images.githubusercontent.com/4321921/111873578-3527dc00-8991-11eb-9c59-51335facc514.png)

**Comment by vsmenon** [comment]
This appears to be a bug in the analyzer.  The CFE (compiler front end) statically fails:

```
Error: A value of type 'Type' can't be assigned to a variable of type 'num'.
 - 'Type' is from 'dart:core'.
  print(1 + Never);
            ^
Error: Compilation failed.
```

**Comment by srawlins** [comment]
This is .... a bizarre bug. Good catch!

**Comment by lfkdsk** [comment]
simple identifier‘s default type is a dynamic type.  dynamicType <: other types.
`_resolve2` missing a branch for processing never type. But use `_typeProvider.neverType` is also the wrong way, because NeverType's Type should be type-Type, not neverType.


```
  void _resolve2(SimpleIdentifierImpl node) {
    var element = node.staticElement;

    if (element is ExtensionElement) {
      _setExtensionIdentifierType(node);
      return;
    }

    DartType staticType = DynamicTypeImpl.instance;
/// ...
```

**Comment by lfkdsk** [comment]
try to fix with : https://github.com/dart-lang/sdk/pull/45808
