### ISSUE TITLE
dart migrate exception

### ISSUE THREAD

**Issue by dmitrymozheyko** [dart-lang/sdk#45406]
SDK version (2.12.2)

`NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node at offset 3064 in /Users/dm/work/sit-co.ru/shattecustomermobile/sources/shatte_customer/lib/bloc_gallery/gallery.dart (ShatteApp?.logoImage)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:3014:47)
#2      EdgeBuilder.visitPropertyAccess (package:nnbd_migration/src/edge_builder.dart:1451:12)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8448:49)
#4      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#5      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#6      EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2934:7)
#7      EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1154:5)
#8      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#10     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#11     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2934:7)
#12     EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1154:5)
#13     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6130:15)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#16     EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1498:7)
#17     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8617:49)
#18     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#19     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#20     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#21     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#22     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#23     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#24     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#25     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#26     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#27     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#28     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#29     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2488:7)
#30     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#31     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#32     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#33     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#34     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#35     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#36     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#37     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#38     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#39     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#40     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#41     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#42     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#43     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#44     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#45     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#46     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#47     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#48     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#49     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#50     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#51     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#52     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#53     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#54     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#55     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>`

Code in this line is

`static final Widget logoImage = Image.asset('assets/images/shatte-logo.png',
      fit: BoxFit.cover, height: 32);`

**Comment by stereotype441** [comment]
@dmitrymozheyko thanks for the report!  Are you able to make progress by running the tool with the command-line argument `--ignore-exceptions`?

**Comment by dmitrymozheyko** [comment]
> @dmitrymozheyko thanks for the report! Are you able to make progress by running the tool with the command-line argument `--ignore-exceptions`?

I removed ? sign after class names in static members calls and migration completes succcesfully

**Comment by stereotype441** [comment]
> > @dmitrymozheyko thanks for the report! Are you able to make progress by running the tool with the command-line argument `--ignore-exceptions`?
> 
> I removed ? sign after class names in static members calls and migration completes succcesfully

Thanks!  That's a valuable clue.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
