### ISSUE TITLE
The default value of an optional parameter must be constant.

### ISSUE THREAD

**Issue by thinhhoangnguyen** [dart-lang/sdk#45407]
There's a problem going on in Dart 2.12. I have read the documentation very carefully and Dart said: "You can have required named parameters of nullable types, and optional named parameters of non-nullable types (if they have a default value)." And Dart doesn't mention that the default value of an optional parameter must be constant. And here's what I got:
![image](https://user-images.githubusercontent.com/35698467/111981442-46601c80-8b3a-11eb-8430-c38d873eb82d.png)

**Comment by eernstg** [comment]
Any default value for a formal parameter must be constant.

**Comment by thinhhoangnguyen** [comment]
> Any default value for a formal parameter must be constant.

How about this one
![image](https://user-images.githubusercontent.com/35698467/111982035-0cdbe100-8b3b-11eb-85cd-47eb47d67477.png)

**Comment by eernstg** [comment]
Are you referring to `this.id`? The default value for that parameter is the empty string literal, and that's a constant expression, so that's fine.

**Comment by thinhhoangnguyen** [comment]
> Any default value for a formal parameter must be constant according to the language specification: https://github.com/dart-lang/language/blob/afa278b0d3f5e77e721efdde3e2e34927976c475/specification/dartLangSpec.tex#L1942.
> 
> However, you may have noticed that this should be documented in some of the other (less formal) documents? The language tour does mention this in the section 'Default parameter values'.

Tks you
