### ISSUE TITLE
Analyzer fails to analyze/resolve mixin that implements class

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45411]
Moved from https://github.com/Dart-Code/Dart-Code/issues/3222.

The following (invalid) code:

```dart
class MyClass {
  set test(int i) => 0;
}

mixin MyMixin implements MyClass {
  void method() => super.test = ;
}
```

Fails to be properly parsed/resolved with the following exception occurring on a `!`:

<img width="1255" alt="Screenshot 2021-03-22 at 13 42 11" src="https://user-images.githubusercontent.com/1078012/111998993-74326a80-8b14-11eb-9981-481282baec6f.png">

The exception doesn't make it back to the user, but since there's no result for this file, causes "Invalid file" errors in the LSP when the editor sends requests for code completion/hovers/code actions/etc.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/192501
