### ISSUE TITLE
Failures on [ VM ] Ensure shared timeline objects are protected by locks

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#45412]
There are new test failures on [[ VM ] Ensure shared timeline objects are protected by locks](https://github.com/dart-lang/sdk/commit/a62e14488215128776db34a65e565df0b6559cac).

The tests
```
standalone_2/array_bounds_check_generalization_test Crash (expected Pass)
vm/cc/DartAPI_TimelineAsync Crash (expected Pass)
vm/cc/DartAPI_TimelineDuration Crash (expected Pass)
vm/cc/DartAPI_TimelineInstant Crash (expected Pass)
vm/cc/TimelinePauses_Basic Crash (expected Pass)
vm/cc/TimelinePauses_BeginEnd Crash (expected Pass)
```
are failing on configurations
```
dartk-tsan-linux-release-x64
dartkp-tsan-linux-release-x64
```

**Comment by bkonyi** [comment]
Reverted relevant changes (a62e14488215128776db34a65e565df0b6559cac and f06348108a9b2151001a830315b3ea98720f0c92).
