### ISSUE TITLE
Inconsistent flow graph construction with and without incremental kernel compiler

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#45421]
VM service test started failing on CL touching the VM service. cc @bkonyi 

There are new test failures on [[ VM / Service ] Add identityHashCode to @Instance and Instance](https://github.com/dart-lang/sdk/commit/3b49fd862ba243e3c9008734e64c2ec66239f75a).

The tests
```
service_2/get_allocation_samples_test/dds RuntimeError (expected Pass)
service_2/get_allocation_samples_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
app_jitk-linux-release-x64
```

**Comment by bkonyi** [comment]
I'll take a look. Would you mind posting a direct link to the logs next time though? It'll make my life easier :-)

**Comment by bkonyi** [comment]
Looks like it was just a flaky test starting to fail, so it's unrelated to the CL that happened to turn it red.

**Comment by rmacnak-google** [comment]
Different flow graphs are being constructed for unoptimized code in the training run and running from the snapshot.

```
BEFORE (from source)
runtime/observatory_2/tests/service_2/test_helper.dart__ServiceTesteeRunner@24180151_run__async_op (ClosureFunction)
...
>testee>err> t0 <- InstanceCall:84( dyn:call<0>, t0)
...

AFTER (from snapshot)
runtime/observatory_2/tests/service_2/test_helper.dart__ServiceTesteeRunner@24180151_run__async_op (ClosureFunction)
...
>testee>err> t1 <- LoadLocal(:t0 @-13)
>testee>err> t2 <- LoadLocal(:t0 @-13)
>testee>err> CheckNull:84(t2, NoSuchMethodError)
>testee>err> t2 <- LoadLocal(:t0 @-13)
>testee>err> t2 <- LoadField(t2 . Closure.function {final})
>testee>err> DebugStepCheck:86()
>testee>err> t1 <- ClosureCall:88( function=t2<0>, t1 using unchecked entrypoint)
>testee>err> t0 <- DropTemps(1, t1)
...
```

This is a problem because deoptimization relies on consistent assignment of deopt ids.

**Comment by rmacnak-google** [comment]
This is ultimately caused by https://github.com/dart-lang/sdk/issues/39302. In first run the program ran from source with the incremental compiler, in the second run the program ran from app-jit that was compiled with the non-incremental compiler. The former is missing call site metadata, so it compiles some closure calls differently.

@alexmarkov
