### ISSUE TITLE
[convert_patch.dart] _ChunkedJsonParser could use a typed list to keep track of its internal state?

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#45420]
This issue is about making the following list a typed list.

https://github.com/dart-lang/sdk/blob/64a8d2a8b8b85a6e3221ebbc80f36a7746045b4e/sdk/lib/_internal/vm/lib/convert_patch.dart#L423

There are just 2 methods that use it in the same file, and I assume that are the only ones using it:

https://github.com/dart-lang/sdk/blob/64a8d2a8b8b85a6e3221ebbc80f36a7746045b4e/sdk/lib/_internal/vm/lib/convert_patch.dart#L473-L488

I think this would benefit from using a Uint64List, together with an integer (in that same list) that tracks at what index the stack currently ends.

The current state could also be stored in that same list at index 0. 

(Not fully tested)
```dart
/*
  - The current parsing state is stored at index 0 
  - The current parse state stack index is stored at index 1 where
      • 1 means the parse state stack is empty
      • Anything > 1 is an index pointing into the parse state stack
  - index 2 and above are reserved for the parse state stack elements
*/
final Uint64List states = Uint64List(2)
  ..[0] = STATE_Initial
  ..[1] = 1;
int get state => states[0]; 
  
  // Grows to the exact size asked for.
  // Taken from https://github.com/dart-lang/sdk/blob/1055db533c655f9bf3f8f9e34f1e87ab415a26e6/sdk/lib/_internal/vm/lib/convert_patch.dart#L260-L266
  void ensureCapacity(int newCapacity) {
    if (newCapacity <= states.length) return;
    Uint64List newList = new Uint64List(newCapacity);
    newList.setRange(0, states.length, states, 0);
    states = newList;
  }
 
/// TODO don't pass in the state to the two calls to saveState.
  void saveState() {
    final newIndex = states[1] + 1;     
    ensureCapacity(newIndex);
    states[newIndex] = state;
    states[1] = newIndex;
  }

  /**
   * Restore a state pushed with [saveState].
   */
  /// TODO change the two assignments that call restoreState into simple calls to restoreState.
  void restoreState() {
    final currentState = states[1];
    if (currentState < 2) {
      // throw the same error that removeLast would throw.
    } else {
      states[0] = states[currentState] | VALUE_READ_BITS;
      states[1] = currentState - 1;
    }
  }
```

The states list would only have to be resized once for the whole parsing session and not on every call to restoreState and saveState.

If all usages of those parsers are like this, where the parser is left to be garbage collected,
https://github.com/dart-lang/sdk/blob/64a8d2a8b8b85a6e3221ebbc80f36a7746045b4e/sdk/lib/_internal/vm/lib/convert_patch.dart#L72-L79
then this should have the same peak memory for each parsing session with just a slightly higher average memory use, but with lower GC overhead since the integers wouldn't have to be boxed.

Do my assumptions sound correct and does this make sense?

---
Note: Does this comment also apply to typed lists?
https://github.com/dart-lang/sdk/blob/64a8d2a8b8b85a6e3221ebbc80f36a7746045b4e/sdk/lib/_internal/vm/lib/growable_array.dart#L354-L356

Note: It seems like this could also benefit from using the unsafe versions of [] and []= (especially in AOT) See: #45403

**Comment by mraleph** [comment]
> but with lower GC overhead since the integers wouldn't have to be boxed.

They are not really boxed, they are just tagged. Dart VM uses tagged pointers which can represent `kPointerSizeBits - 1`-bit integers (e.g. 31-bit on 32-bit platforms, 63-bit on 64-bit platforms) without boxing. I think only 5 bits are actually used in the state. 

Going to typed list _might_ be beneficial because it could potentially remove an indirection on accessing the backing store and also reduce the memory size (`Uint8List` would be enough). 

Note that `setRange` is a rather in-efficient operation right now, so we would have to fix that as well. 

This is really a micro-optimization though. I would expect that on large JSONs actually object creation matters considerably more than this, note that you only ever touch this array when entering/leaving objects and arrays.

**Comment by modulovalue** [comment]
Update: I will provide a benchmark once I can see any improvements.

**Comment by modulovalue** [comment]
My suggestions did not lead to any noteworthy performance improvements.
