### ISSUE TITLE
[convert_patch.dart] minCapacity < minCapacity never evaluates to true.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#45432]
Hello,

https://github.com/dart-lang/sdk/blob/9d1a307954e3e8d5c0b0444829dfb59251f9ed82/sdk/lib/_internal/vm/lib/convert_patch.dart#L254

I believe this will always evaluate to false.

**Comment by mraleph** [comment]
Good catch. It got broken during code review, original code said `if (minCapacity < kMinCapacity) return kMinCapacity;` but then `kMinCapacity` was renamed to match the code style.
