### ISSUE TITLE
Failures on [vm/compiler] Explicitly use near jumps in InstantiateTypeArgumentsInstr...[cfe] Compute variance for type parameters on duplicate typedefs

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#45445]
There are new test failures on [[vm/compiler] Explicitly use near jumps in InstantiateTypeArgumentsInstr...[cfe] Compute variance for type parameters on duplicate typedefs](https://github.com/dart-lang/sdk/compare/0de315c14649fbe15eb2576fa2040dd5fe3fb234~...2fa31c9dbdef5f70756e4e620ef430e78218eb1a).

The tests
```
vm/cc/TimelineAnalysis_ThreadBlockCount Crash (expected Pass)
vm/cc/TimelinePauses_Basic Crash (expected Pass)
vm/cc/TimelinePauses_BeginEnd Crash (expected Pass)
```
are failing on configurations
```
dartk-asan-linux-release-x64
```

Link to the [logs](https://dart-ci.appspot.com/log/vm-kernel-asan-linux-release-x64/dartk-asan-linux-release-x64/6286/vm/cc/TimelineAnalysis_ThreadBlockCount).

cc @bkonyi , since I'm guessing it might have been your CL that affected this.

**Comment by a-siva** [comment]
the timeline unit tests do not seem to have a way of setting the recorder (recorder_) in the Timeline class as a result of which the Timeline::Clear() method becomes a nop (recorder_ is null).

**Comment by bkonyi** [comment]
Yeah, this is related to my CL. I've done some refactoring of the tests so we properly actually override `Timeline::recorder()` consistently and perform the proper cleanup ([CL here](https://dart-review.googlesource.com/c/sdk/+/192960)).
