### ISSUE TITLE
Analyzer should trigger an error if enum comparison is used as const expression

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#45441]
With Dart 2.13.0 (build 2.13.0-150.0.dev) the analyzer accepts enum comparison in const expression though [enum comparisons are not yet allowed in asserts](https://github.com/dart-lang/language/issues/312).

```dart
enum E { a, b }
@immutable
class A {
  const A([E e = E.b]) : assert(e != E.a); // no diagnostic but there should be an `invalid_constant` error for `e != E.a`
}
void main() {
  const A(); // const_evaluation_throws_exception
}
```

/cc @scheglov @bwilkerson

**Comment by srawlins** [comment]
I've seen a few bugs about analyzer accepting code in assert initializers, I think also with a `!=` operation...

**Comment by eernstg** [comment]
It's on my TODO list to push on https://github.com/dart-lang/language/issues/1811, which would turn `e == E.a` and `e != E.a` into constant expressions (and indeed `e1 == e2` as well as `e1 != e2` for any `e1` that has primitive equality). So please don't rush to change the implemented behavior: It seems to be a step away from a behavior which is likely to be the specified behavior in the near future.
