### ISSUE TITLE
[meta] Update handling of type aliases expanding to a type variable

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45449]
The current implementation of the CFE and analyzer in some cases allow for using a type alias that expands to a type variable as a class:

```dart
typedef F<X> = X; // Standard example of a type alias that expands to a class.

class A {}
class B extends F<A> {} // Using F as a superinterface.
```

The language specification as updated in https://github.com/dart-lang/language/pull/1468 clarifies what it means for a type alias to expand to a type variable, and specifies that it is a compile-time error to use such a type alias as a class, and specifies what that means. This makes it an error in the above example to use `F<A>` as a superinterface, but the current implementations allow that.

It is also an error to use `F` in the following way, but that is already detected as an error by the current implementations (and it definitely should be an error):

```dart
typedef F<X> = X;
class C<X> extends F<X> {}
```

This issue is concerned with an implementation of the new rules.

**Comment by eernstg** [comment]
Test updates in https://dart-review.googlesource.com/c/sdk/+/192743.

**Comment by leafpetersen** [comment]
Can this be closed?
