### ISSUE TITLE
Analyzer: poor error message when using nonfunction type aliases without upgrading language version

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45459]
The following code is erroneous, since it attempts to use both the null safety and the nonfunction type alias features without moving to the 2.13 language version:

```dart
typedef A = int;
void main() {
  int? x;
}
```

The analyzer currently prints the following error messages for this code:

```
  error • Invalid generic function type. • /Users/leafp/tmp/test.dart:3:11 • invalid_generic_function_type
  error • This requires the 'non-nullable' language feature to be enabled. • /Users/leafp/tmp/test.dart:5:6 • experiment_not_enabled
```

I can see that in general it may be difficult to tell when a user has merely mistyped a typedef instead of attempted to use a nonfunction type alias, but I wonder whether we can possibly give more useful feedback here?  I'm concerned that users will attempt to use the feature without upgrading their language version, and will get no help from the resulting error message.  Perhaps at least ensuring that the "help" text accompanying this error mentions the possibility of a language version mismatch might help?

cc @bwilkerson @devoncarew @scheglov @eernstg

**Comment by eernstg** [comment]
At the place where the `invalid_generic_function_type` is emitted, perhaps the analyzer already parses a `<type>` rather than a `<functionType>`? In that case it might be useful (when the language version is below 2.13) to emit the message that `nonfunction-type-aliases` needs to be enabled, unless there is a syntax error.

**Comment by scheglov** [comment]
Yes, we have similar hints for other experiments.
I will update the parse to report such nudge for non-function typedefs as well.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/193100

**Comment by leafpetersen** [comment]
```
  error • This requires the 'nonfunction-type-aliases' language feature to be enabled. • /Users/leafp/tmp/test.dart:2:11 • experiment_not_enabled
```

👍
