### ISSUE TITLE
jsonDecode(data.body) returns Map instead of List for single json object

### ISSUE THREAD

**Issue by omerasif57** [dart-lang/sdk#45456]
**Background**: 
**For example:** 
This demo endpoint "https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY" return a SINGLE json object

**Limitation**:
while parsing above json `jsonDecode(data.body)` returns a Map (for single json object). I need to check type then encapsulate map to list then proceed ahead. 

**Desired**:
Adding a Map to a List is okay. But a List<Map> is desired here by default by `jsonDecode()`

**Question:**
Can we get an optional List<Map> object for Single Json Object with a single flag to `decode` method?

**Comment by natebosch** [comment]
I think decoding a `Map` is one of the most common use cases for `jsonDecode`. Adding a flag to the method for behavior that can be handled by the caller would add more complexity that it is worth, especially when the vast majority of users expect the current behavior.

`jsonDecode` will return whichever type is represented by the string you passed. `jsonDecode('{}')` will return a `Map`, `jsonDecode('[]')` a `List`, `jsonDecode('""')` a `String`, and `jsonDecode('1')` a number.

I'd recommend either doing the type check afterwards, or wrapping the string with `[` and `]` if you specifically want the `jsonDecode` call to produce the `List`.
