### ISSUE TITLE
[ffi] Allow C++ code to throw Exception and let Dart/Flutter catch it

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#45462]
Hi thanks for Flutter and Dart! I hope I can write c++ code that throws, say, `throw std::runtime_error("ouch")`. Then I hope the flutter code calling the c++ code (via ffi) can see the exception and catch it.

How can I do this? Thanks!

**Comment by mannprerak2** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/39140

**Comment by fzyzcjy** [comment]
@mannprerak2 So... there is no way to do it? :(

**Comment by mannprerak2** [comment]
Nope, you need to make error code part of the return value somehow, maybe wrap the return code in some struct which has the error code and the return value.

**Comment by mraleph** [comment]
I don't think it is duplicate of #39140 - that one is about throwing C++ exceptions over Dart frames (i.e. if you have a sandwich stack Dart -> C++ (a) -> Dart -> C++ (b) and inner C++ (b) throws exception then #39140 suggests it could be caught in C++ (b) and ignored by Dart altogether).

This one is about converting C++ exception into a Dart exception automatically on the boundary between Dart and C++. 

This can actually be made to work (at least in environments following Itanium C++ ABI) by providing custom personality routine for Dart trampolines. This is some gnarly stuff though and it is extremely hard to make it work across all platforms we support.

**Comment by fzyzcjy** [comment]
I am closing this issue, because I have later created my code generator (wrapped) https://github.com/fzyzcjy/flutter_rust_bridge, which eliminates the need to throw errors across boundaries - they will be simply converted automatically by the lib.

Thanks for the discussions!
