### ISSUE TITLE
CFE: No error message when using nonfunction type aliases with previous language versions

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45460]
The following code is erroneous, since it attempts to use the nonfunction type alias feature with a previous language version.  The CFE reports no error for this code currently.

```dart
// @dart = 2.12
typedef A = int;
void main() {}
```

cc @johnniwinther @stefantsov @eernstg

**Comment by johnniwinther** [comment]
I don't think this is exclusive to the nonfunction type aliases experiment, i.e. we currently don't enforce that unreleased experiments are only supported in the current sdk version.

**Comment by franklinyow** [comment]
Assigning to @johnniwinther, please reassign as you see fit

**Comment by leafpetersen** [comment]
> we currently don't enforce that unreleased experiments are only supported in the current sdk version.

Note that at least in this case I don't think this has to do with it being an unreleased experiment.  With [this cl](https://dart-review.googlesource.com/c/sdk/+/192948) which enables the experiment by default, if I run the following program (without specifying any experiment flags):

```dart
// @dart=2.6

typedef A = int;

void main() {
  A? a;
}
```

I get the following output:

```
../../../tmp/test.dart:6:4: Error: Null safety features are disabled for this library.
Try removing the `@dart=` annotation or setting the language version to 2.12 or higher.
  A? a;
   ^
../../../tmp/test.dart:1:1: Context: This is the annotation that opts out this library from null safety features.
// @dart=2.6
^^^^^^^^^^^^
```

The CFE is correctly rejecting the use of nullability features in a Dart 2.6 file, but is allowing nonfunction type aliases to be used.

**Comment by johnniwinther** [comment]
Created https://dart-review.googlesource.com/c/sdk/+/193480
