### ISSUE TITLE
CastMap does an invalid cast on 'remove'

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/sdk#45473]
**STR:**
```
  final foo = json.decode('{}').cast<String, Object>();
  foo.remove('akey');
```

https://github.com/dart-lang/sdk/blob/d44457f79d087b52a0468609d44013e5fd9f09f0/sdk/lib/internal/cast.dart#L280 is incorrect, since `remove` returns a nullable value even if the value type is non-null.

**Comment by stuartmorgan** [comment]
This is causing issues for the very popular `shared_preferences` plugin on Linux and Windows, so ideally we would cherry-pick a fix for this to stable. (If that's not feasible, we can work around it in the plugin, but I don't think that plugin is going to be the only thing to hit this.)

**Comment by devoncarew** [comment]
cc @lrhn

**Comment by stuartmorgan** [comment]
@lrhn Is it possible to cherry-pick this since it's a very straightforward fix?

**Comment by lrhn** [comment]
Shouldn't be a problem. Not sure where we are in release cycles right now, but if it's cherry-pick season, it would be nice to get it in.
