### ISSUE TITLE
FieldFormalParameter.type is null for initializing formals

### ISSUE THREAD

**Issue by shuoch-g** [dart-lang/sdk#45476]
**Detail**

Here is code to reproduce this issue:
```
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:analyzer/dart/ast/ast.dart';

void main() {
  final root = parseString(content: '''
class MyClass {
  MyClass(String this.a, this.b, {this.c});

  final String a;
  final String b;
  final String c;
}
''').unit;

  final visitor = _Visitor();
  root.accept(visitor);
}

class _Visitor extends GeneralizingAstVisitor<void> {
  @override
  void visitFieldFormalParameter(FieldFormalParameter node) {
    print('paramter: $node');
    print('parameter type: ${node.type}');
  }
}
```

The output is

```
paramter: String this.a
parameter type: String
paramter: this.b
parameter type: null
paramter: this.c
parameter type: null
```

As you can see, for initializing formals the type annotation is null. Given the comment on `FieldFormalParameter` syntax

```
///    fieldFormalParameter ::=
///        ('final' [TypeAnnotation] | 'const' [TypeAnnotation] | 'var' | [TypeAnnotation])?
///        'this' '.' [SimpleIdentifier] ([TypeParameterList]? [FormalParameterList])?
```

This seems intended, but I wonder if there is any way I can get the type information **without resolving its element** ?

Thanks !

**Comment by devoncarew** [comment]
cc @scheglov @bwilkerson for the API question

**Comment by bwilkerson** [comment]
> ... I wonder if there is any way I can get the type information without resolving its element ?

No. The getter `FieldFormalParameter.type` returns the AST node for the type annotation. This corresponds to the syntactic structure of the code. If no type annotation appears in the code, then it returns `null`.

To get type information you need to get a resolved AST and use the element/type model. You can access the element model via `FormalParameter.declaredElement`.

**Comment by scheglov** [comment]
Note also that `FieldFormalParameter.type` is AST, not a `DartType` instance, e.g. not `InterfaceType` instance that corresponds to `String` in `String a;`. If just such low-level information is enough for you, you might get similar level by looking yourself into the enclosing class for a field named `c`, and taking its enclosing `VariableDeclarationList.type`. It will work in most cases, except when the field type was inferred from a super-type. For example, here the type of `var f;` is `int`, because it is inherited from `A.f`. Correspondingly, the type of `this.f` is `int`.

```dart
abstract class A {
  int get f;
}

class B extends A {
  var f;
  B(this.f);
}
```

**Comment by shuoch-g** [comment]
Thanks! This issue can be closed, just want to say thank you to all.

I ended up getting a resolved AST, and I believe Konstantin's comment is also feasible, I might give it a try if I cannot resolve the unit.

Thank you all !
