### ISSUE TITLE
[dartdevc] Mark root library in ddc debug metadata

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#45479]
Currently debugger is trying to take a guess (and sometimes fails) at the root library of the app:

https://github.com/dart-lang/sdk/issues/44760

Can DDC infer what library contains the main and mark that library as the rootlib in the metadata?

**Comment by nshahan** [comment]
DDC could probably track if a library contains a top level method named main but no way to know for sure if that is the actual entry point for the application being loaded.

**Comment by annagrin** [comment]
Closing this one as impossible for ddc - we probably should store it in some app-level metadata that can be generated by the builds.
