### ISSUE TITLE
Migrator incorrectly adds `as Future<T>` to `Future<T?>`

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/sdk#45472]
**STR:**

- Write the following:
  ```
  String foo;

  Future<String> getNullableFoo() async {
    return foo;
  }
  
  Future<String/*!*/> getFoo() {
    return getNullableFoo();
  }
  ```
- Run `dart migrate`

**Expected results:**
```
String? foo;

Future<String?> getNullableFoo() async {
  return foo;
}
  
Future<String> getFoo() async {
  return (await getNullableFoo())!;
}
```
(Or something equivalent, but that's the way we've been manually fixing this case.)

**Actual results:**
```
String? foo;

Future<String?>  getNullableFoo() async {
  return foo;
}

Future<String/*!*/>  getFoo() {
  return getNullableFoo() as Future<String>;
}
```

That code will crash at runtime with "type 'Future<T?>' is not a subtype of type 'Future<T>' in type cast" (regardless of the value of `foo` at the time), so the migration tool should not suggest it.

(This case as written is contrived and probably seems absurd, but is based on a use case that's not uncommon in Flutter plugins: the framework provides `Future<T?> invokeMethod<T>` for communicating over platform channels with native code. Since we're crossing language boundaries sound nullability can't be guaranteed, but a plugin author can know that they will never return null from the native code and thus want to cast away the nullability.)

**Comment by stereotype441** [comment]
@stuartmorgan unfortunately changing a sync method to async is probably not something the migration tool can feasibly do (it's trivial to see in your example that it's safe, but in general it could affect execution timing in some pretty unsafe ways).

I could see the migration tool generating something like this though:
```dart
String? foo;

Future<String?> getNullableFoo() async {
  return foo;
}

Future<String/*!*/> getFoo() {
  return getNullableFoo().then((value) => value!);
}
```
How would you feel about that approach?

**Comment by stuartmorgan** [comment]
Seems reasonable; I'm not attached to the specific output I gave. I should probably just have put "Something that doesn't fail at runtime 100% of the time" as the expected results 🙂

**Comment by stereotype441** [comment]
Sounds good.  I'll see what I can do
