### ISSUE TITLE
[dart-migration] un-migrate files from null-safety?

### ISSUE THREAD

**Issue by johngithubby** [dart-lang/sdk#45482]
How do I un-migrate files from null-safety? When I was migrating my flutter project, I unchecked the test directory where I kept my tests (test), but the migration web page must have been reloaded and the checkmark was back on when I applied the migration.

Flutter_driver is not migrated yet, so I'm getting messages like this one:

{

> 
> 	"resource": "/Users/asdasd/appsauuad/test_driver/features/common/date_header_page.dart",
> 	"owner": "dart",
> 	"code": "import_of_legacy_library_into_null_safe",
> 	"severity": 2,
> 	"message": "The library 'package:flutter_driver/flutter_driver.dart' is legacy, and should not be imported into a null safe library.\nTry migrating the imported library.",
> 	"source": "dart",
> 	"startLineNumber": 1,
> 	"startColumn": 8,
> 	"endLineNumber": 1,
> 	"endColumn": 52,
> 	"tags": []
> }

Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (7 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

**Comment by lrhn** [comment]
The easiest approach would normally be to check the old version of the files out from source control.
For `git` that would be something like `git checkout pre-migration-branch test/`.

You'll then have to go through the reverted files and manually add a `//@dart=2.9` marker to each Dart file that is not migrated.

**Comment by johngithubby** [comment]
thank you @lrhn
