### ISSUE TITLE
[dartanalyzer] cannot find files if multiple directories are provided

### ISSUE THREAD

**Issue by axel-op** [dart-lang/sdk#45488]
The `dartanalyzer` command cannot work if multiple directories are provided in arguments.

* Dart SDK Version: 2.13.0-116.0.dev 
* OS: Windows, Linux (haven't tested on MacOS)

```cmd
> dartanalyzer bin lib
Analyzing lib, bin...
No dart files found at: [...]\bin

> dartanalyzer bin lib tool
Analyzing bin, lib, tool...
No dart files found at: [...]\lib
```

**Comment by nex3** [comment]
This is a pretty disruptive breaking bug; `dartanalyzer lib test` is a common invocation in CLI-based workflows. Can we increase the priority?

**Comment by srawlins** [comment]
This appears to be working with the replacement command, `dart analyze`.
