### ISSUE TITLE
Failures on [co19] skip test that uses dart:mirrors on precompiled and web platforms

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45484]
There are new test failures on [[co19] skip test that uses dart:mirrors on precompiled and web platforms](https://github.com/dart-lang/sdk/commit/dac02ba37ac5a9278d7520cfae78ac4e3f7b4ad9).

The tests
```
pkg/dev_compiler/test/expression_compiler/expression_compiler_test Timeout (expected Pass)
pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux
```

**Comment by sigmundch** [comment]
sounds like these tests are timing out flakily but not reaching the threshold of the bot infrastructure to be considered flaky.

@annagrin @Markzipan - it may be necessary to extend the default limit, or to split the test in several sub tests to stay within the timeout limit.

**Comment by Markzipan** [comment]
I'm currently porting the vast majority of of those tests to the e2e test suite. I can delete these tests from the regular suite, then split the ported tests if those grow too large.

**Comment by annagrin** [comment]
@aam could you please share a link to failures - I couldn't find them on that CL.

**Comment by aam** [comment]
@annagrin here you go: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-linux-debug/10144/overview

**Comment by alexmarkov** [comment]
`pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test` turned flaky -> Timeout on `pkg-win-release` bot.

Log: https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/17883/pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test

This test is consistently timing out on pkg-linux-debug and pkg-win-release. It's flaky on pkg-linux-release and pkg-mac-release.

**Comment by annagrin** [comment]
@Markzipan looks like the expression compiler worker testes are flaky again - would you be able to investigate?

**Comment by annagrin** [comment]
I could not repro a hang on my linux and windows machine, but from the logs it looks like the tests just take about 4 min so they could be just timing out.

**Comment by Markzipan** [comment]
@annagrin My bad, just saw this. I resolved this for the e2e tests by splitting them across module systems.  That should suffice for fixing these timeouts a well (since it seems we're testing AMD and DDC together).

**Comment by annagrin** [comment]
@Markzipan thanks!

**Comment by annagrin** [comment]
fix pending in https://dart-review.googlesource.com/c/sdk/+/213734
