### ISSUE TITLE
[analyzer] Repeated superinterface not detected via type alias

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45489]
The `implements` clause of a class cannot have [the same type twice](https://github.com/dart-lang/language/blob/3500b68861bca9200339921dac35d8d8f55d1873/specification/dartLangSpec.tex#L4465).

However, the analyzer does not report that error for the following program:

```dart
class B {}
typedef T = B;
class C implements B, T {}

void main() {}
```

**Comment by eernstg** [comment]
Here is another instance of the same issue:

```
class C {}
typedef CAlias = C;

mixin CM on C, CAlias {}
```

This is an error because `CM` has a repeated occurrence of a term denoting the type `C` in its `on` type list, and [that's an error](https://github.com/dart-lang/language/blob/3500b68861bca9200339921dac35d8d8f55d1873/specification/dartLangSpec.tex#L5322).

**Comment by eernstg** [comment]
Note that the case where the conflict arises because of an `on` type list in a mixin is also reported as https://github.com/dart-lang/sdk/issues/45505.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/193451
