### ISSUE TITLE
Tests for upcoming features are being skipped on the analyzer

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45481]
There are a huge quantity of co19 nonfunction type alias tests that appear to be being skipped, with a reference to `github.com/dart-lang/language/issues/115`

Examples:

```
LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/dynamic/*: Skip # github.com/dart-lang/language/issues/115
LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/*: Skip # github.com/dart-lang/language/issues/115
```

@eernstg @athomas Is this intentional?  Unless there's something I'm missing here, we should be unskipping this ASAP.  Do we need to audit the status files for other skips here?

**Comment by leafpetersen** [comment]
cc @scheglov

**Comment by eernstg** [comment]
The issue/115 skips are removed in https://dart-review.googlesource.com/c/sdk/+/192930.

**Comment by sgrekhov** [comment]
@eernstg please see https://dart-review.googlesource.com/c/sdk/+/193402

**Comment by leafpetersen** [comment]
This is fixed.
