### ISSUE TITLE
i-2-b: Dart and analyzer behaves in the different way for non-function typedef variable.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45487]
Dart SDK version: 2.13.0-161.0.dev (dev) (Mon Mar 22 19:57:50 2021 -0700) on "windows_x64"

Here is a source code example which passes with dart and throws a compile time error with analyzer:
``` dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => <Y extends X>() {};

class C<X> {}
typedef A<X extends C<X>> = C<X?>;

test(A source) {
  var fsource = toF(source);
  F<A<C<dynamic>?>> target  = fsource;
}

main() {}
```
Both tools should behave in the similar way.

Sample output is: 
```
$> dart --enable-experiment=nonfunction-type-aliases test.dart

$> dartanalyzer --enable-experiment=nonfunction-type-aliases test.dart
Analyzing test.dart...
  error - 'C<Never>?' doesn't conform to the bound 'C<C<Never>?>' of the type parameter 'X'. - test.dart:9:7 - type_argument_not_matching_bounds
  hint - The value of the local variable 'target' isn't used. - test.dart:9:21 - unused_local_variable
1 error and 1 hint found.
```

**Comment by eernstg** [comment]
`A<C<dynamic>?>` is not well-bounded and an error should be emitted.

**Comment by stefantsov** [comment]
This issue was addressed by https://dart-review.googlesource.com/c/sdk/+/192146, but the fix was reverted. The re-landing of the fix should resolve this issue.

**Comment by stefantsov** [comment]
I'm working on the reland at https://dart-review.googlesource.com/c/sdk/+/193401.
