### ISSUE TITLE
Failures on [vm/compiler] Change when parents of local functions are retained.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45483]
There are new test failures on [[vm/compiler] Change when parents of local functions are retained.](https://github.com/dart-lang/sdk/commit/bf74cad4775af085b7cfba829a0a1c23208c5586).

The tests
```
pkg/vm_snapshot_analysis/test/instruction_sizes_test RuntimeError (expected Pass)
```
are failing on configurations

[unittest-asserts-release-mac](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8851781495415641936/+/steps/test_results/0/logs/new_test_failures__logs_/0)

```
 'package:vm_snapshot_analysis/v8_profile.dart': Failed assertion: line 470 pos 12: 'parent != null': Trying to create node of type NodeType.functionNode with <anonymous closure @170> and no parent.
```

cc @sstrickl

**Comment by sstrickl** [comment]
Ah, yep, I'll need to look into how artificial nodes are added for WSRed owners and do the same for parent functions in ClosureData. Looking into that now.

**Comment by sstrickl** [comment]
Will be fixed once https://dart-review.googlesource.com/c/sdk/+/193303 lands.
