### ISSUE TITLE
feedback on experience with the Dart migration tool

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#45497]
After having done several migration of packages now, I started with migrating my main app some days ago. As it is a quite big app, I couldn't do the whole migration in one step, which is supported by the tool what is really a great future. Though it has some unexpected behaviour.

If use code generation in your project and your press "apply migration", the tool will insert a language constraint in all the non-migrated files. Unfortunately it forgets to do this in any generated file. Which makes the project no longer compilable.

When continuing the migration, the migration tool unfortunately selects all files and not just those that haven't had a language constraint. Which means I have to deselect all files that I don't want to have migrated now. In the same context it would be really helpful if there were a select all and deselect all buttons because if the project is big it takes a lot of time to unselect all files at the beginning of the migration.

Also please, at a button to insert late hints.

Overall the tool makes a much more polished impression than in the beginning. I experienced sometimes an arrow that it couldn't load the file after change, but pressing reload staff that always.

Thanks a lot for this tool, it's a huge time saver.

**Comment by escamoteur** [comment]
@mit-mit @leafpetersen in case you haven't seen this

**Comment by leafpetersen** [comment]
Thanks for the feedback!  cc @devoncarew @srawlins @stereotype441 for the UI suggestions.

**Comment by escamoteur** [comment]
I just realized, when you rerun from source, it will select all files again even if you manually deselected almost all of them :-(

I think a 'Apply migration for this file` would be really helful when doing a migration step by step

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
