### ISSUE TITLE
[meta] Type alias regular-boundedness not checked

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45491]
Consider the following program:

```dart
class A<X extends A<X>> {}
typedef AAlias<X> = A;
void main() {}
```

This program has an error at the declaration of `AAlias`, because it is not true that the body of the type alias is a regular-bounded type when the type arguments satisfy their bounds (cf. [this rule](https://github.com/dart-lang/language/blob/3500b68861bca9200339921dac35d8d8f55d1873/specification/dartLangSpec.tex#L19582)).

Both the analyzer and the cfe accept the above program with no errors, as of commit a7b0f5108d2938f03eda39bdd72e05135f07d76f.

**Comment by stefantsov** [comment]
I'm working on a fix for that at https://dart-review.googlesource.com/c/sdk/+/193662.
