### ISSUE TITLE
Migrate analysis_server_client to null safety

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#45500]
`pkg/analyzer_plugin/tool/spec/generate_all.dart` generates into it, but we cannot update it yet.

**Comment by AlexeyBukin** [comment]
Any updates?

**Comment by srawlins** [comment]
CC @bwilkerson

**Comment by devoncarew** [comment]
I believe this is now complete.

**Comment by devoncarew** [comment]
Heads up that we are considering discontinuing the package; that's tracked here: https://github.com/dart-lang/sdk/issues/50262. It would be great to hear about the use cases for people using `package: analysis_server_client`.
