### ISSUE TITLE
[analyzer/ffi] Inline array const lengths

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#45507]
The following code is accepted by the dart runtime, but rejected by the analyzer.

```dart
const EIGHT = 8;

class Struct8BytesInlineArrayInt extends Struct {
  @Array(EIGHT)
  external Array<Uint8> a0;
}
```

The ffi_verifier expects an int or int list expression here. Instead, we should evaluate the annotation to a const, so that referenced consts are inlined.

@timsneath thanks for reporting.

**Comment by dcharkes** [comment]
```dart
  void _validateSizeOfAnnotation(AstNode errorNode,
      NodeList<Annotation> annotations, int arrayDimensions) {

    // ...
    final x = annotation.elementAnnotation?.computeConstantValue();
    print(x?.hasKnownValue); // false.
```

@bwilkerson Contrary to the implementation of `@Packed(1)` in `_validatePackedAnnotation`, the annotations found in `_validateSizeOfAnnotation` do not have a known value. Is this due to using redirecting const factory constructors (from `Array` to `_ArraySize`)?

**Comment by bwilkerson** [comment]
Based on off-thread discussions, it sounds like analyzer can't compute an actual value because some of the values it needs are in patch files, and it doesn't know how to read patch files. (There might also be a bug around `external` declarations, but that has yet to be confirmed.)
