### ISSUE TITLE
Null safety: null checks on class fields not taken into accounts at compilation/analysis time

### ISSUE THREAD

**Issue by emembrives** [dart-lang/sdk#45503]
Hello,
With Dart 2.13.0 (Linux, through Flutter), as well as the online editor on the https://dart.dev/#try-dart website, my code produces a null safety related error that I think should not be here:
```
class NullSafetyError {
  final String? fieldStr;
  
  NullSafetyError(this.fieldStr);
  
  String strOr(String def) {
    if (fieldStr == null) {
      return def;
    }
    return fieldStr;
  }
}
```
`return fieldStr;` triggers the following error: `A value of type 'String?' can't be returned from the method 'strOr' because it has a return type of 'String'.`. However, the `if` should have told the compiler/analyser that the return is safe.

It seems that null checks on fields are not taken into account by the compiler. If I transform `fieldStr` into a local variable (adding `final fieldStr = this.fieldStr` as the first line of `strOr`), the error disappears.

**Comment by eernstg** [comment]
This is working as specified, but note that there is a lot of discussion about this topic [here](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion).
