### ISSUE TITLE
Adjust ddc to consider that private classes can escape via typedefs

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#45512]
Since all fields in Dart can be overriden, DDC conservatively generates fields as virtual properties unless it can prove that the field will not be overriden.

Currently it tries to determine if a class is private and will not be overriden. The logic for this takes into consideration local subclasses. See `_extensiblePrivateClasses`, for example: https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/kernel/property_model.dart#L46

This needs to be updated to take into consideration the recently added non-function type aliases.

**Comment by sigmundch** [comment]
@johnniwinther - I figure that non-function type aliases are lowered and eliminated by the CFE in most kernel code. However, in order to support modular compilation, I assume you need to represent in kernel somehow the presence of these aliases. Are those represneted in `Library.typedefs`? What is the recommended way for a backend to detect whether a class was exposed? Do we need to walk through all typedefs, or will classes be annotated somehow?

**Comment by johnniwinther** [comment]
You'll need to walk the typedefs declarations of the library.
