### ISSUE TITLE
ffi_2/function_callbacks_test failures

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#45510]
Following tests fail after https://github.com/dart-lang/sdk/commit/05ff52692fc2e77862f9a4f034070dfadcf5a04e

ffi_2/function_callbacks_test/0
ffi_2/function_callbacks_test/1
ffi_2/function_callbacks_test/2
ffi_2/function_callbacks_test/3
ffi_2/function_callbacks_test/4
ffi_2/function_callbacks_test/5
ffi_2/function_callbacks_test/6
ffi_2/function_callbacks_test/7
ffi_2/function_callbacks_test/8

```
--- Command "vm_compile_to_kernel" (took 01.000934s):
DART_CONFIGURATION=ProductX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ProductX64/vm_platform_strong.dill -o /b/s/w/ir/out/ProductX64/generated_compilations/dartkp-dwarf-linux-product-x64/tests_ffi_2_function_callbacks_test/out.dill /b/s/w/ir/tests/ffi_2/function_callbacks_test.dart --packages=/b/s/w/ir/.packages -Ddart.vm.product=true

exit code:
0

--- Command "precompiler" (took 02.000602s):
DART_CONFIGURATION=ProductX64 out/ProductX64/gen_snapshot --snapshot-kind=app-aot-elf --elf=/b/s/w/ir/out/ProductX64/generated_compilations/dartkp-dwarf-linux-product-x64/tests_ffi_2_function_callbacks_test/out.aotsnapshot --loading-unit-manifest=/b/s/w/ir/out/ProductX64/generated_compilations/dartkp-dwarf-linux-product-x64/tests_ffi_2_function_callbacks_test/ignored.json --enable-testing-pragmas --dwarf_stack_traces --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ProductX64/generated_compilations/dartkp-dwarf-linux-product-x64/tests_ffi_2_function_callbacks_test/out.dill

exit code:
-6

stderr:
Unexpected object (Class with illegal cid, full-aot): 0x7f7873882ca1 Library:'file:///b/s/w/ir/tests/ffi_2/function_callbacks_test.dart' Class: Foo

--- Re-run this test:
python tools/test.py -n dartkp-dwarf-linux-product-x64 ffi_2/function_callbacks_test/0
```

**Comment by dcharkes** [comment]
Discussion last week:

> Yeah, a class containing a static method was added, and the tearoff of the static method is passed to a function
> 
> I mean, a quick fix would be to just @pragma("vm:entry-point") the class or method, I think, but that shouldn't be a case where the class should get shaken out and hence why I'm curious

> Yes, I added that test to exercise the behavior of callbacks to static methods in classes instead of top level methods
> 
> The special CFE sauce wiring up everything might not do the appropriate changes to make sure the class is retained.
> 
> Feel free to just file an issue and approve, and I'll get to it next week.

I'll investigate the CFE sauce.
