### ISSUE TITLE
Analyzer does not throw a compile error for a constructor of the raw type which is not well-bounded.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45522]
Dart SDK version: 2.13.0-165.0.dev (dev) (Thu Mar 25 02:53:52 2021 -0700) on "windows_x64"

Here is a code source example which calls a constructor of the raw type which is not well bounded:
``` dart
class C<X> {}
typedef G<X> = X Function(X);
typedef A<X extends G<C<X>>> = C<X>;

main() {
  A();
}
```
Seems like a compile error should be thrown here, however this does not happen, both analyzer passes without error here.

Similar dart issue which throws a compile error with analyzer and passes with dart is discussed in [45519](https://github.com/dart-lang/sdk/issues/45519).

This is also discussed in [co19 issue 1050](https://github.com/dart-lang/co19/issues/1050).

Sample output is:
```
$> dartanalyzer --enable-experiment=nonfunction-type-aliases test.dart 
Analyzing test.dart...
No issues found!

$> dart --enable-experiment=nonfunction-type-aliases test.dart 
$>
```

**Comment by scheglov** [comment]
[This CL](https://dart-review.googlesource.com/c/sdk/+/193450) will fix it, but it seems that there are more cases of this in `co19/`, see https://github.com/dart-lang/sdk/issues/45514.
