### ISSUE TITLE
Expose APIs in DDS to convert back and forth between file paths and dart URIs

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#45530]
Currently we have many different tools all making educated guesses about how to convert between the paths. Worse, the heuristics about how to convert a file path to a dart uri differ for external and external workflows so this is a constant source of bugs.
DWDS can provide a custom implementation of this API for google3 web apps.

Suggested APIs to add to DDS. The APIs should take a list of paths as round trips can be a bottleneck when DDS clients are running on a different machine than DDS.

```dart
List<String> filePathsToDartUris(List<String> paths)
List<String> dartUrisToFilePaths(List<String> uris)
```

This matters most for debuggers setting breakpoints robustly but it also matters for tools such as the widget inspector and stack trace rewriters that need to understand both file paths and dart uris.

**Comment by jacob314** [comment]
cc: @bkonyi @grouma

**Comment by terrylucas** [comment]
@terry

**Comment by terrylucas** [comment]
Need to fix  routine `String displayAsPackage(String sourceName)` in DevTools memory_controller.dart when mechanism exist.

**Comment by jacob314** [comment]
This is likely the root cause of many breakpoint robustness issues we are seeing. Currently both VSCode and IntelliJ depend on hacks and the analysis server to map back and forth between file uris and packages. This causes breakpoints to be set on the wrong packages reducing user trust in breakpoints. For example:
https://b/issues/183216584

**Comment by bkonyi** [comment]
This functionality will almost certainly need to live in the VM service proper as we'd always need access to `package_config.json` to do this in DDS, whereas the VM will always have this information. Closing in favor of #46631.
