### ISSUE TITLE
Can't create a Dart Web run configuration with a path or query parameters

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#45532]
If you create a new Flutter or Dart Web run configuration in IntelliJ, there's no option to add query parameters or a path on the end of the URL. This would make it easier to quickly run or attach a debugger to a specific screen in a Flutter or Dart web app.

<details>
  <summary>Screenshots</summary>
  Flutter Run / Debug configuration screen:
<img width="1071" alt="Screen Shot 2021-03-30 at 3 46 59 PM" src="https://user-images.githubusercontent.com/1145719/113066404-534ec280-916f-11eb-8ada-c6a06807ec1f.png">

Dart Web Run / Debug configuration screen:

<img width="1183" alt="Screen Shot 2021-03-30 at 3 45 47 PM" src="https://user-images.githubusercontent.com/1145719/113066489-75484500-916f-11eb-8783-ae1d00e124a3.png">
</details>

**Comment by alexander-doroshko** [comment]
@johnpryan @mraleph This seems to be a duplicate of https://github.com/dart-lang/webdev/issues/1039. Once `webdev` supports the feature, we'll be able to add it to the Dart plugin.

**Comment by johnpryan** [comment]
Yep, this looks like a dupe
