### ISSUE TITLE
Test co19/Language/Functions/syntax_t03 crashes the precompiler

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45531]
Failing on a number of [configurations](https://dart-ci.firebaseapp.com/current_results/#/filter=co19/Language/Functions/syntax_t03).  See [here](https://dart-ci.appspot.com/log/any/dartkp-strong-linux-debug-x64/172/co19/Language/Functions/syntax_t03) for an example log.  Reproduces locally on my machine at head.

cc @a-siva

**Comment by alexmarkov** [comment]
Duplicate to https://github.com/dart-lang/sdk/issues/45384.
