### ISSUE TITLE
web: add runtime checks for input types of >> and >>> operators

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#45534]
Currently `>>` and `>>>` do not check that the input is not a double. This check was elided back in the days of Dart-1 and we can now fix it given the stronger typing guarantees we have today.

Dart2js would need to add some specializations to ensure the checks are optimized away when the types are properly provided.

Example test failure in: `corelib/unsigned_shift_test/07` (code such as `2.4 as dynamic >>> 1`).

/cc @rakudrama @nshahan

**Comment by nshahan** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/45438?

**Comment by sigmundch** [comment]
yes, thanks!
