### ISSUE TITLE
ddc source maps produce incorrect locations when a method contains multiple "debugger()" calls

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45544]
This came up at https://github.com/Dart-Code/Dart-Code/issues/3233 though can be reproduced without VS Code. Here, clicking "Continue" keeps breaking on the last `debugger()` call of the method, even though it's hitting the ones above (the console output shows where execution really is):

![Mar-31-2021 15-13-51](https://user-images.githubusercontent.com/1078012/113159571-9d4dac00-9234-11eb-825d-565dc46befbe.gif)

I also created a small script like this:

```dart
import 'dart:developer';

main() {
  print('1');
  debugger();
  print('2');
  debugger();
  print('3');
  debugger();
}
```

I compiled with `dartdevc`, then used `package:source_maps` to try and parse the map and print the locations around the lines with the debugger calls:

<img width="869" alt="Screenshot 2021-03-31 at 15 21 57" src="https://user-images.githubusercontent.com/1078012/113159906-e1d94780-9234-11eb-9b4e-212774dd3eb8.png">

The output seems to match the behaviour shown at the top - each of the lines with `debugger()` calls seems to resolve to the same location:

```
26: <SourceMapSpan: from <SourceLocation: 0 lib/foo.dart:9:13> to <SourceLocation: 0 lib/foo.dart:9:13> ""> // incorrect
27: <SourceMapSpan: from <SourceLocation: 0 lib/foo.dart:6:3> to <SourceLocation: 0 lib/foo.dart:6:3> "">
28: <SourceMapSpan: from <SourceLocation: 0 lib/foo.dart:9:13> to <SourceLocation: 0 lib/foo.dart:9:13> ""> // incorrect
29: <SourceMapSpan: from <SourceLocation: 0 lib/foo.dart:8:3> to <SourceLocation: 0 lib/foo.dart:8:3> "">
30: <SourceMapSpan: from <SourceLocation: 0 lib/foo.dart:9:13> to <SourceLocation: 0 lib/foo.dart:9:13> "">
```

**Comment by devoncarew** [comment]
@grouma - do you know who to route this to?

**Comment by grouma** [comment]
cc @nshahan

**Comment by grouma** [comment]
Note we have a similar report from an internal user.

**Comment by nshahan** [comment]
Thanks for the bug reports. My guess is that we are reusing the same node in our JavaScript AST for the debugger call so each one gets the same source location.
