### ISSUE TITLE
[BUG] null safety List issue

### ISSUE THREAD

**Issue by KristianBalaj** [dart-lang/sdk#45541]
Dart SDK version: 2.12.1 (stable)
Platform: MacOS

Code:
```
List<int?> numbers;
numbers = List<int>.unmodifiable([]);
numbers.add(null);
```

Addition of the null to the list throws an Exception - `type 'Null' is not a subtype of type 'int' of 'value'`

There is no null safety error in this assignment (there should be one on the second line), so I think this is an issue.

**Comment by mraleph** [comment]
Dart generics are covariant, e.g. `List<Button>` is assignable to `List<Widget>` if `Button` is a subtype of `Widget`, you will however get a dynamic error if you try to add something that is not a `Button` to such list. 

`int` is a subtype of `int?`. So in the same way `List<int>` is assignable to `List<int?>` and you get a dynamic error when you try to put `null` into it.

**Comment by mraleph** [comment]
You migth be interested in this language feature: https://github.com/dart-lang/language/issues/524 which proposes to extend Dart with an ability to enforce variance per variable declaration
