### ISSUE TITLE
No error in CFE and Analyzer for Array.multi() with negative dimensions

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#45540]
The following code produces no compile errors in both analyzer and CFE
```dart
import "dart:ffi";

class MyStruct extends Struct {
  @Array.multi([-1])  // no error
  external Array<Uint8> a0;
}

void main() {
  MyStruct? ms = null;
}
```
`Dart SDK version: 2.13.0-165.0.dev (dev) (Thu Mar 25 02:53:52 2021 -0700) on "windows_x64" `

cc @dcharkes

**Comment by sgrekhov** [comment]
See also the similar issue #45538

**Comment by sgrekhov** [comment]
Like in #45538 now there are no errors for the code above nor in analyzer nor in CFE. Is it correct? What is an expected behaviour?

**Comment by dcharkes** [comment]
The expected behavior up til now is undefined, but it would be nice to disallow negative and 0 as array dimensions.

**Comment by lfkdsk** [comment]
try to fix with: [vm] https://github.com/dart-lang/sdk/pull/45785 [analyzer] https://github.com/dart-lang/sdk/pull/45784

**Comment by dcharkes** [comment]
co19/LibTest/ffi/Array/Array.multi_A02_t01
co19/LibTest/ffi/Array/Array_A02_t01

@sgrekhov These tests should have a negative expectation.

**Comment by sgrekhov** [comment]
Now it is an error in analyzer if array has a negative or zero size. But CFE still allows zero-sized arrays. It produces an error for negative size but not for zero

**Comment by dcharkes** [comment]
As long as it's labelled library-ffi, we'll get to it at some point.
