### ISSUE TITLE
 InternetAddress.lookup throws an error when runs with `timeout` which returns empty list in onTimeout callback

### ISSUE THREAD

**Issue by ManoyloK** [dart-lang/sdk#45542]
If we try lookup for a host like this
```
final foundAddresses =
          await InternetAddress.lookup('smth.com').timeout(
        const Duration(milliseconds: 300),
        onTimeout: () => [],
      )
```
We get an error:
`type '() => List<InternetAddress>' is not a subtype of type '(() => FutureOr<List<_InternetAddress>>)?' of 'onTimeout'`
 

Dart version 2.12.2, macOS 11.2.1

**Comment by aam** [comment]
Thank you for reporting this problem!
https://dart-review.googlesource.com/c/sdk/+/193720 should have the fix.
