### ISSUE TITLE
Analyzer CONFLICTING_GENERIC_INTERFACES reports overlong error spans

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45557]
For the following test case:

```dart
class A<T> {}

class B implements A<int>, A<String> {
  //Long stuff here
  // And here
  // And here
}
```

The analyzer reports the span of the conflicting generic interface error as the complete class:

```
xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --format=machine ~/tmp/test.dart
ERROR|COMPILE_TIME_ERROR|CONFLICTING_GENERIC_INTERFACES|/Users/leafp/tmp/test.dart|3|1|88|The class 'B' can't implement both 'A<int>' and 'A<String>' because the type arguments are different.
ERROR|COMPILE_TIME_ERROR|IMPLEMENTS_REPEATED|/Users/leafp/tmp/test.dart|3|28|9|'A' can only be implemented once.
```

Note that the `88` given as the span of the first error there: this is the span of the error.

Similar issue to https://github.com/dart-lang/sdk/issues/42865 .

cc @scheglov @bwilkerson - just filing this as an FYI since I encountered it, not actually causing any user visible issues that I'm aware of.

**Comment by leafpetersen** [comment]
Additional note: the line indicated for the error is also incorrect if there are doc comments preceeding it.  For example:

```dart
class A<T> {}

/// foobar
/// baz
class B implements A<int>, A<String> {
  //Long stuff here
  // And here
  // And here
}
```

Here the error is indicated on line 3, not line 5.

**Comment by srawlins** [comment]
The error is now only reported on the class name.
