### ISSUE TITLE
Customer-reported issue with NNBD migration tool

### ISSUE THREAD

**Issue by Chazzman** [dart-lang/sdk#45571]
Migration tool trashed my code
![image](https://user-images.githubusercontent.com/5728275/113452107-577a1a80-93d1-11eb-834c-3f9313db3ec6.png)
Wee sample
and another:
![image](https://user-images.githubusercontent.com/5728275/113453036-33b7d400-93d3-11eb-8a42-f49efacefb44.png)
even doc got a whack or two:
![image](https://user-images.githubusercontent.com/5728275/113453105-56e28380-93d3-11eb-9c49-fa1f43298823.png)
killing me:
![image](https://user-images.githubusercontent.com/5728275/113453465-04559700-93d4-11eb-8766-bb77eb0144eb.png)

**Comment by stereotype441** [comment]
@Chazzman I'm so sorry you ran into this problem!  Thanks for the bug report, and thanks for including screenshots of what happened; I was able to reproduce the problem based on your screenshots.

I believe what happened is that you added the `/*!*/` hints by clicking on the `Add /*!*/ hint` button on the bottom of the "Edit details" pane of the migration tool UI, and then you clicked on "APPLY MIGRATION" immediately afterward.

You need to re-analyze your code after adding hints using the "RERUN FROM SOURCES" button, which is right next to "APPLY MIGRATION".  The migration tool was supposed to avoid corruption like this by disabling the "APPLY MIGRATION" button after you apply a hint, and then re-enabling it after you click "RERUN FROM SOURCES".  Unfortunately that's not working properly for the hint buttons at the bottom of the "Edit details" pane.  I'll get to work on a fix.

In the meantime, you should be able to proceed with your migration if you click on "RERUN FROM SOURCES" before clciking "APPLY MIGRATION".  Does that work around the problem for you?
