### ISSUE TITLE
Analyzer does not check that bounds are satisfied by generic metadata arguments

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45579]
The following example should be an error, since `String` is an invalid type argument for the generic class `Y`:

```dart
class Y<T extends num> {
  const Y();
}

@Y<String>()

class Test1 {}
```

The analyzer currently issues no errors on this code when run with `--experiment=generic-metadata`.

This is tests by `co19/src/Language/Metadata/syntax_t11.dart`, but unfortunately that test is broken pending the next co19 roll.

cc @devoncarew @scheglov @natebosch

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/194000
