### ISSUE TITLE
`CanvasElement.getContext3d()` should have a nullable return value

### ISSUE THREAD

**Issue by Fox32** [dart-lang/sdk#45572]
I'm porting a WebGL app to null safety and noticed during migration that the return value of `CanvasElement.getContext3d()` from `dart:html` is defined as non null. However it is a common pattern to check the return value for null which indicates that WebGL is not supported/available.

Looking at the code, it looks suspicious: 

```dart
  gl.RenderingContext getContext3d(
      {alpha: true,
      depth: true,
      stencil: false,
      antialias: true,
      premultipliedAlpha: true,
      preserveDrawingBuffer: false}) {
    var options = {
      'alpha': alpha,
      'depth': depth,
      'stencil': stencil,
      'antialias': antialias,
      'premultipliedAlpha': premultipliedAlpha,
      'preserveDrawingBuffer': preserveDrawingBuffer,
    };
    var context = getContext('webgl', options);
    if (context == null) {
      context = getContext('experimental-webgl', options);
    }
    return context as gl.RenderingContext;
  }
```

At the end, `context` is casted to `gl.RenderingContext` even though context is `Object?` and should be casted to `gl.RenderingContext?`.
`getContext` is defined correctly and can return null:

```dart
  Object? getContext(String contextId, [Map? attributes]) {
    if (attributes != null) {
      var attributes_1 = convertDartToNative_Dictionary(attributes);
      return _getContext_1(contextId, attributes_1);
    }
    return _getContext_2(contextId);
  }
```
I wonder if there are cases where a casting from `T?` to `U` and not to `U?` is valid. Otherwise should the analyzer detect something like this?
As a workaround, I wrote myself an extension:

```dart
extension on CanvasElement {
  RenderingContext? getContext3dNullable(
      {alpha = true,
      depth = true,
      stencil = false,
      antialias = true,
      premultipliedAlpha = true,
      preserveDrawingBuffer = false}) {
    var options = {
      'alpha': alpha,
      'depth': depth,
      'stencil': stencil,
      'antialias': antialias,
      'premultipliedAlpha': premultipliedAlpha,
      'preserveDrawingBuffer': preserveDrawingBuffer,
    };
    var context = getContext('webgl', options);
    context ??= getContext('experimental-webgl', options);
    return context as RenderingContext?;
  }
}
``` 

---

Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "windows_x64"
Window 10, 64bit

**Comment by srujzs** [comment]
Yeah, this seems like an incorrect assumption that the second `getContext` will always return a non-nullable. WebGL can still be unsupported. This should be a simple fix.

> I wonder if there are cases where a casting from T? to U and not to U? is valid. Otherwise should the analyzer detect something like this?

I'm not sure what the official language reasoning was, but this cast is intended to be supported.
