### ISSUE TITLE
int.tryParse should not throw an exception

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#45573]
A failure to parse in a `tryParse` method is expected, not exceptional. Using exceptions for this logic makes it difficult to use a debugger with "pause on caught exceptions" turned on.

**Comment by rakudrama** [comment]
Where does it throw an exception?

AFAIK the js_runtime / js_dev_runtime versions do not throw. Is this a VM implementation issue?

**Comment by lrhn** [comment]
The current implementation throws on failure, reusing the existing `parse` function, then catches that and returns `null` instead.

Rewriting has not been a priority, but it's definitely possible.

That said, pausing on caught exceptions should be expected to catch some exceptions that are handled at a higher abstraction level. Throwing and catching your own exceptions is perfectly valid behavior (I'd be more concerned about catching errors).

**Comment by natebosch** [comment]
https://dart-review.googlesource.com/c/sdk/+/193960 should remove the exception, but it has an impact on some kernel files that I don't fully understand the impact.

@rakudrama - yes - sorry for not updating the bug. I realized after I started digging it was VM only.

**Comment by natebosch** [comment]
Fixed in 427e17dfce7
