### ISSUE TITLE
Analyzer unit test failures when enabling the nonfunction type alias experiment by default

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45576]
There are new test failures on [Enable non-function type aliases by default in 2.13.](https://dart-review.googlesource.com/c/sdk/+/192948).

The tests
```
pkg/analysis_server/test/integration/analysis/navigation_test RuntimeError (expected Pass)
pkg/analysis_server/test/integration/analysis/navigation_test RuntimeError (expected Pass)
pkg/analysis_server/test/search/element_references_test RuntimeError (expected Pass)
pkg/analysis_server/test/search/element_references_test RuntimeError (expected Pass)
pkg/analysis_server/test/search/top_level_declarations_test RuntimeError (expected Pass)
pkg/analysis_server/test/search/top_level_declarations_test RuntimeError (expected Pass)
```

started failing with this CL.

cc @scheglov

**Comment by scheglov** [comment]
I will start working on making these tests to not depend on the state of the flag.
If you want to land, mark these tests failing, land the CL, and I will just fix them for the state when they are enabled.

**Comment by leafpetersen** [comment]
Thanks!  I approved the failures and am rolling forward - they didn't look to me like actual problems.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/194003

**Comment by scheglov** [comment]
We landed fixes for these tests.
