### ISSUE TITLE
Null-safety analysis false positive

### ISSUE THREAD

**Issue by sebthom** [dart-lang/sdk#45582]
The following code results in the compile error `Error: The argument type 'Duration?' can't be assigned to the parameter type 'Duration' because 'Duration?' is nullable and 'Duration' isn't.`

```dart
Duration? expiresWithin = Duration(minutes: 10);

void main() {
  DateTime? expiration = expiresWithin == null ? null : DateTime.now().add(expiresWithin);
  //                                                   compile error here: ~~~~~~~~~~~~~
}
```

Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "windows_x64"

**Comment by sebthom** [comment]
Another example:
```dart
int? foo = 1;

void main() {
  if (foo != null)  
    printNumber(foo);
}

void printNumber(int value) => print(value);
```

**Comment by lbguilherme** [comment]
A variable from another scope (or a field of a class) can be changed as a side of some other function call. For example:

```
int​?​ foo ​=​ ​1​;

​void​ ​main​() {
  ​if​ (foo ​!=​ ​null​)  
    ​printNumber​(makeNull(), foo);
}

int makeNull() {
  foo = null;
  return 4;
} 

​void​ ​printNumber​(​int dummy, int​ value) ​=>​ ​print​(value);
```

The compiler can't assume the variable will remain not null inside the if. A solution for this would be to create a local variable that can't be changed outside this scope:

```
int​?​ foo ​=​ ​1​;

​void​ ​main​() {
  final localFoo = foo;
  ​if​ (localFoo ​!=​ ​null​)  
    ​printNumber​(localFoo);
}
```

**Comment by sebthom** [comment]
@lbguilherme Thanks for the explanation!
