### ISSUE TITLE
Crash when using new lightweight isolates

### ISSUE THREAD

**Issue by sroddy** [dart-lang/sdk#45596]
Cross-posting this bug that I've managed to easily reproduce when using new Flutter lightweight engines, but looks like it much likely caused by some race-conditions inside the dart vm itself (given that with regular flutter engines the same never happens).

https://github.com/flutter/flutter/issues/79335

https://github.com/flutter/flutter/files/6228137/MultipleFluttersIos.30-03-21.05-08.crash.zip

**Comment by mraleph** [comment]
Tracked by flutter bug.
