### ISSUE TITLE
Some analyzer tests fail due to truncation

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#45590]
When https://dart-review.googlesource.com/c/sdk/+/193740 lands, the following tests will begin failing under the `analyzer-asserts-linux` and `analyzer-linux` configurations:

- language_2/syntax/deep_nesting_statement_test/01
- pkg/analyzer/test/src/dart/analysis/driver_resolution_test
- pkg/analyzer/test/src/summary/resynthesize_ast2_test

And the following tests will begin failing under the `analyzer-asserts-strong-linux` and `analyzer-asserts-weak-linux` configurations:

- language/syntax/deep_nesting_statement_test/01
- language/generic/super_bounded_types_error_test
- language/generic/super_bounded_types_test

These tests fail becuase they cause the analyzer output to be larger than 500k, so the test runner truncates it; this in turn causes JSON parsing to fail (which I've chosen to report as a crash).

I believe these failures will be addressed by https://dart-review.googlesource.com/c/sdk/+/178940, which removes the test runner truncation feature.

**Comment by munificent** [comment]
I finally got a chance to sync, merge, and approve the expected failures for https://dart-review.googlesource.com/c/sdk/+/178940, so that should land soon, once AAR folks can take a look.

**Comment by munificent** [comment]
My CL landed (a long time ago) and these tests are now passing so calling it done.
