### ISSUE TITLE
Flaky tests turned to Timeout on app_jitk-linux-release-x64

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#45604]
There are new test failures on [[vm/aot] Fix retaining of targets of FFI callbacks in precompiler](https://github.com/dart-lang/sdk/commit/a38a2dd34385f7e9711b0efdcd4558e45590b07c). The change is unrelated (it may only affect AOT but not app-jit).

The tests
```
service_2/next_through_operator_bracket_test/service Timeout (expected Pass)
service_2/step_through_for_each_sync_star_test/dds Timeout (expected Pass)
service_2/step_through_for_each_sync_star_test/service Timeout (expected Pass)
service_2/step_through_getter_test/dds Timeout (expected Pass)
service_2/step_through_getter_test/service Timeout (expected Pass)
service_2/stream_subscription_test/service Timeout (expected Pass)
service_2/validate_timer_port_behavior_test/dds Timeout (expected Pass)
service_2/validate_timer_port_behavior_test/service Timeout (expected Pass)
vm/dart_2/boxmint_test Timeout (expected Pass)
vm/dart_2/byte_array_test Timeout (expected Pass)
```
are failing on configurations
```
app_jitk-linux-release-x64
```

These tests were previously flaky, but now they turned to timeouts.
The tests are listed in the flaky.json:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8850672203931795904/+/steps/update_flakiness_information/0/logs/raw_io.output_text_flaky.json_/0

On the same change many other tests turned from passing to flaky:

```
ffi_2/function_callbacks_very_many_test/0
language_2/call/closurization_test/0
language_2/operator/arithmetic_test
language_2/regress/regress7525_test
language_2/vm/inline_heuristic_test
language_2/vm/load_elimination_has_loads_from_place_test
language_2/vm/load_elimination_mark_stored_values_escaping_test
language_2/vm/load_to_load_forwarding_vm_test
language_2/vm/optimized_shl_test
language_2/vm/regress_14903_test
language_2/vm/uint32_right_shift_test
language_2/vm/unaligned_float_access_literal_index_test
language_2/vm/unaligned_integer_access_register_index_test
lib_2/typed_data/float64x2_functional_test/0
lib_2/typed_data/int32x4_sign_mask_test
lib_2/typed_data/int32x4_test/0
service_2/async_single_step_out_test/service
service_2/breakpoint_in_parts_class_test/service
service_2/causal_async_star_stack_contents_test/dds
service_2/causal_async_star_stack_contents_test/service
service_2/client_resume_approvals_reload_test/service
service_2/column_breakpoint_test/dds
service_2/column_breakpoint_test/service
service_2/debugging_inlined_finally_test/dds
service_2/debugging_inlined_finally_test/service
service_2/dev_fs_http_put_weird_char_test/dds
service_2/dev_fs_http_put_weird_char_test/service
service_2/developer_server_control_test/dds
service_2/developer_server_control_test/service
service_2/developer_service_get_isolate_id_test/dds
service_2/developer_service_get_isolate_id_test/service
service_2/dominator_tree_vm_with_double_field_test/dds_0
service_2/dominator_tree_vm_with_double_field_test/dds_1
service_2/dominator_tree_vm_with_double_field_test/dds_2
service_2/dominator_tree_vm_with_double_field_test/service_0
service_2/dominator_tree_vm_with_double_field_test/service_1
service_2/dominator_tree_vm_with_double_field_test/service_2
service_2/enable_service_port_fallback_positive_test/dds
service_2/enable_service_port_fallback_positive_test/service
service_2/get_allocation_profile_rpc_test/service
service_2/get_client_name_rpc_test/service
service_2/get_source_report_test/service
service_2/library_dependency_test/dds
service_2/library_dependency_test/service
service_2/malformed_test/dds
service_2/malformed_test/service
service_2/next_through_assign_call_test/dds
service_2/next_through_assign_call_test/service
service_2/next_through_operator_bracket_test/dds
```

@whesse Are there any recent infra changes in the handling of flaky tests?

**Comment by whesse** [comment]
This was a single shard, that timed out on a subset of that shard's tests (a consecutive alphabetic interval), when creating the snapshots.  Perhaps a batch runner got stuck in a bad mode, or something?
Should recover on next run.  Will think more about this failure, and how to detect it.

**Comment by whesse** [comment]
Looking at the logs for the timing out tests, the stack traces all indicate that the compiler is actively doing useful work when it is interrupted by the timeout.  Looking at other shards, that are working correctly, a large number of tests are taking around 35 seconds to compile.  So it seems like any infrastructure flaky that makes a shard twice as slow will push large numbers of tests over the limit of 1 minute.  I think this builder, and maybe similar ones, should have their test timeout increased to 2 minutes, and that these tests just take a really long time to AOT compile.

The debug bot has test timeouts of 8 minutes instead of 1 minute, and many compilations are taking 1 minute and 20 seconds on these bots, but not timing out.  So I think it is just that the release mode doesn't add any default timeout multipliers the way debug mode does, and 1 minute is just too short a time for the aot compilation of some of these tests.
