### ISSUE TITLE
Dart Migration: NoSuchMethodError: The getter 'isDynamic' was called on null.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#45600]
When running dart migration on dart 2.12.2 the following exception was thrown.

Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.12.2) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic at offset 4909 in /home/bsutton/git/conduit/conduit/conduit/lib/src/http/managed_object_controller.dart (Operation.get)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      EdgeBuilder._makeEdgeOrigin (package:nnbd_migration/src/edge_builder.dart:3141:25)
#2      EdgeBuilder._checkExpressionNotNull (package:nnbd_migration/src/edge_builder.dart:1985:18)
#3      EdgeBuilder._handleTarget (package:nnbd_migration/src/edge_builder.dart:3056:14)
#4      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:2980:20)
#5      EdgeBuilder.visitPrefixedIdentifier (package:nnbd_migration/src/edge_builder.dart:1405:14)
#6      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8257:49)
#7      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#8      EdgeBuilder.visitAnnotation (package:nnbd_migration/src/edge_builder.dart:325:7)
#9      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:280:49)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#11     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#12     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2470:5)
#13     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#14     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#15     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#16     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#17     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#18     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#19     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#20     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#21     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#22     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:51)
#23     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#24     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#25     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#26     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#27     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#28     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#29     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1154:19)
#30     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:28)
#31     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#32     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1152:5)
<asynchronous suspension>
#33     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#34     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#35     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#36     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#37     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#38     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

**Comment by stereotype441** [comment]
Hi @bsutton, thanks for the bug report!  Were you able to make progress by re-running `dart migrate` with the `--ignore-exceptions` option?

**Comment by bsutton** [comment]
yes, I stepped around the issue by using the --ignore-exceptions option.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
