### ISSUE TITLE
Factory constructor of 'A' class delegated to a constructor of 'B' class returns instance of 'A' class instead of 'B'

### ISSUE THREAD

**Issue by vadlit** [dart-lang/sdk#45614]
Factory constructor of 'A' class delegated to a constructor of 'B' class returns instance of 'A' class instead of 'B'
So this code cannot be compiled (`A value of type 'A' can't be returned from a function with return type 'B'`):

```
B createInstance() {
  return A.myFactoryMethod();
}

class A {
  A._();

  factory A.myFactoryMethod() = B;
}

class B extends A {
  B(): super._();
}
```

Can be reproduced when 'null safety' enabled only. It's unexpected behaviour and breaks the behaviour worked in previous versions of 'not null safe' Dart.
I often used previous behavior when used Freezed classes with factory constructors.

Dart SDK 2.12.2
Windows

**Comment by mraleph** [comment]
This is working as intended - implicit down-casts are disabled in null safe Dart. 

You have to cast explicitly: `A.myFactoryMethod() as B`.

**Comment by vadlit** [comment]
It doesn't make the language friendly.
From the perspective of a developer, I just delegated creating of new instance to another constructor. So I don't understand why compiler cannot get the type of instance out of there but not from original class. All necessary information is already stored in the factory constructor.
I don't suggest to downcast type. I suggest originally store correct information about factory constructor type.

**Comment by mraleph** [comment]
>  I suggest originally store correct information about factory constructor type.

Constructors on `class A` return instances of `A`. There is no difference between: 

```dart
class A {
  factory A.redirecting() = B;
}
```

and

```dart
class A {
  factory A.redirecting() => B();
}
```

The whole idea with redirecting factories is that they allow you to hide the implementation - so it does not make sense to have a different (more specific) return type.  

Furthermore: such change is going to break things in strange ways. Consider for example: 

```dart
class A {
  factory A.x() = X;
  factory A.y() = Y;
}

class X extends A { }
class Y extends A { }

final list = [A.x()];
list.add(A.y());  // (*)
```

Line marked with `(*)` will be a compile time error if `A.x` has return type `X`. 

If you know that `A.myFactoryMethod` delegates to `B` then you should either cast or even better just invoke `B` directly:

```dart
B createInstance() {
  return B();
}
```

IIRC Freezed generates public classes for your variants - so this will work just fine.

**Comment by vadlit** [comment]
Yes, Freezed generates public classes and I can use them, but it means that I cannot use factory constructors directly (or I have to cast every time). Sounds bad.
As for your example with
```
final list = [A.x()];
list.add(A.y())
```
the same behaviour will be with any type of constructors, so I don't see a problem here.
```
final list = [X()];
list.add(Y())
```
The same expected compile-time error and it's ok.
I don't see disadvantages of my suggestion, but I see disadvantages of current behaviour + it brokes the behaviour existed before.

**Comment by mraleph** [comment]
> The same expected compile-time error and it's ok.

It's not okay because it is a breaking change (as it changes inferred type of `[A.x()]`, think that `A` it can be some common class in the SDK like `Map` which uses redirecting factories to hide implementation) and breaking changes have very high bar. 

Furthermore, as I have said above, this violates the following fundamental properties of constructors: 

1. Constructors on `A` return `A`. 
2. Factories hide implementation allowing you to change implementation without breaking user code.
3. Redirecting factories are just convenience shorthand for factories.

I let @lrhn @eernstg @leafpetersen pass actual judgement here, but I'd say fairly confidently based on the arguments above that there is absolutely *no* chance that return type of the redirecting factory would be changed to expose actual implementation type.

**Comment by vadlit** [comment]
Thank you for your answer

**Comment by lrhn** [comment]
@mraleph is correct. The intended model is that a redirecting factory constructor is an abstraction (all factory constructors are), and it's considered an implementation detail which object it actually returns. You should be able to change the actual returned type at any time without changing the program's types.

If you really intend to make `A.something()` return a `B` every time, just make it a static method instead of a constructor:
```dart
class A {
  A._();

  static B myFactoryMethod() => B();
}
```

**Comment by leafpetersen** [comment]
@lrhn I have a vague memory that we have discussed allowing factory constructors to have an explicit return type which is different than the enclosing class type, do I remember this correctly?  Do we have a request for it?

**Comment by eernstg** [comment]
We can use a type alias to achieve a similar redirection as a redirecting factory constructor. We can't use the same name for the type alias and for the class, so it's not an alternative to having the redirecting factory with a different return type: it just serves to illustrate the associated inference task:

```dart
// Needs `--enable-experiment=nonfunction-type-aliases` until 2.13.

abstract class A<X> {
  X get x;
  // The typedef below pseudo-emulates this factory:
  // factory A(X x, X y) = B<X, X>;
}

typedef A_typedef<X> = B<X, X>;

class B<X, Y> implements A<X> {
  X x;
  Y y;
  B(this.x, this.y);
}

void main() {
  // `A_typedef(..., ...)` would have been `A(..., ...)` if we had those factories.
  var x1 = A_typedef(2, 3); // Type `B<int, int>`.
  print(++x1.y); // So we can use `B` members; prints '4'.
  var x2 = A_typedef(2, 2.71828); // How about arguments with different types?
  print(x2.runtimeType); // 'B<num, num>'.
}
```

If we had factories with user-specified return types, `A<T>(..., ...)` should yield an object whose type is a subtype of `A<T>`, for any `T`. So for inference on `A(2, 3)` we must use a `T` such that `int <: T`, and we get `int` as expected, and the type of `A(2, 3)` is `B<int, int>`. But with `A(2, 2.71828)` we must satisfy `int <: T` and `double <: T`, and we get `B<num, num>`, not `B<int, double>`.

So even though it might look like we can just "macro expand" the redirecting factory at the call site and then perform inference, it's a bit more involved than that.

**Comment by lrhn** [comment]
I don't think we have a request for constructor return types (or restricted constructor type arguments, as it would be).

It could be something like:
```dart
class Heap<T> {
  Heap(int Function(T, T) compare) : ...
  Heap<R extends Comparable<R>>.comparable() : ...  
}
```
That would be better than what we do now in some places, where `compare` is optional, but if you omit it, it *dynamically* calls `compare` on the elements. The "solution" is to use a static factory function instead: `static Heap<R> comparable<R>() => Heap<R>(defaultCompare);`, but it would be nicer to have an actual constructor.

Or, wait for generic constructors, and allow them to declare the type parameters:
```dart
class Map<K, V> { 
  factory Map<X, X>.self<X>() = Map<X, X>;
  ...
}
```
It's not entirely clear how to solve for the constraints of such non-linear types.
