### ISSUE TITLE
language_2/unsorted/disassemble_test produces very large command line output

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#45618]
I am [fixing the test runner](https://dart-review.googlesource.com/c/sdk/+/178940) to allow longer output since the current limit truncates some static error tests. The new limit is 4MB, which I found through some trial and error. That's pretty big, but is necessary to handle:

language_2/unsorted/disassemble_test

There may be others. Ideally, that test would be changed to produce less output and then we can reduce the limit in the test runner.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/201169 and
https://dart-review.googlesource.com/c/sdk/+/201169
should fix the large output issue.
