### ISSUE TITLE
Compiler cannot remember that a 'final' field has been checked as not null

### ISSUE THREAD

**Issue by vadlit** [dart-lang/sdk#45615]
Compiler cannot remember that a 'final' field has been checked as not null. `Operator '+' cannot be called on 'int?' because it is potentially null`
It leads to a necessity to introduce fake intermediate variables everywhere to help the compiler.
Kotlin compiler is smarter in similar cases.

```
void main() {
  final a = A(4);
  if (a.nullable != null) {
    print (a.nullable + 1);
  }
}

class A {
  final int? nullable;  
  
  A(this.nullable);
}
```

Dart 2.12.2
Windows

**Comment by keertip** [comment]
@vadlit, when you say 'compiler' do you see this during static analysis, or when trying to run the program?

**Comment by mraleph** [comment]
Fields are not promoted because that would be unsound. This is explicitly called out in the documentation, see https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields

Language team is discussing a number of approaches to this problem (see https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion), but right now you either need to use `!` or load field into a local variable and compare that with `null` instead.

**Comment by vadlit** [comment]
Please be more attentive. I'm talking about final fields only!
But you referred to any fields.
Final fields are guaranteed to be immutable, so there is no problem with "unsoundness". I believe it's a bug

**Comment by eernstg** [comment]
@vadlit, please consider the following situation:

```dart
class A {
  final int? i = 42;
  void foo() {
    if (i != null) print((i as dynamic).isEven);
  }
}

class B extends A {
  bool makeItNull = true;
  int? get i {
    makeItNull ^= true;
    return makeItNull ? null : super.i;
  }
}

void main() {
  B().foo();
}
```

I'm using `i as dynamic` rather than `i` in order to allow the null reference error to occur (we'll get a compile-time error if we use `i.isEven`).

**Comment by mraleph** [comment]
> I'm talking about final fields only!

In Dart fields don't work the same way as in most other languages (including Kotlin). They behave more like _properties_, with implicit overridable getter (and setter). 

`final` simply means that the field only declares a getter but no setter. You can't overwrite the value stored in the field. However you can override the getter itself to make it return whatever you want. 

See @eernstg example above that demonstrates this.

**Comment by vadlit** [comment]
It's awful language design then, as for me.
So now I understand why compiler can't help me here. Ok.

**Comment by vadlit** [comment]
By the way, may be it would be nice to introduce a new keyword means 'final final' (overriding is prohibited). Something like 'sealed final'

**Comment by eernstg** [comment]
We are considering a sealing mechanism (which could be applied to a class or an instance member). There are other ways to get the desired property as well (that is: establishing the guarantee that evaluation of a getter multiple times yields the same value each time), e.g., dart-lang/language#1518.

> It's awful language design

The main rationale is that properties should encapsulate their implementation, such that clients do not depend on whether a given property `x` is stored or computed. The _lack_ of encapsulation in this area in languages like Java causes those communities to recommend that you never have public fields, you must always write getters and setters if clients should be allowed to access a field. In Dart you get those getters and setters automatically and consistently.
