### ISSUE TITLE
Dart cannot be sure that the method argument is not null if the argument is used in a closure

### ISSUE THREAD

**Issue by vadlit** [dart-lang/sdk#45629]
By some reason Dart cannot be sure that the method argument is not null if the argument is used in a closure. `Property 'isEven' cannot be accessed on 'int?' because it is potentially null`

```
void main() {
  foo(1);
}

void foo(int? nullable) {
  Future.delayed(Duration(seconds:0)).then((_)
  {
    if (nullable == null) { 
      nullable = 5;
    }
    if (nullable == null) {
      return;
    }
    print(nullable.isEven);
  });
}
```

In this case, as far as I undestand, there's no chance that the 'nullable' argument suddenly becomes nullable after the 1st check, because it's just a method argument, not class field.
The problem is not reproduced if remove the first check.

Dart 2.12.2
Windows

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/1247. It's possible that the flow analysis could give special treatment to the case where _all_ references (read &amp; write) to a given local variable occurs in the same function literal or local function, even though the variable is declared in an enclosing function.
