### ISSUE TITLE
[CP][beta channel] address an issue with very slow file opening with VS Code

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#45632]
**commit(s) to merge**: COMMIT-HASH

- https://github.com/dart-lang/sdk/commit/e8d53cff924214ea8dd20b36bb82f7d2dde7a131

**merge instructions**: clean merge or patch CL

- expected clean merge (this was very recent)

**What is the issue**: Brief description of the problem

- with some recent analysis server context work, users using LSP see increased resource usage (from rebuilding available declarations) and errors in the error list vanishing and reappearing as they open/close files; this issue exists in master but not in previous beta/stable releases (it's a regression)

**What is the fix**: Brief description of the fix

- For the analysis server in LSP mode, improve the handling of loose files and context rebuilds

**Why cherrypick**: Describe the reasons, like many users impacted, or serious functional issues, for example

- without this fix, users will see increased resource usage (from rebuilding available declarations) and errors in the error list vanishing and reappearing as they open/close files

**Risk**:

- low

**Link to original  issue(s)**:

- https://github.com/dart-lang/sdk/issues/45633

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

@scheglov @DanTup

**Comment by athomas** [comment]
Please take a look at this test failure on windows that seems to be introduced by the commit:
https://dart-ci.appspot.com/log/analyzer-win-release/analyzer-unittest-asserts-release-win/14525/pkg/analysis_server/test/lsp/initialization_test

**Comment by DanTup** [comment]
@athomas I think https://dart-review.googlesource.com/c/sdk/+/194763/ should fix this, though it'll take me some fiddling to get the SDK tests running on my Windows machine - if you can easily run the same windows trybot on the CL, that might give an answer sooner. Thanks!

**Comment by DanTup** [comment]
@athomas the test fix is now in master (ea9c6484f1412c09f19ce570eb1617017084a642). Let me know if anything else is required. Thanks!

**Comment by christopherfujino** [comment]
for the engineer doing the cherrypick, there was a mistake on the release doc as to which dart release is the branch point. <b>This cherrypick should be applied to the [2.13.0-211.0.dev](https://github.com/dart-lang/sdk/commit/dda1a31495e39a77b463753caf1295eaa47bc983) release.</b>

**Comment by vsmenon** [comment]
Do we need a consolidated cherry-pick with both fixes here?

**Comment by athomas** [comment]
We should pick ea9c6484f1412c09f19ce570eb1617017084a642 as well. It only changes the expectations of a test to also pass on Windows. There's zero risk in picking it and we get a better signal from the tests on beta/stable if we pick it.

**Comment by franklinyow** [comment]
Approved in SCRUM

**Comment by athomas** [comment]
Merged to beta in 94162a2 (2.13.0-211.6.beta).
