### ISSUE TITLE
Test runner gets confused if a co19 test has both an @compile-error annotation and a static error expectation

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45634]
Discovered tracking down a very confusing error with @athomas in which a co19 test was passing locally but showing up as failing on the bots.  If a test uses both `@compile-error` but also has a static error test expectation, then the test runner gets confused and interprets the successful run (that is, correct reporting of a static error) as a missing compile time error.  To reproduce, sync to `9674ab8921a34f23d0e38af6ae29f0e535a829f0` and run:

```
leafp-macbookpro:sdk leafp$ mkdir cache_temp
leafp-macbookpro:sdk leafp$ python tools/test.py -n analyzer-asserts-strong-mac co19/Language/Mixins/declaration_t01 -v --clean-exit --write-results --output-directory cache_temp/ && cat cache_temp/results.json 
Test configuration:
    analyzer-asserts-strong-mac(architecture: x64, compiler: dart2analyzer, mode: release, runtime: none, system: mac, nnbd: strong, enable-asserts, use-sdk)
Suites tested: co19
Running "dart2analyzer" command: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=nonfunction-type-aliases --ignore-unrecognized-flags --packages=/Users/leafp/src/dart-repo/sdk/.packages --format=json --no-hints /Users/leafp/src/dart-repo/sdk/tests/co19/src/Language/Mixins/declaration_t01.dart
Done dart2analyzer-none release_x64 co19/Language/Mixins/declaration_t01: pass

=== All 1 test passed ===
{"name":"co19/Language/Mixins/declaration_t01","configuration":"analyzer-asserts-strong-mac","suite":"co19","test_name":"Language/Mixins/declaration_t01","time_ms":3386,"result":"Pass","expected":"CompileTimeError","matches":false}
```

Per @athomas:

```
note the "matches":false part. Somehow, the result is recorded as "Pass" instead of "CompileTimeError"
I suspect this is the same confusion about what "Pass" means in the test runner.
```

@athomas suggests that the test runner should fail to parse the test in this case so that we will detect these kind of errors in the roll.

cc @munificent @eernstg

**Comment by munificent** [comment]
Oh dear. Yeah, the test file parser should flag those cases. Ideally, we would migrate *all* of the `/* @compile-error */` tests to real static error tests, now that the latter exists. It's strictly superior.

**Comment by athomas** [comment]
FYI, the Unipro team is working on migrating the old @compile-error tests to static error tests (https://github.com/dart-lang/co19/issues/1086). Once that lands we should remove the support for them from the test runner.

**Comment by athomas** [comment]
Awesome, thanks @munificent!

**Comment by munificent** [comment]
It was very satisfying cleaning up these old tests. :)
