### ISSUE TITLE
[CP][beta channel] Please cherry pick a dart_style DEPS roll into beta

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#45647]
**commit(s) to merge**: c8b3fb1e7163ba6000b89aa2bb4f30b39ae82acb

Code review on master is: https://dart-review.googlesource.com/c/sdk/+/194883

**merge instructions**: It's a one line DEPS change.

**What is the issue**: The roll of dart_style earlier this week introduced a formatting change that was deliberate but turned out to be overwhelmingly unpopular.

More detail: The previous roll of dart_style into the SDK introduces four changes:

1. Support non-function type aliases.
2. Support the new `<<<` operator.
3. Support generic metadata annotations.
4. Change the way nested conditional expressions are formatted (https://github.com/dart-lang/dart_style/issues/722).

The first fix is critical. The last two were until we decided to push those language features out a release. Now they are harmless. The last change, unfortunately, turned out to not be a change for the better in the eyes of users.

**What is the fix**: [Reverted the change the conditional formatting](https://github.com/dart-lang/dart_style/pull/1019) and left the others.

**Why cherrypick**: Users who auto-format their code will mostly likely be unhappy when the flattened formatting is applied, and then annoying by the churn when a later release of Dart reverts that formatting back to the original. This ensures they never see the bad formatting.

**Risk**: Minimal. Reverting back to previous known-good behavior. The change itself is just commenting out a few lines of code. Dartfmt has thorough test coverage.

**Link to original  issue(s)**: https://github.com/dart-lang/dart_style/issues/722

Sorry for the churn and late notice. I believed this formatting change would be innocuous and well-received based on comments on the original request.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by lukepighetti** [comment]
Reverting this is definitely the right move, in my opinion. (Issue OP here)

**Comment by christopherfujino** [comment]
for the engineer doing the cherrypick, there was a mistake on the release doc as to which dart release is the branch point. <b>This cherrypick should be applied to the [2.13.0-211.0.dev](https://github.com/dart-lang/sdk/commit/dda1a31495e39a77b463753caf1295eaa47bc983) release.</b>

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved in SCRUM

**Comment by athomas** [comment]
Merged to beta in 94162a2 (2.13.0-211.6.beta).

**Comment by munificent** [comment]
Thank you!
