### ISSUE TITLE
Suggest importing packages for extension methods the same way as other imports

### ISSUE THREAD

**Issue by ChristianKleineidam** [dart-lang/sdk#45643]
I'm using the [time ](https://pub.dev/packages/time) plugin and added it in pubspec.

When I write `Duration interval = 1.hours;` in a class that doesn't have `import 'package:time/time.dart';` I currently have to manually add  `import 'package:time/time.dart';` without AndroidStudio providing me the import via alt+enter+enter. 
In practice this is particularly annoying when I refactor and for a moment remove the usage as pressing Crtl+S in my setup automatically deletes unused imports.

**Comment by bwilkerson** [comment]
For future reference, this would likely be an enhancement to `ImportLibrary`.

**Comment by scheglov** [comment]
This was fixed in 979f3ea79ee188ec2e0c039a3186ebd28e0f636c.
