### ISSUE TITLE
Dart Analyzer and  x = 5 ~ 3

### ISSUE THREAD

**Issue by drpond1** [dart-lang/sdk#45659]
The DART analyzer does not flag
   int x = 5 ~ 3;

Webdev does correctly explain the error,  so this is probably a low priority concern.
If I restart the analyzer,  I still get no errors detected.

Versions
Analysis server version: 1.32.4
Dart SDK: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64

Analysis options
Implicit dynamic: true
Implicit casts: true
Feature set: FeatureSet{constant-update-2018, control-flow-collections, extension-methods, non-nullable, set-literals, spread-collections}

Generate hints: true

**Comment by eernstg** [comment]
Apparently, the analyzer does not recognize that `~` is a unary operator.

**Comment by drpond1** [comment]
Webdev correctly reports:
Error: '~' isn't a binary operator.

**Comment by eernstg** [comment]
Right, the common front end does catch the error, so `dart`, `dart2js` etc. do report it.

**Comment by lrhn** [comment]
The analyzer seem to think that an `operator~()` declaration can be called using infix (and ignoring the second operand).
It only seems to affect `~`, the only operator which is user-overridable, prefix and not also infix.

**Comment by lfkdsk** [comment]
try to fix with : https://github.com/dart-lang/sdk/pull/45751/

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/195882
