### ISSUE TITLE
Proposal add Iterator<T>.takeAllWhere(test)

### ISSUE THREAD

**Issue by jeroen1602** [dart-lang/sdk#45654]
This tracker is for issues related to:

* Dart core libraries ### ("dart:core")

Say you have a list like this
```dart
final items = [1, 2, 3 ,4 ,5 ,6 ,7 ,8 ,9];
```

And you want all the items where the test `item > 3 && item < 5` is true. If you want to do this currently you will need to create a for loop.

```dart
final filteredItems = [];
for (final item in items) {
  if (item > 3 && item < 5) {
    filteredItems.add(item);
  }
}
```

I propose adding a function like `takeWhile` that would take all the items where a certain condition is true instead of only the first items. This would look something like this:

```dart
final filteredItems = items.takeAllWhere((item) => (item > 3 && item < 5)).toList();
```

**Comment by jeroen1602** [comment]
I already coded an extension for anyone who wants to use this already.

[IterableTakeAllWhereExtension.dart.zip](https://github.com/dart-lang/sdk/files/6291610/IterableTakeAllWhereExtension.dart.zip)

**Comment by lbguilherme** [comment]
`takeWhile` already does exactly this, doesn't it?

```dart
final filteredItems = items.takeWhile((item) => (item > 3 && item < 5)).toList();
```

**Comment by jeroen1602** [comment]
No `takeWhile` will only take items until the test becomes false. So it will get to the first item, the test will fail and it will return an empty list. So to make it work you would first need to skip, given the list is even sorted.

**Comment by lbguilherme** [comment]
There is [`where`](https://api.dart.dev/stable/2.10.4/dart-core/Iterable/where.html) then.

```dart
final filteredItems = items.where((item) => (item > 3 && item < 5)).toList();
```

**Comment by jeroen1602** [comment]
You are right, I was under the impression that `where` returned a single item. Teaches me to read the docs better.

I'll close the issue now.
