### ISSUE TITLE
Add swap option as quickfix to conditional operator

### ISSUE THREAD

**Issue by guenth39** [dart-lang/sdk#45669]
I would like to have Quick Fix to Swap the options of a ternary operation like swap with parent or swap with child.

![image](https://user-images.githubusercontent.com/29251617/114525177-2eb21a80-9c46-11eb-9dc6-2ca63bcb1a96.png)

**Comment by Levi-Lesches** [comment]
I'm working on #46915 and #46025, but I can try this after I'm done
