### ISSUE TITLE
[analyzer] Constant evaluation does not detect null related error

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45672]
Consider the following program:

```dart
const dynamic d = null;
const xs = <int>[d];

void main() {
  print(xs);
}
```

This program is accepted by the analyzer (97742f827a207454102da154ec3befe29b624e80) with no errors (and no other diagnostic messages).

However, the program is purely null safe and should be assumed to run with sound null checking, and hence the `int` type argument should be considered to denote the type `int` (not `int*`). Cf. [this section](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#constant-instances):

> With sound null checking, all generic const constructors and generic const literals
> are evaluated using the type arguments provided

**Comment by lfkdsk** [comment]
Hi, I try to fix this issue with https://github.com/dart-lang/sdk/pull/45750

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/196042
