### ISSUE TITLE
pragma vm:notify-debugger-on-exception does not work on async methods

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#45673]
The pragma `vm:notify-debugger-on-exception` does not work as expected for async methods. If you run the following code with a debugger attached (with break on exception enabled) it will not break on the `throw 'Foo';` line as expected.

```dart
void main() {
  foo();
}

@pragma('vm:notify-debugger-on-exception')
Future<void> foo() async {   // <<<< note the async here
  try {
    throw 'Foo';
  } catch (e) {
    print('exception caught');
  }
  return Future.value();
}
```

See also https://github.com/flutter/flutter/issues/17007#issuecomment-818318520

Once this is fixed, there's one method in the flutter framework to which we should add the pragma:

https://github.com/flutter/flutter/blob/12ec7dc8790feb437566c8b8e6b6e883a110b4d1/packages/flutter/lib/src/services/binding.dart#L275

**Comment by goderbauer** [comment]
Thanks for the fix!

**Comment by cskau-g** [comment]
You're welcome!
This should now account for the three special cases for the yielding functions (async, sync*, async*) that I could think of.
But if you should happen to run into some other case that isn't working as expected, let me know and I can have another look.
