### ISSUE TITLE
[null safety] FontFaceSet.add has the wrong type in dart:html

### ISSUE THREAD

**Issue by mdebbar** [dart-lang/sdk#45676]
In `dart:html`, the `add` method on `FontFaceSet` is expecting the return value to be a non-null `FontFaceSet` type. But firefox is returning `null`.

This is causing flutter web apps to crash on firefox. The issue is reproducible on fresh apps created by `flutter create` with no changes.

**Comment by nshahan** [comment]
cc @srujzs
