### ISSUE TITLE
[ffi]Is it necessary to manually free the memory?

### ISSUE THREAD

**Issue by xuexin** [dart-lang/sdk#45689]
```
class RawImage extends Struct {
  @Int32()
  external int length;
  external Pointer<Uint8> bytes;
}

Pointer<RawImage> mallocRawImage(Uint8List bytes) {
  final bytesPointer = bytes.allocatePointer();
  final refPointer = malloc<RawImage>();
  refPointer.ref
    ..length = bytes.length
    ..bytes = bytesPointer;
  return refPointer;
}
extension Uint8ListBlobConversion on Uint8List {
  Pointer<Uint8> allocatePointer() {
    final blob = malloc<Uint8>(length);
    final blobBytes = blob.asTypedList(length);
    blobBytes.setAll(0, this);
    return blob;
  }
}
```
I manually malloc memory for Struct to pass it to native, should I manually free the Pointer<RawImage> and the Pointer<Uint8>? And how about the Struct returned from native?

**Comment by dcharkes** [comment]
Hi @xuexin,

When you `malloc`/`calloc`  you should `malloc.free`/`calloc.free` it.

When a struct gets returned by value it is backed by `TypedData` instead of `Pointer` and lives in the Dart heap. So in that case it is garbage collected automatically.

**Comment by dcharkes** [comment]
I can take a look into https://github.com/dart-lang/sdk/issues/45697, that would enable creating structs backed by TypedData also when passing them as arguments.

Of course it will take a while before that would be available in the stable Dart release, so for now you need to be careful to free your allocated structs.

**Comment by xuexin** [comment]
@dcharkes 
Thanks for your answer
