### ISSUE TITLE
Hide dart:web_sql in generated dartdocs

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#45687]
We plan on eliminating the API soon, but we can start by hiding it from our docs!

**Comment by sigmundch** [comment]
@devoncarew @jcollins-g what would be the right process to get this library hidden? 

(also, procedural question: what's the best way to track issues that directly affect dartdoc? Should we file this also under https://github.com/dart-lang/dartdoc?)

**Comment by jcollins-g** [comment]
the quickest way to hide a library is to use `@nodoc` directly inside the documentation comment.  You can also use the nodoc field in dartdoc_options.yaml.

https://github.com/dart-lang/dartdoc#excluding-from-documentation

**Comment by jcollins-g** [comment]
Note that `@nodoc`, a bit confusingly, is not actually an annotation, just a literal string inside the documentation comment.

**Comment by jcollins-g** [comment]
Issues that require dartdoc changes are best filed under https://github.com/dart-lang/dartdoc.

**Comment by sigmundch** [comment]
Great, thanks!
