### ISSUE TITLE
[CP][beta channel] Cherry-pick dart:html bug fix

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#45686]
**commit(s) to merge**: TBD (CL about to land)

**merge instructions**: clean merge

**What is the issue**: fix bug in algorithm in dart:html

**What is the fix**: small change to the algorithm

**Why cherrypick**:  address bug b/143778164

**Risk**: low

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @srujzs

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved

**Comment by srujzs** [comment]
Commit hashes:

For the fix: ce5a1c2392debce967415d4c09359ff2555e3588
For the CHANGELOG: adc36a6563614a7c3ba29d9911e57fc68e7d9ac0

**Comment by athomas** [comment]
Merged to beta in go/dart-hash/94162a28126443d4c3f1a7c9267ec1d69d38b330 (2.13.0-211.6.beta).
