### ISSUE TITLE
vm_snapshot_analysis should migrate to null safety

### ISSUE THREAD

**Issue by jmagman** [dart-lang/sdk#45683]
`vm_snapshot_analysis` 0.6.0 is not null safe:
```
environment:
  sdk: '>=2.8.0 <3.0.0'
```

This is preventing the `flutter_tool` from migrating its size analyzer library to null safety.
https://github.com/flutter/flutter/blob/74bd7b6f6db6433783a36f94d9e43173745187f4/packages/flutter_tools/lib/src/base/analyze_size.dart#L10
```dart
import 'package:vm_snapshot_analysis/treemap.dart';
```

\cc @mraleph

**Comment by mraleph** [comment]
Migration CL is up for review: https://dart-review.googlesource.com/c/sdk/+/195263
