### ISSUE TITLE
[CP][stable channel] Fix Dart VM compiler crashes when compiling initializers containing async closures

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#45695]
**commit(s) to merge**: bed058967673986153bfd965772c4032e706befe

**merge instructions**: clean merge

**What is the issue**: Dart VM compiler (both JIT and AOT) would crash when compiling initialiser containing an `async` closure inside (e.g. `final field = () async {  }`) due to accessing parameter variables on the wrong scope when building scopes for the initializer. 

**What is the fix**: Patch removes incorrect access to the parameter variables in scope building algorithm, which fixes the crash. 

**Why cherrypick**: 2 flutter crashes were reported recently which can be traced back to this issue (https://github.com/flutter/flutter/issues/79949, https://github.com/flutter/flutter/issues/80402). As always with this type of crashes it is very hard for end user to track it down to the actual source of failure in their code.

**Risk**: Minimal, the patch is self-contained. Has been validated on master for 1 month.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/45306 (all other issues are linked into it)

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by a-siva** [comment]
strongly support approving this CP.

**Comment by mraleph** [comment]
@kf6gpe has told me that Flutter CP window is closed so there would be no more stable hot fix releases unfortunately.

**Comment by mraleph** [comment]
Disregard my previous comment, I should have read the chat that we are trying to push this through.

**Comment by sigmundch** [comment]
I also support this CP

**Comment by franklinyow** [comment]
Looks like there are enough people supporting this.
Approved
FYI @kf6gpe

**Comment by franklinyow** [comment]
Description:
Fix Dart VM compiler crashes when compiling initializers containing async closures, see #45306 for detail

**Comment by athomas** [comment]
Merged to stable in b6f9dbc570c4e9065e922228c9747b4ea8104904 (2.12.4).
