### ISSUE TITLE
LSP code completion marks getters as deprecated when only the setter is

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45698]
The analyzer code has a lot of deprecated setters which are causing identifiers to be struck through in code completion even though you pay be using the getter:

<img width="809" alt="Screenshot 2021-04-14 at 13 53 47" src="https://user-images.githubusercontent.com/1078012/114713331-eddf0200-9d28-11eb-81e9-374d0e56ef51.png">

<img width="714" alt="Screenshot 2021-04-14 at 13 53 52" src="https://user-images.githubusercontent.com/1078012/114713334-ef102f00-9d28-11eb-9d63-4d3e207dd833.png">

@bwilkerson I don't know if the code completion has enough context (or could even know) if you're going to set this or not so I think it would make sense to either only strike through if both are depcreated, or just read from the getter instead. WDYT?

**Comment by bwilkerson** [comment]
I agree. There is code (https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/completion/dart/suggestion_builder.dart#L114) that attempts to fix this problem, but it appears that either it fails sometimes of there's another path that doesn't take this into account.

**Comment by DanTup** [comment]
Nope, all working as expected - I was unexpected using a stable SDK and your fix was more recent than that (acdd5231fdd8297f056f3b792e4dd5a11ea19001). All works fine on latest!
