### ISSUE TITLE
[CP][beta] Prevent public dart:io api change to OSError from going to stable.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45706]
commit(s) to merge: 8800decca48b7062f2f7a862c7605c5efff0f6e4

merge instructions: clean merge

What is the issue: Bugfix https://dart.googlesource.com/sdk/+/e190a85f4936fb92dd1db5b0c19a7f1b8a4199d4 introduced a change to public dart:io OSError class. We want to revert public api change.

What is the fix: Moves error code getter from public method on OSError class to private getter in socket patch class.

Why cherrypick: Prevent unnecessary public api change

Risk: low

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @a-siva @sortie

**Comment by aam** [comment]
cc @mraleph @lrhn

**Comment by vsmenon** [comment]
lgtm

**Comment by lrhn** [comment]
LGTM, ship it!

**Comment by aam** [comment]
@franklinyow @kf6gpe is this CP still on radar or has it slipped through the cracks?

**Comment by a-siva** [comment]
It is still on the radar, the cherry pick window opens this week and closes on 4/26 (this CP is in the list for Dart).

**Comment by aam** [comment]
Cool, thanks. I didn't realize we wait with cherry picking, wait until window opens.

**Comment by franklinyow** [comment]
Approved in SCRUM

**Comment by athomas** [comment]
Merged to beta in 5cae07b3980f4684d3d477457c307a67235adf99 (2.13.0-211.13.beta).
