### ISSUE TITLE
Failures on [vm] Handle WSRs more generally in v8 snapshot profile writing.

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#45702]
There are new test failures on [[vm] Handle WSRs more generally in v8 snapshot profile writing.](https://github.com/dart-lang/sdk/commit/dc88076767c19a46669255d44ab4fa440f2293a2).

The tests
```
ffi_2/function_callbacks_test/8 Crash (expected Pass)
language_2/deferred/split_constants_canonicalization_test/0 Crash (expected Pass)
vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test Crash (expected Pass)
vm/dart_2/deferred_loading_call_modes_test/0 Crash (expected Pass)
vm/dart_2/deferred_loading_call_modes_test/1 Crash (expected Pass)
vm/dart_2/split_literals_test/object RuntimeError (expected Pass)
vm/dart_2/v8_snapshot_profile_writer_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-simarm-crossword
dartkp-linux-debug-x64
```

Approving these temporarily, looking into the failure now.

**Comment by alexmarkov** [comment]
These tests are also failing on the following NNBD configurations:
```
dartkp-strong-linux-debug-simarm-crossword
dartkp-strong-linux-debug-x64
dartkp-weak-asserts-linux-debug-x64
dartkp-weak-asserts-linux-debug-simarm-crossword
```

@sstrickl If there's no quick fix available, does it make sense to revert the change which caused these failures?

**Comment by sstrickl** [comment]
Only AOT tests that don't have a dispatch table but go through WriteDispatchTable will be affected, which only seems like a handful of tests that turn on flags not usually used in practice.

I have had a quick fix ready for it in CL [https://dart-review.googlesource.com/c/sdk/+/195272](195272), but unfortunately _that_ is failing on x64c for some reason, which I am investigating and is proving harder to track down than I expected. I'm wondering whether to bother @rmacnak-google about it and see if he can find what's going on, because it looks like just weird corruption in compressed mode.

**Comment by rmacnak-google** [comment]
You can land your change and leave x64c broken to make some progress. I'll take a look at x64c next week.

**Comment by sstrickl** [comment]
Okay, have approved the failure on dartk-linux-debug-x64c (I assume it will fail on other debug-x64c configs so will approve post-landing.) and am submitting it now.

**Comment by sstrickl** [comment]
Fix did show issues on other builders as well. Product makes sense, as dropped Code objects weren't handled in CreateArtificalNodeIfNeeded (fixing that now). Hoping that one of the other bots, if not the same issue, also show what was going on with x64c.
