### ISSUE TITLE
[analyzer] Missing error when function type is used as on-type of mixin

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45701]
Consider the following program:

```dart
mixin M on Function() {}
void main() {}
```

It is a [compile-time error](https://github.com/dart-lang/language/blob/ff957765b7dd4495bdb2a74157671a0d019ef48d/specification/dartLangSpec.tex#L5313) if a mixin has an on-type which is a function type, but the analyzer (0c22d58a7ee942cf8ac9cebdac3ba2dac0b6f9a6) does not report any issues for this program.

**Comment by lfkdsk** [comment]
Also fix in pr : https://github.com/dart-lang/sdk/pull/45735/

**Comment by srawlins** [comment]
Analyzer now reports `expected_named_type` here.
