### ISSUE TITLE
[analyzer] Function is a built-in identifier, but no error is emitted when it is used to name a type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45704]
This is the analyzer specific issue for #45703, which has the details.

**Comment by lfkdsk** [comment]
Hi @eernstg , I try to fix this with https://github.com/dart-lang/sdk/pull/45735

**Comment by eernstg** [comment]
Thanks, @lfkdsk! I suspect that the change would need to be made at a different level (where the treatment of built-in identifiers in general is handled), but @scheglov knows a lot more about that than I do. ;-)

**Comment by scheglov** [comment]
I started this in https://dart-review.googlesource.com/c/sdk/+/200080, but it seems that there are more changes to CFE than I can do on my own.

**Comment by devoncarew** [comment]
> I started this in https://dart-review.googlesource.com/c/sdk/+/200080, but it seems that there are more changes to CFE than I can do on my own.

@scheglov - would it be good to have input / assistance from the CFE team for this? cc @johnniwinther

**Comment by johnniwinther** [comment]
@jensjoha Could you take a look at the CL https://dart-review.googlesource.com/c/sdk/+/200080 from @scheglov ?

**Comment by jensjoha** [comment]
This should be fixed with 25dcfca3c23e5ca6870b4c3fc614750377d8efa1.
