### ISSUE TITLE
flaky pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test turned consistent Timeout

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45713]
Flaky pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test turned consistent Timeout on [this build](https://dart-ci.appspot.com/log/pkg-linux-debug/unittest-asserts-debug-linux/10370/pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test)

**Comment by alexmarkov** [comment]
The tests

```
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_sound_test
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_unsound_test
```

also turned from flaky to Timeout in `unittest-asserts-debug-linux` configuration (on `pkg-linux-debug` bot).

**Comment by sstrickl** [comment]
Has happened again on [this build](https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-linux-release/15683/overview).

**Comment by alexmarkov** [comment]
`pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test` flipped from flaky to Timeout once again.

/cc @annagrin @sigmundch

**Comment by annagrin** [comment]
@alexmarkov could you please add a link to the latest failure?

**Comment by alexmarkov** [comment]
Log when this test started failing recently:
https://dart-ci.appspot.com/log/pkg-linux-debug/unittest-asserts-debug-linux/11362/pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test
(available from [Results Feed](https://dart-ci.firebaseapp.com/))

The most recent log:
https://dart-ci.appspot.com/log/any/unittest-asserts-debug-linux/11409/pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test
(available from [Current Test Results](https://dart-ci.firebaseapp.com/current_results/))

**Comment by Markzipan** [comment]
I'm taking a look at this now. I should have a fix out relatively soon. It seems that the chrome invocation loop used in these tests has somehow regressed, leading to more frequent timeouts.

**Comment by annagrin** [comment]
Thanks Mark for looking at this!

**Comment by Markzipan** [comment]
This turns out to be some strange timeout issue related to running Chrome in headless mode on our Windows trybots. This fails to reproduce on my local Windows machine, so it's possible it's some combination of headless Chrome and the flavor/config of Windows used in our testing framework. I have a fix out for review
