### ISSUE TITLE
pragma vm:notify-debugger-on-exception does not work on functions defined in functions

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#45710]
The pragma `vm:notify-debugger-on-exception` does not work as expected for functions defined within a function. If you run the following code with a debugger attached (with break on exception enabled) it will not break on the `throw 'Hello';` line as expected.

```dart
void main() {
  foo();
}

void foo() {
  @pragma('vm:notify-debugger-on-exception')
  void bar() {
    try {
      throwingMethod();
    } catch (e) {
      print('exception caught');
    }
  }
  bar();
}

void throwingMethod() {
  throw 'Hello';
}
```

This was discovered while working on https://github.com/flutter/flutter/pull/78649.

Once the problem is fixed Flutter should refactor the code in the `_LayoutBuilderElement._layout` to turn the anonymous closure in there into a named one and apply the pragma to it.

**Comment by cskau-g** [comment]
Support for pragmas like these has now landed.
