### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Failed to rerun migration

### ISSUE THREAD

**Issue by khongorzul1120** [dart-lang/sdk#45722]
Failed to rerun migration

Error: ConflictingEditException: {"offset":38304,"length":2,"replacement":""} conflicts with {"offset":38301,"length":7,"replacement":""}

Please fill in the following:

**Name of package being migrated (if public)**:
**What I was doing when this issue occurred**:
**Is it possible to work around this issue**:
**Has this issue happened before, and if so, how often**:
**Dart SDK version**: 2.12.2
**Additional details**:

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
#0      addEditForSource (package:analyzer_plugin/src/protocol/protocol_internal.dart:58:7)
#1      SourceFileEdit.add (package:analyzer_plugin/protocol/protocol_common.dart:5544:32)
#2      addEditToSourceChange (package:analyzer_plugin/src/protocol/protocol_internal.dart:73:12)
#3      SourceChange.addEdit (package:analyzer_plugin/protocol/protocol_common.dart:5240:7)
#4      DartFixListener.addEditWithoutSuggestion (package:nnbd_migration/src/front_end/dartfix_listener.dart:28:18)
#5      NullabilityMigrationAdapter.addEdit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:538:14)
#6      NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:189:16)
#7      NonNullableFix.finalizeUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:115:15)
#8      _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1159:21)
#9      _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1156:28)
#10     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#11     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1156:5)
<asynchronous suspension>
#12     MigrationCliRunner._rerunFunction (package:nnbd_migration/migration_cli.dart:977:14)
<asynchronous suspension>
#13     NonNullableFix.rerun (package:nnbd_migration/src/front_end/non_nullable_fix.dart:169:17)
<asynchronous suspension>
#14     PreviewSite.rerunMigration (package:nnbd_migration/src/preview/preview_site.dart:597:22)
<asynchronous suspension>
#15     PreviewSite.handlePostRequest (package:nnbd_migration/src/preview/preview_site.dart:454:9)
<asynchronous suspension>
#16     HttpPreviewServer._handlePostRequest (package:nnbd_migration/src/preview/http_preview_server.dart:109:5)
<asynchronous suspension>
#17     HttpPreviewServer._handleServer.<anonymous closure> (package:nnbd_migration/src/preview/http_preview_server.dart:119:9)
<asynchronous suspension>

```

**Comment by stereotype441** [comment]
Hi @khongorzul1120, thanks for the bug report!

A few questions:
- Is the code you were migrating publicly available?  (It's ok if it isn't, it's just sometimes easier for us to debug if it is)
- Can you tell us what you were doing when the issue occurred?
- How frequently does this happen?  Have you found a sequence of steps that reliably causes the issue to arise?
- Have you been able to make progress with the migration tool in spite of this bug, or does it prevent you from getting anything done?

(Note that there is one other bug that looks similar: #45554.  I haven't had a chance to investigate that issue yet, but the person who filed that bug appears to have found a workaround.  Does their workaround help you any?)

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
