### ISSUE TITLE
Dart analyzer and Intellij IDEA is once in a while unusable - and Intellij IDEA just becomes nothing but a raw text editor

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#45723]
Hi thanks for the lib! But such behavior of dart analyzer & intellij idea is driving me crazy...

I write Flutter program using Intellij IDEA (with dart & flutter plugins), but the experience is very painful and even unuseable recently :( Let me try to explain it in detail in order to seek the root cause easier:

Firstly, once in a while, the following happens: The **syntax highlight** disappeaers (every word is white except for keywords; but you know, normally there are many colors, such as purple for fields). The **jumping** does not work completely. For example, originally I can `cmd+B` on a class/method name to jump to the definition of the class/method, but now I cannot. In short, **almost everything does not work** and Intellij IDEA just work as if it is a **pure text editor**!

Example screenshot:

![image](https://user-images.githubusercontent.com/5236035/114978035-3e866480-9ebb-11eb-84b6-e86fdc657576.png)

Secondly, I also observe that, when the things above happen, the **code formatter** also behaves very strangely. When I trigger "format the file", it takes many seconds, and the finally formatted file is strange, in a format that is **contrary to the normal format** required by Flutter. I guess it is like formatting just partially, but I am not sure. For example, in the screenshot above, I originally added just one or two lines of code, and format it, and it looks like what is in the screenshot. You know, the standard formatting is completely not like this.

Here is another example of strange formatting. Left hand side is the code formatted when flutter behaves normally; right hand side is formatted when it is strange.

![image](https://user-images.githubusercontent.com/5236035/114978292-9f15a180-9ebb-11eb-98c0-c9f723530ace.png)

![image](https://user-images.githubusercontent.com/5236035/114978312-a5a41900-9ebb-11eb-87b6-d161aa245360.png)

![image](https://user-images.githubusercontent.com/5236035/114978331-ab016380-9ebb-11eb-803b-cce668bf4137.png)

Thirdly, such case sometimes last for a few minutes, sometimes even >15 minutes or longer. I have tried the following, but sometimes it works, sometimes it does not work:

* exit intellij, delete the whole `~/.dartServer` folder (about 1GB), restart intellij
* wait for minutes, even for half an hour
* try to continue programming as if intellij is a raw text editor (or worse)

* Dart SDK Version latest
* Whether you are using Windows, MacOSX, or Linux (if applicable) macos
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) no, intellij

more info that is possbly related: 

the analysis-driver folder is about 1GB

![image](https://user-images.githubusercontent.com/5236035/114977530-61fcdf80-9eba-11eb-9346-a73e120212b8.png)

I have read: https://github.com/flutter/flutter-intellij/issues/4012 , https://github.com/flutter/flutter-intellij/issues/4142 , https://github.com/dart-lang/sdk/issues/28383 , etc

**Comment by gumbarros** [comment]
```
if(details != null and details.appointments.length == 1){

}
```

Do you have a if like this in your code? I solved the problem removing this if

**Comment by fzyzcjy** [comment]
@gumbarros I have >10k lines of flutter code... it is not very possible to find out and remove such lines

**Comment by gumbarros** [comment]
> @gumbarros I have >10k lines of flutter code... it is not very possible to find out and remove such lines
> 
> wait a bit: you should use '&&' instead of 'and'!

I found this notification 2 years later lol, but my IDE was crashing because of the 'and' instead  of the '&&'

**Comment by mraleph** [comment]
This is unactionable without reproduction of some sort.
