### ISSUE TITLE
Can't null check late final variables 

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#45732]
For lazy values, it's common to use the `??=` operator instead of a null check. But `late final` variables marked as non-nullable types can't be null-checked: 

```dart
class A {
  late final String _value;
  String get value {
    _value ??= 'hello, world';
    return _value;
  }
}
```

```
warning • The left operand can't be null, so the right operand is never executed at src/app.dart • (dead_null_aware_expression)
          Try removing the operator and the right operand.
```

If this is changed to an if statement, this results in a "condition is always false"

```dart
class A {
  late final String _value;
  String get value {
    if (_value == null) _value = 'hello, world';
    return _value;
  }
}
```

```
   info • The operand can't be null, so the condition is always false at src/app.dart:18:16 • (unnecessary_null_comparison)
          Try removing the condition, an enclosing condition, or the whole conditional statement.
```

[DartPad snippet](https://dartpad.dev/c99fc6c09ace0e990108a6a47d0e4528?null_safety=true)

**Comment by lrhn** [comment]
Correct, you can't `null`-check a non-nullable variable. It won't ever be `null`. Late variables are *not* the same thing as nullable variables.
You also can't check whether a late variable has been initialized, so if your existing code depends on *checking* whether initialization is necessary (perhaps with a `null` check), then it doesn't translate to a `late` variable. 
That's OK, late variables are intended to handle specific cases where you *want* "late initialization" (not at the declaration point) of a variable without the compiler being able to ensure that you only read the variable after initialization.
In this case, you might just want *lazy* initialization (initialized on first read).

Either just keep the variable nullable, non-`final` and non-`late`, that's a perfectly good implementation strategy.
You can write the getter `null`-safely as:
```dart 
  String? _value;
  String get value => _value ??= 'hello, world';
```
and you can check whether `_value` has been initialized or not.

If you want the variable to be *lazy*, you can use `late` and `final`:
```dart
  late final String value = 'hello, world';
```
That variable will be initialized the first time it's read, and you don't need any extra getter. You won't be able to check from a third method whether it has been initialized. If that's necessary, use the nullable implementation.

**Comment by johnpryan** [comment]
Thanks for the detailed answer!
