### ISSUE TITLE
Pointer<Utf8> toDartString crashes the application

### ISSUE THREAD

**Issue by kirill-21** [dart-lang/sdk#45734]
If Pointer of type Utf8 is equal to nullptr, and you try to call toDartString method on it - application closes without any errors.
```
static int findWindowA(String? lpClassName, String? lpWindowName) {
    // Convert lpClassName to a native utf8 string if it is not null
    Pointer<Utf8> _lpClassName =
        lpClassName == null ? nullptr : lpClassName.toNativeUtf8();

    // Convert lpWindowName to a native utf8 string if it is not null
    Pointer<Utf8> _lpWindowName =
        lpWindowName == null ? nullptr : lpWindowName.toNativeUtf8();

    print(_lpClassName.toDartString());

    final _findWindowA = _user32.lookupFunction<
        Int32 Function(Pointer<Utf8> _lpClassName, Pointer<Utf8> _lpWindowName),
        int Function(Pointer<Utf8> _lpClassName,
            Pointer<Utf8> _lpWindowName)>('FindWindowA');

    return _findWindowA(_lpClassName, _lpWindowName);
  }
```

**Comment by lrhn** [comment]
Seems like expected behavior for a native null-pointer dereference. I recommend not doing that 😁 .

Should the `dart:ffi` functions recognize null pointers?

**Comment by dcharkes** [comment]
This is expected behavior indeed.

> application closes without any errors

@kirill-21 You also wrote this on your other issue. I recommend setting up your OS settings or running Dart in a way which shows you the crashes rather than hides them.

> Should the `dart:ffi` functions recognize null pointers?

This is `package:ffi`, and maybe we should, filed an issue.

**Comment by kirill-21** [comment]
> This is expected behavior indeed.
> 
> > application closes without any errors
> 
> @kirill-21 You also wrote this on your other issue. I recommend setting up your OS settings or running Dart in a way which shows you the crashes rather than hides them.
> 
> > Should the `dart:ffi` functions recognize null pointers?
> 
> This is `package:ffi`, and maybe we should, filed an issue.

In my other issue is was definitely not a nullptr. And is not it bad that you even cannot check if the value is null without crashing the application?
