### ISSUE TITLE
Is there any guidance on adding CFE tests?

### ISSUE THREAD

**Issue by lfkdsk** [dart-lang/sdk#45738]
I noticed that there are a lot of locations for CFE tests in the current project, but it's not quite clear where the relevant commands and added tests are.

**Comment by asashour** [comment]
One can start with [building](https://github.com/dart-lang/sdk#building-dart) the SDK, then run the suite tests of `front-end`. There is an `UPDATE_EXPECTATIONS` to automatically write them.  Have a look at https://github.com/dart-lang/sdk/issues/44485#issuecomment-751245373



[strong_suite](https://github.com/dart-lang/sdk/blob/main/pkg/front_end/test/fasta/strong_suite.dart) is one the main suites.
