### ISSUE TITLE
Failures on [vm/compiler] Fix relocator to take out-of-range backwards calls into acount

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#45754]
There are new test failures on [[vm/compiler] Fix relocator to take out-of-range backwards calls into acount](https://github.com/dart-lang/sdk/commit/d41f9a738e3d3d35b5cbeeec1974ef8e23093c65).

The tests
```
vm/cc/PCRelativeCallPatterns Fail (expected Pass)
```
are failing on configurations
```
dartk-win-debug-x64
dartk-win-release-x64
```

**Comment by mkustermann** [comment]
Already fixed in 8156646b0c92f0e1d83ef62a84745c37c4cd1d72
