### ISSUE TITLE
dds package should migrate to null safety

### ISSUE THREAD

**Issue by jmagman** [dart-lang/sdk#45756]
`dds` 1.7.6 is not null safe:
https://github.com/dart-lang/sdk/blob/96cf91bea3d19a284d1c9ebaf2180719aa00610d/pkg/dds/lib/dds.dart#L5

This is preventing the `flutter_tool` from migrating its size analyzer library to null safety.
https://github.com/flutter/flutter/blob/6b3093b6afd6a47e57c07f7e3f701d5e97073fc8/packages/flutter_tools/lib/src/base/dds.dart#L9

\cc @bkonyi

**Comment by bkonyi** [comment]
Thanks for formally filing an issue for this. How urgently does this need to be migrated? It's on my radar, but I have a fairly involved DDS change in-flight right now which may take some time to land so I won't be able to get started on migration until that's done.

**Comment by jmagman** [comment]
> Thanks for formally filing an issue for this. How urgently does this need to be migrated? 

Not too urgent, though it is I believe the last unsafe package the tool depends on.  

> It's on my radar, but I have a fairly involved DDS change in-flight right now which may take some time to land so I won't be able to get started on migration until that's done.

Any idea of a general ETA for when that would be done?  Are we talking weeks, months..?

**Comment by bkonyi** [comment]
[This is the change in question](https://dart-review.googlesource.com/c/sdk/+/188361) that needs to land. It's quite large and is going through initial review, so _hopefully_ it'll land in the next week or so. I'd say mid-May would be a conservative estimate.

**Comment by bkonyi** [comment]
@jmagman I've got a local version of DDS migrated but there's currently two packages that DDS depends on that haven't been migrated yet (`package:devtools_shared` and `package:sse`). Are you aiming to enable strong null safety at this point?

**Comment by jmagman** [comment]
> `package:devtools_shared` and `package:sse`

(Note to self: https://github.com/flutter/devtools/issues/2978 and https://github.com/dart-lang/sse/issues/47)

@bkonyi Would like to in the tool within the next few months.  dds isn't currently the bottleneck, but I _believe_ it is the last imported dependency that isn't null safe (though the tests also use a null unsafe version of mockito).

**Comment by bkonyi** [comment]
Okay, that's totally doable. I think I can have something published by end of next week, assuming the tree closures get resolved this week.

**Comment by bkonyi** [comment]
Reopening for now until 2.0.0 is published.

**Comment by bkonyi** [comment]
This seems to have rolled through into google3, so I've gone ahead and published as `2.0.0`.

**Comment by jmagman** [comment]
> This seems to have rolled through into google3, so I've gone ahead and published as `2.0.0`.

Thanks!  

On to the next... https://github.com/dart-lang/webdev/issues/1327. 😄
