### ISSUE TITLE
[CP][beta channel] Fix for very large AOT applications

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#45755]
**commit(s) to merge**: d41f9a738e3d3d35b5cbeeec1974ef8e23093c65, 8156646b0c92f0e1d83ef62a84745c37c4cd1d72

**merge instructions**: cherry-picks cleanly (though there's some weird build issues - possibly due to python3 upgrade - /cc @athomas )

**What is the issue**: For very large applications where the code size can exceed 32 MiB it can happen that a PC-relative backwards call crosses a larger distance than instruction encoding can represent. The AOT compiler failed to create trampolines in this case

**What is the fix**: Ensure the AOT compiler emits a trampoline if pc-relative backwards branches are out-of-range.

**Why cherrypick**: It has been hit by flutter customers, e.g. https://github.com/flutter/flutter/issues/80043

**Risk**: Low. The actual fix is 7 lines of code (though the CL is larger in order to be able to write a test for it)

**Link to original  issue(s)**: 

  * https://github.com/flutter/flutter/issues/80043

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
@kf6gpe Will you do extra stable hotfix for this one, it's coming from flutter customer, PTAL

**Comment by kf6gpe** [comment]
The window's currently closed --- were you thinking Flutter 2.0 / Dart 2.12 stable? Or Flutter 2.2-beta / Dart 2.13 beta? For the latter, the window is open next week.

I'm tempted to defer this to the next stable --- although I see the customer in question. Let me check with a couple of the Flutter folks who know the customer.

**Comment by vsmenon** [comment]
General note: is there a good way to tell if commits have successfully rolled internally?  That would be a nice sanity check for all requests.

Given that this is (1) customer visible, (2) a crasher, and (3) a relatively small fix, we should strongly consider this.  2.13 is probably fine though.

**Comment by mkustermann** [comment]
> General note: is there a good way to tell if commits have successfully rolled internally? That would be a nice sanity check for all requests.

/cc @davidmorgan

**Comment by athomas** [comment]
The best way to tell is to look at go/dart-version, find the latest dev release rolled internally and then run:

```bash
git fetch # ensure you have all the tags
git tag --contains <commit SHA> <latest dev release>

# example
$ git tag --contains d41f9a7 2.14.0-4.0.dev # no output because it's not included
```

The UI way to do that is to go to the commit in GitHub and look at the tags (go/dart-hash/<Commit SHA>).

In the unusual case, when there is a commit rather than a dev release rolled internally, `git merge-base --is-ancestor` can be used to check from the command line.

**Comment by mkustermann** [comment]
> @mkustermann Offline discussion with Flutter team thinks this can wait until 2.13. I'm going to move this to merge-to-beta.
> Please re-check the CL on bata branch.

It merges cleanly & tests pass. Though it needs b5c63ce7577c8c7634651dfac28d3e093bba91f7 as well in order to build (due to removal of `python` on our machines).

**Comment by athomas** [comment]
> It merges cleanly & tests pass. Though it needs [b5c63ce](https://github.com/dart-lang/sdk/commit/b5c63ce7577c8c7634651dfac28d3e093bba91f7) as well in order to build (due to removal of `python` on our machines).

Does it actually need that change or would installing python-is-python2 be sufficient? We don't have plans to cherry-pick the python3 migration to beta.

**Comment by mkustermann** [comment]
> Does it actually need that change or would installing python-is-python2 be sufficient? 

It probably is sufficient - though I can only test tit locally.

**Comment by athomas** [comment]
Ok, bots have both versions of python and the beta and stable branch builders will pick the 2.x versions. No concerns from the infra side, this can be safely merged if approved.

**Comment by franklinyow** [comment]
Approved in SCRUM

**Comment by a-siva** [comment]
I checked, the above changes have rolled into Flutter engine but not yet into the framework. This is the framework PR that has the required roll into the framework https://github.com/flutter/flutter/pull/80769, it is waiting for the framework tree to go green

**Comment by athomas** [comment]
Merged to beta in 5cae07b3980f4684d3d477457c307a67235adf99 (2.13.0-211.13.beta).

**Comment by mkustermann** [comment]
@l8023lxb Without knowing more it's impossible to say what issue you run into. If the patch applies cleanly to `2.10.5` it might not be the cause of your issue. If you need more help with it, please file a new github issue, provide a reproduction of the issue then we may take a look. Though in general we don't backport any fixes to old versions.

**Comment by l8023lxb** [comment]
> @l8023lxb note that you need to build `gen_snapshot` for the right arch/OS combination, if you would like to cherry pick this into an older version of Flutter, building dart sdk itself is not going to help.

Ok. Thank you very much.I try tomorrow.😀

**Comment by l8023lxb** [comment]
> @l8023lxb note that you need to build `gen_snapshot` for the right arch/OS combination, if you would like to cherry pick this into an older version of Flutter, building dart sdk itself is not going to help.

I build new gen_snapshot with cherry-pick commit ,and app start normal .Thank you! You are so niubility!!!☺
