### ISSUE TITLE
Add deprecation warning whenever analyzer see dart-ext: import

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#45759]
Tracking issue for adding warning message for Deprecate and remove dart native extensions, see  #45451 for more detail

**Comment by franklinyow** [comment]
@srawlins please reassign if someone else is handling this

**Comment by srawlins** [comment]
What is a native extension?

**Comment by srawlins** [comment]
OK I've looked at the referenced issue. I'll reassign when we decide who will cover this.

**Comment by devoncarew** [comment]
In-lined from the parent issue:

> In Dart 2.14 issue a deprecation warning whenever analyzer or CFE see dart-ext: import.
> In Dart 2.15 remove support for dart-ext: imports and hide Dart VM C API symbols from standalone dart binary shipped with SDK

**Comment by srawlins** [comment]
I'm going to start on this ASAP
