### ISSUE TITLE
`LinkedList.add` crashs on web with a cast error

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#45767]
hi,
a user of my get_it_mixing reported a strange cast error when he runs the app on the web. 
I could reproduce this in the most basic setup where adding an item to a linked list throws an exception on the web but not on other platforms.

You could find the repro project here

https://github.com/escamoteur/linked_list_web_error

[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.18363.1500], locale de-DE)

@mraleph

**Comment by escamoteur** [comment]
It happens also in pure Dart on dart pad

**Comment by renefloor** [comment]
@escamoteur I first simplified this example to:

```
import 'dart:collection';

class SomeType extends LinkedListEntry<SomeType>{}
final _watchList = LinkedList<LinkedListEntry<SomeType>>();

void main() {
  var entry = SomeType();
  try{
    _watchList.add(entry);
  }catch(e){
    print(e);
  }
}
```

Then thought you don't add an object of type `LinkedListEntry`, but of `SomeType`. So this example fixed it for me.

```
import 'dart:collection';

class SomeType extends LinkedListEntry<SomeType>{}
final _watchList = LinkedList<SomeType>();

void main() {
  var entry = SomeType();
  try{
    _watchList.add(entry);
    print('no problem');
  }catch(e){
    print(e);
  }
}
```

**Comment by escamoteur** [comment]
But `_watchEntry` extends LinkedListEntry too

**Comment by leafpetersen** [comment]
Slightly simplified example:

```dart
import 'dart:collection';
import 'package:flutter/foundation.dart' as _;

class _WatchEntry<S, T>
    extends LinkedListEntry<_WatchEntry<Object, Object?>> {}
final _watchList = LinkedList<_WatchEntry<Object, Object?>>();

void main() {
  _WatchEntry<Object, Object?> entry = _WatchEntry<bool, bool?>();
  try{
    _watchList.add(entry);
  } catch(e){
    print(e);
  }
  print("Done");
}
```

This crashes with a type error on dartpad, but if I remove the unused import it succeeds.

The type error that gets printed out is:

```
Expected a value of type 'LinkedList<_WatchEntry<Object, Object>>?', but got one of type 'LinkedList<_WatchEntry<Object, Object?>>'
```

The fact that `_WatchEntry<Object, Object>` is a type that doesn't appear anywhere in this program suggests to me that this is a compiler bug.

cc @sigmundch @rakudrama

**Comment by sigmundch** [comment]
cc @nshahan 

Thanks everyone for helping us narrow this down to a smaller repro!

The removal of the unnecessary import was a good clue! Dartpad for flutter uses DDC, whereas dartpad for non-flutter uses dart2js. I didn't know this, but the dartpad UI seems pretty dynamic and switches the backend depending on whether flutter is imported.

Locally, this program shows the error in ddc:
```dart
import 'dart:collection';

class A<S, T> extends LinkedListEntry<A<Object, Object?>> {}

void main() {
  LinkedList<A<Object, Object?>>().add(A<bool, bool?>());
}
```

And removing `dart:collection`:
```dart
class Entry<E extends Entry<E>>{
  L<E>? _list;
}
class L<E extends Entry<E>> {
  add(E entry) { entry._list = this; }
}

class A<T> extends Entry<A<Object?>> {}

void main() {
  L<A<Object?>>().add(A<bool?>());
}
```
is enough to trigger the failure.

**Comment by sigmundch** [comment]
a small tweak to remove some of the indirection:
```dart
class Entry<E extends Entry<E>>{
  foo(L<E>? input) {}
}
class L<E extends Entry<E>> {}

class A<S> extends Entry<A<Object?>> {}

void main() {
  A<bool>().foo(L<A<Object?>>());
}
```

This fails with the error: ` Expected a value of type 'L<A<Object>>?', but got one of type 'L<A<Object?>>'`

An odd piece here is the type `L<A<Object>>`. You cannot write that type in the program (you get a compile-time error highlighting that `A<Object>` doesn't comply with the bound of `L`). So this is likely coming from a place where DDC may be dropping the `?` accidentally.

**Comment by sigmundch** [comment]
The output of DDC seems to be initializing the base type of `A<S>` incorrectly:
```js
dart.setBaseClass(repro8.A$(S), repro8.Entry$(repro8.A$(core.Object)));
```

as opposed to:
```js
dart.setBaseClass(repro8.A$(S), repro8.Entry$(repro8.A$(dart.nullable(core.Object))));
```

**Comment by sigmundch** [comment]
quick update - it seems that whenever we emit this `setBaseClass` we are omitting the nullability here: https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/kernel/compiler.dart#L870

**Comment by sigmundch** [comment]
Here is a smaller repro illustrating the semantic difference:
```dart
class I<T> {}
class F<E extends F<E>> extends I<E> {}
class A<T> extends F<A<Object?>> {} // extending F forces DDC to deferr the superclass and trigger the bug

void main() {
  print(A<bool>() is I<A<Object?>>);
  print(A<bool>() is I<A<Object>>);
}
```

This prints true/false in the VM and dart2js, but true/true in DDC
