### ISSUE TITLE
Dart detects incorrect closures for the function with type parameter

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45763]
Dart SDK version: 2.14.0-3.0.dev (dev) (Tue Apr 13 22:57:19 2021 -0700) on "windows_x64"

Please run the following source code example:
``` dart
Type? capturedTypeArgument;
Type typeOf<X>() => X;

X captureTypeArgument<X>() {
  capturedTypeArgument = X;
  throw "";
}

typedef check = void Function<T>();

void main() {
  void f(check Function<T>() g) => g();

  try { f(<T>() => captureTypeArgument()); } catch(e) {}
  print(typeOf<void Function<T>()>() == capturedTypeArgument);
  print(check);
  print(capturedTypeArgument);
}

```
Seems like `typeOf<void Function<T>()>()` and `capturedTypeArgument` should be equal, however this is not so - `print(typeOf<void Function<T>()>() == capturedTypeArgument);` produces `false` here:
```
$> dart --enable-experiment=generic-metadata test.dart
false
<X0>() => void
<X1>() => void
```

**Comment by eernstg** [comment]
It looks like this could be a CFE issue. Consider the kernel code:

```
library /*isNonNullableByDefault*/;
import self as self;
import "dart:core" as core;

typedef check = <T extends core::Object? = dynamic>() → void;
static field core::Type? capturedTypeArgument;
static method typeOf<X extends core::Object? = dynamic>() → core::Type
  return self::typeOf::X%;
static method captureTypeArgument<X extends core::Object? = dynamic>() → self::captureTypeArgument::X% {
  self::capturedTypeArgument = self::captureTypeArgument::X%;
  throw "";
}
static method main() → void {
  function f(<T extends core::Object? = dynamic>() → <T extends core::Object? = dynamic>() → void g) → void
    return g.call<dynamic>();
  try {
    f.call(<T extends core::Object? = dynamic>() → <T extends core::Object? = dynamic>() → void => self::captureTypeArgument<<T extends core::Object? = dynamic>() → void>());
  }
  on core::Object catch(final core::Object e) {
  }
  core::print(self::typeOf<<T extends core::Object? = dynamic>() → void>().{core::Type::==}(self::capturedTypeArgument));
  core::print((#C1).{core::Type::==}(self::capturedTypeArgument));
  core::print(#C1);
  core::print(self::capturedTypeArgument);
}
constants  {
  #C1 = TypeLiteralConstant(<T extends core::Object? = dynamic>() →* void)
}
```

The surprising bit is that `#C1` uses `*` on the function type itself, as if the program (with respect to the treatment of the type literal `check` at least) is treated as if it were using `--no-sound-null-safety`.

@johnniwinther, WDYT?

**Comment by a-siva** [comment]
//cc @crelier FYI to confirm it is a CFE issue.

**Comment by crelier** [comment]
I do not think this is a CFE issue, because this works correctly in my [pending CL](https://dart-review.googlesource.com/c/sdk/+/189942) refactoring type parameters, but not with the current top of the tree. My CL reworked parts of the code establishing scopes for type parameters in function types when reading from the kernel file. I suspect that it fixed this issue there. The type parameter printed as 'X1' indicates that it has index 1. It should have index 0.

Unless this is an urgent issue, I would suggest we wait until my pending CL is committed.
