### ISSUE TITLE
RegExp error

### ISSUE THREAD

**Issue by marcobraghim** [dart-lang/sdk#45765]
Why the following regular expression is failing? It's working fine in PHP and JS

```dart
RegExp(r'#[\wÀ-ú]{2,}+');
```

The error given:
```
Nothing to repeat#[\wÀ-ú]{2,}+
```

Ps.: Sorry if this isn't the right place to ask it.

**Comment by lrhn** [comment]
What @tatumizer says, or maybe even `RegExp(r'(?:#[\wÀ-ú]{2,})+');` if you don't need the capture.

The [grammar](https://262.ecma-international.org/5.1/#sec-15.10.1) of regular expressions allows only one quantifier, which includes `+` or `{2,}`, after an Atom, so `{2,}+` is grammatically invalid. Adding the extra parentheses makes it valid, and if you want to include the `#` in the repetition, that also makes it do the right thing.

**Comment by marcobraghim** [comment]
Thank you guys
