### ISSUE TITLE
[CP][beta channel] Fix for Function.== in DDC

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#45772]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/8e2539d24c93ebb238c8681250ab67c4bf19c4e9

**merge instructions**: clean merge

**What is the issue**: DDC has two dispatch mechanisms: a direct member call or an indirect call using a symbol in the prototype of the target. We use the former for most methods implemented in classes when we know the static type of the call, and the latter for various reasons (dynamic calls and calls to potentially native APIs like html elements from the browser).

DDC is generating the wrong one for Function.== under null safety. This causes issues whenever users compare `f1 == f2` when the type of `f1` is a non-nulllable `Function`. 

**What is the fix**: Force DDC to use the proper dispatch mechanism on Function.

**Why cherrypick**: User visible regression, noticed by external users and in the flutter build.

**Risk**: low, fix is very contained and small, the change uses the conservative dispatch mechanism that is always supported.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/45601 https://github.com/dart-lang/sdk/issues/45762

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @nshahan

**Comment by vsmenon** [comment]
Has this rolled internally yet - that'd be a good sanity check.  Otherwise, lgtm.

**Comment by sigmundch** [comment]
It did, all green there too.

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved in SCRUM

**Comment by athomas** [comment]
Merged to beta in 5cae07b3980f4684d3d477457c307a67235adf99 (2.13.0-211.13.beta).
