### ISSUE TITLE
[CP][beta channel] Fix source location of debugger() calls

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#45774]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/aaa66ed77ea8b7582ab478ad4425dadcec4a5b02 https://github.com/dart-lang/sdk/commit/825b59ae6d77bb94b5434d8637ba85448206caa4

**merge instructions**: clean merge

**What is the issue**: ddc source maps produce incorrect locations when a method contains multiple "debugger()" calls

**What is the fix**: DDC's lowering was reusing the debugger node and keeping all with the same source location. The fix required tracking each statement and its source location separately.

**Why cherrypick**: This is not a high-priority item. The main issue is that it gives a poor debug experience. The issue was noticed by external customers. I'm inclined to cherry pick if a build is being created for other reasons.

**Risk**: low, only affects users with `debugger` statements which only occur on debug-only code. Overall, the fix is very contained.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/45544

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @nshahan

**Comment by franklinyow** [comment]
Approved in SCRUM

**Comment by athomas** [comment]
Merged to beta in 5cae07b3980f4684d3d477457c307a67235adf99 (2.13.0-211.13.beta).
