### ISSUE TITLE
Analyzer detects error line number and position in the source code incorrectly

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45786]
Dart SDK version: 2.14.0-3.0.dev (dev) (Tue Apr 13 22:57:19 2021 -0700) on "windows_x64"

The following source code example throws a compile time error for the line 5 because type alias cannot reference itself:
``` dart
/**
 * This is a test
 */

typedef FUNC1<T> = void Function<T1 extends FUNC1<T>>();

main() {}
```
The problems is that in this particular case analyzer ignores comments when calculate line number in the code.

So, dart prints error diagnostc for the line 5 whereas analyzer do the same for the line 1.

Sample output is:
```
$> dart test.dart
test.dart:5:9: Error: The typedef 'FUNC1' has a reference to itself.
typedef FUNC1<T> = void Function<T1 extends FUNC1<T>>();
        ^^^^^

$> dartanalyzer test.dart
Analyzing test.dart...
  error - Typedefs can't reference themselves directly or recursively via another typedef. - test.dart:1:1 - type_alias_cannot_reference_itself
1 error found.
```

Analyzer should refer to `test.dart:5:9` instead of `test.dart:1:1` here.

If I remove comments in the top of the source and just leave empty lines before the typedef definition, line number is calculated correctly.

**Comment by lfkdsk** [comment]
It seems like this `typedef` element's beginToken is doc element, and doc element's offset is zero.

**Comment by lfkdsk** [comment]
try to change reportError focus on typedef's name : https://github.com/dart-lang/sdk/pull/45790

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/e9b1d45382fe036883fb09efae492b43358cb9d7#diff-34bdef16e4753eaf47e385c5528e86971c0a0417d23a4006063927c9d2cccd7e
