### ISSUE TITLE
Dartanalyzer cannot pick a null error while it fails at run time

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#45797]
Tested  with Dart 2.12.3 and https://dart.dev/

```
void main() {
  var b = foo('a');
  goo(b);
  var b2 = foo(null);
  goo(b2); //Analyzer shall show an error here, but it does not
}

T foo<T extends String?>(T a) => a;
int goo(String s) => s.length;
```

BTW, is it the right way to declare a method that can access both `String` and `String?` (without changing the null-safety status)?

**Comment by eernstg** [comment]
This must be a bug in the analyzer. Here is a shorter example:

```dart
T foo<T extends String?>(T a) => a;

void main() {
  var x = foo(null);
  int i = x; // No compile-time error, so `x` has type `dynamic`.
}
```

**Comment by eernstg** [comment]
The behavior with `--no-implicit-dynamic` may be preferable, but I'll close this issue because the behavior matches the specification.

**Comment by eernstg** [comment]
> BTW, is it the right way to declare a method that can access both `String`
> and `String?` (without changing the null-safety status)?

Your signature works quite well for this purpose:

```dart
T foo<T extends String?>(T a) => /* something */;
```

This signature preserves the property that non-null-in means non-null-out (I assume that's what you mean by 'without changing the null-safety status'). However, it also preserves the property that null-in means null-out, and that interacts badly with variable type inference. You can't really blame the signature for this, and the right way to catch the problem would be to flag the very fact that `x` gets the type `dynamic`, that is, use `--no-implicit-dynamic`.

**Comment by tomyeh** [comment]
Great! Thanks.
