### ISSUE TITLE
Failures on [vm, compiler] Make UnboxedConstant more like Constant

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#45805]
There are new test failures on [[vm, compiler] Make UnboxedConstant more like Constant](https://github.com/dart-lang/sdk/commit/571908fbecb9ae5cdebfc390d3eba40b4a17160f).

The tests
```
lib_2/typed_data/float32x4_test/0 Crash (expected Pass)
lib_2/typed_data/float32x4_test/1 Crash (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-simarm-crossword
```

/cc @rmacnak-google It seems this was caused by your CL, could you take a look?

**Comment by mraleph** [comment]
It's a bug in the simulator. Fix: https://dart-review.googlesource.com/c/sdk/+/196660
