### ISSUE TITLE
CFE test expectations need updating when generic metadata flag flips

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45816]
The [cl](https://dart-review.googlesource.com/c/sdk/+/193748) flipping the generic metadata flag causes [failures](https://dart-ci.firebaseapp.com/cl/193748/4) in CFE expectations tests that will need to be reset.

cc @johnniwinther 

pkg/front_end/test/fasta/messages/AnnotationOnFunctionTypeTypeVariable/part_wrapped_script1
pkg/front_end/test/fasta/messages/AnnotationOnFunctionTypeTypeVariable/script1
pkg/front_end/test/fasta/messages/GenericFunctionTypeInBound/part_wrapped_script
pkg/front_end/test/fasta/messages/GenericFunctionTypeInBound/script
pkg/front_end/test/fasta/messages/GenericFunctionTypeInferredAsActualTypeArgument/part_wrapped_script
pkg/front_end/test/fasta/messages/GenericFunctionTypeInferredAsActualTypeArgument/script
pkg/front_end/test/fasta/messages/GenericFunctionTypeUsedAsActualTypeArgument/part_wrapped_script1
pkg/front_end/test/fasta/messages/GenericFunctionTypeUsedAsActualTypeArgument/part_wrapped_script2
pkg/front_end/test/fasta/messages/GenericFunctionTypeUsedAsActualTypeArgument/script1
pkg/front_end/test/fasta/messages/GenericFunctionTypeUsedAsActualTypeArgument/script2
pkg/front_end/test/fasta/outline/general/function_type_parameter
pkg/front_end/test/fasta/outline/nnbd/issue34803
pkg/front_end/test/fasta/outline/nnbd_mixed/cyclic_typedef
pkg/front_end/test/fasta/strong/nnbd/issue34803
pkg/front_end/test/fasta/text_serialization/general/function_type_parameter
pkg/front_end/test/fasta/text_serialization/general/issue45330
pkg/front_end/test/fasta/text_serialization/nnbd/issue34803
pkg/front_end/test/fasta/text_serialization/nnbd_mixed/cyclic_typedef
pkg/front_end/test/fasta/weak/general/function_type_parameter
pkg/front_end/test/fasta/weak/general/issue45330
pkg/front_end/test/fasta/weak/nnbd/issue34803
pkg/front_end/test/fasta/weak/nnbd_mixed/cyclic_typedef

**Comment by johnniwinther** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/196921
