### ISSUE TITLE
Failures on Fix missing RestoreCSP() from vm/cc/RelocationTest_* tests

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45811]
There are new test failures on [[gardening] Fix missing RestoreCSP() from vm/cc/RelocationTest_* tests](https://github.com/dart-lang/sdk/commit/2b50aff49345b0d00b2408a2c5462ea031a6a9df).

The tests
```
vm/cc/CodeRelocator_DirectForwardCall Fail (expected Pass)
vm/cc/CodeRelocator_OutOfRangeBackwardCall Fail (expected Pass)
```
are failing on configurations
```
dartk-linux-release-simarm64
```

**Comment by aam** [comment]
cc @mkustermann @mraleph

**Comment by mkustermann** [comment]
Aren't they already addressed?

**Comment by aam** [comment]
https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-linux-release-simarm64/11540/overview seems to be failures on the cl with the fix. Am I looking at it incorrectly?

**Comment by aam** [comment]
Note this failures are on simarm64 bots, the fix you mention addresses failures on arm64 bot https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/cross-vm-linux-release-arm64/6817/overview

**Comment by mkustermann** [comment]
@aam As mentioned, I believe they are addressed.
