### ISSUE TITLE
[analyzer] please make the "create constructor for final fields" fix add `required` where needed

### ISSUE THREAD

**Issue by sma** [dart-lang/sdk#45812]
I'm using the "create constructor for final fields" fix all the times to let my IDE generate constructors, mostly for Flutter widget but also for "normal" data classes. Unfortunately, I have manually prefix nearly all `this.foo` attributes with `required` because they are not nullable. It should be possible to detect whether I did not opt out of NNBD and generate the current syntax. Right now, the fix generates invalid code that doesn't compile.

As an additional bonus, it would be nice if the constructor would be created at the top of the class and not below the fields because according to Futter's coding style, I have to move the constructor declaration up each and every time.

**Comment by asashour** [comment]
Could you please provide a minimal case? I see an issue with "Add final field formal parameters", which is missing `required`, but then "add 'required' keyword" works fine.


```dart
void main() {
  runApp(const MyHomePage(title: 'abc'));
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const Text('');
  }
}
```

**Comment by sma** [comment]
When I created the issue, an "Add required keyword" quick fix didn't exist. It indeed is a workaround.

It is still not the best solution because you have to invoke it for each parameter separately, I think.

---

Long version:

This is the code inserted by the `stl` completion in VSC:

```
class Foo extends StatelessWidget {
  const Foo({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

If i add `final String bar;` like so:

```
class Foo extends StatelessWidget {
  const Foo({Key? key}) : super(key: key);

  final String bar;

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

I get an error because `bar` is not initialized.

I can try to "fix" the error because of the uninitialized `bar` field, only to get another error, even if the code completion could easily be smart enough to add the required `required` right now without me fixing that manually.

```
class Foo extends StatelessWidget {
  const Foo({Key? key, this.bar}) : super(key: key);

  final String bar;

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

Now, I need to invoke the quick fix a second time to fix that error:

```
class Foo extends StatelessWidget {
  const Foo({Key? key, required this.bar}) : super(key: key);

  final String bar;

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

While the above mentioned workaround works for a single field, it gets quite annoying, if you have to do this repeatedly.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/239300

**Comment by bwilkerson** [comment]
> As an additional bonus, it would be nice if the constructor would be created at the top of the class and not below the fields because according to Futter's coding style ...

There is a lint that you can enable to cause that style to be used, and to remind you if your classes ever become unsorted: `sort_constructors_first`.
