### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by DZESU** [dart-lang/sdk#45822]
I'm not sure is this a bug or I'm just stupid myself.
What I wonder is why "testA" and "testB" give different result output
If this is not a bug, I would be appreciated if anyone can help guide me about this syntax.

Dart version: 2.12.2
OS : Window

```
void main() {
  List a = [1,2,3];
  
  List b = [4,5,6];
  
  int testA = (a.length??0) + b.length;
  int testB = a.length??0 + b.length;
  
  print("testA = $testA");//testA = 6
  
  print("testB = $testB");//testB = 3
  
}
```

![image](https://user-images.githubusercontent.com/19683344/116005746-867f5700-a632-11eb-8a4b-8ea52dbf8deb.png)

**Comment by WizNeo6** [comment]
.length is not nullable, so you don't need null handling.
if you change the code to this, the warning will gone.
``` dart
void main() {
  List? a;
  List b = [4,5,6];
  
  int testA = (a?.length ?? 0) + b.length;
  int testB = a?.length ?? 0 + b.length;
  
  print("testA = $testA");//testA = 6
  print("testB = $testB");//testB = 3
}
  ```

**Comment by DZESU** [comment]
@WizNeo6  Maybe I post the issues wrong. What I wonder is why "testA" and "testB" give different result output.

**Comment by eernstg** [comment]
`testA` and `testB` give different results because of the syntactic structure: `+` binds more tightly than `??`, so what you've written means the following:

```dart
int testB = a?.length ?? (0 + b.length);
```

**Comment by eernstg** [comment]
I'll close this issue because it is all working as intended.

**Comment by DZESU** [comment]
@eernstg What if the list is null, I use that `??` in case the my list is null so I can give default value instead of getting crash.

**Comment by DZESU** [comment]
Oh... I see. Thank you for explanation.
