### ISSUE TITLE
No published analyzer available for language version 2.12.0

### ISSUE THREAD

**Issue by AdityaSettlin** [dart-lang/sdk#45826]
It's been more than a few hours and I am stuck with this issue.

**Comment by AdityaSettlin** [comment]
Whenever i run "flutter pub run build_runner build" it throws this same error, doesn't matter how much I try it keeps on showing the same error.

json_serializable:json_serializable on lib/api/exceptions.dart:
Your current `analyzer` version may not fully support your current SDK version.     

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.10.0
SDK language version: 2.12.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.12.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[INFO] Generating SDK summary...
[SEVERE] json_serializable:json_serializable on lib/api/exceptions.dart:

Bad state: Unexpected diagnostics:
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:166:25 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:539:15 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:390:19 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:30:49 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:18:62 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:42:22 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:327:34 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:376:19 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:516:13 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:224:29 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:65:23 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:58:17 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:41:23 - This requires the 'non-nullable' language feature to be enabled.
C:\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:132:29 - This requires the 'non-nullable' language feature to be enabled.
[SEVERE] json_serializable:json_serializable on lib/api/exceptions.dart:

**Comment by AdityaSettlin** [comment]
Here's my pubspec.yaml settings

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  build_runner: ^1.10.1
  cached_network_image: ^2.3.2+1
  cupertino_icons: ^0.1.3
  double_back_to_close_app: ^2.0.1
  equatable: ^1.2.4
  flutter_bloc: ^6.0.4
  flutter_platform_widgets: ^0.32.5
  flutter_zoom_drawer: ^1.0.4+1
  google_maps_flutter: ^1.2.0
  http: 0.12.0+4
  infinite_scroll_pagination: ^2.2.3
  json_to_model: ^1.4.0
  json_serializable: ^3.3.0
  provider: ^4.3.3
  rxdart: ^0.24.1


  flutter_localizations:
    sdk: flutter
  easy_localization: ^2.3.3

# dependency_overrides:
#   analyzer: '0.39.14'

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

**Comment by mit-mit** [comment]
Does not repro:

```
$ ~/sdk/stable/dart-2-12-0/bin/dart --version
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
```

```
$ cat pubspec.yaml
name: test5
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  analyzer:
```

```$ ~/sdk/stable/dart-2-12-0/bin/dart pub get
Resolving dependencies...
Got dependencies!
| ~/tmp/test5 @ mit-macbookpro3 (mit)
```
