### ISSUE TITLE
Dart does not throw a compile error when dart 2.6 code source declares a generic function with generic function as its type argument

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45834]
Dart SDK version: 2.14.0-32.0.dev (dev) (Thu Apr 22 20:17:19 2021 -0700) on "windows_x64"

Here is a code source example:
``` dart
// @dart=2.6

class C4<X extends void Function<T>()> {}

typedef F1 = void Function<X extends void Function<T>()>();

main() {}
```
Analyzer throws 2 compile time errors here: for the line 3 (`class C4<X extends void Function<T>()> {}`) and line 5 (`typedef F1 = void Function<X extends void Function<T>()>();`).

This is a correct result because generic functions as type arguments and bounds are not supported in the previous dart versions.

The problem is that dart throws a error for the line 3 and silently passes on the line 5 here. It should throw both errors here instead too.

Sample output is:
```
$> dartanalyzer --enable-experiment=generic-metadata test.dart
Analyzing test.dart...
  error - Generic function types can't be used as type parameter bounds - test.dart:3:20 - generic_function_type_cannot_be_bound
  error - Generic function types can't be used as type parameter bounds - test.dart:5:38 - generic_function_type_cannot_be_bound
2 errors found.

$> dart --enable-experiment=generic-metadata test.dart
test.dart:3:10: Error: Type variables can't have generic function types in their bounds.
class C4<X extends void Function<T>()> {}
         ^
```

**Comment by eernstg** [comment]
@lrhn, I believe @iakh is right in blaming the CFE, so I'll change the label to area-front-end. Please follow up if you disagree.

**Comment by lrhn** [comment]
Agree, I didn't read the text thoroughly enough.
