### ISSUE TITLE
build_runner 2.1.0 not working with analyzer 1.5.0

### ISSUE THREAD

**Issue by leadpresence** [dart-lang/sdk#45844]
**I cant explian what the issue might be and i m working with following kindly help with suggestion:**

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**My class**

```
import 'package:hive/hive.dart';

part 'inventory_model.g.dart';

@HiveType()
class Inventory {
  @HiveField(0)
  final String name;

  @HiveField(1)
  final String description;

  Inventory({this.name, this.description});
}
```

in my case pubspec:

```
 hive: ^2.0.4
 hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner
```: ^2.0.1

ERROR:

flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 510ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 15.1s

[INFO] There was output on stdout while compiling the build script snapshot, run with `--verbose` to see it (you will need to run a `clean` first to re-snapshot).

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 860ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 4.3s elapsed, 0/5 actions completed.
[INFO] Generating SDK summary completed, took 4.3s

[INFO] 5.6s elapsed, 4/5 actions completed.
[SEVERE] hive_generator:hive_generator on lib/models/inventory.dart:

You have to provide a non-null typeId.
[INFO] Running build completed, took 5.8s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 46ms

[SEVERE] Failed after 5.8s
pub finished with exit code 1

**Comment by mit-mit** [comment]
cc @natebosch @jakemac53

**Comment by jakemac53** [comment]
@leadpresence can you run the build with `--verbose`?

Also do you have any dependency overrides in your pubspec? (or can you link the entire thing here?)

**Comment by natebosch** [comment]
According to the changelog [hive has required a `typeId` argument to `HiveType` since version `1.3.0`](https://pub.dev/packages/hive/changelog#130)

The error here is coming from the hive generator.

From what I can tell you should add a named `tyepId` argument to the `HiveType` annotation. Note that in the code it is marked `required`.
