### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Couldn't apply migration

### ISSUE THREAD

**Issue by salvadorfrisco** [dart-lang/sdk#45842]
Couldn't apply migration

Error: RangeError (end): Invalid value: Not in inclusive range 0..15317: 18446

Please fill in the following:

**Name of package being migrated (if public)**:
**What I was doing when this issue occurred**:
**Is it possible to work around this issue**:
**Has this issue happened before, and if so, how often**:
**Dart SDK version**: 2.13.0-211.6.beta
**Additional details**:

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
#0      RangeError.checkValidRange (dart:core/errors.dart:333:9)
#1      _StringBase.replaceRange (dart:core-patch/string_patch.dart:607:33)
#2      applyEdit (package:analyzer_plugin/src/protocol/protocol_internal.dart:82:15)
#3      SourceEdit.apply (package:analyzer_plugin/protocol/protocol_common.dart:4454:32)
#4      applySequenceOfEdits.<anonymous closure> (package:analyzer_plugin/src/protocol/protocol_internal.dart:90:17)
#5      List.forEach (dart:core-patch/growable_array.dart:403:8)
#6      applySequenceOfEdits (package:analyzer_plugin/src/protocol/protocol_internal.dart:89:9)
#7      SourceEdit.applySequence (package:analyzer_plugin/protocol/protocol_common.dart:4381:7)
#8      IncrementalPlan.apply (package:nnbd_migration/src/preview/preview_site.dart:115:27)
#9      PreviewSite.performApply (package:nnbd_migration/src/preview/preview_site.dart:520:10)
#10     PreviewSite.handlePostRequest (package:nnbd_migration/src/preview/preview_site.dart:449:9)
<asynchronous suspension>
#11     HttpPreviewServer._handlePostRequest (package:nnbd_migration/src/preview/http_preview_server.dart:109:5)
<asynchronous suspension>
#12     HttpPreviewServer._handleServer.<anonymous closure> (package:nnbd_migration/src/preview/http_preview_server.dart:119:9)
<asynchronous suspension>

```

**Comment by stereotype441** [comment]
Hi @salvadorfrisco, thanks for the bug report!  Can you give us any information about what you were doing at the time the error occurred?

Also, is the code you're migrating publicly available?  If it is, that would be very helpful to us in trying to debug the issue.

Thanks!

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
