### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by red-gel** [dart-lang/sdk#45845]
## Version information

- `IDEA AI-201.8743.12.41.7199119`
- `2.12.2`
- `AI-201.8743.12.41.7199119, JRE 1.8.0_242-release-1644-b3-6222593x64 JetBrains s.r.o, OS Linux(amd64) v5.8.0-50-generic, screens 1366x768`

**Comment by mkustermann** [comment]
@red-gel Could you provide any information on what the issue here is?

@scheglov I guess this bug is not actionable (or is there any side information uploaded from IntelliJ feedback)?

**Comment by scheglov** [comment]
Yes, no information to do anything.
