### ISSUE TITLE
Heads-up: dart2js late lowering changes the interface --- probably not possible for ddc

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#45854]
If for instance running this code through the incremental compiler I get an error upon recompilation after invalidating `late_statics.dart`:

`late_statics.dart`:
```dart
import 'late_statics_lib.dart' as lib;
void testUninitializedNonFinalTopLevelField() {
  print(lib.a);
  lib.a = 42;
  print(lib.a);
}
```

`late_statics_lib.dart`:
```dart
late int a;
```

Errors:
```
late_statics.dart:4:7: Error: Setter not found: 'a'.
   lib.a = 42;
       ^
```

I understand that dart2js is meant as a whole-world compiler and that I'm thus doing something I'm not supposed to, but if nothing else it's a good datapoint: The same things is not going to work for ddc which is not a whole-world compiler, but works with both incremental compilation (e.g. through flutter), modular compilation (e.g. internally) and expression compilation.

/cc @fishythefish

**Comment by fishythefish** [comment]
Correct, this is expected. For certain kinds of `late` variables, such as statics, we use a kernel transformation to lower the variable to a `Cell`, which is essentially a boxed value. Reads and writes of the `late` variable are implemented as methods on the `Cell`, which replace the original getter/setter. This means that if `late` is added to (or removed from) a static, then we need to recompile not only the declaring library, but any library which uses the static as well.

I don't have any experience with the incremental compiler, so I'm not sure what it would take to ensure this is viable. This late lowering is currently intended only for dart2js, but it may be nice in the future to reuse the implementation for DDC.

/cc @rakudrama
