### ISSUE TITLE
Missing CFE errors on failed partial instantiations

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45851]
The test `tests/language/closure/partial_instantiation_static_bounds_check_test.dart` assigns generic functions to monomorphic function types.  This should generally cause an implicit partial instantiation, but in this case the result should cause a bounds check error, since the instantiation is invalid.  The CFE seems to be missing this check.

cc @johnniwinther @stefantsov

**Comment by asashour** [comment]
I think this is fixed.
