### ISSUE TITLE
[co19] LibTest/ffi/Packed/Packed_A01_t02 expectations

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#45852]
https://godbolt.org/z/13nM7n18b

```c
#pragma pack(push, 16)
typedef struct  {
  double x;
  int32_t y;
} MS16;
#pragma pack(pop)
```

This struct has a size of 12 bytes on Linux ia32, but the test expects 16.

```dart
Expect.equals(16, sizeOf<S16>());
```

https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-release-ia32/dartk-strong-linux-release-ia32/199/co19/LibTest/ffi/Packed/Packed_A01_t02

**Comment by sgrekhov** [comment]
Fixed by 055b5c984613ec1b8ef76516db3ea99fee63acb9
