### ISSUE TITLE
Controlling the json decoding of numerics

### ISSUE THREAD

**Issue by IanWorthington** [dart-lang/sdk#45856]
I'm attempting to use json.decode() to decode a response body that contains financial data.  The numbers in this need to be converted to a decimal format (ie not double) either in the parse or, if I can get them out as Strings, afterwards.

The only callback I can find is reviver, which is too late as they're doubles by then and the damage has been done.

It looks like the work is done in _parseJson() (but that's marked in json.dart as external and I can't find the full source for that, only a patch file in this library).

How can we control how numerics are decoded?

**Comment by mkustermann** [comment]
@IanWorthington I guess the issue here is that you're running your Dart code on the Web and get therefore JavaScript doubles which loose precision? (Or are you also having issues when running on the VM because the json integers are outside signed 64-bit range?)

/cc @lrhn

**Comment by IanWorthington** [comment]
@mkustermann I'm actually running on Android, but because it's  financial application I want to use ANSI-style decimals  (like Java BigDecimals, which seem to be available in the pub.dev decimal package) to hold my values, rather than wing it with doubles and end up in a world of pain at some stage down the road.  But to do that I need to get at my values /before/ the json converter has its way with them, rather than after as the reviver callback permits, I'm happy to have them output as Strings, if necessary, and I'll convert them myself afterwards.

**Comment by lrhn** [comment]
I'm not planning on changing the platform JSON decoding in this way.
It's not impossible, but I think it's overloaded with enough special cases already.
Introducing a way to override the parsing of *integer literals* is very specific. It's not something it's built for, and it won't work on the web anyway, because they parse using the platform JSON parser first.

Using something like `package:jsontool`, it should be possible to read JSON and pass number literals to `BigInt.parse` or `Inte64.parse` instead of using the default. I'm updating that package for null safety anyway, I'll try to add an example showing how that can be achieved with minimal fuss.

**Comment by IanWorthington** [comment]
@lrhn 

Many thanks Lasse, I'll check out your package: sounds promising!

I might have to take very slight issue with your characterisation of overriding the parsing of numerics as a very specific use case.  The rfc, https://tools.ietf.org/html/rfc7159#page-6, says:

"   This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available."

which I interpret as "IEEE 754 binary64s will work mostly until such time as they don't".   :)

It would, I think, be nice to have a way of dealing elegantly with this problem within the supported code, but I perfectly understand if you choose to differ in your opinion!

Again, many thanks for the pointer to your alternative package.

**Comment by IanWorthington** [comment]
@lrhn

Hi Lasse, just wanted to follow up with you and say your package works perfectly.  I used it to keep all numerics as strings and pushed the question of how each should be translated back to the converter.  Thus I could translate directly to int, double, or Decimal as appropriate for each variable, a solution I'm happy with.

Many thanks for your help.
