### ISSUE TITLE
Dart create output doesn't use installation overrides

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#45859]
Instructions for some `dart create` templates wrt. how to run the app are incorrect. For example:

```
$ dart create -t server-simple myserver
...
Created project myserver in myserver! In order to get started, run the following commands:

  cd myserver
  dart run
```

It looks like the implementation might not respect overrides like:

```
  @override
  String getInstallInstructions() => '${super.getInstallInstructions()}\n'
      'run your app using `dart run ${entrypoint.path}`.';
```

?

Finally, I think these overrides should mention `dart run`, not just `dart` (some are missing run).

**Comment by mit-mit** [comment]
@bkonyi did you get a chance to look at this?

**Comment by bkonyi** [comment]
> @bkonyi did you get a chance to look at this?

Yes, I sent out a review yesterday :-)

https://dart-review.googlesource.com/c/sdk/+/200287
