### ISSUE TITLE
Add option to disable DevTools for standalone VM

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#45867]
We should provide a `--disable-devtools` flag to allow for users to prevent DevTools from being served by DDS as some tools / IDEs currently serve their own instances.

**Comment by jonahwilliams** [comment]
I'm assuming that we're also not going to be starting devtools if we're passing --disable-dart-dev too? Or do we need to add a new flag to the flutter tool bootstrap and other parts of the tool?

**Comment by bkonyi** [comment]
Yes, that's the case. Also, DevTools will only start if `--enable-vm-service` or `--observe` is provided, so even if `--disable-dart-dev` isn't provided (aside: I'd like to drop that flag at some point since it won't impact startup time for basic runs like `dart foo.dart`) DevTools won't spawn unless the user explicitly enables the service.

**Comment by jonahwilliams** [comment]
i believe the concern was less to do with startup time and more to do with making sure programming errors in the tool are surfaced correctly. for example `dart program.dart` where the program is missing should not print out a warning about there not being a program.dart command

**Comment by bkonyi** [comment]
> i believe the concern was less to do with startup time and more to do with making sure programming errors in the tool are surfaced correctly. for example `dart program.dart` where the program is missing should not print out a warning about there not being a program.dart command

Oh, well if that's the case, that shouldn't be an issue anymore:

```
$ dart bad.dart
Error when reading 'bad.dart': No such file or directory.
```

**Comment by jonahwilliams** [comment]
cool!
