### ISSUE TITLE
"Warning: Tried to initialize from a previous compilation" while important a package from github as dependency

### ISSUE THREAD

**Issue by ChristianKleineidam** [dart-lang/sdk#45862]
When I run All tests in Android Studio I get the error:
```
Warning: Tried to initialize from a previous compilation (file:///C:/Users/Christian/Documents/Programming/anatomyleaflet/anatomy_leaflet/build/test_cache/build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill), but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file ../../../../../CHRIST~1/AppData/Local/Temp/initialize_from.dillae0d7be8/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.
```
When I delete the file I don't get the error the time I run All tests (there's no file and a file gets recreated). When I however run All tests again I get the error message again.

It seems like this happens iff I have in my pubspec.yaml as dependency:

```
  drag_and_drop_gridview:
    git:
      url: https://github.com/DevOrbiter/drag_and_drop_gridview.git
      ref: master
```

**Comment by jensjoha** [comment]
Thank you for your report!
I unfortunately cannot reproduce this from the description. Can you provide a more complete example?

**Comment by ChristianKleineidam** [comment]
Somehow the error reappeared and now removing the dependency doesn't make it go away. I don't want to release the relevant code openly on Github but I'm okay with zipping my project folder mailing it to you. 

If it matters I'm using Android Studio.

Flutter doctor is right now:
C:\Progs\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel dev, 2.3.0-0.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-0.1.pre at C:\Progs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d72bfb8d07 (10 days ago), 2021-04-26 06:05:55 -0700
    • Engine revision de6e1adf97
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at C:/Users/Christian/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 31.0.0-rc3
    • ANDROID_HOME = C:/Users/Christian/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Christian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
Process finished with exit code 0

**Comment by jensjoha** [comment]
Thanks @ChristianKleineidam but unless the code has an attached open source license I'm not allowed to look at it.
