### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined when compiling with dart2js (window.navigator.mediaDevices!.getUserMedia)

### ISSUE THREAD

**Issue by Hexer10** [dart-lang/sdk#45878]
When this function is called `await window.navigator.mediaDevices!
      .getUserMedia({'video': true, 'audio': false});` and the code is compiled using dart2js the following exception is thrown in the chrome console:
```
js_helper.dart:1130 Uncaught TypeError: Cannot read property 'toString' of undefined
    at main.dart:8
    at _wrapJsFunctionForAsync_closure.$protected (async_patch.dart:316)
    at _wrapJsFunctionForAsync_closure.call$2 (async_patch.dart:341)
    at Object._asyncStartSync (async_patch.dart:246)
    at main (main.dart:8)
    at js_helper.dart:2684
    at js_helper.dart:2684
    at dartProgram (js_helper.dart:2684)
    at js_helper.dart:2684
```

while using `dartdevc` (ie. `webdev serve`) the error is not thrown and the code works properly.

This is my current code:

main.dart
```dart
import 'dart:html';

void main() async {
  await window.navigator.mediaDevices!
      .getUserMedia({'video': true, 'audio': false});
}
```

index.html
```html
<!DOCTYPE html>
<html>
<head>
    <title>web_test</title>
    <script defer src="main.dart.js"></script>
</head>
</html>
```

```
Dart version: Dart SDK version: 2.12.4 (stable) (Thu Apr 15 12:26:53 2021 +0200) on "linux_x64"
Browser: chrome
```

**Comment by Hexer10** [comment]
I think I've solved this, it is not an issue from the dart compiler, but it was because a was accessing the webpage that was being served with the dart2js files on a non-secure context thus that api was not available. Sorry for bothering!

**Comment by sigmundch** [comment]
Thanks for the update! Glad you found the cause behind the issue.
