### ISSUE TITLE
Support Webgl via dart bindings for google filament

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/sdk#45885]
https://github.com/google/filament

**Comment by mraleph** [comment]
This is unfortunately out of scope for Dart. We don't really have resources to build bindings for every library out there. 

We do however want to enable any interested party to build their own bindings, e.g. you can use `dart:ffi`/`ffigen` to create your own bindings for filament and publish them on `pub`.

**Comment by unicomp21** [comment]
@mraleph 
I am so confused.
>We don't really have resources to build bindings for every library out there.

Filament isn't a library "out there", it is a Google project/product.  Is this a case of the left hand not talking to the right hand?

**Comment by mraleph** [comment]
Google teams (and individual engineers) produce lots of different things. It does not mean that all of these things are somehow part of some unified big picture and are intended to somehow interoperate.
 
> Filament isn't a library "out there", it is a Google project/product.

Note [this helpful disclaimer](https://github.com/google/filament#disclaimer) at the end of filament's README.
