### ISSUE TITLE
Migration tool fails when used with barrel file

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [dart-lang/sdk#45889]
I am using barrel files in my project and migration tool identifies them as libraries saying that those were not migrated

**Comment by stereotype441** [comment]
Hi @vytautas-pranskunas-, thanks for the bug report!  I have not worked with Barrel files before, so I will need some more information to be able to work on this bug.  Would you be able to share some example code that exhibits the problem?

**Comment by vytautas-pranskunas-** [comment]
barel files are generated files that contains gathered export like:

components.dart which contains:

export 'compoentn_one.dart'
export 'compoentn_two.dart'
...

so nothing more to share...

**Comment by vytautas-pranskunas-** [comment]
Alo it can be that i cannot migrate because i am using mobx generator wich uses part syntax like:

part 'payout_page.store.g.dart';

because when i run dart migration tool i get this message:
```
Before migrating your package, we recommend ensuring that every library it
imports (either directly or indirectly) has been migrated to null safety, so
that you will be able to run your unit tests in sound null checking mode.  You
are currently importing the following non-null-safe libraries:
```

there i see some shared components, stores, pages but not all....!!!!

Can you tell me why?

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
