### ISSUE TITLE
[analyzer] Incorrect extensions reported in a conflict

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45887]
Consider the following program:

```dart
extension E on int? { void foo() {} }
extension E1 on int { void foo() {} }
extension E2 on int { void foo() {} }
void main() => 1.foo();
```

This program causes the analyzer (9ff5ac12c6efec99b8d6580c7a7154bb5e265add) to emit the following error message:

```
ERROR|COMPILE_TIME_ERROR|AMBIGUOUS_EXTENSION_MEMBER_ACCESS|/usr/local/google/home/eernst/lang/dart/scratch/202105/n001.dart|4|18|3|A member named 'foo' is defined in extensions 'E' and 'E1' and neither is more specific.
```

However, the conflict actually arises for `E1` and `E2`, not for `E` and `E1`, so the error message is wrong. It seems likely that the problem lies in the error message and not in the underlying checks, because we get a correct error message if `E` is commented out, and we also (correctly) do not get any error messages if `E2` is commented out.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/198240

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/2efbd99c4799b087669b284c28e6644ff8f84807
