### ISSUE TITLE
Feature: Short form of import package

### ISSUE THREAD

**Issue by ggdream** [dart-lang/sdk#45897]
* Dart VM

## e.g.
- For Ts/Js, if had a path of `router/index.ts`, we will call the package by `import some from 'router'`, rather than `import some from 'router/index.ts'`.

- Python, it has `__init__`, supports it.

**Comment by simolus3** [comment]
You can see https://github.com/dart-lang/language/issues/649 for ideas and work on this.

**Comment by lrhn** [comment]
Agree, the language issue has the current thoughts on shorthands for imports. It's one proposal, others are definitely possible.
It's not currently scheduled, but a better import syntax is something we do want to add eventually.

**Comment by ggdream** [comment]
> You can see [dart-lang/language#649](https://github.com/dart-lang/language/issues/649) for ideas and work on this.

Thanks

**Comment by ggdream** [comment]
> 同意，语言问题具有当前关于进口捷径的想法。这是一个建议，其他建议绝对有可能。
> 目前尚未安排，但我们希望最终添加更好的导入语法。
Thanks，
Expect that likes it
