### ISSUE TITLE
analyze CLI busy indicator (/) does not animate in dev builds

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#45891]
```console
$ dart analyze --fatal-infos .
Analyzing ....                         \
```

The busy indicator (rotating line `\`) animates in stable builds but does not animate in dev builds (at least on Mac) so at first I even thought that analyzer just hang on me.

Version I tried

Broken:

```
$ dart --version
Dart SDK version: 2.14.0-57.0.dev (dev) (Wed Apr 28 15:26:37 2021 -0700) on "macos_x64"
```

Okay: 

```
$ dart --version
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
```

Might be related to Dart CLI work.

/cc @devoncarew

**Comment by devoncarew** [comment]
I can repro this.

**Comment by devoncarew** [comment]
I'll bisect this.

**Comment by devoncarew** [comment]
A bisect shows this commit as the issue: d0725fee3d5742b2dcaf3ae34df3254c456582b4 - "Update multiple packages to null safety releases.". Perhaps one of the packages updated contained a regression?

**Comment by devoncarew** [comment]
Assuming that package:cli_util might be the issue, the above commit rev'd it from `50cc840b146615899e97b892578848401b2028d5` to `fd1b716e8a350a454e01ae56df540293d31ff6c8`.

**Comment by devoncarew** [comment]
I'm guessing it's this commit which introduced the issue: https://github.com/dart-lang/cli_util/commit/2fbb4eb458d8c95b008b28ee77307b0138ec5421. cc @natebosch @jakemac53 @pq
