### ISSUE TITLE
dart:io on Windows cannot access certificates in the machine store

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#45909]
See https://github.com/dart-lang/sdk/blob/29c850db57576489f0f92f40ea6de38f8a7873f8/runtime/bin/security_context_win.cc#L52-L55

This can cause issues for Windows users who have certificates installed at the machine level that would satisfy TLS/SSL needs, even if they do not have them installed in the user store.

If we used [CertOpenStore](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certopenstore) we could also access machine level certificates.

/cc @aam

**Comment by zanderso** [comment]
It would also be useful for debugging if the command line VM took a flag to skip the native platform trusted root certs and only use the compiled-in certs on the platforms where they are compiled in. I'll file a separate issue for that.

**Comment by zanderso** [comment]
I filed https://github.com/dart-lang/sdk/issues/45912
