### ISSUE TITLE
Compiler not yelled at me when assign null value to null-safe variable

### ISSUE THREAD

**Issue by LittleFireflies** [dart-lang/sdk#45901]
## Steps to Reproduce
I have this following model or data class after I migrate with `dart migrate`:
```
class Article {
  Article({
    required this.author,
    required this.title,
    required this.description,
    required this.url,
    required this.urlToImage,
    required this.publishedAt,
    required this.content,
  });

  String author;
  String title;
  String description;
  String url;
  String urlToImage;
  DateTime publishedAt;
  String content;

  factory Article.fromJson(Map<String, dynamic> json) => Article(
        author: json["author"] == null ? null : json["author"],
        title: json["title"],
        description: json["description"] == null ? null : json["description"],
        url: json["url"],
        urlToImage: json["urlToImage"] == null ? null : json["urlToImage"],
        publishedAt: DateTime.parse(json["publishedAt"]),
        content: json["content"] == null ? null : json["content"],
      );
}
```
Compiler not telling me error at me after I assigned `author: json["author"] == null ? null : json["author"],`. So, I feel safe to run my app without checking my code again, until I found out that the app gives me error: `type 'Null' is not subtype of type 'String'`. But, it still shows error when I directly assign `author: null,`.

I don't know if it is a valid issue, or I have any misconception about null safety. Will be glad to have new insight about it. Thanks.

**Expected results:** 
Compiler should forbid me because of assigning null value to null-safe variable.

**Actual results:** 
It compiles fine but shows error on the app.

<details>
  <summary>dart --version</summary>
Dart SDK version: 2.12.4 (stable) (Unknown timestamp) on "linux_x64"
</details>

**Comment by eernstg** [comment]
You are passing a value of type `dynamic` as the actual argument for the named parameter `author`. This is accepted at compile time and there will be a type check at run time, so the behavior is as expected.
