### ISSUE TITLE
Constant map literals on VM have linear lookup

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#45908]
A lookup operation is linear for const map literal on the VM.  I don't believe this is true for a non-const on the VM or const/non-const on Web:

```
const map = { ... };

var value = map[key];
```

See: https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/immutable_map.dart#L23

**Comment by vsmenon** [comment]
@jefflim-google - is this impacting performance on your app?

**Comment by jefflim-google** [comment]
There was one specific case that I wanted to replace with a large constant map, and I noticed lots of small lookups showing up on the profile that never showed before.

I don't know whether the overall app performance is affected negatively by this -- most of our constant maps have a small number of elements, and may see little difference.

**Comment by jefflim-google** [comment]
Constant sets are also O(N) for contains() checks for final sets O(1)

**Comment by jefflim-google** [comment]
Note: a consequence of this is that Map.of(constantMap) is O(N²)

**Comment by vsmenon** [comment]
@mraleph @mkustermann - tentatively marking P1 per offline discussion.

**Comment by vsmenon** [comment]
BTW, this was @jefflim-google 's test case:

```dart
const map0 = <String, String>{
  'a': '1',
  'aaa': '111',
  'b': '2',
  'bbb': '222',
  'c': '3',
  'ccc': '333',
  'd': '4',
  'ddd': '444',
  'e': '5',
  'eee': '555',
  'f': '6',
  'fff': '666',
  'g': '7',
  'ggg': '777',
  'h': '8',
  'hhh': '888',
  'i': '9',
  'iii': '999',
  'j': 'a',
  'jjj': 'aaa',
  'k': 'b',
  'kkk': 'bbb',
};
 
final map1 = <String, String>{
  'a': '1',
  'aaa': '111',
  'b': '2',
  'bbb': '222',
  'c': '3',
  'ccc': '333',
  'd': '4',
  'ddd': '444',
  'e': '5',
  'eee': '555',
  'f': '6',
  'fff': '666',
  'g': '7',
  'ggg': '777',
  'h': '8',
  'hhh': '888',
  'i': '9',
  'iii': '999',
  'j': 'a',
  'jjj': 'aaa',
  'k': 'b',
  'kkk': 'bbb',
};
 
void runTest(String name, Map<String, String> map) {
  final startTime = DateTime.now();
  int lookups = 0;
  for (var i = 0; i < 100000; ++i) {
    String? k = 'jjj';
    while (k != null) {
      k = map[k];
      ++lookups;
    }
  }
  final endTime = DateTime.now();
  print('$name took ${endTime.microsecondsSinceEpoch - startTime.microsecondsSinceEpoch} us for $lookups lookups');
}
 
void main() {
  runTest('const', map0);
  runTest('final', map1);
  runTest('const', map0);
  runTest('final', map1);
  runTest('const', map0);
  runTest('final', map1);
  
  print(map0.runtimeType);
  print(map1.runtimeType);
}
```

**Comment by rakudrama** [comment]
In the discussion there was a question about dart2js performance.
(dart2js has several const Map representations, only one is used by the example code)

Comparison of Dart VM JIT with dart2js:
```
$ out/ReleaseX64/dart-sdk/bin/dart ~/play1/45908.dart 
const took 36169 us for 300000 lookups
final took 11424 us for 300000 lookups
const took 31445 us for 300000 lookups
final took 4623 us for 300000 lookups
const took 31478 us for 300000 lookups
final took 4582 us for 300000 lookups
_ImmutableMap<String, String>
_InternalLinkedHashMap<String, String>
$ out/ReleaseX64/dart-sdk/bin/dart2js ~/play1/45908.dart --out=o1.js && third_party/d8/linux/d8 o1.js
Compiled 8,917,237 characters Dart to 112,898 characters JavaScript in 0.82 seconds
Dart file /usr/local/google/home/sra/play1/45908.dart compiled to JavaScript: o1.js
const took 14000 us for 300000 lookups
final took 11000 us for 300000 lookups
const took 9000 us for 300000 lookups
final took 5000 us for 300000 lookups
const took 9000 us for 300000 lookups
final took 5000 us for 300000 lookups
ConstantStringMap<String, String>
JsLinkedHashMap<String, String>
```

**Comment by rakudrama** [comment]
Some observations:

-  For small maps, the linear scan might be better than a hashed lookup.
-  For larger maps, an `Expando` could be used to access a `LinkedHashMap` created on demand.
-  The operations are incorrectly using the `key`'s `==` method. [This line](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/immutable_map.dart#L24) should be `_kvPairs[i] == key`.
-  The returned value in `operator []` could use an unsafe cast [like here](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/compact_hash.dart#L379).

**Comment by dcharkes** [comment]
Using @rakudrama's suggestion:

* The const lookup backed by a LinkedHashMap in an Expando is ~2x slower than the final map.
  * Maps with <= 7 elements are quicker to access through iteration (JIT x64).
* We could get a ~1.5x solution by having an `unsafeLookup` function on Expandos.
  * Half of the Expando runtime is `_checkType` (which does essentially nothing in this case, because we no the key is an ImmutableMap).
https://github.com/dart-lang/sdk/blob/8a2b7bb5d5a7b3ff0919078b5e885a74e22ed308/sdk/lib/_internal/vm/lib/expando_patch.dart#L19-L20
https://github.com/dart-lang/sdk/blob/8a2b7bb5d5a7b3ff0919078b5e885a74e22ed308/sdk/lib/_internal/vm/lib/expando_patch.dart#L139-L150
  * Adding an unsafe lookup to Expando brings it down to ~1.5x slower than the final map.
  * Maps with <= 4  elements are quicker to access through iteration (JIT x64).

**Comment by jensjoha** [comment]
As a little extra bit of information: we have a few const sets in the constant evaluator of the compiler.
On a program specifically designed to use the sets a lot, changing the sets from const to non-const static ones instead makes the constant evaluation ~31% faster...

**Comment by vsmenon** [comment]
Any updates here?  I'm tentatively adding to the next milestone as this is P1 with an internal customer.

**Comment by mkustermann** [comment]
> Any updates here? I'm tentatively adding to the next milestone as this is P1 with an internal customer.

Most of it is in review as of today.

**Comment by eernstg** [comment]
Note that there may be some upcoming changes that are relevant to this issue (it might happen, or it might not happen, the language team hasn't made a decision):

We may change the rules about primitive equality such that it is also required for a user-written class that it does not override `hashCode`. (If it does override `hashCode` then it may or may not override `operator ==`, but in any case it won't have primitive equality&mdash;so there are no errors per se, but instances of that class can't, for instance, be elements in a constant set.)

@dcharkes, I suspect that this could make it easier to support constant collections with good performance.

@lrhn, do you have further comments on this topic?

**Comment by mkustermann** [comment]
@eernstg I suggested doing that breaking language change to @lrhn since the current rules are not consistent / make little sense. It could simplify the logic a little, but would not make a big difference in practice.

**Comment by eernstg** [comment]
@mkustermann, @dcharkes, thanks for the input!

So maybe it doesn't actually matter much for constant collections. However, it might still be a useful simplification in other situations (e.g., if a long switch is compiled to use a computed goto based on the `hashCode` of the scrutinee).
