### ISSUE TITLE
'only Ubuntu 16.04 is tested', but Ubuntu 16.04 is past end of standard support

### ISSUE THREAD

**Issue by cpswan** [dart-lang/sdk#45904]
* Dart SDK Version 2.12.4
* Linux
* Browser N/A

The [Get the Dart SDK](https://dart.dev/get-dart) page states:

> Linux
**Supported versions:** Recent Linux versions, but only Ubuntu 16.04 is tested.

Ubuntu 16.04 passed end of standard support in Apr 2021 (per [Ubuntu Releases Wiki](https://wiki.ubuntu.com/Releases))

**Comment by mit-mit** [comment]
@athomas are we updating this?

**Comment by athomas** [comment]
yes, Yes, and YES!

**Comment by athomas** [comment]
Internal tracking bug: https://crbug.com/1207358

**Comment by athomas** [comment]
The page was updated a while back and the testing infra mostly runs on Bionic now (nothing is using Xenial anymore).
