### ISSUE TITLE
Add quick fix for unnecessary_getters_setters

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#45929]
The fix should rename the field and remove the getter and setter.

**Comment by bwilkerson** [comment]
This rule generates a lint on both the getter and the setter. A single-use fix could be invoked on either and fix both, but when applied in bulk the two would conflict with each other.

One possibility would be to change the rule to only lint one or the other. Thoughts?

@pq

**Comment by pq** [comment]
> One possibility would be to change the rule to only lint one or the other. 

This works for me and seems consistent with what we've done elsewhere.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/215121
