### ISSUE TITLE
Add quick fix for avoid_print

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#45921]
The fix should make the invocation of `print` conditional on `kDebugMode`.

**Comment by pq** [comment]
@bwilkerson: I'm assuming the fix should check to see if we're in a Flutter project and add a 'package:flutter/foundation.dart' import if needed?

**Comment by bwilkerson** [comment]
Assuming that's where `kDebugMode` is defined, yes.

**Comment by bwilkerson** [comment]
There's a second reasonable fix, which is to remove the invocation of `print`.

I think we'd only want either of these fixes in the case where the invocation of `print` is the expression of an expression statement. If you can think of other places where one or the other should be applied, let me know.

**Comment by pq** [comment]
+1. Thanks!

**Comment by bwilkerson** [comment]
The first fix was added here: https://dart-review.googlesource.com/c/sdk/+/213801.

**Comment by bwilkerson** [comment]
> Does that need to be corrected for this to be closed out?

No, I don't think so. It would be nice for it to be done, but I don't know that it's impacting a lot of users.
