### ISSUE TITLE
 const Set.empty constructor

### ISSUE THREAD

**Issue by zs-dima** [dart-lang/sdk#45938]
Could be nice to have  const Set<T>.empty constructor to be able to declare fields with Set<T> type.

**Comment by mraleph** [comment]
`const {}` constructs an empty set if used in a place where `Set<T>` is expected, e.g. 

```dart
final Set<String> x = const {};  // const {} is an empty constant Set
```

> to be able to declare fields with Set type

It is a bit unclear how this is related? Could you clarify? You can declare fields just fine - you just need to make sure they are initialised or nullable or late, e.g. 

```dart
class X {
  final Set<String> s;
  X(this.s);  // ok
  X({required this.s}); // also ok
  X() : s = something; // also ok
}
```

**Comment by zs-dima** [comment]
@mraleph 
`final Set<T> x = const <T>{};`
- awesome, thanks a lot
