### ISSUE TITLE
Observatory is broken in the latest SDK

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#45933]
Run a console application with `--enable-asserts --enable-vm-service:49618`.

```console
Observatory listening on http://127.0.0.1:49618/fiNvm3Tot50=/

The Dart DevTools debugger and profiler is available at: http://127.0.0.1:49618/fiNvm3Tot50=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A49618%2FfiNvm3Tot50%3D%2Fws
```

Connecting to `http://127.0.0.1:49618/fiNvm3Tot50=/` gives `{"jsonrpc":"2.0", "error":{"code":-32601,"message":"Method not found","data":{"request":{"method":"fiNvm3Tot50=","params":{}}}},"id":""}`.

Where
```console
scheglov@scheglov-macbookpro2:~/Applications$ dart --version
Dart SDK version: 2.14.0-edge.29c850db57576489f0f92f40ea6de38f8a7873f8 (be) (Wed May 5 01:06:12 2021 +0000) on "macos_x64"
```

**Comment by bkonyi** [comment]
Thanks for reporting @scheglov. The DevTools integration has been reverted for now, so if you rebase things should be working again. I'll investigate before relanding.

**Comment by bkonyi** [comment]
Looks like there was some incorrectly configured middleware for auth codes / DDS debugging. Should be an easy fix.
