### ISSUE TITLE
CompileTimeErrorCodes without tests

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#45957]
There appear to be no test for either `CompileTimeErrorCode.MIXIN_INFERENCE_INCONSISTENT_MATCHING_CLASSES` or `CompileTimeErrorCode.MIXIN_INFERENCE_NO_MATCHING_CLASS`.

These codes should either have tests associated with them or they should be removed.

**Comment by srawlins** [comment]
Neither of these codes exist any longer.
