### ISSUE TITLE
List.insert behavior

### ISSUE THREAD

**Issue by BLitzMe** [dart-lang/sdk#45961]
Perhaps I'm making a dumb mistake, but there is a behavior in the snippet below that i don't understand. But it also could be a bug. I'll let the Gurus decide

```
   void main() {
    List<int> myList = List.generate(2, (_) => 0, growable: true);

    myList.addAll(List<int>.generate(1, (_) => 0));

    myList.insert(3, 11);

    print(myList);
    }
```

I generate a list with two elements. Then I add a list with one element to it. So in total the original list should have 3 elements. So why does an insert at index 3 (fourth element) work? I expect an out of range error as is the case with myList.insert(4, 11).

**Comment by lrhn** [comment]
It works because we allow inserting before or after any element of the list.

It's a fencepost issue - the position you provide to `insert`  is not the index of an element, but the index of a gap between elements (or before the first or after the last element).

**Comment by BLitzMe** [comment]
thankyou so much. That explains it
