### ISSUE TITLE
Prepare package:wasm for publishing

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#45967]
The `pubspec` has a few issues:

1. Says "not for publishing"
2. SDK constraint should be `">=2.10.0 <3.0.0"`
3. ffi dep should be rolled to `^1.0.0`
4. dev_dep om `pedantic` is missing

The `readme.md` file should have some contents. Can we provide a very small set of steps for for example calling into a `hello world`-like piece of C code or something like that?

**Comment by liamappelbe** [comment]
I should also move the unit tests into this directory
