### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by klee06420** [dart-lang/sdk#45962]
Hi All;
   Today i have receive my classmate sharing the 
futtle error after i compile

error: The named parameter 'child' isn't defined. (undefined_named_parameter at [grocery_store] lib\pages\profile_page.dart:159)

i need help
<img width="960" alt="error" src="https://user-images.githubusercontent.com/82371575/117600639-e6234980-b17e-11eb-9896-110965ff4369.png">

**Comment by jcollins-g** [comment]
This does not seem to be an analyzer bug.  If you are using the latest version of Flutter and its `showDialog` function:  https://api.flutter.dev/flutter/material/showDialog.html, `showDialog` no longer has a `child` argument.  It should be replaced with the `builder` argument.  See the referenced documentation.
