### ISSUE TITLE
Incorrect and duplicated diagnostics regarding generators

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#45960]
Create a file containing the following code:

```dart
Iterable<int> f() sync* {
  return 3;
}
```

The analyzer will produce two diagnostics:

```
error: Can't return a value from a generator function (using the 'async*' modifier). (return_in_generator)
error: Can't return a value from a generator function (using the 'sync*' modifier). (return_in_generator)
```

Only the second of these is correct (the function is not marked as `async*`). I believe that this is happening because the parser is producing the first and analyzer is producing the second.

If we use the `async*` modifier:

```dart
Stream<int> f() async* {
  return 3;
}
```

We get a valid message, but still get two copies, one from the parser and one from the analyzer:

```
error: Can't return a value from a generator function (using the 'async*' modifier). (return_in_generator)
error: Can't return a value from a generator function (using the 'async*' modifier). (return_in_generator)
```

The situation is even worse when an expression body is used:

```dart
Iterable<int> f() sync* => 3;
```

The diagnostics produced are:

```
error: Functions marked 'async' must have a return type assignable to 'Future'. (illegal_async_return_type)
error: Can't return a value from a generator function (using the 'async*' modifier). (return_in_generator)
```

even though neither of the modifiers are used.

If we change the modifier to `async*`:

```dart
Stream<int> f() async* => 3;
```

We get the same two diagnostics as with `sync*`:

```
error: Functions marked 'async' must have a return type assignable to 'Future'. (illegal_async_return_type)
error: Can't return a value from a generator function (using the 'async*' modifier). (return_in_generator)
```

While the second is now correct, the first is not.

I believe that the parser's messages need to be fixed and that the analyzer needs to stop producing duplicate diagnostics.

**Comment by srawlins** [comment]
```dart
Iterable<int> f() sync* {
  return 3;
}
```

now only features one error:

> error • 45960.dart:2:3 • Can't return a value from a generator function that uses the 'async*' or 'sync*' modifier. Try replacing 'return' with 'yield', using a block function
          body, or changing the method body modifier. • return_in_generator

-----

```dart
Stream<int> f() async* {
  return 3;
}
```

also produces only one:

>  error • 45960-2.dart:2:3 • Can't return a value from a generator function that uses the 'async*' or 'sync*' modifier. Try replacing 'return' with 'yield', using a block
          function body, or changing the method body modifier. • return_in_generator

-----

```dart
Iterable<int> f() sync* => 3;
```

still produces two :(

-----

```dart
Stream<int> f() async* => 3;
```

now produces one:

> error • 45960-4.dart:1:24 • Can't return a value from a generator function that uses the 'async*' or 'sync*' modifier. Try replacing 'return' with 'yield', using a block
          function body, or changing the method body modifier. • return_in_generator
