### ISSUE TITLE
[analyzer] Static check on `yield` should use the element type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45971]
Consider the following program:

```dart
import 'dart:async';

Stream<int> f() async* {
  dynamic d = 1;
  yield d;
}

Iterable<int> g() sync* {
  dynamic d = 1;
  yield d;
}

void main() async {
  await for (var i in f()) print(i);
  for (var i in g()) print(i);
}
```

The current analyzer (from commit dce0263228c0587fe6258e2cc7ed01ffacbd5c2e) reports an error for each of the two `yield` statements:

```dart
ERROR|COMPILE_TIME_ERROR|YIELD_OF_INVALID_TYPE|/usr/local/google/home/eernst/lang/dart/scratch/202105/n012.dart|5|9|1|The type 'Stream<dynamic>' implied by the 'yield' expression must be assignable to 'Stream<int>'.
ERROR|COMPILE_TIME_ERROR|YIELD_OF_INVALID_TYPE|/usr/local/google/home/eernst/lang/dart/scratch/202105/n012.dart|10|9|1|The type 'Iterable<dynamic>' implied by the 'yield' expression must be assignable to 'Iterable<int>'.
```

However, the check [should actually](https://github.com/dart-lang/language/blob/86f7ed6dc4a8a33e24107d3a29b403c6ce295ae8/specification/dartLangSpec.tex#L18367) be performed based on the element type of `f` and `g`, namely `int`, so the question is whether `dynamic` is assignable to `int`, not whether `Iterable<dynamic>`/`Stream<dynamic>` is assignable to `Iterable<int>`/`Stream<int>`.

**Comment by eernstg** [comment]
Thanks!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/199140

**Comment by srawlins** [comment]
Analyzer now reports:

```none
  error • 45971.dart:5:9 • A yielded value of type 'dynamic' must be assignable to 'int'. • yield_of_invalid_type
  error • 45971.dart:10:9 • A yielded value of type 'dynamic' must be assignable to 'int'. • yield_of_invalid_type
```
