### ISSUE TITLE
Symlinks failing on windows bots

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#45981]
There are new test failures on [Don't report deprecated hints from deprecated constructors....[vm/concurrency] Track on [Thread] whether VM can deopt a mutator](https://github.com/dart-lang/sdk/compare/de767e3f2d237a0724862d1ff7497579d04bde34~...fa521e4c71542f07bda8e864de351b2cbd308a29).

The tests
```
co19/LibTest/io/Link/resolveSymbolicLinksSync_A01_t01 RuntimeError (expected Pass)
co19/LibTest/io/Link/resolveSymbolicLinksSync_A01_t01 RuntimeError (expected Pass)
co19/LibTest/io/Link/resolveSymbolicLinks_A01_t01 RuntimeError (expected Pass)
co19/LibTest/io/Link/resolveSymbolicLinks_A01_t01 RuntimeError (expected Pass)
```
are failing on all windows bots with the following error:

```
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\dart.exe --enable_asserts --no-sound-null-safety --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\tests\co19\src\LibTest\io\Link\resolveSymbolicLinksSync_A01_t01.dart

exit code:
255

stderr:
Unhandled exception:
FileSystemException: Cannot resolve symbolic links, path = 'C:\b\s\w\iton6qvt\co19-resolveSymbolicLinksSync_A01_t01_7b6bedce\co19-resolveSymbolicLinksSync_A01_t01_18db5e28\resolveSymbolicLinksSync_A01_t01_3_8269.lnk' (OS Error: Access is denied.

, errno = 5)
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:818:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:348:5)
#2      _main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/resolveSymbolicLinksSync_A01_t01.dart:66:34)
#3      inSandbox (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/file_utils.dart:24:22)
#4      main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/resolveSymbolicLinksSync_A01_t01.dart:32:9)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n dartk-weak-asserts-win-release-x64 co19/LibTest/io/Link/resolveSymbolicLinksSync_A01_t01
```

[One of the logs](https://dart-ci.appspot.com/log/vm-kernel-nnbd-win-release-x64/dartk-weak-asserts-win-release-x64/212/co19/LibTest/io/Link/resolveSymbolicLinksSync_A01_t01).

This does not look like it is related to any of the mentioned commits.

@athomas @whesse did something change with the Windows bot setup related to symlinks?

**Comment by whesse** [comment]
The Windows bots updated to a more recent version of Windows 10.  This may have changed the behavior, or it may have exposed some problem which was potentially there before also.

The actual failure seems to be when dereferencing a symbolic link that starts with "..\".  This is "link3" in the tests, and links between two sibling directories inside a temporary directory.

There are bug reports of many existing failures and differences in behavior between Windows and other OSs in the dart:io file system libraries, adding this report to those: #29096
