### ISSUE TITLE
Code generation is broken for direct_parser_ast_helper.dart

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#45984]
I'm in the middle of making some experimental changes that require modifying `direct_parser_ast_helper.dart`, which is a generated file.  When I try running the code generator (even without my other changes), I get analysis errors.  It looks like the code generator probably needs some changes to accommodate null safety.

I'm also concerned by the fact that no test failure occurred to alert us to the fact that the code generator needed to be re-run; I think we should add a front_end test that verifies that the current contents of `direct_parser_ast_helper.dart` matches the output of the code generator, so that future breakages like this get noticed immediately.

You can see the results of running the code generator here: https://dart-review.googlesource.com/c/sdk/+/199320, and the corresponding anaylsis errors here: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8847513079265343744/+/u/analyze_pkg_front_end/stdout

**Comment by stereotype441** [comment]
@johnniwinther @jensjoha FYI

**Comment by stereotype441** [comment]
Thanks, @jensjoha!  I couldn't help but notice that d8f5e0ad864eb7c058cc35399fce6270dfb0df34 doesn't add any tests.  As I mentioned in the issue above, I'm concerned by the fact that no test failure occurred to alert us to the fact that the code generator needed to be re-run.  Are you planning to add a front_end test that verifies that the current contents of `direct_parser_ast_helper.dart` matches the output of the code generator?

**Comment by jensjoha** [comment]
It's a follow-up that I'm landing shortly.

**Comment by jensjoha** [comment]
Landed as 915d0f4601cb9cfbfb30275adbc3b1f76d9f543f.
