### ISSUE TITLE
Make JIT/AOT VM pipeline aware of closure annotations

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#45987]
Right now TFA as well as the kernel reader in the VM are not taking annotations for local closures into account. We should enable this to e.g. guide our inliner to recognize `@pragma('vm:prefer-inline')` or other related vm-specific annotations.

The kernel AST stores those annotations in `FunctionDeclaration.variable.annotations`.

Let's track this here with at least the sub-parts:

  * [ ] Make TFA + tree shaker aware of those annotations and handle them in a similar way to member annotations (see [cl/199200](https://dart-review.googlesource.com/c/sdk/+/199200/))
  * [x] Make flow graph builder recognize annotations on local functions when they are lazily created.

/cc @alexmarkov @mraleph 

/cc @cskau-g Due to connection with https://github.com/dart-lang/sdk/issues/45710

**Comment by cskau-g** [comment]
Possibly both the sub-parts are addressed now. Is there more that we need to address before closing this issue?

**Comment by mkustermann** [comment]
Yes, seems like the inliner is also respecting the pragmas on closures now.
