### ISSUE TITLE
Analyzer silently drops exceptions occurring during parsing

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#45983]
This morning I've been trying to debug an analyzer exception that happens during parsing of invalid code, and I was confused as to why I could only see the exception when invoking the analyzer through its Dart API; the `dart analyze` and `dartanalyzer` commands did not exhibit the problem.

Then I found this code, from `pkg/analyzer/lib/src/dart/analysis/file_state.dart`:
```dart
  /// Return a new parsed unresolved [CompilationUnit].
  ///
  /// If an exception happens during parsing, an empty unit is returned.
  CompilationUnitImpl parse([AnalysisErrorListener? errorListener]) {
    errorListener ??= AnalysisErrorListener.NULL_LISTENER;
    try {
      return _parse(errorListener);
    } catch (_) {
      return _createEmptyCompilationUnit();
    }
  }
```

Although I can see the value of preventing the user from experiencing a crash, dropping the exception completely like this means that any exceptions that happen during the parser/AstBuilder stage of analysis won't show up on trybots.  For instance, if a test contains a deliberate syntax error that causes the AstBuilder to emit a syntax error and then throw an exception, it will show up on the bot as a passing test (because a syntax error was emitted before the exception occurred).  But the user experience will be bad; they will get no error recovery, no syntax errors from the rest of the file, and no resolution results anywhere in the file (hence no code completion or navigation).

If we can figure out a way that exceptions like this show up as crashes on the trybots, while still preventing the user from experiencing a crash, I think it could help us track down a category of analyzer bugs that have been flying under our radar.

**Comment by bwilkerson** [comment]
The `dart analyze` command is a client of the server, and the server has a mechanism for reporting errors to the client. The command could report those errors to the user and/or have a mode in which such errors cause the command to fail the bots.

I'm not sure whether that's the best solution, but I do believe that any exceptions that occur in the parser should also be reported to the instrumentation log so that they end up in our crash reporting system.

**Comment by stereotype441** [comment]
@bwilkerson to clarify, when you say, "I do believe that any exceptions that occur in the parser should also be reported to the instrumentation log", do you mean (a) you believe that such exceptions are already reported to the instrumentation log, or (b) that we ought to change the code in order to ensure that such exceptions are reported to the instrumentation log?

Given the implementation of the `FileState.parse` method I quoted above, I can't see any way that these exceptions would be reported to the instrumentation log today, so I assume you mean (b)?

**Comment by bwilkerson** [comment]
Yes, I meant the latter. We ought to be reporting them, even though we're clearly not at the moment.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/199369
