### ISSUE TITLE
Dart analysis not working properly on "timer"

### ISSUE THREAD

**Issue by darkrevenger** [dart-lang/sdk#45995]
I think I've already written here everything I could to explain the issue in here: https://github.com/flutter/flutter/issues/81962 

If you need me to re-write/upload the things here please let me know.

**Comment by julemand101** [comment]
Just to clarify, are you ever reading the `_timer` variable in your code? The analyzer warning is given for variables you are only setting but never read since this variables can often be removed without any side effect.

**Comment by darkrevenger** [comment]
I used to have a dispatch but removed it since I need it runing 24/7 now, so, the variable greyed out is actually correct?

**Comment by julemand101** [comment]
@darkrevenger Yes, it is correct behavior since the variable is private so there are no way some other code outside your package are going to use the variable.

**Comment by jcollins-g** [comment]
P4 as this appears technically correct, but is confusing since the intention is to create a "background process" and explicitly retain a handle to it (making it clearer to the reader of the code what is happening).   This might be working as intended (user should mark to ignore the unused field).

**Comment by darkrevenger** [comment]
Yes, thank you for the explanation everyone, I'm closing since I see it was my misunderstunding of the analyzer.
