### ISSUE TITLE
[analyzer] dart analyze yields different results than Dart Analysis window in IDE

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#45999]
I tried to come up with a simple repro with the same import of `package:shelf` and use of the `Handler` typedef, but could not repro there. Here is the best repo I have: https://github.com/flutter/devtools/pull/3009. If you clone devtools and checkout the changes from that branch, you should be able to see the issues.

I am using a type def from `package:shelf` in my code.
`typedef Handler = FutureOr<Response> Function(Request request);`

In my code, I have `shelf.Handler? handler` as a method parameter, but this is giving me an analysis error.
<img width="816" alt="Screen Shot 2021-05-12 at 10 31 30 AM" src="https://user-images.githubusercontent.com/43759233/118029277-dccde480-b318-11eb-8671-d0fcf3962a3d.png">

Dart analysis in IntelliJ:
<img width="1115" alt="Screen Shot 2021-05-12 at 11 48 43 AM" src="https://user-images.githubusercontent.com/43759233/118028710-3e418380-b318-11eb-9183-701dbc6bf1dc.png">

Results from running `dart migrate`:
```
[~/develop/devtools/packages/devtools_server • null-safe • 130] ~/develop/flutter/bin/dart analyze
Analyzing devtools_server...           1.5s

  error • lib/src/external_handlers.dart:42:62 • The method 'toFilePath' can't be
          unconditionally invoked because the receiver can be 'null'. Try making the call
          conditional (using '?.') or adding a null check to the target ('!'). •
          unchecked_use_of_nullable_value
warning • lib/src/external_handlers.dart:50:15 • The '!' will have no effect because the
          receiver can't be null. Try removing the '!' operator. •
          unnecessary_non_null_assertion
  error • lib/src/file_system.dart:16:12 • A value of type 'String?' can't be returned from the
          method '_userHomeDir' because it has a return type of 'String'. •
          return_of_invalid_type
   info • lib/src/memory_profile.dart:169:39 • Avoid redundant argument values. •
          avoid_redundant_argument_values
  error • lib/src/server.dart:90:12 • A value of type 'int?' can't be assigned to a variable of
          type 'int'. Try changing the type of the variable, or casting the right-hand type to
          'int'. • invalid_assignment
  error • lib/src/server.dart:100:21 • A value of type 'int?' can't be assigned to a variable of
          type 'int'. Try changing the type of the variable, or casting the right-hand type to
          'int'. • invalid_assignment
  error • lib/src/server.dart:703:7 • The argument type 'Uri?' can't be assigned to the
          parameter type 'Uri'. • argument_type_not_assignable
  error • lib/src/server.dart:747:9 • The argument type 'Uri?' can't be assigned to the
          parameter type 'Uri'. • argument_type_not_assignable
  error • lib/src/server.dart:1058:27 • A value of type 'Uri?' can't be assigned to a variable
          of type 'Uri'. Try changing the type of the variable, or casting the right-hand type
          to 'Uri'. • invalid_assignment
warning • lib/src/server_api.dart:34:21 • The '!' will have no effect because the receiver can't
          be null. Try removing the '!' operator. • unnecessary_non_null_assertion
  error • lib/src/server_api.dart:75:27 • The argument type 'String?' can't be assigned to the
          parameter type 'String'. • argument_type_not_assignable
  error • lib/src/server_api.dart:91:40 • A value of type 'String?' can't be assigned to a
          variable of type 'String'. Try changing the type of the variable, or casting the
          right-hand type to 'String'. • invalid_assignment
  error • lib/src/server_api.dart:124:27 • The argument type 'String?' can't be assigned to the
          parameter type 'String'. • argument_type_not_assignable
  error • lib/src/server_api.dart:157:63 • The argument type 'String?' can't be assigned to the
          parameter type 'String'. • argument_type_not_assignable
  error • lib/src/server_api.dart:170:63 • The argument type 'String?' can't be assigned to the
          parameter type 'String'. • argument_type_not_assignable
warning • lib/src/usage.dart:168:43 • The '!' will have no effect because the receiver can't be
          null. Try removing the '!' operator. • unnecessary_non_null_assertion

16 issues found.
```

@scheglov

**Comment by scheglov** [comment]
Works for me with the latest SDK.
![image](https://user-images.githubusercontent.com/384794/118030453-2c60e000-b31a-11eb-8c70-1c31e1cacf4a.png)
I tried to remove / add `?` - it reacts as expected, by reporting or not the error.

**Comment by scheglov** [comment]
It might be because of a bug in the cache, try to remove your `~/.dartServer/.analysis-driver` and restart DAS.

**Comment by kenzieschmoll** [comment]
from `~/.dartServer` I ran `rm -rf .analysis-driver`, and clicked the Restart button from IntelliJ, and the same analyses came up.
<img width="30" alt="Screen Shot 2021-05-12 at 12 38 18 PM" src="https://user-images.githubusercontent.com/43759233/118034535-f2dea380-b31e-11eb-8f74-f83a76cf18ee.png">

**Comment by scheglov** [comment]
Archive the package and send it to me.
Maybe I have not applied all that is necessary.

**Comment by kenzieschmoll** [comment]
Debugged with @scheglov offline. The Dart settings for the IntelliJ project pointed to an outdated Dart SDK, where as the `dart analyze` command was using the latest Dart 2.14 from the flutter SDK, so that is where the discrepancy was coming from. This is resolved. Thanks!
