### ISSUE TITLE
would like a mirror of https://github.com/dart-lang/lints

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#46007]
We've recently added a new package to dart-lang - the 'lints' package. We'd like to use this in the sdk repo as a setting for static analysis, and need to be able to bring it in as a DEP.

The url is https://github.com/dart-lang/lints; thanks!

cc @pq

**Comment by athomas** [comment]
Done: https://dart.googlesource.com/lints

**Comment by devoncarew** [comment]
👍 , thanks!
