### ISSUE TITLE
Inaccurate dartdocs for comparison operators in classes num, int, and double (SDK version 2.13.0) 

### ISSUE THREAD

**Issue by simphotonics** [dart-lang/sdk#46015]
The comments documenting the comparison operators in the classes `num` (and implicitly `int` and `double`) are inaccurate. 
(See below.)

For example in the expression:  `1 < 2` the parameter `other` is 2 yet the docs suggest that `other` should be numerically **smaller** than this number.

From file: `lib/core/num.dart`  
```Dart
  /// Whether [other] is numerically smaller than this number.
  ///
  /// If either operand is the [double] NaN, the result is always false.
  bool operator <(num other);

  /// Whether [other] is numerically smaller than or equal to this number.
  ///
  /// If either operand is the [double] NaN, the result is always false.
  bool operator <=(num other);

  /// Whether [other] is numerically greater than this number.
  ///
  /// If either operand is the [double] NaN, the result is always false.
  bool operator >(num other);

  /// Whether [other] is numerically greater than or equal to this number.
  ///
  /// If either operand is the [double] NaN, the result is always false.
  bool operator >=(num other);
```

It would be clearer to change the docs e.g. of the operator `<` to:
```Dart 
  /// Returns `true` if this number is numerically smaller than [other] .
  ///
  /// If either operand is the [double] NaN, the result is always false.
  bool operator <(num other);
```

**Comment by lrhn** [comment]
I personally prefer the "Whether" to "Returns `true`" phrasing. 
For one thing, the example of the latter here doesn't say what is returned when the number is not numerically smaller than `other`.

I also (personally) think that starting a DartDoc with "Returns" is strictly less readable and useful than the current documentation.

So, the change I am willing to consider would be *adding* a "Returns" paragraph, or modifying the last line:
```dart
/// Returns `true` is this number is numerically smaller than [other]. 
/// Returns `false` if this number is greater than or equal to `other`, 
/// or if either value is [NaN](double.nan).
```
