### ISSUE TITLE
Analyzer error location includes class comments.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#46033]
See https://dart-review.googlesource.com/c/sdk/+/199480/1..2/tests/language/nonfunction_type_aliases/private_names/private_name_duplicate_interface_error_test.dart as an example.

For some errors, the analyzer considers the entire class declaration as the range of the error.
For that purpose, the class declaration seems to include the preceding doc comment.

Just want to make sure that is deliberate. So, is it?

It has an uncomfortable interaction with the `pkg/test_runner/tool/update_static_error_tests.dart` script which puts expectation on the line after the start of the issue. Running that will put the `// [error line 40, column 1]` line in the middle of  the DartDoc comment.

**Comment by bwilkerson** [comment]
No, the Dartdoc comment should never be included in the diagnostic range, and the range should probably never be the whole class. We generally try to limit the range to the smallest number of characters possible in order to draw the user's attention to the location of the underlying error.

**Comment by bwilkerson** [comment]
The specific case mentioned above should be fixed by https://dart-review.googlesource.com/c/sdk/+/200240. Please let us know if you find other such cases.
