### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by divitcr7** [dart-lang/sdk#46032]
Not able to see FlatButton properities

## Version information

- `IDEA AI-202.7660.26.42.7322048`
- `2.12.2`
- `AI-202.7660.26.42.7322048, JRE 11.0.8+10-b944.6842174x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

**Comment by srawlins** [comment]
Thanks for filing an issue. Please explain in more detail the issue you are facing. How do you reproduce the issue? What is the expected behavior? What is the actual behavior?
