### ISSUE TITLE
Tried to initialize from a previous compilation

### ISSUE THREAD

**Issue by davidsowerby** [dart-lang/sdk#46030]
Running flutter test from Android Studio:

```
Warning: Tried to initialize from a previous compilation (file:///home/david/git/precept/precept_client/build/test_cache/build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill), but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file /tmp/initialize_from.dillAOAZER/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.
```

**Comment by davidsowerby** [comment]
Forgot the file:
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/6492780/initialize_from.dill.gz)

**Comment by srawlins** [comment]
My best guess for triage is... area-vm?

**Comment by Hixie** [comment]
This is easy to reproduce by having the compiler race with itself, e.g. run `flutter test` simultaneously on the same directory in multiple consoles at the same time.

**Comment by jensjoha** [comment]
Thanks for reporting this.
With Hixies comment in mind I'll assume this is a tooling error (as in the tool provides us a partly written dill --- the tool (flutter in this case) shouldn't do that) and I'll close the issue.
