### ISSUE TITLE
Add explicit discard for futures you don't want to `await`

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#46047]
This tracker is for issues related to: dart:async

Right now if you have the `unawaited_futures` linter turned on there isn't a way to not `await` an asynchronous operation without using linter ignores.  Ideally there should be a way to explicitly disregard the asynchronous operation without resorting to using ignores or going for implicitly discarded futures.

For example:
```dart
Future<void> bar() {...}
void foo() {
  bar(); # linter error
}
```

becomes:
```dart
Future<void> bar() {...}
void foo() {
  bar().discard();
}
```

While one could create an extension method for `future`, it wouldn't be that helpful unless the autofix tools for linter errors suggested using `discard()`.  For that it as to be built into the dart sdk.

**Comment by dnfield** [comment]
The typical way to do this is to use `unawaited` from package:pedantic (or similar impl if you don't want a runtime dependency on pedantic).

**Comment by gaaclarke** [comment]
That's good, but it's too obscure and the should be built into the standard sdk.  It could even be part of the language, not sure if that is preferable.
```dart
Future<void> bar() {...}
void foo() {
  unawait bar();
}
```

**Comment by MrBirb** [comment]
Related #45284

**Comment by gaaclarke** [comment]
I'd say https://github.com/dart-lang/sdk/pull/45284 captures the essence of this issue.  Closing this so discussion can happen there.
