### ISSUE TITLE
Migrate pkg/analyzer_utilities/lib/tools.dart off `dartfmt`

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#46046]
The `dartfmt` command line executable is deprecated in favor of the newer `dart format` command. I see a class `DartFormat` in pkg/analyzer_utilities/lib/tools.dart that invokes `dartfmt` directly. If that class is still in use (the only reference to it I see is in pkg/analysis_server/tool/code_completion/relevance_table_generator.dart), it should be migrated to `dart format` or to the dart_style [library API](https://pub.dev/documentation/dart_style/latest/dart_style/DartFormatter-class.html).

**Comment by devoncarew** [comment]
https://dart-review.googlesource.com/c/sdk/+/200300, though I'm going to make sure it builds cleanly before I put it out for review.

**Comment by munificent** [comment]
That was fast, thanks!
