### ISSUE TITLE
No published analyzer available for language version 2.14.0

### ISSUE THREAD

**Issue by CaseyHillers** [dart-lang/sdk#46041]
```
$ dart run build_runner build --delete-conflicting-outputs
Precompiling executable... (10.4s)
Precompiled build_runner:build_runner.
[INFO] Generating build script completed, took 305ms
[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot... completed, took 11.0s
[INFO] Building new asset graph completed, took 627ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[WARNING] json_serializable:json_serializable on lib/protos.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.12.0
SDK language version: 2.14.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.14.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[SEVERE] json_serializable:json_serializable on lib/protos.dart:
```

* Dart SDK Version (`dart --version`)
```
$ dart --version
Dart SDK version: 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af (be) (Fri May 14 15:47:38 2021 +0000) on "linux_x64"
```

* Whether you are using Windows, MacOSX, or Linux (if applicable)
`Linux`

**Comment by CaseyHillers** [comment]
Flutter related issue: https://github.com/flutter/flutter/issues/82705

**Comment by srawlins** [comment]
@scheglov do we have a new publish in the works?

**Comment by scheglov** [comment]
Do we need another version? AFAIK `analyzer 1.5.0` supports language `2.14`.

**Comment by devoncarew** [comment]
@jakemac53 - can you provide some details about how to triage these issues? The error message - `No published analyzer available for language version xxx` - indicates that there is no analyzer supporting that language version; I suspect that it's more correct to say that the analyzer version is use locally doesn't support that version?

**Comment by srawlins** [comment]
> Do we need another version? AFAIK analyzer 1.5.0 supports language 2.14.

The error doesn't indicate what the latest version number known is, at the time of reporting. But if we have an analyzer release which understands "current" language version is 2.14, then we can close.

**Comment by CaseyHillers** [comment]
> The error doesn't indicate what the latest version number known is

This project ran into the issue with a transitive dependency of `analyzer=0.41.2

**Comment by jakemac53** [comment]
@devoncarew  The message does include the text **and have the latest analyzer** in the message, and the first suggestion we give is to upgrade your analyzer, but I do think we will still get false positives filed.

In the case of a false positive issue (it sounds like this is one?) I would close the issue and suggest that they increase their analyzer version to the latest (which for most users will require updating some other dependency that is actually limiting it).

**Comment by devoncarew** [comment]
> In the case of a false positive issue (it sounds like this is one?)

Note that we get a fair number of these issues filed; I believe most of them are false positives.

**Comment by jakemac53** [comment]
We can try re-wording the message to be more clear, I am not sure exactly what to add there. Maybe we need to link it to a Doc somewhere instead which is a lot more long winded and only at the bottom of that does it suggest filing an issue?

**Comment by srawlins** [comment]
I don't think we've seen too many false positives since I changed the wording [in March](https://github.com/dart-lang/build/commit/19d3b8f060458a339966182d8e8468df21d104c9).

**Comment by jakemac53** [comment]
I am going to go ahead and close this issue in any case as it doesn't seem actionable. Definitely open to wording suggestions or other thoughts on the message, but probably in an issue specific to that?

**Comment by CaseyHillers** [comment]
The issue I saw was Dart couldn't resolve a compatible `analyzer` for my project. This required some debugging, and to make progress on the issue required me to add `analyzer: ^1.5.0` to my pubspec.yaml to progress on fixing the dependency issues.

It would have been helpful to surface Dart wasn't able to resolve analyzer due to conflicts instead of saying the package was missing for 2.14.

**Comment by jakemac53** [comment]
The tool giving this message only knows that the current analyzer doesn't support the current language version. We could reach out to pub to ask what the latest version of the analyzer _is_ I think, and provide a more informed message, but I am not enthused about blocking the build on network requests... we may be able to still return early and log this warning asynchronously though.

We could even not suggest filing an issue at all unless you are on the latest analyzer in that case?

**Comment by jakemac53** [comment]
I looked a bit into this and created https://github.com/dart-lang/build/pull/3107

**Comment by devoncarew** [comment]
@jakemac53 - thanks for the messaging updates in dart-lang/build#3107 !
