### ISSUE TITLE
Private constructors of generic classes are externally exposed with no static analysis error, but does error at compile time as expected

### ISSUE THREAD

**Issue by acoutts** [dart-lang/sdk#46057]
```
Dart SDK version: 2.14.0-74.0.dev (dev) (Mon May 3 05:56:14 2021 -0700) on "macos_x64"
```

Example code:

## `foo.dart`
```dart
class Foo<T> {

  /// This should not be callable outside of this class
  Foo._private();

  static Foo public() {
    return Foo._private();
  }
}
```

## `foo_consumer.dart`
```dart
import 'foo.dart';

class FooConsumer {
  void test() {
    final bar = Foo._private(); // Should have static analysis error
  }
}

```

`FooConsumer` should not be able to access `_private()` on `Foo`, but there is no static analysis error for this. There is however a compile time error as you would expect.

As soon as I remove the generic type from `Foo` then the analysis error is visible as expected:
```dart
class Foo {
...
```

```
The class 'Foo' doesn't have a constructor named '_private'.
Try invoking a different constructor, or define a constructor named '_private'.dart(new_with_undefined_constructor)
```

The compile time error is expected but the lack of a static analysis error is unexpected.

**Comment by eernstg** [comment]
Re-running the example locally, I can see that the analyzer accepts the invocation of the private constructor, but the common front end (via `dart`) reports the error as expected.

**Comment by acoutts** [comment]
Ah yes I meant compile time, you are right. I was working in VSCode if that helps as well.

**Comment by eernstg** [comment]
OK, good! I think VSCode makes no difference: I saw the same behavior with a command line `dartanalyzer`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/200530
