### ISSUE TITLE
Need to analyze more flutter code in try-bots

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#46063]
I broke the flutter engine roll when I introduced a new Hint, unnecessary_import. This hint has violations in flutter plugins, cocoon, generated flutter tests, and flutter customer code. So I'd like a try-bot (existing or new) to check these things:

Perhaps just the various code tested here: https://github.com/flutter/tests/tree/master/registry

If adding (some or all of) these tests would slow down flutter-analyze, we could do a new, opt-in try-bot, or rely on HHH?

**Comment by srawlins** [comment]
CC @jason-simmons @zanderso @devoncarew

**Comment by pq** [comment]
Yes, please!

**Comment by srawlins** [comment]
I forgot to mention the other recent issue on this topic: https://github.com/dart-lang/sdk/issues/44811

**Comment by devoncarew** [comment]
I think a good set of repos we'd want to have try-bot capability for could be:

- flutter/flutter
- flutter/engine
- flutter/plugins
- flutter/packages

and, we'd like some analysis awareness of flutter/tests, though the analysis there will likely be more lenient. The goal would be to catch API breakages in user contributed tests, not to fail when there are minor analysis fixes upstream in dart. So think analysis errors, not analysis info level items (or, verifying that there aren't any issues caught by flutter_lints/flutter.yaml, or some other similar mechanism).

**Comment by devoncarew** [comment]
cc @Hixie @goderbauer as I discussed some of the above with them today

**Comment by goderbauer** [comment]
@devoncarew What I forgot to mention in our brief chat yesterday: We also analyze the samples embedded in our API docs with this script here on our CI: https://github.com/flutter/flutter/blob/master/dev/bots/analyze_sample_code.dart

If it's not already happening, that may be worthwhile to run on the try bots as well to avoid breakages caused by the samples.

**Comment by srawlins** [comment]
@devoncarew I think you finished this recently?

**Comment by devoncarew** [comment]
Mostly. We now check flutter/plugins and the flutter/flutter generated code. We've relaxed the restrictions so we won't generally fail on flutter customer code. We don't check flutter/cocoon. I think this can be closed; I'm not 100% sold on analyzing flutter/cocoon, but I suppose we could add it to one of the scripts if we wanted to.
