### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by wael93** [dart-lang/sdk#46068]
## Version information

- `IDEA AI-202.7660.26.42.7322048`
- `2.13.0`
- `AI-202.7660.26.42.7322048, JRE 11.0.8+0-b944-P17168821x64 JetBrains s.r.o, OS Linux(amd64) v5.8.0-50-generic, screens 1920x1080`

**Comment by srawlins** [comment]
Please re-open with details, errors, and/or stack traces if you continue to see this problem.
