### ISSUE TITLE
Failures on [vm] Enable new kernel AST invocation nodes for the VM, take 2...[vm, compiler] Remove compaction of canonical type tables from precompiler.

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#46088]
There are new test failures on [[vm] Enable new kernel AST invocation nodes for the VM, take 2...[vm, compiler] Remove compaction of canonical type tables from precompiler.](https://github.com/dart-lang/sdk/compare/dfcb88f4c9a41685958987a70ea9f548702e1c4c~...88021fd67a668180609fffb2daabcee6053741ef).

The tests
```
pkg/front_end/test/test_generator_test Timeout (expected Pass)
```
are failing on configurations
```
cfe-unittest-asserts-release-win
```

**Comment by johnniwinther** [comment]
cc @jensjoha
