### ISSUE TITLE
The `dart analyze` tool doesn't work on stand-alone scripts.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#46109]
Given the plan to discontinue the stand-alone `dartanalyzer` command (https://github.com/dart-lang/sdk/issues/46100), the `dart analyze` command should have feature parity before that happens.

It's currently not possible to analyze a stand-alone file using `dart analyze`. For a random file I had lying around:
```
> dart analyze mirext.dart
Directory doesn't exist: mirext.dart

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options.
```
vs
```
> dartanalyzer mirext.dart
Analyzing mirext.dart...
  error - A value of type 'TypeMirror' can't be assigned to a variable of type 'ClassMirror'. - mirext.dart:12:19 - invalid_assignment
  error - A value of type 'DeclarationMirror?' can't be assigned to a variable of type 'LibraryMirror'. - mirext.dart:16:21 - invalid_assignment
2 errors found.
```

(I can do `dart analyze .`, and if the file is the only one in the directory, it works, but if it's not, it's a lot of unnecessary overhead to analyze and filter through the rest).

**Comment by bkonyi** [comment]
cc @devoncarew @bwilkerson

**Comment by bwilkerson** [comment]
That should have been addressed by https://dart-review.googlesource.com/c/sdk/+/190640. I don't know whether that CL is in the version being used.
