### ISSUE TITLE
Extension method is not allowing generic type if I didn't specify the extension name

### ISSUE THREAD

**Issue by Abdelazeem777** [dart-lang/sdk#46107]
If I write the extension with generic the compiler refuses it like the following example.

![Screenshot from 2021-05-22 13-44-38](https://user-images.githubusercontent.com/30933932/119225474-4d88b400-bb04-11eb-8362-26580524368a.png)

but if I specify the extension name the compiler accepts it.
![Screenshot from 2021-05-22 13-44-52](https://user-images.githubusercontent.com/30933932/119225477-4eb9e100-bb04-11eb-94e7-c8327f34ea51.png)

**Comment by lrhn** [comment]
Behavior is correct. You need to *declare* the `T` variable before you can use it in the `on` type.
For an unnamed (library local) extension, you can do that as:
```dart
extension <T> on Iterable<T> { 
  ...
}
```
A non-generic unnamed (library-local) extension could be:
```dart
extension on Iterable<int> { 
  ...
}
```
So, the syntax where you remove `MyIterable<T>` is *valid* (you can omit a name for an extension if you want to, and you can omit a type parameter if the extension is not generic), but you then fail to declare the `T` that is later used in `Iterable<T>`, which means that `T` there does not refer to a type,.

That's what the error says, and it's correct.
