### ISSUE TITLE
[proposal] [linux] replace "apt-key" with "gpg"

### ISSUE THREAD

**Issue by iapicca** [dart-lang/sdk#46104]
in ubuntu 21.04
following the installation steps for linux in [install-using-apt-get](https://dart.dev/get-dart#install-using-apt-get)
specifically running the command
`sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'`
 outputs 
```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```
with a quick search  I found this [article](https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html) and this [askubuntu answer](https://askubuntu.com/a/1307181/1031965) on the topic

maybe is worth considering switching to [gpg](https://gnupg.org/)

**Comment by parlough** [comment]
Thanks for opening the issue!

These docs were updated last year to the non-deprecated `gpg` mechanism in https://github.com/dart-lang/site-www/commit/71c6326ad3530cabbf7f90da6a4f9d62d051e228 and https://github.com/dart-lang/site-www/commit/2e06f6a07f43e1875f9819f6c9cc63db91b115f0.
