### ISSUE TITLE
Dart VM 2.13.0 core dump

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#46112]
There is no FFI or anything special involved, just plain Dart code. 

To reproduce:

```bash
git clone https://github.com/renggli/dart-more.git
cd dart-more
git checkout e7b512b
pub get
dart test --platform=vm test/collection_test.dart
```

This crashes on `Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "macos_x64"` with `llegal instruction: 4`.

And on `Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "linux_x64"` with `egmentation fault (core dumped)`.

The same tests passed with (various) previous versions of the Dart VM, and work fine with the JS compiler.

The culprit seems to be around [these typed method/constructor calls](https://github.com/renggli/dart-more/blob/e7b512bb496b666103822c5c8efa9d769562bf03/test/collection_test.dart#L2403), but I couldn't manage to reproduce it in a more minimal setup. Not sure how to debug further?

**Comment by renggli** [comment]
Interestingly the problem only seem to happen with `dart test test/collection_test.dart`, everything works fine when running the tests with `dart run test/collection_test.dart`.

**Comment by a-siva** [comment]
Are there any license restrictions for the source code example you provide above. Would it be possible to extract a reproduction into a simpler test case so we can work on investigating it without having to pull your entire project which might have licensing restrictions.

**Comment by renggli** [comment]
This is the MIT licensed code of https://pub.dev/packages/more. 

I tied to build a minimally reproducible example, but I gave up after hours. The problem is mostly that the crash doesn't give any indication of what is wrong. I think it is triggered by the [mentioned line](https://github.com/renggli/dart-more/blob/e7b512bb496b666103822c5c8efa9d769562bf03/test/collection_test.dart#L2403) (found by commenting everything else in the test), but I was unable to reproduce it in an empty file that doesn't depend on the code of the library.

**Comment by renggli** [comment]
I found a way how I can avoid the segmentation fault from happening: https://github.com/renggli/dart-more/commit/8b2a5492ea438f3d9a096eea379daac3c3025e53. The change moves the the method that generates the test-cases out of the test-group to the top-level of the file.

**Comment by asashour** [comment]
This is not reproducible with `Dart SDK version: 2.19.0-388.0.dev (dev) (Thu Nov 10 10:03:56 2022 -0800) on "windows_x64"`

**Comment by a-siva** [comment]
@asashour thanks for letting us know about this.
@renggli is moving to the 2.19.0 version an option for you ?

**Comment by renggli** [comment]
Yes, the problem seems to only occur in 2.13 and I can no longer reproduce in any of the newer version (>=2.14.0). As a [workaround](https://github.com/dart-lang/sdk/issues/46112#issuecomment-864567822) in the meantime I've moved the method to the top-level of the file.

Thank you for fixing this.
