### ISSUE TITLE
why List source file in core is list.dart, but in patch is array_patch

### ISSUE THREAD

**Issue by inkalsee2** [dart-lang/sdk#46115]
why List source file in core is list.dart, but in patch is array.dart and array_patch.dart

**Comment by a-siva** [comment]
The actual implementation for lists by the different runtimes (dart2js, ddc, dart VM) etc. are captured in the patch files and the runtimes use file names which seem appropriate for the runtime's implementation. For instance
dart2js implements list in core_patch.dart
dart VM implements list using the internal array data structure implementation in the VM and hence uses array.dart
