### ISSUE TITLE
how to use optional named parameters in NULL SAFETY?

### ISSUE THREAD

**Issue by kamleshwebtech** [dart-lang/sdk#46128]
Case optional named parameters - I am using dart class in flutter and code is as: 

```dart
class MyDataObject {
  final int anInt;
  final String aString;
  final double aDouble;

  MyDataObject({
     this.anInt = 1,
     this.aString = 'Old!',
     this.aDouble = 2.0,
  });
} 
```

getting error that need to 'Add required keyword' before this.anInt = 1, this.aString = 'Old!' and this.aDouble = 2.0, Kindly suggest what is the issue and how can we fix it. Thanks.

**Comment by vsmenon** [comment]
Closing as we cannot repro - please file a new issue if you're still seeing issues.
