### ISSUE TITLE
TSAN DartAPI_New failure

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#46126]
https://dart-ci.appspot.com/log/vm-kernel-tsan-linux-release-x64/dartk-tsan-linux-release-x64/1665/vm/cc/DartAPI_New

```
--- Command "run_vm_unittest" (took 10.000242s):
DART_CONFIGURATION=ReleaseTSANX64 out/ReleaseTSANX64/run_vm_tests --dfe=/b/s/w/ir/out/ReleaseTSANX64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags DartAPI_New

exit code:
255

stdout:
Running test: DartAPI_New
Done: DartAPI_New

stderr:
../../runtime/vm/dart_api_impl_test.cc: 5666: error: expected 'type' to be a valid handle but found an error handle:
    'Compilation failed /test-lib:15:35: Error: The constructor function type 'MyClass Function(dynamic)' isn't a subtype of 'MyExtraHop Function(dynamic)'.
 - 'MyClass' is from '/test-lib'.
 - 'MyExtraHop' is from '/test-lib'.
  factory MyExtraHop.hop(value) = MyClass.named;
                                  ^
/test-lib:19:38: Error: The constructor function type 'MyExtraHop Function(dynamic)' isn't a subtype of 'MyInterface Function(dynamic)'.
 - 'MyExtraHop' is from '/test-lib'.
 - 'MyInterface' is from '/test-lib'.
  factory MyInterface.named(value) = MyExtraHop.hop;
                                     ^
/test-lib:20:41: Error: The constructor function type 'MyClass Function(dynamic)' isn't a subtype of 'MyInterface Function(dynamic)'.
 - 'MyClass' is from '/test-lib'.
 - 'MyInterface' is from '/test-lib'.
  factory MyInterface.multiply(value) = MyClass.multiply;

[...]


--- Re-run this test:
python3 tools/test.py -n dartk-tsan-linux-release-x64 vm/cc/DartAPI_New
```

Commit range [[dart2js] Migrate Setlet to NNBD...Remove a few tests from the bottom of checker_test](https://github.com/dart-lang/sdk/compare/95daf6a38362989c7d3025d09ed11fb0a26c7695~...367acf4492471968c54de29a3455545cbeed4da3).

Suspect commit would be https://github.com/dart-lang/sdk/commit/89996356b58566264d7411ab15b2dec47ca7997d, it is the only VM change (cc @crelier).

However, it does not fail on any of the other bots, only the TSAN bot.

Started happening at the same time as https://github.com/dart-lang/sdk/issues/46121#issuecomment-847695402.

**Comment by a-siva** [comment]
This test has been failing in all the configurations and we have an issue tracking this already (https://github.com/dart-lang/sdk/issues/33041). It is possible in TSAN mode we were seeing some flaky crashes which got fixed and now we consistently get runtime errors.
