### ISSUE TITLE
Dart migrate exception 

### ISSUE THREAD

**Issue by ibrahim-demirci** [dart-lang/sdk#46122]
ı run "dart migrate command " and got this exception. 

PS C:\flutter_projeleri\container_coordinates> dart migrate
Migrating C:\flutter_projeleri\container_coordinates

See https://dart.dev/go/null-safety-migration for a migration guide.

[exception: FileSystemException(path=C:\Program Files\Dart\dart-sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:184:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:473:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:371:18)
#3      ContextBuilder.findSdk.<anonymous closure> (package:analyzer/src/context/builder.dart:209:16)
#4      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:140:29)
#5      DartSdkManager.getSdk (package:analyzer/src/generated/sdk.dart:95:19)
#6      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:208:30)
#7      ContextBuilder.createSourceFactoryFromWorkspace (package:analyzer/src/context/builder.dart:178:19)
#8      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:119:9)
#9      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:98:37)
#10     new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:65:36)
#11     MigrationCliRunner.contextCollection (package:nnbd_migration/migration_cli.dart:542:28)
#12     MigrationCliRunner.hasMultipleAnalysisContext (package:nnbd_migration/migration_cli.dart:551:12)
#13     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:701:9)
#14     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:72)
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
#16     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:30)
#17     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#18     new Future.sync (dart:async/future.dart:218:31)
#19     CommandRunner.run (package:args/command_runner.dart:112:14)
#20     runDartdev (package:dartdev/dartdev.dart:53:29)
#21     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:9)
#22     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:279:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
]
[exception: FileSystemException(path=C:\Program Files\Dart\dart-sdk\lib\_internal\libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:184:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:473:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:371:18)
#3      ContextBuilder.findSdk.<anonymous closure> (package:analyzer/src/context/builder.dart:209:16)
#4      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:140:29)
#5      DartSdkManager.getSdk (package:analyzer/src/generated/sdk.dart:95:19)
#6      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:208:30)
#7      ContextBuilder.createSourceFactoryFromWorkspace (package:analyzer/src/context/builder.dart:178:19)
#8      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:119:9)
#9      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:98:37)
#10     new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:65:36)
#11     MigrationCliRunner.contextCollection (package:nnbd_migration/migration_cli.dart:542:28)
#12     MigrationCliRunner.hasMultipleAnalysisContext (package:nnbd_migration/migration_cli.dart:551:12)
#13     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:701:9)
#14     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:72)
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
#16     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:30)
#17     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#18     new Future.sync (dart:async/future.dart:218:31)
#19     CommandRunner.run (package:args/command_runner.dart:112:14)
#20     runDartdev (package:dartdev/dartdev.dart:53:29)
#21     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:9)
#22     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:279:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
]
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:184:7)
#1      FolderBasedDartSdk.languageVersion (package:analyzer/src/dart/sdk/sdk.dart:395:12)
#2      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:231:40)
#3      ContextBuilder.createSourceFactoryFromWorkspace (package:analyzer/src/context/builder.dart:178:19)
#5      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:98:37)
#6      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:65:36)
#7      MigrationCliRunner.contextCollection (package:nnbd_migration/migration_cli.dart:542:28)
#8      MigrationCliRunner.hasMultipleAnalysisContext (package:nnbd_migration/migration_cli.dart:551:12)
#9      MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:701:9)
#10     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:72)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
#12     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:30)
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#14     new Future.sync (dart:async/future.dart:218:31)
#15     CommandRunner.run (package:args/command_runner.dart:112:14)
#16     runDartdev (package:dartdev/dartdev.dart:53:29)
#17     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:9)
#18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:279:32)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

My versions :

PS C:\flutter_projeleri\container_coordinates> flutter --version
Flutter 2.2.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b22742018b (10 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
