### ISSUE TITLE
[vm/ffi] Passing structs by value from native to dart is broken on 32-bit targets

### ISSUE THREAD

**Issue by alexlapa** [dart-lang/sdk#46127]
## Summary

Having this C code:
```C
#include <stdint.h>

struct MyStruct
{
    uint64_t val;
};

struct MyStruct create_my_struct()
{
    struct MyStruct myStruct;
    myStruct.val = 123;
    return myStruct;
}

```

and this Dart code:

```Dart
import 'dart:ffi';

final nativeLib = DynamicLibrary.open('./libstruct.so');

class MyStruct extends Struct {
  @Uint64()
  external int val;
}

main() {
  final struct = nativeLib.lookupFunction<
      MyStruct Function(),
      MyStruct Function()>('create_my_struct')();
  print('MyStruct.val = ${struct.val}');
}

```

Runing Dart on i686 target would return ~random results:
```
MyStruct.val = 4097305856
...
MyStruct.val = 4097830144
...
MyStruct.val = 4097305856
```

MRE: https://github.com/alexlapa/dart-ffi-i686-return-struct-by-value-bug

## More background

Initially i've encountered this issue with Rust + Flutter in `i686-linux-android` android emulator, `x86_64-linux-android` works fine. Some additional debugging on i686 ubuntu xenial in virtualbox showed that this issue can be reproduced in this environment.

My reproduction uses stable `2.13` dart + `6.0.0` clang, however this was also tested on `2.14.0-119.0.dev` dart + `3.8.0 clang with same results.

Integers of all sizes are affected. Double works fine, float doesn't.

**Comment by Hardebayho** [comment]
I've experienced this too... In my case, it's float gives correct results and integers are the problem

By the way, my platform was Android (armeabi-v7a)

**Comment by a-siva** [comment]
//cc @dcharkes

**Comment by dcharkes** [comment]
Thanks for reporting @alexlapa! This reproduces on Linux ia32.

Fix underway: https://dart-review.googlesource.com/c/sdk/+/201269 (See description for an explanation of the bug if you're interested).

@Hardebayho it does not reproduce on Arm v7a. Are you sure you're seeing this issue on a hardware device? The Android simulators run ia32 (also known as x86 or i686), not Arm v7a.
