### ISSUE TITLE
analyzer / meta cross dependencies result in compilation errors since analyzer 1.6.0 was published

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#46136]
The resulting errors look like this:

```
../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:1600:40: Error: Getter not found: 'topLevelVariable'.
      return kinds.contains(TargetKind.topLevelVariable);
                                       ^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Getter not found: 'topLevelVariable'.
      case TargetKind.topLevelVariable:
                      ^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Type 'dynamic' of the case expression is not a subtype of type 'TargetKind' of this switch expression.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('../../.pub-cache/hosted/pub.dartlang.org/meta-1.3.0/lib/meta_meta.dart').
      case TargetKind.topLevelVariable:
                      ^
../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2001:13: Context: The switch expression is here.
    switch (this) {
            ^
```

The problem seems to be that no version of `package:meta` exists that has the interface the new analyzer expects.

A version of `package:meta` must be published to correct this and another version of `package:analyzer` should be released that requires that version of `package:meta`.

Marking P0 as the impact seems to be pretty broad:  any package with an open constraint on analyzer that allows 1.6.0 is potentially impacted.

**Comment by scheglov** [comment]
Apparently 1bfa8610d118ec14136f679b3e14c96f1684204d updated `package:meta`, and changes `package:analyzer` to implicitly require these changes without the corresponding change to the dependencies. I will publish new `package:meta` and re-publish `package:analyzer` as `1.7.0`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/201343 to publish `package:meta`.

**Comment by shaynekellyii** [comment]
Do you have any estimate on when this will be resolved?

**Comment by scheglov** [comment]
Once https://dart-review.googlesource.com/c/sdk/+/201344 is LGTMed, I will publish.

**Comment by scheglov** [comment]
`package:meta 1.4.0` was published.

**Comment by scheglov** [comment]
`package:analyzer` looks compile-time errors free and passes tests with `pub downgrade`.
So, I'm going to publish it.

**Comment by scheglov** [comment]
`package:analyzer 1.7.0` was published.

**Comment by gspencergoog** [comment]
Does 1.6.0 need to be marked as a bad version?

**Comment by scheglov** [comment]
It does, but [can](https://github.com/dart-lang/pub-dev/issues/378) we?

**Comment by jcollins-g** [comment]
Reopening issue.  Unfortunately the proposed fix (publishing meta 1.4.0) does not solve the issue for Flutter users.   This is because Flutter pins meta to 1.3.0, forcing pub resolution to 1.6.0 for analyzer.

**Comment by scheglov** [comment]
There are two possible solutions:
1. Somehow remove `analyzer 1.6.0` from `Pub` (I cannot do this).
2. Revert changes that required unpublished `meta 1.4.0` changes, and publish `analyzer 1.8.0` that depends on `meta 1.3.0`.

I will revert 1bfa8610d118ec14136f679b3e14c96f1684204d and aa30fc88258f7ee833da4543ca95690f16e99720.

**Comment by jcollins-g** [comment]
Flutter users with this problem should temporarily use dependency overrides as suggested here:  https://github.com/dart-lang/sdk/issues/46142#issuecomment-848631599

**Comment by devoncarew** [comment]
Note that an ability like https://github.com/dart-lang/pub-dev/issues/378 would really help here.

**Comment by jakemac53** [comment]
The change you have pending @scheglov should work, and that is the only available fix to us afaik.

You should be safe to re-land the changes in a future version which requires the latest meta.

**Comment by scheglov** [comment]
`analyzer 1.7.1` was published.

**Comment by jcollins-g** [comment]
Yep, the workaround above should no longer be necessary:  `pub upgrade` should now give you analyzer version 1.7.1 when using Flutter.

**Comment by flutterfromscratch** [comment]
Considering that this broke `build_runner` for everybody using Flutter yesterday, do you guys have an internal process to discuss how to avoid these things from happening in the future? I love using Flutter and I think it's amazing, but there have been a couple of these "oops" package pushes which have wound up throwing nonsensical error messages and prevented me from coding for that day. I've not experienced something similar with any other library or framework within recallable memory.
