### ISSUE TITLE
dart migrate throw "$async.Future isn't a type at lib\generated\appService.pbgrpc.dart:49:3 • (not_a_type)"

### ISSUE THREAD

**Issue by boldt** [dart-lang/sdk#46131]
## System

* Windows 10
* Flutter 2.2.0
* Dart 2.13.0
* grpc 3.0.0

## Issue

We're trying to migrate a small library using the [grpc:3.0.0](https://pub.dev/packages/grpc) to null-safety. Running `dart migrate` throws plenty of the the following error:

```
  error • Future isn't a type at lib\app.dart:147:3 • (not_a_type)
  error • $async.Future isn't a type at lib\generated\appService.pbgrpc.dart:49:3 • (not_a_type)
```
## Note

I files this issue alreade at the grpc library: https://github.com/grpc/grpc-dart/issues/475. They send me here.

**Comment by boldt** [comment]
Since this only happens with the generated code, we run the following command to migarte the app:

```
dart migrate --ignore-errors
```

The issue still needs to be solved.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
