### ISSUE TITLE
Support connecting to abstract unix sockets created by other processes

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#46149]
In an abstract unix socket address, all bytes of the `sun_path` field are significant. `connect()` etc. calls can be told to consider fewer bytes by passing a shorter length for the address. However, in the Dart implementation, the length is always passed as the full size of the address struct. This means that if a C or Python program is listening for connections on abstract address `\0mysocket`, and the address on the Dart side is `@mysocket`, Dart will try to connect to address `\0mysocket\0\0\0\0...`, which does not exist.

This is needed for dbus connections on Linux desktop for e.g. desktop notifications where the dbus session is listening on an abstract unix socket.

I've started a small fix here https://dart-review.googlesource.com/c/sdk/+/201441.

/cc @aam @a-siva @cbracken @robert-ancell @csells

**Comment by robert-ancell** [comment]
The Unix Socket API is a magical thing :)

**Comment by aam** [comment]
So does the Dart do the right thing now passing full name with trailing zeros?
Is the issue actually with the Python and C implementations that truncate the name by the first zero?
Is there an example that demonstrates the existing problem?

**Comment by zanderso** [comment]
It's a legal use of the API for a server to specify an address without trailing null bytes. This is currently the case for the dbus session address on my Linux system: `DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-kjujx1ykZP,guid=...`.

Right now it's impossible for Dart to connect to that address because if you specify address `@/tmp/dbus-kjujx1ykZP` from the Dart API, it will translate that into `\0/tmp/dbus-kjujx1ykZP\0\0\0\0\0\0...`, which is a different address.

**Comment by aam** [comment]
Yes, got you. So socket address name that dart is attempting to connect to in `ServerSocket::CreateUnixDomainBindListen` is always a fixed length name regardless of what dart user code specified.
Sounds like there were no real users of unix domain sockets until now.
