### ISSUE TITLE
Analyzer 1.6.0 on Dart 2.13.0 fail to precompile: Getter not found: 'topLevelVariable'. Type 'dynamic' of the case expression is not a subtype of type 'TargetKind' of this switch expression.

### ISSUE THREAD

**Issue by artnavsegda** [dart-lang/sdk#46142]
Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "macos_x64"

Failed to precompile build_runner:build_runner:
/opt/homebrew/Caskroom/flutter/2.2.0/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:1600:40: Error: Getter not found: 'topLevelVariable'.
      return kinds.contains(TargetKind.topLevelVariable);
                                       ^^^^^^^^^^^^^^^^
/opt/homebrew/Caskroom/flutter/2.2.0/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Getter not found: 'topLevelVariable'.
      case TargetKind.topLevelVariable:
                      ^^^^^^^^^^^^^^^^
/opt/homebrew/Caskroom/flutter/2.2.0/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Type 'dynamic' of the case expression is not a subtype of type 'TargetKind' of this switch expression.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('/opt/homebrew/Caskroom/flutter/2.2.0/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0/lib/meta_meta.dart').
      case TargetKind.topLevelVariable:
                      ^
/opt/homebrew/Caskroom/flutter/2.2.0/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2001:13: Context: The switch expression is here.
    switch (this) {
            ^
pub finished with exit code 1

**Comment by arnoutvandervorst** [comment]
Same, started happening after upgrading to build_runner 2.0.4 and analyser 1.6.0

**Comment by kluverua** [comment]
*for forced use of a specific version of the **analyzer**, you can add this block to **pubspec.yaml**
```
dependency_overrides:
  analyzer: '1.5.0'

```

**Comment by vsmenon** [comment]
@pq - perhaps a versioning issue with your recent change - https://dart-review.googlesource.com/c/sdk/+/200900 ?

**Comment by pq** [comment]
@vsmenon: quite right.  `1.6.0` has a dependency on a change to  a newer `package:meta`.  I was out yesterday but it looks like there was a scramble to address this by @scheglov, @jcollins-g, @bwilkerson and others and I believe we're out of the woods with analyzer `1.7.0`.   There's also been some conversation about what we can do to harden the CI/release process to avoid this kind of issue in the future.  Not sure there's resolution yet.  (If there are open issues, maybe someone could link here?)

/fyi @devoncarew 


Sorry for the inconvenience @artnavsegda !

**Comment by jcollins-g** [comment]
@flutterfromscratch  Eeeep.  pubspec.yaml in Flutter pins meta to a specific version (1.3.0), forcing any package that uses Flutter and analyzer (even indirectly, e.g. through package test or build_runner) to prefer analyzer 1.6.0.

Reopened https://github.com/dart-lang/sdk/issues/46136 and closing this as duplicate.

**Comment by devoncarew** [comment]
cc @jakemac53 as I know he's thought about flutter package pinning and the implications. I hadn't realized that it means that a flutter stable release (pinning meta) will effectively also pin the analyzer version, and transitively all build related packages.

**Comment by jakemac53** [comment]
Oh right 🤕 ... ya this is very problematic for this case in particular. Flutter users can override `meta` to the latest but that isn't a good solution.
