### ISSUE TITLE
Implement checks on @visibleForOverriding

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#46155]
Analyzer does not have any checks for `@visibleForOverriding` indicated in the docs: https://pub.dev/documentation/meta/latest/meta/visibleForOverriding-constant.html

It should.

**Comment by simolus3** [comment]
I've opened https://dart-review.googlesource.com/c/sdk/+/202620 to fix this.

**Comment by simolus3** [comment]
This should probably be re-opened now.

Also, can you help me understand the correct behavior when this annotation is used on constructors? Does it mean that the constructor should only be called from subclasses? How is the annotation different from `@protected` in that case?

**Comment by bwilkerson** [comment]
I don't _know_ that we ought to support putting this annotation on constructors, I was just noting that it's being used that way in practice and that it might warrant having a discussion. You question about `@protected` is valid, though it's also documented as applying to an "instance member". Still, it might be better to extend the definition of `@protected` than `@visibleForOverriding`. In any case we'll need to fix at least some of the uses of the annotation before we can land your CL.
