### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "C:\Users\micro\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\_fe_analyzer_shared-22.0.0".

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#46157]
I'm not sure if I'm in the right tracker or not.

Until recently `dart pub run test` worked.  I'm using:

```
[√] Flutter (Channel master, 2.3.0-13.0.pre.187, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.3.0-13.0.pre.187 at C:\Users\micro\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a96e763155 (6 minutes ago), 2021-05-26 23:14:02 -0400
    • Engine revision a832502eaf
    • Dart version 2.14.0 (build 2.14.0-153.0.dev)
```
But now it fails:
```
PS C:\Users\micro\Documents\GitHub\dash_craft> dart pub run test
Deprecated. Use `dart run instead`
Could not find a file named "pubspec.yaml" in "C:\Users\micro\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\_fe_analyzer_shared-22.0.0".
```

Did symlinking break on windows?  Did something break in the latest analyzer package?  Not sure.

* Dart SDK Version (`dart --version`)
```
Dart SDK version: 2.14.0-153.0.dev (dev) (Tue May 25 19:09:39 2021 -0700) on "windows_x64"
```

**Comment by eseidel** [comment]
Running in another project of mine (where I know this has worked previously) I get:

```
PS C:\Users\micro\Documents\GitHub\cauldron_quest> dart pub run test
Deprecated. Use `dart run instead`
Precompiling executable...
Failed to precompile test:test:
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-1.3.0/lib/src/error/best_practices_verifier.dart:1973:14: Error: A non-null value must be returned since the return type 'String' doesn't allow null.
  String get displayString {
             ^
```

**Comment by eseidel** [comment]
Hmm, if I `dart pub upgrade` in that cauldron_quest project it then works.  Perhaps this is user error.  Investigating.

**Comment by eseidel** [comment]
Yeah, `dart pub upgrade` fixed it in my original repo too.  Not sure at all what went wrong.  Glad it's fixed.  Maybe this should just be closed then?

Leaving open in case this is useful, feel free to close.

**Comment by vsmenon** [comment]
I think you got caught up in transient state related to https://github.com/dart-lang/sdk/issues/46136

**Comment by vsmenon** [comment]
Closing here.  Main discussion https://github.com/dart-lang/pub-dev/issues/378
