### ISSUE TITLE
type '(String, StringBuffer) => Null' is not a subtype of type 'Object' of 'value'

### ISSUE THREAD

**Issue by SteveAlexander** [dart-lang/sdk#46165]
Using Dart on Flutter's master, dev, beta, or stable channels, running in the VM on Android, the following code incorrectly throws a TypeError:

```dart
  final l = <Object>[];
  l.add((String x, StringBuffer y) {
    print(x);
  });
```

I reproduced this on an Android Pixel emulator, using Flutter, inserting the above code in the `main()` entry-point.

The code does not throw an error running on iOS or on MacOS.

```
E/flutter ( 6922): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type '(String, StringBuffer) => Null' is not a subtype of type 'Object' of 'value'
E/flutter ( 6922): #0      List.add (dart:core-patch/growable_array.dart)
E/flutter ( 6922): #1      main
package:saml2/main.dart:58
E/flutter ( 6922): #2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 6922): #3      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 6922): #4      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 6922): #5      _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 6922): #6      runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 6922): #7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 6922): #8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 6922): #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by lrhn** [comment]
Reproduces on 2.13.1. Does not appear to affect dart2js, only VM.

**Comment by SteveAlexander** [comment]
Changing `<Object>[]` to `<Object?>[]` or `<dynamic>[]` avoids the error. Perhaps this helps narrow down the relevant code?

**Comment by SteveAlexander** [comment]
Also... I was confused by the error message `is not a subtype of type 'Object' of 'value'`

What does the `of 'value'` part mean?

**Comment by lrhn** [comment]
The error likely comes from inside the `add` method, where it checks that the argument for the `value` parameter has the required type. Since Dart generics are covariant, methods like `void add(E value)` need to check their arguments at run-time, because the receiver object, of type `List<Object>` might have been used with a static type of `List<Object?>`. Passing `null` as argument to `add` in that case must be caught at run-time, because the static type system allows it.
That run-time check seems to fail here, for no good reason (a function *is an* `Object`).

**Comment by crelier** [comment]
Thanks for the report and the repro. I am surprised that this simple bug remained undetected until now.
CL under review: https://dart-review.googlesource.com/c/sdk/+/201863
