### ISSUE TITLE
Float32x4 component accessors are missing recognized lowerings

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#46176]
Accessing a component always involves a runtime call and boxing. 

Float64x2 accessors are optimized on the other hand.

**Comment by gmpassos** [comment]
I have an ANN package that uses SIMD to compute:

https://pub.dev/packages/eneural_net

It's very clear that SIMD performance is lowered when accessing Float32x4 fields (x,y,x,w).

I'm even holding a 'exp' function implementation using SIMD approaches, but the performance is actually reduced if compared with a normal computation.

**Comment by alexmarkov** [comment]
FWIW Float32x4 get:x, get:y, get:z and get:w are recognized and handled in the same switch in the inliner as Float64x2 accessors:

https://github.com/dart-lang/sdk/blob/822140714da5842482f55bbb6f22325480019c8f/runtime/vm/compiler/recognized_methods_list.h#L335-L338

https://github.com/dart-lang/sdk/blob/822140714da5842482f55bbb6f22325480019c8f/runtime/vm/compiler/backend/inliner.cc#L3940-L3943

(Unlikely to Float64x2GetX/Float64x2GetY they're called Float32x4ShuffleX-Float32x4ShuffleW.)

The following small example also shows that they are inlined and intrinsified:
```dart
import 'dart:typed_data';

var values = [Float32x4(1, 2, 3, 4)];

void main() {
  final v = values[0];
  print(v.x + v.y + v.z + v.w);
}
```
```
 18:     v53 <- Unbox:16(v58) T{_Float32x4}
 20:     ParallelMove xmm1 <- xmm0
 20:     v29 <- SimdOp:16(Float32x4ShuffleX, v53) T{_Double}
 22:     ParallelMove xmm2 <- xmm0
 22:     v31 <- SimdOp:18(Float32x4ShuffleY, v53) T{_Double}
 24:     ParallelMove xmm1 <- xmm1
 24:     v11 <- BinaryDoubleOp(+, v29, v31) T{_Double}
 26:     ParallelMove xmm2 <- xmm0
 26:     v33 <- SimdOp:22(Float32x4ShuffleZ, v53) T{_Double}
 28:     ParallelMove xmm1 <- xmm1
 28:     v15 <- BinaryDoubleOp(+, v11, v33) T{_Double}
 30:     ParallelMove xmm0 <- xmm0
 30:     v35 <- SimdOp:26(Float32x4ShuffleW, v53) T{_Double}
 32:     ParallelMove xmm1 <- xmm1
 32:     v19 <- BinaryDoubleOp(+, v15, v35) T{_Double}
 34:     v55 <- Box(v19) T{_Double}
```

There are also graph intrinsics for Float32x4 accessors in addition to inliner support.

**Comment by mraleph** [comment]
Thanks, Alex! I guess I somehow managed to overlook this.
