### ISSUE TITLE
[CP][stable channel] Merge a3767f7db86a85fcd6201e9357ad47b884002b66 to stable channel (2.13)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#46173]
**commit(s) to merge**: a3767f7db86a85fcd6201e9357ad47b884002b66

**merge instructions**: clean merge

**What is the issue**: Flutter AOT precompiler crashes (https://github.com/flutter/flutter/issues/83094)

**What is the fix**:  Generate non-speculative Unbox instructions for Phis

**Why cherrypick**: This crash was reported by a Flutter user and it is possible other Flutter users may also run into this crash. When such a crash is reported it is not obvious the crash is because of this issue and we would spend additional engineering cycles investigating the crash and narrow it down to this cause.

**Risk**: The change has landed in master and is in the process of being rolled into Flutter. We should wait for it to be rolled fully which I hope will happen over the weekend.

**Link to original  issue(s)**:  https://github.com/flutter/flutter/issues/83094

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @alexmarkov

**Comment by franklinyow** [comment]
CC @kf6gpe

**Comment by franklinyow** [comment]
@alexmarkov @mraleph 
The original issue flutter/flutter#83094 is still open.  
Can you give an update on the roll progress?

**Comment by kf6gpe** [comment]
I don't think this made the last cherrypick window. @christopherfujino can you confirm?

If not, let's keep this in mind for the next hotfix release. There's not one scheduled, but I could see taking this if we get enough to proceed.

**Comment by franklinyow** [comment]
@kf6gpe We have not approved this pick.  So this won't be in the last cherrypick window.

**Comment by kf6gpe** [comment]
Got it. I'll wait until it's approved and then add it to the list. Thanks!

**Comment by franklinyow** [comment]
Description:
Fix an crashing issue in Flutter precompiler  , see flutter/flutter#83094 for detail

**Comment by athomas** [comment]
Merged to stable in 516eb3b05c252ef3d34255d06700c1f09f7f4502 (2.13.3).
