### ISSUE TITLE
Uint64List.fromList does not turn the int elements into uint64 values

### ISSUE THREAD

**Issue by kjeremy** [dart-lang/sdk#46188]
In attempting to send 2 uint64 values (505 and 0) through a `Socket` I expected the following code to work:

```dart
var message = Uint64List.fromList([505, 0]);
socket.add(message.buffer.asUint8List());
```

It does not. However the following does:

```dart
var message = Uint64List(2);
var bytedata = ByteData.view(message.buffer);
bytedata.setUint64(0, 505);
bytedata.setUint64(8, 0);
socket.add(message.buffer.asUint8List());
```

I don't see anything in the documentation that would suggest why the first version wouldn't work. It is certainly the more natural way to write this.

Similarly for retrieving data from a socket this does not work:

```dart
await for (Uint8List data in socket) {
      final topicAndPayloadSize =
          Uint64List.sublistView(data, 0, 2 * Uint64List.bytesPerElement);
      final topicId = topicAndPayloadSize[0];
      final payloadSize = topicAndPayloadSize[1];
}
```

But this does:

```dart
await for (Uint8List data in socket) {
      final byteData = data.buffer.asByteData();
      final topicId = byteData.getUint64(0);
      final payloadSize = byteData.getUint64(8);
}
```

Again this is surprising behavior. I'm not sure if this is a bug or there's something missing in the documentation that would make this more clear.

Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "windows_x64"
Android

**Comment by mraleph** [comment]
Most likely endianess issue. Note that `{get|set}Uint64` defaults to big endian (see [signature](https://api.dart.dev/stable/2.10.5/dart-typed_data/ByteData/setUint64.html)). While other operations are host endian (which means they are little endian - cause Dart does not even run natively on big endian systems at the moment). 

I'd check what kind of byte order does your server use. (Most likely so called _network order_ - which is actually big endian).

**Comment by kjeremy** [comment]
Yes that's most likely it. It would be nice if `fromList` let you specify the endianness or if it was documented that this is in host endian order.

**Comment by mraleph** [comment]
Yeah, I am a bit surprised that `dart:typed_data` does not make it clear and just implicitly assumes that the reader guessed that values are stored in memory in host order (I guess it is somewhat an obvious/implicit guess to make, but still). /cc @lrhn

**Comment by lrhn** [comment]
Generally, everything except `ByteData` uses host endian. It's slightly annoying that `ByteData` does not have a way to specify a default endianness for the object, but it would require one or two extra bits of storage to remember.
It should probably be documented explicitly everywhere.

So, in general, if endianness matters, use `ByteData` and explicitly provide an endianness to each call.
If not, use anything else, or use `ByteDate` with `Endina.host`.
