### ISSUE TITLE
PackageName package:address/packagename.dart  The library 'package:address/packagename.dart' is legacy, and should not be imported into a null safe library. Try migrating the imported library.dart(import_of_legacy_library_into_null_safe)

### ISSUE THREAD

**Issue by AzadCoder** [dart-lang/sdk#46184]
Hi, I just upgraded to Flutter 2.2 stable. But when I import every package I get this kind of warning and package not working.
In this case flutte map_box package

```mapbox_gl
package:mapbox_gl/mapbox_gl.dart

The library 'package:mapbox_gl/mapbox_gl.dart' is legacy, and should not be imported into a null safe library.
Try migrating the imported library.dart(import_of_legacy_library_into_null_safe)
```
Not problem if it was just for one package but it happens for to many packages.

**Comment by vsmenon** [comment]
What did you upgrade from?  What does your `pubspec.yaml` look like?  You may need to explicitly opt-out of null safety.  You should be able to do this by making sure your lower bound sdk constraint is `2.11.0` or lower.  Null safety became default in `2.12`.

````
environment:
  sdk: ">=2.11.0 <3.0.0"
```
