### ISSUE TITLE
Please add auto suggestions for coders who are new to dart and flutter

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/sdk#46189]
it's very difficult to know what are the properties of the given funtion...widget...and vs code not shows well the real suggestions please

**Comment by bwilkerson** [comment]
This is a tooling issue, not a language issue, so I moved the issue to the sdk repository.

Our completion support ought to provide all of the valid options. For example given the code
```
void f(String s) {
  s.
}
```
if you request completions after the period they ought to include all of the methods (including getters and setters) that are visible on the class `String`. If you're not seeing this, could you please provide at least one concrete example of code in which completions are not being suggested as expected?

**Comment by fisforfaheem** [comment]
suppose u want to add an widget... say a buttin widget... when we press ctrl+space  it should first show the possible properties in suggestions etc

**Comment by bwilkerson** [comment]
Could you provide me with a small piece of sample code in which you're not seeing the suggestions you're expecting to see? It's hard to fix issues unless we can reproduce them, so some reproduction steps would be useful.

Also, which IDE are you using?

**Comment by fisforfaheem** [comment]
Thanks for your response. sorry i am too busy right now, BUT , i just moved
from beta sdk to master SDk now 99% issue is solved. the suggestions
somehow now show up...
[image: image.png]

**Comment by bwilkerson** [comment]
I'm glad to hear that most of the problem has been resolved. Given that, I'm going to close this issue, but when you have time please open new issues for any remaining problems you're still seeing.
