### ISSUE TITLE
Float32x4 GC mitigation needed!

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/sdk#46187]
`Float32x4` and `Int32x4` brings SIMD acceleration, replacing use of normal numbers (double & int) to a lane of 4 numbers.

One side effect of `Float32x4` and `Int32x4` is the increase of objects to be handled by GC.

Some strategy in the VM implementation of `Float32x4` and `Int32x4` is needed to reduce GC work. It seems that other
types, like`String`, have a better performance.

**Comment by mraleph** [comment]
@gmpassos could you provide some runnable code and instructions for us to run/benchmark/profile ourselves? 

In general most local allocations of SIMD values should be eliminated, but SIMD values still need to be boxed when passed around. It is possible to give SIMD values similar treatment as (non-nullable) `double` type - which we unbox in AOT mode in most places. However it would require language team decision on #43255 - to allow VM erase identity of SIMD values.

**Comment by gmpassos** [comment]
I have worked to show that in the last days:

https://github.com/eneural-net/eneural_net_dart/blob/master/example/eneural_net_benchmark_activation_functions.dart

**Comment by gmpassos** [comment]
@mraleph FYI: https://github.com/dart-lang/sdk/issues/47488
