### ISSUE TITLE
How to url encode + in dart ?

### ISSUE THREAD

**Issue by raphire08** [dart-lang/sdk#46193]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Dart core libraries ("dart:uri", etc.)

Dart Version - 2.13.0
on MacOS using safari

Trying to encode "+" in the url encoding using `Uri.encodeFull(someString)` is not working trying with `Uri.encodeComponent(someString)` is encoding everything "@ . "etc.

I just want to encode + sign

**Comment by vsmenon** [comment]
You will generally get much quicker responses on these sorts of questions in one of these channels:

https://dart.dev/community#join-the-conversation

The issue tracker is for bugs and feature requests.

**Comment by raphire08** [comment]
Okay

**Comment by vsmenon** [comment]
Great - if you do find that something is unsupported (or buggy) here, please do file a new issue.  Thanks!
