### ISSUE TITLE
[vm/ffi] Add DynamicLibrary.functionExists()

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#46192]
Currently, the only way to check whether a function exists in a given DL (or an already loaded library in `DynamicLibrary.Process()`) is to call `.lookup()` and catch exceptions. This doesn't work all that well when someone has "catch all exceptions" enabled, e.g. in VS Code.

Consider adding a boolean returning function to check whether a function with a given name exists. I've had a quick look at the SDK code and adding a new function based on the existing `ResolveSymbol` looks reasonably simple (`ffi_dynamic_library.cc`):

```c++
static bool SymbolExists(void* handle, const char* symbol) {
#if defined(HOST_OS_LINUX) || defined(HOST_OS_MACOS) ||                        \
    defined(HOST_OS_ANDROID) || defined(HOST_OS_FUCHSIA)
  return dlsym(handle, symbol) != nullptr;
#elif defined(HOST_OS_WINDOWS)
  return GetProcAddress(reinterpret_cast<HMODULE>(handle), symbol) != nullptr;
#else
  const Array& args = Array::Handle(Array::New(1));
  args.SetAt(0,
             String::Handle(String::New(
                 "The dart:ffi library is not available on this platform.")));
  Exceptions::ThrowByType(Exceptions::kUnsupported, args);
#endif
}
```

_Originally posted by @vaind in https://github.com/dart-lang/ffi/issues/104#issue-899609369_

This is a `dart:ffi` feature, not `package:ffi` feature, so I'm moving this issue.

**Comment by simolus3** [comment]
Is anyone working on this? Otherwise, I'm happy to help contribute this feature.

**Comment by dcharkes** [comment]
> Is anyone working on this?

No.

> Otherwise, I'm happy to help contribute this feature.

Yes, please go ahead and make a PR. 😄 
I'll review it.
