### ISSUE TITLE
Can't decode null with json.fuse(utf8).decode

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#46205]
Tested with Dart `2.12.0` and `2.14.0-166.0.dev`.

Following example doesn't work:
```dart
import 'dart:convert';

final json2utf8 = json.fuse(utf8);
final value = utf8.encode('null');

void main() => print(json2utf8.decode(value));
```
Instead I get:
```
Unhandled exception:
type 'Null' is not a subtype of type 'Object'
#0      _JsonUtf8Decoder.convert (dart:convert-patch/convert_patch.dart:78:19)
#1      Codec.decode (dart:convert/codec.dart:26:34)
#2      main (file:///source/dart-neats-clean/canonical_json/test/hack.dart:6:32)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12
```

---------------------------------------------

If using language version 2.10, then it works fine:
```dart
//@dart=2.10
import 'dart:convert';

final json2utf8 = json.fuse(utf8);
final value = utf8.encode('null');

void main() => print(json2utf8.decode(value));
// this prints: null
```

--------------------

It seems that if I create `final json2utf8 = json.fuse(utf8);` then I can use `json2utf8.encode(...)` on lists, maps, null, etc... and I can decode JSON with `json2utf8.decode(...)` unless the value encoded was `null`. Maps/lists containing `null` doesn't seem to be a problem.

The same problem appears in `Utf8Decoder().fuse(JsonDecoder())`.

**Comment by lrhn** [comment]
Looks like a null-safety migration bug.
https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/convert_patch.dart#L72
The return type should be `Object?`.
