### ISSUE TITLE
Implementation: Symbol constructor accepts arbitrary string as argument

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46207]
Cf. https://github.com/dart-lang/language/pull/1588, and noting the decision to change the `Symbol` constructor such that it accepts any string as an argument (not just the strings `s` such that `#s` is a correct symbol literal), this issue requests an implementation such that the following tests succeed:

```
tests/corelib/symbol_arbitrary_string_test.dart
tests/corelib/symbol_reserved_word_error_test.dart
tests/corelib/symbol_reserved_word_test.dart
```

Note that these changes only affect libraries using the current language (in particular, only libraries with null safety).

**Comment by jensjoha** [comment]
Am I correct in my understanding that when these tests expects errors it's a bug in the test?

python3 tools/test.py -n cfe-strong-linux corelib/symbol_test/02
python3 tools/test.py -n cfe-strong-linux corelib/symbol_test/03

basically
```
const Symbol('0');
const Symbol('_');
```
?

**Comment by eernstg** [comment]
Yes, subtests #02 and #03 should be changed to expect that compilation succeeds, and a couple of invocations of `new Symbol(...)` further down expecting an argument error shouldn't expect that any more.

**Comment by eernstg** [comment]
@jensjoha, the tests are adjusted in https://dart-review.googlesource.com/c/sdk/+/205480.

**Comment by jensjoha** [comment]
Yeah, I'm a little puzzled by not seeing any failures on symbol_operator_test though...

**Comment by eernstg** [comment]
I think that's OK: `corelib/symbol_operator_test.dart` was changed such that a number of dynamic symbols (`new Symbol(_)`) are no longer expected to throw. This means that the analyzer will (still) accept the code (it never tries to determine whether the argument `a` in `new Symbol(a)` satisfies any constraints beyond being a `String`). The CFE already implements the new semantics, and so does dart2js, at least.

Is there still something that differs from your expectations?

**Comment by jensjoha** [comment]
That symbol_operator_test was wrong before should have caused errors --- but I don't remember seeing any in that file.
And on your CL it now (in the results thing) says
```
new test -> Pass (expected Pass)
corelib/symbol_operator_test
```
which I don't get either --- because it seems it's not a new file?!?

Also

```
Pass -> skipped (expected Pass)
corelib/symbol_operator_test/none
```
and
```
Pass -> skipped (expected Pass)
corelib/symbol_operator_test/03
```

seems weird, but that's maybe just the results feed presenting it weirdly (2 and 3 went away I think).

**Comment by eernstg** [comment]
That's probably because it isn't a multi-test any more: all `//#`s are gone.

So `corelib/symbol_operator_test/X` with `X` in `{none, 03}` don't exist any more, which is shown as `skipped`, and the plain `corelib/symbol_operator_test` is considered new.

Maybe you can view the historical data by looking for `.../none` and `.../03`?

**Comment by jensjoha** [comment]
Right --- /none and /03 doesn't show up when not searching for them specifically... There doesn't seem to be any failures on /03 really before though, which is weird... 

Hah, at least some of the failures are

```
Unhandled exception:
Didn't throw: >>>
#0      testSymbolThrows (file:///b/s/w/ir/out/DebugX64/generated_tests/corelib/symbol_operator_test_03.dart:74:5)
```

i.e. in the *removed* stuff if I'm not mistaking..?

**Comment by eernstg** [comment]
Yes, that's perfect, the given configuration did have the new behavior already, so it was not throwing in `testSymbolThrows`. The new `testSymbolNotInstanceOperator` should then run with no errors, which is also what we see.

**Comment by scheglov** [comment]
What is "the current language"? So, `2.14`? But without a specific feature to attach this change to?

Or, `non-nullable` is the feature that enables it?
I'm going for now to assume this for now.

**Comment by scheglov** [comment]
`language/vm/symbols_test/03` expects that `const Symbol(r'_foo')` and a few other `_` strings are compile-time errors. But they should be fine, because they satisfy "any string".

Also will the documentation of the `Symbol` constructor be updated?

**Comment by eernstg** [comment]
> Or, `non-nullable` is the feature that enables it?

Yes, that's fine.

> `language/vm/symbols_test/03` expects that `const Symbol(r'_foo')` and a few
> other `_` strings are compile-time errors. But they should be fine, because they
> satisfy "any string".

Yes, cf. https://dart-review.googlesource.com/c/sdk/+/205781.

**Comment by eernstg** [comment]
Closing: All subtasks closed.
