### ISSUE TITLE
Trim abstract unix socket path length precomp Connection refused

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#46204]
There are new test failures on [Trim abstract unix socket path length](https://github.com/dart-lang/sdk/commit/5dc1f8db8c08ad10414c5a7ed3dd1693f239e1f9).

The tests
```
standalone_2/io/unix_socket_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-android-release-arm64
dartkp-android-release-arm_x64
dartkp-asan-linux-release-x64
dartkp-linux-debug-simarm-crossword
dartkp-linux-release-arm64
dartkp-linux-release-simarm-crossword
dartkp-tsan-linux-release-x64
```

```
// ...

--- Command "vm" (took 130ms):
DART_CONFIGURATION=ReleaseASANX64 out/ReleaseASANX64/dart_precompiled_runtime --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseASANX64/generated_compilations/dartkp-asan-linux-release-x64/tests_standalone_2_io_unix_socket_test/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.fail('Unexpected exception Expect.fail('Failed with exception:
SocketException: Connection failed (OS Error: Connection refused, errno = 111), address = @hidden, port = 0
') is thrown')
#0      Expect._fail (package:expect/expect.dart:731)
#1      Expect.fail (package:expect/expect.dart:300)
#2      main (file:///b/s/w/ir/cache/builder/sdk/tests/standalone_2/io/unix_socket_test.dart:447)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-asan-linux-release-x64 standalone_2/io/unix_socket_test
```

https://dart-ci.appspot.com/log/vm-kernel-precomp-asan-linux-release-x64/dartkp-asan-linux-release-x64/1319/standalone_2/io/unix_socket_test

The test was modified on this CL to test new functionality.

Multiple configurations fail, all precompiled, but not all precomp bots fail (or did those get approved earlier)?

CL https://dart-review.googlesource.com/c/sdk/+/201441

Test status: https://dart-ci.firebaseapp.com/current_results/#/filter=standalone_2/io/unix_socket_test

cc @zanderso @a-siva @aam

**Comment by zanderso** [comment]
Some fixes here https://dart-review.googlesource.com/c/sdk/+/201861

**Comment by zanderso** [comment]
I landed the above fixes. I'm not sure how to interpret the Dart dashboard. @dcharkes could you take a look and let me know if we can close this?

**Comment by dcharkes** [comment]
### Failures
I see one hard failure on one configuration https://dart-ci.appspot.com/log/any/dartkp-android-release-arm_x64/4732/standalone_2/io/unix_socket_test.

```
sizeof(UntaggedScript) got 48, AOT_Script_InstanceSize expected 40
../../runtime/vm/dart.cc: 170: error: CheckOffsets failed. Try updating offsets by running ./tools/run_offsets_extractor.sh
version=2.14.0-edge.e3bc9b6104f224f76fdc9ea9ca846980937eddf9 (be) (Thu Jun 3 13:21:35 2021 +0000) on "android_arm"
```

This does not look like that is related to the test or your changes. Just the redness on the Dart CI at this moment.

### Flakes

The logs for flaking test can be found on the flakiness dashboard: [link to test](https://dashboards.corp.google.com/_0d7e1e34_2c58_4d29_bf12_cf7bed10396d?fb=name:in:standalone_2%2Fio%2Funix_socket_test,standalone%2Fio%2Funix_socket_test&fh=eJxFzLEKQyEMheF3yewkLvUNOjuKQ9DAFaIVG4dS7rtr6NDxO_Cf-IVawEPHRmAgv3i1_rd8Bh29iSnLcUHBMCg_tbH24ZzV6sIpOsVkoC2WGn6Bl7novFRhvYE7bbeDI0s.).

When clicking on the number under RTE you can see the log of how the test failed the last time it failed. And then from there back to build you can see which build that run belonged to.

It looks like all flaky failures were on June 1st and before (so before the fixes were landed).

So I would say we do not have current failures. Thanks for the fixes!
