### ISSUE TITLE
Poor analyzer error message when using type `Never` prior to Dart 2.12

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#46217]
Running `dart analyze` on this program:
```dart
// @dart=2.11
Never f() => throw 'foo';
```
Produces this message:
```
Analyzing test.dart...                 3.4s

   info • test.dart:2:1 • The type 'Never' wasn't supported until version 2.X.0, but this code is required to be able to run on
          earlier versions. Try updating the SDK constraints. • sdk_version_never

1 issue found.
```
That message should say `2.12.0`, not `2.X.0` 😃

**Comment by stereotype441** [comment]
The text `2.X.0` also shows up on our website, if you follow the link associated with the error: https://dart.dev/tools/diagnostic-messages#sdk_version_never

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/202067
