### ISSUE TITLE
vm_service Null check operator used on a null value

### ISSUE THREAD

**Issue by liujiakuoyx** [dart-lang/sdk#46213]
vm_service: ^7.0.0

#0      new Script._fromJson (package:vm_service/src/vm_service.dart:6813:50)
#1      Script.parse (package:vm_service/src/vm_service.dart:6772:36)
#2      createServiceObject (package:vm_service/src/vm_service.dart:68:25)
#3      VmService._processResponse (package:vm_service/src/vm_service.dart:2202:26)
#4      VmService._processMessageStr (package:vm_service/src/vm_service.dart:2181:7)
#5      VmService._processMessage (package:vm_service/src/vm_service.dart:2133:7)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
 Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by parlough** [comment]
The non-null assertion referred to here was removed in https://github.com/dart-lang/sdk/commit/fa5da6a944485e62f7bba5761ccbc54f0b80326e, reliably handling nullable values. It seems this fix was included in the following `package:vm_service` v7.1.0 release, so this should be fixed by now.

Thanks for reporting the issue :)
