### ISSUE TITLE
[CP][stable channel] Fix an analyze crash when analyzing against package:meta v1.4.0

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#46210]
**commit(s) to merge**: COMMIT-HASH

- https://github.com/dart-lang/sdk/commit/8eba5201159e001520f93bf5d398dfacf5930fd1

**merge instructions**: clean merge or patch CL

- assumed clean merge

**What is the issue**: Brief description of the problem

The analyzer in stable was built against package:meta 1.3.0. A value was added to a package:meta enum in meta 1.4.0; if the current stable analyzer analyzes code (that uses the 'targetkind' annotation), and the user code is using meta 1.4.0, the analyzer will crash.

**What is the fix**: Brief description of the fix

This fix improves the enum lookup for this situation to be based on the name of the enum and not the index of the enum.

**Why cherrypick**: Describe the reasons, like many users impacted, or serious functional issues, for example

This is a small fix, and many people using analyzer stable, but resolving their code against the recently released package:meta 1.4.0, will see analyzer crashes.

**Risk**:

- low

**Link to original  issue(s)**:

- https://github.com/dart-lang/sdk/issues/46183

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

--------

**Comment by franklinyow** [comment]
@kf6gpe

**Comment by franklinyow** [comment]
Description:
Fix an analyze crash when analyzing against package:meta v1.4.0 , see #46183 for detail

**Comment by athomas** [comment]
Merged to stable in 516eb3b05c252ef3d34255d06700c1f09f7f4502 (2.13.3).
