### ISSUE TITLE
[vm/ffi] Uint64 may have negative values

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#46214]
Consider the following program

```dart
import "dart:ffi";
import "package:ffi/ffi.dart";

void main() {
  final pointer = calloc<Uint64>();
  try {
    pointer.value = -1;
    print(pointer.value);  // prints -1
  } finally {
    calloc.free(pointer);
  }
}
```
Why unsigned value became negative here? If to change value to `Uint32` (`final pointer = calloc<Uint32>();`), then printed value became `4294967295`

Tested on `Dart SDK version: 2.14.0-166.0.dev (dev) (Fri May 28 20:48:34 2021 -0700) on "windows_x64"`

**Comment by mraleph** [comment]
Dart does not have unsigned integers so Uint64 values above max signed 64-bit integer (`(1 << 63) - 1`) will look like negative integers when they pass through into Dart. There is no loss of information through because they are bitwise equal.
