### ISSUE TITLE
The compiler is broken.

### ISSUE THREAD

**Issue by AndyKat22** [dart-lang/sdk#46215]
$ flutter build web --release --web-renderer html

OS / Version - Mac OS Catalina 10.15.7
Dart : Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Target dart2js failed: Exception: .dart_tool/flutter_build/cf7c7397902276c32230314e3de29087/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.13.1), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: FileSystemException: writeFrom failed, path =
'/Users/andy/Projects/Ukuvuna/ukuvuna_web/.dart_tool/flutter_build/cf7c7397902276c32230314e3de29087/app.dill' (OS Error: No
space left on device, errno = 28)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
#1      RandomAccessFileOutputProvider.createBinarySink.writeBytesSync
(package:compiler/src/source_file_provider.dart:445:14)
#2      _BinaryOutputSinkWrapper.write (package:compiler/src/source_file_provider.dart:496:14)
#3      BinaryOutputSinkAdapter.add (package:compiler/src/util/sink_adapter.dart:10:12)
#4      BufferedSink.addBytes (package:kernel/binary/ast_to_binary.dart:2978:13)
#5      BinaryPrinter.writeBytes (package:kernel/binary/ast_to_binary.dart:95:11)
#6      BinaryPrinter.writeByteList (package:kernel/binary/ast_to_binary.dart:118:5)
#7      BinaryPrinter.writeUriToSource (package:kernel/binary/ast_to_binary.dart:810:7)
#8      BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:568:7)
#9      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#10     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:549:14)
#11     KernelLoaderTask.load.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/loader.dart:196:19)
#12     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#13     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:189:9)
<asynchronous suspension>
#14     Compiler.runInternal (package:compiler/src/compiler.dart:285:29)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             15.6s
Exception: Failed to compile application for the Web.

**Comment by julemand101** [comment]
> OS Error: No space left on device

Have you checked if this error is right? Do you have any space left on the device where "/Users/andy/Projects/Ukuvuna/ukuvuna_web/.dart_tool/flutter_build/cf7c7397902276c32230314e3de29087/app.dill" is located?

**Comment by AndyKat22** [comment]
@julemand101 

That was the case 100%... To be honest, I didn't even see that, too many late nights in a row :-)

Thanks for pointing that out.
