### ISSUE TITLE
@debugOnly annotation

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#46223]
It's occasionally useful to expose an API purely for use when debugging code, but that should never be checked in to a real project. Examples include the `solo` flag for the `test()` function in `package:test` or a flag to enable verbose debugging output for a library. It would be useful to have an annotation to represent this (similar to `@deprecated`) that can be placed anywhere `@deprecated` can and produces an error if the annotated item is used in any context except in the package in which it's defined.

**Comment by MrBirb** [comment]
Well you already opened an [issue](https://github.com/dart-lang/sdk/issues/28113)  in 2016 😅

**Comment by nex3** [comment]
https://media0.giphy.com/media/KChOCrUh2lYxW/giphy.gif
