### ISSUE TITLE
LibraryDependency does not surface what the show clause was for a library dependency

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#46221]
https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#librarydependency

This makes it hard to determine what members from a library dependency are actually visible and which ones aren't.
This information is useful for autocomplete in DevTools and any other tools that want to surface what the public api of a library looks like.

**Comment by jacob314** [comment]
Fyi @bkonyi

**Comment by bkonyi** [comment]
Re-opening until package:vm_service changes are published.

FYI @annagrin, this is coming down the pipe and will require some dwds work.
