### ISSUE TITLE
dart2js has no null-safe production mode builders

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#46220]
The `dart2js-nnbd-linux-x64-chrome` is our only builder running null-safe tests. Although it covers all the relevant test suites, it does not run any of them in minified or production mode, like `dart2js-minified-strong-linux-x64-d8` does. We now perform lowering and optimization of enough null-safety-specific features (like `late`) that we should ensure this configuration is tested.

cc @sigmundch

**Comment by sigmundch** [comment]
Good point.

I am now noticing that the test matrix is attempting to run strong and weak mode, but the `--no-sound-null-safety` was not being specified in weak mode, so we seem to be running some tests in strong mode twice for the migrated suites. Maybe we should swap some of that redundant work and run with a production mode instead? (since we anyways get weak mode coverage from the _2 suites?)

**Comment by fishythefish** [comment]
Good catch! Presumably these got missed when default flags changed? I notice that other configurations with `--no-sound-null-safety` are all suffixed `-unsound` but the `dart2js-hostasserts-weak-*` ones aren't.

We should update the test matrix so that we have coverage for the migrated suites with `--no-sound-null-safety`. We could ensure that the flag gets plumbed to the `weak` configurations, but since we no longer have an experiment flag, perhaps we should just remove these configurations and use the pre-null-safety ones they were based on? We'll additionally want to include at least one of the minified/production configurations, so that'll require some extra capacity.

I don't think we can rely entirely on `_2` suites for coverage of unsound null safety. The migrated suites can use language features which are unavailable in `_2`, and we should ensure that those work as expected with unsound null safety.

**Comment by sigmundch** [comment]
Sounds good, let me propose that we preserve the historical names then to reduce the churn on the status/history data. In summary:
* add `--no-sound-null-safety` to most dart2js configurations that don't say `-strong-`
* remove `-unsound` configurations (now redundant with the historical configurations with the flag fixed)
* remove `-weak-` configurations (ditto)
* change the NNBD bot to use the unsound configurations on migrated suites (non-`_2`)
* add a production-sound configuration (or production-strong to be consistent with the existing naming)
* add steps to test that configuration also in the NNBD builder


What do you think? Do feel we need to add coverage for all suites, or could we just restrict this to a few suites? Like web? or maybe language, corelib, and web?


/cc @athomas @whesse  - FYI we'll be adding a few steps in our build bot to ensure we add coverage for a production configuration on some tests. Do we need some additional capacity for this change?

**Comment by fishythefish** [comment]
Mostly SGTM. I think we're in agreement, but just to clarify:
* The NNBD bot will continue to run both sound and unsound configurations on migrated suites, but the unsound ones should now actually be running in unsound mode with the flag.
* We should also add the (existing) unsound production configuration to the NNBD bot.

For the production configurations, I think we should prioritize test suites that exercise the new language features unavailable in `_2` suites. My instinct is to go with `language`, `corelib`, and `co19`. Are those too much? (A possible benefit is that we can stick with a `d8` runtime rather than a browser.)

---

If we're willing to deal with some churn right now, we have an opportunity to improve the naming, since we've been trying to get away from the term "strong". Your proposal results in each configuration having a plain version which is passed `--no-sound-null-safety` and a `-strong-` version. Instead, we could commit to having a plain version and an `-unsound` version which is passed `--no-sound-null-safety`.

Aside from the naming benefits, this means that we view sound null safety as the default, and the specially-tagged configurations become the ones that need the extra flag. When we remove unsound null safety, we can just delete the `-unsound` configurations and the `_2` suites, and the plain configurations won't need to be touched and won't have any churn. The current churn may also be mitigated by the fact that our plain configurations are accidentally running without `--no-sound-null-safety`. Thoughts?

**Comment by sigmundch** [comment]
I'm good with that plan, I saw we go for it!

Some additional clarifications:

> The NNBD bot will continue to run both sound and unsound configurations on migrated suites, but the unsound ones should now actually be running in unsound mode with the flag.

correct

> We should also add the (existing) unsound production configuration to the NNBD bot.

we can, it also feels a bit wasteful to do this for all those suites. Maybe just a small suite like `language` as a smoke test?

Another detail: Should we use a regular (and not hostasserts) build for all production configurations? That also helps reduce the load.

Regarding renames: I like it. If we find the history to be valuable, then we may want to consider renaming the configurations also in the database (I believe @athomas @whesse have mentioned that it's a possibility).

**Comment by athomas** [comment]
Re: renames: They are still tricky, but what we can relatively easily do is to baseline a new configuration on an old one (that's not really a re-name because they old one would still be in the databases).

**Comment by nshahan** [comment]
I'm adding a new test in the language_2 directory and I got a failure on dart2js-strong-hostasserts-linux-ia32-d8-try.
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8839154923620053552/+/u/test_results/new_test_failures__logs_

Since the test is in the language_2 directory it should be considered legacy code and running with weak null safety but the error message makes it appear that the configuration attempted and failed to load a sound .dill file.
