### ISSUE TITLE
[gardening/test] string_overflow_test is failing

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#46225]
This failure currently affects a large number of bots:
```
Unhandled exception:
Out of Memory
#0      _StringBase._concatRangeNative (dart:core-patch/string_patch.dart:956:34)
#1      String._concatAll (dart:core-patch/string_patch.dart:1008:26)
#2      _StringBase._interpolate (dart:core-patch/string_patch.dart:876:27)
#3      main (file:///b/s/w/ir/tests/standalone/string_overflow_test.dart:14:34)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

The reason this old test is failing now is that [201227](https://dart-review.googlesource.com/c/sdk/+/201227) renamed the file which likely caused it to start getting picked up as a test. Plus the catch for OoM errors was removed.

I'll go ahead and approve this failing to unblock the bots.
Though my personal feeling is that this test probably should be rewritten to at least be less wasteful with memory, if possible.

**Comment by cskau-g** [comment]
CC: @munificent FYI

**Comment by mkustermann** [comment]
Tests cannot assume they can allocate a large amount of memory. I'll try to fix it.
