### ISSUE TITLE
Implement constructor tearoffs support in IntelliJ

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46234]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

**Comment by devoncarew** [comment]
@eernstg - is the syntax finalized now (and ready for parsers to implement / syntax highlighters to be updated)?

cc @jwren

**Comment by eernstg** [comment]
I think it's a good idea to wait, in order to avoid duplicated work in case there are changes in the design before it is accepted. We will add a comment here (and on all the other issues associated with #46228) at that time.

**Comment by jwren** [comment]
@eernstg -  Devon mentioned that the syntax is finalized enough to add to the Dart Plugin for IntelliJ.  The feature link above is broken, is [this link](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md) the correct source of truth?  Thank you -- Jaime

**Comment by eernstg** [comment]
@jwren, thanks! Yes, the document was moved and the link you mentioned is the correct one today. Corrected it above, too.

**Comment by jwren** [comment]
Grammar changes required are here: https://dart-review.googlesource.com/c/sdk/+/197161

**Comment by jwren** [comment]
Initial PR to Alex out at https://github.com/JetBrains/intellij-plugins/pull/819

**Comment by devoncarew** [comment]
@jwren - I believe the support landed?

**Comment by alexander-doroshko** [comment]
@devoncarew Only part of it. Things like `const filledIntList = List<int>.filled;` are not supported yet. Also tracked as https://youtrack.jetbrains.com/issue/WEB-52293.

**Comment by devoncarew** [comment]
Great, thanks for the update! FYI, depending on general readiness, we may or may not enable this in the beta release shipping the week of 9/13.

**Comment by devoncarew** [comment]
Also related: https://github.com/dart-lang/sdk/issues/47160

**Comment by devoncarew** [comment]
@jwren - can you confirm that this is generally on track for early October?

**Comment by jwren** [comment]
I have tried a few times to cover the last case (see above) without overhauling the BNF.  @alexander-doroshko said he would try to take a look soon.  To answer the question though, we'll figure it out in time for an early October release.

**Comment by alexander-doroshko** [comment]
Full syntax support is there in the latest published Dart plugin builds for all IDEs.

**Comment by devoncarew** [comment]
Great - thanks!
