### ISSUE TITLE
Implement constructor tearoffs support in AngularDart

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46239]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

**Comment by devoncarew** [comment]
@grouma - did you find out if there was work to do here before this lands internally? Work that we'd like to do after it lands? We expect the other work to be feature complete early October.

**Comment by grouma** [comment]
I discussed with the team internally. I don't think there is work to do besides verifying the feature. I just now was able to manually verify the feature works as expected for some edge cases the team was concerned about. We should be good from the Angular perspective unless something unforeseen pops up.

**Comment by devoncarew** [comment]
Great, thanks! I'll close - we can re-open more specific items if we do find issues.
