### ISSUE TITLE
Implement constructor tearoffs support in DDC

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46230]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

The implementation issues for this feature are needed in order to have a reference when approving test failures. Further information will be added here when the implementation work starts.

**Comment by nshahan** [comment]
Implemented in 5ea90ee.
