### ISSUE TITLE
Implement constructor tearoffs support in the VM/AOT

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46231]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

The implementation issues for this feature are needed in order to have a reference when approving test failures. Further information will be added here when the implementation work starts.

**Comment by alexmarkov** [comment]
The tests

```
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A01_t01
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A02_t05
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t01
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t03
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t04
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A04_t02
```

currently crash on `dartkp-strong-linux-release-x64` and `dartkp-weak-asserts-linux-release-x64` configurations.
Example log:
```
--- Command "vm_compile_to_kernel" (took 03.000326s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --enable-experiment=constructor-tearoffs --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_LanguageFeatures_Constructor-tear-offs_tearing_off_from_typedef_A01_t01/out.dill /b/s/w/ir/tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A01_t01.dart --enable-experiment=constructor-tearoffs --packages=/b/s/w/ir/.packages -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 02.000818s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --enable-experiment=constructor-tearoffs --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_LanguageFeatures_Constructor-tear-offs_tearing_off_from_typedef_A01_t01/out.S --enable-experiment=constructor-tearoffs --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_LanguageFeatures_Constructor-tear-offs_tearing_off_from_typedef_A01_t01/out.dill

exit code:
-6

stderr:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x39
version=2.14.0-edge.970ea21f4971f929c2487cdbfa4eb9a2a90877db (be) (Tue Jul 20 09:15:20 2021 +0000) on "linux_x64"
pid=1806, thread=1806, isolate_group=isolate(0x55f033aa7c00), isolate=(nil)((nil))
isolate_instructions=0, vm_instructions=0
  pc 0x000055f0313202ab fp 0x00007fffe58ffa60 dart::LocalScope::CaptureVariable(dart::LocalVariable*)+0xb
  pc 0x000055f031747e9c fp 0x00007fffe58ffaa0 dart::kernel::ScopeBuilder::VisitTypeParameterType()+0x1ac
  pc 0x000055f031747ffc fp 0x00007fffe58ffb40 dart::kernel::ScopeBuilder::AddVariableDeclarationParameter(long, dart::kernel::ScopeBuilder::ParameterTypeCheckMode, dart::kernel::ProcedureAttributesMetadata const&)+0xcc
  pc 0x000055f0317441e6 fp 0x00007fffe58ffcc0 dart::kernel::ScopeBuilder::BuildScopes()+0x1076
  pc 0x000055f0312bb6f7 fp 0x00007fffe58ffff0 dart::ParsedFunction::EnsureKernelScopes()+0x37
  pc 0x000055f03170ec03 fp 0x00007fffe5900020 dart::kernel::StreamingFlowGraphBuilder::ParseKernelASTFunction()+0x53
  pc 0x000055f03170ea57 fp 0x00007fffe59000d0 dart::kernel::StreamingFlowGraphBuilder::BuildGraph()+0xb7
  pc 0x000055f031722153 fp 0x00007fffe5900380 dart::kernel::FlowGraphBuilder::BuildGraph()+0x63
  pc 0x000055f031364140 fp 0x00007fffe5900590 dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool)+0x40
  pc 0x000055f031619c7a fp 0x00007fffe5900c70 dart::PrecompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x31a
  pc 0x000055f03161ac05 fp 0x00007fffe5900e60 out/ReleaseX64/gen_snapshot+0xa5fc05
  pc 0x000055f031616f96 fp 0x00007fffe5900f60 dart::Precompiler::CompileFunction(dart::Precompiler*, dart::Thread*, dart::Zone*, dart::Function const&)+0x176
  pc 0x000055f031614601 fp 0x00007fffe5900fd0 dart::Precompiler::ProcessFunction(dart::Function const&)+0xe1
  pc 0x000055f03160f0c4 fp 0x00007fffe5901020 dart::Precompiler::Iterate()+0x94
  pc 0x000055f031604664 fp 0x00007fffe59012d0 dart::Precompiler::DoCompileAll()+0x1004
  pc 0x000055f0316035f1 fp 0x00007fffe5901810 dart::Precompiler::CompileAll()+0x101
  pc 0x000055f03179dffd fp 0x00007fffe5901960 Dart_Precompile+0x19d
  pc 0x000055f03110d5ed fp 0x00007fffe5901ae0 dart::bin::main(int, char**)+0x84d
-- End of DumpStackTrace

--- Re-run this test:
python3 tools/test.py -n dartkp-strong-linux-release-x64 co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A01_t01
```

**Comment by alexmarkov** [comment]
These tests also fail:

```
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A04_t03
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A05_t01
```

```
--- Command "vm_compile_to_kernel" (took 01.000311s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --enable-experiment=constructor-tearoffs --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_LanguageFeatures_Constructor-tear-offs_tearing_off_from_typedef_A04_t03/out.dill /b/s/w/ir/tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A04_t03.dart --enable-experiment=constructor-tearoffs --packages=/b/s/w/ir/.packages -Ddart.vm.product=false --sound-null-safety

exit code:
253

stderr:
Unexpected node StaticTearOff: StaticTearOff(List.filled) at file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A04_t03.dart:31:12
#0      SummaryCollector.defaultTreeNode (package:vm/transformations/type_flow/summary_collector.dart:1437:7)
#1      TreeVisitor.defaultExpression (package:kernel/visitor.dart:192:43)
#2      TreeVisitor.visitStaticTearOff (package:kernel/visitor.dart:209:47)
#3      StaticTearOff.accept (package:kernel/ast.dart:4780:44)
#4      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:864:42)
#5      SummaryCollector.visitVariableDeclaration (package:vm/transformations/type_flow/summary_collector.dart:2142:48)
#6      VariableDeclaration.accept (package:kernel/ast.dart:10402:43)
#7      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:864:42)
#8      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart)
#9      List.forEach (dart:core-patch/growable_array.dart:403:8)
#10     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1930:21)
#11     Block.accept (package:kernel/ast.dart:8862:43)
#12     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:864:42)
#13     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:765:9)
#14     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1485:52)
#15     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:287:42)
#16     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:212:14)
#17     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1381:32)
#18     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1620:23)
#19     Call.apply (package:vm/transformations/type_flow/summary.dart:273:31)
#20     Summary.apply (package:vm/transformations/type_flow/summary.dart:722:33)
#21     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:296:24)
#22     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:212:14)
#23     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1381:32)
#24     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1324:7)
#25     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1503:14)
#26     transformComponent (package:vm/transformations/type_flow/transformer.dart:85:20)
#27     runGlobalTransformations (package:vm/kernel_front_end.dart:457:5)
#28     compileToKernel (package:vm/kernel_front_end.dart:374:11)
<asynchronous suspension>
#29     runCompiler (package:vm/kernel_front_end.dart:267:19)
<asynchronous suspension>
#30     runBatchModeCompiler.<anonymous closure> (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:57:22)
<asynchronous suspension>
#31     runBatch (package:kernel/src/tool/batch_util.dart:38:33)
<asynchronous suspension>
#32     runBatchModeCompiler (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:43:3)
<asynchronous suspension>
#33     main (file:///b/s/w/ir/pkg/vm/bin/gen_kernel.dart:32:5)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-strong-linux-release-x64 co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A04_t03
```

**Comment by whesse** [comment]
More tests have shown up as crashing on ia32, with the latest commit landed:
dartk-strong-linux-debug-ia32
dartk-weak-asserts-linux-debug-ia32

co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A01_t01
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A01_t02
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t01
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t06
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t09
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t10
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t14
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t19
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t20
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t23
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t24
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A05_t02
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A06_t02

Log:
[https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-debug-ia32/dartk-strong-linux-debug-ia32/283/co19/LanguageFeatures/Constructor-tear-offs/named*](https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-debug-ia32/dartk-strong-linux-debug-ia32/283/co19/LanguageFeatures/Constructor-tear-offs/named*)

DART_CONFIGURATION=DebugIA32 out/DebugIA32/dart --sound-null-safety --enable-experiment=constructor-tearoffs --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A01_t02.dart

exit code:
-6

stderr:
../../runtime/vm/compiler/assembler/assembler_ia32.cc: 1959: error: expected: IsNotTemporaryScopedHandle(object)
version=2.14.0-edge.58969783ba6b20b68c42da32a91a77e5862bbafb (be) (Fri Jul 30 21:32:58 2021 +0000) on "linux_ia32"
pid=25024, thread=25090, isolate_group=main(0x4e32900), isolate=main(0x4e48500)
isolate_instructions=1f52260, vm_instructions=1f52260
  pc 0x0231c5c9 fp 0xf2c7dfa8 dart::Profiler::DumpStackTrace(void*)+0x89
  pc 0x0283cdf4 fp 0xf2c7dfc8 Dart_DumpNativeStackTrace+0x14
  pc 0x01f5239a fp 0xf2c7dff8 dart::Assert::Fail(char const*, ...)+0x2a
  pc 0x02693d4b fp 0xf2c7e048 dart::compiler::Assembler::PushObject(dart::Object const&)+0x10b
  pc 0x027fc3dd fp 0xf2c7e1a8 dart::compiler::StubCodeCompiler::GenerateAllocationStubForClass(dart::compiler::Assembler*, dart::GrowableArray<dart::compiler::UnresolvedPcRelativeCall*>*, dart::Class const&, dart::Code const&, dart::Code const&)+0x53d
  pc 0x023b4cc2 fp 0xf2c7e308 dart::StubCode::GetAllocationStubForClass(dart::Class const&)+0x282
  pc 0x02715335 fp 0xf2c7e358 dart::AllocateObjectInstr::EmitNativeCode(dart::FlowGraphCompiler*)+0x25
  pc 0x026bd268 fp 0xf2c7e4b8 dart::FlowGraphCompiler::VisitBlocks()+0x3e8

**Comment by alexmarkov** [comment]
Implementation is complete.

Current status of tests:

1. All `language` tests which enable `constructor-tearoffs` experiment are now passing on all VM configurations: 
```
language/constructor/tear_off_test
language/constructor/unnamed_new_test
language/generic_methods/explicit_instantiated_tearoff_test
language/type_object/explicit_instantiated_type_literal_test
language/typedef/aliased_constructor_tear_off_test
language/typedef/aliased_type_literal_instantiation_test
```

2. co19/LanguageFeatures/Constructor-tear-offs tests in `dartk-strong-linux-release-x64` configuration: 174 tests passed, 20 failed:

- 16 CompileTimeError and 2 MissingCompileTimeError (https://github.com/dart-lang/sdk/issues/46882).

- 2 RuntimeError: 1 incorrect test (https://github.com/dart-lang/co19/issues/1160); 1 test for equality of types (https://github.com/dart-lang/sdk/issues/46893)

3. co19/LanguageFeatures/Constructor-tear-offs tests in `dartkp-strong-linux-release-x64` configuration: 173 tests passed, 21 failed:

- 1 more CompileTimeError as co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A06_t01 uses dart:mirrors which is not supported in AOT mode.

**Comment by alexmarkov** [comment]
In weak mode (`dartk-weak-asserts-linux-release-x64` and `dartkp-weak-asserts-linux-release-x64` configurations) there are 6 more RuntimeErrors on co19/LanguageFeatures/Constructor-tear-offs tests. All of them are due to incorrect tests (https://github.com/dart-lang/co19/issues/1161).

**Comment by alexmarkov** [comment]
Status of co19 tests on the most recent version of tests from co19 repository (at https://github.com/dart-lang/co19/commits/6cb0670b42ddd2a74d65f7d69213af76ef5f8ac9):

dartk-strong-linux-release-x64, dartk-weak-asserts-linux-release-x64: 185 tests passed, 7 failed (5 CompileTimeError, 2 MissingCompileTimeError).

dartkp-strong-linux-release-x64, dartkp-weak-asserts-linux-release-x64: 184 tests passed, 8 failed (6 CompileTimeError, 2 MissingCompileTimeError).

There are no outstanding VM bugs.
