### ISSUE TITLE
Change core libraries as needed in order to use or work well with constructor tearoffs

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46245]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/working/0216%20-%20constructor%20tearoffs/proposal.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

The implementation issues for this feature are needed in order to have a reference when approving test failures. Further information will be added here when the implementation work starts.

**Comment by lrhn** [comment]
There are no planned changes to the platform libraries.
We may want to *use* the feature, in cases where we currently eta-expand a constructor instead of tearing it off, but that's neither urgent nor important and can be fixed at any later time. It should not block release of the feature.
