### ISSUE TITLE
Update documentation to cover constructor tearoffs

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46243]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

**Comment by devoncarew** [comment]
cc @kwalrath

**Comment by leafpetersen** [comment]
Does this cover any effective dart work required?  cc @munificent

**Comment by jacob314** [comment]
It would align well with lints if effective dart explained why you should get used to always using tearoffs when they have the same result.
E.g.
Never write:
`foo.forEach((e) => print(e))`
when you can write
`for.forEach(print)`
for all kinds of tearoffs.

**Comment by munificent** [comment]
I think we will want to reword the guideline around tear-offs a little since the current wording is limited to methods. Filed https://github.com/dart-lang/site-www/issues/3560 to track.
