### ISSUE TITLE
Implement constructor tearoffs support in language tests and in co19 tests

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46242]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

The work on these tests has started:

- [x] [co19 tests](https://github.com/dart-lang/co19/issues/1087)
- [ ] [language tests](https://dart-review.googlesource.com/c/sdk/+/197168)

**Comment by devoncarew** [comment]
@eernstg - is this item done (or if not, who's the best owner?)?

**Comment by eernstg** [comment]
The co19 tests are here: https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Constructor-tear-offs.

I'm working on https://dart-review.googlesource.com/c/sdk/+/211140 which adds a test about constant factory contructors #46984, and I'm about to add a test about syntactic disambiguation, dart-lang/language#1806.

@lrhn, do you have any upcoming constructor-tearoffs tests? Current language tests are here:

```
typedef/aliased_type_literal_instantiation_test.dart
typedef/aliased_constructor_tear_off_test.dart
constructor/reference_test.dart
constructor/tear_off_test.dart
constructor/unnamed_new_error_test.dart
constructor/unnamed_new_test.dart
generic_methods/explicit_instantiated_tearoff_test.dart
type_object/explicit_instantiated_type_literal_error_test.dart
type_object/explicit_instantiated_type_literal_test.dart
```

So we're nearly done. I've assigned myself as owner.

**Comment by eernstg** [comment]
No further proposals, so I'll close this one.
