### ISSUE TITLE
Implement constructor tearoffs support for the VM Service

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46240]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

**Comment by bkonyi** [comment]
Added some tests [in this CL](https://dart-review.googlesource.com/c/sdk/+/212627).

**Comment by devoncarew** [comment]
@bkonyi - do you know if there's anything more to do here?

**Comment by bkonyi** [comment]
Nope, just need the tests to land.
