### ISSUE TITLE
[CP][stable channel] Ensure start/stop file watching requests are run on the dart thread.

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#46249]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/ed82bb6f4c5a90b81ff91052cdedc53817488b16

**merge instructions**: clean merge or patch CL

- assumed clean

**What is the issue**: Brief description of the problem

- numerous user reports of the analysis server stopping responding to IDE requests; this is due to the isolate running the analysis server deadlocking when unsubscribing from file watching events

**What is the fix**: Brief description of the fix

At present start/stop requests are scheduled on RunLoop thread. This results in deadlocks since same RunLoop thread might be busy with blocking writes of file watching events, not giving a chance for Dart to read previously-written events. Reading would unblock writer.

This fix moves start/stop requests to run on Dart thread instead.

**Why cherrypick**: Describe the reasons, like many users impacted, or serious functional issues, for example

- lots of users reports; likely manifesting in a few separate issues

**Risk**:

- assumed low; cc @a-siva @aam

**Link to original  issue(s)**:

- https://github.com/dart-lang/sdk/issues/45996

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @a-siva @aam @DanTup

**Comment by franklinyow** [comment]
Description:
Fix for analysis server stop responding to IDE requests , see #45996 for detail

**Comment by aam** [comment]
@mraleph pointed out potential (unlikely) problem in the original fix, which were fixed in follow-up [dart#202312](https://dart-review.googlesource.com/c/sdk/+/202312) landed three days ago in dart sdk.

**Comment by aam** [comment]
that follow-up change I mentioned [dart#202312](https://dart-review.googlesource.com/c/sdk/+/202312) landed in flutter https://github.com/flutter/flutter/commit/c9d5485361ddfe5d3d04b73149537dff5b74d51f 21h ago

**Comment by a-siva** [comment]
Created https://github.com/dart-lang/sdk/issues/46298 for the additional change to be picked.

**Comment by athomas** [comment]
Merged to stable in 516eb3b05c252ef3d34255d06700c1f09f7f4502 (2.13.3).
