### ISSUE TITLE
LateInitializationError: Field '_local@xxxxxxxx' has not been initialized in flutter

### ISSUE THREAD

**Issue by Shashwat2708** [dart-lang/sdk#46259]
This is my code. I have imported all the neccessary pacages which were-
```dart
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/data/latest.dart' as tz;
```
Please help me as soon as possible

```dart
`FlutterLocalNotificationsPlugin notificationsPlugin =
FlutterLocalNotificationsPlugin();

class customSwitch extends StatefulWidget {
  const customSwitch({Key key}) : super(key: key);


  @override
  _customSwitchState createState() => _customSwitchState();
}

class _customSwitchState extends State<customSwitch> {

  bool state = true;
  @override
  Widget build(BuildContext context) {
    return Switch(
        value: state,
        onChanged: (bool s) async {
          setState(() {
            state = s;
          });
          if (state == true){
            await displayNotification();
          }else{

          }
        });
  }
  Future<void> displayNotification() async {
    notificationsPlugin.zonedSchedule(
        0,
        "Hello",
        'Match is Started',
        tz.TZDateTime.now(tz.local).add(Duration(seconds: 3)),
        NotificationDetails(
          android: AndroidNotificationDetails(
              'channel id', 'channel name', 'channel description'),
        ),
        uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime,
        androidAllowWhileIdle: true);
  }
}

void initializeSetting() async {
  var initializeAndroid = AndroidInitializationSettings('snoozer_logo');
  var initializeSetting = InitializationSettings(android: initializeAndroid);
  await notificationsPlugin.initialize(initializeSetting);
}
```

**Comment by Shashwat2708** [comment]
This is my code. I have imported all the neccessary pacages which were-
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/data/latest.dart' as tz;

Please help me as soon as possible




`FlutterLocalNotificationsPlugin notificationsPlugin =
FlutterLocalNotificationsPlugin();

class customSwitch extends StatefulWidget {
  const customSwitch({Key key}) : super(key: key);


  @override
  _customSwitchState createState() => _customSwitchState();
}

class _customSwitchState extends State<customSwitch> {

  bool state = true;
  @override
  Widget build(BuildContext context) {
    return Switch(
        value: state,
        onChanged: (bool s) async {
          setState(() {
            state = s;
          });
          if (state == true){
            await displayNotification();
          }else{

          }
        });
  }
  Future<void> displayNotification() async {
    notificationsPlugin.zonedSchedule(
        0,
        "Hello",
        'Match is Started',
        tz.TZDateTime.now(tz.local).add(Duration(seconds: 3)),
        NotificationDetails(
          android: AndroidNotificationDetails(
              'channel id', 'channel name', 'channel description'),
        ),
        uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime,
        androidAllowWhileIdle: true);
  }
}

void initializeSetting() async {
  var initializeAndroid = AndroidInitializationSettings('snoozer_logo');
  var initializeSetting = InitializationSettings(android: initializeAndroid);
  await notificationsPlugin.initialize(initializeSetting);
}
`

**Comment by lrhn** [comment]
Do you have a stack trace for the error?
The message means that a `late` declared variable named `_local` is being read before it has been written. I don't see any such declaration in the Dart platform libraries.

The most likely culprit is in the timezone package, https://github.com/srawlins/timezone/blob/a4f14a018690233294e914d95efcb09bc9dbf0a0/lib/src/env.dart#L20
If the stack trace agrees, I'd recommend filing an issue in that package. (@srawlins)

**Comment by Shashwat2708** [comment]
Till then, how can I use and schedule a notification?

**Comment by srawlins** [comment]
Notifications appear to be a part of Flutter or a Flutter package, so this is not the right place to ask. I think StackOverflow may be the best place to pose this question.

**Comment by Shashwat2708** [comment]
Ok.
I just had to initialize. I got it

**Comment by lrhn** [comment]
Seems like a dangerous design if you have to initialize the late field explicitly. I'd probably use a nullable field, check that it's initialized on each access and throw a `StateError` with a good error message if it's not.

In any case, that issue is in `package:timezone`, the rest is working as intended.

**Comment by muhammad-hamza-brainx** [comment]
@Shashwat2708  Kindly let me know how did you resolve this issue?

**Comment by EnesCaliskan** [comment]
I'm having the same problem. Can you tell us how you fixed the issue ?

**Comment by ninad7cos** [comment]
> I'm having the same problem. Can you tell us how you fixed the issue ?

import 'package:timezone/data/latest.dart' as tz;

void main() async{
  tz.initializeTimeZones();
  runApp(MyApp());
}

**Comment by EnesCaliskan** [comment]
> > I'm having the same problem. Can you tell us how you fixed the issue ?
> 
> import 'package:timezone/data/latest.dart' as tz;
> 
> void main() async{ tz.initializeTimeZones(); runApp(MyApp()); }
> 
> Initialize timezone

Thank you so much! Much appreciated!

**Comment by muhammad-hamza-brainx** [comment]
> > I'm having the same problem. Can you tell us how you fixed the issue ?
> 
> import 'package:timezone/data/latest.dart' as tz;
> 
> void main() async{ tz.initializeTimeZones(); runApp(MyApp()); }
> 
> Initialize timezone

Thank you so much!!

**Comment by Shashwat2708** [comment]
Sorry that i couldn't reply faster..... In these cases, all you need to do is either initialize the package in main function itself or you can do so in the initState.

**Comment by diwakar85** [comment]
tz.initializeTimeZones(); 

thanku so much

**Comment by gusreyes01** [comment]
Thank you!

> > > I'm having the same problem. Can you tell us how you fixed the issue ?
> > 
> > 
> > import 'package:timezone/data/latest.dart' as tz;
> > void main() async{ tz.initializeTimeZones(); runApp(MyApp()); }
> > Initialize timezone
> 
> Thanks a lot

Thank you!

**Comment by duythien02** [comment]
Thank you!
