### ISSUE TITLE
[Feature Request / Bug?][Analyzer] Allow using nullable final variables after checking for null

### ISSUE THREAD

**Issue by matanshukry** [dart-lang/sdk#46257]
When a member variable is declared both nullable and final, one should be able to evaluate it to a not-nullable type when comparing to null inside of a local method.

Code:
```
class MyData {
  MyData({this.value});
  
  final int? value;
  
  String get valueText {
    if (value == null) {
      return "No Value";
    }
    
    // value is final so it can't be changed, and we know it's not null.
    final int val = value;
    return val.toString();
  }
}
```

DartPad: http://dartpad.dev/198e3b0c685ab77d49c5ac71160f7ab3

**Comment by lrhn** [comment]
Dart can only promote *local* variables. Even a final variable can be overridden with a different getter in a subclass, and allowing promotion for final *variables* makes it a breaking change to make a variable change from `final var int foo = 42` to `int get foo => 42;`, something which should be non-breaking.

So, working as intended. We do need a better workaround for when you have nullable instance variables, but that's likely a different feature.

**Comment by matanshukry** [comment]
@lrhn that make sense. Like you mentioned though, we do need a better workaround. Is there an issue for it?

Example for what I'm ending up with at the moment btw:
```
void dispose() {
  final localData = _data;
  if (localData != null) {
    localData.dispose();
    _data = null;
  }
}
```

This case looks worse by the fact that inside the condition I'm changing the `_data` variable, to nullify it.

**Comment by lrhn** [comment]
We have [numerous issues in the language repository](https://github.com/dart-lang/language/issues?q=is%3Aissue+is%3Aopen+label%3Afield-promotion) discussing options, but no clear decision on which way to go. (They're all great - or not, or go too far, or not far enough, depending on perspective).

Your solution is what I would do too (and maybe even swap the assignment and `dispose` call, so the `dispose` method would see a `null` `_data` if it looks).
If I don't care about last-1% performance, I could also write it as:
```dart
void dispose() {
  _data?.dispose();
  _data = null;
}
```
and not care that I might set `_data` to `null` even if it already is.

**Comment by matanshukry** [comment]
@lrhn Awesome, thanks for the help and the quick reply!
