### ISSUE TITLE
rename StringBuffer to StringBuilder

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#4626]
Java and C# both have &quot;StringBuilder&quot; as the recommended way to build strings.

**Comment by jmesserly** [comment]
At this point, I'm guessing this is Never Gonna Happen (TM) :)

**Comment by certified84** [comment]
> At this point, I'm guessing this is Never Gonna Happen (TM) :)

It's 2023 and there's still no change :(

**Comment by lrhn** [comment]
The issue was closed in 2015. What did you expect? :wink:
