### ISSUE TITLE
Would like `dart compile` to be able to stop after N errors (or even just the first one)

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#46268]
I hope this is the right tracker.

```
dart compile js .\web\main.dart
```

Will print all the errors and just keep going.  In my case I'm attempting to convert a package (wasm) to web (for fun in my case) and I don't need to see the 10k errors it's generating, just the first one. :)

```
Dart SDK version: 2.14.0-182.0.dev (dev) (Thu Jun 3 16:01:27 2021 -0700) on "windows_x64"
```
```
[√] Flutter (Channel master, 2.3.0-17.0.pre.220, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.3.0-17.0.pre.220 at C:\Users\micro\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f88966935 (16 hours ago), 2021-06-04 13:58:21 -0700
    • Engine revision 03d645e782
    • Dart version 2.14.0 (build 2.14.0-182.0.dev)
```

**Comment by eseidel** [comment]
Maybe the real problem is that it isn't just showing me the analysis errors (a dart:ffi dependency for example)?  I presumably don't have VSC configured sufficiently to tell it that the main.dart file I'm working on will be compiled to web rather than VM and thus it should show me errors like dart:ffi missing?

**Comment by eseidel** [comment]
Yeah, I think the actual problem here is that I haven't found a way to tell the analyzer "this main.dart will be compiled for js thus you should show me warnings about dart:ffi missing".

Please feel free to close if this is not useful. :)

**Comment by bkonyi** [comment]
Do you happen to have a reproduction or sample of the log output? That'll give us a better idea of what the right thing to do here is.
