### ISSUE TITLE
Migrate tool incorrectly treats result of emulated function calls as nullable

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#46263]
When running `dart migrate`, the return values of invocations of emulated function classes (classes that implement `call`) are incorrectly treated as nullable.

This only happens when calling emulated functions directly but not when using `.call(...)`, and also doesn't affect normal function types.

As a result, functions that return the result of these calls and variables that are initialized with the result of these calls are marked as nullable.

Reduced test case: https://gist.github.com/greglittlefield-wf/3b8cb36ae407a8485b1f5029db0e9c62

Screenshot of migration tool
<img width="1468" alt="Screen Shot 2021-06-04 at 12 04 41 PM" src="https://user-images.githubusercontent.com/1713967/120852561-351a8f80-c52f-11eb-854c-9023e8ed707e.png">

After running the migration and opting into null-safety, showing that the static type of the call is indeed `int` and not `int?`.
<img width="376" alt="Screen Shot 2021-06-04 at 12 23 13 PM" src="https://user-images.githubusercontent.com/1713967/120852865-a5291580-c52f-11eb-893d-1e8cae3cdcf4.png">

The function return value case can be worked around by adding `/*!*/` hints comments, but unfortunately there's nothing that can prevent the tool from updating the `var` case.

We also have many of these types of calls in our libraries (via [the invocation of OverReact UiProps classes as builders](https://github.com/Workiva/over_react#uiprops-as-a-builder)), so having to manually add the hints and update the typings on variables seems like it would be pretty tedious.

For example, 
```dart
// The over_react code:
var content = Dom.div()();

// gets migrated to:
ReactElement? content = Dom.div()();
```

Tested and reproduced in Dart SDK versions 2.13.0 and 2.14.0-176.0.dev

**Comment by greglittlefield-wf** [comment]
I took a stab at fixing this; here's the CL: https://dart-review.googlesource.com/c/sdk/+/220125

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
