### ISSUE TITLE
Record class names for CPU stack frames

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#46265]
We used to have class names recorded for CPU stack frames. Now the items in a CPU profile response from the vm service only have the method name. This makes it difficult to trace a method back to its encompassing class.

**Comment by bkonyi** [comment]
Can you please provide more information about which field is missing the details you're looking for?

**Comment by kenzieschmoll** [comment]
This is related to the 'name' field for a stack frame. For example, given:

```dart
class MyClass {
  void someMethod() {
    ...
  }
}
```

the 'name' field for a stack frame used to show `MyClass.someMethod`. Today, we see only `someMethod`.

**Comment by bkonyi** [comment]
You should be able to get the parent class name for a given function by inspecting the `owner` property of a `@Function`, which is available via the `ProfileFunction`'s `function` [property](https://pub.dev/documentation/vm_service/latest/vm_service/ProfileFunction-class.html), returned as part of the `CpuSamples` response.

I'm going to close this for now as it's WAI, but please reopen if you're unable to get the function owner information via the list of `ProfileFunction`s.
