### ISSUE TITLE
[analyzer] Language version detection does not allow script tag

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46273]
Thanks to @sgrekhov for noticing this behavior! Consider the following program (the script tag needs to be there, but it is not important which program it is invoking):

```dart
#!/bin/false
// Store as 'n004.dart'.
// @dart = 2.9

part 'n004part.dart';

void main() {}
```

```dart
// Store as 'n004part.dart'.
// @dart = 2.9

part of 'n004.dart';
```

This program is accepted by the vm, but the analyzer (commit 01fb0a6e22bd372b0c394cb8fa22a5647e606488) rejects the program with the following error message:

```
ERROR|COMPILE_TIME_ERROR|INCONSISTENT_LANGUAGE_VERSION_OVERRIDE|/usr/local/google/home/eernst/lang/dart/scratch/202106/n004.dart|5|6|15|Parts must have exactly the same language version override as the library.
```

Apparently, the script tag makes the analyzer ignore (or misread) the language version comment. However, the [language version feature spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/feature-specification.md) specifies that a script tag before the language version comment must be tolerated:

> The syntax for choosing a different language version than the default is a single source
> line consisting only of a single-line comment of the form `// @dart = 2.0` (exactly two slashes,
> the string `@dart`, an `=`, and a version string which is two decimal numerals separated by `.`)
> in the initial part of the file, prior to any language declarations. It can be preceded by a `#!` line
> or by other comments, but not by a library declaration or any other declaration.

**Comment by jcollins-g** [comment]
triaging as P1 as this is an `incorrect analysis error on edge case without workaround`

**Comment by devoncarew** [comment]
@scheglov, I assume you have context in this area?

And, for the repro case above, I assume that the use of parts is not important - it's the script tag which is disabling our detection of the language version comment?
