### ISSUE TITLE
nested map structure causes the analysis server parser (LibraryAnalyzer.analyze()) to never complete

### ISSUE THREAD

**Issue by kirill-21** [dart-lang/sdk#46278]
Typing Map<AnyType, AnyType> (especially a nested map) breaks the IDEA, it stops analyzing the code and shows "some" errors, which actually do not exists. To return IDEA to a normal state you need to close it and then open it again. The issue will disappear after such restart

![120380432-d506cc00-c329-11eb-984a-a4afca57a916](https://user-images.githubusercontent.com/63228361/121057404-e89db100-c7c7-11eb-8f01-d6b1ffabcebc.gif)

Just try to type(not copy):

```
  Map<Map<String, String>, Map<String<String>> anyname = {};
```

and the issue will appear

Flutter doctor v:
![image](https://user-images.githubusercontent.com/63228361/121057537-1125ab00-c7c8-11eb-965b-413d968fe2d7.png)

**Comment by devoncarew** [comment]
Thanks for the report! I had to try a few different ways to repro it, but might have one now. I suspect that the parser is getting into a place where it doesn't terminate:

<img width="324" alt="Screen Shot 2021-06-07 at 1 30 54 PM" src="https://user-images.githubusercontent.com/1269969/121083849-c3437f80-c794-11eb-9004-bb770d06c47b.png">

**Comment by devoncarew** [comment]
I'm trying to get a stack trace to help determine what the parser's doing here.

**Comment by devoncarew** [comment]
From some brief debugging, we may not be making progress in the 'ignoreComments' extension method (the body for that is defined in `IgnoreInfo.forDart()`).

<img width="1089" alt="Screen Shot 2021-06-07 at 1 58 10 PM" src="https://user-images.githubusercontent.com/1269969/121087376-35b65e80-c799-11eb-93dd-1f740f277a2b.png">

To repro this started with a file with a class def, and in the body of the class (after the constructor), added a comment:

```
// Map<Map<String, String>, Map<String, String>> sddf = {};
```

I then typed that code in by hand; after that the analysis server process pegs at 100% cpu and doesn't make progress - I assume stuck in parsing.

**Comment by kirill-21** [comment]
Hi again, not only the nested map causes such thing, now i faced the issue with Future<List<String>>, i guess that's an issue of all declarations with more than one sub-type
![image](https://user-images.githubusercontent.com/63228361/123507783-144be280-d674-11eb-8b95-ed168c1f060c.png)
