### ISSUE TITLE
Support --no-serve-devtools for running tests

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#46274]
A `--no-serve-devtools` flag was added in 4b96d7a09d5d8a7755f88c0192fad3c7eb57f9f6 to allow running the VM without spawning its own DevTools. This is used by VS Code which currently hosts its own version of DevTools for some additional functionality and having another DevTools address printed in the output is confusing.

The flag doesn't seem to work when running tests (I'm using `dart run test:test test/foo_test.dart` based on [this thread](https://github.com/dart-lang/pub/issues/2753)):

```
dart --enable-vm-service=0 --no-serve-devtools run test:test test/basic_test.dart
Observatory listening on http://127.0.0.1:50892/BHdTT1HoCkc=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:50892/BHdTT1HoCkc=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A50892%2FBHdTT1HoCkc%3D%2Fws
00:01 +5: All tests passed!                              
```

I tried putting the flag in other places in the command but nothing seemed to work.

@bkonyi

**Comment by bkonyi** [comment]
As discussed offline, this is WAI since `--no-serve-devtools` needs to be passed _after_ `dart run`. `dart --observe --no-serve-devtools foo.dart` is also valid (e.g., implicit `dart run`).
