### ISSUE TITLE
Properties not tree shaked when using final

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/sdk#46282]
This might not be an issue as I'm not well versed in compilation. I was testing tree shaking this evening to see if the properties in a list of const would be tree shaken. This was important for me because I've a series of packages that depend on a dataset but each individual package only use a fraction of the properties from this dataset.

Anyway, I used this snippet to test

```
void main(List<String> arguments) {
  allEntities.forEach((element) => print(element.a));
}

class Entity {
  final String a;
  final String b;

  const Entity(this.a, this.b);
}

final allEntities = [
  Entity('Bonjour', 'monde'),
  // Entity('hello', 'world'),
];
```

and I'm compiling to javascript because I've no idea how to analyze other outputs: `dart compile js bin/tree_shaking.dart`

When commenting the line `Entity('hello', 'world'),`  the result is:

```
    _lazyFinal($, "allEntities", "$get$allEntities", function() {
      return H.setRuntimeTypeInfo([new Z.Entity("Bonjour")], H.findType("JSArray<Entity>"));
    });
```

The property `String b` is correctly tree shaken. However once the line with hello world is uncommented the result becomes:

```
    _lazyFinal($, "allEntities", "$get$allEntities", function() {
      return H.setRuntimeTypeInfo([Z.Entity$("Bonjour", "monde"), Z.Entity$("hello", "world")], H.findType("JSArray<Entity>"));
    });
```

There the `b` property is not tree shaken.

Once I change the final to const, it is correctly tree shaken (the result is a bit different):

```
    C.Entity_Bonjour = new Z.Entity("Bonjour");
    C.Entity_hello = new Z.Entity("hello");
```

**Comment by cedvdb** [comment]
This is inconvenient.

I extracted the static data of one of my package to an external package assuming the properties when not used would be tree shaken because of the test above.

https://github.com/cedvdb/dart_countries

When doing this it is tree shaken:

```
void main(List<String> arguments) {
  print(countries[0].name);
  // for (var country in countries) {
  //   print(country.name);
  // }
}
```

(I cannot find washington anywhere in the compiled js

However when uncommenting the for loop, Washington and all the extra info are displayed.

**Comment by devoncarew** [comment]
Thanks for the feedback! Triaging to the web team since I suspect they're best setup to answer this (or close, if it's better covered by the doc issue you found).

**Comment by cedvdb** [comment]
@devoncarew my question wasn't targeted to web / js compilation. I used the js compilation output simply because that's the only output I can see what's been tree shaken but I assumed the tree shaking output would be the same in all cases.

**Comment by rakudrama** [comment]
The native Dart VM compiler and the dart2js compiler are completely different compilers. You can't make any assumptions about the native compiler from looking at the JavaScript output of the dart2js compiler.
