### ISSUE TITLE
meta 1.4.0 cause pub run test error

### ISSUE THREAD

**Issue by hythl0day** [dart-lang/sdk#46286]
I installed meta 1.4.0. And since then I cannot use 'pub run test'. I got this error:

```
PS G:\_dev\hetu-script> pub run test
Precompiling executable...
Failed to precompile test:test:
/C:/Users/aleph/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/analyzer-1.2.0/lib/src/error/best_practices_verifier.dart:1956:14: Error: A non-null value must be returned since the return type 'String' doesn't allow null. 
  String get displayString {
             ^
```

I checked the 'best_practices_verifier.dart' file, it has an extension on TargetKind. however according to Meta package changelog, the 1.4.0 version:

```
Introduce TargetKind.topLevelVariable that indicates that an annotation is valid on any top-level variable declaration.
```

I guess this is the reason why test compiles failed, because it got a null when encounter the new enum value.

The solution for me is to add this line in my pubspec.yaml to force my project use a earlier version of meta:

```
  meta: <=1.3.0
```

**Comment by devoncarew** [comment]
Yes, unfortunately, that version of package:analyzer isn't compatible with 1.4.0 of package:meta. One workaround is to force an earlier version of package:meta - as you're doing above. 

Note that `1.7.1` of analyzer is available now - above, it looks like 1.2.0 is being selected. You might try moving your package: test dep to a newer version to see if a newer analyzer is selected. cc @natebosch

**Comment by hythl0day** [comment]
> Yes, unfortunately, that version of package:analyzer isn't compatible with 1.4.0 of package:meta. One workaround is to force an earlier version of package:meta - as you're doing above.
> 
> Note that `1.7.1` of analyzer is available now - above, it looks like 1.2.0 is being selected. You might try moving your package: test dep to a newer version to see if a newer analyzer is selected. cc @natebosch

My Dart SDK is 2.13 and I tried change the test package to test: ^1.17.5, I still get the problem, I'm not sure why the it wouldn't use 1.7.1 version of analyzer package.

**Comment by devoncarew** [comment]
You might try adding an explicit dep for analyzer 1.7.1 in your pubspec and then running 'pub get'. If the version solve fails, the error message will tell you which other package is forcing an older version of analyzer.

**Comment by hythl0day** [comment]
> You might try adding an explicit dep for analyzer 1.7.1 in your pubspec and then running 'pub get'. If the version solve fails, the error message will tell you which other package is forcing an older version of analyzer.

Okay, I added explicit dep of analyzer 1.7.0 and meta 1.4.0 and the problem solved. (I do not want to add analyzer because I do not use it directly)
analyzer 1.7.1 is reverted some changes also related to incompability.

**Comment by devoncarew** [comment]
Yeah, an explicit dep would just be a workaround, but might tell you which other package was selected an older package:analyzer.
