### ISSUE TITLE
firstTokenAfterCommentAndMetadata issue with field?

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#46299]
With analyzer-1.7.0 I face a strange behaviour but I'm not sure if this behaviour is intented or not.

When visiting the AST of the following code

```dart
class A {
  ///
  int? i1;
}
```

`node.firstTokenAfterCommentAndMetadata` doesn't point to the same token depending on the node evaluated :

```
node(2:3) firstToken(3:3) FieldDeclarationImpl
node(3:8) firstToken(3:8) VariableDeclarationImpl
```

I expected the 2 invocation would have pointed to `int?`.

@bwilkerson  Is it a bug or is it intended ?

**Comment by bwilkerson** [comment]
That's intended. The `VariableDeclaration` is a child of the `FieldDeclaration`, potentially one of many as would be the case with `int? i1, i2, i3;`. The `VariableDeclaration` doesn't include the type annotation because the type annotation can be shared by multiple variables.
