### ISSUE TITLE
Failures on [io/socket] When socket connection fails report stacktrace of the callsite.

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#46304]
There are new test failures on [[io/socket] When socket connection fails report stacktrace of the callsite.](https://github.com/dart-lang/sdk/commit/80749188ca1670ba5759730fd1f533413318b891).

The tests
```
standalone_2/io/socket_connect_stacktrace_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-dwarf-linux-product-x64
```

This test does a string search for `"main "` in the stacktrace, which fails with non-symbolic stack traces. We could either try to extend this test to handle that case, or write a non-symbolic specific version that always adds `--dwarf-stack-traces` similar to `vm/dart/casual_stacks/async_throws_stack_lazy_non_symbolic_test.dart` and allow this one to continue to fail on the non-symbolic CI bot.

/cc @aam

**Comment by aam** [comment]
thank you @sstrickl for the analysis! non-symbolic stack traces looks like a pain to deal with - it seems one need to produce debug .so file at gen_snapshot time, then at runtime decode stack trace using it.
