### ISSUE TITLE
[CP][stable channel] Fix OOM VM test (transferable_throws_oom_test crashing after upgrade from Ubuntu 16 -> 18)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#46300]
commit(s) to merge: f827c533156578aae356ef1b75f24a43107faca0

merge instructions: clean merge 

What is the issue: Brief description of the problem

Recent upgrade to bionic has caused an OOM test to start failing because the OS now does not result in an error from malloc when allocating 1 TB and the test relies on that. The test was changed to allocate 1 PB of memory.

This changes makes the test allocate 1 PB of memory and that triggers a failure in malloc.

Why cherrypick: The stable release bots are showing test result failures and fixing this will enable us to look for real failures as opposed to this synthetic test failure.

Risk: Very low, it is just a change to the test

Link to original issue(s):  https://github.com/dart-lang/sdk/issues/46167

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @a-siva @aam

**Comment by franklinyow** [comment]
Approved in SCRUM
CC: @kf6gpe change in test only

**Comment by athomas** [comment]
Merged to stable in 516eb3b05c252ef3d34255d06700c1f09f7f4502 (2.13.3).
