### ISSUE TITLE
The argument type 'Iterable<T>' can't be assigned to the parameter type 'Iterable<T>'

### ISSUE THREAD

**Issue by DenisBarzanov** [dart-lang/sdk#46311]
extension ListExtension<T> on List<T> {
      Iterable<T> insertInBetween<T>(T item) {
        // Iterable<T> iterable = this;
        final iterable = Iterable.generate(this.length, (i) => this[i]);
        return _intersperse<T>(item, iterable).toList();
                                      ^^^^^^^

      }
    }
    
    Iterable<T> _intersperse<T>(T element, Iterable<T> iterable) sync* {
      final iterator = iterable.iterator;
      if (iterator.moveNext()) {
        yield iterator.current;
        while (iterator.moveNext()) {
          yield element;
          yield iterator.current;
        }
      }
    }

Error: 

    The argument type 'Iterable<T>' can't be assigned to the parameter type 'Iterable<T>'.dart(argument_type_not_assignable)

* Dart SDK Version (`dart --version`)
dart: `Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "macos_x64"`

**Comment by julemand101** [comment]
Not sure why it cannot figure this out automatically but if I change the following in your extension:
```dart
    final iterable = Iterable.generate(this.length, (i) => this[i]);
```
Into:
```dart
    final iterable = Iterable.generate(this.length, (i) => this[i] as T);
```
The error goes away on my machine. But I am not sure why Dart cannot automatically figure out the return type of `this[]` in this case.

**Comment by eernstg** [comment]
You probably don't want to make `insertInBetween` generic: Just change `insertInBetween<T>` to `insertInBetween`, and then there's only one type variable named `T`.

**Comment by mraleph** [comment]
@DenisBarzanov notice that you have two different `T`s. 

/cc @bwilkerson @scheglov I would expect analyzer could provide some disambiguation when there are two type parameters which have the same name but are different.

**Comment by eernstg** [comment]
https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html will actually detect it (in particular, dart-pad shows an `info` about it).
