### ISSUE TITLE
Null safety inference issue

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#46325]
```dart

      if (widget.note!.devices != null)
        ...widget.note!.devices
            .where((u) => u != widget.contextDeviceId)
            .map<Widget>((u) => 

```

This gives the error `The method 'where' can't be unconditionally invoked because the receiver can be 'null'.
Try making the call conditional (using '?.') or adding a null check to the target ('!').`

Why after doing a null check above does this require another `!` on `devices`?

**Comment by eernstg** [comment]
The expression `widget.note!.devices` invokes a couple of members, but the last step is the invocation of a getter named `devices`. That getter could be implicitly induced by a variable declaration, or it could be an plain getter declaration, and it can be overridden in a subclass of the statically known type of `widget.note!`. In any case, it is not safe to assume that you will get the same object twice when you call a given getter twice. (That goes for `note` as well, so you may even be calling `devices` on two different receivers).

The typical solution is to store the result of a nontrivial getter invocation in a local variable and reuse it:

```dart
  var devices = widget.note!.devices;
      if (devices != null)
        ...devices
            .where((u) => u != widget.contextDeviceId)
            .map<Widget>((u) => 
```

There is a lot of discussion about how to enable promotion for instance variables here: https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion.

**Comment by eernstg** [comment]
I'll close this issue because it doesn't report on anything broken, and the discussion about possible enhancements that would allow promotion of instance variables in some cases is taken elsewhere.
