### ISSUE TITLE
Null safety migration weirdness 

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#46323]
Migration tool seems to have got confused applying. I did make some alterations adding hints using the web IDE. I'm manually fixing it all at the moment, it's affected multiple files.

Example:

```dart
    vm.publishToPubSub(PublishToPubSubAction(
        uid: _ac!count.uid,
        message: AccountNewMessage((b) => b
          ..account = _ac!count.toBuilder()
          ..uid = _ac!count.uid),
        topic: PubSubTopics.account_new));

    var note = Note.create(
        priority: Note.PRIORITY_MEDIUM,
        uids: [_ac!count.uid],
        staffAuthUid: vm.staffProfile.au!thUid,
        staffInitials: vm.staffProfile.ini!tials,
```

**Comment by jimmyff** [comment]
Another weird example:
```dart 
        transformDoc: (d) =>
            CloudPhotoDetails.fromJsonMap(firestoreSerializers, d.d as Map<String, dynamic>ata()),
```
It's added typing mid method call

**Comment by jimmyff** [comment]
Here is another example, It didn't action the hint, also it added late to the state class definition:
```dart
class PhotosPart extends StatefulWidget {
  final String?/*!*/ uid;

  PhotosPart(this.uid);

  @override
  _PhotosPartState createState() => _PhotosPartState();
}

class _PhotosPartState extends State<PhotosPart> late {
```

In total there were 370+ errors, I should probably roll back and try again as I've done this with a few other projects without issue but I'm just going to keep going through them fixing manually. The only thing I did different this time was use the hints in the web IDE.

**Comment by jimmyff** [comment]
(I'm not looking for a solution to this, I just wanted to flag it to the necessary people. happy for this issue to be closed)

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
