### ISSUE TITLE
Analyzer mistakenly assumes static access over cascade.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#46324]
Example:
```dart
void main() {
  List..toString().log;
  double..infinity.log;
}
extension on Object? {
  void get log {
    print(this);
  }
}
```

In the front-end (dart2js in Dartpad) this gives one error, that `infinity` is not a member of `Type`.

In the analyzer (also in Dartpad) I get two errors:
```
line 2 • Instance member 'toString' can't be accessed using static access. (view docs)
line 3 • The getter 'infinity' isn't defined for the type 'Type'. (view docs)
```

The second error shows that the analyzer does recognize that the member access is on the `Type` object, not static namespace of the class.
The first error suggests that it gets confused about `toString` (likely all `Object` members) in particular.

I believe the first error from the analyzer is a bug.

**Comment by srawlins** [comment]
@eernstg I think you just finalized a change to rules with cascade on a Type. Is the analyzer now reporting an error correctly? Is this bug no longer a bug?

**Comment by eernstg** [comment]
At the language meeting today we just discussed the treatment of cascades where the receiver is a type literal, and we agreed that it should be a compile-time error:

```dart
void main() {
  int..toString(); // Error.
  List<String>?..toString(); // Error.
  int?..toString(); // Error.
  int..extensionMethodOnType(); // Error.
}
```

The work on implementing these newly specified errors will not start before Q4.

However, until then we should keep the analyzer unchanged (it currently reports an error for these constructs saying "can't be accessed using static access"), such that there will be as little breakage as possible.

The funny thing is that the analyzer actually says "The method copyRange isn't defined for the type 'Type'" when I try to do the opposite:

```dart
void main() {
  List..copyRange<int>([], 0, []); // Error.
}
```

Anyway, we want an error in both cases: `<typeLiteral> '..'`, `<typeLiteral> '?..'` and `<typeLiteral> '?.'` should all become errors, such that we can consistently say that a static access uses `'.'` and only `'.'`, and all the others are exclusively used with a receiver which is evaluated to an object.

So the behavior of the analyzer is perfect! (we just need to change the error message ;-).

@lrhn, do you agree that the best way ahead here would be to close this issue? Then we'll create new issues based on the new rules when they are ready. Please reopen if you disagree.
