### ISSUE TITLE
co19[_2]/src/LibTest/io/Link/watch_A01_t01 tests seems to be invalid

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#46338]
The tests are written with assumption that retargeting watched link triggers file watch notification when watcher is set up on the link itself(https://github.com/dart-lang/co19/blob/master/LibTest/io/Link/watch_A01_t01.dart#L31) , which it doesn't. So the tests is failing on all platforms.

**Comment by mraleph** [comment]
@aam maybe this should be filed in co19 repo?

**Comment by aam** [comment]
Okay, closed in favor of https://github.com/dart-lang/co19/issues/1100
