### ISSUE TITLE
Map.cast does not check for narrower key type on lookup

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#46336]
It's not clear to me from the docs what the intended behaviour is

https://api.dart.dev/stable/2.10.4/dart-core/Map/cast.html

but I found it surprising that

```dart
{'one': 1}.cast<int, int>()['one']
```

succeeds in looking up a `String` key in a `Map<int, int>`; I was expecting it to either throw or return nothing.

**Comment by lrhn** [comment]
I think the documentation is saying that the lookup should throw.

**Comment by davidmorgan** [comment]
Would it be worth clarifying in the docs?

Specifically

_If any operation exposes a non-RK key or non-RV value, the operation will throw instead._

could be amended to cover this case, e.g.

_If any operation exposes a non-RK key or non-RV value, the operation will throw instead. Map lookup is an exception to this: because `operator[]` takes `Object?`, a non-RK key is allowed to return an RV value if one is present in the underlying `Map`._

Thanks.

**Comment by lrhn** [comment]
I'll look into documenting that methods accepting `Object?` do not check their argument, and passes it through unchanged.
This applies to multiple members across the different collections.

**Comment by davidmorgan** [comment]
Sounds good, thanks.
