### ISSUE TITLE
flutter_test from flutter sdk does not support meta 1.4.0

### ISSUE THREAD

**Issue by abhishek-mesky** [dart-lang/sdk#46345]
Because every version of flutter_test from SDK depends on meta 1.3.0 and my_app depends on meta ^1.4.0, flutter_test from SDK is forbidden.
So, because my_app depends on flutter_test any from SDK, version solving failed.
pub get failed (1; So, because my_app depends on flutter_test any from SDK, version solving failed.)

**Comment by mraleph** [comment]
You need to align your meta constraint with `flutter_test`.
