### ISSUE TITLE
Unresolved references in extension doc comments get flagged as errors when extended type is nullable

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#46343]
The following program:
```dart
/// [Foo]
extension on int? {}

main() {}
```
Is accepted by the CFE but rejected by the analyzer.  The analyzer's error message is:
```
  error • test.dart:1:6 • The property 'Foo' can't be unconditionally accessed because the receiver can be 'null'. Try making the access conditional (using '?.') or adding a null check to the
          target ('!'). • unchecked_use_of_nullable_value
```
Removing the `?` from the line `extension on int? {}` works around the problem.  Changing `Foo` to an identifier that's in scope (e.g. `double`) also works around the problem.

**Comment by srawlins** [comment]
What a bizarre bug. I have to imagine easy though.

**Comment by srawlins** [comment]
This seems to be resolved.
