### ISSUE TITLE
could dart create private constructor ?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#46341]
such as Student can not be create by constructor, but can be a static method:
```dart
class Student {
  String? name;
  private Student(this.name);  // use _Student(this.name) also error

  static newInstance(String name) {
    return Student(name);
  }
}
```

then user use Student('sss') to create Student will be error, just can use newInstance

**Comment by eernstg** [comment]
You just need to make the second part of a constructor name private, e.g.:

```dart
class Student {
  String? name;
  private Student._(this.name);  // This is a private constructor.
  ...
}
```

**Comment by eernstg** [comment]
@Silentdoer, I'll close this issue because private constructors exist, and nothing in this issue indicates that they aren't working as intended. Please create a new issue if you do encounter something that doesn't work.

**Comment by Silentdoer** [comment]
> @Silentdoer, I'll close this issue because private constructors exist, and nothing in this issue indicates that they aren't working as intended. Please create a new issue if you do encounter something that doesn't work.

thank you
