### ISSUE TITLE
How can i invoke isolate by receive one elements in stream?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#46342]
```dart
import 'dart:io';
import 'dart:isolate';

void main(List<String> args) async {
  var receivePort = ReceivePort();
  await Isolate.spawn(handler, receivePort.sendPort);

  var sendPort = await receivePort.first as SendPort;

  sendPort.send('kkkk');
  sendPort.send('bbbb');
  sendPort.send('uuu');

  sleep(Duration(seconds: 3));
}

void handler(SendPort sendPort) async {
  var receivePort = ReceivePort();
  sendPort.send(receivePort.sendPort);

  var list = List<dynamic>.empty(growable: true);
  while (true) {
    if (list.isNotEmpty) {
      print('do some thing, and will eat element in list');
      list.removeLast();
    } else {
      //if (receivePort.isEmpty) {
        sendPort.send(aMessageToOuter);
      //}
      // **HERE**: Unhandled exception: Bad state: Stream has already been listened to.
      // why can not continue await element from receivePort?
      await for (var msg in receivePort) {
        print(msg);
        list.add(msg);
        // break for other logic processing
        break;
      }
    }
  }
}

```

or maybe question: how to reset ReceivePort and listen once again?
or: just await one element from ReceivePort and can await next element in two code scope

**Comment by Silentdoer** [comment]
my mean is than, await receivePort 
's element can be take one then break, then do something, then continue to await next element?

**Comment by mraleph** [comment]
> my mean is than, await receivePort's element can be take one then break, then do something, then continue to await next element?

`ReceivePort` is a `Stream`, so you can do 

```
await for (var msg in port) {
  // ...
}
```

**Comment by Silentdoer** [comment]
> > my mean is than, await receivePort's element can be take one then break, then do something, then continue to await next element?
> 
> `ReceivePort` is a `Stream`, so you can do
> 
> ```
> await for (var msg in port) {
>   // ...
> }
> ```

but when i break this, it could reawait the stream, why can not reuse stream?

**Comment by mraleph** [comment]
Because it is is a single-subscription stream. You can make a broadcast stream out of it if you want to listen multiple times. 

Read https://api.dart.dev/stable/2.13.3/dart-async/Stream-class.html for more information.
