### ISSUE TITLE
[CP][stable channel] [ddc] Fix web compiler crash

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#46358]
**commit(s) to merge**: 303f96d3f38c3455c0e6a4a33c3eded0763464f0

**merge instructions**: Patch https://dart-review.googlesource.com/c/sdk/+/203293 (merge had conflicts, CL resolves them).

**What is the issue**: Fixes bug where DDC would crash when compiling in sound null safety a type that contains a FutureOr<T> when T has not been bound and we have no nullability information for the FutureOr.

**What is the fix**: DDC did not expect to ever see a FutureOr<T> type tagged with unspecified nullability come from the CFE and crashed if it did. It turns out this is possible and correct in some circumstances. We now handle that case and compile the type correctly.

**Why cherrypick**: The compiler crash blocks development on the web if your application contains this specific pattern. It appears in the [either_dart](https://pub.dev/packages/either_dart) package that has been migrated to null safety so consumers of the package that also migrate their package will be broken without this fix.

**Risk**: Low, the change targets a very specific type construction.

**Link to original  issue(s)**: https://github.com/flutter/flutter/issues/82838

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @sigmundch

**Comment by nshahan** [comment]
Depending on the selected branch point for the 2.14 beta we might need to cherry pick into beta as well. 303f96d should merge cleanly into the beta branch though.

**Comment by athomas** [comment]
@nshahan This will not be in the beta branch, but it will be picked up for 2.14 stable (there'll be another branchout for that later).

**Comment by vsmenon** [comment]
lgtm

**Comment by a-siva** [comment]
approved for 2.14 beta
conditionally approved for 2.13 stable (if a hotfix is created for other reasons)

**Comment by athomas** [comment]
Merged to beta in bd5cd8a65baf2cdad8f5ba9b350c4e912d2a6cdf (`2.14.0-188.3.beta`). Issue will remain open until merged to stable.

**Comment by athomas** [comment]
Merged to stable in 065872e802209ffa97aa3fad204758830b6100a0 (2.13.4).
