### ISSUE TITLE
Dart Migration Error

### ISSUE THREAD

**Issue by VenkateshSiddani** [dart-lang/sdk#46368]
**Flutter Version -** 
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (3 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node at offset 129337 in /Users/773777/Desktop/Venky/WorkSpace/WorkingCode_AID/CTS_GIT/Stable_2.2.1/AID/aid/lib/Master/ResourceMaster/ResourceMasterView.dart (Singleton?.profile)

#0      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:3017:47)
#1      EdgeBuilder.visitPropertyAccess (package:nnbd_migration/src/edge_builder.dart:1451:12)
#2      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8314:50)
#3      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#4      EdgeBuilder._handlePropertyAccess (package:nnbd_migration/src/edge_builder.dart:2981:20)
#5      EdgeBuilder.visitPropertyAccess (package:nnbd_migration/src/edge_builder.dart:1451:12)
#6      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8314:50)
#7      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#8      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:486:22)
#9      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:951:50)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#11     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#12     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#13     EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1154:5)
#14     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6054:15)
#15     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#16     EdgeBuilder.visitConditionalExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:688:20)
#17     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#18     EdgeBuilder.visitConditionalExpression (package:nnbd_migration/src/edge_builder.dart:667:26)
#19     ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2232:15)
#20     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#21     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#22     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#23     EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1154:5)
#24     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6054:15)
#25     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#26     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#27     EdgeBuilder._handleCollectionElement (package:nnbd_migration/src/edge_builder.dart:2438:14)
#28     ListMixin.forEach (dart:collection/list.dart:86:13)
#29     EdgeBuilder.visitListLiteral (package:nnbd_migration/src/edge_builder.dart:1224:21)
#30     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6675:50)
#31     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#32     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#33     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#34     EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1154:5)
#35     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6054:15)
#36     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#37     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#38     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#39     EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1154:5)
#40     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6054:15)
#41     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#42     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#43     EdgeBuilder._handleInvocationArguments (package:nnbd_migration/src/edge_builder.dart:2937:7)
#44     EdgeBuilder.visitInstanceCreationExpression (package:nnbd_migration/src/edge_builder.dart:1154:5)
#45     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6054:15)
#46     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#47     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2331:20)
#48     EdgeBuilder.visitReturnStatement (package:nnbd_migration/src/edge_builder.dart:1498:7)
#49     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8482:50)
#50     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#51     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#52     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:521:40)
#53     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#54     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1065:50)
#55     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#56     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#57     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:326:46)
#58     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#59     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1020:50)
#60     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#61     EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2490:7)
#62     EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#63     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6942:50)
#64     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#65     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#66     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#67     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#68     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#69     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#70     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#71     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#72     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#73     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#74     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#75     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#76     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#77     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#78     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#79     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#80     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#81     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#82     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#83     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#84     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#85     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#86     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#87     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
