### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by oneQiu** [dart-lang/sdk#46365]
No Error,But can't be reload by ctrl+s;
![image](https://user-images.githubusercontent.com/50658231/122030341-4782ac00-ce00-11eb-9053-73ce45ed44af.png)
![image](https://user-images.githubusercontent.com/50658231/122030361-4b163300-ce00-11eb-8870-101784ab1a4c.png)

## 版本信息

- `IDEA AI-202.7660.26.42.7351085`
- `2.13.1`
- `AI-202.7660.26.42.7351085, JRE 11.0.8+10-b944.6842174x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1536x864`

**Comment by mraleph** [comment]
Does view issues not reveal any issues?

**Comment by devoncarew** [comment]
I believe this is working as intended; you should be able to see the analysis errors in your application by switching to the 'Dart Analysis' tab.
