### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by kivoon** [dart-lang/sdk#46366]
## Version information

- `IDEA AI-201.8743.12.41.6953283`
- `2.13.1`
- `AI-201.8743.12.41.6953283, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1920x1080`

**Comment by mraleph** [comment]
Not actionable.
