### ISSUE TITLE
Errors while trying to roll my own dart:html

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#46360]
I have built a package that fully transpiles, or tries to, WebIDLs specification to Dart using package:js.  

https://pub.dev/packages/js_bindings

It generate classes, @anonymous classes for dictionary and mixins when needed.  
The builder also add MDN documentation to classes, properties etc.  
It got a pretty nice generated code: take a look at the [MediaStream spec](https://github.com/jodinathan/js_bindings/blob/main/lib/bindings/mediacapture_streams.dart)

Here are the [254 specs transpiled](https://github.com/jodinathan/js_bindings/tree/main/lib/bindings) to Dart.

However, I am having trouble to make this work.  
One of the errors: ```The superclass, 'HTMLElement', has no unnamed constructor that takes no arguments.```.  
However, HTMLElement has an [unnamed external factory constructor with no arguments](https://github.com/jodinathan/js_bindings/blob/dcda2b48f15cb855b1e4ce9905664faf6baceb6e/lib/bindings/html.dart#L209).  
Is this expected?  

I am guessing that the errors can have a different source from what the output says, so I wonder if you could reproduce the errors?  
To reproduce you only have to import the package and use anything from it, like the simple example in the README.

This tracker is for issues related to:
* dart2js

**Comment by mraleph** [comment]
> Is this expected?

Yes, factories are different from normal constructors because they can return anything that is a subtype of an enclosing class, so they are not suitable as super constructors. Not having a public constructor and having a factory constructor is actually a common way to prevent subclassing in Dart.

Consider: 

```dart
class A {
  factory A() {
    return _AImpl();
  }
}

class _AImpl implements A { 
}

class B extends A {
  // Invalid. No super constructor for A is available to delegate to.
  // Can't really construct superclass A.
  B() : A(); 
}
```

**Comment by jodinathan** [comment]
@mraleph does this mean we can't have inheritance with js interop? =\

**Comment by mraleph** [comment]
> @mraleph does this mean we can't have inheritance with js interop? =\

I am hardly a JS interop expert. Maybe @srujzs can shed some light on the problems you are hitting.

**Comment by srujzs** [comment]
You can still have `external` generative constructors in `JS()` classes. You just can't have them in ones that are tagged `@anonymous` (because there is no class binding to call a constructor for).

**Comment by jodinathan** [comment]
from my tests with `staticInterop` it seems you can't use `extends` and `with` in js interop, only `implements` works.  

the package [js_bindings](https://pub.dev/packages/js_bindings/versions/0.0.4-dev) is fixed in the dev release by only using `implements`

**Comment by jodinathan** [comment]
from my tests with `staticInterop` it seems you can't use `extends` and `with` in js interop, only `implements` works.  

the package [js_bindings](https://pub.dev/packages/js_bindings/versions/0.0.4-dev) is fixed in the dev release by only using `implements`

**Comment by srujzs** [comment]
FYI Jonathan, I've noticed you're using non-`external` members in the `extension`s e.g. https://github.com/jodinathan/js_bindings/blob/main/lib/bindings/ambient_light.dart. You could replace those methods with `external` members as they're currently equivalent to what you have.

**Comment by jodinathan** [comment]
@srujzs I ended up making more use of js_util as now there is no need to use `promiseToFuture` neither `allowInterop`. Also added operators `[]` and `[]=`

**Comment by jodinathan** [comment]
@srujzs but I will try the external members in the extension any time for the sake of better reading
