### ISSUE TITLE
Analyzer reports an error for wrong const initialization in a wrong place

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#46371]
The following [co19 test](https://github.com/dart-lang/co19/blob/master/Language/Expressions/Constants/top_level_function_t01.dart) start failing. The test is

```dart
const a = () {};
//        ^
// [analyzer] unspecified
// [cfe] unspecified

main() {
  try {
    print(a);
  } catch (x) {}
}
```
Analyzer produces
```
--- Command "dart2analyzer" (took 39ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=json --no-hints /b/s/w/ir/cache/builder/sdk/tests/co19/src/Language/Expressions/Constants/top_level_function_t01.dart

static error failures:
- Missing expected unspecified error at line 16, column 11, length 1.

- Unexpected error at line 26, column 4294966470, length 26: COMPILE_TIME_ERROR.CONST_INITIALIZED_WITH_NON_CONSTANT_VALUE

--- Re-run this test:
python3 tools/test.py -n analyzer-asserts-strong-linux co19/Language/Expressions/Constants/top_level_function_t01
```
Please note column number `4294966470`. In fact, line 26 is the last empty line of this test

Issue is reproducible on the edge version of the analyzer. There were no this issue at least on Jun 11

`Dart SDK version: 2.14.0-edge.fed3cef63a279e1232c00424c22f6b0ba7a4f558 (be) (Tue Jun 15 14:08:52 2021 +0000) on "linux_x64"`

**Comment by sgrekhov** [comment]
cc @scheglov

**Comment by scheglov** [comment]
This is an issue with non-serializable expressions - here a function expression.
We don't set offsets for such expressions, so they stay `-1` and cause such too big offset.
I plan to replace it with a synthetic function expression that has correct offset and length.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/204001
