### ISSUE TITLE
print() without a newline character

### ISSUE THREAD

**Issue by VarunS2002** [dart-lang/sdk#46383]
The problem:
In a few cases, `print()` shouldn't add a newline character like when it has to be printed char by char.
Although this can be done using `stdout.write()`, this breaks support for Dart2JS and only supports Native.
This is not ideal. 
Example that needs print without a newline character:  [First method in this file](https://github.com/VarunS2002/Dart-sudoku_solver_generator/blob/main/sudoku_solver_generator/lib/src/sudoku_utilities_base.dart)

Suggested solutions:
1. Add a boolean named parameter so the signature will be: `void print(Object? object, {bool newLine = true})`
    - So using it as `print('D2JS', newLine=false);` won't add a newline character to the end.
2. Add a new function like `void printWithoutNewLine(Object? object)` 
    - Since changing the original `print` to `println` breaks existing code.
3. Add an optional parameter so the signature will be: `void print(Object? object, [String end = '\n'])`
    - This is the same as the `print` function in Python.
    - End parameter adds the given string to the end of the object to print.
    - So using it as `print('D2JS', end='');` won't add a newline character to the end.

**Comment by VarunS2002** [comment]
I have temporarily implemented the `StringBuffer` method, however that breaks support for animating the console by printing char by char with a delay of 25ms.
Can that be done in both JS and Native using the same code (Zones or something else) yet?

**Comment by lrhn** [comment]
You'd need to use different code for different platforms, likely with conditional imports to select between them.

Consider the following files:
```dart
// vc-io.dart
import "dart:io";

void write(String string, {bool newline = false) {
  if (newline && !(string.endsWith('\n') || string.endsWith('\r')) {
    stdio.writeln(string);
  } else {
    stdio.write(string);
  }
}
```
```dart
import "dart:js" as js;
import "dart:convert" show LineSplitter;

final _consoleLines = <List<String>>[];
var _hasNL = true; // Whether the last line in _buffer is complete.
final _console = js.context["console"];
void write(String string, {bool newline = false}) {
  if (string.isNotEmpty) {
    for (var part in LineSplitter.split(string)) {
      if (_hasNL) {
        _consoleLines.add([part]);
      } else {
        _consoleLines.last[0] += part;
        _hasNL = true;
      }
    }
    _hasNL = newline || string.endsWith('\n') || string.endsWith('\r');
    _console.callMethod("clear");
    for (var line in _consoleLines) {
      _console.callMethod("log", line);
    }
  } else if (newline) {
    _hasNL = true;
  }
}
```
and then a wrapper library exposing the one supported by the current platform:
```dart
// vc.dart
import "dart:async";
import "vc-io.dart" 
   if (dart.library.js) "vc-js.dart" // Use this if JS is available.
   as vc;

/// Captures calls to [print] in the [body] and forwards them to [writeln].
void capturePrint(void Function() body) {
  runZoned(body, zoneSpecification: ZoneSpecification(print: (s, p, z, arg) {
    writeln(arg);
  }));
}

/// Writes [string] to the console without adding a newline.
void write(String string) {
  vc.write(string);
}

/// Writes to the console, and adds a newline if the string doesn't end in one.
void writeln(String string) {
 vc.write(string, newline: true);
}
```

As you can see, it's not that complicated, but it requires cooperation with the code doing the writing.
It's not functionality we'd add to the platform. The `print` statement is not intended for general *controlled* output, but is primarily for debugging and simple sequential output.

**Comment by VarunS2002** [comment]
@lrhn 
You see [pub.dev](https://pub.dev/) checks compatibility of a package with runtime js and tags it as not-compatible with runtime js and also deducts 10 points if you import dart:io.

![image](https://user-images.githubusercontent.com/30069380/122234971-ea0f5d80-ceda-11eb-9aea-98111a22897d.png)
and

![image](https://user-images.githubusercontent.com/30069380/122235163-19be6580-cedb-11eb-904f-ca3e012b6191.png)

Assuming this code works as intended (I haven't tried yet), will pub.dev still label my package as not compatible with runtime js even though dart:io is imported conditionally?
If true, this should be a issue linked to [pub.dev issues](https://github.com/dart-lang/pub-dev) in my opinion.
Additionally, to prevent publishing and then realising that a developer broke support for runtime js (basically what I did), is there a linter rule in [pedantic](https://pub.dev/packages/pedantic) like `support_runtime_js` to check for this?
If not I would like to create a feature request for that too.
Thanks.

**Comment by lrhn** [comment]
You don't have to play that point game ... but if you do want to, you can have a default:
```dart
// vc-none.js

void write(String string, {bool newline = false}) {
  throw UnsupportedError("Need either dart:io or dart:js to work");
}
```
and then import as:
```dart
import "vc-none.dart"
  if (dart.library.js) "vc-js.dart"
  if (dart.library.io) "vc-io.dart"
  as vc;
```
If you ever find yourself on a platform without both of `dart:io` and `dart:js`, the code will break. At that point, I hope you'll have another platform-dependent approach to use as a third option.

**Comment by lrhn** [comment]
Probably not severe. If you always write your conditional imports as "general default case" first, platform specific version later, then you're safe. Even if your general default cast always throws, it will still *compile* on all platforms.

I'm not aware of any lints helping you with this, and see none in https://dart-lang.github.io/linter/lints/

**Comment by VarunS2002** [comment]
@lrhn 
Thanks you so much for your help! 
Shall I close this?

**Comment by lrhn** [comment]
We can keep it open as a request for a non-newline-adding print, but I don't see that as a likely outcome, so let's close it now.

**Comment by VarunS2002** [comment]
@lrhn 
Update:
Turns out [this package](https://pub.dev/packages/pana) is the official way [pub.dev](https://pub.dev/) evaluates packages and it  can be run natively in local directories.
A small section of the console output:

![image](https://user-images.githubusercontent.com/30069380/122374367-f39ed100-cf7f-11eb-8ff1-524e3ece1d91.png)
