### ISSUE TITLE
Analyzer crash: NoSuchMethodError: The getter 'node' was called on null.

### ISSUE THREAD

**Issue by keanuyaoo** [dart-lang/sdk#46394]
This tracker is for issues related to:  Analyzer
Windows 10, Dart v1.13.3

ClassName?.staticMethod can be compiled and running well, but may cause Analyzer crash;   This improper grammar make tools 
different response.

**Comment by keertip** [comment]
@keanuyaoo, please add repro steps so we can look into it.
