### ISSUE TITLE
Failures caused by wrong tests with Symbol constructor accepts arbitrary string as argument

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#46395]
The tests

corelib/symbol_test/02
corelib/symbol_test/03
language/vm/symbols_test/03

needs updating.

/cc @eernstg

**Comment by eernstg** [comment]
`tests/corelib/symbol_test.dart` was updated in 166d474257c3a4999d6374c63b06ebd05e486343 and `tests/language/vm/symbols_test.dart` was updated 9371fd9fc8057201a6862e4a2726c8fffcea3afa.

I'll close the issue because it's only reporting on test faults, and adjust the area accordingly.
