### ISSUE TITLE
Analysis server not recognizing non-function typedefs for autocompletion and location with IDEs

### ISSUE THREAD

**Issue by RandalSchwartz** [dart-lang/sdk#46409]
If I have the file
```
class Dismissed {}

typedef Funky = void Function();

typedef Triple = double;
```

and in a different file that has not yet imported the file, I can begin to type `Dismissed` or `Funky`, and it will correctly complete the word, as well as auto-import the file.  However, `Triple` is not recognized, and not offered for auto-import.  Once imported, `Triple` is recognized for completion.

Chatted with @DanTup and he sent me here.

**Comment by DanTup** [comment]
I've started work on a possible fix at https://dart-review.googlesource.com/c/sdk/+/204403/.
