### ISSUE TITLE
Can't use custom structs in Dart 2.10.3

### ISSUE THREAD

**Issue by pak3nuh** [dart-lang/sdk#46410]
This tracker is for issues related to:
* Analyzer
* Dart core libraries ("dart:ffi")

I'm trying to use a rust library through FFI but can't lookup functions that use custom made Struct types in my code due to an analyzer error.

```dart
class InteractionStruct extends Struct {
  Pointer<Void> pact;
  Pointer<Void> interaction;
}

typedef _createInteractionNative = InteractionStruct Function(Pointer, Pointer<Utf8>); 
typedef _createInteractionDart = InteractionStruct Function(Pointer, Pointer<Utf8>);

void createInteraction(DynamicLibrary lib) {
  final createFunctionNative = lib.lookup<NativeFunction<_createInteractionNative>>('new_interaction');
  // the analyzer fails with
  // Expected type 'NativeFunction<InteractionStruct Function(Pointer<NativeType>, Pointer<Utf8>)>' to be a valid and instantiated subtype of 'NativeType'
  final createFunctionDart = createFunctionNative.asFunction<_createInteractionDart>();
...
}
```
I know the FFI is still beta in this version, but by the SDK samples this should work.

### Dart version
Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "linux_x64"

**Comment by mraleph** [comment]
2.10 does not have support for struct by value in FFI. This support has shipped in 2.12.

Please try upgrading to a newer stable release.
