### ISSUE TITLE
NoSuchMethodError: The method '[]' was called on null. Receiver: null Tried calling: []()

### ISSUE THREAD

**Issue by jxnc12yangb** [dart-lang/sdk#46415]
Hi,
I have a error, please tell me what happens with this error ，here is the error message:

NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: [] ()

I don't know when it will call [] ()
Show me a sample

**Comment by lrhn** [comment]
You are doing `something[index]`, which is most likely a list or map lookup, but can be calling the `[]` operator on some other class.
The `something` expression evaluates to `null`, which is why you get an error trying to call the `[]` operator on `null`.
