### ISSUE TITLE
`dart --help --verbose` prints to stderr instead of to stdout

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#46412]
`dart --help`, `dart help`, `dart analyze --help`, and `dart help analyze` all print to stdout, but `dart --help --verbose` prints everything to stderr instead (which is ironic since the ability to easily paginate output with `less` is even more important with the `--verbose` output).

(Also see #25133.)

* Dart SDK version: 2.13.3 (stable) (Unknown timestamp) on "linux_x64"

**Comment by bkonyi** [comment]
Fix up for review [here](https://dart-review.googlesource.com/c/sdk/+/204661).
