### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by imchai** [dart-lang/sdk#46423]
## Version information

- `IDEA IC-211.7442.40`
- `2.13.3`
- `IC-211.7442.40, JRE 11.0.11+9-b1341.57x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 , screens 2880.0x1620.0`

**Comment by keertip** [comment]
@imchai, closing issue as there is no information we can work on.
