### ISSUE TITLE
Command line parameter is not fully read

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#46426]
Detected in https://github.com/flutter/flutter/issues/84270

With the below example:
```dart
void main(List<String> args) {
  print('args: $args');
}
```

Running

    >dart test.dart "^(?!Golden).+"

Expected

    ^(?!Golden).+

Actual:

    (?Golden).+

Dart SDK version: 2.14.0-228.0.dev (dev) (Sat Jun 19 18:06:49 2021 -0700) on "windows_x64"

Windows 10

**Comment by bkonyi** [comment]
@asashour is it always the first character that's being dropped, or is it just the `^` character?

**Comment by asashour** [comment]
It seems that regardless of the position, `^` and `!` are always removed.

```
>dart test.dart "a^b!c"
abc

>dart test.dart "a!@#$%^&*()b"
a@#$%&*()b
```

**Comment by bkonyi** [comment]
@asashour which terminal are you using? Command Prompt, Powershell, Linux Subsystem for Windows, Cygwin, etc.?

I'm unable to reproduce with my initial tests on bleeding edge on Windows and on Linux (although I ran into some weird bash behavior when using `!` with double quotes). I'll checkout `2.14.0-228.0.dev` next and give that a shot.

**Comment by asashour** [comment]
I am using windows command prompt.

**Comment by bkonyi** [comment]
I _think_ this is just the CMD doing something weird and you might just need to escape some characters. Can you try running this: `dart test.dart "^^(?^^!Golden).+"`?

**Comment by asashour** [comment]
Indeed, it can be escaped by prefixing both characters with `^`.

However, I don't think this is CMD-related, since Java works without escaping.

You can close this issue if you believe so.

```java
public class Test {
  public static void main(String[] args) {
    System.out.println(args[0]);
  }
}
```


```
>dart test.dart "^^(?^^!Golden).+"
args: [^(?^Golden).+]

>dart test.dart "!!"
args: []

>dart test.dart "\!"
args: [" ]

>dart test.dart "^!"
args: [!]

C:\use\flutter>dart test.dart "^^(?^!Golden).+"
args: [^(?!Golden).+]

>java Test "^(?!Golden).+"
^(?!Golden).+

>java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

```

**Comment by lrhn** [comment]
I cannot reproduce either. Windows 10, built from bleeding edge:
```
λ dart test.dart "^(?!Golden).+$"
args: [^(?!Golden).+$]

λ dart --version
Dart SDK version: 2.14.0-edge.28c784d87b0def07e63a1d5053fb9e7b6240c635 (be) (Wed May 19 12:35:16 2021 +0000) on "windows_x64"
```

You say you're getting Dart through Flutter. Is Flutter possibly using a different compiler, with a preamble which works differently on the command line before passing it to the `main` function (the C++ one, not the Dart `main`, that comes later).

**Comment by mraleph** [comment]
Flutter is using `dart.bat` wrapper https://github.com/flutter/flutter/blob/master/bin/dart.bat which I think causes this behavior because it does `SETLOCAL ENABLEDELAYEDEXPANSION`.

**Comment by bkonyi** [comment]
> because it does SETLOCAL ENABLEDELAYEDEXPANSION

That's definitely the issue, so this is a problem with Flutter. Will follow up on flutter/flutter#84270.
