### ISSUE TITLE
Analyzer: Extract method and NNBD doesn't provide right return type

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#46429]
Say we have this:
```
void foo(int b) {
  int? x;
  if (b < 2) {
    x = 42;
  }
  if (b >= 2) {
    x = 43;
  }
  print(x!);
}
```

and select the lines
```
  int? x;
  if (b < 2) {
    x = 42;
  }
  if (b >= 2) {
    x = 43;
  }
```

and chose extract method. I get the following:
```
void foo(int b) {
  int x = bar(b);
  print(x!);
}

int bar(int b) {
  int? x;
  if (b < 2) {
    x = 42;
  }
  if (b >= 2) {
    x = 43;
  }
  return x;
}
```

with a warning on line 3 (`The '!' will have no effect because the receiver can't be null.`) and an error on line 14 (`A value of type 'int?' can't be returned from the function 'bar' because it has a return type of 'int'.`).

Both are correct.
It's the extract method that was wrong. The return type should have been `int?` instead (and as a consequence the variable on line 2 should have been `int?` as well).

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/204626
