### ISSUE TITLE
[CP][beta channel] Please merge commits dart-lang/sdk@5f8a9d3 and dart-lang/sdk@da4ff4e

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#46421]
**commit(s) to merge**:  5f8a9d33d2f81c8ff7714c03c473b1291823403b
 
**merge instructions**: Clean merge

**What is the issue**: More robust handling of annotations in TFA

**What is the fix**: 
This change improves robustness of TFA by ignoring (and cleaning) all annotations which are not ConstantExpression, instead of crashing on them

**Why cherrypick**:
This is the second part of changes that went in to handle a AOT compiler crash with the error "Missing canonical name for Reference to _Experimental"

**Risk**: Low (has already rolled into Flutter in the master branch)

**Link to original  Issue** https://github.com/flutter/flutter/issues/83466

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @alexmarkov

**Comment by a-siva** [comment]
approved in the Dart scrum meeting

**Comment by a-siva** [comment]
@athomas @whesse can this issue be closed (change has been merged into 2.14 beta branch) ?

**Comment by whesse** [comment]
The change 5f8a9d3 has been merged into beta 1.14.0-188.5.beta, but the other change, listed in the title of this issue but not in the body of the issue, da4ff4e, has not been.

Is this a mistake, and this second change also needs to be cherry-picked into beta?

**Comment by alexmarkov** [comment]
@whesse da4ff4e9a695d2eb04dc18af164a0efd0fe1f337 is included into beta branch (when it was cut) and doesn't need to be cherry-picked.
