### ISSUE TITLE
[vm] non-const LinkedHashMap in JIT snapshots

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#46428]
We currently don't support having non-const LinkedHashMaps in JIT snapshots.

When invoking a function with non-const Maps before creating the snapshot and invoking the same function after loading the JIT snapshot we crash.

Reproduction: https://dart-review.googlesource.com/c/sdk/+/204503/1

Removing either the invocation of the non-const Map before creating the snapshot or when running from the snapshot makes the test succeed.

(Possibly related: Changing the clusters for kLinkedHashMapCid in clustered_snapshot.cc to UNREACHABLE still builds the SDK just fine, and doesn't trigger on the reproduction test case.)

**Comment by mraleph** [comment]
JIT snapshots don't support/expect arbitrary non-constant data in them, that's why they are taken with `fields_may_be_reset` flag. I think the cluster code for serializing `kLinkedHashMapCid` is dead code and is untested.
