### ISSUE TITLE
[analyzer] `Source` doesn't exist in the public api

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#46420]
I don't believe there is a way to import the `Source` class.  You can access it like so, but you can't import it so it is valid name in your namespace.
```dart
import 'package:analyzer/error/error.dart' show AnalysisError;
import 'package:analyzer/src/generated/source.dart' show Source; // verboten import (implementation_import)

void foo(AnalysisError err) {
  print err.source;
}
```

Furthermore, any datatype you can access, you should probably be able to import into your namespace.

**Comment by srawlins** [comment]
This also affects what you can see in documenttaion. We have public API which uses `Source` as a return type or a parameter type, and it's not linked.

@scheglov @bwilkerson WDYT about exposing Source in a public library? Is it intentionally private or just private-by-default-until-discussed?

**Comment by scheglov** [comment]
It is not API by default, although de-facto is exposed.
It is not what I would like it to be - just a pair of the file path and URI.
Reading and kinds should not be there.

**Comment by gaaclarke** [comment]
If it helps, the reason I wanted to expose it is because there are multiple ways to get references to `Source` and I wanted to factor out a function that converts an offset to a line number `int calcLineNumber(Source source, int offset)`.  It wasn't just the convenience of being able to name a variable, but also blocks the ability to factor out common functionality.

**Comment by bwilkerson** [comment]
> ... I wanted to factor out a function that converts an offset to a line number ...

In case it's useful, analyzer has a class named `LineInfo` that already does that for you, and most of the result objects returned from `AnalysisSession` have a reference to an already computed instance.
