### ISSUE TITLE
[CP][beta channel] Please merge fb32ffd97f365bc4c286b506d9be272a794345f5 into beta branch

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#46422]
**commit(s) to merge**:  fb32ffd97f365bc4c286b506d9be272a794345f5

**merge instructions**: clean merge

**What is the issue**: IOS app crashes on websocket close if app was in background for long-term

**What is the fix**:  Ensure SIGPIPE is not triggered for client socket connect code

**Why cherrypick**: All IOS apps which use websockets and are backgrounded will run into this issue.

**Risk**: Low, has been rolled into Flutter on master

**Link to original  issue(s)**:  https://github.com/flutter/flutter/issues/84499

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @aam

**Comment by a-siva** [comment]
approved in the dart scrum meeting

**Comment by a-siva** [comment]
@athomas @whesse can this issue be closed (change has been merged into 2.14 beta branch) ?

**Comment by whesse** [comment]
Merged to beta in 2.14.0-188.5.beta : https://github.com/dart-lang/sdk/commit/0cc2dddef12a1d63d08f993b63667623e584b459
