### ISSUE TITLE
dart --version prints to stderr instead of stdout

### ISSUE THREAD

**Issue by subfuzion** [dart-lang/sdk#46440]
`dart --version` [prints](https://github.com/dart-lang/sdk/blob/master/runtime/bin/main_options.cc#L130) to `stderr`.

Consider printing to `stdout` instead so that redirection isn't necessary to parse the output, as it is currently. Ex:

```
$ dart --version 2>&1 | cut -d ' ' -f 4
2.14.0-228.0.dev
```  

**Dart SDK Version** (`dart --version`): Dart SDK version: 2.14.0-228.0.dev (dev) (Sat Jun 19 18:06:49 2021 -0700) on "macos_x64"

**Comment by bkonyi** [comment]
Fix up for review [here](https://dart-review.googlesource.com/c/sdk/+/204661).

**Comment by mraleph** [comment]
Changing it to stdout is a breaking change. 

This has been like this since day 1 so we have been so far treating this as working-as-intended. 

If we want to change this (some tools changed, e.g. python used to print to stderr for a long time and then switched to stdout) then we might want to go through a breaking change process.

**Comment by subfuzion** [comment]
Yeah, I had brought this up because with Python 3 switching to stdout, I can't think of a single other language that does this, which makes this behavior a bit surprising for anyone trying to parse the version string (especially if they don't realize what they're seeing is being printed to stderr).

I agree that this would be a breaking change -- but it's one that would be a trivial fix for anyone parsing the version string. Anyone doing redirection as I demonstrated in the description (which is pretty much how anyone parsing from a bash script is going to do it), won't be affected at all. While this isn't earth-shattering, It might not be a bad thing to change this behavior for the next major version.

**Comment by bkonyi** [comment]
Fair point. I think this is worth going through the breaking change process for the version string and the help messages so we're consistent with most other UNIX tooling.

**Comment by bkonyi** [comment]
Landed in https://github.com/dart-lang/sdk/commit/cccc0293c540ebee7116d98ef6cb24c1caf9512e.
