### ISSUE TITLE
incremental_compiler_test is flaky on mac-arm64

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46450]
There are new test failures on [[cfe] Verify that only new method invocation nodes are generated when supported](https://github.com/dart-lang/sdk/commit/1adf5dc7c691ab228abdc4fe60061f8c16cd2ec8).

The tests
```
pkg/vm/test/incremental_compiler_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64
```

Log:
```
00:08 [32m+14[0m[31m -1[0m: expression evaluation from source [1m[31m[E][0m[0m

  Bad state: No element

  dart:core-patch/growable_array.dart 332:5           List.first
  pkg/vm/test/incremental_compiler_test.dart 1676:21  RemoteVm._computeMainId
  ===== asynchronous gap ===========================
  pkg/vm/test/incremental_compiler_test.dart 1648:52  RemoteVm.mainId
  ===== asynchronous gap ===========================
  pkg/vm/test/incremental_compiler_test.dart 1703:14  RemoteVm.getIsolate
  ===== asynchronous gap ===========================
  pkg/vm/test/incremental_compiler_test.dart 1197:27  main.<fn>.launchBreakAndEvaluate.<fn>
```

https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/15/pkg/vm/test/incremental_compiler_test

/cc @aam @johnniwinther

**Comment by dcharkes** [comment]
Again today https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/309/pkg/vm/test/incremental_compiler_test

**Comment by dcharkes** [comment]
And today: https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/767/pkg/vm/test/incremental_compiler_test

Why does this only occur on arm64 macs though?

**Comment by whesse** [comment]
I marked this test as flaky manually, so it will no longer appear as switching between passing and failing.  After the next build completes, it should show up as flaky in the [current results page](https://dart-ci.firebaseapp.com/current_results/#/filter=pkg/vm/test/incremental_compiler_test) and on the [flakiness dashboard](go/dart-flakiness?fb=configuration:in:unittest-asserts-release-mac-arm64)

**Comment by dcharkes** [comment]
It swapped status again on mac-arm64 today

```
unittest-asserts-release-mac-arm64
flaky -> RuntimeError (expected Pass)
pkg/vm/test/incremental_compiler_test
```

log: https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/992/pkg/vm/test/incremental_compiler_test

**Comment by whesse** [comment]
This test is actually flaky on all platforms:

go/dart-flakiness?fb=name:eq:pkg%2Fvm%2Ftest%2Fincremental_compiler_test

![image](https://user-images.githubusercontent.com/4905639/140053912-732c68c3-b677-4955-b965-4c908a41bb75.png)

**Comment by alexmarkov** [comment]
```
00:09 [32m+14[0m[31m -1[0m: expression evaluation from source [1m[31m[E][0m[0m

  Bad state: No element

  dart:core-patch/growable_array.dart 339:5           List.first
  pkg/vm/test/incremental_compiler_test.dart 1673:21  RemoteVm._computeMainId
  ===== asynchronous gap ===========================
  pkg/vm/test/incremental_compiler_test.dart 1645:52  RemoteVm.mainId
  ===== asynchronous gap ===========================
  pkg/vm/test/incremental_compiler_test.dart 1700:14  RemoteVm.getIsolate
  ===== asynchronous gap ===========================
  pkg/vm/test/incremental_compiler_test.dart 1196:27  main.<fn>.launchBreakAndEvaluate.<fn>
  

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8831453547242854513/+/u/test_results/new_test_failures__logs_

**Comment by a-siva** [comment]
//cc @bkonyi the latest failure seems to indicate isolates.first is empty, did anything change in service protocol to cause this ?

**Comment by bkonyi** [comment]
@a-siva from what I can tell, this has always been happening. Chances are that the test has connected to the service before the main isolate has come up and is getting an empty isolate list from the `VM` response.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/63645 should hopefully fix it

**Comment by whesse** [comment]
Manually marked as flaky again.
