### ISSUE TITLE
[vm] Functions are not subtypes of Object

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#46452]
```dart
void main() {
  print(f is Object);
  print([f] is List<Object>);
}

void f() {}
```

On the VM, this prints `true`, then `false`. I would expect both lines to print `true`.

**Comment by lrhn** [comment]
This is a null-safety related behavior. If I add `//@dart=2.9`, it prints `true` instead.
Creating the list explicitly with `<void Function()>[f]` doesn't change the `false` result.

It's internally inconsistent in that an `as List<Object>` cast succeeds, and you can assign the value to a `List<Object>` variable.

**Comment by alexmarkov** [comment]
This bug was fixed in https://dart-review.googlesource.com/c/sdk/+/211580.
