### ISSUE TITLE
restart_call_on_deopt_regress_46070_test started failing

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#46463]
The upgrade to use Fuchsia windows clang toolchain (https://dart-review.googlesource.com/c/sdk/+/201862)
could potentially have caused the following tests to fail on the windows ia32

```
vm/dart/deopt/restart_call_on_deopt_regress_46070_test RuntimeError (expected Pass)
vm/dart_2/deopt/restart_call_on_deopt_regress_46070_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-win-release-ia32
dartk-weak-asserts-win-release-ia32
dartk-win-debug-ia32
dartk-win-release-ia32
```

**Comment by aam** [comment]
The change in test status (from Crash to RuntimeError) started with https://dart-review.googlesource.com/c/sdk/+/204204.

**Comment by alexmarkov** [comment]
These tests are now passing on all configurations and not flaky.
