### ISSUE TITLE
About the feature of the StopWatch class

### ISSUE THREAD

**Issue by myConsciousness** [dart-lang/sdk#46479]
Hi, thanks for your daily energetic development.

I'm using the StopWatch class in an app I'm working on, but I noticed that it doesn't have the feature to split the time.
I could add a class that inherits from the StopWatch class to add the functionality, but since it's called a "stopwatch", I think the feature to split the time should be built in.

If you don't want to implement it or don't need this feature, drop the issue.

Thank you.

**Comment by lrhn** [comment]
I'm not sure what "split the time" means. If Wikipedia is correct, the idea is to remember and display the current time when the split button is pressed, while still counting time in the background. When the split button is pressed again, the display goes back to showing the total time, including the time that passed while showing the split time.

I'm not sure that is a good model for something like the Dart `Stopwatch` class. It doesn't have a *display* that it needs to share with other uses.
You can read the `elapsedMilliseconds` at any time, and remember that for as long as you want to in your own variables, while the stopwatch keeps ticking. It doesn't need a button or shared display for that.
Adding a way to make the stopwatch class freeze what it reports to `elapsedMilliseconds`, while still *counting* in the background, seems like an unnecessary complication.

So, I'd probably prefer not to add that functionality.

**Comment by myConsciousness** [comment]
> I'm not sure what "split the time" means. If Wikipedia is correct, the idea is to remember and display the current time when the split button is pressed, while still counting time in the background. When the split button is pressed again, the display goes back to showing the total time, including the time that passed while showing the split time.
> 
> I'm not sure that is a good model for something like the Dart `Stopwatch` class. It doesn't have a _display_ that it needs to share with other uses.
> You can read the `elapsedMilliseconds` at any time, and remember that for as long as you want to in your own variables, while the stopwatch keeps ticking. It doesn't need a button or shared display for that.
> Adding a way to make the stopwatch class freeze what it reports to `elapsedMilliseconds`, while still _counting_ in the background, seems like an unnecessary complication.
> 
> So, I'd probably prefer not to add that functionality.

That is the correct understanding.
I've only recently started writing Dart, so I don't know the details yet, but I somewhat understand what you wanted to tell.

By the way, the split function I was trying to implement is equivalent to the split function in the following Java class.

https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/time/StopWatch.java

**Comment by lrhn** [comment]
That does look like what I was envisioning. I must admit don't see the *point* of the `split` operation, other than mimicking a physical stop watch. That is not the goal of the Dart `Stopwatch` class. The goal of that is to allow you to measure elapsed time. A split time is just a record of elapsed time at a specific point, stored for posterity in the same object, and with an extra state transition back and forth. Which feels like more state than you need (I cannot see any practical reason for the `unsplit` function in the Java class, it should work just as well without it, allowing you to just press `split` again if you want to update the split time.)

I'll just say no to doing that in Dart. :)
