### ISSUE TITLE
Analyzer assumes dynamic has static members from Object

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#46472]
After adding static methods `hash`, `hasAll` and `hashAllUnordered` to the `Object` class, the analyzer treats them as static members of `dynamic` when you try to tear something of that name off from `dynamic`. It should not.
```dart
class C {
  C get c => this;
  String get hash => "A";
  String get hashAll => "B";
  String get hashAllUnordered => "C";
}

class D {
  String hash() => "A";
  String hashAll() => "B";
  String hashAllUnordered() => "C";
}

main() {
 dynamic o = C();
 print(o.hash);
 print(o.hashAll);
 print(o.hashAllUnordered);
 o = D();
 print(o.hash());
 print(o.hashAll());
 print(o.hashAllUnordered());
 o = C();
 print(o.c.c.c.hash);
}
```
gives
```
  error • Static method 'hash' can't be accessed through an instance. • ex.dart:16:10 • instance_access_to_static_member
  error • Static method 'hashAll' can't be accessed through an instance. • ex.dart:17:10 • instance_access_to_static_member
  error • Static method 'hashAllUnordered' can't be accessed through an instance. 
• ex.dart:18:10 • instance_access_to_static_member
  error • Static method 'hash' can't be accessed through an instance. • ex.dart:24:16 • instance_access_to_static_member
4 errors found.
```

The analyzer shouldn't consider static members here. It's likely an artifact of there not being any static members previously, and the analyzer never needed to distinguish between members of `Object` accessed through `Object` and `dynamic`.

The example shows that it's only getters/tear-offs that are handled this way, invocations do not give similar errors.

A little tracing suggests that the single-identifier receiver errors is reported by the call at https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/generated/error_verifier.dart#L1013
There might be other places for other receivers.

**Comment by vsmenon** [comment]
Is this obsolete?  ( @srawlins ? )

I'm not seeing any warnings in Dartpad now.  I do if I retype `o` as `Object`.

**Comment by srawlins** [comment]
Hmm, I think since we haven't released a version of Dart in months, DartPad does not have this bug _yet_. :)

I still see the following with a recent SDK:

```dart
 error • a.dart:16:10 • Static method 'hash' can't be accessed through an instance. Try using the class 'Object' to access the method. •
          instance_access_to_static_member
  error • a.dart:17:10 • Static method 'hashAll' can't be accessed through an instance. Try using the class 'Object' to access the method. •
          instance_access_to_static_member
  error • a.dart:18:10 • Static method 'hashAllUnordered' can't be accessed through an instance. Try using the class 'Object' to access the method. •
          instance_access_to_static_member
  error • a.dart:24:16 • Static method 'hash' can't be accessed through an instance. Try using the class 'Object' to access the method. •
          instance_access_to_static_member
```

**Comment by srawlins** [comment]
Looks like these three static member have been added in 2.14 dev releases. https://api.dart.dev/dev/2.14.0-385.0.dev/dart-core/Object-class.html#static-methods

**Comment by vsmenon** [comment]
Ahh, good catch re dartpad.  

@scheglov - does this look like a quick fix?  If so, we should consider cherry picking to the upcoming stable.  ( @a-siva @devoncarew )

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/209420
