### ISSUE TITLE
[html] Node leak

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#46470]
Hey, I have created a simple dart web app however there is a leak which I've tracked down to interacting with an `Element`. It's increasing the number of nodes in the DOM every time the element is called. My web app is running on a low powered device (Amazon Kindle) and it's causing it to crash after a while due to this leak.

## Browser Performance Profile:
![image](https://user-images.githubusercontent.com/298850/123406745-227dfe00-d5a3-11eb-8b39-071961b21419.png)
Simple profile showing the issue: [Profile-20210625T111130.zip](https://github.com/dart-lang/sdk/files/6715456/Profile-20210625T111130.zip)

## The code

Problematic code:
```dart
    // Iterate over the rows and columns and update element if required
    for (var r = 0, rl = 3; r < rl; r++) {
      for (var c = 0, cl = 7; c < cl; c++) {
        final character = display[r][c] == ' ' ? '' : display[r][c];
        if (elements[r][c].innerText != character) {
          elements[r][c].innerText = character;
        }
      }
    }
```
Removing the line `elements[r][c].innerText = character;` solves the nodes leak.

The [source file is here](https://github.com/jimmyff/crypto-clock/blob/2d849d95f32d9ebea98bbbda37c570389c1a759f/web/main.dart#L268). Although the above is a simpler implementation which I'm running locally trying to track down the issue. 

## Testing

You can [test the web page here](https://jimmyff.github.io/crypto-clock/). I suggest setting the update interval to 5 seconds which means you will see more requests and this will make the leak easier to spot. To do this click/tap in the central column and change update interval to 5 then save.

**Comment by kevmoo** [comment]
CC @sigmundch

**Comment by jimmyff** [comment]
I think this is actually with dev tools being misleading:

https://github.com/angular/angular.js/issues/13716 & https://github.com/dart-lang/http/issues/586

There does seem to be a leak in my app, but I don't think this is it.
