### ISSUE TITLE
Investigate making ABI translator from arm/arm64 to intel (for running simarm/simarm64 with FFI)

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#46488]
We should investigate making ABI translator from generated simarm/simarm64  FFI calls to intel. It would allow us to replace natives in `dart:io` and others with `FfiNative`s without loosing option to run in simarm/simarm64.

**Comment by dcharkes** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/37299.

**Comment by mkustermann** [comment]
In that case we should close this one :)
