### ISSUE TITLE
Analyzer's mock sdk is outdated

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#46480]
The analyzer's mock SDK appears to have outdated declarations for `dart:ffi` (see https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/test_utilities/mock_sdk.dart#L618). If that's true then it means that the tests of analyzer's support for `dart:ffi` might be out of date. In particular, I noticed that the tests for `FfiCode.ARGUMENT_MUST_BE_A_CONSTANT` appear to be relying on an outdated declaration.

Does analyzer need to provide support for older versions of the SDK in general, or of `dart:ffi` in particular?

Who should be responsible for keeping the analyzer's mocked version of `dart:ffi` up to date and ensuring that the analyzer's support for it is maintained?

One option we might consider here is to write a test that compares the mock SDK to the real SDK to find places where the mock SDK is outdated (incomplete is presumably fine). Such a test would presumably cover more than just `dart:ffi` and would guard against other kinds of version skew.

Another option would be to remove the mock SDK and always use the real SDK for testing.

@devoncarew @scheglov @dcharkes

**Comment by dcharkes** [comment]
> I noticed that the tests for FfiCode.ARGUMENT_MUST_BE_A_CONSTANT appear to be relying on an outdated declaration.

That is not intended.

> Who should be responsible for keeping the analyzer's mocked version of dart:ffi up to date and ensuring that the analyzer's support for it is maintained?

A test turning red! 🦞   (Which would make CL authors doing changes responsible.)

I'm fine with any of the two options. Is there a reason we have a mock SDK in the first place? Speed? Or being able to test things that are not in the SDK themselves yet?

**Comment by scheglov** [comment]
My view on this is that unit tests are for us, `analyzer` developers, to make testing more convenient - faster, or verifying more details. The authoritative suits of tests are shared tests - `language/` and `co19/`. We must pass them, with the actual SDK.

As such, we use the mock SDK for our convenience - speed mostly, but also to be able to put it into the in-memory file system. If it is not fully consistent with the actual SDK, and tests don't pass, then it is like any other part of our unit tests - it is not testing what it should, and must be fixed. If it is not consistent, but we still test what we want to test conveniently - well, it would be nice to update, but not necessary.

**Comment by bwilkerson** [comment]
> The authoritative suits of tests are shared tests ...

That's only true for diagnostics included in the specification. It isn't true for hints and it isn't true for the FFI checks, which is where we have a problem.

> We must pass [the shared tests], with the actual SDK.

Should we be testing everything that isn't included in the shared tests against the real SDK?

> If it is not fully consistent with the actual SDK, and tests don't pass ...

But there's a problem if the tests pass only because the APIs they're testing against are incorrect. At that point we have no signal telling us that users will see an issue. If the APIs were correct then the tests would fail because there would be errors beyond those we were expecting.

**Comment by scheglov** [comment]
I tried to switch `analyzer` unit tests to actual SDK.

When we naively copy SDK files into `MemoryResourceProvider`, I did not have enough patience to wait when it finishes, it was 5+ minutes for `9000` out of `+21549` tests.

If we read the actual SDK once, and then just copy, it takes `13:16 +21549`.

With mock SDK it takes `01:53 +21604`.

Using one approach for some tests, and another for other tests does not seem palatable.

With such timing difference I would like to keep mock SDK, and agree that I will update `dart:ffi` in the mock SDK when it changes in the actual SDK. Now I just need to know when it changes. In google3 we have `LINT.IfChange … LINT.ThenChange`, I wonder if there is a similar mechanism in Gerrit.

**Comment by scheglov** [comment]
A combination of mock SDK, but copying `dart:ffi` from the platform SDK seems to work fast enough.
Still does not seem nice :-(

```dart
final _platformSdk = <String, String>{};

void copyPlatformSdk({
  required MemoryResourceProvider resourceProvider,
}) {
  if (_platformSdk.isEmpty) {
    var platformSdkPath = getSdkPath();
    // var platformFiles = io.Directory(platformSdkPath).listSync(recursive: true);
    var platformFiles = io.Directory(path.join(platformSdkPath, 'lib', 'ffi'))
        .listSync(recursive: true);
    for (var file in platformFiles) {
      if (file is io.File) {
        var filePath = file.path;
        if (file_paths.isDart(path.context, filePath) ||
            path.basename(filePath) == 'allowed_experiments.json' ||
            path.basename(filePath) == 'version') {
          var relativePath = path.relative(filePath, from: platformSdkPath);
          _platformSdk[relativePath] = file.readAsStringSync();
        }
      }
    }
  }

  for (var entry in _platformSdk.entries) {
    resourceProvider.newFile(
      resourceProvider.pathContext.join(sdkRoot, entry.key),
      entry.value,
    );
  }
}
```

**Comment by bwilkerson** [comment]
I have put together a CL to update the definition of `dart:ffi` in the mock sdk as a short-term work-around (and will send it out shortly), but I do think it's important for us to think about longer term solutions.

**Comment by scheglov** [comment]
We could have a script to run that will get the current `dart:ffi` from the actual SDK and copy into the mock SDK. Ideally this change is done by a person who knows what he is changing.

Ideally the mock SDK should be changed at the same time as the actual SDK is changed, by the person who knows what he is doing and why. Ideally (for us, but not for the this person), Gerrit should require our review of such changes.

A less ideal solution is to have a script that will get the current `dart:ffi` from the actual SDK and copy into the mock SDK. Just blindly copy, no thinking, no removing unnecessary stuff. One of us will have to run it periodically.

Oh, there could be a test that checks that the copy in the mock SDK is the same as the actual SDK.

**Comment by dcharkes** [comment]
How about a script that checks if any if the ffi SDK files is changed that also the mock SDK is updated? (In the same way that we have a script that checks if tests in language/ are updated tests in language_2 should be updated.) That would not enforce that the change is correct, but would notify someone editing the Dart SDK dart:ffi files on `git cl upload` to update the mock sdk.

**Comment by bwilkerson** [comment]
I apologize for the noise. While I still believe that it would be good for us to have an automated way to detect when the mock sdk is out of sync with the real SDK, the mock sdk is not currently out of date (that I'm aware of).

What happened is that I was testing the behavior of the analyzer in a package that had a dependency on `flutter` (I had forgotten that this was the case). The dependency caused analyzer to use the older version of the Flutter SDK, which is where the discrepancy was.

As an interesting side-note, the package I was using had a dependency on `flutter`, but does not include the `sdk: flutter` designation. My understanding is that this designation is what should tell the analyzer to use the Flutter SDK rather than the Dart SDK, but perhaps I'm wrong about that.
