### ISSUE TITLE
[ Breaking Change Request ] Update `dart --help --verbose` and `dart --version` to output to stdout

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#46497]
**Intended Behavior Change**

Update `dart` to print help and version information to `stdout` instead of `stderr`.

**Current Behavior**

Currently the following invocations output details to `stderr` instead of `stdout`:

- `dart --help --disable-dart-dev`
- `dart --help --verbose`
- `dart --version`

Most UNIX tools, as well as other language implementations such as `python3` output their help messages to `stdout`, and some tools like `less` are typically used by piping `stdout` as input.

**Expected Impact**

Tooling and tests which scrape `stderr` for version information or VM flags will start to fail. Impacted tooling and tests will need to be updated to scrape this information from `stdout`.

**Related issues**

- #46440 
- #46412

**Comment by franklinyow** [comment]
CC: @mit-mit @vsmenon @kevmoo, @Hixie  for approvals

**Comment by kevmoo** [comment]
Approved – although @mit-mit should have the final say from the PM team

**Comment by mit-mit** [comment]
SGTM

**Comment by bkonyi** [comment]
Change landed in https://github.com/dart-lang/sdk/commit/cccc0293c540ebee7116d98ef6cb24c1caf9512e.
