### ISSUE TITLE
Cannot build host vm with Xcode 13 on macOS, TARGET_OS_LINUX dart flags declared

### ISSUE THREAD

**Issue by jmagman** [dart-lang/sdk#46499]
On Xcode 13 beta 2 (13A5154o) (available at [go/xcode](https://x20.corp.google.com/teams/xcode/Xcode13.0)) on dart 557c841b50b I wasn't able to build the host Flutter engine.
```
$ ./flutter/tools/gn --unoptimized && ninja -C out/host_debug_unopt 
...
ninja: Entering directory `out/host_debug_unopt'
[1/1] Regenerating ninja files
[4594/5483] LINK ./gen_snapshot
FAILED: gen_snapshot 
../../buildtools/mac-x64/clang/bin/clang++ -isysroot /Users/m/Applications/Xcode-13_beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.11.0 -rdynamic -arch x86_64 -nostdlib++ -stdlib=libc++ -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -Wl,-pie  -Xlinker -rpath -Xlinker @executable_path/Frameworks -o ./gen_snapshot -Wl,-filelist,./gen_snapshot.rsp  -ldl -lpthread -framework CoreFoundation -framework CoreServices
Undefined symbols for architecture x86_64:
  "dart::FLAG_generate_perf_jitdump", referenced from:
      dart::VirtualMemory::Init() in libdart_vm_precompiler.virtual_memory_posix.o
  "dart::FLAG_generate_perf_events_symbols", referenced from:
      dart::VirtualMemory::Init() in libdart_vm_precompiler.virtual_memory_posix.o
ld: symbol(s) not found for architecture x86_64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
[4611/5483] CXX obj/third_party/dart/runtime/vm/libdart_vm_jit.object.o
ninja: build stopped: subcommand failed.
```
(Ran on top of PR https://github.com/flutter/buildroot/pull/475 to pick up macOS 12 SDK.)

@jason-simmons noticed those dart flags should be gated on `#if defined(TARGET_OS_LINUX)`.  
https://github.com/dart-lang/sdk/blob/d9f9b4dc96064879a8187b48ed62a7cbc32abc2c/runtime/vm/virtual_memory_posix.cc#L40-L43

The Xcode 12.5 (working) TargetConditionals.h does not define `TARGET_OS_LINUX`:
```
    #define TARGET_OS_MAC               1
    #define TARGET_OS_WIN32             0
    #define TARGET_OS_UNIX              0
```
[TargetConditionals-12.h.txt](https://github.com/dart-lang/sdk/files/6730183/TargetConditionals-12.h.txt)
But Xcode 13 does (as well as `TARGET_OS_WINDOWS`):
```
    #define TARGET_OS_MAC               1
    #define TARGET_OS_WIN32             0
    #define TARGET_OS_WINDOWS           0
    #define TARGET_OS_UNIX              0
    #define TARGET_OS_LINUX             0
```
[TargetConditionals-13.h.txt](https://github.com/dart-lang/sdk/files/6730184/TargetConditionals-13.h.txt)

**Comment by jmagman** [comment]
\cc @zanderso

**Comment by zanderso** [comment]
One option would be to put a Dart-specific prefix on the existing defines, i.e. `TARGET_OS_MAC` -> `DART_TARGET_OS_MAC`, etc.

/cc @a-siva @aam @rmacnak-google

**Comment by jmagman** [comment]
Or these kinds of checks can be swapped to check the value instead of whether it's defined, since if it's not defined it would be 0. 
`#if TARGET_OS_LINUX`.

**Comment by a-siva** [comment]
Not sure why the code in sdk/runtime/vm/virtual_memory_posix.cc needs to be guarded around TARGET_OS_LINUX, there is code in os_android.cc that is not guarded like that.

**Comment by zanderso** [comment]
Since the `TargetConditionals.h` header is updated with new defines, the issue affects all `#if defined(TARGET_OS...)` checks.

**Comment by a-siva** [comment]
Do you see additional undefined symbols ?

**Comment by jmagman** [comment]
@a-siva If I comment out the `DECLARE_FLAG`s it then crashes
```
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x100
version=2.14.0-244.0.dev (dev) (Thu Jun 24 12:43:59 2021 -0700) on "macos_x64"
pid=69720, thread=3587, isolate_group=vm-service(0x7fbbee812c00), isolate=vm-service(0x7fbbee817e00)
isolate_instructions=10f9162c0, vm_instructions=10f9162c0
  pc 0x0000000112c824c7 fp 0x000070000319e9a8 Unknown symbol
  pc 0x000000010fc58619 fp 0x000070000319ea50 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x149
  pc 0x000000010fc5842d fp 0x000070000319eac0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x14d
  pc 0x000000010fd0d477 fp 0x000070000319eb40 dart::Library::Invoke(dart::String const&, dart::Array const&, dart::Array const&, bool, bool) const+0x307
  pc 0x000000011048f069 fp 0x000070000319ec30 Dart_Invoke+0x639
  pc 0x000000010fbd4beb fp 0x000070000319ec80 dart::bin::DartUtils::PrepareBuiltinLibrary(_Dart_Handle*, _Dart_Handle*, bool, bool)+0x4b
```
but maybe that's not what you're asking?

I see places this could be a problem if the code was ever rewritten or refactored, like say these conditions were reverted:
https://github.com/dart-lang/sdk/blob/2c6009efafdee8668ab6f5be3919903c3a94a51d/runtime/vm/image_snapshot.cc#L965-L967
or this was refactored to not `|| defined(TARGET_OS_MACOS)`:
https://github.com/dart-lang/sdk/blob/82ea8416ed2a22e40c5c67252cb37bebec3a57e8/runtime/bin/snapshot_utils.cc#L352

https://github.com/dart-lang/sdk/search?q=TARGET_OS_LINUX

**Comment by zanderso** [comment]
https://dart-review.googlesource.com/c/sdk/+/205860 has rolled into the engine.

**Comment by jmagman** [comment]
Just tested, seems to be working now.  Thanks @zanderso!
