### ISSUE TITLE
we should ignore vm entry-point pragmas from the POV of unused code analysis

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#46506]
We should ignore vm entry-point pragmas from the POV of unused code analysis; the pragma annotation is indicating that the method is likely called from native code.

```
@pragma("vm:entry-point")
void _aNativeMethod() {
  ...
```

```
@pragma("vm:entry-point", !const bool.fromEnvironment("dart.vm.product"))
void _aNativeMethod() {
   ...
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/205303

**Comment by devoncarew** [comment]
> https://dart-review.googlesource.com/c/sdk/+/205303

Thanks!

**Comment by scheglov** [comment]
Clean up https://dart-review.googlesource.com/c/sdk/+/205341
