### ISSUE TITLE
Dart analyzer in Android Studio question/issue

### ISSUE THREAD

**Issue by kristijorgji** [dart-lang/sdk#46507]
The screenshoot below says it all, in principle:
1. I have a certain nullable type T?
2. I check first in if condition if it is different then null. T? something = T(); if (something != null) { // do something with something. Still analyzer wants to check against null and use `!.`}

Same situation in screenshoot below and many other situations for me, also in pure dart code not just inside flutter.

In screenshoot I just compared that stackChildren is not null
its type is `  final List<Widget>? stackChildren;`

so why do I need to use `!` after variable to assert is not null again while expanding

![Screenshot 2021-06-29 at 15 57 34](https://user-images.githubusercontent.com/15630854/123810596-d27c9f80-d8f2-11eb-9936-ad7f53d39be9.png)

Next example same situation String?, checking that is different then null, still need to assert `!`

![Screenshot 2021-06-29 at 16 05 35](https://user-images.githubusercontent.com/15630854/123811828-e4127700-d8f3-11eb-9ba5-57d2f4c6c859.png)

Have to use `text!` instead of `text`

I am not complaining though, just trying to understand what is reason for this. In typescript for example analyzer would not ask to assert after the null check

**Comment by lrhn** [comment]
The `stackChildren` is likely not a *local* variable. Dart only allows you to type-promote local variables, that includes removing nullability.

You can use `...?stackChildren` instead to only spread the value if it's non-null. That avoids having to read the non-local variable twice, and then try to infer something for the latter read from tests on the former (which is what promotion does).
