### ISSUE TITLE
Wrong error location of COMPILE_TIME_ERROR.TYPE_PARAMETER_SUPERTYPE_OF_ITS_BOUND in tests

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46510]
co19/Language/Generics/parameter_A03_t01
co19/Language/Generics/parameter_A03_t02
co19/Language/Generics/parameter_A03_t04
co19/Language/Generics/parameter_A03_t05

**Comment by bwilkerson** [comment]
This was reported and has been fixed (https://github.com/dart-lang/co19/issues/1103). Just waiting on a new roll of the co19 tests.

**Comment by scheglov** [comment]
Thank you. I will update my tracking document.
