### ISSUE TITLE
Code action preview not supported in IntelliJ

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#46511]
In a file containing
```
void f() {
  Object()
}
```
place the cursor after `Object()` and request code actions (Alt+Enter / Option+Enter), then request a preview (Alt+Space / Option+Space). You should see "Preview isn't available".

I believe IntelliJ has enough information to be able to provide a preview.

**Comment by parlough** [comment]
https://github.com/JetBrains/intellij-plugins/commit/9a671516aced59f2ca7dc47f59e59e27da1db54a implemented preview, which after 2021.3 seems to be instead toggled with F1 or Ctrl+Q by default. It's working well in the cases I tested :)
