### ISSUE TITLE
Analyzer does not report problems in .packages files

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46529]
```
standalone/package/scenarios/invalid/invalid_package_name_test
standalone/package/scenarios/invalid/same_package_twice_test
```

Don't know if actually the analyzer should support it, or `test_runner`, or it is something that should not work at all.

**Comment by bwilkerson** [comment]
Sounds to me like something that `test_runner` should support. I don't think we want this to be supported outside our own test framework.

**Comment by scheglov** [comment]
Yes, and actually it does support it.
As I understand these tests verify that we get some indication about errors in `.packages` files.

Currently we don't report back the exception thrown by `package_config_packages_file.parse()` (PackageConfigFormatException "FormatException: Not a valid package name (at offset 2)"). And I don't have a good way to report such non-Dart issues.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/205628
