### ISSUE TITLE
lib/mirrors/deferred_type_test is invalid

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46526]
From the specification: A type T is deferred iff it is of the form p.T where p is a deferred prefix. It 
is a compile-time error to use a deferred type in a type annotation, type test,
type cast or as a type parameter. However, all other compile-time errors must
be issued under the assumption that all deferred libraries have successfully been
loaded.

![image](https://user-images.githubusercontent.com/384794/123994947-b45e8000-d982-11eb-97b3-58ef6c746f75.png)

**Comment by eernstg** [comment]
Perhaps this test used to rely on the ability to run programs with warnings? In any case, we might just remove this test: `language/regress/regress23408a_test.dart` already tests that it is a compile-time error to use a type from a deferred library, and any non-total-rewrite update to `deferred_type_test.dart` will make it a test that does only that. Then it says nothing about mirrors, and serves no purpose.

Closing, the test has been removed [now](https://dart-review.googlesource.com/c/sdk/+/205720).
