### ISSUE TITLE
Final variable type promotion is lost inside a closure if followed by try/catch

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#46532]
* Dart SDK Version (`dart --version`)

```
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"
```

## Description

The following code attempts to use type promotion of a final variable, which should be guaranteed to work in this case because the variable in question is final.

```dart
mixin A {
}

class Foo with A {
  final foo = 'foo';
}

class Bar with A {
  final bar = 'bar';
}

void main() {
  final A a;
  try {
    a = Foo();
  } catch (e) {
    print('ERROR: $e');
    return;
  }
  if (a is Foo) {
    print(['foo', 'bar'].firstWhere((i) => i == a.foo)); // fails to compile
  } else if (a is Bar) {
    print(['foo', 'bar'].firstWhere((i) => i == a.bar)); // fails to compile
  }
}
```

The two lines where it says `// fails to compile` fail because of the errors (from DartPad):

```
Error: The getter 'foo' isn't defined for the class 'A'.
 - 'A' is from 'package:dartpad_sample/main.dart' ('lib/main.dart').
    print(['foo', 'bar'].firstWhere((i) => i == a.foo));
                                                  ^^^
lib/main.dart:23:51:
Error: The getter 'bar' isn't defined for the class 'A'.
 - 'A' is from 'package:dartpad_sample/main.dart' ('lib/main.dart').
    print(['foo', 'bar'].firstWhere((i) => i == a.bar));
                                                  ^^^
Error: Compilation failed.
```

I am almost certain this is a bug because changing the code that assigns `a` from:

```dart
  final A a;
  try {
    a = Foo();
  } on FormatException catch (e) {
    print('ERROR: $e');
    return;
  }
```

to:

```dart
final A a = Foo();
```

... causes the problem to go away. But at the point where the error occurs, it shouldn't matter which of the two above was used, as `a` is guaranteed to be assigned and final after this.

This issue might be related to [issue 32285](https://github.com/dart-lang/sdk/issues/32285)?

**Comment by renatoathaydes** [comment]
Also, notice that this compiles fine:

```dart
    print(a.foo);
    //print(['foo', 'bar'].firstWhere((i) => i == a.foo));
```

So type promotion seems to work when outside the closure only.

**Comment by eernstg** [comment]
The following reduced example will actually suffice to obtain the error:

```dart
void main() {
  final num a;
  a = 1;
  if (a is int) (i) => i == a.isEven; // fails to compile
}
```

whereas the following compiles without errors:

```dart
void main() {
  final num a = 1;
  if (a is int) (i) => i == a.isEven; // fails to compile
}
```

The reason why there is no promotion of `a` in the function literal body is that there is an assignment to `a` (this happens for any assignment to `a`, no matter where it is located). Some more info can be found in https://github.com/dart-lang/language/issues/1247.

I think we can close this issue as a duplicate, because the discussion about this particular part of the flow analysis is already the topic of that issue.

**Comment by renatoathaydes** [comment]
The treatment of a final local variable for purpose of flow analysis should not depend on whether it's assigned immediately on declaration, or separately. There's no good reason to do it that way. As long as the variable has been definitely assigned (which the analyzer can easily recognize), the two cases are identical?!

I agree that in the case where the variable is not final, the current behaviour is appropriate. But for final local variables, I believe it's simply a mistake to not promote the type.

**Comment by eernstg** [comment]
I think it's better to make that argument in https://github.com/dart-lang/language/issues/1247!
