### ISSUE TITLE
Failures on [cfe] Perform eager canonicalization of instantiations without experiment

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#46547]
There are new test failures on [[cfe] Perform eager canonicalization of instantiations without experiment](https://dart-review.googlesource.com/c/sdk/+/205648).

The tests
```
co19/Language/Generics/typedef_A05_t01 RuntimeError (expected Pass)
co19_2/Language/Generics/typedef_A05_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
dartdevk-checked-linux-release-chrome
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
```

**Comment by johnniwinther** [comment]
@nshahan These failures to do not reproduce locally so I don't know what the problem is.

**Comment by eernstg** [comment]
Also, they don't seem to occur in ['current results'](https://dart-ci.firebaseapp.com/current_results/#/filter=co19/Language/Generics/typedef_A05_t01,co19_2/Language/Generics/typedef_A05_t01&showAll).

**Comment by sigmundch** [comment]
I may be misreading the code, but the stack trace looks suspicious. Not sure if that's a bug in our source-maps/deobfuscation or an issue in the AST the CFE produces, or an issue in DDC.

The [stack][1] has these lines:
```
Error: Expect.equals(expected: <X>, actual: <dynamic>) fails.
    at Object.throw_ [as throw] (http://127.0.0.1:34103/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4863:11)
    at Object._fail (http://127.0.0.1:34103/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-linux-release-chrome/tests_co19_2_src_Language_Generics_typedef_A05_t01/typedef_A05_t01.js:663:15)
    at Function.equals (http://127.0.0.1:34103/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-linux-release-chrome/tests_co19_2_src_Language_Generics_typedef_A05_t01/typedef_A05_t01.js:126:14)
    at checkme1 (http://127.0.0.1:34103/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-linux-release-chrome/tests_co19_2_src_Language_Generics_typedef_A05_t01/typedef_A05_t01.js:97:19)
    at result (http://127.0.0.1:34103/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:4907:33)
    at Object.main (http://127.0.0.1:34103/root_dart/out/ReleaseX64/generated_compilations/dartdevk-checked-linux-release-chrome/tests_co19_2_src_Language_Generics_typedef_A05_t01/typedef_A05_t01.js:109:5)
    at testMainWrapper (http://127.0.0.1:34103/root_build/generated_tests/dartdevk-checked-linux-release-chrome/tests_co19_2_src_Language_Generics_typedef_A05_t01/test.html?crossOriginPort=36933:85:90)
```

Deobfuscated error and stack:
```
Error: Expect.equals(expected: <X>, actual: <dynamic>) fails.
    at Object.throw_   out/ReleaseX64/gen/utils/dartdevc/kernel/amd/dart_sdk.js 4863:11
    at Object._fail    ../../../../../tests/co19_2/src/Utils/expect.dart 22:5
    at Function.equals ../../../../../tests/co19_2/src/Utils/expect_common.dart 31:5
    at checkme1        ../../../../../tests/co19_2/src/Language/Generics/typedef_A05_t01.dart 21:32
    at result          ../../../../lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 91:61
    at Object.main     ../../../../../tests/co19_2/src/Language/Generics/typedef_A05_t01.dart 33:5
    at testMainWrapper out/ReleaseX64/generated_tests/dartdevk-checked-linux-release-chrome/tests_co19_2_src_Language_Generics_typedef_A05_t01/test.html 85:90
```

Note that the line in main:
[tests/co19_2/src/Language/Generics/typedef_A05_t01.dart 33:5](https://github.com/dart-lang/co19/blob/d6e96f6d922b17fcf2e021e0f2b28835c861eb17/Language/Generics/typedef_A05_t01.dart#L33)

is a call to `checkme2`, but the stack contains `checkme1`. :shrug: 

[1]: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8842816711589129312/+/u/test_results/new_test_failures__logs_

**Comment by nshahan** [comment]
I have stepped through this test in chrome and it's not a sourcemap issue. The DDC compiled code is actually calling `checkme1` when it should be calling `checkme2`. It looks like the CFE change is not compatible with our current canonicalization at runtime. We have lost the bound on the type argument and now checkme2 and checkme1 are being canonicalized to the same value. I think this error is only triggered by generic functions where the type arguments are not present in the rest of the function signature (not in the arguments or the return type). In those cases our canonicalization still works.

I'll have to debug the old code a little to see what we were doing before to hopefully find a solution.

@johnniwinther To help me understand this change better, can you describe how the kernel representation of `checkme1` and `checkme2` changed? Hopefully with that I can alter our canonicalization to start working again in this case.

**Comment by johnniwinther** [comment]
@nshahan @sigmundch Thanks for investigating. The same test also fails on some of the [VM bots](https://github.com/dart-lang/sdk/issues/46550) so it might be a CFE problem. I'll take a closer look.

**Comment by nshahan** [comment]
> Also, they don't seem to occur in 'current results'.

@eernstg I see them there. Maybe the results hadn't been updated yet at the time that you looked.

**Comment by nshahan** [comment]
@johnniwinther I've looked into this more and there is definitely at least one bug on the DDC side with how functions are canonicalized. Even without your change running this code with DDC will incorrectly call the wrong function and print "fn".

```dart
fn<T>() {
  print('fn');
}

gn<T>() {
  print('gn');
}

typedef Test1<T>();

main() {
  const Test1 t1 = fn;
  const Test1 t2 = gn;
  t2();
}
```

**Comment by johnniwinther** [comment]
@nshahan The CL got reverted due to a problem with the Flutter roll: https://github.com/flutter/flutter/issues/85819 Can you if that is same underlying DDC problem?

**Comment by eernstg** [comment]
I just discussed this issue with @johnniwinther. I can see that there is a DDC canonicalization issue (perhaps there's a connection to https://github.com/dart-lang/sdk/issues/46568), but I don't see anything wrong with the eager canonicalizations.

**Comment by nshahan** [comment]
Closing this issue since the the change that caused the test failures was reverted. I am working on other changes that should hopefully avoid new failures when a new version lands but if so let's either reopen or file a new issue.
