### ISSUE TITLE
co19/LibTest/isolate/Isolate/kill_A01_t04 crashing on Windows

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#46541]
`co19/LibTest/isolate/Isolate/kill_A01_t04` started crashing on `dartkp-strong-win-release-x64`:
https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-precomp-nnbd-win-release-x64/258/overview

However, locally I can reproduce the issue at revisions earlier than the one crashing on bots (I stopped testing at 51ad1c620b21b017f3b64edeaed5d6b7a04978a2), so this is likely unrelated to the set of CLs that is started failing on on the bots.

**Comment by aam** [comment]
There is https://github.com/dart-lang/sdk/issues/45111 that tracks racing nature of current implementation of isolate message communication in dart vm.
