### ISSUE TITLE
proposal: allow automatic migration to late final

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#46555]
I propose an automatic migration to late final for a particular style of late initialization used in the dartdoc project (and possibly elsewhere?) prior to null safety. 

In order to emulate late initialization, dartdoc uses the following pattern (expanded using full if statements and blocks for clarity):

```dart
class A {
  final int y;
  A(this.y);
    
  int _x;
  int get x {
    if (_x == null) {
      _x = y + 1;
    }
    return _x;
  }
}
```

This way, we only run a computation once, and only if accessed -- essentially emulating the behavior of the current `late final`.  If migrated via the tool, the code could currently convert to:

```dart
// Null safe migration of A.
class A {
  final int y;
  A(this.y);
    
  int? _x;
  int? get x {
    if (_x == null) {
      _x = y + 1;
    }
    return _x;
  }
}
```

While this is an improvement, it doesn't really express what the pattern is intending, which is closer to this:

```dart
// Proposed migration example 1.
class A {
  final int y;
  A(this.y);
  
  late final int? x = () {
    int _x?;
    _x = y + 1;
    return _x;
  } ();
}
```

or even:

```dart
// Proposed migration example 2.
class A {
  final int y;
  A(this.y);
  
  late final int x = () {
    int _x = y + 1;
    return _x;
  } ();
}
```

The proposal is to leverage existing method-extraction to grab the block inside the `if null` and transform it into a closure, and then convert to a late final with a closure call if these conditions apply:

* `_x` is assigned only within the `if null` block.
* `_x` is not read outside of the `x` getter.
* There is no non-exception path to leave the `x` getter without returning `_x`.
* The `x` getter doesn't do anything outside the `if null` block except returning `_x`.
* There is no `x` setter, inherited or otherwise.

I think there's enough information in the analyzer to know whether these conditions are true so it seems plausible we could at least get to example 1.  Once converted to a closure call, the tracing of nullability might even allow transforming into example 2 or something else, better, TBD.

Here are some real-world examples of this pattern for inspiration.

A trivial example, from the dartdoc code:  https://github.com/dart-lang/dartdoc/blob/c9621b92c738ec21a348cc2de032858276e9c774/lib/src/model/class.dart#L345
A more complex example: https://github.com/dart-lang/dartdoc/blob/c9621b92c738ec21a348cc2de032858276e9c774/lib/src/model/class.dart#L355
A highly complex example, might not be migrateable since it uses helpers:  https://github.com/dart-lang/dartdoc/blob/c9621b92c738ec21a348cc2de032858276e9c774/lib/src/model/class.dart#L469

**Comment by jcollins-g** [comment]
I had thought something else was going on here and had clicked the wrong button to cancel a comment.  Reopened.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
