### ISSUE TITLE
tryParse could be nullable?

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#46564]
I have an issue with this code:
```dart
Map<String, String> map = {};
map['hello'] = '123';
int? something = int.tryParse(map['hello']); // uh oh!
```
tryParse accepts a non-null string. Therefore, I need to use `map['hello']!` but if hello doesn't exist, it gets even more verbose.
```dart
if (map['hello'] != null) {
    int? something = int.tryParse(map['hello']!);
    if (something != null) {
        doWhatIWant();
    } else {
       doSomethingElse();
   }
} else {
    doSomethingElse();
}
```
If tryParse propagated null, this wouldn't be needed.

My dream is still having String.toInt() one day, so that `'123'.toInt()` would be possible. In this nullable case, `map['hello']?.toInt()` could be used.

**Comment by lrhn** [comment]
There are no plans to change `int.tryParse` to accept a `null` argument.
It can't use a `null` for anything, and the caller is perfectly capable of detecting whether the argument it's null or not before calling. Allowing a `null` in a place where it's not *needed* can hide issues where something is *accidentally* `null` or nullable.

If you want to treat `null` the same as an invalid string, all you need to do is `int.tryParse(map['hello'] ?? '')`, then `tryParse` will return `null`.
