### ISSUE TITLE
DateTime.substract doesn't calculate correctly

### ISSUE THREAD

**Issue by dumabg** [dart-lang/sdk#46573]
This tracker is for issues related to:
* Dart core libraries
* Dart SDK Version:  2.13.4 
* Linux.

Code:
`var dateTime = DateTime(2022, 4, 1);
  print(dateTime);
  print(dateTime.subtract(Duration(days: 5)));`

dateTime.substract gives 2022-03-26 23:00:00.000, but it must give 2022-03-27 00:00

**Comment by II11II** [comment]
Hi @dumabg,
Does this appear only on a Linux machines?

**Comment by julemand101** [comment]
Sounds like another classic example on daylight saving time. Please read the note on `subtract` on `DateTime`:
> Notice that the duration being subtracted is actually 50 * 24 * 60 * 60 seconds. If the resulting `DateTime` has a different daylight saving offset than `this`, then the result won't have the same time-of-day as `this`, and may not even hit the calendar date 50 days earlier.
>
>Be careful when working with dates in local time.

https://api.dart.dev/stable/2.13.4/dart-core/DateTime/subtract.html

**Comment by lrhn** [comment]
This is indeed working as intended because `Duration` doesn't have a notion of calendar days, only milli/micro-seconds.

**Comment by dumabg** [comment]
> Hi @dumabg,
> Does this appear only on a Linux machines?

I have tested only on Linux
