### ISSUE TITLE
Implement recursive top-level inference

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46579]
Currently in the analyzer we do inference in two phases - first we resolve the initializer presuming all not yet inferred types of fields are `dynamic`. Then we get dependencies as elements referenced by the initializer, and infer in the topological order.

Type inference in the following code in the analyzer is done incorrectly.
```dart
class A {
  static final a = A.b.c;
  static final b = A();
  final c = a;
}
```

When we resolve the initializer of `a`, we see that it references `b`, but its type is presumed to be `dynamic`, so we don't know that it also references `c`. So, we miss the cycle `a -> c -> a`.

We should do something like CFE does, and perform recursive inference.

**Comment by stereotype441** [comment]
Note: I've just made an update to https://github.com/dart-lang/language/issues/1650 describing in more detail how the analyzer and CFE currently handle top level inference, and discussing options.  We may want to wait until a decision has been made on that issue before proceeding with this fix.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/206421 passes shared tests and smoke tests in google3.
I have not tested in on the whole google3 code base.

**Comment by scheglov** [comment]
Global presubmit looks green.
https://test.corp.google.com/ui#id=OCL:383979626:BASE:384026798:1625939487362:700fb7e6

**Comment by srawlins** [comment]
Is this still in the works, @scheglov ?

**Comment by scheglov** [comment]
It is up to the language team to decide here, whether they want to go with this change to inference.
This is tracked in https://github.com/dart-lang/language/issues/1650.

We probably should keep this open.

**Comment by scheglov** [comment]
@leafpetersen This is the issue about type inference that I mentioned as related to macro type inference.

**Comment by eernstg** [comment]
@scheglov wrote:
> It is up to the language team to decide here, whether they want to go with this change to inference

I just added a comment to dart-lang/language#1650, noting that there might not be a need to change anything in the spec.

**Comment by scheglov** [comment]
The CL landed, so I guess this can be marked fixed.
