### ISSUE TITLE
Follow-up improvements to async transform temp. var. typing

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#46588]
[Alex suggested](https://dart-review.googlesource.com/c/sdk/+/205647/comments/4d5a024d_e133ed19) some follow-up improvements to temporary variables in the async transform:

> Maybe we can put [async] temporary variables into more narrow scopes and make sure ScopeBuilder can reuse the same context slot for different local variables with non-intersecting scopes.

> Also, we should probably consider putting null to those temporary local variables after they were used, so we're not retaining references to results of sub-expressions and potentially extending their live ranges. That may help to reduce memory usage more than just reusing temporary variables for unrelated expressions.

> [...] measurements which would show the increase (or improvements) in memory usage. We might need to construct new benchmarks for that. Without such measurements the point of increasing memory usage is too theoretical.

This comes after changes to the way temporary variables are typed in b681bfd8d27 and [205647](https://dart-review.googlesource.com/c/sdk/+/205647) (see https://github.com/flutter/flutter/issues/51828 and https://github.com/flutter/flutter/issues/85311).

**Comment by alexmarkov** [comment]
Async kernel transformation was removed in https://github.com/dart-lang/sdk/commit/94c120a6ea5c7ab1f7bab3341cfa2bd03f313cf1, so this issue is no longer relevant.
