### ISSUE TITLE
in Queue<List> que, List is raw type or List<dynamic>?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#46584]
and:
`if (a is Future) {}`
Future in here is `Future<dynamic>` or raw type?
and in `Future aMethod() {}`
Future is `Future<dynamic>` or raw type?`

**Comment by Silentdoer** [comment]
ok, `Queue<List>`, List is `List<dynamic>`, `Future aMethod() {}`, Future is `Future<dynamic>`, if (a is Future) {}, Future is also `Future<dynamic>`

**Comment by eernstg** [comment]
A raw type in Dart is a type that denotes a generic class without actual type arguments. So `List` and `Future` are raw types, but `List<int>` and `Future<dynamic>` are not (they are parameterized types).

The meaning of a raw type is determined by the declaration of the type parameters. If there are no bounds then it's `dynamic`; so `Future` means `Future<dynamic>`. But with `class C<X extends num> {}`, `C` means `C<num>`. There are many more details, but a good starting point is: A raw type receives its bounds as actual type arguments, with `dynamic` as the default.
