### ISSUE TITLE
Error: Couldn't find constructor when using private constructor with mixin

### ISSUE THREAD

**Issue by felangel** [dart-lang/sdk#46581]
### Environment

* Dart SDK Version (`dart --version`)
`Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "macos_x64"`

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOSX

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A

### Reproduction Steps

Given a class `MyClass` defined in `my_class.dart`:

```dart
class MyClass {
  const MyClass._();
  const MyClass.named() : this._();
}
```

When `MyClass` is imported and extended (including a mixin) within `main.dart`:

```dart
import 'my_class.dart';

class TestClass extends MyClass with MyMixin {
  TestClass() : super.named();
}

mixin MyMixin {}

void main() {}
```

And the program is run via `dart main.dart` the following error occurs:

```sh
my_class.dart:3:27: Error: Couldn't find constructor 'MyClass._'.
  const MyClass.named() : this._();
```

### Expected

I would expect the code to run with no errors.

### Additional Information

When `MyClass` is defined within the same file (`main.dart`) the code runs successfully with no errors.
When `TestClass` does not use `MyMixin` the code runs successfully with no errors.
When `MyClass` does not define `const` constructors, the code runs successfully with no errors.

**Comment by lrhn** [comment]
I'm guessing this is a front-end issue, since it's the one resolving names.

The code should work.
