### ISSUE TITLE
Error compiling with meta 1.7.0

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/sdk#46583]
* Dart SDK Version (`dart --version`): 2.13.4
* Whether you are using Windows, MacOSX, or Linux (if applicable): Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): Chrome

I get the following messages trying to compile an Angular Dart project:

```
[INFO] Connecting to the build daemon...
[SEVERE] Failed to precompile build_runner:build_runner:
[SEVERE] ../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.40.6/lib/src/error/best_practices_verifier.dart:258:50: Error: The property 'displayString' is defined in multiple extensions for 'TargetKind' and neither is more specific.
[SEVERE]  - 'TargetKind' is from 'package:meta/meta_meta.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart').
[SEVERE] Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
[SEVERE]         var kindNames = kinds.map((kind) => kind.displayString).toList()
[SEVERE]                                                  ^^^^^^^^^^^^^
[SEVERE] ../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.40.6/lib/src/error/best_practices_verifier.dart:1917:14: Context: This is one of the extension members.
[SEVERE]   String get displayString {
[SEVERE]              ^^^^^^^^^^^^^
[SEVERE] ../../../.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart:91:14: Context: This is one of the extension members.
[SEVERE]   String get displayString {
[SEVERE]              ^^^^^^^^^^^^^
[SEVERE] ../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.40.6/lib/src/error/best_practices_verifier.dart:260:36: Error: The getter 'commaSeparatedWithOr' isn't defined for the class 'List<dynamic>'.
[SEVERE]  - 'List' is from 'dart:core'.
[SEVERE] Try correcting the name to the name of an existing getter, or defining a getter or field named 'commaSeparatedWithOr'.
[SEVERE]         var validKinds = kindNames.commaSeparatedWithOr;
[SEVERE]                                    ^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup
<asynchronous suspension>
#1      BuildDaemonClient.connect
<asynchronous suspension>
#2      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:28:12)
<asynchronous suspension>
#3      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:193:18)
<asynchronous suspension>
#4      DaemonCommand.run (package:webdev/src/command/daemon_command.dart:110:11)
<asynchronous suspension>
#5      CommandRunner.runCommand
<asynchronous suspension>
#6      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:40:12)
<asynchronous suspension>
#7      main
<asynchronous suspension>
Exited (255)
```

Setting a dependency_override to `meta: 1.6.0` seems to fix the problem

**Comment by mraleph** [comment]
@jakemac53 any ideas? is this WAI?

**Comment by jakemac53** [comment]
cc @scheglov who is more familiar with the issue

**Comment by scheglov** [comment]
See https://github.com/dart-lang/sdk/issues/46558

`meta 1.5.0` and `meta 1.7.0` have changes that we usually don't consider breaking - adding new top-level declarations. But practically they are, because they result in extension conflicts. This issue cannot be fixed in a published version of `analyzer`, but `analyzer 1.7.2` was patched to work with `meta 1.7.0`.

**Comment by jakemac53** [comment]
Ok, so it sounds like there are two potential solutions:

- Update to the latest analyzer (preferred approach)
- Restrict meta to `meta: <1.5.0`.
  - This may require using dependency overrides to get a version solve, which will introduce risk

Note that not updating analyzer is going to end up holding you back to older versions of other packages as well, and eventually it is likely to prevent you from updating your SDK.

**Comment by giorgiofran** [comment]
Unfortunately I had to set a dependency override like `meta: <1.7.0`.
This way it works, but I have opened this issue because I know that, in the long run, it is a risky move.

I cannot update to a recent version of `analyzer` because I'm an Angular Dart user.

**Comment by jakemac53** [comment]
> I cannot update to a recent version of `analyzer` because I'm an Angular Dart user.

Ok, that makes sense. It may be worth considering just checking in your `pubspec.lock` file to your repo, and only using `pub get`. That will ensure your package dependencies don't change and are consistent for everybody. You can occasionally run a `pub upgrade` to try and fetch new versions if you like, but will only run into potential problems when doing that.
