### ISSUE TITLE
when factory method arg name is generic type, should be warning

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#46594]
```dart
class Uk<T> {
  T mm;
  Uk.name(this.mm);
  factory Uk(T) {  // flag, this should be warning, T is dynamic T
    return Uk.name(T);
  }
}
```

**Comment by eernstg** [comment]
Looks like a case that would be flagged by https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html.

**Comment by eernstg** [comment]
Actually, it doesn't work, but I created an [issue](https://github.com/dart-lang/linter/issues/2769) on that. ;-)
