### ISSUE TITLE
dart analysis server's organize_imports seems to ignore sections

### ISSUE THREAD

**Issue by NANASHI0X74** [dart-lang/sdk#46597]
I'd like to organize my imports so that dart/flutter(_gen) imports, 3rd party libraries and imports from the current project each have their own section, but each time I use the `organize imports` code action the sections are broken up again and the imports are instead regrouped into one section of dart: imports and one for everything else, which are both sorted alphabetically. This leads to some third party library imports coming after my own package:$CURRENT_PROJECT imports, which I find very undesirable.

I'd like to use the code action though to automatically remove unused imports and sort imports alphabetically. But the behavior of the code action which ignores my own grouping of imports into different sections does not meet my personal needs. I'd like the action instead to sort imports alphabetically within sections, but not merge them, and order the sections according to the normal priority rules (i.e. dart: imports section comes first for example).

Is this how the code action is supposed to behave or am I doing something wrong/missing some configuration options or something? If the former, would you consider changing the behavior to what I described?

Dart/flutter version:
```
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (7 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```
platform Linux

**Comment by bwilkerson** [comment]
> Is this how the code action is supposed to behave or am I doing something wrong/missing some configuration options or something?

Yes, that's how the code action is intended to behave. The [style guide](https://dart.dev/guides/language/effective-dart/style#ordering) defines this ordering for directives and the action conforms to the style guide.

> If the former, would you consider changing the behavior to what I described?

I can't say that we would never support a different ordering, but we generally build tools that conform to the style guide, so it isn't currently a planned effort.

**Comment by NANASHI0X74** [comment]
ah, I see. Well, I've read the styleguide and it does not specify that you shouldn't separate your package: imports into different sections, that was not quite clear.

So as I read it, doing that does conform to the style guide.

**Comment by bwilkerson** [comment]
While it doesn't explicitly state that you can't have blank lines within a section, it does say that

> Each “section” should be separated by a blank line.

which I think we took to mean that blank lines shouldn't appear _within_ sections because they're being used to _separate_ sections. I don't personally have any problem with the style you're proposing, but I do think that it's different than what the style guide is suggesting. Also, the cost of changing both the action and the associated lint rule (which we keep in sync) is probably prohibitively high at this point given the number of users that are using both.

**Comment by mraleph** [comment]
I will tentatively close based on @bwilkerson last comment.

**Comment by NANASHI0X74** [comment]
hmm. Would there be a more appropriate place to propose this for the style guide itself?

**Comment by bwilkerson** [comment]
@munificent
