### ISSUE TITLE
[CP][beta channel] Merge fix for dart_style 2.0.2 roll

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#46598]
**commit(s) to merge**: 6c92e18952e21ee2e94603ffa73adc79a55f85f1

**merge instructions**: clean merge to origin/dev.  The branch point for the next beta is already passed, and
the fix is not in that branch point.  If a new branch point is picked, this CP will not be needed.

**What is the issue**: The published version of dart_style 2.0.2 has a different hash than the one in the DEPS.

**What is the fix**: Change the pinned hash of dart_style in DEPS to the 2.0.2 release

**Why cherrypick**: The correct dart_style commit reports 2.0.2 from "dart format --version". 

**Risk**: Low.  The changes are in dart_style's version number constant and pubspec.yaml, which is not used in the SDK
  checkout.  No change to behavior in the Dart SDK is expected except the version number.

**Link to original  issue(s)**: https://github.com/flutter/flutter/issues/86326

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by franklinyow** [comment]
SCRUM approved

**Comment by franklinyow** [comment]
CC: @zanderso @christopherfujino

**Comment by whesse** [comment]
No action will be taken until we create the beta branch for this branch point.
I propose creating the -301.1.beta version identical to -301.0.dev, and then creating the -301.2.beta version with this cherry pick, when we create the beta channel next week.

**Comment by whesse** [comment]
This is now merged into 2.14.0-301.2.beta, at https://dart.googlesource.com/sdk/+/3cc4208a482a84bffcf09ceb8fdd85001cd43e19
