### ISSUE TITLE
The Dart process still remains even after the process is completed

### ISSUE THREAD

**Issue by myConsciousness** [dart-lang/sdk#46606]
Thanks for this amazing development.

I don't know if this is directly related to the Dart language, but during development using Dart, after debugging and checking the screen in the local environment, the process remains even after the screen is closed and debugging is completed.

I recently investigated the cause of my laptop's high battery drain and CPU load, and found that there were several Dart processes left that should have been terminated as described above, some of which remained for more than 100 hours after termination.

I'm sorry if a similar event has already been reported as an issue.

**Comment by mraleph** [comment]
Thanks for taking time to report an issue. We will need more information to diagnose it. 

What are these processes that are left behind? Are they your processes which failed to quit even though you stopped the debugging session (e.g. using STOP button in the IDE) or are these auxiliarly processes that IDE launches (e.g. Dart analysis server, Dart development service etc).

**Comment by mit-mit** [comment]
@myConsciousness can you kindly supply the requested information?

**Comment by myConsciousness** [comment]
Sorry I was hard to find the time to come here.

In case you're wondering, I'm using a Macbook with an M1 silicon chip. I don't know the details of this event, because I only saw it after some event happened, but I think it is reproducible, because this event has been happening on my local machine since I published this issue.

I am using the Dart language with VSCode to do Flutter development. I have noticed that when I run `flutter run` and exit the emulator after checking the screen, the Dart process that was running in the emulator seems to remain. In fact, this has been happening frequently in the past week, and I have to manually kill the process after finishing the screen check using the emulator.

**Comment by jerryzhoujw** [comment]
I think if you not close vscode, the dart will be remaining there cause the language server is still working.  Not sure if it's correct.

**Comment by myConsciousness** [comment]
@jerryzhoujw 

That's true, but when I checked the process list for the first time, there were nearly 30 Dart processes left that should have been terminated, and some of them had been running for over 100 hours.

**Comment by mit-mit** [comment]
Sorry @myConsciousness but without more detail, and a set of repro steps, this is too unclear for us to investigate. From your description this could be a potential issue in anything from VSCode to the `flutter` tool to the Dart core libraries.

**Comment by mit-mit** [comment]
Closing as unactionable
