### ISSUE TITLE
Dart migrate duplicate applied

### ISSUE THREAD

**Issue by ybin0823** [dart-lang/sdk#46607]
We started `dart migrate` from `flutter 1.22.6` to `flutter 2.0.3`.

## 1. I can't check files.
As far as I remember, in the past file selection was possible. Why not now?
[Before]
![image](https://user-images.githubusercontent.com/7553607/125570308-5a765983-5243-4e24-92af-cf0f5720bf48.png)

[After]
![image](https://user-images.githubusercontent.com/7553607/125570407-f8f5d642-e607-4c47-b3f2-3b9189d4a4f7.png)

## 2. Duplicate applied
![스크린샷 2021-07-14 오후 2 51 18](https://user-images.githubusercontent.com/7553607/125570485-d536abc4-b0f8-4d3f-b8fb-f9de627f3334.png)

I knew that it was fixed by performing `dart migrate` several times. As shown in the picture, if it is performed the second time, it will be applied repeatedly like `??`.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
