### ISSUE TITLE
VmService `onTimelineEvent` stream sending duplicate event blocks

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#46605]
Currently trying to workaround this in DevTools by storing a set of all the event block timestamps we have currently received, and not processing timeline events for a block if we have already seen a block of events with the same timestamp.
@bkonyi

**Comment by kenzieschmoll** [comment]
Interestingly, even with removing duplicate blocks (matching on the timestamp of the block), we are still seeing duplicate traces.

**Comment by kenzieschmoll** [comment]
I will add notes here as I discover things. I have noticed that events from the very first block tend to be repeated.

**Comment by bkonyi** [comment]
I'm unable to reproduce. Feel free to re-open if you start seeing it again.
