### ISSUE TITLE
HttpClient setClientAuthoritiesBytes not working

### ISSUE THREAD

**Issue by alexrainman** [dart-lang/sdk#46615]
Steps to Reproduce

Load .p12 file from assets

```
ByteData keystore = await rootBundle.load('assets/security/client.p12');
final String passPhrase = "mypassphrase";
```

Set SecureContext

```
SecurityContext sc = SecurityContext();
sc.setClientAuthoritiesBytes(keystore.buffer.asInt8List(), password: passPhrase);
HttpClient client = HttpClient(context: sc);
```

Run a post

```
final request = await client.postUrl(Uri.parse('myserveruri'));
request.headers.set(HttpHeaders.contentTypeHeader, "application/json");
request.add(json.encode(body).codeUnits);
final response = await request.close();
```

Error:

```
Exception has occurred.
HttpException (HttpException: , uri = myserveruri)
```

The p12 contains the private key. Similar configuration works on native Android, iOS and Xamarin.

What im doing wrong here?

I tried providing the client.crt and client.key like this:

```
ByteData clientcrt = await rootBundle.load('assets/security/client.crt');
ByteData clientkey = await rootBundle.load('assets/security/client.key');
final String passPhrase = "mypassphrase";
SecurityContext sc = SecurityContext();
sc.setClientAuthoritiesBytes(clientcrt.buffer.asInt8List());
sc.usePrivateKeyBytes(clientkey.buffer.asInt8List(), password: passPhrase);
HttpClient client = HttpClient(context: sc);
```

It does not work either.

**Comment by mraleph** [comment]
As I have [explained](https://github.com/dart-lang/sdk/issues/37173#issuecomment-879903596) before `setClientAuthoritiesBytes` is for _server_ sockets. The [documentation](https://api.dart.dev/stable/2.9.0/dart-io/SecurityContext/setClientAuthoritiesBytes.html) is pretty clear on that one

```
  /// Sets the list of authority names that a [SecureServerSocket] will advertise
  /// as accepted, when requesting a client certificate from a connecting
  /// client.
```

You need to use `useCertificateChainBytes` and `usePrivateKeyBytes`. If your server certificate does not pass validation against default trusted root CAs then you might also need to use `setTrustedCertificates` on the client side.

You can take a look at [this test](https://github.com/dart-lang/sdk/blob/master/tests/standalone/io/secure_server_client_certificate_test.dart), which verifies that client correctly sends its certificate to the server (if server requires client to send one) to see how to properly set things up.

**Comment by alexrainman** [comment]
This is driving me crazy.

I removed the client certificate requirement from my backend running on App Service on Azure, and still cannot connect from dart/flutter.

Tried with http, HttpClient and Dio, which is a wrapper of HttpClient, and i get random errors.

With http and HttpClient i get:

```
Exception has occurred.
ClientException
```

With Dio i get:

```
Exception has occurred.
DioError (DioError [DioErrorType.other]: HttpException: , uri = https://mmanow-sandbox.azurewebsites.net/news/MMA%20Now
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
<asynchronous suspension>
)
```

Now certificate is not required, just an ApiKey, and i am sending the required header.

I thought it was related to TLS 1.2, but not, changing it on the App Service to a lower version doesn't make a difference.

I run the same api locally and i can connect.

I can also connect to the same App Service on Azure with Postman, i just cannot connect from dart/flutter.

Any ideas?
