### ISSUE TITLE
How to make the result of strong-mode (implicit-casts/implicit-dynamic) analysis as warning, instead of error?

### ISSUE THREAD

**Issue by wigl** [dart-lang/sdk#46624]
My project has been developed for almost a year, and I didn’t use stricter static checks at the beginning, which resulted in a lot of bugs.
Now I want to add strong-mode (implicit-casts/implicit-dynamic) to analysis_options.yaml, But after that, 5k errors were displayed!
![image](https://user-images.githubusercontent.com/12051109/125794485-65d1f282-56d7-42f6-80f1-f11f00fd13ef.png)

I can't modify them all at once. Can I display this error as warning? In this way, I will pay attention to this warning in future development, and the historical code not need modified temporarily.
thanks.

**Comment by wigl** [comment]
I haven't solved this problem. It was closed because a new [issue](https://github.com/dart-lang/sdk/issues/46624) was created in [dart-lang/sdk](https://github.com/dart-lang/sdk).

There are some problems with adding `analysis_options.yaml` in sub-directory:
1. We also need to add `pubspec.yaml` in the subdirectory, otherwise the analyzer will not execute.
2. If `pubspec.yaml` is added, the sub-directory will as a package.

**Comment by srawlins** [comment]
@wigl you can change the severity of different error codes. [See this page](https://dart.dev/guides/language/analysis-options#customizing-analysis-rules). You might set some codes to `ignore` temporarily, and you can work your way through the different codes enabled by those analysis options.
