### ISSUE TITLE
Add analyzer error for leaf FfiNative with handles.

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#46625]
Adding a multi-test with an expected compile-time error, does not fail as expected when run through `dartanalyzer`:
```
@FfiNative<Handle Function()>("foo", isLeaf: true)  //# 01: compile-time error
external Object foo();  //# 01: compile-time error
```
```
$ dart tools/test.dart -n analyzer-asserts-strong-linux -- ffi/ffi_native_test/01
ffi/ffi_native_test/01 is new and failed (Pass, expected CompileTimeError)
```

**Comment by eernstg** [comment]
I'm not working on the analyzer, but I did have some involvement in the new features added in 21Q1, so let me comment on the situation:

The constant constructor `FfiNative` does accept a type argument with no bound, and it does accept a positional argument of type `String` and a named argument `isLeaf` of type `bool`. With the small-features-21Q1 enabled, it is allowed for metadata to have type arguments. In other words, it looks like there is no error in the first case.

Next, the `external` function declaration is connected to an implementation by each runtime in an implementation specific manner, so I wouldn't expect the analyzer to be able to determine whether or not there is a binding. Again, I can't immediately see any errors.

Maybe there aren't any errors?

**Comment by cskau-g** [comment]
Thank you, Erik.
I'm afraid I didn't fully explain the what I meant, so let me elaborate.

The compile-time error in the above example is that FFI leaf calls can't have return or argument types of Handle. (This is an FFI limitation.) 
We added a special check for this in the kernel transform here:
https://github.com/dart-lang/sdk/blob/d3e1cdfb16b811c5e703807afd48014dbad655f7/pkg/vm/lib/transformations/ffi_use_sites.dart#L875-L877

So the above example yields a compile-time error when run normally, but it does not when run through `dartanalyzer`.

But I should also point out that the example is just one case, and I imagine this affects other similar compile-time errors.

**Comment by eernstg** [comment]
OK, thanks for the explanation!

**Comment by bwilkerson** [comment]
@dcharkes Will you be adding this check, or should someone on the analyzer team do so?

**Comment by dcharkes** [comment]
That would be either @cskau-g or the analyzer team. @cskau-g added the `FfiNative`s to `dart:ffi`.

**Comment by cskau-g** [comment]
I was the one who added `_ensureLeafCallDoesNotUseHandles(..)` so that responsibility probably falls on me before Daco.
But I don't know how these checks are usual added?

I should probably also mention that this issue isn't urgent from our side. I created this issue mainly for tracking.

**Comment by bwilkerson** [comment]
The checks are implemented in the class `FfiVerifier` in the file `pkg/analyzer/lib/src/generated/ffi_verifier.dart`. I'm happy to be a resource to answer questions while you're working on it.

**Comment by cskau-g** [comment]
Ah, I was under the incorrect impression that this was a general matter of surfacing the existing compile-time error from `dart` through `dartanalyser`, but I see we just need to add a parallel error to analyzer.
I'll take this one.

Thanks for clarifying @bwilkerson.
