### ISSUE TITLE
dart format hangs when reading from stdin

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#46636]
```
echo 'main() {}' | dart format
```

This will print `main() {}` and then hang.

cc @bkonyi @munificent 

This is with the latest dev release `Dart SDK version: 2.14.0-312.0.dev (dev) (Tue Jul 13 15:32:06 2021 -0700) on "linux_x64"`

**Comment by fishythefish** [comment]
FWIW this seems to be working on master.

**Comment by mraleph** [comment]
Duplicate of #46600
