### ISSUE TITLE
Apparent memory corruption with profiler enabled running on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#46643]
**[Original issue](https://github.com/flutter/devtools/issues/3201)**

Dart code that runs correctly without a profiler enabled produces incorrect results when the profiler is enabled on the Windows Subsystem for Linux.

Here's some relatively small code sample that reproduces the issue:
```
bool isSanitary(String name) {
  return name == sanitize(name);
}

String sanitize(String initialName) {
  var newName = initialName.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
  return newName;
}

void main(List<String> arguments) {
  print('Hello world!');
  for(var i = 0; i < 10000; i++) {
    var str = 'x';
    for(var j = 0; j < i; j++) {
      if(!isSanitary(str)) {
        print(i);
        print(j);
        print(str);
        throw Exception('not sanitary');
      }
      str += 'x';
    }
  }
}
```

When running or debugging this code without a profiler, it runs to completion with no exceptions, and just the `Hello world!` print message.

When the CPU profiler is enabled, however, this does not work.  An example output when the profiler is enabled looks like this:
![image](https://user-images.githubusercontent.com/75506197/125674341-a6a0ed8e-29f2-4384-89b3-84b144133092.png)

When I paste this into GitHub, it seems to remove the whitespace characters, so maybe they are some sort of weird character.
```
Hello world!
493
257
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

The numbers for `i` and `j` seem to be a bit random, it doesn't happen at the same time every time.

I'm running with Dart SDK version: 2.13.4 on WSL1 Ubuntu 18.04.4 LTS with Visual Studio Code.  The issue reproduces whether the CPU Profiler is opened as a tab within vscode or in a Chrome browser.

To reproduce:
- Set a breakpoint at `print('Hello world!');`
- Start debugging and wait until breakpoint is hit
- Start the CPU Profiler, "Enable profiler", and hit record
- Resume debugging
- Exception `not sanitary` will hit

**Comment by bkonyi** [comment]
FYI @eseidelGoogle

**Comment by aam** [comment]
Interestingly inlining all of `SignalHandler::GetProgramCounter`, `GetFramePointer`, ... in https://github.com/dart-lang/sdk/blob/master/runtime/vm/thread_interrupter_linux.cc#L42 fixes the assert/corrupted memory.
Having even just one of those SignalHandler::* calls in `ThreadInterruptSignalHandler` still results in an assert.
@rmacnak-google I think this supports your theory that the problems are caused by size of red zone(or its absence) on WSL.

**Comment by aam** [comment]
Seems like the problem is only present on WSL v1, while on WSL v2 everything works as expected.

**Comment by bkonyi** [comment]
Seems like Microsoft typically [recommends use of v2 for most use cases](https://docs.microsoft.com/en-us/windows/wsl/compare-versions).

**Comment by mkorbel1** [comment]
Confirming that this only happens for me on WSL1 as well.  WSL2 seems to resolve the issue.

**Comment by aam** [comment]
Given that it works on WSL2, this is unlikely to be looked at.
