### ISSUE TITLE
Analysis bug when add abstract final fields in mixin with const constructor

### ISSUE THREAD

**Issue by windrunner414** [dart-lang/sdk#46641]
```
mixin A {
  abstract final int b;
}

class B with A {
  @override
  final int b;
  const B(this.b);
}

void main() {
  print(B(123).b);
}
```

This code run normally but I get a analysis error `This constructor can't be declared 'const' because a mixin adds the instance field: 'A.b'.
Try removing the 'const' keyword or removing the 'with' clause from the class declaration, or removing the field from the mixin class.`

**Comment by eernstg** [comment]
Yes, that's true: An abstract final instance variable denotes an abstract getter and should be treated as such.

**Comment by windrunner414** [comment]
@eernstg  Should abstract final be considered the same as getter? abstract final with built_value will report an error says should use getter. Will abstract final be different from getter in the future? (But at least in const, they should be the same)

**Comment by srawlins** [comment]
@eernstg can you point me to spec text (or a proposal in the language repo) that spells this out? I'm not finding any definitions of abstract fields at https://spec.dart.dev/DartLangSpecDraft.pdf, nor in the NNBD feature spec.

**Comment by srawlins** [comment]
Ah, found it, in `future-releases`: https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/feature-specification.md.

> An abstract instance variable declaration D is treated as an abstract getter declaration and possibly an abstract setter declaration. The setter is included if and only if D is non-final.
