### ISSUE TITLE
Bad dart:core floor performance

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#46650]
## Function in question

While porting some Java code to Dart (@KdotJPG's OpenSimplex2 code, see [package](https://github.com/creativecreatorormaybenot/funvas/tree/main/open_simplex_2)), I came across the following function (comments + Dart port by me):

```dart
int fastFloor(double x) {
  // We cannot simply return x.toInt() because casting to an integer floors
  // towards zero (truncates) and we want to floor towards negative infinity.
  final xi = x.toInt();
  return x < xi ? xi - 1 : xi;
}
```

## Performance issue

This made me wonder: why not simply use [`dart:core.floor`](https://api.dart.dev/stable/2.13.4/dart-core/num/floor.html)?

So I wrote some benchmark tests and I found out that `fastFloor` is about 20% faster than `floor` (ran on macOS).  
So why is that? And why would we not always use `fastFloor`?

## Version

```
Dart SDK version: 2.14.0-301.0.dev (dev) on "macos_x64"
```

**Comment by a-siva** [comment]
//cc @alexmarkov

**Comment by alexmarkov** [comment]
I wrote the following micro-benchmark to test performance of `double.floor()` and compare it against custom Dart code:

```dart
import 'package:benchmark_harness/benchmark_harness.dart';

const int N = 10000;

int fastFloor(double x) {
  // We cannot simply return x.toInt() because casting to an integer floors
  // towards zero (truncates) and we want to floor towards negative infinity.
  final xi = x.toInt();
  return x < xi ? xi - 1 : xi;
}

class BenchFloor extends BenchmarkBase {
  BenchFloor() : super('BenchFloor');

  @override
  void run() {
    double x = 1.2;
    int result = 0;
    for (int i = 0; i < N; i++) {
      result += x.floor();
      x = x + 0.5;
    }
    if (result != 25005000) {
      throw 'Unexpected result: $result';
    }
  }
}

class BenchFastFloor extends BenchmarkBase {
  BenchFastFloor() : super('BenchFastFloor');

  @override
  void run() {
    double x = 1.2;
    int result = 0;
    for (int i = 0; i < N; i++) {
      result += fastFloor(x);
      x = x + 0.5;
    }
    if (result != 25005000) {
      throw 'Unexpected result: $result';
    }
  }
}

void main() {
  final benchmarks = [BenchFloor(), BenchFastFloor()];
  for (var benchmark in benchmarks) {
    benchmark.report();
  }
}
```

On my machine (linux/x64) I got the following results (best of 5 runs):

```
JIT/x64:
BenchFloor(RunTime): 303.81512987999395 us.
BenchFastFloor(RunTime): 147.609889298893 us.

AOT/x64
BenchFloor(RunTime): 763.1590995803128 us.
BenchFastFloor(RunTime): 503.88186397984884 us.
```

Indeed, on Linux the performance gap is even bigger.

15e5ec176235d4d5d82dd6de2c8f2586069e5c22 improves performance in JIT mode on x64 by using SSE4.1 roundsd instruction if it is available:
```
BenchFloor(RunTime): 135.00067499156262 us.
```

I'll continue looking at improving AOT performance of `double.floor()`. Related issue: https://github.com/dart-lang/sdk/issues/46876.

**Comment by creativecreatorormaybenot** [comment]
@alexmarkov You broke my CI on the master channel 😂 I wrote unit tests that confirmed the `fastFloor` performance was better than `double.floor` and that is not the case anymore on `master` 🙃 

See https://github.com/creativecreatorormaybenot/funvas/runs/3329292332?check_suite_focus=true.

**Comment by alexmarkov** [comment]
Micro-benchmark results in AOT mode after the latest improvements in `double.floor()` and `double.toInt()` performance:

```
AOT/x64
BenchFloor(RunTime): 321.05601926163723 us.
BenchFastFloor(RunTime): 136.54061987984707 us.
```

**Comment by alexmarkov** [comment]
Micro-benchmark results after the last optimization of `double.floor()` (best of 5 runs):

```
JIT/x64
BenchFloor(RunTime): 134.67827082351357 us.
BenchFastFloor(RunTime): 147.83206445413555 us.

AOT/x64
BenchFloor(RunTime): 134.0217784627756 us.
BenchFastFloor(RunTime): 135.97865252566456 us.
```

**Comment by creativecreatorormaybenot** [comment]
@alexmarkov thanks, that is super sweet! love it ❤️
