### ISSUE TITLE
Test that fail in spec parser have no errors in CFE and Analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#46659]
The following co19 tests have no errors in CFE and Analyzer but fail on specification parser.

[co19/Language/Libraries_and_Scripts/URIs/syntax_t01](https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/URIs/syntax_t01.dart)
[co19/Language/Libraries_and_Scripts/URIs/syntax_t03](https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/URIs/syntax_t03.dart)
[co19/Language/Libraries_and_Scripts/URIs/syntax_t05](https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/URIs/syntax_t05.dart)
[co19/Language/Libraries_and_Scripts/URIs/syntax_t11](https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/URIs/syntax_t11.dart)
[co19/Language/Libraries_and_Scripts/URIs/syntax_t13](https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/URIs/syntax_t13.dart)
[co19/Language/Libraries_and_Scripts/URIs/syntax_t15](https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/URIs/syntax_t15.dart)
[co19/Language/Libraries_and_Scripts/Imports/syntax_t15](https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/Imports/syntax_t15.dart)

@eernstg is this a tools or spec parser issue?

**Comment by eernstg** [comment]
This is a spec parser issue, addressed in https://dart-review.googlesource.com/c/sdk/+/208880.

**Comment by eernstg** [comment]
Landed.
