### ISSUE TITLE
Expose `OS::GetCurrentMonotonicTicks` as `Dart_TimelineGetTicks`

### ISSUE THREAD

**Issue by iskakaushik** [dart-lang/sdk#46665]
`Dart_TimelineGetTicks` will serve as the default monotonic timestamp provider for the Flutter Engine. This will allow the Engine and Dart timeline events to be backed by the same clock. We would like to use this new API rather than `Dart_TimelineGetMicros` as all of the engine clocks are currently backed by nano second clocks.

See:

1. Plan to unify dart and flutter timeline clocks: [LINK](https://docs.google.com/document/d/1Sx8QA1qXgJGw5r4ESviDnU2LSShNHiq_LjbRWPgSvXQ/edit?resourcekey=0-BoBvLxgqf_nc_rwLc0zmTw#)
2. https://github.com/flutter/flutter/issues/76875

cc: @zanderso , @chinmaygarde

**Comment by iskakaushik** [comment]
It will be important that this API be usable after `Dart_Cleanup` as well. As we expect to log events after the VM shutdown as well. Based on a cursory glance at `OS::GetCurrentMonotonicTicks` looks like it shouldn't be a problem, but wanted to confirm. Thanks!

**Comment by a-siva** [comment]
So you would like us to add a new API call as follows
DART_EXPORT int64_t Dart_TimelineGetTicks() {
  return OS::GetCurrentMonotonicTicks();
}

I noticed that on the Windows platform when QueryPerformanceCounter is not supported it ends up returning  GetCurrentTimeMicros() I hope that is ok.

Dart_Cleanup() will have no effect on this.

**Comment by iskakaushik** [comment]
@a-siva that sounds good to me, thanks!

**Comment by a-siva** [comment]
There seems to be nothing Dart specific in this, what is the rationale for putting it in the Dart API and not implementing it directly in the engine ? Is it just the convenience that we already have the implementation in the VM codebase ?

**Comment by zanderso** [comment]
I'm not sure if Kaushik had another reason in mind, but I think there is an advantage to the VM and the Engine using the same clock by construction rather than just by agreement. Another way to get the same thing would be for the Engine to give a clock to the VM, but my guess is that that would be more complicated.

**Comment by iskakaushik** [comment]
@zanderso is right, wanted to avoid duplicating all the platform specific code. This also makes the contract more concrete. Right now, it just happens that our clocks match up on all non-darwin platforms, but this would make that match 100% of the time. Also more reasoning in go/flutter-engine-clocks.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/207900
