### ISSUE TITLE
Http parser replies with error if both Content-Length and Transfer-Encoding supplied. Too strict maybe?

### ISSUE THREAD

**Issue by flekken** [dart-lang/sdk#46670]
Hi!

I am using Flutter 2.2.2 with Dart 2.13.3 to build an Android and iOS app. I am using a rest api and this is where I found the following problem.

When the server respond it sends both Content-Length and Transfer-Encoding headers.
Example:
```
HTTP/1.1 200 OK
Date: Tue, 22 Jun 2021 09:59:16 GMT
Transfer-Encoding: chunked
Content-Length: 188
Content-Type: application/json
```
Dart throws an exception for this case [coming from http_parser](https://github.com/dart-lang/sdk/blob/6a8e74e6562f2661a9f5ef6f456fbe2b4e79dfde/sdk/lib/_http/http_parser.dart#L692).

HttpParser is built according to RFC 2616 which say in point 4.4.3:

> The Content-Length header field MUST NOT be sent if these two lengths are different (i.e., if a Transfer-Encoding header field is present).

The problem is RFC 2616 also say this in the same passage:

> If a message is received with both a Transfer-Encoding header field and a Content-Length header field, the latter MUST be ignored.

This means to me that Dart's HttpParser is too strict. Also if I read this correctly a [pull request changed this recently to be this way.](https://github.com/dart-lang/sdk/commit/ee37fff58cf189ba677e9f49aaa6b305133a753d#diff-df40de065164c2757ae1178963130ee5cae09dd238880f3d172755515c9bf99f)

Can someone shed some light why this became more strict? Wouldn't it be better if this were more loose?

Thank you!

My dart --version:
Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "macos_x64"

**Comment by mit-mit** [comment]
cc @aam

**Comment by aam** [comment]
from [rfc-7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2):
```
   A sender MUST NOT send a Content-Length header field in any message
   that contains a Transfer-Encoding header field.
...

**Comment by flekken** [comment]
Thank you for your answer. Linked rfc explains if both headers present then there is a possible vulnerability to response splitting or request smuggling.

**Comment by aam** [comment]
You are welcome!
