### ISSUE TITLE
FFI : Failed to load dynamic library

### ISSUE THREAD

**Issue by starsice** [dart-lang/sdk#46689]
Hi, I have a problem,
### dart --version
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "windows_x64"
### operating system
Windows 10 1809
### code
I try to run on windows vm very simple code :

```
import 'package:myfirst/test2.dart' as test2;
import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:ffigen/ffigen.dart';
import 'package:myfirst/example.dart';

void main() {
  print('Hello world: ${test2.calculate()}!');


  var libraryPath = path.join(Directory.current.path, 'lib', 'libusb-1.0.dll');
  final a = DynamicLibrary.open(libraryPath);

  var libraryPath2 = path.join(Directory.current.path, 'lib', 'USB2XXX.dll');
  final b = DynamicLibrary.open(libraryPath2);
}
```

### error
when I run it in vs code get error:

```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'C:\Users\adidas\Desktop\dart\test1\lib\USB2XXX.dll': 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      main                                           bin\test1.dart:29
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

Exited (255)
```
### More
I successfully loaded `libusb-1.0.dll`, but `USB2XXX.dll` failed. Why, am I missing something?

I am using the dll here: https://gitee.com/toomoss/USB2XXX_Example/tree/master/sdk/libs/windows/x86_64
help pls😊

**Comment by dcharkes** [comment]
The error code that Windows returns is 126.

> Error 126 is what you get when a dependent DLL can not be found.

https://stackoverflow.com/search?q=windows+126

**Comment by starsice** [comment]
@dcharkes ,Thanks！At your prompt, I found that the dll file depends on `MSVCR100.dll`.After I installed the `Microsoft Visual C++ 2010 SP1 Redistributable Package (x64)`, the problem was solved.😄
