### ISSUE TITLE
DateTime should be able to tell me the time in a time zone, and whether DST is in effect

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#46683]
The `DateTime` class has no way to determine the time in, say, the Pacific Daylight Time time zone.

Sure, if you _happen_ to have your machine running in that time zone, you can call `DateTime.now()` and get the right time there, but if your servers are running on UTC time, and you want to convert to PDT, you need to implement your own DST conversion algorithm to know if the `America/Los_Angeles` time zone is UTC-7 or UTC-8 at the current time.

This is something that Dart should be providing as a basic SDK service.

I'd like to see an API like `DateTime.now().isDaylightSavings`, and `DateTime.now(zone: 'America/Los_Angeles')`, which takes into account DST, or `DateTime.now(zone: 'UTC-8')`, which just does an 8-hour offset from UTC (Yes, you can already do that with `DateTime.now().toUtc().subtract(const Duration(hours: 8))`, so I guess not required, but nice to have).

For the zones, it could support the values in the ICANN [`tz` database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

Most operating systems have the facility for getting time in a time zone built-in, so it shouldn't increase executable size much, or require us to maintain our own DST database.

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
> The `DateTime` class has no way to determine the time in, say, the Pacific Daylight Time time zone.

Correct. The `DateTime` class is not aware of any time zones other than UTC and "local time". If PDT is not your local time, there simply is no information available to give the results you want. You need a more complicated time-zone aware class.

The restrictions on `DateTime` comes partly from needing to be compatible with the JavaScript `Date` class (which has the same restrictions) and partly from not wanting each application to have to include a large time zone database just to be able to (potentially) handle arbitrary time zones.

Even if the operating systems have the information, JavaScript still doesn't.

We have no current plans to introduce more features to the `DateTime` time zone management.

**Comment by gspencergoog** [comment]
Well, that's too bad.  OK.

For future archaeologists, this package does exist: https://pub.dev/packages/timezone
