### ISSUE TITLE
Nullable safety migration: for List<Object> I would like to migrate all to List<Object>/List<Object?> instead of List<Object?>?

### ISSUE THREAD

**Issue by jerryzhoujw** [dart-lang/sdk#46715]
I have run `dart migration` in my project which is  from `flutter 1.22.6` to `flutter 2.x`

I find the auto result include lots of `List<Object?>?`.

But for most of it, I need to change it back to `List<Object>` or `List<Object>?`

for most of the case, list with nullable object in it  `List<Object?>` is not my needed.

I would like this even there will be some build errors after run script, I can fix the fewer errors by hand, rather then to change lots of `List<Object?>` back to  `List<Object>`

I think the `fewer change needed by hand` is better than `fewer build error` need fixed by hand in migration case.

What do you think.

**Comment by srawlins** [comment]
Can you give minimal examples where the tool migrates something to `List<Object?>?`? Usually the `?` characters are highlighted and provide details about why the tool decided a type needed to be made nullable.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
