### ISSUE TITLE
How can i get a Uint32List from ByteData?

### ISSUE THREAD

**Issue by sososdk** [dart-lang/sdk#46729]
Dart:  2.13.4

```dart
final WriteBuffer buffer = WriteBuffer();                        
buffer.putUint8(0);                                              
buffer.putUint8(0);                                              
buffer.putUint8(8);                                              
buffer.putUint32(1);                                             
buffer.putUint32(2);                                             
buffer.putUint32(3);                                             
final ByteData byteData = buffer.done();                         
                                                                 
byteData.buffer.asUint8List(0, 3);                               
byteData.buffer.asUint32List(3, 3);    // throw RangeError: Offset (3) must be a multiple of BYTES_PER_ELEMENT (4)
```

The above method threw an exception. What is the correct method?

**Comment by lrhn** [comment]
Dart typed data lists *must* always be aligned inside their buffer. You can't create a `Uint32List` which accesses the values you wrote at offset 3 of the buffer.

Either put an extra byte before the Uint32's to align them, so you can do `byteData.buffer.asUint32List(4, 3)` instead, or you'll have to read the values out using the `ByteData` methods:
```dart
var firstNumber = byteData.getUint32(3);
```

**Comment by sososdk** [comment]
Hello @lrhn , maybe we need a method to generate a new `Uint32List` with an aligned buffer. 🤔

**Comment by lrhn** [comment]
Creating an aligned buffer can be done. It's a little cumbersome because you have to work at the byte level:
```dart
var words = byteData.buffer.asUint8List().sublist(3, 3 + 3 * Uint32List.bytesPerElement).buffer.asUint32List();
```
That is: View the bytes as a `Uint8List`, then use `sublist` to take out only the bytes you want (which will then be aligned), and then view those as a `Uint8List`.

Another version of the same thing:
```dart
var words = Uint8List.sublistView(byteData, 3, 3 + 3 * Uint32List.bytesPerElement).sublist(0).buffer.asUint32List();
```

**Comment by sososdk** [comment]
Thank you!
