### ISSUE TITLE
Go-to-Definition jumps to class when invoked on an unnamed constructor invocation

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#46725]
Given the following code:

```dart
class Foo {
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  Foo() {
    print('');
  }
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
}

final a = Foo();
final b = new Foo();
```

Invoking Go-to-Definition on either of the constructor calls at the bottom returns information for the class rather than the constructor implementation:

```
==> {
	"id": "244",
	"method": "analysis.getNavigation",
	"params": {
		"file": "/Users/danny/Desktop/dart_sample/bin/main.dart",
		"length": 0,
		"offset": 163
	},
	"clientRequestTime": 1627322197221
}
<== {
	"id": "244",
	"result": {
		"files": [
			"/Users/danny/Desktop/dart_sample/bin/main.dart"
		],
		"targets": [
			{
				"kind": "CLASS",
				"fileIndex": 0,
				"offset": 6,
				"length": 3,
				"startLine": 1,
				"startColumn": 7
			}
		],
		"regions": [
			{
				"offset": 162,
				"length": 3,
				"targets": [
					0
				]
			}
		]
	}
}
```

**Comment by scheglov** [comment]
I guess this is with LSP.
It seems to jump to the unnamed constructor with the classic protocol.

**Comment by DanTup** [comment]
@scheglov I saw it with both - the JSON above is the classic protocol. If you can't repro, I'll do some digging shortly. I actually noticed it in the Call Hierarchy I'm working on, which led me to test here and saw the same thing. I was knee-deep in changes though, so it's possible I messed something up.

**Comment by DanTup** [comment]
I think this is a difference between the navigation notification and the results from `getNavigation`. VS Code uses `getNavigation` also for non-LSP, but I suspect IntelliJ/AS maybe are using the notification.  If I look at the notification, it seems correct:

https://gist.github.com/DanTup/c2c8fdee50966e2a484e91ee3b585ecc#file-navigation_notification-json

But `getNavigation` does not:

https://gist.github.com/DanTup/c2c8fdee50966e2a484e91ee3b585ecc#file-get_navigation-json

Stepping through, I think it's happening when there's an offset/length and we use the node directly here:

https://github.com/dart-lang/sdk/blob/9db372e6f46964ab5c63b253869020e89b51fe26/pkg/analyzer_plugin/lib/utilities/navigation/navigation_dart.dart#L26-L31

It seems like when we start with an offset, `_getNodeForRange` returns the innermost node, which here is a `SimpleIdentifier` (and its `writeOrReadElement` is the `ClassElement`). When we start from the root, we get the `ConstructorName` wrapping it.

So if I naively just walk up the tree while the parent is the same offset/length, the results are correct:

```dart
    var node = _getNodeForRange(unit, offset, length);
    while (node != null &&
        node.parent != null &&
        node != node.parent &&
        node.offset == node.parent!.offset &&
        node.length == node.parent!.length) {
      node = node.parent;
    }
    node?.accept(visitor);
```

I'm not sure if this is the proper fix though?

**Comment by bwilkerson** [comment]
I'm not currently coming up with a concrete case where that wouldn't work, but theoretically it could step up to a node for which the visitor would not return any navigation information but where one of the skipped over children would have. I'd probably implement the fix you have as-is, and if we find a broken case in the future we can fix it then.
