### ISSUE TITLE
[analyzer] An explicitly instantiated instance method tearoff is parsed as starting with a prefix

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46721]
Consider the following program:

```dart
class A {
  List<X> m<X>(X x) => [x];
}

extension FunctionApplier on Function {
  void applyAndPrint(List<Object?> positionalArguments) =>
      print(Function.apply(this, positionalArguments, const {}));
}

void main() {
  var a = A();
  a.m<int>.applyAndPrint([2]);
  a.m<String>.applyAndPrint(['three']);
}
```

This program is rejected (as of ef8add038fcc6d4df171d04e8946be2ae56f1631) by `dartanalyzer` with the following error messages:

```
ERROR|COMPILE_TIME_ERROR|PREFIX_SHADOWED_BY_LOCAL_DECLARATION|/usr/local/google/home/eernst/lang/dart/scratch/202107/n038.dart|12|3|1|The prefix 'a' can't be used here because it is shadowed by a local declaration.
ERROR|COMPILE_TIME_ERROR|PREFIX_SHADOWED_BY_LOCAL_DECLARATION|/usr/local/google/home/eernst/lang/dart/scratch/202107/n038.dart|13|3|1|The prefix 'a' can't be used here because it is shadowed by a local declaration.
```

However, `a` is not an import prefix, it is a local variable. Presumably, the analyzer parser (or some other early step of the analysis) assumes that with constructs of the form `<identifier> '.' <identifier> <typeArguments> '.'`, the first identifier must be an import prefix. That may have been true before `constructor-tearoffs`, but it isn't true with that feature, so the analyzer will need to investigate the situation more closely before it concludes that it is looking at an import prefix.

**Comment by devoncarew** [comment]
cc @srawlins

**Comment by srawlins** [comment]
Must handle new rewriting spelled out in @stereotype441 's Constructor Tearoff parsing strategy doc.

Analyzer's resolver gets the following from the parser:

* ExpressionStatementImpl: (`a.m<int>.applyAndPrint([2]);`)
  * `._expression`: InstanceCreationExpressionImpl (`a.m<int>.applyAndPrint([2])`)
    * `._constructorName`: ConstructorNameImpl (`a.m<int>.applyAndPrint`)
      * `._type`: TypeNameImpl (`a.m<int>`)
        * `._name`: PrefixedIdentifierImpl (`a.m`)
          * `._prefix`: SimpleIdentifierImpl (`a`)
          * `._identifier`: SimpleIdentifierImpl (`m`)
        * `._typeArguments`: TypeArgumentListImpl (`<int>`)
      * `._name`: SimpleIdentifierImpl (`applyAndPrint`)

This must be re-written into something like:

* ExpressionStatementImpl: (`a.m<int>.applyAndPrint([2]);`)
  * `._expression`: MethodInvocationImpl (`a.m<int>.applyAndPrint([2])`)
    * `._target`: FunctionReferenceImpl (`a.m<int>`)
      * `._function`: PrefixedIdentifierImpl (`a.m`)
        * `._prefix`: SimpleIdentifierImpl (`a`)
        * `._identifier`: SimpleIdentifierImpl (`m`)
      * `._typeArguments`: TypeArgumentListImpl (`<int>`)
    * `._methodName`: SimpleIdentifierImpl (`applyAndPrint`)
