### ISSUE TITLE
Process.run and Process.runSync APIs on the web are inconsistent with the core API

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#46726]
In dart-lang/sdk@d44457f (reviewed in https://dart-review.googlesource.com/c/sdk/+/151121), the encoding parameters to `Process.run` and `Process.runSync` were changed to be nullable. This change landed in Dart SDK 2.10. However, the change didn't update the web versions of those libraries (https://github.com/dart-lang/sdk/blob/cf5587e8612a3e19b9f622444572ab69fb9321ac/sdk/lib/_internal/js_runtime/lib/io_patch.dart#L361-L381).

So when compiling for web, the dart:io API is currently broken.

https://github.com/google/process.dart/issues/64

@leafpetersen

**Comment by kevmoo** [comment]
CC @sigmundch

**Comment by sigmundch** [comment]
Thanks @tvolkert for filing the issue - preparing https://dart-review.googlesource.com/c/sdk/+/208145 to fix this shortly.

/cc @johnniwinther - I don't recall if we ever implemented checks in the `@patch` mechanism to validate that we are doing a valid patch, if so, this may be an inconsistency worth detecting.

**Comment by johnniwinther** [comment]
There is hardly any checking of patching currently.
