### ISSUE TITLE
Service and profiler tests failing on dartk-linux-release-arm64 and app_jitk-linux-debug-x64

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#46746]
After 746b8f1f, there were a lot of service test failurs on a few number of bots. 9397b8ff fixes most of the tests, but there are still a handful remaining from runs after it landed:

On dartk-linux-release-arm64 and app_jitk-linux-debug-x64, the following tests are still failing:
```
     service_2/get_allocation_samples_test/service   (Pass -> RuntimeError, expected Pass) at 746b8f..babfe0
     service_2/get_allocation_samples_test/dds   (Pass -> RuntimeError, expected Pass) at 746b8f..babfe0
```

On dartk-linux-release-arm64, the following additional tests are still failing:
```
     service_2/rewind_optimized_out_test/service   (RuntimeError -> Timeout, expected Pass) at 94bdcc
     vm/cc/Profiler_BasicSourcePositionOptimized   (Pass -> Crash, expected Pass) at 746b8f..f424f3
     service_2/get_vm_timeline_rpc_test/service   (RuntimeError -> Timeout, expected Pass) at 94bdcc
     service_2/get_allocation_traces_test/service   (Pass -> RuntimeError, expected Pass) at 746b8f..f424f3
     vm/cc/Profiler_BinaryOperatorSourcePositionOptimized   (Pass -> Crash, expected Pass) at 746b8f..f424f3
     vm/cc/Profiler_SourcePositionOptimized   (Pass -> Crash, expected Pass) at 746b8f..f424f3
     service_2/get_allocation_traces_test/dds   (Pass -> RuntimeError, expected Pass) at 746b8f..f424f3
     vm/cc/Profiler_FunctionInline   (Pass -> Fail, expected Pass) at 746b8f..babfe0
     service_2/rewind_optimized_out_test/dds   (RuntimeError -> Timeout, expected Pass) at cb5d0b..41cf79
```

Given the number of remaining failing tests, I'm going to approve them for now.

cc @bkonyi

**Comment by sstrickl** [comment]
While the CL showed all the failures on dartk-linux-debug-ia32 and vm-kernel-optcounter-threshold-linux-release-ia32-try to be fixed (the latter having one test previously approved for a Timeout returning to that state), it also showed all the failures on app_jitk-linux-debug-x64 to be fixed as well but one showed up on the non-trybot, so I imagine there's at least one more similar heisenbug remaining.

**Comment by sstrickl** [comment]
Given that the fix I added was needed even before the original commit landed, I expect it may not be an issue with the commit itself, but just that it exposed already existing issues that were less likely to trigger before.

**Comment by bkonyi** [comment]
Unfortunately, I can't seem to reproduce these issues on my Linux box... :-( this is going to be a fun one...

Also @sstrickl, in the future could you please provide links to logs for a subset of the failures? The builder names and test configuration names don't match up 1:1, so it's a pain to go digging for them in the tree. Having even just one log per failure is a huge help!

**Comment by aam** [comment]
@bkonyi wrote
> Unfortunately, I can't seem to reproduce these issues on my Linux box... :-( this is going to be a fun one...

Should https://dart.googlesource.com/sdk/+/17961606060fa36971fdc40cee8105a13262e97e be reverted while you investigate the failures?

**Comment by bkonyi** [comment]
No, the failures are approved for now and I have a fix for the failures I could reproduce [here](https://dart-review.googlesource.com/c/sdk/+/208940). The failures are likely due to us running out of sample buffer space, so increasing the number of sample blocks should the failures.

**Comment by aam** [comment]
It looks like https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-nnbd-linux-debug-ia32/286, https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-linux-debug-ia32/7219, https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/cross-vm-linux-release-arm64 all seems to be affected by reland.

service/get_allocation_samples_test, service/get_allocation_traces_test, vm/cc/Profiler_BasicSourcePositionOptimized, vm/cc/Profiler_FunctionInline, vm/cc/Profiler_SourcePositionOptimized, vm/cc/Profiler_BinaryOperatorSourcePositionOptimized are the tests that stared to fail with reland on ia32, arm64 bots.

**Comment by aam** [comment]
> No, the failures are approved for now 

Main concern with this is that is by approving failures we are potentially disrupting/breaking things downstream from dart sdk(flutter, google).

**Comment by bkonyi** [comment]
I strongly believe that the fix in the CL linked above will resolve most, if not all of the issues. Given that this is next to impossible to reproduce locally on machines with various performance characteristics and we're not actually seeing crashes, just test failures, reverting the reland without landing the potential fix first would be counterproductive.

**Comment by bkonyi** [comment]
Going to take a different approach for the fix. Revert up [here](https://dart-review.googlesource.com/c/sdk/+/208960).
