### ISSUE TITLE
Failures on [vm/gardening] Cleanup file_fuzz_test and raw_datagram_read_all_test.

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46747]
There are new test failures on [[vm/gardening] Cleanup file_fuzz_test and raw_datagram_read_all_test.](https://github.com/dart-lang/sdk/commit/d8839511737dbd1775f37cb5a13862bd7d6f4b88).

The tests
```
standalone_2/io/file_fuzz_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-win-debug-x64
dartk-win-release-x64
```

@aam Could you please take a look?

**Comment by alexmarkov** [comment]
Also, `standalone_2/io/raw_datagram_read_all_test` starts timing out on Windows after d8839511737dbd1775f37cb5a13862bd7d6f4b88.

Logs:

https://dart-ci.appspot.com/log/vm-kernel-precomp-win-release-x64/dartkp-win-release-x64/12940/standalone_2/io/raw_datagram_read_all_test

https://dart-ci.appspot.com/log/vm-kernel-win-release-x64/dartk-win-release-x64/17723/standalone_2/io/raw_datagram_read_all_test

**Comment by aam** [comment]
thank you @alexmarkov for sorting out through the errors.
