### ISSUE TITLE
[ Breaking Change Request ] Drop reference to Observatory in VM service message

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#46756]
**Intended Behavior Change**

Update the VM service message to no longer reference Observatory as it will no longer be shipped with the SDK in a future release (2.17). Observatory users will instead be directed to use DevTools for debugging via an existing message and the Observatory string will be replaced by the a message similar to the following:

`A Dart VM service is listening on http://127.0.0.1:8181/abc123=/`

**Current Behavior**

Currently, invoking the VM with either `--observe` or `--enable-vm-service` outputs a message to `stdout` similar to `Observatory listening on http://127.0.0.1:8181/bKrWeCYueRo=/`. Various pieces of tooling and testing infrastructure scrape `stdout` for this message in order to determine the VM service URI (e.g., flutter_tools).

**Expected Impact**

Tooling which relies on the Observatory message being printed to `stdout` will fail to connect to running Dart applications. This will mostly only impact tooling and tests which are not already relying on the `--write-service-info=` flag to write the VM service connection information to disk.

**Mitigation**

Impacted tooling should be updated to support the new VM service message and also support the legacy Observatory message if the tool supports arbitrary Dart versions.

**Related issues**

- #38419

cc for review: @franklinyow @mit-mit @vsmenon @kevmoo @Hixie

FYI: @a-siva @jonahwilliams @devoncarew @jacob314

**Comment by jonahwilliams** [comment]
We can't use --write-service-info on iOS or Android, since we don't have access to the filesystem where those are written.

**Comment by Piero512** [comment]
DevTools is great for Flutter, but I was able to debug performance issues from a compute() isolate through the observatory, something that I wasn't able to do in DevTools , even though the observatory doesn't have all the bell and whistles of the Observatory.

**Comment by DanTup** [comment]
> will be replaced by the a message similar to the following

Is the _exact_ message (allowing for URL differences 😛) known? If not, can you ping here when it is?

The VS Code extension mostly doesn't use this now, but there's still a little code to handle it in some cases.

**Comment by a-siva** [comment]
> DevTools is great for Flutter, but I was able to debug performance issues from a compute() isolate through the observatory, something that I wasn't able to do in DevTools , even though the observatory doesn't have all the bell and whistles of the Observatory.

This breaking change will only change the string printed from the VM and will not drop observatory functionality

**Comment by a-siva** [comment]
> We can't use --write-service-info on iOS or Android, since we don't have access to the filesystem where those are written.

For these cases can the tooling be changed to parse the new string ?

**Comment by jonahwilliams** [comment]
Parsing the new string is fine. IIRC this is all configured in a single place, so we should be able to update the code to accept either and roll.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/protocol_discovery.dart#L37

**Comment by bkonyi** [comment]
@DanTup I'll be sure to update here with the CL before it lands so we'll have the exact wording tracked here.

@jonahwilliams thanks for pointing to where we'll need to make the change. I'll update the tool as part of a roll once the change lands.

@Piero512 thanks for the feedback! As @a-siva mentioned, Observatory isn't going away quite yet, but it's no longer under active development and is in maintenance mode. Would you mind filing an issue in the [DevTools repository](https://github.com/flutter/devtools/) explaining what you were trying to do and why you had to go to Observatory to figure out your performance issue? We want to make sure DevTools is as good (or better) than Observatory before we drop support, so user feedback is always greatly appreciated!

**Comment by aam** [comment]
@bkonyi wrote

> @jonahwilliams thanks for pointing to where we'll need to make the change. I'll update the tool as part of a roll once the change lands.

Perhaps it might be simpler to update tools to accommodate _both_ messages before the change in dart vm lands.

**Comment by jonahwilliams** [comment]
I would agree with that too :)

**Comment by natebosch** [comment]
This may impact UX for debugging with the test runner. It looks like we currently can create a deep link to the observatory UI for a specific isolate. https://github.com/dart-lang/test/blob/562c927ed8ede647cc44bc3f2daf3e480cca6673/pkgs/test_core/lib/src/runner/vm/platform.dart#L219-L221

cc @jacob314 - is there be a similar capability in devtools?

**Comment by kenzieschmoll** [comment]
What is the effect of the deep link? That a specific isolate ID is selected by Observatory? What do the tests that use the observatory deep link check in the Observatory UI?

**Comment by Hixie** [comment]
When landing this please make sure to shephard this all the way into google3 (reverting at each step until it can be landed cleanly), as I expect there will be a million places that depend on this exact string that will be hard to find.

**Comment by bkonyi** [comment]
I've started replacing references to Observatory in output strings and flags/options to instead reference the Dart VM Service (updated flags/options will still have aliases for their old observatory-related names to prevent breakages, but won't be listed going forward). 

The old Observatory message:

`Observatory listening on http://127.0.0.1:8181/abcdefg/`

Will tentatively be changed to:

`Dart VM Service listening on http://127.0.0.1:8181/abcdefg/`

**Comment by DanTup** [comment]
> Will tentatively be changed to:

From discussions today, my understanding is that this text is no long tentative and is being merged, so I'm going to update the places in VS Code (and the SDK DAP, if we're not just always using `--write-service-info` there) to handle both messages above.

If this is incorrect (or changes), please let me know!

**Comment by bkonyi** [comment]
@DanTup after discussing offline, we're going to go with this message instead:

```
The Dart VM Service is listening on http://...
```

**Comment by DanTup** [comment]
Got it, thanks!

**Comment by mit-mit** [comment]
I think "service" should be lower-case?

**Comment by bkonyi** [comment]
@mit-mit, discussed with @sfshaza2 and we're going to go with a lowercase 'service'.

FYI @DanTup

**Comment by DanTup** [comment]
Got it, thanks!

**Comment by bkonyi** [comment]
@jwren is there anything that needs to be changed in the Intellij plugin for this?

**Comment by jwren** [comment]
Yes, it shouldn't be much, captured here: https://youtrack.jetbrains.com/issue/WEB-54727.  I'll make sure it happens soon.  Which version of the SDK will this change be made?  In the Dart Plugin we'll have it conditional on the Dart SDK version.

**Comment by jwren** [comment]
Change out for review for the Dart Plugin for IntelliJ - https://github.com/JetBrains/intellij-plugins/pull/855.  As soon as the change lands I'll do some manual testing to ensure that it works as expected.

It looks like the Flutter Plugin for IJ doesn't have any references to `"Observatory listening ` so we shouldn't need any changes there.

**Comment by bkonyi** [comment]
Now that we've published new versions of the Dart Intellij plugin, the VM service message change has relanded in https://github.com/dart-lang/sdk/commit/b03605207764a591d2174a910836e58c731aeb82. Assuming it sticks, this change will be visible starting in the **2.17 stable release**.

**Comment by angelicasmailer** [comment]
```
Launching lib\main.dart on V2239 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
I/flutter (20609): The Dart VM service is listening on ************************************
```

Stuck at this Tried, Vivo, Realme, Oppo, Redmi. Motorola

Please help guys. 

Create new flutter project in vscode to reproduce the problem

All the devices were on Android 13 August 2023 Patch.

```

Flutter SDK3.13.3
Dart SDK3.1.1 (Flutter)
VSCode 1.82
```
