### ISSUE TITLE
[infra] dart HHH and HHH-web bots run the same tool tests

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#46768]
I was looking into recent flakes in dart HHH and HHH-web bots (https://ci.chromium.org/p/dart/g/flutter-hhh/console), and I noticed that they run `tool_tests` and `web_tool_tests` respectively which became the same after https://github.com/flutter/flutter/pull/78636. 

Seems like flutter (https://ci.chromium.org/p/flutter/g/framework/console) has bots for every subshard in that directory, so they are run only once. 

Is it possible to run all the non-web tool subshards  on the HHH bot, and web.shard subshard on the HHH-web bot, to reduce flakes and keep web tool tests separate from VM ones? Will it lose any coverage? 

Here is where flutter configures the tool_tests and web_tool_tests to run on separate bots (links by @jmagman):

- there's a tool_tests shard, and a general and commands subshard https://flutter.googlesource.com/infra/+/refs/heads/main/config/framework_config.star#246
- there's a web_tool_tests shard and a web subshard https://flutter.googlesource.com/infra/+/refs/heads/main/config/framework_config.star#284
(trying to find the recipe code, one sec)
- and they are set as environment variables: https://flutter.googlesource.com/recipes/+/241b9194bb6285464695c61ab59a889552716901/recipes/flutter/flutter_drone.py#73

**Comment by annagrin** [comment]
@athomas @whesse is it possible to configure HHH bots similarly to flutter bots?
/cc @jmagman

**Comment by annagrin** [comment]
Thanks @jmagman I was not sure where is the best place to fix this - flutter bots or HHH configuration.  I am happy with either:)

**Comment by jmagman** [comment]
We can fix this on the flutter test harness side: https://github.com/flutter/flutter/pull/87385

**Comment by 1972chris** [comment]
Thanks

**Comment by 1972chris** [comment]
[[]()]()

**Comment by a-siva** [comment]
Closing this issue as it is being tracked in https://github.com/flutter/flutter/pull/87385

**Comment by jmagman** [comment]
I believe https://github.com/flutter/flutter/pull/87385 worked.

[flutter-engine-linux #13692](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840191416309183504/+/u/flutter_test_tool_tests/stdout) shows:
```
SHARD=tool_tests
SUBSHARD=general
...
SUBSHARD=commands
```
but not `web` subshard.

[flutter-engine-linux-web_tests #3084](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840191416001261584/+/u/flutter_test_web_tool_tests/stdout) is running `test/web.shard`
```
RUNNING: cd packages/flutter_tools; ../../bin/cache/dart-sdk/bin/pub run test --test-randomize-ordering-seed=20210731 -rcompact -j1 --no-color --timeout=180000ms test/web.shard
```
but not `general` or `commands` subshards.
