### ISSUE TITLE
cannot use external in ffi

### ISSUE THREAD

**Issue by lucian-ma** [dart-lang/sdk#46762]
![image](https://user-images.githubusercontent.com/20057999/127613529-eda580f2-ed37-4227-ab68-fb3c80df4266.png)

**Comment by lrhn** [comment]
Which version of Dart are you depending on? In your `pubspec.yaml`, what is your `environment`/`sdk` version constraint?

You need to require at least Dart 2.12.0 (aka. null safety) in order to enable external variable declarations. They were added to the language in that language version.
