### ISSUE TITLE
[vm/ffi] Flaky crashes on QEMU bot

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#46775]
```
INFO: Core dump archiving is activated
Test configuration:
    dartkp-linux-release-arm-qemu(architecture: arm, compiler: dartkp, mode: release, runtime: dart_precompiled, system: linux, use-qemu)
Suites tested: ffi_2
Total: 289 tests
 * 0 tests will be skipped (0 skipped by design)
 * 0 tests are expected to be flaky but not crash
 * 0 tests are expected to flaky crash
 * 288 tests are expected to pass
 * 0 tests are expected to fail that we won't fix
 * 0 tests are expected to fail that we should fix
 * 0 tests are expected to crash that we should fix
 * 0 tests are allowed to timeout
 * 1 could not be categorized or are in multiple categories

Unexpected exit code 127
DART_CONFIGURATION=ReleaseXARM qemu-arm -L /usr/arm-linux-gnueabihf/ out/ReleaseXARM/dart_precompiled_runtime --use-slow-path --stacktrace-every=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_function_test.dart_3/out.aotsnapshot

**
ERROR:/build/qemu-z6QTYR/qemu-2.11+dfsg/qom/object.c:1645:object_get_canonical_path_component: code should not be reached

INFO: No unexpected crashes recorded
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840284732626898736/+/u/ffi_tests/stdout

Filing a new issue because the error message is different than the previous QEMU issue https://github.com/dart-lang/sdk/issues/41534.

`object_get_canonical_path_component: code should not be reached`

A quick search reveals https://bugs.launchpad.net/qemu/+bug/1756519 and https://patchwork.kernel.org/project/qemu-devel/patch/20180402171354.27706-4-jcmvbkbc@gmail.com/ which are QEMU 2.11 and 2018.

We're also running 2.11 on the bots.

@athomas can we update QEMU to a newer version? 2.12.1 For example? Or all the way to 6.0.0 if that doesn't break our use of the public API?

**Comment by athomas** [comment]
The bots use qemu 2.11 because that's what bionic provides:
https://packages.ubuntu.com/bionic/qemu-user

We'd have to install qemu in some other way to get something newer than 2.11.

**Comment by alexmarkov** [comment]
Still happens:

```
Unexpected exit code 127
DART_CONFIGURATION=ReleaseXARM qemu-arm -L /usr/arm-linux-gnueabihf/ out/ReleaseXARM/dart_precompiled_runtime --use-slow-path --stacktrace-every=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_function_very_many_test.dart_3/out.aotsnapshot

**
ERROR:/build/qemu-KZtMUi/qemu-2.11+dfsg/qom/object.c:1645:object_get_canonical_path_component: code should not be reached
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8827099373283668625/+/u/ffi_tests/stdout

**Comment by dcharkes** [comment]
The commit where it turned purple seems to have to do nothing with QEMU or FFI, it's an analyzer commit: bd660d98472f01c57ece4dcf2a7a8810ea4e402d.

@athomas did we change anything in the bot configuration 7 days ago?

Last green run: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-precomp-ffi-qemu-linux-release-arm/6565/overview
First purple run: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-precomp-ffi-qemu-linux-release-arm/6566/overview

**Comment by athomas** [comment]
The plan to address this is to switch the builder to a focal image in Q3 after Flutter infra has made that available to us.

**Comment by rmacnak-google** [comment]
The first several builds after the update are green!
