### ISSUE TITLE
compile result is different between dart2js and dart2native

### ISSUE THREAD

**Issue by a-skua** [dart-lang/sdk#46770]
## my environments
```shell
# dart --version
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"

# dart2js --version
Dart-to-JavaScript compiler (dart2js) version: 2.13.4

# uname -mps
Darwin arm64 arm # macOS Big Sur Version 11.3.1, Apple M1
```

## problematic codes
exec code
https://github.com/a-skua/tiamat/blob/46d30fb2f63b88df32af637df4033899c1186426/example/main.dart

debug code
https://github.com/a-skua/tiamat/blob/46d30fb2f63b88df32af637df4033899c1186426/lib/src/casl2/operand_parser/output.dart#L44-L50

## what's happen
`dart run main.dart` and `dart compile exe main.dart && main.exe` are ok.
```
...
--- START DEBUG ---
label is OUT
has label: true
address is null
has address: false
symbols: [ PUSH 0,GR1: [],  PUSH 0,GR2: [],  LAD GR1,OUT: [],  LAD GR2,38: [],  SVC 2: [],  POP GR2: [],  POP GR1: []]
--- END   DEBUG ---
...
```

but, `dart compile js main.dart && open index.html` is not ok.
```
...
--- START DEBUG ---
label is OUT
has label: false
address is null
has address: false
symbols: [ PUSH 0,GR1: [],  PUSH 0,GR2: [],  LAD GR2,38: [],  SVC 2: [],  POP GR2: [],  POP GR1: []]
--- END   DEBUG ---
...
```
I expected `has label: true`, but it was `has label: false`

I tried `dart2js -O0 main.dart`, it was as expected `has label: true`!
but, `dart2js -O1 main.dart` was not as expected: `has label: false`.

I only know this far, so if you know anything, I would like a hint.

**Comment by bkonyi** [comment]
FYI @sigmundch

**Comment by sigmundch** [comment]
cc @rakudrama

**Comment by rakudrama** [comment]
This appears to be a bug in global type inference.

Global type inference thinks that `ExResult.label` is always `null` in `automata/pattern4.dart`.
The `label` argument to the generative constructor factory has inferred type `[null]`. The value comes from the local `label` in the method `automata`.

Local `label` is assigned in an if-then block in a switch.
```
String label? = null;
...
switch (...) {
  ...
  case ?:
    if (?) {
      label = ... 
      break; // [1]
    }
    ...
    break;
```

Removing the break at `// [1]` causes inference to be correct.
This looks like it might be a bug in the phi node construction inside switch statements.
It should be possible to come up with a simper example.

**Comment by sigmundch** [comment]
We came across another instance of this bug. Here is a similar repro:

```dart
class A {
  final int value;
  const A(this.value);

  static const A one = const A(1);
}

bool bTrue = confuse(true);
bool bFalse = confuse(false);
A value = confuse(A.one);

@pragma('dart2js:noInline')
confuse(x) => x;

main() {
  L? sourceInfo;
  switch (value) {
    case A.one:
      if (bTrue) {
        sourceInfo = L1();
        break;
      }
      sourceInfo = L2();
      break;
    default:
      return null;
  }

  sourceInfo.m1();
  return sourceInfo;
}

abstract class L {
  void m1();
}

class L1 implements L {
  @pragma('dart2js:noInline')
  void m1() => print("L1");
}

class L2 implements L {
  @pragma('dart2js:noInline')
  void m1() => print("L2");
}
```

Here `L1.m1` is accidentally tree-shaken.
