### ISSUE TITLE
FFI not working on Windows

### ISSUE THREAD

**Issue by jaddison06** [dart-lang/sdk#46772]
I'm using a very simple program to brush up on my knowledge of Dart FFI. NumberStorage is a simple class which interacts with a C struct containing two integers.

```dart
final ns = NumberStorage(123, 456);
print(ns.GetA()); // should print 123
print(ns.GetB()); // should print 456 
ns.FreeNumberStorage();
```

I've tested my code on Linux, and it works perfectly. However, on Windows, the code just hangs as soon as I try and call any C function, and dart.exe starts using loads of CPU. Nothing gets printed to the console.

I'm on Windows 11, but I've tested on Windows 10 and the same weird behaviour occurs.

`dart --version` is 2.13.4 (stable) on all operating systems.

**Comment by dcharkes** [comment]
@jaddison06 what is the definition of NumberStorage?

**Comment by jaddison06** [comment]
I'm creating this using some custom codegen, so sorry that it's so ugly!

```dart
class NumberStorage {
    Pointer<Void> structPointer = Pointer.fromAddress(0);

    void _validatePointer(String methodName) {
        if (structPointer.address == 0) {
            throw Exception('NumberStorage.$methodName was called, but structPointer is a nullptr.');
        }
    }

    late _libTest_class_NumberStorage_method_InitNumberStorage_sig _InitNumberStorage;
    late _libTest_class_NumberStorage_method_FreeNumberStorage_sig _FreeNumberStorage;
    late _libTest_class_NumberStorage_method_GetA_sig _GetA;
    late _libTest_class_NumberStorage_method_GetB_sig _GetB;

    NumberStorage(int a, int b) {
        final lib = DynamicLibrary.open('build\\native\\libTest.dll');

        // INITIALIZER
        _InitNumberStorage = lib.lookupFunction<_libTest_class_NumberStorage_method_InitNumberStorage_native_sig, _libTest_class_NumberStorage_method_InitNumberStorage_sig>('InitNumberStorage');

        _FreeNumberStorage = lib.lookupFunction<_libTest_class_NumberStorage_method_FreeNumberStorage_native_sig, _libTest_class_NumberStorage_method_FreeNumberStorage_sig>('FreeNumberStorage');
        _GetA = lib.lookupFunction<_libTest_class_NumberStorage_method_GetA_native_sig, _libTest_class_NumberStorage_method_GetA_sig>('GetA');
        _GetB = lib.lookupFunction<_libTest_class_NumberStorage_method_GetB_native_sig, _libTest_class_NumberStorage_method_GetB_sig>('GetB');

        structPointer = _InitNumberStorage(a, b);
    }

    void FreeNumberStorage() {
        _validatePointer('FreeNumberStorage');
        return _FreeNumberStorage(structPointer);
    }

    int GetA() {
        _validatePointer('GetA');
        return _GetA(structPointer);
    }

    int GetB() {
        _validatePointer('GetB');
        return _GetB(structPointer);
    }
}
```

**Comment by dcharkes** [comment]
And the definitions of InitNumberStorage, FreeNumberStorage, GetA and GetB?

P.S. You might want to use static late variables for your `_InitNumberStorage` etc so that you reuse them among instances.

P.S. 2 If you just write a C header file package:ffigen can generate the bindings for you. But if you're already writing a generator that maybe doesn't help you :)

**Comment by dcharkes** [comment]
Can you provide a full minimal reproduction? With these partial snippets of code I cannot reproduce it. There could be something wrong with your bindings for example in `_libTest_class_NumberStorage_method_InitNumberStorage_sig`. (e.g. the sizes of ints in the struct and function arguments.) Or, there could be something wrong with the windows built dll.

If you want to debug it yourself, you can try running the Dart executable in visual studio with the dart file as argument, then it will open the debugger on a crash or you can break in the debugger if it ends up in an endless loop.

**Comment by jaddison06** [comment]
Hi, sorry for the late reply - I've been away. I tried following the official hello world, and that didn't work either, so it seems like there was a problem with my setup. I was using gcc-10.2.0 from Cygwin, but I've now switched to WSL and it's working perfectly.
