### ISSUE TITLE
Error flutter outline

### ISSUE THREAD

**Issue by panha-liger** [dart-lang/sdk#46777]
## Version information

- `IDEA AI-201.8743.12.41.7199119`
- `2.12.3`
- `AI-201.8743.12.41.7199119, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x960`
I don't know where is my outline?

**Comment by lrhn** [comment]
Can you explain in more detail what your problem is?

**Comment by a-siva** [comment]
No replies so far, will close the issue as cannot reproduce due to insufficient information.
Please feel free to reopen it if a reproduction with  more information is available.
