### ISSUE TITLE
[Request] Add quick fix to return_of_invalid_type

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#46785]
It is frustrating to me when I get to the end of a method and I want a different type, it gives the error without a quick fix. I need to scroll up and manually change the return type (which sometimes I don't know/already forgot/it is something different).
I wish there were a quick fix for it.

![image](https://user-images.githubusercontent.com/351125/127810041-85e35b9e-53e6-455c-b5a8-b1c392f544d8.png)

**Comment by srawlins** [comment]
This is a good idea. I agree that the solution I often want in this case is to change the function signature.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/209962

**Comment by asashour** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/f4b6fa85eae9ffde044fe479999974585ca000da, please close.
