### ISSUE TITLE
Failures on Limit simultaneous connections on http client in AssetFileSystem

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#46786]
There are new test failures on [Limit simultaneous connections on http client in AssetFileSystem](https://github.com/dart-lang/sdk/commit/d135395e219d5044ba8600e04a667d669b2f5556).

The tests
```
pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64
```

**Comment by liamappelbe** [comment]
cc @annagrin

**Comment by annagrin** [comment]
@liamappelbe  could you please share a link to the failures?

**Comment by liamappelbe** [comment]
Oops. I was using the an automatic bug filing thing. We should update it to automatically include a link to the failures.

Anyway, here you go: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-mac-release-arm64/355/overview

My guess is that the test is doing something weird and needs to be updated.

**Comment by annagrin** [comment]
Thanks you! Found the bug, working on the fix.
