### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Ameenahssan102** [dart-lang/sdk#46780]
## Version information

- `IDEA AI-201.8743.12.41.7199119`
- `2.13.4`
- `AI-201.8743.12.41.7199119, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

**Comment by a-siva** [comment]
Can you elaborate a bit more on what problem you ran into ? The details above do not seem to have any error stacktrace.

**Comment by a-siva** [comment]
No replies so far, will close the issue as cannot reproduce due to insufficient information.
Please feel free to reopen it if a reproduction with  more information is available.
