### ISSUE TITLE
analysis server: "add type annotation" grabs src reference instead of public reference

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#46795]
## Note
This was originally filed against Dart Code but was declared to be a bug in the Dart analysis server: https://github.com/Dart-Code/Dart-Code/issues/3513

## Description

I was getting an `always_specify_types` linter error in the following code:

```dart
import 'package:analyzer/dart/ast/ast.dart' as dart_ast;
...
    final dart_ast.TypeName typeName = parameter.childEntities.firstWhere(
        (e) =>  // <-- Here is the always_specify_types error
            e is dart_ast.TypeName) as dart_ast.TypeName;
```

I hit the "add type annotation" "quick fix" and it imported `import 'package:_fe_analyzer_shared/src/base/syntactic_entity.dart';`  which is a linter error since it is in src.  I expected it to grab `import 'package:analyzer/dart/ast/syntactic_entity.dart';` since that import wouldn't create another linter error.

Here is the source code for `package:analyzer/dart/ast/syntactic_entity.dart`:
```dart
export 'package:_fe_analyzer_shared/src/base/syntactic_entity.dart'
    show SyntacticEntity;
```

**Comment by scheglov** [comment]
This was fixed in e0752585f275ae90f45ea0475e10559ac873e116.
We don't suggest non-API libraries from other packages anymore.
So, if there is a public library, Quick Fix will suggest it.
