### ISSUE TITLE
fuzzer: crash in generated code on simarm64c

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#46797]
```
DART SDK REVISION: Dart SDK version: 2.14.0-edge.9ec112a509d98dd63ea38ca5a004489a5f8ff65c (be) (Tue Aug 3 03:06:41 2021 +0000) on "linux_x64"

dart runtime/tools/dartfuzz/dartfuzz.dart --no-fp --no-ffi --flat --seed 460149359 fuzz.dart

out/ReleaseSIMARM64C/dart --optimization_counter_threshold=1 --deterministic --old_gen_heap_size=128 fuzz.dart

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0xffffffffffffff40
version=2.14.0-edge.9ec112a509d98dd63ea38ca5a004489a5f8ff65c (be) (Tue Aug 3 03:06:41 2021 +0000) on "linux_simarm64"
pid=752, thread=841, isolate_group=main(0x562f4b465c00), isolate=main(0x562f4b437000)
isolate_instructions=562f49c1f7a0, vm_instructions=562f49c1f7a0
Stack dump aborted because GetAndValidateThreadStackBounds failed.

```

**Comment by wustrong** [comment]
> ```
> DART SDK REVISION: Dart SDK version: 2.14.0-edge.9ec112a509d98dd63ea38ca5a004489a5f8ff65c (be) (Tue Aug 3 03:06:41 2021 +0000) on "linux_x64"
> 
> dart runtime/tools/dartfuzz/dartfuzz.dart --no-fp --no-ffi --flat --seed 460149359 fuzz.dart
> 
> out/ReleaseSIMARM64C/dart --optimization_counter_threshold=1 --deterministic --old_gen_heap_size=128 fuzz.dart
> 
> ===== CRASH =====
> si_signo=Segmentation fault(11), si_code=1, si_addr=0xffffffffffffff40
> version=2.14.0-edge.9ec112a509d98dd63ea38ca5a004489a5f8ff65c (be) (Tue Aug 3 03:06:41 2021 +0000) on "linux_simarm64"
> pid=752, thread=841, isolate_group=main(0x562f4b465c00), isolate=main(0x562f4b437000)
> isolate_instructions=562f49c1f7a0, vm_instructions=562f49c1f7a0
> Stack dump aborted because GetAndValidateThreadStackBounds failed.
> ```

do you fix this?
