### ISSUE TITLE
Missing legacy marker on inferred type argument of generic constructor through typedefs that are not just renames

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#46808]
There are a lot of features at play here (I might not have the description perfect) but this example comes directly from 
https://github.com/dart-lang/sdk/blob/7f5d1cc30d96e3d9773f619986c06d55ed9b7a49/tests/language/typedef/aliased_constructor_tear_off_test.dart#L186-L189

After removing the rest of the test we have:

```dart
Object? context<T>(T x) => x;

class C<T> {
  final T x;
  C(this.x);
  C.named(this.x);
}

typedef Bounded<T extends num> = C<T>; // Not proper rename.

void main() {
  if (!identical(context<C<int> Function(int)>(Bounded.new), C<int>.new)) {
    throw 'failure!';
  }
}
```

When running in weak null safety mode the `int` type in the constant value for `context<C<int> Function(int)>(Bounded.new)` is missing the legacy that appears in the constant version of `C<int>.new`.

Looking at the kernel text dump you can see the two constants are different only in the legacy marker:
```
constants  {
  ...
  #C2 = instantiation tes::C::_#new#tearOff <core::int>
  #C3 = instantiation tes::C::_#new#tearOff <core::int*>
}
```

cc @johnniwinther @eernstg

**Comment by nshahan** [comment]
The same issue appears on the uses of some of the other typedefs in the test file:

```dart
typedef Wrapping<T> = C<C<T>>; // Not proper rename.
typedef Extra<T, S> = C<T>; // Not proper rename.

class D<S, T> {
  D();
  D.named();
}

typedef Swapped<T, S> = D<S, T>; // Not a proper rename.
```

The issue appears on both the named and unnamed constructors.

**Comment by eernstg** [comment]
The funny thing is that it looks a little bit lossy when a non-trivial number of expressions turn out to contain legacy markers on type arguments because they are constant expressions (though not necessarily in a constant context) and we're running a mixed version program. But I agree that it's the right thing to do.
