### ISSUE TITLE
dart2js: elide initialization checks of late fields in -O3+

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#46806]
Our plan to reduce the cost of initialization checks is to do a few things:

* completely elide the cost of the initialization checks whenever we compile with `-O3` (possibly bundled with `--omit-implicit-checks` or with a separate flag).
* add optimizations so we don't need to do so by default
  * https://github.com/dart-lang/sdk/issues/43361
  * https://github.com/dart-lang/sdk/issues/45682
* support for fine-tuning which checks are elided based on scoped annotations. Then the checks can only be elided with `-O4`, but frameworks can generate code that elides the checks in specific locations (e.g. generated templates where the Angular compiler can ensure the checks are not needed).

This issue tracks the first step

**Comment by rakudrama** [comment]
Update:

https://github.com/dart-lang/sdk/commit/6384eceedc3a947f8dfc44681fd0fe84b1930f1f Removes some checks when the same late field is used several times in one method. This is about 25% of the checks in large Dart Angular apps.

https://github.com/dart-lang/sdk/commit/6384eceedc3a947f8dfc44681fd0fe84b1930f1f Makes some of the checks slightly smaller.

**Comment by sigmundch** [comment]
agree finishing this work is still a P1. Main remaining work here is in plumbing to use annotations to elide checks in lowering in certain scenarios (like code emitted by certain code generators)

**Comment by sigmundch** [comment]
Updates: changes landed to make annotations querying ondemand and more hierarchical. This is needed so that annotations can be derived more easily (a) based on the context of the library or (b) based on the provenance of the generated code (important in the case of getters/setters derived from a late variable declaration).

ETA now is a few days to land the last changes before the annotation can be tested by frameworks.

**Comment by rakudrama** [comment]
Closing since late instance field checks can be elided via an annotation.
