### ISSUE TITLE
dart migrate  error

### ISSUE THREAD

**Issue by jinliyuelong** [dart-lang/sdk#46804]
My flutter and darr versions are as follows
----------------------------------------------------------------
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (5 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
------------------------------------------------------------------------------------------------
But when run dart migrate，the  errors as follows  occur!

--------------------------------
dart migrate  
Migrating /Users/liyanjun43/work/02jingyitruck/02code/02flutter/mrd_flutter_framworks

See https://dart.dev/go/null-safety-migration for a migration guide.

Note: more than one project found; migrating the top-level project.

Analyzing project...
[----------------------------------------------------------------------------------------------|]
331 analysis issues found:
  error • The parameter 'key' can't have a value of 'null' beca
  ……
The migration tool didn't start, due to analysis errors.

The following steps might fix your problem:
1. Run `dart pub get`.
2. Try running `dart migrate` again.

**Comment by jinliyuelong** [comment]
My previous flutter version was 1.22.5

**Comment by jinliyuelong** [comment]
how can i solve it?

**Comment by srawlins** [comment]
Sorry for the delay. Is there any more text in the crash, or is the word `beca` actually cut off?
