### ISSUE TITLE
Promote value that is switched on to non-null in cases

### ISSUE THREAD

**Issue by spkersten** [dart-lang/sdk#46805]
In a case of a switch statement, the type of a value that is switched on can be promoted to be nonnullable. For example:
```dart
void foo(Foo? value) {
  switch (value) {
    case Foo.a:
      bar(value); // The argument type 'Foo?' can't be assigned to the parameter type 'Foo'.
      break;
    case Foo.b:
      bar(value); // The argument type 'Foo?' can't be assigned to the parameter type 'Foo'.
      break;
    case null:
      break;
  }
}

void bar(Foo value) {}

enum Foo {
  a,
  b,
}
```
this currently (Dart 2.13) gives two errors as indicated with comments, while `value` is guaranteed to be not null at that point.

edit: Maybe it's not so simple when considering fall-through (possible from `case null:`.

**Comment by vsmenon** [comment]
Merging into https://github.com/dart-lang/language/issues/1726
