### ISSUE TITLE
General Guidance - extending the dart language for flutter development

### ISSUE THREAD

**Issue by johnmcconnell** [dart-lang/sdk#46819]
This tracker is for issues related to:

* Common Front End (CFE) and kernel

Some other pieces of the Dart ecosystem are maintained elsewhere. Please
file issues in their repository:

* Dart language: https://github.com/dart-lang/language

I'm looking for general guidance on extending the dart language for flutter development.

For example, let's suppose I want to extend the language to support a new keyword `dataclass` (which automatically calculates the toString, hashCode, etc... methods given the class's fields. Conceptually, the similar to kotlin's `data class`: https://kotlinlang.org/docs/data-classes.html).

I understand I can build the local flutter engine using:
- `/flutter/tools/gn` and  `ninja -C <target>`

And I can point flutter's frontend compiler to my locally patched sdk using:
- `dart bin/starter.dart --sdk-root='../../out/<target>/flutter_patched_sdk' --target=<platform> <compilation_target.dart>`

Can you point me in the right direction where in https://github.com/dart-lang/sdk/tree/master/pkg/front_end/lib/src/fasta , I would need to make changes in order to accomplish the goal above (assuming fasta in the right target) ?

I understand it depends, but I'm looking for "in general" or if you have a link to a guide/documentation.

**Comment by vsmenon** [comment]
A couple things:
- If you're interested in doing something like this right now, I'd look at https://pub.dev/packages/built_value or similar packages that use code generation.  
- Longer term, https://github.com/dart-lang/language/blob/master/working/macros/motivation.md is our emerging plan to make the language more easily extensible (and you can see data classes as an example there).

**Comment by vsmenon** [comment]
Closing here as there is no bug / feature request.  The below is a better place for interactive discussions:

https://dart.dev/community#join-the-conversation

**Comment by johnmcconnell** [comment]
I'm specifically looking for guidance in extending the language in way (that I'm fairly certain) is not on the roadmap. Any links/docs in that respect?

I'll check out the community chat for further inquiries, thank you
