### ISSUE TITLE
Unbounded type variable in typedef defaults to `dynamic` but expected `Object?`

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#46811]
I'm seeking clarification if this is a bug in one of the specs, the test, or the implementation. The example comes from:
https://github.com/dart-lang/sdk/blob/7f5d1cc30d96e3d9773f619986c06d55ed9b7a49/tests/language/typedef/aliased_type_literal_instantiation_test.dart#L45

The type variable in the typedef defaults to `dynamic` so we observe that `C<dynamic>` is not identical to `C<Object?>`.

```dart
class C<T> {
  final T x;
  C(this.x);
  C.named(this.x);
}

typedef Direct<T> = C<T>;

void main() {
  const Type co = C<Object?>;
  const Type d1 = Direct;

  if (!identical(d1, co)) throw 'failure!';
}
```

cc @johnniwinther @eernstg

**Comment by johnniwinther** [comment]
cc @stefantsov

**Comment by eernstg** [comment]
This is working as intended: `Direct` is used as a type literal, the missing type argument is computed by instantiation to bound, and [the result is](https://github.com/dart-lang/language/blob/450634924aba1cc2d61e2d3e4051f9a99deb8f2b/specification/dartLangSpec.tex#L7527) `Direct<dynamic>`.

I created https://dart-review.googlesource.com/c/sdk/+/209081 where the corresponding adjustments have been made.

**Comment by eernstg** [comment]
Landed.

**Comment by nshahan** [comment]
Thanks for the quick fix!
