### ISSUE TITLE
http.get throwing unexpected ArgumentError: Invalid internet address

### ISSUE THREAD

**Issue by danielnovograd** [dart-lang/sdk#46821]
* Dart SDK Version: 2.14.0-301.2.beta (beta)
* Mac OSX
* Running Flutter app on an iOS device

If I try to follow the Flutter docs example to make an HTTP request:

```dart
import 'package:http/http.dart' as http;

void main() {
  final uri = Uri.parse("https://google.com");
  http.get(uri);
}
```

`http.get` is throwing an exception `Invalid argument(s): ArgumentError: Invalid internet address google.com` with call stack:

```
new _InternetAddress.fromString (dart:io-patch/socket_patch.dart:238)
new InternetAddress (dart:io-patch/socket_patch.dart:72)
_isLoopback (dart:ui/hooks.dart:237)
_getHttpConnectionHookClosure.<anonymous closure> (dart:ui/hooks.dart:250)
_HttpClient._openUrl (dart:_http/http_impl.dart:2669)
_HttpClient.openUrl (dart:_http/http_impl.dart:2568)
IOClient.send (/home/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.3/lib/src/io_client.dart:30)
BaseClient._sendUnstreamed (/home/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.3/lib/src/base_client.dart:93)
BaseClient.get (/home/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.3/lib/src/base_client.dart:27)
get.<anonymous closure> (/home/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.3/lib/http.dart:46)
_withClient (/home/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.3/lib/http.dart:164)
get (/home/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.3/lib/http.dart:46)
HttpService.fetch (/home/dev/project/mobile/lib/services/http_service/http_service.dart:15)
ArticleRepository.getArticleFromText (/home/dev/project/mobile/lib/repositories/articles/article_repository.dart:15)
ScanBloc._processImage (/home/dev/project/mobile/lib/screens/scan/bloc/scan_bloc.dart:83)
<asynchronous gap> (Unknown Source:0)
```

I would expect this to not throw an exception

**Comment by DeD1rk** [comment]
See also https://github.com/flutter/flutter/issues/83792.

**Comment by bleroux** [comment]
How do you launch your application ? (Debug mode or not, which IDE, ...) ?

**Comment by DeD1rk** [comment]
I myself tested only on an iOS 15 beta simulator, in debug mode (it's only visible in debug since it's caught), from vscode, but I'm not sure about the others.

**Comment by bleroux** [comment]
Do you have 'All Exceptions' is checked in the 'Breakpoints' panel ?
![Capture d’écran du 2021-09-11 21-14-51](https://user-images.githubusercontent.com/840911/132959025-67938247-8b3c-404e-802e-5bc30daf2897.png)

If yes this is expected : this tells the debugger to halt on any Exception. 
For this particular code the exception is expected and catched : https://github.com/flutter/engine/blob/master/lib/ui/hooks.dart#L240

**Comment by DeD1rk** [comment]
> Do you have 'All Exceptions' is checked in the 'Breakpoints' panel ?

yes

>If yes this is expected : this tells the debugger to halt on any Exception.
For this particular code the exception is expected and catched : https://github.com/flutter/engine/blob/master/lib/ui/hooks.dart#L240

I know. However, I think it's undesirable to have exceptions (or especially, errors) thrown when nothing special is going on from the framework intentionally as it pollutes the debugging information for users of the framework. The fact that it's an Argument_Error_ makes it worse, as 'error's are meant to indicate programmer mistakes, as opposed to just exceptional occurrences.

**Comment by natebosch** [comment]
cc @a-siva from what I gather on this and flutter/flutter#83792 it seems we may have an exception being thrown and caught for a non-exceptional situation.

**Comment by bleroux** [comment]
@natebosch  I submitted a PR for this : https://github.com/flutter/engine/pull/28576
I will soon add a test to it

**Comment by natebosch** [comment]
Ah, thanks @bleroux!

This was an issue in flutter and not in the Dart SDK at all.

Closing as fixed by https://github.com/flutter/engine/pull/28576
