### ISSUE TITLE
co19/LibTest/core/Symbol/Symbol_A06_t01 test fails on dartdevk

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#46830]
The test below works on all platforms, including dart2js, but fails on 

```dart
import "../../../Utils/expect.dart";

class C {
  bool called = false;

  @override
  noSuchMethod(Invocation invocation) {
    called = true;
    Expect.equals(invocation.memberName, new Symbol("foo"));
    Expect.isFalse(identical(invocation.memberName, const Symbol("foo"))); // Fails here, isFalse argument is true
  }
}

main() {
  dynamic c = new C();
  c.foo();
  Expect.isTrue(c.called);
  c.called = false;

  c.foo;
  Expect.isTrue(c.called);
  c.called = false;
}
```
Tested on the edge version of DSK

**Comment by eernstg** [comment]
I think we'd need to change the test in this case: We generally don't want to prevent optimizations where certain objects provided by the runtime are canonicalized, even in the case where we do not _require_ this canonicalization.

An instance creation using `new` (explicitly or implicitly) that invokes a generative constructor _must_ yield an object that isn't `identical` to any existing object, but objects provided by the runtime (that is "built-in objects" like reified types and function tearoffs) are not guaranteed to have been created by `new`, so it's OK to canonicalize them, even at run time, if that's helpful.

Consequently, we should test for `identical(v1, v2)` whenever that is specified, but we should not jump to the conclusion that we must have `!identical(v1, v2)` for all other cases. In particular, we shouldn't have `Expect.isFalse(identical(...))`.

The 'Symbols' section in the language specification is currently being updated (https://github.com/dart-lang/language/pull/1782) such that it includes equality and identity of symbols obtained from invocations of the `Symbol(_)` constructor.

**Comment by eernstg** [comment]
Closing, I believe there is no need to change any tools, and the change to the test is handled in https://github.com/dart-lang/co19/issues/1128.
