### ISSUE TITLE
No tests for CompileTimeErrorCode.UNCHECKED_USE_OF_NULLABLE_VALUE

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#46839]
The error code `CompileTimeErrorCode.UNCHECKED_USE_OF_NULLABLE_VALUE` has no analyzer tests associated with it. If it can't be produced in practice then we should remove it; if it is produced then we should have some tests.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/209500

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/210220
