### ISSUE TITLE
[analyzer] Implement function tearoff equality corner cases

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46840]
This is the analyzer specific version of https://github.com/dart-lang/sdk/issues/46834, which has the details. It seems likely that there is no work to do here, because the analyzer configurations are passing the tests.

**Comment by jcollins-g** [comment]
P3 only based on this being a theoretical problem and our tests passing; we should still confirm this is OK.

**Comment by devoncarew** [comment]
@eernstg - is this part of the constructor tearoff work?

cc @srawlins

**Comment by eernstg** [comment]
@devoncarew 
> is this part of the constructor tearoff work?

Leaf and I discussed this. There should not be a need to guard this feature by an experiment flag, but it would be good if it can fit into the schedule with the October milestone.

**Comment by devoncarew** [comment]
@srawlins  - pinging this issue. This is currently part of the work we expect to ship for the next stable - branching in ~8 days. Do you expect to have this done by then (or should we re-plan)?
