### ISSUE TITLE
Loading JS file working in application and not in plugin

### ISSUE THREAD

**Issue by johannphilippe** [dart-lang/sdk#46851]
I'm working on a multi-platform plugin for exposing Csound API to Dart. 
For the web part, it is using a Javascript file generated with Emscripten (CsoundObj.js) and another one (CsoundDart.js, mostly glue upon CsoundObj.js). 
The dart side is a simple wrapper using package:js. 
I tested in a Flutter app, loading Javascript files from index.html `<script>...</script>` and it works fine. 
In the plugin project, I load the Javascript files from assets with 
```
html.document.body.append(html.ScriptElement()
   ..src = "assets/packages/csounddart/assets/CsoundObj.js"
   ..type = "text/javascript"
   ..defer = true
);
```  
I make this manipulation for both files. Unfortunately, while the second file (CsoundDart.js) seems to load properly, the CsoundObj class is undefined, and I get the following error from CsoundDart.js : `ReferenceError: CsoundObj is not defined`.
I can confirm (I tested with another dummy file) that it is not a scope question (CsoundDart.js can access scope from other files dynamically loaded like showed above).
CsoundObj.js is attached below. 

[CsoundObj.js.zip](https://github.com/dart-lang/sdk/files/6950652/CsoundObj.js.zip)

**Comment by vsmenon** [comment]
I suspect this is an ordering issue.  You may need to wait on Dart execution dependent on that script until the script is loaded.

Some options:
- Try not setting `defer` - this is telling to browser it can defer loading the script.
- Use `ScriptElement`'s `onLoad` to signal when the script has been loaded.

**Comment by johannphilippe** [comment]
Thank you for advices. 
The removing of `defer` doesn't seem to change anything. 
About the second solution, I tried the following : 
```
html.ScriptElement elem = html.ScriptElement()
  ..src = "assets/packages/csounddart/assets/CsoundObj.js"
  ..type= "text/javascript";

elem.onLoad.lastWhere((element) {
  html.document.body.append(html.ScriptElement()
   ..src = "assets/packages/csounddart/assets/CsoundDart.js"
   ..type = "text/javascript"
   ..defer = true
);
  return true;
});
``` 
Do you think it's correct ? It returns the same `CsoundObj is not defined`

**Comment by johannphilippe** [comment]
Anyway, I'm not sure it's an ordering issue, since I also tried to copy the content of CsoundObj.js inside CsoundDart.js, and it returns the same issue. Though, when including both JS files in the index.html of an app, it works fine. 
Is there a difference in the JS engine working in plugins and apps ?

**Comment by vsmenon** [comment]
That sort of error is typically an ordering issue.  I'd suggest adding prints (e.g., `console.log`) in your JS files where the specific types are defined and your Dart and seeing how it differs in the various cases.

Re plugins - that's a Flutter concept, not a Dart one.  I wouldn't be surprised if there is extra async / ordering issues there, but you may want to ask on a Flutter forum.

**Comment by vsmenon** [comment]
BTW, one thing I should add - you probably need to set:
```
  ...async = false
  ...defer = false
```
explicitly is you want synchronous script loading.  This is due to browser behavior, not Dart specific.

**Comment by johannphilippe** [comment]
Are you sure it could be an ordering issue even if loading both files concatenated as one file still returns the same result ? 
I appended the CsoundDart.js at the end of CsoundObj.js and it's still the same. It's weird since the `CsoundObj is not defined` error comes from the code I appended, while CsoundObj is supposed to be defined at the begining of the file.

**Comment by johannphilippe** [comment]
I tried your recommendations with same results. I will ask on the flutter side. 
Thank you for your time !

**Comment by vsmenon** [comment]
If the error is coming from usage in Dart, it may be that those scripts aren't loaded before your Dart code is executed.

**Comment by vsmenon** [comment]
Closing here as I don't believe there is a Dart SDK bug or feature request here.
