### ISSUE TITLE
[Dart FFI] How to pass Struct list from Dart to C/C++ Using FFI?

### ISSUE THREAD

**Issue by Xwnine** [dart-lang/sdk#46857]
Cpp side:

```
struct MyStruct {
  char* address;
  int32_t port;
};

bool Connect(MyStruct address[], uint32_t address_sizes) = 0;
```

## Dart side:
```
class MyStruct extends Struct {
  Pointer<Utf8> address;

  @Int32()
  int port;
}
````

How to pass Struct list from Dart to C/C++ Using FFI?

**Comment by simolus3** [comment]
At least in C, an array is just the pointer to the first element, so you can do this:

```dart
typedef _connect_native = Int8 Function(Pointer<MyStruct> address, Uint32 addressSizes);
typedef _connect_dart = int Function(Pointer<MyStruct> address, int addressSizes);

final library = DynamicLibrary.open(path);

final function =
    library.lookupFunction<_connect_native, _connect_dart>('Connect');
final array = malloc<MyStruct>(10);
function(array, 10);
free(array);
```

**Comment by sososdk** [comment]
> At least in C, an array is just the pointer to the first element, so you can do this:
> 
> ```dart
> typedef _connect_native = Int8 Function(Pointer<MyStruct> address, Uint32 addressSizes);
> typedef _connect_dart = int Function(Pointer<MyStruct> address, int addressSizes);
> 
> final function =
>     library.lookupFunction<_connect_native, _connect_dart>('Connect');
> final array = malloc<MyStruct>(10);
> function(array, 10);
> free(array);
> ```

Hello @simolus3 , can I transfer existing data:

```dart
void connect(List<MyStruct> data) {
  // How to convert data into pdata?
  final pdata;
  final size = data.length;
  function(pdata, size);
}
```

**Comment by simolus3** [comment]
Sure, but you'll have to copy:

```dart
final cArray = malloc<MyStruct>(data.length);
for (var i = 0; i < data.length; i++) {
  final source = data[i];
  final dest = cArray[i];
  dest
    ..address = source.address
    ..port = source.port;
}

function (cArray, data.length);
free(cArray);
```
