### ISSUE TITLE
Bogus analyzer error for `late` field initializer referencing super?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#46850]
`late` member variables are able to use field initializers that reference `this`, so I don't see why `super` should be any different.  Given the following code:

```dart
class Base {
  final int value = 42;
}

class Derived extends Base {
  late int _value = super.value;

  @override
  int get value => _value;
}

void main() {
  var derived = Derived();
  print(derived.value);
}
```
the analyzer prints:
```
  error • example.dart:6:21 • Invalid context for 'super' invocation. •
          super_in_invalid_context
```
However, there seems to be no issue when actually running the above code.  Regardless of whether `super` should be allowed here, this behavior is inconsistent.

I've observed the analyzer error in both DartPad (Flutter 2.2.3 Dart SDK 2.13.4) and when running `dart analyze` (Dart SDK version: 2.13.4 (stable)).

**Comment by jcollins-g** [comment]
`  // ignore: super_in_invalid_context ` seems to help, so marking as P2.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/213029
