### ISSUE TITLE
Uninvoked Lists Being Changed Through Other Lists

### ISSUE THREAD

**Issue by John235643** [dart-lang/sdk#46856]
```
void main() {
  List<int> keepMe = [1,2,3];
  List<int> changeMe = keepMe;
  changeMe.removeLast();
  print('changeMe: $changeMe'); // [1, 2]
  print('keepMe: $keepMe');     // [1, 2]
}
```
I think what's happening is "changeMe" is pointing to the same location in memory as "keepMe" so if either changes, they both change. Is this intended behavior? If so, it doesn't seem like this logic is consistently applied (see below).
```
void main() {
  var keepMe = 2;
  var changeMe = keepMe;
  changeMe = 9;
  print('changeMe: $changeMe'); // 9
  print('KeepMe: $keepMe');     // 2
}
```
Dart SDK version: 2.13.4

**Comment by vsmenon** [comment]
Yes, this is intended behavior.  The assignment to `changeMe` is just a shallow copy of the top-level value, not a deep copy of the memory that is transitively pointed to.  Note, this is similar to most languages in this space (e.g., Java, JavaScript).

You may want to follow up here if you have questions:

https://dart.dev/community#join-the-conversation
