### ISSUE TITLE
num.tryParse is much slower in null-safety mode (sdk >=2.12.0) when parsing fails (in VM)

### ISSUE THREAD

**Issue by f69** [dart-lang/sdk#46865]
When using num.tryParse to parse content of relatively large CSV file with mixed-type fields (several megabytes in size; trying to parse every field - several hundreds of thousands in total) it becomes **much** slower in null-safety mode than without null safety and causes unacceptable performance of real app.

Test example:
```
void main(List<String> arguments) {
  final stopwatch = Stopwatch()..start();
  for (int i = 0; i < 100000; i++) num.tryParse('abc');
  print(stopwatch.elapsed);
}
``` 
Test results (on Mac Book Pro):
pubspec.yaml:
```
environment:
  sdk: '>=2.10.0 <3.0.0'
```
`0:00:00.041545`

```
environment:
  sdk: '>=2.12.0 <3.0.0'
```
`0:00:01.142831`

**30 times slower!**
With Flutter and Android emulator or real device situation is even worse: up to **100 times slower!**

```
% dart --version
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"
```

**Comment by mraleph** [comment]
AFAIK this is fixed on master by 427e17dfce7e1fcd7878b8824c6204192c6e9a21 - this will be included in the next stable release. Try one of the recent development builds.

**Comment by f69** [comment]
I confirm: on
`Dart SDK version: 2.14.0-343.0.dev (dev) (Thu Jul 22 08:02:36 2021 -0700) on "windows_x64"`
result is OK:
`0:00:00.034182`

**Comment by mraleph** [comment]
@f69 thanks for checking!
