### ISSUE TITLE
DDC: Mixing in an implementer of a covariant field or setter results in getter that always returns null

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#46867]
Mixing in an implementer of a covariant field or setter and then concretely implementing that member with another class can result in the target class's getter always returning null in DDC-compiled code. Potentially a similar issue to https://github.com/dart-lang/sdk/issues/29914 (see below).

Reduced test case:

```dart
void main() {
  // Prints 'null', not 'foo from BaseClass' as expected, or even 'foo from Interface'.
  print('SubClass().foo');
  print(SubClass().foo);

  // Setting the value works as expected, though; 
  // this prints 'set foo in BaseClass' as expected.
  SubClass().foo = 'bar';
}

class Interface {
  // This can be a getter and covariant setter or a covariant field.
  covariant Object foo = 'foo from Interface';
}

mixin Mixin implements Interface {}

class BaseClass {
  // This can be a getter/setter or another field.
  Object get foo => 'foo from BaseClass';
  set foo(Object value) {
    print('set foo in BaseClass');
  }
}

// BaseClass.foo satisfies the need to concretely implement Interface.foo when mixed in.
// This issue can also be reproduced by mixing in BaseClass instead of extending it.
class SubClass extends BaseClass with Mixin {}
```

I noticed that the issue does not occur if you tweak this code by either:
- Adding `implements Interface` to BaseClass
- Moving `implements Interface` from Mixin to BaseClass
- Making Interface.foo non-covariant

When logging this class to the console, you can see that there's a setter declared in one of the objects in the prototype chain without a corresponding getter. This seems like a similar issue to https://github.com/dart-lang/sdk/issues/29914, so perhaps the fix is also something similar?

<img width="455" alt="Screen Shot 2021-08-09 at 6 47 41 PM" src="https://user-images.githubusercontent.com/1713967/128796027-33a713e3-5f63-4d5e-9192-52b3e1bbb12c.png">

Dart SDKs I've checked in which the issue occurs:
- Dart 2.14.0-377.0.dev (I only tried with null safety enabled)
- Dart 2.13.3 (both with and without null safety enabled)
- Dart 2.12.0 (I only tried without null safety enabled)

Dart SDKs I've checked in which the issue does not occur:
- Dart 2.10.4
- Dart 2.9.0
- Dart 2.7.2

**Comment by nshahan** [comment]
@greglittlefield-wf Thanks for the minimal reproduction and the detailed investigation. I think I see what the bug is here and I'm testing a fix. The setter with a covariant parameter is causing the synthetic mixin class in the hierarchy to generate a forwarding setter. It should have a matching forwarding getter because there is a getter higher up the class hierarchy but it's missing.
