### ISSUE TITLE
Equality of generic local method tearoffs instantiated with the same type variable

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#46864]
I've observed in some discussions [\[1\]](https://github.com/dart-lang/language/issues/1777#issuecomment-892608249) [\[2\]](https://dart-review.googlesource.com/c/sdk/+/197168/1..7/tests/language/generic_methods/explicit_instantiated_tearoff_test.dart#b41) that there is no specification for equality on generic local method tearoffs but some implementations do support it. In a language test I've found there are expectations for non-equality that will fail in DDC with my work in progress changes to support the constructor-tearoff experiment:

https://github.com/dart-lang/sdk/blob/0b1ddaa598d4fcc2fdf2eb750623d30326191d46/tests/language/generic_methods/explicit_instantiated_tearoff_test.dart#L158

https://github.com/dart-lang/sdk/blob/0b1ddaa598d4fcc2fdf2eb750623d30326191d46/tests/language/generic_methods/explicit_instantiated_tearoff_test.dart#L163

Should these expectations be removed? The now specified equality for other forms of instantiated generic method tearoffs makes this expectation of non-equality inconvenient to satisfy in DDC.

1. https://github.com/dart-lang/language/issues/1777#issuecomment-892608249
2. https://dart-review.googlesource.com/c/sdk/+/197168/1..7/tests/language/generic_methods/explicit_instantiated_tearoff_test.dart#b41

cc @eernstg @lrhn

**Comment by eernstg** [comment]
I would prefer that we do not test for `notEquals` in these cases: We could introduce rules about certain local functions being equal (or even identical) in specific situations. But it is likely to prevent some optimizations if we require other pairs of local functions to be not-equal, and I do not think there is a language semantics contradiction in allowing those optimizations (in other words, we don't specify not-equal in any more general rule that applies to those local functions as a special case).

**Comment by eernstg** [comment]
@lrhn, would you be happy about removing tests  extension instance method equality? Cf. https://dart-review.googlesource.com/c/sdk/+/209860.

**Comment by lrhn** [comment]
I would, for now.

**Comment by eernstg** [comment]
Closing: https://dart-review.googlesource.com/c/sdk/+/209860 has landed.
