### ISSUE TITLE
Can't read full type name from DartType

### ISSUE THREAD

**Issue by ductranit** [dart-lang/sdk#46885]
I have class like this
```
class Test {
    Map<MyEnum, Map<String, String>> animations = {};
}

```
Then I used [source_gen](https://github.com/dart-lang/source_gen) to scan & read properties of this class
```
class MyGenerator extends Generator {
 @override
 String generate(LibraryReader library, BuildStep buildStep) {
    library.allElements.forEach((element) {
      final classElement = cast<ClassElement>(element);
      final annotations = library.annotatedWith(typeChecker);
      if (classElement != null && !classElement.isEnum) {
        for (var field in classElement.fields) {
          var type = field.type.getDisplayString(withNullability: false);
           // I expect the type is "Map<MyEnum, Map<String, String>>" but it returns "Map<dynamic, Map<dynamic, dynamic>**>"
          print(type);
        }
      }
    });
 }
}
```
Before I can get the full type of DartType with [getDisplayString()](https://pub.dev/documentation/analyzer/latest/dart_element_type/DartType/getDisplayString.html)
It returns the value `Map<MyEnum, Map<String, String>>`
But now it returns `Map<dynamic, Map<dynamic, dynamic>**>`
I did upgrade the sdk many times, so I don't remember which version that could work before.
This is my current version
```
Dart SDK version: 2.14.0-383.0.dev (dev) (Wed Aug 4 23:26:45 2021 -0700) on "macos_x64"
```
From the document, I know that I shouldn't depend on getDisplayString(), but I can't find other way to do that.
How can I get the correct type of properties like Map, List...?

**Comment by vsmenon** [comment]
FYI - @scheglov @srawlins - expected behavior or a regression?

**Comment by scheglov** [comment]
Could you please provide the full enough subset of the generator, so that something could be run to reproduce this issue? From a first glance it should give the type. Converting it to code is a different question, but it should not be all dynamic.

**Comment by scheglov** [comment]
FWIW, I cannot reproduce this in a standalone unit test.
```dart
  solo_test_XXX() async {
    await resolveTestCode(r'''
class Test {
    Map<MyEnum, Map<String, String>> animations = {};
}
''');
    var type = findElement.field('animations').type;
    print(type.getDisplayString(withNullability: true),);
  }
```
The result:
```console
00:01 +0: ClassAliasDriverResolutionTest | solo_test_defaultConstructor                            
Map<dynamic, Map<String, String>>
00:01 +1: All tests passed!                                                                        
```
We have `dynamic` because `MyEnum` is not declared.

I don 't think this is related to `getDisplayString()`, it simply outputs types. It must be related to type resolution, but I have hard time to imagine how to get `Map` resolved, but not `String`.

**Comment by srawlins** [comment]
I'll close as stale. If we can get a complete reproduction, please re-open.
