### ISSUE TITLE
Shift right operator is wrong: 12345678901234>>1 == 971446265

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#46884]
Hi, this simple code:

```
void main() async {
  final a = 12345678901234;
  print('a=$a a>>1=${a>>1} a/2=${a/2}');
}
```

When run in dartpad.dev gives me:

```
a=12345678901234 a>>1=971446265 a/2=6172839450617
```

Notice the shift right operator yields very strange result. This breaks my app totally, because I expect shift right operator is correct...

I guess it is because of javascript's problem (https://stackoverflow.com/questions/6847636/bitwise-operations-with-big-integers). But in that case, it may be better to warn or forbid such operations in dart?

**Comment by vsmenon** [comment]
Yes, `int` is platform dependent.  See here for details and (at the bottom) for workarounds when you need exactness over performance:

https://dart.dev/guides/language/numbers

In general, warning would be noisy as nearly all math operations can demonstrate platform differences.

**Comment by vsmenon** [comment]
Closing as working as designed.
