### ISSUE TITLE
No errors in analyzer for constructor tear-offs that violate bounds

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#46896]
The following test produces no issues in analyzer but has an errors in CFE

```dart
import "../../Utils/expect.dart";

class C<T extends num> {
  int? i;

  C() { i = 0; }

  C.constr1(int i) { this.i = 1; }
  C.constr2(int num, String str) { this.i = 2; }
  C.constr3() { i = 3; }
}

main() {
  Expect.equals(2, (C<dynamic>.constr2)(1, "").i); // CFE Error: Type argument 'dynamic' doesn't conform to the bound 'num' of the type variable 'T' on 'C<T> Function<T extends num>(int, String)'.
  Expect.equals(3, (C<dynamic>.constr3)().i); // CFE Error: Type argument 'dynamic' doesn't conform to the bound 'num' of the type variable 'T' on 'C<T> Function<T extends num>()'.
}
```
Tested on `Dart SDK version: 2.14.0-edge.d7c0271ac0d37f4c6391e77af3fcf987aaf47cfb (be) (Mon Aug 9 23:56:19 2021 +0000) on "windows_x64"`

@eernstg please confirm which tool is correct here

**Comment by eernstg** [comment]
Instances of a generic class must have actual type arguments that satisfy the bounds (an object can't have a super-bounded type), and the same constraint carries over to instantiated constructor tearoffs.

In the feature spec, this rule is a consequence of the association between a constructor tearoff and a generic helper function, `...$tearoff`, as described [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md#named-constructor-tear-off):

> `<typeParams>` are exactly the same type parameters as those of the class declaration of C (including bounds)

This implies that evaluation of the constructor tearoff corresponds to a function tearoff with the same type arguments, and in that case it is also a compile-time error to violate the bounds.

(We do check some bounds at run time, but this only occurs for instance methods, so for a function which is not an instance method it is actually true that every bound violation is flagged as an error at compile-time.)

**Comment by srawlins** [comment]
I think I fixed this last week. Analyzer now reports, "'dynamic' doesn't conform to the bound 'num' of the type parameter 'T'."
