### ISSUE TITLE
Name shadowing issue with globals vs base class fields

### ISSUE THREAD

**Issue by tetkin-g** [dart-lang/sdk#46895]
There appears to be a compiler issue related to name shadowing.

If there's a global function `thing`, and a class that has a field also named `thing`, then code within a method in that class referring to `thing` will correctly resolve to the field in the class rather than the global.

However if there is a base class that has a field named `thing`, then code in a method in a *sub-class* that referring to `thing` will resolve to the global rather than the field in the base class.

As far as I understand it, the field in the base class should take priority over the global symbol.

See example here:
https://dartpad.dartlang.org/?id=522e2dbbcc79d7beebc22b122a1fef1e&null_safety=true

```dart
void main() {
  Foo1().hi();
  Foo2().hi();
}

void thing() {
  print('global thing');
}

class Base {
  int thing = 888;
}

class Foo1 extends Base {
  void hi() {
    print('Foo 1 thing: $thing'); // <-- this somehow ends up referring to the function not the field.
  }
}


class Foo2 {
  int thing = 777;
  
  void hi() {
    print('Foo 2 thing: $thing'); // <-- this resolves to the field rather than the global.
  }
}
```

* Dart SDK 2.13.4
* Chrome, macOS

**Comment by eernstg** [comment]
This is working as intended. As a rule of thumb in Dart, the lexical scope always takes priority over other sources of lookups. For gory details, check the section 'Lexical Lookups' in the [language specification](https://spec.dart.dev/DartLangSpecDraft.pdf).
