### ISSUE TITLE
Typo in test comment

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#46898]
`veryify` is misspelled in

https://github.com/dart-lang/sdk/blob/b2b8e59b2863ef02709dfdb750e9ae8e3732389c/pkg/analysis_server/test/lsp/completion_yaml_test.dart#L527

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/210001

**Comment by lrhn** [comment]
It's very verified! Good catch.

**Comment by vsmenon** [comment]
Thanks for the fix!
