### ISSUE TITLE
webdev build/serve has issues with conditional imports 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#46918]
I am trying to write code which is shared between Web and native platforms which uses `HttpStatus` class. I have tried the following: 

1. 
    ```dart
    import 'dart:io' show HttpStatus;
    ```
    Works on `dart2js` breaks `webdev serve` with 
    ```
    [WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling grpc_web|web/main.dart with ddc because some of its 
    transitive libraries have sdk dependencies that not supported on this platform:

    grpc|lib/src/shared/status.dart
    ```
1. 
    ```dart
    import 'dart:io' if (dart.library.html) 'dart:html' show HttpStatus;
    ```
    Works on `dart2js` breaks `webdev serve` with 
    ```
    [WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling grpc_web|web/main.dart with ddc because some of its 
    transitive libraries have sdk dependencies that not supported on this platform:

    grpc|lib/src/shared/status.dart
    ```
1. 
    ```dart
    import 'http_status_stub.dart'
      if (dart.library.io) 'dart:io'
      if (dart.library.html) 'dart:html' show HttpStatus;
    ```

    Works on `dart2js` breaks `webdev serve` with 

    ```
    [SEVERE] build_modules:module_library on package:grpc/src/shared/http_status.dart: Invalid argument(s): Unsupported conditional import of `dart:io` found in grpc|lib/src/shared/http_status.dart.
    ```

What finally worked is to create `http_status_{web,io}.dart` which `export` `HttpStatus` from `dart:io` and `dart:html` respetively and then have `http_status.dart` which conditionally exports `http_status_{web,io}.dart`.

```dart
export 'http_status_io.dart' if (dart.library.html) 'http_status_web.dart';
``` 

This seems broken. I think https://github.com/flutter/flutter/issues/71961 is the same issue.

**Comment by jakemac53** [comment]
Yes - webdev/build_runner do not support conditional imports/exports of `dart:` libraries directly. It requires you to use the export pattern.

In general conditional imports should expose the same API on all platforms. That isn't _why_ we don't support it, but it is why we decided not to invest in fixing it.

**Comment by mraleph** [comment]
I think limitation itself is fine, but error message should probably be improved to explain what exactly is not supported and how to address it. I discovered the workaround by accident (simply because I know that some form of conditional imports _is supported_).

**Comment by mraleph** [comment]
Additionally I'd expect that 2 behaves the same as 3 (throws an error) otherwise it is confusing that you add a conditional import and it simply _does nothing_.

**Comment by jakemac53** [comment]
Ya the message could definitely be better here, and its fair to expect the same output in those cases. We handle them differently and the first one just takes precedence and exits early before we even get to checking for conditional imports today. But it looks pretty easy to improve.
