### ISSUE TITLE
[suggestion] ChangeBuilder to check visible type before `writeType()`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#46911]
To handle `DartEditBuilder`.`writeType()` for unreferenceable type, there is a pattern of checking the visible type:

https://github.com/dart-lang/sdk/blob/fc4d4144fb0503cc4bebb46cc478ef7a9538fced/pkg/analysis_server/lib/src/services/correction/dart/add_type_annotation.dart#L84-L86

How about if we add two methods in `ChangeBuilder` and `DartEditBuilder`, so that we have something like:

    ChangeBuilder builder = ...
    DartEditBuilder dartEditBuilder = builder.getDartEditBuilder(String path);
    // expose the existing _getVisibleType()
    if (dartEditBuilder.getVisibleType(type) != null) {
      // make the needed changes
    }

I believe this would be better pattern to use.

**Comment by bwilkerson** [comment]
I would rather have a method like
```
bool canWriteType(DartType type) { ... }
```
that returns the same value as `writeType` would return when given the same `type`. That way, if `writeType` needs to fail under other circumstances in the future user code will still be predicated on the correct semantics.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/210463

**Comment by asashour** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/86898c2ee6ad46758a43a197bcdc374591f2c5a5
