### ISSUE TITLE
AnalysisSession `getResolvedUnit2` is slower than AnalysisServer unit resolution

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#46914]
While comparing the performance of `dart analyze` and Dart Code Metrics cli we found out that our cli is much slower than `dart analyze`. For Dart Code Metrics we use `AnalysisContextCollection` and `context.currentSession.getResolvedUnit2` to get a file `ResolvedUnitResult` for further analysis and dart analyze [launches AnalysisServer](https://github.com/dart-lang/sdk/blob/master/pkg/dartdev/lib/src/commands/analyze.dart#L99).
Here is some measurement for [a PR we have](https://github.com/dart-code-checker/dart-code-metrics/pull/344):

> dart analyze command takes about 3-5 seconds on our codebase, dart_code_metrics CLI runs about two minutes.
>
> I am not sure if this is some environment configuration or maybe Windows issue. On my machine results of this simple profiling code are:
>
> contextForMs: 76, getResolvedUnitMs: 115290, runAnalysisforFileMs: 128.

which shows that the most time consuming operation is `getResolvedUnit2` call.

If we replace `getResolvedUnit2` call with `getParsedUnit2` it will work a lot faster, but won't provide all additional info `ResolvedUnitResult` has which is really important for our analysis.

And we can't launch `AnalysisServer` by ourself because it doesn't know when the plugin analysis is completed: https://github.com/dart-lang/sdk/issues/38407 

Could you take a look at `getResolvedUnit2`, is it really slow or we just misuse it somehow?

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
All things equal, there should not be significant difference in performance of `dart analyze` and `AnalysisContextCollection`, simply because `dart analyze` runs the analysis server (DAS), which [implements](https://github.com/dart-lang/sdk/blob/6f917d00afff06691369d87f2857097726326c66/pkg/analysis_server/lib/src/context_manager.dart#L418) its analysis using `AnalysisContextCollection`.

One difference though is that DAS uses on-disk cache, so can reuse analysis results (errors, linked element models, etc) for files that are not affected by the changes. It does this by providing `ByteStore`, which is not available via API. So, DAS does not have to analyze as many files, so might do much less work, so faster.

On my computer the on-disk cache is located in `/Users/scheglov/.dartServer/.analysis-driver`. You could try to clear it to see if DAS then has the same (slow) performance as using `AnalysisContextCollection`.

**Comment by incendial** [comment]
> You could try to clear it to see if DAS then has the same (slow) performance as using AnalysisContextCollection.

Before clearing `.analysis-driver` folder `dart analyze` took ~8 secs to complete, but after I removed the folder, it took ~45 secs to complete. So, the on-disk cache definitely helps a lot. 

> It does this by providing ByteStore, which is not available via API.

Could you make it available or we need to implement a similar cache by ourself?

**Comment by scheglov** [comment]
We don't have plans to make `ByteStore` API, but if you are willing to accept that it might break at some point, you could instantiate `AnalysisContextCollectionImpl` instead, and give it a `ByteStore` instance, e.g. `FileByteStore` or `EvictingFileByteStore`, or even implement it yourself to satisfy caching needs of your system.

**Comment by incendial** [comment]
Thank you! May I ask why you don't have plans to provide API for `ByteStore`? I hope your answer might help us choose between using `AnalysisContextCollectionImpl` or implementing our own cache (ex. if you have plans to change `ByteStore` significantly in the nearest future).

**Comment by scheglov** [comment]
I don't have any specific reason for this, it just has never been a priority for anyone. FWIW, `ByteStore` interface was stable for long time.

**Comment by incendial** [comment]
Got it, thank you!

**Comment by bwilkerson** [comment]
> ... it just has never been a priority for anyone.

It sounds to me like it's a priority for plugin authors and I think we ought to reconsider. While I'm not necessarily suggesting that we make `ByteStore` part of the public API, we might want to consider adding a parameter to `AnalysisContextCollection.new` that allows clients to request that a byte store be used. I'm not sure whether that's a path to a directory or something else, but anytime the answer to a legitimate need is "use internal classes", I think we should consider the option of extending the public API to address the need.

**Comment by incendial** [comment]
> It sounds to me like it's a priority for plugin authors and I think we ought to reconsider. 

I think it depends on wether a plugin has its own cli or not. If the problem with `AnalysisServer` picking up signals from plugins will be solved, I guess a separate cli will not be required at least for plugins that "just add custom lints". But yeah, if we talk about another type of analysis (like we have an unused files search) a separate cli will still be a thing.

> While I'm not necessarily suggesting that we make ByteStore part of the public API, we might want to consider adding a parameter to AnalysisContextCollection.new that allows clients to request that a byte store be used.

That definitely the API we'd use. For example, I've tested cli runs with `EvictingFileByteStore` and on our codebase I see a 30% increase of overall run (from 24 secs to 16, and it looks like 8 are spent on compiling or something). But I think on a larger codebase the difference will be bigger.

**Comment by scheglov** [comment]
Touching just the compiling portion for now. When you run Dart sources, Dart VM has to parse the code and compile into kernel (Dart, not OS) code, and then JIT execute it. If you run the same code again and again, it might be beneficial to pre-compile it. See https://dart.dev/tools/dart-compile

It seems to make one of my ad hoc analysis scripts quite faster.
```
scheglov@scheglov-macbookpro2:~/Source/Dart/sdk.git/sdk/pkg/analyzer_cli/bin $ dart compile exe analyzer2.dart
Info: Compiling without sound null safety
Generated: /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer_cli/bin/analyzer2.exe

scheglov@scheglov-macbookpro2:~/Source/Dart/sdk.git/sdk/pkg/analyzer_cli/bin $ time ./analyzer2.exe
Analyzing /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/tool/messages/generate.dart...
No issues found!
./analyzer2.exe  3.89s user 0.27s system 113% cpu 3.678 total

scheglov@scheglov-macbookpro2:~/Source/Dart/sdk.git/sdk/pkg/analyzer_cli/bin $ time dart analyzer2.dart
Analyzing /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/tool/messages/generate.dart...
No issues found!
dart analyzer2.dart  18.88s user 1.89s system 150% cpu 13.788 total
```

**Comment by incendial** [comment]
Thanks for pointing that out, it's quite impressive to see 20s -> 4s change! But there is no way to distribute pre-compiled code through pub, right? Meaning that we need to publish it using `brew` or any other package manager to make it available to the end users.

Also, we found a bug with compiling for Windows some time ago: https://github.com/dart-code-checker/dart-code-metrics/issues/385 (with a stack trace). I'm not sure that the problem still here (I'll ask to check it again), but maybe you know something about that?

**Comment by scheglov** [comment]
No, I don't know how to use `pub` and executables.

The path to `libraries.dart` in [the issue](https://github.com/dart-code-checker/dart-code-metrics/issues/385) does not look like a path in a Dart SDK  directory. It could be, but I would expect something like `dart-sdk` in there.

**Comment by incendial** [comment]
> The path to libraries.dart in the issue does not look like a path in a Dart SDK directory. It could be, but I would expect something like dart-sdk in there.

Hm... I'll take a look on how the sdk path is resolved, thanks!

**Comment by Levi-Lesches** [comment]
>  But there is no way to distribute pre-compiled code through pub, right?

If you have your entrypoint in `bin`, then have your users run `dart pub global activate ...` pub should automatically pre-compile your executable into a snapshot. I believe it's slower than exe's, but it should be a bit faster than a standard .dart file.

**Comment by incendial** [comment]
>  I believe it's slower than exe's, but it should be a bit faster than a standard .dart file.

Not sure about that: https://github.com/dart-code-checker/dart-code-metrics/pull/428#issuecomment-901034813, but haven't tested it myself.

**Comment by Levi-Lesches** [comment]
From reading that issue, it seems the tests were run using a `path` source instead of pulling from pub.dev: 

> ```
> dart pub global activate -spath D:\Projects\GitHub\dart-code-metrics
> ```

 But pub doesn't precompile from path sources (since it expects it to change). So perhaps the tests run there aren't reflecting what users are seeing when they use pull from pub.dev.

**Comment by incendial** [comment]
> But pub doesn't precompile from path sources (since it expects it to change). So perhaps the tests run there aren't reflecting what users are seeing when they use pull from pub.dev, which are precompiled.

That's interesting, didn't think about that. We'll run more tests with a published version then, thanks!
