### ISSUE TITLE
`main` exits while waiting for `Future`

### ISSUE THREAD

**Issue by MikhailZex** [dart-lang/sdk#46919]
Thank you for taking the time to file an issue!

Details: 
* Related to: Dart core libraries ("dart:async", "dart:io", etc.)

* Dart SDK Version (`dart --version`)
```
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "windows_x64"
```

The problem actual:
```dart
Future<void> main(List<String> args) async {
  var st = DateTime.now();

  // var filePath = r'D:\Games\Chronos - Before the Ashes\Chronos\Content\Paks\Chronos-WindowsNoEditor.pak';
  // var filePath = r'D:\Games\Mass Effect - LE\Game\ME1\BioGame\CookedPCConsole\Lighting1.tfc';
  var filePath = './bin/counter.dart';

  var len = await File(filePath).length();

  var chunkSize = len ~/ 8;

  var pool = ProcessorPool(countFile);
  await pool.start();

  for (var i = 0; i < 8; i++) {
    var startIndex = i * chunkSize;
    var endIndex = i == 7 ? len : startIndex + chunkSize;

    pool.send([filePath, startIndex, endIndex]);
  }


  pool.shutdown();

  await for (var each in pool.outputStream) {
    // ⚠main just exits here instead of waiting for the value of each,
    // ⚠in actuality, the value of each will take considerable computaion and time, hence the use
    // ⚠of isolates to speed up the work but instead main exits while waiting for the value
    await each;
  }

  print(DateTime.now().difference(st));
}

```

My code is at https://github.com/MikhailZex/processors/blob/master/bin/counter.dart

Am new to dart & have tried searching for possible errors/fixes on stackoverflow, no luck so far so I assume its a bug. If I'm wrong, please do close this issue and point me in the right direction.

Thanks in advance.

**Comment by mraleph** [comment]
Based on the cursory read of you package code, I'd guess you are missing proper handling of asynchrony here: https://github.com/MikhailZex/processors/blob/master/lib/src/processor.dart#L268. Note that your processing function is actually asynchronous - but the code does not seem to handle it. You probably should have an await here and make sure that no further events are processed from the port until `function` finishes.

**Comment by lrhn** [comment]
(Also consider looking at the code of [`IsolateRunner`](https://pub.dev/documentation/isolate/latest/isolate.isolate_runner/IsolateRunner-class.html) and [`LoadBalancer`](https://pub.dev/documentation/isolate/latest/isolate.load_balancer/LoadBalancer-class.html) from the recently discontinued `package:isolate`. That package isn't maintained anymore, but the code should still be fine as a reference).

**Comment by MikhailZex** [comment]
Thanks a lot guys, found the problem.

The `Processor` is shutdown when a "kill signal" is sent to and then **_mirrored_** back from the isolate [[code here](https://github.com/MikhailZex/processors/blob/24d0bf58a832ec4217f4b5bf92636dadba965153/lib/src/processor.dart#L155)]

when running an async function in the isolate, the kill signal is mirrored and the isolate shut down  _**while the async fn is paused on an await.**_

Normally your just await the `Future` in your main process code, the calc will still run in the isolate but that doesn't work here because the isolate is shutdown - i.e. you end up with an isolated that closes before it serves it purpose and `Future`s that never complete.
