### ISSUE TITLE
StreamTransformer default constructor documentation wrong?

### ISSUE THREAD

**Issue by EPNW** [dart-lang/sdk#46924]
The documentation for [`StreamTransformer()`](https://api.dart.dev/stable/2.13.4/dart-async/StreamTransformer/StreamTransformer.html) in dart 2.13.4 lists the following example:
```dart
/// Starts listening to [input] and duplicates all non-error events.
StreamSubscription<int> _onListen(Stream<int> input, bool cancelOnError) {
  late StreamSubscription<String> subscription;
  // Create controller that forwards pause, resume and cancel events.
  var controller = new StreamController<String>(
      onPause: () {
        subscription.pause();
      },
      onResume: () {
        subscription.resume();
      },
      onCancel: () => subscription.cancel(),
      sync: true); // "sync" is correct here, since events are forwarded.

  // Listen to the provided stream.
  subscription = input.listen((data) {
    // Duplicate the data.
    controller.add(data);
    controller.add(data);
  },
      onError: controller.addError,
      onDone: controller.close,
      cancelOnError: cancelOnError);

  // Return a new [StreamSubscription] by listening to the controller's
  // stream.
  return controller.stream.listen(null);
}

// Instantiate a transformer:
var duplicator = const StreamTransformer<int, int>(_onListen);

// Use as follows:
intStream.transform(duplicator);
```

As far as I can see, the type arguments for `subscription` and `controller` should be `int`, not `String`?

**Comment by Levi-Lesches** [comment]
I copied the code to Dartpad and verified that changing `controller` to `Stream<int>` fixes all the errors.

**Comment by lrhn** [comment]
The code is also not a particularly good example any more, I'll rewrite it to something modern.

**Comment by EPNW** [comment]
> 
> 
> The code is also not a particularly good example any more, I'll rewrite it to something modern.

Good to hear that, I already started basing my code for an SyncStreamTransformer on it 😁.  I will wait then for the next example 👍
