### ISSUE TITLE
Failures on [VM/Runtime] Added a Dart VM initialization state to prevent racy access

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#46922]
There are new test failures on [[VM/Runtime] Added a Dart VM initialization state to prevent racy access](https://github.com/dart-lang/sdk/commit/1f405bf163c64ec732c3a6d604033da0b439628b).

The tests
```
vm/cc/DartAPI_InvokeVMServiceMethod_Loop Crash (expected Pass)
```
are failing on configurations
```
dartk-asan-linux-release-x64
```

**Comment by askeksa-google** [comment]
Also, the test
```
lib_2/isolate/isolate_import_test/none/1 Crash (expected Pass)
```
is failing on configurations
```
dartk-reload-linux-debug-x64
dartk-reload-rollback-linux-debug-x64
```

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/210302 should fix these errors.
