### ISSUE TITLE
[CP][beta channel] Change min SDK version used by 'dart create'

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#46921]
**commit(s) to merge**:
https://github.com/dart-lang/sdk/commit/cfc3a654a5f2ac1df6a16ca74b83e5d59fb5e163

**merge instructions**: clean merge or patch CL
Clean merge.

**What is the issue**: Brief description of the problem
Currently the templates used by `dart create` use a hard-coded min SDK version of `2.14`. This means that new language features can't be used without manually updating the SDK version.

**What is the fix**:
Changes the `dart create` logic to use the version of the SDK itself as the min SDK version.

**Why cherrypick**:
Ensures customers can use new language and SDK features.

**Risk**:
Expected to be very low.

**Link to original  issue(s)**:

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

-

**Comment by vsmenon** [comment]
Approved

**Comment by athomas** [comment]
Merged to beta in 9a1827339c8e4e55a9b214d033aeba7d30daa28f (2.14.0-377.7.beta).
