### ISSUE TITLE
[BUG] [PRIORITY] Unexpected Behavior with Nested Async Generators 

### ISSUE THREAD

**Issue by zs-dima** [dart-lang/sdk#46927]
Looks like Dart language critical issue had been wrongly labeled.

It is Dart core critical issue. It is not just certain 'library' issue. 

Could I kindly ask you if this issue going to be prioritized?

https://github.com/dart-lang/sdk/issues/44616

**Comment by vsmenon** [comment]
The library is where the issue is and @lrhn has been actively looking at #44616.  It is a de facto breaking change, so not trivial to land.

**Comment by AlexandrFarkas** [comment]
It's not about library. It's dart critical issue related to behaviour of yield* and yield. It just happened that BLoC uses this approach.
