### ISSUE TITLE
"PRESUBMIT.py" had an exception

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#46930]
On trying

    git cl upload -s

There is an error

>Running Python 2 presubmit upload checks ...
"C:\use\dart-sdk\sdk\PRESUBMIT.py" had an exception.
invalid syntax (PRESUBMIT.py, line 75)
Maybe your depot_tools is out of date?

I have downloaded the latest `depot_tools` on Windows, however, it seems it still users Python 2 and I assume the commit https://github.com/dart-lang/sdk/commit/d2bd43f43e6636036a3d250eadcd429c444b7540 forces Python 3.

`set USE_PYTHON3=True` doesn't have an effect before `git cl upload -s`

```
C:\>where python
C:\use\depot_tools\python.bat

C:\>python
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
```

which seems to come from

    C:\use\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python\bin

**Comment by athomas** [comment]
@asashour Do you have python3 installed as well?

**Comment by asashour** [comment]
Yes, python3 is installed, and even after putting it at the beginning of the `PATH`, the same error.

![image](https://user-images.githubusercontent.com/2410127/129853869-0be60d00-5c4f-4c37-b30e-b7c86bb4ad2e.png)

```
C:\use\flutter\clone\dart-sdk\sdk>git cl upload -s
Running Python 2 presubmit upload checks ...
"C:\use\flutter\clone\dart-sdk\sdk\PRESUBMIT.py" had an exception.
invalid syntax (PRESUBMIT.py, line 75)
Maybe your depot_tools is out of date?

C:\use\flutter\clone\dart-sdk\sdk>python
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
```

**Comment by athomas** [comment]
It shouldn't fail in the `Python 2 presubmit upload checks` because the `PRESUBMIT.py` file contains `USE_PYTHON3 = True` line. Can you verify that this line is in PRESUBMIT.py in your checkout?

Also, try running `update_depot_tools`, `git pull` (or some other command to ensure that your checkout is on the most recent revision) and `gclient sync`.

**Comment by athomas** [comment]
FYI, I know of at least one developer on Windows that doesn't suffer this particular issue. That's why I'm trying to troubleshoot your setup.

**Comment by athomas** [comment]
Found a potential fix, adding `USE_PYTHON3: True` to `codereview.settings` might fix this (though I can only reproduce the issue if I remove the `USE_PYTHON3 = True` from PRESUBMIT.py).

**Comment by asashour** [comment]
Thanks for your feedback. I am using the latest `master`, and yes the line in `PRESUMIT.py` is there and the history is correct. `update_depot_tools` and `gclient sync` were also executed.

Indeed, putting the line in `codereview.settings` fixes the issue (tested in a test branch), however I can't commit that in other changes.


![image](https://user-images.githubusercontent.com/2410127/130301513-83141b67-a596-4c7a-b7ba-05584a6b41ca.png)

**Comment by athomas** [comment]
I have a CL that changes this in the SDK: https://dart-review.googlesource.com/c/sdk/+/211001

This doesn't really explain your issues, but we want to do this anyway because it will apply to future presubmit scripts as well.
