### ISSUE TITLE
long AOT compilation time due to quadratic code in cid range building code

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#46936]
To repro: 

```dart
$ git clone https://github.com/hydro-sdk/hydro-sdk
$ cd hydro-sdk/
$ git checkout 603
$ flutter pub get
$ $DART_SDK/pkg/vm/tool/precompiler2 -v bin/swid.dart bin/swid.aot
```

AOT compilation will sit in `gen_snapshot` for a very long time. If I `perf record` it I get profile like this: 

```
    24.09%  gen_snapshot  gen_snapshot        [.] dart::Object::HandleImpl
    23.62%  gen_snapshot  gen_snapshot        [.] dart::Class::IsSubtypeOf
    13.14%  gen_snapshot  gen_snapshot        [.] dart::VMHandles::AllocateHandle
     6.83%  gen_snapshot  gen_snapshot        [.] dart::Zone::DeleteAll
     4.98%  gen_snapshot  gen_snapshot        [.] dart::AbstractType::operator^=
     4.83%  gen_snapshot  gen_snapshot        [.] dart::Type::type_class
     2.72%  gen_snapshot  gen_snapshot        [.] dart::TypeArguments::IsUninstantiatedIdentity
     2.02%  gen_snapshot  gen_snapshot        [.] dart::TypeArguments::InstantiateFrom
```

Call-graph points to cid range construction as the source of `IsSubtypeOf` checks. 

I suspect that complicated inheritance hierarchy hits quadratic case in the cid range construction code, because we ask the same `IsSubtypeOf` question again and again. (e.g. given chain A -> B -> C we will ask if `A is D`, then we will ask `B is D` which leads us to ask `A is D` again and so on).

Reported by @chgibb 

/cc @mkustermann

**Comment by mkustermann** [comment]
@sstrickl has made some changes that makes us ask this question even more often, tentatively assigning to her.

**Comment by sstrickl** [comment]
Have some initial thoughts about how to handle this by retrieving (and creating, if necessary) the ranges for subclasses/implementors first and then just merging the ranges appropriately for the base class based on comparing it to its direct subclasses/implementors (instead of all other classes), semi-related to how we create the ranges for JIT. I think that should avoid the issue, though we'll need to see if we end up missing some cases afterwards.

**Comment by sstrickl** [comment]
Okay, have a candidate fix where the profile is much better (below are entries >= 1% of the total runtime):

```
   4,33%  gen_snapshot  gen_snapshot        [.] dart::kernel::KernelLineStartsReader::TokenRangeAtLine
   2,18%  gen_snapshot  gen_snapshot        [.] dart::kernel::KernelTokenPositionCollector::CollectTokenPositions
   1,63%  gen_snapshot  gen_snapshot        [.] dart::ConcurrentMarkTask::Run
   1,54%  gen_snapshot  gen_snapshot        [.] dart::ScavengerVisitorBase<false>::VisitPointers
   1,41%  gen_snapshot  gen_snapshot        [.] dart::PriorityQueue<long, long>::InsertOrChangePriority
   1,25%  gen_snapshot  gen_snapshot        [.] dart::VMHandles::AllocateZoneHandle
```

(Also it runs in 12s, vs. the old version which ran in 8m40s.)

Verifying that the type testing stubs are unchanged between the two, and if so I'll put the CL up for review.

**Comment by sstrickl** [comment]
No changes to type testing stubs after the fix, so it is currently being reviewed as part of [CL 210581](https://dart-review.googlesource.com/c/sdk/+/210581).
