### ISSUE TITLE
shift double number in Dart?

### ISSUE THREAD

**Issue by BigGitWorld** [dart-lang/sdk#46935]
Hi.
I want to shift a double number but dart shows this error : 
```
The operator '<<' isn't defined for the type 'double'. (Documentation)  Try defining the operator '<<'
```
In fact, I have a java code and must convert it to dart language.

**JAVA code:**
```
float number;
...
number = frame[6];   //frame is an short array (short[])
number <<= 8;
number += frame[5];
```

I know we don't have float and short in dart and converted them to double and int.
but the above code does not work in Dart.

**Dart code:**
```
double number;
...
number = frame[6];   //frame is an int array (<int>[])
number <<= 8;
number += frame[5];
```

what is Dart equivalent of the above java code?

**Comment by mraleph** [comment]
> ```
> float number;
> number <<= 8;
> ```

You can't shift `float` type in Java either. Are you sure your Java code actually looks like this? 

You can multiply `number` by 256 or alternatively do `frame[6] << 8`.

**Comment by BigGitWorld** [comment]
Oooops!
You are right. it was short not float in java.
and your solution worked. 
thanks
