### ISSUE TITLE
DDS: Trying to listen on port 80

### ISSUE THREAD

**Issue by knopp** [dart-lang/sdk#46934]
Happens with current master, can be reproduced with `flutter attach`.

The service is initialized with localhost URL: `http://127.0.0.1`.
The problem is that `_startDDSServer()` does the following:

https://github.com/dart-lang/sdk/blob/ada4278fd5a54d58c0aa4a9cc9b1e14a0d3333bc/pkg/dds/lib/src/dds_impl.dart#L130

`uri.port` in this case is 80 (provided by `Uri.defaultPort`). I'm not quite sure why this is an issue now and wasn't before, possibly something changed in flutter tool and now the uri is set actually, but this does look like a bug in DDS.

This causes an access denied exception (only root can bind to 80) and the attach process fails.

**Comment by jmagman** [comment]
@bkonyi

**Comment by bkonyi** [comment]
Where is `Uri.defaultPort` being called? DDS doesn't try and bind to a default port, so if [`serviceUri`](https://pub.dev/documentation/dds/latest/dds/DartDevelopmentService/startDartDevelopmentService.html) is not provided we just bind to a random port. Are you sure `flutter_tools` isn't passing this?

**Comment by knopp** [comment]
> Where is `Uri.defaultPort` being called? DDS doesn't try and bind to a default port, so if [`serviceUri`](https://pub.dev/documentation/dds/latest/dds/DartDevelopmentService/startDartDevelopmentService.html) is not provided we just bind to a random port. Are you sure `flutter_tools` isn't passing this?

https://github.com/dart-lang/sdk/blob/d9048340ba899dc00d2800ab311d79d23a73063f/sdk/lib/core/uri.dart#L1483-L1485

Flutter tools is passing `http://127.0.0.1` (without port). But for HTTP URIs that don't have port the port getter will return 80.

**Comment by bkonyi** [comment]
Ah, gotcha. While that does look like an issue, why are we passing a URI without a port explicitly defined? I think the right thing to do for now is to update the URI to `http:127.0.0.1:0` if we want to bind to a random port for `flutter attach`.

**Comment by knopp** [comment]
You're right. This is the [commit](https://github.com/flutter/flutter/pull/88015/files#diff-427a57df837b7e9b002d94623a94e334f6903f5be4ea290d282561797b6e05c4L48) that is causing it. There's something wrong with the migration. The `hostPort` argument is not nullable, but it is actually `null` (and thus default 80 is used). I'll open a flutter issue.
