### ISSUE TITLE
New static analysis inline ignore directive for "all lints"

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#46957]
In mockito's generated code, I would like "all lints" to be ignored, and not reported by the analyzer.

The code that mockito generates is very dynamic, and depends heavily on the code that triggered it. For example, a user might have code like:

```dart
// ignore: implementation_imports
import 'package:foo/src/foo.dart' show Foo_Thing;
import 'package:mockito/annotations.dart' show GenerateMocks;

@GenerateMocks([Foo_Thing])
void main() {}
```

Mockito will generate code which also refers to Foo_Thing, so must also violate `implementation_imports`. Mockito will generate a new class whose name is based on Foo_Thing, so will also violate the camelCase names lint rule.

**I'd really like to have `// ignore_lints_for_file` or `// ignore_for_file: lints`.**

Right now mockito has almost a dozen lines of `// ignore_for_file: this_lint, that_lint`. Each one comes from a user request where they are generating against code that results in a previously unknown lint violation. Each one requires a release cycle. As more lint rules get added to package:lints, I will get more of these reports.

CC @bwilkerson @pq . This is an alternative (or a supplement) to the more fine-grained analysis configuration proposals.

**Comment by pq** [comment]
Interesting!

Where does mockito generate its files?  Are they separate from or co-mingled w/ other libraries?  Are the names prefixed or suffixed with `mock` or anything identifying?

**Comment by srawlins** [comment]
They can be either; if test/foo_test.dart contains `@GenerateMocks`, then build_runner will generate a `foo_test.mocks.dart` file. This file can go right next to `test/foo_test.dart` or in `.dart_tool/...`, depending on the build.yaml config. By default, I think it is the former.

New classes are prefixed with `Mock_` and others are prefixed with `_Fake_` and suffixed with `_#` where `#` is an increasing unique integer. Other than that, all names and types come from the user's code.

**Comment by Levi-Lesches** [comment]
@srawlins, Would it be possible to have an `analysis_options.yaml` file that excludes `*.mocks.dart`, and have Mockito users insert

```YAML
include: package:mockito/analysis_options.yaml
```

in their `analysis_options.yaml` files?

**Comment by srawlins** [comment]
@Levi-Lesches That is possible.

That would hide all errors that mockito might generate, which I wish to avoid.

**Comment by pq** [comment]
Good question @Levi-Lesches.  One of the ideas we've kicked around could take advantage of globs like that (and was kind of where I was going with my leading question!)

Something like:

```yaml
linter:
  rules:
    directives_ordering:
      exclude:
        - *.mocks.dart
    file_names:
      exclude:
        - *.mocks.dart
        - test/**
    prefer_single_quotes:
      enabled: false
```

**Comment by srawlins** [comment]
Mockito (or any package which generates code) providing an analysis option file is a very powerful idea. But again, we'd need to add to this list of exclusions each time one is found by a user, requiring 3 new lines in this file, and a new release. It's been happening quite a bit, and I don't think there is an end in sight; any new lint rule that addresses naming, imports, parameter types or names, method names or return types, etc. could be violated in user code, and so could additionally be violated in mockito-generated code.

But this analysis_options file idea is slick too. What about:

```yaml
linter:
  exclude:
    - *.mocks.dart
```

:D :D :D

**Comment by Levi-Lesches** [comment]
> @Levi-Lesches That is possible.
> 
> That would hide all errors that mockito might generate, which I wish to avoid.

It hides _all_ errors? I didn't realize that. In any case, the code won't compile, so wouldn't you want that? End users would get the errors when they try to run the tests, but otherwise don't need to be inundated by errors in mock files that really correspond to errors in their user-side code. If you're worried about warnings and lints during development of mockito, the `analysis_options` file in your project root isn't the one being `include`d, that would be in `lib`, so you can have two separate sets of options.

**Comment by srawlins** [comment]
> ... but otherwise don't need to be inundated by errors in mock files that really correspond to errors in their user-side code

Mm, that's an interesting point. So if a user has a source file with a typo, that typo might be carried over (~duplicated) into the generated mocks, which may be distracting. But this only happens on when running `build_runner build` which is generally run manually these days, right? Or is there a watch mode which continually builds generated files as you type/save?

But I do not want errors hidden from users which are in generated code and are present because of a bug in mockito. Showing those errors leads to good bug reports (and of course all of my lint reports).

Your idea means that we push compile-time errors from static errors to runtime errors, which should generally work, but goes against the practice that we prefer to give users errors earlier in their development cycle rather than later.

CC @natebosch who works on Mockito as well, and on the build packages. I wonder if `//ignore_for_file: lints` is something that's been requested for other builders.

**Comment by Levi-Lesches** [comment]
> Your idea means that we push compile-time errors from static errors to runtime errors, which should generally work, but goes against the practice that we prefer to give users errors earlier in their development cycle rather than later.

Just to clarify, I didn't mean runtime errors. I meant ignoring analyzer lints so that they become compile-time errors. So CIs and manual builds are unchanged, just the IDE isn't overrun with mockito errors.

**Comment by natebosch** [comment]
> I wonder if `//ignore_for_file: lints` is something that's been requested for other builders.

We've had requests for the ability to ignore lints in all generated files, but I haven't seen this idea before.

**Comment by pq** [comment]
@natebosch, for your purposes would something like:

```dart
linter:
  exclude:
    - *.mocks.dart
```

work for you?

**Comment by bwilkerson** [comment]
A couple of thoughts.

If we do want to support ignore comments for groups of diagnostics then I would propose that
- we should make group names distinct from diagnostic names, so perhaps something like `severity:lint` (and consider what other kinds of groups we might want to be able to express), and
- we allow it for individual lines as well (it'll probably be easier to implement and it's more consistent).

While it would be possible for users to get the same effect by extending the analysis options file, it would be more convenient if they didn't need to because code generator authors were doing the work for them. It also wouldn't require updating every time a new generator started producing file names that didn't match the current patterns.

On the other hand, having a more general mechanism is appealing for other reasons, and having a single way to accomplish the same task is sometimes helpful to users. And if the metaprogramming proposal pans out we might not have need for the ignore comment style at some point (though I have no idea how long it would be 'till that work was shipped).

**Comment by natebosch** [comment]
> @natebosch, for your purposes would something like:
> 
> ```dart
> linter:
>   exclude:
>     - *.mocks.dart
> ```
> 
> work for you?

Yes that would work.

There are two tradeoffs I can think of:
- handling it once per builder vs once per project using a builder
- giving users no control to enable lints in generated files if they really want to vs mockito generated code never getting linted.

My hunch is I'd lean toward `// ignore_for_file: lints` with those tradeoffs, but this hasn't been a big issue for my projects personally.

@jakemac53 any thoughts?

**Comment by pq** [comment]
> That would make most external builders just get this for free.

This seems like a pretty strong argument for pushing ahead with this idea.

Thanks for chiming in @jakemac53 and @natebosch!  Super useful.

**Comment by hacker1024** [comment]
For those coming across this issue now, as of Dart 2.15, the following syntax can be used to disable lints in a file:
```dart
ignore_for_file: type=lint
```

Case sensitivity and whitespace is ignored (`TYPE=LINT` and `type = lint` also work).

Is this documented anywhere? If not, it should be.

**Comment by srawlins** [comment]
Documentation is pending. https://github.com/dart-lang/site-www/issues/3576
