### ISSUE TITLE
jsonDecode FormatException when decode JSON string

### ISSUE THREAD

**Issue by phuhung273** [dart-lang/sdk#46959]
* Dart SDK Version: 2.13.4
* Windows 10

This code works:
```
jsonDecode("{\"username\":\"admin@gmail.com\",\"password\":\"admin123\"}");
```
But this
```
print(jsonString); // {\"username\":\"admin@gmail.com\",\"password\":\"admin123\"}
var json = jsonDecode(jsonString);
```

Results in:
```
I/flutter ( 6189): {\"username\":\"admin@gmail.com\",\"password\":\"admin123\"}
E/flutter ( 6189): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Unexpected character (at character 2)
E/flutter ( 6189): {\"username\":\"admin@gmail.com\",\"password\":\"admin123\"}
E/flutter ( 6189):  ^
E/flutter ( 6189): 
E/flutter ( 6189): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter ( 6189): #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:934:48)
E/flutter ( 6189): #2      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
E/flutter ( 6189): #3      JsonDecoder.convert (dart:convert/json.dart:506:36)
E/flutter ( 6189): #4      JsonCodec.decode (dart:convert/json.dart:157:41)
E/flutter ( 6189): #5      jsonDecode (dart:convert/json.dart:96:10)
```

I wonder what could possibly go wrong with my jsonString ?

**Comment by mnordine** [comment]
Why don't post the exact minimal reproducible case? This works:

```dart
import 'dart:convert';

void main() {
  final jsin = "{\"username\":\"admin@gmail.com\",\"password\":\"admin123\"}";
  final result = jsonDecode(json);
  print(result);
}
```

**Comment by phuhung273** [comment]
> Why don't post the exact minimal reproducible case? This works:
> 
> ```dart
> import 'dart:convert';
> 
> void main() {
>   final json = "{\"username\":\"admin@gmail.com\",\"password\":\"admin123\"}";
>   final result = jsonDecode(json);
>   print(result);
> }
> ```
> 
> output:
> 
> ```
> {username: admin@gmail.com, password: admin123}
> ```

I didn't post this case because I have tried and knew it works.
The problem is still there, but i have found a workaround.
Many thanks for your reply.

**Comment by mraleph** [comment]
Your server was most likely sending escaped string back (e.g. `{\"username\":\"admin@gmail.com\",\"password\":\"admin123\"}` rather than `{"username":"admin@gmail.com","password":"admin123"}`).
