### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by nazarpunk** [dart-lang/sdk#46953]
## Version information

- `IDEA IU-212.4746.92`
- `2.13.4`
- `IU-212.4746.92, JRE 11.0.11+9-b1504.13x64 JetBrains s.r.o., OS Mac OS X(x86_64) v11.5.2, screens 2560.0x1440.0`

**Comment by bernaferrari** [comment]
What is the issue?

**Comment by mraleph** [comment]
Not actionable without additional information.
