### ISSUE TITLE
DateTime is incorrectly created from max finite int by ms from epoch 

### ISSUE THREAD

**Issue by ChaserVasya** [dart-lang/sdk#46966]
dart --version:
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "windows_x64"

```
    final int _a = 8640000000000000;          // _maxMillisecondsSinceEpoch in DateTime source code. around 2^53
    final int _b = 8640000000000000 + 1;      // expected error
    final int _c = double.maxFinite.toInt();  // 2^63. expected error

    final a = DateTime.fromMillisecondsSinceEpoch(_a);    // passed
    final b = DateTime.fromMillisecondsSinceEpoch(_b);    // error
    final c = DateTime.fromMillisecondsSinceEpoch(_c);    // well of course an er... stop, passed? what ???  
```

Also, it would be nice to make `_maxMillisecondsSinceEpoch`  getter to improve clarity and readability. It is such a small request that I don`t know need I create a new issue or not.

**Comment by lrhn** [comment]
Does look like a bug. The `double.maxFinite.toInt()` on the VM is 2^63-1 (double.maxFininte is ~1e308, so we round down to the largest integer), and that is above the  limit for `fromMillisecondsSinceEpoch`. For some reason it's not caught.
A quick check suggests that values above `0x22d72e88eaa7ef` do not throw.
