### ISSUE TITLE
Higher order functions always autocomplete to anonymous closures

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#46979]
(This issue was originally filed for DartCode but was determined to be an analyzer issue: https://github.com/Dart-Code/Dart-Code/issues/3509)

## Seen behavior:
Given the following code:
```dart
String _commaJoin(String x, String y) => '$x, $y';

void foo() {
  final List<String> bar = <String>['Hello', 'world'];
  bar.re**CURSOR HERE**
}
```

If I select 'reduce()' from the suggestions it will autocomplete `bar.reduce((value, element) => null)` highlighting `null`.

## What I expected

What I actually wanted was `bar.reduce(_commaJoin)`.  It's a bit of a hassle to delete the closure.  In this case no autocomplete of the argument would be better, or a dropdown list of functions in the current context that match the needed signature like so:

```
┌─────────────┐
│ Lambda      │
│ _commaJoin  │
└─────────────┘

**Comment by scheglov** [comment]
This was done in e29057a973ceaa9189b496b28168ee8d08e48ccd.
However there is another related issue that we also want to fix: https://github.com/dart-lang/sdk/issues/55164
