### ISSUE TITLE
No language tests covering parser changes for constructor tearoff disambiguation tokens

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#46976]
I've just run https://dart-review.googlesource.com/c/sdk/+/210941 through trybots.  It updates the set of disambiguation tokens that control whether a `<` following an expression is interpreted as a relational operator or the beginning of a `<typeArguments>` selector (see https://github.com/dart-lang/language/issues/1806 for the motivation for this change).

This CL didn't trigger any language test failures; that must mean we don't have any language test coverage for the set of disambiguation tokens.

I would be happy to write a few language tests to cover this, but I believe @eernstg may be in the process of writing further language tests for this feature, and I don't want to unnecessarily duplicate effort.  Erik, do you want me to go ahead and add some language tests that cover the set of disambiguation tokens, or should I leave that to you?

**Comment by eernstg** [comment]
I'll take a look.

**Comment by stereotype441** [comment]
Fixed in 9076b6a76a5c4e7a933002c2e6b8e3d3f8fdf03f
