### ISSUE TITLE
[analyzer] Implement enhanced support for constant factory constructors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46985]
This is the analyzer specific issue for #46984, which has the details.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/209222

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/211162

**Comment by scheglov** [comment]
Tests in https://dart-review.googlesource.com/c/sdk/+/211140 pass now.
