### ISSUE TITLE
[CP][beta channel] 2a8f3d5 - Update dartdoc revision to 2.0.0

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#46983]
**commit(s) to merge**:   2a8f3d5fd52f9993054746f8e8199e579779edae

**merge instructions**: https://dart-review.googlesource.com/c/sdk/+/211085. (Patch had conflict in DEPS, CL resolves)

**What is the issue**: Dartdoc's [revision at beta HEAD](https://github.com/dart-lang/dartdoc/commit/c9621b92c738ec21a348cc2de032858276e9c774) contained a crash bug in the generic typedef support introduced when the new lookup code was [switched on by default](https://github.com/dart-lang/dartdoc/commit/e23ed44b7a25715838f051e201b17891275170dd). 

**What is the fix**: The proposed fix is to update the revision of dartdoc shipped with 2.14 to the current stable release of dartdoc, 2.0.0.

**Why cherrypick**: Having these bugs fixed would prevent reports of crash bugs in dartdoc that can be corrected by `pub global activate dartdoc`.

**Risk**: The cherry pick to update dartdoc can't be done to only incorporate the bugfixes as per usual cherry-pick policy.  It is therefore possible that changing revisions will introduce new problems of some sort.  To mitigate this I have built and tested a beta SDK with the compiled dartdoc to smoke test it by hand, testing it on dartdoc's "test package" and the SDK itself.

**Link to original  issue(s)**:  https://github.com/dart-lang/dartdoc/issues/2740 https://github.com/dart-lang/dartdoc/issues/2755

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by jcollins-g** [comment]
To elaborate on the risk, the most important downstream users of dartdoc use `pub global activate dartdoc` or other similar means to grab the latest stable dartdoc rather than the version compiled in the SDK, including pub.dev and Flutter.  So this is lower risk than it otherwise might be.

**Comment by athomas** [comment]
FYI, api.dart.dev docs are built with the dartdoc in the Dart SDK. Currently, they seem to work https://api.dart.dev/beta so perhaps the SDK isn't affected by this issue.

**Comment by athomas** [comment]
@devoncarew Why merge-to-stable? Do we want to patch 2.13.4 (currently on stable)? Or do we want this to into 2.14 (currently on beta)?

**Comment by devoncarew** [comment]
@athomas - yup, that was my thinking. This is essentially merge-to-stable for the stable that's not yet out :)

**Comment by devoncarew** [comment]
Approved! @athomas - note that this is now a cp to stable, not beta. Not sure if that will be an issue for you. If so, I'm sure @jcollins-g could provide a new cp.

**Comment by athomas** [comment]
Merged to stable in 3300f32fdc5432f40bc00f4179529cbd7449c93a (`2.14.2`).
