### ISSUE TITLE
[DDC] Implement enhanced support for constant factory constructors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46988]
This is the DDC specific issue for #46984, which has the details.

**Comment by sigmundch** [comment]
I don't believe there is anything to do on the backend side once the CFE is changed. @nshahan feel free to close this if/when that's the case

**Comment by eernstg** [comment]
Haha, too late, @nshahan got the cc already. ;-)

**Comment by nshahan** [comment]
Looks like the DDC implementation is working to me.
