### ISSUE TITLE
[VM] Implement enhanced support for constant factory constructors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46989]
This is the VM specific issue for #46984, which has the details.

**Comment by alexmarkov** [comment]
VM only cares about const attribute on _generative_ constructors, const attributes on factories are ignored. So, my understanding is that this language change doesn't need any changes in the VM.

The test in https://dart-review.googlesource.com/c/sdk/+/211140 passes on the VM.

**Comment by eernstg** [comment]
Sounds good! :+1:
