### ISSUE TITLE
[dart2js] Implement enhanced support for constant factory constructors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46987]
This is the dart2js specific issue for #46984, which has the details.

**Comment by sigmundch** [comment]
I don't believe there is anything to do on the backend side once the CFE is changed. @fishythefish feel free to close this if/when that's the case

**Comment by eernstg** [comment]
OK, sounds good!

**Comment by fishythefish** [comment]
Closing since I'm not aware of any required work on our end and I don't seem to have any problems running https://github.com/dart-lang/language/issues/1763, which I assume means the CFE fix must have landed already. If there are tests I should validate against, please let me know.

**Comment by eernstg** [comment]
Maybe check that it works for the test added in https://dart-review.googlesource.com/c/sdk/+/211140?
