### ISSUE TITLE
Failures on [dart2js] Enable default constructor tear-off lowering

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#46992]
There are new test failures on [[dart2js] Enable default constructor tear-off lowering](https://dart-review.googlesource.com/c/sdk/+/208924).

The tests
```
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t19 RuntimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t20 RuntimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A06_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/syntax_t02/02 Pass (expected CompileTimeError)
co19/LanguageFeatures/Constructor-tear-offs/syntax_t02/06 Pass (expected CompileTimeError)
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A02_t05 RuntimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t06 RuntimeError (expected Pass)
language/constructor/tear_off_test RuntimeError (expected Pass)
language/typedef/aliased_constructor_tear_off_test RuntimeError (expected Pass)
pkg/compiler/test/model/cfe_annotations_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-strong-linux-x64-chrome
dart2js-hostasserts-strong-linux-x64-d8
dart2js-hostasserts-weak-linux-x64-chrome
dart2js-hostasserts-weak-linux-x64-d8
unittest-asserts-no-sdk-linux
unittest-weak-asserts-no-sdk-linux
```

**Comment by rakudrama** [comment]
From https://dart-ci.firebaseapp.com/cl/208924/7:

_dart2js-hostasserts-strong-linux-x64-chrome_
_dart2js-hostasserts-weak-linux-x64-chrome_

**CompileTimeError -> Pass (expected CompileTimeError)**
- [ ] co19/LanguageFeatures/Constructor-tear-offs/syntax_t02/02
- [ ] co19/LanguageFeatures/Constructor-tear-offs/syntax_t02/06

**Crash -> RuntimeError (expected Pass)**
- [ ] co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A06_t01

_dart2js-hostasserts-strong-linux-x64-d8_
_dart2js-hostasserts-weak-linux-x64-d8_
**Crash -> RuntimeError (expected Pass)**
- [ ] language/constructor/tear_off_test
- [ ] language/typedef/aliased_constructor_tear_off_test

_dart2js-hostasserts-weak-linux-x64-chrome_
**Crash -> RuntimeError (expected Pass)**
- [ ] co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t19
- [ ] co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t20
- [ ] co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A02_t05
- [ ] co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t03
- [ ] co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t06

_unittest-asserts-no-sdk-linux_
_unittest-weak-asserts-no-sdk-linux_
**Pass -> RuntimeError (expected Pass)**
- [ ]  pkg/compiler/test/model/cfe_annotations_test

**Comment by johnniwinther** [comment]
`co19/LanguageFeatures/Constructor-tear-offs/syntax_t02/02` and `co19/LanguageFeatures/Constructor-tear-offs/syntax_t02/06` seem to be a CFE issue. I'll look into it.

**Comment by johnniwinther** [comment]
I've created https://dart-review.googlesource.com/c/sdk/+/211902 for the crashes in `language/typedef/aliased_constructor_tear_off_test` and `language/type_object/explicit_instantiated_type_literal_test`.

**Comment by rakudrama** [comment]
language/constructor/tear_off_test has been fixed, so all these failures have now been fixed.
