### ISSUE TITLE
[html] No Convenient Constructor for MetaElement

### ISSUE THREAD

**Issue by GZGavinZhao** [dart-lang/sdk#46991]
Dart version: Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"
Machine: M1 Mac

I've been working on an AngularDart package that adds `<meta>` tags to the HTML document. However, I found there's no way to construct a fleshed `MetaElement` directly. `MetaElement` itself only has an empty constructor. If I want to add a `MetaElement` with attributes, I have to do something similar to this:
```dart
var meta = Element.tag('meta')
  ..attributes = {
    // Blah, blah, blah...
    'content': content,
  };
document.head.append(meta);
```

May I ask if there is a reason for not having a convenient constructor for `MetaElement`, like `Element.meta(String name, ...)`, especially given that (at least in my opinion) `<meta>` is very common?

Thank you!

**Comment by Levi-Lesches** [comment]
Aren't all elements from `dart:html` like this?
