### ISSUE TITLE
crashes : dart::SimpleHashMap::Lookup(void*, unsigned int, bool) (hashmap.cc:22) 

### ISSUE THREAD

**Issue by Sunyandong-CS** [dart-lang/sdk#47004]
crashes on hashmap.cc:22 in Dart SDK, reported on different devices models with iOS 13,14
The crash stack is different but ends always on hashmap.cc SimpleHashMap::Lookup.

flutter doctor:
`[✓] Flutter (Channel unknown, 2.0.104-0.0.pre.1, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)`

[crash1.log](https://github.com/dart-lang/sdk/files/7060145/crash1.log)
[crash2.log](https://github.com/dart-lang/sdk/files/7060146/crash2.log)
[crash3.log](https://github.com/dart-lang/sdk/files/7060147/crash3.log)
[crash4.log](https://github.com/dart-lang/sdk/files/7060148/crash4.log)

**Comment by Sunyandong-CS** [comment]
@mraleph sorry for the late reply。
i got orgin crash log like that:
`Pthread id: 19426
Thread 13 name:  MTFlutterRoute.1.ui
 Thread 13 Crashed:
0   libsystem_kernel.dylib          0x00000001ba65d84c 0x1ba636000 + 161868
1   libsystem_pthread.dylib         0x00000001d6eba9e8 0x1d6eb0000 + 43496
2   libsystem_c.dylib               0x00000001974748f4 0x197401000 + 473332
3   Flutter                         0x000000010b11c2e8 0x10ac58000 + 4997864
4   Flutter                         0x000000010b1fc430 0x10ac58000 + 5915696
5   Flutter                         0x000000010b20ed60 0x10ac58000 + 5991776
6   Flutter                         0x000000010b2039f8 0x10ac58000 + 5945848
7   Flutter                         0x000000010b204f48 0x10ac58000 + 5951304
8   Flutter                         0x000000010b11348c 0x10ac58000 + 4961420
9   Flutter                         0x000000010af89f28 0x10ac58000 + 3350312
10  Flutter                         0x000000010af80d98 0x10ac58000 + 3313048
11  Flutter                         0x000000010af2d6c4 0x10ac58000 + 2971332
12  Flutter                         0x000000010af2f524 0x10ac58000 + 2979108
13  CoreFoundation                  0x000000018e7073e0 0x18e66c000 + 635872
14  CoreFoundation                  0x000000018e706fe4 0x18e66c000 + 634852
15  CoreFoundation                  0x000000018e7064c4 0x18e66c000 + 632004
16  CoreFoundation                  0x000000018e700850 0x18e66c000 + 608336
17  CoreFoundation                  0x000000018e6ffba0 0x18e66c000 + 605088
18  Flutter                         0x000000010af2f400 0x10ac58000 + 2978816
19  Flutter                         0x000000010af2ee04 0x10ac58000 + 2977284
20  libsystem_pthread.dylib         0x00000001d6eb9b3c 0x1d6eb0000 + 39740`

and i try to symbolize usingwith  -1 PCs in frames，got：

![image](https://user-images.githubusercontent.com/25921028/132341473-03666aa5-eacb-4a84-b938-58988a529e59.png)

it seems the  initial symbolization is correct .

**Comment by Sunyandong-CS** [comment]
@mraleph I sent you an email(me@mrale.ph) with a dsym file and crash log。maybe it can help locate the problem

**Comment by mraleph** [comment]
Thanks for the dSYM. The trick is to -1 return addresses on the stack to get a correct symbolization. Compare this (using normal addresses from the crash report): 

```
$ atos -o Flutter.dSYM/Contents/Resources/DWARF/Flutter -arch arm64 -l 0x10ac58000 0x000000010b11c2e8 0x000000010b1fc430 0x000000010b20ed60 0x000000010b2039f8 0x000000010b204f48
dart::SimpleHashMap::Lookup(void*, unsigned int, bool) (in Flutter) (hashmap.cc:22)
dart::ThreadPool::RunImpl(std::__1::unique_ptr<dart::ThreadPool::Task, std::__1::default_delete<dart::ThreadPool::Task> >) (in Flutter) (thread_pool.cc:91)
dart::Scavenger::Scavenge() (in Flutter) (scavenger.cc:1499)
dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::Heap::GCReason) (in Flutter) (heap.cc:471)
dart::Heap::NotifyIdle(long long) (in Flutter) (heap.cc:388)
```

to this (using adjusted addresses, with -1 adjustment applied)

```
$ atos -o Flutter.dSYM/Contents/Resources/DWARF/Flutter -arch arm64 -l 0x10ac58000 0x000000010b11c2e7 0x000000010b1fc42f 0x000000010b20ed5f 0x000000010b2039f7 0x000000010b204f47
dart::Assert::Fail(char const*, ...) (in Flutter) (assert.cc:44)
dart::ThreadPool::RunImpl(std::__1::unique_ptr<dart::ThreadPool::Task, std::__1::default_delete<dart::ThreadPool::Task> >) (in Flutter) (thread_pool.cc:94)
dart::Scavenger::Scavenge() (in Flutter) (scavenger.cc:1499)
dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::Heap::GCReason) (in Flutter) (heap.cc:470)
dart::Heap::NotifyIdle(long long) (in Flutter) (heap.cc:381)
```

The second one makes sense. As I have predicted in https://github.com/dart-lang/sdk/issues/47004#issuecomment-906464104 it is an assertion failure.

I think this assertion failure is in this line of code: 

```cpp
void ThreadPool::Worker::StartThread() {
  int result = OSThread::Start("DartWorker", &Worker::Main,
                               reinterpret_cast<uword>(this));
  if (result != 0) {
    FATAL1("Could not start worker thread: result = %d.", result);  // (!) here
  }
}
```

most likely you are hitting an OOM situation - the application might be using so much memory that you can't even start a thread.

**Comment by mraleph** [comment]
I will go ahead and close this because like with all OOM situations crash reports don't actually provide enough context for us to debug the issue.
