### ISSUE TITLE
flutter any from sdk and analyzer ^2.1.0

### ISSUE THREAD

**Issue by bordunosp** [dart-lang/sdk#47007]
Because analyzer >=2.0.0 depends on meta ^1.7.0 and every version of flutter from sdk depends on meta 1.3.0, analyzer >=2.0.0 is incompatible with flutter from sdk.
So, because app depends on both flutter any from sdk and analyzer ^2.1.0, version solving failed.
pub get failed (1; So, because app depends on both flutter any from sdk and analyzer ^2.1.0, version solving failed.)
Process finished with exit code 1

**Comment by jcollins-g** [comment]
In order to use analyzer 2.1.0, you will need to use a version of Flutter including https://github.com/flutter/flutter/commit/78e06e716ba56d84a6686dad2b4b7b9794434912.  I do not know if any stable version of Flutter contains this, so you may need to go to the dev channel.

Marking as closed.
