### ISSUE TITLE
No coverage information is generated for generator functions

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#47016]
STEPS TO REPRODUCE
1. `flutter create cov`
2. `cd cov`
3. Replace `lib/main.dart` with the following:
```dart
void baseline() {
  print('executed');
}

Iterable<int> count() sync* {
  print('executed');
  yield 0;
  print('not executed');
}
```
4. Replace `test/widget_test.dart` with the following:
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:cov/main.dart';

void main() {
  testWidgets('test', (WidgetTester tester) async {
    baseline();
    for (final int i in count()) {
      print(i);
      return;
    }
  });
}
```
5. Run `flutter test --coverage`
6. Run `lcov --list coverage/lcov.info`

EXPECTED RESULTS
You should see that some of the code is not covered. In particular, the line that says "not executed" is not covered.

ACTUAL RESULTS
Only two lines of the `main.dart` are considered coverable, the entire generator function is omitted from the results. As a result, the coverage numbers claim 100% coverage.

**Comment by liamappelbe** [comment]
Confirmed that sync generators have coverage, now that the CFE is attaching token positions to them.

**Comment by Hixie** [comment]
woot!
