### ISSUE TITLE
DartType != Entity

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#47032]
https://github.com/dart-lang/sdk/blob/06a471ce86a89a7d712232381a664e6469afaab8/pkg/compiler/lib/src/js_backend/type_reference.dart#L665-L670

Found by enabling the `unrelated_type_equality_checks` lint

info: Equality operator `==` invocation with references of unrelated types. (unrelated_type_equality_checks at [compiler] lib/src/js_backend/type_reference.dart:666)

`parent` is `DartType`, `type.element.typeDeclaration`is an `Entity`. These will never be equal.

**Comment by rakudrama** [comment]
Quibble: in legacy mode both operands could be `null`.

https://dart-review.googlesource.com/c/sdk/+/212343
