### ISSUE TITLE
[CP][beta channel] prevent kernel panics on Exynos 2100 SoC devices (e.g. S21 Samsung phone)

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#47043]
**commit(s) to merge**: abe2e7fd282c8ea7df83afb1b9ec41180724f008

**merge instructions**: clean merge

**What is the issue**: Sporadic kernel panics on Exynos 2100 SoC devices, e.g. Samsung S21 phones, see flutter/flutter#88261

**What is the fix**: We try to avoid certain pattern of the code that seems to cause some sort of CPU deadlock, so far were unable to track it down to a particular CPU errata. 

**Why cherrypick**: Flutter application would cause the whole phone to reboot, seems fairly strong of an impact.

**Risk**: Low.

**Link to original  issue(s)**:

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon

**Comment by mit-mit** [comment]
+1 for taking this

**Comment by timsneath** [comment]
Based on the prevalence of this phone type, this seems like an important CP on its surface.

**Comment by vsmenon** [comment]
lgtm given the crasher

Odd looking workaround!  Slava, do we have test coverage on this?  Do you want to wait on whether it rolls into flutter or internal (it may have given it landed a few days ago)?

**Comment by devoncarew** [comment]
Marking this as cp-approved.

**Comment by mraleph** [comment]
> Slava, do we have test coverage on this? 

Yes we do. 

> Do you want to wait on whether it rolls into flutter or internal (it may have given it landed a few days ago)?

The change is fairly mechanical, so I would be confident cherry-picking it just based on a normal coverage, it more or less just restores the pattern of code that was there before 8db0a975c14caadb8413b5e5762aad83b7369404.

**Comment by athomas** [comment]
Merged to beta in aa7d19d185583b221093ad7385cf91fca3e8779c (2.14.0-377.8.beta).
