### ISSUE TITLE
Analyzer false positive for unused `call` extension member.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#47041]
Example:
```dart
extension on Type {
  int call<T>() => 2;
}

void main() {
  print((int)<int>());
}
```
This code gives a warning about the `call` method not being used, even though it is.

**Comment by jcollins-g** [comment]
marked P1 for incorrect analysis warning on edge case without workaround (besides "don't have a call extension method").

**Comment by jcollins-g** [comment]
this does have a workaround; disabling the warning.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/212840
