### ISSUE TITLE
Parser doesn't support a<b>..c()

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#47045]
The parser doesn't support `a<b>..c()` need for the constructor tearoffs feature. Currently failures:
```
language/constructor/explicit_instantiation_syntax_test/16
language/constructor/explicit_instantiation_syntax_test/18
language/constructor/explicit_instantiation_syntax_test/28
language/constructor/explicit_instantiation_syntax_test/none
```

**Comment by bwilkerson** [comment]
@srawlins for status info

**Comment by jensjoha** [comment]
This is the failing part:

```
void g(_) {}
[...]
void test() {
[...]
g(C<int, int> .. toString()); 
[...]
}
```

So the test expects `C<int, int> .. toString()` to be one argument.
From https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md#grammar-ambiguities `..` is not mentioned (e.g. I would have expected it to be mentioned as a `continuationToken` if it was to be parsed as one argument).

Am I reading and/or understanding stuff wrong here?

/cc @eernstg

**Comment by eernstg** [comment]
The test needs updates, because the rules about which tokens are stopTokens/continuationTokens were changed (cf. https://github.com/dart-lang/language/pull/1823).

The test is updated in https://dart-review.googlesource.com/c/sdk/+/212587.

**Comment by jensjoha** [comment]
With the test changes landed none of the sub-tests fail. I'll close this issue.

**Comment by srawlins** [comment]
Did this not require a change to the parser?

**Comment by jensjoha** [comment]
> Did this not require a change to the parser?

No, the test was wrong and the parser was right.
(How the parser recovers is another story and there's a discussion about that in https://github.com/dart-lang/sdk/issues/47060)

**Comment by srawlins** [comment]
I see. Excellent!
