### ISSUE TITLE
[gardening] https_client_certificate_test failing

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#47052]
```
dartk-strong-linux-debug-ia32
flaky -> RuntimeError (expected Pass)
standalone/io/https_client_certificate_test
```

Log: https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-debug-ia32/dartk-strong-linux-debug-ia32/307/standalone/io/https_client_certificate_test

@askeksa-google's investigation yesterday.

> Trying to bisect failure on vm-kernel-nnbd-linux-debug-ia32, but it seems to also fail beyond where it worked on the CI.
>
> Then-tip of master edc835fe4ca62abb6d40962cabcb5d1e4a873dbd, last known good commit (on the CI) 4ae44ffebb3ddfc30c4ad5fcf1759463e3eef0a7, the commit before that 7731eea46896f1ac980801677bd0c7365fbdda38 and a somewhat older one eae58445e904440ff3fcb2a12d2905990d66bbf4. All failed locally with `gclient sync -D && ./tools/build.py -m debug -a ia32 runtime && python3 tools/test.py -n dartk-strong-linux-debug-ia32 standalone/io/https_client_certificate_test`
>
> Same error as in the CI log: https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-debug-ia32/dartk-strong-linux-debug-ia32/307/standalone/io/https_client_certificate_test

The test was already flaky, so no surprise it reproduces on older commits.

The test fails on all configurations except for analyzer: https://dart-ci.firebaseapp.com/current_results/#/filter=standalone/io/https_client_certificate_test

And that has been the case for a while https://github.com/dart-lang/sdk/issues/35462#issuecomment-448931563

It is only flaky on this configuration, and has been so since 2021-05-04

Approving failure on this configuration.

**Comment by vially** [comment]
I have submitted a change that should fix these tests on: https://dart-review.googlesource.com/c/sdk/+/296863

**Comment by dcharkes** [comment]
Thanks @vially !

The CI looks green, merging! 🚀

**Comment by dcharkes** [comment]
This test is only failing on TSAN now, which is most likely a different issue.
