### ISSUE TITLE
Add Collection.isFrozen

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#4705]
For a number of scenarios I'd like to be able to expose collections from a class, but the collections should not be modified external to the class.

To support scenarios such as this, I would really like to have an isFrozen (or isMutable, or isImmutable, or isReadOnly) property to indicate that the collection cannot be modified to allow a caller to check without risk of throwing an exception.

In addition, I'd really like a helper method similar to C#'s List.AsReadOnly  which returns a read-only wrapper for the collection, to make it easy to have an internally mutable collection, but expose an immutable version of it to external callers.

This all could be accomplished with subclasses of List&lt;&gt;, but from my APIs I'd really like to stick to exposing the generic collections and not 'FreezableList&lt;&gt;' or something.

**Comment by lrhn** [comment]
We now have `List.unmodifiable` and `Map.unmodifiable` constructors.

Adding it as an `asUnmodifiable()` method on the list or map itself would be too problematic with the numerous existing implementations of those interfaces which won't have the new method, so a constructor was chosen. It also has the advantage of being able to set or change the type parameters of the new list/map.
