### ISSUE TITLE
Add flag to allow for DDS to be disabled without disabling the CLI

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#47059]
Using a recent nightly build of the SDK, if I run:

```
~/Dev/Dart\ SDKs/nightly/bin/dart --enable-vm-service=0 run --disable-dart-dev test:test danny_test.dart
```

I get this crash:

```
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x0
version=2.15.0-edge.fb5526a2476771bab13b7526664dfc11feb7997c (be) (Mon Aug 30 14:48:55 2021 +0000) on "macos_x64"
pid=8320, thread=259, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=10f9abe40
  pc 0x00007fff2040d552 fp 0x00007ffee02b7550 _platform_strlen+0x12
  pc 0x000000010fab13e3 fp 0x00007ffee02b7580 dart::bin::File::UriToPath(char const*)+0x13
  pc 0x000000010fab1475 fp 0x00007ffee02b75b0 dart::bin::File::OpenUri(dart::bin::Namespace*, char const*, dart::bin::File::FileOpenMode)+0x15
  pc 0x000000010f985153 fp 0x00007ffee02b7640 dart::bin::DFE::TryReadKernelFile(char const*, unsigned char**, long*)+0x33
  pc 0x000000010f9850ae fp 0x00007ffee02b7680 dart::bin::DFE::ReadScript(char const*, unsigned char**, long*) const+0x2e
  pc 0x000000010f9863ac fp 0x00007ffee02b7750 dart::bin::RunMainIsolate(char const*, char const*, dart::bin::CommandLineOptions*)+0x4dc
  pc 0x000000010f985f54 fp 0x00007ffee02b77d0 dart::bin::RunMainIsolate(char const*, char const*, dart::bin::CommandLineOptions*)+0x84
  pc 0x000000010f986ea7 fp 0x00007ffee02b7900 dart::bin::main(int, char**)+0x607
  pc 0x000000010f987c99 fp 0x00007ffee02b7910 main+0x9
  pc 0x00007fff203e5f3d fp 0x00007ffee02b7920 start+0x1
-- End of DumpStackTrace
zsh: abort      ~/Dev/Dart\ SDKs/nightly/bin/dart --enable-vm-service=0 run --disable-dart-de
```

It doesn't happen if I don't include `--disable-dart-dev`. It's possible I'm putting it in the wrong place, but I don't think it should crash like this.

(if I move it to before `run` I get "Error when reading 'run': No such file or directory").

@bkonyi

**Comment by bkonyi** [comment]
`--disable-dart-dev` disables the CLI interface, so `dart run --disable-dart-dev` is completely invalid. In general, you should avoid passing `--disable-dart-dev` unless you're experiencing issues or really don't want DDS to start. If you pass `--disable-dart-dev`, you're effectively using the standalone VM without any access to any of the "new" commands (e.g., `run`, `test`, `pub`, etc).

The error for `dart --disable-dart-dev run` makes sense since the VM interprets `run` as a path and can't find a file named `run`, but we shouldn't crash for `dart run --disable-dart-dev` either.

**Comment by DanTup** [comment]
> In general, you should avoid passing `--disable-dart-dev` unless you're experiencing issues or really don't want DDS to start.

Disabling DDS was the goal here - it's code in the DAP that will spawn the process, and we're going to connect DDS from within the DAP process.

I'm not sure what the correct way to do this is then - I was hoping to run `dart run test:test test/foo.dart` but without DDS. Is that possible?

**Comment by DanTup** [comment]
Running the script directly like that bypassed the `package:test` runner which does the JSON output, etc. (which we need to integrate the test results into the IDE instead of just text output).

If we don't disable DDS, then my understanding is that we end up with an extra process (DAP -> DDS -> VM running the user/test script) whereas we were instead trying to connect DDS in the DAP process.

I'm not sure what the best option would be. We used to run `dart bin/snapshots/pub.snapshot run test test/foo.dart` but that wasn't a great solution (Dart-Code moved to `dart run test:test` but doesn't need to disable DDS since it can't run it itself).

What do you think is the best thing to do here?
