### ISSUE TITLE
[cfe] Adjust computation of flatten

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#47057]
This is the CFE specific issue for https://github.com/dart-lang/sdk/issues/47053, which has the details.

**Comment by eernstg** [comment]
@johnniwinther, am I right in guessing that you have been working on this?

**Comment by johnniwinther** [comment]
Dima and I have been working various parts of it. As I understand it we have update our flatten computation, right? Is it a spec change or just an implementation bug?

**Comment by eernstg** [comment]
We did not change the spec, but it looks like `flatten(T & Future<int>)` returns `T` or `T & Future<int>`, but it should return `int`.

(I just asked Dmitry about the fact that the type of `x` is reported as `T` rather than `T & Future<int>`, but assigning `x` to a variable of type `Future<int>` is allowed even though the type prints as `T`, so I assume that it must be represented as `T & Future<int>` internally.)

**Comment by johnniwinther** [comment]
The runtimes only look at the `T` part of `T & X`.

**Comment by eernstg** [comment]
(I'm always confused when a type named `X` isn't a type variable, and a type variable isn't named `X`, `Y` or something thereabouts ;-)

The runtimes shouldn't need to worry about this, because it's concerned with a static error (and even in the case where the program is allowed to run, this type isn't reified).

**Comment by stefantsov** [comment]
The issue is being worked on at https://dart-review.googlesource.com/c/sdk/+/212467.
