### ISSUE TITLE
RegExp quote function

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#4706]
There should be a way to quote a string so that it can be used in a RegExp to match exactly that string. This would mean escaping all RegExp-active characters such as periods and parentheses.

**Comment by nex3** [comment]
Can we make sure this gets into Dart 2.0? It's been a pretty glaring hole in our libraries for a long time.

**Comment by lrhn** [comment]
We're expect to add the feature. It's something we can add at any point, so it doesn't get priority over things that are *needed* for for Dart 2.0. 
On the other hand, it's likely to be a very simple function, so maybe we'll find time for it.

**Comment by Hixie** [comment]
A better name might be `escape`.

**Comment by natebosch** [comment]
Looks like this made it in https://api.dartlang.org/stable/2.0.0/dart-core/RegExp/escape.html
