### ISSUE TITLE
Dart Kernel Documentations

### ISSUE THREAD

**Issue by EhsanAramide** [dart-lang/sdk#47066]
Hi dart team!
I was exploring around underlying of the Dart VM and its mechanism so I wanted to read about kernel semantics, I found [its documentation](https://github.com/dart-lang/sdk/blob/master/pkg/kernel/doc/semantics/kernel-semantics.tex) but it is in tex I tried to compile it and view its contents in pdf format but I couldn't.
Does it possible for you to create a pdf format from tex file and share it with the public?

**Comment by mraleph** [comment]
I don't know how helpful the operation semantics doc is going to be, given that it has not been updated since 2017 and Kernel AST has changed in many ways. 

/cc @stefantsov @johnniwinther

**Comment by mraleph** [comment]
Not really. Binary format is documented here: https://github.com/dart-lang/sdk/blob/master/pkg/kernel/binary.md

The meaning of individual AST nodes is usually documented in the code https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/ast.dart

**Comment by EhsanAramide** [comment]
Thanks. (I already saw them before but it's ok)
Actually I read the runtime documentations (in runtime/docs) and as written in the documentations about compilation pipeline, first of all the `CFE` compiles source code to `Kernel binary` then the VM just handle the `Kernel binary`. Actually, I wanna documentations around these topics, I think as you said I should read the doc comments in these packages.

**Comment by EhsanAramide** [comment]
Thanks you about your comment

> doesn't reflect the actual state of Kernel.

As you said this isn't actual state of Kernel but the actual state of kernel and associated operations documentations can find under `kernel` and `CFE` packages Doc comments?

**Comment by stefantsov** [comment]
> As you said this isn't actual state of Kernel but the actual state of kernel and associated operations documentations can find under `kernel` and `CFE` packages Doc comments?

I believe https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/ast.dart reflects the current state of Kernel as an intermediate language.
