### ISSUE TITLE
[dart2js] Implement support for dynamic checks on parameters that are covariant-by-declaration due to inheritance

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#47076]
This is the dart2js specific issue for #47072, which has the details.

**Comment by devoncarew** [comment]
@sra (or @sigmundch) - can you provide a very rough estimate of how long this would take to do? We're trying to get breadbox estimates of the ~5 impl. tasks for this language change.

**Comment by sigmundch** [comment]
@rakudrama (our apologies for the spam @sra)

**Comment by rakudrama** [comment]
It would be useful to have a sketch of how the CFE will present the additional checks.

**Comment by devoncarew** [comment]
cc @johnniwinther

**Comment by johnniwinther** [comment]
I'm working on a CL that'll add explicit `AsExpression`s to the already generated forwarding stub. Some of the stubs are skipped by dart2js so we might need to fix that.
