### ISSUE TITLE
`Future` API docs is missing mentioning of async/await

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#47082]
The API docs for `Future` only illustrate using `.when`:
https://api.dart.dev/stable/2.13.4/dart-async/Future-class.html

We should make sure to also illustrate async/await.

**Comment by jacob314** [comment]
We should also link to existing high quality documentation on Future such as https://medium.com/dartlang/dart-asynchronous-programming-futures-96937f831137 or dart.dev such as 
https://dart.dev/codelabs/async-await. Might even make sense to include some of the content from those pages inline with the Future documentation.
Fyi @kwalrath
