### ISSUE TITLE
Unused method `BulkFixProcessor.producableFixesForError`?

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#47083]
Two things regarding this method:

- Is `producable` correctly misspelled, shouldn't it be `producible`?
- It seems `producableFixesForError` is not used at all.

https://github.com/dart-lang/sdk/blob/a6cc772b670034f355c626e28ce11d1555f97e24/pkg/analysis_server/lib/src/services/correction/bulk_fix_processor.dart#L239

**Comment by bwilkerson** [comment]
@DanTup I suspect that this was added for the original LSP support but is no longer needed. Can you confirm that?

**Comment by DanTup** [comment]
@bwilkerson correct - it should've been removed with the code that used it in 8f9cdb3b2f846a146ea29d41f1c7b79e9b280c4e.

Feel free to remove if convenient, otherwise I can do it tomororw. Thanks!

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/212293

**Comment by DanTup** [comment]
Thanks!
