### ISSUE TITLE
Optional Type assertion throwing error when passed null

### ISSUE THREAD

**Issue by steven-spiel** [dart-lang/sdk#47090]
When a class has a type `T`, and an instance of the class uses an optional type `T?`, the instance methods in the class should be able to distinguish if T is nullable or not.

In this instance, `handler` should be run if `T` is nullable or the `value` is not null. 

There should be a way for the analyzer to know that it's safe to pass the null value through. `T is T?` doesn't seem to do it.

[DartPad](https://dartpad.dev/?id=ddd7c78c9d579960ba28b81c28c02a71&null_safety=true)

![Screen Shot 2021-09-02 at 3 40 56 PM](https://user-images.githubusercontent.com/77690617/131906037-fa0dff90-aef6-4848-8c08-46fb2b96d9b1.png)

```dart
class Foo<T> {
  void doThing({
    required void Function(T event) handler,
    required T? value,
  }) {
    if (value != null || T is T?) {
      // Error is thrown here
      handler(value);
    }
  }
}
```

The error thrown is:

```
Error compiling to JavaScript:
Warning: Interpreting this as package URI, 'package:dartpad_sample/main.dart'.
lib/main.dart:7:15:
Error: The argument type 'T?' can't be assigned to the parameter type 'T' because 'T?' is nullable and 'T' isn't.
      handler(value);
              ^
Error: Compilation failed.
```

* Dart SDK Version `2.13.4`
* MacOSX `11.5.2`

**Comment by lrhn** [comment]
The phrase `T is T?` doesn't work and doesn't mean what you intend. It's almost invariably false, unless `T` is bound to a to a supertype of the `Type` class.
The test doesn't promote `value` to `T`, so you can't use it.

What you can do instead is:
```dart
  if (value != null) {
     handler(value);
  } else if (value is T) {
     handler(value);
  }
```
This first does a cheap check to see if value is null, and if not, it checks whether the value (which *is* `null`) is still a T, and if so, you can use it anyway. 
(I wish you could just write `if (value != null || value is T)`, but the "or" condition doesn't promote that well.)

Or you could just use `if (value is T)` as the only test. The `value != null` might be a little faster, and handles most of the values, but I can't be sure the compiler can't optimize `value is T` when value has type `T?`.

**Comment by steven-spiel** [comment]
Ah, excellent. I see that. Fantastic!
