### ISSUE TITLE
Update CHANGELOG when Constructor tearoffs goes to stable

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#47109]
The current constructor tearoffs CHANGELOG entry has verbiage indicating that the feature is in beta preview and not fully supported.  The links are also into the `accepted` directory, rather than the `2.15` directory.

This issue is to track removing the BETA PREVIEW verbiage, moving the feature spec to the 2.15 directory, and updating the links when the feature ships to stable.

**Comment by bernaferrari** [comment]
What is `constructor tearoffs` and how it is going to be enabled? It seems to me like putting Dart 2.15/2.16/etc (in the future) in pubspec is what enables it, but I might be wrong.

**Comment by eernstg** [comment]
@bernaferrari, the constructor-tearoffs feature bundle consists of several things. There's a [FAQ](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/faq.md) and a [feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).

**Comment by devoncarew** [comment]
Was this done (or, is there any work remaining to do here)?

**Comment by leafpetersen** [comment]
Yes, @munificent fixed this [here](https://dart-review.googlesource.com/c/sdk/+/218986).
