### ISSUE TITLE
Migration Tool Exception

### ISSUE THREAD

**Issue by viratshukla** [dart-lang/sdk#47100]
Exception details:

NoSuchMethodError: The getter 'library' was called on null.
Receiver: null
Tried calling: library at offset 438 in /Users/xx/xx/FlutterProjects/xx/xx/lib/core/database/tables/generic_table.dart (TextColumn)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:374:40)
#2      Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:100:9)
#3      EdgeBuilder.visitTypeName (package:nnbd_migration/src/edge_builder.dart:1793:40)
#4      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10068:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#6      EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2473:5)
#7      EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#8      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6942:50)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#10     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#11     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#12     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#13     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#16     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#17     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#18     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#19     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#20     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#21     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#22     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#23     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#24     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#25     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#26     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#27     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#28     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#29     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#30     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#31     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#32     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

**Comment by viratshukla** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.5.1 20G80 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
