### ISSUE TITLE
Flaky crash in the CFE: pkg/front_end/test/fasta/strong/agnostic/identical broke (Pass -> Fail)

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#47118]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8836847894007988417/+/u/test_results/new_test_failures__logs_

```
Crash when compiling file:///b/s/w/ir/pkg/front_end/testcases/agnostic/identical.dart,
 at character offset null:
 'dart:collection-patch/compact_hash.dart': Failed assertion: line 830 pos 12: '<optimized out>': is not true.
```

The test's history doesn't contain this error so I'm assuming it's a flake. The CL where I saw this has only unrelated status file changes.

**Comment by mraleph** [comment]
Given the timing I think this is highly likely related to @dcharkes changes to hashmaps.

**Comment by jensjoha** [comment]
https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/front-end-win-release-x64/15935/overview too.

**Comment by jensjoha** [comment]
and https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/front-end-mac-release-x64/16131/overview

**Comment by dcharkes** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/212586

* `line 830 pos 12` wrong assert in const set
* `line 251 pos 12` wrong assert in const map
