### ISSUE TITLE
[Analyzer] Add quick-fix for avoid_renaming_method_parameters

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#47126]
![image](https://user-images.githubusercontent.com/351125/132251223-5786248e-3d8f-46e3-8125-252b8ec79438.png)

Below is a related discussion in `dart-lang/lints`. The error message has been improved but there is no quick-fix yet for `avoid_renaming_method_parameters`. Brian Wilkerson aggress it should become a quick fix (this wasn't initially included in the 'we should consider it' list of quick fixes).

![image](https://user-images.githubusercontent.com/351125/132251253-1bb40ed9-89ab-4eba-a75a-4aaff320e30c.png)

**Comment by bernaferrari** [comment]
@asashour you like to fix my issues, so here it goes another one 😛

**Comment by asashour** [comment]
Hahaha, I am not sure of you see my other trials, but yours definitely are clear and seem attractive 😉

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/212980

**Comment by asashour** [comment]
A second try in https://dart-review.googlesource.com/c/sdk/+/248583

**Comment by bernaferrari** [comment]
Great job!!
