### ISSUE TITLE
[Analyzer] Add quick fixes for extensions

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#47127]
Coming from other languages, it is hard to initially understand Dart extensions and while the analyzer is good at complaining, it is bad at fixing.

```dart
extension String {} // Expected to find 'on'.

// Suggestion:
extension ExtendedString on String {}
```
The analyzer could add the `on` with a default name such as `Extended` + type (be careful with Map<...> or List<...>), `TemporaryName`, `ExtensionName` or `ReplaceMe`.

Second one, 

```dart
extension myextension on String {} // Name extensions using UpperCamelCase. 
```
IMO it should convert to `Myextension`, so the user sees what was wrong more intuitively than reading the message, and can fix again if it had a composed name.

**Comment by bwilkerson** [comment]
> The analyzer could add the `on` with a default name ...

I believe that this one should be fixed by adding the `on`. The extension isn't required to have a name so I don't think the fix should add one.

> IMO it should convert to `Myextension` ...

My concern with that suggestion is that there would then be no diagnostic letting the user know that they need to look at the name. Some users might assume that the fix would completely fix the issue and not look to see whether it had done so, especially since the diagnostic is removed. It seems like it might be better to leave it than to partially fix it while hiding the fact that the fix was incomplete.

**Comment by bwilkerson** [comment]
> Could there be a lint to add the `on`?

Yes, there could, and arguably should, be a fix to add the `on`. Sorry that that wasn't clear from my earlier response.

**Comment by srawlins** [comment]
Omitting the `on` results in a SyntaxError (plus follow-on errors). Adding the word `on` reduces the number of errors from 3 to 2, so we'd probably want to implement this where the user chooses a type. Can VS Code or IntelliJ provide autocomplete for that name? Eek.

(Improving the error recovery to produce an ideal of 1 error would be a separate issue.)

**Comment by bwilkerson** [comment]
> ... so we'd probably want to implement this where the user chooses a type.

I might have misunderstood something, but I thought the use case we're discussing is where the user has forgotten the `on` but has included the extended type:
```
extension String { ... }
```
In that case there isn't any need to prompt for the name.

**Comment by bernaferrari** [comment]
Yes, if `extension on String` is valid, I would love to see the `on` being added

**Comment by srawlins** [comment]
Oh I see. Very good, a much simpler fix.

**Comment by FMorschel** [comment]
I've opened this CL: https://dart-review.googlesource.com/c/sdk/+/392540
