### ISSUE TITLE
[analyzer] Remove unnecessary raw String from `protocol_generated`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#47146]
As a step to remove all unnecessary raw Strings from analyzer (at least).

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/212744

**Comment by srawlins** [comment]
Just a note: This is not a recommended lint rule. The PR is great, and obviously has 0 maintenance burden, but I don't see this being a high priority lint rule for the team.
