### ISSUE TITLE
Enabling heap verification requires setting too many flags

### ISSUE THREAD

**Issue by lexprfuncall** [dart-lang/sdk#4714]
We now have 3 flags which must be set to &quot;true&quot; to enable heap verification.

--verify_before_gc
--verify_after_gc
--verify_handles

There are few occasions where setting one of these flags is interesting.  Typically, one wants to enable all of the flags.  We should consolidate these three flags into one, or have a &quot;super flag&quot; that sest all the flags at once.

**Comment by iposva-google** [comment]
Stale.
