### ISSUE TITLE
`CREATE_MISSING_OVERRIDES` fix does nothing for abstract method

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#47141]
For the below case, there is a message `'m' must have a method body because 'A' isn't abstract`, with an option to fix by `Create 0 missing overrides`, which does nothing.

```dart
class A {
  void m();
}
```

**Comment by srawlins** [comment]
o_O That's certainly a strange option.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/215420
