### ISSUE TITLE
`CREATE_NO_SUCH_METHOD` is not adding the return type

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#47142]
For this case, there is a suggested fix to `Create 'noSuchMethod' method`
```dart
class A {
  void m();
}
```
which generates

```dart
class A {
  void m();

  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
```
which gives a message `The method noSuchMethod should have a return type but doesn't.`

1. I guess `CREATE_NO_SUCH_METHOD` should add the return type `dynamic` by default.
2. [lint] The method name in the mesage should be surrounded by apostrophes, so it becomes `The method 'noSuchMethod' ...`

**Comment by bwilkerson** [comment]
> I guess `CREATE_NO_SUCH_METHOD` should add the return type `dynamic` by default.

That diagnostic is coming from the `always_declare_return_types` lint, which not all users have enabled. We have discussed the possibility of using the set of enabled lints to control the behavior of fixes, and that might be the right thing to do here, but the declaration in `Object` doesn't contain a return type so packages that haven't enabled this lint might prefer to not add a return type.

**Comment by srawlins** [comment]
The quick fix still does not provide a return type today, but the declaration on Object now seems to explicitly specify `dynamic`:

```
$ git grep noSuchMethod sdk
...
sdk/lib/_internal/vm/lib/object_patch.dart:  dynamic noSuchMethod(Invocation invocation) {
...
sdk/lib/core/object.dart:  external dynamic noSuchMethod(Invocation invocation);
...
```
