### ISSUE TITLE
autofix for unnecessary_cast

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#47156]
It would be great if `dart fix` could fix `unnecessary_cast`.

In particular, consider an API like this:

```dart
class A { }
class B extends A { }

A foo() => B();

void main() {
  B b = foo() as B;
}
```

If I change the `foo` method to be more precise in its return type, I get an `unnecessary_cast` info in the `main` function:

```dart
class A { }
class B extends A { }

B foo() => B();

void main() {
  B b = foo() as B; // unnecessary_cast
}
```

It would be great if `dart fix` could just remove the cast for me.

https://github.com/flutter/flutter/pull/89451 is an example of an API change that triggered this quite a bit.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/212823
