### ISSUE TITLE
[cfe] Implement support for generic function instantiation of existing function objects in constants

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#47154]
This is the CFE specific issue for #47150, which has the details.

**Comment by eernstg** [comment]
There is actually still an issue with the CFE which is associated with potentially constant type expressions:

```dart
// A potentially constant type expression is supported for `as` (and `is`)
class A<X> {
  final List<X> x;
  const A(x): x = x is List<X> ? x : x as List<X>;
}

void m<X>(X x) {}

// Generic function instantiation to a type parameter is supported implicitly.
class B<X> {
  final void Function(X) f;
  const B(): f = m;
}

// But it is not supported explicitly.
class C<X> {
  final f;
  const C(): f = m<X>; // Error, but should be accepted.
}

void main() {
  const A<int>(<int>[1]); // OK.
  const b = B<String>(); // OK.
  print(b.f.runtimeType); // OK: 'String => void'.
  const c = C<String>(); // Compile-time error, but should be accepted.
  print(c.f.runtimeType); // (Never executed, so we don't know).
}
```

**Comment by johnniwinther** [comment]
Do we also support type variables in type literals as potentially constant, and if so, should we also support type variables as potentially constant type literal?

```Dart
class Class<T> {
  final field1;
  final field2;
  const Class() 
    : this.field1 = Class<T>, // Should this be allowed now?
      this.field2 = T; // Should this also be allowed now?
}
```

**Comment by eernstg** [comment]
Given that we do support the implicit generic instantiation (where a function object is used to initialize an instance variable), it seems inconsistent to rule out the explicit form. Here's the implicit one:

```dart
X id<X>(X x) => x;

class A<X> {
  final X Function(X) f;
  const A(): f = id;
}

void main() {
  const c = A<int>();
  print(c.f.runtimeType); // `(int) => int`.
}
```

The [new section](https://github.com/dart-lang/language/pull/1848/files) in the constructor-tearoffs specification says that `e<T>` is a potentially constant expression (as required for an expression in an initializer list) under some syntactic criteria (as usual, we don't want to check any static semantic properties during a 'potentially constant' check). So this allows for the type argument of the enclosing class to occur as the `T`.

When we encounter a `<constObjectExpression>`, we substitute actual arguments for formal parameters, and the resulting expression must be constant. Given that the actual type arguments to the constant object expression must be constant type expressions, I believe that this case is included.

However, if it gives rise to substantial refactorings or other implementation work then we'd need to reconsider.

**Comment by johnniwinther** [comment]
I wasn't thinking of the implicit/explicit instantiations (which your example is about) but of the _type literals_ that use type variables.

In fixing the compile-time error we emitted for the type variable occurring in an explicit instantiation, I just happened to touch the similar code for type variable type literals (and with that the newly supported generic type literals which might now contain type variables within them) and wondered whether we should support these in potentially context expressions.

**Comment by eernstg** [comment]
You're right, type literals are covered in the same way by the same part of the constructor-tearoffs specification, so `this.field1 = Class<T>` should be allowed. It doesn't cover a lone identifier, though, so `this.field2 = T` is not supported.

That's silly, because we could just use `typedef F<X> = X;` and make it `this.field2 = F<T>`.

I think this means that the consistent approach would be to allow both.

**Comment by johnniwinther** [comment]
@eernstg Will you ensure that `this.field2 = T` will be spec'ed to be supported as part of the constructor-tearoff feature?

**Comment by eernstg** [comment]
Yes, that would have happened already several days ago except for that influenza (or whatever it was).

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/pull/1860.
