### ISSUE TITLE
Analyzer Feedback from IntelliJ Dart code completion time over 2000 ms 

### ISSUE THREAD

**Issue by almpazel** [dart-lang/sdk#47163]
## Version information

- `IDEA IC-202.8194.7`
- `2.14.0-377.8.beta`
- `IC-202.8194.7, JRE 11.0.9+11-b944.49x64 JetBrains s.r.o., OS Mac OS X(x86_64) v10.16, screens 1440x900  Retina`

**Comment by scheglov** [comment]
Not actionable.

**Comment by xshiwei** [comment]
![screenshot-20210926-151403](https://user-images.githubusercontent.com/25923053/134797719-21dd4a2b-4d80-4fb4-89fb-0e5b4a3d9f73.png)

**Comment by xshiwei** [comment]
I also have this problem. On my Android studio, I feel that the code completion time is too long every time. Sometimes I even need to wait for more than 3 seconds. My computer is apple m1. When I change the dart sdk to When it becomes the arm version, the speed will be greatly improved. But the button to run is not displayed anymore. So I have to use VsCode, but I still hope that this problem can be solved. thanks

**Comment by xshiwei** [comment]
![image](https://user-images.githubusercontent.com/25923053/134797889-0431c868-1ce4-45b9-a114-4978f138b910.png)
Here are some of my configurations

**Comment by xshiwei** [comment]
@scheglov

**Comment by scheglov** [comment]
OK, it looks as https://github.com/flutter/flutter-intellij/issues/5761
Probably worth tracking there, as having more content.
