### ISSUE TITLE
Spurious analyzer error in some non-null safe subclasses of a null safe class

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#47162]
The smallest reproduction case I've been able to find so far is:

```dart
// A library migrated to null safety, foo.dart
class C {
  T? something<T>(covariant Object o, [T? Function()? callback = _default]) =>
      null;
}

Null _default() => null;
```

```dart
// @dart=2.11

import 'foo.dart';

class Bad extends C {}
//    ^^^ Error is here
```

The error is:

> `'C.something' ('T Function<T>(Object, [T Function()])')` isn't a valid concrete implementation of `'C.something' ('T Function<T>(Object, [T Function()])')`. • invalid_implementation_override

The CFE accepts this code.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/212866
