### ISSUE TITLE
dart compile exe doesn't work for 32-bit SDK

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#47177]
If I download the 32-bit Linux Dart SDK (version 2.14.1) and run `dart compile exe`, it prints:

```
Could not find /tmp/dart-sdk/bin/snapshots/gen_kernel.dart.snapshot. Have you built the full Dart SDK?
```

I haven't tested on Windows or Mac OS, but I've verified that this doesn't happen on the 64-bit SDK.

**Comment by alexmarkov** [comment]
Currently, AOT compilation is not supported when targeting 32-bit Intel (only x64, 32-bit ARM and 64-bit ARM architectures are supported). We should probably print a better error message when `dart compile exe` or `dart compile aot-snapshot` are used on IA32.

**Comment by nex3** [comment]
To be clear, `dart compile aot-snapshot` *does* work.

**Comment by alexmarkov** [comment]
@nex3 Are you sure you're using a 32-bit SDK for `dart compile aot-snapshot`?

On a fresh checkout:
```
$ tools/build.py -a ia32 -m release create_sdk

$ out/ReleaseIA32/dart-sdk/bin/dart compile exe test_hello.dart 
Could not find /...skipped.../out/ReleaseIA32/dart-sdk/bin/snapshots/gen_kernel.dart.snapshot. Have you built the full Dart SDK?

$ out/ReleaseIA32/dart-sdk/bin/dart compile aot-snapshot test_hello.dart 
Could not find /...skipped.../out/ReleaseIA32/dart-sdk/bin/snapshots/gen_kernel.dart.snapshot. Have you built the full Dart SDK?

$ out/ReleaseIA32/dart-sdk/bin/dart --version
Dart SDK version: 2.15.0-edge.8c9dcc92f594e8e4f7238aa6f41257e320f95454 (be) (Mon Sep 13 18:02:09 2021 +0000) on "linux_ia32"
```

**Comment by nex3** [comment]
You're right, I was testing against the wrong SDK.

**Comment by nex3** [comment]
This is still an issue. See for example [this build](https://github.com/sass/dart-sass/actions/runs/7351959267/job/20016222507), where the failure message is still

```
Could not find /system/lib/dart/bin/snapshots/gen_kernel_aot.dart.snapshot. Have you built the full Dart SDK?
```

**Comment by bkonyi** [comment]
Fix for the incorrect error message is up for review [here](https://dart-review.googlesource.com/c/sdk/+/344240). `dart compile exe` and `dart compile aot-snapshot` will both continue to be unsupported for the foreseeable future as we don't have AOT support for IA32.
