### ISSUE TITLE
useResult analysis reports references in dartdoc.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#47181]
Take this example:

```dart
import 'package:meta/meta.dart';

@useResult
int get f => 1;

/// I love [f].
int g = 1;
```

Analyzer reports:

> a.dart:6:13 • 'f' should be used. Try using the result by invoking a member, passing it to a function, or returning it from this function. • unused_result

**Comment by srawlins** [comment]
cc @pq

**Comment by pq** [comment]
😬  That's obviously not good.  Thanks for the report!

**Comment by blaugold** [comment]
Looks like this did not get fixed completely. The analyzer still reports an error for members of a class:

```dart
import 'package:meta/meta.dart';

class A {
  @useResult
  bool b() => true;
}

/// [A.b].
const a = 'a';
```

```
info - foo.dart:8:8 - The value of 'b' should be used. Try using the result by invoking a member, passing it to a function, or returning it from this function. - unused_result
```

**Comment by pq** [comment]
Sure enough, I missed the prefixed identifier case.  Looking now.

Thanks for the catch, @blaugold.  And sorry for the hassle!
