### ISSUE TITLE
Static Analyser on Inherited Generic Types

### ISSUE THREAD

**Issue by raveesh-me** [dart-lang/sdk#47193]
I am in a situation which feels like a defect with the static analysis.

![image](https://user-images.githubusercontent.com/15698263/132945371-5d25e417-8034-4ded-a2e2-c5192e772949.png)

This gives me an undefined method error: https://dart.dev/tools/diagnostic-messages#undefined_method 

I have clearly mentioned that T extends the required interface that has a fromJson function.
![image](https://user-images.githubusercontent.com/15698263/132945411-e97b648c-8176-4520-b928-3dceb8233983.png)

Also, typecasting it twice might fix things...
```
                return (T as JsonCompatibleModel).fromJson(_snapshotData) as T?;

```
![image](https://user-images.githubusercontent.com/15698263/132945433-afa1da46-cf2c-4cc1-9240-6c42e35c5d8b.png)

I am using:
```
Ubuntu 20.04 latest updates
➜  cloud-ktchn-pos-flutter-app git:(refacttors/rav-sep9) ✗ flutter --version
Flutter 2.5.0 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (3 days ago) • 2021-09-07
23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0
```

Flutter doctor:
```
➜  cloud-ktchn-pos-flutter-app git:(refacttors/rav-sep9) ✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS
    5.4.0-84-lowlatency, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android
    SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.0)
[✓] Connected device (1 available)

• No issues found!
```

Having to make double typecasts for something compiler has the opportunity to pick up just feels wierd

**Comment by lrhn** [comment]
This has nothing to do with type inference, you simply cannot call static methods on type variables.
Dart static method invocations are resolved at compile-time. A call like `T.fromJson` cannot do that, so it's not a proper static call, it is not allowed and therefore doesn't work.

You need to pass the actual `fromJson` *function* as a parameter, along with the type, in order for this to be able to work.
