### ISSUE TITLE
Breakpoints in dart: libraries are not hit

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#47204]
This came up at https://github.com/Dart-Code/Dart-Code/issues/3551.

Given the following code:

```dart
main() {
  print('test');
}
```

There are two possible ways in VS Code to try and set a breakpoint _inside_ the `print` function:

1. Invoke the analysis servers Go-to-Definition on `print` and then add the breakpoint in the file that opens
  For a Dart app, the file that opens is `{dart-sdk-path}/lib/core/print.dart`
  For a Flutter app, the file that opens is `{flutter-sdk-path}/bin/cache/pkg/sky_engine/lib/core/print.dart`
2. Add a breakpoint on the _call_ to `print`, run the app, then Step Into `print` and add the breakpoint in the file that opens
  For both Dart and Flutter apps, the file is downloaded from the VM and has the uri `dart:core/print.dart`

Setting the breakpoints either of these ways does _not_ cause the debugger to pause when next calling `print`. Ideally, both would, since both of them are reasonable ways for the user to get to the code and assume this would work (and both should generally match the version of code that is running in the VM as I understand it).

Here's an example showing the script URI returned from the VM:

```js
"script": {
	"type": "@Script",
	"fixedId": true,
	"id": "libraries/@0150898/scripts/dart%3Acore%2Fprint.dart/0",
	"uri": "dart:core/print.dart", // <------------------------------ see here
	"_kind": "kernel"
},
```

And here's an example of a call to `setBreakpointWithScriptUri` with the same URI that fails to set a working breakpoint:

```js
{
	"id": "10",
	"jsonrpc": "2.0",
	"method": "addBreakpointWithScriptUri",
	"params": {
		"isolateId": "isolates/996847484333475",
		"scriptUri": "file:///Users/danny/Dev/Dart%20SDKs/v2.13.4/lib/core/print.dart",
		"line": 9
	}
}
```

@bleroux found that for the Flutter case, and when you set breakpoints after stepping into the code, replacing `"dart:"` with `"/"` in the `addBreakpointWithScriptUri` will work for Flutter apps (I think this forces it to partially-match the URI, although I'm not certain and not sure why). It still only fixes a subset of the problem though (and it may break things if this is fixed in the VM for users that upgrade). Implementing the workaround in the SDK DAP might be more reasonable (with a test that would fail if the issue is fixed in a way that breaks the workaround), although it would still be nice to have a solution that works for the other cases (Dart CLI, and if the user Go-to-Definition'd into the SDK library).

@bkonyi

**Comment by rmacnak-google** [comment]
This is probably related to the debuggable bit on libraries, which unfortunately exists. It controls whether breakpoints or stepping will stop in the library, and it is off by default for `dart:` libraries.

https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#setlibrarydebuggable

**Comment by DanTup** [comment]
As far as I can see, we're setting that as expected:

```js
		"libraries": [
			{
				"type": "@Library",
				"fixedId": true,
				"id": "libraries/@0150898",
				"name": "dart.core",
				"uri": "dart:core"
			},
```

```
{
	"id": "12",
	"jsonrpc": "2.0",
	"method": "setLibraryDebuggable",
	"params": {
		"isolateId": "isolates/340950901623355",
		"libraryId": "libraries/@0150898",
		"isDebuggable": true
	}
}
```

I think we currently send it for _all_ libraries always, because the default changed in the past and caused issues, so now we're quite explicit about it.

Here's a full log:

[full_debug_log.txt](https://github.com/dart-lang/sdk/files/7161468/full_debug_log.txt)

Line 34 calls `setLibraryDebuggable` for `dart:core`
Line 28 + 29 set the breakpoints (one using the analysis servers path, and the other using the URI we get while debugging)

I'll do some testing to ensure the order of the above doesn't matter, but I'm fairly sure it works fine for non-SDK libraries this way (I didn't realise until just now we were sending them this way around!).

**Comment by DanTup** [comment]
The weird order was because VS Code sent us the breakpoints while we were starting up. I temporarily delayed setting the breakpoints for testing, but the behaviour is the same. Here's an updated log:

[Dart-Code-Log-2021-08-02 12-36-25.txt](https://github.com/dart-lang/sdk/files/7161532/Dart-Code-Log-2021-08-02.12-36-25.txt)

Line 121 calls setLibraryDebuggable for dart:core (response is line 123)
Line 162+163 set the breakpoints (line 165+167 are the responses)
Line 171 resume the app (it was started paused to avoid race conditions setting breakpoints)
Line 174 the isolate exits, having never hit the breakpoint

**Comment by bleroux** [comment]
I think there are several issues to tackle there.

The first one is that [addBreakpointWithScriptUri](https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#addbreakpointwithscripturi) documentation doesn't explain what is expected  for ```scriptUri``` parameter.

Digging in the code and reading informative @bkonyi comments on [this flutter issue](https://github.com/flutter/flutter/issues/27189), we can find what works or not :
- ```dart:core/print.dart``` : **failed**  (as reported by @DanTup)
- ```org-dartlang-sdk:///sdk/lib/core/print.dart``` : **passed**  (from @bkonyi comments)
- ```/core/print.dart``` : **passed** (found reading [this](https://github.com/dart-lang/sdk/blob/main/runtime/vm/object.cc#L12849))

To get those results I wrote the following sdk test :

```dart
const int LINE_A = 10;
...
var printUri = 'dart:core/print.dart';

var tests = <IsolateTest>[
  hasStoppedAtBreakpoint,
  // Dart libraries are not debuggable by default
  markDartColonLibrariesDebuggable,
  // Add breakpoint in core lib
  (Isolate isolate) async {
    var bpt = await isolate.addBreakpointByScriptUri(printUri, LINE_A);
    expect(bpt is Breakpoint, isTrue);
  },
  resumeIsolate,
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_A),
  resumeIsolate,
];
```

I have fun with this and would like to contribute. 
@DanTup  @rmacnak-google @bkonyi Should I create several issues so we can make progress step by step ?
If yes, first one would be on ```addBreakpointWithScriptUri``` documentation, as it will define what is expected.

**Comment by DanTup** [comment]
> If yes, first one would be on `addBreakpointWithScriptUri` documentation, as it will define what is expected.

I think it would definitely be good to clearly document this. Issues have come up in the past where sometimes breakpoints would only be hit if using `file:///` and sometimes only if `package:foo/` depending on how the files were loaded, and that led to IDEs sending the same breakpoint in multiple formats to try and get one that worked. Unfortunately that caused other complications in VS Code (because we had to try and manage mappings of 1-to-n breakpoints), but changes were made in the VM to handle either.

I think the ideal solution would allow the editor to send any of `file:///` URIs _or_ the `package:`/`dart:` URIs, because generally the editor only knows file paths when not in a debug session, and only VM URIs when stepping through code. If the VM can't map these URIs, I'm not sure how an editor could (plus, anything done in the editor needs duplicating in them all, but anything in the VM is all just in the SDK).

Eg., it would be great if all of these worked:

- `file:///home/danny/project_foo/lib/foo.dart`
- `package:project_foo/foo.dart`
- `file:///home/danny/dart-sdk/lib/core/print.dart`
- `file:///home/danny/flutter/bin/cache/pkg/sky_engine/lib/core/print.dart` (I don't really understand why this file exists since it seems duplicated in `file:///home/danny/flutter/bin/cache/dart-sdk/lib/core/print.dart`, but the former is where the analysis server jumps to when using go-to-definition in a Flutter app)
- `dart:core/print.dart`

Slightly related is https://github.com/dart-lang/sdk/issues/46631 which describes a way for the editor to change between these paths through the VM Service. Although for requests like `addBreakpointWithScriptUri` I don't think it makes sense for the editor to ask the VM to translate them to then immediately send them back - it seems like internally `addBreakpointWithScriptUri` should be able to use the same mapping to just do the right thing.

(I don't know how feasible this is though, I don't know much about the internals - @rmacnak-google @bkonyi likely have more informed opinions)

**Comment by bleroux** [comment]
As a first step, I submitted a PR to fix a bug in scripts lookup : https://dart-review.googlesource.com/c/sdk/+/213766

@bkonyi @rmacnak-google Thank you to review it.
