### ISSUE TITLE
No error in analyzer constant generic tear-off with non constant type parameter

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#47213]
The following test produces an expected error in CFE but has no issues in analyzer
```dart
void f<X>(X x) {}

void main() {
  void g1<Y>() {
    const c1 = f<Y>; // No error in analyzer here
//             ^^^^
// [analyzer] unspecified
// [cfe] unspecified
  }
}
```
Tested on edge version of SDK on Linux and on `Dart SDK version: 2.15.0-101.0.dev (dev) (Mon Sep 13 12:09:30 2021 -0700) on "windows_x64" `

**Comment by scheglov** [comment]
@srawlins
