### ISSUE TITLE
No error in analyzer when we try to instantiate 'call' method of non-generic function object

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#47211]
The following test fails in analyzer
```dart
T foo1<T>(T value) => value;

typedef T Foo<T>(T value);

main() {
  Foo funcValue1 = foo1;
  funcValue1.call<int>; // No error in analyzer here
//               ^
// [analyzer] unspecified
// [cfe] unspecified
}
```
There is an expected error in CFE `The static type of the explicit instantiation operand must be a generic function type but is 'dynamic Function(dynamic)'.` but no error in CFE

Tested on the edge version of the SDK

**Comment by scheglov** [comment]
@srawlins

**Comment by srawlins** [comment]
Fixed with https://dart-review.googlesource.com/c/sdk/+/213539

**Comment by srawlins** [comment]
Oops, not yet.
