### ISSUE TITLE
Nullcheck duplication.

### ISSUE THREAD

**Issue by Hu1buerger** [dart-lang/sdk#47236]
On dart version  2.13.4.

Suppose the following code.

```dart
  UserCredential? userCreds;

  User? get currentUser {
    if(userCreds != null){
      return userCreds!.user;
    }
    return FirebaseAuth.instance.currentUser;
  }
```

I am arguing that the null check in `return userCreds!.user` is unnecessary. 
The code already guarantees that userCreds is not null in that case.

Therefore I propose to add this context-aware linting and compiling to fluter so that the above code would be of this or similar nature.

 ```dart
  UserCredential? userCreds;

  User? get currentUser {
    if(userCreds != null){
      return userCreds.user;
    }
    return FirebaseAuth.instance.currentUser;
  }
```

This should be part of dart to reduce code written.

EDIT: I believe this is part of kotlin too. 
EDIT 2: I would see the issue of needing the null check again if dart would be multithreaded

**Comment by mraleph** [comment]
This is discussed in the guide: https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields

In Dart a field can be overriden by a getter which returns unstable value, e.g. first time not-`null`, the second time `null`. This means you can't _soundly_ promote a "field access" after a check.

Dart language team is aware of the problem, but has not decided to a single solution yet. See https://github.com/dart-lang/language/labels/field-promotion
