### ISSUE TITLE
PropertyElementResolver resolveSimpleIdentifier throws unhelpful issues when the token is unresolvable

### ISSUE THREAD

**Issue by skoga** [dart-lang/sdk#47241]
SDK version: Dart SDK version: 2.15.396800962-edge+google3-v2 (google3) (google3) on "linux_x64"

file: https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/dart/resolver/property_element_resolver.dart#L203

node.scopeLookupResult is marked as being non-nullable, but if you look up the property:

https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/dart/ast/ast.dart#L8920

It is marked as being nullable.

This results in really unhelpful analyzer blow-ups of the form:

Action threw an exception: Null check operator used on a null value
#0      PropertyElementResolver.resolveSimpleIdentifier (package:analyzer/src/dart/resolver/property_element_resolver.dart:206)
#1      SimpleIdentifierResolver._resolve1 (package:analyzer/src/dart/resolver/simple_identifier_resolver.dart:169)
#2      SimpleIdentifierResolver.resolve (package:analyzer/src/dart/resolver/simple_identifier_resolver.dart:41)
#3      ResolverVisitor.visitSimpleIdentifier (package:analyzer/src/generated/resolver.dart:1854)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8995)
#5      ResolverVisitor.visitFunctionExpressionInvocation (package:analyzer/src/generated/resolver.dart:1467)
#6      FunctionExpressionInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5014)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7590)
#8      ResolverVisitor.visitCascadeExpression (package:analyzer/src/generated/resolver.dart:1083)
#9      CascadeExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1214)
#10     AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:99)
#11     _VariableInferenceNode._resolveInitializer (package:analyzer/src/summary2/top_level_inference.dart:513)
#12     _VariableInferenceNode.evaluate (package:analyzer/src/summary2/top_level_inference.dart:463)
#13     _InferenceWalker.evaluate (package:analyzer/src/summary2/top_level_inference.dart:300)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:100)
#15     DependencyWalker.walk (package:analyzer/src/summary/link.dart:119)
#16     _InferenceWalker.walkNodes (package:analyzer/src/summary2/top_level_inference.dart:317)
#17     _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:350)
#18     TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:120)
#19     Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:181)
#20     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:97)
#21     Linker.link (package:analyzer/src/summary2/link.dart:78)
#22     link (package:analyzer/src/summary2/link.dart:37)
#23     AnalyzeAction._computeLinkedLibraries.<anonymous closure> (package:dart.build_defs.action.analyzer.g3_analyzer_cli/analyze_action.dart:169)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32)
#25     AnalyzeAction._computeLinkedLibraries (package:dart.build_defs.action.analyzer.g3_analyzer_cli/analyze_action.dart:104)
#26     AnalyzeAction.analyze.<anonymous closure>.<anonymous closure> (package:dart.build_defs.action.analyzer.g3_analyzer_cli/analyze_action.dart:53)
#27     AnalyzeAction.analyze.<anonymous closure>.<anonymous closure> (package:dart.build_defs.action.analyzer.g3_analyzer_cli/analyze_action.dart:51)
#28     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50)
#29     AnalyzeAction.analyze.<anonymous closure> (package:dart.build_defs.action.analyzer.g3_analyzer_cli/analyze_action.dart:51)
<asynchronous suspension>
#30     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50)
<asynchronous suspension>
#31     AnalyzeAction.analyze (package:dart.build_defs.action.analyzer.g3_analyzer_cli/analyze_action.dart:37)
<asynchronous suspension>
#32     AnalyzeWorker.analyze (package:dart.build_defs.action.analyzer.g3_analyzer_cli/analyze_worker.dart:35)
<asynchronous suspension>
#33     LibraryRunner.run.<anonymous closure> (package:dart.build_defs.tool.common.snapshot_runner/library_runner.dart:64)
<asynchronous suspension>
#34     LibraryRunner.run (package:dart.build_defs.tool.common.snapshot_runner/library_runner.dart:70)
<asynchronous suspension>
#35     main (google3:///dart/build_defs/action/analyzer/bin/main.dart:8)
<asynchronous suspension>

Ideally, you'd be able to create a user-readable error that states that the reference associated with node.token wasn't found.

**Comment by scheglov** [comment]
Can be reproduced with `var v = 0..isEven() = 1;`

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/213843
