### ISSUE TITLE
TSAN lock-order inversion introduced by shutdown change

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#47255]
[This commit](https://dart-review.googlesource.com/c/sdk/+/213561) (identified by local bisection) introduced a TSAN lock-oder-inversion, as seen in [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8835779319093894049/+/u/vm_tests_shard_2/task_stdout_stderr:_vm_tests_shard_2). The runner identifies the crash as an infra failure, even though it seems to be just the TSAN violation causing the crash.

**Comment by a-siva** [comment]
Reverted https://dart-review.googlesource.com/c/sdk/+/213561
