### ISSUE TITLE
VM quits when calling a service extension if a completer is awaited

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#47279]
I hit this while trying to write a test for something. I register a service extension in an isolate and then wanted to wait until it was called:

```dart
  final completer = Completer();
  print('Registering service!');
  registerExtension(extensionName, (method, params) async {
    print('Service was called!');
    completer.complete();
    return ServiceExtensionResponse.result(jsonEncode(params));
  });
  print('Waiting for service to be called!');
  await completer.future;

  print('Will exit soon...');
  await Future.delayed(const Duration(seconds: 30));
```

When the service extension is called, the process seems to quit and the calling code gets "Service disappeared" from the vm_service package.

Commenting out the call to `completer.complete()` does _not_ fix it. However commenting out `await completer.future` does. It's not clear to me what's going on here (and whether it's a bug, or expected).

A full test script that can be run that spawns both parts (the code above in one process, and code that connects to it and calls its service extension) is here:

https://gist.github.com/DanTup/6a49f286f3d0b92d1da61ecc6628c5be

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by rmacnak-google** [comment]
WAI. The standalone VM exits an isolate when it has an empty event queue and no open receive ports. Receive ports are opened internally by dart:io when there are outstanding timers or file/socket/pipe operations. The existence of a Completer that has not been completed does not prevent isolate exit. The registration of a service extension does not prevent isolate exit (we generally expect the VM service and extensions to not significantly change the program's behavior and mostly just record and report things; a program should do the same thing when the VM service is disabled in product mode).

It is possible to keep the isolate alive to wait for a call to the service extension by opening a receive port when the extension is registered and closing that port after the extension is called, but if the program's behavior depends on input from an service extension call, that input probably should be provided by normal arguments instead.

**Comment by DanTup** [comment]
This makes sense to me now, thanks!
