### ISSUE TITLE
Incorrect stream behaviour in test mode

### ISSUE THREAD

**Issue by ChaserVasya** [dart-lang/sdk#47275]
I usually test simple code in test mode, as a dartpad.dev alternative. Now it is the difference in behaviour.

Code snippet:
```
void main() {
  genInt().listen((e) => print(e), onDone: () => print('done'));
}

Stream<int> genInt() async* {
  yield 1;
}
```
Output. There is no printed '1': 
```
Connecting to VM Service at http://127.0.0.1:56982/uMCbFXFZTvU=/ws
No tests were found.
Exited (1)
```
But in dartpad.dev it is:
![image](https://user-images.githubusercontent.com/74578917/134473236-4e66b8b2-5024-48b3-bae8-5aa6a2107f45.png)

What I expected: output in test mode should contain '1'.

dart --version:
`Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "windows_x64"`

**Comment by lrhn** [comment]
Not sure what "test mode" is. Is it something provided by your IDE? (If so, which IDE?)

I'm guessing the "No tests were found." output is a hint. If it expects to finds tests written using `package:test`, it might decide to simply skip everything if it doesn't find any.

**Comment by ChaserVasya** [comment]
@lrhn , You are right. Adding test plug as below helped me.
```
void main() {
  test(
    'foo',
    () => generateHehJson().listen((e) => print(e)),
  );
}
```

But before flutter upgrade this doesn't help me. So, I did not attach importance to the hint. We can close issue.
