### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by shivamhaldkar** [dart-lang/sdk#47283]
## Version information

- `IDEA AI-203.7717.56.2031.7583922`
- `2.12.0`
- `AI-203.7717.56.2031.7583922, JRE 11.0.10+0-b96-7249189x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366.0x768.0`

**Comment by stevemessick** [comment]
Closing as there is no actionable content.
