### ISSUE TITLE
dart2js: support for stdin & stdout 

### ISSUE THREAD

**Issue by Bara-dev** [dart-lang/sdk#47286]
I'm not sure if there's a flag I'm missing, but is it possible for dart2js to use stdin and stdout?
The closest issue I found is [3037](https://togithub.com/dart-lang/sdk/issues/3037) (opened: 2012, closed: 2018) with no clear explaination.

For context, I'm simply trying to build an online dart to js compiler (which would use dart2js). Writing to file and then reading it just to return it to the user is a bit too much, but I understand if supporting stdin and stdout is out of the scope.

**Comment by rakudrama** [comment]
I don't see us putting much effort into supporting stdin and stdout.

Most applications are organized as one or more packages, so there is more than one input file describing the package (`pubspec.yaml`, `analysis_options.yaml`, a `lib/` directory containing `.dart` files, etc).

dart2js produces more than one output file, so stdout is not really suitable. The outputs include one or more `.js` files, corresponding source map `.js.map` files, a `.deps` file listing the dependencies (files that if changed might result in a change in the outputs), as well as some other files when given appropriate command line arguments.

**Comment by Bara-dev** [comment]
I see, thanks for the info!
