### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by shivamhaldkar** [dart-lang/sdk#47292]
![package error](https://user-images.githubusercontent.com/72499474/134942561-8a85a4b9-556f-4a79-82a2-c024a786b9c9.PNG)

my every package show this type of error or else, please someone help.

**Comment by stevemessick** [comment]
From the screen shot, it looks like your Dart files have been overwritten by compiled Java code from an Android app. I don't think there is much we can do to help. I'd suggest re-installing your Dart code from backup.
