### ISSUE TITLE
Static consts in extension are not visible

### ISSUE THREAD

**Issue by ChaserVasya** [dart-lang/sdk#47299]
![image](https://user-images.githubusercontent.com/74578917/135013212-d13b3b3a-9e97-433f-9e6c-6ce0792a9cbb.png)

dart --version:
`Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "windows_x64"`

**Comment by julemand101** [comment]
You cannot use extensions to add new static members to types. The purpose of static at extensions is to access the static variable though the extension itself which requires you to name it:
```dart
void main() {
  print(FooExtension.extension_bar); // 2
}

class Foo {
  static const int origin_bar = 1;
}

extension FooExtension on Foo {
  static const int extension_bar = 2;
}
```
Or if some of your extension methods needs access to some static helper methods and/or fields.
