### ISSUE TITLE
[analyzer] Failure in language/constants_2018/constant_types_test/04

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#47302]
CL https://dart-review.googlesource.com/c/sdk/+/214644 changed said test such that it expects to use a type variable in the initializer list of a constant constructor as a type literal without error:

```dart
class C<X> {
  final t;
  const C(): t = X;
}
```

This used to be a compile-time error, but with https://github.com/dart-lang/language/pull/1860 it is no longer an error (a type variable used as an expression is a potentially constant expression).

This is part of the constructor-tearoffs feature bundle and part of the work requested in https://github.com/dart-lang/sdk/issues/47150.

NB: Due to a glitch in Gerrit (which has been reported), the change does not cause any buildbots to turn red, and there will not be an approval for the failure. This issue would have been the one to mention in that approval.

**Comment by scheglov** [comment]
Do we allow type variables only when `constructor-tearoffs` is enabled for the library? Or always?

**Comment by eernstg** [comment]
This is all part of the `constructor-tearoffs` feature bundle, so it should only be enabled there.

**Comment by srawlins** [comment]
tests/language/const/instantiated_function_constant_test.dart exercises this new rule too.

**Comment by scheglov** [comment]
It seems that type variables were already allowed as "potentially constant type expression" for null safety.
https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#const-objects

So, my understanding is that now we enable them as "potentially constant expression" when `constructor-tearoffs` is enabled. This seems to fix the language test.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/215014

**Comment by eernstg** [comment]
> enable them as "potentially constant expression" when `constructor-tearoffs` is enabled

Exactly, thanks!
