### ISSUE TITLE
[isolate] Exception thrown from isolate NOT typed, hard to handle (eg: filter by type)

### ISSUE THREAD

**Issue by peterweb2005** [dart-lang/sdk#47318]
for example, i throw a exception inside isolate,

```
throw SocketException('io or read timeout')
```

then i CAN catch the "exception" from the isolate call
```
        await compute(isolateRequest, [
          client,
          request,
        ]);
```

but the error or "exception" caught cant filter
even cant filter by the "case Exception" clause, the error is not Exception?

and when the error thrown not thought isolate is good, can filter

```
    switch (error.runtimeType) {
      case SocketException: // socket or conn
        message = fromSocketException(error);
        break;
      case Exception:
        message = fromException(error);
        break;
      default:
    }
```

**Comment by a-siva** [comment]
can this be closed as 'closed-as-intended'

**Comment by lrhn** [comment]
I believe the VM team is working on sending stack traces through send-ports. At that point, `compute` could possibly be rewritten to pass the actual error object instead of a string representation. 
It's not there yet, and it'll be a Flutter issue to do so, so closing this issue.
