### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SocketException: OS Error: Software caused connection abort, errno = 103, address = x.x.x.x, port = 40201

### ISSUE THREAD

**Issue by Tan-yi-xiong** [dart-lang/sdk#47319]
## code
```dart
   Socket.connect('192.168.3.244', 8848).then((socket) {
      print('connectSuccess');
      socket.listen((event) {

      }, onError: (e, s) {
        print('onListenerCallError: $e');
      });
      socket.write('data');
    }).catchError((e) {
      print('connectError: $e');
    });
```

## Steps to Reproduce

 

1. Execute this code when the network is open.
   log:`I/flutter: connectSuccess`
2. Shut down all Internet connections on your phone.
   log: `I/flutter: onListenerCallError: SocketException: OS Error: Software caused connection abort, errno = 103, address = 192.168.3.244, port = 44968`  
 `E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SocketException: OS Error: Software caused connection abort, errno = 103, address = 192.168.3.244, port = 44968`

**Expected results:**  No exceptions will be thrown after listening is set up.

**Actual results:**  I got this error in the listener, but the error is still thrown, I don't know how to catch  it.

**OS:** Android

**Comment by lrhn** [comment]
It's not clear whether the missing error handling is in Dart code or Flutter code.
Tentatively marking as an issue for `dart:io`.

**Comment by Tan-yi-xiong** [comment]
I opened the same issue under the Flutter repo, [reply](https://github.com/flutter/flutter/issues/90927#issuecomment-930016391) is dart issue.

**Comment by a-siva** [comment]
The unhandled error could be coming from the socket.write('data'); line which does not seem to have a try/catch around it.

**Comment by MichalNemec** [comment]
Hello, im using mqtt5_client package and upon turning network off i get `SocketException: Software caused connection abort (OS Error: Software caused connection abort, errno = 103), address = mq.domain.com, port = 49304` and ive created issue on the lib https://github.com/shamblett/mqtt5_client/issues/90 which navigated me here, because it uses dart:io.

How can i catch this issue? its spamming my crashlytics.

**Comment by a-siva** [comment]
//cc @brianquinlan

**Comment by aam** [comment]
To catch async errors related to socket operations you need to start socket connection in the Zone with your custom error handler using `runZonedGuarded`. `Zone` is the mechanism you use to handle "unhandled" async errors in Dart.
