### ISSUE TITLE
[CP] Merge fix for dynamic table in separate debugging ELF files

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#47316]
**commit(s) to merge**: d16ad3d

**merge instructions**: merges cleanly into `origin/stable`

**What is the issue**: Dynamic table in separate debugging information ELF file has invalid relocated addresses when segments are loaded into memory.

**What is the fix**: NOBITS sections, which have no file content to load into segments, are now ordered in segments after sections that do have content.

**Why cherrypick**: The bad dynamic table information impacts tools that handle the separate debugging information like [Sentry](https://github.com/getsentry/sentry-dart).

**Risk**: None.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/47289

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by athomas** [comment]
Merged to stable in 020b3efd3f0023c5db2097787f7cf778db837a8f (2.14.3).
