### ISSUE TITLE
Ability to use Sanitizers or Valgrind to test Dart+C++ or Dart+Rust?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#47315]
Hi thanks for the wonderful language and sdk! I wonder whether we can use Sanitizers or Valgrind to test Dart+C++ or Dart+Rust?

For example, when code-reviewing a library, I see some double-free problems (here https://github.com/sunshine-protocol/allo-isolate/issues/7 if you are interested). This is quite dangerous, and if it is running on users' phones it can crash and make the users very angry.

I know it seems that there is no good ways to use Sanitizers or Valgrind to test Flutter+C++ or Flutter+Rust. But maybe we can have it in the *dart* environment (not *Flutter* environment)?

Thanks for any help!

**EDIT:** I see Valgrind seems to be able to be used because it can instrument any binary (not tested yet). But what about sanitizers - can we use them? Because Valgrind is very slow, so my workload may need to run for a long time under the instrumented mode.

**Comment by rmacnak-google** [comment]
The Dart VM is continuously tested with Address Sanitizer, Memory Sanitizer, Thread Sanitizer and Undefined Behavior Sanitizer. To use them with your own project, you would have have to build the VM yourself and enable them by passing `--sanitizer=asan` etc to `tools/build.py`.

https://github.com/dart-lang/sdk/wiki/Debugging-Dart-VM-with-AddressSanitizer

**Comment by fzyzcjy** [comment]
@rmacnak-google Thanks for the reply! But imho that link is about sanitizing the *dart vm itself*, not the C++/Rust code that in my app and which is communicating with dart via ffi.

**Comment by fzyzcjy** [comment]
@rmacnak-google I have tried but cannot figure out a way to let the ASan work with dart+rust. Could you please give some hints, or make this issue open (since it is not solved)? Thanks!
