### ISSUE TITLE
pkg:meta - Add TargetKind.enumValue (or similar)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#47312]
I have a case where an annotation is only valid on the values/members/whatever of an enum.

```dart
enum Foo {
  @JsonValue('bob')
  robert
}
```

I'd love to be able to do

```dart
@Target({TargetKind.enumEntry})
class JsonValue {
...
```

See https://github.com/google/json_serializable.dart/issues/616

**Comment by bwilkerson** [comment]
Sounds reasonable to me. I'd name it `enumConstant`.

I don't know whether adding a target kind would be a breaking change, but hopefully not.

**Comment by kevmoo** [comment]
We should chat with @scheglov – I think we've had issues  with adding here before...and avoiding breaks!

**Comment by scheglov** [comment]
Adding a new enum value is formally a breaking change, it breaks any `switch` statement making it non-exhaustive. My understanding is that we decided that for `meta` we allow such breakage and don't expect that there are other consumers of `meta` than `analyzer`, that use `TargetKind`, and the analyzer itself uses `TargetKindExtension` to encapsulate the `switch`.

So, we might be fine to add it.
