### ISSUE TITLE
Instantiated tearoffs of equal functions are not equal

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#47317]
According to the @eernstg equality of local functions is not specified. But we do specify that the equality properties of any function object obtained by generic function instantiation is determined by the equality of the source function objects.

But the following [test](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Constructor-tear-offs/equality_A03_t01.dart) fails
```dart
import "../../Utils/expect.dart";

main() {
  X localFunction<X>(X x) => x;

  var f1_1 = localFunction;
  var f1_2 = localFunction;
  var f2_1 = f1_1<int>;
  var f2_2 = f1_2<int>;

  Expect.equals(f1_1 == f1_2, f2_1 == f2_2);
}
```
If `f1_1 == f1_2`, then it must be `f2_1 == f2_2` or vice versa, if `f1_1 != f1_2`, then we should have `f2_1 != f2_2`. Anyway `Expect.equals()` in this test must pass but it doesn't

Tested on `Dart SDK version: 2.15.0-139.0.dev (dev) (Wed Sep 22 12:41:36 2021 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
@sgrekhov, I'm not sure about the configurations where this failure occurs (it could be a common-front-end-only behavior, but it could also depend on the backends). Do you have more precise information about the failing configurations?

**Comment by sgrekhov** [comment]
@eernstg it's a runtime error on dartk and dartkp configurations. Please see https://dart-ci.firebaseapp.com/cl/215543/1

**Comment by eernstg** [comment]
OK, thanks!

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/215620 fixes

```
co19/LanguageFeatures/Constructor-tear-offs/equality_A03_t01
co19/LanguageFeatures/Constructor-tear-offs/equality_A03_t02
co19/LanguageFeatures/Constructor-tear-offs/equality_A03_t04
```

The test `co19/LanguageFeatures/Constructor-tear-offs/equality_A03_t05` still fails because it has an incorrect expectation, filed https://github.com/dart-lang/co19/issues/1210.
