### ISSUE TITLE
Wrong analyzer error for identical constant instantiated tearoffs

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#47329]
The followin code produces an error in analyzer and no issues in CFE

```dart
class CheckIdentical {
  const CheckIdentical(Object? o1, Object? o2) : assert(identical(o1, o2));
}

X topLevelFunction<X>(X x) => x;

const c1 = topLevelFunction<int>;
const int Function(int) c2 = topLevelFunction;

main() {
  const CheckIdentical(c1, c2); // Analyzer error. Evaluation of this constant expression throws an exception.
}
```
Both of those function objects are obtained as a generic function instantiation with the constant type expression `int` as the type argument, based on two occurrences of the identifier `topLevelFunction`, and they should both evaluate to the same function object, a closurization of said function declaration, cf. https://github.com/dart-lang/language/blob/3e1d7084ecba96bc88a9db49532c2bba1ff2da15/specification/dartLangSpec.tex#L13107.

Tested on ``Dart SDK version: 2.15.0-150.0.dev (dev) (Fri Sep 24 21:55:32 2021 -0700) on "windows_x64"

**Comment by scheglov** [comment]
This code works with the bleeding edge analyzer. I suspect that @srawlins fixed it.
