### ISSUE TITLE
Null safety migration unnecessarily inserts null assertion operator in map operator [] calls.

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#47326]
In the following program there is an operator [] call on a map: `var t = m[x];`. The argument type is `Object?` so a nullable variable should be allowed to be passed.

```dart
String foo() {
  var m = <int, String>{1: 'one'};
  var x = nullableInt();
  var t = m[x];
  if (t == null) return null;
  return '$t with other text';
}

int nullableInt() => null;
```
Running the migration tool on this library produces the following changes. The `!` operator was inserted on the argument to the operator [] causing a runtime error where there was none before. 

```dart
String? foo() {
  var m = <int , String>{1: 'one'};
  var x = nullableInt();
  var t = m[x!];
  if (t == null) return null;
  return '$t with other text';
}

int? nullableInt() => null;
```

This is a minimal repro but I have had this come up multiple times while migrating real libraries.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
