### ISSUE TITLE
CastError in MapMixin.entries

### ISSUE THREAD

**Issue by kuhnroyal** [dart-lang/sdk#47335]
Dart version: Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "macos_x64"

I am getting a `type 'Null' is not a subtype of type 'AssetPaging' in type cast` from inside `MapMixin.entries`.

The project is on sound null-safety and the map is declared as
```dart
final Map<AssetPathEntity, AssetPaging> _dataMap = {};
```
So it should not be possible to have null values.

After debugging this I am kind of lost:
<img width="1334" alt="Bildschirmfoto 2021-09-30 um 15 08 31" src="https://user-images.githubusercontent.com/1260818/135462187-5856abf6-9942-44d5-8500-5e531edae29d.png">

The map clearly has the key/value pair but the retrieval of the value via `this[key]` returns null.

This is happening in a Flutter app so I am not completely sure this is the right place for the issue.
The problem is ONLY happening on iOS and not on Android which makes me wonder if this is somehow caused by the native map implementation.

**Comment by kuhnroyal** [comment]
I added a couple more watches that I can not make sense of:

<img width="331" alt="Bildschirmfoto 2021-09-30 um 15 32 45" src="https://user-images.githubusercontent.com/1260818/135470138-c08c7263-9dc8-40fc-ac5f-ab91359e783b.png">

The difference between these 2:

```
containsKey(keys.first) = false
keys.containsKey(keys.first) = true
```
shows that there is something weird happening in the `_InternalLinkedHashMap` implementation.

**Comment by mraleph** [comment]
@kuhnroyal could you provide the definition of `AssetPaging`? Most specifically it's `get hashCode` and `operator==`. This sort of error can happen if `get hashCode` returns unstable result.

**Comment by lyio** [comment]
Should the `hashCode` of `AssetPaging` matter as it is the value in the map? The `hashCode` of `AssetPathEntity`, the key in this case, is generated using the `hashCode` of one of its properties, namely the `id`.

```
  @override
  int get hashCode {
    return this.id.hashCode;
  }
  ```
`AssetPaging` itself does not have a `hashCode` implementation.

**Comment by mraleph** [comment]
If hash code of a key changes after it was inserted into the map then the map will get into an inconsistent state - and you will not be able to find this key again, because hash map implementation uses hash code to locate where the key resides. 

```
class X {
 int hashCode = 42;
}

void main() {
  final key = X();
  final map = <X, String>{};
  map[key] = "ok";
  print(map[key] ?? "fail");  // -> ok
  key.hashCode = 24;
  print(map[key] ?? "fail");  // -> fail
  print(map[map.keys.first] ?? "fail");  // -> fail
  key.hashCode = 42;
  print(map[key] ?? "fail");  // -> ok
  print(map[map.keys.first] ?? "fail"); // -> ok
}
```

That's how hash maps work and that's why `get hashCode` is expected to return consistent values and not change over time.

**Comment by kuhnroyal** [comment]
@mraleph Yes, I understand that. But the error is happening inside the SDK map implementation while it is iterating over its list of keys.

**Comment by mraleph** [comment]
The error happens because the map got into an inconsistent state, because you violated the invariant, and `map[key]` does not work even for the keys which are in the map.

**Comment by kuhnroyal** [comment]
Yes, you are correct, thank you!
I just didn't expect the map to throw wile it is iterating over its own keys.
