### ISSUE TITLE
break_on_function_many_child_isolates_test failing on ubsan bot

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#47341]
break_on_function_many_child_isolates_test is failing on the ubsan bot. It's a NPE at [jit/compiler.cc:246](https://github.com/dart-lang/sdk/blob/main/runtime/vm/compiler/jit/compiler.cc#L246)

Logs: https://dart-ci.appspot.com/log/vm-kernel-ubsan-linux-release-x64/dartk-ubsan-linux-release-x64/1038/service_2/break_on_function_many_child_isolates_test/service

This test has [previously been flaky](https://github.com/dart-lang/sdk/issues/46909), but the new failure looks different. Might be related to isolate groups?

**Comment by dcharkes** [comment]
Another one today: https://dart-ci.appspot.com/log/vm-kernel-ubsan-linux-release-x64/dartk-ubsan-linux-release-x64/1046/service_2/break_on_function_many_child_isolates_test/service

cc @bkonyi service protocol
cc @aam @mkustermann isolate groups

**Comment by mkustermann** [comment]
Seems like a benign, trivial issue. Made [cl/215547](https://dart-review.googlesource.com/c/sdk/+/215547)
