### ISSUE TITLE
Wrong Null warning on const building from function parameters

### ISSUE THREAD

**Issue by ChaserVasya** [dart-lang/sdk#47351]
Snipped and problem:

![image](https://user-images.githubusercontent.com/74578917/135622585-c1371b86-4d77-4b52-8581-cbc28b2de2d5.png)

`bar` is definitly nonNull. But the  third warning states the opposite. Other warnings are true.

dart --version :
`Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "windows_x64"`

**Comment by kallentu** [comment]
Fixed after ba00516.
