### ISSUE TITLE
What is "ENABLE SERVER SNIPPETS" in VS CODE Dart?

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/sdk#47368]
Please elaborates its purpose, I cant find any thing on it.

**Comment by lrhn** [comment]
If you read the documentation in the VS-Code settings, it says:

> **Dart: Enable Server Snippets**<br>
> * [ ] This setting is currently unused and should be left set to 'false'. It will be updated an enabled by default in the future.

So: It apparently (currently) does nothing. If you want to know what it's intended for, you should ask the [DartCode project](https://dartcode.org/) directly.
