### ISSUE TITLE
json.decode() does not parse JSON

### ISSUE THREAD

**Issue by shubham9436** [dart-lang/sdk#47367]
I have a json String `{"a":"{\"b\":7}"}`. But it does not get decoded from the default library. I have written the following code:
```
import 'dart:convert';
void main() {
  String a =
        '{"a":"{\"b\":7}"}';
   print(json.decode(a));
}
```

**Comment by asashour** [comment]
If you print `a`, it would be

    {"a":"{"b":7}"}

I guess you mean `a` to be the below (as `r`aw)

```dart
String a =
  r'{"a":"{\"b\":7}"}';
```

**Comment by lrhn** [comment]
What @asashour says. Your code does not contain the JSON text `{"a":"{\"b\":7}"}`.
It contains a string with content `{"a":"{"b":7}"}`, which is not valid JSON, because the `\`s are interpreted as escapes in the string literal.
So, working as intended.

**Comment by shubham9436** [comment]
> If you print `a`, it would be
> 
> ```
> {"a":"{"b":7}"}
> ```
> 
> I guess you mean `a` to be the below (as `r`aw)
> 
> ```dart
> String a =
>   r'{"a":"{\"b\":7}"}';
> ```
> 
> Or
> 
> ```dart
> String a =
>   '{"a":"{\\\"b\\\":7}"}';
> ```

How to convert `'{"a":"{\"b\":7}"}'` to `'{"a":"{\\\"b\\\":7}"}'` or `r'{"a":"{\"b\":7}"}'` ?

**Comment by asashour** [comment]
You put `r` in front of the string.

Or you write it manually.

I guess some IDEs in other languages could escape the string if you paste the content inside "". A possible enhancement requests to their teams.

**Comment by shubham9436** [comment]
https://pub.dev/packages/g_json solves the problem.
