### ISSUE TITLE
Instantiate-to-bounds works incorrectly for typedef with two independent type parameters

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#47364]
Dart SDK version: 2.15.0-82.2.beta (beta) (Wed Sep 15 13:03:43 2021 +0200) on "windows_x64"

Let's consider the following code source:

``` dart
class A<X> {}
class B<X> {}

typedef G1<X, Y extends B<Y>> =  X Function(Y);
typedef G2<X extends A<X>, Y> =  X Function(Y);
typedef G<X extends A<X>, Y extends B<Y>> =  X Function(Y);

main() {
  G? source;
  G1? source1;
  G2? source2;
}
```
`G`, `G1` and `G2` are typedefs with two type parameters - `X` (covariant) and `Y` (contravariant).

For any of these typedefs, `X` and `Y` do not depend on each other, so seems like any of them  should be  equal to `A<Object?> Function(A<Never>)` and the test should pass.

However both dart and analyzer throw a compile time error for the line `9` (`G? source;`).

Dart sample output is :
```
test.dart:9:6: Error: Type argument 'A<dynamic>' doesn't conform to the bound 'A<X>' of the type variable 'X' on 'G'.
 - 'A' is from 'test.dart'.
Try changing type arguments so that they conform to the bounds.
  G? source;
     ^
test.dart:6:11: Context: This is the type variable whose bound isn't conformed to.
typedef G<X extends A<X>, Y extends B<Y>> =  X Function(Y);
          ^
test.dart:9:6: Context: If you want 'G<A<dynamic>, B<Never>>?' to be a super-bounded type, note that the inverted type 'G<A<Never>, B<Object?>>?' must then satisfy its bounds, which it does not.
 - 'A' is from 'test.dart'.
 - 'B' is from 'test.dart'.
 - 'Object' is from 'dart:core'.
  G? source;
     ^
```
Analyzer output is:
```
Analyzing test.dart...
  error - 'B<Object?>' doesn't conform to the bound 'B<B<Object?>>' of the type parameter 'Y'. - test.dart:9:3 - type_argument_not_matching_bounds
  hint - The value of the local variable 'source' isn't used. - test.dart:9:6 - unused_local_variable
  hint - The value of the local variable 'source1' isn't used. - test.dart:10:7 - unused_local_variable
  hint - The value of the local variable 'source2' isn't used. - test.dart:11:7 - unused_local_variable
1 error and 3 hints found.
```

**Comment by eernstg** [comment]
For the bounds checks we need to consider the invocation of the type alias at first, and if that is not an error then we can expand the type alias and see which type it ultimately denotes.

So `G` means `G<A<dynamic>, B<Never>>`, and that type is neither regular bounded nor super bounded (if we invert it then we get `G<A<Never>, B<dynamic>>`, which is also not regular bounded), so the raw `G` is an error (and we don't reach the step where we note that it would mean `A<dynamic> Function(B<Never>)`).

`G1` means `G1<dynamic, B<Never>>`, which is a regular bounded type that denotes `dynamic Function(B<Never>)`.

`G2` means `G2<A<dynamic>, dynamic>` which is super bounded (the inverted type is `G2<A<Never>, dynamic>`, which is regular bounded).

The common front end (and hence `dart`) is correctly flagging `G` and accepting `G1` and `G2`, and so is the analyzer.

The error message printed by the analyzer is a bit confusing. Apparently, the analyzer detects that the type is not regular bounded; then it computes the inverted type (replacing contravariantly located bottom types by `Object?` and top types in any non-contravariant location by `Never`); but then it detects that this inverted type also isn't regular bounded, which causes the error message

```
'B<Object?>' doesn't conform to the bound 'B<B<Object?>>' of the type parameter 'Y'
```

However, that error message isn't very helpful: The program doesn't pass `B<Object?>` as a type argument to any type in the specified line of code, not even after using instantiation to bound to expand `G` into `G<A<dynamic>, B<Never>>`.

So even the developer who knows exactly how raw types are treated wouldn't necessarily know where `B<Object?>` came from.

@scheglov, do you think it would be possible to adjust the analyzer error message associated with this kind of situation such that it talks about the given code?  -- that is, we'd tell the developer that `G` means `G<A<dynamic>, B<Never>>`, and then we'd complain that this is not a well-bounded type?

We wouldn't have to talk about super bounded types at all in the case where there are no correct super bounded types, but the analyzer could of course choose to mention that the given type fails to be correctly super bounded, cf. the error message from the CFE.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/215484
