### ISSUE TITLE
Flaky pkg/dds/test/get_cached_cpu_samples_test

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#47375]
`TESTEE ERR: ../../runtime/vm/profiler.cc: 250: error: expected: filter != NULL`.

log: https://dart-ci.appspot.com/log/pkg-linux-debug/unittest-asserts-debug-linux/12172/pkg/dds/test/get_cached_cpu_samples_test

![image](https://user-images.githubusercontent.com/3601775/135978337-c5a1d83f-84bc-41d4-8828-da82944368d0.png)

Toggled from flaky to failing on debug-linux today.

Test introduced in c7fe9ada2f3112bb4c593e2a328fd91379284bc8.

cc @bkonyi

**Comment by bkonyi** [comment]
This assertion has been removed so this issue is no longer valid.
