### ISSUE TITLE
Cannot use mixin method

### ISSUE THREAD

**Issue by fctorial** [dart-lang/sdk#47382]
```
void main(List<String> arguments) {
  A('').f();
}

class A {
  final String s;
  A(this.s);
}

mixin M on A {
  void f() {
    print(this.s);
  }
}
```
An error is reported on line 2 saying 'method f not found for class `A`). Isn't a class part of its own class heirarchy?

**Comment by nshahan** [comment]
`mixin M on A` is only a way to limit the classes that mixin `M` can be applied to. You still need to apply the mixin to a class by using the `with` keyword. See the last example in the mixin documentation here: https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins

With your example:
```dart
void main(List<String> arguments) {
  B('hello').f();
}

class A {
  final String s;
  A(this.s);
}

mixin M on A {
  void f() {
    print(this.s);
  }
}

class B extends A with M {
  B(String s) : super(s);
}
```

**Comment by fctorial** [comment]
I tried adding mixin M to A but that resulted in four errors:

![image](https://user-images.githubusercontent.com/58381615/136120312-e457d2b0-db7e-4f95-bf0b-6ff55ad1caf3.png)

Is it possible to use a mixin  for a single class without creating a boilerplate class?

**Comment by fctorial** [comment]
I was trying to use mixins as rust impl blocks. In rust you can use multiple impls for a struct to group methods together. Apparently that's not the intended use of mixins.
