### ISSUE TITLE
Failures on Fix a bug where calling _WindowsCodePageEncoder.convert would call an abort on non-Windows platforms.

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#47402]
There are new test failures on [Fix a bug where calling _WindowsCodePageEncoder.convert would call an abort on non-Windows platforms.](https://github.com/dart-lang/sdk/commit/bfbf75a1f65d20368d9a0a750984d8c995a1d12d).

The tests
```
standalone_2/io/issue_46436_test CompileTimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-x64
dartkp-linux-product-x64
dartkp-linux-release-simarm-crossword
dartkp-mac-release-simarm64
dartkp-obfuscate-linux-release-x64
dartkp-win-release-x64
```

This new test uses `dart:mirrors` which is not supported in AOT mode. We should either rewrite the test without dart:mirrors or skip it in tests/standalone_2/standalone_2_kernel.status and tests/standalone/standalone_kernel.status:
```
[ $runtime == dart_precompiled ]
io/issue_46436_test: SkipByDesign # dart:mirrors is not supported in AOT
``` 

/cc @brianquinlan

**Comment by brianquinlan** [comment]
Fixed in de45656da1885cbc761fb45e8f63cef0ae6ba52a.
