### ISSUE TITLE
Stop producing .packages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#47431]
We added logic to produce the new packages file: `.dart_tool/package_config.json`, however we now generate both that and `.packages`. I think we should stop generating `.packages`, so that there is a single master, and less room for confusion.

Known dependants of the `.packages` file that will need to get fixed first:

- [x] dart.dev docs: https://github.com/dart-lang/site-www/issues/3422
- [x] IntelliJ plugin: https://github.com/flutter/flutter-intellij/issues/5614

**Comment by mit-mit** [comment]
I moved this to the SDK tracker as it's such a cross-cutting issue.

**Comment by rakudrama** [comment]
In my personal workflow on small code snippets (often copy/paste from bug reports) I use
```
dart/sdk$ sdk/bin/dart --packages=.packages  /some/path/foo.dart
dart/sdk$ sdk/bin/dart2js_developer --packages=.packages  /some/path/foo.dart
```
What would this look like if `.packages` was removed?
I have over 1200 of these small programs, so creating some kind of project for each one would cumulatively have been quite a burden.

**Comment by mit-mit** [comment]
Can't you just pass a `package_config.json` file instead?

```
dart/sdk$ sdk/bin/dart --packages=package_config.json /some/path/foo.dart
dart/sdk$ sdk/bin/dart2js_developer --packages=package_config.json  /some/path/foo.dart
```

Yes, we'd have to replace our current `.packages` file with a `package_config.json` file, but that is an SDK specific issue.

**Comment by natebosch** [comment]
> Yes, we'd have to replace our current `.packages` file with a `package_config.json` file, but that is an SDK specific issue.

@rakudrama - this issue refers to the `.packages` file created by `dart pub get` in packages. I think you're referring to doing development directly in the SDK repo. That `.packages` file removal is tracked at https://github.com/dart-lang/sdk/issues/48275

We already have a replacement file it the SDK repo, you can change `--packages=.packages` to `--packages=.dart_tool/package_config.json`. This should work today.

**Comment by sigmundch** [comment]
An issue we discovered today that is worth tracking before we stop generating .packages files:
* [ ] https://github.com/dart-lang/sdk/issues/48939

**Comment by mit-mit** [comment]
PR for this: https://github.com/dart-lang/sdk/issues/47431

I'll move the VM issue discussed in https://github.com/dart-lang/sdk/issues/47431#issuecomment-1115115928 to https://github.com/dart-lang/sdk/issues/48272

**Comment by mit-mit** [comment]
Roll is https://dart-review.googlesource.com/c/sdk/+/244621

**Comment by sigurdm** [comment]
> Roll is https://dart-review.googlesource.com/c/sdk/+/244621

Actual roll is: https://dart-review.googlesource.com/c/sdk/+/244623
