### ISSUE TITLE
new annotation to identify classes safe for use as mixins

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#47437]
More context in https://github.com/dart-lang/linter/issues/3018#issuecomment-940383834.

**TL;DR:** some classes are _intended_ to be mixed in and it would be great if an annotation could teach the `prefer_mixin` lint about them.

**Comment by pq** [comment]
See also dart-lang/language#1529 and https://github.com/dart-lang/language/issues/1643.

Also fyi: @lrhn, @Hixie.

Assuming we're allowing a class to be used as **_both_** a class and a mixin, I'm inclined towards `@mixable`.

**Comment by parlough** [comment]
With the addition of the [`mixin`](https://dart.dev/language/mixins#class-mixin-or-mixin-class) class modifier as part of Dart 3's [class modifier feature](https://dart.dev/language/class-modifiers), it seems the use cases discussed here are handled.

As for the pragma/`package:meta` discussion, if anyone would like to continue that, please open a separate issue. Thanks all!
