### ISSUE TITLE
[CP] fix certificate loading in presence of expired certificates on Windows

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#47432]
commit(s) to merge: aa0a4410f447df4bbe14cd8cbc017ba04915a63b

merge instructions: clean merge

What is the issue: Correct certificate is not loaded in presence of similar, but expired certificate

What is the fix: Skip over expired certificates, don't load them.

Why cherrypick: Users report https-connectivity problems despite having valid certificates, caused by expired certificates

Risk: low

Link to original issue(s): https://github.com/dart-lang/sdk/issues/47420, https://github.com/dart-lang/sdk/issues/46370

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @a-siva

**Comment by athomas** [comment]
Cherry-picked to stable in 4ac35a7ec8c598ba1fdd8a1835a7fd84c61d9221 (`2.14.4`).
