### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by mastafa1122** [dart-lang/sdk#47442]
## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.14.0`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

**Comment by srawlins** [comment]
Please re-open if you see this problem again.
