### ISSUE TITLE
Automated tests for ensuring `dart create` templates can resolve and run

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#47458]
A couple of times, one of the templates in `dart create` have broken, for example in https://github.com/dart-lang/sdk/issues/47450.

I suggest we create a test that for each template at least runs:

1. `dart create -t <template> testapp`
2. `dart pub get`
3. `dart run` (or equivalent as needed by the app)

After 3. we should scrape the output looking for something that suggests the running was successful (like "Serving `web` on http://" for the web template)

**Comment by mit-mit** [comment]
CL in https://dart-review.googlesource.com/c/sdk/+/220883

**Comment by bkonyi** [comment]
Resolved in [this CL](https://dart-review.googlesource.com/c/sdk/+/227560).
