### ISSUE TITLE
Implement Enhanced Enums feature in the CFE

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#47453]
This issue is for implementing https://github.com/dart-lang/language/issues/158 in the CFE and referencing it in the related CLs.

See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

**Comment by devoncarew** [comment]
@chloestefantsova - did you mean this to be a general 'implement enhanced enums' issue, or just specific to the CFE? I started https://github.com/dart-lang/sdk/issues/47849 but then saw this issue.

**Comment by chloestefantsova** [comment]
> @chloestefantsova - did you mean this to be a general 'implement enhanced enums' issue, or just specific to the CFE? I started #47849 but then saw this issue.

I meant this as the CFE specific one, so the two issues are in agreement with each other 🙂

**Comment by chloestefantsova** [comment]
This is considered implemented.
