### ISSUE TITLE
[analyzer]: hasIsTest works on Mac, but not on Linux

### ISSUE THREAD

**Issue by Giuspepe** [dart-lang/sdk#47461]
I'm writing a dart script which analyzes all tests in a repository.
To do this, I have the following class:

```dart
class MyAnalyzer extends GeneralizingAstVisitor<void>
    with AstVisitingSuggestor { 

  @override
  void visitMethodInvocation(MethodInvocation node) {
    super.visitMethodInvocation(node);
    final isTest =
        node.methodName.staticElement?.hasIsTest ?? false;

    if (isTest) { 
        doStuff(node);
    }
  }
} 
```

My script works fine on Mac and acts on all tests.

However, when running the identical script on the identical repository, but on Linux instead of Mac, `isTest` is always false. 

**Expected error**
`hasIsTest` should work correctly regardless of the platform

My dart version is 2.14.3

**Comment by Giuspepe** [comment]
The source code I tried it with has the following structure:


```dart
void main() {
  test(...);

  testWidgets(...);

  @isTest
  myTestMethod(...);
}
```

Your assumption is right, indeed the `staticElement` is null for some reason on Linux while it is not null on Mac.

**Comment by asashour** [comment]
I have tested my sample with `Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "macos_x64"` and it printed `null`.

Could you provide a minimal complete case that behaves differently?
