### ISSUE TITLE
[bug?] dart:io Socket.connect creates two connections with non-dart:io TCP servers

### ISSUE THREAD

**Issue by epoberezkin** [dart-lang/sdk#47479]
The minimal example to reproduce:

A minimal node.js TCP server:

```javascript
const net = require('net');
const port = 8080;

const server = new net.Server();

server.listen(port, function() {
    console.log(`listening on localhost:${port}`);
});

server.on('connection', function(socket) {
    console.log('new client connection');
    socket.on('data', function(chunk) {
        console.log(`received: ${chunk.toString()}`);
    });
});
```

Dart socket connection:

```dart
import 'dart:io';

void main() async {
  final socket = await Socket.connect('localhost', 8080);
  socket.add([65, 66, 67]);
  await socket.flush();
}
```

Running the dart code make the server print 'new client connection' twice, but "ABC" is received only once.

The same happens with Haskell TCP server.

However, it does not happen with a minimal dart TCP server:

```dart
import 'dart:io';

void main() {
  ServerSocket.bind('localhost', 8080)
      .then((server) => server.listen((Socket socket) {
            print('new client connection');
            socket.listen((List<int> data) {
              String result = String.fromCharCodes(data);
              print(result);
            });
          }));
}
```

With dart server 'new client connection' is only printed once.

It means that dart client TCP Socket implementation is incorrect, but dart ServerSocket implementation compensates for it.

Neither JS, nor Haskell TCP clients do it.

**Comment by sortie** [comment]
The localhost address may resolve to both 127.0.0.1 (IPv4) and ::1 (IPv6). In those cases, it appears that Dart connects to the destination port on both addresses concurrently and prefers one of the connections (likely the first one to succeed, I'd have to check the code to confirm). This behavior would explain why you're seeing two connections if your node.js server listens on both IPv4/IPv6 on your operating system.

Such behavior was likely added as a feature to provide better performance on systems where IPv6 is around but doesn't actually work.

You can inhibit this behavior on localhost by connecting to 127.0.0.1 or ::1 directly. If you're connecting to other machines, you can select the protocol by setting the `sourceAddress` named parameter to an IPv4/IPv6 address to select the protocol (`InternetAddress.anyIPv4` and `InternetAddress.anyIPv6` are handy to request any available source address on the given protocol).

**Comment by epoberezkin** [comment]
@sortie - thank you! As far as I am concerned, it's the design choice, not a bug, that is probably worth adding to the docs, but in any case, I can workaround the issue by resolving the address manually.

Please close if you think nothing should be done.
