### ISSUE TITLE
Enable server + browser functionality in tests

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#4747]
Right now we have two ways of running tests: 
1) from the command line with the VM (or v8, etc)
2) in a browser.

There is a set of functionality that we're not testing, though: tests that require a local server to be running (on the VM) and also using a browser. An example might be we want to test FormData, and want to make sure the POST to the server received the data we thought we sent in the form. This requires us to fire up a server on the VM, and then open a browser (or DRT) and create a FormData and submit, which we currently can't do. 

There are a lot of tests (AudioElement, FormData for example) where we're only testing very limited functionality because we don't have this in the test framework. Let's add this ability to our test framework so we can write and run better tests (and better track functionality regression)!

**Comment by whesse** [comment]
Tests that involve multiple processes, or multiple machines, can be implemented well in Google's internal testing systems, so I propose that any tests that require custom servers and clients be added to Google's internal testing of the Dart SDK, instead of using test.py.  Leaving the issue closed.
