### ISSUE TITLE
[VMService] - getClassList missing in Service Protocol API TOC

### ISSUE THREAD

**Issue by bleroux** [dart-lang/sdk#47497]
[Dart VM Service Protocol API ](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#public-rpcs) documentation should have a link to `getClassList` RPC in TOC 'Public RPCs' section.
(`getClassList` is a public RPC and it is documented in the file, this issue is only to add it to TOC).

**Comment by a-siva** [comment]
Landed https://dart-review.googlesource.com/c/sdk/+/217183
