### ISSUE TITLE
Feature request: optional source port parameter for Socket.connect()

### ISSUE THREAD

**Issue by mofeldmann** [dart-lang/sdk#47500]
I would like to be able to specify the source port for outgoing TCP connections, this currently does not seem to be possible.
Is this a design decision? Otherwise I would try to develop a patch, in order to change `Socket.connect` to 
```dart
static Future<Socket> connect(host, int port, {sourceAddress, sourcePort, Duration? timeout})
```
In that case, have you any hints where I can find the corresponding C code for [socket_patch.dart](https://github.com/dart-lang/sdk/blob/056afdac39fc4160a5b13f134c86203a3975906c/sdk/lib/_internal/vm/bin/socket_patch.dart)?

**Comment by mofeldmann** [comment]
I submitted a patch here: https://dart-review.googlesource.com/c/sdk/+/217604
Feel free to review, thanks.

**Comment by a-siva** [comment]
Patch as landed, thanks for the contribution @mofeldmann, closing this issue.
