### ISSUE TITLE
Dart on M1 Mac is using too much memory, 24GB

### ISSUE THREAD

**Issue by hongfeiyang** [dart-lang/sdk#47503]
<img width="1072" alt="Screen Shot 2021-10-20 at 3 10 35 pm" src="https://user-images.githubusercontent.com/19302128/138027483-91254847-45f0-497d-bc78-afca6229a6c0.png">

Dart is using too much memory on my M1 MacBook Air. I know that dart is running on rosetta, but come on, 24GB memory usage is just too much...

I opened a flutter project on vscode, and while I was running flutter get, the memory usage just shot up like crazy. I am running macOS 11.6, flutter 2.5.1, Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "macos_x64".

This has happened many times already, it has become a problem and I have to force terminate any dart process every once in a while.

**Comment by goldcoders** [comment]
im using macbook air m1 never had this issue... im using 8gb ram

**Comment by a-siva** [comment]
> > @hongfeiyang To investigate this further we would need more information on what was running at that time, a command line of what was being run would be a good starting point.
> 
> `flutter pub get` and then it could not be completed because of a unsatisfiable dependency, and while on that screen, memory usage skyrocketed.

//cc @jonas-jonas

**Comment by hongfeiyang** [comment]
> im using macbook air m1 never had this issue... im using 8gb ram 
> 
> 

Strange, I got this kind of issue all the time, and sometimes my hot reload gets stuck and the memory usage is high too

**Comment by rohitrvayuz** [comment]
@lrhn @rmacnak-google @a-siva @hongfeiyang @vsmenon Any solution here?

**Comment by hongfeiyang** [comment]
> @lrhn @rmacnak-google @a-siva @hongfeiyang @vsmenon Any solution here?

I replaced flutter's packaged SDK with ARM64 version of the Dart SDK, seems to work exceptionally well

**Comment by lukaszciastko** [comment]
> > @lrhn @rmacnak-google @a-siva @hongfeiyang @vsmenon Any solution here?
> 
> I replaced flutter's packaged SDK with ARM64 version of the Dart SDK, seems to work exceptionally well

I did that, but it didn't help. I'm currently on an 8 GB M1 Mac (this was the only model available in the country where I was at the time), and my experience with Dart is really bad. Dart processes are using around 6-7 GB of RAM, which makes my laptop completely unusable at times.

**Comment by lukaszciastko** [comment]
> @lukaszciastko are you using something [`dart_code_metrics` ](https://pub.dev/packages/dart_code_metrics) plugin?

I'm not. Why?

**Comment by mraleph** [comment]
@lukaszciastko some plugins cause really bad memory usage.

**Comment by mraleph** [comment]
@lukaszciastko could you look at which dart process in particular is consuming a lot of memory? There might be multiple dart processes - and we need to know which one (e.g. is it one spawned by the IDE?)

**Comment by Pr47h4m** [comment]
I'm facing similar issues 
when I uncommented prefer_single_quotes option and then dart analyser was taking very very long 
then i need to quit vs code and then also dart did not get terminated from activity monitor and was taking 1gb physical memory

**Comment by hongfeiyang** [comment]
I eventually solved this issue with a maxed out M1 Max, haven't seen dart memory usage exceeding 64G, yet xD

**Comment by a-siva** [comment]
@Pr47h4m @lukaszciastko and @hongfeiyang can you all post the output from your activity monitor which shows all the dart processes running on the system when this happens.

**Comment by Pr47h4m** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56750378/156168294-6d72daba-7522-4c97-96aa-a978e7f8532c.png">

**Comment by Pr47h4m** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56750378/156399488-fcac491b-42a8-456c-a127-9083c0875165.png">

Please check there are 5-6 dart processes taking approximately 2.5-3GB RAM

**Comment by a-siva** [comment]
@DanTup when somebody is using VS code and developing a Flutter app, what are all the Dart processes that get started in the background. I am assuming one 'analysis server' process, one 'pub' process and one 'flutter tools' process, is any other Dart process started besides these.

**Comment by DanTup** [comment]
There are three processes that will be spawned by VS Code at project load that are longed-lived:

- `dart language_server` - the analysis server
- `flutter deamon` - the Flutter device daemon used to detect connected devices
- `dart devtools` - the backend server for serving DevTools

There are other processes that will be spawned, but none that are _expected_ to be long-lived (`pub get`, `dart`/`flutter` to run debug sessions, `flutter config` to get some config values, etc.).

On my M1 MacBook Air, opening a Flutter project I currently see only those three Dart processes:

<img width="992" alt="Screenshot 2022-03-02 at 19 46 24" src="https://user-images.githubusercontent.com/1078012/156438166-09492493-e067-4b8a-926e-f1c133b315c1.png">

Running `ps -x | grep dart` shows their full commands:

```
  870 ??         0:00.37 /Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart devtools --machine --try-ports 10 --allow-embedding
  871 ??         0:09.28 /Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart language-server --client-id=VS-Code --client-version=3.36.0
  907 ??         0:02.55 /Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/danny/Dev/Google/flutter/packages/flutter_tools/.packages /Users/danny/Dev/Google/flutter/bin/cache/flutter_tools.snapshot daemon
```

Additionally, running `code --status` provides some info about processes spawned from the VS Code extension host (I had to run the **Shell Command: Install 'code' command in PATH** command for the `code` command to work):

```
CPU %	Mem MB	   PID	Process
    0	   139	   835	code main
    0	    49	   838	   gpu-process
    0	    25	   840	   utility-network-service
    0	   221	   842	   window (main.dart — flutter_sudoku)
    0	    90	   852	   extensionHost
    0	     0	   869	     bash /Users/danny/Dev/Google/flutter/bin/flutter daemon
    0	   106	   907	       /Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/danny/Dev/Google/flutter/packages/flutter_tools/.packages /Users/danny/Dev/Google/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	   943	         /usr/bin/script -t 0 /dev/null /usr/bin/arch -arm64e xcrun xcdevice observe --both
    0	    33	   944	           /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0	    41	   870	     /Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart devtools --machine --try-ports 10 --allow-embedding
    0	   426	   871	     /Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart language-server --client-id=VS-Code --client-version=3.36.0
    0	   115	   853	   shared-process
    0	    41	   854	     ptyHost
    0	     0	   861	       /bin/zsh -l
    0	    41	   858	     fileWatcher
```

It would be useful to see the output of those commands (`ps -x | grep dart` and `code --status`) for anyone seeing this.

**Comment by DanTup** [comment]
It may also be worth noting that you'll get the processes noted above for _each VS Code window_. Each VS Code window is an isolated application and they cannot share those processes. Therefore if you open two different VS Code windows with two different Flutter projects, you will get 6 processes (and if those projects reference each other, there will be a lot of duplicated data in memory between the analysis servers).

If you do need to work on multiple projects, opening them in a single window (as a "multi-root workspace") would consume significantly less resources.

**Comment by a-siva** [comment]
Comment from @DanTup explains the resource usage and a mechanism for lowering the resource footprint.
Closing issue.
