### ISSUE TITLE
Cannot override generic method with constraints

### ISSUE THREAD

**Issue by pv-hernandez** [dart-lang/sdk#47510]
I was trying to mock a bloc class with mockito and ran into a strange compilation issue.

After some tests I reduced the problem to the dart compiler.

The dart compiler is not able to process the following code:

```dart
abstract class B<E1> {
  void f<E2 extends E1>(E2 tr);
}

class Ev {}

class B1 extends B<Ev> {
  @override
  void f<E3 extends Ev>(E3 tr) {
  }
}

void main() async {
  B1();
}
```

The linter doesn't find any problems, but the compiler reports this:
```log
Error compiling to JavaScript:
Info: Compiling with sound null safety
Warning: Interpreting this as package URI, 'package:dartpad_sample/main.dart'.
lib/main.dart:9:28:
Error: The parameter 'tr' of the method 'B1.f' has type 'E3', which does not match the corresponding type, 'E3', in the overridden method, 'B.f'.
  void f<E3 extends Ev>(E3 tr) {
                           ^
lib/main.dart:2:8:
Info: This is the overridden method ('f').
  void f<E2 extends E1>(E2 tr);
       ^
Error: Compilation failed.
```

If I remove the generic constraint `extends E1` from the base class (and remove `extends Ev` from the subclass) it works fine.

I tested this on the latest stable version of flutter installed in my machine and in the dartpad.dev version to check if it was something with my install. Both tests show the same error.

My machine is a macOS Big Sur and I ran the darted test on Safari.
DartPad reports this version: `Based on Flutter 2.5.3 Dart SDK 2.14.4`
The installed dart reports this version: `Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "macos_x64"`

**Comment by dgreensp** [comment]
This issue seems to still happen in some form in Dart 3.3.3 (analyzer has no problem but compiler says it's not a valid override):

```dart
import "package:web/web.dart" show Event;

abstract interface class IFoo {
  void listen<T extends Event>(void Function(T) callback);
}

class Foo implements IFoo {
  @override
  void listen<T extends Event>(void Function(T) callback) {
    
  }
}

void main() {
  
}
```

**Comment by mraleph** [comment]
@dgreensp please file a separate issue - this one is likely connected to the extension types.

**Comment by eernstg** [comment]
> compiler says it's not a valid override

This issue seems to have been corrected recently: The spurious error message is emitted when using the stable channel of DartPad, but not with the beta channel nor the main channel. So perhaps we don't even need a new issue.
