### ISSUE TITLE
Web Audio Api not working in Safari

### ISSUE THREAD

**Issue by AndrewLugg** [dart-lang/sdk#47520]
This tracker is for issues related to:
* dart2js
* web_audio_api

* Dart SDK Version 2.12-2.14

Browser Safari version < 14.

Web Audio Api in Dart Web, throws error in Dart versions 2.12 -2.14 when using Safari on iOS or MacOS with safari version less that 14. It works with Dart version 2.10 so a regression from old versions. I haven't tested it with 2.11.  I suspect it lines up with the "webkit" prefix for web audio versions lower than 14 of Safari (https://caniuse.com/?search=web%20audio%20api)

This use to work. Audio works fine using Audio Context. And I have tested it with 14.5 Safari, and that is fine as well.

Here is a copy of the error from safari, it is minified, but you can see the issue is occurring when it calls "decodeAudioData". This is not when playing, just when loading the audio ready to play.

<img width="1098" alt="web_audio_api" src="https://user-images.githubusercontent.com/19848590/138201275-b8edcfb0-18e3-469c-a6a8-cd31e849d250.png">

I suspect it has something to do with this commit (https://dart-review.googlesource.com/c/sdk/+/161628), as it is the only change to the web_audio_dart2js.dart since 2.10 version except for null-saftey changes, and it happens to be in "decodeAudioData".

**Comment by AndrewLugg** [comment]
I have created a quick reproducible example which I have tested with different devices with same results as mentioned above.

Here is a Gist of it: https://gist.github.com/AndrewLugg/3cab8b444cafd14c7ba97c4bb3bde6e5

The order might be slightly odd, it is because it is some stripped down code from my project that I use it in. The reason it is copying the buffer, is because we replay audio, and decoding the buffer destroys the original buffer, and we don't want to re-download the file.

This code works in Dart 2.10 on all devices, but in dart 2.14 only on newer Safari, Chrome. Below version 14 of safari, it will just say "starting.." with an error appearing in console, the "try and catch" doesn't catch it.

**Comment by AndrewLugg** [comment]
After doing some more testing, I have found this is related to null-safety. If I set "sound_null_safety" to false for dart2js, the issue goes away.

**Comment by srujzs** [comment]
I haven't been able to repro this, since I can't seem to find an approved way to downgrade Safari to test this with.

However, from your latest comment, it seems like this is triggering a null-assertion. `decodeAudioData` is typed to return a non-nullable `Future`, and it seems with a previous version of Safari, this wasn't true. The `toString` here is just an optimized null-check, and since the function doesn't seem to return a value, it's triggered. It's also likely why you don't see this behavior if you turn off sound null-safety.

https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData seems to backup this hypothesis noting that the API returns a `Promise` since 14.1. The fix here might to just type the API as nullable, although that may be a breaking change.

**Comment by AndrewLugg** [comment]
Another option would be swapping to use the callback, and generate the promise/future in dart. It would make it a non-breaking change, and would provide the promise for all browsers.

**Comment by srujzs** [comment]
Can you clarify what you mean by "swapping to use the callback"? You might be referring to this, but I can imagine one way of handling this is just directly calling the callbacks in the future we construct if they're provided. This would make `_decodeAudioData` nullable, and have us always returning the completer's future instead, keeping the return type the same.

**Comment by AndrewLugg** [comment]
I was meaning that all recent browsers offer `baseAudioContext.decodeAudioData(ArrayBuffer, successCallback, errorCallback);`
instead of using the newer `Promise<decodedData> baseAudioContext.decodeAudioData(ArrayBuffer);` that returns a promise, the sdk/library could create a completer and return  as a future of the completer, with it completing on the callback.
It would mean that the Future, would be not nullable, because it is just the future of the completer, which would make it a non-breaking change, but also it means that developers would get a consistent response without it acting differently on older browsers. Otherwise you may get some developers waiting on the promise and the response, and it gets null back on an old browser, and finding it a hard bug to track down.

It would kind of make Dart polyfilling this browser difference.

**Comment by AndrewLugg** [comment]
Any plans to implement a fix?

**Comment by srujzs** [comment]
Yes, I have a fix that I was playing around with a bit a while ago, but kept coming across issues with timing and inconsistencies between the two possible call syntaxes (might be specific to Chrome). I'll take a look again and see if I can resolve them and report back. Are you currently blocked/unable to work around this with interop?

**Comment by AndrewLugg** [comment]
I am having to have null-safety off on our deployments to make it work with safari which isn't ideal. I haven't swapped to using the interop instead because I was hoping it would be patched.

**Comment by srujzs** [comment]
I have a CL up for this, but the issues within Safari made it a little more complicated. Can I have you try this on an older Safari version and report back, Andrew? It works on my Safari version but it's >= 14.1.

<details>
  <summary>decodeAudioData</summary>

```dart
Future<AudioBuffer> decodeAudioData(ByteBuffer audioData,
      [DecodeSuccessCallback? successCallback,
      DecodeErrorCallback? errorCallback]) {
    // `decodeAudioData` can exist either in the older callback syntax or the
    // newer `Promise`-based syntax that also accepts callbacks. In the former,
    // we synthesize a `Future` to be consistent.
    // For more details:
    // https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData
    // https://www.w3.org/TR/webaudio/#dom-baseaudiocontext-decodeaudiodata
    var decodedBuffer;
    var decodeError;

    void success(AudioBuffer decodedData) {
      decodedBuffer = decodedData;
      successCallback?.call(decodedData);
    }

    void error(DomException? error) {
      decodeError = error;
      // Safari has a bug where it may return null for the error callback. In
      // the case where the Safari version still returns a `Promise` and the
      // error is not null after the `Promise` is finished, the error callback
      // is called instead in the `Promise`'s `catch` block. Otherwise, and in
      // the case where a `Promise` is not returned by the API at all, the
      // callback never gets called (for backwards compatibility, it can not
      // accept null). Instead, the `Future` completes with a custom string as
      // the error, indicating that null was given.
      // https://github.com/mdn/webaudio-examples/issues/5
      if (error != null) errorCallback?.call(error);
    }

    var nullErrorString =
        '[AudioContext.decodeAudioData] completed with a null error.';

    var decodeResult = JS("creates:AudioBuffer;", "#.decodeAudioData(#, #, #)",
        this, audioData, allowInterop(success), allowInterop(error));

    if (decodeResult != null) {
      // Promise-based syntax.
      return promiseToFuture<AudioBuffer>(decodeResult).catchError((error) {
        // If the error was null in the callback, but no longer is now that the
        // `Promise` is finished, call the error callback. If it's still null,
        // throw the error string.
        if (decodeError == null) {
          if (error != null) {
            errorCallback?.call(error);
          } else {
            throw nullErrorString;
          }
        }
        throw error;
      });
    }
    // Callback-based syntax. Note that with this syntax, the call to
    // `decodeAudioData` is blocking, so there is nothing to `await`. Using the
    // `Completer` within the callbacks we provide to the function leads to
    // unexpected errors within the browser, so we just `complete` with either
    // the resulting `AudioBuffer` or `DomException` (if not null).
    var completer = Completer<AudioBuffer>();
    if (decodedBuffer != null) {
      completer.complete(decodedBuffer);
    } else {
      completer.completeError(decodeError ?? nullErrorString);
    }
    return completer.future;
  }
```

</details>

**Comment by AndrewLugg** [comment]
I am happy to try and test it, but I am unsure how I can do that being an internal library without compiling the SDK.

**Comment by srujzs** [comment]
Ah, I didn't realize you can't test with recompilation. I toyed around with the code logic to see if the callback-based syntax would give us the expected behavior, and I think it does. I just submitted a CL fixing this API, it should flow into a dev release soon. If it's possible for you to try a dev release, let me know if this resolves the issue. If not, feel free to reopen. Thank you!

**Comment by AndrewLugg** [comment]
I was able to test this on the current dev branch (2.17.0-169.0.dev) and there is a new error that is now showing.

![image](https://user-images.githubusercontent.com/19848590/157780224-3b57bc78-3f14-4410-9dd0-b582432aaac7.png)

Also this error is not fixed by turning off "sound_null_saftey" so it now breaks all older versions of safari.

Versions tested with:
Safari 15.3  - Works
Safari 14.1  - Works
Safari 13.1  - Breaks
Safari 12.1  - Breaks

**Comment by srujzs** [comment]
That's unfortunate, can you share the compiler output as well? Judging from the error (where the call to `decodeAudioData` doesn't have enough arguments), I'm assuming this is because a `successCallback` is not passed? In that case, the code assumes it can be called with only 1 argument (the buffer). In your case, if you want to support older Safari versions, I think you'd need to always pass callbacks to be consistent.

I'll try to see if I can use BrowserStack if there are still issues.

**Comment by AndrewLugg** [comment]
Is this what you are after?
![image](https://user-images.githubusercontent.com/19848590/157784414-6aa76d40-818b-410f-b711-30619153af33.png)

I can zip up the project I am using for testing with compiled code if that would help. Its just a barebones test project.

**Comment by srujzs** [comment]
Yup, and sure, from that I'm assuming the Dart API is being called as `decodeAudioData(<buffer>)`. Can you change the calling code to include non-null `successCallback` and `errorCallback`s?

**Comment by AndrewLugg** [comment]
So swapping to the callbacks does fix the issue with the decodeAudioData, and my original code works now, but if try to play the audio it fails on that instead.

![image](https://user-images.githubusercontent.com/19848590/158084406-bf1e65e1-52b8-426d-9770-b975938fdbb2.png)

Here is my simple testing script, with the callback changes, you will see it works with null-safety false, but it fails with it set to true.
[web_audio_null_safety.zip](https://github.com/dart-lang/sdk/files/8240855/web_audio_null_safety.zip)

**Comment by srujzs** [comment]
Running with `2.17`, I'm unfortunately not seeing the issue reproduce. I'm using the `run.sh` script and loading `index.html`. I can hear the audio fine with and without the null-safety option enabled in the pubspec on the latest versions of Chrome, Firefox, and Safari. Judging from what you've mentioned, I'm assuming this is because a native null assertion is being triggered somewhere, but I can't tell without more information. Can I have you share the output along with the stack trace (preferably unminified, I believe the flag `--no-minify` should do that)?

**Comment by AndrewLugg** [comment]
Are you running it on older version of Safari I was testing it on Safari 10.1?

It works fine in the latest version of Safari, Chrome.

**Comment by srujzs** [comment]
Yup, just uploaded a CL for review changing it to be nullable. Will report back once it's landed.

**Comment by srujzs** [comment]
FYI - https://github.com/dart-lang/sdk/commit/a16bd37ed23fd5419785f40b21e97893f86a42dd has landed

In the next day or so, there should be a dev version available with this CL. You can find the dev version by looking at the tags of the above commit once it's been added. Let me know if this resolve the issue, thanks!

**Comment by AndrewLugg** [comment]
I have just tested this with 2.17.0-246.0.dev on Safari version 10.1 with Null-safety on, and confirm that you can now play audio on old versions Safari.

There is a another null-safety issue with setValueAtTime on GainNode, but that is a minor inconvenience. And also only occurs on old safari.

Thank you for fixing it.
