### ISSUE TITLE
flutter-analyze buildbot must match flutter engine's analyze builtbot

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#47527]
Recently the Engine -> Framework roll failed because of various analysis errors in various Flutter-interested code [1]. With the Dart SDK's [flutter-analyze buildbot](https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-analyze), this should have been caught in the Dart SDK's postsubmit queue.

The flutter-analyze buildbot appears to only analyze:

* flutter/engine
* flutter/flutter
* flutter/plugins

This list presumably falls short. Flutter's gallery is in a separate repository from these (flutter/gallery). It is unclear how analysis in `dev/benchmarks` and `dev/integration_tests` is clean on Dart SDK's flutter-analyze, but fails in Flutter's "Linux analyze" bot.

[1]
https://github.com/flutter/flutter/issues/92181

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20customer_testing/23466/overview

```
Processing ./../../bin/cache/pkg/tests/registry/flutter_gallery.test...
>> flutter analyze --no-fatal-infos
| Analyzing tests...
|
|    info • 'brightness' is deprecated and shouldn't be used. This property is no longer used, please use systemOverlayStyle instead. This feature was deprecated after v2.4.0-0.0.pre. • lib/themes/gallery_theme_data.dart:29:9 • deprecated_member_use
|   error • The argument for the named parameter 'toolbarTextStyle' was already specified • lib/themes/gallery_theme_data.dart:29:203 • duplicate_named_argument
|   error • The argument for the named parameter 'titleTextStyle' was already specified • lib/themes/gallery_theme_data.dart:29:283 • duplicate_named_argument
|
| 3 issues found. (ran in 8.6s)
Processing ./../../bin/cache/pkg/tests/registry/flutter_gallery.test...
ERROR: One or more tests from flutter_gallery failed.
```

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/24427/overview

```
▌13:12:07▐ RUNNING: cd .; bin/flutter analyze --flutter-repo
Analyzing 3 directories...                                      


  error • Missing type arguments for generic function 'callMethod<T>' • dev/benchmarks/macrobenchmarks/lib/src/web/bench_text_layout.dart:78:11 • implicit_dynamic_function
  error • Missing type arguments for generic function 'getProperty<T>' • dev/integration_tests/web_e2e_tests/test_driver/text_editing_integration.dart:240:42 • implicit_dynamic_function
  error • Missing type arguments for generic function 'callConstructor<T>' • dev/integration_tests/web_e2e_tests/test_driver/text_editing_integration.dart:246:39 • implicit_dynamic_function

3 issues found. (ran in 148.4s)
```

CC @athomas @zanderso @a-siva @devoncarew

**Comment by devoncarew** [comment]
I suspect what happened in this recent case was that:
- the breaking change was to a dart: library
- we check the flutter repo by running `flutter analyze --flutter-repo --dart-sdk <path/to/dart/sdk/from/head>`
- that runs the analysis server, but I believe that is uses the dart sdk definition from `<flutter-sdk>/bin/cache/pkg/sky_engine` to know what the dart: libraries are

So we don't get the new dart: changes from the breaking change. That vended version of the dart: libraries - the sky_engine stuff - is built on the fluter/engine bot. It's all pretty add-hoc - stitching together a variant of the dart: libraries - and likely isn't logic we'll want to copy into the flutter-analyzer bot.

**Comment by srawlins** [comment]
Thanks @devoncarew yeah that sounds tricky to fix.

I think it shouldn't be hard to at least add flutter_gallery to the bot.
