### ISSUE TITLE
[Analyzer] No quick-fix for `required` + `default value` on named parameters

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#47540]
I wish Dart had a quick-fix for the following scenario:

> Required named parameters can't have a default value. 
> Try removing either the default value or the 'required' modifier.

```dart
class MyExample {
  final int value;

  MyExample({
    required this.value = 1, // Required named parameters can't have a default value.
  });
}
```

Expected: either remove the default value or remove the 'required'.

Personally, I think we should remove the default value, as that is much harder for the developer to remove by hand. With 'required' you just search for all usages and replace with '', or use multi-cursor and it works. That is a lot thicker for default values.

I would also want to see a 'multi-fix' for this quick-fix, as I was refactoring a class and there are dozens of lines I need to manually fix.

**Comment by asashour** [comment]
I would like to know, how a developer would have multiple offending places, where both required and default value happened. Is it with "multi-cursor", where many parameters in a single file are changed at once? And if yes, is it something usual?

Another point, it could be controversial which one to remove (required or parameter), and each situation could need different handling, which would make multi-fix not a good choice, I think.

**Comment by bwilkerson** [comment]
> Another point, it could be controversial which one to remove (`required` or `default value`), and each situation could need different handling, which would make multi-fix not a good choice, I think.

We should offer both as quick fixes, and we should consider (though I'm not completely sold on the idea) enabling both for fix-all-in-file mode. I wouldn't enable either one for bulk-fix mode.

**Comment by asashour** [comment]
`RemoveRequired` in [sdk/251761](https://dart-review.googlesource.com/c/sdk/+/251761)

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/251940
