### ISSUE TITLE
replacement in deprecated 

### ISSUE THREAD

**Issue by EhsanAramide** [dart-lang/sdk#47554]
I searched about similar issues but I didn't find anything if this is duplicated let me know.
Currently for deprecating an API we use this:
```dart
@Deprecated('This is deprecated')
void forExample(String name) {
  print('this is just a name => $name');
}
// and we will get warning if we use
void main(List<String> args) {
  forExample('name');
}
```
![Screenshot from 2021-10-26 21-00-43](https://user-images.githubusercontent.com/72789505/138930680-6b4e8455-9ac7-4fc9-a1a7-9e4587a8c584.png)

**what is your idea about adding a new optional field (to avoid making break change) for replacement in code fix? (which this field can be a list of associated elements for example if the deprecated API is a function all of them should be a function)**
For example, we can do this:
```dart
@Deprecated('This is deprecated', replaceWith: [forSomeFunction, forThisFunction])
void forExample(String name) { // ...
// or in other elements like typedefs, classes, primitive types (String, int, bool)
@Deprecated('This is deprecated', replaceWith: SomeType)
class AType { // ...
```
and then when we use
```dart
void main(List<String> args) {
  // analyzer_code_fix: `forExample` is deprecated instead use `forSomeFunction` and `forThisFunction`
  forExample('name');
  // and in code fix list we will get `replace with forSomeFunction` and `replace with forThisFunction`
}
```

**Comment by srawlins** [comment]
@bwilkerson has looked into this previously. Not sure if there is an existing issue or an existing design.

**Comment by bwilkerson** [comment]
We did look into using information in the `deprecated` annotation, but a number of issues (including the fact that the information disappears when the deprecated declaration is deleted) caused us to rethink the problem.

We have an alternative that we explored that allows package authors to provide this kind of support to clients of their APIs. The Flutter team has used it and seems to have had reasonable success, but we have not yet made a decision about whether to support the technology longer term, so at the moment it's in an unsupported and use-at-your-own-risk state.

If you're interested you can read about it here: https://github.com/flutter/flutter/wiki/Data-driven-Fixes.
