### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by deeppatel8259** [dart-lang/sdk#47550]
## Version information

- `IDEA AI-203.7717.56.2031.7784292`
- `2.14.0`
- `AI-203.7717.56.2031.7784292, JRE 11.0.10+0-b96-7249189x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366.0x768.0`

**Comment by srawlins** [comment]
Please re-open if you see this problem again.
