### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0 at offset 5157 in ...utils.dart (crc >> 8)

### ISSUE THREAD

**Issue by insinfo** [dart-lang/sdk#47555]
RangeError (index): Invalid value: Valid value range is empty: 0 at offset 5157 in C:\MyDartProjects\appjazz\flutter_advanced_networkimage\lib\src\utils.dart (crc >> 8)

PS C:\MyDartProjects\appjazz\flutter_advanced_networkimage> dart migrate
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to anonymously report feature usage    ║
  ║ statistics and to send basic crash reports. This data is used to help      ║
  ║ improve the Dart platform and tools over time.                             ║
  ║                                                                            ║
  ║ To disable reporting of anonymous analytics, run:                          ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Migrating C:\MyDartProjects\appjazz\flutter_advanced_networkimage

See https://dart.dev/go/null-safety-migration for a migration guide.

Note: more than one project found; migrating the top-level project.

Analyzing project...
[--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|]No analysis issues found.

Generating migration suggestions...
[-----------------------------------------------------------------                                                                                                                                                          ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.12.4) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

RangeError (index): Invalid value: Valid value range is empty: 0 at offset 5157 in C:\MyDartProjects\appjazz\flutter_advanced_networkimage\lib\src\utils.dart (crc >> 8)

#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:517:61)
#2      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:967:49)
#3      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#4      EdgeBuilder.visitParenthesizedExpression (package:nnbd_migration/src/edge_builder.dart:1358:18)
#5      ParenthesizedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7964:15)
#6      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#7      EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#8      EdgeBuilder.visitBinaryExpression (package:nnbd_migration/src/edge_builder.dart:516:9)
#9      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:967:49)
#10     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#11     EdgeBuilder._handleAssignment (package:nnbd_migration/src/edge_builder.dart:2329:20)
#12     EdgeBuilder.visitAssignmentExpression (package:nnbd_migration/src/edge_builder.dart:409:26)
#13     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:715:49)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15     EdgeBuilder.visitExpressionStatement (package:nnbd_migration/src/edge_builder.dart:801:25)
#16     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3676:49)
#17     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#18     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#19     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#20     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#22     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#23     EdgeBuilder.visitForStatement.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:854:55)
#24     EdgeBuilder._handleForLoopParts.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:2772:18)
#25     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#26     EdgeBuilder._handleForLoopParts (package:nnbd_migration/src/edge_builder.dart:2771:26)
#27     EdgeBuilder.visitForStatement (package:nnbd_migration/src/edge_builder.dart:853:5)
#28     ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4707:49)
#29     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#30     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#31     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:517:39)
#32     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#33     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#34     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#35     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#36     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:324:45)
#37     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#38     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#39     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#40     EdgeBuilder.visitFunctionExpression.<anonymous closure> (package:nnbd_migration/src/edge_builder.dart:937:25)
#41     ScopedSet.doScoped (package:nnbd_migration/src/utilities/scoped_set.dart:44:13)
#42     EdgeBuilder.visitFunctionExpression (package:nnbd_migration/src/edge_builder.dart:935:28)
#43     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5004:49)
#44     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#45     EdgeBuilder.visitFunctionDeclaration (package:nnbd_migration/src/edge_builder.dart:886:9)
<asynchronous suspension>
#61     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#62     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#63     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#64     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#65     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

failed on migrate this

```dart
/// Calculate crc32 checksum
///
/// crc table generator:
/// ```dart
/// List<String> createCRCTable() {
///   List<String> result = List<String>(256);
///   for (int i = 0; i <= 255; i++) {
///     int rem = i;
///     for (int j = 0; j <= 7; j++) {
///       rem = (rem & 1) > 0 ? (rem >> 1) ^ 0xedb88320 : rem >> 1;
///     }
///     result[i] = '0x' + rem.toRadixString(16).padLeft(8, '0');
///   }
///   return result;
/// }
/// ```
int crc32(List<int> bytes) {
  const List<int> crcTable = const [
    0x00000000,
    0x77073096,
    0xee0e612c,
    0x990951ba,
    0x076dc419,
    0x706af48f,
    0xe963a535,
    0x9e6495a3,
    0x0edb8832,
    0x79dcb8a4,
    0xe0d5e91e,
    0x97d2d988,
    0x09b64c2b,
    0x7eb17cbd,
    0xe7b82d07,
    0x90bf1d91,
    0x1db71064,
    0x6ab020f2,
    0xf3b97148,
    0x84be41de,
    0x1adad47d,
    0x6ddde4eb,
    0xf4d4b551,
    0x83d385c7,
    0x136c9856,
    0x646ba8c0,
    0xfd62f97a,
    0x8a65c9ec,
    0x14015c4f,
    0x63066cd9,
    0xfa0f3d63,
    0x8d080df5,
    0x3b6e20c8,
    0x4c69105e,
    0xd56041e4,
    0xa2677172,
    0x3c03e4d1,
    0x4b04d447,
    0xd20d85fd,
    0xa50ab56b,
    0x35b5a8fa,
    0x42b2986c,
    0xdbbbc9d6,
    0xacbcf940,
    0x32d86ce3,
    0x45df5c75,
    0xdcd60dcf,
    0xabd13d59,
    0x26d930ac,
    0x51de003a,
    0xc8d75180,
    0xbfd06116,
    0x21b4f4b5,
    0x56b3c423,
    0xcfba9599,
    0xb8bda50f,
    0x2802b89e,
    0x5f058808,
    0xc60cd9b2,
    0xb10be924,
    0x2f6f7c87,
    0x58684c11,
    0xc1611dab,
    0xb6662d3d,
    0x76dc4190,
    0x01db7106,
    0x98d220bc,
    0xefd5102a,
    0x71b18589,
    0x06b6b51f,
    0x9fbfe4a5,
    0xe8b8d433,
    0x7807c9a2,
    0x0f00f934,
    0x9609a88e,
    0xe10e9818,
    0x7f6a0dbb,
    0x086d3d2d,
    0x91646c97,
    0xe6635c01,
    0x6b6b51f4,
    0x1c6c6162,
    0x856530d8,
    0xf262004e,
    0x6c0695ed,
    0x1b01a57b,
    0x8208f4c1,
    0xf50fc457,
    0x65b0d9c6,
    0x12b7e950,
    0x8bbeb8ea,
    0xfcb9887c,
    0x62dd1ddf,
    0x15da2d49,
    0x8cd37cf3,
    0xfbd44c65,
    0x4db26158,
    0x3ab551ce,
    0xa3bc0074,
    0xd4bb30e2,
    0x4adfa541,
    0x3dd895d7,
    0xa4d1c46d,
    0xd3d6f4fb,
    0x4369e96a,
    0x346ed9fc,
    0xad678846,
    0xda60b8d0,
    0x44042d73,
    0x33031de5,
    0xaa0a4c5f,
    0xdd0d7cc9,
    0x5005713c,
    0x270241aa,
    0xbe0b1010,
    0xc90c2086,
    0x5768b525,
    0x206f85b3,
    0xb966d409,
    0xce61e49f,
    0x5edef90e,
    0x29d9c998,
    0xb0d09822,
    0xc7d7a8b4,
    0x59b33d17,
    0x2eb40d81,
    0xb7bd5c3b,
    0xc0ba6cad,
    0xedb88320,
    0x9abfb3b6,
    0x03b6e20c,
    0x74b1d29a,
    0xead54739,
    0x9dd277af,
    0x04db2615,
    0x73dc1683,
    0xe3630b12,
    0x94643b84,
    0x0d6d6a3e,
    0x7a6a5aa8,
    0xe40ecf0b,
    0x9309ff9d,
    0x0a00ae27,
    0x7d079eb1,
    0xf00f9344,
    0x8708a3d2,
    0x1e01f268,
    0x6906c2fe,
    0xf762575d,
    0x806567cb,
    0x196c3671,
    0x6e6b06e7,
    0xfed41b76,
    0x89d32be0,
    0x10da7a5a,
    0x67dd4acc,
    0xf9b9df6f,
    0x8ebeeff9,
    0x17b7be43,
    0x60b08ed5,
    0xd6d6a3e8,
    0xa1d1937e,
    0x38d8c2c4,
    0x4fdff252,
    0xd1bb67f1,
    0xa6bc5767,
    0x3fb506dd,
    0x48b2364b,
    0xd80d2bda,
    0xaf0a1b4c,
    0x36034af6,
    0x41047a60,
    0xdf60efc3,
    0xa867df55,
    0x316e8eef,
    0x4669be79,
    0xcb61b38c,
    0xbc66831a,
    0x256fd2a0,
    0x5268e236,
    0xcc0c7795,
    0xbb0b4703,
    0x220216b9,
    0x5505262f,
    0xc5ba3bbe,
    0xb2bd0b28,
    0x2bb45a92,
    0x5cb36a04,
    0xc2d7ffa7,
    0xb5d0cf31,
    0x2cd99e8b,
    0x5bdeae1d,
    0x9b64c2b0,
    0xec63f226,
    0x756aa39c,
    0x026d930a,
    0x9c0906a9,
    0xeb0e363f,
    0x72076785,
    0x05005713,
    0x95bf4a82,
    0xe2b87a14,
    0x7bb12bae,
    0x0cb61b38,
    0x92d28e9b,
    0xe5d5be0d,
    0x7cdcefb7,
    0x0bdbdf21,
    0x86d3d2d4,
    0xf1d4e242,
    0x68ddb3f8,
    0x1fda836e,
    0x81be16cd,
    0xf6b9265b,
    0x6fb077e1,
    0x18b74777,
    0x88085ae6,
    0xff0f6a70,
    0x66063bca,
    0x11010b5c,
    0x8f659eff,
    0xf862ae69,
    0x616bffd3,
    0x166ccf45,
    0xa00ae278,
    0xd70dd2ee,
    0x4e048354,
    0x3903b3c2,
    0xa7672661,
    0xd06016f7,
    0x4969474d,
    0x3e6e77db,
    0xaed16a4a,
    0xd9d65adc,
    0x40df0b66,
    0x37d83bf0,
    0xa9bcae53,
    0xdebb9ec5,
    0x47b2cf7f,
    0x30b5ffe9,
    0xbdbdf21c,
    0xcabac28a,
    0x53b39330,
    0x24b4a3a6,
    0xbad03605,
    0xcdd70693,
    0x54de5729,
    0x23d967bf,
    0xb3667a2e,
    0xc4614ab8,
    0x5d681b02,
    0x2a6f2b94,
    0xb40bbe37,
    0xc30c8ea1,
    0x5a05df1b,
    0x2d02ef8d,
  ];

  int crc = 0xffffffff;

  for (int byte in bytes) {
    crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >> 8);
  }

  return crc ^ 0xffffffff;
}
```
https://github.com/insinfo/flutter_advanced_networkimage

 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on Microsoft Windows [versÃ£o 10.0.22000.258], locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (4 available)

• No issues found!

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
