### ISSUE TITLE
.DS_Store shows up in import suggestions on Mac

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#47562]
I have a Flutter project on my machine. Let's say is it called `myproject`.

When typing an import manually the suggestions include `package:myproject/.DS_Store`. 

`.DS_Store` is metadata related stuff and should probably not show up in those suggestions?
It is included in the gitignore of the project.

```
Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "macos_x64"
Visual Studio Code version: 1.61.2
Dart Plugin version: v3.27.2
Flutter plugin version: v3.27.0
```

**Comment by srawlins** [comment]
I cannot reproduce this, but I'm unaware of any work done in the analyzer recently that would address this...

**Comment by srawlins** [comment]
@scheglov @bwilkerson are you aware of anything that would have fixed this in the last 18 months (It's a big question, haha, just checking).

@navaronbracke does this still occur in a recent version of Dart? Like 2.19?

**Comment by navaronbracke** [comment]
I just checked with Dart 2.19.6 and I cannot reproduce it anymore either.

**Comment by scheglov** [comment]
Well, I don't know why it does not work for you, because I can reproduce it in a unit test.
```dart
  Future<void> test_uri_end() async {
    newFile('$testPackageLibPath/.DS_Store', '');

    await _checkDirectives(
      uriContent: '^',
      validator: () {
        assertResponse(r'''
suggestions
  dart:
    kind: import
  dart:async
    kind: import
  dart:async2
    kind: import
  dart:collection
    kind: import
  dart:convert
    kind: import
  dart:core
    kind: import
  dart:ffi
    kind: import
  dart:html
    kind: import
  dart:io
    kind: import
  dart:isolate
    kind: import
  dart:math
    kind: import
  package:
    kind: import
  package:bar/
    kind: import
  package:bar/bar01.dart
    kind: import
  package:foo/
    kind: import
  package:foo/foo01.dart
    kind: import
  package:foo/foo02.dart
    kind: import
  package:foo/foo11.dart
    kind: import
  package:test/
    kind: import
  package:test/.DS_Store
    kind: import
  package:test/test.dart
    kind: import
''');
      },
    );
  }
```

**Comment by srawlins** [comment]
Oh so it's very possible that VS Code does some filtering.

I imagine we should still filter out... any files that don't end in `.dart`? Any downsides to that?

**Comment by scheglov** [comment]
Nope, even though it is theoretically possible to import any file, it does not have to be named `.dart`, it is not reasonable thing to do. So, I think we should apply such filter.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/296442
