### ISSUE TITLE
Do serial GC when CPU contention is high

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#47575]
If possible, detect when there are high amounts of scheduling contention and do a serial GC rather than a multi-threaded GC.

This would avoid wasted time on waiting for a parallel thread to get scheduled in a resource-limited environment, but also avoid forcing serial GC in all instances even when contention is otherwise low.

It's not clear to me if this is really possible or not, but @rmacnak-google says that Ninja might do something similar.

/cc @a-siva

**Comment by rmacnak-google** [comment]
A possible implementation: https://dart-review.googlesource.com/c/sdk/+/218788. A potential issue is the notion of busy comes from a trailing one-minute window since that's what's available.

**Comment by rmacnak-google** [comment]
The engine increased the priority of the UI thread instead.
