### ISSUE TITLE
Kythe implementation for named arguments anywhere

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47579]
See #47451 for the meta issue and dart-lang/language#1072 for the language issue.

**Comment by leafpetersen** [comment]
FYI, the flag has been flipped so these can be used without a flag internally now.

**Comment by leafpetersen** [comment]
@emmanuel-p do you have a status on this?

**Comment by emmanuel-p** [comment]
Basic support is implemented.
Some improvements are planned.
Tracked internally by b/225119276.
