### ISSUE TITLE
Pre-allocate new space to avoid lengthy scavenges during initialization

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#47573]
If an application knows from training runs on a given architecture how much new space it will need during initialization, it should be allowed to supply that and have the VM more eagerly allocate it rather than lazily allocating new space during a scavenge.

This could reduce the amount of time spent in uninterruptible sleep due to IO during a scavenge.

/cc @rmacnak-google @a-siva

**Comment by a-siva** [comment]
Not sure how effective this is going to be.

We have a page_cache which is empty initially, one way to eagerly allocate would be to use the parameter --new_gen_semi_initial_size which is by default set to 1MB on 32 bit systems and 2 MB on 64 bit systems as a guide for prepopulating the new gen page cache. This eager allocation would have to be done during VM initialization which would mean this uninterruptible sleep that we see in Scavenge now will move over to initialization phase and we would see the same stalls. Another option could be to start the prepopulation on a worker thread which might run into CPU contention.
