### ISSUE TITLE
No error in analyzer when 'super' is accessed in a field initializer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#47584]
The following code produces an error in CFE but has no issues in analyzer
```dart
class S {
  int s1;
  S(this.s1);
}

class C extends S {
  int i;
  C(this.i) : super(super.s1); // CFE Error: Can't access 'super' in a field initializer.
}

main() {
  C(42);
}
```
There must be an error in the analyzer as well

Tested on `Dart SDK version: 2.15.0-257.0.dev (dev) (Tue Oct 26 14:16:53 2021 -0700) on "windows_x64" `

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/218787
