### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by nitunga** [dart-lang/sdk#47582]
## Version information

- `IDEA AI-203.7717.56.2031.7678000`
- `2.14.4`
- `AI-203.7717.56.2031.7678000, JRE 11.0.10+0-b96-7249189x64 JetBrains s.r.o., OS Linux(amd64) v5.11.0-38-generic, screens 1600.0x900.0`

**Comment by devoncarew** [comment]
cc @jwren - see my comment in the other recent closed feedback bug
