### ISSUE TITLE
Dart fix should change "return" to "continue" when changing "forEach" to "for in"

### ISSUE THREAD

**Issue by cthurston** [dart-lang/sdk#47581]
## Use case

Code has this pattern:

```dart
myList.forEach((obj){
  if(obj == 'whatever') return;
  // Do something else
})
```

After dart fix:

```dart
for(var obj in myList) {
  if(obj == 'whatever') return;
  // Do something else
})
```
## Proposal
After dart fix should be:

```dart
for(var obj in myList) {
  if(obj == 'whatever') continue;
  // Do something else
})
```

**Comment by bernaferrari** [comment]
I don't like this because it doesn't seem the same. The same would be a goto with a label which is not a good pattern. I think the current way is fine.

**Comment by cthurston** [comment]
Should it throw a warning because it changes the intent/functionality of the code?

**Comment by bernaferrari** [comment]
Then you are modifying the users code, what if there is already a comment?

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/239304

**Comment by bwilkerson** [comment]
> I don't like this because it doesn't seem the same. The same would be a goto with a label which is not a good pattern.

Could you elaborate on why this doesn't seem appropriate? As far as I can see, the current behavior unintentionally changes the semantics of the code while the proposed change preserves the original semantics. (It also seems to me that a `continue` _is_ a goto, but with an implicit label.)

**Comment by bernaferrari** [comment]
I don't remember what I was thinking, I guess the change is fine  :)
