### ISSUE TITLE
Angular compiler implementation for named arguments anywhere 

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47591]
See #47451 for the meta issue and dart-lang/language#1072 for the language issue.

**Comment by devoncarew** [comment]
> What's the timeline for this work?

We're trying to figure it out now. We're just setting up the tracking mechanisms (meta issue, github project, ...). Once we have those and have very rough estimates for the impl. costs for the various tools we could figure out when it might ship.

The tldr is that it's available to be implemented but that we don't know when it might ship.

**Comment by devoncarew** [comment]
Internal issue: b/209865431

cc @leonsenft

**Comment by leafpetersen** [comment]
FYI, the flag has been flipped so these can be used without a flag internally now.

**Comment by leafpetersen** [comment]
Is this actually done?  The internal issue is still open.

**Comment by mattrberry** [comment]
The internal bug has just been wrapped up. All set to close this issue now.

**Comment by leafpetersen** [comment]
Thanks!
