### ISSUE TITLE
Segfault when profiling ffi functions with `isLeaf: true`

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#47594]
I can reproduce this on stable (`2.14.4`) and dev (`2.15.0-257.0.dev`), I'm on `Linux 5.14.10-1`.

When using the profiler from the observatory with ffi-functions marked as leaf, the VM crashes. Here's a sample program to reproduce this (I can find a more minimal repro if needed):

```dart
import 'dart:ffi';

import 'package:ffi/ffi.dart';

typedef _strerror_native = Pointer<Utf8> Function(Int32);
typedef _strerror_dart = Pointer<Utf8> Function(int);

void main() {
  final lib = DynamicLibrary.process();
  final strerror = lib.lookupFunction<_strerror_native, _strerror_dart>(
    'strerror',
    isLeaf: true, // Note that the error does not happen with isLeaf: false
  );

  for (var i = 0; i < 10000; i++) {
    strerror(0).toDartString();
  }
}
```

This can be reproduced by running

1. `dart run --enable-vm-service --pause-isolates-on-start repro.dart`
2. Enabling the profiler in the observatory
3. Continuing the main isolate in the observatory debugger

The crash is as follows:

```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7
version=2.15.0-257.0.dev (dev) (Tue Oct 26 14:16:53 2021 -0700) on "linux_x64"
pid=26324, thread=26499, isolate_group=main(0x56458ed2d000), isolate=main(0x56458edb5800)
isolate_instructions=56458d64b140, vm_instructions=56458d64b140
  pc 0x000056458d8ab101 fp 0x00007f0119bfdd20 /home/simon/bin/dart-sdk/dev/bin/dart+0x201f101
  pc 0x000056458d8ab778 fp 0x00007f0119bfde50 dart::Profiler::SampleThread(dart::Thread*, dart::InterruptedThreadState const&)+0x398
  pc 0x000056458d926c16 fp 0x00007f0119bfdfb0 /home/simon/bin/dart-sdk/dev/bin/dart+0x209ac16
  pc 0x00007f0125db8870 fp 0x00007f0119bfe690 /usr/lib/libpthread.so.0+0x13870
-- End of DumpStackTrace
```

(I also noticed strange behavior inside of native functions when profiling, but that may as well be my fault and I don't have a simple repro)

**Comment by rmacnak-google** [comment]
It looks like FFI neglects to update Thread::vm_tag/exit_fp for leaf function calls, causing the profiler to misinterpret a C frame as a Dart frame.

**Comment by dcharkes** [comment]
cc @cskau-g If you want to take a look at this, go ahead, otherwise I can do it.
