### ISSUE TITLE
Make `.stat()` resolve symlinks on Windows

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#47597]
# Change

Make `FileStat.stat()` and `FileSystemEntity.stat()` resolve symbolic links before returning their results on Windows.

#  Rationale

Other platforms already do this and the [documentation already says (for `File`) that symlinks are resolved](https://api.dart.dev/stable/2.14.4/dart-io/File-class.html). This would fix a platform inconsistency.

# Impact

Likely to be low as, AFAIK, symlinks are not heavily used on Windows.

# Mitigation

None currently. AFAIK, Dart currently has no mechanism for executing `stat()` on a symlink. I plan on changing this as part of https://github.com/dart-lang/sdk/issues/20389.

Note: I was unaware of the breaking change process and [already made the change](https://github.com/dart-lang/sdk/commit/5e990591b9504c168d94de964560765633608ced). I can revert it if needed.

**Comment by devoncarew** [comment]
I can track down approvals (as per https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md#step-2-approval). However, I wonder if we should just consider this a bug fix, esp. as the docs indicate that we already do this.

cc @a-siva

**Comment by a-siva** [comment]
I agree this looks more like a bug fix for the Windows platform.

**Comment by devoncarew** [comment]
@brianquinlan, I'm going to close this as something we can consider a bug fix - not something that we need to track through the breaking change process. Thanks!
