### ISSUE TITLE
Use of 'super' in dart2js output breaks in Android browser

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#4759]
Approximately 80% of all android web users use the Android browser (not the Chrome for Android browser). See http://developer.android.com/about/dashboards/index.html

dart2js emits code that uses the word 'super'. This has caused at least two problems.

First:

The minifier that's part of the new MVC4 bundling stuff fails with &quot;run-time warning JS1028: Expected identifier or string: super&quot; while trying to minify the dart output below: 

$$._PendingSendPortFinder = {&quot;&quot;:
&nbsp;[&quot;ports?&quot;, &quot;_visited&quot;],
&nbsp;super: &quot;_MessageTraverser&quot;, //&lt;--- this line specifically
&nbsp;visitSendPort$1: function(port) {
&nbsp;&nbsp;if (typeof port &equals;&equals;&equals; 'object' &amp;&amp; port !== null &amp;&amp; !!port.is$_BufferingSendPort &amp;&amp; port.get$_port() == null)
&nbsp;&nbsp;&nbsp;&nbsp;$.add$1(this.ports, port.get$_futurePort());

See this thread for more: https://groups.google.com/a/dartlang.org/forum/?fromgroups#!topic/misc/wVQ6Mi1dWtU

(luckily in this case, MVC4 was updated and fixed the issue)

Second:

I get a syntax error on line 8 and this is what the generated code (from hi.dart in sample code) looks like:

function Isolate() {}
init();

var $$ = {};
var $ = Isolate.$isolateProperties;
$$.ExceptionImplementation = {&quot;&quot;:
&nbsp;[&quot;_msg&quot;],
&nbsp;super: &quot;Object&quot;,
&nbsp;toString$0: function() {
&nbsp;&nbsp;var t1 = this._msg;
&nbsp;&nbsp;return t1 == null ? 'Exception' : 'Exception: ' + $.S(t1);
},
&nbsp;is$Exception: true

A patch was submitted (note: the ++ and -- are reversed here) which claims to fix the issue:

--- lib/dart2js/lib/compiler/implementation/js_backend/emitter.dart	2012-08-27 18:47:33.152927918 -0700
+++ lib/dart2js/lib/compiler/implementation/js_backend/emitter.dart~	2012-08-27 16:30:30.881870773 -0700
@@ -166,7 +166,7 @­@
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (Object.prototype.hasOwnProperty.call(collectedClasses, cls)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var desc = collectedClasses[cls];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$isolatePropertiesName[cls] = $defineClassName(cls, desc[''], desc);
-      if (desc['superduper'] !== &quot;&quot;) $pendingClassesName[cls] = desc['superduper'];
+      if (desc['super'] !== &quot;&quot;) $pendingClassesName[cls] = desc['super'];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;var pendingClasses = $pendingClassesName;
@@ -197,7 +197,7 @­@
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hosOwnProperty instead. \*/'''
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var hasOwnProperty = Object.prototype.hasOwnProperty;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for (var member in prototype) {
-        if (member == '' || member == 'superduper') continue;
+        if (member == '' || member == 'super') continue;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (hasOwnProperty.call(prototype, member)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;newPrototype[member] = prototype[member];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
@@ -567,7 +567,7 @­@
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// TODO(floitsch): the emitInstanceMember should simply always emit a ',\n'.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// That does currently not work because the native classes have a different
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// syntax.
-    buffer.add(' superduper: &quot;$superName&quot;');
+    buffer.add(' super: &quot;$superName&quot;');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;emitInstanceMembers(classElement, buffer, true);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer.add('\n};\n\n');
&nbsp;&nbsp;&nbsp;}
@@ -746,7 +746,7 @­@
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;boundClosureBuffer.add(&quot;&quot;&quot;
&nbsp;$classesCollector.$mangledName = {'':
&nbsp;&nbsp;['self', 'target'],
- 'superduper': '$superName',
+ 'super': '$superName',
&nbsp;&quot;&quot;&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// Now add the methods on the closure class. The instance method does not
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// have the correct name. Since [addParameterStubs] use the name to create

See this thread for more: https://groups.google.com/a/dartlang.org/forum/#!topic/misc/hj8iL89-Wdg

**Comment by sigmundch** [comment]
I believe this is currently working - dart2js output no longer has `.super`. I couldn't find when exactly it was fixed, though.
