### ISSUE TITLE
Enable toggling of timeline streams using a Dart C API method (to be used in release builds)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#47601]
Add a new Dart C API method that allows toggling of the following timeline streams in the VM

    V(API, "dart:api") 
    V(Compiler, "dart:compiler")
    V(CompilerVerbose, "dart:compiler.verbose")
    V(Dart, "dart:dart")
    V(Debugger, "dart:debugger")
    V(Embedder, "dart:embedder")
    V(GC, "dart:gc")  
    V(Isolate, "dart:isolate")
    V(VM, "dart:vm")

This API method would provide functionality similar to the `'setVMTimelineFlags'` rpc method supported in the service protocol.

In this model the embedder would always have 'systrace_timeline' enabled by default in the release build but all the streams would be disabled and it could then toggle the individual streams at runtime to collect timeline traces.

**Comment by xster** [comment]
Also cc @christianedwardpadilla. 

> In this model the embedder would always have 'systrace_timeline' enabled by default in the release build

This might be an implementation detail, but the desired capabilities are: 

- Be able to take a release build locally or on CI, and run it with a VM flag before the VM starts to globally enable timeline traces for the process
- Be able to take a release build (in production). There is no awareness of whether the traces will be toggled on during the process but depending on user actions, the traces will be turned on and off through the above APIs. 

The 2 scenarios currently have no overlap. So there's some flexibility in terms of the API design.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/219860
