### ISSUE TITLE
Inconsistent help for test

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#47608]
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"

```
dart help test
```
===>
```
Run tests for a project.

Usage: dart test [arguments]
```
--------------------------
```
dart test --help
```
===> Detailed help on the arguments.

A random selection of other commands provides the same help both ways.

**Comment by natebosch** [comment]
This was fixed in https://github.com/dart-lang/test/pull/1554
