### ISSUE TITLE
Messages do not come to isolate if there is Stream.listen() in the isolate

### ISSUE THREAD

**Issue by Tim-dev-hub** [dart-lang/sdk#47609]
I ran into a strange problem with Isolate, I create a new isolate, send SendPort to it through which I then receive another SendPort (for bidirectional communication with the isolate). But I get messages to the isolate only if I do not listen to Stream in the isolate, while messages from the isolate to the main come anyway

dart sdk version: 2.5.3 
My code: 
```
main() async {
  var isolate = await initIsolate();
  isolate.send("Message");
}

Future<SendPort> initIsolate() async {
  Completer completer = new Completer<SendPort>();
  ReceivePort isolateToMainStream = ReceivePort();

  isolateToMainStream.listen((data) {
    if (data is SendPort) {
      SendPort mainToIsolateStream = data;
      completer.complete(mainToIsolateStream);
    } else {
      print('[isolateToMainStream] $data');
    }
  });

  Isolate myIsolateInstance =
      await Isolate.spawn(_start, isolateToMainStream.sendPort);
  return completer.future as Future<SendPort>;
}

void _start(SendPort isolateToMainStream) {
  //create a new port and send it to the main
  ReceivePort mainToIsolateStream = ReceivePort();
  isolateToMainStream.send(mainToIsolateStream.sendPort);

  //listen messages from main
  mainToIsolateStream.listen((data) {
    print('[mainToIsolateStream] $data');
    //works only if don't listen Stream
  });

  //listen Stream
  var _jsonclient = JsonClient.create("Assets/bin/tdlib");
  _jsonclient.incomingString().listen((update) {
    if (update != null) isolateToMainStream.send(update);
  });

  //this check passed
  print("end of _start(SendPort)");
}
```

**Comment by mraleph** [comment]
One common issue that might cause isolate to stop answering is an uncaught exception which by default will cause isolate to exit. You can set `errorsAreFatal: false` in `Isolate.spawn` to suppress this behaviour. I'd guess that something in `JsonClient` might be throwing an uncaught exception, but hard to figure it out because your have not provided a fully runnable code example.

In future I suggest asking questions using community channels: https://dart.dev/community. This issue tracker is primarily for reporting bugs and not for asking for help with your code.

**Comment by cliftonlabrum** [comment]
@cuteUtya I'm running into this same issue. Did you ever figure out the cause?

**Comment by cuteUtya** [comment]
@cliftonlabrum 

As I can remember there no nice solution. But I did next: I listened for new messages from main isolate for shorts period of time couple of times per minute (like 1ms 180 times per minute), maybe it's can affect you framerate, but it's works good for me. 

If it's doesn't for you — write to me again I will check my old code, I can't he sure that it was my final solution
