### ISSUE TITLE
Analyzer Failures on Implement Generic Function Instantiation via wrapping node

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#47605]
There are new test failures on [Implement Generic Function Instantiation via wrapping node](https://github.com/dart-lang/sdk/commit/0da6894247ea946ab0d767bed0c124c074eb70e7).

The tests
```
language/generic/typedef_test CompileTimeError (expected Pass)
language/generic/typedef_test CompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-strong-linux
analyzer-asserts-strong-mac
analyzer-asserts-strong-win
analyzer-asserts-weak-linux
analyzer-asserts-weak-mac
analyzer-asserts-weak-win
```

The output of the strong-linux failure is:
--- Command \"dart2analyzer\" (took 55ms):\nDART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=json --no-hints /b/s/w/ir/cache/builder/sdk/tests/language/generic/typedef_test.dart\n\n
unexpected analysis errors in typedef_test.dart:\n
- Line 51, column 6: TODO.TODO\n
  TODO(jmesserly): Analyzer incorrectly rejects this form:\n\n
- Line 53, column 9: COMPILE_TIME_ERROR.INVALID_ASSIGNMENT\n
-   A value of type 'int Function(int, int)' can't be assigned to a variable of type\n  'T Function<T>(T, T)'.\n\n
- --- Re-run this test:\npython3 tools/test.py -n analyzer-asserts-strong-linux language/generic/typedef_test

**Comment by eernstg** [comment]
This looks like a fault in the test. Cf. https://github.com/dart-lang/sdk/issues/47561#issuecomment-953781196 and https://github.com/dart-lang/sdk/issues/39641 for some background.

@scheglov, I adjusted the test here: https://dart-review.googlesource.com/c/sdk/+/219042.

**Comment by eernstg** [comment]
Said tests are now succeeding.
