### ISSUE TITLE
Customer-reported issue with NNBD migration tool

### ISSUE THREAD

**Issue by mohadel92** [dart-lang/sdk#47614]
#### Steps to reproduce
start dart migration tool 

#### What did you expect to happen?
i expect to be able to resize the files column so that i can check my files 

#### What actually happened?

resizing the windows is disabled

_Screenshots are appreciated_
<a href="https://ibb.co/tQXQNGP"><img src="https://i.ibb.co/vVYVrFv/Screen-Shot-2021-11-03-at-7-26-04-PM.png" alt="Screen-Shot-2021-11-03-at-7-26-04-PM" border="0"></a>

**Dart SDK version**: 2.14.4

Thanks for filing!

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
