### ISSUE TITLE
Request methods like `firstOrNull`, `lastOrNull`.. on List objects.

### ISSUE THREAD

**Issue by zonble** [dart-lang/sdk#47612]
Currently, if a developer calls methods like `first`, `last`, `firstWhere`, `lastWhere` on an empty list, Dart throws an exception. This is somehow not expected.

Since Dart supports null safety, it is very natural a developer would like to use optional chain or nullable chain syntax while working on a list. For example, when a developer want to get a member of the first element in a list, he or she is very likely to write code like this:

``` dart
final variable = someList?.first?.someProperty?.someValue;
```

A developer may think it is safe but it is actually not. 

Other programming languages have methods like firstOrNull might solve the issue:

- Kotlin https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/first-or-null.html
- C# https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.firstordefault?view=net-5.0

I would like to have following new methods:

- firstOrNull
- lastOrNull
- firstWhereOrNull
- lastWhereOrNull

**Comment by Markzipan** [comment]
These functions should be available in `package:collection` right now. See similar discussion here: https://github.com/dart-lang/sdk/issues/42583
