### ISSUE TITLE
Compiled executable get Segmentation fault(11) in arm64 based Kubernetes

### ISSUE THREAD

**Issue by fdelucchijr** [dart-lang/sdk#47618]
I'm building a dart 2.15.0-178.1.beta-sdk executable with BuildX (in GitHub Actions) and sending to my companies Cluster (2 Oracle Amphere (ARM64 2cpu 12gb ram) Nodes) and I get following message from the pod:

Note: The executable is run inside a ubuntu:latest image.

```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=2, si_addr=0xfffd969515c0

===== CRASH =====
si_signo=Trace/breakpoint trap(5), si_code=1, si_addr=0xfffd96983e40
```

Any help would be much appreciated!

EDIT:
This is a rare problem, the image runs completely fine in my arm64 m1 MBA, and in my desktop WSL amd64, issue only present in Amphere Arm

**Comment by mraleph** [comment]
We would need more information to diagnose this. I'd suggest to attach a debugger or try collecting a core dump (if possible).

**Comment by fdelucchijr** [comment]
> We would need more information to diagnose this. I'd suggest to attach a debugger or try collecting a core dump (if possible).

Do you have any info related to how can I attach a debugger to an executable inside a container in Kubernetes? 🤣. 
I will start digging in how can I give you more info. Thank you for your quick response!

**Comment by fdelucchijr** [comment]
I get this coredump from the file (I tried to process it with gdb but no luck for me, I'm pretty noob into that level of abstraction in SE): https://we.tl/t-27DGPAckCR

**Comment by mraleph** [comment]
I poked around in the core dump but it is pretty hard to diagnose what is going on, for various reasons, mainly because machine code for `/app/server` is not available for inspection.

If you have access to the binary which produced the core, you can start by loading it into `gdb-multiarch` like so

```
$ gdb-multiarch server core.21695
```

Then you should be able to disassemble instructions around the crash location. I think we are doing a call and we hit some wrong location (which is not executable). You could try (these are addresses taken from the core you have shared):

```
(gdb) x/10i 0xfffef52cfd50-0x20
(gdb) x/10i 0xfffef54f15c0-0x20
```

**Comment by fdelucchijr** [comment]
These are the logs from the procedure:
```
Reading symbols from server...
(No debugging symbols found in server)

warning: core file may not match specified executable file.
[New LWP 602]
[New LWP 603]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Core was generated by `./server --debug'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0xfffef57e6000 (LWP 602))]
(gdb) x/10i 0xfffef52cfd50-0x20
   0xfffef52cfd30:      Cannot access memory at address 0xfffef52cfd30
(gdb) x/10i 0xfffef54f15c0-0x20
   0xfffef54f15a0:      b.vc    0xfffef54f15ac
   0xfffef54f15a4:      bl      0xfffef54d88e4
   0xfffef54f15a8:      stur    x2, [x0, #7]
   0xfffef54f15ac:      mov     x15, x29
   0xfffef54f15b0:      ldp     x29, x30, [x15], #16
   0xfffef54f15b4:      ret
   0xfffef54f15b8:      bl      0xfffef54d86e4
   0xfffef54f15bc:      b       0xfffef54f1508
   0xfffef54f15c0:      tbz     w0, #0, 0xfffef54f15d8
   0xfffef54f15c4:      ldurh   w9, [x0, #1]
```

**Comment by mraleph** [comment]
Is this from exactly the same `server` binary that crashed on the server? I am bit puzzled why the first print did not succeed. 
 
Is it possible for you to switch from building a single executable to build a snapshot instead and then run that through `dartaotruntime`? 

Currently you probably use `dart compile exe`, could you try to do `dart compile aot-snapshot` and then try to run that on the server instead (you would need to copy snapshot + `dartaotruntime` from the match ARM64 Dart SDK)?

**Comment by fdelucchijr** [comment]
Yes, it is from the same executable, even from the same pod (k8s).

Oka, I'm gonna try right now!

**Comment by fdelucchijr** [comment]
Sorry for the delay, I've tried putting a pod with the complete SDK, copied the repo to the pod and compiled the snapshot. Running make the following result:
```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=2, si_addr=0xfffc2a7815c0
Aborted (core dumped)
```
I also tried the last commands with GDB, this is the results:
```
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Core was generated by `dartaotruntime server'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0xfffc2aa83e00 (LWP 291))]
(gdb) x/10i 0xfffef52cfd50-0x20
   0xfffef52cfd30:      Cannot access memory at address 0xfffef52cfd30
(gdb) x/10i 0xfffef54f15c0-0x20
   0xfffef54f15a0:      Cannot access memory at address 0xfffef54f15a0
```

Copying the repo allow me to try to run the source code with Dart. It works without problem, It seems to be only a problem with the executables.

**Comment by fdelucchijr** [comment]
Any update or something can I help in to solve it?

**Comment by mraleph** [comment]
Sorry, I was busy with other things. I provisioned an Amphere server and I can actually reproduce the crash just by compiling a simple hello world. Now I can just investigate it there, let me see what I can find.

**Comment by mraleph** [comment]
I have a fix up: https://dart-review.googlesource.com/c/sdk/+/220381

**Comment by fdelucchijr** [comment]
Thank you very much!!! You're awesome!! Now our app can go full ARM kubernetes!!!! 🚀

**Comment by cthurston** [comment]
I'm getting this same error when trying to docker buildx linux/amd64 on a Mac M1.

pubspec.yaml
```
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
```
  
Dockerfile
```
FROM dart:stable AS build

WORKDIR /app
COPY pubspec.* ./
RUN dart pub get
```

Run command (tried from terminal and terminal running with rosetta):
docker buildx build --platform linux/amd64 -t dart_server:v1 .

Error:
```
#8 1.992 ===== CRASH =====
#8 1.992 si_signo=Segmentation fault(11), si_code=1, si_addr=0x48
#8 1.993 version=2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "linux_x64"
#8 1.993 pid=9, thread=17, isolate_group=dartdev(0x4002f9d000), isolate=dartdev(0x4002f9d800)
#8 1.993 isolate_instructions=ffffaf233000, vm_instructions=4001e1b540
#8 1.993   pc 0x0000ffffaf014320 fp 0x0000004009a7ccc0 Unknown symbol
#8 1.996   pc 0x0000004001f97fbd fp 0x0000004009a7daa0 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x14d
#8 1.996   pc 0x0000004001f97dfc fp 0x0000004009a7db00 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x14c
#8 1.997   pc 0x0000004001f9a20f fp 0x0000004009a7db50 dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&)+0x16f
#8 1.997   pc 0x0000004001fc1085 fp 0x0000004009a7dc30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x375
#8 1.998   pc 0x0000004001fe914c fp 0x0000004009a7dca0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x14c
#8 1.998   pc 0x0000004001fe984f fp 0x0000004009a7dcf0 dart::MessageHandler::TaskCallback()+0x1df
#8 1.998   pc 0x0000004002103678 fp 0x0000004009a7dd80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x138
#8 1.999   pc 0x0000004002103b0c fp 0x0000004009a7ddb0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
#8 1.999   pc 0x000000400207c9e8 fp 0x0000004009a7de70 /usr/lib/dart/bin/dart+0x207c9e8
#8 1.999 -- End of DumpStackTrace
#8 2.000 qemu: uncaught target signal 6 (Aborted) - core dumped
#8 2.013 Aborted
```

Note: It does successfully build as arm using docker build.

**Comment by mraleph** [comment]
@cthurston it's not the same error, it's a different one in a different place. please file a separate issue.

**Comment by cthurston** [comment]
#48420 opened
