### ISSUE TITLE
new hint for uses of bidirectional unicode codepoints

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#47611]
**TL;DR** [Bidirectional Unicode](https://unicode.org/reports/tr9/) text can be interpreted and compiled differently than how it appears in editors leading to possible security vulnerabilities. 

---

This work started as a lint (https://github.com/dart-lang/linter/issues/3048) but after some discussion w/ the language-team, it was decided to bump it to a hint (and so opted-in by default).

**Comment by lrhn** [comment]
I think it could be a good idea to follow Rust and have *two* lints: "BIDI-characters in String literal" and "BIDI-characters in comment".

That prevents the attack of doing:
```dart
/// ignore: unicode-bidi-someting
var username = "root"; // Some comment "WITH RTL TEXT"
```
and actually having RTL text in the string as well.

**Comment by pq** [comment]
> I do think we should mark the actual string or comment, not just the entire file.

FWIW, we're now highlighting the offset of the offending character -- making remediation way easier.

**Comment by pq** [comment]
> I think it could be a good idea to follow Rust and have two lints: "BIDI-characters in String literal" and "BIDI-characters in comment"

Agreed.  I'm working on a new patch that adds `HintCode.TEXT_DIRECTION_CODE_POINT_IN_COMMENT` and `HintCode.TEXT_DIRECTION_CODE_POINT_IN_LITERAL` and should have it up for review shortly.    It also includes the escaped unicode sequence in the error message which I think will come in handy if folks encounter this issue in the wild.
