### ISSUE TITLE
analysis server crashing in vscode

### ISSUE THREAD

**Issue by minimalhustler** [dart-lang/sdk#47617]
The Dart Analysis Server server crashed 5 times in the last 3 minutes. The server will not be restarted

Hello , i am getting this error continuously i freshly installed vscode and followed all steps for setting up flutter and dart , please someone got the solution share.

**Comment by srawlins** [comment]
Sorry for the delay; can you report your `flutter doctor` output?

Does the issue occur when performing a specific task or opening a certain file?

**Comment by minimalhustler** [comment]
thanks for reply actually dart analysis fixed but now i am stucked with the " gradle build failed to generate an apk " anyone know why this happend . IN FLUTTER DOCTOR 1 Have just 1 issue " Could Not determine java version " Does this effect , build of apk ?
![Uploading IMG_2021-11-08-18-46-54-854.jpg…]()

**Comment by srawlins** [comment]
Glad the crash stopped happening. Please feel free to re-open this issue if it occurs again.

**Comment by devnoaman** [comment]
how to validate what is the problem that leads analysis server to get crashed

**Comment by srawlins** [comment]
I suspect a stack trace would be shown in the Instrumentation log when the Analysis Server crashes. I could be wrong. See here: https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/tutorial/instrumentation.md
