### ISSUE TITLE
[CP] Ensure rehashing of maps correctly resets [_deletedKeys]

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#47639]
**commit(s) to merge**: dc7e082336fc7a9c639c1d62edf4cc0ebb57ea51

**merge instructions**: clean (auto)merge   (on 2.15.0-268.0.dev which will become the beta branch according to infra)

**What is the issue**: Sending a `Map` across a `SendPort` where the map had some elements removed will result in a copy of the `Map` which will yield incorrect `.length`.

**What is the fix**: For the particular issue reported: not re-hashing the map (not needed in that case). For general maps, resetting `_deletedKeys = 0` in the Dart rehashing code.

**Why cherrypick**: Users reported this.

**Risk**: low

**Link to original  issue(s)**:
https://github.com/dart-lang/sdk/issues/47598

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by mit-mit** [comment]
sgtm

**Comment by athomas** [comment]
Merged to beta in c8b50bd835770529f30c6079376c824264a57e2c (2.15.0-268.8.beta).
