### ISSUE TITLE
Failures on [vm/concurrency] Remove --(no-)enable-isolate-groups flag usage in tests

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#47632]
There are new test failures on [[vm/concurrency] Remove --(no-)enable-isolate-groups flag usage in tests](https://github.com/dart-lang/sdk/commit/96d40d1caaa05387175867a9ba115dc0cbf23a30).

The tests
```
standalone_2/io/platform_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-release-simarm-crossword
dartkp-linux-release-x64
dartkp-obfuscate-linux-release-x64
dartkp-win-release-x64
```

/cc @mkustermann

**Comment by mkustermann** [comment]
This is an existing failure. It is just that the test itself went from being a multitest with `.../0` and `.../1` sub-tests to be a non-multitest. So it appears like a new failure but it isn't.

Looking at the test it's pretty obvious that it doesn't work in AOT:
```dart
test() {
  ...
  if (!Platform.isWindows) {
    Expect.isTrue(Platform.executable.endsWith('dart'));
    Expect.isTrue(Platform.resolvedExecutable.endsWith('dart'));
  } else {
    Expect.isTrue(Platform.executable.endsWith('dart.exe'));
    Expect.isTrue(Platform.resolvedExecutable.endsWith('dart.exe'));
  }
 ...
}
main() {
  ...
  test();
  ...
}
```

In AOT we `Platform.executable` will of course be `dart_precompiled_runtime`.

**Comment by alexmarkov** [comment]
Currently failing on the following configurations:

```
app_jitk-linux-debug-x64
app_jitk-linux-release-x64
dartk-linux-release-simarm
dartkp-linux-debug-x64
dartkp-linux-product-x64
dartkp-linux-release-simarm
dartkp-linux-release-simarm-crossword
dartkp-linux-release-simarm64
dartkp-linux-release-x64
dartkp-mac-release-simarm64
dartkp-obfuscate-linux-release-x64
dartkp-strong-linux-release-x64
dartkp-weak-asserts-linux-release-x64
dartkp-win-release-x64
```

**Comment by mkustermann** [comment]
Same testing infrastructure is probably responsible for this (old and new) failure:

The tests
```
vm/dart_2/spawn_shutdown_test Crash (expected Pass)
```
are failing on configurations
```
app_jitk-linux-product-x64
```

**Comment by mkustermann** [comment]
Uploaded [cl/219520](https://dart-review.googlesource.com/c/sdk/+/219520) to fix the test as well as a VM issue on the error path.

Both issues have been around for a long time and weren't actually caused by my change.

**Comment by mkustermann** [comment]
Both `standalone_2/io/platform_test` and `vm/dart_2/spawn_shutdown_test` are passing in all configuration now.
