### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by emiheskey** [dart-lang/sdk#47646]
## Version information

- `IDEA AI-203.7717.56.2031.7621141`
- `2.14.0`
- `AI-203.7717.56.2031.7621141, JRE 11.0.10+0-b96-7281165x64 JetBrains s.r.o., OS Mac OS X(x86_64) v10.14.6, screens 1440.0x900.0`

**Comment by mraleph** [comment]
no information, hence feedback is non actionable.
