### ISSUE TITLE
[CP] Update documentation of SendPort.send to be more precise

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#47640]
**commit(s) to merge**: 6225f46b760a5c1eebff9c4dce621e93192a886c

**merge instructions**: clean (auto)merge (on `2.15.0-268.0.dev` which will become the `beta` branch according to infra)

**What is the issue**: Clarifies what objects can be sent across `SendPort`s.

**What is the fix**: Make the API documentation less ambiguous

**Why cherrypick**: The next stable release will launch with more performant and more feature-rich concurrency support. We'd like to ensure users do understand what they can send across `SendPort`s and what they cannot.

**Risk**: low

**Link to original  issue(s)**:
https://github.com/dart-lang/sdk/issues/46623

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in c8b50bd835770529f30c6079376c824264a57e2c (2.15.0-268.8.beta).
