### ISSUE TITLE
Add fixes for undefined_enum_constant

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#47643]
The `undefined_enum_constant` does not currently have any quick fixes, but could have at least two:
- [ ] replace the name with a similar name that is defined
- [ ] add a declaration of the constant

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/239667 for the second point.

For the first point, I am not if there is a 'similar' name utility which exists somewhere.

**Comment by bwilkerson** [comment]
We already have a correction producer that handles similar cases named `ChangeTo`. It probably wouldn't be too hard to extend it to handle more cases (enum constants probably aren't the only place where fixing typos would be helpful).
