### ISSUE TITLE
DDC fails to create type with complex mixin type

### ISSUE THREAD

**Issue by TimWhiting** [dart-lang/sdk#47645]
flutter --version
```
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (5 weeks ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3
```
* Chrome

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    const ProviderScope(
      child: MaterialApp(
        home: Scaffold(
          body: Center(
            child: Text('Hello World'),
          ),
        ),
      ),
    ),
  );
}
```

pubspec.yaml
```yaml
name: dart_web
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter_riverpod: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

To reproduce:
- flutter create dart_web
- copy pubspec and main from issue
- flutter run -d chrome

Error:
```
Uncaught TypeError: framework.OverrideWithProviderMixin$ is not a function
    at auto_dispose.dart:29
    at Object.makeGenericType [as AutoDisposeStateProvider$] (classes.dart:242)
    at load__packages__riverpod__src__state_provider_dart (auto_dispose.dart:29)
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

Works with ahead of time compilation via dart2js / flutter build

Fails on all channels stable / beta / dev / master.
Works on other platforms

**Comment by TimWhiting** [comment]
https://github.com/rrousselGit/river_pod/issues/889

**Comment by dorontal** [comment]
+1 - exactly the same issue here, thanks

**Comment by getdekoded** [comment]
+1 here as well

**Comment by Laebrye** [comment]
+1 here

**Comment by nshahan** [comment]
Thanks for the issue report. I can dig in but does anyone in this thread have a stand alone repro that doesn't involve the flutter and riverpod packages?  If you know the structure of the class hierarchy with mixins that causes the issue it would save some time building a reproduction.

**Comment by TimWhiting** [comment]
I tried to figure out the full class hierarchy to see what might be causing the issue, but there are a lot of classes and mixins involved. Also, I'm not very familiar of compiling dart to web without flutter. I can try recreating it without flutter later tonight, but can't guarantee anything.

**Comment by rrousselGit** [comment]
Riverpod technically doesn't depend on Flutter.
The weird thing is, I don't see an issue with plain Dart code using the package in Dartpad.

The following works just fine:

```dart
import 'package:riverpod/riverpod.dart';

void main() {
  final provider = StateProvider.autoDispose((ref) => 0);
  final container = ProviderContainer(
    overrides: [
      provider.overrideWithProvider(StateProvider.autoDispose((ref) => 42)),
    ]
  );

  print('hello ${container.read(provider)}');
}
```

The irony is, this snippet is explicitly using the mixin that is causing the problem, and everything work just fine.
Whereas the snippet that fails isn't using it at all.




I don't see anything special with that mixin.
It's not doing anything fancy:

```dart
mixin OverrideWithProviderMixin<State, ProviderType extends ProviderBase<Object?>> {
  ProviderBase<State> get originProvider;

  Override overrideWithProvider(ProviderType value) {
    ...
  }
}
```

So I'm kind of lost on what the problem is. Maybe Flutter is using some fancy compilation flags?

**Comment by rrousselGit** [comment]
For some reason, it appears that this happens explicitly with `flutter_riverpod`, not `riverpod` – even if the application is using Flutter.

If we change the import on the snippet I gave to use Flutter, it still work just fine:
```dart
import 'package:riverpod/riverpod.dart';
import 'package:flutter/material.dart';

void main() {
  final provider = StateProvider.autoDispose((ref) => 0);
  final container = ProviderContainer(
    overrides: [
      provider.overrideWithProvider(StateProvider.autoDispose((ref) => 42)),
    ]
  );

  runApp(Text('hello', textDirection: TextDirection.ltr));
}
```


Whereas if we change the import from `package:riverpod/riverpod.dart` to `package:flutter_riverpod/flutter_riverpod.dart`, the error is back.

This is surprising because `flutter_riverpod.dart` is just a bunch of exports:

```dart
// this is flutter_riverpod/flutter_riverpod.dart
export 'package:riverpod/riverpod.dart';

export 'src/change_notifier_provider.dart'
    show
        ChangeNotifierProvider,
        AutoDisposeChangeNotifierProvider,
        AutoDisposeChangeNotifierProviderFamily,
        ChangeNotifierProviderFamily,
        AutoDisposeChangeNotifierProviderRef,
        ChangeNotifierProviderRef;

export 'src/consumer.dart'
    show
        Consumer,
        ConsumerWidget,
        ConsumerBuilder,
        WidgetRef,
        ConsumerState,
        ConsumerStatefulWidget,
        ConsumerStatefulElement;

export 'src/framework.dart' show ProviderScope, UncontrolledProviderScope;
// ignore: deprecated_member_use_from_same_package
export 'src/provider_listener.dart' show ProviderListener, OnProviderChange;
```

**Comment by nshahan** [comment]
I believe I have a simple reproduction and I am investigating a fix now:

```dart
class C<T> with M<C<T>> {}

mixin M<T> {}

void main() {
  C<int>();
}
```

Interestingly, I noticed that the error goes away if I reorder the class and the mixin in the file. I suspect the ordering might be the reason that the issue only appears when using the flutter_riverpod package. It is likely that the export changes the order that the classes and mixins appear within the compiled file.

**Comment by nyck33** [comment]
Would it be possible for either the Dart team @nshahan  or Riverpod @rrousselGit  to designate a Flutter version (and Dart SDK) and versions of the flutter_riverpod, hooks_riverpod that is going to work nicely together for the time being as a workaround?

**Comment by dorontal** [comment]
@nyck33 you can try older Dart versions by downloading from here: [https://dart.dev/get-dart/archive](https://dart.dev/get-dart/archive)

Already tried Dart versions `2.14.3`,  `2.14.2`, `2.14.1`, `2.14.0`, `2.13.4` and all of these produce the **exact** same issue here. After trying these, I gave up, so your question still stands and it would be useful to me too if anybody sheds a light on which package combination works.

[ Originally, I thought I had noticed that this problem started after the Dart 2.14.4 (automatic) upgrade on my system, but at the time did not look or notice to see whether Riverpod had also been updated recently to some new version. ]

**Comment by nshahan** [comment]
I would not expect that this surfaced with a change in the Dart SDK. The code in question has not been changed for a little while. My guess is that a change in one of the river pod packages inadvertently triggered a bug that has been present DDC for a while.

**Comment by TimWhiting** [comment]
Yes, I believe this to be the case, it appeared with the 1.0.0 release of riverpod which was the first to use a mixin structure that apparently exposed a bug that has been in DDC. 

For riverpod users, I believe that 1.0.0-dev.7 was the last version that works fine. Also, the current version of riverpod uses an sdk constraint of >=2.14.0, so make sure you have a compatible sdk. As a workaround if you don't want to go back to 1.0.0-dev.7, you can use 1.0.0 and do your development on other platforms such as Android / iOS / desktop, and then test in release mode on the web (flutter build web).

**Comment by aosorio-avilez** [comment]
> Yes, I believe this to be the case, it appeared with the 1.0.0 release of riverpod which was the first to use a mixin structure that apparently exposed a bug that has been in DDC.
> 
> For riverpod users, I believe that 1.0.0-dev.7 was the last version that works fine. Also, the current version of riverpod uses an sdk constraint of >=2.14.0, so make sure you have a compatible sdk. As a workaround if you don't want to go back to 1.0.0-dev.7, you can use 1.0.0 and do your development on other platforms such as Android / iOS / desktop, and then test in release mode on the web (flutter build web).

I already try with versions `1.0.0-dev.4`, `1.0.0-dev.5`, `1.0.0-dev.6` and `1.0.0-dev.7` but the issue still there, I think the only workaround is development with another platforms as @TimWhiting said or the moment, thanks.

**Comment by TimWhiting** [comment]
@aosorio-avilez I can get it to work doing this:
```yaml
dependencies:
  flutter_riverpod: 1.0.0-dev.6
  riverpod: 1.0.0-dev.6
```

**Comment by nshahan** [comment]
I've landed a fix in the Dart SDK. I'll open a cherry pick request and report here with details about versions that will contain the fix.

**Comment by nshahan** [comment]
@TimWhiting While we wait for the fix to be cherry picked and published as a part of a release it is possible there might be a work around by rearranging the structure of the riverpod packages. Libraries that contain cyclic imports end up getting compiled together into a single module and the ordering within that module is the source of this problem. 

Moving `OverrideWithProviderMixin` to a different location would be the goal. One possibility is that removing it from the files that form a cycle of imports could avoid the bug in DDC.

**Comment by TimWhiting** [comment]
@nshahan The mixin declaration is already in a separate library from the mixin applications, and they do not form a cycle. I've tried reordering the exports of these libraries from the package to make sure the library with the declaration appears first, but it is not working. Note that it works if you just use the riverpod package, but not if you use a package that imports / re-exports the riverpod package. For some reason this is happening at a package boundary level. In short, I don't think there is anything the package itself can do to remedy the situation.
