### ISSUE TITLE
[CP] Cherry pick "Support non-cross-compiled ARM64 on Mac testing" to 2.15.0-268.1.beta

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#47641]
**commit(s) to merge**: ~536ca0b158db7b5f27f01efea6dd190d25b8bd3c~ (decided not to pick this because the problem was fixed by configuration of the CI system instead)
1ca06b953112612cd6250d2b11bb776688ec8e1a

CL links:
https://dart-review.googlesource.com/c/sdk/+/218922
https://dart-review.googlesource.com/c/sdk/+/218923

**merge instructions**: clean merge

**What is the issue**: ARM Mac build and test machines on LUCI swarming download native ARM versions of python and Android SDKs, after a recent change.  These changes fix the build to accept or bypass these native ARM downloads.  The native ARM python means that the build is now a native compilation, not a cross-compilation.

**What is the fix**: Don't fetch the Android SDK - we don't need it to build the Mac Dart SDK.  Change scripts to accept builds in xcodebuild/Release-ARM64.

**Why cherrypick**: needed for successful SDK builds to release the SDK.  The second CL is only needed for successful testing of the build, using sharded tests.

**Risk**: Low.

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by devoncarew** [comment]
@athomas for thoughts on the cherry pick request

**Comment by athomas** [comment]
We must CP 1ca06b953112612cd6250d2b11bb776688ec8e1a to build something releasable.

https://github.com/dart-lang/sdk/commit/536ca0b158db7b5f27f01efea6dd190d25b8bd3c maybe, but we might be able to solve this with configuration instead.

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
1ca06b953112612cd6250d2b11bb776688ec8e1a merged to beta in c8b50bd835770529f30c6079376c824264a57e2c (2.15.0-268.8.beta).
