### ISSUE TITLE
2.15 cherry pick request - rev DevTools version in SDK to latest 2.8.0

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#47644]
Commit: https://github.com/dart-lang/sdk/commit/b8e419d16b10be073f080192a55aaf598321ca10

This is to ensure DevTools 2.8.0 is included in the Dart 2.15 / Flutter 2.8 beta and stable releases. User risk is low. This cherry pick used to be part of the flutter cherry pick process ([example](https://github.com/flutter/flutter/issues/87744)), but now we ship devtools directly in the SDK and will cherry pick the version number update when necessary.

**Comment by devoncarew** [comment]
Thanks; can you include the commit to cherry-pick? We do want to briefly mention the risk wrt cherry picking and the user impact if we don't (see https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel). I'm guessing here that the risk is pretty low and the impact would be that we ship an older version of DevTools.

**Comment by kenzieschmoll** [comment]
Updated the description to include the commit. 

> I'm guessing here that the risk is pretty low and the impact would be that we ship an older version of DevTools.

This is correct.

**Comment by devoncarew** [comment]
Thanks!

**Comment by devoncarew** [comment]
Approved!

**Comment by athomas** [comment]
Merged to beta in c8b50bd835770529f30c6079376c824264a57e2c (2.15.0-268.8.beta).
