### ISSUE TITLE
[CP] disable JavaScript-to-JavaScript async transform optimization

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#47658]
**commit(s) to merge**: 0afb365804ebeec902e0b71ec3550f4359d702fc

**merge instructions**: clean merge in origin/beta

**What is the issue**: Bad code generated in some cases when a switch-statement expression is, or comes from, an `await `expression.

**What is the fix**: The fix disables an optimization, forcing switch statements containing an `await` anywhere to use the 'full' transform.

**Why cherrypick**: Large external customer Workiva is affected. work-arounds are hard because they rely on understanding how the dart2js optimizer works, i.e. most attempts of a work-around get optimized away, leaving the problem. Bad codegen is hard to debug.

**Risk**: Low. No code change in Flutter Gallery or cm_shell.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/47566

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew
/cc @sigmundch

**Comment by devoncarew** [comment]
cc @sigmundch for thoughts on the cherry pick

**Comment by devoncarew** [comment]
How broad do we think the impact is here - how frequently is this hit? And, is this a recent regression or something that's been around a while?

**Comment by sigmundch** [comment]
I lean towards approval. Likely it has been around for eons, but it would be very hard to debug if it came up. The fix is extremely low risk as it's just disabling an (unsound) optimization. Stephen validated and there is no regression from doing so in representative examples. This wouldn't make the cut if we had a hotfix two weeks from now though.

**Comment by devoncarew** [comment]
From the scrum, we'll plan to review this once it's landed and been vetted in google3.

**Comment by sigmundch** [comment]
Update: internal roll landed smoothly on 11/9, no issues raised since.

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in 52519ea8eb4780c468c4c2ed00e7c8046ccfed41 (2.15.0-268.18.beta).
