### ISSUE TITLE
[CP] text direction unicode hints

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#47655]
**commit(s) to merge**: 39008c82435fc266e8ac17fefacc1b14afb58bbe

**merge instructions**: clean merge or patch CL

**What is the issue**:  Dart tools do not guard against  text direction unicode security vulnerabilities

**What is the fix**: Adds hints to identify text direction unicode sequences

**Why cherrypick**: Dart steering committee prioritized this fix for beta

**Risk**: possible false positives; performance degradation.

**Link to original  issue(s)**:

https://github.com/dart-lang/sdk/issues/47611

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by devoncarew** [comment]
An update: this has been reverted in google3. We'll need to resolve and re-land (but this may not be in a position to cherry pick for a bit).

**Comment by devoncarew** [comment]
From the scrum, we'll plan to review this once it's landed and been vetted in google3.

**Comment by pq** [comment]
The Dart CI build for the re-land ran green and made it into the SDK w/ [b403d4b](https://github.com/dart-lang/sdk/commit/b403d4bf73542b974fb85bfbe58c7e2136b8318d).

If the roll tomorrow doesn't shake any big issues out, I think we can look at this again.

**Comment by devoncarew** [comment]
@pq  - I believe the commit for this cherry pick is correct, but the gerrit review (at the top) is not. Can you confirm and remove the CL if that's the case?

**Comment by pq** [comment]
Stale cherry pick CL removed.

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in 52519ea8eb4780c468c4c2ed00e7c8046ccfed41 (2.15.0-268.18.beta).
