### ISSUE TITLE
[CP] Update changelog with details about jsinterop changes

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#47657]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/b97737c3b53a6c043a6a1b97e61b8670ded75629

**merge instructions**: clean merge

**What is the issue**: Changelog was missing some details we'd like to include before the 2.15 stable release

**What is the fix**: Adding the text to the changelog.

**Why cherrypick**: Highlight important features in the changelog.

**Risk**: extremely low, near zero, maybe ε?

**Link to original  issue(s)**: #44533

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew @rileyporter

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in c8b50bd835770529f30c6079376c824264a57e2c (2.15.0-268.8.beta).
