### ISSUE TITLE
Exclamation mark not accepted in dart define during compliation (Windows)

### ISSUE THREAD

**Issue by pomidi** [dart-lang/sdk#47651]
I have realized that exclamation mark is ignored in dart-defines in Windows, while in Linux it works properly. I am using `Dart SDK version: 2.15.0-116.0.dev (dev) on "windows_x64"`.

To show the issue I have created a test file: 
```
void main() {
  final test = const String.fromEnvironment('TEST_ENV', defaultValue: '');
  print('TEST_ENV: $test');
}
```
When compiling as follows: 
```
dart compile exe bin\env_test.dart --define="TEST_ENV=HEY!You"
```

Running the code, I get:
```
>env_test.exe
TEST_ENV: HEYYou
``` 

I expect to get HEY!You, but it prints HEYYou.

**Comment by mraleph** [comment]
I suspect you are using Dart SDK distributed with Flutter which probably means you are hitting this issue https://github.com/flutter/flutter/issues/84270
