### ISSUE TITLE
[CP][beta channel] 243fb5c - analyzer: Support non-proper rename type alias constructor tear-offs

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#47654]
**commit(s) to merge**:   243fb5c383416fb82b6852a83ad3c4449683858a

**merge instructions**: merge https://dart-review.googlesource.com/c/sdk/+/218746

**What is the issue**: analyzer's support for the constructor-tearoffs feature is incomplete without this CL; without this CL there is no notion of proper rename type aliases; the analyzer may report certain constructor tear-offs as identical or as not identical, incorrectly, in const contexts.

**What is the fix**: This CL landed in main after the beta branch cut; it completes analyzer's support for the constructor-tearoffs feature.

**Why cherrypick**: This is the last CL for analyzer's support of the constructor-tearoffs feature, which is enabled by default with Dart Language Version 2.15.

**Risk**: None that I am aware of

/cc @devoncarew

**Comment by devoncarew** [comment]
@leafpetersen to weigh in on the cherry pick request

**Comment by leafpetersen** [comment]
I am in favor of taking this.

**Comment by devoncarew** [comment]
approved!

**Comment by athomas** [comment]
Merged to beta in c8b50bd835770529f30c6079376c824264a57e2c (2.15.0-268.8.beta).
