### ISSUE TITLE
[CP] Cherry-pick 2.15 changelog updates

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#47668]
**commit(s) to merge**: 5331d12f3fd79ce61c588379e24c80d775fe3eab, a856655545e80c58262355e4e9c3af3d928cdfbe

**merge instructions**: clean merge

**What is the issue**: Several tweaks to CHANGELOG.md were landed in main after the branch-out.

**What is the fix**: N/A

**Why cherrypick**:  The risk is very small (just CHANGELOG.md changes) and it makes sense to be consistent across all release branches.

**Risk**: Very low.

**Link to original  issue(s)**: N/A

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by mit-mit** [comment]
sgtm

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in 52519ea8eb4780c468c4c2ed00e7c8046ccfed41 (2.15.0-268.18.beta).
