### ISSUE TITLE
[CP] Fix `pub publish` hanging after reading from `stdin`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#47661]
**commit(s) to merge**: 109c317ac12a43d8a25b14bca9805276bf8c84ee

**merge instructions**: Should merge clean, this a one-liner bumping `pub_rev` to [`96404e0749864c9fbf8b12e1d424e8078809e00a`](https://github.com/dart-lang/pub/commit/96404e0749864c9fbf8b12e1d424e8078809e00a).

**What is the issue**: New method of reading from `stdin` caused `dart pub publish` and `dart pub token add` to hang after completing. This likely happens because of some lingering event listener on `stdin`, it seems to not have affected tests because `exit()` was explicitly called.

**What is the fix**: Use `stdin.readLineSync()` from `dart:io`, instead of trying to read `stdin` async, which we don't need to do.

**Why cherrypick**: Affects users running `pub publish` as they will likely have the process hanging.

**Risk**: Minor, theprevious method of reading `stdin` with `StreamQueue` was introduced just before 2.15.0 branched.

**Link to original  issue(s)**: https://github.com/dart-lang/pub/issues/3219

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by devoncarew** [comment]
@jonasfj - thanks for the cherry pick. I see this is a DEPs update. I haven't looked at the diff in the pub repo; is this just getting the fix from the pub repo (or the fix and other unrelated commits)?

**Comment by athomas** [comment]
This is just the fix.

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in c8b50bd835770529f30c6079376c824264a57e2c (2.15.0-268.8.beta).
