### ISSUE TITLE
`killPid` returns false when successfully killing on Windows. Make it return true!

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#47675]
The [`killPid`](https://api.dart.dev/stable/2.14.4/dart-io/Process/killPid.html) static method of `Process` tries to send a signal to a process. It returns true if the signal was delivered (whether it was a kill-signal or not).

However, on Windows, it just kills the process in a non-signal based way. It then returns `false`, probably because no signal was delivered. 
It would be better if it returned `true` if a process with that Pid existed (and it was killed), and `false` if no process with that Pid existed.

**Comment by aam** [comment]
@lrhn , looking at the source code https://github.com/dart-lang/sdk/blob/main/runtime/bin/process_win.cc#L922 it seems it should return `true` if `TerminateProcess` was successful. `false` can also be returned if we failed to (get permission to) attach to the subject process.

Do you have a repro for the problem you describe?

**Comment by lrhn** [comment]
I agree that the source code looks like it does the right thing.

I was reporting this bug based on someone else's experience. Likely something like https://github.com/flutter/flutter/pull/96320#discussion_r781491804, but I no longer remember how I first became aware of it.

**Comment by aam** [comment]
Please reopen with reproduction steps.
