### ISSUE TITLE
The flutter-analyze bot needs to run the dart fix tests in flutter

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#47678]
The flutter-analyze bot (https://github.com/dart-lang/sdk/blob/main/tools/bots/flutter/analyze_flutter_flutter.sh) doesn't currently cover changes to the analysis server's fix support that impacts some of the flutter tests. We would like to have it updated to run one additional test.

The tests can be run by executing `dart fix --compare-to-golden` in the root of the `packages/flutter` package using the version of `dart fix` being tested.

This is currently hampering our ability to make changes to `dart fix` or it's underlying support in the analysis server.

**Comment by athomas** [comment]
Do you need my assistance here? It seems like a rather simple change to the script or am I missing some hidden complexity?

https://github.com/dart-lang/sdk/blob/main/tools/bots/flutter/analyze_flutter_flutter.sh#L39 seems to do the same in another directory.

**Comment by srawlins** [comment]
I'll take a look at this, @athomas and let you know if I need help. Thanks for the link!!

**Comment by srawlins** [comment]
How does this script fail? Is it called in such a way that a non-zero return code of any contained command will fail the script and report a failure in the bot?

**Comment by athomas** [comment]
Yes, the `set -e` means any command with a non-zero exit code will make the
script exit with that exit code and then the build will fail.

**Comment by srawlins** [comment]
@bwilkerson  Now that I understand the tool a bit more, can you say why `dart fix --compare-to-golden` should be run in `packages/flutter`? When I run the command here manually, I get the following output:

```
...
No corresponding expect file for the Dart file at "/Users/srawlins/code/flutter/packages/flutter/lib/rendering.dart".
No corresponding expect file for the Dart file at "/Users/srawlins/code/flutter/packages/flutter/lib/scheduler.dart".
No corresponding expect file for the Dart file at "/Users/srawlins/code/flutter/packages/flutter/lib/animation.dart".
No corresponding expect file for the Dart file at "/Users/srawlins/code/flutter/packages/flutter/lib/services.dart".
Passed: 0, Failed: 1280
srawlins-macbookpro2:flutter srawlins$ echo $?
1
```

However, in the `packages/flutter/test_fixes` directory, the same command succeeds with `Passed: 6, Failed: 0`.

Is the ask for this issue just that we run the just-built `dart`, rather than flutter's pre-packaged `dart`?

**Comment by bwilkerson** [comment]
> can you say why `dart fix --compare-to-golden` should be run in `packages/flutter`?

That was a sloppy shorthand on my part. Sorry for the confusion. As you noted it should be run in `packages/flutter/test_fixes`.

> Is the ask for this issue just that we run the just-built `dart`, rather than flutter's pre-packaged `dart`?

Yes. The problem we ran into is that a change in the SDK wasn't flagged as being a problem until it had been rolled into Flutter, breaking Flutter's roller. We need to catch this kind of error sooner in the process in order to avoid breaking the roller.

**Comment by srawlins** [comment]
Excellent, thanks!
