### ISSUE TITLE
[vm_service] stop using Isolate.spawnUri in `mark_main_isolate_as_system_isolate_test.dart`

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#47689]
This is triggering an `avoid_dynamic_execution` lint in g3.

**Comment by bkonyi** [comment]
I don't think we can avoid using `Isolate.spawnUri` here, so we should probably just disable the lint in google3 for `third_party/dart/vm_service`

**Comment by bkonyi** [comment]
Resolved in cl/413155215
