### ISSUE TITLE
Debugger in DartEditor does not show enough information for closure activation on the stack

### ISSUE THREAD

**Issue by larsbak** [dart-lang/sdk#4768]
In the stack view (attached picture) the line:
&nbsp;&nbsp;&nbsp;&nbsp;CodeEmitterTask.&lt;anonymous closure&gt;()
fails to show the closure resides inside the assembleProgram method.
How about displaying:
&nbsp;&nbsp;&nbsp;&nbsp;CodeEmitterTask.assembleProgram.{}()

This will make the context clear.

Regards,
&nbsp;&nbsp;Lars

______
**Attachment:**
[DebuggerClosure.png](https://storage.googleapis.com/google-code-attachments/dart/issue-4768/comment-0/DebuggerClosure.png) (209.43 KB)

**Comment by iposva-google** [comment]
Editor is not supported any more.
