### ISSUE TITLE
typedefs on Types show as dynamic Function() in WebStorm

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#47683]
dart 2.15.0-edge. Also tried with 2.14.4 and the result is the same.  

The app builds ok but WebStorm insists in not recognizing the typedef:  

<img width="1181" alt="Screen Shot 2021-11-11 at 21 28 49" src="https://user-images.githubusercontent.com/6199518/141388298-27ac2b56-4d6e-4ccf-9868-bf3cc08296cb.png">

**Comment by srawlins** [comment]
> typedefs on Types show as dynamic Function() in WebStorm

CC @bwilkerson this might be intentional? Do we perhaps de-alias aliases to show why a signature may not match?

> The app builds ok but WebStorm insists in not recognizing the typedef:

Is this an unrelated issue? Can you give an example in text form, not a screenshot? I cannot tell if the dialog error is referring to line 181, 182, or 186. If it's referring to 186 (my suspicion), we need to be able to see line 186.

**Comment by jodinathan** [comment]
Take a look at the definition `typedef ErrorFieldMap = Map<String, ErrorItem?>;` at right.  
Now look at the left side where I assign `_validateErrors`, which is a `ErrorFieldMap`, to a literal `Map` `{}` and the analyzer error in the tooltip saying that I can not assign a `Map<dynamic, dynamic>` to a `dynamic Function()`.

**Comment by bwilkerson** [comment]
When I put the same declarations in a file:
```dart
typedef ErrorFieldMap = Map<String, ErrorItem?>;
ErrorFieldMap _validateErrors = {};
class ErrorItem {}
```
I don't see any diagnostics. I guessed that `ErrorItem` is a class, but that might have been my mistake.

Either way, does this small bit of code reproduce the situation you're seeing with a larger piece of code?

**Comment by jodinathan** [comment]
weird.  The error stopped for no apparent reason.  

Maybe it was some sort of cache thing.  

thanks for your time
