### ISSUE TITLE
@useResult annotation doesn't count "if" as use

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#47685]
I thought I had a perfect use case for `@useResult`, changing an exception into a bool success/failure result ... but it turns out that this is not enough to satisfy the analyzer:

```
@useResult
bool foo() {
  return true;
}
 
void bar() {    
  if(foo()) { // hint here: "The value of 'foo' should be used."
    print('hi');
  }
}
```

could it be tweaked to count this as use, please?

Thanks.

**Comment by asashour** [comment]
I guess this is fixed.

**Comment by asashour** [comment]
I guess it was fixed in https://github.com/dart-lang/sdk/commit/434e1b70e81f91312fcaecd6b6149eebf4d8bdb2

**Comment by pq** [comment]
yes.  This should be fixed.  Thanks @asashour!
