### ISSUE TITLE
[CP] Fix DDC compiled app crash - ecdcde3

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#47688]
**commit(s) to merge**: ecdcde3a838e1c88c2d00df3b8d36a916b628b49

**merge instructions**: clean merge

**What is the issue**: When a class cyclicly appears in the type argument of a mixin applied to it a DDC compiled application could crash when loading the library.

**What is the fix**: Ensure the mixin class definition is emitted before it is used.

**Why cherrypick**: Many users of the latest version of package:flutter_riverpod have reported crashes when running 

**Risk**: Low, adds a use of a common pattern used elsewhere in the compiler for class definitions.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/47645

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew @sigmundch

**Comment by sigmundch** [comment]
I'm in favor of approving - the issue has high visibility. It's technically not a regression, but it was triggered by a commonly used package. Definitely for 2.15, also worth discussing whether it merits a cherry-pick for 2.14.

**Comment by Patrick386** [comment]
The same problem occurs when migrating. When will the improved SDK be updated?

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in 52519ea8eb4780c468c4c2ed00e7c8046ccfed41 (2.15.0-268.18.beta).

**Comment by nshahan** [comment]
@athomas @devoncarew Is there also a cherry pick into a Flutter beta that would contain the Dart SDK 2.15.0-268.18.beta? If so, what is the version?

**Comment by devoncarew** [comment]
Once something makes it into the dart cherrypicks, they get picked up by the coo-responding flutter one. This cherry pick was in the recent flutter beta - `2.8.0-3.2.pre`.
