### ISSUE TITLE
[CP] Ensure spawnUri'ed isolates keep their own origin_id.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#47696]
**commit(s) to merge**: c4a07a88f9c0a233e40f37fb919c183921c05e96

**merge instructions**: clean (auto)merge

**What is the issue**: An isolate spawned via `Isolate.spawnUri()` that spawns another isolate via `Isolate.spawnUri()` and tries to communicate with the former using user-defined data structures can lead to a crash. Instead it should result in an error. (When using `dart test` / `dart run` - which internally uses `spawnUri()`, one `spawnUri` in user code is enough to trigger it).

**What is the fix**: Make setting of the `origin_id` of an isolate conditional on it not being `ILLEGAL _PORT`.

**Why cherrypick**: Users have hit this.

**Risk**: low

**Link to original  issue(s)**:
https://github.com/dart-lang/sdk/issues/47674

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

/cc @aam

**Comment by athomas** [comment]
@mkustermann given that this was found on the stable release, are you requesting this to be picked into 2.14 stable or 2.15 beta (so that it goes out with 2.15)?

**Comment by mkustermann** [comment]
@athomas Given the new stable will happen soon, I think it's enough for it to be included in 2.15 beta.

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in 52519ea8eb4780c468c4c2ed00e7c8046ccfed41 (2.15.0-268.18.beta).
