### ISSUE TITLE
Debugging in VS Code throws uncaught exceptions

### ISSUE THREAD

**Issue by a7md0** [dart-lang/sdk#47692]
I'm not sure if this is the right place to file this issue, but this is related to #37953. The reproduction repository is provided, which uses 3rd party HTTP client package ([flutterchina/dio](https://pub.dev/packages/dio/example)). To recap, awaiting a Future that may fail from the library (e.g., 404 HTTP GET request) will throw an uncaught exception, even though the call is surrounded with try/catch block (the catch block get executed directly after skipping the uncaught exception).

* Preproduction repository: https://github.com/a7md0/ex_unhandled_app
* Visual Studio Code version: `1.62.1 f4af3cbf5a99787542e2a30fe1fd37cd644cc31f x64`
* Dart SDK Version: `Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "windows_x64"`
* Flutter SDK Version:-
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision 18116933e7 (4 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```
* Platform: Windows 10 x64 with Android Simulator (API 29)
* Breakpoints from "Run and Debug" tab
![image](https://user-images.githubusercontent.com/10885603/141615227-4a5d45d1-1126-40fd-85f9-970729ee3f1b.png)

**Comment by mkustermann** [comment]
@cskau-g Could you take a look at this? (Related to the `break in debugger on unhandled exceptions` feature you were implementing)

**Comment by mkustermann** [comment]
@cskau-g Thanks for investigating!

**Comment by markfili** [comment]
Correct! Should there be a way, in any IDE, to disable the debugger
stopping on exceptions thrown from libraries used in our projects which can
be handled like the one in Dio library?

**Comment by cskau-g** [comment]
@markfili, if you're asking for a way to disable stops on uncaught exceptions, then that already exists as you can use e.g. DevTools to toggle the debugger behaviour for exceptions (stop on none, uncaught, or all) through the service protocol.

Whether this is exposed in your IDE of choice is of course up to the IDE/extension authors.

If you want more granular control, to set the behaviour per library, then I think that's a feature request for service protocol. (Please file a separate issue for that.)
Though I personally think being able to disable per library won't be that much more useful - libraries shouldn't be throwing large amounts of uncaught exceptions in the first place.

**Comment by aliyazdi75** [comment]
Hi @cskau-g,

Regarding this [issue](https://github.com/Baseflow/flutter_cached_network_image/issues/336) for [`cached_network_image`](https://pub.dev/packages/cached_network_image) plugin, this problem still persists.

This is a reproducible [Gist](https://gist.github.com/aliyazdi75/f70f86b7877e3f5cf7f66c081e18e6ba). As you can see, with defining an `errorWidget`, the exceptions should be handled but the debugger throws on `cached_network_image` exceptions only, not all flutter exceptions.

Could you please take a look at this if possible?
