### ISSUE TITLE
Unable to Create Generic Constructor of T that extends a concrete Type

### ISSUE THREAD

**Issue by indrajit-roy** [dart-lang/sdk#47699]
Hi. Today I faced an issue when I wanted to create a parent data class for all my data models in dart.
What I am trying to do,

```
abstract class DataClass {
// throwing an error since abstract classes cannot be instantiated, 
// but I need my sub classes to implement this factory constructor
 factory DataClass.fromMap(Map<String, dynamic> map) => throw UnimplementedError();
} 
```

```
class ModelClass<T extends DataClass> extends DataClass {
final List<T> values;
factory ModelClass.fromMap(Map<String, dynamic> json) => ModelClass(     
       // Cannot call a constructor invokation on T
        values: json["results"] == null ? null : List<T>.from(json["values"].map((x) => T.fromMap(x))),
      );
}
```

**I dont know if there is another way of achieving a similar outcome. But implementing something like this would drastically reduce a lot of Api Response duplication, where some parameters are always constant.**

**Comment by keertip** [comment]
@leafpetersen

**Comment by eernstg** [comment]
Note that the ability to invoke static methods and/or constructors of a class based on the value of a type variable was discussed in https://github.com/dart-lang/sdk/issues/10667 and https://github.com/dart-lang/language/issues/356.

**Comment by lrhn** [comment]
Closing in favor of https://github.com/dart-lang/language/issues/356.

**Comment by eernstg** [comment]
Let me just mention the standard workaround for being able to call a constructor of a type variable: Introduce a formal parameter which is a factory function (which would typically be the torn-off constructor, but could also be any other function with the right type), and then call that factory function rather than trying to call a constructor on a type variable:

```dart
abstract class DataClass {
  DataClass.fromMap(Map<String, dynamic> map);
}

class ModelClass<T extends DataClass> extends DataClass {
  final List<T>? values;
  ModelClass.fromMap(
      Map<String, dynamic> json, T Function(Map<String, dynamic>) tFactory)
      : values = json["results"] == null ? null : <T>[],
        super.fromMap(json) {
    var values = this.values;
    if (values != null) {
      Iterable<Map<String, dynamic>> jsonValues = json["values"]!;
      for (var x in jsonValues) {
        values.add(tFactory(x));
      }
    }
  }
}
```
