### ISSUE TITLE
Dart FFI function returns num instead of int

### ISSUE THREAD

**Issue by haraldkubota** [dart-lang/sdk#47707]
* Dart SDK Version Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "linux_x64"
* On Linux (x86_64)

While testing FFI I ran into an odd issue which is either non-intuitive or wrong (AKA: a bug), but I cannot exclude that I do something wrong.
I wrote a as-simple-as-possible test case here: https://github.com/haraldkubota/dart-ffi/tree/ffinum/ffi with a short README.md to explain how to reproduce this.

Summary: 

```
primitives_bench.dart:46:15: Error: A value of type 'num' can't be assigned to a variable of type 'int'.
    sum = sum + prlib.plusOne(i);
              ^
```
prlib.plusOne() should have this signature: int prlib.plusOne(int), but I get above error and somehow Dart think it's returning a num instead.

This works:
```
    sum = sum + prlib.plusOne(i) as int;
```

Is this a bug? Is there an implicit num somewhere?

**Comment by haraldkubota** [comment]
Same result on ARMv8 (same version 2.14.4), so it's not x86_64

**Comment by mraleph** [comment]
variable `prlib` is declared as `var prlib` - so its static type is `dynamic`. Consequently `prlib.plusOne(i)` is a dynamic call which returns a value of static type `dynamic`. `int + dynamic` is `num`. Hence the error message.
