### ISSUE TITLE
[CP] Fix handling of captured try_finally_return_value variable

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#47703]
**commit(s) to merge**: 9b7caf3b93856838dd51053effec3ff37d2c69a4

**merge instructions**: clean merge

**What is the issue**: In async/async* methods synthetic :try_finally_return_value variable (which is used to hold return value across finally) could be captured, the flow graph builder in the VM leaves context in an unspecified state and depth after TranslateFinallyFinalizers(NULL, -1), this causes incorrect code to be generated for LoadLocal(finally_return_variable)

**What is the fix**: Flow graph builder in the VM now has the correct context_depth_ in order to access it using LoadLocal(finally_return_variable) when building flow graph for return statement.

**Why cherrypick**: Causes a crash at runtime of the app, was reported by an external user.

**Risk**: Low, has been merged into flutter framework that has rolled into g3

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/47610

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew @alexmarkov

**Comment by a-siva** [comment]
Cherry pick request into the Dart 2.15 beta 3 + stable candidate.

**Comment by devoncarew** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in 52519ea8eb4780c468c4c2ed00e7c8046ccfed41 (2.15.0-268.18.beta).
