### ISSUE TITLE
Generated Proto dart Auto Import Not Working

### ISSUE THREAD

**Issue by coldstar96** [dart-lang/sdk#47705]
When I initially generate dart proto files, Android Studio/VSCode recognizes all proto classes. However, after using for awhile, auto import doesn't work. It only suggests "Create class/mixin" options. When I rename the folder of generated protos to something else, it starts recognizing the files and auto import works. When I change back to the folder name I used before, it stops recognizing. Not sure how to repro but it happened twice.

Steps
1. Generated protos under myproject/lib/gen
2. Auto import for Proto classes worked
3. After using for awhile, Auto import stopped working for proto files
4. Renamed proto folder to myproject/lib/generated and Android Studio/VSCode auto import worked
5. After using for awhile, Auto import stopped working for proto files
6. Renamed myproject/lib/somethingelse and auto import started working. But if I change back right away, auto import doesn't work.

I tried **Invalidate cache/restart** but didn't work. It  is really painful to manually type proto import statements. Can someone please take a look?

Env
Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on September 30, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 10
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, io.flutter, io.kanro.idea.plugin.protobuf

Dart: 203.8430
Flutter: 62.0.1

**Comment by scheglov** [comment]
I suspect that this was caused by older available files support for not-yet-imported libraries.
We switched to a different implementation since then.
So, this issue is obsolete.
