### ISSUE TITLE
dart compile exe produces executables which don't properly work on Linux with non default page size

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#47709]
I have been investigating a crash on a Amphere machines (https://www.oracle.com/cloud/compute/arm/) and these machines have 64kb pages. This does not seem to agree with how our dart compile exe binaries are packaged. I get: 

```console
$ dart-sdk/bin/dart compile exe test.dart
Info: Compiling with sound null safety
Generated: /home/opc/test.exe
$ ./test.exe
Loading failed: File offset must be page-aligned.
$ getconf PAGESIZE
65536
```

**Comment by a-siva** [comment]
Curious what the resolution on this was ?

**Comment by mraleph** [comment]
It was duplicate of #47618 - requires bumping the max page size for ELF format. (fix in flight).

**Comment by mraleph** [comment]
Duplicate of #47618
