### ISSUE TITLE
On Windows, renaming a file using the `Directory` class generates an incorrect exception

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#47713]
```
    final file = File("${tempDir.path}/file");
    file.createSync();
    final dir = Directory(file.path);
   dir.renameSync("${tempDir.path}/dir");
FileSystemException: Rename failed, path = 'C:\b\s\w\itcom54o37\testRenameButActuallyFile744d46d/file' (OS Error: The operation completed successfully.
```

Note how the OS Error said that the operation completed successfully.

**Comment by zanderso** [comment]
There's a missing `SetLasterror` call here https://github.com/dart-lang/sdk/blob/main/runtime/bin/directory_win.cc#L511. See the analogous code in `file_win.cc` here: https://github.com/dart-lang/sdk/blob/main/runtime/bin/file_win.cc#L626

**Comment by brianquinlan** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/085e978ce43da9ce016586f5116fe344a661b019
