### ISSUE TITLE
[CP] When generating Store/Load instructions use guard information that is kept on a slot.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#47710]
**commit(s) to merge**: 67baa5848a2c70cde9e0e65e13f5878f01725473

**merge instructions**: clean (auto)merge

**What is the issue**: When running with many isolates in JIT mode there's a low probability of a racy access in the compiler that can lead to crashes.

**What is the fix**: Ensure the unoptimizing compiler sees a consistent view of a `Field` object's guarded state.

**Why cherrypick**: Have observed this with low-probability on our newly added `iso-stress`  builder.

**Risk**: low-medium

**Link to original  issue(s)**:
https://github.com/dart-lang/sdk/issues/47314

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew

/cc @aam

**Comment by devoncarew** [comment]
approved

**Comment by devoncarew** [comment]
I'm going to un-approve this as it looks like it might be causing a failure on the google3 roll.

**Comment by mkustermann** [comment]
@devoncarew The original change landed 2 weeks ago and has rolled into g3. Could you point us to the failure you're seeing? (/cc @aam who authored the change)

**Comment by aam** [comment]
Sent out revert https://dart-review.googlesource.com/c/sdk/+/220484.
It's flutter google3 roll that hit problems.

**Comment by aam** [comment]
There is indeed a problem with original reverted CL https://github.com/dart-lang/sdk/issues/47722.
Closing this.
