### ISSUE TITLE
Consider making migration tool more liberal with adding `?`s to `is`/`as` checks

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#47711]
(From today's break-out session about null safety migration)

We have seen a few examples of patterns like this:
```dart
void someMethodThatAcceptsManyTypesOfInputs(List<Object> inputs) {
  for (var item in inputs) {
    if (item is List<Object>) { // (1)
      foo(item);
    } else if (item is ...) {
      ...
    }
  }
}
```

When run through the migration tool, line (1) is typically left unchanged (it is not changed to `if (item is List<Object?>)`), because the migration tool operates on evidence of nullability based on static analysis, and there's no such evidence that the list members need to be nullable.

This is a problem because the call sites (which might be in another package, migrated at a different time) might pass in a `List<Object?>` or `List<dynamic>`, e.g.:
```dart
void callSite() {
  someMethodThatAcceptsManyTypesOfInputs([1, 2, 3, null]); // `List<Object?> after migration
  someMethodThatAcceptsManyTypesOfInputs([]); // `List<dynamic>`
}
```

This can be particularly tricky to debug since it doesn't result in a static error or an assertion failure, simply in a change in the behavior of `someMethodThatAcceptsManyTypesOfInputs`.  It's particularly frustration when `someMethodThatAcceptsManyTypesOfInputs` is migrated prior to the call site, and the call site (before migration) is passing in `List<Object*>`, because `List<Object*>` satisfies the `is` check, but after migration, if it becomes `List<Object?>`, then that no longer passes the `is` check.  The only solution at that point is often to go back and fix the migration of `someMethodThatAcceptsManyTypesOfInputs` (which should have been migrated to check for `List<Object?>` in the first place).

Similar issues can arise for `as` casts, and when the type on the RHS is something other than a list (i.e. some other generic type, or a function type).

It might be better for the migration tool to bias towards making the type on the RHS of an `is` or `as` test as wide as possible (at least in the absence of strong evidence of non-null intent), so that this sort of problem doesn't arise.

Of course, there's non way for the migration tool to know for sure whether `is List<Object>` or `is List<Object?>` is really the better migration.  But the consequence of erroneously choosing `List<Object?>` is small (probably a few extra `!`s downstream of the `is` check), whereas the consequence of erroneously choosing `List<Object>` can be a real big pain.

**Comment by leafpetersen** [comment]
One of the ways of thinking about this is in terms of the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle).  We should always aim to *produce* things as non-nullable as possible, but we may wish to be more liberal with what we accept, at least in some cases.  A cast is an "acceptance" position, so there is an argument for being more liberal with it.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
