### ISSUE TITLE
[analyzer] NodeReplacer throws when replacing the block of a catch clause

### ISSUE THREAD

**Issue by shyndman** [dart-lang/sdk#47726]
Hi there,

I found a small issue in the implementation of `NodeReplacer.visitCatchClause`, which prevents catch cause replacement.

https://github.com/dart-lang/sdk/blob/cb33212b18e82d3d6b8ac0cccce499e40ee4cb5b/pkg/analyzer/lib/src/dart/ast/utilities.dart#L1728-L1740

You'll notice that there is no handling for the catch's body block, and as a result the code hits `visitNode`, and `visitNode` throws.

It's an easy fix. Happy to send a PR your way. For now I've gotten around it with a subclass.

Thanks!

**Comment by bwilkerson** [comment]
Glad you found a workaround. A PR would be much appreciated.

**Comment by shyndman** [comment]
So I put together a test case, ran it, and oddly, it didn't fail.

Turns out some code was added somewhat recently that invalidates the testing approach.

https://github.com/dart-lang/sdk/blob/cb33212b18e82d3d6b8ac0cccce499e40ee4cb5b/pkg/analyzer/lib/src/dart/ast/utilities.dart#L3011-L3022

The tests work by replacing a node with itself, then verifying that the tree isn't broken. With that early exit, the node replacement code isn't running.

BUT, on the upside, I commented out the early exit and tests are all passing (except for the one I added, yay!),.

Fixing this is a bit beyond the scope of what I'm wanting to do. Would you like me to send a PR for my catch body change, along with a test that will work when this other issue is resolved?

**Comment by bwilkerson** [comment]
@scheglov @srawlins

**Comment by shyndman** [comment]
So...still send the PR? I can at least fix one of the bugs.

**Comment by scheglov** [comment]
I will fix it, there is some work to be done in better testing.

**Comment by shyndman** [comment]
sg. Thanks.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/220806
