### ISSUE TITLE
dartdoc needs a keyword to identify the library section

### ISSUE THREAD

**Issue by Siksek** [dart-lang/sdk#47745]
Hello,

I was using dartdoc and found that one of my libraries didn't show its documentation content, I kept tracking and testing and found that if I added something like "**import**" after the library section then **dartdoc** will pick it up. The problem is that this library file does not need to import anything.

Below is an example (example.dart):
````
/// Contains used sizes
///
/// Contains different sizes based on the private variable _standardSize.
/// these sizes can be used for different things.

// Constant Static sizes that can be used in different cases
class Sizes {
  final smallSize = 8.0;
  final mediumSize = 12.0;
  final largeSize = 18.0;
}
````
This should show the documentation at the top but it is not shown until I add 'import' for example import 'dart:io';

So the code becomes like this:
````
/// Contains used sizes
///
/// Contains different sizes based on the private variable _standardSize.
/// these sizes can be used for different things.

import 'dart:io';

// Constant Static sizes that can be used in different cases
class Sizes {
  final smallSize = 8.0;
  final mediumSize = 12.0;
  final largeSize = 18.0;
}
````
And now the library documentation appears (also attached two images before and after).

* Dart SDK Version: Dart SDK version: 2.14.3 (stable)
* Linux (Ubuntu)
* Firefox and Chro
![after](https://user-images.githubusercontent.com/94785497/142760761-98eedbe7-2062-4189-9068-6e8bd7f4f136.png)
![before](https://user-images.githubusercontent.com/94785497/142760762-0e4c82b5-7dd0-426f-89e4-3841bb2a81a0.png)
me

**Comment by Siksek** [comment]
I found that ````import 'dart:core';```` is **better** as it removes the warning for 'unused_import'.

**Comment by lrhn** [comment]
If you want to document the library, use a library declaration:

```dart
/// Some library documentation.
library my.example.library;
```

It *would* be nice if you could omit the name, and only have the `library;` for annotations and documentation.

**Comment by Siksek** [comment]
So by that instead of using ````import 'dart:core';```` to mark the end of library documentation I need to use library declaration.
````
/// This library or that
/// Some library documentation
library my_example;

import 'other_lib.dart';
.
.
````
I agree with @Irhn regarding: to make the name optional if not provided use the file name itself.
