### ISSUE TITLE
prefer_if_null_operators refactoring introduces runtime error

### ISSUE THREAD

**Issue by grundid** [dart-lang/sdk#47747]
**Describe the issue**
The refactoring suggested by prefer_if_null_operators might introduce runtime errors.

**To Reproduce**
Given the Code 
```dart
bool multiline = true;
int maxLines = 10

int lines = maxLines != null ? maxLines : multiline ? 5 : 1;

```
The linter will suggest to convert it to 

```dart
int lines = maxLines ?? multiline ? 5 : 1;
```

At runtime this will result in `type 'int' is not a subtype of type 'bool'` error.

**Expected behavior**

```dart
int lines = maxLines ?? (multiline ? 5 : 1);
```

**Comment by pq** [comment]
Thanks for the report @grundid!  I've transferred the issue to the SDK (since that's where quick-fix implementations live).

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/239066
