### ISSUE TITLE
Make analyzer show an error if type is different after "??" check

### ISSUE THREAD

**Issue by d-apps** [dart-lang/sdk#47740]
Is it possible to add to analyzer to check the case where you put "??" ( to check if it is null ) and show error when the type of variable is different?

```
User{
 int id;

  factory User.fromJson(Map<String, dynamic> json){
    return User(
     id: json["id"] ?? "", // here the Dart analyzer could show an error, because if the json["id"] is null it will try to set a String to an int.
   );
  }

}
```

Thank you.

**Comment by bwilkerson** [comment]
We could potentially add a lint for that, but I suspect that it would have too many false positives to be of any value.

Under null safety, if you get rid of the `dynamic` by casting it to `int` (`return User(id: json["id"] as int ?? "");`) then you'll get an error because the type of the `??` expression is now `Object`, and implicit downcasts (except from `dynamic`) are an error.

**Comment by d-apps** [comment]
> We could potentially add a lint for that, but I suspect that it would have too many false positives to be of any value.
> 
> Under null safety, if you get rid of the `dynamic` by casting it to `int` (`return User(id: json["id"] as int ?? "");`) then you'll get an error because the type of the `??` expression is now `Object`, and implicit downcasts (except from `dynamic`) are an error.

Since the analyzer does not recognize that, it will be a runtime error right?

**Comment by bwilkerson** [comment]
If you're using an SDK with version `2.12.0` or later, and if your library hasn't opted out to an earlier version, then it should be opted in to the null safety feature and the code that includes the cast should produce a diagnostic. If you're running an earlier version (or the library has opted out to an earlier version) then you won't see a diagnostic.

If there's no diagnostic being produced by the analyzer, then, yes, it will be a runtime error. But the good news is that you can get better diagnostics by migrating your code to the latest version of the SDK.

If you're on `2.12.0` or later and you're not seeing a diagnostic when you add the cast, please let us know.

**Comment by d-apps** [comment]
![Screen Shot 2021-11-22 at 10 09 15](https://user-images.githubusercontent.com/20110433/142867325-e09ce7af-4710-42f0-882b-c420b2baa5e6.png)

Casting worked. I think it might be a good workaround for this problem, thank you @bwilkerson

**Comment by srawlins** [comment]
I'll close this for now, without further motivation for the lint.
