### ISSUE TITLE
Failures on [ CLI / Gardening ] Kill test subprocesses before deleting directories

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#47750]
These test failures seem real, and related to the commit https://dart-review.googlesource.com/c/sdk/+/220641
@bkonyi 

There are new test failures on [[ CLI / Gardening ] Kill test subprocesses before deleting directories](https://github.com/dart-lang/sdk/commit/2408d388782826227a32df5e59a769101819edca).

The tests
```
pkg/dartdev/test/commands/migrate_test RuntimeError (expected Pass)
pkg/dartdev/test/commands/pub_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

**Comment by bkonyi** [comment]
Can you add a link to the logs please?

**Comment by whesse** [comment]
Gee, I'm surprised there were no useful links automatically created.  Here is a link to the results page for that builder, and direct links to the failure logs and builds.

logs:
https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/18706/pkg/dartdev/test/commands/migrate_test
https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/18706/pkg/dartdev/test/commands/pub_test

Results feed:
https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=pkg/dartdev/test/commands/migrate_test
https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=pkg/dartdev/test/commands/pub_test

Current results:
https://dart-ci.firebaseapp.com/current_results/#/filter=pkg/dartdev/test/commands&showAll

Build:
https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release/18706/overview

**Comment by bkonyi** [comment]
Thanks for the logs Bill! I'll take a look.

**Comment by bkonyi** [comment]
Fix up for review [here](https://dart-review.googlesource.com/c/sdk/+/221543).
