### ISSUE TITLE
Dead code issue

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#47752]
```dart
if (false) ...[
    SizedBox(height: 24),
],
SizedBox(height: 16), // this gets highlighted as dead code
```
Expected: stop highlighting after [] is closed.
![image](https://user-images.githubusercontent.com/351125/143072539-1e3af9bc-aa74-48ab-aafa-8a16454c465a.png)

I'm in 2.15.0-116.0.dev (Flutter dev hasn't been updated for a while) but I searched and couldn't find any issues/fixes since September.

**Comment by bwilkerson** [comment]
@srawlins

**Comment by srawlins** [comment]
:( I thought I fixed this with https://github.com/dart-lang/sdk/issues/47305. Thanks for reporting!

**Comment by bernaferrari** [comment]
I think you probably did fix it, I'm using Dart from 2021-09-16. Can you test for me? It is kind of frustrating no one is updating Flutter for a while, so I can't check.
