### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by gisborne** [dart-lang/sdk#47751]
Just crashed. The analysis pane is frozen. I can scroll and select things, but eg double-clicking does nothing. It is showing some warnings I just fixed. Hitting Restart Dart Analysis Server 🔄 doesn't help.

Dart analyze from the command line works fine.

Huh. I was going to look for a log to send you, so I tried to open Preferences, and that doesn't work either.

Save All looks like it isn't working either. That's a bummer, because I'm a have to restart…

## Version information

- `IDEA AI-203.7717.56.2031.7784292`
- `2.14.4`
- `AI-203.7717.56.2031.7784292, JRE 11.0.10+0-b96-7249189x64 JetBrains s.r.o., OS Mac OS X(aarch64) v12.0.1, screens 3360.0x2100.0  Retina`

**Comment by srawlins** [comment]
Apologies that we did not get to this issue; closing as stale but please re-open if you see a crash like this on a recent version of Dart.
