### ISSUE TITLE
Remove dart:io's `Platform.packageRoot` and dart:isolate's `Isolate.packageRoot` APIs

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#47769]
The `dart:io` library contains a `packageRoot` API:

```dart
/// This returns `null`, as `packages/` directories are no longer supported.
///
@Deprecated('packages/ directory resolution is not supported in Dart 2')
static String? get packageRoot => null; // TODO(mfairhurst): remove this
```

Similarily in the isolate API:

```dart
/// The package root of the current isolate, if any.
///
/// This getter returns `null`, as the `packages/` directory is not supported
/// in Dart 2.
@Deprecated('packages/ directory resolution is not supported in Dart 2.')
external static Future<Uri?> get packageRoot;
```

As the deprecation comments state, this is not only deprecated but non-functional in Dart 2, and is hardcoded to return null. We should go ahead and remove it.

**Comment by mit-mit** [comment]
While the API doesn't currently work, removing the API is technically a breaking change, so tagging.

**Comment by mit-mit** [comment]
CL is https://dart-review.googlesource.com/c/sdk/+/221340

**Comment by devoncarew** [comment]
@bwilkerson - would `dart fix` help at all here? Is there any useful guidance we can have for deleted APIs - does flutter have any similar situations?

**Comment by mit-mit** [comment]
I don't think we need to spend any more time here -- I'm fairly sure there is a very minimal risk. Even `pub` has supported package directories for more than two years: https://github.com/dart-lang/pub/pull/1960

**Comment by mit-mit** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/71e3dac037b77c44114448e266ad4432c091fa0b

**Comment by zanderso** [comment]
This change is breaking the Dart roll into Flutter. See https://github.com/flutter/engine/pull/30231.

**Comment by mit-mit** [comment]
Sorry about that; PR to roll Engine is https://github.com/flutter/engine/pull/30236. Framework was already prepared in https://github.com/flutter/flutter/pull/94603
