### ISSUE TITLE
vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test fails in bare instructions mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#47761]
Removal of `--[no-]use-bare-instructions` revealed that this test was only passing in non-bare instructions mode. 

We should investigate why and whether this reveals an issue that our customer will also hit with their applications. (which are primarily deployed in bare instructions mode).

**Comment by mkustermann** [comment]
Merging into https://github.com/dart-lang/sdk/issues/51468
