### ISSUE TITLE
Implement `WeakReference`, `Finalizer` and `NativeFinalizer` in VM

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#47777]
For reference: [language proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/1847%20-%20FinalizationRegistry/proposal.md).

* [x] WeakReference
* [x] Finalizable
* [ ] Finalizer (in review)
* [ ] NativeFinalizer (in progress)

**Comment by a-siva** [comment]
Now that Finalizer and NativeFinalizer has landed, can this issue be closed?
