### ISSUE TITLE
Implement `WeakReference`, `Finalizer` in dart2js

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#47775]

**Comment by devoncarew** [comment]
@sigmundch - who's a likely owner here?

**Comment by sigmundch** [comment]
I'll follow up shortly on the owner (same with ddc). Most likely this will be the same person, since the implementation is likely to be the same for both.

**Comment by dcharkes** [comment]
@lrhn suggested that if `detach` is omitted in `Finalizer.attach` we use `value` as the detach object.

I'll update the documentation in the VM CL, but of course it should be implemented as such in Dart2JS as well then.

https://dart-review.googlesource.com/c/sdk/+/229544/8/sdk/lib/core/weak.dart#185

**Comment by rileyporter** [comment]
dart2js implementation landed in https://github.com/dart-lang/sdk/commit/278a040e1dcbd01b838103c00aa1effa7943ce04
