### ISSUE TITLE
No published analyzer available for language version 2.16.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#47790]
Since 2.16.0-dev releases are out, it'd be nice to have a corresponding pkg:analyzer

**Comment by kevmoo** [comment]
CC @scheglov

**Comment by srawlins** [comment]
I'm marking this P1 as this does break running any build-ecosystem builders in SDK dev channel. I think that's correct.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/221541
