### ISSUE TITLE
2.15 cherry pick request - rev DevTools version in SDK to latest 2.9.1

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#47805]
Commit to include: https://github.com/dart-lang/sdk/commit/44b93338d9467c1a9990cb796ad78cdef1f81a93

This is to ensure the latest DevTools (version 2.9.1) is included in the Dart 2.15 / Flutter 2.8 stable releases. User risk is low. This cherry pick is a necessary part of the DevTools release process now that we ship with the Dart SDK. See [example](https://github.com/dart-lang/sdk/issues/47644) of previous cherry pick.

**Comment by devoncarew** [comment]
What's the current DevTools version? Reving from what to `2.9.1`?

**Comment by kenzieschmoll** [comment]
Current DevTools version is 2.8.0 (note that the version number being the same as the flutter version number is more coincidence than intention - given that we release monthly, this version number is likely to get out of sync with flutter)

**Comment by devoncarew** [comment]
We're declining this as it's the week before the release (w/ a higher bar for cherry picks).

Generally though, this tool should be kept in sync with the VM? We may want a policy here for cherry picks - that the tool version we're cherry picking in not get too far ahead of the VM.
