### ISSUE TITLE
How to override a generic method bounded to a type variable?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#47808]
Take this example:

```dart
class A<T> {
  void on<E extends T>(E p) {}
}

class B extends A<String> {
  @override
  void on<E extends String>(E p) {}
}

void main() {}
```

analyzer reports no errors. CFE reports:

> Error: The parameter 'p' of the method 'B.on' has type 'E', which does not match the corresponding type, 'E', in the overridden method, 'A.on'.

Is there any way to legally implement `B`, a non-generic implementation of `A`? Making B generic makes the program legal:

```dart
class B<T> extends A<T> {
  @override
  void on<E extends T>(E p) {}
}
```

**Comment by eernstg** [comment]
Could it be a bug fix which is not yet present in the tools that were used?

The example seems to be essentially equivalent to https://github.com/dart-lang/sdk/issues/47510, and that one was fixed in https://github.com/dart-lang/sdk/commit/d83e78c7a37e86b8b70b34cee0777e9b516e314f.

**Comment by srawlins** [comment]
Confirmed this is fixed at HEAD
