### ISSUE TITLE
Different override behavior when implementing a concrete class in `src` vs `test`

### ISSUE THREAD

**Issue by btrautmann** [dart-lang/sdk#47803]
* Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "macos_x64"
* Mac OSX 11.6

This _is_ "just a question", but I don't know that StackOverflow is the best place for it considering it's not a "how do I do this?" as much as it is a "is this by design?":

I noticed when messing around with some testing strategies that there is a difference between using the `implements` keyword in source code and in test code.

For instance, consider this class:

```dart
// lib/src/test_file.dart
class MyCoolClass {
  final int _myCoolInt;

  MyCoolClass(this._myCoolInt);

  Future<int> doSomething() async {
    return _myCoolInt;
  }
}
```
If I, directly in the same file, implement this class:
```dart
// lib/src/test_file.dart
class MyFakeCoolClass implements MyCoolClass {

  @override
  // TODO: implement _myCoolInt
  int get _myCoolInt => throw UnimplementedError();

  @override
  Future<int> doSomething() {
    // TODO: implement doSomething
    throw UnimplementedError();
  }
}
```
I am forced to override both the private `_myCoolInt` and `doSomething()`.

However,

If I implement the _same_ class in a test file:
```dart
// test/test_file_2.dart
class MyFakeCoolClass implements MyCoolClass {

  @override
  Future<int> doSomething() {
    // TODO: implement doSomething
    throw UnimplementedError();
  }
}
```
I am only forced to implement the public function. Is this expected/by design? If so, I'm curious to understand the intention. If this _is_ expected, I have boiled down my approach to using this "feature" to create different variants of objects within my app, which is:

1. If the underlying injected dependencies (for instance a database or other storage mechanism) are already pre-configured for the current environment (e.g production would use database, test would use an in-memory strategy), you likely don’t need a fake and can always use the concrete implementation in your tests.

2. If `1` is not true and your fake _only_ needs to exist in a test, directly implement the concrete class within the test directory which won’t required you to implement its members.

3. If neither of the above are true, create an `abstract` class definition and have an "implementation-per-configuration". These classes should be easy to name uniquely because they should have an obvious purpose (a purpose that is unique per configuration, e.g production vs staging). This also doesn't feel too "smelly" because a staging X is as much a "production-y" object as a production X is.

Before I solidify this approach, I'd love to know if this is really a feature or if it's a bug.

**Comment by lrhn** [comment]
This is expected and by design.

Library private declarations like `_myCollInt` are only visible inside the same library. 

That's a problem if a class is used as an interface (which all classes can be), because you can't implement that member in another library. You can't *name* that member at all in another library, if you write `_myCoolInt` there, it's a different name, private to the other library.

So, the language allows you to ignore private members from other libraries when implementing an interface. Those members are just not there when the interface is seen from outside the library. The compiler then adds a synthetic
```dart
int get myCollInt => this.noSuchMethod(
  Invocation.getter(#_myCoolInt));  // symbol private to the original library!
```
declaration to your class, to ensure that you *actually* implement the full interface, even the part you can't specify yourself.

**Comment by btrautmann** [comment]
Ah, that's awesome. Thanks for the explanation! I'm going to close this now as that was a perfectly clear answer 👌
