### ISSUE TITLE
How to add vm flags to Self-contained executables (exe)

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#47818]
We run our Dart program with
```
dart run --disable-analytics --use_compactor=true --old_gen_growth_time_ratio=7 main.snapshot --port=8080
```

How do I add vm flags to self-contained executables?
```
./main --port=8080
```

**Comment by bkonyi** [comment]
There's currently no support for adding VM flags to self-contained executables. If you really need to provide VM flags you can write a wrapper script that invokes `dartaotruntime main.snapshot` with the relevant flags.

As a side note, `--use_compactor` and `--old_gen_growth_time_ratio` are both VM development flags and provide no support guarantees (e.g., they could break or be removed at any time), so I'd highly recommend avoiding the use of VM verbose flags for non-development purposes (cc @rmacnak-google).
