### ISSUE TITLE
VM doesn't build on macOS with mac_sdk_min = "10.15"

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#47820]
If I change `mac_sdk_min = "10.15"` in (`build/config/mac/mac_sdk.gni`), the build fails beause we use the deprecated method "SecTrustEvaluate":

```
FAILED: obj/runtime/bin/standalone_dart_io.security_context_macos.o 
/Users/athom/src/depot_tools/.cipd_bin/gomacc ../../buildtools/mac-x64/clang/bin/clang++ -MMD -MF obj/runtime/bin/standalone_dart_io.security_context_macos.o.d -DTOOLCHAIN_VERSION=9PhdU1KoAbaI6JR1uPmFEAwa-0A6IXjxHhoghP9Cy18C -DNDEBUG -DTARGET_ARCH_X64 -DDART_TARGET_OS_MACOS -I../../runtime -I../../third_party -I../.. -Igen -I../../runtime/include -I../../third_party/zlib -I../../third_party/boringssl/src/include -isysroot sdk/xcode_links/MacOSX11.3.sdk -mmacosx-version-min=10.15  -fno-exceptions -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Werror -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wno-tautological-constant-compare -Wno-unused-but-set-variable -Wpartial-availability -fdebug-prefix-map=/Users/athom/src/sdk=../.. -no-canonical-prefixes -stdlib=libc++ -Wheader-hygiene -Wstring-conversion -O3 -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++17 -fno-rtti -fno-exceptions -c ../../runtime/bin/security_context_macos.cc -o obj/runtime/bin/standalone_dart_io.security_context_macos.o
../../runtime/bin/security_context_macos.cc:315:14: error: 'SecTrustEvaluate' is deprecated: first deprecated in macOS 10.15 [-Werror,-Wdeprecated-declarations]
    status = SecTrustEvaluate(trust.get(), &trust_result);
             ^~~~~~~~~~~~~~~~
             SecTrustEvaluateWithError
sdk/xcode_links/MacOSX11.3.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:353:10: note: 'SecTrustEvaluate' has been explicitly marked deprecated here
OSStatus SecTrustEvaluate(SecTrustRef trust, SecTrustResultType *result)
         ^
1 error generated.
```

**Comment by whesse** [comment]
This call is already dead code when compiled for 10.14 or above - it is guarded in the else clause of
 if (__builtin_available(iOS 12.0, macOS 10.14, *)).

I think a CL just removing that check and else clause is the right fix, since we are dropping support for 10.13.

**Comment by athomas** [comment]
Hmm, but Flutter might still support older versions of iOS...

https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms

**Comment by whesse** [comment]
There is a pragma that can be used instead to disable the warning.
Also, the warning for a deprecated function should only appear if the deployment target is set to 10.15 or above. Should we be setting the deployment target to 10.13 explicitly?

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated"
  [my deprecated code]
#pragma clang diagnostic pop

**Comment by athomas** [comment]
I'm trying to raise the min SDK to 10.15 to fix the linker warnings and
because we no longer support macOS 10.14 and 10.15.

**Comment by a-siva** [comment]
> I'm trying to raise the min SDK to 10.15 to fix the linker warnings and because we no longer support macOS 10.14 and 10.15.

We no longer support macOS 10.13 and 10.14 correct ?

**Comment by athomas** [comment]
Correct: https://dart.dev/get-dart#macos

**Comment by athomas** [comment]
Additional context: https://chat.google.com/room/AAAAtyvwZMA/W4lg5xkiNwA

**Comment by a-siva** [comment]
Should we fix this using @whesse suggestion above ?

**Comment by mraleph** [comment]
Can we move this forward and bump out mac_sdk_min to at least 10.14 to match Flutter's buildroot?

**Comment by brianquinlan** [comment]
In progress PR: https://dart-review.googlesource.com/c/sdk/+/221629

**Comment by brianquinlan** [comment]
It looks like we can't set the min SDK version to 10.15 because flutter supports 10.14.

I have a [PR out](https://dart-review.googlesource.com/c/sdk/+/295389?tab=checks) that sets the minimum SDK version to 10.14 and includes the pragmas suggested by @whesse to allow us to use the deprecated `SecTrustEvaluate` function.

**Comment by brianquinlan** [comment]
@athomas I'm not sure what you want to do with this bug - the VM will build with `mac_sdk_min = "10.15"` but the actual set value is `"10.14"`.

**Comment by whesse** [comment]
We still want to land CL that removes the deprecated call, that is no longer supported in 10.15.

https://dart-review.googlesource.com/c/sdk/+/221629

That was blocked on support for MacOS 10.13, but also on continued support for iOS 11.
Comments on the CL say that removing support for iOS 11 is not immediately planned, so it can't be landed yet.

The pragmas added in the landed PR suffice for now, to enable compilation with target OS 10.15.
We could close this issue, and open another, saying to remove the deprecated call once iOS 11 is dropped.

**Comment by brianquinlan** [comment]
How about I just put a comment in `mac_sdk.gni` saying to remove those calls when `mac_sdk_min` is set to `10.15`? 

The person who makes the change is unlikely to miss it that way?

**Comment by brianquinlan** [comment]
I'll add the note: https://dart-review.googlesource.com/c/sdk/+/296424
