### ISSUE TITLE
dart:io stdin.readLineSync example should be updated for null-safety

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#47827]
https://api.dart.dev/stable/2.14.4/dart-io/dart-io-library.html states:

> To read text synchronously from the command line (the program blocks waiting for user to type information):
> 
> ```dart
> String inputText = stdin.readLineSync();
> ```

This example is no longer valid with NNBD and should be updated to use `String?` (or `var`) instead of `String`.  Even better would be to include a null check in the example:

```dart
String? inputText = stdin.readLineSync();
if (inputText != null) {
  // Do something with [inputText].
}
```

FWIW, since NNBD was enabled, there have been a lot of questions on StackOverflow from people who copy/paste old, null-unsafe examples for reading from `stdin` and don't understand why their code isn't working. (I doubt that the majority of them were following this specific example, though.)

**Comment by brianquinlan** [comment]
The example has been updated to be:
`String? inputText = stdin.readLineSync();`
https://api.dart.dev/stable/2.18.6/dart-io/dart-io-library.html
