### ISSUE TITLE
Add DevTools version to `dart --version` output

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#47825]
We do this for `flutter --version`
```
flutter --version
Flutter 2.6.0-12.0.pre.749 • channel master • git@github.com:flutter/flutter.git
Framework • revision 92d2a9ab06 (2 weeks ago) • 2021-11-17 15:56:35 -0500
Engine • revision d389ae475c
Tools • Dart 2.16.0 (build 2.16.0-20.0.dev) • DevTools 2.8.0
```

This will allow tools and users to understand which version of DevTools is included in the Dart SDK.

**Comment by bkonyi** [comment]
Would adding a `dart devtools --version` option be sufficient? I think we rely on the format of the version string output from `dart --version` in some situations, so that would likely be breaking.

**Comment by kenzieschmoll** [comment]
I think `dart devtools --version` would still work

**Comment by kenzieschmoll** [comment]
@DanTup can you confirm whether this will work for detecting the DevTools version from inside VS code?

**Comment by DanTup** [comment]
Yep, `dart devtools --version` would work fine for me. Although, if we're going to use commands like this from tools, it would be nice if there was an option for structured output (for ex. json) rather than text to avoid any cosmetic changes breaking things (as seems to be the concern above).

**Comment by bkonyi** [comment]
Closed in https://github.com/flutter/devtools/pull/3546
