### ISSUE TITLE
[dart:js_util] js_util methods ignore type arguments

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#47832]
```
import 'dart:html' as html;
import 'dart:js_util' as js_util;

void main() {
  js_util.setProperty(
    html.window,
    '_tmp',
    'string',
  );
  var function = js_util.getProperty<Function>(
    html.window,
    '_tmp',
  );
}
```
The above succeeds even though `getProperty`'s return type is `T`, where `T` is the function's singular type argument.

Modifying the above to:

```
  var function = js_util.getProperty(
    html.window,
    '_tmp',
  ) as Function;
```

gives the expected `TypeError`: `Error: Expected a value of type 'Function', but got one of type 'String'`. This is true for both web compilers. This likely also applies for other `js_util` methods beyond `getProperty`, like `setProperty` and `callMethod`, but I haven't verified.

cc @rileyporter

**Comment by sigmundch** [comment]
This may have been on purpose and not related to any optimization.

The code in https://github.com/dart-lang/sdk/blob/master/sdk/lib/js_util/js_util.dart#L71  is inferred as having `<T>` as the type parameter of the `JS` expression, which means that the compiler will trust that the result is `T`:
```
T getProperty<T>(Object o, Object name) => JS<T>('Object|Null', '#[#]', o, name);
```

We could change the body of getProperty to explicitly use dynamic and introduce an implicit cast in the body of these methods:
```
T getProperty<T>(Object o, Object name) => JS<dynamic>('Object|Null', '#[#]', o, name);
```

That would then show up as a cast in ddc and with -O2 but will again get omitted with -O3.

Today's JS-interop ignores the types, so the change here is aligned with what JS-interop does today. Adding the implicit cast may be a nice gradual way of adding additional checking, but not adding additional cost in production when -O3 is in use. Thoughts?

**Comment by srujzs** [comment]
Good points, I'll reword the title to reflect this.

I think `<dynamic>` is the way forward, and accurately assumes it can not know the value of the `JS` call. Users using the type argument will intend for it to be checked, as the Dart equivalent e.g. `T foo<T>() => 0 as dynamic` would. This also is sufficiently different from some of the unchecked behavior in interop today as it's not from `package:js` nor do `Interceptor`s come into play.
