### ISSUE TITLE
IDE auto-imports first implementation library over public export of implementation library

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#47842]
I think
- a) `Don't import implementation files from another package.` shouldn't show up for package:collection?
- b) package:collection/ should export(?) the extensions?

![image](https://user-images.githubusercontent.com/351125/144519468-19f297bf-09f2-47a9-a7c1-2a090edf0be4.png)

With https://github.com/dart-lang/sdk/issues/45680 recommending firstWhereOrNull, I can't use it without this warning.

**Comment by bwilkerson** [comment]
That library is exported from the public library of the package, which can be imported using
```dart
import 'package:collection/collection.dart';
```

**Comment by lrhn** [comment]
And the warning definitely should show up. The warning is for your protection.
Never import files in `src/` directories, not unless you are the author of both packages and know what you're doing.

**Comment by bernaferrari** [comment]
So is this an IDE issue? Because the IDE auto imported the src/ file now that it imports extensions.

**Comment by bwilkerson** [comment]
> ... the IDE auto imported the src/ file ...

Yes, that's a known bug (I haven't looked to see whether there's an issue open for it). The IDE support currently doesn't have the information necessary to determine which public libraries should be imported in order to import something that's declared in a `src` library, so it currently defaults to importing the library containing the declaration.

@scheglov Perhaps we can talk soon about efficient ways to capture that information.

**Comment by srawlins** [comment]
@bernaferrari can you say which IDE auto-imported the library in `src/`?

**Comment by bernaferrari** [comment]
Intellij

**Comment by scheglov** [comment]
I can reproduce the issue.
https://dart-review.googlesource.com/c/sdk/+/222243

We should know extensions exported from a library, and probably should use exported namespaces instead of looking at declarations.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/223441

**Comment by scheglov** [comment]
The issue was fixed with the CL above.
I'm landing one more clean up https://dart-review.googlesource.com/c/sdk/+/223741
