### ISSUE TITLE
CFE computes some function types in field initialization parameters incorrectly

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#47847]
Consider the following program.

```dart
class A {
  final Function(Function(int)) foo;
  A(this.foo(Function(int)));
}
```

When compiled by the CFE it shows the following compile-time error message:

```
/tmp/asdf.dart:3:10: Error: The type of parameter 'foo', 'dynamic Function(dynamic Function(dynamic))' is not a subtype of the corresponding field's type, 'dynamic Function(dynamic Function(int))'.
Try changing the type of parameter 'foo' to a subtype of 'dynamic Function(dynamic Function(int))'.
  A(this.foo(Function(int)));
         ^
/tmp/asdf.dart:2:33: Context: The field that corresponds to the parameter.
  final Function(Function(int)) foo;
```

It seems that the type of the formal parameter is incorrectly computed as `Function(Function(dynamic))`, and the expected type is `Function(Function(int))`.

**Comment by eernstg** [comment]
The initializing formal parameter gets its type from the old-style function type which is specified "around" the name of the parameter, and old-style function types use a single identifier as the parameter name, assuming the type `dynamic`, as opposed to new-style function types where the parameter name can be omitted.

```dart
class A {
  final Function(Function(int)) foo;
  A(this.foo(Function(int p))); // This should do it.
}
```

**Comment by chloestefantsova** [comment]
@eernstg Thanks for clarifying that! I assume that we can close the issue now as a non-issue? 🙂

**Comment by eernstg** [comment]
Certainly! And, in passing, noting that the choice to consider a single identifier as a parameter name and not a type is _hugely_ confusing. It keeps tripping up everybody who gets in touch with it. 😄

**Comment by chloestefantsova** [comment]
> It keeps tripping up everybody who gets in touch with it. 😄

I guess you can increase the body count with my case 😄
