### ISSUE TITLE
iOS: Dart_TimelineEvent is surprisingly slow

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#47850]
This tracker is for issues related to:
* Dart VM

## Description

I was doing some performance testing on iOS and noticed that 7% of CPU time was spent in `GetCurrentThreadCPUMicrosForTimeline`.  It is the second hottest symbol I'm executing beyond memcpy (I'm copying thousands of buffers that are a megabyte big for microbenchmarks).  Compared to the other symbols, some that are also doing system calls, it's shocking how much CPU time it is taking.

<img width="1154" alt="Screen Shot 2021-12-03 at 3 36 44 PM" src="https://user-images.githubusercontent.com/30870216/144686320-77daf763-b1f6-4e9e-90e0-fcc2dc2147c3.png">

## Steps to reproduce

1) Check out https://github.com/flutter/flutter/tree/master/dev/benchmarks/platform_channels_benchmarks
2) Make the following code change so channels use `compute` (which will call Dart_TimelineEvent which calls GetCurrentThreadCPUMicrosForTimeline)\
```diff
--- a/packages/flutter/lib/src/services/platform_channel.dart
+++ b/packages/flutter/lib/src/services/platform_channel.dart
@@ -57,7 +57,10 @@ class BasicMessageChannel<T> {
   /// Returns a [Future] which completes to the received response, which may
   /// be null.
   Future<T?> send(T message) async {
-    return codec.decodeMessage(await binaryMessenger.send(name, codec.encodeMessage(message)));
+    final ByteData? encodedResult =
+      await binaryMessenger.send(name, codec.encodeMessage(message));
+    return compute<ByteData?, T?>(codec.decodeMessage, encodedResult);    
+//    return codec.decodeMessage(await binaryMessenger.send(name, codec.encodeMessage(message)));
   }
```
3) Run the platform channels benchmarks with `flutter run --profile` with instruments running a Time Profiler probe.

## Profile

<img width="1111" alt="Screen Shot 2021-12-03 at 3 47 33 PM" src="https://user-images.githubusercontent.com/30870216/144686902-b7ff9a89-87d5-4a7b-8a11-2766a6c8aceb.png">

All of the time is in the thread_info call.

## Version
Dart version 2.16.0 (build 2.16.0-56.0.dev)

## Evaluation

Can't we just use the system clock for Dart_TimelineEvent, why does it have to be the clock from thread_info?

**Comment by rmacnak-google** [comment]
We record both monotonic wall time and thread time, both of which are visualized in Catapult.

**Comment by gaaclarke** [comment]
Maybe there should be a way to opt out of it since I'm not using Catapult then.  Since we know the cost is high to query the thread time it should be optional.

**Comment by gaaclarke** [comment]
Updates on this:
 * This is an impediment for providing more tracing for flutter users: https://github.com/flutter/flutter/pull/100926
 * I've added a microbenchmark that shows Timeline events are 2x slower on iOS than android: https://flutter-flutter-perf.skia.org/e/?begin=1643949613&end=1648138606&queries=sub_result%3Dtimeline_with_arguments&requestType=0
 * I've suggested we add the ability to change the sample rate of the `thread_info` calls and us the clock time as a way to interpolate: https://github.com/flutter/flutter/pull/100926#issuecomment-1086361759

**Comment by zanderso** [comment]
Re-opening based on https://github.com/dart-lang/sdk/issues/47850#issuecomment-1086401613. Esp. concerned if this is blocking https://github.com/flutter/flutter/pull/100926.

**Comment by gaaclarke** [comment]
Here are the benchmarks for changing the samplerate of `thread_info`.  `timeline` is a microbenchmark calling Timeline events over and over again.  `build` is a macrobenchmark where we are rebuilding Flutter frames over and over again.  The microbenchmarks suggest a samplerate of 100khz but the macrobenchmark suggests as a samplerate of 2khz.  I bet this is because we are using timeline events with arguments frequently in Flutter which limits the benefit of the change since JSON encoding is so expensive.  I'll have to double check how we are using those parameters.  If they are not useful in profile builds we should rip them out.

delay (µs) | samplerate (hz) | timeline wo/ arguments (µs) | savings | timeline w/ arguments (µs) | savings | build benchmark w/ trace user widgets (µs) |  
-- | -- | -- | -- | -- | -- | -- | --
0 | inf | 3.6314 |   | 4.9332 |   | 989.1 |  
1 | 1000000 | 3.0432 | 16.20% | 4.4318 | 10.16% | 988.8974224 | 0.02%
5 | 200000 | 1.9845 | 45.35% | 4.5912 | 6.93% | 986.5451496 | 0.26%
10 | 100000 | 1.6052 | 55.80% | 4.3707 | 11.40% | 949.0230292 | 4.05%
100 | 10000 | 1.4908 | 58.95% | 4.5289 | 8.20% | 958.1759182 | 3.13%
250 | 4000 | 1.4384 | 60.39% | 4.3411 | 12.00% | 920.6610814 | 6.92%
500 | 2000 | 1.4905 | 58.96% | 4.373 | 11.36% | 891.3721179 | 9.88%

Link to benchmarks:
- timeline - https://github.com/flutter/flutter/blob/master/dev/benchmarks/microbenchmarks/lib/foundation/timeline_bench.dart
- build - https://github.com/flutter/flutter/blob/master/dev/benchmarks/microbenchmarks/lib/stocks/build_bench.dart

**Comment by bkonyi** [comment]
As mentioned on flutter/flutter#100926:

@rmacnak-google might have a better way of doing this that doesn't involve approximating thread time and is quite a bit faster (quick results show ~3x improvement on some simple C programs when using the current `GetCurrentThreadCPUMicros()` implementation and one that uses `clock_gettime_nsec_np(CLOCK_THREAD_CPUTIME_ID) / 1000` instead). I'll follow up later whether or not this approach pans out.

**Comment by gaaclarke** [comment]
@bkonyi awesome, I'll pause the approximation work until I hear back.  Let me know if you want help measuring the change against Flutter.

**Comment by gaaclarke** [comment]
I tested the change against `build_bench.dart` with `debugProfileBuildsEnabled` and it went from 3371.8 µs to 2403.9 µs (29% decrease in build time).  This blows the approximation off of the system clock away.  It does require newer operating systems.  But iOS 10 can support the iPhone 5 which was released 10 years ago so I don't think we need to try to do the approximation stuff for the older operating systems.  Thanks @rmacnak-google and @bkonyi .

**Comment by zanderso** [comment]
FYI we'll soon be increasing the minimum supported iOS version to iOS 11.

**Comment by gaaclarke** [comment]
closed via https://dart-review.googlesource.com/c/sdk/+/240148/7/runtime/vm/os_macos.cc#111

**Comment by gaaclarke** [comment]
This resulted in a 72% increase in Timeline performance for no parameters and a 46% increase in Timeline performance with parameters for the Timeline benchmarks:

https://flutter-flutter-perf.skia.org/e/?begin=1649245654&end=1649459529&keys=X910e8b4ac5857b2178ba24fd805d071d&requestType=0

Good work everybody.
