### ISSUE TITLE
build systems implementation for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47862]
See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

**Comment by devoncarew** [comment]
cc @jakemac53

**Comment by itsjustkevin** [comment]
@jakemac53 has this work been completed?

**Comment by jakemac53** [comment]
There shouldn't be any work involved for the build systems in theory. I haven't personally tested anything though.

**Comment by jakemac53** [comment]
I did test things out in build_runner and both super parameters and enhanced enums appear to work as expected 👍

**Comment by itsjustkevin** [comment]
@jakemac53 to clarify, it seems this work is all complete, can we close this issue?
