### ISSUE TITLE
Angular compiler implementation for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47868]
See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

**Comment by devoncarew** [comment]
Internal issue: b/209865741 

cc @leonsenft

**Comment by leafpetersen** [comment]
FYI, the flag has been flipped so these can be used without a flag internally now.

**Comment by jodinathan** [comment]
is there any public repo of Angular to test this feature?

**Comment by leafpetersen** [comment]
This is still in progress.  cc @grouma

**Comment by mattrberry** [comment]
The internal bug has just been wrapped up. All set to close this issue now.

**Comment by leafpetersen** [comment]
Thanks!
