### ISSUE TITLE
Kythe implementation for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47867]
See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

**Comment by devoncarew** [comment]
cc @emmanuel-p

**Comment by leafpetersen** [comment]
FYI, the flag has been flipped so these can be used without a flag internally now.

**Comment by leafpetersen** [comment]
@emmanuel-p can you confirm this is done?

**Comment by emmanuel-p** [comment]
Basic support is implemented.
Some improvements are planned.
Tracked internally by b/225119276.
