### ISSUE TITLE
web debugging support for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47863]
See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

**Comment by devoncarew** [comment]
cc @annagrin

**Comment by sigmundch** [comment]
This is likely simply require adding a few tests for the debugger and expression evaluation. We expect the implementation to be entirely handled by the CFE lowering, though.

**Comment by annagrin** [comment]
The work required:
- adding tests for new expressions in expression evaluation tests, 
- validating that completion works in devtools

**Comment by Markzipan** [comment]
Update: tests added in https://github.com/dart-lang/sdk/commit/e68c3e8bc86bd07ebd39886544444125f9de1e5c

**Comment by sigmundch** [comment]
@Markzipan - I'm closing this assuming there is nothing more to do, but please reopen if I missed something.
