### ISSUE TITLE
SegFault with FFI binding to native library

### ISSUE THREAD

**Issue by boekhold** [dart-lang/sdk#47879]
Dart SDK version: 2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "linux_x64"
Ubuntu 20.04 Focal

I am receiving a Segfault from the Dart VM on exit of my program, which is related to my FFI bindings to the `libsane` library.

```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x7fa0aadb0160
version=2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "linux_x64"
pid=930912, thread=930921, isolate_group=(nil)((nil)), isolate=(nil)((nil))
isolate_instructions=0, vm_instructions=55ef14d7b580
Stack dump aborted because GetAndValidateThreadStackBounds failed.
/home/boekhold/local/flutter/bin/internal/shared.sh: line 223: 930912 Aborted                 (core dumped) "$DART" "$@"
```

A test case is available in the following repository:
https://github.com/boekhold/dart-sane-segfault

Also refer to the following  discussion on Google Groups involving @dcharkes :
https://groups.google.com/a/dartlang.org/g/misc/c/-w0zIbk8YhM

**Comment by mraleph** [comment]
Based on https://bugzilla.redhat.com/show_bug.cgi?id=1065695 which @dcharkes has pointed too there is likely a problem in how SANE interacts with dynamic library loading. I suggest you try loading the library manually via `dlopen` and never unload it (as opposed to using `DynamicLibrary` APIs which would unload the library when execution finishes).

**Comment by boekhold** [comment]
> I suggest you try loading the library manually via `dlopen` and never unload it (as opposed to using `DynamicLibrary` APIs which would unload the library when execution finishes).

Apologies if this is a stupid question, but how do I manually use `dlopen` inside a Dart program?

**Comment by mraleph** [comment]
`dlopen` and `dlsym` are also just a C functions which could be called through FFI. Something like this (this loads `libm.so.6` and looks up `pow`): 

```dart
import 'dart:ffi';
import 'package:ffi/ffi.dart';

void main() {
  final dlopen = DynamicLibrary.process().lookupFunction<
      Pointer<Void> Function(Pointer<Utf8>, Int32),
      Pointer<Void> Function(Pointer<Utf8>, int)>('dlopen');
  final dlsym = DynamicLibrary.process().lookupFunction<
      Pointer<Void> Function(Pointer<Void>, Pointer<Utf8>),
      Pointer<Void> Function(Pointer<Void>, Pointer<Utf8>)>('dlsym');

  const RTLD_LAZY = 0x00001;
  print(dlopen);
  print(dlsym);

  final libm = dlopen(
    "libm.so.6".toNativeUtf8(), // note: toNativeUtf8 leaks memory
    RTLD_LAZY,
  );
  print(libm);

  final pow =
      dlsym(libm, "pow".toNativeUtf8()) // note: toNativeUtf8 leaks memory
          .cast<NativeFunction<Double Function(Double, Double)>>()
          .asFunction<double Function(double, double)>();
  print(pow(2.0, 3.0));
}
```

**Comment by boekhold** [comment]
Thanks @mraleph. Unfortunately it doesn't make a difference. You can see my changes in the "dlopen" branch in the repository: https://github.com/boekhold/dart-sane-segfault/blob/dlopen/listdevices.dart. Still getting the same segfault.

I don't really want to speculate because I just don't know enough about this stuff. Having said that (:-)) it's quite possible that SANE itself is doing something wrong in their handling of threads. I checked their code, and pthreads **are** used inside SANE backends. The 'test' backend definitely uses threads. I also checked the source code of the "epsonscan2" backend, which also uses pthreads.

**Comment by boekhold** [comment]
The cause of the SEGFAULT was identified by the SANE team as being a specific driver that is loaded by default on most distributions. Disabling this driver gets rid of the segfault. This wasn't specific to my Dart FFI bindings...

https://gitlab.com/sane-project/backends/-/issues/542

**Comment by boekhold** [comment]
> > The cause of the SEGFAULT was identified by the SANE team as being a specific driver that is loaded by default on most distributions. Disabling this driver gets rid of the segfault. This wasn't specific to my Dart FFI bindings...
> > https://gitlab.com/sane-project/backends/-/issues/542
> 
> do you fix this? and how?

The issue is with the "hpaio" driver, so I disabled that by editing `/etc/sane.d/dll.d/hplip` and commenting out the line that says `hpaio`.
