### ISSUE TITLE
Faulty doc comment in FormatException

### ISSUE THREAD

**Issue by Leptopoda** [dart-lang/sdk#47876]
Hi there,
reading the doc comment of the FormatException there seems to be an index error. 
https://github.com/dart-lang/sdk/blob/c29e1c6a58f477de5985efc007b65a339f6142b7/sdk/lib/core/exceptions.dart#L53-L54

shouldn't it be `0 <= offset <= source.length -1` or `0 <= offset < source.length`.

If this is indeed an error I'm happy to open a PR for it :upside_down_face:

**Comment by lrhn** [comment]
It's actually correct. It's quite possible to have a format error at the *end* of input, most likely something missing. For example:
```dart
var json = '{"x": 42'; // missing '}'.
jsonDecode(json); // Throws format exception with position at the end of the source.
```
