### ISSUE TITLE
`sync*` methods generate much larger code than non.

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#47874]
The following program:

```dart
void main() {
  print(iter1());
  print(iter2());
}

Iterable<String> iter1() sync* {
  yield 'Hello';
  yield 'World';
  yield '!';
}

Iterable<String> iter2() {
  return <String>[
    'Hello',
    'World',
    '!',
  ];
}
```

Generates >1KiB for the `sync*` version but only 167b for the one that returns a list. I would not have been surprised to learn that the `sync*` generated slightly larger code, but I'm surprised it's that much bigger.

It seems like this should be an easy case to optimize into something that returns a list and saves some code size/heap space/memory. 

Flutter ends up with a lot of small functions that are called like this in exception handlers that seem to add up to more code size than needed.

**Comment by lrhn** [comment]
It's not that surprising that it's big code. I'd expect a *best case* implementation to be equivalent to:
```dart
Iterable<String> iter1() => _$iter1();

class _$iter1 extends Iterable<String> {
  _$Iterable(): super();
  Itearator<String> get iterator => _$iter1$Iterator<String>()
}

class _$iter1$Iterator<String> implements Iterator<String> {
  String? _current = null;
  int _state = 0;
  _$iter1$Iterator(): super();

  String get current => _current ?? (_current as String);

  bool moveNext() {
    switch (_state) {
      case 0: 
        _current = "Hello";
        _state = 1;
        return true;
      case 1:
       _current = "World";
       _state = 2;
       return true;
     case 2:
       _current = "!";
       _state = 3;
       return true;
    default:
       _current = null;
       return false;
    }
  }
}
```
That's pretty optimal, and recognizes that the method has no *arguments*, that it returns immediately after the last yield (so "state 4" and "done" can be combined), that the function has no *state* (no local variables) and no loops, or even nested blocks, any of which would complicate the implementation. The compiler is ready for that complication, and it might not always be able to get rid of all of it when it's not needed.

This function has such an incredibly simple design that it can be implemented as `get iterator => ["Hello", "World", "!"].iterator;`. Most `sync*` functions aren't that simple, so I'm not surprised the compilers aren't trying to optimize for that (or other very simple patterns).

**Comment by dnfield** [comment]
```dart
Iterable<String> iter3() => _$iter3();

class _$iter3 extends Iterable<String> {
  Iterator<String> get iterator => <String>['Hello', 'World', '!'].iterator;
}
```

Ends up showing up as about halfway between `iter1` and `iter2`, including the code size for the `_$iter3` class. This still isn't as good as just returning the list, which is an iterable. I don't really agree that it leaks implementation details - no sane user could ever cast it safely to a List.

However, I suspect even if the compiler optimizes for this it'll still be less efficient and. have weird performance cliffs. Perhaps a lint would be more appropriate, e.g. one that tells you "this generator is simple enough to be rewrite as a non-generator, and would save code size and execution speed if you did." /cc @pq

In Flutter's codebase, very simple `sync*` generators are very common. We try to avoid them because they have shown performance issues in the past, although I don't know that we've looked at code size related to them before, and sometimes new ones get added because its a covenient language feature for developers (rather than because they _really_ need lazy generation). See https://cs.opensource.google/search?q=%22%20sync*%20%7B%22&ss=flutter

**Comment by dnfield** [comment]
I suspect many of our users also write sync* code that is trivially converted to a `List` as well, but have not done as much research there.

**Comment by pq** [comment]
/fyi @mraleph 

> Perhaps a lint would be more appropriate, e.g. one that tells you "this generator is simple enough to be rewrite as a non-generator, and would save code size and execution speed if you did."

Interesting idea.  I'd argue for improved readability too.

@munificent: do you have any effective Dart advice on idiomatic/judicious use of generator functions?

**Comment by munificent** [comment]
> @munificent: do you have any effective Dart advice on idiomatic/judicious use of generator functions?

No, I find they are very rarely used or even known about. I think they are a valuable feature, but I can't recall seeing what I would consider an abusive use of `sync *` where it would be easy to just return a list instead. Most of the few cases where I see `sync *` are for patterns that would be very difficult or slow to return an eager list.

**Comment by dnfield** [comment]
@munificent - I am not convinced there is a single proper usage of sync* in Flutter's codebase. There are a large number of functions that got cargo-culted like this:

```
  informationCollector: () sync* {
    yield DiagnosticsNode<Foo>(...);
  }
```

These functions are always eagerly evaluated in the codebase, and they're not expensive to evaluate. Someone likely thought it was easier to write that way, particularly before some of the ui-as-code improvements came for `List` like for loops and conditionally adding elements. Each one of these adds about 1kb of code to every Flutter application.

This is code written by experienced Dart developers, but it's an antipattern. We've mainly limited these methods to debug-only or exception-handling only, but even in the exception-handling only case it is now bloating code size.

**Comment by munificent** [comment]
> There are a large number of functions that got cargo-culted like this:
> 
> ```
>   informationCollector: () sync* {
>     yield DiagnosticsNode<Foo>(...);
>   }
> ```

Wild. I have never seen examples like in code that I've reviewed.

> This is code written by experienced Dart developers, but it's an antipattern.

Agreed.

**Comment by pq** [comment]
>  Perhaps a lint would be more appropriate, e.g. one that tells you "this generator is simple enough to be rewrite as a non-generator, and would save code size and execution speed if you did."

I'm all for exploring this.  The rub I guess is in defining "simple generator" in a way that captures a meaningful number of cases.  Happy to experiment if folks want to bounce around ideas.

**Comment by mraleph** [comment]
The current difference between these two functions is much smaller (after @alexmarkov has reworked implementation of suspending functions).

On X64 the first one is 93 bytes and the second one is 182 bytes. The is still 2x difference, but it's much smaller than before, so I am going to close the issue.  

We have no immediate plans to try and squeeze more out of it, we definitely don't plan to perform the sort of fusion described in https://github.com/dart-lang/sdk/issues/47874#issuecomment-988912049
