### ISSUE TITLE
Need a googlesource repo for flutter/gallery

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#47882]
In order to analyze flutter/gallery in the flutter-analyze bot (for https://github.com/dart-lang/sdk/issues/47527), we need a googlesource repo:

https://dart.googlesource.com/external/github.com/flutter/gallery

**Comment by whesse** [comment]
@athomas @sortie Any thoughts on this? The existing external/github.com/flutter mirrors are copied from the GoB github mirror, as shown in their setup: "gob-ctl show dart/external/github.com/flutter/flutter".  I assume we just want mirrors on dart.googlesource of the repos we use in a checkout of a builder.

**Comment by athomas** [comment]
Yes, we should just create this mirror.

**Comment by sortie** [comment]
My only concern is that we use Flutter gallery as a code size benchmark and moving it to another repository will likely break those benchmarks.

**Comment by whesse** [comment]
Done: https://dart.googlesource.com/external/github.com/flutter/gallery

Flutter gallery is not moving, just being mirrored to GoB.

**Comment by srawlins** [comment]
🎉  Thansk it works great!
