### ISSUE TITLE
The --enable-vm-service= flag doesn't work with the "dart language-server" command

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#47880]
This might be expected, but I wanted to check before changing anything in VS Code...

Sometimes to track down analysis server issues, I ask users to enable the VM Service for the analysis server to open Observatory or connect DevTools. In Dart v2.15.0 we switched from using `dart sdk-path/bin/snapshots/analysis_server.dart.snapshot` to `dart language-server` and that seems to have prevented this from working.

Eg,:

```
dart --enable-vm-service=8123 sdk-path/bin/snapshots/analysis_server.dart.snapshot --lsp
```

will output:

```
Observatory listening on http://127.0.0.1:8123/dJ_UTkyYsZg=/
```

However,:

```
dart --enable-vm-service=8123 language-server
```

will not (and nothing will be bound to port 8123).

I don't know if this is a bug or there's something special about how `"dart language-server"` works. If required, I could switch back to using the snapshot when we need to run with the VM Service enabled, but since the goal was to avoid clients needing to know about the snapshots and their locations, I'd like to check that's necessary before doing so.

@bkonyi @bwilkerson

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by bkonyi** [comment]
`dart language-server` currently spawns a secondary process, so the `--enable-vm-service` flag isn't being forwarded to the server process.

**Comment by DanTup** [comment]
@bkonyi do you know where the code that spawns the process is? I found [`LanguageServerCommand`](https://github.com/dart-lang/sdk/blob/1c571a12fa1d4b13b363546360dbf5ff765bdf4e/pkg/dartdev/lib/src/commands/language_server.dart#L40) but as far as I can tell it's all in-progress from there down.

**Comment by bkonyi** [comment]
We spawn the secondary process [here](https://github.com/dart-lang/sdk/blob/main/pkg/dartdev/lib/src/analysis_server.dart#L108).

**Comment by bkonyi** [comment]
Oh, I think I confused this with the analysis server. I'll look more closely.

**Comment by DanTup** [comment]
Oh, I see - I think there are two different paths here:

- `dart fix` and `dart analyze` commands go through the code you linked
- `dart language_server` which I think uses [a different path](https://github.com/dart-lang/sdk/blob/1c571a12fa1d4b13b363546360dbf5ff765bdf4e/pkg/dartdev/lib/src/commands/language_server.dart#L40)

The first two are spawning servers for their own use (and don't have flags for things like using the LSP protocol), and the second just runs the server directly (and passes all of the analysis server flags over).

This issue is specifically about the second one, so I don't _think_ it's caused by an additional process, but I'm not very familiar with the code so could be mistaken.

**Comment by bkonyi** [comment]
So I think this is WAI. The VM service doesn't advertise itself if it's expecting a DDS instance to connect since it doesn't know which URI to advertise until that happens. Since DDS is only wired up to be started via `dart run --observe` (or implicitly via `dart --observe foo.dart`), the VM service is never advertised when you invoke `dart --observe language-server`.

This behavior can be disabled by passing `--no_dds` which will configure the VM service to advertise it's URI as soon as it's finished initializing. However, running this way will also prevent DevTools from being served since we're not going through the `dart run` flow. Also, you won't have a great debugging experience since you'll be debugging an app-jit snapshot with no sources.

I think the right thing to do here is to run `pkg/dartdev/bin/dartdev.dart` directly. This way you'll have a DDS instance, access to a DevTools instance, and the ability to inspect sources. Something like this seems to work: `dart --observe pkg/dartdev/bin/dartdev.dart language-server`.

**Comment by DanTup** [comment]
> So I think this is WAI. The VM service doesn't advertise itself if it's expecting a DDS instance to connect since it doesn't know which URI to advertise until that happens.

The issue here wasn't just the banner, it also doesn't binding to the provided port (manually trying to connect on the port that was passed doesn't work). Should that work?


> Also, you won't have a great debugging experience since you'll be debugging an app-jit snapshot with no sources.

Ah, interesting. Is that different to when running from the `analysis_server.snapshot` file, or the same? The sources themselves probably aren't that important, but being able to use CPU/Memory profiler in DevTools could be.

Today it's possible in VS Code to do this (if Dart-Code runs the `.snapshot` file directly, instead of the `language_server` command):

- set the `dart.analyzerVmServicePort` setting in VS Code workspace settings (this restarts the analysis server)
- run `dart devtools`
- use the port number configured above to connect DevTools to the analysis server's VM Service
- Use CPU Profiler, Memory Profiler, Debugger, etc. in DevTools

I'm not sure from the above how much of this would be lost if `dart language_server` supported the VM Service. If it's just sources missing, but CPU/memory profiler still give useful information (valid class/method names etc.) then it's probably still useful. If none of that will work, then it's probably better for VS Code to just fall back to the `.snapshot` file in the case where this port number has been set.


> I think the right thing to do here is to run `pkg/dartdev/bin/dartdev.dart` directly

To be clear - this is for other users that won't have the SDK sources. The use case here is if a user has high analysis_server memory usage or CPU that we can't reproduce, this allows us to easily get CPU/memory profiles from them. It's very infrequently used, but sometimes it can be useful.

For someone _with_ the SDK sources, `pkg/analysis_server/bin/server.dart` can be run directly (via the `dart.analyzerPath` setting in VS Code), and everything works as expected there.


Given how infrequently this is used though, unless this is just a simple bug that's easily fixed (or, if it won't support getting good memory/cpu profiles), I think using the `.snapshot` in VS Code (when the `dart.analyzerVmServicePort` setting is set) is probably the simplest way to resolve this. On the chance the `.snapshot` ceases to be (or moves/renames), it breaking temporarily isn't critical (the setting is only used temporarily, there's a prompt at startup to remind you when it's enabled encouraging you to turn it off).

**Comment by DanTup** [comment]
> Maybe the simplest way forward here is just to pass `--no_dds` when a service port is provided?

Ah, that seems to work fine - thanks!


> maybe it's worth considering making requests directly to the service from VSCode to get the details you're interested in and manually dump the responses to files on disk so users don't need to try and connect with a DevTools instance.

It's hard to know what might be useful in advance. This is a bit of an escape hatch so if we can't repro/understand an issue, there's a way to give the user (potentially customised) instructions for getting additional useful info. It's not used that often so not really worth doing much work for it, but it's useful to have if there are no other options for getting more info.

Thanks!
