### ISSUE TITLE
Analyzer reports error for a valid constant expression

### ISSUE THREAD

**Issue by kinex** [dart-lang/sdk#47896]
After upgrading to Flutter 2.8.0, the following code results analyzer error (this error was not shown in Flutter 2.5.3):

```dart
  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(horizontal: kIsWeb ? 16 : 8),
      child: Text("foo"),
    );
  }

```
The error message is:

> In a const constructor, a value of type 'Null' can't be assigned to the field 'right', which has type 'double'.
> Try using a subtype, or removing the keyword 'const'.dart(const_constructor_field_type_mismatch)
 
The confusing error message is related to https://github.com/dart-lang/sdk/issues/46792.

Anyway, the code should not result any error as `kIsWeb` is defined as:
```dart
const bool kIsWeb = identical(0, 0.0);
```

If I remove the `const` from `Padding`, I get a warning 

> Prefer const with constant constructors dart(prefer_const_constructors)

Dart SDK version: 2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "macos_x64"
VS Code version 1.63.0 (Mac)
Dart Code version 3.29.0

**Comment by kinex** [comment]
Actually I just open my project in VS Code (version 1.63.0, Dart Code version 3.29.0, Mac) and the errors (total of 239 errors related to this) appear in the Problems tab.

**Comment by ZiyadF296** [comment]
Yes, I am experiencing this exact same issue with the exact code!
```dart
padding: const EdgeInsets.symmetric(horizontal: kIsWeb ? 10 : 4),
```

Error:
```dart
A value of type 'Null' can't be assigned to a parameter of type 'double' in a const constructor.
Try using a subtype, or removing the keyword 'const'.dartconst_constructor_param_type_mismatch
```

It used to work normally and as expected before Dart 2.15.

However, I am still able to run and compile my apps normally, it's just the errors are confusing and slowing my productivity when seeing red lines where I shouldn't.

**Comment by srawlins** [comment]
CC @scheglov regarding `kIsWeb`

**Comment by scheglov** [comment]
I can reproduce this with
```dart
const bool intVsDouble = identical(0, 0.0);

void f() {
  const A(intVsDouble ? 0 : 1);
}

class A {
  const A(int _);
}
```

My theory is that we don't handle `UNKNOWN_VALUE` well, and treat it somewhere as `null`.

**Comment by scheglov** [comment]
Apparently this is an intentional change, but maybe now we know that this code does cause issues.
https://github.com/dart-lang/sdk/blob/052fbd3103fd7e4fa4936e6ba03d0ad454a74b3d/pkg/analyzer/lib/src/dart/constant/evaluation.dart#L626-L630

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/224120
