### ISSUE TITLE
Invoking methods from abstract classes

### ISSUE THREAD

**Issue by ebelevics** [dart-lang/sdk#47893]
I'm using method from abstact class
`typedef Converters<View, Data> = FutureOr<Data?> Function(View? view);`

but after using it I receive for this example
`type '(String?) => String?' is not a subtype of type '(dynamic) => dynamic'`

why is this happening? For some reason I thought Dart 2.15 would solve this. Otherwise I need to replace typedef with abstract class and then extending with ordinary class which does work, but it makes code much more boilery, for exact same effect.

**Comment by mraleph** [comment]
You need to provide a more complete reproduction of the problem. I'd guess you did not properly instantiate the type somewhere so `Converters` ends up being `(dynamic) => dynamic` - but what exactly happened is hard to say without seeing more code.

**Comment by ebelevics** [comment]
here is small example to produce the problem
```
typedef Converters<ViewT, DataT> = FutureOr<DataT?> Function(ViewT? view);

abstract class AbstractControl<ViewT, DataT> {
  late ViewT? initValue;
  final Converters<ViewT?, DataT?> convertToData;
  AbstractControl({this.initValue, required this.convertToData});
}

class Control<ViewT, DataT> extends AbstractControl<ViewT, DataT> {
  Control({
    ViewT? initValue,
    required FutureOr<DataT?> Function(ViewT? val) convertToData,
  }) : super(initValue: initValue, convertToData: convertToData);
}

main() {
  final Map<String, AbstractControl> controls = {
    "firstName": Control<String, String>(
      initValue: "abc",
      convertToData: (val) => val,
    ),
    "lastName": Control<String, String>(
      initValue: "xyz",
      convertToData: (val) => "test + $val",
    ),
  };

  controls.forEach((key, control) {
    final data = control.convertToData(control.initValue);
  });
}
```

**Comment by mraleph** [comment]
Yeah this is a known problem. It is reduced to:

```dart
class C<T> {
  void Function(T) f;
  C(this.f);
}

void main() {
  C<dynamic> o = C<String>((String v) { });
  o.f("smth");  // throws: type '(String) => Null' is not a subtype of type '(dynamic) => void'
}
```

This is a corner case in the type-system: generics are covariant, but `T` is used in the contravariant position in `void Function(T)` making it unsound unless there is a dynamic check which verifies a match between declared and actual types in runtime (or alternatively there is a dynamic type check at the entry to the closure - which is something we want to avoid).

So    

```dart
void main() {
  C<dynamic> o = C<String>((String v) { });
  o.f("smth");
}
```

is compiled as 

```dart
void main() {
  C<dynamic> o = C<String>((String v) { });
  (o.f as void Function(dynamic))("smth");
}
```

Which should explain the error. 

See https://github.com/dart-lang/language/issues/1137 for the deeper discussion.
