### ISSUE TITLE
The document for NetworkInterface.listSupported needs to be updated

### ISSUE THREAD

**Issue by abcxcba** [dart-lang/sdk#47894]
https://api.dart.dev/stable/2.14.4/dart-io/NetworkInterface/listSupported.html
 bool listSupported
Whether the list method is supported.
**The list method is currently unsupported on Android.**

NetworkInterface.list now supports Android.
https://github.com/dart-lang/sdk/commit/78340fdf8264b42b980a76c2462aabba8c2ee78a

code:
```
  print('Android NetworkInterface.listSupported :' + NetworkInterface.listSupported.toString());
  print('all interfaces: $interfaces');
```
output:
```
I/flutter ( 6674): Android NetworkInterface.listSupported :true
I/flutter ( 6674): all interfaces: [NetworkInterface('radio0', [InternetAddress('10.0.2.16', IPv4)])]
```

**Comment by brianquinlan** [comment]
Fixed https://github.com/dart-lang/sdk/commit/9b2b9df09e5fe5cacd4bb056c7b97bbea39b6ffd
