### ISSUE TITLE
Report analysis_options options implicit-casts or implicit-dynamic as deprecated

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#47902]
Need to write new (or use existing) infra for reporting uses of `implicit-casts: false` (replaced by `strict-casts: true`) and `implicit-dynamic: false` (replaced by `strict-raw-types: true`) in analysis_options.yaml.

**Comment by bwilkerson** [comment]
Please add this to `OptionsFileValidator`. It will be easier to maintain if all the checks are together.

**Comment by dcharkes** [comment]
@srawlins 6a54fdd46e2df14c9a7b4fd9d6b2d6e181ca0b7a broke the flutter-analyze bot.

Flutter needs to be migrated.

**Comment by srawlins** [comment]
Agreed ☹️  will revert.
