### ISSUE TITLE
No release date for 2.15.0 in changelog

### ISSUE THREAD

**Issue by sebe** [dart-lang/sdk#47909]
Hi @mit-mit fyi - Dart changelog entry for 2.15.0 is missing release date.
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#2150

thanks

**Comment by mit-mit** [comment]
cc @athomas

**Comment by mit-mit** [comment]
https://dart-review.googlesource.com/c/sdk/+/223424
