### ISSUE TITLE
How to update external memory size (`Dart_UpdateFinalizableExternalSize`) for a `Dart_CObject` of type `Dart_CObject_kNativePointer `?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#47901]
Hi thanks for this wonderful lib! I wonder how to update external memory size (`Dart_UpdateFinalizableExternalSize`) for a `Dart_CObject` of type `Dart_CObject_kNativePointer `?

I know `Dart_UpdateFinalizableExternalSize` but it requires a DartHandle. But I only have a Dart_CObject which contains a native pointer.

Related: https://github.com/fzyzcjy/flutter_rust_bridge/issues/243

**Comment by mraleph** [comment]
Please don't use this type. It was introduced for some internal usage and has somewhat confusing semantics.

**Comment by fzyzcjy** [comment]
Thank you!
