### ISSUE TITLE
ROUNDSD instruction executed on non-SSE4.1 x86_64 processors

### ISSUE THREAD

**Issue by Crazywater** [dart-lang/sdk#47907]
Continuing from https://github.com/dart-lang/webdev/issues/1465

Something in Dart emits a `roundsd` instruction which is only supported with SSE4.1 on non-SSE4.1 processors. This breaks `dartdevc` on my machine when compiling the `fixnum` package. I *think* dartdevc is using a VM snapshot so this should be VM related?

```
0x7ffff57c1ec7      roundsd $0xb,%xmm0,%xmm1
```

To get to this I used (from a directory running a web app with `package:fixnum`)

```
gdb dart
(gdb) run /usr/lib/dart/bin/snapshots/dartdevc.dart.snapshot --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_outline_sound.dill --modules=amd --no-summarize -o /tmp/scratch_spaceYKUSEU/packages/fixnum/fixnum.sound.ddc.js --source-map --packages=org-dartlang-app:///.dart_tool/package_config.json --module-name=packages/fixnum/fixnum --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/lib/dart/lib/libraries.json --experimental-emit-debug-metadata --reuse-compiler-result --use-incremental-compiler --used-inputs-file=/tmp/ddk_builder_MIHLLO/used_inputs.txt package:fixnum/src/int64.dart package:fixnum/fixnum.dart package:fixnum/src/intx.dart package:fixnum/src/int32.dart --sound-null-safety
[...]
Thread 7 "DartWorker" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff177f700 (LWP 7978)]
0x00007ffff57c1ec7 in ?? ()
(gdb) layout asm
>0x7ffff57c1ec7      roundsd $0xb,%xmm0,%xmm1
0x7ffff57c1ecd      movaps %xmm1,%xmm0      
0x7ffff57c1ed0      mov    0x17(%r15),%r12  
0x7ffff57c1ed4      callq  *0x7(%r12)       
0x7ffff57c1ed9      push   %rax             
0x7ffff57c1eda      pop    %rax             
0x7ffff57c1edb      mov    -0x10(%rbp),%r15 
0x7ffff57c1edf      mov    %rbp,%rsp        
...
```

Version is 2.15.0:
```
$ dart --version
Dart SDK version: 2.15.0 (stable) (Unknown timestamp) on "linux_x64"
```

**Comment by Crazywater** [comment]
Looking around a likely reason could be 16e8dc257e51d48669ce8d5d91ac094325faa5b5, I think 2.14 still worked for me. @alexmarkov

**Comment by Crazywater** [comment]
I wonder if this just happens because the `dartdevc` VM snapshot shipped in the Dart SDK is a snapshot from a machine *with* SSE 4.1 so the checking logic in 16e8dc257e51d48669ce8d5d91ac094325faa5b5 says it's ok to emit `roundsd`.

There is special logic for AOT compilation, but likely using a snapshot built on a machine with SSE4.1 and using that on pre-SSE4.1 is problematic?

**Comment by mraleph** [comment]
See also https://github.com/flutter/flutter/issues/94181

I think you analysis is correct - we train app-jit snapshots on modern CPUs so app-jit snapshots end up containing SSE4.1 instructions. We should probably introduce a special flag which sets CPU features to the lowest supported configuration when training app-jit snapshots and use the same trick we do for AOT compilation to emit code which uses runtime feature detection.

**Comment by alexmarkov** [comment]
@mraleph It looks like we always had this problem with app-jit snapshots: code in app-jit snapshots could be generated for one set of CPU features but snapshot could be copied and executed on another machine with a different set of CPU features. With my changes this problem became more apparent as we're now using roundsd instruction in unoptimized code.

For SSE4.1 specifically there is `--no-use-sse41` flag on ia32 and x64 which can be used to disable SS4.1 features:

https://github.com/dart-lang/sdk/blob/ecdf148428934522b8a3a0f0f7d8729ddde81584/runtime/vm/cpu_x64.cc#L19

https://github.com/dart-lang/sdk/blob/ecdf148428934522b8a3a0f0f7d8729ddde81584/runtime/vm/cpu_x64.h#L31-L34

As a quick fix, we can probably enable this flag when training app-jit snapshots during Dart SDK build on ia32/x64.

On other architectures we have similar flags (e.g. `--no-use_vfp`, `--no-use_neon`, `--no-use_integer_division`). Maybe we should introduce one platform-independent option (something like `--target-unknown-cpu`) to disable all optional CPU features and enable this option by default when generating app-jit snapshots.

@mraleph @a-siva @rmacnak-google @mkustermann WDYT?

**Comment by mraleph** [comment]
> On other architectures we have similar flags (e.g. `--no-use_vfp`, `--no-use_neon`, `--no-use_integer_division`). Maybe we should introduce one platform-independent option (something like `--target-unknown-cpu`) to disable all optional CPU features and enable this option by default when generating app-jit snapshots.

+1. Yep, I think this is the way to go.

**Comment by rmacnak-google** [comment]
Since we no longer support ARMv5TE and ARMv6, we probably can remove `--use_vfp`. My understanding is Debian armhf implies vfp.
