### ISSUE TITLE
noSuchMethod for static calls, new

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#4790]
Right now it doesn't seem possible to intercept constructor calls or static calls via noSuchMethod.
Is that intended? Of course, noSuchMethod on the instance wouldn't work, but I'd expect to be able to hook it on the class somehow (and libraries eventually :) )

class Foo {
&nbsp;&nbsp;bar() =&gt; print('its a bar');
&nbsp;&nbsp;noSuchMethod(name, args) =&gt; 'NSM $name';
&nbsp;&nbsp;// not legal: static noSuchMethod(name, args) =&gt; 'NSM $name';
}

void main () {
&nbsp;&nbsp;print(new Foo().baz);
&nbsp;&nbsp;// how to intercept this? print(Foo.quux);
&nbsp;&nbsp;// or this? print(new Foo.fisk());
}

**Comment by jmesserly** [comment]
I think metaclass DEP would support this?
Anyway, I'm happy to close. This issue is pretty old by this point.

**Comment by jirkadanek** [comment]
I am not sure I see how metaclass DEP (https://github.com/gbracha/metaclasses/blob/master/proposal.md, as reference for people finding this issue first) supports this. Would I then be able to define a static method noSuchMethod on my class, which would then become the regular method noSuchMethod on the metaclass? And failed static method lookups will be redirected to calling it?
