### ISSUE TITLE
What happens if the `Dart_CObject_kNativePointer`'s size is not updated accurately? Since IMHO it is just a hint, I guess it should not cause serious problems?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#47900]
Hi thanks for the wonderful language! I wonder what happens if the `Dart_CObject_kNativePointer`'s size is not updated accurately? Since IMHO it is just a hint, I guess it should not cause serious problems?

Related: https://github.com/fzyzcjy/flutter_rust_bridge/issues/243

**Comment by mraleph** [comment]
External size is just an input to GC scheduling heuristic. 

However please don't use this type. It was introduced for some internal usage and has somewhat confusing semantics.

**Comment by fzyzcjy** [comment]
@mraleph Thank you!
