### ISSUE TITLE
[Windows] DynamicLibrary.open() prints incorrect error code

### ISSUE THREAD

**Issue by jjanku** [dart-lang/sdk#47911]
Hi, I believe `status` should be passed to ` Utils::SCreate()`, not `error`:
https://github.com/dart-lang/sdk/blob/6c98722611e93a4b2f9332bdaa1f03df87ba4ed9/runtime/platform/utils.cc#L363-L364

**Comment by a-siva** [comment]
@jjanku thanks for pointing this out, will submit a PR to fix this.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/223742
