### ISSUE TITLE
dart fix for `prefer_final_parameters` not fixing everything

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#47912]
I tried enabling `prefer_final_parameters` for the flutter repository and fixing all violations with `dart fix --apply`. While it auto-fixes a lot of violations, it doesn't catch all of them. In fact, across the entire repository, 3432 violations are missed.

To reproduce:
1. Enable `prefer_final_parameters` in https://github.com/flutter/flutter/blob/master/analysis_options.yaml#L166
2. Run `dart fix --apply` (I recommend trying this in a subdirectory like `packages/integration_test` for faster turn-around time)
3. Run `flutter analyze .` (e.g. in `packages/integration_test`)
4. Observe that not all warnings have been fixed.

Examples that have not been fixed, but look auto-fixable:
* https://github.com/flutter/flutter/blob/9f7848f80f176a5caf05ea19f7aaa0cfcb78583c/packages/integration_test/lib/integration_test_driver.dart#L79
* https://github.com/flutter/flutter/blob/9f7848f80f176a5caf05ea19f7aaa0cfcb78583c/packages/integration_test/lib/integration_test_driver.dart#L78
* https://github.com/flutter/flutter/blob/9f7848f80f176a5caf05ea19f7aaa0cfcb78583c/packages/integration_test/lib/integration_test_driver.dart#L34

There are many more...

**Comment by parlough** [comment]
Thanks for the reproduction examples, I can take a look sometime over the next few days.
