### ISSUE TITLE
[CP - stable channel] [vm/aot] Visit TypeParameterType.promotedBound in tree shaker - 1777f769abc9ea7f2a7e2c70c3e1635a838bc199

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#47914]
**commit(s) to merge**: 1777f769abc9ea7f2a7e2c70c3e1635a838bc199

**merge instructions**: clean merge

**What is the issue**: AOT compilation fails with error "Invalid argument(s): Missing canonical name for Reference" in a flutter app

**What is the fix**: If tree shaker doesn't visit TypeParameterType.promotedBound which contains the only reference to a particular class it may remove that class, leaving a dangling reference from promotedBound. After that kernel AST serialization would crash with "Missing canonical name for Reference" error.

**Why cherrypick**: This error was encountered by a Flutter app developer when building their app for release and it is possible other developers would also encounter this issue

**Risk**: Low (has test case)

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/47878

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by a-siva** [comment]
Comment this cherry pick is being requested for the Flutter 2.8 / Dart 2.15 stable channel.
It is also a candidate for cherry picking into the recent Dart 2.16 beta 1 branch

**Comment by a-siva** [comment]
//cc @alexmarkov

**Comment by whesse** [comment]
This was not merged to 2.16 beta 1, and it is included in 2.16 beta 2, which has been branched and will be released next week (Jan 12).

It was not merged to 2.15 stable during the hotfix window this week, and therefore not suggested as a hotfix for Flutter 2.8 in its hotfix window this week.  That is the last hotfix window for Flutter 2.8.

It will be in 2.16 stable, and Flutter 2.10, at the end of the month.  So it seems like no further action will be taken on this merge request, unless we want to do a merge to stable today and tell Flutter to do a hotfix for 2.8.

**Comment by a-siva** [comment]
> It was not merged to 2.15 stable during the hotfix window this week, and therefore not suggested as a hotfix for Flutter 2.8 in its hotfix window this week. That is the last hotfix window for Flutter 2.8.
> 
Do we know why it was not merged into 2.15 stable ?

**Comment by whesse** [comment]
There was a thread on the flutter release chat, saying there were no hotfix requests and so no patch release would be done, and I didn't speak up about this one, as I thought others were tracking it.

**Comment by whesse** [comment]
Actually, I thought it had already been merged, and it had, in stable 2.15.1.  By me, on Dec 14th.  So it has been merged, closing this issue.
