### ISSUE TITLE
Undefined va_list usage in syslog_android.cc

### ISSUE THREAD

**Issue by fvrmatteo** [dart-lang/sdk#47939]
Hi all,

I was testing some code on Android using Dart 2.13.0 and involving the [Syslog::VPrint](https://github.com/dart-lang/sdk/blob/main/runtime/platform/syslog_android.cc#L18) and [Syslog::VPrintErr](https://github.com/dart-lang/sdk/blob/main/runtime/platform/syslog_android.cc#L27) functions and realised the code was crashing with a SIGSEGV inside the call to `__android_log_vprint`, specifically while dereferencing a pointer retrieved as first argument from the `va_list`.

The issue is related with the fact that the same `va_list` is being used first by `vprintf`, effectively consuming all the arguments and leaving the `va_list` in a modified state and then by `__android_log_vprint` which will start the parsing of the arguments where `vprintf` left, therefore accessing "undefined" values that will be subsequently used as pointers (in my case).

If I'm not mistaken about the described behaviour, the issue seems to be affecting multiple Dart VM versions.

**Comment by rmacnak-google** [comment]
Good catch! We shouldn't be reusing the same va_list between the two prints.
