### ISSUE TITLE
[dart:io] Support HttpServer2

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#47946]
Would it be possible to add support for HttpServer2 in dart?

Reasons:
- Websockets only work internally with autobahn. 
  Without autobahn support we use Sse (package:sse) that sends post events for bi-directional communication, which is very inefficient for frequent events (such as debug events sent by flutter profiling)
- We might have only autobahn option in the near future for DDR due to uberproxy changes.

**Comment by mhoad** [comment]
I’m also very interested in this as well.

**Comment by mraleph** [comment]
@annagrin are you asking for a server supporting HTTP/2 protocol or specifically for bindings to a specific _internal_ implementation of HTTP/2? 

For former `package:http2` _should_ probably be sufficient.
For later bindings will have to reside in the internal repo and can't be part of the SDK.

**Comment by annagrin** [comment]
@mraleph I didn't know there is a difference. I know there are c++ implementations of HttpServer2 internally that supports autobahn and I was hoping to have a wrapper of it in dart.

**Comment by a-siva** [comment]
//cc @brianquinlan

**Comment by mraleph** [comment]
Given that this issue mentions a bunch of internal only technologies, I suggest we close this one and file an internal issue, otherwise we can't really have a discussion here.

**Comment by brianquinlan** [comment]
I already reached out to annagrin@ asking her to file an internal bug. I'm going to close this one now.

If anyone *outside* of Google is interested in HTTP2 support for Dart, there is the [http2](https://pub.dev/packages/http2) package. If that is not sufficient, please file another bug.
