### ISSUE TITLE
Add a fix for the sort_unnamed_constructors_first lint

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#47954]
It would be good to have a fix for the `sort_unnamed_constructors_first` lint.

**Comment by HelioStrike** [comment]
Wrote a fix for this at https://dart-review.googlesource.com/c/sdk/+/231900.

**Comment by asashour** [comment]
I guess this is resolved.

**Comment by bwilkerson** [comment]
Yes, thanks.
