### ISSUE TITLE
VM silently crashes when awaiting DirectoryWatcher's ready event if the directory does not exist

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#47967]
I'm trying to update the analysis server to use the `DirectoryWatcher`'s `ready` event to avoid losing events (related to https://github.com/dart-lang/watcher/issues/115), however I found that if a directory does not exist, awaiting `watcher.ready` immediately terminates the VM with no error/message.

```dart
import 'package:watcher/watcher.dart';

main() async {
  // Try to watch a folder that does not exist
  final watcher = DirectoryWatcher('/tmp/foo');

  // Print any events/errors from the stream.
  final sub = watcher.events.listen(
    (event) => print(event.type),
    onError: (e) => print('ERROR ON STREAM: $e'),
  );

  // Wait for the watcher to become ready.
  print('waiting for ready...');
  try {
    await watcher.ready;
    print('watcher is ready!');
  } catch (e) {
    print('ERROR WAITING FOR READY: $e');
  }

  print('DONE!');
  sub.cancel();
}
```

I would expect this code to print `watcher is ready` or `ERROR WAITING FOR READY` but it actually just prints (and then terminates):

```
waiting for ready...
ERROR ON STREAM: FileSystemException: Directory listing failed, path = '/tmp/foo/' (OS Error: No such file or directory, errno = 2)
(process exists, seemingly cleanly)
```

So it enters the `try` block, but then appears to terminate without any message without completing the `try` or `catch` blocks. If you comment out `await watcher.ready`, it runs as you would expect, so it seems like awaiting `watcher.ready` is causing the issue if the directory doesn't exist.

I'm not sure if this is a `package:watcher` issue or SDK issue, but since the VM is terminating, here seemed like the best place.

**Comment by aam** [comment]
I would not say vm crashes - the program just terminates without `watcher.ready` completing(with neither boolean nor error).

Also note that dart sdk Directory `watch` method works as expected:
```
import 'dart:async';
import 'dart:io';
import 'dart:isolate';

final dir = Directory('/tmp/foo');
worker(_) {
  if (dir.existsSync()) {
  	throw 'directory $dir should not be present';
  }
  dir.create();
  print('created $dir');
}

main() async {
  final dir = Directory('/tmp/foo');
  if (dir.existsSync()) {
  	dir.deleteSync(recursive: true);
  }
  print('watching $dir');
  await Future.delayed(Duration(seconds: 1));
  dir.watch().listen((e) { print('got $e');});
  await Isolate.spawn(worker, null);
}
```

```
╰─➤  xcodebuild/DebugX64/dart dir_watch_test.dart                                                                                  watching Directory: '/tmp/foo'
created Directory: '/tmp/foo'
got FileSystemCreateEvent('/tmp/foo')
```

**Comment by DanTup** [comment]
> I would not say vm crashes - the program just terminates without watcher.ready completing(with neither boolean nor error).

If `watcher.ready` never completes, I would expect the program never to terminate (since it's being `await`ed in the `main` function). For example, if I await `Future.delayed(const Duration(seconds: 100))`, the app will wait 100 seconds before terminating, it doesn't just terminate immediately?

**Comment by aam** [comment]
`Future.delayed` is different from just awaiting some `Future`. `Future.delayed` creates a timer which keeps program active until that timer fires. `await Future` by itself doesn't keep program ticking. Consider
```
import 'dart:async';

void main() async {
  print('starting...');
  await Completer<String>().future;
  print('all done');
}
```

```
$  xcodebuild/DebugX64/dart s1.dart
starting...
$
```

**Comment by DanTup** [comment]
Oh wow, TIL. I always thought `Future`-returning `main`s were allowed to complete before exiting!

Thanks for clarifying. I ended up with this when I was trimming down a bug I'm seeing in the analysis server (where `ready` never seems to fire), and I thought this might've been the same issue but manifesting itself a little different. I guess that's not the case, so I'll try to get a more solid repro from it and re-file.

Sorry for the noise!

**Comment by DanTup** [comment]
Actually, I think this is the same issue - but the repro above was just bad. Here I've added an additional `Future.delayed(const Duration(seconds: 10));` at the top that ensure the app does not quit within 10 seconds:

```dart
import 'package:watcher/watcher.dart';

main() async {
  // Ensure app doesn't quit for at least 10s
  Future.delayed(const Duration(seconds: 10));

  // Try to watch a folder that does not exist
  final watcher = DirectoryWatcher('/tmp/foo');

  // Print any events/errors from the stream.
  final sub = watcher.events.listen(
    (event) => print(event.type),
    onError: (e) => print('ERROR ON STREAM: $e'),
  );

  // Wait for the watcher to become ready.
  print('waiting for ready...');
  try {
    print('waiting for watcher');
    await watcher.ready;
    print('watcher is ready!');
  } catch (e) {
    print('ERROR WAITING FOR READY: $e');
  }

  print('DONE!');
  sub.cancel();
}
```

This app stalls on `await watcher.ready` still, and the app remains around for 10 seconds before exiting without having progressed pass the `await`. My understanding from the comments at https://github.com/dart-lang/watcher/issues/115 is that we should use this event to know when we can continue, but if it never completes then the server is going to stall.

It seems like `ready` is a watcher concept and not from the SDK though, so I'll re-file this in `package:watcher`.
