### ISSUE TITLE
[Dart Analysis Server] IntelliJ does not suggest imports for excluded files in analysis_options.yaml

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#47965]
* Dart SDK Version: 2.15.1
* OS: Windows

**Steps to reproduce:**
1. Exclude a file from analysis in a project's analysis_options.yaml
2. Try to import types in the excluded file from another file

Suggestions should work even with files that have been excluded in the project's analysis_options.yaml.  If I remember correctly, this used to be the case previously.

This is frustrating to work with as code generation often produce files that do not conform to a project's lints and hence need to be excluded. However, these files are still imported when editing other non generated files. 

With excluded files:
![with ignored files](https://youtrack.jetbrains.com/api/files/74-1234895?sign=MTY0MDA0NDgwMDAwMHwxMS04NDU5NTl8NzQtMTIzNDg5NXxkYVNfWVFrZHhZSmYxME0zd2lLbG9E%0D%0AY3BDWUpVSFQwWGlIM3RwMUJQNVRnDQo%0D%0A&updated=1639736478098)

Without excluded files:
![without ignored files](https://youtrack.jetbrains.com/api/files/74-1234901?sign=MTY0MDA0NDgwMDAwMHwxMS04NDU5NTl8NzQtMTIzNDkwMXxNSmE1ME9TdkFYcERtaHptWWh0UWZp%0D%0ATlNoeW83VTN3YjFhYVkyWGcydUQ4DQo%0D%0A&updated=1639736585010)

I originally created an [issue](https://youtrack.jetbrains.com/issue/WEB-54086) on IntelliJ's side but was redirected here.

**Comment by srawlins** [comment]
Thanks for filing an issue. Certainly there is a downside to excluding those files, and there is a downside to including them (suggesting them when they would not be useful).

I suspect it is more useful to not suggest excluded files that to suggest them; this behavior may be best as it is.

As far as analyzing generated files, file generators can now include `// ignore_for_file: type=lint` to ignore all lint rules. See upcoming documentation here: https://github.com/dart-lang/site-www/issues/3576 (hopefully published at https://dart.dev/guides/language/analysis-options soon).

**Comment by Pante** [comment]
> 
Having generated files include the new "ignore all lints" comment will certainly be far better solution. Is there any ETA on when that will be available?

**Comment by srawlins** [comment]
It should be available in Dart 2.15.0. If a package generates a file for your project which violates various lint rules, and you'd like it to feature such an `// ignore_for_file` comment, you'll have to file an issue with the package's maintainers.

**Comment by Pante** [comment]
> It should be available in Dart 2.15.0. If a package generates a file for your project which violates various lint rules, and you'd like it to feature such an `// ignore_for_file` comment, you'll have to file an issue with the package's maintainers.

That's great to hear, thanks so much for the quick reply!
