### ISSUE TITLE
Failures on Rewrite any URIs to canonical, not only file://.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#47961]
There are new test failures on [Rewrite any URIs to canonical, not only file://.](https://github.com/dart-lang/sdk/commit/df48d2f74405d32e97b630672a9414bf91c5ba2b).

The tests
```
pkg/analyzer/test/src/dart/analysis/driver_test RuntimeError (expected Pass)
```
are failing on configurations
```
analyzer-unittest-asserts-release-win
```

It looks like the test is using a MemoryFileSystem which checks that an input is normalized, and it may be expecting backslashes on Windows.  The error is:

00:23 [32m+149[0m[31m -1[0m: AnalysisDriver_BazelWorkspaceTest | test_nestedLib_notCanonicalUri [1m[31m[E][0m[0m

  Invalid argument(s): Path must be normalized : /workspace/my/outer/lib/inner/lib/c.dart

  package:analyzer/file_system/memory_file_system.dart 200:7  MemoryResourceProvider._ensureAbsoluteAndNormalized
  package:analyzer/file_system/memory_file_system.dart 98:5   MemoryResourceProvider.getFile
  package:analyzer/src/dart/sdk/sdk.dart 133:33               AbstractDartSdk.pathToUri
  package:analyzer/src/generated/source.dart 62:17            DartUriResolver.pathToUri
  package:analyzer/src/context/source.dart 107:26             SourceFactoryImpl.pathToUri
  package:analyzer/src/dart/analysis/file_state.dart 900:32   FileSystemState.hasUri
  package:analyzer/src/dart/analysis/driver.dart 901:19       AnalysisDriver.getResult
  package:analyzer/src/dart/analysis/session.dart 122:20      AnalysisSessionImpl.getResolvedUnit
  pkg\analyzer\test\src\dart\analysis\driver_test.dart 89:42  AnalysisDriver_BazelWorkspaceTest.test_nestedLib_notCanonicalUri
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 199:9            Declarer.test.<fn>.<fn>

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/224801
