### ISSUE TITLE
Eliminate pub dependency on package:devtools_server

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#47974]
In a recent need to eliminate a dependency on `package:intl`, it was brought to light that there is still a dependency on `package:devtools_server` from the SDK (see [comment](https://github.com/dart-lang/intl/pull/436#issuecomment-996266204)), even though this package is no longer shipped on pub. The `package:devtools_server` dependency is due to the current implementation of the `dart devtools` command. 

From @bkonyi: "We can probably rework this so that we spawn devtools the same way DDS does for `dart run`"

We should do this to eliminate the dependency on a package that is no longer going to be shipped on pub (devtools_server).

Related tracking issue to eliminate other dependencies on `package:devtools_server` - https://github.com/dart-lang/webdev/issues/1474

**Comment by bkonyi** [comment]
`devtools_server` functionality has been moved into DDS (3b736b846064295f08727b914b65561487a74540) and the SDK no longer depends on it.
