### ISSUE TITLE
The fix create_constructor_super should be updated when super initializers are implemented

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#47979]
The fix create_constructor_super should be updated when super initializers are implemented. It currently generates normal parameters and includes them in the super invocation, but that could generally be improved by generating super initializer parameters.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/238560

I am not sure if this is clear (regarding `bool? isDefinition`).
