### ISSUE TITLE
No warning in analyzer when null-aware operator is used on type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48004]
The following code produces a warning in CFE and no issues in analyzer
```dart
class C {
  static String s = "Lily was here";
}

main() {
  print(C?.s); // CFE 'Warning: The class 'C' cannot be null.', Analyzer 'No issues found!'
}
```

@eernstg please confirm that CFE is right here and it is an analyzer issue

Tested on `Dart SDK version: 2.16.0-122.0.dev (dev) (Fri Dec 17 22:57:15 2021 -0800) on "windows_x64" `

**Comment by eernstg** [comment]
It should be a warning at this point, but the language team has already decided to support a package of changes that would make it an error.


@srawlins, should we keep this blocked until the details have been sorted out and an implementation issue for said changes has been created?  Or would you prefer to introduce the warning as specified now? (.. just guessing, changing the warning to an error might be so easy that there isn't much wasted effort in doing this in two steps ..)

**Comment by srawlins** [comment]
@eernstg if the bundle of changes is coming soon, waiting seems fine by me.

**Comment by eernstg** [comment]
At this point I think it will take time before there is an updated set of rules, and there's no firm guarantee that we will end up having an error rather than a warning. So I'd suggest that the analyzer gets updated to report the warning. This means that the analyzer and the CFE agree on the behavior, and they both agree with the current specification.

**Comment by bwilkerson** [comment]
Sam is out this week and next, but yes, it seems reasonable to implement it as a warning.

@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/246301
