### ISSUE TITLE
Quick Question about the memory usage of Dart.

### ISSUE THREAD

**Issue by ArishSultan** [dart-lang/sdk#48019]
Hi, Its not an issue but a question about the runtime memory usage of dart.
```
@SomeAnnotation()
class Some Class {}

@SomeAnnotationWithParams(
// A lot of configurations
)
class AgainSomeClass {}
```

The only explanation about const classes i get from internet is that the const constructor is only invoked once through out the application does this goes same with annotations?

Do the application initialize annotation while app execution or they are just compile time stuff?

**Comment by aam** [comment]
For class to be used as an annotation it has to have a const constructor. Annotations are  loaded by vm as the compile-time constant objects evaluated during compile time.
