### ISSUE TITLE
Split method of String class documentation

### ISSUE THREAD

**Issue by elrasool** [dart-lang/sdk#48029]
The documentation of string class needs an amendment in the loop of the split method. I think the writer intended to write "rune" not "run".

![split method](https://user-images.githubusercontent.com/13761393/147688176-2f3778e7-741e-4299-ae12-2a7f82fc943a.jpg)

**Comment by natebosch** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/91e6801ae70cfa4a80f9c2fc4600d7f6ba11db70
