### ISSUE TITLE
Code Completion and fixes don't correctly reflect state of files that have part/part-of removed

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#48027]
This was originally raised at https://github.com/Dart-Code/Dart-Code/issues/3752 by @witchdrash, but it seems like a server issue. Removing `part` and `part of` from files seems to cause classes to no longer show up in code completion, and for quick-fixes with stale entries to appear.

----

Create a multi-part file with several classes each separated out into their own files e.g.

a.dart
```dart
part "./b.dart";
part "./c.dart";

class AClass {}
```

b.dart
```dart
part of "./a.dart";

class BClass {
CClass? cReference;
}
```

c.dart
```dart
part of "./a.dart";

class CClass {
AClass? aReference;
}
```

someother.dart
```dart
import '/a.dart';

class SomeThing {
AClass? aReference;
BClass? bReference;
CClass? cReference;
}
```

Intellisense works just fine for importing into each file, remove the part and part of and intellisense wont see AClass, BClass or CClass anymore even if you restart VSCode, to import them you have to add it manually, renaming the files to a2.dart, b2.dart, c2.dart fixes it and intellisense once again shows them on the import menu, but naming them back to a.dart, b.dart and c.dart causes the problem to re-emerge.

**Comment by DanTup** [comment]
I can repro the issue above (where the classes no longer show up in code completion after removing `part`/`part of`), but also the generated code actions also seem to think the classes are available through the original file:

![Screenshot 2021-12-30 at 12 41 29](https://user-images.githubusercontent.com/1078012/147753090-58a95122-fe81-42bc-9283-76faa03bf7cf.png)

Even after restarting VS Code and `import`ing the files, some of the items are still missing from completion:

![Screenshot 2021-12-30 at 12 47 19](https://user-images.githubusercontent.com/1078012/147753306-74e4f614-fe9f-4082-800b-8278fed7f646.png)

**Comment by scheglov** [comment]
I cannot reproduce this, but it might be because I have e0752585f275ae90f45ea0475e10559ac873e116.

**Comment by DanTup** [comment]
Ah, nice - I also don't seem to be able to reproduce using:

Dart SDK version: 2.16.0-edge.2766add19a274cef9eb0c763fa3627026fd9b923 (be) (Tue Jan 4 16:19:06 2022 +0000) on "macos_x64"

Thanks!
