### ISSUE TITLE
Should passing a function with generic types to `Isolate.entryPoint` and specifing them at `Isolate.spawn` preserve the type information?

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#48035]
I'm currently experimenting with `Isolate`s and the following tripped me up.

When passing an `entryPoint` to an `Isolate` and it has type parameters they are ignored. Even when being explicitly torn-off.

Please consider the bellow example:
```dart
import 'dart:async';
import 'dart:collection';
import 'dart:isolate';

void main() async {
  final port = ReceivePort();
  final msg = InitMsg(msg: 10, fn: fib, responsePort: port.sendPort);

  final entry = _entry<int, int>;
  entry(msg, false);
  final isolate = await Isolate.spawn<InitMsg<int, int>>(
    entry,
    InitMsg(msg: 10, fn: fib, responsePort: port.sendPort),
    onError: port.sendPort,
    onExit: port.sendPort,
  );

  print(await port.first);
  isolate.kill();
}

final _fibCache = HashMap<int, int>.from({0: 0, 1: 1});
int fib(int i) => _fibCache[i] ??= fib(i - 1) + fib(i - 2);

void _entry<Msg, Res>(InitMsg<Msg, Res> init, [bool exit = true]) {
  print(Msg);

  if (exit) Isolate.exit(init.responsePort, init.fn(init.msg));
}

class InitMsg<Message, Response> {
  final Message msg;
  final SendPort responsePort;
  final FutureOr<Response> Function(Message) fn;

  const InitMsg({
    required this.msg,
    required this.fn,
    required this.responsePort,
  });

  FutureOr<Response> process() => fn(msg);
}
```

Expected output:
```
int
int
55
```

Actual output:
```
int
dynamic
[type '(int) => int' is not a subtype of type '(dynamic) => dynamic', ...
```

Of course to mitigate that I can instead change the line:
```dart
if (exit) Isolate.exit(init.responsePort, init.fn(init.msg));
```
to
```dart
if (exit) Isolate.exit(init.responsePort, init.process());
```
and the types are preserved in the object itself, as well as, we get the bellow output.
```
int
dynamic
55
```

I'm not sure if this is by design or not. 

Just wanted to ask if there are any plans to support passing generic types to the `entryPoint`?

`dart --version`
`Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"`

**Comment by a-siva** [comment]
//cc @aam

**Comment by lrhn** [comment]
It seems the VM loses generic instantiation of tear-offs when used as *entry point* for `Isolate.spawn`.
Example:
```dart
import"dart:isolate";

void func<T>(T o) {
 print("$o:$T");
}

void call2(dynamic f) {
  f(2);
}
void call4(dynamic f) {
  f(4);
}

void main() async {
  await Isolate.spawn(func<int>, 1);     // prints 1:dynamic
  await Isolate.spawn(call2, func<int>); // prints 2:int
  void Function(int) to = func; 
  await Isolate.spawn(to, 3);            // prints 3:dynamic
  await Isolate.spawn(call4, to);        // prints 4:int
}
```

There is no good reason for that, other than historically not being able to pass function values, and therefore treating the spawn entry point *differently* from any other serialized value.
Now that it's possible to send arbitrary closures, we probably should send the entry point directly, the same way the argument object is sent.
