### ISSUE TITLE
Analyzer doesn't give unnecessary_import feedback if element used only from 1 export

### ISSUE THREAD

**Issue by SuperPenguin** [dart-lang/sdk#48038]
I'm doing a barrel export and notice when using only elements from 1 export files it doesn't give `unnecessary_import` at all.

For example if I have
`a.dart`
```dart
class A {}

class A2 {}
```
`b.dart`
```dart
class B {}
```
`c.dart`
```dart
class C {}
```
`alphabet.dart`
```dart
export 'a.dart';
export 'b.dart';
export 'c.dart';
```

and used it like so, the analyzer give feedback `unnecessary_import` for all a, b, c dart files
```dart
import 'package:hmmm/src/alphabet/a.dart'; // unnecessary_import
import 'package:hmmm/src/alphabet/b.dart'; // unnecessary_import
import 'package:hmmm/src/alphabet/c.dart'; // unnecessary_import
import 'package:hmmm/src/alphabet/alphabet.dart';

void something() {
  final a = A();
  final a2 = A2();
  final b = B();
  final c = C();
}
```

but if only element used from `a.dart`, it doesn't give `unnecessary_import` to a, only `unused_import` for b and c.

```dart
import 'package:hmmm/src/alphabet/a.dart';
import 'package:hmmm/src/alphabet/b.dart'; // unused_import
import 'package:hmmm/src/alphabet/c.dart'; // unused_import
import 'package:hmmm/src/alphabet/alphabet.dart';

void something() {
  final a = A();
  final a2 = A2();
  // final b = B();
  // final c = C();
}
```

dart --version
Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "windows_x64"

IDE
 vscode

**Comment by scheglov** [comment]
@srawlins

**Comment by srawlins** [comment]
In the second case you describe, `alphabet.dart` and `a.dart` provide the _same_ set of "used" elements (A and A2). We consider these "redundant" imports, rather than "unnecessary."

We have not yet landed the check for redundant imports. The check is more complicated, because when two import directives provide the same set of used elements, we want to be careful about recommending which import directive to remove.

**Comment by srawlins** [comment]
Follow support for redundant imports here: https://github.com/dart-lang/sdk/issues/44569.
