### ISSUE TITLE
 Warning: Tried to initialize from a previous compilation

### ISSUE THREAD

**Issue by christinachimi** [dart-lang/sdk#48031]
Got this error when running flutter test.

 
> Warning: Tried to initialize from a previous compilation (file:///Users/path/to/project/build/test_cache/build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill), but
> the file was not self-contained. This might be a bug.
> 
> The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
> If you are comfortable with it, it would improve the chances of fixing any bug if you included the file
> /var/folders/tp/g3yw6ptx5v3fk7cv_bnw5z640000gp/T/initialize_from.dilleKT8a7/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
> Either way, you should probably delete the file so it doesn't use unnecessary disk space.

I have not noticed this error before, and it did not seem to effect the test run.

**Comment by a-siva** [comment]
@christinachimi as indicated in the error message, are you in a position to share the file `/var/folders/tp/g3yw6ptx5v3fk7cv_bnw5z640000gp/T/initialize_from.dilleKT8a7/initialize_from.dill.gz ` in this issue?

**Comment by christinachimi** [comment]
@a-siva not here in the issue, no. The problem hasn't recurred, so feel free to close if it's not useful.

**Comment by a-siva** [comment]
@christinachimi Ok, will close it now as non actionable, if you run into the issue again please reopen or file a new issue.
