### ISSUE TITLE
Missing tests for invalid_constructor_name diagnostic

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48045]
There are no tests in the analyzer code base for the `CompileTimeErrorCode.INVALID_CONSTRUCTOR_NAME` diagnostic code.

There might be tests for it in the language or co19 tests, but it would still be good to have tests for it in the analyzer code base (or to remove it if it can't actually be generated).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/226160
