### ISSUE TITLE
Inconsistent behavior with omitted late initialization checks

### ISSUE THREAD

**Issue by alexeyinkin** [dart-lang/sdk#48043]
I have noticed that if I do not initialize late variables, `LateInitializationError` is only thrown in debug, but in release these checks are skipped. Combined with other optimizations of the compiler, this leads to unexpected order of execution and output.

I tested the following examples with Dart 2.15.1 in Linux (pure Dart) and Android (ran as Flutter project with `main.dart` replaced with the example code).

For pure Dart, I compiled and ran the code as:
```bash
dart compile exe lib/main.dart
lib/main.exe
```

For Android with Flutter, I compiled and ran the code as:
```bash
flutter run --release
```

## Read an uninitialized field ##
```dart
class LateField {
  late int n;

  LateField() {
    print(n);
  }
}

void main() {
  LateField();
}
```

I did not find the behavior for this documented. I expect either initialization error or a random integer output.
Instead I get:

```
Unhandled exception:
Attempt to execute code removed by Dart AOT compiler (TFA)
```

## Read and write a constant to an uninitialized field ##
```dart
class LateField {
  late int n;

  LateField() {
    print(n);
    n = 31999;
  }
}

void main() {
  LateField();
}
```

I expect the same result as in the above test. Instead I get:
```
31999
```

... which should never happen as in the source code the value is not written at the time of `print`.

## Read and write a variable to an uninitialized field ##
```dart
class LateField {
  late int n;

  LateField() {
    print(n);
    n = DateTime.now().millisecondsSinceEpoch;
  }
}

void main() {
  final obj = LateField();
  print(obj.n);
}
```

I expect the same result as in one of the above tests. Instead I get:
```
139798064955457
1641197443737
```

The last line is the expected timestamp, but the first line appears to be the garbage that was in the memory before the variable initialization, it varies from run to run. On Android, I witnessed it being `-3875206600128134888` for instance.

## Writing at a garbage address ##

Extending the above test, we can write to a field at an uninitialized object pointer:

```dart
class LateScalar {
  late int n;
}

class LateObject {
  late LateScalar obj;

  LateObject() {
    obj.n = 31999;
    print(obj.n);
    obj = LateScalar();
    print(obj.n);
  }
}

void main() {
  LateObject();
}
```

The expected result is some segmentation falut, and it does indeed happen in Linux:

```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=2, si_addr=0x7fc7e48883e8
Aborted (core dumped)
```

On Android, the app dies with an operating system popup saying `test has stopped.`, `test` being the Flutter project name. During this, `flutter run --release` still runs in the terminal with no messages, until is killed with Ctrl-C.

## What feels wrong with this ##

1. At the very least the docs should say that late checks are skipped with the default `dart compile exe` without other options, and in that case the behavior is undefined. These pages may be the right places to do so:
https://dart.dev/guides/language/effective-dart/usage
https://dart.dev/tools/dart-compile

2. The docs should say how to keep the checks in release builds. I see talks about different optimization levels like `-O0` ... `-O3`, but they are not mentioned in https://dart.dev/tools/dart-compile, and `dart compile` does not have `-On` option.

3. It is unclear how these test results relate to #46806. It appears as if this has already landed and enabled by default, but the issue is open and scheduled for Dart 2.16 beta 1.

Dart version (installed with Flutter):
Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "linux_x64"

**Comment by mraleph** [comment]
This is definitely a bug.
