### ISSUE TITLE
The package_import_contains_dot_dot hint is not being generated.

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48042]
The `package_import_contains_dot_dot` hint is not being generated. We should either implement it or remove it.

If we want to implement it then the existing tests will need to be updated. The URI resolver appears to say that a URI doesn't exist if the path escapes the `lib` directory, and there's no reason to generate two diagnostics for the URI, but the URI resolver will accept the following example as being valid, so it would make a reasonable test case:
```dart
import 'package:meta/foo/../meta.dart';
```

**Comment by srawlins** [comment]
It's been removed.
