### ISSUE TITLE
proper exception/warning for null aware operator used on null value

### ISSUE THREAD

**Issue by Ritsz123** [dart-lang/sdk#48050]
## Use case
During the development I mistakenly used `!` (null check operator) on the null instance. 
In the console, I realized there was no special warning or exception thrown but just a log stating `Null check operator used on a null value`  Thankfully I was aware of the file in which I did the mistake but it will be very hard to find the error if more than one developer is working on the particular project.

## Proposal
Suggestion:
I think instead of just mentioning `Null check operator used on a null value` in the console if a proper warning or exception is thrown mentioning the location of error it will be very easy to track the file & line of error.

**Comment by a-siva** [comment]
@Ritsz123 which tool were you using when you ran into this error (dart analyzer, dart2js or command line dart) ?

**Comment by Ritsz123** [comment]
@a-siva I had this issue in flutter project when the app was running on Android device, not aware which tool it uses..

**Comment by vsmenon** [comment]
How are you running flutter?  From the command line?  Via an IDE?  In release mode or debug mode?

The stack trace for the exception should show the line number.

**Comment by Ritsz123** [comment]
@vsmenon I'm running the flutter application via IDE (Android studio) in release mode 
There is no exception thrown nor any stack trace in the logs.

**Comment by vsmenon** [comment]
Are you sure this isn't getting caught and handled?  E.g., by the framework?

If you run your app in debug mode and pause on any exception, do you see anything?

**Comment by vsmenon** [comment]
Closing this as cannot replicate.

To the best of my knowledge, Flutter prints the full stack trace for uncaught errors.  The stack trace shows the location of the error.  My best guess is there is application code that catches errors and only prints the message.  If it appears that the flutter framework itself is doing this (it doesn't seem to), please open a bug there.
