### ISSUE TITLE
[analyzer] A name clash involving a constructor and a type variable isn't detected

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#48053]
Consider the following program:

```dart
class C<X> {
  C.X();
}
```

This program [should](https://github.com/dart-lang/language/blob/9daaad1d2103dcb7ad91f3ebf27a878c13fca985/specification/dartLangSpec.tex#L2540) give rise to an error, because the name of the constructor has a second identifier which is also the name of a type variable. The CFE reports this error as expected, but the analyzer accepts the program without any diagnostic messages.

The change can presumably be considered non-breaking, because we assume that no Dart software will be in use without ever being handled by the CFE.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/226284

**Comment by eernstg** [comment]
Thx!
