### ISSUE TITLE
 CFE implementation for super-initializer parameters

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48058]
See https://github.com/dart-lang/sdk/issues/48055 for the main tracking issue.

cc @johnniwinther @chloestefantsova

**Comment by chloestefantsova** [comment]
I were using the following issue to track the CFE implementation: https://github.com/dart-lang/sdk/issues/47525

**Comment by devoncarew** [comment]
Gotcha; closing in favor of https://github.com/dart-lang/sdk/issues/47525.
