### ISSUE TITLE
compareToIgnoreCase on String

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#4805]
String should have a compareToIgnoreCase to avoid expensive case-insensitive comparisons like a.toLowerCase().compareTo(b.toLowerCase()).

**Comment by lrhn** [comment]
There is a `compareAsciiUpperCase` and a `compareAsciiLowerCase` function in `package:collection` that is (ASCII) case-insensitive.

A full Unicode case-insensitive compare is not possible (only a case-insensitive equality check, ordering in the presence of complex normalization isn't practically reasonable).
