### ISSUE TITLE
 DDC implementation for super-initializer parameters

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48061]
See https://github.com/dart-lang/sdk/issues/48055 for the main tracking issue.

cc @sigmundch

**Comment by sigmundch** [comment]
This is likely going to be entirely handled by the CFE lowering, but we'll keep this open until we validate that such is the case.

**Comment by nshahan** [comment]
All test failures on DDC configurations have been fixed. I think it is safe to close this issue but we can reopen if something appears.
