### ISSUE TITLE
build systems implementation for super-initializer parameters

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48064]
See https://github.com/dart-lang/sdk/issues/48055 for the main tracking issue.

**Comment by devoncarew** [comment]
cc @jakemac53

**Comment by jakemac53** [comment]
Do we expect any work here or do you just want me to make sure things work?

Also which build systems are we covering here, just build_runner and bazel?

**Comment by devoncarew** [comment]
No work anticipated here per se - this is just a standing checklist item for new language features; some may have work required and some not. We'll just need the build system work scoped out for this feature (which may well be saying that none is expected). 

> Also which build systems are we covering here, just build_runner and bazel?

Yup just those two.

**Comment by jakemac53** [comment]
Sounds good, I don't expect any work but I can validate once the features are implemented? Not sure how I could validate beforehand.

**Comment by jakemac53** [comment]
There will be at least one small action item for bazel which is to bump the language version for null safe opted in packages to the latest. But that is trivial.

**Comment by jakemac53** [comment]
I am not sure what the status is regarding internal, there shouldn't be any work beyond bumping the default language version for null safety packages. I don't usually manage that and I am not sure exactly who does tbh, somebody on the dart-in-google3 team probably?

For build_runner we just need to check that it works, there is no expected work there.
