### ISSUE TITLE
 syntax highlighters implementation for super-initializer parameters

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48060]
See https://github.com/dart-lang/sdk/issues/48055 for the main tracking issue.

- [x] https://github.com/dart-lang/dart-syntax-highlight/ (@DanTup)
- [x] https://github.com/highlightjs/highlight.js (@srawlins)
- [x] https://github.com/codemirror/CodeMirror/ (@domesticmouse)

**Comment by devoncarew** [comment]
@DanTup for dart-syntax-highlighting; @srawlins for highlight.js; @domesticmouse for codemirror. I'll add ldaps to the checklist above. Often, there isn't any work for this syntax highlighters for new language features, but we need to check (and do any work that may be required).

**Comment by srawlins** [comment]
highlight.js seems to work out-of-the-box. `super` is highlighted exactly as `this`, as a keyword.

**Comment by domesticmouse** [comment]
Putting the below sample into DartPad shows CodeMirror treating `super.parameter` equivalent to `this.parameter`:

```dart
class B {
  final int foo;
  final int bar;
  final int baz;
  B(this.foo, this.bar, [this.baz = 4]);
}
class C extends B {
  C(super.foo, super.bar, [super.baz = 4]);
}
```

**Comment by DanTup** [comment]
The same is true for VS Code, `super` is treated just like `this`.

Textmate Grammar (from [dart-syntax-highlight/](https://github.com/dart-lang/dart-syntax-highlight/)):

<img width="704" alt="Screenshot 2022-05-09 at 09 58 17" src="https://user-images.githubusercontent.com/1078012/167376394-cc07a319-d3a9-48b3-9500-468c6e29b510.png">


Semantic Tokens (from the LSP server):

<img width="696" alt="Screenshot 2022-05-09 at 09 58 58" src="https://user-images.githubusercontent.com/1078012/167376401-b318f1de-09e4-43fb-a2df-e9a5a2dbb2e0.png">
