### ISSUE TITLE
IntelliJ implementation for super-initializer parameters

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48074]
See https://github.com/dart-lang/sdk/issues/48055 for the main tracking issue.

**Comment by devoncarew** [comment]
cc @jwren

**Comment by stereotype441** [comment]
Note: in our planning meeting on Dec 13, it was suggested that when the user hovers over an optional super parameter that inherits a default value from the corresponding parameter on the base class, the IDE should show the default value that's being inherited from the base class constructor.  Doing so requires work in the analysis server, and possibly in some of the IDE integration logic.
