### ISSUE TITLE
Angular compiler implementation for super-initializer parameters

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48073]
See https://github.com/dart-lang/sdk/issues/48055 for the main tracking issue.

**Comment by devoncarew** [comment]
cc @leonsenft

**Comment by maopanglin** [comment]
There are two ways that AngularDart might need to consider but I am not worried about this change.

1. The generated code part. The Angular compiler doesn't generate code like this pattern.
2. Clients' Angular Dart code source. The Angular compiler can rely on Dart analyzer to extract the right nodes.

**Comment by leonsenft** [comment]
Regarding (2), I think there are some unanswered questions around dependency injection annotations on super-initializer parameters. See my thoughts in b/213383778.

**Comment by leafpetersen** [comment]
FYI, the flag has been flipped so these can be used without a flag internally now.

**Comment by jodinathan** [comment]
this will be so useful for Angular DI...  
any public Angular repo that we can try this out?

**Comment by leafpetersen** [comment]
This is still in progress.

**Comment by mattrberry** [comment]
The internal bug has just been wrapped up. All set to close this issue now.

**Comment by leafpetersen** [comment]
Thanks!

**Comment by jodinathan** [comment]
we know that if Google was to publish their internal AngularDart it would mean lots of breaking changes, however, we are very ok with that.  
Before we dig the compiler and other internal stuff and have many hours of rework, maybe we would come with a plan to start publishing AngularDart again?
