### ISSUE TITLE
Kythe implementation for super-initializer parameters

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48071]
See https://github.com/dart-lang/sdk/issues/48055 for the main tracking issue.

**Comment by devoncarew** [comment]
cc @emmanuel-p

**Comment by leafpetersen** [comment]
FYI, the flag has been flipped so these can be used without a flag internally now.

**Comment by leafpetersen** [comment]
I don't know is it?  @emmanuel-p

**Comment by emmanuel-p** [comment]
Basic support is implemented.
Some improvements are planned.
Tracked internally by b/225119276.

**Comment by leafpetersen** [comment]
Any updates on this?
