### ISSUE TITLE
Cannot contain large binary blob inside code

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#48081]
I need to encode some binary blob (say, 100KB) in Dart code. Do not want to put it in a separate file, but hope can put it in `.dart` code (because, for example, I want the excellent flutter hot restart instead of rebuilding the Flutter app again and again if the file chages).

What is the most brief way to do so?

For example I can come up with `final bytes = [100, 70, 220, 132, ...];` but it will make the `.dart` file huge.

I can also do `final data = 'aGVsbG8...'` and use it by `base64.decode(data)`, but it takes up 33% extra space in generated binary.

Thanks for any suggestions!

**Comment by vsmenon** [comment]
Hi!  This issue tracker is for bugs and feature requests.  This question / discussion would be much better suited for one of these venues:

https://dart.dev/community#join-the-conversation

thanks!
