### ISSUE TITLE
`String` and `bool` are missing in `Dart type system` charts.

### ISSUE THREAD

**Issue by horam-fs** [dart-lang/sdk#48080]
Is there any specific reason that `bool` and `String` are missing in the related charts to `Dart Type system`?
(e.g. [this](https://dart.dev/null-safety/understanding-null-safety) one)

**Comment by mraleph** [comment]
Charts their are provided as illustrations of some particular properties and not as an exhaustive charts of all types available in Dart, e.g. the first two charts show how Null is a subtype of all types prior to NNBD, and not related to non-nullable types after NNBD, etc Hence adding `bool` and `String` would not really add anything to the message that the chart is trying to convey.
