### ISSUE TITLE
language tests for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48088]

**Comment by devoncarew** [comment]
I'm uncertain whether we already have these tests or not (or, whether they're complete).

cc @lrhn @eernstg

**Comment by eernstg** [comment]
Cf. https://dart-review.googlesource.com/c/sdk/+/221081.

**Comment by lrhn** [comment]
I'll land that file today, then start considering "error" tests.

**Comment by lrhn** [comment]
Error tests have landed too, so I believe we are complete for this issue.
