### ISSUE TITLE
Mistaken nullability warning when compiling executable

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#48090]
May be related to https://github.com/dart-lang/sdk/issues/46264

I have a package, `actors`, which is now emitting this warning when a binary depending on it is compiled:

```
▶ dart compile exe bin/dartle.dart
Info: Compiling with sound null safety
../../../.pub-cache/hosted/pub.dartlang.org/actors-0.8.1/lib/src/isolate/isolate_actor.dart:35:39: Warning: Operand of null-aware operation '??' has type 'String' which excludes null.
  final isolateName = Isolate.current.debugName ?? '';
                                      ^
Generated: /Users/renato/programming/projects/dartle/bin/dartle.exe
```

This is very weird because I am using Dart 2.15.1 and the `actors` package uses the environment config `sdk: '>=2.15.0 <3.0.0'` (same as the package I am currently compiling), which I updated to try to get rid of this warning (I thought the nullability of this property might have changed between Dart 2.14 and 2.15 - but that's not the case).

[`Isolate.current.debugName`](https://api.dart.dev/stable/2.15.1/dart-isolate/Isolate/debugName.html) is certainly nullable, and it appears to have been nullable at least since Dart `2.9.0`: https://api.dart.dev/stable/2.9.0/dart-isolate/Isolate/debugName.html (it wasn't nullable up until [2.8.0](https://api.dart.dev/stable/2.8.0/dart-isolate/Isolate/debugName.html)).

What could be the issue?

**Comment by renatoathaydes** [comment]
Maybe this helps: my tests for another project started failing just recently because of this.. the test monitors `stderr` and the output has changed:

https://github.com/renatoathaydes/dartle/runs/4731870282?check_suite_focus=true

```
Expected: []
	  Actual: [
	            '../../../../../../.pub-cache/hosted/pub.dartlang.org/actors-0.8.0/lib/src/isolate/isolate_actor.dart:35:39: Warning: Operand of null-aware operation \'??\' has type \'String\' which excludes null.',
	            '  final isolateName = Isolate.current.debugName ?? \'\';',
	            '                                      ^'
	          ]
```

So, this is looking like a regression in Dart 2.15.

**Comment by johnniwinther** [comment]
This is caused by a discrepancy between the declaration of `Isolate.debugName` which has type `String?` and the patch implementation which has type `String`. The front-end uses the implementation types.

I'll update the patch implementation to match the declaration.

**Comment by renatoathaydes** [comment]
Thanks @johnniwinther . This is breaking my build, so can you tell me when/which is the next release that will include this coming up?

**Comment by johnniwinther** [comment]
It might take while before it is available in stable release. Until then you can use one of these work-arounds:

Indirection through local with type `dynamic`:
```Dart
String _generateName() {
   final dynamic isolateNameWorkaround = Isolate.current.debugName;
   final String isolateName = isolateNameWorkaround ?? '';
```
Access through a helper:
```Dart
String? get _isolateNameWorkaround => Isolate.current.debugName;
String _generateName() {
  final isolateName = _isolateNameWorkaround ?? '';
```
