### ISSUE TITLE
Add a new keyLog property to HttpClient

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#48093]
# Change

I propose that we add a new `keyLog` property to `HttpClient` with a signature like:
```
void keyLog=(
  void f(String line)?
)
```

This would allow users to [log TLS keys for use with Wireshark and other analysis tools](https://github.com/dart-lang/sdk/issues/47838).

The approach was discussed in this [code review](https://dart-review.googlesource.com/c/sdk/+/222060/2/sdk/lib/io/security_context.dart#40)

The non-breaking alternative would be to make `keyLog` an argument to the `HttpClient` constructor but that is not symmetrical with the `HttpClient` API (i.e. onBadCertificateCallback).

See related discussing on [Add a new connectionFactory property to HttpClient](https://github.com/dart-lang/sdk/issues/47887).

#  Rationale

The `HttpClient` API already has multiple attributes that accept functions e.g.

```
void findProxy=(
  String f(Uri url)?)

void badCertificateCallback=(
  bool callback(
    X509Certificate cert,
    String host,
    int port
  )?
)
```

and implementing this as a constructor argument would be inconsistent with the rest of the API. Also, parameterizing all future functionality as constructor arguments does not seem scalable.

# Impact

All classes that `implements HttpClient` (without `extends Mock` or equivalent [`noSuchMethod`](https://api.flutter.dev/flutter/dart-core/Object/noSuchMethod.html) implementation) will need to be updated.

I suspect that there are not many implementations of HttpClient outside of mocks.

# Mitigation

Users must implement the `keyLog` property.

**Comment by zanderso** [comment]
Please note https://github.com/flutter/flutter/blob/76cf452fe3d18e3765139190c13c2d52e0264310/packages/flutter_tools/test/src/fake_http_client.dart#L123

**Comment by devoncarew** [comment]
@vsm, @Hixie, and @grouma - can you review and sign off for Dart, Flutter, and AngularDart respectively? Thanks!

**Comment by grouma** [comment]
I couldn't find any usages of `implements HttpClient` in the Angular code base so this should have no impact.

**Comment by grouma** [comment]
Note that this may impact internal customer code. I did a quick spot check and it will impact the Assistant team but overall there aren't many usages of `implements HttpClient`.

**Comment by Hixie** [comment]
I don't object.

We should make sure we document that this is a very security-sensitive API though, and that applications should only use it during debugging.

**Comment by vsmenon** [comment]
Do we have summary on level of impact on internal and external code of this breaking change?

**Comment by brianquinlan** [comment]
@vsmenon For Google code, there are a few places that `implement HttpClient` without `noSuchMethod` or equivalent.

I checked some likely-to-be-affected external packages e.g. `package:http`, `package:http2` but didn't find any that would be broken.

**Comment by vsmenon** [comment]
Thanks!  For this (and https://github.com/dart-lang/sdk/issues/47887), what would downstream users need to do a minimum?  E.g., implement an empty `keyLog` method?

**Comment by brianquinlan** [comment]
@vsmenon Yes, my plan was for the changelog to include instructions to add this to your implementation:

```
  set keyLog(String f(String line)) => throw UnsupportedError();
```

**Comment by vsmenon** [comment]
Thanks - lgtm

**Comment by devoncarew** [comment]
@brianquinlan - you're good to go with this change (see the 'Execution' steps here: https://github.com/dart-lang/sdk/blob/main/docs/process/breaking-changes.md#step-3-execution). Thanks for your patience!

**Comment by brianquinlan** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/917ae52f70a8bf75616011ef26ffa59737e1ec3a
