### ISSUE TITLE
Future(computation) constructor slow in javascript (by 1000 times slower than Future.value())

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#48104]
Running this program in dartpad:
```dart
import "dart:async";

main() async {
  var sw = Stopwatch()..start();
  int N = 10;
  int result = await (int n) async {
    for (int i = 0; i < n; i++) {
      await Future.value(1);
    }
    return n;
  }(N);
  print(result);
  print("t=${sw.elapsedMicroseconds}");
 
  sw.reset();
  result = await (int n) async {
    for (int i = 0; i < n; i++) {
      await Future(() => 1);
    }
    return n;
  }(N);
  print(result);
  print("t=${sw.elapsedMicroseconds}");
  return result;
}
```
Results:
10
t=5201
10
t=5814799

The culprit is Timer.run() method used inside Future constructor. 
The same program, when run on VM, produces the following output (with N=100000)
100000
t=64293
100000
t=496046
Exited

Still slower, but only by 7-8 times, not 1000 times. (I expected it to be slower by 2 times max)

(I also compared the Future.value() version in dartpad vs Future.value() in VM. In javascript, it's slower by 2.5 times, which is reasonable).

This affects all methods that use `Timer.run()` under the hood: `Future.delayed`, `Future.microtask`, `scheduleMicrotask` and probably more.
Flutter also uses `Timer.run` directly [in some places](https://github.com/flutter/flutter/blob/ab0a33597328772fe27dbc0b217ac930373ef5f0/packages/flutter/lib/src/scheduler/binding.dart). Maybe this issue should be open against `Timer.run` instead - not sure.

EDIT: when I run the same test in MS Edge, the timing, in absolute terms, is much better, but the ratio is still around 500.
When you try to reproduce, set N to a higher value (say, 1000 or 10000).

**Comment by tatumizer** [comment]
@lrhn: what is the rationale for having a `Future(computation)` constructor in the first place?
We could always write `Future.value(computation())` instead, with no `Timer.run` overhead. Right? Wrong?

**Comment by lrhn** [comment]
@tatumizer Wrong.
The `Future(computation)` is equivalent to `Future.delayed(Timer.zero, computation)`, so it delays the entire computation (by a little).
If you wanted to compute now, and still capture errors into the future, you can use `Future.sync(computation)`.

We basically have all three options:
* Right now: `Future.sync(computation)`
* Later microtask: `Future.microtask(computation)`
* Later event: `Future(computation)`

We really had no good input on one should be the default when we designed the `Future` class, and thought that "a later event" would be what people wanted for their asynchronous computation. In practice, people created woefully few futures with any of those constructors, it was almost always either `Completer` or just `.then` on an existing future. The `Future.delayed` constructor is probably the most used one, even if it's primarily used in tests.

If designed today, I probably would have skipped the `Future` constructor entirely, and maybe made `Future.sync` be just `Future`.
Isn't hindsight great :grin:

**Comment by tatumizer** [comment]
But... isn't `Future.sync(computation)` the same as `Future.value(computation())`? (note the **()**).

So many options... The documentation doesn't say under what circumstances you have to prefer `Future.microtask` vs `Future.sync` vs `Future()`. There're no real-world examples of usage. I found out about `Future(computation)` from the parallel thread and [rejoiced](https://github.com/dart-lang/language/issues/2033#issuecomment-1003743870), driven by the illusion that said constructor provides the most efficient way to implement the trick. (Spoiler: I was wrong :-)). `Timer.run` says it will execute as soon as possible, so I figured `Future(computation)` will also execute as soon as possible, and because I couldn't think of any way to execute anything sooner than "as soon as possible", there was no motivation for me to look for alternatives. But when I tried to experimentally verify the conclusion, the results turned to be underwhelming.

> In practice, people created woefully few futures with any of those constructors

You can't blame them :-)
I can only speculate that they really tried, but ran into the same problems, and decided to not take anything for granted about these constructors. 😄

**Comment by tatumizer** [comment]
Closing for the lack of interest.
