### ISSUE TITLE
The difficulty of converting the input into another data type.

### ISSUE THREAD

**Issue by DeveloperDotSystem** [dart-lang/sdk#48111]
I'm having a hard time trying to make a program to calculate the area of ​​a rectangle with Dart and I use a function with parameters to calculate it where I always use the `int` data type to do the calculation, where I use the `dart:io` library and when I use `stdin.readLineSync()` I don't know which is the correct way to convert `"10"` to `10`.

I think Dart just makes it harder to convert input data types.

**Comment by JacobBangSSE** [comment]
Please don't use the issue tracker for general questions about how to do stuff in Dart. Use instead one of the other ways of interacting with the community: https://dart.dev/community

For your question, please take a look at this question on Stackoverflow: https://stackoverflow.com/questions/66695339/the-argument-type-string-cant-be-assigned-to-the-parameter-type-string-w/

Or more directly, take a look at https://api.dart.dev/stable/2.15.1/dart-core/int/parse.html

**Comment by julemand101** [comment]
Please don't use the issue tracker for general questions about how to do stuff in Dart. Use instead one of the other ways of interacting with the community: https://dart.dev/community

For your question, please take a look at this question on Stackoverflow: https://stackoverflow.com/questions/66695339/the-argument-type-string-cant-be-assigned-to-the-parameter-type-string-w/

Or more directly, take a look at https://api.dart.dev/stable/2.15.1/dart-core/int/parse.html
