### ISSUE TITLE
Why does file.writeAsBytes only receive a portion of a file?

### ISSUE THREAD

**Issue by abcxcba** [dart-lang/sdk#48121]
server side,s.dart :
``` lang-dart
import 'dart:io';

void main(List<String> args) async {
  final serverSocket = await ServerSocket.bind('127.0.0.1', 6666);
  print('server');
  serverSocket.listen((socket) {
    final file = File('/tmp/bb/111.deb');
    socket.listen((da) async {
      await file.writeAsBytes(da, mode: FileMode.append, flush: true); //Only a portion of the file is received without any errors.
      // file.writeAsBytesSync(da, mode: FileMode.append);   // ok
    }, onDone: () async {
      await socket.flush();
      await socket.close();
      socket.destroy();
      await serverSocket.close();
    }, onError: (err) {
      print(err.toString());
    });
  });
}

```

client,c.dart :
``` lang-dart
import 'dart:io';

void main(List<String> args) async {
  final file = File('/tmp/dart_2.15.1-1_amd64.deb');
  final socket = await Socket.connect('127.0.0.1', 6666);
  print('send file to server:');
  await socket.addStream(file.openRead());
  //await Future.delayed(Duration(seconds: 10));
  await socket.flush();
  await socket.close();
  socket.destroy();
  print('exit');
}

```

dart run s.dart 

dart run c.dart 

dart_2.15.1-1_amd64.deb 126MB 

111.deb 21MB

Can anyone tell me why? Thank you!

**Comment by mraleph** [comment]
When you write ` socket.listen((da) async { /* callback */ })` that does not mean that the stream subscription will be paused while callback is processing the chunk it received. Instead as soon as synchronous portion of the callback is completed it might be called again. Which means you end up trying to concurrently write multiple chunks into the same file. You need to pause subscription if you would like to avoid that or use `File.openWrite` and write bytes through `IOSink` interface. 

Also please don't use this issue tracker to ask questions, it exists to report issues. There are other channels for asking questions, see https://dart.dev/community

**Comment by abcxcba** [comment]
> When you write ` socket.listen((da) async { /* callback */ })` that does not mean that the stream subscription will be paused while callback is processing the chunk it received. Instead as soon as synchronous portion of the callback is completed it might be called again. Which means you end up trying to concurrently write multiple chunks into the same file. You need to pause subscription if you would like to avoid that or use `File.openWrite` and write bytes through `IOSink` interface.
> 
> Also please don't use this issue tracker to ask questions, it exists to report issues. There are other channels for asking questions, see https://dart.dev/community

I'm sorry for asking here.
Previously I thought the callback function was called serially, processing the received chunks one after the other.
If it is a serial call to "await File.openWrite" the next call is made only after the return.
I observed that "await File.openWrite" returns the result "early", which seems to be a bug, but I'm not sure if it's a bug, so I'm asking here.

Today I tested the calling order of the callback function and found that it is not called serially, but whenever a new chunk is received, the callback function is called.
Thanks for your reply, thanks!
