### ISSUE TITLE
vm/dart_2/isolates/reload_many_isolates_live_and_die_test timed out on dartk-linux-release-simarm

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#48128]
[log](https://dart-ci.appspot.com/log/vm-kernel-linux-release-simarm/dartk-linux-release-simarm/13801/vm/dart_2/isolates/reload_many_isolates_live_and_die_test)

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-linux-release-simarm/13801/overview

**Comment by alexmarkov** [comment]
The test flips between passing and timeout, periodically making bot red. Previous approvals don't seem to work after test passed, and subsequent timeout makes bot red again.

**Comment by whesse** [comment]
Manually marked it flaky. If the flakiness expires (it is consistent for 100 runs), then it may need to be manually marked flaky again.
