### ISSUE TITLE
dart compile jit-snapshot giving incorrect script path

### ISSUE THREAD

**Issue by jaddison06** [dart-lang/sdk#48122]
The `dart compile jit-snapshot` command executes a training run of the code. During this training run, `Platform.script` returns the path of the Dart source file that's being compiled. However, at runtime, `Platform.script` correctly returns the path of the compiled JIT snapshot. This inconsistency seems like incorrect behaviour.

Dart 2.15.1 on Windows 10

**Comment by mraleph** [comment]
This is working as intended. `Platform.script` returns path to the file that was used to start the current isolate.
