### ISSUE TITLE
Analyzer and IDE tooltip disagree on the inferred type of an object

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#48147]
There seems to be a situation where the tooltip in VS Code and the analyzer disagree on the type of an object.
The analyzer correctly infers the type but the tooltip still displays `dynamic`, even after type promotion in the if check.
![Screenshot 2022-01-14 at 11 49 45](https://user-images.githubusercontent.com/23480364/149503683-481ca59a-f672-4112-9423-aa78065129b4.png)

Casting it to the right type, makes the analyzer complain about an unnecessary cast.

Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"
VSCode: Version: 1.63.2
Dart plugin version: v3.32.0

**Comment by scheglov** [comment]
It looks that maybe VS Code displays the declared type of `error` instead of its promoted type.

It the following code, IntelliJ displays `String` in `print`.
```dart
void f(aaa) {
  if (aaa is String) {
    print(aaa);
  }
}
```
![image](https://user-images.githubusercontent.com/384794/150028040-4508e5b6-ab07-49c7-86ab-984ca98feb13.png)

I don't use VS Code myself, and not sure where is code that produces these hints, but maybe @DanTup can help with this.

**Comment by DanTup** [comment]
Yeah, this is related to #34196. In the analyzer info we get both `staticType` and `elementDescription`:

```js
{
	"offset": 6559,
	"length": 6,
	"elementDescription": "Animal a",
	"elementKind": "local variable",
	"isDeprecated": false,
	"staticType": "Horse"
}
```

However we don't get the declared type (`Animal`) on its own, so it's not so obvious when we should/shouldn't show the static type (to avoid showing redundant info). I see IntelliJ is just always showing both types though, so I think for now we should just do the same. Showing the same type twice sometimes doesn't seem like justification for not showing this.

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/228840/
