### ISSUE TITLE
CFE: support interfaces and mixins for enum classes

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#48140]
This is a part of https://github.com/dart-lang/sdk/issues/47453.

Tests `co19/LanguageFeatures/Enhanced-Enum/semantics_A01_t01` and `co19/LanguageFeatures/Enhanced-Enum/semantics_A01_t02` fail with RuntimeError on the VM because interfaces and mixins are currently ignored for enum classes.

For the enum class which is declared as
```dart
enum E with M implements I1, I2 {
```

the following kernel is generated by CFE:
```
  class E extends core::_Enum /*isEnum*/  {
```

@chloestefantsova Could you please take a look?

**Comment by chloestefantsova** [comment]
Yes, this is the functionality I'm working on at the moment. The support for mixins was added yesterday: https://dart-review.googlesource.com/c/sdk/+/227541. Currently I'm looking into supporting interfaces.
