### ISSUE TITLE
Missing tests for three diagnostics

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48159]
The diagnostics named
- `CompileTimeErrorCode.MISSING_CONST_IN_LIST_LITERAL`,
- `CompileTimeErrorCode.MISSING_CONST_IN_MAP_LITERAL`, and
- `CompileTimeErrorCode.MISSING_CONST_IN_SET_LITERAL`

do not appear to have any tests associated with them in the `analyzer` code base.

**Comment by scheglov** [comment]
An example of a test that requires, but does not report, one of such error codes is:
```dart
  solo_test_XXX() async {
    await assertErrorsInCode(r'''
void f([var a = {}]) {}
''', [
      error(CompileTimeErrorCode.NON_CONSTANT_DEFAULT_VALUE, 16, 2),
    ]);
  }
''');
  }
```

We use these error codes just as signals that another error code should be reported.

**Comment by bwilkerson** [comment]
Is either the problem message or the correction message ever used? I'm considering removing them if they're not used.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/229980
