### ISSUE TITLE
breaking change: remove support for old super-mixins from CFE and VM

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#48167]
# Background

Currently CFE allows certain targets (e.g. Flutter, Dart CLI) to use old super mixin feature - which permitted to classes to be used as mixins even when they extended something that was not an `Object`.

Meaning that CFE would compile (and VM would run) the following code:

```dart
class Base {}

class Mixin extends Base {
}

class C extends Base with Mixin {
}
```

Analyzer rejects this code with `mixin_inherits_from_not_object` error:

```console
  error • test.dart:5:27 • The class 'Mixin' can't be used as a mixin because it extends a class other than 'Object'. • mixin_inherits_from_not_object
```

Though this error can be suppressed via `// ignore:mixin_inherits_from_not_object`.

The analyser used to support this feature (hidden under a flag) but this support has been removed.

# Proposed change

We propose to remove support for this feature from CFE.

# Migration

Users should migrate their `class Mixin extends Base` declarations to use `mixin Mixin on Base` declarations instead.

```dart
class Base {}

mixin Mixin on Base {
}

class C extends Base with Mixin {
}
```

# Impact

Given that the analyzer issues an error by default we consider the risk to be minimal. 

As far as we can neither Flutter no internally Google code base does not contain any suppressions for `mixin_inherits_from_not_object` which means it does not contain any uses of these feature.

Only users that explicitly suppressed analysis error will be affected and will be required to migrate.

**Comment by mraleph** [comment]
Announced on announce@dartlang.org. @devoncarew please kick of the process.

**Comment by devoncarew** [comment]
To paraphrase from above:
- we'd like to remove support for old super-mixins from CFE and VM
- the analyzer no longer supports this syntax (it emits an `mixin_inherits_from_not_object` error)
- we haven't found places (in flutter or in google3) where this error is ignored - assumed no remaining uses of the older syntax
- and, we've sent the notification + migration email

@vsm - can you review and sign off for Dart? @Hixie - can you do the same for Flutter? And @grouma for Angular? Thanks!

**Comment by Hixie** [comment]
I didn't realise we still supported this. Sure, this is fine by me.

**Comment by Hixie** [comment]
Does removing support leave an error message in place that explains how to migrate easily?

**Comment by devoncarew** [comment]
> Does removing support leave an error message in place that explains how to migrate easily?

I assume it would leave the existing error message in place (`The class 'Mixin' can't be used as a mixin because it extends a class other than 'Object'`). @bwilkerson - perhaps this message could be modified to suggest the use of the `mixin` ... `on` syntax?

**Comment by devoncarew** [comment]
ping @vsm, @grouma

**Comment by grouma** [comment]
As far as I can tell this will not impact Angular.

**Comment by vsmenon** [comment]
lgtm

**Comment by devoncarew** [comment]
@mraleph - this breaking change request is approved; feel free to move to the next steps (https://github.com/dart-lang/sdk/blob/main/docs/process/breaking-changes.md#step-3-execution).

**Comment by mraleph** [comment]
We are ready to go @johnniwinther

**Comment by itsjustkevin** [comment]
@johnniwinther Is this something we are still moving forward with?

**Comment by johnniwinther** [comment]
It is. I'm currently looking into making some preparations in the CFE.

**Comment by johnniwinther** [comment]
This has landed.

**Comment by MaryaBelanger** [comment]
@johnniwinther can you confirm [this section in the docs on mixins](https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins) reflects the change?

**Comment by eernstg** [comment]
The section ['Mixins'](https://dart.dev/samples#mixins) is up to date. The section ['Adding features to a class: mixins'](https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins), too.

The latter does contain the sentence

> To _implement_ a mixin, create a class that extends Object and declares no constructors.

It would have been better if it said 'To implementa mixin, write a mixin declaration. For backward compatibility, it is also possible to use a class as a mixin if it extends `Object` (that is, it has the clause `extends Object` or it does not have an `extends` clause), and it does not have any constructors', but the current wording isn't actually wrong.
