### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by HeDu2027** [dart-lang/sdk#48168]
## Version information

- `IDEA AI-203.7717.56.2031.7784292`
- `2.15.1`
- `AI-203.7717.56.2031.7784292, JRE 11.0.10+0-b96-7249189x64 JetBrains s.r.o., OS Mac OS X(aarch64) v12.1, screens 2880.0x1800.0  Retina`

**Comment by mraleph** [comment]
No information provided.
