### ISSUE TITLE
Renaming the package's name in pubspec.yaml results in 'couldnt resolve the package' error when running 'dart test'

### ISSUE THREAD

**Issue by Nimrodda** [dart-lang/sdk#48163]
Dart SDK Version: 2.14.4 Linux
Disclaimer: Dart newbie here.

I think I found out a potential caching bug related to package renaming. I have a simple dart program that I created with `dart create` and I added a unit test to `test` folder. The test is run successfully until I change the package name and update the import in the test file. I then get an error `Couldn't resolve the package <package name>`. When I revert the name change and the import, the test passes and the error is gone.

Project folder structure looks like this:
lib/foo.dart
test/foo_test.dart
pubspec.yaml
... and the rest

pubspec.yaml before renaming the package:
```
name: foo
description: sample project
version: 1.0.0
```

foo_test.dart before renaming the package has the following package import:
```
import 'package:foo/foo.dart'
```
At this point the unit test, which I run with `dart test` command, runs successfully.

After renaming the package to `bar`:
pubspec.yaml:
```
name: bar
description: sample project
version: 1.0.0
```

foo_test.dart:
```
import 'package:bar/foo.dart'
```
Running `dart test` results in error: `Couldn't resolve the package 'bar'`.

If I delete the folder `.dart_tool` and run `dart test` again, the test is run successfully.
I'm not sure if this is by design, but I'd expect the cache to be updated after renaming the package.

**Comment by lrhn** [comment]
You need to run `dart pub get` whenever you change the `pubspec.yaml` file.
In this case, it will update the `.dart_tool/package_config.json` file to point the `bar` package to the current `lib` directory. Until you do that, the config file will contain an entry for the (prior) package named "foo".
