### ISSUE TITLE
[CP] Deprecation message for dartanalyzer command

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#48176]
**commit(s) to merge**: [d9b69e9](https://github.com/dart-lang/sdk/commit/d9b69e907eed1b92a436f7688d5222c8e8d87be5) should be picked into the beta channel

**merge instructions**: clean merge 

**What is the issue**: 

We planned, and announced, that the `dartanalyzer` command is deprecated in Dart 2.16: https://github.com/dart-lang/sdk/issues/46100

However, there was a mistake in how the deprecation output was added in [cr 219702](https://dart-review.googlesource.com/c/sdk/+/219702), so the deprecation messages ended up being added to a set of bin files that are only used internally during SDK development, and not in the actual `bin/dartanalyzer` and `bin/dartanalyzer.bat` files we ship in the SDK.

The intended output was added to the correct files in [cr 229143](https://dart-review.googlesource.com/c/sdk/+/229143).

**What is the fix**: Add simple print statements

**Why cherrypick**: We already announced the deprecation. If these messages don't go put in 2.16 there is a risk that developers might not realize that this command is deprecated.

**Risk**: Very low, just adds a print statement.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/46100

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by mit-mit** [comment]
Confirmed that the fix from [cr 229143](https://dart-review.googlesource.com/c/sdk/+/229143) works in a downloaded bleeding edge build (https://storage.googleapis.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-macos-x64-release.zip):

```
$ ~/tmp/dart-sdk/bin/dartanalyzer
Warning: 'dartanalyzer' is deprecated. Please use 'dart analyze'.
Usage: dartanalyzer [options...] <directory or list of files>
```

And from current beta:
```
$ ~/dev/flutter/bin/cache/dart-sdk/bin/dartanalyzer --version
dartanalyzer version 2.16.0-134.1.beta
$ ~/dev/flutter/bin/cache/dart-sdk/bin/dartanalyzer
Usage: dartanalyzer [options...] <directory or list of files>

```

**Comment by devoncarew** [comment]
From the scrum meeting, this is approved.

**Comment by whesse** [comment]
Cherry-picked into 2.16.0-134.5.beta.
