### ISSUE TITLE
[CP] Handle `Object` members of `dart:html` types in dart2js runtime

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#48189]
**commit(s) to merge**: d17205184ac5e5e9404a376673a4c6b45dd08f37

Please note that the only relevant non-test and non-status file changes are pkg/compiler/lib/src/js_emitter/native_emitter.dart and sdk/lib/_internal/js_runtime/lib/js_helper.dart, which amount to ~20 lines of code.

**merge instructions**: Cleanly cherry-picks to https://github.com/dart-lang/sdk/commit/455fe9d18007ee57ad60d0939527d2fd7fa7966c (the current beta version of 2.16.0-134.1.beta)

**What is the issue**: `dart:html` classes' type hierarchies were changed, but not fully accounted for in the dart2js runtime. This means we'd get incorrect values for some of the `Object` default methods e.g. `hashCode`.

**What is the fix**: The first change in the CL is to update the tags so dart2js can correctly register `dart:html` types. The second change is an additional if-clause to emit the right `toString` values.

**Why cherrypick**: The major component of this is `hashCode`. Maps that contain many instances of these types will hash them all in the same bucket, leading to performance regressions. Beyond this, and less importantly, `toString` and `runtimeType` result in significantly less useful values i.e. treating `dart:html` types as a generic JS object type.

**Risk**: Little.

The first change shouldn't make behavior worse than it already is, since it will only affect the `dart:html` types today. The second change only affects `toString` and error Strings when reporting a failed instance check.

**Link to original issue(s)**:  https://github.com/dart-lang/sdk/issues/48187

https://github.com/dart-lang/sdk/issues/47942 is where it first popped up.

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew @sigmundch

**Comment by sigmundch** [comment]
I'm in favor of cherry-picking. This was an unintended regression and the cherry pick will bring 2.16 in line with the behavior and performance of 2.15.

Looking through the changes, the only actual code changes are down to 7 lines, the rest are comments and tests.

**Comment by devoncarew** [comment]
Thanks for the cherry pick request! We're working through the approval now (I believe mostly related to potentially validating this change via a google3 roll).

**Comment by srujzs** [comment]
Thanks Devon!

**Comment by whesse** [comment]
Cherry-picked into 2.16.0-134.5.beta.
