### ISSUE TITLE
[dartdev] How to get the 'pub' dependency?

### ISSUE THREAD

**Issue by passsy** [dart-lang/sdk#48198]
Running `pub get` in `pkg/dartdev` errors with

```
Because dartdev depends on pub any which doesn't exist (could not find package pub at https://pub.dartlang.org), version solving failed.
```

I can manually download [`package:pub`](https://github.com/dart-lang/pub) and make `pub` a path-dependency, but that's most likely not the correct way.

How can I setup my dev environment to actually work on the `dartdev` cli?

**Comment by mraleph** [comment]
If you follow https://github.com/dart-lang/sdk/wiki/Building#getting-the-source (more specifically if you use `fetch dart` / `gclient` to pull both `sdk` repo and its dependencies as specified in `DEPS`) then you should get `sdk` folder in which everything is in the right place. (e.g. `pub` will land in `third_party/pkg/pub`).

We don't use `pub` when developing packages in the SDK tree. Instead they are all wired together through specially generated `.packages` and `.dart_tool/package_config.json` files which live directly in the `sdk` repo and assume specific layout of the checkout (which is what `gclient` tool creates and maintains).

Let me know if you need further help with this.
