### ISSUE TITLE
dart in the command not work well

### ISSUE THREAD

**Issue by singleseeker** [dart-lang/sdk#48208]
Dart SDK version: 2.17.0-51.0.dev (dev) (Sun Jan 23 22:42:03 2022 -0800) on "macos_x64"

The dart command in the terminal shows me a dot as a response.

Any idea?

I am thinking that if the user folder contains a dot, the result gets weird.

![image](https://user-images.githubusercontent.com/520698/150911619-92ceff78-c598-46e3-a24b-df74a6545669.png)

**Comment by singleseeker** [comment]
![image](https://user-images.githubusercontent.com/520698/150922577-a060ecf8-13fa-42c6-9b76-d5c234b8eefb.png)

**Comment by mraleph** [comment]
Maybe dartcli related. /cc @bkonyi

**Comment by singleseeker** [comment]
I also tried to download the zip file from https://dart.dev/get-dart/archive.
After unzip the file,

```
~ » /Users/s.s./Downloads/dart-sdk/bin/dart --version
Dart SDK version: 2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "macos_x64"

~ » /Users/s.s./Downloads/dart-sdk/bin/dart -h                                                                                                      
.

```

@bkonyi @mraleph , any advice to solve the problem？

I tried to create a new user account, with a new flutter installed, everything worked well.
But with the main account s.s., just a dot was returned even I reinstalled the flutter.

**Comment by singleseeker** [comment]
In the vs code, got errors.

![image](https://user-images.githubusercontent.com/520698/151009021-d8e8a2d8-2c6d-4651-b1d9-ea768f1cbdad.png)

**Comment by bkonyi** [comment]
I'm unable to reproduce at `2.17.0-51.0.dev` on my MacBook. I haven't tried with a user account with a dot in the name, but something like `/Users/bkonyi/test./dart-sdk/bin/dart -h` doesn't encounter the same issue.

Can you try `/Users/s.s./Downloads/dart-sdk/bin/dart -h --disable-dart-dev` and let me know if that gives you any output? 

Also, if you've still got your temporary user account without the dot in the name, can you try something similar to what I've done (e.g., download the SDK and put it into a folder with a dot somewhere in the path) and see if that behaves any differently? I doubt it's something specific to the user folder, but it's worth ruling out.

**Comment by singleseeker** [comment]
@bkonyi Thank you for your response.

I tried to move dart-sdk to the path without dot, still did not work.


```
/usr/local/development/flutter (stable) » bin/dart -h                                                                                                                                                                    
.


/usr/local/development/flutter (stable) » bin/dart -h --disable-dart-dev                                                                                                                                           
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]

Executes the Dart script <dart-script-file> with the given list of <script-arguments>.

Common VM flags:
--enable-asserts
  Enable assert statements.
--help or -h
  Display this message (add -v or --verbose for information about
  all VM options).
--packages=<path>
  Where to find a package spec file.
--define=<key>=<value> or -D<key>=<value>
  Define an environment declaration. To specify multiple declarations,
  use multiple instances of this option.
--observe[=<port>[/<bind-address>]]
  The observe flag is a convenience flag used to run a program with a
  set of options which are often useful for debugging under Observatory.
  These options are currently:
      --enable-vm-service[=<port>[/<bind-address>]]
      --serve-devtools
      --pause-isolates-on-exit
      --pause-isolates-on-unhandled-exceptions
      --warn-on-pause-with-no-debugger
  This set is subject to change.
  Please see these options (--help --verbose) for further documentation.
--write-service-info=<file_uri>
  Outputs information necessary to connect to the VM service to the
  specified file in JSON format. Useful for clients which are unable to
  listen to stdout for the Observatory listening message.
--snapshot-kind=<snapshot_kind>
--snapshot=<file_name>
  These snapshot options are used to generate a snapshot of the loaded
  Dart script:
    <snapshot-kind> controls the kind of snapshot, it could be
                    kernel(default) or app-jit
    <file_name> specifies the file into which the snapshot is written
--version
  Print the SDK version.
```

I did some tests.

* Creating a new account (q.q.) with flutter worked well.
* In the current account, neither reinstalling fluter nor changing SDK location works.

Really weird! 

What does dart-sdk depend on? Or any cache problem?
I can not even debug code unless this problem is solved.

**Comment by singleseeker** [comment]
With lots of tests, I finally solved the problem.

It`s something about permission, and I tried to reset my home folder permission, everything works well now.

```
sudo chown -R $(echo $USER):staff $(echo ~)
```

Thank you for being so helpful.  @bkonyi 

I hope it will give us more feedback when something like this happens.
It will save more time to debug.
