### ISSUE TITLE
[vm] external functions with `vm:prefer-inline` are not inlined

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48215]
`@pragma('vm:prefer-inline')` is ignored on `external` if no `@pragma("vm:external-name", ...)` is present:

The following does not get inlined:

```dart
@pragma("vm:recognized", "other")
@pragma('vm:prefer-inline')
external void reachabilityFence(Object object);
```

```
  => reachabilityFence (deopt count 0)
     Bailout: not inlinable
```

However, this does:

```dart
@pragma("vm:recognized", "other")
@pragma('vm:prefer-inline')
@pragma("vm:external-name", "Ffi_reachabilityFence")
external void reachabilityFence(Object object);
```

```
vm:prefer-inline pragma for Function 'reachabilityFence': static.
  => reachabilityFence (deopt count 0)
vm:prefer-inline pragma for Function 'reachabilityFence': static.
vm:prefer-inline pragma for Function 'reachabilityFence': static.
     Success
       with reason AlwaysInline, code size 2, call sites: 0

```

External functions are rejected from inlining:

```c++
#if !defined(DART_PRECOMPILED_RUNTIME)
bool Function::CanBeInlined() const {
  // <snip>

  return is_inlinable() && !is_external() && !is_generated_body();
}
#endif  // !defined(DART_PRECOMPILED_RUNTIME)
```

Commit rejecting `external` functions from being inlined: 78a6b4615557bd5634b8d0554e1c2fb47cc53ef7.

`native`s became `external` with a `@pragma("vm:external-name", ...)` in: d8d7af15ce9e4eb78c8aac0dfa46413036747bb7.

Arguably, `@pragma('vm:prefer-inline')` should take precedence in this case.

**Comment by rmacnak-google** [comment]
The patching of functions in already-finalized classes that 78a6b4615557bd5634b8d0554e1c2fb47cc53ef7 was concerned with could only happen in the old VM frontend, not the new CFE.

**Comment by mkustermann** [comment]
> natives became external with a @pragma("vm:external-name", ...) in: d8d7af1.

Actually, the VM still uses `native` to describe natives. If there's an `@pragma('vm:external-name', '<name>')` we'll clear `is_external()` and set `is_native()`.

Actual native calls can in fact not be inlined, but the way this is prevented is via a bailout instead of via `CanBeInlined()`.

**Comment by dcharkes** [comment]
Thanks @rmacnak-google I've updated the CL to reflect this.

@mkustermann yes it still uses 'native', that why they were inlined already if they were 'native' but were recognized rather than using the runtime entry. Thanks for the review!
