### ISSUE TITLE
"you've found a bug in our compiler"

### ISSUE THREAD

**Issue by jscholler** [dart-lang/sdk#48249]
Hello, I guess the compiler has a message for this board :)

Some context:
upon seeing this, I did `dart pub cache clean` and re-installed webdev. Still the same error upon serving. I did a couple of `webdev build` & `webdev serve` and it went away.

I am no sure this related, but I am serving multiple dart frontends that have some shared code. 

```
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/local/Cellar/dart/2.15.1/libexec/lib/_internal/ddc_outline_sound.dill --modules=amd --no-summarize -o packages/util_web_lib/src/state_machine/machine.sound.ddc.js --source-map --summary=packages/util_web_lib/src/logging.sound.ddc.dill=packages/util_web_lib/src/logging --packages=.dart_tool/package_config.json --module-name=packages/util_web_lib/src/state_machine/machine --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/local/Cellar/dart/2.15.1/libexec/lib/libraries.json --experimental-emit-debug-metadata --used-inputs-file=/var/folders/76/lhgzkrts64d4nq01d0yczqgh0000gn/T/ddk_builder_71VJ8I/used_inputs.txt package:util_web_lib/src/state_machine/state.dart package:util_web_lib/src/state_machine/machine.dart --sound-null-safety
    dart --version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"

FileSystemException(uri=file://packages/util_web_lib/src/logging.sound.ddc.dill; message=No such file or directory)
#0      _IoFileSystemEntity.readAsBytes (package:front_end/src/api_prototype/standard_file_system.dart:85:57)
#1      MultiRootFileSystemEntity.readAsBytes (package:build_integration/file_system/multi_root.dart:82:61)
<asynchronous suspension>
#2      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:209:13)
<asynchronous suspension>
#3      _compile (package:dev_compiler/src/kernel/command.dart:301:21)
<asynchronous suspension>
#4      compile (package:dev_compiler/src/kernel/command.dart:51:12)
<asynchronous suspension>
#5      _CompilerWorker.performRequest (file:///opt/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:68:18)
<asynchronous suspension>
#6      AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:35:20)
<asynchronous suspension>
#7      main (file:///opt/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:31:5)
<asynchronous suspension>
```

**Comment by nshahan** [comment]
@jakemac53 Can you think of anything that would conflict when serving multiple apps at the same time? Could there be a lock on a .dill file that is shared between the apps?

**Comment by jakemac53** [comment]
Using webdev it should use the build daemon so they won't conflict. If one is using build_runner directly though it's possible.

But this is actually a long standing known issue that we have never been able to reproduce or track down. We thought maybe some other fixes had resolved it, but it seems not.

The best resolution is to just delete your `.dart_tool` directory which will purge the cache.

**Comment by nshahan** [comment]
@jscholler Does deleting the `.dart_tool` directory in your package resolve the issue?

**Comment by sigmundch** [comment]
For reference the other bug tracking the flakyness issues is https://github.com/dart-lang/sdk/issues/38102. The exception looks slightly different, but it could be the same cause. If we believe this is the same problem, we can dedup them.

**Comment by devoncarew** [comment]
(Note: we recently added a ['no response'](https://github.com/dart-lang/sdk/wiki/Triaging-Dart-SDK-issues#using-the-needs-info-label) bot to our repo; it may have closed existing issues with the `needs-info` label incorrectly. If you think your issue was effected, please feel free to reopen the issue)
