### ISSUE TITLE
[dart2js] dart:web_gl NoSuchMethodError: method not found: 'get$TEXTURE_MAX_ANISOTROPY_EXT'

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#48240]
See original issue for repro: https://github.com/flutter/flutter/issues/96659

**Comment by annagrin** [comment]
Maybe similar: https://github.com/flutter/flutter/issues/97357

**Comment by srujzs** [comment]
This is a duplicate of https://github.com/dart-lang/sdk/issues/48152 I believe. I don't think #97357 is similar, I'm commenting on that bug now. The flutter issue should be closed in favor of #48152 imo, as it's an issue within the SDK.

**Comment by sigmundch** [comment]
closing as duplicate of #48152
