### ISSUE TITLE
The message for MISSING_ANNOTATION_ON_STRUCT_FIELD could be improved

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48256]
The problem message for `FfiCode.MISSING_ANNOTATION_ON_STRUCT_FIELD` could be improved. In a review with the FFI team, we agreed on the following message: "Fields of type '{0}' in a subclass of '{1}' must have an annotation indicating the native type.".

This might require some reworking of the `FfiVerifier` in order to make the two argument values available in the scope where the diagnostic is generated.

**Comment by CicadaCinema** [comment]
https://dart-review.googlesource.com/c/sdk/+/241280
