### ISSUE TITLE
Add delete as JS native in js_util

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#48265]
We have `setProperty` and `getProperty` from `dart:js_util`.   

Would be very useful to be able to use `delete` natively.  
Without `delete` we have to depend on `Reflect` methods, which are expensive and with restricted compatibility.

Reading the `js_util.dart` I guess would be something like 

```dart
void delete<T>(Object o) {
  return JS('', 'delete #', o);
}
```

**Comment by Markzipan** [comment]
Similar to: https://github.com/dart-lang/sdk/issues/31692

What were some cases that would benefit from a native `delete` that `Reflect` doesn't already accomplish (besides performance)?

**Comment by jodinathan** [comment]
compatibility and `Reflect` is 3x slower than native `delete`: https://www.measurethat.net/Benchmarks/Show/11339/0/reflectdeleteproperty-vs-delete#latest_results_block

**Comment by Markzipan** [comment]
Thanks for the info!

Any opinions here @rileyporter and @srujzs?

**Comment by ditman** [comment]
I just found myself in the need of this while writing some cleanup code :)

**Comment by srujzs** [comment]
Thought I responded to this when this was first filed. I think this is useful and it should be simple to add this, especially since there's no alternative. We'll likely just keep the dart2wasm implementation as unimplemented like a number of other js_util APIs.

**Comment by ditman** [comment]
Thanks @srujzs!

**Comment by rileyporter** [comment]
I'm adding some other JS operators to js_util for the web backends, so I can do this at the same time.

**Comment by rileyporter** [comment]
Done in https://github.com/dart-lang/sdk/commit/b6388f2ea08da228ba5d36e9a6f88521cb878a66

**Comment by ditman** [comment]
Yeeeeesssss!! Thanks @rileyporter!!
