### ISSUE TITLE
WeakReference constructor doesn't reject object that is not supported as an Expando key

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48264]
According to the `WeakReference` [documentation](https://api.dart.dev/dev/2.17.0-71.0.dev/dart-core/WeakReference-class.html)

> Not all objects are supported as targets for weak references. The WeakReference constructor will reject any object that is not supported as an Expando key.

But, in fact, it doesn't
```dart
    WeakReference wr = WeakReference<String>("Lily was here"); // No error here
    print(wr.target); 
```
Expando does not work on numbers, strings, booleans, null, dart:ffi pointers, dart:ffi structs, or dart:ffi unions. All of these objects must be rejected by `WeakReference` constructor

**Comment by sgrekhov** [comment]
cc @dcharkes

**Comment by dcharkes** [comment]
Thanks @sgrekhov.

Fix underway: https://dart-review.googlesource.com/c/sdk/+/231481.
