### ISSUE TITLE
Remove `.packages` from the Dart SDK repo

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#48275]
I dropped a bunch of places reading this file in https://dart-review.googlesource.com/c/sdk/+/211503, but there are still some places that depend on it.

**Comment by mit-mit** [comment]
@natebosch any chance we could assign this issue to you to get the rest removed the SDK repo?

**Comment by natebosch** [comment]
Sure, I am planning to keep pushing on this as I have time.

**Comment by natebosch** [comment]
> I just grepped through this repo for "dotPackages"

Yeah there are still a bunch. Any help cleaning up whatever you find is great.

`dotPackages` as a variable name can sometimes refer to the path to `.dart_tool/package_config.json` since some tools were updated to understand either file with the same argument.

**Comment by scheglov** [comment]
There are a few shared tests that use `.packages`, started failing [here](https://dart-ci.firebaseapp.com/cl/237637/1).
```
standalone_2/package/scenarios/both_dir_and_file/prefers_packages_file_test
standalone_2/package/scenarios/packages_file_in_parent/sub/packages_file_in_parent_test
standalone_2/package/scenarios/packages_file_only/packages_file_only_test
```

**Comment by mit-mit** [comment]
@sigmundch there are a bunch of search hits on `.packages` in `/pkg/compiler/` -- is that something the web team can look at in Q2?

**Comment by mit-mit** [comment]
@johnniwinther there are a bunch of search hits on .packages in `/pkg/front_end/` -- is that something the CFE team can look at in Q2?

**Comment by mit-mit** [comment]
@sortie I see a bunch of search hits on `.packages` in `/tools.bots` -- is that something you can help with?

**Comment by sigmundch** [comment]
I think we should be able to get rid of the web uses of `.packages`. A big bulk of them come from the modular_test framework, which we created a few years back. That required changing how the framework works, but I made progress on that today via https://dart-review.googlesource.com/c/sdk/+/240651/3 and https://dart-review.googlesource.com/c/sdk/+/240650/2

**Comment by johnniwinther** [comment]
@mit-mit Have we deprecated the feature yet? I'd like to keep testing of the feature as long as we support it.

**Comment by mit-mit** [comment]
@johnniwinther sorry missed your question. Yes, the `.packages` file has been deprecated since Dart 2.8.

**Comment by mit-mit** [comment]
I'm making some progress in https://dart-review.googlesource.com/c/sdk/+/243625 on removing the generation of the `.packages` file. There are a lot of failures I don't understand though in the test results for patchset 3 for DDC:
https://ci.chromium.org/ui/p/dart/builders/try/ddc-linux-release-chrome-try/42906/overview

@athomas @sigmundch does this somehow ring a bell to you?

**Comment by sigmundch** [comment]
@mit-mit Funny you ask today, just yesterday I came across the same error.

FYI @sortie also has a step to remove the use of .packages on the bots (see https://dart-review.googlesource.com/c/sdk/+/240842). That prompted me to make a similar change to yours to unblock him (https://dart-review.googlesource.com/c/sdk/+/243643), but also came across the errors on the DDC bots. I haven't yet investigated, but it's possible that the errors are not DDC specific, but more of an infra issue with the test runner or the http server it uses to launch browser tests. I'll try to check later today if I get a chance, but otherwise I'll look tomorrow.

**Comment by sigmundch** [comment]
Turns out the DDC bot failures were due to an issue in the test runner. The test runner was generating an invalid html to bootstraps the ddc code after the change because it used the path of the package configuration file in its logic. 

I'm attempting a new run with a fix in https://dart-review.googlesource.com/c/sdk/+/243643

**Comment by sigmundch** [comment]
(and forgot to say, this turned out to be exactly what @athomas suggested initially. At first I didn't put together how that logic connected with DDC, but I landed in that same place after looking at the generated JavaScript)

**Comment by sortie** [comment]
.packages has now been removed from the bots, thanks everyone for helping that along :)

**Comment by mit-mit** [comment]
https://dart-review.googlesource.com/c/sdk/+/243625 has been created to stop generating the `.packages` file in the SDK

**Comment by mit-mit** [comment]
@natebosch are you aware of any other work for the present issue after /243625 lands?

**Comment by natebosch** [comment]
If /243625 doesn't cause any issues I think that covers the vast majority, though there may be a bit more cleanup to do.

I found a few references - https://dart-review.googlesource.com/c/sdk/+/244046

I'm a little surprised that these references don't cause any issues when you stop creating the `.packages` file entirely...

**Comment by mit-mit** [comment]
/243625 and /244046 have both landed 🚀 , so closing this issue
