### ISSUE TITLE
[dart2js] Missing type metadata for type used only in generic function instantiation

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#48277]
The type metadata for `Queue` is missing in this program:

```dart
import 'dart:collection';

class Foo<T> {}

const f1 = Foo<Queue>.new;
const f2 = Foo<Queue<String>>.new;

main() {
  print(f1() is Foo<Iterable>);
  print(f2() is Foo<Iterable<Comparable>>);

  print(f1() as Foo<Iterable>);
  print(f2() as Foo<Iterable<Comparable>>);

  print(check<Foo<Iterable>>(f1()));
  print(check<Foo<Iterable<Comparable>>>(f2()));
}

T check<T>(x) => x as T;
```
This leads to errors in subtype tests:
```
false
false
Instance of 'Foo<Queue<dynamic>>'
Instance of 'Foo<Queue<String>>'
o9.js:945: TypeError: Instance of 'Foo<Queue<dynamic>>': type 'Foo<Queue<dynamic>>' is not a subtype of type 'Foo<Iterable<dynamic>>'
      throw A.wrapException(A._TypeError$fromMessage(A._Error_compose(object, A.instanceOrFunctionType(object, testRti), A._rtiToString(testRti, null))));
      ^
TypeError: Instance of 'Foo<Queue<dynamic>>': type 'Foo<Queue<dynamic>>' is not a subtype of type 'Foo<Iterable<dynamic>>'
    at Object.wrapException (o9.js:324:17)
    at Object._failedAsCheck (o9.js:945:15)
    at Rti._generalAsCheckImplementation [as _as] (o9.js:934:9)
    at Rti._installSpecializedAsCheck (o9.js:873:22)
    at main (o9.js:2159:18)
    at o9.js:2659:7
    at o9.js:2638:7
    at dartProgram (o9.js:2653:5)
    at o9.js:2661:3
```
(the two direct `as` expressions pass because they are removed - not sure where this is happening)

**Comment by fishythefish** [comment]
Just from a glance at this issue, my hunch is that the RTI computation may need to be updated for constructor tearoffs, since invoking them can create instances. (We'll likely have to be conservative about this - if we observe a constructor tearoff, we should treat that type as having instances, whether that tearoff eventually ends up being called or not.)

**Comment by rakudrama** [comment]
@fishythefish Constructor tear-offs are (possible generic) static methods that call the constructor, so my hunch is that we should be able to reproduce this with hand-rolled static method tear-offs, i.e. code that was possible before constructor tear-offs. Maybe there is something different about the CFE-generated static methods.

**Comment by fishythefish** [comment]
@rakudrama Such a hand-rolled static method would still have to invoke a constructor in its body, right? So we would have noted that the type has instances when we saw the constructor call. I'm guessing we didn't add any special handling for `Foo.new`, but we should probably treat it the same as seeing `new Foo()`.
