### ISSUE TITLE
Incorrect behaviour of `keys` and `values` iterables of VM LinkedHashMaps

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#48282]
The documentation on Map states "Modifying the map while iterating the keys or values may also break the iteration".
I believe the VM result below is incorrect because the keys are iterated completely between modifications.

```dart
import 'dart:collection';

void printIt(String name, Object Function() f) {
  try {
    print('$name: ${f()}');
  } catch (e) {
    print('$name: throws $e');
  }
}

void check(String name, Map<String,Object> m) {
  m['a'] = 1;
  m['b'] = 2;
  final keys = m.keys;
  printIt('$name.keys.length', () => keys.length);
  printIt('$name.keys', () => keys);
  m['c'] = 3;
  printIt('$name.keys.length', () => keys.length);
  printIt('$name.keys', () => keys);
  m['x'] = 24;
  printIt('$name.keys.length', () => keys.length);
  printIt('$name.keys', () => keys);
  m['y'] = 25;
  printIt('$name.keys.length', () => keys.length);
  printIt('$name.keys', () => keys);
}

void main() {
  check('Map', {});
  check('HashMap', HashMap());
  check('SplayTreeMap', SplayTreeMap());
}
```
VM result:
```
Map.keys.length: 2
Map.keys: (a, b)
Map.keys.length: 3
Map.keys: (a, b)
Map.keys.length: 4
Map.keys: (a, b)
Map.keys.length: 5
Map.keys: throws Concurrent modification during iteration: _LinkedHashMap len:5.
HashMap.keys.length: 2
HashMap.keys: (a, b)
HashMap.keys.length: 3
HashMap.keys: (c, a, b)
HashMap.keys.length: 4
HashMap.keys: (c, a, b, x)
HashMap.keys.length: 5
HashMap.keys: (y, c, a, b, x)
SplayTreeMap.keys.length: 2
SplayTreeMap.keys: (a, b)
SplayTreeMap.keys.length: 3
SplayTreeMap.keys: (a, b, c)
SplayTreeMap.keys.length: 4
SplayTreeMap.keys: (a, b, c, x)
SplayTreeMap.keys.length: 5
SplayTreeMap.keys: (a, b, c, x, y)
```
dart2js result
```dart
Map.keys.length: 2
Map.keys: (a, b)
Map.keys.length: 3
Map.keys: (a, b, c)
Map.keys.length: 4
Map.keys: (a, b, c, x)
Map.keys.length: 5
Map.keys: (a, b, c, x, y)
HashMap.keys.length: 2
HashMap.keys: (a, b)
HashMap.keys.length: 3
HashMap.keys: (a, b, c)
HashMap.keys.length: 4
HashMap.keys: (a, b, c, x)
HashMap.keys.length: 5
HashMap.keys: (a, b, c, x, y)
SplayTreeMap.keys.length: 2
SplayTreeMap.keys: (a, b)
SplayTreeMap.keys.length: 3
SplayTreeMap.keys: (a, b, c)
SplayTreeMap.keys.length: 4
SplayTreeMap.keys: (a, b, c, x)
SplayTreeMap.keys.length: 5
SplayTreeMap.keys: (a, b, c, x, y)
```

**Comment by rakudrama** [comment]
@lrhn Do you agree the VM is wrong?
Would you prefer [tests in corelib](https://dart-review.googlesource.com/c/sdk/+/231333) or [tests in lib/collection](https://dart-review.googlesource.com/c/sdk/+/231336)?

**Comment by dcharkes** [comment]
Interesting, that bug has been there for years.

> To fix that bug, the access of _data and _usedData at get:keys needs to be moved later, to the construction of the  Iterator , not the iterable.
> This moves the access away from a context that is specialized to the Base by duplication in a mixin application to a context that is unspecialized. The accesses, when moved to the _CompactIterable becomes polymorphic in the Base.
> 
> This specific version is fine because it is specialzed _HashVMImmutableBase, but the remaining cases need to be fixed by even more manual duplication.
> 
> We will need three versions of _CompactIterable and _CompactIterator for the three bases. I wonder if there is a way to make it happen automatically?

@rakudrama on https://dart-review.googlesource.com/c/sdk/+/231243/6/sdk/lib/_internal/vm/lib/compact_hash.dart#332

Maybe we need to untangle the mixin behavior there when addressing this.

**Comment by lrhn** [comment]
I agree that the VM is wrong. The `keys` getter is intended to be lazily backed by the map, and not get locked in until you starts iterating, like every other iterable backed by a collection.

I think I'd put the test in `lib.collection`, but it's been a little inconsistent so far (`Map` is in `dart:core`, `LinkedHashMap` is in `dart:collection`, but the `Map` implementation is really `LinkedHashMap`, so anything goes, really).

**Comment by lrhn** [comment]
I'll make a fix. Shouldn't be too hard.

**Comment by rakudrama** [comment]
There is a 10% regression on  `Iterators.poly.Map.int.keys.1` for dart-aot.
This indicates that `for (final value in map.keys)` is slower for a low trip-count loop.
Dart JIT is not affected.

I have not looked at the generated code, but I suspect that `_CompactIterable.get:iterator` is now just big enough to make AOT shy about inlining, and as a result `.keys.iterator` is no longer two inlinings followed by the scalar replacement through load-elimination of the ephemeral keys-iterable. JIT is more aggressive inlining which would explain why it is not affected.

Could AOT be more clever in deciding to inline this kind of target - i.e. if an argument is an allocation and the target just uses the argument for loads, we can expect the final fields of the allocation to be store-forwarded and therefore should not be considered?

**Comment by mraleph** [comment]
as a temporary workaround we could just annotation `_CompactIterable.get:iterator` with `@pragma('vm:prefer-inline')`. /cc @lrhn

**Comment by mraleph** [comment]
I have looked at this. The reason for the regression is that `get:iterator` become slightly more expensive: it accesses `_data` and `_usedData` through `_HashBase` interface that has two implementations `_HashVMBase` and `_HashFieldBase`. This means compiler is unable to inline `table._data` and `table._usedData` and those become virtual (GDT) calls. Previously we would load them from inside `get keys => ...` / `get values => ` which are declared within mixin and copied into the concrete class, so they were simple field accesses. 

We need to get rid of `_HashVMBase`  `_HashFieldBase` split for this to become better.

**Comment by rakudrama** [comment]
> I have looked at this. The reason for the regression is that `get:iterator` become slightly more expensive: it accesses `_data` and `_usedData` through `_HashBase` interface that has two implementations `_HashVMBase` and `_HashFieldBase`. This means compiler is unable to inline `table._data` and `table._usedData` and those become virtual (GDT) calls. Previously we would load them from inside `get keys => ...` / `get values => ` which are declared within mixin and copied into the concrete class, so they were simple field accesses.
> 
> We need to get rid of `_HashVMBase` `_HashFieldBase` split for this to become better.

I had forgotten about these base classes.

`_CompactIterator.moveNext` must have the same problem at `_table.isModifiedSince`. That would be worth inlining.

How difficult is it to un-split `_HashBase`? If it is too difficult or a long-term project due to dependencies, perhaps the whole Table -> Iterable -> Iterator scheme could be specialized via mixins.

> 
> > I have not looked at the generated code, but I suspect that `_CompactIterable.get:iterator` is now just big enough to make AOT shy about inlining, and as a result `.keys.iterator` is no longer two inlinings followed by the scalar replacement through load-elimination of the ephemeral keys-iterable. JIT is more aggressive inlining which would explain why it is not affected.
> 
> This is polymorphic benchmark so call site does not know which iterable it is iterating.

**Comment by a-siva** [comment]
Is the temporary workaround mentioned in https://github.com/dart-lang/sdk/issues/48282#issuecomment-1621272867 still a feasible thing, trying to see if that would be a quick way to address the flutter regression https://github.com/flutter/flutter/issues/130339

**Comment by mraleph** [comment]
@a-siva that workaround was suggested based on the assumption that performance is affected by the `get iterator` not being inlined, but that was proven to be not the case (at least for the concrete benchmark I have looked at: https://github.com/dart-lang/sdk/issues/48282#issuecomment-1625241307). Let me look at the flutter regression.

**Comment by lrhn** [comment]
Tried to de-polymorph the code: https://dart-review.googlesource.com/c/sdk/+/313380
(Not sure how to test if performance is better.)

**Comment by a-siva** [comment]
> Tried to de-polymorph the code: https://dart-review.googlesource.com/c/sdk/+/313380 (Not sure how to test if performance is better.)

Looks like @jason-simmons has a local setup to measure impact of a change on the Flutter benchmark, should we try your change above to see if it has an impact ?

**Comment by jason-simmons** [comment]
https://dart-review.googlesource.com/c/sdk/+/313380 did not make a significant difference in the `complex_layout_scroll_perf_bad_ios__timeline_summary` benchmark on an iPhone 11.

(The runs that I did actually showed a slight increase in frame build times with that patch)

**Comment by mraleph** [comment]
I am working on removing `_HashVMBase` altogether. I will then check generated code to see if it returns back to where it was before this change.

**Comment by eseidel** [comment]
In case anyone else is running tests on stable dart and confused by this failure, the new test here is expected to fail in 3.1:
```
eseidel@erics-mbp sdk % dart run tests/lib/collection/map_iterables_consistency_test.dart 
Unhandled exception:
Concurrent modification during iteration: _Map len:1.
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:710:7)
#1      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#2      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#3      new List.of (dart:core-patch/array_patch.dart:47:28)
#4      check (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/tests/lib/collection/map_iterables_consistency_test.dart:47:27)
#5      main (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/tests/lib/collection/map_iterables_consistency_test.dart:69:3)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
eseidel@erics-mbp sdk % dart --version
Dart SDK version: 3.1.5 (stable) (Tue Oct 24 04:57:17 2023 +0000) on "macos_arm64"
```
