### ISSUE TITLE
[Enhanced enums] No error in analyzer when enum declared instance field named `values`

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48289]
The following code produces no issues in analyzer.
```dart
enum E1 {
  e1,
  e2,
  e3;

  final int values = 42;
}

main() {
  E1.e1;
}
```
In CFE it is an error
```
 Error: Constant evaluation error:
  final int values = 42;
            ^
```
Tested on `Dart SDK version: 2.17.0-edge.5e8e68c2c86983f8f4bc856e3ad5092db4d65f6c (be) (Thu Feb 3 01:08:34 2022 +0000) on "linux_x64"`

**Comment by scheglov** [comment]
The analyzer now reports an error for this case.
