### ISSUE TITLE
[Enhanced enums] missing implementations are not reported in analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48291]
The following co19 test fails in analyzer https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A11_t02.dart
```dart
abstract class I {
  String toString([int index]);
}

enum E1 implements I {
//                 ^
// [analyzer] unspecified
// [cfe] unspecified
  e1,
  e2,
  e3;
}

enum E2<T> implements I {
//                    ^
// [analyzer] unspecified
// [cfe] unspecified
  e1<int>(42),
  e2<String>("42"),
  e3<bool>(false);

  const E2(T t);
}

main() {
  E1.e1;
  E2.e1;
}
```
Missing implementation of `I.toString` not reported.

Tested on `Dart SDK version: 2.17.0-edge.5e8e68c2c86983f8f4bc856e3ad5092db4d65f6c (be) (Thu Feb 3 01:08:34 2022 +0000) on "linux_x64"`

**Comment by sgrekhov** [comment]
See also https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A11_t01.dart

**Comment by scheglov** [comment]
The analyzer now reports errors for these cases.
