### ISSUE TITLE
[Enhanced enums] override errors are not reported in analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48290]
The following co19 test fails in analyzer https://github.com/dart-lang/co19/blob/4fa20bd5aa56f2d2f45c94e4e2c90d39fd8575fe/LanguageFeatures/Enhanced-Enum/semantics_A10_t01.dart

```dart
enum E1 {
  e1,
  e2,
  e3;

  String get index => "Lily was here";
//           ^^^^^
// [analyzer] unspecified
// [cfe] unspecified

  String toString(int index) => "E1";
//       ^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
}

enum E2<T> {
  e1<int>(42),
  e2<String>("42"),
  e3<bool>(false);

  const E2(T t);
  String index() => "Lily was here";
//       ^^^^^
// [analyzer] unspecified
// [cfe] unspecified

  void set toString(int index) {}
//         ^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
}

main() {
  E1.e1;
  E2.e1;
}
```
`index` override error not detected, error because `index` can't be overridden at all not reported. `toString` override error not reported.

Tested on `Dart SDK version: 2.17.0-edge.5e8e68c2c86983f8f4bc856e3ad5092db4d65f6c (be) (Thu Feb 3 01:08:34 2022 +0000) on "linux_x64"`

**Comment by scheglov** [comment]
The analyzer reports errors for these cases now.
