### ISSUE TITLE
[Enhanced enums] CFE reports wrong setter/getter signature error

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48297]
The following co19 test fails on CFE https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A09_t10.dart
```dart
import "../../Utils/expect.dart";

enum E1 {
  e1,
  e2,
  e3;

  static void set e1(E1 val) {
    Expect.equals(E1.e2, val);
  }
}

enum E2<T> {
  e1<int>(42),
  e2<String>("42"),
  e3<bool>(false);

  const E2(T t);
  static void set e1(E2<int> val) {
    Expect.equals(E2.e1, val);
  }
  static void set e2(E2<String> val) {
    Expect.equals(E2.e2, val);
  }
  static void set e3(E2<bool> val) {
    Expect.equals(E2.e3, val);
  }
}

main() {
  E1.e1 = E1.e2;
  E2.e1 = E2.e1;
  E2.e2 = E2.e2;
  E2.e3 = E2.e3;
}
```
The type of `E2.e1` is considered to be `E2<dynamic>`, but it should be `E2<int>`, so there should not be a setter/getter
signature error

Tested on `Dart SDK version: 2.17.0-edge.5e8e68c2c86983f8f4bc856e3ad5092db4d65f6c (be) (Thu Feb 3 01:08:34 2022 +0000) on "linux_x64"`

**Comment by chloestefantsova** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/236000.
