### ISSUE TITLE
[Enhanced enums] naming conflicts are not reported in analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48295]
The following co19 test fails in analyzer https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A09_t05.dart

```dart
enum E1 {
  e1,
  e2,
  e3;

  void set e1(int v) {};
//         ^^
// [analyzer] unspecified
// [cfe] unspecified
}

enum E2<T> {
  e1<int>(42),
  e2<String>("42"),
  e3<bool>(false);

  const E2(T t);
  void set e2(int v) {}
//         ^^
// [analyzer] unspecified
// [cfe] unspecified
}

enum E3 {
  e1,
  e2,
  e3;

  static void set e1(int i) {}
//                ^^
// [analyzer] unspecified
// [cfe] unspecified
}

main() {
  E1.e1;
  E2.e1;
  E3.e1;
}
```
All of these errors should be reported

Tested on `Dart SDK version: 2.17.0-edge.5e8e68c2c86983f8f4bc856e3ad5092db4d65f6c (be) (Thu Feb 3 01:08:34 2022 +0000) on "linux_x64"`

**Comment by sgrekhov** [comment]
See https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A09_t08.dart as well

**Comment by lrhn** [comment]
These are errors, not because you can't have a setter named `e1=`, but because you can't have a static getter `e1` and an instance setter `e1=`.

So, `E3` is actually valid.

**Comment by eernstg** [comment]
PS: `E3.e1` has a return type of `E3`, but `E3.e1=` has a parameter type of `int`, and `E3 <: int` does not hold.

**Comment by scheglov** [comment]
The analyzer reports an error for each enum above now.
