### ISSUE TITLE
[Enhanced enums] CFE doesn't report names conflict

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48294]
The following co19 test fails in CFE https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A09_t04.dart
```dart
enum E1 {
  e1,
  e2,
  e3;

  int get e1 => 42;
//        ^^
// [analyzer] unspecified
// [cfe] unspecified
}

enum E2<T> {
  e1<int>(42),
  e2<String>("42"),
  e3<bool>(false);

  const E2(T t);
  int get e2 => 42;
//        ^^
// [analyzer] unspecified
// [cfe] unspecified
}

enum E3 {
  e1,
  e2,
  e3;

  static int get e1 => 42;
//                     ^^
// [analyzer] unspecified
// [cfe] unspecified
}

main() {
  E1.e1;
  E2.e1;
  E3.e1;
}
```
Expected errors are not reported
Tested on `Dart SDK version: 2.17.0-edge.5e8e68c2c86983f8f4bc856e3ad5092db4d65f6c (be) (Thu Feb 3 01:08:34 2022 +0000) on "linux_x64"`

**Comment by chloestefantsova** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/232380.
