### ISSUE TITLE
[Enhanced enums] Getter/setter signature mismatch error not detected

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48296]
The following co19 test fails in analyzer https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A09_t11.dart

```dart
enum E1 {
  e1,
  e2,
  e3;

  static void set e1(int val) {}
//                   ^^^
// [analyzer] unspecified
// [cfe] unspecified
}

enum E2<T> {
  e1<int>(42),
  e2<String>("42"),
  e3<bool>(false);

  const E2(T t);
  static void set e1(E2<String> val) {}
//                      ^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
  static void set e2(E2<bool> val) {}
//                      ^^^^
// [analyzer] unspecified
// [cfe] unspecified
  static void set e3(E2<int> val) {}
//                      ^^^
// [analyzer] unspecified
// [cfe] unspecified
}

main() {
  E1.e1;
  E2.e1;
  E2.e2;
  E2.e3;
}
```
Expected errors should be detected
Tested on `Dart SDK version: 2.17.0-edge.5e8e68c2c86983f8f4bc856e3ad5092db4d65f6c (be) (Thu Feb 3 01:08:34 2022 +0000) on "linux_x64"`

**Comment by scheglov** [comment]
I believe this is implemented now, with the exception that the error is reported on the enum constants, as we do for classes - we report on fields and getters.
