### ISSUE TITLE
Probable dart2js bug in profile or release mode

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#48304]
Hi,

several users of my get_it package ran into an exception when running their Flutter app on web in release or profile mode.
The exception and the generated code don't make any sense to me.

Please see details at

https://github.com/fluttercommunity/get_it/issues/238

**Comment by sigmundch** [comment]
/cc @fishythefish

I've been spending some time investigating this issue, and I have narrowed down the problem a bit. I believe this is a bug in the RTI optimization. 

I'll continue working on reducing the test further. I've managed to get it working locally without flutter, but I need a bit more iteration to figure out a good workaround and a smaller repro.

**Comment by sigmundch** [comment]
Looking more closely, this seems related to the use of `call` methods in the application. If I explicitly call generic methods instead of using the callable interface, the error goes away.

**Comment by sigmundch** [comment]
@fishythefish - I was able to reduce this further, but I haven't yet tried ripping out the get_it dependency. This is however a pretty small program:

```dart
import 'package:get_it/get_it.dart';

abstract class ISecureStorage {}
class WebSecureStorage implements ISecureStorage {}

class AppSecureStorage implements ISecureStorage {
  final ISecureStorage _storage;
  AppSecureStorage(this._storage);
}

class Module  {
  Module(this._getIt);
  final GetIt _getIt;
  AppSecureStorage get appSecureStorage => AppSecureStorage(_getIt<ISecureStorage>());
}

void main() {
  final get = GetIt.instance;
  final libCommonModule = Module(get);
  get.registerFactory<ISecureStorage>(() => WebSecureStorage());
  libCommonModule.appSecureStorage;
}
```

Oddly enough, inlining the `appSecureStorage` getter by hand makes the error disappear.

**Comment by sigmundch** [comment]
(and similarly changing `_getIt<ISecureStorage>()` to invoke `.get` directly also fixes the issue: `_getIt<ISecureStorage>.get()`)

**Comment by fishythefish** [comment]
@sigmundch I'll take a look when I get a minute. I'm not surprised that `call` support is broken - I've fixed multiple similar bugs in the past.

**Comment by sigmundch** [comment]
And here is a standalone repro:
```dart
abstract class GetIt {
  static final GetIt instance = F();
  registerFactory<T>(Function f);
  call<T>();
  get<T>();
}

class F implements GetIt {
  Map<Type, Factory> map = {};
  registerFactory<T>(Function f) => map[T] = Factory(f);
  call<T>() => get<T>();
  get<T>() => map[T]!.allocator();
}

class Factory {
  Function allocator;
  Factory(this.allocator);
}

abstract class ISecureStorage {}
class WebSecureStorage implements ISecureStorage {}

class AppSecureStorage implements ISecureStorage {
  final ISecureStorage _storage;
  AppSecureStorage(this._storage);
}

class Module  {
  Module(this._getIt);
  final GetIt _getIt;
  AppSecureStorage get appSecureStorage => AppSecureStorage(_getIt<ISecureStorage>());
}

void main() {
  final get = GetIt.instance;
  final libCommonModule = Module(get);
  get.registerFactory<ISecureStorage>(() => WebSecureStorage());
  libCommonModule.appSecureStorage;
}
```

Note that removing the `GetIt` interface also hides the issue.

**Comment by fishythefish** [comment]
Great, thanks so much, @sigmundch! Small repros go a long way whenever I'm debugging these issues.

**Comment by fishythefish** [comment]
Just started taking a look at this, but wanted to provide a quick update. It seems that although `call<T>` should take a type argument, we appear to always be supplying `dynamic`, which causes the map lookup to fail. (Observe that in Siggi's last example, if you change the type argument to `registerFactory` from `ISecureStorage` to `dynamic`, the program runs with no issues.)

`call` usually needs to be handled a bit specially and we've had other `call`-specific issues in the RTI-need computation before. I'll track down the missing code path and put up a fix as soon as I can.

**Comment by sigmundch** [comment]
slight simplification of the repro:
```dart
abstract class B {
  call<T>();
}

class C implements B {
  call<T>() => print(T);
}

abstract class A {}

class Wrapper {
  Wrapper(this.b);
  final B b;
}

void main() {
  B b = C();
  b<A>();             // prints A
  Wrapper(b).b<A>();  // should print A, but prints dynamic
}

```

**Comment by sigmundch** [comment]
ironically, changing the last line to:
```dart
  (Wrapper(b).b)<A>(); // prints A;
```
does work. So there may be something here that relates to how the call itself is represented by the CFE lowering.

**Comment by fishythefish** [comment]
@johnniwinther It seems that `Dart2jsTarget.supportsExplicitGetterCalls` (added [here](https://dart-review.googlesource.com/c/sdk/+/129702)) is affecting the CFE lowering in this case. Changing it to `true` fixes the issue. There's a `TODO` saying that we need to fix JS-interop before we can make this change: https://github.com/dart-lang/sdk/blob/f15518dffc2c6df7ee43ad2a00a963cb8ce69cff/pkg/compiler/lib/src/kernel/dart2js_target.dart#L88-L91

In the meantime, is there a way we can get the explicit `call` in non-interop cases?

**Comment by johnniwinther** [comment]
I'll look into it.

**Comment by johnniwinther** [comment]
The problem is with the rti optimization. The generated AST _does_ include the type argument and when I run with ` --disable-rti-optimization` it works.

**Comment by sigmundch** [comment]
@johnniwinther - yes, however we noticed is that the RTI optimization bug is only triggered because we can't enable the CFE lowering of explicit getter calls. If we did, the problem also goes away. @fishythefish was wondering if there is a way to selectively enable the lowering, so we only have it disabled in parts of the program where JS-interop is involved. Do you think that could be possible?

@lucaspal - @johnniwinther was referring to an internal flag of the dart2js compiler. Unfortunately, if you are running into this from flutter, currently there isn't a way to disable this optimization from their command-line APIs. We are having conversations to see if that can be made easier going forward (like in https://github.com/flutter/flutter/issues/99015)

**Comment by fishythefish** [comment]
@lucaspal That's a flag that can be passed to dart2js and is included in `-O0`. If you're invoking dart2js via Flutter, that flag might not be exposed.

@johnniwinther We know this works with `--disable-rti-optimization` since the trivial RTI need will just put type arguments on everything. Enabling `supportsExplicitGetterCalls` also fixes the issue since it changes the CFE lowering of `call` to something that is handled correctly. (The CFE does emit the type argument in both cases, but the `call` invocation is represented differently.) What I'm wondering is if it's possible to partially enable the new lowering rather than chase down an RTI-need bug to handle a lowering that will go away soon.

**Comment by johnniwinther** [comment]
Looking a bit further into this, I found that it is not the rti need data that is wrong but the way we query it in the ssa builder. The `InstanceGetterInvocation` is (implicitly) a `.call` invocation, but the selector used to query whether the target needed rti used the target (getter/field) name instead.

I have a fix in progress here: https://dart-review.googlesource.com/c/sdk/+/234288
