### ISSUE TITLE
[Enhanced enums] No error in analyzer when enum mixes in mixin on Object with instance variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48302]
The following code produces an error in CFE and no issues in analyzer
```dart
mixin M1 on Object {
  final int i1 = 1;
  int mixedInMethod1(int v) => v;
}

enum E with M1 { // CFE error: A constant constructor can't call a non-constant super constructor.
  e1,
  e2,
  e3;
}

main() {
  print(E.e1);
}
```

Tested on `Dart SDK version: 2.17.0-69.0.dev (dev) (Fri Jan 28 00:44:27 2022 -0800) on "windows_x64"`

cc @eernstg to confirm that it is an analyzer issue

**Comment by sgrekhov** [comment]
An edge SDK version has no this issue. Analyzer correctly reports `COMPILE_TIME_ERROR.ENUM_MIXIN_WITH_INSTANCE_VARIABLE`.

**Comment by eernstg** [comment]
We have the [following](https://github.com/dart-lang/language/blob/2b2d58b0910a913ee5d494e489f4970e9c70a959/specification/dartLangSpec.tex#L5631), about `const`ness of the implicitly induced constructors in a mixin application:

> If $S_q$ is a generative const constructor, and $C$ does not declare any
> instance variables, $C_q$ is also a const constructor.

So a mixin application with an instance variable declaration, no matter which kind, gets no constant constructors. This matches the CFE error message, and the analyzer should report the same thing.
