### ISSUE TITLE
[CP] Please cherry pick change e4942db83e2ad147de8710c0c96629f676fc91e3 (Avoid speculative conversion in ffi Pointer.asTypedList)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#48301]
**commit(s) to merge**: e4942db83e2ad147de8710c0c96629f676fc91e3

**merge instructions**: clean merge

**What is the issue**: Flutter AOT precompiler crash using isar package

**What is the fix**: This change fixes the type incompatibility by loading value with LoadUntagged and then converting it with ConvertUntaggedToUnboxed(kUnboxedIntPtr)

**Why cherrypick**: The issue was reported by Flutter user and it manifests as a crash in the AOT compiler when building a flutter app

**Risk**: low (has rolled into top of tree Flutter without any issues).

**Link to original  issue(s)**: https://github.com/flutter/flutter/issues/97301

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by a-siva** [comment]
//cc @alexmarkov

**Comment by devoncarew** [comment]
Marking as cherry pick approved

**Comment by athomas** [comment]
This needs to into both beta 2.17 and stable 2.16.1

**Comment by athomas** [comment]
Merged to beta in fa166c29f0407be21acebb394d194a38c00593cb (`2.17.0-69.2`).
