### ISSUE TITLE
Update the version of Firefox used for dart2js tests

### ISSUE THREAD

**Issue by filmil** [dart-lang/sdk#48318]
Heya folks.

When able, do update the [version of Firefox used][1] for `dart2js` tests.  The version currently in use (67) is apparently too old to allow the [ICU library][2] to be updated to the latest ICU 70.1. If an upgrade is attempted, errors that can be seen in the comments to [this review][3] appear.

In [that review][3], I found by bisection that the errors go away if using at least Firefox version 72.  We'd probably do good to update to a much newer version of Firefox, say the current one (94).

This bug blocks https://github.com/dart-lang/sdk/issues/48246

[1]: https://github.com/dart-lang/sdk/blob/main/DEPS#L189 
[2]: https://github.com/dart-lang/sdk/blob/main/DEPS#L290
[3]: https://dart-review.googlesource.com/c/sdk/+/230640

**Comment by filmil** [comment]
@mkustermann @kaushikiska

**Comment by mkustermann** [comment]
> In [that review](https://dart-review.googlesource.com/c/sdk/+/230640), I found by bisection that the errors go away if using at least Firefox version 72.

@filmil The failures happen on VM builders, e.g. `vm-kernel-nnbd-linux-release-x64-try`. More specifically, the tests
```
corelib/regexp/unicode-property-binary_test RuntimeError (expected Pass)
corelib_2/regexp/unicode-property-binary_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-release-x64
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

Since these are VM failures, I'm not sure how updating the version of Firefox could help here.

/cc @athomas from dart-infra for the question of updating Firefox.

**Comment by filmil** [comment]
@mkustermann Drilling down to the specific failing tests, I find that the failing ones are all called `dart2js-linux-firefox` across these different configurations - as far as I was able to tell. 

See here for example, thought I think you can find analogous failures in all the failed builders too: https://dart-ci.firebaseapp.com/current_results/#/filter=corelib_2/regexp/unicode-property-binary_test&showAll

HTH, but I have to admit I didn't dig into *why* this is failing, rather just under which conditions this fails.  Better approaches and ideas are most welcome.

**Comment by mkustermann** [comment]
Ah, I see - you are looking at current results for that test. Indeed, the firefox configuration is failing this test already at `origin/master` (the link you are looking at is for `current results` - i.e. for committed code).

Though the CL that rolls ICU causes different failures that are VM-specific and seem unrelated to firefox (e.g. [this failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8823246502691086753/+/u/test_results/new_test_failures__logs_))

**Comment by filmil** [comment]
> Ah, I see - you are looking at current results for that test. Indeed, the firefox configuration is failing this test already at `origin/master` (the link you are looking at is for `current results` - i.e. for committed code).

Ah those are preexisting errors.  Well, in that case, it seems that those go away if Firefox is updated.

> Though the CL that rolls ICU causes different failures that are VM-specific and seem unrelated to firefox (e.g. [this failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8823246502691086753/+/u/test_results/new_test_failures__logs_))

Noted.  The error there is pretty much the same as in the preexisting case:

```
/===========================================================================================\
| corelib_2/regexp/unicode-property-binary_test broke (Pass -> RuntimeError, expected Pass) |
\===========================================================================================/

--- Command "vm" (took 01.000594s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart -Dtest_runner.configuration=dartk-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/corelib_2/regexp/unicode-property-binary_test.dart

exit code:
255

stderr:
Unhandled exception:
FormatException: Invalid property name\p{Emoji}
#0      new _RegExp (dart:core-patch/regexp_patch.dart:218:27)
#1      new RegExp (dart:core-patch/regexp_patch.dart:27:15)
#2      main (file:///b/s/w/ir/tests/corelib_2/regexp/unicode-property-binary_test.dart:105:5)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

--- Re-run this test:
python3 tools/test.py -n dartk-linux-release-x64 corelib_2/regexp/unicode-property-binary_test
```

The property name `\p{Emoji}` is [well documented as supported in the ICU][1], and has been for quite a while.   It not being recognized seems to be pointing at the inability to load the unicode data.

[1]: https://unicode.org/reports/tr51/#def_emoji_character

**Comment by filmil** [comment]
Now looking.  It seems that `ParsePropertyClassName` is failing for `Emoji` for some reason:
https://cs.opensource.google/dart/sdk/+/master:runtime/vm/regexp_parser.cc;l=1626?q=%22Invalid%20property%20name%22&ss=dart%2Fsdk

**Comment by filmil** [comment]
Digging a bit, I found that the error code in this line is 4 (`U_FILE_ACCESS_ERROR`): https://chromium.googlesource.com/external/github.com/dart-lang/sdk/+/refs/heads/master/runtime/vm/regexp_parser.cc#1509

So, as I was suspecting, the ICU code has issues accessing the ICU data files.  At the moment unclear why, though.

**Comment by filmil** [comment]
@kpozin FYI

**Comment by filmil** [comment]
To wit, making a symlink:

```
ln -s $PWD/out/ReleaseX64/icudtl.dat $PWD/out/ReleaseX64/icudt70l.dat
```

and then building and running like so, makes the test pass:

```
./tools/build.py --goma -mrelease --os=linux --arch=x64 && env ICU_DATA=$PWD/out/ReleaseX64 python3 tools/test.py -n dartk-linux-release-x64 corelib_2/regexp/unicode-property-binary_test
```

**Comment by filmil** [comment]
This change introduced the break: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3268349
At the moment, unsure how exactly.

**Comment by filmil** [comment]
After some digging and comparing, it seems that the emoji properties have been offloaded into the ICU data file between ICU 69.1 and ICU 70.1. This leads to the emoji properties `\p{Emoji}` not being found.

See for reference: https://github.com/unicode-org/icu/commit/f9beb616a8a51d73c93cd7add6775ed0ae069bb1

Will check why this seems to be the case.

**Comment by mkustermann** [comment]
@filmil Great investigation work!

Right now the `dart` binary is self-contained. The Dart SDK we build and ship to users doesn't have that `icudt.dat` file in it - it only happens to be available in the build folder (for some reason).

Would it be feasible to include the parts of that file that are needed into the `dart` binary somehow?

/cc @mraleph fyi I remember there was talk about binary size and sharing of ICU across dart / flutter / android.

**Comment by whesse** [comment]
Firefox is updated to 98.0.2 on Linux and Windows.  There is no Firefox uploaded for MacOS.
