### ISSUE TITLE
Customer-reported issue with NNBD migration tool - remember selection.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#48314]
I am doing iterative migration of a large application, so I need to work with a small subset of all files.
After clicking 'Rerun from sources' or 'Rerun with Changes' the tool reset the selection and I have to search for my files again.

Can the tool remember my selection?
Also a button 'Deselect All' would be very helpful.

**Comment by scheglov** [comment]
@stereotype441 @srawlins

**Comment by polina-c** [comment]
CC @leafpetersen

**Comment by stereotype441** [comment]
> As an interim workaround, I think there might be a way to specify a set of files on the command line - do I remember correctly? @stereotype441 @srawlins ?

Unfortunately I think that feature only exists in the google3 version of the tool ☹️

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
