### ISSUE TITLE
Improve the use of conditional imports / exports for non-package projects

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#48320]
When writing a Flutter app that requires supporting web and I/O, conditional imports are required.

Writing conditional imports is explained in the [Creating Packages](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files) documentation.

This documentation specifically talks about _packages_. Not about a user-facing app. (i.e. `flutter create myapp`)

When writing some code that depends on a conditional import/export, using the approach as described in the docs does not work for regular apps.

### Example:

Assuming the following files:
```
- main.dart
- lib/service/
    - io_service.dart
    - service.dart
    - web_service.dart 
```

main.dart
```
import 'package:myapp/service/service.dart';

void main(){
  final service = Service();

  print(service.sayHello());
}
```

service.dart
```
export './stub.dart'
    if (dart.library.io) './io_service.dart'
    if (dart.library.html) './web_service.dart';

class Service {
  const Service();

  String sayHello()=> throw UnimplementedError("This is a stub.");
}
```

stub.dart
```
import 'package:myapp/service/service.dart';

class StubService extends Service {
  StubService(): super();
}
```

io_service.dart
```
import 'package:myapp/service/service.dart';

class IoService extends Service {
  const IoService(): super();

  @override
  String sayHello() {
    return "Hello from I/O service";
  }
}
```

web_service.dart
```
import 'package:myapp/service/service.dart';

class WebService extends Service {
  const WebService(): super();

  @override
  String sayHello() {
    return "Hello from web service";
  }
}
```

Running this with `flutter run -d chrome` makes the app crash, because the `StubService` is used instead of the `WebService`.

I also have some other observations:
- It does work with a totally different approach:
    - using conditional imports instead of exports
    - the stub is a top-level method (i.e. `Service getService() => throw UnimplementedError('This is a stub.');`)
    - implementations define the same top-level method but with a different implementation 
    - the interface is an abstract class with a `factory` constructor that delegates to the top-level method
This workaround isn't the best, as mistyping the top-level method can break things (I had it happen once)

- It would be nice if the interface itself could be used as the stub, this saves an additional file / class.

**Comment by srawlins** [comment]
A specific question like this is best asked on a forum such as StackOverflow, where there is a higher level of experts answering questions.

That being said, your project described about does not use the unconditional imports system as described in the docs. In `main.dart`, you instantiate a `Service` object, so you get the `Service.sayHello` implementation.

> It would be nice if the interface itself could be used as the stub, this saves an additional file / class.

This might be an interesting feature. You could file a request at the language repo: https://github.com/dart-lang/language/issues
