### ISSUE TITLE
No release date for 2.16.0 in changelog

### ISSUE THREAD

**Issue by sebe** [dart-lang/sdk#48328]
Hi @mit-mit and @athomas,
Dart changelog entry for 2.16.0 is missing release date.
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#2160

Also no entry in https://dart.dev/guides/whats-new

Thanks

**Comment by athomas** [comment]
Thanks, https://dart-review.googlesource.com/c/sdk/+/231942 will add it.

**Comment by parlough** [comment]
As for the What's New article, that is about changes to the website, not the SDK, but I've submitted an update here: https://github.com/dart-lang/site-www/pull/3820
