### ISSUE TITLE
Program in loop on using 'dart:isolate'

### ISSUE THREAD

**Issue by leandroveronezi** [dart-lang/sdk#48326]
I have a problem using 'dart:isolate'.
My code works in development but when running the compiled code the program enters a loop.

Dart work
dart test.dart 

Dart not work!
dart compile exe ./test.dart -o test
./test

dart --version
Dart SDK version: 2.16.0 (stable) (Mon Jan 31 15:28:59 2022 +0100) on "linux_x64"

```
import 'dart:async';
import 'dart:isolate';

void main() async {
  //delay
  print('start');
  await new Future.delayed(new Duration(seconds: 1));

  final name = 'Eval Knievel';
  final uri = Uri.dataFromString(
    '''
    import "dart:isolate";

    void main(_, SendPort port) {
      port.send("Nice to meet you, $name!");
    }
    ''',
    mimeType: 'application/dart',
  );

  final port = ReceivePort();
  await Isolate.spawnUri(uri, [], port.sendPort);

  final String? response = await (port.first as FutureOr<dynamic>);
  print(response);
}

```

**Comment by mraleph** [comment]
Note that while the current behaviour is incorrect, the correct behaviour would be to throw. 

AOT runtime does not contain any compilation components so you can't spawn isolates from Dart source. 

/cc @mkustermann @aam

**Comment by mkustermann** [comment]
There was also a bug where it accidentally always spawned the new isolate from same source the main isolate (and ignored the `<uri>` in `Isolate.spawnUri(<uri>,. ..)`.

Made [cl/232603](https://dart-review.googlesource.com/c/sdk/+/232603) that cleans this up.

After that CL lands, you'll be able to `Isolate.spawnUri(<uri>)`  but the `<uri>` has to point to a AOT compiled snapshot (i.e. a file created by `dart compile aot-snapshot <file.dart>`). Any other `<uri>` - being it a `data:...` uri, a `...dart` file / ... will result in an `IsolateSpawnException`.
