### ISSUE TITLE
Dart_IsNull_DL missing

### ISSUE THREAD

**Issue by nielsenko** [dart-lang/sdk#48331]
When converting a `Dart_WeakPersistentHandle` to a `Dart_Handle` with `Dart_HandleFromWeakPersistent_DL`  you get back dart null, if the object has been GC'ed. From the docs:

> Allocates a handle in the current scope from a weak persistent handle.
>
> This will be a handle to Dart_Null if the object has been garbage collected.

However, I need the `Dart_IsNull` to be exposed in the `_DL` api to actually recognise this situation.

I can of course track this "manually" by setting some flag in the finalizer callback, but that seems a bit silly.

**Comment by a-siva** [comment]
//cc @dcharkes

**Comment by nielsenko** [comment]
Have you considered this?

**Comment by dcharkes** [comment]
Adding `Dart_IsNull_DL` is fine I believe.

Here's my original reasoning.

> We re-expose things that are required for FFI use cases: Ports, Handles, Scopes, and Errors.
>
> We can re-expose things that enable interacting with a running Dart VM, enabling mixing and matching the FFI with dart_api: Objects, Instances, Numbers, Booleans, Strings, Lists, Maps, TypedData, Invoke, Exception, and even Native Fields and Functions.
>
> We can re-expose: Things like notify idle and notify low memory, which might be useful when doing many native things. However, they might interfere with how Flutter uses them.
>
> We do not re-expose: For which we have delegated ownership to embedders. Starting and stopping isolates, compiling and loading code, etc.

> Objects: all 27 functions
> Instances: all 8 functions
> Numbers: all 11 functions
> Booleans: all 4 functions
> Strings: all 13 functions
> Lists: all 10 functions
> Maps: all 3 functions
> TypedData: all 9 functions
> Invoke: all functions
> Exception: all functions
> 
> -- This is the normal dart_api interaction with a running Dart VM, if we want to enable full mixing and matching of the ffi with the dart_api, we should expose these.

Adding `Dart_IsNull_DL` would fit in that line of reasoning.

cc @mkustermann @mraleph any concerns?

**Comment by blagoev** [comment]
I suppose, either `Dart_IsNull_DL` should be exposed or the return type of `Dart_HandleFromWeakPersistent_DL` and similar APIs should be changed. Either of these can work.

**Comment by mraleph** [comment]
No concerns on my side, we should go ahead and add it to unblock @blagoev & @nielsenko (alternatively you should feel free to submit the PR).

**Comment by blagoev** [comment]
@mraleph I was thinking about doing that. Let me try :)

**Comment by dcharkes** [comment]
> @mraleph I was thinking about doing that. Let me try :)

Thanks! Please tag me on the PR, I'll review 👍

**Comment by dcharkes** [comment]
@blagoev please note to in crease the minor version in

* runtime/include/dart_version.h and 
* tests/ffi/vmspecific_handle_dynamically_linked_test.dart
* tests/ffi_2/vmspecific_handle_dynamically_linked_test.dart
  * You can add a `DynamicLibrary.executable()` lookup test with `Dart_IsNull_DL` in these last two files as well.

**Comment by blagoev** [comment]
@dcharkes I had that version in my mind already. But thanks for pointing the exact places. This will help.
