### ISSUE TITLE
pkg/vm_snapshot_analysis/test/instruction_sizes_test failing

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48339]
There are new test failures on [[vm/compiler] Allow WB elimination for small arrays.](https://github.com/dart-lang/sdk/commit/72eb59f32af1bc9e74c1e3fe1190214dbf4aaef0).

The tests
```
pkg/vm_snapshot_analysis/test/instruction_sizes_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac
unittest-asserts-release-mac-arm64
```

```
  Expected: {
              'package:input': {
                '#type': 'package',
                'package:input/input.dart': {
                  '#type': 'library',
                  '::': {
                    '#type': 'class',
                    'makeSomeClosures': {
                      '#type': 'function',
                      '#size': <a value less than <0>>,
                      '<anonymous closure>': {'#type': 'function', '#size': <a value less than <0>>}
                    }
                  }
                }
              }
            }
    Actual: {
              'package:input': {
                'package:input/input.dart': {
                  '::': {
                    'makeSomeClosures': {
                      '<anonymous closure>': {'#size': -345, '#type': 'function'},
                      '#type': 'function'
                    },
                    '#type': 'class'
                  },
                  '#type': 'library'
                },
                '#type': 'package'
              }
            }
     Which: at location ['package:input']['package:input/input.dart']['::']['makeSomeClosures'] is {
              '<anonymous closure>': {'#size': -345, '#type': 'function'},
              '#type': 'function'
            } which has different length and is missing map key '#size'
```

[logs](https://dart-ci.appspot.com/log/pkg-mac-release/unittest-asserts-release-mac/20396/pkg/vm_snapshot_analysis/test/instruction_sizes_test)

**Comment by dcharkes** [comment]
The tests
```
pkg/vm_snapshot_analysis/test/instruction_sizes_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-linux
```

This time on linux.

This test is failing, and flaking between timeout and failure.

[test history](https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=pkg/vm_snapshot_analysis/test/instruction_sizes_test&configurations=unittest-asserts-release-linux).

[log](https://dart-ci.appspot.com/log/pkg-linux-release/unittest-asserts-release-linux/18894/pkg/vm_snapshot_analysis/test/instruction_sizes_test).

**Comment by a-siva** [comment]
Saw another case of this on Windows, see [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8805576014656415489/+/u/test_results/new_test_failures__logs_ )

**Comment by dcharkes** [comment]
Another case on Windows, see [log](https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/22493/pkg/vm_snapshot_analysis/test/instruction_sizes_test).

**Comment by aam** [comment]
This failure
```
00:39 [32m+2[0m[31m -1[0m: instruction-sizes basic-parsing [1m[31m[E][0m[0m

  Expected: true
    Actual: <false>
  All symbols should have unique names (within libraries): [Optimized] _awaitCompletedFuture@4048458.run
``` 

seems to be caused by https://github.com/dart-lang/sdk/blob/main/runtime/vm/object.cc#L10071 which doesn't account for the case of ambiguous _named_ closures, which do happen to exist: https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/vm/lib/async_patch.dart#L230 and https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/vm/lib/async_patch.dart#L248

**Comment by aam** [comment]
This failure ```  Expected: contains 'tornOff{body}'
    Actual: {
              '[tear-off] tornOff': ProgramInfoNode:function package:input/input.dart::C.[tear-off] tornOff,
              'tornOff': ProgramInfoNode:function package:input/input.dart::C.tornOff
            }
  ``` has started with https://dart-review.googlesource.com/c/sdk/+/251300 which removed "{body}"-suffixed names.
