### ISSUE TITLE
pkg/dds/test/sse_smoke_test flaky on mac due to ChromeDriver version

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48341]
There are new test failures on [Report DUPLICATE_DEFINITION for 'values' in enums.](https://github.com/dart-lang/sdk/commit/6bcc451e597867cb7c0b4f21d9143d0a43cbb401).

The tests
```
pkg/dds/test/sse_smoke_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac
```

Based on the [history](https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=pkg/dds/test/sse_smoke_test&configurations=unittest-asserts-release-mac) it seems to have started flaking more since February 3rd, 2022.

Most recent [logs](https://dart-ci.appspot.com/log/pkg-mac-release/unittest-asserts-release-mac/20410/pkg/dds/test/sse_smoke_test)

```
  SessionNotCreatedException (500): session not created: This version of ChromeDriver only supports Chrome version 91
  Current browser version is 97.0.4692.99 with binary path /opt/s/w/ir/cache/builder/sdk/third_party/browsers/chrome/Google Chrome.app/Contents/MacOS/Google Chrome
```

@athomas @whesse Did we upgrade our chrome versions on the bot?
@bkonyi FYI

**Comment by alexmarkov** [comment]
This error happens from time to time for a long time. Duplicate to https://github.com/dart-lang/sdk/issues/43743.

**Comment by sstrickl** [comment]
[Popped up again](https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-mac-release/20427/overview), approving.
