### ISSUE TITLE
new co19/LanguageFeatures/FinalizationRegistry/WeakReference/weak_reference_target_t05 fails after co19 roll

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#48358]
From dartk-weak-asserts-linux-release-x64's [logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8822688706315720161/+/u/test_results/new_test_failures__logs_)

```

/=====================================================================================================================================================================\
| dartk-weak-asserts-linux-release-x64:co19/LanguageFeatures/FinalizationRegistry/WeakReference/weak_reference_target_t05 broke (Pass -> RuntimeError, expected Pass) |
\=====================================================================================================================================================================/

--- Command "vm" (took 02.000690s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --enable_asserts --no-sound-null-safety -Dtest_runner.configuration=dartk-weak-asserts-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/LanguageFeatures/FinalizationRegistry/WeakReference/weak_reference_target_t05.dart

exit code:
255

stdout:
unittest-suite-wait-for-done
unittest-suite-success

stderr:
Unhandled exception:
Expect.isNotNull(actual: <null>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.isNotNull (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:45:7)
#2      main (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/FinalizationRegistry/WeakReference/weak_reference_target_t05.dart:47:10)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-weak-asserts-linux-release-x64 co19/LanguageFeatures/FinalizationRegistry/WeakReference/weak_reference_target_t05
```

cc @athomas @sgrekhov

**Comment by sgrekhov** [comment]
@aam I believe this is already fixed. This test (and the `weak_reference_target_t06` as well) checks that `WeakReference` is not cleared by GC if there is a strong reference to the Object in another thread. And then it checks that it does cleared by GC after another thread died. But delays were too small therefore the test was racy. Delays were increased in https://github.com/dart-lang/co19/commit/d7b76bda637e69ce1bbe62270e28b4de48c58e50. So simply wait for the next roll and then retest

**Comment by askeksa-google** [comment]
Approved failures. Logs [here](https://dart-ci.appspot.com/log/vm-kernel-nnbd-mac-release-x64/dartk-strong-mac-release-x64/460/co19/LanguageFeatures/FinalizationRegistry/WeakReference/weak_reference_target_t05) and [here](https://dart-ci.appspot.com/log/vm-kernel-nnbd-mac-release-x64/dartk-weak-asserts-mac-release-x64/460/co19/LanguageFeatures/FinalizationRegistry/WeakReference/weak_reference_target_t05).

**Comment by alexmarkov** [comment]
`co19/LanguageFeatures/FinalizationRegistry/ffi/WeakReference/weak_reference_target_t05` is now passing on all VM configurations.
