### ISSUE TITLE
[Enhanced enums] No error in CFE when `Enum` subtype overrides `index`

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48353]
The following [co19 test](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t03.dart) fails in CFE now
```dart
abstract class E1 extends Enum {
  int get index => 42; // No expected error here in CFE
//        ^^^^^
// [analyzer] unspecified
// [cfe] unspecified
}

abstract class E2 extends Enum {
  List<E2> get index => [];
//             ^^^^^
// [analyzer] unspecified
// [cfe] unspecified
}

main() {
  print(E1);
  print(E2);
}
```
According to the [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/enhanced-enums/feature-specification.md#implementing-enum-and-enum-types) 

> It's a compile-time error if a class, mixin or enum declaration has Enum as a superinterface, and it declares a non-abstract instance member named index. That member would override the index getter inherited from Enum, and we currently do not allow that.

So there should be an error.

Tested on `Dart SDK version: 2.17.0-edge.21a5f734562eb0d2fca0f9b5b646632fbcdb04cb (be) (Wed Feb 9 02:28:41 2022 +0000) on "linux_x64"`

UPD There is no expected error in CFE on the enum as well
```dart
enum E1 {
  e1,
  e2;

  final int index = 42; // No expected error on CFE
//          ^^^^^
// [analyzer] unspecified
// [cfe] unspecified
}
```

**Comment by chloestefantsova** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/237580.
