### ISSUE TITLE
dart2js removes method call with potential side effects in compiled javascript

### ISSUE THREAD

**Issue by schultek** [dart-lang/sdk#48383]
I have come across an issue where the dart2js compiler completely removes an important method call from the output js.

This happens with dart2js on **all** optimization levels (even 0) but not with dartdevc.
```shell
dart --version
Dart SDK version: 2.16.0 (stable) (Mon Jan 31 15:28:59 2022 +0100) on "macos_x64"
```

This can be reproduced with the following code:

```dart
void main() {
  load();
  load(cond: true);
}

/// we have two optional booleans
/// cond can be both true and false
/// use will always be false
dynamic load({bool cond = false, bool use = false}) {
  print("start of load()");
  int? data;
  if (cond) {
    data = callWithSideEffects();
  }
  return [if (use && cond) data];
}

int callWithSideEffects() {
  print("SIDE EFFECT");
  return 2;
}
```

Running `dart2js main.dart -O0` results in the following output (only relevant part shown)

```js
main() {
  A.load(false);
  A.load(true);
},
load(cond) {
  var t1;
  A.print("start of load()");
  cond;
  t1 = A._setArrayType([], type$.JSArray_nullable_int);
  return t1;
}
```

We see that the full `if` statement with the method call is stripped and only a simple `cond` remains.

For the last line in `load()` the array will always be empty because `use` is always `false`. This is correctly compiled since `use` does not exist and an empty array is returned.

I think what is going on is that the compiler thinks that therefore `data` is never used and that it can be removed, together with all assignments to it - including the method call with side effects.

From my testing it appears that the crutial part is the `use && cond` with the list for some reason. It will correctly compile if:

- the last line is `return [if (use) data];`
- the last line is `if (use && cond) return data;`
- the last line is `return use ? [data] : [];`

It will however wrongly compile if:

- the last line is `return use && cond ? [data] : [];`

**Comment by rakudrama** [comment]
Thanks for the detailed report, it was helpful in understanding the root cause.
This fix will probably land in a few days: https://dart-review.googlesource.com/c/sdk/+/232781
