### ISSUE TITLE
Socket tcpNoDelay still buffers packets

### ISSUE THREAD

**Issue by zim32** [dart-lang/sdk#48386]
So I see strange behaviour in dart Socket. I create a socket and set :

socket.setOption(SocketOption.tcpNoDelay, true);

It returns true, so everything is fine

Then I call listen() and start receving data.
But dart still buffers incoming data. Using wireshark I can see two TCP packets coming with different SEQ number, I can see both packets has been acknowledged, but my dart code sees data from both packets as one concatenated data packet. 

Is this a bug or intended behaviour?

Dart SDK version: 2.16.0 (stable) (Unknown timestamp) on "linux_x64"

**Comment by mraleph** [comment]
Note that `TCP_NODELAY` only affects sending side, not the receiving side. 

> Is this a bug or intended behaviour?

It's an intended behaviour. Dart attempts to read all available data once it knows that there is something to read (we use `epoll` internally). If both packets have arrived by the time Dart starts reading then the data from both packets will be read.
