### ISSUE TITLE
Poor recovery when enum constant with type arguments, dot

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#48380]
```dart
enum E {
  v<int>.;
}
```

or 

```dart
enum E {
  v<int>;
}
```

or 

```dart
enum E {
  v.;
}
```

Can we insert synthetic arguments `()` in these cases?

And make sure that `;` is not lost.

I tried to do it myself, but eventually found `TokenStreamRewriter` and decided that this is too much for me.
This causes wrong completion in enum constants.

**Comment by jensjoha** [comment]
I don't think I understand what the bad thing about the current parsing is.

E.g.

```
enum E {
  v<int>.;
}
```

is parsed as

```
enum E {
  v<int>.*synthetic*;
}
```

which seems fine? (and doesn't appear to throw any semicolon away?)

**Comment by scheglov** [comment]
You are right, the semicolon is not discarded, I was confused.

The main issue is that when an enum constant has type arguments, according to the grammar it also must have value arguments. Looking into the spec now, I don't see it saying this explicitly, although it used to do so. Maybe it was too obvious. But examples in `Enum values:` still show it.

So, could parser insert not only a synthetic identifier after `.`, but also synthetic `()`?

**Comment by scheglov** [comment]
Thank you, this works great!
