### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Couldn't apply migration

### ISSUE THREAD

**Issue by programmingpoint** [dart-lang/sdk#48394]
Couldn't apply migration

Error: Bad state: It looks like this migration has already been applied. Try restarting the migration tool if this is not the case.

Please fill in the following:

**Name of package being migrated (if public)**:
**What I was doing when this issue occurred**:
**Is it possible to work around this issue**:
**Has this issue happened before, and if so, how often**:
**Dart SDK version**: 2.13.4
**Additional details**:

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
#0      PreviewSite.performApply (package:nnbd_migration/src/preview/preview_site.dart:487:7)
#1      PreviewSite.handlePostRequest (package:nnbd_migration/src/preview/preview_site.dart:449:9)
<asynchronous suspension>
#2      HttpPreviewServer._handlePostRequest (package:nnbd_migration/src/preview/http_preview_server.dart:109:5)
<asynchronous suspension>
#3      HttpPreviewServer._handleServer.<anonymous closure> (package:nnbd_migration/src/preview/http_preview_server.dart:119:9)
<asynchronous suspension>

```

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
