### ISSUE TITLE
Stream call onDone method after 30s without data

### ISSUE THREAD

**Issue by xhcoding** [dart-lang/sdk#48392]
example code:

```dart
  
  var request = new http.Request("GET", _makeUri('/v1/events/subscribe/1'));
  request.headers["Cache-Control"] = "no-cache";
  request.headers["Accept"] = "text/event-stream";
  request.headers.addAll(_makeHeaders(const Duration(seconds: 3)));

  var client = http.Client();
  var response = await client.send(request);

  if (response.statusCode != 200) {
    return;
  }

  print("time: ${DateTime.now()}");
  response.stream.listen((value) {
    print("body: $value");
  },
      cancelOnError: true,
      onError: (e) => print("onError: $e"),
      onDone: () => print("onDone: ${DateTime.now()}"));
```

output:
```
time: 2022-02-14 17:41:02.284105
onDone: 2022-02-14 17:41:32.202743
```

When response no data, `onDone` be called after 30s, how to increase this time ?

**Comment by lrhn** [comment]
Maybe the [timeout](https://api.dart.dev/stable/2.16.1/dart-html/HttpRequest/timeout.html) setter will work. Worth a try at least.

**Comment by xhcoding** [comment]
Thanks for you advise.

I use `timeout` like this:
```dart
  print("time: ${DateTime.now()}");
  response.stream.timeout(const Duration(seconds: 29)).listen((value) {
    print("body: $value");
  },
      cancelOnError: true,
      onError: (e) => print("onError: $e"),
      onDone: () => print("onDone: ${DateTime.now()}"));

```
When timeout is 29s , I get TimeoutException output: 
```
time: 2022-02-14 18:57:42.506061
onError: TimeoutException after 0:00:29.000000: No stream event
```

When timeout is 31s,  `onDone` is still called after 30s

```
time: 2022-02-14 18:58:21.623774
onDone: 2022-02-14 18:58:51.530074
```

**Comment by lrhn** [comment]
So, it's not a timeout. 
Are you sure it's not the remote end timing out and closing the connection? (If so, the `onDone` is the correct behavior.)

Try printing the `response.statusCode` and see what it is (and when it arrives).
If the statusCode comes after 30 seconds, and is 408 (request timeout), then it's definitely the server timing out on you.
If it comes early as `400`, then nothing happens for 30 seconds ... then it's not clear who decides to end the connection.

Is this in a browser or is it native code?

**Comment by xhcoding** [comment]
I used Wireshark to capture packets and found that the  server close the connection.

Sorry to bother you!
