### ISSUE TITLE
Split unused_element into two diagnostics?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#48401]
It seems that recent updates to `unused_element` added support for:

```dart
class _Private {
  _Private({
    this.value = 42,
    ^^^^^^^ unused_element
  });

  final int value;
}

void main() {
  print(_Private().value);
}
```

Where `value` is marked as unused because `_Private` is never used with `_Private(value: ...)`.

I personally do not agree with this new feature and would like to disable it in my projects. But I don't want to disable `unused_element` completely since I want to use the other warnings it implements.

Would it be possible to extract this new feature as a separate lint? Such that it can be explicitly disabled in the `analysis_options.yaml` instead of having to use `//ignore:`

**Comment by bwilkerson** [comment]
Just out of curiosity, why do you want to have an optional parameter that is never used left in your code base?

**Comment by srawlins** [comment]
I think the question is very pertinent to the diagnostic. The parameter is unused, and is reported as such.

**Comment by rrousselGit** [comment]
The parameter is here for the sake of the pattern.

The fact that it is unused changes from one day to another. At any time, I could add a new usage of the `_Private` class that suddenly uses the parameter, and the next day remove that new usage.

I don't want to have a back-and-forth of adding/removing the parameter repeatedly while I'm iterating on other parts of the code.  
To begin with, having the parameter is harmless. And the property `value` is indeed used

**Comment by rrousselGit** [comment]
> After you're done iterating on the code, would you then want to know that it's unused?

No, because I don't think code can truly even be considered as "done". 

> True. But so is having any other unused code, except, of course, for the maintenance burden.

I don't think this is similar. An unused parameter on a private class causes no maintenance burden.
Although the lint is technically correct and the parameter is indeed unused, we don't lose anything by leaving it here.

This is quite different from an unused method, which could cause confusion – such as when something within that method does not compile.

___


I'd personally consider the constructor parameter and the property as a single entity. Hence as long as the property is used, I don't mind the parameter not being used.

To begin with, if we were to use data-classes, we'd write:

```dart
data class _Private({final int value = 42});
```

Where this would define both the constructor parameter and the property at the same time. And while the constructor parameter could technically be unused, the lint in this scenario would be incorrect, as without the constructor parameter the property wouldn't exist.

**Comment by bwilkerson** [comment]
Thanks. That perspective is good to have.

**Comment by srawlins** [comment]
> An unused parameter on a private class causes no maintenance burden.
Although the lint is technically correct and the parameter is indeed unused, we don't lose anything by leaving it here.

How is it different from other unused code? I think any example of bloat caused by unused methods or imports or fields, etc can be caused by an unused parameter as well.

The unused parameter might be unexpected ("What? But I do use it, right? Well, we should be using it. Whoops!"). It might bring an additional type whose removal could lead to an unused import. It might have a default value whose removal might raise more dead code.

**Comment by talamaska** [comment]
I've stumbled upon this warning today when upgrading some of my published packages. I don't really understand how the privacy of the class changes the outcome of the lint rule here. I have a parameter that is used inside the widget, it's just that the widget is private and used only in the same file, sure without this optional parameter. But what if at some point I want to use it in the same file with the optional parameter? It doesn't reflect the true meaning of the rule and cause headaches to many people.

**Comment by rrousselGit** [comment]
> How is it different from other unused code? I think any example of bloat caused by unused methods or imports or fields, etc can be caused by an unused parameter as well.

I don't think these are comparable examples.

Unused imports can slow down build_runner for example.   
Unused methods have a high probability of breaking, as the complexity of a method can get very large.

An constructor parameter on the other hand is fairly benign. And adding to that, there are various more helpful unused lints that already cover constructor.

For example:
-  unused properties. If a property is unused, removing it will remove the associated constructor parameter too.
- unused variables.
  If a constructor does:
  ```dart
  MyClass({String? parameter});
  ```
  where the `parameter` is not used (as in not assigned to a property or used in the body), then fixing the lint will also remove the parameter.

So in the end, the primary scenario this lint touches is the initialization of used properties.
In that scenario, the parameter is not harming anyone, and is often there for the sake of convention.
