### ISSUE TITLE
[Enhanced Enums] Enums lose visibility of 'toString' after mixing in a mixin

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#48424]
The following prints:
```
E.v
null
```
But I'd expect:
```
E.v
EM.v
```

Snippet:
```
mixin M on Enum {
  int mixinMethod() => index * 100;
}

enum E {v}
enum EM with M {v}

main() {
  print(E.v.toString());
  print(EM.v.toString());
}
```

Is this intended?
This reproduces on both the VM and DDC, leading me to believe it's on the CFE-side of things.

**Comment by lrhn** [comment]
Definitely not intended.

**Comment by chloestefantsova** [comment]
This is fixed in https://github.com/dart-lang/sdk/commit/ab84be0a888480ff4d05833fbbcfc3d99709968a.
