### ISSUE TITLE
Update CompileTimeErrorCode.IMPLEMENTS_DISALLOWED_CLASS for enhanced_enums

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48437]
The error code `CompileTimeErrorCode.IMPLEMENTS_DISALLOWED_CLASS` is misleading when the class being implemented is `Enum` and the 'enhanced_enums' feature is enabled. For example, this code:

```dart
class C implements Enum {}
```

produces a diagnostic that reads "Classes and mixins can't implement 'Enum'.". It would be more accurate to say that "Concrete classes and mixins can't implement 'Enum'." because under 'enhanced_enums' abstract classes are allowed to implement `Enum`. Of course, the feature doesn't impact other disallowed classes, so the message for them should be unchanged.

**Comment by bwilkerson** [comment]
@scheglov @srawlins

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/233701
