### ISSUE TITLE
AOT compiler on Windows 64 generates buggy code when using Int32List

### ISSUE THREAD

**Issue by LennartKleinwort** [dart-lang/sdk#48436]
I have created a simple wrapper class with one final Int32List attribute and implemented the two array operators:

```
class TypedIntList {
  final Int32List _inner;

  late final int length;
  TypedIntList.wrap(this._inner) {
    length = _inner.length;
  }
  TypedIntList(this.length)
      : _inner = Int32List(length);

  void operator []=(int index, int value) {
    _inner[index] = value;
  }

  @pragma('vm:never-inline') // code crashes randomly without this
  int operator [](int index) {
    return _inner[index];
  }
}
```
This class is used in my machine generated codebase (created by a transpiler) to emulate arrays. The codebase itself is very large and everything runs fine except when using the AOT compiler for Windows 64:

```
dart compile aot-snapshot -o main.aot lib\main.dart
dartaotruntime.exe main.aot
```
When running the AOT generated binary there are random crashes or the code simply runs in an infinite loop. The issue disappears when I annotate my array operator with @pragma('vm:never-inline'). It took several days of testing to find this problem. I created a second List<int> attribute in my TypedIntList class and mirrored every write/read access to check whether List<int> and Int32List stay always equal. And there is never a single difference although returning the value read from the Int32List does not work until the  @pragma('vm:never-inline') annotation is added. So this seems to be a very weird inliner issue in the AOT compiler. The code is running fine on Android and in the Dart VM.

Dart-Version: 2.16.1 (stable)

**Comment by gmpassos** [comment]
Dart version?

**Comment by cubesdev** [comment]
> Dart version?

Dart-Version is 2.16.1 (stable)

**Comment by mraleph** [comment]
Unfortunately we would need considerably more information or a runnable reproduction  to figure this out.

You could dump disassembly of `main.aot` (with and without `@pragma`) with `objdump` and then diff them in attempt to locate the place which was actually affected.
