### ISSUE TITLE
Update CompileTimeErrorCode.NON_ABSTRACT_CLASS_INHERITS_ABSTRACT_MEMBER under enhanced_enums

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48438]
Given the following code:

```dart
abstract class C implements Enum {
  int get values => 0;
}
enum E implements C {
  a
}
```

The analyzer produces two diagnostics at the name of `E`:

```
error: Missing concrete implementation of 'getter C.values'. (non_abstract_class_inherits_abstract_member at [test_package] lib/test.dart:4)
error: An instance member named 'values' can't be inherited from 'C' in a class that implements 'Enum'. (illegal_enum_values_inheritance at [test_package] lib/test.dart:4)
```

The second is valid, but the first should not be reported because it would be wrong for the user to add a concrete implementation of `values`. The code should special case `values` when it's being inherited from a class that implements `Enum`.

Interestingly enough, there are no diagnostics reported if `values` is replaced by `index`. I'm not sure whether this is expected.

**Comment by bwilkerson** [comment]
@scheglov @srawlins

**Comment by scheglov** [comment]
We treat `index` as a concrete field of `class Enum`, which is extended by every enum declaration, so it is implemented.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/233968
