### ISSUE TITLE
Process.start does not close process on ctrl + c

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/sdk#48439]
I'm having an issue with some commands I try to run with `Process.start`, where the started process does not close on CTRL + C.

So far I've had the issue with `firebase` cli, `flutter test` and `flutter drive`. It works fine with simple commands like `sleep`. So I'm not sure if the issue comes from those other program, `dart:io` or how I use `Process.start`.

I've opened an issue https://github.com/flutter/flutter/issues/98395 on flutter repository but now realizing I've this issue with more commands that just flutter's, I think this issue fits here better.

Here is an image of the output I get when trying to exit the process:

![image](https://user-images.githubusercontent.com/22280985/153871750-2d239784-d4e9-4a86-b599-c56ec5d6c247.png)

Here is an example of a command that does not exits with firebase emulator:

```dart
import 'dart:io';

void main(List<String> arguments) async {
  await Process.start(
    'firebase',
    ['emulators:start'],
    mode: ProcessStartMode.inheritStdio,
    runInShell: true,
  );
}
```

It works however when explicitely sending the sigint signal to those processes, but the stdout is a bit sketchy:

```dart
import 'dart:io';

void main(List<String> arguments) async {
  Process? process;
  ProcessSignal.sigint.watch().listen((event) {
    process?.kill(ProcessSignal.sigint);
    exit(1);
  });
  process = await Process.start(
    'firebase',
    ['emulators:start'],
    mode: ProcessStartMode.inheritStdio,
    runInShell: true,
  );
}
```

# Repro

https://github.com/cedvdb/flutter_repros/tree/drive_ctrl_c

 - get the correct branch
 - run android emulator
 - `dart run run_me.dart`

**Comment by jensjoha** [comment]
Funny --- I reported https://github.com/dart-lang/sdk/issues/42918 a while back where I found that a launched process was killed if I ctrl-C'd but not if the launching process throws...
