### ISSUE TITLE
Question about deprecated

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48445]
Should the analyzer produce a hint for the following code:

```dart
class A {
  int get x => 0;
}

class B extends A {
  @deprecated
  @override
  int get x => 0;
}
```

It doesn't seem to make sense to say that an instance member is deprecated if it overrides a member that isn't deprecated. For example, consider:

```dart
void f(A a, B b) {
  a.x; // no hint
  b.x; // use of deprecated member
}
void g(B b) => f(b, b);
```

**Comment by bwilkerson** [comment]
@lrhn @srawlins

**Comment by lrhn** [comment]
The annotation doesn't appear to make a lot of sense by itself. 
Although one *possible* interpretation is that `B` will stop implementing `A` in the future. The documentation should probably say that.

If someone added the annotation, they either meant it, or it's a mistake.
If there is any way it can be deliberate, we shouldn't disallow it.
So, I'd say this is working as intended.

Don't know if a hint might make sense.

**Comment by bwilkerson** [comment]
Given that there's a plausible use case, any check should be opt-in. But until a user actually requests it, I think we can close this.
