### ISSUE TITLE
Discontinue `dartanalyzer`

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#48457]
As part of the transition to the new [unified `dart` developer tool](https://github.com/dart-lang/sdk/issues/46100), we're discontinuing `dartanalyzer` in favor of `dart analyze`. This issue tracks remaining clean-up items needed to fully discontinue `dartanalyzer`:

* [x]  add support for analyzing the Dart SDK libs (currently `--dart-sdk=/Users/foo/src/dart-repo/sdk/sdk`)
   https://github.com/dart-lang/sdk/issues/48959
* [x] Scrub [all occurrences](https://github.com/dart-lang/sdk/search?q=dartanalyzer) of `dartanalyzer` in the SDK
* [x] Remove `bin/dartanalyzer` & `bin/snapshots/dartanalyzer.dart.snapshot` from the SDK
* [ ] Remove [`package:analyzer_cli`](https://github.com/dart-lang/sdk/tree/main/pkg/analyzer_cli) from the SDK
* [x] Add support for running with experiments, either via a private build target for dartanalyzer or by supporting experiment flags in `dart analyze`
   https://github.com/dart-lang/sdk/issues/48960

**Comment by eernstg** [comment]
Could we make it a action item to support `dart analyze --enable-experiment=...` as well, or do we have a plan for how to do that in some other way?

**Comment by mit-mit** [comment]
I think `dart --enable-experiment=... analyze` works already?

**Comment by eernstg** [comment]
That would be great! I currently seem to get the following:

```
> dart --enable-experiment=enhanced-enums analyze n030.dart
Analyzing n030.dart...                 3.4s

  error • n030.dart:2:4 • This requires the 'enhanced-enums' language
          feature to be enabled. Try updating your pubspec.yaml to set the
          minimum SDK constraint to 2.17.0 or higher, and running 'pub get'. •
          experiment_not_enabled

1 issue found.
> dart analyze --enable-experiment=enhanced-enums n030.dart  
Could not find an option named "enable-experiment".

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options.
```

where `dart` is from commit 19c7f85bfe1758d39570feeee3e6aa3ebdc56d90.

**Comment by mit-mit** [comment]
Yes; you need to be on the right language version also, which requires a package config being generated by `pub get`

**Comment by eernstg** [comment]
OK, did that. But we're not at 2.17.0 yet (and this `dart` is from a commit late yesterday afternoon), so following the advice in the emitted message does not seem to work at this point:

```
> dart pub get
Resolving dependencies... 
The current Dart SDK version is 2.17.0-edge.19c7f85bfe1758d39570feeee3e6aa3ebdc56d90.

Because scratch requires SDK version >=2.17.0 <3.0.0, version solving failed.
```

**Comment by mit-mit** [comment]
Try:

```
environment:
  sdk: '>=2.17.0-0 <3.0.0'
```

**Comment by eernstg** [comment]
Still `Try updating your pubspec.yaml to set the minimum SDK constraint to 2.17.0 or higher`.

**Comment by mit-mit** [comment]
Sure, but 1) if you had created your project with `dart create` the pubspec would have had the right constraint, and 2) the message I believe optimizes for the 99%+ fraction of users that use stable releases. In either case, probably better to discuss in a separate issue as that seems entirely orthogonal to the present issue.

**Comment by bkonyi** [comment]
@bwilkerson @srawlins can one of you take ownership of this? Ideally this would be done for 2.17.

**Comment by srawlins** [comment]
No promises on the 2.17 bit 😬 but we can triage this.

**Comment by bkonyi** [comment]
> No promises on the 2.17 bit grimacing but we can triage this.

I had a feeling, but that's not the end of the world. `2.18` should be fine :-)

**Comment by srawlins** [comment]
The necessary flags have been added to `dart analyze`.

**Comment by srawlins** [comment]
I believe the Engprod team is tasked with the SDK test tool's use of `dartanalyzer`.

**Comment by jcollins-g** [comment]
https://dart-review.googlesource.com/c/sdk/+/249662 will take care of removing dartanalyzer and references to it (WIP, I'm currently sending it to bots to try and track down anything I missed).   For removing the package, I'm proposing we mark the package obsolete in pub, alter the README to be a short blurb referencing the removal issue, and stripping the tool of all functionality not needed by the SDK build and test framework.

**Comment by mit-mit** [comment]
Thanks @jcollins-g!

> For removing the package, I'm proposing we mark the package obsolete in pub
This was done a little while ago.

> alter the README to be a short blurb referencing the removal issue
Looks like this already happened; I made a few further tweaks here:
https://dart-review.googlesource.com/c/sdk/+/251763

> and stripping the tool of all functionality not needed by the SDK build and test framework.
Can we file a separate cleanup issue for that?
