### ISSUE TITLE
lib_2/html/audiocontext_test is potentially flaky

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#48452]
There are new test failures on [Breaking analyzer change: always insert ImplicitCallReference nodes.](https://github.com/dart-lang/sdk/commit/f654af1fea114e3bd5bb80371953611fe1805618).

This commit doesn't touch dart2js or any code it uses, so I believe the failure was caused by something else (or possibly the test is flaky).

The tests
```
lib_2/html/audiocontext_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-linux-firefox
```

**Comment by sigmundch** [comment]
Ah, it appears to be FF specific. I see that it's also tracked by https://github.com/dart-lang/sdk/issues/48434, so I'm closing this as a duplicate.
