### ISSUE TITLE
get dart app version number 

### ISSUE THREAD

**Issue by a-eniou-pvotal** [dart-lang/sdk#48462]
I made a dart app for server application but I want to print the app version number on app execute, so I search for getting app version number for dart command-line apps but I couldn’t find any answers, all answers related to flutter apps.

So how to get app version for dart command-line apps?

**Comment by lrhn** [comment]
I'm not sure what the "app version number" is.
Is it the version number of the `pubspec.yaml` file of the project used to build the app?
If so, I do not believe it's automatically included in the resulting program in any automatic way.
