### ISSUE TITLE
Where is the implementation of this JS<T extends Object?>(String typeDescription, String codeTemlate, [arg0, .....])

### ISSUE THREAD

**Issue by tzsh1007** [dart-lang/sdk#48467]
This function 
external T JS<T extends Object?>(String typeDescription, String codeTemplate,
    [arg0,
    arg1,
    arg2,
    arg3,
    arg4,
    arg5,
    arg6,
    arg7,
    arg8,
    arg9,
    arg10,
    arg11,
    arg12,
    arg13,
    arg14,
    arg15,
    arg16,
    arg17,
    arg18,
    arg19]);

is in the ../dart-sdk/lib/_internal/js_dev_runtimes/private/foreign_helper.dart, but I can't found the implementation.

I haven't found from the dart-sdk,  please tell me, thks.

**Comment by lrhn** [comment]
The implementation of this function is provided directly by the web compiler, there is no Dart source code for it.
