### ISSUE TITLE
`DateTime.toIso8601String()` includes microseconds even when 0

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#48470]
The API docs for `toIso8601String()` say:

*  The format is `yyyy-MM-ddTHH:mm:ss.mmmuuuZ` for UTC time
* `uuu` are microseconds in the range 001 to 999. If [microsecond] equals 0, then this part is omitted.

However, microseconds seem to be always included when using UTC time:

```dart

  String toIso8601String() {
...
    String us = microsecond == 0 ? "" : _threeDigits(microsecond);
    if (isUtc) {
      return "$y-$m-${d}T$h:$min:$sec.$ms${us}Z";
    } else {
      return "$y-$m-${d}T$h:$min:$sec.$ms$us";
    }
  }
```

**Comment by Markzipan** [comment]
Do you have a repro for this? Seems to be working as intended on the VM (as well as the highlighted logic).

**Comment by lrhn** [comment]
In the VM, I also see no zero microseconds, whether UTC or not.
The line
```dart
String us = microsecond == 0 ? "" : _threeDigits(microsecond);
```
precisely makes the `us` string empty if microseconds is zero, otherwise it's a three digit string.

On the web, there are no microseconds in a JavaScript `Date` object, so it's always zero, and also never included.

**Comment by mit-mit** [comment]
On macOS 12.2.1:

```dart
main() {
  final timestamp = '2018-03-12T16:49:11Z';
  var timestamp2 = DateTime.parse(timestamp).toIso8601String();
  print('Original: $timestamp, converted: $timestamp2');
}
```

```
mit-macbookpro5:tmp mit$ dart run repro.dart
Original: 2018-03-12T16:49:11Z, converted: 2018-03-12T16:49:11.000Z
```

**Comment by lrhn** [comment]
That looks correct. The milliseconds are included (three "0" digits), but the microseconds are omitted. Otherwise there would be six "0" digits.

**Comment by mit-mit** [comment]
Yes, my bad, I got microseconds and milliseconds confused.
