### ISSUE TITLE
Rename refactor incorrectly renames private symbols in other libraries

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#48474]
```dart
// foo.dart
class A {
  final String _private = '';
}
```

```dart
// bar.dart
import 'foo.dart';

class B implements A {
  final int _private = 1;
}
```

If I do a rename with the analysis server (I'm using LSP but I'd assume it happens either way) in `bar.dart` of `_private`, then the field which happens to have the same name in the class that is implemented is renamed as well. This would make sense if the classes were in the same library, but not across libraries.

**Comment by natebosch** [comment]
The real world situation was a rename of `HtmlWebSocketChannel._webSocket`. It also renamed the field with the same name in `IoWebSocketChannel`

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/308165
