### ISSUE TITLE
Tests failed when mock version of meta was updated

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48476]
The following tests started failing when the analyzer's mock version of `package:meta` was updated to include a `@Target` annotation on `_DoNotStore` and `_OptionalTypeArgs`:

```
AssignmentOfDoNotStoreTest | test_classMemberVariable
AssignmentOfDoNotStoreTest | test_classStaticVariable
AssignmentOfDoNotStoreTest | test_topLevelVariable
AssignmentOfDoNotStoreTest | test_topLevelVariable_assignment_field
AssignmentOfDoNotStoreTest | test_topLevelVariable_assignment_functionExpression
AssignmentOfDoNotStoreTest | test_topLevelVariable_binaryExpression
AssignmentOfDoNotStoreTest | test_topLevelVariable_ternary
InferenceFailureOnFunctionInvocationTest | test_functionType_optionalTypeArgs
ReturnOfDoNotStoreTest | test_returnFromClosureInFunction
ReturnOfDoNotStoreTest | test_returnFromFunction
ReturnOfDoNotStoreTest | test_returnFromGetter
ReturnOfDoNotStoreTest | test_returnFromGetter_binaryExpression
ReturnOfDoNotStoreTest | test_returnFromGetter_ternary
ReturnOfDoNotStoreTest | test_returnFromMethod
ReturnOfDoNotStoreInTestsTest | test_noHintsInTestDir
```

Either the tests need to be updated or the `Target` annotations need to be updated.

**Comment by bwilkerson** [comment]
@pq

**Comment by srawlins** [comment]
`InferenceFailureOnFunctionInvocationTest | test_functionType_optionalTypeArgs` is a test which features `@optionalTypeArgs` on a function-typed parameter, which should be allowed. I guess the `Target` needs to be updated?

**Comment by srawlins** [comment]
Wow, I think I mislabled this. _All_ of the tests backing `@doNotStore` are marked `@FailingTest`. 😮

**Comment by bwilkerson** [comment]
Any progress?

**Comment by pq** [comment]
Ah, sorry. No progress.

**Comment by bwilkerson** [comment]
Any progress? Do we need to adjust the priority?

**Comment by pq** [comment]
No progress. Let me know what you think about priority. If it feels like a real **P1**, I can shift some energy over to take a look.

**Comment by srawlins** [comment]
> All of the tests backing @doNotStore are marked @FailingTest.

I think this is still P1. If you're on other P1s at the moment, I can take this one instead.
