### ISSUE TITLE
HHH bots failure: No module named 'httplib2'

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#48486]
We are noticing that the HHH bots are failing with an error of a missing python module. Not sure what the root cause is, but it appears like possibly an infrastructure issue?

Sample run https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-engine-linux-web_tests/4974/overview
and logs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8820961975918964577/+/u/3xHEAD_Flutter_Hooks/stdout

Error: 
```
ModuleNotFoundError: No module named 'httplib2'
```

We noticed the failure in the 3H-web bot, but the issue appears to also affect the non-web ones.

**Comment by athomas** [comment]
https://dart-review.googlesource.com/c/sdk/+/234721 should fix this.

**Comment by athomas** [comment]
Needs another fix: https://dart-review.googlesource.com/c/recipes/+/234643
