### ISSUE TITLE
Macros can't create unnamed constructors

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#48485]
I am working on integrating the data class example in the language repo with the actual CFE, and I ran into an issue when it tries to generate a constructor, I get the following:

```
Unhandled exception:
Crash when compiling null,
at character offset null:
example/user_main.dart:27:7: Internal problem: Unsupported operation: 'SyntheticSourceConstructorBuilder.applyPatch'.
class User {
      ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      unsupported (package:front_end/src/fasta/problems.dart:85:10)
#2      BuilderImpl.applyPatch (package:front_end/src/fasta/builder/builder.dart:294:5)
```

It looks like the patch mechanism being used to apply the augmentations doesn't allow patching of synthetic constructors.

Can we delay creation of the synthetic constructors until after macros are applied?

**Comment by johnniwinther** [comment]
I'll look into it.

Is it correct that we don't support constructor augmentation? From the proposed grammar changes it doesn't look like you can use the `augment` modifier on constructor declarations.

**Comment by jakemac53** [comment]
We do support augmenting constructors, https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md#augmenting-constructors.

Please file issues if we need to update the grammar etc :).
