### ISSUE TITLE
`Number Theoretic Transform` yielding different results compared to Javascript

### ISSUE THREAD

**Issue by AldrinMathew** [dart-lang/sdk#48483]
- Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "linux_x64"
- Linux

The same implementation of `Number Theoretic Transform` is yielding different results in Dart compared to Javascript for the same input.
I have created a repository containing implementations in both languages [here](https://github.com/AldrinMathew/dart-js-ntt)

All functions in the scripts have been tested and cross checked and only `ntt` and `nttInverse` is yielding different results. I even tested bitshift (left, right and triple) at one point just to be sure.

I have added instructions on how to run the scripts and what to expect in the repository. The scripts will also check the result from the other language and report the different results. As of now, it is safe to assume that the JS implementation yields the correct results as it is used in another cryptographic algorithm which passes the tests.

**Comment by rakudrama** [comment]
Have you identified where the intermediate values diverge? What is the first intermediate result that is different?

One thing that stands out to me is that both programs use `%`.
[`a % b` in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder) is 'remainder' and corresponds to [`a.remainder(b)` in Dart](https://api.dart.dev/stable/2.14.3/dart-core/num/remainder.html).
[`a % b` in Dart](https://api.dart.dev/stable/2.14.3/dart-core/num/operator_modulo.html) is the Euclidean modulo operation, which is different to remainder when an operand is negative.

**Comment by AldrinMathew** [comment]
@rakudrama 
That's it!! The `%` operator is only used in integer bitwidth conversion functions like `int16` and `int32`, and those were all tested independently with inputs from `0` to `1000000`, so that was the problem.
Thanks a lot. I spend 3 days writing tests around 2K loc to test all functions and classes in the package. The entire package was complete days ago, but couldn't publish it without solving this. I have a background in mathematics and can't comprehend how I forgot about this.
