### ISSUE TITLE
Add a fix for CompileTimeErrorCode.SUPER_FORMAL_PARAMETER_WITHOUT_ASSOCIATED_NAMED

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48480]
The diagnostic `CompileTimeErrorCode.SUPER_FORMAL_PARAMETER_WITHOUT_ASSOCIATED_NAMED` should have a fix that would replace the name with a similar name from the super constructor. This would be conditional on there being one or more similar enough names.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/245360

**Comment by asashour** [comment]
Kind reminder for review, thanks.
