### ISSUE TITLE
Add a fix for CompileTimeErrorCode.UNDEFINED_ENUM_CONSTRUCTOR

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48481]
The diagnostics `CompileTimeErrorCode.UNDEFINED_ENUM_CONSTRUCTOR_NAMED` and `CompileTimeErrorCode.UNDEFINED_ENUM_CONSTRUCTOR_UNNAMED` should have the `CreateConstructor` fix associated with them (after verifying that it works correctly in those cases).

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/245169
