### ISSUE TITLE
dart lang math not right , 7*1.15 = 8.049999999999999?

### ISSUE THREAD

**Issue by cnmade** [dart-lang/sdk#48494]
I confirm this on MacOS and even on DartPad

and i also tried the calc under cli

```

nomore@appledeMac-mini ~/tmp $ dart main.dart
8.049999999999999
nomore@appledeMac-mini ~/tmp $ cat main.dart
void main() {
    double i = 7 * 1.15;
    print(i);

}
nomore@appledeMac-mini ~/tmp $ dart --version
Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"

```

**Comment by cnmade** [comment]
I tried golang, look good

```golang
nomore@appledeMac-mini ~/tmp $ go run main.go
8.05
nomore@appledeMac-mini ~/tmp $ cat main.go
package main

import "fmt"
func main() {
   x := 7  * 1.15
   fmt.Println(x)
}
nomore@appledeMac-mini ~/tmp $ go version
go version go1.17.5 darwin/amd64
```

**Comment by mraleph** [comment]
That's how floating point numbers work. Please read something like: https://floating-point-gui.de/

The difference between Go and Dart is just the choice of how to format the same number.

If you want precise decimal computations don't use floating point numbers.

**Comment by a14n** [comment]
> If you want precise decimal computations don't use floating point numbers.

Shameless plug : you can use the [decimal](https://pub.dev/packages/decimal) package.

**Comment by cnmade** [comment]
problem, how to parse a math expression to decimal ,   my input was 
```
7*1.05
```

I search for a while, but does not find a library really can handle this expression parse well.

that's a big problem.

**Comment by cnmade** [comment]
The real world problem is : we often got a input math expression string.

How can we easy deal with it. and calc the right result (as double)

for example :  
```
7 * 3.13 / 2.1769853 + 10.12/3.1715
```

we need parse it. and convert right calc and got result.

what's a real and good practice to deal with it .

**Comment by cnmade** [comment]
@mraleph thanks, i already use it
