### ISSUE TITLE
Callbacks of future.then is called immediately without using unsafe API

### ISSUE THREAD

**Issue by johnchen902** [dart-lang/sdk#48493]
As far as I know, it is promised that the callbacks of completed futures are always called in later microtasks, as long as _unsafe_ APIs (such as Completer.sync or SynchronousStreamController) are not involved.

Consider the following snippet using `Future.sync`, which is _not_ documented to be unsafe:

```dart
import 'dart:async';

Future<int> makeFuture(bool useValue) =>
    useValue ? Future.value(5) : Future.sync(() => 5);

void test(bool useValue) {
  var c = Completer<int>();
  c.future.then((_) => print('$useValue 1'));
  c.complete(makeFuture(useValue));
  print('$useValue 2');
}

void main() {
  test(true);
  test(false);
}
```

* Expected behavior: `true 2` should appear before `true 1` and `false 2` should appear before `false 1`.
* Actual behavior:
   ```
   true 2
   false 1
   false 2
   true 1
   ```
* Environment:
  * DartPad (Dart SDK 2.16.1, Linux, Chrome)
  * My company's servers (Dart SDK 2.17.0, Linux, Chrome, both DDK and dart2js)
  * I'm informed that this is also reproducible with VM.
* Similar Issues:
  * #44751, in which the callbacks are _still_ called in later microtasks, just with different orders

**Comment by lrhn** [comment]
When the  `Completer.complete` function is given a `_Future` that has already completed, then it can go through a path that completes its future *synchronously* (ends up calliing `_Future.completeWithValue(....)` which works synchronously). 
That's a bug.

I'll make a test, fix it, add maybe some documentation to `_Future` methods, so it's clearer which functions to use in which situation.

**Comment by lrhn** [comment]
The CL link above points to the wrong place. The actual CL is https://dart-review.googlesource.com/c/sdk/+/234981, and it has not been committed yet.

**Comment by whesse** [comment]
The fix for this bug was reverted, and the fix was never relanded.  It looks like this issue may not have been fixed.

**Comment by lrhn** [comment]
Didn't stick this time either.

**Comment by lrhn** [comment]
N'th time is the charm. Thanks @natebosch
