### ISSUE TITLE
Analyzer is too strict in type checking extension override bounds

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#48509]
Consider the following code:

file `a.dart` (null safe):
```dart
extension E<X extends int> on List<X> {
  void m() {}
}
```

file `b.dart` (legacy):
```dart
// @dart=2.6
import 'a.dart';

f() => E<Null>([]).m();

main() {
  f();
}
```

The VM runs this program without complaint.  The analyzer complains:
```
error • b.dart:4:10 • 'Null' doesn't conform to the bound 'int' of the type parameter 'X'. Try using a type that is or is a subclass of 'int'. • type_argument_not_matching_bounds
```

I believe the VM's behavior is correct.  Even though the bound on `X` is non-nullable `int`, the nullability should be erased when viewed from the context of legacy library `b.dart`, so the invocation `E<Null>.m()` should be valid.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/235420
