### ISSUE TITLE
Expression.staticParameterElement sometimes points to a synthetic element

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#48500]
In the following situations, `Expression.staticParameterElement` points to a synthetic element that's not in the element tree (i.e. it has an `enclosingElement` that is `null`), whereas I believe it would be possible for it to point to a `ParameterMember` that in turn points to a parameter element in the element tree:
- In an instance creation expression, when the class being constructed is generic and the type parameters are inferred.
- In a method call, when the method being called is generic and the type parameters are either explicit or inferred.

I will shortly land some analyzer unit tests that illustrate this.

**Comment by stereotype441** [comment]
I'm hopeful that this issue will be fixed by a refactor I'm currently in the middle of, so I'm going to assign it to myself for now.  If I can't manage to fix it as part of the refactor I'll unassign myself.

**Comment by abitofevrything** [comment]
I believe this needs reopening, as I am encountering this issue again on the latest `analyzer` version (6.3.0 when I'm writing this):
```dart
void genericFunction<T>(T bar) {}

void foo() {
  genericFunction(1); // IntegerLiteral.staticParameterElement is a `ParameterMember` that points to a synthetic `ParameterElement`
}
```

It still works as expected for generic classes and members though:
```dart
class C<T> {
  C(T bar);
}

void foo() {
  C(1); // IntegerLiteral.staticParameterElement is not synthetic
}
```
```dart
abstract class C {
  T method<T>({arg});
}

test(C c) => c.method<bool>(arg: true);  // NamedExpression.staticParameterElement is not synthetic
```

Hopefully this is just a case that was missed in https://github.com/dart-lang/sdk/commit/f5af2d9e776a4d232c4f6a1a760d26e3a3ca2b52 that can be quickly changed :)

**Comment by parlough** [comment]
@abitofevrything Would you mind opening a new issue with this information? A lot has changed in the analyzer since this was implemented and a new issue would allow your issue to be focused on in isolation. Thanks :)

**Comment by abitofevrything** [comment]
Created #54669.
