### ISSUE TITLE
New Dart 2.17 `Isolate.run` doesn't close ports properly in an edge case

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#48516]
`Dart SDK version: 2.17.0-180.0.dev (dev) (Sun Mar 6 02:42:47 2022 -0800) on "macos_x64"`

Consider the following contrived example using the newly added `Isolate.run`:

```dart
import 'dart:isolate';

void main() async {
  final ReceivePort port = ReceivePort();
  try {
    await Isolate.run(() => port);
  } catch (e) {
    print(e);
  } finally {
    port.close();
  }
}

```

Running it by calling `dart run filename.dart` doesn't stop the executable. Which I believe means some ReceivePort isn't closed properly.

Looking at the implementation I think the culprit is the way Isolate is spawned.
https://github.com/dart-lang/sdk/blob/9a0be16a9dccf76c810c016ff43a60a7b694e823/sdk/lib/isolate/isolate.dart#L231-L244

Since the Future isn't awaited the `catch` block will not be called, but simply the `onError` handler, which just competes the Future.

<br>

I just happened to have started work on optimising the Flutter's `compute` method on the same day this new feature landed. So, in case it proves useful I just wanted to add a note that in the Flutter repository testing of closing all the ports is done by calling the `compute` in this case `Isolate.run` from a new `Process`. 

[For reference the PR with the rewritten `compute`.](https://github.com/flutter/flutter/pull/99527)

**Comment by horo99** [comment]
您发给我的信件已经收到。谢谢！

**Comment by dnfield** [comment]
@lrhn fyi

**Comment by lrhn** [comment]
Good catch.

If the spawn call sending the function fails, because the function closes over a sendport, then the raw receive port of the `run` method is not closed.
The `onError:` should also close the receive port.

**Comment by a-siva** [comment]
Potential candidate for cherry pick into Dart 2.17 Beta 2 branch.
