### ISSUE TITLE
Failures on [cfe] Handle enum super initializer with super-parameters enabled

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#48510]
There are new test failures on [[cfe] Handle enum super initializer with super-parameters enabled](https://github.com/dart-lang/sdk/commit/005ebcc761702223b6189ce1aa872564d1b6aa24).

The tests
```
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_amd_unsound_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux
```

**Comment by nshahan** [comment]
I think remember @Markzipan "sharded" them by the module type and null safety mode but maybe the growing number of tests is triggering timeouts again? WDYT?

**Comment by Markzipan** [comment]
That looks like a likely culprit. Further dividing them by agnostic/null-safe tests would be a reasonable patch, but I'll have to split them more intelligently down the line.

**Comment by nshahan** [comment]
Maybe we should just start landing new suites for every new language version to test its new features?

**Comment by annagrin** [comment]
@Markzipan I believe this is already fixed?

**Comment by Markzipan** [comment]
I believe so, closing this
