### ISSUE TITLE
generated_plugin_registrant.dart does not respect prefer_double_quotes: true

### ISSUE THREAD

**Issue by 18601673727** [dart-lang/sdk#48520]
Every time run debug for the flutter app, the `generated_plugin_registrant.dart` file got generated with content like this:
```dart
//
// Generated file. Do not edit.
//

// ignore_for_file: directives_ordering
// ignore_for_file: lines_longer_than_80_chars

import 'package:shared_preferences_web/shared_preferences_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  SharedPreferencesPlugin.registerWith(registrar);
  registrar.registerMessageHandler();
}
```
but I have set `prefer_double_quotes: true` in `analysis_options.yaml` so the linter keeps complain about `Prefer double quotes where they won't require escape sequences.`

**Comment by srawlins** [comment]
Please file this issue against the flutter/flutter repo. They can take the steps mentioned above.

**Comment by 18601673727** [comment]
Thank you @srawlins @Levi-Lesches!
