### ISSUE TITLE
[vm_service] Add tests for VmServerConnection

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#48536]
Looks like only dwds uses VmServerConnection, so sometimes we detect bugs too late (when wiring things to UI) and fixing cycle is too long. Adding tests for all VmServerConnection API would solve this problem.

See: https://github.com/dart-lang/sdk/issues/48521

**Comment by parlough** [comment]
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/51188
