### ISSUE TITLE
[ Timeline ] Possibility for segfault when attempting to write a timeline event at shutdown

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#48534]
Access to `Timeline::recorder_` isn't guarded by any locks, which makes it possible for one thread to try and allocate a new event from the recorder after it's been deleted. We should add a lock or some atomic counters to make sure we don't delete the recorder while timeline events are being written.

See [logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8820428833784457201/+/u/run_animation_with_microtasks_perf_ios__timeline_summary/test_stdout) for an example.

Related to https://github.com/flutter/flutter/issues/98421.

**Comment by a-siva** [comment]
marking as P1 based on the priority assigned to the Flutter issue.
