### ISSUE TITLE
Build on RISC-V host

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [dart-lang/sdk#48545]
I am looking for a way to build Dart on a RISC-V machine. As far as I see, the depot_tools support pretty much every CPU architecture except of RISC-V.

Did anyone figure out a way to either build the Dart SDK without the depot_tools or to make the depot_tools run on RISC-V?

**Comment by TheOneWithTheBraid** [comment]
Related `depot_tools` issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1305961&can=2&q=component%3AInfra%3ESDK

**Comment by rmacnak-google** [comment]
GN: 585b59afcdbc71d1189eb90e701b9fa91b0eb463

**Comment by rmacnak-google** [comment]
This now works with the most recent depot_tools. Note that because we don't have a prebuilt toolchain for RISC-V hosts, one must use the host's gcc, i.e. `tools/build.py --no-clang`.
