### ISSUE TITLE
[CP][stable?] Prevent dart2js crash on flutter web code using package:freezed

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#48559]
**commit(s) to merge**:  5090974cf37b54e81d65614bd52ea020261ac93c

**merge instructions**: needs special cherry-pick CL, but I'd like to discuss first whether we'd approve this hotfix before we create it. It merges cleanly on the beta channel, but not on stable due to some refactoring that occurred in between.

**What is the issue**: a broken invariant in the kernel representation when there are multiple redirecting factories, this can cause crashes in dart2js downstream.

**What is the fix**: CFE was updated to fix this invariant by picking the effective target and not the direct target of redirecting calls.

**Why cherrypick**:  The pattern that triggers this bug is commonly generated by `package:freezed`, a very popular package in the flutter ecosystem. The broken representation silently works in DDC and the VM, but triggers a crash in dart2js for flutter web users. 

**Risk**: low - fix is fairly localized, has been rolled internally.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/47916 (multiple reports merged here, 69+ votes). This is related to https://github.com/flutter/flutter/issues/100038 (a hotfix request on flutter). 

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew @johnniwinther

**Comment by mit-mit** [comment]
cc @kevmoo for input on customer priority

**Comment by athomas** [comment]
Not included in the beta, so we also want to merge this to beta if approved.

/cc @itsjustkevin

**Comment by sigmundch** [comment]
At our discussion we decided to proceed with including this in beta going forward, but to wait on the stable channel based on whether current users are in the beta/main channel or not.

For beta, it should be a clean merge.

**Comment by johnniwinther** [comment]
CL for merging into stable: https://dart-review.googlesource.com/c/sdk/+/238041

**Comment by athomas** [comment]
@itsjustkevin I'm considering this one as approved for both stable and beta based on the offline conversation yesterday.

**Comment by whesse** [comment]
This CP has landed in 2.16.2 stable.

**Comment by athomas** [comment]
Dart and Flutter releases get released on the same day. In this case that's planned for tomorrow.

**Comment by long1eu** [comment]
It landed in Dart but not Flutter

**Comment by athomas** [comment]
@itsjustkevin Did the Flutter release not go out?

**Comment by long1eu** [comment]
![AEF951A7-DA2B-4C30-A582-E92C2AB859A4](https://user-images.githubusercontent.com/9283414/160232378-959c279e-5cc3-47e5-b7b5-ab291a6c8a4a.png)

Not on stable or on beta

**Comment by sigmundch** [comment]
It appears there was a delay from the flutter side, but just checked this morning again and the release is out in [2.10.4](https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.10.4-stable.tar.xz) :tada:
