### ISSUE TITLE
Failures on [cfe] Pass references to augmentation libraries

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#48558]
There are new test failures on [[cfe] Pass references to augmentation libraries](https://github.com/dart-lang/sdk/commit/f3cc205fd82c3a0421875a4cc1291aeeedd4da17).

The tests
```
pkg/front_end/test/macros/incremental/incremental_macro_test RuntimeError (expected Pass)
```
are failing on configurations
```
cfe-unittest-asserts-release-mac
```

**Comment by brianquinlan** [comment]
The same error is also occurring on Linux (i.e. cfe-unittest-asserts-release-linux):
https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/front-end-linux-release-x64/17348/overview
