### ISSUE TITLE
DynamicLibrary.open() not loads the provided dylib, no error

### ISSUE THREAD

**Issue by westito** [dart-lang/sdk#48557]
Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"

I want to load `sqlite3 3.38.0` dylib installed by Homebrew, but I got the handle of the system installed `3.36.0`.
I try to test code using sqlite3 by `dart` command. I can't link the library into the binary.

```dart
final DynamicLibrary dlLib = DynamicLibrary.process();
final versionFunc = dlLib
        .lookup<NativeFunction<Pointer<Utf8> Function()>>('sqlite3_libversion');
final Pointer<Utf8> Function() versionDartFunc = versionFunc.asFunction();
final version = versionDartFunc().toDartString();
print('$version'); // Prints: 3.36.0
```
That's okay, this is loads the system sqlite3

But I try to load custom dylib:
```dart
const brewLib = '/opt/homebrew/Cellar/sqlite/3.38.0/lib/libsqlite3.0.dylib';
final dlLibBrew = DynamicLibrary.open(brewLib);
final versionFunc = dlLibBrew
        .lookup<NativeFunction<Pointer<Utf8> Function()>>('sqlite3_libversion');
final Pointer<Utf8> Function() versionDartFunc = versionFunc.asFunction();
final version = versionDartFunc().toDartString();
print('$version'); // Prints: 3.36.0
```
Both returns the same memory address (handle). It seems the DartVM not loads the custom lib, rather just returns the existing. The dylib really contains version 3.38.0, I checked.

Next, I tried load the library with custom dlopen (DartVM do exactly like that under the hood):
```dart
const brewLib = '/opt/homebrew/Cellar/sqlite/3.38.0/lib/libsqlite3.0.dylib';
final DynamicLibrary dlLib = DynamicLibrary.process();
final Pointer<Void> Function(Pointer<Utf8>, int) dlopenFun = dlLib
        .lookup<NativeFunction<Pointer<Void> Function(Pointer<Utf8>, Int32)>>(
            "dlopen")
        .asFunction();
final Pointer<Void> Function(Pointer<Void>, Pointer<Utf8>) dlsymFun = dlLib
        .lookup<
            NativeFunction<
                Pointer<Void> Function(Pointer<Void>, Pointer<Utf8>)>>("dlsym")
        .asFunction();
final sqliteHandle = dlopenFun(brewLib.toNativeUtf8(), 0x01); // returns the same handle that open()
final sqliteSym =
        dlsymFun(sqliteHandle, 'sqlite3_libversion'.toNativeUtf8()); // returns the same handle that lookup<>()
```

None of the commands above throws error.
I enabled dynamic loader logging with `DYLD_PRINT_LIBRARIES` and `DYLD_PRINT_LIBRARIES_POST_LAUNCH` environment variables, but it didn't show anything when `DynamicLibrary.open()` or `dlopen()` called.
It seems this is a macOS system level error, but I didn't find any information and got no answer on StackOverflow.
I guess the OS think this library already loaded and not loads the newer version. I can't get over this.

**Comment by mraleph** [comment]
This is expected (though somewhat counterintuitive) behavior on Mac OS X, see `man dlopen`.

> When path contains a slash but is not a framework path (i.e. a full path or a partial path to a dylib), dlopen() searches the following until it finds a compatible Mach-O file: `$DYLD_LIBRARY_PATH` (with leaf name from path ), then the supplied path (using current working directory for relative paths), then `$DYLD_FALLBACK_LIBRARY_PATH` (with leaf name from path ).

In other words `$DYLD_LIBRARY_PATH` is going to take priority over full path to the library. 

Nothing we can really do to suppress this unfortunately.
