### ISSUE TITLE
Constructor tear off and function literal of same class has different runtime type.

### ISSUE THREAD

**Issue by ArunPrakashG** [dart-lang/sdk#48550]
The runtime types returned by these two:

- `() => HomePage()`
- `HomePage.new`

is completely different.
Outputs:

`Function Literal: () => HomePage`
`Constructor Tear-Off: ({Key? key, _Location? $creationLocationd_0dea112b090073317d4}) => HomePage`

The runtime type string generated by the tear off doesn't seem to be the right one. Please let me know if this is intended.

**Dart SDK Version:**
Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64"

**Platform:**
I have tested this on macOS & Windows

**Comment by ArunPrakashG** [comment]
It only has the key parameter.
This is in flutter.

`HomePage({Key? key}) : super(key: key);`

**Comment by lrhn** [comment]
I'm guessing the extra parameter was somehow injected by Flutter for use with the [widget inspector](https://github.com/flutter/flutter/blob/f0524d542b2a5b3faae21b6cf7a354c4a2545758/packages/flutter/lib/src/widgets/widget_inspector.dart#L2861), and that's now visible since the constructor can be inspected as an object.

**Comment by ArunPrakashG** [comment]
That might be the cause in it.
But my original question highlight a different case.

Aren't these two the same ?
- () => HomePage()
- HomePage.new

If they are the same, why is the runtimeType different ?
different as in, We get different strings when printing them. Shouldn't they both print the same ?

Please correct me if I am mistaken,

**Comment by lrhn** [comment]
No, those two are not the same.

The function `() => HomePage()` takes zero parameters and calls the `HomePage` constructor with zero arguments.
It's a function literal expression, like every other function expression. This one happens to call the constructor in a specific way. The compiler considers it completely unrelated to the constructor.
You decide, entirely, the signature of the function by how you write the parameter list, the body only supplies the return type.

The `HomePage.new` function takes as many arguments as a he constructor allows, which in this case is two optional arguments. It's a function value which does not correspond to a function expression.
If the class had been generic, the tear-off would be a generic function (unless immediately instantiated), and the function literal above would not.
The signature of the function is decided by the constructor's signature.
