### ISSUE TITLE
What is the replacement for Analyzer's Source.modificationStamp

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#48565]
Hello!

This issue is about how `Source.modificationStamp` is deprecated, but there is no clear way forward.
The annotation currently is `@Deprecated('Not used anymore')`, which isn't helpful. And the documentation mentions `AnalysisContext.getModificationStamp` but that API no-longer exist either

In that situation, what can we use instead?

My use-case is for an analyzer plugin emitting fixes, and along with the fix, the protocol asks for a file stamp too.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Use `0` if the file exists, or `-1` if it does not exist.
This is what `ChangeBuilderImpl` from `analyzer_plugin` does.

**Comment by rrousselGit** [comment]
But isn't this going to break the logic behind having this property to begin with?

My understanding is that analyzer_plugin asks for a timestamp such that if somehow the file was edited after fixes were emitted, the fixes would be considered as no-longer valid.

**Comment by scheglov** [comment]
Correct, the intention was to use that produced changes are applicable to the files.

I don't remember the original reason why we switched to such `0` and `-1` values, but my current excuse is that with analysis server and overlays there are no modification stamp values.
