### ISSUE TITLE
[cfe] co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t27 failure

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#48577]
Said test causes a failure, cf. https://github.com/dart-lang/co19/issues/1316. The failure is a missing compile-time error for a mixin that declares an operator `==` and has `Enum` as a superinterface (cf. https://github.com/dart-lang/language/blob/master/accepted/future-releases/enhanced-enums/feature-specification.md#implementing-enum-and-enum-types).

The test needs an adjustment as well, that will occur separately, https://github.com/dart-lang/co19/issues/1319.

**Comment by eernstg** [comment]
Same issue with co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t26.

**Comment by eernstg** [comment]
Same issue with co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t25.

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/237580.

**Comment by eernstg** [comment]
A similar issue arises for `hashCode` in LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t23.

**Comment by eernstg** [comment]
Variant of the issue above with `hashCode` in LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t21.

**Comment by eernstg** [comment]
One more variant with `hashCode` in LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t19.

**Comment by eernstg** [comment]
One more variant with `hashCode` in LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t17.

**Comment by eernstg** [comment]
One more variant with `hashCode` in LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t15.

Fault in test handled separately, cf. https://github.com/dart-lang/co19/issues/1321.

**Comment by eernstg** [comment]
One more variant in LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t13.
