### ISSUE TITLE
Fails to fix require_trailing_commas rule in functions

### ISSUE THREAD

**Issue by evandrmb** [dart-lang/sdk#48578]
Hi, I'm not sure if the issue should be filed in this repo, but I'm having problems with the `require_trailing_commas` rule. When it's active and we have the following setting at VsCode:

```
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
```
It seems incapable of fixing the code in functions like

```dart
Future<void> someFunction(
      BuildContext context, String value1, String value2) async {}
```

Neither in constructors
```dart
  const factory LoginState.logged(Collaborator user, Company company,
      {@Default(false) bool wasFirstLogin}) = _Logged;
```

But works just fine at widgets:

```dart
Text(
            label,
            style: Theme.of(context).textTheme.bodyText1,),
```

* Tools • Dart 2.16.0 • DevTools 2.9.2
* Windows

**Comment by bwilkerson** [comment]
The class `AddTrailingComma` needs to be expanded to handle parameter lists as well as argument lists.

@asashour

**Comment by asashour** [comment]
Sure.

https://dart-review.googlesource.com/c/sdk/+/237660

in both scenarios they are `FormalParameterList`
