### ISSUE TITLE
[dart2js]: unsoundness in global type inference

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#48571]
This is a copy of https://github.com/flutter/flutter/issues/100135 for tracking pruposes under the Dart SDK repo:

Repro:
```dart
abstract class Base {}

class Child1 extends Base {
  final bool isChild1 = true;
}

class Child2 extends Base {}

main() {
  List<Base> children = [
    Child1(),
    Child2(),
  ];

  List<Base> onlyChild2 = [];
  for (final child in children) {
    // NOTE: without the added "&& child.isChild1" everything works fine
    if (false == (child is Child1 && child.isChild1)) {
      onlyChild2.add(child);
    }
  }

  // Will print "true" in debug, but "false" in profile
  print(onlyChild2.first is Child2);

  // EDIT: What is arguably worse is the following:
  // Will print "false" in debug, but "true" in profile
  print(onlyChild2.first is Child1);
}
```

Running this program with dart2js prints (incorrectly): false, true, running with `--disable-type-inference` will print (correctly): true, false.

**Comment by sigmundch** [comment]
Small simplification of the repro:
```dart
abstract class Base {}
class Child1 extends Base {}
class Child2 extends Base {}

main() {
  Base child = DateTime.now().millisecondsSinceEpoch > 0 ? Child2() : Child1();
  List<Base> list = [];
  if (false == (child is Child1 && true)) {
    list.add(child);
  }
  print(list.first is Child1); // prints true, should be false
}

```

**Comment by sigmundch** [comment]
@rakudrama - this looks to me like an issue in handling nesting of conditions and misattributing the state in the locals handler where we shouldn't. That is:

* the `if` starts a `handleCondition`
* the `==` quickly leaves the conditionContext when recursing on the left and right
* the `&&` begins a new condition context and computes a new state after true/false
* when we come back to the `if` we incorrectly grab the true/false state created by the `&&` and attribute it to the entire condition.


Not sure if this is the right fix, seems like we are missing some cleanup of the conditional state. Maybe directly in `visit` whenever `!conditionContext`?
https://github.com/dart-lang/sdk/blob/f58adc5dc3e9ecd9186771a1e62df84372cbcbe4/pkg/compiler/lib/src/inferrer/builder_kernel.dart#L259

**Comment by fishythefish** [comment]
I only gave this a quick glance so far, but other elements of our context handling confuse me.

https://github.com/dart-lang/sdk/blob/f58adc5dc3e9ecd9186771a1e62df84372cbcbe4/pkg/compiler/lib/src/inferrer/builder_kernel.dart#L256-L262

It's strange to me that we leave the condition context at all during the `==`. Calls to `visit` need to explicitly say `conditionContext: true` even if we already know the surrounding context is a condition. Should line 258 be `_accumulateIsChecks = conditionContext || oldAccumulateIsChecks;`?

Note: this change alone doesn't fix the issue. The way we manage invariants in our inference state machine is pretty scattered, and we may need to reset/invalidate other state when we leave a context, as Siggi suggests.

**Comment by sigmundch** [comment]
_( bummer, I thought I replied yesterday... seems I lost my draft :( )_

> It's strange to me that we leave the condition context at all during the `==`. 

It does look strange, but it's actually intended. Once you go deeper into subexpressions, the conclusions within the sub expressions don't map to the whole condition unless we can reason about the semantics of the `==` operator. It's rare to have a `==` with a boolean constant value, so dropping the context seems reasonable.

Doing so would be no different from code like this (which also reproduces the same bug as the one above):
```dart
abstract class Base {}
class Child1 extends Base {}
class Child2 extends Base {}

trivial(x) => true;

main() {
  Base child = DateTime.now().millisecondsSinceEpoch > 0 ? Child2() : Child1();
  List<Base> list = [];
  if (trivial(child is Child1 && true)) {
    list.add(child);
  }
  print(list.first is Child1);
}
```
