### ISSUE TITLE
Poor formatting for super parameters in IntelliJ

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48582]
In a file in a package that has the `super_parameters` experiment enabled, paste the following:
```
class A {
  A(int x);
}
class B extends A {
  B(super.x);
```
Then type a `}` at the end of the file (I was on the next line when I tested this).

The constructor declaration will be poorly formatted so that each token is on a separate line.

**Comment by bwilkerson** [comment]
@jwren

**Comment by jwren** [comment]
Thank you for the bug report @bwilkerson -- I can't seem to configure such a project myself, I am getting both a message that I need to enable super-parameters, and that it isn't supported, this is with the latest built from head at the end of last week:

"warning: The option 'super_parameters' isn't supported by 'language'. (unsupported_option_with_legal_values at [console_dart] analysis_options.yaml:18)"

and

"error: This requires the 'super-parameters' language feature to be enabled. (experiment_not_enabled at [console_dart] bin/bar.dart:5)"

My analysis options file includes:

```
analyzer:
  language:
    super-parameters: true
```

CC @alexander-doroshko

**Comment by bwilkerson** [comment]
Experiments aren't enabled under the `language` key, but under the `enable-experiment` key.

I verified that I can reproduce it using a package in which the `pubspec.yaml` includes:
```
environment:
  sdk: '>=2.17.0-dev <3.0.0'
```
and the `analysis_options.yaml` contains:
```
analyzer:
  enable-experiment:
    - enhanced-enums
    - named-arguments-anywhere
    - super-parameters
```

It's possible that my IntelliJ / plugin is too old:

IntelliJ IDEA 2021.2.4 (Community Edition)
Build #IC-212.5712.43, built on December 21, 2021
Runtime version: 11.0.13+8-b1504.49 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: dart.server.additional.arguments=--port=10010 --instrumentation-log-file=/Users/brianwilkerson/temp/serverLog/instrumentation.log, debugger.watches.in.variables=false, dart.server.vm.options=--observe=8181 --enable-vm-service --pause_isolates_on_unhandled_exceptions=true --disable-service-auth-codes, max.suggested.heap.size=4096
Non-Bundled Plugins: Dart (212.5632)
Kotlin: 212-1.5.10-release-IJ5712.43
