### ISSUE TITLE
Issue/Extend timeline events when sending messages to other isolates containing the size of copied object graph

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#48591]
When using `SendPort.send()` or `Isolate.spawn()` the implementation may need to copy an object graph. For developers to see how large such object graphs are, we should make this information available in DevTools, e.g. via timeline events containing the number of bytes those objects will occupy (if message serializer is used, the deflated object size for the messages)

/cc @mit-mit @lrhn

**Comment by a-siva** [comment]
//cc @bkonyi
