### ISSUE TITLE
Typedef errors not correct

### ISSUE THREAD

**Issue by guidezpl** [dart-lang/sdk#48593]
Dart SDK version: 2.17.0-202.0.dev (dev) (Thu Mar 10 20:55:41 2022 -0800) on "macos_x64"

In file 1, I define a typedef and a class method which uses it:
`typedef ThemeExtensionMap = Map<Type, ThemeExtension<dynamic>>;`

<img width="667" alt="Screenshot 2022-03-17 at 13 37 10" src="https://user-images.githubusercontent.com/6655696/158810374-86f343e0-c65f-43b1-b3fe-e9c07e6da26e.png">

In file 2, I call that method, but get the following analyzer error, indicating an incorrect parameter type.

`The argument type 'Map<Type, MyColors>' can't be assigned to the parameter type 'dynamic Function()?'.`

<img width="522" alt="Screenshot 2022-03-17 at 13 36 56" src="https://user-images.githubusercontent.com/6655696/158810583-13cff639-7a02-4164-9ebc-cd158979bad1.png">

Why is the type now being indicated as 'dynamic Function()?'?

**Comment by mraleph** [comment]
@guidezpl did you rerun `pub get` after changing the constraint (if you needed to change it)? I'd also check if you analysis server is new enough (sometimes people point their IDE to an old SDK by accident).

**Comment by guidezpl** [comment]
Can't repro anymore, likely an issue with multiple SDKs. Closing :)
