### ISSUE TITLE
Provide interop for other languages

### ISSUE THREAD

**Issue by mgazisalik** [dart-lang/sdk#48604]
It would be very nice if there is interop for python, golang, etc..

**Comment by mraleph** [comment]
You can interop with all these languages through Dart FFI (i.e. there are known cases where people embed Go code into their Dart/Flutter applications). 

Higher level interop can be built out of lower-level interop primitives - but these is outside of scope for Dart team. We simply don't have resources to provide interop packages for all languages in the world. 

We encourage community to step up and fill the gaps where needed.
