### ISSUE TITLE
Create Method fix produces incorrect linked edit groups for function arguments

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#48612]
Given this code:

```dart
class A {
  void a() => c((cell) => cell.south);
  void b() => c((cell) => cell.west);
}
```

The "Create method 'c'" quickfix produces the following source change:

```js
{
	"message": "Create method 'c'",
	"edits": [
		{
			"file": "/home/my_project/lib/main.dart",
			"edits": [
				{
					"offset": 86, "length": 0,
					"replacement": "\n\n  c(Function(dynamic cell) param0) {}"
				}
			]
		}
	],
	"linkedEditGroups": [
		{
			"positions": [
				{ "file": "/home/my_project/lib/main.dart", "offset": 90 },
				{ "file": "/home/my_project/lib/main.dart", "offset": 24 }
			],
			"length": 1
		},
		{
			"positions": [
				{ "file": "/home/my_project/lib/main.dart", "offset": 101 },
				{ "file": "/home/my_project/lib/main.dart", "offset": 92 }
			],
			"length": 22
		},
		{
			"positions": [
				{ "file": "/home/my_project/lib/main.dart", "offset": 109 },
				{ "file": "/home/my_project/lib/main.dart", "offset": 115 }
			],
			"length": 6,
			"suggestions": [
				{
					"value": "param0",
					"kind": "PARAMETER"
				}
			]
		}
	],
	"id": "dart.fix.create.method"
}
```

If you apply the initial edit, you end up with:

```dart
class A {
  void a() => c((cell) => cell.south);
  void b() => c((cell) => cell.west);

  c(Function(dynamic cell) param0) {}
}
```

The offsets of the positions in edit groups cover the following ranges:

- 90-91: `c`
- 24-25: `c`
- 101-123: `dynamic cell) param0) ` // This is wrong
- 92-114: `Function(dynamic cell)`
- 109-115: `cell) ` // This is wrong
- 115-121: `param0`

@bwilkerson my assumption is that the overlapping linked groups is normal (although that's an issue for LSP - I'm working on a fix to skip them). The other issues I believe is a result of a linked edit group having a single `length` for all of its positions, and in this case the generated code has different text in different locations, eg.:

- `Function(dynamic cell)` vs `dynamic cell`
- `cell` vs `param0`

I'm not sure whether using a single length is the issue, or whether the generated code should match (and if so, whether it's _always_ the case that it can match)?

**Comment by DanTup** [comment]
> It doesn't make sense for them to be overlapping.

Ah, good to know - in that case I won't need to filter them out in LSP :-)

> So, we need to figure out why those extraneous offsets are being produced and stop that from happening.

I'll take a look and see what I can find (the offsets both start at a type and arg name which I'm sure is not a coincidence).

**Comment by bwilkerson** [comment]
I suspect that `writeType` is adding edit groups for the parameter type and parameter name when writing out a function type, and that they accidentally have the same identifiers as the edit groups being created for the surrounding method.

If so, we'll need to find a way to ensure that the names are unique.

**Comment by DanTup** [comment]
Yep, I think that's spot on. I ended up in `DartEditBuilderImpl.writeParameters` where it's creating edit groups for the nested args and using `'${groupPrefix}TYPE$i'` where `groupPrefix` is an empty string and `i` is the index for the parameter in this list.

Although, I think fixing the non-unique name doesn't address the overlapping edit groups - it would just produce additional edit groups? When writing a function type, shouldn't creation of nested edit groups be suppressed entirely? Or more generally, should edit groups be suppressed for any code inside a callback of an existing `addLinkedEdit`?

**Comment by bwilkerson** [comment]
> ... should edit groups be suppressed for any code inside a callback of an existing addLinkedEdit?

Yes.
