### ISSUE TITLE
[analyzer] unstable lints location

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#48611]
Steps:

1. Enable `cascade_invocations` lint
2. Copy the following in a new file
```
class A {
  void m() {}
  int? x;
}

void f(A a, A b) {
  a.m();
  a.x = 1;
  a.m();
}
```

2. The lints are shown correctly in the second and third invocations.
3. At the end of the method, add `b.m();`
4. Save
5. Remark the added line with `//`, save

    Expected:

       The lints remain the same

    Actual

       The lints are shown in different unexpected places.

6. Remove the remark
7. The lints are fine for a short period, then then are shown wrong again.

Attached is a video showing the issue

https://user-images.githubusercontent.com/2410127/158989611-98c480e5-2bdc-45c5-901b-c80c7a92d20b.mp4

```
Dart SDK version: 2.17.0-216.0.dev (dev) (Thu Mar 17 04:20:48 2022 -0700) on "windows_x64"

IntelliJ IDEA 2021.3.3 (Community Edition)
Build #IC-213.7172.25, built on March 15, 2022

Dart Plugin 213.7227
```

**Comment by scheglov** [comment]
I cannot reproduce it.

**Comment by asashour** [comment]
The reason is https://github.com/dart-lang/sdk/commit/6de7ea74328ef752a00db3d6b1e8a44d354caea3

For further investigations.

**Comment by asashour** [comment]
This seems to be fixed in latest IntelliJ Dart plugin.
