### ISSUE TITLE
`strong-mode` documentation points to archived repo

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#48617]
The two google links at:
https://github.com/dart-lang/sdk/blob/2c0ba56ea12490d7f355641d2b5169386cbee53c/pkg/analyzer_cli/lib/src/options.dart#L383
https://github.com/dart-lang/sdk/blob/2c0ba56ea12490d7f355641d2b5169386cbee53c/pkg/analyzer_cli/lib/src/options.dart#L389

both point to a Markdown doc that was last updated in 2016 and is in an archived / deprecated repo.

It's unclear whether these are still relevant. https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks suggests that `implicit-casts` is now deprecated; it's not clear whether the same applies to `implicit-dynamic` or not. I'm unclear whether they should still be turned on?

**Comment by bwilkerson** [comment]
@srawlins For status of the options.

I will point out that the `analyzer_cli` package contains the implementation of the `dartanalyzer` command, which itself is deprecated and will at some point be removed. I don't know whether that impacts the importance of dealing with the help documentation.

**Comment by parlough** [comment]
I believe these options are now also fully covered by the `strict-casts`, `strict-inference`, and `strict-raw-types`  [language modes](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks):

```yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```

Side note, could we somehow deprecate the `strong-mode` in `analysis_options.md` and direct users to the new language modes?

**Comment by bwilkerson** [comment]
Yes, we can, and probably should, create diagnostic for those cases. We already have one for `strong-mode: true`, which we believed to be the more common case.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/sdk/issues/50679 which tracks removing these modes, since the old `analyzer_cli` referenced here is no longer used.

https://dart.dev/tools/analysis#enabling-additional-type-checks documents the newer language modes.
