### ISSUE TITLE
[Windows] Null Safety Migration tool 404 error

### ISSUE THREAD

**Issue by iqfareez** [dart-lang/sdk#48622]
![nnbd migration preview 404](https://user-images.githubusercontent.com/60868965/159189789-421a7bf3-d43b-40cd-a1e7-8145f6061cdb.png)

* Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64"
* Windows
* Edge

Error occurred when trying to migrate old Flutter project. Make the migration tool **correctly respecting Windows' case insensitive paths.**

Steps to reproduce: https://github.com/flutter/flutter/issues/100134#issue-1169639718

Others: https://github.com/microsoft/vscode/issues/145195

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
