### ISSUE TITLE
[Analyzer] @visibleForOverriding flags calls to super

### ISSUE THREAD

**Issue by math1man** [dart-lang/sdk#48626]
I have a method handleErrorEvent annotated `@visibleForOverriding`, and in the implementation I call `super.handleErrorEvent()` to fall back to the default implementation. The IDE flags this and says that the method is only visible for overriding, because the super call is technically still a method call. This seems like a bug, and `@visibleForOverriding` should allow calling the method's own super. See screenshot below

* Dart SDK Version (`dart --version`): Google internal
* Whether you are using Windows, MacOSX, or Linux (if applicable): MacOSX
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): Android Studio

![image](https://user-images.githubusercontent.com/4040946/159255682-a5ac302d-856a-4ffa-b308-34b62f8e4092.png)

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/239432
