### ISSUE TITLE
flaky ffi_2/function_structs_by_value_generated_leaf_test/1 turned timeout 

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#48627]
on [dartk-win-debug-ia32](https://dart-ci.appspot.com/log/vm-kernel-win-debug-ia32/dartk-win-debug-ia32/6970/ffi_2/function_structs_by_value_generated_leaf_test/1)

```
--- Command "vm" (took 02:00.000019s):
set DART_CONFIGURATION=DebugIA32 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugIA32\crashpad_handler.exe & out\DebugIA32\dart.exe --deterministic --optimization-counter-threshold=5 -Dtest_runner.configuration=dartk-win-debug-ia32 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\tests\ffi_2\function_structs_by_value_generated_leaf_test.dart

exit code:
null

diagnostics:
win_sdk_path not found

--- Re-run this test:
python3 tools/test.py -n dartk-win-debug-ia32 ffi_2/function_structs_by_value_generated_leaf_test/1
```

**Comment by alexmarkov** [comment]
Same happened on `vm-kernel-nnbd-linux-release-ia32`.

https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-release-ia32/dartk-strong-linux-release-ia32/680/ffi/function_structs_by_value_generated_leaf_test/1

**Comment by alexmarkov** [comment]
Also, multiple tests turned from flaky to timeout on `vm-kernel-win-debug-ia32`:
```
ffi_2/function_callbacks_very_many_test/0
ffi_2/null_test/1
ffi_2/variance_function_test/1
```
and from Pass to Timeout:
```
service_2/pause_on_unhandled_async_exceptions2_test/dds_1
```

In addition, `vm-kernel-optcounter-threshold-linux-release-ia32` is timing out on multiple shards.
It looks like IA32 became slower.

Possible suspect: 1bff4bead9297d2d6e545e3ea7804bdb5a08a305
/cc @rmacnak-google

**Comment by liamappelbe** [comment]
Just happened again on dartk-weak-asserts-linux-debug-ia32, ffi/function_structs_by_value_generated_leaf_test/1, after [the workaround](https://dart-review.googlesource.com/c/sdk/+/263421) was submitted. But the timeout for that test was already increased in that CL. Maybe the timeout needs to be increased further?

**Comment by alexmarkov** [comment]
Timeout was not increased, [that change](https://dart-review.googlesource.com/c/sdk/+/263421) increased `--optimization-counter-threshold` to 20 to prevent too many unnecessary optimized compilations in kernel service. We can try to further increase `--optimization-counter-threshold`, but we also need to increase number of iterations in the test (to make sure optimization happens for all tested functions), which may slow down the test.

Maybe this time we should just split this test into multiple tests as it is very huge.
