### ISSUE TITLE
Failures on [vm/ffi] Add error for FFI annotation with opt. args....Run macro types phase.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#48625]
There are new test failures on [[vm/ffi] Add error for FFI annotation with opt. args....Run macro types phase.](https://github.com/dart-lang/sdk/compare/eb955436299772ff1b14646e385c83ce6698789b~...2c0ba56ea12490d7f355641d2b5169386cbee53c).

The tests
```
pkg/analyzer_cli/tool/perf_test CompileTimeError (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-linux-ia32-d8
dart2js-minified-linux-d8
```

I think this is because the added tests are being used as source code for a different test that runs on Dart web with dart2js, and that platform does not have the dart:cli library available:

DART_CONFIGURATION=ReleaseIA32 sdk/bin/dart2js_developer -Dtest_runner.configuration=dart2js-hostasserts-linux-ia32-d8 --test-mode --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/pkg/analyzer_cli/tool/perf_test.dart --out=/b/s/w/ir/cache/builder/sdk/out/ReleaseIA32/generated_compilations/dart2js-hostasserts-linux-ia32-d8/pkg_analyzer_cli_tool_perf_test/perf_test.js

exit code:
1

stdout:
pkg/analyzer/lib/src/summary2/macro_application.dart:6:8:
Error: Not found: 'dart:cli'
import 'dart:cli' as cli;
       ^
pkg/analyzer/lib/src/summary2/macro_application.dart:55:47:
Error: Method not found: 'waitFor'.
                        var macroResult = cli.waitFor(
                                              ^^^^^^^
Error: Compilation failed.

--- Re-run this test:
python3 tools/test.py -n dart2js-hostasserts-linux-ia32-d8 pkg/analyzer_cli/tool/perf_test

**Comment by scheglov** [comment]
I reverted the changes that used `dart:cli` in https://dart-review.googlesource.com/c/sdk/+/237960
