### ISSUE TITLE
Directory.listSync returns files out of order on some platforms (should be documented?)

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#48621]
Directory("foo").listSync() will return in alphabetical order on Windows, but out of order on Mac.

This is fine.  Just seems like the docs should mention no ordering guarantee?

https://api.flutter.dev/flutter/dart-io/Directory/listSync.html

e.g. 

```
Order of FilesystemEntities is not guaranteed and may vary between platforms.  If you depend on order, it is recommended you sort the output, e.g.

var entities = dir.listSync().toList();
entities.sort((a, b) => a.path.compare(b.path));
```

var dir = Directory(dirPath)
for (var element in dir.listSync() {
  print(element.path);
}

e.g. prints on Mac:

html5lib-tests/tokenizer/domjs.test
html5lib-tests/tokenizer/entities.test
html5lib-tests/tokenizer/test4.test
html5lib-tests/tokenizer/unicodeCharsProblematic.test
html5lib-tests/tokenizer/test3.test
html5lib-tests/tokenizer/contentModelFlags.test
html5lib-tests/tokenizer/test2.test
html5lib-tests/tokenizer/escapeFlag.test
html5lib-tests/tokenizer/numericEntities.test
html5lib-tests/tokenizer/README.md
html5lib-tests/tokenizer/xmlViolation.test
html5lib-tests/tokenizer/test1.test
html5lib-tests/tokenizer/unicodeChars.test
html5lib-tests/tokenizer/pendingSpecChanges.test
html5lib-tests/tokenizer/namedEntities.test

My mac version:
Dart SDK version: 2.17.0-69.2.beta (beta) (Mon Feb 14 13:41:58 2022 +0100) on "macos_x64"

I can get the Windows version if needed.

**Comment by kevmoo** [comment]
Seems this was fixed in https://github.com/dart-lang/sdk/commit/0a591de1647fb59f4a5ea97c9265c54f25cafa20 – satisfied @eseidel ?

**Comment by eseidel** [comment]
Thanks!

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/0a591de1647fb59f4a5ea97c9265c54f25cafa20
