### ISSUE TITLE
Expando `object` -> `key`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48634]
Expando `key`s are named `object` in Map-like methods.

* https://api.dart.dev/stable/2.16.1/dart-core/Expando/operator_get.html
* https://api.dart.dev/stable/2.16.1/dart-core/Expando/operator_put.html

This is inconsistent with `Map` naming:

* https://api.dart.dev/stable/2.16.1/dart-core/Map/operator_get.html
* https://api.dart.dev/stable/2.16.1/dart-core/Map/operator_put.html

Should we rename `object` to `key` in `Expando`?

cc @lrhn

(Triggered by https://dart-review.googlesource.com/c/sdk/+/229544/41/sdk/lib/_internal/vm/lib/internal_patch.dart, thanks @rmacnak-google.)

**Comment by mraleph** [comment]
The reason for this naming is due to `Expando` being an _expansion_ of the given `object`. 

If it was named `WeakMap` then `key` would be more appropriate.

**Comment by dcharkes** [comment]
Thanks for the explanation @mraleph !
