### ISSUE TITLE
False negative in `if-expression`

### ISSUE THREAD

**Issue by theRealProHacker** [dart-lang/sdk#48636]
## Describe the issue
Dart doesn't lint, the last statement in the `innerFunc` below. It only gives some `infos` because I am not using the variables anywhere. However, building the project fails dramatically.

## To Reproduce
```dart
void main() {
  void innerFunc(bool myBool, String errorMessage){
    String? _hint = !myBool ? "Value1" : null;
    String? _label = myBool ? "Value2" : null;
    String? _errorText = errorMessage.isNotEmpty ? errorMessage;
  }
}
```
## Expected behavior
I expect the linter to give me a clear warning, at that line, and tell me exactly why the error is happening. Even building gives you a quite unclear parse error: `Error: This couldn't be parsed.` Which doesn't really tell my anything about the error. Instead, the linter or at least the compiler should tell me that I am missing the `:` which most other modern linters/compiler/interpreters are able to do and which is pretty easy because after an `?` the compiler should be expecting an `:`.

**Comment by eernstg** [comment]
I transferred this issue from the linter repo to the SDK repo, because we should get a compile-time error on the line that declares `_errorText`. 

We have two issues here: The analyzer should report a syntax error, and the common front end shouldn't crash. Here is a smaller example:

```dart
void f(bool myBool, String s) {
  String? x = s.isNotEmpty? s;
}

void main() { f(true, ''); }
```

**Comment by eernstg** [comment]
Exactly! The conditional expression (`?:`) has ambiguities with other constructs as well, e.g., `{ b ? [1] : 2 }` could be a map literal where `b?[1]` is a null-aware invocation of the index operator on `b` (the parser won't know whether `b` resolves to a type declaration or a variable declaration) which is mapped to `2`, or it could be a set literal containing one element which is obtained by evaluating the conditional expression `b ? [1] : 2`. So "easy" isn't always a safe bet for Dart syntax. ;-)

**Comment by bwilkerson** [comment]
> The analyzer should report a syntax error ...

Using the smaller example from https://github.com/dart-lang/sdk/issues/48636#issuecomment-1075047729, the `dart analyze` command produces two diagnostics:
```
error: Expected an identifier. (missing_identifier at [test_package] lib/test.dart:2)
error: Expected to find ':'. (expected_token at [test_package] lib/test.dart:2)
```

> I expect the linter to give me a clear warning ...

I'm not sure what you mean by "linter". Are you using the `dart analyze` command? If so, and if you aren't seeing the diagnostics above, then it's possible that the bug has been fixed but the change hasn't yet made it into a 'dev' or 'stable' release. If you're using a different command, can you tell me which one?

**Comment by eernstg** [comment]
Closing: Apparently, I forgot to check the behavior of the bleeding edge tools: The issue has been fixed by now, in the analyzer as well as in the common front end.

**Comment by pq** [comment]
Thanks for following up @eernstg!  And for motivating the good conversation @theRealProHacker !
