### ISSUE TITLE
autofix for `use_super_parameters` incorrectly "fixes" renamed arguments

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48633]
When the `use_super_parameters` lint is enabled `dart fix --apply` applies an incorrect fix if parameters are renamed. 

Code before running `dart fix --apply`:
```dart
class Base {
  const Base({
    this.key,
    this.arg,
  });

  final int? key;
  final String? arg;
}

class Extended extends Base {
  const Extended({
    int? key,
    String? renamedArg,
  }) : super(
          key: key,
          arg: renamedArg,
        );
}
```

Code after running `dart fix --apply`:

```dart
class Base {
  const Base({
    this.key,
    this.arg,
  });

  final int? key;
  final String? arg;
}

class Extended extends Base {
  const Extended({
    super.key,
    super.renamedArg, // 🔥 ERROR! The parameter needs to be passed to the superclass's `arg` param. 
  });
}
```

Instead, the autofixer should have only changed how `key` is passed to the superclass and leave `arg`/`renamedArg` alone.

This bug only triggers if there's a parameter for which the `use_super_parameters` lint triggers legitimately (here: `key`). If you only have the renamed parameter (remove `key` from the example above) nothing happens as expected.

**Comment by goderbauer** [comment]
//cc @bwilkerson @pq

**Comment by bwilkerson** [comment]
Thanks! I'll take a look at this in the morning.
