### ISSUE TITLE
[CFE] package:path produces undetermined nullability

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#48643]
Patch [this CL](https://dart-review.googlesource.com/c/sdk/+/238163) to update dart2js to throw if it hits `ir.Nullability.undetermined`. This prevents the SDK from building due to `PathMap.V%`.

In fact, even the following is sufficient to repro the issue:
```dart
import 'package:path/path.dart';

void main() {}
```

/cc @johnniwinther @chloestefantsova

**Comment by johnniwinther** [comment]
This nullability is found on a `TypeParameterType` which is where we expect to find `Nullability.undetermined` - it means that `PathMap.V` can be nullable or non-nullable depending on instantiation: `PathMap<String>` make non-nullable, `PathMap<String?>` makes it nullable.

**Comment by fishythefish** [comment]
Oh, I see. I recalled that it was an invariant that backends wouldn't see `Nullability.undetermined`, but I must have been mistaken.

@nshahan - I thought DDC was throwing on *any* encounter with `Nullability.undetermined`, but it looks like DDC does correctly permit it on type parameters and in some other places. I can do something similar for dart2js.

**Comment by nshahan** [comment]
Ah yes, that is a good point. I forgot that code path in DDC sometimes is triggered after we "cleanup" undetermined nullability in a few positions where the CFE does expect to show it.
