### ISSUE TITLE
super parameters break non-const subclasses of const superclasses

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48642]
```dart
void main() {
  Extended(value: 10);
}

class Foo {
  const Foo({this.value, this.list});

  final int? value;
  final List? list;
}

class Extended extends Foo {
  // 🔥 Error: Constant expression expected.
  Extended({super.value}) : super(list: List.filled(10, null));

  // No Error:
  // Extended({int? value}) : super(value: value, list: List.filled(10, null));
}
```

Running the above program with Dart 2.17.0-226.0.dev on macos_x64 gives the following error:

```
lib/super_params.dart:14:46: Error: Constant expression expected.
Try inserting 'const'.
  Extended({super.value}) : super(list: List.filled(10, null));
                                             ^^^^^^
lib/super_params.dart:14:46: Error: Cannot invoke a non-'const' factory where a const expression is expected.
Try using a constructor or factory that is 'const'.
  Extended({super.value}) : super(list: List.filled(10, null));
                                             ^^^^^^
```

When not using the new super parameter feature for `value` of `Extended` (see commented out constructor above) everything compiles and runs as expected.

**Comment by goderbauer** [comment]
/cc @mit-mit 

Noticed this while trying to upgrade the flutter code base to use super parameters where appropriate. There are a couple of instances in our code base that trigger this problem. Here's one real life example: https://github.com/flutter/flutter/blob/2e5ad37b063928d080de7839f08999ed0dc521c9/dev/integration_tests/flutter_gallery/lib/gallery/about.dart#L25

**Comment by leafpetersen** [comment]
cc @johnniwinther @lrhn  This reproduces at head for me.  The analyzer reports no errors.

**Comment by chloestefantsova** [comment]
I'm working on the fix in https://dart-review.googlesource.com/c/sdk/+/238700
