### ISSUE TITLE
Failures on [vm] Refactor compilation of runtime calls.

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#48646]
There are new test failures on [Update clang and gn to match Fuchsia....Handle another case of replacing a named constructor](https://github.com/dart-lang/sdk/compare/5b71e48f951a01e23f69f428fbdfca81583dacd1~...b75c19e8a89fc8d12b41cd9c5b00a6074b054442).

The tests
```
vm/dart_2/write_barrier_double_register_clobber_test RuntimeError (expected Pass)
vm/dart_2/write_barrier_simd_register_clobber_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-simarm-crossword
dartkp-linux-release-simarm
dartkp-linux-release-simarm-crossword
```

These tests were introduced in 67f93d3840981ad81b44bceb0b755fbab50f13bd and immediately started failing on AOT/simarm.
@rmacnak-google Could you please take a look?

**Comment by sstrickl** [comment]
Also approving the overnight failures on

```
dartkp-strong-linux-debug-simarm-crossword
dartkp-strong-linux-release-simarm-crossword
dartkp-weak-asserts-linux-debug-simarm-crossword
dartkp-weak-asserts-linux-release-simarm-crossword
```

**Comment by rmacnak-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/238301
