### ISSUE TITLE
The x86/x64 disassembler prints the wrong registers.

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#48656]
The disassembler code in runtime/vm/compiler/assembler/disassembler_x86.cc for instance prints:
```
movb rdi,[rsp+0x8]
```
When the underlying assembly is in fact:
```
movb bh,[rsp+0x8]
```

It likewise prints full-width registers for instructions that operate on e.g. byte registers. (i.e. `rax` instead of `al`)

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/247463
