### ISSUE TITLE
documentation for `strong-mode` rules

### ISSUE THREAD

**Issue by DetachHead** [dart-lang/sdk#48650]
**Describe the issue**
there seems to be no documentatioin for the `analyzer.strong-mode` options. though the `implicit-casts` option is [mentioned briefly here](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks), i can't seem to find any documentation for the other options.

i think there are 2 more (`implicit-dynamic` and `declaration-casts`)

**Comment by DetachHead** [comment]
raised #48651

**Comment by scheglov** [comment]
@srawlins

**Comment by srawlins** [comment]
The `strong-mode` rules are soft deprecated; soon to be for reals deprecated, so we will not be writing documentation for them.

**Comment by parlough** [comment]
I think this can be closed since the strong-mode rules were removed in Dart 3 and the strict language modes are documented in https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks :D

**Comment by parlough** [comment]
I'm going to close this as the replacement strict language modes are documented at https://dart.dev/tools/analysis#enabling-additional-type-checks and https://github.com/dart-lang/sdk/issues/50679 is tracking removing the old `strong-mode` options. 

Please open an issue on [site-www](https://github.com/dart-lang/site-www/issues) if you'd like to see any further improvements to the docs. Thanks!
