### ISSUE TITLE
[ Gardening ] `vm/cc/MoveByteRunTest` crashing on Windows

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#48661]
Failing on various Windows VM kernel configurations.

[Sample logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8818799351553344273/+/u/test_results/new_test_failures__logs_)

**Comment by alexmarkov** [comment]
`vm/cc/MoveByteRunTest` is now passing on all configurations.
