### ISSUE TITLE
Dart SDK 2.16.2 not able to run

### ISSUE THREAD

**Issue by taylorren** [dart-lang/sdk#48663]
I tried to install/upgrade Dart SDK to 2.16.2 using `choco` on my Windows. 

The install and upgrade is good but then `dart` will give me the following error:

```
Failed to start the Dart CLI isolate. Could not resolve DartDev snapshot or kernel.
(null).
```

When I rollback to 2.16.1 using `choco install dart-sdk --version 2.16.1`, everything works fine. 

I am not sure if anyone else has the same issue or is it just me.

**Comment by a-siva** [comment]
//cc @athomas

**Comment by whesse** [comment]
I did a clean install of Dart SDK 2.16.2 on Windows using chocolatey.
There were no problems, and the dart command worked correctly for
me afterwards. I did need to open a new shell, to get dart on my PATH.

I also tried downgrading to 2.16.1, and upgrading again to 2.16.2, and both worked.

I would recommend trying again to upgrade to 2.16.2.

**Comment by athomas** [comment]
Removed the P0 because we can't reproduce the issue.

**Comment by athomas** [comment]
We also checked with the implementation teams, and the differences between `.1` and `.2` are unlikely to cause this particular error message.
