### ISSUE TITLE
dart LSP `textDocument/definition` returns zero width definition location for instances

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/sdk#48677]
Take the following example:

```dart
void main(List<String> args) {
  final m = MyClass();
  final type = MyClass;
}

class MyClass {
  MyClass();
}
```

# VsCode
Flowing to definition (e.g. `Cmd+Click`)
- from `MyClass();` (after `m =`) will put the cursor before `MyClass();` in the second to last line.
- from "MyClass;" (after `type =`) will put the cursor before `MyClass` in the third to last line, and also highlight the entire token.

# Runnable Example
I have put together a small runnable example under https://github.com/ltOgt/lsp_constructor_flow_example.
It uses the above example in `example.dart` and performs `textDocument/definition`.

It uses my work in progress lsp wrapper https://github.com/ltOgt/lsp.
I can understand if you dont want to execute some random code from me, but im sure you have your own tooling to test this.

```dart
import 'dart:io';
import 'package:lsp/lsp.dart';

void main(List<String> args) async {
  // TODO change this
  const String rootPath = "/Users/omni/dart_issues/lsp_constructor_flow/";
  const String exampleFile = rootPath + "lib/example.dart";
  bool ok = File(exampleFile).existsSync();
  if (!ok) return;

  // TODO change this
  const String dartSdkPath = "/Users/omni/development/flutter/bin/cache/dart-sdk/";
  const String analysisPath = dartSdkPath + "bin/snapshots/analysis_server.dart.snapshot";

  final lspConnectorDart = LspConnectorDart(
    analysisServerPath: analysisPath,
    clientId: "example-client",
    clientVersion: "0.0.1",
  );
  final lsp = await LspSurface.start(
    lspConnector: lspConnectorDart,
    rootPath: rootPath,
    clientCapabilities: {},
  );

  final response = await lsp.textDocument_definition(
    filePath: exampleFile,
    // points to "MyClass()" in "m = ..." in example.dart
    line: 1,
    character: 14,
  );
  final start = response.fileLocations.first.range.start;
  final end = response.fileLocations.first.range.end;

  // THIS WILL PRINT OUT "2" and "2" <-----------------------------------------
  print(start.character);
  print(end.character);

  final response2 = await lsp.textDocument_definition(
    filePath: exampleFile,
    // points to "MyClass" in "type = ..." in example.dart
    line: 2,
    character: 18,
  );
  final start2 = response2.fileLocations.first.range.start;
  final end2 = response2.fileLocations.first.range.end;

  // THIS WILL PRINT OUT "6" and "13" <-----------------------------------------
  print(start2.character);
  print(end2.character);
}

```

Edit: I am using `Dart version 2.17.0 (build 2.17.0-239.0.dev)`

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
@bwilkerson @scheglov these regions are computed from the `nameOffset` and `nameLength` on the constructor.

For a _named_ constructor, the `nameOffset`, `nameEnd` and `nameLength` all correspond to the name of the constructor:

```
class AAA {
  AAA.named();
      ^^^^^
}
```

For an unnamed constructor things are a bit different:

```
class AAA {
  AAA();
}
```

- `nameOffset` is at the start of the type name (`^AAA()`)
- `nameLength is 0 (this is not the difference between `nameEnd` and `nameOffset`)
- `nameEnd` is at the end of the type name (`AAA^`)

I can fix this by changing `AnalyzerConverter.locationFromElement` to use `nameEnd - nameOffset` for constructors, but it will affect some tests added in https://github.com/dart-lang/sdk/commit/f67d4b368c38c3d2d89f78b8932c34910b27c581 that are explicitly checking for 0 lengths. I'm not sure if that's ok or if this is a deliberate decision. If allowing non-zero is fine, it's also possible we could remove the special casing in `ConstructorElementImpl.nameOffset` (in the same change above) but that would likely affect more code than use navigation, LSP definition (and `Element` on suggestions, which is the only other place using `AnalyzerConverter.locationFromElement` that I can see).

**Comment by bwilkerson** [comment]
That's terrible. APIs need to be consistent; the length should always be the difference between the offset and the end.

That said, I'm guessing that 'name' was taken to be the name of the constructor (exclusive of the name of the class), which can sometimes be omitted. The question then becomes, what region of text do we use when the name is omitted? I think that the name of the class is the right answer, but we probably used `length == 0` as a test for the unnamed constructor at some point, and that's probably why the API is the way it is.

It would be interesting to change `length` to be consistent and see what breaks. If we're still using `length` for that purpose, then we should change the code to use `isDefaultConstructor` instead. If it's being depended on for something else, then we need to understand what semantics we've conflated with the length of the name.

**Comment by scheglov** [comment]
If a constructor is unnamed, then `nameOffset`, `nameLength`, and `nameEnd` are meaningless. We only have the token of the class name (`AAA` before `()`), and could provide its offset and name. This should be explicit - you simply don't have any `nameOffset`, etc; we should not pretend that some other tokens fill them.

**Comment by DanTup** [comment]
@scheglov 

> This should be explicit - you simply don't have any `nameOffset`, etc; we should not pretend that some other tokens fill them.

Ok, then it sounds like the best fix may be in `AnalyzerConverter.locationFromElement` to special-case unnamed constructors to return the range around the class name. However, I can't find a way from a `ConstructorElement` to get at this range (at least, not without using `nameOffset` and `nameEnd`). There's an `enclosingElement` that points to the class, but that's the whole class and not the class part of the constructor.

Is there something I can use instead of `nameOffset`/`nameEnd`? (as an aside, perhaps those should both return `null` for unnamed constructors?).

@bwilkerson 

> If we're still using length for that purpose, then we should change the code to use `isDefaultConstructor` instead

It looks like `isDefaultConstructor` is not the same as just not having a name, it also check there are no required params:

https://github.com/dart-lang/sdk/blob/838241b02408a920d53ee4e965214303a765bf73/pkg/analyzer/lib/src/dart/element/element.dart#L1456-L1464

So I think for now, code that wants to detect this (such as in `AnalyzerConverter.locationFromElement` if that's where we should fix this) should do `.name.isEmpty`.

**Comment by bwilkerson** [comment]
> If a constructor is unnamed, then `nameOffset`, `nameLength`, and `nameEnd` are meaningless.

I believe your argument is for these getters to only apply to the name, which is fine. It means we need three other getters for the class name (`classNameOffset`, etc.).

> This should be explicit - you simply don't have any `nameOffset`, etc; we should not pretend that some other tokens fill them.

I'm not sure how you're suggesting that we indicate to the user that these values don't exist. I really don't want to make `nameOffset` and `nameLength` nullable for other element classes. Should they `throw` for the unnamed constructor?

> It looks like `isDefaultConstructor` is not the same as just not having a name ...

Then we probably want an `isUnnamedConstructor` that is limited to the form of the name.

**Comment by DanTup** [comment]
To confuse things a little further, `nameEnd` is already nullable and says:

```
/// Return the offset of the character immediately following the last
/// character of this constructor's name, or `null` if not named.
```

However, in my testing unnamed constructors do have a `nameEnd` (`nameOffset` to `nameEnd` spans exactly the class name).

I've a change here that removes the special casing of returning a 0-length when `periodOffset` is `null` and all tests pass, but I don't know if there may be code outside of the server that relied on that behaviour (it seems inconsistent that it didn't match `end`-`offset`.. if it's to remain, I think `offset` should probably be increased to the end of the class name).

https://dart-review.googlesource.com/c/sdk/+/239083/

I haven't added `isUnnamedConstructor` yet as it isn't necessary if we do the above - however if there may be other code checking the zero-length that would need to be updated, I think it may make sense to add anyway.

**Comment by scheglov** [comment]
I think we don't need `isUnnamedConstructor`. We already know that this is a `ConstructorElement`. And the `name` must be `null` for an unnamed constructor.

We might be able to avoid `nameLength` and `nameEnd` at all, because these are computable from `nameOffset` and `name`. IIRC, the only reason we have them is for `LibraryElement`. Which might be not so useful now.

Yes, we need something like `classNameOffset`, although with enhanced enums naming it `class` might be for fully correct. OTOH, I'm not sure how to call it better - `containerNameOffset`?

I think it should be allowed for `name` and `nameOffset` to be absent (as a pair), kind of `nameOffset` being `null`. We use a magic constant `-1`, but it seems to me a vestige of the pre-null-safety world. A nullable value that the type system forces you to check is better than a magic value that you may silently treat as something real.

For a constructor the name related set of properties is something like this:
```dart
class ConstructorElementSelector (Name?) {
  int get periodOffset;
  String get name;
  int get nameOffset;
}

class ConstructorElement ... {
  ConstructorElementSelector? get selector;
  int get containerNameOffset;
}

**Comment by bwilkerson** [comment]
> We might be able to avoid `nameLength` and `nameEnd` at all, because these are computable from `nameOffset` and name. IIRC, the only reason we have them is for `LibraryElement`. Which might be not so useful now.

We need to be able to support operations on named libraries. Please don't remove APIs that provide access to valid information.

> Yes, we need something like `classNameOffset`, although with enhanced enums naming it class might be for fully correct. OTOH, I'm not sure how to call it better - `containerNameOffset`?

Yeah, I can't think of a great name either. I first thought of `parentNameOffset`, but that sounds more like the name offset of the parent (`parent.nameOffset`) rather than the offset of the parent name. Maybe `typeNameOffset`?

> I think it should be allowed for `name` and `nameOffset` to be absent (as a pair), kind of `nameOffset` being `null`.

I'm ok with that.

> We use a magic constant `-1`, but it seems to me a vestige of the pre-null-safety world.

I thought the element model used `-1` the same way the AST nodes do: as an indication that the element is synthetic (not as an indication that the element doesn't have a name).

> We would need `ElementName` anyway, the question is only whether we put it into `Element`, or only into leaf interfaces.

If all elements have the field then it's better for it to be defined on `Element` so that code that operates on an `Element` can access the information directly.

**Comment by DanTup** [comment]
So would something like this work? The `periodOffset` is a bit awkward, because it needs to be set only if the constructor has a name, but it's not normally part of a name.

```dart
class Element {
  // names are optional (eg. unnamed constructor doesn't have one))
  ElementName? get name; 
}

class Constructor extends Element {
  // override type because constructors with names will always have periodOffset
  @override
  TypeNamePrefixedElementName? get name;

  // constructors always have type names
  ElementName get typeName;
}

class ElementName /* ElementNameLocation? */ {
  int get offset;
  int get end;
  int get length => end - offset;
}

class TypeNamePrefixedElementName extends ElementName {
  int get periodOffset;
}
```

And for compatibility, existing `Element` getters something like:

```
class Element {
  @deprecated('Use name.offset')
  int get nameOffset => name?.offset ?? -1;
  @deprecated('Use name.end')
  int get nameEnd => name?.end ?? -1;
  @deprecated('Use name.length')
  int get nameLength => name != null ? name.end - name.offset : 0;
}

class Constructor {
  @deprecated('Use name.offset or typeName.offset')
  int get nameOffset => (name ?? typeName).offset;
  @deprecated('Use name.end or typeName.end')
  int get nameEnd => (name ?? typeName).end;
  @deprecated('Use name.length or typeName.length')
  int get nameLength => (name ?? typeName).length;
}
```

Although if we did this, consumers like the navigation code would still need to handle the difference (eg. use `name ?? typeName` to get the navigation target for a constructor). It could be nice to wrap that up somewhere so given an `Element` you can get a range for it's "name" (where "name" really means "the part the user expects to be the navigation target") without needing to handle `null`s or specific sub-classes (`ElementName get navigationName => name ?? typeName`)?

**Comment by DanTup** [comment]
Sounds reasonable to me (though I suspect the question is mostly for @scheglov).

Outside of the navigation discussed here, what are these nameOffset/etc fields used for? eg., if we decided "that the name of a constructor included both the name of the class and the optional period and other name" and just updated the existing `nameOffset`/etc., what would break (or be worse) as a result?

(I'm not necessarily suggesting we should do that, just curious who else is consumes these values).

**Comment by scheglov** [comment]
The name of the enclosing element is always present in any constructor declaration, so it seems to me that it (its offset) should be a property of `ConstructorElement`.

To avoid saying `name.name`, I propose using the field `id`, with the corresponding changing of the meaning (for setters `id` will not end with `=`). So:
```dart
class ElementName {
  String get id;
  int get offset;
}

class ConstructorElementName extends ElementName {
  int get periodOffset;
}
```

`LibraryElement` is problematic. It does not have one identifier in its name. And I don't like trying to shoehorn not-quite-compatible data into a generic looking interface. So, for libraries we need something like this:
```dart
class LibraryElementName {
  List<LibraryElementNameComponent> components;
}

class LibraryElementNameComponent {
  String get id;
  int get offset;
}
```

This also means that `ElementName` and `LibraryElementName` don't have any common interesting interface. We could declare a common one, e.g. re-purpose `ElementName` and use `SimpleElementName(id, offset)` instead. This empty `ElementName` could be used in `Element`:
```dart
class Element {
  ElementName? /*here the empty one*/ get name;
}
```

Or we could say that `Element` does not have name at all, instead leaf element types have it, e.g.
```dart
class ClassElement extends Element {
  /// Does not override.
  ElementName /*here the one that has id and offset*/ get name;
}
class LibraryElement extends Element {
  LibraryElementName? get name;
}
```

Both approaches for me represent an issue: we need to check for a concrete subclass to know which properties it has. Either directly with `if`, or with a visitor, or with something like `Either`; the last two could enforce exhaustiveness. There are less variants of element names than elements, so the set of `if` statements would be smaller. OTOH, there are "elements" that never have a name, e.g. a closure, so having `ElementName? get name` for these elements is disenginious - it is always `null`.

I'm still leaning toward adding an empty `ElementName? get name` to `Element`.

**Comment by scheglov** [comment]
> > We might be able to avoid `nameLength` and `nameEnd` at all, because these are computable from `nameOffset` and name. IIRC, the only reason we have them is for `LibraryElement`. Which might be not so useful now.
> 
> We need to be able to support operations on named libraries. Please don't remove APIs that provide access to valid information.

  Yes, I checked analyzer and analysis server, and we actually need data about library names. See my proposal about `LibraryElementName`.

> > Yes, we need something like `classNameOffset`, although with enhanced enums naming it class might be for fully correct. OTOH, I'm not sure how to call it better - `containerNameOffset`?
> 
> Yeah, I can't think of a great name either. I first thought of `parentNameOffset`, but that sounds more like the name offset of the parent (`parent.nameOffset`) rather than the offset of the parent name. Maybe `typeNameOffset`?

  Using the word `type` is not quite correct, elements are not types.

> > We use a magic constant `-1`, but it seems to me a vestige of the pre-null-safety world.
> 
> I thought the element model used `-1` the same way the AST nodes do: as an indication that the element is synthetic (not as an indication that the element doesn't have a name).

  You are right, for elements mostly we use `-1` as a sign of a synthetic element. For `ExtensionElement` though we do use `-1` for unnamed extensions. Now we have a chance to correct this.

  It does not seem to me that we use `-1` in AST, it seems that when we create `SyntheticStringToken`, we use some actual offsets, probably of the next present token.

> > We would need `ElementName` anyway, the question is only whether we put it into `Element`, or only into leaf interfaces.
> 
> If all elements have the field then it's better for it to be defined on `Element` so that code that operates on an `Element` can access the information directly.

  Probably, I lean toward this as well, although for some element kinds it might be always `null`.

**Comment by DanTup** [comment]
Sorry for the delay, this got buried in my inbox. The change I made in https://github.com/dart-lang/sdk/commit/7e46465786c094988ac9f790a7d2858035e1b1d9 fixed the original issue, but I don't from the above if we're happy with that (or concerned anything might have been relying on that behaviour).

I can look at making the changes above if that makes sense - although they look quite breaking to me, so I don't know if changes like that need to be carefully timed?
