### ISSUE TITLE
Illegal instruction(4):   dart-sdk build error - dat2js compile error

### ISSUE THREAD

**Issue by qfanr2d2** [dart-lang/sdk#48670]
With the following .gclient.
solutions = [
  {
    "name": "sdk",
    "url": "https://dart.googlesource.com/sdk.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]

I get the code (today March 25, 2022) with: gclient sync    
Then build with:  ./tools/build.py --no-goma --mode release --arch x64 create_sdk

When the build process  crashed when it did the following command
     ...sdks/dart-sdk/bin/dart2js sdk/runtime/observatory/web/main.dart -o 
 ...sdk/out/ReleaseX64/gen/runtime/observatory/observatory/web/main.dart.js

===== CRASH =====
si_signo=Illegal instruction(4), si_code=2, si_addr=0x7f41b0d4f297
version=2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "linux_x64"
pid=8642, thread=8651, isolate_group=main(0x563f7ee35000), isolate=main(0x563f7ee35800)
isolate_instructions=7f41b0bcc000, vm_instructions=563f7c440600
  pc 0x00007f41b0d4f297 fp 0x00007f41ab07d078 Unknown symbol
  pc 0x00007f41b0d52926 fp 0x00007f41ab07d0b0 Unknown symbol
  pc 0x00007f41b0d52439 fp 0x00007f41ab07d0f0 Unknown symbol
  pc 0x00007f41b1b6bffa fp 0x00007f41ab07d1d8 Unknown symbol
  pc 0x00007f41b1b6fc75 fp 0x00007f41ab07d258 Unknown symbol
  pc 0x00007f41b1a821c4 fp 0x00007f41ab07d288 Unknown symbol
  pc 0x00007f41b1b4c2d3 fp 0x00007f41ab07d2e0 Unknown symbol
  pc 0x00007f41b0e35e35 fp 0x00007f41ab07d338 Unknown symbol
  pc 0x00007f41b1b6f904 fp 0x00007f41ab07d398 Unknown symbol
  pc 0x00007f41b1a821c4 fp 0x00007f41ab07d3c8 Unknown symbol
  pc 0x00007f41b1b4c2d3 fp 0x00007f41ab07d420 Unknown symbol
  pc 0x00007f41b0dcfee1 fp 0x00007f41ab07d490 Unknown symbol
  pc 0x00007f41b0dd19e8 fp 0x00007f41ab07d4e0 Unknown symbol
  pc 0x00007f41b0dd21ca fp 0x00007f41ab07d530 Unknown symbol
  pc 0x00007f41b1c777ec fp 0x00007f41ab07d5a0 Unknown symbol
  pc 0x00007f41b0dd1ec8 fp 0x00007f41ab07d600 Unknown symbol
  pc 0x00007f41b1c77609 fp 0x00007f41ab07d660 Unknown symbol
  pc 0x00007f41b1cd7c6a fp 0x00007f41ab07d6b8 Unknown symbol
  pc 0x00007f41b0ddd9a4 fp 0x00007f41ab07d728 Unknown symbol
  pc 0x00007f41b197b5c1 fp 0x00007f41ab07d770 Unknown symbol
  pc 0x00007f41b1c7b5dc fp 0x00007f41ab07d7b8 Unknown symbol
  pc 0x00007f41b0dd1ec8 fp 0x00007f41ab07d818 Unknown symbol
  pc 0x00007f41b1c7b10e fp 0x00007f41ab07d868 Unknown symbol
  pc 0x00007f41b1cd88aa fp 0x00007f41ab07d8c0 Unknown symbol
  pc 0x00007f41b0ddd9a4 fp 0x00007f41ab07d930 Unknown symbol
  pc 0x00007f41b197bbbb fp 0x00007f41ab07d988 Unknown symbol
  pc 0x00007f41b197c318 fp 0x00007f41ab07d9d8 Unknown symbol
  pc 0x00007f41b197d189 fp 0x00007f41ab07da90 Unknown symbol
  pc 0x00007f41b197dd51 fp 0x00007f41ab07db40 Unknown symbol
  pc 0x00007f41b1993c73 fp 0x00007f41ab07dbd0 Unknown symbol
  pc 0x00007f41b0d342c9 fp 0x00007f41ab07dc48 Unknown symbol
  pc 0x00007f41b0d345dc fp 0x00007f41ab07dcb0 Unknown symbol
  pc 0x00007f41b1b9d196 fp 0x00007f41ab07dd48 Unknown symbol
  pc 0x00007f41b1b9d39e fp 0x00007f41ab07dd98 Unknown symbol
  pc 0x00007f41b1b9ee0e fp 0x00007f41ab07ddf8 Unknown symbol
  pc 0x00007f41b1b9e6bf fp 0x00007f41ab07de78 Unknown symbol
  pc 0x00007f41b1a61a4b fp 0x00007f41ab07dec0 Unknown symbol
  pc 0x00007f41b1d1bdf5 fp 0x00007f41ab07df00 Unknown symbol
  pc 0x00007f41b1993609 fp 0x00007f41ab07dfa0 Unknown symbol
  pc 0x00007f41b0d342c9 fp 0x00007f41ab07e018 Unknown symbol
  pc 0x00007f41b0d345dc fp 0x00007f41ab07e080 Unknown symbol
  pc 0x00007f41b1b9d196 fp 0x00007f41ab07e118 Unknown symbol
  pc 0x00007f41b1b9d39e fp 0x00007f41ab07e168 Unknown symbol
  pc 0x00007f41b1b9ee0e fp 0x00007f41ab07e1c8 Unknown symbol
  pc 0x00007f41b1b9e6bf fp 0x00007f41ab07e248 Unknown symbol
  pc 0x00007f41b1a61a4b fp 0x00007f41ab07e290 Unknown symbol
  pc 0x00007f41b1d1bdf5 fp 0x00007f41ab07e2d0 Unknown symbol
  pc 0x00007f41b1992df5 fp 0x00007f41ab07e370 Unknown symbol
  pc 0x00007f41b0d342c9 fp 0x00007f41ab07e3e8 Unknown symbol
  pc 0x00007f41b0d345dc fp 0x00007f41ab07e450 Unknown symbol
  pc 0x00007f41b1b9d196 fp 0x00007f41ab07e4e8 Unknown symbol
  pc 0x00007f41b1b9d39e fp 0x00007f41ab07e538 Unknown symbol
  pc 0x00007f41b1b9ee0e fp 0x00007f41ab07e598 Unknown symbol
  pc 0x00007f41b1b9e6bf fp 0x00007f41ab07e618 Unknown symbol
  pc 0x00007f41b1a61a4b fp 0x00007f41ab07e660 Unknown symbol
  pc 0x00007f41b1ba038d fp 0x00007f41ab07e6a0 Unknown symbol
  pc 0x00007f41b1ba2ea1 fp 0x00007f41ab07e710 Unknown symbol
  pc 0x00007f41b1ba3079 fp 0x00007f41ab07e770 Unknown symbol
  pc 0x00007f41b0d34fa3 fp 0x00007f41ab07e800 Unknown symbol
  pc 0x00007f41b1ba3330 fp 0x00007f41ab07e850 Unknown symbol
  pc 0x00007f41b1ba8a13 fp 0x00007f41ab07e898 Unknown symbol
  pc 0x00007f41b1ba948b fp 0x00007f41ab07e8d8 Unknown symbol
  pc 0x00007f41b1ba96a9 fp 0x00007f41ab07e900 Unknown symbol
  pc 0x00007f41b1d1bc5e fp 0x00007f41ab07e940 Unknown symbol
  pc 0x00007f41b1d1c7c8 fp 0x00007f41ab07e980 Unknown symbol
  pc 0x00007f41b07029af fp 0x00007f41ab07e9f8 Unknown symbol
  pc 0x0000563f7c5b5f13 fp 0x00007f41ab07eaa0 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x153
  pc 0x0000563f7c5b5d4c fp 0x00007f41ab07eb00 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x14c
  pc 0x0000563f7c5b82bf fp 0x00007f41ab07eb50 dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&)+0x16f
  pc 0x0000563f7c5defb4 fp 0x00007f41ab07ec30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x374
  pc 0x0000563f7c606e5c fp 0x00007f41ab07eca0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x14c
  pc 0x0000563f7c60755f fp 0x00007f41ab07ecf0 dart::MessageHandler::TaskCallback()+0x1df
  pc 0x0000563f7c71f018 fp 0x00007f41ab07ed80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x138
  pc 0x0000563f7c71f4ac fp 0x00007f41ab07edb0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
-- End of DumpStackTrace

**Comment by a-siva** [comment]
I tried to reproduce the same this morning and was able to build successfully without any issues.

Can you do an 'rm -fr out/ReleaseX64' on your system, that is delete the out directory and try again.

**Comment by qfanr2d2** [comment]
> I tried to reproduce the same this morning and was able to build successfully without any issues.
> 
> Can you do an 'rm -fr out/ReleaseX64' on your system, that is delete the out directory and try again.

After I removed the out/ReleaseX64, I tried the build again. I got same crash at
[549/3293] ACTION //runtime/observatory:build_observatory(//build/toolchain/linux:clang_x64)
FAILED: gen/runtime/observatory/observatory/web/main.dart.js

is it caused by my computer?  It is an old amd CPU:  AMD Athlon(tm) II X2 220 Processor

**Comment by qfanr2d2** [comment]
I can build the sdk with the Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz

**Comment by alexmarkov** [comment]
@qfanr2d2 Could you run the failed build command under `gdb` and figure out which instruction is illegal on your CPU?

**Comment by qfanr2d2** [comment]
> @qfanr2d2 Could you run the failed build command under `gdb` and figure out which instruction is illegal on your CPU?

It is the roundsd instruction.  
 0x7ffff34a2297:      roundsd $0xb,%xmm0,%xmm1

Here is  the cpu infomation.

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          16
Model:               6
Model name:          AMD Athlon(tm) II X2 220 Processor
Stepping:            3
CPU MHz:             800.000
CPU max MHz:         2800.0000
CPU min MHz:         800.0000
BogoMIPS:            5625.67
Virtualization:      AMD-V
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save

**Comment by mraleph** [comment]
@alexmarkov I think this was fixed by b80e682cbf313691650cc9c45302811deb710aa0 but checked in SDK which is used for the build has not been updated to include the fix.

**Comment by athomas** [comment]
Checked-in SDK upgrade: https://dart-review.googlesource.com/c/sdk/+/239065/
