### ISSUE TITLE
`const` keyword before constructors not identified by LSP.

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/sdk#48676]
Take the following example
```dart
class MyClass {
  // "const" is "Other", and not even contained in the token data
  const MyClass();
  // "const" is "keyword", and contained in the token data
  static const int i = 1;
}
```

As can be examined e.g. through the use of VSCodes `>Developer: Inspect Editor Tokens and Scopes` mode, the dart LSP does not recognise the `const` keyword before the `MyClass` constructor in its Semantic Tokens returned through `textDocument/semanticTokens/full`.

- `const` before constructor
<img width="415" alt="image" src="https://user-images.githubusercontent.com/24209580/160286109-88aad1f4-d113-41b5-939e-74200e317dd0.png">

- `const` before static `i`
<img width="439" alt="image" src="https://user-images.githubusercontent.com/24209580/160286102-c6f00afd-850c-459e-9ed5-a34d86e1e0a2.png">
 
I am using `Dart version 2.17.0 (build 2.17.0-239.0.dev)`

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
Thanks! I've opened a fix at https://dart-review.googlesource.com/c/sdk/+/239027/.

<img width="508" alt="Screenshot 2022-03-28 at 10 55 32" src="https://user-images.githubusercontent.com/1078012/160374014-f64cf9f7-c9b9-4d64-b43c-1d2b7ede940f.png">
