### ISSUE TITLE
It is hard to know which stream has already been listened to

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/sdk#48671]
When the state error: `"Stream has already been listened to."` is thrown, it is sometimes hard to find which stream is the root cause. In my case the stack trace did not add much information when running flutter integration tests (it did when running unit tests however).

Including the generic type in the error could already furnish some information

`"Stream<${T.runtimeType}> has already been listened to."`

It's not enough though. Maybe saving the stack trace upon creation of the stream controller and outputting the definition file in the error description be a solution?

**Comment by lrhn** [comment]
I don't think adding more overhead at runtime is something we want to do unless the benefit definitely outweighs the cost.
Storing entire stack traces speculatively is unlikely to be anywhere close to efficient.

Reifying type names as strings sounds expensive in code size for AoT compiled code (web in particular). If anything, I'd want to get rid of type names entirely at runtime (but maybe combined with debugging information, so you can reinsert the type name offline).

We could make the error message more detailed in "debug mode" (when assertions are enabled). That risks test code and production code having different behavior, which again risks the tests not actually catching the production-code errors. Possible, but something I prefer to avoid if I can.

That leaves giving users the ability to attach debugging information to streams. Somehow.

We could just add a `String` field to `Stream` with a "name" that you can ask for, and which defaults to `null`.
That adds a field to every stream (not every stream-controller, not all streams have controllers, for example the streams defined by an `async*` function), which is still a memory overhead. 
We could use an `Expando` instead. Then it's basically free if you don't use the feature.

Maybe we should just embed the `Stream` object in the `StateError` object, as an optional `state` field in `StateError`. Then you can catch the `StateError` and do whatever you want with the extra object.

**Comment by cedvdb** [comment]
Async errors are often hard to debug in general. What about a solution that is more generalized than just for this case then ?

Something like an AsyncStackTrace.  Node has something like this, I'm not sure how much it can be translated here

https://docs.google.com/document/d/13Sy_kBIJGP0XT34V1CV3nkWya4TwYx9L3Yv45LdGB6Q/edit

**Comment by lrhn** [comment]
You can use the [stack_trace](https://pub.dev/packages/stack_trace) package to automatically capture stack traces where a stream is listened to (where the callback is created at least). It just comes with a significant overhead, so you might not want to use it in production.

**Comment by cedvdb** [comment]
Thanks, I'm actually already using it but the original error happened in an integration test, which did not have sufficient stack trace. I guess this is more related to integration testing than the sdk.  If adding the runtime type of the generic is not an option I guess I'll close this.

**Comment by cedvdb** [comment]
This is a wild idea, but would it be possible for the compiler to reach the variable name / property / getter, or whatever information it can find and attach it to the stream ? 

I'm thinking static meta programming here, where the definition of a stream, eg in the dart sdk, would use a macro that would analyze the call site ? I'm assuming the answer is no here.
