### ISSUE TITLE
No warning for named break used incorrectly?

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#48685]
https://dartpad.dev/?id=cbdec4750cae0edda85029d894c804d5

```dart
enum Thing {
  one,
  two,
}

void main() {
  var thing = Thing.one;
  goback:
  switch (thing) {
    case Thing.one:
      print("one");
      thing = Thing.two;
      break goback;
    case Thing.two:
      print("two");
      break;
  }
}
```

I ran into this this weekend.  There are no lints or warnings, but the above only ever prints "one".    I think named breaks only work for loops?

I wasn't able to find any docs on named breaks, which maybe is its own separate bug?

**Comment by eseidelGoogle** [comment]
I have package:lint (v 1.0.1) with recommended lints enabled.  I'm using whatever the current Flutter master has for Dart, it was 2.17.dev. or so.

**Comment by eseidelGoogle** [comment]
Probably something close to:
Dart SDK version: 2.17.0-246.0.dev (dev) (Sun Mar 27 12:20:08 2022 -0700) on "macos_arm64"

**Comment by lrhn** [comment]
A labeled break works for any labeled statement, so this is working as intended.

The break *exits* the labeled statement (the `switch` statement here), so for a labeled loop or switch, it works exactly like an unlabeled break would.

If you want to continue to the "two" case, you can use a `continue` to a labeled switch case:
```dart
void main() {
  var thing = Thing.one;
  switch (thing) {
    case Thing.one:
      print("one");
      continue thing_two;
    thing_two:
    case Thing.two:
      print("two");
      break;
  }
}
```
