### ISSUE TITLE
dynamic undefined behaviour

### ISSUE THREAD

**Issue by subzero911** [dart-lang/sdk#48684]
Copy-paste the following snippet into DartPad:

```dart
void main() {  
  final result = baz() + 1;   
  print(result);  
}

baz() {
  return 'abc';
}
```

**Expected behaviour:** it compiles, but runtime error
**Actual behaviour:** no runtime error, but nothing is printed!

(i didn't test it in IDE though, it may be a DartPad bug)

**Comment by asashour** [comment]
It is fine, when I try it:

![image](https://user-images.githubusercontent.com/2410127/160422286-4794e1ae-8710-4feb-835c-c7604e0e594c.png)
