### ISSUE TITLE
analyzer should warn about final super parameters

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48699]
```dart
class Base {
  Base(this.value);
  final int value;
}

class Extended extends Base {
  Extended(final super.value); // note the incorrect final here
}
```

The analyzer doesn't think anything is wrong with this code, but when I execute it, I get the following error:

```
Error: Can't have modifier 'final' here.
Try removing 'final'.
  Extended(final super.value);
           ^^^^^
```

The analyzer should tell me about this problem while I write the code so I can correct it before running my program.

(This was discovered while debugging https://github.com/dart-lang/sdk/issues/48698)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Why? Is it specified somewhere?
I see that `const`, `late` and `var` are disallowed.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/384794/160749500-52560d28-3f0d-45d2-bb2c-bb6b13bfd33b.png">

And the super-formal parameters [specification](https://github.com/dart-lang/language/blob/master/working/1855%20-%20super%20parameters/proposal.md#semantics) also mentions `var`, `super` and `late`.

But in the language specification I see `finalConstVarOrType` in `fieldFormalParameter`, so I guess `final` is allowed.

And this code works fine in VM.
```dart
class A {
  final int value;
  A(final this.value);
}

void f(final int value) {}

main() {}
```
So, I don't see why it should not work for `super.name`.
@lrhn

**Comment by eernstg** [comment]
A super parameter is already final, so `final` should be benign, but redundant. I don't see any rules against it.

**Comment by pq** [comment]
> A super parameter is already final, so final should be benign, but redundant

We could definitely consider linting or hinting for this.  My preference would be to make it a hint I guess but maybe I'm missing a reason someone might value this redundancy?

**Comment by goderbauer** [comment]
If final is allowed there, why does it give a runtime error? Should that error be removed then as well?

**Comment by bwilkerson** [comment]
Yes, it's a bug that you got a runtime error.

It's effectively dead code, so a hint seems reasonable to me.

**Comment by eernstg** [comment]
> why does it give a runtime error?

Wouldn't that be a compile-time error from the vm, rather than an actual run time error? If this is true then it should be reported as an issue on the common front end.

**Comment by asashour** [comment]
I understood there is a new issue to be created for the `CFE`, while this issue is for the analyzer to have a `hint`.

I am also under the impress that this should also be applied to `FieldFormalParameter`, since it has the same behavior.

Please look into https://dart-review.googlesource.com/c/sdk/+/239640

**Comment by eernstg** [comment]
Perhaps the error message from the CFE was emitted by some earlier version? I don't see it with the current CFE, not for a formal of the form `final super.x` and also not for `final this.x`.

**Comment by asashour** [comment]
Please try:

```dart
class Base {
  Base(this.value);
  final int value;
}

class Extended extends Base {
  Extended(final super.value); // note the incorrect final here
}

void main() {
  Extended(5);
  print('hi');
}
```

There is:

```
lib/b.dart:7:12: Error: Can't have modifier 'final' here.
Try removing 'final'.
  Extended(final super.value); // note the incorrect final here
           ^^^^^
```


`Dart SDK version: 2.17.0-251.0.dev (dev) (Tue Mar 29 00:56:13 2022 -0700) on "windows_x64"` (from Flutter `master`)

**Comment by eernstg** [comment]
Right, I do get the error, with a bleeding edge `dart` from ac19f520543c0df766eff24cd85409af49416b47. So it must be a quite recent change.
