### ISSUE TITLE
autofix for use_super_params has trouble with "final"

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48698]
The autofix for use_super_params is correcting the following code...

```dart
class Base {
  Base(this.value);
  final int value;
}

class Extended extends Base {
  Extended(final int value) : super(value);
}
```

... to ...

```dart
class Base {
  Base(this.value);
  final int value;
}

class Extended extends Base {
  Extended(final super.value); // note the incorrect final here
}
```

When running this code, I get the following error:

```
Error: Can't have modifier 'final' here.
Try removing 'final'.
  Extended(final super.value);
           ^^^^^
```

The autofix should have removed the "final" here.

(And I also would have expected the analyzer to complain about the incorrectly left behind "final" - instead of just getting an error when executing the program. Filed https://github.com/dart-lang/sdk/issues/48699 for that.)

**Comment by goderbauer** [comment]
There's some discussion over at https://github.com/dart-lang/sdk/issues/48699 whether the final keyword is actually allowed in the context or not...

I still believe the autofix should remove it since there is agreement that it is redundant.

**Comment by bwilkerson** [comment]
I agree that we should remove it.
