### ISSUE TITLE
Failures on  [anlaysis_server] Add support for LSP's Go-to-Type Definition

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#48701]
There are new test failures on [anlaysis_server] Add support for LSP's Go-to-Type Definition

The new test compares a file URI to "file:///src/..." but on Windows the file URI starts with "file:///C:/src"

Log: https://dart-ci.appspot.com/log/any/analyzer-unittest-asserts-release-win/18419/pkg/analysis_server/test/lsp/type_definition_test

The tests
```
pkg/analysis_server/test/lsp/type_definition_test RuntimeError (expected Pass)
```
are failing on configurations
```
analyzer-unittest-asserts-release-win
```

**Comment by DanTup** [comment]
Thanks! I've opened a fix at https://dart-review.googlesource.com/c/sdk/+/239314/.
