### ISSUE TITLE
RISC-V 64 build failing due to `-fno-strict-vtable-pointers`

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#48703]
The RISC-V 64 build currently (d2d83df1f2c49649ed4e42b09d66576663f9588e) fails with:
```
riscv64-linux-gnu-g++: error: unrecognized command-line option '-fno-strict-vtable-pointers'; did you mean '-fno-omit-frame-pointer'?
```

Reproducible locally with:
```
tools/build.py '--sanitizer=none' -ariscv64 -mrelease --no-clang --use-qemu dart_precompiled_runtime runtime --no-start-goma -j200
```

**Comment by cskau-g** [comment]
@rmacnak-google are you the right person to have a look at this?

**Comment by cskau-g** [comment]
FWIW, it builds locally if I replace:
https://github.com/dart-lang/sdk/blob/c78ef90124dfb84215805a19eb91783b0f7ef7e9/runtime/BUILD.gn#L206-L207
with
```python
    if (dart_target_arch != "riscv32" && dart_target_arch != "riscv64") {
      cflags += [
        "-fno-strict-vtable-pointers",  # Handle assignment updates vtable
                                        # pointers.
      ]
    }
```
But I don't know if we can just drop that flag, or if there is a replacement for `riscv64-linux-gnu-g++`.

**Comment by rmacnak-google** [comment]
(Though also note the RV QEMU bot doesn't work currently because the Ubuntu version is too old for QEMU to have RV support. The steps do work locally.)
