### ISSUE TITLE
Abi class isn't mentioned in changelog

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#48711]
It looks like `dart:ffi` added an `Abi` class in 2.16.0, but it's not mentioned in the changelog. Documenting all new and changing APIs in the changelog is crucial for ensuring that package authors know how to correctly version their packages.

**Comment by lrhn** [comment]
It also seems like very `dart:ffi` declaration needs a `@Since("2.xx")` annotation.

You can add the first release to the `ffi.dart` library itself, as `@Since("2.yy") library dart.ffi;`, but all later additions should have individual annotations for the version they were introduced in.

**Comment by dcharkes** [comment]
Thanks for reporting.

Will address in:
https://dart-review.googlesource.com/c/sdk/+/240045
https://dart-review.googlesource.com/c/sdk/+/240047
