### ISSUE TITLE
dart.server.vm.options and Observatory

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#48712]
We used to be able to provide `dart.server.vm.options` in IntelliJ `Registry...` to specify Observatory flags, like `--observe:8181 --pause_isolates_on_unhandled_exceptions=false --disable-service-auth-codes`. But it seems that this stopped working, probably because we run now `language-server`? What is the way to pass VM options now?

**Comment by bkonyi** [comment]
I'm OOO until next week. Maybe @rmacnak-google can take a look?

**Comment by scheglov** [comment]
BTW, maybe not everyone saw it, but when I pass `--no_dds` in addition to `--observe:8181`, I can connect to Observatory.

**Comment by jwren** [comment]
Updating documentation and closing out this issue.

**Comment by DanTup** [comment]
> when I pass `--no_dds` in addition to `--observe:8181`, I can connect to Observatory.

That's my current workaround too (see https://github.com/dart-lang/sdk/issues/47880#issuecomment-1087424523), although right now DevTools can't be connected to the VM Service that way (so if Observatory goes away, this might make it more difficult to get CPU profiles etc. this way). There's a related issue at https://github.com/flutter/devtools/issues/3099.
