### ISSUE TITLE
CFE does not set `isSetter` on Field nodes for enhanced enums with static setters.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#48710]
Snippet:
```
// SharedOptions=--enable-experiment=enhanced-enums

import "package:expect/expect.dart";

enum E1 {
  e1,
  e2,
  e3;

  static void set e1(E1 val) {
    Expect.equals(E1.e2, val);
  }
}

enum E2<T> {
  e1<int>(42),
  e2<String>("42"),
  e3<bool>(false);

  const E2(T t);
  static void set e1(E2<int> val) {
    Expect.equals(E2.e1, val);
  }
  static void set e2(E2<String> val) {
    Expect.equals(E2.e2, val);
  }
  static void set e3(E2<bool> val) {
    Expect.equals(E2.e3, val);
  }
}

main() {
  E1.e1 = E1.e2;
  E2.e1 = E2.e1;
  E2.e2 = E2.e2;
  E2.e3 = E2.e3;
}
```

Iterating through the kernel `Field` nodes, `E1.e1` should set both `hasGetter` and `hasSetter` to `true` but currently only sets the implicit `hasGetter`. 

Also see: https://github.com/dart-lang/sdk/issues/48700

**Comment by johnniwinther** [comment]
The `Field.hasSetter` is set if the field is mutable, i.e. it has an implicit setter, _not_ if there exists a corresponding setter. And there is nothing different the encoding of enum enhanced from what would have been generated for
```Dart
class A {
  static const int field = 0;
  static void field(int value) {}
}
```

Can you point to the code in DDC that uses this property?

**Comment by Markzipan** [comment]
Thanks, Johnni! It turns out that DDC doesn't support static setters on const fields at all! 

DDC emits static fields lazily via `Field.initializer` in one pass, then emits the `Procedure`s in another pass (non-lazily). I'll add some logic to associate static/const field names with procedures with the same name.

In DDC this logic sits here: https://github.com/dart-lang/sdk/blob/main/pkg/dev_compiler/lib/src/kernel/compiler.dart#L1326

**Comment by Markzipan** [comment]
Fixed (see issue linked above)
