### ISSUE TITLE
constant constructor parameters

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#48726]
With a code like

```dart
class A {
  const A(int i);
}
```

I wonder if there is a point of this parameter, since it isn't accessible, and `const` constructor can't have a body.

**Comment by bwilkerson** [comment]
See the lint `avoid_unused_constructor_parameters`. I haven't tested it, but I think it will catch this case.

**Comment by devoncarew** [comment]
@asashour - are you reporting a bug here or asking a question? Can you update the title to reflect which it is?

**Comment by asashour** [comment]
@devoncarew sure, but I needed some time to check the answer.

Closing as the lint is actually handling the case.
