### ISSUE TITLE
No code completions on this. in enum constructors

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#48724]
## Repro steps

1. Use a 2.17 SDK
2. Create a project with a 2.17 lower constraint (e.g. `2.17.0-0`)
3. Add this to main.dart:
   ```
   enum Water {
     frozen(32);

     final int temperatureInFahrenheit;
     const Water();
   }
   ```
4. Inside `Water(` type `this.` and hit tab

## Expected result

Code completion for `temperatureInFahrenheit`.

## Actual result

No code completion.

**Comment by mit-mit** [comment]
cc @scheglov @bwilkerson

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/239736
