### ISSUE TITLE
body_might_complete_normally triggers on function with exhaustive switch

### ISSUE THREAD

**Issue by dowski** [dart-lang/sdk#48728]
Dart SDK 2.16.2

```
The body might complete normally, causing 'null' to be returned, but the return type,
'String', is a potentially non-nullable type.
```

This seems to happen if the `case` clause terms have parentheses around them. See [this DartPad](https://dartpad.dev/?id=ea296aacf5cc1ccae7190771116994fd) for an example.

If the parentheses around each `case` term are removed, the analyzer doesn't complain anymore.

**Comment by bwilkerson** [comment]
@srawlins @scheglov 

Also, that's a suboptimal message. Can we specialize the message in the case where we know that the return type is actually non-nullable (and not just potentially non-nullable)?

**Comment by scheglov** [comment]
AFAIK enum exhaustiveness check is syntactic.
https://dart-review.googlesource.com/c/sdk/+/239841

**Comment by asashour** [comment]
Shouldn't this be closed?
