### ISSUE TITLE
Dart + LLVM / Improving Dart's performance?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#48722]
Hi thanks for the wonderful language and sdk! I am interested in improving the performance of Dart. Is Dart welcomed for contributions? Are there some introductory level doc to learn?

By the way, I see an article in 2020 (https://zhuanlan-zhihu-com.translate.goog/p/189411332?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp) mentioned:

> Although the Dart AOT product has been optimized to the extreme, making its running performance comparable to that of old-fashioned languages ​​such as Java and C++, there is still room for optimization in the entire compilation pipeline. By transforming the Dart compiler and using the LLVM compiler to generate small code size and high performance, we can effectively reduce the size of the engine product and improve the code running performance.
> At present, arm32 and arm64 have passed all tests and are entering the final optimization stage, and they will be available for use soon.
> At present, the official is also paying attention to the optimization work of our compiler, hoping to contribute to the community after the effect is achieved.

So I wonder how is the progress? Will Dart have LLVM in the future?

**Comment by mraleph** [comment]
You should address this question to Alibaba team. Their most recent update is [here](https://mp.weixin.qq.com/s?__biz=MzUzMjk2ODM1MA==&mid=2247484736&idx=1&sn=c080c85e8eab7152eccc599170613770&chksm=faaa63b1cdddeaa782aee05d96d733623cb4d52f26670b41ab2e9dbf63301aee4995c070fe00&scene=178&cur_album_id=2315269791693144067#rd). 

We have evaluated LLVM before, including [evaluating](https://docs.google.com/document/d/15OVvpYKFrvv-nX1CoeO-aXCgjiA38jLh_dGt9Qa8Gnw/view) Alibaba's LLVM backend described in these articles, and don't think taking dependency on LLVM is warranted. We plan to continue monitoring this - including take another look at Alibaba's work.

**Comment by fzyzcjy** [comment]
Thanks for the reply!
