### ISSUE TITLE
[CP] Cherry pick fix for enum code completions to beta

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#48739]
**commit(s) to merge**: https://github.com/dart-lang/sdk/commit/54af2c5fd1c54025196bd3a63b09c13ead817ed9

**merge instructions**: clean merge or patch CL

**What is the issue**: Code completions don't work in the 2.17 enums feature

**What is the fix**: Brief description of the fix

**Why cherrypick**: New feature with significant issue

**Risk**: TBD

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/48724

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by whesse** [comment]
Merged in 2.17.0-266.5.beta.
