### ISSUE TITLE
RTCPeerConnection missing connectionState property

### ISSUE THREAD

**Issue by cterefinko** [dart-lang/sdk#48735]
[html_dart2js](https://raw.githubusercontent.com/dart-lang/sdk/main/sdk/lib/html/dart2js/html_dart2js.dart) is missing the native js property [connectionState](https://www.w3.org/TR/webrtc/#dom-peerconnection-connection-state) and an [onConnectionStateChange](https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-onconnectionstatechange) handler for RTCPeerConnection.

**Comment by Markzipan** [comment]
Pinging @srujzs

**Comment by srujzs** [comment]
I think this is possibly a simple fix, but haven't dug much into it yet. It seems like we need to add that property and create a separate static `EventStreamProvider` for `connectionstatechange`. It seems like it should be possible to workaround this with interop, however, using `js_util` and `addEventListener`.

**Comment by cterefinko** [comment]
Since I'd like to to update [dart-webrtc to use these](https://github.com/flutter-webrtc/dart-webrtc/issues/10), I think it'd be nice to not have to use interop.

I sent out https://dart-review.googlesource.com/c/sdk/+/240240 for review, but it was unclear to me if there was anything else that needed to be updated.
