### ISSUE TITLE
[CP] DevTools related cherry pick request for Dart 2.17

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#48753]
This cherry pick request is to roll the DevTools version in the SDK from 2.12.1 to 2.12.2. User risk is low. 

[commit to cherry pick] This is the SDK commit that bumps the DEPS version for DevTools to 2.12.2: https://github.com/dart-lang/sdk/commit/2badd2e71eaeb5c6b24005af5005fe1220ce21a9

Here is a diff DevTools 2.12.1 vs 2.12.2: https://github.com/flutter/devtools/compare/v2.12.1...v2.12.2.

DevTools 2.12.2 contains 3 functional commits that
- fix a breakage where traces will not be rendered properly with Track Widget Builds enabled (see https://github.com/flutter/flutter/issues/101379 for details)
- fix a bug preventing the inspector from loading the widget tree

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew

**Comment by devoncarew** [comment]
cc @itsjustkevin
