### ISSUE TITLE
[CP] cherry pick fixes to pub

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#48759]
**commit(s) to merge**: 557089ea5d784b9664b3e896795e81e8c580912e

**merge instructions**: clean merge

**What is the issue**: Recent regressions in pub.

https://github.com/dart-lang/pub/issues/3379
https://github.com/dart-lang/pub/issues/3381

**What is the fix**: 
Updating the DEPS file for pub.

Changes including in deps update:
```
> git log --format="%C(auto) %h %s" a3a102a..a949b32
 https://dart.googlesource.com/pub.git/+/a949b329 Fix handling of ['git@github.com](mailto:'git@github.com):dart-lang/pub.git' style urls in git source ([#3381](https://github.com/dart-lang/pub/issues/3381))
 https://dart.googlesource.com/pub.git/+/c6cd3758 Always use forward slash for relative paths in lockfile ([#3379](https://github.com/dart-lang/pub/issues/3379))
 https://dart.googlesource.com/pub.git/+/7d48f902 Remove unused function ([#3370](https://github.com/dart-lang/pub/issues/3370))
 https://dart.googlesource.com/pub.git/+/b1373d4c Fix import prefix ([#3369](https://github.com/dart-lang/pub/issues/3369))
```

**Why cherrypick**:
 * Pub will be degraded otherwise
 * **git-dependencies using SSH will not work**, this a regression, and will affect many people with dependency on private git-repository.

**Risk**: small

/cc @mit-mit @whesse @athomas @vsmenon @kevinjchisholm

**Comment by mit-mit** [comment]
Are any of those four listed issues regressions (i.e. new issues not present in 2.16 stable)?

**Comment by jonasfj** [comment]
I think these two are regressions:
 * https://dart.googlesource.com/pub.git/+/a949b329, this one being particularly bad, it would affect anyone using git-dependencies with SSH.
 * https://dart.googlesource.com/pub.git/+/c6cd3758

**Comment by sigurdm** [comment]
The others are minor fixes to pub that went in the same roll (remove a dead-function and remove a no-longer-needed import prefix).

We see it as higher risk to make a special cherry pick without those commits than just leaving them in.
