### ISSUE TITLE
[CP] Cherrypick CFE FutureOr nullability fixes to Dart 2.17

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#48763]
**commit(s) to merge**: 7d8d3bb8078a3f0ce9a2a41f2120ff7db75ce0df

**merge instructions**: clean merge

**What is the issue**: Undetermined nullability for FutureOr types was leaking through the CFE into our backends (detected first in DDC), as reported by Flutter users.

**What is the fix**: CFE-side fixes in type substitution.

**Why cherrypick**: This is causing problems right now for some Flutter web users (e.g., consumers of https://pub.dev/packages/riverpod). 

**Risk**: Little

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/48631

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew @sigmundch @nshahan

**Comment by sigmundch** [comment]
I'm in favor of including this as part of 2.17 - the change is fairly small (most of the CL are tests, only 10 LOC of actual change), and it addresses an issue that is being hit by flutter web users.

@johnniwinther @leafpetersen - what do you think?

**Comment by johnniwinther** [comment]
LGTM

**Comment by athomas** [comment]
Merged to beta in e5fa9de3e4025b0a6769f042cfb81120ee9659c9 (2.17.0-266.7.beta).
