### ISSUE TITLE
Stack data structure as part of dart:collection or dart:core

### ISSUE THREAD

**Issue by Farial-mahmod** [dart-lang/sdk#48773]
It would be great if Stack can be used from dart:collection as Queue, HashMap etc or from dart:core like List . Kindly, add Stack in Dart language without depending on third-party packages as Java .

**Comment by lrhn** [comment]
The Dart growable `List` is a perfectly good stack, so we haven't bothered adding another stack as well.
It has `add`, `isEmpty` and `removeLast`, which is all a stack needs, so `final myStack = <String>[];`  should work.

Also, the `Queue` data structure is actually a *double-ended* queue, so it can also be used as a stack, with `add`, `isEmpty` and `removeLast` methods as well.

Adding a separate stack would be superfluous, and would likely just be wrapping a `List` anyway.
