### ISSUE TITLE
What is the general organization of the Dart2JS code in the Dart SDK?

### ISSUE THREAD

**Issue by lancejpollard** [dart-lang/sdk#48777]
The outline of the compiler can be found [in the README](https://github.com/dart-lang/sdk/tree/5c2ca380a48a4599bec55ad3b057a9b18bb3a0a3/pkg/compiler#the-dart2js-compiler). How does it map to specific files though, in the compiler source code? The end of the readme starts on some aspects, but I am missing the rubber hitting the road part.

That is, what is a quick rundown of what the key folders/files are in [pkg/compiler/lib/src](https://github.com/dart-lang/sdk/tree/5c2ca380a48a4599bec55ad3b057a9b18bb3a0a3/pkg/compiler/lib/src)? I have been looking through the `js_emitter` and `js_x` related source code in the compiler, but have yet to find _where the rubber hits the road_. Where does the actual output JS file generation occur, so I can work my way backwards and see all the steps to generate the output file(s)?

Does dart generate a JS AST (or CST)? Or does it just write text as it encounters something else (like the "model")?

Also, why are there two tree-shaking phases? Can you explain the rationale behind the compiler phases in more depth? The readme lists the purpose of some of the parts of the compiler, but not really the rationale.

**Comment by fishythefish** [comment]
The README does provide a high-level outline of the codebase, but it hasn't been maintained regularly for years now. (See the [history](https://github.com/dart-lang/sdk/commits/1e799e158082f59dea5a139691993a0e7af5b70a/pkg/compiler/README.md).) Towards the bottom of the README, there's a section on code layout. It doesn't completely reflect the current state of our files, but it may give you an idea of where key files may be found.

I'll try to provide some details below, but this is not meant to be an exhaustive explanation or list of files.

Dart does generate a JS AST - see `pkg/js_ast/` for the implementation and `pkg/compiler/lib/src/js/js.dart` for some wrappers around it. Bits of the AST are built up in `pkg/compiler/lib/src/js_emitter/` as well as `pkg/compiler/lib/src/ssa/codegen.dart`. Actual file I/O is handled in `pkg/compiler/lib/src/io/` and invoked from `pkg/compiler/lib/src/dart2js.dart`.

Note that working backward from file output may not be the easiest way to grok a given phase of the compiler. Is there a particular aspect of dart2js you're curious about?

/cc @sigmundch

**Comment by sigmundch** [comment]
@fishythefish - I just sent you a draft of changes to bring some of the readme documentation more aligned with what we do today: https://dart-review.googlesource.com/c/sdk/+/242505

I agree with your assessment, it's not as easy to work backwards because the compiler has so many phases. The file under `pkg/compiler/lib/src/compiler.dart` is where most of the phase management happens today, so it may be a better starting point? It is a big system though (>150KLoc), so there isn't really a unique answer, and where to start really depends on what you are trying to achieve.
