### ISSUE TITLE
[analyzer] add quick fixes for `VAR_RETURN_TYPE`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#48779]
As suggested by the `ParserErrorCode.VAR_RETURN_TYPE` message, there are possibly two ways to fix it:

- [ ] Remove `var`
- [ ] Replacing `var` with the name of the return type

**Comment by asashour** [comment]
For removing `var`:

https://dart-review.googlesource.com/c/sdk/+/240841

Replacing with the name of the return type, would follow after the first CL.

**Comment by bwilkerson** [comment]
Not that I'm not grateful for the contribution, but just FYI, based on the information available to me, very few users will ever see this diagnostic. Unfortunately, that means that very few users will be impacted by a fix for this diagnostic. I'm only mentioning this in case you would prefer to focus on more frequently generated diagnostics.

**Comment by asashour** [comment]
Thanks for the info, this was reported, because I personally came across it, but it doesn't mean it it widely encountered.

Is there a possibility to share the most common issues, or generally the short-term roadmap, for things I can help with?  I understand the review takes time, and better alignment would help provide a more focused contribution, and provide more value to the users.

**Comment by bwilkerson** [comment]
We definitely need to get better about making it easier for external contributors to know what work there is to be done, the priority of that work, and how much experience it's likely to require in order to do it. Unfortunately it will take some time to put all that in place, but we definitely value all of the contributions we receive.

**Comment by asashour** [comment]
Closed, as no need for further work.
