### ISSUE TITLE
completion_metrics tool, with `--overlay remove-token`, throws InconsistentAnalysisException for flutter/gallery

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#48789]
Cloning flutter/gallery, and then running `flutter pub get`, and then running the completion_metrics tool, throws an error:

```none
$ $HOME/code/flutter/bin/dart pkg/analysis_server/tool/code_completion/completion_metrics.dart /Users/srawlins/code/flutter-gallery --overlay remove-token
Analyzing root: "/Users/srawlins/code/flutter-gallery"
Unhandled exception:
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:133:7)
#1      AnalysisSessionImpl.getResolvedUnit (package:analyzer/src/dart/analysis/session.dart:119:5)
#2      CompletionMetricsComputer._computeInContext (file:///Users/srawlins/code/dart-sdk/sdk/pkg/analysis_server/tool/code_completion/completion_metrics.dart:1409:16)
<asynchronous suspension>
#3      CompletionMetricsComputer.computeMetrics (file:///Users/srawlins/code/dart-sdk/sdk/pkg/analysis_server/tool/code_completion/completion_metrics.dart:737:7)
<asynchronous suspension>
#4      main (file:///Users/srawlins/code/dart-sdk/sdk/pkg/analysis_server/tool/code_completion/completion_metrics.dart:129:3)
<asynchronous suspension>
```

It seems to be doing better if I do not pass `--overlay remove-token`.

**Comment by srawlins** [comment]
Some motivating user-filed bugs relating to this:

* https://github.com/dart-lang/sdk/issues/43113
* https://github.com/dart-lang/sdk/issues/40347
* https://github.com/dart-lang/sdk/issues/41641

**Comment by srawlins** [comment]
CC @bwilkerson in case you're interested

**Comment by bwilkerson** [comment]
I'm definitely interested, but @scheglov probably has more context for solving the underlying issue.

**Comment by srawlins** [comment]
Haha, it took 90 minutes to run over flutter/gallery.

**Comment by scheglov** [comment]
If you are curious, it still runs. Which is concerning, but it uses CPU, so maybe not stuck?
<img width="267" alt="image" src="https://user-images.githubusercontent.com/384794/163475906-5bbae4c4-c408-4788-9e0c-ebde5128e565.png">

**Comment by scheglov** [comment]
I think the issue is fixed, but I still was not able to wait until the process is done.

**Comment by srawlins** [comment]
I'm adding a progress bar here: https://dart-review.googlesource.com/c/sdk/+/241623

**Comment by srawlins** [comment]
It seems to get waaaaay hung up on `lib/codeviewer/code_segments.dart`, a 47000 line file. Many many statements, not too many class members.
