### ISSUE TITLE
[CP] Please cherry pick 3d8290d926b7b909bc8ff19b4d6d96c2301d81c3 into Dart 2.17 beta 3

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#48783]
**commit(s) to merge**: 3d8290d926b7b909bc8ff19b4d6d96c2301d81c3

**merge instructions**: clean merge

**What is the issue**: profiling an app using timelines on iOS is very slow because Dart_TImelineEvent is surprisingly slow

**What is the fix**: Using a newer call to efficiently access thread CPU time on Mac

**Why cherrypick**: Please see https://github.com/dart-lang/sdk/issues/47850, performance testing on macOS is inefficient. This is not a bug fix but developers profiling their apps will find themselves being less productive because of this infficiency.

**Risk**: Just 3 lines of code change, the fix has been rolled into Flutter and verified that it does improve performance times.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/47850

/cc @mit-mit @whesse @athomas @vsmenon @kevinjchisholm @rmacnak-google

**Comment by whesse** [comment]
Merged in 2.17.0-266.5.beta.
