### ISSUE TITLE
Null assertion in try/catch block

### ISSUE THREAD

**Issue by Phreeshad** [dart-lang/sdk#48799]
_Dart SDK version: 2.17.0-282.0.dev_

Let's assume we have a `try/catch` block as the following;
```
var titles;
var sections;
try {
  assert(library != null);
  titles = library.keys.toList();
  sections = library.values.toList();
}catch(e) {
  print('A problem occured!');
}
```
Although there is an assertion check before, and also `try` block will catches the exception if `library` is `null`, the Analyzer says:
```
The property 'keys' can't be unconditionally accessed because the receiver can be 'null'.
Try making the access conditional (using '?.') or adding a null check to the target ('!').dart(unchecked_use_of_nullable_value)
```

**Comment by julemand101** [comment]
In case you don't know, `assert` is not evaluated when running your application in production as stated in the language tour:
> In production code, assertions are ignored, and the arguments to assert aren’t evaluated.

https://dart.dev/guides/language/language-tour#assert

Which means we cannot use `assert` to make any guarantees about fields not being null later in our program.

About the try...catch block I would assume that we should not make use of that to catch NullPointerExceptions when the type system can statically determine that field can be `null`. We already have other ways to do that.

**Comment by devoncarew** [comment]
This is working as intended; the analyzer - and the type system - can't use asserts to promote types to null safety. Asserts don't always run - you can opt-into them in debug configurations, but they are compiled out in release ones. Relying on them for type promotion wouldn't generally be sound.

**Comment by Phreeshad** [comment]
Oh, then I misunderstood about `assert`, thank you!
