### ISSUE TITLE
Add high level utilities for comparing analyzed types

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#48809]
Except `TypeChecker.fromRuntime`.

**Comment by natebosch** [comment]
This was originally a request to move the `TypeChecker` class from `source_gen`, but I suspect if we implement such a feature we'd want to consider if that API was the one we want.

This utility is intended to make it easier to work with DartType - it more directly expresses assignability, it allows comparing against other ways to express a type like a URL scheme (or from the runtime, but that capability uses mirrors and probably isn't worth porting over), and it filters annotations by type.

**Comment by bwilkerson** [comment]
After a brief glance at `TypeChecker`, there appears to be a fair bit of duplication with the analyzer package's `TypeSystem`. I would prefer to talk about specific APIs that might be useful to add to `TypeSystem` than to have another mechanism for dealing with types.

It would be great if someone more familiar with `TypeChecker` could do the comparison and let us know what you think should be added.

**Comment by ykmnkmi** [comment]
How to get or initialize `TypeSystem` instance?

**Comment by bwilkerson** [comment]
You can access the type system that was used for analysis through `ResolvedUnitResult.typeSystem`.

**Comment by srawlins** [comment]
> It would be great if someone more familiar with TypeChecker could do the comparison and let us know what you think should be added.

This is an important question. What is the ask here, for these utilities?

**Comment by natebosch** [comment]
> What is the ask here, for these utilities?

The original request was on the `source_gen` repo asking for `TypeChecker` to get moved into the analyzer package.

It sounds like the right resolution is to close this issue, and @ykmnkmi can file issues with more specific requests for anything not covered by `TypeSystem`.

**Comment by bwilkerson** [comment]
If you have the element for the class (or whatever defines the type) you can ask it to `instantiate` a type based on it. Would that work?

**Comment by natebosch** [comment]
I'm wondering about the case where I want to compare a type in the code I'm analyzing against a known hardcoded type. For instance I might want to check whether the `@Foo()` annotation on a class is a subclass of `class Bar`. I can get a `DartType` for `Foo` by parsing the metadata, but I don't know how to most easily get a `DartType` for `Bar`. 

If resolving the library where `Bar` is defined based on the hardcoded known URI and then getting the type from there is the preferred approach I think that is OK. `TypeChecker` does some normalization so you can specify a type by a URL and name, and then it can compare that against `DartType` instances.

**Comment by natebosch** [comment]
We'd typically assume that the library had already been resolved (necessarily true in the case where `Foo` is a subtype of `Bar`, but maybe not otherwise) so the cost to re-resolve shouldn't be too high.

Walking up the superclass chain as you described is I think effectively what we've implemented with `TypeChecker` - it might be worth considering some utility to abstract some of that but I don't have any concrete proposals.

The main value in `TypeChecker` seems to be the URI normalization (since builders may see different formats like `asset:` or `package:` URIs for sources using the analyzer APIs). The URIs are controlled by our integration with the analyzer, so it probably continues to make sense to keep that in `source_gen` instead of the analyzer.


Does the driver (or session, or type system) track types that have been resolved so far? If so, would it be feasible to query for a particular type  or class element by library URI and name?

**Comment by bwilkerson** [comment]
> Does the driver (or session, or type system) track types that have been resolved so far?

I believe the answer is no. @scheglov to correct me if I'm wrong.

**Comment by scheglov** [comment]
You can ask for a specific library by its URI, and then ask it for a `ClassElement` that it exports, see for example https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/pkg/analyzer/lib/src/dart/analysis/session_helper.dart#L24

Then you could ask https://github.com/dart-lang/sdk/blob/d78797d0141cd5956dbe599caebd1b5b19fc270e/pkg/analyzer/lib/dart/element/type.dart#L158

Or you could iterate over https://github.com/dart-lang/sdk/blob/d78797d0141cd5956dbe599caebd1b5b19fc270e/pkg/analyzer/lib/dart/element/type.dart#L275 to check if there is a class that you are looking for, get `InterfaceType.element`, its `ClassElement.library.source`, check `Source.uri` and `ClassElement.name`.

We do know internally which libraries are available in the current session, but we don't expose this information.
