### ISSUE TITLE
quick fix for `prefer_initializing_formals` needs smarts when types need specifying

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#48804]
_Mis-filed as a linter issue (https://github.com/dart-lang/linter/issues/3345)._  

The fix for `prefer_initializing_formals` needs to know when a type should be specified.

```dart
class C {
  final Object name;
  final int length;
  C.forName(String name) : name = name;
}
```

fixes to:

```dart
class C {
  final Object name;
  final int length;
  C.forName(this.name);
}
```

which is incorrect.

It should produce:

```dart
class C {
  final Object name;
  final int length;
  C.forName(String this.name);
}
```

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/241221

**Comment by pq** [comment]
Thanks for the fix @asashour!
