### ISSUE TITLE
NNBD migration can strengthen on forced errors in increment/decrement/assignment operators

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#48800]
I think `id` is inferred as nullable since the value of `idCounter++` is the pre-value, but the assignment will never happen if `idCounter` is `null` since there will be a crash on `null + 1`. So we can be sure `id` is non-nullable.

![image](https://user-images.githubusercontent.com/2108821/163054975-8c28f38d-1e22-4ddf-9edb-c9b3575f1a7b.png)

Changing to `++idCounter` makes `idCounter` be `late`, a reasonable choice.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
