### ISSUE TITLE
dart fix for `use_super_parameters` causes incorrect default value

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48803]
Run `dart fix --apply` over the following code:

```dart
class Foo {
  Foo({this.value = 10});
  final int? value;
}

class Bar extends Foo {
  Bar({int? value}) : super(value: value);
}

void main() {
  print(Bar().value); // Prints `null`, as expected.
}
```

This gives the following incorrect result:

```dart
class Foo {
  Foo({this.value = 10});
  final int? value;
}

class Bar extends Foo {
  Bar({super.value});
}

void main() {
  print(Bar().value); // 🔥 Prints `10` (should have preserved the previous behavior of printing `null`)
}
```

Instead, the constructor of `Bar` should have been rewritten as follows to preserve semantics:

```dart
  Bar({super.value = null});
```

(The correct rewrite causes a false `avoid_init_to_null` lint warning, I filed https://github.com/dart-lang/linter/issues/3349 for that.)

**Comment by asashour** [comment]
Just to add,

```dart
Bar({super.value = null});
```

triggers [avoid_init_to_null](https://dart-lang.github.io/linter/lints/avoid_init_to_null.html), so should it also be changed to accept `=null` with super parameters?

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/241220

**Comment by bwilkerson** [comment]
The change to the lint rule is in progress (https://github.com/dart-lang/linter/pull/3351).
