### ISSUE TITLE
Evaluate if it is possible to not invoke the isolate create callback when Isolate.SpawnFunction is used

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#4880]
Evaluate if it is possible to not invoke the isolate create callback when
Isolate.SpawnFunction is called. This has some implications when script snapshots are used.

Would be ideal if the spawned isolate is able to clone the script object from the spawning isolate.

I am not sure if there are some issues in dartium with regards to this.

**Comment by iposva-google** [comment]
Stale.
