### ISSUE TITLE
generate_package_config.py fail due to dart sdk version missmatch

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48818]
`python3 tools/generate_package_config.py` currently fails with the following error:

```
src/third_party/dart/tools/generate_package_config.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.16.
// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
^
Error: Command 'python3 src/third_party/dart/tools/generate_package_config.py' returned non-zero exit status 254 in /Users/goderbauer/dev/engine
src/third_party/dart/tools/generate_package_config.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.16.
// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
^
```

The dart sdk used to run this script is defined in https://github.com/dart-lang/sdk/tree/main/tools/sdks, which is currently `2.16.2`, but the script seems to need 2.17.

This is possibly related to the analyzer_server bumping its lower bound to 2.17 in https://github.com/dart-lang/sdk/commit/d422b637586b044f8c80d06bc8c4c4661558befb.

**Comment by whesse** [comment]
We may not want to boost the checked-in SDK to 2.17 before we release stable 2.17. 

I think the bound for analyzer_server should not have been bumped past the checked-in version of the SDK in https://github.com/dart-lang/sdk/commit/d422b637586b044f8c80d06bc8c4c4661558befb.

@athomas

**Comment by athomas** [comment]
I've created https://dart-review.googlesource.com/c/sdk/+/241516 to get us in 2.17 beta. We should have high enough confidence in our betas to use them in the checked-in SDKs. If something turns out to be broken in the beta, it gives us a chance to fix before the stable.

**Comment by athomas** [comment]
Assuming this was fixed by the checked-in SDK update.
