### ISSUE TITLE
It should not be an error for `Enum` to have an `index` getter

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#48811]
The analyzer currently issues an error if I analyze the dart sdk, as follows:

```
  error • A concrete instance member named 'index' can't be declared in a class that implements 'Enum'. • dart:core/enum.dart:101:13 • illegal_concrete_enum_member
```

I believe that the error in question is not intended to apply to the actual `Enum` class of the SDK (that is, only things which have the actual `Enum` class as a proper super-interface).  cc @lrhn @eernstg @scheglov @srawlins @bwilkerson

**Comment by leafpetersen** [comment]
See also https://github.com/dart-lang/language/issues/2202 for a clarification question on the specification for this.

**Comment by eernstg** [comment]
Agreed, the `index` rule should not apply to `Enum` itself. I think this is already specified. However, we'd need an exception for `_Enum`, which is mentioned indirectly in the enhanced-enums specification. We might keep that out of the specification documents, just like we never mention that a constructor like `bool.fromEnvironment` can be an external const factory, or how `FutureOr` can behave the way it does, given that it is declared as a class. So it's OK for system libraries to contain "magic" code.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/241466
