### ISSUE TITLE
"The specified language version is too high." error could be more specific

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48819]
See https://github.com/dart-lang/sdk/issues/48818 for am example of where the error was encountered. 

I wish this error would contain more information to help debugging it, e.g.:

- What was the specified language version?
- Where was that version specified?

**Comment by bradcypert** [comment]
Yeah, im running into this now and oddly enough I'm only seeing it when building on iOS (Android builds fine), so the error isn't really helpful for me (and feels like the error message may be a red herring?)
