### ISSUE TITLE
error

### ISSUE THREAD

**Issue by caiwei1990** [dart-lang/sdk#48824]
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.16.2`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.16, screens 1440x900, 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.16.2, server version 1.32.8, error: Bad state: No type: color
#0      ExpressionExtension.typeOrThrow (package:analyzer/src/dart/ast/extensions.dart:88:7)
#1      ExtractMethodRefactoringImpl._initializeParameters (package:analysis_server/src/services/refactoring/extract_method.dart:719:41)
#2      ExtractMethodRefactoringImpl.checkInitialConditions (package:analysis_server/src/services/refactoring/extract_method.dart:199:24)
#3      _RefactoringManager._init (package:analysis_server/src/edit/edit_domain.dart:1201:36)
<asynchronous suspension>
#4      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:993:7)
<asynchronous suspension>
```

For additional log information, please append the contents of
file:///private/var/folders/47/n91qcfn91_977y7jtlv7yhq40000gn/T/report.txt.

**Comment by scheglov** [comment]
Not actionable without an example of code on which this happens.

**Comment by DanTup** [comment]
This may be the same issue I found today (https://github.com/Dart-Code/Dart-Code/issues/4029). Extract Method could be invoked on import prefixes and also on type names that had `?` suffixes.

I've CC'd you on a possible fix at https://dart-review.googlesource.com/c/sdk/+/249600.

**Comment by scheglov** [comment]
Ah, nice that you tracked it down :-)
