### ISSUE TITLE
Response parse exception Content-Length and Transfer-Encoding

### ISSUE THREAD

**Issue by DmitriyVasilevPlaytika** [dart-lang/sdk#48822]
Hello

Durring developing the our product we faced with the next error.
When we trying to edit the response from the out server by Charles in headers added the Content-Length, but headers already has the Transfer-Encoding. In this case response can't be parse completly and 
_http/http_parser.dart throw the next exception:
"Both Content-Length and Transfer-Encoding are specified, at most one is allowed"

It's create a lot of issue with developing and qa the produc.
Can you please fix it?
For example the previos project we developed by .Net and this situation handled by .Net frameworks like ignore Content-Length in headers in case when headers have Content-Length and Transfer-Encoding.

I'm also look in the code "http_parser.dart" and I see the next:
```
function bool _headersEnd()
...
// Ignore the Content-Length header if Transfer-Encoding
// is chunked (RFC 2616 section 4.4)
    if (_chunked) _transferLength = -1;
...
```

As I understood this code should ignore the situation when headers contain Content-Length and Transfer-Encoding.

Thank you!

**Comment by a-siva** [comment]
//cc @brianquinlan

**Comment by DmitriyVasilevPlaytika** [comment]
Guys any news?

**Comment by brianquinlan** [comment]
If I understand correctly, you'd like to be able to disable HTTP header validation?

**Comment by DmitriyVasilevPlaytika** [comment]
> 
If it possible to not throw the Exception "Both Content-Length and Transfer-Encoding are specified, at most one is allowed"
because as I saw in code after validation in _doParse() method 
will be called
_headersEnd()
 and here exist code
 if (_chunked) _transferLength = -1;
 
 as I understand correct
 validation with throwing exception for this two fields not required in _headersEnd()

**Comment by DmitriyVasilevPlaytika** [comment]
@brianquinlan  Did you have a some progress for this?

**Comment by brianquinlan** [comment]
If my reading of [RFC 2616 4.4](https://www.rfc-editor.org/rfc/rfc2616#section-4.4) section 3 is correct then we should ignore the "Content-Length" header.

**Comment by DmitriyVasilevPlaytika** [comment]
Yes, please ignore it.

**Comment by sfali23** [comment]
I am getting same error. Is there any workaround for this?

**Comment by a-siva** [comment]
//cc @aam

**Comment by brianquinlan** [comment]
[RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2) says:
>    A sender MUST NOT send a Content-Length header field in any message
>    that contains a Transfer-Encoding header field.

But I have a fix in the works on our end: https://dart-review.googlesource.com/c/sdk/+/327703

**Comment by brianquinlan** [comment]
@sfali23 Are you sure that the **server** is not sending those headers?

**Comment by sfali23** [comment]
Correct, server is setting `Content-Length` while `Transfer-Encoding` was added may be by the library. By removing `Content-Length` from server make it work.
