### ISSUE TITLE
"Convert to using super parameters" correction in the analysis server defaults to null with required List arguments

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#48831]
When I have a constructor like this:

```dart
  _MenuBarMenuRenderWidget({
    Key? key,
    required List<Widget> children,
  }) : super(key: key, children: children);
```

The analysis server suggests converting to using super parameters (correctly), but when I apply the fix, I get:

```dart
  _MenuBarMenuRenderWidget({
    super.key,
    required super.children = null,
  });
```

Which is incorrect, since "Required named parameters can't have a default value.", and because a default for a non-nullable `List` shouldn't be `null`.

Dart version: Dart SDK version: 2.18.0-30.0.dev (dev) (Mon Apr 18 01:06:35 2022 -0700) on "linux_x64"

**Comment by bwilkerson** [comment]
What does the constructor in the superclass of `_MenuBarMenuRenderWidget` look like?

**Comment by gspencergoog** [comment]
it is:

```dart
  _MenuBarMenuRenderWidget({
    required super.children,
  });
```
and it's superclass is:

```dart
  MultiChildRenderObjectWidget({ super.key, this.children = const <Widget>[] });
```

Here's a reproducible standalone example:

```dart
class Key {}

class Widget {
  Widget({this.key});

  final Key? key;
}

class Base extends Widget {
  Base({ super.key, this.children = const <Widget>[] });

  List<Widget> children;
}

class Child extends Base {
  Child({Key? key, required List<Widget> children}) : super(key: key, children: children);
}
```

When I convert `Child`, it gives me:
```dart
class Child extends Base {
  Child({super.key, required super.children = null});
}
```
Which is incorrect.

**Comment by bwilkerson** [comment]
Thanks, I can reproduce the bug now.
