### ISSUE TITLE
Completions after if-element, not at the end of the list, does not include else keyword

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#48837]
For example,

```dart
void f(int i, int j) {
  [if (true) i ^, j];
}
```

`else` is not suggested at the carat.

**Comment by bwilkerson** [comment]
As of https://dart-review.googlesource.com/c/sdk/+/312940 it does now show up on the list, though it's a long way down when there's nothing typed. Typing 'e' causes it to jump to the second entry, so that's probably not too bad for now.
