### ISSUE TITLE
Deprecate WindowBase64, replace with WindowOrWorkerGlobalScope

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#48838]
`WindowBase64` seems like something random from the Chrome IDL

`WindowOrWorkerGlobalScope` seems like what we want - https://developer.mozilla.org/zh-TW/docs/Web/API/WindowOrWorkerGlobalScope

It includes the `atob` and `btoa` methods, plus many other things that are shared – and could allow better OO programming over common types.

**Comment by rileyporter** [comment]
Based on a quick initial check, this was used for Dartium and otherwise would be safe to deprecate and delete immediately.

**Comment by kevmoo** [comment]
We should do at least one stable release w/ it deprecated – in case anyone is using it. But I think a 1-2 punch (deprecate, remove) would be a great idea

**Comment by kevmoo** [comment]
Closing out. Use `pkg:web`
