### ISSUE TITLE
[cfe] Error reported for spurious conflict involving static and extension method

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#48834]
Thanks to @athomas for raising this issue. Consider the following program:

```dart
extension HashAll on Iterable {
  int hashAll() => 0;
}

extension HashAllList on List {
  int hashAll() => 1;
}

void main() {
  List l = [];
  Iterable i = [];
  print(l.hashAll());
  print(i.hashAll());
}
```

The CFE (using `dart` from commit 20b560226e654f8885acd607b94f23b63bd9806b) reports a conflict with a _static_ member of the class `Object`:

```
n008.dart:2:7: Error: This extension member conflicts with Object member 'hashAll'.
  int hashAll() {
      ^^^^^^^
n008.dart:8:7: Error: This extension member conflicts with Object member 'hashAll'.
  int hashAll() {
      ^^^^^^^
```

However, I cannot find a justification in the specification documents that any such conflict should be reported. Intuitively, it would not be a conflict anyway, because access to the static method `hashAll` in `Object` would have to use the syntax `Object.hashAll` or `prefix.Object.hashAll` everywhere outside the class `Object` itself, and those forms cannot be an access to the extension methods shown above (assuming that `Object` resolves to the built-in class and hasn't been shadowed by declaration like a local variable).

I believe the conflict should not be reported. The behavior is CFE specific, the analyzer doesn't report a conflict.

**Comment by eernstg** [comment]
Actually, the spec needs to be clarified [here](https://github.com/dart-lang/language/blob/24ba4b5014a434641927f30ebb3557e649bf4a02/specification/dartLangSpec.tex#L5840):

```
$D$ declares a member (static or not) with the same basename as a
member declared by the built-in class \code{Object}.
```

It should be adjusted to say 'an instance member'. Cf. https://github.com/dart-lang/language/pull/2207.

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/241603.
