### ISSUE TITLE
older repository references from the SDK DEPS file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#48830]
There are a few older repository references in our SDK DEPS file. These are repositories that may at one point have lived in the `dart-lang/` github org but have since moved out. Github re-directs references to the new location automatically; I don't know how important it is for the references to be correct (or, if we have to update our mirror information). It would make some tooling I'm writing simpler if the DEPS file points to the current (non-redirected) locations. The references are:

- `https://github.com/google/protobuf.dart` (currently referred to as 'dart-lang/protobuf.dart')
- `https://github.com/lrhn/charcode` (currently referred to as 'dart-lang/charcode')
- `https://github.com/google/pedantic` (currently referred to as 'dart-lang/pedantic')

**Comment by devoncarew** [comment]
Also, `dart-lang/platform.dart` should be `google/platform.dart`.

**Comment by devoncarew** [comment]
And `dart-lang/process.dart` ==> https://github.com/google/process.dart.

**Comment by sortie** [comment]
DEPS is not using github directly but through https://dart.googlesource.com/ which is mirrored from github for most packages. Some of those mirrors are still mirroring from dart-lang which is then transparently redirected to the other new orgs.

We could either keep the moved repositories at their current top level names on dart GoB and then change where they're mirrored from; or we can go further and rename them to match the other stuff we're importing from non-dart-lang orgs. I'm thinking I'll be looking into all these repositories as part of my KR to secure the dart GoB per our data security policies. charcode is a special case I'll look into specifically.

cc @athomas

**Comment by sortie** [comment]
@leafpetersen DEPS isn't referencing dart-lang or GitHub but is getting everything through Git-on-Bort (e.g. https://dart.googlesource.com/ but see the `allowed_hosts` array in `DEPS` for all the hosts we allow) so I don't see any action items for us here. It sounds like it's your tooling that needs to understand `DEPS` appropriately?

There's a bit of concerns regarding the mirroring we do from GitHub into GoB but that should be unrelated to the work you're doing and I'm cleaning that up later in a separate issue.

Can I close this issue? Or please reopen if you can clarify what you need that isn't already there?

**Comment by devoncarew** [comment]
For several of these repos, the DEPS file is pointing to the older locations. I think it would be more correct to point to the new repo locations; I'm just not sure how this would work with the mirroring.

If I get time this week, I'll create a CL updating the DEPS for the repo locations, and see if it builds through (or if we hit other issues).

**Comment by sortie** [comment]
I'm confused. Can you link to the place you see where DEPS is referencing github? I don't see any github references in there at all.

**Comment by devoncarew** [comment]
Sure:

The `args_rev` dep is defined as

`Var("dart_root") + "/third_party/pkg/args": Var("dart_git") + "args.git" + "@" + Var("args_rev")`

which if you unwind the variables a bit gives you:

`sdk/third_party/pkg/args: https://dart.googlesource.com/args.git@3b3f557...`

for protobuf:

```
Var("dart_root") + "/third_party/pkg/protobuf": Var("dart_git") + "protobuf.git" + "@" + Var("protobuf_rev")
```

becomes: 

`sdk/third_party/pkg/protobuf: https://dart.googlesource.com/protobuf.git@...`

for package:file:

`Var("dart_root") + "/third_party/pkg/file": Var("dart_git") + "external/github.com/google/file.dart" + "@" + Var("file_rev")`

becomes:

```
sdk/third_party/pkg/file: https://dart.googlesource.com/external/github.com/google/file.dart@...
```

I guess I've been treating googlesource.com as an implicit github.com/dart-lang reference., but looking more closely clearly it can be set up to mirror any github org's repo.

Do we have any conventions for which repos get the `external/github.com/...` treatment? protobuf above, like package:file, is hosted in the google github org, but does not have an `external/github.com/google/..` reference.

My end goal here is to be able to know where the deps are hosted just by parsing the DEPS file, without having to have special casing for 4-5 repos.

**Comment by devoncarew** [comment]
Using `gclient revinfo`, here's the current dart package deps listed in the DEPS file:

```
https://dart.googlesource.com/args.git
https://dart.googlesource.com/async.git
https://dart.googlesource.com/bazel_worker.git
https://dart.googlesource.com/benchmark_harness.git
https://dart.googlesource.com/boolean_selector.git
https://dart.googlesource.com/browser_launcher.git
https://dart.googlesource.com/characters.git
https://dart.googlesource.com/charcode.git
https://dart.googlesource.com/cli_util.git
https://dart.googlesource.com/clock.git
https://dart.googlesource.com/collection.git
https://dart.googlesource.com/convert.git
https://dart.googlesource.com/crypto.git
https://dart.googlesource.com/csslib.git
https://dart.googlesource.com/dart_style.git
https://dart.googlesource.com/dartdoc.git
https://dart.googlesource.com/external/github.com/google/file.dart
https://dart.googlesource.com/external/github.com/google/vector_math.dart.git
https://dart.googlesource.com/external/github.com/google/webdriver.dart.git
https://dart.googlesource.com/external/github.com/google/webkit_inspection_protocol.dart.git
https://dart.googlesource.com/ffi.git
https://dart.googlesource.com/fixnum.git
https://dart.googlesource.com/glob.git
https://dart.googlesource.com/html.git
https://dart.googlesource.com/http.git
https://dart.googlesource.com/http_io.git
https://dart.googlesource.com/http_multi_server.git
https://dart.googlesource.com/http_parser.git
https://dart.googlesource.com/intl.git
https://dart.googlesource.com/json_rpc_2.git
https://dart.googlesource.com/linter.git
https://dart.googlesource.com/lints.git
https://dart.googlesource.com/logging.git
https://dart.googlesource.com/markdown.git
https://dart.googlesource.com/matcher.git
https://dart.googlesource.com/mime.git
https://dart.googlesource.com/mockito.git
https://dart.googlesource.com/oauth2.git
https://dart.googlesource.com/package_config.git
https://dart.googlesource.com/path.git
https://dart.googlesource.com/platform.dart.git
https://dart.googlesource.com/pool.git
https://dart.googlesource.com/process.dart.git
https://dart.googlesource.com/protobuf.git
https://dart.googlesource.com/pub.git
https://dart.googlesource.com/pub_semver.git
https://dart.googlesource.com/shelf.git
https://dart.googlesource.com/shelf_packages_handler.git
https://dart.googlesource.com/shelf_proxy.git
https://dart.googlesource.com/shelf_static.git
https://dart.googlesource.com/shelf_web_socket.git
https://dart.googlesource.com/source_map_stack_trace.git
https://dart.googlesource.com/source_maps.git
https://dart.googlesource.com/source_span.git
https://dart.googlesource.com/sse.git
https://dart.googlesource.com/stack_trace.git
https://dart.googlesource.com/stream_channel.git
https://dart.googlesource.com/string_scanner.git
https://dart.googlesource.com/sync_http.git
https://dart.googlesource.com/term_glyph.git
https://dart.googlesource.com/test.git
https://dart.googlesource.com/test_descriptor.git
https://dart.googlesource.com/test_process.git
https://dart.googlesource.com/test_reflective_loader.git
https://dart.googlesource.com/typed_data.git
https://dart.googlesource.com/usage.git
https://dart.googlesource.com/watcher.git
https://dart.googlesource.com/web-components.git
https://dart.googlesource.com/web_socket_channel.git
https://dart.googlesource.com/webdev.git
https://dart.googlesource.com/yaml.git
https://dart.googlesource.com/yaml_edit.git
```

**Comment by devoncarew** [comment]
(`protobuf`, `charcode`, `platform`, and `process` are referenced differently than the other github google org repos)

**Comment by sortie** [comment]
Thanks Devon for clarifying! This setup is indeed as I'm describing. dart.googlesource.com is indeed its own entity and is NOT a blind mirror of the github dart-lang organization. The repositories there have been carefully set up to mirror changes to and from other locations. A given repository may have its actual source of truth on dart.googlesource.com, github, or even G3.

A few of repositories have since moved into different organizations or become third party. We've kept the historical names for now due to backwards compatibility, although I am wanting to clean that up as we discontinue the old locations. That's why there's a bit of inconsistency with the external repositories with github in their name as you mention.

From the SDK's point of view, these dependencies are hosted on googlesource. Everyone using DEPS are using only googlesource. There's no github involved in a SDK checkout. The build will fail with a disallowed host if github is referenced in DEPS. If you want to e.g. roll dependencies into the Dart SDK, then those are the repositories you'll want to monitor, and not their upstream locations.

If you want to care about the actual sources of truth, you cannot easily map them from DEPS. Like I said, some of these packages are developed on googlesource, others on Github, and some even in G3. You'll need to know that location per package.

Can you clarify what purpose you want to use this information for?

**Comment by devoncarew** [comment]
As you said above, I don't think there's necessarily any AIs for you here; thanks for all the info!

**Comment by sortie** [comment]
Thanks for the use case information. If you're looking to see how well the DEPS are in sync with the upstream repositories, you can simply check the mirrored git repositories from gclient revinfo, as they are automatically mirrored and up to date with the latest commits. You don't actually need the upstream repositories for that. The pub and G3 information is separate though, but at least the packages have the same names.
