### ISSUE TITLE
Failures on [dart2js] Migrate more of entities.dart...[parser] Rename Token impl classes to avoid name conflicts

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#48847]
There are new test failures on [[dart2js] Migrate more of entities.dart...[parser] Rename Token impl classes to avoid name conflicts](https://github.com/dart-lang/sdk/compare/7a0b8f850bd9f063e675db916a6e844fd1e19f07~...35c78ac66b0ee6713b2b0293bf45dd76f9af6c25).

The tests
```
vm/dart_2/isolates/reload_many_isolates_live_and_die_test Timeout (expected Pass)
```
are failing on configurations
```
dartk-reload-linux-release-x64
```

This test seems to be very slow and has flaky timeouts on other configurations (dartk-linux-release-simarm, dartk-tsan-linux-release-x64, dartk-linux-release-simarm64, dartk-mac-release-x64, dartk-reload-rollback-linux-release-x64).

@mkustermann Is it possible to reduce the amount of work performed in this test without loosing test coverage? Or maybe we should `SkipSlow` the test on all these configurations?

**Comment by mkustermann** [comment]
For our artificial hot-reload test mode: The test itself launches subprocesses and performs reload on them. We don't need the test driver itself to run in this artificial identical hot reload mode.

For simulators: We can reduce the load.

For others: We should give it a little more time. e.g. the TSAN mode adds value (running it locally already revealed an issue: https://github.com/dart-lang/sdk/issues/48871)

-> [cl/242107](https://dart-review.googlesource.com/c/sdk/+/242107)
