### ISSUE TITLE
Private variable in class still access outside

### ISSUE THREAD

**Issue by HoangNguyen0403** [dart-lang/sdk#48864]
Hi development team. Today i tried with private instance on dartpad and get this wierd mechanism about private variable.

![image](https://user-images.githubusercontent.com/103477760/164596489-ffc6e1bf-5800-40ad-9147-7b4416708aeb.png)

I tried with flutter 2.5.3 ( dart 2.11.4 ) it's still worked like i expected is i can't access to private variable. But not sure why in dart 2.16.2 i get this one. Please check this because i think it's urgent! Regards!

![image](https://user-images.githubusercontent.com/103477760/164597057-18e0688e-1c06-42b4-955e-aee0dc470897.png).

Note: tried both on dartpad and with Flutter from Android Studio. Not only in DartPad

**Comment by HoangNguyen0403** [comment]
@scheglov i see someone tag you and see profile you're in Google. So can help me to take a look with this

**Comment by srawlins** [comment]
Private fields are intended to be visible outside of the class in which they are declared. They are private to the library in which they are declared. See the explanation in the [Language Tour](https://dart.dev/guides/language/language-tour#libraries-and-visibility).

**Comment by HoangNguyen0403** [comment]
> Private fields are intended to be visible outside of the class in which they are declared. They are private to the library in which they are declared. See the explanation in the [Language Tour](https://dart.dev/guides/language/language-tour#libraries-and-visibility).

so what's difference between private and public variables inside our codebase ?

**Comment by HoangNguyen0403** [comment]
> Private fields are intended to be visible outside of the class in which they are declared. They are private to the library in which they are declared. See the explanation in the [Language Tour](https://dart.dev/guides/language/language-tour#libraries-and-visibility).

And do we have anything in ChangeLog here ? Because i think update this syntax is not a small update. We want hide variable that don't want to display when call instance of class. With this new, it's nonsense.

**Comment by HoangNguyen0403** [comment]
After ask in community and get this answer "This is normal, private variables declared in the same file are accessible".
I think i understand about that. But not sure this mechanism is good or not.

**Comment by lrhn** [comment]
Dart privacy is library scoped, so yes, this is normal for Dart.

The unit of editing is the library. Nobody outside of your library will see the private members, and if you declare one class per library, it's really just like class privacy. It just allows you to add more code to the library, which can all share the private declarations. You decide the size of the chunk of code which can cooperate around the private declarations.
