### ISSUE TITLE
[Analyzer Plugin] Navigation Contributions not appearing in IntelliJ

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#48868]
I'm trying to add custom Navigation Contributions to IntelliJ through an Analyzer Plugin by following [this](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer_plugin/doc/tutorial/navigation.md) doc.

I managed to get it to work in VSCode but not in IntelliJ i.e. 'command + click' shows new navigation targets in VSCode, but not in IntelliJ.

Edit: [Related comment](https://github.com/dart-archive/angular_analyzer_plugin/issues/120#issuecomment-264530466)

**Comment by bwilkerson** [comment]
The fact that it's working in VS Code strongly suggests that your implementation is correct.

Can you look at the protocol traffic log to see whether the navigation region you're producing is sent to the client?

**Comment by modulovalue** [comment]
I don't think that I'll be able to make this API work for my use case.

@bwilkerson
FYI: There is at least one other inconsistency between IntelliJ and VS Code (https://youtrack.jetbrains.com/issue/WEB-41424).
I'll close this now, but feel free to reopen it if you'd like to track this issue here.
