### ISSUE TITLE
[vm/ffi] `Pointer.fromFunction` on closures

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48865]
Currently, `Pointer.fromFunction` can only be called on top level static functions.

However, consider the following scenario:

1. A pre-existing native library that invokes callbacks. This code cannot be edited.
2. A generated `dart:ffi` binding for this native library.
3. An object-oriented API around these bindings. This API does not expose any `dart:ffi` types.
4. Users of this object-oriented API providing the callbacks.

Now we have a problem.

Users of the object-oriented API will have to provide their defined functions as `Pointer.fromFunction` calls, because the object-oriented API implementation cannot call `Pointer.fromFunction` on closures.

The typical workaround is to not use `fromFunction` on the users' top-level functions, but create a `Map<int, RetType Function(ArgumentTypes)>` in Dart, store the users' closures there, and use `fromFunction` on a function defined within the API. However, this requires an extra integer argument to be passed to the native library, and the native library should pass that integer back in its callback. And in this scenario we specified we don't own the native library.

If we would support callbacks on closures, this scenario could be supported.

In AOT, the function pointer created points to a trampoline which saves the callback id which identifies which function is used. We could possibly pre-allocate a bunch of these and assign the mapping from callback id to closure at runtime instead of compile time. But how many would we allocate? Would we let the users specify that? Would that be useful?

Since the _only_ piece of information we get when a callback is invoked is the address in memory, _and_ all executable pieces of code in memory need to be precompiled on iOS, I don't see another solution for supporting closures.

(Instead of supporting closures, we could explore using macro's to effectively inline the object-oriented API including a `fromFunction` call on the call-site of the API.)

Context: https://github.com/dart-lang/ffigen/pull/333/files#r855608183

**Comment by mkustermann** [comment]
ObjC can store such extra information as a persistent handle in the ObjC block, Java can do so in a Java object. Even C/C++ APIs often allow callbacks to get a peer pointer. As such the invoked top-level function can pick out the ObjC-block-variable, Java-instance-field or peer argument and get the closure/object from it.

Of course this will require the native side to free the persient handle when no longer needed (i.e. ObjC block destructor, Java finalizer on object, ...)

So this issue is mainly an issue for C/C++ APIs that don't pass peer information when invoking a callback, right?

**Comment by dcharkes** [comment]
> So this issue is mainly an issue for C/C++ APIs that don't pass peer information when invoking a callback, right?

Correct.

So far we've not run into a use case, but people keep asking. To which the answer usually is: peer pointer. (Especially if writing the C/C++ code themselves.) 🙃

**Comment by dcharkes** [comment]
Closure callbacks are now supported in `NativeCallable`s.

* edeac698c242e06cc5e961001a4209cbc9ab050b
* e8d7425c4ea8765c1e349db9197563dcb45b9638

We're not intending to add this to `Pointer.fromFunction`.
