### ISSUE TITLE
Completion inside a class includes static members from super-classes

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#48873]
For example:

```
class B {
  static int aae = 5;
  int aaf = 6;
}

class C {
  static int aaa = 1;
  int aab = 2;
}

class D extends C {
  static int aac = 3;
  
  int aad = 4;
  
  void m() {
    aa^
  }
}
```

Completing after `aa` in `m()` gives 4 suggestions: `aac`, `aad`, `aaa`, `aab` (in DartPad). `aae` and `aaf` are not included (rightly so). But `aaa` should also not be included; it is not in scope.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/242280
