### ISSUE TITLE
Analyzer doesn't warn on custom operators usage in constant constructor definitions

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#48889]
`Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64"`

Consider the bellow example:
```dart
class A {
  static const zero = A(0);

  final int val;

  const A(this.val);

  bool operator >(A a) => val > a.val;
  bool isMore(A a) => val > a.val;
}

class B {
  final A a;

  const B(this.a) : assert(a > A.zero); // no analyzer error
}

void main() {
  print(const B(A(9))); // analyzer error
}
```
the analyze produces no warnings for the constant `B` constructor but fails when trying to call it in `main` with const.

Running `dart analyze`:
```txt
Analyzing file.dart...                    1.8s

  error • file.dart:19:9 • Evaluation of this constant expression throws an exception. • const_eval_throws_exception

1 issue found.
```

What is more is if we replace:
```dart
const B(this.a) : assert(a > A.zero);
```
with:
```dart
const B(this.a) : assert(a.isMore(A.zero));
```

Running `dart analyze`:
```txt
Analyzing file.dart...                    1.6s

  error • file.dart:15:28 • Invalid constant value. • invalid_constant
  error • file.dart:19:9 • Evaluation of this constant expression throws an exception. • const_eval_throws_exception

2 issues found.
```

we get the expected `invalid_constant` error reported at the constructor definition.

**Comment by jellynoone** [comment]
Similarly it if we use the class as an annotation we only get an error reported at runtime rather than by the analyzer:
```dart
class A {
  static const zero = A(0);
  final int val;

  const A(this.val);

  bool operator >(A a) => val > a.val;
}

class B {
  final A a;

  const B(this.a) : assert(a > A.zero); // no analyzer error
}

@B(A(9)) // no analyzer error
void fn() {}

void main() {}
```

Running `dart analyze`:
```txt
Analyzing file.dart...                    1.4s
No issues found!
```
Running `dart run`:
```txt
file.dart:16:2: Error: Constant evaluation error:
@B(A(9)) // no analyzer error
 ^
file.dart:13:30: Context: The method '>' can't be invoked on 'A {val: 9}' in a constant expression.
 - 'A' is from 'file.dart'.
  const B(this.a) : assert(a > A.zero); // no analyzer error
                             ^
file.dart:17:6: Context: While analyzing:
void fn() {}
     ^
```

**Comment by lrhn** [comment]
That's actually correct behavior as currently specified, for (bad) historical reasons. 
It's something I think we should disallow (see https://github.com/dart-lang/language/issues/1296), and it's definitely fine to give a warning/hint for it.

**Comment by eernstg** [comment]
The error is actually reported at compile-time (by the common front end, CFE) when it says

> `file.dart:13:30: Context: The method '>' can't be invoked on 'A {val: 9}' in a constant expression.`

so the question is whether the CFE or the analyzer has the correct behavior.

The [following location](https://github.com/dart-lang/language/blob/bb6b4d1dc93668ab4f46d8170813d88bbf39a97d/specification/dartLangSpec.tex#L4366) in the spec says

```
Any expression that appears within
the initializer list of a constant constructor
must be a potentially constant expression
(\ref{constants}),
or a compile-time error occurs.
```

So we only require that `a > A.zero` must be a potentially constant expression. That is indeed true, because this requirement only checks that each of the operands is potentially constant.
