### ISSUE TITLE
Generics error with typedef

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#48898]
Can't seem to be able to use `typedef` and generics while it works when using the full function signature.

Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64"

```dart
class Foo {}

typedef Bar<T extends Foo> = void Function(T);

class Daz<T extends Foo> {
  void load(T t) {}
  
  void fus(void Function(T) fn) {}
  
  void foo(Bar fn) {}
  
  void daz() {
    fus(load); // OK
    foo(load); // error
    foo(load<T>); // error
  }
}
```

**Comment by mraleph** [comment]
`Bar` means `Bar<Foo>` (instantiate to bounds). You mean to write `Bar<T>` in `foo` signature:

```
  void foo(Bar<T> fn) {}
```

Then `foo(load)` will compile. 

`load<T>` does not compile because `load` is not a generic function itself so it expects no type arguments of its own.
