### ISSUE TITLE
When using systrace, the Dart timeline should not make clock calls

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#48900]
When recording to systrace output, we don't even send the `micros` to the buffer on any platform. So we end up making a bunch of calls to get the system clock time and discard it. This shows up in profiling as taking significant amounts of time.

/cc @rmacnak-google @bkonyi @a-siva  
/cc @iskakaushik @gaaclarke

**Comment by dnfield** [comment]
On the Flutter side, I think we're probably ok to just pass `0` when tracing to systrace. But I haven't traced through the VM code to see if that will remove all the places where it defaults arguments to the current timestamp.

**Comment by bkonyi** [comment]
I think we should be safe to not make those clock calls within the timeline code if we're using the systrace recorder since the system should be tracking this information.

**Comment by dnfield** [comment]
@rmacnak-google and I were just talking about this offline - for Fuchsia it will still be needed.
