### ISSUE TITLE
Support code completion of diagnostic names in the error section of analysis_options.yaml

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48904]
We support code completion of lint names in the `linter` / `rules` list. We should also support code completion of all diagnostic names in the `analyzer` / `errors` map.

**Comment by mnordine** [comment]
@bwilkerson another key I would love to see autocompleted is `enable-experiment` key. It should auto-complete the supported experiments. What do you think?

**Comment by bwilkerson** [comment]
That would certainly make sense to me.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/244920
