### ISSUE TITLE
Improve array loading times for large snapshots

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#48910]
In a large snapshot for customer: money there's significant time spent on array deserialization in the snapshot. This area seems like it could be improved to either do less work or do its work a bit faster.

From discussion with @a-siva and @rmacnak-google:

- can the array of class and function references in the dictionary of the library object be eliminated (except for those classes, functions that have the entry point pragma)
- consider placing arrays that only have references to RO Data objects in a special cluster and use offsets instead of ids in the reference table
- consider placing arrays that only have smis in a special cluster and use the actual smi values instead of ids in the reference table

**Comment by dnfield** [comment]
Some more assets are available at http://shortn/_09Yx1TBIBc (google only, sorry)

**Comment by mraleph** [comment]
> can the array of class and function references in the dictionary of the library object be eliminated (except for those classes, functions that have the entry point pragma)

Here is the breakdown of where arrays are coming from in terms of snapshot sizes. This was computed from heapsnapshot generated by `gen_snapshot`:

```
total: 1499344
%shared: 13 0.00%
ArtificialRoot.canonical_type_arguments: 15 0.00%
ArtificialRoot.canonical_type_parameters: 15 0.00%
ArtificialRoot.canonical_function_types: 15 0.00%
ArtificialRoot.canonical_types: 15 0.00%
ArtificialRoot.symbol_table: 15 0.00%
Class.functions_hash_table_: 1428 0.10%
Function.data_: 2810 0.19%
ArtificialRoot.symbol-table: 2819 0.19%
TypeParameters.names_: 6057 0.40%
FunctionType.named_parameter_names_: 7220 0.48%
ExceptionHandlers.handled_types_data_: 21562 1.44%
Class.functions_: 28170 1.88%
Class.fields_: 36647 2.44%
Class.interfaces_: 55533 3.70%
ArtificialRoot.libraries_map: 61223 4.08%
FunctionType.parameter_types_: 82887 5.53%
GrowableObjectArray.data_: 84556 5.64%
Library.dictionary_: 105438 7.03%
Class.invocation_dispatcher_cache_: 129244 8.62%
Class.constants_: 179990 12.00%
const Array: 693672 46.27%
``` 

Some of this is fairly trivial to prune:
- `Library.dictionary_ 105438 7.03%` drops non entry-points entirely
- `GrowableObjectArray.data_: 84556 5.64%` seems to come from `Library.used_scripts_: 51471 99.98%`. This field should just be dropped entirely in product AOT snapshots AFAIK. 
- `Class.constants_` I think this should be possible to drop as well (at least have a mode for that). I think it should only be needed for canonicalization of arriving messages sent between two different isolate groups. Maybe we can just have a special flag which disables multiple isolate groups in Flutter applications? (This is not properly supported by tooling anyway). /cc @mkustermann @aam

**Comment by mraleph** [comment]
```
Class.invocation_dispatcher_cache_: 129244 8.62%
```

This is caused by a bug which adds a lot of duplicated entries to these caches. I am going to fix this: 

-[ ] https://github.com/dart-lang/sdk/issues/48914

**Comment by aam** [comment]
> Maybe it would be better to simply prune the constants: Exclude any constant based on user-defined class/function and any constant transitively referencing such? We can measure and see what % we could remove.
> @aam Interested in looking at this?

Sure, created https://github.com/dart-lang/sdk/issues/48928 for that.

**Comment by rmacnak-google** [comment]
Related:
 - 706e62a1bf9f8c11053330821155ca1feae95dcf - [vm] Canonicalize empty Class::interfaces_.
 - 72c153b93084ead3e9d2079b2f3c9568d8fa2d09 - [vm] Keep snapshot cursor etc in registers during ReadFill.
 - 5748add35c24f87cc271fd563e01a37d9a46f92e - [vm] Use a big-endian encoding for snapshot ref ids.

**Comment by a-siva** [comment]
Here is the data for the GPay AOT snapshot from using the flag `print_array_optimization_candidates
`
```
INFO: From Flutter, aot, snapshotting //java/com/google/nbu/paisa/flutter/gpay/app:android_release_android_library_flutter_artifacts_android_aot:
Arrays
  total:  17416,  221765 elements
  smi-only:264,  16179 elements
  ro-only:1986 ,  18883 elements
  empty:160
Arrays
  total:  61449,  289799 elements
  smi-only:0,  0 elements
  ro-only:1247 ,  1879 elements
  empty:13288
VMIsolate(CodeSize): 3180
Isolate(CodeSize): 6029491
ReadOnlyData(CodeSize): 9108896
Instructions(CodeSize): 23826104
Total(CodeSize): 38967671
VMIsolate(HeapSize): 16684
Isolate(HeapSize): 14336996
Total(HeapSize): 14353680

```

**Comment by a-siva** [comment]
With https://github.com/dart-lang/sdk/commit/706e62a1bf9f8c11053330821155ca1feae95dcf - [vm] Canonicalize empty Class::interfaces_
the empty array references are gone reducing the number of array references by 13k

INFO: From Flutter, aot, snapshotting //java/com/google/nbu/paisa/flutter/gpay/app:android_release_android_library_flutter_artifacts_android_aot:
Arrays
  total:  17416,  221765 elements
  smi-only:264,  16179 elements
  ro-only:1986 ,  18883 elements
  empty:160
Arrays
  total:  48161,  289799 elements
  smi-only:0,  0 elements
  ro-only:1247 ,  1879 elements
  empty:0
VMIsolate(CodeSize): 3180
Isolate(CodeSize): 5963051
ReadOnlyData(CodeSize): 9108896
Instructions(CodeSize): 23826104
Total(CodeSize): 38901231
VMIsolate(HeapSize): 16684
Isolate(HeapSize): 14124388
Total(HeapSize): 14141072

**Comment by a-siva** [comment]
Another related fix https://dart-review.googlesource.com/c/sdk/+/243709 (Trim user-defined entries from classes constants table)

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/242862 (Avoids duplicate entries in invocation dispatcher cache).

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/242864 (Removes used_scripts field from AOT product builds)
This reduces the Arrays count from 45359 to 37990.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/244303 is the CL in progress to remove dictionary entries (The CL still has some failing tests that need investigation). A preliminary run of building the AOT snapshot including this CL shows the following stats
Arrays
  total:  29632,  96654 elements
