### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by kotdroidZero** [dart-lang/sdk#48922]
## Version information

- `IDEA AI-202.7660.26.42.7486908`
- `2.16.1`
- `AI-202.7660.26.42.7486908, JRE 11.0.8+10-b944.6916264x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.16, screens 1920x1080`

**Comment by asashour** [comment]
Any chance to get a reproducible example, with more error details pleas?
