### ISSUE TITLE
API to hot-restart (not hot-reload) the Flutter app?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#48933]
I need to control a Flutter app (running in dev mode), to make it hot-restart. Thus, I wonder how to implement it? What is the API call to, maybe, vmservice?

P.S. I see https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#reloadsources but it seems to be for hot-reload, not hot-restart.

I guess it is maybe not documented?

**Comment by a-siva** [comment]
Flutter tools has a mechanism to restart an app, I believe the Flutter engine starts the app on a new Isolate. This is also
supported in the IDE tools.

The VM service does not provide a mechanism to restart an app.

**Comment by fzyzcjy** [comment]
Thanks. Indeed I have found the solution: just mimic what devtools does to "hot restart".

**Comment by fodedoumbouya** [comment]
Hello @fzyzcjy. 
I wanna do the same thing but I am having trouble to mimic how devtools does to "hot restart".
can you please provide me how you did it.
Thank you very much

**Comment by fzyzcjy** [comment]
I guess it is: https://github.com/fzyzcjy/flutter_convenient_test/blob/13b555e0f17921cae2f5940330f850d6b70d265e/packages/convenient_test_manager_dart/lib/services/real_vm_service_wrapper_service.dart#L113

**Comment by fodedoumbouya** [comment]
Thanks
