### ISSUE TITLE
Pacstall

### ISSUE THREAD

**Issue by trymeouteh** [dart-lang/sdk#48930]
Please add this sdk into the pacstall repository. Pacstall is the AUR for Ubuntu which will allow Ubuntu users to easily install the sdk and receive updates very shortly after an update is released.

**Comment by sortie** [comment]
HI @trymeouteh,

For Ubuntu, we already provide Debian packages that you can install and get updates through your regular package management. See <https://dart.dev/get-dart#install-using-apt-get>.

Jonas
