### ISSUE TITLE
[analyzer] fix for `use_key_in_widget_constructors` should use super parameters when possible

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#48946]
For a case like:

```dart
import 'package:flutter/material.dart';

class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(context) => Container();
}
```

Adding 'key' to consturctor, would produce

```dart
const MyWidget({Key? key}) : super(key: key);
```

which is then offered to "convert to using super parameters".

It would be better to directly use super parameters on adding the 'key'.

`Dart SDK version: 2.18.0-75.0.dev (dev) (Sun May 1 14:47:57 2022 -0700) on "windows_x64"`

**Comment by pq** [comment]
Tagging as `P1` as `use_key_in_widget_constructors` is a flutter recommended lint.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/244242

**Comment by pq** [comment]
Fantastic.  Thank you!
