### ISSUE TITLE
Assertion failure in Api::NewArgumentError if Dart API already has a ReusableObjectHandleScope

### ISSUE THREAD

**Issue by jason-simmons** [dart-lang/sdk#48951]
Some Dart APIs in `runtime/vm/dart_api_impl.cc` acquire a `ReusableObjectHandleScope` (for example, `Dart_StringLength`)

If these APIs need to signal an error then they will call `Api::NewArgumentError`, which will instantiate an `ArgumentError` object.  To locate `ArugmentError` it will need to call `Library::LookupEntry`, which also acquires a `ReusableObjectHandleScope`.

IIUC Dart code should not enter a reusable scope if something else on the stack has already entered that scope.  If this happens with `dart_debug` enabled, then `Library::LookupEntry` causes an assertion failure.

I noticed this while trying to debug a Flutter engine patch that migrates Flutter to use Dart FFI for its native APIs (https://github.com/flutter/engine/pull/29607)

Prior to this patch Flutter did not see this assertion failure because it entered a `START_NO_CALLBACK_SCOPE` by the time `Api::NewArgumentError` was called.  `Api::NewArgumentError` would then exit with a pre-constructed error instead of trying to create an `ArgumentError`.

But any caller that goes through the `ArgumentError` path will get the double `ReusableObjectHandleScope`.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/243842
