### ISSUE TITLE
Migration tool: Add `!` for 'near-miss' promotion cases, or at least a hint slot.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#48956]
My code has a huge number of cases where promotion does not happen due to the tested value being the value of a field or getter.

![image](https://user-images.githubusercontent.com/2108821/166722330-ab740eae-5c6e-47f2-9ca4-25f37addecad.png)

The vast majority of cases like this should be migrated as `!`.
Stylistically, I think `!` is usually the correct approach because improvements to inference will automatically warn that the `!` is useless (unlike introducing a local).

If automatically adding `!` is a step too far, the tool should support manual hinting.
Currently there is nothing to click to manually hint.

**Comment by rakudrama** [comment]
In the above example it is very likely that `FrameEntry` could be sealed is the language supported it, improving
In this case I can't go to `register` and hint there as the type there is a type parameter.

The empty hinting space is fickle. If you hint, rerun, and remove the hint, that removes the hinting space, so you can't get back to where you were without rerunning again. (Rerunning on my app takes 20+ seconds, so I prefer not to need to do that.)

/cc @stereotype441 @srawlins

**Comment by srawlins** [comment]
You can add null-check comments after expressions (`frame.inlinedMethodName /*!*/`) in your source file. The preview UI may not have a button for adding that.

**Comment by srawlins** [comment]
> The empty hinting space is fickle. If you hint, rerun, and remove the hint, that removes the hinting space, so you can't get back to where you were without rerunning again. (Rerunning on my app takes 20+ seconds, so I prefer not to need to do that.)

Is this a separate issue? I don't really understand the steps.

**Comment by rakudrama** [comment]
1. Yes, I can switch between the UI and source but the tool often gets upset with changes from the UI and source, and at 20 seconds a pop, rerunning gets tedious.

2. Regarding the fickle behaviour - (a) use the UI to add a `/*!*/` hint (b) rerun the analysis, the hint is all red (c) click on the all red `/*!*/` and click on the "Remove /*!*/ hint" button. Now there is no way in the UI to add the hint back, since the hint 'space' has gone. It is related to the first issue in that there is nowhere to click to add a `/*!*/` hint.

**Comment by srawlins** [comment]
> Yes, I can switch between the UI and source but the tool often gets upset with changes from the UI and source, and at 20 seconds a pop, rerunning gets tedious.

Hmm I don't think this is expected. What do you mean by "upset?"

Are you saying that adding null-check hints in source is more tedious than the null-check hint button in the preview UI? Because it require re-running more often? Or just because of the back-and-forth between source and the preview UI? I don't think you should have to re-run from source more often one way or the other, but I may be mis-remembering how it works.

> Regarding the fickle behaviour

Ah interesting. Yeah this would be a separate bug. I wonder if CTRL+R would re-draw the hint space? Not sure.

**Comment by rakudrama** [comment]
I think what is going on when it gets 'upset' is that the tool can't insert a hint if the file has been changed in an editor, forcing me to re-run.

**Comment by srawlins** [comment]
Ahh yes. I see. So if you can make all the edits you want via the preview UI, then you don't need to re-run as often. But if you  make some changes via preview UI buttons, and some via source changes, you'd have to re-run at every source change. That is not fun.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
