### ISSUE TITLE
Add support to `dart analyze` for running with experiments

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#48960]
To support removing `dartanalyzer` in https://github.com/dart-lang/sdk/issues/48457.

**Comment by srawlins** [comment]
I was able to land the `--dart-sdk` flag, but this one seems much more complicated to implement:

I think it involves adding a `--enable-experiment` flag to the analysis_server snapshot, which would get pushed through to Driver, to SocketServer, to AnalysisServer, to ContextManager, to the ContextCollection. Maybe not too hard if it is just stored in AnalysisServerOptions, as that gets shared all the way from Driver down to ContextManager.

CC @bwilkerson @scheglov for thoughts.

**Comment by bwilkerson** [comment]
Yes, it's reasonable for those flags to be stored in the `AnalysisServerOptions`. I'd probably add the hooks for setting the values in `AnalysisContextCollectionImpl` and keep it out of the public API for now.

**Comment by scheglov** [comment]
Yes, using `AnalysisServerOptions` looks good.

We already have the hook in `AnalysisContextCollectionImpl`, see `updateAnalysisOptions` and how it is used in `analyzer_cli` specifically for this purpose.

**Comment by srawlins** [comment]
This should be complete.
