### ISSUE TITLE
[CP] [vm] Flush thread store buffer block after processing finalizers

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48964]
### Commit(s) to merge

78f218e

### Target

stable

### Issue Description

When `Finalizer`s and `NativeFinalizer`s are used in Flutter (and `dart` with `--use-compactor`), the GC can crash.

### What is the fix

Flush the store buffer during GC to account for write to the store buffer during the GC.

### Why cherry-pick

When `Finalizer`s or `NativeFinalizer`s are used in Flutter apps, those apps can crash.

Without the fix, developers have to work around this by allocating a new `Finalizer` or `NativeFinalizer` for every attachment. But we have no way of communicating that to all developers trying out finalizers.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/48843

### Extra Info

This is a 4 line fix:

https://dart-review.googlesource.com/c/sdk/+/243262/12/runtime/vm/heap/marker.cc
https://dart-review.googlesource.com/c/sdk/+/243262/12/runtime/vm/thread.cc

The rest is tests/logging.

@mraleph @rmacnak-google Would you consider this a low risk cherry pick?

cc @mkustermann

**Comment by athomas** [comment]
Based on an offline discussion with @mit-mit and @mraleph we're treating this as approved and will prepare a beta build with this CP. We can still decide not to publish this.

@itsjustkevin

**Comment by sortie** [comment]
I cherry-picked this change as 2.17.0-266.10.beta (fc290d1e2ee283a1169602744e3623f639c8a7ba).
