### ISSUE TITLE
update package:markdown to latest published version (5.0.0+) in DEPS

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#48967]
I tried to bump `package:markdown` but hit a snag with a failing internal test and had to revert (https://dart-review.googlesource.com/c/sdk/+/243800).   The internal issue with details is b/231525859.

@srawlins : maybe you could take a look?

**Comment by srawlins** [comment]
I would make this a P4; is there a reason it should be bumped soon?

**Comment by pq** [comment]
Great question.  I'm not sure how to assign priorities here and happy to defer to ecosystem folks.  A down-side to not staying up to date is that it keeps all of the vended packages w/ dependencies on markdown on older versions (because in theory they should have compatible version constraints w/ what's in the SDK).  Superficially, that affects pub scoring...  More substantially I think it's just more tech debt.

I guess the question I would ask is why are we publishing versions of packages and *not* keeping them up to date in the SDK?

**Comment by srawlins** [comment]
That all makes sense.

> I guess the question I would ask is why are we publishing versions of packages and not keeping them up to date in the SDK?

Hmm, what do you mean? Like why don't we do it on the same day? I'm certainly not proposing that we don't update the package in the SDK. We should, some day, according to priorities.

**Comment by natebosch** [comment]
We should be syncing these packages to the SDK, and especially to google3, _before_ we publish them.

**Comment by natebosch** [comment]
Publishing breaking changes which we can't yet accept in the SDK or google3 seems especially risky.

**Comment by srawlins** [comment]
Thanks for the reminder, @natebosch I had forgotten that. I'll mark this P3.

**Comment by pq** [comment]
WIP: https://dart-review.googlesource.com/c/sdk/+/245223.

**Comment by devoncarew** [comment]
@pq, @srawlins - do you know if markdown is now sync'd past the commit that was causing issues in google3? I see the above CL landed, but there are still ~15 unsynced markdown commits.

**Comment by srawlins** [comment]
Yep, should be.
