### ISSUE TITLE
Annotation required parameters are ignored

### ISSUE THREAD

**Issue by Ehesp** [dart-lang/sdk#48969]
This bug appears on both:

- Dart SDK version: 2.16.2 (stable)
- Dart 2.18.0 (build 2.18.0-91.0.dev)

Given the following code snippet:

```dart
class MyAnnotation {
  final String foo;

  const MyAnnotation({
    required this.foo,
  });
}

@MyAnnotation()
class MyClass {}

void main() {
  MyAnnotation();
}
```

The analyzer does not complain that the required `foo` parameter is missing when used as an annotation. However, it does when the class is instantiated (within main). I am able to omit the required values from the annotation when they should be required.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/243925

**Comment by Ehesp** [comment]
Dang thanks for the quick action!
