### ISSUE TITLE
Deprecate dart:html's document.registerElement & registerElement2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#48973]
- [ ] Mark these as `@Deprecated`
- [ ] Add an entry to the changelog for the next release
- [ ] Email the announce alias

**Comment by mit-mit** [comment]
@kevmoo @sigmundch is this the full list of deprecations for Dart 3?

If so, let's get the deprecations going. Preferably we should get them in ASAP. 

And then please update https://github.com/dart-lang/sdk/issues/49529 to list these as full discontinuations in Dart 3.0.

**Comment by sigmundch** [comment]
I sent a breaking change announcement today, specifically about these 2 APIs. Depending on the feedback, I think it may be possible to discontinue the API prior to Dart 3.

CL https://dart-review.googlesource.com/c/sdk/+/252840 will add the deprecation annotation.

That said, there is a related breaking change we should consider: the compilers today allow users to extend html elements and define their custom element classes. Without the custom element registration APIs, there is no value in doing that. Disallowing that users extend html element is a separate breaking change, though. The more I think about it, the more I feel compelled to push on that breaking change as well.

Thoughts?

/cc @rakudrama @srujzs @rileyporter

**Comment by kevmoo** [comment]
SGTM! :shipit: 👍 🤘

**Comment by srujzs** [comment]
> the compilers today allow users to extend html elements and define their custom element classes

Do these work as intended today? I don't remember if these were just broken with or without the custom element APIs.

> Disallowing that users extend html element is a separate breaking change

Is this the only native class we allow Dart classes to extend in our compilers? I agree that it doesn't make sense to continue allowing this once the custom element APIs go away. I know you mentioned there was an indirect way to do custom elements with interop - do we have a tracking bug/documentation on that? This comes up once in a while and it'd be useful to point users to the current way this is (somewhat) supported.

**Comment by sigmundch** [comment]
> Do these work as intended today? I don't remember if these were just broken with or without the custom element APIs.

Good question, I think you are right that they are not usable. That is, I don't believe there is a way to instantiate these classes without using registerElement and createElement('x-foo'). 

@rakudrama - do you recall if there are other ways to instantiate these classes?

> Is this the only native class we allow Dart classes to extend in our compilers?

I am not sure to be honest, we need to review the full list of native APIs, @rakudrama may have a hunch though :)

>  I know you mentioned there was an indirect way to do custom elements with interop - do we have a tracking bug/documentation on that?

I don't believe we have an official doc, so we should create one. The best references implementations we have are:
* this old demo written by Jenny: https://github.com/jmesserly/dart-custom-element-demo
* this package authored by Don: https://github.com/rampage-dart/rampage
