### ISSUE TITLE
duplicate_import diagnostic does not catch importing both relative and with a package: URI

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#48987]
If I have a file which imports the same library twice, as both `package:foo/src/bar.dart` and `bar.dart`, I'd expect either `duplicate_import` or `unnecessary_import`, but I don't see either.

See https://github.com/dart-lang/build/pull/3291

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/244183
