### ISSUE TITLE
json.encode doesn't produce valid json?

### ISSUE THREAD

**Issue by nohkumado** [dart-lang/sdk#48995]
Hello, 
as long as i dabbled inside a flutter env, everything was fine, considering an exerpt of the class below:

```
class ExamNode
{
  String question;
  Map<String,ExamNode> children = {};
  int level = 0;
  int sectionTime = 0;

 Map<String, dynamic> asMap() {
    Map<String, dynamic> tojson =
    {
      "isLeaf": isLeaf(),
      "question": question,
      "level": level,
      "sectionTime": sectionTime,
      "children": {},
    };
    children.forEach((key, node) {tojson["children"][key] = node.asMap(); });
    return tojson;
  }//end toJson()

String toJson()
  {
    Map<String, dynamic> tojson = asMap();
    //return json.encode(tojson);
    return jsonEncode(tojson);
  }
}
```

inside flutter i can convert the tree to a String and convert it back, but as soon as i send it anywhere else, it fails....

in the map, i have a boolean and 2 int, and those are inserted without enclosing " , whilst this poses no problem inside the flutter env, it does as soon as it gets send to some other python, php, what-ever backend.... those refuse to decode the json string because of that behaviour, how can i solve this?

**Comment by lrhn** [comment]
Can you describe the problem in more detail.

What is the generated JSON which is invalid?

Not quoting integers and booleans is valid JSON. If the other end expects string values instead of JSON numbers or boolean literals, you can do:
```dart
... toJson = 
  {
     "isLeaf": isLeaf().toString(),
     "question" :question,
     "level": level.toString(),
     "sectionTime": sectionTime.toString(),
     "children": { 
       for (var entry in children.entries) entry.key: entry.value.asMap()
     }
  };
```
That is, adding `.toString()` on the integer and bool values when creating the "JSON map" which will be converted to JSON.
Then the other receivers will see string values in the JSON source instead of JSON integers or booelans.

**Comment by nohkumado** [comment]
yes i do proper json decoding, and that's where i get the error from....
as soon as i feed the incoming json tothe decoder e.g. in php  to json_decode is hickups on the not stringified int's and bools...

your workaround, converting everything to string worked though, so i will use that....
