### ISSUE TITLE
double.clamp implementations are out of sync with typing rules

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#48990]
according to @lrhn [comment](https://github.com/dart-lang/sdk/issues/39652#issuecomment-690937501), `double.clamp` should return a `double` because its receiver is a `double`. That does not seem to be implemented correctly:

```
  num clamp(num lowerLimit, num upperLimit) {
    // TODO: Remove these null checks once all code is opted into strong nonnullable mode.
    if (lowerLimit == null) {
      throw new ArgumentError.notNull("lowerLimit");
    }
    if (upperLimit == null) {
      throw new ArgumentError.notNull("upperLimit");
    }
    if (lowerLimit.compareTo(upperLimit) > 0) {
      throw new ArgumentError(lowerLimit);
    }
    if (lowerLimit.isNaN) return lowerLimit;
    if (this.compareTo(lowerLimit) < 0) return lowerLimit;
    if (this.compareTo(upperLimit) > 0) return upperLimit;
    return this;
  }
```

**Comment by lrhn** [comment]
That comment was actually wrong.

The return type is `double` if *all* of the receiver and arguments are `double`s, which is satisfied by code which always returns one of those three. (And it's `int` if they are all `int`).
