### ISSUE TITLE
diagnostic should be produced when a deferred element is used in a constant context

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#48991]
For example:

a.dart:

```dart
class A {
  const A();
}

const aa = A();
```

b.dart:

```dart
import 'a.dart' deferred as a;

class B {
  const B(Object a);
}

main() {
  var b = const B(a.aa); // SHOULD PRODUCE DIAGNOSTIC
}
```

The front-end produces a warning like this:

    Error: 'aa' can't be used in a constant expression because it's marked as 'deferred' which means it isn't available until loaded.

But analyzer does not.

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/244281 adds a test to make sure the `LinterContext` handles this case.

**Comment by pq** [comment]
See also: b/230089181

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I was not able to fix it quickly and easily.
As we noticed somewhere else, constants evaluation is a mess.
