### ISSUE TITLE
missing_enum_constant_in_switch quick fix adds final fields of enum (new to Dart 2.17)

### ISSUE THREAD

**Issue by JarrodCColburn** [dart-lang/sdk#49003]
### Creating a switch statement on an enum (where enum contains a final field!) without all cases handled correctly produces  `missing_enum_constant_in_switch` hint. However, when clicking `quick fix` in VS Code, the fix incorrectly generates a case for the additional final field.

![asdfasdf-1652384867471](https://user-images.githubusercontent.com/16673615/168158053-343a98b3-f13f-430e-9947-c09d8c2a8366.gif)

**To Reproduce**
1. Create Enum with final field
```dart
enum Water {
  frozen(32),
  boiling(212);

  final int tempInFarhenheit; // <- final field
  const Water(this.tempInFarhenheit);
}
```
2. Create switch statement on Enum, without handling all enum cases
```dart
void whichWater(Water water) {
  switch (water) {
    case Water.boiling:
      break;
  }
  // don't include other cases
}
```
3. Allow vs code to suggest 'quick fix'
```dart
void whichWater(Water water) {
  switch (water) {
    case Water.boiling:
      //..
      break;
    case Water.frozen:
      break;
    case Water.tempInFarhenheit: // <-this shouldn't be here
      break;
  }
}

```

**Expected behavior**
The switch statement quick fix should not generate code for final fields.
```dart
// expected fix
void whichWater(Water water) {
  switch (water) {
    case Water.boiling:
      //..
      break;
    case Water.frozen:
      // ..
      break;
    // omits case for  Water.tempInFarhenheit
  }
}

```
**Additional context**
I'm not actually sure if this is a linter problem, VS Code problem, or some 3rd option. My apologies if I have entered this bug in wrong place as I really appreciate all the hard work you guys do.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/244626
