### ISSUE TITLE
False positive `unused_element` in Dart 2.17

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#49007]
When a value for an optional parameter is only given in a `super` constructor invocation, it seems like the analyzer now considers that parameter unused:

```dart
class _Foo {
  final String x;
  final int? y;

  _Foo(this.x, [this.y]); // Diagnostic: Value for parameter y isn't ever given
}

class Bar extends _Foo {
  Bar(String x) : super(x, 0); // but it is given here
}
```

On Dart 2.17, analyzing that file reveals this false-positive:

```
Analyzing foo.dart...                  1.2s

  error • foo.dart:5:22 • A value for optional parameter 'y' isn't ever given. Try removing the
          unused parameter. • unused_element

1 issue found.
```

As far as I remember that didn't happen in Dart 2.16.

**Comment by bwilkerson** [comment]
@srawlins

**Comment by srawlins** [comment]
Thanks for filing!

**Comment by carmas123** [comment]
@simolus3 this is not a false positive. This tip is shown when a parameter is never called and not only if it's used into the class.
