### ISSUE TITLE
dart:html inputMode should be nullable

### ISSUE THREAD

**Issue by mdebbar** [dart-lang/sdk#49014]
https://api.dart.dev/stable/2.9.1/dart-html/Element/inputMode.html

**Comment by parlough** [comment]
Hey @mdebbar, I believe [inputMode](https://api.dart.dev/stable/2.17.0/dart-html/Element/inputMode.html) is nullable already. The docs you linked are for Dart 2.9.1 though which precedes the release of null safety.

**Comment by mdebbar** [comment]
@parlough thanks for the clarification! I linked to the one that showed up on Google Search and didn't notice the version number.

We don't need this issue anymore. Closing.
