### ISSUE TITLE
Code suggestion for initState/dispose/setState no longer works in Flutter 3

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#49027]
Original issue:
https://github.com/flutter/flutter-intellij/issues/6167

-----

With Flutter 3.0, code suggestion for initState/dispose/setState no longer works. It worked for Flutter 2.10.
This issue was found in both Windows(10) and Mac(12.3.1).

Steps to Reproduce
Start typing in ini.
Hit control-space for auto suggestions
Nothing comes up yet.
<img width="750" alt="Image" src="https://user-images.githubusercontent.com/12907755/168500713-3e691dbe-75c9-423c-bb37-d7dac649f2a6.png">

（It worked in Flutter 2.10.x）
<img width="750" alt="Image" src="https://user-images.githubusercontent.com/12907755/168500746-91588056-14f2-41ee-a2e4-3c6c3d478fa1.png">

The screenshots are for initState, but the same thing happens with dispose and setState.

Version info
`Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
[✓] VS Code (version 1.67.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

-----

I can confirm that changing the Flutter SDK from 2.10.5 to 3.0.0 causes this issue. You need to be editing the definition of a class that extends `State` and start to type a new method definition by typing `ini`. Prior to the upgrade you would see a suggestion to create a method named `initState()`. After the upgrade there are no suggetions.

@bwilkerson

**Comment by bwilkerson** [comment]
I believe that @scheglov has fixed this on HEAD. It might be worth filing a cherry pick request for it.

**Comment by ldsouza93** [comment]
I'm facing the same issue, anyone could fix it?

**Comment by srawlins** [comment]
@scheglov do you think Brian is correct?

**Comment by scheglov** [comment]
Yes.

**Comment by scheglov** [comment]
This was fixed in https://dart-review.googlesource.com/c/sdk/+/244363 and more tests added in https://dart-review.googlesource.com/c/sdk/+/244726

**Comment by keybow007** [comment]
It still seems to be unresolved even with Flutter 3.0.1.

![スクリーンショット 2022-05-21 5 55 53](https://user-images.githubusercontent.com/12907755/169609645-be5905c1-0be8-4065-b71d-42fe62a99f05.png)

(flutter doctor)

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
[✓] VS Code (version 1.67.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
`

**Comment by srawlins** [comment]
We could consider this for a cherry-pick.

**Comment by Pynman** [comment]
Faced the same issues.

**Comment by vsmenon** [comment]
@srawlins - is this still an open issue?  It looks like the fix landed and is being cherry-picked.

**Comment by srawlins** [comment]
I think that's right. It looks like @scheglov filed the cherry-pick here: https://github.com/dart-lang/sdk/issues/49086, which has been marged and released.

**Comment by keybow007** [comment]
Thanks for fixing.

I just tried it with Flutter 3.0.2.

initState and dispose did code completion properly.

(initState / dispose in Flutter 3.0.2)
![スクリーンショット 2022-06-11 x5 33 05](https://user-images.githubusercontent.com/12907755/173147482-f450bca9-3f1c-4c4e-b144-42e3d703936e.png)

Unfortunately, however, code completion for setState does not seem to work yet.

(setState in Flutter 3.0.2 => no suggestion)
![スクリーンショット 2022-06-11 5 33 39](https://user-images.githubusercontent.com/12907755/173147663-6b2ad959-3dc3-490d-abfa-4aa8f10375ad.png)

(setState in Flutter 2.10.5 => work properly)
![スクリーンショット 2022-06-11 5 41 20](https://user-images.githubusercontent.com/12907755/173147690-fb79952b-556e-4fe2-adb7-e304a4451de3.png)

Since setState is a very commonly used and important method, it would be helpful if it could be resolved as soon as possible.

Thanks.

**Comment by vsmenon** [comment]
@keybow007 - could you please create a new issue and link to here?  Don't want that to get lost in a closed issue.  Thanks!

**Comment by keybow007** [comment]
Thank for reply. I created a new issue.
https://github.com/dart-lang/sdk/issues/49233

**Comment by Nathan617** [comment]
Same here. setState and colors are not autocompleting anymore. Waiting for a fix

**Comment by bodadrop2022** [comment]
Same here!!

**Comment by scheglov** [comment]
See https://github.com/dart-lang/sdk/issues/49233#issuecomment-1165043997

**Comment by khanahsan** [comment]
> See [#49233 (comment)](https://github.com/dart-lang/sdk/issues/49233#issuecomment-1165043997)

please see this i'm still face this issue

Code suggestion for async/dispose/setState no longer works in Flutter 3.0.2 #106724

**Comment by khanahsan** [comment]
[Code suggestion for async/dispose/setState no longer works in Flutter 3.0.2 #106724
](https://github.com/flutter/flutter/issues/106724)

i'm still face this issue in Android Studio i use dart 2.17.3 version

**Comment by n-apps** [comment]
Can confirm. setState is not autocompleting in Android Studio (version 2021.2)

```
• Flutter version 3.0.4 
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 85684f9300 (6 days ago), 2022-06-30 13:22:47 -0700
• Engine revision 6ba2af10bb
• Dart version 2.17.5
• DevTools version 2.12.2
```

**Comment by Nathan617** [comment]
Just did the update to Flutter 3.0.5 for Mac native M1 (with Android Studio version 2021.2 native M1) and colors autocomplete as well as setState autocomplete work fine now

**Comment by n-apps** [comment]
> Just did the update to Flutter 3.0.5 for Mac native M1 (with Android Studio version 2021.2 native M1) and colors autocomplete as well as setState autocomplete work fine now

Can confirm. Upgrading to 3.0.5 fixed it for me.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/16646251/178929818-adc71226-f80d-4ed2-8819-f29452f47f59.png">
