### ISSUE TITLE
Defining a variable with the name 'name' in an enum causes a syntax error in Flutter Web

### ISSUE THREAD

**Issue by RahmiTufanoglu** [dart-lang/sdk#49021]
**Describe the issue**
After updating to **Dart 2.17** and **Flutter 3.0** I made use of the new capabilities of **Enums**. However, the explicit creation of a variable with the name **'name'** causes an _'Identifier 'name' has already been declared'_ in the Chrome console after running the **Flutter Web** application.

**To Reproduce**
```
enum MyEnum {
  hello(name: 'Foo'),
  world(name: 'Bar');

  final String name;

  const MyEnum({required this.name});
}
```

**Expected behavior**
Flutter Web application will not be executed. Google Chrome console shows _'Uncaught SyntaxError: Identifier 'name' has already been declared_.

**Additional context**
Flutter for mobile still works fine. The issue is only related to Flutter Web.

**Comment by srawlins** [comment]
Perhaps a dart2js or DDC issue?

**Comment by liamappelbe** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/245082

Interestingly this was a bug in the CFE, but since enum constructors are never invoked by the user, the VM wasn't compiling them. That's why it only showed up on the web.

**Comment by liamappelbe** [comment]
Actually, DDC might need to separately fix this issue. I don't know enough about DDC to know for sure, so I'll leave this issue open for now.

**Comment by liamappelbe** [comment]
Apparently DDC uses the same CFE as the VM and dart2js, so my CFE fix should have fixed the bug for DDC too.
