### ISSUE TITLE
[CP] Run 'dart pub' in PluginManager.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#49028]
### Commit(s) to merge

9fa6817

### Target

stable, I think

### Issue Description

Using an analyzer plugin with Dart 2.17 causes analyzer to crash. It occurs on developer platforms.

### What is the fix

The fix is to shell out to `dart pub` rather than `pub`.

### Why cherry-pick

Some number of users use analyzer plugins. At least 6 users have +1'd the issue since Dart 2.17 was released. I believe the users who use analyzer plugins may not have any Dart Analysis Server integration from their IDE, when using Dart 2.17.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/48682

**Comment by vsmenon** [comment]
Nice to see a fix that also looks like code simplification.  :-)

lgtm

**Comment by athomas** [comment]
Merged to stable in edf0ab222395c4b13c3e52a18900dd62702b639f (2.17.1).

**Comment by athomas** [comment]
Dart will be released today. Flutter is usually released on the same day as Dart.
