### ISSUE TITLE
[CP] [vm/ffi] Support `late` `Finalizable` variables

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#49024]
### Commit(s) to merge

e418026d74b6c666a7fcb30278a2b10ed97fdb29

### Target

stable 2.17.1

### Issue Description

`late` variables with (sub)type `Finalizable` throw `LateInitializationError`s when initialized by assignment instead of immediately on the variable declaration.

```dart
class Foo implements Finalizable {}

void main() {
  late Foo foo;
  foo = Foo();
  print(foo);
}
```

```
Unhandled exception:
LateInitializationError: Local 'foo' has not been initialized.
```

`Finalizable`s are kept alive by inserting `reachabilityFence`s, and the argument to the fence causes a field-load which get checked for being initailized.

### What is the fix

Don't check field-loads for the sentinel value (the value representing that a late field is not initialized) when the field load is an argument to the `reachabilityFence` method.

### Why cherry-pick

We have released `NativeFinalizer`s in Dart 2.17, and any native resource should implement the `Finalizable` interface.

None of these native resources can then be used in `late` variables.

(Concrete use case: automatic reference counting for Objective C objects in `package:ffigen`. cc @liamappelbe @brianquinlan)

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/49005

### Extra Info

cc @mkustermann @mraleph Thanks for your input on the fix!

**Comment by athomas** [comment]
Merged to stable in edf0ab222395c4b13c3e52a18900dd62702b639f (2.17.1).
