### ISSUE TITLE
Flutter frontend compile tests failing after .packages file removed

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#49026]
The flutter-frontend builder is failing, because it is no longer running any tests.
The script that generates the compilation tests depends on the .package files, which
have just been removed.

For example,
https://dart.googlesource.com/sdk/+/c4c9dc599451f95cc0f845cc4d15387ec7310621/pkg/frontend_server/test/frontend_server_flutter.dart#94
is using the .packages files.

I am removing this builder from the CQ until this is fixed.

@scheglov @jensjoha @devoncarew @stereotype441

**Comment by whesse** [comment]
Builder removal CQ: https://dart-review.googlesource.com/c/sdk/+/244927

**Comment by jensjoha** [comment]
Fixed with 787f83acabe17887a1bf7f4cd8febbe34f1143c1.
