### ISSUE TITLE
Analyzer trips up on super constructor parameters

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#49032]
This tracker is for issues related to:
* Analyzer

## platform
macOS

## version
Dart SDK version: 2.18.0-117.0.dev (dev) (Sun May 15 20:46:12 2022 -0700) on "macos_x64"

## steps to reproduce
1) check out flutter
1) `cd <flutter>`
1) `./bin/dart --enable-asserts dev/bots/analyze.dart`

## observed output
```
Unhandled exception:
Invalid argument(s): Content produced diagnostics when parsed:
  EXPECTED_TOKEN: Expected to find '}'. - 54:18
```

Example line that generates the EXPECTED_TOKEN error: https://github.com/flutter/flutter/blob/03be77dbf0315d32db5b0069637fbdb9cb2c91b5/packages/flutter/lib/src/foundation/diagnostics.dart#L2430

The analyzer is running with `FeatureSet.fromEnableFlags2(sdkLanguageVersion: Version.parse('2.17.0-0'), flags: <String>['super-parameters'])` so it seems related to `super-parameters`.

**Comment by asashour** [comment]
With flutter `master`, I have some different result on Windows 10:

```
C:\use\flutter> bin\dart --enable-asserts .\dev\bots\analyze.dart
...
Skip test comments...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
C:\use\flutter\dev\bots\test\prepare_package_test.dart:363: skip test without a justification comment.
C:\use\flutter\dev\bots\test\sdk_directory_has_space_test.dart:20: skip test without a justification comment.
...
...
C:\use\flutter\packages\flutter_tools\test\general.shard\macos\xcode_validator_test.dart:73: skip test without a justification comment.

See: https://github.com/flutter/flutter/wiki/Tree-hygiene#skipped-tests
```

**Comment by gaaclarke** [comment]
Yea, it appears to work on linux too since flutter's CI runs it just fine.  For some reason, being on macOS seems key.

**Comment by devoncarew** [comment]
(Note: we recently added a ['no response'](https://github.com/dart-lang/sdk/wiki/Triaging-Dart-SDK-issues#using-the-needs-info-label) bot to our repo; it may have closed existing issues with the `needs-info` label incorrectly. If you think your issue was effected, please feel free to reopen the issue)
