### ISSUE TITLE
[CP] [pkg/dart2native] Handle cases where linker-signed is not an option.

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#49041]
### Commit(s) to merge

4e520ec7

### Target

stable

### Issue Description

As seen on #49010, attempting to compile dart code to a standalone executable on older versions of macOS (<= 11.0) fails when attempting to override the original signature for `dartaotruntime`. This is because the `codesign` executable does not support the `linker-signed` option, which we use to add a signature that can be overwritten by the developer without requiring the `-f`/`--force` flag be passed to `codesign`.

This wasn't seen in testing because only X64 runs macOS <= 11.0, and tests are run using a locally built unsigned SDK, and the code for signing standalone executables only executes if `dartaotruntime` is signed.

### What is the fix

The basic fix is to not fail immediately when `codesign` fails when passed the `linker-signed` option. Instead, we then fallback to overriding the signature without that option, and only fail at this step if that second attempt also fails.

In the full fix, since `linker-signed` signatures still require being force overridden for versions of macOS < 11.0 even when that option is recognized, we only perform the `linker-signed` attempt on macOS >= 11.0, and also print a warning if that fails and we fall back to the non-linker-signed attempt.

The commit also adds a test for signing `dartaotruntime` in the locally built SDK and then attempting to compile a standalone executable with it, triggering the standalone executable signing behavior even on X64.

### Why cherry-pick

Currently Dart users that cannot upgrade their development platforms past macOS 10.15.x cannot create standalone executables.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/49010

**Comment by mit-mit** [comment]
cc @athomas

**Comment by mit-mit** [comment]
SGTM, I think we should pick this

**Comment by a-siva** [comment]
This change is fairly low risk and addresses a P1 issue with codesigning on macOS. The Fix essentially checks for the macOS version and uses the 'linker-signed' option only when the version is > 11.0. There is a test case associated with the change. I would recommend approving this cherry pick.

**Comment by athomas** [comment]
Merged to stable in edf0ab222395c4b13c3e52a18900dd62702b639f (2.17.1).
