### ISSUE TITLE
`Isolate.exit()`s synchronous message validation happens in `NoSafepointScope` which harms responsiveness

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#49050]
The message validation code for `Isolate.exit()` runs synchronously in `NoSafepointScope`, see [runtime/lib/isolate.cc](https://github.com/dart-lang/sdk/blob/5f9de6dad476d8c097d23dbc8009a128a7499994/runtime/lib/isolate.cc#L191):
```

static ObjectPtr ValidateMessageObject(Zone* zone,
                                       Isolate* isolate,
                                       const Object& obj) {
  ...
  {
    NoSafepointScope no_safepoint;
    ...
    while (!working_set.is_empty() && !error_found) {
      ...
    }
}
```

This is not a problem if no other threads want to safepoint, but if e.g. a UI isolate allocates widgets and will want to GC, it may have to wait for a long time (depending on how large the `Isolate.exit()`ed message is).

See a reproduction in [isolate_exit_pause_time_issue.dart](https://gist.github.com/mkustermann/ef910a4554068df50323272d53355cdf#file-isolate_exit_issue_repro-dart), which results in:
```
.Min(RunTimeRaw): 0.001 ms.
.Avg(RunTimeRaw): 388.26340250000004 ms.
.Percentile50(RunTimeRaw): 53.022 ms.
.Percentile90(RunTimeRaw): 1335.022 ms.
.Percentile95(RunTimeRaw): 1535.022 ms.
.Percentile99(RunTimeRaw): 1695.022 ms.
.Max(RunTimeRaw): 1734.022 ms.
```

/cc @aam Could you look into this?

**Comment by aam** [comment]
> /cc @aam Could you look into this?

Sure, thank you for putting the benchmark together. 10M objects in the exit message is quite a bit though! :-)

**Comment by mkustermann** [comment]
> Sure, thank you for putting the benchmark together. 10M objects in the exit message is quite a bit though! :-)

Some users do run `compute()` where the function parses 100 MB files. See https://github.com/d-markey/squadron/issues/7#issuecomment-1116190118:

> Once I got the overall parse time for a 100MB VCD file down below the 30 seconds mark, performance was less of a consideration if it was happening in the background. In my case, the UI would freeze in debug mode and be more responsive in release mode (I can't remember for sure now, but I think that was native... can't remember web'.

**Comment by mkustermann** [comment]
Thanks for looking into it, @aam !
