### ISSUE TITLE
Analyzer, treat `@required` in null-safe code as a deprecation notice.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#49066]
In null-safe code, the `@required` annotation is no longer useful. (There is currently no warning if you use it anyway, according to dartpad.)

I suggest repurposing it for a "deprecating optionality".

That is, an optional parameter can still be marked as `@required` in null safe code, and it will then trigger a warning to omit the corresponding argument, just as in non-null safe code. The purpose is to mark parameters which will stop being optional in a later release, effectively *deprecating* the parameter *being optional*, but not the parameter itself. It would then also apply to positional parameters.
That's not something we can otherwise represent, using a `@Deprecated` annotation will deprecated the parameter itself.

Alternatively, introduce a more specifically named `@DeprecatedOptional(message)` annotation with the same meaning.

**Comment by bwilkerson** [comment]
A different name would probably be better; users might be confused because the old and new semantics are so different. I might propose `@soonToBeRequired`.

**Comment by matanlurey** [comment]
I am going to assume that this otherwise deprecated annotation is not going to receive more analysis support.

Closing as not-planned.
