### ISSUE TITLE
Error with const and named parameters anywhere

### ISSUE THREAD

**Issue by olof-dev** [dart-lang/sdk#49087]
There seems to be an issue with the named parameters anywhere feature of Dart 2.17 and the const keyword. Running this program:

```dart
class Robot {
  final String name;
  final EngineType engineType;

  const Robot(this.name, {required this.engineType});
}

enum EngineType { nuclear, warp }

void main() {
  final rob = const Robot(engineType: EngineType.nuclear, "Rob");
  print(rob.name);
}
```

produces the output

```
test.dart:11:21: Error: Constant evaluation error:
  final rob = const Robot(engineType: EngineType.nuclear, "Rob");
                    ^
test.dart:11:50: Context: The variable '(unnamed)' is not a constant, only constant expressions are allowed.
  final rob = const Robot(engineType: EngineType.nuclear, "Rob");
```

If you make it `const rob = Robot(...)` instead, if runs just fine, so I guess it's just a parser error.

Thanks so much for your awesome work on Dart!

```
dart --version
Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "linux_x64"
```

**Comment by eernstg** [comment]
Here's another small change which makes the program run with no errors: Change `engineType: EngineType.nuclear, "Rob"` to `"Rob", engineType: EngineType.nuclear`. This points in the direction of the 'named parameters anywhere' feature.

**Comment by lrhn** [comment]
Good guess. I'm guessing "named parameters anywhere" introduces temporary variables to remember the expression order, and those temporary variables are not constant. They should be when the expression is constant.

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/245860.
