### ISSUE TITLE
2.17.1 can't be install

### ISSUE THREAD

**Issue by bshlomo** [dart-lang/sdk#49089]
please look at the image
![2 17 1 install error](https://user-images.githubusercontent.com/42788959/169860526-8cc9bc1a-8f10-42ca-ab58-25f4bbf6d5de.png)

**Comment by athomas** [comment]
This looks like a community maintained installer.

**Comment by athomas** [comment]
@bshlomo contact the maintainer of the installer.

**Comment by bshlomo** [comment]
@athomas
Who is the maintainer of this installer?
![2 17 1 install error -2](https://user-images.githubusercontent.com/42788959/169992947-0e5de3c1-f6ad-4d96-8096-aa93541f173a.png)

**Comment by athomas** [comment]
@bshlomo the answer is _literally_ in that email: "GeKorm" is the maintainer. Just because I tried to help you before doesn't mean I maintain that installer.

**Comment by bshlomo** [comment]
@athomas
Thank you for past help and thank you for the current help
it is obvious
