### ISSUE TITLE
quick fix idea to resolve an error type, add `await`

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#49114]
```
if(**file.exists()**) {}
```

The bold text above yields: Conditions must have a static type of 'XYZ'. (Documentation)  Try changing the condition.

The fix I expected was to add `await`, the non-equal static types here are bool and Future<bool>.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/246100

**Comment by bwilkerson** [comment]
Would you expect to see this fix in a function whose body is not already marked as `async`? If so, should we automatically add the `async` keyword and update the return type, or would you prefer to apply a second fix?
