### ISSUE TITLE
[CP] Issue 49097. Resolve constants in enhanced enum constructors/methods.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#49117]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/246041

### Target

stable

### Issue Description

https://github.com/dart-lang/sdk/issues/49097

There was a bug in enhanced enums implementation in the analyzer - we failed to resolve default values for constructors and methods.

### What is the fix

With the referenced CL we will resolve these constant expressions.

### Why cherry-pick

This bug causes false positive diagnostics reported.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/49097

**Comment by mit-mit** [comment]
Including this with the next batch of picks SGTM

**Comment by vsmenon** [comment]
lgtm
