### ISSUE TITLE
Flutter Layout spends 50% of its time in "File backed page in"

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#49119]
This tracker is for issues related to:

* Dart VM

I've been investigating the performance of the Layout operation in Flutter and I was surprised to find that a large amount of time spent in layout isn't actually occupied in CPU.  I'm seeing that 50% of the time is spent in VM page faults.

For this example I'm just using the default Flutter project that is just simply a button.  I'm running on an iPhone SE 2 (3 GB ram), with the Profile configuration.  I've added signposts around the Layout event [here](https://github.com/flutter/flutter/blob/cc733660ed9108893ab8c6728c802b76cc282f4d/packages/flutter/lib/src/rendering/object.dart#L948).

What I'm seeing is that during the 25ms it takes to execute Layout, the thread is only active 16ms:
<img width="695" alt="Screen Shot 2022-05-26 at 1 28 58 PM" src="https://user-images.githubusercontent.com/30870216/170574823-c6b1709c-cc78-439b-9d4b-9423680a89e2.png">

The total time spent in system calls for this time range is 128 µs, so it isn't because of system calls that the thread is not running.

If you look at the virtual memory usage though, a large percentage of time is spent in page faults (11.56ms):
<img width="719" alt="Screen Shot 2022-05-26 at 1 31 18 PM" src="https://user-images.githubusercontent.com/30870216/170575301-ac3863b3-e8a9-4504-a4b4-2b021bf94732.png">

Looking at the timeline, we see that the time the thread is inactive is correlated to the "File backed page in":
<img width="1471" alt="Screen Shot 2022-05-26 at 1 34 07 PM" src="https://user-images.githubusercontent.com/30870216/170575606-a9abc953-bad2-41e7-be25-6d8b3affe1d4.png">

I don't know what the solution to this problem is, but given that this is the simplest Flutter project you can make on a device with a reasonable amount of RAM, we shouldn't be spending 50% of our time with page faults.

cc @a-siva @mraleph

**Comment by gaaclarke** [comment]
I wonder if this is related to locality, where loading the renderobject tree is taking us all over the place in memory.  It might not be so much a problem with the Dart VM but a result of our data structure.

**Comment by dnfield** [comment]
It's really hard to get good data locality in UI applications...

**Comment by gaaclarke** [comment]
Would "File backed page in" actually be used for our datastructure though, or would iOS only use that for read-only memory like machine code?

**Comment by gaaclarke** [comment]
After looking through the profiles a bit I'm pretty sure this related to paging in the compiled code.  I'm not sure if there is a way we can make this more efficient?  Maybe using differ optimization flags to reduce code size, making sure debugging symbols aren't blowing up code size, maybe prefetch certain symbols we know will be required at startup for every flutter project?  I don't have any experience making these sort of optimizations.  Maybe the VM team will have a better idea if there is something actionable here.

**Comment by dnfield** [comment]
@mraleph had talked at some point about profiler guided layout for code.

**Comment by mraleph** [comment]
For starters we can try something simpler than PG based code layout - try to arrange code based on unweighted call-graph. 

> I don't know what the solution to this problem is, but given that this is the simplest Flutter project you can make on a device with a reasonable amount of RAM, we shouldn't be spending 50% of our time with page faults.

I would expect that page-faults reduce/disappear after initial startup? Is this not the case? Can you look at how number evolve in several subsequent layouts?

**Comment by gaaclarke** [comment]
Slava in a different channel suspects it is not the presence of debugger symbols which is causing page faults since they are supposed to be placed in a different part of the binary, not inline with the code.  As an experiment I was asked to try turning off the profiler which I did with the following diff:
```diff
--- a/runtime/dart_vm.cc
+++ b/runtime/dart_vm.cc
@@ -209,9 +209,9 @@ static std::vector<const char*> ProfilingFlags(bool enable_profiling) {
 // Disable Dart's built in profiler when building a debug build. This
 // works around a race condition that would sometimes stop a crash's
 // stack trace from being printed on Android.
-#ifndef NDEBUG
+//#ifndef NDEBUG
   enable_profiling = false;
-#endif
+//#endif
```

It looks like that eliminated the VM page faults too:
<img width="670" alt="Screen Shot 2022-05-31 at 11 48 51 AM" src="https://user-images.githubusercontent.com/30870216/171263687-8a5638c2-58c9-48e3-9ba8-8e70de51efe1.png">

I'm not sure what the action items are now.  For sure benchmarks should be making sure they don't have the dart profiler turned on.  I don't know if there is any other work we should be doing.  If we could avoid the overhead until someone actually attaches to the profiler that would be nice too.

**Comment by mraleph** [comment]
Thanks for running the experiments @gaaclarke! 

It would be great to understand why exactly profiler is triggering this, but I think realistically this might be rather hard to figure out given how sealed and non-transparent iOS is so I will just close this one as resolved.
