### ISSUE TITLE
NoSuchMethod error for JS interop tear-off in dart2js

### ISSUE THREAD

**Issue by rileyporter** [dart-lang/sdk#49129]
For JS interop members with a nested @JS name, e.g. `console.log`, dart2js is not generating the member name correctly when using the member as a tear-off.

Minimal repro:
```dart
import 'package:js/js.dart';

@JS('console.log')
external String consoleLog(
  Object? arg1, [
  Object? arg2,
  Object? arg3,
  Object? arg4,
  Object? arg5,
  Object? arg6,
  Object? arg7,
  Object? arg8,
  Object? arg9,
  Object? arg10,
]);

void main() {
consoleLog("foo");      // OK
(consoleLog)("foo");   // error
}
```

Looking at the JavaScript, in dart2js we are generating `self["console.log"]` for the tear-off, instead of `self.console.log`.

A workaround is to call the tear-off inside a closure:
```
((a) => consoleLog(a))("foo");
```

Another workaround would be to declare the JS interop member for the `console` object separately, and then declare the `consoleLog` JS interop function as a `log` member on `console`, without the two-level `console.log` name.

**Comment by sigmundch** [comment]
I believe the issue here is likely in the templates we use to generate tearoff stubs. Here is a tentative fix: https://dart-review.googlesource.com/c/sdk/+/246340, but I'll wait to hear from @rakudrama to make sure this is the right approach.
