### ISSUE TITLE
How to generate Element id?

### ISSUE THREAD

**Issue by RicoLiu** [dart-lang/sdk#49123]
Hi, I have a question.

```
/// element.dart
/// The unique integer identifier of this element.
  int get id;
```

What is the generation rule for this Id?

**Comment by lrhn** [comment]
The traditional way to give each instance of a class a unique ID is to have a static counter
```dart
class MyElement {
  static int _idCounter = 0;

  final int id = _idCounter++;
  ...
}
```
That way each object you create gets an integer ID different from all previously used IDs (at least as long as you don't create more than 2^64 instances, 2^53 on the web, which you won't).

**Comment by a-siva** [comment]
The `element.dart` that you refer to above is code from your project or from some published Dart package ?

**Comment by lrhn** [comment]
Makes sense, it's a reference. Seems to be [in the analyzer](https://pub.dev/documentation/analyzer/latest/dart_element_element/Element/id.html).

**Comment by jcollins-g** [comment]
Closing as the question seems to be answered?
