### ISSUE TITLE
fetch dart  has something wrong!

### ISSUE THREAD

**Issue by pythonName** [dart-lang/sdk#49124]
Running: gclient root
Updating depot_tools...
Running: gclient config --spec 'solutions = [
  {
    "name": "sdk",
    "url": "https://dart.googlesource.com/sdk.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Updating depot_tools...
Running: gclient sync
Updating depot_tools...

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://dart.googlesource.com/sdk.git /Users/xxx/Documents/GitHub_MySelf/dart-sdk/_gclient_sdk_w6wyde6q' in '/Users/xxx/Documents/GitHub_MySelf/dart-sdk'
Cloning into '/Users/xxx/Documents/GitHub_MySelf/dart-sdk/_gclient_sdk_w6wyde6q'...
remote: Total 1248298 (delta 919221), reused 1248298 (delta 919221)
Receiving objects: 100% (1248298/1248298), 1.35 GiB | 8.33 MiB/s, done.
Resolving deltas: 100% (919221/919221), done.
Syncing projects: 100% (100/100), done.
Running hooks: 100% (8/8), done.
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Traceback (most recent call last):
  File "/Users/xxx/Documents/GitHub_MySelf/depot_tools/fetch.py", line 285, in <module>
    sys.exit(main())
  File "/Users/xxx/Documents/GitHub_MySelf/depot_tools/fetch.py", line 280, in main
    return run(args, spec, root)
  File "/Users/xxx/Documents/GitHub_MySelf/depot_tools/fetch.py", line 274, in run
    return checkout.init()
  File "/Users/xxx/Documents/GitHub_MySelf/depot_tools/fetch.py", line 153, in init
    self.run_git(
  File "/Users/xxx/Documents/GitHub_MySelf/depot_tools/fetch.py", line 109, in run_git
    return git_common.run(*cmd, **kwargs)
  File "/Users/xxx/Documents/GitHub_MySelf/depot_tools/git_common.py", line 748, in run
    return run_with_stderr(*cmd, **kwargs)[0]
  File "/Users/xxx/Documents/GitHub_MySelf/depot_tools/git_common.py", line 818, in run_with_stderr
    raise subprocess2.CalledProcessError(retcode, cmd, os.getcwd(), ret, err)
subprocess2.CalledProcessError: Command 'git -c color.ui=never submodule foreach git config -f $toplevel/.git/config submodule.$name.ignore all' returned non-zero exit status 128 in /Users/xxx/Documents/GitHub_MySelf/dart-sdk
fatal: No url found for submodule path 'pkg/analysis_server/native/cJSON' in .gitmodules

**Comment by Salakar** [comment]
Getting the same issue here, unable to fetch the source - is there a way to perhaps fetch a specific tag/branch with `fetch`?

```
Step #0: ________ running 'python3 sdk/tools/generate_package_config.py' in '/workspace/build/dart_sdk_source'
Step #0: ________ running 'python3 sdk/tools/generate_sdk_version_file.py' in '/workspace/build/dart_sdk_source'
Step #0: ________ running 'python3 sdk/build/linux/sysroot_scripts/install-sysroot.py --arch i386' in '/workspace/build/dart_sdk_source'
Step #0: Installing Debian Jessie i386 root image: /workspace/build/dart_sdk_source/sdk/build/linux/debian_jessie_i386-sysroot
Step #0: Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7031a828c5dcedc937bbf375c42daab08ca6162f/debian_jessie_i386_sysroot.tgz
Step #0: ________ running 'python3 sdk/build/linux/sysroot_scripts/install-sysroot.py --arch amd64' in '/workspace/build/dart_sdk_source'
Step #0: Installing Debian Jessie amd64 root image: /workspace/build/dart_sdk_source/sdk/build/linux/debian_jessie_amd64-sysroot
Step #0: Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7031a828c5dcedc937bbf375c42daab08ca6162f/debian_jessie_amd64_sysroot.tgz
Step #0: ________ running 'python3 sdk/build/linux/sysroot_scripts/install-sysroot.py --arch arm' in '/workspace/build/dart_sdk_source'
Step #0: Installing Debian Jessie arm root image: /workspace/build/dart_sdk_source/sdk/build/linux/debian_jessie_arm-sysroot
Step #0: Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7031a828c5dcedc937bbf375c42daab08ca6162f/debian_jessie_arm_sysroot.tgz
Step #0: ________ running 'python3 sdk/build/linux/sysroot_scripts/install-sysroot.py --arch arm64' in '/workspace/build/dart_sdk_source'
Step #0: Installing Debian Jessie arm64 root image: /workspace/build/dart_sdk_source/sdk/build/linux/debian_jessie_arm64-sysroot
Step #0: Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7031a828c5dcedc937bbf375c42daab08ca6162f/debian_jessie_arm64_sysroot.tgz
Step #0: ________ running 'python3 sdk/tools/buildtools/update.py' in '/workspace/build/dart_sdk_source'
Step #0: Running: gclient root
Step #0: Running: gclient config --spec 'solutions = [
Step #0:   {
Step #0:     "name": "sdk",
Step #0:     "url": "https://dart.googlesource.com/sdk.git",
Step #0:     "deps_file": "DEPS",
Step #0:     "managed": False,
Step #0:     "custom_deps": {},
Step #0:   },
Step #0: ]
Step #0: '
Step #0: Running: gclient sync --no-history
Step #0: Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Step #0: Traceback (most recent call last):
Step #0:   File "/workspace/depot_tools/fetch.py", line 285, in <module>
Step #0:     sys.exit(main())
Step #0:   File "/workspace/depot_tools/fetch.py", line 280, in main
Step #0:     return run(args, spec, root)
Step #0:   File "/workspace/depot_tools/fetch.py", line 274, in run
Step #0:     return checkout.init()
Step #0:   File "/workspace/depot_tools/fetch.py", line 153, in init
Step #0:     self.run_git(
Step #0:   File "/workspace/depot_tools/fetch.py", line 109, in run_git
Step #0:     return git_common.run(*cmd, **kwargs)
Step #0:   File "/workspace/depot_tools/git_common.py", line 748, in run
Step #0:     return run_with_stderr(*cmd, **kwargs)[0]
Step #0:   File "/workspace/depot_tools/git_common.py", line 818, in run_with_stderr
Step #0:     raise subprocess2.CalledProcessError(retcode, cmd, os.getcwd(), ret, err)
Step #0: subprocess2.CalledProcessError: Command 'git -c color.ui=never submodule foreach git config -f $toplevel/.git/config submodule.$name.ignore all' returned non-zero exit status 128 in /workspace/build/dart_sdk_source
Step #0: fatal: No url found for submodule path 'pkg/analysis_server/native/cJSON' in .gitmodules
```
