### ISSUE TITLE
Highlight range for FfiCode.ABI_SPECIFIC_INTEGER_MAPPING_UNSUPPORTED

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#49134]
The highlight range for `FfiCode.ABI_SPECIFIC_INTEGER_MAPPING_UNSUPPORTED` should be changed so that only the unsupported value is highlighted.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/246242

**Comment by dcharkes** [comment]
How would we deal with the following?

```dart
const y = IntPtr();
const x = {
  Abi.androidArm: Uint32(),
  Abi.androidArm64: y,
  Abi.androidIA32: UintPtr(),
};
@AbiSpecificIntegerMapping(x)
class UintPtr extends AbiSpecificInteger {
  const UintPtr();
}
```

What should the error location be in that case? The `AbiSpecificIntegerMapping`? the `x`? Or the elements of the const?
The elements in the const might be an error message without context.

So maybe we can only improve the situation if the const map is inline, but need to have a fallback to the current behavior if it is referring to a const by name.

**Comment by bwilkerson** [comment]
Good catch, thanks!

In cases where the value of the argument is far removed from the annotation, we should definitely fall back to highlighting something else. We generally try to keep the highlighting region as short as possible because that's usually the best way to direct the user's attention to the source of the problem. In this case I'd suggest that we highlight the whole argument, but not the whole annotation.

But it does suggest that we might want to include the invalid value in the problem message, maybe something like:

> Invalid mapping to 'IntPtr'; only mappings to 'Int8', 'Int16', 'Int32', 'Int64', 'Uint8', 'Uint16', 'UInt32', and 'Uint64' are supported.

That way, when they navigate to the constant they'll know which value is causing the problem. It would also help even in the case where the highlight range is on the invalid value when the message is displayed by `dart analyze`, because that tool doesn't currently print any code snippets as context.

**Comment by dcharkes** [comment]
sgtm!

Thanks for making it better @asashour and @bwilkerson!
