### ISSUE TITLE
Web error stack traces inconsistent with app

### ISSUE THREAD

**Issue by helin24** [dart-lang/sdk#49147]
We parse file locations from stack traces in the IntelliJ plugins to allow users to click to open relevant files when an error occurs. This is broken for web because the format of web stack traces differs from apps.

We could add separate parsing when users are running a web app, but as far as we know there isn't a particular reason why we would want a different format of messaging for web vs non-web, particularly for the file locations.

Example error (not web):
```

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _Exception was thrown while handling a gesture:
Exception: test message

When the exception was thrown, this was the stack:
#0      _MyHomePageState._incrementCounter.<anonymous closure> (package:hello_flutter_external/main.dart:63:7)
#1      State.setState (package:flutter/src/widgets/framework.dart:1109:30)
#2      _MyHomePageState._incrementCounter (package:hello_flutter_external/main.dart:56:5)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1004:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:247:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:612:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#16     _invoke1 (dart:ui/hooks.dart:167:13)
#17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#21ff9
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Example error on web:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _Exception was thrown while handling a gesture:
Exception: test message

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/hello_flutter_external/main.dart 63:7                                <fn>
packages/flutter/src/widgets/framework.dart 1109:30                           setState
packages/hello_flutter_external/main.dart 56:5                                [_incrementCounter]
packages/flutter/src/material/ink_well.dart 1004:21                           [_handleTap]
packages/flutter/src/gestures/recognizer.dart 247:24                          invokeCallback
packages/flutter/src/gestures/tap.dart 612:48                                 handleTapUp
packages/flutter/src/gestures/tap.dart 298:5                                  [_checkUp]
packages/flutter/src/gestures/tap.dart 269:7                                  acceptGesture
packages/flutter/src/gestures/arena.dart 157:12                               sweep
packages/flutter/src/gestures/binding.dart 449:20                             handleEvent
packages/flutter/src/gestures/binding.dart 425:14                             dispatchEvent
packages/flutter/src/rendering/binding.dart 329:11                            dispatchEvent
packages/flutter/src/gestures/binding.dart 380:7                              [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 344:5                              handlePointerEvent
packages/flutter/src/gestures/binding.dart 302:7                              [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 285:32                             [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1118:13                           invoke1
lib/_engine/engine/platform_dispatcher.dart 185:5                             invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 147:39                                [_onPointerData]
lib/_engine/engine/pointer_binding.dart 560:18                                <fn>
lib/_engine/engine/pointer_binding.dart 513:21                                <fn>
lib/_engine/engine/pointer_binding.dart 227:16                                loggedHandler

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#a5aa8
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by helin24** [comment]
@lrhn The IntelliJ plugins are written in Java and we aren't using `package:stack_trace`. We're instead parsing the stdout from the Flutter SDK, really only looking for URIs. If this stack trace/URI formatting is a result of JS translation, we may just have to implement a slightly different parsing method in the plugins.

**Comment by sigmundch** [comment]
Note that DDC produces JS stacks initially, but then uses a [stack-trace-mapper][1] to processes stacks and convert them using inline source-map content added to each .js module. The stack-trace-mapper is not shipped with the SDK but loaded by serving frameworks (like flutter web and webdev).

The stack-trace-mapper uses `package:stack_trace` internally, and it may be possible to tweak how the lines get formatted. There is a risk, however, that other tools/scripts may be relying on today's format, so a change to the mapper would need to be rolled out carefully.

Long term, my personal preference in the future is to move away from using the stack-trace mapper and leave the original JS stacks intact if possible. Then let the IDEs manage the translation with source-map outside of the client process (this is the mechanism we take with dart2js, where production stacks are deobfuscated on the server-side). Unfortunately, there are additional challenges we need to resolve first before we can do this.

[1]: https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/web/stack_trace_mapper.dart

**Comment by helin24** [comment]
@sigmundch Is source-map a package/other entity or do you mean the general idea of having a map from sources to JS files? 

I'll bring up this issue within IDEs and then update here if we want to try to coordinate a change.

**Comment by sigmundch** [comment]
Source-maps is a [standard][1] used by many browsers vendors to convert JS location back to the original source locations (in our case in Dart). We have an implementation of the translation in Dart in `package:source_maps` (which is used also by the stack-trace-mapper). There are implementations in other languages too (including Java) and, for instance, our internal customers use such implementations to convert stack traces server-side.

[1]: https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit

**Comment by helin24** [comment]
We're going to make some changes on the IDE side, so I can close this. Thanks for the input here all!
