### ISSUE TITLE
[CP] Fix `dart pub login`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#49146]
### Commit(s) to merge

42e12a50de5371b4107ae1860945dcdf6ebb32fd ([sdk/+/246582](https://dart-review.googlesource.com/c/sdk/+/246582))

### Target

stable

### Issue Description

Fix `dart pub login` due to unexpected `null` in response.

### What is the fix

The command crashed because the metadata end-point returned `null` for
the name property. This fix handles invalid responses more gracefully,
and handles the case where `name` is `null`, by not displaying the name.

### Why cherry-pick

Users who was already logged was able to continue publish packages, but
displaying the login status using `dart pub login` was broken.
Attempts to login would also cause a crash after successful
authentication, before credentials were saved.

### Risk

low (changes only affect the `dart pub login` command, which is fairly broken).

### Issue link(s)

https://github.com/dart-lang/pub/issues/3424

### Extra Info

This bumps `pub_rev` with two new commits, see diff: https://github.com/dart-lang/pub/compare/a949b329b1b51f5f3973a790e0a0a45897d837de...cherry-pick-for-2.17.2

```
$ git log --format="%C(auto) %h %s" a949b329b1b51f5f3973a790e0a0a45897d837de..cherry-pick-for-2.17.2 
 c66381c5 Make `name` field of `_UserInfo` nullable. Fix #3424 (#3442)
 cecc8e3c Handle broken response from userinfo_endpoint (#3427)
```

**Comment by jonasfj** [comment]
**Update:** I just realized that `dart pub publish` initiates a login-flow on-the-fly, and this flow does not talk to the meta-data end-point (hence, unaffected by this bug).

So users can still publish, even if they are not logged in, they just have to use `dart pub publish` and complete the login-flow it initiates.
But it's fair to think that some users who experience that `dart pub login` is broken, won't try to run `dart pub publish` -- since they'll think authentication is broken.

**Comment by vsmenon** [comment]
lgtm
