### ISSUE TITLE
Intellisense not able to understand the null check above

### ISSUE THREAD

**Issue by harshitsangani** [dart-lang/sdk#49151]
Dart SDK Version: `2.17.1`
Platform: MacOS

## Screenshot
![image](https://user-images.githubusercontent.com/68107287/171328724-ca491ef8-570b-439d-b606-49a2990138f3.png)

**Comment by srawlins** [comment]
Thanks for filing an issue, @harshitsangani . Can you provide more details? What type of variable is `pagination`, what are you expecting? etc.

At a guess, it looks like you are expecting `pagination` to promote to a non-nullable type after the second line of text in the image you attached. See [Working with nullable fields](https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields) if `pagination` is a field.

**Comment by harshitsangani** [comment]
@srawlins Thanks for the question, It is supposed to infer the `pagination` variable on line 2 as non-null field as It is already checked on line 1.

**Comment by jcollins-g** [comment]
> @srawlins Thanks for the question, It is supposed to infer the `pagination` variable on line 2 as non-null field as It is already checked on line 1.

Hi, can you share the declaration of `pagination`?

**Comment by harshitsangani** [comment]
@jcollins-g here's the complete scenario

if I have checked that `pagination!=null` then it should infer the enclosed code as non-null pagination object.

![Screenshot 2022-06-03 at 10 50 13 AM](https://user-images.githubusercontent.com/68107287/171791407-065cde16-5f54-479d-9106-fd9dfd79918f.png)

**Comment by mraleph** [comment]
@harshitsangani This is working as intended. It is unsound to promote field types like that. Please read [Working with nullable fields](https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields) which explains why this is not the case and offers alternatives.

**Comment by harshitsangani** [comment]
@mraleph I look into the docs, but I still disagree here, as if we have checked it to be a not null then it should promote it to non-null variable.

**Comment by mraleph** [comment]
@harshitsangani unfortunately that would be unsound, as explained in the link documentation, because field can be overriden with a getter. Consider the code like this:

```
class X {
  String? foo;
  
  void doSomething() {
    if (foo != null) {
      print(foo.length);  // Expecting foo to be non-null
    }
  }
}

// In some other library
class Y extends X {
  int _counter = 0;
  String? get foo {
    return (_counter++).isOdd ? null : "";
  }
}
```

As you can see checking field once does not guarantee that it stays the same. 

The [language team is trying to find a way](https://github.com/dart-lang/language/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afield-promotion) to address this pain point - but it will take time before something comes.
