### ISSUE TITLE
Result of getRetainingPath should not include WeakReference

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#49155]
details: https://stackoverflow.com/questions/72454842/why-weakreference-is-part-of-getretainingpath
code: https://github.com/dart-lang/sdk/blob/1e7bc687a7931c7bd837147b6fef60b9cf4fa42c/runtime/vm/service.cc#L2481

Blocks memory detection tool: https://github.com/flutter/devtools/issues/3951

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by polina-c** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/302367
