### ISSUE TITLE
Make the `unencodedPath` argument to `Uri.http` and `Uri.https` constructors optional

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#49165]
We are already using positional optional parameters for `queryParameters`. These are constructors so the change is non-breaking for the vast majority of typical use cases.

It looks strange to pass an empty string for an empty path.

**Comment by lrhn** [comment]
The HTTP scheme allows a path of "path-abempty", so omitting it is technically fine.
It's also a little weird, but who are we to stop people from being weird.
