### ISSUE TITLE
Source generator: Is there any way to find all object instantiations?

### ISSUE THREAD

**Issue by leoshusar** [dart-lang/sdk#49175]
Hi! I already tried to ask on [StackOverflow](https://stackoverflow.com/questions/72426711/dart-source-generator-is-there-any-way-to-find-all-object-instantiations), but nobody seems to know there, so I'm trying here.

I am trying to make a source generator that would mimic C# anonymous objects, because they are great for when you are manipulating with collections (`Select`, `GroupBy`, etc.).

Imagine this code:
```dart
class Person {
  final String firstName;
  final String lastName;
  final int age;

  Person(this.firstName, this.age, this.lastName);
}

class TestClass {
  final _data = [
    Person('John', 'Doe', 51),
    Person('Jane', 'Doe', 50),
    Person('John', 'Smith', 40),
  ];

  void testMethod() {
    final map1 = _data.map((p) => _$$1(name: p.firstName, age: p.age));
    final map2 = _data.map((p) => _$$2(fullName: '${p.firstName} ${p.lastName}', age: p.age));
  }
}
```

Those `_$$x` objects are what I want to generate now. I need to somehow find them and find what is being passed into them, so my code generator would generate this:
```dart
class _$$1 {
  final String name;
  final int age;

  const _$$1({required this.name, required this.age});
}

class _$$2 {
  final String fullName;
  final int age;

  const _$$1({required this.fullName, required this.age});
}
```

but I cannot seem to even find method content:
```dart
FutureOr<String?> generate(LibraryReader library, BuildStep buildStep) {
  for (final clazz in library.classes) {
    final method = clazz.methods.first;
    method.visitChildren(RecursiveElementVisitor<dynamic>());
  }
}
```

it looks like the `MethodElement` doesn't have any children? so this doesn't look like the right way.

Is there any other way to find what I need?

**Comment by bwilkerson** [comment]
I can't speak to what information the code generator makes available to you, but I can confirm that the `MethodElement` (which is part of the [element model](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/doc/tutorial/element.md), doesn't have any representation of the content of the method. The element model represents the things (elements) that are declared in code (can be referenced). The [ast model](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/doc/tutorial/ast.md) represents the full source code, including statements and expressions, and is what you need in order to find invocations of methods.

@jakemac53 for information about how to access the AST from a code generator.

**Comment by leoshusar** [comment]
Thank you! I have been able to find `FunctionExpression` -> `ExpressionFunctionBody` -> `MethodInvocation`, there I see the object name (`_$$1`) and its `argumentList`.
However I cannot find the argument types I need for generating the class (`String` and `int` in this case), `staticType` is null.
Am I approaching this right? Can I get those types somehow?

**Comment by jakemac53** [comment]
@leoshusar you need a resolved Ast for this, which you can get by passing `resolve: true` to the call to `astNodeFor`.

**Comment by leoshusar** [comment]
So I finished the main functionality and I've got one more question now.
When I write this:
```dart
final a = _$$1(string: 'test');
final b = _$$2(test: a.string);
```
it will generate these classes:
```dart
class _$$1 {
  const _$$1({required this.string});

  final String string;
}

class _$$2 {
  const _$$2({required this.test});

  final dynamic test;
}
```
The `_$$1` is correct, but `_$$2` has the property as `dynamic`, because both classes are being generated from the same AST and it doesn't know about the `_$$1`.
Is there any way to generate the first class and somehow re-resolve the AST with that class included?

**Comment by jakemac53** [comment]
Sort of, but it probably isn't realistic for you.

You could create different `part` files, and you could re-resolve after outputting each one. But that requires an unknown number of part files, so you probably wouldn't be able to properly declare your outputs.

**Comment by leoshusar** [comment]
And any other options? Isn't there maybe some way to force rerun the generator on the same library input but with added data from the previous run? I'm imagining something like it would run until I don't return any new source.
I'm open to any hacks (except modifying SDK or 3rd party libs) that would make it working, if there are any.

**Comment by jakemac53** [comment]
There aren't any hacks you could use that I am aware of. Files are immutable in the build once they are produced.

**Comment by leoshusar** [comment]
>You could create different part files, and you could re-resolve after outputting each one.

Could you please tell me more about how it would work, what would trigger the generator to re-run after one part being generated? I've been thinking about it got a few more ideas (that may also be impossible).

1)
- generate first part file
- re-resolve AST
- generate second part file but save that content in the first part file
- re-resolve AST
- ...

You said files are immutable, but what about editing them directly using `File` from `dart:io`? Is there a way to get a direct path to that file?

2)
- generate the first part and save it to a variable inside the generator
- re-resolve
- generate the second part and merge it with the previously generated one, save again, overwrite the already created part file
- ...

3) Running my own analysis context inside a single build step, which I would be (somehow) able to modify, add source to it, resolve ASTs, etc.

Do you think any of these is possible?

**Comment by jakemac53** [comment]
> You said files are immutable, but what about editing them directly using `File` from `dart:io`? Is there a way to get a direct path to that file?

If you ever find yourself importing `dart:io`, its almost guaranteed you will break the build system in some way. In this case we cache contents of files, so we won't see your update. The analyzer will also cache the analysis results.

> generate the second part and merge it with the previously generated one, save again, overwrite the already created part file

We don't allow overwriting files. As a general principle the build system only allows _new_ code, not modifying existing code.

I could possibly see an argument that it would be safe to allow overwriting a file _within the same build step_ though. This would allow you to do what you want. The file isn't exposed to any other builders at that point, so it probably wouldn't create major issues. This feature would have to be an external contribution, and it would take a fair bit of work, and need to be thoroughly tested etc. If you want to try and take that on, I would first file an issue to discuss the design and get sign-off before implementing so you don't waste effort.

> 3: Running my own analysis context inside a single build step, which I would be (somehow) able to modify, add source to it, resolve ASTs, etc.

In theory this would likely be possible, but it would be a large amount of work (to do right). It would also be very slow compared to using the built in resolver which shares analysis work across build steps.

> Could you please tell me more about how it would work, what would trigger the generator to re-run after one part being generated?

I think you would not be able to use source_gen, you would need to use the regular `Builder` class. You could likely use some helpers from source_gen though.

We allow you to see your own generated outputs immediately after outputting them, so you can just re-resolve after calling the `BuildStep#writeAsString` method to write files. You would likely need to re-navigate back to the same place you were at in the new Ast node you are given though, I don't think the resolved Ast you had before will still be valid (or have updated results).

The larger issue though is knowing how many parts you will need to output. You have to declare outputs before looking at the file. So I don't really see how it could work out for your use case, unless you limit to some hard coded possible number of outputs.

**Comment by leoshusar** [comment]
Thank you for explanation!
I don't think it's worth the hassle to implement anything to support this in the `build` package, because if I'm not mistaken, once [this](https://github.com/dart-lang/language/issues/207) is implemented, it would work the same as what I'm trying to do here, but native.

Anyway, I tried to re-resolve after using `BuildStep#writeAsString`, but it doesn't pick my output.

```dart
part 'anon_test.a.dart';

class TestClass {
  void testMethod() {
    final a = _$$1(string: 'test');
    final b = _$$2(test: a.string);
  }
}
```

```dart
import 'dart:async';

import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:build/build.dart';

class AnonymousObjectsBuilder implements Builder {
  @override
  final buildExtensions = const {
    '.dart': ['.a.dart'],
  };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    final inputLibrary = await buildStep.inputLibrary;
    final newInputId = buildStep.inputId.changeExtension('.a.dart');

    final visitor = TestVisitor();

    var ast = await buildStep.resolver.astNodeFor(inputLibrary.topLevelElements.first, resolve: true);
    // this will print these lines:
    // [_$$1] string String
    // [_$$2] test dynamic
    ast!.visitChildren(visitor);
    // generate _$$1, hardcoded for now
    await buildStep.writeAsString(newInputId, 'part of \'anon_test.dart\';\n\nclass _\$\$1 {\n  const _\$\$1({required this.string});\n\n  final String string;\n}');

    // re-resolve - is this the right way to do it?
    ast = await buildStep.resolver.astNodeFor(inputLibrary.topLevelElements.first, resolve: true);
    // since _$$1 is generated, I can see the file exists and IDE picks up that class, it should print these lines:
    // [_$$1] string String
    // [_$$2] test String
    // but the latter one is still dynamic
    ast!.visitChildren(visitor);
  }
}

class TestVisitor extends RecursiveAstVisitor<void> {
  @override
  void visitMethodInvocation(MethodInvocation node) {
    super.visitMethodInvocation(node);

    final methodName = node.methodName.name;

    if (!methodName.startsWith(r'_$$')) {
      return;
    }

    final argument = node.argumentList.arguments.first as NamedExpression;

    print('[$methodName] ${argument.name.label.name} ${argument.staticType}');
  }
}
```

**Comment by jakemac53** [comment]
Hmm I think that this is not actually supported via part files, we don't invalidate the parent library, so you won't get updated results.

You could emit a new _library_ instead of a part file, but then you can't use private names, which you probably want, but I did confirm that would work (you need to explicitly resolve the new library with `libraryFor`, but can throw the result away).

We could possibly support re-resolving the input library to pick up part files, but I am not super convinced it is worth while.

**Comment by leoshusar** [comment]
Ahh, that's unfortunate. And yes, since I wanted to use private names, I guess I have no more ideas now. I think I'll live with it as it is now and maybe soon it will be supported natively.

Thank you for your help!
