### ISSUE TITLE
os_signposts aren't showing up correctly in Instruments

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#49178]
## Description
This tracker is for issues related to: Dart VM

There are few problems:
1) There are events being generated with no name for the "Dart" subsystem "Dart" category
1) ~~None of the regions of time have end events because they are being called with `OS_SIGNPOST_ID_EXCLUSIVE`, so they don't match the begin.~~
1) Only events from the flutter engine are displaying, the Timeline events in the framework are not generating events (Timeline calls generated from C++ with `TRACE_EVENT`, not Dart Timeline events)
1) ~~The events aren't showing up in the "Points of Interest" probe which displays the data better and is the default probe added to most profiling schemes.~~ (6/8/22 removed since the heuristics for deciding if something should be in this category are not clear)

## Steps to reproduce
1) `flutter create counter`
1) `open ios/Runner.xcworkspace`
1) Edit the configuration to include the command line argument `--trace-systrace`
1) Run the app on device
1) Launch Instruments and make sure there is a "Points of Interest" and an "os_signposts" probes
1) Attach to the running process

## Update 6/8/22
@a-siva @rmacnak-google and @gaaclarke decided that the correct way to implement this is to make the [AsyncId](https://github.com/dart-lang/sdk/blob/7b001746fd4aaaf787f939898ed8ec43dffb0086/runtime/vm/timeline.h#L394) available for synchronous Timeline events.  That way they can be assigned to the os_signpost events.  We should also move the usage of non-literal strings to the messages for events in order to avoid abusing the api which was causing os_signposts to be unnamed sometimes:
```c++
--- a/runtime/vm/timeline_macos.cc
+++ b/runtime/vm/timeline_macos.cc
@@ -41,15 +41,13 @@ void TimelineEventMacosRecorder::OnEvent(TimelineEvent* event) {
       break;
     }
     case TimelineEvent::kBegin: {
-      _os_signpost_emit_with_name_impl(
-          &__dso_handle, log, OS_SIGNPOST_INTERVAL_BEGIN,
-          OS_SIGNPOST_ID_EXCLUSIVE, label, "", buffer, sizeof(buffer));
+      os_signpost_emit_with_type(log, OS_SIGNPOST_INTERVAL_BEGIN,
+                                 event->AsyncId(), "Timeline", "%s", label);
       break;
     }
     case TimelineEvent::kEnd: {
-      _os_signpost_emit_with_name_impl(
-          &__dso_handle, log, OS_SIGNPOST_INTERVAL_END,
-          OS_SIGNPOST_ID_EXCLUSIVE, label, "", buffer, sizeof(buffer));
+      os_signpost_emit_with_type(log, OS_SIGNPOST_INTERVAL_END,
+                                 event->AsyncId(), "Timeline");
       break;
     }
     case TimelineEvent::kAsyncBegin: {
```

**Comment by gaaclarke** [comment]
I suspect all those unnamed events are the Timeline events from the dart code.  They are ending up unnamed for some reason on iOS though.

**Comment by gaaclarke** [comment]
Here is a screenshot of the failure.  I'm trying to debug it / fix it for you.

<img width="1144" alt="Screen Shot 2022-06-06 at 9 53 21 AM" src="https://user-images.githubusercontent.com/30870216/172208246-33f5e6bc-fee8-4286-941e-6a9a69ad3692.png">

**Comment by rmacnak-google** [comment]
This is a limitation of signpost. It stores pointers to event names instead of copying, which only works for event names that are C string literals.

**Comment by gaaclarke** [comment]
Yea, I think the proper usage would be this:
```c++
      os_signpost_emit_with_type(log, OS_SIGNPOST_EVENT,
                                 OS_SIGNPOST_ID_EXCLUSIVE, "Dart", "%s", label);
```

By calling directly into `_os_signpost_emit_with_name_impl` we are bypassing the assert that the name is a string literal.

Testing it out now to be sure.

**Comment by gaaclarke** [comment]
I tried the following patch and got the following output.  While this looks like the output we'd like and uses the API the way it was intended, it completely trashes Instruments.  Instruments get stuck at 100% CPU and never displays the graph of the regions on version 13.3.1 (13E500a).  I've used this technique successfully elsewhere but the volume of events must make the difference.

patch:
```diff
diff --git a/runtime/vm/timeline_macos.cc b/runtime/vm/timeline_macos.cc
index cbb2efa5a7f..a905a9c1dab 100644
--- a/runtime/vm/timeline_macos.cc
+++ b/runtime/vm/timeline_macos.cc
@@ -30,47 +30,38 @@ void TimelineEventMacosRecorder::OnEvent(TimelineEvent* event) {
   }
 
   const char* label = event->label();
-  uint8_t _Alignas(16) buffer[64];
-  buffer[0] = 0;
-
   switch (event->event_type()) {
     case TimelineEvent::kInstant: {
-      _os_signpost_emit_with_name_impl(&__dso_handle, log, OS_SIGNPOST_EVENT,
-                                       OS_SIGNPOST_ID_EXCLUSIVE, label, "",
-                                       buffer, sizeof(buffer));
+      os_signpost_emit_with_type(log, OS_SIGNPOST_EVENT,
+                                 OS_SIGNPOST_ID_EXCLUSIVE, "Timeline", "%s",
+                                 label);
       break;
     }
     case TimelineEvent::kBegin: {
-      _os_signpost_emit_with_name_impl(
-          &__dso_handle, log, OS_SIGNPOST_INTERVAL_BEGIN,
-          OS_SIGNPOST_ID_EXCLUSIVE, label, "", buffer, sizeof(buffer));
+      os_signpost_emit_with_type(log, OS_SIGNPOST_INTERVAL_BEGIN,
+                                 OS_SIGNPOST_ID_EXCLUSIVE, "Timeline", "%s",
+                                 label);
       break;
     }
     case TimelineEvent::kEnd: {
-      _os_signpost_emit_with_name_impl(
-          &__dso_handle, log, OS_SIGNPOST_INTERVAL_END,
-          OS_SIGNPOST_ID_EXCLUSIVE, label, "", buffer, sizeof(buffer));
+      os_signpost_emit_with_type(log, OS_SIGNPOST_INTERVAL_END,
+                                 OS_SIGNPOST_ID_EXCLUSIVE, "Timeline", "%s",
+                                 label);
       break;
     }
     case TimelineEvent::kAsyncBegin: {
-      _os_signpost_emit_with_name_impl(
-          &__dso_handle, log, OS_SIGNPOST_INTERVAL_BEGIN, event->AsyncId(),
-          label, "", buffer, sizeof(buffer));
+      os_signpost_emit_with_type(log, OS_SIGNPOST_INTERVAL_BEGIN,
+                                 event->AsyncId(), "Timeline", "%s", label);
       break;
     }
     case TimelineEvent::kAsyncEnd: {
-      _os_signpost_emit_with_name_impl(
-          &__dso_handle, log, OS_SIGNPOST_INTERVAL_END, event->AsyncId(), label,
-          "", buffer, sizeof(buffer));
+      os_signpost_emit_with_type(log, OS_SIGNPOST_INTERVAL_END,
+                                 event->AsyncId(), "Timeline", "%s", label);
       break;
     }
     case TimelineEvent::kCounter: {
-      const char* fmt = "%s";
-      Utils::SNPrint(reinterpret_cast<char*>(buffer), sizeof(buffer), fmt,
-                     event->arguments()[0].value);
-      _os_signpost_emit_with_name_impl(&__dso_handle, log, OS_SIGNPOST_EVENT,
-                                       event->AsyncId(), label, fmt, buffer,
-                                       sizeof(buffer));
+      os_signpost_emit_with_type(log, OS_SIGNPOST_EVENT, event->AsyncId(),
+                                 "Counter", "%s", event->arguments()[0].value);
       break;
     }
     default:
```

screenshot:
<img width="1138" alt="Screen Shot 2022-06-06 at 11 04 19 AM" src="https://user-images.githubusercontent.com/30870216/172219482-0ea12806-eaf1-4b3f-87e3-58c202c1257f.png">

**Comment by gaaclarke** [comment]
Ugh, figured it out.  There was also an error in our code with respect to event id's.  Cleaning it up and will submit a CL.

**Comment by gaaclarke** [comment]
fixed by https://dart-review.googlesource.com/c/sdk/+/247327

**Comment by gaaclarke** [comment]
Here is the events after the patch, notice that there are more system events now that things are messed up and that there is an extra layer "Timeline" when defining the events.
<img width="1136" alt="Screen Shot 2022-06-06 at 11 52 45 AM" src="https://user-images.githubusercontent.com/30870216/172227663-63ab14b7-5489-441f-ae7a-c5ed3d447da0.png">

**Comment by gaaclarke** [comment]
Looking at the last screenshot, it looks like it might not be quite right yet.  The times for the events don't make sense.

**Comment by gaaclarke** [comment]
The reason that patch didn't work is that it didn't account for recursive calls to synchronous timeline events.  When you start  pairing them up correctly though sometimes there are timeline events that end with no beginning.

For example I'm seeing an end event for `Dart_Initialize` but there is no begin event.

**Comment by gaaclarke** [comment]
I've fixed it, but found the following events don't have a begin event:
```
error: unmatched end event: Dart_Initialize
error: unmatched end event: DartVMInitializer
error: unmatched end event: Shell::Create
```

I'm not sure if that is a Dart bug or a Flutter bug.  They happen at the top level so I was able to easily ignore them without string comparisons.

**Comment by a-siva** [comment]
Initialization calls happen before the timeline system starts up and hence we don't see any of the start events for these I presume.

**Comment by gaaclarke** [comment]
@a-siva @rmacnak-google I updated the description with the decision from our meeting.  PTAL to make sure I got it right.

**Comment by rmacnak-google** [comment]
The Flutter engine should also be updated to pass event ids into Dart_TimelineEvent for begin and end events, or post events directly to signpost.
