### ISSUE TITLE
[analyzer] DartTypes equality without considering their nullability status

### ISSUE THREAD

**Issue by Amir-P** [dart-lang/sdk#49180]
In my case I need to check DartTypes equality with possible different nullability statuses. Is there any way to do that?

**Comment by bwilkerson** [comment]
The only way that I can think of at the moment would be to use `TypeSystem.promoteToNonNull` on both types and then compare them. But I'm not sure whether that will get you the semantics you're after.

@scheglov Would that work? Is there a better way?

**Comment by scheglov** [comment]
What is your understanding of type equality? The same as `20.2 Dynamic Type System`:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/384794/172024863-b8f82c83-dfce-4836-9366-1370d73d5732.png">
Or identical? Or [runtime type equality](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#runtime-type-equality-operator)?

And what does it mean "without nullability statuses"? All of them? Or only of the outermost type? Note that `TypeSystem.promoteToNonNull` implements `NonNull` from https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#null-promotion, which does only outermost modifications.

**Comment by Amir-P** [comment]
Here is what I'm trying to do: I have a class like `class SomeClass extends SomeOtherClass<B>` and some fields like `final A a; final B b; final C? c;` where `C` extends `B` and `B` extends `A`. I want to find fields matching generic type of `SomeClass`. By match I mean the type of field should be equal to generic type of `SomeClass` or should be a subtype of it. So the fields `b` and `c` should match with `SomeClass`.

So equality is not a correct term here.

Also, what you've explained about `TypeSystem.promoteToNonNull`, means that in a case where we have a type like `typedef Foo = Bar?` if we use `TypeSystem.promoteToNonNull` on `Foo?` we will get `Foo` or `Bar?` and not `Bar`, right? @scheglov

**Comment by scheglov** [comment]
It looks that you want to use `DartType.asInstanceOf(ClassElement)`, see https://github.com/dart-lang/sdk/blob/d78797d0141cd5956dbe599caebd1b5b19fc270e/pkg/analyzer/lib/dart/element/type.dart#L158

As for typedef's, they are always instantiated to the final type, so with `typedef Foo = Bar?` when you write `Foo?` you still get `Bar?` in the resolved AST and element model.

**Comment by Amir-P** [comment]
Thanks @scheglov , Looking at the document of `asInstanceOf`, it doesn't seem to be what I want. Anyway, I gave it a test. I have a `ClassElement` for the `SomeClass` and a `DartType` for the field `final DateTime? a;` but the result of `DartType.asInstanceOf(ClassElement)` is `null`.

```dart
class SomeOtherClass<T> {}
class SomeClass extends SomeOtherClass<DateTime> {}

final DateTime? a;
```

**Comment by scheglov** [comment]
Well, apparently `DateTime` does not implement `SomeClass`.
