### ISSUE TITLE
[analyzer] A built-in identifier cannot be the name of a type or an extension

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#49196]
Cf. [this rule](https://github.com/dart-lang/language/blob/8fb9f0ad4e8e5eabb1ec83abcd53f2f587d111fb/specification/dartLangSpec.tex#L16616) and [this rule](https://github.com/dart-lang/language/blob/8fb9f0ad4e8e5eabb1ec83abcd53f2f587d111fb/specification/dartLangSpec.tex#L5800), it is a compile-time error to declare an import prefix, a class, a mixin, a type parameter, a type alias, or an extension whose name is a built-in identifier.

This error is not reported by the analyzer for the built-in identifier `Function` in several cases, including: Import prefix, class name, and mixin name.

The errors do get reported by the CFE, so the change should be non-breaking in practice.

**Comment by bwilkerson** [comment]
When this is fixed, I think we can also remove `HintCode.DEPRECATED_FUNCTION_CLASS_DECLARATION` (or at least only use it for pre-null-safe code, depending on when the rules referenced above were added to the language).

**Comment by srawlins** [comment]
The analyzer reports this error now in all of the positions above, and others that I checked.
