### ISSUE TITLE
[CP] Fixes for enhanced enum and switch.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#49191]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/247332

### Target

stable

### Issue Description

In implementation of enhanced enums in the analyzer two places should be fixed:
1. Support for `SimpleIdentifier` in exhaustiveness checking in `switch` statements, which were not possible before, but possible now inside the enum itself.
2. Another `switch` related hint where an approximation for accessing enum constants was used (`static const`), but which does not work correctly for enhanced enums because there are non-enum-constant constants possible now.

### What is the fix

The CL makes small fixes in the analyzer.

### Why cherry-pick

Well, this causes issues for users.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/49188

**Comment by itsjustkevin** [comment]
@vsmenon @athomas This is a relatively small change with mostly updates to tests, this seems like a low risk cherry pick.  Do you have an opinion on this?

**Comment by itsjustkevin** [comment]
Based on the low risk and complexity of this cherry-pick, I am going to mark it as approved.

**Comment by whesse** [comment]
This has been landed in 2.17.4.  2.17.5, with no additional changes, will be published.
