### ISSUE TITLE
Throw of `null` should throw `TypeError` in sound null-safe mode.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#49198]
If you do `throw null as dynamic;` in sound null-safety mode, the current implementation throws a `NullThrownError`.

The `throw` operator in null safe Dart has a context type of `Object`, so the dynamic should have an implicit down-cast of `as Object`, which will fail in sound null-safe mode.

We don't actually specify the context type anywhere (of anything), but the [NNBD feature specification states](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#:~:text=It%20is%20an%20error%20if%20the%20static%20type%20of%20e%20in%20the%20expression%20throw%20e%20is%20not%20assignable%20to%20Object.):
> It is an error if the static type of `e` in the expression `throw e` is not assignable to `Object`.

which is as close as we ever come to stating the context type of anything in that document.

I'd expect `throw null as dynamic;` to throw a `TypeError` in *sound* null-safe mode, due to the implicit downcast to `Object`. In unsound null-safe mode, the `as Object` will let `null` through, and we'll have to do something about it, and using the old `NullThrowError` is fine (but so is throwing a `TypeError` in any null-safe library).

I want to remove `NullThrownError` in Dart 3.0, so I also want sound null-safe code to stop throwing it.

Async errors, like `Future.error`, `Completer.completeError` and `StreamController.addError` already throw synchronous type errors if you pass in `null` in unsound null-safety mode.

**Comment by johnniwinther** [comment]
This is a backend issue. The CFE just generates a throw expression and the backends perform the runtime checking for `null`.

**Comment by lrhn** [comment]
I thought the front-end was the one introducing implicit downcast from `dynamic`. This should be an implicit downcast.

**Comment by lrhn** [comment]
It's already a compile-time error if the expression is not *assignable* to `Object`, so the only allowed nullable type is `dynamic`. I want an implicit downcast to `Object` for that, just as for other `dynamic` expressions with non-top context types.

As long as we have unsound null-safe mode, the implicit downcast can still let a `null` through, because `as Object` will allow `null`. So, backends still need to be ready for a `null`. They just shouldn't see it in a *sound* null-safe program.

**Comment by johnniwinther** [comment]
Ok. I'll make the change to the CFE.
