### ISSUE TITLE
Linking Dart functions to a native binary

### ISSUE THREAD

**Issue by ibaryshnikov** [dart-lang/sdk#49199]
Is it possible to link Dart functions to a native binary the same way as with JavaScript and WebAssembly? In JS it's possible to pass an object with imports to [instantiateStreaming](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming) method. Does Dart have a similar feature? Assuming desktop and mobile targets.

**Comment by ibaryshnikov** [comment]
Thanks for a quick reply! Thank you for the links, haven't seen the second one yet.
I'm checking the limits of dart ffi. So far I've figured out that we can invoke the native function using `.lookup().asFuntion()` method. Also, it's possible to pass a static Dart function into a native function as a callback. But is it possible to link Dart functions to a native module? Something like an alternative to `DynamicLibrary.open` with second argument, which contains hashmap with functions to link.

**Comment by mraleph** [comment]
The closest alternative I can think off is to create a struct with a bunch of function pointers on the native side and then fill it in from Dart side, thus emulating what runtime linker would do for two shared objects. Something like this: 

```cpp
// C++
struct Imports {
  void (*callback1)(int x);
  void (*callback2)(double y);
  void (*callback3)(void* whatever);
  void (*callback4)(const char* something);
};

EXPORT_SYMBOL Imports imports;

// Use somewhere in the code:
imports.callback1(0);
```


```dart
// Dart

class Imports extends Struct {
  // ...
}

final lib = DynamicLibrary.open("foo");
final imports = lib.lookup<Imports>("imports");
imports.ref
  ..callback1 = Pointer.fromFunction(callback1)
  ..callback2 = Pointer.fromFunction(callback2)
  ..callback3 = Pointer.fromFunction(callback3)
  ..callback4 = Pointer.fromFunction(callback4);
```

**Comment by ibaryshnikov** [comment]
This looks great, thanks! I'll give it a try!
