### ISSUE TITLE
Drop references to dump-info-visualizer

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#49204]
- [x] dart.dev website - https://github.com/dart-lang/site-www/pull/4093
- [ ] pkg/compiler - https://github.com/dart-lang/sdk/blob/a362115c600f1853aa64df9016c1705b55d332a9/pkg/compiler/lib/src/dump_info.dart#L1300-L1301
- [ ] pkg/dart2js_info - https://github.com/dart-lang/sdk/blob/a362115c600f1853aa64df9016c1705b55d332a9/pkg/dart2js_info/bin/src/to_json.dart#L29-L36
- [ ] Add better docs to `dart2js_info` readme about how to use the tool!

**Comment by kevmoo** [comment]
CC @devoncarew @sigmundch

**Comment by sigmundch** [comment]
Thanks Kevin!

Yes, let's drop the help text going forward from the compiler output and eventually default to only generate the binary output. We can then drop the `--compat` mode altogether from the dart2js_info tools with time.

**Comment by kevmoo** [comment]
was thinking we should just create a "go" link – like `dart.dev/go/dart2js-dump-info` – so we can change where we point folks in the future
