### ISSUE TITLE
Enhanced enums: unexpected null on non-nullable field

### ISSUE THREAD

**Issue by dkvyk** [dart-lang/sdk#49216]
The following code acts pretty unpredictably:
```
enum StrangeEnum {
 
 a(fizz: true, requiredField: false, buzz: false),
 b(requiredField: false);

 const StrangeEnum({
 this.fizz = true, 
 this.buzz = false, 
 required this.requiredField,
 });

 final bool fizz;
 final bool buzz;
 final bool requiredField;
}
```

If I print StrangeEnum.values, fizz field on 'b' object will be null. However, if I change the arrangement of named arguments (e.g. place required on top) things work as intended. I believe this issue is caused by the combination of params with default values and required params in the constructor.

**Comment by vsmenon** [comment]
Thanks for the bug report.  Can you please let us know your Dart version number and how you are running it?

And, if possible, a full repro showing the null value printed?
