### ISSUE TITLE
Remove deprecated Dart_IsolateHeap* dart_tool_api functions

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#49211]
`Dart_IsolateHeap*(Dart_Isolate isolate)` functions were deprecated in favor of `Dart_IsolateGroupHeap*(Dart_IsolateGroup)`.
This issue tracks removal of deprecated functions from API once the change https://dart-review.googlesource.com/c/sdk/+/247504 which introduces new ones rolls out.

**Comment by a-siva** [comment]
This was addressed in https://dart-review.googlesource.com/c/sdk/+/248680, closing issue.
