### ISSUE TITLE
dart2js doesn't properly implement noSuchMethod forwarders that throw

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#49226]
As part of supporting https://github.com/dart-lang/language/issues/2020, I need to change the behavior of noSuchMethod forwarders so that they sometimes unconditionally throw an exception rather than forwarding to an instance of noSuchMethod.

I have a prototype of the necessary change here: https://dart-review.googlesource.com/c/sdk/+/246040/5.  It passes tests on all platforms but dart2js.

In a meeting with @sigmundch and @rakudrama a while back, it was suggested that maybe we need to remove the check `member.name.isPrivate && member.name.libraryName != member.enclosingLibrary.reference` at https://github.com/dart-lang/sdk/blob/a8550301206f3dc914e5136277ea33098d1ea129/pkg/compiler/lib/src/kernel/env.dart#L363-L368

But I tried this and didn't have any luck.

**Comment by johnniwinther** [comment]
The problem is that dart2js never handled private names (correctly). See for instance https://github.com/dart-lang/sdk/issues/33732

I have CL in progress that fixes this: https://dart-review.googlesource.com/c/sdk/+/252665
