### ISSUE TITLE
@useResult annotation doesn't count passing to a function as named argument as use

### ISSUE THREAD

**Issue by noinskit** [dart-lang/sdk#49230]
I have a group of functions that don't have side effects and should always be used somehow and I spent some time debugging a place where it was not used this way. I thought `@useResult` is the right defense-in-depth, but looks like it doesn't understand named arguments:
```dart
import 'package:meta/meta.dart';

@useResult
int test(int x) => x;

void functionWithPositionalArg(int x) {}

void functionWithNamedArg({required int x}) {}

main() async {
  functionWithPositionalArg(test(1)); // no warnings, all good
  functionWithNamedArg(x: test(2)); // "The value of 'test' should be used."
}
```

Docs for useResult clearly promise that "A value is considered used if it is (...) passed to a function".

**Comment by noinskit** [comment]
```
% flutter doctor --version
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (3 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

Also reproduces on https://dartpad.dev (which seems to use the same version that I have).

**Comment by noinskit** [comment]
I see that dartpad allows trying out different versions and it reproduces there on the beta channel as well ("Based on Flutter 3.1.0 Dart SDK 2.18.0-44.1.beta").

**Comment by bwilkerson** [comment]
I just confirmed that the bug has been fixed at HEAD. Note that @asashour was using a newer version of the Dart SDK than was being used in DartPad, which explains the difference. I don't know which version of Flutter will first contain the fix, but it is will appear in a future release.

**Comment by noinskit** [comment]
Understood, thank you!
