### ISSUE TITLE
Why is `remove` (and `contains`, `lookup`, ...) in `Set` not generic?

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/sdk#49231]
When removing an item from a set, one can't rely on type checking:

```dart
class MyClass {
  int myId;
  MyClass(this.myId);
}

main() {
  final myObj = MyClass(0);
  
  Set<int> ids = {};
  
  // compile error
  // ids.add(myObj);
  
  // wanted to do this, and noticed immediately, since the line above does not work
  ids.add(myObj.myId);
  
  // works, even though the set cant possibly contain this object
  ids.remove(myObj);

  // meant to write this, but the line above went unnoticed
  ids.remove(myObj.myId);
}
```

Why is `remove`(and other methods) not defined with the generic parameter? 

```dart
abstract class Set<E> extends EfficientLengthIterable<E> {
  //...
  bool add(E value);

  //...
  bool remove(Object? value);
  // bool remove(E? value); // <----- Why not this?

  //...
}
```

**Comment by lrhn** [comment]
This is a recurring question. See also:
https://github.com/dart-lang/sdk/issues/37685, https://github.com/dart-lang/sdk/issues/28690, https://github.com/dart-lang/sdk/issues/48030 and several other issues.

In short: It allows you to up-cast a `Set<int>` to `Set<num>` and call `numSet.remove(3.5)` without getting an error.
Removing something which isn't there is safe (so is asking whether it's there, looking it up, etc.)

No current plan to change the interfaces. It would be too breaking, and we don't have API versioning.

**Comment by eernstg** [comment]
Of course, with `myMap.remove(myValue)`, `Key` and `Value` could be the same type or `Value` could be a subtype of `Key`; similarly, you could do `remove(myInt)` from a collection of `int`, but `myInt` has a completely different meaning. In those situations a type-based diagnostic would not help.

But in those presumably very common situations where the relevant types are unrelated (not subtype, not supertype), you could consider enabling [collection_methods_unrelated_type](https://dart-lang.github.io/linter/lints/collection_methods_unrelated_type.html).

**Comment by ltOgt** [comment]
Thanks @eernstg , thats exactly what i was looking for!

**Comment by FireSourcery** [comment]
Should the argument be `covariant Object?` however?  So that users' subtype implementations can choose to restrict the type via override?

**Comment by lrhn** [comment]
If someone wants to restrict, they can do `covariant MyType` themselves, the super-interface doesn't have to do that.
