### ISSUE TITLE
Conditional import does not perform a check for file existence in if/else of said import

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#49255]
When using a conditional import, if a file does not exist, no error is reported for the conditional paths while writing the import in a dart file.

Consider this code sample:

```
import 'my_service_stub.dart'
    if (dart.library.io) 'my_io_service_impl.dart'
    if (dart.library.html) 'my_web_service_impl.dart';
```

If the file `my_service_stub.dart` does not exist, I get an error saying that the file does not exist. 
However that is not the case if either `my_io_service_impl.dart` or `my_web_service_impl.dart` don't exist.

It would be nice if the check could be extended to the conditionals in the import as well. (and exports?)

* Dart SDK Version: 2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "macos_x64"

**Comment by vsmenon** [comment]
Are you seeing this error during compilation, analysis, or both?

**Comment by lrhn** [comment]
The analyzer only uses the first import. It doesn't know which platform your code will run on, or be compiled for, so it just uses the default file.

**Comment by asashour** [comment]
Is this considered a bug, or the analyzer shouldn't check for some files in some OS configuration?

**Comment by navaronbracke** [comment]
> or the analyzer shouldn't check for some files in some OS configuration
I would expect the analyzer to check for the existence of all the files in the conditional import, regardless of the platform that you'd be eventually compiling for. So all three files in this case, not just the first one.

**Comment by bwilkerson** [comment]
The problem is that conditional imports are sometimes used with generated files, and some generators will only generate the files for the current platform. In such cases such a check would result in false positives with no remediation. Because the analyzer can't know whether the files would exist under different conditions, we have chosen to not report the error under any conditions. This is WAI.
