### ISSUE TITLE
out_of_memory_recovery_test flaking and timing out

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#49259]
`out_of_memory_recovery_test` is flaky on multiple configurations

![image](https://user-images.githubusercontent.com/3601775/173585478-7fceca42-6cac-4de9-85fb-08a85a096d23.png)
[current test status](https://dart-ci.firebaseapp.com/current_results/#/filter=standalone/out_of_memory_recovery_test&showAll)

[Log MacOS arm64](https://dart-ci.appspot.com/log/vm-kernel-nnbd-mac-debug-arm64/dartk-weak-asserts-mac-debug-arm64/327/standalone/out_of_memory_recovery_test)

The flakiness started recently on some configurations:

![image](https://user-images.githubusercontent.com/3601775/173586264-d87b97e3-c170-422f-b242-c39be7ac86d1.png)

The last new result being yesterday.

It might be https://github.com/dart-lang/sdk/commit/305c3e30c6aea9c05a1abec35eb5f7e09f716348, as it was the only GC commit yesterday. Those GC tweaks might have caused both https://github.com/dart-lang/sdk/issues/48920#issuecomment-1155161819 and this test to slow down.

@rmacnak-google could you investigate if your GC change could have caused this? If that isn't the culprit, I can dive deeper into what happened that made this test slower.

**Comment by sstrickl** [comment]
Same test went from Pass to Timeout again today on the same configuration: [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8810683958244906097/+/u/test_results/new_test_failures__logs_).

**Comment by rmacnak-google** [comment]
Probably was either issues with the test (it's not necessarily the case that a scavenge will be abort before we hit OOM) and the GC (need reset progress bars on aborted scavenge, etc) that have been recently fixed.
