### ISSUE TITLE
Passing `--enable-mirrors=false` does not set `dart.library.mirrors` to `false`.

### ISSUE THREAD

**Issue by abitofevrything** [dart-lang/sdk#49266]
Passing the `--enable_mirrors=false` flag disables imports of `dart:mirrors` so it would make sense for it to also prevent conditional imports gated behind `dart.library.mirrors` as they will not work. This is currently not the case.

## Steps to reproduce:
With the following code sample:
```dart
void main() => print(const bool.fromEnvironment('dart.library.mirrors'));
```
1. Run with `dart --enable_mirrors=false run main.dart`.

### Expected result
The above program should output `false` since `dart:mirrors` imports are disabled. Other programs that conditionally import files based on `dart.library.mirrors` (e.g `import 'a.dart' if (dart.library.mirrors) 'b.dart'`) should import the non-mirrors library (`a.dart` in this case).

### Actual result
The above program outputs `true` and libraries gated behind a conditional `dart.library.mirrors` import are imported regardless.

* Dart SDK Version: 2.18.0-163.0.dev (dev)
* OS: Linux 5.18.2-artix1-1

**Comment by bkonyi** [comment]
The flag is `--enable_mirrors=false` not `--enable-mirrors=false`. Can you give that a try?

**Comment by abitofevrything** [comment]
> The flag is `--enable_mirrors=false` not `--enable-mirrors=false`. Can you give that a try?

My bad - I had originally run it with `enable_mirrors` but made a typo when typing the issue. Edited to correct the mistake.

**Comment by johnniwinther** [comment]
Conditional imports support `dart.library.mirrors` but it is determined fully by the `Target` which it set to `true` for the JIT VM and `false` for AOT VM and all other backends.

**Comment by abitofevrything** [comment]
The reason this is an issue is that (from what I can tell), this is what prevents conditional mirror imports from working in flutter which sets this flag to prevent imports of mirrors when in debug mode.

This is an issue for me as my package supports being run without mirrors but does not work in flutter.

**Comment by alexmarkov** [comment]
8bc1cda3f726a0fcb1fee88a7981d8e6aba73c03 fixes the problem in standalone Dart VM.
801bbb551bd4b8c2a875f8f2c6ddb337e102e0f7 fixes the problem in Flutter.
