### ISSUE TITLE
dart run --snapshot crashes

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#49276]
`$ dart run --snapshot=server.snap --snapshot-kind=app-jit server.dart`
segfaults with:
```
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=2, si_addr=0x0
version=2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "macos_arm64"
pid=10314, thread=259, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=100d29620
  pc 0x000000019e5cc864 fp 0x000000016f15efa0 _platform_strlen+0x4
  pc 0x0000000100de4d24 fp 0x000000016f15efd0 dart::bin::File::OpenUri(dart::bin::Namespace*, char const*, dart::bin::File::FileOpenMode)+0x1c
  pc 0x0000000100d03458 fp 0x000000016f15f070 dart::bin::DFE::TryReadKernelFile(char const*, unsigned char**, long*, bool, std::__2::shared_ptr<unsigned char>*)+0xac
  pc 0x0000000100d032ec fp 0x000000016f15f0c0 dart::bin::DFE::ReadScript(char const*, unsigned char**, long*, bool, std::__2::shared_ptr<unsigned char>*)+0x54
  pc 0x0000000100d046b0 fp 0x000000016f15f190 dart::bin::RunMainIsolate(char const*, char const*, dart::bin::CommandLineOptions*)+0x518
  pc 0x0000000100d04264 fp 0x000000016f15f240 dart::bin::RunMainIsolate(char const*, char const*, dart::bin::CommandLineOptions*)+0xcc
  pc 0x0000000100d050d8 fp 0x000000016f15f3c0 dart::bin::main(int, char**)+0x5ec
  pc 0x0000000100d05ec8 fp 0x000000016f15f3d0 main+0xc
  pc 0x00000001033a508c fp 0x000000016f15f520 Unknown symbol
-- End of DumpStackTrace
[1]    10314 abort      dart run --snapshot=server.snap --snapshot-kind=app-jit server.dart
```

`$ dart --snapshot=server.snap --snapshot-kind=app-jit server.dart` works fine on the same machine.

It crashes on every input file, e.g:
```dart
void main() {
  print('hi');
}
```

Note that the current documentation [recommends](https://dart.dev/tools/dart-tool#:~:text=Use%20instead%20of%20the%20pre%2Dexisting%20Dart%20VM%20command%20(dart%20with%20no%20command).) using `dart run` instead of `dart`.

**Comment by rmacnak-google** [comment]
Fails on Linux too.

cc @bkonyi

**Comment by bkonyi** [comment]
Can you try `dart compile jit-snapshot server.dart`?

**Comment by mnordine** [comment]
That works. Does it do the exact same thing?

**Comment by bkonyi** [comment]
Yup, it does. There's probably just some weird interaction with the new CLI and the older VM flags. However, it's still worth investigating the crash as the invocation you were making should still work.

**Comment by bkonyi** [comment]
Hm, so it looks like the CLI isolate is configured to only run when there's no snapshot, so the `run` keyword causes confusion since it's not a valid file. I think that adding some logic to check for this case and print an error pointing users to `dart compile` is the right thing to do here. The legacy behavior will still work without the `run` keyword.
