### ISSUE TITLE
../../runtime/vm/message_snapshot.cc: 576: error: expected: !lib.IsNull()

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#49281]
I'm seeing the following crash in the analyzer server in the context of working on a plugin:

```
[13:59:42] [Analyzer] [Error] ../../runtime/vm/message_snapshot.cc: 576: error: expected: !lib.IsNull()
version=2.18.0-190.0.dev (dev) (Tue Jun 14 21:17:02 2022 -0700) on "macos_arm64"
pid=16256, thread=3599, isolate_group=main(0x1101bae00), isolate=main(0x110221800)
isolate_instructions=100a02be0, vm_instructions=100a02be0
[13:59:42] [Analyzer] [Error]   pc 0x0000000100c01bdc fp 0x0000000177386560 dart::Profiler::DumpStackTrace(void*)+0x68
[13:59:42] [Analyzer] [Error]   pc 0x0000000100a02d64 fp 0x0000000177386580 dart::Assert::Fail(char const*, ...) const+0x28
[13:59:42] [Analyzer] [Error]   pc 0x0000000100b73864 fp 0x0000000177386600 dart::ReadApiMessage(dart::Zone*, dart::Message*)+0x72f4
[13:59:42] [Analyzer] [Error]   pc 0x0000000100b6b5c4 fp 0x0000000177386680 dart::MessageDeserializer::Deserialize()+0x244
[13:59:42] [Analyzer] [Error]   pc 0x0000000100b6c4fc fp 0x00000001773867f0 dart::ReadMessage(dart::Thread*, dart::Message*)+0x148
[13:59:42] [Analyzer] [Error]   pc 0x0000000100b3f18c fp 0x0000000177386da0 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0xcc
[13:59:42] [Analyzer] [Error]   pc 0x0000000100b67420 fp 0x0000000177386e10 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x154
[13:59:42] [Analyzer] [Error]   pc 0x0000000100b67b5c fp 0x0000000177386e70 dart::MessageHandler::TaskCallback()+0x204
[13:59:42] [Analyzer] [Error]   pc 0x0000000100c86068 fp 0x0000000177386f30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14c
[13:59:42] [Analyzer] [Error]   pc 0x0000000100c86448 fp 0x0000000177386f60 dart::ThreadPool::Worker::Main(unsigned long)+0x78
[13:59:42] [Analyzer] [Error]   pc 0x0000000100bfe234 fp 0x0000000177386fc0 dart::OSThread::GetMaxStackSize()+0xac
  pc 0x000000019ccc026c fp 0x0000000177386fe0 _pthread_start+0x94
```

In an attempt to make my analyzer plugin debuggable during development, I'm replacing the actual plugin, that is spawned in its own isolate by the analyzer server, with a proxy, which forwards messages to the actual plugin over web-socket.

```dart
class ProxyPlugin {
  late final SendPort _serverSendPort;
  late final ReceivePort _pluginReceivePort;
  late final IOWebSocketChannel _remotePluginChannel;

  Future<void> start(SendPort serverSendPort) async {
    _serverSendPort = serverSendPort;
    _pluginReceivePort = ReceivePort();

    _serverSendPort.send(_pluginReceivePort.sendPort);

    _remotePluginChannel = IOWebSocketChannel.connect('ws://localhost:9999');

    _pluginReceivePort.listen(cancelOnError: false, (message) {
      final request = json.encode(message);
      _remotePluginChannel.sink.add(request);
    });

    _remotePluginChannel.stream.listen(cancelOnError: false, (message) {
      final response = json.decode(message as String) as Map<String, Object?>;
      if (response.containsKey('event')) {
         // Workaround for bug in analyzer server which expects `params` to have type 
         // `Map<String, Object>` instead `Map<String, Object?>`.
        response['params'] = {
          ...(response['params']! as Map).cast<String, Object>()
        };
      }
      _serverSendPort.send(response);
    });
  }
}
```

The messages that are passed to `_serverSendPort.send` and cause the crash consist of just plain dart objects as returned by `json.decode`.

```
Flutter 3.1.0-0.0.pre.1292 • channel master • https://github.com/flutter/flutter.git
Framework • revision b29c64b3f9 (2 hours ago) • 2022-06-17 06:28:07 -0400
Engine • revision 6cb83ab0f1
Tools • Dart 2.18.0 (build 2.18.0-190.0.dev) • DevTools 2.14.0
```

[Full Logs from VS Code extension](https://github.com/dart-lang/sdk/files/8927322/Dart-Code-Log-2022-05-05.13-59-36.txt)
[instrumentation.log.txt](https://github.com/dart-lang/sdk/files/8927465/instrumentation.log.txt)

**Comment by pq** [comment]
@bwilkerson

**Comment by bwilkerson** [comment]
Sorry, but I have no idea what that output even means. Perhaps someone on the VM team with knowledge of isolates could provide some insight.

**Comment by blaugold** [comment]
The crash is caused by the VM not being able to find the library for the class of an object that has been sent from one to another isolate, probably from the server isolate to the plugin isolate.

**Comment by bwilkerson** [comment]
Sorry, but that doesn't help much (probably because of a lack of knowledge on my part). The analysis server communicates with its plugins by sending and receiving string encodings of json compatible objects (maps and lists of strings, bools, and ints). Those then get translated into more semantically meaningful objects by the server and the plugins (assuming the plugins are built on the `analyzer_plugin` package). The conversion code explicitly imports and references that classes that it builds, so as far as I know the VM is guaranteed to know what library the classes came from.

Is there a mechanism that you're using to send something other than strings across the `IOWebSocketChannel`?

**Comment by blaugold** [comment]
No. All that the `ProxyPlugin` from above does is take the json compatible objects, encode them into json strings, send them over the `IOWebSocketChannel` and then decode json strings coming out of the channel and send those into the `_serverSendPort`.

**Comment by bwilkerson** [comment]
Have you tried not decoding the strings from the `_remotePluginChannel ` and just sending the strings through the `_serverSendPort`? If the `_serverSentPort` is the port used to communicate with the analysis server, then it's expecting strings and will do its own decoding.

**Comment by blaugold** [comment]
The `_serverSendPort` is the port that is passed into the `main` function of the plugin. I did try just passing the JSON strings from the `_remotePluginChannel` channel through, but then they seem to be ignored.

If I understand the analysis server side correctly, it expects either a `SendPort` or `Map` and ignores everything else:

https://github.com/dart-lang/sdk/blob/d0fc029f68a67dfe14ab4a1e7fc760ab6661c5c4/pkg/analyzer_plugin/lib/src/channel/isolate_channel.dart#L222-L237

Just FYI, the proxied plugin is using in the `analyzer_plugin` package, so it should be sending the correct messages.

**Comment by bwilkerson** [comment]
That doesn't match my memory, but obviously my memory is wrong (or the code's been changed since I last looked at it).

Is there any way (breakpoint, print, etc.) for you to figure out what object structure is being passed? That seems like your best bet for debugging the situation.

**Comment by blaugold** [comment]
The instrumentation log contains the messages passed between the server and the plugin.

I have created a [repository](https://github.com/blaugold/analysis_plugin_crash) with a minimal setup to reproduce the issue.

Curiously, there is a way to make the crash go away. The isolate that is spawned by the server for the plugin does not import the `analyzer_plugin` package. It just de/encodes to/from JSON and communicates over the network with the actual plugin running in a separate process.

When import `package:analyzer_plugin/plugin/plugin.dart` in the isolate running the proxy, the crash does not occur and everything works as expected. I'm still not using any of the imported elements.

**Comment by PixelToast** [comment]
Awhile ago I was working on a proxy plugin just like this one, you can work around the library error by putting `assert(ServerPluginStarter == ServerPluginStarter);` somewhere in the file, it seems the analysis server crashes if the plugin libraries aren't loaded in the plugin isolates.

**Comment by blaugold** [comment]
I'm closing this issue in favor of https://github.com/dart-lang/sdk/issues/50594. The root cause is that a `HashMap` is being sent to analyzer plugins when only `Map`s are supported by `SendPort`s between isolates spawned with `Isolate.spawnUri`.
