### ISSUE TITLE
add isBlank/isNotBlank getters to the String

### ISSUE THREAD

**Issue by elbeicktalat** [dart-lang/sdk#49280]
## The Problem
I have a `TextField`, which must contains value, also white spaces are not allowed. I know that I could have an **extension method**, but I think some common use case like this can be implemented in the core library.

## Actual solution
```dart
if (text.isEmpty && text.contains(' ')) {
// throw error
}
// some processes
```

## Proposal solution
```dart
// isBlank returns true if the given string is empty or contains only white space code points, otherwise false.
if (text.isBlank) {
// throw error
}
// some processes
```

In the end, I would like to say that I have my custom library to handle this and other use cases, but as I said, having this in the core library is very helpful.

Thanks!

**Comment by devoncarew** [comment]
I think extensions methods are actually a good solution here - it allows people to have the long tail of APIs use cases they want, while keeping the core API smaller.

From looking quickly, it looks like package:basics does have the extension method you want: https://github.com/google/dart-basics.

Thanks for the feedback!
