### ISSUE TITLE
update the usage instructions for dart2js_info

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#49285]
The readme for dart2js_info - https://github.com/dart-lang/sdk/blob/main/pkg/dart2js_info/README.md - indicates that people should try it out via `dart pub global activate`. However, the dart2js_info package is no longer published and has been marked as discontinued on pub.dev.

I'm not sure what the best way to try the tool out now is (cloning the repo, running gclient sync, and directly running the tool from pkg/dart2js_info?), but we should update the readme to whatever the current best practice is.

**Comment by nshahan** [comment]
cc @Markzipan

**Comment by Markzipan** [comment]
Thanks for pointing this out - I'll clean this up. I've noticed some dartium references in there as well, which is concerning
