### ISSUE TITLE
[analyzer] `AddConst` fix should handle `final` declarations

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49294]
```dart
class A {
  const A();
}

void f() {
  final a = A();
}
```

There is a [prefer_const_constructors](https://dart-lang.github.io/linter/lints/prefer_const_constructors.html) lint, with a fix, which adds `const`:

```dart
  final a = const A();
```

which leads to [prefer_const_declarations](https://dart-lang.github.io/linter/lints/prefer_const_declarations.html).

However, it should directly outputs

```dart
  const a = A();
```

instead.

<hr>

Another suggestion is to handle this in `ReplaceFinalWithConst`.

**Comment by keertip** [comment]
Yes, this would be good to have, but this scenario occurs only if you have both those lints enabled.

**Comment by asashour** [comment]
Please note that both belong to `Flutter`, so they are enabled by default.

**Comment by FMorschel** [comment]
> but this scenario occurs only if you have both those lints enabled.

The fixes/assists know when a certain lint is enabled so this is completely possible to fix.

**Comment by FMorschel** [comment]
https://dart-review.googlesource.com/c/sdk/+/392860
