### ISSUE TITLE
[analysis_server] tests to normalize EOL by default

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49297]
If changing the expectation of [this test](https://github.com/dart-lang/sdk/blob/a247b158d6fc2ae89e824080bd7877e7b51f642a/pkg/analysis_server/test/src/services/correction/fix/rename_method_parameter_test.dart#L26-L38) for example, to be:

```dart
await assertNoFix();
```

there are errors:

>Expected one error, found:
  C:\home\test\lib\test.dart(63..63): The parameter 'b' should have the name 'a' to match the name used in the overridden method. [LintCode.avoid_renaming_method_parameters]
  C:\home\test\lib\test.dart(66..66): The parameter 'a' should have the name 'b' to match the name used in the overridden method. [LintCode.avoid_renaming_method_parameters]

on Windows, but `(59..59)` and `(62..62)` on macOS.

This seems to come from different line endings.

There is [useLineEndingsForPlatform ](https://github.com/dart-lang/sdk/blob/a247b158d6fc2ae89e824080bd7877e7b51f642a/pkg/analysis_server/test/abstract_single_unit.dart#L22), but I guess if it is not enabled, the test should normalize the code to a specific OS, so that the error `offset` remains the same on all platforms.

This was detected in [sdk/248583](https://dart-review.googlesource.com/c/sdk/+/248583/)

**Comment by bwilkerson** [comment]
> There is `useLineEndingsForPlatform `, but I guess if it is not enabled, the test should normalize the code to a specific OS, so that the error `offset` remains the same on all platforms.

If that flag is not enabled, then the code shouldn't be changed from its already normalized state. When it is enabled, then we replace the linux-based line endings with the Windows-based end-of-line marker. The flag is enabled in `FixProcessorTest.setUp`. I believe that this is working as intended.

**Comment by asashour** [comment]
I see, thanks for the explanation.
