### ISSUE TITLE
Function extensions do not work when imported

### ISSUE THREAD

**Issue by harkairt** [dart-lang/sdk#49292]
Hello!

I have this in a file:
```dart
extension VoidFnX on void Function() {
  void Function()? when(bool condition) => condition ? this : null;
}
```

but I cannot use it (even if I manually import this file) in another file. (lint says it is an unused import)

When I copy over the extension into the file in which I want to use it, suddenly my syntax errors are gone and the extension function works properly.

Dart version `2.17.1`

**Comment by natebosch** [comment]
Closing for now. We can reopen if you have a reproduction case which does not work as expected.

**Comment by harkairt** [comment]
yes, thanks. 
I've tried it out again and it works, so.. I don't know what I've messed up.
