### ISSUE TITLE
MSAN Failures on Update clang and gn to match Fuchsia.

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#49298]
There are new test failures on [Update clang and gn to match Fuchsia.](https://github.com/dart-lang/sdk/commit/e9f629f607205f01db3fb6d8624debc30c60c3e8).

The tests
```
vm/cc/DartAPI_NativeFieldAccess Crash (expected Pass)
vm/cc/DartAPI_NativeFieldAccess_Throws Crash (expected Pass)
vm/cc/Dart_SetFfiNativeResolver Crash (expected Pass)
vm/cc/Dart_SetFfiNativeResolver_DoesNotResolve Crash (expected Pass)
vm/cc/Dart_SetFfiNativeResolver_MissingResolver Crash (expected Pass)
```
are failing on configurations
```
dartk-msan-linux-release-x64
```

@rmacnak-google @dcharkes

**Comment by dcharkes** [comment]
@rmacnak-google are you aware of any behavior changes of clang in this roll?
