### ISSUE TITLE
[Feature] Considered extending the enum class to include properties and methods like any other class?

### ISSUE THREAD

**Issue by CListery** [dart-lang/sdk#49300]
Similar to Kotlin...
```kotlin
enum class Color(val rgb: Int) {                      // 1
    RED(0xFF0000),                                    // 2
    GREEN(0x00FF00),
    BLUE(0x0000FF),
    YELLOW(0xFFFF00);

    fun containsRed() = (this.rgb and 0xFF0000 != 0)  // 3
}
```

**Comment by asashour** [comment]
With [enhanced enums](https://dart.dev/guides/language/language-tour#enumerated-types) (since `2.17` language version), this is possible

```dart
enum Color {
  RED(0xFF0000),
  GREEN(0x00FF00),
  BLUE(0x0000FF),
  YELLOW(0xFFFF00);

  final int x;

  const Color(this.x);

  bool containsRed() => x & 0xFF0000 != 0;
}
```

**Comment by CListery** [comment]
> With [enhanced enums](https://dart.dev/guides/language/language-tour#enumerated-types) (since `2.17` language version), this is possible
> 
> ```dart
> enum Color {
>   RED(0xFF0000),
>   GREEN(0x00FF00),
>   BLUE(0x0000FF),
>   YELLOW(0xFFFF00);
> 
>   final int x;
> 
>   const Color(this.x);
> 
>   bool containsRed() => x & 0xFF0000 != 0;
> }
> ```
> 
> Please note that language features are [here](https://github.com/dart-lang/language).

thank you very much
