### ISSUE TITLE
dart compile jit-snapshot can't take flags (like -o) or --options as training arguments

### ISSUE THREAD

**Issue by cpswan** [dart-lang/sdk#49302]
`Dart SDK version: 2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "linux_x64"`

If I try to pass an option `-e` as `[<training arguments>]`:

```
$ dart compile jit-snapshot args_example.dart -e 1234
Could not find an option or flag "-e".

Usage: dart compile jit-snapshot [arguments] <dart entry point> [<training arguments>]
...
```

or similarly `--example`:

```
$ dart compile jit-snapshot args_example.dart --example 1234
Could not find an option named "example".
...
```

Where `args_example.dart` is:

```dart
import 'package:args/args.dart';

void main(List<String> arguments) {

  final parser = ArgParser()..addOption('example', abbr: 'e');

  ArgResults argResults = parser.parse(arguments);
  
  print(argResults['example']);
  
}
```

It looks like this area has previously had attention for arguments that aren't preceded by `-` at #43839 and for env variables with #48447

**Comment by bkonyi** [comment]
Fix up for review [here](https://dart-review.googlesource.com/c/sdk/+/249340).

**Comment by cpswan** [comment]
@bkonyi do you know which SDK release this will find its way into? As 2.17.5 and 2.17.6 have been released since this was closed I was hopeful that they'd have the fix, but it seems not.

**Comment by mraleph** [comment]
@cpswan it in [2.18.0-226.0.dev](https://github.com/dart-lang/sdk/releases/tag/2.18.0-226.0.dev) or newer.
