### ISSUE TITLE
Disallow negative or hexadecimal content-length headers.

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#49305]
# Change

Generate a `HttpException` when `HttpHeaders.add(...)` encounters a negative or hexadecimal encoded `content-length`. Currently both are acceptable.

Also, change non-numeric input to raise a `HttpException` rather than a `FormatException` so that a consistent `Exception` is thrown.

#  Rationale

[RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2) says that the production for `content-length` is:

```
     Content-Length = 1*DIGIT
```

So we are currently accepting invalid input that might cause clients/servers to misbehave.

The possibility of `HttpHeaders.add(...)` throwing `FormatException` is undocumented so (partially) consolidate to `HttpException` (which is what is what is thrown for most parse failures).

# Impact

This change does not break any Google tests.

Note that this does **not** change the semantics of the [`HttpHeaders.contentLength` property](https://api.flutter.dev/flutter/dart-io/HttpHeaders/contentLength.html) where a negative value means remove the header completely.

# Mitigation

Users should not use `HttpHeaders.add(...)`  to set `content-length` headers that are not allowed by the RFC.

**Comment by brianquinlan** [comment]
@itsjustkevin - do we no longer need approval from Hixie and grouma?

**Comment by a-siva** [comment]
the breaking change lgtm, not sure who else needs to approve it.

**Comment by itsjustkevin** [comment]
@grouma and @Hixie thoughts on this breaking change request?

**Comment by Hixie** [comment]
LGTM

**Comment by vsmenon** [comment]
lgtm

**Comment by grouma** [comment]
LGTM

**Comment by brianquinlan** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/981bcf61c97f3857eca00b14342616c1681a7e43

**Comment by MaryaBelanger** [comment]
@brianquinlan just want to clarify for my own understanding (and documentation), 

> Note that this does not change the semantics of the [HttpHeaders.contentLength property](https://api.flutter.dev/flutter/dart-io/HttpHeaders/contentLength.html) where a negative value means remove the header completely.

Did you bring this up because `content-length` headers and the `HttpHeaders.contentLength` property are completely different items, and you don't want them getting conflated?

Or, did you mean that the statement on the api docs page "_The value is negative if there is no content length set._" doesn't need to change, because it's equivalent to the statement you made "_a negative value means remove the header completely._"
