### ISSUE TITLE
Uri.encodeFull bug

### ISSUE THREAD

**Issue by rdai** [dart-lang/sdk#49315]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* dart:core

* Dart SDK Version: 2.17.5
* Windows
* Chrome

https://dartpad.dev/1636449e87da414cfa657729e37c043e

The Uri.encodeFull doesn't seem to handle "#", maybe other symbols as well. 
For example "Family # 1.m4v" outputs as "Family%20#%201.m4v" so the "#" is not converted, the resulting URL is not valid.

but https://www.urlencoder.org/ gives "Family%20%23%201.m4v"

Thank you.
Ray

**Comment by mraleph** [comment]
This behaviour is documented, see https://api.dart.dev/stable/2.17.5/dart-core/Uri/encodeFull.html

> All characters except uppercase and lowercase letters, digits and the characters `!#$&'()*+,-./:;=?@_~` are percent-encoded. This is the set of characters specified in in ECMA-262 version 5.1 for the `encodeURI` function.
