### ISSUE TITLE
[analysis_server] failed test with linter `master`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49317]
As of 4d750a862d3f659107e0101d3035bcdc2ca3b2ee (with `linter` master), Windows seems to have two failing tests (at least with me):

1. `make_final_test.dart`

It seems that the `node` detected by the server is the `VariableDeclarationList`, and not previously the `name` (this was recently introduced in https://github.com/dart-lang/linter/commit/6e6be1e4aaf71efc72049a0faff82ce4bf6fddb2). And `MakeFinal` doesn't currently handle `node is VariableDeclarationList`

```
package:test_api                                             expect
test\src\services\correction\fix\fix_processor.dart 109:5    BulkFixProcessorTest.assertHasFix
===== asynchronous gap ===========================
test\src\services\correction\fix\make_final_test.dart 183:5  PreferFinalLocalsBulkTest.test_singleFile

Expected: an object with length of <1>
  Actual: []
   Which: has length of <0>
```

2. ~~`google_analytics_manager_test.dart`~~

`Dart SDK version: 2.18.0-216.0.dev (dev) (Tue Jun 21 21:30:43 2022 -0700) on "windows_x64"`

**Comment by asashour** [comment]
First point at [sdk/249584](https://dart-review.googlesource.com/c/sdk/+/249584)

**Comment by bwilkerson** [comment]
I think the second case was handled by https://dart-review.googlesource.com/c/sdk/+/249543. Sorry I didn't see the reference to your CL before that landed. Looking at the first CL now.
