### ISSUE TITLE
New feature wanted

### ISSUE THREAD

**Issue by seifalmotaz** [dart-lang/sdk#49330]
Hi.
 I know that there is a `Function.apply` method that works just like the main function.
 I have an idea to make a new function let's say `Function.prepare` that prepare the function to be called then calls the function later.
Example:

```dart
void example(String str) {
      print(str)
}

void main() {
      var preparedFunction = Function.prepare(example, ['hello world']);
      //  ... do some code then
      preparedFunction.call(); // or preparedFunction.apply();
}
```

**Comment by natebosch** [comment]
@julemand101 - It's a little different in that `Function.apply` unwraps a `List` into the individual arguments. It works to specialize to the argument shape in this example - and that's what I'd do in most cases.

@seifalmotaz - If you _do_ need to handle functions with unknown arity or argument type (I'd avoid this if you can) you can wrap `Function.apply`. This is not functionality we'll include directly in the SDK.

```dart
Object? Function() applyArguments(Function f, List<Object?> args) =>
    () => Function.apply(f, args);

void example(String str) {
  print(str);
}

void main() {
  var preparedFunction = applyArguments(example, ['hello world']);
  //  ... do some code then
  preparedFunction();
}
```

For more discussion around feature requests fo language level support for partial application, see https://github.com/dart-lang/language/issues/351
