### ISSUE TITLE
[analyzer] improve some diagnostic message parameters

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49355]
There seems to be some incorrect diagnostic message parameters:

1. `AMBIGUOUS_IMPORT` (AmbiguousImportTest.[test_variable_write](https://github.com/dart-lang/sdk/blob/d998ba033dde1d6499a23833d05a2b22ed35aa62/pkg/analyzer/test/src/diagnostics/ambiguous_import_test.dart#L296))

>The name 'x=' is defined in the libraries 'package:test/a.dart' and 'package:test/b.dart'.

2. `INVALID_OVERRIDE` (InvalidOverrideTest.[test_setter_overrides_abstract_field_invalid](https://github.com/dart-lang/sdk/blob/d998ba033dde1d6499a23833d05a2b22ed35aa62/pkg/analyzer/test/src/diagnostics/invalid_override_test.dart#L342))
>'B.x=' ('void Function(int)') isn't a valid override of 'A.x=' ('void Function(num)').

3. `MIXIN_APPLICATION_NO_CONCRETE_SUPER_INVOKED_MEMBER` (MixinApplicationNoConcreteSuperInvokedMemberTest.[test_class_setter](https://github.com/dart-lang/sdk/blob/d998ba033dde1d6499a23833d05a2b22ed35aa62/pkg/analyzer/test/src/diagnostics/mixin_application_no_concrete_super_invoked_member_test.dart#L229))
>The class doesn't have a concrete implementation of the super-invoked member 'foo='.

4. `PRIVATE_COLLISION_IN_MIXIN_APPLICATION` (PrivateCollisionInMixinApplicationTest.[test_class_superclassAndMixin_setter2](https://github.com/dart-lang/sdk/blob/d998ba033dde1d6499a23833d05a2b22ed35aa62/pkg/analyzer/test/src/diagnostics/private_collision_in_mixin_application_test.dart#L187))
> The private name '_foo=', defined by 'B', conflicts with the same name defined by 'A'.

**Comment by bwilkerson** [comment]
I wonder whether we might want to make some of those messages more specific about the kind of element being referred to. The `=` is the specification's (and hence implementation's) way of saying "setter". Given that there might be both a getter and a setter with the same name (from the user's perspective at least), perhaps we should say something like

> The setter 'x' is defined in the libraries 'package:test/a.dart' and 'package:test/b.dart'.

or

> The setter 'B.x' ('void Function(int)') isn't a valid override of 'A.x' ('void Function(num)').

**Comment by asashour** [comment]
Also:
```dart
import 'package:meta/meta.dart';

class A {
  @mustBeOverridden
  int f = 0;
}

class B extends A {}
```

gives `Missing concrete override implementation of 'f' and 'f='.`

**Comment by bwilkerson** [comment]
That could definitely be improved. Maybe something like "Missing a concrete implementation of both the getter and setter 'f'."? I don't think "override" is adding anything here, but the message does need to make it clear that both the getter and setter need to be overridden.

**Comment by asashour** [comment]
`AMBIGUOUS_IMPORT` in https://dart-review.googlesource.com/c/sdk/+/269900

The message wasn't change to `The setter ...`, because the test case has a `variable`, not a `setter`, from the user perspective.

**Comment by asashour** [comment]
`MIXIN_APPLICATION_NO_CONCRETE_SUPER_INVOKED_MEMBER` in https://dart-review.googlesource.com/c/sdk/+/279717

**Comment by asashour** [comment]
`PRIVATE_COLLISION_IN_MIXIN_APPLICATION` in https://dart-review.googlesource.com/c/sdk/+/279719

**Comment by asashour** [comment]
`MISSING_OVERRIDE_OF_MUST_BE_OVERRIDDEN` in https://dart-review.googlesource.com/c/sdk/+/279960
