### ISSUE TITLE
Crash in InferableTypeBuilderMixin.type

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#49357]
[This change](https://dart-review.googlesource.com/c/sdk/+/250102) has one `}` missing (during `git rebase`), and this causes a crash in CFE. See "Uncomment the next line to fix the crash" for the location.

**Comment by bwilkerson** [comment]
The line is in `pkg/analyzer/lib/src/dart/analysis/file_state.dart`.

**Comment by johnniwinther** [comment]
I can see errors in the logs but no crashes. Can you point me to where the crash can be seen?
