### ISSUE TITLE
Missing analysis error on use of super

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#49358]
This code does not produce any analysis errors:

```dart
class A {}

class B extends A {
  fn() => super;
}

void main() {}
```

When compiling the CFE produces the error:
```
Error: Can't use 'super' as an expression.
To delegate a constructor to a super constructor, put the super call as an initializer.
  fn() => super;
          ^^^^^
```

**Comment by bwilkerson** [comment]
I'm kind of surprised that this isn't a parse error. I'm not seeing how the grammar allows the example, but maybe it does.

**Comment by lrhn** [comment]
Still a thing. 

It seems that in some places, a `super` is expected to be continued by a selector, in other places that check is missing. 
It's probably easier for the parser to allow `super` as a "primary" and then allow any selector *or operator* to be used on it. (The analyzer error message for when it does disallow `super` by itself is "Missing selector such as '.identifier' or '[0]'.", which doesn't cover operators.)
It should just be a compile-time error (and putting it in the parser would be better) if the `super` is *not* the receiver of an explicit member invocation. (Implicit `.call` tear-off doesn't count.)

CFE has errors in all places where `super` is used as an expression by itself, with the error "Error: Can't use 'super' as an expression.".

More examples:
```dart
class C {
  String call() => "C";
}

class D extends C {
  Function tearoff() => super; // Tear-off (error if remove C.call).
  
  C self() => super;
  
  int badTypeSelf() => super; // Type error, `D` not assignable to `int`.
  
  returnOperand() {
    return super;
  }
  
  throwOperand() {
    throw super;
  }

  element() {
    // Has type `List<D>`, so typed like `this`.
    var l = [super];
    l.st<E<List<D>>>();
  }
  
  localfunc() { // For the return type inference.
    f() => super;
    f.st<E<D Function()>>(); 
  }

  assignment() {
    var s = super; // Error, expect selector.
  }
  argument() {
    print(super); // Error, expect selector.
  }
  statement() {
    super; // Error, expect selector.
  }
  switchStatement() {
   switch (super) {} // Error, expect selector.
  }
}

void main() {}

extension <T> on T {
  st<X extends E<T>>(){}
}
typedef E<T> = T Function(T);
```

**Comment by srawlins** [comment]
Fixed with https://dart-review.googlesource.com/c/sdk/+/369122
