### ISSUE TITLE
DartDevTools memory view get very slow after some tracking

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#49360]
I am trying the DDT to debug the memory usage of a console application but the UI gets unusable after couple rounds of tracking.

To reproduce just create any console app that generates many objects, start it with --observe, open the DDT memory panel, access the allocation tab, click the tracking button.  
Once it refreshes, click to order by bytes or count ordered by greatest.  
Mark checked the most allocated object from the list.  
Get back to the app and make it allocate some objects.  
Get back to DDT and click tracking again.  
In the panel below, click to list the object with most instances allocated.  
Try to use the scrollbar. Try to click any instance to see the stack trace.  
Get nuts.  

Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "macos_x64"

**Comment by mraleph** [comment]
Please file this issue at https://github.com/flutter/devtools

(Can't transfer it because the repo is in a different Github org.)
