### ISSUE TITLE
[analyzer] add fixes for `ABSTRACT_FIELD_CONSTRUCTOR_INITIALIZER`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49365]
As written [here](https://github.com/dart-lang/sdk/blob/80c742ea1197c7c77820c5bc28da659ddbf82140/pkg/analysis_server/lib/src/services/correction/error_fix_status.yaml#L91-L95), there should be two fixes:

- [ ] Remove the initializer [sdk/250162](https://dart-review.googlesource.com/c/sdk/+/250162)
- [ ] Remove the `abstract` keyword  [sdk/250161](https://dart-review.googlesource.com/c/sdk/+/250161)

There is a merge conflict between them.

**Comment by asashour** [comment]
Can we have a review please? Thanks.

**Comment by bwilkerson** [comment]
Thanks for the ping, and sorry I missed these earlier.
