### ISSUE TITLE
Compile deferred component error. Seem like a compile error in gen_snapshot.

### ISSUE THREAD

**Issue by lawangle** [dart-lang/sdk#49372]
## Environment:
flutter tools:  2.10.4(https://github.com/flutter/flutter/commit/c860cba910319332564e1e9d470a17074c1f2dfd)
dart version: 2.16.2 (https://github.com/dart-lang/sdk/commit/6fbb9236c65a54c26830f047b88709ac11bdf2ae)

## Replay steps: 
1. git clone flutter gallery: https://github.com/flutter/gallery/tree/fully-deferred-gallery . (I tried other branch, the bug is the same.) 
2. run: flutter build appbundle --verbose.
3. gen_snapthot .... command start
4. waiting and gen_snapthot fail

The problem log in my local environment is:
`[+822599 ms] [+822565 ms] Unresolved call to Code([Optimized] ___TabsNonScrollableDemoState&State&SingleTickerProviderStateMixin&RestorationMixin._updateProperty) from Code([Optimized]
__HomePageState&State&SingleTickerProviderStateMixin&RestorationMixin.registerForRestoration.listener)
[        ] [   +2 ms] Unresolved call to Code([Optimized] __CupertinoAlertDemoState&State&RestorationMixin._updateProperty) from Code([Optimized]
__LoginPageState&State&RestorationMixin.registerForRestoration.listener)
[        ] [        ] Unresolved call to Code([Optimized] __CupertinoAlertDemoState&State&RestorationMixin._updateProperty) from Code([Optimized]
__LoginPageState&State&RestorationMixin.registerForRestoration)
[        ] [        ] Unresolved call to Code([Optimized] __CupertinoAlertDemoState&State&RestorationMixin._updateProperty) from Code([Optimized] [tear-off]
__LoginPageState&State&RestorationMixin._updateProperty)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized]
__RallyPieChartState&State&SingleTickerProviderStateMixin.createTicker)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized] [tear-off]
__RallyPieChartState&State&SingleTickerProviderStateMixin._updateTicker)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized]
__HomePageState&State&SingleTickerProviderStateMixin.createTicker)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized] [tear-off]
__RallyTabState&State&SingleTickerProviderStateMixin._updateTicker)
[        ] [        ] Unresolved call to Code([Optimized] ___TabsNonScrollableDemoState&State&SingleTickerProviderStateMixin&RestorationMixin._updateProperty) from Code([Optimized] [tear-off]
__HomePageState&State&SingleTickerProviderStateMixin&RestorationMixin._updateProperty)
[        ] [        ] Unresolved call to Code([Optimized] ___TabsNonScrollableDemoState&State&SingleTickerProviderStateMixin&RestorationMixin._updateProperty) from Code([Optimized]
__HomePageState&State&SingleTickerProviderStateMixin&RestorationMixin.registerForRestoration)
[        ] [        ] Unresolved call to Code([Optimized] ___TabsNonScrollableDemoState&State&SingleTickerProviderStateMixin&RestorationMixin.restorePending) from Code([Optimized]
__HomePageState&State&SingleTickerProviderStateMixin&RestorationMixin.didUpdateRestorationId)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized] [tear-off]
__HomePageState&State&SingleTickerProviderStateMixin._updateTicker)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized]
__RallyTabState&State&SingleTickerProviderStateMixin.createTicker)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized]
__RallyPieChartState&State&SingleTickerProviderStateMixin.activate)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized]
__HomePageState&State&SingleTickerProviderStateMixin.activate)
[        ] [        ] Unresolved call to Code([Optimized] __ProgressIndicatorDemoState&State&SingleTickerProviderStateMixin._updateTicker) from Code([Optimized]
__RallyTabState&State&SingleTickerProviderStateMixin.activate)
[        ] [        ] Unresolved call to Code([Optimized] ___TabsNonScrollableDemoState&State&SingleTickerProviderStateMixin&RestorationMixin.restorePending) from Code([Optimized]
__HomePageState&State&SingleTickerProviderStateMixin&RestorationMixin.didChangeDependencies)
[        ] [        ] Unresolved call to Code([Optimized] new __TabsNonScrollableDemoState) from Code([Optimized] HomePage.createState)
[        ] [        ] ../../third_party/dart/runtime/vm/compiler/relocation.cc: 124: error: expected: all_unresolved_calls_.IsEmpty()
[        ] [   +2 ms] Dart snapshot generator failed with exit code -6`

## Other messages:
1. I tried flutter tools(v2.8.3, dart version: 2.15.1) and the result of 'build appbundle'  is successful.
2. I tried flutter tools in current stable branch, the dart-sdk is 2.17.5, this bug is gone.(I can't upgrade flutter directly, because it will cost us a lot of time to solve other problems.)
3. It's seems that caller in unit(=4) will call callee in other unit, but rellocation should happen in the same unit and then fail.  

I am a beginner in dart-sdk and i am very interesing in the bug's reason.

**Comment by mraleph** [comment]
In general we don't provide support for older versions, but @rmacnak-google might remember which bug could have been causing this and associated fix (if any).

**Comment by lawangle** [comment]
I understand. If there is any clue can be helpful.

**Comment by rmacnak-google** [comment]
`flutter build appbundle --no-deferred-components` is a possible work-around for older versions.

**Comment by lawangle** [comment]
> `flutter build appbundle --no-deferred-components` is a possible work-around for older versions.

Tks, but deferred component is necessary for our app.
I will try to find the bug, thanks.

**Comment by mraleph** [comment]
reopening to reflect that @lawangle has found an actual bug.

**Comment by mraleph** [comment]
This should be fixed now. Thanks for the contribution @lawangle!
