### ISSUE TITLE
Autocompletion is inconsistent with private class definitions

### ISSUE THREAD

**Issue by hacker1024** [dart-lang/sdk#49376]
Consider the following example:

```dart
void main() {
  // ...
}

class Example1 {}

class _Example2 {}
```

Often, I experience the following:

- If I show completions in the main function before typing anything, both declared classes show up.
- If I type `E` or `Ex` in the `main` function, `Example1` shows up as a suggestion.
- If I type `_` or `_E` in the `main` function, `_Example2` does _not_ show up as a suggestion.

This suggestion behaviour applies to many contexts, like when requesting suggestions for a class to construct in a variable assignment, or requesting suggestions for a class to implement.

If I declare a variable in the same library, like so...

```dart
final _example3 = Object();
```

...Then completions for classes with a `_` prefix start working, and sometimes it seems that they continue to do so for a short period even if I remove the variable declaration.

This issue may be related to #45868 - I'm not sure if it's a feature request or a report of another symptom of the underlying cause.

**Comment by keertip** [comment]
This example no longer reproduces. The underlying issue has been fixed, as also indicated by #45868 .
