### ISSUE TITLE
Provide a way to get the Android version (e.g. 12)

### ISSUE THREAD

**Issue by liaoxuewei** [dart-lang/sdk#49377]
This tracker is for issues related to:
Dart core libraries ("dart:async", "dart:io", etc.)

https://github.com/dart-lang/sdk/issues/36625

Has this problem been solved? How can I get the operating system version number, such as Android 12, and the version number is not 12 x. But a version number that is not suitable for human reading.

**Comment by liaoxuewei** [comment]
Example: HPB-AN006.1.0.125(...)

**Comment by a-siva** [comment]
A CL was submitted a while ago for this [sdk/commit/33273b5](https://github.com/dart-lang/sdk/commit/33273b5b257afe6c14ab5ec883d79d0df6abaa72) but I haven't verified if it does the right thing, will check and update here.

**Comment by liaoxuewei** [comment]
This has been submitted for a long time, but my version is almost the latest version. It should include this submission, which doesn't seem to work?

Is there any other way to get the readable operating system version? For example, the following version forms, android 11/android 12/windows 10

**Comment by liaoxuewei** [comment]
Because the processing of each version will be different, otherwise some processing will not be compatible.
I think this is also a necessary ability for flutter to cross platform.
Thanks!

**Comment by brianquinlan** [comment]
We might need to use JNI to get this info: https://developer.android.com/reference/android/os/Build.VERSION#SDK_INT

**Comment by brianquinlan** [comment]
Does the [`device_info_plus`](https://pub.dev/packages/device_info_plus) give you the information that you need?

Maybe in the [`sdkInt` property](https://pub.dev/documentation/device_info_plus/latest/device_info_plus/AndroidBuildVersion/sdkInt.html)
