### ISSUE TITLE
[CP] Avoid clobbering array length in AllocateArray stub on ARM

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#49398]
### Commit(s) to merge

ec9a660ccca94edaf04051192282c7ecaf2bcccc

### Target

stable

### Issue Description

Accidental register clobbering on the allocation slow path in `noSuchMethod` implementation on ARM leading to occasional hard to diagnose and work-around crashes in Flutter applications, e.g. https://github.com/flutter/flutter/issues/106510

### What is the fix

Avoid cloberring the register by passing correct value of `preserve_registers` argument to leaf runtime call scope.

### Why cherry-pick

Users have no reliable way to fix these crashes in their own code.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/106510

**Comment by vsmenon** [comment]
lgtm

**Comment by whesse** [comment]
This was picked into stable 2.17.6
