### ISSUE TITLE
[CP] [vm/ffi] Fix constant `Finalizable`s

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#49411]
### Commit(s) to merge

https://github.com/dart-lang/sdk/commit/d3ea8bff5c56e557bf5b4310fe2538feeda7b84c

### Target

stable

### Issue Description

```dart
class A implements Finalizable {}

void b([A? a]) {}

void main() {
  b();
}
```

crashes the compiler in `dart compile exe`.

### What is the fix

The VM relied on only seeing expression types emitted by the transformer implementing finalizable in the CFE. However, further transforms could change that expression, in this instance to a constant. The fix is that the VM just accepts all expressions types.

### Why cherry-pick

At least one user is running into this in production (cc @blaugold).

* https://github.com/dart-lang/sdk/issues/49402#issuecomment-1177310166

### Risk

low

### Issue link(s)

* https://github.com/dart-lang/sdk/issues/49402

**Comment by mraleph** [comment]
I support CP

**Comment by a-siva** [comment]
lgtm

**Comment by itsjustkevin** [comment]
Approving the cherry pick based on consensus.  Thank you everyone!

**Comment by whesse** [comment]
This was picked into stable 2.17.6
