### ISSUE TITLE
Duplicate exports should not be allowed

### ISSUE THREAD

**Issue by chrisnorman7** [dart-lang/sdk#49439]
Hi,
Currently, you can cheerfully have duplicate exports, and the linter does not complain.

I feel there should be a rule that does not allow this.

#### Reproduction Steps

* Run `dart create -t package duplicate_exports`
* Edit `duplicate_exports/lib/duplicate_exports.dart`.
* Duplicate the line that says `export 'src/duplicate_exports_base.dart';`
At this point, I think a warning about duplicate exports would be nice.

Thanks in advance.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/260703
