### ISSUE TITLE
Trying to run a Dart program without a "main" results in internal information

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#49432]
I accidentally tried running a program that didn't have a `main` function:

```bash
dart pub run packages/foo/bin/foo.dart
```

... which results in the following command-line error:

```
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
```

While technically correct, I'm guessing most users won't know what Kernel is and this could be better written as:

```
Invoked Dart programs must have a "main" function defined: 
https://dart.dev/guides/language/language-tour#a-basic-dart-program
```

Anyway, I realize this isn't super high priority, but could be a nice tiny addition for new users.

**Comment by Edwardndiyo** [comment]
I currently have this error, how do I solve it ?

**Comment by bkonyi** [comment]
> I currently have this error, how do I solve it ?

Hi @Edwardndiyo, if you're seeing this message you don't have `main()` defined in the entrypoint you've provided to `dart`. If that's not the case, can you please file a new issue with all the relevant information, including a minimal reproduction case?
