### ISSUE TITLE
Uri.parse auto replacing '+' with space in queryParameters

### ISSUE THREAD

**Issue by viJay-beep-code** [dart-lang/sdk#49462]
Below sample code is auto replacing '+' character in a query parameter with space, when fetching value using queryParameters.
```
Uri uri = Uri.parse('https://test.com/parse?code=sf+sf+/fd3' );
print(uri.query); //print - code=sf+sf+/fd3
print(uri.queryParameters['code']); //prints - sf sf /fd3
```
How to solve this?

**Comment by lrhn** [comment]
Replace `+` by `%2B`.

**Comment by viJay-beep-code** [comment]
Thanks, I know that replacing '+' with '%2B' will result into the correct string. But is it the official way to solve this? 
And is conversion from plus to space expected? What other characters need to be replaced?
