### ISSUE TITLE
[dart2js] Breaking change: remove support for compiling sources from http

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#49473]
**Context**: The dart2js compiler internally allowed compiling inputs provided via an HTTP client connection. Support for this was experimental and never documented. We don't believe this functionality is in use at this time, and we intend to delete it with the goal of reducing technical debt in our system.

**What can break?**
If you run dart2js and provide `http` URIs as inputs, the compiler will no longer download the files and compile them. Instead it will provide a compile-time error indicating that the compiler doesn't support http sources.

We don't expect this to be an active pattern used by the community today, but we are using this notice to make sure we didn't miss any use cases.

**Mitigation**
If by chance there is a use of this feature, the mitigation is to add a tool chain step to first download resources and then run the compiler with inputs from local disk.

/cc @itsjustkevin @kevmoo @mit-mit @vsmenon

**Comment by kevmoo** [comment]
SGTM!

**Comment by jakemac53** [comment]
There aren't active uses today, but it is potentially useful for running dart2js against a development server (like webdev, or the internal equivalent). Experiments have shown it to be pretty slow though compared to loading files from disk, even with a local server.

**Comment by itsjustkevin** [comment]
@Hixie @grouma @vsmenon @mit-mit thoughts on this breaking change?

**Comment by grouma** [comment]
SGTM.

**Comment by Hixie** [comment]
fine by me

**Comment by mit-mit** [comment]
SGTM

**Comment by itsjustkevin** [comment]
Marking this change as approved
