### ISSUE TITLE
Incorrect return type on an `@FfiNative` annotation causes segfault at runtime

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#49471]
Ideally there would be analysis and even compilation issues with this:

BAD: 

```dart
  @FfiNative<Handle Function(Pointer<Void>, Uint32, Uint32, Handle)>('Picture::toImageSync')
  external void _toImageSync(int width, int height, _Image outImage);
```

GOOD:

```dart
  @FfiNative<Void Function(Pointer<Void>, Uint32, Uint32, Handle)>('Picture::toImageSync')
  external void _toImageSync(int width, int height, _Image outImage);
```

Ideally the compiler or analyzer would have told me there's a mismatch between the return signature of the function and the generic parameter of the annotation. This was due to a copy paste error on my end, and resulted in a segfault at runtime that produced lots unsymbolized frames even in an unopt build.

@dcharkes maybe?

**Comment by dcharkes** [comment]
I recently discovered the same issue in the analzyer:

* https://github.com/dart-lang/sdk/issues/49412

I was under the impression this was only missing in the analyzer and that the CFE did check this report compilation errors. I will double check this.
