### ISSUE TITLE
[analyzer] Add a fix for `AMBIGUOUS_EXTENSION_MEMBER_ACCESS`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49489]
https://dart-review.googlesource.com/c/sdk/+/252583

<hr>
How to add an extension override for a case like:

```dart
extension E on int {
  int get a => 1;
}

extension E2 on int {
  set a(int v) {}
}

f() {
  0.a;
}
```

In the hints for fixing `AMBIGUOUS_EXTENSION_MEMBER_ACCESS` in `error_fix_status`, there is

> For each extension, add a fix to add an extension override.
~~

**Comment by bwilkerson** [comment]
An extension override specifies which extension a member is located in. The receiver is wrapped in parentheses (if it isn't already) and the name of the extension appears before the parenthesized target. In the case above, the fix would change the body of `f` to either read `E(0).a;` or `E2(0).a;`.

Obviously, this only works when the extension is named.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/252583
