### ISSUE TITLE
DartPad: "Internal Error: The compiler crashed when compiling this element."

### ISSUE THREAD

**Issue by jscholler** [dart-lang/sdk#49482]
This breaks the compiler on Dartpad :)
(Based on Flutter 3.0.5 Dart SDK 2.17.6)

```
class A {
  final String a = 'flower';
  final int t = 0;
  A();
}

class B extends A {
  B(super.a, super.t);
}

void main() async {
  var c = B('HELLO', 1);
  print(c.a);
  print(c.t);
}
```

**Comment by lrhn** [comment]
The analyzer correctly points out that the `super.a` and `super.t` parameters are invalid because the super-class constructor doesn't take two positional arguments.
Dart2js crashes instead. Crash seems to be in the front-end:
```

The compiler crashed: Crash when compiling null,
at character offset null:
Null check operator used on a null value
#0      DeclaredSourceConstructorBuilder.finalizeSuperInitializingFormals (package:front_end/src/fasta/source/source_constructor_builder.dart:337:48)
#1      DeclaredSourceConstructorBuilder.inferFormalTypes (package:front_end/src/fasta/source/source_constructor_builder.dart:255:9)
```

**Comment by chloestefantsova** [comment]
> That said, using a recent dev release of the SDK dart2js produces a compile-time error now, so it's quite likely this has been fixed already.

I agree. It seems to be fixed now. I'm closing the issue. Please reopen if needed.
