### ISSUE TITLE
Failures on Disallow invalid content-length.

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#49483]
There are new test failures on [Disallow invalid content-length.](https://github.com/dart-lang/sdk/commit/981bcf61c97f3857eca00b14342616c1681a7e43).

The tests
```
pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_amd_test Timeout (expected Pass)
pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_ddc_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac
unittest-asserts-release-mac-arm64
```

**Comment by a-siva** [comment]
//cc @sigmundch

**Comment by a-siva** [comment]
//cc @brianquinlan

**Comment by nshahan** [comment]
Yeah that looks like it could likely be the problem. 
https://dart-review.googlesource.com/c/sdk/+/250260/4/pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_shared.dart#941

Would `'content-length': 0,` be a more appropriate migration if the content passed is `null`?

**Comment by sigmundch** [comment]
I was wondering that, according to the rfc: https://www.rfc-editor.org/rfc/rfc9110.html#name-content-length

> _A server MAY send a Content-Length header field in a response to a HEAD request ([Section 9.3.2](https://www.rfc-editor.org/rfc/rfc9110.html#HEAD)); a server MUST NOT send Content-Length in such a response unless its field value equals the decimal number of octets that would have been sent in the content of a response if the same request had used the GET method._

So, I'd say we would need to extract the file size instead of sending 0.

**Comment by nshahan** [comment]
@sigmundch Are you suggesting we should read the file and include the content regardless of the request type? So the existing migration:

```dart
if (await entity.existsAsyncIfPossible()) {
  if (request.method == 'HEAD') {
    var headers = {
      'content-length': '-1',
      ...request.headers,
    };
    return Response.ok(null, headers: headers);
  }

  if (request.method == 'GET') {
    // 'readAsBytes'
    var contents = await entity.readAsBytesAsyncIfPossible();
    var headers = {
      'content-length': '${contents.length}',
      ...request.headers,
    };
    return Response.ok(contents, headers: headers);
  }
}
```

should be changed to:
```dart
if (await entity.existsAsyncIfPossible()) {
  // 'readAsBytes'
  var contents = await entity.readAsBytesAsyncIfPossible();
  if (request.method == 'HEAD') {
    var headers = {
      'content-length': '-1',
      ...request.headers,
    };
    return Response.ok(contents, headers: headers);
  }

  if (request.method == 'GET') {
    var headers = {
      'content-length': '${contents.length}',
      ...request.headers,
    };
    return Response.ok(contents, headers: headers);
  }
}
```

**Comment by sigmundch** [comment]
Close - I was thinking we'd keep the body of the response empty, but include the length only in the header.

```dart
if (await entity.existsAsyncIfPossible()) {
  // 'readAsBytes'
  var contents = await entity.readAsBytesAsyncIfPossible();
  if (request.method == 'HEAD' || request.method == 'GET') {
    var headers = {
      'content-length': '${contents.length}',
      ...request.headers,
    };
    return Response.ok(request.method == 'GET' ? contents : null, headers: headers);
  }
}
```

**Comment by nshahan** [comment]
Sounds good. I'll test it and send a change.
