### ISSUE TITLE
unnecessary_import hint is not reported if the same number of elements are used from each file

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#49497]
### a.dart

```dart
class A {}
```

### b.dart

```dart
export 'a.dart';
```

### foo.dart

```dart
// Only one of these is required.
import 'a.dart';
import 'b.dart';

A? a;
```

In `foo.dart`, one of the imports is unnecessary but it's not reported because the number of used elements from each file is the same (1). The relevant code is here:

https://github.com/dart-lang/sdk/blob/b6c8bd7a81d3a71a0e57a152626538012396823f/pkg/analyzer/lib/src/error/imports_verifier.dart#L689

Adding a second class to `b.dart` and using it in `foo.dart` causes `a.dart` to be marked as unnecessary.

Changing the `>` to `>=` in the code above likely won't work, because both imports would be deemed unnecessary. I think it needs some deterministic way to decide which one is unnecessary (I don't know if it also needs to take into account when there's more than two providing the same items too?).

@bwilkerson @srawlins

**Comment by srawlins** [comment]
That would be a "redundant" import. https://github.com/dart-lang/sdk/issues/44569

**Comment by DanTup** [comment]
Ah, gotcha - makes sense. Closing this since it seems like a dupe of that then. Thanks!
