### ISSUE TITLE
Lack of precise indication to a specific place in code which caused the type error

### ISSUE THREAD

**Issue by Heretiq** [dart-lang/sdk#49494]
### Commit(s) to merge

n/a

### Target

no idea

### Issue Description

While practicing the following code on DartPad, I had an "Uncaught TypeError: Cannot read property '$add' of nullError: TypeError: Cannot read property '$add' of null" in the console.
![image](https://user-images.githubusercontent.com/42956202/180097320-0924bb8e-8208-43f4-9a35-7201b8912fe2.png)
It would be nice to know the precise location of the place in the code which caused the error, like in Java (line 9 in the occurrence - announcement of the variable fibListEvenSum).
Sure, if I assign 0 to var fibListEvenSum, there will be no this error. But it would be much more difficult to find it out in a more complex and long code.
And, for better readability,  it would be also nice to organise better the spacing in the error description:
"Uncaught TypeError: Cannot read property '$add' of null<add fullstop or semicolon>Error: TypeError: Cannot read property '$add' of null".

void main() {
  var limit = 4000000;
  var fibList = <int>[];
  var fibListEvenSum;
  fibList.add(1);
  fibList.add(2);
  while (fibList[fibList.length - 1] <= limit) {
    var newItem = fibList[fibList.length - 1] + fibList[fibList.length - 2];
    if (newItem <= limit) fibList.add(newItem);
    else break;
  }
  for (int item in fibList) {
    print(item);
    if (item % 2 == 0) fibListEvenSum += item;
  }
  print("The sum is $fibListEvenSum");
}

### What is the fix

It would be nice to know the precise location of the place in the code which is the cause of the type error.
And, for better readability,  it would be also nice to organise better the spacing in the error description:
"Uncaught TypeError: Cannot read property '$add' of null<add fullstop or semicolon>Error: TypeError: Cannot read property '$add' of null"

### Why cherry-pick

for better debugging and readability

### Risk

low

### Issue link(s)

n/a

**Comment by itsjustkevin** [comment]
Please read https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel and submit a normal issue for this under the dart-pad repository.
