### ISSUE TITLE
[CP] Please cherry pick da18c7c9a7080cc0ccd8455e1df85289b6445174 into the beta branch

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#49493]
### Commit(s) to merge

da18c7c9a7080cc0ccd8455e1df85289b6445174

### Target

beta

### Issue Description

Future produced by async function has wrong type argument

This is a regression that was introduced in the new restructured async implementation.

### What is the fix

In order to create a Future for the result of async closure,
closure needs to instantiate a type argument of its result type.
The result type may reference type arguments of enclosing function or
class and scope builder should visit closure's result type
in order to capture receiver or type arguments variable of parent
factory.

[https://dart-review.googlesource.com/c/sdk/+/251320](https://dart-review.googlesource.com/c/sdk/+/251320)

### Why cherry-pick

It is a regression

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/49424

### Extra Info

The CL merges cleanly into the beta channel.

**Comment by itsjustkevin** [comment]
@a-siva is this regression applicable to the stable branch also?

@vsmenon @athomas @sigmundch could you give votes on this cherry-pick?

**Comment by vsmenon** [comment]
lgtm

**Comment by sigmundch** [comment]
lgtm as well

**Comment by a-siva** [comment]
> @a-siva is this regression applicable to the stable branch also?

No.

**Comment by whesse** [comment]
This fix is cherry-picked in 2.18.0-271.4.beta.
