### ISSUE TITLE
No errors or hints when `@mustCallSuper` annotates inappropriate elements.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#49499]
I think that `@mustCallSuper` can only annotate a class's or mixin's instance members (methods, operators, getters, setters, or fields). But no error/hint is reported when you annotate other things with `@mustCallSuper`.

**Comment by bwilkerson** [comment]
I'll just note that the documentation states that the annotation is

> Used to annotate an instance method `m`.

Operators are generally considered to be methods, but getters, setters, and fields are not.
