### ISSUE TITLE
Failures on [anaysis_server] Cancel in-progress LSP completion requests if another arrives

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#49501]
There are new test failures on [[anaysis_server] Cancel in-progress LSP completion requests if another arrives](https://github.com/dart-lang/sdk/commit/055774958d7158fccb95dd67805cefc89bfb3598).

The tests
```
pkg/dds/test/sse_smoke_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac
```

Logs: https://dart-ci.appspot.com/log/pkg-mac-release/unittest-asserts-release-mac/22444/pkg/dds/test/sse_smoke_test

**Comment by DanTup** [comment]
I don't think this failure is related to 055774958d7158fccb95dd67805cefc89bfb3598. That change is package:analysis_server but this failure is in DDS.

The error contains this:

 SessionNotCreatedException (500): session not created: This version of ChromeDriver only supports Chrome version 101
  Current browser version is 103.0.5060.134 with binary path /opt/s/w/ir/cache/builder/sdk/third_party/browsers/chrome/Google Chrome.app/Contents/MacOS/Google Chrome

I don't know how Chrome/ChromeDriver are versioned in the SDK, but perhaps this is the cause? @bkonyi do you know about this?

**Comment by DanTup** [comment]
Looks like this has come up before. there's an open issue at #43743 that may be tracking it?

**Comment by liamappelbe** [comment]
Yeah, looks like it. Closing this as a dupe.
