### ISSUE TITLE
[analyzer] add fixes for some `AnalysisOptionsHintCode`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49513]
https://dart-review.googlesource.com/c/sdk/+/252580

Also, it seems that `ANALYSIS_OPTION_DEPRECATED` is already included in `STRONG_MODE_SETTING_DEPRECATED`, so it should be removed.

**Comment by bwilkerson** [comment]
> Also, it seems that ANALYSIS_OPTION_DEPRECATED is already included in STRONG_MODE_SETTING_DEPRECATED, so it should be removed.

Sorry, but I don't know what you mean. It's "included" in what sense? Which one do you think should be removed?

**Comment by asashour** [comment]
Sorry, I wasn't clear.

I meant that

```dart
analyzer:
  strong-mode:
    declaration-casts: false
```

is included in 
```dart
analyzer:
  strong-mode: true
```

In other words, deprecation of the sub-value of `strong-mode` is not needed, because the parent (`strong-mode`) is already deprecated, so whether the child is deprecated or not, it will be removed (by parent removal).

**Comment by bwilkerson** [comment]
That makes sense, thanks.
