### ISSUE TITLE
[dart2js] Allow to specify headers for `EventSource`

### ISSUE THREAD

**Issue by Lenny4** [dart-lang/sdk#49527]
It would be nice to be able to specify specify header for [EventSource](https://api.dart.dev/be/169657/dart-html/EventSource-class.html).

Now the constructor only accept 2 parameters: `url`, `withCredentials`.

It would be nice to add a third parameter `headers` which will allow to pass custom [HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers).

Thanks.

**Comment by rileyporter** [comment]
Thanks for the suggestion! 

It looks like the [`EventSource` API](https://docs.w3cub.com/dom/eventsource/eventsource) isn't defined by the Web specification to take in a custom HTTP header. Our intention with `dart:html` APIs is to generally try and match the Web specification, so I don't see us adding this extra parameter right now.

However, as a workaround, you could use [JS interop with `@staticInterop`](https://pub.dev/packages/js). There are some limitations which might not fit your use case exactly, but for now, `@staticInterop` is our recommended path for interop with native types.
