### ISSUE TITLE
[CP] Fix DevTools crash for web apps with weak null safety

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#49525]
### Commit(s) to merge

901d01a45cc8ff527384c23bff2386ccefae4eeb

### Target

Beta

### Issue Description

During the migration of DDC to null safety a change accidentally introduced a bug that passed a value of the completely wrong type to a method that accepts a dynamic argument. This code path can be triggered by loading Dart/Flutter DevTools for a web app that is running with weak null safety. The compiler used by DevTools during expression evaluation will crash.

### What is the fix

The API in question requires a value typed as a JavaScript expression AST node or a list of JavaScript expression AST nodes. The bug accidentally passed a Kernel AST node instead. The fix very simple, change the Kernel AST `NullLiteral` value to be a JavaScript AST `LiteralNull` value.

### Why cherry-pick

This cherry pick fixes a bug that prevents users from running Dart/Flutter DevTools in a web application that is running with weak null safety.

### Risk

low

### Issue link(s)

https://b.corp.google.com/issues/239838271

**Comment by nshahan** [comment]
cc @sigmundch

**Comment by itsjustkevin** [comment]
@vsmenon @kenzieschmoll @sigmundch thoughts on this CP?

**Comment by sigmundch** [comment]
I'm strongly in favor of cherry-picking this. This would be a big regression we can prevent. The regression started with https://github.com/dart-lang/sdk/commit/de90931be4d9ff2931af4b655070d1774a330a73 (June 22), and was included on the last beta cut [2.18.0-271.2.beta](https://github.com/dart-lang/sdk/releases/tag/2.18.0-271.2.beta). Note that the fix is minimal (1 line, everything else is test coverage).

**Comment by vsmenon** [comment]
lgtm

I'm a bit confused by @nshahan 's 'why' description though.  Do we not support DevTools with weak null safety?

**Comment by nshahan** [comment]
@vsmenon Sorry about that, I didn't word that very clearly. The bug prevents a user from running DevTools to debug a web application that is running with weak null safety. This CP will fix that and allow DevTools to work as expected.

**Comment by vsmenon** [comment]
Thanks for clarifying!

lgtm

**Comment by whesse** [comment]
This fix is cherry-picked in 2.18.0-271.4.beta.
