### ISSUE TITLE
[web] incorrect result for XOR with negative numbers

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#49523]
The code below prints `-1` when executed with the Dart VM and `4294967295` when executed in a JS engine such as NodeJS.

```dart
void main() {
  print(0 ^ -1);
}
```

I would expect that `0 ^ -1` always evaluates to `-1`.

**Comment by lrhn** [comment]
Known behavior of all bitwise operations when compiled to JavaScript. See, e.g., #49498.

**Comment by blaugold** [comment]
Ah, sorry. Should have read the docs :)
