### ISSUE TITLE
Make `Dart_Post` schedule on port's isolate

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#49524]
This tracker is for issues related to:
* Dart VM

There doesn't appear to be a way to post data from C onto an arbitrary isolate.  What I'd like to do is:

```c++
class Router {
  public:
    void handlePlatformMessage(Dart_Handle channel, Dart_Handle message, Dart_Port port, Dart_Handle callback) {
      // Called on arbitrary isolate thread.
      std::shared_ptr<Handler> handler;
      {
        std::scoped_lock lock(mutex_);
        handler = _handlers[ToCppString(channel)];      
      }
      handler->thread->post([handler, port, callback]() {
        std::unique_ptr<Bytes> result = handler->exec(message);
        Dart_Handle dart_result = ZeroCopyConversion(result.release());
        Dart_Post(port, callback);
        Dart_Post(port, dart_result);
      });
    }
  private:
    std::mutex mutex_;
    std::map<std::string, std::shared_ptr<Handler>> handlers_;
};
```

I don't believe this is possible with today's API since `Dart_Post` requires that `Dart_CurrentIsolate() != nullptr` and one cannot safely call `Dart_EnterIsolate` safely from an arbitrary thread since it is an error to do so if another thread has already "entered" that isolate.

This could be implemented by making ports store their isolate so that `Dart_Post` can schedule with that isolate, thus removing the dependency on `Dart_CurrentIsolate()`'s value.

This is a required feature if we ever want to implement https://github.com/flutter/flutter/issues/13937 since this would allow scheduling on an arbitrary isolate's event loop via the SendPort API.

cc @mkustermann

**Comment by rmacnak-google** [comment]
`Dart_Post` is for a sender running with a current isolate, which is the only way to even have `Dart_Handle`s to serve as a message. There must a current isolate, but it does not need to be the isolate of the destination port.

`Dart_PostCObject` is for a sender running without an isolate, which necessarily can't have `Dart_Handle`s and so must provide `Dart_CObject`s as the message instead.

**Comment by gaaclarke** [comment]
Thanks, `Dart_PostCObject` is what I was looking for.

**Comment by mkustermann** [comment]
> This could be implemented by making ports store their isolate so that Dart_Post can schedule with that isolate, thus removing
> the dependency on Dart_CurrentIsolate()'s value.

Ports do store the isolate which will process messages sent to the a port. Though only as long as the isolate is alive, after it's death, posting messages to the port will be silently dropped. So the reference from Port to Isolate is in some sense a weak reference (and stored in our `PortMap`)

> Thanks, Dart_PostCObject is what I was looking for.

To persist references to objects that the receiver can use (e.g. `callback` closure in your case) you can use persistent handles.
