### ISSUE TITLE
[frontend_server] FrontendCompiler gives incorrect sources to track when options change from having a package to having no package. 

### ISSUE THREAD

**Issue by michaelRichards99** [dart-lang/sdk#49534]
This tracker is for issues related to:
* pkg/frontend_server
* Common Front End (CFE) and kernel

Dart SDK Version:  2.18.0-edge.0a269370d732f34e77126b8817c827971c397aae
OS: MacOSX

I put the code below in the pkg/frontend_server/test/frontend_server_test.dart file and ran with the command `python3 tools/test.py -v -n unittest-asserts-release-mac pkg/frontend_server/test/frontend_server_test.dart`

The following unit test causes the FrontendCompiler to output incorrect tracked sources. The issue seems to be caused by "--packages" flag.  If the test is run with the empty package_config.json that is commented out, the tracked sources remain valid, but using the example with a single package, it gives incorrect output.  

The problem also persists across FrontendCompiler instances. Instantiating a new instance for each compile still maintains the tracked sources bug. 

`
test('tracked sources remain valid when packages change', () async {
      var file = File('${tempDir.path}/src1.dart')
        ..createSync()
        ..writeAsStringSync("main() {}\n");
      var file2 = File('${tempDir.path}/src2.dart')
        ..createSync()
        ..writeAsStringSync('''main() {}''');
      var packages = File('${tempDir.path}/.dart_tool/package_config.json')
        ..createSync()
        // ..writeAsStringSync('{"configVersion": 2, "packages": []}');
        ..writeAsStringSync('''
      {
        "configVersion": 2,
        "packages": [
          {
            "name": "hello",
            "rootUri": "../",
            "packageUri": "./"
          }
        ]
      }
      ''');
      var dillFile = File('${tempDir.path}/app.dill');

      final List<String> noPackageArgs = <String>[
        '--sdk-root=${sdkRoot.toFilePath()}',
        '--incremental',
        '--platform=${platformKernel.path}',
        '--output-dill=${dillFile.path}',
        '--target=vm',
        '--filesystem-scheme',
        'org-dartlang-root',
      ];
      final List<String> packageArgs = <String>[
        '--sdk-root=${sdkRoot.toFilePath()}',
        '--incremental',
        '--packages=${packages.path}',
        '--platform=${platformKernel.path}',
        '--output-dill=${dillFile.path}',
        '--target=vm',
        '--filesystem-scheme',
        'org-dartlang-root',
      ];

      var compilerOutput = StringBuffer();
      FrontendCompiler compiler = FrontendCompiler(compilerOutput);

      // source 1
      // compiler = FrontendCompiler(compilerOutput);
      await compiler.compile(file.path, argParser.parse(packageArgs));
      print(compilerOutput.toString());
      compilerOutput.clear();
      compiler.acceptLastDelta();
      compiler.resetIncrementalCompiler();
      // source 2
      // compiler = FrontendCompiler(compilerOutput);
      await compiler.compile(file2.path, argParser.parse(noPackageArgs));
      print(compilerOutput.toString());
      compilerOutput.clear();
      compiler.acceptLastDelta();
      compiler.resetIncrementalCompiler();
      // source 2 package changes
      // compiler = FrontendCompiler(compilerOutput);
      await compiler.compile(file2.path, argParser.parse(packageArgs));
      print(compilerOutput.toString());
      compilerOutput.clear();
      compiler.acceptLastDelta();
      compiler.resetIncrementalCompiler();

      expect(true, false);
    });
`

The result of running this unit test is:

result e7f3d989-e827-4def-8dcd-2e37c1e4b138
e7f3d989-e827-4def-8dcd-2e37c1e4b138
+file:///var/folders/h1/9j46flx1153c50f281y4rqbm00zl3b/T/frontendServerTestc1EcSP/src1.dart
e7f3d989-e827-4def-8dcd-2e37c1e4b138 /var/folders/h1/9j46flx1153c50f281y4rqbm00zl3b/T/frontendServerTestc1EcSP/app.dill 0

result 148a5515-2a38-4d74-babb-0afd8682b1bf
148a5515-2a38-4d74-babb-0afd8682b1bf
+file:///var/folders/h1/9j46flx1153c50f281y4rqbm00zl3b/T/frontendServerTestc1EcSP/src2.dart
148a5515-2a38-4d74-babb-0afd8682b1bf /var/folders/h1/9j46flx1153c50f281y4rqbm00zl3b/T/frontendServerTestc1EcSP/app.dill 0

result 14b321d5-4689-4f9b-8086-34055d0d7d30
14b321d5-4689-4f9b-8086-34055d0d7d30
-file:///var/folders/h1/9j46flx1153c50f281y4rqbm00zl3b/T/frontendServerTestc1EcSP/src1.dart
14b321d5-4689-4f9b-8086-34055d0d7d30 /var/folders/h1/9j46flx1153c50f281y4rqbm00zl3b/T/frontendServerTestc1EcSP/app.dill 0

The second output is incorrect. It is saying that both src1.dart and src2.dart should be tracked.

**Comment by michaelRichards99** [comment]
Edit: I did some more testing and the compiler also returns incorrect tracked sources even when the "--packages" option does not change.  As long as 2 separate Dart entry points are compiled in the same process, it gives incorrect results. 

`
await compiler.compile(file.path, argParser.parse(packageArgs));
`
`
await compiler.compile(file2.path, argParser.parse(packageArgs));
`

A request as simple as this in the example test above can be used to reproduce. It also persists across FrontendCompiler instances.

**Comment by aam** [comment]
thanks @michaelRichards99 .
Can you clean up the repro test above so instead of printing things out, t has an assert that fails on exact line where expectations are not met? If possible you can create a Gerrit CL from this as well marking the test as skipped for now.

**Comment by michaelRichards99** [comment]
Here's the Gerrit CL with unit test that fails: https://dart-review.googlesource.com/c/sdk/+/253002

**Comment by aam** [comment]
cc @jensjoha for ideas regarding why the list of sources reportedly used by incremental compiler seems to be outdated(no longer used files are still being reported as used).

@michaelRichards99 can you confirm that this is what causing problems for you: files that should no longer be used by the compiler are still being tracked? Besides performance downsides does it cause correctness problems?

**Comment by michaelRichards99** [comment]
Through my testing I've gotten it into cases where its tracking files it should no longer be tracking, and where it's not tracking files that should be tracked. If the package_config file contains an empty list of packages, the problem seems to go away, but real Dart packages don't have this structure.

There are no correctness problems in the existing SDK that I've noticed. But in this [CL](https://dart-review.googlesource.com/c/sdk/+/252001) which allows for compilations across any number of Dart entry points, this does lead to correctness problems.

**Comment by aam** [comment]
> and where it's not tracking files that should be tracked.

Do you have a failing test for that? (similarly to how https://dart-review.googlesource.com/c/sdk/+/253002 highlights issues with tracking more files than needed - which should not cause correctness problems as far as I understand for your CL).

**Comment by michaelRichards99** [comment]
I've added a [unit test to the CL](https://dart-review.googlesource.com/c/sdk/+/253002) which shows more weird output. 

Sorry I was incorrect on my last comment. The issue is that Its reporting fewer tracked sources than needed. The CL I linked to where this resulted in correctness issues maintains a set of tracked sources that the compiler outputs and when interpreting the results of the newly added unit test, after the 3rd compile request which outputs only '-src1.dart', It would leave tracked sources as an empty set, and the next compile request would be invalid.

**Comment by jensjoha** [comment]
Generally, tracking "more than expected" is working as intended.
The incremental compiler keep libraries from files in packages around as we've seen - in flutter tests - that some tests don't depend on the flutter libraries, but as the next test we will be told to compile probably will we don't want to throw the work of having compiled all of flutter away. This is also a reason why having an empty packages file changes the behaviour: The compiled files are now not in a package.

So to me the +file2 output on the second run isn't a surprise. What did surprise me though was the -file1 on the third run. It's mostly because `.compile` initializes from the old dill (which wasn't obvious for me from the name without the context of there also being a `.recompileDelta`).

In more detail:
1) The provided test says `.compile` which internally creates a new incremental compiler, initializing from the previously generated dill file.
2) While a packages file isn't directly specified for the second run, it's in the default location and is thus automatically found. As such there's no change in package structure and for all compiles the files are in the package `hello`.
3) When serializing the kept-in-the-compiler-libraries are not included, so the data we initialize from in the next run will only include that actual output.

So, overall what happens is this:
1) We compile file1, report "+file1" and save dill1 with file1 included.
2) We initialize from dill1 with file1 included, compiles file2, keep file1 around in the compiler because it's in a package, reports "+file2" and saves dill2 with file2 included (but not file1). 
3) We initialize from dill2 which only includes file2, compiles file2, and as our world no longer contains file1 we report "-file1" and saves dill3 with file2 included.

All in all the output is correct.

**Comment by jensjoha** [comment]
Oh, I'm sort of reading some of the comments like there was an example of reporting to few dependencies, but I can't seem to find the example of that. If there is such a thing please point me to it.

**Comment by michaelRichards99** [comment]
Thank you for explaining, that clears a lot of this up! I seem to have remembered incorrectly, I cannot reproduce reporting fewer dependencies. I think the only issue here was misunderstanding how the tracked sources reporting worked.
