### ISSUE TITLE
Search or Filter feature in IntelliJ problems panel

### ISSUE THREAD

**Issue by ehcpdeveloper** [dart-lang/sdk#49533]
A search on description of "dart analysis window" would be good, 
for, for example, searching specific errors or filtering them.

## Version information

- `IDEA IC-221.5921.22`
- `2.17.6`
- `IC-221.5921.22, JRE 11.0.15+10-b2043.56x64 JetBrains s.r.o., OS Mac OS X(x86_64) v12.3, screens 1920.0x1080.0, 3584.0x2240.0, 1920.0x1080.0  Retina`

**Comment by bwilkerson** [comment]
The Dart Analysis view is added by the plugin, so JetBrains has control over it. Please create an issue on https://youtrack.jetbrains.com/issues/IDEA.

**Comment by ehcpdeveloper** [comment]
Actually, this was not an issue, I came up here, through  "Analyzer Feedback" icon. Maybe wrong place, but this is caused by that icon... fyi. fixing or not fixing is up to you :)
I'm not going to write anywhere else, this is just a feedback for your convenience. 
![image_2022-07-26_231659650](https://user-images.githubusercontent.com/1267949/181113587-327108da-b72c-48fa-b6d1-386cf1cb08d2.png)
