### ISSUE TITLE
Wrap with Builder assist should insert a trailing comma

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#49541]
See: https://twitter.com/k_sokolovskyi/status/1547940961493192705

Repro:

```dart
class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const Text('hi');
  }
}
```

If `require_trailing_commas` is enabled, the "Wrap with Builder" snippet should ensure that a trailing comma is inserted.

**Comment by ksokolovskyi** [comment]
@pq Thanks a lot for this fix!
