### ISSUE TITLE
Should pkg/meta's @alwaysThrows be deprecated for Dart v3?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#49567]
My understanding is that, similar to `pkg/meta`'s `@required`, `@alwaysThrows` has no use in Dart v3:

```dart
// Dart v2 before null-safety
import 'package:meta/meta.dart';

@alwaysThrows
void a() => throw 'Always throws';
```

```dart
// Dart v2 after null-safety
Never a() => throw 'Always throws';
```

Anyone, not sure... figured I'd highlight this for others to look at.

**Comment by bwilkerson** [comment]
That's probably reasonable. The only place I can think of where the annotation can be used that `Never` can't be used is on a setter, but it seems highly unlikely that anyone's using the annotation on a setter.
