### ISSUE TITLE
LibraryElement.parts broken in analyzer 4.3.0 and newer

### ISSUE THREAD

**Issue by jmatth** [dart-lang/sdk#49566]
* Dart SDK Version: Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"
* OS: macOS
* Browser: N/A

The latest updates to `analyzer` seem to have broken `LibraryElement.parts` in at least some cases. The [`auto_route`][auto_route] project uses that field in its code generator. With version `4.3.0` or newer of `analyzer`, the `parts` field is empty even when there is a part directive in the file, which causes the generator to break. I have a separate bug open against that project at Milad-Akarie/auto_route_library#1172

I bisected the `analyzer` package and found the issue was introduced in d19e1d16b928c401e6c25b5bcb7cf44ac0e85cd5. Unfortunately that commit contains a lot of code and I'm not familiar with the `analyzer` internals, so that's when I stopped investigating and filed this issue.

[auto_route]: https://github.com/Milad-Akarie/auto_route_library
[auto_route_generator]: https://github.com/Milad-Akarie/auto_route_library/blob/0c841372071c6eaca73188a18001a20d3fed3818/auto_route_generator/lib/auto_route_generator.dart#L68-L80

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
`LibraryElement.parts` stopped including units which don't point back at the library, i.e. don't have a `part of name;` or `part of uri;` directives. A not existing file has this property.

OTOH, `LibraryElement.parts2` supports these cases. You get `List<PartElement>`, where each `PartElement` has `DirectiveUri get uri`, and there are several subtypes of `DirectiveUri`. For the valid case it is `DirectiveUriWithUnit`, but could be `DirectiveUriWithSource`, etc.

**Comment by jmatth** [comment]
Yeah, there's already an open PR to move to `parts2`. I opened this issue because I wasn't sure whether the change was intentional or a bug. Since it is intentional, I would suggest the `analyzer` version should be bumped to `5.0.0` since this:

> LibraryElement.parts stopped including units which don't point back at the library, i.e. don't have a part of name; or part of uri; directives. A not existing file has this property.

breaks backwards compatibility.

**Comment by scheglov** [comment]
I agree that this was a breaking change. But it is too late to publish it as `5.0.0`.

I ran this change over large number of clients, and it affected only one in a tiny way. So, I would recommend for an affected client to publish a new version that restricts supported `analyzer` version to versions before `4.3.0`.

**Comment by jmatth** [comment]
> But it is too late to publish it as 5.0.0.

Might not be, it's possible to retract versions within 7 days so there may be a few hours left to retract `4.3.0` and `4.3.1`. I'm guessing that's not happening though so we can probably just close this issue. Thanks for your help and responding so quickly.

In case anyone ends up here from Github issue search or googling the same problem, here's at least one way to access the URIs of part directives using `parts2`:

```dart
// CaseElement clazz = ...;
Iterable<Uri> partUris = clazz.library.parts2
    .map((e) => e.uri)
    .whereType<DirectiveUriWithRelativeUri>()
    .map((e) => e.relativeUri);
```

Or if you just need the URI as a string:

```dart
// CaseElement clazz = ...;
Iterable<String> partUriStrings = clazz.library.parts2
    .map((e) => e.uri)
    .whereType<DirectiveUriWithRelativeUriString>()
    .map((e) => e.relativeUriString);
```

See also the discussion at Milad-Akarie/auto_route_library#1165

**Comment by keertip** [comment]
closing as there is a workaround.
