### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [dart-lang/sdk#49576]
### Commit(s) to merge

*

### Target

*

### Issue Description

Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Thanks in advance.

### What is the fix

*

### Why cherry-pick

*

### Risk

high

### Issue link(s)

*

**Comment by itsjustkevin** [comment]
Please open a blank issue utilizing https://github.com/dart-lang/sdk/issues/new for feature requests. 

Closing as this is not a cherry-pick request.

**Comment by Neustradamus** [comment]
@itsjustkevin: Can you update it? "feature requests" is missing:
- https://github.com/dart-lang/sdk/issues/new/choose
