### ISSUE TITLE
New Hint: replace alwaysThrows with Never

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#49583]
The `@alwaysThrows` annotation can be replaced with a return type of `Never`.

A `@deprecated` annotation on `alwaysThrows` would report for pre-null safe code, so we should not do that. Instead, perhaps a new Hint: if a library is null safe, it should not reference `alwaysThrows`.

Also a quick fix for the new Hint.

See also https://github.com/dart-lang/sdk/issues/49567

**Comment by srawlins** [comment]
> A `@deprecated` annotation on `alwaysThrows` would report for pre-null safe code, so we should not do that. Instead, perhaps a new Hint: if a library is null safe, it should not reference `alwaysThrows`.

I'm calling that ship sailed :). We can just deprecate the annotation.

**Comment by srawlins** [comment]
@bwilkerson would this be a candidate for a data-driven fix? Replace

```dart
@alwaysThrows void foo() => throw 'x';
```

with

```dart
Never foo() => throw 'x';

**Comment by bwilkerson** [comment]
I don't believe that we currently have support for annotations, but we could add support that would make this possible.
