### ISSUE TITLE
Define standard event for navigating IDEs to view a file + line + column

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#49606]
Currently the DevTools > Inspector does a lot of extra work to navigate to select a widget.
We should instead dispatch an event with a file + line + column indicating IDEs should navigate to that location.

Flutter should dispatch that event directly rather than relying on IDEs listening for the dart:developer inspect event. DevTools should also dispatch the event to trigger code navigation in the IDE from all places where DevTools wants to trigger navigation in the IDE.

Peer issue in DevTools: https://github.com/flutter/devtools/issues/4326

**Comment by jacob314** [comment]
@CoderDake fixed this.
You can now call this tool event to navigate in IDEs
https://github.com/flutter/flutter/blob/9c72f5a7e62e63c199739267f3feeee0559caf11/packages/flutter/lib/src/widgets/widget_inspector.dart#L1518
```dart
  postEvent(
        'navigate',
        <String, Object>{
          'fileUri': location.file, // URI file path of the location.
          'line': location.line, // 1-based line number.
          'column': location.column, // 1-based column number.
          'source': 'flutter.inspector',
        },
        stream: 'ToolEvent',
      );
      ```
