### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by ah968** [dart-lang/sdk#49609]
## Version information

- `IDEA AI-212.5712.43.2112.8815526`
- `2.17.6`
- `AI-212.5712.43.2112.8815526, JRE 11.0.12+7-b1504.28-7817840x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2600.0x1462.5`

**Comment by srawlins** [comment]
Please include feedback with a feedback report.
