### ISSUE TITLE
Using postMessage to pass SharedArrayBuffer throws UnimplementedError: structured clone of other type

### ISSUE THREAD

**Issue by nullrocket** [dart-lang/sdk#49610]
Using postMessage on a Worker or MessagePort throws `UnimplementedError: structured clone of other type
`.  when passing a SharedArrayBuffer.  This is  when using dart2js to compile workers to javascript.   I believe adding it here would fix the issue, but I don't know if there is more to do than just that of course.  

https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/sdk/lib/html/html_common/conversions_dart2js.dart#L116-L117

I did work around it by manually editing the emitted js and adding the following line to the emitted code from dart2js.

```javascript
  // Opt out of structured cloning!
    if(e instanceof SharedArrayBuffer) {
      return e;
    }
    // This is the emitted js from cloneNotRequired
    if (type$.NativeByteBuffer._is(e) || type$.NativeTypedData._is(e) || type$.MessagePort._is(e))
        return e;
```

This is using **Dart SDK version: 2.19.0-61.0.dev**

Just to note: Javascript needs the original, not cloned, SharedArrayBuffer passed in the message, it also requires that it not be transferred via the transfer list in order to work properly.

**Comment by nullrocket** [comment]
This became a blocker for me so decided to learn how to contribute to the sdk and do a PR.

https://dart-review.googlesource.com/c/sdk/+/255765

Given the way tests run there isn't really an automated way to test since SharedArrayBuffer requires the page content to be served with secure headers.   Its a fairly low risk change and I've manually tested it. 

If the capability to server secure headers and https is ever added to the test harness then https://github.com/dart-lang/sdk/blob/main/tests/lib/html/postmessage_structured_test.dart[](https://github.com/dart-lang/sdk/blob/main/tests/lib/html/postmessage_structured_test.dart) would be a good home for adding some tests.

**Comment by nullrocket** [comment]
Any chance I can get some feed back on whether this might be merged?

**Comment by nullrocket** [comment]
@mit-mit @biggs0125 I am really starting to feel the pain of maintaining a fork just to compile some web workers.  It seems my PR is in limbo and I don't know how or  who to ask for a review.

**Comment by mit-mit** [comment]
Sorry about that, assigned a reviewer
