### ISSUE TITLE
Process.start and Process.run don't complete when invoked during a Flutter test

### ISSUE THREAD

**Issue by btrautmann** [dart-lang/sdk#49615]
Hi folks 👋 I'm not sure if this is the correct place to be opening this, but I believe I've narrowed it down to _not_ being a Flutter issue, so hopefully this is alright.

I'm running into an issue where `Process.start` and `Process.run` complete as expected when invoked during a pure dart test, but as soon as they're invoked within a `Widget` test (via `testWidgets`) they hang. I've been unable to debug them because they're `external` functions and I'm not super familiar with debugging the implementations in those cases.

Here's a reproducing snippet though:

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  Future<String> runProcess() async {
    final process = await Process.start(
      'echo',
      ['hello'],
    );
    final stream = process.stdout.asBroadcastStream();

    final token = await stream.firstWhere(
      (element) => utf8.decode(element).contains('hello'),
    );

    return utf8.decode(token);
  }

  group('group', () {
    test('test', () async {
      final output = await runProcess();

      expect(output, contains('hello'));
    });
  });
}
```

This works and correctly prints:
```console
✓ group test
```

But when you make this change:
```diff
-test('test', () async {
+testWidgets('test', (tester) async {
```
The process never completes and the test never finishes. This made me think it was the `testWidgets` function was the issue, but I looked at that code and it hangs when it awaits the `callback` parameter, which is the code that is running the `Process`, so it seems to point to it being an issue with `Process`.

Please let me know if I can provide any further information to help debug this.

**Comment by mraleph** [comment]
I'd make an educated guess that this is caused by `FakeAsync` (https://github.com/flutter/flutter/issues/5728). In general if you have a real asynchronous stuff happening in a `testWidgets` you need to run it using `runAsync` (https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html) otherwise the test will just hang.

Could you try doing

```dart
      final output = await tester.runAsync(runProcess);
```

and see if it helps.

**Comment by btrautmann** [comment]
Amazing, that was the answer. Thank you @mraleph! I'll close this.
