### ISSUE TITLE
Avoid false positives applying Google3 specific functionality to non-google3 specific bazel workspaces

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#49629]
Related issue: https://github.com/dart-lang/sdk/issues/49544
The cherry pick was fine to unblock but I think the right solution to this is to stop treating non-g3 BAZEL workspaces as BAZEL workspaces as we don't really support that case anyway.
To detect g3 bazel workspaces we should check for the magic
dart/config/ide/flutter.json
file like the Flutter IntellIJ support does.
See
https://github.com/flutter/flutter-intellij/blob/e6bb872cca41d5bcdaebc073c6c6882f3fc22633/flutter-idea/src/io/flutter/bazel/Workspace.java#L34
That should avoid false positives like this and keep our different tools consistent.

**Comment by jacob314** [comment]
Fyi @scheglov

**Comment by scheglov** [comment]
Start https://dart-review.googlesource.com/c/sdk/+/254343

**Comment by scheglov** [comment]
Replacing the marker file: https://dart-review.googlesource.com/c/sdk/+/254480

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/255141
