### ISSUE TITLE
Failing FFI tests in co19

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#49648]
The tests
```
co19/LibTest/ffi/Size/Size_A01_t01 RuntimeError (expected Pass)
co19/LibTest/ffi/UintPtr/UintPtr_A01_t01 RuntimeError (expected Pass)
co19/LibTest/ffi/UintPtr/UintPtr_A01_t02 RuntimeError (expected Pass)
```
are failing on configurations
```
dart2wasm-hostasserts-linux-x64-d8
dartk-strong-linux-release-ia32
dartk-strong-win-release-ia32
dartk-weak-asserts-linux-release-ia32
dartk-weak-asserts-win-release-ia32
```
/cc @dcharkes

**Comment by dcharkes** [comment]
Logs: https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-release-ia32/dartk-strong-linux-release-ia32/630/co19/LibTest/ffi/UintPtr/UintPtr_A01_t02

**Comment by dcharkes** [comment]
@sgrekhov these tests also need different expectations based on architecture size (similar to https://github.com/dart-lang/co19/pull/1389).

32 bit unsigned integers truncate a signed Dart -42 `0xFFFF FFFF FFFF FFD6` (two's complement) to unsigned `0xFFFF FFD6`  4294967254.
