### ISSUE TITLE
Missing "not a recognized lint rule" with "rule: bool" form

### ISSUE THREAD

**Issue by Erhannis** [dart-lang/sdk#49651]
**Describe the issue**
Given a nonexistent rule `rulename`:
When you run `dart analyze` with the form
```
linter:
  rules:
    - rulename
```
in analysis_options.yaml, it tells you "'rulename' is not a recognized lint rule".  When you use the form
```
linter:
  rules:
    rulename: bool
```
it does not.

**To Reproduce**
See examples above.

**Expected behavior**
Both forms of rule specification should provoke an info message for unknown rules.

**Additional context**
See discussion in dart-lang/linter#3590 .

**Comment by bwilkerson** [comment]
Moved because this check is actually performed in the `analyzer` package.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/257520
