### ISSUE TITLE
Unused private constructor doesn't trigger unused_*

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#49654]
Minimal reproduction:

```dart
void example(PublicClassPrivateConstructor? e) {
  print(e == null);
}

class PublicClassPrivateConstructor {
  PublicClassPrivateConstructor._();
}
```

I'm guessing there is an argument this is often a "hint" to prevent `extends` or `with`, which leads me to believe we need an `@interface` annotation - but it's also probably reasonable to use `// ignore: unused_constructor` for this purpose as well.

**Comment by matanlurey** [comment]
Interestingly enough, adding a factory constructor starts triggering:

```dart
void example(PublicClassPrivateConstructor? e) {
  print(e == null);
}

class PublicClassPrivateConstructor {
  factory PublicClassPrivateConstructor() {
    throw UnimplementedError();  
  }
  
  PublicClassPrivateConstructor._();
}
```

**Comment by srawlins** [comment]
Yeah it's intentional for the reasons you give.

**Comment by srawlins** [comment]
Want to change this to a request for `@interface`?

**Comment by matanlurey** [comment]
@srawlins I'm OK with you closing this as a dupe of https://github.com/dart-lang/sdk/issues/46331 in that case. Up to you.

**Comment by srawlins** [comment]
I'll keep this open as we should change the behavior soon for Dart 3.0 `interface`s.

**Comment by lrhn** [comment]
It's not just a hint, it prevents the class from having an implicit public default constructor. 
That means that having a single private constructor is a reasonable thing to do, even if nobody uses it. 
(Today `abstract interface` can do the same thing - then it doesn't matter that the class has a default constructor, if you can't call it and can't use it as a super constructor. Used to be that the private constructor was the best way to achieve that.)

**Comment by srawlins** [comment]
Alright let's call it meaningful then.

**Comment by matanlurey** [comment]
> Alright let's call it meaningful then.

I have an inverse read of the situation, now that we have `abstract interface`, an unused private constructor _is_ dead code :P.

**Comment by bwilkerson** [comment]
While I see your perspective, the code serves a purpose. There's another (and maybe better) way to accomplish the same purpose, but that doesn't negate the fact that the code can't just be removed without making other changes.

The two styles are both valid Dart, and if would be irritating to a user that preferred the constructor approach to have diagnostics that they never intended to resolve.

I could argue that the lint ought to flag such a constructor if the class is already marked as `abstract interface`. I don't know whether we do.

In addition, we could have a lint to flag cases where a class could be marked with `abstract interface`. If we did add such a lint it should have a fix.

Or we could skip the lint and implement an assist that would convert the class and remove the constructor. It isn't clear to me that anyone would discover such an assist, however.

**Comment by lrhn** [comment]
If you can guarantee that the default constructor of an `abstract interface` class is not shown in DartDoc, then I'll agree that there is a better way. (But also don't want to migrate too much code for that, and we still do allow pre-3.0 code to exist, so unless the lint can behave differently for pre-3.0 code than for post-3.0 code, it's a problem.)
