### ISSUE TITLE
dart.io Process.run() crashes app on iOS

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#49650]
See https://github.com/flutter/flutter/issues/109300

From @mraleph 

You can't launch new processes on iOS - that's just not possible, necessary syscalls are blocked by the OS itself (unless device is jailbroken).

We should probably just change the Process_Start native to throw when building for iOS.

**Comment by Ephenodrom** [comment]
Fyi: If you read the discussion in the corresponding Flutter issue @mraleph comes to the conclusion that throwing a ProcessException would be the best solution.

Blocking the build will maybe prevent some apps to not build for iOS anymore.

A multiplatform app that will activate some extra features depending on available system calls will then be usable on iOS but just without the extra features.
