### ISSUE TITLE
[analysis_server] How to get whole method as a SourceRange

### ISSUE THREAD

**Issue by KlausJokisuo** [dart-lang/sdk#49653]
Is it possible to use addDartFileEdit to replace a method. I've been trying to search how I can easily use whole method as a SourceRange, but I've been unable to find any information regarding this.

Thanks.

**Comment by bwilkerson** [comment]
That depends on what you mean by the "whole method". If you have a `MethodDeclaration` node, you can use `RangeFactory` (from the `analyzer_plugin` package) to get a `SourceRange` for everything covered by that node. The `MethodDeclaration` node covers everything from the beginning of the first documentation comment or annotation through the end of the method's body.

If you want a subset of that, for example everything except the documentation comment and annotations, then you'll need to use a method like `RangeFactory.startEnd` starting with the `node.firstTokenAfterCommentAndMetadata` and ending with the end of the method `node`.

**Comment by KlausJokisuo** [comment]
@bwilkerson Thanks for your response. The latter one is what I was looking for.
