### ISSUE TITLE
[CP] Fix of git 

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#49660]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/254923

### Target

beta

### Issue Description

* depending on git Uri's of the form `git@github.com/a/b` will crash pub.
* `dart pub global activate --source git URL` crashes if the url is on the form `git@github.com/a/b`

This is because Uri.parse throws on such uris - problem was introduced in https://github.com/dart-lang/pub/pull/3305 when we started using package:path/prettyUri to present Uri's in the output.

### What is the fix

We catch the exception from Uri.parse and just present the Uri as is.
https://github.com/dart-lang/pub/commit/8ff63a8e7e36e70ceb96819c4dd9b3594b572302

We already did a fix of this issue in: https://github.com/dart-lang/pub/commit/a949b329b1b51f5f3973a790e0a0a45897d837de but missed two instances of path.prettyUri.

### Why cherry-pick

This is a low-risk fix re-enabling users to depend on git packages via ssh.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/pub/issues/3497, https://github.com/dart-lang/pub/issues/3520

**Comment by athomas** [comment]
LGTM

**Comment by mit-mit** [comment]
SGTM

**Comment by sortie** [comment]
The linked changelist https://dart-review.googlesource.com/c/sdk/+/254921 is bad. I believe you meant https://dart-review.googlesource.com/c/sdk/+/254923 instead.

**Comment by sigurdm** [comment]
> The linked changelist https://dart-review.googlesource.com/c/sdk/+/254921 is bad. I believe you meant https://dart-review.googlesource.com/c/sdk/+/254923 instead.

Yes indeed

**Comment by sortie** [comment]
This commit has been cherry-picked in 2.18.0-271.7.beta (0283de5506a5bd7d0e63e2092bf53ec93adddbd1).
