### ISSUE TITLE
error: Handle check failed: saw sentinel expected Instance:

### ISSUE THREAD

**Issue by a1017480401** [dart-lang/sdk#49663]
My Flutter app has the following error.
I don’t know how this crash happened, so I can’t provide sample code.

Log：

../../third_party/dart/runtime/vm/object.h: 7827: error: Handle check failed: saw sentinel expected Instance:
  #00  pc 0x0000000000089cd0  /apex/com.android.runtime/lib64/bionic/libc.so (abort)
  #00  pc 0x000000000069610c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x000000000069744c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x000000000075ea0c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x0000000000403164  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000401d58  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000416ca0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000ae094c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x00000000004733b0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000ae11d8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418fe8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000419158  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418b54  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418808  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x00000000004172e0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000041a2f0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000adffc8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000adfcc8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000400150  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000ae11d8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418fe8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000419158  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418b54  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418808  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x00000000004172e0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000041a2f0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000a05958  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000041e074  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x00000000004d6278  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418fe8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000419158  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418b54  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000418808  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x00000000004172e0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000041a2f0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x00000000004164d8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000416428  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000419ad0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000419c28  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000a20a7c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000a234d0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000a1e228  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000419b30  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000419c28  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000a20a7c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000a16cfc  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000059b1e0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000043d778  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000043d598  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000043d51c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000ae6bf4  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x000000000043ca9c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x0000000000402d7c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk
  #00  pc 0x00000000006cb994  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x00000000006d80b0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x00000000006ddb10  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x00000000005b3ae0  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x000000000068d5a4  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x000000000034601c  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x00000000003495a8  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x0000000000019da8  /system/lib64/libutils.so (android::Looper::pollInner(int))
  #00  pc 0x00000000000199ac  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**))
  #00  pc 0x0000000000012c74  /system/lib64/libandroid.so (ALooper_pollOnce)
  #00  pc 0x00000000003496b4  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x0000000000347cdc  /data/app/~~0KIRlbk-m3gmiwM7jBop0w==/com.changdu.novel.reader4-qo5rHRwRXiZhy03gJQnd-w==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0x00000000000eb7a8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*))
  #00  pc 0x000000000008bc8c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread)

Flutter dotcor -v

[√] Flutter (Channel beta, 3.3.0-0.2.pre, on Microsoft Windows [版本 10.0.19044.1889], locale zh-CN)
    • Flutter version 3.3.0-0.2.pre on channel beta at D:\code\flutter\SDK\flutter_windows_3.3.0-0.2.pre-beta\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ac27ac8e6 (13 days ago), 2022-08-02 14:35:08 -0700
    • Engine revision d1e7dc18bf
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\code\android\AndroidSDK
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: D:\code\android\AS\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at D:\tools\Visual Studio\2022\Components
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\code\android\AS
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at D:\tools\IntelliJ IDEA 2022.2
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[√] Connected device (4 available)
    • V2055A (mobile)   • 343470231100DGT • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [版本 10.0.19044.1889]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 103.0.1264.71

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by a-siva** [comment]
Is it possible to give us some reproduction instructions for inducing this crash

**Comment by a1017480401** [comment]
> Is it possible to give us some reproduction instructions for inducing this crash

Sorry, this crash is from a production environment, I don't know the reason for the crash，so I can’t provide instruction

**Comment by a1017480401** [comment]
> Is it possible to give us some reproduction instructions for inducing this crash

Sorry, this crash is from a production environment, I don't know the reason for the crash，so I can’t provide instruction

**Comment by rmacnak-google** [comment]
@flutter-symbolizer-bot

**Comment by mraleph** [comment]
(the bot is only listening on Flutter repo right now)

<details>
<summary>Symbolized stack</summary>

```
#00 0000000000089cd0 /apex/com.android.runtime/lib64/bionic/libc.so (abort)
#01 000000000069610c <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    dart::Assert::Fail(char const*, ...) const
                                                                    third_party/dart/runtime/platform/assert.cc:55:3
#02 000000000069744c <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    dart::Instance::CheckedHandle(dart::Zone*, dart::ObjectPtr)
                                                                    third_party/dart/runtime/vm/object.h:7827:3
#03 000000000075ea0c <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    dart::DRT_HelperTypeCheck(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments)
                                                                    third_party/dart/runtime/vm/runtime_entry.cc:987:7
                                                                    dart::DRT_TypeCheck(dart::NativeArguments)
                                                                    third_party/dart/runtime/vm/runtime_entry.cc:985:1
#04 0000000000403164 <...>/split_config.arm64_v8a.apk 
#05 0000000000401d58 <...>/split_config.arm64_v8a.apk 
#06 0000000000416ca0 <...>/split_config.arm64_v8a.apk 
#07 0000000000ae094c <...>/split_config.arm64_v8a.apk 
#08 00000000004733b0 <...>/split_config.arm64_v8a.apk 
#09 0000000000ae11d8 <...>/split_config.arm64_v8a.apk 
#10 0000000000418fe8 <...>/split_config.arm64_v8a.apk 
#11 0000000000419158 <...>/split_config.arm64_v8a.apk 
#12 0000000000418b54 <...>/split_config.arm64_v8a.apk 
#13 0000000000418808 <...>/split_config.arm64_v8a.apk 
#14 00000000004172e0 <...>/split_config.arm64_v8a.apk 
#15 000000000041a2f0 <...>/split_config.arm64_v8a.apk 
#16 0000000000adffc8 <...>/split_config.arm64_v8a.apk 
#17 0000000000adfcc8 <...>/split_config.arm64_v8a.apk 
#18 0000000000400150 <...>/split_config.arm64_v8a.apk 
#19 0000000000ae11d8 <...>/split_config.arm64_v8a.apk 
#20 0000000000418fe8 <...>/split_config.arm64_v8a.apk 
#21 0000000000419158 <...>/split_config.arm64_v8a.apk 
#22 0000000000418b54 <...>/split_config.arm64_v8a.apk 
#23 0000000000418808 <...>/split_config.arm64_v8a.apk 
#24 00000000004172e0 <...>/split_config.arm64_v8a.apk 
#25 000000000041a2f0 <...>/split_config.arm64_v8a.apk 
#26 0000000000a05958 <...>/split_config.arm64_v8a.apk 
#27 000000000041e074 <...>/split_config.arm64_v8a.apk 
#28 00000000004d6278 <...>/split_config.arm64_v8a.apk 
#29 0000000000418fe8 <...>/split_config.arm64_v8a.apk 
#30 0000000000419158 <...>/split_config.arm64_v8a.apk 
#31 0000000000418b54 <...>/split_config.arm64_v8a.apk 
#32 0000000000418808 <...>/split_config.arm64_v8a.apk 
#33 00000000004172e0 <...>/split_config.arm64_v8a.apk 
#34 000000000041a2f0 <...>/split_config.arm64_v8a.apk 
#35 00000000004164d8 <...>/split_config.arm64_v8a.apk 
#36 0000000000416428 <...>/split_config.arm64_v8a.apk 
#37 0000000000419ad0 <...>/split_config.arm64_v8a.apk 
#38 0000000000419c28 <...>/split_config.arm64_v8a.apk 
#39 0000000000a20a7c <...>/split_config.arm64_v8a.apk 
#40 0000000000a234d0 <...>/split_config.arm64_v8a.apk 
#41 0000000000a1e228 <...>/split_config.arm64_v8a.apk 
#42 0000000000419b30 <...>/split_config.arm64_v8a.apk 
#43 0000000000419c28 <...>/split_config.arm64_v8a.apk 
#44 0000000000a20a7c <...>/split_config.arm64_v8a.apk 
#45 0000000000a16cfc <...>/split_config.arm64_v8a.apk 
#46 000000000059b1e0 <...>/split_config.arm64_v8a.apk 
#47 000000000043d778 <...>/split_config.arm64_v8a.apk 
#48 000000000043d598 <...>/split_config.arm64_v8a.apk 
#49 000000000043d51c <...>/split_config.arm64_v8a.apk 
#50 0000000000ae6bf4 <...>/split_config.arm64_v8a.apk 
#51 000000000043ca9c <...>/split_config.arm64_v8a.apk 
#52 0000000000402d7c <...>/split_config.arm64_v8a.apk 
#53 00000000006cb994 <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)
                                                                    third_party/dart/runtime/vm/dart_entry.cc:0:0
                                                                    dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
                                                                    third_party/dart/runtime/vm/dart_entry.cc:145:10
#54 00000000006d80b0 <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)
                                                                    third_party/dart/runtime/vm/isolate.cc:0:0
#55 00000000006ddb10 <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
                                                                    third_party/dart/runtime/vm/message_handler.cc:240:16
#56 00000000005b3ae0 <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    dart::MessageHandler::HandleNextMessage()
                                                                    third_party/dart/runtime/vm/message_handler.cc:301:10
                                                                    Dart_HandleMessage
                                                                    third_party/dart/runtime/vm/dart_api_impl.cc:2062:29
                                                                    tonic::DartMessageHandler::OnHandleMessage(tonic::DartState*)
                                                                    flutter/third_party/tonic/dart_message_handler.cc:113:14
                                                                    tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0::operator()() const
                                                                    flutter/third_party/tonic/dart_message_handler.cc:42:37
                                                                    decltype(std::__1::forward<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&>(fp)()) std::__1::__invoke<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&>(tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&)
                                                                    third_party/libcxx/include/type_traits:3530:1
                                                                    void std::__1::__invoke_void_return_wrapper<void>::__call<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&>(tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&)
                                                                    third_party/libcxx/include/__functional_base:348:9
                                                                    std::__1::__function::__alloc_func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()()
                                                                    third_party/libcxx/include/functional:1533:16
                                                                    std::__1::__function::__func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()()
                                                                    third_party/libcxx/include/functional:1707:12
#57 000000000068d5a4 <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    std::__1::function<void ()>::operator()() const
                                                                    third_party/libcxx/include/functional:2419:12
                                                                    flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()::operator()() const
                                                                    flutter/runtime/dart_isolate.cc:407:11
                                                                    decltype(std::__1::forward<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()&>(fp)()) std::__1::__invoke<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()&>(flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()&)
                                                                    third_party/libcxx/include/type_traits:3530:1
                                                                    void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()&>(flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()&)
                                                                    third_party/libcxx/include/__functional_base:348:9
                                                                    std::__1::__function::__alloc_func<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'(), std::__1::allocator<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()>, void ()>::operator()()
                                                                    third_party/libcxx/include/functional:1533:16
                                                                    std::__1::__function::__func<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'(), std::__1::allocator<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()>, void ()>::operator()()
                                                                    third_party/libcxx/include/functional:1707:12
#58 000000000034601c <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    std::__1::function<void ()>::operator()() const
                                                                    third_party/libcxx/include/functional:2419:12
                                                                    fml::MessageLoopImpl::FlushTasks(fml::FlushType)
                                                                    flutter/fml/message_loop_impl.cc:126:5
                                                                    fml::MessageLoopImpl::RunExpiredTasksNow()
                                                                    flutter/fml/message_loop_impl.cc:139:3
#59 00000000003495a8 <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    fml::MessageLoopAndroid::OnEventFired()
                                                                    flutter/fml/platform/android/message_loop_android.cc:92:5
                                                                    fml::MessageLoopAndroid::MessageLoopAndroid()::$_0::operator()(int, int, void*) const
                                                                    flutter/fml/platform/android/message_loop_android.cc:42:52
                                                                    fml::MessageLoopAndroid::MessageLoopAndroid()::$_0::__invoke(int, int, void*)
                                                                    flutter/fml/platform/android/message_loop_android.cc:40:40
#60 0000000000019da8 /system/lib64/libutils.so (android::Looper::pollInner(int))
#61 00000000000199ac /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**))
#62 0000000000012c74 /system/lib64/libandroid.so (ALooper_pollOnce)
#63 00000000003496b4 <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    fml::MessageLoopAndroid::Run()
                                                                    flutter/fml/platform/android/message_loop_android.cc:68:18
#64 0000000000347cdc <...>/split_config.arm64_v8a.apk!libflutter.so 
                                                                    fml::MessageLoopImpl::DoRun()
                                                                    flutter/fml/message_loop_impl.cc:94:3
                                                                    fml::MessageLoop::Run()
                                                                    flutter/fml/message_loop.cc:49:10
                                                                    fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0::operator()() const
                                                                    flutter/fml/thread.cc:85:14
                                                                    decltype(std::__1::forward<fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0>(fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0&&)
                                                                    third_party/libcxx/include/type_traits:3530:1
                                                                    void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0>&, std::__1::__tuple_indices<>)
                                                                    third_party/libcxx/include/thread:341:5
                                                                    void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0> >(void*)
                                                                    third_party/libcxx/include/thread:351:5
#65 00000000000eb7a8 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*))
#66 000000000008bc8c /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread)
```
</details>

**Comment by a1017480401** [comment]
I found that my newly created isolate reported an error when executing the code
