### ISSUE TITLE
DartObject `getField` doesn't retrieve field from parent

### ISSUE THREAD

**Issue by RicardoRB** [dart-lang/sdk#49677]
Having an annotation that extends from another abstract annotation with fields, isn't possible to get the field from the children with `_parentAnnotationTypeChecker.firstAnnotationOf(methodElement)`.

Acceptance Criteria:

**GIVEN**
```dart
abstract class Bind {
  const Bind([this.path = '']);

  /// The path to bind the property to.
  /// If not set, the entire route would be by [Controller].
  final String path;
}

class Get extends Bind {
  const Get([super.path]);
}
```

**WHEN**
city_controller.dart
```dart
@Controller('/cities')
class CityController {
  CityController(this._cityService);

  final CityService _cityService;

  @Get()
  Response getCities(Request request) {
    return Response.ok(jsonEncode(_cityService.getCities()));
  }

  @Get('/<id>')
  Response getCity(@PathParam() int id) {
    return Response.ok(_cityService.getCity(id));
  }
}
```

controller_generator.dart
```dart
const _bindType = TypeChecker.fromRuntime(Bind);
final controllerPath = controllerAnnotation.read('path').stringValue;
final bind = _bindType.firstAnnotationOf(methodElement);
final path = '$controllerPath${bind?.getField('path')?.toStringValue() ?? ''}';
```

**OUTPUT**
`['/cities','/cities']`

**EXPECTED**
`['/cities','/cities/<id>']`

**Comment by scheglov** [comment]
If you look carefully into the computed `DartObject` for `bind`, you should find there a field named `(super)`, which will include values of fields for the superclass. We have following test in the analyzer (with text dumping computed values):
```dart
  test_superFormalParameter_explicitSuper_requiredNamed() async {
    await assertNoErrorsInCode('''
class A {
  final int a;
  const A({required this.a});
}

class B extends A {
  final int b;
  const B(this.b, {required super.a}) : super();
}

const x = B(2, a: 1);
''');

    var value = findElement.topVar('x').evaluationResult.value;
    assertDartObjectText(value, r'''
B
  (super): A
    a: int 1
  b: int 2
  variable: self::@variable::x
''');
  }
```

We don't flatten fields into a single map because subclasses are allowed to declare fields with the same name, which will be different memory locations, with different values. So, it is up to the consumer to walk fields, including superclasses.

**Comment by RicardoRB** [comment]
Ok, as you described, I can do something like:
```dart
bindAnnotation?.getField('(super)')?.getField('path')?.toStringValue()
```
That isn't really intuitive, I would recommend create something like:

```dart
  DartObject? getParentField(String name) {
    return getField('(super)')?.getField(name);
  }
```

**Comment by scheglov** [comment]
Well, who said that there can be just one superclass? :-)
We would have to add also `getParentParentField()`, etc.

But yes, theoretically it could be something more generic, e.g. `getFieldWithInheritance(Strung name)`.

**Comment by RicardoRB** [comment]
I believe it may work as doing `('super')`, I didn't try it, but I believe doing `getField('(super)')` won't matter what super class is, or is there a way to specify the parent? :)
