### ISSUE TITLE
Timeouts on [pkg:js] Add changes to factory_stub_test to web_2...Remove deprecated APIs from dart:convert

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#49676]
The commits in [[pkg:js] Add changes to factory_stub_test to web_2...Remove deprecated APIs from dart:convert](https://github.com/dart-lang/sdk/compare/c34b72482e5a41c02eaf0760e41c960f6e0c46dd~...db6a10ccbf96fa6ecf3a5f0be5545d23924c5ca4) likely regressed ia32 debug speed.

We have one approved timeout on that commit range:

> dartk-win-debug-ia32
> Pass -> Timeout (expected Pass)
> ✔ standalone_2/regress31114_test
> approved 9:52 Fri Aug 12 kustermann
> Windows debug-ia32 tests have huge variance in runtime.

And multiple bots turned purple since that commit range: 2x linux-ai32 1x linux-x64-precomp
![image](https://user-images.githubusercontent.com/3601775/184825669-6bd6e67f-4ce0-46d5-a65c-96588ce07f82.png)
![image](https://user-images.githubusercontent.com/3601775/184825197-592d075f-3be2-4f90-a1b0-4afb89ba7a34.png)
https://ci.chromium.org/p/dart/g/be/console?limit=100

The VM commits in this range:

* https://dart-review.googlesource.com/c/sdk/+/253700
  * Already reverted for other reasons, but still timeouts.
* https://dart-review.googlesource.com/c/sdk/+/253840
  * No significant asserts, so shouldn't have regressed debug mode.

@whesse mentioned that those bots went from 75 minutes to over 90. It looks like it is always the same shard going into the timeout `vm nnbd tests in weak mode with asserts_shard_3`:
* https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-nnbd-linux-debug-ia32/629/overview (before timeout)
* https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-nnbd-linux-debug-ia32/630/overview
* https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-kernel-nnbd-linux-debug-ia32/636/overview

before:

```
2081 out of 2099 completed
Tests running for 75 minutes
```

after:

```
1825 out of 2099 completed
Tests running for 85 minutes
```

@whesse is there a way to see if it is specific tests that have started to take longer or whether all tests have started to take longer?
@whesse is there a way to to trigger the bot on the last commit before the timeouts started happening? To verify that it is indeed a Dart commit that caused this significant slowdown and not an infrastructure change.

Edit:

* https://dart-review.googlesource.com/c/sdk/+/255243/3 revert to before commit range, bots finish fine.
* https://dart-review.googlesource.com/c/sdk/+/255243/4 revert to end of commit range, bots time out.

**Comment by whesse** [comment]
The same shard is timing out, but when it does, some other shards are still running, and get canceled.  So it is not just that single shard that is timing out.  You can see which shards have not completed yet in the timeline view.

The bot could be triggered on the last commit before the timeouts, but I would first try running the bot as a tryjob with the revert of the suspected commit.  You could also make a CL that reverts everything back to that commit, by resetting the working directory to that commit and committing, and run that as a tryjob.

**Comment by alexmarkov** [comment]
It is possible that https://dart-review.googlesource.com/c/sdk/+/253840 slowed flow graph checker which runs in debug mode, which could have slowed compilation in debug mode. I can try to fix that.

@whesse @athomas Can we make our testing infra more resilient and fail particular tests with timeouts rather than making the bot purple without further details?

**Comment by dcharkes** [comment]
> It is possible that https://dart-review.googlesource.com/c/sdk/+/253840 slowed flow graph checker which runs in debug mode, which could have slowed compilation in debug mode. I can try to fix that.

Thanks @alexmarkov.

I have verified that the bots don't timeout before the range commits, and do after the range of commits.
Since the try bots on the CL you mention also timed out, I'm going to assume this is the commit.

Please feel free to reassign to me if it turns out your CL is not the cause.
