### ISSUE TITLE
Nonsensical type appears in error message for nullable promoted type variable

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#49692]
The following code is rejected by the analyzer (as it should be):
```dart
T f<T>(T t, bool b) {
  if (t is int) {
    var u = b ? t : null; // (1)
    return u;
  } else {
    return t;
  }
}

main() {
  num n = f<num>(1, false);
  print(n);
}
```
But the error message is surprising:
```
error - test.dart:4:12 - A value of type 'T? & int' can't be returned from the function 'f' because it has a return type of 'T'. - return_of_invalid_type
```
This is wrong because at no point in the code does the type `T? & int` exist; in fact, the type `T? & int` shouldn't even be possible, since the only things that should be possible to promote using `&` are unadorned type variables.  The type in question (which is the type of the variable `u` at (1)) ought to be `(T&int)?`.

The CFE accepts this code (which is a worse problem, since it's unsound)--see https://github.com/dart-lang/sdk/issues/49691.

**Comment by scheglov** [comment]
It looks that only the presentation is not correct?
https://dart-review.googlesource.com/c/sdk/+/255547 will fix it.
