### ISSUE TITLE
Unsound handling of nullable promoted type variable type

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#49691]
The following code is accepted by the CFE, and prints `null` when run under the VM:
```dart
T f<T>(T t, bool b) {
  if (t is int) {
    var u = b ? t : null; // (1)
    return u;
  } else {
    return t;
  }
}

main() {
  num n = f<num>(1, false);
  print(n);
}
```
This should be impossible, since `n` has static type `num`, which is not nullable.

I haven't investigated deeply, but I suspect what is happening is that when analyzing the expression `b ? t : null`, the CFE computes a static type of `(T&int)?` (which is correct, if a little weird), but then since variables aren't allowed to have types that involve promotion, it tries to demote it by dropping the `&int` part of the type; but it gets confused and winds up dropping the `?` also.  As a result, the variable `u` winds up with the static type `T` (which is unsound; it should be `T?`).

The analyzer rejects this code, as it should, however, the error message it emits hints at the fact that all is not well there either--see https://github.com/dart-lang/sdk/issues/49692.

**Comment by chloestefantsova** [comment]
That is a very interesting corner case of the `UP` algorithm. The Analyzer and the CFE give different answers for the input `UP(T & int, Null)`.  The algorithm [instructs](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#upper-bounds) to return `S?` for inputs of the form `UP(S, Null)`, which leaves the implementations to deal with the type `(T & int)?`.

As I understand it, the type `(T & int)?` is a normal type for the Analyzer. At least, it shows that type in the error message.

```
Analyzing asdf.dart...

  error - asdf.dart:4:12 - A value of type '(T & int)?' can't be returned from the function 'f' because it has a return type of 'T'. - return_of_invalid_type

1 issue found.
```

The CFE was never prepared to handle types like `(T & int)?`, which results in the soundness issue discussed here.

The question is, should types like `(T & int)?` be allowed by the type system at all? Maybe the `UP` algorithm should be modified to handle that situation explicitly and avoid types like `(T & int)?`.

/cc @eernstg @scheglov

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/pull/2427.
