### ISSUE TITLE
[ddc] factory constructors failing in JS interop classes

### ISSUE THREAD

**Issue by rileyporter** [dart-lang/sdk#49693]
DDC is incorrectly routing JS interop factory constructors. Instead of using the function body of the factory constructor, DDC calls `dart.global.JSInteropClassName();`. When using `@staticInterop`, it correctly erases to `JavaScriptObject`, but calls `dart.global.JSInteropClassName['factoryConstructorName|staticInteropFactoryStub']()`, which is also not correct since the factory doesn't exist on the `dart.global` object.

Small repro:
```dart
import 'package:js/js.dart';

@JS()
class Foo {
  factory Foo.fooFactory() => dynamic as Foo;
}

void main() {
  var foo = Foo.fooFactory();
}
```

Error message in DDC:
```
Uncaught TypeError: dart.global.Foo is not a function
```
And in the compiled JS:
```JavaScript
  main.main = function main$() {
    let foo = dart.global.Foo();
  };
```

The same example with dart2js will correctly route to the `fooFactory`, but this code will fail dart2js for the incorrect `as` check from `dynamic as Foo`.

**Comment by nshahan** [comment]
@srujzs I don't think there is a test for this pattern but I'm just curious if you know of one.

**Comment by nshahan** [comment]
@srujzs Your change implements this feature right?
https://dart-review.googlesource.com/c/sdk/+/270501

**Comment by srujzs** [comment]
Yup, thanks for pointing this out! This can be marked as completed.
