### ISSUE TITLE
No dead code warnings in variable initializers

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#49701]
Given the following code:

```
Never f() { throw ''; }

class C {
  static final x = [1, 2, f(), 4];
}

var x = [1, 2, f(), 4];
```

I would expect to see the `4`'s marked as dead code, but the aren't. They do get marked if you place the last line inside a top-level function.

**Comment by stereotype441** [comment]
I believe the reason there's no dead code warning is that the analyzer doesn't create an instance of the FlowAnalysis class when evaluating top level initializers.  In retrospect, that was a mistake--it totally should (and it would improve null safety; there's a bunch of analyzer code that currently has to check whether flow analysis is null; that would go away).
