### ISSUE TITLE
Have dartdev launch the Resident Frontend Server as an AOT executable to increase server startup times

### ISSUE THREAD

**Issue by michaelRichards99** [dart-lang/sdk#49700]
`dart run --resident` [currently](https://github.com/dart-lang/sdk/blob/7ddee84e7868bb4696e609b197389b8f2494bfb9/pkg/dartdev/lib/src/generate_kernel.dart#L141) launches the Resident Frontend Server as a detached process using the frontend_server AOT snapshot. For some reason launching the AOT snapshot in detached mode takes 500ms while launching the snapshot as a normal process takes 50ms, leading to longer start times when `dart run --resident` needs to start the server. 

Switching the frontend_server from an AOT snapshot to an AOT executable alleviates most of these issues, resulting in compile times equal to that of pub's [precompile pipeline](https://github.com/dart-lang/pub/blob/7d30cf0bb2b1f1f03c3eb7d46509a6130a6c5468/lib/src/dart.dart#L148) when starting the compilation server is required.

**Comment by derekxu16** [comment]
`frontend_server` was being launched from an AppJIT snapshot before, not an AOT snapshot. As of https://github.com/dart-lang/sdk/commit/26021dcc25fb12d043c01f8c8581ef1836050a23, it is launched from an AOT snapshot.
