### ISSUE TITLE
[Records] Implement feature in the CFE

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49713]

**Comment by mit-mit** [comment]
I think @jensjoha is working on this

**Comment by johnniwinther** [comment]
This is a joined effort: @jensjoha is working on the parser (basic implementation is done), @chloestefantsova is adding the new AST nodes, and I'm working on the building the AST nodes from the parser events. When we have a specification, @chloestefantsova will be working on the type inference.

**Comment by itsjustkevin** [comment]
@chloestefantsova is this still a work in progress?

**Comment by chloestefantsova** [comment]
To my knowledge, this is implemented. I defer to @johnniwinther to make the call about closing the issue.

**Comment by vsmenon** [comment]
@johnniwinther - can we close?

**Comment by johnniwinther** [comment]
Soon. I have a CL out for #51940 and Paul is looking into #50912 and  #50929.

**Comment by stereotype441** [comment]
#50912 and #50929 were non-issues (they were old bugs that had since been fixed, but I had neglected to close them).  I've closed them now.
