### ISSUE TITLE
[Records] VM implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49719]

**Comment by bernaferrari** [comment]
Is fasta part of VM? 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/351125/225971218-96f644c6-4974-4663-8e71-ea99e98fd6ec.png">

**Comment by alexmarkov** [comment]
@bernaferrari VM uses fasta (more generally called common front-end, CFE), but we treat it as a separate component in the issue tracker as different people are working on the front-end and the VM. CFE has its own issue for the implementation of the records feature - https://github.com/dart-lang/sdk/issues/49713. If you experience any bugs related to records in the VM - please file issues and we will triage and route them as needed.
