### ISSUE TITLE
[Records] Dart2js implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49718]

**Comment by itsjustkevin** [comment]
@rakudrama is there any work left in this area?

**Comment by rakudrama** [comment]
@itsjustkevin Yes.

Things that should be resolved before the cut:
- There is a spec issue still in play where the language team need to reach consensus: https://github.com/dart-lang/language/issues/2895. 
- There are a few tests where dart2js crashes - I think they are Patterns tests. This is what I am currently working on.

Things that are fit-and-finish and would be nice to have in the first release but can be added later if really necessary
-  @natebiggs has been implementing some optimization features that make the code quality better when things are passed or returned using records (#50701)
- I would like error messages that contain Records (e.g. ArgumentError) to be more readable.

**Comment by itsjustkevin** [comment]
Thank you for the update here @rakudrama! 

There have been a lot of trade offs made during the process of bringing Dart 3 to life.  For all items that are nice to have and not critical to the release or are cleanup items please dump them in the [milestone](https://github.com/dart-lang/sdk/milestone/110) I created so we don't lose track of them.  Thank you again!

**Comment by rakudrama** [comment]
> Things that should be resolved before the cut:
> 
> * There is a spec issue still in play where the language team need to reach consensus: [What guarantees do we have around the runtimeType of primitive types? language#2895](https://github.com/dart-lang/language/issues/2895).

Resolved and implemented except for one case we can implement later.

> * There are a few tests where dart2js crashes - I think they are Patterns tests. This is what I am currently working on.

Patterns-related and being tracked under the patterns issue (two CLs in review)

> 
> Things that are fit-and-finish and would be nice to have in the first release but can be added later if really necessary
> 
> * @natebiggs has been implementing some optimization features that make the code quality better when things are passed or returned using records ([[Records] Improve dart2js global type analysis #50701](https://github.com/dart-lang/sdk/issues/50701))

Nate landed this.

> * I would like error messages that contain Records (e.g. ArgumentError) to be more readable.

This was done.
