### ISSUE TITLE
[Records] DDC implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49717]

**Comment by nshahan** [comment]
Progress update: At parity with the VM support, five remaining test failures. Those tests are getting unexpected compile time errors. Currently blocked on CFE.

**Comment by nshahan** [comment]
Progress update: Close to parity with the VM support. Need to triage one failing test in DDC that doesn't appear for the VM.

**Comment by nshahan** [comment]
Update:
All test failures have been triaged with issues linked in the failures spreadsheet.

**Comment by vsmenon** [comment]
@annagrin @nshahan is there still open work here or can we close?

**Comment by nshahan** [comment]
No remaining work planned at this time. All failing tests have been triaged and are expected to be fixed with test updates or new compile time errors.
