### ISSUE TITLE
[Records] Syntax highlighters implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49716]
Cobbling together the list from past issues:

* [x] https://github.com/dart-lang/dart-syntax-highlight/ (@DanTup)
  * https://github.com/dart-lang/dart-syntax-highlight/pull/31
* [x] https://github.com/highlightjs/highlight.js (@srawlins)
* [x] https://github.com/codemirror/CodeMirror/ (@domesticmouse)

**Comment by srawlins** [comment]
I think there is nothing to do for highlight.js, or CodeMirror. These are not real parsers and just do a loose tokenization.

**Comment by DanTup** [comment]
TextMate grammar is the same, some tests were added in https://github.com/dart-lang/dart-syntax-highlight/pull/31.

(Closing this since it seems like there's nothing left :-) )
