### ISSUE TITLE
[Records] Analyzer implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49714]
The following is a list of the individual features that need to be considered. The features are listed roughly in dependency order.

- [x] #50087
- [x] Element model (scheglov, NA)
- [x] Type system updates (scheglov)
- [x] Summary support (scheglov)
- [x] Resolution (scheglov)
- [x] Constant evaluation (brianwilkerson)
- [x] Index and search (scheglov)

**Comment by itsjustkevin** [comment]
@srawlins what items are needed to call this feature work done?

**Comment by bwilkerson** [comment]
I updated it by copying `pkg/analyzer/doc/process/new_language_feature.md`, which might or might not be complete.

**Comment by itsjustkevin** [comment]
@bwilkerson have you found that these items cover most necessary work?  Is there anything in that list I should update?

**Comment by bwilkerson** [comment]
@scheglov can confirm, but I believe that the list above is reasonably complete and that the analyzer, aside from a couple of known bugs, is complete.

**Comment by scheglov** [comment]
Yes, I think the analyzer implementation is probably complete.

However there are still discussions about parsing ambiguous code, and corresponding parser changes, and there is a bucket of co19 tests failing because of the need to disambiguate. So, there might be something new to be uncovered with tests.

**Comment by itsjustkevin** [comment]
@bwilkerson and @scheglov thank you for providing clarity around this issue!

**Comment by srawlins** [comment]
@scheglov how about now? Did the change regarding whitespace in an annotation land? And the change to make the first value in a record, `$1`, did that land?

**Comment by scheglov** [comment]
I believe we can mark "records" done.
