### ISSUE TITLE
[Records] Core library updates

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49727]
Expected updates:

* Add `Record` class as superclass of all record types. 
* Add abstract `==` and `hashCode` on `Record` with documentation stating how record equality and hashcode is computed.
* Consider: `static bool identical(Record, Record)` on class `Record`, doing deep structure equivalence checks.

* Add documentation to `identical` saying how it works for record types.
* Add documentation to `identityHashCode` saying how it works for record types (arbitrarily).
* Add documentation to `Expando`, `WeakReference` and `Finalizer` saying that they do not work with record objects.

Add more as needed.

**Comment by lrhn** [comment]
Expected updates:

* Add `Record` class as superclass of all record types. 
* Add abstract `==` and `hashCode` on `Record` with documentation stating how record equality and hashcode is computed.
* Consider: `static bool identical(Record, Record)` on class `Record`, doing deep structure equivalence checks.

* Add documentation to `identical` saying how it works for record types.
* Add documentation to `identityHashCode` saying how it works for record types (arbitrarily).
* Add documentation to `Expando`, `WeakReference` and `Finalizer` saying that they do not work with record objects.

**Comment by lrhn** [comment]
We could now add `divmod` to `int` as effectively:
```dart
(int quotient, int remainder) divmod(int divisor) => (this ~/ divisor, this.remainder(divisor));
```
Backends can optimize this to ensure we only do one low-level `divmod` operation, like they try to do now for close-by `~/` and `.remainder` operations, but users can trust the optimization more this way.

(Could also have `divremainder` for the above, and make `divmod` use `%` and a compatible division instead.)

The usual concern would be whether it should be `num.divmod` and work on all combinations of integers and doubles, and then we'll have to add language specification rules to type `int.divmod(int)` as `(int, int)`.

**Comment by lrhn** [comment]
Another possible related addition would be an extension method on `Iterable<E>` which provides the index along with the value, `Iterable<(int, E)> get indexed;`.  Q.v. #49928.
It would make a lot of the `*Indexed` extension methods in `package:collection` unnecessary.

**Comment by vsmenon** [comment]
Is there any work left here?

**Comment by lrhn** [comment]
There is significant work left. I've started on it, but is focusing on modifiers right now.

Concrete plans:
* `Iterable.indexed` extension method
* Some kind of parallel wait on records of futures, say `await (future1, future2, future3).wait` or `await ~(future1, future2, future3)`.
* Possibly parallelizing iterables and streams too: `(iterable1, iterable2, iterable3).zip`.

**Comment by mit-mit** [comment]
I think this was completed in https://dart-review.googlesource.com/c/sdk/+/288903, @lrhn ?

**Comment by lrhn** [comment]
I don't think we ever got around to documenting `identical` and `equals` for records. I'll do that tomorrow. It's DartDoc only, so it should be uncontroversial.

**Comment by mit-mit** [comment]
Yeah, but we'll have to cherry pick it, so please file a request for that

**Comment by lrhn** [comment]
The change is cherry-pick requested. Only thing we need to decide if whether we want to do something about `dart:mirrors` too.
