### ISSUE TITLE
[Records] analysis server / IDE support work

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49726]
This is the issue tracking the work that needs to be done in the analysis server to support the `records` feature. If you decide to work on a feature, either create an issue for the feature and link to it from here, or put your name beside the feature so that we don't duplicate effort.

- [x] Call Hierarchy (scheglov, NA)
- [x] Closing Labels (brianwilkerson, NA)
- [x] Code Completion (scheglov)
- [x] Code Folding (brianwilkerson)
- [x] documentSymbol (brianwilkerson, NA)
- [x] Flutter Outline (brianwilkerson, NA)
- [x] Hovers (brianwilkerson)
- [x] Implemented Markers (scheglov, NA)
- [x] Navigation (brianwilkerson, NA)
- [x] Occurrences (brianwilkerson, NA)
- [x] Organize Imports (scheglov, NA)
- [x] Outline (brianwilkerson)
- [x] Overrides Markers (scheglov, NA)
- [x] #49959
- [x] Refactorings - legacy (scheglov)
- [x] Refactorings - self describing (brianwilkerson, NA)
- [x] Search - Find References (scheglov)
- [x] Search - Member Declarations (scheglov, NA)
- [x] Search - Member References (scheglov, NA)
- [x] Search - Top-level Declarations (scheglov, NA)
- [x] selectionRange (brianwilkerson)
- [x] Semantic Highlights (brianwilkerson)
- [x] signatureHelp (brianwilkerson)
- [x] Sort Members (scheglov, NA)
- [x] Type Hierarchy (scheglov, NA)

**Comment by bwilkerson** [comment]
While I'm sure that there are bugs that will be found, I believe that the currently known work has been completed, so I'm going to close this issue. Individual issues should be created when those bugs are found.
