### ISSUE TITLE
[Records] Angular compiler implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49722]

**Comment by grouma** [comment]
Can you provide more context?

**Comment by srawlins** [comment]
I added this to the "Dart 3 stable" milestone.

This one I think could have consequences that the Angular team may want to consider. Sorry we're just now getting back to these tickets. CC @leonsenft 

The Angular team should probably confirm that records do not blow up the compiler etc in various positions:

* if a record is used in an `@Input` or `@Output`.
* if a record type is specified as the type of an `OpaqueToken`. (I see that [function types are not allowed](go/angular-dart-null-safety#function-types), and record types are similar in certain ways to function types,
* if a record is used in a `@Component` annotation (not sure if that would be legal anywhere...

Here's the [records spec](https://github.com/dart-lang/language/blob/main/accepted/future-releases/records/records-feature-specification.md#introduction). Not sure if there is a lighter-weight text yet for non-language implementors yet. @munificent
