### ISSUE TITLE
[Records] IntelliJ implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49723]

**Comment by scheglov** [comment]
With https://dart-review.googlesource.com/c/sdk/+/258323

For code `(int, String aaa, {double bbb}) f() => (0, '', bbb: 1.2);`, IntelliJ does not apply semantic highlighting for field names in the record type annotation. It does apply `PARAMETER_REFERENCE` to `bbb: 1.2`, but does not apply if I change it to `FIELD`.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/384794/189195734-71eb8be4-06f2-4778-80cd-2562cb344f63.png">

**Comment by itsjustkevin** [comment]
@jwren can this work be done outside of the normal SDK release cycle?  If so, I would like to move this to the Dart Stable milestone and out of the beta 3 milestone.

**Comment by jwren** [comment]
This can be closed out, https://youtrack.jetbrains.com/issue/WEB-58274
