### ISSUE TITLE
[Extension type] Analysis server / IDE support work

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49741]
This is the issue tracking the work that needs to be done in the analysis server to support the views feature. If you decide to work on a feature, either create an issue for the feature and link to it from here, or put your name beside the feature so that we don't duplicate effort.

- [x] Call Hierarchy (dantup)
- [x] Closing Labels (N/A, scheglov)
- [x] Code Completion (brianwilkerson)
- [x] Code Folding (scheglov)
- [x] documentSymbol (keertip)
- [x] Flutter Outline (N/A, dantup)
- [ ] Hovers (keertip? bwilkerson?)
- [x] Implemented Markers (scheglov)
- [x] Navigation (scheglov)
- [x] Occurrences (scheglov)
- [x] Organize Imports (N/A, scheglov)
- [x] Outline (keertip)
- [x] Overrides Markers (scheglov)
- [x] Quick Assists (keertip)
- [x] Quick Fixes (keertip)
- [x] Refactorings - legacy (scheglov)
- [x] Refactorings - self describing (keertip)
- [x] Search - Find References (scheglov)
- [x] Search - Member Declarations (scheglov)
- [x] Search - Member References (scheglov)
- [x] Search - Top-level Declarations (scheglov)
- [x] selectionRange (scheglov)
- Syntax Highlighting
  - [x] Semantic Highlights (dantup)
  - [x] LSP Semantic Tokens (dantup)
  - [x] [dart-syntax-highlight](https://github.com/dart-lang/dart-syntax-highlight/) TextMate Grammar (dantup)
- [x] Signature Help (dantup)
- [x] Snippets (N/A dantup)
- [x] Sort Members (scheglov)
- [x] Type Hierarchy (scheglov)
- [x] Type Hierarchy - LSP (dantup)

**Comment by srawlins** [comment]
Still blocked on https://github.com/dart-lang/language/issues/2420

**Comment by DanTup** [comment]
@srawlins what's the status of this? I started some changes (https://github.com/dart-lang/dart-syntax-highlight/pull/41, https://dart-review.googlesource.com/c/sdk/+/286928) because I had a notification from https://github.com/dart-lang/sdk/issues/49734 and the spec is in the "Accepted" folder, but I just noticed the comment above and that #2420 is still open :-)

**Comment by eernstg** [comment]
I hadn't noticed that dart-lang/language#2420 was open and referred to 'views'. The feature is now the 'inline class' feature, the [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/inline-classes/feature-specification.md) is in `accepted` and dart-lang/language#2420 has been closed.

**Comment by eernstg** [comment]
I added a comment on the '[views]' issues that I could easily find.

**Comment by DanTup** [comment]
Yeah, that caught me out too 😄 Maybe it's worth just adding Inline-Classes (and keeping Views) avoids any confusion?

I also now see I missed the milestone change above from Dart3 -> Future so guess that somewhat answers my question too.

**Comment by srawlins** [comment]
Hey @DanTup I was out today but it looks like all your questions are answered, haha. Yeah it's accepted and there is a lot of movement, e.g. in dart_style, parser, etc. So it is "accepted" for some "future" release.

**Comment by DanTup** [comment]
> Snippets

Any opinion on whether we should add a snippet for `extension type`? We do have some snippets for basic things like class definition although we don't currently have one for `extension`. I don't personally feel like they add a lot, although perhaps they do help with the syntax if it's not something you type out by hand a lot?

**Comment by bwilkerson** [comment]
I don't have a strong opinion, although I agree that they generally feel like they don't add much. I'm fine with not having one, but don't object to having one if someone thinks we should.

**Comment by bwilkerson** [comment]
The feature has shipped, so I'm going to close this. Any features not yet implemented should have their own issues.
