### ISSUE TITLE
[Extension type] VM debugging support

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49747]

**Comment by eernstg** [comment]
Please note that this feature has been renamed: It is now the 'inline class' feature.

**Comment by a-siva** [comment]
Looks like we some work on expression evaluation is required.
Consider this example 
```
extension type V0(int id) {
  num foo() => 42;
}
extension type V1(int id) implements V0 {}
extension type V2(int id) implements V0 {}
extension type V(int id) implements V1, V2 {}
main() {
  V v = V(1);
  V1 v1 = V1(1);
  V2 v2 = V2(1);
  print(v.foo());
  print(v1.foo());
  print(v2.foo());
}
```

Inside devtools if we evaluate
`v.foo()`
we get the following error
```
evaluateInFrame: (113) Expression compilation error org-dartlang-debug:synthetic_debug_expression:1:3:
Error: The method 'foo' isn't defined for the class '_Smi'. 
 '_Smi' is from 'dart:core'.
```

**Comment by a-siva** [comment]
When we hover the cursor on `V/V1/V2 `it shows the type as `int`, maybe it needs to indicate it is an extension type `V/V1/V2 wrapping `int``

**Comment by a-siva** [comment]
//cc @derekxu16 @bkonyi

**Comment by a-siva** [comment]
@bkonyi the feature is now called extension-types and hence the title.

**Comment by bkonyi** [comment]
Oh, I didn't realized we changed the name again from 'inline class'. I'll change it back.

**Comment by a-siva** [comment]
Removing milestone 3.3 per discussion in the Dart scrum meeting this morning

**Comment by jensjoha** [comment]
With https://github.com/dart-lang/sdk/commit/f5743b9f44d401501ba5b6f59770892e1e06ed04 and https://github.com/dart-lang/sdk/commit/c959173b4c3699683ef3163f53242dc727f45b7c landed evaluation should work.

E.g. with the example code above

```
> v.foo()
42
```

Can this issue be closed?
