### ISSUE TITLE
[Extension type] Core library updates

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49740]

**Comment by shilangyu** [comment]
Where could one read more about this Views feature? Unfortunately I could not find it in the `language` repo. Is that a library-only change?

**Comment by mraleph** [comment]
@shilangyu you can check these two proposals to get the idea:

https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md

https://github.com/dart-lang/language/blob/master/working/extension_structs/overview.md

tldr is that views provide a way to define a non-reified type, which only exists as a separate entity during compilation and is erased in runtime. It's a zero-overhead to provide a wrapper (with its own helper methods) around an existing representation type.

**Comment by eernstg** [comment]
Please note that this feature has been renamed: It is now the 'inline class' feature.
