### ISSUE TITLE
[Patterns] Dart2js implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49754]

**Comment by vsmenon** [comment]
@rakudrama - is there anything still open here wrt to functionality?

**Comment by rakudrama** [comment]
There are a few failures still because the front-end generates identifiers with strange names.

**Comment by leafpetersen** [comment]
Moving this to the stable milestone, since I believe anything further will be cherry picked.  Feel free to close if we think this is done.

**Comment by rakudrama** [comment]
I think we are done.

**Comment by vsmenon** [comment]
Is there anything we need to cherry-pick?

**Comment by rakudrama** [comment]
> Is there anything we need to cherry-pick?

Not yet ;-)
The changes that were hot on the deadline made it it. The remaining failing tests are all for the usual 'production mode' reasons - tests that fail to throw just because `-O3` omits checks.

**Comment by vsmenon** [comment]
Great, thanks @rakudrama !
