### ISSUE TITLE
[Patterns] Web debugging support

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49757]

**Comment by annagrin** [comment]
Currently debugging experience for pattens is not very clean:

https://github.com/dart-lang/webdev/issues/1974

**Comment by itsjustkevin** [comment]
As https://github.com/dart-lang/webdev/issues/1974 is close, is there anything else we need to call this done @annagrin?

**Comment by vsmenon** [comment]
@elliette - anything you're planning to land here?

**Comment by elliette** [comment]
We should be all good here:

- Initial pattern support was implemented in https://github.com/dart-lang/webdev/pull/2042, included in DWDS `18.0.2`
- Follow-up polish was implemented in https://github.com/dart-lang/webdev/pull/2061, included in DWDS `19.0.0`

DWDS 19.0.0 has been rolled into Flutter: https://github.com/flutter/flutter/pull/124138
