### ISSUE TITLE
[Patterns] Syntax highlighters implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49752]
Cobbling together the list from past issues:

* [x] https://github.com/dart-lang/dart-syntax-highlight/ (@DanTup)
  * https://github.com/dart-lang/dart-syntax-highlight/pull/38
* [x] https://github.com/highlightjs/highlight.js (@srawlins)
  * issue: https://github.com/highlightjs/highlight.js/issues/3725
  * PR: https://github.com/highlightjs/highlight.js/pull/3726
* [ ] https://github.com/codemirror/CodeMirror/ (@domesticmouse)

**Comment by itsjustkevin** [comment]
Agree that this should be done before stable.  From my perspective, this is still part of the minimum viable product.  I would like to continue tracking this in beta 3, but will take a look again after we have filtered down the items in beta 3.

**Comment by vsmenon** [comment]
@domesticmouse - per checklist above - is there any work here you were planning on? And anything blocking?

**Comment by domesticmouse** [comment]
> @domesticmouse - per checklist above - is there any work here you were planning on? And anything blocking?

I believe CodeMirror is in a good place. I added the new keywords in https://github.com/codemirror/codemirror5/commit/6a705898e74e223b74e02fe59f60af83074205a0 and https://github.com/codemirror/codemirror5/commit/c17c5f0abe0147151d834e8eec9c400ec327120a

**Comment by vsmenon** [comment]
Thanks - can we close this?

**Comment by vsmenon** [comment]
I'll close.
