### ISSUE TITLE
[Patterns] DDC implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49753]

**Comment by nshahan** [comment]
Progress update: At parity with the VM support. Currently blocked on CFE implementation work.

**Comment by nshahan** [comment]
Progress update: Close to parity with the VM support. Need to triage three failing tests in DDC that don't appear for the VM.

**Comment by nshahan** [comment]
No remaining work planned at this time. All failing tests have been triaged and are expected to be fixed with test updates or new compile time errors.
