### ISSUE TITLE
[Patterns] Analysis server / IDE support work

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49759]
This is the issue tracking the work that needs to be done in the analysis server to support the patterns feature. If you decide to work on a feature, either create an issue for the feature and link to it from here, or put your name beside the feature so that we don't duplicate effort.

- [x] Call Hierarchy
  Need tests to ensure that invocations within patterns are found.
  (keertip)
- [x] Closing Labels
  (brianwilkerson, NA)
- [x] Code Completion
  - [x] Need tests to ensure that completion works within patterns.
  - [x] Need tests to ensure that variables introduced by patterns are suggested where appropriate.
  - [x] Need to propose new keywords. (brianwilkerson)
- [x] Code Folding
  Decide whether we want to fold switch expressions.
  (@pq)
- [x] documentSymbol
  (brianwilkerson, NA)
- [x] Flutter Outline
  (brianwilkerson, NA)
- [x] Hovers
  Need tests to ensure that hovers work in patterns.
  (dantup)
- [x] Implemented Markers
  (brianwilkerson, NA)
- [x] Navigation
  Need tests to ensure that navigation works in patterns.
 (keertip)
- [x] Occurrences
  Need tests to ensure that referenced within patterns are found.
  (dantup)
- [x] Organize Imports
  (brianwilkerson, NA)
- [x] Outline
  (brianwilkerson, NA)
- [x] Overrides Markers
  (brianwilkerson, NA)
- [x] Quick Assists and Fixes
  #49960
- [x] Refactorings - legacy
  (brianwilkerson, NA)
- [x] Refactorings - self describing
  (brianwilkerson, NA)
- [x] Search - Find References
  Need tests to ensure that referenced within patterns are found.
  (dantup)
- [x] Search - Member Declarations
  (brianwilkerson, NA)
- [x] Search - Member References
  (dantup)
- [x] Search - Top-level Declarations
  (brianwilkerson, NA)
- [x] selectionRange
  Needs to be extended to support pattern nodes.
  (dantup)
- [x] Semantic Highlights
  (brianwilkerson)
- [x] signatureHelp
  (brianwilkerson, NA)
- [x] Snippets
  Decide whether we want to add a snippet for switch expressions.
  (dantup)
- [x] Sort Members
  (brianwilkerson, NA)
- [x] Type Hierarchy
  (brianwilkerson, NA)

**Comment by pq** [comment]
RE: code-folding, we don't currently for standard switches so I'd say we not rush to implement it for switch expressions.  If the need arises we can revisit.

**Comment by bwilkerson** [comment]
sgtm

**Comment by keertip** [comment]
@bwilkerson , can we close this issue?

**Comment by bwilkerson** [comment]
Yes. Done.
