### ISSUE TITLE
Enable gen_snapshot to be compiled for x64 host on ARM Macs

### ISSUE THREAD

**Issue by jmagman** [dart-lang/sdk#49768]
Currently Flutter compiles `gen_snapshot_x64` on x64 Intel LUCI bots.  Apple will likely phase x64 machines out of their product line in the next few years, which will make it increasingly difficult to keep enough of these machines up to maintain builder capacity (due to inability to source new machines, security updates becoming less frequent, etc).  Enable the capability to compile x64 binaries on arm64 Macs.

cc @mraleph

**Comment by rmacnak-google** [comment]
This was added in 4f7bb16cc5cafbb4744e9b4e9cebf527bf30edcd. It is possible to build gen_snapshot and run the AOT compiler, but not to run the JIT.

**Comment by jmagman** [comment]
Nice, I missed https://github.com/flutter/flutter/issues/103386. Thanks @rmacnak-google!
