### ISSUE TITLE
Analyzer retains significants amount of memory for ASTs due to uncleared expando entries

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#49766]
The analyzer uses an `Expando` (see [package:analyzer/src/dart/constant/evaluation.dart](https://github.com/dart-lang/sdk/blob/876fb36c8275794ca591c8133d1519dd1ae36f75/pkg/analyzer/lib/src/dart/constant/evaluation.dart#L32)):
```dart
final enumConstantErrorNodes = Expando<EnumConstantDeclaration>();
```
that maps `InstanceCreationExpression` AST nodes to `EnumConstantDeclaration` (which is also an AST).

The former seems to be a small artificially generated AST node representing a copy of the initializer expression (see [package:analyzer/src/dart/element/element.dart](https://github.com/dart-lang/sdk/blob/876fb36c8275794ca591c8133d1519dd1ae36f75/pkg/analyzer/lib/src/dart/element/element.dart#L1651)) :
```dart
  /// If this element represents a constant variable, and it has an initializer,
  /// a copy of the initializer for the constant.  Otherwise `null`.
  Expression? constantInitializer;
```
the creation seems to happen in [package:analyzer/src/summary2/element_builder.dart](https://github.com/dart-lang/sdk/blob/876fb36c8275794ca591c8133d1519dd1ae36f75/pkg/analyzer/lib/src/summary2/element_builder.dart#L243):
```dart
      var initializer = astFactory.instanceCreationExpression(...);
      ...
      field.constantInitializer = initializer;
```

But the value seems to be a value of the actual parsed AST, see [package:analyzer/src/dart/constant/utilities.dart](https://github.com/dart-lang/sdk/blob/876fb36c8275794ca591c8133d1519dd1ae36f75/pkg/analyzer/lib/src/dart/constant/utilities.dart#L152)
```dart
  @override
  void visitEnumConstantDeclaration(EnumConstantDeclaration node) {
    ...
   enumConstantErrorNodes[constantInitializer] = node;
  }
```

When running the analyzer on flutter and resolving all files, it will end up consuming around 600 MB of live objects. If one makes an experiment and ignores the retention from expando key to expando value, the memory consumption will shrink a hopping (120 MB / ~ 20%).

The element model hangs on to the small constant initializer AST (which will stay alive) and since that initializer is used as key in an `Expando` it will keep the value (the normal AST node) alive. The normal AST node is probably strongly connected with all parsed AST nodes (since it has parent pointers going up to the root).

=> That keeps lots of memory alive.

/cc @bwilkerson @scheglov Could you find the right place where either the expando key can be reset to `null` or where the expando itself is replaced? I think this would cause a big difference in the RAM consumption.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/255825
