### ISSUE TITLE
When I want to combine two strings together, the second string comes and replaces the letters of the first string from the beginning

### ISSUE THREAD

**Issue by shMolaee** [dart-lang/sdk#49776]
```dart
void runCommand(String inputCommand) {
    String? commandValue = commands[command];
    if (commandValue != null ) {
      String _arguments = arguments.sublist(0, arguments.length - 1).join();
      print('start');
      print(_arguments);
      print(commandValue);
      print(commandValue + _arguments);
      print('end');
      executeCommand(commandValue + _arguments);
    }
```

![Screenshot 2022-08-21 004558](https://user-images.githubusercontent.com/52465568/185765681-d959629e-70bc-4355-a1cc-c5b095d8f8c3.png)
![Screenshot 2022-08-21 004624](https://user-images.githubusercontent.com/52465568/185765683-77c5bbe0-694b-4a75-b901-edbae54fa083.png)

**Comment by lrhn** [comment]
Are you on Windows? 
I'd check if the `commandValue` ends with a newline (not a carriage return and newline). That will put the cursor back at the beginning of the line before printing the rest of the `commandValue + _arguments` string.

Try printing `jsonEncode(commandValue)`. That should make invisible characters obvious.

**Comment by shMolaee** [comment]
Thanks for response 
jsonEncode return "php artisan serve\r"
and I solve it by commandValue.replaceAll('\r', '') @lrhn

**Comment by lrhn** [comment]
Yup, my bad. The likely culprit was a single carriage return, not a single newline.
