### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by SM-Ahad** [dart-lang/sdk#49782]
## Version information

- `IDEA AI-212.5712.43.2112.8815526`
- `2.17.6`
- `AI-212.5712.43.2112.8815526, JRE 11.0.12+7-b1504.28-7817840x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1024.0x768.0`

**Comment by a-siva** [comment]
@SM-Ahad there is not enough information here regarding the problem, if there was an actual problem could you reopen the issue with an actual error message.
