### ISSUE TITLE
Add function for creating unmodifiable typed data

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#49784]
In https://github.com/flutter/engine/pull/35468 it became apparent that having a way to create unmodifiable views directly from the Dart API would be ideal (the name `Dart_NewUnmodifiableTypedData ` was suggested).  This would allow sharing of unmodifiable views across isolates in the same group and it's also a more convenient interface.

**Comment by a-siva** [comment]
Adding a new parameter `bool unmodifiable` to the existing API functions `Dart_NewTypedData `and `Dart_NewExternalTypedData `should suffice ?

**Comment by gaaclarke** [comment]
> Adding a new parameter `bool unmodifiable` to the existing API functions `Dart_NewTypedData `and `Dart_NewExternalTypedData `should suffice ?

I wouldn't recommend it since if the API is C it would require casting a const buffer to use it.

**Comment by a-siva** [comment]
Looks like @rmacnak-google already has a CL for this https://dart-review.googlesource.com/c/sdk/+/255816
