### ISSUE TITLE
Detect erroneous multi-line strings.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#4979]
It is a (relatively) common error to forgot commas between two items of a string list:
var a = [&quot;foo&quot;,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;bar&quot;  // &lt;&equals;&equals;&equals;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;gee&quot;];

In this case &quot;bar&quot; and &quot;gee&quot; will be concatenated without any warning.
It would be nice if the editor offered some kind of warning for this.
In general this is difficult, but the following heuristics could potentially work:
- wrong number of arguments to a function call.
- in lists: if the two strings easily fit onto one line. Here, for example, the user could just as well write &quot;bargee&quot; if she wanted one string. Having concatenated strings is thus probably an error.

**Comment by srawlins** [comment]
I don't think the analyzer is going to do either of the suggestions:

1. We already warn about wrong number of arguments to a function.
2. I don't think the analyzer is going to start looking at whether the two strings fit on one line together... does it do any positional/formatting analysis like this today?

**Comment by bwilkerson** [comment]
A request for this same functionality was just added to the linter project. It appears that it is a fairly common mistake, and we ought to provide support.

**Comment by srawlins** [comment]
Ah. dart-lang/linter#225. The list literal case. I think we have to be careful in what we're fixing, to avoid generating noise warnings.

Should there just be a hint in List literals to never use "space"-concatenated String literals? I think the request in dart-lang/linter#225 is based on the idea that trailing plus signs are much more visible than trailing (or missing) commas.

**Comment by bwilkerson** [comment]
> Should there just be a hint in List literals to never use "space"-concatenated String literals?

That seems reasonable to me, although I'd make it a lint rather than a hint.

**Comment by srawlins** [comment]
This is now implemented as a lint: [no_adjacent_strings_in_list](http://dart-lang.github.io/linter/lints/no_adjacent_strings_in_list.html), and the formatter also indents such that the error is noticeable.
