### ISSUE TITLE
Using an enum in a const constructor assert

### ISSUE THREAD

**Issue by lukaszdebowski** [dart-lang/sdk#49792]
Hi! :) 

I wanted to add a compile time assert to one of the classes, I would like to achieve a compile time check similar to "if this value is null, this other value must not be null" or "if this value is this specific enum value, this other value must not be null". 

When trying to do that, I noticed I cannot use an enum in a const constructor assert. I can use a string just fine. 

Here are 2 gists to better explain the issue I'm seeing:

This works (I can enforce the value of `status` in compile time if it is a string): https://dartpad.dev/?id=24f4927c2674f1dbc03b86b4ace457e1
This throws a compile error (I cannot enforce the value of `status` since it's an enum): https://dartpad.dev/?id=91f484ab9365e85fb2a7ec7604acf31c

I would say this is a bug? Or a limitation that should be possible I think, since enums are considered compile time constants, similar to a String?

**Comment by lrhn** [comment]
You cannot use `==` with enums (https://github.com/dart-lang/language/issues/1811), but you can use `identical` (because it works for all objects and cannot call user code).

Try:
```dart
 const StateClass({
    required this.status,
    this.session,
  }) : assert(
          !(session == null && identical(status, AuthStatus.loggedIn)),
          'session has to be present if status is loggedIn',
        );
```
