### ISSUE TITLE
SplayTreeMap.from() compare, replace items if they have the same value

### ISSUE THREAD

**Issue by MatteoAntolini** [dart-lang/sdk#49806]
I was trying to sort a `Map` with a given `List` and I encounter this bug

```Dart
import 'dart:collection';

void main() {
  
  List aList = ["A", "B", "C"];
  
  Map bMap = {"C": [], "B": [], "A": []};
  
  SplayTreeMap bSorted = SplayTreeMap.from(bMap, (a, b) => aList.indexOf(a).compareTo(aList.indexOf(b)));

  print(bSorted);
  
  bMap = {"D": [], "E": [], "A": []};
  
  bSorted = SplayTreeMap.from(bMap, (a, b) => aList.indexOf(a).compareTo(aList.indexOf(b)));

  print(bSorted);
  
  bSorted = SplayTreeMap.from(bMap, (a, b) => 0);

  print(bSorted);
}
```

Results:
```
{A: [], B: [], C: []}
{D: [], A: []}
{D: []}
```

Expected results:
```
{A: [], B: [], C: []}
{D: [], E: [], A: []}
{D: [], E: [], A: []}
```

Tested on Dartpad

**Comment by lrhn** [comment]
That's the intended behavior. The `compare` function defines when two keys are equal, which is when the compare function returns `0`. The `compare` function should be a a *complete* ordering of the keys. Which means that if two objects compare equal, they are, from the map's perspective, the same object.

The `indexOf` on `aList` returns -1 for elements that are not in the list.
That means that `'D'` and `'E'` keys are equal. 
You'd get the same effect with a hash map using the same comparison:
```dart
import "dart:collection";
void main() {
  List aList = ["A", "B", "C"];
  Map bMap = {"D": [], "E": [], "A": []};
  var map = LinkedHashMap(
      equals: (a, b) => aList.indexOf(a) == aList.indexOf(b),
      hashCode: (a) => aList.indexOf(a))
    ..addAll(bMap);
  print(map); // {D: [], A:[]}
}
```

All in all, working as intended, you have provided an comparison relation which considers `D` and `E` as *equal* objects.
