### ISSUE TITLE
Poor correction message and suggested fix for non-null optional positional parameters

### ISSUE THREAD

**Issue by jeremy-deutsch** [dart-lang/sdk#49816]
SDK Version: 2.17

## Current behavior

Given the following function:
```dart
void usesOptionalParam([String str]) {}
```

The analyzer will show the following error message, attached to the `String` parameter type:
```
The parameter 'str' can't have a value of 'null' because of its type, but the implicit default value is 'null'.

Try adding either an explicit non-'null' default value or the 'required' modifier.
```

And the two available fixes are adding the `required` keyword or making the parameter type nullable, in that order.

## Expected behavior

The correction message shouldn't suggest adding the 'required' modifier (since it doesn't work in this context), and the available fixes shouldn't include adding the 'required' keyword.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/256840
