### ISSUE TITLE
`dart analyze <file>` says the file is fine, `dart <file>` fails with compile-time error

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#49811]
Tried with the current HEAD (3669086a408).

Repro:

1. git clone https://github.com/osa1/protobuf.dart -b analyzer_bug
2. cd protobuf.dart/protobuf
3. dart pub get
4. dart analyze test/coded_buffer_reader_test.dart
5. dart test/coded_buffer_reader_test.dart 

Step 4 says "No issues found!", but step 5 fails with compile-time error:

```
lib/src/protobuf/pb_list.dart:218:31: Error: The method 'deepCopy' isn't defined for the class 'GeneratedMessage'.
 - 'GeneratedMessage' is from 'package:protobuf/protobuf.dart' ('lib/protobuf.dart').
Try correcting the name to the name of an existing method, or defining a method named 'deepCopy'.
        wrappedList.add(value.deepCopy(freeze: freeze) as dynamic);
                              ^^^^^^^^
lib/src/protobuf/pb_map.dart:138:33: Error: The method 'deepCopy' isn't defined for the class 'GeneratedMessage'.
 - 'GeneratedMessage' is from 'package:protobuf/protobuf.dart' ('lib/protobuf.dart').
Try correcting the name to the name of an existing method, or defining a method named 'deepCopy'.
        wrappedMap[key] = value.deepCopy(freeze: freeze) as dynamic;
                                ^^^^^^^^
```

**Comment by osa1** [comment]
We discussed this at the office and @eernstg explained that the CFE error is valid. My understanding of the problem is:

- We have `value : E`
- We promote it with `value is GeneratedMessage`
- The resulting type is an intersection type of `E` and `GeneratedMessage`
- Intersection types are not reified
- Because the type is not reified, the extension bound `T extends GeneratedMessage` does not hold for this type
- So we can't call the extension methods

So the error is valid, and analyzer should've caught it.

**Comment by srawlins** [comment]
Still reproducible today. But there is a duplicate issue that is more active. Tracking as https://github.com/dart-lang/sdk/issues/53711.
