### ISSUE TITLE
`Dart_CObject.as_typed_data.values` should be const

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#49827]
`Dart_CObject.as_typed_data.values` is of type `uint8_t*`.  The documentation says that `kTypedData` should be copied on send so there is no reason to have a non-const value.

reference: https://github.com/flutter/engine/pull/35174#discussion_r956252808

cc @a-siva

**Comment by a-siva** [comment]
Is this what you are alluding to  https://dart-review.googlesource.com/c/sdk/+/256602

**Comment by gaaclarke** [comment]
> Is this what you are alluding to https://dart-review.googlesource.com/c/sdk/+/256602

Yep, that fixes the API issue.  I noted in that CL review but I think we can plumb out the const_casts completely.

**Comment by a-siva** [comment]
> Yep, that fixes the API issue. I noted in that CL review but I think we can plumb out the const_casts completely.

Done, PTAL.
