### ISSUE TITLE
`runtimeType` should narrow

### ISSUE THREAD

**Issue by DetachHead** [dart-lang/sdk#49832]
```dart
void foo(Object value) {
  if (value.runtimeType == int) {
    value + 1; // Error: The operator '+' isn't defined for the class 'Object'.
  }
} 
```

this would be especially useful in switch statements:
```dart
switch(value.runtimeType) {
  case int:
    value + 1; // error
    break;
  case String:
    // ...
}
```

**Comment by lrhn** [comment]
This cannot be done. Promoting based on `runtimeType` is unsound.

The `runtimeType` getter can be overridden by user code to return anything. The compiler cannot assume that just becomes `o.runtimeType == int`, then `o` must have type `int`.

Also, don't use `runtimeType`, or `Type` objects in general, for checking anything unless absolutely necessary. Do an `is` check instead:
```dart
 if (value is int) {
   value + 1;
 } else if (value is String) {
   ...
 }
```
is canonical, readable *and* it promotes.


```dart
class Fake<T> {
  Type get runtimeType => T;
  String toString() => "Not $T";
}
void main() {
  var fi = Fake<int>();
  var fn = Fake<Never>();
  if (fi.runtimeType == int) {
    print(fi); // Not int
  }
  if (fn.runtimeType == Never) {
    print(fn);  // Not Never
  }
}
```
Accepting promotion here would be deeply unsound.

**Comment by DetachHead** [comment]
> Also, don't use `runtimeType`, or `Type` objects in general, for checking anything unless absolutely necessary. Do an `is` check instead:
> 
> ```dart
>  if (value is int) {
>    value + 1;
>  } else if (value is String) {
>    ...
>  }
> ```

@lrhn yeah i avoid using it where possible, but in this case i wanted to use it with a switch statement. is there a better way to do that or should i just stick to if statements?

**Comment by lrhn** [comment]
I'd stick to `if` statements, at least until if/when we get patterns which can do type checks like an `is` check.
