### ISSUE TITLE
[analyzer] Missing error in extension method

### ISSUE THREAD

**Issue by iapicca** [dart-lang/sdk#49842]
please see this [code sample](https://dartpad.dev/?id=ef1a43907d1f2a5cb6a64f44cdec7662)
```dart
import 'dart:async';

typedef Nullary<T> = T Function();
typedef NullaryAsync<T> = Nullary<Future<T>>;
typedef NullaryFutureOr<T> = Nullary<FutureOr<T>>;

typedef Unary<T, S> = T Function(S);
typedef UnaryAsync<T, S> = Unary<Future<T>, S>;
typedef UnaryFutureOr<T, S> = Unary<FutureOr<T>, S>;

extension NullaryFutureOrToNullaryAsync<T> on NullaryFutureOr<T> {
  NullaryAsync<T> get future => call();
}

extension UnaryFutureOrToUnaryAsync<T, S> on UnaryFutureOr<T, S> {
  UnaryAsync<T, S> get future => call();
}

FutureOr<void> nullary() {}
FutureOr<void> unary(dynamic _) {}

void main() {
  print(nullary.future.runtimeType);
  print(unary.future.runtimeType);
}

```

both extensions should throw, but they do so only at runtime

`Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"`

**Comment by eernstg** [comment]
Here's a variant of the example which is running code (printing 'Null' and 'Null'):

```dart
import 'dart:async';

typedef NullaryFunction<T> = T Function();
typedef NullaryFunctionFuture<T> = NullaryFunction<Future<T>>;
typedef NullaryFunctionFutureOr<T> = NullaryFunction<FutureOr<T>>;

typedef UnaryFunction<T, S> = T Function(S);
typedef UnaryFunctionFuture<T, S> = UnaryFunction<Future<T>, S>;
typedef UnaryFunctionFutureOr<T, S> = UnaryFunction<FutureOr<T>, S>;

extension NullaryFutureOrToNullaryAsync<T> on NullaryFunctionFutureOr<T> {
  FutureOr<T> get invoke => call();
}

extension UnaryFutureOrToUnaryAsync<T, S> on UnaryFunctionFutureOr<T, S> {
  FutureOr<T> invoke(S s) => call(s);
}

FutureOr<void> nullaryFunction() {}
FutureOr<void> unaryFunction(dynamic _) {}

void main() {
  print(nullaryFunction.invoke.runtimeType);
  print(unaryFunction.invoke(1).runtimeType);
}
```

I changed a few names to emphasize that it's about the arity of functions, not about nullable or non-nullable types. I changed the invocation of the function taking one argument such that we're passing one argument (`call(s)`).

With that, it's more obvious to me what the code is doing. ;-)

Then I changed the code back to a form which is similar to the original example, by changing the extensions as follows:

```dart
extension NullaryFutureOrToNullaryAsync<T> on NullaryFunctionFutureOr<T> {
  Function get invoke => call();
}

extension UnaryFutureOrToUnaryAsync<T, S> on UnaryFunctionFutureOr<T, S> {
  Function invoke(S s) => call();
}
```

The expected compile-time errors are reported by the common front end, but the analyzer does not complain (even though we're invoking a function with type `FutureOr<T> Function(S)` with no actual arguments, and we're returning an expression of type `FutureOr<T>` )

My interpretation is that the analyzer treats `call` in an extension on a function type as if it had no signature (so we're allowed to pass arbitrary actual argument lists, and the return type is considered to be `dynamic`).

@scheglov?

**Comment by iapicca** [comment]
@eernstg 
thank you for your quick response,
I just wanted to add that `call` instead of `call()` behave as intended (yelling)
(this was actually how I stumble across this)
```diff
import 'dart:async';

typedef Nullary<T> = T Function();
typedef NullaryAsync<T> = Nullary<Future<T>>;
typedef NullaryFutureOr<T> = Nullary<FutureOr<T>>;

typedef Unary<T, S> = T Function(S);
typedef UnaryAsync<T, S> = Unary<Future<T>, S>;
typedef UnaryFutureOr<T, S> = Unary<FutureOr<T>, S>;

extension NullaryFutureOrToNullaryAsync<T> on NullaryFutureOr<T> {
+  NullaryAsync<T> get future => call;
-  NullaryAsync<T> get future => call();
}

extension UnaryFutureOrToUnaryAsync<T, S> on UnaryFutureOr<T, S> {
+  UnaryAsync<T, S> get future => call;
-  UnaryAsync<T, S> get future => call();
}

FutureOr<void> nullary() {}
FutureOr<void> unary(dynamic _) {}

void main() {
  print(nullary.future.runtimeType);
  print(unary.future.runtimeType);
}

```

**Comment by eernstg** [comment]
```dart
extension NullaryFutureOrToNullaryAsync<T> on NullaryFutureOr<T> {
   NullaryAsync<T> get future => call; // "Undefined name 'call'".
}

extension UnaryFutureOrToUnaryAsync<T, S> on UnaryFutureOr<T, S> {
   UnaryAsync<T, S> get future => call; // "Undefined name 'call'".
}
```

In this case the analyzer version in dart-pad ('Based on .. Dart SDK 2.17.6') complains that `call` is undefined, even though it should be treated as `this.call`, and that expression should have the static type which is the on-type, i.e., `FutureOr<T> Funtion()` respectively `FutureOr<T> Function(S)`.

So that would be another analyzer issue.

**Comment by scheglov** [comment]
For `call()` invocation: https://dart-review.googlesource.com/c/sdk/+/256704

**Comment by scheglov** [comment]
For `call` as simple identifier: https://dart-review.googlesource.com/c/sdk/+/256921

**Comment by iapicca** [comment]
@scheglov that was really fast <3
