### ISSUE TITLE
Some experimental flag stop reporting `deprecated_export_use` in analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#49844]
Consider the following program
```dart
import "dart:io";

main() {
  BytesBuilder builder = new BytesBuilder();
  print(builder);
}
```
If to run `dart analyze` the the following output is produced
```
dart analyze test.dart                      
Analyzing test.dart... 
info • test.dart:20:3 • The ability to import 'BytesBuilder' indirectly has been deprecated. Try importing 'BytesBuilder' directly. • deprecated_export_use
info • test.dart:20:30 • The ability to import 'BytesBuilder' indirectly has been deprecated. Try importing 'BytesBuilder' directly. • deprecated_export_use
```

Now run it with `records` or `inference-update-2` experimental flags
```
dart analyze --enable-experiment=records,inference-update-2 test.dart 
Analyzing test.dart...
No issues found!
```

Why use of these experimental flags turns off `deprecated_export_use` hint? Is it an intentional change? I tried also an old experimental flag `non-nullable`. With this flag the hint is shown

`Dart SDK version: 2.19.0-131.0.dev (dev) (Tue Aug 23 17:21:34 2022 -0700) on "windows_x64" `

**Comment by bwilkerson** [comment]
Is this impacting your ability to write tests for the `records` feature?

**Comment by sgrekhov** [comment]
No. Just noticed this issue

**Comment by bwilkerson** [comment]
This appears to be a fairly recent breakage, which isn't surprising. I was not able to reproduce it using an SDK built sometime last week, but am seeing it using a build from this morning.

@scheglov In case this rings any bells.

**Comment by scheglov** [comment]
We should report the hint regardless of experiments enabled. I can reproduce the issue, in a sense, when I analyze (not using `dart analyze`, but with in-memory cache analysis), I don't get the hint. So, when it reported the hint, it must have come from the file system cache.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/256701
