### ISSUE TITLE
nuchbenja654@gmail.com nuchbenja654@nuchanns.com
nuchbenja6543@gmail.com

### ISSUE THREAD

**Issue by Nuchanncat** [dart-lang/sdk#49840]
เราขอแนะนำให้คุณลองติดตั้งแอพนี้

https://play.google.com/store/apps/details?id=com.arumcomm.systeminfo

**Comment by vsmenon** [comment]
Not clear if this was filed as intended?  Please feel free to open a new issue following one of the formats here: https://github.com/dart-lang/sdk/issues/new/choose
