### ISSUE TITLE
Tracking: Flutter null safety package support for sound null safety and lines of legacy code

### ISSUE THREAD

**Issue by nuritzi** [dart-lang/sdk#49850]
As we continue to work towards Dart null safety, we need to measure how we're doing on the Flutter side. To do this, we need to gather a few key metrics.

*  **Goal 1**: Track the number of lines of code in the flutter/flutter repo that aren't soundly null safe (@dart=x markers where x <2.12).
* **Goal 2:** Track progress on % of packages under the flutter github org which are soundly null safe (meaning a) lower SDK >= 2.12, and b) no @Dart=x markers where x <2.12)

**Comment by nuritzi** [comment]
Tracking on flutter in issue: https://github.com/flutter/flutter/issues/110468

**Comment by parlough** [comment]
Closing as done since https://github.com/flutter/flutter/issues/110016 and https://github.com/flutter/flutter/issues/110020 were both resolved, with Flutter now running with and only supporting sound null safety.
