### ISSUE TITLE
Front end and analyzer allow `continue` to meaningless targets

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#49852]
The spec says:

> Let *s<sub>c</sub>* be a **continue** statement. If *s<sub>c</sub>* is of the form **continue** *L*;, then it is a compile-time error if *s<sub>c</sub>* is not enclosed in either an **await for** (18.6.3), **do** (18.8), **for** (18.6), or **while** (18.7) statement labeled with *L*, or in a **switch** statement with a case clause labeled with *L*, within the innermost function in which **s<sub>c</sub>* occurs.

However, both the front end and analyzer seem to allow `continue` to target any arbitrary labeled statement enclosing the `continue` statement, provided that there is also a loop or switch statement enclosing the `continue` (the label is not required to be associated with the enclosing loop or switch statement).  For example, this code is accepted by both the front end and analyzer:

```dart
bool f() => true;
main() {
  switch (0) {
    default:
      print('before labeled block');
      L: {
        if (f()) {
          print('before continue');
          continue L;
        }
        print('after continue');
      }
      print('after labeled block');
  }
}
```

In practice, the bogus `continue L;` appears to behave like `break L;`.  E.g. when the example above is run under the VM, it prints:
```
before labeled block
before continue
after labeled block
```

However, flow analysis treats the bogus `continue L;` as if it branches to nowhere (similar to a `throw` statement).  In principle, this can lead to unsoundness.  For example, this code is accepted by both the front end and the analyzer:

```dart
bool f() => true;
main() {
  int i;
  switch (0) {
    default:
      L: {
        if (f()) {
          continue L;
        }
        i = 1;
      }
  }
  print(i);
}
```

But when run it prints `null`, which should be impossible.

Note that since this affects both the front end and the analyzer, fixing it would technically be a breaking change, so we should probably fix it in both the front end and the analyzer at the same time, and we should roll out the fix using the [breaking change process](https://github.com/dart-lang/sdk/blob/main/docs/process/breaking-changes.md).

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/277481

For the CFE and analyzer.

I am not sure who should start the breaking change process if this is accepted.
