### ISSUE TITLE
Failures on Fix bug in Completer.complete.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#49860]
There are new test failures on [Fix bug in Completer.complete.](https://github.com/dart-lang/sdk/commit/3688a4723c3ea3c211003fbc899571d6ea4c8648).

The tests
```
pkg/vm_snapshot_analysis/test/instruction_sizes_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

**Comment by a-siva** [comment]
The test analysis/test/instruction_sizes_test  had some issues which were fixed in 
https://dart-review.googlesource.com/c/sdk/+/266820
https://dart-review.googlesource.com/c/sdk/+/267244
