### ISSUE TITLE
Cannot trigger callback on listening for the sigint termination signal on Linux

### ISSUE THREAD

**Issue by CicadaCinema** [dart-lang/sdk#49861]
When running the below code with `dart bin/child.dart`, I cannot get the line with `print('Child interrupted.');` to execute under any circumstances.

```dart
import 'dart:io';

void main(List<String> arguments) {
  print('Starting child');

  ProcessSignal.sigint.watch().listen((event) {
    print('Child interrupted.');
    exit(0);
  });

  // this takes a long time
  fibonacci(1000);

  print('Finished child');
}

int fibonacci(int n) {
  return n < 2 ? n : (fibonacci(n - 1) + fibonacci(n - 2));
}
```

### Expected outcome

'Child interrupted.' printed to stdout upon pressing CTRL+C or after using `kill -s sigint`

### Actual outcome

Nothing happens upon pressing CTRL+C or using `kill -s sigint`:

```
jazz@localhost|small-test|$ dart bin/child.dart 
Starting child
^C^C^C
```

Note that I know I have the right PID because if I use another termination signal, like sigterm with `kill -s sigterm`, the process is successfully terminated:

```
jazz@localhost|small-test|$ dart bin/child.dart 
Starting child
^C^C^CTerminated
```

### Version information
```
jazz@localhost|small-test|$ uname -a
Linux localhost.localdomain 5.19.4-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 25 17:42:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
jazz@localhost|small-test|$ dart --version
Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "linux_x64"
```

**Comment by CicadaCinema** [comment]
possibly related: https://github.com/dart-lang/sdk/issues/48439 (this is on Windows though)

**Comment by mraleph** [comment]
One Dart code can't interrupt the other synchronously running Dart code, so this is working as expected. The signal event simply can't be delivered to the listener, unless synchronous code yields.

As an option you can run your listener in a separate isolate:

```dart
import 'dart:io';
import 'dart:isolate';
import 'dart:async';

void main(List<String> arguments) async {
  // Spawn an isolate which will listen to SIGINT and exit the process.
  final isolate = await Isolate.spawn((message) {
    ProcessSignal.sigint.watch().listen((event) {
      print('Child interrupted.');
      exit(0);
    });
  }, null);

  print('Starting child');
  fibonacci(1000);
  print('Finished child');
}

int fibonacci(int n) {
  return n < 2 ? n : (fibonacci(n - 1) + fibonacci(n - 2));
}
```

I am not sure there is much we can do here, unless we decide to violate "Dart code can't interrupt other synchronous Dart code" constraint. (/cc @lrhn @leafpetersen)

**Comment by lrhn** [comment]
Breaking the single-threaded execution model would be a break, and very breaking, change. No plans to do that.
