### ISSUE TITLE
Is `NativeFinalizer` running concurrently with Dart code?

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#49865]
Regular `Finalizer`s run in the same `Isolate` as the object they finalize, so obviously no other Dart code can run in that `Isolate`.

The docs for [`NativeFinalizer`](https://api.dart.dev/stable/2.17.7/dart-ffi/NativeFinalizer-class.html) say:

> Callbacks will happen as early as possible, when the object becomes inaccessible to the program, and may happen at any moment during execution of the program.

and

> The callback might be invoked on an arbitrary thread and not necessary on the same thread that created `NativeFinalizer`.

Does this mean that the `Isolate` which contains a `NativeFinalizer` can run concurrently with the native callback of the `NativeFinalizer`?

The question is coming up because of a native API that is not thread safe, which is being called from a Dart `Isolate` and from a `NativeFinalizer`'s callback to clean up resources.

**Comment by mraleph** [comment]
> Does this mean that the `Isolate` which contains a `NativeFinalizer` can run concurrently with the native callback of the `NativeFinalizer`?

Native finalizers are invoked from GC as soon as marking is complete. No Dart code will be running at this point within the isolate group (all threads are at safepoint), though some native code (e.g. native code invoked through FFI) might be running. If your finalizer is not thread safe you need to put some locking in place to prevent issues. 

Hope this explains it.

**Comment by blaugold** [comment]
Thanks for the explanation @mraleph! That's very helpful.
