### ISSUE TITLE
DateTime.now().millisecondsSinceEpoch return an incorrent timestamp, It is not the same as android/iOS gets

### ISSUE THREAD

**Issue by lhzmrl** [dart-lang/sdk#49874]
It happens by accident in a production environment.
the code just like this:
```dart
int timestamp = DateTime.now().millisecondsSinceEpoch;
```
Our backend checks the timestamp in the request, which should not be too far from the actual time,but sometimes the timestamp is a few minutes earlier, sometimes it's a few minutes later.But there is no problem with the timestamp obtained by Android/iOS.

Our environment like this:
```yaml
environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=2.2.0"
```
Is there any reported issues like this?Can you give me some suggestions?

**Comment by julemand101** [comment]
Are you sure the time are synchronized on both clients and servers? Not sure I am reading your question correctly but it sounds like you are wondering why the server and client might report different time stamps?

**Comment by lhzmrl** [comment]
> Are you sure the time are synchronized on both clients and servers? Not sure I am reading your question correctly but it sounds like you are wondering why the server and client might report different time stamps?

Users have reported that they have time synchronization turned on and that the timestamps of requests made via Android/iOS are correct,so I think the user phone time is correct.
I don't know how Dart VM gets the time. Is it possible that this time is inconsistent with the user's system time?

**Comment by julemand101** [comment]
The Dart VM gets the time from the device it is running on. So if the Dart VM are running on a server, it gets the time from this specific server. So it is important to enable time synchronization on your servers.

If you are running Linux you should be able to check using `timedatectl status` and see the following:
```
...
System clock synchronized: yes
...
```

**Comment by lhzmrl** [comment]
Sorry, I didn't describe clearly enough.
We are writing a Flutter application, we do not use Dart as the server.
Just to verify the timeliness of the network request, we carry a timestamp in the request, and the server will check it. The server is not using the dart language or the dart VM.
So, you think the time dart gets must match the time on the device, right?

**Comment by julemand101** [comment]
The time you are getting in Flutter are the time which the operating system reports back on the device where you app are running.

If your server checks the time in the requests, it is important that your server are also time synchronized.

**Comment by lhzmrl** [comment]
We make sure the server time is correct.
Is there a way to modify the dart virtual machine time? We want to rule out if there is a third-party library that modifies the time.

**Comment by julemand101** [comment]
As far as I know there is no way to do that. But this is rarely the first time where software developers are getting into time synchronization issues between server and clients. Clients are just in general terrible at making sure the time synchronization are running constantly and without any issues.

A good example on this is the amount of issues people have with two-factor authentication codes generated based on the time on the device.

Yes, you might have enabled the time synchronization on your device but it is nowhere a guarantee that it is actually is functional. Also, devices might have different understanding on how precise time needs to be and delay the synchronization.

**Comment by lhzmrl** [comment]
We allow the timestamp in the request to be less two minutes before or later than the server time, and normal situations are sufficient.But there are some user feedback requests fail, we found that it is a timestamp problem and they said they have time synchronization turned on.

What's even more strange is that when flutter request failed,the timestamp of request sent through the Android or iOS native method is right and the request is success.I can't think of any other explanation other than the Dart VM being problematic.

We will try to add more log to position the problem.Thanks for Your Time. @julemand101

**Comment by devoncarew** [comment]
I believe this is working as intended - the Dart VM (and the Flutter runtime) will just return the time as reported by the underlying OS.
