### ISSUE TITLE
Renaming symbol to private should also change `this.field` constructor arguments to match.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#49872]
In VSCode and IntelliJ, if I have the following class:

```dart
class MyClass {
  const MyClass({
    required this.field,
  });

  final int field;
}```

and I rename the symbol `field` to be `_field`, what I get is:

```dart
class MyClass {
  const MyClass({
    required this._field, // Gives a "private_optional_parameter" error
  });

  final int _field;
}
```

Which is adding an error to my code that I need to then fix.

I was expecting it to do something like this:

```dart
class MyClass {
  const MyClass({
    required int field,
  }) : _field = field;

  final int _field;
}
```

It seems like the analyzer would have enough information to be able to perform this mutation, since it has the type before the mutation, and knows that it is a parameter to the constructor.

Dart: Dart SDK version: 2.19.0-152.0.dev (dev) (Tue Aug 30 04:23:30 2022 -0700) on "macos_arm64"
VSCode extension version: v3.46.1

**Comment by gspencergoog** [comment]
Oh, and "Encapsulate Field" should also do this.  Currently, that results in this output:

From this:
```dart
class MyClass {
  MyClass({
    required this.field,
  });

  /// The `field`.
  int field;
}
```

To this:
```dart
class MyClass {
  MyClass({
    required this._field,
  });

  /// The `field`.
  int _field;

  /// The `field`.
  int get field => _field;

  /// The `field`.
  set field(int field) {
    _field = field;
  }
}
```

and I expected this:

```dart
class MyClass {
  MyClass({
    required int field,
  }) : _field = field;

  /// Set `value` field.
  int get field => _field;
  int _field;
  set field(int value) {
    _field = value;
  }
}
```

**Comment by gspencergoog** [comment]
I just noticed that's it's actually worse than just the class that you rename the field in.  Anything calling that constructor also gets itself renamed:

```dart
class MyClass {
  MyClass({
    required this.field,
  });

  /// The `field`.
  int field;
}

MyClass myClass = MyClass(field: 0);
```

is converted to:

```dart
class MyClass {
  MyClass({
    required this._field, // Gives a "private_optional_parameter" error
  });

  /// The `field`.
  int _field;
}

// Gives no error, although I think it probably should, since named
// parameters can't start with an underscore.
MyClass myClass = MyClass(_field: 0);
```

If it did the transform I suggested above, then none of the calls to the constructor would need renaming.

**Comment by bwilkerson** [comment]
Given that the current behavior produces invalid code, it's definitely a bug.

**Comment by bwilkerson** [comment]
Encapsulate field is an assist implemented by the class `EncapsulateField`. Given the following code, you can find it on the lightbulb menu when you click on the name of the field:
```
class C {
  int x = 0;
}
```

**Comment by asashour** [comment]
For the renaming part, initial CL at:

https://dart-review.googlesource.com/c/sdk/+/257102

**Comment by gspencergoog** [comment]
While you are looking at the encapsulate field code, one thing that I'd love to also have fixed is to not use the name of the field for the argument to the setter: it's confusing because it's shadowing the actual accessor.

So, instead of this:
```dart
  int get field => _field;
  set field(int field) {
    _field = field;  // The "field" on this line is the argument, but looks like the accessor.
  }
```

I'd prefer this:
```dart
  int get field => _field;
  set field(int value) {
    _field = value;
  }
```

**Comment by asashour** [comment]
Oh, it is not easy to notice the assists.

EncapsulateField in https://dart-review.googlesource.com/c/sdk/+/257200
