### ISSUE TITLE
[dart gardening] ddc-nnbd-linux-release-chrome bot is failing

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#49886]
The [ddc-nnbd-linux-release-chrome](https://ci.chromium.org/p/dart/builders/ci.sandbox/ddc-nnbd-linux-release-chrome) bot is red after:

https://dart.googlesource.com/sdk/+/883464d89d7a2e9057fc03f6ddd1cc6f07e63d6b

**Comment by annagrin** [comment]
@bwilkerson @nshahan FYI

**Comment by bwilkerson** [comment]
Thanks for pinging me. The CL in question changes some documentation (and no code) so I don't think it can have been responsible for the failure. Digging a little further, the failure message is

```
There are new unapproved failures on this build
There are unapproved failures
(dartdevk-strong-linux-release-chrome):
    language/async_star/async_star_test   (flaky -> RuntimeError, expected Pass) at 883464
```

That suggests to me that a test that was previously marked as flaky has now failed consistently enough that the build system is, as of this build, marking it as failing. That further suggests that the failure is unrelated to my CL; the CL just happened to be what triggered the Nth consecutive failure of the test.

**Comment by annagrin** [comment]
@bwilkerson thanks! Will look into that.

**Comment by annagrin** [comment]
The bot is failing due to a flaky test timing out.
