### ISSUE TITLE
A few deep questions

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#49897]
Hello,

Im a young flutter.dart dev from India,

I asked the following questions in the community, but maybe it could not attract anyone knowledgeable, so im asking here, if you dont mind,

May i ask:

1. Is it possible to pass a function to `catch`(of `try` block), like `onError`: If we have `void logError(Object o, StackTrace s) {  print(o.toString());print(s.toString());  }`, then i can `Stream.listen(onData, onError: logError,)` but not `try { functionCall();  } catch logError`, if yes, then how,

2. Is it possible to give choice in function parameters to a function, like`Future.catchError` does: `Future.catchError` accepts either `Function(Object)` or `Function(Object, StackTrace)`, but the nearest i could mimic was `void function({final void Function(Object)? withObj, final void Function(Object, StackTrace)? withObjAndST}){}`, which is completely different, as it involves making a value `null`, if yes, then how,

3. If i have a class `class c{ static const int a = 0, b = 1; }`, with only static members, then would it be wise to use `abstract` keyword, as i already know that there wont be any objects of this class, please explain to this noob,

4. Is there any plan (or maybe whisper) to add nanoseconds support to `DateTime` class, as found in kotlin(dart.old), the Java(dart.oldold), as i think dart is the new java, hence it should be complete,

thanking you...

**Comment by mit-mit** [comment]
The present issue tracker is meant for tracking problems/defects of the Dart SDK. We're unfortunately not able to answer support questions here about how to use Dart. For those I recommend a community service, like for example https://stackoverflow.com/tags/dart
