### ISSUE TITLE
[Records] diagnostic for field assignments

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#49893]
Given the following snippet, I'd expect the assignment to produce a warning (since records don't have setters):

```dart
void f() {
  var r = (x: 1, y: 2);
  r.x = null;
}
```

(fyi @kallentu since this might be a good case to have tests for.)

**Comment by scheglov** [comment]
I believe this was fixed in 5c800a62cff2d96fb5505d60224e612da844a541.

**Comment by pq** [comment]
Nice.  Confirmed.

Thanks!
