### ISSUE TITLE
Analyzer complains on nullable values even after a non-null check

### ISSUE THREAD

**Issue by d-markey** [dart-lang/sdk#49903]
Hello,

Dart Analyzer complains on the following code, where fields are declared with a nullable type but the code makes a null check before accessing them. Since these fields are also final, the null check holds and I don't see why the analyzer would complain?

Is there something I'm missing, or could the analyzer be improved? Right now in such use cases, the fields must be accessed with "!" and that makes the code look awkward.

```dart
class A {
  A({ this.b1, this.b2 });

  final B? b1;
  final B? b2;

  Iterable<B> objects() sync* {
    if (b1 != null) yield b1; // the analyzer complains here: but b1 is final and != null, so b1 is effectively a B
    if (b2 != null) yield b2; // same remark
  }

  Iterable<int> values() sync* {
    if (b1 != null) yield b1.value; // same remark
    if (b2 != null) yield b2.value; // same remark
  }

  B first() {
    if (b1 != null) return b1; // same remark
    if (b2 != null) return b2; // same remark
    return B.none;
  }

  Iterable<int> hashCodes() sync* {
    if (b1 != null) yield b1.hashCode; // no complaint here! (OK, null has a hashCode)
    if (b2 != null) yield b2.hashCode; // no complaint here! (OK, null has a hashCode)
  }
}

class B {
  const B._none() : value = -1;

  B(this.value) : assert(value != -1);

  final int value;

  static const none = B._none();
}
```

**Comment by julemand101** [comment]
I have described the problem in this Stackoverflow answer: https://stackoverflow.com/questions/65456958/dart-null-safety-doesnt-work-with-class-fields/65457221#65457221

In short, we are allowed to override final variables with a `getter` in a subclass where the getter are not guarantee to return the same object each time it is asked.

**Comment by lrhn** [comment]
Yep, what @julemand101 says. You can (so far) only promote *local* variables, not instance variables.
(Overriding in a subclass is *one* of the issues, but not the only one.)

**Comment by d-markey** [comment]
Hello, thanks for the explanation!
