### ISSUE TITLE
Using external constructors on abstract classes breaks analysis and tricks Dart into allowing null values into non-nullable values

### ISSUE THREAD

**Issue by lucavenir** [dart-lang/sdk#49912]
* Dart SDK version: 2.18.0 (stable)
* Last reproducible test: Fri Aug 26 10:22:54 2022 +0000) 

# Premises
NOTE. Before opening this issue I tried googling some documentation onto the `external` keyword and reliably found [this](https://spec.dart.dev/DartLangSpecDraft.pdf#External%20Functions). In there I read:
> An external function is connected to its body by an implementation specific
mechanism. Attempting to invoke an external function that has not been connected to its body will throw a NoSuchMethodError or some subclass thereof.
> An implementation specific compile-time error can be raised at an external
function declaration.
> Such errors are intended to indicate that every invocation of that function would
throw, e.g., because it is known that it will not be connected to a body

So, if I've understood this correctly, the `external` keyword _doesn't_ give null-related responsibilities to the developer.

In other words, the `external` keyword _lifts the developer_ from not finding the external method at some point: it **does not** give any responsibility to the developer, unlike `late`, `as` or the null check operator `!`.

Let me know if I've understood this correctly.

# The Analyzer is Missing a compile-time error

As the title states, I found out a confusing use case that might be a bug (or unintended behavior).

Let's start with the following, which is a Dart Analyzer issue:
```dart
abstract class A {
  external A.fromJson(dynamic input);

  int field;
}

class B extends A {
  B(super.input) : super.fromJson();

  B.fromJson(super.a) : super.fromJson();
}
```

Here, surprisingly, the analyzer won't complain (!), but the compiler will, _as it should_, with the following error:

> Error: Field 'field' should be initialized because its type 'int' doesn't allow null.

Here, while I was expecting an error, the actual message surprises me: the compiler isn't telling me that something is wrong with _external functions body not being given_. Here, instead, I'm being told - rightfully - that `field` _doesn't allow null values, and it should be initialized_. This might be OK, but this led me to investigate further.

Anyways, the first takeaway here is that **the static analyzer isn't complaining about this**.

You can copy and paste the above snippet into [dartpad](https://dartpad.dev/) and check it for yourself.

# Null values slipping into non-nullable fields

This made me realize something was wrong, so I tried experimenting on [this dartpad gist](https://dartpad.dev/?id=b2b84b0efcf9a0b4615920aed83b0230). Code:
```dart
import 'dart:math';

abstract class A {
  const A(this.field);

  external const A.fromJson(dynamic input);

  final int field;
}

class B extends A {
  const B(int abc) : super(abc);

  B.fromJson(dynamic dfe) : super.fromJson(dfe);
}


void main() {
  final someNum = Random().nextInt(4);
  final test = B.fromJson(someNum);
  print('Now, I am actually curious of what I get here... ${test.field}');
  print('Well, isn't this new.');
}
```

(note how the `external` can't be tested onto DartPad because of `dart2js` (I guess), so I had to copy-paste stuff onto my IDE).

Run that snippet locally and you'll obtain:
```logs
Now, I am actually curious of what I get here... null
Well, isn't this new.
```

Yes, we've obtained `null` out of a `int` variable..
Also, _I have so many questions_!

1. Why is `B` allowed to call a constructor of an `abstract class`?
2. No one is providing the `external` constructor a function body... how are allowed to call that?
3. `A` has `field`, non-nullable, integer. Yet, we managed to obtain a `null` value out of it.  This _totally_ doesn't look like sound null safe code.

# The linter behaves... weird

**EDIT. IMPORTANT. The following proved to be correct, skip this section.**
This also made me notice a weird behavior onto the linter, which suggests to implement [use_super_parameters](https://dart-lang.github.io/linter/lints/use_super_parameters.html) on:
- On `B` (line 12). This makes sense.
- On `B.fromJson`, this confuses me.

I decide to try and run a `dart fix --apply` (or just auto fix on save on your IDE). This results in the following:

```dart
class B extends A {
  const B(super.abc);

  B.fromJson(super.dfe) : super.fromJson();
}
```

... But `A` hasn't neither `abc` nor `dfe` as parameters or fields! Furthermore, the last line confuses me a lot. Where is that super parameter going?

Finally, leaving out the fact that `super.fromJson` shouldn't be callable, what's the point in calling it again?

# A final question

I encountered these problems when I was exploring a way to implement and write an abstract contract so that every class extending that _has_ to implement it.

I thought the following would enforce every subclass to have a `fromJson` constructor, or at least to enforce having one `dynamic input` parameter if implemented. But it doesn't.

```dart
abstract class SomeContract {
  const SomeContract(this.field);

  external factory SomeContract.fromJson(dynamic input);

  final int field;
}

class SomeImplementation extends SomeContract {
  const SomeImplementation(super.abc);

  factory SomeImplementation.fromJson() {
    return const SomeImplementation(1);
  }
}
```

As you can see `SomeImplementation.fromJson` is allowed to have zero parameters. FYI, That's my "starting point" of the above investigation.

**Comment by lrhn** [comment]
> * Why is `B` allowed to call a constructor of an `abstract` class?

That's a perfectly reasonable thing to do. You must do that if you subclass an abstract class.

> * No one is providing the external constructor a function body... how are allowed to call that?

More to the point: Why does the program *compile* at all?
Or run. 
It should *at the minimum* throw at runtime when calling the `external` constructor that has no implementation.

> * A has field, non-nullable, integer. Yet, we managed to obtain a `null` value out of it. This totally doesn't look like sound null safe code.

Correct. The unimplemented constructor must not run successfully, so the uninitialized object should never be created.
That is a bug.



As for `super.abc`: The names of positional super parameters are purely for documentation. They do not have to match the parameter names of the supreclass constructor. Names of positional parameters are just for the reader.

**Comment by lucavenir** [comment]
Ok. So we can agree that also the analyzer problem above is a bug. Right?

About your answers:

> That's a perfectly reasonable thing to do. You must do that if you subclass an abstract class.

Huh? This is news to me. I can't think of a practical example of that.

> More to the point: Why does the program _compile_ at all? Or run. It should _at the minimum_ throw at runtime when calling the `external` constructor that has no implementation.

Yes that's what I meant, I took it for granted, but that's actually important. That should not compile, like the first example with the analyzer. I just want to remark this.

> As for `super.abc`: The names of positional super parameters are purely for documentation. They do not have to match the parameter names of the supreclass constructor. Names of positional parameters are just for the reader.

Right! I didn't realize they were positional arguments. But I still have a doubt about this.
I'd expect the linter to correct this
```dart
  B.fromJson(dfe) : super.fromJson(dfe);
```
To this:
```dart
  B.fromJson(super.dfe);
```

As the latter is syntactic sugar for the former. Instead, the linter corrects the code with calling `super.fromJson` again. What am I missing?

**Comment by mraleph** [comment]
@alexmarkov could you check why our IL builder does not build a throwing body for an `external` constructor which is not backed by any native? `dart2js` seems to do the right thing.

**Comment by alexmarkov** [comment]
@mraleph VM doesn't throw an error because external constructor has a body in kernel AST.

It seems like an old problem, likely the same as https://github.com/dart-lang/sdk/issues/28565.

We can probably throw an error if external function is non-native regardless of its body. Trying this out in https://dart-review.googlesource.com/c/sdk/+/258281.

**Comment by mraleph** [comment]
Should we maybe file an issue that front-end must not produce `external` functions with bodies in the Kernel?

**Comment by lrhn** [comment]
Seems reasonable. A function is either abstract, external, or it has a body. Those should be mutually exclusive.

If a body is provided, somehow, the function should stop being external. If not, it's still somebody's responsibility to provide a body before the program can be considered complete.
