### ISSUE TITLE
Why map allows Object? instead of typed key.

### ISSUE THREAD

**Issue by AlexanderFarkas** [dart-lang/sdk#49911]
Seems like a bug, but it's intentional

This piece of code compiles, but itsn't sound at all.
If I'd like to refactor `providables` to `Map<String, String>,` I would need to manually check all places, where I access by index, call `containsKey` e.t.c

```dart
void main() {
  final Map<int, String> providables = {};
  print(providables["Hello, world"]);
}
```

* Dart SDK version: 2.17.6 (stable)  on "macos_arm64"

**Comment by lrhn** [comment]
The code is sound, the result of the lookup is `null`, which is a valid return value for `operator[]` of any map.
It's not convenient, as you've noticed. It's also not very easy to change.

See #9893 for the original reason that this is how it currently is.
