### ISSUE TITLE
[CP] Fix issues with type propagation inside catch-blocks

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#49923]
### Commit(s) to merge

6ad380575159ba81cb836d7c3256e507ff9fd323, f38a2804a33df89a915c97c178c3b585bb92e01d

### Target

both

### Issue Description

Compiler is confused about what a local variable accessed in a try-block can contain: e.g. it might think that `late` variable is already initialized or remove a necessary null-check from a parameter which is nullable.  

### What is the fix

Type propagation rules are updated to avoid incorrect type inference.

### Why cherry-pick

Real world users are hitting these bugs and they are hard to diagnose and work around.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/111088
https://github.com/flutter/flutter/issues/110715

**Comment by mit-mit** [comment]
Picking SGTM

**Comment by vsmenon** [comment]
lgtm

**Comment by sortie** [comment]
I've cherry-picked the two commits to 2.18.1 as c42a304ce78f37b717cc055abc503023871a7013.
