### ISSUE TITLE
When using flutter Canvas, there is no API similar to clearing Canvas. Is there any way to fix it?

### ISSUE THREAD

**Issue by z244370114** [dart-lang/sdk#49933]
## Use case

The clearRect() function can specify the x, y position and width and height of the starting point to clear the canvas；
context.clearRect(0, 0, w, h);

## Proposal

Hope to have related API

**Comment by mraleph** [comment]
Flutter framework is developed in a different repo: github.com/flutter/flutter

That being said: `clearRect` is just filling the given rectangle with `rgba(0,0,0,0)` so you can achieve the same with `drawColor`.

**Comment by z244370114** [comment]
> Flutter framework is developed in a different repo: github.com/flutter/flutter
> 
> That being said: `clearRect` is just filling the given rectangle with `rgba(0,0,0,0)` so you can achieve the same with `drawColor`.

好的我试试！
