### ISSUE TITLE
Support the "Remove this widget" assist on Builder widgets

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#49949]
Moving from https://github.com/Dart-Code/Dart-Code/issues/4155, raised by @stx.

The existing "Remove this widget" assist only handles removing widgets with `child`/`children`, but it would be useful to also be able to remove `Builder`s which have a `builder` function (there may be some restrictions on whether this is always possible, for ex. `builder: _fooBuilderMethod` is probably not).

```dart
// Builder added with "Wrap with Builder"
Builder(
  builder: (context) {
    return Text(
      '$_counter',
      style: Theme.of(context).textTheme.headlineMedium,
    );
  }
),
```

-----

Original comment from @stx:

**Describe the bug**

This might be more of a feature request, but since Remove Widget already exists and appears to randomly disappear, I'm filing it as a bug.

It's common during refactors to want to remove builders or shift them around. Removing them by hand can be a bit time consuming.

**To Reproduce**

1. Try to refactor any builder widget.
2. Remove Widget is missing from the menu.

**Expected behavior**

Remove Widget works for any widget.

**Please complete the following information:**
 - Operating System and version: macOS Ventura
 - VS Code version: 1.71
 - Dart extension version: 3.48.3
 - Dart/Flutter SDK version: 2.18.0/3.3.0

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/259590

I think that even with a method invocation, it should be allowed, e.g.

```dart
  Widget f() => const Text('');

  Widget build(BuildContext context) {
    return Container(
      child: Builder(
        builder: (context) => f(),
      ),
    );
  }
```

to

```dart
  Widget f() => const Text('');

  Widget build(BuildContext context) {
    return Container(
      child: f(),
    );
  }

**Comment by DanTup** [comment]
@asashour I was thinking of a method tear-off, like:

```
Widget f(BuildContext context) => const Text('');

  Widget build(BuildContext context) {
    return Container(
      child: Builder(
        builder: f,
      ),
    );
  }
```

Although, now I'm thinking that it could be replaced with `child: f(context)` so maybe that's also fine? 🤔

**Comment by asashour** [comment]
That's interesting.

I guess it can be replaced by only `child: f(context)`, providing that:
1.  `context` is defined in the scope
1. its type is `BuildContext`

And we can't do that in some scenarios, e.g.

```dart
Widget f(BuildContext context) => Text('');

void build() {
  Container(
    child: Builder(
      builder: f,
    ),
  );
}
```

At the moment, I don't know how to get a scoped variable from an arbitrary name (e.g. `context`), also I am not sure if that doesn't change the semantics, since we call `f` with the current `context` and not returning a `FunctionExpression` which is called by a (possibly another) `context` later.

The provided CL doesn't offer a fix for this case, because the `builderExpression` is `SimpleIdentifier`.

**Comment by asashour** [comment]
Can we have a review of the proposed CL [sdk/259590](https://dart-review.googlesource.com/c/sdk/+/259590) please?

**Comment by DanTup** [comment]
Thanks! The change looks reasonable to me, but will need a Googler to review. @bwilkerson FYI - I'm not familiar with the process by which unassigned CLs like this are picked up.

**Comment by bwilkerson** [comment]
We don't have a formal process. Normally I just notice when an issue is updated with a pointer to a CL. Sometimes I miss it, which is a poor experience for contributors, but I do the best I can.
