### ISSUE TITLE
Error on line 46, column 15: Mapping values are not allowed here. Did you miss a colon earlier?Create an issue

### ISSUE THREAD

**Issue by Chonkosaurus-rex** [dart-lang/sdk#49946]
![Capture](https://user-images.githubusercontent.com/113284711/189520322-5769c73a-bbf4-4af4-956f-c8b5b4a07eb4.PNG)
I don't know what to do please help.

**Comment by asashour** [comment]
Please add two spaces at the beginning of the previous line.

**Comment by mraleph** [comment]
Please familirise yourself with `pubspec.yaml` format (and YAML in general). All information you might need is available here: https://dart.dev/tools/pub/pubspec

@asashour has pointed out the solution
