### ISSUE TITLE
Quick Assists and Fixes for Records

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#49959]
A meta-issue to discuss and track server work on quick assists and fixes for [records](https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md).

**CorrectionProducers to Review/Test/Update**

- [x] `AddTypeAnnotation` (brianwilkerson)
- [x] `ChangeTypeAnnotation` (brianwilkerson)
- [x] `CreateLocalVariable` (brianwilkerson)
- [x] `MakeVariableNullable` (brianwilkerson)
- [x] `RemoveConst` (brianwilkerson, NA)
  - This is only triggered for `const` before a non-`const` constructor.
- [x] `RemoveUnnecessaryParentheses` (brianwilkerson, NA)
  - This is only triggered for the unnecessary_parenthesis lint, which appears to not be impacted by records.
- [x] `RemoveUnusedElement` (brianwilkerson, NA)
  - This appears to only be invoked for declarations, and because records aren't declared, I don't think it's impacted.
- [x] `ReplaceWithVar` (brianwilkerson)
- [x] `SplitVariableDeclaration` (brianwilkerson)
- [x] `UseConst` (brianwilkerson, NA)
  - This is only triggered for instance creations, so I don't think it's impacted.

**Comment by bwilkerson** [comment]
We might well have missed some cases, but all of the known cases have been handled, so I'm going to close this issue. We should open individual issues for any bugs we uncover.
