### ISSUE TITLE
Is there any way to type cast listeners in `html.EventTarget.addEventListener`

### ISSUE THREAD

**Issue by Hawmex** [dart-lang/sdk#49958]
So, I'm attempting to do something like this:

```dart
import 'dart:html' as html;

typedef StricterEventListener<T extends html.Event> = void Function(T event);

class Widget {
  final StricterEventListener<html.MouseEvent>? onClick;

  const Widget({this.onClick});
}

void main() {
  final widget = Widget(onClick: (final event) => print('clicked!'));

  html.document.body!.addEventListener('click', widget.onClick);
}
```

And I get this error:

```
The argument type 'void Function(MouseEvent)?' can't be assigned to the parameter type 'dynamic Function(Event)?'.
```

Is there any way to solve this nicely and cleanly?

**Comment by Hawmex** [comment]
Thanks, @mnordine . Yes this is a viable approach. But removing event listeners requires new fields to store subscriptions besides the event listeners themselves. When there are too many events, having two fields for each event can be frustrating.

**Comment by Hawmex** [comment]
@mnordine can't a type parameter get passed to `addEventListener` and `removeEventListener`? This wouldn't be a breaking change I assume.

```dart
void addEventListener<T extends Event>(
  String type,
  EventListener<T>? listener, [
  bool? useCapture,
]);
```

**Comment by annagrin** [comment]
[dart web gardening] @leafpetersen could you please redirect this question appropriately?

**Comment by leafpetersen** [comment]
If the question is about the web libraries, maybe @srujzs or @sigmundch are the right people here?

**Comment by sigmundch** [comment]
Unfortunately I don't believe this is something that can be expressed in the language.

Long ago there were discussions in Dart about allowing to declare a closure with a `covariant` check, similar to how you can write `covariant` when you override methods today. @leafpetersen - can confirm whether this language addition is still being considered, but I don't recall this being in any recent conversations.


> ...  But removing event listeners requires new fields to store subscriptions to cancel them later, besides the event listeners themselves

Just worth pointing out that in Dart tear-offs are not always guaranteed to be identical. This can create scenarios where a `removeEventListener` may not actually remove the actual listener. It seems in your example above that you have the right pattern: you are storing the callback as a field and ensuring that you use the same callback twice. So I only mention this just in case. As an example, this would not work well:
```dart
class A {
  method(Event e) { ... }

  ...
  foo() {
    addEventListener('click', method);
    ...
  }
  bar() {
    removeEventListener('click', method); // this tear-off is not guaranteed to be identical to the one above.
    ...
  }
```

For what it's worth, using tear-offs is OK with streams/subscriptions. In that case, the tax may depend on the pattern of your application. For instance, if many events are disposed together at once, some developers group the subscriptions together, so they don't have a field per subscription, but a field per component in their UI:
```dart
class A {
  List<Subscription> subscriptions = [];
  method1(Event e) { ... }
  method2(Event e) { ... }

  ...
  foo() {
    subscriptions.add(element.onClick.listen(method1));
    subscriptions.add(element.onDrag.listen(method2));
    ...
  }
  bar() {
    subscriptions.forEach((s) => s.cancel());
  }
```

Hope this helps!

**Comment by Hawmex** [comment]
Thank you, @sigmundch . Grouping subscriptions is indeed the solution to my problem. As it is solved for my case, this issue can be closed.

**Comment by sigmundch** [comment]
Great to hear!
