### ISSUE TITLE
How to use DEBUG_FLAG_MACRO in FLAG_LIST?

### ISSUE THREAD

**Issue by Frost819** [dart-lang/sdk#49956]
I saw this debug macro in vm/flags.h. It seems to be a debug flag to show some debug info. But I have no idea how to enable this flag. Does it have anthing to do with the experiment flags in the sdk doc and how can I enable it. Thank you.

**Comment by mraleph** [comment]
If you use CLI then you need to make a debug build of the `dart` binary and then you pass the flag through the command line. 

If you use Flutter then you need to build Flutter engine with debug VM and then pass the flag to the Dart VM where `Dart_SetVMFlags` are called.

Which flag are you interested in specifically?

**Comment by Frost819** [comment]
I'm debugging some isolate related issue. So I am focused on FLAG_trace_isolates specifically.

**Comment by mraleph** [comment]
Yeah for that you would need to build debug build of Dart VM / Flutter engine, you can't enable this flag otherwise.
