### ISSUE TITLE
Analysis Server cannot find declaration / usages in case of multiple analysis context

### ISSUE THREAD

**Issue by maRci002** [dart-lang/sdk#49951]
I'm trying to create a multi-module mono-repos project and unfortunatelly analysis server doesn't do it's job for instance cannot go to declaration or find a variable / method usages mainly inside the flutter sdk source code.

## Steps to reproduce

`flutter create flutter_app && cd flutter_app && mkdir packages && cd packages && dart create --template=package package_1`

_**note**: both `flutter create` / `dart create` commands run `pub get` implicitly_

Open `flutter_app` project in Android Studio / VSCode.

Copy this line: `VisualDensity.adaptivePlatformDensity.baseSizeAdjustment.dy;` somewhere inside `main.dart`

Now try to go to `baseSizeAdjustment` 's declaration `Ctrl` + `Click` ( _in case of Android Studio `Ctrl` + `B` this is an alternative_ ), here `baseSizeAdjustment` returns `Offset` however it's greyed out if not just press again `Ctrl` + `Click` to find `baseSizeAdjustment`'s usages.

_**note**: for instance `BoxConstraints` is also greyed out_

VSCode:

https://user-images.githubusercontent.com/8436039/189683944-a5237582-de89-425b-88ea-c8e72cee0f35.mp4

Android Studio:

https://user-images.githubusercontent.com/8436039/189684896-5dba3d88-ae76-4d5b-80a0-cdd90c10efec.mp4

Whenever I try to find `baseSizeAdjustment` usages the analysis server finds some of them but not all of them, it only finds all of them if I remove `package_1` package.

VSCode:

https://user-images.githubusercontent.com/8436039/189685983-b8fa27b4-9959-4bd7-954f-e5c98d9b1115.mp4

Android Studio:

https://user-images.githubusercontent.com/8436039/189686119-973a0eca-50dd-4d80-aea4-60afe11af146.mp4

According to `Analysis Server Diagnostics` I have two analysis context defined:
1. **flutter_app**
> Context location: C:\Users\maRci002\StudioProjects\flutter_app
> Analysis options path: C:\Users\maRci002\StudioProjects\flutter_app\analysis_options.yaml
> SDK root: 
2. **package_1**

> Context location: C:\Users\maRci002\StudioProjects\flutter_app\packages\package_1
> Analysis options path: C:\Users\maRci002\StudioProjects\flutter_app\packages\package_1\analysis_options.yaml
> SDK root: C:\flutter\bin\cache\dart-sdk

`dart --version`

> Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "windows_x64"

`flutter --version`

> Flutter 3.3.1 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 4f9d92fbbd (6 days ago) • 2022-09-06 17:54:53 -0700
> Engine • revision 3efdf03e73
> Tools • Dart 2.18.0 • DevTools 2.15.0

**Comment by scheglov** [comment]
Interesting... The first time I search, IntelliJ can find all `13` references. After this - nothing.

Even more interesting is that if I put `package_1` not into `packages`, but into `packag`, the first time still `13`, then `7`, and no references in `main.dart` anymore.

**Comment by scheglov** [comment]
It seems that the second time we use wrong analysis driver for it.
```
[SearchFindElementReferencesHandler][file: /Users/scheglov/Source/flutter/packages/flutter/lib/src/material/theme_data.dart]
[SearchFindElementReferencesHandler][element: Offset get baseSizeAdjustment]
  [element.uri: package:flutter/src/material/theme_data.dart]
  [element.path: /Users/scheglov/Source/flutter/packages/flutter/lib/src/material/theme_data.dart]

[SearchFindElementReferencesHandler][file: /Users/scheglov/Source/flutter/packages/flutter/lib/src/material/theme_data.dart]
[SearchFindElementReferencesHandler][element: dynamic get baseSizeAdjustment]
  [element.uri: file:///Users/scheglov/Source/flutter/packages/flutter/lib/src/material/theme_data.dart]
  [element.path: /Users/scheglov/Source/flutter/packages/flutter/lib/src/material/theme_data.dart]
```

**Comment by scheglov** [comment]
OK, I see some more.

Somehow `/Users/scheglov/Source/flutter/packages/flutter/lib/src/material/theme_data.dart` is asked from `package_1` analysis driver, so it becomes a "known" file. But because `package_1` does not depend on `package:flutter`, the file does not have its `package:` URI, so the file cannot be resolved well (there are many compile time errors). It can be resolved without any issue in `flutter_app`, but we have found the element that is not the same as the one used in `flutter_app`, so we find nothing.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/259504

**Comment by maRci002** [comment]
I first encountered this bug when looking at `FlutterFire` source code (this time not the Flutter SDK) and I thought the analysis server just cannot follow platform interface package implementations, sometimes analysis server restart helped however after the first usages search it broke down again.

@scheglov can you confirm whenever your changes are ready that this case also works:

1. `flutter create flutter_app && cd flutter_app && flutter pub add firebase_auth && dart create --template=package package_1`
2. Open `platform_interface_firebase_auth.dart` file
3. Go to `Future<UserCredentialPlatform> signInWithCredential` declaration
4. Find `signInWithCredential`'s implementations (IntelliJ / Android Studio: `Navigate` -> `Implementation(s)` or just `click down button` at right side
5. finds both web `firebase_auth_web.dart` / vm method channel `method_channel_firebase_auth.dart` versions

Here is a little video as soon as I create `package_1` I can only find `method_channel_firebase_auth.dart` override:

https://user-images.githubusercontent.com/8436039/190602892-96a46460-b2b8-4359-b719-d03b9b964faf.mp4

**Comment by scheglov** [comment]
This seems to work too. I did `flutter create flutter_app && cd flutter_app && flutter pub add firebase_auth && dart create --template=package package_1` as was in your steps, and did not delay creating `package_1` as in the video. But I think this should be equivalent - we create analysis context collection on any package change. With moving `package_1` out, trying, and moving back in, it still worked - both overrides were shown.
