### ISSUE TITLE
Ability to override global excludes for `AnalysisContextCollection` or add a function to take a list of files, like `resolveFile2`

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#49953]
For DCM commands (like unused files, unused code) we use `AnalysisContextCollection` to get resolved units to calculate the command result. Unfortunately, the default behaviour for the context collection is to pick up an analysis_options file and exclude the files listed in `exclude:` section, but for our commands we actually need to analyze all the files in the project no matter if they are excluded or not. So we ended up using the `resolveFile2` function to resolve all exclude files separately and everything seemed to work fine, but since some analyzer version (probably 4.2 or so) it started to work very slow (here is the report from our users: https://github.com/dart-code-checker/dart-code-metrics/issues/811#issuecomment-1234032888 and as you can see, the only thing changed between the measurements is the analyzer version). 

I've checked the code and currently I don't see a way, how to resolve the excluded files properly. Could you help to find a solution? If it's not possible right now, any chance you can change the `AnalysisContextCollection` or create a function for multiple files resolution? Or at least fix the performance regression, but resolving a bunch of files would really help.

The screenshot from the user report:
![image](https://user-images.githubusercontent.com/21116742/189723356-118beccd-26be-4966-9012-dc7eb2242dc3.png)

**Comment by incendial** [comment]
And here is the example of how we use the context collection and resolveFile: https://github.com/dart-code-checker/dart-code-metrics/blob/81f521c0b707531333468019c40dd8067eb87056/lib/src/analyzers/unnecessary_nullable_analyzer/unnecessary_nullable_analyzer.dart#L66

**Comment by incendial** [comment]
@bwilkerson @scheglov sorry for the ping, but this problem made DCM command barely usable, could you please take a look?

**Comment by scheglov** [comment]
I'm not surprised that `resolveFile2` has bad performance. When you use it, it has to read all dependency files, parsed them a few times, link element models, etc. This is very expensive.

The idea of adding more options to `AnalysisContextCollection` does not seem very palatable to me. I like the current simplicity, when we analyze with the state of the file system. If you want to analyze with different options, update the analysis options file.

You don't have to do this using the physical file system, i.e. the default `PhysicalResourceProvider`, but you can create `OverlayResourceProvider` around `PhysicalResourceProvider`, and use `setOverlay` to "overwrite" the content of analysis option files. Parsing and updating these `analysis_options.yaml` files is on you of course.

If you don't care about other options than exclude, you could replace it with the empty content at all.

Alternatively, you could identify an analysis context that would include the excluded file, and still ask to analyze it. As long as `package:` URIs are resolvable, the context does not mind resolving the file, excludes are just for (1) don't create analysis contexts where we don't want them; or (2) exclude files from analysis by default.

**Comment by incendial** [comment]
> The idea of adding more options to AnalysisContextCollection does not seem very palatable to me. I like the current simplicity, when we analyze with the state of the file system. If you want to analyze with different options, update the analysis options file.

The problem with the current approach is that it implicitly states that the excluded files will not be needed for any kind of analysis, which is not true just based on the "unused code" check since we need to correctly find all used code. If code is defined in not excluded scope and used in excluded - with the current api there is no way to resolve units just for all code.

> I'm not surprised that resolveFile2 has bad performance. When you use it, it has to read all dependency files, parsed them a few times, link element models, etc. This is very expensive.

I'm not surprised either and it looked "good enough", but why since analyzer 4.2 the performance got worse?

> You don't have to do this using the physical file system, i.e. the default PhysicalResourceProvider, but you can create OverlayResourceProvider around PhysicalResourceProvider, and use setOverlay to "overwrite" the content of analysis option files. Parsing and updating these analysis_options.yaml files is on you of course.

If you don't care about other options than exclude, you could replace it with the empty content at all.

I understand the proposed idea, if updating the api is not an option, I guess I'll try, hope it won't create new issues

**Comment by incendial** [comment]
Looks like everything is fine with the overlay provider, waiting for tests on a real project, but all our tests passed successfully. Thank you!

**Comment by incendial** [comment]
Got a report that the command is now x5 times faster, THANK YOU!

**Comment by bwilkerson** [comment]
I might be misunderstanding your comment, so I apologize ahead of time if that's the case, but I found it to be somewhat concerning.

> The problem with the current approach is that it implicitly states that the excluded files will not be needed for any kind of analysis, ...

I'm not sure what gave you that impression, but that isn't the intent. Excluded files are files for which no analysis results should be reported. Because we aren't going to report any results for them, we can avoid analyzing them except in cases where they need to be analyzed as part of analyzing some non-excluded file.

The facility is useful for things like generated files whose content is not directly under user control and for code that users decide doesn't need to conform to other standards, such as temporary scripts.

> ... which is not true just based on the "unused code" check since we need to correctly find all used code. If code is defined in not excluded scope and used in excluded - with the current api there is no way to resolve units just for all code.

I'd say that in that case the excluded files need to be analyzed in order to analyze the non-excluded files, so doing so is fine.

It sounds like the real problem here is that there isn't an API for directly accessing all of the files in the analysis root. However, I suspect that you could accomplish the same task by asking the `ContextRoot` for the `root` folder and using `getChildren` to walk the directory structure.

Erasing the excluded files list seems like too big a hammer for the problem I think you have.

**Comment by incendial** [comment]
Sorry, if my statement sounded offensive or anything, that was not the intent. 

> I'm not sure what gave you that impression, but that isn't the intent.

That currently you can't override excludes with the API (only modifying the analysis_options file), even if you don't pass the path to the analysis_options, it will still be retrieved and used, thus applying all the excludes to the result on the analysis. That's why I named it "implicit".

> Excluded files are files for which no analysis results should be reported.

Yes, when we're talking about local "per file" analysis. But when the calculation requires all the project to be analysed, the current behaviour doesn't work by default. Or maybe I'm just confused by `Analysis` word meaning in `AnalysisContextCollection`. For me it also means general analysis.

> It sounds like the real problem here is that there isn't an API for directly accessing all of the files in the analysis root.

Yes!

> However, I suspect that you could accomplish the same task by asking the ContextRoot for the root folder and using getChildren to walk the directory structure.

But will I get `ResolvedUnitResult` from that API or I'll need to perform the resolution manually? 

> Erasing the excluded files list seems like too big a hammer for the problem I think you have.

Agreed that it's an overkill, but at least replacing the content of the analysis_options helped and everything else work as expected. The best option would be to have some API, for sure.

**Comment by bwilkerson** [comment]
> Sorry, if my statement sounded offensive or anything, that was not the intent.

Your comment didn't sound offensive; it was perfectly fine.

> But when the calculation requires all the project to be analysed, the current behaviour doesn't work by default.

The difference is between analyzed (parsed and resolved) verses reported. Given the way we intended the excluded list to be used I would expect that you would analyze any files you need to in order to report dead code, but that you wouldn't report on dead code contained in any excluded files.

> But will I get `ResolvedUnitResult` from that API or I'll need to perform the resolution manually?

I'm not sure what you mean by "manually", but I would expect `AnalysisSession.getResolvedUnit` to return a valid result even when the file at the specified path has been excluded, as long as the file is inside the context root and not inside a nested context root.

**Comment by incendial** [comment]
>  that you wouldn't report on dead code contained in any excluded files.

Yes, 100% true, but we were relating on `context.contextRoot.analyzedFiles()` to get the list of files, related to the current context, but looks like it's a mistake. And actually changing that might help to get rid of the overlay analysis_options content modification.

> I'm not sure what you mean by "manually", but I would expect AnalysisSession.getResolvedUnit to return a valid result even when the file at the specified path has been excluded, as long as the file is inside the context root and not inside a nested context root.

Thanks for pointing that out. Before I though that only analyzed files are resolved, but checked locally and it was a false assumption from me. I was able to get resolved unit for the excluded file.
