### ISSUE TITLE
Quick Assists and Fixes for Patterns

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#49960]
A meta-issue to discuss and track server work on quick assists and fixes for [patterns](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md).

**CorrectionProducers to Review/Test/Update**

- [x] `RemoveDuplicateCase`
- [x] `UseCurlyBraces`

**New Assists**

- [x] https://github.com/dart-lang/sdk/issues/50417

**Comment by bwilkerson** [comment]
Actually, I think we need to review all of them, don't we? Or are those the only two you think need tests / bug fixes?

**Comment by pq** [comment]
We do.  Those were just two that popped out as likely needing updates (I think?)

**Comment by keertip** [comment]
Other fixes/assists to be looked at:
- [ ] `add_const`
- [ ]  `remove_question_mark`
- [ ]  `remove_var`
- [ ]  `replace_if_else_with_conditional`
- [ ]  `remove_non_null_assertion`

**Comment by pq** [comment]
It'd be great to add a 

- [ ] ➕ `remove_break`  

too to associate w/ `unnecessary_breaks` (https://github.com/dart-lang/linter/issues/3671)

**Comment by pq** [comment]
We'll also want fixes for `invalid_case_patterns` (https://github.com/dart-lang/linter/issues/4044) which may be as simple as associating `add_const`?

- [ ] `invalid_case_patterns`

**Comment by keertip** [comment]
Updated `error_fix_status.yaml` with no fix/needs fix status for diagnostics related to patterns.

**Comment by pq** [comment]
Taking a quick look at the FE issues listed above. I think they're still open so I'm guessing `add_const` is still incomplete. @keertip?

**Comment by keertip** [comment]
`add_const` work is now complete.

**Comment by keertip** [comment]
@pq, do you have any pending work for this issue. If not we can close it.

**Comment by pq** [comment]
Yep.  I'm close to done w/ https://github.com/dart-lang/sdk/issues/50417.  Once that lands we can close this out?

**Comment by keertip** [comment]
Yes, we can!

**Comment by scheglov** [comment]
There is still a failing test that annotated with this issue.
