### ISSUE TITLE
`dart fix --help` doesn't help

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#49971]
I was following flutter's guide (https://github.com/flutter/flutter/wiki/Data-driven-Fixes#test-folder) and couldn't find `--compare-to-golden` in Dart fix help. I couldn't also find if there is a way to trigger "compare to golden" in a single file, because there is no documentation of anything.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/351125/190461434-93bc41ba-849e-4176-92bf-8ca3e53d851d.png">

**Comment by asashour** [comment]
Not sure if this helps much, but adding `-v` prints:

```
$ dart fix -h -v
...
Usage: dart [vm-options] fix [arguments]
-h, --help                      Print this usage information.
-n, --dry-run                   Preview the proposed changes but make no changes.
    --apply                     Apply the proposed changes.
    --code=<code1,code2,...>    Apply fixes for one (or more) diagnostic codes.
    --compare-to-golden         Compare the result of applying fixes to a golden file for testing.
```

**Comment by bernaferrari** [comment]
I guess it could at least say `-v` option exists? But being so small, '-v' could replace '-h' maybe?

**Comment by asashour** [comment]
`-v` is a global option

```
$ dart
...
Global options:
-h, --help                 Print this usage information.
-v, --verbose              Show additional command output.
    --version              Print the Dart SDK version.
    --enable-analytics     Enable analytics.
    --disable-analytics    Disable analytics.
```

**Comment by srawlins** [comment]
Yeah it's a feature that there are hidden options that `--help` will not show. Not sure why this one was chosen to be hidden. CC @bwilkerson

**Comment by bwilkerson** [comment]
> Not sure why this one was chosen to be hidden.

Because it's only there for Flutter developers, not for the general user population.

**Comment by srawlins** [comment]
I'll close this then. I think it's good to hide such options, and not risk confusing users, or exposing something not supported for public use.
