### ISSUE TITLE
Type flow engine needs to be updated for the records language feature

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#49977]
This is likely the cause for the following issues detected by the bots:

There are new test failures on [Reland "[cfe,corelib] Add class 'Record' to the core library"...[cfe] Handle duplicates in augmentation libraries](https://github.com/dart-lang/sdk/compare/30bbd94e5d679e348587db1ab080418a73b9a49a~...4b6a8f35b940f77e0d892537bf3029a61ae53e20).

The tests
```
co19/LanguageFeatures/Records/record_class_A01_t01 DartkCrash (expected Pass)
co19/LanguageFeatures/Records/record_class_A02_t06 DartkCrash (expected Pass)
co19/LanguageFeatures/Records/record_class_A03_t01 DartkCrash (expected Pass)
co19/LanguageFeatures/Records/record_expressions_A05_t02 DartkCrash (expected Pass)
```
are failing on configurations
```
dartkp-strong-linux-release-x64
dartkp-weak-asserts-linux-release-x64
```

**Comment by johnniwinther** [comment]
cc @alexmarkov

**Comment by alexmarkov** [comment]
TFA was updated in e5f3b0dc0e86cab0ce43634b027e14ff9c3d77a6.

The tests now pass except `co19/LanguageFeatures/Records/record_class_A01_t01` which fails with `RuntimeError` for another reason.
