### ISSUE TITLE
[analyzer] how to use `AnalysisOptionsFileConfig` in testing `analyzer_plugin`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49987]
I am trying to fix some part of #49559, and couldn't find a way to control `analysis_options.yaml`, so it is read by the test method.

In [sdk/259720](https://dart-review.googlesource.com/c/sdk/+/259720), `writeTestPackageAnalysisOptionsFile` writes the file, however `resolvedUnit.session.analysisContext.analysisOptions.lintRules` doesn't seem to pick the changes.

In `analysis_server`, there is a similar method, with TODO to use `AnalysisOptionsFileConfig`

https://github.com/dart-lang/sdk/blob/e8b67ccf6f3710f7267b2bbd5a01580546db4d5c/pkg/analysis_server/test/src/g3/fixes_test.dart#L190-L192

so I understand the correct way is to use `AnalysisOptionsFileConfig` from the `analyzer` in

https://github.com/dart-lang/sdk/blob/e8b67ccf6f3710f7267b2bbd5a01580546db4d5c/pkg/analyzer/test/src/dart/resolution/context_collection_resolution.dart#L42

but I am not sure how this is possible to be called from the `analyzer_plugin`, since it is in `test` main folder, not in `src`

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
`registerLintRules()` from `'package:linter/src/rules.dart'` should be called somewhere, e.g. in `setUp()`.

**Comment by asashour** [comment]
Thanks a lot.
