### ISSUE TITLE
(Willing to PR) Pause an isolate from C side, in order to try to let Flutter run animations at 60fps even if there are heavy widgets

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#49981]
I am trying to implement https://github.com/flutter/flutter/issues/101227. One proposal at here https://github.com/flutter/flutter/issues/101227#issuecomment-1249005541 needs to pause (suspend) the Dart isolate and resume it. In that proposal, I try to let Dart run on a separate thread, and use a mutex (or things like that) to block it whenever I want it to be paused. However, introducing threads solely for this propose seems not very elegant, as we are vulnerable to all threading bugs. Therefore, I wonder whether we can pause a Dart thread using Dart C API?

Detailed need: The dart code will call a special function (say, `safepoint()`), at all locations that it feels it is pauseable. In addition, the C++ code will tell Dart VM (or anyone who interests) that it wants dart isolate to pause as soon as dart reaches the next `safepoint()` call.

I know Dart isolate has a "pause" method, but that seems only to pause event loop. In the requirement above, I need to pause *synchronously running* code.

I am willing to PR!

**Comment by mraleph** [comment]
I think the best way forward with this (I can see that the discussion on flutter/flutter#101227 is ongoing) is to create a complete design and build a prototype demonstrating how things fit together and the benefits of the approach.  

What you are essentially asking for here is some form of preemption for Dart isolates. There are different ways to build this out (e.g. you can use existing interrupt points to implement this), but in the end we really need to see end design before we gonna consider adding something like this.

**Comment by fzyzcjy** [comment]
Totally agree. Thank you for the suggestions!
