### ISSUE TITLE
INVALID_FIELD_NAME_POSITIONAL reported even when there is no conflict

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#49998]
The specification [says](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#record-type-annotations): A field name that collides with the synthesized getter name of a positional field. For example: (int, $0: int) since the named field '$0' collides with the getter for the first positional field.

The example `(int, $0: int)` is weird and probably should be `(int, {int $0})`, but the intention seems to disallow only when there is a conflict, not always.

Happens for `co19/LanguageFeatures/Records/record_type_annotations_A07_t02`.

**Comment by bwilkerson** [comment]
The fix should wait until we have clarity on which names should be checked.

**Comment by scheglov** [comment]
`co19/LanguageFeatures/Records/record_type_annotations_A05_t05`

**Comment by bwilkerson** [comment]
I believe that this should now be fixed by https://dart-review.googlesource.com/c/sdk/+/260682
