### ISSUE TITLE
[Patterns] Parser implementation

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#50035]

**Comment by itsjustkevin** [comment]
Initial work merged at https://dart-review.googlesource.com/c/sdk/+/261020.

Thanks @stereotype441

**Comment by srawlins** [comment]
@stereotype441 is there more known parsing work, or is everything "known" done?

**Comment by stereotype441** [comment]
> @stereotype441 is there more known parsing work, or is everything "known" done?

No, there's still more parsing work left to do, including:
- pattern variable declaration statement
- pattern variable declaration inside for-loop parts
- if-case inside collections
- pattern assignments
- detection of all relevant parse errors

as well as addressing all the TODO comments from the CLs above.

I took a break from patterns parsing to write up a specification for flow analysis of patterns (and then went on vacation), but I'm expecting to return to it soon.  If the analyzer team becomes blocked on any of the above items before I can get to them, let me know and I'd be happy to hand over some parsing tasks to someone else.

**Comment by srawlins** [comment]
Hi @stereotype441 @johnniwinther , the last CLs tagged with this issue landed in December. Is there more parser work ongoing?

**Comment by johnniwinther** [comment]
Yes, I'm currently working on report errors for unsupported constant patterns.

**Comment by srawlins** [comment]
Ah excellent, thanks!

**Comment by vsmenon** [comment]
@stereotype441 - is there still open work here or can we close?

**Comment by stereotype441** [comment]
> @stereotype441 - is there still open work here or can we close?

I still have a couple of minor issues I'm trying to investigate before the beta cut, but they're issues with error recovery so they're not blocking.  I'll close this issue when I'm done with them.
