### ISSUE TITLE
[dart2wasm] Memory import failures in co19 finalizer tests

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50039]
Among the co19 tests that we run with dart2wasm, these two generate Wasm memory imports:

- co19/LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t05
- co19/LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t12

But d8 fails to find the imported memory:

```
--- Command "d8" (took 50ms):
DART_CONFIGURATION=ReleaseX64 /usr/local/google/home/omersa/dart/sdk/sdk/third_party/d8/linux/d8 --experimental-wasm-gc --wasm-gc-js-interop --experimental-wasm-stack-switching --experimental-wasm-type-reflection pkg/dart2wasm/bin/run_wasm.js -- /usr/local/google/home/omersa/dart/sdk/sdk/out/ReleaseX64/generated_compilations/custom-configuration-1/tests_co19_src_LanguageFeatures_FinalizationRegistry_ffi_Finalizer_attach_A04_t12/attach_A04_t12.wasm

exit code:
1

stdout:
pkg/dart2wasm/bin/run_wasm.js:380: TypeError: WebAssembly.Instance(): Import #49 module="ffi" error: module is not an object or function
    return new WebAssembly.Instance(module, imports);
           ^
TypeError: WebAssembly.Instance(): Import #49 module="ffi" error: module is not an object or function
    at instantiate (pkg/dart2wasm/bin/run_wasm.js:380:12)
    at pkg/dart2wasm/bin/run_wasm.js:394:20

Deobfuscated error and stack:
TypeError: WebAssembly.Instance(): Import #49 module="ffi" error: module is not an object or function
    at instantiate pkg/dart2wasm/bin/run_wasm.js 380:12
    at <fn>        pkg/dart2wasm/bin/run_wasm.js 394:20
```

I'm not sure if this is a problem with the d8 flags, or with the compiler (maybe we don't want to generate memory imports).

I will mark these tests as "skip" for now.

**Comment by askeksa-google** [comment]
The tests use FFI features without linking to an FFI module, which we currently don't support and may not want to support, since it is of limited use, and it is unclear which memory we should be referring to anyway.

**Comment by osa1** [comment]
https://dart-review.googlesource.com/c/sdk/+/260583 marks these tests as "skip".
