### ISSUE TITLE
Problem with use a big numbers

### ISSUE THREAD

**Issue by claudneysessa** [dart-lang/sdk#50036]
Problem with use a big numbers

I have a problem with use a big numbers.

Example:
If i use a function to display a big number after a trillion a have this problem:

issueFunction(double valor) {
  print(valor.toStringAsFixed(2));
}

issueNumeros() {
  issueFunction(111111111111111.11);
  issueFunction(1111111111111111.11);
  issueFunction(11111111111111111.11);
  issueFunction(111111111111111111.11);
  issueFunction(1111111111111111111.11);
}

Result:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/12506432/191898137-ac013af3-c860-432d-923e-c15d88a1458b.png">

How can i resolve this problem?

**Comment by eernstg** [comment]
Please check out https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html and https://dart.dev/guides/language/numbers, then please create a new issue if something isn't working as intended in Dart.
