### ISSUE TITLE
js-interop: [Making a Dart function callable from JavaScript] is not work

### ISSUE THREAD

**Issue by Aethey** [dart-lang/sdk#50030]
I want my dart code  get callbak from js like `EventChannel`
But I didn’t find anything like it
 then I use 
```
@JS('functionName')
external set 
```

But it not work, and then I run the demo code from:
[Making a Dart function callable from JavaScript]
```
@JS()
library callable_function;

import 'package:js/js.dart';

/// Allows assigning a function to be callable from `window.functionName()`
@JS('functionName')
external set _functionName(void Function() f);
...

```
~~then I call the 
`functionName() `or `window.functionName()` in JS
but nothing print.~~
sorry,I find if I call the JS method from dart , and in the JS method send value to dart, it will be work
but if the JS method is a async method, and I want to get the callback in dart, what should I do?

**Comment by mraleph** [comment]
Please use other channels to ask for help: https://dart.dev/community#join-the-conversation

Issue tracker exists for tracking bugs and feature requests.
