### ISSUE TITLE
[infra] Update ninja to v1.9.0 on Windows

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50032]
Our current ninja version on Windows is 1.8.2:

```
google\dacoharkes@DACOHARKES-WIN3 C:\src\dart-sdk\sdk>C:\src\depot_tools\ninja.exe --version
1.8.2
```

This version fails to generate a useful `compile_commands.json` for C++ analysis support on Windows due to `.rsp` files.

Ninja 1.9.0 has a flag for expanding these contents of the rsp file rather than referring to it:

* https://github.com/ninja-build/ninja/pull/1223

Could we update ninja to at least 1.9.0?

Hopefully this will make development on Windows in vscode with the clangd plugin slightly more bearable. 🙂 

cc @athomas

**Comment by athomas** [comment]
Note: currently we're using depot_tools ninja. We could start pinning our own. depot_tools ninja upgrade issue is https://crbug.com/931218

**Comment by dcharkes** [comment]
Looks like the depot_tools one is blocked.

I only want it for generating compile_commands.json. I'll try a different version of ninja hardcoded in the python script to see if it helps. If it helps I can maybe make it a param to tools/generate_idefiles.py (but of course that doesn't help any dart sdk Windows dev out of the box).

**Comment by dcharkes** [comment]
Ah that was easier than expected. 🎉 

`choco install ninja`

Which puts the `ninja` on the PATH, and `tools/generate_idefiles.py` just uses whatever is on the path (it doesn't bother finding our own ninja).

We have a workaround.

**Comment by athomas** [comment]
I think we should still upgrade ninja, and put it in the DEPS. That seems to be the way forward in general.

**Comment by dcharkes** [comment]
Ah, then we could get rid of the `-x` flag I just added to `generate_idefiles.py` in https://dart-review.googlesource.com/c/sdk/+/260701 and always add it in our ninja invocations from that file.

**Comment by athomas** [comment]
Correct, this is done.
