### ISSUE TITLE
"Rerun from sources" does not respect files previously unchecked

### ISSUE THREAD

**Issue by tijoforyou** [dart-lang/sdk#50046]
After unchecking one or more files via the migration tool UI, "Rerun from sources" re-enables the migration on all those files.

@stereotype441

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
