### ISSUE TITLE
Auto fix for `use_key_in_widget_constructors`

### ISSUE THREAD

**Issue by pd4d10** [dart-lang/sdk#50056]
**Describe the quick-fix**

`dart fix --apply` seems don't auto fix this rule. But it works in vscode:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/9524411/192188657-4023892f-0fef-4076-a42c-19e690a9c916.png">

Is this by design?

**Comment by pd4d10** [comment]
Thanks for the explanation!

So, is there any other *CLI or programmatic way* to use this auto fix capability? Actually, it doesn't have to be part of `dart fix` (at least in my case), the other ways which help me to do the auto fix would also be great.

**Comment by bwilkerson** [comment]
No, sorry, `dart fix` is currently the only way to apply fixes outside the IDE.

**Comment by pq** [comment]
This one looks reasonable to enable in bulk IMO.

It's worth noting that as a [flutter lint](https://github.com/flutter/packages/blob/main/packages/flutter_lints/lib/flutter.yaml), enabling it might be pretty widely beneficial.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/262423
