### ISSUE TITLE
[CP] Avoid CFE crash when input contains invalid super parameters usage

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#50052]
### Commit(s) to merge

bbdb9e43608a33313ec4a057225204d2b69dabf5

### Target

stable

### Issue Description

CFE crashes when input contains incorrect usage of super parameters feature instead of reporting a syntax error.

### What is the fix

Fix global type inference to propertly handle situations where incorrect super parameters are involved.

### Why cherry-pick

Users get an uninformative CFE crash with a stack trace instead of a readable syntax error and can't really figure out what is wrong with their code on their own.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/49641
https://github.com/flutter/flutter/issues/111833
https://github.com/dart-lang/sdk/issues/47470#issuecomment-1250232084

**Comment by itsjustkevin** [comment]
@johnniwinther @vsmenon @athomas @sigmundch thoughts on this cherry-pick?

**Comment by johnniwinther** [comment]
LGTM

**Comment by vsmenon** [comment]
lgtm

**Comment by mit-mit** [comment]
SGTM

**Comment by itsjustkevin** [comment]
Marking this as approved.  If anyone has a major reason why this shouldn't happen, please not it here.

**Comment by athomas** [comment]
We should also merge this fix to beta, it missed the branchout.

**Comment by whesse** [comment]
Merged to stable 2.18.2, not closing until it is fixed on beta as well.

**Comment by itsjustkevin** [comment]
@athomas and @mraleph is there an immediate need to submit this to beta already or can it wait until the next release window?

**Comment by itsjustkevin** [comment]
Fair point @athomas if it turns out to be a big callout, we can pivot.

**Comment by whesse** [comment]
Closing issue - it is landed in stable, and will be in the new beta branchout created today.
