### ISSUE TITLE
Connection tracking leak in HttpClient

### ISSUE THREAD

**Issue by moffatman** [dart-lang/sdk#50054]
When using `HttpClient.maxConnectionsPerHost`, there seem to be a few unhandled cases that end with the number of connections the client thinks it has open creeping up, eventually leading to all requests being blocked since there is no room for real connections left. I noticed this since I use that option in my flutter app. After the app is open for a few days, the `HttpClient` will start hanging on all requests to the most-frequently used host.

A really easy reproduction can be found on macOS with a flutter sandboxed app where you don't have `com.apple.security.network.client` entitlement. When making any network request, a `SocketException` will be thrown to the caller, but the `_ConnectionTarget._connecting` count will remain increased by 1, even though the connection failed. So if you have `maxConnectionsPerHost` set to 1, you will get an exception on the first request, and all subsequent requests to the same host will hang.

I can see a similar reproduction when toggling Wi-Fi with active HTTP connections. But I don't know whether dart or macOS is keeping those dead sockets open.

So depending on in which phase socket errors occur, it might not properly update the count of open connections. 

Version: 2.19.0-226.0.dev, macOS (arm64)

**Comment by kevmoo** [comment]
CC @brianquinlan

**Comment by brianquinlan** [comment]
I can reproduce this.

`_ConnectionTarget.connect(...)` is a bit of a beast...
