### ISSUE TITLE
How to disassemble aot snapshots

### ISSUE THREAD

**Issue by nielsenko** [dart-lang/sdk#50059]
Is it possible to decompile AOT compiled dart code?

I know how to do it for JIT snapshots, with the secret `dart --disassemble` flag, but I would like to do it for an AOT snapshot as well.

I see some reference to a `dart_precompiled_runtime` that apparently supports a `--disassemble` flag (ie. https://github.com/dart-lang/sdk/issues/41705), but this `dart_precompiled_runtime` is a mystery to me, and perhaps others outside google.

Could you elaborate on how to do this?

**Comment by osa1** [comment]
With the commit referenced above you can also do

```
dart compile exe \
    --extra-gen-snapshot-options=--disassemble,--print-flow-graph,--print-flow-graph-filter=<function name> \
    -v <Dart file>
```
