### ISSUE TITLE
[CP] Please cherry pick 875922a88f11c3cf32174995ba2c007ffa4b50fb into the stable branch

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#50064]
### Issue Description
Regression in coverage computation (mixins are not getting accounted in coverage computation)

### What is the fix
The new implementation of library filters lazy loads the scripts, the same way when there are no library_filters. Skipped scripts are still placed in the script_table_, but given an index of -1, and omitted from script_table_entries_

### Why cherry-pick
This is a regression in Dart 2.18 and has been reported by an external user.

### Issue link(s)
https://github.com/dart-lang/sdk/issues/49887

### Extra Info
The change merges cleanly into the stable branch

**Comment by vsmenon** [comment]
lgtm

**Comment by mit-mit** [comment]
sgtm, but with lower priority for creating the patch release

**Comment by athomas** [comment]
Merged to stable for `2.18.3`.
