### ISSUE TITLE
Get mirror of `package:dart_console` in order for `dart-lang/sdk` to use it in DEPS

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#50061]
I'd like to get a mirror of `package:dart_console` (hosted at [timsneath/dart_console](https://github.com/timsneath/dart_console)) so we can use it in `dart-lang/sdk` repository (via pinned version in `DEPS`).

According to [the wiki](https://github.com/dart-lang/sdk/wiki/Adding-and-Updating-Dependencies), it seems this would be fine - given that a Googler has written the package.

/cc @athomas @whesse

**Comment by athomas** [comment]
I believe the current policy is "No new dependencies outside of core and tools packages" (go/raising-the-quality-of-dart-packages-2020) and the wiki should probably be updated for this. So unless we make @timsneath's package a core or tools package it's not allowed in the SDK DEPS.

/CC @mit-mit @devoncarew

**Comment by mit-mit** [comment]
The rationale for that current policy is that something which is highly maintained (here the SDK) shouldn't take a dependency on something that is sparingly maintained/not maintained at all (here a package published by an individual).

How much of the package do you need? If just a bit, perhaps you can just inline that in the SDK?

**Comment by devoncarew** [comment]
+1 to @mit-mit's comment - I'd look at working around the package (additionally, I see that package:dart_console depends on package:win32, also not in the sdk). We're trying to limit SDK deps in general, and were just recently able to remove the last few deps not published by the dart team.

**Comment by mraleph** [comment]
I understand how the policy applies to things which are transitive dependencies of the SDK itself. Reducing dependencies there makes sense. Here @mkustermann wants to pull in a package to be used in a development tool that he has written. This sort of usage should be exempt from go/raising-the-quality-of-dart-packages-2020 - as it is never going to reach the end user. 

The other alternative is to develop that tool outside of Dart SDK repo in a separate repo - but that seems counterproductive. We want internal tools which are tightly coupled with the SDK to live in the SDK repo.  

> `package:win32`

FWIW by now this package is an integral part of Flutter ecosystem.

**Comment by mkustermann** [comment]
Couldn't agree more than with @mraleph!

* We have to ensure that `dart-lang/sdk` and all of it's dependencies are safe to use.
* We should ensure what gets distributed to end users (which is mainly the built `dart-sdk.zip`s as well as subset of `<sdk>/pkg/*` packages) meets our quality standards. 

Neither of those are an issue in this case (even more so because the code using `package:dart_console` wouldn't be published atm).

> How much of the package do you need? If just a bit, perhaps you can just inline that in the SDK?
> I'd look at working around the package (additionally, I see that package:dart_console depends on package:win32, also not in the sdk).

Copying parts of `package:dart_console` code into `dart-lang/sdk` creates a fork:
* Copying code doesn't change the quality of it (which seems to be questioned here).
* Whatever effort we'd put into maintaining the fork, we can put into maintaining `package:dart_console`. Which then the community would also benefit from.

=> I think the processes is getting in the way here and it should be adjusted.

I can go ahead with checking my code into `dart-lang/sdk` without updating `DEPS` by moving it not into `<sdk>/pkg` but e.g. `<sdk>/runtime/tools`. It would then force users to run `dart pub get` themselves before using. Would that be better?

**Comment by athomas** [comment]
The problem I see with adding it to DEPS is that once it's in there, it tends to get used in other places as well over time.

Also, there was nothing in the original request about what the purpose it. If this is a tool that developers just run locally, and it won't be used in the infrastructure, using `pub` seems like a good option that avoids the DEPS discussion.

**Comment by mraleph** [comment]
Would we be able to run some smoke tests on the CI if we go the route of using `pub get`?

**Comment by athomas** [comment]
Given the answers above, your plan is to build a tool that uses `dart_console` and will eventually be tested and distributed together the rest of the SDK. So why shouldn't normal restrictions apply other than that they are inconvenient?

```
a) safety/security (despite being written by Googler?)
b) quality (any evidence it is not up to our quality standards?)
c) maintenance (any evidence that bugs aren't getting fixed?)
```

If all those aren't an issue, it sounds like you can easily make the argument to make it a `tools` package.

> Would we be able to run some smoke tests on the CI if we go the route of using pub get?

Yes, though we try to keep tests dependent on `pub` to a minimum to avoid flakiness introduced by the extra networking it needs. The few tests we have are fairly stable so this would also work for a few more tests.

**Comment by devoncarew** [comment]
> Copying parts of package:dart_console code into dart-lang/sdk creates a fork:

How much of this package are you relying on? What are you using it for? I know of a few other packages that support ansi output / terminal manipulation.

**Comment by mkustermann** [comment]
For now, I'll try to land it now in `runtime/tools` without updating `DEPS`.

> How much of this package are you relying on? What are you using it for? I know of a few other packages that support ansi output / terminal manipulation.

Maybe half of it: The console, cursor movement, terminal control, colors (Based on that the CLI tool will have code completion).

**Comment by mkustermann** [comment]
Closing this as the original request to mirror `package:dart_console` & update `DEPS` is currently not needed.

We may re-visit this discussion if we start making the heapsnapshot analysis tool available to end-users.

**Comment by devoncarew** [comment]
> For now, I'll try to land it now in `runtime/tools` without updating `DEPS`.

The code won't be tested on the bots however - neither static analysis or test (unless you wire something up yourself). It's likely to bit-rot. Have you considered creating it as a package in dart-lang/? This would work well unless your package needs to closely align with the SDK.

**Comment by mkustermann** [comment]
> The code won't be tested on the bots however - neither static analysis or test (unless you wire something up yourself). It's 
> likely to bit-rot.

It is tested in all relevant VM configurations (see [runtime/tests/vm/dart/heapsnapshot_cli_test.dart](https://github.com/dart-lang/sdk/blob/2a43b3789824e3398/runtime/tests/vm/dart/heapsnapshot_cli_test.dart), run test via e.g. `tools/test.py -n dartk-strong-linux-release-x64 vm/dart/heapsnapshot_cli_test`).

Only the (relatively small) code that depends on `package:dart_console` is not tested.

> Have you considered creating it as a package in dart-lang/? This would work well unless your package needs 
> to closely align with the SDK.

The code is somewhat aligned with the VM (e.g. it's reachability analysis has to replicate something VM's GC is doing - e.g. need to be aware of `WeakProperty`, `WeakReference`, `FinalizerEntry`, ... and their fields & treat them same way VM's GC treats them).

Additionally our CI can run the tests in various configurations (JIT, AOT, compressed pointer mode, ...) - which is hard to replicate in a separate repo.

Lastly, we can use gerrit as code review tool (which is much better than github).
