### ISSUE TITLE
Implement reachability barrier

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#50080]
This is a follow up for GCClock discussion at [go/flutter-devtools-sync](http://go/flutter-memory-sync).

Implement API `int gcCount` in `dart:developer`, and make it available in profile and debug modes.

Suggested documentation:

> The value increases when full cycle of garbage collection happened.
> 
> It is not guaranteed for each full cycle of garbage collection to result in the counter increase.
> However, it is guaranteed that, if an object did not have retaining path to the app root when the value
> switched to `n`, it will be garbage collected by the time when the value switched to `n + 1`.

**Comment by polina-c** [comment]
https://dart-review.googlesource.com/c/sdk/+/266424

**Comment by a-siva** [comment]
CL in progress here https://dart-review.googlesource.com/c/sdk/+/266424
