### ISSUE TITLE
DateTime.tryParse parses invalid dates, substituting a valid date

### ISSUE THREAD

**Issue by WorikQCI** [dart-lang/sdk#50083]
```
DateTime.tryParse("2022-02-34")
DateTime (2022-03-06 00:00:00.000)
```

The input string was invalid.  The correct value to return is `null`

* Dart core libraries ("dart:async", "dart:io", etc.)

This the correct place?

```
% dart --version
Dart SDK version: 2.18.1 (stable) (Tue Sep 13 11:42:55 2022 +0200) on "macos_arm64"
```

**Comment by Cat-sushi** [comment]
[parse method - DateTime class - dart:core library - Dart API](https://api.dart.dev/stable/2.18.1/dart-core/DateTime/parse.html "parse method - DateTime class - dart:core library - Dart API") says :

> This method accepts out-of-range component values and interprets them as overflows into the next larger component. For example, "2020-01-42" will be parsed as 2020-02-11, because the last valid date in that month is 2020-01-31, so 42 days is interpreted as 31 days of that month plus 11 days into the next month.

**Comment by lrhn** [comment]
See https://github.com/dart-lang/sdk/issues/11189

We decided at some point to not try to be strict here.

**Comment by WorikQCI** [comment]
What a terrible idea.

There is no valid output for invalid input
