### ISSUE TITLE
[frontend_server] Tracked sources output by the FrontendCompiler are incorrect when compiling more than 1 entry point

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50095]
> FrontendCompiler outputs incorrect tracked sources when more than 1 entry point is compiled. This unit test fails because of this issue.
>
> Bug: Tracked sources output by the FrontendCompiler are incorrect when compiling more than 1 entry point.

From https://dart-review.googlesource.com/c/sdk/+/253002

cc @jensjoha

**Comment by jensjoha** [comment]
https://github.com/dart-lang/sdk/issues/49534
