### ISSUE TITLE
Flip the test configurations in the Dart VM build bots to test strong null safety mode in all the configurations

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#50091]
Please see  go/dart-vm-sound-null-safety for details on the test configurations switch.

**Comment by a-siva** [comment]
//cc @athomas

**Comment by itsjustkevin** [comment]
@athomas and @a-siva has this work been completed?  Is there anything we need to unblock this?

**Comment by athomas** [comment]
This work is ongoing but not blocked on anything right now.

**Comment by a-siva** [comment]
@rmacnak-google has submitted a number of CLs that have moved all the existing legacy bots to run tests in sound null safety mode, closing issue.
