### ISSUE TITLE
Feature suggestion : add isARM to Platform

### ISSUE THREAD

**Issue by Roms1383** [dart-lang/sdk#50098]
Hi and thanks ! So as the title suggests, it would be great to have an easy way to differentiate between MacOS Intel platform and MacOS ARM platform.

* Feature suggestion related to Dart core libraries ("dart:io")
* Dart SDK version : `2.18.2 (stable) on "macos_arm64"`
* Using MacOS M1 Pro
* Using Chrome

**Comment by lrhn** [comment]
Defining a "platform" is a fractal problem. You can always split a "platform" into two by differentiating one some property that differs, and which *might* be important to someone.

We have generally shied away from specifying the CPU architecture, and just gone with operating system name.
Those are orthogonal. I'm sure we have Android on both Intel and ARM already, and now also MacOS. 
It's still MacOS, at least in name.

We try to keep the number of platforms as limited as possible.

(The other end of the spectrum would be where you can distinguish every version number of each operation system, the OS language, and the precise mold of the CPU. That will allow perfect tailoring to the environment, but also be completely impossible to keep up-to-date.)

**Comment by rmacnak-google** [comment]
The question of what architecture we're running is also pretty ambiguous. For example, on an ARM64 Mac, we could be running a Dart VM under Rosetta that is generating Dart code for RV64, so that ARM64, X64, and RV64 are all legitimate answers to "the current architecture" depending on what one is trying to do.

**Comment by sortie** [comment]
Indeed the platform question is complicated and other systems solve it better. Does `dart:fii` offer the needed functionality? Alternatively on macOS, you can use `dart:io` to run e.g. the `uname -m` program to find the machine architecture.

**Comment by Roms1383** [comment]
@lrhn @rmacnak-google @sortie hi everybody and thanks for being so reactive :pray: 🙂 

> Defining a "platform" is a fractal problem. You can always split a "platform" into two by differentiating one some property that differs, and which might be important to someone.

> The question of what architecture we're running is also pretty ambiguous. For example, on an ARM64 Mac, we could be running a Dart VM under Rosetta that is generating Dart code for RV64, so that ARM64, X64, and RV64 are all legitimate answers to "the current architecture" depending on what one is trying to do.

Ah Indeed. Then it's better we, users, handle it ourselves on a case-by-case basis.

> Alternatively on macOS, you can use dart:io to run e.g. the uname -m program to find the machine architecture.

@sortie I didn't think about it, thanks for the suggestion !

Issue initially [aroused](https://github.com/fzyzcjy/flutter_rust_bridge/issues/754#issuecomment-1263502812) when loading a dynamic library, strangely enough some of us (MacOS users only) need to use `DynamicLibrary.open(dylibPath)` instead of `DynamicLibrary.executable()` (see [DynamicLibrary](https://api.dart.dev/stable/2.6.1/dart-ffi/DynamicLibrary-class.html)). But ultimately it's not blocking since we chose to let our users "opt-onto" Silicon by specifying an additional CLI arg when running commands, so it's not that of a big deal (details in [comment](https://github.com/fzyzcjy/flutter_rust_bridge/issues/754#issuecomment-1264547762)).

**Comment by brianquinlan** [comment]
You can do the differentiation that you want using the [`dart:ffi` Abi class](https://api.dart.dev/stable/2.18.5/dart-ffi/Abi-class.html).

Is that sufficient?

**Comment by Roms1383** [comment]
At first sight it seems like it does perfectly @brianquinlan, thanks so much !
Let's just hold on for the outcome of the related PR on `flutter_rust_bridge` to close this issue, mostly because I don't own all the different devices to check on my own: I'm gonna wait for CI builds and help from fellow contributors who do to make sure everything is fine first.

**Comment by Roms1383** [comment]
@brianquinlan we couldn't test for each and every platform (mostly because we don't own the different devices ourselves), but I'm confident that [dart:ffi Abi class](https://api.dart.dev/stable/2.18.5/dart-ffi/Abi-class.html) is indeed the solution to our issue.

I've used it to differentiate between MacOS Intel and MacOS M1 (so strictly speaking `Abi.macosX64` from `Abi.macosArm64`) and it works like a charm !

Thanks again for steppin' in, I think this issue can be closed :)
