### ISSUE TITLE
Discrepancy in treatment of legacy `Never`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#50099]
I guess this issue illustrates how wonderful it is that we're getting rid of support for non-null-safe code. ;-)

Consider the following program (consisting of two libraries, `n014.dart` and `n014lib.dart`):

```dart
// --- Library 'n014lib.dart'.
import 'n014.dart';

void callF() {
  f<Never>(null);
}

// --- Library 'n014.dart'.
// @dart = 2.9
import 'dart:async';
import 'n014lib.dart';

void f<X>(Object o) {
  print(o is FutureOr<X>);
}

void main() {
  callF();
}
```

This program has no issues (with `dart analyze`, `dart`, or `dart compile js`), but it prints `true` with the VM and `false` with `dart compile js`.

I believe the correct behavior is to print `true`: When `f` is invoked, the value of `X` is `Never` (the empty type, because 'n014.dart' enables null safety), and the value of `o` is null. The type `FutureOr<X>` then means `FutureOr<Never*>*`, because it occurs in a legacy library.

But we have a [very special rule](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#runtime-checks-and-unsound-null-checking) for `null is T` for various kinds of `T`, and in particular `null is Never*` should evaluate to true, so `null is FutureOr<Never*>*` should also evaluate to true.

Based on that analysis, I'll mark this as a `dart compile js` issue.

**Comment by eernstg** [comment]
Note that `dart compile js` prints `true` with `print(o is X)`. This means that `o is X` is true and at the same time `o is FutureOr<X>` is false, which violates the expectation that `o is T` implies `o is FutureOr<T>` for all `T`.

**Comment by fishythefish** [comment]
I believe @nshahan just encountered this as well and a fix is on the way.

**Comment by nshahan** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/261000.
