### ISSUE TITLE
Only classes extending NativeFieldWrapperClass1 can be passed as Pointer.  Pass as Handle instead.

### ISSUE THREAD

**Issue by weishirongzhen** [dart-lang/sdk#50107]
<img width="681" alt="截屏2022-10-03 10 51 39" src="https://user-images.githubusercontent.com/54241621/193493333-89a87b84-28de-4a1e-84a7-d7bfb2131eeb.png">

use ffi-gen output code as above screen shot.
any idea?

**Comment by dcharkes** [comment]
Correct, 8a78aaf463ec45457b963c49bc002f315da2a53c.
