### ISSUE TITLE
Meta: Is there a way to enforce a named constructor/factory or static method in a subclass via annotation

### ISSUE THREAD

**Issue by jtdLab** [dart-lang/sdk#50115]
Is there a possibility to enforce a constructor/factory or static method to be available in a subclass via annotation

**Comment by bwilkerson** [comment]
Assuming you're asking whether such a mechanism exists today: not that I'm aware of. Constructors and static members are not inherited by subclasses, and most of the annotations similar to the one you're asking about are related to ensuring certain properties related to inheritance and/or overriding.

**Comment by jtdLab** [comment]
Okay. I think solving the "missing" "constructor/static method inheritance" in dart via a meta annotation would be great. If technically possible. What are the cons to this idea?

**Comment by bwilkerson** [comment]
> I think solving the "missing" "constructor/static method inheritance" in dart via a meta annotation would be great.

I'm not sure what that means, so ignore the rest of this response if I'm misunderstanding you. The fact that constructors and static members (fields and method) are not inherited is a fundamental part of the language specification.

If you're proposing that the language should be changed, you can [file an issue on the language repo](https://github.com/dart-lang/language/issues/new/choose).

If you're proposing that we add an annotation to simulate a change to the language, then I don't think we would do that. We are happy to add annotations that enhance the experience of using the language, but we're not going to add annotations that modify the language in such a fundamental way.

**Comment by jtdLab** [comment]
For example the `@protected` annotation gives the analyzer the possibility to provide feedback to the developer if he tries to access the variable outside of the protected scope (Something like protected keyword is not a feat of the Dart Language). 

The situation im talking about is like that

```dart
class A {
 @newAnnotation
 A.foo();
}

class B extends A {
// analyzer notifies pls provide a constructor .foo
}
```

If you related to an equal case in your previous answer i will close this issue.

**Comment by bwilkerson** [comment]
No, that was different than what I thought you'd meant.

I don't know whether we'd be willing to add such an annotation, but I definitely agree that an annotation for that behavior would be possible.

**Comment by srawlins** [comment]
Thanks for the request, @jtdLab . Can you clarify what the use case is? Why would it be beneficial for subclasses to have constructors with the same name as a super class?
