### ISSUE TITLE
[CP] DevTools cherry pick request for Dart 2.19

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#50117]
This cherry pick request is to roll the DevTools version in the SDK from 2.17.0 to 2.18.0. This DevTools version bump was targeted for the upcoming release (with the expected cutoff of 10/5) but there was a date miscommunication so we missed the cutoff by a day. Discussed this with @zanderso and @itsjustkevin offline. 

[commit to cherry pick] This is the SDK commit that bumps the DEPS version for DevTools to 2.18.0: Commit to cherry pick: https://github.com/dart-lang/sdk/commit/003ea967a56e0dd0e2744099c78a46fa5ddc6c57

**Comment by itsjustkevin** [comment]
@athomas @whesse the cutoff date issue was a failure on my part to catch that it was incorrect. 

We would like to cherry-pick this into the beta branch to give it time to test.

**Comment by athomas** [comment]
LGTM

**Comment by whesse** [comment]
This has been cherry-picked into 2.19.0-255.2.beta
