### ISSUE TITLE
[dart2wasm] Implement instance tear-off of `null`

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50111]
Repro:

```dart
void main() {
  print(toStringTearOff(123)()); // works
  print(toStringTearOff(null)()); // fails with 'unreachable'
}

Function() toStringTearOff(Object? obj) {
  return obj.toString;
}
```

@askeksa-google did you already have an idea on how to implement this?

What I have in mind is: since we only support sound-null-safe Dart, in a tear-off expression we can always check if the receiver is nullable, and if it is, insert a conditional (or a call a function with a conditional) that checks whether the receiver is `null` or not. If it's `null`, we return a pre-generated closure that implements the method for the `null` receiver.

**Comment by askeksa-google** [comment]
We already do that `null` check. You just need to add `toString` and `noSuchMethod` cases to the `switch` in `visitInstanceGet` in the code generator.

**Comment by osa1** [comment]
https://dart-review.googlesource.com/c/sdk/+/262601
