### ISSUE TITLE
CFE doesn't resolve names on types extending a record type

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50124]
Consider the following code:

```dart
foo<T extends (int, String)>(T t) => t.$0;
```

The CFE currently reports the following error:

```
/tmp/qwerty.dart:1:40: Error: The getter '$0' isn't defined for the class '(int, String)'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '$0'.
foo<T extends (int, String)>(T t) => t.$0;
```

**Comment by eernstg** [comment]
The general rule we have specified for a type variable type is that [the interface is taken from the bound](https://github.com/dart-lang/language/blob/2536dba6c5dcc2c43b8a9585e277c9e68e6a7639/specification/dartLangSpec.tex#L4947). This means that it's an obvious generalization of existing rules to say that `T` has a `$0` getter in the given example.
