### ISSUE TITLE
[dart2wasm] Tracking issue for failing async tests

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50122]
Tests below are currently marked as skip as they time out:

- Language/Statements/Continue/async_loops_t07
- Language/Statements/Continue/async_loops_t08
- LibTest/async/Stream/Stream.fromFutures_all_t01
- LibTest/async/Stream/Stream.fromIterable_all_t01
- LibTest/async/StreamController/StreamController.broadcast_Stream_all_A01_t01
- LibTest/async/StreamController/stream_all_A01_t01

Currently they're marked as being blocked on #50026, but at least some of them fail with the missing `Function.apply` implementation in the current `main` branch, and the fix for #50026 doesn't seem to make any of these work.

(The reason why they time out is probably because the missing implementation causes the tests to hang)

https://dart-review.googlesource.com/c/sdk/+/262426 updates status file to reference this issue in these tests.

**Comment by askeksa-google** [comment]
As of https://dart-review.googlesource.com/c/sdk/+/267960 the tests are re-enabled, as they no longer time out.

These tests are now fixed:
- co19/Language/Statements/Continue/async_loops_t08
- co19/LibTest/async/Stream/Stream.fromFutures_all_t01

These tests still fail:
- co19/Language/Statements/Continue/async_loops_t07
- co19/LibTest/async/Stream/Stream.fromIterable_all_t01
- co19/LibTest/async/StreamController/StreamController.broadcast_Stream_all_A01_t01
- co19/LibTest/async/StreamController/stream_all_A01_t01

**Comment by mkustermann** [comment]
I believe this can be closed. All the tests seem to be passing modulo `co19/LibTest/async/Stream/Stream.fromIterable_all_t01` which fails on all backends and is more likely a corelib issue.
