### ISSUE TITLE
Analyzer error highlighting and messaging with errors in nested widget constructors

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#50127]
Given the following sample code: https://gist.github.com/jonahwilliams/f876f5a6c0efcbc90788cf339f777f25

I had a type error because one of my widgets was missing a positional parameter:

```dart
  @override
  Widget build(BuildContext context) {
    return Center(
      child:
        ShaderSamplerBuilder(
          child: CircularProgressIndicator()
        )
      );
  }
}
```

Fixed version:

```dart
  @override
  Widget build(BuildContext context) {
    return Center(
      child:
        ShaderSamplerBuilder(
          builder, // woops, forgot this one
          child: CircularProgressIndicator()
        )
      );
  }
}
```

In VSCode, the error highlighting appears on the opening paren of the ShaderSamplerBuilder constructor. This makes it appear as if there is an error in the CircularProgressIndicator constructor:

![Untitled](https://user-images.githubusercontent.com/8975114/193913686-6a9a5699-cb3a-4c03-a12f-76331aacb0f5.png)

Additionally, when I highlight the error squigglies to try to see the specific error, I have to scroll through all of the CircularProgressIndicator docs. At the end, both lints and the error are displayed, but it was difficult to tell which errors I needed to fix and what the error actually applied to.

![Untitled 2](https://user-images.githubusercontent.com/8975114/193913956-0ce58539-9533-4f96-b1d6-cb7388a864c7.png)

I would expect that the highlighting could more accurately tell me where the error was occuring, and feature the errors more prominently than the lints/hints or the dart docs

**Comment by jonahwilliams** [comment]
FYI @srawlins

**Comment by srawlins** [comment]
I think two issues here, or two fixes:

1) The highlight region is the opening `(` through the closing `)`, for `not_enough_positional_arguments`. This is specifically problematic as the `(` can (often) be the last character on a line. It would be better to (a) include the function name (if there is one), (b) only highlight the function name (if there is one), (c) highlight only the arguments, but not the `(` or `)`. Any of these choices would be better, I think.

2) I think we should include the name of the function (if there is one), e.g.

   > 1 positional argument(s) expected by ShaderSamplerBuilder, but 0 found.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/262603

has a proposal to highlight the following token, and having an optional function name.
