### ISSUE TITLE
Pure function closures aren't optimized away in AOT builds

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#50126]
## Seen
The resulting assembly code for AOT builds for closures that capture no state is slower than using using methods/functions.

## Expected
I expect closures that capture no state to perform as fast as methods/functions.

## Version
Dart 2.17.1

## Example

https://godbolt.org/z/hqMbKGorb

```dart
void test1() {
    List<int> ints = [1, 2, 3, 4, 5, 6];
    ints.sort((x, y) => x - y);
    print(ints);
}

int _sort(int x, int y) => x - y;

void test2() {
    List<int> ints = [1, 2, 3, 4, 5, 6];
    ints.sort(_sort);
    print(ints);
}

void main(List<String> args) {
    test1();
    test2();
}
```

Notice that `test1` has an extra `call 9a048 <Stub__iso_stub_AllocateClosureStub>` that test2 doesn't have.

**Comment by gaaclarke** [comment]
I had time to make a simple benchmark and I can't get this to show any meaningful impact on x86_64 AOT.  I can't capture GC time in the microbenchmark.  So to be clear this is small potatoes.  It's probably not worth investigating.

**Comment by a-siva** [comment]
Based on the comment above, closing this issue.

**Comment by gustav3d** [comment]
What a disgrace to simply ignore this issue.

**Comment by a-siva** [comment]
@gustav3d if you have an example where your experience is different from what is mentioned in the comment by @gaaclarke please share here and we will re-prioritize the issue.
