### ISSUE TITLE
Failures on CL 260451 due to super/this confusion

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#50138]
There is a new test failure on [CL 260451](https://dart-review.googlesource.com/c/sdk/+/260451).

The test
```
co19/LanguageFeatures/Private-fields-promotion/promotion_A01_t05 MissingCompileTimeError (expected Pass)
```
is failing on configurations
```
cfe-strong-linux
cfe-weak-linux
```

This happening because field promotion doesn't yet make a distinction between `super.fieldName` and `this.fieldName`.  I plan to address this in a follow-up CL.

**Comment by stereotype441** [comment]
As of https://dart-review.googlesource.com/c/sdk/+/262865 (the analyzer implementation of field promotion) this also fails on configuration `analyzer-asserts-linux` (unsurprisingly).

**Comment by srawlins** [comment]
Hi @stereotype441 was this fixed in 3207808?

**Comment by stereotype441** [comment]
> @stereotype441, any progress on this?

Not yet.  This failure is related to the "field promotion" feature, which we have postponed until 3.1.

**Comment by stereotype441** [comment]
Unassigning myself because I'm not actively working on field promotion right now; I will likely pick it up again later in the year.
