### ISSUE TITLE
[vm/aot] annotations on libraries retain top_level_class

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50137]
```
Unexpected object (Class with illegal cid, full-aot): 0x7f1c2903bea1 Library:'file:///tmp/tests_ffi_native_assets_UZOZJC/.dart_tool/native_assets.dart' Class: ::
referenced by 0x7f1c2903bbc1 Library:'file:///tmp/tests_ffi_native_assets_UZOZJC/.dart_tool/native_assets.dart'
referenced by 0x7f1c29c08081 null
```

Extra input file

```dart
@pragma('vm:entry-point')
@pragma('vm:native-assets', {
  'linux_x64': {
    'file://${Platform.script.toFilePath()}': [
      'absolute',
      '${ffiTestFunctionsUriAbsolute.toFilePath()}',
    ],
  }
})
library native_assets;
```

Invocation:

`/usr/local/google/home/dacoharkes/dart-sdk/sdk/pkg/vm/tool/gen_kernel --aot --platform /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/vm_platform_strong.dill --packages /usr/local/google/home/dacoharkes/dart-sdk/sdk/.dart_tool/package_config.json --output /tmp/tests_ffi_native_assets_VDXIER/out.dill --source /tmp/tests_ffi_native_assets_VDXIER/.dart_tool/native_assets.dart /usr/local/google/home/dacoharkes/dart-sdk/sdk/tests/ffi/native_assets/paths_test.dart`

`/usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/gen_snapshot --snapshot-kind=app-aot-elf --elf=/tmp/tests_ffi_native_assets_VDXIER/out.snapshot /tmp/tests_ffi_native_assets_VDXIER/out.dill`

Looking up the annotation on the library in the VM works fine in JIT.

The TFA does not have logic for libraries on the native code oracle.
I've tried finding the top-level class in `pkg/vm/lib/transformations/type_flow/native_code.dart`.

```dart
  @override
  visitLibrary(Library library) {
    final type = _annotationsDefineRoot(library.annotations);
    if (type != null) {
      if (type != PragmaEntryPointType.Default) {
        throw "Error: pragma entry-point definition on a library must evaluate "
            "to null, true or false. See entry_points_pragma.md.";
      }
      nativeCodeOracle.addClassReferencedFromNativeCode(
          library.classes.firstWhere((e) => e.name == LibraryIndex.topLevel));
    }
    library.visitChildren(this);
  }
```

However, no `::` class is found.

@alexmarkov Maybe you know what the right fix is here before I reinvent the wheel. 🙂

**Comment by alexmarkov** [comment]
Kernel AST doesn't have a concept of top-level classes. It has just libraries and ordinary classes.
TFA and its tree shaker currently do not remove libraries at all, even if they are empty.

So you might need to look at the tree shaking performed in [Precompiler::DropLibraries()](https://github.com/dart-lang/sdk/blob/1bff4bead9297d2d6e545e3ea7804bdb5a08a305/runtime/vm/compiler/aot/precompiler.cc#L2850).

**Comment by mkustermann** [comment]
@dcharkes Could you provide clear reproduction instructions? (The example you gave above in https://github.com/dart-lang/sdk/issues/50137#issue-1398131334 uses an annotation with compile-time errors)

As Alex said, the library is probably tree shaken in `gen_snapshot`. The `@pragma('vm:entry-point')` annotation is currently not affecting libraries - one would need to update `precompiler.cc:Precompiler::AddAnnotatedRoots()` to look for the annotation on a library and if it's present add the top-level class of the library to the set of retained classes.

> Looking at it again, the issue might actually be that adding pragma's to a library causes the top_level_class to be retained. But since we don't assign a class id to top level classes, the serializer fails. (We remove class ids from top level classes to avoid running over the 64k class id limit.) So we probably need a way to keep annotations on libraries in AOT snapshots without adding the top level classes.

I don't see how this can be related.

Top-level get assigned a class-id and get registered in the class table like any other class, but their cid will be outside the 16-bit space.

**Comment by dcharkes** [comment]
It doesn't reproduce anymore:

```
$ cat main.dart 
main() {
  print('hello');
}
$ cat additional_source.dart 
@pragma('vm:entry-point')
@pragma('vm:native-assets', {
  'foo': 'bar',
})
library native_assets;
$ /usr/local/google/home/dacoharkes/dart-sdk/sdk/pkg/vm/tool/gen_kernel --aot --platform /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/vm_platform_strong.dill --packages /usr/local/google/home/dacoharkes/dart-sdk/sdk/.dart_tool/package_config.json --output out.dill --source additional_source.dart  main.dart 
$ /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/gen_snapshot --snapshot-kind=app-aot-elf --elf=out.snapshot out.dill                      
$  /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/dart_precompiled_runtime out.snapshot
hello
```

Either something has changed in the mean time (I've rebased a bunch of times) or it was caused by something else.
I'll try to revert my design later to be based on library annotations instead of class annotations again to see if I can reproduce it again to triage it further.

**Comment by dcharkes** [comment]
The error was apparently caused by a slightly different scenario:

* https://github.com/dart-lang/sdk/issues/50540

**Comment by dcharkes** [comment]
I'm able to reproduce this again by enabling meta-data for libraries as per

* https://github.com/dart-lang/sdk/issues/50539#issuecomment-1326461544

with the following dart component:

```dart
  return Component(
    libraries: [
      Library(
        Uri.parse('vm:native-assets'),
        fileUri: _dummyFileUri,
        annotations: [
          ConstantExpression(InstanceConstant(pragma.reference, [], {
            pragmaName.fieldReference: StringConstant('vm:native-assets'),
            pragmaOptions.fieldReference: nativeAssetsConstant,
          }))
        ],
      )..nonNullableByDefaultCompiledMode =
          NonNullableByDefaultCompiledMode.Strong,
    ],
  )..setMainMethodAndMode(
      null,
      false,
      NonNullableByDefaultCompiledMode.Strong,
    );
```

Adding entry-point doesn't prevent the illegal cid.
This is in contrast with:

* https://github.com/dart-lang/sdk/issues/50540

But might have the same root cause.

```
invocation : /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/gen_snapshot --snapshot-kind=app-aot-elf --elf=/tmp/tests_ffi_native_assets_TVZYKS/out.snapshot /tmp/tests_ffi_native_assets_TVZYKS/program.dill
dir        : /usr/local/google/home/dacoharkes/dart-sdk/sdk
exitCode   : -6
stdout     : 
stderr     : Unexpected object (Class with illegal cid, full-aot): 0x7f4f8652fb61 Library:'vm:native-assets' Class: ::
referenced by 0x7f4f8652f831 Library:'vm:native-assets'
referenced by 0x7f4f87108081 null
```

**Comment by dcharkes** [comment]
I was putting the library in the object_store, causing to retain it, which then caused the toplevel class to be retained if it has any metadata. 🙈 

So this is caused by a combination of retaining libraries and adding metadata to the library.
