### ISSUE TITLE
Are field names starting with underscores allowed for records?

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50144]
The following test assumes that they aren't, but I'm not sure what the current status of that is.

```
python3 tools/test.py -n cfe-strong-mac co19/LanguageFeatures/Records/record_type_annotations_A06_t01
```

**Comment by eernstg** [comment]
The spec said that this is an error last time I checked, I think it's still there. So: no private names.

**Comment by chloestefantsova** [comment]
> The spec said that this is an error last time I checked, I think it's still there. So: no private names.

Thanks, Erik! Is it true for both named and positional field names in record types or only for the named fields?

**Comment by eernstg** [comment]
I'd assume the names of positional fields (the ones that are basically just comments) would be treated the same as the names of named fields. The section [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#syntax) is in line with this conclusion, even though it doesn't explicitly mention the two kinds of names.
