### ISSUE TITLE
`Wrong full snapshot version` on trying to run a language test on Windows

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50141]
After building the SDK, and on trying to run a language test with

`python3 tools/test.py -n analyzer-win language_2/parameter/bad_named_parameters_test`

There is an error:

>Wrong full snapshot version, expected '76d4b846230cf20a52c4206cba8c1838' found '08c97bb6b092b132f1e7ec94d72e301f'

[Stackoverflow](https://stackoverflow.com/questions/53431517) questions were more for Flutter.

SDK was built without errors with:

```
gclient sync
python ./tools/build.py --no-goma --mode release --arch x64 create_sdk
```

And on trying to skip that error in [app_snapshot.cc](https://github.com/dart-lang/sdk/blob/e77f2ee5ffe37173cfdac0ffe79ae20c25399ec8/runtime/vm/app_snapshot.cc#L8356-L8364), there is another error:

>Snapshot not compatible with the current VM configuration: the snapshot requires 
'release no-code_comments no-dwarf_stack_traces_mode lazy_dispatchers no-dedup_instructions no-asserts use_field_guards use_osr no-branch_coverage x64-win no-compressed-pointers null-safety' 
but the VM has 
'release no-code_comments no-dwarf_stack_traces_mode lazy_dispatchers no-dedup_instructions no-asserts use_field_guards use_osr no-branch_coverage x64 windows no-compressed-pointers null-safety'

with only differ between `x64-win` and `x64 windows`. Skipping that error also doesn't help.

Is it meant for Windows to run those tests, or anything I am missing?

**Comment by whesse** [comment]
The Windows builder that tests that configuration also builds an additional build target, that builds the dartanalyzer tool used by the test.  This tool is no longer built by create_sdk, since the "dartanalyzer" command has been replaced by the "dart analyze" command.  I think you have an outdated version of dartanalyzer, that didn't get overwritten by a new build.

Try adding utils/dartanalyzer after create_sdk in your build command.

**Comment by asashour** [comment]
Indeed, I cleared the `out` directory, and rebuilt everything, and it couldn't find `dartanalyzer`. On adding `utils/dartanalyzer` it was then found.

I guess this info would be helpful to add in [wiki](https://github.com/dart-lang/sdk/wiki/Building).

Thanks a lot.
