### ISSUE TITLE
Potential parsing issues with record types being sub-terms of typedefs

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50146]
The following tests produce compile-time errors, but it seems they should not.

**python3 tools/test.py -n cfe-strong-linux co19/LanguageFeatures/Records/record_type_annotations_A02_t11**

```
tests/co19/src/LanguageFeatures/Records/record_type_annotations_A02_t11.dart:45:17: Error: Expected an identifier, but got '('.
Try inserting an identifier before '('.
typedef void R5((int? i, {String? s}));
                ^
tests/co19/src/LanguageFeatures/Records/record_type_annotations_A02_t11.dart:49:10: Error: Expected an identifier, but got '('.
Try inserting an identifier before '('.
void bar((int? i, {String? s})) {}
         ^
```

**python3 tools/test.py -n cfe-strong-linux co19/LanguageFeatures/Records/record_type_annotations_A02_t12**

```
tests/co19/src/LanguageFeatures/Records/record_type_annotations_A02_t12.dart:44:30: Error: Expected '{' before this.
typedef (int? i, {String? s})? R4();
                             ^
tests/co19/src/LanguageFeatures/Records/record_type_annotations_A02_t12.dart:44:30: Error: Expected a declaration, but got '?'.
typedef (int? i, {String? s})? R4();
                             ^
tests/co19/src/LanguageFeatures/Records/record_type_annotations_A02_t12.dart:44:36: Error: Expected a function body or '=>'.
Try adding {}.
typedef (int? i, {String? s})? R4();
                                   ^
tests/co19/src/LanguageFeatures/Records/record_type_annotations_A02_t12.dart:49:10: Error: Expected an identifier, but got '('.
Try inserting an identifier before '('.
void bar((int? i, {String? s})?) {}
         ^
```

**Comment by eernstg** [comment]
Actually, the old style `typedef` requires parameter names (if there is only one identifier then it's the name, not the type, we can't omit the name and have the type).

```dart
typedef void R5((int? i, {String? s}) someName);
```

This covers `R5` and `bar` in record_type_annotations_A02_t11.

However, the treatment of with `R4` seems to be wrong, it should be possible to have a return type which is `R?` where `R` is a record type.

**Comment by lrhn** [comment]
I'm guessing that `typedef` parsing does lookahead to see if it's a new or old typedef, and expects an identifier after the `typedef`, since both the new-style typedef and the content of an old-style typedef used to have to start with an identifier.

(I'm ready to discontinue old-style typedef.)

**Comment by jensjoha** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/263123 / b3dbaadc8308af59388a0f581b59346bd9ef0aad
