### ISSUE TITLE
Can't correctly inference sub class

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#50151]
```dart
class Foo {}
class Bar extends Foo {
  String daz = 'daz';
}

T make<T extends Foo>(T Function() fn) {
  return fn();
}

void main() {
  Foo bar = make(Bar.new);
  
  print(bar.daz); // error
}

```

**Comment by eernstg** [comment]
;-)

**Comment by jodinathan** [comment]
@eernstg wouldn't it work like promotion?

this works:

```dart
if (bar is Bar) {
  print(bar.daz);
}
```

**Comment by eernstg** [comment]
Promotion by assignment or initialization requires that the target type is a 'type of interest'. This basically means that you have referred to that type or a non-null version thereof. For example, with `int? i = 5;` you have made `int?` and `int` types of interest, so the initialization to `5` will promote `i` to have type `int`. But with `num? n = 5;` you haven't made `int` a type of interest, so there is no promotion.

In the example here, you had `Foo bar = make(Bar.new);`, and even with the change that prevents the context type from prevailing, `Foo bar = make<Bar>(Bar.new);`, you would _still_ have a situation where `Bar` isn't a type of interest. So you still won't get the promotion of `bar`.
