### ISSUE TITLE
`Record` tests fail in dart2wasm

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#50156]
Tests involving the `Record` feature are failing in dart2wasm. This seems to be because the dart2wasm compiler configuration doesn't respect experiments specified by the test files, which appears to be because `dart2wasm` can't accept `--enable-experiments` flags. I'm not sure if `Record` objects would just work out of the box if we were able to pass the experiment to the CFE, or whether they would need special treatment in dart2wasm.

**Comment by eyebrowsoffire** [comment]
Hmm, I do notice this https://github.com/dart-lang/sdk/issues/50014. Maybe this is just a dupe

**Comment by askeksa-google** [comment]
Yes, no need for this issue when we have #50014.
