### ISSUE TITLE
Run compiled dart program in `Isolate`

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/sdk#50158]
Hello, I want to request a feature for `dart:isolate`:
Dart can be compiled to `kernel` modules, `aot-snapshot`s and `jit-snapshot`s.
There's a method `Isolate.spawnUri`, which is simply JIT from pure Dart code.
It would be good to have an option to spawn `Isolate` from `kernel` module or `aot`/`jit` snapshot.

**Comment by rmacnak-google** [comment]
This is already possible. The URI given to Isolate.spawnUri can point to source, kernel or app-jit when running on a JIT VM or an app-aot snapshot when running on an AOT VM.

**Comment by Zekfad** [comment]
@rmacnak-google thanks for your response.
It would be good to clarify the docs about such a possibility?
