### ISSUE TITLE
(Willing to PR) Expose more about Timeline, such as allowing to configure timestamp, just like what is exposed to Flutter C++ code

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#50165]
## I am willing to PR for this :)

In `flutter/engine` we can report timeline events like:

```c++
    fml::tracing::TraceEventAsyncComplete(
        "flutter",                    // category
        "SceneDisplayLag",            // name
        raster_finish_time,           // begin_time
        latest_frame_target_time,     // end_time
        ...
    );
```

Or other sync or async or flow things. Most interestingly, we can report the *time* we choose, instead of always being forced as *now*. 

This is very helpful feature. Hope I do not need to prove its helpfulness, because it is there and `flutter/engine` has already proved it by using it extensively :)

---

### Potential implementation

I looked at how `flutter/engine` finally calls Dart timeline code. It uses `Dart_TimelineEvent` indeed. On the other hand, a Dart code using `Timeline` class will finally utilize `DartTimelineEventHelpers::ReportTaskEvent`.

Comparing their implementation, the (rough) solution is quite trivial: 

```c++
void DartTimelineEventHelpers::ReportTaskEvent(TimelineEvent* event,
                                               int64_t id,
                                               intptr_t type,
                                               int64_t timestamp, // <---- ADDED, suppose we define negative as use-default
                                               char* name,
                                               char* args) {
  const int64_t start = timestamp < 0 ? OS::GetCurrentMonotonicMicrosForTimeline() : timestamp; // <----- MODIFIED, old code is unconditionally call `OS::GetCurrentMonotonicMicrosForTimeline()`
  ... same as before ...
```

**Comment by rmacnak-google** [comment]
There are several different underlying recorders, some of which do not take a timestamp as input and assume the event happens at the current time, such as Android's Systrace and Mac's Signpost. The exposure of a timestamp parameter is leftover plumbing from when the only recorder was Mojo, not a capability of the trace system.
