### ISSUE TITLE
Add support for 8-bit color format in ui.Image

### ISSUE THREAD

**Issue by lcodecorex** [dart-lang/sdk#50178]
It is recommended to add support for 8-bit color format in ui.Image, such as OPAQUE/APHLA8/GRAY8 anyway.
It provides the ability to input any data into the shader's sampler without memory waste.

for example:
Input Y/U/V components to the shader respectively, then you can play YUV stream on pure Flutter without use of any platform external texture.

pseudo code:
```
Future<ui.Image> decodeFrom8BitFormat(Uint8List bytes, int width, int height) {
  final completer = Completer<ui.Image>();
  decodeImageFromPixels(
    bytes.buffer.asUint8List(),
    width,
    height,
    PixelFormat.alpha8,  // 8bit pixel format
    completer.complete,
  );
  return completer.future;
}

Future<Shader> yuvShader() async {
  const width = 960;
  const height = 540;
  final yBytes = Uint8List(width * height);
  final uBytes = Uint8List(width * height ~/ 4);
  final vBytes = Uint8List(width * height ~/ 4);
  final yTextureImage = await decodeFrom8BitFormat(yBytes, width, height);
  final uTextureImage = await decodeFrom8BitFormat(uBytes, width ~/ 2, height ~/ 2);
  final vTextureImage = await decodeFrom8BitFormat(vBytes, width ~/ 2, height ~/ 2);

  const _spirv = ''; // base64 encoded compile from glsl
  final program = await FragmentProgram.compile(spirv: Uint8List.fromList(base64Decode(_spirv)).buffer);
  return program.shader(
    floatUniforms: Float32List.fromList([]),
    samplerUniforms: [
      ImageShader(
        yTextureImage,
        TileMode.clamp,
        TileMode.clamp,
        UmbraShader.identity,
      ),
      ImageShader(
        uTextureImage,
        TileMode.clamp,
        TileMode.clamp,
        UmbraShader.identity,
      ),
      ImageShader(
        vTextureImage,
        TileMode.clamp,
        TileMode.clamp,
        UmbraShader.identity,
      ),
    ],
  );
}
```

**Comment by lcodecorex** [comment]
In my case, to render YUV420P images on pure Flutter, I must convert YUV data to fake RGBA data which intents to sink data to ImageShader.
So I converted YYYYUV to RGBA like, such as vec4(0, 0, 0, Y0),vec4(0, 0, 0, Y1),vec4(0, 0, 0, Y2),vec4(0, 0, 0, Y3),vec4(0, 0, 0, U0),vec4(0, 0, 0, V0). It's a much(3X) waste of memory. Follow is my code:
```
final yuvData = await rootBundle.load('assets/dash.yuv');
const yLen = 1920 * 1080;
const uvLen = 960 * 540;
final yData = Uint8List.view(yuvData.buffer, 0, yLen);
final uData = Uint8List.view(yuvData.buffer, yLen, uvLen);
final vData = Uint8List.view(yuvData.buffer, yLen + uvLen, uvLen);
final yRgbaData = Uint32List.fromList(yData);
final uRgbaData = Uint32List.fromList(uData);
final vRgbaData = Uint32List.fromList(vData);
yImage = await decodeRawRgba(yRgbaData.buffer.asUint8List(), 1920, 1080);
uImage = await decodeRawRgba(uRgbaData.buffer.asUint8List(), 960, 540);
vImage = await decodeRawRgba(vRgbaData.buffer.asUint8List(), 960, 540);
```

final result:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/10334668/195023294-640e0cbe-b519-4118-95ac-a9873731013c.png">

The source code is here: [flutter_yuv_render_sample](https://github.com/lcodecorex/flutter_yuv_render_sample)

**Comment by lrhn** [comment]
This sounds like an issue that should be filed in the/a Flutter repository, maybe https://github.com/flutter/flutter.

**Comment by lcodecorex** [comment]
> 

I raised this question under flutter [issues](https://github.com/flutter/flutter/issues/113266), but it is considered to be related to the **dart:ui** library.

**Comment by lrhn** [comment]
The `dart:ui` library *is* a Flutter library, it's only provided by the Flutter SDK, and does not exist in the plain Dart SDK.

**Comment by lrhn** [comment]
Back on track :)
