### ISSUE TITLE
`dart test -p chrome` fails with: No such file or directory

### ISSUE THREAD

**Issue by matehat** [dart-lang/sdk#50176]
Since the upgrade to Flutter 3.3.4 / Dart 2.18.2, running `dart test` and targeting a browser fails:

```
❯ dart test -p chrome
00:00 +0 -1: compiling test/facets_test.dart [E]
  Failed to load "test/facets_test.dart":
  No such file or directory
    Command: /opt/homebrew/Cellar/asdf/0.9.0/libexec/installs/flutter/3.3.4-stable/bin/cache/dart-sdk/bin/dart2js --enable-asserts /private/var/folders/rx/3377ldyn6_3g2k3rqzbh3khw0000gn/T/dart_test_3XH4AU/runInBrowser.dart --out=/private/var/folders/rx/3377ldyn6_3g2k3rqzbh3khw0000gn/T/dart_test_hplddc/test_BbJ7dj/facets_test.dart.browser_test.dart.js --packages=file:///Users/mathieublaisdamours/Development/platform/dart/packages/faceted_model/.dart_tool/package_config.json --enable-diagnostic-colors
00:00 +0 -1: Some tests failed.
```

I highly suspect `[..]/dart2js` to be the culprit, since it was removed in Dart 2.18. Thing is, this call originates from `dart test` command, thus as a user I have no control over providing the alternative path to compiling to js.

**Comment by sigmundch** [comment]
@jakemac53 - I thought most uses from webdev and build_web_compilers were using directly the dart2js snapshot and not the wrapper script. Is this use from `dart test` coming from a different codepath that we didn't cover in our migration?

**Comment by sigmundch** [comment]
In fact, I see that @natebosch migrated the test runner to use `dart compile js` in https://github.com/dart-lang/test/pull/1665

Could this be that an old version of `package:test` is being used here?

**Comment by jakemac53** [comment]
Yeah this must be an old version. You should be able to run `dart pub upgrade` to get the latest. If you can't get the latest due to a version solve not allowing it you would need to either resolve those issues or fall back to the older sdk.

**Comment by sigmundch** [comment]
Thanks @jakemac53!

@matehat - let us know if `dart pub upgrade` resolves this issue for you! I'd be curious to see which version of package test you have too.

**Comment by sigmundch** [comment]
Awesome, thanks for confirming!

@jakemac53 @natebosch - FYI, note the comment above about the CHANGELOG and versioning, in case any action is needed there.

**Comment by jakemac53** [comment]
Oh I see what is happening, its actually in `test_core` where the code lives, but we hadn't actually published that package yet. So test 1.20.2 does not have the change to use `dart compile js`, it just drops the `dart2js-path` argument.
