### ISSUE TITLE
dart does not recognize the linux home symbol

### ISSUE THREAD

**Issue by hellojukay** [dart-lang/sdk#50187]
This tracker is for issues related to:

* Dart core libraries ("dart:async", "dart:io", etc.)

* Dart SDK Version (`dart --version`)
```
hellojukay@manjaro ~ $ dart --version
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"
```

```
    appDocDir = await Directory("~/.config/food/").create(recursive: true);
```
this code create dirctory in  `./~/.config/food/`, but i think `~` should be `$HOME`, it should create directory `/home/hellojukay/.config/food`

**Comment by asashour** [comment]
I am not sure if this should be automatically handled. Do other languages support that?

[Java](https://stackoverflow.com/questions/7163364) seems not.
[Python](https://docs.python.org/3/library/os.path.html) seems to have `os.path.expanduser(path)`

If this is decided to be supported, other OSs should also be implemented.

**Comment by hellojukay** [comment]
Thanks @asashour , this shuold not be supported, for golang it not work also。
