### ISSUE TITLE
Set.intersection dartdoc uses name "unionSet"

### ISSUE THREAD

**Issue by ryanhaining** [dart-lang/sdk#50180]
https://github.com/dart-lang/sdk/blob/main/sdk/lib/core/set.dart#L290-L291

```
/// final unionSet = characters1.intersection(characters2);
/// print(unionSet); // {A}
```

The name seems confusing given that the result is not a union. The `difference` docs use the name `differenceSet1`, so I believe `intersection` should be using `intersectionSet`.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/263621
