### ISSUE TITLE
Utf8Decode of `UnmodifiableUint8ListView` on VM is slower than `Uint8List`.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#50194]
I modified the Utf8Decode benchmark to mix `Uint8List` and `UnmodifiableUint8ListView`.
The result is 30-95% slower for the mixed workload (AOT,  JIT similar)
I suspect that the accelerated path does not recognize the unmodifiable view.

go/dartbug-50194-perfnumbers

/cc @askeksa-google

**Comment by a-siva** [comment]
//cc @rmacnak-google
