### ISSUE TITLE
null safty not working properly

### ISSUE THREAD

**Issue by alex9153** [dart-lang/sdk#50219]
```
class Foo {
  String? bar;

  void func() {
   if (bar == null)
     return;
    var temp = bar;
  }
}
```

in the func method "bar" is not available without !

**Comment by mraleph** [comment]
Documentation explains why this is the case: https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields

tldr is that something like this is a valid subclass of `Foo`, which makes sound promotion of fields (even if they are final) currently impossible:

```dart
class Bar extends Foo {
  String? get bar => random.nextBool() ? super.bar : null;
}
```

The language team is aware that this is one of the common sources of complaints and they are looking at various possible solutions, see [label:field-promotion](https://github.com/dart-lang/language/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afield-promotion) on the language repo.
