### ISSUE TITLE
feature flags which can differ per app are set at VM compile time

### ISSUE THREAD

**Issue by Mis012** [dart-lang/sdk#50221]
issue:  
feature flags like DART_COMPRESSED_POINTERS split the number of apps that you can run with a given vm build in half (ignoring the fact that most developers probably don't change the defaults, making the math more complicated), meaning that you need (assuming the number of such features is 9, which seems like a good guess) 2^9 == 512 builds of the dart vm in order to be able to run any dart app. If this was a thing with e.g. hotspot, I'm sure I wouldn't be the only one seeing that as an issue, but here we are...

proposed solution (or I assume you would see this as a feature request, which is still better than WONTFIX):  
make it possible to change these feature flags at runtime, so that a Linux distribution can package one build of the dart vm instead of 512 of them.

now, I assume your answer to this will be "we expect all apps to bundle their own build of the dart vm", which is fair, but it would surely be great if you could restrain yourself from making it basically impossible for Linux distributions to package a build of dart vm that is statistically likely to work with a randomly selected dart application

NOTE: while it might be possible for a Linux distribution to package open source dart apps such that they will work with it's build of dart vm, there are distributions which package closed source software, and there doesn't seem to be any good reason for why that should require packaging at minimum 512 builds of dart vm (or one per app, whichever is less I suppose?)

**Comment by mraleph** [comment]
Dart VM does not provide a stable ABI (unlike say JVM - which runs class files). So any AOT compiled app (or app distributed as an AppJIT snapshot, or Kernel AST binary blob) needs to ship its own runtime or require that target machine has a specific pinned version of Dart SDK installed. 

If app is distributed as source then it can use any Dart VM version installed on the machine (as long as that Dart VM supports the necessary language level).

So whether or not something like compressed pointers are runtime configurable or not does not actually make distribution any simpler.
