### ISSUE TITLE
Dart package should have easy access to its files

### ISSUE THREAD

**Issue by matthew-carroll** [dart-lang/sdk#50222]
I'm working on a Dart package, which includes a file in the package that our Dart code needs to reference at runtime.

We're activating this package globally. Currently, it seems like we have to locate this file on the user's machine ourselves.

Dart should provide a method that resolves the location of a globally activated package so that we can easily and confidently access our own files within that package.

**Comment by matthew-carroll** [comment]
CC @slightfoot

**Comment by blaugold** [comment]
How are you resolving the location? [`Isolate.resolvePackageUri`](https://api.dart.dev/stable/2.18.2/dart-isolate/Isolate/resolvePackageUri.html) has worked well for me for this use case.

```dart
final assetLocation = await Isolate.resolvePackageUri(Uri.parse('package:my_package/src/assets/foo.txt'));
```

**Comment by matthew-carroll** [comment]
@slightfoot can you respond to the suggestion above ^

**Comment by mraleph** [comment]
I think @blaugold's suggestion should work for you. Please comment if it does not and we reopen.

**Comment by AlexanderFarkas** [comment]
Correct me if I'm wrong, but `Isolate.resolvePackageUri` doesn't work in AOT mode

**Comment by mraleph** [comment]
@AlexanderFarkas it does not, but AOT is not mentioned anywhere in the question. The question is about globally activated package which has nothing to do with AOT.

**Comment by SantiiRepair** [comment]
@mraleph yes, but it would be interesting to expand the information
