### ISSUE TITLE
Duration.toString() wrong formatting on negative durations

### ISSUE THREAD

**Issue by uditrugman** [dart-lang/sdk#50232]
This tracker is for issues related to:
* Dart core libraries ("dart:async", "dart:io", etc.)

* Dart SDK Version (`dart --version`)
```
fvm dart --version
Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"
```

it appears that Duration.toString() does not deal with negatives as expected.
it will include "-" only if the number of hours != 0, otherwise the "-" will just not appear.

OK - expect((Duration.zero - const Duration(hours: 1)).toString(), equals("-1:00:00.000000"));

FAILED - expect((Duration.zero - const Duration(minutes: 1)).toString(), equals("-0:01:00.000000"));
Actual result: 0:01:00.000000

**Comment by lrhn** [comment]
This is fixed in 2.18.
