### ISSUE TITLE
Severe regression of BinaryPrinter.writeComponentFile performance

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#50239]
Noticed this regression while investigating another unrelated regression and bisected it to e4ae0cf2ce0755b85e9bffdfa50f5042e4edcd99.

There was a big drop in performance of [BinaryPrinter.writeComponentFile](https://github.com/dart-lang/sdk/blob/30de5494d5e93bb014c2bfdd9d3f85ff0e03a429/pkg/kernel/lib/binary/ast_to_binary.dart#L583) method when running this Dart code using the Dart SDK after e4ae0cf2ce0755b85e9bffdfa50f5042e4edcd99.
 
Repro:
* Checkout a recent version of Dart SDK (for example at c3fb57010512acdc680593186e86a32f345ec694), build Dart SDK to get a `vm_platform_strong.dill` and get a large input kernel file with a compatible kernel binary version (I used ~500MB dill file from an internal app described in b/251787563).
* Apply the following change to measure time:
```patch
diff --git a/pkg/kernel/lib/binary/ast_to_binary.dart b/pkg/kernel/lib/binary/ast_to_binary.dart
index eba37ecd6a5..630e8c63c80 100644
--- a/pkg/kernel/lib/binary/ast_to_binary.dart
+++ b/pkg/kernel/lib/binary/ast_to_binary.dart
@@ -581,6 +581,7 @@ class BinaryPrinter implements Visitor<void>, BinarySink {
   }
 
   void writeComponentFile(Component component) {
+    Stopwatch timer = new Stopwatch()..start();
     Timeline.timeSync("BinaryPrinter.writeComponentFile", () {
       compilationMode = component.mode;
       _computeCanonicalNames(component);
@@ -623,6 +624,7 @@ class BinaryPrinter implements Visitor<void>, BinarySink {
 
       _flush();
     });
+    print("writeComponentFile took ${timer.elapsedMilliseconds}ms");
   }
 
   void writeListOfStrings(List<String>? strings) {
```
* Run
```
dart pkg/vm/bin/protobuf_aware_treeshaker.dart --aot --platform vm_platform_strong.dill --remove-source input.dill output.dill
```

If running this command using Dart SDK at e4ae0cf2ce0755b85e9bffdfa50f5042e4edcd99 or after, writeComponentFile takes ~23-25 seconds.
If running this command using Dart SDK at previous revision (b5972073a9de5e0b1df13ddafdb683f5aee55ff8) or before (for example using Dart SDK 1.18.0 stable), writeComponentFile takes ~4.5 seconds.

@lrhn It looks like certain `Uri` APIs became a lot slower in e4ae0cf2ce0755b85e9bffdfa50f5042e4edcd99.

fyi @johnniwinther @jensjoha @rakudrama @rmacnak-google

**Comment by lrhn** [comment]
That is a surprisingly large difference for that change, unless it directly hits the changed behavior. 
Do any of the URIs used by the code contain backslahses? 
(If so, that would change the code from using `SimpleUri`, which simply validateds the original string and keeps it as backing store, to using the fully generalized `Uri` implementation which handles escapes and normalizes each part of the URI.)

**Comment by alexmarkov** [comment]
Narrowed this down to `writeUriToSource` method:

https://github.com/dart-lang/sdk/blob/4768317f2b56a7049c16f371058da8af3ff9981d/pkg/kernel/lib/binary/ast_to_binary.dart#L829-L892

This method uses maps with Uri keys and also converts Uris to Strings. There are 30784 Uris being processed in the main loop, and they all changed from `_SimpleUri` to `_Uri` after e4ae0cf2ce0755b85e9bffdfa50f5042e4edcd99. There are 0 Uris with `uriAsString.contains('\\')`, where `String uriAsString = "$uri"`. Is it possible that that change switched all Uris to slow `_Uri` representation by mistake?

**Comment by alexmarkov** [comment]
It looks like `_Uri` also violates some speculative assumptions in JIT, because after e4ae0cf2ce0755b85e9bffdfa50f5042e4edcd99 `writeUriToSource` method was deoptimized 276 times (with reason 14 'GuardField'), and VM continued using unoptimized version of this method all the time, which explains why it became so slow. Before e4ae0cf2ce0755b85e9bffdfa50f5042e4edcd99 this method was not deoptimized.

**Comment by alexmarkov** [comment]
Filed https://github.com/dart-lang/sdk/issues/50245 about the repeated deoptimization.

**Comment by alexmarkov** [comment]
All processed Uris changed the type. Example: `org-dartlang-sdk:///sdk/lib/async/async.dart`.
Most likely they are created with `Uri.parse` while reading kernel binary.

The following simple example shows the difference in type:
```dart
main() {
  Uri uri = Uri.parse('org-dartlang-sdk:///sdk/lib/async/async.dart');
  print (uri.runtimeType);
}
```

**Comment by alexmarkov** [comment]
Verified that 61741732f4b16d883f3c5d4f760767c7ac4bc78c fixed the regression.
