### ISSUE TITLE
[ Breaking Change Request ] Remove support for `Metrics` from `dart:developer`

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#50231]
Since the early days of the VM service protocol, the Dart VM has provided APIs for visualizing instantaneous metrics in graphs within Observatory through `dart:developer`, exposed through the [`Metrics`](https://api.dart.dev/stable/2.18.2/dart-developer/Metrics-class.html) interface.

**Rationale:**

This feature has been broken for quite some time in Observatory as we lost the ability to display charts and graphs as a consequence of the Dart 2.0 and null-safety migrations. DevTools also does not currently support displaying metrics, so it seems like a good time to trim an unused API.

**Impact:**

Deprecating and removing the `Metrics` APIs should have little to no impact as they haven't worked in quite some time. There's no obvious uses in g3, and there have been no issues filed regarding the broken Observatory functionality in the years since the breakage occurred. There's also no breakages to the VM service protocol as a result of this change, as the existing metrics RPCs are private and were never publicly exposed.

**Proposal:**
Deprecate [`Metrics`](https://api.dart.dev/stable/2.18.2/dart-developer/Metrics-class.html), [`Metric`](https://api.dart.dev/stable/2.18.2/dart-developer/Metric-class.html), [`Counter`](https://api.dart.dev/stable/2.18.2/dart-developer/Counter-class.html), and [`Gauge`](https://api.dart.dev/stable/2.18.2/dart-developer/Gauge-class.html), and schedule them for removal in Dart 3.0.

cc @a-siva @kenzieschmoll

**Comment by sigmundch** [comment]
@bkonyi - I fear this will indirectly break the support we just added in https://github.com/dart-lang/sdk/issues/49062 to expose internal metrics like memory usage and capacity numbers, correct?

Will we offer any alternative to that other than the current logic we use in dart2js? (where we launch a the service protocol and use a vm service client within the process to read this data).

**Comment by bkonyi** [comment]
> @bkonyi - I fear this will indirectly break the support we just added in #49062 to expose internal metrics like memory usage and capacity numbers, correct?
> 
> Will we offer any alternative to that other than the current logic we use in dart2js? (where we launch a the service protocol and use a vm service client within the process to read this data).

No, this shouldn't impact internal memory statistics accessed via the service protocol's private metric RPC. If I recall correctly, we ended up discovering that the native metrics weren't being exposed properly by #49062 anyway since they are defined in native code, not in the `Metrics` map in `dart:developer`.

**Comment by sigmundch** [comment]
Thanks for clarifying - I thought they had been exposed and that we just didn't get around to convert our logic to use it.

**Comment by a-siva** [comment]
//cc @zanderso

**Comment by itsjustkevin** [comment]
@sigmundch do you feel comfortable with this now that @bkonyi has addressed your concerns?

**Comment by sigmundch** [comment]
Yes, thanks for checking. sgtm

**Comment by itsjustkevin** [comment]
Thanks for the response @sigmundch, with that, @vsmenon, @grouma, @Hixie can you take a look?

**Comment by vsmenon** [comment]
@a-siva @kenzieschmoll - do you both lgtm?

**Comment by a-siva** [comment]
lgtm

**Comment by Hixie** [comment]
fine by me since it's already broken anyway. did anyone file a bug asking for it to be fixed?

**Comment by kenzieschmoll** [comment]
DevTools doesn't use Metrics for anything. LGTM.

**Comment by bkonyi** [comment]
@itsjustkevin is it safe to assume this can go forward? :-)

**Comment by bkonyi** [comment]
[Deprecation CL is ready to land once this is approved](https://dart-review.googlesource.com/c/sdk/+/272381).

**Comment by bkonyi** [comment]
> fine by me since it's already broken anyway. did anyone file a bug asking for it to be fixed?

Nope, I don't think anyone really even noticed it was broken in the first place.

**Comment by itsjustkevin** [comment]
@grouma opinions on this breaking change?

**Comment by itsjustkevin** [comment]
Thank you @grouma, with that, I think we can approve this breaking change @bkonyi.

**Comment by itsjustkevin** [comment]
@bkonyi I see this was merged in November and would like to close this, but don't see a changelog entry for this.  Am I just missing it?

**Comment by bkonyi** [comment]
Hm, thought I had included a changelog entry, but looks like I haven't. I'll add one.

**Comment by itsjustkevin** [comment]
Thanks @bkonyi!  Feel free to close the issue when the changelog entry is added.

**Comment by itsjustkevin** [comment]
Changelog updated in https://dart-review.googlesource.com/c/sdk/+/278531.  Closing this issue.
