### ISSUE TITLE
Failures on Front end logic for field promotion.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#50235]
There are new test failures on [Front end logic for field promotion.](https://dart-review.googlesource.com/c/sdk/+/260451).

The tests
```
co19/LanguageFeatures/Records/type_promotion_A02_t01 Crash (expected Pass)
co19/LanguageFeatures/Records/type_promotion_A02_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-strong-linux-x64-chrome
dart2js-hostasserts-weak-linux-x64-chrome
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
```

It looks like this is due to some record handling logic that is unfinished, and not actually related to field promotion.

**Comment by sigmundch** [comment]
Thanks @stereotype441 - indeed, both compilers are not far enough yet to cover much of the records feature. I'm closing this issue since we'll be tracking the entire suite of test as part of the implementation process.
