### ISSUE TITLE
[gen_kernel] Support compiling without entry point

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50242]
Passing in the following _additional_ file to `gen_kernel` with `--source <path-to-file>` works:

```dart
@pragma('vm:entry-point')
@pragma('vm:native-assets', {
  "linux_x64": {
    "mylib_dylib": [
      "absolute",
      "/usr/local/google/home/dacoharkes/ffi-samples/dacoharkes/native_lib_distribution/mylib_dylib/native/lib/linux_x64/libmylib_dylib.so"
    ],
    "mylib_source": [
      "absolute",
      "/usr/local/google/home/dacoharkes/ffi-samples/dacoharkes/native_lib_distribution/dart_app/.dart_tool/native/mylib_source/linux_x64/libmylib_source.so"
    ]
  }
})
class _NativeAssets {}
```

Now, if I do _two_ `gen_kernel` invocations and use dill-file concatenation, I require having a `void main() {}` in this additional file.

```
invocation : /usr/local/google/home/dacoharkes/dart-sdk/sdk/pkg/vm/tool/gen_kernel --platform /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/vm_platform_strong.dill --packages /usr/local/google/home/dacoharkes/dart-sdk/sdk/.dart_tool/package_config.json --output /tmp/tests_ffi_native_assets_KREUSU/nested/native_assets.dill /tmp/tests_ffi_native_assets_KREUSU/nested/.dart_tool/native_assets.dart
dir        : /usr/local/google/home/dacoharkes/dart-sdk/sdk
exitCode   : 254
stdout     : /tmp/tests_ffi_native_assets_KREUSU/nested/.dart_tool/native_assets.dart: Error: No 'main' method found.
Try adding a method named 'main' to your program.
```

Should we consider supporting running `gen_kernel` without a `main`?

(Note that in AOT this would treeshake everything that is not marked with `@pragma('vm:entry-point')`, but kernel concatenation is _only_ supported in JIT anyway currently. https://github.com/dart-lang/sdk/issues/50152)

**Comment by jensjoha** [comment]
gen_kernel seems to call `kernelForProgram` which does this:

```dart
    if (requireMain && component.mainMethod == null) {
      context.options.report(
          messageMissingMain.withLocation(source, -1, noLength),
          Severity.error);
      return null;
    }
```

whereas `kernelForModule` does not...

**Comment by dcharkes** [comment]
I do not have this use case anymore, as we have opted for passing data specifically for native assets rather than a separate Dart file: https://dart-review.googlesource.com/c/sdk/+/264842/29/pkg/vm/lib/kernel_front_end.dart

Closing this issue. It can be reopened if someone else has this use case.
