### ISSUE TITLE
[web] `String.fromCharCodes` is very slow on some inputs.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#50253]
The following program produces results like these when compiled with **dart2js**:

```text
List                         1ms
UnmodifiableListView         14606ms
Uint8List                    2ms
UnmodifiableUint8ListView    30169ms
List                         1ms
UnmodifiableListView         29174ms
Uint8List                    0ms
UnmodifiableUint8ListView    30096ms
...
```

The code is calling `String.fromCharCodes` with a large `start:` index.
It appears that the instances of  `List` other than `JSArray` and `Uint8List` are treated like arbitrary `Iterable`s, using an `Iterator` to scan over the ~1M elements before the slice.

It would be better to use something like `List.of(charCode.skip(start).take(end - start))`, since `List` implementations usually use some kind of `SubListIterable` that can `skip` efficiently. The downside is that if the captured list is too short it is not easy to diagnose whether `start` or `end` is at fault.

<details>

```dart
import 'dart:collection';
import 'dart:typed_data';

void main() {
  final list1 = List.filled(1000000, 32);
  final list2 = UnmodifiableListView(list1);
  final list3 = Uint8List.fromList(list1);
  final list4 = UnmodifiableUint8ListView(list3);

  for (int i = 0; i < 10; i++) {
    time('List                       ', use(list1));
    time('UnmodifiableListView       ', use(list2));
    time('Uint8List                  ', use(list3));
    time('UnmodifiableUint8ListView  ', use(list4));
  }
  print('result: "$result"');
}

void time(String name, String Function() work) {
  final sw = Stopwatch()..start();
  for (int i = 0; i < 1000; i++) {
    result = work();
  }
  print('$name  ${sw.elapsedMilliseconds}ms');
  if (result != ' ' * 10) throw 'Unexpected "$result"';
}

late String result;

String Function() use(List<int> list) =>
    () => String.fromCharCodes(list, list.length - 20, list.length - 10);
```
</details>

Other issues noticed when stepping through the **dart2js** generated code

- `is NativeUint8List` does not seem to be efficient
- The "is JSIndexable" test in the accelerator code for `J.$index$asx` finds a interceptor dispatch record _without the `JSIndexable` slot initialized_. It might be that `TypedArrayOfInt` should explicitly implement `JSIndexable`, or something else is wrong with the mechanism.
- The normal path for `String.fromCharCodes` for `JSArray` could be modernized to use JavaScript's `String.fromCodePoints`. This method rejects input elements that cannot be converted to an integer in the Unicode range, so it would avoid the need for the loop we currently use to validate the inputs. The downside is that the browsers all differ in the format of the error.

**Comment by lrhn** [comment]
The code is indeed:
```dart
  factory String.fromCharCodes(Iterable<int> charCodes,
      [int start = 0, int? end]) {
    if (charCodes is JSArray) {
      // Type promotion doesn't work unless the check is `is JSArray<int>`,
      // which is more expensive.
      // TODO(41383): Optimize `is JSArray<int>` rather than do weird 'casts'.
      JSArray array = JS('JSArray', '#', charCodes);
      return _stringFromJSArray(array, start, end);
    }
    if (charCodes is NativeUint8List) {
      return _stringFromUint8List(charCodes, start, end);
    }
    return _stringFromIterable(charCodes, start, end);
  }
```
The special cases are exactly what you'd expect.
We could probably accept `NativeUint16List` too, without needing any validation.

Using a JS native operation which does the right thing, even if it throws a different error, should be fine. The `String.fromCharCodes` method doesn't specify which error it throws, and we do not consider it a breaking change to change the behavior of code which throws an `Error`.

**Comment by rakudrama** [comment]
@lrhn You present some interesting ideas for how to deal with the truncation-happy `skip` and `take` methods.
It is not quite right since `start` can be equal to `charCodes.length`, resulting in an empty string - example `String.fromCharCodes(UnmodifiableListView([1]), 1)` - would erroneously signal an error due to `list.isEmpty`.

This might be better expressed as finding a `sublist` of a general `Iterable`.

**Comment by lrhn** [comment]
Hmm, good point. If `start == charCodes.length && end == start`, then it's valid.
It should probably just be `var count = charCodes.take(start).length;`. If that is actually `== start`, we're OK.

**Comment by rakudrama** [comment]
I had come to a similar conclusion for `end == start`.

What I am struggling with is the path where `start == charCodes.length` and `end == null`.
This should return an empty string.
Then you get an empty list which is indistinguishable from `start > charCodes.length`.

We can handle `start == 0 && end == null` specially, leaving `start > 0 && end == null`.

```dart
   if (end == null) {
     if (start == 0) {
       var list = charCodes.toList();
       if (list is! JSArray) list = [...list]; // Should never happen, but just to be sure.
        return Primitives.stringFromCharCodes(list); // Takes an entire JSArray
     }
     // start > 0
     sliceIterable = sliceIterable.skip(start - 1);
     var list = sliceIterable.toList();
     if (list is! JSArray) list = [...list]; // Should never happen, but just to be sure.
     if (list.isEmpty) {
       // Second iteration here is bad!
       throw RangeError.range(start, 0, charCodes.length, "start");
     }
     list.removeAt(0);
     return Primitives.stringFromCharCodes(list); // Takes an entire JSArray
   }
 }
```
As written above, a `MappedListIterable` will call the map function for an extra element, which we have to remove.
(The low-level API takes an entire list for efficiency reasons, and we prefer not to create a sublist copy of our local copy).

I think I would prefer this:
```dart
     // start > 0
     sliceIterable = sliceIterable.skip(start - 1);
     if (sliceIterable.isEmpty) {
       // Second iteration here is bad! Is there a less-specific version of RangeError that is appropriate?
       throw RangeError.range(start, 0, charCodes.length, "start");
     }
     var list = sliceIterable.skip(1).toList();
     if (list is! JSArray) list = [...list]; // Should never happen, but just to be sure.
     rreturn Primitives.stringFromCharCodes(list); // Takes an entire JSArray
```
If we change the test to `sliceIterable.isEmpty`, a `WhereIterable` might scan the predicate over the same region to answer `.isEmpty` and then `.skip(1)`. But we create a JSArray of the correct size.
