### ISSUE TITLE
[dart2js] global analysis performance: hash map lookups

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#50258]
We identified that hashmap lookups during our global inference take a large (~7%) time in the CPU profile. We think this is likely due to hash collisions given the large volume of entities (~900K in a large internal application).

The entities are indexed based on the indexable element maps already, so we can either:
* improve the hashing
* switch to a flat array to lookup values by index, rather than hash

@fishythefish started looking into this.

**Comment by ktprime** [comment]
may new c++ flat hash map [benchmark](https://martin.ankerl.com/2022/08/27/hashmap-bench-01/) https://martin.ankerl.com/2022/08/27/hashmap-bench-01/

**Comment by rakudrama** [comment]
>  We think this is likely due to hash collisions given the large volume of entities (~900K in a large internal application).

Is there some data that supports the hypothesis the lookups have hash collisions as opposed to there simply being very many lookups? The current hashCode is `index*7 + N`, perhaps multiplying by different constants that are further from a power of two would help.

**Comment by sigmundch** [comment]
Yes, two data points:
- the profiles showed [_getValueOrData][1] really hot (can't remember the % now, unfortunately). @mkustermann highlighted for us that this method most expensive piece is probing/rehashing. I can't recall if he observed that the trace samples were within the rehashing loop, or if this was just a theory.
- @fishythefish created a [CL that swaps to use a list representation][2], and they observed significant wins in CPU time (8% wins)

During our sync last week with the VM team, we also discussed one more possibility: to not use our own hashcode anymore. They reminded us that we added our own hashCode methods at a time when the default Object.hashCode wasn't good enough, but none of us could remember if this was one of those. @fishythefish and I were brainstorming about it, and we noticed that these objects are already canonicalized and don't implement `==`, so we thought we may not need to use a custom hashCode anymore for the element map. If so, removing `hashCode` could be the alternative approach to try here.

I don't know if @fishythefish ended up exploring that yet. My recollection is that they were evolving the CL swapping the representation. Their goal was to still offer a Map-like abstraction (possibly based on element-map) instead, but with the list perf characteristics. 

[1]: https://github.com/dart-lang/sdk/blob/3afb674e521f08fdbef330d0556fd365df6e963f/sdk/lib/_internal/vm_shared/lib/compact_hash.dart#L574
[2]: https://dart-review.googlesource.com/c/sdk/+/264500

**Comment by fishythefish** [comment]
https://dart-review.git.corp.google.com/c/sdk/+/268364 removes the custom `hashCode` implementations on indexed entities. I took some measurements compiling a large program 50 times. This CL saves about 10s (out of ~330s), but I took this measurement prior to https://dart-review.git.corp.google.com/c/sdk/+/268166 landing. With that change included, the code indexing into the map isn't as hot, so the improvement drops to only a couple seconds in the sample I took.

Nevertheless, I'm going to go ahead and land the change. The entities are canonicalized, they don't have a custom `operator ==`, and we don't seem to rely on `hashCode` being a linear function of the index, so I don't see any benefit in keeping the extra code around. The default implementation is also less likely to accidentally have collisions/poor distribution, and we can relieve ourselves of the maintenance burden of fiddling with the constants.

**Comment by mraleph** [comment]
@fishythefish would it be possible for you to run another benchmark with the following change (without [dart-review.git.corp.google.com/c/sdk/+/268166](https://dart-review.git.corp.google.com/c/sdk/+/268166) if possible):

```dart
diff --git a/runtime/vm/compiler/asm_intrinsifier_x64.cc b/runtime/vm/compiler/asm_intrinsifier_x64.cc
index bba1c3a8d76..c01ef2dd0bd 100644
--- a/runtime/vm/compiler/asm_intrinsifier_x64.cc
+++ b/runtime/vm/compiler/asm_intrinsifier_x64.cc
@@ -1432,7 +1432,7 @@ void AsmIntrinsifier::Object_getHash(Assembler* assembler,
   __ imulq(RCX, Immediate(0xffffda61));  // A
   __ addq(RCX, RBX);                     // new_state = (A* state_lo) + state_hi
   __ movq(Address(THR, target::Thread::random_offset()), RCX);
-  __ andq(RCX, Immediate(0x3fffffff));
+  __ andq(RCX, Immediate(0x00ffffff));
   __ cmpl(RCX, Immediate(0));
   __ j(EQUAL, &not_yet_computed);
 
diff --git a/runtime/vm/object.cc b/runtime/vm/object.cc
index 10554d0d62b..3fe94f43e7f 100644
--- a/runtime/vm/object.cc
+++ b/runtime/vm/object.cc
@@ -19352,7 +19352,7 @@ IntegerPtr Instance::IdentityHashCode(Thread* thread) const {
       hash = ((uval >> 32) ^ (uval)) & kSmiMax;
     } else {
       do {
-        hash = thread->random()->NextUInt32() & 0x3FFFFFFF;
+        hash = thread->random()->NextUInt32() & 0x00FFFFFF;
       } while (hash == 0);
     }
 ```

I am looking at the way to assess potential performance issues from going to 24 bit hash identity codes

**Comment by fishythefish** [comment]
@mraleph Sure, I can do that. Did you want the results with the default `hashCode` implementation, or the custom one I just deleted?

**Comment by sigmundch** [comment]
I think the patched logic only affects the default `hashCode`, so my guess is that he is interested in the result with the default implementation.

**Comment by fishythefish** [comment]
Makes sense, just wanted to check. :)

All of these numbers are from sampling 50 runs of dart2js phase 2 on the same large application without https://dart-review.git.corp.google.com/c/sdk/+/268166:

| | min | max | median | mean |
| - | - | - | - | - |
| Original | 278s | 427s | 333.5s | 331.8s |
| Deleted `hashCode` | 274s | 404s | 323s | 322.6s |
| Deleted `hashCode` + VM patch | 294s | 482s | 338s | 348.9s |

The VM patch does seem to be a noticeable performance regression.

**Comment by mraleph** [comment]
Thanks a lot @fishythefish! 

/cc @rmacnak-google this might be an interesting data point for [your CL](https://dart-review.git.corp.google.com/c/sdk/+/267245), it seems going to 24-bits hashes could be a noticeable perf impact on applications that heavily reliant on identity `hashCode`.

**Comment by sigmundch** [comment]
I believe we can close this now as obsolete, right @fishythefish ?

**Comment by fishythefish** [comment]
Yup, https://dart-review.git.corp.google.com/c/sdk/+/268364 landed, and I don't think there's any work left to do on our side.
