### ISSUE TITLE
Analyzer incorrectly reports `this` as an `unidentified_identifier` if followed by an interpolation

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#50263]
For example:

```dart
class A {
  void f() {
    var foo = '';
    print('$this$foo');
  }
}
```

reports a diagnostic on `$this`.

![image](https://user-images.githubusercontent.com/67586/197057031-28596e32-93ce-44e4-9f7b-818060634b36.png)

FWIW, this is blocking a linter roll into the SDK: https://dart-review.googlesource.com/c/sdk/+/264961

**Comment by bwilkerson** [comment]
I'm not sure I'd consider this a P1, but that said, there's a slightly shorter test case:
```
class C {
  void m() {
    print('$this$this');
  }
}
```
The first use is flagged but the second isn't.

In case it's useful, the dump of the relevant portion of the AST for the above code is
```
┊   ┊   ┊   ┊   ┊   ┊   ┊   ArgumentListImpl [32..45]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        static parameter types = [Object? object]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   StringInterpolationImpl [33..44]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        static type = String
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   InterpolationStringImpl [33..33]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   InterpolationExpressionImpl [34..38]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   SimpleIdentifierImpl [35..38]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name = this
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        static type = dynamic
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   InterpolationStringImpl [39..38]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   InterpolationExpressionImpl [39..43]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ThisExpressionImpl [40..43]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        static type = C
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   InterpolationStringImpl [44..44]
```

The first use is not recognized as a `this` expression while the second one is.

**Comment by pq** [comment]
> I'm not sure I'd consider this a P1

Fair.  I'd rather it not get lost though since it's blocking the linter roll (which will take a while to get unblocked even once this lands since it needs to get to flutter before I can update flutter to be prepared for the new linter 😬).

Is there a tag I can apply that communicates that this is blocking something downstream?

**Comment by bwilkerson** [comment]
Not that I know of. I'll note that I wasn't aware that this issue is blocking a roll when I said that. Given what I know now, I'd mark this a P1 too.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/265083

1. I am not sure if the test can ideally be in the analyzer, or be better in `_fe_analyzer_shared`. I don't know how to execute (or write expectations of ) `CFE` tests.

2. Could also the previous condition in the proposed change `identical(next, $_)` be removed? As the underscore is not separate from the lexeme I think, but that could be another change.

**Comment by pq** [comment]
Thanks so much for jumping on this @asashour.  Much appreciated!
