### ISSUE TITLE
wasm module does not work after binaryen

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#50268]
I have tried compiling one of our protobuf benchmarks to Wasm GC out of benchmarking curiosity using instructions provided by @osa1 

```console
$ git clone https://github.com/google/protobuf.dart.git
$ cd protobuf.dart/benchmarks
$ dart pub get 
$ tool/compile_protos.sh
$ $DART_SDK_SRC/sdk/bin/dart2wasm bin/deep_copy.dart out/deep_copy.wasm
```

Resulting module runs fine on V8 (10.9.48):

```console
$ ~/.jsvu/v8 --experimental-wasm-gc --wasm-gc-js-interop --experimental-wasm-stack-switching --experimental-wasm-type-reflection $DART_SDK_SRC/pkg/dart2wasm/bin/run_wasm.js -- out/deep_copy.wasm
```

But if I try TOT `wasm-opt` on it then any optimization level above `-O1` breaks it:

```console
$ ~/src/third_party/binaryen/bin/wasm-opt -all --nominal -O2 -o out/deep_copy.opt.wasm out/deep_copy.wasm
$ ~/.jsvu/v8 --experimental-wasm-gc --wasm-gc-js-interop --experimental-wasm-stack-switching --experimental-wasm-type-reflection $HOME/src/dart/sdk/pkg/dart2wasm/bin/run
_wasm.js -- out/deep_copy.opt.wasm
/usr/local/google/home/vegorov/src/dart/sdk/pkg/dart2wasm/bin/run_wasm.js:23: CompileError: WebAssembly.Module(): Compiling function #333 failed: type error in branch[0] (expected (ref any), got anyref) @+176222
        return new WebAssembly.Module(bytes);
               ^
CompileError: WebAssembly.Module(): Compiling function #333 failed: type error in branch[0] (expected (ref any), got anyref) @+176222
    at compile (/usr/local/google/home/vegorov/src/dart/sdk/pkg/dart2wasm/bin/run_wasm.js:23:16)
    at main (/usr/local/google/home/vegorov/src/dart/sdk/pkg/dart2wasm/bin/run_wasm.js:41:68)

1 pending unhandled Promise rejection(s) detected.
``` 

It's unclear to me where the bug is exactly. I am uploading `deep_copy.wasm` for convenience.

[deep_copy.wasm.zip](https://github.com/dart-lang/sdk/files/9837631/deep_copy.wasm.zip)

/cc @askeksa-google @osa1 @joshualitt @eyebrowsoffire 
/cc @kripken

**Comment by osa1** [comment]
This seems like a binaryen bug because it fails to validate the module it generates.

Original module runs fine:

```
d8 --experimental-wasm-gc --wasm-gc-js-interop --experimental-wasm-stack-switching --experimental-wasm-type-reflection ~/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js -- query_encode_binary.wasm
protobuf_query_encode_binary(RunTimeRaw): 13840 us.
```

wasm-opt validates the original module:

```
wasm-opt -all --nominal --name-types -S query_encode_binary.wasm -o query_encode_binary_opt.wat
```

Optimize the original module with wasm-opt:

```
wasm-opt -all --nominal --name-types query_encode_binary.wasm -o query_encode_binary_opt.wasm -O
```

wasm-opt fails to validate the resulting module:

```
wasm-opt -all --nominal --name-types -S query_encode_binary_opt.wasm -o query_encode_binary_opt.wat
[wasm-validator error in function 290] break type must be a subtype of the target block type, on
(block $label$62 (result (ref any))
 (br $label$61
  (ref.test_static ${mut:i32}
   (br_on_non_data $label$62
    (extern.internalize
     (local.get $0)
    )
   )
  )
 )
)
Fatal: error validating input
```

**Comment by kripken** [comment]
I can confirm this is hitting a binaryen bug. I'll investigate, thanks for the report!

**Comment by kripken** [comment]
There are at least two issues here, see the above links.

First, the wasm spec has an [apparent bug](https://github.com/WebAssembly/gc/pull/330). Until that is fixed and V8 is updated to that, the only way to work in V8 is to disable the `gto` pass. That is run by default in `-O2` and above. It can be manually disabled by [removing the relevant line](https://github.com/WebAssembly/binaryen/blob/884fe9bcee0a7aa10a427d76bd317bb136258dc6/src/passes/pass.cpp#L585). You can also use `-O1` which does not run it (but also does not run a lot of other useful stuff like inlining and devirtualization).

Second, the Binaryen optimizer had a bug with the recently introduced internalize/externalize instructions, see [the PR](https://github.com/WebAssembly/binaryen/pull/5175) for a fix.

With `gto` disabled and that PR included, I can optimize `deep_copy.wasm` at various opt levels without errors in Binaryen or V8.

@osa1 I can't reproduce the error you refer to on `deep_copy.wasm`. Where can I get that `query_encode_binary.wasm` file that you mention?

**Comment by mraleph** [comment]
@kripken I see that the spec is actually correct - which means V8 does not implement it properly? Is there a monorail bug for this or should I file one?

**Comment by osa1** [comment]
@kripken `query_encode_binary.wasm` attached, though it seems like after your PR in binaryen, binaryen now validates the optimized version of it.

[query_encode_binary.zip](https://github.com/dart-lang/sdk/files/9851094/query_encode_binary.zip)

**Comment by kripken** [comment]
@mraleph I'm not aware if there's a V8 bug filed or not - @jakobkummerow ?

@osa1 Thanks, I can reproduce the "break type" error with that file. I'll look into it.

**Comment by kripken** [comment]
@osa1 Ok, good, I am seeing the same as you - that was the same issue as fixed by that PR, and things work properly after it landed.

**Comment by mraleph** [comment]
Then I think we are all good! Thanks @kripken @jakobkummerow!

I can run benchmarks now. They are rather slow (12x/6x slower than native or 2x/6x slower than JS, depending on the benchmark), but that's just more work for dart2wasm team then :)

**Comment by kripken** [comment]
Let me know if you see anything we can optimize on the binaryen side!
