### ISSUE TITLE
Returning void is indeed not void

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#50274]
Reproduce:

```dart
void main() {
  void f() => 42;
  print(f() as dynamic);
  exit(0);
}
```

Output: 42. Expect to be never or throw or etc.

This is a low-priority issue, just want to report it here in case someone else faces it :)

**Comment by lrhn** [comment]
That is how Dart currently defines `void`. It's just `Object?` with a static requirement that you don't use the value.
There are ways around that requirement, casting to `dynamic` being one.

**Comment by fzyzcjy** [comment]
Interesting, never knew that before. Thanks!
