### ISSUE TITLE
Dart Language Server seems to ignore `dart.lineLength` setting

### ISSUE THREAD

**Issue by sebthom** [dart-lang/sdk#50272]
I am working on an integration of the Dart language server with Eclipse via the [LSP4E](https://github.com/eclipse/lsp4e) project.

According the documentation at https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/tool/lsp_spec/README.md#client-workspace-configuration it should be possible to configure the line length used by the SDK formatter via the `dart.lineLength` option as part of the JSON response to an `workspace/configuration` request.

In my case however the setting seems to be ignored by the Dart LS.
When the Dart LS requests the workspace config via
```json
{"id":1,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///D:/workspaces/projects/dart-hotreloader","section":"dart"},{"section":"dart"}]}}
```
I tried to send back the line length configuration using
```json
{"id":1,"jsonrpc":"2.0","result":[{"dart":{"enableSdkFormatter":true,"lineLength":120}}]}
```
as well as using
```json
{"id":1,"jsonrpc":"2.0","result":[{"dart.enableSdkFormatter":true,"dart.lineLength":120}]}
```
neither seems to work.

When the client requests formatting using
```json
{"id":"11","jsonrpc":"2.0","method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///D:/workspaces/projects/dart-hotreloader/lib/hotreloader.dart"},"options":{"tabSize":4,"insertSpaces":false}}}
```
The dart file is always formatted according max line length 80.

I am using `Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "windows_x64"`

Any ideas/suggests are highly appreciated.

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
@sebthom the response being sent doesn't appear valid for the request. The request from the server is asking for _two_ sets of configuration, the `dart` config for the `dart-hotreloader` folder, as the global `dart` config:

```js
"items": [
	{ // item 1
		"scopeUri": "file:///D:/workspaces/projects/dart-hotreloader",
		"section": "dart"
	},
	{ // item 2
		"section": "dart"
	}
]
```

However the response only contains one lot:

```js
"result": [
	{ // item 1
		"dart.enableSdkFormatter": true,
		"dart.lineLength": 120
	}
]
```

Right now, if the number of items in the response doesn't match the request, we make no attempt to understand which is which and just ignore the config. If LSP4E does not support workspaceFolder-scoped config, it should include a `null` for that element:

```js
"result": [
	null, // item 1
	{ // item 2
		"dart.enableSdkFormatter": true,
		"dart.lineLength": 120
	}
]
```

**Comment by sebthom** [comment]
@DanTup thanks for your response. I adjusted my code accordingly but the line length still seems to be ignored. I tried to send three different variations of the JSON, but none worked. The code is still wrapped at 80chars.

```json
{"jsonrpc":"2.0","id":2,"result":[{"dart.enableSdkFormatter":true,"dart.lineLength":120},{"dart.enableSdkFormatter":true,"dart.lineLength":120}]}
{"jsonrpc":"2.0","id":2,"result":[{"dart":{"dart.enableSdkFormatter":true,"dart.lineLength":120}},{"dart":{"dart.enableSdkFormatter":true,"dart.lineLength":120}}]}
{"jsonrpc":"2.0","id":2,"result":[{"dart":{"enableSdkFormatter":true,"lineLength":120}},{"dart":{"enableSdkFormatter":true,"lineLength":120}}]}
```

any ideas? is there any way to enable a debug log in the dart language server that shows what it does the the response it received?

**Comment by sebthom** [comment]
I got it working by dropping the `dart.` prefix at all in the json response:
```json
{"jsonrpc":"2.0","id":2,"result":[{"enableSdkFormatter":true,"lineLength":120},{"enableSdkFormatter":true,"lineLength":120}]}
```
The documentation at https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/tool/lsp_spec/README.md#client-workspace-configuration  is a bit misleading as it lists all configuration settings with the `dart.` prefix.
