### ISSUE TITLE
Know memory layout / size of a class for debug purpose?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#50287]
## Background

When working on https://github.com/flutter/flutter/pull/113927, I find it weird: 

```dart
// case A
class AnimatedController {
  String? debugLabel;
  String toString() => ...debugLabel...;
}
void main() { ... use AnimatedController and toString ... }

// case B
class AnimatedController {
  // no debugLabel field at all
}
```

In both cases, my (draft) experiment surprisingly says a profile flutter build (dart aot) yields the *same* memory usage! I originally thought removing one field that is used must reduce memory usage.

## Problem

May I know memory layout / size of a class for debug purpose? For example, if I can see what is the memory layout of `AnimatedController`, then I can very clearly know what happens and why memory is not reduced.

**Comment by mraleph** [comment]
You can use `--print-object-layout-to=file.json` for `gen_snapshot`. This will dump class layouts in JSON format to a file. In Flutter tooling you can pass this flag through `--extra-gen-snapshot-options=...`. 

Dart objects are currently aligned by two word sizes, so removing a field does not always reduce the size of the object.

**Comment by fzyzcjy** [comment]
@mraleph Hmm my experiment shows different result about this:

> the field is also effectively unused if it always contains the same constant value

The result is:

* v1: 2.51GB
* v2: 4.00GB

But we know secondField is always null (always contains the same constant null)

run using: dart compile exe a.dart && ./a.exe. On a 64bit mac.

```dart
class C {
  int? mainField;
  int? secondField;

  int get hashCode => mainField.hashCode; // v1
// int get hashCode => mainField.hashCode ^ secondField.hashCode; // v2
}

Future<void> main() async {
  print('start');
  final arr = <C>[];
  for (var i = 0; i < 100000000; ++i) {
    arr.add(C()..mainField = 10);
  }
  print('hash=${Object.hashAll(arr)}');

  print('sleep...');
  await Future<void>.delayed(const Duration(seconds: 10000));
}
```

**Comment by fzyzcjy** [comment]
Or, another almost equivalent experiment:

v1 2.51GB, v2 4.00GB

```dart
class AnimationController {
  int? mainThing;

  // v1
  String toString() => '$mainThing'; // and no field "debuglabel" at all

// v2
// String? debugLabel;
// String toString() => '$mainThing $debugLabel';
}

Future<void> main() async {
  print('start');
  final arr = <AnimationController>[];
  for (var i = 0; i < 100000000; ++i) {
    arr.add(AnimationController()..mainThing = 10);
  }
  print('hash=${Object.hashAll(arr)}');
  print('tostring=${arr.first.toString()}');

  print('sleep...');
  await Future<void>.delayed(const Duration(seconds: 10000));
}

**Comment by fzyzcjy** [comment]
Btw thank you and I find out how to make that PR experiment work (add two dummy fields to make it cross 16B alignment)
