### ISSUE TITLE
[dart_library.js] pass app name to module loader function

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#50297]
Parent: https://github.com/dart-lang/webdev/issues/1769

dart loader function built by DDC needs to. be aware of the app name to support multi-app scenario. 

- pass current app name as a last parameter to the loader functions generated by DDC

Related: https://github.com/dart-lang/sdk/issues/50296

**Comment by bkonyi** [comment]
This work has been deprioritized, so I'm going to close this for now.
