### ISSUE TITLE
[DDC] Make expression evaluation interface less fragile for multi apps

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#50299]
Parent: https://github.com/dart-lang/webdev/issues/1769

Currently expression compiler returns a function that passes `appName$t` to the library load function. The value, the current app name, is known during debugging the app and is passed to the generated code before evaluating the expression. This creates a few problems:

- DDC cannot change the `appName$t` name (causing potential name clashes)
- DWDS  assumes the name to be `appName$t` (making the interface between the compiler and the debugger too constrained)

Suggestion: make the API design cleaner by

- making DDC wrap the generated function in `lambda(x)` where `x` is a temporary app name passed to the library loader calls inside generated code
- making DWDS pass the actual app name as a parameter during evaluation.

Parent: https://github.com/dart-lang/sdk/issues/50296

**Comment by bkonyi** [comment]
This work has been deprioritized, so I'm going to close this for now.
