### ISSUE TITLE
[parser] Remove `LIBRARY_DIRECTIVE_NOT_FIRST`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50291]
We should investigate removing `ParserErrorCode.LIBRARY_DIRECTIVE_NOT_FIRST` from the Dart SDK.

> Should we (or someone) figure out where the error comes from, and stop it at the source instead?

https://dart-review.googlesource.com/c/sdk/+/265321/3/tools/verify_docs/bin/verify_docs.dart

**Comment by dcharkes** [comment]
A quick look through the code base reveals it is also used for signalling other things than annotations that come before the `library` keyword.

The implementation is here with `messageLibraryDirectiveNotFirst`:

https://github.com/dart-lang/sdk/blob/bd75b2c9e1ae5950b959eed856bcdce40253bc47/pkg/_fe_analyzer_shared/lib/src/parser/directive_context.dart#L58-L71

It would be a trivial change to remove all references to `LibraryDirectiveNotFirst` and `LIBRARY_DIRECTIVE_NOT_FIRST`, but that would also remove the "recoverable errors" for other things before the `library` keyword.

The authors of `LIBRARY_DIRECTIVE_NOT_FIRST` are no longer on the project, cc people who have touched it afterwards @bwilkerson @jensjoha @srawlins @stereotype441 Could you give us some more context on "recoverable parse errors"? It sounds like `class` before `library` is a recoverable error. But an annotation before `library` should not be an error at all.

**Comment by jensjoha** [comment]
Can we extract the error case?
From @mraleph's comment on the issue it seems that the error is legit.

And sure, we could often remove errors because our recovery is (sometimes) good. But if the language specs says something is an error we kind of have to issue the error. Again the code would be good.

**Comment by mraleph** [comment]
I think this is really a misunderstanding of what is happening in the code. 

I suspect, based on the cursory glance through the `verify_docs.dart`, that the code being analysed ends up looking like this: 

```
import 'dart:ffi';

@Foo()
library x;

...
```

The error is completely warranted in this case. I think the comment simply needs to be rewritten like so:

```dart
  /// ```dart template:none
  /// @Asset('package:a/a.dart')
  /// library a;
  ///
  /// import 'dart:ffi';
  /// 
  /// @Native<Int64 Function(Int64, Int64)>()
  /// external int sum(int a, int b);
  /// ```
```

**Comment by dcharkes** [comment]
@mraleph very well spotted! 😲 

And it's not erroring on an annotation on `library`.
