### ISSUE TITLE
[DDC] pass app name to emitDebugEvent in developer.postEvent

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#50298]
Parent: https://github.com/dart-lang/webdev/issues/1769

Developer.postEvent needs to be aware of the current app to communicate events to DWDS. Read app name stored in the library loader function produced by DDC  pass it to the API used to communicate with DWDS.

Related : https://github.com/dart-lang/sdk/issues/50296

**Comment by bkonyi** [comment]
This work has been deprioritized, so I'm going to close this for now.
