### ISSUE TITLE
[CP] Please cherry pick c55a2886c445cd9d2cdbff05c1b9df0b3407e14d into the stable channel

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#50295]
### Commit(s) to merge

c55a2886c445cd9d2cdbff05c1b9df0b3407e14d

### Target

stable

### Issue Description

Flutter app crashes randomly when hot reloading, this happens on all platforms

### What is the fix

Do not issue breakpoint resolved events without an isolate

### Why cherry-pick

This issue is impacting the work flow of a flutter user enormously. Normally it would be fine to use another channel during development but there are a lot of depreciation changes coming up and it would be hard to downgrade to stable to make a release.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/113540

**Comment by whesse** [comment]
This will be merged to stable 2.18.4 once it is approved. We have a stable hotfix scheduled release on Wed Nov 2, so this should be approved today if we want to build stable 2.18.4 in time to release Dart and Flutter on Nov 2.

**Comment by a-siva** [comment]
//cc @vsm @mit-mit @itsjustkevin

**Comment by vsmenon** [comment]
lgtm
