### ISSUE TITLE
[DDC] Pass app name to dart_library.import in during expression evaluation

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#50296]
Parent: https://github.com/dart-lang/webdev/issues/1769

`dart_library.import` needs to be aware of what app the current library is loaded for. 

- store the app name in the library function so debugger can read it at runtime
  - dart_library.js will pass the app name to the library loader function generated by DDC
     https://github.com/dart-lang/sdk/issues/50297
- pass app name to `dart_library.import` during module building

**Comment by bkonyi** [comment]
This work has been deprioritized, so I'm going to close this for now.
