### ISSUE TITLE
RegExp hang

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#50301]
Dunno why but this hangs: [test.dart.txt](https://github.com/flutter/flutter/files/9864813/test.dart.txt)

That is, `pattern.allMatches(input).toList()` for a version of `pattern` that is a huge absurd machine-generated RegExp and a version of `input` that contains a Burmese dictionary.

**Comment by lrhn** [comment]
It's *probably* the RegExp.

A very quick look at the beginning shows (prettified):
```regex
^(
  (?:[-;@#<!.\\"/* ]*
     (?:REM[-;@#<!.\\"/* ]*)?
     [-;@#<!.\"/*]+
  )?)
  ( *)
  (?:BSD 2
```
That alone can spend quadratic time matching a line of `-----------------------------------------------------------`.
The first `[- ...]*` starts by matching everything. Then the "REM" doesn't occur, but that's OK, it's inside a `?`.
Then the second `[-....]+` matches nothing. No space. Next character is not `B`, so we backtrack.
That goes back to the first `[-...]*` which drops back by one `-`, then the second `[-...]+` matches that `-` and we continue not finding `B`. This repeats until we have failed to find `B` N-squared times for N `-`s.

The continuation is actually
```regex
( *)
  (?:BSD 2-Clause License \(http://www.opensource.org/licenses/bsd-license.php\))? *
```
so the `BSD`-part itself is also optional and the ` *` surrounding it can do the same quadratic matching of repeated spaces (which is probably less likely to happen in practice).
I'm guessing that if we continue deciphering the regexp we'll finde more polynomial backtracking issues.

I gave up understanding the rest of the RegExp, though. I'd rather see the code generating it, it's likely to be more readable (RegExp, like Perl, are write-only code :wink:).
Without a textual description of what a RegExp is _intended_ to do, it's pretty much impossible to understand it, or check that it does what it should. Definitely not self-documenting.

I'd recommend just not using a RegExp for something of this magnitude. They're not magical speed-demons that always beat properly written code, and for complex things, they're also nigh impossible to check for correctness.

**Comment by lrhn** [comment]
Looking at it more, it seems the RegExp tries to recognize the 2-clause BSD license in a comment, no matter what comment syntax is used, or how it's line-broken, or how many spaces are put between words.
(Which prompts the question "Why?".)

It _almost_ works on this input, which contains a *3-clause* BSD license text. That means it probably matches up to the second clause, then fails.
Then it tries one gazillion other ways to backtrack and match again (probably mostly by rearranging how the whitespace is matched), which it can because the RegExp is ambiguous in several ways, and every time it still fails at the third clause and tries another backtracking.
That's exactly the kind of situation where RegExps perform horribly.
It'll probably complete eventually, if not in this universe's life time, then the next.

(Cutting away the Burmese dictionary and header comment doesn't make any visible difference, just the 3-clause BSD license by itself is enough.)

I'd probably just do something primitive like replacing every non-releveant character sequence with spaces:
```dart
void main() {
  var normalized = input.replaceAll(normWordsRE, " ");
  var matches = normalized.contains(bsd2Words);
}

final normWordsRE = RegExp(r'(?:^ *(?:REM\b|/+)|[^a-zA-Z\d.,/:;()"])+');

const bsd2Words =
    'Redistribution and use in source and binary forms, with or without modification, '
    'are permitted provided that the following conditions are met: '
    'Redistributions of source code must retain the above copyright notice, this '
    'list of conditions and the following disclaimer. '
    'Redistributions in binary form must reproduce the above copyright notice, this '
    'list of conditions and the following disclaimer in the documentation and/or '
    'other materials provided with the distribution. '
    'THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND '
    'ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED '
    'WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE '
    'DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR '
    'ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES '
    '(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; '
    'LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON '
    'ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT '
    '(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS '
    'SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.';
```
It's not precise, but it does require the correct word in the correct order with no other letters or digits mixed in between them.

**Comment by Hixie** [comment]
To be clear I totally agree that this is ridiculous code. It's from the Flutter engine license script (see https://github.com/flutter/engine/blob/main/tools/licenses/lib/patterns.dart and files in that directory; IIRC the precise pattern in this test is from https://github.com/flutter/engine/blob/main/tools/licenses/lib/patterns.dart#L1352) and is absolutely the wrong way to do this. The approach has not scaled. At some point I want to change the code to first tokenize the source files and then run the patterns on them that way.

That said, this seems like a weird pathological case. This regular expression (with `[\r\n]+` changed to `\n+` in one place) is in production today, and is compared against thousands of files regularly. I think the precise input file is not being tested against it today, but it's not that different from other files that are. It's disturbing to see such a drastic difference in performance.

**Comment by Hixie** [comment]
(If it helps, you can think of this as a security report highlighting a potential DOS attack. :-) )

**Comment by lrhn** [comment]
Using user-provided RegExps on user-provided input (or any input, really) should generally be considered a DOS risk.

Having a complex RegExp applied to arbitrary user input is also a risk. The RegExp should be vetted and tested carefully before being released to the world.

It's not something we can really fix while maintaining the ECMAScript RegExp behavior. The backtracking behavior, and order, is embedded in the specification. There might be some situations where a RegExp compiler can determine that if something fails once, there is no need to go back and try other approaches, but it's not generally solvable (it is equivalent to rewriting the RegExp into another one which matches the same thing, and RegExp equivalence in general is NP-space complete. And that's for real regular expressions, not the expanded ones with back-references which makes the Dart `RegExp` not even context free).

All in all, some RegExps being able to spend inordinate amounts of time on some inputs is a known problem with no known practical solution, so this is "working as designed".
