### ISSUE TITLE
[analyzer] hint for `as` of `null` variable

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50309]
```dart
void as() {
  int? i;
  i as double;
}
```

Should there be a hint, similar to [not_assigned_potentially_non_nullable_local_variable](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=not_assigned_potentially_non_nullable_local_variable#not_assigned_potentially_non_nullable_local_variable). As `a` is null and the casting would always fail.

Please see https://github.com/dart-lang/sdk/issues/50275#issuecomment-1288059725

**Comment by srawlins** [comment]
We might be able to do this; I think it would have to be done in the Flow Analysis system, which might mean it would need to be done as a language feature (tracking that something's 'promoted' type is `Null`, I think?)

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/266400

I am not sure if we can put the logic in `resolver` or in 

https://github.com/dart-lang/sdk/blob/98afb38b6aeb510fcfa67d5cd82ab456f57d06dc/pkg/analyzer/lib/src/error/best_practices_verifier.dart#L350-L363

as the hint is similar to `CAST_FROM_NULL_ALWAYS_FAILS`. `BestPracticesVerifier` doesn't have `flowAnalysis`.

**Comment by bwilkerson** [comment]
As has been discussed elsewhere, I think this needs to be implemented based on definite assignment analysis, which implies that the hint has to be generated in the resolver where we have access to the `FlowAnalysis`.
