### ISSUE TITLE
[analyzer] `dead code` for conditional access to a `null` nullable variable

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50308]
```dart
class A {
  int? f;
  void m() {}
}

void test() {
  A? a;
  a?.m(); // here
  a?.f;   // and here
}
```

Should the method invocation and field access be triggered as `dead code` since `a` is null in this case?

**Comment by srawlins** [comment]
We could probably do that. This seems related to https://github.com/dart-lang/language/issues/1959.

The title says `null` field, but do you mean `null` instance variable? `a` is not a field.

**Comment by bwilkerson** [comment]
Am I mistaken, or would such a lint effectively require local data flow analysis? If so, I'm not sure we want to take on the cost of maintaining such a feature. If there's a heuristic we could use, would it catch enough cases to be valuable?

**Comment by srawlins** [comment]
It would require the definite assignment stuff in flow analysis, which I think would not need to be altered? Given an expression `a?.b`, if we can ask if `a` is definitely _unassigned_, then we could report.

**Comment by bwilkerson** [comment]
Excellent. I think that means that we'll need to check in the resolver rather than afterward, but I think that's where most of the dead code analysis happens anyway.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/266381

**Comment by srawlins** [comment]
This fix was reverted.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/266920
