### ISSUE TITLE
[gardening] dartdevk-checked-linux-release-firefox bot is failing

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#50324]
https://dart-ci.firebaseapp.com/#showLatestFailures=true&configurations=dartdevk-checked-linux-release-firefox

@scheglov your changes are mentioned, could you please check if they are related or if the test failure need to be approved?

**Comment by scheglov** [comment]
I don't think this is because of any of my changes.
It looks like something from `dartdevc`.

**Comment by rileyporter** [comment]
Test failures have been approved with a tracking bug for the underlying issue: #50362
