### ISSUE TITLE
[gardening] dartdevk-*-linux-release-chrome bots are failing

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#50323]
https://dart-ci.firebaseapp.com/#showLatestFailures=true&configurations=dartdevk-strong-linux-release-chrome,dartdevk-weak-linux-release-chrome

@kallentu There is an unapproved failure after you changes (see link above) - could you please check if they are related?

**Comment by kallentu** [comment]
This does not seem related to my change. Asked @nshahan about this and AFAIK it's most likely a flakey test that turned failing.
