### ISSUE TITLE
[gardening] dart2js-mac-chrome test bot failure

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#50322]
https://dart-ci.firebaseapp.com/#showLatestFailures=true&configurations=dart2js-mac-chrome,dart2js-mac-chrome-unsound

@srawlins @bwilkerson the failure above shows changes from you, could you please have a look in case the changes are related to the failure?

**Comment by srawlins** [comment]
Yeah I don't see how this could be caused by my commit or Brian's. There are a number of web and dart2js commits just before and just after our commits: https://github.com/dart-lang/sdk/commits/main?after=3aa7a9e2b459587de49c2e77e4d7f68b850a3c07+34&branch=main&qualified_name=refs%2Fheads%2Fmain

**Comment by rileyporter** [comment]
Test failures have been approved with a tracking bug for the underlying issue: #50362
