### ISSUE TITLE
RegExp documentation does not mention DOS risk

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#50321]
Per the conclusion on https://github.com/dart-lang/sdk/issues/50301#issuecomment-1293645935, it is expected that RegExp matches can take arbitrary amounts of time (e.g. hours) when faced with carefully-crafted inputs. Currently the documentation for the RegExp class provides no guidance regarding this risk.

We should add a "Risks" section to the RegExp API docs that discusses the dangers of processing data using user-provided patterns or user-provided inputs, recommended mitigations, suggestions on how to design regular expressions safely, how to test them for such risks, etc.

**Comment by rmacnak-google** [comment]
The default Map and Set implementations are also vulnerable to computational complexity attacks. https://www.kb.cert.org/vuls/id/903934/
