### ISSUE TITLE
[dart2js]  Please document best practices for better transpilation quality 

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#50331]
"[How to improve the transpiled code quality of flutter web build](https://stackoverflow.com/questions/74002995/how-to-improve-the-transpiled-code-quality-of-flutter-web-build)"
I asked this question on:
- StackOverflow: NO answer, and 
- r/FlutterDev: removed (with reason, spam)

The question ~is:
>I [read](https://www.reddit.com/r/FlutterDev/comments/xtklez/would_it_be_possible_to_create_a_more_lightweight/) at r/FlutterDev, 
>> Flutter web strives to mimic the UI including complex animations
>
>So may i ask, what all steps we can take to improve the quality of the transpiled code(html, css, and js) of my web-app project, 
>Aside from, creating widgets with less-to-no animations, etc.
>I know [Dawn](https://pub.dev/packages/dawn).dart, [Jaspr](https://pub.dev/packages/jaspr).dart, etc. But i specifically want to use flutter with html backend,

Thanking you...

**Comment by sigmundch** [comment]
@gintominto5329 - thanks for reaching out. Unfortunately, we don't have a clear answer to give you. We (the Dart team) maintain the language and tools that support many frameworks, but we have less in-depth knowledge about the best practices for building UIs with those frameworks or how to tune them to your needs.

I think reaching out to the flutter community on the mediums above as you have done already, was the right approach. Sorry you haven't heard that much feedback in those channels, though. It is a broad and ambiguous topic, so it's probably hard for the community to provide suggestions. 

I only have two comments to offer at a high-level:
* Consider investigating how to build flutter apps that avoid animations altogether. I doubt the framework will do this kind of work automatically, but it may be possible for you to choose flutter widgets strategically, and only pick some that are cheap and simple, and that don't have animations. I have no experience in this domain, so I don't know if that's possible. Searching for example open-source Flutter Web apps that work well and meet your standards could be a way to discover ways to do this.

* Evaluate whether the canvaskit rendering is part of the cost you are trying to avoid. Note that Flutter web currently provides two rendering engines, one using canvas-kit via wasm, and the other using html. See: https://docs.flutter.dev/development/platform-integration/web/renderers. This will not remove animations for you automatically, so it is quite possible this is not enough for your needs.

*  It is possible that Flutter Web design is not a good match for you. If so, consider exploring other frameworks. It's quite possible that a non-flutter framework is what you are looking for. Within Dart, the community has provided some interesting web-centric frameworks that you can explore (for example, check out https://workiva.github.io/over_react/). I don't have an exhaustive list, so I'd again recommend reaching out to the community for recommendatoins.
