### ISSUE TITLE
Feature request: StringBuffer write to the start of the line.

### ISSUE THREAD

**Issue by Renesanse** [dart-lang/sdk#50330]
I am using StringBuffer often and sometimes I need to write a char to the start of the line. Is It easy to implement?
Maybe something like this:
```dart
final sb = StringBuffer();
sb.write('123', atStart: true);
```

**Comment by lrhn** [comment]
Seems like you need a "StringQueue" where you can add at both ends. (You say "line", a `StringBuffer` can contain multiple lines.)

It's not something we plan to do, but I don't think it's inherently impossible. On the web, it's trivial.
On native, we could change the internal buffer from a list to a (list-)queue. We'd have to prepare the native functions for such an input, but that should be doable. 

I'm just not sure it's worth the effort and extra complexity, though.

I'd recommend you just use a `Queue<String>` to store your content in, then use `queue.join("")` at the end. Won't have `writeln` functionality, so you have to add the newline `"\n"` manually, and you can't write char codes, but for most uses it will work perfectly well.

**Comment by Renesanse** [comment]
ok, thx. "line" is't incorrect, you a right. I meant buffer.
