### ISSUE TITLE
[VM] Hide unsound null safety flag if build requires it

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#50348]
Starting in Dart3.beta, the SDK will have a new build flag to determine whether an SDK supports unsound null safety on any of its commands. When the flag indicates that unsound mode is not supported, then the VM needs to provide an error if a user passes in the --no-sound-null-safety flag.

**Comment by a-siva** [comment]
This CL is blocked on the following

- https://github.com/dart-lang/sdk/issues/50091
- migration of dart2js to sound null safety

**Comment by mit-mit** [comment]
Hi @a-siva what remains that blocks this change?

**Comment by a-siva** [comment]
> Hi @a-siva what remains that blocks this change?

- dart2js fully migrated and the option removed from invocation of dart2js in the SDK builds
- Flutter tools changed to not pass this option in, see https://github.com/flutter/flutter/issues/118810

**Comment by sigmundch** [comment]
FYI - re dart2js - @natebiggs has a CL in progress to update the dart2js invocation to use sound null safety. He is out this week, but we can get a more accurate estimate when he returns next week.

**Comment by a-siva** [comment]
This CL https://dart-review.googlesource.com/c/sdk/+/283981 attempts to add a build time option for removing the unsound null safety flag, currently this fails to build the SDK, once @natebiggs lands the CL to update dart2js I can try building the SDK again.

**Comment by biggs0125** [comment]
I expect to land my CL (https://dart-review.git.corp.google.com/c/sdk/+/280221) early next week. I'm waiting for the equivalent internal change to roll around a bit to make sure nothing comes up.

**Comment by biggs0125** [comment]
I've landed the above change, Dart2JS should now run in sound null safe mode.

**Comment by a-siva** [comment]
> I've landed the above change, Dart2JS should now run in sound null safe mode.

Confirmed that the Dart SDK builds successfully now.

**Comment by a-siva** [comment]
Here is what I learnt about use Flutter's Dart SDK internally from @chingjun 
Flutter's Dart SDK is used in the following scenarios
- to compile a kernel / AOT that needs to be compatible with a prebuilt Flutter Engine (Dart VM)
- to run a prebuilt dill file

Basically all Flutter Dart code internally will be compiled with the frontend_server that is in the downloaded Dart SDK
The --no-sound-null-safety flag is being passed  when calling the kernel_worker and frontend_server as all this code has not been migrated.

This pretty much means we cannot remove the `-no-sound-null-safety flag` from the 'dart compile kernel' or `dart compile  aot-snapshot`  commands in dart cli until all this code is migrated. The Dart VM will have to retain the ability to run unsound null safe code when it reads a dill file that was compiled with that option.

**Comment by a-siva** [comment]
We have decided to not implement this build flag for 3.0 and hence removing the milestone, the option of locking down the no-sound-null-safety option in the compiler has already landed.
