### ISSUE TITLE
Value of type 'Null' can't be assigned to a variable of type 'Null'

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50340]
In dart2wasm I'm patching the `Null` class with this:

```dart
@patch
@pragma("wasm:entry-point")
class Null {
  @pragma("wasm:entry-point")
  static final Null _instance = Null._();

  Null._();
}
```

Which generates this error:

```
../../sdk/sdk/sdk/lib/_internal/wasm/lib/null.dart:11:38: Error: A value of type 'Null' can't be assigned to a variable of type 'Null'.
  static final Null _instance = Null._();
```

If I omit the type in the field, I think the inferred type is correct, at least the analyzer seems to correctly infer it as `Null`. However even with the type omitted it causes strange errors like, for example:

```
class Null {
  ... same as above ...
  
  static Null getInstance() => _instance;
}
```

Error:

```
../../sdk/sdk/sdk/lib/_internal/wasm/lib/null.dart:13:32: Error: A value of type 'Null' can't be returned from a function with return type 'Null'.
  static Null getInstance() => _instance;
```

Full repro (with the updated libraries.yaml): https://github.com/osa1/sdk/tree/null_bug
Build with `./tools/build.py dart2wasm`.

**Comment by srawlins** [comment]
> Which generates this error:

What generates that error? The analyzer or a compiler?

**Comment by osa1** [comment]
Compiler.

**Comment by askeksa-google** [comment]
Problem is that the Dart `Null` type is the type that only contains the `null` value, so we can't actually talk about those fake instances of `Null` in Dart code.

Would it be sufficient for the fake `Null` instance trick to just add the members we want to the `Null` class, create a Wasm struct (of type `#Top`) in a constant global containing the right class ID and identity hash code, and load that instance to substitute for the `null` value in appropriate places?

**Comment by osa1** [comment]
It's probably not worth fixing this as there are workarounds, such as creating an instance in the code generator (rather than in Dart code) as @askeksa-google suggests, or just using another class like `_WasmNull` that behaves like `Null`.
