### ISSUE TITLE
Inference error for a field with an immediately invoked function expression

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#50351]
The analyzer and the CFE seem to disagree about how inference should work in this case. The CFE is also inconsistent between the handling of a field and a local variable with the same expression.

```dart
class C {
  var value = () {
    var value = something();
    if (value == null) {
      throw '';
    }
    var result = value;
    return result;
  }();
}

String? something() => 'something';

void main() {
  print(C().value.length);
                  ^^^^^^ // Error: Property 'length' cannot be accessed on 'String?' because it is potentially null.
}
```

In this code I expect the inferred type for `value` to be `String`, and for there to be no error. If I change `var` to `String`, the program runs without error. If I use this same expression as a local variable, there is no error.

```dart
void main() {
  late var value = () {
    var value = something();
    if (value == null) {
      throw '';
    }
    var result = value;
    return result;
  }();
  print(value.length);
}
String? something() => 'something';
```

If I change the assignment to `var result = value!;`, there is a warning about the `!` being unnecessary, but it runs without error. If I change the assignment to `String result = value;` it also runs without error.

**Comment by johnniwinther** [comment]
This is related to https://github.com/dart-lang/sdk/issues/49528 and is a consequence of https://github.com/dart-lang/language/issues/1650

**Comment by natebosch** [comment]
Let's close this as a duplicate of #49528
