### ISSUE TITLE
dart:html not support webkitEnterFullscreen

### ISSUE THREAD

**Issue by HG9558** [dart-lang/sdk#50355]
I am using Flutter for development. Now there is a scenario. I need to click on a video to achieve a full screen display effect. In Chrome browser, I can use Request FullScreen, but it doesn't work in safari browser. I tried to use webkitEnterFullscreen and it generated an error, here is my error message.

![image](https://user-images.githubusercontent.com/22909991/199247727-0ac0e3d4-991e-4791-8fa1-7a2c56643cf7.png)

**Comment by srawlins** [comment]
Questions like this are best suited for a user forum like StackOverflow, where many users are present to answer specific questions.

**Comment by rileyporter** [comment]
I think you want the [`enterFullscreen()` method](https://api.flutter.dev/flutter/dart-html/VideoElement/enterFullscreen.html) from `VideoElement`.

I'm closing the bug since dart:html has this support, but please re-open the bug if that method is broken.
