### ISSUE TITLE
[analyzer] Type Hierarchy is reporting with error the fields: superclass, interfaces, mixins and subclasses

### ISSUE THREAD

**Issue by rjfurlan** [dart-lang/sdk#50364]
**Note 1:** The problem was detect after upgrading from Dart 2.14.4(Flutter 2.5.3-Stable) to Dart 2.15.0(Flutter 2.8.0-Stable), and trying to get Flutter Widget class hierarchy inside of Android Studio . **A wrong result was obtained**.

**Note 2:** The result below were obtained using analysis_server_client with SEARCH_REQUEST_GET_TYPE_HIERARCHY and/or logging the results of the **variable _item of the function compute()** of the type_hierarchy.dart file, both with the same result.

To Exemplify the problem, 2 tests were created in which the hierarchy of classes is generated:

**Test 1:** a group of classes was created based on a new test that was added in the type_hierarchy_test.dart file:
class A {}
class D extends A {}
class C extends A {}
class B extends A {}
class G extends B {}
class F extends B {}
class E extends A {}

After  doing a search for the type of hierarchy it was obtained:
 0 - name: A       superclass: 1     interfaces: []  mixins: []  subclasses: [2, 3, 4, 5]
 1 - name: Object  superclass: null  interfaces: []  mixins: []  subclasses: []          
 2 - name: B       superclass: 0     interfaces: []  mixins: []  subclasses: [6, 7]      
 3 - name: C       superclass: 0     interfaces: []  mixins: []  subclasses: []          
 4 - name: D       superclass: 0     interfaces: []  mixins: []  subclasses: []          
 5 - name: E       superclass: 0     interfaces: []  mixins: []  subclasses: []          
 6 - name: F       superclass: **4**     interfaces: []  mixins: []  subclasses: []          
 7 - name: G       superclass: **4**     interfaces: []  mixins: []  subclasses: []

**For classes ‘F’ and ‘G’, for the superclass value the expected value is 2 but 4 was found;**

**Test 2:** another group of classes was created:
class A {}
class C extends A {}
class B extends A {}
class Bd extends B {}
class Be extends B {}
class Cg extends C {}
class Ch extends C {}

After  doing a search for the type of hierarchy it was obtained:
 0 - name: A       superclass: 1     interfaces: []  mixins: []  subclasses: **[2, 3]**
 1 - name: Object  superclass: null  interfaces: []  mixins: []  subclasses: []    
 2 - name: B       superclass: 0     interfaces: []  mixins: []  subclasses: **[6, 7]**
 3 - name: Bd      superclass: **3**     interfaces: []  mixins: []  subclasses: []    
 4 - name: Be      superclass: **3**     interfaces: []  mixins: []  subclasses: []    
 5 - name: C       superclass: 0     interfaces: []  mixins: []  subclasses: **[4, 5]**
 6 - name: Cg      superclass: **2**     interfaces: []  mixins: []  subclasses: []    
 7 - name: Ch      superclass: **2**     interfaces: []  mixins: []  subclasses: []

**For class ‘A’ the subclasses value the expected value is [2, 5] but [2, 3] was found
For class ‘B’ the subclasses value the expected value is [3, 4] but [6, 7] was found
For class ‘Bd’ the superclass value the expected value is 2 but 3 was found
For class ‘Be’ the superclass value the expected value is 2 but 3 was found
For class ‘C’ the subclasses value the expected value is [6, 7] but [4, 5] was found
For class ‘Cg’ the superclass value the expected value is 5 but 2 was found
For class ‘Ch’ the superclass value the expected value is 5 but 2 was found**

**Problem analysis**
An update (commit a242b4d6cc56de2175a8b344e6495ae523fcd4ee from 05/oct/2021, Dart 2.15.0) has been found that affects the files:
 - type_hierarchy.dart (add new routine “sort subclasses only” in the compute() function)
 - type_hierarchy_test.dart(add a new test)

**To the type_hierarchy.dart:**

> A routine was created that sorts the _items list, “sort subclasses only”
> This routine sorts the list(_items) by the class name, **causing a new placement of items within the _items list**
> **Which makes it necessary to update the values: superclass,  interfaces,  mixins and subclasses of each item**

**To the type_hierarchy_test.dart:**

> A new test was added to probably check the ordering, but for classes ’F’ and ‘G’ the **superclass value  should be 2 but it’s 4 in the test** (see test 1 above).

**Comment by scheglov** [comment]
@bwilkerson

**Comment by asashour** [comment]
Thanks for reporting this issue.

**Comment by bwilkerson** [comment]
I've created a revert of the original CL. I should have looked more closely at the original issue. It isn't even clear that changing the sort order on the server side would solve the UX issue.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/267281
