### ISSUE TITLE
Cannot run analyzer scripts on recent SDK builds

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#50382]
I'm trying to run our benchmark tool [1] or our completion stats tool [2], but recent builds of `dart` fail to run either, resulting in the following crash:

```none
$ xcodebuild/ReleaseX64/dart-sdk/bin/dart pkg/analysis_server/tool/code_completion/completion_metrics_client.dart
Crash when compiling file:///Users/srawlins/code/dart-sdk/sdk/pkg/analyzer/lib/src/dart/element/member.dart at character offset 9234:
Unsupported operation: _ExplicitNamedTypeBuilder.registerInferredType

#0      TypeBuilder.registerInferredType (package:front_end/src/fasta/builder/type_builder.dart:358:5)
#1      DeclaredSourceConstructorBuilder.finalizeSuperInitializingFormals.performRecoveryForErroneousCase (package:front_end/src/fasta/source/source_constructor_builder.dart:405:23)
#2      DeclaredSourceConstructorBuilder.finalizeSuperInitializingFormals (package:front_end/src/fasta/source/source_constructor_builder.dart:425:14)
#3      DeclaredSourceConstructorBuilder.inferFormalTypes.<anonymous closure> (package:front_end/src/fasta/source/source_constructor_builder.dart:339:11)
#4      SourceLoader.withUriForCrashReporting (package:front_end/src/fasta/source/source_loader.dart:296:17)
#5      DeclaredSourceConstructorBuilder.inferFormalTypes (package:front_end/src/fasta/source/source_constructor_builder.dart:318:29)
#6      DeclaredSourceConstructorBuilder.inferTypes (package:front_end/src/fasta/source/source_constructor_builder.dart:311:5)
#7      InferableTypeBuilder.inferType (package:front_end/src/fasta/builder/omitted_type_builder.dart:149:19)
#8      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:2404:19)
#9      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:533:14)
...
```

I've tried this at several recent commits, without success: d315721169773f2329a6098c9c74916036f083b5, 0b4376e3d17b9b099e1b170291050d2291f9446e, 925268bebed8e095871cb95cfd3f4123ea6af958, 902e5d030e4a05ed7c43f2aeb26131e134f89e5a.

After checking out each commit, I `rm -rf xcodebuild/` (I think I've seen caching problems before), then `gclient sync -D`, then `./tools/build.py --no-goma --mode release --arch x64 create_sdk dartanalyzer`.

I've tried running the benchmarking script in two ways. The first is approximately what golem uses:

`./sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart compile exe sdk/pkg/analysis_server/benchmark/benchmarks.dart -o benchmarks`

The other is just an execute, without the `dart compile exe` command:

```
./sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart \
    sdk/pkg/analysis_server/benchmark/benchmarks.dart run das-flutter \
    --dart-sdk=$PWD/sdk/xcodebuild/ReleaseX64/dart-sdk \
    --flutter-repository=/Users/srawlins/code/flutter
```

[1] pkg/analysis_server/benchmark/benchmarks.dart
[2] pkg/analysis_server/tool/code_completion/completion_metrics_client.dart

**Comment by johnniwinther** [comment]
I have a repro for the crash and work on a fix. The weird thing, though, is that this only occurs in face of compile-time errors - see the `performRecoveryForErroneousCase` from the stack trace.

**Comment by johnniwinther** [comment]
The CL is ready: https://dart-review.googlesource.com/c/sdk/+/268002

**Comment by johnniwinther** [comment]
@srawlins The fix has landed. Can you verify that it solves your problem?

**Comment by srawlins** [comment]
Verified this fixed it! Thanks!
