### ISSUE TITLE
[dev_compiler] Dart compiler crash for an Unhandled exception

### ISSUE THREAD

**Issue by reza-ebrahimi** [dart-lang/sdk#50394]
Dart compiler crashed for an Unhandled exception inside the dev compiler, please find the log below.

```bash
Unhandled exception:
Null check operator used on a null value
#0      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1652:65)
#1      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1609:19)

#2      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:3593:24)
#3      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1608:15)
#4      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2411:25)
#5      ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3583:18)
#6      ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1606:16)
#7      ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:1240:28)
#8      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:729:19)
#9      ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:657:23)
#10     List.forEach (dart:core-patch/growable_array.dart:416:8)
#11     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:603:23)
#12     List.forEach (dart:core-patch/growable_array.dart:416:8)
#13     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:442:15)
#14     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:153:33)
#15     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:705:47)

<asynchronous suspension>
#16     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:846:7)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Exited (sigterm)
```

* Dart SDK Version (`dart --version`)
```
❯ dart --version
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"
```

* Whether you are using Windows, MacOSX, or Linux
```
Ubuntu Linux
```

* Whether you are using Chrome, Safari, Firefox, Edge 
```
Chrome
```

**Comment by nshahan** [comment]
@reza-ebrahimi Thanks for the report! Could you elaborate on how you are running DDC? 

- Was this a Flutter web or build_runner build?
- Was this an initial build, or a rebuild after an edit?
- Can you reproduce this crash and if so is the code being compiled open source?

**Comment by reza-ebrahimi** [comment]
> Was this a Flutter web or build_runner build?

Flutter web.

> Was this an initial build, or a rebuild after an edit?

Hard to say, I think it was a hot-reload after an edit to a `super` constructor initializer.

> Can you reproduce this crash and if so is the code being compiled open source?

Both No. But I'm experiencing crashes in the compiler while working on the project on a daily basis.

**Comment by nshahan** [comment]
I can see the non-null assertion operator that is causing the problem.
https://github.com/dart-lang/sdk/blob/317ad8967414ef8e5e2fca7557ec4cff4c6c9df1/pkg/dev_compiler/lib/src/kernel/compiler.dart#L1652

I can create a fix to work around the crash but clearly there is an incorrect assumption that the super initializer will be non-null given a code pattern that we don't have a test for. I'm trying to find a reproduction to figure out where the actual bug originates.

All that said, if you experience another crash like this while editing and rebuilding I would love any more details of the code that was being edited.

**Comment by annagrin** [comment]
[gardening] Waiting for a repro to assign priority.

**Comment by annagrin** [comment]
Note: make sure we add more frontend server hot restart tests

**Comment by annagrin** [comment]
@christopherfujino this crash happens when using flutter tools - do you know if we have data on how ofter this stack trace is encountered?
