### ISSUE TITLE
Using Iterable causes code to run 360x slower.

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#50404]
## Observed
The following patch made my code execute in 0.5s instead of 3m:
```diff
if (changedFileBuildCommands.isEmpty) {
       _outSink.writeln(
@@ -236,13 +239,13 @@ class ClangTidy {
   ) {
     final List<Command> totalCommands = <Command>[];
     if (sharedBuildCommandsData.isNotEmpty) {
-      final Iterable<Command> buildCommands = buildCommandsData
-          .map((dynamic data) => Command.fromMap(data as Map<String, Object?>));
-      final Iterable<Set<String>> shardFilePaths =
+      final List<Command> buildCommands = buildCommandsData
+          .map((dynamic data) => Command.fromMap(data as Map<String, Object?>)).toList();
+      final List<Set<String>> shardFilePaths =
           sharedBuildCommandsData.map((List<Object?> list) => list
               .map((Object? data) =>
                   Command.fromMap((data as Map<String, Object?>?)!).filePath)
-              .toSet());
+              .toSet()).toList();
       final Iterable<_SetStatusCommand> intersectionResults =
           _calcIntersection(buildCommands, shardFilePaths);
       totalCommands.addAll(intersectionResults
```
## Exepected
The code that uses Iterable should execute faster if anything since it eliminates extra copies.

## Context
https://github.com/flutter/engine/pull/37265

cc @zanderso

**Comment by mraleph** [comment]
> The code that uses Iterable should execute faster if anything since it eliminates extra copies.

`.map(...)` and friends don't cache results (which is mentioned in the documentation). 

Your code is basically the following: 

```
for (var x in iterable1) {
  for (var y in iterable2) {
    // ...
  }
}
```

So for each element of `iterable1` you recompute elements of `iterable2` from scratch. 

Computing them once makes things faster. 

I think this is WAI and well documented?

**Comment by gaaclarke** [comment]
Here is the documentation:

> Returns a new lazy [Iterable](https://api.dart.dev/stable/1.10.1/dart-core/Iterable-class.html) with elements that are created by calling f on each element of this Iterable in iteration order.
> 
> This method returns a view of the mapped elements. As long as the returned [Iterable](https://api.dart.dev/stable/1.10.1/dart-core/Iterable-class.html) is not iterated over, the supplied function f will not be invoked. The transformed elements will not be cached. Iterating multiple times over the the returned [Iterable](https://api.dart.dev/stable/1.10.1/dart-core/Iterable-class.html) will invoke the supplied function f multiple times on the same element.
> 
> Methods on the returned iterable are allowed to omit calling f on any element where the result isn't needed. For example, [elementAt](https://api.dart.dev/stable/1.10.1/dart-core/Iterable/elementAt.html) may call f only once.

Yea, I understood that the values were lazy, I expected the results to be memoized.  I think I'm having some sort of weird mandela effect where that was the expected behavior of map functions.  At least in some languages the `map` function returns an iterator not an iterable so you can't accidentally iterate over it twice.

I don't think there is anything actionable here.
