### ISSUE TITLE
Extract method formats nullable types incorrectly

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#50402]
(Reproduced using IntelliJ, but I believe the logic for this is in the analysis server)

Given the following code:
```dart
abstract class C {
  List<int>? get x;
}
class D {
  f(C c) {
    var x = c.x;
    if(x != null) {
      print(x);
    }
  }
}
```
Highlight the lines:
```dart
    if(x != null) {
      print(x);
    }
```
And request an "extract method" refactor.

When I do this, I get the following code:
```dart
abstract class C {
  List<int>? get x;
}
class D {
  f(C c) {
    var x = c.x;
    g(x);
  }

  void g(List?<int> x) {
    if(x != null) {
      print(x);
    }
  }
}
```
Note that the extracted `g` method has an argument `x` of type `List?<int>`, which is not valid Dart.  It should be `List<int>?`.

**Comment by scheglov** [comment]
It look that this was fixed since then.
