### ISSUE TITLE
Allow to load AOT image dynamically at runtime

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#50406]
I was thinking and it would be very powerful if we could ship AOT compiled images as modules and have our code load them dynamically at runtime. Someting close to dynamic libraries (.dll or .so).

**Comment by mraleph** [comment]
Do you mean loading Dart modules into other Dart programs? You can already do this today with isolates, just point `Isolate.spawnUri` at the AOT snapshot and it will create a new isolate group with the code in the other snapshot. 

If you want to load AOT compiled code into the same isolate where another AOT compiled code is running - then this requires modular AOT if we need to support situations when host program and dynamic portion are compiled separately. Current AOT is whole program and going to modular will have bad impact on code size and performance. If you can compile host and dynamic portion together then you can simply use deferred libraries - which AOT supports.

**Comment by feinstein** [comment]
I am thinking about dynamically updating Flutter apps, so I can download a portion of the app and run it.

If I detect there's a new version on the server, then I can download it and on the next time the app restarts I can load that new patch instead.

**Comment by feinstein** [comment]
I didn't know the Play Store also forbids this... Funny how they allow interpreted code though.

Thanks @mraleph.
