### ISSUE TITLE
[CP] [vm/aot/tfa] Fix handling of type parameter nullability in factory constructors

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#50412]
### Commit(s) to merge

8ef9c6aab4b016644a6b811ac6fda374376757d0

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.git.corp.google.com/c/sdk/+/268500

### Issue Description

Type flow analysis (part of AOT compiler) ignored nullability of type parameter types (`T?`) in factory constructors. This caused incorrect results of analysis and incorrect optimizations. Only factories of generic classes which use type parameters as nullable (`T?`) are affected.

### What is the fix

Added a new ApplyNullability operation to a summary in order to apply any extra nullability ('?' or '*') on top of the type argument passed to a factory constructor.

### Why cherry-pick

This bug caused incorrect optimizations which may lead to a crash or a silent incorrect behavior which may be hard to diagnose.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/50392

**Comment by mraleph** [comment]
I support cherry picking.

**Comment by a-siva** [comment]
lgtm.

**Comment by alexmarkov** [comment]
Cherry-pick landed in 203d14e9ae2bebc8d8ba2241b537ffad40ad4a9f.
