### ISSUE TITLE
double basic math giving incorrect answer (rounding issue?)

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#50413]
I'm dealing with financial data and came across a weird issue with doubles and basic subtraction: 

```dart
void main() {
  var subtraction = 3.6 -0.01;
  print("result: $subtraction");
  print("3.59? ${subtraction==3.59}");
}
```

outputs:

```
result: 3.5900000000000003
3.59? false
```

This is happening on Android, Web & Dart pad. Is this some sort of a weird rounding issue?

**Comment by eernstg** [comment]
This is a FAQ. Please check out https://dart.dev/guides/language/numbers and https://www.itu.dk/~sestoft/bachelor/IEEE754_article.pdf.
