### ISSUE TITLE
Quick assist to convert switch statements to switch expressions

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#50417]
With the in-progress work on patterns, we're also adding a new switch expression. It would be very cool if we could support a quick fix that would allow you to convert switch statements to switch expressions when it makes sense. I think that's feasible when:

*   The switch is exhaustive over its type:
    * It's covering all cases in an enum, or
    * It has a default case.
*   And all of the cases (including default) have the same structure:
    * A single `return` statement, or
    * An assignment to the same variable or setter, or
    * *Maybe* a call to the same function but with a different argument.
*   While also allowing cases that abort too.

Then in that case, the shared structure in the cases can be hoisted out and the switch statement turned into a switch expression whose result is then applied to the shared structure. So, for example:

```dart
// Convert return:
switch (color) {
  case Color.red:
    return 'red';
  case Color.blue:
    return 'blue';
  case Color.green:
    throw 'Green is bad';
  case Color.yellow:
    return 'yellow';
}

return switch (color) {
  Color.red => 'red',
  Color.blue => 'blue',
  Color.green => throw 'Green is bad',
  Color.yellow => 'yellow'
};

// Convert assignment:
switch (color) {
  case Color.red:
    name = 'red';
    break;
  case Color.blue:
    name = 'blue';
    break;
  case Color.green:
    throw 'Green is bad';
  case Color.yellow:
    name = 'yellow';
    break;
}

name = switch (color) {
  Color.red => 'red',
  Color.blue => 'blue',
  Color.green => throw 'Green is bad',
  Color.yellow => 'yellow'
};

// Convert argument:
switch (color) {
  case Color.red:
    showName('red');
    break;
  case Color.blue:
    showName('blue');
    break;
  case Color.green:
    throw 'Green is bad';
  case Color.yellow:
    showName('yellow');
    break;
}

showName(switch (color) {
  Color.red => 'red',
  Color.blue => 'blue',
  Color.green => throw 'Green is bad',
  Color.yellow => 'yellow'
});
```

**Comment by bwilkerson** [comment]
The question, in my mind, is whether this should be tied to a 'prefer_switch_expressions' lint, or whether this should just be available as a quick assist in places where it could be applied. (I'd be hesitant to say that all such switch statements are marked as a problem without users explicitly choosing that style.)

**Comment by munificent** [comment]
If it were me, I wouldn't make this a "prefer" lint. Just an assist users can manually invoke for specific switch statements if they want to. I agree with you that I don't think all switch statements *should* be expressions just because they could be. Sometimes a statement is just easier to read.

**Comment by srawlins** [comment]
CC @pq @keertip

**Comment by pq** [comment]
> If it were me, I wouldn't make this a "prefer" lint. 

Proposal here: https://github.com/dart-lang/linter/issues/3673

**Comment by pq** [comment]
Implemented w/ https://github.com/dart-lang/sdk/commit/b68719c737e40991f02d49a9065990db008ffaa8
