### ISSUE TITLE
Quick fix to remove unnecessary break statements

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#50416]
Part of the pattern matching features is making switch statements simpler, including removing the need for pointless `break;` statements at the end of each non-empty case.

It would be great to add a quick-fix that eliminates those automatically in code that is on the language version where patterns are supported.

**Comment by bwilkerson** [comment]
Agreed. But fixes are only applied where there's a diagnostic reporting a problem. I think it would be reasonable to start reporting a dead-code diagnostic for unnecessary `break` statements to which such a fix could be applied. WDYT?

**Comment by munificent** [comment]
> Agreed. But fixes are only applied where there's a diagnostic reporting a problem. I think it would be reasonable to start reporting a dead-code diagnostic for unnecessary `break` statements to which such a fix could be applied.

Yes, 100%.

**Comment by srawlins** [comment]
CC @pq have we implemented this yet? I feel like I saw some changes related to this but I could be mistaken.

**Comment by pq** [comment]
yes!  I did tackle this one.

Implemented in 2192131b5e8fc170e5d02d8610a9765470d35034.
