### ISSUE TITLE
Parser error on `[...? x as T?]`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#50411]
```dart
void main() {
  dynamic x = [0];
  var l1 = [...? x as List<int>?]; // Fails to parse. Sees `?` as start of conditional expression, expected ':'
  var l2 = [...? x as List<int>?,]; // Works
  print(l);
}
```
This code fails to parse. The `?` after the `as` type seems to put the parser into a mode where it expects a conditional expression, even if it sees a `]`. If it sees a `,` first, then it recovers correctly and the code works.

**Comment by asashour** [comment]
I think this is fixed.

**Comment by lrhn** [comment]
It seems so. DartPad is not updated yet, but local builds parse this example correctly.

**Comment by FMorschel** [comment]
Which version is this fixed so that I can update it?
