### ISSUE TITLE
[dart2wasm] Tear-offs of same instance are not equal

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50429]
Extracted from a larger SDK test:

```dart
class C {
  void call() {}
}

void main() {
  final c = C();
  print(c.call == c.call);
}
```

AOT output: true
dart2wasm output: false

**Comment by askeksa-google** [comment]
We could implement `_Function.operator ==` to achieve this by comparing the contexts (which contain the `this` references for tear-offs) and the vtables. So just two reference comparisons.

Implementing a (non-trivial) `hashCode` that is consistent with this is tricky, though. For tear-offs, the `this` objects have identity hash codes we can use, but this is not the case for other contexts. The vtables current don't have anything hashable in them, and adding a hash for this obscure use case seems wasteful. We could hash the types, which are always equal whenever the vtables are.

So,
```dart
int get hashCode => runtimeType.hashCode;
```
could be an initial version which is consistent with `==` and not completely trivial.

**Comment by askeksa-google** [comment]
Hmm, looking at the description for `Function.operator ==`:
```
  /// Test whether another object is equal to this function.
  ///
  /// Function objects are only equal to other function objects
  /// (an object satisfying `object is Function`),
  /// and never to non-function objects.
  ///
  /// Some function objects are considered equal by `==`
  /// because they are recognized as representing the "same function":
  ///
  /// - It is the same object. Static and top-level functions are compile time
  ///   constants when used as values, so referring to the same function twice
  ///   always give the same object, as does referring to a local function
  ///   declaration twice in the same scope where it was declared.
  /// - if they refer to the same member method extracted from the same object.
  ///   Repeatedly extracting an instance method of an object as a function value
  ///   gives equal, but not necessarily identical, function values.
  ///
  /// Different evaluations of function literals
  /// never give rise to equal function objects.
  /// Each time a function literal is evaluated,
  /// it creates a new function value that is not equal to any other function
  /// value, not even ones created by the same expression.
```
My suggestion above could sometimes characterize different evaluations of the same function literal as equal, in violation of the last paragraph.

A fix would be to only consider the function objects equal if their contexts are objects, i.e. subtypes of the class hierarchy top type, meaning the closures are tear-offs.

The `hashCode` could use a combination (e.g. xor) of the type hash and the `this` identity hash for tear-offs and the identity hash of the closure for other closures.

**Comment by osa1** [comment]
> We could implement _Function.operator == to achieve this by comparing the contexts (which contain the this references for tear-offs) and the vtables. So just two reference comparisons.

Isn't this the same as my suggestion?

> My suggestion above could sometimes characterize different evaluations of the same function literal as equal

You mean when the function doesn't have a context (doesn't capture variables), right?

We could allocate an empty struct for context in those cases and compare contexts by reference in all cases.

Allocation of function literals will be slightly more expensive, but equality check won't need any special cases and will be faster.

Would that work?

**Comment by eernstg** [comment]
>> My suggestion above could sometimes characterize different evaluations of the same function literal as equal
>
> You mean when the function doesn't have a context (doesn't capture variables), right?

This is an interesting question: We've specified that certain function objects must compare equal, or even `identical`, but _not_ that they must be different. The underlying rationale is that it should be allowed for a compiler to optimize, for instance, a function literal that does not use its context:

```dart
void main() {
  Function functionFactory() => () => 3;
  var f1 = functionFactory(), f2 = functionFactory();
  print(identical(f1, f2)); // Can be 'true'.
}
```

This is because it's allowed to implement the above as follows:

```dart
int _g() => 3;

void main() {
  Function functionFactory() => _g;
  var f1 = functionFactory(), f2 = functionFactory();
  print(identical(f1, f2)); // 'true'.
}
```

**Comment by askeksa-google** [comment]
> Isn't this the same as my suggestion?

If by "Function indices" you mean the reference to the vtable, then yes. 😉

> You mean when the function doesn't have a context (doesn't capture variables), right?

Not only that. When a function literal occurs inside a loop but only captures variables outside the loop, the loop context is optimized away, and the closure refers directly to the outer context. So closures produced by different iterations of the loop would compare equal.

> Allocation of function literals will be slightly more expensive, but equality check won't need any special cases and will be faster.

Comparison of closures is an obscure use case. If we can avoid it, we should not make commonly used constructs slower to support it. Much rather make closure comparison slower.

> We've specified that certain function objects must compare equal, or even `identical`, but _not_ that they must be different.

Does this mean that the last paragraph of the documentation for `Function.operator ==`, which mandates some function objects to compare different, and thus also not `identical`, is incorrect?

**Comment by osa1** [comment]
> Does this mean that the last paragraph of the documentation for Function.operator ==, which mandates some function objects to compare different, and thus also not identical, is incorrect?

Correct. We discussed this with Erik in chat and I created https://dart-review.git.corp.google.com/c/sdk/+/269721 to fix this.

**Comment by osa1** [comment]
Since function literals not being equal and identical is not part of the spec (and that part of the `Function.operator ==` documentation will be removed soon with the CL above), we can now implement this simply by comparing vtable and context references. No special cases needed for functions without context.

**Comment by osa1** [comment]
- https://dart-review.git.corp.google.com/c/sdk/+/269721 updates `Function` documentation and removes invalid tests
- https://dart-review.googlesource.com/c/sdk/+/269882 fixes this issue in dart2wasm

**Comment by osa1** [comment]
Both CLs landed.
