### ISSUE TITLE
The result of [list].isEmpty is  opposite when the [list] is create by splitting of strings

### ISSUE THREAD

**Issue by h2magic-axious** [dart-lang/sdk#50425]
# Enviromnent
Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "macos_arm64"

### Example Code
<img width="307" alt="image" src="https://user-images.githubusercontent.com/48404363/201033029-b8aef03d-4e0e-46f1-b036-d8cbe2cae384.png">

### The result
<img width="197" alt="image" src="https://user-images.githubusercontent.com/48404363/201033168-a3b07ece-0c79-40dd-b6e4-e86be0679135.png">

**Comment by mraleph** [comment]
`y` has one element and it is an empty string. so `y` is formatted as `[]`. `toString` is not an unambiguous encoding. You can convert to JSON if you want one.
