### ISSUE TITLE
dart compile exe --enable-asserts fails with "Unrecognized flags"

### ISSUE THREAD

**Issue by simc** [dart-lang/sdk#50426]
Either the help of `dart compile exe` is incorrect:

> --enable-asserts                Enable assert statements.

Or the command `dart compile exe --enable-asserts main.dart` is broken because it outputs

```
Info: Compiling with sound null safety

Setting VM flags failed: Unrecognized flags: enable-asserts

Error: AOT compilation failed
Generating AOT snapshot failed!
```

Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "macos_arm64"

**Comment by vsmenon** [comment]
@a-siva - just verifying - does AOT mode support asserts?

**Comment by rmacnak-google** [comment]
AOT supports asserts. Product mode does not support asserts. `dart compile exe` uses product mode.

**Comment by a-siva** [comment]
help of dart compile exe is incorrect, we should fix that.
