### ISSUE TITLE
Dart compile exe fails on arm64 when building from source

### ISSUE THREAD

**Issue by nielsenko** [dart-lang/sdk#50428]
Environment:
```
Dart SDK Version: Dart SDK version: 2.19.0-edge.f910f23469950deffbaca9568313c9f7e8420acb (be) (Thu Nov 10 01:07:58 2022 +0000) on "macos_arm64"
```

After building Dart from source, and trying to compile a file:
```sh
.../sdk/xcodebuild/ReleaseARM64/dart compile exe test/indexed_test.dart
```
 I get:
> Could not find .../custom_build/dart-sdk/sdk/xcodebuild/ReleaseARM64/snapshots/gen_kernel.dart.snapshot. Have you built the full Dart SDK?

But I believe I have build the full SDK with:
```sh
./tools/build.py --no-goma --mode all --arch arm64 create_sdk
```

Using `jit-snapshot` compilation and the interpreter works fine. Am I doing something wrong?

**Comment by mraleph** [comment]
I think you need to run `dart` from the SDK itself, i.e. you need to run `sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart`.
