### ISSUE TITLE
Non-nullable variable is null anyway — Attempt to execute code removed by Dart AOT compiler (TFA)

### ISSUE THREAD

**Issue by Cyp** [dart-lang/sdk#50431]
* Dart SDK Version: 2.18.4 (stable)

```dart
final _foo = _Foo(const {'fileNotFound': true});

class _Foo<E> {
  _Foo(this.baz);

  final Map<String, E> baz;

  E? bar(String? json) => json != null ? baz[json]! : null;
}

Future<void> main() async {
  print('_foo.bar(null) ?? true = ${_foo.bar(null) ?? true}');
}
```

Somehow `_foo.bar(null) ?? true` ends up being `null` in release mode on Android (haven't tested other platforms).

In this test case, the code for printing `null` is (correctly) optimised out, so it crashes when (incorrectly) trying to print `null` anyway. In other code, a non-nullable enum silently causes problems later, by being an impossible `null`.

Doesn't trigger without the (unreachable) `!` on `baz[json]`.

### Actual output in release mode

```
E/flutter ( 6010): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Attempt to execute code removed by Dart AOT compiler (TFA)
E/flutter ( 6010): #0      main (package:someapp/main.dart)
E/flutter ( 6010): #1      _runMain.<anonymous closure> (dart:ui/hooks.dart:134)
E/flutter ( 6010): #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
E/flutter ( 6010): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

### Expected output in debug mode

```
I/flutter ( 7099): _foo.bar(null) ?? true = true
```

### See also

Not sure if it's related to #48238, although that one is with dart2js. Or maybe #49972 / #49930?

**Comment by Cyp** [comment]
A workaround is just to be more verbose, even though I'd have expected the generated code to be exactly identical. Haven't tested, but porting the workaround to the test case:
```dart
  // E? bar(String? json) => json != null ? baz[json]! : null;
  E? bar(String? json) {
    if (json != null) {
      final ret = baz[json];  // Wild guess is that saving in a temporary variable before the `!` fixes type deduction somehow, but haven't tested.
      return ret!;
    } else {
      return null;
    }
  }
```

**Comment by vsmenon** [comment]
Interesting - I'm getting a different error, but perhaps TFA is getting confused in both cases?  

@alexmarkov - wdyt?

```
> dart --version
Dart SDK version: 2.19.0-edge.c387068e00bdb6411a1c6e20d62b2ec046b5c499 (be) (Sat Nov 5 07:26:03 2022 +0000) on "macos_arm64"

> cat > guard.dart
final _foo = _Foo(const {'fileNotFound': true});

class _Foo<E> {
  _Foo(this.baz);

  final Map<String, E> baz;

  E? bar(String? json) => json != null ? baz[json]! : null;
}

Future<void> main() async {
  print('_foo.bar(null) ?? true = ${_foo.bar(null) ?? true}');
}

> dart guard.dart 
_foo.bar(null) ?? true = true

> dart compile exe guard.dart 
Info: Compiling with sound null safety.
Generated: /Users/vsm/test/guard.exe

> ./guard.exe 
Unhandled exception:
Attempt to execute code removed by Dart AOT compiler (TFA)
#0      main (file:///Users/vsm/test/guard.dart)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193)
```

**Comment by Cyp** [comment]
That's the same error, I think. I get `Attempt to execute code removed by Dart AOT compiler (TFA)` too.

**Comment by alexmarkov** [comment]
TFA transformed this example incorrectly, but only because kernel AST was incorrectly typed in the front-end.

Conditional expression in `_Foo.bar`:
```
ConditionalExpression(!(json == null) ?{(_Foo.E? & Object)} this.{_Foo.baz}.{Map.[]}(json{String})! : null)
```

Calling `getStaticType` from `ConditionalExpression` results in `IntersectionType((_Foo.E? & Object))`. It should be nullable, but its right type is `Object` and it is non-nullable. TFA used static type to narrow the result of conditional expression to a non-nullable Object which results in an empty set of values, then it is propagated to `main` and caused incorrect tree-shaking.

In order to fix this bug, we need to make sure `getStaticType` taken from that `ConditionalExpression` is correct.

/cc @johnniwinther @chloestefantsova

**Comment by chloestefantsova** [comment]
Sorry for the very late response on the issue. It seems that the VM already has a work around for the spurious output from the CFE. I'm working on a CL to make the CFE emit the correct type: https://dart-review.googlesource.com/c/sdk/+/311845
