### ISSUE TITLE
HttpException (HttpException: Failed to parse header value)

### ISSUE THREAD

**Issue by subbbbbaru** [dart-lang/sdk#50433]
Hello! I want to write a mobile application for a keenetic router. But I get an HttpException (HttpException: Failed to parse header value) error when I make a request to the Keenetic router.

 ```
 void httpp() async {
    HttpClient httpClient = new HttpClient();
    HttpClientRequest request =
        await httpClient.get('192.168.1.1', 80, '/auth');
    // it's polite to send the body length to the server

    request.headers.set('Accept-Encoding', '*', preserveHeaderCase: true);
    request.headers.set('Accept', '*/*', preserveHeaderCase: true);
    request.headers
        .set('Transfer-Encoding', 'chunked', preserveHeaderCase: true);
    request.headers.set('Connection', 'keep-alive', preserveHeaderCase: true);
    HttpClientResponse response = await request.close(); // HttpException (HttpException: Failed to parse header value)
    final chunks = await response.transform(utf8.decoder).toList();
    final bbb = chunks.join(',');
    httpClient.close();
    print(bbb);
    print(response);
  }
```

I verified via Wireshark that the request is being processed and I am getting a response headers like this:
`{'Server': 'Web server', 'Date': 'Thu, 29 Sep 2022 22:21:56 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'TMAKGAGUCQNB=HHMDXTJAKYRNHCNS; Path=/', 'WWW-Authenticate': 'x-ndw2-interactive realm="Keenetic Air" challenge="MQWUWIVNDDMINFPVMUOBNWFSIRBGPTKI" session_id="HHMDXTJAKYRNHCNS" session_cookie="TMAKGAGUCQNB"', 'X-NDM-Realm': 'Keenetic Air', 'X-NDM-Challenge': 'MQWUWIVNDDMINFPVMUOBNWFSIRBGPTKI'}`

But he still couldn't solve the problem. I will be grateful for help.

[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-arm, locale ru-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_arm64"

**Comment by sortie** [comment]
The `Set -Cookie` header looks malformed. A space in the header name isn't allowed and will not work. It seems like a bug in your keenetic router? There's not so much you can do if it's not responding in valid HTTP.

It looks like you posted the HTTP response as decoded by wireshark into JSON format. Can you post the raw HTTP request and raw HTTP response? The exact characters sent and received will help a lot when we think about cases like this, where we're dealing with a server that does not implement the specification and barely work.

**Comment by subbbbbaru** [comment]
> The `Set -Cookie` header looks malformed. A space in the header name isn't allowed and will not work. It seems like a bug in your keenetic router? There's not so much you can do if it's not responding in valid HTTP.
> 
> It looks like you posted the HTTP response as decoded by wireshark into JSON format. Can you post the raw HTTP request and raw HTTP response? The exact characters sent and received will help a lot when we think about cases like this, where we're dealing with a server that does not implement the specification and barely work.

I am sorry. I made a mistake when I copied the headers.  There is no space character.

**Comment by subbbbbaru** [comment]
Request:

GET /auth HTTP/1.1
user-agent: Dart/2.18 (dart:io)
Connection: keep-alive
Accept: */*
Accept-Encoding: *
host: 192.168.1.1

474554202f6175746820485454502f312e310d0a757365722d6167656e743a20446172742f322e31382028646172743a696f290d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a4163636570743a202a2f2a0d0a4163636570742d456e636f64696e673a202a0d0a686f73743a203139322e3136382e312e310d0a0d0a

Response:

HTTP/1.1 401 Unauthorized
Server: Web server
Date: Thu, 29 Sep 2022 21:55:34 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: LTLBXITXDJFHLUF=OCKUWIXZJPYLQFYU; Path=/
WWW-Authenticate: x-ndw2-interactive realm="Keenetic Air" challenge="KVAZHEAUGGWRZODBBJSBFWMYRXAYVVPN" session_id="OCKUWIXZJPYLQFYU" session_cookie="LTLBXITXDJFHLUF"
X-NDM-Realm: Keenetic Air
X-NDM-Challenge: KVAZHEAUGGWRZODBBJSBFWMYRXAYVVPN


485454502f312e312034303120556e617574686f72697a65640d0a5365727665723a20576562207365727665720d0a446174653a205468752c2032392053657020323032322032313a35353a333420474d540d0a5472616e736665722d456e636f64696e673a206368756e6b65640d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a5365742d436f6f6b69653a204c544c4258495458444a46484c55463d4f434b555749585a4a50594c514659553b20506174683d2f0d0a5757572d41757468656e7469636174653a20782d6e6477322d696e746572616374697665207265616c6d3d224b65656e657469632041697222206368616c6c656e67653d224b56415a48454155474757525a4f4442424a534246574d59525841595656504e222073657373696f6e5f69643d224f434b555749585a4a50594c51465955222073657373696f6e5f636f6f6b69653d224c544c4258495458444a46484c5546220d0a582d4e444d2d5265616c6d3a204b65656e65746963204169720d0a582d4e444d2d4368616c6c656e67653a204b56415a48454155474757525a4f4442424a534246574d59525841595656504e0d0a0d0a

**Comment by brianquinlan** [comment]
Where did you get the response data from? Is this an print from Dart or from curl or something?

**Comment by subbbbbaru** [comment]
> Where did you get the response data from? Is this an print from Dart or from curl or something?

I am getting this exception in Dart. I solved this problem with Flutter platform channels.

**Comment by brianquinlan** [comment]
Sorry, I meant where did the output that you posted i.e. 

```
HTTP/1.1 401 Unauthorized
Server: Web server
Date: Thu, 29 Sep 2022 21:55:34 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: LTLBXITXDJFHLUF=OCKUWIXZJPYLQFYU; Path=/
WWW-Authenticate: x-ndw2-interactive realm="Keenetic Air" challenge="KVAZHEAUGGWRZODBBJSBFWMYRXAYVVPN" session_id="OCKUWIXZJPYLQFYU" session_cookie="LTLBXITXDJFHLUF"
X-NDM-Realm: Keenetic Air
X-NDM-Challenge: KVAZHEAUGGWRZODBBJSBFWMYRXAYVVPN

485454502f312e312034303120556e617574686f72697a65640d0a5365727665723a20576562207365727665720d0a446174653a205468752c2032392053657020323032322032313a35353a333420474d540d0a5472616e736665722d456e636f64696e673a206368756e6b65640d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a5365742d436f6f6b69653a204c544c4258495458444a46484c55463d4f434b555749585a4a50594c514659553b20506174683d2f0d0a5757572d41757468656e7469636174653a20782d6e6477322d696e746572616374697665207265616c6d3d224b65656e657469632041697222206368616c6c656e67653d224b56415a48454155474757525a4f4442424a534246574d59525841595656504e222073657373696f6e5f69643d224f434b555749585a4a50594c51465955222073657373696f6e5f636f6f6b69653d224c544c4258495458444a46484c5546220d0a582d4e444d2d5265616c6d3a204b65656e65746963204169720d0a582d4e444d2d4368616c6c656e67653a204b56415a48454155474757525a4f4442424a534246574d59525841595656504e0d0a0d0a
```

come frome?
