### ISSUE TITLE
Should StreamController pass itself to its callbacks?

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#50447]
StreamController does not pass itself to it's callbacks.  Which means that if you wish to reference the stream controller from it's callbacks, you have to use a late variable, as the official docs do for the timer example:
https://github.com/dart-lang/site-www/blob/main/examples/misc/lib/articles/creating-streams/stream_controller.dart

```
Stream<int> timedCounter(Duration interval, [int? maxCount]) {
  late StreamController<int> controller;
  Timer? timer;
  int counter = 0;

  void tick(_) {
    counter++;
    controller.add(counter); // Ask stream to send counter values as event.
    if (counter == maxCount) {
      timer?.cancel();
      controller.close(); // Ask stream to shut down and tell listeners.
    }
  }

  void startTimer() {
    timer = Timer.periodic(interval, tick);
  }

  void stopTimer() {
    timer?.cancel();
    timer = null;
  }

  controller = StreamController<int>(
      onListen: startTimer,
      onPause: stopTimer,
      onResume: startTimer,
      onCancel: stopTimer);

  return controller.stream;
}
```

Although "tick" is the callback requiring the reference to stream controller, it's really the "startTimer" callback which is doing so.

Would it be simpler if the various on* methods just took a StreamController argument?

**Comment by lrhn** [comment]
It would definitely be different, which is why we're not going to do it now. Not planning on changing the API in a breaking way.

You don't need a late variable, you can just add the methods after creating the controller:
```dart
var controller = StreamController<int>(sync: true);
controller.onListen = controller.onResume = startTimer;
controller.onPause = controller.onCancel = stopTimer;
```
(Maybe I should get the article changed.)

**Comment by eseidel** [comment]
Thanks.
