### ISSUE TITLE
unused_result lint is triggered on import

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#50444]
### a.dart

```dart
import 'package:meta/meta.dart';

@useResult
int foo() => 42;
```

### b.dart

```dart
import 'a.dart' show foo;  
import 'a.dart' hide foo;
```

### Problem

The Analyzer reports `The value of 'foo' should be used.'` on both imports in `b.dart`. I would not expect the [unused_result](https://dart.dev/tools/diagnostic-messages#unused_result) rule to trigger on import statements.

```
$ dart --version
Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "macos_arm64"
```

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/269460
