### ISSUE TITLE
Code action to add all required args at once

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#50445]
In an [issue](https://github.com/flutter/flutter-intellij/issues/6392) on the Flutter plugin, @dark-chocolate suggests adding an option to add all required parameters at once. (There's a screen shot in the original.) If you don't care about the order, then this makes a lot of sense.

**Comment by asashour** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/49775

**Comment by stevemessick** [comment]
Thanks @asashour, closing this one.
