### ISSUE TITLE
A possible issue in SplayTreeMap with custom key comparator

### ISSUE THREAD

**Issue by anidotnet** [dart-lang/sdk#50454]
I am seeing an unusual behavior in SplayTreeMap while getting a value against a key, where I am using Comparable object as key having a custom compare logic. Similar java code is behaving as expected but dart code is not.

```dart
import 'dart:collection';

void main() {
  var memMap = SplayTreeMap<T, String>();
  memMap[T(5)] = "a";
  memMap[T(5.0)] = "b";

  print(memMap); // prints - {5.0: b, 5: a}
  print(memMap[T(5.0)]); // prints - b
  print(memMap[T(5)]); // prints - null  (???? should prints 'a' like thee java code did)
}

class T implements Comparable<T> {
  final Comparable _value;
  const T(this._value);

  @override
  int compareTo(T other) {
    return _comp(_value, other._value);
  }

  @override
  toString() => _value.toString();
}

int _comp(first, second) {
  if (first is num && second is num) {
    var result = _compareNum(first, second);
    if (first.runtimeType != second.runtimeType) {
      if (result == 0) return 1;
    }
    return result;
  }
  return first.compareTo(second);
}

int _compareNum(num x, num y) {
  return x.toDouble().compareTo(y.toDouble());
}

```

Similar code in java is behaving as expected.

```java
package anindya.demo;

import lombok.ToString;

import java.util.TreeMap;

public class Demo {
    public static void main(String[] args) {
        TreeMap<T, String> map = new TreeMap<>();
        map.put(new T(5), "a");
        map.put(new T(5.0), "b");

        System.out.println(map);                // prints - {Demo.T(comparable=5)=a, Demo.T(comparable=5.0)=b}
        System.out.println(map.get(new T(5.0)));    // prints - b
        System.out.println(map.get(new T(5)));      // prints - a
    }

    @ToString
    public static class T implements Comparable<T> {
        private Comparable comparable;
        public T(Comparable comparable) {
            this.comparable = comparable;
        }

        @Override
        public int compareTo(T o) {
            return compare(comparable, o.comparable);
        }

        private int compare(Comparable c1, Comparable c2) {
            if (c1 == null && c2 == null) {
                return 0;
            }

            if (c1 == null) {
                return -1;
            }

            if (c2 == null) {
                return 1;
            }

            if (c1 instanceof Number && c2 instanceof Number) {
                int result = compareNum((Number) c1, (Number) c2);
                if (!c1.getClass().equals(c2.getClass())) {
                    if (result == 0) return 1;
                }
                return result;
            } else {
                return c1.compareTo(c2);
            }
        }

        private int compareNum(Number n1, Number n2) {
            return Double.compare(n1.doubleValue(), n2.doubleValue());
        }
    }
}

```
Not sure if this is an issue in SplayTreeMap or not. If this is an expected behavior in dart, please explain why it is so.

* Dart SDK Version - Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "linux_x64"
* OS - Ubuntu 22.04.01 LTS

**Comment by asashour** [comment]
The reason is: 

    if (first.runtimeType != second.runtimeType) {

For `first`, it's `int`, while the other is `double`.

**Comment by asashour** [comment]
More specifically, there are two invocations of the compare which are incorrectly handled by the logic:

    first type: int, second type: double, result: 1
    first type: double, second type: int, result: 1


The comparison should be stable, i.d. one should return `1` and the other `-1`.

**Comment by anidotnet** [comment]
But as you see, I have same comparator logic in java and dart. While java can traverse the treemap and get me the result, dart cannot. Your logic regarding the comparison should also hold true in case of java code, but it does not.

**Comment by anidotnet** [comment]
Thanks @asashour for the clarification. When I changed the logic as below,

```dart
if (first.runtimeType != second.runtimeType) {
  if (result == 0) {
    return first.toString().compareTo(second.toString());
  }
}
```
it started behaving as expected.

**Comment by asashour** [comment]
Being successful with Java doesn't meant the logic is correct, is _may_ work, and may not. Even in different Java implementation that may give different results.

In [Java](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Comparable.html#compareTo(T)), it is stated that:

>The implementor must ensure [signum](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Integer.html#signum(int))(x.compareTo(y)) == -signum(y.compareTo(x)) for all x and y. (This implies that x.compareTo(y) must throw an exception if and only if y.compareTo(x) throws an exception.)

and (double, int) comparison is not the opposite of (int, double), which violates this rule.
