### ISSUE TITLE
[dart2js] constant literals are evaluated runtime

### ISSUE THREAD

**Issue by ohir** [dart-lang/sdk#50455]
Background: js int is 53 bits wide, js bitops are 32bit wide. But constant expression should have been turned into an int by the compiler, not evaluated at runtime.

Typical notation for readable round numbers can not be used due to this bug:
```
  assert(tag < (1 << 32), // const literal is being evaluated at runtime, giving 0 
  // assert(tag < 4294967296, // number of course works
     'tag must fit into 32 bits number. Got ${_ph(tag, 16)}  lit:${_ph(1 << 32, 16)}');
```
gives at runtime (Chrome)
```
Assertion failed: file:///unimportant
tag < (1 << 32)
"tag must fit into 32 bits number. Got 0000000000000000  lit:0000000000000000"
```

`Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "macos_x64"`

**Comment by vsmenon** [comment]
This is intentional behavior.  It's also not a sign that the compiler is evaluating at runtime.  Web compilers constant fold using web semantics.

**Comment by vsmenon** [comment]
You can refer to:

https://dart.dev/guides/language/numbers#bitwise-operations

for tips on working with numbers semantics across native and web.
