### ISSUE TITLE
LSP initialization may be too strict

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#50468]
A while back, I wrote a Flutter plugin for Lapce. (This was before I discovered @zarathir had already written one for Dart.) It worked for about two days. Then I updated everything and it stopped working. After some debugging I found that Lapse prints this message: `[ERROR] lsp server /path/to/flutter/bin/cache/dart-sdk/bin/dart stopped!`.

I think Dart SDK 2.18.1 (or 2.18.0) worked. 2.18.2 does not. Could there have been a change to the Dart analyzer that made LSP initialization too strict?

My LSP server args are:
-    "--no_dds",
-    "language-server",
-    "--client-id=Lapce",
-    "--client-version=0.0.1",
-    "--protocol-traffic-log=/path/to/lsp-traffic.log",
-    "--analysis-driver-log=file:/path/to/lsp-driver.log",

My `lsp-traffic.log` has this single line: 
`1668466833592:Ver:1657729343032595194383:Lapce:0.0.1:1.33.4:2.19.0`
There is nothing in `lsp-driver.log`.

FWIW I tried the Dart plugin I mentioned and it doesn't seem to be working, either. After starting Lapce with the Dart plugin,`ps xa | grep dart` just prints the processes for Flutter and IntelliJ.

/cc @jacob314

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
I can't see any server changes in the diff between 2.18.0 and 2.18.2 (https://github.com/dart-lang/sdk/compare/2.18.0..2.18.2), although in your log above I see 2.19.0 which certainly does have (although nothing I can think related to initialisation).

I tried installing Lapce and the Dart plugin noted above to reproduce this, and I definitely don't see the plugin working, but I also tried setting up a log file and restarting, but that log file is never created:

<img width="679" alt="Screenshot 2022-11-15 at 10 46 14" src="https://user-images.githubusercontent.com/1078012/201900669-02e531f3-b427-482e-a316-1f189d0649b7.png">

I've restarted the server, opened a small Dart project and opened a Dart file (which shows Dart in the status bar). Is there anything else I need to do to have it try to start the server?

**Comment by zarathir** [comment]
> My LSP server args are:
> 
>     * "--no_dds",
> 
>     * "language-server",
> 
>     * "--client-id=Lapce",
> 
>     * "--client-version=0.0.1",
> 
>     * "--protocol-traffic-log=/path/to/lsp-traffic.log",
> 
>     * "--analysis-driver-log=file:/path/to/lsp-driver.log",
> 

@stevemessick Try leaving out the "language-server" parameter. This gets appended by default to the arguments passed to the server.
Maybe I'll remove this and add it back to the default settings to avoid confusion.

I haven't put a lot of work in the plugin, as the plugin api of lapce is quite limited atm and will change. They just released v0.1 of the [plugin spec](https://lapce.dev/plugin-server-protocol/).

**Comment by DanTup** [comment]
@zarathir in my case it seems like the server is not being started at all (and I don't have an extra `language-server`). Is there anything I need to do to trigger this, or is there any logging anywhere that might confirm that it's trying to start the process?

**Comment by zarathir** [comment]
@DanTup Try setting the path to your dart executable in the `Server Path` option. Seems like the plugin is unable to start the lsp from PATH.

**Comment by DanTup** [comment]
@zarathir tried that, but it didn't seem to make any difference (my `dart` is also on `PATH`). I tried both the stable 2.18.0 and a bleeding edge version from today. Should there be anything in the log files when it tries to start the server? I can't find anything in any logs to suggest it's even loading your plugin (but I don't know if there should be).

**Comment by zarathir** [comment]
Hmmm, seems weird. Did you try to reload the plugin after setting the path to the dart executable?
There should be a log entry if the lsp server is stopped. That should look like this:
`[2022-11-15][17:36:42][lapce_data::proxy][ERROR] lsp server /home/zarathir/flutter/bin/dart stopped!`

This is what I'm currently running. With dart sdk `v2.18.4`
![image](https://user-images.githubusercontent.com/47316908/201976539-7706dc5c-ce4a-46ce-97d4-136ba647b4c2.png)

**Comment by stevemessick** [comment]
> @stevemessick Try leaving out the "language-server" parameter. This gets appended by default to the arguments passed to the server.

Thanks for the suggestion, but those args were copied from the debugging output of the Flutter plugin. I didn't use any custom args with the Dart plugin. @zarathir does your Dart plugin work for you? If so, which versions of Lapce and the Dart SDK are you using? FWIW I'm using a custom build of Lapce, built from sources.

**Comment by zarathir** [comment]
@DanTup Yes, plugin works for me. I'm running lapce-nightly. Did you check if the plugin is in the right lapce directory? Lapce creates different directories for different builds.

You can reload the plugin with clicking on the gear. And check if the plugin is in the right place with `Open Plugins Directory`
![image](https://user-images.githubusercontent.com/47316908/201982869-fbaab265-0a17-4399-8918-1c9f278f0ba8.png)

I don't know if this is the right place to discuss this anymore, as this has gotten quite off-topic. Feel free to open an issue on the plugin repo and we'll continue this over there.

**Comment by DanTup** [comment]
I think it's in the right place (I installed it through the UI):

<img width="225" alt="Screenshot 2022-11-15 at 17 27 11" src="https://user-images.githubusercontent.com/1078012/201986333-e36d792c-e844-4cfd-a24f-0ac5ab260c41.png">

I'll try installing the nightly version later in case that helps. If not, I'll file an issue in the plugin repo about this. Thanks!

**Comment by stevemessick** [comment]
Since the Dart plugin works when the path to the analyzer is set, it is clear the analyzer isn't causing the problems I'm seeing. Thanks @zarathir for clearing that up.

**Comment by DanTup** [comment]
@stevemessick so is everything working ok now? I could understand the server failing to start (resulting in a the "stopped" message you posted above) if the args were incorrect, although having an protocol log file created with a header suggests it got reasonable far into starting a server so I'm not sure why it would've stopped.

If you can reproduce that and want me to take a look, let me know (otherwise I'll hold off trying to get Lapce working until it's clear there may be something up). Thanks!

**Comment by stevemessick** [comment]
@DanTup The Dart plugin works. I've got a bug in my code, I think. I thought there was a problem in the analyzer because I couldn't get either my plugin or the Dart plugin to work. But @zarathir explained how to make the Dart plugin work, and now it does, so I don't think the analyzer has a problem. Sorry for the noise!
