### ISSUE TITLE
How to make Dart app (executable) runs silently in background without seeing the cmd interface?

### ISSUE THREAD

**Issue by r4444zy** [dart-lang/sdk#50463]
I made a code which runs simple command line in cmd using Process.run till now everything is fine, after i have compiled it to an exe file using dart compiler, i clicked it and it shows cmd prompt and it disappears, how i can make it runs silently without seeing that cmd interface?
(the business logic of my code works fine)
![image](https://user-images.githubusercontent.com/106804966/201686137-a4e8dff3-2dbb-4ca7-83b6-e94b3c0fef68.png)

**Comment by vsmenon** [comment]
Can you please add Dart version info, the OS you are using, and, if possible, a sample app that recreates this behavior?

**Comment by r4444zy** [comment]
yes sure,

Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "windows_x64"

OS : Windows 10

example of the app: 
`import 'dart:io';
import 'dart:convert';
import 'dart:io';

open(String path) async {
  var process = await Process.start(path, [], runInShell: true);
}

main() async {
  await open(r"D:\scr\test\bin\file.txt");
  exit(1);
}
`

**Comment by rmacnak-google** [comment]
The VM in the SDK is a console application. You would need to build a variant of the VM using the linker option `/SUBSYSTEM:WINDOWS`.

https://learn.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170

**Comment by mraleph** [comment]
Alternatively you could just flip the flag in the PE header. See few possible ways to do it [here](https://stackoverflow.com/questions/2435816/how-do-i-poke-the-flag-in-a-win32-pe-that-controls-console-window-display/14806704)

**Comment by r4444zy** [comment]
@mraleph i tried the first recommended solution and it shows error.

D:\scr\test\bin>editbin.exe /subsystem:windows test.exe
'editbin.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by r4444zy** [comment]
I just want to hide the window of cmd after running the compiled .exe file of the dart app above.

**Comment by mraleph** [comment]
The SO quite clearly states that `editbin.exe` is part of the MSVC. So if you want to use `editbin` you need to install MSVC.

**Comment by r4444zy** [comment]
it works! thank you.
