### ISSUE TITLE
[analyzer] add `async` fix for `return_of_invalid_type_from_closure`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50460]
1. With
```dart
void g(Future<String> Function() a) {}

void f() {
  g(() => '');
}
```

there is an error of:

>The return type 'String' isn't a 'Future<String>', as required by the closure's context.

It would be better to offer a fix, to add `async`, so that we have

```dart
  g(() async => '');
```

2. A similar case for `return_of_invalid_type`:

```dart
Future<String> futureString() => '';
```

**Comment by bwilkerson** [comment]
I agree, those are reasonable fixes to offer.

**Comment by FMorschel** [comment]
Here is my CL https://dart-review.googlesource.com/c/sdk/+/394361

**Comment by FMorschel** [comment]
Can I get a new review for my CL @bwilkerson? Thanks!
