### ISSUE TITLE
[analyzer] add `await` fix for `argument_type_not_assignable`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50461]
```dart
Future<String> futureString() async => '';

void g(String s) {}

void f() async {
  g(futureString());
}
```

There is an error of:

>The argument type 'Future<String>' can't be assigned to the parameter type 'String'.

It should be better to have offer a fix to add `await`, so that we have

```dart
  g(await futureString());
```

**Comment by FMorschel** [comment]
https://dart-review.googlesource.com/c/sdk/+/388040
