### ISSUE TITLE
[analyzer] message for `invalid_implementation_override` seems to be inverted

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50478]
With the [example](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=invalid_implementation_override#invalid_implementation_override) code:

```dart
class A {
  int add(int a) => a;
}
class B extends A {
  int add(num a);
}
```

The error is:

> 'A.add' ('int Function(int)') isn't a valid concrete implementation of 'B.add' ('int Function(num)').

I believe it should be

> 'B.add' ('int Function(num)') isn't a valid concrete implementation of 'A.add' ('int Function(int)')

**Comment by bwilkerson** [comment]
No, it's actually correct. Technically correct, but not necessarily easy to understand, so it still might want to be changed.

Abstract methods have some interesting semantics. In particular, the concrete implementation of an abstract method can come from either a subclass (what you'd normally expect) or a superclass (what's happening in your example). The concrete implementation has to correctly implement the abstract method in either case, but in your example it doesn't. Hence the seemingly backward message.

The most common case for this is something like the following, where the abstract method comes from an interface and the concrete method comes from a superclass:

```
class A {
  int add(int a) => a;
}
abstract class I {
  int add(num a);
}
class B extends A implements I {}
```

That's the use case that the message was originally written for, and I want to make sure that that case is still clear if we make any other changes.

**Comment by asashour** [comment]
I see, thanks for explaining.
