### ISSUE TITLE
change to analyzer snapshots bumps dart binary size

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#50487]
@jensjoha landed [a change](https://dart-review.git.corp.google.com/c/sdk/+/269683) to how analyzer snapshots are trained.

This resulted in a sizeable bump to the size of the `dart` binary. [This benchmark](https://golem.corp.goog/Benchmark?repository=dart&benchmark=SDKArtifactSizes.analysis_server#targets%3Ddart-null%3BmachineTypes%3Dlinux-x64%3Bcpus%3DIntel%20Xeon) shows a bump from ~24MB to ~51MB. Is it acceptable and worth it? I have no idea who can/should answer this...

@jensjoha, the change "makes it faster when first loaded". Given the case of a user that bumps their Dart SDK from 2.18 to 2.19, or a similar bump which maybe happens 2-4x a year, is the performance literally only improved on the first time one of these snapshots is invoked? Is the performance improvement seen only 2-4 runs a year?

I would think that better training would mean that performance is improved on every run...

CC @bwilkerson @athomas @mraleph @sortie

**Comment by mraleph** [comment]
@jensjoha Could you try compiling analyzer as an AOT binary and see how big that is and how well it performs against the JIT version?

**Comment by mnordine** [comment]
> This resulted in a sizeable bump to the size of the dart binary

You mean the analyzer snapshot, not the `dart` binary, right?

**Comment by mnordine** [comment]
FWIW, on Windows, using Powershell, with an empty project:
`2.18.4`: `807ms`
`master`: `367ms`

**Comment by mnordine** [comment]
I've tried it on several projects, and, as expected with this change, it reduces total time by about 400-600ms.

**Comment by mnordine** [comment]
Just my 2 cents, but I'd be happy to pay the cost of 25MB on the SDK download to not pay that startup cost every time the analyzer starts.

**Comment by srawlins** [comment]
> You mean the analyzer snapshot, not the `dart` binary, right?

I'm honestly not sure what is being tracked in that benchmark. The title made me assume the `dart` binary, but maybe it's a snapshot file or the zipped up SDK or something.

**Comment by mnordine** [comment]
Yeah, just on my machine, it's the analyzer snapshot file that increases in file size after that commit, nothing to do with the `dart` executable.

**Comment by jensjoha** [comment]
> @jensjoha, the change "makes it faster when first loaded". Given the case of a user that bumps their Dart SDK from 2.18 to 2.19, or a similar bump which maybe happens 2-4x a year, is the performance literally only improved on the first time one of these snapshots is invoked? Is the performance improvement seen only 2-4 runs a year?

There seems to be some misconception here. *Whenever* you load the analyzer (say open an IDE), before the VM started basically without any code compiled and would spend time doing that, making optimizations once the it had that information etc. Now it's ~just there from the start.
Even if the analyzer has all base code cached it will still be faster --- though I haven't benchmarked it, this certainly should include completions, invalidations etc although it naturally won't be going from 20 seconds to 10 seconds (given that a completion shouldn't take 20 seconds to begin with).
This is every time the analyzer starts. I will try to do some benchmarks though.
(Whenever using new code for the first time, though, (say a new package or a new version of a package, an updated flutter, or a change in own code that invalidates big chunks) it will - with big enough code - still be a 20 -> 10 seconds thing for the case where the analyzer before hadn't warmed up).

**Comment by srawlins** [comment]
@jensjoha thanks for clarifying and for the additional benchmarks! I really only filed this because the golem benchmark showed the jump which seemed to warrant the discussion.

A 5% bump to total SDK size seems totally fine to me. 🤷

**Comment by mraleph** [comment]
> As such it seems like a good way to go, but as said, because if the integration I don't think it's an easy thing.

Could you file a bug to track this. I think we should figure a way to go this route also it would align with what we are running on Golem - all those benchmarks are AOT compiled.

> The exe created is 24MB and it takes ~40 seconds.

So it is not that much different from JIT snapshot. (24Mb exe means around 20Mb of AOT snapshot).

**Comment by jensjoha** [comment]
> So it is not that much different from JIT snapshot. (24Mb exe means around 20Mb of AOT snapshot).

It's smaller than the trained jit snapshot :)

**Comment by jensjoha** [comment]
> Could you file a bug to track this

https://github.com/dart-lang/sdk/issues/50498

**Comment by mit-mit** [comment]
The mentioned SDK size increase SGTM

**Comment by srawlins** [comment]
I'm satisfied; thanks for everyone's patience and responses!
