### ISSUE TITLE
regexp/named-captures_test is flaky on Firefox

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#50486]
The test
```
corelib_2/regexp/named-captures_test RuntimeError (expected Pass)
```
is flaky on configuration
```
dartdevk-checked-linux-release-firefox
```

Reproducing locally, I can see that Firefox auto-updates extremely quickly, and runs the new version when it is restart.  So it can be auto-updating during a single build, or on a cached checkout and be updated for later builds too.

This test fails on Firefox version Mozilla Firefox 106.0.5, but passes on Firefox 98.0.2, the current checked in version.

Fixed the test runner to stop autoupdates of Firefox: https://dart-review.googlesource.com/c/sdk/+/270101

Will update Firefox to a recent version as well, which should make this test fail consistently, like all the other browsers.

**Comment by lrhn** [comment]
Q.v. #50437
