### ISSUE TITLE
js-interop:

### ISSUE THREAD

**Issue by AbhishekDevCode** [dart-lang/sdk#50495]
call js.context.myFunc(); not working for mobile and ios

**Comment by mraleph** [comment]
If you are compiling targeting the native then JS interop is not supposed to work because there is no JS involved there.

You will need to use some third party library to run your JS code.

**Comment by AbhishekDevCode** [comment]
can you give me some idea about third party package run for JS code ?

**Comment by mraleph** [comment]
Try searching on pub.dev or ask community https://flutter.dev/community

https://pub.dev/packages/flutter_js is one example.
