### ISSUE TITLE
[Records] Annotation space record type annotation parsing

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#50490]
@jensjoha 

The language specification decided on https://github.com/dart-lang/language/issues/2469
So, the parser should be updated accordingly.

**Comment by leafpetersen** [comment]
I believe, per discussion with @johnniwinther that this change was proposed to land after the cut for 2.19 at the end of the month to avoid the breaking change landing in 2.19.  (We agreed that the already landed breaking change around try/catch would remain and go out in 2.19).
