### ISSUE TITLE
[CP] Fix dart vm hanging while running tests

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#50491]
### Commit(s) to merge

ce9a42f53e146e0c88aec5f00c7fa0a02abf1199

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/270300

### Issue Description

Dart vm occasionally hangs when running tests especially with enabled test coverage.
This is due to potentially many http vmservice servers created and started, but only one of them shutdown, the rest staynig up preventing dart vm from exiting.

### What is the fix

Ensure that only one vmserver http server is started.

### Why cherry-pick

Hanging dart vm while running tests causes continuous integration issues with customers, forcing them to spend much more (potentially expensive) CPU resources while running tests.

### Risk

medium

### Issue link(s)

https://github.com/dart-lang/sdk/issues/50389

**Comment by aam** [comment]
cc @a-siva

**Comment by itsjustkevin** [comment]
Friendly bump @a-siva

**Comment by a-siva** [comment]
This was supposed to be discussed in the scrum meeting last week so others could approve. from my side it is a lgtm.

**Comment by a-siva** [comment]
//cc @vsmenon @mit-mit @itsjustkevin can we get approval for this cherry pick request, we have ping regarding this from a user

**Comment by itsjustkevin** [comment]
Friendly bump.

**Comment by vsmenon** [comment]
lgtm

**Comment by itsjustkevin** [comment]
I am calling this one approved.

**Comment by whesse** [comment]
This cp is landed on stable, and does not need to be landed on beta because 2.19.0-444.1.beta includes the cherry-picked commit already.

Leaving the issue open until the stable hotfix including this CP is built and released, by making a CHANGELOG change on main adding the new stable hotfix change info, and making a VERSION change on the stable branch, also copying the CHANGELOG change.

**Comment by itsjustkevin** [comment]
I am getting a bit of conflicting information here.  We have the `merge-to-beta` label added but @whesse mentioned that we do not need this landed on beta.

@athomas and @whesse could you help clear this up?

**Comment by a-siva** [comment]
We should remove the merge-to-beta label, as pointed out by @whesse this change exists in  2.19.0-444.1.beta already and so does not need a cherry pick.

**Comment by itsjustkevin** [comment]
Merged into Dart 2.18.6.
