### ISSUE TITLE
[GitHub Actions] Scrorecards supply-chain security last ran successfully on 14 Sep 2022

### ISSUE THREAD

**Issue by cpswan** [dart-lang/sdk#50497]
I wanted to look at the SARIF file from this repo, but it turns out that the last successful run for the scorecards-analysis action was 2 months ago (and the SARIF file from that run has expired):

![image](https://user-images.githubusercontent.com/478926/202477320-82ed3946-cc78-4a1d-a108-22a0bd163aba.png)

Runs since [#131](https://github.com/dart-lang/sdk/actions/runs/3049212578) have concluded with:

```
2022/09/15 00:09:24 error signing scorecard json results: error signing payload: getting key from Fulcio: retrieving cert: error obtaining token: expired_token
```

**Comment by devoncarew** [comment]
Thanks for the report! cc @athomas and @godofredoc

**Comment by athomas** [comment]
Thanks!

I updated the token, but on re-run the action still complained about the expired token. I'll wait for the next normal run and if it's still failing look more into this.

**Comment by godofredoc** [comment]
We need to add these two lines to the workflow config in dart-lang/sdk https://github.com/flutter/flutter/blob/master/.github/workflows/scorecards-analysis.yml#L21-L22

**Comment by devoncarew** [comment]
https://dart-review.git.corp.google.com/c/sdk/+/270500
