### ISSUE TITLE
Fix grammar: `an` instead of `a` before words beginning with vowel sounds.

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50509]
https://dart-review.googlesource.com/c/sdk/+/270740

There are many places in the documentation, of incorrect `a` instead of `an`, when the following word starts with a `vowel` sound.

**Comment by devoncarew** [comment]
@asashour - do you have more details for this bug report?

**Comment by asashour** [comment]
Sorry for not doing so earlier, now more details are added.
