### ISSUE TITLE
[analyzer] `AddNullCheck` with null-aware operator

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50506]
```dart
void f(String? s) {
  if(s?.length > 1) {
  }
}
```

Offers a fix to be:

```dart
if (s?.length! > 1) {}
```

instead of

```dart
if (s!.length > 1) {}
```

**Comment by pq** [comment]
Good catch!

**Comment by bwilkerson** [comment]
I'll just note that the second option isn't necessarily the best (though I'd agree that it is in this case). What makes it better is the fact that `length` can't return `null`, so what we likely want to offer is to place the null check operator after the last component in the chain that can return a `null`.

More concretely, if `length` could return `null` then the current behavior should be preserved.

**Comment by asashour** [comment]
Even if the field is `nullable`, the current behavior seems to be incorrect. For example:

```dart
class A {
  int? n;
}

void f(A? a) {
  a?.n > 1;
}
```

Is should be

```dart
a!.n > 1;
```

instead of
```dart
a?.n! >1;
```

Please find [sdk/274442](https://dart-review.googlesource.com/c/sdk/+/274442) noting that I couldn't make a test case for `PrefixedIdentifier`
