### ISSUE TITLE
[Patterns] Fix analyzer unit tests failing with the 'patterns' feature enabled

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#50502]
For now, these tests use language version override `@dart = 2.18`.

**Comment by scheglov** [comment]
`messages.yaml` was updated to force language `2.18` for
```
CompileTimeErrorCode.BREAK_LABEL_ON_SWITCH_MEMBER
CompileTimeErrorCode.CASE_EXPRESSION_TYPE_IMPLEMENTS_EQUALS
CompileTimeErrorCode.CASE_EXPRESSION_TYPE_IS_NOT_SWITCH_EXPRESSION_SUBTYPE
CompileTimeErrorCode.NON_CONSTANT_CASE_EXPRESSION
CompileTimeErrorCode.NON_CONSTANT_CASE_EXPRESSION_FROM_DEFERRED_LIBRARY
CompileTimeErrorCode.SWITCH_CASE_COMPLETES_NORMALLY
```
We should triage these failures, some of them are bugs, and some require changes to the snippets.

**Comment by scheglov** [comment]
This is part of the language features work, so I should have set it to P1.
Correcting now :-)

**Comment by bwilkerson** [comment]
If the fix is to update the snippets to use not-yet-valid code, we probably don't want to update them until shortly before the language feature ships.

**Comment by stereotype441** [comment]
Note: in CL [Add parser support for patternAssignment](https://dart-review.googlesource.com/c/sdk/+/272383) I've added `@dart = 2.18` to one additional test: `AssignmentDriverResolutionTest.test_notLValue_parenthesized_simple`.

**Comment by mit-mit** [comment]
@scheglov is there more work here?

**Comment by itsjustkevin** [comment]
@scheglov the CL noted in your last comment is closed, is there another CL we are missing to close this out?

**Comment by scheglov** [comment]
OK, there are no more tests that fail and marked with this issue.
So, we can close it.
