### ISSUE TITLE
Deprecation message has two dots at the end

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#50518]
When marking something as deprecated, using `@Deprecated('message')`, if the deprecation message ends in a dot, the effective messages has two dots at the end.

Example:
```
void main() {
  final foo = Foo();
  
  final bar = foo.bar;
}

class Foo {
  @Deprecated('This value should not be used. Use the qux variable instead.')
  final int bar = 42;
}
```

Running `dart analyze` on the example produces:
```
   info • test.dart:4:19 • 'bar' is deprecated and shouldn't be used. This value should not be used. Use the qux variable instead.. Try replacing the use of the
          deprecated member with the replacement. • deprecated_member_use_from_same_package
```

* Dart SDK Version (`dart --version`)
Dart SDK 2.19.0-406.0.dev

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/271020
