### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by zyadalamami** [dart-lang/sdk#50526]
## Version information

- `IDEA AI-213.7172.25.2113.9123335`
- `2.18.4`
- `AI-213.7172.25.2113.9123335, JRE 11.0.13+0-b1751.21-8125866x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 , screens 1366.0x768.0`

**Comment by mraleph** [comment]
There is no actionable feedback provided.
