### ISSUE TITLE
Failures on Test field promotion during top level inference.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#50522]
There are new test failures on [Test field promotion during top level inference.](https://dart-review.googlesource.com/c/sdk/+/270760).

The tests
```
language/inference_update_2/top_level_type_inference_test CompileTimeError (expected Pass)
```
are failing on configurations
```
cfe-strong-linux
cfe-weak-linux
dart2js-hostasserts-strong-linux-x64-d8
dart2js-hostasserts-weak-linux-x64-d8
dart2wasm-hostasserts-linux-x64-d8
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

**Comment by stereotype441** [comment]
@johnniwinther ping.  Have you had a chance to look into this?  I'm hoping to get back to field promotion in early January and this is one of the few remaining blocking items.

**Comment by johnniwinther** [comment]
I landed the [fix](https://dart-review.googlesource.com/c/sdk/+/272301) yesterday, so you should be unblocked.

**Comment by johnniwinther** [comment]
I didn't see any tests that started passing, though. Do we still need to update how this is queried in the CFE?

**Comment by stereotype441** [comment]
Unassigning myself because I'm not actively working on field promotion right now; I will likely pick it up again later in the year.
