### ISSUE TITLE
Can't download RISC-V SDK for 2.19.0-374.2.beta or 2.19.0-374.1.beta

### ISSUE THREAD

**Issue by cpswan** [dart-lang/sdk#50548]
* Dart SDK Version: 2.19.0-374.2.beta or 2.19.0-374.1.beta
* Linux on RISC-V
* wget (and Chrome)

I went to the [Dart SDK archive](https://dart.dev/get-dart/archive) to download the latest SDK for RISC-V. The latest release [2.19.0-374.2.beta](https://storage.googleapis.com/dart-archive/channels/beta/release/2.19.0-374.2.beta/sdk/dartsdk-linux-riscv64-release.zip) and the previous release [2.19.0-374.1.beta](https://storage.googleapis.com/dart-archive/channels/beta/release/2.19.0-374.1.beta/sdk/dartsdk-linux-riscv64-release.zip) both result in the following type of error from GCS:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: dart-archive/channels/beta/release/2.19.0-374.2.beta/sdk/dartsdk-linux-riscv64-release.zip</Details>
</Error>
```

With wget this gets reported at `ERROR 404: Not Found.`

The last working version appears to be 2.19.0-255.2.beta

**Comment by sortie** [comment]
Hi, the Dart SDK is not yet officially supported on RISC-V and as such we currently only publish builds on the dev channel and not beta and stable until it's ready. Thanks for helping by trying it out! :)

The 2.19.0-374.2.beta release branched off 2.19.0-374.0.dev, so you could download that version instead and only miss out on a [single cherry-pick](https://github.com/dart-lang/sdk/commit/1f419057acae250e4337457b43a9583ca243c330).

It looks like a bug on our dart.dev website that it includes RISC-V in the beta channel, but correctly omits it from the stable channel. Likewise with the Windows ARM64 build that is also only on dev. We'll fix the website to avoid confusion :)

**Comment by athomas** [comment]
@cpswan It was added by mistake to beta before being ready that's why it showed up for some versions. This has been fixed. We currently have no test coverage for RISC-V, so we don't know how well it works and wouldn't know if it breaks. Until we have coverage (and it works well enough), RISC-V will remain on main and dev channels only.

**Comment by cpswan** [comment]
@athomas were RISC-V builds intentionally promoted to stable channel from 3.3.0, or has there been another glitch in the matrix?

![image](https://github.com/user-attachments/assets/b6ef01d6-40d1-4c5a-bbfd-54406e4d8462)

**Comment by athomas** [comment]
> @athomas were RISC-V builds intentionally promoted to stable channel from 3.3.0, or has there been another glitch in the matrix?

It's intentional, see https://dart.dev/get-dart#system-requirements
