### ISSUE TITLE
Navigation seems to slow down auto complete

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#50542]
When I have a certain file open (internally), and run a CPU profile while trying to autocomplete, I get that we're spending > 500 ms in `Directory.exists`:

<img width="1080" alt="Screen Shot 2022-11-23 at 2 42 29 PM" src="https://user-images.githubusercontent.com/103167/203658599-108d82fb-859e-4257-9483-f232ae6f34e6.png">

It seems like _DartNavigationComputerVisitor calls `resourceProvider.getFile` for every doc comment visited in `visitComment`. This was introduced in https://github.com/dart-lang/sdk/commit/ae7e3517c80532eaac28c8d718e5caaf06722b46#diff-31f9a5232da9a94e12badc4bff0d6a6212b70984059e0dcab30c60e94243c510. It seems bad to me.

@scheglov can you say why _DartNavigationComputerVisitor would be doing work at this moment? Here are the steps I take to reproduce (with dummied down text):

1. File contains something like `class C { final _x = {}; void f() { _x.entries.^ } }` with cursor at the caret.
2. I start a CPU profile, in DevTools
3. I type `<backspace>`
4. I type `.`
5. I wait several seconds.
6. completions appear for instance members on `List`.

**Comment by srawlins** [comment]
CC @gspencergoog who wrote the referenced change and @bwilkerson who might be familiar as well.

**Comment by scheglov** [comment]
Yes, doing IO, is a very bad idea. Even if there is a need to get some additional data, this data should be cached and not recomputed every time.

I suspect that `_DartNavigationComputerVisitor` does this work because we wanted to implement some feature. I'm not sure if you had a more specific question that I fail to recognize.

**Comment by bwilkerson** [comment]
That could easily be optimized. We don't need nearly as many existence checks, and we could probably cache the result temporarily while processing a single compilation unit (or maybe even longer term).

I have no idea why `_DartNavigationComputerVisitor` is running during code completion (or whether it is). Can you expand the call stack and find out where it's being run from?

**Comment by bwilkerson** [comment]
`_DartNavigationComputerVisitor` is doing the work so that we can navigate from the link to an example to the source for the example in Flutter-style doc comments.

**Comment by srawlins** [comment]
@scheglov 

> I'm not sure if you had a more specific question that I fail to recognize.

I was wondering why `_DartNavigationComputerVisitor` is entered during the steps I mentioned.

**Comment by scheglov** [comment]
The reason `_DartNavigationComputerVisitor` is running during completion might be that completion is an async operation, so it can be interleaved with other operations running in parallel.

**Comment by srawlins** [comment]
I'll ask a different question: What IDE events trigger entering `_DartNavigationComputerVisitor`? Clicking the mouse around? Typing a character into a file?

**Comment by bwilkerson** [comment]
Even if it isn't interleaved sometimes, this could sometimes account for the latency we're seeing. If server has started computing navigation before the request for code completion is seen, and it's taking a long time for navigation to return, then it's might be preventing code completion from getting started.

> What IDE events trigger entering `_DartNavigationComputerVisitor`?

Modifying a file.

**Comment by srawlins** [comment]
Here is the rest of (a different repro of) the call to `DartNavigationComputerVisitor`:

<img width="1144" alt="Screen Shot 2022-11-23 at 3 03 29 PM" src="https://user-images.githubusercontent.com/103167/203660836-6072223f-fd0c-4670-8f20-327057038bcf.png">
<img width="1115" alt="Screen Shot 2022-11-23 at 3 03 56 PM" src="https://user-images.githubusercontent.com/103167/203660869-8f6aa467-e70d-4366-8e49-33b1fb56c76d.png">

**Comment by scheglov** [comment]
Typing a character. This changes the file overlay, which triggers file analysis, and when the resolved unit is received by the server, it starts computing notifications, such as the navigation and semantic highlighting.

**Comment by bwilkerson** [comment]
Sounds like we need a way to delay computing the notifications when a code completion request is already on the queue so that these tasks won't interfere with completions. Kind of sounds like a job for a scheduler.

**Comment by srawlins** [comment]
Ah that's a good point. Since I'm typing two things: `<backspace>` and then `.`, the requests might go something like:

1. user types `<backspace>`
1. IDE requests completions at `_x.entries^`
2. IDE requests navigations
3. etc.
4. user types `.`
5. IDE requests completions at `_x.entries.^`

so one or more navigation requests are in the pipe. And may be in progress, so they can't be cancelled.

**Comment by srawlins** [comment]
OK we will revert https://github.com/dart-lang/sdk/commit/ae7e3517c80532eaac28c8d718e5caaf06722b46 unless someone jumps on a fix forward, to dramatically reduce the introduced file system I/O.

**Comment by srawlins** [comment]
Looking at the code more, we call out to the file system for every import directive and export directive, in `_addUriDirectiveRegion`, during navigation-computation (on every edit to a file).

**Comment by bwilkerson** [comment]
Which probably wouldn't be a problem if we were cancelling obsolete navigation requests and scheduling them to happen after code completion requests.

**Comment by bwilkerson** [comment]
The lifetime of `_DartNavigationComputerVisitor ` is the duration of `computeDartNavigation`, so you don't need to clear the cache.

Yes, a string search is much faster than file I/O and will probably take care of the performance issue.
