### ISSUE TITLE
Lookup function does not work on arm

### ISSUE THREAD

**Issue by guyluz11** [dart-lang/sdk#50550]
Tested the function `InternetAddress.lookup` 

https://github.com/dart-lang/sdk/blob/7759f7fe032f1936194c45cf12dd5c6ad23d0f58/sdk/lib/io/socket.dart#L148

as reverse lookup of a hostname on my arm (also known as ARMv7 and armhf) Linux device and it crashed with the error

```dart
Unhandled exception:
SocketException: Failed host lookup: 'HPC0180319938E.local' (OS Error: Name or service not known, errno = -2)
#0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:506:9)
<asynchronous suspension>
#1      main (file:///my_project_path/network_tools/network_tools/example/main.dart:7:3)
<asynchronous suspension>
```

While the exact same line and same lookup string work on my intel 64 architecture (in the same network).

Tested with multiple lookups and I get the same result for all of them.

**Comment by guyluz11** [comment]
Not sure if the c implementation uses the ping command but `ping HPC0180319938E.local` returns `ping: HPC0180319938E.local: Name or service not known`

**Comment by mraleph** [comment]
Dart just uses `getaddrinfo`. Check your OS configuration - it might not have multicast DNS enabled.

**Comment by guyluz11** [comment]
In case anyone else have the same issue as stated [here](https://askubuntu.com/questions/772774/unknown-host-even-though-avahi-is-installed-and-running)  

`libnss-mdns` was missing 

`sudo apt install libnss-mdns`

 and `/etc/nsswitch.conf` content needed to change to 

`hosts:          files mymachines mdns4 [NOTFOUND=return] dns myhostname`
