### ISSUE TITLE
Question: Unnecessary `new` keyword

### ISSUE THREAD

**Issue by Coaspe** [dart-lang/sdk#50554]
As far as I know, using `new` keyword is totally optional from `Dart 2.0`. It's not mandatory to use it.
And I found a lot of posts related to that in StackOverflow like [this](https://stackoverflow.com/questions/50091389/do-you-need-to-use-the-new-keyword-in-dart).

However, while looking through the `broadcast_stream_controller.dart`, I saw a lot of `new` keywords being used.
Is there a reason for using `new` keyword like below?

![스크린샷 2022-11-25 오후 10 26 33](https://user-images.githubusercontent.com/76432686/203995427-813f60a2-0ad8-43d5-bd9b-63a91cf92ea9.png)
![스크린샷 2022-11-25 오후 10 26 37](https://user-images.githubusercontent.com/76432686/203995445-718ffe3f-97cc-49d6-85c8-a6afe6eea447.png)

**Comment by eernstg** [comment]
The most common argument I've heard is that it may help improve the readability of code in situations where a named constructor is called, and it's important for the comprehension of the code that we're creating a new object (as opposed to calling a static method).

```dart
class C {
  C.named();
  static int C.otherName() => 3;
}

void main() {
  var x = C.named(); // Can have `new`, which shows that it's a `C`.
  var y = C.otherName(); // Cannot have new, and isn't a `C`.
}
```

Of course, it makes no difference technically, and almost everybody will say "just get rid of `new` everywhere".

**Comment by lrhn** [comment]
Honest answer: Because we never bothered to remove them. The code works, and it hasn't really been touched in years. other than small tweaks.
If I were to make a larger refactoring or other bigger editing of the files, I'd probably remove all the `new`s, but so far it's just not been on anyone's radar.
