### ISSUE TITLE
How i can set a timeout to `await for` statement in listening to a stream?

### ISSUE THREAD

**Issue by r4444zy** [dart-lang/sdk#50556]
how i can stop the "await for" statement from listening to a stream after specific duration if there is no data coming (for example 5 seconds) ?

```
await for (s in stream) {  // if there is no data coming from the stream after 5 seconds ==> exit loop and move to the next line to execute.
.....
}
```

**Comment by lrhn** [comment]
I'd use `await for (var s in stream.timeout(const Duration(seconds: 5))) ...`.
That will cause the stream itself to throw (emit) a `TimeoutException` if there are no events for five seconds.
You'd have to catch that exception then.

If you just want to stop the loop, use 
```dart
await for (var s in stream.timeout(const Duration(seconds: 5), onTimeout: (s) => s.close())) ...
```
which closes the stream on a timeout.
