### ISSUE TITLE
Is there some native package for support quic protocol without http3

### ISSUE THREAD

**Issue by fengyeall111** [dart-lang/sdk#50562]
I've searched may places to find the package for support quic protocol without http3,but there is none.
eg:cronet dose not have quic conn but just http3client.
If we must use dart:ffi ,that's too bad. Why netstack is not part of the language？

**Comment by KellyKinyama** [comment]
Started the implementation at this repo: https://github.com/KellyKinyama/dart-quic
But the job is tough. Though I was able to parse i client hello from quic client.

**Comment by mraleph** [comment]
I would discourage implementing QUIC in pure Dart unless you want to do it as an exercise or you have some other strong reasons to do that. Instead choose a native implementation and figure out how to write FFI bindings to it.

**Comment by KellyKinyama** [comment]
Are there implementation examples based on ffi. If so, are they cross platform (windows, linux, android, apple, etc) and are as easy to use as dart?

**Comment by vukitoso** [comment]
> Are there implementation examples based on ffi. If so, are they cross platform (windows, linux, android, apple, etc) and are as easy to use as dart?

I don’t want to impose my solution on you; I just made some notes for myself.
I found the program sing‑box (https://github.com/SagerNet/sing-box) for working with VPNs; it supports a huge number of network protocols, a lot of them.

It has a separate graphical client:

for Android: https://github.com/SagerNet/sing-box-for-android, written in Kotlin
for iOS/macOS: https://github.com/SagerNet/sing-box-for-apple, written in Swift

But after looking through the source code a bit, I discovered that the graphical client’s code does not contain the business logic for handling the network protocols (DNS, QUIC, HTTP, HTTPS, TLS, SOCKS, Shadowsocks, ShadowTLS, VMess, VLESS, Hysteria, Hysteria2, TUIC, AnyTLS, Naive, Trojan, WireGuard, SSH).
The sing‑box developers told me that the business code resides in a library written in Go.

It is implemented via x/mobile (https://pkg.go.dev/golang.org/x/mobile) + gobind (https://pkg.go.dev/golang.org/x/mobile/cmd/gobind)

x/mobile – The Go mobile repository holds packages and build tools for using Go on mobile platforms.
gobind – Gobind generates language bindings that make it possible to call Go functions from Java and Objective‑C.

I have been looking for a cross‑platform language to build an application for all platforms with QUIC support for a long time. In the end, I concluded that if modern solutions are required, it is better to use a combination of a graphical interface written in one language and a library with business logic written in another language, as is done in sing‑box.

**Comment by KellyKinyama** [comment]
I am not very far from performing the first quic handshake in pure dart:
https://github.com/KellyKinyama/dart-quic/blob/master/lib/go_quic/hex_dump2.dart
