### ISSUE TITLE
CL "Add parser support for patternAssignment" introduces crashes in frontend test cases

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#50575]
In [Add parser support for patternAssignment](https://dart-review.googlesource.com/c/sdk/+/272383) I'm adding status file entries to expect crashes in the following frontend tests:

```
extensions/explicit_invalid_access
general/issue40242
rasta/malformed_function
```

The crashes are happening because these tests contain code that was previously invalid, but is now being parsed as a pattern assignment, and pattern assignment support is not yet complete:
- `extensions/explicit_invalid_access` contains `Extension(c) = 42;`
- `general/issue40242` contains `(c2) = new C();`
- `rasta/malformed_function` contains `(null) = null;`.

**Comment by stereotype441** [comment]
CC @johnniwinther @chloestefantsova

**Comment by johnniwinther** [comment]
`extensions/explicit_invalid_access` and `general/issue40242` no longer crashes.
