### ISSUE TITLE
Bleeding edge API docs are not accessible due to too many redirects

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#50590]
The bleeding edge API docs found at https://api.dart.dev/be seem to be broken due to too many redirects. I'm not familiar with the setup, but perhaps due to the recipe changes in https://dart-review.googlesource.com/c/recipes/+/263700, or changes required in https://github.com/dart-lang/api.dart.dev due to those other changes?

\cc @sortie @kevmoo

**Comment by sortie** [comment]
This is being fixed in https://github.com/dart-lang/api.dart.dev/pull/88.

**Comment by kevmoo** [comment]
Great to see this land. Who is going to deploy @sortie ? (CC @athomas )

**Comment by sortie** [comment]
I deployed it and it's live now
