### ISSUE TITLE
Add runtime type check for 'await' in DDC

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#50602]
This is a DDC part of https://github.com/dart-lang/sdk/issues/49396.

According to the spec, `await e` should check runtime type of `e` to be a `Future<flatten(S)>` where `S` is a static type of `e` before waiting for `e` (otherwise it should wait for `Future.value(e)`). See https://github.com/dart-lang/sdk/issues/49396 for details.

Kernel AST contains the type to check in `AwaitExpression.runtimeCheckType`.

@sigmundch @nshahan

**Comment by nshahan** [comment]
Waiting for test cases to be finalized and landed https://dart-review.git.corp.google.com/c/sdk/+/267422.

**Comment by nshahan** [comment]
Tests landed but contain unexpected compile time errors. It sounds like these should not be errors. Waiting on CFE work to accept the code in the test.

**Comment by alexmarkov** [comment]
You can also use `language/async/await_type_check_test` which was landed in 66f1dee48cee1fe06699fb62d45f79d92f440293 until those compile-time errors are sorted out.

**Comment by eernstg** [comment]
@alexmarkov and @nshahan, the definition of flatten turned out to be too aggressive (causing gratuitous loss of type information), so it was adjusted, cf. https://github.com/dart-lang/sdk/issues/49396#issuecomment-1344174457. Sorry about the inconvenience this may cause!
