### ISSUE TITLE
Document recommended memory limits.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#50605]
this is follow up on [go/notes-user-profile-for-devtools-memory-uxr](https://goto.google.com/notes-user-profile-for-devtools-memory-uxr)

It would be extremely useable to see documented recommendation on an application memory usage limit, depending on the target device family.

**Comment by srawlins** [comment]
Hi @polina-c where should this be documented, do you think?

**Comment by polina-c** [comment]
I think at https://dart.dev/guides > Development > Memory Management

And recently published memory concepts (https://docs.flutter.dev/development/tools/devtools/memory#basic-memory-concepts) can be moved here, because they should live in a central place, not in DevTools documentation.
