### ISSUE TITLE
Document how to detect out-of-memory crash

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#50606]
this is follow up on [go/notes-user-profile-for-devtools-memory-uxr](https://goto.google.com/notes-user-profile-for-devtools-memory-uxr)

It should be documented how to determine if application crashed because of memory issues.

**Comment by srawlins** [comment]
Hi @polina-c where should this be documented, do you think?

**Comment by polina-c** [comment]
The same place as specified here: https://github.com/dart-lang/sdk/issues/50605#issuecomment-1339825865

**Comment by polina-c** [comment]
https://github.com/dart-lang/site-www/issues/4419
