### ISSUE TITLE
[analysis_server] Extension reference not found in search.findElementReferences

### ISSUE THREAD

**Issue by sstasi95** [dart-lang/sdk#50604]
Hi,

search.findElementReferences doesn't find Extension's references, even though a member of that Extension is actually referenced. The extension's member reference is correctly found, but the extension itself is not.
The same thing doesn't happen with normal classes (maybe because the class constructor is explicitly called?).

Is this expected behaviour?

Code to reproduce the issue (using package:analysis_server_lib):
```
import 'dart:async';
import 'dart:io';

import 'package:analysis_server_lib/analysis_server_lib.dart';
import 'package:path/path.dart' as path;

class ServerHelper {
  static Future<ServerHelper> create() async {
    return ServerHelper(await AnalysisServer.create());
  }

  final AnalysisServer server;
  Directory tempDir;
  Map<String, List<AnalysisError>> errors = {};

  ServerHelper(this.server) : tempDir = Directory.systemTemp.createTempSync('tests');

  Future init() {
    server.analysis.onErrors.listen((AnalysisErrors e) {
      if (e.errors.isEmpty) {
        errors.remove(e.file);
      } else {
        errors[e.file] = e.errors;
      }
    });

    server.server.setSubscriptions(['STATUS']);
    return server.analysis.setAnalysisRoots([tempDir.path], []);
  }

  Stream get onAnalysisFinished {
    return server.server.onStatus.where((ServerStatus status) {
      return status.analysis != null && status.analysis!.isAnalyzing == false;
    });
  }

  Future<String> createFile(String filePath, String text) {
    String fullPath = path.join(tempDir.path, filePath);
    return server.analysis.updateContent(
      {fullPath: new AddContentOverlay(text)},
    ).then((_) => fullPath);
  }

  void dispose() {
    server.dispose();
    tempDir.deleteSync(recursive: true);
  }
}

Future<void> main() async {
  final helper = await ServerHelper.create();
  await helper.init();
  String main = await helper.createFile(
    'int_ext.dart',
    '''
extension FooExt on FooClass {
  bool get fooMemberExt => true;
}

class FooClass {
  bool get fooMember => true;
}

void fooBar() {
  FooClass().fooMember;
  FooClass().fooMemberExt;
}

void main(List<String> args) {
  fooBar();
}
''',
  );

  final member = await helper.server.search.getElementDeclarations(file: main);
  for (final res in member.declarations) {
    final id = await helper.server.search.findElementReferences(
      main,
      res.offset,
      true,
    );

    print('id: ${id.id} - ${id.element}');

    final sub = await helper.server.search.onResults.first;

    if (sub.results.isEmpty) {
      print('Not found: ${res.name}'); // FooExt not found, but I think it should be found
    }
  }

  helper.dispose();
}
```

* analysis_server_lib version: 0.2.3
* dart --version: Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "macos_arm64"

Thanks,

Simone

**Comment by scheglov** [comment]
Interesting, it seems that we do index and search extension references, but fail to find the element at the extension declaration.
```dart
extension MyExtension on int {
  void foo() {}
}

void f() {
  MyExtension(0).foo();
}
```
Here I can search (and rename) `MyExtension` in `MyExtension(0)`, but not in `MyExtension on int`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/274083

**Comment by sstasi95** [comment]
Thank you for looking into it. So, if I understand correctly, calling an extension method by explicitly calling the extension constructor will count as an extension reference, but if we call it with an instance of the extended class it won't.

This will count as a `MyExtension` reference:
`MyExtension(0).foo()`

This will not:
`0.foo()`

Did I understand correctly?

**Comment by scheglov** [comment]
We should distinguish the extension (a container) reference, and an extension method reference.
Usually you don't have to write `MyExtension(0)`, and only write to disambiguate, if there are two extensions on `int` with `foo` declare.
```dart
extension E1 on int {
  void foo() {}
}
extension E2 on int {
  void foo() {}
}
void f() {
  0.foo();
}
```
Without `E1(0)` or `E2(0)` we get `error: A member named 'foo' is defined in extension 'E1' and extension 'E2', and none are more specific. (ambiguous_extension_member_access at [my_test] bin/test4.dart:8)`.

So, yes, `0.foo()` is not a reference to `MyExtension`; it references `foo`.

**Comment by sstasi95** [comment]
Thank you for the clarification.
