### ISSUE TITLE
[vm/ffi] Support freeing `Pointer.fromFunction` trampolines

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50610]
Currently, we never free these trampolines. The argument being that we hand out a pointer to C and we don't know when C is done.

However, in C use cases where the user knows when they are done with it, they currently have no way to free the trampoline.

In Java (with `Runnable`) and ObjectiveC (with `Block`), we do know when we're done with a callback. Consequently, `package:jnigen` and `package:ffigen` could generate the calls to free the trampolines.

**Comment by liamappelbe** [comment]
> In Java (with Runnable) and ObjectiveC (with Block), we do know when we're done with a callback.

The way the ObjC bindings are written at the moment, there are no per-Block function pointers. There's a couple of trampolines that are used by *all* the blocks. So this wouldn't really apply.

There are 2 ways of constructing Blocks: from an ordinary Dart function, or from a native function pointer (which would usually be from Pointer.fromFunction). In the latter case, I suppose we could add a flag to the constructor that tells the Block that the function pointer was created by Pointer.fromFunction, and that the Block now owns the function pointer and should free it when it's destroyed.

**Comment by mkustermann** [comment]
Right now the `Pointer.fromFunction()` return values are functions that carry no state. As long as that's true, there's no reason to have a free mechanism.

Only if we start associating state with `Pointer.fromFunction()` (e.g. by having it an isolate/isolate-group state, or closure state) this becomes relevant.

What we **will need** is a mechanism for higher-level language bindings's to free dart-related state associated with their callbacks (e.g. ObjC blocks, Java objects that may refer to dart objects/closures). 
=> This is tracked already, see https://github.com/dart-lang/ffigen/issues/473, https://github.com/dart-lang/ffigen/issues/428

**Comment by liamappelbe** [comment]
`NativeCallable`s can be manually closed by the user, so this bug is essentially fixed even though you still can't close `Pointer.fromFunction` callbacks.

**Comment by dcharkes** [comment]
We should actually tell users to migrate. I've filed:

* https://github.com/dart-lang/sdk/issues/53524
