### ISSUE TITLE
Package dependency scripts are re-compiled on every run

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#50617]
I have a hunch this is related to the fact that `dart run` now runs a `pub get` on every single call.

To repro, on the latest dev (2.19.0-440.0.dev, not sure about older versions), just run `dart test` in any project that depends on `package:test`. You will see output like this each time:

```
Resolving dependencies in <your-package>... 
Got dependencies in <your-package>!
Building package executable... (6.2s)
Built test:test.
```

But it should only be rebuilding when the dependency is modified (package deps change).

I am marking this as a P1 because it causes a very significant downgrade to the experience of using package:test or any other command line tool - the compile step takes many seconds.

cc @jonasfj @sigurdm @mit-mit

**Comment by jakemac53** [comment]
We also seem to have lost the ability to do incremental rebuilds in pub

**Comment by jakemac53** [comment]
Fwiw I tried on stable (2.18.5) and it still emits the `Built test:test.` line, but it is much faster (sub second).

**Comment by jonasfj** [comment]
> I have a hunch this is related to the fact that dart run now runs a pub get on every single call.

Yeah, fixed in:
https://github.com/dart-lang/pub/commit/04f7bce84f0673874dc06b8603aa3f43a99432e9

Only affected pre-releases (so SDK builds).

I think we've rolled it into the SDK today or yesterday.

**Comment by jakemac53** [comment]
Closing this as I can confirm that it is fixed in the latest dev
