### ISSUE TITLE
UnmodifiableMapView - no errors thrown when attempting to read a key that does not exist, or when trying to access a key that does not exist

### ISSUE THREAD

**Issue by ApiJoe** [dart-lang/sdk#50627]
For dart objects that are of the family class 'UnmodifiableMapView', there is a problem of unthrown errors when you try to access  fields that do not exist within them, or try to add a field. For instance:

```
blockOfCode() {
  print('some code!');
}


myFunc() {
  final someUnmodifiableMap = myObjectDTO.document; 
  print('lets modify a field!');
  someUnmodifiableMap['privs'] = ['write','read']; // privs may or may not exist, but cannot modify regardless
  blockOfCode();
  print('done myFunc!');
}

myFunc();
print('done!');
```

In this example, the runtime will see the attempt to modify the value of 'privs'. Instead of throwing an error, what I'm finding is that the dart runtime will immediately eject out of the inner function, myFunc, and run the next line of code. So, while I would expect this output: 

```
lets modify a field!
some code!
done myFunc!
done!
```

I would get this instead:
```
lets modify a field!
done!
```

The problem is there are no errors thrown by the runtime when this happens.

I believe this also might happen when trying to access fields that do not exist, like in above:
```
final privileges = someUnmodifiableMap['pr1vs'] //mispelled
```

I believe it could also happen when a response object might be missing the field:
```
final privileges = PrivilegesDTO.fromJson(someUnmodifiableMap['privs']); 
```

Dart version - 2.18.5, Flutter 3.3.9, Windows 10.

**Comment by lrhn** [comment]
Does not reproduce for simple examples.

I'm using a `Map.unmodifiable(...)` map and running the code above, and it consistently throws an `UnsupportedError` when I try to modify the map, whether the key exists or not.

Tested in DartPad and 2.18.3 VM using code:
```dart
import "dart:collection";

void main() {
  blockOfCode() {
    print('some code!');
  }

  myFunc() {
    final someUnmodifiableMap = Map.unmodifiable({
      'privs': ['a']  // or other key name.
    });
    print('lets modify a field!');
    someUnmodifiableMap['privs'] = [
      'write',
      'read'
    ]; // privs may or may not exist, but cannot modify regardless
    blockOfCode();
    print('done myFunc!');
  }

  myFunc();
  print('done!');
}
```

Are you sure your version of `myFunc` is not `async`, and you are not awaiting it, because that would delay reporting the uncaught error until after printing `"done"`.
