### ISSUE TITLE
Process.runSync return bad exit codes.

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#50631]
I'm running command `dpkg -s certbot `to see if certbot is installed. In console, exit code is 0 when it is installed and 1 if not. But in Dart, running Process.runSync, exit code is always 0. This is painful.

UPDATE: Using Process.start method works fine, so I can say there is a bug in Dart Process.runSync (and maybe also in Process.run).

Dart SDK version: 2.18.5 (stable) (Tue Nov 22 15:47:29 2022 +0000) on "linux_x64".
System: Debian 9.5 (WSL on Windows 10) x64

**Comment by brianquinlan** [comment]
Would you include snippets for the working and non-working examples?

**Comment by busslina** [comment]
> Would you include snippets for the working and non-working examples?

### a) Executing linux command on console (correct behavior)
`dpkg -s certbot`
Exit code is 0 when certbot is installed on the system and 1 when is not installed.


### b) Executing linux command via Dart Process.runSync function (unexpected behavior)
```
final res = Process.runSync(
  'dpkg',
  [
    '-s',
    'certbot',
  ],
);
```
Exit code is 0 when certbot is installed on the system and also 0 when is not installed.

** I did not test it with Process.run (async) function, but may it also fail.
*** I also tested that function with argument 'runInShell' with both values true and false. Same unexpected behavior happend.

**Comment by busslina** [comment]
Is this solved?

**Comment by a-siva** [comment]
I tried the following example
```
asiva-desktop[sdk]>more ~/tmp/issue50631,dart
import 'dart:io';

main() {
  final res = Process.runSync(
    'dpkg',
    [
      '-s',
      'certbot',
    ],
  );
  print(res.exitCode);
}

asiva-desktop[sdk]>out/ReleaseX64/dart-sdk/bin/dart ~/tmp/issue50631,dart
1
asiva-desktop[sdk]>
```
and it produced the correct exit code on the latest version of Dart.
