### ISSUE TITLE
[vm] `pextrd` emitted on non-sse4.1 CPUs

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50640]
https://dart-review.googlesource.com/c/sdk/+/264240 introduced use of `pextrd`, but is not gated behind `TargetCPUFeatures::sse4_1_supported()`.

```c++
void HashDoubleOpInstr::EmitNativeCode(FlowGraphCompiler* compiler) {
  const XmmRegister value = locs()->in(0).fpu_reg();
  const Register temp = locs()->temp(0).reg();
  ASSERT(locs()->temp(1).reg() == EBX);
  ASSERT(locs()->temp(2).reg() == EDX);
  const XmmRegister temp_double = locs()->temp(3).fpu_reg();
  PairLocation* result_pair = locs()->out(0).AsPairLocation();
  ASSERT(result_pair->At(0).reg() == EAX);
  ASSERT(result_pair->At(1).reg() == EDX);

  // If either nan or infinity, do hash double
  compiler::Label hash_double, try_convert;

  // extract high 32-bits out of double value.
  __ pextrd(temp, value, compiler::Immediate(1));

// and two more below
```

```c++
void Assembler::pextrd(Register dst, XmmRegister src, const Immediate& imm) {
  ASSERT(TargetCPUFeatures::sse4_1_supported());
```

Reproduction: https://dart-review.googlesource.com/c/sdk/+/264842/49  `tools/test.py -n dartk-linux-debug-ia32-canary vm/dart_2/appjit_cha_deopt_test`
[Log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8795585264496857905/+/u/test_results/new_test_failures__logs_)

It's quite curious that we didn't hit it before, but we do with my CL.

@aam

**Comment by dcharkes** [comment]
Thanks @aam

**Comment by aam** [comment]
The regression was introduced in 2.19.0-407.0.dev so it's in beta candidate which was chosen at 2.19.0-444.0.dev
