### ISSUE TITLE
Analyzer 5.3.0 crashing on Flutter stable

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/sdk#50643]
```console
$ dart run build_runner build
Building package executable... 
Failed to build build_runner:build_runner:
../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart:8153:48: Error: The method 'elementAtOrNull' isn't defined for the class 'NodeListImpl<TypeAnnotationImpl>'.
 - 'NodeListImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
 - 'TypeAnnotationImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
Try correcting the name to the name of an existing method, or defining a method named 'elementAtOrNull'.
    var elementType = typeArguments?.arguments.elementAtOrNull(0)?.typeOrThrow;
```

**Comment by ahmednfwela** [comment]
had to revert to `5.2.0` because of this, I am guessing this is due to https://github.com/dart-lang/sdk/issues/49928 ?

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
See https://github.com/flutter/engine/pull/38114

https://github.com/dart-lang/collection/pull/217 that added `elementAtOrNull` landed 6 months ago, and was pulled into Dart SDK soon after. I would expect that 6 months should be enough to pull `package:collection` into Flutter. But if it is not, the solution is to restrict `package:analyzer` version.

**Comment by scheglov** [comment]
Ah, I see. `package:analyzer` should require at least `collection: ^1.17.0`.
My bad. I will fix it.

**Comment by lrincon-lealco** [comment]
Gracias

**Comment by scheglov** [comment]
I retracted `analyzer 5.3.0` from Pub.
I guess you will need to do `dart pub upgrade` again, maybe removing `.dart_tool/package_config.json`.
I have never done this before, so if you know better, please advise other people here.

**Comment by domesticmouse** [comment]
In my testing this is fixed. As my testing involves building up a project from scratch I'm unsure what is required to downgrade a project that has the retracted version. I'm hoping a `flutter pub upgrade` will do the right thing.
