### ISSUE TITLE
Dart Isolate extremely slow in release mode in background for iOS and Android

### ISSUE THREAD

**Issue by maxmitz** [dart-lang/sdk#50656]
I used Dart Isolate to do computational exhausting operations in the background with Flutter. I have a problem that for iOS and Android in release mode the operation more or less stops when I move it to the background. In the foreground, it works fine.

Did I do something wrong or is Dart Isolate not able to do this? Is this the right place to ask this question?

Thanks in advance and thanks for working on Dart!

A small example to test it:

main.dart

import 'dart:isolate';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool hasStarted = false;
  String? computationPercentage;
  Isolate? flutterIsolate;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextButton(onPressed: (hasStarted) ? () {} : () async => triggerComputationalExaustingTask(), 
            child: const Text("Start computation")),
            if(computationPercentage != null) Text(computationPercentage!)
          ],
        ),
      ),
    );
  }
  Future<void> triggerComputationalExaustingTask() async {
    setState(() {
      hasStarted = true;
    });

    final port = ReceivePort();
    port.listen((message) { 
      if(message == stopIsolateMessage) {
        flutterIsolate?.kill();
        setState(() {
          hasStarted = false;
        });
      } else if (message is String){
        setState(() {
          computationPercentage = message;
        });
      }
    });

    flutterIsolate = await Isolate.spawn(computationalExaustingTask, port.sendPort);
  }
}

const stopIsolateMessage = "STOP_ISOLATE";

@pragma('vm:entry-point')
void computationalExaustingTask(SendPort sendPort) {
  sendPort.send("0%");
  double bigNumber = 10000000000;

  for (double i = 0; i < bigNumber; i++){
    i++;
    i--;
    if (i % (bigNumber/100) == 0) {
      sendPort.send("${i* 100~/bigNumber}%");
    }
  }

  sendPort.send("Finished");
  sendPort.send(stopIsolateMessage);
}

**Comment by aam** [comment]
> Did I do something wrong or is Dart Isolate not able to do this? Is this the right place to ask this question?

The code looks fine.

>  I have a problem that for iOS and Android in release mode the operation more or less stops when I move it to the background. In the foreground, it works fine.

What is the equivalent code of running this computation in the foreground that you see that is running faster?
Did you have stopwatch readings to confirm that loop iteration in background isolate runs slower?

**Comment by maxmitz** [comment]
With foreground and background, I mean that I run the app in the foreground or in the background. The code is always started in the foreground. Can Dart Isolates be used for background processing or are they only used for multithreading?

Yes, I did stopwatch readings.

**Comment by insinfo** [comment]
Could it be that your problem is not related to this?
https://stackoverflow.com/questions/6650717/when-an-ios-application-goes-to-the-background-are-lengthy-tasks-paused

**Comment by aam** [comment]
Ah, yes, I see now. Sure, Android and iOS platforms have different mechanism to ensure that backgrounded apps don't drain the batteries, so it's unsurprising that you see fewer computation cycles available once your app goes into the background.
You might want to check https://docs.flutter.dev/development/packages-and-plugins/happy-paths/recommended#background-processing- and various approaches described in there.

Dart isolates by themselves allow for concurrent execution of Dart code, won't solve by themselves the problem of getting computational cycles allocated by Android/iOS for your backgrounded app.
