### ISSUE TITLE
Add `--warn-on-legacy-js-interop` flag to JS compilers (dart2js & DDC)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#50665]
Talking to @srujzs about this.

We should let folks OPT-IN to getting warnings here. We can use this on critical packages, etc in the short term to start pushing folks towards wasm-compatible JS-interop model.

CC @sigmundch ... and @joshualitt

**Comment by rakudrama** [comment]
Could this be a lint? That has everything needed to manage opt-in.

**Comment by kevmoo** [comment]
@rakudrama – great idea! I'd take it.

The only issue with a lint: it's not reported for ALL CODE.

I want to be able to compile https://gallery.flutter.dev/ – or some other big app – and see all of the spots that would need to get fixed to run w/ wasm (at least in theory)

**Comment by kevmoo** [comment]
Going to go with the lint idea. It's cleaner.
