### ISSUE TITLE
[analyzer] Unhandled exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#50660]
Hi, our users reported a strange null check exception https://github.com/dart-code-checker/dart-code-metrics/issues/1098 and after looking at source code I'm not sure that this is the expected behaviour https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/dart/element/member.dart#L624. I've also asked for the code example that produced the exception.

Also, the Element class declares the source property as nullable.
<img width="386" alt="Screenshot 2022-12-08 at 19 20 07" src="https://user-images.githubusercontent.com/21116742/206484311-e30fc7d6-6938-45c2-8604-ab3d1f2b55c7.png">

@bwilkerson @scheglov could you please take a look?

**Comment by incendial** [comment]
The example from our user https://github.com/dart-code-checker/dart-code-metrics/issues/1098#issuecomment-1342995946

**Comment by scheglov** [comment]
Yes, this example is what allowed me to reproduce it!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/274603

So, this is how to reproduce it.
```dart
void foo<T>({required int a}) {}

void f() {
  foo(a: 0);
}
```
Fortunately, this is not the issue that I thought it is initially, with completely synthetic `FunctionType` and its parameters.
