### ISSUE TITLE
[CP] cherry pick a rename of the `dart bug` ==> `dart info` command for 2.19

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#50662]
### Commit(s) to merge

eba9ada49e4, ccb092a5f4c, 793367c498

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/274480

### Issue Description

The 'dart bug' command was partially implemented when we branched for 2.19 and renamed after we branched.

### What is the fix

The fix is to cherry pick in the balance of the work (https://github.com/dart-lang/sdk/commit/793367c498da7ec7efda1a74d6663a941aeec932; rename the command from 'dart bug' to 'dart info', and complete windows support), as well as the two CLs that had landed in that space between the branch and the above CL (https://github.com/dart-lang/sdk/commit/eba9ada49e4 and https://github.com/dart-lang/sdk/commit/eba9ada49e4).

### Why cherry-pick

The cost of not cherry-picking would be:
- shipping a command named `dart bug` in 2.19, and then immediately renaming it in the next stable release (to `dart info`). W/ the cherry pick we can instead ship it initially as `dart info`
- not having windows support

### Risk

low

### Issue link(s)

none

**Comment by mit-mit** [comment]
SGTM

**Comment by vsmenon** [comment]
lgtm

**Comment by mit-mit** [comment]
@devoncarew is this done?
