### ISSUE TITLE
[CP] cherry-pick linter 1.31.0

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#50663]
### Commit(s) to merge

d5c1158b7b535457fb0370efc216c0371c534160, 636eec185b9a3c3d62a79afc3c85726e2aada430

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/274481

### Issue Description

Linter 1.30.0 has two issues w/ 2.19:

1. the recommended lint `prefer_equal_for_default_values` will double-report where there is newly introduced analyzer diagnostic
2. the core lint `unrelated_type_equality_checks` generates false positives in the updated `package:fixnum`

### What is the fix

Lands linter 1.31.0 that:

1. updates `prefer_equal_for_default_values` to not report for SDKs >=2.19
2. updates `unrelated_type_equality_checks` for the `package:fixnum` restructuring

### Why cherry-pick

Users of 2.19 will see lint noise.

(Note that these changes landed on Tuesday, *before* the feature cut-off, so really aren't cherry-picks. 🤷 )

/fyi @devoncarew 

### Risk

low

### Issue link(s)

https://github.com/dart-lang/linter/issues/3868, https://github.com/dart-lang/linter/issues/3864

**Comment by mit-mit** [comment]
SGTM, this was causing analysis in `package:fixnum` in the beta channel.

**Comment by vsmenon** [comment]
lgtm

**Comment by pq** [comment]
Fixed w/ https://dart-review.googlesource.com/c/sdk/+/274481.
