### ISSUE TITLE
Remove analyzer's deprecated analysis modes: no-implicit-casts and no-implicit-dynamic

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#50679]
When these are removed, we can close issues related to them:

* https://github.com/dart-lang/sdk/issues/26915
* https://github.com/dart-lang/sdk/issues/31013
* https://github.com/dart-lang/sdk/issues/37437
* https://github.com/dart-lang/sdk/issues/48617
* https://github.com/dart-lang/sdk/issues/48650

The new 'language' modes are documented here: https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks

**Comment by bwilkerson** [comment]
Do we want to set a milestone for this?

**Comment by srawlins** [comment]
Good idea. Just set to Dart 3 Alpha.

**Comment by parlough** [comment]
I completely missed this somehow, but looks like this removal was reverted in https://github.com/dart-lang/sdk/commit/94f20d77314a91489e2c32fd144b81f506822561. Perhaps reopen this so the removal doesn't get lost?

Do you have any extra context on why it was reverted?

**Comment by srawlins** [comment]
I think it was removed because some flutter customer tests referenced them.

**Comment by srawlins** [comment]
Removed.
