### ISSUE TITLE
Process.start() gets blocked when read stderr before stdout

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#50674]
In docs, it is said to read both stdout and stderr streams in order to release system resources:
- https://api.flutter.dev/flutter/dart-io/Process/start.html

> Users must read all data coming on the [stdout](https://api.flutter.dev/flutter/dart-io/Process/stdout.html) and [stderr](https://api.flutter.dev/flutter/dart-io/Process/stderr.html) streams of processes started with Process.start. If the user does not read all data on the streams the underlying system resources will not be released since there is still pending data.

I'm running on a AWS VM (Debian 11 x64).

Well, I did a execute function that do the recommended steps to execute linux commands. First read stderr stream, then stdout and finally exit code and returns. It worked well for me with commands like ln, chown, chmod, ... But failed (gets blocked) with unzip command. I resolved it partially by adding -qq flag, but I digged more and discovered that order matters (for Dart). So I switch order (first reading stdout, then stderr) and worked fine (with and without -qq flag).

I did other reads on Unix post in StackOverflow (https://stackoverflow.com/a/21654781/4681977) and it is said:

> You should not rely on ordering of stdout and stderr. They are two separate streams, and should be treated as such

So I guess there is a Dart bug here (or maybe Dart use other standard).

Thank you

UPDATE: the title maybe confuse someone, not getting blocked on Process.start(), but after process started, when reading stderr stream.

**Comment by brianquinlan** [comment]
Could you include a code example that demonstrates the issue?

**Comment by busslina** [comment]
> Could you include a code example that demonstrates the issue?


### a) Utility function
```
Future<clib.ProcResult> execute(
  String cmd, [
  List<String>? moreArguments,
]) async {
  // Parsing command into parts
  final parts = cmd.trim().split(' ');

  // Executing process
  late final Process process;
  try {
    process =
        await Process.start(parts.removeAt(0), [...parts, ...?moreArguments]);
  } catch (e) {
    // Failed execution
    return clib.ProcResult(
      failedExecution: true,
      failedExecutionError: e.toString(),
    );
  }

  // Reading stderr
  String stderr = '';
  await for (final list in process.stderr) {
    stderr += String.fromCharCodes(list);
  }

  // Reading stdout
  String stdout = '';
  await for (final list in process.stdout) {
    stdout += String.fromCharCodes(list);
  }

  // Constructing result
  return clib.ProcResult(
    exitCode: await process.exitCode,
    stderr: stderr,
    stdout: stdout,
  );
}
```

### b) Works okay
`final res = await execute('pwd');`

### c) Works okay
`final res = await execute('chmod +x /usr/local/bin/dart');`

### d) Unexpected behavior (gets blocked reading stderr stream)
`final res = await execute('unzip dart-sdk.zip');`

### e) Unexpected behavior (gets blocked reading stderr stream)
`final res = await execute('unzip -qq dart-sdk.zip');`

As I said before, d) and e) works okay changing the order (reading stdout stream before stderr stream).

** This is the version that failed, now current version of my function writes first to stdin, then reads stdout and finally reads stderr.

**Comment by brianquinlan** [comment]
Hey @busslina, 

I suspect that what is happening is that `unzip dart-sdk.zip` is blocking wait for someone to read from it's `stdout`, which you are not doing because you are blocked reading from it's `stderr`.

Try changing the code to use listen e.g.

```
process.stderr.listen(...)
process.stdout.listen(...)
```

**Comment by busslina** [comment]
> Hey @busslina,
> 
> I suspect that what is happening is that `unzip dart-sdk.zip` is blocking wait for someone to read from it's `stdout`, which you are not doing because you are blocked reading from it's `stderr`.
> 
> Try changing the code to use listen e.g.
> 
> ```
> process.stderr.listen(...)
> process.stdout.listen(...)
> ```
Whats up Brian,

I didn't try yet your proposal but I guess it will work as you expect, because 'listen' method is not blocking while 'await for' it is. But this does not change anything. You should be able to read stdout and stderr in the the order you want because they must be independent.

You suspect that the unzip command maybe is blocking to read from its stdout, but I don't think it can be done. You can block on stdin waiting for some data, but how it will block stdout? You only can write to stdout and there is no way to know if it has been readed, as far as I know.

**Comment by brianquinlan** [comment]
Hey @busslina,

Writing to stdout will eventually block when no one is reading from it. Imagine this case:

```
cat /dev/random | dart myprogram.dart
```

And myprogram.dart looks something like:
```dart
main() {
  while (true) {
    sleep(const Duration(seconds: 5));
    print(Stdin.readLineSync());
  }
}
```

Since `cat /dev/random` generates an infinite stream of data and `myprogram.data` reads the data slowly, `cat /dev/random` must eventually block because there is no where for the data to go.

The same applies to `unzip`.

I'm not sure how we could fix that in dart.

**Comment by busslina** [comment]
> Hey @busslina,
> 
> Writing to stdout will eventually block when no one is reading from it. Imagine this case:
> 
> ```
> cat /dev/random | dart myprogram.dart
> ```
> 
> And myprogram.dart looks something like:
> 
> ```dart
> main() {
>   while (true) {
>     sleep(const Duration(seconds: 5));
>     print(Stdin.readLineSync());
>   }
> }
> ```
> 
> Since `cat /dev/random` generates an infinite stream of data and `myprogram.data` reads the data slowly, `cat /dev/random` must eventually block because there is no where for the data to go.
> 
> The same applies to `unzip`.
> 
> I'm not sure how we could fix that in dart.

Yes, so what I undestand, if the case is an infinite program like `cat /etc/random`, stdout can block the reading of stderr or viceversa. I got it. But my case is a finit program (unzip), and also tested with -qq flag which tends to avoid printing info. So this is not the same type of case that `cat /dev/random | dart myprogram.dart`.

I opened this issue because I think Dart is not following the "Unix guidelines" (that I read [here](https://stackoverflow.com/questions/21654673/bash-stderr-captured-before-stdout/21654781#21654781), maybe he is wrong, but it makes sense to be order independent both out streams). I understand your point but I think it does not apply here. Also I discovered other bug that is related with this one (https://github.com/dart-lang/sdk/issues/50631), so I assume Dart is not very stable with Process related stuff. Lets say that I will share for anyone the code that I'm using and seems to work okay:

### a) execute function

```
Future<clib.ProcResult> execute(
  String cmd, [
  List<String>? moreArguments,
  void Function(IOSink sink)? stdinCbk,
]) async {
  cmd = cmd.trim();

  // Empty command
  if (cmd.isEmpty) {
    clib.error('Empty command');
  }

  // Parsing command into parts
  final parts = cmd.trim().split(' ');

  // Executing process
  late final Process process;
  final command = parts.removeAt(0);
  try {
    process = await Process.start(command, [...parts, ...?moreArguments]);
  } catch (e) {
    // Failed execution
    return clib.ProcResult(
      command: command,
      failedExecution: true,
      failedExecutionError: e.toString(),
    );
  }

  // Writing to stdin
  if (stdinCbk != null) {
    stdinCbk(process.stdin);
  }

  // Reading stdout
  String stdout = '';
  await for (final list in process.stdout) {
    stdout += String.fromCharCodes(list);
  }

  // Reading stderr
  String stderr = '';
  await for (final list in process.stderr) {
    stderr += String.fromCharCodes(list);
  }

  // Flushing stdin
  await process.stdin.flush();

  // Constructing result
  return clib.ProcResult(
    command: command,
    exitCode: await process.exitCode,
    stderr: stderr,
    stdout: stdout,
  );
}
```

### b) ProcResult class

```
class ProcResult {
  // Data
  final String command;

  final bool failedExecution;
  final String? failedExecutionError;

  late final int exitCode;
  late final String stderr;
  late final String stdout;

  /// Constructor.
  ProcResult({
    required this.command,
    this.failedExecution = false,
    this.failedExecutionError,
    int? exitCode,
    String? stderr,
    String? stdout,
  }) {
    // Bad usage I
    if (!failedExecution &&
        (exitCode == null || stderr == null || stdout == null)) {
      clib.error('Bad usage I');
    }

    // Bad usage II
    if (failedExecution && failedExecutionError == null) {
      clib.error('Bad usage II');
    }

    // Assigning values
    if (!failedExecution) {
      this.exitCode = exitCode!;
      this.stderr = stderr!;
      this.stdout = stdout!;
    }
  }

  // Getter functions
  //
  // - 01 - Success

  //#region
  /// 01 - Success.
  bool get success {
    return !failedExecution && exitCode == 0;
  }
  //#endregion

  // Functions
  //
  // - 01 - Crash
  // - 02 - Display

  //#region
  ProcResult crash({
    String? msg,
    bool onlyIfExecutionFailed = false,
    void Function()? beforeCrash,
  }) {
    // Failed exection
    if (failedExecution) {
      // Executing before crash function
      if (beforeCrash != null) {
        beforeCrash();
      }

      clib.error(
          'Process execution failed -- ${failedExecutionError!}${msg == null ? '' : ' -- $msg'}');
    }

    if (onlyIfExecutionFailed) {
      return this;
    }

    // Bad exit code
    if (!success) {
      // Executing before crash function
      if (beforeCrash != null) {
        beforeCrash();
      }

      clib.error(
          'Process returned with exit code: $exitCode${msg == null ? '' : ' -- $msg'} -- stderr: $stderr');
    }

    return this;
  }

  /// 02 - Display.
  void display() {
    print(stdout);
  }
  //#endregion

  // Override functions
  //
  // - 01 - To string

  //#region
  /// 01 - To string.
  @override
  String toString() {
    return 'ProcResult($command) -- Exit code: $exitCode -- Stdout: \'$stdout\' -- Stderr: \'$stderr\'';
  }
  //#endregion
}
```

**Comment by brianquinlan** [comment]
Hey @busslina ,

I don't think that Dart could easily have different behavior here and it is consistent with other environments that I just looked at i.e. Java, Node.js, Python and Ruby.

One thing that we can probably do better here is documenting the behavior. The [Python docs](https://docs.python.org/3/library/subprocess.html), for example, call out that reading from `stdin` or `stdout` can result in a deadlock in four differences places ;-) e.g.

![image](https://user-images.githubusercontent.com/8851008/208482001-a5ace43f-e524-4768-b3c6-81cea7922cef.png)

Node.js is more terse but they also [highlight the blocking behavior](https://nodejs.org/api/child_process.html#child-process).

Java [documents the issue but doesn't suggest a solution](https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html).

If you agree, then I'll change this to a documentation bug.

**Comment by busslina** [comment]
> Hey @busslina ,
> 
> I don't think that Dart could easily have different behavior here and it is consistent with other environments that I just looked at i.e. Java, Node.js, Python and Ruby.
> 
> One thing that we can probably do better here is documenting the behavior. The [Python docs](https://docs.python.org/3/library/subprocess.html), for example, call out that reading from `stdin` or `stdout` can result in a deadlock in four differences places ;-) e.g.
> 
> ![image](https://user-images.githubusercontent.com/8851008/208482001-a5ace43f-e524-4768-b3c6-81cea7922cef.png)
> 
> Node.js is more terse but they also [highlight the blocking behavior](https://nodejs.org/api/child_process.html#child-process).
> 
> Java [documents the issue but doesn't suggest a solution](https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html).
> 
> If you agree, then I'll change this to a documentation bug.

Well, Dart is a "young" language and platform, and we can everybody help to keem improving. Personally I like Dart a lot, coming from other languages like Java or Typescript, I think is in a good way. I can say is my preferred language and I want it still being my preferred one.

I will keep open this issue for the case anyone want to add anything, then I'm closing.

Thanks for your time Brian

**Comment by brianquinlan** [comment]
Hey @busslina ,

It's not that we are locked into design decisions made by other programming languages here but we are building on top of POSIX, which offers certain primitives. And, given those primitives, I don't know how we would accomplish the semantics that you want in a reasonably efficient way.

Please don't close the bug. I think that we need better documentation here.

**Comment by brianquinlan** [comment]
I have a proposed documentation change here:
https://dart-review.googlesource.com/c/sdk/+/276621
