### ISSUE TITLE
Front-end infers incorrect type when combining promoted type variable and `null`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#50677]
Example:
```dart
S foo<S extends Object>(S x, bool b) {
  if (x is int) {
    x.toRadixString(16);  // Valid
    S v = x; // Valid, so x has type S&int
    v = (b ? x : null); // No warning.
    Never z = (b ? x : null); // Type S?
    (b ? x : null).isEven; // No warning.
    return v;
  }
  return x;
}

void main() {
  foo<Object>(1, false);
}
```
This gives an error (in DartPad) of:
```
lib/main.dart:6:18:
Error: A value of type 'S?' can't be assigned to a variable of type 'Never'.
    Never z = (b ? x : null); // Type S?
                 ^
```
See #50676 for a similar analyzer issue.
The error here is valid, and just added to attempt to eek out the actual static type.
The problems are the missing errors in the `v = ...` and `...isEven` operations.

It's not as easy to see which type the front-end actually assigns to `(b ? x : null)` as in the analyzer, but it's *most likely* the same as the analyzer: `S? & int`, which is not a valid Dart type. (You can only promote type variables, `S?` is not a type variable.)

This type can explain why the expression is assignable to `v` of type `S`, because the `& int` with a non-nullable type in `S? & int` cancels the `?` from `S?`, and makes the result assignable to `S`.
And it explains the lack of warning when calling `.isEven`, because the `& int` takes precedence.

The result is incorrect. The value is actually `null`. If we comment out the `Never z = ...;` line, the program compiles and runs until it fails with:
```
Uncaught TypeError: Cannot read properties of null (reading '$and')Error: TypeError: Cannot read properties of null (reading '$and')
```
If I remove the `extends Object` from `S`, the error changes to
```
Uncaught TypeError: Cannot read properties of null (reading 'toString')Error: TypeError: Cannot read properties of null (reading 'toString')
```
which I recognize as a failed not-null assertion.

Valid static types would be `(S & int)?`, or possibly, if necessary, dropping the promotion and using `S?`.
(I don't know what we have specified, if anything.)

@stereotype441

**Comment by stereotype441** [comment]
Haha, looks similar to https://github.com/dart-lang/sdk/issues/49691, which I discovered a few months back.  It looks like @eernstg tried to propose a solution in https://github.com/dart-lang/language/pull/2427, but it never got reviewed.  (CC @leafpetersen who is tagged for code review of that PR)

**Comment by eernstg** [comment]
This has been resolved by the [spec change](https://github.com/dart-lang/language/pull/3435) that moved the 'UP' type function to handle intersection types earlier. The implementation issue is https://github.com/dart-lang/sdk/issues/54002.
