### ISSUE TITLE
Add an un-ignorable severity above "error".

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#50683]
Currently the analyzer can configure the severity of messages as "info", "warning" or "error".
It's also possible to ignore messages using `// ignore: problem_name`.

Would it make sense to have a severity *above* "error" which is an "error which cannot be ignored"?

This is hypothetical, I don't actually have a need for it myself (right now), so this is mainly to see if anyone *is* interested in the idea.

I could imagine teams where some (probably style-related) lints would be considered mandatory, and not allowed to be ignored. Or framework-related lints, which are really for your own protection.

Rather than having to check that in code-reviews, they could just set the severity to "fatal" (strawman name) in `analysis_options.yaml`, and then an `// ignore: ...` would not hide the error, and maybe the `// ignore: ...` itself would be an error (e.g., for `// ignore_for_file:` comments).

The existing workaround is to just educate your developers to not add such ignores, and to catch any mistakes in code-review.
But people like automation!

**Comment by incendial** [comment]
Love the idea of atomic un-ignorable rules, but what do you think about the ESLint approach to have a config option, which ignores all "disable-like" comments https://eslint.org/docs/latest/user-guide/configuring/rules#disabling-inline-comments?

<img width="700" alt="Screenshot 2022-12-12 at 14 15 27" src="https://user-images.githubusercontent.com/21116742/207020137-b4df4a3b-90b0-4520-839a-12e0d50d1a6e.png">

Or it's too strict and less flexible?

**Comment by bwilkerson** [comment]
I'm not sure whether it solves the problem, but analyzer supports a `cannot-ignore` key in the analysis options file whose value is a list of either the names of specific diagnostics or severities.

**Comment by lrhn** [comment]
That works too. It's even more general, because it can cause hints and warnings that cannot be ignored, not just errors.
It does require more typing (name the lint once to enable it, once to add it to the cannot-ignore list), but this would mostly make sense for large setups where a lot of code shares the same analysis options. A little more typing won't stop those who actually care enough to make the distinction.

So, accepted as solved.
