### ISSUE TITLE
Property escape sequences are not supported in this regex dialect

### ISSUE THREAD

**Issue by kirill-21** [dart-lang/sdk#50685]
![image](https://user-images.githubusercontent.com/63228361/206914960-f08938dd-3042-4e8f-8241-217c49930814.png)

**This is underlined as an error, however, it works.**

If you do not use Raw string than no error is shown and it works identically as on the first image
![image](https://user-images.githubusercontent.com/63228361/206914995-e14fe00f-4539-44b8-8af2-1071cbfd1665.png)

```dart
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
    • Flutter version 3.3.9 on channel stable at C:\Applications\SDKs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Applications\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
```

**Comment by asashour** [comment]
I guess this is IntellilJ plugin related, not an error from Dart SDK.

**Comment by kirill-21** [comment]
> I guess this is IntellilJ plugin related, not an error from Dart SDK.

Where should i report this issue then? I tried to look for something called like "dart analyzer" but did not find appropriate repo

**Comment by asashour** [comment]
Please look into [this](https://youtrack.jetbrains.com/issue/IDEA-305739/False-positive-Property-escape-sequences-are-not-supported-in-this-regex-dialect-using-Dart-plugin) and [this](https://youtrack.jetbrains.com/issue/SCL-17098), this seems to be IntelliJ-related, not Dart-specific.

**Comment by jacob314** [comment]
Fyi @jwren

**Comment by jwren** [comment]
As stated by @asashour , this is not a Dart or Flutter issue but an issue in IntelliJ, see the YouTrack issue linked above.
