### ISSUE TITLE
[CP] [vm/ffi] Fix FfiTrampolineData GC bug

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50695]
### Commit(s) to merge

e3e355e16a8b67ba6a1d7a83f837e8e69cf71534

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/275060

### Issue Description

GC crashes with FFI trampolines, happening on all platforms in JIT mode.

### What is the fix

Make the GC visit the `c_signature` field again.

### Why cherry-pick

Users are hitting this:

* https://github.com/dart-lang/sdk/issues/50678

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/50678

### Extra Info

cc @mkustermann

**Comment by itsjustkevin** [comment]
@mkustermann could you take a look at this cherry-pick request?

**Comment by mkustermann** [comment]
> @mkustermann could you take a look at this cherry-pick request?

@itsjustkevin LGTM

**Comment by itsjustkevin** [comment]
@dcharkes cherry-pick is approved, can you go ahead and push the gerrit cl?

**Comment by dcharkes** [comment]
I'm unfamiliar with the new process, you mean +2 in Gerrit?

I'd need a +1 on the CL.

**Comment by athomas** [comment]
Yes, you need to get the CL reviewed and then land it with the CQ as if it
was targeting main.

**Comment by mit-mit** [comment]
@dcharkes are you still working on this?

**Comment by dcharkes** [comment]
This was merged back in december.
