### ISSUE TITLE
[CP] Fix call-through-getter runtime handling.

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#50697]
### Commit(s) to merge

0150cddace45a62e6a0af8639256b39dec74355e

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/275101

### Issue Description

When `x.dyn:foo()` needs to be handled as `y = x.dyn:get:foo` + `y.dyn:call()`, the runtime incorrectly used `call()` for the second part. This can result in an incorrect noSuchMethod if `call` has no non-dynamic callers and is tree-shaken. If the target `call` has unboxed parameters or results, the caller and callee will disagree about whether they are unboxed and this can give an incorrect result or crash.

### What is the fix

The runtime is fixed to use `dyn:call()` for the second step.

### Why cherry-pick

Program execution can yield incorrect answers or crashes.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/116405

**Comment by itsjustkevin** [comment]
@a-siva

**Comment by a-siva** [comment]
lgtm, the change is small and risk is low. The change has already rolled into Flutter framework as part of Dart 3.0.0-8.0.dev

**Comment by itsjustkevin** [comment]
@rmacnak-google cherry-pick is approved, you can merge your change.

**Comment by athomas** [comment]
This is on stable now, but needs to be cherry-picked to beta as well or the fix won't be in 2.19.

**Comment by a-siva** [comment]
Should we create a CL for the beta branch ?

**Comment by itsjustkevin** [comment]
> Should we create a CL for the beta branch ?

Yes please, let's get this merged in before the holidays if possible!

**Comment by a-siva** [comment]
@rmacnak-google  has created a CL here https://dart-review.googlesource.com/c/sdk/+/275843

**Comment by itsjustkevin** [comment]
Thanks @a-siva and @rmacnak-google!

**Comment by mit-mit** [comment]
@rmacnak-google is this done?

**Comment by itsjustkevin** [comment]
Merged into Dart 2.18.6.
