### ISSUE TITLE
HttpRequest.requestedUri breaks  when host header contains port number 

### ISSUE THREAD

**Issue by ricardoboss** [dart-lang/sdk#50704]
Hi, I'm trying to write a proxy server in dart with a flutter GUI. The problem I am now facing is that the HttpRequest object doesn't provide the original url that was requested, which is quite strange for me (worked a lot with PHP and ASP.NET APIs). How can I get the originally requested URL (including host, port, scheme and path)?

I have a test application set up: 

(https://github.com/ricardoboss/dart_http_server/blob/main/bin/dart_http_server.dart)

```dart
import 'dart:io';

void main() async {
  final server = await HttpServer.bind(InternetAddress.anyIPv4, 7000);
  print("Server is running");
  await for (final request in server) {
    print("uri: ${request.uri}");
    print("scheme: ${request.uri.scheme}");
    print("host: ${request.uri.host}");
    print("port: ${request.uri.port}");
    print("path: ${request.uri.path}");
    print("http host: ${request.headers.host}");
    print("http port: ${request.headers.port}");

    request.response.close();
  }
}
```

...that prints the following output if I access the server address:

```
Server is running
uri: /
scheme: 
host: 
port: 0
path: /
http host: localhost
http port: 7000
uri: /favicon.ico
```

If I set this server as my proxy, I can see that requests to other servers contain _some_ of the information I want, but in the wrong fields:

```
uri: www.google.com:443
scheme: www.google.com
host: 
port: 0
path: 443
http host: www.google.com
http port: 443
uri: go.microsoft.com:443
scheme: go.microsoft.com
host: 
port: 0
path: 443
http host: go.microsoft.com
http port: 80
```

Strangely, sometimes it works, but only very rarely:

```
uri: http://google.com/
scheme: http
host: google.com
port: 80
path: /
http host: google.com
http port: 80
```

Do you have any explanation why that happens? Anything I am doing wrong? Do I need to use a different HTTP server? Is this a bug in `dart:io`?

Any help is very much appreciated!

`dart --version`: `Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "windows_x64"`

**Comment by mraleph** [comment]
You are likely looking for the [`HttpRequest.requestedUri`](https://api.dart.dev/be/180360/dart-io/HttpRequest/requestedUri.html) rather than `HttpRequest.uri`. 

In HTTP protocol does not actually transmit _originally requested URL_, so it is lost... The best you can do is to reconstruct it using information you have. See RFC9112 for more details: https://www.rfc-editor.org/rfc/rfc9112#name-reconstructing-the-target-u

**Comment by ricardoboss** [comment]
@mraleph the issue persists. Why have you closed the issue?

**Comment by mraleph** [comment]
Yeah the fact that this crashes seems like potentially a bug. Could you dump your whole headers? `print(reuqest.headers)`.

**Comment by ricardoboss** [comment]
(I see you tagged `os-ios`, but I actually experienced this on Windows as the `dart --version` output says)

**Comment by brianquinlan** [comment]
I was able to reproduce this with:
```
curl -v --proxy http://localhost:9000 http://google.com
*   Trying 127.0.0.1:9000...
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET http://google.com/ HTTP/1.1
> Host: google.com
> User-Agent: curl/7.85.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: text/plain; charset=utf-8
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-length: 0
<
* Connection #0 to host localhost left intact
```

The output from the dart server looks like:
```dart
void main() async {
  final server = await HttpServer.bind(InternetAddress.anyIPv4, 9000);
  print("Server is running");
  await for (final request in server) {
    print("New request: ${request.uri}"); // google.com:443
    print("scheme: ${request.uri.scheme}"); // google.com
    print("host: ${request.uri.host}"); // ''
    print("port: ${request.uri.port}"); // 0
    print("path: ${request.uri.path}"); // 443
    print("http host: ${request.headers.host}"); // google.com
    print("http port: ${request.headers.port}"); // 443
    try {
      print("requested uri: ${request.requestedUri}");
    } catch (e) {
      print("requested uri (exception!): ${e.toString().trim()}");
    }
    // http: //google.comhttp//google.com
    print("\nHeaders:");
    print(request.headers);
    // user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46
    // proxy-connection: keep-alive
    // host: google.com:443

    request.response.close();
  }
}
```

My first instinct is that we only handling the `abs_path` production of the `Request-URI` described in [RFC-2616 5.1.2](https://www.rfc-editor.org/rfc/rfc2616#section-5.1.2).

But the code looks correct to me. I'll step through it after lunch ;-)

**Comment by brianquinlan** [comment]
I have a fix for review here: https://dart-review.googlesource.com/c/sdk/+/278481
