### ISSUE TITLE
JavaScript compilers support for `--null-assertions` in Dart 3.0

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#50711]
Regarding the `--null-assertions` flag. It provides enhanced null safety errors when running without sound null safety. It was added as a tool to assist in large scale migrations so you can migrate a library and get some null safety errors at runtime when testing an app that isn't fully migrated. I believe this feature is considered totally obsolete in a world where all code being compiled should be null safe.

For DDC this is a question of what flags are supported when you try to run a debug app with package:webdev or flutter web. For dart2js it includes those and what flags are available through `dart compile js`.

cc @sigmundch @jakemac53 @fishythefish @mit-mit @itsjustkevin

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/pull/3424 drops support for this flag in build_runner so we won't pass it to the compilers any more (specifically kernel, ddc, and dart2js).

**Comment by nshahan** [comment]
Just waiting on the unsound null safety flags to be removed from Flutter tool.

**Comment by mit-mit** [comment]
@nshahan is there a tracking issue for the Flutter tool flag issue?

**Comment by nshahan** [comment]
@mit-mit yes the flag handling cleanup got rolled into https://github.com/flutter/flutter/issues/118810.
