### ISSUE TITLE
CyclicInitializationError co19 tests need update

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#50723]
There are new test failures on [[3.0 alpha] Remove deprecated dart:core errors](https://dart-review.googlesource.com/c/sdk/+/259041).

The tests
```
co19/LibTest/core/CyclicInitializationError/CyclicInitializationError.class_A01_t01 CompileTimeError (expected Pass)
co19/LibTest/core/CyclicInitializationError/CyclicInitializationError.class_A01_t02 CompileTimeError (expected Pass)
co19/LibTest/core/CyclicInitializationError/CyclicInitializationError_A01_t01 CompileTimeError (expected Pass)
co19/LibTest/core/CyclicInitializationError/CyclicInitializationError_A01_t02 CompileTimeError (expected Pass)
co19/LibTest/core/CyclicInitializationError/variableName_A01_t01 CompileTimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-mac-debug-x64
dartk-weak-asserts-mac-debug-x64
```

**Comment by lrhn** [comment]
Does https://github.com/dart-lang/co19/issues/1598 mean that we need to roll co19 changes into the SDK?

**Comment by whesse** [comment]
That commit has already rolled into the SDK, the issue is fixed.  Can be seen that the tests have all been removed, at

[](https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LibTest/core&showAll)
