### ISSUE TITLE
windows platform compile error！

### ISSUE THREAD

**Issue by x64bugreport** [dart-lang/sdk#50722]
https://github.com/dart-lang/sdk/wiki/Building
I followed the documentation exactly, but got an error.
Environment: win11+vs2022 Enterprise Edition

error:
J:\deskstop\flutter-engine\dart-sdk\sdk>.\tools\build.py --no-goma --mode debug --arch x64 create_sdk
ERROR at dynamically parsed input that //build/toolchain/win/BUILD.gn:247:24 loaded :4:3: Invalid token.
C:\Program Files/Microsoft Visual Studio/2022/Enterprise
  ^
I have no idea what this is.
See //build/toolchain/win/BUILD.gn:283:1: whence it was called.
win_toolchains(target_cpu) {
^---------------------------
See //BUILD.gn:11:1: which caused the file to be included.
group("default") {
^-----------------
Command failed: J:\deskstop\flutter-engine\dart-sdk\sdk\buildtools\gn.exe gen out\DebugX64 --ide=vs --args=target_os="win" host_cpu="x64" target_cpu="x64" dart_target_arch="x64" dart_use_compressed_pointers=false dart_use_crashpad=false dart_snapshot_kind="app-jit" dart_use_fallback_root_certificates=true bssl_use_clang_integrated_as=true dart_use_tcmalloc=false dart_use_mallinfo2=false is_debug=true is_release=false is_product=false dart_debug=true dart_runtime_mode="develop" exclude_kernel_service=false is_clang=true dart_vm_code_coverage=false is_asan=false is_lsan=false is_msan=false is_tsan=false is_ubsan=false is_qemu=false dart_platform_sdk=false use_goma=false goma_dir="None" verify_sdk_hash=true
buildtools/ninja/ninja -C out\DebugX64 create_sdk
ninja: error: loading 'build.ninja': 系统找不到指定的文件。

ninja: Entering directory `out\DebugX64'
BUILD FAILED

I have to complain that your build tools are so hard to use. When I compiled flutter, a third-party library reported an error. Simply compiling dart still reports an error, which is really unfriendly.

**Comment by x64bugreport** [comment]
J:\deskstop\flutter-engine\dart-sdk\sdk>.\tools\build.py --no-goma --mode release --arch x64 create_sdk
Traceback (most recent call last):
  File "J:/deskstop/flutter-engine/dart-sdk/sdk/build/toolchain/win/setup_toolchain.py", line 315, in <module>
    main()
  File "J:/deskstop/flutter-engine/dart-sdk/sdk/build/toolchain/win/setup_toolchain.py", line 273, in main
    env = _LoadToolchainEnv(cpu, toolchain_root, win_sdk_path, target_store)
  File "J:/deskstop/flutter-engine/dart-sdk/sdk/build/toolchain/win/setup_toolchain.py", line 189, in _LoadToolchainEnv
    return _ExtractImportantEnvironment(variables)
  File "J:/deskstop/flutter-engine/dart-sdk/sdk/build/toolchain/win/setup_toolchain.py", line 67, in _ExtractImportantEnvironment
    raise Exception(
Exception: Path "C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\um" from environment variable "include" does not exist. Make sure the necessary SDK is installed.
ERROR at //build/toolchain/win/BUILD.gn:248:24: Script returned non-zero exit code.
  win_toolchain_data = exec_script("setup_toolchain.py",
                       ^----------
Current dir: J:/deskstop/flutter-engine/dart-sdk/sdk/out/ReleaseX64/
Command: J:/deskstop/flutter-engine/depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe J:/deskstop/flutter-engine/dart-sdk/sdk/build/toolchain/win/setup_toolchain.py "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" "C:\Program Files (x86)\Windows Kits\10" "C:\WINDOWS\System32;C:\WINDOWS\SysWOW64;Arm64Unused" win x64 environment.x64
Returned 1.
See //build/toolchain/win/BUILD.gn:284:1: whence it was called.
win_toolchains(target_cpu) {
^---------------------------
See //BUILD.gn:11:1: which caused the file to be included.
group("default") {
^-----------------
Command failed: J:\deskstop\flutter-engine\dart-sdk\sdk\buildtools\gn.exe gen out\ReleaseX64 --ide=vs --args=target_os="win" host_cpu="x64" target_cpu="x64" dart_target_arch="x64" dart_use_compressed_pointers=false dart_use_crashpad=false dart_snapshot_kind="app-jit" dart_use_fallback_root_certificates=true bssl_use_clang_integrated_as=true dart_use_tcmalloc=false dart_use_mallinfo2=false is_debug=false is_release=true is_product=false dart_debug=false dart_runtime_mode="develop" exclude_kernel_service=false is_clang=true dart_vm_code_coverage=false is_asan=false is_lsan=false is_msan=false is_tsan=false is_ubsan=false is_qemu=false dart_platform_sdk=false use_goma=false goma_dir="None" verify_sdk_hash=true
buildtools/ninja/ninja -C out\ReleaseX64 create_sdk
ninja: error: loading 'build.ninja': 系统找不到指定的文件。

ninja: Entering directory `out\ReleaseX64'
BUILD FAILED

J:\deskstop\flutter-engine\dart-sdk\sdk>

**Comment by whesse** [comment]
It looks like the script build/vs_toolchain.py is not correctly finding your WIndows SDK and your MSVS installation.
The environment variables 'WINDOWSSDKDIR' and 'GYP_MSVS_OVERRIDE_PATH' can be used to specify the correct values of these.

**Comment by x64bugreport** [comment]
> It looks like the script build/vs_toolchain.py is not correctly finding your WIndows SDK and your MSVS installation. The environment variables 'WINDOWSSDKDIR' and 'GYP_MSVS_OVERRIDE_PATH' can be used to specify the correct values of these.

Thanks for the reply, I found that the windows sdk version 10.0.20348.0 must be installed before compiling. My computer contains other versions of sdk, but it cannot build normally. I hope that the build script can output more logs, which is convenient for users to troubleshoot problems, thank you!
