### ISSUE TITLE
[Class modifiers] Implement feature in the CFE

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#50727]

**Comment by kallentu** [comment]
Quick update for the CFE work:
All the work here is done except `It is a compile-time error if a subtype of a declaration marked base or final is not marked base, final, or sealed` which is the last loophole I need to close. Otherwise, everything functions as the spec expects.

**Comment by kallentu** [comment]
The one last loophole landed as of today. Done all necessary work in CFE.

**Comment by itsjustkevin** [comment]
Thanks @kallentu
