### ISSUE TITLE
Clearly define future-proof JS-interop

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#50721]
Update: all js interop is tracked in https://github.com/dart-lang/sdk/issues/49353 and https://github.com/orgs/dart-lang/projects/65/views/1

---

Working with @srujzs on this. Some combination of SDK constraint, pkg:js version, and `@staticInterop`

See also

- https://github.com/dart-lang/linter/issues/3892
- https://github.com/dart-lang/sdk/issues/50665
- https://github.com/dart-lang/site-www/issues/4331
- https://github.com/dart-lang/site-www/issues/4450
- https://github.com/firebase/flutterfire/issues/10118
- https://github.com/flutter/flutter/issues/117022

**Comment by srujzs** [comment]
Below are the set of features we expect to work across both the JS and Wasm compilers for JS interop. Inline classes will be in this list, but they don't exist yet. :)

Disclaimer: The following should work, but none of this necessarily works **performantly** on dart2wasm. That's a longer-term project involving JS types that will need further work and user migration.

Dart SDK Constraint: >= 2.19
`package:js` constraint >= 0.6.6-dev (if you want mocking) and >= 0.6.5 (if you don’t care for it)

- Subset of `package:js`
    - [@staticInterop interfaces](https://github.com/dart-lang/sdk/tree/main/pkg/js#staticinterop)
        - External factory constructors with and without `@anonymous`
        - External `static` class members
        - External non-`static` extension members on a `@staticInterop` class (fields, getters, setters, methods)
        - Non-external extension members on a `@staticInterop` class
    - Top-level external members
    - [@JSExport](https://github.com/dart-lang/sdk/tree/main/pkg/js#jsexport-and-js_utilcreatedartexport) to do mocking and exports (version >= 0.6.6-dev)
- Subset of `dart:js_util` (these are just the current ones that work, we may add more before Dart 3 for dart2wasm)
    - `jsify`
    - `dartify`
    - `getProperty`
    - `hasProperty`
    - `setProperty`
    - `callMethod`
    - `callConstructor`
    - `instanceof`
    - `promiseToFuture`
    - `globalThis`
    - `newObject`
    - `createStaticInteropMock`
    - `createDartExport`
    - `allowInterop`

**Comment by kevmoo** [comment]
Awesome, @srujzs – thanks!

RE `package:js` – are we going to publish `0.6.6` along with Dart 2.19?

**Comment by parlough** [comment]
We don't really have any JS interop docs on dart.dev right now, but would it be worth mentioning (alongside 2.19) in [JS Interop](https://dart.dev/web/js-interop) that Dart's JS interop story is currently evolving and to stick to these to help ease the transition?

\cc @MaryaBelanger

**Comment by kevmoo** [comment]
We should absolutely create a tracking issue in https://github.com/dart-lang/site-www/ and put it in my list at the top, @parlough 

I don't think this is super urgent to get landed the day 2.19 launches – but early-ish in 2023 would be great.

I swear I chatted with @atsansone about this, too – but maybe not.

**Comment by parlough** [comment]
We have a tracking issue for general `@staticInterop` docs: https://github.com/dart-lang/site-www/issues/4331

I've created a new issue to track the possibility of outlining the defined "future-proof" JS-interop mentioned here: https://github.com/dart-lang/site-www/issues/4450

**Comment by eernstg** [comment]
>  Inline classes will be in this list, but they don't exist yet. :)

They _can_ exist now: https://github.com/dart-lang/language/blob/master/accepted/future-releases/inline-classes/feature-specification.md.

**Comment by srujzs** [comment]
> RE `package:js` – are we going to publish `0.6.6` along with Dart 2.19?

Yeah, I think we should. Mocking is useful - I'll plan on publishing today.

Re: documentation - In the tracking issue, we originally thought of having a polished syntax for `@staticInterop` for Dart 3, but it's looking very likely we can get interop with inline classes out instead, making that unneeded.

As for whether it's worth documenting future-proof interop, I think it's worth it, with a disclaimer that this is really meant for people eagerly interested in making dart2wasm work, and we'll codify better syntax in Dart 3.

**Comment by srujzs** [comment]
I think this is resolved. There is some other stuff that was proposed for this but we haven't done, and we might not do for the context of this bug. @kevmoo , any objections?

**Comment by sigmundch** [comment]
sgtm, I was about to ask too. Based on @itsjustkevin proposal this week for improving our tracking, seems like we could move any remaining work to individual tasks in our project page, and potentially use a different issue for all future discussions of the feature. Do we have the canonical bug for that yet?

**Comment by srujzs** [comment]
We have the project here: https://github.com/orgs/dart-lang/projects/65, but I don't think we have a bug to keep track of all future discussions on next-gen interop. I think you had one that labeled work for Dart 3 (before we decided to add JS types), but I can't seem to find it. We could repurpose/update that.

**Comment by itsjustkevin** [comment]
> sgtm, I was about to ask too. Based on @itsjustkevin proposal this week for improving our tracking, seems like we could move any remaining work to individual tasks in our project page, and potentially use a different issue for all future discussions of the feature. Do we have the canonical bug for that yet?

I created https://github.com/dart-lang/sdk/issues/52684 last month based on some prior conversation we had.  Could this be used as the discussion issue?

**Comment by ditman** [comment]
This doc page was very handy responding to a customer, and I had no idea it existed. 🙏

**Comment by sigmundch** [comment]
> ... I created https://github.com/dart-lang/sdk/issues/52684 last month based on some prior conversation we had. Could this be used as the discussion issue?

I fear that issue may be more for inline classes and not necessarily the right place for interop related discussions.

Searching for previous issues we have used for this purpose, I came across this other issue:
https://github.com/dart-lang/sdk/issues/49353

Seems like potentially a good candidate (and looks like we'll want to transfer all of the subissues to our project too)

**Comment by sigmundch** [comment]
I'm going to go ahead and close this issue in favor of #49353
