### ISSUE TITLE
[Class modifiers] Syntax highlighters implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#50730]
Cobbling together the list from past issues:

* [x] https://github.com/dart-lang/dart-syntax-highlight/ (@DanTup)
  * https://github.com/dart-lang/dart-syntax-highlight/pull/38
* [x] https://github.com/highlightjs/highlight.js (@srawlins)
  * issue: https://github.com/highlightjs/highlight.js/issues/3725
  * PR: https://github.com/highlightjs/highlight.js/pull/3726
* [x] https://github.com/codemirror/CodeMirror/ (@domesticmouse)

**Comment by srawlins** [comment]
A note for tracking: These features are completed "out-of-band": they do not require changes to the Dart SDK or the Flutter repositories, so they can be landed after the Beta 3 deadline. I think it is still good to track them with the Beta 3 milestone for now.

**Comment by itsjustkevin** [comment]
See https://github.com/dart-lang/sdk/issues/49752

**Comment by leafpetersen** [comment]
Any updates here?

**Comment by vsmenon** [comment]
@domesticmouse - per checklist above - is there any work here you were planning on? And anything blocking?

**Comment by vsmenon** [comment]
ping

@domesticmouse @itsjustkevin - do we have anything left here?  I don't think this would block a release.  Should we move to cleanup?

**Comment by domesticmouse** [comment]
I believe CodeMirror is ready for this release. I added the appropriate keywords, and I think it's been through CodeMirror's monthly release cycle.

**Comment by vsmenon** [comment]
Thanks, I will go ahead and close this one.
