### ISSUE TITLE
[Class modifiers] Dart2js implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#50732]

**Comment by sigmundch** [comment]
We don't believe there will be any work on the backend, but assigning to @rakudrama to make the final call

**Comment by itsjustkevin** [comment]
@rakudrama any word on if this is necessary or not?  If not can we close this issue out?

**Comment by kallentu** [comment]
There are no runtime semantics so nothing d2js needs to do, I believe, but @rakudrama can let me know if I'm mistaken.

**Comment by itsjustkevin** [comment]
@rakudrama is this safe to close?

**Comment by rakudrama** [comment]
No dart2js-specific work was required.
