### ISSUE TITLE
[Class modifiers] DDC implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#50731]

**Comment by nshahan** [comment]
Currently we don't expect any implementation needed on our side to support the feature. Leaving this open until we have a better test suite and know there are no new AST nodes any new patterns are working as expected.

This feature could unlock some changes to how we compile code if we have a better idea of what classes are actually mixed-in. I'm excited to investigate more in the future.

**Comment by kallentu** [comment]
@nshahan fyi, classes can no longer be mixed in (anywhere, in or out of library) in Dart 3 unless they are using the `mixin` modifier. So only `mixin class`es and `mixin`s can be mixed in.
Not sure if that changes anything on the DDC side.

But besides that, there are no runtime semantics so I don't think there's any work needed on the DDC.

**Comment by nshahan** [comment]
🎉 🍾 🎊  I saw that and I am so happy! 

This will unlock some changes that we can make in DDC but nothing required for Dart 3. I have ideas that will allow us to simplify our handling of mixins and fix some correctness bugs that have been around for a long time.

**Comment by nshahan** [comment]
With the completion of https://github.com/dart-lang/sdk/issues/50727 I still don't see any issues on the DDC side. I'm closing this with the understanding that we don't need to handle anything new from the CFE for this feature.
