### ISSUE TITLE
[Class modifiers] Analysis server / IDE support work

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#50737]
This is the issue tracking the work that needs to be done in the analysis server to support the class modifiers feature. If you decide to work on a feature, either create an issue for the feature and link to it from here, or put your name beside the feature so that we don't duplicate effort.

- [x] Call Hierarchy
  (brianwilkerson, NA)
- [x] Closing Labels
  (brianwilkerson, NA)
- [x] Code Completion
  Need to suggest the new modifiers and filter out suggestions that are invalid based on class capabilities
- [x] Code Folding
  (brianwilkerson, NA)
- [x] documentSymbol
  (brianwilkerson, NA)
- [x] Flutter Outline
  (brianwilkerson, NA)
- [x] Hovers
  Need to add the new modifiers to the hover help
- [x] Implemented Markers
  (brianwilkerson, NA)
- [x] Navigation
  (brianwilkerson, NA)
- [x] Occurrences
  (brianwilkerson, NA)
- [x] Organize Imports
  (brianwilkerson, NA)
- [x] Outline
  NA
- [x] Overrides Markers
  (brianwilkerson, NA)
- [x] #51496
  Needs review
- [x] #51440
  (@pq)
- [x] Refactorings - legacy
  (brianwilkerson, NA)
- [x] Refactorings - self describing
  (brianwilkerson, NA)
- [x] Search - Find References
  (brianwilkerson, NA)
- [x] Search - Member Declarations
  (brianwilkerson, NA)
- [x] Search - Member References
  (brianwilkerson, NA)
- [x] Search - Top-level Declarations
  (brianwilkerson, NA)
- [x] selectionRange
  (brianwilkerson, NA)
- [x] Semantic Highlights
  Highlight new keywords
- [x] signatureHelp
  (brianwilkerson, NA)
- [x] Snippets
  (brianwilkerson, NA)
- [x] Sort Members
  (brianwilkerson, NA)
- [x] Type Hierarchy
  (brianwilkerson, NA)

**Comment by pq** [comment]
We're pushing Class Modifier quick-fixes until post-beta (pending further investigation into what we want to support) so I think this issue is good to close as complete.
