### ISSUE TITLE
[Class modifiers] VM debugging support

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#50743]

**Comment by itsjustkevin** [comment]
No action needed

**Comment by a-siva** [comment]
//cc @bkonyi @derekxu16

**Comment by itsjustkevin** [comment]
@a-siva is there VM debugging support required for this feature?

**Comment by a-siva** [comment]
> @a-siva is there VM debugging support required for this feature?

The work would primarily be around ensuring the VM service protocol changes made for this feature (see https://github.com/dart-lang/sdk/issues/50742) are implemented in the VM and ensuring that clients like devtools etc. are able to consume it.

**Comment by mit-mit** [comment]
Could this be beta 3?
