### ISSUE TITLE
TypeError.toString() message  has regressed for simple types

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#50756]
Consider the following test, which would have passed in older SDKs.

```dart
import 'package:test/test.dart';

void main() {
  test('TypeError "null as String" text does not mention type parameters', () {
    try {
      var x = null as String;
      print(x);
    } on TypeError catch (e) {
      expect(e.toString(),
          "type 'Null' is not a subtype of type 'String' in type cast'');
    }
  });
}
```

This now fails as follows:

```
Expected: 'type \'Null\' is not a subtype of type \'String\' in type cast\''
Actual: 'type \'Null\' is not a subtype of type \'String\' of \' in type cast\''
```

It looks like it is maybe trying to list some information about generic type parameters now, but String has no generic type parameters.

cc @lrhn

**Comment by jakemac53** [comment]
Note that in general I am not opposed to this message changing, we do have a golden test which will get broken, but I don't consider the exact message to be a part of the API. But I do think the new message is a regression from the old.

**Comment by lrhn** [comment]
This is probably a bug in the removal of `CastError`.
The message ` in a type cast`, leading space and all, seems like it gets put into a place where something else is expected. Maybe the name of a variable being assigned to.
It's badly formatted and reads worse, so it's definitely not what we want to end up with.

Let's see if we can make sure it looks like before.

**Comment by kevmoo** [comment]
```dart
void main() {
  print(null as int);
}
```

Also the grammar is just...off...

```
Unhandled exception:
type 'Null' is not a subtype of type 'int' of ' in type cast'
#0      main (file:///Users/kevmoo/github/json_serializable.dart/checked_yaml/example/boo.dart:2:14)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

the ` of '` bit just seems...like a bad string template being applied!

**Comment by lrhn** [comment]
The call to create this message seems to happen somewhere in VM C++ code, so tagging as area-vm.

**Comment by a-siva** [comment]
https://github.com/dart-lang/sdk/issues/50756 should fix that message. I believe this regressed when `CastError` was deprecated and replaced by 'TypeError'
