### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by jsoref** [dart-lang/sdk#50754]
The [contribution guidelines](https://github.com/dart-lang/sdk/blob/94f20d77314a91489e2c32fd144b81f506822561/CONTRIBUTING.md) suggest using the [Dart Issue Tracker](https://dartbug.com/) which appears to just link to [dart-lang/sdk/issues](https://github.com/dart-lang/sdk/issues), so, I'm opening this ticket...

Here's the rough list of items that I've found:
https://github.com/jsoref/dart-lang-sdk/actions/runs/3711536404

I have a (medium size by my standards) set of changes that I'd like to offer:

Notes:
1. I generally annotate my PRs, but the guidelines suggested I file a ticket before I make a PR, so, I'm not going to do that until later.
2. I generally prefer not to squash my PRs until their content is deemed acceptable because it makes rebasing fairly risky/painful
3. IME, gerrit hates my style of commits.
4. I'm happy to split my PRs by directory or file type.
5. It's generally quite impractical for me to split by change type (comment, api, locals) -- it's quite likely that generally doing this will result in build failures / problematic merge conflicts and incomplete changes
6. I haven't tried to build things, it's quite possible that some of the changes relate to external modules.
7. I do try to identify external files/modules and avoid touching them, but I don't always succeed. There were a couple of files that appeared to be lists of tests that are probably from external modules, I left some of those changes in but, dropping them is trivial (as is dropping changes to any other file/directory).
8. Some projects don't like changing changelogs. I've _tried_ to avoid breaking changelog entries, so if a changelog entry said it was correcting a typo, I tried to leave the type alone, but if a changelog entry included its own errant typo, I tried to correct that
9. A number of names of contributors, authors, and publications had typos.
10. Some items in license blocks have typos, historically lawyers would get antsy about such changes.
11. I do try to correct typos in file names/directories, but it's certainly possible that I haven't done that completely.
12. There are a couple of categories of preference-ish changes, esp. `in to`/`into` or `opt in`/`opt-in`, `work around`/`workaround`, `re-entrant`/`reentrant`. It's trivial for me to drop any individual changeset, I can explain each of my choices (`work around` is a verb-phrase / `workaround` is a noun, `in to` is a preposition and the beginning of a verb, / `into` is a preposition).
13. There are a number of cases where words were doubled, often the correction is dropping the duplicate, but in a number of cases I changed one of the two (this is very manual).

https://github.com/dart-lang/sdk/compare/main...jsoref:spelling?expand=1

I have tried to proof the changes, but I haven't tried to build -- I normally rely on GitHub CI for this, but that doesn't appear to be present.

**Comment by lrhn** [comment]
The fixes seem to be good (at a quick glance), but bountiful. I couldn't sit through reviewing 900+ changes like this, and actually look at every one, and I'd forget where I got to.
I'd personally suggest splitting by directory, so the granularity becomes ~50-100 files per PR, if possible, just to make it easier to get reviewed. 

But I'm just a guy who does reviews of platform libraries. I don't know who'd be best suited to guide a PR with this many files affected. I'd probably ask the infrastructure people. @athomas?

The one thing that made me worry a little is the renaming of a test file. We have metadata about expected test-results that are not in the repo, so changing a file's name will clear our expectations. That's not a big problem, it just need to be reapplied as if it was a new test (and if it succeeds everywhere, it's a non-issue), but I'd consider splitting that out by itself, or into an otherwise smaller CL, just to reduce risk.

Otherwise, sterling job!

**Comment by jsoref** [comment]
I should note that if you want to not lose your place, you can use a PR version, e.g.: https://github.com/check-spelling/dart-lang-sdk/pull/1/files -- it took me a few rounds to get to the end of the file set.

To get my tooling to run reasonably fast, I split the work into 4 chunks:
* ^pkg/front_end/
* ^pkg/(?!front_end/)
* ^tests/
* _everything else_

Trying to envision things on a directory basis,
* sdk is ~56 files, 28 of its 49 commits appear to standalone, so those could be fairly easily offered as a single unit.
* tools is ~30 files, 18 of its 32 commits appear to standalone, so those could be fairly easily offered as a single unit.
* pkg/compiler is ~42 files, 42 of its  69 commits appear to standalone, so those could be fairly easily offered as a single unit.

I'm not sure which other things would be easily teased out... I probably won't have time to do anything the middle of next week.

**Comment by jsoref** [comment]
As of this point, I _believe_ that all of my originally planned items from https://github.com/dart-lang/sdk/issues/50754#issue-1499829058 are now either merged or in open PRs.

Once everything else is merged, I'll do one update of the CI and probably one follow-up pass at which point I'll close this as "completed"

**Comment by jsoref** [comment]
Ok, here's the full catchup:
https://github.com/dart-lang/sdk/compare/main...jsoref:spelling?expand=1 -- It's 102 Commits / 128 Files changed

Alternatively, they can be digested as:

[spelling-pkg](https://github.com/jsoref/dart-lang-sdk/tree/spelling-pkg)
[spelling-pkg-analyzer](https://github.com/jsoref/dart-lang-sdk/tree/spelling-pkg-analyzer)
[spelling-pkg-front_end](https://github.com/jsoref/dart-lang-sdk/tree/spelling-pkg-front_end)
[spelling-build-tools](https://github.com/jsoref/dart-lang-sdk/tree/spelling-build-tools)
[spelling-tests](https://github.com/jsoref/dart-lang-sdk/tree/spelling-tests)
[spelling-runtime](https://github.com/jsoref/dart-lang-sdk/tree/spelling-runtime)
[spelling-sdk](https://github.com/jsoref/dart-lang-sdk/tree/spelling-sdk)

The last one could be split a couple more times, but only if it's worth doing so.

@mit-mit / @lrhn / @eernstg / @athomas -- thoughts?

**Comment by athomas** [comment]
@jsoref Please file a single PR. These are pretty mechanic to review and 1 PR is less work for me than 7.

**Comment by eernstg** [comment]
@athomas, we could take 64 files each? ;-)
(We can do that with a single PR)

**Comment by athomas** [comment]
@eernstg Or you do fancy dart language spec stuff and I take on this chore :)

**Comment by eernstg** [comment]
OK, thanks! Do get back to me if needed! ;-)

**Comment by jsoref** [comment]
This is complete.

If people are interested in preventing typos from creeping in, I'd be happy to talk with them, otherwise, I'll see folks around...
