### ISSUE TITLE
Archived `stagehand` repo causing `gclient sync` failures

### ISSUE THREAD

**Issue by perks** [dart-lang/sdk#50761]
When attempting to build 2.12.2, `gclient sync` fails to fetch the `stagehand` subrepo and thus results in an unbuildable branch.

This is likely due to `https://dart.googlesource.com/stagehand.git` no longer existing

**Comment by sortie** [comment]
Hi, unfortunately it's been difficult to make it possible to check out the source code of older Dart SDK releases in the long term, as some of the technology we depend on (such as DEPS) have changed incompatibly over time. In this case, though, it looks like it's Dart itself that's at fault for removing the stagehand repository.

To unblock you with a workaround: You can find the archived repository at <https://github.com/dart-archive/stagehand>. The DEPS and gclient system is supposed to let you override the repository path using `custom_deps`, but unfortunately I was unable to successfully use this mechanism. Perhaps it's buggy or I used it wrong. You can probably work around it by manually placing the appropriate git repository at the right location, checked out to the right commit per DEPS.

@athomas I'd say we should keep such repositories around on Dart GoB to ensure the longevity of old Dart SDK source codes. Someone must've removed the repository from Dart GoB (could've been me for all I know). I can restore it under the old name and probably freeze the repository. Do you know if there's any good way to hide a repository on GoB or set up a redirect, so I can name it under an archived name?

**Comment by athomas** [comment]
What's the use case here? If you just need a Dart 2.12.2 build we still have those in the archive? We don't have a goal of keeping old checkouts buildable forever.

**Comment by athomas** [comment]
Also, the workaround should work if the DEPS file is modified to fetch from https://github.com/dart-archive/stagehand.git:
```
Var("dart_git") + "stagehand.git"
# ->
https://github.com/dart-archive/stagehand.git
```
