### ISSUE TITLE
Failures on [parser] Breaking change for metadata parsing

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#50769]
There are new test failures on [[parser] Breaking change for metadata parsing](https://dart-review.googlesource.com/c/sdk/+/272600).

The test
```
dart_style/test/formatter_test RuntimeError (expected Pass)
```
is failing.

/cc @munificent

**Comment by jensjoha** [comment]
The same thing - I'm guessing - is also run internally and causes `go/dart-cbuild result: FAILURE (REGRESSIONS DETECTED)`.

**Comment by munificent** [comment]
I'll take a look.

**Comment by munificent** [comment]
Fix out: https://github.com/dart-lang/dart_style/pull/1154

**Comment by munificent** [comment]
...and CL out to roll the fix into the SDK: https://dart-review.googlesource.com/c/sdk/+/276681
