### ISSUE TITLE
Some tests for patterns fail because the 'records' feature isn't enabled in them

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50782]
The issue is discovered in the following tests.

* language/patterns/shared_case_variable_error_test
* language/patterns/shared_case_variable_test
* language/patterns/switch_case_scope_test

The error was encountered during work on https://dart-review.googlesource.com/c/sdk/+/276524.

This issue is assigned label `area-front-end` tentatively, and it needs further investigation, and possibly reassignment of the tags.

**Comment by eernstg** [comment]
Just noticed that there may be a typo: I can't see any declaration of `result` [here](https://github.com/dart-lang/sdk/blob/181c9962b13b888ea8164e470be8dd48845014d1/tests/language/patterns/shared_case_variable_test.dart#L125).

**Comment by johnniwinther** [comment]
Currently block by assertion failure in the flow analysis.

**Comment by chloestefantsova** [comment]
The tests either appear to be fixed by now or fail for a different reason. I'm closing the issue.
