### ISSUE TITLE
Runtime errors potentially due to incomplete pattern desugaring in switch statements

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50783]
The following tests started surfacing runtime errors after the switch-pattern desugaring was partially introduced. It's most likely that the incomplete desugaring is the root of the issue, and it will be resolved eventually as desugaring becomes more complete.

* co19/LanguageFeatures/Patterns/list_A01_t02 (additionally, possibly 'records' not enabled on dart2js tests)
* co19/LanguageFeatures/Patterns/logical_and_A06_t01
* co19/LanguageFeatures/Patterns/logical_or_A02_t02
* co19/LanguageFeatures/Patterns/logical_or_A05_t01
* co19/LanguageFeatures/Patterns/wildcards_A01_t04

The error was encountered during work on https://dart-review.googlesource.com/c/sdk/+/276524.

This issue is assigned label `area-front-end` tentatively, and it needs further investigation, and possibly reassignment of the tags.

**Comment by alexmarkov** [comment]
I can confirm that the following tests fail because _Object pattern_ is not implemented yet:
```
co19/LanguageFeatures/Patterns/list_A01_t02
co19/LanguageFeatures/Patterns/logical_and_A06_t01
co19/LanguageFeatures/Patterns/logical_or_A05_t01
co19/LanguageFeatures/Patterns/wildcards_A01_t04
```

`co19/LanguageFeatures/Patterns/logical_or_A02_t02` fails for another reason: https://github.com/dart-lang/sdk/issues/50797.

**Comment by chloestefantsova** [comment]
More of the failing tests for the same reason.

* tests/co19/src/LanguageFeatures/Patterns/list_A04_t05.dart
* co19/LanguageFeatures/Patterns/record_A01_t01
* co19/LanguageFeatures/Patterns/record_A01_t02
* co19/LanguageFeatures/Patterns/record_A01_t03
* co19/LanguageFeatures/Patterns/record_A01_t04

These are detected by the try bots on the following CL: https://dart-review.googlesource.com/c/sdk/+/276940.

**Comment by chloestefantsova** [comment]
More of the failing tests:

* co19/LanguageFeatures/Patterns/list_A01_t04
* co19/LanguageFeatures/Patterns/record_A02_t02
* co19/LanguageFeatures/Patterns/record_A02_t03
* co19/LanguageFeatures/Patterns/record_A02_t04
* co19/LanguageFeatures/Patterns/record_A03_t01
* co19/LanguageFeatures/Patterns/record_A04_t01
* co19/LanguageFeatures/Patterns/record_A02_t08
* co19/LanguageFeatures/Patterns/map_A05_t01

An example of the stack trace is as follows:

```
Unhandled exception:
  Crash when compiling file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/list_A01_t04.dart at character offset 1070:
UnimplementedError: TODO(paulberry)

#0      SharedTypeAnalyzerErrors.patternTypeMismatchInIrrefutableContext (package:front_end/src/fasta/type_inference/shared_type_analyzer.dart:94:5)
#1      TypeAnalyzer.analyzeDeclaredVariablePattern (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:386:15)
#2      InferenceVisitorImpl.visitVariablePattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:9102:29)
#3      VariablePattern.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:5547:20)
#4      InferenceVisitorImpl.visitListPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:9201:15)
#5      ListPattern.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:4371:20)
#6      InferenceVisitorImpl.dispatchPattern (package:front_end/src/fasta/type_inference/inference_visitor.dart:8873:12)
#7      TypeAnalyzer.analyzePatternVariableDeclarationStatement (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:1042:5)
#8      InferenceVisitorImpl.visitPatternVariableDeclaration (package:front_end/src/fasta/type_inference/inference_visitor.dart:8268:5)
#9      PatternVariableDeclaration.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:5029:20)
#10     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:157:26)
#11     InferenceVisitorImpl._visitStatements (package:front_end/src/fasta/type_inference/inference_visitor.dart:741:50)
#12     InferenceVisitorImpl.visitBlock (package:front_end/src/fasta/type_inference/inference_visitor.dart:762:31)
#13     Block.accept (package:kernel/ast.dart:9694:43)
```

/cc @stereotype441

**Comment by chloestefantsova** [comment]
One more example:

* co19/LanguageFeatures/Patterns/wildcards_A01_t01

**Comment by chloestefantsova** [comment]
More of the test failing due to the pattern desugaring being incomplete:

* co19/LanguageFeatures/Patterns/map_A04_t02
* co19/LanguageFeatures/Patterns/map_A05_t01
* co19/LanguageFeatures/Patterns/object_A01_t01
* co19/LanguageFeatures/Patterns/object_A02_t01
* co19/LanguageFeatures/Patterns/record_A01_t07
* co19/LanguageFeatures/Patterns/record_A01_t08
* co19/LanguageFeatures/Patterns/variable_A02_t01
* co19/LanguageFeatures/Patterns/variable_A02_t03
* co19/LanguageFeatures/Patterns/variable_A02_t04
* co19/LanguageFeatures/Patterns/variable_A02_t06

**Comment by chloestefantsova** [comment]
One of the tests tracked in this issue fails with a missed compile-time error, and all other pass. I'm closing this issue.
