### ISSUE TITLE
[dart2js] Compiling `dart:io` for NodeJS environment 

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#50799]
If a Dart app uses `dart:io` and is compiled to JS via `dart compile js`, any call to `dart:io` will throw an `UnsupportedError`.

But is there an option to map `dart:io` calls to NodeJS [process](https://nodejs.org/api/process.html), [fs](https://nodejs.org/api/fs.html) and others? If no, any chance Dart will support compiling for NodeJS env in the future?

**Comment by sigmundch** [comment]
Thanks for your question.

Unfortunately this is not something the Dart web team currently plans to support, that said, there are packages from the community that do, and that have great support too.

My understanding is that the `sass` compiler is written in Dart (https://github.com/sass/dart-sass/) but also supports running as a nodejs module. I believe they heavily rely on `package:node_interop` to do so. That's one of several packages (see also `package:node_io`) available from https://github.com/pulyaevskiy/node-interop.

Often teams create an extra layer of abstraction on top of `dart:io` to provide an easy transition between the VM and node js environments. I believe you should be able to find examples from sass or other projects.

Hope these pointers help!

**Comment by incendial** [comment]
@sigmundch Thank you!
