### ISSUE TITLE
[analyzer] `CONST_INITIALIZED_WITH_NON_CONSTANT_VALUE` offers wrong fix

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50803]
```dart
class A {}

void f() {
  const x = A();
}
```

is being offered to be:

```dart
  const x = constA(); // 🔥  not even a space.
```

There are two things:

1. If the `InstantCreation` is not a `const`, the fix shouldn't be offered.
2. If the fix is offered, `const` should be followed by a space.

**Comment by bwilkerson** [comment]
> 1. If the `InstantCreation` is not a `const`, the fix shouldn't be offered.

I agree, but note that if the constructor _is_ a `const` constructor, then there won't be a `const_with_non_const` diagnostic because the `const` will be implicit. Are there any circumstances where the fix would be valid?

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/277120

Previously, [const_initialized_with_non_constant_value](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=const_initialized_with_non_constant_value#const_initialized_with_non_constant_value) is associated with `UseConst` which was adding `const` to the node. This is incorrect, because we should use `AddConst` (if it supports the declaring element) or `RemoveConst` from the node.

The proposed CL associates the diagnostic with `RemoveConst` and `RemoveNew`, both are the _second_ possible fix. The added failing test would pass with #49818  

I had a look at the the analyzer test cases for the diagnostic, and I think it is fine to remove the `UseConst`.

**Comment by asashour** [comment]
Could we have a review please? Thanks.
