### ISSUE TITLE
Date format abbreviated month not used in es_US locale

### ISSUE THREAD

**Issue by rodcheater** [dart-lang/sdk#50811]
The abbreviated month is not being used in `es_US` locale when using the skeleton pattern.

Try this code:

```
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';

void main() {
  initializeDateFormatting();
  print(DateFormat('d MMM yyyy', 'es_US').format(DateTime.now()));
  print(DateFormat.yMMMd('es_US').format(DateTime.now()));
}
```

It prints:

```
21 dic. 2022
21 de diciembre de 2022
```

Note that instead using `es_ES` as the locale produces the expected result.

**Comment by asashour** [comment]
Shouldn't this be part of [intl](https://github.com/dart-lang/intl) package?

**Comment by rodcheater** [comment]
Yep.

https://github.com/dart-lang/intl/issues/523
