### ISSUE TITLE
`use_decorated_box` quick-fix

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#50817]
**Describe the quick-fix**
Replace the `Container` with `DecoratedBox`.

**Examples**
OLD:

```dart
Widget buildArea() {
  return Container(
    decoration: const BoxDecoration(
      color: Colors.blue,
      borderRadius: BorderRadius.all(
        Radius.circular(5),
      ),
    ),
    child: const Text('...'),
  );
}
```

FIXED:

```dart
Widget buildArea() {
  return const DecoratedBox(
    decoration: BoxDecoration(
      color: Colors.blue,
      borderRadius: BorderRadius.all(
        Radius.circular(5),
      ),
    ),
    child: Text('...'),
  );
}
```

**Additional context**
Or explain why there won't be any quick-fixes.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/280165

Please note that the proposed CL offers a bulk fix (with the needed complexity). Also, it could be used to offer a fix for `use_colored_box` with minimal changes.
