### ISSUE TITLE
[analyzer] `const_initialized_with_non_constant_value` false positive with `new`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50827]
```dart
class A {
  const A();
}

const a1 = A();
const a2 = new A();
```

`a1` is ok, however `a2` triggers [const_initialized_with_non_constant_value](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=const_initialized_with_non_constant_value#const_initialized_with_non_constant_value), I think both expressions are fine, and the diagnostic should not be triggered.

**Comment by eernstg** [comment]
It is actually OK to flag the declaration of `a2`. The instance creation `A()` in the declaration of `a1` is implicitly `const` because it occurs in a constant context, but `new A()` can not be a constant expression.

**Comment by asashour** [comment]
Thanks for explaining.
