### ISSUE TITLE
[CP] Bugfix for web DateTime, to 2.19

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#50821]
### Commit(s) to merge

8ad766159f21e4e98e91ea02c1940da42005ca1f

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/277002

### Issue Description

A use of a private variable, instead of the public getter exposing it, made the web `DateTime` classes incompatible with custom implementations. Combined with the 2.19 language change of not forwarding implicit implementations of inaccessible members to `noSuchMethod`, means that existing workarounds using `noSuchMethod` also won't work.

See https://github.com/dart-lang/sdk/issues/50750 for an issue where the problem arose.

### What is the fix

Just read the `millisecondsSinceEpoch` using the public getter instead of the private field.

### Why cherry-pick

Existing code is broken with no workaround. They'd like the fix to be available along with the language change that breaks the existing workaround.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/50750

**Comment by mit-mit** [comment]
SGTM
