### ISSUE TITLE
[WARNING] ../../flutter/.pub-cache/hosted/pub.dartlang.org/freezed-2.0.4/lib/src/tools/type.dart:27:16: Error: The getter 'imports' isn't defined for the class 'PrefixElement'.Create an issue

### ISSUE THREAD

**Issue by phongtran2309** [dart-lang/sdk#50825]
- 'PrefixElement' is from 'package:analyzer/dart/element/element.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-3.4.1/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'imports'.
      return e.imports.any((l) {
               ^^^^^^^
[INFO] Precompiling build script... completed, took 692ms

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78

i got an error when i try to run flutter pub run build_runner watch --delete-conflicting-outputs
this flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-arm, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

this my pubsec.yaml
 cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.8
  dotted_line: ^3.1.0
  carousel_slider: ^4.1.1
  flutter_switch: ^0.3.2
  simple_shadow: ^0.3.0
  flutter_slidable: ^2.0.0
  fl_chart: ^0.55.2
  dropdown_button2: ^1.8.8
  sliding_up_panel: ^2.0.0+1
  dotted_border: ^2.0.0+3
  smooth_page_indicator: ^1.0.0+2
  webviewx: ^0.2.1
  webview_flutter: ^2.8.0
  syncfusion_flutter_charts: ^20.3.58
  d_chart: ^0.1.0
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_html: ^3.0.0-alpha.6
  loading_animation_widget: ^1.2.0+3
  k_chart: ^0.6.1
  tiny_charts: ^0.1.0
  audio_wave: ^0.1.4
  flutter_gifimage: ^1.0.1
  analyzer: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  footer: 
  very_good_analysis: ^2.4.0
  dart_code_metrics: ^4.14.0
  very_good_performance: ^0.0.4
  dependency_validator: ^3.2.0
  json_serializable:
  build_runner:
  flutter_gen_runner:
  freezed: ^2.0.1
  auto_route_generator: 3.2.3
  logger:
  import_sorter: ^4.6.0
  provider: ^6.0.3

**Comment by lrhn** [comment]
The `imports` getter was introduced in https://github.com/dart-lang/sdk/commit/664c0213746162645c9f11ced955987b9c3dc33e, which was for analyzer version 5.2.0.
You're using analyzer-3.4.1 according to the pub-cache path and package resolution list. You will need a require a newer version of the analyzer.
