### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by greenviewsoft** [dart-lang/sdk#50845]
## Version information

- `IDEA AI-212.5712.43.2112.8609683`
- `2.17.6`
- `AI-212.5712.43.2112.8609683, JRE 11.0.12+7-b1504.28-7817840x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2400.0x1350.0`

**Comment by gintominto5329** [comment]
Same as, or similar to, #50841

**Comment by asashour** [comment]
An issue without details of what the problem is, or how to reproduce it, is likely to be closed.

**Comment by incendial** [comment]
Haven't seen a valid issue created by this action in a while, maybe it should be removed (or reworked somehow)? [Source code](https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/ide/errorTreeView/AnalysisServerFeedbackAction.java).
