### ISSUE TITLE
web's indexed_db: storing just a single `ByteBuffer` of length 256, takes ~637 bytes

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#50849]
Hello,

I working on a new library for dart, and currently involved, in its local persistence component, which needs indexed_db on web, 

The library writes only the following type of objects, in case of web's indexed_db,

```
Map<String,Object> map = { 'p': "0/1/2", 'd': byteBuffer };
```

After storing a single object of the above type (on a flutter app, built in **release** mode), the chrome storage tab, is reporting the size, for indexed_db, at 2139 bytes, and increases by 637(instead of 256) bytes, for each object added,

I understand that extra metadata needs to be stored, type information, etc, which is pasted at the end of this post,

### Proposed solution
We can be very sure, that `ByteBuffer`s are only used by the performance/efficiency critical programs, 
So, cannot a special exception, be added, for `ByteBuffer` type objects, which packs the data, as compact as possible, and persisting the bare minimum, only the information that's critically required,

### Why `ByteBuffer`
- Web supports its `ArrayBuffer` as equal, to what im proposing here, indicating "the intention of performance criticality"
- `Uin8List`, `Blob`, etc, are not as well supported, as `ByteBuffer`, especially on the web safaris,

Thanking you,

```
{d: ArrayBuffer(256), p: '0/1/2'}
d
: 
ArrayBuffer(256)
byteLength
: 
256
[[Int8Array]]
: 
Int8Array(256)
[0 … 99]
[100 … 199]
[200 … 255]
buffer
: 
ArrayBuffer(256)
byteLength
: 
256
byteOffset
: 
0
length
: 
256
Symbol(Symbol.toStringTag)
: 
"Int8Array"
[[Prototype]]
: 
TypedArray
[[Uint8Array]]
: 
Uint8Array(256)
[0 … 99]
[100 … 199]
[200 … 255]
buffer
: 
ArrayBuffer(256)
byteLength
: 
256
byteOffset
: 
0
length
: 
256
Symbol(Symbol.toStringTag)
: 
"Uint8Array"
[[Prototype]]
: 
TypedArray
[[Int16Array]]
: 
Int16Array(128)
[0 … 99]
[100 … 127]
buffer
: 
ArrayBuffer(256)
byteLength
: 
256
byteOffset
: 
0
length
: 
128
Symbol(Symbol.toStringTag)
: 
"Int16Array"
[[Prototype]]
: 
TypedArray
[[Int32Array]]
: 
Int32Array(64)
[[ArrayBufferByteLength]]
: 
256
[[ArrayBufferData]]
: 
105
p
: 
"0/1/2"
```

**Comment by rakudrama** [comment]
> So, cannot a special exception, be added, for `ByteBuffer` type objects, which packs the data, as compact as possible, and persisting the bare minimum, only the information that's critically required

We have already done what you request.
We have arranged that (1) that a JavaScript `ArrayBuffer` **is** a Dart `ByteBuffer` in Dart program, and (2) creating or accessing a `ByteBuffer` in Dart actually creates or accesses a JavaScript `ArrayBuffer`. I don't think there is anything more we can do.

`ByteBuffer` is [implemented by JavaScript's `ArrayBuffer`](https://github.com/dart-lang/sdk/blob/8e07d492ddbb53f5061e768a7d38f65dd3c5e88d/sdk/lib/_internal/js_runtime/lib/native_typed_data.dart#L28).  I would expect that storing a `ByteBuffer` from Dart to behave the same as storing an `ArrayBuffer` from JavaScript.
