### ISSUE TITLE
[BUG] `RandomAccessFile` only the first, and last bytes, getting written to file, rest all zero

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#50855]
Hello,

The following code, does not write the content to the file, just 2 bytes get written correctly, the first, and the last, rest all are blank,

```import "dart:convert";
import "dart:io";
import "dart:typed_data";

const Utf8Encoder encoder = Utf8Encoder();

void main() {
  final File file = File("/tmp/demo.txt");

  try {
    file.openSync(
      mode: FileMode.writeOnlyAppend,
    )
      ..writeByteSync(0)
      ..closeSync();

    Uint8List bytes;

    int itemCounter = 0;

    while (itemCounter++ < 128) {
      bytes = encoder.convert("text");

      file.openSync(
        mode: FileMode.writeOnly,
      )
        ..setPositionSync((itemCounter += 1))
        ..writeByteSync(bytes.length)
        ..flushSync() /// NO effect, after removing
        ..closeSync();
    }
  } catch (e, s) {
    print("`catch(e,s){`");
    print(e);
    print(s);

    return;
  }

  print("file:${file.readAsBytesSync()}\\0\n");
}
```
### Output
```
file:[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4]\0
```

But this begins to work correctly, when the `file.openSync(` code, is shifted to a variable outside the loop, but this is not good, as the provided code is a simplified version of a function, the code inside the loop is a single function, int the actual code

```
    final RandomAccessFile _file = file.openSync(
      mode: FileMode.writeOnly,
    );

    while (itemCounter++ < 128) {
      bytes = encoder.convert("text");

      _file
        ..setPositionSync((itemCounter += 1))
        ..writeByteSync(bytes.length);
    }

    _file
      ..flushSync()
      ..closeSync();
```

### Output
```
file:[0, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4]\0
```

Thanking you,

**Comment by julemand101** [comment]
If you read the documentation for `File.open` you will find this important section that describes the `mode` parameter:

> Files can be opened in three modes:
>
>    * [FileMode.read](https://api.dart.dev/stable/2.18.6/dart-io/FileMode/read-constant.html): open the file for reading.
>
>    * [FileMode.write](https://api.dart.dev/stable/2.18.6/dart-io/FileMode/write-constant.html): open the file for both reading and writing and truncate the file to length zero. If the file does not exist the file is created.
>
>   *  [FileMode.append](https://api.dart.dev/stable/2.18.6/dart-io/FileMode/append-constant.html): same as [FileMode.write](https://api.dart.dev/stable/2.18.6/dart-io/FileMode/write-constant.html) except that the file is not truncated.

https://api.dart.dev/stable/2.18.6/dart-io/File/open.html

The reason the file gets zeroed in your case is because you are opening the file with `FileMode.writeOnly` which means the same as `FileMode.write` in which the file gets truncated to length zero (basically deletes all the content of the file).

If you instead uses `FileMode.append` you program will work correctly. Tested the following:
```dart
import "dart:convert";
import "dart:io";
import "dart:typed_data";

const Utf8Encoder encoder = Utf8Encoder();

void main() {
  final File file = File("/tmp/demo.txt");

  try {
    file.openSync(
      mode: FileMode.writeOnlyAppend,
    )
      ..writeByteSync(0)
      ..closeSync();

    Uint8List bytes;

    int itemCounter = 0;

    while (itemCounter++ < 128) {
      bytes = encoder.convert("text");

      file.openSync(
        mode: FileMode.append,
      )
        ..setPositionSync((itemCounter += 1))
        ..writeByteSync(bytes.length)
        ..flushSync()

        /// NO effect, after removing
        ..closeSync();
    }
  } catch (e, s) {
    print("`catch(e,s){`");
    print(e);
    print(s);

    return;
  }

  print("file:${file.readAsBytesSync()}\\0\n");
}
```

Returns:
```
file:[0, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 0]\0
```

Do notice the spacing between values. The reason for this is because you are incrementing `itemCounter` twice (both in the white-loop definition and in `..setPositionSync((itemCounter += 1))`).
