### ISSUE TITLE
The "dart:ui" library cannot be used without Flutter.

### ISSUE THREAD

**Issue by HeySreelal** [dart-lang/sdk#50854]
## Issue
I was trying to use "dart:ui" on a pure dart project since I've to make use of canvas and other UI elements. But, when I import "dart:ui" to a pure dart project I keep getting the URI doesn't exist error.

```
Target of URI doesn't exist: 'dart:ui'.

Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist)
```

But, I can see that DartPad is now capable of importing "dart:ui" without Flutter components.  Is this currently not supported in dart on local projects or am I missing something?

## Specs & Details
This tracker is for issues related to:
* Dart core libraries ("dart:async", "dart:io", etc.)

## SDK Version
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_arm64".

## Machine Specs:
OS: Mac OS - Ventura 13.1
Chip: M1, 2020

**Comment by lrhn** [comment]
The `dart:ui` library is provided by Flutter as part of the Flutter SDK, and is not part of the base Dart SDK. The stand-alone `dart` executable does not contain `dart:ui`. The only UI available to the base Dart system is HTML on the web.

The current DartPad is "Based on Flutter 3.3.10 Dart SDK 2.18.6", so it is using the Flutter SDK, which means it has `dart:ui` available.
