### ISSUE TITLE
The CFE is potentially too strict in checking for the 'records' experiment flag

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50870]
In the following test the `records` feature isn't enabled: https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Patterns/object_A01_t09.dart

However, the test imports the library `patterns_lib.dart`. That library uses record literals and has the `records` experimental flag enabled: https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Patterns/patterns_lib.dart

When run on the DDC try bot, the test results in the following error messages.

```
stdout:
org-dartlang-app:/tests/co19/src/LanguageFeatures/Patterns/patterns_lib.dart:117:3: Error: This requires the experimental 'records' language feature to be enabled.
Try passing the '--enable-experiment=records' command line option.
  ({num area}) get areaAsRecord => (area: areaAsDouble);
  ^
org-dartlang-app:/tests/co19/src/LanguageFeatures/Patterns/patterns_lib.dart:117:36: Error: This requires the experimental 'records' language feature to be enabled.
Try passing the '--enable-experiment=records' command line option.
  ({num area}) get areaAsRecord => (area: areaAsDouble);
                                   ^

--- Re-run this test:
python3 tools/test.py -n dartdevk-weak-linux-release-chrome co19/LanguageFeatures/Patterns/object_A01_t09
```

It's possible that the CFE is too restrictive in checking for the flag.

**Comment by chloestefantsova** [comment]
A similar failure is detected on co19/LanguageFeatures/Patterns/object_A04_t01

**Comment by chloestefantsova** [comment]
Another similar case: co19/LanguageFeatures/Patterns/object_A02_t08

**Comment by munificent** [comment]
> This is how the tools behave in a couple of simple experiments I just made. @munificent, do you agree on this description of the test runner's behavior?

That sounds right, though my recollection of the test runner gets dimmer every day. :)

**Comment by chloestefantsova** [comment]
The failures shown in the tests appear to be fixed.
