### ISSUE TITLE
Any plans of replacing `dynamic` with `Object?`, `List<int>` with `Uint8List`

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#50874]
Hello,

Reading `Future func()` seems very bad, compared to `Future<Object> func()`, especially in the code, of a core library (`indexed_db` for example), and may depreciate the intent of code quality, towards the language team, among the readers of the code,

Also the [`RandomAccessFile`](https://api.dart.dev/dev/3.0.0-75.0.dev/dart-io/RandomAccessFile-class.html) class has methods, [`void writeFromSync(List<int> buffer,`](https://api.dart.dev/dev/3.0.0-75.0.dev/dart-io/RandomAccessFile/writeFromSync.html), [`int readIntoSync(List<int> buffer,`](https://api.dart.dev/dev/3.0.0-75.0.dev/dart-io/RandomAccessFile/readIntoSync.html), which operate on `List<int>` instead of `Uint8List`, although the former is converted into the latter, internally, so are there any plans to replace int list parameters, with byte arrays, 
Maybe in dart 3,

If **not**, can there we some member function, like [`Uint8List readSync(int count)`](https://api.dart.dev/dev/3.0.0-75.0.dev/dart-io/RandomAccessFile/readSync.html), which takes a byte array, for writing to a file, maybe like `void writeSync(Uint8List bytes)`,

Thanking you,

**Comment by lrhn** [comment]
Specific changes to individual libraries is always possible. There is no general plan to go over all the libraries and change things.

Changing a `Future` (aka `Future<dynamic>`) to `Future<Object?>` is a breaking change.
I'd be positive to writing `Future<dynamic>` explicitly, instead of just `Future`, but changing the type to not be `dynamic` is non-trivial, since it will break any code currently relying on the type being `dynamic`.

Changing an argument type from `List<int>` to `Uint8List` is also breaking change, so it's unlikely to just happen.

**Comment by mraleph** [comment]
To provide some context: this is related to https://github.com/dart-lang/sdk/issues/36900 - @tvolkert has previously done a pass over various APIs and strengthened their return types from `List<int>` to `Uint8List`. We have not done similar strengthening for parameters.

**Comment by gintominto5329** [comment]
Actually I asked this, because of Dart 3, that its a major version, so the system could be open, for breaking changes

**Comment by lrhn** [comment]
We *can* make breaking changes, but it's always a cost/benefit trade-off. 
These changes are fairly low benefit, so the cost of breaking existing code weighs heavily against it.

If we did the same change as part of a larger "no-implicit-`dynamic`" clean-up, it would be part of a larger benefit, and part of a larger required migration, so it would be a smaller incremental cost.
(I hope we'll get to do such a change at some point. Fixing individual declarations before that is less likely to happen, unless it's a recognized pain point.)

**Comment by gintominto5329** [comment]
Please close this issue, if not needed anymore, no needed from my side,

Thanks

**Comment by aam** [comment]
Closing per @lrhn comment above regarding cost/benefit trade-off.
