### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by benifan** [dart-lang/sdk#50892]
## Version information

- `IDEA AI-211.7628.21.2111.8309675`
- `2.18.6`
- `AI-211.7628.21.2111.8309675, JRE 11.0.11+9-b60-7590822x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366.0x768.0`

**Comment by srawlins** [comment]
Please open an issue with details of your issue if you encounter this again.
