### ISSUE TITLE
No code completion for type names for try/on when there's already at least one "on" clause

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#50893]
When using `try`/`on` there's code completion for type names:

<img width="369" alt="Screenshot 2023-01-04 at 14 37 25" src="https://user-images.githubusercontent.com/1078012/210578806-84bc72c7-5741-4b49-b722-d2e88c9db1d4.png">

However when writing a second `on`, there's no completion:

<img width="422" alt="Screenshot 2023-01-04 at 14 38 10" src="https://user-images.githubusercontent.com/1078012/210578959-74efa481-b6df-4217-af5e-d6ee31838d97.png">

In the bad case, `on` appears to be a `SimpleIdentifier` in the AST, whereas it's not in the good case.

Good:

```
┊   ┊   ┊   ┊   ┊   TryStatementImpl [95..107]
┊   ┊   ┊   ┊   ┊   ┊   BlockImpl [99..102]
┊   ┊   ┊   ┊   ┊   ┊   CatchClauseImpl [104..107]
┊   ┊   ┊   ┊   ┊   ┊   ┊   NamedTypeImpl [108..107] (synthetic)
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name =
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        type = dynamic
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   SimpleIdentifierImpl [108..107] (synthetic)
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name =
┊   ┊   ┊   ┊   ┊   ┊   ┊   BlockImpl [108..107]
```

Base:

```
┊   ┊   ┊   ┊   ┊   TryStatementImpl [95..139]
┊   ┊   ┊   ┊   ┊   ┊   BlockImpl [99..102]
┊   ┊   ┊   ┊   ┊   ┊   CatchClauseImpl [104..139]
┊   ┊   ┊   ┊   ┊   ┊   ┊   NamedTypeImpl [107..119]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name = ArgumentError
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        type = ArgumentError
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   SimpleIdentifierImpl [107..119]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name = ArgumentError
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        static element = class ArgumentError extends Error
┊   ┊   ┊   ┊   ┊   ┊   ┊   CatchClauseParameterImpl [128..132]
┊   ┊   ┊   ┊   ┊   ┊   ┊   BlockImpl [135..139]
┊   ┊   ┊   ┊   ┊   ExpressionStatementImpl [141..144]
┊   ┊   ┊   ┊   ┊   ┊   SimpleIdentifierImpl [141..142]
┊   ┊   ┊   ┊   ┊   ┊   ┊        name = on
┊   ┊   ┊   ┊   ┊   ┊   ┊        static type = dynamic
```

**Comment by srawlins** [comment]
Wow great catch.

**Comment by keertip** [comment]
@DanTup, can you still reproduce this at bleeding edge. I was not able to. See completions on not just the second `on` clause, but on subsequent `on` clauses too.

**Comment by DanTup** [comment]
I can't repro on bleeding edge (or even Dart 3.3.0) today. I'm not sure why, but in my screenshot the word "on" being white also seems odd to me (suggests we didn't get any semantic token for it). Today, I get a dead code warning and not the red error I had in the screenshot above:

![image](https://github.com/dart-lang/sdk/assets/1078012/5694569a-a9b3-4ef9-9927-e8eb3efddeba)

I'm not sure why this is (or what version of the SDK I was using when I took the screenshot above), but I suggest we close this until we see it happen again (at which point I should include a copy/pastable repro and the Dart version!).
