### ISSUE TITLE
[ddc] Cannot staticInterop with subclass of Error

### ISSUE THREAD

**Issue by ditman** [dart-lang/sdk#50899]
Say we have an object that extends JS's `Error`, similar to this one (typescript for brevity, Error is [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)):

```typescript
export interface MyCustomError extends Error {
  customProp: String;
}
```

If I attempt to JS-Interop with code similar to this:

```dart
/// Error object
@JS('Error')
@staticInterop
abstract class DomError {}

/// Methods on the error object
extension DomErrorExtension on DomError {
  /// Error message.
  external String? get message;
  /// Stack trace.
  external String? get stack;
}

/// My custom Error class.
@JS()
@staticInterop
abstract class MyCustomError extends DomError{}

/// Methods of the custom Error object.
extension MyCustomErrorExtension on MyCustomError {
  external String get customProp;
}
```

Whenever objects of that type flow from JS to Dart, like this:

```dart
Future<void> onError(MyCustomError? error) async {
  console.log(error);
}
```

I get an exception similar to the following in DDC:

```
Uncaught Error: Expected a value of type 'MyCustomError?', but got one of type 'NativeError'
    at Object.throw_ [as throw] (errors.dart:288:49)
    at Object.castError (errors.dart:121:3)
    at Object.cast [as as] (operations.dart:529:12)
    at dart.NullableType.new.as (types.dart:411:9)
    at Object._argumentErrors (operations.dart:216:40)
    at Object._checkAndCall (operations.dart:362:22)
    at Object.dcall (operations.dart:372:39)
    at Lp.ret [as i] (js_patch.dart:415:11)
    at Dp.G (client:368:170)
    at ac (client:85:202)
    at _.l.dispatchEvent (client:83:347)
    at _.Ge.B (client:160:179)
```

When compiling with dart2js, the above code works as expected, and the object is logged to the console:
<img width="487" alt="Screenshot 2023-01-04 at 4 49 03 PM" src="https://user-images.githubusercontent.com/1255594/210677096-5f94e398-ae32-4f16-8201-5efc16548f32.png">

_Note: I'm using flutter, so DDC => flutter in debug mode and dart2js => flutter in --profile mode._

### Some info about my environment

```console
$ flutter --version
Flutter 3.7.0-14.0.pre.24 • channel master • git@github.com:ditman/flutter.git
Framework • revision a7942e80d4 (26 hours ago) • 2023-01-03 14:33:55 -0800
Engine • revision c0b3f8fcea
Tools • Dart 3.0.0 (build 3.0.0-77.0.dev) • DevTools 2.20.0

$ which dart
/usr/local/google/home/dit/github/flutter/bin/dart

$ dart --version
Dart SDK version: 3.0.0-77.0.dev (dev) (Mon Jan 2 06:21:11 2023 -0800) on "linux_x64"
```

**Comment by srujzs** [comment]
Note to myself, recapping what we've talked about: This is because `Error` is a special class in DDC, reserved by `@JsPeerInterface`. This class extends `Interceptor` instead of `JavaScriptObject`. When we try to cast the error object to the `@staticInterop` type (which is erased to `JavaScriptObject`), the cast fails. The fix here is likely to change the supertype of this reserved class to `JavaScriptObject`, being careful that DDC doesn't have any dependencies on the direct superclass being `Interceptor`.

**Comment by nshahan** [comment]
Just curious can we reproduce a similar problem with all classes marked with `@JsPeerInterface` or is it something special happening with `Error`?

**Comment by srujzs** [comment]
Nothing special with `Error`, this should be true for all such classes e.g. `Array` (and indeed it is when I try it out).

For now, I don't think we're quite ready for users to be able to interop core types like `Number` or `Boolean`, so I'm inclined to only address `Error` (and implicitly, any of its subtypes like `TypeError`). In the future, we can provide core types when we create a usable JS type hierarchy.

**Comment by ditman** [comment]
YAY!
