### ISSUE TITLE
[CP] Fix compiler crash when returning a value of uninitialized late variable from async function

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#50894]
### Commit(s) to merge

b205ea18cb49fe86af507076bda35c31fa06202d

### Target

beta, stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/278362, https://dart-review.googlesource.com/c/sdk/+/278361

### Issue Description

AOT compiler crashed on the Dart code which was returning a value of uninitialized late local variable from async function.

### What is the fix

Internal classes (such as uninitialized sentinel) are properly handled when checking if return value of async function is a Future.

### Why cherry-pick

Reported by user; this bug prevents building their Flutter app in profile/release modes.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/117892

**Comment by alexmarkov** [comment]
@a-siva @mraleph

**Comment by mit-mit** [comment]
SGTM

**Comment by mraleph** [comment]
SGTM

**Comment by vsmenon** [comment]
lgtm
