### ISSUE TITLE
[CFE] git hooks with dictionary files on Windows

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50891]
On trying to upload a CL touching dictionary-using package e.g. `_fe_analyzer_shared` with `git cl upload -s`, there are many messages that the words are missing, e.g.

```
file:///C:/use/dart-sdk/sdk/pkg/_fe_analyzer_shared/lib/src/flow_analysis/flow_analysis.dart:474:7: The word 'call' is not in our dictionary.

If the word is correctly spelled please add it to one of these files:
- file:///C:/use/dart-sdk/sdk/pkg/front_end/test/spell_checking_list_common.txt
- file:///C:/use/dart-sdk/sdk/pkg/front_end/test/spell_checking_list_code.txt
```

Although `call` is actually there.

The current workaround is to use `--bypass-hooks`, but that is not ideal.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/278345

Apologies for hijacking the assignment (which usually hints that others shouldn't take it).

Please note there is no test case, since `spell_checking_utils_test` doesn't load the dictionaries (which can also be changed if needed).

**Comment by jensjoha** [comment]
Thanks!

**Comment by jensjoha** [comment]
I took the liberty of landing you're change, I hope that's okay.

**Comment by asashour** [comment]
Sure, thanks, I don't have such permission :)
