### ISSUE TITLE
Breaking change: compile-time error for `continue` statement having invalid target

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50902]
# Change

A compile-time error will be triggered for `continue` statement targeting invalid labeled statements (which are not `for`, `do`, `while`, or `switch` case).

Original issue is #49852, see also https://github.com/dart-lang/language/issues/2586

Note: there is already [continue_label_on_switch](https://dart.dev/tools/diagnostic-messages#continue_label_on_switch), which would be part of the new error.

# Rationale 

As per 18.15 of the specs, it is a compile-time error for the `continue` label to target non-loops or switch members.

# Impact

There is a chance that some invalid usage is encountered.

# Mitigation

Users have to change the code and properly target valid labeled statements.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/279343

As the relevant CL has landed, the proposed CL adds `CHANGELOG` and close this issue.

I hope that follows the  [breaking-changes process](https://github.com/dart-lang/sdk/blob/main/docs/process/breaking-changes.md).

**Comment by itsjustkevin** [comment]
@vsmenon @grouma @Hixie @eernstg could you take a look at this?  It has been merged for a month now.

**Comment by eernstg** [comment]
This is a bug fix that eliminates a soundness issue. The update in https://dart-review.googlesource.com/c/sdk/+/279343 was a new entry in CHANGELOG.md, which means that it (presumably) hasn't been implemented, but I doubt that there is any other way ahead than implementing it.

@vsmenon, @grouma, @Hixie, do you see a reason to reject this request?

**Comment by eernstg** [comment]
Enforcement of existing spec.

**Comment by asashour** [comment]
The change has been implemented in https://github.com/dart-lang/sdk/commit/49c7d930425b695d577802121f83a0bc77b39ef3

**Comment by grouma** [comment]
LGTM
