### ISSUE TITLE
[dart2wasm] lib/async/stream_periodic3_test is flaky

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#50901]
The tests
```
lib/async/stream_periodic3_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2wasm-hostasserts-linux-x64-d8
```

The test is flaky but isn't picked up by the flakiness detection system.

**Comment by mkustermann** [comment]
This test doesn't need to be skipped: [cl/368564](https://dart-review.googlesource.com/c/sdk/+/368564)
