### ISSUE TITLE
Error when calling Function.apply with constructor of generic class and named parameter 

### ISSUE THREAD

**Issue by SylphiaWindy** [dart-lang/sdk#50905]
* Dart SDK Version : 2.18.6
* Windows and MacOSX confirmed
* not tested with browsers, guessed it would be the same

Code to reproduce:
```dart
class Cls<T> {
  Cls({required T Function() x});
}

void main() {
  final kwargs = <Symbol, dynamic>{
    #x: () => 0,
  };
  Function.apply(Cls<int>.new, [], kwargs);  // Error
}
```

Runtime error thrown: 

>  type '() => int' is not a subtype of type '() => Y0' of 'x'

No error thrown if Function.apply was called with a normal class method with same named parameter defined.

**Comment by lrhn** [comment]
If run in DartPad, we get another weird error:
```
Uncaught Error: NoSuchMethodError: method not found: 'call'
Receiver: Closure 'Cls___new_tearOff' with <int>
Arguments: [x: Closure 'main_closure']
```
I think something is generally wrong with instantiated tear-offs not having a `call` member, it's not just constructors.

For the VM, the type error is odd. If I print the `.runtimeType` of the tear-off, I get:
```
({required () => Y0 x}) => Cls<int>
```
so it seems the instantiating type parameter is not correctly bound.
