### ISSUE TITLE
Parser allows named parameter with no name in function types.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#50908]
Example:
```dart
  void Function({required int Function()}) f;
  void Function({required int}) g;
```
These declarations are allowed and parsed.

If I check the type, e.g., as:
```dart
  void Function({required int})? f; // Now also valid and initialized
  print([f].runtimeType); // List<(({required int }) => void)?>
```
the parameter still has no name. Or maybe it has an empty name. (I'm surprised more things don't crash!)

If I try to make a conflict:
```dart
  void Function({required int, required int})? f;
```
there is no name conflict, so it's probably no name, not an empty name.

We also allow it in function declarations:
```dart
 void foo({required int Function()}) => null;
```
is also parsed, but impossible to call.

The `required` does not seem to be relevant.

@eernstg Check that the grammar/restrictions on the side doesn't allow this. :)

**Comment by lrhn** [comment]
I had not considered that `({required int Function()?})` would be valid old-style function parameter syntax without the disambiguation rule. I think you are correct that that's how it's parsed in function declarations.

In function *types*, it's not that simple.
```dart
void main() { 
  void Function({required int Function(), required int Function()})? f;
  print([f].runtimeType);
}
```
This code does not cause a name-conflict error (and it does if I add `x` after both types).
DartPad fails an assertion if I try to run it, though.

**Comment by eernstg** [comment]
Function types don't actually admit the old-style `<functionFormalParameter>` syntax, they only admit the syntax `<type> <identifier>` or `<type>` (and for named parameters only the former, plus of course `'required'?`).

The undetected missing names in the function type `void Function({required int Function(), required int Function()})` is a bug.

**Comment by jensjoha** [comment]
> I'll create a fix.

Fix in-flight in https://dart-review.googlesource.com/c/sdk/+/278744.

> We also allow it in function declarations:
> 
> ```dart
>  void foo({required int Function()}) => null;
> ```
> 
> is also parsed, but impossible to call.

It should be possible to call --- it's called `Function`. This seems to work:

```dart
void foo({required int Function()}) => null;
main() {
  foo(Function: () => 42);
}
```

Similarly this code is also allowed, but it's called `otherName` instead:

```dart
void foo({required int otherName()}) => null;
```

And just for completion, having it twice does produce an error about naming conflicts:

```dart
void foo({required int Function(), required int Function()}) => null;
```

When trying to run it tells me this:

```
t.dart:1:49: Error: Duplicated parameter name 'Function'.
void foo({required int Function(), required int Function()}) => null;
                                                ^^^^^^^^
t.dart:1:24: Context: Other parameter named 'Function'.
void foo({required int Function(), required int Function()}) => null;
                       ^^^^^^^^
```

> @stereotype441 and @jensjoha, I guess you would be the best persons to ask: Is it true that the parser of our tools does not implement this disambiguation rule about a `<type>` of the form `<type> 'Function' '('` or `<type> 'Function' '<'`?
> Alternatively, if any such disambiguation rule has actually been implemented, can you explain why `foo` is parsed such that it has a formal parameter named `Function`?

What the parser seems to do is that a type can be required or not.
If the type is required and it sees `<type>` 'Function' '(' [...] `)`` it will be a function type.
If the type is not required it furthermore has to see an identifier (different from `this` and `super`) afterwards.

In the cases seen here:

```dart
  void Function({required int Function()}) f;
  void Function({required int, required int})? f;
```

the type is required, it's parsed as a function type, and the bug fixed in the CL linked above allowed the thing to not have a name.

For

```dart
 void foo({required int Function()}) => null;
```

it's not required, there's no identifier afterwards and it's not parsed as a function type and other stuff kicks in to parse what it calls an "Inline Function Type".

**Comment by eernstg** [comment]
@jensjoha wrote:
> other stuff kicks in to parse what it calls an "Inline Function Type".

```dart
 void foo({required int Function()}) => null;
```

I think this implies that the disambiguation mechanism I mentioned has not been implemented: If it had been implemented then `int Function()` would be parsed as a function type, and it would have been a syntax error that there is no name. And it sounds like you have tested the above declaration with https://dart-review.googlesource.com/c/sdk/+/278744 such that the missing name would be reported.

So the disambiguation mechanism isn't needed, and it isn't there, and that's exactly what we want.

**Comment by jensjoha** [comment]
I think this can be closed.
