### ISSUE TITLE
Create samples for new language features

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#50906]
@mit-mit announced in [the Dart 3 medium article](https://medium.com/dartlang/the-road-to-dart-3-afdd580fbefa) that patterns would be introduced.

We would like to demonstrate new language features to users in a way that they can easily get started using them. 

### Work log

- [ ] Create patterns sample
- [ ] Add samples to Dart pad

**Comment by itsjustkevin** [comment]
@munificent do we already have consumable samples to demonstrate to early adopters?

**Comment by itsjustkevin** [comment]
@atsansone and @MaryaBelanger do we have documentation on utilizing the new features?

**Comment by MaryaBelanger** [comment]
@itsjustkevin Nope not yet. Dart 3 dart.dev updates are planned for the release, nothing earlier than that though.

**Comment by bernaferrari** [comment]
The best possible use case for patterns will be bloc.

**Comment by atsansone** [comment]
@itsjustkevin : We were looking at starting that work post-Forward. I'm out this week, so I'll follow up next week.

**Comment by munificent** [comment]
There are a bunch of samples in [the proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md) that you might be able to harvest from.

**Comment by mit-mit** [comment]
@itsjustkevin will you be handling this one?

**Comment by MaryaBelanger** [comment]
fyi @johnpryan created this repo for testing the new language features too: https://github.com/johnpryan/dart3_samples
Maybe that could be the de facto sample resource?

I've been getting scattered inquiries about Dart 3 samples from across the team and I'm not sure how to address. 

I'm planning to "write" samples inline as I'm writing the docs, not as a separate undertaking. To do so, I'm going to refer to:
- mostly the [specs](https://github.com/dart-lang/language/tree/master/accepted/future-releases), 
- whatever tests/inline comments I can find in the [actual implementation commits](https://github.com/dart-lang/sdk/commits/main) per topic in this repo, 
- the slides from Bob's last presentation, 
- mit's samples repo mentioned above,
- this little [snippet](https://gist.github.com/mit-mit/59a18f3a4610d3934224363f70e4031e#file-dart3pre-dart) from mit's blogpost, 

But again, that's just going to happen as I'm writing, which is going to be happening over the next couple months. I'm going to direct people to this issue (or John's repo once it starts filling out) if they're looking for samples 🤷‍♀️

**Comment by mit-mit** [comment]
@itsjustkevin this doesn't appear to be completed?

**Comment by itsjustkevin** [comment]
@mit-mit wasn't aware that this work was still desired post-release.  Thanks for the catch. Reopening.

**Comment by mit-mit** [comment]
Yeah, still needed. But I think that @RedBrogdon might be working on it?

**Comment by devoncarew** [comment]
Is this issue still relevant?

**Comment by itsjustkevin** [comment]
I think this can be closed, anyone can reopen if needed.

**Comment by Stargator** [comment]
@itsjustkevin, if this is done, where are these samples located?

**Comment by munificent** [comment]
You can find a bunch of samples of the new Dart 3 features in:

* https://dart.dev/language/patterns
* https://dart.dev/language/pattern-types
* https://dart.dev/language/class-modifiers
* https://dart.dev/language/class-modifiers-for-apis
* https://medium.com/dartlang/dart-3-1-a-retrospective-on-functional-style-programming-in-dart-3-a1f4b3a7cdda
