### ISSUE TITLE
Patterns, parse empty record type annotation

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#50912]
See `co19/LanguageFeatures/Patterns/parenthesized_A01_t01`, code like:
```dart
  var (() c) = empty;
```

**Comment by scheglov** [comment]
Also
```dart
String test(Record record) {
  return switch (record) {
    (: final Record case7 as ()) => "case7 = $case7",
    _ => "default"
  };
}
```

**Comment by scheglov** [comment]
and
```
    case (: final () case11?):
      return "case11 = $case11";
```

**Comment by stereotype441** [comment]
I have verified that all the examples in this issue are now correctly parsed.  But there was a gap in testing (we didn't have any parser tests of variable patterns whose type was a record pattern).  I'll follow up with a CL that tests that scenario.
