### ISSUE TITLE
Unit test handle checks consider dangling handles to be valid

### ISSUE THREAD

**Issue by lexprfuncall** [dart-lang/sdk#5092]
Dart API tests currently have an EXPECT_VALID macro that is used to check handles returned by API calls.

Unfortunately, the code beneath this macro does not discriminate between allocated and dangling (freed) handles.  This provides a false sense of security and is probably not what test authors expect.

We should either add a new macro, say EXPECT_SUCCESS, which passes for allocated and non-error handles, or strengthen the checks beneath EXPECT_VALID.

**Comment by zanderso** [comment]
@a-siva Is there something more needed here other than checking the handles for the Zap value in a Debug build? @bkonyi , maybe you could take a look at this one if you're blocked on the memory profiling work for some reason.
