### ISSUE TITLE
Is there any way to read from stdin without Enter or New line?

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#50945]

**Comment by julemand101** [comment]
Look at [`stdin.echoMode`](https://api.dart.dev/stable/2.18.6/dart-io/Stdin/echoMode.html) and [`stdin.lineMode`](https://api.dart.dev/stable/2.18.6/dart-io/Stdin/lineMode.html):

```dart
import 'dart:convert';
import 'dart:io';

void main() async {
  stdin.echoMode = false;
  stdin.lineMode = false;

  await for (final letter in stdin.transform(const Utf8Decoder())) {
    print('GOT: $letter');
  }
}
```
The example above does not work if running inside the console in IntelliJ but does work in a standalone terminal where it will output each character as you type. `stdin.readByteSync()` will also work where it will imminently return as soon a character have been entered.

**Comment by busslina** [comment]
> Look at [`stdin.echoMode`](https://api.dart.dev/stable/2.18.6/dart-io/Stdin/echoMode.html) and [`stdin.lineMode`](https://api.dart.dev/stable/2.18.6/dart-io/Stdin/lineMode.html) (and maybe also [`stdin.echoNewlineMode`](https://api.dart.dev/stable/2.18.6/dart-io/Stdin/echoNewlineMode.html):
> 
> ```dart
> import 'dart:convert';
> import 'dart:io';
> 
> void main() async {
>   stdin.echoMode = false;
>   stdin.lineMode = false;
> 
>   await for (final letter in stdin.transform(const Utf8Decoder())) {
>     print('GOT: $letter');
>   }
> }
> ```
> 
> The example above does not work if running inside the console in IntelliJ but does work in a standalone terminal where it will output each character as you type. `stdin.readByteSync()` will also work with this where it will imminently return as soon a character have been entered.

Thank you, I tested that and seems to work, but after that await for, I tried to restore echo and line mode previous state, and failed. Some OS error with stdin file descriptor. For now my best alternative is using sync method readByteSync. The only bad thing is that I can't receive sigint or any other signal while reading byte sync.

**Comment by a-siva** [comment]
Question has been answered above, closing issue.
