### ISSUE TITLE
[analyzer] introduce `RangeFactory.nodeWithPrecedingComments` extension

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50959]
As hinted in https://dart-review.googlesource.com/c/sdk/+/277100/comment/e2373f61_88a6ed41/

It is better to have a utility method, used by both fixes.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/278741

**Comment by srawlins** [comment]
cc @bwilkerson @keertip I think I really like this idea. What do you think?
