### ISSUE TITLE
Analysis Server becomes out of sync when Format Code happens

### ISSUE THREAD

**Issue by maRci002** [dart-lang/sdk#50968]
## Steps to reproduce

In Android Studio when `File | Settings | Languages & Frameworks | Flutter | Format code on save` or `File | Settings | Tools | Actions on Save | Reformat code` is enabled and Save action is performed the Analyzer Server becomes out of sync.

<details>
  <summary>Example code</summary>
  
  ```dart
  import 'package:flutter/material.dart';
  
  void main() {
    runApp(const MyApp());
  }
  
  class Foo {}
  
  class Bar {}
  
  class MyApp extends StatelessWidget {
    const MyApp({super.key});
  
    @override
    Widget build(BuildContext context) {
      return const MaterialApp(
        home: MyHomePage(),
      );
    }
  }
  
  class MyHomePage extends StatelessWidget {
    const MyHomePage({super.key});
  
    @override
    Widget build(BuildContext context) {
      return const Placeholder();
    }
  }
  ```
</details>

**Rename ( `F2` ):**
1. Make sure your cursor is at the enf of `class Foo {}`
2. Press `Spacebar`
3. Save your file ( `Ctrl + S` )
4. Try to Rename ( `F2` ): `Foo` the Analyzer Server wants ro rename `Bar`

https://user-images.githubusercontent.com/8436039/211584620-f3e1d49f-2d9f-4e86-b00e-7f37649b07ef.mp4

**Context Actions ( `Alt + Enter` ):**
1. remove const from `MaterialApp`
2. Make sure your cursor is at the enf of `return MaterialApp(`
3. Press `Spacebar`
4. Save your file ( `Ctrl + S` )
5. Press Context Actions ( `Alt + Enter` ) and apply: `Add 'const' modifier`

https://user-images.githubusercontent.com/8436039/211586120-9556ee4a-9621-4190-ac6c-bf4dc08565ec.mp4

I can reproduce on both stable and beta channels.

`dart --version`

> Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "windows_x64"

`flutter --version`

> Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 135454af32 (4 weeks ago) • 2022-12-15 07:36:55 -0800
> Engine • revision 3316dd8728
> Tools • Dart 2.18.6 • DevTools 2.15.0

`Android Studio`

```
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    idea.plugin.protoeditor (213.6461.28)
    com.markskelton.one-dark-theme (5.7.2)
    com.bloc.intellij_generator_plugin (3.4.0)
    Dart (213.7433)
    andrasferenczi.dart-data-plugin (0.2.0)
    io.flutter (71.2.3)
```

**Comment by jensjoha** [comment]
This seems to happen even without format on save enabled.

If I'm at the end of `class Foo {}` and ask to rename it wants to rename `Foo`. If I add a space and ask to rename it says unable to, if I save and ask again it wants to rename `Bar'.

I'm still to find out why.

**Comment by maRci002** [comment]
Yes I can reproduce without code Format.

Note: this issue just like #50960 cannot be reproduced via VSCode.

Maybe Flutter / Dart plugin are to blame.

> Non-Bundled Plugins:
>     Dart (213.7433)
>     io.flutter (71.2.3)

**Comment by jensjoha** [comment]
I think this is what happens:
Before updating the IDE works with windows line endings (in my tests asks for offset 101).
When updating (creating an overlay) it uses linux line endings (in my tests asks for offset 95).
When saving the IDE goes back to the windows line endings because that's what the file is like (again asking for offset 101), but because of the 10 second delay we found in https://github.com/dart-lang/sdk/issues/50960 the analysis server isn't up to date and uses the old file (where we should have requested offset 95). Apparently 101 there fits with `Bar`.

(This probably also explains why there was the "no answer" in #50960 --- the file isn't invalidated, it simply and by accident didn't hit anything on the windows/linux line-ending mis-match offset).

**Comment by bwilkerson** [comment]
@jwren

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/278883
