### ISSUE TITLE
Syntax error due to records even when records aren't enabled

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#50975]
Consider this snippet:

```dart
// @dart = 2.12
@MyAnnotation
(

)
void main() {

}
```

This parses correctly with the current stable SDK (for reference, I'm on 2.18.6). Running it with `Dart 3.0.0-89.0.dev` prints this error, however:

```
test.dart:4:1: Error: Expected a declaration, but got '('.
(
^
test.dart:6:1: Error: Expected a declaration, but got ')'.
)
```

I assume this is due to the [ambiguity records have around annotations](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#ambiguity-with-metadata-annotations), so this is rightly a syntax error _if records were enabled_. They aren't though, and so I'd still expect newer Dart versions to be able to parse that snippet.

This affects not only the CFE but also the analyzer, which means that `analyzer` versions using `_fe_analyzer_shared` version `0.52.0` are unable to parse what's currently valid Dart.

**Comment by bwilkerson** [comment]
@jensjoha

**Comment by jensjoha** [comment]
This is expected as it's a breaking change. From the specification that was also linked above:

> Breaking change: Existing metadata annotations with whitespace before their argument lists will no longer parse correctly. In a corpus of 18,672,247 lines of code containing 409,825 metadata annotations, 46,245 had argument lists and none of those had whitespace before the argument list. Note that this analysis only captures code that has been committed. Code being written may be less well formatted, but we expect problems from this to be rare.
>
>Because this change does not seem to break a significant fraction of code in the wild and our parser is currently not aware of language versioning, we make this grammar change unconditionally when parsing a Dart library targeting any language version.
