### ISSUE TITLE
Consider adding synonyms for `dart pub`

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#50971]
Some options for synonyms:

- [ ] `dart packages`
- [ ] `dart pkg`

**Comment by jonasfj** [comment]
@bkonyi is there a good reason for adding these synonyms?

I agree, that it would be nice if the CLI interface was better.
Is that what this aims at, or is it more like consistency with `flutter packages`?

**Comment by parlough** [comment]
I also think there is consistency and value in having one specific command. With synonyms, developers may get comfortable and use them in tutorials, videos, demonstrations, etc creating an inconsistent experience or unfamiliarity for those reading/watching but are used to a different flavor of the command. Most documentation will refer to the primary alias as well, making the others challenging to search for.

Perhaps the user experience could still be improved here without adding this potential source of inconsistency by making sure "pub" shows up in the "Did you mean one of these?" text for these aliases.

```terminal
$ dart packages get

Could not find a command named "packages".

Did you mean one of these?
  pub
```
