### ISSUE TITLE
[ANTLR grammar] Minor observations.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#50982]
This issue points out some parts of the ANTLR-based Dart grammar that don't seem to be intended to be that way or can perhaps be made a little stricter.

---

A) Consider localVariableDeclaration -> initializedVariableDeclaration -> declaredIdentifier:

<img width="1343" alt="Bildschirmfoto 2023-01-11 um 00 33 04" src="https://user-images.githubusercontent.com/24444584/211686328-b3d02631-0be0-4eee-a2dc-7737ff32c2cf.png">

I think a local variable should not be allowed to be annotated as being covariant?

i.e. I think the following is not valid Dart code:
```dart
void foo() {
  covariant final i = 0;
}
```

the same for forLoopParts via its first production again via declaredIdentifier:

<img width="937" alt="Bildschirmfoto 2023-01-11 um 00 33 37" src="https://user-images.githubusercontent.com/24444584/211686823-beb072d5-53b1-4541-95ff-035c085eb5fe.png">

---

B) There are three rules that seem to not be related to the lexical grammar, that are not meant to be start symbols and do not appear on the rhs of any production and are therefore unused. They are:

- functionPrimaryBodyPrefix
- functionExpressionBodyPrefix
- functionBodyPrefix

I think they can either be removed or should not be unused?

<img width="1055" alt="Bildschirmfoto 2023-01-10 um 15 46 37" src="https://user-images.githubusercontent.com/24444584/211686958-9a552cd4-c000-4c68-a60b-edeae3590619.png">

---

C) finalConstVarOrType allows fieldFormalParameters to be const and late, which doesn't look right. Same for simpleFormalParameter via declaredIdentifier.

<img width="850" alt="Bildschirmfoto 2023-01-11 um 00 42 18" src="https://user-images.githubusercontent.com/24444584/211687071-4df46c94-9ef1-4933-aef7-14c140f58c6b.png">

and same for the first production of forLoopParts via declaredIdentifier.

<img width="1215" alt="Bildschirmfoto 2023-01-11 um 01 42 48" src="https://user-images.githubusercontent.com/24444584/211691790-e741f21c-84e1-4519-b547-c185484bbccb.png">

---

D) I think the rhs of the comparison in uriTest can be restricted to be a stringLiteralWithoutInterpolation to capture the fact that interpolated strings are not allowed there (as is already being done with uris) 

<img width="1292" alt="Bildschirmfoto 2023-01-10 um 15 40 10" src="https://user-images.githubusercontent.com/24444584/211687433-136cb64a-fa00-4050-a1ac-20fa8d5190fd.png">

---

E) The single/double line single/double quote string literals in a singleStringWithoutInterpolation allow for simple interpolations to occur in it:

<img width="615" alt="Bildschirmfoto 2023-01-10 um 15 36 54" src="https://user-images.githubusercontent.com/24444584/211687949-6bd53ba3-e27a-4529-9e15-c3041dcf0cba.png">

Fixing this (by having explicit string literals for each one with and without simple interpolations) will introduce an ambiguity in the regular part of the lexical grammar. I'm not sure what the best way would be to express and resolve that ambiguity in ANTLR, but I think, conceptually, we should disambiguate in favor of the non interpolated version of these strings and use both versions in the syntactical grammar as a replacement for the single interpolated version that is being used today?

---

F) I think onParts would be better expressed as `onPart+`. This seems to be a valid substitution to me, and would make this part of the grammar easier to understand and visualize.

<img width="461" alt="Bildschirmfoto 2023-01-11 um 01 13 49" src="https://user-images.githubusercontent.com/24444584/211688901-9d901c2c-211f-4067-a0b4-547b25d0d5a2.png">

---

G) The firstset of libraryDefinition contains `FEFF`. libraryDefinition is a start symbol. partDeclaration is also a start symbol, but the firstset of partDeclaration does not contain `FEFF`. Is that intentional? The descriptions of FEFF that I could find online make me think that partDeclaration should also start with an optional FEFF (to match libraryDefinition)?

---

H) There's a small typo here:

funciton -> function
https://github.com/dart-lang/sdk/blob/78ac63303b57a9804f3e0958c7f9afafb05f484d/tools/spec_parser/Dart.g#L132

And the convention of 4 spaces after the colon and pipe is being violated here:

https://github.com/dart-lang/sdk/blob/78ac63303b57a9804f3e0958c7f9afafb05f484d/tools/spec_parser/Dart.g#L640-L668

---

(I hope the images are helpful!)

**Comment by modulovalue** [comment]
> [...] but this approach is easier to specify and has better error recovery.

That makes sense to me, thank you for the explanation.

Some context: I hope to be able to assume that the ANTLR-based grammar specification is sound (parses only syntactically valid Dart programs) and complete (parses all syntactically valid Dart programs) so that I can more easily verify that the grammar that I end up using remains correct as Dart continues to evolve.

Are soundness and completeness (as described above) goals of the ANTLR-based grammar specification?

**Comment by eernstg** [comment]
@lrhn already described the situation very precisely: In some cases, including the modifier `covariant`, we could choose to make certain situations like covariant top-level variables a syntax error (in which case the grammar would be larger and have more near-duplicated elements) or we could make it a compile-time error which is not a syntax error (which is what we actually do). The main reason for doing this is that the grammar ruleset explodes if we encode too many restrictions into the grammar, compared to the situation where we make it a "normal" compile-time error.

However, there is one more aspect of this: We do not specify which compile-time errors are syntax errors, and which ones are not. The point is that it is up to each Dart parser to make that decision based on its purpose and usage.

If we use a grammar that derives a larger language than the one in the language specification, and then reject the programs that are outside the language using non-syntax compile-time errors, the parser may well have a more helpful behavior during error recovery, and it may be able to give more informative error messages. This means that it's perfectly meaningful for a tool to use a more permissive grammar than the one in the specification.

The only requirement is that if _P_ is a program which is derivable by the specified grammar, and _P_ doesn't have any compile-time errors, then Dart tools should accept _P_, and if it is executed then it should have the run-time behavior which is specified.

[Dart.g](https://github.com/dart-lang/sdk/blob/main/tools/spec_parser/Dart.g) is intended to serve as a mechanized checking device on the specification grammar. That is, Dart.g should be equivalent to the sum of the grammar snippets in the language specification. We may then use it to detect parsing success/failure discrepancies with actual Dart code, which will help us to detect elements of the specification grammar that aren't consistent with the behavior of the language tools. We may then correct the behavior of the tools, or change the specification such that they are consistent, whichever is more appropriate.

In that sense, Dart.g as executed via the ANTLR v4 parser generator is intended to be equivalent to the language specification. In particular, both the language specification and the ANTLR parser rely on the ordering of alternatives in each grammar rule to disambiguate, in the case where multiple choices will produce a successful parse.

(It should be noted that the language specification is at Dart 2.10 at this point, and updates to include null safety (in particular, Dart 2.13), are under review. In contrast, Dart.g is much further ahead, e.g., it includes patterns and records. But when the language specification catches up with newer language versions, the two grammars should be equivalent. Issues reporting discrepancies are very welcome. ;-)

With all these things in mind, the soundness and completeness goals are as follows: Dart.g for language version x.y should be consistent with the language specification for language version x.y. Tools may choose to use a more permissive grammar, as long as they filter out the additional programs (the ones that "should have had a syntax error") by means of non-syntax compile-time errors.

**Comment by modulovalue** [comment]
Thank you @eernstg for your help. I will now consider the ANTLR-based grammar specification  as a part of the LaTeX-based specification and not as a single independent unit. I made some assumptions that were not true, thank you for correcting them.
