### ISSUE TITLE
[Patterns] Value returned by object pattern getter in switch is not cached

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#50987]
`co19/LanguageFeatures/Patterns/logical_or_A05_t0*` tests fail on `dartk`, `dartdevk` and `dart2js`
The code, demonstrating the problem looks like:
```dart
  const zero = Unit(0, logger);
  const one = Unit(1, logger);
  const two = Unit(2, logger);
  const three = Unit(3, logger);
  const pi = Unit(3.14, logger);

  Shape shape1 = Square(1, logger);
  String s1 = switch (shape1) {
    Square(area: two) || Square(area: one) => log,
    _ => "Other"
  };
  Expect.equals("Square.area=2;=1;", s1);
```
Here 'logger' logs 'Square.area' on each call of `Square.area` getter, and overloaded operator `==` of the constants `const one = Unit(1, logger);` adds `=1`.
Error is
```
Expect.equals(expected: <Square.area=1;=2;>, actual: <Square.area=1;Square.area=2;>) fails.
```
This mean that value, returned by `Square.area` getter, is not cached but getter is called on each comparison.  Is this correct? The tests were written in suggestion that getter value should be cached. Who is right here? The current implementation or the tests?

cc @eernstg

**Comment by eernstg** [comment]
I would expect the caching to occur, cf. https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=Whenever%20the%20same%20member%20is%20invoked%20by%20a%20later%20pattern%20(either%20a%20subsequent%20subpattern%2C%20or%20a%20pattern%20in%20a%20later%20case)%2C%20we%20don%27t%20invoke%20the%20member%20again%20and%20instead%20use%20the%20previously%20returned%20value.

**Comment by alexmarkov** [comment]
Kernel AST has a repeated call to a getter:

```
          final pat::Unit<pat::MetricUnits> #t15 = #t14{pat::Square<pat::MetricUnits>}.{pat::Square::area}{pat::Unit<pat::MetricUnits>};
          if(#t15 =={pat::Unit::==}{(core::Object) → core::bool} #C6) {
            final pat::Shape<pat::MetricUnits> #t16 = #t13;
            if(#t16 is pat::Square<pat::MetricUnits>) {
              final pat::Unit<pat::MetricUnits> #t17 = #t16{pat::Square<pat::MetricUnits>}.{pat::Square::area}{pat::Unit<pat::MetricUnits>};
              if(#t17 =={pat::Unit::==}{(core::Object) → core::bool} #C5) {
```

/cc @chloestefantsova @johnniwinther

**Comment by alexmarkov** [comment]
The following tests fail with RuntimeError due to repeated calls to the same getters:

```
co19/LanguageFeatures/Patterns/logical_and_A06_t01
co19/LanguageFeatures/Patterns/logical_or_A05_t01
co19/LanguageFeatures/Patterns/logical_or_A05_t02
co19/LanguageFeatures/Patterns/logical_or_A05_t03
co19/LanguageFeatures/Patterns/logical_or_A05_t04
co19/LanguageFeatures/Patterns/logical_or_A05_t05
co19/LanguageFeatures/Patterns/logical_or_A05_t06
```
