### ISSUE TITLE
double.toStringAsFixed() rounding is not accurate

### ISSUE THREAD

**Issue by Ro6Fish** [dart-lang/sdk#50984]
When more than or equal to four decimal places, the number 1.99995 is not rounded using this method, the expected result should be 2.0000, when I use 1.99996 the result is correct

![image](https://user-images.githubusercontent.com/20988424/211798864-8cad03dc-a4f8-415e-928d-a6f541efc0f5.png)

**Comment by lrhn** [comment]
This is working as expected.

There is no double with the precise value 1.99995. The actual double value closest to that real value is
1.9999499999999998944844037396251223981380462646484375
which, as you can see, is smaller than 1.99995, so when rounding to four decimal places, it's closer to 1.9999 than 2.0000.

The same thing applies to the other supposed error, which has value
1.9999949999999999672439798814593814313411712646484375

(There is also no double with value 1.9995, but the closest double to that happens to be the larger 1.9995000000000000550670620214077644050121307373046875).

**Comment by Ro6Fish** [comment]
Thanks！
