### ISSUE TITLE
Records: Single-positional-field record types should not need trailing comma.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#51006]
The [grammar for record types](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#record-type-annotations) allow a single-positional-field record (1-tuple) type without a trailing comma. Only the record value expression needs the trailing comma for a 1-tuple record.

Example:
```dart
void main() {
 (int) x = (1,);
}

void foo<T extends (int)>(){}

typedef P<T> = (T);
```
These should all be valid. Today they give the following errors (from `dart analyze`, but `dart run` gives similar errors):
```
  error - singlerec.dart:2:6 - Record type with
          one entry requires a trailing comma.
          Try adding a trailing comma. -
          record_type_one_positional_no_trailing_comma
  error - singlerec.dart:5:24 - Record type
          with one entry requires a trailing
          comma. Try adding a trailing comma. -
          record_type_one_positional_no_trailing_comma
  error - singlerec.dart:7:18 - Record type
          with one entry requires a trailing
          comma. Try adding a trailing comma. -
          record_type_one_positional_no_trailing_comma
```

**Comment by jensjoha** [comment]
From the link I read this:

> It is a compile-time error if a record type has any of:
> 
> [...]
> 
> Only one positional field and no trailing comma. _This isn't ambiguous, since there are no parenthesized type expressions in Dart. But prohibiting this is symmetric with record expressions and leaves the potential for later support for parentheses for grouping in type expressions._

**Comment by lrhn** [comment]
Ack, my bad. The grammar allows not having a comma, but the extra prose makes it a compile-time error.
That's OK since there are no ambiguities, so in a type position, `(T)` is always invalid.
