### ISSUE TITLE
Expose Dart VM API to request multiple instances of a class, identical to what observatory is doing. 

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#51003]
<img width="266" alt="Screenshot 2023-01-12 at 11 53 50 AM" src="https://user-images.githubusercontent.com/12115586/212167738-9e1e2d72-d85b-4003-949b-22af4e67ea7d.png">

**Comment by polina-c** [comment]
https://dart-review.googlesource.com/c/sdk/+/279201

**Comment by derekxu16** [comment]
FYI, the current status is that I can't land that CL yet, because it will break DWDS internally. I have a fix ready (https://github.com/dart-lang/webdev/pull/1905), but the DWDS GitHub checks are currently broken.

**Comment by derekxu16** [comment]
What needs to be changed in `_getInstancesAsArray`? The intent of the CL was to make `getInstances` have the same functionality as `_getInstancesAsArray`. Nothing should've been added to `getInstances` that wasn't already available in `_getInstancesAsArray`.

**Comment by derekxu16** [comment]
I see that the issue is explained in https://github.com/dart-lang/sdk/issues/51393.
