### ISSUE TITLE
`switch` Quick Fix fails on lack of curly braces

### ISSUE THREAD

**Issue by satvikpendem** [dart-lang/sdk#51004]
`Dart SDK version: 2.19.0-444.4.beta (beta) (Tue Jan 10 10:24:44 2023 +0000) on "windows_x64"`

When creating a `switch` statement and using the Quick Fix helper in VSCode, if curly braces are not included, the helper produces syntactically invalid code. Consider the following code:

```dart
enum ExampleEnum { one, two }

void example() {
  final ExampleEnum exampleEnum;

  switch (exampleEnum)
}
```
![image](https://user-images.githubusercontent.com/42670561/212185700-a9c75a5f-325e-489d-80d2-e5136befc64a.png)
 
 After running the Quick Fix, the code becomes:
 
```dart
enum ExampleEnum { one, two }

void example() {
  final ExampleEnum exampleEnum;

  switch (exampleEnum)

    case ExampleEnum.one:
      // TODO: Handle this case.
      break;
    case ExampleEnum.two:
      // TODO: Handle this case.
      break;
  }
```
![image](https://user-images.githubusercontent.com/42670561/212185853-18d130ff-8895-4da2-90cd-762ea681985b.png)

It works fine with `switch (exampleEnum) {}`:

```dart
enum ExampleEnum { one, two }

void example() {
  final ExampleEnum exampleEnum;

  switch (exampleEnum) {
    case ExampleEnum.one:
      // TODO: Handle this case.
      break;
    case ExampleEnum.two:
      // TODO: Handle this case.
      break;
  }
}
```

Expected behavior is that either the Quick Fix adds the curly braces (preferred), or it doesn't show the suggestion until curly braces have been added manually by the programmer.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/278913
