### ISSUE TITLE
`unnecessary_type_check` Quick Fix should have an option to remove the type check

### ISSUE THREAD

**Issue by satvikpendem** [dart-lang/sdk#51013]
`Dart SDK version: 2.19.0-444.4.beta (beta) (Tue Jan 10 10:24:44 2023 +0000) on "windows_x64"`

Sample:

```dart
class Example {
  final String name;

  Example({required this.name});

  @override
  bool operator ==(covariant Example other) {
    if (identical(this, other)) return true;

    return other is Example && other.name == name;
  }
}
```

The lint on `other is Example` is `Unnecessary type check; the result is always 'true'. Try correcting the type check, or removing the type check.` but the Quick Fix does not have an option to remove the unnecessary type check.

**Comment by asashour** [comment]
Duplicate of #47793, a proposed fix to be submitted there.
