### ISSUE TITLE
[CP] Remove delay in removing file overlays.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51015]
### Commit(s) to merge

97f5626a6fb18c35b9e5581158e309efb6470517

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/278993

### Issue Description

On IDEs like IntelliJ and Android Studio, static analysis is not available for 10 seconds after a file save. This CL fixes this bug.

### What is the fix

The fix is to remove the 10 second delay.

### Why cherry-pick

This is a severe issue representing a severe regression starting in Dart 2.17 releases.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/50960 and https://github.com/dart-lang/sdk/issues/49107

**Comment by srawlins** [comment]
CC @a-siva @scheglov @jacob314

**Comment by a-siva** [comment]
lgtm

**Comment by mraleph** [comment]
lgtm

**Comment by srawlins** [comment]
I believe this landed?
