### ISSUE TITLE
Change `HttpProfileRequestRef.id` type from `String` to `int`

### ISSUE THREAD

**Issue by CoderDake** [dart-lang/sdk#51035]
# Intent
- Change `HttpProfileRequestRef` to use `String` for it's `id` type.
- Change  `ext.dart.io.getHttpProfileRequest` to use `String` for the passed `id` (instead of `int`).

# Justification
flutter/DevTools runs on web, so it only has access to 52 bit `int`.
Using `String` to pass the `id` will avoid overflowing the `id`.

# Impact
These RPC calls were originally created for use with Devtools. I haven't been able to find any other internal uses of the RPC. 

I'm unsure of how to check if any external customers depend on these.

# Mitigation
- Anyone uses of the `ext.dart.io.getHttpProfile` or `ext.dart.io.getHttpProfileRequest` VmService calls 
  - may need to change the types of ids that they pass or receive. 
- Uses of `HttpProfileRequestRef` or `HttpProfileRequest` 
  - may need to change type of ids being passed or reveived
  
# Changes
To see the specific proposed changes see: https://dart-review.googlesource.com/c/sdk/+/279122

# ⚠️ Update ⚠️ (Below was added Jan 19, 2023 @ 2:13PM ET)
While testing these changes I found that the [`SocketStatics.id`](https://github.com/dart-lang/sdk/blob/9bea89246aadcdd7442498228219e786bf18eb25/pkg/vm_service/lib/src/dart_io_extensions.dart#L203) type should be changed from `int` to `String` as well. 
I am going to include that change in this breaking change as well.

**Comment by bkonyi** [comment]
This change SGTM.

**Comment by bkonyi** [comment]
@itsjustkevin can you sign off on this please? :)

**Comment by itsjustkevin** [comment]
@grouma @Hixie @vsmenon could you take a look at this breaking change request?

**Comment by vsmenon** [comment]
lgtm

**Comment by grouma** [comment]
LGTM. This may have an impact on devtools, cc @kenzieschmoll

**Comment by CoderDake** [comment]
The change has now been landed from https://dart-review.googlesource.com/c/sdk/+/280020
