### ISSUE TITLE
[dart2wasm] Incorrect function equality of instantiations

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51030]
Generic instantiation part of this documentation is currently not implemented: https://github.com/dart-lang/sdk/blob/5a5a83031bdc9a0855c6584ea9033acbd295726e/pkg/dart2wasm/lib/intrinsics.dart#L1499-L1502

Example:

```dart
void main() {
  X foo<X>(X x) => x;
  int Function(int) x1 = foo<int>;
  int Function(int) x2 = foo<int>;
  print(x1 == x2);
}
```

AOT output: true
dart2wasm output: false

**Comment by osa1** [comment]
The problem should be how we compare closure contexts for equality: https://github.com/dart-lang/sdk/blob/2cfc0146e16703c05d5c48c3c4d6ba2fc99f3ddc/pkg/dart2wasm/lib/intrinsics.dart#L1565-L1581

For instantiation closures, what we need to do is:

1. Check if both closures are instantiations (Do instantiation contexts have a common supertype that is not a supertype of any other struct?)
2. If they are, check if they are instantiations of the same closure. This can be done by comparing vtable references.
3. Compare instantiation closure struct fields (`_Type` objects) structurally.

Currently we can't do (3) because we don't have the struct type in runtime. Some options:

- We could store the `_Type`s in Wasm arrays
- We could generate per-instantiation-closure type comparison functions that take two instantiation context structs as arguments and compare the types. These functions will need a known index in instantiation clsoure vtables so that they can be called in `_Closure._equals`.

Any thoughts @askeksa-google?

**Comment by askeksa-google** [comment]
1. They don't have a common supertype currently, but we can easily add one. It would make sense to create one supertype for all of them (for checking whether the context is an instantiation context) plus one for each type count, which would be the supertype of all instantiation contexts with that type count (and a direct subtype of the common one). The one specific to the type count can then be set as the `null` fallback case here: https://github.com/dart-lang/sdk/blob/15c1801eb2d3e619e6f32f9ea6e3e20f42a93d1a/pkg/dart2wasm/lib/closures.dart#L325
2. At this point, we have already checked that the vtables references are the same.
3. Yes, this would just be a dispatch table call of `==`.

It should not be a problem to add the type comparison functions to the generic closure vtables. With the suggested type hierarchy, it's just one function per type count.

**Comment by osa1** [comment]
This is being implemented in https://dart-review.googlesource.com/c/sdk/+/285902.
