### ISSUE TITLE
Flutter customer tests override operator == with a dynamic parameter.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51038]
See failures here: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8791703831221213185/+/u/Customer_testing/customer_testing/test_stdout

We have to fix all of these before issuing a warning about it.

* [x] flutter_portal - https://github.com/fzyzcjy/flutter_portal/pull/98
  * [ ] bump flutter/tests - https://github.com/flutter/tests/pull/211
* [x] flutter/cocoon - https://github.com/flutter/cocoon/pull/2400
  * [ ] bump flutter/tests - https://github.com/flutter/tests/pull/210
* [ ] flutter_reactive_ble - https://github.com/PhilipsHue/flutter_reactive_ble/pull/677
  * [ ] bump flutter/tests - https://github.com/flutter/tests/pull/219

**Comment by navaronbracke** [comment]
@srawlins If I'm not mistaken you should be using `other is SomeType && <other checks here>` instead of `as`?

Yes, you will get a warning from the `unrelated_type_equality_checks` lint but it fails at runtime with a type cast error.

**Comment by srawlins** [comment]
I'm not sure what you're referring to. One of the PRs? Could you comment on the PR?

**Comment by navaronbracke** [comment]
@srawlins I commented on https://github.com/PhilipsHue/flutter_reactive_ble/pull/677 to clarify.

Not sure about the cast in the `flutter_cocoon` PR, but per https://github.com/flutter/cocoon/pull/2400#discussion_r1072962994 I think its fine?

**Comment by srawlins** [comment]
Customer tests are fixed.
