### ISSUE TITLE
[cfe] Implement primitive equality

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51047]
This is the CFE specific issue for #51045, which has the details.

**Comment by johnniwinther** [comment]
@eernstg Is this part of the patterns feature?

**Comment by eernstg** [comment]
Yes.

**Comment by eernstg** [comment]
About being part of the patterns feature: cf. https://github.com/dart-lang/language/issues/2108#issuecomment-1308021567.

**Comment by eernstg** [comment]
Closed because of https://github.com/dart-lang/sdk/commit/94c165d18910ba1db4636e2b4987e73227ac902d.
