### ISSUE TITLE
[analyzer] Implement primitive equality

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51046]
This is the analyzer specific issue for #51045, which has the details.

**Comment by bwilkerson** [comment]
Do we have a timeframe for when this work needs to be done?

**Comment by eernstg** [comment]
It's bundled with patterns, cf. https://github.com/dart-lang/language/issues/2108#issuecomment-1308021567.

**Comment by scheglov** [comment]
What does it mean - "bundled with patterns"? Do we implement this functionality while implementing patterns and report everywhere, or do we report errors for overridden `hashCode` only when `patterns` feature is enabled?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/283440, but it has some failures, including google3, if enabled unconditionally.

**Comment by eernstg** [comment]
Could you enable it when and only when patterns are enabled? This would imply that the breakage caused by primitive equality would be encountered as part of the migration where patterns are enabled, which is probably a reasonable timing.

**Comment by scheglov** [comment]
Done, we check presence of `get hashCode` only if the `patterns` feature is enabled inside the library where we validate a constant value (where `switch` is).
