### ISSUE TITLE
Failures on [cfe] Report error when mixin classes have a non-Object superclass....[_fe_analyzer_shared] Refactor NullValue and ValueKind

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51051]
There are new test failures on [[cfe] Report error when mixin classes have a non-Object superclass....[_fe_analyzer_shared] Refactor NullValue and ValueKind](https://github.com/dart-lang/sdk/compare/4ffe1b27688ddbe67cb2a2a835bdc867e5966de5~...ef147e4c6854ffd35424a8c8e6543c3f2ebf7c35).

The tests
```
vm/dart_2/use_resolve_dwarf_paths_flag_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-asan-linux-release-x64
```

**Comment by alexmarkov** [comment]
Most probably started with https://github.com/dart-lang/sdk/commit/8bcc8491388dfc3a5f842c7c183dd8acff02c93d.
@sstrickl Could you please take a look?

**Comment by sstrickl** [comment]
Am looking now, thanks!
