### ISSUE TITLE
Missing noSuchMethod-induced `hashCode` stub?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51050]
Consider the following program:

```dart
abstract class WeirdHashCode {
  Never get hashCode;
}

class SecretNonPrimitiveHashCode implements WeirdHashCode {
  noSuchMethod(Invocation invocation) => 0;
}

void main() {
  Object o = SecretNonPrimitiveHashCode();
  print(o.hashCode);
}
```

This program gives rise to a compile-time error from the analyzer:

```
Analyzing n013.dart...                 0.6s

  error • n013.dart:16:7 • 'Object.hashCode' ('int Function()') isn't a
          valid concrete implementation of 'WeirdHashCode.hashCode' ('Never
          Function()'). • invalid_implementation_override

1 issue found.
```

The CFE reports an error, too:

```
n013.dart:16:7: Error: The implementation of 'hashCode' in the non-abstract class 'SecretNonPrimitiveHashCode' does not conform to its interface.
class SecretNonPrimitiveHashCode implements WeirdHashCode {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///sdk/lib/_internal/vm/lib/object_patch.dart:24:11: Context: The return type of the method 'Object.hashCode' is 'int', which does not match the return type, 'Never', of the overridden method, 'WeirdHashCode.hashCode'.
Change to a subtype of 'Never'.
  int get hashCode => _getHash(this);
          ^
n013.dart:13:13: Context: This is the overridden method ('hashCode').
  Never get hashCode;
            ^
```

These error messages are consistent with a situation where `SecretNonPrimitiveHashCode` is a typical class.

However, `SecretNonPrimitiveHashCode` actually has a non-trivial `noSuchMethod`, which changes the rules when one or more members do not have an implementation with the required signature.

I think the expected behavior is that (1) we detect that `SecretNonPrimitiveHashCode` has a non-trivial `noSuchMethod`, and (2) it does not have an implementation of `hashCode` that is a correct override of the signature in the interface of `SecretNonPrimitiveHashCode`, and hence we should implicitly induce a noSuchMethod forwarder for `hashCode` with the required signature.

The program may not be very useful, but on the other hand it should not have any compile-time errors.

**Comment by bwilkerson** [comment]
Given that this is a corner case, I'm going to initially give it a low priority. Please adjust the priority if you disagree.

**Comment by eernstg** [comment]
My bad, the behavior is correct after all! (So, I'm closing the issue!)

The reason why we _should not_ get an implicitly induced noSuchMethod forwarder is that it would override `Object.hashCode` respectively `Object.[]`. It's ok for a noSuchMethod forwarder to override another noSuchMethod forwarder, but there will not be any such forwarder in the case where it would override an explicitly declared method implementation.

The point is that it would be confusing and error-prone if an existing (visible) method implementation suddenly starts to throw (or behave in some other unexpected way) because we're actually calling an (invisible) noSuchMethod forwarder, just because we have chosen to say `implements SomeClass`, and `SomeClass` makes too big promises about the signature of some member.

So it's all working as intended. Sorry about the noise!
