### ISSUE TITLE
remove experimental annotation from `@reopen` before publishing (for 3.0)

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#51059]
Before we do a `package:meta` release for Dart 3.0, we'll want to remove the `experimental` tag from the `@reopen` declaration.

See: https://dart-review.googlesource.com/c/sdk/+/278888

**Comment by itsjustkevin** [comment]
@pq seems like this is merged, is there any other work required before closing this issue?

**Comment by pq** [comment]
We've still got it marked `@experimental` so we'll want to keep this one open for now...

**Comment by pq** [comment]
This one is gated behind https://github.com/dart-lang/linter/issues/3920.

Assuming that lands we can/should do this.

If it doesn't, we'll want to update the docs to *not* promote the lint.
