### ISSUE TITLE
[CP] [deps] rev dartdoc

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51061]
### Commit(s) to merge

cabf3336061e476cfe3b3c5d19210a5d8d2a400a, partially

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/279320

### Issue Description

Dartdoc had some regressions recently. One big one was https://github.com/dart-lang/dartdoc/issues/3204, fixed in https://github.com/dart-lang/dartdoc/pull/3271, released in dartdoc 6.1.5. In this bug, the up/down arrow keys navigate through the list of suggestions in the search box, but possibly out-of-order.

Also in dartdoc 6.1.5 is a fix for using the Enter key in the search field.

### What is the fix

The fix was to use a flat structure for the suggestions, instead of a tree structure.

### Why cherry-pick

dartdoc is used to build api.dart.dev, which would feature this bug for the docs generated for Dart 2.19.0.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/dartdoc/issues/3204

**Comment by srawlins** [comment]
CC @kevmoo

**Comment by itsjustkevin** [comment]
I see this as low risk and high reward.  I am going to approve this, does anyone disagree?

**Comment by athomas** [comment]
This is in 2.19.0 and on the beta channel.
