### ISSUE TITLE
[CP] [analyzer] Limit the number of plugins-per-context to one

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51062]
### Commit(s) to merge

0ab9f97844a64af2ddd7949ff671adff98c0f096 and 5fe2f3bce2ba7ecbbda9367833f4c0e73fa3d82c

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/279324

### Issue Description

Some users complain on social media that the Dart Analysis Server is slow and consumes a lot of memory. One theory is that these users may be using multiple analyzer plugins and are unaware that they are, or unaware that these multiple analyzer plugins are the culprit. To mitigate this issue, we are limiting the number of analyzer plugins per analysis context to 1.

### What is the fix

The fix is to limit the number of analyzer plugins per analysis context to 1.

### Why cherry-pick

It may be a pressing issue that some users have a poor editing experience due to multiple plugins being run simultaneously. We'd like to fix this before Dart 3.

### Risk

medium

### Issue link(s)

https://github.com/dart-lang/sdk/issues/50981

### Extra Info

I write 'medium' risk, without really knowing what 'low', 'medium', or 'high' mean, for a few reasons:

* This cherry pick required two CLs because the first had issues with the tests
* This cherry pick had merge conflicts that I had to resolve
* I am very very unfamiliar with analyzer plugins. I manually tested the fix, but not with extensive testing. No one in our organization uses analyzer plugins, much less multiple, so this isn't being dogfooded.

**Comment by srawlins** [comment]
CC @jacob314 @mit-mit @devoncarew

**Comment by itsjustkevin** [comment]
@srawlins based on your risk assessment, I don't know if I feel like this cherry-pick is worth the risk so close to the launch.  Do we feel like this is impacting users enough to take the risk?  Are we against having this in the first batch of hotfixes to stable post dart 2.19?

**Comment by srawlins** [comment]
> @srawlins based on your risk assessment, I don't know if I feel like this cherry-pick is worth the risk so close to the launch. 

I agree, but I'll let @mit-mit @bwilkerson and @devoncarew weigh in.

> Do we feel like this is impacting users enough to take the risk?

We don't have much data at all, as we don't have analytics.

> Are we against having this in the first batch of hotfixes to stable post dart 2.19?

I would be fine with that.

**Comment by devoncarew** [comment]
For transparency, I haven't looked through the commits to eval them, but just based on the size, I would hold off on cherry-picking into beta for the launch.

But this _is_ something we want in 2.19 generally; I would be in favor of cherry-picking it for the hot-fixes post-launch. It's an important issue to address and having this fix in 2.19 will help us with messaging to the community ('here are some upcoming changes...').

**Comment by devoncarew** [comment]
(also, @srawlins, thanks for taking this on!)

**Comment by itsjustkevin** [comment]
Thanks for weighing in @srawlins and @devoncarew with that, can we cancel the cherry-pick to beta and stage this for a cherry-pick to stable once we launch the next version?

**Comment by bwilkerson** [comment]
sgtm

**Comment by jacob314** [comment]
sgtm

**Comment by athomas** [comment]
Please re-evaluate for stable.

**Comment by itsjustkevin** [comment]
@srawlins did we ever post a stable cherry-pick for this issue?

**Comment by whesse** [comment]
This has not landed on stable yet, and a stable hotfix will be built tomorrow.
Please create a CL targeting stable with this hotfix, and get it approved and landed.
This issue should also get approval before landing the cherry-pick.

**Comment by srawlins** [comment]
Replacing with https://github.com/dart-lang/sdk/issues/51272 to merge to stable.

**Comment by satvikpendem** [comment]
I'm using a few linting packages, and I'm getting this warning about having multiple plugins, perhaps it's useful to some people to be able to have more than one plugin active, maybe behind an advanced flag in `analysis_options.yaml`? I made a related issue here: https://github.com/invertase/dart_custom_lint/issues/78
