### ISSUE TITLE
API doc issue: Documention Typo in dart:io RandomAccessFile.readIntoSync method

### ISSUE THREAD

**Issue by beesaferoot** [dart-lang/sdk#51073]
A minor typo in the sentence:
> Reads bytes and writes ~~then~~ into the range of buffer from start to end

Should be _them_ instead.

ref: https://api.dart.dev/stable/2.18.6/dart-io/RandomAccessFile/readIntoSync.html

**Comment by beesaferoot** [comment]
Would like to land a PR but couldn't find where this can be fixed from.

**Comment by a-siva** [comment]
//cc @brianquinlan

**Comment by asashour** [comment]
Please close this, the CL is merged.
