### ISSUE TITLE
[dart2wasm] Default map/sets use inefficient implementations that assume user-provided `equals`, `hashCode`, `isValidKey`

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51070]
https://github.com/dart-lang/sdk/blob/dc12e2982bc0d34cebe73b061d5568942ca2cdd0/sdk/lib/_internal/wasm/lib/hash_factories.dart#L28-L29

https://github.com/dart-lang/sdk/blob/dc12e2982bc0d34cebe73b061d5568942ca2cdd0/sdk/lib/_internal/wasm/lib/hash_factories.dart#L54-L55

Currently default maps and sets (which are also used in map and set literals) use the implementation types shown above.

These types use user-provided `equals`, `hashCode`, and `isValidKey` functions and so they're slow in the common case where none of those are provided.

In particular, these types use this mixin from the standard library, which calls the provided `hashCode` and `equals` dynamically:

https://github.com/dart-lang/sdk/blob/dc12e2982bc0d34cebe73b061d5568942ca2cdd0/sdk/lib/_internal/vm_shared/lib/compact_hash.dart#L269-L277

(the `... as Function` part makes these dynamic calls, as the shape and argument types of the function being called is not known in the call site)

For the common cases with no user-provided equals, hashCode, and isValidKey, VM uses more efficient `_Map` and `_Set` types. However those types use external methods so we cannot directly use them in dart2wasm.

We should implement similar `_Map` and `_Set` types that use `Object.operator ==`, `Object.hashCode`, and no `isValidKey`, and use these map and set types in literals and when none of `equals`, `hashCode`, and `isValidKey` are provided.

**Comment by askeksa-google** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/279164

**Comment by osa1** [comment]
Merged with 2e1624199891d8e384a2658a83623e3f041b9318. I've confirmed that the dynamic calls in default maps and sets disappeared in benchmarks.
