### ISSUE TITLE
DevTools 2.20 in the Dart SDK was released with experimental features enabled

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#51078]
The version of DevTools currently in the SDK was built in profile mode instead of release mode, which resulted in all of the DevTools experimental features being enabled. Many of these features are incomplete or broken and should not be shipped with the 2.19 release.

We should create a new release and have it cherry picked in to the outgoing stable release.

FYI @mit-mit @itsjustkevin @kevmoo @vsmenon @a-siva

**Comment by bkonyi** [comment]
Tracking issue on the DevTools repo: https://github.com/flutter/devtools/issues/5073

**Comment by kenzieschmoll** [comment]
The commit that will need to be cherry picked is up for review now: https://dart-review.googlesource.com/c/sdk/+/279335

**Comment by a-siva** [comment]
lgtm for cherry pick.

**Comment by whesse** [comment]
Converted to a CP request issue, because the CP approval is on this issue already.

CP to beta changelist: https://dart-review.googlesource.com/c/sdk/+/279383

**Comment by athomas** [comment]
This is in 2.19.0.
