### ISSUE TITLE
[CP] DevTools hotfix 2.20.1

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#51083]
### Commit(s) to merge

c1642b396c4d791cf79f0de35d70b8352710c169

### Target

both

### Prepared changelist for beta/stable

none yet - unavailable to do this for the next 2 hrs

### Issue Description

The version of DevTools currently in the SDK was built in profile mode instead of release mode, which resulted in all of the DevTools experimental features being enabled. Many of these features are incomplete or broken and should not be shipped with the 2.19 release.

https://github.com/dart-lang/sdk/issues/51078

### What is the fix

Release a new version of DevTools 2.20.1 that is build in release mode, not profile mode. This has been uploaded to CIPD and the DEPS file change is here: https://dart-review.googlesource.com/c/sdk/+/279335

Here is the diff of the DevTools changes between 2.20.0 and 2.20.1: https://github.com/flutter/devtools/compare/v2.20.0...kenzieschmoll:devtools:2.20.1?expand=1.

This includes a few changes to some tool scripts and a version bump. The last line in that diff changes the build command from using `--profile` to `--release`, which is the important part of this fix.

### Why cherry-pick

This issue affects all Dart and Flutter users using DevTools. Incomplete and broken features that were supposed to be behind an experiment flag were accidentally turned on and released to the Dart and Flutter SDKs. This also affects our analytics, and analytics from the time that DevTools 2.20.0 was shipped with Dart and Flutter show that we have stopped receiving GA events (these are only sent in release mode and therefore not in the profile build that was shipped as 2.20.0).

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51078

### Extra Info

I built the SDK with this change and verified the 2.20.1 version of DevTools is included and the experimental features are disabled as intended.

**Comment by mit-mit** [comment]
sgtm

**Comment by vsmenon** [comment]
lgtm

**Comment by a-siva** [comment]
lgtm

**Comment by athomas** [comment]
This is in 2.19.0.
