### ISSUE TITLE
`body_might_complete_normally_catch_error` not reported by dart analyze

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#51096]
Apparently the `body_might_complete_normally_catch_error` gets only partially reported.

Consider the following code sample:

```dart
void main() async {
  await Future.delayed(const Duration(seconds: 1), () => 24).catchError((_) {
    // LINT: body_might_complete_normally_catch_error
  });
}
```

The `catchError()` gets a lint warning as expected for `body_might_complete_normally_catch_error` in VSCode:
![Screenshot 2023-01-23 at 12 08 10](https://user-images.githubusercontent.com/23480364/214025151-17016395-58d4-44af-81ae-98d194105d88.png)

but if I run `dart analyze lib/foo.dart` I get 

```
Analyzing foo.dart...                  1.6s
No issues found!
```

As a side note, there is no link to the lint documentation either (lint code does not have a link in the tooltip)

VSCode version: 1.74.3 (Universal)
Dart-Code: v3.56.0
Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "macos_x64"

**Comment by asashour** [comment]
I am not able to reproduce with `Dart SDK version: 3.0.0-136.0.dev (dev) (Wed Jan 18 09:30:53 2023 -0800) on "windows_x64"`.

Would you mind testing with `beta` or `dev`/`master` branch? I also believe that 2.19 release is immanent.

**Comment by navaronbracke** [comment]
Apparently, I have the exact same issue with the `override_on_non_overriding_member` lint.

**Comment by navaronbracke** [comment]
@asashour Ah, that might be it. Both are diagnostic messages. Would be nice if I could tell the analyzer to also report those with the same priority as lints.

`--fatal-infos` doesn't help though. I'll check with a more recent version of the SDK.

**Comment by asashour** [comment]
Changing the priority of errors can be done with `analyzer: errors:` as described [here](https://dart.dev/guides/language/analysis-options#changing-the-severity-of-rules).

```
analyzer:
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
```

**Comment by navaronbracke** [comment]
Thanks, that should do it for me.
