### ISSUE TITLE
`invalid_use_of_protected_member` is not a recognized lint rule

### ISSUE THREAD

**Issue by FelixZY** [dart-lang/sdk#51090]
I just upgraded flutter from `3.3.9` to `3.7.0-1.4.pre` which included a dart upgrade to

```
$ dart --version
Dart SDK version: 2.19.0-444.4.beta (beta) (Tue Jan 10 10:24:44 2023 +0000) on "linux_x64"
```

After this upgrade, the analyzer rule `invalid_use_of_protected_member` seems to have been removed (`'invalid_use_of_protected_member' is not a recognized lint rule` - `dart(undefined_lint_warning)`), but I cannot find any deprecation notice or related information.

* Was this rule intentionally removed?
* If so, what is the new recommendation for detecting improper use of `@protected` members?

**Comment by bwilkerson** [comment]
@srawlins

**Comment by srawlins** [comment]
Where does this text come from?

> 'invalid_use_of_protected_member' is not a recognized lint rule - dart(undefined_lint_warning)

I am unfamiliar with this. As far as I know, the rule is still around, though it is not a lint rule, and never was. It is a "hint." [This unit test](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/test/src/diagnostics/invalid_use_of_protected_member_test.dart) asserts it is still present.

**Comment by asashour** [comment]
Could you share `analysis_options.yaml`?

Putting `invalid_use_of_protected_member` inside `linter: rules:` gives that error (also with the stable version `3.3.10`), which is correct, since it is not a lint, should be instead in `analyzer: errors:`

**Comment by asashour** [comment]
The reason is: in the stable version, if rules is a map (not a list), they weren't checked if they exist or not, that's why there weren't a warning before.

The new behavior is correct, and the fix is in 6e03189e2b1c32ce4f8e472d81d93471ae2d814c

In other words, the previous entry didn't have an effect, if you need this `hint`, please put it in `analyzer: errors:`

**Comment by FelixZY** [comment]
Got it. I remember going through https://dart-lang.github.io/linter/lints/index.html to set up my `linter: rules:` so I guess that page has contained `invalid_use_of_protected_member` at some point.

I have not been able to find as extensive documentation on `analyzer: errors:` - could you point me the right way?

Thank you for your assistance!

**Comment by asashour** [comment]
Please look [here](https://dart.dev/guides/language/analysis-options#customizing-analysis-rules)

**Comment by srawlins** [comment]
Thanks @asashour !

**Comment by amrgetment** [comment]
Is there a linter for protected members?

**Comment by bwilkerson** [comment]
If we're talking about members marked with `@protected`, then, no, there is no _lint_ for this case, but there is a _warning_ for this case. (The difference being that a lint needs to be explicitly enabled while a warning is enabled by default.)

If you're seeing a situation in which a protected member is being used outside the library and/or a subtype of the defining type, but isn't being flagged, that might be a bug.
