### ISSUE TITLE
[CP] Avoid confusing sdk-ranges in pub solve-error messages.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#51101]
### Commit(s) to merge

(Has not been merged to main yet)

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/279509

### Issue Description

Pub can show wrong/misleading/confusing ranges for unfulfilled sdk constraints in 2.19.

We introduced an sdk rewrite to allow dart 3 to be compatible with dart 2.12 and later, such that internally it treats constraints like `>=2.12.0 <3.0.0` as `>=2.12.0 <4.0.0`. But that was landed already in 2.19, where a constraint like `>=2.19.5 <3.0.0` might give a message like:

Because library requires SDK version >=2.19.0-beta.1 <4.0.0, version solving failed.

Details:
https://github.com/dart-lang/pub/issues/3738

### What is the fix

We disable the logic for treating `>=2.12.0 <3.0.0` as `>=2.12.0 <4.0.0` for the 2.19 branch.

### Why cherry-pick

This has no functional consequences, but can lead to confusing error messages.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/pub/issues/3738

**Comment by sigurdm** [comment]
CC @athomas

**Comment by mit-mit** [comment]
SGTM

**Comment by athomas** [comment]
I'm not sure this meets the bar for release blocker, because it's just an incorrect error message with no functional consequences. We're running the CQ now and will make a call on merging this around 16:00. This could go into a stable hotfix as well.

**Comment by itsjustkevin** [comment]
It would take an extremely detrimental bug for us to feel comfortable cheery-picking into a stable release.

I am leaning toward pushing this to a fast follow stable hot fix over cherry-picking into the release. 

Could we change the geritt CL to run against the stable branch instead?

**Comment by athomas** [comment]
Agreed. Let's defer this to 2.19.1 stable.

**Comment by athomas** [comment]
SGTM for stable, marking this as approved.

**Comment by sortie** [comment]
Released in 2.19.1.
