### ISSUE TITLE
Provide `length` of `Record` types to VM service clients 

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#51104]
`Strings`, `Lists`, `Maps` and `Sets` all have a `length` property. I think `Record` types should also have a `length` property, corresponding to the number of fields in a `Record`.

**Comment by rmacnak-google** [comment]
If a record has both indexed and named fields, do both count towards the record's length or only the indexed fields?

**Comment by elliette** [comment]
> If a record has both indexed and named fields, do both count towards the record's length or only the indexed fields?

I would think that both should count. The following record for example should have a length of 6:

`var myRecord = (1, a: "hello", "hi", b: 4, true, c: {"greeting": "hi"});`

**Comment by bkonyi** [comment]
I think we'd be okay counting both named and indexed fields, as long as it's properly documented.

**Comment by derekxu16** [comment]
Documenting the rationale behind this change: we added `length` to `Record` `@Instance`s to allow clients to know how many fields a record has without having to make a second call to `getObject` to get a full `Instance`. We also added `length` to `Record` `Instance`s for consistency.
