### ISSUE TITLE
`Abi.values` documentation contains obsolete TODO comment

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#51103]
See https://api.dart.dev/stable/2.18.7/dart-ffi/Abi/values-constant.html

**Comment by rmacnak-google** [comment]
The nearby comment about windows-arm64 is also stale: we build and upload an SDK for it now.

**Comment by brianquinlan** [comment]
OK, I'll remove that as well.

**Comment by a-siva** [comment]
Can this be closed now ?

**Comment by brianquinlan** [comment]
Fixed in I737c17e06a346bba138133e78871a2919f8073ea
