### ISSUE TITLE
dartdev `create web` templates for Dart 3.0 support

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#51106]
The integration test for creating a new Dart Web project is failing and currently skipped because it takes too long to timeout on the failure. https://github.com/dart-lang/sdk/issues/51037

I believe these are the steps remaining to get it working:
- [x] Publish `build_web_compilers` compatible with Dart 3.0.0-134.0.dev (already done v4.0.0).
- [x] Publish `dwds` compatible with Dart 3.0.0-134.0.dev.
- [x] Publish `webdev` compatible with `dwds` and `build_web_compilers` that are compatible with Dart 3.0.0-134.0.dev.
- [x] Update dartdev web template to depend on `build_web_compilers: 4.0.0`.

**Comment by nshahan** [comment]
@annagrin I believe the list above should cover everything we need to fix the `dart create web` command.

**Comment by annagrin** [comment]
@mit-mit @nshahan we need to publish a new version of webdev that works with current SDK. Here are the steps we normally follow to make sure the published package is properly tested:

- roll dwds master internally, wait for a week to fix any issues encountered by the users
- publish dwds
- publish webdev

I tested the `dart create web` command with my local webdev installation and it works, so as soon as we publish webdev it should just start working.

Does this schedule sound acceptable for the fix?

**Comment by nshahan** [comment]
The test is passing on linux and mac but failing on windows. Unfortunately the test output log is not very helpful. https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8790341062187901153/+/u/test_results/new_test_failures__logs_

Since the updates in the build and webdev packages were related to filenames and paths my only guess is that one of them isn't correct for windows. Still investigating.
