### ISSUE TITLE
README.dart-sdk is out of sync for the items in bin/

### ISSUE THREAD

**Issue by RandalSchwartz** [dart-lang/sdk#51108]
The README.dart-sdk listing for `bin` contains a few entries that are no longer located in the SDK (such as `dartdoc`).  Needs a proper sync-up.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/279703

**Comment by asashour** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/e4b830057a3383813d163fa08e4b123df68c4e65.
