### ISSUE TITLE
[cfe] process `.dart_tool/build/generated` folder

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#51105]
This is the CFE part of #51087, to support [build](https://github.com/dart-lang/build)

The below cases don't find the `part`, on running `main()`, taken from the sample [package](https://github.com/greglittlefield-wf/generated_part_issue_repro/):

```dart
// example/foo.dart
part 'foo.g.dart';

void main() {
  print(_abc);
}
```

```dart
// .dart_tool/build/generated/<project_name>/example/foo.g.dart
part of 'foo.dart';

var _abc = 'hello';
```

<details>

<summary>error</summary>

```
example/foo.dart:1:6: Error: Error when reading 'example/foo.g.dart': The system cannot find the file specified.

part 'foo.g.dart';
     ^
example/foo.dart:1:6: Error: Can't use 'example/foo.g.dart' as a part, because it has no 'part of' declaration.
part 'foo.g.dart';
     ^
example/foo.dart:4:9: Error: Undefined name '_abc'.
  print(_abc);
        ^^^^
```

</details>
<hr>

Having `library` also gives similar error.

```dart
// example/foo_lib.dart
library foo_library;

part 'foo_lib.g.dart';

void main() {
  print(_abc);
}
```

```dart
// .dart_tool/build/generated/example/foo_lib.g.dart
part of 'foo_lib.dart';

var _abc = 'hello';
```

/cc @greglittlefield-wf

**Comment by johnniwinther** [comment]
@asashour @jakemac53 Where is it specified that we are supposed to handle this?

**Comment by jakemac53** [comment]
@johnniwinther I am not aware of any plan to support this in the CFE

**Comment by jakemac53** [comment]
Note that you should be able to use `dart run build_runner run <script>` instead of `dart <script>` and that should work for build to cache files.

**Comment by asashour** [comment]
> should be able to use `dart run build_runner run <script>` instead

You are right, sorry that I didn't test it this way.

Apologies for the disturbance.
