### ISSUE TITLE
Re-enable tcmalloc for RV64

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51111]
RV64 builds began failing with

```
obj/runtime/vm/compiler/backend/libdart_compiler_precompiler_testing.inliner.o: in function `std::unique_ptr<dart::CompilerTimings::Timers, std::default_delete<dart::CompilerTimings::Timers> >::~unique_ptr()':
/usr/riscv64-linux-gnu/include/c++/9/bits/unique_ptr.h:291:(.text._ZN4dart16FlowGraphInliner16CollectGraphInfoEPNS_9FlowGraphElbPlS3_+0x506): relocation truncated to fit: R_RISCV_JAL against symbol `free' defined in google_malloc section in obj/third_party/tcmalloc/gperftools/src/tcmalloc.tcmalloc.o
collect2: error: ld returned 1 exit status
```

This is apparently related to a bug in ld/binutils related to linker relaxation and weak symbols. This bug was fixed two ways: the switch from -O3 to -O2 reduced binary size avoiding the range issue and disabling tcmalloc created fewer weak symbols.

We should re-enable tcmalloc either when we update to a new version of gcc or when Fuchsia clang supports RV64.

If the problem recurs before then, we can disable linker relaxation entirely with -mno-relax.

**Comment by mkustermann** [comment]
Since our dependency on tcmalloc is gone, we can probably close this issue.
