### ISSUE TITLE
Fix capture during matching

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#51112]
Currently `patterns/switch_expressions_variable_capture` fails because the joint variable is captured instead of the declared variable.

**Comment by johnniwinther** [comment]
@chloestefantsova This might be related to the issues you mentioned.

**Comment by chloestefantsova** [comment]
It seems so! That's my next target. Thanks!

**Comment by chloestefantsova** [comment]
Related to https://github.com/dart-lang/sdk/issues/50898
