### ISSUE TITLE
Duplicated enums across a web project when in DDC

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#51114]
I can't seem to reproduce it easily as our web project is big, but basically a simple enum is not the same in different parts of a project when compiling with DDC. It doesn't happen with dart2js.

```dart
enum Foo {foo}

class Bar { Foo f = Foo.foo; }

void main() {
  final b = Bar();

  print(b.f == Foo.foo); // prints false
  print(b.f.name == Foo.foo.name); prints true
  print(b.f.hashCode == Foo.foo.hashCode); prints false
}
```

Dart SDK version: 2.19.0-255.2.beta (beta) (Tue Oct 4 13:45:53 2022 +0200) on "macos_x64"

**Comment by jodinathan** [comment]
it seems it has to do with aliased imports and static usage, ie:

```dart
// file A
enum Foo {foo}

// file B
import 'foo.dart' as f;
class Bar {
  static values = f.Foo.values;
}

// file C
void main() {
  print(Bar.values.first == Foo.foo); // false and all items in Bar.values have different hashCode from Foo.values
}
```

**Comment by nshahan** [comment]
@jodinathan Were you able to reproduce with the example in your second comment? I haven't been able to reproduce this yet.

**Comment by jodinathan** [comment]
unfortunately no.  
As the Dart 3 is in development I will close this ticket and reopen it if it happens again.
