### ISSUE TITLE
Using WeakArrays for representation of set of dependent code has issues

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#51125]
Using WeakArrays for representation of set of dependent code has issues.

One issue seems to be in `CodeTraits`:
```c++
class CodeTraits {
  ...
  static uword Hash(const Object& key) {
    ASSERT(key.IsCode());
    return Code::Cast(key).PayloadStart();
  }
};
```
we use `PayloadStart()` as hash.  Since such hash may be different from run to run it will make our `app-jit` snapshots no longer deterministic.

**Comment by mkustermann** [comment]
Apart from non-determinism I have reason to believe that [cl/278943](https://dart-review.googlesource.com/c/sdk/+/278943) have led to situations where we miss to deoptimize code that should be deoptimized (possibly related to AppJIT snapshot generation & running such snapshots)

**Comment by mkustermann** [comment]
The exact failure can be seen at tip-of-tree when trying to reland that CL, see [cl/279712](https://dart-review.googlesource.com/c/sdk/+/279712?tab=checks) & [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8790987626630078545/+/u/test_results/new_test_failures__logs_):
```
/=======================================================================================================\
| co19/LanguageFeatures/Named-arguments-anywhere/global_t02 broke (Pass -> RuntimeError, expected Pass) |
\=======================================================================================================/

--- Command "dartdevc" (took 177ms):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/dart-sdk/bin/snapshots/dartdevc.dart.snapshot -Dtest_runner.configuration=dartdevk-strong-linux-release-chrome --sound-null-safety -Dtest_runner.configuration=dartdevk-strong-linux-release-chrome --ignore-unrecognized-flags --no-summarize -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_global_t02/global_t02.js /b/s/w/ir/tests/co19/src/LanguageFeatures/Named-arguments-anywhere/global_t02.dart -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/async_helper.dill=async_helper -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/expect.dill=expect -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/js.dill=js -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_sound/meta.dill=meta

exit code:
0

--- Command "chrome" (took 01.000784s):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:43209/root_build/generated_tests/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_global_t02/test.html?crossOriginPort=38685

Runtime error:
ReferenceError: t0 is not defined
    at Object.main (http://127.0.0.1:43209/root_dart/out/ReleaseX64/generated_compilations/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_global_t02/global_t02.js:74:78)
    at testMainWrapper (http://127.0.0.1:43209/root_build/generated_tests/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_global_t02/test.html?crossOriginPort=38685:86:102)

Deobfuscated error and stack:
ReferenceError: t0 is not defined
    at Object.main     ../../../../../tests/co19/src/LanguageFeatures/Named-arguments-anywhere/global_t02.dart 19:47
    at testMainWrapper out/ReleaseX64/generated_tests/dartdevk-strong-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_global_t02/test.html 86:102


exit code:
0

--- To debug locally, run:
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/pkg/test_runner/bin/http_server.dart -p 43209 -c 38685 --network 127.0.0.1 --build-directory=/b/s/w/ir/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/.dart_tool/package_config.json

--- Re-run this test:
python3 tools/test.py -n dartdevk-strong-linux-release-chrome co19/LanguageFeatures/Named-arguments-anywhere/global_t02
```

When investigating these it seemed that the `tools/build.py` step that creates AppJIT snapshots of `dartdevc` (ddc compiler) has the issue. Though running app-jit training many times, seemingly results in this issue sometimes appearing and sometimes not.

When the app-jit snapshot has the issue in it, running the app-jit on this co19 test causes the ddc code to run incorrectly, producing the incorrect javascript.

My suspicion is that the running of ddc's appjit snapshot causes some things to be invalidated, but we don't properly deoptimize code, thereby running the wrong thing, which makes the ddc compilation produce the wrong js.

**Comment by rmacnak-google** [comment]
I'm sad that appjit_determinism_test didn't catch this :(

**Comment by rmacnak-google** [comment]
I think the missing deopts are caused by the non-deterministic hash code: a code will be inserted based on the training address, the address will be different in the trained run, so the set lookup will give false negatives.

**Comment by mkustermann** [comment]
> ... so the set lookup will give false negatives

My thinking was that on deoptimization we loop over the entire array and deoptimize all dependent code and as such the hash wouldn't matter at all for that purpose, so I was puzzled why the hash causes this issue.

Reading through the code I can see that there's one place where it does matter: On deoptimization we also have to walk the stack and here we now use the set lookup which would then return false-negative due to different entrypoint and then make us not lazy-deopt where we should.

Mystery solved :)

**Comment by mkustermann** [comment]
Thanks for fixing, @rmacnak-google . Guess we can close this now.
