### ISSUE TITLE
[analyzer] `unnecessary_null_comparison` with null constants

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#51121]
```dart
const s = null;

void f(int i) {
  if (i == s) { // <- here
    print('');
  }
}
```

`unnecessary_null_comparison` should be triggered. It seems it is currently triggered with only `null` literal.

**Comment by bwilkerson** [comment]
Adding this to the warning would introduce some false positives. Consider, for example
```
const logForName = null;

void f(String name) {
  if (name == logForName) {
    // ...
  }
}
```

I could imagine adding such code as a debugging aid. While it isn't hard to add an ignore for such a case, I suspect that the number of times someone defines a new name for `null`, with no intention that the name will never be non-`null` is very small, so I don't think we should do this.

**Comment by asashour** [comment]
I see, thanks.
