### ISSUE TITLE
[CP] Fix crash when isolates shares and use one RegEx concurrently

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#51130]
### Commit(s) to merge

438b81c4f26693366a220b5571a9c6c75cbabca7, 4275d595b6524d3d0d2c3d89f6327e10d644494e

### Target

both

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/279747

### Issue Description

RegEx runtime execution state was incorrectly shared between isolates, which resulted in one isolate potentially affecting another by overwriting currently running RegEx execution state(backtracking stack, etc). If one has long running RegEx, that probability of a crash increases significantly.

### What is the fix

First commit disables sharing of RegEx completely, fixing the crash, but regressing the performance of sending RegEx across isolates.
Second commit restored fast RegEx sharing, making sure that runtime state(backtracking stack and others) are kept local to every isolate.

### Why cherry-pick

The fix missed the window for 2.19.0, users would like the fix to be available on stable.

### Risk

medium

### Issue link(s)

https://github.com/dart-lang/sdk/issues/50082

**Comment by a-siva** [comment]
lgtm, the customer would like to have this fixed in a stable version.

**Comment by sortie** [comment]
Released in 2.19.1.

**Comment by Cat-sushi** [comment]
I confirmed this issue is fixed at 2.19.1.
Thank you.
