### ISSUE TITLE
[dart2wasm] A new runtime type function needed for records

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51134]
This is an issue with the records implementation, but I wanted to create a new issue as I think it shouldn't block #50014.

When generating runtime type of a record we currently (in the WIP CL, not yet merged) call `runtimeType` of the record fields.

This is not right as we don't want to show the overridden runtime types, but the actual runtime type. For example:

```dart
class CustomRuntimeType {
  Type get runtimeType => String;
}

void main() {
  print((CustomRuntimeType(),).runtimeType);
}
```

AOT prints `(CustomRuntimeType)`, dart2wasm prints `(String)`.

Unfortunately we also can't directly use the class ID of the members, we need to map `_BoxedInt` to `int`, `_BoxedBool` to `bool`, and the same for the other implementation types (typed arrays etc.).

@askeksa-google  tried adding a new member to `Object` for this purpose. The idea is that this new member would only be overridden by the implementation classes and nothing else.

However the problem with this is that `dart:typed_data` is not a part of `dart:core`, so a private member like `Object._myInternalRuntimeType` cannot be overridden in `typed_data` types like `_Uint16List`.

**Comment by osa1** [comment]
I can think of two ways of implementing this runtime type function. (I'll call it `implementationRuntimeType`)

1. We generate a single Wasm function, as an intrinsic. It will have hard-coded mapping of `_BoxedInt` => `int` etc. and generate if-else chains to compare class IDs with the known implementation classes and return the interface types. If the argument is not a known implementation class it will call `_runtimeType`.

   The problem with this is that the if-else chain will be slow to execute every time we do a type check. Type checks are already slow though so perhaps this won't be a big deal.

2. We add a new `Object` member `_Type get _implementationRuntimeType => _runtimeType`. We never override this, but when generating dispatch table entries for this member, we implement special cases for the known implementation types and add functions that return `int`, `bool` etc. to the table instead of adding the default implementation.

   This will be basically free in runtime as we already do an instance invocation to get the runtime types currently. We will just have a few extra dispatch table entries for the `_implementationRuntimeType` member.

I think (2) should be good. @askeksa-google thoughts?

**Comment by osa1** [comment]
I just realized (2) is the same as what @askeksa-google tried, except it's done in the compiler to work around the limitation with overriding a private member outside of the library that defines the class.

**Comment by askeksa-google** [comment]
Another option: Have a constant array that maps class IDs to masqueraded class IDs and look up into this list when generating masqueraded runtime types.

The array needs to be big enough to cover the masqueraded class with the highest class ID. We could initialize masqueraded classes before other classes (like we currently do for `_Closure` and `_Type`) so they get small class IDs.
