### ISSUE TITLE
[CFE] Pattern temporary variables are incorrectly typed

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51138]
Part of https://github.com/dart-lang/sdk/issues/49749.

Example:

```dart
String test(List list) {
  return switch (list) {
    <num>[3, >0] => "relational",
    [4, var c as num] => "cast",
    _ => "default",
  };
}

main() {
  test([4, "42"]);
}
```

Kernel AST before VM-specific transformations (before `Target.performModularTransformationsOnLibraries`):
```
  static method test(core::List<dynamic> list) → core::String {
    return block {
      core::String #t1;
      core::int #t2 = -1;
      core::num c;
      final core::List<dynamic> #0#0 = list;
      late final core::bool #0#3 = #0#0{core::List<core::num>}.{core::List::length}{core::int} =={core::num::==}{(core::Object) → core::bool} #C1;
      late final core::num #0#6 = #0#0{core::List<core::num>}.{core::List::[]}(0){(core::int) → core::num};
      late final core::num #0#9 = #0#0{core::List<core::num>}.{core::List::[]}(1){(core::int) → core::num};
      if(#0#0 is{ForNonNullableByDefault} core::List<core::num> && #0#3 && #C2 =={core::num::==}{(core::Object) → core::bool} #0#6 && (let final dynamic #t3 = #0#9 in #0#9.{core::num::>}(#C3){(core::num) → core::bool})) {
        #t2 = 0;
      }
      else
        if(#0#3 && #C4 =={core::num::==}{(core::Object) → core::bool} #0#6 && (let final dynamic #t4 = #0#9 as{ForNonNullableByDefault} core::num in let final dynamic #t5 = c = #0#9 as{ForNonNullableByDefault} core::num in true)) {
          #t2 = 1;
        }
        else
...
```

The problem is that for the pattern `[4, var c as num]` we check that length of the list is 2 (in `#0#3`), and then we access list elements via late variables `#0#6` and `#0#9` which have type `num`, but the original list is `List<dynamic>` and it can have non-`num` elements. As a result, values of `#0#6` and `#0#9` may violate their static type. Also, cast `#0#9 as{ForNonNullableByDefault} core::num` is eliminated as redundant because `#0#9` has type `num` already.

Test `co19/LanguageFeatures/Patterns/list_A01_t01` currently fails with RuntimeError due to this bug.

@chloestefantsova @johnniwinther

**Comment by alexmarkov** [comment]
The test `co19/LanguageFeatures/Patterns/list_A01_t02` also fails because of this bug.

**Comment by johnniwinther** [comment]
I'm working on this.
