### ISSUE TITLE
Inferred variable/field types should not be used as context when doing full resolution

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51137]
Consider the following code:
```dart
// @dart=2.17
T? inferFromArgs<T>(
        T Function(List<int>) fromBytes, List<int> Function(T) toBytes) =>
    null;
final x = inferFromArgs(String.fromCharCodes, (m) => m.codeUnits); // (1)
void main() {}
```
The `// @dart=2.17` annotation disables horizontal inference.  So, when analyzing (1), the analyzer should push down a context of `List<int> Function(?)` when analyzing the closure `(m) => m.codeUnits`.  Therefore, the inferred type of the parameter `m` should be the greatest closure of `?`, which is `Object?`.  As a result, there should be a compile-time error, because the type `Object?` doesn't support the getter `.codeUnits`.  The CFE produces the proper error message.

Here's what happens when the analyzer analyzes this code: since (1) is a top level variable declaration with no explicit type, the analyzer first performs top level type inference, which involves resolving the right hand side of the declaration.  The type `Object?` is correctly assigned to `m`, however no error is reported because the analyzer doesn't report errors during top level type inference.  The inferred type of the variable `x` is `String?`.

Then, after top level type inference is complete, the analyzer visits the entire file and resolves it, reporting errors.  Which means that it visits the declaration of `x` a second time.  On the second visit, the inferred type of `String?` is pushed down as a context.  As a result, even though horizontal inference is disabled, the type `String` is inferred for `m`, and so no error is reported.

I believe the easiest way to fix this would be to change the analyzer so that when resolving a top level variable or field declaration, it only passes the context type down to the initializer if the type is explicit.

(Note that since the CFE already reports the correct error here, it should not be necessary to go through the breaking change process for this change).

**Comment by natebosch** [comment]
Does this affect newer language versions?

**Comment by stereotype441** [comment]
> Does this affect newer language versions?

Yes, it applies to all language versions.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/281462
