### ISSUE TITLE
[CP] Fix VM crash due to incorrect flowgraph float representation (JIT/debug configurations)

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#51147]
### Commit(s) to merge

ff2d661d5ba07766fc27196e98df6c6ae80444b9

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/279917

### Issue Description

Mixed use of double and float calculation could cause to VM crash in debug/jit configuration.

### What is the fix

The fix ensures correct (float) representation for phi-instructions, fixing the crash.

### Why cherry-pick

Flutter and dart users are affected by the crash 

### Risk

medium

### Issue link(s)

https://github.com/flutter/flutter/issues/118559, https://github.com/dart-lang/sdk/issues/50622

**Comment by itsjustkevin** [comment]
@a-siva thoughts on this cherry-pick as it is a medium risk?

**Comment by a-siva** [comment]
lgtm

**Comment by HayesGordon** [comment]
@itsjustkevin and @a-siva  Can we get this in please 🙏 

It's impacting a lot of people

**Comment by itsjustkevin** [comment]
Thanks for the cherry-pick @aam

**Comment by whesse** [comment]
The cherry-pick still needs to be landed by the author

**Comment by itsjustkevin** [comment]
@aam you are free to land the change as it has been approved!

**Comment by mikeesouth** [comment]
Not sure why this is still open. Is this merged so it will land in 3.7.2?

**Comment by whesse** [comment]
It is merged, but the stable releases haven't been built and published yet.
