### ISSUE TITLE
[analyzer] incorrect dead_code in for loop that ends with a switch statement

### ISSUE THREAD

**Issue by xtyxtyx** [dart-lang/sdk#51145]
<img width="906" alt="CleanShot 2023-01-28 at 00 07 24@2x" src="https://user-images.githubusercontent.com/15033141/215133723-eb749beb-a75c-4573-a8e2-74f29fcf99cc.png">

Seems related to #50189

**Comment by bwilkerson** [comment]
@stereotype441

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/280084
