### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by BhaviniJain23** [dart-lang/sdk#51153]
## Version information

- `IDEA AI-221.6008.13.2211.9477386`
- `2.19.0`
- `AI-221.6008.13.2211.9477386, JRE 11.0.15+0-b2043.56-8887301x64 JetBrains s.r.o., OS Mac OS X(aarch64) v13.2, screens 2880.0x1800.0  Retina`

**Comment by vsmenon** [comment]
Is there a bug report here or stack trace to attach?
