### ISSUE TITLE
patterns not working after jsonDecode

### ISSUE THREAD

**Issue by kmvignesh** [dart-lang/sdk#51157]
I was trying dart 3 `patterns` and found one wired issue.

```
main(){
  Map<String, dynamic> json = jsonDecode('{"total":7,"result":["Apple","Pineapple"]}');
  Map<String, dynamic> hardcoded = {
    "total": 7,
    "result": ["Apple", "Pineapple"],
  };
  checkJson(json);
  checkJson(hardcoded);
}

void checkJson(var data) {
  switch (data) {
    case {"total": int total,"result": List<String> list} :
      print('list : $list, total:$total');
    default:
      print('structure match not found');
  }
}
```
json resulting -> structure match not found
hardcoded resulting -> list : [Apple, Pineapple], total:7

<img width="1129" alt="Screenshot 2023-01-29 at 4 04 08 PM" src="https://user-images.githubusercontent.com/17671967/215320458-54424d88-2f95-455f-b7b1-3ec1dc6958b5.png">

Also i have verified the data type after `jsonDecode`
<img width="1193" alt="Screenshot 2023-01-29 at 4 05 45 PM" src="https://user-images.githubusercontent.com/17671967/215320549-fc718056-e7ec-4702-8f86-16aa4377ece9.png">

**Comment by asashour** [comment]
On changing the type to `List<dynamic>`, both are found:

```dart
void checkJson(var data) {
  switch (data) {
    case {"total": int total, "result": List<dynamic> list} :
      print('list : $list, total:$total');
    default:
      print('structure match not found');
  }
}
```

**Comment by lrhn** [comment]
That's correct and expected behavior. The result list is a `List<dynamic>` which does not satisfy the `List<String>` type check.

There is currently no way to match a list containing an unknown number of elements that all satisfy some pattern, each sub-pattern in pattern is applied to only one value.
