### ISSUE TITLE
package:meta 1.9.0 has not been published yet

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#51154]
The version of `package:meta` on pub.dev currently is 1.8.0, which is 8 months old.

Now that Dart 2.19 has been released, a new version should be published for the new `@reopen` and `@mustBeOverridden` annotations.  Not sure if this was overlooked or if there's some other reason to delay publishing a new version. (Note that meta's `pubspec.yaml` in the GitHub repo still says 1.8.0.)

CC @srawlins

**Comment by vsmenon** [comment]
@devoncarew @srawlins - do we intend to publish this on a particular cadence?

**Comment by srawlins** [comment]
No particular cadence, but I do intend to publish 1.9.0 tomorrow.

**Comment by jamesderlin** [comment]
Thanks!
