### ISSUE TITLE
[CP] Fix `pub get` behavior on old lockfile

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#51166]
### Commit(s) to merge

https://github.com/dart-lang/pub/pull/3754

### Target

2.19 stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/280093

### Issue Description

`dart pub get` will upgrade packages instead of preserve locked constraints when `pubspec.lock` is created by pre-2.19.0 sdk.

This happens because we switched from using `pub.dartlang.org` to `pub.dev` as the default hosted url.
And although we normalize them to be the same, normalization was missing in one place, causing the version solver to consider the locked package-version incompatible with the constraint, and therefore unlocking them.

### What is the fix

The fix is to normalize `pub.dartlang.org` to `pub.dev` everywhere we create the internal representation of a package constraint. Therefore `retry` from `pub.dartlang.org` is seen by the solver as related to `retry` from `pub.dev`, and the lock is preserved.

### Why cherry-pick

This is a severe regression in the behavior of `dart pub get`.

It can be confusing and potentially dangerous if unintended version-upgrades of dependencies slip into production. 

Further making this bug unfortunate is that 2.19.0 introduced a sha-256 field for each package in the lockfile. This can make the version upgrades harder to spot in a diff view.

### Risk

medium

### Issue link(s)

https://github.com/flutter/flutter/issues/119091

### Extra Info

(this has not been rolled to the sdk main yet).

**Comment by jonasfj** [comment]
LGTM

**Comment by athomas** [comment]
LGTM

**Comment by vsmenon** [comment]
lgtm
