### ISSUE TITLE
Failures on [co19] Roll co19 to abb96bbca3fc36e6a594967509687431d138e998...Make record positional field getters start at `$1`.

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51168]
There are new test failures on [[co19] Roll co19 to abb96bbca3fc36e6a594967509687431d138e998...Make record positional field getters start at `$1`.](https://github.com/dart-lang/sdk/compare/bee7ab2b32adca681060d151337d3589406fb410~...9fe2529b216e36b5ff8cf03277c70509666f8aa8).

The tests
```
vm/dart/records_allocation_sinking_il_test Crash (expected Pass)
vm/dart/records_return_value_unboxing_il_test Crash (expected Pass)
```
are failing on configurations
```
dartkp-strong-linux-release-x64
dartkp-strong-mac-release-arm64
dartkp-weak-asserts-linux-release-x64
dartkp-weak-asserts-mac-release-arm64
```

@lrhn It looks like your change bee7ab2b32adca681060d151337d3589406fb410 is the culprit, could you please take a look?

**Comment by a-siva** [comment]
Should this be area-front-end instead of area-vm ?

**Comment by alexmarkov** [comment]
Used `area-vm` label because `vm` tests are broken (or probably just not updated properly). It doesn't seem to be related to the front-end.

**Comment by alexmarkov** [comment]
These failures happen because [compare_il](https://github.com/dart-lang/sdk/blob/5577eafdba878d3e3420f0016eba5d96850ceee1/pkg/vm/tool/compare_il#L29) tool uses checked-in Dart SDK to run IL verification (included into tests), and older SDK doesn't understand the recent change of positional record fields starting with $1.

In order to fix these failures, we need to update checked-in SDK to `3.0.0-180.0.dev` or later. I tried bumping sdk_tag in DEPS, but got the following error from `gclient sync`:

```
Errors:
  failed to resolve dart/dart-sdk/linux-amd64@version:3.0.0-180.0.dev (line 65): no such tag
```

@athomas Do you have any suggestions about updating checked-in Dart SDK?

**Comment by athomas** [comment]
@alexmarkov this has to be done by engprod. We don't have a `-180.dev`+ release published, yet. I'll pick this up on Thu/Fri after the next dev release goes out.

**Comment by athomas** [comment]
The roll fixed the tests:
```
CompileTimeError -> Pass (expected Pass)
language/patterns/switch_case_scope_test
Crash -> Pass (expected Pass)
vm/dart/records_allocation_sinking_il_test
vm/dart/records_return_value_unboxing_il_test
```
