### ISSUE TITLE
Please create a cherry pick for the fix to https://github.com/dart-lang/sdk/issues/51087

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#51177]
We'd need an engineer to run with this.

**Comment by kevmoo** [comment]
@scheglov @bwilkerson – would one of you fine folks help here?

**Comment by robbecker-wf** [comment]
It would be very helpful to get fix for https://github.com/dart-lang/sdk/issues/51087 into a 2.19.x release

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/51181

**Comment by kevmoo** [comment]
Closing this out. Tracking with #51181 – thanks @scheglov
