### ISSUE TITLE
Copyright The Chromium authors

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#51184]
In some places in the SDK, there is a header of:

>Copyright 2014 The Chromium Authors. All rights reserved.

For example, in analysis_server mock packages for Flutter.

I think it should be changed in most of the places to be `the Dart project authors` (or `The Flutter Authors` as in some tests).

Also, sometimes `Copyright <year>` and sometimes `Copyright (c) <year>` is used, this should also be unified.

**Comment by bwilkerson** [comment]
> For example, in analysis_server mock packages for Flutter.

That code was copied from the flutter package, so the copyright needs to be the same as it is in the flutter package.

I can't speak to the other changes you suggested.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/280117 for `analysis_server`.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/280168

which handles incorrect year, missing comma or period.

**Comment by devoncarew** [comment]
Thanks for the issue! Closing it as I believe your CL covers the remaining work.
