### ISSUE TITLE
[CP] Issue 51087. Restore canonical URI in PackageBuildFileUriResolver.pathToUri()

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#51181]
### Commit(s) to merge

02e5c9fd1ec419716c2ec6228fa7950e2677fa68

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/280045

### Issue Description

`PackageBuildFileUriResolver.pathToUri()` was not implemented for `PackageBuiltWorkspace`, so `file://` URIs were not restoring canonical URIs (but `package:` did, which is good).

See https://github.com/dart-lang/sdk/issues/51087

### What is the fix

We implemented `PackageBuildFileUriResolver.pathToUri()`.

### Why cherry-pick

This is a small fix, but it is useful for `package:build` users.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51087

**Comment by itsjustkevin** [comment]
@srawlins could you take a look at this cherry-pick when you get a chance?

**Comment by srawlins** [comment]
LGTM
