### ISSUE TITLE
ByteBuffer lengthInBytes does not match Uint8List lengthInBytes

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#51194]
## code

```dart
      final Uint8List bytes = (result[3] as Uint8List?)!;
      expect(bytes.lengthInBytes, bytes.buffer.asByteData().lengthInBytes);
```

## failure:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <4002043>
  Actual: <4002000>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/aaclarke/dev/flutter/dev/integration_tests/wide_gamut_test/integration_test/app_test.dart:41:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

## seen in

Version 3.0.0-154.0.dev

**Comment by lrhn** [comment]
Where was `result[3]` created? If it's a `Uint8List.view` on a larger buffer, then it would be expected that the `ByteData`'s length is greater, since it spans the entire buffer.

Change `bytes.buffer.asByteData()` to `ByteData.sublistView(bytes)`, or to `bytes.buffer.asByteData(bytes.offsetInBytes, bytes.lengthInBytes)`, then you should get the correct result.

So, most likely working as intended.

**Comment by gaaclarke** [comment]
`result[3]` is coming from a flutter platform channel that is sending an NSData value that has size `4002000` on the host side, so it's surprising it thinks it's 4002043 bytes long.

encoder: https://github.com/flutter/engine/blob/main/shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm#L316

decoder:
https://github.com/flutter/flutter/blob/19dfde6989b14bd7dedbc50d7edceef4e59879a4/packages/flutter/lib/src/services/message_codecs.dart#L504

4002043 is probably the payload of the whole message and `result[3]` is just a view into it.  That probably checks out since the other 3 values are 2 ints and a string of about 15 characters length.  As a client of that API, there is no way to know know that the `UInt8List` is a view without debugging the implementation.

This explains the bug I was seeing though so thanks.

IMO this is too easy of a bug to make.  I'd rather have the buffer value of a view to be null or for itself to be a view that matches the region of the UInt8List.  It would probably be very difficult to make this change now.

> (Also (result[3] as Uint8List?)! could just be (result[3] as Uint8List).)

I believe we have a linter that complains of casting away nullability with `as`.

**Comment by lrhn** [comment]
It's an incredibly error-prone API, copied verbatim from JavaScript. It has some good points too, but the index/length on top of a buffer *and* having to go through the buffer to get to another view, trips up people all the time.

We added the `sublistView` constructors to provide a convenient and safe way to go from one view of a slice of a buffer to another. Can't just remove the rest, though.
Try to use those whenever you can, and avoid extracting the buffer.

Other than that
> As a client of that API, there is no way to know know that the `UInt8List` is a view without debugging the implementation.

All typed-data lists are views. Some of them are views that start at offset 0 and has the same length as the buffer, but they are still views. (Internally in the VM that might not be true, but it's always true on the web, and it's the model that we expose. There is no way to detect if something is a view or not.)

You should assume that *any* typed data object you receive can have a start/length different from the entire buffer. The only time you can safely assume that to not be the case is if you allocated the typed-data list yourself.

Does that suck? Heck, yeah. I've made enough of my own mistakes on that account. But it's the API that we have, not the API that we deserve :grin:
