### ISSUE TITLE
`use_super_parameters` false positive for differing nullability

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/sdk#51196]
The following code is flagged as "convert 'foo' to a super parameter":

```
class A {
  A(this.foo);
  String? foo;
}

class B extends A {
  B(String foo) : super(foo);
}
```

But doing that conversion changes the nullability of the argument to `B`'s constructor.

**Comment by asashour** [comment]
May I ask for clarification?

The code is converted to

```dart
B(String super.foo);
```

which seems to be correct.

Tested on `stable` and `dev`.

**Comment by stuartmorgan** [comment]
> The code is converted to
> 
> ```dart
> B(String super.foo);
> ```

Interesting, I had no idea you could put a type on a super parameter. Thanks!

Closing given that (although it would be nice if there were an example of that syntax in the language tour and/or the lint examples).
