### ISSUE TITLE
[cfe] inline last variable assignment

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#51202]
When a variable `x` is assigned, and then used, as in:

```dart
void f(int i) {
  int x = i * 2;
  print(x);
}
```

it causes the generation of:

```
core::int x = i.{core::num::*}(2){(core::num) → core::int};
core::print(x);
```

Would it be better to directly treat it as `print(i * 2)`, or

```
core::print(i.{core::num::*}(2){(core::num) → core::int});
```

Would that save some instructions (and is worth the effort), or this type of optimization is done by later components?

Of course, this may change the order of invocation, and so it should be avoided in some cases, e.g.

```dart
void g() => 1;

void f() {
  int x = g() * 2;
  print(g(), x); // the 'g()' of 'x' must be called before the 'g()' of 'print'
}
```

**Comment by johnniwinther** [comment]
It is the backends' job to do this where applicable.

Also for debugging, we might want `x` to available/visible in the current stack, which wouldn't be possible if the CFE inlined it.
