### ISSUE TITLE
Add JS types to Dart2Wasm, then remove support for the existing JS interop API on Dart2Wasm.

### ISSUE THREAD

**Issue by joshualitt** [dart-lang/sdk#51208]
The existing JS interop API for Dart2Wasm is based on punning Dart types / JS Types. This is somewhat convenient, but also error prone on JS backends, however it is problematic to implement on Dart2Wasm. To bootstrap Dart2Wasm, we approximated the existing API, by copying between JS types and Dart types when they flow across the interop boundary. This is not efficient. We could have investigated proxying objects that flow across the interop boundary, but this would have been invasive, inefficient, and difficult or even impossible on the JS side of the boundary.

To enable efficient JS interop on Dart2Wasm, the Dart web team developed a new API built around concrete static types for JS objects that flow across the interop boundary. In this model, we restrict JS interop APIs to only take / return JS types, and JS types are not punned to their Dart counterparts, i.e. `String is! JSString`. Instead users must explicitly convert between Dart types and JS types.

One point worth noting, this is a substantial change to JS interop, and all existing users of Dart2Wasm's JS interop API also need to support JS interop on JS backends. However, supporting concrete JS types on JS backends is a more complicated issue. While concrete JS types on JS backends will ensure a safer JS interop experience for our users, we have to understand the tradeoffs better before we start changing JS interop for all of our users. Therefore, the MVP for JS types on JS backends will continue to pun Dart types / JS types, and the conversion functions will be optional to use, and free when used with Dart2js. In the longer term, we have some good options to gradually provide the benefits of JS types to our users on JS backends, but that discussion is outside the scope of this bug.

This bug will track a few related efforts:
1) Landing the JS types MVP for all JS backends.
2) Converting existing users of JS interop on Dart2Wasm to the new API.
3) Removing support for the 'type punning' API from Dart2Wasm entirely.

Update as of 11/9:

JS types have landed and the semantics are well-defined and consistent. We plan on deprecating usage of other forms of JS interop on dart2wasm and migrating Flutter to use these new libraries.

**Comment by natebosch** [comment]
> and the conversion functions will be optional to use

Having a difference in required API usage between platforms has cause us problems in the past. Can we consider making the (free) calls mandatory for all platforms instead of only mandatory for wasm?

**Comment by joshualitt** [comment]
@sigmundch @srujzs 

Honestly, I agree 100%. We've talked about exactly what you are proposing as an intermediate step in our journey to a consistent semantics for JS interop across all web backends. This would actually benefit users of JS interop on JS backends because by decoupling Dart types from JS types it would be much harder for them to run into undefined behavior.

However, users of JS interop on JS backends are 'used' to the conflation of Dart types and JS types, and they may not necessarily see the value proposition, especially if they only care about targeting JS in the near term. Our compromise proposal is to add a flag to allow users to opt in to this decoupling, either for type safety or for when they want to ensure compatibility with Dart2Wasm.

I think we're hedging a bit right now because there are so many unknowns, but once we've deployed JS types maybe things will become clearer. That said, I think we are all open to discussion on this issue, and we can certainly prioritize the flag.

**Comment by kevmoo** [comment]
what's the story here @sigmundch @srujzs ?

**Comment by srujzs** [comment]
A lot has changed (naturally). Addressing Joshua's points:

1. This is done. The current implementation is using `@staticInterop` to implement JS types and we're moving to extension types soon here. While the reified type is platform-dependent, the type declarations are uniform across all backends.
2. I think this is mostly done where "existing users" is just Flutter. I'd need to check in with @eyebrowsoffire on whether we only use `dart:js_interop` (and possibly `dart:js_interop_unsafe`) features, or if we're still using `dart:js_util`/`package:js`-specific features. My guess is there's some code that still needs to possibly be migrated.
3. Once 2 is complete, we can announce a breaking change and gut support for `package:js` and `dart:js_util` in dart2wasm.

Re: Nate's question - JS interop checks are uniform across all backends. JS types + a small set of Dart types (mostly just the primitives) are the only allowed types when using `dart:js_interop`. There is no flag to either enable or disable this.

**Comment by kevmoo** [comment]
@srujzs – feel free to update the original comment with status.

If we want to track this work some other way, that's fine, too. As long as it's tracked!

**Comment by srujzs** [comment]
I'm going to go ahead and close this in favor of https://github.com/dart-lang/sdk/issues/54004 to track the deprecation/migration work.
