### ISSUE TITLE
[dart2wasm] Dart List to JS array conversion loses type argument

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51200]
```dart
import 'package:js/js.dart';

@JS()
@anonymous
@staticInterop
class AnonymousJSClass {
  external factory AnonymousJSClass.factory(
      {List<double> zoo = const [1.0, 2.0]});
}

extension AnonymousJSClassExtension on AnonymousJSClass {
  external List<double> zoo;
}

void main() {
  final anonymousJSClass = AnonymousJSClass.factory(zoo: const [1.0]);
  print(anonymousJSClass.zoo);
}
```

This currently works because of #51187. With the bug fixed in https://dart-review.googlesource.com/c/sdk/+/280163, it fails with:

```
Type '_GrowableList<Object?>' is not a subtype of type 'List<double>' in type cast
    at AnonymousJSClassExtension|get#zoo (wasm://wasm/000ab766:wasm-function[800]:0x24167)
    at main (wasm://wasm/000ab766:wasm-function[55]:0x1585b)
    at main tear-off (wasm://wasm/000ab766:wasm-function[57]:0x1586f)
    at _invokeMain (wasm://wasm/000ab766:wasm-function[68]:0x15f9e)
    at Module.invoke (/usr/local/google/home/omersa/dart/sdk/sdk/test.mjs:173:28)
    at main (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js:61:21)
```

The problem is the conversion from Dart List to JS array, in

https://github.com/dart-lang/sdk/blob/e77907f7555803a8b59ab2b1fa174908c6649454/sdk/lib/_internal/wasm/lib/js_helper.dart#L375-L376

which calls 

https://github.com/dart-lang/sdk/blob/e77907f7555803a8b59ab2b1fa174908c6649454/pkg/dart2wasm/lib/js_runtime_blob.dart#L54-L61

Note that this function has no way of knowing the type argument (`T` in `List<T>`) and does not store it anywhere in the JS object. So when I read this array back I get a `List<Object?>` back. (I don't know where exactly this happens yet)

**Comment by joshualitt** [comment]
There might be ways to fix this bug, but we're moving away from this style of JS interop all together. I'm closing this bug because with JS types it won't be possible for us to have this kind of an issue.
