### ISSUE TITLE
Analysis server benchmark doesn't run on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#51207]
I'm trying to set up continuous benchmarking of analysis server on Windows, and one of the benchmarks fails
with a path error on Windows.  The cold-start benchmark works (run analysis-server-cold), but the warm
benchmark fails:

C:\src\dart\sdk>out\ReleaseX64\dart-sdk\bin\dart pkg\analysis_server\benchmark\benchmarks.dart run analysis-server
Running analysis-server 4 times...
analysis-server threw exception: {id: 2, error: {code: INVALID_FILE_PATH_FORMAT, message: Invalid file path format: C:\src\dart\sdk\pkg\analysis_server\lib/src/analysis_server.dart}}

Can you figure out the problem and fix the benchmark?  If you don't have access to a Windows machine, I can help debug.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/280260

Sorry for overtaking the assignment.
