### ISSUE TITLE
`ConvertForEachToForLoop` fixer produces invalid syntax for expression function body with curly braces

### ISSUE THREAD

**Issue by oprypin** [dart-lang/sdk#51205]
Example code (yes, it's very weird, this is a mistakenly written set literal):
```dart
  [1, -2].forEach((x) => {
        print('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed $x')
      });
```
Actual replacement contains a syntax error:
```dart
  for (var x in [1, -2]) {
    {
        print('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed $x')  // Error: Expected ';' after this.
      };
  }
```

**Comment by asashour** [comment]
For info, I guess this is case of `unnecessary set literal`, which is to be tackled soon, to trigger a warning, as reported #50900, but fix could also handle it.

**Comment by bwilkerson** [comment]
Rather than trying to handle the case of a literal set or map without type arguments as the return value value of the closure, I'd rather see the fix just not be offered in that case.

If we do try to fix it, I believe the fix requires adding the type arguments, not in removing the braces.
