### ISSUE TITLE
OSR-deopt thrashing

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51220]
The tests
```
standalone/io/large_file_read_small_file_test
vm/dart/spawn_uri_from_kernel_blob_test
```
are failing on configurations
```
vm-eager-optimization-linux-release-ia32
```

```
/======================================================================================\
| standalone/io/large_file_read_small_file_test broke (Pass -> Timeout, expected Pass) |
\======================================================================================/

--- Command "vm" (took 08:00.000111s):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --random-seed=1524871612 --sound-null-safety -Dtest_runner.configuration=vm-eager-optimization-linux-release-ia32 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone/io/large_file_read_small_file_test.dart

...

--- Re-run this test:
python3 tools/test.py -n vm-eager-optimization-linux-release-ia32 standalone/io/large_file_read_small_file_test
```

--trace-compiler --trace-deoptimization shows repeated OSR and deopt at the same BinarySmiOp or GuardField (depending which test). Usually a deopt would add a deopt reason to the ICData to prevent the optimization from being repeated.

@alexmarkov

**Comment by alexmarkov** [comment]
Small repro:

```

main() {
  for (int i = 0; i < 10000000; ++i) {
    if (i > 2*1024*1024*1024) {
      print(1);
    }
    if (i % 1000000 == 0) {
      print(i);
    }
  }
  print('ok');
}
```

`ApplyICData` pass creates a few `BinarySmiOp` instructions:
```
      v9 <- Constant(#2) T{_Smi}
      v10 <- Constant(#1024) T{_Smi}
...
    v11 <- BinarySmiOp:28(*, v10, v9) T{_Smi}
    v12 <- BinarySmiOp:30(*, v11, v10) T{_Smi}
    v13 <- BinarySmiOp:32(*, v12, v10) T{_Smi}
```
After that, `Canonicalize` pass converts them to
```
      v55 <- Constant(#2097152) T{_Smi}
      v56 <- Constant(#10)
...
    v57 <- BinarySmiOp:32(<<, v55, v56) T{_Smi}
```

Then, `LICM` pass moves this instruction out of the loop and assignes a different deop_id:
```
    v57 <- BinarySmiOp:78(<<, v55, v56) T{_Smi}
```

The new deop_id doesn't have a corresponding descriptor with `kIcCall`  kind, so `AddDeoptReason` is not called for it when deoptimization happens.

Also, `ICData::kHoisted` / `ProhibitsHoistingCheckClass` mechanism which would prevent LICM in case of deopt only works for a few instructions, but not `BinarySmiOp`.

We can probably extend `ICData::kHoisted` / `ProhibitsHoistingCheckClass` mechanism to `BinarySmiOp` which should disable LICM on the first deopt and then disable BinarySmiOp on the 2nd deopt.

@rmacnak-google @mraleph @mkustermann WDYT?

**Comment by mraleph** [comment]
I think proposed solution is fine.
