### ISSUE TITLE
Dart 2.9.0 compiled AOT file fails to run, prompting:VM initialization failedCreate an issue!

### ISSUE THREAD

**Issue by Aaron009** [dart-lang/sdk#51249]
The AOT file I compiled on Mac OS runs on CentOS, and the error is as follows:

`
VM initialization failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts x64 macos no-compressed-pointers null-safety' but the VM has 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts x64 linux no-compressed-pointers null-safety'
`

@nex3 @raggi @ianloic @sethladd 
Help me

**Comment by raggi** [comment]
Your AOT build is platform specific, see the Linux vs macOS entries in the configuration.

Please don't arbitrarily highlight individuals in issues to seek support. I no longer work at Google, or on Fuchsia or with or on Dart.

I suspect you can find assistance in the Flutter community channels, and there may also be communication resources listed on the Dart homepage.

**Comment by mraleph** [comment]
As explained above this is working as intended.

AOT snapshots are OS specific.

**Comment by Aaron009** [comment]
> As explained above this is working as intended.
> 
> AOT snapshots are OS specific.

The files I compiled with AOT before can be run directly on another machine.
