### ISSUE TITLE
"Stack dump aborted because InitialRegisterCheck failed." error

### ISSUE THREAD

**Issue by nopxjs** [dart-lang/sdk#51256]
**when i do anything with dart or flutter in commands its showing me this error:**

===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF70411EBFC
version=2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "windows_x64"
pid=157480, thread=157484, isolate_group=vm-isolate(00000218EC865F10), isolate=vm-isolate(00000218EC869FB0)
os=windows, arch=x64, comp=no, sim=no
isolate_instructions=7ff704016a70, vm_instructions=7ff704016a70
Stack dump aborted because InitialRegisterCheck failed.

**Comment by devoncarew** [comment]
Thanks for the report! Can you also include the output of running `dart info`?

**Comment by mraleph** [comment]
If you get this sort of error with any `dart` / `flutter` command then I would think that something is wrong with either your machine or your installation of Flutter. You can start by purging Flutter installation and reinstalling from scratch. I'd also recommend doing a `memtest` on your machine to check if you RAM is okay.
