### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by mukesh98Digni** [dart-lang/sdk#51259]
## Version information

- `IDEA AI-221.6008.13.2211.9514443`
- `2.19.0`
- `AI-221.6008.13.2211.9514443, JRE 11.0.15+0-b2043.56-8887301x64 JetBrains s.r.o., OS Mac OS X(x86_64) v12.5.1, screens 1920.0x1080.0`

**Comment by devoncarew** [comment]
Closing as this is not actionable.
