### ISSUE TITLE
Cannot use "is" with variable of type "Type"

### ISSUE THREAD

**Issue by bytes7bytes7** [dart-lang/sdk#51258]
Why can I not check a type of a variable with another `Type` variable?
So, I can check a type like that:
```dart
class Foo<T> {
  const Foo(this.value);

  final T value;
}

void main() {
  Foo foo = Foo(1);

  if (foo is Foo<int>) {
    print('int');
  }
}
```
But I cannot do this:
```dart
class Foo<T> {
  const Foo(this.value);

  final T value;
}

void main() {
  Foo foo = Foo(1);
  Type t = Foo<int>;

  if (foo is t) {
    print('int');
  }
}
```
Linter says: The name 't' isn't a type and can't be used in an 'is' expression.
I think there are many situations where we need to check a type with variable.

* Dart SDK Version 2.19.1
* Windows 10 x64

**Comment by utkarsh147-del** [comment]
please assign this issue to me.i want to work on this

**Comment by shrey141102** [comment]
I looked around and found that,
the 'is' keyword in Dart only supports compile-time constant type arguments. The value of the t variable is not known until runtime, so it cannot be used in the is expression.

We can use the 'runtimeType' property of the Object class to dynamically check the runtime type of an object.
```
if (foo.runtimeType == t) 
{
  print('int');
}
```

So, the corrected code would be, I guess
```
class Foo<T> {
  const Foo(this.value);

  final T value;
}

void main() {
  Foo foo = Foo(1);
  Type t = Foo<int>;

  if (foo.runtimeType == t) {
    print('int');
  }
}
```

**Comment by julemand101** [comment]
@shrey141102 
Be aware that checking using `runtimeType` is very different from checking using `is`. Checking using `runtimeType` will only tell if the type of your object is the exact same type your are checking against.

`is` will instead check if your object is compatible with a given class:

An example:
```dart
class A {}
class B extends A {}

void main() {
  B b = B();
  print(b is A); // true
  print(b.runtimeType == A); // false
}
```

**Comment by shrey141102** [comment]
How about using a function that returns a boolean value indicating the result, by checking if the type of a variable with another Type variable is the same or not.

**Comment by lrhn** [comment]
A `Type` object is not a type. It's a token which represents the type's identity, and which can be used for equality checks and not much else outside of the `dart:mirrors` library.

The way to abstract over a type is a type variable, not a normal variable. If you need to do subtype/`is` checks, you need a real type, not a `Type` object.

In general, I recommend avoid using `Type` objects for anything if you are not using `dart:mirrors`.

**Comment by escamoteur** [comment]
@lrhn but isn't that a real weeakness of Dart that it is not possible to dynamically do a subtype check with is? I just ran in an application where I really could have used it.

**Comment by escamoteur** [comment]
Thanks for the elaborated reply.
In my case I wanted to check an array of types against a caught exception to handle the reaction depending on the type.
This already failed by the `Exception` type as the runtime type of a simple Exception is `_Exception` furthermore especially with matching caught Exceptions dynamically type hierarchies are important to filter for a whole group of exceptions.

I finally solved it by passing a list of `errorFilter<T>` closures to the Errorfilter object 

```dart
typedef ErrorFilterPredicate = ErrorReaction? Function(
  Object error,
  StackTrace stackTrace,
);

ErrorReaction? errorFilter<TError>(
  Object error,
  ErrorReaction reaction,
) {
  if (error is TError) {
    return reaction;
  }
  return null;
}

/// Takes a list of predicate functions and returns the first non null
/// [ErrorReaction] or [ErrorReaction.defaultHandler] if no predicate
/// matches.
/// The predicates are called in the order of the list. which means if you want to
/// match against a type hierarchy you have to put the more specific type first.
/// You can define your own predicates or use the [errorFilter] function
/// like this
/// ```dart
/// final filter = PredicatesErrorFilter([
///  errorFilter<ArgumentError>(error, ErrorReaction.throwException),
/// errorFilter<RangeError>(error, ErrorReaction.throwException),
/// errorFilter<Exception>(error, ErrorReaction.globalIfNoLocalHandler),),
/// ]);
/// In contrast to the [TableErrorFilter] this filter can match against the
/// type hierarchy using the [errorFilter] function.
class PredicatesErrorFilter implements ErrorFilter {
  final List<ErrorFilterPredicate> _filters;

  const PredicatesErrorFilter(this._filters);

  @override
  ErrorReaction filter(Object error, StackTrace stackTrace) {
    final reaction = _filters
        .map((filter) => filter(error, stackTrace))
        .firstWhere((element) => element != null, orElse: () => null);
    return reaction ?? ErrorReaction.defaultHandler;
  }
}
````

**Comment by lrhn** [comment]
ACK. That's a perfectly reasonable solution. You need to parameterize by something which can, given an object,
* recognize whether the object has a specific type, and
* provide a reaction for a recognized type.

A function taking an object and returning an optional reaction fits that perfectly.

(I'll just, because I can't help it, suggest to write `filter` as:
```dart
@override
  ErrorReaction filter(Object error, StackTrace stackTrace) {
    for (final filter in _filters) {
      final reaction = filter(error, stackTrace);
      if (reaction != null) return reaction;
    }
    return ErrorReaction.defaultHandler;
  }
```
I just find it more readable without all the run-on iterable methods and extra null checking. 
It's probably more efficient too. :wink:)

**Comment by escamoteur** [comment]
LoL, actually my version was proposed by Copilot :-) you are absolutely right, your version is the better one. I usually like the function style syntax with where and map but in this case it definitely makes it harder to understand what's going on
