### ISSUE TITLE
Core library review Gerrit condition should consider CL creator.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#51263]
The "core-library-review" Gerrit submit requirement on CLs (https://github.com/dart-lang/sdk/wiki/Gerrit-Submit-Requirements#core-library-review) requires a +1 from a member of each of four teams (web/vm/wasm/api).

It should probably consider the author of the CL being one of the approvers as sufficient for that team, so it's not necessary to `+1` your own CL to get approval, something which is strongly frowned upon.

(It definitely shouldn't require _another_ person on the same team to approve the change, since WASM and web both have only one approver. Which is a different issue, because any of those two being unavailable will block all core library commits.)

The condition is:
```
hasfooter:CoreLibraryReviewExempt OR ( label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-api AND label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-vm AND label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-wasm AND label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-web )
```
(The VM team has three approvers, API has two, Web and and WASM only one each.)

I'm in dart-core-library-change-approvers-api, but my own CL is not considered approved by that group.

https://dart-review.googlesource.com/c/sdk/+/280100

Self approving gives warnings about that being disallowed and possibly preventing the CL from being submitted (but does count towards core-library-review).

I can obviously add an exception with a reason of "check is being silly!", but not needing a workaround would be better.

**Comment by mraleph** [comment]
This should improve this: 

```diff
diff --git a/project.config b/project.config
index 095b542696d..7424f5d707b 100644
--- a/project.config
+++ b/project.config
@@ -82,5 +82,5 @@
 [submit-requirement "Core-Library-Review"]
        description = "SDK core library changes need to be approved for each platform or have a 'CoreLibraryReviewExempt: <reason>' footer. See also: https://github.com/dart-lang/sdk/wiki/Gerrit-Submit-Requirements#core-library-review"
        applicableIf = NOT ownerin:bots AND NOT is:pure-revert AND path:\"^sdk/lib/[^_].*\\.dart$\"
-       submittableIf = hasfooter:CoreLibraryReviewExempt OR ( label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-api AND label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-vm AND label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-wasm  AND label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-web )
+       submittableIf = hasfooter:CoreLibraryReviewExempt OR ((label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-api OR ownerin:mdb/dart-core-library-change-approvers-api) AND (label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-vm OR ownerin:mdb/dart-core-library-change-approvers-vm) AND (label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-wasm OR ownerin:mdb/dart-core-library-change-approvers-wasm) AND (label:Code-Review=+1,group=mdb/dart-core-library-change-approvers-web OR ownerin:mdb/dart-core-library-change-approvers-web))
        canOverrideInChildProjects = false
```

Unfortunately I am somewhat struggling to create a CL against `meta/config`.

We are going to send team wide communication once we fix this.

**Comment by sortie** [comment]
Looks like Alex already turned that comment into a CL: https://dart-review.googlesource.com/c/sdk/+/282060

Slava, btw here's how you work with refs/meta/config from the command line (does the UI support submit requirements?):

```sh
git fetch origin refs/meta/config
git checkout -b foo FETCH_HEAD
git commit
# Generate a Change-Id (actually just an I followed by a random unique hash)
echo Change-Id: I$({ git var GIT_COMMITTER_IDENT ; echo "$refhash" ; git show HEAD; } | git hash-object --stdin)
git commit --amend # Put it in the commit message
git push origin foo:refs/for/refs/meta/config # Patchsets also work because of Change-Id
```

Regular devs cannot access refs/meta/config but you can since you're in dart-repo-team.
