### ISSUE TITLE
[CP] [analyzer] Limit the number of plugins-per-context to one

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51272]
### Commit(s) to merge

0ab9f97 and 5fe2f3b

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/281300

### Issue Description

Some users complain on social media that the Dart Analysis Server is slow and consumes a lot of memory. One theory is that these users may be using multiple analyzer plugins and are unaware that they are, or unaware that these multiple analyzer plugins are the culprit. To mitigate this issue, we are limiting the number of analyzer plugins per analysis context to 1.

### What is the fix

The fix is to limit the number of analyzer plugins per analysis context to 1.

### Why cherry-pick

It may be a pressing issue that some users have a poor editing experience due to multiple plugins being run simultaneously. We'd like to fix this before Dart 3.

### Risk

medium

### Issue link(s)

#50981

### Extra Info

I write 'medium' risk, without really knowing what 'low', 'medium', or 'high' mean, for a few reasons:

* This cherry pick required two CLs because the first had issues with the tests
* This cherry pick had merge conflicts that I had to resolve
* I am very very unfamiliar with analyzer plugins. I manually tested the fix, but not with extensive testing. No one in our organization uses analyzer plugins, much less multiple, so this isn't being dogfooded.

Replaces https://github.com/dart-lang/sdk/issues/51062, which was a cherry-pick for beta.

**Comment by itsjustkevin** [comment]
Cherry-pick was approved for the beta branch in https://github.com/dart-lang/sdk/issues/51272.  Marking this as approved due to approvals from the previous issue.

**Comment by srawlins** [comment]
Let me know if there's anything I should do here, or if I should close this.

**Comment by srawlins** [comment]
This was merged. I think this can be closed.
