### ISSUE TITLE
Some doc issues in the `reopen` documentation

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51270]
* "Indicates that the annotated class or mixin declaration intentionally allows subclasses to implement or extend it," - This should also say, "or mix it in", correct?
* "if it's marked interface, or if it is marked sealed and" - 'interface' and 'sealed' must be enclosed in backticks
* "A class or mixin prevents inheritance" - This language is confusing to me, or maybe non-idiomatic. I don't think classes prevent this or that. The spec uses the word "prevent" to indicate that the language prevents such-and-such or a developer may want to prevent this or that. Also, "inheritance" is not found in the spec. What does it mean? A class which "prevents inheritance" cannot be extended? implemented? mixed in? all three?
* "and the subclass is marked base," - 'base' must be enclosed in backticks.
* "it extends or mixes in another class or mixin which requires inheritance." - What does "requires inheritance" mean?
* "or has as an on type" - this seems hard to read. Should 'on' just be in quotes? backticks?

CC @pq @lrhn

**Comment by pq** [comment]
See also: https://github.com/dart-lang/sdk/issues/51551

**Comment by MaryaBelanger** [comment]
I think this was addressed here https://github.com/dart-lang/sdk/commit/4c7e87888d3d1999bc302cc28b74e08c08b655db (https://dart-review.googlesource.com/c/sdk/+/286860)? Or are these issues on-top-of/in-spite-of those changes?

**Comment by pq** [comment]
I *think* these specific issues were addressed.  Let's open new issues for any follow-ups.

(@srawlins: please reopen -- heh -- if you feel otherwise!)

**Comment by srawlins** [comment]
Looks great! Thanks!
