### ISSUE TITLE
[Sealed class] Implement feature in the CFE

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#51280]

**Comment by srawlins** [comment]
CC @kallentu

**Comment by johnniwinther** [comment]
@kallentu Is there anymore work needed for the CFE?

**Comment by kallentu** [comment]
> @kallentu Is there anymore work needed for the CFE?

The only thing I have left to do for sealed for the CFE is some changed behaviour with its interaction with base and final. I guess for the sealed feature on its own, everything is done.
Closing.

**Comment by srawlins** [comment]
Yeah definitely a downside of having separate language features. But it's all just tracking info, 🤷 . Thanks!
