### ISSUE TITLE
[Sealed class] Web debugging support

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#51289]

**Comment by nshahan** [comment]
@annagrin We need to investigate if this new language feature requires any special handling on the debugger side.

**Comment by a-siva** [comment]
On the VM side we implemented the ability to display this attribute for a class here
https://dart-review.googlesource.com/c/sdk/+/285360
The VM service API was modified for this and I presume the dwds would have to be changed to provide the same information.

**Comment by itsjustkevin** [comment]
Friendly ping.

**Comment by vsmenon** [comment]
@annagrin - anything we need to land here?

**Comment by annagrin** [comment]
I don't think so - we don't currently support any of the class attributes for web (we lack symbols). The vm_service update won't break dwds (tested the debugger with it).

@elliette do you know if class attributes are used or shown anywhere in DevTools for web or other platforms?

**Comment by elliette** [comment]
None of these class attributes are being used in DevTools or in DAP currently. This can be follow up for after Dart 3.0.0.

**Comment by leafpetersen** [comment]
Anything to do here, or should we close this out?

**Comment by nshahan** [comment]
At this time there is nothing related to class modifiers shown in the debug tools. I'm closing and we can create a new issue if/when the UI makes use of that information.
