### ISSUE TITLE
[Sealed class] Angular compiler implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#51294]

**Comment by srawlins** [comment]
CC @leonsenft I'm not sure if this has any implications for Angular. Here's the spec: https://github.com/dart-lang/language/blob/master/accepted/future-releases/sealed-types/feature-specification.md

**Comment by leafpetersen** [comment]
@grouma @leonsenft anything you want to track here or can I close this out?

**Comment by leonsenft** [comment]
I can't think of any implications that would be blocking or a concern for us. We'll likely use this feature to seal some framework classes.
