### ISSUE TITLE
[Sealed class] IntelliJ implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#51295]

**Comment by srawlins** [comment]
CC @jwren

**Comment by leafpetersen** [comment]
@jwren anything we should keep this open for or can I close this out?

**Comment by jwren** [comment]
Done, closing out.

For record keeping, this landed in the master branch in the JetBrains repo at https://github.com/JetBrains/intellij-plugins/commit/1390470ea0e1993d00b864b2c14ed0bf6cf76a14
