### ISSUE TITLE
Sending shallow immutable lists across isolates may result in observable side-effects across isolates

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#51302]
User was writing [blog post](https://onepub.dev/Blog?id=xpxpsdavuh) about isolates, which mentions that sending `List.unmodifiable()`s across isolates is very fast.

This is a bug:
```dart
import 'dart:isolate';

class C { 
  int field = 0;
}

void main() async {
  final original = C();

  final rp = ReceivePort();
  rp.sendPort.send(List<C>.unmodifiable([original]));
  final copy = ((await rp.first) as List)[0] as C;

  copy.field = 1;
  print(original.field);
}
```

(Credits to @mraleph for reporting offline)

**Comment by bsutton** [comment]
So I believe that I'm that blog writer.

My understanding is that the bug is;  immutable memory arrives in the spawned isolate as mutable.

I'm hoping the bug fix is that it arrives as immutable rather than removing the significant performance boost that sharing immutable memory between isolates delivers.

**Comment by julemand101** [comment]
As far as I see it, it would be a breaking change if objects inside `List.unmodifiable` becomes immutable when sending over to an Isolate or when added to a unmodifiable list. The objects might not have been designed to become immutable in the first place which would break any usage of the objects after they become immutable. But it would also be a troublesome since the objects inside the unmodifiable list might be part of another object in the same message.

**Comment by bsutton** [comment]
> The objects might not have been designed to become immutable in the first place which would break any usage of the objects after they become immutable. 

Could support be limited to lists of immutable objects (e.g. strings).

This is a highly useful use case and obviates the 2nd  problem you mentioned.

**Comment by julemand101** [comment]
> Could support be limited to lists of immutable objects (e.g. strings).

There have been some discussion about being able to have a general concept of immutable objects in Dart and be able to send such cheaply though SendPort: https://github.com/dart-lang/sdk/issues/49587#issuecomment-1204560576

But yeah, if nothing else, it would be nice if we can have a quick way to transfer basic types.

**Comment by mkustermann** [comment]
> So I believe that I'm that blog writer.

@bsutton  It's just wonderful you automatically found your way here :+1: (I intended on trying to find out the author and reach out, but that's better)

> I'm hoping the bug fix is that it arrives as immutable rather than removing the significant performance boost that sharing immutable memory between isolates delivers.

The root cause is that `<imm-foo> = List.unmodifiable(<foo>)` gives a shallow immutable list back: The returned `<imm-foo>` list cannot be modified, but all objects `<imm-foo>` references can be arbitrary mutable objects. In the above example an instance of `C`.

Sending `SendPort.send(<imm-foo>)` will give something to the receiver. Both sender and receiver will have an immutable list, but if they share it, then they also share everything transitively referenced from such a shallow immutable list. We cannot allow the transitively referenced things to contain mutable objects. So if the transitive graph contains mutable objects, we'll have to copy even the `<imm-foo>` list itself (as well as what it references).

I plan on first fixing this unintended bug in [cl/281421](https://dart-review.googlesource.com/c/sdk/+/281421) and then as an optimization, let us determine at construction time of `List.unmodifiable()` whether it's transitively immutable, and if so, mark it as transitively immutable, so any sent via ports will share it, see [cl/281424](https://dart-review.googlesource.com/c/sdk/+/281424). The ladder would e.g. share `List.immutable([1, 'foo', List.immutable([true])])` and the `SendPort.send` implementation can see that by simply checking a bit on the `<imm-foo>`, so it's fast.

**Comment by gnprice** [comment]
As a cross-reference for anyone finding this thread:

> I plan on first fixing this unintended bug in [cl/281421](https://dart-review.googlesource.com/c/sdk/+/281421) and then as an optimization, let us determine at construction time of `List.unmodifiable()` whether it's transitively immutable, and if so, mark it as transitively immutable, so any sent via ports will share it

That work is now tracked in #51334 .
