### ISSUE TITLE
patterns, analyzer reports dead code after first relational pattern

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51308]
Dart SDK version: 3.0.0-edge.3d01b0aac3b5f143a2ccbefa8f9339272e1591a4 (be) (Tue Feb 7 18:24:54 2023 +0000) on "macos_x64"

This code is from the patterns spec.

```dart
String asciiCharType(int char) {
  const space = 32;
  const zero = 48;
  const nine = 57;

  // Relational pattern
  return switch(char) {
    == space => 'space', // Analyzer reports all below is dead code. 6Feb23
    < space => 'control',
    > space && < zero => 'punctuation',
    >= zero && <= nine => 'digit'
    // Etc...
  };
}
```

**Comment by stevemessick** [comment]
cc @scheglov 

My comment is slightly off. Looking closely, the gray text starts after `<`.

**Comment by asashour** [comment]
Could you please verify with an even recent revision? I am not able to reproduced it with 63b5f5d4b1c53ce5818fa2648492869bdaf104bf.

**Comment by stevemessick** [comment]
After sync and build the problem disappeared. Closing.

**Comment by scheglov** [comment]
I believe Paul implemented support for relational patterns in flow analysis, so this fixed this issue.
I saw a similar fix for `co19/` tests.
