### ISSUE TITLE
Record types being produced in pre-3.0 code when the experiment is enabled

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#51323]
Create a file containing the following in a package in which both the `records` and `patterns` experiments are enabled:

```dart
// @dart=2.12
const a = 1;
const b = 2;
void f(int i) {
  switch (i) {
    case const (a + b):
      break;
  }
}
```

The code should be valid, but the parenthesized expression is interpreted as a record and a diagnostic is produced because the type of the `case` expression doesn't match the type of the `switch` expression.

**Comment by lrhn** [comment]
Even in 3.0 code, `(a + b)` is not a record expression, it needs to be `(a + b,)`, so something is wrong.

Most likely reason is that `const (a + b)` was not valid expression syntax pre 3.0 to begin with, so it falls into a path that has nowhere else to go than parsing as a record.

**Comment by bwilkerson** [comment]
That's quite possible. But I do think it will be confusing to users to see a message saying that the type `(int)` isn't assignable to the type `int` if they haven't updated to 3.0 because they might not even recognize that `(int)` is a record type. I think we want to produce the same parse errors we would have before record support was implemented.

**Comment by asashour** [comment]
> The code should be valid.

Is the code valid for only Dart 3, or is it valid for version 2.12 as well? I couldn't reproduce a case that passes with version 2.12.

The reason I ask is because whether CFE should also report that compile-time error for the example in OP, or not.

**Comment by bwilkerson** [comment]
The code is invalid in all versions. The problem is that we're producing a `RecordLiteral` in a context where records shouldn't be able to exist.

**Comment by lrhn** [comment]
The code should be valid for Dart 3.0, the `const (a + b)` is a constant pattern containing a constant expression.

(See [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#constant-pattern), grammar production: `constPattern ::= .... 'const' '(' expression ')';`.)

**Comment by srawlins** [comment]
@bwilkerson is this still an open valid bug? It's P1, and Dart 3 is shipping soon :)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/305142
