### ISSUE TITLE
Flaky test on Windows buildbot

### ISSUE THREAD

**Issue by iposva-google** [dart-lang/sdk#5133]
The tests vm/cc/Sleep and vm/cc/Monitor are flaky on the Windows debug buildbot. The frequency of flakiness increased so we should investigate that buildbot setup and load.

**Comment by iposva-google** [comment]
Stale.

**Comment by peter-ahe-google** [comment]
I've skipped the test. At least the following alternatives are available:

- Wrap the test in a loop and report a failure only if the test is more flaky than expected.
- Move the test to an FYI builder.
- Delete the test.

Marking it as flaky in a status file serves no purpose.

**Comment by ricowind** [comment]
There are no current VM people cc'ed on this
cc @a-siva  for triage

**Comment by peter-ahe-google** [comment]
Thank you!
