### ISSUE TITLE
patterns, problem with method call on result of switch expression

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51335]
This code breaks the analyzer:
```dart
void f15(int n, Object a, Object b, Object c) {
  var x = switch (n) {
    1 => a,
    2 => b,
    _ => c
  }.toString();
}
```
Removing `.toString()` restores functionality. There's nothing useful in the IntelliJ log. The main clue that there is a problem is the function name `f15` isn't highlighted.

cc @scheglov

**Comment by srawlins** [comment]
What do you mean by "breaks the analyzer"?

**Comment by stevemessick** [comment]
The analyzer stops working. No syntax highlighting, completions, etc. Also, no errors reported.

**Comment by scheglov** [comment]
Usually (as in this case) this is caused by an exception thrown inside the analyzer.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/281946
