### ISSUE TITLE
Incorrect hint on local variable declaration

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51336]
This local variable declaration causes a problem for the analyzer.
```dart
  var fns = <Function()>[];
```
The analyzer says:
> info: The return type of ' Function()' cannot be inferred. (inference_failure_on_function_return_type at [experiments] lib/patterns.dart:239)

I checked with @munificent and was assured that the code is correct. It comes from the patterns spec.

**Comment by srawlins** [comment]
The return type of the type cannot be inferred, so should be specified. See the last example at https://github.com/dart-lang/language/blob/master/resources/type-system/strict-inference.md#function-return-types.

`inference_failure_on_function_return_type` should only be reported when [`strict-inference`](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks) is enabled. Can you tell if it is enabled?

**Comment by stevemessick** [comment]
I had forgotten I enabled that option. Closing. Thanks @srawlins !
