### ISSUE TITLE
Failures on [deps] rev markdown and dartdoc

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51348]
There are new test failures on [[deps] rev markdown and dartdoc](https://github.com/dart-lang/sdk/commit/1fc33f7c637ad2162561a1071b09338aa7c58b0f).

The tests
```
pkg/dds/test/dap/integration/dart_test_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

From log:
```
00:00 [32m+0[0m: dart test can run without debugging[0m

Event "dart.debuggerUris" has taken longer than 10s

00:36 [32m+0[0m[31m -1[0m: dart test can run without debugging [1m[31m[E][0m[0m

  Expected: [
              '✓ group 1 passing test',
              'Expected: <2>',
              '  Actual: <1>',
              <(a string starting with 'package:test_api' and a string ending with 'expect')>,
              <a string ending with 'main.<fn>.<fn>'>,
              '✖ group 1 failing test',
              '',
              'Exited (1).'
            ]
    Actual: [
              'Failed to load "b/s/w/ir/x/t/dart-sdk-dap-test52714d33/app74a4ed2/test_file.dart": Does not exist.',
              'package:test_core/src/runner/load_suite.dart 134:26    new LoadSuite.forLoadException',
              'package:test_core/src/runner.dart 268:21               Runner._loadSuites.<fn>',
              'dart:_internal/iterable.dart 393:20                    MappedIterator.moveNext',
              'dart:core/iterable.dart 325:23                         Iterable.forEach',
              'package:async/src/stream_group.dart 95:13              StreamGroup.merge',
              'package:test_core/src/runner.dart 258:24               Runner._loadSuites',
              'package:test_core/src/runner.dart 117:22               Runner.run.<fn>',
              'dart:async/zone.dart 1398:13                           _rootRun',
              'dart:async/zone.dart 1300:19                           _CustomZone.run',
              'dart:async/zone.dart 1803:10                           _runZoned',
              'dart:async/zone.dart 1746:10                           runZoned',
              'package:test_core/src/runner/configuration.dart 878:7  Configuration.asCurrent',
              'package:test_core/src/runner.dart 110:33               Runner.run',
              'package:test_core/src/executable.dart 149:30           _execute',
              'package:test_core/src/executable.dart 38:9             main',
              'package:test/src/executable.dart 26:20                 main',
              'dart:isolate-patch/isolate_patch.dart 295:33           _delayEntrypointInvocation.<fn>',
              'dart:isolate-patch/isolate_patch.dart 192:26           _RawReceivePort._handleMessage',
              '✖ loading b/s/w/ir/x/t/dart-sdk-dap-test52714d33/app74a4ed2/test_file.dart',
              '',
              'Exited (1).'
            ]
     Which: at location [0] is 'Failed to load "b/s/w/ir/x/t/dart-sdk-dap-test52714d33/app74a4ed2/test_file.dart": Does not exist.' instead of '✓ group 1 passing test'
  

  package:test_api/src/expect/expect.dart 134:31         fail
  package:test_api/src/expect/expect.dart 129:3          _expect
  package:test_api/src/expect/expect.dart 46:3           expect
  pkg\dds\test\dap\integration\test_support.dart 53:3    expectLines
  pkg\dds\test\dap\integration\dart_test_test.dart 68:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9       Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7       Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9        Invoker._waitForOutstandingCallbacks.<fn>
 ```

Full log: https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/23656/pkg/dds/test/dap/integration/dart_test_test

/cc @bkonyi

**Comment by DanTup** [comment]
Taking a look - I'd be surprised if it was the markdown/dartdoc bump that broke this, but it looks like a little earlier `package:test` was bumped (https://github.com/dart-lang/sdk/commit/059634a18ddc3b6b691b5f870550741de3b22209) and I think that might have included some changes related to passing test scripts on Windows (@jakemac53 fyi - I'll ping you if I have more info if I can repro this on my PC).

**Comment by DanTup** [comment]
I can repro from the command line on Windows when passing a full path to a test file:

![image](https://user-images.githubusercontent.com/1078012/217863523-305745e1-e893-496f-8ccf-d61881814102.png)

```
C:\Users\danny\AppData\Local\Temp\dart-sdk-dap-test35f7d620\app5a7bb8e7>dir
// snip
09/02/2023  15:44               248 test_file.dart
//snip
```

```
C:\Users\danny\AppData\Local\Temp\dart-sdk-dap-test35f7d620\app5a7bb8e7>dart test "C:\Users\danny\AppData\Local\Temp\dart-sdk-dap-test35f7d620\app5a7bb8e7\test_file.dart"
00:00 +0 -1: loading Users/danny/AppData/Local/Temp/dart-sdk-dap-test35f7d620/app5a7bb8e7/test_file.dart [E]
  Failed to load "Users/danny/AppData/Local/Temp/dart-sdk-dap-test35f7d620/app5a7bb8e7/test_file.dart": Does not exist.

To run this test again: dart test Users/danny/AppData/Local/Temp/dart-sdk-dap-test35f7d620/app5a7bb8e7/test_file.dart -p vm --plain-name "loading Users/danny/AppData/Local/Temp/dart-sdk-dap-test35f7d620/app5a7bb8e7/test_file.dart"
00:00 +0 -1: Some tests failed.
```

**Comment by DanTup** [comment]
I've opened a PR at https://github.com/dart-lang/test/pull/1923 which seems to fix the problem in my testing on Windows.

**Comment by DanTup** [comment]
I'm expecting this to be fixed by 938b2fc5d1e0cd4afb7f421074ca708ca01f5c31.

**Comment by DanTup** [comment]
@alexmarkov can you tell if this is fixed? I'm looking at https://ci.chromium.org/p/dart/g/alt/console but can't see the red bot I thought this had caused (maybe it's an approved failure somewhere?).

Also, the commit noted above appears to have broken the "sdk/g3" bot - however I don't have access to see the details. Can you see whether that failure may be related?

**Comment by alexmarkov** [comment]
The test `pkg/dds/test/dap/integration/dart_test_test` currently passes: https://dart-ci.firebaseapp.com/current_results/#/filter=pkg/dds/test/dap/integration/dart_test_test&showAll

It started passing since https://github.com/dart-lang/sdk/commit/8157a652471767206a9fcdb05d04f65fba60a544, so maybe it is just flaky.

**Comment by alexmarkov** [comment]
It looks like the output of passing tests is not saved (usually, if test passes there's no useful output anyway).

@athomas @jakemac53 Is there any caching of DEPS or maybe compiled tests in `package:test` which may result in this kind of flaky behavior? Maybe such cache is not cleaned on every build on our bots or rarely cleaned.

**Comment by jakemac53** [comment]
package:test caches incremental dill files for the compiled tests in the `.dart_tool/test` directory but I don't think that would be at play here.

**Comment by alexmarkov** [comment]
@athomas Is it possible that sometimes contents of `.dart_tool/test` directory is not cleared and reused between different builds on the same bot? That would explain why this error appears and disappears on seemingly unrelated commits.

**Comment by jakemac53** [comment]
Even if that was the case I don't believe the error listed above would have anything to do with it. We don't cache failures, only successful incremental dill files, and we gracefully handle their existence (or not).

**Comment by jakemac53** [comment]
Is this test still failing at all? The only failure mentioned so far should have been something that would consistently fail. If we see a new failure I would like to be able to look at the logs.

**Comment by alexmarkov** [comment]
What if we cached successful compilation of the test and then `package:test` was upgraded to a version with a bug, while tests were not changed. Running tests would still reuse cached dill file and would be still be successful if running on particular bots.

Currently test passes. The strange thing is that it started failing on unrelated commit and then suddenly started passing even before the fix in `package:test` was rolled into Dart SDK.

Maybe there is another reason for this: is it possible for this test to pull current version of `package:test` from pub, and not from Dart SDK DEPS? That would explain this behavior - failures were following published versions of `package:test` instead of Dart SDK changes, so test started failing when new version of `package:test` was published and stopped failing when a version with the fix was published. If that's the case, we should change this test to be more hermetic.

**Comment by DanTup** [comment]
Aaah yes, this is it. The test is just running `dart test` and I had assumed that was using a version of `package:test` rolled into the SDK (I think I was mislead by the issue occuring on a `DEPS` update and didn't properly question why it), but ofc it needs to use the version that matches the users project constraints :-)

This explains both the delayed failure (it didn't happen after the roll of `package:test` in `DEPS`, it was when you pushed to Pub) and the fix was early (you published to Pub before `DEPs` updated).

So all is good, and sorry for the confusion :-)
