### ISSUE TITLE
[dart2wasm] Support `switch` in `sync*` functions

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#51342]
The `sync*` implementation in dart2wasm currently does not support `switch` statements.

To implement these via the `sync*` CFG, each `case` needs a target label that the `switch` can jump to and which can also be jumped to by `continue` statements. The implementations does not need the workarounds for backwards `continue` that the normal `switch` implementation has, since this workaround is essentially already there in the form of the switch-in-loop implementation of the `sync*` CFG.

**Comment by osa1** [comment]
Implemented in https://dart-review.googlesource.com/c/sdk/+/292740.

**Comment by osa1** [comment]
Just to update: we implemented `switch` handling in async functions using most of the same code in the CL linked above. We should find a way to either reuse the code, or in the worst case copy-paste-modify the switch handling in `AsyncCodeGenerator` to `SyncStarCodeGenerator`.

**Comment by osa1** [comment]
I'm fixing the remaining `sync*` missing features and issues in https://dart-review.googlesource.com/c/sdk/+/366663.
