### ISSUE TITLE
using `@pragma("vm:external-name", nativeFunction)` functions in client code

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#51359]
Hello,

I wanted to use
```dart
@pragma("vm:external-name", "StringBase_createFromCodePoints")
external static String _createFromCodePoints(List<int> codePoints, int start, int end);
```
[source](https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/vm/lib/string_patch.dart#L252)

in my code, without going through the `stdlib` route, but im getting an error, "native function not found",

The reason is performance, 

I take complete responsibility of my code, and undefined behavior, but please let us,

thanks

**Comment by lrhn** [comment]
You should use `dart:ffi` for that.

VM external functions only work for functions declared inside the VM's source code

**Comment by mraleph** [comment]
@gintominto5329 it would help if you would explain what your performance issue is and how accessing this mechanism helps you. Are you specifically asking to get access to `StringBase_createFromCodePoints` or just some C function? If it is the latter then FFI is indeed the answer - like @lrhn suggests.
