### ISSUE TITLE
[dart2wasm] Incorrect bounds/covariance check

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51358]
```dart
import "expect.dart";

class A<T> {
  boundCheck<X extends T>() {}
}

A<Object?> getA<T>() => int.parse("1") == 1 ? A<T>() : A<Never>();

void checkTypeParameterBound<T, Bound>() {
  getA<Bound>().boundCheck<T>();
}

void main() {
  Expect.throwsTypeError(() => checkTypeParameterBound<Object, String>());
}
```

`checkTypeParameterBound` throws a type error in JIT, doesn't throw with dart2wasm.

**Comment by osa1** [comment]
The problem is we don't generate type checks for *type parameters*, we only generate them for value parameters. Here's the code for `boundCheck` in the repro:

```wast
 (func $A.boundCheck (type $type$346) (param $0 (ref $type$348)) (param $1 (ref $type$4)) (result (ref null $type$48))
  (ref.null none))
```

**Comment by osa1** [comment]
I've added the type check in https://dart-review.googlesource.com/c/sdk/+/282660, but it currently fails with a null deref in runtime when the type parameter bound is something like `X extends T<X>`, e.g. the type being checked is used in the bound. Example:

```dart
class C<T extends Comparable<T>> {}

void main() {
  C<String>();
}
```

The Wasm field for `T` in this class is nullable, and it's value is null in the constructor for `C` when we generate the type check.

@askeksa-google do you know why we generate nullable Wasm fields for class type parameters?

**Comment by askeksa-google** [comment]
> The Wasm field for `T` in this class is nullable, and it's value is null in the constructor for `C` when we generate the type check.

This seems to be an ordering/scoping issue. I see two ways we could fix this:
1. Assign the type arguments to the type parameter fields before performing the type parameter bound checks.
2. Change the scoping of type variables such that inside a constructor body, the class type parameters refer to the type arguments given to the constructor, rather than the type parameter fields.
