### ISSUE TITLE
Nullability of non-exhaustive switch expression

### ISSUE THREAD

**Issue by Mike278** [dart-lang/sdk#51364]
Looks like there's been some recent progress on pattern type inference, so I was playing around with `3.0.0-edge.41d6db8ce587910e32cacf848fd388aee1a830a7` and noticed that non-exhaustive switch expressions can be assigned to a non-nullable type. 

For example:
```dart
void main() {
  final alwaysTrue = DateTime.now().millisecondsSinceEpoch > 1;
  final String x = switch (alwaysTrue) { false => 'hello' };
  assert(x.length == 5); // runtime error: The getter 'length' was called on null.
}
```

Probably just not implemented yet, but wanted to flag it just in case!

**Comment by lrhn** [comment]
Just not implemented. Non-exhaustive switch expressions are simply not allowed, but I'm guessing the implementation of the exhaustion-checking algorithm isn't done yet.

**Comment by Mike278** [comment]
Ah yep, just found #51275
