### ISSUE TITLE
[dart2js] Use `instanceof` in more cases

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#51366]
dart2js can use `instanceof` for `is` tests, for example

```dart
   o is StringBuffer
```
compiles to
```js
  o instanceof A.StringBuffer
```

We miss the opportunity when there is an interface with a single implementation tree
```dart
abstract class Interface {}
class Implementation implements Interface {}

   o is Interface  // could be `o instanceof A.Implementation`.
```

All the parts exists - similar logic to what is used in the TypeMask abstract value domain to reduce Subtype(Interface) to Sublcass(Implementation).
```dart
    final lub = closedWorld.getLubOfInstantiatedSubtypes(testedClass);
    if (lub != null && closedWorld.classHierarchy.hasOnlySubclasses(lub)) {
      // may compile `o is testedClass`  -->  `o instanceof lub`
    }
```
There would need to be minor refactoring to return both the decision to use `instanceof` and the appropriate class to test.

**Comment by eernstg** [comment]
The upcoming class modifier feature could be relevant to this topic.

A class `B` marked `base` would be a good starting point: That kind of class will typically have a subtype graph which is a tree of subclasses (no `implements` edges).

It is possible to have `class C implements B {}` when `B` and `C` are declared in the same library, but it shouldn't be hard to filter out the cases where that happens. That done, for classes in any other library, it is then impossible to be a subtype of `B` without also being a subclass of `B`.

We could have `implements` edges in the superinterface graph from a subclass of `B` to some other type (which could be unrelated to `B`, or it could be another subclass of `B`). I don't know if this will destroy the potential for this optimization.
