### ISSUE TITLE
[DDC] Uncaught Error: type arguments should not be null: T 

### ISSUE THREAD

**Issue by giggitygoat** [dart-lang/sdk#51360]
If the following code is run with the DDC it will fail.

```
class A<T extends C> extends B<A> {}

abstract class B<E extends B<E>> {}

class C {}
```
The error given: Uncaught Error: type arguments should not be null: T 

If I change the order it works.

```
class C {}

abstract class B<E extends B<E>> {}

class A<T extends C> extends B<A> {}
```

```
$flutter --version 
Flutter 3.7.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 32fb2f948e (2 days ago) • 2023-02-08 07:30:10 -0800
Engine • revision f40b73f8a4
Tools • Dart 2.19.2 • DevTools 2.20.1
```

**Comment by nshahan** [comment]
@giggitygoat Thanks for the reproduction. To help me determine the priority can you describe where you discovered the issue? Is this pattern in a published package you don't own or is the reordering work-around enough to unblock you for now?

**Comment by giggitygoat** [comment]
@nshahan I discovered it whilst importing a private flutter package project (the culprit) in a different project where I was running debug mode for browser. I own the package and potentially could try reordering some stuff to get it to work.

**Comment by giggitygoat** [comment]
@nshahan I am unable to reproduce the same bug on dart version 3.4.0-edge.74672eca0a32dfa72122fcc94d88a959055e5d98

**Comment by nshahan** [comment]
Thanks for the confirmation! The ordering issue that appeared in this bug is now avoided by the switch to the new runtime type representation in DDC.
