### ISSUE TITLE
Void pointer argument between Dart and C

### ISSUE THREAD

**Issue by mihok** [dart-lang/sdk#51375]
Im not sure if this is the right place to ask, but I saw a few other type-questions and thought I would give it a shot. I'm currently working on making the C implementation of BLAKE3 compatible with Dart. BLAKE3 has the following function:

```c
void blake3_hasher_update(blake3_hasher *self, const void *input,
                          size_t input_len) {
    ...
}
```

Which is converted by FFIGEN into Dart:

```dart
void blake3_hasher_update(
    ffi.Pointer<blake3_hasher> self,
    ffi.Pointer<ffi.Void> input,
    int input_len,
  ) {
    ...
}
```

But I'm unsure how to call this or even provide input data to this function?

**Comment by mraleph** [comment]
StackOverflow is a better place to ask questions. 

Make sure to read https://dart.dev/guides/libraries/c-interop before you jump into using `ffigen`. This should give you some idea of how to `dart:ffi` works. 

> But I'm unsure how to call this or even provide input data to this function?
 
Do you understand how you would call it in C? Do you have experience with C? In Dart you would call it in a similar way as you would do it in C, i.e. you need to allocate `blake3_hasher` object somewhere (e.g. via `malloc`), initialise it via `blake3_hasher_init`, then you need to allocate input buffer somewhere (e.g. via `malloc`), copy data into that buffer and then call `blake3_hasher_update` with hasher and buffer.

**Comment by mihok** [comment]
Thanks @mraleph !
