### ISSUE TITLE
2 if condition is never executed

### ISSUE THREAD

**Issue by danwirele** [dart-lang/sdk#51372]
When I using 2 if block's, the second one is not executed.
When I use switch case or else if construction the code executes successfully.
Code example:
```dart
  FutureOr<void> _onSwitchPageSignupEvent(
    SwitchPageSignupEvent event,
    Emitter<SignupState> emit,
  ) {
    if (state.runtimeType == RegistrationSignupState) {
      emit(LoginSignupState());
    }
    if (state.runtimeType == LoginSignupState) {
      emit(RegistrationSignupState());
    }
  }
```
In this example second one if will not be executed.
```dart
  FutureOr<void> _onSwitchPageSignupEvent(
    SwitchPageSignupEvent event,
    Emitter<SignupState> emit,
  ) {
    if (state.runtimeType == RegistrationSignupState) {
      emit(LoginSignupState());
    } else if (state.runtimeType == LoginSignupState) {
      emit(RegistrationSignupState());
    }
  }
```
This code executes correctly.

**Comment by danwirele** [comment]
Flutter version 3.7.0 on channel stable
Dart version 2.19.0
Error was found in debugging mode under the web

**Comment by sigmundch** [comment]
Thanks for filing this issue.

We will need additional context to be able to isolate the problenm. Could you:

* Send us a full example that we can compile and run locally? Include what command options you are using as well. One reason this helps is that flutter on the web uses 2 different compilers depending on the mode. If you run `flutter run -d chrome` you get one compiler, but if you run `flutter build -d chrome` you get another.

* If your code is private or is hard to create a repro. Could you share more context around this if tests? For example, what is the declared type of `state`?

**Comment by danwirele** [comment]
I present the repository with a presentation of the problem `https://github.com/pocket-red-fox/twoifcond.git`

**Comment by danwirele** [comment]
Tests were also builded under linux, the result is same

**Comment by sigmundch** [comment]
@danwirele thanks for sharing all the details. Turns out this is actually working as intended. 

It so happens that `state` in your code is a field which is being updated when you call `emit`. As a result, the `state` you read on the second condition is different than the state you read in the previous one.

Here is a simplified program without flutter that can run on dartpad or the command-line Dart VM:

```dart
import 'dart:async';
import 'package:bloc/bloc.dart';

abstract class HomeEvent {}
class SwitchHomeEvent extends HomeEvent {}

abstract class HomeState {}
class FirstHomeState extends HomeState {}
class SecondHomeState extends HomeState {}

abstract class HomeBloc extends Bloc<HomeEvent, HomeState> {
  HomeBloc() : super(FirstHomeState()) {
    on<SwitchHomeEvent>(_onSwitchHomeEvent);
  }

  FutureOr<void> _onSwitchHomeEvent(
    SwitchHomeEvent event,
    Emitter<HomeState> emit,
  );
}

class IfElse extends HomeBloc {
  @override
  FutureOr<void> _onSwitchHomeEvent(
    SwitchHomeEvent event,
    Emitter<HomeState> emit,
  ) {
    if (state.runtimeType == FirstHomeState) {
      print("v2:condition 1");
      emit(SecondHomeState());
    } else if if (state.runtimeType == SecondHomeState) {
      print("v1:condition 2");
      emit(FirstHomeState());
    }
  }
}

class IfNoElse extends HomeBloc {
  @override
  FutureOr<void> _onSwitchHomeEvent(
    SwitchHomeEvent event,
    Emitter<HomeState> emit,
  ) {
    if (state.runtimeType == FirstHomeState) {
      print("v2:condition 1");
      emit(SecondHomeState());
    }
    if (state.runtimeType == SecondHomeState) {
      print("v2:condition 2");
      emit(FirstHomeState());
    }
  }
}

class IfLocal extends HomeBloc {
  @override
  FutureOr<void> _onSwitchHomeEvent(
    SwitchHomeEvent event,
    Emitter<HomeState> emit,
  ) {
    final stateLocal = state;
    if (stateLocal.runtimeType == FirstHomeState) {
      print("v3:condition 1");
      emit(SecondHomeState());
    }
    if (stateLocal.runtimeType == SecondHomeState) {
      print("v3:condition 2");
      emit(FirstHomeState());
    }
  }
}

void main() async {
  for (HomeBloc bloc in [ IfElse(), IfNoElse(), IfLocal()]) {
    print('$bloc');
    print('first event');
    bloc.add(SwitchHomeEvent());
    await Future((){});
    print('second event');
    bloc.add(SwitchHomeEvent());
    await Future((){});
  }
}
```

This prints:
```
Instance of 'IfElse'
first event
v2:condition 1
second event
v1:condition 2
Instance of 'IfNoElse'
first event
v2:condition 1
v2:condition 2
second event
v2:condition 1
v2:condition 2
Instance of 'IfLocal'
first event
v3:condition 1
second event
v3:condition 2
```

`IfElse` is like your `Normal` example, `IfNoElse` is like the `Exception` example you showed (prints on both branches instead of one). `IfLocal` is an alternative to `IfElse` an shows the same behavior. It illustrate that the problem comes from reading the `state` field, which has been mutated after the first condition executed.
