### ISSUE TITLE
[vm/ffi]: Passing opaque pointer as Pointer<Void> and retrieve it later

### ISSUE THREAD

**Issue by buraktabn** [dart-lang/sdk#51388]
I've created bindings for [librdkafka](https://github.com/confluentinc/librdkafka) using ffigen and building a wrapper library on top of it. There's a C function that takes [`void *opaque`](https://github.com/confluentinc/librdkafka/blob/292d2a66b9921b783f08147807992e603c7af059/src/rdkafka.h#L2439) and I can retrieve that opaque pointer in [here](https://github.com/confluentinc/librdkafka/blob/292d2a66b9921b783f08147807992e603c7af059/src/rdkafka.h#L2446).

I can use this opaque pointer to pass the context and retrieve it later to use on callbacks.

For example I have to following abstract class that defines the context
```dart
abstract class ClientContext {
  void log(RDKafkaLogLevel level, String fac, String message) {
    // Handle logs
  }

  void stats(Statistics statistics) {
    info("Client stats: $statistics");
  }

  void statsRaw(List<int> stats);

  void error(KafkaError error, String reason) {
    error("$error $reason");
  }
}
```
When creating a client I could do something like
```dart
void rd_kafka_conf_set_opaque(
  ffi.Pointer<rd_kafka_conf_t> conf,
  ffi.Pointer<ffi.Void> opaque,
) {
  return _rd_kafka_conf_set_opaque(
    conf,
    opaque,
  );
}
...
final callback = malloc<Void>();
kafkaFFI
  ..rd_kafka_conf_set_opaque(nativeConfig.ptr, callback) // pass it here
  ..rd_kafka_conf_set_log_cb(nativeConfig.ptr, Pointer.fromFunction(nativeLogCb));
  
  
void nativeLogCb(Pointer<RDKafka> client, int level, Pointer<Char> fac, Pointer<Char> buf) {
  final $fac = fac.cast<Utf8>().toDartString();
  final logMessage = buf.cast<Utf8>().toDartString();

  final context = kafkaFFI.rd_kafka_opaque(client) as ClientContext; // use here
  context.log(RDKafkaLogLevel.fromInt(level), $fac.trim(), logMessage.trim());
}
```

Other libraries don't seem to follow this other than [rust-rdkafka](https://github.com/fede1024/rust-rdkafka). I don't really need to pass the context here but doing it might have some befits. It seems not possible or is there any way of doing this?.

**Comment by mraleph** [comment]
I am not entirely sure that I understood your request / question correctly, but if you want to store a reference to the Dart object on the native side the correct way to do it is to create persistent handle and store that. Then you can unwrap the handle and take the reference out whenever you need it. 

BTW, I happened to notice that `rd_kafka_conf_set_log_cb` is documented to call the passed callback on an arbitrary internal thread - this is not going to work with Dart. 

/cc @dcharkes

**Comment by dcharkes** [comment]
> BTW, I happened to notice that `rd_kafka_conf_set_log_cb` is documented to call the passed callback on an arbitrary internal thread - this is not going to work with Dart.

Tracked in:

* https://github.com/dart-lang/sdk/issues/37022
