### ISSUE TITLE
VM test contains hardcoded source offsets

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#51389]
The VM test "JSON_JSONStream_DartObject" from `json_test.cc` compares output to a literal string which contains line numbers and offsets.

The test breaks if core library source code changes.
There is no script to update the expectation.

As such, the test is too fragile &mdash; it breaks when things unrelated to what it tests are changed.
That's only acceptable if there is an easy way to update the test expectation, which there also is not.

Consider introducing a pattern matching comparison instead of using `StringEquals`, so it's possible to introduce patterns that match any number (e.g., "%d" matching any sequence of digits), 
or replacing digit sequences with placeholders before testing,
or providing a script (linked in the test and the failure-report) that can automatically update the expectation.

**Comment by alexmarkov** [comment]
@bkonyi It looks like line numbers were added in https://dart-review.googlesource.com/c/sdk/+/227640 and token positions in https://dart-review.googlesource.com/c/sdk/+/201864.

**Comment by mraleph** [comment]
It would be also great to have update script for service debugger tests some of which also contain hardcoded line numbers pointing to core libraries.
