### ISSUE TITLE
[CP] Don't hold references to Elements in _ElementCompletionData

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51392]
### Commit(s) to merge

010749c9950d01e826aaa122b0a370a96ada49e1

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/282804

### Issue Description

A bug introduced in 2.19 can dramatically increase analyzer's memory usage. To support a new feature, a change was made which holds onto too much information during the analyzer's lifetime.

### What is the fix

The fix is to not hold onto unnecessary information during the analyzer's lifetime.

### Why cherry-pick

The issue was introduced in Dart 2.19, and we have several reports of increased memory usage in the analyzer.

### Risk

low

### Issue link(s)

Found during investigations against internal IDE

**Comment by srawlins** [comment]
CC @scheglov @DanTup @bwilkerson

**Comment by DanTup** [comment]
@srawlins 

> The issue was introduced in Dart 2.19, and we have several reports of increased memory usage in the analyzer.

FWIW my understanding was that this issue only affected Cider (where these are cached in `CiderCompletionCache`), so it might be that this fix doesn't improve anything for external users (although I don't know if that's the target here).

**Comment by scheglov** [comment]
Yes, I think users of DAS are not affected by this change.
We put `_ElementCompletionData` into the corresponding `Element`, and nowhere else.
So, they hold each other, which is not an issue for GC.

**Comment by srawlins** [comment]
Sweet. I'll back it out then. Thanks!
