### ISSUE TITLE
Make _getInstanceAsArray a public RPC

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#51393]
This is needed to evaluate big arrays to enable [go/observatory-heap-query-walk-through](http://goto.google.com/observatory-heap-query-walk-through).

**Comment by a-siva** [comment]
//cc @bkonyi @derekxu16

**Comment by polina-c** [comment]
vm_service v11.1.0 includes getInstanceAsList

**Comment by polina-c** [comment]
I am on 11.2.0
getInstanceAsArray is not here:

<img width="890" alt="Screenshot 2023-03-06 at 1 27 01 PM" src="https://user-images.githubusercontent.com/12115586/223234755-b71240ec-11b8-42d3-9a55-df0d44b0e940.png">

**Comment by polina-c** [comment]
actual name is getInstanceAsList

**Comment by derekxu16** [comment]
I think you have to define `getInstancesAsList` in DevTools's `VmServiceWrapper` similarly to https://github.com/flutter/devtools/blob/cd4f8be5f9fcb9df5e32665b1574444f427caa9a/packages/devtools_app/lib/src/service/vm_service_wrapper.dart#L273-L291
