### ISSUE TITLE
[CFE] Generated top-level procedures for inline class constructors don't copy annotations

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#51397]
Dart version: 3.0.0-edge.232ed497eab5f45d0affdf835edaa1fc94ed480e
Platform: macOS

Using test.py with `--enable-experiment=inline-class` and with DDC.

Compiling
```dart
import 'dart:js_interop';

@JS()
inline class A {
  final JSObject obj;
  @JS()
  external A();
}
```

results in the generated `Procedure` node for `A|` not having any annotations, even though it was annotated with `@JS()`.

This is higher priority than some of the other ones, as this blocks us from being able to implement object literal factories. We intend to use constructor-level annotations for those, so this is relevant.

Interestingly enough, this doesn't affect getters, setters, fields, or methods.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/283041
