### ISSUE TITLE
Type promotion for joined variables in switch

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#51399]
This code does not promote `a` in `a; // here` to `int`.
```
void f(int? x) {
  switch (x) {
    case int? a?:
    case int? a when a != null:
      a; // here
  }
}
```
However without joining, when only one `case` is present, it does.
Is this a known limitation?

**Comment by stereotype441** [comment]
Thanks for the bug report!  This will be addressed by https://dart-review.googlesource.com/c/sdk/+/283441.
