### ISSUE TITLE
[analyzer] Generic function instantiation not applied to record getters

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51403]
Consider the following program:

```dart
X id<X>(X x) => x;

void main() {
  var record = (id, 'str');
  int Function(int) f2 = record.$1;
}
```

This program is accepted by the CFE, but the analyzer (commit bedcd576560c386e6930573e97ee82596b69fdfe) reports a compile-time error:

```
  error • n005.dart:7:26 • A value of type 'X Function<X>(X)' can't be
          assigned to a variable of type 'int Function(int)'. Try changing
          the type of the variable, or casting the right-hand type to 'int
          Function(int)'. • invalid_assignment
```

Clearly, this error can be caused by a failure to apply implicit generic function instantiation. In contrast, the following program is accepted by the analyzer as well as the CFE (and it compiles and runs with no issues with `dart`):

```dart
class A {
  X id<X>(X x) => x;
}

void main() {
  int Function(int) f = A().id;
}
```

It looks like there's a need to add a case in the analyzer such that generic function instantiation can be applied to invocations of record getters, just like it can be applied to any other syntactic form of expression that occurs in the relevant typing situation.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/283343
