### ISSUE TITLE
Unexpected parse errors with analyzer in repo

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51415]
I'm working on patterns support in `dart format`. So far I've been using the latest published analyzer version, 5.4.0. That's working fine.

I tried with the bleeding edge versions of analyzer and _fe_analyzer_shared directly from the Dart SDK repo today and I get a couple of parse errors:

```
  line 1, column 69 of .: The empty record literal is not supported as a constant pattern.
    ╷
  1 │ void foo() { if (obj case (longFieldName: const (first: 1, second: 2))) {;}
    │                                                                     ^
    ╵

  line 1, column 68 of .: The empty record literal is not supported as a constant pattern.
    ╷
  1 │ void foo() { if (obj case const (element, element, element, element)) {;}
    │                                                                    ^
    ╵

  line 1, column 72 of .: The empty record literal is not supported as a constant pattern.
    ╷
  1 │ void foo() { if (obj case Foo(longFieldName: const (first: 1, second: 2))) {;}
    │                                                                        ^
    ╵
```

As far as I can tell, the code is correct. I don't see any errors in these formatter tests when using analyzer 5.4.0.

cc @scheglov @bwilkerson @jensjoha

**Comment by munificent** [comment]
Update: I'm seeing these with analyzer 0.5.5 now too.

**Comment by scheglov** [comment]
I believe these are coming from the parser, not from the analyzer itself.
Yes, I published `analyzer 5.5.0` today, so the current state of the parser is what clients get now.

**Comment by munificent** [comment]
Should I reassign this to "area-front-end" then?

**Comment by scheglov** [comment]
It is never quite clear to me, because `_fe_analyzer_shared` is neither, but probably yes.

**Comment by munificent** [comment]
I tested dart_style against the bleeding edge Dart SDK and this fixes the test failures I was seeing. Thanks!

Whenever a new analyzer version is published that contains this change, let me know and I'll update dart_style to use it.

**Comment by scheglov** [comment]
`analyzer 5.6.0` with the fix was published

**Comment by munificent** [comment]
Thanks!
