### ISSUE TITLE
weak_canonical_string_table_test went from flaky to timeout

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#51417]
The tests
```
vm/dart/weak_canonical_string_table_test Timeout (expected Pass)
```
are failing on configurations
```
dartk-strong-win-debug-x64
```

History: https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=vm/dart/weak_canonical_string_table_test&configurations=dartk-strong-win-debug-x64

**Comment by a-siva** [comment]
Reduce iteration count with a smaller heap to preserve the intent to force GCs, hopefully this will make the test not timeout on the debug builds (see https://dart-review.googlesource.com/c/sdk/+/283220)

**Comment by a-siva** [comment]
Landed https://dart-review.googlesource.com/c/sdk/+/283220, should fix this timeout.
