### ISSUE TITLE
Should `num` be `sealed` with class modifiers.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#51411]
Dart 3 will (if all goes as planned) introduce class modifiers including `sealed`.
A sealed class can *and must* be exhausted in switch cases, it's like having an enum of subtypes, every subtype must be accounted for, just like every enum value must be accounted for when switching over an enum type.

**Should `num` be `sealed`?**

The `num` type has precisely two subtypes, `int` and `double`. It's an eminent candidate for being a being sealed.

If sealed, a switch expression of `switch (someNum) { int x => ..., double d => ... }` would be exhaustive and not need a default case. On the other hand, a switch of:
```dart
num x = ...;
switch (x) {
  case double(isFinite: false): throw "Bad Number";
  case == 0.0 && double(isNegative: true): x = 0.0; // Convert -0.0 to 0.0
  case (isNegative: true): throw "Must be non-negative"; // Otherwise don't accept negative.
}
// All is well.
```
would *not be allowed*, because it's not exhaustive over a `sealed` type.

If not sealed, the switch expression will not be allowed, it will need a (useless) default case, because it's not clear that there won't be  further immediate subtypes of `num` in the future, which would be breaking for code assuming the current two exhaust the supertype. 
But the switch statement will be allowed.

I have made `num` sealed in CL https://dart-review.googlesource.com/c/sdk/+/281683
That triggers errors in co19 tests which do switch over `num`. 
Maybe that's not something that will happen outside of tests at all, so it doesn't matter.

Maybe some people actually do switch on `num`. (Most likely, nobody does today, the bigger question is whether they will when they get patterns.)

Opinions? (No opinions means I'll keep it `sealed`.)

**Comment by eernstg** [comment]
I tend to think that it's helpful to consider types as sealed in the case where this is actually sound. This makes switch expressions more natural/convenient, and it makes the semantics of switch statements more explicit. So my first opinion is: Keep it sealed!

One thing comes to mind, though: Do we ever want a numeric zoo, e.g., `int8`, .., `int256`, .. `somethingSomethingUnsigned`?  If we do want that then we might break some (a handful or a lot of?) switches whenever the zoo grows. Perhaps that's still exactly what we want, because all the locations where someone wants to switch over a `num` expression will now be flagged as non-exhaustive, and they should then be fixed.

**Comment by rakudrama** [comment]
On the web (dart2js), all `num` are `double`. That spells trouble.
The implementation types are  `JSInt implements int, double` and `JSNumNotInt implements double`.

`switch (someNum) { double d => ...}` is exhaustive.
`switch (someNum) { double d => ..., int x =>  ... }` will never match the `int` pattern.

**Comment by eernstg** [comment]
Surely there could be an exception such that `class JSInt implements int, double` would not be an error.

Moreover, it's not unthinkable that switches where the scrutinee type is `num` can be given special treatment (and similarly for nested patterns matching on a `num`).

Would it cause any harm to anyone (on any platform) if we emit a diagnostic message for every switch over `num` (top-level or nested) where an `int` case comes after a `double` case?

```dart
class Point<X extends num> {
  final X x;
  Point(this.x);
}

void main() {
  Point<num> p = ...; // Could be a `Point<T>`, for `T` in `num`, `int`, `double`, `Never`.
  switch (p)
    case Point(:double x): ...
    case Point(:int x): ... // Diagnostic: "unreachable case on the web".
  }
}
```

Even for code where the target platforms don't include the web, it's just a good habit, and the code might be used in a web setting at some point.

**Comment by lrhn** [comment]
Web numbers are a problem. As always.

If you write a switch like `switch (someNum) { double d => ..., int x =>  ... }`, it will at least work both on the web and native, it won't be *wrong*, because all the numbers really are doubles.

However `switch (someNum) { double d => ...}` is not exhaustive, and will not be treated as exhaustive, because it doesn't cover `int`. We do not want different exhaustability behavior on different platforms. It's simply not a valid switch, even when compiling for the web.

Since it won't compile on the web anyway, you'll have to add either `int i =>` or `default =>`/`_ =>` to make it compile.
By making `num` sealed, using `int i` will work, and will also carry over to running on native numbers. 
If `num` is not sealed, even adding `int i =>` won't be sufficient.
(Unless we special-case `num` somehow, to be exhaustible, but not must-be-exhausted.)

Switch expressions is not worrying me. My bigger worry is switch statements needing to be exhaustive, even if switching on `int` or `double` alone doesn't need to.
That said, switching on doubles is a horrible experience anyway, and I hope most people won't do it. Doing it on `num` makes sense only when you want to actually separate the two types of numbers, and treat each by itself:
```dart
switch (someNum) {
  case double d: return d.toStringAsFixed(5);
  case int i: return i.toString() + ".00000";
}
```
This switch being exhaustive means you don't need a dummy `return "unreachable";` below the switch or in a default branch.

**Comment by lrhn** [comment]
It's sealed.
