### ISSUE TITLE
Mirror the dash-analytics package so it can be added to DEPS

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#51425]
The analyzer team will be using the https://github.com/dart-lang/tools/tree/main/pkgs/dash_analytics package to wire up analytics for the server.

This has to be mirrored on Gerrit so before we can add it to the DEPS file.

**Comment by keertip** [comment]
@bwilkerson @athomas

**Comment by keertip** [comment]
@whesse, please reassign if needed.

**Comment by whesse** [comment]
This may be hard, because we have to mirror the entire repo and add it to deps, but that isn't a big problem.

**Comment by bwilkerson** [comment]
@eliasyishak

**Comment by eliasyishak** [comment]
Thank you for the cc @bwilkerson... let me know if there is anything I can do to help

**Comment by whesse** [comment]
Note that the generate_package_config.dart script will add all packages in the tools repo to the SDK's .dart_tool/package_config.json file, once it is added to DEPS.

Right now, there is only the single package dash_analytics in the repo, so that is what we want.

**Comment by whesse** [comment]
I have added a mirror of dart-lang/tools to the dart GoB host, and it can now be added to DEPS.

I am not clear on how this new package fits within the restrictions outlined in our sdk DEPS policy - the "raising-the-quality-of-dart-packages" document, which is linked to from our instructions about setting up a mirror.

Should it be added to the package owners tracking sheet (internal) as a non-published package?

Semantically, it seems to be the same as a package added to the sdk repo in the pkg/ directory.  Is it maintained in a separate repo so that it can be used by the Flutter framework without publishing it?

**Comment by eliasyishak** [comment]
Thanks for setting everything up! Yes we have decided to create this separate repo so that we can use the analytics package within any Flutter and Dart related tooling. If we decide to publish it will likely be unlisted. @devoncarew anything else I'm missing?

**Comment by bwilkerson** [comment]
@eliasyishak If there's nothing else that needs to be done first (and I don't think there is), do you want to update the DEPS file to pull in the analytics package, or would you like me to do so?

**Comment by whesse** [comment]
It can work best if the DEPS file starts pulling it in, and then that change to DEPS rolls to flutter engine DEPS, before adding actual dependencies to the package in the SDK build.  That way, the tip-of-tree builders already have the new package rolled in to them before it is needed.

**Comment by bwilkerson** [comment]
Good to know, thanks! Sounds like we definitely want the CL to only add the package to the DEPS file, which was what I was trying to suggest anyway.

We could then start working on a CL to use the package as long as we hold off landing the latter CL until after the roll into the flutter engine DEPS.

**Comment by eliasyishak** [comment]
@bwilkerson do you mind adding it to the DEPS and tagging me in the PR? I'm not sure how to update that file would like to learn how to do so. I couldn't find anything in the Wiki on updating that file at first glance

**Comment by bwilkerson** [comment]
I have uploaded a CL (https://dart-review.googlesource.com/c/sdk/+/283920), but it doesn't currently work because `https://dart.googlesource.com/dash_analytics` doesn't yet exist.

@whesse Should it exist, or do we just need to wait a bit?

**Comment by sortie** [comment]
Your repository is named `tools`: https://dart.googlesource.com/tools/ :)

**Comment by devoncarew** [comment]
> I am not clear on how this new package fits within the restrictions outlined in our sdk DEPS policy - the "raising-the-quality-of-dart-packages" document, which is linked to from our instructions about setting up a mirror.

@whesse - good question; adding a dep for this package is expected, so I think this falls within our policy.

Agree that dep'ing it in first, and letting that work through the downstream systems like the engine, before adding code references to the package makes sense.

**Comment by bwilkerson** [comment]
That helps, but I still can't get it to download it to the right place. It appears to be assuming that if it's in the `sdk` repo then it should go into `sdk/sdk/third_party`, but that if it's in the `tools` repo then it should go into `sdk/tools/third_party`.

I'm obviously missing something and should let someone more familiar with the DEPS file pull this in.

**Comment by devoncarew** [comment]
No worries; @bwilkerson and @whesse - I sent you this for review: https://dart-review.git.corp.google.com/c/sdk/+/283921.
