### ISSUE TITLE
implement precedence in `DartPatternImpl` subclasses

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#51426]
See TODO in `DartPatternImpl`:

```dart
  @override
  // TODO(brianwilkerson) Remove this and implement it in subclasses when we
  //  have constants for pattern-related precedence values.
  Precedence get precedence => throw UnimplementedError();
```

This is required to detect unnecessary parenthesis in the linter https://github.com/dart-lang/linter/issues/4062.

/fyi @bwilkerson @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/283740

**Comment by pq** [comment]
Thank you!
