### ISSUE TITLE
Incorrectly getting 'Unable to compute fixes: The lint xxx is not enabled' from dart fix

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#51427]
I'm running `dart fix` over the sdk repo. In some cases, I see

```
Unable to compute fixes: The lint 'unnecessary_brace_in_string_interps' is not enabled; add it to your analysis options and try again.
```

in places were we do have the lint enabled. After adding some debugging code, it looks like whats happening is that the check is firing for a sub-analysis context - an analysis context created from a sub-directory that has a different config in its analysis options file.

The error message here is a false positive; I suspect that the check should just be removed and - if the user types in a code that's not enabled - we just do something like report 'no changed files' (or whatever the std. messaging would be for no changes).

https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/bulk_fix_processor.dart#L239

cc @pq

**Comment by pq** [comment]
> I suspect that the check should just be removed 

That sounds right to me.

Thanks for digging into debugging it!
