### ISSUE TITLE
[vm] Try simplifying the locking logic used by the timeline recorders

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#51424]
Perhaps some logic can be shared between `Timeline::recorder_lock_` and `RecorderShutdownSynchronizationLock`.

See https://dart-review.googlesource.com/c/sdk/+/283141/comment/ee1b12cb_bf4792ef/

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/283481
