### ISSUE TITLE
edit.organizeImports vs. source.organizeImports

### ISSUE THREAD

**Issue by james2doyle** [dart-lang/sdk#51439]
This tracker is for issues related to:

* Analyzer
* Dart SDK version: 3.0.0-239.0.dev (dev) (Wed Feb 15 02:39:19 2023 -0800) on "macos_arm64"

Not sure where to file this but the LSP seems to be missing some capabilities for execution. Right now my editor is reporting the following: 

```
Dart: Supported execute commands: ['edit.sortMembers', 'edit.organizeImports', 'edit.fixAll', 'edit.sendWorkspaceEdit', 'refactor.perform', 'move_top_level_to_file']
```

It seems to be missing some of the capabilities outlined in the Spec: https://github.com/dart-lang/sdk/blob/086727ee6f66abdcc7050ee53504ba58e200ce40/pkg/analysis_server/tool/lsp_spec/lsp_meta_model.json#L13305-L13320

Specifically `source.organizeImports` and `source.fixAll`. Wondering if there is something missing here?

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
I think there may be some confusion here between Code Actions and Commands. This might be because the way VS Code/LSP discovers file-level code actions (like Organize Imports).

There is a _Command_ `edit.organizeImports` (defined by Dart, arbitrarily, not defined by the spec) which takes some arguments (a file path) and will generate edits to organize imports and send them back to the client (via `workspace/applyEdit`). This command's ID is advertised by the server (as your client has reported) so that the client knows if it sees requests to execute `edit.organizeImports` it can be done by the server (as opposed to being a local command in the client). Since this command takes arguments, the client has no way of knowing how to execute the command on its own - it can only do so if it's told to (and given arguments) by some other mechanism.

Seperately, there are `CodeAction`s. These are things you usually see in the lightbulb menu, but those prefixed with `source` are a special kind that the editor knows can be invoked for a file without a specific location in the document.

So VS Code (or other LSP clients) can send a request to the server to ask "are there any source CodeActions for this file?" to which we respond with a `CodeAction` with the `kind` `source.organizeImports`. That `CodeAction` says that if selected it should trigger the `edit.organizeImports` command (described above) and provides the arguments required to invoke it (inside `createCommand`). Although VS Code discovers this via a CodeAction, it doesn't show in the lightbulb menu but instead enables the standard "Organize Imports" command in VS Code.

This is the code that produces the `source.organizeImports` `CodeAction` looks like this (the `createCommand` method here adds the arguments, which includes a `path`):

https://github.com/dart-lang/sdk/blob/4e614d299cc96ec09294c1577af15fcf5a675f0d/pkg/analysis_server/lib/src/lsp/handlers/code_actions/dart.dart#L296-L301

Hopefully this makes sense?

Are you asking about this because you're trying to use Organize Imports in your editor but can't find it? If so, can you confirm which editor/LSP client you're using? Thanks!

**Comment by james2doyle** [comment]
Ok thanks for the info. I'll add some more context:

I'm using Sublime LSP with Sublime Text 4. For the most part, the LSP plugins just map the editor features to LSP features.

**I can call the Code Actions manually and they work great.**

The issue comes when I try to use the features that can auto run on save.

https://github.com/sublimelsp/LSP/blob/1e4adea1da49deb4134eaa2253c27555258790d8/LSP.sublime-settings#L13-L28

You can see the docs here only support `source.*` actions but the LSP does not seem to return those capabilities so the actions can never run.

The Dart LSP has this single line when it starts:

```
Dart: Supported execute commands: ['edit.sortMembers', 'edit.organizeImports', 'edit.fixAll', 'edit.sendWorkspaceEdit', 'refactor.perform', 'move_top_level_to_file']
```

In contrast, when I start the Typescript LSP, I get the following output:

```
LSP-typescript: Supported execute commands: ['_typescript.applyWorkspaceEdit', '_typescript.applyCodeAction', '_typescript.applyRefactoring', '_typescript.configurePlugin', '_typescript.organizeImports', '_typescript.applyRenameFile', '_typescript.goToSourceDefinition']
LSP-typescript: supported code action kinds: ['source.fixAll.ts', 'source.removeUnused.ts', 'source.addMissingImports.ts', 'source.organizeImports.ts', 'source.removeUnusedImports.ts', 'source.sortImports.ts', 'quickfix', 'refactor']
LSP-typescript: Supported semantic token types: ['class', 'enum', 'interface', 'namespace', 'typeParameter', 'type', 'parameter', 'variable', 'enumMember', 'property', 'function', 'member']
LSP-typescript: Supported semantic token modifiers: ['declaration', 'static', 'async', 'readonly', 'defaultLibrary', 'local']
```

So it actually looks like the Typescript LSP registers both "Supported execute commands" and  "supported code action kinds" when starting up. 

Given all this, it seems that the Sublime LSP will only work with the "source.*" code actions, in which Dart registers none.

Here is the output of the Eslint LSP when it starts:

```
LSP-eslint: Supported execute commands: ['eslint.applySingleFix', 'eslint.applySuggestion', 'eslint.applySameFixes', 'eslint.applyAllFixes', 'eslint.applyDisableLine', 'eslint.applyDisableFile', 'eslint.openRuleDoc']
LSP-eslint: supported code action kinds: ['quickfix', 'source.fixAll.eslint']
```

You can see this advice in the Eslint LSP repo where they suggest using the source name for the auto save action: https://github.com/sublimelsp/LSP-eslint#faq
You can see the same advice in the Typescript LSP docs: https://github.com/sublimelsp/LSP-typescript#code-actions-on-save

I guess my question boils down to, why does the Dart analysis server not register any "source.*" capabilities? Or is it possible the "edit.* " actions are mislabelled and should be "source.*" instead?

**Comment by DanTup** [comment]
@james2doyle thanks for the additional info. It appears I missed something when responding above - the server does actually advertise `CodeActionKind`s up-front too (without needing a `textDocument/codeAction` request), although they are distinct from `Command`s (which is why your TS output lists "Supported execute commands" and "supported code action kinds" separately).

> I guess my question boils down to, why does the Dart analysis server not register any `source.*` capabilities? Or is it possible the `edit.*` actions are mislabelled and should be `source.*` instead?

There's a difference between commands and code actions. The things you're seeing with `edit.` are commands (and are required as they are, they're not mis-labelled). The server _additionally_ advertises support for `source.*` _code actions_, but they're separate.

There are two ways for a server to register each of it's capabilities. One is _statically_ which happens once at startup and is often quite restrictive, and the other is _dynamically_ which can happen at any time and has more options. We favour dynamic registrations when the client supports them, because this allows us to register our features only for specific file types rather than globally (for example allowing us to tell the client we only provide `CodeAction`s for Dart, and avoiding it sending us requests for `CodeAction`s when you're editing JS files).

My guess is that your client supports dynamic registration so we're not doing static registration (which is why you don't see the log, because perhaps it's specifically only logging things in the static registrations), but perhaps it's also not handling the dynamic registration of `CodeAction`s correctly. If you enabling logging the LSP traffic (which you can do with the `--instrumentation-log-file=/foo/bar.txt` option when starting the Dart LSP server) and search for `source.organizeImports`, I think you'll see a message from the server like this:

```js
{
	"id": 2,
	"jsonrpc": "2.0",
	"method": "client/registerCapability",
	"params": {
		"registrations": [
			{
				"id": "17",
				"method": "textDocument/codeAction",
				"registerOptions": {
					"codeActionKinds": [
						"source",
						"source.organizeImports",
						"source.fixAll",
						"source.sortMembers",
						"quickfix",
						"refactor"
					],
					"documentSelector": [
						{
							"language": "dart",
							"scheme": "file"
						}
					]
				}
			}
		]
	}
}
```

This is the equivalent of the static registration TypeScript is doing, but is filtered to Dart files.

Assuming you see this in the logs, then I think the server is behaving correctly. It's not clear to me what's preventing this from working as you'd like in Sublime though - if you configure Sublime to use `source.organizeImports` on-save anyway, does it just not work? If so (and assuming the dynamic registration was in the log) I would suggest filing an issue against the Sublime LSP client (linking to this comment may be useful, and you're welcome to CC me if I might be able to help).

**Comment by DanTup** [comment]
At a guess, I'd say there may be an issue around here:

https://github.com/sublimelsp/LSP/commit/fb4de2078977ccf0f07d2271fdf87a1023b04b9b#diff-68edb5ba4a540fc78bc78afefa019e7a7e4d1f349dac645baf71399c29ee266fR127

This code seems to read `codeActionProvider.codeActionKinds` (the static registration) when deciding whether to run the code action on-save, but doesn't seem like it's taking into account dynamic registrations.

**Comment by james2doyle** [comment]
Ok thanks for all the help so far!

Here is how I configured my LSP plugin trying to get the auto commands working:

```json
"lsp_format_on_save": true,
"lsp_code_actions_on_save": {
    "source.organizeImports": true,
    "source.fixAll": true,
    "source.sortMembers": true,
    "edit.sortMembers": true,
    "edit.organizeImports": true,
    "edit.fixAll": true,
},
```

Doesn't seem to work though.

I ran the server with the log and got the following:

```
1676654363847:Ver:1671918873111731955779:unknown.client.lsp:1.22.0:1.33.4:3.0.0
```

```json
{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "rootPath": "/Users/jamesdoyle/Git/flutter-explorations/ed_team_app",
    "workspaceFolders": [
      {
        "name": "ed_team_app",
        "uri": "file::///Users/jamesdoyle/Git/flutter-explorations/ed_team_app"
      }
    ],
    "capabilities": {
      "workspace": {
        "symbol": {
          "tagSupport": {
            "valueSet": [
              1
            ]
          },
          "symbolKind": {
            "valueSet": [
              5,
              3,
              23,
              17,
              2,
              6,
              20,
              18,
              10,
              11,
              25,
              24,
              9,
              16,
              22,
              8,
              21,
              19,
              13,
              12,
              7,
              26,
              1,
              4,
              14,
              15
            ]
          },
          "dynamicRegistration": true
        },
        "didChangeConfiguration": {
          "dynamicRegistration": true
        },
        "executeCommand": {},
        "codeLens": {
          "refreshSupport": true
        },
        "semanticTokens": {
          "refreshSupport": true
        },
        "applyEdit": true,
        "workspaceEdit": {
          "documentChanges": true,
          "failureHandling": "abort"
        },
        "inlayHint": {
          "refreshSupport": true
        },
        "workspaceFolders": true,
        "configuration": true
      },
      "general": {
        "markdown": {
          "parser": "Python-Markdown",
          "version": "3.2.2"
        },
        "regularExpressions": {
          "engine": "ECMAScript"
        }
      },
      "window": {
        "showDocument": {
          "support": true
        },
        "showMessage": {
          "messageActionItem": {
            "additionalPropertiesSupport": true
          }
        },
        "workDoneProgress": true
      },
      "textDocument": {
        "completion": {
          "insertTextMode": 2,
          "completionItem": {
            "deprecatedSupport": true,
            "labelDetailsSupport": true,
            "insertReplaceSupport": true,
            "resolveSupport": {
              "properties": [
                "detail",
                "documentation",
                "additionalTextEdits"
              ]
            },
            "insertTextModeSupport": {
              "valueSet": [
                2
              ]
            },
            "tagSupport": {
              "valueSet": [
                1
              ]
            },
            "documentationFormat": [
              "markdown",
              "plaintext"
            ],
            "snippetSupport": true
          },
          "completionItemKind": {
            "valueSet": [
              16,
              7,
              1,
              6,
              22,
              19,
              10,
              9,
              2,
              14,
              13,
              8,
              24,
              11,
              12,
              20,
              5,
              15,
              23,
              3,
              18,
              4,
              25,
              17,
              21
            ]
          },
          "dynamicRegistration": true
        },
        "documentSymbol": {
          "hierarchicalDocumentSymbolSupport": true,
          "tagSupport": {
            "valueSet": [
              1
            ]
          },
          "symbolKind": {
            "valueSet": [
              5,
              3,
              23,
              17,
              2,
              6,
              20,
              18,
              10,
              11,
              25,
              24,
              9,
              16,
              22,
              8,
              21,
              19,
              13,
              12,
              7,
              26,
              1,
              4,
              14,
              15
            ]
          },
          "dynamicRegistration": true
        },
        "inlayHint": {
          "resolveSupport": {
            "properties": [
              "textEdits",
              "label.command"
            ]
          },
          "dynamicRegistration": true
        },
        "definition": {
          "linkSupport": true,
          "dynamicRegistration": true
        },
        "colorProvider": {
          "dynamicRegistration": true
        },
        "callHierarchy": {
          "dynamicRegistration": true
        },
        "selectionRange": {
          "dynamicRegistration": true
        },
        "codeLens": {
          "dynamicRegistration": true
        },
        "typeHierarchy": {
          "dynamicRegistration": true
        },
        "synchronization": {
          "willSaveWaitUntil": true,
          "didSave": true,
          "willSave": true,
          "dynamicRegistration": true
        },
        "typeDefinition": {
          "linkSupport": true,
          "dynamicRegistration": true
        },
        "hover": {
          "contentFormat": [
            "markdown",
            "plaintext"
          ],
          "dynamicRegistration": true
        },
        "documentLink": {
          "tooltipSupport": true,
          "dynamicRegistration": true
        },
        "publishDiagnostics": {
          "versionSupport": true,
          "tagSupport": {
            "valueSet": [
              1,
              2
            ]
          },
          "dataSupport": true,
          "codeDescriptionSupport": true,
          "relatedInformation": true
        },
        "references": {
          "dynamicRegistration": true
        },
        "declaration": {
          "linkSupport": true,
          "dynamicRegistration": true
        },
        "rangeFormatting": {
          "dynamicRegistration": true
        },
        "implementation": {
          "linkSupport": true,
          "dynamicRegistration": true
        },
        "signatureHelp": {
          "signatureInformation": {
            "parameterInformation": {
              "labelOffsetSupport": true
            },
            "documentationFormat": [
              "markdown",
              "plaintext"
            ],
            "activeParameterSupport": true
          },
          "contextSupport": true,
          "dynamicRegistration": true
        },
        "semanticTokens": {
          "tokenModifiers": [
            "deprecated",
            "static",
            "definition",
            "declaration",
            "abstract",
            "documentation",
            "async",
            "modification",
            "defaultLibrary",
            "readonly"
          ],
          "overlappingTokenSupport": false,
          "augmentsSyntaxTokens": true,
          "tokenTypes": [
            "class",
            "keyword",
            "namespace",
            "struct",
            "type",
            "method",
            "comment",
            "decorator",
            "enum",
            "interface",
            "operator",
            "event",
            "number",
            "enumMember",
            "parameter",
            "macro",
            "variable",
            "function",
            "property",
            "typeParameter",
            "regexp",
            "string",
            "modifier"
          ],
          "requests": {
            "range": true,
            "full": {
              "delta": true
            }
          },
          "formats": [
            "relative"
          ],
          "multilineTokenSupport": true,
          "dynamicRegistration": true
        },
        "formatting": {
          "dynamicRegistration": true
        },
        "documentHighlight": {
          "dynamicRegistration": true
        },
        "rename": {
          "prepareSupport": true,
          "prepareSupportDefaultBehavior": 1,
          "dynamicRegistration": true
        },
        "codeAction": {
          "dataSupport": true,
          "codeActionLiteralSupport": {
            "codeActionKind": {
              "valueSet": [
                "quickfix",
                "refactor",
                "refactor.extract",
                "refactor.inline",
                "refactor.rewrite",
                "source.fixAll",
                "source.organizeImports"
              ]
            }
          },
          "resolveSupport": {
            "properties": [
              "edit"
            ]
          },
          "isPreferredSupport": true,
          "dynamicRegistration": true
        }
      }
    },
    "clientInfo": {
      "name": "Sublime Text LSP",
      "version": "1.22.0"
    },
    "initializationOptions": {
      "onlyAnalyzeProjectsWithOpenFiles": false,
      "suggestFromUnimportedLibraries": true,
      "outline": true,
      "flutterOutline": true,
      "closingLabels": true,
      "updateImportsOnRename": true
    },
    "processId": 91708,
    "rootUri": "file::///Users/jamesdoyle/Git/flutter-explorations/ed_team_app"
  },
  "id": 1
}
```

Which does show the code actions, at least two of them.

That was the first two lines. Further down I get the following:

```json
{
  "id": 3,
  "jsonrpc": "2.0",
  "method": "client/registerCapability",
  "params": {
    "registrations": [
      {
        "id": "16",
        "method": "textDocument/codeAction",
        "registerOptions": {
          "codeActionKinds": [
            "source",
            "source.organizeImports",
            "source.fixAll",
            "source.sortMembers",
            "quickfix",
            "refactor"
          ],
          "documentSelector": [
            {
              "language": "dart",
              "scheme": "file"
            }
          ]
        }
      }
    ]
  }
}
```

Here is the "registerCapability" and it does show all the source capabilities. So it does seem like it just is not returning the dynamic registrations when looking at the session. 

I'll make an issue on the Sublime LSP side and see if there is something going on there

**Comment by james2doyle** [comment]
I am seeing these lines in the log:

```
1676656755429:Res:{
  "id": 3,
  "jsonrpc": "2.0",
  "result": [
    {
      "command": {
        "arguments": [
          {
            "path": "/Users/jamesdoyle/Git/flutter-explorations/ed_team_app/lib/src/team_feature/team_member_list_view.dart",
            "autoTriggered": true
          }
        ],
        "command": "edit.organizeImports",
        "title": "Organize Imports"
      },
      "kind": "source.organizeImports",
      "title": "Organize Imports"
    },
    {
      "command": {
        "arguments": [
          {
            "path": "/Users/jamesdoyle/Git/flutter-explorations/ed_team_app/lib/src/team_feature/team_member_list_view.dart",
            "autoTriggered": true
          }
        ],
        "command": "edit.fixAll",
        "title": "Fix All"
      },
      "kind": "source.fixAll",
      "title": "Fix All"
    }
  ]
}
1676656756600:Watch:<unknown>:/Users/jamesdoyle/Git/flutter-explorations/ed_team_app/lib/src/team_feature/team_member_list_view.dart:modify
```

It looks like the triggers are running automatically but they are not updating the file they are running on...

**Comment by DanTup** [comment]
> I ran the server with the log and got the following:
> [...]
> Which does show the code actions, at least two of them.

The JSON you posted there is sent from the client to the server. The `CodeActionKind`s there are the client telling the server which `CodeActionKind`s it supports. It also shows `dynamicRegistration: true` as I suspected. What you posted after that is the server dynamically registering them.

So those do seem to match up with my suspicion about. The issue you've filed in Sublime/LSP describes the issue well, though I'd also include the JSON from above that contains the `"method": "client/registerCapability",` call (which is the server dynamically registering `CodeAction` support) which may be helpful.

The final JSON block you posted is the server providing the `CodeAction`s in response to the client asking for them (which is basically the instructions of how the client should perform those actions - the commands and arguments that it needs to invoke them). Interestingly we returned `autoTriggered` which suggests when the client asked for them, it did tell us that it was doing so automatically (and it wasn't manually triggered), so it seems like it may be doing a lot of what is expected and it's odd it's not actually executing them.

I've subscribed to the Sublime/LSP issue to get notifications of updates, and will post there if I can add any value (or, if it does turn out we're doing something wrong here, will fix).

**Comment by james2doyle** [comment]
Ok based on the response from the Sublime LSP contributor it seems to be an issue with the dynamic registration not being considered. Sounds like the fix needs to be in that repo. Thanks for all the help! I'll close this now and continue the conversation there
