### ISSUE TITLE
CFE allows extending `Function`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#51435]
There are new test failures on [Enforce current library restrictions.](https://dart-review.googlesource.com/c/sdk/+/281683).

The tests
```
language/nonfunction_type_aliases/generic_usage_function_error_test MissingCompileTimeError (expected Pass)
language/nonfunction_type_aliases/usage_function_error_test MissingCompileTimeError (expected Pass)
```
are failing (at least) on configurations
```
cfe-linux
cfe-strong-linux
cfe-weak-linux
```

A change of behavior was added, making `Function` be a `final` class, which should prevent it from being used as a superclass, interface or mixin in language version 3.0 code (but not below, where it should still be ignored like now).

The error is reported by the analyzer, probably because the analyzer used the `final class Function` declaration as basis for its type, and is not reported by the CFE, presumably because it replaces the declaration entirely with its own internal definition.

The CFE should make it an error to use the `Function` class as a supertype in class-modifier-enabled code.
(Maybe it's as easy as setting the `final` flag on the internal type definition. One can hope.)

**Comment by kallentu** [comment]
Implemented with https://github.com/dart-lang/sdk/commit/1ce23bbd0bbb419537dc9d136aad774c9b96f4ac.
