### ISSUE TITLE
[analyzer] not show error when List generics type implicit promotion

### ISSUE THREAD

**Issue by CoderBuck** [dart-lang/sdk#51442]
code:
```dart
class A {}
class A1 extends A {}
class A2 extends A {}

void main() {
  List<A> list = <A>[];
  list = <A1>[];  //   list type is changed to List<A1> 
  list.add(A2());
}
```
when run
<img width="879" alt="image" src="https://user-images.githubusercontent.com/17465838/219571433-37c982e6-d925-4d37-a9db-26c16317ca92.png">

```
> dart --version
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_x64"
```

**Comment by mraleph** [comment]
Dart's generics are covariant - so this is working as intended.

Language team has previously discussed introducing variance annotations which would allow developers to control this. See

- [Use-site variance](https://github.com/dart-lang/language/issues/753)
- [Declaration-site variance](https://github.com/dart-lang/language/issues/524)

**Comment by eernstg** [comment]
I think it could be useful to mention one more thing:

```dart
class A {}
class A1 extends A {}
class A2 extends A {}

void main() {
  List<A> list = <A>[];
  list = <A1>[];  // `list.runtimeType == List<A1>`, static type still `List<A>`.
  list.add(A2()); // Accepted at compile time due to covariance, throws at run time.
}
```

The reason why `list` is _not_ promoted at `list = <A1>[]` is that `List<A1>` is not a 'type of interest' for `list` at that point (or ever, in fact), and an assignment will only promote to a type of interest.

You can make a type a type of interest by checking for it:

```
void main() {
  List<A> list = <A>[];
  if (list is! List<A1>) list = <A1>[];  // Promote `list` to `List<A1>`.
  list.add(A2()); // Compile-time error.
}
```
