### ISSUE TITLE
Positional fields for `Records` should be indexed at 1 not 0

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#51451]
This would conform with the recent spec update to `Records`: https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#120

FYI @derekxu16 @bkonyi

**Comment by mit-mit** [comment]
I think this should be a P1 for beta 2 given it's such a big API change

**Comment by derekxu16** [comment]
The change will probably land today.

https://dart-review.googlesource.com/c/sdk/+/284722
