### ISSUE TITLE
Dart analyzer server has terminated

### ISSUE THREAD

**Issue by NamBaoL** [dart-lang/sdk#51454]
The editor didn't show any errors or highlights and neither show syntax errors until I run the app. 
I tried `flutter clean` and `flutter upgrade`, and uninstall and install the SDK again. Any solutions?

<img width="341" alt="Screenshot 2023-02-17 at 9 28 06 PM" src="https://user-images.githubusercontent.com/86450453/219838756-3d1eb8fa-a937-46a2-956d-90ca8a460a20.png">

**Comment by bwilkerson** [comment]
Which editor are you using?

Which version of the Flutter SDK are you using?

**Comment by keertip** [comment]
closing as there is not enough information to figure out what could have caused the crash.

@NamBaoL , feel free to reopen issue with more details if this happens again.
