### ISSUE TITLE
Extensions are not recognized on parameter class members if declared via "var"

### ISSUE THREAD

**Issue by apps-transround** [dart-lang/sdk#51469]
Consider a function with a class parameter. If it is declared by var, the extensions on its members are lost:

```dart
void main() {
  void withType(AnyClass h) {
    print(h.address.upper());
    /* ABCD */
  }
  void withVar(var h) {
    print(h.address.upper());
    /* NoSuchMethodError: Class 'String' has no instance method 'upper'. */
  }
  
  AnyClass anyClass = AnyClass();
  withType(anyClass);
  withVar(anyClass);
}

extension StringUtils on String {
  String upper() {
    return toUpperCase();
  }
}

class AnyClass {
  String address = 'abcd';
}
```
The output is the following:
ABCD
Unhandled exception:
NoSuchMethodError: Class 'String' has no instance method 'upper'.
Receiver: "abcd"
Tried calling: upper()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      main.withVar (package:win_test/extension_test.dart:9:26)
#2      main (package:win_test/extension_test.dart:14:3)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

Process finished with exit code 255

[This not the extension on dynamic issue](https://github.com/dart-lang/sdk/issues/42381#issue-640551997)

[The documentation indicates that it should work](https://dart.dev/guides/language/extension-methods#:~:text=Extension%20methods%20do%20work%20with%20Dart%E2%80%99s%20type%20inference)

I think this is a very low priority issue that can be easily avoided by using the class type for the function parameters.

* Dart SDK Version (`dart --version`)
Dart SDK version: 2.19.1 (stable) (Tue Jan 31 12:25:35 2023 +0000) on "windows_x64"

**Comment by mraleph** [comment]
Note that parameter types of non-anonymous functions are **not** type inferred from uses. So putting `var` on a parameter is the same as not putting anything - which means `dynamic` in this context.

**Comment by apps-transround** [comment]
Thanks, I wasn't aware of that.
