### ISSUE TITLE
dart:ffi status in SQLite tutorial seems out of date?

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#51460]
https://github.com/dart-lang/sdk/blob/main/samples/ffi/sqlite/docs/sqlite-tutorial.md#current-dartffi-development-status

says:
```
Platform limitations:

dart:ffi is only enabled on 64 bit Windows, Linux, and MacOS. (Arm64 and 32 bit Intel are under review.)
dart:ffi only works in JIT mode, not in AOT.
```

My understanding is neither of those limitations are still the case?

**Comment by dcharkes** [comment]
Nice to see you again @eseidel!

Correct, those limitations are gone! Thanks for the report. I'll update the doc.
