### ISSUE TITLE
`required` named parameters with a leading underscore are not checked at compile-time

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#51472]
Normally named parameters that are named with a leading underscore are rejected with a compile-time error.  Given:
```dart
class Foo {
  final int? _x;
  
  Foo({this._x});
}

void main() {
  var foo = Foo(_x: 42);
  print(foo._x);
}
```
Executing the above code in interpreted mode (`dart foo.dart`) results in an expected error:
```
foo.dart:4:13: Error: An optional named parameter can't start with '_'.
  Foo({this._x});
            ^^ 
```
Compiling it with `dart compile exe` also fails as expected:
```dart
Info: Compiling with sound null safety.
foo.dart:4:13: Error: An optional named parameter can't start with '_'.
  Foo({this._x});
            ^^
Error: AOT compilation failed
Generating AOT kernel dill failed!
```
If I change the `_x` named parameter to be `required`, these compile-time errors disappear.  Running with `dart foo.dart` generates a runtime error instead:
```
Unhandled exception:
NoSuchMethodError: No constructor 'Foo.' with matching arguments declared in class 'Foo'.
Receiver: Foo
Tried calling: new Foo.()
Found: new Foo.({required int? _x@18207824}) => Foo
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:225:5)
#1      main (file:///home/jameslin/src/tmp/foo.dart)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```
And with `dart compile exe`, no errors are generated at compile-time nor at runtime.

Perhaps related, the compile-time error messages specifically refer to "An **optional** named parameter...", but the optional-ness should not be relevant.  The error messages should just say "A named parameter...".

I'm using Dart SDK version: 2.19.2 (stable) (Unknown timestamp) on "linux_x64".

**Comment by asashour** [comment]
With the `dev` channel, the compile-time errors are there, both with the analyzer and the CFE (on running `dart foo.dart`).

But yes, the message `An optional named parameter can't start with '_'.` should not have **optional**, and the analyzer message and the CFE should be the same.

**Comment by srawlins** [comment]
Now the analyzer prints "Named parameters can't start with an underscore."

The CFE prints "Error: A named parameter can't start with an underscore ('_')."
