### ISSUE TITLE
[analyzer] `dead_code` does not flag dead code in for-loop & while-loop

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#51474]
* Dart SDK Version 2.19.2

The following snippet of code isn't flagged as dead code even though it can never be reached:
```dart
for (int i = 0; i < 0; i++) {
  // Dead code not flagged
}

const a = 1;
while (a < 0) {
  // Dead code not flagged
}

const b = 'foo';
while (b == 'bar') {
  // Dead code not flagged
}
```

However, replacing the condition with a `false` literal seems to flag it:
```dart
for (int i = 0; false; i++) {
  // Dead code flagged
}

while (false) {
  // Dead code flagged
}
```

**Comment by bwilkerson** [comment]
@stereotype441

**Comment by bwilkerson** [comment]
Thanks for raising the question.

While it's true that we could recognize a small number of special cases (the `for` loop example being one), recognizing all of the cases (such as the `while` loop example) would effectively require evaluating some portion of the code.

Even with the restrictions necessary to avoid the halting problem, we don't believe that we want the analyzer to perform any evaluation of code beyond what's required by the specification for constants. As a result, we're going to have to say no to this request.
