### ISSUE TITLE
[CP] DDC Test and builder configuration changes

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#51484]
### Commit(s) to merge

fc2c9269f081a1735e669f8fff70fb76823536d0

### Target

beta and stable

### Prepared changelist for beta/stable

* Stable
https://dart-review.googlesource.com/c/sdk/+/284542
https://dart-review.googlesource.com/c/sdk/+/284543
https://dart-review.googlesource.com/c/sdk/+/284544

### Issue Description

We updated the configurations for running test builders in the SDK repo. There are accompanying changes in the infrastructure but that config is outside of the SDK repo and is the same across main, beta, and stable branches.

### What is the fix

Changes to the DDC test and builder configurations that work with the infrastructure changes.

### Why cherry-pick

This cherry pick is only needed if there are other cherry picks selected before the next merge from main into beta or stable. It will help ensure we can still run trybots for DDC.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51481

### Extra Info

I'm filing this issue early in preparation. @athomas can link the change to the infrastructure that will trigger the need for this cherry pick when it is ready.

Beta requires cherry picking 2 changes:
https://dart-review.googlesource.com/c/sdk/+/284545 (non-breaking)
https://dart-review.googlesource.com/c/sdk/+/284546 (breaking and requires previous change + change in infra repo)

Stable requires cherry picking 3 changes:
https://dart-review.googlesource.com/c/sdk/+/284542 (non-breaking)
https://dart-review.googlesource.com/c/sdk/+/284543 (non-breaking)
https://dart-review.googlesource.com/c/sdk/+/284544 (breaking and requires previous two changes + change in infra repo)

**Comment by itsjustkevin** [comment]
@sigmundch can you take a look at this cherry pick request?

**Comment by athomas** [comment]
LGTM, I strongly suggest we merge this to avoid losing DDC test coverage on stable until 3.0.
