### ISSUE TITLE
Add support for `dart compilation-server status`

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#51488]
This command would allow for users to query the running status of the resident frontend compilation service for their current project.

**Comment by bkonyi** [comment]
@derekxu16 @a-siva is this something that still makes sense to do?

**Comment by a-siva** [comment]
Not sure how useful this is if the command line tool is able to automatically figure out the location of the frontend server and connect to it or start one if there isn't one.

**Comment by derekxu16** [comment]
Yeah, I agree. This doesn't seem like a feature that will be used frequently.

**Comment by bkonyi** [comment]
That's what I figured, just wanted to make sure there wasn't something obvious I was missing. I'll just close this issue then.
