### ISSUE TITLE
[Breaking change] Support `SameSite` in `Cookies`.

### ISSUE THREAD

**Issue by sun-jiao** [dart-lang/sdk#51486]
Related pull request:
[github](https://github.com/dart-lang/sdk/pull/51457)
[googlesource](https://dart-review.googlesource.com/c/sdk/+/283984?tab=comments)

1. **The intended change in behavior**: Add enum type `SameSite` ([link](https://github.com/dart-lang/sdk/blob/3becd6194ffcc3782f563efde29d416193102071/sdk/lib/_http/http.dart#L738)) and public filed `sameSite` in abstract class `Cookie` ([link](https://github.com/dart-lang/sdk/blob/3becd6194ffcc3782f563efde29d416193102071/sdk/lib/_http/http.dart#L797)) and its default implementation `_Cookie` ([link](https://github.com/dart-lang/sdk/blob/3becd6194ffcc3782f563efde29d416193102071/sdk/lib/_http/http_headers.dart#L952)). 
2. **The justification/rationale for making the change**: This artribute is important for CORS requests, for example, accessing dart backend in Flutter Web. Bacause they runs on different port, browsers don't allow Flutter Web to use cookies of dart backend.
3. **The expected impact of this change**: all classes implement `Cookie` must override the filed `sameSite`.
4. **Clear steps for mitigating the change**: We can release this change in the beta and dev channels first, so developers can make changes in advance. By the time these changes appeared in the stable channel, developers will have overridden `sameSite` in their implementation, so their projects will not break.

**Comment by natebosch** [comment]
> 3\. all classes implement `Cookie` must override the filed `sameSite`.

@brianquinlan - do we have an estimate of internal and external usage of this pattern?

**Comment by brianquinlan** [comment]
@natebosch 

Know places that `implement Cookie`
- The archived project [`http_io`](https://github.com/dart-archive/http_io)
- One place in Google Ads where `Cookie` is implemented as part of a fake

**Comment by itsjustkevin** [comment]
@vsmenon @grouma @Hixie breaking change request!

@brianquinlan and @sun-jiao thank you for bringing this to my attention.

**Comment by grouma** [comment]
> One place in Google Ads where Cookie is implemented as part of a fake

I'm seeing a couple more locations, including some outside Ads. Overall it is < 10 and they all seem to be testing related. Should be a fairly straightforward change.

**Comment by mit-mit** [comment]
This breaking change SGTM. @vsmenon @grouma @Hixie can you approve too?

**Comment by Hixie** [comment]
fine by me

**Comment by grouma** [comment]
SGTM.

**Comment by itsjustkevin** [comment]
Calling this approved, @vsmenon please chime in if you disagree.

**Comment by sun-jiao** [comment]
Merged.

**Comment by shilangyu** [comment]
Any reason why `SameSite` is a `class` instead of an enum?
