### ISSUE TITLE
service_2/get_allocation_traces_test flaky and failing

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#51487]
There are new test failures on [[cfe] Disallow subtyping Function with class modifiers enabled....[dds/dap] Ensure variable evaluateNames are stored for all lists/fields/getters](https://github.com/dart-lang/sdk/compare/9356df41a017888bbf84189f15a4742b5d324e49~...1ce23bbd0bbb419537dc9d136aad774c9b96f4ac).

The tests
```
service_2/get_allocation_traces_test/dds RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-release-arm64
```

```
  Expected: <2>
    Actual: <1>
  

  package:test_api/src/expect/expect.dart 134:31                               fail
  package:test_api/src/expect/expect.dart 129:3                                _expect
  package:test_api/src/expect/expect.dart 46:3                                 expect
  runtime/observatory_2/tests/service_2/get_allocation_traces_test.dart 127:5  tests.<fn>
  ===== asynchronous gap ===========================
  runtime/observatory_2/tests/service_2/test_helper.dart 495:17                _ServiceTesterRunner.run.runTest.<fn>.<fn>
  ===== asynchronous gap ===========================
  runtime/observatory_2/tests/service_2/test_helper.dart 374:9                 _ServiceTesterRunner.run.ignoreLateException
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9                             Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7                             Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9                              Invoker._waitForOutstandingCallbacks.<fn>
```

[full log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8788505835392610689/+/u/test_results/new_test_failures__logs_)

I don't see an obvious commit in the range that could have caused this.
* 56b303e64b7c7d651f2d3fbda865a2ac6fa1a938, but why would that only cause issues on one architecture?
* 41be8d54b55664543f8cc18683899bb4f0bfca99, but this doesn't touch the relevant test or code.

This test is flaky in service_2 on multiple other platforms: https://dart-ci.firebaseapp.com/current_results/#/filter=service_2/get_allocation_traces_test,service/get_allocation_traces_test&showAll

cc @bkonyi

**Comment by derekxu16** [comment]
happened again: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-linux-release-arm64/1/overview

**Comment by alexmarkov** [comment]
Once again: https://dart-ci.appspot.com/log/vm-linux-release-arm64/vm-linux-release-arm64/73/service/get_allocation_traces_test/dds

**Comment by dcharkes** [comment]
This test is meta flaking a lot: https://dart-ci.web.app/#showLatestFailures=false&test=service/get_allocation_traces_test/dds

It is flaking on multiple architectures, but on on ia32 it is meta flaking between failing and flaky.

@bkonyi can we either fix this test or disable it?

**Comment by dcharkes** [comment]
Still happening.

**Comment by bkonyi** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/54487 since `service_2/` no longer exists and `service/` is in maintenance mode. However, we're still seeing flakes in the `package:vm_service` version of this test.
