### ISSUE TITLE
Runtime exception: type 'double' is not a subtype of type 'int' in type cast

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51498]
I *think* this is valid code:
```dart
void f(num val) {
  var x = val as int;
  print(x);
}
```
But when it is called as `f(1.0)` it throws the exception in the title.

Android emulator
Flutter 3.8.0-14.0.pre • channel master • git@github.com:stevemessick/flutter.git
Framework • revision dad9eb21f9 (24 hours ago) • 2023-02-22 07:16:23 +0800
Engine • revision 3aa112c75c
Tools • Dart 3.0.0 (build 3.0.0-261.0.dev) • DevTools 2.21.1

**Comment by a-siva** [comment]
//cc @alexmarkov

**Comment by mraleph** [comment]
> I _think_ this is valid code:

Yes, it is a valid code.

> But when it is called as `f(1.0)` it throws the exception in the title.

That's because `1.0` is a `double` not an `int` just like the exception says. So naturally doing `1.0 as int` fails with an exception in the title.

**Comment by a-siva** [comment]
When this code is run in DartPad no exception is generated, there is a mismatch in the implementations.

**Comment by alexmarkov** [comment]
Described in more details in https://dart.dev/guides/language/numbers.
In particular, see a subsection about types: https://dart.dev/guides/language/numbers#types-and-type-checking.

**Comment by stevemessick** [comment]
Thanks for the replies.

@alexmarkov I actually (re)read that section before submitting this issue.

@mraleph Do we have documentation about type analysis that explains why the runtime type takes precedence over the declared type? I'm confused about why a declaration of `num` is replaced by a runtime type of `double`.

**Comment by alexmarkov** [comment]
@stevemessick Type cast (`as`) and type test (`is`) always test the runtime type of their operand. It is specified in the Dart language specification (`Expressions` -> `Type Cast`). Also see https://dart.dev/guides/language/type-system#runtime-checks for an example.

**Comment by stevemessick** [comment]
Thanks @alexmarkov !
