### ISSUE TITLE
[dart2wasm] Use `struct.new` for object allocation

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#51492]
## Overview

When allocating Dart objects, we currently use `struct.new_default` to allocate the struct, then initialize its fields. This has the consequence that all fields of the struct must be defaultable and mutable.

If we instead use `struct.new`, we can use the actual nullability for reference-typed fields, and all (non-`late`) `final` fields can be immutable. Type parameter fields can be both non-nullable and immutable. This will save null checks when reading non-nullable fields and enable more optimizations in Binaryen.

## Strategy

The overall approach is to split construction of an object into two phases:
1. Compute the initial values of all fields. This involves evaluating initializers for instance fields and all constructor initializers (first subclasses then superclasses). After all values have been computed, instantiate the object with `struct.new`.
2. Execute the bodies of the constructors (first superclasses then subclasses) with `this` pointing to the constructed object.

One challenge with this approach is that parameters to constructors are available to both initializers and bodies, but arguments to super constructors must only be evaluated once. Thus, if each of the two phases are implemented via a call to super constructors, some parameters may need to be saved somewhere on the side for use in the second phase.

An alternative, which is probably the most feasible, is to inline the evaluation of initializers of superclasses into the constructors of subclasses. This way, all parameters can be saved in locals in the same Wasm function, and they can be reused when executing the bodies. The bodies need not be inlined. There can be one function for each constructor containing just the body of that constructor. The main constructor function will call the body functions for all superclasses.

## Implementation

For each constructor, we generate an additional Wasm function for the body of the constructor. We add a special reference for this in `reference_extensions.dart`.

### Constructor generation

A constructor has inputs consisting of type parameters and ordinary parameters (no receiver parameter) and a single output which is the constructed object.

- For each constructor, starting with this one and walking up the super chain (connected via the `SuperInitializer`s):
  - Set up the type environment to map the constructor type parameters to the locals containing the type arguments.
  - Perform bound checks for type parameters with covariant bounds.
  - Evaluate the initializers for all instance fields declared in the class and store the results in locals for use later.
  - Evaluate the constructor initializers. Store the results for `FieldInitializer`s in locals for use later.
    - For the `SuperInitializer`: Evaluate the arguments (including type arguments) and store them in locals. Map the parameters for the super constructor to those locals.
- For each field in the struct, push the initial value for the field. These will each we one of:
  - The class ID.
  - The identity hash code.
  - A type parameter.
  - A Dart field initialized by a constructor initializer.
  - A Dart field initialized by an initializing expression.
  - An uninitialized field, initialized to `null`.
- Instantiate the object using `struct.new`. Store it in a local.
- For each constructor, starting with the topmost superclass (except `Object`) and walking down the chain:
  - Push the new object and all arguments to the constructor (all available from locals).
  - Call the constructor body function for the constructor.
- Return the new object.

### Constructor body generation

The constructor body function has inputs consisting of a receiver and ordinary parameters (no type parameters). It has no outputs.

- Set `thisLocal` and `preciseThisLocal` to the receiver parameter
- Set up the type environment to map the constructor type parameters to the type parameter fields of the object
- Generate code for the body.

### Constructor call

- Push the arguments (including type arguments).
- Call the constructor function.

## Discuss

@osa1 @joshualitt WDYT?

**Comment by joshualitt** [comment]
This sounds good to me!

It sounds like this approach could involve a bit more work up front, but the constructed objects could potentially be more efficient?

**Comment by osa1** [comment]
Makes sense to me, I had suggested the same thing a while ago, in chat. It's wasteful to do a null check on every access when we know that the field can't be null.

As far as I understand there are three parts in an initialization, in evaluation order:

1. Field initialization using the parameters passed to the constructor and the default values. (`Class.fields` initializers, which can be arbitrarily large expressions IIUC)
2. The initializer list (the part after `:` in a constructor, `Initializer` in kernel). These initializers can't refer to fields, but they can use parameters and call super constructors.
3. The constructor body. This is like an ordinary Dart function, assumes `this` initialized.

With this idea, (1) and (2) need to be done before we can allocate the Wasm struct. AFAIU the implementation you describe generates a function for (1) and (2) per constructor. (3) calls the function for (1) and (2) for superclasses and then for the class it's constructing.

Did I get this right?

> One challenge with this approach is that parameters to constructors are available to both initializers and bodies, but arguments to super constructors must only be evaluated once. Thus, if each of the two phases are implemented via a call to super constructors, some parameters may need to be saved somewhere on the side for use in the second phase.

I'm confused. Parameters are already passed in Wasm locals, why do you need extra saving? I think you mean return values of the functions that do (1) and (2), right?

Could we use multiple returns for this? Initializer functions (the functions that do (1) and (2)) can return the field values, as multiple values. The call site in (3) can then re-order them before `struct.new`.

> An alternative, which is probably the most feasible, is to inline the evaluation of initializers of superclasses into the constructors of subclasses. This way, all parameters can be saved in locals in the same Wasm function, and they can be reused when executing the bodies. The bodies need not be inlined. There can be one function for each constructor containing just the body of that constructor. The main constructor function will call the body functions for all superclasses.

This may be fine, but initializers can be arbitrarily large expression, so code size may be a problem.

**Comment by askeksa-google** [comment]
> 1. Field initialization using the parameters passed to the constructor and the default values. (`Class.fields` initializers, which can be arbitrarily large expressions IIUC)

This phase actually only encompasses the `Class.fields` initializers. Initialization from constructor parameters is done via the initializer list in step (2).

> With this idea, (1) and (2) need to be done before we can allocate the Wasm struct. AFAIU the implementation you describe generates a function for (1) and (2) per constructor. (3) calls the function for (1) and (2) for superclasses and then for the class it's constructing.
> 
> Did I get this right?

Almost. My suggestion is, for each constructor, to generate a *constructor function* that does (1) and (2) for this constructor and all super constructors (inlined into one Wasm function) plus a *constructor body function* that does (3) for only this constructor. After allocating the object, the constructor function calls the constructor body functions for all super constructors and itself.

> I'm confused. Parameters are already passed in Wasm locals, why do you need extra saving? I think you mean return values of the functions that do (1) and (2), right?

This is probably best illustrated by an example:
```dart
int _x = 0;

int get nextX => ++_x;

class A {
  final int y;
  List<int>? l;

  A(int z) : y = z * 2 {
    l = [z * 3];
  }
}

class B extends A {
  B() : super(nextX);
}

class C extends B {
  C() : super();
}

main() {
  final c = C();
  print("${c.y} ${c.l?.single}");
}
```
Here, the `z` parameter to the `A` constructor is used twice: in the initializer list for initializing `y` and in the body for initializing `l`. The value passed into `z` by the `B` constructor is computed by the expression `nextX`, which has side effects.

Now, consider construction of `C` in a scenario where we have implemented the constructor via two functions that only handle the constructor itself:
- An *initializer function* that performs (1) and (2) for this constructor, calls the initializer function for the super constructor (which will return field values for the superclass) and then appends its own field values and returns the combined field values.
- A *body function* which calls the body function for the super constructor and then executes the body of the constructor.

When we get to the point where the body function for the `B` constructor needs to call the body function for the `A` constructor, it needs to pass the value for the `z` parameter, since it is needed in the body of the `A` constructor. However, that value was computed in the initializer function for the `B` constructor and thrown away when that function returned. If we compute the value again, the program will give the wrong result (it will print `2 6` instead of `2 3`).

> Could we use multiple returns for this? Initializer functions (the functions that do (1) and (2)) can return the field values, as multiple values. The call site in (3) can then re-order them before `struct.new`.

This is what I tried in my first design, until I hit the issue with the parameters.

It would be possible to make the initializer functions return both the field values and super constructor arguments (or better, some selected subset of them that can't be trivially recomputed), though I think that could quickly get quite messy. TBH, I'm also a bit worried that using a huge number of return values could cause both Binaryen and the engine to choke and do something not very efficient.

> This may be fine, but initializers can be arbitrarily large expression, so code size may be a problem.

Indeed. We need to check whether this generates reasonable code in practice. The worst case is if some class has a lot of fields and a lot of subclasses, causing a quadratic blowup. However, in practice, I think that in such a situation, the subclass constructors will typically have many parameters in the first place (at least this is what many Flutter widget classes look like), so it's kind of already blown up.

For the initializing expressions for instance fields, we could choose to put them into shared functions whenever they are non-trivial, which could avoid some of the duplication, even compared to the current situation, where we duplicate the expressions for every constructor.

**Comment by osa1** [comment]
> When we get to the point where the body function for the B constructor needs to call the body function for the A constructor, it needs to pass the value for the z parameter, since it is needed in the body of the A constructor. However, that value was computed in the initializer function for the B constructor and thrown away when that function returned. If we compute the value again, the program will give the wrong result (it will print 2 6 instead of 2 3).

Right.. this is tricky. So basically (3) needs values generated by the combination of (1) and (2) in a previous initialization step.

I don't know how much of this is standard (instead of implementation), but I tweaked the example a little bit to print evaluated order of field default values, initializer lists, and constructor bodies:

<details>

<summary>Initialization and constructor evaluation order test</summary>

```dart
int _x = 0;

int get nextX => ++_x;

class A {
  final int aField = (() {
    print("Initialize A.aField (field)");
    return 123;
  })();
  final int y;
  List<int>? l;

  A(int z)
      : y = (() {
          print("Initialize A.y (initializer)");
          return z * 2;
        })() {
    print("A constructor");
    l = [z * 3];
  }
}

class B extends A {
  final int bField = (() {
    print("Initialize B.bField (field)");
    return 123;
  })();
  final int z;
  B()
      : z = (() {
          print("Initialize B.z (initializer)");
          return 1;
        })(),
        super(nextX) {
    print("B constructor");
  }
}

class C extends B {
  final int cField = (() {
    print("Initialize C.cField (field)");
    return 123;
  })();
  final int t;
  C()
      : t = (() {
          print("Initialize C.t (initializer)");
          return 2;
        })(),
        super() {
    print("C constructor");
  }
}

main() {
  final c = C();
  print("${c.y} ${c.l?.single}");
}
```

</details>

Output: (comments mine)

```
Initialize C.cField (field)
Initialize C.t (initializer)
Initialize B.bField (field)
Initialize B.z (initializer)    // value generated here ...
Initialize A.aField (field)
Initialize A.y (initializer)
A constructor                   // ... need to be passed here
B constructor
C constructor
```

When the "field" and "initializer" lines above done in the same function and "constructor" lines in separate functions, the value for `z` generated by the code that initializes `B` to `A`'s constructor.

Your alternative of inlining initialization steps solves this by introducing locals for initializer arguments and passing them to the constructor functions.

With initializers as separate functions, initializers need to return values passed to `super(...)` so that you can pass them to the constructors after the initializers run. I may be missing some details but this doesn't seem difficult to implement. `super(...)` calls are syntactically explicit (with their own AST nodes) so we could easily make initializer functions return the values they pass to `super(...)`. We can name those return values in the call site, pass them to constructors in the same order.

Also, initializer for a constructor need to return all passed to superclasses, transitively. E.g. if `C` initializes `B` which initializes `A`, `C`'s initializer function need to return values passed to `A`'s initializer followed by values passed to `B`s initializer.

I have no idea re: multiple returns preventing optimizations.

Assuming I'm not missing anything and implementation is not too difficult, we have two options:

- One Wasm function per initialization:
  - (+) No code duplication
  - (-) Uses multiple returns, potentially returns large number of values

- Every constructor inlines `super` initializers:
  - (+) No multiple returns, Wasm locals used to pass values around
  - (-) Code duplication, initialization of a field will be duplicated in every constructor that initializes the field

**Comment by osa1** [comment]
So I guess the main question is how costly is multiple returns. If it is costly, then inlining initializers makes sense. If not, leaving inlining decisions to the optimization step might make more sense.

**Comment by askeksa-google** [comment]
It would make sense to implement the non-duplicating version and then experiment with the inlining heuristics for our internal inliner to see what the effect would be of inlining the initialization functions.

If we do it like this, we should optimize it such that it only preserves super arguments that actually need to be preserved. A simple, conservative criterion for this is that both of the following are true:
- The expression is not trivial, i.e. it's neither a `BasicLiteral`, a `ConstantExpression` nor a `VariableGet`.
- The super constructor body is not empty.

It turns out that this is an extremely rare situation, only occurring [once](https://github.com/flutter/flutter/blob/19b2aa14c08fdef829c1f09e2f964454147defeb/packages/flutter/lib/src/material/material_state.dart#L745) in all of Flutter. And in that case, the super constructor body doesn't even use the value.

**Comment by osa1** [comment]
> we should optimize it such that it only preserves super arguments that actually need to be preserved

We could also check the free variables in constructor bodies. Only the free variables need to be passed.

---

This change will also allow storing non-nullable fields as unboxed. That's not always beneficial (use sites may have to allocate a boxed value), but for the cases when we know that won't happen we can implement a new pragma `@pragma("dart2wasm:unbox")` that stores the field unboxed.

This can be used to improve bound checks by marking `_ListBase._length` as "unbox". Use sites of `length` getter won't be any worse as `length` already returns `i64` today, so it null-checks and unboxes the field. Bound checks in `[]` etc. will be able to use the field without doing the same.

**Comment by askeksa-google** [comment]
Non-nullable fields with types that translate to numeric Wasm types (e.g. `bool`, `int`, `double`, `Pointer`) are already unboxed. Only reference types are forced nullable, since the requirement is just that the field types are defaultable, and numeric types are always defaultable.

**Comment by askeksa-google** [comment]
> We could also check the free variables in constructor bodies. Only the free variables need to be passed.

Yes. We can compute the parameters needed for a body function inductively like this:
- The `Object` constructor body function needs no parameters.
- Any other constructor body function needs:
  1. The variables used in its body
  2. The dependencies for the parameters needed by the super constructor body function (when the super constructor argument is a `VariableGet`)
  3. The computed values for the non-trivial arguments to its super constructor for parameters needed by the super constructor body function
  4. The computed values for the non-trivial arguments to all super constructors higher up (to pass on)

Note that (i) and (ii) can overlap.

**Comment by askeksa-google** [comment]
Yes, I agree that we should try to keep object allocation to one allocation.

One obstacle to note on the strategy discussed in this issue:

If the Dart program contains a cycle through non-nullable fields, the Wasm representation will similarly have a cycle through non-nullable fields. Such a struct can never be constructed. This may pose a problem is cases where we want to produce a dummy value for a Wasm type. So we need to either break such cycles by making some of the fields nullable, or somehow avoid needing dummy values for such types.

We do need one particular cycle, though:

The constant for the empty list of `_Type` (i.e. `const <_Type>[]`) has a type argument field which points to the interface type object for `_Type`. The interface type object for `_Type` has a list of type arguments which is the empty list of `_Type`. We currently handle this by initializing the type argument field of the empty list of `_Type` to `null` and then setting it later, in the module init function. 

Both of the fields that point to each other would be immutable with the new approach. We need to make one of them mutable in order to be able to construct the cycle. We should be able to keep them non-nullable, though.
