### ISSUE TITLE
Lock down the no-sound-null-safety option in the compiler

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#51513]
The option of completely dropping support for unsound null safety in the Dart SDK as a build time option was explored in https://github.com/dart-lang/sdk/issues/50348, looks like this option needs to wait until all Flutter code internally is migrated to be null safe.

As an alternative we will lock down the option to pass --no-sound-null-safety option in the `compile` command (both kernel and aot) and the `run` command will run in unsound mode when the input file is a kernel file or AOT snapshot compiled using the unsound option.

**Comment by a-siva** [comment]
Here is a CL that does some of this https://dart-review.googlesource.com/c/sdk/+/284900

**Comment by vsmenon** [comment]
@bkonyi - I think you're point on this?  Please let me know if not.  :-)

**Comment by bkonyi** [comment]
> @bkonyi - I think you're point on this? Please let me know if not. :-)

I am, and this should be resolved by [a569f4a](https://github.com/dart-lang/sdk/commit/a569f4a5409bcb9755532099ed1c09811b970c1d) :-)
