### ISSUE TITLE
[Patterns] Debugger seems to show some internal implementation variables

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#51512]
When debugging an app which uses patterns we seem to show synthetic variables.
The vm service has a way of filtering synthetic variables and it appears that these variables are not following that pattern.

See image below for an example :
![image](https://user-images.githubusercontent.com/8633293/221048259-a3da5c6b-956c-429f-a063-aff25e12e704.png)

**Comment by a-siva** [comment]
//cc @alexmarkov @bkonyi @derekxu16 @stevemessick

**Comment by stevemessick** [comment]
Thanks @a-siva ! FWIW I have also seen synthetic variables that begin with a single `#`.

**Comment by a-siva** [comment]
> Thanks @a-siva ! FWIW I have also seen synthetic variables that begin with a single `#`.

The VM has code to filter out names that start with ':', the '#' and '##' patterns is new, Alex is going to chat with the CFE team and figure out a consistent pattern for these synthetic variables so that they are filtered out.

**Comment by alexmarkov** [comment]
This is blocked on https://github.com/dart-lang/sdk/issues/51554. Once front-end introduces a proper way to distinguish synthetic variables,  we would be able to filter those variables in the VM/debugger.
