### ISSUE TITLE
FFI transformation creates an incorrect AST for Finalizable late local variable

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51511]
Example:

```dart
import 'dart:ffi';

class Foo implements Finalizable {}

void main() {
  late Foo foo;
  foo = Foo();
  print(foo);
}
```

Kernel before `transformLibraries` from pkg/vm/lib/transformations/ffi/use_sites.dart:
```
  static method main() → void {
    late bar::Foo foo;
    foo = new bar::Foo::•();
    core::print(foo);
  }
```

Kernel after the transformation:
```
  static method main() → void {
    late bar::Foo foo;
    foo = block {
      final bar::Foo :expressionValueWrappedFinalizable = new bar::Foo::•();
      _in::reachabilityFence(foo);
    } =>:expressionValueWrappedFinalizable;
    core::print(foo);
    _in::reachabilityFence(foo);
  }
```

Note that inserted `_in::reachabilityFence(foo);` reads late variable `foo` before it is initialized.
Any attempt to read a late variable before it is initialized results in an exception, so further optimizations can reduce this to
```
  static method main() → void {
    late bar::Foo foo;
    foo = block {
      final bar::Foo :expressionValueWrappedFinalizable = new bar::Foo::•();
      foo;
      throw 'Unreachable';
    } =>:expressionValueWrappedFinalizable;
  }
```

We should produce correct kernel AST after the FFI transformation and should not require all optimization passes after FFI transformation to recognize and specially handle `reachabilityFence`.

This bug blocks landing the improvement in TFA which would enable the optimization mentioned above.

@dcharkes

**Comment by dcharkes** [comment]
The transformation does not have access to variables in scope from the CFE as that information is (or was) transient in the CFE. So it builds its own scopes:

https://github.com/dart-lang/sdk/blob/262efd84fd2b14cf64dfa6c937856d717fbe6e1e/pkg/vm/lib/transformations/ffi/finalizable.dart#L41

The knowledge about scopes does not require any flow analysis.

Knowing when late variables are initialized would require adding control flow analysis. (It seems smelly that this transform would have to redo all the logic that's already done in other places in the CFE/TFA. Could we somehow reuse existing logic?)

However, adding control flow analysis is not enough, consider:

```dart
void foo() {
  late Finalizable a;
  if (currentTimeInMilliseconds % 2 ==0) {
    a = MyFinalizable();
  }
  // potentially do something with `a`s native resource.
  return;
}
```

Now, this would need a fence on `a` before the `return` if it was initialized, but _not_ if it wasn't initialized.
I'm not sure how we would achieve this without it being a runtime decision. (Runtime decision was implemented in e418026d74b6c666a7fcb30278a2b10ed97fdb29).

I'm open to suggestions. Any bright ideas @alexmarkov ?

**Comment by dcharkes** [comment]
> Late variables have runtime semantics which cannot be predicted at compile time (in general case). So I'm not sure what kind of control flow analysis do you mean.
> 
> We can detect that late variable is initialized by introducing another `bool v$initialized = false;` variable for each late variable `v` and then rewrite assignment to `v` to also set `v$initialized` to `true`. After that, reachability fence can be guarded: `if (v$initialized) reachabilityFence(v)`.

That would work indeed.

> However, there is a simpler solution, based on the following observation: we don't really need to keep reachable late variable, we need to keep reachable its _value_. So, in order to avoid complicated runtime semantics of late variables, for each late variable `late T v` we can introduce another variable `T? v$value;` and rewrite assignment `v = expr` as `v$value = (v = expr)`. After that, we can maintain reachability of its value using `reachabilityFence(v$value)`. Note that `v$value = (v = expr)` should be used instead of `v = (v$value = expr)` because in the latter case assignment to `v` might not happen at runtime if `v` is `late final` and was already assigned.

Right, if every assignment to the late variable also assigns to the non-late nullable copy, it should indeed be enough to have a reachability fence on that copy.

We should double check how easy it would be to avoid using two locations and two assignments in the compiler further on. This might regress code/size and register pressure around finalizables.

Would you like to make the necessary changes @alexmarkov ? Then you can immediately test your TFA improvement on top of it.
Otherwise I can take a look next week and send a CL to you. Then the tests would rely on CFE expect files.

> We should produce correct kernel AST after the FFI transformation and should not require all optimization passes after FFI transformation to recognize and specially handle reachabilityFence.

Agreed. 👍  (Maybe unless we cause significant regressions by requiring two variables instead of one.)

**Comment by alexmarkov** [comment]
I don't think introducing an extra local variable would make any difference in code size or performance, unless it is captured. Finalizable late local variables are very rare, so it shouldn't matter even if there is an extra overhead.

> Otherwise I can take a look next week and send a CL to you.

Sgtm. You can also test the fix against https://dart-review.googlesource.com/c/sdk/+/285061 (`language/vm/regress_49005_test` and `pkg/vm/test/transformations/ffi_test` are currently failing).

**Comment by dcharkes** [comment]
Part 2 in progress: https://dart-review.googlesource.com/c/sdk/+/287460
