### ISSUE TITLE
Failures on Enable the fallback exhaustiveness algorithm (with improvements).

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51522]
There are new test failures on [Enable the fallback exhaustiveness algorithm (with improvements).](https://dart-review.googlesource.com/c/sdk/+/284840).

The tests
```
co19/LanguageFeatures/Patterns/execution_pattern_assignment_A01_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Patterns/execution_switch_statement_A02_t02 RuntimeError (expected Pass)
```
are failing on configurations
```
ddc-linux-chrome
ddc-linux-chrome-unsound
```

**Comment by nshahan** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/51519.
