### ISSUE TITLE
Analyzer - Plugins not running after Dart sdk version 2.19.2

### ISSUE THREAD

**Issue by GabrielCR99** [dart-lang/sdk#51539]
* What you were doing:
    I'm trying to use dart_code_metrics plugin in a project that has analysis_options.yaml on it. It also includes package flutter_lints in the analysis file.
* What occurred:
    In the "Plugins" tab when you go to the Analyzer Diagnostics, the following error is showing: 
![image](https://user-images.githubusercontent.com/42328188/221420699-3a737331-f6e0-40bc-bf5f-117cac277b67.png)

* What you think the expected behavior should have been:
    Analyzer should start dart_code_metrics normally

Other data to include:
*The IDE you are using and its version (VS-Code, 1.75.1)
*The Dart SDK version (2.19.2)
*Your operating system (Windows 11)

**Comment by bwilkerson** [comment]
@srawlins @jacob314

**Comment by incendial** [comment]
@GabrielCR99 hey, DCM author here - the title says `after Dart sdk version 2.19.2`, so before it worked for you well and stopped after the SDK upgrade, right? Just trying to narrow down the possible place where the problem is.

**Comment by GabrielCR99** [comment]
Hey there @incendial! I remember that this error actually happened when i updated flutter and dart version and after the update, I did a `flutter pub cache clean``. This is actually very weird, as it seems that it already occured in the past, when I opened an issue in DCM repository (https://github.com/dart-code-checker/dart-code-metrics/issues/737). Even weirder, on my notebook (Windows 10), it's running normally, with no errors. 
![image](https://user-images.githubusercontent.com/42328188/221434279-f9c8d573-12e7-43f7-be50-78dabba148d7.png)


Sadly, I don't know how to check for a more verbose error in the analyzer. Maybe it's somethings with the cache?

**Comment by incendial** [comment]
One option would be to try deleting the `.dartServer/.plugin_manager` folder (it's basically a cache, so it won't affect anything else) and then restarting the IDE, but I'm not 100% sure that would help.

**Comment by GabrielCR99** [comment]
It worked like a charm @incendial! Many thanks, as always helping me out in analyzer diagnostics 😄 I'm going to close this issue since you helped me solve it.

![image](https://user-images.githubusercontent.com/42328188/221451836-8f166fb1-5140-4b3f-9ab8-fc2cf14504fe.png)
