### ISSUE TITLE
[Suggest a feature] Add index and list as parameters to the list methods.

### ISSUE THREAD

**Issue by titoworlddev** [dart-lang/sdk#51530]
Hello, I've been using Dart for a long time and now I was thinking that the list methods are quite lazy... That is to say, they're good because it helps with the use of such lists, but it's very heavy because every time you want to use a index when you had already created your code with a forEach(), with a map(), with a reduce(), etc, you have to transform that code into a for loop in order to make use of the index. 
All of this is a fairly large waste of time which would be solved by adding the index and the list as function parameters of the list methods and that, for example, you have codes like the following.

```dart
void main() {
  List<String> elements = ['Element', 'Element', 'Element', 'Element'];

  // elem = Element of the list
  // index = Index of the element
  // list = List (elements in this case)
  elements.forEach((elem, index, list) {
    print('$elem #$index');
  });

  elements.map((elem, index, list) {
    return print('$elem #$index');
  });

  List<int> numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  numbers.reduce((total, current, index, list) {
    print(list[index]);
    return total + current;
  });

}
```

And so with all the methods that use cycles in the lists. It would be a great help and a good addition to dart.

**Comment by incendial** [comment]
Have you tried the [collections package](https://pub.dev/packages/collection)?
It provides nice extensions like [forEachIndexed](https://github.com/dart-lang/collection/blob/master/lib/src/list_extensions.dart#L120) and looks like it's exactly what you're looking for.

**Comment by mraleph** [comment]
This is available through package `package:collection` as @incendial points out. 

Changing signatures of these methods on `Iterable` and `List` is non starter because it is going to break a lot of code.

**Comment by titoworlddev** [comment]
Are you really telling me to use a package for this? I can not believe it...

Also, I don't know what you're saying that this can break a large amount of code, it's about adding something new, not modifying what's already there.

It seems painful to me that they make me use a package when there are languages that already have it implicit.

It's about making the language more versatile and simple, not that you have to be looking for packages for such primary functions.

And on top of that you close the issue... I see that there is no desire to work to improve.
