### ISSUE TITLE
[vm/ffi] `@Native` assets `relative` path resolution

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#51546]
`@Native external` functions can have a `relative` path as per 9a8508ebff21dc6e701f453a11be2309ef771c53.
This relative path is relative to `Platform.script`.

However, we're not handling this in the VM consistently with with `Platform.script` in Dart.

In Dart, `Platform.script` always returns a fully resolved absolute path. If no schema was provided on entry, the path is resolved in the current working directory. If a schema is provided, `Uri.parse` is used to parse this.

In the VM we currently only have access to the path before "resolve relative to current working dir" or `Uri.parse`.

So we either need to (1) duplicate the logic in Dart for resolution in C++ in the VM, or (2) load `Platform.script` by entering Dart code rather than resolving in the VM.

Relevant resolution logic:

https://github.com/dart-lang/sdk/blob/9a6c8ed50b096810b155c09cda6e174d7d12a8db/sdk/lib/_internal/vm/bin/platform_patch.dart#L54-L68

Relevant plumbing:

https://github.com/dart-lang/sdk/blob/9a6c8ed50b096810b155c09cda6e174d7d12a8db/runtime/bin/main_impl.cc#L198

This sets the commandline argument passed as script, and this is what we have available in the VM.

Things to consider:

1. The embedder is responsible for managing `Platform.script`.
     However, we always do this scheme-check+`Uri.parse` or `Uri.base.resolve`.
2. Entering Dart code to invoke `Platform.script` might require compiling new Dart code (in JIT).

I believe reason 2 is why we didn't go for approach (2) in the initial CL (but I can't find the relevant discussion anymore).

Approach 1, implementing the same logic in the VM as in `_nativeScript` leads to unfortunate code duplication, but it avoids the issue of trying to execute Dart code while compiling Dart code. (With eager resolution of FFI `@Native`s we want to do the resolution in the compiler.)

FYI @mkustermann

**Comment by mkustermann** [comment]
A couple of thoughts here:

> @Native external functions can have a relative path as per 9a8508e.
> This relative path is relative to Platform.script.

It is what we define it to be.

The `Platform.script` API is in `dart:io`. There may be embedders that want to use FFI but not `dart:io`.  We can define that native libraries with relative paths are resolved relative to the isolate group's script uri, or we could ask the embedder via callback to resolve it (or even load it).

> ... duplicate the logic in Dart for resolution in C++ ...

It seems that the Dart code simply ensures that it's an absolute uri (using cwd to resolve relative paths). That in itself is not implemented correctly as it doesn't even guarantee to always answer the same thing, see https://github.com/dart-lang/sdk/issues/51559

> This sets the commandline argument passed as script, and this is what we have available in the VM.

This is also less than ideal, due to the need to have extra C++ -> Dart calls on isolate initialization - which increases startup latency.

**Comment by dcharkes** [comment]
> We can define that native libraries with relative paths are resolved relative to the isolate group's script uri

In JIT that is.

In AOT, it will be relative to ... the final executable (except on Android because the JVM is the exectuable?)
So far, I've been using absolute paths in AOT and ensuring that the folder with dylibs is in the PATH/LD_PATH etc.

> or we could ask the embedder via callback to resolve it (or even load it).

That would also address

* https://github.com/flutter/flutter/issues/59834

But then the embedders need to know about the 5 types of paths (system, process, absolute, relative, executable).

I need to think a bit about whether "relative" even makes sense in AOT.

**Comment by dcharkes** [comment]
> I need to think a bit about whether "relative" even makes sense in AOT.

It makes sense as long as the file that contains the mapping is the reference point.

If running from an AOT-snapshot, the relative path should be relative to to the AOT snapshot.
If the AOT-snapshot is appended to the dartaotruntime, the dartaotruntime should be used for relative path resolution.

On Android, we will always load an aotsnapshot, so we should have a path for that.

**Comment by dcharkes** [comment]
Some notes from offline discussion:

* What to do with 'relative' when the embedder provides kernel by pushing in memory? And there is no path at all to resolve 'relative' to?
  * Option 1: dlopening should be done by the embedder. (Then we don't even have to settle on 'relative', 'absolute', 'system', 'process', 'executable', the embedder could define its own tags.) The Flutter embedder could decide to dlopen relative to libflutter.so rather than the `.dart`/`.dill`/`.aotsnapshot` file for example.
  * Option 2: embedders should not use 'relative' in the native assets mapping if there is nothing to resolve relative to at all.
* When using static linking or dynamic linking (instead of dynamic loading), there is no resolution at runtime, there is resolution at link-time by the embedder.
  * Then a plain path should be provided that the native-linker can consume. We could use 'system' or 'relative' for that, or define a new tag to declare such kind of path.
