### ISSUE TITLE
[iOS]: File system watching is not supported on this platform

### ISSUE THREAD

**Issue by JaffaKetchup** [dart-lang/sdk#51549]
Continuation of https://github.com/flutter/flutter/issues/99456, due to https://github.com/flutter/flutter/issues/99456#issuecomment-1216982651. This has recently been re-reported on my package (PR at https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/110, but I'll use a different method instead), so the situation remains pretty much the same. 

> I'm getting File system watching is not supported on this platform, path = '' error trying to use Directory.watch on flutter.
I am using Mac Big Sur 11.2.3. M1
Does anyone know why? Please let me know. Thanks.

This issue was accepted in https://github.com/flutter/flutter/issues/99456#issuecomment-1062574452, then closed as it is more suitable for this repo.

**Comment by a-siva** [comment]
We use the underlying FSEventStreamFileSystemWatcher to implement file system watching in Dart and this API is only available on macOS and is not supported on iOS.

**Comment by JaffaKetchup** [comment]
@a-siva In that case, this should be considered a feature request. See https://pub.dev/packages/dispatch_source_watcher, which claims to use the https://developer.apple.com/documentation/dispatch/dispatchsource iOS API to achieve the same result. Additionally, the docs could do with more clarification.

**Comment by JaffaKetchup** [comment]
I have updated the title accordingly, I'd appriciate if this could be re-opened.

**Comment by a-siva** [comment]
We could consider adding the feature but a cursory reading of the dispatch source API on iOS makes it sound like there are some limitations which would make it not possible to exactly match what we have on other platforms.

One question are you not able to use package:dispatch_source_watcher in your app to get the same functionality?

**Comment by JaffaKetchup** [comment]
@a-siva Its a package, so whilst I could include it, minimal dependencies (yeah, code shaking does size, but it's not all about that) and 'ensured maintenance' and all that sort of stuff.
I would offer my help, but I have no experience with iOS development, so I won't be of any use.
If this can't be incorporated into Dart for some reason, I think that it should be at least mentioned on the docs, and suitable alternatives listed.
Note that the official 'watcher' package resorts to a polling watcher if there is no system watcher. Even this behaviour would be preferable (of course, once documented).

**Comment by a-siva** [comment]
//cc @devoncarew for your opinion regarding adding support in the 'watcher' package
