### ISSUE TITLE
Using ```auto_route_generator``` with ```analyzer ^v5.2.0``` causes a bug.

### ISSUE THREAD

**Issue by Yokoi-K** [dart-lang/sdk#51542]
## Apology

The same issue was created on the ```auto_route``` side.
But I didn't get any replies, so I created another one here.

↓This is same issue.
https://github.com/Milad-Akarie/auto_route_library/issues/1355

## Summary

I have created the following PR to help explain the differences.
Look at Files changed.

https://github.com/Yokoi-K/flutter_analyzer_auto_route_test/pull/1

The bug I found is that function type is ```dynamic``` .

### Using analyzer v5.1.0

```onPressed is VoidCallback.```

```dart
class SubRoute extends _i3.PageRouteInfo<SubRouteArgs> {
  SubRoute({
    _i4.Key? key,
    required void Function() onPressed,
  }) : super(...),
        );
  static const String name = 'SubRoute';
}
```

### Using analyzer ^v5.2.0

```onPressed is VoidCallback.```

```dart
class SubRoute extends _i3.PageRouteInfo<SubRouteArgs> {
  SubRoute({
    _i4.Key? key,
    required dynamic onPressed,
  }) : super(...),
        );
  static const String name = 'SubRoute';
}
```

## Help

Can you solve this problem?
Please help me as I am having trouble.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by ookami-kb** [comment]
Happens to me as well in analyzer 5.4.0.
