### ISSUE TITLE
Cannot determine type signature of `Map` and `List` instances using `InstanceRef`

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#51550]
> Note: This is an inconsistency between `package:dwds` and the `vm_service`. Opening here instead of in `package:dwds` because the `vm_service` is providing less information. 

When using `DWDS`, DevTools can determine the type signature of a `Map` or `List` instance using `classRef.name`. For `vm_service`, there is no type signature. 

Compare DWDS, which returns `IdentityMap<String, String>`:

![Screenshot 2023-02-27 at 12 33 31 PM](https://user-images.githubusercontent.com/21270878/221680864-00fb9f55-42c3-417d-9560-842227873d4a.png)

To `vm_service`, which returns `_Map`.

![Screenshot 2023-02-27 at 12 46 47 PM](https://user-images.githubusercontent.com/21270878/221682111-c667093d-3039-451d-a9d1-5da8152efc28.png)

FYI @bkonyi

**Comment by bkonyi** [comment]
I'm not sure this is a bug as the type parameters should be be made available through the `typeParameters` property.

**Comment by elliette** [comment]
> I'm not sure this is a bug as the type parameters should be be made available through the `typeParameters` property.

Oh interesting. It seems like those are `null`:
![Screenshot 2023-02-27 at 12 55 03 PM](https://user-images.githubusercontent.com/21270878/221683503-683dbcb4-d077-494d-a180-5880fa331d44.png)

**Comment by bkonyi** [comment]
Are they? The original screenshot from the VM target has two.

**Comment by elliette** [comment]
Ah got it, the `typeParameters` of the `classRef` not the `instanceRef`. Thanks!
