### ISSUE TITLE
[Inline classes] Report error on implements non-inline class

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#51564]
Consider the following:

```dart
// Dart SDK version: 3.0.0-edge.0c32c7fc6295f329b8d8d74f640bdd77b0058c13 (be) (Fri Feb 24 07:45:06 2023 +0000) on "macos_arm64"
// ./dart run --enable-experiment=inline-class x.dart
void main() {
  print(0.foo());
}

abstract class Foo {
  int get t;
}

extension on int {
  Foo foo() => _FooImpl(this);
}

inline class _FooImpl implements Foo {
  final int t;

  const _FooImpl(this.t);
}
```

This fails to compile with:

```
Error: A value of type '_FooImpl' can't be returned from a function with return type 'Foo'.
 - 'Foo' is from 'package:foo/bar.dart' ('...').
  Foo foo() => _FooImpl(this);
```

If we remove the inline keyword then the program compiles as expected.

I'm wondering, is this a limitation of inline classes or is the experiment just not ready yet?

**Comment by lrhn** [comment]
It's a limitation of inline classes. They cannot implement class interfaces, because an interface method is late-dispatch and inline classes are static-dispatch.

The `implements Foo` should be an error.
