### ISSUE TITLE
Dart Analyzer keep crashing

### ISSUE THREAD

**Issue by tlvenn** [dart-lang/sdk#51561]
The Dart Analyzer invoked through VS Code LSP keep crashing on me, the log shows:

```
{"id":4,"jsonrpc":"2.0","error":{"code":-32800,"message":"Request was cancelled"}}Content-Length: 4964
Content-Type: application/vscode-jsonrpc; char…
[19:30:06] [Analyzer] [Info] <== {"id":13,"jsonrpc":"2.0","result":[{"endLine":19,"kind":"imports","startLine":0},{"endLine":44,"startLine":24},{"endLine":43,"startLine":26},{"endLine":42,"startLine":27},{"endLine":41,"startLine":28},{"endLine":36,"startLine":31},{"endLine":35,"startLine":33},{"endLine":40,"startLine":37},{"endLine":70,"startLine":46},{"endLine":69,"startLine":48},{"endLine":68,"startLine":49},{"endLine":67,"startLine":53},{"endLine":66,"startLine":55},{"endLine":65,"startLine":58},{"endLine":63,"startLine"…
[19:30:06] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"macos","name":"macOS","platform":"darwin","emulator":false,"category":"desktop","platformType":"macos","ephemeral":false,"emulatorId":null,"sdk":"macOS 13.3 22E5219e darwin-x64","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":false,"flutterExit":true,"hardwareRendering":true,"startPaused":true}}}]
[19:30:06] [General] [Info] Returning cached results for project search
[19:30:06] [General] [Info] Checking 1 projects for supported platforms
[19:30:06] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/tlvenn/workspace-ariane/livetrader"}}]
[19:30:06] [Analyzer] [Error] Unhandled exception:
Null check operator used on a null value
#0      MethodInvocationResolver._resolveReceiverSuper (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:693:21)
#1      MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:121:7)
#2      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:285:31)
#3      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resol…
[19:30:06] [Analyzer] [Info] Spawning /usr/local/Caskroom/flutter/3.7.5/flutter/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.58.0"]
[19:30:06] [Analyzer] [Info]     PID: 86697
```

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.3 22E5219e darwin-x64, locale en-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by pq** [comment]
Looking at `method_invocation_resolver` it looks like `enclosingClass` is null?

```dart
    var target = _inheritance.getMember2(
      enclosingClass!,
      _currentName!,
      forSuper: true,
    );
```


/fyi @scheglov

**Comment by tlvenn** [comment]
I should add the analyzer only crash on a given project, I can reproduce it on the other dart / flutter projects I have.

**Comment by tlvenn** [comment]
There is some additional piece of env in the log in case it's helpful

```
Dart Code extension: 3.60.1
Flutter extension: 3.60.0 (activated)

App: Visual Studio Code
Version: 1.76.0
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /usr/local/Caskroom/flutter/3.7.5/flutter/bin/cache/dart-sdk
    Ver: 2.19.2
Flutter SDK:
    Loc: /usr/local/Caskroom/flutter/3.7.5/flutter
    Ver: 3.7.5
```

**Comment by incendial** [comment]
@tlvenn hey, looks like there is a specific class with a method in your code that leads to this error. Is your project big? Any chance you can try to find the code causing this? It would really help.

**Comment by scheglov** [comment]
Yes, an example of code, or even a longer stack trace would be useful.
I see that we have a method invocation, that has `super` as a target.
But without more details, where it is is invoked, I was not able to reproduce it.

**Comment by tlvenn** [comment]
This is a rather big project unfortunately. Is there any way I can debug the analyser and have a breakpoint that would provide the context we need ?

How I can produce a longer stack trace ? Is there a way to invoke the analyser the same way the LSP does ? if I try `dart analyse` it works without any glitch...

Definitely willing to dig but would be helpful to get directions on how to proceed.
Thanks in advance.

**Comment by tlvenn** [comment]
I was able to capture the full stack trace:
```
Null check operator used on a null value
#0      MethodInvocationResolver._resolveReceiverSuper (package::analyzer/src/dart/resolver/method_invocation_resolver.dart::693::21)
#1      MethodInvocationResolver.resolve (package::analyzer/src/dart/resolver/method_invocation_resolver.dart::121::7)
#2      ElementResolver.visitMethodInvocation (package::analyzer/src/generated/element_resolver.dart::285::31)
#3      ResolverVisitor.visitMethodInvocation (package::analyzer/src/generated/resolver.dart::2723::21)
#4      MethodInvocationImpl.resolveExpression (package::analyzer/src/dart/ast/ast.dart::8689::14)
#5      ResolverVisitor.dispatchExpression (package::analyzer/src/generated/resolver.dart::778::16)
#6      TypeAnalyzer.analyzeExpression (package::_fe_analyzer_shared/src/type_inference/type_analyzer.dart::336::9)
#7      ResolverVisitor.visitExpressionFunctionBody (package::analyzer/src/generated/resolver.dart::2222::7)
#8      ExpressionFunctionBodyImpl.resolve (package::analyzer/src/dart/ast/ast.dart::4257::16)
#9      FunctionExpressionResolver.resolve (package::analyzer/src/dart/resolver/function_expression_resolver.dart::64::29)
#10     ResolverVisitor.visitFunctionExpression (package::analyzer/src/generated/resolver.dart::2395::33)
#11     FunctionExpressionImpl.resolveExpression (package::analyzer/src/dart/ast/ast.dart::5889::14)
#12     ResolverVisitor.dispatchExpression (package::analyzer/src/generated/resolver.dart::778::16)
#13     TypeAnalyzer.analyzeExpression (package::_fe_analyzer_shared/src/type_inference/type_analyzer.dart::336::9)
#14     InvocationInferrer._visitArguments (package::analyzer/src/dart/resolver/invocation_inferrer.dart::523::18)
#15     FullInvocationInferrer.resolveInvocation (package::analyzer/src/dart/resolver/invocation_inferrer.dart::209::36)
#16     InvocationInferenceHelper.resolveMethodInvocation (package::analyzer/src/dart/resolver/invocation_inference_helper.dart::179::7)
#17     MethodInvocationResolver._setResolution (package::analyzer/src/dart/resolver/method_invocation_resolver.dart::971::24)
#18     MethodInvocationResolver._resolveReceiverTypeLiteral (package::analyzer/src/dart/resolver/method_invocation_resolver.dart::836::9)
#19     MethodInvocationResolver.resolve (package::analyzer/src/dart/resolver/method_invocation_resolver.dart::136::9)
#20     ElementResolver.visitMethodInvocation (package::analyzer/src/generated/element_resolver.dart::285::31)
#21     ResolverVisitor.visitMethodInvocation (package::analyzer/src/generated/resolver.dart::2723::21)
#22     MethodInvocationImpl.resolveExpression (package::analyzer/src/dart/ast/ast.dart::8689::14)
#23     ResolverVisitor.dispatchExpression (package::analyzer/src/generated/resolver.dart::778::16)
#24     TypeAnalyzer.analyzeExpression (package::_fe_analyzer_shared/src/type_inference/type_analyzer.dart::336::9)
#25     AstResolver.resolveExpression (package::analyzer/src/summary2/ast_resolver.dart::115::22)
#26     _PropertyInducingElementTypeInference.perform (package::analyzer/src/summary2/top_level_inference.dart::256::17)
#27     PropertyInducingElementImpl.typeInternal (package::analyzer/src/dart/element/element.dart::5861::35)
#28     ElementTypeProvider.getFieldType (package::analyzer/src/generated/element_type_provider.dart::62::15)
#29     PropertyInducingElementImpl.type (package::analyzer/src/dart/element/element.dart::5823::52)
#30     _InitializerInference.perform (package::analyzer/src/summary2/top_level_inference.dart::153::15)
#31     TopLevelInference.infer (package::analyzer/src/summary2/top_level_inference.dart::107::26)
#32     Linker._performTopLevelInference (package::analyzer/src/summary2/link.dart::255::29)
#33     Linker._buildOutlines (package::analyzer/src/summary2/link.dart::134::5)
<asynchronous suspension>
#34     Linker.link (package::analyzer/src/summary2/link.dart::94::5)
<asynchronous suspension>
#35     link (package::analyzer/src/summary2/link.dart::37::3)
<asynchronous suspension>
#36     LibraryContext.load.loadBundle (package::analyzer/src/dart/analysis/library_context.dart::180::24)
<asynchronous suspension>
#37     LibraryContext.load.<anonymous closure> (package::analyzer/src/dart/analysis/library_context.dart::246::7)
<asynchronous suspension>
#38     PerformanceLog.runAsync (package::analyzer/src/dart/analysis/performance_logger.dart::50::14)
<asynchronous suspension>
#39     LibraryContext.load (package::analyzer/src/dart/analysis/library_context.dart::244::5)
<asynchronous suspension>
#40     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package::analyzer/src/dart/analysis/driver.dart::1337::9)
<asynchronous suspension>
#41     PerformanceLog.runAsync (package::analyzer/src/dart/analysis/performance_logger.dart::50::14)
<asynchronous suspension>
#42     AnalysisDriver.performWork (package::analyzer/src/dart/analysis/driver.dart::1057::24)
<asynchronous suspension>
#43     AnalysisDriverScheduler._run (package::analyzer/src/dart/analysis/driver.dart::2140::7)
<asynchronous suspension>
```

**Comment by DanTup** [comment]
I responded on Discord, but for reference in case it's useful to future readers:

> Is there any way I can debug the analyser and have a breakpoint that would provide the context we need ?

There's some info about running the server from source, logging protocol traffic and attaching a debugger using VS Code here:

https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/process/running_in_vs_code.md


> How I can produce a longer stack trace ?

You can increase the `dart.maxLogLineLength` in VS Code to reduce the truncation of lines in the log you captured, or use the instrumentation log (see the link above) to get full untruncated logs (I'm assuming it's the line truncation that's chopping the stack trace here).


> Is there a way to invoke the analyser the same way the LSP does ?

You can run `dart language_server`, although you'd have to speak to it using the LSP protocol to initialize it and set the open folders (you may be able to copy/paste from the instrumentation log, but it needs the headers, including `\r\n` terminators (it's `\r\n` even on non-Windows) before the JSON.

**Comment by scheglov** [comment]
Thank you.
The log did not help per se, because it still does not show the enclosing node.

I was able to reproduce the issue.
But there is no guarantee that this is the same case as you see.

```dart
extension on int {
  late final v = super.foo();
}
```

**Comment by scheglov** [comment]
To reproduce this locally, you could run `package:analyzer` yourself. Because this is an exception during analysis, not during a service of the language server, you don't have to go through the server and its JSON protocol.

```dart
import 'package:analyzer/dart/analysis/analysis_context_collection.dart';

void main() async {
  final collection = AnalysisContextCollection(includedPaths: [
    '/Users/scheglov/dart/test',
  ]);

  for (final analysisContext in collection.contexts) {
    // print(analysisContext.contextRoot.root.path);
    final analysisSession = analysisContext.currentSession;
    for (final path in analysisContext.contextRoot.analyzedFiles()) {
      if (path.endsWith('.dart')) {
        print('  $path');
        await analysisSession.getResolvedUnit(path);
      }
    }
  }
}
```

Once you reproduce the issue, and know the file where it is, you can either copy this file and hack it until you reduce it to a small example, or you could set a breakpoint in `package:analyzer` (I can do this in IntelliJ). Because I know the state I'm looking for, I changed the analyzer inside `Pub` cache (do it very carefully, and don't forget to revert your changes) to reduce the number of hits inside the analyzer.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/384794/222800494-fe4d015e-1e61-4f65-b8ef-26f77401e239.png">

**Comment by DanTup** [comment]
> Because I know the state I'm looking for, I changed the analyzer inside `Pub` cache (do it very carefully, and don't forget to revert your changes) to reduce the number of hits inside the analyzer.

It should be possible to set a conditional breakpoint (with the condition `enclosingClass == null`) to do this without modifying the PubCache (at least in VS Code, I'm not sure whether it's available for IntelliJ).

I hadn't thought about using `package:analyzer` directly like that. Getting set up to run the server from source isn't trivial, so this could be a good way to narrow things down that only occur on projects that can't be shared, thanks! :-)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/286864

**Comment by tlvenn** [comment]
Thanks a lot for fixing this @scheglov !
How can i get the latest sdk ?
I though switching to the master channel would do it but I am stuck with `3.0.0-290.0.dev (dev) (Thu Mar 2 14:58:47 2023 -0800) on "macos_x64"`

**Comment by DanTup** [comment]
@tlvenn my understanding is that the Dart SDK needs first roll into flutter/engine, and then flutter/engine needs to roll into flutter/flutter before you'll see this on master.

Normally these rolls happen all automatically frequently, but sometimes they're paused/reverted when branches are being aligned (eg. for beta releases) which could be happening here based revert/comments at https://github.com/flutter/engine/pull/40054#issuecomment-1453962686.

**Comment by tlvenn** [comment]
Hi @scheglov & @DanTup , thanks for your guidance on how to investigate this.
I was able to integrate @scheglov patch and could verify that unfortunately my issue seems to be something else..

The analyser is crashing on this specifically:
```
  late final _$authenticateTrackedAction =
      TrackedAction.create<Tuple2<String, String>>(
          (tuple) => super.authenticate(tuple.item1, tuple.item2),
          name: '_MainStore.authenticate');
  TrackedActionStatus get authenticateStatus =>
      _$authenticateTrackedAction.status;
```

on the node `(tuple) => super.authenticate(tuple.item1, tuple.item2)`
![CleanShot 2023-03-07 at 15 01 55](https://user-images.githubusercontent.com/3340262/223353601-d478a1d2-5af2-4062-9a4d-350642fd241f.png)

The `factory SuperContext.of(SuperExpression expression)` ends up recursively calling the parent node until this node matches `MixinDeclaration` and return `SuperContext.valid`.

![CleanShot 2023-03-07 at 15 10 41](https://user-images.githubusercontent.com/3340262/223353255-7593754d-2703-4c61-82ab-6293e35db921.png)

This code is pretty old and did not trip the analyzer before so it seems that there is a regression somewhere somehow.
Now that we have identified the culprit, i should be able to isolate this into a demo project so you can reproduce it on your side.

**Comment by scheglov** [comment]
This was almost not enough to give me enough actionable data.
In the future it would be useful to know the sequence of enclosing nodes.
But because you mentioned `MixinDeclaration`, I managed to reproduce it.

```dart
mixin M {
  late final a = super.foo();
}
```

Interestingly, when within a method of a mixin, it does work.
Which is not totally surprising, because otherwise all the Flutter would break.

It will take me a day or two to get to it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/287641

**Comment by tlvenn** [comment]
Thanks a lot for this @scheglov !
