### ISSUE TITLE
[analyzer] Implement constant equality as primitive equality

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51567]
This is the analyzer specific issue corresponding to https://github.com/dart-lang/sdk/issues/51565, which has the details.

**Comment by eernstg** [comment]
@scheglov, will this fit into Beta 3?

**Comment by scheglov** [comment]
Yes, it should fit.
I suppose the change also happens only when the `patterns` feature it enabled?

**Comment by eernstg** [comment]
Sounds good, thanks! Yes, enabling it as part of the patterns feature sounds fine!
