### ISSUE TITLE
Creating a function from another function

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51569]
Wraps a function to throw an exception when running for a long time.

To control the execution time, it is required to call a function inside
some other function - the call function.

The example shows a simple demonstration of working with a function with no
arguments. But what if you want to wrap a function and pass arguments to it
through the wrapper function.
The call function in the example is used to call a function with no arguments.

The callv2 function is used to call a function, passing arguments to it. Now
for this you need to use Function.apply. This leads to inconvenience when
passing arguments, to disabling the static check of a function call.

It is proposed to implement the ability to define types for a function
based on the types of another function. See callv3, callv4, ... for possible
syntax examples.

The implementation of the feature will make it possible to write wrappers for
functions while maintaining static control and ease of specifying the types
of parameters, the type of result.

Maybe the task can be solved somehow with the help of annotations, code
generators. I don’t know, I haven’t tried it yet, but I want to get the
simplest way to solve it.

The syntax can be anything, just a few examples are listed. The main thing is
that the problem can be solved.

```dart
class TimeoutFunction<T extends Function> {
  final T _func;
  final Duration timeout;

  TimeoutFunction(this._func, this.timeout);

  Future<dynamic> call() async {
    var completer = Completer();

    var timer = Timer(timeout, () {
      assert(!completer.isCompleted);
      completer.completeError('timeout');
    });

    Future.value(_func()).then((result) {
      if (!completer.isCompleted) {
        timer.cancel();
        completer.complete(result);
      }
    });

    return completer.future;
  }

  Future<dynamic> callv2({
    Map<Symbol, dynamic> namedArgs = const {},
    List<dynamic> posArgs = const [],
  }) async {
    var completer = Completer();

    var timer = Timer(timeout, () {
      assert(!completer.isCompleted);
      completer.completeError('timeout');
    });

    Future.value(Function.apply(
      _func,
      posArgs,
      namedArgs,
    )).then((result) {
      if (!completer.isCompleted) {
        timer.cancel();
        completer.complete(result);
      }
    });

    return completer.future;
  }

  // The "@" character emphasizes that the task is solved at the compilation level.
  @AboutType<T>.returnType
  callv3(@AboutType<T>.parameters) async {
    //...
  }

  @AboutType<_func>.returnType
  callv4(@AboutType<_func>.parameters) async {
    //...
  }
  
  @MakeFunction<T, callv5> {
    // .....
  }
}
```

**Comment by lrhn** [comment]
I don't want to enable reflection on function types, where you can dynamically create a function of any type that you can think up  in the program.

I also don't want to enable reflection over argument lists (converting them into lists and maps, and reifying them back).
That's not the correct level of abstraction.

It does mean that we have no way to abstract over function signatures. If you don't know the parameter list statically, there is no way you can create a function with that parameter list at runtime.
(Which is good for code-size, bad for flexibility.)

A more suitable solution could be something like:
```dart
/// Returns a function with the same type as [function].
///
/// When the returned function is invoked, the [around] function is called first.
/// It can then call its `original` function argument when it wants to transfer control to
/// the wrapped [function], which is then invoked with all arguments provided 
/// to the returned function.
/// The `original` function never returns. Calling it effectively works like returning from
/// the [around] function at the call-point (or like it threw an uncatchable exception).
/// The [around] function can intercept the return using `try`/`finally`, but it must 
/// eventually throw or let the returning from calling `original` complete.
/// If the returning completes, the call to the returned function completes with the 
/// same result. If [around] ends by throwing, the call to the returned function
/// throws the same error and stack trace.
F wrap<F extends Function>(F function, Never Function(Never Function() original) around);
```

The obvious short-coming is async functions. If `function` returns a future, do we want to await it before returning from `around`? Maybe, probably, but not certainly. So maybe we need two different functions.


Another approach, more promising, but also demanding more changes to the language, is to actually allow abstracting over parameter lists. Maybe using record, so `Function` is defined as
```dart
class Function<out R, in P extends Record> {
  static R invoke<out R, in P extends Record>(Function<R, P> function, P arguments) => function(...arguments);
}
```

Obvious short-coming is that a record doesn't have *optional* fields, so an `int Function(int, [int])` would be a subtype of both `Function<int, (int,)>` and a `Function<int, (int, int)>` (aka. `int Function(int)` and `int Function(int, int)`), but won't have a `Function<R, P>` representation itself.
Still better than nothing, and with a proper argument-list record spread operator, it's pretty usable.

Even just being able to abstract over return type is useful. Then `Function.apply` would be
```dart
  external static R apply<R>(Function<R, Never>, List<Object?> positional, [Map<Symbol, Object?>? named]);
```
and would keep the proper return type.

**Comment by gmb119943** [comment]
This is not about dynamic function wrappers. @AboutType<T>.returnType will be replaced by the compiler with a static type that matches the return type of the template function. This is about developing a template engine for creating wrapper functions.

**Comment by gmb119943** [comment]
And @AboutType<func>.parameter will be replaced by the compiler with a list of parameters. Some analogue of define from c/c++.

**Comment by gmb119943** [comment]
Fine. As a dart expert, what would be your advice for writing a function that wraps another function and controls how long it takes to execute. This function should be part of a library that allows you to set the maximum execution time for a function. Practical use? For example, there is a certain system of real time. The task must be completed within a certain time.

**Comment by lrhn** [comment]
Limiting execution time only applies to asynchronous functions to begin with. There is no way to preempt a running synchronous computation without its cooperation. At least not inside the same isolate, and all isolate communication is asynchronous too.

We can't abstract over function signatures, so I'd limit myself to nullary functions and expect you to provide the parameters inside that function.

That means that instead of doing `someFunction = addTimeout(duration, someFunction);` and having it work for every type of function, you need to know the parameter type at the point where you wrap and do:
```dart
someFunction = (int arg1, int arg2) => someFunction(arg1, arg2).timeout(duration);
```
or, for a synchronous function, I'd spawn an isolate running it, like `Isolate.run` does, but keep the isolate around so I can kill it when a local timer times out. Still asynchronous in the local isolate.


The example using `@AboutType` suggests a macro based solution instead. I don't know whether the currently designed macros can handle that, but maybe they can.
Just be careful that you actually know the types at the point where the macro must be expanded.

**Comment by gmb119943** [comment]
Thanks for the advice.

By the way, the proposed mechanism could be used not only for timeouts. Another example, functions with caching. There is even a package like this https://pub.dev/packages/cached. In this package, the developer applies annotations with code generation. With the support of the described mechanism in some form, it would be easier for him to do this.

The described mechanism will probably not be needed often, and in certain cases it can be changed to code generators, but if something like this were at least in an experimental form, then the solution of some problems could be simplified.

**Comment by lrhn** [comment]
If code generation is the way to go, then I'd recommend looking at the macros/metaprogramming proposal; https://github.com/dart-lang/language/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Astatic-metaprogramming


Generally, this will likely require language changes, so an more specific issue in the language repository will be more actionable.
