### ISSUE TITLE
CFE should report a compile-time error when using ":" as the default value separator in 3.0

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51576]
For Dart 3.0, we are [removing support](https://github.com/dart-lang/language/issues/2357) for the long-deprecated ancient `:` default separator syntax:

```dart
foo({int x: 3}) {}
```

Analyzer has already implemented this and reports an error on the above code. The CFE should too.

**Comment by johnniwinther** [comment]
Is this only libraries with a language version >= 3.0 ?

**Comment by munificent** [comment]
I don't know actually. I haven't been driving this change and the main issue isn't clear. If it were up to me, I would still allow `:` in libraries whose language version is <3.0. @bwilkerson, how does the analyzer handle this? @lrhn or @mit-mit, do you have a preference?

**Comment by bwilkerson** [comment]
In code prior to 3.0 analyzer issues a warning that the syntax is going away. In 3.0 and later it issues an error saying that it's no longer allowed. Specifically, the 3.0 messages (problem and correction) read:

Using a colon as a separator before a default value is no longer supported.

Try replacing the colon with an equal sign.

**Comment by lrhn** [comment]
Definitely allow it in pre-3.0 libraries. It's a versioned language change, which is why it's not considered breaking.

**Comment by munificent** [comment]
Confirming what @lrhn says, we discussed this in the language meeting today and agreed it should be a versioned change. It's an error to use `:` as a default value separator in a 3.0 library. It is *not* an error to use `:` as a default value separator in a <3.0 library.
