### ISSUE TITLE
Switching to far branches repeats too much work

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51572]
If the assembler bails out because of of insufficient branch range, the whole pipeline is restarted in far branch mode, including rebuilding the flow graph and optimization passes. It should be sufficient to restart only the code generation.

**Comment by a-siva** [comment]
This is a compile time improvement not performance of generated code.

**Comment by rmacnak-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/399461
