### ISSUE TITLE
Package paths without quotes

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51575]
Is it possible to make it optional to use in import, export quotes around what is being imported or loaded. The quotes can only be left out when there are spaces in the path. And in the IDE, you can highlight the paths with a special color somehow.

**Comment by mnordine** [comment]
Does this cover what you want? https://github.com/dart-lang/language/blob/master/working/0649%20-%20Import%20shorthand/proposal.md

**Comment by gmb119943** [comment]
I skimmed through the document for suggestions about quotes. There https://github.com/dart-lang/language/blob/master/working/0649%20-%20Import%20shorthand/proposal.md#design this topic is covered and it is possible to specify the path without quotes. If I understand correctly, it also says that paths with spaces cannot be used. It seems to me that this solution will not be very flexible. You must also allow quoted paths if required. This will also ensure backward compatibility with older versions of dart.

**Comment by lrhn** [comment]
This is a language request, and https://github.com/dart-lang/language/issues/649 is the existing request for shorter imports.
