### ISSUE TITLE
default file extension

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51574]
What can be exported and imported besides dart files in code? Is it possible to make it so that when working with packages, if the file name is specified in export, import, the file extension (.dart) would be optional. But if you plan to support other types of files, then make .dart the default.

**Comment by mnordine** [comment]
This is also covered in https://github.com/dart-lang/language/blob/master/working/0649%20-%20Import%20shorthand/proposal.md

**Comment by gmb119943** [comment]
Yes, I saw. Thank you.
