### ISSUE TITLE
[dart:develop] How to register hot-reload callback?

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#51598]
Is there any extension method?

For example
```dart
registerExtension('ext.dart.develop.hotReload', (isolateId, params) {
  count = 0;
  // ...
});
```

**Comment by ykmnkmi** [comment]
No output for VS Code Debug `Hot-Reload` and Observer `Reload Source`:

```dart
var service = await vmServiceConnectUri('$socketUri');
service.streamListen('Isolate'); 
service.onReceive.listen(print);
```

**Comment by julemand101** [comment]
Maybe related: https://github.com/dart-lang/sdk/issues/49491

**Comment by ykmnkmi** [comment]
And this #50856

**Comment by a-siva** [comment]
Is this in the context of a flutter application or a pure Dart application?

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by bkonyi** [comment]
Subscribing to the [`Isolate` stream](https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#streamlisten) should let you receive `IsolateReload` events. You'll only get this event for hot reloads, _not hot restarts_ as hot restarts spawn completely new isolates to replace the currently running isolates.

**Comment by ykmnkmi** [comment]
@a-siva pure Dart application.

**Comment by ykmnkmi** [comment]
```dart
import 'dart:async';
import 'dart:developer';
import 'dart:io';
import 'dart:isolate';

import 'package:vm_service/vm_service_io.dart';

void onData(List<int> bytes) {
  // print(String.fromCharCodes(bytes));
  print(bytes);
}

Future<void> main(List<String> arguments) async {
  var info = await Service.getInfo();
  var webSocketUri = info.serverWebSocketUri;

  var service = await vmServiceConnectUri('$webSocketUri');
  await service.streamListen('Isolate');
  service.onReceive.listen(print);

  stdin.listen(onData);
}
```

**Comment by ykmnkmi** [comment]
Does I understand it right when I call `Service.reloadSources(mainIsolateID)` it reload source in whole isolate group?

No need to call `Service.reloadSources(mainIsolateID)` for every isolate in this group? Just the main isolate where all others are spawned by `Isolate.spawn`.

**Comment by derekxu16** [comment]
Yes, that's correct.
