### ISSUE TITLE
[Class modifiers] Report a diagnostic when `@reopen` is placed on a class which hasn't reopened anything

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51592]
It'd be good to have a diagnostic for no-op `@reopen` annotations. Generally, it would report on any `@reopen` annotation which is attached to a class (or mixin?) which does not reopen anything. (`@reopen` annotations on things other than classes should already be reported as `INVALID_ANNOTATION_TARGET`.)

Examples:

```dart
// library lib1.dart
interface class Interface1 {}
```

```dart
// library lib2.dart
import 'lib1.dart';

interface class Interface2 {}

// WARNING: Does not re-open anything.
@reopen class C1 {}

// WARNING: Does not re-open anything, as it is illegal to extend Interface1 here.
@reopen class C3 extends Interface1 {}
```

CC @pq @bwilkerson

**Comment by pq** [comment]
/fyi @kallentu: if we captured  information about induced modifiers in the element model, this is something we could neatly implement.  Moreover, if we cached this data, we could do it quickly.

**Comment by pq** [comment]
Bumping this to the next milestone for future assessment. Landing `@reopen` at all is enough of a stretch IMO. (See https://github.com/dart-lang/linter/issues/3920.)

**Comment by srawlins** [comment]
Mind if I take this one, Phil?
