### ISSUE TITLE
[CP] fix vm crash on particular use of RegExp

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#51606]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/286021

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/286520

### Issue Description

On mobile devices on a repeated use of some RegExp vm will crash.
Due to the size of some RegExps, vm optimization pipeline targeting arm devices will run twice. Between first and second runs some internal RegExp compiler state  will change(CharacterRanges will get canonicalized), so the second run that saw canonicalized CharacterRange will produce flow graph that is incompatible with what first run produced, which saw not-canonicalized CharacterRange. That causes the crash.

### What is the fix

Ensure that canonicalization of CharacterRange is done before first optimization compiler run starts generation, ensuring that first and second run produce compatible flow graphs.

### Why cherry-pick

External users hit and reported this crash

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/121270

**Comment by itsjustkevin** [comment]
Thank you for the cherry-pick @aam.

@a-siva could you take a look?

**Comment by a-siva** [comment]
lgtm

**Comment by itsjustkevin** [comment]
@aam you are free to merge you CL!
