### ISSUE TITLE
[dart2wasm] readAsBytesSync fails with "unsupported operation"

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51600]
`File.readBytesAsSync` used to work a few weeks ago, but started to fail recently.

Repro:

```dart
import 'dart:io';

void main() {
  File("test.dart").readAsBytesSync();
}
```

Output:

```
Unsupported operation: _Namespace
    at _Namespace._namespace (wasm://wasm/000b83b6:wasm-function[842]:0x26f36)
    at _File.openSync (wasm://wasm/000b83b6:wasm-function[815]:0x26633)
    at _File.readAsBytesSync (wasm://wasm/000b83b6:wasm-function[766]:0x24b43)
    at main (wasm://wasm/000b83b6:wasm-function[54]:0x16607)
    at main tear-off (wasm://wasm/000b83b6:wasm-function[56]:0x16619)
    at _invokeMain (wasm://wasm/000b83b6:wasm-function[67]:0x16d1c)
    at Module.invoke (/usr/local/google/home/omersa/dart/sdk_wasm/test/test.mjs:172:28)
    at main (/usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/run_wasm.js:61:21)
```

This method is used by protobuf benchmarks, which are currently broken.

**Comment by osa1** [comment]
`_File.readAsBytesSync` never really worked, so I tried a random commit from 4 months ago (ca7ab1e89d8) to see how this worked before. It seems like this conditional import in protobuf benchmarks:

```dart
export 'readfile_vm.dart' if (dart.library.js) 'readfile_d8.dart' show readfile;
```

Previously imported `readfile_d8.dart`, but now it (correctly) imports `readfile_vm.dart`. It works as expected when I check for `dart.library.wasm`.

The second issue is the js package import in `readfile_d8.dart`:

```dart
import 'dart:typed_data';

import 'package:js/js.dart';

/// Read the file at the given [path].
///
/// This relies on the `readbuffer` function provided by d8.
@JS()
external ByteBuffer readbuffer(String path);

/// Read the file at the given [path].
Uint8List readfile(String path) {
  return Uint8List.view(readbuffer(path));
}
```

Which is no longer available when compiling with dart2wasm.

@joshualitt  @askeksa-google  do you know how to import d8 `readbuffer` function here, without using `package:js`?

**Comment by osa1** [comment]
@joshualitt the problem is the `@JS()` part. I can't import the package `js` so `JS` is not available.

AFAIU `readbuffer` is a v8 built-in function, we should just use a different annotation there to generate the right import for `readbuffer`.

**Comment by joshualitt** [comment]
@osa1, the `JS` annotation is also available in `dart:js_interop` so you can import that instead.

**Comment by osa1** [comment]
Thanks! I fixed the benchmarks in https://github.com/osa1/protobuf.dart/commit/1ad6889ba4030f13e6090bb6b6566e3f3f0fb335.
