### ISSUE TITLE
Trigger certain trybots with Gerrit "hash"tags or labels

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51605]
I was reading that you can configure a GitHub Action to trigger when a certain label is applied to a PR, and I thought that would be a useful feature for our Gerrit code reviews.

The idea is that tagging a CR with a Gerrit Hashtag like "[check-flutter]" would trigger the 'flutter-analyze' and 'flutter-engine' try bots.

Or maybe it would be with the other Gerrit syntax that, for example, we use to specify how a CR was tested with 'Tested=' on the final lines of a description.

**Comment by athomas** [comment]
There's no built-in support for triggering on gerrit tags or labels, only thing we currently can configure is based on modified files:
https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/main/lucicfg/doc/README.md#luci.cq-tryjob-verifier

Something similar is currently support with this footer, though:
`Cq-Include-Trybots: luci.dart.try:flutter-analyze-try`

So the easiest would be to implement a script that adds the appropriate footers to the CL.

**Comment by srawlins** [comment]
> So the easiest would be to implement a script that adds the appropriate footers to the CL.

That's not a bad idea! `git commit --template=flutter-trybots-footer.txt` looks like it will do the trick. From the docs:

> When editing the commit message, start the editor with the contents in the given file.

Thanks @athomas ! We can close this unless there is an upstream gerrit feature request or something.

**Comment by athomas** [comment]
Let's close it for now, if it turns out the current features are too cumbersome we can revisit.

**Comment by srawlins** [comment]
Many moons later (but not yet a year!), I have encoded this into a git alias.

In my `~/.gitconfig`, I have:

```ini
[alias]
        commitbots = "!git commit \"$@\" -m \"Cq-Include-Trybots: luci.dart.try:flutter-analyze-try,analyzer-win-release-try\" #"
```

I need a better name... but now I can write, with extra arguments, something like `git commitbots -am "Commit message"` and the `Cq-Include-Trybots` will be added at the end, resulting in a commit message of:

```none
Commit message

Cq-Include-Trybots: luci.dart.try:flutter-analyze-try,analyzer-win-release-try
```

which will automatically get picked up by `git cl upload`. 🎉
