### ISSUE TITLE
Analyzer reports error for a valid constant expression

### ISSUE THREAD

**Issue by nikitadol** [dart-lang/sdk#51607]
```
dart --version
Dart SDK version: 2.19.3 (stable) (Tue Feb 28 15:52:19 2023 +0000) on "macos_arm64"
```

Code example: 
```dart
class Test {
  const Test(this.list);

  final List<int> list;
}

const bool fromEnvironment = bool.fromEnvironment('dart.library.js_util');

void main() {
  const Test([
    1,
    2,
    if (fromEnvironment) ...[
      3,
      4,
      5,
    ],
  ]);
}
```

Dart analyze:
```console
A value of type 'Null' can't be assigned to a parameter of type 'List<int>' in a const constructor. Try using a subtype, or removing the keyword 'const'. •
          const_constructor_param_type_mismatch
```

If I change `dart.library.js_util` to something else (or remove one letter), then the problem disappears

A similar problem was here:
https://github.com/dart-lang/sdk/issues/47896

**Comment by pq** [comment]
/fyi @scheglov who fixed https://github.com/dart-lang/sdk/issues/47896.

**Comment by scheglov** [comment]
The reason this happens is that we don't know the value of `const bool fromEnvironment`. And the current implementation of `IfElement` evaluation says "cannot compute, invalid value" instead of "valid value, don't know which one".

I will not fix this quickly, constants support in the analyzer is complicated and has code with rich history.

**Comment by nikitadol** [comment]
@scheglov 
If I change:
```dart
const bool fromEnvironment = bool.fromEnvironment('dart.library.js_util');
```
to:
```dart
const bool fromEnvironment = bool.fromEnvironment('environment');
```
Then the analyzer will not show an error

**Comment by scheglov** [comment]
It was special cased for https://github.com/dart-lang/sdk/issues/50045
Not saying that this is right, just for information.

**Comment by kallentu** [comment]
Pushed a fix for this involving unknown bool constants in lists [40aacb3](https://github.com/dart-lang/sdk/commit/40aacb348252f47fb479d539110ffe59e8d4670c).
Closing.
