### ISSUE TITLE
[Class Modifiers] Investigate cfe test failures with class modifiers flag flip

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#51610]
See [these logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787787247092936193/+/u/test_results/new_test_failures__logs_), for language tests failures I have just been mailing out some mass fixes but lots of these are different types of tests that I don't quite fully understand how to fix.

Can you take a look and advise on the best course of action? Ideally we would pre-emptively fix but we can also attach changes to the [flag flip CL](https://dart-review.googlesource.com/c/sdk/+/285080) if necessary.

**Comment by jakemac53** [comment]
Note that many of these failures might be resolved separately in [Lasse's cl](https://dart-review.googlesource.com/c/sdk/+/284304) to add modifiers to the core libs. You can likely ignore issues regarding extending final classes from the SDK core libs for instance.

**Comment by kallentu** [comment]
I'm currently looking into these.

@johnniwinther with some questions from my investigatory work.

1. A lot of these are just prior tests using classes as mixins. I can go through them and change them to mixin or mixin classes. Would you rather me do that or just tag them as `@dart=2.19`?

2. There's a lot of errors that now with `Function` actually being `final`, there's two sets of errors when you subtype `Function`. Do we want to revert/remove `Function`'s specific impl/extends/with errors and just leave the set of errors from it being final?
```
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/messages/ExtendFunction/part_wrapped_script broke (Pass -> Fail, expected Pass)
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/messages/ExtendFunction/script broke (Pass -> Fail, expected Pass)
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/messages/ImplementFunction/part_wrapped_script broke (Pass -> Fail, expected Pass)
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/messages/ImplementFunction/script broke (Pass -> Fail, expected Pass)
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/modular/class_modifiers/subtype_function broke (Pass -> Fail, expected Pass)
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/modular/general/inherit_function broke (Pass -> Fail, expected Pass)
```

3. Additionally, what is Dartino? What do we do with these tests?
```
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/incremental_dartino/add_named_mixin_application.incremental broke (Pass -> Fail, expected Pass)
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/incremental_dartino/remove_named_mixin_application.incremental broke (Pass -> Fail, expected Pass)
cfe-unittest-asserts-release-linux:pkg/front_end/test/fasta/incremental_dartino/unchanged_named_mixin_application.incremental broke (Pass -> Fail, expected Pass)
```

I'll ask more as I find more issues cropping up. Most of these seems okay to fix with a mixin/mixin class and it shouldn't take too long.

**Comment by jakemac53** [comment]
> 2\. There's a lot of errors that now with `Function` actually being `final`, there's two sets of errors when you subtype `Function`. Do we want to revert/remove `Function`'s specific impl/extends/with errors and just leave the set of errors from it being final?

Fwiw these might be out of date, or in any case will have to be resolved in order to land the [core library opt in CL](https://dart-review.googlesource.com/c/sdk/+/284304) cc @lrhn . I have not updated my cl with any changes to that one in a while.

**Comment by johnniwinther** [comment]
1) Tests that "just happen to" use classes as mixin, i.e tests that don't explicitly test using a class a mixin, should be updated to use mixin or mixin classes. Those that test use of a class as a mixin should have a `@dart=2.19` annotation and maybe duplicated so we one test before 3.0 and one after.

2) Given that we never reported on extending, implementing or mixing in `Function`, we can just remove these errors and use the `final` error.

3) Dartino is an old project for compiling Dart to embedded devices. This was the first time we supported incremental compilation, so we held on to the test corpus. These tests should be updated to use mixin and mixin classes.

**Comment by lrhn** [comment]
The core-lib-opt-in CL does not fix the double `Function`-error, it just accepts it for now.
It's also reported inconsistently, perhaps because the `Function` type actually being used is not the one introduced by the `class` declaration.

We should let new libraries expose the "class is final" error and 2.12-2.19 libraries have the old behavior.

**Comment by jakemac53** [comment]
Is this already the behavior that is shipped? In the flag flip cl after updating it to master I still see lots of failures related to extending LinkedListEntry and other final classes, with non-final classes. So that would explain why I am seeing those, but you were able to land without breaking them.

**Comment by kallentu** [comment]
All errors triaged and fixed.
Also, flag flip landed, so will be closing this now.

**Comment by jakemac53** [comment]
Thanks so much @kallentu ! 🚀
