### ISSUE TITLE
[CP] [vm] Fix `Dart_CObject_Type` breaking change

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#51615]
### Commit(s) to merge

14e4a52657329314a59e9d2f887259d4ec169bce

### Target

beta and stable (potentially we don't have to cherry pick for beta if we chose a new candidate soon, as then the commit from main will be included I presume - that landed 2 weeks ago).

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/286741
https://dart-review.googlesource.com/c/sdk/+/286780

### Issue Description

`dart_api.h`'s `Dart_CObject_kSendPort`'s enum value was changed without need and without issuing a breaking change.

### What is the fix

Adding enum values at the end of the enum instead.

### Why cherry-pick

Packages using `dart:ffi` with the `dart_api_dl.h` rely on binary stability of `dart_api_dl.h`. These packages cannot work on multiple versions of the SDK. This forces users to update their packages to the newest version of the SDK and break their packages on older versions of the SDK.

In this case `dart_version.h` wasn't updated either, so users cannot check whether their package will work, leading to segfaults when calling the dart APIs from C.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51459

### Extra Info

This affects 2.19 stable and 3.0.0 beta.

**Comment by itsjustkevin** [comment]
@dcharkes could you help me understand a bit more here?   We pushed a breaking change without going through the normal process?  

I think my questions here are: 
1. Was this changed long ago?  Should we be reverting instead of fixing forward?
2. If we plan to keep the changes, have we communicated this yet?

**Comment by itsjustkevin** [comment]
@mkustermann could you take an initial look at this cherry-pick?

**Comment by dcharkes** [comment]
> We pushed a breaking change without going through the normal process?

Yes. In the C API of the Dart VM: https://github.com/dart-lang/sdk/blob/main/runtime/include/dart_api_dl.h (or rather a type referenced by that API).

> Was this changed long ago?

From 2.18 to 2.19

> Should we be reverting instead of fixing forward?

Reverting gains us the same as fixing forward. The issue is a C enum, reverting would remove the entry, fixing forward moves the entry til last position, both will restore the int-values of the preceding enum values.

> If we plan to keep the changes, have we communicated this yet?

WDYM with keeping the changes? Doing nothing or fixing forward?

**Comment by itsjustkevin** [comment]
Thanks @dcharkes the last question can be ignored as you pointed out that this was a change from 2.18 -> 2.19.

**Comment by blaugold** [comment]
Any news on this?

**Comment by itsjustkevin** [comment]
@a-siva can you give this cherry-pick a look?

**Comment by a-siva** [comment]
lgtm

**Comment by itsjustkevin** [comment]
@dcharkes cherry-pick approved, you are okay to merge the changes.
