### ISSUE TITLE
Null check does not result in non-optional type in lines in the if-statement

### ISSUE THREAD

**Issue by martijnjanssen** [dart-lang/sdk#51628]
In the code shown below the `String? a` and `String? b` are still considered optional after checking their existence in the if-statement. I would assume that the type checker would be able to deal with situations like these, not encouraging me to use `a!` and `b!` in this instance.

* Dart SDK Version (`dart --version`)
Based on Flutter 3.7.6
Dart SDK 2.19.3
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Reproducible by pasting into online DartPad

I have created a snippet to be pasted into https://dartpad.dev highlighting the issue.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: MyStatelessWidget(b: 'b'),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  String? a;
  String? b;

  MyStatelessWidget({super.key, this.a, this.b});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Potential LSP bug'),
      ),
      body: Center(
        child: Column(
          children: [
            const Text('test'),
            if (a != null && b != null)
              Column(children: [
                Text(a),
                Text(b),
              ]),
          ],
        ),
      ),
    );
  }
}
```

**Comment by mraleph** [comment]
This is working as intended. Please see https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields for more details.

**Comment by martijnjanssen** [comment]
Right, makes sense, thanks! 

Sorry for raising this issue.
