### ISSUE TITLE
Error on switch case that isn't valid pattern in 2.19 library

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51626]
I'm testing enabling the records and patterns flags. I'm seeing [a failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787699418492648273/+/u/test_results/new_test_failures__logs_) in language/switch/switch_legacy_test. A simplified repro:

```
// @dart = 2.19
main() {
  switch (1) {
    case 1 + 1:
      print('two');
  }
}
```

Since this sets the language version to 2.19, the switch case should be fine since it should be parsed as a constant expression, not a pattern. But I get:

```
../../../Documents/temp.dart:4:12: Error: The binary operator + is not supported as a constant pattern.
Try wrapping the expression in 'const ( ... )'.
    case 1 + 1:
           ^
```

I get this error even if I set the language version of the library to something ancient like 2.10.

**Comment by johnniwinther** [comment]
Same root cause as #51625
