### ISSUE TITLE
Valid switch cases in 2.19 version libraries are reporting errors about patterns not being enabled

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51625]
I'm testing Dart with the records and patterns flags enabled. If I run:

```dart
// @dart=2.19
main() {
  switch (1) {
    case 1 as int:
      print('one');
  }
}
```

I get:

```
$ dart ~/Documents/temp.dart
../../../Documents/temp.dart:4:12: Error: The 'patterns' language feature is disabled for this library.
Try removing the `@dart=` annotation or setting the language version to 3.0 or higher.
    case 1 as int:
           ^^
../../../Documents/temp.dart:1:1: Context: This is the annotation that opts out this library from the 'patterns' language feature.
// @dart=2.19
^^^^^^^^^^^^^
```

While `as` expressions aren't particularly *useful* expressions in constants, they are valid constant expressions and should be parsed as such (and not a pattern) if the library is at 2.19.

**Comment by johnniwinther** [comment]
@stereotype441 @jensjoha I think this is a consequence of the `allowPatterns` flag used to implement the patterns support in the parser. This flag is set based on whether the feature is enabled (globally, either by default or by passing the experiment option) and not on whether it is enabled for the current library, given its language version.

**Comment by munificent** [comment]
This issue is also affecting:

* co19_2/Language/Statements/Switch/syntax_t02
* language_2/implicit_creation/implicit_const_context_constructor_generic_test
* language_2/implicit_creation/implicit_const_context_constructor_named_test
* language_2/implicit_creation/implicit_const_context_constructor_test
* language_2/implicit_creation/implicit_const_context_list_test
* language_2/implicit_creation/implicit_const_context_map_test
* language_2/implicit_creation/implicit_const_context_prefix_constructor_generic_test
* language_2/implicit_creation/implicit_const_context_prefix_constructor_test
* language_2/switch/switch_test

I'll just approve those failures for now in the flag flip CL.

**Comment by munificent** [comment]
And some more that I think have this as their root cause:

* language/switch/case_expression_with_assignment_test
* language/switch/case_test
* language_2/switch/switch_test
* co19_2/Language/Statements/Switch/syntax_t01
* co19_2/Language/Statements/Switch/syntax_t02
* vm/dart_2/isolates/concurrency_stress_sanity_test

I'll approve these failures too.
