### ISSUE TITLE
Arrow function without brackets for a single parameter

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51621]
Is it possible in one of the next versions of dart to implement a shorthand syntax for => functions?

The abbreviation is that for functions => with one parameter, it is not necessary to use parentheses around the parameter.
Much like in javascript.

```dart
void main() {
  var list1 = [1, 2, 3];

  list1.map((i) => i + 1); // current version
  list1.map(i => i + 1);   // a new version
}
```

**Comment by mnordine** [comment]
You should put language stuff in https://github.com/dart-lang/language

**Comment by mnordine** [comment]
Something like that exists: https://github.com/dart-lang/language/issues/320

**Comment by lrhn** [comment]
I'll defer to the existing language issue.
