### ISSUE TITLE
Provide better visibility into how vm RegExp execution time is spent

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#51624]
Currently vm profiler viewer doesn't show good useful information about time spent running RegExps.

We can improve this state of things:
- new `RegExp` event tag can be introduced so that one can quickly filter for RegExp events, get a sense at a very coarse level of how much time is spent running RegExps.
- Currently all generated RegExp functions all have the same "RegExp_matcher" name. Instead generated RegExp functions should have names that can be traced back to the executed RegExp pattern(pattern can be part of the name, for example).  This should help quickly identify RegExp patterns that are taking longer than others.
- In vm profiler viewer, drilling into the RegExp function should show generated instructions tied (via special kind of TokenPosition) to a particular location in the RegExp string object. This should help user understand which parts of the RegExp results in hot-code shown by the profiler.
  * Generated matcher function should carry pointer to the RegExp object(so the RegExp pattern string is available at runtime for the ).
  * RegExp compiler should annotate generated instructions with token positions, which required those instructions.
  * Observatory need to support this special kind of TokenPositions so it uses them as an index into pattern strings and shows that as a "source" for generated RegExp instructions.

cc @rmacnak-google 

Should help with addressing https://github.com/flutter/flutter/issues/118193#issuecomment-1396133378

**Comment by mraleph** [comment]
fwiw when dealing with RegExp's most common performance issue is backtracking and spending quadratic time to match as a result. If the whole regexp backtracks or a large subpattern, then just highlighting this range as hot is not going to help much.

**Comment by aam** [comment]
Yeah, the point is to provide better clarity regarding what makes particular RegExp slow, allow user to have better chance of fixing troublesome expressions.
The size or complicated look of a pattern don't translate into slowness. Backtracking that the code has to do does and proposed changes to the profiler should help highlight it.
Basically this addresses "dark magic" sentiment from the comment above.
