### ISSUE TITLE
the second argument of the main function

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51620]
Can I write questions about dart here? What does the main function with two arguments mean?

```dart
void main(List<String> args, dynamic secondArg) {
  print(secondArg); // null
}
```

**Comment by eernstg** [comment]
Check out this paragraph: https://github.com/dart-lang/language/blob/8bf06233bd62653f18a5ade3d18668dd500181f0/specification/dartLangSpec.tex#L19981.
