### ISSUE TITLE
[dart2wasm] Plan for type check optimizations

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#51635]
This is an tracking issue outlining some initial ideas for optimizing the type checks in dart2wasm. Some of the steps here depend on previous steps. For some steps it makes sense to handle more than one step in the same CL.

1. [x] Add a type category table, indexed by class ID, and use it for computing runtime types. [CL](https://dart-review.googlesource.com/c/sdk/+/285684)
2. [x] Introduce `_ObjectType`, `_AbstractFunctionType` and `_AbstractRecordType` for the special interface types `Object`, `Function` and `Record`, respectively. Only `Object` needs a new entry in the type category table, since the other two are abstract. [CL](https://dart-review.googlesource.com/c/sdk/+/318681)
3. [x] Consolidate the handling of nullability in subtype checks, such that a subtype check consists of a nullability check followed by a subtype check that ignores nullability. [CL](https://dart-review.googlesource.com/c/sdk/+/319983)
5. [x] Merge the `_NullType` and `_NeverType` classes to make checking for their union more efficient. [CL](https://dart-review.googlesource.com/c/sdk/+/320540)
4. [x] Change type normalization for `FutureOr` to normalize to nullable if the type argument is nullable to save a case for `FutureOr` when checking whether a subtype check fails due to the nullabilities. [CL](https://dart-review.googlesource.com/c/sdk/+/320821)
6. [ ] ~~Refactor the subtype check into separate implementations for each rhs type kind, dispatched as a method on the type object. [CL](https://dart-review.googlesource.com/c/sdk/+/319800)~~
7. [ ] Dispatch subtype checks via a two-dimensional jump table indexed by the type categories of the two sides.
8. [x] Add a parallel subtype check method that takes an object as the lhs to avoid instantiating the runtime type object. [CL](https://dart-review.googlesource.com/c/sdk/+/336903)
9. [ ] ~~Specialize type checks to check separately for `null` when the rhs nullability is known and skip the nullability part of the subtype check.~~
10. [ ] ~~Specialize type checks to perform direct calls to the appropriate subtype check implementation when the type kind of the rhs is known.~~
11. [x] Use Wasm arrays directly instead of Dart lists in the runtime type representation. [CL](https://dart-review.googlesource.com/c/sdk/+/322900)
12. [x] Order classes depth-first such that the class IDs of all subclasses of a class (usually) form a contiguous range. Change the optimized type check to check against a set of subtype ranges instead of individual class IDs.
13. [ ] Change the type parameter substitution metadata (in `typeRulesSubstitutions`) to be sparse, i.e. only include entries that are non-empty and non-identity. Since these cases are rare, this should drastically cut down the size of the data. Look up into this data with the pair of class IDs, for instance via row displacement or other simple hashing.
14. [ ] Change the supertype metadata (in `typeRulesSupers`) to store the subtype ranges instead, and use those for general interface type subtype checks.

**Comment by osa1** [comment]
Just so that we can compare before and after, currently flute (flute commit f42b09f, SDK commit c30bec0f1a3) spends 12% of the time in `isSubtype`.

The top 5 Dart functions in perf output:

- `_TypeUniferse.isSubtype`: 12.49%
- `ListBase.indexOf`: 9.18%
- `_ListBase.[]` 5.90%
- `ListBase.isEmpty`: 3.42%
- `_ListBase.length`: 2.94%

**Comment by askeksa-google** [comment]
> * `ListBase.indexOf`: 9.18%

This looks like there is significant speed to be gained by using a more efficient subtype metadata representation. We are going to redesign it anyway, since the current representation is quite big, so this is something to keep in mind for that redesign.

**Comment by osa1** [comment]
As a binary size optimization we discussed yesterday, we can omit class names of mixin application classes as those names are never used.

**Comment by osa1** [comment]
Something else we had discussed a while ago is we should minimize member names used in errors to save on strings.
