### ISSUE TITLE
Flutter bots need to update the pre-built Dart SDK to pick up class modifier additions

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#51650]
See [this failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787346785382218641/+/u/analyze_flutter_gallery/stdout#L9056_0) and [this failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787346785382218641/+/u/analyze_flutter_flutter/stdout#L7390_0).

Both the LinkedListEntry and IterableMixin classes are marked as mixins, yet both are triggering a diagnostic when mixed in.

**Comment by bwilkerson** [comment]
@kallentu

**Comment by jakemac53** [comment]
Looks like this is a result of an out of date pre-built SDK, not any real issue. We need the flutter bots to use at least 3.0.0-293.0.dev

**Comment by a-siva** [comment]
A roll of Dart made it to the flutter framework tree this morning https://github.com/flutter/flutter/pull/122109 which updated the dart-sdk version to 3.0.0-305.0.dev
