### ISSUE TITLE
2.19.3 and 2.19.4 missing from changelog

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#51662]

**Comment by julemand101** [comment]
They are here: https://github.com/dart-lang/sdk/blob/stable/CHANGELOG.md

I guess the last few stable releases have yet to be merged into main.

**Comment by sortie** [comment]
Okay I totally always forget about this myself but it is technically documented as step 4 on go/dart-release-eng#stable-patch-release-and-beta-hotfix

@itsjustkevin you did the past couple releases, can you sync stable CHANGELOG.md back to main?
