### ISSUE TITLE
analyzer: Using a const instance as the "bitwise or expression" in a relational pattern reports a weird error

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51679]
Take this slight modification to the [Relational pattern example from the spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#relational-pattern):

```dart

class MyInt {
  const MyInt(int i);
  
  bool operator <(MyInt other) => false;
}

String asciiCharType(int char) {
  const space = MyInt(32);
  const zero = 48;
  const nine = 57;

  return switch (char) {
    < space => 'control', // error
    == space => 'space',
    > space && < zero => 'punctuation', // error
    >= zero && <= nine => 'digit'
    // Etc...
  };
}
```

This code (today on DartPad) results in an odd error on the `// error` lines:

> The argument type 'MyInt' can't be assigned to the parameter type 'num'.

I don't understand this message:

* I don't think the "bitwise or expression" has to be a num, so I don't know where 'num' is coming from.
* I don't think there is any 'MyInt' argument, or any 'num' parameter, in a pattern.

CC @scheglov @munificent

**Comment by scheglov** [comment]
Here we match `char` against `space`.
This means matching `int < MyInt`.
This means invocation of `int.<(num)`.
And we try to pass `MyInt` where `num` is expected, so the error.

I don't understand the portion about "bitwise or expression", there are no `||` anywhere.

**Comment by srawlins** [comment]
> This means invocation of `int.<(num)`.

Ah I see. This makes sense. If I change the parameter to `MyInt char`, then the errors go away.

I still hope we can separate into a different error message, other than "The argument type 'MyInt' can't be assigned to the parameter type 'num'." Perhaps something like "The constant expression type 'MyInt' can't be used in this relational pattern against a 'num'"?

I don't know all of the terms we're using for patterns and errors.

> I don't understand the portion about "bitwise or expression", there are no `||` anywhere.

I don't understand it either, I'm just using the [name from the spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#relational-pattern). Maybe a typo.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/287940
