### ISSUE TITLE
[ANTLR spec] identifierNotFUNCTION anomaly.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#51674]
Consider the `identifierNotFUNCTION` production rule:
https://github.com/dart-lang/sdk/blob/b1b1f47b958228ec082fbcb19d4e56787ff1d418/tools/spec_parser/Dart.g#L1000-L1005

The single nonterminal in its second production, `builtInIdentifier`, has a `FUNCTION` production:

https://github.com/dart-lang/sdk/blob/b1b1f47b958228ec082fbcb19d4e56787ff1d418/tools/spec_parser/Dart.g#L1593-L1604

This seems weird because the name `identifierNotFUNCTION` seems to imply that it should not be able to produce a `FUNCTION`.

Futhermore, `identifier` adds `FUNCTION` to `identifierNotFUNCTION` which it already is able to derive through `builtInIdentifier`:

https://github.com/dart-lang/sdk/blob/b1b1f47b958228ec082fbcb19d4e56787ff1d418/tools/spec_parser/Dart.g#L1007-L1011 

---

It looks to me like this can be resolved by inlining `identifierNotFUNCTION` into `identifier` and replacing any `identifierNotFUNCTION` that are left by `identifier`.

**Comment by eernstg** [comment]
Ah, interesting!

`Function` was added to the set of 'built-in identifiers' rather late (2018-02-19, cec672c7934e4c8513a58b271908efba702246a9), and nobody noticed that this change basically eliminated the special role played by `<identifierNotFUNCTION>`.

The original reason why `<functionSignature>` and `<functionFormalParameter>` uses `<identifierNotFUNCTION>` is that this disambiguates the situation where an ongoing parse might be about to recognize a function type used as a return type, and it might also be about to recognize a function name which is spelled `Function`.

```dart
void Function() f1() {} // `Function` is part of the return type.
void f2(void Function() f3()) {} // `Function` is part of the return type of the parameter type.

void Function() {} // `Function` is the name of the function.
void f4(void Function()) {} // `Function` is the name of the parameter.
```

Apparently, the more recent versions of ANTLR are able to disambiguate these situations. So when `Function` was added to the set of built-in identifiers and `<identifierNotFUNCTION>` became just another name for `<identifier>`, everything just continued to work! ;-)

This means that it makes sense to eliminate `<identifierNotFUNCTION>`. Thanks for noticing this fact, and doing that!

**Comment by eernstg** [comment]
This update has now been landed as https://dart-review.googlesource.com/c/sdk/+/287667.
