### ISSUE TITLE
vm/dart/optimized_switch_test has compile errors under Dart 3.0

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51684]
This test contains switches on enum types that deliberately don't cover every case. In Dart 3.0, it's a compile error (not warning) to switch on an enum and not cover every case.

I can pin the test to 2.19, but then we'll lose coverage for how the VM behaves on these switches in 3.0. I'm guessing the right fix is to split the test into two: one with the switches that are valid in 3.0 and one with just the ones that are errors and pin the latter to 2.19. For now, I'll approve the failure and link to this issue.

**Comment by mraleph** [comment]
@alexmarkov Alex, could you split the test so that we don't loose the coverage entirely?
