### ISSUE TITLE
[vm/ffi] Replace manual logic with class modifiers

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#51683]
We have various manual static checks that things are not extended/implemented/mixed in.

Mixing in will be disabled by default when not adding the `mixin` keyword.
But for not allowing to extend and/or implement we should add the various modifiers from https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md#syntax.

We can likely only disable the manual checks if language will be in 3.0 mode. We still need the guarantees in older language modes. So we can't delete the checks right away.

**Comment by dcharkes** [comment]
This also means we need a separate set of tests for the ffi suite in language level 3.0 mode, where we expect different error messages.

Or maybe we can get away with relying on the fact that both modes will produce an error message on the same code. But that would not be true for non-FFI tests which introduce more restrictions. @athomas are we going to duplicate language tests for 3.0 mode that give a different set of errors with different class modifiers?
Analyzer tests test for the actual ID of the error message, those might need a different set of expectations for 3.0 language mode. @bwilkerson, I presume this is true for non-FFI tests as well. Do we already have a plan for this?

**Comment by a-siva** [comment]
Does this need to be under the 'Dart 3 beta 3' milestone?

**Comment by dcharkes** [comment]
Without removing the old logic, in 3.0 we get duplicated error messages.

Error messages already duplicated: mixing in things:

https://dart-review.googlesource.com/c/sdk/+/289223/1/pkg/analyzer/test/src/diagnostics/subtype_of_ffi_class_test.dart#512

Error messages that will be duplicated when adding class modifiers: extending and implementing:

https://dart-review.googlesource.com/c/sdk/+/289223/1/pkg/analyzer/test/src/diagnostics/subtype_of_ffi_class_test.dart#355

@kallentu is exploring if we can enforce the class modifiers also in pre-3.0 rules, so that we can drop the manual checking for mixin/extends/implements. (both CFE and analyzer) If that is deems unfeasable, we should change the custom FFI rules in the analyzer/CFE to only trigger in language version >=3.0.

Relevant rules:

* analyzer
    * SUBTYPE_OF_FFI_CLASS_IN_EXTENDS
    * SUBTYPE_OF_FFI_CLASS_IN_IMPLEMENTS
    * SUBTYPE_OF_FFI_CLASS_IN_WITH
* CFE
    * FfiExtendsOrImplementsSealedClass

**Comment by vsmenon** [comment]
@dcharkes 

What's the update here?  Are we still trying get anything for the beta?

**Comment by dcharkes** [comment]
This has landed.
