### ISSUE TITLE
[CP] dart2js test and builder configuration changes

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#51686]
### Commit(s) to merge

d77e22a20bcf11f6d2107af9971edbe434cfe54b

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/287903

### Issue Description

We updated the configurations for running dart2js test builders in the SDK repo. There are accompanying changes in the infrastructure but that config is outside of the SDK repo and is the same across main, beta, and stable branches.

### What is the fix

Changes to the dart2js test and builder configurations that work with the infrastructure changes.

### Why cherry-pick

Allows dart2js test builders to run on the stable branch. Otherwise they will fail on CQ/CI.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51481

### Extra Info

The stable branch requires cherry picking 4 changes:
https://dart-review.googlesource.com/c/sdk/+/287903
https://dart-review.googlesource.com/c/sdk/+/287902
https://dart-review.googlesource.com/c/sdk/+/287901
https://dart-review.googlesource.com/c/sdk/+/287900

**Comment by itsjustkevin** [comment]
@athomas again for approval.  

Note: Approval here will constitute approval for the beta branch cherry-pick also.

**Comment by athomas** [comment]
LGTM

@nshahan: please have someone review the CLs so they're ready to land.

**Comment by itsjustkevin** [comment]
@nshahan cherry-pick approved.  Please merge once all tests pass.

**Comment by nshahan** [comment]
Submitted.
