### ISSUE TITLE
[CP] dart2js test and builder configuration changes

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#51687]
### Commit(s) to merge

d77e22a20bcf11f6d2107af9971edbe434cfe54b

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/287905

### Issue Description

We updated the configurations for running dart2js test builders in the SDK repo. There are accompanying changes in the infrastructure but that config is outside of the SDK repo and is the same across main, beta, and stable branches.

### What is the fix

Changes to the dart2js test and builder configurations that work with the infrastructure changes.

### Why cherry-pick

Allows dart2js test builders to run on the beta branch. Otherwise they will fail on CQ/CI.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51481

**Comment by itsjustkevin** [comment]
Approved @athomas has already given a review on the CL.

**Comment by nshahan** [comment]
Submitted.
