### ISSUE TITLE
Linter should warn about probable wrong use of arrow operator in `() => {...}`

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#51698]
One of the hardest issues to debug in Dart, which I hit all the time but never seem to remember to check for, is when I accidentally use `() => {...}` (lambda returning a set) rather than `() {...}` (block lambda).

A diverse array of compiler warnings and errors will result in this case, including some very weird things like `if...else` acting as an expression, rather than imperatively (so `if (cond) {block1} else {block2}` will treat `block1` and `block2` as sets, meaning the statements can't have semicolons at the end, etc. -- the errors are bizarre, and absolutely nothing indicates that the issue is the extraneous `=>`).

The linter should warn about this by default, because at least in my experience, it's far more common that I'd accidentally include the arrow operator than that I would want to return a set constructed by the Lambda using set builder notation.

* Dart SDK Version (`dart --version`): Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "linux_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable): Linux

**Comment by asashour** [comment]
A possible duplicate of #50900

**Comment by lukehutch** [comment]
It's a dup. Thanks!
