### ISSUE TITLE
[dart2js] make it an error to use the dart2js snapshot outside "dart compile js"

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#51695]
Today, the dart2js gives a warning when invoked in an unsupported context, like outside the dart cli and internal build systems. Since #46100 developers are expected to invoke dart2js via "dart compile js". 

The only way to invoke dart2js outside the standard way is to directly access its snapshot (which is not in an advertised location of the SDK). Only internal build systems and the flutter tool do this today. 

We would like to make it an error to invoke the snapshot directly, except for those counted supported cases.

To do so, we need to:
* [x] https://github.com/flutter/flutter/pull/122344 - Fix the invocation from the flutter tool to use the `--invoker` flag (which marks flutter tools as an allowed entrypoint) or to use `dart compile js` instead. 
* [ ] Change dart2js to issue an error going forward when the `--invoker` flag is missing.

**Comment by sigmundch** [comment]
@mit-mit - any concerns in making this happen by Dart 3.0? Any additional communication needed? Technically this is would be a new error, but we don't consider this a breaking change because the snapshot is hidden since the breaking changes in #46100 (made in https://github.com/dart-lang/sdk/commit/69249df50bcc7a0489176efd3fd79fff018f1b91, which went out in Dart 2.8)

**Comment by mit-mit** [comment]
No concerns, and I do not think additional comms are needed.
