### ISSUE TITLE
[ANTLR-based spec] `patterns` production rule is not being used.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#51697]
The `patterns` production rule is not being used i.e. it can't be found on the rhs of any production.

https://github.com/dart-lang/sdk/blob/d0024e9931843219b2c682f9b98ddfe1259d864f/tools/spec_parser/Dart.g#L1041-L1043

It looks to me like it can be removed?

**Comment by eernstg** [comment]
Done in https://dart-review.googlesource.com/c/sdk/+/288202. Thanks!
