### ISSUE TITLE
[analysis_server] Skip quick fixes calculation if there are no diagnostics 

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#51705]
`CodeActionsContext` comes with the `diagnostics` field which contains all diagnostics that overlap the selected range.
https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/lsp_protocol/protocol_generated.dart#L2389

Considering, that the fixes are associated with produced diagnostics and that VS Code requests code actions on every cursor position change, maybe the calculation can be skipped if there are no selected diagnostics? But note, that VS Code will send all selected diagnostics, even one produced by other extensions.
Also noticed, that you don't use `data` field. I ended up reusing it for `fix_all` and `fix_all_of_type`, but looks like with your approach for quick fixes this won't work.

Separate question: are there any artifacts left, why did you choose the current batch quick fixes approach? Or maybe I can address my questions to someone? I've been investigating another one with mutable AST, and so far I'm happy with it, as it allows more complex changes like moving code parts without any conflicts (but requires the user to use `dart format`).

**Comment by incendial** [comment]
@DanTup cc

**Comment by DanTup** [comment]
> Considering, that the fixes are associated with produced diagnostics and that VS Code requests code actions on every cursor position change, maybe the calculation can be skipped if there are no selected diagnostics?

I don't believe we can assume that the `diagnostics` provided are provided or up-to-date. When you modify a file, VS Code sends a CodeAction request for the "new cursor position" but wouldn't have had up-to-date diagnostics back from the server yet (though when the server is computing those fixes, it will have computed them).

The LSP spec also notes this explicitly:

```
export interface CodeActionContext {
	/**
	 * An array of diagnostics known on the client side overlapping the range
	 * provided to the `textDocument/codeAction` request. They are provided so
	 * that the server knows which errors are currently presented to the user
	 * for the given range. There is no guarantee that these accurately reflect
	 * the error state of the resource. The primary parameter
	 * to compute code actions is the provided range.
	 */
	diagnostics: Diagnostic[];
```

(I'm not actually sure what the use case was for including them, given they can't be relied upon).


> Also noticed, that you don't use `data` field. I ended up reusing it for `fix_all` and `fix_all_of_type`, but looks like with your approach for quick fixes this won't work.

I'm not sure I understand. `data` is for the server to round-trip data if it needs to - there's no requirement to use it. But I also don't know what you mean that you ended up reusing it (or what you mean by my approach won't work). Can you provide more details?


> Separate question: are there any artifacts left, why did you choose the current batch quick fixes approach?

I'm also unsure exactly what the questions are. The current batch implementation is using existing work that was done for "dart fix", although from the rest of the question (about a mutable AST) I'm wondering if you mean generally the way edits are built by the server (using the edit builder classes that generate source)? If so, there was a similar question (and an answer from @bwilkerson) at https://groups.google.com/a/dartlang.org/g/analyzer-discuss/c/8nvZyCZGGiU/m/QQKtORdECQAJ that might give some insight.

**Comment by incendial** [comment]
> I don't believe we can assume that the diagnostics provided are provided or up-to-date. When you modify a file, VS Code sends a CodeAction request for the "new cursor position" but wouldn't have had up-to-date diagnostics back from the server yet (though when the server is computing those fixes, it will have computed them).

Yeah, but the ESLint server uses them as if they are stable 
https://github.com/microsoft/vscode-eslint/blob/517d0fb9f9264ae3c9023e9b374f386adda69a33/server/src/eslintServer.ts#L813. Can the spec actually not reflect the reality? 

> I'm not sure I understand. data is for the server to round-trip data if it needs to - there's no requirement to use it. But I also don't know what you mean that you ended up reusing it (or what you mean by my approach won't work). Can you provide more details?

Sorry, sure. I'm talking more about the optimisations, rather than "a requirement". I have the same approach with quick fixes as ESLint has - they are associated with the diagnostics and are calculated when the diagnostics are calculated. This allows to store some data in `data` and reuse it in code actions calculations. For example, I store that there are `other` diagnostics with fixes and also `same` diagnostics, thus add "fix all" and "fix all of type" without extra recalculation. That's what I was trying to say, is it better now? 🙂

> you mean by my approach won't work

Not your exactly, but the overall approach with fixes.

> The current batch implementation is using existing work that was done for "dart fix", although from the rest of the question (about a mutable AST) I'm wondering if you mean generally the way edits are built by the server (using the edit builder classes that generate source)? If so, there was a similar question (and an answer from @bwilkerson) at https://groups.google.com/a/dartlang.org/g/analyzer-discuss/c/8nvZyCZGGiU/m/QQKtORdECQAJ that might give some insight.

Yes, that's exactly what I was looking for. Thank you!

**Comment by incendial** [comment]
> Many people assume that the best way to write code editing applications is to build an AST, modify the AST, then write the AST out as source code. But after many decades of experience writing such tools we have come to realize that it's actually much easier to modify the source code directly and then rebuild the AST from source in order to continue editing. The biggest difficulty you face when modifying the AST is keeping the AST consistent with what the analyzer would have produced. The more complex the language the more true this is, and Dart is fairly complex from an analysis perspective because of flow analysis, type inference, and other such non-local features. And if your modifications produce an AST that's different than what the analyzer would have produced then you're effectively having to support two subtly different AST representations, which increases your implementation and maintenance burdens.

Interesting, that explains why the "dart fix" works with string replacements and offsets. I still have single AST, so not sure if this problems will actually appear, but I agree that modifying the AST is harder than creating string replacements. But with mutable AST I can easily sort parameters without any confits in one go, which looks nearly impossible for the strings + offsets approach.

**Comment by incendial** [comment]
> ESLint is only one reality, and just because it's doing it doesn't mean it's guaranteed to always work :-)

I've been a ESLint user for a long time and don't remember any problems with this. But I also use code actions on a shortcut, which always sends an additional request for code actions.

> Diagnostics are pushed to the client by the server. When a client is about to send a CodeAction request whether the server is about to send it an updated list of diagnostics for that file (the user may recently modified a different file which has caused this files diagnostics to change, but it may have taken some time to compute them). The client could only provide what it had at the time, which is why the spec has this clause.

IMO it's an edge case, but I'm not sure how it scales on larger codebases, especially with the analyzer not scaling well in terms of CPU / memory which might introduce some unexpected delays. A client can always request code actions again and sometimes I end up doing it even now and would not consider it a big deal (but it's my opinion, of course). Also, shouldn't the priority files (aka opened files) be analyzed first?

> I don't think it's just an edge case either, I think things being out-of-date will happen a lot. When you type a character in VS Code, it both tells the server about the change, and also asks for CodeActions. Unless the server has analyzed the file and sent new diagnostics in between those two requests (which I suspect is very unlikely given there is almost no time at all between them) then any diagnostic you've just introduced or removed with the edit would not be reflected in what's sent to the server.
 
The thing with typing is that basically most of the time the code actions calculation is useless. That is my main concern here, but most importantly, I'm here not to push you, but rather discuss 🙂. I will keep this check for DCM to see how good / bad it actually is.

> than users see bugs like the "fix all" actions not showing up "randomly" (based on timing).

Not sure how this one can appear, but we have different implementations, so maybe it's something implementation-related.

>  It seems like both approaches have pros/cons, and which is best probably depends on a number of factors/use cases/prorities. Server uses these same classes for lots of code generation besides fixes that might have different requirements too (for example inserting stful snippet could be much more awkward to do building AST nodes versus building a string).

100% agree, I actually think that the best option is to have both approaches: mutable AST for quick fixes when independent fixes should be applied at the same time with as less confits as possible and the string-based approach for a single change, like inserting a code snippet or applying one quick fix.

**Comment by DanTup** [comment]
> I've been a ESLint user for a long time and don't remember any problems with this. But I also use code actions on a shortcut, which always sends an additional request for code actions.

If you're triggering another request, that could certainly reduce the chance of the issues I'd be concerned about, but I also think there are a lot of variables here (such as analysis time, which can vary a lot across project size and machine resources).

My main concern is that the LSP spec calls this out. No matter what VS code's behaviour is today, if the spec says they can't be relied on, it's very possible that VS Code in the future or other LSP clients (today or in future) will deliver unreliable diagnostics and be entirely within spec. I think there needs to be a compelling reason to change (and if we feel the current code action handler is slow, I'd prefer to first profile it and try to optimise it before doing this).


> The thing with typing is that basically most of the time the code actions calculation is useless. 

I agree, although I also suspect that while the user is typing there is a very high likelihood that there are diagnostics, because they will constantly have incomplete expressions/statements. I suspect the majority of times where there are no diagnostics are when the user is just moving the cursor around, and that's perhaps the time that this optimisation would be least useful to you?


All this said, it's still not completely clear to me what the goal/problem is here. Are you seeing performance you're trying to optimise? Is it in server, or plugins? If plugins, are you missing information that would be useful to make this optimisation (without the server itself having to rely on this)? I understand the request, but I don't understand the impact enough to have a good opinion on the trade-off (or, if the solution is to provide more context to plugins so they can make optimisations, what context would be useful).

**Comment by incendial** [comment]
> Are you seeing cases where you think code actions are not performing well?

If this is the question, probably no. But if I work in a project with significant amount of code (like flutter/devtools), I can end up with high cpu / memory usage + a delay for code actions for like 2-3 seconds. So in this case I'd be happy if the server would stop any unnecessary calculations.

**Comment by DanTup** [comment]
> If this is the question, probably no. But if I work in a project with significant amount of code (like flutter/devtools), I can end up with high cpu / memory usage + a delay for code actions for like 2-3 seconds.

That would meet my bar for not performing well. Is there any pattern to this? Are you able to capture a log or get a screenshot of the Analysis Diagnostic pages with timings (from the command palette, run **Dart: Open Analyzer Diagnostics**, then click Timings on the left)? (if you have some steps that might help me repro, that would be even better ofc)

When you're typing, VS Code does send a lot of requests (it asks for semantic tokens, inlay hints, code actions, outline, etc.) so it would be useful to know if all the time is spent in Code Actions, or whether other requests might be delaying it.

**Comment by incendial** [comment]
> That would meet my bar for not performing well. Is there any pattern to this? 

I'd say no, just editing the code. I'll get back with more info once I hit this problem again.

> if you have some steps that might help me repro, that would be even better ofc

If you have a good device, I believe this might be hard to achieve.

**Comment by DanTup** [comment]
@incendial do you still see the poor performance for code actions noted above? Are you able to get any logs or screenshots of the analysis diagnostic pages (described above)?

I think skipping the quick fix calculations would be problematic (and I don't think it'll help much, since while you're typing you usually have diagnostics anyway), but if the requests are taking 2s+ then I'd like to figure out why.

**Comment by incendial** [comment]
@DanTup sorry, I don't have any new info, didn't have many cases when I needed to do something in a big codebase (but then code actions was not the main problem, so I didn't pay any attention).

If you need examples to proceed, feel free to close this one and I'll get back when I have something.
