### ISSUE TITLE
Git changes indicator not appearing in VSCode 

### ISSUE THREAD

**Issue by MahmoudKhalid** [dart-lang/sdk#51714]
Git Changes indicator does not appear in VSCode

<img src="https://i.imgur.com/IYuVhXo.jpg" />

It was supposed to appear like this

<img src="https://i.imgur.com/hGhK0aH.jpg" />

Any Solution?

**Comment by MahmoudKhalid** [comment]
Seem it is a bug in VSCode new version
https://github.com/microsoft/vscode/issues/176749

**Comment by lrhn** [comment]
The git change modifier is not supplied by the Dart language server, so changes in its behavior is almost certainly unrelated to Dart or the Dart SDK.
Which means it's not something we are in a position to fix. Sorry ☹️
