### ISSUE TITLE
Auto release memory inside isolate while running

### ISSUE THREAD

**Issue by ngminhduong** [dart-lang/sdk#51715]
Use case
I want to keep the isolate instance and use it while the app is running instead of continuously spawning and killing it, because:

1. Reduce the cost to create isolate.
2. In my case I use https://pub.dev/packages/reflectable package and I want run it in a isolate so that I need call initializeReflectable() only one in a isolate and reuse it.

My solution:
I build a class to create isolate, call initializeReflectable() in this isolate and keep this instance.
``` dart
import 'dart:async';
import 'dart:isolate';
import 'package:flutter/foundation.dart';
import 'package:isolate_leak_2/database_reflect.dart';

class FSTypeMirror {
  Type dynamicReflectedType;
  String simpleName;
  FSTypeMirror(this.dynamicReflectedType, this.simpleName);
}

class GetAllClassCrossIsolatesMessage {
  final SendPort? sender;
  final SendPort? errorPort;
  GetAllClassCrossIsolatesMessage({required SendPort this.errorPort, required SendPort this.sender});
}

class DBIsolate<Q, R> {
  late SendPort _isolateSendPort;
  bool _isInitialized = false;
  VoidCallback initializer;
  ComputeCallback<Q?, R> handler;
  Isolate? _isolate;
  final ReceivePort resultPort = ReceivePort();

  DBIsolate(this.handler, this.initializer);

  void kill() {
    resultPort.close();
    _isolate?.kill();
  }

  Future<void> initialize() async {
    if (this._isInitialized) {
      return Future<void>.value(null);
    } else {
      _isolate = await Isolate.spawn<_IsolateConfiguration<Q?, FutureOr<R>>>(
        _spawn,
        _IsolateConfiguration<Q?, FutureOr<R>>(
            this.handler,
            null,
            this.initializer,
            resultPort.sendPort
        ),
        errorsAreFatal: false,
      );
      this._isolateSendPort = await resultPort.first;
      this._isInitialized = true;
    }
  }

  Future<List<FSTypeMirror>> getAllClasses() {
    var completer = Completer<List<FSTypeMirror>>();
    ReceivePort port = ReceivePort();
    ReceivePort errorPort = ReceivePort();
    this._isolateSendPort.send(GetAllClassCrossIsolatesMessage(
        errorPort: errorPort.sendPort,
        sender: port.sendPort));
    port.listen((message) {
      completer.complete(message);
    });
    errorPort.listen((error) {
      completer.completeError(error);
    });
    return completer.future;
  }
}

Future<void> _spawn<Q, R>(_IsolateConfiguration<Q, FutureOr<R>> configuration) async {
  configuration.initializer();

  var ourReceivePort = ReceivePort();

  configuration.resultPort.send(ourReceivePort.sendPort);
  ourReceivePort.listen((msg) async {
    if (msg is GetAllClassCrossIsolatesMessage) {
      try {
        var clazzes = dbReflectable.annotatedClasses.map((e) => FSTypeMirror(e.dynamicReflectedType, e.simpleName)).toList();
        msg.sender!.send(clazzes);
      } catch (e) {
        msg.errorPort!.send(e);
      }
    }
  });
}

@immutable
class _IsolateConfiguration<Q, R> {
  const _IsolateConfiguration(
      this.callback,
      this.message,
      this.initializer,
      this.resultPort,
      );
  final ComputeCallback<Q, R> callback;
  final Q message;
  final VoidCallback initializer;
  final SendPort resultPort;
}
typedef ComputeCallback<Q, R> = FutureOr<R> Function(Q message);

```
Everything work fine with me but I have an issue. The memory continues to increase while running.
I found the root cause of this issue is because I don't kill the isolate.

I think my approach makes sense because it could help to improve the app's performance significantly. Instead of continuing to spawn new isolates, we should have a solution to reuse them.

Please check memory timeline:
<img width="1023" alt="Screen Shot 2023-03-10 at 3 35 31 PM" src="https://user-images.githubusercontent.com/5801114/224630152-388cbae5-52a0-48df-871a-e35947f7774d.png">
Example project with Flutter:

[isolate.zip](https://github.com/dart-lang/sdk/files/10954466/isolate.zip)

**Comment by mraleph** [comment]
Isolates within an isolate group are more or less just static fields and the state reachable from that. There is no magic solution to releasing this memory, if you have some state that you don't need - then you need to manually clear static fields that hold to it (and be ready to recreate this state again). Releasing all of this memory is the same as killing the isolate - there is no major benefit to reusing  such "cleared" isolate.
