### ISSUE TITLE
Introduce vm annotation, use it on Future, Zone classes to prevent instances of those from being sent

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#51722]
Sending some classes instances(Future, Zone, etc) across isolates can succeed or fail in hard to reason about fashion. It seems appropriate to restrict those from being sent across altogether.

As proposed on https://github.com/dart-lang/sdk/issues/51594#issuecomment-1465848107 we should introduce vm annotation that would make it possible to prohibit those from being sent.

cc @mkustermann @lrhn

**Comment by lrhn** [comment]
I suggest `@pragma("vm:isolate-unsendable")`.

We can always create an internal `const unsendable = pragma("vm:isolate-unsendable");` if we want it to look prettier, but using this object as annotation, the same annotation can also be applied outside of the platform libraries, without us having to expose it directly.

It's an annotation which is isolate-specific, so if it was expose, it should be in `dart:isolate`.
But we, and probably others, want to use it in libraries that are used when isolates are not available, so we can't depend on `dart:isolate` for it.

**Comment by mkustermann** [comment]
This has been implemented now.
