### ISSUE TITLE
[cfe] Does not apply call insertion in pattern declaration

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51738]
Consider the following program:

```dart
class A {
  X call<X>(X x) => x;
}

void g(A a) {
  var Function(call: f) = a;
  Function g = a; // This works.
}
```

The CFE (SDK 3.0.0-322.0.dev) reports a compile-time error for this program:

```
Error: The matched value of type 'A' isn't assignable to the required type 'Function'.
 - 'A' is from 'package:dartpad_sample/main.dart' ('lib/main.dart').
 - 'Function' is from 'dart:core'.
  var Function(call: f) = a;
      ^
```

However, I would expect this situation to give rise to a 'call insertion' coercion, that is, the initializing expression should have been transformed from `a` into `a.call`, based on the context type `Function`.

**Comment by nshahan** [comment]
cc @johnniwinther 

I believe there is a related test failure because of a missing call method tearoff coercion in 
```
language/patterns/call_tear_off_test
```
