### ISSUE TITLE
the timestamp of datetime is error

### ISSUE THREAD

**Issue by peacess** [dart-lang/sdk#51735]
import 'package:test/test.dart';

void main(){
  test("",(){
    var t1 = DateTime.fromMillisecondsSinceEpoch(1000, isUtc: true);
    var t2 = DateTime.fromMillisecondsSinceEpoch(1000,isUtc: false);
//the t1 != t2, but the compareTo == 0,  millisecondsSinceEpoch == millisecondsSinceEpoch
    expect(0, equals(t1.compareTo(t2))); 
    expect(t1.millisecondsSinceEpoch, equals(t2.millisecondsSinceEpoch));
    expect(t1.toUtc().millisecondsSinceEpoch, equals(t2.toUtc().millisecondsSinceEpoch));
  });
}

**Comment by julemand101** [comment]
From the documentation of `==`:
> Returns true if other is a [DateTime](https://api.dart.dev/stable/2.19.4/dart-core/DateTime-class.html) at the same moment and in the same time zone (UTC or local).
> ...
> See [isAtSameMomentAs](https://api.dart.dev/stable/2.19.4/dart-core/DateTime/isAtSameMomentAs.html) for a comparison that compares moments in time independently of their zones.

So the `==` operator checks if the timezone is the same which means it matters if you are having UTC or localtime when comparing two `DateTime` objects. If you want to compare by the moment in time, then you should use the `isAtSameMomentAs()` method.

If we look at the documentation of `compareTo` we see:
> Compares this DateTime object to other, returning zero if the values are equal.
>
> A [compareTo](https://api.dart.dev/stable/2.19.4/dart-core/DateTime/compareTo.html) function returns:
> * a negative value if this DateTime [isBefore](https://api.dart.dev/stable/2.19.4/dart-core/DateTime/isBefore.html) other.
> * 0 if this DateTime [isAtSameMomentAs](https://api.dart.dev/stable/2.19.4/dart-core/DateTime/isAtSameMomentAs.html) other, and
> * a positive value otherwise (when this DateTime [isAfter](https://api.dart.dev/stable/2.19.4/dart-core/DateTime/isAfter.html) other).

So when returning `0` it means the two `DateTime` objects are pointing at the same moment in time as we check for with `isAtSameMomentAs()`. But `0` does not mean the two `DateTime` objects are necessarily equal in the sense of `==`.

I would also question what the order should have been if timezone was part of the comparison?
