### ISSUE TITLE
[dart web gardening] dartdev tests failing on build_daemon pub constraint checking

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#51732]
See: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-mac-release/25083/overview

**Comment by jakemac53** [comment]
This looks like a webdev issue - it needs to update its build_daemon constraint to allow version 4.0.

**Comment by jakemac53** [comment]
The message also probably should change the suggested constraint :)

**Comment by jakemac53** [comment]
Nevermind, the issue seems to be a hard coded build_daemon dependency in the web template. That very likely should not be there, as the package is not directly used?

**Comment by jakemac53** [comment]
https://dart-review.googlesource.com/c/sdk/+/289260, honestly we should probably only use `any` constraints in these templates. They are basically guaranteed to go stale otherwise.

**Comment by nshahan** [comment]
The test appears to be flaking now, is that expected?

**Comment by jakemac53** [comment]
What is the error when it flakes?

**Comment by nshahan** [comment]
Closing this issue now that the test changed from failing -> flaking.

There was a preexisting issue for the flaking problem https://github.com/dart-lang/sdk/issues/48816.
