### ISSUE TITLE
Failures on [ dart test ] Improve help message when running `dart test` with no package:test dependency

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51741]
There are new test failures on [[ dart test ] Improve help message when running `dart test` with no package:test dependency](https://github.com/dart-lang/sdk/commit/8f7e889546b79fc7f493651256c756d182ef378f).

The tests
```
pkg/dartdev/test/commands/test_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux
unittest-asserts-release-mac
unittest-asserts-release-mac-arm64
```

Example log:
https://dart-ci.appspot.com/log/pkg-mac-release/unittest-asserts-release-mac/25108/pkg/dartdev/test/commands/test_test

/cc @bkonyi

**Comment by bkonyi** [comment]
Already resolved by https://dart-review.googlesource.com/c/sdk/+/288920.
