### ISSUE TITLE
Analyzer crash with incorrect use of mixins in Dart 3.0

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#51758]
Declaring a `mixin` and then attempting to use it as a class via the `class Foo = MyMixin with Bar;` (where the `mixin` is `MyMixin`) will cause the analysis server to crash. Example program:

```dart
mixin M {} // should be a `mixin class`, but also shouldn't crash the analyzer :)
mixin N {}

class A = M with N;
```

This cropped up when removing the 2.19 opt out from the `tests/corelibs/map_mixin.dart` language test, I initially didn't realize it needed to be a `mixin class`, but it crashed my analysis server so I didn't realize 😬. (see https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8786453619759877617/+/u/test_results/new_test_failures__logs_)

**Comment by jakemac53** [comment]
It is also worth noting that `dart analyze` will _not_ crash, but it also will not analyze this file at all, it will just happily report 0 errors but do nothing. Seems like a bug?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/289403
