### ISSUE TITLE
Test various WarningCodes with patterns

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51750]
Here's what I've got so far:

* [x] `CAST_FROM_NULL_ALWAYS_FAILS` should be implemented for CastPattern [sam]
* [x] `UNNECESSARY_QUESTION_MARK` should be tested with type annotations in patterns, like CastPattern, and variable patterns [sam]
* [x] ~~`TYPE_CHECK_IS_NULL` and `TYPE_CHECK_IS_NOT_NULL` should be tested with CastPattern~~ [sam]
* [x] `UNNECESSARY_NAN_COMPARISON_FALSE` and `UNNECESSARY_NAN_COMPARISON_TRUE` in... various patterns [sam]
* [ ] `UNNECESSARY_NULL_COMPARISON_FALSE` and `UNNECESSARY_NULL_COMPARISON_TRUE` in... various patterns
* [x] ~~`NULL_AWARE_IN_LOGICAL_OPERATOR` in logical or and logical and patterns~~ [scheglov]
* [x] `INVALID_USE_OF_visibility` (`PROTECTED`, etc) in ObjectPattern [sam]

**Comment by srawlins** [comment]
CC @scheglov if you're interested. I've mailed for the first item: https://dart-review.googlesource.com/c/sdk/+/289240

**Comment by srawlins** [comment]
Good news: `UNNECESSARY_NULL_COMPARISON_FALSE` and `UNNECESSARY_NULL_COMPARISON_TRUE` do not need to be reported when `null` is used to match a value of a non-nullable type; `WarningCode.CONSTANT_PATTERN_NEVER_MATCHES_VALUE_TYPE` is already reported.

However, `UNNECESSARY_NULL_COMPARISON_TRUE` is also supposed to be reported when a _definitely un-assigned_ value is compared to `null`. For BinaryExpressions, this work is carried out in BinaryExpressionResolver. I suspect that the equivalent code for constant patterns is in shared CFE/analyzer code, which I'm not familiar with. CC @scheglov if you're interested.

**Comment by srawlins** [comment]
I checked out `TYPE_CHECK_IS_NULL`, which is only reported on IsExpressions, as in `foo is Null` (and respectively `foo is! Null` for the complementing code).

I think there is no new position to report `TYPE_CHECK_IS_NULL` in patterns, as there is no equivalent to an IsExpression. For example, a CastPattern is more like an AsExpression, on which `TYPE_CHECK_IS_NULL` is not checked.

CC @bwilkerson for any thoughts, but I think our work here is mostly done.

**Comment by leafpetersen** [comment]
Anything further to do on this?  If so, can I move it to the stable milestone (anything further will likely be a cherry pick).

**Comment by srawlins** [comment]
Some of those last ones are very low priority. I'll remove the milestone entirely.

**Comment by srawlins** [comment]
`WarningCode.CONSTANT_PATTERN_NEVER_MATCHES_VALUE_TYPE` is reported in patterns instead of `UNNECESSARY_NULL_COMPARISON`.
