### ISSUE TITLE
[CP] Merge test matrix from main to stable to restore VM test coverage

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#51764]
### Commit(s) to merge

b9d8103371d8bc53566c1b0c749a7f07c541afd3, 4d5e6d9473764e487af21d2f3df4bfbea4bbc1d4, N/A

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/289501

### Issue Description

Test coverage of vm-jit and vm-aot-android configurations is currently mostly dysfunctional on stable due to the many changes that landed on main since the last stable.

### What is the fix

This change brings the test_matrix on stable in sync with main and will restore test coverage.

### Why cherry-pick

Knowing that the Dart VM still works on stable is important and allows CPs to be tested.

### Risk

low

### Issue link(s)

N/A

### Extra Info

This is purely an infrastructure change, there is zero risk that the product or distributions are affected by these changes.

Note that the CL is a stack of CLs, and the top CL is not a cherry-pick but a merge of a single file (tools/bots/test_matrix.json from main to stable).

**Comment by athomas** [comment]
Obviously LGTM from me :)

**Comment by itsjustkevin** [comment]
Infra cherry-pick already reviewed by @whesse.  Cherry-pick approved.
