### ISSUE TITLE
Release new analyzer version?

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#51760]
Now that class-modifiers, records, and patterns are enabled by default for 3.0, does it need a new release of the analyzer pub package, so that `FeatureSet.latestLanguageVersion()` turns these features on be default as well? Currently, when parsing a file using the analyzer API that contains class modifiers it complains that the experiment is not enabled.

cc @srawlins

**Comment by srawlins** [comment]
I think this does need a new release, CC @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/289441

**Comment by goderbauer** [comment]
Thank you! Can confirm that `FeatureSet.latestLanguageVersion()` now works with code that has class modifiers, https://github.com/flutter/engine/pull/40386.
