### ISSUE TITLE
[js] 0.6.8 breaks `package:test` because `allowInterop` is missing

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/sdk#51774]
This tracker is for issues related to: **Dart core libraries**

The issue could be introduced by bd79be0e19717a7491742f3794492a22411d12a3, and `package:js` just released with `0.6.8` an hour ago.

See the example failure as a reference: https://github.com/cfug/dio/actions/runs/4452707510/jobs/7820608359?pr=1738#logs

**Comment by AlexV525** [comment]
cc @joshualitt we can still make a retraction if possible.

**Comment by joshualitt** [comment]
Yes, thanks for catching this so quickly, we're retracting right now.

**Comment by srujzs** [comment]
https://pub.dev/packages/js 0.6.8 has been retracted. We'll work on figuring out what do with `allowInterop` when we republish. Thanks for catching this!

**Comment by AlexV525** [comment]
Basically I think the new version should constraints the bottom from 3.0.0-dev.x, where x represents the version tag that `allowInterop` has been added into.

**Comment by AlexV525** [comment]
Closing as it's fixed by 2459634.
