### ISSUE TITLE
[Web][Feature request][OPFS] Please add "Origin-private filesystem" support, allowing native DBs on the web

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#51781]
hello,

Currently, the recommended client-side persistence/storage solution, on web, is [`IndexedDB`](https://api.dart.dev/dev/3.0.0-347.0.dev/dart-indexed_db/dart-indexed_db-library.html), but its API is quite-bad, I never found anyone using it directly, without abstractions,

So a new solution has been released by the web-sters, called ["Origin-private FileSystem"](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#origin_private_file_system), which has [support in all the browsers](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle#browser_compatibility), except "Samsung Internet"(mobile), and "Internet Explorer"(desktop), even the slow-mover Safari supports it,

It allows the code(js/wasm), to access a filesystem-like, persistent, high-performance, and origin-private, storage medium,
- Permission prompts are not required to access files in the OPFS,
- The OPFS is subject to browser quota restrictions, just like IndexedDB,
- Clearing data for the site deletes the OPFS,

It just behaves as a filesystem, with files and directories, etc; but the implementation is vendor dependent, maybe inside another database, but the user gets a posix-inspired, sync, as well as async, filesystem-like API, 

The performance capabilities of OPFS can be sensed from the fact that, it was originally developed to provide the persistence capabilities to sqlite.wasm, on the web, the same globally known embedded-database,

Specification is available at [spec.whatwg.org](https://fs.spec.whatwg.org/#origin-private-file-system)

thanks,

**Comment by kevmoo** [comment]
Hello @gintominto5329 – where exactly do you want support added? in `dart:html`?

**Comment by gintominto5329** [comment]
> Hello @gintominto5329 – where exactly do you want support added? in `dart:html`?

Yes sir,

`dart:html` should be the correct place, 


Because it already has other `FileSystem`(and `OPFS`) related classes, like 
- [`DirectoryEntry`](https://api.dart.dev/dev/3.0.0-347.0.dev/dart-html/DirectoryEntry-class.html)(web::`FileSystemDirectoryHandle`), 
- [`FileEntry`](https://api.dart.dev/dev/3.0.0-347.0.dev/dart-html/FileEntry-class.html)(web::`FileSystemFileHandle`), etc,

thanks,

**Comment by anlumo** [comment]
Note that the sync API is only supported in Web Workers, and Flutter does not support Web Workers.

**Comment by gintominto5329** [comment]
> Note that the sync API is only supported in Web Workers, and Flutter does not support Web Workers.

[`IndexedDB`](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) docs, also have a note like "This feature is available in Web Workers"

**Comment by gintominto5329** [comment]
hi,

Could this feature(OPFS support), expected:
- By dart-3.2, or any other release estimate,
- to feature the high-perf sync API, which requires WebWorker support, or only async API,

thanks

**Comment by gintominto5329** [comment]
Any updates?
thanks

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/web/blob/main/lib/src/dom/fs.dart

We're going to be moving all of our support to this package in the future. Improvements to `dart:html` and friends will likely be limited to critical bugs and blockers.

**Comment by gintominto5329** [comment]
> See https://github.com/dart-lang/web/blob/main/lib/src/dom/fs.dart
> 
> We're going to be moving all of our support to this package in the future. Improvements to `dart:html` and friends will likely be limited to critical bugs and blockers.

I checked out [`package:web`](https://pub.dev/packages/web), but it was published 8 years ago.

So when, and how, could we use the new package
