### ISSUE TITLE
[CP] Add missing promotion of Finalizer external size.

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51798]
### Commit(s) to merge

f4b34ad31bf679519142f27094a2f817030d8127

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/289941

### Issue Description

False OutOfMemory exceptions due to a VM accounting bug.

### What is the fix

Properly promote external size.

### Why cherry-pick

Users have encountered this issue on stable https://github.com/dart-lang/sdk/issues/50537#issuecomment-1475261765 and there is no way from the Dart program to work around this.

### Risk

medium

### Issue link(s)

https://github.com/dart-lang/sdk/issues/50537

**Comment by itsjustkevin** [comment]
@alexmarkov could you take a look at this cherry-pick for approval?

**Comment by alexmarkov** [comment]
lgtm

**Comment by xunreal75** [comment]
Does not fix out of Memory issue - Context and _Closure are growing.
