### ISSUE TITLE
[Patterns] Missing error from analyzer for label and variable in switch case

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#51803]
The analyzer doesn't produces an error for a switch case with a label and a variable pattern, if the variable is not used:
```
void f(Object? x) {
  switch (x) {
    foo: case int? x:
      break;
  }
}
```
Instead it just reports warning/hint about the unused label/variable:
```
  warning - The label 'foo' isn't used. - temp\label_and_capture.dart:3:5 - unused_label
  hint - The value of the local variable 'x' isn't used. - temp\label_and_capture.dart:3:20 - unused_local_variable
```

**Comment by scheglov** [comment]
Why should we report an error here? The [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#shared-case-scope) says: "Note that it is not a compile-time error for there to be non-shared defined variables between cases. It's only an error to use them in the body."

**Comment by johnniwinther** [comment]
Ah. My mistake.
