### ISSUE TITLE
WebSocket connection is never established

### ISSUE THREAD

**Issue by DipDevStudio** [dart-lang/sdk#51816]
I am trying to implement a connection to a video mixer device on the local network. This device has an API via WebSocket.
WebSocket standard library and its default use do not give any results.
The command below never completes.
```dart
final socket = await WebSocket.connect('ws://192.168.1.1:1234');
```
When debugging, it turns out that the [command](https://github.com/dart-lang/sdk/blob/main/sdk/lib/_http/websocket_impl.dart#L1047) never ends. More deeply I was not able to debug.

```dart
return request.close();
```
The Postman application successfully establishes a connection. Also, the standard use of WebSocket in a web browser via JS also has no problems. I tried absolutely all the packages from the [store](https://pub.dev) that are related to WebSocket or Socket - the result is identical to the above (all packages are based on the implementation from the Dart team).

I assume that the device does not have a full-fledged HTTP server and the command to complete the HTTP connection is not executed. But since it works together with Postman and browser-based JS - I conclude that the Dart team wrote the code not optimally and it takes forever.

I tried to implement [my own alternative way of establishing a connection](https://github.com/DipDevStudio/websocket_alternative/blob/main/lib/web_socket_alternative.dart) via Socket and then use the standard method of the library:
```dart
WebSocket.fromUpgradedSocket(soket, serverSide: false);
```
This solution allows me to successfully establish a connection, update the socket, and turn it into a WebSocket.
A connection established in this way successfully accepts data if the device starts to send data itself, but unfortunately does not send it to the device. 
![image](https://user-images.githubusercontent.com/43139736/226921454-999619c2-ae3e-4094-bf6b-dfa1238d2eec.png)
If I send data to both WebSocket and Socket at once
```dart
  @override
  void add(Uint8List data) {
    print('Data send:\n$data');
    try {
      _socket!.write(data);
      _webSocket!.add(data);
    } catch (e) {
      print(e);
    }
  }
```
 then the reception and sending work successfully, but only once, after that, it is an error.
 
![image](https://user-images.githubusercontent.com/43139736/226921909-7967e65e-43fe-49e0-9df4-5a229be24b7a.png)

_This is how I was able to implement the interaction with the device._
_I send one command, wait for a response and then close the connection. So in order to send many commands I have to create many connections one after the other. This also works relatively well but unfortunately, some antiviruses on Windows block this behavior (lots of fast connections)._

I would be grateful if you could tell me how to use the standard WebSocket solution (to establish a connection) or what changes I should make to make my alternative implementation work properly.

**Comment by brianquinlan** [comment]
Hey @DipDevStudio is the WebSocket server that you are publicly available? It will be hard to debug this without more information.
