### ISSUE TITLE
Analyzer Feedback from Android Studio

### ISSUE THREAD

**Issue by romCho** [dart-lang/sdk#51829]
Android studio turned on the flutter project
When the message comes out, snippet or auto-suggestion will be executed.
May I know the solution?

![스크린샷 2023-03-23 오후 3 40 36](https://user-images.githubusercontent.com/125230869/227123767-fe5edc53-0e6a-444a-8771-39ac9f54ac15.png)

## Version information

- `IDEA AI-221.6008.13.2211.9619390`
- `2.19.4`
- `AI-221.6008.13.2211.9619390, JRE 11.0.15+0-b2043.56-8887301x64 JetBrains s.r.o., OS Mac OS X(aarch64) v13.2.1, screens 3456.0x2234.0, 3440.0x1440.0  Retina`

**Comment by scheglov** [comment]
Do you have any logs in the `Notifications` pane of the Android Studio?
