### ISSUE TITLE
[anaylzer-plugin] Feature request: providing a type inference information 

### ISSUE THREAD

**Issue by wurikiji** [dart-lang/sdk#51831]
Dart currently does not support utility types for functions: something like`ReturnType`, and `Parameters` in typescript. 

For my custom packages, I need those abilities to improve the DX. 
For example

```dart
void main() {
  final dynamic wrapped = Wrapper(() => 10);
  print(wrapped());
  
  final dynamic wrapped2 = Wrapper((int a, int b) => a * b);
  print(wrapped2(10, 20));
}

class Wrapper {
  Wrapper(this.f);
  final Function f;
  
  @override
  dynamic noSuchMethod(Invocation invocation) {
    final positionals = invocation.positionalArguments;
    final optionals = invocation.namedArguments;
    final builtValue = Function.apply(f, positionals, optionals);
    final computedValue = builtValue * 10;
    return computedValue;
  }
}
```

I like to provide an analyzer plugin that provides type information. So that when developers type `wrapped2(`, my custom plugin shows the `(int, int)` parameter types. 
If the analyzer plugin can provide this ability, it will be great.

**Comment by DanTup** [comment]
> That said, this sounds like a feature that would be useful, and one that we might already have for VS Code.

@bwilkerson I don't believe we support this. In the code example above, `wrapped2` is typed `dynamic` so I don't think there is enough information to know its arguments.

If I understand correctly, this seems more like a language(?) request, something similar to callable classes, but where the signature of the `call` method is something that can come from a type argument? For example something like:

```dart
class Wrapper<T extends Function> {
  final T f;
  Wrapper(this.f);

  /// This signature wants to be T
  void/* return type of T */ call(/* arguments of T */) {
    return f(/* args */);
  }
}
```

I'm not sure this is possible today?

**Comment by bwilkerson** [comment]
> If I understand correctly ...

I think you're right, and I missed that aspect of it. This isn't something that can be done in the analyzer without a change to the language, so I'm going to close this issue.

@wurikiji 
If you want to propose a change to the language, you can do so at https://github.com/dart-lang/language/issues/new/choose.
