### ISSUE TITLE
[breaking change] Provide RISC-V builds for Linux (.zip)

### ISSUE THREAD

**Issue by jakubtalich** [dart-lang/sdk#51843]
### Change Intent

[There are](https://dart.dev/get-dart/archive) builds for many architectures, but RISC-V build for Linux is missing.

### Justification

RISC-V is becoming a popular architecture and given that Dart supports it, it would come in handy for many developers to have this build available for download without having to build it themselves.

### Impact

No impact on functionality, but good impact on the community.

### Mitigation

N/A

**Comment by mit-mit** [comment]
RISC-V is currently in preview and as per https://dart.dev/get-dart:

_"Linux
Supported versions: Debian stable and Ubuntu LTS under standard support.
Supported architectures: x64, IA32, ARM64, ARM, RISC-V (RV64GC).
Support for RISC-V is in preview, and is available only in the dev and beta channels."_

Downloads for beta and dev are on https://dart.dev/get-dart/archive

<img width="955" alt="Screenshot 2023-03-24 at 17 01 11" src="https://user-images.githubusercontent.com/13644170/227578942-43c940da-4d33-4333-83b8-d492f3f38c9b.png">


It will graduate to stable once we have sufficient testing and validation completed.
