### ISSUE TITLE
DAS needs impl or maybe just tests for MakeFinal with a variable declaration pattern

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51863]
As of https://github.com/dart-lang/linter/pull/4132, linter will report `prefer_final_locals` in variable declaration patterns like `var [a, b, ...rest] = [1, 2, 3, 4, 5, 6, 7];`. DAS should support MakeFinal in variable declaration patterns.

**Comment by pq** [comment]
Confirmed no fix:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/67586/228076325-f3a001a4-d639-427f-9465-ae0a3be5646c.png">


```dart
f(Object o) {
  if (o case [int x, int y]) {}
}
```

**Comment by pq** [comment]
No fix (even as of https://github.com/dart-lang/linter/pull/4225):

<img width="453" alt="image" src="https://user-images.githubusercontent.com/67586/228079256-16ac0640-4cd1-4c00-a9ad-a6f6d5ada218.png">
