### ISSUE TITLE
DAS needs impl or maybe just tests for RemoveLeadingUnderscore with variable declaration patterns

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51867]
https://github.com/dart-lang/linter/pull/4133 added linter support for `no_leading_underscores_for_local_identifiers` in variable declaration patterns. DAS should have support in RemoveLeadingUnderscores as well.

**Comment by pq** [comment]
Good catch.

Confirmed:

```dart
f() {
  final (_a, b) = (1, 2);
  print('$_a$b');
}
```

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/291361
