### ISSUE TITLE
Problems with error reporting for variable and wildcard patterns

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51868]
While writing some extra test cases for https://github.com/dart-lang/sdk/issues/51529, I realized that we have some related functionality that's still broken.

- The spec says "It is a compile-time error if a variable pattern in a declaration context is marked with `var` or `final`."  The CFE doesn't produce this error yet (e.g. it permits both `var [var x] = ...;` and `var [var _] = ...;`.  The analyzer doesn't currently produce it if the variable name is `_` (e.g. it permits `var [var _] = ...;`.
- The spec says "It is a compile-time error if a variable pattern appears in an assignment context."  The CFE doesn't produce this error if the variable name is `_` (e.g. it permits `[x, var _] = ...;`.

**Comment by stereotype441** [comment]
I'm going to go ahead and work on this because I think it makes the most sense for these errors to be reported by the parser.

**Comment by munificent** [comment]
> I think it makes the most sense for these errors to be reported by the parser.

+1. In particular, if these are reported later, then it's possible for erroneous code to make its way to the formatter without any error reported. That in turn means the formatter may try to parse an incomplete AST and fail.
