### ISSUE TITLE
DAS needs impl or maybe just tests for ReplaceFinalWithVar with a variable declaration pattern

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51864]
As of https://github.com/dart-lang/linter/pull/4152, linter will report `unnecessary_final` on variable declaration patterns. DAS should support ReplaceFinalWithVar in variable declaration patterns.

**Comment by pq** [comment]
Good catch.  Confirmed no fix here:


```dart
f() {
  final (a, b) = (1, 2);
}
```

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/291342
