### ISSUE TITLE
Pattern match missing inference and generic method instantiation

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#51871]
A missing generic instantiation is causing a compile time error here:
https://github.com/dart-lang/sdk/blob/0d000e85d6f3a75ca65c4d6e858e08eb16c50ff6/tests/language/patterns/implicit_instantiation_test.dart#L32-L41

```
org-dartlang-app:/tests/language/patterns/implicit_instantiation_test.dart:36:24: Error: The argument type 'T Function<T>(T)' can't be assigned to the parameter type 'int Function(int)'.
  if (Compare() case < c) {
                       ^
```

In a discussion with @munificent he mentioned that this pattern match should have the same downward inference and generic instantiation as this similar code that doesn't contain any patterns and runs without any errors:

```dart
T id<T>(T t) => t;

typedef IntFn = int Function(int);
typedef TFn = T Function<T>(T);

class Compare {
  operator <(IntFn f) {
    print(f.runtimeType);
    return f is TFn;
  }
}

main() {
  const c = id;
  Compare() < c;
}
```

cc @johnniwinther

**Comment by chloestefantsova** [comment]
@munificent I have some questions about generalizing that kind of coercion to other pattern-related spots. Should the same be performed in switch expressions, for example, in the following program?

```dart
T id<T>(T t) => t;

typedef IntFn = int Function(int);
typedef TFn = T Function<T>(T);

class Compare {
  operator <(IntFn f) => f is TFn;
}

test1() {
  const c = id;
  return switch(Compare()) {
    < c => throw "Error",
    _ => "OK"
  };
}

main() {
  test1();
}
```

Generalizing even more, should all types of coercions be enabled for the operands of all relational patterns in all pattern-related language constructs? If so, the following CFE test, which currently is compiled without any errors, will be rejected because of the attempt to coerce string `s` to `num`.

https://github.com/dart-lang/sdk/blob/main/pkg/front_end/testcases/patterns/relational_assignable.dart

**Comment by eernstg** [comment]
> should all types of coercions be enabled for the operands of all relational patterns in all pattern-related language constructs? 

We do not have a specification of the precise set of locations where coercions are applied (they are specified to be applicable everywhere, based on the context type and the type of the expression only, but they have always been implemented such that they were only applied in a smaller set of locations aka assignment locations). This means that we can't find anything about not applying coercions outside those assignment locations in the language specification or any other specification document.

However, I believe that we _will_ specify this; in particular, there is no support for changing `Function f = callableObject..memberOnCallableObject();` into `Function f = (callableObject.call)..memberOnCallableObject();` and then report an error. In other words, we're almost certainly going to specify something like assignable locations and say that coercions only occur there, we're not likely to change the implementation to do exactly what is currently specified.

**Comment by chloestefantsova** [comment]
Thank you for the clarification, Erik, and for confirming that the existing CFE unit test should indeed be treated as expecting a compile-time error.

I'm working on the fix at https://dart-review.googlesource.com/c/sdk/+/292001.
