### ISSUE TITLE
Support spawnUri() with data: URLs, or add spawnSource() to the isolate library

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#5187]
It would be very useful to be able to resolve data: URLs in the VM. Most obviously, this would be useful for spawnUri, when you want to run a small program in an isolate. This is particularly true because it's difficult to determine where a relative URL would be resolved, and absolute URLs tend to be non-portable. But it would also be useful more generally.

**Comment by nex3** [comment]
This seems to have been fixed by fbc6b005a4f387d0a21af19b23e4f1d9325b735d. @rmacnak-google feel free to re-open if that's wrong.
