### ISSUE TITLE
Why can't you make a const string based on a const object?

### ISSUE THREAD

**Issue by 47b7b0** [dart-lang/sdk#51875]
Why can't you make a const string based on a const object?

```dart
class A {
  const A();

  @override
  String toString() {
    return 'A';
  }
}

void main() {
  const a = const A();
  const String s = '$a'; // static error
}
```

**Comment by eernstg** [comment]
Constant expressions is a very small subset of Dart, and they are basically a set of special cases where the semantics of _everything_ which is done is determined by the platform. For instance, we have the notion of an object or class with 'primitive equality', which is used to restrict constant expressions of the form `e1 == e2` such that their value can be computed at compile time (without ever running any code).

A string literal is similar: `'$a'` is a constant if `a` is a constant expression whose type belongs to a short whitelist, and `class A` isn't on that whitelist.
