### ISSUE TITLE
DAS needs if-case/switch pattern support for `MakeFinal`

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#51872]
![image](https://user-images.githubusercontent.com/67586/228097413-187161ba-e055-4823-b5a6-f1221a2ed8a2.png)

Follow-up from: https://github.com/dart-lang/sdk/issues/51863

(Will require a linter in DEPS that includes https://github.com/dart-lang/linter/pull/4225.)

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/292400
