### ISSUE TITLE
DAS needs impl or maybe just tests for ReplaceWithVar with variable declaration patterns

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51881]
https://github.com/dart-lang/linter/pull/4175 added linter support for `omit_local_variable_types` in variable declaration patterns. DAS should have support in ReplaceWithVar as well, I think.

**Comment by keertip** [comment]
We are good here. The quick fix will be shown if there this lint is triggered, it not there is no quick fix.

**Comment by keertip** [comment]
There is no fix to contribute if there is no diagnostic. So, no tests.
