### ISSUE TITLE
DAS needs impl or maybe just tests for ReplaceNullCheckWithCast with null-assert patterns

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51880]
https://github.com/dart-lang/linter/pull/4148 added linter support for `null_check_on_nullable_type_parameter` in null-assert patterns. I think DAS should have support to quick fix such patterns into cast patterns. I could be wrong that that is an appropriate fix...

**Comment by bwilkerson** [comment]
@munificent

**Comment by munificent** [comment]
Yeah, changing it from `!` to `as T` makes sense to me.

**Comment by keertip** [comment]
https://dart-review.googlesource.com/c/sdk/+/292100
