### ISSUE TITLE
unnecessary_import conflicts with deprecated_export_use

### ISSUE THREAD

**Issue by emersion** [dart-lang/sdk#51890]
**Describe the issue**

My code uses `BytesBuilder` from `dart:typed_data`, and other classes from `dart:io`. When importing explicitly `dart:typed_data`, the linter complains:

```
   info • The import of 'dart:typed_data' is unnecessary because all of the used elements are also provided by the import of
          'dart:io' • lib/link_preview.dart:3:8 • unnecessary_import
```

When removing the explicit import, the linter still complains:

```
   info • The ability to import 'BytesBuilder' indirectly is deprecated • lib/link_preview.dart:84:22 • deprecated_export_use
```

**To Reproduce**
Just use `BytesBuilder`.

**Expected behavior**
`unnecessary_import` should not be triggered.

**Comment by scheglov** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/302080

**Comment by MrCsabaToth** [comment]
I'm on Channel beta, 3.13.0-0.2.pre recent Flutter and have this problem. What's the solution?

**Comment by srawlins** [comment]
@MrCsabaToth can you give a complete reproduction of the issue you are seeing?

**Comment by MrCsabaToth** [comment]
> @MrCsabaToth can you give a complete reproduction of the issue you are seeing?

Scratch that. Now that I `import dart:typed_data;` besides the `io` package the analyzer is fine.
