### ISSUE TITLE
Breakpoints do not stop on record assignment

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51909]
Set a breakpoint in IntelliJ (well, you can't yet, but will be able to after the next plugin release) on an assignment statement with a RHS that is a record. Run to the breakpoint. Observe that execution stops at the next non-record-assignment.

The code in the screen shot was copied from the patterns spec, if you need it. Notice that all three assignments have been performed. I did not single-step at all. The breakpoint is on line 2; execution stopped on line 5.

<img width="1393" alt="Screenshot 2023-03-30 at 2 38 38 PM" src="https://user-images.githubusercontent.com/8518285/228970779-8f55543e-3677-4785-ae69-4a1a00798cc0.png">

TBH I'm not sure this is a real problem. But it looks odd.
@johnniwinther

**Comment by johnniwinther** [comment]
cc @alexmarkov

**Comment by jacob314** [comment]
Fyi @bkonyi 

Steve have you tested that code with DDC? It would be interesting to see if that is a VM only issue or not.
