### ISSUE TITLE
Generic type in extension is not inferred in some cases

### ISSUE THREAD

**Issue by kaboc** [dart-lang/sdk#51901]
```dart
extension Ext1<T> on ValueListenable<T> {
  S method<S>(S Function(T) callback) {
    return callback(value);
  }
}

...

ValueNotifier(123).method((v) => v * 2); // v is inferred as int.
```

```dart
extension Ext2<T, U extends ValueListenable<T>> on U {
  S method<S>(S Function(T) callback) {
    return callback(value); // value is correctly considered as type T here.
  }
}

...

ValueNotifier(123).method((v) => v * 2); // v is dynamic.
```

I think `v` in the second example above should be treated as int in the same way as in the first one. The analyzer knows that `value` is of type R in the body of the method, so I feel it should be possible to infer the type when the method is used too.

**Comment by kaboc** [comment]
The reason I tried Ext2 in addition to Ext1 is because when I have both Ext1 for ValueListenable and Ext3 below for Listenable in the same library, a call to an extension method on a ValueNotifier calls the method of Ext3, which I didn't expect to happen.

```dart
extension Ext3<T extends Listenable> on T {
  S method<S>(S Function(T) callback) {
    return callback(this);
  }  
}
```

- extension Ext1\<T> on ValueListenable\<T>
- extension Ext3\<T extends Listenable> on T

Comparing these two, `T` in Ext1 apparently has a closer relationship with ValueNotifier than `T` in Ext3 does. Is it another bug?

I came up with Ext2 after thinking about how to avoid it, but sadly I found it had the type inference issue described above. Although I know there are workarounds [here](https://dart.dev/language/extension-methods#api-conflicts), I don't want to force users of my package to do any workaround.

**Comment by eernstg** [comment]
For `Ext3`, `Listenable` is just a concise way to write `Listenable<S>` where `S` is chosen by an algorithm known as 'instantiation to bound'. If there is no bound then we get `Listenable<dynamic>`. In particular, an invocation would choose `T == ValueListenable<int>` for the invocation of `Ext3.method` as well as the invocation of `Ext1.method`.

This makes the two invocations equally specific in the first round. We then consider the 'instantiation to bound on-type' of the two extensions, namely `ValueListenable<dynamic>` for `Ext1` and `Listenable<dynamic>` for `Ext3`.

We can't conclude anything before the typing relationships between `Listenable` and `ValueListenable` are known, so we can't go further.

Do you have a small, self-contained example showing that `Ext1` is chosen over `Ext3`?

**Comment by kaboc** [comment]
Thank you for your explanation and the link to a helpful document.

For the first issue, Is it the only solution that the types are specified like `Ext2<int, ValueNotifier<int>>(ValueNotifier(123)).method((v) => v * 2);`? I was looking for a more concise way...

As for the second issue, I don't think `Listenable` (from the Flutter SDK) is a generic class unlike `ValueListenable`. The example below uses simplified versions of those classes.

```dart
abstract class Listenable {
  int count = 0;
}

abstract class ValueListenable<T> extends Listenable {
  T get value;
}

class ChangeNotifier implements Listenable {
  @override
  int count = 0;
}

class ValueNotifier<T> extends ChangeNotifier implements ValueListenable<T> {
  ValueNotifier(this.value);
  
  @override
  T value;
}

//-------------------------------------------------

extension Ext1<T> on ValueListenable<T> {
  S method<S>(S Function(T) callback) {
    return callback(value);
  }
}

extension Ext3<T extends Listenable> on T {
  S method<S>(S Function(T) callback) {
    return callback(this);
  }  
}

void main() {
  ValueNotifier(123).method((v) => v * 2); // I want to use the method of Ext1, but this is actually the one from Ext3.
}
```

**Comment by eernstg** [comment]
You get the extension method from `Ext3` because type inference chooses `T == ValueNotifier<int>` for the invocation using `Ext3`, and it chooses `T == int` for the invocation of `Ext2`, and this yields instantiated on-types of `ValueNotifier<int>` respectively `ValueListenable<int>`, and the former is more specific than the latter (it is a subtype, and that's what "more specific" means for an extension, except when we need a tie-breaker).

So that's working as intended, too.

**Comment by kaboc** [comment]
Thank you again. It is great that all the behaviors I mentioned are not bugs but as expected.

I feel it would be better if there was a more concise way than explicitly choosing which extension to use, but here is a not suitable place to discuss it. I'll close this issue, and make a feature request on the right repo if I still think it is necessary after thinking more about it.
