### ISSUE TITLE
No quick fix for `ParserErrorCode.INVALID_INSIDE_UNARY_PATTERN`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51915]
In d2184a9d03ac1368bd4b83c75fb128bbefdef82c, I added logic to report `ParserErrorCode.INVALID_INSIDE_UNARY_PATTERN` if the inner pattern of a unary pattern is either (a) another unary pattern, or (b) a relational pattern, and the inner pattern is not parenthesized.  The patterns spec prohibits these combinations, even though they can be successfully parsed.

It would be nice if this error had a quick fix that added the necessary parens.

**Comment by bwilkerson** [comment]
Is it always the case that the highlighted region is the whole pattern that needs to be inside parens?

**Comment by stereotype441** [comment]
> Is it always the case that the highlighted region is the whole pattern that needs to be inside parens?

Yes, I arranged the error reporting logic so that this is always the case.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/292981
