### ISSUE TITLE
JetBrains code formatter should use dartfmt

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#51911]
I've been using the default JetBrains formatter without realizing it, and there are cases where it tries to format the code even though it is invalid Dart code. I'd prefer if the "Format code" action used dartfmt instead.

Steps to reproduce:

1. Run `flutter create --empty new_project`
2. Open project in Android Studio / IntelliJ
3. Delete the closing paren for the `Scaffold` widget:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ,
    );
  }
}
```
4. Run the "Reformat Code" action (not "Reformat code with dartfmt")
5. Observe weird output:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp
    (
        home: Scaffold(
    body: Center(
    child: Text('Hello World!'),)
    ,
    ,
    );
  }
}
```

**Comment by srawlins** [comment]
Well, I guess that's a bug for JetBrains 😄  @stevemessick do you know where this should be directed?

**Comment by stevemessick** [comment]
I thought @alexander-doroshko had changed everything to use dartfmt years ago. But no, I can reproduce this problem.

Ideally, there would be an issue on https://youtrack.jetbrains.com to track this. @jwren might find this interesting, too.

**Comment by alexander-doroshko** [comment]
Thanks, it's already tracked in YouTrack. Some details [here](https://youtrack.jetbrains.com/issue/WEB-55062/IntelliJ-formatter-is-different-from-dart-format#focus=Comments-27-5858722.0-0) and [here](https://youtrack.jetbrains.com/issue/WEB-38773/When-the-Dart-formatter-is-set-to-dartfmt-it-appears-both-the-dart-plugin-code-formatter-and-dartfmt-are-run-one-after-another#focus=Comments-27-3717364.0-0). Sorry for the delay with these issues.

**Comment by srawlins** [comment]
Thanks @stevemessick and @alexander-doroshko . Closing here.
