### ISSUE TITLE
Hide console window option for the dart compile exe on Windows

### ISSUE THREAD

**Issue by zs-dima** [dart-lang/sdk#51922]
Might be nice to add options to `dart compile exe' to hide the console window.
    `dart compile exe ./bin/dart_app.dart -o dart-app.exe -no-window`

Current workarounds are not quite good:

1. `editbin` does not work with exetutables compiled with the latest dart, `Dart 2.19.6`
    `editbin.exe /subsystem:windows dart-app.exe`

3. Hiding windows on startup with `ffi` will still display a console window for a short time anyway.
    https://github.com/dart-lang/sdk/issues/41926

**Comment by bkonyi** [comment]
@aam is this something you might be able to take a look at? I don't currently have a Windows setup.

**Comment by aam** [comment]
@zs-dima wrote
> editbin does not work with exetutables compiled with the latest dart, Dart 2.19.6 editbin.exe /subsystem:windows dart-app.exe

What is the error that you see with `editbin.exe` against latest dart-generated executable?
I just tried latest dart with editbin from msvc 2022 and things work as expected

```
C:\src\d\dart-sdk\sdk>out\ReleaseX64\dart --version
Dart SDK version: 3.0.0-edge.e9cde3a829bfa5fac71a257e1c8caf0908c4ebcc (be) (Mon Apr 10 08:17:33 2023 -0700) on "windows_x64"
C:\src\d\dart-sdk\sdk>type hellowrite.dart
import 'dart:io';

main() {
        File("c:\\src\\hi.txt").writeAsStringSync('Hello ${DateTime.now()}');
}
C:\src\d\dart-sdk\sdk>out\ReleaseX64\dart-sdk\bin\dart compile exe hellowrite.dart
Info: Compiling with sound null safety.
Generated: c:\src\d\dart-sdk\sdk\hellowrite.exe

C:\src\d\dart-sdk\sdk>type c:\src\hi.txt
Hello 2023-04-11 11:03:04.879462
C:\src\d\dart-sdk\sdk>editbin /subsystem:windows hellowrite.exe
Microsoft (R) COFF/PE Editor Version 14.34.31937.0
Copyright (C) Microsoft Corporation.  All rights reserved.
```
<ran hellowrite.exe from Windows Explorer - no window is showing up as I ran it>
```
C:\src\d\dart-sdk\sdk>type c:\src\hi.txt
Hello 2023-04-11 11:03:34.432059
```

**Comment by aam** [comment]
@zs-dima please reopen once you have more data regarding issues with suggested solution of using `edtibin.exe`
