### ISSUE TITLE
`dart` tool tries to execute files without `.dart` extension

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#51932]
Version: Dart SDK version: 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "macos_arm64"

`dart` tries to execute any file with the name of the first command line argument as a Dart program. If, for example, a file named `format` exists in the working directory, `dart format .` tries to execute this file instead of running the `format` sub-command.

**Comment by a-siva** [comment]
> @a-siva @mit-mit, do we want to consider only supporting direct invocations of scripts (e.g., the basic `dart <script>` flow) with `.dart` extensions?

This would be a breaking change correct.

**Comment by lrhn** [comment]
We could also just hardcode the CLI command names in the VM, and let it trigger the CLI on any of those.
It would only break scripts named with short list of names, not ending in `.dart`.

**Comment by bkonyi** [comment]
Yes, it would technically be a breaking change in principle, but I imagine this is one of those situations where the actual impact would be quite small.

We could hard code the CLI command names, but then we have another list in the VM that can eventually get out of sync with the CLI. The root set of commands is fairly stable, so this is probably a reasonable approach, even if I find it a tad gross... :-)

**Comment by a-siva** [comment]
> We could hard code the CLI command names, but then we have another list in the VM that can eventually get out of sync with the CLI. The root set of commands is fairly stable, so this is probably a reasonable approach, even if I find it a tad gross... :-)

One option to keep it in sync would be to remove the dispatch code from the CLI code and instead have the VM call the CLI with the command to trigger so that the command selection code resides in only one place (the VM).

**Comment by jamesderlin** [comment]
> We could hard code the CLI command names, but then we have another list in the VM that can eventually get out of sync with the CLI. The root set of commands is fairly stable, so this is probably a reasonable approach, even if I find it a tad gross... :-)

I'm not familiar with the architecture of the CLI or VM, but if the CLI already knows the command names, why can't the CLI check if the argument matches a command name and pass it along to the VM only if it doesn't?

**Comment by sigurdm** [comment]
> One option to keep it in sync would be to remove the dispatch code from the CLI code and instead have the VM call the CLI with the command to trigger so that the command selection code resides in only one place (the VM).

That might work - but is not a trivial change, and there would still need to be a coordination between the VM and dartdev code to agree on which commands are parsed.

I landed [https://dart-review.googlesource.com/c/sdk/+/361363](https://dart-review.googlesource.com/c/sdk/+/361363) I think that is a good compromise. The vm still needs to run files with arbitrary extensions because we don't have a extension for snapshots, which the vm should also run.

Not sure if we want to close this issue, or do more here.

**Comment by bkonyi** [comment]
Yeah, I think this is a sufficient solution, especially since any user that _really_ wants to create a Dart script with no extension that happens to share the name of a CLI command can work around it by running `dart ./format` instead.
