### ISSUE TITLE
No quick fix for ParserErrorCode.LATE_PATTERN_VARIABLE_DECLARATION

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51931]
In 8d16c1dc871a42bb4f643d7c29a17148f0228935, I added error recovery logic to the parser to report `ParserErrorCode.LATE_PATTERN_VARIABLE_DECLARATION` if a pattern variable declaration statement included the keyword `late`.  Previously the parser would get confused and output several unhelpful errors.

It would be nice if this error had a quick fix that removed the keyword `late`.

The location associated with the error is the anomalous `late` keyword.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/293004
