### ISSUE TITLE
VmService access to annotations

### ISSUE THREAD

**Issue by pithuene** [dart-lang/sdk#51942]
There seems to be no way to access annotations on classes, functions, etc. through the `VmService` class.
As far as I can see this is also not included in the [Service Protocol Spec](https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md).

For some function with an annotation:
``` dart
class MyClass {
  @MyAnnotation()
  void myFunction() { ... }
}
```
I would like a way to access the `MyAnnotation` instance through a `FuncRef` to `myFunction`.
Is there some way to achieve this?

**Comment by a-siva** [comment]
//cc @derekxu16 @bkonyi

**Comment by bkonyi** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/41302.
