### ISSUE TITLE
No quick fix for `ParserErrorCode.DEFAULT_IN_SWITCH_EXPRESSION`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51953]
In a3f5cfdc7f272f94d333f3aab2217e25dd8d0a63, I added error recovery logic to the parser to report `ParserErrorCode.DEFAULT_IN_SWITCH_EXPRESSION` if a switch expression contains the keyword `default` in place of a pattern. Previously the parser would get confused and output several unhelpful errors.

It would be nice if this error had a quick fix that changed the keyword `default` to `_`.

The location associated with the error is the location of the anomalous `default` keyword.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/295390
