### ISSUE TITLE
CFE missing error for patterns

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#51969]
The test co19/LanguageFeatures/Patterns/scope_A01_t01 has the following expectation:

```dart
const c = 1;

test() {
  print(c);
//      ^
// [analyzer] unspecified
// [cfe] unspecified
  var [c] = [c];
//           ^
// [analyzer] unspecified
// [cfe] unspecified
  print(c);
}
```

The CFE currently prints no error on the first use of `c` in the method.  I believe this is intended to be an error (cc @munificent @eernstg to check me).  The analyzer currently makes this an error.

I don't think this is blocking for beta, marking it stable for now so that we track whether we want to consider this for a cherry pick (I'm initially inclined towards not).

cc @johnniwinther

**Comment by munificent** [comment]
I do see that CFE reports an error in:

```dart
const c = 1;

test() {
  print(c);
  var [c] = [1];
}
```

It reports the error on the `c` in `[c]` and not in the `print(c)`, but the language never specifies *where* an error is shown, just *that* some error must be shown in certain circumstances.

Likewise, it does show an error in:

```dart
test() {
  var [c] = [c];
}
```

And:

```dart
const c = 1;

test() {
  var [c] = [c];
}
```

So I think CFE is correctly reporting an error in all of the cases I can think of related to this test. We may just want to update the test expectations to have the error where CFE reports it.

**Comment by leafpetersen** [comment]
Sounds good to me, thanks.  I'll file a co19 issue.

**Comment by leafpetersen** [comment]
Filed https://github.com/dart-lang/co19/issues/2009
