### ISSUE TITLE
Incorrect completions after `:` in object and record patterns

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51961]
Reproduced in IntelliJ, but since completions are provided by the analysis server, I believe this is an analysis server issue.

Given the following code:
```dart
abstract class MyClass {
  int get foo;
}

f(Object o) {
  switch (o) {
    case MyClass(:var ) // (1)
  }
}
```
Place the cursor after `:var ` on the line marked (1), and request completions.

Expected result: the only completions should be the names of getters available on `MyClass`, for example `foo`.

Observed result: top level names are offered as completions (these would be invalid), and `foo` is not.

Note that things are worse in a declarartion context.  With this code:
```dart
abstract class MyClass {
  int get foo;
}

f(MyClass o) {
  var MyClass(:) = o; // (1)
}
```
if I place the cursor after the `:` on the line marked (1), no completions are offered.

Similar problems happen for record patterns.  In:
```dart
abstract class MyClass {
  int get foo;
}

f(({int foo, String bar}) o) {
  var (:) = o; // (1)
  switch (o) {
    case (:var ) // (2)
  }
}
```
if I place my cursor after the `:` on the line marked (1), or after `:var ` on the line marked (2), I would expect to be offered just `foo` and `bar` as completions, but instead I get top level names.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/293901 should help for completion inside object pattern.

I think record pattern completion was not yet implemented with enough coverage.
So, I will leave it out for now.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/293863 for record the record pattern example.

**Comment by leafpetersen** [comment]
Can I close this, or should I move it to stable to track possible further work that might need cherry picks?

**Comment by scheglov** [comment]
I was able to finish and land https://dart-review.googlesource.com/c/sdk/+/293863 only today, so for record patterns completion is not fully implemented. We might consider cherry picking this change. Other than that, I don't plan further work here.

**Comment by itsjustkevin** [comment]
Moving this to the cleanup milestone for cherry-pick consideration.

**Comment by vsmenon** [comment]
What's the status?  Is this fixed and just under CP consideration?

**Comment by scheglov** [comment]
Yes, it is implemented, but should be CPed.

**Comment by scheglov** [comment]
CP landed.
