### ISSUE TITLE
NPE in UserPromptPreferences

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#51968]
See https://github.com/dart-lang/pub/pull/3862

I think this is because we cannot get the location.
```dart
String? _getStandardStateLocation() {
  final Map<String, String> env = io.Platform.environment;
  if (env.containsKey('ANALYZER_STATE_LOCATION_OVERRIDE')) {
    return env['ANALYZER_STATE_LOCATION_OVERRIDE'];
  }

  final home = io.Platform.isWindows ? env['LOCALAPPDATA'] : env['HOME'];
  return home != null && io.FileSystemEntity.isDirectorySync(home)
      ? join(home, _serverDir)
      : null;
}
```

Maybe `LOCALAPPDATA` is not defined, or the target is missing or not a directory.

@DanTup

**Comment by jacob314** [comment]
If we don't know the home directory I think is better to not store a location than to use one that is unsafe. This API is nullable anyway so it seems like callers should just be handling null more gracefully.
In particular we could change
https://github.com/dart-lang/sdk/blob/cd7b4f8e4bf59f27475e4440f8de7995f1718d3c/pkg/analysis_server/lib/src/services/user_prompts/user_prompts.dart#L27
to avoid using `!`

**Comment by jcollins-g** [comment]
https://dart-review.googlesource.com/c/sdk/+/293920 fixes the immediate issue though @bwilkerson has some comments that should be addressed longer term to minimize spam in the instrumentation log.

**Comment by DanTup** [comment]
@jcollins-g thanks for looking at this!

I think I made a bad assumption that the server wouldn't run at all without access to this state folder, but I now see it creates an in-memory store for the driver state (`MemoryCachingByteStore`).

I suspect this issue might be restricted to bots (`LOCALAPPDATA` usually exists set by default), but just in case I think we'd be better not showing prompts at all if we're unable to persist the preferences (having a "Don't show again" button that doesn't work wouldn't be great). I'll make some changes to do that (it'll also avoid logging multiple times as @bwilkerson noted), although I suspect that's not critical for the beta given the fix above.

**Comment by DanTup** [comment]
Some tweaks at https://dart-review.googlesource.com/c/sdk/+/294000 that allow different preferences when there's no state location to when there's just no file. This will prevent a broken "do not show" button if this condition did occur for real users. Only a single entry will be written to the log in this case.

**Comment by DanTup** [comment]
(Closing, since this was fixed by https://github.com/dart-lang/sdk/commit/b6cf3f9c22cf6c83ae7f648b3441d9b8319a5de8)
