### ISSUE TITLE
Failures on [_fe_analyzer_shared] Handle empty types in exhaustiveness

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#51967]
There are new test failures on [[_fe_analyzer_shared] Handle empty types in exhaustiveness](https://dart-review.googlesource.com/c/sdk/+/293682).

The tests
```
co19/LanguageFeatures/Patterns/pattern_uses_A02_t03 Crash (expected Pass)
language/patterns/empty_switch_expression_weak_test Crash (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-linux-chrome-unsound
dart2js-hostasserts-linux-d8-unsound
```

**Comment by johnniwinther** [comment]
It looks like dart2js isn't happy about the empty switch expression `switch (throw '') {}`.

**Comment by sigmundch** [comment]
I'l close this issue in favor of the other one. Thankfully this only affects programs in weak-mode, so I expect this wont be visible externally where mixed programs are not supported.
