### ISSUE TITLE
How to implement a macos app to run as root priviledge?

### ISSUE THREAD

**Issue by irocn** [dart-lang/sdk#51974]
Hello,
I need to run a external cli command that need root priviledge, when I use the below code but it don't work
```
Process.start("my_cli", [],..)
```
I capture the stderr information is "Permission deny..."

It also don't work when I run it from terminal use sudo.
```
sudo open myapp.app
```
it still throw the permission deny issue.

Are three any solution to make the mac app with root priviledge? It will prompt to ask password when I double click it to run.

**Comment by a-siva** [comment]
@irocn are you doing this from a Flutter app or a simple command line Dart app ?
