### ISSUE TITLE
Missing "rename" quick-fix for `lowerCamelCase` lint occurrence

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#51995]
On the following code, I can quick-fix the `r_final_x`, but I can't quick-fix the `r_x`. If the lint shows up on both, both should be fixable, right?

```dart
Radius clampedEllipseRadius(double w, double h) {
  const double r_x = 100000000; // warning, can't be quick-fixed
  const double r_y = 1000; // warning, can't be quick-fixed
  const sqrt2 = 1.4142135623730951;

  final r_final_x = math.min(r_x, w / (2 * sqrt2)); // warning, can be quick-fixed
  final r_final_y = math.min(r_y, h / (2 * sqrt2)); // warning, can be quick-fixed
  
  return Radius.elliptical(r_final_x, r_final_y);
}
```

<img width="872" alt="image" src="https://user-images.githubusercontent.com/351125/230742219-be8c9a4c-cf9b-4e8d-a668-6e4c827b8369.png">

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/306670
