### ISSUE TITLE
Spurious `_` type on pattern-extracted variable from await-expression

### ISSUE THREAD

**Issue by gnprice** [dart-lang/sdk#52004]
The following code produces an error from the analyzer:
```dart
void main() async {
  final (:x) = await Future.value((x: 'abc'));
  x.length; // ERROR: The property 'length' can't be unconditionally accessed because the receiver can be 'null'.
}
```

In fact the type of `x` should be `String`, not a nullable type, and there should be no error.

This reproduces in the master channel on dartpad.dev, at 3.0.0-403.0.dev.

---

Further observations:

Putting the cursor on the variable `x` shows `_ x`, meaning that the type inferred for `x` is shown as `_`. It should be `String`.

The code runs fine; `print(x.length)` prints 3.

The issue doesn't reproduce if we don't use pattern-matching to unpack the record:
```dart
  final xr = await Future.value((x: 'abc'));
  xr.x.length; // ok
```

It also doesn't reproduce if we cut out the future and the await:
```dart
  final (:y) = (y: 'abc');
  y.length; // ok
```

Putting the cursor on those variables `xr` and `y` shows their types as `({String x})` and `String`, respectively, which are correct.

**Comment by lrhn** [comment]
The analyzer is *very* confused (based on DartPad and local 3.0.0-417.1.beta).

The code:
```dart
```
gives the following warnings
```
Analyzing anaweird.dart...

  error • anaweird.dart:3:8 • 'String Function(String)' doesn't conform to the bound 'dynamic Function(dynamic)' of the type
          parameter 'X'. Try using a type that is or is a subclass of 'dynamic Function(dynamic)'. •
          type_argument_not_matching_bounds
  error • anaweird.dart:4:3 • A method tear-off on a receiver whose type is 'dynamic' can't have type arguments. Specify the type of
          the receiver, or remove the type arguments from the method tear-off. • generic_method_type_instantiation_on_dynamic
  error • anaweird.dart:5:5 • The property 'arglebargle' can't be unconditionally accessed because the receiver can be 'null'. Try
          making the access conditional (using '?.') or adding a null check to the target ('!'). • unchecked_use_of_nullable_value

3 issues found.
```

The first two errors claim that `x` has type `dynamic`. That's supported by not complaining that `.arglebargle` doesn't exist.

Yet it allows invoking extension members on `x`, which you are not allowed to do on `dynamic`. (That does seem to be a general bug. The analyzer also allows `dynamic d = 0; d.st<Exactly<dynamic>>()`. So maybe a separate issue.)

The type of `x` should be `String`, and it is so in the front end.

**Comment by bwilkerson** [comment]
> Yet it allows invoking extension members on `x`, which you are not allowed to do on `dynamic`. (That does seem to be a general bug. The analyzer also allows `dynamic d = 0; d.st<Exactly<dynamic>>()`. So maybe a separate issue.)

I'm confused, and look forward to learning something. According to the language spec (section "20.7 Type dynamic"):

> The type `dynamic` is a static type which is a supertype of all other types, just like `Object`, but it differs from other types in that the static analysis assumes that every member access has a corresponding member with a signature that admits the given access.

I don't understand how the analyzer is suppose to know that `st` is defined by the extension and not part of the behavior of `d`.

For example, given
```dart
class C {
  void m() {}
}

extension<T> on T {
  void m() {}
}

void f(dynamic o) {
  o.m();
}
```

Couldn't the invocation of `m` be the `m` on `C` if `o` is an instance of `C`? Or does the fact that there's an extension method that can be found make the invocation invalid even though it's potentially ok?

**Comment by lrhn** [comment]
Ah, good point. The analyzer is accepting any call on `dynamic`, but it's not actually calling it so it won't err because there is no member. I got my wires crossed comparing the behavior of the analyzer and the dart2js output.

So the only error is that the analyzer infers the type `dynamic` where it should infer `String`.

**Comment by scheglov** [comment]
We have a bug in identifying "unknown" types, which we are still inferring, it misses the check for `RecordType`s.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/295102
