### ISSUE TITLE
Failures on [infra] Copy llvm-symbolizer to shards....Move and rewrite PrefixedNamespaceTest.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#52010]
There are new test failures on [[infra] Copy llvm-symbolizer to shards....Move and rewrite PrefixedNamespaceTest.](https://github.com/dart-lang/sdk/compare/dfea94f5de4d454e8391a6c029aa7401bd493d39~...956bb9ac5745ffca3b4ccaf7c561c93a4308042b).

The tests
```
vm/dart/v8_snapshot_profile_writer_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-mac-release-simarm64
```

It seems even after https://github.com/dart-lang/sdk/commit/9fc1f76e028c5aa5c5048c20a018ef5ed8681c85 landed, the `vm-aot-mac-release-simarm64` is still failing with an error indicating the `llvm-strip` binary isn't there.

@rmacnak-google Any ideas why your changes to the infra would cause this issue in the first place and why the fix didn't fix it?

**Comment by rmacnak-google** [comment]
Some of the test checks if clangBuildToolsDir exists, so I think before my changes the test was just skipping more. I'm still puzzled why llvm-strip appears to be missing when it is included in the fileset.
