### ISSUE TITLE
Renaming a variable declared in an object or record pattern with omitted name doesn't preserve semantics

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52014]
Starting with this Dart 3.0 code:
```dart
test(Map m) {
  for (var MapEntry(:key, :value) in m.entries) {
    print('$key: $value');
  }
}
```
If I place the cursor on one of the instances of `key` and use a rename refactor to change its name to `k`, the result is:
```dart
test(Map m) {
  for (var MapEntry(:k, :value) in m.entries) {
    print('$k: $value');
  }
}
```
which has a compile time error because the `MapEntry` class doesn't define a getter `k`.  IMHO the rename should produce:
```dart
test(Map m) {
  for (var MapEntry(key: k, :value) in m.entries) {
    print('$k: $value');
  }
}
```
There's a similar problem with named fields in record patterns.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/295101
