### ISSUE TITLE
[CP] Patterns flow analysis: recognize `[...]` (and related patterns) as trivially exhaustive.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52018]
### Commit(s) to merge

dc639c13cb7edc673f609259755e1fe0a95703d6

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/294682

### Issue Description

With the current beta channel, list patterns containing a single rest pattern are not recognized by flow analysis as trivially exhaustive.  As a result, a switch statement like the following will not be recognized by flow analysis as exhaustive:
```dart
f(List<Object> x) {
  String description;
  switch (x) {
    case [_]:
      description = 'one element';
    case [...]:
      description = 'some other number of elements';
  }
  print(description);
}
```
And thus there will be an error at the print statement claiming that `description` hasn't been definitely assigned.

Worse yet, if the user attempts to fix the problem by adding, e.g.:
```dart
    default:
      throw 'unreachable';
```
then the exhaustiveness checker will (correctly) report a warning that this default case is unreachable.

This affects all platforms, but only programs which use the patterns feature of Dart 3.0.

### What is the fix

The fix is to add some logic to flow analysis to understand that a list pattern containing a single rest pattern can be exhaustive.  Although the CL affects 89 lines, 86 of those are in tests; it is a 3-line fix.

### Why cherry-pick

- The risk to existing users is low, since we haven't yet released a stable version of Dart that supports the patterns feature.
- The fix improves usability, by making the analysis agree with user intuition and by avoiding confusing and conflicting error messages.
- If this fix is not cherry-picked prior to the stable release, then the fix will have to be re-done in such a way that it only applies when the Dart language version is 3.1 or higher; this will add implementation and maintenance effort.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52017

**Comment by mit-mit** [comment]
We should pick this.

**Comment by vsmenon** [comment]
@leafpetersen - can you take a quick look?

**Comment by leafpetersen** [comment]
LGTM

**Comment by vsmenon** [comment]
Thanks - lgtm.
