### ISSUE TITLE
Extract variable refactor should create variables inside of switch statement

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52015]
Given the following Dart 3.0 code:
```dart
test(Object o) {
  switch (o) {
    case int():
      print(o + 1);
  }
}
```
If I select the text `o + 1` and perform an "extract variable" refactor, I get:
```dart
test(Object o) {
  var object = o + 1;
  switch (o) {
    case int():
      print(object);
  }
}
```
Which has a compile time error, because at the site of `var object = o + 1;` the variable `o` is not known to be an `int`.

I would have expected this instead:
```dart
test(Object o) {
  switch (o) {
    case int():
      var object = o + 1;
      print(object);
  }
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/295100
