### ISSUE TITLE
[CP] Fix compiler crash when unboxed record is used in a try block

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#52012]
### Commit(s) to merge

b6b8b00daa93abc68d6adb99e7676274a53b2cce

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/294560

### Issue Description

Compiler crashed when call to a method returning an unboxed record occurred inside `try` block.

### What is the fix

Environment used by exception handling is now copied from the call to `AllocateSmallRecord` instruction when boxing a record return value.

### Why cherry-pick

Compiler crash can affect users which use both records and `try` blocks.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51972

**Comment by a-siva** [comment]
lgtm
