### ISSUE TITLE
Create documentation for and improve bot configuration for analyzer

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#52033]
During the 3.0 push it was identified that many analyzer team members don't have sufficient understanding of what tests get run on which bots, how to check them, and how to alter the configuration of bots to improve test performance.   There may also be gaps in the team's knowledge as a whole where none of us actually know critical pieces of this.  An analyzer-team specific document that covers frequently encountered problems, links to relevant dashboards and configuration files, and gives some examples might be helpful here.   Writing this document may also identify areas in which the system could be improved to be more intuitive.

**Comment by keertip** [comment]
/cc @athomas , @whesse 

We had to reach out to the infra team to figure out how to get to the test failure logs/messages, as sometimes clicking on the links did not end up with anything useful.

Is there any documentation on how to navigate through the build bots?
