### ISSUE TITLE
failed to transfer SendPort to dart from c

### ISSUE THREAD

**Issue by LF-H** [dart-lang/sdk#52047]
failed to transfer SendPort to dart from c,use sample code as follow:
https://github.com/dart-lang/sdk/tree/master/samples/ffi/async
thank you!

**Comment by vsmenon** [comment]
Can you be more specific?  What in particular is failing?  What version of Dart are you on?

**Comment by LF-H** [comment]
> Can you be more specific? What in particular is failing? What version of Dart are you on?

Thanks for the reply, I got the value of receive_port_ through Dart_NewNativePort_DL. But the execution to Dart_PostCObject_DL will return an error, so it prompts "Failed to send message, invalid port or isolate died".
When I create Dart_Handle through Dart_NewSendPort, I am prompted, "Isolate is not created or Dart_EnterScope is not executed"
I create an Isolate through Dart_CreateIsolateGroup, and when compiling, I am prompted that "Dart_CreateIsolateGroup is not defined"
I have copied files such as dart_api.h, so I currently don't know how to create the Isolate correctly.
The code uses PendingCall as shown below:
`class PendingCall {
 public:
  PendingCall(void** buffer, size_t* length)
      : response_buffer_(buffer), response_length_(length) {
    receive_port_ =
        Dart_NewNativePort_DL("cpp-response", &PendingCall::HandleResponse,
                              /*handle_concurrently=*/false);
  }
  ~PendingCall() { Dart_CloseNativePort_DL(receive_port_); }

  Dart_Port port() const { return receive_port_; }

  void PostAndWait(Dart_Port port, Dart_CObject* object) {
    std::unique_lock<std::mutex> lock(mutex);
    
    const bool success = Dart_PostCObject_DL(port, object);
    if (!success) FATAL("Failed to send message, invalid port or isolate died");

    printf("C   :  Waiting for result.\n");
    while (!notified) {
      cv.wait(lock);
    }
  }

  static void HandleResponse(Dart_Port p, Dart_CObject* message) {
    if (message->type != Dart_CObject_kArray) {
      FATAL("C   :   Wrong Data: message->type != Dart_CObject_kArray.\n");
    }
    Dart_CObject** c_response_args = message->value.as_array.values;
    Dart_CObject* c_pending_call = c_response_args[0];
    Dart_CObject* c_message = c_response_args[1];
    printf("C   :   HandleResponse (call: %" Px ", message: %" Px ").\n",
           reinterpret_cast<intptr_t>(c_pending_call),
           reinterpret_cast<intptr_t>(c_message));

    auto pending_call = reinterpret_cast<PendingCall*>(
        c_pending_call->type == Dart_CObject_kInt64
            ? c_pending_call->value.as_int64
            : c_pending_call->value.as_int32);

    pending_call->ResolveCall(c_message);
  }

 private:
  static bool NonEmptyBuffer(void** value) { return *value != nullptr; }

  void ResolveCall(Dart_CObject* bytes) {
    assert(bytes->type == Dart_CObject_kTypedData);
    if (bytes->type != Dart_CObject_kTypedData) {
      FATAL("C   :   Wrong Data: bytes->type != Dart_CObject_kTypedData.\n");
    }
    const intptr_t response_length = bytes->value.as_typed_data.length;
    const uint8_t* response_buffer = bytes->value.as_typed_data.values;
    printf("C   :    ResolveCall(length: %" Pd ", buffer: %" Px ").\n",
           response_length, reinterpret_cast<intptr_t>(response_buffer));

    void* buffer = malloc(response_length);
    memmove(buffer, response_buffer, response_length);

    *response_buffer_ = buffer;
    *response_length_ = response_length;

    printf("C   :     Notify result ready.\n");
    notified = true;
    cv.notify_one();
  }

  std::mutex mutex;
  std::condition_variable cv;
  bool notified = false;

  Dart_Port receive_port_;
  void** response_buffer_;
  size_t* response_length_;
};`

thanks for help。

**Comment by a-siva** [comment]
//cc @aam

**Comment by aam** [comment]
@LF-H sorry it took a while to get back to your issue.
Are you still facing the problem?

You can take a look at dart sdk test code to see how you can create isolates: https://github.com/dart-lang/sdk/blob/a155e2b521088d38/runtime/bin/ffi_test/ffi_test_functions_vmspecific.cc#L356 for example.
