### ISSUE TITLE
Incorrect completions after `:` in an irrefutable object pattern

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52059]
In an irrefutable context, e.g.:
```dart
f(Map m) {
  // Place cursor after `MapEntry(:` and ask for completions
  for (var MapEntry(:) in m.entries) {

  }
}
```
completion offers `final` and `var`, neither of which are valid.  Instead, the valid getters from `MapEntry` should be shown (but not the methods--see https://github.com/dart-lang/sdk/issues/52058).

(Note that in a refutable context, `final` and `var` _are_ valid completions.)

Reproduced at fa3a72fa7e5818e15118044ddd68a2c2ad2dfcd0

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/296501
