### ISSUE TITLE
Compiler wrongfully reporting error when destructuring sealed class

### ISSUE THREAD

**Issue by maxluchterhand1** [dart-lang/sdk#52055]
Consider the following piece of code

```
sealed class Base {}

class A extends Base {
   A(this.value);

  final int value;
}

class B extends Base {
  B(this.value);

  final int value;
}

class C extends Base {
  C(this.value);

  final int value;
}


void main() {
  final Base state = A(1);
  final _ = switch (state) {
    A(value: final value) ||
    C(value: final value) ||
    B(value: final value) =>
    value,
  };
}
```

When you run this, you will get the following error:

> Error: Variable pattern 'value' doesn't have the same type or finality in all cases.
>     A(value: final value) ||
>                    ^^^^^

Edit:
I was initially misled to believe this error was produced by matching the same subtype twice with different destructuring. However, I realized that this error also occurs with only one case per subtype and identical destructuring. I thus edited this issue to reflect that.

**Comment by eernstg** [comment]
Each of the operands of the logical-or pattern introduces a final variable of type `int`, so the CFE should not report an error claiming that they have different finality or type.

The error message 'Variable pattern 'value' is missing...' in the second example is fine, and the CFE does report that one.

**Comment by chloestefantsova** [comment]
I believe this is fixed in https://github.com/dart-lang/sdk/commit/b9b1fdff76d21012dfe9dad213f3a6aed6adfb61. Please reopen the issue if needed.
