### ISSUE TITLE
Methods shouldn't be offered as completions inside an object pattern

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52058]
Asking for completions inside an object pattern often gives way more possibilities than are warranted.  For example, in this code:
```dart
f(Map m) {
  for (var MapEntry() in m.entries) {

  }
}
```
Place the cursor between the parentheses of `MapEntry()` and request completions.

Observed behavior: the completions that are offered are (in order):
- `hashCode`
- `key`
- `runtimeType`
- `toString()`
- `value`
- `noSuchMethod(...)` (completes to `noSuchMethod(invocation)`)

Expected behavior: the most likely completions are `key` and `value` (the getters from the class `MapEntry` itself); they should be prioritized highest.  After that, `hashCode` and `runtimeType` (the getters from supertypes*).  Methods shouldn't be offered as completions at all, since accepting them just leads to syntax errors**.

So IMHO the offered completions should be:
- `key`
- `value`
- `hashCode`
- `runtimeType`

A similar behavior happens after `:var` in a refutable type, e.g.:
```dart
f(Object o) {
  switch (o) {
    // Place cursor before `):` and ask for completions
    case MapEntry(:var ):
  }
}
```

*It would be nice if the getters were sorted by how "far away" they are in the class hiesarchy, so that `hashCode` and `runtimeType` are always listed last, but I think this is lower priority.
**Technically, it would be valid to complete to tearoffs of `toString` or `noSuchMethod` (i.e. no parentheses), but I personally think it's so unusual that anyone would want to do this on purpose that it's better not to offer them as completions at all.

Reproduced with fa3a72fa7e5818e15118044ddd68a2c2ad2dfcd0.

**Comment by pq** [comment]
@bwilkerson I marked this as a `P1` as an "Automation resulting in corrupted code from clean inputs, edge cases or with an easy workaround" per the [triage doc](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/TRIAGE.md). Feel free to nudge if you feel otherwise.
