### ISSUE TITLE
[analyzer][Class modifiers] No error if base class is indirectly implemented

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52056]
The following co19 tests fail in both analyzer and CFE
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Class-modifiers/basic_restrictions_A03_t08.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Class-modifiers/basic_restrictions_A03_t09.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Class-modifiers/basic_restrictions_A03_t10.dart

The code looks like
```dart
// class_modifiers_lib.dart
base class BaseClass {}

// test.dart
import "class_modifiers_lib.dart";

base class ExtendsBaseClass extends BaseClass {}

base class IndirectlyImplementsBaseClass implements ExtendsBaseClass {}
//                                                  ^^^^^^^^^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
```

No expected errors produced. But according to the [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md#syntax)

> It's a compile-time error if:
> ... 
> A declaration implements another declaration, and the other declaration itself, or any of its super-declarations, are marked base or final and are not from the first declaration's library

Tested on the edge SDK (April 17, 2023) on Linux x64

**Comment by eernstg** [comment]
If this is handled by `_fe_analyzer_shared` then 'area-meta' may be actionable. If it is handled separately by the common front end and the analyzer then we should have a sub-issue for each of those tools.

@johnniwinther, @stereotype441, WDYT?

**Comment by eernstg** [comment]
@kallentu, maybe you're the one who knows best?

**Comment by stereotype441** [comment]
@eernstg FYI, I recently created an `area-fe-analyzer-shared` label for issues affecting the shared code.  I'll apply that label to this issue now.  (@kallentu I don't actually know if you implemented this logic in a shared way or not; feel free to adjust the labels as appropriate).

**Comment by eernstg** [comment]
We'd have two-or-more issues in the case where a given implementation effort takes place in two-or-more different portions of source code, because it's difficult to determine the right time to close the issue if one job is done and another is not. I guess that's not important in this case.

**Comment by scheglov** [comment]
Was fixed as https://github.com/dart-lang/sdk/issues/52160.
