### ISSUE TITLE
[CP] [beta] [analysis_server] Prevent "dart fix" prompts if do-not-show preferences cannot be persisted

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52061]
### Commit(s) to merge

da1898e0c76e9eb9bd33392a65f44c43edb9bf39

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/295521

### Issue Description

The issue is that users could see repeated prompts about being able to run "dart fix" despite clicking "Don't show again" when the server is running in a way that cannot persist the preference.

### What is the fix

The fix is to never try to show prompts in cases where the "Don't show again" preference would not be persisted.

### Why cherry-pick

Showing the user a prompt repeatedly after they click "Don't show again" would be frustrating and appears as if their preference is being ignored.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51968

### Extra Info

The original issue was a crash. The fix for the crash made it into beta, but in a way that could cause duplicate prompts. This change disables the prompt entirely in cases where the preference would not be persisted.

FYI @bwilkerson

**Comment by mit-mit** [comment]
SGTM
