### ISSUE TITLE
assist(s) to convert from if-else statements to switches (and back)

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#52068]
Related to https://github.com/dart-lang/sdk/issues/52025, notes from @leafpetersen:

## Convert between if then else statements and switches.  

This could be generalized to multiple cases/branches for certain kinds of things, but it gets a bit tricky to make sure that the semantics don't change.

```dart
if (e is Foo()) {

} else {

}
```

<->

```dart
switch (e) {
  case Foo():
  default: 
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/295724

**Comment by bwilkerson** [comment]
Note that the example isn't valid code. I suspect it was intended to be `if (e is Foo)`.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/296067

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/297140

**Comment by scheglov** [comment]
![20230421-switch-if-case](https://user-images.githubusercontent.com/384794/233728334-e2e96f82-81d1-4828-8a78-2e5672e3f3ba.gif)
