### ISSUE TITLE
[CP] [beta] [analysis_server] Prevent colon from automatically triggering completion in switch statements

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52063]
### Commit(s) to merge

cf8aaebc4a98f5c6533604a87120057253370539

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/295620

### Issue Description

When typing colons in switch case statements, code completion is automatically triggered:

<img width="295" alt="Screenshot 2023-04-17 at 15 07 05" src="https://user-images.githubusercontent.com/1078012/232508818-10f35b85-de68-43b5-b495-d139432c1b84.png">

Pressing `<enter>` will automatically accept this completion, inserting `break` where the user was probably trying to add a newline.

### What is the fix

The fix is to prevent colons from triggering code completion inside switch case.

### Why cherry-pick

Avoids frustration of having unwanted/unexpected code inserted while typing.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51980

### Extra Info

This was noticed in the issue above (although the issue itself was about the ranking of `break`).

FYI @bwilkerson

**Comment by mit-mit** [comment]
SGTM
