### ISSUE TITLE
Incorrect `WarningCode.CONSTANT_PATTERN_NEVER_MATCHES_VALUE_TYPE` for `null`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52060]
This code:
```dart
class C {
  void Function()? callback;
}

f(Object o) {
  switch (o) {
    case C(callback: null): // (1)
  }
}
```
Produces the diagnostic `WarningCode.CONSTANT_PATTERN_NEVER_MATCHES_VALUE_TYPE` at (1).

There should not be any warning; `callback` is nullable, so `null` is a possible match.

Reproduced with fa3a72fa7e5818e15118044ddd68a2c2ad2dfcd0.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/298280
