### ISSUE TITLE
[CP] Update --enable-analytics to re-enable unified analytics

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#52072]
### Commit(s) to merge

3149f813bbfb5ded1c66bb0784ef35af8d1b3aae

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/295723

### Issue Description

The existing implementation for unified analytics does not allow a user to opt-in if they had previously opted out. 

### What is the fix

Add a call to unified_analytics that sets reporting to true.  This will not override the usual consent mechanism nor the requirement that a message be displayed.

### Why cherry-pick

This will impact a small number of users who think they have opted-back in to analytics, when in reality, analytics will remain disabled.   Collecting data from all users that have opted in would improve analytics for the analysis server.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52070

### Extra Info

There is no test for this CL directly, but the call that was added is well tested elsewhere.   I tested it end-to-end by hand as part of the cherry pick just to be extra certain, and verified that the file update works.

**Comment by mit-mit** [comment]
We should pick this.

**Comment by athomas** [comment]
LGTM
