### ISSUE TITLE
[CFE, Analyzer] Error message on `abstract sealed class` should lead the user to success

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#52073]
Currently, the error message for when a user writes `abstract sealed class` simply tells the user that it's not allowed, e.g.:

```
 error • example.dart:61:10 • A class can't be declared both 'sealed' and 'abstract'. Try removing the 'abstract' or
          'sealed' keyword. • abstract_sealed_class
```

This may lead the user to believe that they cannot have a class which is both abstract and sealed (incorrect) instead of to the correct conclusion which is that sealed classes are already abstract.  It seems to me it would be more likely to lead the user to the correct outcome if the error message assumed that the user wanted an abstract sealed class (after all, that's what they wrote) and pointed them in the correct direction, something like:

```
A `sealed` class cannot be marked `abstract` since it is already implicitly abstract.  Try removing the `abstract` keyword.
```

cc @bwilkerson @johnniwinther @munificent @kallentu WDYT?

**Comment by bwilkerson** [comment]
Your suggestion lgtm.
