### ISSUE TITLE
telemetry / analytics flags in dartdev are confusing and incomplete

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#52087]
We have --enable-analytics, --disable-analytics, and --disable-telemetry.   The two disable flags actually do the same thing.   There is no corresponding enable for disable-telemetry even though enable-analytics does what we want here.   Changing the telemetry flag will require a PDD revision.

**Comment by parlough** [comment]
@bkonyi Did your work in https://github.com/dart-lang/sdk/commit/12e52d8fde254a0aad0102223324f7aa953146c3 fix this? It seems so.

**Comment by parlough** [comment]
I'm going to close this as fixed by https://github.com/dart-lang/sdk/commit/12e52d8fde254a0aad0102223324f7aa953146c3  which switches dartdev to use `package:unified_analytics` and removes the `--disable-telemetry` flag.

Please reopen if you think there is more to do here :)
