### ISSUE TITLE
`unnecessary_cast` false positive when cast affects inferred type

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#52086]
**Describe the issue**

`x as T` seems to trigger an `unnecessary_cast` lint if the static type of `x` is statically known to be a subtype of `T`.  Although such a cast superficially seems pointless, there can be cases where the cast makes a difference.  For example, consider:

```dart
var record = (1, 2, 3);
```
The inferred type of `record` is `(int, int, int)`.  If I want one of the members to be a `num`, I could explicitly specify the `Record` type:
```dart
(int, num, int) record = (1, 2, 3);
```
but that becomes awkward, tedious, and potentially error-prone if the `Record` has many members.  I alternatively could do:
```dart
num x = 2;
var record = (1, x, 3);
```
which I suppose is okay, but it's more verbose and requires naming more things.  I'd rather do:
```dart
var record = (1, 2 as num, 3);
```
The last version, however, triggers the `unnecessary_cast` lint (using DartPad based on Flutter 3.10.0-4.0.pre Dart SDK 3.0.0-431.0.dev).

**To Reproduce**

See above.

**Expected behavior**

Ideally the `unnecessary_cast` lint would trigger if and only if removing the cast has no effect.

I admit that this sort of situation probably isn't likely to occur much in practice.

**Comment by srawlins** [comment]
> If I want one of the members to be a `num`,

Can you give an example of when you want this? There are many examples of unnecessary_cast false positives (https://github.com/dart-lang/sdk/issues/44411, https://github.com/dart-lang/sdk/issues/48984, https://github.com/dart-lang/sdk/issues/49269, https://github.com/dart-lang/sdk/issues/49550), but I'm looking for some code that becomes an error without that `as num`.

**Comment by eernstg** [comment]
```dart
class A<X extends A<X>> {}
class B extends A<B> {}
class C extends B {}

void f<X extends A<X>>(X x) {}

void main() {
  f(B()); // OK.
  f(C()); // Couldn't infer type parameter `X`.
  f(C() as B); // OK, but 'unnecessary_cast'.
}
```

**Comment by jamesderlin** [comment]
> Can you give an example of when you want this?

A trivial example:
```dart
void main() {
  var record = (1, 2 as num);
  record = (1, 3.1415);
}
```
It doesn't seem too far-fetched that such a re-assignment might come about in something like:
```dart
final recordStore = <(int, num)>[];

bool somePredicate(int x) => false;

void main() {
  var record = (0, 0 as num); // Default value.
  for (var r in recordStore) {
    if (somePredicate(r.$1)) {
      record = r;
      break;
    }
  }

  // Do something with the found `record`.
}
```
