### ISSUE TITLE
analysis server + intelliJ + `final class` – code navigation stops working

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#52093]
This file: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart

As is: code navigation just doesn't work.

If I remove the two instances of `final` class – works like a champ!

From analysis server status thingy

Status
Server type: LegacyAnalysisServer
Server process ID: 62245

Versions
Analysis server version: 1.34.0
Dart SDK: 3.1.0-12.0.dev (dev) (Mon Apr 17 06:30:42 2023 -0700) on "macos_arm64"

**Comment by kevmoo** [comment]
https://user-images.githubusercontent.com/17034/232957222-e24c748d-2240-42c8-9698-c1bf63027c4a.mov

**Comment by srawlins** [comment]
CC @jwren 

@kevmoo can you also show your version of IntelliJ?

**Comment by kevmoo** [comment]
IntelliJ IDEA 2022.1.3 (Ultimate Edition)

**Comment by srawlins** [comment]
I'm initially marking this as P1 at least for diagnosis; we should figure out why this is happening quickly, in case there is something we need to cherry-pick into Dart 3.0.

**Comment by srawlins** [comment]
CC @bwilkerson @kallentu in case this is not IntelliJ-specific.

**Comment by alexander-doroshko** [comment]
@kevmoo If you need to stay with IntelliJ IDEA 2022.1.x then please update to the latest version of that branch, which is 2022.1.4. After that you'll be able to use the latest Dart plugin for that branch, which has version 221.6103.1. I believe you won't have this problem with these versions of the IDE and the plugin.

Also you may consider updating the IDE. The most current version is 2023.1, and it is three major versions ahead of the one that you currently use.

**Comment by alexander-doroshko** [comment]
Update: I've verified and confirmed that the old version of the Dart plugin doesn't support the fresh [Class modifiers](https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md) feature, and that the up-to-date versions work fine.

The minimal IDE version you need to have to get the up-to-date Dart plugin is IntelliJ IDEA 2022.1.4 or Android Studio Electric Eel (2022.1.x)

**Comment by bwilkerson** [comment]
Thanks for checking on that!

**Comment by kevmoo** [comment]
Confirmed everything is fine in the latest. Thanks!

**Comment by jwren** [comment]
Thank you Alex!
