### ISSUE TITLE
[CP] Remove restriction on implementing StreamView.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#52107]
### Commit(s) to merge

b0260187e78c0afe7462cbd4b3f95c28bbf30885

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/296584

### Issue Description

Remove restriction on implementing `StreamView`.
It was unnecessary, and negatively affects subclass creators, which have to add `base` or `final` to their classes,
with no actual benefit.
(The Dart class modifiers do not support saying that *this particular* class isn't intended as an interface, without also saying it for all subclasses. The class was using `base` only in the former sense.)

### What is the fix

Remove the `base` modifier from `class StreamView`.

### Why cherry-pick

It affects subclasses in packages that we want to migrate real-soon-now.

There is absolutely no risk, all this change does is *remove* a restriction. All existing code stays valid.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/async/issues/238

**Comment by mit-mit** [comment]
SGTM

**Comment by lrhn** [comment]
Landed

**Comment by itsjustkevin** [comment]
Reopening.  Let’s keep this open until we are sure it’s landed on the beta branch.

**Comment by lrhn** [comment]
ACK. It's landed on the beta branch now, but hasn't been part of a release.
