### ISSUE TITLE
[CP] Report PATTERN_NEVER_MATCHES_VALUE_TYPE for RecordType(s)

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52103]
### Commit(s) to merge

4ba4d11aea49ad620b316ad4794f5c83069b298b

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/296400

### Issue Description

We report a hint when the matched value type can never match the specified pattern type.
We already have such check for interface types in beta, this change expands it to record types.
Not critical, but nice to have a guardrail for a new kind of types, to avoid potential frustration "Why this does not match?!"

### What is the fix

We check that two record types have the same shape, and corresponding fields can match each other (recursively).

### Why cherry-pick

Improve UX around new kind of types.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51893

**Comment by shilangyu** [comment]
I tried the latest master build (`3.2.0-77.0.dev`) and this warning does not seem to be raised. Example:

```dart
  final  _ = switch((param1: '', param2: '')) {
     (:final param1) => print('found $param1'),
      _ => print('not found'),
  };
```
The first branch will never match, but no warning is reported. Let me know if this is expected or I should open a new issue about it.

**Comment by itsjustkevin** [comment]
@shilangyu as this issue is stale and has been closed for a while, opening a new issue would be a great approach.  Thank you for calling this out.
