### ISSUE TITLE
Can Dart support Arduino ESP32 or Raspberry Pi?

### ISSUE THREAD

**Issue by fangjunai** [dart-lang/sdk#52105]
Can Dart support Arduino ESP32 or Raspberry Pi?

**Comment by fangjunai** [comment]
I mainly use it for IoT,
If Arduino ESP32 can be implemented, it would be better and cheaper

**Comment by mraleph** [comment]
We have no current plans of porting and supporting Dart on ESP32. We experimented with this space [before](https://github.com/dart-archive/sdk), but discontinued out efforts to avoid spreading ourselves too thin.

**Comment by krispypen** [comment]
looks like Swift is adding support for ESP32 with RISC-V https://www.swift.org/blog/embedded-swift-examples/
