### ISSUE TITLE
`standalone/io/http_big_header_test` Timeout on `vm-aot-linux-release-simarm_x64`

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#52110]
There are new test failures on [[pkgs/native] MacOS support + CI](https://github.com/dart-lang/sdk/commit/4cb4d5d0361c064d2dfa37c1cb193c79c581de5d).

The tests
```
standalone/io/http_big_header_test Timeout (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-simarm_x64
```

**Comment by dcharkes** [comment]
This test is meta-flaking: https://dart-ci.web.app/#showLatestFailures=false&test=standalone/io/http_big_header_test&configurations=vm-aot-linux-release-simarm_x64

**Comment by alexmarkov** [comment]
The test still times out sometimes: https://dart-ci.appspot.com/log/vm-aot-linux-release-simarm_x64/vm-aot-linux-release-simarm_x64/1697/standalone/io/http_big_header_test.

**Comment by derekxu16** [comment]
happened again: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-aot-linux-release-simarm_x64/1842/overview

**Comment by a-siva** [comment]
@brianquinlan we seem to be seeing timeouts in this test frequently on the simarm configuration, does this test need to be marked slow for all simulator configurations or potentially be skipped ?

**Comment by brianquinlan** [comment]
I think that I can restructure this test to more directly (and efficiently) verify the behavior that we want to verify.

**Comment by a-siva** [comment]
We seem to be running into this frequently, raising priority of issue to P2.

**Comment by brianquinlan** [comment]
The test takes 1.4s to complete on my Mac.

**Comment by a-siva** [comment]
> The test takes 1.4s to complete on my Mac.

Did you try the failing configuration (vm_aot_linux_simarm_x64)

**Comment by brianquinlan** [comment]
I ran it 3 times on luci  (for vm_aot_linux_simarm_x64) with times of 2:12.31, 2:15.44 and 2:17.47. So it's about 100x slower than when I run it on my mac.

**Comment by a-siva** [comment]
Looks like the test is passing on all the configurations it is running.
