### ISSUE TITLE
[CP][beta channel] Update dart_style to latest rev

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#52111]
Cherrypick CL: https://dart-review.googlesource.com/c/sdk/+/297240

**commit(s) to merge**: [b9fa34d40ad3661ede60767b887577cb24425bb1](https://dart.googlesource.com/sdk/+/b9fa34d40ad3661ede60767b887577cb24425bb1)

**merge instructions**: It's a one line DEPS change, so should merge trivially.

**What is the issue**: There are two minor aesthetic problems with how records are formatted:

```dart
// Single-cascade sections after records:
(
  1,
  2,
)
    ..cascade();

// Non-block-like formatting for records in argument lists:
error(
    offset: 10,
    (
      code: 'unclosed-block',
      message: 'Block was left open',
    ));
```

**What is the fix**: This fixes those two problems:

```dart
// Don't split before single cascades on records:
(
  1,
  2,
)..cascade();

// Block-like formatting for records in argument lists:
error(offset: 10, (
  code: 'unclosed-block',
  message: 'Block was left open',
));
```

**Why cherrypick**: This makes record formatting consistent with how other collections are formatted. It will reduce churn if we change this formatting in a later release since right now there are very few record expressions in the wild. It's a pretty safe change to cherry pick.

**Risk**: Low. It's possible that the formatting changes introduce some other bug, but all existing and new tests are passing, and the two changes are quite small:

https://github.com/dart-lang/dart_style/commit/80288efabeebffd2d3a520c28c2c0bb09f09009c
https://github.com/dart-lang/dart_style/commit/6c9bc10cf2dc6496b2ce863c8d614aa0781abf90

The second change is a one-liner that exactly matches how other collections are handled. The first changes looks larger but is mostly moving existing code without changing it.

**Link to original  issue(s)**: https://github.com/dart-lang/dart_style/issues/1205

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon

**Comment by kevmoo** [comment]
LGTM!

**Comment by athomas** [comment]
LGTM

**Comment by athomas** [comment]
@munificent Would you mind creating the CP CL as described in https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel? I can do the review.

**Comment by munificent** [comment]
Sure thing, done: https://dart-review.googlesource.com/c/sdk/+/297240

Thanks!

**Comment by itsjustkevin** [comment]
@munificent friendly ping, still need this one merged to beta.

**Comment by athomas** [comment]
This one is landed on beta now.
