### ISSUE TITLE
LSP server doesn't provide diagnostics as-you-type for YAML files like fix_data.yaml or pubspec.yaml

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52126]
Split from #52108.

- [ ] In `lib/fix_data.yaml`, diagnostics are not updated as you type
- [ ] In `pubspec.yaml`, diagnostics are not updated as you type
- [x] In `lib/fix_data/foo.yaml` there are no diagnostics at all, even when saving
    https://dart-review.googlesource.com/c/sdk/+/296801

**Comment by DanTup** [comment]
Ah, good point. Shall we close this then now https://github.com/dart-lang/sdk/commit/bbacf39e9c1085650b5f2a180285792ad0dd76d9 has solved the other issue? Or keep it open as a future enhancement?

It's probably not a priority, but the current behaviour does feel a bit odd in VS Code (because it's not obvious this is what's happening).

**Comment by bwilkerson** [comment]
Unless we think that we're going to (a) verify whether the behavior is reasonable and/or (b) improve the behavior of the parser, I don't think we're going to implemented analysis-as-you-type for YAML files. While it would be nice to have, supporting YAML files is never going to be as high a priority as supporting Dart files. But we can leave it open for community contributions.
