### ISSUE TITLE
No completions for unresolved identifier in an object pattern's name

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52129]
Given the following dart 3.0 code:
```dart
class AClassWithAReallyLongName {}

f(Object o) {
  switch (o) {
    case AClass(): // (1)
  }
}
```
Place the cursor on the line marked (1), just before the `(`, and request completions.  No suggestions are given.

Expected behaviour: the completion `AClassWithAReallyLongName` should be offered.

Reproduced in 742612ddaca82b51387a129ed50738256ae2e243.

**Comment by scheglov** [comment]
Oh yes, I hit this more and more often.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/356641
