### ISSUE TITLE
`const UndefinedName()` should offer a quick fix to create a class with a const constructor

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52128]
E.g. with this code:
```dart
main() {
  var x = const Foo();
}
```
`Foo` has the compile-time error `creation_with_non_type`. Requesting quick fixes should bring up the fix `Create class 'Foo'`. Ideally the created class should contain a const constructor, e.g.:
```dart
class Foo {
  const Foo();
}
```
(note that at present, the fix `Create class 'Foo'` only seems to be available when `Foo` is used as a type annotation, e.g.:
```dart
Foo f() {}
```

Reproduced with 742612ddaca82b51387a129ed50738256ae2e243.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/305120
