### ISSUE TITLE
Find references for a constructor should find implicit super calls

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52131]
Given this code:
```dart
class Base {
  Base(); // (1)
}

class Derived extends Base {}
```
Clicking on `Base` on line (1) and requesting `Find all references` should find the class `Derived`, since the implicit default constructor for `Derived` calls `Base`.

Similarly, in this code:
```dart
class Base {
  Base(); // (1)
}

class Derived extends Base {
  Derived(); // (2)
}
```
Clicking on `Base` on line (1) and requesting `Find all references` should find the `Derived` constructor at (2), since this constructor implicitly calls `super`.

Reproduced in 742612ddaca82b51387a129ed50738256ae2e243.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/297080
