### ISSUE TITLE
Inline local variable doesn’t work inside a case block

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52130]
Given the code:
```dart
test(int i) {
  switch (i) {
    case 0:
      var x = i + 1;
      print(2 * x);
  }
}
```
Place the cursor on the declaration of `x` and request quick assists. The quick assist `Inline Local Variable` is offered, however if you select it, you get the error message "Local variable declaration or reference must be selected to activate this refactoring."

Although this is a longstanding issue that precedes Dart 3.0, I think it is more important now because switches are likely to be used more frequently now that the "patterns" feature is being released.

Reproduced in 742612ddaca82b51387a129ed50738256ae2e243.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/306125
