### ISSUE TITLE
Replace an unreferenced variable in a map or list pattern with a wildcard pattern

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#52137]
It would be nice, at some point, to add support for replacing an unreferenced variable in a map or list pattern with a wildcard pattern. For example, replacing `var b` in the following:
```
void f(Object o) {
  switch (o) {
    case {'a': var a, 'b': var b}:
      a;
  }
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/305160
