### ISSUE TITLE
[analyzer] Type's `allSupertypes` returned types are marked as nullable whereas `interfaces` are not 

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#52133]
If a type is marked as nullable, then `allSupertypes` getter returns all super types [also marked as nullable](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/dart/element/type.dart#L509).
But if we take a look at the interfaces getter, [the returned types are returned as is](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/dart/element/type.dart#L530). Same works for [mixins](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/dart/element/type.dart#L644), [superclass](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/dart/element/type.dart#L654) and so on.

Is there a reason why returned types differ? Also, what's the idea behind marking `allSupertypes` types nullable if the class actually implements non-nullable type?

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
We started applying nullability suffixes in https://dart-review.googlesource.com/c/sdk/+/261840

We probably should have updated `mixins`, `interfaces`, and `superclass` for consistency.

You are right that when we declare a _class_, its supertypes are never nullable. But when we instantiate a class into a _type_, we given it a nullability suffix, and asking `allSupertypes` is like asking "how else can I look at this type?". So, we can look at `List<int>` as `Iterable<int>`; but we cannot look at `List<int>?` as `Iterable<int>` - this would be a compile time error.

**Comment by incendial** [comment]
Thanks, totally makes sense!
Is there an option to get all supertypes (or superclasses?) that represent the chain of declared classes (without the nullability suffix)?

**Comment by scheglov** [comment]
I'm not sure what you want. We have `InterfaceElement.allSupertypes`, but these are without applying `InterfaceType.typeArguments`. It feels consistent to me, we either apply all that "configures" the `InterfaceElement` into `InterfaceType`, or nothing.

**Comment by incendial** [comment]
For example,
```
void main() {
  final regular = <Element>{};
  final generics = <AnotherElement?>[];

  final elements = generics.toSet();
  final unused = elements.difference(regular);
}

class Element {}

class AnotherElement implements Element {}
```

I need to check that `generics`'s type has `regular`s type in the type hierarchy, but ignore the nullability. Good question, how it should work with type arguments though...

**Comment by incendial** [comment]
How I do it like this:
```dart
bool _containsSupertype(DartType child, DartType parent) =>
      !child.isDartCoreObject &&
      parent is InterfaceType &&
      parent.allSupertypes
          .any((type) => type.element.name == child.element?.name);
```

**Comment by scheglov** [comment]
If you don't care about argument types, you could use
```dart
  bool _containsSupertype(DartType child, DartType parent) =>
      !child.isDartCoreObject &&
      parent is InterfaceType &&
      parent.element.allSupertypes
          .map((e) => e.element)
          .contains(child.element);
```

**Comment by incendial** [comment]
So no option to do it in one go? Looks like `map` + `contains` is slower than `any`.

**Comment by incendial** [comment]
Ah, I can actually use `any` with equality. But still an option to have just `contains` would be better.
Should I close this or you want to keep it open before fixing other places where a nullability suffix is missing?

**Comment by scheglov** [comment]
Well, if `map` + `contains` give the right semantics, we could rewrite it as a single loop, that does "map" into a local variable, and "contains" as a comparison, e.g.
```dart
for (final superType in allSupertypes) {
  if (superType.element == child.element) return true;
}
```

https://dart-review.googlesource.com/c/sdk/+/297400 should make other getters consistent.

**Comment by incendial** [comment]
Which is the same as `parent.element.allSupertypes.any((type) => type.element == child.element))` as I mentioned.
