### ISSUE TITLE
[CP] [vm/compiler] Support obfuscation of record field names

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#52134]
### Commit(s) to merge

d83caf1c0cc9cb94d6530ff2cae437a72cc0fd1f

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/296940

### Issue Description

Obfuscation of record field names was not properly supported in compiler, causing compiler crashes and runtime errors.

### What is the fix

Added obfuscation of field names when building flow graph for RecordFieldGet kernel node.
Prevented obfuscation of $n names of record positional fields in order to handle them during dynamic invocations.

### Why cherry-pick

Affects users which use records and obfuscation (e.g. https://github.com/flutter/flutter/issues/125289).

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/125289, https://github.com/dart-lang/sdk/issues/52124

**Comment by alexmarkov** [comment]
@mraleph @a-siva

**Comment by a-siva** [comment]
lgtm

**Comment by itsjustkevin** [comment]
@alexmarkov we can go ahead and merge this CL.

**Comment by mit-mit** [comment]
SGTM
