### ISSUE TITLE
[CP] Web compilers still support `List` constructor.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#52132]
### Target

beta

### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/297461

### Issue description

The `List([int n])` constructor was removed from the Dart 3.0 SDK. It was not callable from language version 2.12 or above code, and the 3.0 SDK no longer supports pre-2.12 language versions.

The `@patch` declarations for the external factory constructor in dart2js and dev-compiler `core_patch.dart` files were not removed, and their existence did not cause any error even if there was no `external factory List([int n]);` constructor declaration to patch.

Instead, the `@patch` declaration *added* the constructor to the class, and it's now possible to compile code which uses that constructor using dart2js, with a language version of 3.0.
```dart
//@dart=3.0
void main() {
  print(List().length);
}
```
compiled using the 3.0.0-417.2.beta SDK (current checked-in SDK in the Dart repo) gives:
```
$ ../tools/sdks/dart-sdk/bin/dart --version
Dart SDK version: 3.0.0-417.2.beta (beta) (Wed Apr 19 09:44:49 2023 +0000) on "linux_x64"

$ ../tools/sdks/dart-sdk/bin/dart compile js list.dart -o list.js
Info: Compiling with sound null safety.
Compiled 9,742,562 characters Dart to 98,239 characters JavaScript in 0.73 seconds using 184.828 MB of memory
Dart file list.dart compiled to JavaScript: list.js

$ ../third_party/d8/linux/d8 list.js
0
```

### What's the fix

We've removed the checks preventing code from using `List`, because they're no longer needed because it's no longer there. 
But it's actually still there and can be used.

### Risk

Low

**Comment by lrhn** [comment]
Working on a CL to remove those patches, and the existing code which uses it. We have such code in the SDK too, in web-compiler-only tests.

https://dart-review.googlesource.com/c/sdk/+/296900

**Comment by sigmundch** [comment]
Wow, good catch Lasse! This was really surprising, and worth following up on ways to reduce chances of something like this falling through the cracks in the future. Fix LGTM!

**Comment by itsjustkevin** [comment]
Thanks for the cherry-pick request @lrhn.  Almost didn't catch this one.  For future cherry-picks could you use the [issue template](https://github.com/dart-lang/sdk/issues/new?assignees=mit-mit%2Cathomas%2Cvsmenon%2Citsjustkevin&labels=cherry-pick-review&template=2_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E) in accordance with the [cherry-pick wiki](https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel)?  This way we can ensure this doesn't get lost in the stream of issues.

**Comment by vsmenon** [comment]
lgtm

**Comment by lrhn** [comment]
Haven't filed a real cherry-pick request, didn't dare until I know whether the CL can land. (Was still running test when I left for today.)

**Comment by itsjustkevin** [comment]
> Haven't filed a real cherry-pick request, didn't dare until I know whether the CL can land. (Was still running test when I left for today.)

I've updated this to take the place of an official cherry-pick request, no worries.

**Comment by lrhn** [comment]
Still need to make the CL actually work. There are some tests which now break (they're but should be marked as such, or just deleted, those who are marked `//@dart=2.9` or even `//@dart=2.7`) , and at least one test fails just because some code in the analyzer is now dead (https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8783197135886411921/+/u/test_results/new_test_failures__logs_).

So, more cleanup needed before CL can land.

**Comment by sigmundch** [comment]
FYI @rakudrama is making progress fixing failures in https://dart-review.googlesource.com/c/sdk/+/297100 (which takes over @lrhn's change)

**Comment by rakudrama** [comment]
I have landed https://dart-review.googlesource.com/c/sdk/+/297100

Please cherry-pick it.

**Comment by itsjustkevin** [comment]
@lrhn thanks for this, could you merge a cherry-pick of https://dart-review.googlesource.com/c/sdk/+/297100 to the beta channel?

**Comment by lrhn** [comment]
Thank Stephen!
I've made a aherry-pick CL of cl/297100 against origin/beta: 
  https://dart-review.googlesource.com/c/sdk/+/297461

**Comment by vsmenon** [comment]
Can we commit this today in time for the next cut?  ( @itsjustkevin )

**Comment by itsjustkevin** [comment]
@vsmenon  Trying to hold off cutting the beta until all of the in flight cherry-picks are merged.  The backlog is too large and seems risky to push to the next cycle.

**Comment by sigmundch** [comment]
I came to realize that our support to tag failures as accepted that we use in the `main` branch is not available on the `beta` branch, so the CL required a manual submit. I went ahead and did that, so the merge has now landed.
