### ISSUE TITLE
Variable in for-in loop can’t be renamed using rename refactor

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52149]
Given the following code:
```dart
f(List<int> ints) {
  for (var value in ints) { // (1)
    print(value);
  }
}
```
Place the cursor on the identifier `value` on the line marked (1), and request a rename refactor.

Expected result: it should be possible to rename this variable.

Observed result: the IDE shows the message "The element can't be renamed."

I see similar behaviour with for-in collection elements, e.g.:
```dart
f(List<int> ints) => [for (var value in ints) value * 2];
```

Reproduced in 60fec9c72046c7556a93736ed55388a676c4d890.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/297900

This looks to be an LSP specific issue.
IntelliJ does not call the server at all 😨
