### ISSUE TITLE
[CP] [io] Remove `abstract` modifier from the `Platform` class

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#52141]
### Commit(s) to merge

69f71e90ea9880d03eceec2578a404de63240b68

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/297200

### Issue Description

The `abstract` modifier was added to the [`Platform` class](https://api.dart.dev/stable/dart-io/Platform-class.html). This breaks `package:dcli_core`.

### What is the fix

Remove the `abstract` modifier from the [`Platform` class](https://api.dart.dev/stable/dart-io/Platform-class.html).

### Why cherry-pick

Affects users of `package:dcli_core`.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52138

**Comment by vsmenon** [comment]
lgtm

**Comment by itsjustkevin** [comment]
CC @devoncarew

**Comment by itsjustkevin** [comment]
@brianquinlan waiting on this one to be merged so that it may be added in the next release.

**Comment by mit-mit** [comment]
@itsjustkevin this was already merged in https://github.com/dart-lang/sdk/commit/69f71e90ea9880d03eceec2578a404de63240b68

**Comment by mit-mit** [comment]
SGTM

**Comment by itsjustkevin** [comment]
> @itsjustkevin this was already merged in [69f71e9](https://github.com/dart-lang/sdk/commit/69f71e90ea9880d03eceec2578a404de63240b68)

We still need https://dart-review.googlesource.com/c/sdk/+/297200 cherry-pick merged to the beta branch for the release.

**Comment by lrhn** [comment]
Consider also including https://dart-review.googlesource.com/c/sdk/+/297540, so it will be easier to reintroduce `abstract` in the future.

**Comment by brianquinlan** [comment]
I think that adding the deprecation to Dart 3.1 is fine. I'm hoping that, at the same time, we can remove the breaking use case.

So the releases work this way:
- Dart 3:0: `Platform` is non-`abstract` (as it was in Dart 2.x)
- Dart 3.1: `Platform` is non-`abstract`. Constructor is deprecated [297540](https://dart-review.googlesource.com/c/sdk/+/297540). Use case for constructing it is removed [297260](https://dart-review.googlesource.com/c/sdk/+/297260).
- Breaking change process
- Dart 3.2: `Platform` made `abstract`.

**Comment by vsmenon** [comment]
This on track to land today?

**Comment by brianquinlan** [comment]
I'll land it now. I was just waiting a bit to see if @lrhn and @itsjustkevin had further thoughts about the inclusion of https://dart-review.googlesource.com/c/sdk/+/297540. I'll land **without** that code.

**Comment by mit-mit** [comment]
Yeah, let's get this landed. We can then have a separate discussion about the `@deprecated` part afterwards. I think we can make that timeline work in several ways.

**Comment by itsjustkevin** [comment]
@lrhn and @brianquinlan looks like there is a build failure here, do you mind taking a look?

**Comment by brianquinlan** [comment]
@itsjustkevin Where are you seeing a build failure?

**Comment by itsjustkevin** [comment]
@brianquinlan in my imagination, as I realize I was looking at https://dart-review.googlesource.com/c/sdk/+/297540.
