### ISSUE TITLE
"Invert if" should not be offered for if-case

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52148]
With the following Dart 3.0 code:
```dart
f(num n) {
  if (n case int()) {
    print("it's an int");
  } else {
    print("it's not an int");
  }
}
```
Place the cursor on the `if` token and request quick assists.

Expected result: the quick assist "invert if" should not be offered.

Observed result: the quick assist "invert if" _is_ offered, and its behaviour doesn't preserve semantics.  (It exchanges the `if` and `else` blocks, but doesn't change the `if` statement in any other way.)

Reproduced in 60fec9c72046c7556a93736ed55388a676c4d890.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/297880
