### ISSUE TITLE
No quick fix for unused_local_variable when local variable defined in a pattern

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52150]
The following Dart 3.0 code has an `unused_local_variable` diagnostic for the unused variable `k`:
```dart
f(MapEntry e) {
  switch (e) {
    case MapEntry(key: [var a, var b] && var k, :var value):
      print('[$a, $b]: $value');
  }
}
```
It would be nice to have a quick fix that removes the redundant `&& var k`, leaving:
```dart
f(MapEntry e) {
  switch (e) {
    case MapEntry(key: [var a, var b], :var value):
      print('[$a, $b]: $value');
  }
}
```
Similarly, in this code:
```dart
f(MapEntry e) {
  var MapEntry(:key, :value) = e;
  print('Key is $key');
}
```
It would be nice to have a quick fix that removes the redundant `, :value`, leaving:
```dart
f(MapEntry e) {
  var MapEntry(:key) = e;
  print('Key is $key');
}
```
And in this code:
```dart
f((String, int) r) {
  var (s, i) = r;
  print('$i');
}
```
It would be nice to have a quick fix that replaces the unused local variable `s` with a wildcard pattern, leaving:
```dart
f((String, int) r) {
  var (_, i) = r;
  print('$i');
}
```

**Comment by scheglov** [comment]
Actually, with https://dart-review.googlesource.com/c/sdk/+/296761 we do support removing unused variable patterns from object and record patterns.
<img width="809" alt="image" src="https://user-images.githubusercontent.com/384794/234080905-23c7184a-b2b4-4d2b-9304-3acf1cabb92f.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/384794/234081032-1cd9cbab-375c-4336-86d9-711ac0042173.png">
Removing from the logical-and pattern is not implemented yet.
I did not think about it, but now I see when it might be useful.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/297841?forceReload=true
