### ISSUE TITLE
[CP] Improve pub message when pubspec is not null-sefety.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#52152]
### Commit(s) to merge

https://github.com/dart-lang/pub/commit/95044c22de35458a1e5bb3875f5cfaeb8c934c7a

### Target

Beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/297700

### Issue Description

The message was somewhat convoluted. Trying to make it simpler and more relevant.

### What is the fix

Simplify the message.

### Why cherry-pick

Polish on the upgrade experience to 3.0

### Risk

low

### Issue link(s)

Only a pull request: https://github.com/dart-lang/pub/pull/3875

**Comment by sigurdm** [comment]
Yes, that should be the only pub commit in the cherry-pick (unless I made a mistake).

See: https://dart.googlesource.com/pub.git/+/3e2c92a8bb74935302de52b80b870bf66963756d..762a16d4149b007de4c7cdd0f2798db1ead9eff0/ (linked from the roll CL).

**Comment by mit-mit** [comment]
In that case I think we should take this CP, as it's a big usability improvement that lots of folks will see (basically everyone with resolution issues).

**Comment by vsmenon** [comment]
lgtm

**Comment by vsmenon** [comment]
@sigurdm @itsjustkevin - do we see this landing on time for the next cut?

**Comment by vsmenon** [comment]
( @leafpetersen is re running the failures on the current cl right now )

**Comment by itsjustkevin** [comment]
@vsmenon and @leafpetersen the same build is failing on rerun.

**Comment by mit-mit** [comment]
I see nothing in the logs that look related to the change. @athomas seemed to think it might be flaky tests?
