### ISSUE TITLE
Analyzer does not warn of missing exhaustiveness when combining sealed classes and enums.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#52164]
The analyzer correctly warns if any of the cases are removed from these switches, and not if all the cases are present:
```dart
enum E {a, b;}
sealed class S {}
class C1 implements S {}
class C2 implements S {}

void main() {
  E e = E.a as dynamic;
  switch (e) {
     case E.a: 
     case E.b:
  }
  S s = C1() as dynamic;
  switch (s) {
    case C1 _:
    case C2 _:
  }
}
```

However, it does not recognize a missing enum entry if it's combined with another type:
```dart
sealed class SE {}
class C3 implements SE {}
enum EE implements SE {a, b;}

void main() {
  SE se = EE.a as dynamic;
  switch (se) {
    case C3 _:
    // case EE.a:
    case EE.b:
  }
}
```
Here commenting out the `EE.a` or `EE.b` case does not give any errors in the analyzer. The CFE does give the correct error of a missing `EE.a` case.

Even commenting out both `EE.?` cases doesn't give an error.

It looks like the analyzer simply misses that an `enum` declaration can also introduce a subtype of a sealed type which should be included in exhaustiveness.

Checking the code ... yes, [that is the problem](https://github.com/dart-lang/sdk/blob/3184f2224bb36f48804cce1f983f57b6e7b23a97/pkg/analyzer/lib/src/generated/exhaustiveness.dart#L149). And it also mixes mixins:
```dart
sealed class S {}

class C1 implements S {}
mixin M2 implements S {}
class C3 with M2 {}

void main() {
  S s = C1() as dynamic;
  switch (s) {
    case C1 _:
    // case M2 _:  // No error from analyzer.
  }
} 
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/298260
