### ISSUE TITLE
[CP] Front end: move anonymous mixin sealed/final inference to checkSupertypes phase.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52169]
### Commit(s) to merge

96a346fc5e7bf77203814a4801ff57985e66b69e

### Target

Beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/298200

### Issue Description

The front end's handling of sealed classes involving mixins is dependent upon declaration order in the file. If a concrete class extends a sealed class with a mixin, and the concrete class appears before the sealed class in the library, then the front end's internal anonymous mixin application class will not be properly marked as sealed. Consequently, any switches involving the sealed class will be flagged as non-exhaustive, and the error message will claim that the switch must handle the anonymous mixin class. Although the error can in theory be worked around by including a default/wildcard case, the workaround is not obvious, since the error message specifically encourages the user to handle the anonymous mixin class directly (which is impossible because anonymous mixins can't be directly referenced).

See https://github.com/dart-lang/sdk/issues/52048 for a concrete example.

### What is the fix

The logic for inferring sealedness and finality of anonymous mixin application classes was moved from the `buildOutlineNodes` phase of the front end (which processes classes in source order) to the `checkSupertypes` phase (which processes classes in class hierarchy order, visiting superclasses before subclasses). This ensures that the sealedness and finality of anonymous mixin application classes will be set correctly regardless of source order.

### Why cherry-pick

Since the code change only affects the sealed-ness and finality of anonymous mixin applications, it is low risk. (It will only have an effect on code that uses both mixins and the "sealed class" feature). Without this fix, there is a danger of user confusion, since reordering classes within a file is not expected to have any effect. For example, a user might find that the code runs fine until they are ready to send it for code review, whereupon they invoke their IDE's "sort members in file" functionality, triggering the bug.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52048

**Comment by itsjustkevin** [comment]
cc: @johnniwinther

**Comment by johnniwinther** [comment]
LGTM

**Comment by mit-mit** [comment]
LGTM

**Comment by stereotype441** [comment]
Closing since the cherry-pick landed

**Comment by itsjustkevin** [comment]
@stereotype441 I am going to keep this cherry-pick request open to ensure it is tracked all the way to landing in the release.  Once it is added to a release, I will close it.

**Comment by itsjustkevin** [comment]
> @stereotype441 I am going to keep this cherry-pick request open to ensure it is tracked all the way to landing in the release. Once it is added to a release, I will close it.

@stereotype441 called out that the instructions in https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel were misleading.  Edited with the help of @stereotype441.
