### ISSUE TITLE
[CFE]  Missing static error on an indirect implementation of a base class.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#52161]
The static analysis section of the [class modifiers spec](https://github.com/dart-lang/language/blob/main/accepted/future-releases/class-modifiers/feature-specification.md#basic-restrictions) specifies that the error around implementing a base class from another library extends through the transitive closure of the super-declarations:

```
    A declaration implements another declaration, and the other
    declaration itself, or any of its super-declarations,
    are marked `base` or `final` and are not from the first declaration's
    library _(with some exceptions for platform libraries)_.

    _(You can only implement an interface if *all* `base` or `final`
    superdeclarations are inside your own library. Or if you're in
    a pre-feature library and all `base` or `final` superdeclarations
    are in platform libraries.)_

    More formally:
    A declaration *C* in library *L* has a declared interface *P*,
    and *P* has any superdeclaration *S*, from a library *K*,
    which is marked `base` or `final` _(including *S* being *P* itself)_,
    and neither:
    * *K* and *L* is the same library, mor
    * *K* is a platform library and *L* is a pre-feature library.
 ```

The CFE does not seem to report this error, the following code produces no error when tested at current HEAD:

```
// lib.dart
base class C {}

// test.dart
import "lib.dart";
base class Base extends C {}
base class Nefarious implements Base  {}
```

We seem to currently have no test coverage for this error (and the related errors for final, and for the mixin and mixin class cases).

@munificent is working on adding tests, @dart-lang/language-team please help expedite reviews and landing here.

cc @kallentu @johnniwinther @itsjustkevin 

Tentatively marking this as a blocker for stable, let's plan on a cherry pick if at all possible.  If the fix looks like it will be hard to land in that time frame, we can discuss alternatives and possibly aim for the first patch release.

**Comment by eernstg** [comment]
It would indeed be great to have this cherry picked.

**Comment by leafpetersen** [comment]
@johnniwinther do you want me to put together a cherry pick request for this?

**Comment by johnniwinther** [comment]
Yes

**Comment by leafpetersen** [comment]
https://github.com/dart-lang/sdk/issues/52209
