### ISSUE TITLE
[CP] [beta] Report BASE_CLASS_IMPLEMENTED_OUTSIDE_OF_LIBRARY for implementing 'base' via 'extends'.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52173]
### Commit(s) to merge

80d26df2fdb32db2a22a026155e811e4379e06be

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/298201

### Issue Description

The implementation was checking only the elements specified in the `implements` clause, but not its superinterfaces.

### What is the fix

The implementation was changes to check also all superinterfaces of the implemented element.

### Why cherry-pick

This makes the analyzer correct with respect to the implementation.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52160

**Comment by leafpetersen** [comment]
This is fairly high priority to get into the stable release.

**Comment by vsmenon** [comment]
lgtm

**Comment by srawlins** [comment]
LGTM; cherry pick looks tidy enough, low risk.

**Comment by mit-mit** [comment]
LGTM
