### ISSUE TITLE
If an object pattern refers to an unresolved getter, there should be a quick fix to create the getter (or field)

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52176]
The following code has two `undefined_getter` errors: one for the identifier `bar` and one for the identifier `baz`:
```dart
class Foo {}

f(Object o) {
  switch (o) {
    case Foo(:var bar, baz: _):
  }
}
```
Clicking on either of these two identifiers and requesting fixes should activate the fixes "create getter" and "create field", just as it would if these were ordinary imperative getter accesses.

Reproduced in cc3bf609f26bb33d1ecbd8c86b4c6932734ece73.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/298920
