### ISSUE TITLE
vm/dart/isolates/concurrency_stress_sanity_test failing on multiple configurations

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#52178]
There are new test failures on [Fix web_int_literals_test.dart....Resolve the whole unit in resolveForCompletion() when the node is a directive.](https://github.com/dart-lang/sdk/compare/018dadcf5b7d037517c0a8a35df306c120dfabb0~...4bfb196287ed2c746382c87dee38c3f17b02ef41).

The test
```
vm/dart/isolates/concurrency_stress_sanity_test RuntimeError (expected Pass)
```
is failing on configurations
```
dartk-weak-asserts-linux-release-x64
vm-appjit-linux-release-x64
vm-eager-optimization-linux-release-x64
vm-linux-release-x64
vm-reload-linux-release-x64
vm-reload-rollback-linux-release-x64
```

/cc @mkustermann

**Comment by mkustermann** [comment]
> vm/dart/isolates/concurrency_stress_sanity_test RuntimeError (expected Pass)

This test seems to be passing on all configurations atm. Without a failure log it's hard to see what was the issue here.
