### ISSUE TITLE
Rename refactor should be usable on generic type parameter at declaration site

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52177]
Given code like this:
```dart
class Foo<T> { // (1)
  T? x; // (2)
}
```
It is possible to rename the generic type parameter `T` at the site of its usage on line (2), but not at the site of its declaration on line (1). (VSCode complains "The element can't be renamed.")

It should be possible to rename the type parameter at the site of its declaration too.

Reproduced in cc3bf609f26bb33d1ecbd8c86b4c6932734ece73.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/298960

It still does not work for function / method type parameters though.
But supporting these might take longer, and I want to improve probably more often case first.

**Comment by scheglov** [comment]
Implementation for all other locations, unit tests.
https://dart-review.googlesource.com/c/sdk/+/299280
