### ISSUE TITLE
Possible "dart compile" bug

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#52170]
Related to https://github.com/google/file.dart/issues/216

I unfortunately wasn't able to reproduce the issue without a dependency on `package:file`. But considering the surprising behavior, I doubt that the package is the problem.

Long story short, it appears that in some cases, getters are unable to read certain properties of an object.
A property which correctly exists and is non-nullable comes up as non-nullable, and causes the following crash:

```
node.dart:224 Uncaught TypeError: Cannot read properties of undefined (reading 'clock')
    at DirectoryNode.get$clock (node.dart:224:25)
    at DirectoryNode.RealNode$1 (node.dart:153:15)
    at Object.DirectoryNode$ (node.dart:198:3)
    at MemoryFile__doCreate_closure.call$2 (memory_file.dart:70:11)
    at MemoryFileSystemEntity_internalCreateSync_closure.call$5 (memory_file_system_entity.dart:202:19)
    at _MemoryFileSystem.findNode$4$followTailLink$segmentVisitor$visitLinks (memory_file_system.dart:269:17)
    at MemoryFile.internalCreateSync$2$createChild$followTailLink (memory_file_system_entity.dart:189:12)
    at MemoryFile._doCreate$1$recursive (memory_file.dart:64:18)
    at main (memory_file.dart:60:5)
    at js_helper.dart:2744:31
```

triggered with the following code:

```dart
// lib/main.dart
import 'package:file/memory.dart' as f;

void main() {
  final fs = f.MemoryFileSystem();
  final dir = fs.directory('/path');
  final dir2 = dir.childDirectory('another');
  final dir3 = dir2.childDirectory('path');
  final file = dir3.childFile('file.dart');

  file.createSync(recursive: true);
  file.writeAsStringSync('Hello, World!');

  print(file.path);
  print(file.readAsStringSync());
}
```

See https://github.com/google/file.dart/issues/216 for full reproduction steps.

____

What caused me to open this issue is that for no apparent reason, adding `prints` inside the problematic getter fixes the issue:

```diff
class RootNode extends DirectoryNode {
  ...
  @override
  Clock get clock {
+    print(fs);
+    print(fs.clock);
    return fs.clock;
  }
```

When adding those prints, the exception correctly stops occurring.
Removing either of the two prints, and the exception will keep happening.

The thing is, `fs.clock` respectively points to `RootNode.fs` and `_MemoryFileSystem.clock`, both of which are non-nullable object properties (so no getter in the loop).

So it makes no sense for any of those properties to come up as "undefined".

____

By spending a bit of time looking at the generated JS file, the gist of the issue appears to be in the `RealNode.get$clock`'s definition

By default, it is:

```dart
  A.RealNode.prototype = {
    ...
    get$clock() {
      return this.get$parent().fs.clock;
    }
  };
```

But changing `.fs.clock` to `.get$clock()` fixes the issue (which is what adding those prints seems to do).

____

The issue happened on Chrome.

Dart SDK version: 3.1.0-39.0.dev (dev) (Mon Apr 24 18:53:55 2023 -0700) on "macos_arm64"

**Comment by biggs0125** [comment]
I've tracked down the issue to a problem in Dart2JS type inference. Specifically around the way we're handling variables captured by loop scopes and then used within switch statements inside the loop. I'm digging into this more and have a smaller repro that I'll check in as a test.

**Comment by biggs0125** [comment]
Marked as P1 since the code that exercises this bad logic is in `package:file`.
