### ISSUE TITLE
[CP] [beta] Include enums and mixins into types of a sealed class.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52171]
### Commit(s) to merge

b81fd66ed52cdc6b6d17e951f65e7573bc538041

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/298340

### Issue Description

The implementation on exhaustiveness was skipping non-class elements that might be subtypes of sealed declarations.

### What is the fix

Add enums and mixins to the list.

### Why cherry-pick

Without the fix the analyzer will not report the required error, and the users will know that it does not work only when run.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52164

**Comment by srawlins** [comment]
LGTM; cherry pick looks very low risk.
