### ISSUE TITLE
No quick fix for unused_element when the element is a constructor

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52175]
The following code has an `unused_element` diagnostic on the constructor `C._named`:
```dart
class C {
  C();

  C._named();
}
```

Requesting quick fixes should offer the fix "remove unused element".

Reproduced in cc3bf609f26bb33d1ecbd8c86b4c6932734ece73.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/298800
