### ISSUE TITLE
[CP] [beta] Fix reporting CONSTANT_PATTERN_NEVER_MATCHES_VALUE_TYPE for Null vs. nullable FunctionType.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52172]
### Commit(s) to merge

00d841ee99984b83a5f5aa3956bdaf6e8baa3db7

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/298380

### Issue Description

The analyzer reports a warning when a constant pattern will never match the value. The implementation was quite conservative, but still missed one case when `Null` is matched against nullable function type.

### What is the fix

The fix is to allow `Null` and nullable function type, so this is not a warning:
```dart
void f(void Function()? x) {
  if (x case (null)) {}
}
```

### Why cherry-pick

This improves UX with some patterns.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52060

**Comment by srawlins** [comment]
LGTM
