### ISSUE TITLE
Remove Gitter.im from Issue Template

### ISSUE THREAD

**Issue by julemand101** [dart-lang/sdk#52188]
The current template ends with the following:

```
....
Thank you for taking the time to file an issue!

For a real-time response, consider our Gitter channel:

https://gitter.im/dart-lang/sdk
```

The Gitter.im links got recently removed with this issue: https://github.com/dart-lang/site-www/issues/4681

I am not sure if there are any channel where people can be sure to reach out to the Dart team for real-time response, so maybe delete this part completely from the issue template.

Alternative, link to the Community page which contains link to some communities where I have seen Dart team members being part of sometimes: https://dart.dev/community#join-the-conversation

**Comment by devoncarew** [comment]
Thanks for the report! We'd definitely take a PR which removed this reference.

Mentioning other ways to contact the Dart team - via the dart.dev community link - would also be reasonable.

**Comment by julemand101** [comment]
Pull request with suggested change: https://github.com/dart-lang/sdk/pull/52196

**Comment by julemand101** [comment]
Closed with: https://github.com/dart-lang/sdk/commit/2140dac6cbc3afcd18a70676acdab5b8d671190f
