### ISSUE TITLE
[dart2js] Calling compiled JS version of `jsify()` on object with nested list throws TypeError.

### ISSUE THREAD

**Issue by jgerigmeyer** [dart-lang/sdk#52200]
`jsify` calls `_convertDataTree` to convert objects. The Dart version works fine, but calling the compiled JS version of `jsify()` on an object with a nested list throws a TypeError:

```dart
var myObj = { 'foo': ['bar'] };
var converted = jsify(myObj);
```

Which compiles to:

```js
A.jsify(A.LinkedHashMap_LinkedHashMap$_literal(["foo", A._setArrayType(["bar"], type$.JSArray_String)], type$.String, type$.List_String));
```

And throws:

```
error properties: Object({ dartException: TypeError: Instance of 'MappedListIterable<String, dynamic>': type 'MappedListIterable<String, dynamic>' is not a subtype of type 'Iterable<dynamic>' })
    at Object.wrapException [...]
    at Object._failedAsCheck [...]
    at Rti._generalAsCheckImplementation [as _as] [...]
    at Interceptor.addAll$1 [...]
    at _convertDataTree__convert.call$1 [...]
    at _convertDataTree__convert.call$1 [...]
    at Object._convertDataTree [...]
    at Object.jsify [...]
```

It seems to be fixed by adding `toList()` to this line:

https://github.com/dart-lang/sdk/blob/a7854364a628403cd413a77a50003dbc24a99de6/sdk/lib/_internal/js_runtime/lib/js_patch.dart#L157

```js
convertedList.addAll(o.map(_convert).toList());
```

Which compiles to:

```diff
  A._convertDataTree__convert.prototype = {
    call$1(o) {
      var convertedMap, key, convertedList,
        t1 = this._convertedObjects;
      if (t1.containsKey$1(o))
        return t1.$index(0, o);
      if (type$.Map_dynamic_dynamic._is(o)) {
        convertedMap = {};
        t1.$indexSet(0, o, convertedMap);
        for (t1 = J.get$iterator$ax(o.get$keys(o)); t1.moveNext$0();) {
          key = t1.get$current(t1);
          convertedMap[key] = this.call$1(o.$index(0, key));
        }
        return convertedMap;
      } else if (type$.Iterable_dynamic._is(o)) {
        convertedList = [];
        t1.$indexSet(0, o, convertedList);
-       B.JSArray_methods.addAll$1(convertedList, J.map$1$1$ax(o, this, type$.dynamic));
+       B.JSArray_methods.addAll$1(convertedList, J.toList$0$ax(J.map$1$1$ax(o, this, type$.dynamic)));
        return convertedList;
      } else
        return o;
    },
    $signature: 352
  };
```

* Dart SDK Version `2.19.6`
* MacOSX
* Chrome Headless

**Comment by sigmundch** [comment]
Thanks for filing the issue @jgerigmeyer!

I think we need to investigate a bit more to better understand what's happening here. The 2-line snippet you shared above does work for us locally, so there may be some additional elements at play.

One theory I'm wondering about is whether these tests have 2 Dart programs in the mix, and the types from one and the other are not well distinguished. I recall we hit similar issues years ago on sass, but it's been a long time since I've seen anything like it.

The reason I believe something like this could be at play is that the error you ran into is pretty surprising: `MappedListIterable<String, dynamic>` in the Dart class hierarchy is a subtype of `Iterable<dynamic>`. If, however, one of these types came from program (A), and the other from program (B), then dart2js may get confused. Usually dart2js wouldn't be able to see the type from a different program (e.g. we use JS symbols to store type information to get isolation), but maybe something related to this is not working as intended?

Another theory is a bug in the compiler, where some relationships between types are dropped by accident?

If by chance you have a small isolated example for us to look at, or can help us reproduce this locally, that would be super helpful!

Thanks again!

**Comment by nex3** [comment]
We no longer run JS API tests through Dart's test runner, so there's only one Dart program at play here.

**Comment by jgerigmeyer** [comment]
@sigmundch Thanks for looking into it!

> I think we need to investigate a bit more to better understand what's happening here. The 2-line snippet you shared above does work for us locally, so there may be some additional elements at play.
> ...
> If by chance you have a small isolated example for us to look at, or can help us reproduce this locally, that would be super helpful!

You're absolutely correct. When I try to create an isolated case, I can't reproduce this. My latest theory is that it has to do with how I'm bundling the compiled JS file using esbuild -- when I remove bundling or switch to rollup, the error goes away. I'll dig into it more tomorrow and let you know what I find...

**Comment by nex3** [comment]
It's also potentially a problem if dart2js is incompatible with esbuild, although it's not necessarily clear _which one_ it's a problem with.

**Comment by sigmundch** [comment]
I'm not as familiar with esbuild - is it possible that it has optimizations that may involve renaming properties or other things like that? What are the current flags you are using with it?

One of the reasons dart2js's output cannot be passed through the JSCompiler with some of it's common options, is that dart2js generates some property accesses dynamically, specifically to improve performance of type checks. For example, if you have a class like `Iterable` above, which is minified to `XZ`, we may inject `isXZ` into classes that are subtypes of Iterable (like MappedListIterable above). At runtime, when a subtype check is requested, the runtime-type implementation may create a property access dynamically, like `"is" + "XZ"`. This kind of trick would clearly fail if renames are happening that we are not aware of.

I wonder if something like this could be at play with esbuild.

**Comment by jgerigmeyer** [comment]
> I wonder if something like this could be at play with esbuild.

@sigmundch Seems to be it! When I [disable](https://github.com/oddbird/sass-spec/commit/9cca6820c579d66cbfa60788ce951c9fce89f574) esbuild's default [renaming optimization](https://esbuild.github.io/api/#keep-names), the error disappears. (I've hit this issue before, not sure why I didn't think of it sooner.) Thanks for the help!

**Comment by jgerigmeyer** [comment]
> My instinct is "esbuild" since it shouldn't be changing runtime behavior.

@nex3 Yeah, I kinda agree with this, having had this issue with esbuild in the past. It seems like the renaming optimization should be off by default.

**Comment by nex3** [comment]
It could be valuable to have a way to make dart2js output rename-resilient, even if it's a bit slower as a result. It's fairly likely users will try to run Sass through esbuild with default settings at some point, especially once we land browser support, and even if we document this issue plenty of users will run into it the hard way.

**Comment by sigmundch** [comment]
agree - filed #52279 to track
