### ISSUE TITLE
[CP] Dart 3.0 CHANGELOG entry

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#52205]
### Commit(s) to merge

0eee9f1392b6a4a8550077fb766762b9c7601b7e

### Target

stable (or both? not sure)

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/299420

### Issue Description

The CHANGELOG doesn't describe the 3.0 changes.

### What is the fix

This adds all of the language changes and other stuff in 3.0 to the CHANGELOG.

### Why cherry-pick

It's good for a stable release's CHANGELOG to describe that stable release. :)

### Risk

low

### Issue link(s)

None

**Comment by vsmenon** [comment]
lgtm

**Comment by itsjustkevin** [comment]
@athomas could you verify that this needs to be pushed to beta?

**Comment by athomas** [comment]
We don't need this at all, the release tooling takes care of this :)
