### ISSUE TITLE
[CP][cfe] Report error on indirect implementation of base class

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#52209]
### Commit(s) to merge

2a82ba0

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/299462

### Issue Description

Fixes significant missing static error in the CFE with the new class modifiers feature.  See #52161 for details.

### What is the fix

Fixes the issue in the CFE, adds tests.

### Why cherry-pick

This is a very substantial hole in the `base` modifier feature, and once released to stable, fixing it in the future would likely be a very significant breaking change.  

### Risk

medium

### Issue link(s)

#52161

**Comment by vsmenon** [comment]
lgtm given severity.

**Comment by mit-mit** [comment]
LGTM, especially given this would be a breaking change
