### ISSUE TITLE
[CP] Update dartdoc to provide chips for class modifiers on class or mixin pages.

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#52208]
### Commit(s) to merge

f193d91ba50fbb4972bfe68d57e6db8ea9e6c466

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/302841

### Issue Description

The motivating issue is that it is hard to see class modifiers on dartdoc generated pages, here: https://github.com/dart-lang/dartdoc/issues/3392. 

### What is the fix

https://github.com/dart-lang/dartdoc/pulls/3401 is the fix, to add chips to the top of class and mixin pages to indicate class modifiers, show a small tooltip, and link to descriptive documentation.   

### Why cherry-pick

Users may miss that class modifiers apply to a part of a Dart API without this change, as the old way of displaying them in the breadcrumb is easy to miss.  As class modifiers are a core feature of Dart 3.0 it makes sense to have them show up prominently in documentation.  @mit-mit requested that we make an effort to get this in for the initial release.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/dartdoc/issues/3392

### Extra Info

This cherry pick pulls in all deltas for dartdoc, including one other bugfix and some housekeeping.

Release notes:  https://github.com/dart-lang/dartdoc/releases/tag/v6.2.2
Github diff between dartdoc revisions:  https://github.com/dart-lang/dartdoc/compare/1a7952b..d01ddc5

**Comment by itsjustkevin** [comment]
Requesting another look from @mit-mit as this is a usability issue.

Requesting a look from @vsmenon and @leafpetersen to verify if this meets the bar for a cherry-pick late into the cycle.

**Comment by jcollins-g** [comment]
@mit-mit @itsjustkevin Ping to elevate this cherry pick.   The equivalent for Flutter (https://github.com/flutter/flutter/pull/125661)  has already merged; it would be unfortunate if this one didn't make it.

**Comment by itsjustkevin** [comment]
This hasn't been lost in the ocean @jcollins-g, we will be reviewing the cherry-picks today, will report back the status on the issue later in the day 🙂

**Comment by itsjustkevin** [comment]
Hold for next stable hotfix.

**Comment by itsjustkevin** [comment]
@mit-mit do we have the stamp of approval on this cherry-pick now that Dart 3 is released?

**Comment by itsjustkevin** [comment]
@jcollins-g could you rebase this against the stable branch?  Seeing the results would make it easier to verify the safety of this cherry-pick.

**Comment by jcollins-g** [comment]
@itsjustkevin https://dart-review.googlesource.com/c/sdk/+/302841 is the rebased change.  The delta is exactly the same, though of course the context of other DEPS changes may be different.

**Comment by itsjustkevin** [comment]
@jcollins-g I've edited the issue to point to the new cherry-pick, however there are merge conflicts.

**Comment by jcollins-g** [comment]
@itsjustkevin I apologize, my git-fu is not very strong apparently.   I have attempted once again to rebase and have restarted the bots.  Will keep an eye on it.
