### ISSUE TITLE
[CP] fix dart2js crash for rare combination of local functions + generics + records

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#52216]
### Commit(s) to merge

8ee2b8b36b2dc872bb64abbd7887b9cbcaf3cb6f

### Target

stable

### Prepared changelist for stable

https://dart-review.googlesource.com/c/sdk/+/302801

### Issue Description

dart2js crashes in a rare combination of local functions + generics + records. This was caused by a bug: dart2js processed some data out of order.

### What is the fix

The fix was to restore the correct processing order in the compiler.

### Why cherry-pick

Impact is fairly low, and would be a reason to skip this cherry-pick (it is also why we decided not to cherry-pick in beta before the stable release, but are considering this for a patch release after 3.0 goes out)

That said, the way it is exposed is a crash, which we generally want to avoid in our stable releases. 

The fix is really small and considered low risk.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/51899

### Extra Info

This is a cherry-pick for 3.0.1 stable (not the 2.19 stable). We haven't created the gerrit CL yet because the stable branch doesn't have 3.0 changes yet.

**Comment by sigmundch** [comment]
FYI @rakudrama

**Comment by itsjustkevin** [comment]
@sigmundch do we still desire this cherry-pick?  Based on the low risk and impact on users, this seems to meet the criteria for cherry-pick approval.

**Comment by sigmundch** [comment]
Yes, I'm inclined to cherry-pick. I just created the CL for it and linked it above.
