### ISSUE TITLE
[CP] It is not an error to use a void typed expression in SwitchExpressionCase.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52218]
### Commit(s) to merge

d838d1a08aa0ee1b2c5154c188d3662dfd2a6bc1

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/302880

### Issue Description

The language team clarified that it is not an error to use a `void` typed expression in a switch expression case expression.

### What is the fix

The change removes the reporting it for `case`, but keeps from the scrutinee.

### Why cherry-pick

It is probably easier to fix it before `3.0` release than to change rules later.
It is one line change.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52191

**Comment by leafpetersen** [comment]
This should be non-breaking to fix, so to reduce risk we will push this to the first hotfix release.

**Comment by itsjustkevin** [comment]
@scheglov could you rebase this to stable?  @leafpetersen do you still feel strongly that this cherry-pick should be accepted?

**Comment by scheglov** [comment]
I was not able to find any other way to change `beta` branch to `stable` branch than to do cherry-pick in Gerrit UI.
But this changes the CL to cherry pick.
I will update my original request.

**Comment by leafpetersen** [comment]
Yes, let's get this one out the door.
