### ISSUE TITLE
`dart fix` applies the wrong fix for `always-specify-types` in const collection literals.

### ISSUE THREAD

**Issue by water-mizuu** [dart-lang/sdk#52219]
* Dart SDK Version:  `Dart SDK version: 3.1.0-46.0.dev (dev) (Tue Apr 25 23:35:50 2023 -0700) on "windows_x64"`
* Windows 11

So the issue is, when applying fixes for the rule `always-specify-types` as stated above, the result can be seen in this snippet of code:
```dart
/// Before applying the fix
Matrix<E> removed({Set<int> x = const {}, Set<int> y = const {}}) { ... }
/// After applying the fix
Matrix<E> removed({Set<int> x = <int>const {}, Set<int> y = <int>const {}}) { ... }
/// Expected behavior
Matrix<E> removed({Set<int> x = const <int>{}, Set<int> y = const <int>{}}) { ... }
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/300162
