### ISSUE TITLE
[CP] Fix of pub global run for activated packages with earlier sdks.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#52227]
### Commit(s) to merge

https://github.com/dart-lang/pub/commit/3a7dc04eda4e7c359aed35176658bb2acc264f2e

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/300240

### Issue Description

`pub global run` does not understand that a package that is activated with a pre-3 sdk can be compatible with a 3 sdk.

https://github.com/dart-lang/pub/issues/3892

### What is the fix

We teach lockfile parsing to use the dart 3 constraint rewrite (`>=2.12.0 <3.0.0` => `>=2.12.0 <4.0.0`).

https://github.com/dart-lang/pub/pull/3897

### Why cherry-pick

This will affect users who has a globally activated package from a pre-3.0 sdk that they want to continue using after upgrading to Dart 3.0.

Worse is that re-`pub global activate`-ing will not be enough, because `dart pub global activate` will recognize that the same resolution happened, and not update the lockfile. So the workaround is to `dart pub global deactivate` followed by `dart pub global activate`.

### Risk

medium

### Issue link(s)

https://github.com/dart-lang/pub/issues/3892

**Comment by mit-mit** [comment]
I think we should to take this; while there is a workaround (`deactivate` + `activate`), it's very un-self-explanatory, and the issue should hit anyone using `pub global`.
