### ISSUE TITLE
dart fix doesn't work on pub dev package

### ISSUE THREAD

**Issue by chunhtai** [dart-lang/sdk#52233]
Step to reproduce:

1. do a Flutter create
2. in main.dart, use the following code

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(
    MaterialApp.router(
      routerConfig: GoRouter(
        routes: [GoRoute(
          name: 'home',
          path: '/',
          redirect: (context, state) {
            print('named lcation ${state.queryParams['abc']}');
            return null;
          },
          builder: (_, state) {
            return Text('${state.fullPath}');
          }
        )]
      ),
    ),
  );
}
```
3. in pubspec.yaml, adds the following dependecies
```yaml
go_router: ^7.0.0
```
4. run dart fix --apply

expected result:

The `state.queryParams['abc']` should be replaced with `state.queryParameters['abc']`

actual result:

nothing happens

The fix_data for this entry is in https://github.com/flutter/packages/blob/c3f4c46bbbf1d5d8ad980850aacc82955d187b64/packages/go_router/lib/fix_data.yaml#L109

Note: if in step 3 you replace go_router with path dependency and do a flutter pub get again, dart fix work as expected
```
 go_router:
   path: /Users/chtai/git/packages/packages/go_router/
```

**Comment by ahmednfwela** [comment]
I think the feature isn't even supported for non-flutter packages yet
src: https://github.com/flutter/flutter/wiki/Data-driven-Fixes
![image](https://user-images.githubusercontent.com/63286031/235544532-d0eeeb5a-13ad-4ed7-bc37-e3e640bee4cd.png)

**Comment by ahmednfwela** [comment]
@chunhtai here is an easier workaround:
copy `fix_data.yaml` from [here](https://github.com/flutter/packages/blob/c3f4c46bbbf1d5d8ad980850aacc82955d187b64/packages/go_router/lib/fix_data.yaml#L109) to the `lib` folder of the project

**Comment by chunhtai** [comment]
@ahmednfwela  thanks for looking into this.

I knew this is not officially supported, but I still decide to give a try so that go_router customers can still benefit from this.

Hi @lrhn , it would be good to know if dart plan to support this use case or not.

**Comment by ahmednfwela** [comment]
after some trial and error, I finally found a way to fix this in this PR https://github.com/flutter/packages/pull/3877

**Comment by bwilkerson** [comment]
@keertip
