### ISSUE TITLE
[CP] [cfe] Allow void typed switch expression

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#52234]
### Commit(s) to merge

88721ba

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/303020

### Issue Description

CFE companion to https://github.com/dart-lang/sdk/issues/52218.  Fixes the CFE to not reject switch expressions with void arms in void contexts.

### What is the fix

Allows void.

### Why cherry-pick

Deviation from the specified behavior, user reported issue in beta testing.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52191

### Extra Info

This and the accompanying analyzer cherry pick are planned for the first hotfix release.

**Comment by leafpetersen** [comment]
As with the analyzer [side](https://github.com/dart-lang/sdk/issues/52218) of this, we will hold this for the first patch release.

**Comment by itsjustkevin** [comment]
@leafpetersen could you rebase this against the stable branch?  Once the tests come back clean, we can approve this along with the analyzer cherry-pick.

**Comment by leafpetersen** [comment]
This CL is ready to go, let me know when I can submit.
