### ISSUE TITLE
Dart mistakes stand-alone binary for aot snapshot

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#52238]
The file-type detection seems to be inconsistent here:
```
$ dart compile exe bin/hello_world.dart 
Info: Compiling with sound null safety.
Generated: bin/hello_world.exe
$ dart bin/hello_world.exe # Thinks this is an aot snapshot
bin/hello_world.exe is an AOT snapshot and should be run with 'dartaotruntime'
$ dartaotruntime bin/hello_world.exe # does not agree this is an aot snapshot
Loading failed: Could not find isolate snapshot data.
VM initialization failed: Invalid vm isolate snapshot seen
$ bin/hello_world.exe  # Can invoke it directly
hello world
```

**Comment by bkonyi** [comment]
We're currently only checking for the ELF header bytes at the beginning of the file to try and determine if the target is an AOT snapshot. This obviously causes false positives when we try and pass an executable as the target for the VM, but I'm not sure if there's anything else we can easily check to differentiate between an AOT snapshot and an executable binary. @rmacnak-google, can you take a look?
