### ISSUE TITLE
[cli] consider dropping info message about sound null safety

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#52242]
@kevmoo noticed that today `dart compile js` and `dart compile exe` produce an info message saying that the code is compiled with sound null safety:

```
Info: Compiling with sound null safety.
```

Now that Dart 3 only supports sound null safety, we should consider dropping this.

This message has been reported since cad04f86049dc09e800f4dbee1a721726e533ba8, reverting the changes to pkg/dart2native/lib/generate.dart and pkg/dartdev/lib/src/commands/compile.dart would probably be enough to remove this info message.

cc @johnniwinther 
cc @mit-mit - this seems pretty minor to me, but bringing to your attention in case you think it's worth a cherry-pick later in our future patch release of Dart 3.0.1 or later.

Edit: updated commit hash, accidentally dropped a char

**Comment by sigmundch** [comment]
sorry, I had a typo in the commit hash, I edited the comment above with the right hash now.

**Comment by natebosch** [comment]
We should keep an output when compiling in any other mode (only will ever apply internally), and drop the output for sound null safety.

**Comment by mit-mit** [comment]
Agreed. Here's the corresponding change in the Flutter tool:
https://github.com/flutter/flutter/commit/242bb67d199bf8f4cbe89dcb71a35850505a43e9

**Comment by johnniwinther** [comment]
Landed in https://dart-review.googlesource.com/c/sdk/+/301385
