### ISSUE TITLE
[CFE] Inline class constructors' tear-offs are not found

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#52240]
Dart version: Dart SDK version: 3.1.0-edge.08eb081a8208a78969b1390a295693682d82b2eb (be) (Fri Apr 28 15:31:35 2023 -0700) on "macos_x64"
Platform: macOS
Compiler: dart2js
Command: `dart compile js --enable-experiment=inline-class <test_file>`

Code:

```dart
// SharedOptions=--enable-experiment=inline-class

inline class X {
  final int obj;
  X() : obj = 0;
  X.named() : obj = 0;
}

void main() {
  print((X.new)().obj);
  print((X.named)().obj);
}
```

Result:

```
Info: Compiling with sound null safety.
<test_file>:10:12:
Error: Member not found: 'new'.
  print((X.new)().obj);
           ^^^
<test_file>:11:12:
Error: Member not found: 'named'.
  print((X.named)().obj);
           ^^^^^
Error: Compilation failed.
```

The AST seems to create tear-off descriptors correctly for inline class constructors, but `StaticInvocation`s are missing a target.

cc @johnniwinther

**Comment by srujzs** [comment]
Thanks for the quick turnaround, @johnniwinther ! A question on the lowerings: should the inline constructor tear-offs be marked as `isInlineClassMember` or no? Currently, it looks like they're not, and I can't tell if that's intentional or not.

**Comment by johnniwinther** [comment]
That's unintentional. Fix: https://dart-review.googlesource.com/c/sdk/+/302206
