### ISSUE TITLE
language/call/method_must_not_be_field_test/03 is failing on arm64c

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#52257]
The tests
```
language/call/method_must_not_be_field_test/03 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-android-release-arm64c
```

The state had been `RuntimeError` for years. Yesterday it switched to `Fail` for exactly one run, then reverted to `RuntimeError`, so is now showing up as red, even though nothing really has changed.

Example `RuntimeError` log: https://dart-ci.appspot.com/log/vm-aot-android-release-arm64c/vm-aot-android-release-arm64c/558/language/call/method_must_not_be_field_test/03

**Comment by whesse** [comment]
Duplicate of #51517
