### ISSUE TITLE
[analyzer] GeneralizingAstVisitor.visitComment is only visiting documentation typed comments

### ISSUE THREAD

**Issue by MattisBrizard** [dart-lang/sdk#52262]
Hi, i found that `GeneralizingAstVisitor.visitComment` was only visiting documentation typed comments.

But the Comment AstNode documentation indicates that a Comment could be a `endOfLineComment` or `blockComment` or `documentationComment` :
```dart
/// A comment within the source code.
///
///    comment ::=
///        endOfLineComment
///      | blockComment
///      | documentationComment
///
///    endOfLineComment ::=
///        '//' (CHARACTER - EOL)* EOL
///
///    blockComment ::=
///        '/ *' CHARACTER* '&#42;/'
///
///    documentationComment ::=
///        '/ **' (CHARACTER | [CommentReference])* '&#42;/'
///      | ('///' (CHARACTER - EOL)* EOL)+
///
/// Clients may not extend, implement or mix-in this class.
```
I also found that the associated test : [test_visitComment()](https://github.com/dart-lang/sdk/blob/adb38d2eca032dfcaba0725ac7ae39f8fc5dc3e6/pkg/analyzer/test/src/dart/ast/to_source_visitor_test.dart#L698-L708), was only testing for documentation comment.

Did i missed something to visit endOfLine and block comments ?
Thanks.

**Comment by bwilkerson** [comment]
The documentation for `Comment` is wrong (and probably has been for a very long time). We only create a `Comment` node for documentation comments.

If you want to find other comments you'll need to look in the token stream. The token stream is a bi-directional linked list of `Token`s. Every comment (including documentation comments) are represented by a token, but to improve the performance of the parser the comment tokens aren't in the linked list. Instead, each `Token` has a reference to an optional list of `preceedingComments`, which are the tokens for the comments that come before the token (with the lexically left-most token being first in the list).
