### ISSUE TITLE
Possible analyzer performance regression analyzing the flutter repo

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#52268]
CC @Hixie @jacob314 

See some graphs:

* https://flutter-flutter-perf.skia.org/e/?begin=1414088239&dots=false&end=1683225253&queries=sub_result%3Dflutter_repo_watch_maximum&requestType=0&selected=commit%3D34187%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dflutter_repo_watch_maximum%252Ctest%253Danalyzer_benchmark%252C
  * CC @zanderso @godofredoc Can you say what this benchmark measures? Is there a doc or is the impl easy to understand?
  * This seems to highlight https://github.com/flutter/flutter/commit/9e4b5fb7d986fe1a92f92d970f8021e2c1e1603d which added a few dozen/hundred new elements. 🤷 
  * Also https://github.com/flutter/flutter/commit/c7bab2973eb19a7f640f9708816f2aa7458fdb0b which is titled "Move analyzer_benchmark_vm to vm" 🤔 
* https://golem.corp.goog/Benchmark?repository=flutter-analyze&benchmark=analyze_flutter_repository
  * This does not show any dramatic increase, but there is a bump from 145s to 150s. To investigate...

**Comment by zanderso** [comment]
The benchmark in the SkiaPerf link is running `flutter analyze --flutter-repo --watch` 3 times and reporting the max, deleting the cached analysis results between runs.

The noise in the SkiaPerf chart on the right-hand side is due to it moving from Flutter's devicelab where it ran on a dedicated machine by itself to a Linux VM. The Linux VM likely shares a machine with other tasks, and so results are slower and noisier.  I filed https://github.com/flutter/flutter/issues/126090 as the pre-req for moving the benchmark back to a dedicated machine in the device lab.

**Comment by srawlins** [comment]
Thank you so much, Zach!

**Comment by bwilkerson** [comment]
Without more information I don't know how big the actual regression is or how widespread the effects, so I don't know what priority to give it. Advice welcome.

**Comment by Hixie** [comment]
I think the sharp regression on the charts is an artifact of changing how the data is collected and isn't real.

I don't think there's a single regression. I think it may in fact just be that the codebase is growing. The net result though is that it now takes literally a minute or more for some changes to the Flutter framework to get fully processed by the analyzer when you run `flutter analyze --watch --flutter-repo`, even on my 20-core workstation.

**Comment by bwilkerson** [comment]
In case it's easier for profiling/debugging, the `--watch` option uses the analysis server, so we ought to be able to see the same behavior in an IDE, and we ought to be able to profile the analysis server directly.

I'm guessing that the kind of change that takes this long is one that requires a re-analysis of a significant portion of the codebase. Could you give us an example of such a change? (I'm not familiar enough with the Flutter codebase to know what a good example would be.)

**Comment by srawlins** [comment]
I'm calling this stale.
