### ISSUE TITLE
[dart2wasm] Implement `NativeFinalizer`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52261]
For context: the VM implementation is inside the GC, and the relevant standard libraries and patch files interact with that.

* https://dart-review.googlesource.com/c/sdk/+/238086
* https://dart-review.googlesource.com/c/sdk/+/236320

I have no idea what the primitives in WASMGC are that can be used to do this.

Filing a tracking bug so we can point somewhere.

**Comment by askeksa-google** [comment]
`Finalizer` was implemented in https://dart-review.googlesource.com/c/sdk/+/279718

**Comment by mkustermann** [comment]
We don't officially support `dart:ffi` for end users (will make it an error for 3rd parties soon). I'm going to close this in favor of the more general [Implement `dart:ffi` for the web](https://github.com/dart-lang/sdk/issues/46690).

**Comment by dcharkes** [comment]
> will make it an error for 3rd parties soon

@mkustermann  That would break the current workflow for the FFIgenpad project. Maybe we should put it behind an experiment flag instead of hard disallowing it?

**Comment by mkustermann** [comment]
> @mkustermann That would break the current workflow for the FFIgenpad project. Maybe we should put it behind an experiment flag instead of hard disallowing it?

Let's have that discussion offline (what FFIgenpad is, what it wants to do and how to best do it).
