### ISSUE TITLE
Seal `FileSystemEntity`.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#52273]
Similar to https://github.com/dart-lang/sdk/issues/52027 and https://github.com/dart-lang/sdk/issues/51912, could `FileSystemEntity` also be sealed so that functions like:

```dart
Z matchFileSystemEntity<Z>({
  required final FileSystemEntity entity,
  required final Z Function(Directory) directory,
  required final Z Function(File) file,
  required final Z Function(Link) link,
}) {
  if (entity is Directory) {
    return directory(entity);
  } else if (entity is File) {
    return file(entity);
  } else if (entity is Link) {
    return link(entity);
  } else {
    throw Exception(
      "Invalid state. " + entity.toString() + " was expected to be a directory, file or link.",
    );
  }
}
```

can be replaced with exhaustive switches?

**Comment by sortie** [comment]
Note how there's a number of file types that exist but that Dart doesn't really support, such as block devices and character devices. It's bad idea to write code that exhaustively consider file types.

**Comment by brianquinlan** [comment]
This isn't really practical because there is a lot of code that `extends` or `implements` `FileSystemEntity` (or it's subclasses) for testing purposes.
