### ISSUE TITLE
Do records introduce wrapping objects?

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#52278]
I'm planning to implement a LRU cache with a inline-class and a record in order to avoid overhead of a object wrapping a LinkedHashMap.
Now, I have a question if records introduce wrapping objects or not.

```dart
inline class Cache<K, V extends Object> {
  Cache(int size) : _data = (map: {}, size: size);
  final ({Map<K, V> map, int size}) _data;

  V? operator [](K key) {
    var value = _data.map.remove(key);
    if (value != null) {
      _data.map[key] = value;
    }
    return value;
  }

  void operator []=(K key, V value) {
    _data.map.remove(key);
    _data.map[key] = value;
    if (_data.map.length > _data.size) {
      _data.map.remove(_data.map.keys.first);
    }
  }
}
```

**Comment by lrhn** [comment]
Maybe.

Records *are* objects. The one thing that is guaranteed is that if you check, a record is an object.
You can assign a record value to `Object`. You can do `Object o = (1, 2); print(o is (int, int));`.
Generally you should assume that there will be an object, with a record type as runtime type, containing the field values.

The one thing records have going for them is that they are not required to preserve identity over time.
That means that compilers are free to unbox/inline a record's fields, and rebox them later.
That *enables* optimizations, but it doesn't guarantee anything.

**Comment by Cat-sushi** [comment]
Thank you for your explanation.
I understand that unboxing of records is a optimization issue.
