### ISSUE TITLE
Building instructions have broken link

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#52286]
from https://github.com/dart-lang/sdk/wiki/Building

"See also [building for ARM](https://github.com/dart-lang/sdk/wiki/Building-Dart-SDK-for-ARM-processors)."

That link does not exist.

FYI @mraleph who was the last to edit the page.

**Comment by mraleph** [comment]
Fixed. The target page was renamed to include RISC-V which orphaned the incoming link.
