### ISSUE TITLE
[Inline Class] The analyzer doesn't emit any error for overriding members inherited from `Object`.

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#52285]
For the code below, the analyzer doesn't emit any error, but the compiler does.
This is also true for `hashCode` and `runtimeType`.

DartPad Based on Flutter 3.11.0-0.0.pre Dart SDK 3.1.0-63.0.dev

```dart
inline class Id {
  Id(int id) : _id = id;
  final int _id;
  @override
  String toString() => '[$_id]';
}
```

```
Error compiling to JavaScript:
Info: Compiling with sound null safety.
lib/main.dart:5:10:
Error: This extension member conflicts with Object member 'toString'.
  String toString() => '[$_id]';
         ^^^^^^^^
Error: Compilation failed.
```

**Comment by scheglov** [comment]
The analyzer does not support inline classes at all, at least currently.

**Comment by bwilkerson** [comment]
You can watch https://github.com/dart-lang/sdk/issues/49732 to see when this support is started.
