### ISSUE TITLE
[CP] Fix DDC type test correctness

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#52282]
### Commit(s) to merge

b18efe2

### Target

Stable 3.0.1

### Prepared changelist for beta/stable

TDB if needed

### Issue Description

In specific scenarios DDC type checks produce incorrect results due to an incorrect optimization. DDC used the type parameter bound in explicit type checks (ex: `x is T`) instead of the instantiated type. This was limited to type parameters with a bound of `num`, `int`, `double` `String` or `bool` and only when the type parameter is instantiated as a subtype of the bound. In practice the issue is only observable according to this table:

| Bounded type parameter | When instantiated as | Incorrectly allows to pass type checks |
| --- | --- | --- |
| `T extends num` | `int` | non-integer numeric values |
| `T extends num` | `Never` | numeric values |
| `T extends int` | `Never` | integer numeric values |
| `T extends double` | `Never` | numeric values |
| `T extends String` | `Never` | String values |
| `T extends bool` | `Never` | boolean values |

### What is the fix

The fix simply no longer uses the optimization and uses the passed type argument value in type tests instead.

### Why cherry-pick

Personally I don't think this fix is cherry pick worthy but I wanted to highlight it for discussion since it was discovered by a language test for the patterns feature. The bug has been present and gone unnoticed for years. It even existed before we introduced null safety (if you replace `Never` with `Null` in the table above) without anyone reporting a problem. Instantiating a type argument as `Never` is not common and the difference between `int`s and `double`s is blurred when running on the JavaScript platform already so running into the bug is not easy.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52243

### Extra Info

If we think this should be cherry-picked I will create the necessary changelist.

**Comment by itsjustkevin** [comment]
@munificent and @leafpetersen could you take a look and decide if this should be cherry-picked or wait for Dart 3.1?

**Comment by munificent** [comment]
Answering this is a bit above my paygrade, but my opinion is that we shouldn't cherrypick it:

* As Nick notes, this bug has essentially existed for years with no one noticing until a funny patterns test happened to tickle it. I don't think we've ever seen it manifest in real end user code.
* This does change the code that DDC generates for type tests so, there is potentially some impact to generated code size. Nick would know more.

It's definitely a bug and we should fix it. But I don't see much reason to rush a cherry-pick.

**Comment by itsjustkevin** [comment]
Looks like https://github.com/dart-lang/sdk/issues/52243 is closed.  Maybe we should close this cherry-pick request and open a new issue to track it.

**Comment by nshahan** [comment]
@itsjustkevin 
I'm confused about your comment, what would we open a new issue to track? 

https://github.com/dart-lang/sdk/issues/52243 was opened when the DDC bug was discovered. It is closed because the issue has been fixed. I opened the cherry-pick request just in case others thought this fix was important enough to cherry-pick (I do not feel it is).

**Comment by sigmundch** [comment]
I agree with both @nshahan and @munificent here. We have no reason to believe that this issue is more prominent in Dart 3 than before, so I am inclined *not* to cherry-pick at this time and let this be released in 3.1 by default.

Of couse, if something changes (e.g. more users seem to be affected by this) we can revisit the decision.

**Comment by leafpetersen** [comment]
Agreed, let's just let this go out in 3.1

**Comment by athomas** [comment]
Closing, based on comments above.
