### ISSUE TITLE
[Inline Class] Members inherited from `Object` can't be accessed through inline classe variables.

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#52284]
For the code below, the analyzer doesn't emit any error, but the compiler does.
This is also true for `hashCode` and `toString()`.

DartPad Based on Flutter 3.11.0-0.0.pre Dart SDK 3.1.0-63.0.dev

```dart
inline class Id {
  Id(int id) : _id = id;
  final int _id;
}

main() {
  var c = Id(2);
  print(c.runtimeType); // int
}
````

```
Error compiling to JavaScript:
Info: Compiling with sound null safety.
lib/main.dart:8:11:
Error: The getter 'runtimeType' isn't defined for the class 'Id'.
  print(c.runtimeType); // int
          ^^^^^^^^^^^
Error: Compilation failed.
```

**Comment by eernstg** [comment]
Yes, this is a bug, cf. [this rule](https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md#:~:text=If%20the%20name%20of%20m%20is%20a%20name%20in%20the%20interface%20of%20Object).

(You could say that the rationale is that it works as if we had specified `implements Object`, except that this is a feature which hasn't yet been accepted as part of the inline class feature ;-).
