### ISSUE TITLE
pkg:analyzer `LibraryElement(Impl)` has an empty toString if it has no library directive + name

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#52280]
It'd be nice if it was `'Library: ${source.uri}'` or similar for the toString

**Comment by bwilkerson** [comment]
What is the impact of this issue?

**Comment by kevmoo** [comment]
Improves general debugging. Not a huge issue.

**Comment by kevmoo** [comment]
it seems like every (other) element has a reasonable and helpful `toString`. The library is this case is just an empty string. Just printing the class name would be more helpful!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/301726
