### ISSUE TITLE
dart:math library asin function returns different results across native platforms

### ISSUE THREAD

**Issue by luizbarboza** [dart-lang/sdk#52292]
I have noticed a discrepancy in the behavior of the `asin` function from the `dart:math` library across different operating systems. Specifically, when executing the function on Ubuntu, the values -0.8613343773019345 and -0.8613328769698687 produce -1.0378903813942377 and -1.037887428215712, respectively. However, on Windows and macOS, the same input values yield -1.0378903813942375 and -1.0378874282157122, respectively. It is worth noting that the latter values match those returned by the `Math.asin` method in JavaScript.

Can it be clarified if the expected behavior is that the results in Ubuntu are necessarily identical to those in Windows and macOS? Alternatively, is the current behavior of the function considered as intended?

Environment:

**Ubuntu 22.04**
- OS Version: 22.04.2 LTS
- Kernel Version: 5.15.0-1036-azure
- Image Version: 20230426.1
- Systemd version: 249.11-0ubuntu3.9
- Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "linux_x64"

**Windows Server 2022**
- OS Version: 10.0.20348 Build 1668
- Image Version: 20230502.2
- Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "windows_x64"

**macOS 12**
- OS Version: macOS 12.6.5 (21G531)
- Kernel Version: Darwin 21.6.0
- Image Version: 20230425.1
- Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_x64"

**Comment by mraleph** [comment]
I think current behaviour is considered as intended. We just call whatever implementation of `asin` that libc provides without any portability or precision guarantees. 

/cc @lrhn

**Comment by lrhn** [comment]
Agree. We do not try to invent our own trigonometric functions, we just use whatever is provided by the compiler.

As @mraleph says, it's not the *platform*/operating system as much as it is the C++ compiler's standard library (libc) that matters. (Or the browser's JavaScript implementation on the web, which can also differ between browsers. It might not - at least Firefox seems to agree with Chrome, at least on `Math.asin`, but I know there have been discrepancies in the past.)

We *could* try to standardize on a particular implementation on native platforms too,  say by copying the [V8 implementation](https://github.com/v8/v8/blob/d721a9d40627a80acc27a0b856e82a2b20d8d834/src/base/ieee754.cc#L701).
It's extra work, and may or may not be as efficient as what comes with the compiler anyway.
