### ISSUE TITLE
Platform.resolvedExecutable gives invalid path for network UNC

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#52309]
See https://github.com/fluttercommunity/plus_plugins/issues/1483#issuecomment-1538725544 for more information.

In [`Platform::ResolveExecutablePath`](https://github.com/dart-lang/sdk/blob/6e18b083dd302a4c32bd6c49a50e68f3cea7331a/runtime/bin/platform_win.cc#LL261C1-L280C1), if Windows returns a UNC such as `\\?\UNC\server\share\folder\file.exe` from [GetModuleFileNameW](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew), this will become stripped to `UNC\server\share\folder\file.exe`, which is *not* a valid Windows file path.

I believe this is due to some incorrect URL editing here:
https://github.com/dart-lang/sdk/blob/6e18b083dd302a4c32bd6c49a50e68f3cea7331a/runtime/bin/file_win.cc#L1060-L1065

Documentation on valid file path formats on Windows can be found here: 
https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats

/cc @bkonyi @aam

**Comment by timsneath** [comment]
It's not clear why we remove `\\?\` at all? Is it out of a fear that it's not a valid file syntax? 

To this untrained PM eye, it seems dangerous to be editing paths like this by hand if at all possible.

**Comment by timsneath** [comment]
OK, I'll trade you for a broken one :)

```dart
import 'dart:io';

main() {
  print(Platform.executable);
  print(Platform.resolvedExecutable);
}
```

```terminal
[C:\src\scratch] \\.\UNC\MICA\Flutter\bin\cache\dart-sdk\bin\dart.exe io.dart
\\.\UNC\MICA\Flutter\bin\cache\dart-sdk\bin\dart.exe
UNC\MICA\flutter\bin\cache\dart-sdk\bin\dart.exe
```

the former is a valid file path; the latter is not.

**Comment by aam** [comment]
Ah, I see, thanks. `Platform.resolvedExecutable` gets malformed when we attempt to canonicalize Windows path and remove `\\?\`, which was thought to be used specifically to prefix long-paths, letting Windows to bypass MAX_PATH limitation.
UNC paths were not considered, but somehow they should be.
