### ISSUE TITLE
Dart_Invoke for Named Parameters

### ISSUE THREAD

**Issue by anlumo** [dart-lang/sdk#52319]
I checked the tag `3.1.0-90.0.dev` and the main branch for this.

The call `Dart_Invoke` implemented in sdk/dart_api_impl.cc allows calling Dart functions from C code (or any language that can interop with C functions). However, it does not allow passing named parameters. It specifically says so in the code:

https://github.com/dart-lang/sdk/blob/40d99bc981f81aed65f107cf6907b705cd33ef4f/runtime/vm/dart_api_impl.cc#L4691

My use case would necessitate such a feature, because nearly all Flutter SDK calls use named parameters in some way. The alternative is to have some kind of decoding function on the Dart side that then invokes the function, but that's a lot of overhead in an already very expensive operation, which is not ideal in performance-critical code such as Flutter widgets.

I can't find a technical reason why this isn't implemented (other than needing extra code). So, it would be very helpful to get this addition.

**Comment by mraleph** [comment]
Can you elaborate a bit more on your use case? My inclination would be to *not* expand reflective embedder API beyond what is absolutely necessary.

**Comment by anlumo** [comment]
My use case is that I want to implement plugins in a Flutter application using web assembly modules. For this, I have to forward the calls to the application though my Rust layer (using wasmer as the wasm runtime).

**Comment by mraleph** [comment]
> My use case is that I want to implement plugins in a Flutter application using web assembly modules. For this, I have to forward the calls to the application through my Rust layer (using wasmer as the wasm runtime).

Are you using custom build of Flutter engine? Normal builds are supposed to be hiding Dart VM C API. 

What's your plan for release builds? You should be only able to call things which are marked with `@pragma('vm:entry-point')` and most of the things in Flutter framework are not marked with it. Strictly speaking we should be enforcing this restriction in debug mode as well, but we are a bit lax.

**Comment by mraleph** [comment]
> Since I ran into this roadblock, it also doesn't make sense to continue down this road unless I find a solution.

I see. Just want to reiterate that you will *not* be able to call anything through `Dart_Invoke` in release builds unless it is marked with an `entry-point` pragma. And if you start applying `entry-point` indiscriminately across the whole API surface the code quality (and code size) will suffer. This is going to be a much bigger roadblock.  

As a temporary solution to unblock your prototyping you can just patch your engine, e.g. add `Dart_InvokeWithNamed(...)` which allows you to pass names down instead of defaulting to empty `arg_names`. Underlying invocation APIs allow names.

**Comment by anlumo** [comment]
Ok, I see. Thank you for the pointers! I was able to use the analyzer package to get a list of all Flutter classes with all functions and parameters, so I might have to resort to writing some glue code generator for this anyways (obviously with an allowlist, since I don't need most classes within plugins and it'd be way too large).

**Comment by mraleph** [comment]
@anlumo you might want to check what https://pub.dev/packages/dart_eval is doing and see if they have existing tooling for this.

**Comment by anlumo** [comment]
I've experimented with this package (most notably, [my interactive Dart Terminal application](https://github.com/anlumo/dart_terminal) [[web demo](https://anlumo.github.io/dart_terminal/#/)]). There are two problems with it:

1. It uses its own bytecode interpreter, which is probably not great for performance.
2. It doesn't support all of Dart 2's features, not even thinking about Dart 3 features.

There's also the [xml_layout](https://pub.dev/packages/xml_layout) package, which uses XML instead of Dart to solve the same problem, and probably also has the same performance implications.

So, my idea was to talk directly to the Dart VM to bypass these issues, but since this isn't really viable, I probably ultimately have to go into one of those two directions.
