### ISSUE TITLE
[analyzer] Error when omitting base/final/sealed on base/final superclasses through legacy libraries.

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#52315]
https://github.com/dart-lang/sdk/blob/main/tests/language/class_modifiers/trans_legacy/legacy_superdeclaration_error_test.dart
Missing errors from line 46 and onwards.

The analyzer is not reporting an error when a class from a 3.0 library is a subclass of a class in a 2.19 library whose supertype is from the core libraries.

**Comment by kallentu** [comment]
@sgrekhov
[versioning_A03_t01.dart](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Class-modifiers/versioning_A03_t01.dart) - checks that final class cannot be extended
[versioning_A03_t04.dart](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Class-modifiers/versioning_A03_t04.dart) - checks that mixin on a final class cannot be declared

I believe these two tests should be fixed on the analyzer side now.

**Comment by sgrekhov** [comment]
Confirmed. Fixed. Thanx
