### ISSUE TITLE
[CP] Patterns parser: prohibit variable/identifier patterns named when/as.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52311]
### Commit(s) to merge

dc639c13cb7edc673f609259755e1fe0a95703d6

### Target

Stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/302100

### Issue Description

Before the release of Dart 3.0, it was discovered that if the variable name in a variable pattern, or the identifier in an identifier pattern, was `when` or `as`, that would lead to a parsing ambiguity which could not be resolved with the current amount of lookahead the parser possesses. This caused parse errors for patterns like:
```dart
case Enum.value when !flag:
```
(The parser would erroneously interpret `Enum.value` as a type and `when` as the name of a pattern variable).

To reduce risk to the Dart 3.0 release, we fixed this in a minimal way, by prohibiting the variable name in a variable pattern from being called `when` or `as`, but only in those circumstances where the ambiguity arose.

At the same time, we made a change on the main development branch that prohibits `when` or `as` from being used as the variable name in _any_ variable pattern, and simultaneously prohibits `when` or `as` from being used as the identifier in an identifier pattern. (We also updated the spec in https://github.com/dart-lang/language/pull/3033). This cherry-pick brings over that change to the stable branch, bringing the implementation in line with the spec.

### What is the fix

Three new error codes are introduced, to cover the three circumstances in which `when` or `as` might be used illegally: in a declared variable pattern, in an assigned variable pattern, or in an identifier pattern. The parser is modified so that it generates these errors in appropriate circumstances.

### Why cherry-pick

This change makes the implementation more consistent (both with itself and with the spec), and helps users avoid future trouble by preventing people from writing new code with patterns that refer ambiguously to identifiers named `when` or `as`.

If we don't do this cherry-pick, we'll have to accept in perpetuity that Dart 3.0 allows these ambiguous identifier names, and any efforts to prohibit these names in the future will require a language-versioned change (which is significantly more maintenance effort for the Dart team).

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52260

**Comment by itsjustkevin** [comment]
@vsmenon @leafpetersen @munificent and @mit-mit could you take another look at this cherry-pick

**Comment by munificent** [comment]
> we'll have to accept in perpetuity that Dart 3.0 allows these ambiguous identifier names, and any efforts to prohibit these names in the future will require a language-versioned change (which is significantly more maintenance effort for the Dart team).

I mean, we *could* ship it as a non-versioned breaking change.

But, yes, I think getting this fix in sooner and closing the barn door before the horse gets out seems like a good idea.

**Comment by leafpetersen** [comment]
LGTM
