### ISSUE TITLE
Support type promotion with object patterns

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#52325]
I'm wondering if using an object pattern could promote the type in the same way an if statement does. For example, this code promotes the variable `foo`:

```dart
void main() {
  Object? foo = 123;
  if (foo is int) {
    print(foo / 10);
  } else {
    print(foo);
  }
}
```

But in Dart 3, a switch statement with an object pattern doesn't promote `foo`:

```dart
void main() {
  Object? foo = 123;
  switch(foo) {
    case int:
      print(foo / 10);
    default:
      print(foo);
  }
}
```

```
The operator '/' isn't defined for the type 'Object'.
```

**Comment by blaugold** [comment]
`case int` matches the constant `Type` value for `int`.

What you want to use is a [variable pattern](https://github.com/dart-lang/language/blob/main/accepted/future-releases/0546-patterns/feature-specification.md#variable-pattern):

```dart
void main_() {
  Object? foo = 123;
  switch(foo) {
    case final int foo:
      print(foo / 10);
    default:
      print(foo);
  }
}
```

**Comment by lrhn** [comment]
Another case for https://github.com/dart-lang/language/issues/2911.

And as @blaugold points out, it does promote when the pattern actually checks the type.

**Comment by johnpryan** [comment]
Oops, I didn't realize I was matching the type `int` and not the value. This code works also:

```dart
void main() {
  Object? foo = 123;
  switch(foo) {
    case int():
      print(foo / 10);
    default:
      print(foo);
  }
}
```

**Comment by lrhn** [comment]
It's a very well known foot-gun in the new switch syntax. 
I personally blame type literals for the problem, not switches (https://github.com/dart-lang/language/issues/2393 :wink:).

We plan to have a lint reminding you to do something else when you write `case Type:` (https://dart-lang.github.io/linter/lints/type_literal_in_constant_pattern.html).
