### ISSUE TITLE
[CP] [CFE][ffi] Support FFI Finalizable transformation of redirecting factories

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#52332]
### Commit(s) to merge

cc40e17fd9ae4680371c4a3efb4c4762f33946bd

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/302202

### Issue Description

A redirecting factory is normally encoded as something like

```
  static factory •({required self::HelperClass bar = #C1}) → self::Bar
    return new self::Foo::•(bar: bar);
```

which the CFE also expects to recreate its internal state when loading
a dill file.

The Finalizable transformation from FFI can change that to something
like:

```
  static factory •({required self::HelperClass bar = #C1}) → self::Bar {
    return block {
      final synthesized self::Foo :expressionValueWrappedFinalizable = new self::Foo::•(bar: bar);
      _in::reachabilityFence(bar);
    } =>:expressionValueWrappedFinalizable;
  }
```

though, which the CFE doesn't understand and subsequently crashes.

### What is the fix

The fix makes the CFE understand this transformed version, fixing the crash.

### Why cherry-pick

Crashing if for instance using the Realm package.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/124369

**Comment by itsjustkevin** [comment]
Marking this as approved based on @mraleph comment above.  @johnniwinther please remove the approval if you feel otherwise.
