### ISSUE TITLE
Flutter extension in VSCode v3.62.0 breaks auto-complete

### ISSUE THREAD

**Issue by rirjkl19** [dart-lang/sdk#52330]
Hello, I am writing to report a bug in the Flutter extension for VSCode version 3.62.0. After updating the extension, I noticed that the auto-complete feature does not work as expected for files and classes that are deeply nested in the folder structure.

For example, if I have a class named `MyCustomWidgetButton` in a subfolder and I type `MyCustomWidg` in another file, I expect the extension to suggest `MyCustomWidgetButton` and automatically import it. However, this does not happen in v3.62.0. The last version that this worked correctly was v3.60.0.

This is a serious issue for me (or the team) because we have many custom widgets in our project and we rely on the auto-complete feature to save time and avoid errors (at least know we already have an existing widget). I have reverted back to v3.60.0 for now, but I hope this bug can be fixed soon.

Here is the VSCode extension. 

```
Name: Flutter
Id: Dart-Code.flutter
Description: Flutter support and debugger for Visual Studio Code.
Version: 3.60.0
Publisher: Dart Code
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

Please let me know if you need more information or if there is a proper workaround for this problem. Thank you!

**Comment by vsmenon** [comment]
Could you please provide your Dart SDK version as well?  

@DanTup - should this be transferred to Dart-Code?

**Comment by rirjkl19** [comment]
> Could you please provide your Dart SDK version as well?
> 
> @DanTup - should this be transferred to Dart-Code?

```
Name: Dart
Id: Dart-Code.dart-code
Description: Dart language support and debugger for Visual Studio Code.
Version: 3.63.20230502
Publisher: Dart Code
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code
```

**Comment by DanTup** [comment]
@rirjkl19 do you happen to be using the legacy protocol for the analysis server?

<img width="1176" alt="Screenshot 2023-05-10 at 09 52 52" src="https://github.com/dart-lang/sdk/assets/1078012/0e09329a-338a-4d63-9707-2559ef2f70e5">

The only change I can find between v3.60 and v3.62 related to completion affected the legacy protocol. If you're using that, I would suggest turning it off (note: it could be set by either User Settings or Workspace Settings). If there are reasons you think you need to use it, please file an issue at https://github.com/Dart-Code/Dart-Code/issues/new/choose with some information about why.

If that is the issue, it's been fixed and a release is due later this week. It's also already available in the pre-release version of the extension:

<img width="703" alt="Dart pre-release versions" src="https://user-images.githubusercontent.com/1078012/218796750-90a70b0b-4957-468c-8eb4-688095cde112.png">

If you are _not_ using the legacy protocol, are you able to create a small repro I can use for debugging?

Thanks!

**Comment by rirjkl19** [comment]
@DanTup, Unfortunately I tried creating a new project and can't seem to replicate the issue. My only hunch on why I can't replicate it on the project we currently work on is it has too many files and classes. Especially we have apollo code generation for graphql. My estimate is the classes globally reachable would be more or less 10k. 

As for the legacy protocol. Yes turning it off seems to affect the behavior as well (auto-complete is not working properly) so I just keep it checked. And I also tried the pre-release but it doesn't also work. Only v3.60 seems to have that auto-complete behavior I was expecting.

**Comment by DanTup** [comment]
> As for the legacy protocol. Yes turning it off seems to affect the behavior as well (auto-complete is not working properly) so I just keep it checked

Can you file an issue at https://github.com/Dart-Code/Dart-Code about whatever issues you're seeing using the new protocol? The legacy protocol is not being advanced and become unavailable in a future release, it is not recommended for use.

Please also file an issue for the issue you see when using the legacy protocol in the current pre-release that you don't see in v3.60 and I'll provide some instructions for capturing logs/diagnostics that might help track down what's going on. I'll close this one while we'll continue in the Dart-Code issues until it's clear if there are SDK issues to resolve.

Thanks!

**Comment by DanTup** [comment]
> And I also tried the pre-release but it doesn't also work.

Oh, and just to be clear - you installed the _Dart_ pre-release and clicking the **Reload** button? The language functionality is all handled by the Dart extension, not the Flutter extension.

**Comment by rirjkl19** [comment]
> Oh, and just to be clear - you installed the _Dart_ pre-release and clicking the **Reload** button? The language functionality is all handled by the Dart extension, not the Flutter extension.

Hey @DanTup sorry it took me awhile to reply. Yes I tried the pre-release then reload (even closed the VSCode then reopened).

But the things is because of some trial and error to verify some things before filing a new issue. 

Using my previous workaround:
- flutter v3.60.0 
- dart v3.62 
- legacy analyzer protocol (off)

seems to be not working anymore 🤦🏻 .


Whats working right now is this:
- flutter v3.63.20230303 (pre-release)
- dart v3.63.20230502 (pre-release)
- legacy analyzer protocol (off)

Might really be something related to the legacy analyzer. I'm not sure anymore.

**Comment by DanTup** [comment]
@rirjkl19 to confirm, if you use the latest pre-release version, and you do _not_ use the legacy protocol, everything is working?

Or does it seem inconsistent? The code completion does have a time budget for the symbols that are not already imported, and if it takes too long then those results will be skipped. This shouldn't usually occur often, however it's more likely shortly after opening the project and the first time it's triggered.

If you still see problems using the latest pre-release (with either protocol), please do file issues at https://github.com/Dart-Code/Dart-Code. I would strongly recommend sticking on the new (LSP) protocol, and _not_ the legacy protocol though. This will ultimately be the only option (and almost all users use the new protocol) so if there's something not working right for you, we need to get to the bottom of it.

Thanks!

**Comment by rirjkl19** [comment]
> @rirjkl19 to confirm, if you use the latest pre-release version, and you do not use the legacy protocol, everything is working?

Agh! Correction with my previous comment:

Using my previous workaround thats not working anymore:
- flutter v3.60.0
- dart v3.62
- legacy analyzer protocol (CHECKED)

Whats working right now is this:
- flutter v3.63.20230303 (pre-release)
- dart v3.63.20230502 (pre-release)
- legacy analyzer protocol (CHECKED)


> @rirjkl19 to confirm, if you use the latest pre-release version, and you do not use the legacy protocol, everything is working?

Yes it seems unchecking the legacy analyzer causes issue with the auto-completion totally. Will need to note the variations of version with LSP ticked for filing this issue.

**Comment by DanTup** [comment]
> Using my previous workaround thats not working anymore:
> 
> - flutter v3.60.0
> - dart v3.62
> - legacy analyzer protocol (CHECKED)

I think you may have intended to switch to Dart v3.60 too. All of the language functionality is in the Dart extension so if this was broken by an extension update, it would've been the Dart one and not the Flutter one.

So, I'm fairly sure the recent issue you're seeing was a bug I introduced with the legacy protocol for not-imported completions, which is now fixed (in the pre-release, which should be released to stable this week). So I don't think there's anything to fix there.

However:

> Yes it seems unchecking the legacy analyzer causes issue with the auto-completion totally. 

This is concerning. Please do file an issue at https://github.com/Dart-Code/Dart-Code with a description of what is not working here, because the legacy protocol is going to go away and if something is not working, it needs to be fixed. My suspicion is that this is related to the time budget - but we need to investigate to be sure.

**Comment by DanTup** [comment]
FYI, v3.64.0 of the Dart extension has been published which includes the fix for the legacy protocol not including not-imported symbols in code completion (it no longer requires the pre-release version).

I'll follow up on https://github.com/Dart-Code/Dart-Code/issues/4534 with some instructions to help track down the issues you're seeing when using the LSP protocol. Thanks!

**Comment by fisforfaheem** [comment]
suggestions are also messed up, suggestions should feel natural and auto, instead of going down the list and selecting a suggestion is not natural feel

**Comment by DanTup** [comment]
@fisforfaheem can you provide more details on what you mean by "messed up"? Do you mean the ranking isn't ideal? In many cases the ranking is controlled by VS Code, but a screenshot showing the problem would help understand (it might also be better in its own issue). Thanks!

**Comment by U-MINDERS-TECH** [comment]
> @fisforfaheem can you provide more details on what you mean by "messed up"? Do you mean the ranking isn't ideal? In many cases the ranking is controlled by VS Code, but a screenshot showing the problem would help understand (it might also be better in its own issue). Thanks!

if you solve the error plz dear inform me i have the same issue

**Comment by fisforfaheem** [comment]
I think using dart extension with co pilot has become a big issue for me,
as suggestions and dart suggestions dont mix well
