### ISSUE TITLE
[CP] Roll dart_style 156f5c8c3bfe4e3b8e7adc95f7cf24d9500f11c6 into the SDK

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#52346]
### Commit(s) to merge

73dea244cc94dc7dbc00a751b2c3151797f4b836

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/302451

### Issue Description

This couple of few formatting issues around records and pattern matching, and fixes a rare performance regression in long parameter lists.

The CL description has the full details.

### What is the fix

Roll in a new commit of dart_style with the fixes.

### Why cherry-pick

The formatting of some records and switch expressions is pretty bad without these fixes. Since there is very little of that code in the wild today, getting a fix out soon will minimize churn from users to write new code, get it formatted poorly, and then have the formatting improved later.

### Risk

low

### Issue link(s)

See below:

### Extra Info

Here are the dart_style issues this fixes:

https://github.com/dart-lang/dart_style/issues/1212
https://github.com/dart-lang/dart_style/issues/1213
https://github.com/dart-lang/dart_style/issues/1215

**Comment by vsmenon** [comment]
lgtm

**Comment by munificent** [comment]
Should I wait for an LGTM on [the CL](https://dart-review.googlesource.com/c/sdk/+/302451) too before landing it?

**Comment by itsjustkevin** [comment]
Just waiting on it to be reviewed by someone!

**Comment by athomas** [comment]
I reviewed it.

[Doc](https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel#request-cherry-pick-approval) says:
> Send the changelist for review. Await the appropriate consensus and approval via the cherry-pick-approved for them or any OWNER to review the changelist.
> 
> Once the cherry-pick issue is approved and the changelist is reviewed, the cherry-pick author will submit it to the commit queue.

**Comment by munificent** [comment]
Landed: https://dart-review.googlesource.com/c/sdk/+/302451.
