### ISSUE TITLE
Generic type is overrided by the inheritance

### ISSUE THREAD

**Issue by mosleim** [dart-lang/sdk#52344]
I created a class that contains a generic data type.
```dart
class Buck<E> {
  List<E> list;
  Buck({
    required this.list,
  });
}
```
Then, I created a class and a subclass:
```
class SomeThing {}
class SomethingOther extends SomeThing {}
```
I created an object `Buck` with `E` is `SomeThing` class.
```
var buck = Buck<SomeThing>(list: List<SomeThing>.empty());
```
At this point, I assumed type of `buck.list` is `List<SomeThing>`. Then, I assign it with `List<SomethingOther>`.
```
buck.list = List<SomethingOther>.empty();
```
At this point, there is nothing unusual. I assume type of `buck.list` is still `List<SomeThing>`.
However, when I try to add `SomeThing` object to `buck.list`, I get an error:
```
buck.list.add(SomeThing()); // this will be error
```
Here is the complete code:
```
void main() {
  var buck = Buck<SomeThing>(list: List<SomeThing>.empty());
  buck.list = List<SomethingOther>.empty();
  buck.list.add(SomeThing()); // this will error
}

class Buck<E> {
  List<E> list;
  Buck({
    required this.list,
  });
}

class SomeThing {}
class SomethingOther extends SomeThing {}
```
Why does this happen? Is this expected behavior?

my machine:
> dart --version
> Dart SDK version: 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "macos_arm64"

**Comment by fishythefish** [comment]
This is expected behavior. Although `buck.list` has static type `List<SomeThing>`, the actual value it contains is a `List<SomethingOther>`, which can only hold `SomeThing`.

This happens because Dart generics are automatically covariant - if `T` is a subtype of `S`, then `List<T>` is a subtype of `List<S>`. Unfortunately, not every operation that is legal on a `List<S>` is legal on a `List<T>`, so you can still get runtime errors.

**Comment by eernstg** [comment]
@mosleim, agreeing completely with @fishythefish's explanation, I can't help noticing that the dynamically checked covariance that Dart uses works amazingly well, in the sense that there are very few complaints about the fact that a program with no compile-time errors or warnings can still encounter a type error at run time.

However, if you wish to help adding support for statically checked variance to Dart, you can vote for dart-lang/language#524.

> I assume type of `buck.list` is still `List<SomeThing>`.

Indeed, the _static_ type of `buck.list` in the given context is `List<Something>`, and `buck.list is List<SomeThing>` would yield true. However, this is similar to `buck.list is Object` yielding true: This just means that the run-time type of `buck.list` is a subtype of the specified type (`List<SomeThing>` respectively `Object`).

Starting from the fact that Dart does use dynamically checked covariance, we can still do something to avoid creating the situation that you mention:

```dart
class Something {}

class SomethingOther extends Something {}

class Buck<E> {
  List<E> list;
  Buck({
    required this.list,
  });
}

void main() {
  Buck<Something> buck = Buck<SomethingOther>(list: []);

  // Assign a new list to `buck.list`, preserving the type argument:
  buck.list = buck.list.take(0).toList();
}
```

There is no general `clone` or `cloneAsNew` operation in Dart, but we can at times use specific methods to obtain a fresh instance with the same type arguments, even in the case where those type arguments aren't statically known.

This means that if there was no covariant subtyping (here: `buck.list` having a more special type argument dynamically than statically), then there will not be any covariant subtyping after the assignment.

Another very useful technique in this area is to make `Buck.list` final and initialize it as `final List<E> list = [];`, if you can design the program to work without mutating `list` (you can still insert elements etc., but you can't make `list` refer to a different list). This means that the list is guaranteed to have actual type argument `E` (not a proper subtype of `E`). 

These techniques take away one step of the ladder of covariance: You may still have a `buck` of type `Buck<SomethingOther>` with static type `Buck<Something>`, but if you do have a `Buck<E>` for some `E` then it is guaranteed to have a `list` of type `List<E>`, and it's safe to insert an `E` into that list.
