### ISSUE TITLE
[CP] Account for differing flow analysis conventions between CFE and shared code.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52343]
### Commit(s) to merge

cb0eb28cbaedd032c234d3a5e372249603655765

### Target

Stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/302642

### Issue Description

When running in the VM, certain expressions that imply type promotions are sometimes rewritten by the compilation pipeline. If those expressions appear in certain contexts involving patterns, the rewrite could cause type promotion to be lost. This happens because of differences in flow analysis conventions between the front end and the shared implementation of patterns: the front end assumes that the rewritten expressions will be passed to flow analysis, whereas the shared logic assumes the original expressions will be passed to flow analysis.

For example, this code is accepted by the analyzer but not the VM, because the guard clause `j != null` is internally rewritten to `!(j == null)`, causing the promotion of `j` to non-nullable to be lost:
```dart
int f(int i, int? j) => switch (i) {
  0 when j != null => j,
  _ => i
};
```

### What is the fix

We account for the difference in conventions by adding a call to `FlowAnalysis.forwardExpression` to the front end's implementation of `dispatchExpression`. This ensures that when transitioning between front end logic and shared logic, flow analysis will be informed how to match up the rewritten expressions to their original counterparts.

### Why cherry-pick

This change fixes type promotion to be consistent between the analyzer and the VM. Without this fix, there could be customer frustration, because a type might appear to promote properly in the IDE, but then fail to compile when run under the VM.

The fix is confined to the new shared analysis infrastructure and the `dispatchExpression` method, which are only used for patterns and switch statements. Since switch statements didn't support any type promotion prior to Dart 3.0, this means that no user code written prior to Dart 3.0 should be affected. Also, since the change brings the VM behaviour into alignment with the analyzer, it shouldn't break any user code that is already accepted by the analyzer. So I believe the overall risk of this change is low.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52241, https://github.com/dart-lang/sdk/issues/52183

**Comment by itsjustkevin** [comment]
@johnniwinther for review!

**Comment by johnniwinther** [comment]
LGTM
