### ISSUE TITLE
Service.getInfo() does not work for test environment.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#52354]
Steps to repro:

```
clone git@github.com:polina-c/spikes.git
cd spikes/connect_vm
flutter test test/widget_test.dart
```

See output `Obtaining info...` and the test never finishes.

The output is from the code:
```
    print('Obtaining info...');
    final info = await Service.getInfo();
    print('Obtained info.');
```

There is no error as well.

**Comment by polina-c** [comment]
If I run the test by clicking 'Debug' in VSCode, I can successfully connect to the isolate with DEvTools, using url printed in debug console:

<img width="477" alt="Screenshot 2023-05-11 at 11 24 02 AM" src="https://github.com/dart-lang/sdk/assets/12115586/ba415ace-b13c-4312-8c00-4e1822a4e878">

<img width="666" alt="Screenshot 2023-05-11 at 11 22 21 AM" src="https://github.com/dart-lang/sdk/assets/12115586/1a6dd4a2-08de-4118-9832-681c2d16a2be">

**Comment by polina-c** [comment]
https://github.com/dart-lang/sdk/assets/12115586/a2fcfe32-d772-4075-8464-e4e0c38304de

**Comment by polina-c** [comment]
@bkonyi @a-siva @rmacnak-google

**Comment by bkonyi** [comment]
So I've done some digging and I'm not sure exactly what's going on here. The call to the service isolate to get the URI completes successfully and the `receivePort.handler` is executing `completer.complete(uriString)`. However, the completer's future isn't completing so we hang:

```dart
static Future<ServiceProtocolInfo> getInfo() async {
  // Port to receive response from service isolate.
  final RawReceivePort receivePort =
      new RawReceivePort(null, 'Service.getInfo');
  final Completer<String?> completer = new Completer<String?>();
  receivePort.handler = (String? uriString) {
    // This callback executes
    completer.complete(uriString);
  };
  // Request the information from the service isolate.
  _getServerInfo(receivePort.sendPort);
  // Await the response from the service isolate.

  //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  // **This future never completes**
  //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  String? uriString = await completer.future;

  Uri? uri = uriString == null ? null : Uri.parse(uriString);
  // Close the port.
  receivePort.close();
  return new ServiceProtocolInfo(uri);
  }
```

I wonder the event loop in `flutter_tester` is configured differently or does some weird stuff with futures. @christopherfujino, would you know anything about this or know who might?

**Comment by bkonyi** [comment]
@mraleph correctly identified this as an issue related to the use of `FakeAsync` in `flutter_tester`. The fix is to wrap the call to `Service.getInfo()` in [`tester.runAsync`]( https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html).
