### ISSUE TITLE
[analyzer] analyzer starts leaking when typing a switch expression

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#52352]
When I type the following code, analyzer memory usage just skyrockets. Restarting the process via VS Code does not kill the existing one.

<img width="486" alt="Screenshot 2023-05-11 at 17 04 33" src="https://github.com/dart-lang/sdk/assets/21116742/5fde3443-2756-4433-93db-9a95aaba0502">

<img width="441" alt="Screenshot 2023-05-11 at 17 00 21" src="https://github.com/dart-lang/sdk/assets/21116742/ca1f70fe-4a1f-4f6a-9e15-3b9bbaddcf9b">

Been able to repro this 2 times in a row.

Here is a video on produced errors.

https://github.com/dart-lang/sdk/assets/21116742/eac32fed-8a5f-4569-9105-d384e7faa2d7

Let me know what else I need to provide for this to be fixed.

```
#### General info

- Dart 3.0.0-417.4.beta (beta) (Tue May 2 10:26:14 2023 +0000) on "macos_x64"
- on macos / Version 12.6 (Build 21G115)
- locale is en-GB

#### Project info

- sdk constraint: '>=3.0.0-417.1.beta <4.0.0'
- dependencies: ansicolor, collection, crypto, file, glob, html, meta, path, pub_semver, recase, source_span, xml, yaml
- dev_dependencies: lints, mocktail, test
- elided dependencies: 4

#### Process info

|  Memory |   CPU | Elapsed time | Command line                                                                           |
| ------: | ----: | -----------: | -------------------------------------------------------------------------------------- |
| 6996 MB | 67.8% |        07:31 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.65.20230510 |
```

**Comment by incendial** [comment]
And it just keeps growing...
<img width="370" alt="Screenshot 2023-05-11 at 17 10 08" src="https://github.com/dart-lang/sdk/assets/21116742/8aedf6eb-de5f-4a56-94fb-9c4b445f3887">

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
It would be nice if you provided snippets of code with your issues.
It is somewhat inconvenient try to retype code from video :-P

**Comment by scheglov** [comment]
I cannot reproduce it with a simple example.
```dart
  solo_test_X() async {
    await assertErrorsInCode(r'''
void f(Object? x) {
  final innerIf = switch (x) {
    Block(statements: [IfStatement inner]) => inner,
  };
}

class Block {
  List<Statement> get statements => [];
}

class Statement {}

class IfStatement extends Statement {}
''', [
      error(WarningCode.UNUSED_LOCAL_VARIABLE, 28, 7),
      error(CompileTimeErrorCode.NON_EXHAUSTIVE_SWITCH_EXPRESSION, 38, 6),
    ]);

    final node = findNode.singleSwitchExpression;
    assertResolvedNodeText(node, r'''
''');
  }
```

From the fact that it uses CPU, it seems that it might got into an infinite cycle somewhere.

Locally, I always run DAS with Observatory enabled.
To do so, I set `dart.server.vm.options` in my IntelliJ to `--no_dds --observe:8181 --serve-observatory --disable-service-auth-codes`, and then use `cpu profile (table)` on `(main)` isolate to see if there is anything interesting.
<img width="854" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/9d39b781-3e79-4d0f-9f64-1b489f1f9fe3">

**Comment by scheglov** [comment]
I tried to type something similar in the IDE, outside tests, but cannot get it into "sticky errors" when it cycles :-(
```dart

void f(IfStatement node) {
  final innerIf = switch (node.thenStatement) {
    Block(statements: [IfStatement inner]) => inner,
    _ => null,
  };
  print(innerIf);
}
```

**Comment by incendial** [comment]
Interesting, now I also cant repro it in one go. I understood that when "dart.fix" added final:

```dart
final innerIf = switch (node.thenStatement) {
        Block(statements: [final IfStatement inner]) => inner,
      };
```

**Comment by incendial** [comment]
Yep, got it again. Trying to extract steps.

**Comment by incendial** [comment]
https://github.com/dart-lang/sdk/assets/21116742/558e12a2-dd34-471b-98d5-c8f6f9117e25


https://github.com/dart-lang/sdk/assets/21116742/32b543fb-7445-426b-8bd8-990016a89c4b

From my edit history exactly before the initial report.
<img width="354" alt="Screenshot 2023-05-11 at 23 18 52" src="https://github.com/dart-lang/sdk/assets/21116742/f2818831-4129-4a2d-97c8-5f45ec94f006">

Affects dcm as well.

**Comment by incendial** [comment]
As you can see on the second video analyzer is already slowed down, but it was not recorded instantly, probably after 2-3 GB leaked.

**Comment by incendial** [comment]
There is only one other issue present in the file (maybe it's related somehow).

<img width="707" alt="Screenshot 2023-05-11 at 23 22 08" src="https://github.com/dart-lang/sdk/assets/21116742/4fe59395-4639-487f-839d-3509aed66ef7">

```dart
  bool _isCollapsibleIf(IfStatement node) =>
      node.elseStatement == null && node.expression.;
```

**Comment by incendial** [comment]
<img width="341" alt="Screenshot 2023-05-11 at 23 23 52" src="https://github.com/dart-lang/sdk/assets/21116742/8f7d5e37-3e5b-4ef0-8b48-a35efa06f9b0">

**Comment by incendial** [comment]
Let me know if you need anything else.

**Comment by scheglov** [comment]
It might be not obvious, but I cannot reproduce it.
From the provided info I see that there is a problem, but I have no idea why and where.

**Comment by incendial** [comment]
I'll try to extract the exact step, I think I'm close.

**Comment by incendial** [comment]
```dart
final innerIf = switch (node.thenStatement) {
        Block(statements: [if])
      };
```

can you try this one? restarting analyzer here leads to immediate leak.

**Comment by incendial** [comment]
Note: I got `if` by typo in `final`.

**Comment by scheglov** [comment]
It seems to did it! y IDE does not update semantic highlighting, and the DAS process eats CPU.
Thank you!

**Comment by scheglov** [comment]
It looks to be cycling in the parser.
<img width="778" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/3f76d6ee-fcfa-44ce-b587-41101615ec4b">

**Comment by incendial** [comment]
You're welcome! This one was very tricky.
Actually, I thought it something related to the parser.

**Comment by scheglov** [comment]
I cleaned it up to
```dart
void f(Object? x) {
  switch (x) {
    case [if]
  };
}
```
This code cycles the unit test code above.

**Comment by incendial** [comment]
It even does not matter whether it's `case []` or ObjectPattern with []? Interesting. So it might be something old?

**Comment by stereotype441** [comment]
I'm able to reproduce this and I'm investigating.

**Comment by stereotype441** [comment]
Thanks @incendial and @scheglov for tracking down such a small repro! It made it a lot easier to debug the problem.

I've landed a fix in the main development branch, and I've requested approval too cherry-pick it into the 3.0.1 stable release (https://github.com/dart-lang/sdk/issues/52376).

**Comment by incendial** [comment]
Thanks! Considering the fix was in `_fe_analyzer_shared`, do you have a release date for the new version?

**Comment by stereotype441** [comment]
The code that gets run under the hood when you're interacting with your editor is the code that's included in the Dart SDK, even if that code comes ultimately from the `_fe_analyzer_shared` or `analyzer` package instead of directly from the analysis server. So it actually doesn't matter when we release `_fe_analyzer_shared`--you'll get the fix when you install a version of the SDK that includes it.

So far there's no published version of the SDK that includes the fix. Hopefully it will show up in the dev channel later today (dev channel builds have been happening about once every four hours recently). After that it will hopefully show up in the 3.0.1 stable hotfix (assuming my cherry-pick request gets approved). I'm currently checking whether there's a target date for 3.0.1 that I can share publicly.

**Comment by incendial** [comment]
I work on a tool that uses `analyzer` and `_fe_analyzer_shared` directly and I'm asking to pick the changes as well.

**Comment by stereotype441** [comment]
Ah, ok. In that case I'll defer to @scheglov, who usually does the releases of `analyzer` and `_fe_analyzer_shared`.

**Comment by scheglov** [comment]
I'm not ready to publish yet, would like to wait a few days after https://github.com/dart-lang/sdk/commit/a3956e49d0b778360edf181e1046f0f2ccf5e4dd

https://dart-review.googlesource.com/c/sdk/+/303012 for now, not that it is much useful for you, but it record that this issue is fixed :-)
