### ISSUE TITLE
[analyzer] Record syntax mismatched on fat arrow function declarations.

### ISSUE THREAD

**Issue by fourscience** [dart-lang/sdk#52365]
Probably related to the analyzer / linter.

Used dart:
`Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "macos_arm64"`

Problem description:
Using operator overloading on Functions with fat arrow notation is now mismatched by the analyzer for being a record definition.
Seems like it's not actually the overload but rather than wrapping the expression causing the function to be taken as a record.

For example:
`((value) => print(value)) >> "foo";`

Where Function has an operator ">>" overloaded.

However:
`(value) { print("$value"); } >> "foo";`
works just fine.
Which makes sense as this could be a record, but `var a = (1 + 2);` makes an int.

**This also breaks:**
`(1 + 2) >> 2;`

**Comment by bwilkerson** [comment]
@stereotype441 I'm guessing this would be a parser bug, probably because it's deciding too early that we have found a record and then can't change that decision when there's no trailing comma.

**Comment by stereotype441** [comment]
I'll take a look if I get a chance, but @jensjoha worked on parser support for records and probably can diagnose this more quickly than I can.
