### ISSUE TITLE
Update README.md to reflect dart 3+

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/sdk#52369]
Also update the Graphics to modern versions and add WASM and other new work.

**Comment by mit-mit** [comment]
Hi @fisforfaheem can you offer a bit more detail for what kind of updates you think are missing?

**Comment by fisforfaheem** [comment]
Dart is no longer just a client-optimized language. It can also be used to build server and desktop applications.

Dart's hot reload feature is no longer limited to UI changes. It can also be used to see the results of changes to code that affects the behavior of an app.

Dart can now be compiled into ARM64 machine code for mobile devices.

Dart now has first-class support for WebAssembly (WASM). 

Dart's flexible compiler technology has been improved, making it easier to choose the right compiler for your target platform and goals.

**Comment by parlough** [comment]
@mit-mit Do you think this is complete with your great updates in https://github.com/dart-lang/sdk/commit/9f3433b9d76848b4a22771e48af0c37d7f90aaa0?

**Comment by fisforfaheem** [comment]
The main document should be updated. Also the flutter main document on GitHub is older

**Comment by fisforfaheem** [comment]
Oh just saw the commit, thanks.

Also Can u kindly help me out with Flutter,I am unable to raise an issue, i posted something outside the guidelines back 2 years ago and since then unable to contribute at all don't know whom to contact 😕.
