### ISSUE TITLE
`super<Type>` fails to compile, but passes static analysis.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#52378]
Consider the following program:

```dart
class Bar {
  void call<T>() {}
}

class Foo extends Bar {
  void a() {
    super<int>;
  }
}
```

It fails to compile with the following error:

```
Error: Can't use 'super' as an expression.
    super<int>;
    ^^^^^
Error: Compilation failed.
```

but the analyzer doesn't emit any errors or warnings for it.

Reproducible on DartPad.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/303501
