### ISSUE TITLE
[ddc] remove all uses of `__proto__`

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#52372]
The old `__proto__` has been under support only for legacy reasons, the new recommendation is to convert all uses of `__proto__` to `getPrototypeOf` and `setPrototypeOf`

**Comment by annagrin** [comment]
related: https://github.com/dart-lang/webdev/issues/2118

**Comment by sigmundch** [comment]
@nshahan - seems like all of your changes landed. Do we have any remaining work here, or is it fair to close this issue now?

**Comment by nshahan** [comment]
I still have [one more use](https://github.com/dart-lang/sdk/blob/63d856d4878998e4732ef6e8c4ae9c23c3d40166/pkg/dev_compiler/lib/js/legacy/dart_library.js#L306) I want to cleanup before I mark it as complete but I got sidetracked when I started trying to figure out how to resolve the diffs between multiple versions. I'll finish it up soon.
