### ISSUE TITLE
Confusing docs of `dart_isolate::SendPort::send`

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#52370]
hi,

In the docs of [`dart_isolate::SendPort::send`](https://api.dart.dev/dev/3.1.0-101.0.dev/dart-isolate/SendPort/send.html), 
> Instances created by constructors of:
> - List, Map, ...

Is mentioned,

So,
- does `<int>[]` count as "created by **constructor**", or
- only `List<int>.filled(0, -1)` does?

thanks

**Comment by mkustermann** [comment]
The documentation is actually pretty precise, it says:
```dart
...
  ///   - Instances created through list, map and set literals
  ///   - Instances created by constructors of:
  ///     - [List], [Map], [LinkedHashMap], [Set] and [LinkedHashSet]
  ///     - [TransferableTypedData]
  ///     - [Capability]
...
```

> does <int>[] count as "created by constructor"

The `<int>[]` is what the language calls a "list literal".
=> The documentation says *Instances created through list (...) literals* can be sent.

> only List<int>.filled(0, -1) does?

The `List<int>.filled()` is an invocation of a (factory) constructor:
```dart
abstract interface class List<E> implements EfficientLengthIterable<E> {
  ...
  external factory List.filled(int length, E fill, {bool growable = false});
  ...
}
```
=> The documentation says *Instances created by constructors of - [List]* can be sent.

**Comment by mkustermann** [comment]
@gintominto5329 Does that explain your questions? How could the documentation be made more clear on this?

**Comment by mkustermann** [comment]
Closing this as-intended.
