### ISSUE TITLE
[analyzer] @useResult generates false positive when used inside record literal

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#52391]
Dart version: `3.0.0`
Meta version: `1.9.1`

The following usage of `@useResult` generates a false positive:

```dart
import 'package:meta/meta.dart';

@useResult
int foo() => 0;

final bar = (foo(),);   // The value of 'foo' should be used.
```

**Comment by scheglov** [comment]
I believe @pq  fixed this in 0cfb3611d42702e1485953354a02743668414f2a.

**Comment by Nhowka** [comment]
Will that be backported to 3.0.2? I noticed the issue when using `copyWith` pattern. The problem was fixed when testing on master channel.
![image](https://github.com/dart-lang/sdk/assets/10579995/13c11214-7e69-488d-b211-451a6ffb8ed5)

**Comment by pq** [comment]
Yeah. I think this is a good candidate for a cherry-pick.  Thanks @Nhowka!

**Comment by pq** [comment]
https://github.com/dart-lang/sdk/issues/52451
