### ISSUE TITLE
Missing symlink for `dartaotruntime` on Linux

### ISSUE THREAD

**Issue by nns52k** [dart-lang/sdk#52397]
Sorry, I don't know if this is the right place to report the problem.

The version of Dart SDK I'm using is 3.0.0. It doesn't create symlink in PATH folder for `dartaotruntime`. I saw other people complain about this too. So, can we have this fixed in future version of Dart SDK? Thanks.

**Comment by athomas** [comment]
How are you getting the Dart SDK? Is that through the debian packages or some other mechanism (so that I can be sure that a fix would actually help you)?

Where did you see others complain (so I can be sure they are facing the same problem)?
