### ISSUE TITLE
build fails with sprintf deprecation error/warning

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#52407]
I'm on 6250eeca95036d13861241eb91bd327ab7b6f42f

```
Darwin erics-mbp.lan 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64

eseidel@erics-mbp sdk % xcodebuild -version
Xcode 14.3
Build version 14E222b
```

`./tools/build.py --no-goma --mode release --arch arm64 create_sdk` succeeded, but

`./tools/build.py --no-goma --mode release --arch arm64` failed:

```
[4016/4235] CXX obj/third_party/protobuf/src/google/protobuf/stubs/libprotobuf_lite.strutil.o
FAILED: obj/third_party/protobuf/src/google/protobuf/stubs/libprotobuf_lite.strutil.o 
../../buildtools/mac-arm64/clang/bin/clang++ -MMD -MF obj/third_party/protobuf/src/google/protobuf/stubs/libprotobuf_lite.strutil.o.d -DTOOLCHAIN_VERSION=_UIQ8cNFm3XrHcaC2nF0B_sgwaXJY5vFKIMN-2jngXgC -DNDEBUG -DGOOGLE_PROTOBUF_NO_RTTI -DHAVE_PTHREAD -I../.. -Igen -I../../third_party/protobuf/src -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.14  -arch arm64 -fPIE -fcolor-diagnostics -Wall -Wextra -Werror -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wno-tautological-constant-compare -Wno-unused-but-set-variable -Wno-deprecated-non-prototype -Wpartial-availability -fdebug-prefix-map=/Users/eseidel/Documents/GitHub/dart-sdk/sdk=../.. -no-canonical-prefixes -Wheader-hygiene -Wstring-conversion -O2 -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Wno-deprecated-pragma -Wno-enum-enum-conversion -Wno-extra-semi -Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-invalid-noreturn -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-function -Wno-unused-private-field -Wno-c++98-compat-extra-semi -Wno-shorten-64-to-32 -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++17 -fno-rtti -c ../../third_party/protobuf/src/google/protobuf/stubs/strutil.cc -o obj/third_party/protobuf/src/google/protobuf/stubs/libprotobuf_lite.strutil.o
../../third_party/protobuf/src/google/protobuf/stubs/strutil.cc:506:11: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
          sprintf(dest + used, (use_hex ? "\\x%02x" : "\\%03o"),
          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
```

**Comment by eseidel** [comment]
Unfortunately it means it's not possible to run tests, since AFAICT, `create_sdk` isn't enough to run tests (or the `dart` command successfully) from the out directory, it seems to need a full build.

**Comment by eseidel** [comment]
I suspect the right (temporary) fix is to add --no-deprecated-declarations to the protobuf warnings list in gn, since I suspect it will be a while before protobuf notices (since iirc Google uses a controlled version of XCode rather than latest release) and fixes.  I'll work up a patch.

**Comment by a-siva** [comment]
//cc @derekxu16 seems to be related this TODO that you mention in `runtime/vm/protos/tools/compile_perfetto_protos.dart`

```
  if (!Platform.isLinux) {
    // TODO(derekx): The compilation of protoc fails on MacOS due to the error
    // "'sprintf' is deprecated". When bumping protobuf, check if this problem
    // has been resolved.
    print('Error: this tool can only be run on Linux because protoc has '
        'compatibility issues on other platforms.');
    return; 
  }

```

**Comment by derekxu16** [comment]
> //cc @derekxu16 seems to be related this TODO that you mention in `runtime/vm/protos/tools/compile_perfetto_protos.dart`

Yeah, this is the same issue. The `protoc` targets will unfortunately get built when `./tools/build.py --no-goma --mode release --arch arm64 all` is run (equivalent to `./tools/build.py --no-goma --mode release --arch arm64`), because they are part of the build graph. I believe that `./tools/build.py --no-goma --mode release --arch arm64 most` will allow you to run tests, but a patch would be even better!

**Comment by eseidel** [comment]
> > //cc @derekxu16 seems to be related this TODO that you mention in `runtime/vm/protos/tools/compile_perfetto_protos.dart`
> 
> Yeah, this is the same issue. The `protoc` targets will unfortunately get built when `./tools/build.py --no-goma --mode release --arch arm64 all` is run (equivalent to `./tools/build.py --no-goma --mode release --arch arm64`), because they are part of the build graph. I believe that `./tools/build.py --no-goma --mode release --arch arm64 most` will allow you to run tests, but a patch would be even better!

I was just following https://github.com/dart-lang/sdk/wiki/Building#testing, which told me to build all in order to run tests (after I tried just using the results of create_sdk, which it says earlier in those instructions, and they failed, both at running `dart` and running the tests.)

**Comment by eseidel** [comment]
OK, have a patch, about to post.  It gets further, but then dies in: https://github.com/dart-lang/sdk/issues/52418

**Comment by eseidel** [comment]
https://dart-review.googlesource.com/c/sdk/+/303861

**Comment by eseidel** [comment]
Fixing with https://fuchsia-review.googlesource.com/c/protobuf-gn/+/857898 instead.

**Comment by eseidel** [comment]
And now to roll deps: https://dart-review.googlesource.com/c/sdk/+/304146

**Comment by dnfield** [comment]
Could we patch protobuf to use snprintf?

**Comment by eseidel** [comment]
I suspect that is the correct resolution, yes. 👍  I'm very doubtful of my own ability to navigate the protobuf contribution process.  My understanding is it's developed in Google3.  🙃   I was mostly just trying to get the Dart contribution instructions to work (e.g. the build to work). 😭

**Comment by eseidel** [comment]
Not to cut short the conversation with Dan, but this is fixed as described, so closing.
