### ISSUE TITLE
[analyzer] Report unreachable code?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#52409]
Consider the following program:

```dart
class C {
  Never get never => throw 0;
}

void main() {
  switch (C()) {
    case C(never: int _):
      print('Unreachable!');
  }
}
```

This program does not give rise to any diagnostic messages from the analyzer (version Dart SDK 3.1.0-72.0.dev). Would it be possible to report that the body of the specified case is unreachable code, because the control flow must have been at the point where a getter with return type `Never` has been invoked?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/303840

**Comment by eernstg** [comment]
Wow, that was quick! :tada:
