### ISSUE TITLE
[analyzer] Inline class member applicability ("inheritance") seems to be ignored

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#52405]
I know the implementation of inline classes isn't complete, but I'll report this issue such that it is known that it exists.

Consider the following program:

```dart
inline class A {
  final num n;
  A(this.n);
  num get aMember => n;
}

inline class B implements A {
  final int i;
  B(this.i);
}

void main() {
  var b = B(10);
  print(b.aMember);
  A a = b;
  print(a.aMember);
}
```

Using `dart` (from 0767670779471e5c4862d76ab4065f94044544d9), this program compiles and runs. However, the analyzer (same commit) rejects the program with the following error message:

```
  error • n014.dart:7:14 • Missing concrete implementations of 'getter
          A.aMember' and 'getter A.n'. Try implementing the missing methods,
          or make the class abstract. •
          non_abstract_class_inherits_abstract_member
```

This seems to imply that the "inheritance" mechanism in inline classes isn't handled by the analyzer. In fact, each instance member in an inline class works in a way which is similar to an extension method, in the sense that it can be invoked with a receiver whose static type is that inline class or any non-bottom subtype thereof.

That is, an inline class "inherits" instance members from every inline class in its `implements` clause, except when it contains a declaration of that name.

In the example, a receiver of type `B` can invoke `aMember` and `n`, because it implements `A`. The signature of such "inherited" members is taken from the direct superinterface that provides or "inherits" a declaration, if there is exactly one such superinterface.

If there are two or more direct superinterfaces whose interface contains an instance member with the given name, and it isn't ultimately "inherited from" the same declaration, it is an error, unless that member name is redeclared:

```dart
inline class A1 { final int i; A1(this.i); void m() {}}
inline class A2 { final int i; A2(this.i); void m() {}}
inline class B implements A1, A2 {} // Error, `m` is ambiguous.
inline class C implements A1, A2 { int get m => 1;} // OK, and no override constraints.

inline class A { final int i; A(this.i); void m() {}}
inline class B1 implements A { final int i; B1(this.i); }
inline class B2 implements A { final int i; B2(this.j); }
inline class D implements B1, B2 {} // OK, declaration of `m` is uniquely determined.
```

**Comment by srawlins** [comment]
CC @scheglov in case this was implemented in the last few months.

**Comment by scheglov** [comment]
This code has no errors in the analyzer now.
```dart
extension type A(num n) {
  num get aMember => n;
}

extension type B(int i) implements A {}

void main() {
  var b = B(10);
  print(b.aMember);
  A a = b;
  print(a.aMember);
}
```
