### ISSUE TITLE
`reinstall dart` to upgrade?

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/sdk#52417]
I'm confused by the instruction under macOS > [Upgrading](https://github.com/dart-lang/sdk/wiki/Installing-beta-and-dev-releases-with-brew,-choco,-and-apt-get#upgrading) in the wiki:

> ```
> # On the stable channel
> $ brew upgrade dart # replace dart with dart-beta if you are on the beta channel.
> 
> # On the dev channel
> $ brew reinstall dart
> ```

I just used `brew upgrade` alone on the dev channel, and it did in fact upgrade. Why run `brew reinstall`? 
(The [Get Dart](https://dart.dev/get-dart) page only mentions `brew upgrade dart`, but I'm assuming that's because it's referring to the stable channel only?)

@khanhnwin fyi

**Comment by athomas** [comment]
> it did in fact upgrade

It might have been by accident. According to the documentation brew update only works when there is a new stable. Reinstall at some point was the most reliable way to upgrade the dev channel on homebrew. There may be better ways now. One that might work reliably is `brew upgrade --fetch-HEAD`.

The point of the instructions is to give a reliable way from an installed dev version to a newer dev version even when there are no stable releases in between.

**Comment by MaryaBelanger** [comment]
> brew update only works when there is a new stable

I think this happened when I was going from 3.0 beta to stable, so that answers it. Thanks!
