### ISSUE TITLE
[analyzer] analyzer reports _numCids unused even though it's used in _readClasses

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#52420]
This is on 91091f39a549f4565cb20be1546a98dfbce4b21a.

With `Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "macos_arm64"`

Analyzing `runtime/observatory_2/lib/object_graph.dart`

[{
	"resource": "/Users/eseidel/Documents/GitHub/dart-sdk/sdk/runtime/observatory_2/lib/object_graph.dart",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "unused_field",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unused_field",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 4,
	"message": "The value of the field '_numCids' isn't used.\nTry removing the field, or using it.",
	"source": "dart",
	"startLineNumber": 859,
	"startColumn": 7,
	"endLineNumber": 859,
	"endColumn": 15
}]

**Comment by eseidel** [comment]
Happened again on this line:

https://github.com/dart-lang/sdk/blob/91091f39a549f4565cb20be1546a98dfbce4b21a/runtime/observatory_2/lib/src/elements/process_snapshot.dart#L52

[{
	"resource": "/Users/eseidel/Documents/GitHub/dart-sdk/sdk/runtime/observatory_2/lib/src/elements/process_snapshot.dart",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "unused_field",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unused_field",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 4,
	"message": "The value of the field '_snapshotB' isn't used.\nTry removing the field, or using it.",
	"source": "dart",
	"startLineNumber": 53,
	"startColumn": 7,
	"endLineNumber": 53,
	"endColumn": 17
}]

**Comment by scheglov** [comment]
It looks to me that both `_SnapshotGraph._numCids` and `ProcessSnapshotElement._snapshotB` are written, but never read.
<img width="494" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/4b872f33-88c8-4049-b8b5-d2d7a4de71e5">
Do I miss something?

**Comment by eseidel** [comment]
My bad.  Will remove them.

**Comment by eseidel** [comment]
Waiting for https://dart-review.googlesource.com/c/sdk/+/304106 to land and then can send you a change to fix.

**Comment by eseidel** [comment]
I've decided it's not worth trying to fix the observatory_2 directory.  I tried running the "service" tests locally and after 10 mins of fans got multiple crashes and failures and decided this is not worth fighting with as an outside contributor.  Thanks for the look!
