### ISSUE TITLE
Avoid thrown/caught exceptions when using HttpClient.openUrl (and related methods) with hostnames

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52423]
In a recent change (d884d1a76e47e45c5b34b376575b10e236ebeb0a) to fix #50868, there are calls to `_InternetAddress.fromString()` that will throw (and then catch) `ArgumentError` whenever the URI contains a hostname and not an IP address.

This is not itself a bug/problem and everything works as expected. However, a lot of users are running with "break on all exceptions" ticked in VS Code and breaking here is causing some confusion. I've [explained the issue here](https://github.com/flutter/flutter/issues/126650#issuecomment-1547909038) although that's not very visible unless you read the entire thread.

I think that issue should probably be closed (because as far as I can tell everything is working as expected), but since fetching URLs using hostnames is very common I thought it was worth seeing if that code could be altered to not rely on throwing/catching for this flow. While I think users shouldn't generally run with "Break on all exceptions" enabled (the default is "Break on uncaught exceptions"), the less "noise" there is when running in that mode, the easier it'll be to track down actual issues caused by unexpected exceptions being thrown and caught.

**Comment by Hassanmrwt** [comment]
I am facing the same kind of issue, please seek it out on time. 
I have explained my problems in this video 👇👇👇👇👇
https://youtu.be/lRtrcG_Sz8U

**Comment by brianquinlan** [comment]
A fix is in place. I'll go through the cherrypick process tomorrow.
