### ISSUE TITLE
Building wasm with html/js libary

### ISSUE THREAD

**Issue by feduke-nukem** [dart-lang/sdk#52437]
* dart2js

* Dart SDK Version: 3.1.0-118.0.dev
* MacOSX
* Chrome

If I try to build web with `--wasm` argument I am getting `html/js` library import errors:

<img width="810" alt="image" src="https://github.com/dart-lang/sdk/assets/72284940/e39ef58c-995d-447c-8cfb-8cebaf43e64d">
<img width="314" alt="image" src="https://github.com/dart-lang/sdk/assets/72284940/66f0b415-fc62-4d17-ad5b-8e14089b7e14">

it is related to: 
<img width="942" alt="image" src="https://github.com/dart-lang/sdk/assets/72284940/754542ba-4122-42d3-a707-aa4de4b86bc3">

Will it be usable in the future?

**Comment by sigmundch** [comment]
Thanks for the question!

The plan is to support access to browser and JS APIs, but it wont be through the existing `dart:html` library and legacy `package:js` APIs.

We will allow JSInterop via the new `dart:js_interop` (still under development) and access to browser APIs via JSInterop. For example, through packages like `package:web` (also under development). The new `dart:js_interop` temporarily supports using a style similar to `package:js` with `@staticInterop`, but will soon evolve to use a better syntax (hopefully base on the experimental `inline classes` language feature). The new packages that use JSInterop to acesss browser APIs are likely to have some differences with `dart:html`, but the hope is that they are similar enough that switching over to use them will not be a big ordeal.

/cc @joshualitt @srujzs

**Comment by srujzs** [comment]
If you do want to use some of the existing tools under development, here are some pointers:

`@staticInterop` (note that you should import `dart:js_interop` to import this on dart2wasm and not `package:js`): https://pub.dev/packages/js#static-interop and https://pub.dev/packages/js#staticinterop

`package:web` (which is very much in beta and subject to change): https://github.com/dart-lang/web

**Comment by feduke-nukem** [comment]
> If you do want to use some of the existing tools under development, here are some pointers:
> 
> `@staticInterop` (note that you should import `dart:js_interop` to import this on dart2wasm and not `package:js`): https://pub.dev/packages/js#static-interop and https://pub.dev/packages/js#staticinterop
> 
> `package:web` (which is very much in beta and subject to change): https://github.com/dart-lang/web

Thank you very much!
