### ISSUE TITLE
`Map<TKey, TValue>` should inherit from `Iterable<MapEntry<TKey, TValue>>`

### ISSUE THREAD

**Issue by ahmednfwela** [dart-lang/sdk#52435]
Moved from https://github.com/dart-lang/language/issues/3081

currently to iterate over a `Map`, you need to access the `entries` property, but you can't iterate over the map itself

this makes representing a union of `Map | List`  a chore, since they have no common denominator, thus requiring changing the type to `dynamic`

**Comment by lrhn** [comment]
A map is not, will not, and cannot be an `Iterable.`

While some members can co-exist (`Map` has `containsKey`/`containsValue` and `Iterable` has `contains`), 
the method `forEach` has incompatible types between the two interfaces. 

So, it cannot be.

**Comment by ahmednfwela** [comment]
@lrhn why not ? C# has IDicitionary inheriting from IEnumerable just fine

**Comment by lrhn** [comment]
In C#, a class can have two members with the same name, but different signatures.
I'm Dart that's not possible.
The `forEach` of the `Map` interface makes it impossible to implement `Iterable` too.

**Comment by ahmednfwela** [comment]
oh I see, so it's just blocked by https://github.com/dart-lang/language/issues/1122

**Comment by lrhn** [comment]
Yes, "just" blocked on that. :grin:
