### ISSUE TITLE
[breaking change] Make `dart:io` `Platform` `abstract`

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#52444]
### Change Intent

Add the `abstract` class modifier to the `dart:io` [`Platform`](https://api.dart.dev/be/180361/dart-io/Platform-class.html) class.

### Justification

[`Platform`](https://api.dart.dev/be/180361/dart-io/Platform-class.html) only has `static` properties so there is no reason to make instances of it.

### Impact

All code that constructs `Platform` (i.e. `Platform()`) will break. There is one known pattern where this is done: `package:dcli` implements a non-static extension on `Platform` to allow users to get the line ending for the platform i.e.

```dart
Platform().eol;
```
 

### Mitigation

In Dart 3.1:
- The constructor for `Platform` is deprecated.
- `Platform` contains a `lineTerminator` property that obviates the need for the extension in `package:dcli`.

Before we mark `Platform` as `abstract`, I will remove the `extension` from `package:dcli` and give users some time to update their dependencies. Making the change in Dart 3.2 would give users an approximately 6 week period to update their dependencies and code.

**Comment by kevmoo** [comment]
SGTM – although deferring to @mit-mit

**Comment by mit-mit** [comment]
I'm a bit confused about the timeline as the Mitigation section mentions both 3.1 and 3.2. Can you clarify @brianquinlan ?

**Comment by itsjustkevin** [comment]
@vsmenon @Hixie and @grouma another breaking change for your review.

**Comment by grouma** [comment]
As far as I can tell this doesn't impact ACX or our customers. Can we run a global presubmit to validate?

**Comment by brianquinlan** [comment]
> I'm a bit confused about the timeline as the Mitigation section mentions both 3.1 and 3.2. Can you clarify @brianquinlan ?

I was hoping to deprecate the `Platform` constructor in Dart 3.1
I was hoping to make `Platform` `abstract` in Dart 3.2

But @timsneath suggested that Dart 3.2 is too aggressive so we can push that out to... when? I don't know what our policy is here.

**Comment by vsmenon** [comment]
lgtm - let's go forward with marking deprecated

If we're conservative, we'd give a year.  We can decide whether we want to pull that forward.

**Comment by itsjustkevin** [comment]
@vsmenon I would like to mark this as approved, but am still waiting for feedback from @Hixie and some assurance through a global presubmit for @grouma.

**Comment by itsjustkevin** [comment]
Pinging @grouma and @Hixie

**Comment by Hixie** [comment]
We generally seem to use `abstract final class` in the Flutter framework for such "namespace" classes.
But either way, fine by me.
I wish we could move Platform out of dart:io and dart:html and into dart:core so that it works the same everywhere, though.

**Comment by itsjustkevin** [comment]
@brianquinlan I would like to mark this as approved, could you respond the question by @grouma above so we can clear this up?

**Comment by brianquinlan** [comment]
I'm fine waiting a year to actually do the removal. We did the deprecation in Dart 3.1.0 (released August 16, 2024) so I'll make a note to remove this around August 2024

> As far as I can tell this doesn't impact ACX or our customers. Can we run a global presubmit to validate?

We can consider that in a year - but hopefully by then people will have reacted to the deprecation ;-)
