### ISSUE TITLE
Can we make invoking `build.py` with no targets run `ninja -C out/dir` instead of `ninja -C out/dir all`?

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#52442]
In other words, can we delete these two lines from `build.py`? https://github.com/dart-lang/sdk/blob/0bff5652bacee77f6b58923e6ed47b6e294adaa8/tools/build.py#L243-L244

The reason I would like to delete them is because of the following GN behaviour:

"Note that getting targets defined in Ninja files is at the granularity of BUILD.gn files, though the dependency graph from default or any other target is at the granularity of an individual target. So having some target in the BUILD.gn file in the graph from default makes all targets in that file (and toolchain, see below) available as targets on the Ninja command line even though they are not built by default." (From https://fuchsia.dev/fuchsia-src/development/build/build_system/intro#dependency_graph_and_buildgn_files)

Here is an example of `ninja -C out/dir all` causing problems for us: https://github.com/dart-lang/sdk/issues/52407.

[`runtime/vm:perfetto_protos_protozero` and `runtime/vm:perfetto_protos_dart`](https://github.com/dart-lang/sdk/blob/0bff5652bacee77f6b58923e6ed47b6e294adaa8/runtime/vm/BUILD.gn#L127-L145) are not dependencies of any other GN targets, but they get discovered due to the GN behaviour above, and thus get built by `ninja -C out/dir all`. In this case the problem was easy to patch, but I think `ninja -C out/dir all` is fragile. `build.py -mrelease -ax64` on Linux has over 8000 build steps, and it's highly probable that many of them build objects that aren't used by any Dart targets.

To make running `build.py` with no targets maintain the same pratical effect, we would also need to list every Dart target as dependencies of the top-level `default` target: https://github.com/dart-lang/sdk/blob/cc8b3f792eb245cfdcc7c6dce76f2eaf18061d18/BUILD.gn#L11

**Comment by athomas** [comment]
SGTM

@rmacnak-google any opinions?

**Comment by rmacnak-google** [comment]
SGTM. build.py is more predictable if it forwards targets to ninja unchanged.

**Comment by derekxu16** [comment]
I just updated the wiki page about building to account for this change. Let me know if I missed anything.

https://github.com/dart-lang/sdk/wiki/Building/_compare/cda82d0ca9227416de51276cfe7605f091267da5...386604d8c0ebf753b7d1d63b5bd79cc3b8a83be4
