### ISSUE TITLE
[CP] Fix Dart2JS type inference for record accesses on invalid indices.

### ISSUE THREAD

**Issue by biggs0125** [dart-lang/sdk#52443]
### Commit(s) to merge

327a680c349d0da6f6b9cbd9052cb1a100b9531f

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/304420

### Issue Description

https://github.com/dart-lang/sdk/issues/52438

Dart2JS type inference crashes when a record field is accessed but the receiver type does not contain that field.

Users cannot manually generate code like that but code generated by switches can. Specifically when a record is demoted to dynamic/Object and then cased on in a switch with non-matching cases. The generated code from such a switch can contain record accesses that cause these crashes.

### What is the fix

The fix is for each record access to check that the type of the receiver supports the selector being used. 

### Why cherry-pick

This causes crashes in Dart2JS on fairly trivial code. Multiple developers have discovered this bug.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52438

**Comment by sigmundch** [comment]
I'm very much in support of this cherry-pick - I think this has potential to surface often and the fix is very low risk.

**Comment by sigmundch** [comment]
(reopening so that the issue is seen by engprod when they create the release candidate, they can close when they confirm it was shipped in 3.0.2)
