### ISSUE TITLE
[analyzer] Relational pattern expression must be a constant

### ISSUE THREAD

**Issue by AlexVegner** [dart-lang/sdk#52453]
Unexpected error appear: 
The relational pattern expression must be a constant. Try using a constant instead
Time to time appear when I create a new files or edit a file name. 

<details>
  <summary>Steps to reproduce:</summary>

1. Open project sample project in vscode
https://github.com/AlexVegner/relational_pattern_issue
2. Create a new dart file
3. Change the file name

Actual: 
Unexpected error appear: The relational pattern expression must be a constant
</details>

#### This tracker is for issues related to:
* Analyzer
* Vscode flutter/dart plugins (perhaps)

#### Code:
```dart
     final token = switch (peek) {
      // ...
      (>= $a && <= $z) ||
      (>= $A && <= $Z) ||
      (>= $0 && <= $9) =>
       scanString(start),
      // ...
```

Sample code: (lexer)
https://github.com/AlexVegner/relational_pattern_issue/blob/main/lib/lexer.dart#L47

<details>
  <summary>flutter analyze</summary>

```
Analyzing relational_pattern_issue...                                   

  error • The relational pattern expression must be a constant • lib/lexer.dart:47:11 •
         non_constant_relational_pattern_expression
  error • The relational pattern expression must be a constant • lib/lexer.dart:47:20 •
         non_constant_relational_pattern_expression
  error • The relational pattern expression must be a constant • lib/lexer.dart:48:11 •
         non_constant_relational_pattern_expression
  error • The relational pattern expression must be a constant • lib/lexer.dart:48:20 •
         non_constant_relational_pattern_expression
  error • The relational pattern expression must be a constant • lib/lexer.dart:49:11 •
         non_constant_relational_pattern_expression
  error • The relational pattern expression must be a constant • lib/lexer.dart:49:20 •
         non_constant_relational_pattern_expression
```
</details>

<details>
  <summary>flutter doctor:</summary>

```
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources
```
</details>

<details>
  <summary>dart --version</summary>
  
  ```
  Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "macos_arm64"
  ```
 </details>

####  Workarounds: 
- Edit lexer.dart and save it. (the error will disappear. But it will appear again when I will create a new file or change a file name)
- Or move all chart constants from charts.dart to lexer.dart (It will resolve the issue)

#### Note: 
Reproducible with flutter and pure dart projects

**Comment by srawlins** [comment]
Thanks for filing an issue, @AlexVegner. A minimal repro (

```dart
const $a = 1;
const $z = 1;
const $A = 1;
const $Z = 1;
const $0 = 1;
const $9 = 1;

void main() {
  final start = 1;
  final peek = 1;

  final token = switch (peek) {
    (>= $a && <= $z) ||
    (>= $A && <= $Z) ||
    (>= $0 && <= $9) =>
      scanString(start),
    _ => 7,
  };
}

int scanString(int start) => 7;
```
)

properly shows no errors for me, in DartPad and with `flutter analyze`.

I could not reproduce with your steps:

1. clone and `flutter pub get` the 'relational_pattern_issue' repo.
2. Open `relational_pattern_issue` in VS Code.
3. Create a new file, `x.dart`.
4. Rename the file to `y.dart`.

No errors related to `lexer.dart` appeared. Are there other conditions perhaps that are needed?

**Comment by ds84182** [comment]
This only happens when using the charcode package, and is most likely related to the number of constants within the file. I think it's mixing up `PropertyAccessorElementImpl_ImplicitGetter` and `ConstTopLevelVariableElementImpl` as they're present for each constant in the file.

**Comment by scheglov** [comment]
I can reproduce it.
```dart
  solo_test_X() async {
    newFile('$testPackageLibPath/a.dart', r'''
const int a = 0x61;
''');

    await assertErrorsInCode(r'''
import 'a.dart';

void f(int x) {
  switch (x) {
    case >= a:
  }
}
''', [
      error(CompileTimeErrorCode.NON_CONSTANT_RELATIONAL_PATTERN_EXPRESSION, 61,
          1),
    ]);

    final node = findNode.singleListLiteral;
    assertResolvedNodeText(node, r'''
''');
  }
```

**Comment by AlexVegner** [comment]
Hi @srawlins, 

Sorry for late response. 
Your minimal project has all in one file. 
I reproduce the issue only when constant and pattern expression located in different files. 
You can try sample project to reproduce it. 
https://github.com/AlexVegner/relational_pattern_issue/blob/main/lib/lexer.dart#L47

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/306681
