### ISSUE TITLE
[CP] fix @unusedResult support for Records, switch expressions and when clauses

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#52451]
### Commit(s) to merge

b0b393773fa7d7965c6c9ea3a501e93dc60812f9, 0cfb3611d42702e1485953354a02743668414f2a

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/304560

### Issue Description

The `@unusedResult` annotation is over-reporting in record literals, when clauses and switch expressions on STABLE. 

### What is the fix

The unused result verifier just needed to know about records, when clauses  and switch expressions.

### Why cherry-pick

We're producing spurious diagnostics for folks using Dart 3 and `@unusedResult`.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52314, https://github.com/dart-lang/sdk/issues/52391

**Comment by itsjustkevin** [comment]
@srawlins can you take an initial look here?

**Comment by srawlins** [comment]
There is a workaround for https://github.com/dart-lang/sdk/issues/52314, right, to use `// ignore`?

There is no issue associated with https://github.com/dart-lang/sdk/commit/0cfb3611d42702e1485953354a02743668414f2a, but I imagine that can also be worked around with `// ignore`?

**Comment by pq** [comment]
Yep, true. These spurious warnings can be `// ignore`d.

**Comment by srawlins** [comment]
It sounds like this is perhaps not worth the cherry-pick? Since there is a simple work-around, and I am not aware that `@useResult` is widely used. WDYT?

**Comment by pq** [comment]
I don't feel super strongly. I think the change is pretty safe but it's always a risk. Happy to defer to 3.1.  Your call.

**Comment by itsjustkevin** [comment]
@pq are you okay to close this cherry-pick request?

**Comment by pq** [comment]
Sure thing.

**Comment by renggli** [comment]
Unfortunately the absence of this fix in Dart 3.0.5 prevents me from releasing a new version of [petitparser](https://pub.dev/packages/petitparser). I get hundreds of warnings within and across users of the library.
