### ISSUE TITLE
 Code Running Problem After Upgrade Dart 3.0.1 in Windows

### ISSUE THREAD

**Issue by siraajul** [dart-lang/sdk#52460]
After Upgrading in Dart 3.0.1

Whenever i try to run any code on my IDE it shows error ! 

`Crash when compiling file:///C:/Users/HomePC/Desktop/Dart/Module_04/Live%20Class/exception_handling.dart:
Unexpected Kernel SDK Version 7a6514d137 (expected 1618a77599).

#0      BinaryBuilder._readAndVerifySdkHash (package:kernel/binary/ast_from_binary.dart:657:7)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:689:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:166:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:673:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:480:10)
#5      ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:426:13)
<asynchronous suspension>
#6      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:79:31)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#8      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#9      generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#10     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#11     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#12     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#13     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>

Process finished with exit code 252`

**Comment by jacob314** [comment]
Removing area-intellij as this is an issue with loading kernel files not IntelliJ.

**Comment by ali-1989** [comment]
I have this problem!

**Comment by johnniwinther** [comment]
cc @jensjoha

**Comment by jensjoha** [comment]
The initial issue is many months old and I assume the reporter is no longer having this problem.

The two hashes in the error message is from 3.0.0 and 3.0.1, so I'll guess that the update didn't go well. It being Windows I'm guessing the file was in use and wasn't actually properly unpacked or something. But I'm guessing.

The comment from September, being quite a bit newer, probably isn't the same 3.0.0 vs 3.0.1 thing (so should probably have been a separate issue) -- but without further information I'm guessing it's the same issue (i.e. some install/update not going as it should).

As such I'll close this issue.
