### ISSUE TITLE
Patterns parser assert failure

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#52462]
The following (invalid as I understand it) code crashes the parser with an assert error (it seems to "work fine" without asserts):

```dart
var ((a1,)?,)? = null;
```

/cc @stereotype441

**Comment by jensjoha** [comment]
Hmm. It crashes the same way on `var ((a1,)?,) = ((-1,),);` when parsing without pattern support, so not really pattern-related anyway. I think we should just remove the assert, and I'll go ahead and do that. Sorry for the noise.

**Comment by stereotype441** [comment]
Let's go ahead and keep the issue open until the problem is fixed, and then when the fix lands we can close it with a pointer to the commit that fixes it.

**Comment by stereotype441** [comment]
Fixed in 284296f8628a56d22ec44f75a7220e6cbd5b466e.
