### ISSUE TITLE
[CP] Disable graph intrinsics for implicit getters with unboxed record return values

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#52467]
### Commit(s) to merge

86c18251b462a68b64a00e14fb39e292441193ff

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/304760

### Issue Description

AOT compiler crashed when generating an intrinsic for implicit getter returning an unboxed record. The implicit getter is needed only if it is polymorphic and not inlined.

### What is the fix

Generation of intrinsics for implicit getters are disabled when the return value is an unboxed record.

### Why cherry-pick

There are no easy workarounds for users.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52449

**Comment by mraleph** [comment]
CP looks good: the fix is trivial. I support.
