### ISSUE TITLE
Failures on Update _fe_analyzer_shared to require Dart SDK version 3.0.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52474]
There are new test failures on [Update _fe_analyzer_shared to require Dart SDK version 3.0.](https://dart-review.googlesource.com/c/sdk/+/291141).

The tests
```
pkg/front_end/test/compile_dart2js_with_no_sdk_test RuntimeError (expected Pass)
pkg/front_end/test/macros/application/macro_application_test RuntimeError (expected Pass)
pkg/front_end/test/macros/declaration/macro_declaration_test RuntimeError (expected Pass)
pkg/front_end/test/macros/macro_api_test RuntimeError (expected Pass)
```
are failing on configurations
```
cfe-unittest-asserts-release-linux
```

**Comment by stereotype441** [comment]
@johnniwinther any idea what's going on here? It looks like the CFE's getting confused and failing to pick up the proper language version when compiling macros.

**Comment by johnniwinther** [comment]
The problem is that the tests use a custom `package_config.json` to create a `macro_api_test` package. This is located in `pkg/_fe_analyzer_shared/test/macros/api/package_config.json`. It currently specifies the `_fe_analyzer_shared` version to be `2.17` but this can now be removed instead of specifying a specific version.

**Comment by stereotype441** [comment]
> The problem is that the tests use a custom `package_config.json` to create a `macro_api_test` package. This is located in `pkg/_fe_analyzer_shared/test/macros/api/package_config.json`. It currently specifies the `_fe_analyzer_shared` version to be `2.17` but this can now be removed instead of specifying a specific version.

Thanks, Johnni! That took care of all but one failure. The one remaining failure looks like a bug in the interaction between macros and exhaustiveness checking (it appears that `constantToEnumValue` returns `null` during macro execution). That's definitely an issue we should fix before shipping the "macros" feature, but IMHO it shouldn't block us from upgrading `_fe_analyzer_shared` to language version 3.0. So I'm going to go ahead and mark the test as a known failure and send the change out for review.
