### ISSUE TITLE
`LinterContext.resolveNameInScope` not properly resolving Object pattern vars

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#52486]
See: https://github.com/dart-lang/linter/issues/4381

Simple repro from `unnecessary_this` which doesn't notice that the `value` var is shadowing.

```dart
class C {
  Object? value;

  bool equals(Object other) =>
      switch (other) { C(:var value) => this.value == value, _ => false };
}
```

/fyi @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/305060
