### ISSUE TITLE
Dart FFI : What is the equivalent of  ffi.Pointer<ffi.Pointer<Utf8>> in Dart

### ISSUE THREAD

**Issue by ps-sujith** [dart-lang/sdk#52499]
HI Devs

I am trying to integrate a C library to a Dart FFI plugin  which is completed successfully . But i have an issue connecting the dart types to C native types 

Scenario:

I have an API  return in C which accepts a " char **" and when the API is get a response it send back the response to the  caller using the same pointer we passed as the parameter
the code snippets as follows
### C
`int get_user_details(char **response);`

### generated.dart
`int get_user_details(
    ffi.Pointer<ffi.Pointer<ffi.Char>> response,
  )`
 `{
    return _get_user_details(
      response,
    );
  }`

`late final _get_user_detailsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('get_user_details');`
  `late final _get_user_details = _get_user_detailsPtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>();`

### Dart
From dart  not sure what data type i need to use to call  `_binding.get_user_details(//unknown type)`

i have checked @ganeshrvel 's issue #https://github.com/dart-lang/sdk/issues/43403  seems not working for me

PS: we had this c library integrated for native android where we pass` _binding.get_user_details(StringBuilder())` .So i tired with the StringBuilder equivalent for dart StringBuffer which is also not working

I get the response as Success 'int' . but since i pass the wrong type of parameter , the C cant send me back the success/error response

Kindly help

**Comment by mraleph** [comment]
Issue tracker exists for filing bug reports. I recommend using other channels (listed on https://dart.dev/community and https://flutter.dev/community) to ask help. 

There is no direct equivalent of `ffi.Pointer<ffi.Pointer<Utf8>>` in Dart. You need to allocate enough space for the pointer - call your function, then take the result and use it. Something like this:

```dart
import 'package:ffi/ffi.dart';

final result = using((arena) {
  final ptr_ptr = area.allocate<ffi.Pointer<Char>>(sizeOf<ffi.Pointer<Char>>());
  final retval = get_user_details(ptr_ptr);
  return ptr_ptr.value.cast<Utf8>().toDartString();
});
```

**Comment by ps-sujith** [comment]
i have tried this solution which is working fine but the `result_ptr.value.cast<Utf8>().toDartString()` is giving half part of the result.is this the pointer memmory allocation issue? any suggestion

`  Pointer<Pointer<Utf8>> result_ptr = calloc();`
 ` int result= _bindings.get_user_details(result_ptr);`
 ` if(result == 0){`
    `print("success  >> ${result_ptr.value.cast<Utf8>().toDartString()}");`
  `}else{`
  `  print("Error  >> ");`
`  }`
 ` calloc.free(result_ptr);``

**Comment by mraleph** [comment]
@ps-sujith well, is your string a well-formed null-terminated utf8? (is it maybe utf16 or something else?). are you entirely sure that C library is correct? maybe output itself is truncated (if it is long enough - print the length of the string rather than the full string).

**Comment by ps-sujith** [comment]
@mraleph  C library is correct since the same was implemented for android native using java+JNI

when coming to dart i printed the length  it showing : 154295

on the c side it was char **response ,but i defined the type as ffi.Pointer<ffi.Pointer<Utf8>> instead of ffi.Pointer<ffi.Pointer<ffi.char>>

utf8/utf16 still not sure for me. Any suggestion on this considering the length of the response?

**Comment by mraleph** [comment]
> when coming to dart i printed the length it showing : 154295

So is this full length or partial length?

**Comment by ps-sujith** [comment]
its full length.

**Comment by ps-sujith** [comment]
@mraleph  you are right. its not printing the entire results even though  the result contains all.

Adopting your solution.

Thanks for your help , saved my day. Thanks
