### ISSUE TITLE
Both Content-Length and Transfer-Encoding are specified, at most one is allowed

### ISSUE THREAD

**Issue by Carseason** [dart-lang/sdk#52494]
Is there an option to ignore this exception?
Or the sdk can ignore one of them?

**Comment by Carseason** [comment]
My server is on openwrt, and he forwards it through luci.
luci will automatically handle header, resulting in the existence of Transfer-Encoding,
dart to flutter app exception occurs

**Comment by a-siva** [comment]
The change to flag an error when both content-length and transfer-encoding are specified was done here https://dart-review.googlesource.com/c/sdk/+/180485 in response to a security vulnerability. Please see section 6.1 in https://www.rfc-editor.org/rfc/rfc9112#section-6.1

"Early implementations of Transfer-Encoding would occasionally send both a chunked transfer coding for message framing and an estimated Content-Length header field for use by progress bars. This is why Transfer-Encoding is defined as overriding Content-Length, as opposed to them being mutually incompatible. Unfortunately, forwarding such a message can lead to vulnerabilities regarding request smuggling ([Section 11.2](https://www.rfc-editor.org/rfc/rfc9112#request.smuggling)) or response splitting ([Section 11.1](https://www.rfc-editor.org/rfc/rfc9112#response.splitting)) attacks if any downstream recipient fails to parse the message according to this specification, particularly when a downstream recipient only implements HTTP/1.0."
