### ISSUE TITLE
No Dart 3.0.0 CHANGELOG entry regarding the breaking change about colons and default values

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#52491]
This language issue, https://github.com/dart-lang/language/issues/2357, was implemented for Dart 3.0.0. But I don't see any text about it at https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md.

CC @lrhn

**Comment by srawlins** [comment]
Thanks @parlough !!

**Comment by parlough** [comment]
Of course! The changelog is super useful so I want to make sure it's accurate.

However, I messed up the link definition formatting causing it to not work...Fix is in https://dart-review.googlesource.com/c/sdk/+/320140.
