### ISSUE TITLE
[CP] [stable] Add `interface` to a few classes which had missed it.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#52505]
### Commit(s) to merge

7e56658645f9d3a0ccc1b402fdc7add91a2f2067

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/305281

### Issue Description

A few pure interface classes were not marked as `interface` in the 3.0 release. 
It's better to fix that soon, so this is landed as a breaking change, preferably in the next patch release.

### What is the fix

Add `interface` to the class declarations.

Has fixed the very few occurrences of `extends ClassName` in the SDK and other already known 3.0-migrated code (mainly in the SDK itself).

### Why cherry-pick

The sooner the modifier is added, the easier it is to land it.
Every library which migrates to Dart 3.0 increases the risk of there being _some_ Dart 3.0 code which `extends` these interface classes, even if there is very little code with reason to do so.

The CL merges cleanly against the SDK, Flutter and Google internal code.

### Risk

low

### Issue link(s)

https://dartbug.com/52334

**Comment by itsjustkevin** [comment]
@leafpetersen can you take a look here?

**Comment by leafpetersen** [comment]
Per the linked bug, this is an approved breaking change.  Code LGTM.  Agreed we should get this in ASAP.

**Comment by itsjustkevin** [comment]
@lrhn you are free to submit this change!

**Comment by lrhn** [comment]
CL has landed.
