### ISSUE TITLE
[CP] Intermittent VM Heap crash during hot-reload since Flutter 3.10/Dart 3.0

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#52508]
### Commit(s) to merge

e04d826d1aba9a21e789266efc919de9c8a693cf

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/305582

### Issue Description

Hot reload results in a crash, please see issue https://github.com/flutter/flutter/issues/126884

### What is the fix

Defensively check against identity mapping for Enum.values.
https://dart-review.googlesource.com/c/sdk/+/303860

### Why cherry-pick

The issue is resulting in crashes when hot reloading which makes it hard for app developers

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/126884

**Comment by itsjustkevin** [comment]
@mit-mit i defer this cherry pick review to you.

**Comment by mit-mit** [comment]
If this is accessed to low risk, then I think we should pick it. Having a crash in hot reload is pretty high impact.
