### ISSUE TITLE
[CP] [parser] Support nullable record types in patterns

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52518]
### Commit(s) to merge

284296f8628a56d22ec44f75a7220e6cbd5b466e

### Target

Stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/305824

### Issue Description

If a variable pattern or wildcard pattern has an explicit type which is a nullable record type, there is a parse error. For example, this code:
```dart
f(Object? x) {
  switch (x) {
    case ((int, int)? x, String y):
      break;
  }
}
```
is rejected with the error message:
```
.../test.dart:3:23: Error: Expected ')' before this.
    case ((int, int)? x, String y):
                      ^
```

### What is the fix

The parser's disambiguation rules are modified so that if a pattern starts with `(`, and the matching `)` is followed by `? identifier`, an attempt is made to parse the pattern as a variable pattern. Previously, the disambiguation rules only attempted to parse a pattern starting with `(` as a variable pattern if the matching `)` was followed by an identifier (i.e. a variable pattern with a _non-nullable_ record type).

### Why cherry-pick

Without this fix, users cannot express a pattern match using a variable or wildcard pattern with a nullable record type. It is not clear from the error message why the code is being rejected.

If we don't cherry-pick this fix, the fix will be released as part of Dart 3.1, so there will be a danger of a package author releasing code that is intended to be compatible with Dart 3.0, but which fails to work due to its use of a variable pattern with an explicit nullable record type.

The fix is low risk, because it is confined to the disambiguation logic that fires specifically for patterns that begin with `(`. The only syntax that is newly recognized as a variable pattern is `(...)? identifier`. Any ambiguities that might arise from this interpretation are also problems for the syntax `(...) identifier` (e.g. `(...) when` or `(...) as`), and the resolution of these ambiguities is already taken care of and well tested.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52439

**Comment by mit-mit** [comment]
SGTM
