### ISSUE TITLE
[CP] Cherry-pick linter w/ improved `type_literal_in_constant_pattern`

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#52516]
### Commit(s) to merge

[No existing SDK commit; this is an update to DEPS to pull in a cherry-pick on the linter in STABLE]

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/305823

### Issue Description

`type_literal_in_constant_pattern` has been improved to add more reporting.

From @mit-mit:

> We discussed this in the language team, and we think that it's high value enough to pursue as a cherry pick. We'll let you folks decide if the best approach is a linter roll or just patching this single change in.

https://github.com/dart-lang/linter/pull/4358

This cherry-pick is conservative and just pulls in this one change.

See branch: https://github.com/dart-lang/linter/commits/sdk-3.0

### What is the fix

Updating to lint on all type literals.

### Why cherry-pick

From @mit-mit:

> @johnpryan tells me that this issue seems to be mentioned as a common footgun on socials.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/linter/issues/4195

### Extra Info

The commits-to-merge hash above is on the linter. This change just pulls in an update to DEPS.

**Comment by mit-mit** [comment]
I think we should take this; we believe this is a big source of user confusion
