### ISSUE TITLE
unable to convert types on an empty list, see example below

### ISSUE THREAD

**Issue by therenca** [dart-lang/sdk#52519]
`var t = [];`
`List<Map<String, dynamic>> v = t.map((c) => c.map<String, dynamic>((key, value) => MapEntry(key as String, value as dynamic))).toList();`

but when i add a value inside of `t` like so
`var t = [{'test': 'test'}]`
the conversion works

**Comment by lrhn** [comment]
The static type of `var t = [];` is `List<dynamic>`.
The static type of `var t = [{'test': 'test'}];` is `List<Map<String, String>>`.

That affects how the rest of the code is inferred.

For `List<dynamic>`, the program infers the type of `c` as `dynamic` too, which means that the type of `c.map....` is `dynamic`, so the result of `t.map(...).toList` is a `List<dynamic>`.

For `List<Map<String, String>>`, the type of `c` is `Map<String, String>`, so `c.map<String, dynamic>(...)` has type `Map<String, dynamic>`, and the result of `t.map(...).toList()` has type `List<Map<String, dynamic>>`.

So this is working as intended.

The solution is to type your `[]` as, at least, `<Map>[]`.
