### ISSUE TITLE
[CP] Patterns parsing: fix record-typed variable patterns before certain tokens.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52529]
### Commit(s) to merge

e213846ba09bc56fe4b0ecd1bf1d88c6153bffd1

### Target

Stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/306020

### Issue Description

When a record-typed variable pattern is followed by one of the tokens `||`, `&&`, `as`, `?`, `!`, `when`, or `=>`, it is not accepted by the parser. For example, the following code:
```dart
f(x) => switch (x) { (int,) y => 0, _ => 1 };
```
produces the compile-time errors:
```
.../test.dart:1:29: Error: Expected '=>' before this.
f(x) => switch (x) { (int,) y => 0, _ => 1 };
                            ^
.../test.dart:1:31: Error: Expected ',' before this.
f(x) => switch (x) { (int,) y => 0, _ => 1 };
                              ^^
.../test.dart:1:29: Error: Undefined name 'y'.
f(x) => switch (x) { (int,) y => 0, _ => 1 };
                            ^
```

### What is the fix

Previously, if a record-typed variable pattern lacked a `var` or `final` keyword, and was followed by one of the tokens `||`, `&&`, `as`, `?`, `!`, `when`, or `=>`, the parser would fail to recognize it. This happened because the call to `computeVariablePatternType` wasn't passing `true` for the optional parameter `required`; that in turn placed `computeType` in a mode where it believed it was parsing a potentially ambiguous construct in a top-level declaration, and hence it would only accept the record type if the variable name was followed by something that looked like part of a correct declaration (e.g. a comma).

The fix is to pass `true` for the optional parameter `required` of `computeVariablePatternType`. This places `computeType` in a mode where it accepts the record type regardless of what follows it. This is correct behavior since at the point where a variable pattern is being parsed, ambiguities have already been taken care of and the construct being parsed is most definitely a variable pattern.

### Why cherry-pick

Without this fix, users cannot express a pattern match using a variable or wildcard pattern with a record type in certain contexts. It is not clear from the error message why the code is being rejected.

If we don't cherry-pick this fix, the fix will be released as part of Dart 3.1, so there will be a danger of a package author releasing code that is intended to be compatible with Dart 3.0, but which fails to work due to its use of a variable pattern with an explicit nullable record type.

The fix is low risk, because it is confined to the disambiguation logic that fires specifically for record-typed variable patterns that begin with `(`. The code path is well tested, since it is already used for record-typed variable patterns that begin with `final`.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52521

**Comment by itsjustkevin** [comment]
Summoning @leafpetersen for cherry-pick review.

**Comment by leafpetersen** [comment]
LGTM
