### ISSUE TITLE
can't call type aliased records when using `typedef`

### ISSUE THREAD

**Issue by ahmednfwela** [dart-lang/sdk#52523]
```dart
typedef Point = ({num lat, num lng});

void act(Point p) {
  print(p.lat); //works
}

act(Point(lat: 5, lng: 6.3)); //invocation_of_non_function
act((lat: 5, lng: 6.3)); //works
```

**Comment by eernstg** [comment]
This is working as intended. Record types do not have constructors, a record value can only be introduced by evaluating a record literal.

So `Point(lat: 5, lng: 6.3)` is an attempt to use an expression whose value is a reified type (an instance of type `Type`) in a position where a function is expected, a bit like `int(2, 3)` where we're trying to call the `Type` of `int` as a function. (We do use syntax like `StringBuffer('test')` to invoke a constructor as well, but constructors are also functions. Lots of things are functions.)

`(lat: 5, lng: 6.3)` on its own is a record literal, and the type of this expression is computed from the shape (in this case: two named fields, `lat` and `lng`), and the field expression types (`int` respectively `double`). This is the same type os `Point`, which is the reason why it is assignable to the parameter of `act`. So it's all working as intended.
