### ISSUE TITLE
[CP] Warn about old-style cache

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#52526]
### Commit(s) to merge

https://github.com/dart-lang/pub/pull/3921

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/305981

### Issue Description

In dart 3.0 Pub on Windows stopped reading caches in `C:\Users<user>\AppData\Roaming\Pub\Cache` (in favor of `C:\Users<user>\AppData\Local\Pub\Cache`).

These have not been created by pub since dart 2.8, but have been used if existing until and including 2.19.

This has lead to some amount of confusion for users with an old cache. Especially if they had a %PATH% pointing to the old location, then they would invoke old binstubs of globally activated packages.

### What is the fix

We detect the presence of the old cache, and print a warning, and instructions for how to proceed.

### Why cherry-pick

It could help guide users to find the new cache.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52386

**Comment by mit-mit** [comment]
@sigurdm is the warning the only change in `pub` in the new version compared to the current pinned version?

**Comment by sigurdm** [comment]
yes - unless I made a mistake it should be a true cherry pick of the warning
