### ISSUE TITLE
Analyzer confuses invocation as record

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#52538]
Hello!

I came across a scenario where the analyzer emits a "warning" instead of an type error. Not sure how to describe it, so here's a minimal reproducible sample:

```dart
void main() {
  final list = <(int, )>[];
  
  list.add(42);
}
```

In the `add` line, the analyzer emits the following warning:

> A record literal with exactly one positional field requires a trailing comma.

But this warning makes no sense. In reality, the problem is that we're trying to assign `int` to `(int)`.

Instead, we should be getting the following error:

> The argument type 'int' can't be assigned to the parameter type '(int)'.

**Comment by rrousselGit** [comment]
This appears to only be an analyzer error. The compiler correctly fails with the expected error.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/306306
