### ISSUE TITLE
[CP] DDC support for record subtype checks with web numeric semantics 

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#52531]
### Commit(s) to merge

44b5ca76a9f9b0f2d1ed381ae722521c9984ba3b
8dfd25ac7a335a42a374da297246a28815d04765

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/306307

### Issue Description

The subtype check implementation for records in DDC did not respect web semantics for numerics (`int` being a subtype of `double`)

### What is the fix

Update DDC's subtype check implementation to dispatch on the subtype checks for each of its fields.

### Why cherry-pick

This pattern can be triggered extremely easily in DDC. E.g.:
```
void main() {
  var recordList = <(double, String)>[];
  recordList.add((1.0, 'hello')); // crashes but should be allowed
}
```
The issue has a high impact potential due records being widely advertised in the Dart 3.0 release. 

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52480

### Extra Info

This contains cherry-picks for the CLs in [this chain](https://dart-review.googlesource.com/c/sdk/+/305560). The latter just adds a regression test. Additionally, this change diverges very slightly from `main` in `RecordType`'s `as` check. For a clean merge, `RecordImpl` (in `main`) is renamed to `_RecordImpl`.

**Comment by Markzipan** [comment]
@nshahan @sigmundch for context

**Comment by itsjustkevin** [comment]
Hey @Markzipan, I noticed that your request points to the CL that landed on main.  To continue triaging this cherry-pick, we would need that field to point to the cherry-pick to the stable channel.  

For further instructions, please refer to: https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel.

Thank you.

**Comment by itsjustkevin** [comment]
@sigmundch and @nshahan could you take a look at this cherry-pick request?

**Comment by Markzipan** [comment]
Thanks Kevin - updated the link

**Comment by sigmundch** [comment]
I'm very supportive of this cherry-pick. It's low risk but highly visible problem.
