### ISSUE TITLE
Add support for collection-if in 'remove comparison' quick-fix

### ISSUE THREAD

**Issue by shilangyu** [dart-lang/sdk#52543]
The following raises `unnecessary_null_comparison` warning, but offers no quick-fix for it:

```dart
final int a = 123;

final list = [
	if (a != null) // warning here, `a` cannot be null
		a
];
```

The `RemoveComparison` quick-fix doesn't implement support for it. If this is a wanted change, I can send a CL with this feature.

**Comment by DragonTrail99** [comment]
final int? a =123;
Declare 'a' as a nullable value like above

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/306312
