### ISSUE TITLE
Potentially spurious evaluation of some await expressions in web backends

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#52559]
Consider the following lines in a language test.

https://github.com/dart-lang/sdk/blob/76f803a41caf6f4c37c0514b5954a77fb869046c/tests/language/async/await_flatten_test.dart#L36-L39

A `Future` object is created in line 36, then it's awaited in line 37, and line 39 dynamically ensures that the runtime type of the resulting object is `Future<Object?>`. The test passes on the VM, but fails on dart2js, DDC, and dart2wasm.

My understanding is that `await o` should not unwrap the `Future` object because the static type of `o` is `Object`. The backends should perform a check against a type that the node for the `await` expression is decorated with, and in case of a mismatch, they should leave the object intact or wrap it in a `Future`.

The type that the `await` node is decorated with in this case is `Future<Object>` as seen from the generated Kernel code.

```
  final core::Object o = asy::Future::value<core::Object?>();
  core::Object o2 = await o /* runtimeCheckType= asy::Future<core::Object> */ ;
  sta::StaticType|expectStaticType<core::Object, (core::Object) → core::Object>(o2);
  exp::Expect::type<asy::Future<core::Object?>>(o2);
```

It seems to be a runtime error in the web backends.

The issue is encountered while working on this CL: https://dart-review.googlesource.com/c/sdk/+/306400.

**Comment by eernstg** [comment]
Right, `o` evaluates to a `Future<Object?>` but has static type `Object`. So the static type of `await o` is `flatten(Object)`, which is `Object`, so we should wrap the given `Future<Object?>` in a `Future<Object>`, await that, and get hold of the `Future<Object?>` again, which is the value of `await o`.

**Comment by nshahan** [comment]
@chloestefantsova The test `language/async/await_flatten_test` mentioned above is passing on DDC and dart2js now so I'm going to remove those tags. It is still failing on dart2wasm. Please let us know if there are any further issues with the JavaScript compilers.
