### ISSUE TITLE
language/nnbd/syntax/late_modifier_final_field_test failing on reload/rollback CI bots

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#52554]
There are new test failures on [[infra] Forgive flakiness on tests that have been stable for a week](https://github.com/dart-lang/sdk/commit/45f88667647563e7f6db878f46dd41230104b420).

The tests
```
language/nnbd/syntax/late_modifier_final_field_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-reload-rollback-linux-debug-x64
vm-reload-rollback-linux-release-x64
```

[Log for debug-x64](https://dart-ci.appspot.com/log/vm-reload-rollback-linux-debug-x64/vm-reload-rollback-linux-debug-x64/102/language/nnbd/syntax/late_modifier_final_field_test) (same as release-x64):
```
--- Command "vm" (took 05.000602s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --hot-reload-rollback-test-mode --optimization_counter_threshold=10 --sound-null-safety -Dtest_runner.configuration=vm-reload-rollback-linux-debug-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/language/nnbd/syntax/late_modifier_final_field_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.throws fails: Did not throw
#0      Expect._fail (package:expect/expect.dart:696:5)
#1      Expect.throws (package:expect/expect.dart:604:5)
#2      main (file:///b/s/w/ir/tests/language/nnbd/syntax/late_modifier_final_field_test.dart:41:12)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

--- Re-run this test:
python3 tools/test.py -n vm-reload-rollback-linux-debug-x64 language/nnbd/syntax/late_modifier_final_field_test
```

Looking back at the history, these started going flaky between [58df97](https://github.com/dart-lang/sdk/commit/58df9774b6898a32988e52f413ed804b2c0f6f08)..[5164ec](https://github.com/dart-lang/sdk/commit/5164ecd5ece2343bac7d7b01ded910a1025d891b), so chances are the issue is somewhere in that range.

**Comment by mkustermann** [comment]
This seems to be a compiler bug and unrelated to hot-reload.

Repro
```dart
import 'package:expect/expect.dart';

class A {
  late final int fieldWithInit;
}

main() {
  for (int i = 0; i < 50; ++i) {
    final a = A();
    a.fieldWithInit = 456;
    Expect.throws(() => a.fieldWithInit = 789);
  }
}
```

Run
```
out/ReleaseX64/dart --no-use-osr --deterministic --optimization-counter-threshold=10 --sound-null-safety test.dart
Unhandled exception:
Expect.throws fails: Did not throw
...
```
leave `--deterministic` out then it passes.

This may be because of an incorrectly eliminated `sentinel` check in the `late final` implementation in the compiler. More specifically it may be due us not using normal inliner but instead `CallSpecializer::TryInlineInstanceSetter` for inlining the setter call. That doesn't seem to take `late final` into account.

@alexmarkov Could you take a look?
