### ISSUE TITLE
Serializing kernel after TFA breaks functions that return `FutureOr` type

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#52565]
(1) Write a function that returns a `FutureOr` type
(2) Compile to AST and run the TFA kernel transform on it
(3) Serialize the output of the TFA using `writeComponentToBinary` from the kernel package
(4) Deserialize that same file using `loadComponentFromBinary`

Result:
Crash on exception `Expected a class reference to be valid but was 'null'.` in `readNonNullClassReference`

Details:\
In `ast_to_binary.dart`, we have the following code:

```
  @override
  void visitFutureOrType(FutureOrType node) {
    // TODO(cstefantsova): Remove special treatment of FutureOr when the VM
    // supports the new encoding: just write the tag.
    assert(_knownCanonicalNameNonRootTops.isNotEmpty);
    CanonicalName root = _knownCanonicalNameNonRootTops.first;
    while (!root.isRoot) {
      root = root.parent!;
    }
    CanonicalName canonicalNameOfFutureOr =
        root.getChild("dart:async").getChild("FutureOr");
    writeByte(Tag.InterfaceType);
    writeByte(node.declaredNullability.index);
    checkCanonicalName(canonicalNameOfFutureOr);
    writeUInt30(canonicalNameOfFutureOr.index + 1);
    writeUInt30(1); // Type argument count.
    writeNode(node.typeArgument);
  }
```

This works for code that is early in the compilation process. However, if the serialization is done after TFA, this will emit zero for the `canonicalNameofFutureOr.index`. I suspect this is because the `FutureOr` type is being pruned by TFA itself, and so there is no valid index for a `FutureOr` type.

**Comment by eyebrowsoffire** [comment]
This blocks https://github.com/dart-lang/sdk/issues/50800, which in turn is blocking https://github.com/flutter/flutter/issues/117248

**Comment by sigmundch** [comment]
cc @johnniwinther @alexmarkov

**Comment by alexmarkov** [comment]
Could you try adding `@pragma("wasm:entry-point")` to class `FutureOr`?

**Comment by eyebrowsoffire** [comment]
It already is marked as such, see `async/future.dart`:
```
@pragma("vm:entry-point")
abstract class FutureOr<T> {
```
I don't think it's just a matter of ensuring that the `FutureOr` class still exists after TFA. I think the serialization and deserialization technique needs to actually change, because it's basically a lossy process. When you serialize and deserialize the component, anything that is actually a `FutureOrType` in the AST will become an `InterfaceType` that is refers to the class in `dart:async`, which is not the same. At least in `dart2wasm`, that will mess up the codegen machinery since there are compiler-level intrinsics for handling the `FutureOrType` specifically.

I think dart kernel needs an actual encoding for a `FutureOrType`

**Comment by alexmarkov** [comment]
> It already is marked as such, [...]

`@pragma("vm:entry-point")` is not enough, as dart2wasm has its own pragma for entry points - `@pragma("wasm:entry-point")`. TFA recognizes different pragmas depending on the target.

Kernel deserialization is smart enough to recognize InterfaceType based on FutureOr and convert it back to FutureOrType, so nothing is lost in the process of serialization/deserialization:

https://github.com/dart-lang/sdk/blob/3484bfe96441306d59a29451f1524c91f92448c4/pkg/kernel/lib/binary/ast_from_binary.dart#L3861-L3868

> I think dart kernel needs an actual encoding for a `FutureOrType`.

Sure. However, using `@pragma("wasm:entry-point")` on `FutureOr` could be enough to quickly unblock your use case.

**Comment by johnniwinther** [comment]
@alexmarkov Do you know the VM can use the `FutureOrType` directly, so we can avoid the serializing through an `InterfaceType` (as mentioned in the TODO in `visitFutureOrType` above) ?

**Comment by johnniwinther** [comment]
cc @chloestefantsova

**Comment by alexmarkov** [comment]
Took a stab at implementing serialization of `FutureOrType` and `NullType` without using `InterfaceType` encoding in kernel and the VM: https://dart-review.googlesource.com/c/sdk/+/306901.
