### ISSUE TITLE
Unexpected code execution when attempting to execute dart commands

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#52566]
After seeing https://stackoverflow.com/q/76355400/, I realized that `dart FOO` will execute either an internal `FOO` command or a Dart file named `FOO` in the current directory.  In the case of a name collision, the file apparently wins.

How safe is that?  Is there any risk of someone (or perhaps [pub.dev](http://pub.dev/)?) executing some arbitrary file named `pub`/`analyze`/`format`/etc. unexpectedly?  Presumably pub.dev executes commands in a sandboxed environment already, so maybe that's okay.  Should someone cloning a malicious Dart package repository and running `dart analyze`/`dart format`/etc. commands in it be considered game-over already?

Regardless, it seems to me that a safer default would be to always prefer built-ins if there's a name collision.  In the improbably rare case that someone wants to execute a file with the same name as a built-in command, an explicit path could be used (e.g. `dart ./FOO`).

**Comment by bwilkerson** [comment]
Alternately, if there's a collision, print a message and don't run either, given that the user's intent isn't clear and the built-in command might have side-effects.

**Comment by blaugold** [comment]
Just FYI, this has previously been discussed in https://github.com/dart-lang/sdk/issues/51932.

**Comment by jamesderlin** [comment]
Thanks!  I didn't see that one.
