### ISSUE TITLE
Debugger should step across the async gap when stepping into an async function call

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#52569]
When stepping into an async function call, VS Code's Dart debugger steps into `_SuspendState._initAsync` inside `async_patch.dart` -- and then proceeds to go through a series of very complex steps to handle the async call. It's impossible to step through an async call without putting the cursor on the async function name, hitting f12, then setting a breakpoint inside the function, then clicking the Continue button in the debugger. Then you have to remove the breakpoint again if there are other calls to the function that you don't want to debug.

All this should happen automatically if you step into an async function call -- the debugger should stop at the first line of the function that is being called, not at the first line of the async machinery.

* Dart SDK Version (`dart --version`): 3.0.2
* Whether you are using Windows, MacOSX, or Linux (if applicable): Android
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

**Comment by a-siva** [comment]
//cc @derekxu16 @bkonyi

**Comment by lukehutch** [comment]
This is particularly a problem when the async method is an abstract method of a superclass, and the actual method call dispatched at runtime is based on the type of the receiver. To step into these async methods, you can't just hit F12 and set a breakpoint at the start of the async function. You have to find all the implementing subclasses, and manually set breakpoints on entry to each implementation of the abstract function.

**Comment by lukehutch** [comment]
One halfway workaround would be: in the debugger, if you hit F12 on a method, and the concrete receiver is a subclass of the class defining the method, then ask the user if they want to step into the concrete subclass, or the defining superclass.

But in general, it would be better if "Step in" worked fine, always, regardless of the async gap.

**Comment by lukehutch** [comment]
I found one way to do it -- "Step Into" (which enters async code) followed by "Step Over". This seems to take the debugger to the async method.

**Comment by lukehutch** [comment]
@derekxu16 You're right, that was set, and I have no idea how it got set. Thank you for your help!
