### ISSUE TITLE
"Global evaluation is not supported", possible regression

### ISSUE THREAD

**Issue by techvx** [dart-lang/sdk#52574]
Updating via `flutter upgrade` to the latest version breaks the ability to inspect global variables - in VS Code, at least. Impossible to inspect any global state outside of the immediate local scope even when the execution is paused, i.g. at a breakpoint, either. 

The minimal example from the thread [of 5 years ago](https://github.com/Dart-Code/Dart-Code/issues/906#issuecomment-627216361) when the feature appears to have been first discussed:
 
![image](https://github.com/dart-lang/sdk/assets/25274461/091a0618-3ba8-4e9b-a66f-74e3a7180245)

Fails with "global evaluation is not supported". 

Possibly related to #52430 and [#4555](https://github.com/Dart-Code/Dart-Code/issues/4555).

Downgrading to Flutter 3.7.6 / Dart 2.19.3 solves the issue.

Will experiment with other attempts to upgrade and reproducible examples of my own, when I find the time.

<details>
<summary>flutter doctor</summary>
<p>

[√] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.21) 
[√] Android Studio (version 4.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

</p>
</details> 

<details><summary>flutter --version</summary>
<p>

Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (3 months ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1

</p>
</details>

**Comment by a-siva** [comment]
This example seems to work fine in devtools, I am able to print the value of `counter` when stopped at a breakpoint inside the while loop. Haven't tried with VS code.

**Comment by DanTup** [comment]
> Impossible to inspect any global state outside of the immediate local scope even when the execution is paused

Do you see this with your example above? I can reproduce "Global evaluation is not supported" when not paused, but using the example above and being paused I can evaluate `count`:

<img width="598" alt="Screenshot 2023-05-31 at 19 44 51" src="https://github.com/dart-lang/sdk/assets/1078012/19bad0d1-7f42-438f-b0b0-b69834e0ce4e">

There are two known (but distinct) issues I can reproduce:

### 1. In the latest SDKs, some variables cannot be evaluated and show "OptimizedOut"

There's an issue about that at https://github.com/dart-lang/sdk/issues/52430. I think that might be a VM issue as it occurs in both legacy and SDK debug adapters (although how the error appears is slightly different)


### 2. Global evaluation is not supported (that is, you cannot evaluate expressions if execution is not paused)
  This has never been properly supported, but in the legacy debug adapters there were some hacks to try and make it work for some cases. We would pick an arbitrary isolate and its root library (eg. `lib/main.dart`) and evaluate the expression in that context. This would work for some expressions, but not others. This hack was not reproduced in the new SDK debug adapters - the hope was to implement this in a better way (allowing you to choose which script/isolate the expression is being evaluated in the context of) but it requires [some changes in VS Code](https://github.com/microsoft/vscode/issues/134452).


We could consider implementing the same behaviour in the new SDK DAPs, although I'm not sure how useful it really is outside of single-file scripts/trivial apps, as I don't think you'd be able to access most of the globals you want.

FWIW, if you're using the new debug adapters, Globals will now show up in the Variables pane alongside Locals, which might provide some of the value of global evaluation.

**Comment by techvx** [comment]
> Do you see this with your example above?

The standalone loop in the `main.dart` does allow to inspect the `count` both in the globals panel and the debug console itself, when paused / during a breakpoint.

<details><summary>Details</summary>
<p>

![image](https://github.com/dart-lang/sdk/assets/25274461/443556ca-6850-4a74-a79f-0d6ec95b367b)

</p>
</details> 

An actual widget tree only allows for the inspection of local global variables:

<details><summary>Details</summary>
<p>

![image](https://github.com/dart-lang/sdk/assets/25274461/adb7585a-3adf-4e78-b6dc-659eb46ee405)

</p>
</details> 

Referring to them during any other breakpoint, however, is a futile endeavour:

<details><summary>Details</summary>
<p>

![image](https://github.com/dart-lang/sdk/assets/25274461/2da3f018-bdec-4f5c-a9cc-c3faa70d5f29)

</p>
</details> 

Those hacks - in whatever way they had been implemented - were, are, and will be needed for a long time. 

That single exposed root isolate kept things flexible enough to allow setups of this kind:

<details><summary>Code</summary>
<p>

```dart
final debug = Debugger();

void main() {
  final scope = Reactor(
    child: const App(),
    debugger: debug,
  );
  runApp(scope);
}

...

class Debugger {

  late final WidgetState? state;

  void link(WidgetState state) {
    this.state = state;
  }

  call(String i) => state.inspect(i);
}
``` 

</p>
</details> 

These expose and bring to light any relevant state through a simple `debug("inspectable")`, which can easily be made into `debug.inspectable` as well - without any tedious lookups through the whole Widget Details Tree. 

Even when a value-holding `InheritedWidget` or `Provider` (which not every state management solution is based on) is there to look into, inspecting a large `List` or a nested tree of `Map`s and `Set`s without getting lost is virtually impossible.

And this is just one use case I stumbled upon while putting together a few of my own ideas.

**Comment by DanTup** [comment]
I think there's some confusion between two different issues. Supporting "global evaluation" in the new debug adapters in the same way as the old one will not resolve any issues where you're seeing "<optimized out>" or are paused at a breakpoint. Those evaluation errors are a different issue being tracked in https://github.com/dart-lang/sdk/issues/52430 (which I'm less familiar with as they're from the VM).

You can check this using the setting noted above. Setting `"dart.previewSdkDaps": false` will force you back onto the legacy debug adapters which will support "global evaluation" (in the limited way described above), but won't resolve the other issue (eg. inside build methods when at breakpoints) - which I suspect is the one you probably care about most.

I'll have a look at handling global evaluation in the same way for now, but to avoid confusion let's keep these two issues separate - this one specifically for where you see "Global evaluation is not supported" errors, and https://github.com/dart-lang/sdk/issues/52430 for failures like "OptimizedOut" when executing is paused and evaluating is failing.

**Comment by DanTup** [comment]
I've pushed some changes to the new debug adapters (https://github.com/dart-lang/sdk/commit/80a6670d5d081bf6542036979791a8f666adfc1d) and Dart-Code (https://github.com/Dart-Code/Dart-Code/commit/7389b2c40b07b51e3deb2534074ed71a04c52965) to add some basic global eval support.

It works similar to the legacy DAPs (picking the first available isolate), but it does use your current open file as the target (instead of just the root library as the legacy DAP did).

You'll need both the SDK change and the VS Code extension change for this to work. We'll need some VS Code changes (https://github.com/microsoft/vscode/issues/134452) to be implemented to allow you to select which isolate to evaluate in - but I suspect for the majority of cases the one we pick automatically will be sufficient.
