### ISSUE TITLE
Watcher fails with `class 'FileSystemEvent' can't be extended`, for dart, not for flutter.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#52570]
Commit: 
https://github.com/dart-lang/leak_tracker/pull/69/commits/4d2618b7dce261805807698f9ad324192ae13165

To repro run the test and see the build error: 
```
 dart test /Users/polinach/_/leak_tracker/test/dart_debug/leak_tracking/end_to_end_test.dart
Building package executable... (2.7s)
Failed to build test:test:
../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
```

Flutter test builds well:
```
flutter test /Users/polinach/_/leak_tracker/test/dart_debug/leak_tracking/end_to_end_test.dart
```

Versions:

```
polinach-macbookpro3:leak_tracker polinach$ flutter --version
Flutter 3.11.0-16.0.pre.16 • channel [user-branch] • unknown source
Framework • revision 7d310e3b1b (57 minutes ago) • 2023-05-30 17:19:58 -0700
Engine • revision 1ba8091fbc
Tools • Dart 3.1.0 (build 3.1.0-155.0.dev) • DevTools 2.23.1
polinach-macbookpro3:leak_tracker polinach$ dart --version
Dart SDK version: 3.1.0-155.0.dev (dev) (Fri May 26 19:56:47 2023 -0700) on "macos_arm64"
polinach-macbookpro3:leak_tracker polinach$ 
```

**Comment by polina-c** [comment]
`dart pub upgrade` helped

Closing

**Comment by usamamanzoor07** [comment]
Since Updating to Flutter 3.13 I have been unable to run scripts in the terminal. I am trying to run fluttergen with buildrunner like this "fluttergen -c pubspec.yaml"
and below is the response. Earlier it was running smoothly. I have tried "dart pub upgrade" but it is not helping.
Can't load Kernel binary: Invalid kernel binary format version.
Building package executable... (1.4s)
Failed to build flutter_gen:flutter_gen_command:
../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {

**Comment by usamamanzoor07** [comment]
_fe_analyzer_shared 61.0.0 (64.0.0 available)
  analyzer 5.13.0 (6.2.0 available)
  archive 3.3.7
  args 2.4.2
  async 2.11.0
  boolean_selector 2.1.1
  build 2.4.1
  build_config 1.1.1
  build_daemon 4.0.0
  build_resolvers 2.2.1
  build_runner 2.4.6
  build_runner_core 7.2.10
  built_collection 5.1.1
  built_value 8.6.1
  characters 1.3.0
  checked_yaml 2.0.3
  cli_util 0.4.0
  clock 1.1.1
  code_builder 4.5.0
  collection 1.17.2 (1.18.0 available)
  color 3.0.0
  connectivity_plus 4.0.2
  connectivity_plus_platform_interface 1.2.4
  convert 3.1.1
  crypto 3.0.3
  cupertino_icons 1.0.5
  dart_style 2.3.2
  dartx 1.2.0
  dbus 0.7.8
  dio 5.3.2
  fake_async 1.3.1
  ffi 2.1.0
  file 7.0.0
  fixnum 1.1.0
  flex_color_scheme 7.3.1
  flex_seed_scheme 1.4.0
  flutter 0.0.0 from sdk flutter
  flutter_gen 5.3.1
  flutter_gen_core 5.3.1
  flutter_launcher_icons 0.13.1
  flutter_lints 2.0.2
  flutter_screenutil 5.9.0
  flutter_svg 2.0.7
  flutter_test 0.0.0 from sdk flutter
  flutter_web_plugins 0.0.0 from sdk flutter
  fpdart 1.1.0
  frontend_server_client 3.2.0
  get 4.6.5
  get_storage 2.1.1
  glob 2.1.2
  graphs 2.3.1
  http_multi_server 3.2.1
  http_parser 4.0.2
  image 4.0.17
  intl 0.18.1
  io 1.0.4
  js 0.6.7
  json_annotation 4.8.1
  lints 2.1.1
  logging 1.2.0
  lottie 2.6.0
  matcher 0.12.16
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1
  mime 1.0.4
  nm 0.5.0
  package_config 2.1.0
  path 1.8.3
  path_parsing 1.0.1
  path_provider 2.1.0
  path_provider_android 2.1.0
  path_provider_foundation 2.3.0
  path_provider_linux 2.2.0
  path_provider_platform_interface 2.1.0
  path_provider_windows 2.2.0
  petitparser 5.4.0 (6.0.1 available)
  pinput 3.0.0
  platform 3.1.1
  plugin_platform_interface 2.1.5
  pointycastle 3.7.3
  pool 1.5.1
  pub_semver 2.1.4
  pubspec_parse 1.2.3
  shelf 1.4.1
  shelf_web_socket 1.0.4
  sky_engine 0.0.99 from sdk flutter
  smart_auth 1.1.1
  source_span 1.10.0
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  stream_transform 2.1.0
  string_scanner 1.2.0
  term_glyph 1.2.1
  test_api 0.6.0 (0.6.1 available)
  time 2.1.3
  timing 1.0.1
  typed_data 1.3.2
  universal_platform 1.0.0+1
  url_launcher 6.1.12
  url_launcher_android 6.0.38
  url_launcher_ios 6.1.4
  url_launcher_linux 3.0.5
  url_launcher_macos 3.0.6
  url_launcher_platform_interface 2.1.3
  url_launcher_web 2.0.18
  url_launcher_windows 3.0.7
  vector_graphics 1.1.7
  vector_graphics_codec 1.1.7
  vector_graphics_compiler 1.1.7
  vector_math 2.1.4
  watcher 1.1.0
  web 0.1.4-beta
  web_socket_channel 2.4.0
  win32 5.0.6
  xdg_directories 1.0.2
  xml 6.3.0 (6.4.2 available)
  yaml 3.1.2

**Comment by usamamanzoor07** [comment]
This is my pubspec file

name: *****
version: 1.0.0+7
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  flex_color_scheme: ^7.3.1
  intl: ^0.18.1
  get_storage: ^2.1.1
  get: 4.6.5
  url_launcher: ^6.1.11
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  fpdart: ^1.1.0
  pinput: ^3.0.0
  lottie: ^2.6.0




  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_gen: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  image_path: assets/images/app_icon_light.jpg
  adaptive_icon_background: '#FFFFFF'
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/animations/
    - assets/certificates/
    - assets/images/
    - assets/svgs/
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Book.ttf
        - asset: assets/fonts/CircularStd-Light.ttf
          weight: 300
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500

  uses-material-design: true

**Comment by MethylIsocyanide** [comment]
Had the same error, running "dart pub upgrade" solved the issue.

**Comment by devchenli** [comment]
> Since Updating to Flutter 3.13 I have been unable to run scripts in the terminal. I am trying to run fluttergen with buildrunner like this "fluttergen -c pubspec.yaml" and below is the response. Earlier it was running smoothly. I have tried "dart pub upgrade" but it is not helping. Can't load Kernel binary: Invalid kernel binary format version. Building package executable... (1.4s) Failed to build flutter_gen:flutter_gen_command: ../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class. abstract class _ConstructableFileSystemEvent implements FileSystemEvent {

Hello，same error, Any update ?

**Comment by usamamanzoor07** [comment]
@devchenli Not Lucky until now!

**Comment by jeffmilanes** [comment]
@usamamanzoor07 try to run this command 

`dart run build_runner build --delete-conflicting-outputs` or `flutter packages pub run build_runner build --delete-conflicting-outputs`

**Comment by usamamanzoor07** [comment]
Deprecated. Use `dart run` instead.
Building package executable... (8.6s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 463ms
[INFO] Precompiling build script... completed, took 8.3s
[SEVERE] Nothing can be built, yet a build was requested.
[INFO] Building new asset graph completed, took 944ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 3ms
[INFO] Caching finalized dependency graph completed, took 54ms
[INFO] Succeeded after 69ms with 0 outputs (0 actions)

**Comment by bernardoveras** [comment]
Same error...

**Comment by AbdallaTawfikA** [comment]
> Since Updating to Flutter 3.13 I have been unable to run scripts in the terminal. I am trying to run fluttergen with buildrunner like this "fluttergen -c pubspec.yaml" and below is the response. Earlier it was running smoothly. I have tried "dart pub upgrade" but it is not helping. Can't load Kernel binary: Invalid kernel binary format version. Building package executable... (1.4s) Failed to build flutter_gen:flutter_gen_command: ../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class. abstract class _ConstructableFileSystemEvent implements FileSystemEvent {

try pub upgrade worked for me

**Comment by Muhammed-Essam** [comment]
flutter pub upgrade worked for me too

**Comment by KhaledBasiony** [comment]
I had the same error with dart_frog after I upgraded my flutter version to 3.13

I noticed the problem was with `watcher-1.0.2` and after running `dart pub upgrade` it upgraded `watcher` to `1.1.0` and I'm guessing that fixed the issue.

@usamamanzoor07 your error shows it's still using `watcher-1.0.2` somehow, did you try clearing your cache or moving the `watcher-1.0.2` folder out of it?
or maybe running something like `dart pub cache repair`?

**Comment by usamamanzoor07** [comment]
@KhaledBasiony you absolutely hit the nail on the spot. It worked by running `dart pub cache repair`. I hadn't tried it earlier. Thank you so much for helping.

**Comment by JaredEzz** [comment]
> I had the same error with dart_frog after I upgraded my flutter version to 3.13
> 
> I noticed the problem was with `watcher-1.0.2` and after running `dart pub upgrade` it upgraded `watcher` to `1.1.0` and I'm guessing that fixed the issue.
> 
> @usamamanzoor07 your error shows it's still using `watcher-1.0.2` somehow, did you try clearing your cache or moving the `watcher-1.0.2` folder out of it? or maybe running something like `dart pub cache repair`?

Thanks for your help. I had watcher-1.1.0 specified in my pubspec.yml but my pubspec.lock still had 1.0.2 on it. Deleting the lock did it

**Comment by svencarstenrasmusen** [comment]
> I had the same error with dart_frog after I upgraded my flutter version to 3.13
> 
> I noticed the problem was with `watcher-1.0.2` and after running `dart pub upgrade` it upgraded `watcher` to `1.1.0` and I'm guessing that fixed the issue.
> 
> @usamamanzoor07 your error shows it's still using `watcher-1.0.2` somehow, did you try clearing your cache or moving the `watcher-1.0.2` folder out of it? or maybe running something like `dart pub cache repair`?

This worked very well for me too! Thank you very much!

**Comment by gavin-shaw** [comment]
If you are not ready for a `flutter pub upgrade` on your project. You can pin the dependency resolution for only watcher in your pubspec.yaml. This worked for me.

```
dependency_overrides:
  watcher: ^1.1.0
```

**Comment by lanrehnics** [comment]
> If you are not ready for a `flutter pub upgrade` on your project. You can pin the dependency resolution for only watcher in your pubspec.yaml. This worked for me.
> 
> ```
> dependency_overrides:
>   watcher: ^1.1.0
> ```

flutter pub upgrade can be expensive most people don't know. You can inherit bugs you don't expect as a result of breaking changes from updated libs. It's always good to be specific and know what you are changing.

**Comment by kipropfredrick** [comment]
@lanrehnics  this saved me alot

**Comment by mhbdev** [comment]
> `dart pub upgrade` helped
> 
> Closing

Life saver!

**Comment by percula** [comment]
If you're having this issue with `intl_utils:generate`, run `flutter pub global activate intl_utils`. That'll upgrade the global `intl_utils` version, which will also fix the `watcher` version.

**Comment by Frankdroid7** [comment]
For me I deleted my `.pub-cache` folder in my local user directory. 
Then I ran:
1. `flutter pub cache repair`.
2. `flutter pub get`
3. `flutter pub run build_runner build --delete-conflicting-outputs`

Worked for me!

**Comment by jger** [comment]
I had the same issue in my project.

The solution for me was to delete all pubspec.lock files (also in my packages folder).

**Comment by Chappie74** [comment]
> > If you are not ready for a `flutter pub upgrade` on your project. You can pin the dependency resolution for only watcher in your pubspec.yaml. This worked for me.
> > ```
> > dependency_overrides:
> >   watcher: ^1.1.0
> > ```
> 
> flutter pub upgrade can be expensive most people don't know. You can inherit bugs you don't expect as a result of breaking changes from updated libs. It's always good to be specific and know what you are changing.

bless your soul <3

**Comment by maheini** [comment]
Deleting pubspec.lock (and running flutter pub get) helped in my case.

**Comment by agordeev** [comment]
As @lanrehnics pointed, `dart pub upgrade` might upgrade other dependencies, which is sometimes unwanted.

Use `dart pub upgrade watcher` instead. It will upgrade only `watcher` and will fix the issue.

**Comment by caseyryan** [comment]
> Had the same error, running "dart pub upgrade" solved the issue.

Indeed, it helped. Thanks

**Comment by 3li-3bdullah** [comment]
> If you are not ready for a `flutter pub upgrade` on your project. You can pin the dependency resolution for only watcher in your pubspec.yaml. This worked for me.
> 
> ```
> dependency_overrides:
>   watcher: ^1.1.0
> ```

Thanks
