### ISSUE TITLE
request a mirror for dart-lang/ecosystem

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#52586]
Hi! I'd like a mirror for https://github.com/dart-lang/ecosystem. This is in order to bring package:dart_flutter_team_lints (https://github.com/dart-lang/ecosystem/tree/main/pkgs/dart_flutter_team_lints) into the sdk. It's a package which builds on top of package:lints/recommended.yaml; it adds more type and analysis-time safety, but turns on lints that we don't necessarily want to be part of our recommended set for users.

That package - package:dart_flutter_team_lints - doesn't have any other dependencies (apart from package:lints, which is already dep'd into the sdk).

**Comment by devoncarew** [comment]
ping @whesse @athomas @sortie

**Comment by whesse** [comment]
This mirror has been created.  A follow-up, to increase the polling frequency of this mirror and all mirrors of dart-lang repos created since 2019, to match the 30 minute polling frequency of pre-2019 dart-lang mirrors, is in progress.

**Comment by devoncarew** [comment]
Thanks!
