### ISSUE TITLE
Timeouts on ARM64 Linux Cavium

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#52589]
There are new test failures on [[test] Don't apply simulator timeout multipler to ARM hardware.](https://github.com/dart-lang/sdk/commit/87362c6f42c5f4e7e2330ca7a5fe43a677d9b897).

The tests
```
service/add_breakpoint_rpc_kernel_test/dds Timeout (expected Pass)
service/add_breakpoint_rpc_kernel_test/service Timeout (expected Pass)
service/allocations_test/dds Timeout (expected Pass)
service/allocations_test/service Timeout (expected Pass)
service/async_next_regression_18877_test/dds Timeout (expected Pass)
service/async_next_regression_18877_test/service Timeout (expected Pass)
service/async_next_test/dds Timeout (expected Pass)
service/async_next_test/service Timeout (expected Pass)
service/async_scope_test/dds Timeout (expected Pass)
service/async_scope_test/service Timeout (expected Pass)
service/async_single_step_exception_test/dds Timeout (expected Pass)
service/async_single_step_exception_test/service Timeout (expected Pass)
service/async_single_step_into_test/dds Timeout (expected Pass)
service/async_single_step_into_test/service Timeout (expected Pass)
service/async_single_step_out_test/dds Timeout (expected Pass)
service/async_single_step_out_test/service Timeout (expected Pass)
service/async_star_single_step_into_test/dds Timeout (expected Pass)
service/async_star_single_step_into_test/service Timeout (expected Pass)
service/async_star_step_out_test/service Timeout (expected Pass)
service/async_step_out_test/dds Timeout (expected Pass)
service/async_step_out_test/service Timeout (expected Pass)
service/auth_token_test/dds Timeout (expected Pass)
service/auth_token_test/service Timeout (expected Pass)
service/awaiter_async_stack_contents_2_test/dds Timeout (expected Pass)
service/awaiter_async_stack_contents_2_test/service Timeout (expected Pass)
service/awaiter_async_stack_contents_test/dds Timeout (expected Pass)
service/awaiter_async_stack_contents_test/service Timeout (expected Pass)
service/bad_reload_test/dds Timeout (expected Pass)
    and 517 more tests
```
are failing on configurations
```
vm-linux-release-arm64
```

**Comment by rmacnak-google** [comment]
Seems like another reason to migrate to GCE instances

**Comment by alexmarkov** [comment]
This started since 87362c6f42c5f4e7e2330ca7a5fe43a677d9b897 which greatly decreased timeouts on arm and arm64.
@rmacnak-google Does it make sense to revert that change until the infra is improved?

**Comment by rmacnak-google** [comment]
I would give up service tests on Linux ARM64 to get testing at all going on Windows ARM64.

**Comment by dcharkes** [comment]
I'm reapproving:

`vm-aot-linux-release-arm64`
`flaky -> Timeout (expected Pass)`

- service/client_resume_approvals_approve_then_disconnect_test/service
- service/client_resume_approvals_identical_names_test/dds
- service/dominator_tree_vm_test/dds_1
- service/dominator_tree_vm_test/dds_2
- service/dominator_tree_vm_with_double_field_test/dds_1
- service/dominator_tree_vm_with_double_field_test/service_0
- service/dominator_tree_vm_with_double_field_test/service_1
- service/dominator_tree_vm_with_double_field_test/service_2
- service/external_service_synchronous_invocation_test/service
- service/gc_test/dds
- service/gc_test/service
- service/get_object_store_rpc_test/dds
- service/http_get_vm_rpc_test/dds
- service/http_get_vm_rpc_test/service
- service/kill_running_test/dds
- service/kill_running_test/service
- service/regress_45684_test/service
- service/set_vm_name_rpc_test/dds
- service/set_vm_name_rpc_test/service
- service/string_optimized_out_is_not_sentinel_test/service
- service/get_isolate_after_stack_overflow_error_test/service
- service/get_user_level_retaining_path_rpc_test/dds
- service/get_user_level_retaining_path_rpc_test/service
- service/typed_data_test/dds

**Comment by sstrickl** [comment]
Reapproving `flaky -> Timeout (expected Pass)` on `vm-aot-linux-release-arm64` for:
* `service/contexts_test/service`

**Comment by dcharkes** [comment]
Reapproved:

✔ service/dds_disconnects_existing_clients_test/dds
✔ service/dev_fs_weird_char_test/service
✔ service/get_flag_list_rpc_test/dds
✔ service/get_instances_rpc_test/service
✔ service/get_isolate_rpc_test/dds
✔ service/get_supported_protocols_test/dds
✔ service/get_supported_protocols_test/service
✔ service/http_get_isolate_group_rpc_test/dds
✔ service/http_get_isolate_group_rpc_test/service
✔ service/inbound_references_test/dds
✔ service/object_graph_isolate_group_test/service
✔ service/pause_on_unhandled_exceptions_catcherror_test/dds
✔ service/pause_on_unhandled_exceptions_catcherror_test/service
✔ service/reachable_size_test/dds
✔ service/regexp_function_test/dds_0
✔ service/regexp_function_test/service_0
✔ service/regexp_function_test/service_1
✔ service/string_escaping_test/dds
✔ service/string_escaping_test/service
✔ service/vm_service_dds_test/dds

This is getting rather labor intensive.

> I would give up service tests on Linux ARM64 to get testing at all going on Windows ARM64.

@bkonyi thoughts?

**Comment by sstrickl** [comment]
Reapproved:
* service/dev_fs_http_put_weird_char_test/service
* service/dominator_tree_vm_test/dds_1
* service/dominator_tree_vm_with_double_field_test/dds_0
* service/dominator_tree_vm_with_double_field_test/service_0
* service/dominator_tree_vm_with_double_field_test/service_1
* service/dominator_tree_vm_with_double_field_test/service_2
* service/external_service_registration_test/service
* service/get_client_name_rpc_test/service
* service/get_isolate_after_stack_overflow_error_test/service
* service/http_enable_timeline_logging_service_test/service
* service/kill_running_test/dds
* service/reachable_size_test/service
* service/regress_45684_test/dds
* service/string_optimized_out_is_not_sentinel_test/dds
* service/uri_mappings_lookup_test/service

**Comment by sstrickl** [comment]
Reapproving:
* service/custom_stream_listen_test/service
* service/dds_custom_stream_listen_test/dds
* service/get_isolate_after_stack_overflow_error_test/dds
* service/get_ports_rpc_test/dds
* service/get_ports_rpc_test/service
* service/get_retaining_path_rpc_test/dds
* service/object_graph_isolate_group_test/dds
* service/object_graph_isolate_group_test/service
* service/observatory_assets_test/dds
* service/process_service_test/dds
* service/vm_service_dds_test/service
* service/vm_timeline_events_test/service

**Comment by liamappelbe** [comment]
@mkustermann I had to reapprove this timeout again, even though you just increased the timeout multiplier. Thoughts?

**Comment by mkustermann** [comment]
> @mkustermann I had to [reapprove](https://dart-ci.firebaseapp.com/#showLatestFailures=true&configurations=vm-linux-release-arm64) this timeout again, even though you just increased the timeout multiplier. Thoughts?

Here's the impact of my https://github.com/dart-lang/sdk/commit/daa35fd4fd185cb8bad27d719a562a7190475dc8 that restored the timeout multiplier for `vm-linux-release-arm64` to it's original value:

![status](https://github.com/dart-lang/sdk/assets/5757092/1177d830-6061-4a2e-99a0-6b688ee8f2d5)

=> I suspect the majority of the flaky timeouts are gone now for `vm-linux-release-arm64`.

**Comment by dcharkes** [comment]
History of more tests that meta flake here:

* https://dart-ci.web.app/#showLatestFailures=false&test=service/get_allocation_profile_public_rpc_test/dds&configurations=vm-linux-release-arm64
* https://dart-ci.web.app/#showLatestFailures=false&test=service/get_allocation_profile_rpc_test/dds&configurations=vm-linux-release-arm64
* https://dart-ci.web.app/#showLatestFailures=false&test=service/regress_28980_test/dds&configurations=vm-linux-release-arm64

**Comment by derekxu16** [comment]
reapproving service/process_service_test/service, service/set_library_debuggable_test/dds, and service/regress_28443_test/dds

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-linux-release-arm64/732/overview
