### ISSUE TITLE
[Inline class] Error in CFE when calling constant constructor of an inline-class

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52595]
The following code produces an error in CFE
```dart
inline class  V<T> {
  final T id;
  const V(this.id);
}

const c = const V<int>(0); // Error: Static invocation is not a constant expression.
```
There should be no such error
Tested on `Dart SDK version: 3.1.0-155.0.dev (dev) (Fri May 26 19:56:47 2023 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
@johnniwinther, it looks like this compile-time error is reported after the inline constructor invocation has been lowered to a function call. Does this have any serious implications concerning inline classes with constant constructors?

**Comment by johnniwinther** [comment]
It is non-trivial to support but I plan to use the code from the `const-functions` experiment to support this, though.

**Comment by eernstg** [comment]
Great! I expect the ability to have constant expressions whose type is an inline type to be used in practice, and to be desired if it isn't supported.
