### ISSUE TITLE
How to check "RSS" memory high usage (>1GB)? (Willing to PR)

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#52592]
Cross-posted from https://github.com/flutter/flutter/issues/128099, since this also seem to be a devtool problem.

**Comment by a-siva** [comment]
I don't think cross tracking the above issue here adds any value as it is a flutter/devtools request. Maybe the issue above needs to be moved to flutter/devtools repo.

**Comment by fzyzcjy** [comment]
Thank you. Given there are already answers in devtools, I do agree it is an issue there (originally thought this was related to Dart lang)
