### ISSUE TITLE
I encountered a crash issue that may be related to SSL certificates, and I cannot repeat the issue.

### ISSUE THREAD

**Issue by dachongdouniwan** [dart-lang/sdk#52597]
crash stack:

![image](https://github.com/dart-lang/sdk/assets/13745797/f4f9f23a-db30-409e-85d7-f3a7e8b9c4ee)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6.3 21G419 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by dachongdouniwan** [comment]
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001d5fcca98
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  42

**Comment by dachongdouniwan** [comment]
I made a request at 13:06:54 but received no response. 13:06:55 I sent the same request again, and this time the request was successful, but there was a crash.

**Comment by a-siva** [comment]
The information above is not sufficient to debug the problem.
The stack trace indicates a potential memory corruption (SIGSEGV in _objc_release).

If you are able to reproduce the problem consistently or have a complete stack trace when the crash happens (stack trace of all threads in the process) reopen the issue with this information.
