### ISSUE TITLE
[CP] A roll of dart_style which can format empty nullable record types `()?`

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#52591]
### Commit(s) to merge

7c83e8ad4a67cb4cb3d628d59c6df237cae3ee73

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/306911

### Issue Description

The formatter has a bug where a nullable type record with no fields (i.e. `()?`) discards the `?`. The formatter has an internal self-check that it only changes whitespace which fails and the result is that the formatter exits with an error message and doesn't format the file at all.

### What is the fix

The fix is a [trivial one-line change](https://github.com/dart-lang/dart_style/commit/2956b1a705953f880a5dae9d3a0969df0fc45e99) that preserves the `?` if there is one. There are no other changes in this dart_style roll.

### Why cherry-pick

I don't expect nullable empty record types to be very common, but they are valid and meaningful, and without this fix, users are completely unable to format any part of a file that happens to contain `()?`.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/dart_style/issues/1224

**Comment by athomas** [comment]
The current CP CL causes build breakage and can't be landed.

**Comment by munificent** [comment]
Thanks, @itsjustkevin!
