### ISSUE TITLE
Option to generate enum constructor in code action pop-up

### ISSUE THREAD

**Issue by SamuelGadiel** [dart-lang/sdk#52601]
When we create a class we have the option to generate the class constructor by accessing the code actions pop-up and selecting "Create constructor for final fields".

![image](https://github.com/Dart-Code/Dart-Code/assets/22757108/61c80fa4-bba1-4f47-8a91-c9443eb4f566)

Which generates

![image](https://github.com/Dart-Code/Dart-Code/assets/22757108/c9196f1d-aa23-4081-81bb-e45960d9370c)

---

With the introduction of enhanced enums in Dart 2.17 we have the ability of defining attributes to enums, like so

![image](https://github.com/Dart-Code/Dart-Code/assets/22757108/5b88ba0f-1e61-4998-ba02-2487553b114e)

But we have to create the constructor manually since there is no option of generating the constructor using a quick fix in the code actions pop-up

![image](https://github.com/Dart-Code/Dart-Code/assets/22757108/3c5bb4d9-2e87-49d0-911f-2daaea2138a7)

If the given enum have multiple attributes it becomes time consuming to add them all to the constructor.

It would be very helpful to have an option where we can generate the constructor like we do on classes, using the code actions pop-up

---

* Flutter Version (`flutter --version`)
```
Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (10 days ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1
```

* Dart SDK Version (`dart --version`)

```
Dart SDK version: 3.0.2 (stable) (Tue May 23 08:26:58 2023 +0000) on "macos_x64"
```

**Comment by SamuelGadiel** [comment]
Worths mentioning that enums can only have final attributes, and the constructor must be a constant.

![image](https://github.com/Dart-Code/Dart-Code/assets/22757108/d3d0593d-515a-4386-a546-01703a59ef3d)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/307669
