### ISSUE TITLE
`null as T?` described as an "unnecessary cast"

### ISSUE THREAD

**Issue by ryanheise** [dart-lang/sdk#52602]
Given a function with this signature:

```dart
Bar<T> <T>foo(T x)
```

Suppose I instantiate `T` as follows:

```dart
final a = foo(3);
final b = foo(true);
final c = foo("hello");
final d = foo(null as String?);
```

Unfortunately the last one triggers "unnecessary cast".

What I think's going on here is that the lint is simply overzealous. One way to rationalise it is that if I am told that it is an "unnecessary cast", it should be the case that if I delete the cast, the code should still work. But in this case, deleting the cast `d` loses type information that is needed elsewhere in the program. We NEED to add some sort of type information here, and casting is one of the legitimate ways in which we can do this. In the above, I like to consistently infer the parameter type based on the type of the argument rather than by explicitly giving the type parameter to the function, but currently I have to use an inconsistent style on the last line.

Any thoughts on whether this example should really be considered as an unnecessary cast?

**Comment by lrhn** [comment]
The "unnecessary cast" lint doesn't understand type inference. It doesn't try to re-infer the entire program without the cast, to see if it gives the same result. So all it can do is recognize up-casts.
That does give a lot of false positives.

If there is any way for the lint implementation to guess that the type of the expression affects inference (like, it's the argument of a generic function with no type arguments, and the type parameter occurs in the parameter type for the argument), it would be nice to turn off the lint. 
It's probably not possible to completely eliminate false positives.

**Comment by ryanheise** [comment]
Another case would be:

```dart
class Foo {
  var x = null as String?;
}
```

No type parameter on this one, but I guess the commonality between the two cases is that the cast can be assumed to be intentional because it specialises the type of the enclosing term. In the first case via a type parameter, and in this case via `var`.

**Comment by bwilkerson** [comment]
> It's probably not possible to completely eliminate false positives.

Possibly not, but for many years I've been wishing that the analyzer could support a what-if query. It would be great if the lint (and possibly other tools) could find out what the impact of a change, such as removing a cast, would be. The lint could stop reporting any time an inferred type would be different. It's probably too expensive to do this when a global analysis is needed, but it seems like it ought to be both possible and performant when the changes are localized to a single function body or maybe even a single library.

> `var x = null as String?;`

Or you could just write `String? x;`, which I find more readable. Of course, YMMV.

**Comment by ryanheise** [comment]
> > `var x = null as String?;`
> 
> Or you could just write `String? x;`, which I find more readable. Of course, YMMV.

I was just generalising across cases to show the mileage you could get by analysing up to the immediately enclosing term without analysing the entire program.

**Comment by srawlins** [comment]
This unnecessary cast is no longer reported; we changed unnecessary_cast to only report when the cast type is the exact same as the expression's static type.
