### ISSUE TITLE
"gclient sync" on Windows reports "'pipes' is deprecated and slated for removal in Python 3.13"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52605]
I'm planning on trying to use Windows more for some SDK development. Currently when running `gclient sync` I see the following warning:

>Running hooks:  80% ( 8/10) win_toolchain
> ________ running 'python3 sdk/build/vs_toolchain.py update' in 'C:\Dev\Google\dart-sdk'
> C:\Dev\Google\dart-sdk\sdk\build\vs_toolchain.py:17: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
>   import pipes
> Running hooks: 100% (10/10), done.

The line that triggers this is here:

https://github.com/dart-lang/sdk/blob/2a705d8612fbd87e0a86b4bc80408ae9bb95c419/build/vs_toolchain.py#L17

In the top of the file it says:

```
# This file is copied from Chromium:
#   https://cs.chromium.org/chromium/src/build/vs_toolchain.py
# When updating replace reference to python on the first line with python3.
```

It seems that [the copied file](https://cs.chromium.org/chromium/src/build/vs_toolchain.py) has already been updated and is no longer importing `pipes`, however it's not clear to me whether I can just replace this file and open a CL or if there's more to it (there are more differences in the file, such as `TOOLCHAIN_HASH` being different).

This is currently only a warning and not causing any issues, but I presume in some future update of Python it might break.

**Comment by bwilkerson** [comment]
@athomas
