### ISSUE TITLE
prefer_interpolation_to_compose_strings swallows arguments to `.toString()`

### ISSUE THREAD

**Issue by mernen** [dart-lang/sdk#52610]
The following snippet causes a `prefer_interpolation_to_compose_strings` warning:

```dart
String describe(CupertinoDynamicColor color) {
  return 'Color: ' + color.toString(minLevel: DiagnosticLevel.off);
}
```

DartCode/`dart fix` then offers a "Replace with interpolation" fix, which produces:

```dart
String describe(CupertinoDynamicColor color) {
  return 'Color: $color';
}
```

Expected: `.toString()` should only be removed if it has no arguments.

Tested on Dart 3.0.3 (Flutter).

**Comment by scheglov** [comment]
The lint should not be reported, then the fix will not try to fix it :-)
https://github.com/dart-lang/linter/pull/4437

**Comment by mernen** [comment]
I agree that the lint is questionable in this case, but wouldn't that also be true for any other method invocation? (e.g. `'Color: ' + computeColor()`) I consider this lint to be rather aggressive overall. Seems to me like it'd be more consistent to stop suggesting interpolation for any situation where it's just one string literal + any expression that's more complex than a single identifier (`.toString()` call notwithstanding).

Also, what about longer chains? For example:

```dart
'Hello, ' + foo + '! Check out ' + bar.toString(123) + '!'
```

Wouldn't this fix still drop the argument?

**Comment by scheglov** [comment]
It is probably better if you open a separate discussion issue in https://github.com/dart-lang/linter itself.
In general, the lint does what it does, if this is too much, there could be another lint that does less.

As for longer chains, I hope that the fix for the linter that I made works for it too.
But I don't have a specific test for it, TBH.
