### ISSUE TITLE
Can't send record through SendPort

### ISSUE THREAD

**Issue by treeplate** [dart-lang/sdk#52611]
Currently, according to [SendPort.send docs](https://api.dart.dev/stable/3.0.3/dart-isolate/SendPort/send.html), and in practice, a `Record` can't be passed to`SendPort.send`. It would be convenient to be able to do so.

`dart --version: Dart SDK version: 3.1.0-129.0.dev (dev) (Fri May 19 12:10:06 2023 -0700) on "macos_arm64"`

**Comment by a-siva** [comment]
Closing this as a duplicate of https://github.com/dart-lang/sdk/issues/49993
