### ISSUE TITLE
[dart2js] Numeric record type tests give different results at compile time vs. runtime

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#52619]
```dart
@pragma('dart2js:never-inline')
bool test<T>(dynamic x) => x is T;

void main() {
  print(1 is double);
  print(test<double>(1));

  print((1,) is (double,));
  print(test<(double,)>((1,)));
}
```

This prints
```
true
true
false
true
```

cc @rakudrama @biggs0125

**Comment by fishythefish** [comment]
Note that the direct `is` tests are compiled to `print(true)` and `print(false)`. There's probably a bug [here](https://github.com/dart-lang/sdk/blob/526ce3aba48a2e759cbc1b007f7cc84dcf6c850d/pkg/compiler/lib/src/ssa/nodes.dart#LL4349C24-L4349C24) somewhere.

**Comment by sigmundch** [comment]
Thanks @fishythefish!

BTW - I also came across this when debugging this other issue: https://github.com/dart-lang/sdk/issues/52480

**Comment by biggs0125** [comment]
I can take a look at this if no one has started digging in yet!
