### ISSUE TITLE
Repair dart tests that are supposed to run on fuchsia

### ISSUE THREAD

**Issue by tarobins** [dart-lang/sdk#52622]
Dart sdk tests used to run on fuchsia, but no longer do, due to changes in fx and ffx causing the tests to not run.  

In an internal conversation, it was stated

"Changes to fx or ffx broke Dart's limited Fuchsia testing quite some time ago and it has never recovered"

this was in reference to the DuplicateRXVirtualMemory not catching the issue resulting in the rollback https://dart-review.googlesource.com/c/sdk/+/306674.  

We need to get fuchsia testing running again.

This is a list of PRs that fixed the issue in the flutter engine repo https://flutter-review.googlesource.com/q/owner:sebmarchand@google.com+or+owner:mbrase@google.com

I'm willing to help find resources to fix this issue.

**Comment by rmacnak-google** [comment]
Related: b43d95a942d0da95bd02f69433500fce500d1a2a. Though it looks like updating to the latest Fuchsia SDK would remove support for v1 components, therefore breaking `run`, which does not appear to have any v2 replacement.

**Comment by zijiehe-google-com** [comment]
FYI, this folder contains cml definitions we are using in chromium, https://crsrc.org/c/build/config/fuchsia/test/, and v2 uses "ffx test run" with these cml definitions.

**Comment by zijiehe-google-com** [comment]
Finished. Several missing pieces like a dedicated test-realm and rollers for chromium/test-scripts can be done separately.
