### ISSUE TITLE
Move error codes from `dds` to the `vm_service`

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#52636]
`package:dwds` would like to return the same error codes as the `vm_service` (see https://github.com/Dart-Code/Dart-Code/issues/4543 for context)

These error codes are defined in `dart:_vmservice`, which is not public, and then re-defined in dds and observatory. To remove the need for `package:dwds` to also re-define these error codes, we should define them as public constants in package:vm_service and remove the definitions in dds.

**Comment by a-siva** [comment]
//cc @bkonyi @derekxu16

**Comment by derekxu16** [comment]
`package:vm_service 11.7.1` contains @elliette's commit above, so this is complete.

https://pub.dev/packages/vm_service/versions/11.7.1
