### ISSUE TITLE
[CP] Fix nullability of bad cast to FunctionType in pkg/kernel/lib/clone.dart

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#52634]
### Commit(s) to merge

ea8422110024c114174e3ad6a00663ecad3897c1

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/307964

### Issue Description

There is a visitor in the CFE whose job it is to clone AST nodes. `InstanceGetterInvocation` nodes have a `functionType`, but this field is optional. The visitor for this node type had `visitOptionalType(node.functionType) as FunctionType` instead of `as FunctionType?`, so it would crash whenever there was no `functionType`.

This likely affects all platforms. (Edit: This might only be the Flutter web workflow - see Siggi's comment below and the linked issue for details.)

### What is the fix

Change the cast from `as FunctionType` to `as FunctionType?`

### Why cherry-pick

It's a low-risk fix that addresses an obvious bug in the CFE that users cannot work around easily. The code still statically typechecks and any successful cast to `FunctionType` will still be a successful cast to `FunctionType?`.

It fixes the issues users are running into in https://github.com/dart-lang/sdk/issues/52403. (Note the last few comments - users are looking for this to be addressed quickly.)

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52403

**Comment by johnniwinther** [comment]
LGTM
