### ISSUE TITLE
Analysis servers "dart fix" check negatively impacts performance of requests in large workspaces after startup

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52633]
While testing https://github.com/Dart-Code/Dart-Code/issues/4106, I noticed that the first Workspace Symbols query started just after initial analysis completes would take 45s in the Flutter repo. It appears to be held up by the check for whether we should prompt to run "dart fix" which is taking some time.

Removing the "dart fix" check results in the request taking around 5s.

It appears that the time is spent doing analysis, although I familiar enough to know how this work is different to what happened during initial analysis (there are no diagnostics in the whole workspace, so I wouldn't expect any time is spent in checking whether there are actual fixes to be produced), nor why the other requests aren't being handled during `await`s in the fix processing.

@bwilkerson @scheglov I'll do some profiling of this, but FYI.

**Comment by DanTup** [comment]
We end up resolving every library checking this check here:

https://github.com/dart-lang/sdk/blob/80a9e513a7f3e553d19feca570d12ee8a1536ce6/pkg/analysis_server/lib/src/services/correction/bulk_fix_processor.dart#L225

I presume that this is not the same work as is done during initial analysis (since that only takes 4-5s). I think we could make this faster by doing whatever initial analysis does first, and then only resolving the library if there are errors. For ex. something like:

```dart
final errors = await context.currentSession.getErrors(path);
final errorCount = errors is ErrorsResult ? errors.errors.length : 0;
if (errorCount == 0) {
  continue;
}
```

If there are lots of errors, this _could_ result in more work (we're not calling both `getErrors` and `getResolvedLibrary` for some) but I suspect in practice that won't happen.

@scheglov @bwilkerson:

1. Is `getErrors` a reasonable choice here? Is it the fastest way to tell if a library has errors without resolving it?
2. Based on this, am I correct in assuming the data that is cached (and used during initial analysis) contains information about errors, but _not_ enough information to use to produce a resolved library?

**Comment by bwilkerson** [comment]
I don't know whether this is the issue, but the original `dart fix` support on the server side was written to assume that it was only being invoked from the command-line tool, and assumed that the command-line tool wasn't initializing the server in the usual way (via `analysis.setAnalysisRoots`), going so far as to create its own `AnalysisContextCollection`. In hindsight, that was probably a mistake and we probably should have made the command-line tool use a normal pattern of operations.

It's possible, then, that the `dart fix` support we're running on startup is ignoring the analysis results that have already been computed by the server and re-running all of that analysis.

**Comment by DanTup** [comment]
@bwilkerson 

> It's possible, then, that the `dart fix` support we're running on startup is ignoring the analysis results that have already been computed by the server and re-running all of that analysis.

I believe that's not the case here. The code that creates the `AnalysisContextCollection` in that case is in the `EditBulkFixes` handler and as far as I can see, we're correctly using the one from the server here. I think the issue is as @scheglov described which is resolved ASTs not being cached and we're always immediately asking for the resolved library.


@scheglov 

>  if you ask for `getResolvedLibrary ()`, it has to be recomputed, because resolved ASTs are not stored into the cache.

Got it, thanks for confirming :)

> I would made the check for errors more selective, e.g. there might be `TODO`s, that are not fixable.

Yep, I was thinking of that too (because I saw some non-zero counts when testing), I just wanted to check this was the right approach. In a quick test, I still see around 15s though which seems more than the initial analysis. I've got a lot of logging in though, so I'll tidy things up and get some more concrete numbers alongside an implementation to discuss.

**Comment by DanTup** [comment]
> I still see around 15s though which seems more than the initial analysis

This was caused by there being diagnostics that are ignored in analysis_options (so some files were still being resolved). With updated code to also ignore those, it's 0.45s for a clean Flutter repo on my machine.

Some more notes/questions on the CL at https://dart-review.googlesource.com/c/sdk/+/308000.
