### ISSUE TITLE
language/unsorted/flatten_test fails with dart2wasm-linux-chrome (but not with d8)

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#52631]
It looks like the runtime errors are not thrown synchronously, and with Chrome the test ends before throwing the exception.

I'm not sure if the test needs `asyncStart`/`asyncEnd` or this is a dart2wasm issue.

Minimal repro:

```dart
import 'dart:async';

class Derived<T> implements Future<T> {
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

test() async {
  // flatten(Derived<int>) = int
  Future<int> x = (() async => new Derived<int>())();
}

main() {
  test();
}
```

This fails with a runtime error in d8, but passes in Chrome.

**Comment by osa1** [comment]
One explanation why these tests pass with d8 but fail with Chrome can be that we currently use `setTimeout` for scheduling (this will change with https://dart-review.googlesource.com/c/sdk/+/305201), which in d8 does not wait before calling the callback. So some of the async callbacks will be called almost synchronously.

With https://dart-review.googlesource.com/c/sdk/+/305201 we override d8's `setTimeout`, but the new event loop implementation used in d8 waits for all tasks to complete, so these tests will still work as expected with d8 and fail with Chrome because the test driver we use in Chrome does not wait (and has no way to wait) for all events to complete.

**Comment by eernstg** [comment]
Note that the compile-time error in 'language/unsorted/flatten_test.dart' isn't relevant for the behavior of the flatten function, so we might want to delete [line 36](https://github.com/dart-lang/sdk/blob/b8d4b98edd3ae6f87caf7c5a69cf43564bfe9eeb/tests/language/unsorted/flatten_test.dart#L36), or we could rewrite it to use a local function with a declared return type rather than a function literal (like the one in line 35).

**Comment by mkustermann** [comment]
The `language/async/divergent_flatten_test` and `language/nnbd/static_errors/unchecked_use_of_nullable_test` are passing now.

The tests should be using `asyncStart`/`asyncEnd` which I'll do in [cl/368581](https://dart-review.googlesource.com/c/sdk/+/368581)

The issue with test runner not recognizing async tests has been fixed some time ago.
