### ISSUE TITLE
[vm] unexplainable `_boundsCheckForPartialInstantiation`-related performance issues.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#52659]
I am trying to make a program run faster. Unfortunately, according to the flame chart in devtools, `_boundsCheckForPartialInstantiation` takes always at least 12% and I can't find any info on what it does or what I can do to reduce the impact that it has on the performance profile of my program.

The flame chart has the following shape:

<img width="189" alt="Bildschirm­foto 2023-06-09 um 16 38 44" src="https://github.com/dart-lang/sdk/assets/24444584/e99bb121-9b9d-4168-990b-ba14a198b12a">

I understand that it isn't easy to diagnose such a problem without example code, but is there perhaps some general advice on how I can avoid hitting `_boundsCheckForPartialInstantiation`?

```
Dart SDK version: 3.1.0-163.1.beta (beta) (Wed Jun 7 05:06:41 2023 -0700) on "macos_arm64"
```

**Comment by mraleph** [comment]
@modulovalue you have a closure which is a tearoff of a generic method, then you pass use it some context which partially instantiates it. Simple example would be something like:

```dart
class C<T> {
  void foo<S extends T>(S x) {}
}

void main() {
  C<Object> c = C<int>();
  void Function(String) fn;
  fn = c.foo;  // partial instantiation of c.foo tear off
}
```

**Comment by modulovalue** [comment]
Thank you, I think I've found the issue.

I have a hierarchy like the following:

```dart
abstract class Foo_<I, R> {}

abstract class FooFoo_<I, R> implements Foo_<I, R> {}

abstract class FooBar_<I, R> implements Foo_<I, R> {
  I get value;
}

abstract class FooBaz<I, R> implements Foo_<I, R> {
  List<R> get range;

  bool get negated;
}

// ... implementations ...

extension FooMatcherExtension<I, R> on Foo_<I, R> {
  Z match<Z>({
    required final Z Function(
      FooFoo_<I, R> a,
    ) foo,
    required final Z Function(
      FooBar_<I, R> a,
    ) bar,
    required final Z Function(
      FooBaz_<I, R> a,
    ) baz,
  }) {
    final _ = this;
    if (_ is FooFoo_<dynamic, dynamic>) return foo(_ as FooFoo_<I, R>);
    if (_ is FooBar_<dynamic, dynamic>) return bar(_ as FooBar_<I, R>);
    if (_ is FooBaz_<dynamic, dynamic>) return baz(_ as FooBaz_<I, R>);
    throw Exception(
      "Invalid State",
    );
  }
}
```

`match`ing over a `Foo` seems to introduce the _bounds... overhead.

Giving `Foo`s a match method yields no improvement.

I can't quite switch to Dart 3 yet, but I suspect sealed classes & exhaustive pattern matching would help here.

I'll try to use a visitor to see if that helps.

**Comment by modulovalue** [comment]
Finally, using a visitor I was able to fix this.
Thank you for pointing me to look at closures.
