### ISSUE TITLE
Closures over-capture, cannot be sent to other isolate.

### ISSUE THREAD

**Issue by Silfalion** [dart-lang/sdk#52661]
Hello! I'm trying to create a FormData from a Map<String, dynamic> but I'm faced with the error:

```
Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _Future@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)
I/flutter (18310):  <- Instance of '_HttpClientConnection' (from dart:_http)
I/flutter (18310):  <- Instance of '_HashSetEntry<_HttpClientConnection>' (from dart:collection)
I/flutter (18310):  <- _List len:8 (from dart:core)
I/flutter (18310):  <- Instance of '_HashSet<_HttpClientConnection>' (from dart:collection)
I/flutter (18310):  <- Instance of '_ConnectionTarget' (from dart:_http)
I/flutter (18310):  <- Instance of '_HashMapEntry<String, _ConnectionTarget>' (from dart:collection)
I/flutter (18310):  <- _List len:8 (from dart:core)
I/flutter (18310):  <- Instance of '_HashMap<String, _ConnectionTarget>' (from dart:collection)
I/flutter (18310):  <- Instance of '_HttpClient' (from dart:_http)
```

Very sorry, the only code I'm able to share is the following:

`final result = await compute((m)=>exportToFormData(mapOfFields), 'hi');

The function returns a Future<FormData>.

I'm not able to share much more, but the case is very similar to this one(which has a code sample):

https://github.com/flutter/flutter/issues/126520

**Comment by lrhn** [comment]
This sounds like your closure is over-capturing, which is a known problem with the VM's implementation of closures.
Try moving the creation of the closure into another, function, say:

```dart
// Declared somewhere, top-level or static.
Future<WhateverItIs> _computeExport(Map<String, String> data) => compute((_) => exportToForm(data), 'hi');
...
  // Then use as:
  final result = await _computeExport(mapOfFields);
```

**Comment by Silfalion** [comment]
Got it, will give it a shot. Thank you

**Comment by mkustermann** [comment]
We have an older open issue regarding the over-capturing of closures. Will close this in favor of https://github.com/dart-lang/sdk/issues/36983.
