### ISSUE TITLE
VM's RegExp FormatException message needs more space

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#52691]
Example:
```dart
void main() {
  try {
    var re = RegExp(r'[c-');
  } on FormatException catch (e, s) {
    print(e);
  }
}
```
prints
```
FormatException: Unterminated character class[c-
```
There should be a space between the message "Unterminated character class" and the source "\[c-".
(Goes for any format exception, not just unterminated character classes.)

Noticed externally at https://stackoverflow.com/questions/76461164/poor-formatting-for-regexp-format-exception

**Preferably** change the error reporting to use more parameters of the `FormatException` constructor. Pass the source as seconds argument, the position of the error as third (if available), instead of concatenating the source into the message. Then it would print as:
```dart
print(FormatException("Unterminated character class", "[c-", 3));
// FormatException: Unterminated character class (at character 4)
// [c-
//    ^
```

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/312348
