### ISSUE TITLE
Platform.localHostname fails on Chinese Windows 

### ISSUE THREAD

**Issue by nielsenko** [dart-lang/sdk#52701]
```dart
final hostname = Platform.localHostname
```
fails with:
```
Dart Error: Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
```
on Chinese Windows (Chinese GB2312). See also: https://github.com/flutter/flutter/issues/111957 and https://github.com/realm/realm-dart/issues/1319.

Seen on on Flutter 3.10.4, ie. Dart 3.0.3.

I couldn't find any open issues on this, so here you have it.

**Comment by rmacnak-google** [comment]
@brianquinlan @aam

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/320620 reverts the change

**Comment by parlough** [comment]
@aam Can this be closed as fixed now that https://github.com/dart-lang/sdk/commit/35c6cc6234034c58a6af366048d43c4a16358f8f relanded your change?

**Comment by aam** [comment]
Yes, it can.
