### ISSUE TITLE
Null safe on higher order functions in arrays

### ISSUE THREAD

**Issue by Isakdl** [dart-lang/sdk#52712]
There are a few situations where the null safety checks of the analyzer fail to do it's job and we are forced to opt out of the check by using `!`.

It would be nice if the analyzer could know that the values are not able to be null.

Example: 

```dart
class A {
  String? text;
}

var list = <A>[];
list.where((e) => e.text != null).map((e) => e.text.length);
```

The above does not work as it still thinks text can be null. Instead you have to write:

```dart
list.where((e) => e.text != null).map((e) => e.text!.length);
```

I believe the first example should be considered valid as we already have done a null check.

This tracker is for issues related to:
* Analyzer

Platform:
* Dart SDK version: 3.0.2 (stable)
* MacOSX

**Comment by eernstg** [comment]
This would not be sound:

```dart
bool b = false;

class B extends A {
  String? get text => (b = !b) ? super.text : null;
}
```

Check out https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion.
