### ISSUE TITLE
Very slow compilation of large method in AOT compiler due to non-linear algorithm

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#52719]
The `corelib_2/regexp/pcre_test` has a very large `main()` function which causes the test to flakily timeout.

It seems `gen_snapshot` spends minutes compiling just the `main()` function.  The reason seems to be that for `O(instructions-of-block)` we perform the `instr->GetBlock()` - which is again a `O(instructions-of-block)` algorithm, making this quadratic.

We could e.g. consider breaking blocks with very large number of instructions into multiple blocks to avoid this.

/cc @mraleph @alexmarkov

**Comment by alexmarkov** [comment]
Duplicate to https://github.com/dart-lang/sdk/issues/21708.
