### ISSUE TITLE
Bug: Directory watch stream can't be cancelled.

### ISSUE THREAD

**Issue by sidetraxaudio** [dart-lang/sdk#52718]
Testing on Windows 11

```
Directory dir= Directory(Directory.current.path);
    dir.watch().listen((event) {
      print(event);
    });
    await dir.watch().listen((_) {}).cancel();
```
The above code still emits print events from the directory watch stream even after cancelling.
Secondarily, unless I'm approaching this wrong, which may be the case, directory streams are lack-lust at best and could really use some more helpers. Iterating changing lists of directories to watch for changes in order to trigger UI updates (as is the case in many desktop scenarios) is not the best. A cancel streams by path helper would be great. Iterating a list of directories to create watchers and then dispose of them is hard as each instance of a directory is unique despite paths being the same. I've mitigated this by managing a list of directory objects, yet can't find any way of cancelling them as per above bug. This creates a million watchers triggering a million events.

**Comment by lrhn** [comment]
The way to cancel a Dart stream subscription requires you to remember the subscription object.

Here there are two subscriptions performed (two calls to `listen`), but only one of them is cancelled.
The other subscription keeps receiving events independently.
Try:
```dart
    Directory dir = Directory(Directory.current.path);
    var subscription = dir.watch().listen(print);
    await subscription.cancel();
```

**Comment by sidetraxaudio** [comment]
Thank you Irhn. Closing issue.

FYI for future viewers - the stream object itself exists independently and needs to be tracked independent of the directory object. Calling directory.listen().watch() creates a new independent stream object and can't be used to control any other prior stream object. Makes sense retrospectively.

**Comment by lrhn** [comment]
To be precise: 
A `Stream` itself is an inert object which doesn't do anytning by itself. It shouldn't do anything, or start allocating any resources, until it's listened to.

When you listen to a stream, you create an _active_ `StreamSubscription`, backed by code which can generate events, and the subscription stays active until the stream closes or the subscription is `cancel`'ed.

(Caveat: Some *streams* are backed by other resources from the start, like an HTTP request response body, and should be disposed of to release the underlying resource. Most streams should not be like that.)
