### ISSUE TITLE
Unexpected `InvalidType` encountered in TFA summary builder

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#52720]
There are new test failures on [[co19] Roll co19 to ac0e211921396919cd8893a6de53d433ec663b95...[analyzer] Plug "temporary leak" when starting new rebuilds before `afterContextsCreated` is called](https://github.com/dart-lang/sdk/compare/5e08794bbfc2c57b5b0522c6e2b22b419f6aa115~...e41550d587584672cec846c719167945c8e6929b).

The tests
```
co19/LanguageFeatures/Inline-classes/composing_inline_classes_A05_t05 DartkCrash (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-simarm64
vm-aot-linux-release-x64
vm-aot-win-release-x64
```

/cc @alexmarkov

**Comment by alexmarkov** [comment]
TFA crashes because `instantiatedRepresentationType` for `V3` returns `InvalidType`.

Dart:
```
inline class V3 {
  num foo() => 42;
}
```

Kernel:
```
  inline class V3 /* declaredRepresentationType = invalid-type */ {
    method foo = com::V3|foo;
    tearoff foo = com::V3|get#foo;
  }
```
```
  static inline-class-member method V3|foo(lowered final com::V3 #this) → core::num
    return 42;
```

Spec:
> A compile-time error occurs if the inline class does not declare any instance variables, and if it declares two or more instance variables.

So this test should result in a compile-time error.

**Comment by alexmarkov** [comment]
Corresponding co19 issue: https://github.com/dart-lang/co19/issues/2090.

**Comment by chloestefantsova** [comment]
It seems that the CFE now reports compile-time error for that test case, both with the words `inline class` and `extension type` before `V3`. @mkustermann, can this issue be closed now?
