### ISSUE TITLE
dump_kernel.dart  run error

### ISSUE THREAD

**Issue by GvcZhang** [dart-lang/sdk#52735]
When i use latest dart to run dump_kernel.dart, it reports follow error:
<img width="1207" alt="image" src="https://github.com/dart-lang/sdk/assets/45255699/9b4bac6c-5ccc-472d-8035-0ab3871e7740">

Is it a problem with my use？

**Comment by zhangshuqi** [comment]
请问下 您是怎么解决的? 我也遇到了这个问题
