### ISSUE TITLE
Deprecate analysis_options_user.yaml

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#52741]
This is the analyzer implementation issue for https://github.com/flutter/flutter/issues/82948.

Flutter is basically asking that we drop support for `analysis_options_user.yaml`. It is likely that the existing `analysis_options_user.yaml` file is so outdated that it hardly provides any value, and we don't even need to issue a warning that analysis is falling back to this outdated file.

CC @goderbauer

**Comment by srawlins** [comment]
CC @bwilkerson @scheglov I'd like to drop this support soon. And I agree with what I wrote a few months ago that we don't even need to provide a warning. Dropping it will reduce the scope of the project, simplify the world, and reduce our tech debt. 😁  Let me know if you object to simply dropping support.

**Comment by scheglov** [comment]
No objects from me.

**Comment by goderbauer** [comment]
Let's drop it!

**Comment by bwilkerson** [comment]
No objection.
