### ISSUE TITLE
package:dart_internal is not supported on current dev releases

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#52742]
Its environment constraint forbids `3.1.0`.

https://github.com/dart-lang/sdk/blob/main/pkg/dart_internal/pubspec.yaml

CC @natebosch @munificent @devoncarew who have bumped it before.

I don't know what the requirement is for bumping the upper limit except something like "it's getting close and we haven't removed dependencies on it."

**Comment by munificent** [comment]
I'll bump the constraint and publish a version today.
