### ISSUE TITLE
Analyzer incorrectly identifies 'The relational pattern expression must be a constant.'

### ISSUE THREAD

**Issue by mrcsh** [dart-lang/sdk#52740]
* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

- Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "linux_x64"
- Running on Linux
- n/a

I am using the new switch expressions and dart analyze produces the following output, which does compile and run correctly.
```
Analyzing common...                    2.7s

  error • lib/widgets/render_helpers.dart:99:18 • The relational pattern
          expression must be a constant. Try using a constant instead. •
          non_constant_relational_pattern_expression
  error • lib/widgets/render_helpers.dart:99:27 • The relational pattern
          expression must be a constant. Try using a constant instead. •
          non_constant_relational_pattern_expression
  error • lib/widgets/render_helpers.dart:100:18 • The relational pattern
          expression must be a constant. Try using a constant instead. •
          non_constant_relational_pattern_expression
  error • lib/widgets/render_helpers.dart:100:27 • The relational pattern
          expression must be a constant. Try using a constant instead. •
          non_constant_relational_pattern_expression
  error • lib/widgets/render_helpers.dart:101:18 • The relational pattern
          expression must be a constant. Try using a constant instead. •
          non_constant_relational_pattern_expression
  error • lib/widgets/render_helpers.dart:101:27 • The relational pattern
          expression must be a constant. Try using a constant instead. •
          non_constant_relational_pattern_expression

6 issues found.

```

for the following code.

```
Uint8List.fromList([
      ...id.codeUnits
          .map(
            (final ch) => switch (ch) {
              >= $0 && <= $9 => ch - $0,
              >= $a && <= $f => 10 + ch - $a,
              >= $A && <= $F => 10 + ch - $A,
              _ => -1,
            },
          )
          .where((final ch) => ch != -1)
    ]
```

The $X are constants defined in package:charcode/ascii.dart

The code compiles and runs fine so it appears the analyzer is just wrong.

The even odder thing is that the errors are not consistent. Sometimes they go away.  I changed the >= $0 to >= 0x30 and they went away and then I put back the >= $0 and they stayed gone.  

If I can determine what's changing to cause the "errors", I will update the issue.

**Comment by keertip** [comment]
@mrcsh , I was not able to reproduce the issue. The code analyzes with no errors in the IDE.  Are you analyzing running  `dart analyze` on  command line?

**Comment by nex3** [comment]
This occurs _only_ when the constant is loaded through an `import`. Here's a minimal reproduction:

```dart
// other.dart
const int $a = 0x61;
```

```dart
// test.dart
import 'other.dart';

void main() {
  if (1 case <= $a) print("less than a");
}
```

```
$ dart --version
Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "linux_x64"
$ dart analyze test.dart
Analyzing test.dart...

  error - test.dart:4:16 - The relational pattern expression must be a constant. Try using a constant instead. -
          non_constant_relational_pattern_expression

1 issue found.
```

**Comment by mrcsh** [comment]
> 

I am seeing the errors both in ide (AS and vscode) and dart analyze from the command line.

**Comment by ciripel** [comment]
I have the same issue. just modifying a little the file and then back make the error disappear. The issue is with CI/CDs because analyze just fail there, u run it again and sometimes just work.

**Comment by bwilkerson** [comment]
@scheglov
