### ISSUE TITLE
[Analyzer] wrong error if inline class redeclares a member

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52781]
If inline class has a superinterface with a member `m` and redeclares this member it is not an error even it is not a correct override for a regular class. But analyzer reports an error in this case. For example

```dart
inline class V {
  final int id;
  V(this.id);

  int foo() => 0;
}

inline class C1 implements V {
  final int id;
  C1(this.id);

  num foo() => 1; // Analuzer: 'C1.foo' ('num Function()') isn't a valid override of 'V.foo' ('int Function()'). • invalid_override
}

main() {
  print(C1(42).foo());
}
```
The code above fail in analyzer but has no issues in CFE. There shouldn't be an error in analyzer as well. [Specification link](https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md#:~:text=With%20inline%20classes%2C%20any%20member%20signature%20can%20redeclare%20any%20other%20member%20signature%20with%20the%20same%20name%2C%20including%20the%20case%20where%20a%20method%20is%20redeclared%20by%20a%20getter%2C%20or%20vice%20versa)

> With inline classes, any member signature can redeclare any other member signature with the same name, including the case where a method is redeclared by a getter, or vice versa. 

This issue, for example, causes failure of https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Inline-classes/composing_inline_classes_A05_t06.dart

Tested on the edge sdk on Linux x64 and on `Dart SDK version: 3.1.0-227.0.dev (dev) (Sun Jun 18 18:21:21 2023 -0700) on "windows_x64"`

**Comment by lrhn** [comment]
Does not appear to be an issue for extension types as released.
