### ISSUE TITLE
Failures on [vm] Add support for hash-based caches in SubtypeNTestCache stubs.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52787]
There are new test failures on [[vm] Add support for hash-based caches in SubtypeNTestCache stubs.](https://github.com/dart-lang/sdk/commit/f7e26c508d27b89c5cdb269480d54550b31b7370).

The tests
```
vm/dart/regress_48523_test Timeout (expected Pass)
```
are failing on configurations
```
vm-reload-linux-debug-x64
```

Bisected locally. Goes from 1 minute to over 4 minutes for this test.

edit: repro command: `tools/test.py --build -n vm-reload-linux-debug-x64 vm/dart/regress_48523_test`

**Comment by dcharkes** [comment]
06e099884b46f23761b6ce351384aee6df204a97 still times out for me.

I have approved the failure. Could you please take a look at it @sstrickl ?

**Comment by sstrickl** [comment]
Will do, thanks for the heads up!
