### ISSUE TITLE
[analyzer] Incorrect documentation for `FunctionType` parameters

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#52780]
`FunctionType` [parameters](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/dart/element/type.dart#L248) documentation state that the parameters have the same order as in the declaration, but in the implementation parameters actually [get sorted](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/dart/element/type.dart#L110).

**Comment by incendial** [comment]
Also, I'm curious why you decided to sort them, can someone share the reason behind it?

**Comment by bwilkerson** [comment]
Yes, the comment needs to be updated.

I believe the reason for the sorting was to make it faster to compare two function types for supertype/subtype relationships. The order of the named parameters isn't important, just the presence or absence of a given name, so having them in a canonical order improves performance.

**Comment by incendial** [comment]
Got it, thanks!
