### ISSUE TITLE
Stdin not supporting multibytes chars

### ISSUE THREAD

**Issue by tratteo** [dart-lang/sdk#52788]
### Version
```
Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "windows_x64"
```
### Problem
The `stdin` and in particular the method `stdin.readByteSync()` is not working as expected when dealing with **multibytes** char.
Due to this problem, other packages are being affected as well.
- [interact](https://github.com/frencojobs/interact/issues/13#issuecomment-1605585579)

**Example**
Tested on Win11 and Ubuntu, when typing _diacritic accent_ `à`, the method returns **0** on Win11 and **13** on ubuntu, causing unexpected behaviour.

### Expected behaviour
The expected behaviour is to handle correctly all multibytes chars as listed in the [utf8 table](https://www.utf8-chartable.de/).

**Comment by rmacnak-google** [comment]
`readByteSync` deals with **bytes**. If the caller wishes to interpret the bytes as characters, code points or code units, the caller will have to perform the decoding.

**Comment by Martoxdlol** [comment]
It works differently on linux than on windows
![image](https://github.com/dart-lang/sdk/assets/35405382/db388ab8-7e7e-4503-af2c-a3998815d411)

The first byte shouldn't be 0. (I think so)
