### ISSUE TITLE
Add an IDE refactor to convert switch syntaxes

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#52798]
Currently, a `switch` can be written in two different ways:

An expression:

```dart
return switch (obj) {
  Type() => 'hello world',
};
```

A statement:

```dart
switch (obj) {
  case Type():
    return 'hello world';
}
```

It is quite common to want to switch between one or the other. Such as for example, initially writing the `=>` syntax. But refactoring to the `case` syntax because some cases need more than one expression

But although the syntaxes look similar, there are tons of small differences. This makes the refactoring very painful.

Could a quick-fix be added to automate this?

**Comment by bwilkerson** [comment]
We already have a refactoring for some structures of switches. For example, given a file containing
```dart
int f(int i) {
  switch (i) {
    case 0:
      return 0;
    case 1:
      return 1;
    default:
      return 2;
  }
}
```
Positioning the cursor in the `switch` keyword will produce a refactoring to "Convert to switch expression". The inverse is also supported.

The current refactorings are, however, somewhat limited in the sense that they will only be offered when the code matches a pattern we know how to convert (without changing the semantics or introducing errors). If you remove the `default` from the example above the refactoring is no longer offered because we can't produce valid code.

Are there other code patterns that the refactorings should support?

**Comment by rrousselGit** [comment]
I've tried multiple time using assists to see if one was available, but never saw one.

So either my dart version is somehow out of date, or the current one is probably too limited.

One issue is that it's unclear to me what exactly causes the assist to not show up. In that sense, the discoverability of the feature is poor, and it may be missing important use cases. I'll see if I can make a compilation of the cases I'd need.

**Comment by bwilkerson** [comment]
> I've tried multiple time using assists to see if one was available, but never saw one.

Do you see the assist using the code I posted above?

> I'll see if I can make a compilation of the cases I'd need.

Thanks, that would be very helpful.

**Comment by rrousselGit** [comment]
I do see it. Although surprisingly, it appears after the "convert to if chain" refactor, which is likely way less useful overall.   
Anyway, I'll investigate why I didn't see it before.


Although I would say, in the case of a missing default you described earlier: IMO the refactor should still be offered.

Users of pattern-matching very much desire compilation errors. I would treat an "unhandled case" error differently than a "missing variable identifier" error.

Alternatively, the refactor could generate a throwing default case:

```dart
// TODO handle default
_ => throw UnimplementedError(),
```

Or if the switch could be exhaustive, it could rely on the "add missing cases" fix to generate all the missing cases. 

I would assume that that's what people most likely want. Worst-case scenario, they can `ctrl+z` or delete the unwanted cases, but I would assume that it would be fairly rare

**Comment by rrousselGit** [comment]
> ```dart
> int f(int i) {
>   switch (i) {
>     case 0:
>       return 0;
>     case 1:
>       return 1;
>     default:
>       return 2;
>   }
> }
> ```

Is this refactor dependent in any way on the installed packages?  

I tried this in a different project from the one where I tried earlier, and the refactoring doesn't show up.
I didn't change my Dart version in the meantime, so I don't see an obvious reason for this.

**Comment by bwilkerson** [comment]
> Is this refactor dependent in any way on the installed packages?

Not to the best of my knowledge.

It _is_ dependent on the language version (we won't suggest converting a switch statement into a switch expression in a library that's pre-3.0), but I don't see anything in [the code](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/dart/convert_to_switch_expression.dart) that would suggest any other reason for it not showing up (other than the already stated possibility that the code doesn't match the heuristics used to decide how to do the conversion.

**Comment by rrousselGit** [comment]
There's something fishy going on then. Because in [Freezed on the branch "ast"](https://github.com/rrousselGit/freezed/tree/ast), I've been using pattern-matching. Yet when copy-pasting the code in my project, the lint fails to appear.

I'm not really sure what causes this.

**Comment by FMorschel** [comment]
Hey @rrousselGit. I did found this only today and it is relatively old. Have you been able to reproduce any cases that the assist doesn't cover? I also found https://github.com/dart-lang/sdk/issues/52958 that is opened but as I stated there:

> I believe this specific ask was already solved by https://github.com/dart-lang/sdk/issues/54567. I also created my request to it https://github.com/dart-lang/sdk/issues/55861 missing both.
> 
> Current related issues that I know of (1 request to separate the assist to merge the cases and 2 bugs with the current assist respectively):
> 
> - https://github.com/dart-lang/sdk/issues/56180
> - https://github.com/dart-lang/sdk/issues/56597
> - https://github.com/dart-lang/sdk/issues/56602
> 
> There are also some other issues I created related to the formatter and some suggested lints all linked to the above issues.

**Comment by rrousselGit** [comment]
I think that's fixed now
