### ISSUE TITLE
[CP] [vm] Fix leakage of file system watcher related data structures

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#52793]
### Commit(s) to merge

3dd9389c1ff84fd48ba8cb69536c9bdfc07ea20f

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/311521

### Issue Description

Without this fix, there is a bad leak of `_Closure` objects when using overlapping `Directory.watch` streams. This change switches a `Stream.pipe` usage to `Stream.listen`, and cancels subscriptions.

### What is the fix

The fix is to change how these watch events are listened to, and canceling subscriptions.

### Why cherry-pick

This memory leak can be very prevalent in the Dart analyzer, and memory usage (including leaks) is a top issue for users of Dart analyzer.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52703

**Comment by a-siva** [comment]
lgtm

**Comment by itsjustkevin** [comment]
> We might want to cherry pick [8b6e396](https://github.com/dart-lang/sdk/commit/8b6e39696f434e63e8684d9a920062d62cc8054f) as well.

@srawlins should we also be picking the commit @mraleph mentioned above before merging this cherry-pick?

**Comment by srawlins** [comment]
> should we also be picking the commit @mraleph mentioned above before merging this cherry-pick?

[8b6e396](https://github.com/dart-lang/sdk/commit/8b6e39696f434e63e8684d9a920062d62cc8054f) was landed recently, so we would want to land this (https://github.com/dart-lang/sdk/commit/3dd9389c1ff84fd48ba8cb69536c9bdfc07ea20f) cherry-pick first. After a quick evaluation, cherry-picking [8b6e396](https://github.com/dart-lang/sdk/commit/8b6e39696f434e63e8684d9a920062d62cc8054f) helps with this memory theme as well.
