### ISSUE TITLE
Breakpoints should be re-established on hot restarting an app

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#52794]
Breaking this issue out from https://github.com/flutter/devtools/issues/5265

For VM apps, hot-restarting an application causes the breakpoints to disappear. That's because the pre-existing breakpoints aren't set on the isolate we get back from the call to `getIsolate`. 

This isn't affecting web apps. DWDS re-establishes breakpoints here: https://github.com/dart-lang/webdev/blob/8360d50ff889f3c0f817d4d48d3aebd71345cf5d/dwds/lib/src/services/chrome_proxy_service.dart#L280-L283, the VM service should so something similar.

**Comment by a-siva** [comment]
> This isn't affecting web apps. DWDS re-establishes breakpoints here: https://github.com/dart-lang/webdev/blob/8360d50ff889f3c0f817d4d48d3aebd71345cf5d/dwds/lib/src/services/chrome_proxy_service.dart#L280-L283, the VM service should so something similar.

How does DWDS deal with changes to the source that make the previous breakpoint locations incorrect or arbitrary, especially in cases when the source changes are substantial?

**Comment by a-siva** [comment]
//cc @derekxu16

**Comment by elliette** [comment]
DWDS is using the Chrome DevTools Protocol [`Debugger.setBreakpointByUrl`](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setBreakpointByUrl) API method, which persists breakpoints across page reloads. 

- More details are in this issue: https://github.com/dart-lang/webdev/issues/1076
- And in the PR that added this functionality: https://github.com/dart-lang/webdev/pull/1078#issuecomment-668078923

**Comment by a-siva** [comment]
I don't think it is a good idea for the VM to try and automatically re-establish breakpoints after a hot-restart, the sources could have changed in manner that makes it hard to map existing breakpoints back to appropriate locations in the new source base. The IDE tools (editors) have better context of this should be able to do a better job. As suggested in one of the comments above it probably makes sense for the tools to get the existing breakpoints and then map them to appropriate locations after the changes and re-establish the breakpoints after a restart.
