### ISSUE TITLE
Improve `DynamicLibrary.open`'s error messages

### ISSUE THREAD

**Issue by loic-sharma** [dart-lang/sdk#52790]
## Background
Many [pub packages bundle pre-built libraries](https://github.com/pbo-linaro/flutter-apps-with-dll/blob/master/all_dll.csv), including many Flutter Windows plugins that assume an AMD64 architecture.

Flutter is [adding support for Windows Arm64](https://docs.google.com/document/d/1yuexY-EtzeVhU3V6RGBII_kH-znLSkQCspzW70jayZk/edit?usp=sharing&resourcekey=0-8pQRSXSHQlwOo7QtCVLvBA). Windows Arm64 users will receive runtime exceptions until these Windows plugins are updated to support Windows Arm64. It is important these exceptions have useful error messages to minimize the pain of this migration.

## Problem

The errors produced by `DynamicLibrary.open` are difficult to understand:

```dart
import 'dart:ffi';

void main(List<String> arguments) {
  var path = 'C:/path/to/library.dll';
  DynamicLibrary.open(path);
}
```

<details>
<summary>Exception if opening a library that does not exist...</summary>

```
Invalid argument(s): Failed to load dynamic library 'C:/path/to/library.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main (file:///C:/Code/f/tests/x35/bin/x35.dart:5:18)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```
</details>

<details>
<summary>Exception if opening an Arm64 library on an AMD64 machine...</summary>

```
Invalid argument(s): Failed to load dynamic library 'C:/Users/sharm/Downloads/flutter_debee7cece49607b0ee8bb28a3368d049f8929ba_windows-arm64-debug_windows-arm64-flutter/flutter_windows.dll': error code 193
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main (file:///C:/Code/f/tests/x35/bin/x35.dart:7:18)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

</details>

Dart SDK Version: `Dart SDK version: 3.1.0-246.0.dev (dev) (Fri Jun 23 01:04:39 2023 -0700) on "windows_x64"`

### Proposal
Ideally these error messages should give more information about **what** the problem is. For example:

> Library does not exist.

> Cannot open Arm64 library on an AMD64 process.

/cc @dcharkes

**Comment by Levi-Lesches** [comment]
My code running on WSL threw
```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'libserialport.so': libserialport.so: cannot open shared object file: No such file or directory
```
But this didn't print or return
```dart
  final file = File("libserialport.so");
  if (!file.existsSync()) {
    print("CANNOT FIND FILE");
    return;
  }
```

**Comment by Levi-Lesches** [comment]
I deleted this comment earlier because I thought I fixed it, but turns out I did not
```dart
final file = File("libserialport.so");
if (file.existsSync()) {
  final lib = DynamicLibrary.open("libserialport.so");
}
```
Outputs: 
> Invalid argument(s): Failed to load dynamic library 'libserialport.so': libserialport.so: cannot open shared object file: No such file or directory

No error code, but the file clearly exists

**Comment by dcharkes** [comment]
Could you try with the full file path? The current working directory being used by `dart:io` is not the same as the `LD_PATH` (or Windows equivalent of the loading path) that C uses when loading dynamic libraries.

Also, are you trying to load a dylib from outside the sandbox? https://github.com/flutter/flutter/issues/114641

**Comment by Levi-Lesches** [comment]
Thanks, can confirm that setting `LD_LIBRARY_PATH` fixed the issue on Linux, and there was no issue at all on Windows. Also loading with a full path did work.

So I guess `LD_PATH` and `LD_LIBRARY_PATH` should go somewhere in the error message, or at least the docs. I believe on Windows, the regular `PATH` is often enough to make things work.

**Comment by simolus3** [comment]
I've changed this to use `FormatMessageA` in https://dart-review.googlesource.com/c/sdk/+/328420
