### ISSUE TITLE
[CP] Clear watcher subscriptions to avoid leaking package:watcher data

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#52791]
### Commit(s) to merge

5aee0f61b6301099bb25a36d2b2ff197541d3c5b

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/311466

### Issue Description

Prior to this fix, there is a fairly significant memory leak in the Dart analyzer that increases used memory when edits to a pubspec.yaml file are made. This fix closes the leak.

### What is the fix

The fix is to cancel subscriptions more aggresively.

### Why cherry-pick

This memory leak represents a big area of complaint for existing users.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52447

**Comment by srawlins** [comment]
How we doin?

**Comment by mit-mit** [comment]
SGTM

**Comment by srawlins** [comment]
Thanks much!
