### ISSUE TITLE
False positive in unreachable_switch_case

### ISSUE THREAD

**Issue by DenchiUA** [dart-lang/sdk#52800]
```dart
enum MyEnum {first, second}

typedef MyData = (
  MyEnum field1,
  MyEnum field2,
);

void main() {
  print(myFn(MyEnum.first, null));
  print(myFn(MyEnum.first, MyEnum.second));
}

MyData? myFn(MyEnum field1, MyEnum? field2) {
  return switch ((field1, field2)) {
    final MyData a => a,
    _ => null,
    // ^ unreachable_switch_case
  };
}
```

If you remove this line, dart will throw an error.

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
What error do you get?
For me, this example prints (with `_ => null,`) commented out
```
null
(MyEnum.first, MyEnum.second)
```
It looks as a bug to me as well, but I'm curious what specifically you see.

**Comment by DenchiUA** [comment]
```dart
enum MyEnum {first, second}

typedef MyData = (
  MyEnum field1,
  MyEnum field2,
);

void main() {
  print(myFn(MyEnum.first, null));
  print(myFn(MyEnum.first, MyEnum.second));
}

MyData? myFn(MyEnum field1, MyEnum? field2) {
  return switch ((field1, field2)) {
    final MyData a => a,
    //     _ => null,
    // ^ unreachable_switch_case
  };
}
```

Linter tells us, "This case is covered by the previous cases. (view docs).
Try removing the case clause, or restructuring the preceding patterns."

If we remove `_ => null`, the linter stops swearing (although it should tell us that we have not covered all cases) 

We can run the code and get an error if we pass null to the second argument of a function
```
Uncaught TypeError: Cannot read properties of null (reading 'toString$0')
Error: TypeError: Cannot read properties of null (reading 'toString$0')
```
That is, in this case it believes that the type 
`(MyEnum field1, MyEnum? field2) === MyData`

When MyData field2 cannot be null

**Comment by DenchiUA** [comment]
Earlier I thought the problem was only with enum. But there is the same problem with String. 

```dart
typedef MyData = (
  String field1,
  String field2,
);

void main() {
  print(myFn("first", null));
  print(myFn("first", "second"));
}

MyData? myFn(String field1, String? field2) {
  return switch ((field1, field2)) {
    final MyData a => a,
    /// We can delete this line and linter will not give us an error. 
    /// I'm expecting an error like non_exhaustive_switch_expression
    _ => null, 
    // ^ unreachable_switch_case
  };
}
```

**Comment by scheglov** [comment]
This might be a bug in the shared exhaustiveness analysis.
Or, at least, I don't understand why we are doing this.
My expectation looking at `isSubtypeOfInternal`, is that it should match types of record fields.
@johnniwinther 

<img width="883" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/0b8fe608-3e82-4652-a253-d13796724eda">
