### ISSUE TITLE
Failed to build "test" package executable with _fe_analyzer_shared v62.0.0

### ISSUE THREAD

**Issue by sitaram-kalluri** [dart-lang/sdk#52815]
When running "dart run test" observed the following errors

```
Building package executable... 
Failed to build test:test:
../../../../../../.pub-cache/hosted/pub.dev/_fe_analyzer_shared-62.0.0/lib/src/macros/executor/arguments.dart:52:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../../../../../.pub-cache/hosted/pub.dev/_fe_analyzer_shared-62.0.0/lib/src/macros/executor/arguments.dart:52:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @mustBeOverridden
   ^
Failed to build test:test:
../../../../../../.pub-cache/hosted/pub.dev/_fe_analyzer_shared-62.0.0/lib/src/macros/executor/arguments.dart:52:4: Error: Undefined name 'mustBeOverridden'.
  @mustBeOverridden
   ^^^^^^^^^^^^^^^^
../../../../../../.pub-cache/hosted/pub.dev/_fe_analyzer_shared-62.0.0/lib/src/macros/executor/arguments.dart:52:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
```
Version Info:
-----------------
OS: Linux
Dart SDK version - 3.0.5
test package: 1.22.1 (Upgraded the dependency version to 1.24.4 and still the issue exists)

Work Around:
------------------
As a work around, pinning the "_fe_analyzer_shared" dependency version to 61.0.0 resolves the issue.

**Comment by devoncarew** [comment]
I'm not sure if we triage the `area-test` area in the sdk repo. cc @natebosch 

@sitaram-kalluri - did running `dart pub upgrade` work for you?

**Comment by natebosch** [comment]
This isn't related to the test package. The latest `_fe_analyzer_shared` is only compatible with the latest `meta` but does not currently restrict it.

A `dart pub upgrade` is the correct solution to this problem.
We could consider retracting the published version of `_fe_analyzer_shared`, but I don't know if it is necessary.

https://dart-review.googlesource.com/c/sdk/+/311925 will fix the dependency for versions of the package going forward.

**Comment by sitaram-kalluri** [comment]
> I'm not sure if we triage the `area-test` area in the sdk repo. cc @natebosch
> 
> @sitaram-kalluri - did running `dart pub upgrade` work for you?

Running `dart pub upgrade` did not resolve the issue. 

Before executing `dart pub upgrade`, the version of `_fe_analyzer_shared`  was v61.0.0. However, after running `dart pub upgrade`, it was upgraded to v62.0.0, which subsequently led to the issue.

**Comment by sitaram-kalluri** [comment]
The version of `package:meta` is v1.8.0. The caret (^) is not prefixed before the meta package and hence it is not upgraded to the latest version. Upgrading the `package:meta` resolved the issue. 

Thank you for the support. Closing this issue.
