### ISSUE TITLE
Failures on Deprecate ExecutableElement.returnType, use returnType2 instead....[vm] Split isolate initialization logic into two pieces

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52818]
There are new test failures on [Deprecate ExecutableElement.returnType, use returnType2 instead....[vm] Split isolate initialization logic into two pieces](https://github.com/dart-lang/sdk/compare/63b567add21a9c6a74dae44a13f0588f2fd50e78~...8828fee8657c86ff823dbdba907f521c3659fc9c).

The tests
```
service_2/async_step_out_test/dds RuntimeError (expected Pass)
service_2/async_step_out_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-debug-x64
dartk-linux-release-x64
```

Log: https://dart-ci.appspot.com/log/vm-kernel-linux-debug-x64/dartk-linux-debug-x64/21482/service_2/async_step_out_test/service

```
00:08 +0 -1: async_step_out_test.dart (VM Service) [E]

  Expected to be at line 40 but actually at line 30
  Full stack trace:
   Frame([FrameKind.regular] helper async_step_out_test.dart:token(788)) [30]
   Frame([FrameKind.regular] _RootZone.runUnary zone.dart:token(66118)) [1661]
   Frame([FrameKind.regular] _microtaskLoop schedule_microtask.dart:token(1339)) [40]
   Frame([FrameKind.regular] _startMicrotaskLoop schedule_microtask.dart:token(1508)) [49]
   Frame([FrameKind.regular] _runPendingImmediateCallback isolate_patch.dart:token(3637)) [123]
   Frame([FrameKind.regular] _RawReceivePort._handleMessage isolate_patch.dart:token(5592)) [190]
  

  runtime/observatory_2/tests/service_2/service_test_common.dart 303:7  stoppedAtLine.<fn>
  ===== asynchronous gap ===========================
  runtime/observatory_2/tests/service_2/test_helper.dart 495:17         _ServiceTesterRunner.run.runTest.<fn>.<fn>
  ===== asynchronous gap ===========================
  runtime/observatory_2/tests/service_2/test_helper.dart 374:9          _ServiceTesterRunner.run.ignoreLateException
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9                      Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7                      Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9                       Invoker._waitForOutstandingCallbacks.<fn>
```

This test was flaky before

* https://dart-ci.web.app/#showLatestFailures=false&test=service_2/async_step_out_test/dds&configurations=dartk-linux-debug-x64
* https://dashboards.corp.google.com/_0d7e1e34_2c58_4d29_bf12_cf7bed10396d?fh=eJyljrEKwzAMRP9FsyeTpfmDzhlDBuGorcCWjSsXSsm_x6KBlq4dn0_3zvMLeIURBBOBg5BjS_JhfRbqxFKadlxRcSoUzlbx_jQM3ko3rGpP8-Igtag8UaSgMGpt1CWs0SywuWMtZLnwtVVUzvI9-xsc-_e37-8POKiU8oP6qSXbsgPVJ1LD&fb=name:ct:async_step_out_test

But the flakes were only timeouts, not runtime errors, so this is likely a valid failure.

Reproduces locally on 8828fee8657c86ff823dbdba907f521c3659fc9c.

Will bisect locally.

**Comment by dcharkes** [comment]
Repro on a4331b433a8737188589d3ff688fe1b4834643d7
Repro on 2b250992f940288695511f10cc27531193de75c0, which is before the commit range.
Repro on 4949f6185ebe6864c5650dec241fc3a388ac5ff5, the last commit on June 27th. 
Repro on 45572cf7ddef936533625219d05cc2b7cd813a2e.
Repro on ec15052c7fdd22b368b0f3b21673125f8c148e68.
Trying 14a30515523c7b55800ec5af8c651fb5c68d3551.
No repro on 401a11d309b7774bb98027b94710265b5ffe3398, the last commit on June 26th.
No repro on a023c3f00e75b08c5694c6c229b9af4e610d6adf, on June 22nd.

**Comment by dcharkes** [comment]
cc @mraleph this might have been caught by your rework of async stack traces.

@athomas @whesse why did this failure get reported so much later than when the commit landed?

**Comment by whesse** [comment]
The test was flaky, switching between Pass and Timeout.  It changed to stable RuntimeError, and that was marked as just a new type of flaky result.

I thought we had reporting when a new type of flakiness showed up, but I don't see it in the results feed.

It also seems like we should run deflaking when a new result shows up for a flaky test, that isn't in the results seen already.  If the deflaking shows that the new result is stable, then the flakiness should immediately be marked inactive, and the new result reported as a new stable result.

I'll file an issue requesting this to be implemented.

**Comment by whesse** [comment]
Filed issue https://github.com/dart-lang/sdk/issues/52819

The flakiness dashboard does not have a link to the first time the new result appeared, since the log links go to the latest log for that result.  But that data is in the flakiness record, and the "Last new result seen" time that is shown on the flakiness dashboard, 2023-06-23 16:40:45, does correctly point to the exact build where it first happened, which gives a much smaller blamelist.

**Comment by dcharkes** [comment]
Thanks @whesse !

**Comment by mraleph** [comment]
I think this is fixed at HEAD. At least I can't reproduce it anymore.
