### ISSUE TITLE
"Make final" fix puts "final" in the wrong position in record destructuring

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52820]
I have the `prefer_final_locals` lint enabled which triggers on this code individually for both `kind` and `value`: 

```dart
    for (var (kind, value) in sensorValues) {
```

However the quick-fix inserts `final` before the variable name producing invalid code:

```dart
for (var (final kind, value) in sensorValues) {
```

I thought it should change `var` to final instead, although that affects more than just the variable where the fix was invoked. This led me to try the following:

```dart
for (var (kind, value) in sensorValues) {
  value = 1;
```

Here, the lint still fires for `kind`, but I don't know what I'd expect the fix to do here. Perhaps the lint should only fire if all declared variables can be changed to final? Or is there some way to destructure into a mix of final/non-final variables?

**Comment by scheglov** [comment]
@pq

**Comment by pq** [comment]
> Here, the lint still fires for kind, but I don't know what I'd expect the fix to do here. Perhaps the lint should only fire if all declared variables can be changed to final? 

That's my instinct exactly. We do make that call elsewhere so I think this is a bug. (Filed: https://github.com/dart-lang/linter/issues/4539.)

**Comment by DanTup** [comment]
If it's fixed in that way, I presume there's nothing to change in the fix (and should close this issue?)

**Comment by bwilkerson** [comment]
Even in cases where all of the variables can be final, such as
```dart
void f(List<(int, int)> sensorValues) {
  for (var (kind, value) in sensorValues) {
    print(kind);
    print(value);
  }
}
```
the fix still puts the 'final' in the wrong place. I think the fix still needs to be fixed.

**Comment by DanTup** [comment]
Oh yeah, whoops. That was my original issue, I confused myself with the tangent 🙃

**Comment by pq** [comment]
I'm grateful that you brought it up. It's a legitimate false positive in the lint. Thanks for catching it!
