### ISSUE TITLE
Fix for `no_leading_underscores_for_local_identifiers` does not fix local functions

### ISSUE THREAD

**Issue by kturney** [dart-lang/sdk#52821]
https://github.com/dart-lang/linter/pull/3361 added support in the linter to detect local functions for which the name begins with an underscore.

However, as far as I can tell, [analysis_server...remove_leading_underscore.dart](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/dart/remove_leading_underscore.dart) was never updated to provide a fix for this.

`dart --version`: `Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "macos_arm64"`

I will be submitting an MR with a test shortly.

I'd planned to also develop a fix, but I can't seem to build anything due to a missing `../../third_party/pkg/yaml_edit` dependency for `analysis_server`.

I'll also inline here the test I am adding to `pkg/analysis_server/test/src/services/correction/fix/remove_leading_underscore_test.dart`

```dart
  Future<void> test_localFunction() async {
    await resolveTestCode(r'''
void f() {
  int _foo() => 1;
  print(_foo());
}
''');
    await assertHasFix('''
void f() {
  int foo() => 1;
  print(foo());
}
''');
  }
```

I'm willing to develop a fix if I can receive some guidance on fixing the missing `yaml_edit` dependency.

**Comment by kturney** [comment]
test PR: https://github.com/dart-lang/sdk/pull/52822

**Comment by scheglov** [comment]
Not sure what steps you use to prepare the SDK repository, but just checking out is not enough.
A number of packages should be pulled into `third_part/pkg`.
I run following script to do this:
```
cd ~/Source/Dart/sdk.git/sdk
gclient sync
gclient runhooks
```

**Comment by kturney** [comment]
Thanks for that @scheglov. I should have been been better about reading the contributing guide.
You set me on the right path, and I was able to update my PR with a fix for the issue.

**Comment by kturney** [comment]
resolved by https://github.com/dart-lang/sdk/pull/52822
