### ISSUE TITLE
Analyzer: I'd like to be able to "ignore" for a reason

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#52840]
There are lots of reasons you might use a `// ignore: [code]`. For this particular issue, let's assume we are talking about linter-related issues 100% of the time (i.e. ignoring other types of diagnostics that are `// ignore-able`, even though they may also benefit).

Some possible reasons:
1. The lint has a bug, i.e. it is flagging where it should not:
  ```dart
  sealed class Fruit {
    // Sealed classes functionally do not have public constructors.
    // ignore: public_member_api_docs
    const Fruit();
  }
  ```
2. The lint has known false positives that can't be fixed, and `// ignore` is intended to be used:
  ```dart
  // This constant is accessed via legacy code that is intended to exist forever.
  // ignore: avoid_screaming_caps
  const int MAX_ITEMS = 100;
  ```
3. We are intentionally ignoring a lint in (part of) the codebase:
  ```dart
  // We use print here because this runs on both the VM and Web as a diagnostic tool.
  // ignore: avoid_print
  print('Hello World');
  ```

I'd love to be able to describe _why_ I'm ignoring something, i.e. to:
- make it obvious to highlight in code review
- run tooling to discover how many lints are ignored (and why) in a large corpus
- as a lint author, detect why my lint is opted out (in a large corpus)

There isn't an obvious (standard) way to do this today. Just a placeholder idea:

```dart
// ignore(<REASON>): avoid_print
```

We could have a canonical set of reasons, or allow custom reasons. I'm leaning towards the latter for flexibility - there could be a (lol) lint that enforces a standard set of reasons and a syntax beyond this. Unfortunately comments seem poorly suited for this, but I'd love to be able to do something like:

```dart
// ignore: public_member_api_docs
//   reason: bug
//   issue: https://github.com/dart-lang/linter/issues/4526
```

---

Similar-ish issues (requesting extended functionality for ignore):

- https://github.com/dart-lang/sdk/issues/46549
- https://github.com/dart-lang/sdk/issues/43616

**Comment by bwilkerson** [comment]
I would be hesitant to add this to the syntax for the ignore comment unless the information could be used somehow by the analyzer (and I don't see a use for it at the moment).

That said, there's nothing stopping you from adding comments before the ignore comment. If we really want the comments to follow the ignore comment then we'd need to do some work to make the ignore comment apply to the line following the comment "block" (and if there are ever diagnostics reported inside comments we wouldn't be able to ignore them).

**Comment by lrhn** [comment]
I also don't see why
```dart
// Ignored because of bug (https://github.com/dart-lang/linter/issues/4526)
// ignore: public_member_api_docs
```
isn't sufficient.

If a specific format is needed, for some reason, it's unlikely that what the analyzer adds will be sufficient in all cases anyway.
It's better to make your own format then.

**Comment by matanlurey** [comment]
This issue was just for fun, it's not blocking any sort of use case. The main rationale as I see it is if the analyzer adopted a position on _how_ to store reasons, there could be a standard way for doing so (allowing various kinds of static analysis and information gathering).

By declining to have a standard, it's ok, just if we wanted to do such analysis it would require lots of heuristics (for example, the RegExp you listed above would not work if someone wrote "I'm ignoring this because ...", and they would not know it doesn't work).

**Comment by srawlins** [comment]
I forgot to write here that we now have the `document_ignores` rule: https://dart.dev/tools/linter-rules/document_ignores

**Comment by matanlurey** [comment]
That is a sexy lint rule.

**Comment by matanlurey** [comment]
Closing as complete :)
