### ISSUE TITLE
No error in CFE if an inline class has a superinterface with a wrong representation type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52849]
The following code produces an expected error in analyzer but not in CFE
```dart
inline class V1 {
  final String id;
  V1(this.id);
}

inline class V implements V1 {
  final num id; // Analyzer: 'V.id' ('num Function()') isn't a valid override of 'V1.id' ('String Function()').
//          ^^
// [analyzer] unspecified
// [cfe] unspecified
  V(this.id);
}

main() {
  print(V1);
  print(V);
}
```
There should be the same error in CFE
Tested on `Dart SDK version: 3.1.0-268.0.dev (dev) (Fri Jun 30 17:04:24 2023 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
It looks like we have two issues here:

1. If we have `V implements V1` then it is an error for the representation type `R` of `V` to be a non-subtype of the instantiated representation type `R1` of `V1`. In this case we do not have `num <: String`, and that makes the `implements` relationship an error. It looks like none of the tools report this error. Note that it makes no difference which name is used to denote the representation object (in this case it's `id` in both declarations, but it could be anything).
2. The analyzer seems to treat the unique instance variable declaration as a getter in a class, which would explain why it reports an override error. This would be a bug, inline class members do not have a notion of a correct override relationship.

```dart
inline class V1 {
  final int i; V1(this.i); // Not interesting, just needed.
  int get m => 1;
}

inline class V implements V1 {
  final int i; V(this.i); // Not interesting.
  void m(V other) {} // OK!
}
```

PS: There are proposals to change the name of the mechanism from 'inline class' to 'extension type', so we may have a period of time where this change may or may not be finally accepted, and probably a bit of confusion during the rename, if it does indeed happen. For now, I'll just keep using the old terminology.
