### ISSUE TITLE
unused_result: Destructuring is not considered "use" of a returned Tuple

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#52841]
It appears that the diagnostic powering `package:meta`'s `@useResult` needs an update:

```dart
import 'package:meta/meta.dart';

// Unfortunately we cannot reuse "_" as a variable name.
// ignore_for_file: unused_local_variable

void main() {
  // LINT
  returnNumber();
  
  // OK
  var one = returnNumber();
  
  // LINT
  returnTwoNumbers();
  
  // OK
  var two = returnTwoNumbers();
  
  // LINT (but should be OK)
  var (_, _) = returnTwoNumbers();
}

@useResult
int returnNumber() => 1;

@useResult
(int, int) returnTwoNumbers() => (2, 2);
```

I didn't try anything else (i.e. the new `switch` expression), but that might need work too?

**Comment by lrhn** [comment]
Why should it be OK to ignore the result of a function with `@useResult`? 😉

I guess this comes down to what the annotation intends to catch: someone discarding the results, or someone forgetting the result.

Pattern matching the result, then discarding every part, it's definitely not forgetting, but it is arguably discarding.

But, arguably, so is assigning to a variable, and never using that variable again. 
A "proper use" may require you to call a method on the value, pass it as an argument to some function, or return it (if the current function is marked `@useResult`).

If this lint it's just about not forgetting, then I agree with the LINT/OK markers.

(I guess `unawaited_futures` effectively marks every future as "must use", so the logic should be similar.)

**Comment by scheglov** [comment]
@pq

**Comment by bwilkerson** [comment]
> I guess this comes down to what the annotation intends to catch: someone discarding the results, or someone forgetting the result.

I think the reasoning in the past has been that this diagnostic should report when the result is discarded, and that we have other diagnostics to report when a value assigned to a local variable is never used. The latter catches more cases than values returned from function marked with `@useResult`, so seems valuable to have as a separate check, and duplication isn't helpful.
