### ISSUE TITLE
[gardening] service_2/causal_async_star_stack_contents_test/service failing

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52856]
There are new test failures on [[dart2js] Fix valid/invalid refinement logic....[pkg/vm] Instantiate the ffi Pointer class to bounds when needed.](https://github.com/dart-lang/sdk/compare/ac2533e7059a9a6c7be16d4321ef7867caeb1b95~...924a33c0f5705ecf504e9a75c7c11b40c50e410d).

The tests
```
service_2/causal_async_star_stack_contents_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-release-x64
```

Log: https://dart-ci.appspot.com/log/vm-kernel-linux-release-x64/dartk-linux-release-x64/23006/service_2/causal_async_star_stack_contents_test/service

```
00:13 [32m+0[0m[31m -1[0m: causal_async_star_stack_contents_test.dart (VM Service) [1m[31m[E][0m[0m

  Expected: contains '.dart:30'
    Actual: 'causal_async_star_stack_contents_test.dart:34:3'
     Which: does not contain '.dart:30'
  

  package:matcher/src/expect/expect.dart 149:31                                          fail
  package:matcher/src/expect/expect.dart 144:3                                           _expect
  package:matcher/src/expect/expect.dart 56:3                                            expect
  runtime/observatory_2/tests/service_2/causal_async_star_stack_contents_test.dart 97:5  tests.<fn>
```

```
--- Re-run this test:
python3 tools/test.py -n dartk-linux-release-x64 service_2/causal_async_star_stack_contents_test/service
```

Went from flaky to runtime error.

We need to check if this is a new runtime error.

I'll try to see what the failure was before the commit range.

**Comment by dcharkes** [comment]
It fails in the same way in the commit before the range 6a4ef6c93fca0870e914760c9e50d84fc75820c0.

So it has been failing like this for a while I assume.

cc @bkonyi

**Comment by a-siva** [comment]
//cc @derekxu16
