### ISSUE TITLE
[gardening] pkg/dev_compiler/test/expression_compiler/expression_compiler_worker timeouts

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52855]
There are new test failures on [Remove 'Clients may not extend...', because all these classes are final.](https://github.com/dart-lang/sdk/commit/44a94e8400670506930af66e376b49e7570d8ae7).

The tests
```
pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_amd_canary_test Timeout (expected Pass)
pkg/dev_compiler/test/expression_compiler/expression_compiler_worker_ddc_canary_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux
```

This test was already flaky, so it's likely not due to the mentioned commit.

@nshahan

**Comment by nshahan** [comment]
cc @annagrin

**Comment by nshahan** [comment]
This fork of the tests was deleted in https://github.com/dart-lang/sdk/commit/dd1e7ae18bb03caba4b374327a6b14480537d12c and the functionality (running the tests in ddc canary mode) was rolled into the orignal version of the test.
