### ISSUE TITLE
Support for calling `import()` through js interop

### ISSUE THREAD

**Issue by matthewnitschke-wk** [dart-lang/sdk#52852]
I'm working on an implementation that requires calling the [dynamic `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) function from dart

Because the import function is declared as a keyword and not a function on the window, we cannot reference it directly through the dart interop syntax:
```dart
@JS()
library someLib;

// This doesn't work since window.import is undefined, import is a keyword in js
@JS('import')
external Promise esmDynamicImport(String moduleName);
```
There are 2 workarounds to this problem, each with their set of issues:
1. Use `eval` to directly execute the `import()` function
    ```dart
    final Promise Function(String moduleName) _esmDynamicImport = eval('''
        (function _esmDynamicImport(moduleName){
            return import(moduleName);
        })
    ''');
    ```
    While this technically does work, any reliance on eval is a major red flag for security, and not a practical solution in a professional environment.

2. Adding `import()` to the window
    ```html
    <script type="module">
        window._esmDynamicImport = (moduleName) => import(moduleName);
    </script>
    ```
    ```dart
    @JS('_esmDynamicImport')
    external Promise esmDynamicImport(String moduleName);
    ```
    This solution works for basic implementations, but does not respect import map's [`scopes`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap#scoped_module_specifier_maps) keyword due to the `import()` declaration always being run from the same module

From what I can currently deduce, the ability to call `import()` from dart, and allow import maps to fully work, is not currently possible (without `eval`).

What would the consideration to support calling this function at an sdk level be? Either provided through the top level [`js`](https://pub.dev/packages/js) package via `js.import('moduleName')` or some other system which proxies this dynamic import keyword?

**Comment by robbecker-wf** [comment]
@kevmoo would this be something that could be added in the js package or would it need to be in a Dart SDK fix?

**Comment by kevmoo** [comment]
> @kevmoo would this be something that could be added in the js package or would it need to be in a Dart SDK fix?

@srujzs would be likely know...

**Comment by srujzs** [comment]
In the past, we've exposed keywords through `dart:js_util` (like `instanceof` for example) so I think that's a good fit here. You're right that keywords won't work with the existing interop model. We could convert the return value to a `Future` and have users use that or have users decide whether to use `Object` (which is a `Promise`) with `promiseToFuture`. In the future `dart:js_interop` world, we would have `JSPromise` anyways, so we could also use that.

**Comment by matthewnitschke-wk** [comment]
Sounds good, thanks @srujzs and @kevmoo!

We aren't in a huge rush, but this is something that we'd love to see in a future Dart release

Please let me know if you need anything else from us!
