### ISSUE TITLE
[New feature] Bring GO-lang's goroutine support to dart, as Web is not a problem now

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#52858]
hi,

### Go-routine

> A goroutine is a **lightweight** thread managed by the Go runtime.

> A Goroutine is a function which **executes independently** and **simultaneously** in connection with any other Goroutines present in the program.

> The **cost** of creating Goroutines is very small as compared to the thread.

Dart's `Isolate`s are even heavier than threads, so `goroutine` would be like a 3-yo brother to `Isolate`.

### Why?
- Goroutine is the prime highlight feature of GO language.
- This feature, along with memory efficiency, can even make the most GO-phers, and NodeJS-ers, jump to Dart.

### Why now?
As I could understand from [Google Groups: Why not the goroutine way? [Oct 2016]](https://groups.google.com/a/dartlang.org/g/misc/c/gNCAHKh5zhc), dart team did not implement goroutines before, because:
> Dart has Isolates that work in the VM and **Browser** (implemented as **web workers**).

> Dart was trying to match the JavaScript features

> this need to match the present and future JS features

But dart-web is going the wasm route, which **will** have threading support,
So cannot this be implemented now, because
> Make the most GO, and NodeJS users, jump to Dart
Because Memory is not a very big factor now-a-days, which GO users would care about

I also read (in the above google-groups chat), that
> Dartino was experimenting with lighter weight concurrency controls, like coroutines

May be because Dartino, did not have the "Web worker" constraints

thanks

**Comment by gintominto5329** [comment]
Related: [Dart Issue: Isolates are way too complex for a standard user](https://github.com/dart-lang/sdk/issues/50456)

**Comment by lrhn** [comment]
I'll admit I have a hard time placing this issue into an existing bucket. I'm going with `library-isolate`, but only because that's the existing feature it wants to replace.

> But dart-web is going the wasm route,

I wouldn't assume compiling to JavaScript will just go away.

**Comment by bivens-dev** [comment]
Am I missing something? I thought this had already been a thing for some time now https://youtu.be/SXT7nir1B48

**Comment by bernaferrari** [comment]
you don't need to wait for javascript to go away, isolates is already native exclusive, they could just build an easier to use isolate (similar to goroutine or kotlin coroutine) without looking into javascript.

**Comment by gintominto5329** [comment]
**I do not support this feature**, anymore, after reading:

> Isolate groups (having shared heap) can overcome some of the negative scenarios such as parsing a JSON in a spawned isolate and sending the result back to the main thread without a noticeable freeze there. 

> This fundamental change can ruin Dart, as it seems to violate, some key concepts of the language. 

_Originally posted by @maxim-saplin in https://github.com/dart-lang/language/issues/333#issuecomment-1130036521_

Also,

> Visual Studio Code is implemented in single thread JS and packaged as standalone app via Electron

_Originally posted by @maxim-saplin in https://github.com/dart-lang/language/issues/333#issuecomment-1129918815_

repo admins, please close this issue if needed

thanks

**Comment by lrhn** [comment]
Consider it closed :)
