### ISSUE TITLE
[CP] Fix infinite loop in DDC compiler

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#52869]
### Commit(s) to merge

be6a560

### Target

stable and beta

### Prepared changelist for stable/beta

Stable: https://dart-review.googlesource.com/c/sdk/+/312709, 
Beta: https://dart-review.googlesource.com/c/sdk/+/312710

### Issue Description

Some web development compiles of libraries containing `is` or `as` with specific record types will hang and never complete.

A minimal reproduction:
```dart
main() {
  Object value = 'x';
  (a: 'a', b: value) as ({String a, String b});
}
```

### What is the fix

Some record type comparison operations were not properly incrementing a loop variable when iterating the named elements. With this fix the execution can properly exit the loop and the compile succeeds.

### Why cherry-pick

Some type operations using record types will cause the DDC to hang while compiling preventing use of either the record types or web development compiler.

A user reported hitting this in a flutter application and could not compile their app for web development.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52817, https://github.com/flutter/flutter/issues/129482

### Extra Info

cc @sigmundch

**Comment by sigmundch** [comment]
Given the low risk and how its surfaced to users (the compiler hangs), I'm very much in favor of cherry-picking to both channels to ensure it makes it to both 3.0 and 3.1.

**Comment by itsjustkevin** [comment]
@athomas based on the timing of the next beta release, do you have opinions on when this should be merged to beta?

**Comment by vsmenon** [comment]
lgtm

**Comment by itsjustkevin** [comment]
Stable cherry-pick has landed, keeping this open until the beta cherry-pick has landed in a release.

**Comment by nshahan** [comment]
@athomas Any update on landing this in the beta branch?

**Comment by sigmundch** [comment]
I see a beta released after @nshahan's change landed, so it may potentially have this change. That said, the commit of the cherry-pick CL doesn't have a tag with the corresponding beta. 

@athomas - do we set the tags only on commits from the main branch, or do we also do it for these ad-hoc commits that are not always a clean cherry-pick? If not, would it be possible to tag them too?

**Comment by itsjustkevin** [comment]
@nshahan this was landed on the beta branch https://dart.googlesource.com/sdk/+log/1b6421ac0ba6e5196b58bce150495d872433151d.  

@sigmundch I am going to close this to clear up the queue, please feel free to open a new issue to track the commit tag discussion 🙂.
