### ISSUE TITLE
No support of `final inline class` in analyzer and CFE

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52864]
`final inline class ...` produces an error in both analyzer and CFE. But according to the [Inline class specification](https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md#syntax) this syntax is allowed

**Comment by lrhn** [comment]
The use of `final` most likely be removed in the `extension type` revision, so I'd hold off on implementing it.

**Comment by bwilkerson** [comment]
Analyzer support is on hold pending a decision about which flavor of the feature we're planning on shipping.

**Comment by srawlins** [comment]
Final is not a modifier in the new syntax.
