### ISSUE TITLE
Allow for spaces after chunk size when parsing HTTP with Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by ognjenMarinkovic27** [dart-lang/sdk#52887]
I've found that dart:http cannot parse HTTP chunk size when it contains spaces after the number, but before CRLF. In that case, it produces the error:

Failed to parse HTTP, 32 is expected to be a Hex digit

I've found this issue while working with [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer/tree/master)

Dart SDK Version: 3.0.5
OS: linux_x64

**Comment by a-siva** [comment]
A breaking change request to potentially fix this issue has been filed here https://github.com/dart-lang/sdk/issues/53005

**Comment by brianquinlan** [comment]
This will be fixed in Dart 3.2.0
