### ISSUE TITLE
how to listen to Http reqests via `vm_service`

### ISSUE THREAD

**Issue by maxzod** [dart-lang/sdk#52888]
which id is meant for it  
https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#streamlisten

for Logging i use 
```dart
final service = await vmServiceConnectUri(host.text);
    print('started at ${host.text}');
    await service.streamListen("Logging");
    service.onLoggingEvent.listen(onLog);
```

how to do the same for HTTP requests to be able to listen to HTTP requests

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by bkonyi** [comment]
@maxzod are you wanting access the HTTP logging data similar to that shown in DevTools? There's no stream provided by the VM service for HTTP events.

You can use the APIs [here](https://pub.dev/documentation/vm_service/latest/vm_service/DartIOExtension.html) to access network profiling data through the service protocol.

**Comment by a-siva** [comment]
I presume the question has been answered so closing this issue, if there is more info needed please reopen the issue.
