### ISSUE TITLE
Segmentation fault in "dart compile kernel" if -o output path includes directory which doesn't exist

### ISSUE THREAD

**Issue by bpilot** [dart-lang/sdk#52892]
This bug only occurs if the output directory doesn't exist, so isn't that egregious.

However, it isn't the greatest user experience in response to a typo.

Steps to reproduce:
1. Make a file called main.dart with an empty void main() { } or anything else that compiles.
2. dart compile kernel main.dart -o /somewhere/nowhere/main.dill

Result:
Compiling main.dart to kernel file /somewhere/nowhere/main.dill.
Info: Compiling with sound null safety.
Unable to open file /somewhere/nowhere/main.dill for writing snapshot

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=2, si_addr=0x6c8
version=3.0.1 (stable) (Tue May 16 11:57:19 2023 +0000) on "macos_arm64"
pid=58437, thread=259, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
os=macos, arch=arm64, comp=no, sim=no
isolate_instructions=0, vm_instructions=104e7a440
fp=16afd7370, sp=16afd6e30, pc=1055105b8
  pc 0x00000001055105b8 fp 0x000000016afd7370 Dart_ShutdownIsolate+0x3c
  pc 0x0000000104e50228 fp 0x000000016afd73a0 dart::bin::ErrorExit(int, char const*, ...)+0x30
  pc 0x0000000104e539dc fp 0x000000016afd7410 dart::bin::Snapshot::GenerateKernel(char const*, char const*, char const*)+0x128
  pc 0x0000000104e57ff8 fp 0x000000016afd7420 dart::bin::main(int, char**)+0x12ec
  pc 0x0000000104e572a8 fp 0x000000016afd7590 dart::bin::main(int, char**)+0x59c
  pc 0x0000000104e56398 fp 0x000000016afd75b0 main+0x10
  pc 0x00000001078290f4 fp 0x000000016afd7700 Unknown symbol
-- End of DumpStackTrace

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/313543
