### ISSUE TITLE
[gardening] Flaky pkg/dds/test/devtools_server/instance_reuse_test 

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52914]
The tests
```
pkg/dds/test/devtools_server/instance_reuse_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

This test was already flaky.

cc @bkonyi

**Comment by aam** [comment]
flaky->Timeout again https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8748671860650551905/+/u/test_results/stdout

**Comment by aam** [comment]
dup of https://github.com/dart-lang/sdk/issues/50237
