### ISSUE TITLE
Add getters to the vm_service protocol spec

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#52920]
Currently displays of objects are inconsistent between tools (VSCode and DevTools) and backends (VM and dwds). 

The following issues prevent us from always consistently displaying objects:

1. dwds is representing getters as fields instead of methods
   We are working on matching the VM behavior.

3. dart-code is using a VM-specific way (checking if private field `_kind` on the Function object equals to `GetterFunction`, which only works for VM, not dwds). 
    https://github.com/Dart-Code/Dart-Code/blob/15ad6615d8e8c02fd4393112f9896cf3bfc3c1fe/src/debug/dart_debug_impl.ts#L1424

4. DevTools does not show getters on objects at all. 
    We would like to eventually use dart-code logic for DevTools object display so all the debugging tools are consistent.

5. vm_service protocol does not provide a way of easily identifying getters:

   - `Class` does not indicate what function refs are getters:
       https://github.com/dart-lang/sdk/blob/3daa47b54e5f39241c44858e0d66ce51723040bf/runtime/vm/service/service.md?plain=1#L2033

   - If i understand correctly, `@Function` does not specify if the function is a getter either (only if it is an implicit getter):
       https://github.com/dart-lang/sdk/blob/3daa47b54e5f39241c44858e0d66ce51723040bf/runtime/vm/service/service.md?plain=1#L2756

**Suggestion**

So solve all the issues, we would need to solve 4. first.
Define a way to identify getters in `vm_service` protocol so the debugger can evaluate getters if requested (for all backends).

**Comment by annagrin** [comment]
Related: https://github.com/dart-lang/sdk/issues/46723

**Comment by DanTup** [comment]
> dart-code is using a VM-specific way (checking if private field _kind on the Function object equals to GetterFunction, which only works for VM, not dwds).
> https://github.com/Dart-Code/Dart-Code/blob/15ad6615d8e8c02fd4393112f9896cf3bfc3c1fe/src/debug/dart_debug_impl.ts#L1424

That link is for the legacy adapters, but the new adapters do the same thing here:

https://github.com/dart-lang/sdk/blob/3daa47b54e5f39241c44858e0d66ce51723040bf/pkg/dds/lib/src/dap/protocol_converter.dart#L737

FWIW, I recently added support for lazy-evaluation of getters in the new adapters (the user will see the names of the getters but we won't evaluate them unless they click), so if changes are made to simplify accessing getters and their values, we should ensure it still supports getting only the names so they can be fetched lazily/individually.

**Comment by derekxu16** [comment]
`isGetter` and `isSetter` properties have been added to `@Function` and `Function` in [`package:vm_service 11.8.0`](https://pub.dev/packages/vm_service/versions/11.8.0).
