### ISSUE TITLE
New vm/dart/gc/chunked_binary_trees_array_test timing out on a few configurations

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#52924]
There are new test failures on [[vm, gc] Add flag to disable write barrier elimination.](https://github.com/dart-lang/sdk/commit/d486c52ff6da0af20a7174b92144c107608ed04f).

The tests
```
vm/dart/gc/chunked_binary_trees_array_test/0 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_array_test/1 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_array_test/2 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_array_test/3 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_test/0 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_test/1 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_test/2 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_test/3 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_test/4 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_test/5 Timeout (expected Pass)
```
are failing on configurations
```
vm-aot-android-release-arm_x64
vm-aot-linux-release-simarm_x64
vm-reload-linux-debug-x64
```

Specific list of which versions are failing on which configuration follows, including an example log for one of the versions:
* [`vm-aot-android-release-arm_x64`](https://dart-ci.appspot.com/log/vm-aot-android-release-arm_x64/vm-aot-android-release-arm_x64/994/vm/dart/gc/chunked_binary_trees_test/1): just `/1`
* [`vm-aot-linux-release-arm_x64`](https://dart-ci.appspot.com/log/vm-aot-linux-release-simarm_x64/vm-aot-linux-release-simarm_x64/748/vm/dart/gc/chunked_binary_trees_array_test/0): `/0`-`/3`
* [`vm-reload-linux-debug-x64`](https://dart-ci.appspot.com/log/vm-reload-linux-debug-x64/vm-reload-linux-debug-x64/143/vm/dart/gc/chunked_binary_trees_test/1) : `/0` - `/5`

/cc @rmacnak-google

**Comment by dcharkes** [comment]
This test is still timing out (and flakily so).

![image](https://github.com/dart-lang/sdk/assets/3601775/4d92d13c-593c-47b3-99bb-a81b112f383f)

https://dart-current-results.web.app/#/filter=vm/dart/gc/chunked_binary_trees_test&showAll
