### ISSUE TITLE
Named functions subtyping issue on dart2js

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52928]
The following co19 fail on `dart2js-hostasserts-linux-chrome-unsound` and `ddc-linux-chrome-unsound` configurations

[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_arguments_binding_fail_A61_t01](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_arguments_binding_fail_A61_t01.dart)
[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_arguments_binding_fail_A61_t02](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_arguments_binding_fail_A61_t02.dart)
[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_arguments_binding_fail_A61_t03](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_arguments_binding_fail_A61_t03.dart)
[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_class_member_fail_A61_t01](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_class_member_fail_A61_t01.dart)
[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_class_member_fail_A61_t02](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_class_member_fail_A61_t02.dart)
[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_class_member_fail_A61_t03](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_class_member_fail_A61_t03.dart)
[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_global_variable_fail_A61_t01](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_global_variable_fail_A61_t01.dart)
[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_local_variable_fail_A61_t01](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_local_variable_fail_A61_t01.dart)
[co19/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_return_value_fail_A61_t01](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/named_function_types_fail_return_value_fail_A61_t01.dart)

All these tests checks runtime type of named functions with a required parameter
[Logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8775695959909558737/+/u/test_results/new_test_failures__logs_)

**Comment by fishythefish** [comment]
Note that these failures are on configurations with unsound null safety, which uses [legacy subtyping](https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/feature-specification.md#subtyping). Therefore, `required` named parameters are treated as optional. If these tests expect sound mode subtyping rules, then they should contain
```dart
// Requirements=nnbd-strong
```

**Comment by sgrekhov** [comment]
Added `// Requirements=nnbd-strong` to the tests from the above. No this issue any longer. Thank you, @fishythefish
