### ISSUE TITLE
ConcurrentModificationError in dds/dap isolate_manager.dart

### ISSUE THREAD

**Issue by christopherfujino** [dart-lang/sdk#52932]
Seeing this on Flutter `beta/3.12.0-1.1.pre`
Which has dds [2.9.0](https://github.com/flutter/flutter/blob/beta/packages/flutter_tools/pubspec.yaml#L13)

```
ConcurrentModificationError at _CompactIterator.moveNext at dart:collection-patch/compact_hash.dart-58c112d2
at _CompactIterator.moveNext(compact_hash.dart:710)
at IsolateManager._sendBreakpoints(isolate_manager.dart:724)
at <asynchronous gap>(async)
at IsolateManager._configureIsolate(isolate_manager.dart:397)
at <asynchronous gap>(async)
at IsolateManager.registerIsolate(isolate_manager.dart:221)
at <asynchronous gap>(async)
at IsolateManager.handleEvent(isolate_manager.dart:164)
at <asynchronous gap>(async)
at DartDebugAdapter.handleIsolateEvent(dart.dart:2116)
at <asynchronous gap>(async)
at DartDebugAdapter._withErrorHandling(dart.dart:2424)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment]
cc @DanTup

**Comment by rakudrama** [comment]
The recent fix https://github.com/dart-lang/sdk/commit/d8fa6fe25522f45b7070278ad152abe4724cbdf2 for https://github.com/dart-lang/sdk/issues/38256 and https://github.com/dart-lang/sdk/issues/48282 might be causing a latent error to be reported. Is it possible that `_clientBreakpointsByUri` is modified while its `.keys` is being iterated?

**Comment by DanTup** [comment]
> Is it possible that `_clientBreakpointsByUri` is modified while its `.keys` is being iterated?

It looks like this might be possible. Although it's not done inside this method, there are `awaits` in here, so if something triggers breakpoints being sent multiple times and overlapping, I think this could occur.

@christopherfujino how frequently is this occurring? There have been quite a few changes/fixes to breakpoints since that version (that are in DDS 2.9.2). They won't fix the issue, but do mean that cherry-picking a fix to beta for this could be complicated.

**Comment by DanTup** [comment]
> The recent fix https://github.com/dart-lang/sdk/commit/d8fa6fe25522f45b7070278ad152abe4724cbdf2 for https://github.com/dart-lang/sdk/issues/38256 and https://github.com/dart-lang/sdk/issues/48282 might be causing a latent error to be reported.

If the Dart beta branch matches what's in the Flutter beta (I think so), then I don't think that change is included?

https://github.com/dart-lang/sdk/commits/beta

**Comment by DanTup** [comment]
I can't repro this, but I think it can occur if breakpoints are modified as an isolate is being registered. Adding `toList()` to keys here seems like a safe fix to me (the URL being removed of modified in the map should not cause any problems), so I've done this here:

https://dart-review.googlesource.com/c/sdk/+/313782

I don't know if there's a good way to make a new DDS that has this fix without the rest of 2.9.2 though. Would it be reasonable to make a 2.93 and cherry-pick that and accept the other changes given it's early in the beta? (there are actually some nice fixes in 2.9.2, but it does bring the risk of other bugs).

@christopherfujino @bkonyi

**Comment by christopherfujino** [comment]
A few things:

1. there is now a newer Flutter beta release, 3.13.0-0.1.pre, however it uses the same dds version [2.9.0](https://github.com/flutter/flutter/blob/beta/packages/flutter_tools/pubspec.yaml#L13)
2. On the previous beta, the overall usage was low enough that I don't have high confidence on the impact of this bug--that being said, at 3 affected clients (out of ~1k users), it's tied for second most impactful bug.
3. If at all possible, we should try to avoid pulling in unrelated DDS changes to this beta release.

@DanTup & @bkonyi this is the commit that bumped the pubspec version to 2.9.0, is this the commit we would want to hotfix? https://github.com/dart-lang/sdk/commit/46d9f76f7e6d03c159ee15831896b75391d23ae6

**Comment by DanTup** [comment]
>  this is the commit that bumped the pubspec version to 2.9.0, is this the commit we would want to hotfix?

We'd should verify if that's the version that actually shipped as 2.9.0. The version is sometimes increased and then other changes are pushed (that commit is 2nd June, but DDS 2.9.0 was 6th June).

We can't cherry-pick the fix to Dart beta because that's much newer than where DDS 2.9.0 was released, so I think we'd need to branch at the right commit, apply that change, then publish (as DDS 2.9.0+hotfix or something?).

**Comment by bkonyi** [comment]
Hotfix is published as [2.9.0+hotfix](https://pub.dev/packages/dds/versions/2.9.0+hotfix).

**Comment by christopherfujino** [comment]
> Hotfix is published as [2.9.0+hotfix](https://pub.dev/packages/dds/versions/2.9.0+hotfix).

Awesome, thanks! Let me try to cherrypick this to Flutter beta.

**Comment by DanTup** [comment]
I've opened a request for a Dart beta cherry-pick at https://github.com/dart-lang/sdk/issues/52980

**Comment by DanTup** [comment]
This was cherry-picked into both Dart and Flutter betas.

@christopherfujino let me know if you see any other concerning crashes show up in the Flutter beta.
