### ISSUE TITLE
Quick fix for making a class abstract forgets where `base` should go

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#52948]
The quick fix for adding final to a base class produces an out of order fix.

```
base class Foo {
  int bar();
}
```

moving the cursor to `|int bar()` and selecting `Make class 'Foo' abstract` produces:

```
base abstract class Foo {
  int bar();
}
```

instead of 

```
abstract base class Foo {
  int bar();
}
```

Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "macos_x64"

**Comment by pq** [comment]
Definitely a bug. Thanks for the report @navaronbracke!
