### ISSUE TITLE
[CP] Revert invalid refinement check in Dart2JS global inference

### ISSUE THREAD

**Issue by biggs0125** [dart-lang/sdk#52940]
### Commit(s) to merge

73160bc40d5bdb222d9f1def8b67cb22a6d99765

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/313644

### Issue Description

A change made to Dart2JS's global inference meant to prevent type refinement loops was discovered to be unsound. Invalid types were being inferred for some code patterns and thus bad code was being generated.

### What is the fix

The fix is to revert the change and move global inference back into a known sound state.

### Why cherry-pick

This change can lead to unsound code and cause issues in users' Dart2JS compiled applications.

This fix puts inference back into the state it has been for a long time so it is a very safe cherrypick.

### Risk

low

### Issue link(s)

N/A

**Comment by sigmundch** [comment]
I highly support cherry-picking this into beta. We have seen two incidents related to this issue in internal apps, and don't want this to go out in stable externally as it is. Thankfully the cherry-pick is minimal and very low risk.
