### ISSUE TITLE
Rest patterns are contagious within a switch

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#52941]
Consider the following code:

```dart
void main() {
  switch ([1, 2, 3]) {
    case [6, ...var rest]: print(rest);
    case [...var all]: print(all);
  }
}
```

This _should_ print `[1, 2, 3]`. However, it seems like the `var rest` somehow takes precedence over `var all`, despite not being a match.

Now, in this case, you can swap the last case with `case var all` and it'll work fine. But this seems to happen anywhere there are multiple rest matches against the same list:

```dart
void main() {
  switch ([1, 2, 3]) {
    case [6, 7, ...var rest]: print(rest);
    case [_, ...var all]: print(all);
  }
}
```

This prints `[3]` when it should print `[2, 3]`. Tested on Dart 3.0.6.

**Comment by johnniwinther** [comment]
This has been fixed in https://dart-review.googlesource.com/c/sdk/+/302922
