### ISSUE TITLE
Static interop should use compiler-dependent global context

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#52955]
Currently, we use `globalThis` everywhere, but this is not necessarily available. Instead, we should have the compilers decide what to use for interop. For dart2js, this is likely `self` and for DDC, this is likely `dart.global`. Long-term, we should avoid making interop based on the global context unless requested and instead define a scope where we expect users to export their JS code to. We do need to be careful about the compilers shadowing names, however.

**Comment by rakudrama** [comment]
Is the global context something that is fixed, and can be captured for re-use?

Is dart2js allowed to reuse an access of the global context as an optimization?

**Comment by srujzs** [comment]
Talked offline about this but yes, we'd want dart2js to be able to cache this by marking this getter as "pure" through the `JS` foreign function's metadata. DDC naturally won't be able to do this, but that's okay, since that's the current behavior of interop and dart:html.
