### ISSUE TITLE
Support "fixing" switches with cascading conditions into switch expressions with `||`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#52958]
I think I'm using the terms correctly.

```dart
  int get elementSize {
    switch (type) {
      case 'float':
      case 'int':
        return 4;
      case 'short':
        return 2;
      case 'byte':
        return 1;
      default:
        return 0;
    }
```

should have a suggested fix to

```dart
    return switch (type) {
      'float' || 'int' => 4,
      'short' => 2,
      'byte' => 1,
      _ => 0
    };
```

but it does not!

**Comment by pq** [comment]
Yeah. We don't currently have the smarts to handle:

**Comment by parlough** [comment]
An interesting workaround here is that you can convert to an if-case statement chain, then back to a switch statement, then to a switch expression :P

**Comment by FMorschel** [comment]
I believe this specific ask was already solved by https://github.com/dart-lang/sdk/issues/54567. I also created my request to it https://github.com/dart-lang/sdk/issues/55861 missing both.

Current related issues that I know of (1 request to separate the assist to merge the cases and 2 bugs with the current assist respectively):

- https://github.com/dart-lang/sdk/issues/56180
- https://github.com/dart-lang/sdk/issues/56597
- https://github.com/dart-lang/sdk/issues/56602

**Comment by srawlins** [comment]
Ah excellent, closing then.
