### ISSUE TITLE
Analyzer suggests rare `dart:ffi` symbols when starting with a '_'

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#52959]
![Screenshot 2023-07-17 at 3 54 42 PM](https://github.com/dart-lang/sdk/assets/168174/7b94ff12-5a46-4f84-8165-9e80c187ec6a)

I am guessing these are basically the only two types in the standard SDK that are (a) top-level and (b) contain an `_`, but it's still slightly annoying to have them popup _every_ time I write `final _^`.

**Comment by bwilkerson** [comment]
Are there private types in scope that are _not_ being suggested?

**Comment by scheglov** [comment]
We new completion protocol we don't suggest symbols that contain `_` when the completion prefix is `_`.
These get negative fuzzy matching scores, and excluded.
