### ISSUE TITLE
Analyzer auto-completes members on "Never.^" non-ideally

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#52962]
## Simple example

On most types (i.e. `String`):

```dart
void main() {
  String.^
}
```

![Screenshot 2023-07-17 at 4 43 31 PM](https://github.com/dart-lang/sdk/assets/168174/bb0bcfee-39d6-4765-9edc-3e133a09c229)

but for `Never`:

![Screenshot 2023-07-17 at 4 44 09 PM](https://github.com/dart-lang/sdk/assets/168174/6a345a9b-edee-4c7e-8a8f-160f09ec3ced)

## Why file this issue?

Good question. One could say this is such a rare or even unusable concept and the priority of this should be P12. However, this makes using a cute-little namespace pattern in Dart a bit ugly:

```dart
extension Fruits on Never {
  const apple = 'apple';
  const grapes = 'grapes';
  const watermelon = 'watermelon';
}

void main() {
  // Auto-completes first with hashCode and runtimeType, and then Fruits.apple third.
  print(Fruits.^);
}
```

**Comment by lrhn** [comment]
Not sure I understand the example.
The `const` declarations are not valid (have to be static, there are no instance constant variables), you can't access statics of an extension through the `on` type, and you can't access instance getters on a type object.

**Comment by matanlurey** [comment]
> you can't access statics of an extension through

Sure you can:

```dart
void main() {
  print(Presidents.abe);
}

extension Presidents on Never {
  static const abe = 'Abraham';
  static const george = 'George';
  static const jefferson = 'Jefferson';
}
```

**Comment by lrhn** [comment]
That's not "on the `on` type". That's just accessing statics on the extension name directly, so it's not on `Never`, and should (I hope) not be related to the `Never` type at all.
