### ISSUE TITLE
Analyzer suggests static private members I can't possibly access

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#52963]
```dart
// a.dart
class Fruits {
  static final _allSeason = [ ... ];
}
```

```dart
// b.dart
void main() {
  Frui^
}
```

... completes and presents `Fruits._allSeason`, but that's invalid.

**Comment by scheglov** [comment]
I cannot reproduce this anymore.
So, I suspect that this was when using older completion protocol, with available declarations.
New IDEs don't use it anymore.
