### ISSUE TITLE
Dart2Js tree shaking remove used functions when using function reference and generic types

### ISSUE THREAD

**Issue by eric-taix** [dart-lang/sdk#52968]
- `Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_arm64" `
- `MacOSX / M2`
- `Chrome Version 114.0.5735.198 (Build officiel) (arm64)`
  

**What I'm trying to do**
I'm trying to build a generic way to validate some values: a value may have one or multiple validators and a message is associated with a validator, so I can display these messages to the end user. These validation "framework" will be used in Flutter Web.

I've also created to function to easily create these validators, with a generic type so this function can be used to whatever type to validate.

**What I'm expected?**
The code runs either in debug, profile or release mode in a brower.

**What is the result?**
The code runs well in debug mode, but fail to run in profile or release mode.

**Steps to reproduce**
Copy / paste this code and run it in debug mode and also in profile or release mode.

```
void main() {
  final validator = createValidator([
    (validate: isNotEmpty, message: 'Value is required'),
  ]);
  print(validator('it should return null'));
  print(validator(null) == ['Value is requirjed']);
}

/// Validation "framework
typedef FieldValidator<T> = List<String> Function(T? value);
typedef Validator<T> = bool Function(T? value);
FieldValidator<T> createValidator<T>(List<({Validator<T> validate, String message})> validators) => (T? value) {
      return validators
          .where((validator) => !validator.validate(value))
          .map((validator) => validator.message)
          .toList();
    };

/// Validator implementations
bool isNotEmpty(String? value) => value != null && value.isNotEmpty;
```

In profile mode the browser's console output is:
```
core_patch.dart:238 Uncaught TypeError: value.get$isNotEmpty is not a function
    at StaticClosure.isNotEmpty (main.dart:23:58)
    at createValidator__closure.call$1 (main.dart:17:44)
    at WhereIterator.moveNext$0 (iterable.dart:441:13)
    at MappedIterator.moveNext$0 (iterable.dart:392:9)
    at Object.List_List$_of (core_patch.dart:476:5)
    at Object.List_List$of (core_patch.dart:457:39)
    at createValidator_closure.call$1 (iterable.dart:494:7)
    at Object.main0 (main.dart:8:9)
    at main_closure0.call$0 (main.dart:24:7)
    at initialization.dart:77:9
```

**Analysis**
The `Dart2js` tree shaking seems to remove some code as if it doesn't see that `isNotEmpty` is called even if the `main.dart.js` use the getter:
```
    isNotEmpty(value) {
      var t1 = value.get$isNotEmpty(value);
      return t1;
    },
```

To verify this hypothesis, I updated the code:
```
void main() {
  isNotEmpty('avoid tree shaking'); // <== Added line
  
  final validator = createValidator([
    (validate: isNotEmpty, message: 'Value is required'),
  ]);
  ....
```

The result is different (see below) which supports the hypothesis:
```
core_patch.dart:238 Uncaught TypeError: Cannot read properties of null (reading 'length')
    at StaticClosure.isNotEmpty (js_string.dart:429:23)
    at createValidator__closure.call$1 (main.dart:16:44)
    at WhereIterator.moveNext$0 (iterable.dart:441:13)
    at MappedIterator.moveNext$0 (iterable.dart:392:9)
    at Object.List_List$_of (core_patch.dart:476:5)
    at Object.List_List$of (core_patch.dart:457:39)
    at createValidator_closure.call$1 (iterable.dart:494:7)
    at Object.main0 (main.dart:8:9)
    at main_closure0.call$0 (main.dart:24:7)
    at initialization.dart:77:9
```

And the generated code `main.dart.js` is now:
```
    isNotEmpty(value) {
      return value.length !== 0;
    },
``` 

=> The code does not prevent from null value, even if I test the nullity in my code.

To let `Dart2Js` know that the value can be null I had to add another line:
```
void main() {
  isNotEmpty('avoid tree shaking');
  isNotEmpty(null);  // <== Added line

  final validator = createValidator([
    (validate: isNotEmpty, message: 'Value is required'),
  ]);
  ...
```

And now everything is running fine!

**Comment by fishythefish** [comment]
This might be an issue with tracing involving records? Seems like the inferred argument type is based on direct calls to `isNotEmpty` but we don't follow the closure through the record so we miss the calls made via `createValidator`.

**Comment by sigmundch** [comment]
I think so too, when I tried converting the record to a class, the code was no longer tree-shaken.

**Comment by fishythefish** [comment]
Fix on the way: https://dart-review.googlesource.com/c/sdk/+/315020
