### ISSUE TITLE
[Feature Request] API to get a SendPort from a FFI NativePort

### ISSUE THREAD

**Issue by maks** [dart-lang/sdk#52977]
Currently the `dart:ffi` package provides an extension [to get a `NativePort` for a SendPort](https://api.dart.dev/stable/3.0.6/dart-ffi/NativePort/nativePort.html) to pass into native code via FFI.

I would like to request another extension method to retreive a SendPort object in Dart from a NativePort, eg.
```
SendPort SendPort.fromNativePort(int nativePort); 
```

The reason for this request is that it would allow native code to not only make direct use of native ports for communication back to Dart, but also to provide other services to Dart code which require sending back the port back to Dart for use by Dart code. 

The initial use case is to implement a standalone Dart package version of the existing [Flutter IsolateNameServer](https://github.com/flutter/engine/tree/main/lib/ui/isolate_name_server) as I mentioned [in another issue](https://github.com/dart-lang/sdk/issues/44495#issuecomment-1637612636) which currently is not possible using just FFI, rather than asking the Dart team to implement it in one of the Dart core packages.

**Comment by lrhn** [comment]
What can that number be used for?

**Comment by maks** [comment]
@lrhn I assumed the int is some sort of Id that identifies the sendport to the VM when native code wants to send data to Dart via that port, hence I expected it could be used to then return a Dart SendPort object that it represents on the Dart side.

**Comment by mkustermann** [comment]
Would the following not work:
```dart
import 'dart:isolate';
import 'dart:ffi';

void main() {
  final ReceivePort receivePort = ReceivePort();
  final SendPort sendPort = receivePort.sendPort;
  final int nativePort = sendPort.nativePort;

  final SendPort sendPort2 = convertNativePortToSendPort(nativePort);
}
```
in C++
```c++
Dart_Handle convertNativePortToSendPort(Dart_port port) {
  // The API is also available via our `include/dart_api_dl.h` surface.
  return Dart_NewSendPort(port);
}
```

**Comment by lrhn** [comment]
It would worry me, because `SendPort`s are capabilities, and this would allow you to create a capability from a guessed integer.

If `dart:ffi` allows you to read any memory, maybe it's not that big of a security issue, but it is an issue.

**Comment by maks** [comment]
Sorry for the delayed reply and WOW, huge thanks @mkustermann !!!

So I did not know about `Dart_NewSendPort()` or that you could pass `SendPort`'s through FFI calls **or** that there was a  `dart_api_dl.h` and that all the headers are actually shipped in the SDK distro in the `include` directory, so many things to learn at once! 

I'm giving this a go now to see if I can make it work in practise and will report back shortly.

**Comment by maks** [comment]
oops, sorry @mkustermann , please ignore the above, I just missed that I needed to use `Object Function(int port)` and it now works fine, including with AOT exe's!  🎉 
ffigen pointed out my error to me :-)  and of course I also needed to fix using extern C for c++ name mangling.

I think my little package will now be a good case to try out the [new native assets support from](https://github.com/dart-lang/sdk/issues/50565#issuecomment-1570493210) @dcharkes 

@lrhn I don't really fully understand what the security implications of this are as it has to be via FFI, I guess you mean their could be a malicious package that could try to make use of this? But for me, this is functionality is perfect as I can now port the existing Flutter IsolateNameServer to a Dart package without needing the request I opened this issue for.
