### ISSUE TITLE
No support of covariant instance variables

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52981]
According to the Dart [specification](https://spec.dart.dev/DartLangSpecDraft.pdf) "10.6 Instance Variable"

> It is possible for the declaration of an instance variable to include the modifier covariant (8). The effect of this is that the formal parameter of the corresponding implicitly induced setter is considered to be covariant-by-declaration

In fact the following code doesn't work in both analyzer and CFE
```dart
class A {
  covariant num v = 1;
}

class C extends A {
  void set v(int val) {} // CFE: Error: The type 'num' of the inherited field 'A.v' is not a subtype of the type 'int' of the setter 'C.v'.
                         // Analyzer: The return type of getter 'A.v' is 'num' which isn't a subtype of the type 'int' of its setter 'v'. 
}

main() {
  print(C);
}
```
According to the spec setter `A.v` has a covariant formal parameter which means that setter `C.v` should accept any type which is subtype or supertype of `num`

Tested on `Dart SDK version: 3.1.0-309.0.dev (dev) (Thu Jul 13 13:04:16 2023 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
I think the responses from the tools are OK. The error which is reported is that (essentially) we can't do `v = v` in the body of `C`, or more precisely: In the interface of `C`, the return type of the getter named `v` is not a subtype of the formal parameter type of the setter named `v=`, and that's an error (which is still valid, no matter if and where we put the word `covariant`).

It is still possible to test that `covariant` has an effect:

```dart
class A {
  covariant num v = 1;
}

class C extends A {
  int get v => 2; // Ensure that the getter `v` has the required return type.
  void set v(int val) {} // Now we can use the `covariant` property.
}

class C2 implements A {
  int v = 1; // A more typical way to use the extra affordances provided by `covariant`.
}
```

**Comment by sgrekhov** [comment]
Thanks for response. Closing this issue
