### ISSUE TITLE
[Gardening] ffi/native_callables_async_structs_by_value_generated_test/2 RuntimeError (expected Pass)

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#52985]
The tests
```
ffi/native_callables_async_structs_by_value_generated_test/2 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-linux-release-riscv64-qemu
```

[logs](https://dart-ci.appspot.com/log/vm-ffi-qemu-linux-release-riscv64/vm-linux-release-riscv64-qemu/448/ffi/native_callables_async_structs_by_value_generated_test/2)

cc @liamappelbe

**Comment by liamappelbe** [comment]
Duplicate of #48645
