### ISSUE TITLE
[CP] Fix ConcurrentModificationError in dds/dap isolate_manager.dart

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52980]
### Commit(s) to merge

98b63e1dcf600402c910740cf2338cb18e05f68d

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/314740

### Issue Description

A race existed where changing breakpoints while a new isolate was starting could result in a `ConcurrentModificationError` due to iterating a map's `.keys` with an `await` inside the loop (see https://github.com/dart-lang/sdk/issues/52932):

```
ConcurrentModificationError at _CompactIterator.moveNext at dart:collection-patch/compact_hash.dart-58c112d2
at _CompactIterator.moveNext(compact_hash.dart:710)
at IsolateManager._sendBreakpoints(isolate_manager.dart:724)
at <asynchronous gap>(async)
at IsolateManager._configureIsolate(isolate_manager.dart:397)
at <asynchronous gap>(async)
at IsolateManager.registerIsolate(isolate_manager.dart:221)
at <asynchronous gap>(async)
at IsolateManager.handleEvent(isolate_manager.dart:164)
at <asynchronous gap>(async)
at DartDebugAdapter.handleIsolateEvent(dart.dart:2116)
at <asynchronous gap>(async)
at DartDebugAdapter._withErrorHandling(dart.dart:2424)
at <asynchronous gap>(async)
```

### What is the fix

The fix is to take a copy of the keys (using `.toList()`) prior to enumerating. The body of the loop already tolerates map keys being updated (or removed).

### Why cherry-pick

Prevents potential intermittent crashes of the debug adapter (which could terminate a users debug session).

The change is being cherry-picked into Flutter at https://github.com/flutter/flutter/issues/130739 via a DDS hotfix, but that only covers Flutter apps and not Dart CLI/tests.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52932

### Extra Info

cc @bkonyi

**Comment by itsjustkevin** [comment]
@a-siva could we get a second look on this cherry-pick request?

**Comment by a-siva** [comment]
lgtm.

**Comment by DanTup** [comment]
I presume the approval above means this can be merged? I don't have permissions to merge, so someone else (@bkonyi? :-)) will have to land it for me. Thanks!

**Comment by bkonyi** [comment]
I submitted the CL (I assume that's okay... 😬).

**Comment by DanTup** [comment]
@bkonyi thanks! According to https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel#submitting-the-cherry-pick, it appears the author should submit once the issue is approved, so I _believe_ this is correct :-)
