### ISSUE TITLE
Analyzer missing error when inferring type argument from promoted type variable.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#52995]
Example:
```dart
void main() { foo<num>(false, 0, 0); }

class C<T extends num> {
  const C(T _);
  void st<S extends E<T>>(){}
}
typedef E<T> = T Function(T); // Invariant.

void foo<X>(bool test, X v1, X v2) {
  if (v1 is! int) return;
  // promoted to X&int, X&num
  
  C(v1).st<E<X>>;

  C(v1); // Error
  var c1 = C(v1);  // Error
  c1.st<E<X>>;
  // ignore: avoid_single_cascade_in_expression_statements
  C(v1)  // Error
    ..st<E<X>>;

  C(v2).st<E<X>>; // Error.
}
```

The analyzer by-and-large does the specified (and useless) thing of solving the 
type argument to `C` with `T <: num` (bound) and `T&int <: T` (parameter type+argument type), and choosing `T&int` as the solution.

It then erases the `int` as necessary when reifying an intersection type as a type argument or variable type, making the argument no longer valid.

The lines marked `// Error` give the following, regrettably expected, errors:
```
line 15 • 'X' doesn't conform to the bound 'num' of the type parameter 'T'.
Try using a type that is or is a subclass of 'num'.
The raw type was instantiated as 'C<X>', and is not regular-bounded.
error
line 16 • 'X' doesn't conform to the bound 'num' of the type parameter 'T'.
Try using a type that is or is a subclass of 'num'.
The raw type was instantiated as 'C<X>', and is not regular-bounded.
error
line 19 • 'X' doesn't conform to the bound 'num' of the type parameter 'T'.
Try using a type that is or is a subclass of 'num'.
The raw type was instantiated as 'C<X>', and is not regular-bounded.
line 22 • Couldn't infer type parameter 'T'. Tried to infer 'X' for 'T' which doesn't work: Type parameter 'T' is declared to extend 'num' producing 'num'. The type 'X' was inferred from: Parameter '_' declared as 'T' but argument is 'X'. Consider passing explicit type argument(s) to the generic.
```
Nit: "that is or is"?

What's missing is an error in line 13, where I do precisely the same as `C(v1).st<E<X>>;`

I'm allowed to call a method on the result of the invocation, and that method's bound shows that the static type of `C(v1)` is the (not regular-bounded) `C<X>`.

The error in line 22 shows that it's only promoted type variables which are accidentally allowed, not unpromoted ones.

For more fun (likely not related, not sure whether it's right or wrong, or whether it's just giving an error differently), we can add the following at the end of `foo`:
```dart
  // For the lulz:
  const Object? o = 1 as dynamic;
  if (o is! X) return;
  {
    X v1 = o; // Promoted to X
  }
  // o's static type is X
  if (o is! num) return;
  // o's static type is X&num
  {
    X v1 = o;
    num v2 = o;
  }
  // Should not work, inferred type is not const.
  const C(o).st<E<X>>;
```
The error from that (underlining the `o` in the last line) is :
```
Line 35 • A value of type 'int' can't be assigned to a parameter of type 'X' in a const constructor.
Try using a subtype, or removing the keyword 'const'.
```
So we *successfully* pass the inferred type parameter `<X>` to the class, so that we can see the parameter of the constructor will be `X`. It's not a const type, so that should be an error for a const expression, and it's not a subtype of the bound, which is still bad. But it doesn't fail until we try to assign the *value* of `o` to that type, as an argument. (Even though the *expression* is assignable to `X`.)

So likely the same issue as with `C(v1)` above,

That also matches what happens if I add, after the promotion:
```dart
  const c = o;
```
The analyzer says a value of type `int` cannot be assigned to a const variable of type `X`. There is some extra type checking in the analyzer's constant evaluation, based on the actual constant value, on top of the static assignability of the expression. 
Which saves us here. Yey.
(The CFE accepts it, so there I now have a constant with a non-constant type. Only reachable if it's true, but still interesting.)

**Comment by srawlins** [comment]
Analyzer now produces an error on line 13 🎉 . Same message as the other lines.
