### ISSUE TITLE
Front-end does incorrect UP on equivalent promoted type variables.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#52997]
Example:
```dart
// ignore_for_file: unnecessary_cast, unused_local_variable
void main() { foo<num>(false, 0, 0); }

void foo<X>(bool test, X a, X b) {
  if (a is! int) return;
  {
    // UP(T, T) = T  -- success
    var c = (test ? a : a)
      ..toRadixString(2) // Allows int method.
      ..st<E<X>>()  // Erases to X
      ;
    {
      X v1 = c; // Assignable to X
      int v2 = c; // Assignable to int
      c.st<E<X>>; // Erases to X.
      c = a as X;
    }
  }
  
  if (b is! int) return;
  {
    // a : X & int
    // b : X & int
    // "It's the same picture!"
    // 
    // UP(T, T) = T  -- failure :(
    var c = (test ? a : b)
      ..toRadixString(2) // Not defined on Object?
      ..st<E<X>>() // X is not T (Wat?!)
      ;
    {
      X v1 = c;
      int v2 = c; // X not assigable ot int
      c.st<E<X>>; // X is not X
      c = a as X; // X not nullable, X is.
    }
  }  
}

extension Ext<T> on T {
  void st<S extends E<T>>(){}
}
typedef E<T> = T Function(T); // Invariant.
```
Here the first `test ? a : a` successfully takes UP(`X&int`, `X&int`) and gives `X&int`.
This is witnessed to excess by members called directly on the expression via cascades,
and by assignability to/from the variable afterwards.

The second `test ? a : b` gives a different result, even though it should also do UP(`X&int`, `X&int`), it's just `X&int` from two different sources, but it's *the same type*. (Not even after NORM, just plain the same type. Types are structural, they do not have identities, there cannot be two `X & int` types.)

The front-end doesn't recognize that the two types are the same, falls back to the same logic as https://github.com/dart-lang/sdk/issues/52993, and produces the faulty `X`-but-not-nullable type.
All the produced errors (checked in DartPad) match that.

Analyzer has no warnings or errors.

The errors:
```
lib/main.dart:28:9:
Error: The method 'toRadixString' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
      ..toRadixString(2) // Not defined on Object?
        ^^^^^^^^^^^^^
lib/main.dart:29:9:
Error: Type argument 'X Function(X)' doesn't conform to the bound 'T Function(T)' of the type variable 'S' on 'Ext|st'.
      ..st<E<X>>() // X is not T (Wat?!)
        ^
lib/main.dart:41:11:
Info: This is the type variable whose bound isn't conformed to.
  void st<S extends E<T>>(){}
          ^
lib/main.dart:33:16:
Error: A value of type 'X' can't be assigned to a variable of type 'int'.
      int v2 = c; // X not assigable ot int
               ^
lib/main.dart:34:11:
Error: Type argument 'X Function(X)' doesn't conform to the bound 'X Function(X)' of the type variable 'S' on 'void Function<S extends X Function(X)>()'.
      c.st<E<X>>; // X is not X
          ^
lib/main.dart:35:13:
Error: A value of type 'X' can't be assigned to a variable of type 'X' because 'X' is nullable and 'X' isn't.
      c = a as X; // X not nullable, X is.
            ^
Error: Compilation failed.
```

**Comment by chloestefantsova** [comment]
> It seems the identity of the promoted type variable depends on its, well, identity.

Yes, exactly! The rule `UP(T, T) = T` is implemented using `identical` in our code, and using `==` instead of it makes the example compile without errors.

What's the right notion of _equivalence_ on types should be used here? Equality of terms? Any other kind of structural equality? Should we use any sort of type normalization to account for all possible top types?

**Comment by chloestefantsova** [comment]
I'm preparing a CL that uses the term equality instead of identity: https://dart-review.googlesource.com/c/sdk/+/315443. The CL doesn't seem to break anything locally. It should be a safe option to land at least that for now because any other interpretation of equivalence, including those that involve any kind of normalization, will be more permissive.

**Comment by lrhn** [comment]
> What's the right notion of equivalence on types should be used here?

That goes right to the question: What are the entities of the type system?

Dart's type system is an inductively defined "term" system.
A number of types are defined by the specification, fx. the types for `void`, `dynamic`, and `Never`. 
Record types exist for each shape and each choice of type for the field.
Function types exist for each possible parameter list shape and type per parameter and tror type, and each possible type parameter list and choice of type parameter bound type, for genetic function types.
For each type `T`, `T?` and `FutureOr<T>` is a type.

For each nominative type, and valid type argument list, we have a type.

And each type variable declaration introduces a type inside it's scope. Outside the scope they'll be bound to another type. And `X & T` is yet another type.

This inductively defined set has one element per proof of inclusion, and each of those is a unique type in the type system. If it is structurally equivalent (ignoring things like order of named parameters, names of bound type variables), then it's the _same_ type.

(We then have a further equivalence on top, which is structural equivalence after normalization, NORM. I can't say when to use that instead. With any luck, it should not make any difference, but here it probably would.)

**Comment by chloestefantsova** [comment]
Thanks for the elaborate response! To my understanding, it confirms that my CL reflects the expected behaviour.

**Comment by eernstg** [comment]
I think it might be dangerous to use `==` on `DartType` representations of Dart types in some situations, because the object identity is used to keep track of types that are distinct even though their representation does not reveal that distinction. In other words, I'd expect `==` to have some false positives.

Of course, this is just something that @johnniwinther told me a long time ago. @johnniwinther, perhaps you'd comment?

**Comment by johnniwinther** [comment]
The `DartType`s from `package:kernel` have no identity, so it always correct to use `==`.

@eernstg I can't recall the conversation you refer to but I guess it was about different type system implementation.

**Comment by eernstg** [comment]
Thanks, @johnniwinther! That's great, by the way! ;-)
