### ISSUE TITLE
When compiled to JS, `>> 0` truncates the number to 32 bits

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#53002]
Consider this program:

```dart
const int x = 9007199254730661;

void test(String s, int i) {
  print(
    '${s.padLeft(4)} '
    '${i.toString().padRight(16)} '
    '${i.toRadixString(16).padLeft(16)}',
  );
}

void main() {
  test('x', x);
  test('x*1', x * 1);
  for (int i = 0; i <= 64; i += 1) {
    test('>>$i', x >> i);
  }
}
```

When compiled to JS (testing using dartpad.dev) the first few lines of the output are:

```
   x 9007199254730661   1fffffffffd7a5
 x*1 9007199254730661   1fffffffffd7a5
 >>0 4294956965               ffffd7a5
 >>1 2147478482               7fffebd2
 >>2 1073739241               3ffff5e9
```

The `>> 0` case (third line) is not the same as the first two lines (the integer directly, and the integer multiplied by 1).

**Comment by Hixie** [comment]
(The equivalent code using `~/` and powers of two works fine.)

**Comment by lrhn** [comment]
All bitwise operators are truncated to 32 bits on the web.


https://dart.dev/guides/language/numbers#bitwise-operations

**Comment by Hixie** [comment]
Ah.
