### ISSUE TITLE
ParameterElement.documentationComment is always null 

### ISSUE THREAD

**Issue by guenth39** [dart-lang/sdk#53019]
When writing lint rules and according fixes with [custom_lint](https://pub.dev/packages/custom_lint) I'm unable to access the constructor parameters documentation comment, it's always null.

```dart
class MyClass {
  MyClass({
    /// I'm not visible in the analyzer
    this.foo,
    /// Me neither
    this.baa,
  });
```

**Comment by blaugold** [comment]
This looks like a duplicate of https://github.com/dart-lang/sdk/issues/43185.
