### ISSUE TITLE
pkg/dds/test/get_cached_cpu_samples_test crashes VM

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#53015]
See https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8774855373411313329/+/u/test_results/new_test_failures__logs_

Happens in https://dart-review.googlesource.com/c/sdk/+/315660

<details>
  <summary>log text</summary>

/======================================================================================\
| pkg/dds/test/get_cached_cpu_samples_test broke (Pass -> RuntimeError, expected Pass) |
\======================================================================================/

--- Command "vm" (took 12.000597s):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-linux --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/pkg/dds/test/get_cached_cpu_samples_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: No UserTags to cache[0m

TESTEE OUT: The Dart VM service is listening on http://127.0.0.1:34359/cMYoBTFUqNg=/

TESTEE ERR: vm-service: isolate(4182116931436611) 'main' has no debugger attached and is paused at start.  Connect to the Dart VM service at http://127.0.0.1:34359/cMYoBTFUqNg=/ to debug.

00:02 [32m+1[0m: Cache CPU samples for provided UserTag name[0m

TESTEE OUT: The Dart VM service is listening on http://127.0.0.1:46691/h3Xyn-8vTJM=/

TESTEE ERR: 
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0xb8
version=3.1.0-edge.11d0f060ef3e34c4a3ed42cbaf554da59e4803ad (be) (Fri Jul 21 23:08:28 2023 +0000) on "linux_x64"
pid=83535, thread=83538, isolate_group=main(0x5607e90b49a0), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=5607e73a5340, vm_instructions=5607e73a5340
fp=7fbf5e2804c0, sp=7fbf5e280470, pc=5607e75d4680
  pc 0x00005607e75d4680 fp 0x00007fbf5e2804c0 dart::SampleBlockBuffer::BuildProcessedSampleBuffer(dart::SampleFilter*, dart::ProcessedSampleBuffer*)+0xb0
  pc 0x00005607e75d8a10 fp 0x00007fbf5e280500 out/ReleaseX64/dart-sdk/bin/dart+0x23cea10
  pc 0x00005607e75d8992 fp 0x00007fbf5e2805a0 dart::Profile::Build(dart::Thread*, dart::SampleFilter*, dart::ProcessedSampleBufferBuilder*)+0x1f2
  pc 0x00005607e75d6282 fp 0x00007fbf5e280cd0 dart::Profiler::ProcessCompletedBlocks(dart::Isolate*)+0xe2
  pc 0x00005607e75d652f fp 0x00007fbf5e280cf0 out/ReleaseX64/dart-sdk/bin/dart+0x23cc52f
  pc 0x00005607e7517ecb fp 0x00007fbf5e280d40 dart::IsolateGroup::ForEachIsolate(std::__2::function<void (dart::Isolate*)>, bool)+0x10b
  pc 0x00005607e75203a6 fp 0x00007fbf5e280d70 out/ReleaseX64/dart-sdk/bin/dart+0x23163a6
  pc 0x00005607e75175f9 fp 0x00007fbf5e280dc0 dart::IsolateGroup::ForEach(std::__2::function<void (dart::IsolateGroup*)>)+0xa9
  pc 0x00005607e751ecf8 fp 0x00007fbf5e280e00 dart::Isolate::VisitIsolates(dart::IsolateVisitor*)+0x38
  pc 0x00005607e75d6168 fp 0x00007fbf5e280e30 dart::SampleBlockProcessor::ThreadMain(unsigned long)+0xa8
  pc 0x00005607e75cf776 fp 0x00007fbf5e280ef0 out/ReleaseX64/dart-sdk/bin/dart+0x23c5776
-- End of DumpStackTrace

00:03 [32m+1[0m[31m -1[0m: Cache CPU samples for provided UserTag name [1m[31m[E][0m[0m

  DartDevelopmentServiceException: Failed to start Dart Development Service

  package:dds/src/dds_impl.dart 136:7                  DartDevelopmentServiceImpl.startService
  ===== asynchronous gap ===========================
  package:dds/dds.dart 97:5                            DartDevelopmentService.startDartDevelopmentService
  ===== asynchronous gap ===========================
  pkg/dds/test/get_cached_cpu_samples_test.dart 71:13  main.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9     Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7     Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9      Invoker._waitForOutstandingCallbacks.<fn>
  

00:03 [32m+1[0m[31m -1[0m: [31mSome tests failed.[0m

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-linux pkg/dds/test/get_cached_cpu_samples_test

</details>

**Comment by alexmarkov** [comment]
Duplicate to https://github.com/dart-lang/sdk/issues/52213.
