### ISSUE TITLE
Expose vm service API to give me ObjRef by object.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#53012]
It is needed for leak_tracker.

So that it does not have to full scan all instances searching for hash code. 
This will also simplify the leak tracker code, as it will not have to account for possible hash code duplicates

**Comment by polina-c** [comment]
@a-siva

**Comment by polina-c** [comment]
Current implementation of object lookup: https://github.com/dart-lang/leak_tracker/blob/10cce1af65da33daf8268e82ca6e4557235c1a25/pkgs/leak_tracker/lib/src/leak_tracking/retaining_path/_retaining_path.dart#L57

Instead I want to pass object, that I can keep with weak reference.

**Comment by polina-c** [comment]
In order to invoke service.getRetainingPath, I need isolateId as well. Is there a way to get it? If no, is it possible to expose Service.getIsolateIdForObject as well?

**Comment by bkonyi** [comment]
> possible

You're looking for [`Service.getIsolateId`](https://api.dart.dev/dev/3.2.0-94.0.dev/dart-developer/Service/getIsolateId.html).

**Comment by derekxu16** [comment]
I think you also need `Isolate.current` from `dart:isolate` (https://api.flutter.dev/flutter/dart-isolate/Isolate/current.html).

**Comment by polina-c** [comment]
> > possible
> 
> You're looking for [`Service.getIsolateId`](https://api.dart.dev/dev/3.2.0-94.0.dev/dart-developer/Service/getIsolateId.html).

It wants Isolate as parameter

**Comment by bkonyi** [comment]
Yes, you can get that with `Isolate.current` as Derek pointed out.

**Comment by polina-c** [comment]
> I think you also need `Isolate.current` from `dart:isolate` (https://api.flutter.dev/flutter/dart-isolate/Isolate/current.html).

I tried to use it and got confused. 
getRetainingPath wants `String isolateId`, while I do not see anything close in the Isolate in dart:isolate: https://api.flutter.dev/flutter/dart-isolate/Isolate-class.html

@derekxu16, can you help me to figure this out?
