### ISSUE TITLE
[analysis_server] Autocompletion suggestion for redirecting factory constructors shouldn't add arguments

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#53016]
When auto-completing a call to another constructor when declaring a redirecting factory constructor, arguments shouldn't be added to the result since they can't be specified.

```dart
class A {
  A.a(int value);

  factory A.b(int value) = A[!]
}
```

Autocompleting at the `[!]` results in:

```dart
class A {
  A.a(int value);

  factory A.b(int value) = A.a(value)
}
```

I would expect:

```dart
class A {
  A.a(int value);

  factory A.b(int value) = A.a
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/356141
