### ISSUE TITLE
Failures on [analysis_server] Add tests for Windows drive letter encoded colon issue...[dart2wasm] New typed data implementation

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53025]
There are new test failures on [[analysis_server] Add tests for Windows drive letter encoded colon issue...[dart2wasm] New typed data implementation](https://github.com/dart-lang/sdk/compare/0f54180b512e3ddfffcf0f9ba2968655747b4230~...d53070ac758e3668f0cdc8e346b6eb8ca15a7534).

The tests
```
standalone_2/io/io_override_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-debug-x64
dartk-linux-release-x64
dartkp-linux-debug-x64
dartkp-linux-release-x64
```

```
--- Command "vm" (took 05.000160s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-sound-null-safety -Dtest_runner.configuration=dartk-linux-debug-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone_2/io/io_override_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.isNull(actual: <Instance of '_BroadcastStream<FileSystemEvent>'>) fails.
#0      Expect._fail (package:expect/expect.dart:696:5)
#1      Expect.isNull (package:expect/expect.dart:141:5)
#2      ioOverridesRunTest.<anonymous closure> (file:///b/s/w/ir/tests/standalone_2/io/io_override_test.dart:221:14)
<asynchronous suspension>
#3      ioOverridesRunTest (file:///b/s/w/ir/tests/standalone_2/io/io_override_test.dart:253:3)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/tests/standalone_2/io/io_override_test.dart:283:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-linux-debug-x64 standalone_2/io/io_override_test
```

https://dart-ci.appspot.com/log/vm-kernel-linux-debug-x64/dartk-linux-debug-x64/21500/standalone_2/io/io_override_test

I suspect: 1861faef4a487c71e6916e1596e51b7d704ce4a9 Make `_IOOverridesScope` have final fields.

cc @lrhn

```
$ tools/bisect.dart -Dend=0f54180b512e3ddfffcf0f9ba2968655747b4230 -Dstart=d53070ac758e3668f0cdc8e346b6eb8ca15a7534 -Dtest_command="tools/test.py --build -n dartk-linux-release-x64 standalone_2/io/io_override_test" -Dfailure_string="Expect.isNull(actual: <Instance of '_BroadcastStream<FileSystemEvent>'>) fails."
```

Ensuring failure reproduces on d53070ac758e3668f0cdc8e346b6eb8ca15a7534.
Commit d53070ac758e3668f0cdc8e346b6eb8ca15a7534, reproduces failure.
Ensuring failure does not reproduce on 9692a9dfefd.
Commit 9692a9dfefd, does not reproduce failure.
Bisecting d53070ac758...1861faef4a4 (14 commits). Trying a458bab09a6.
Commit a458bab09a6, reproduces failure.
Bisecting a458bab09a6...1861faef4a4 (7 commits). Trying 7dc587d344b.
Commit 7dc587d344b, reproduces failure.
Bisecting 7dc587d344b...1861faef4a4 (4 commits). Trying 2172993731d.
Commit 2172993731d, reproduces failure.
Bisecting 2172993731d...1861faef4a4 (2 commits). Trying 1861faef4a4.
Commit 1861faef4a4, reproduces failure.
Bisected to 1861faef4a4.

**Comment by lrhn** [comment]
Problem comes from the new code assuming sound null safety, and the test being run with unsound null safety, and returning `null` from an override that shouldn't be able to. 
The new code treats that the same as not having an override, and falls back on default behavior.

Since this is legacy behavior, which will be completely impossible real-soon-now, and no actual code broke from the change, I'll just mark the test as failing.
