### ISSUE TITLE
Warning message "Neither type of the operands of '==' is a subtype of the other" not showing

### ISSUE THREAD

**Issue by kattaliraees** [dart-lang/sdk#53022]
This tracker is for issues related to:
* Analyzer

* Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_arm64"

The below piece of code is not giving any compiler error or warning messages when using the dart SDK on my Mac or Windows. But when I tried the same code in [dart pad](https://dartpad.dev/) it gave a proper warning message. This caused an issue to us assuming all integers with values greater than 0 will be considered as true which it didn't and also didn't give any compile time error or analyzer warning. 

When I checked further, any 2 types can be compared using '==' operator, and no warning is shown (showing in Dart pad though)

![Screenshot 2023-07-24 at 12 06 08 PM](https://github.com/dart-lang/sdk/assets/574396/0ee9a025-f6cb-462a-92ca-f58ee427699d)

![Screenshot 2023-07-24 at 12 12 34 PM](https://github.com/dart-lang/sdk/assets/574396/f1237b6c-9e22-4368-b694-7fa3d0312464)

```dart
void main() {
  if (getStatus() == true) {
    print('true');
  } else {
    print('false');
  }
}

int getStatus() {
  return 1;
}
```

**Comment by kattaliraees** [comment]
I have checked in Java, C#, Go, and Swift. All these languages give compile time errors for the above code. (I mean if we compare 2 different types with ==)

**Comment by eernstg** [comment]
It's not unthinkable that this kind of test could make sense:

```dart
class A {}
class B {}
class C implements A, B {}

void main() {
  C c = C();
  A a = c;
  B b = c;
  print(a == b); // 'true'.
}
```

The lint is there because it's _unlikely_ to be a meaningful test, and that's as far as the facts will take us.
