### ISSUE TITLE
[Analyzer] Spurious errors for named constant keys in map patterns

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#53029]
Given a constant `someKey` in a library:

```dart
// lib.dart
const someKey = 'someKey';
```

I'm seeing some inconsistent behavior when using `someKey` in map patterns.  Specifically, the following code is rejected by the analyzer:

```dart
import "lib.dart";
void test(Map<String, String> m) {
  if (m case {someKey : final String s}) ; // Error
}
```

with the following error message:

```
  error • example.dart:69:15 • Key expressions in map patterns must be constants. Try using constants instead. •
          non_constant_map_pattern_key
```

If I add a local constant definition to rename `someKey`, the error goes away:

```dart
import "lib.dart";
void test(Map<String, String> m) {
  const key = someKey;
  if (m case {key : final String s}) ; // No error
}
```

Interestingly, adding the local const definition alone (but continuing to use the non-local name in the pattern) is sufficient to fix the error:

```dart
import "lib.dart";
void test(Map<String, String> m) {
  const key = someKey;  // Adding this line alone is enough to remove the error from the first example above
  if (m case {someKey : final String s}) ; // No error, despite error in the same code above
}
```

cc @srawlins @bwilkerson @scheglov

**Comment by scheglov** [comment]
I suspect that I failed to include keys of map patterns as dependencies of constants.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/316081
