### ISSUE TITLE
non_constant_identifier_names "fix all in file" appears in locations where the fix is not available

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#53021]
Given this code:

```dart
var aaa_aaa = '';

void f() {
  final bbb_bbb = 0;
}
```

The second variable has a fix for the non_constant_identifier_name violation to rename the variable:

![image](https://github.com/dart-lang/sdk/assets/1078012/e25da7bb-9d26-4fbb-8f86-736f0635167b)

However the first variable only has a "fix all in file" without an individual fix:

![image](https://github.com/dart-lang/sdk/assets/1078012/b6223863-a52c-4da1-b457-8c166d7660d0)

If you comment out the second line of code, it doesn't have any fix:

![image](https://github.com/dart-lang/sdk/assets/1078012/cc3639e5-2774-4005-a93c-5b4ee37e68d6)

**Comment by DanTup** [comment]
I think this is because the block here that looks for references doesn't have a case for top-levels:

https://github.com/dart-lang/sdk/blob/4bb8312b4a26795a840326d40d9e85657e8d1017/pkg/analysis_server/lib/src/services/correction/dart/rename_to_camel_case.dart#L74

And if no case is handled, `references == null` which exits without computing a fix:

https://github.com/dart-lang/sdk/blob/4bb8312b4a26795a840326d40d9e85657e8d1017/pkg/analysis_server/lib/src/services/correction/dart/rename_to_camel_case.dart#L93-L95

I'm not sure if this is deliberate (finding references to top-levels is presumably much more expensive than locals and these fixes are computed frequently), but perhaps if that's the case the "Rename everywhere in file" option shouldn't be showing up where there isn't a single version?

**Comment by bwilkerson** [comment]
> I'm not sure if this is deliberate ...

Yes, that's deliberate. The primary difference between a quick fix and a refactoring is that fixes can't (for performance reasons) look outside the local library.

> ... but perhaps if that's the case the "Rename everywhere in file" option shouldn't be showing up where there isn't a single version?

I'm not sure what you mean by "single version", but no, the fix-all shouldn't be showing up in any location when there's no individual fix in that location, regardless of which diagnostic the fix is associated with (in other words, the real bug is bigger than just this one example).
