### ISSUE TITLE
DateTime(1991,4,14,2,0) init with a bug

### ISSUE THREAD

**Issue by sophimp** [dart-lang/sdk#53032]
This tracker is for issues related to:

Dart core libraries: DateTime

Dart SDK version: 2.19.6 (stable) (Tue Jul 25 15:02:04 2023 +0000) on "windows 10"

Example:

  final DateTime date = DateTime(1991,4,14,2,0);
  print(date);  // 1991-04-14 03:00:00.000

The result hour is 3, but input is 2.

**Comment by julemand101** [comment]
Can I ask what timezone you are using on your device?

**Comment by lrhn** [comment]
I'm guessing China, which switched to DST on April 14, 1991, which means that there is no 2 AM that day.

**Comment by sophimp** [comment]
Yeah,  my timezone is UTC/GMT+08:00（Asia/shanghai), like @lrhn said, it seems not a bug,  I think this issue can be closed.
