### ISSUE TITLE
The matched value type 'T?' can never be equal to this constant of type 'Null'. 

### ISSUE THREAD

**Issue by maprohu** [dart-lang/sdk#53033]
Hi!

I write a small dart program and put it in a package directory (lib/sandbox.dart):

```dart
void someMethod<T extends Object>(T? value) {
  switch (value) {
    case null: // gives a warning: constant_pattern_never_matches_value_type
      print('matched');
  }
}

void main() {
  someMethod<int>(null); // prints "matched"
}
```

When I run `dart analyze` on this package I get the following:

```
% dart analyze
Analyzing sandbox...                   0.5s

warning • lib/sandbox.dart:3:10 • The matched value type 'T?' can never be equal to this constant of type 'Null'. Try a constant of the same type as the matched value type. • constant_pattern_never_matches_value_type

1 issue found.
```

So it warns me that the `null` constant will never be matched. Running the program prints "matched" so it does get matched anyway. Removing the `extends Object` constraint makes the warning message go away.

pubspec.yaml is minimal:

```yaml
name: sandbox
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.0.6
```

```
% dart --version
Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_arm64"
```

Cheers,
Marton

**Comment by eernstg** [comment]
This seems to have been fixed: DartPad, beta channel and master channel do not emit this warning.

**Comment by maprohu** [comment]
@eernstg 
Thanks Erik! Also for pointing me to DartPad, never really tried it before. Looks useful.
