### ISSUE TITLE
[incremental compiler] Cannot compile expression containing extension type

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#53036]
Expression compilation of an expression that uses an extension type currently fails to find the extension type (do we need to add an `import self as self` to the synthetic library that is created for expression compilation in the incremental compiler?)

Example: 

<img width="863" alt="image" src="https://github.com/dart-lang/sdk/assets/12737689/efc672f4-1b77-491a-b9d7-dc72bb73ad39">

**Comment by johnniwinther** [comment]
Extension types are still not supported when loaded from dill files. I'll work on it.

**Comment by annagrin** [comment]
> Extension types are still not supported when loaded from dill files. I'll work on it.

Thanks! Forgot to mention - this is happening for both web expression compiler and vm. I haven't tried it with the frontend server though.

**Comment by johnniwinther** [comment]
https://dart-review.googlesource.com/c/sdk/+/316580 has landed support for extension types from dill. @annagrin can you check if the problem persists?
