### ISSUE TITLE
Cannot install SDK using apt-get

### ISSUE THREAD

**Issue by mstewart-altroninc** [dart-lang/sdk#53045]
as of about an hour ago, I cannot install the dart SDK using apt-get. It looks like there was an update today around that time, so I suspect something is wrong. This install is being performed according the directions for linux installations (using apt-get) located here https://dart.dev/get-dart. The result is an error about the signature being invalid; is there a chance this new release is missing some certificate its supposed to have? The errors are as follows:

W: GPG error: https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release: The following signatures were invalid: BADSIG 4EB27DB2A3B88B8B Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>
E: The repository 'https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release' is not signed.

**Comment by mkorbel1** [comment]
I'm hitting the same thing.  It is reliably reproducible in the GitHub codespace container build for https://github.com/intel/rohd, if it is helpful.

**Comment by mkorbel1** [comment]
Also, looks like this is the same as #53044 (filed just 2 min earlier)

**Comment by WangWeiNing** [comment]
same issue here

**Comment by bitwerkstatt** [comment]
Issue can also be reproduced on my machine.

**Comment by cbatson** [comment]
FWIW, before seeing this, I submitted a description of the issue to linux-packages-keymaster@google.com. Will report back here with anything I learn.

**Comment by whesse** [comment]
We published beta and stable at the same time, and they both tried to sign their package repositories in the same signing directory at the same time, giving corrupted signatures.  We are rerunning the package signing now, one after the other.

**Comment by whesse** [comment]
All three channels are working again. The instructions at https://dart.dev/get-dart are for the stable channel.
To install the beta and dev channels for apt-get, run the last line of the one-time setup with the word stable replaced by "testing" or "unstable" in the two places it occurs: (shown for testing)

    echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian testing main' | sudo tee /etc/apt/sources.list.d/dart_testing.list

 The install command for beta is then

    sudo apt-get -t testing install dart
