### ISSUE TITLE
Add opportunity to force user of function to handle exception

### ISSUE THREAD

**Issue by machinescream** [dart-lang/sdk#53058]
Something similar to throwable from Java maybe?

**Comment by lrhn** [comment]
I think that's #984.

**Comment by machinescream** [comment]
required onError callback as an alternative, right?

**Comment by lrhn** [comment]
I don't think people manually calling `Future.then` is going to be the main issue. Most people use `await` instead. If we never make it work for direct use of futures, just normal functions and awaited async functions, it'll probably be adequate.

And just making it work for synchronous functions is hard enough.
