### ISSUE TITLE
`unused_local_variable`: false positive when used with switch expression

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#53057]
**Describe the issue**
There's currently a false positive when using cascading functions with a switch expression.

**To Reproduce**
The following code snippet:
```dart

class Foo {
  void function() {}
}

void f() {
  final Foo foo = switch (true) {
    _ => Foo(),
  }..function()..function();
}
```

Produces: `The value of the local variable 'foo' isn't used.` However, removing `foo` causes a compile error.

**Comment by Pante** [comment]
> Can you explain how `foo` is used. I cannot see it myself.

I'm not sure if it's a good explanation, but `foo` is used only to allow cascading method calls on it.

**Comment by srawlins** [comment]
I think `switch` is then parsed as a switch statement rather than a switch expression.
