### ISSUE TITLE
Server error: "Missing implementation of visitFunctionExpression"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#53075]
Raised at https://github.com/Dart-Code/Dart-Code/issues/4666, I was able to reduce it to this (it seems to require `const` on the constructor and the function call in the `assert`):

```dart
class StylishBottomBar  {
  const StylishBottomBar({
    List<String?> items,
  }) : assert(items.every((String? item) => item != null));
}
```

It causes the server to terminate with the following in the log:

```
[12:12:14 PM] [Analyzer] [Error] Unhandled exception:
Exception: Missing implementation of visitFunctionExpression
#0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2842:5)
#1      ThrowingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:2514:58)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6124:50)
#3      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:939:19)
#4      AstBinaryWriter.visitArgumentList …
```

I'm not sure why the calls tack is truncated, but below is a screenshot of it in the debugger (I couldn't dump it as text, sorry).

![Screenshot 2023-07-31 122607](https://github.com/dart-lang/sdk/assets/1078012/b6259c6a-a350-4f8a-b401-c64c982dc44c)

(@scheglov FYI)

**Comment by srawlins** [comment]
CC @kallentu , looks like a bug specific to const constructor asserts; you probably have the freshest notion of this code :)

**Comment by kallentu** [comment]
I looked into what makes the difference between const and non-consting that constructor and it's the call of this line: https://github.com/dart-lang/sdk/blob/d9363a6639d4adf716f4714d4907a7d2b1d2cb6e/pkg/analyzer/lib/src/summary2/bundle_writer.dart#L208

And all this happens without ever entering the constant evaluator, so I suspect @scheglov might have more context on this?

The `_constantInitializers` do have a `FunctionExpression` in there (`(String? item) => item != null`) and the `AstBinaryWriter` doesn't implement it, but I'm not sure if it's as straight forward as making a `visitFunctionExpression` or if something else is wrong up the pipeline.

**Comment by shashkiranr** [comment]
Hi,

Any Workaround for this issue? The dart analyser keeps failing and the auto complete feature in Android Studio for Flutter seems to fail with it in classes where const constructor and assert are used and referenced

**Comment by kallentu** [comment]
@srawlins I can take a go at fixing this. I was taking a look at it yesterday.

**Comment by scheglov** [comment]
We might need to use `replaceNotSerializableNode` in one more place.
