### ISSUE TITLE
DAP threadIds can currently be 53bit integers but the DAP spec specifies 32bit integers

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#53086]
We recently started using `Isolate.number`s from the VM Service as the `threadId`s in the debug adapter. It turned out that these numbers were random 64bit numbers and could easily be values that aren't precisely representable in languages that use 64bit floating point numbers.

This was fixed via #53081 by reducing these numbers to 53bits.

However, with some more digging it's not clear that 53bit integers are allowed in DAP either. The spec says:

> integers defined in the protocol (JSON schema type `integer`) may be represented as 32 bit signed integers, although some properties disallow negative values. numbers in the protocol (JSON schema type `number`) may be represented as 64 bit floating point numbers.

Although the [online spec](https://microsoft.github.io/debug-adapter-protocol/specification) has `threadId` as `number`, the [JSON spec](https://microsoft.github.io/debug-adapter-protocol/debugAdapterProtocol.json) uses `integer`.

Assuming the correct type is `integer`, this means we cannot use > 32bits for `threadIds`. This would mean either:

1. The VM Service IDs need reducing further from 53bit to 32bit integers
2. We should stop using the `Isolate.number` directly as `threadId` and instead add a custom API for mapping back and forth

@bkonyi @jacob314 thoughts/opinions?

(cc @elliette @christopherfujino)

Related:

- https://github.com/microsoft/debug-adapter-protocol/issues/422
- https://github.com/mfussenegger/nvim-dap/issues/1004
- https://github.com/dart-lang/sdk/issues/53081

**Comment by bkonyi** [comment]
After chatting with @rmacnak-google, I don't think we'll be able to reduce the ID space any further. The isolate ID is really the isolate's main port and is meant to be "unguessable", so reducing the ID space weakens this property (ideally we'd have a 128-bit ID).

If the DAP requires 32-bit thread IDs, we'll need to take a different approach that involves mapping between isolate and thread IDs.

**Comment by rmacnak-google** [comment]
Right, send ports are [capabilities](https://en.wikipedia.org/wiki/Capability-based_security) and their IDs should be [Swiss numbers](http://wiki.erights.org/wiki/Swiss_number).

**Comment by DanTup** [comment]
@elliette would it work for you if we include isolateIds in the response to DAP `threads`? It means you'd need to call DAP for `threads` but from the response you'd have a mapping of `threadId <-> isolateId` (which you can cache and just re-call `threads` if you discover a thread/isolate that's not in your cache).

A change for this is here (the extra fields are only included over DDS to avoid the non-standard field for standard DAP clients):

https://dart-review.googlesource.com/c/sdk/+/317701

Which depends on this change that reverts the original code:

https://dart-review.googlesource.com/c/sdk/+/317700

We can land these together and then you could switch over.

**Comment by elliette** [comment]
Thanks works for me, thank you!

**Comment by DanTup** [comment]
Great, thanks for confirming! I've opened reviews for them.

**Comment by DanTup** [comment]
The quote above about not using 32bits was because of what's written in the DAP spec - it seems like that might be more restrictive. I think we should stick to > 32bits for DAP integers.

This issue was fixed by going back to increasing integers starting at 1 for `threadId`s, but it seems the Flutter stable release unfortunately ended up with a DDS release between the break and the revert 😞

**Comment by christopherfujino** [comment]
CP request [here](https://github.com/flutter/flutter/issues/139177)
