### ISSUE TITLE
Many co19 async tests are timing out flakily on dartdevc and dart2js

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#53098]
Up to 5 percent of the time on our dartdevc and dart2js builders is spent running tests that time out.
Almost all of these are tests of async behavior in the co19 and legacy co19_2 test suites.
They are timing out about half the time or less, and take 5 seconds or less to run normally, and time out after a minute when they time out.

I haven't had much success reproducing this locally, running the same configurations and settings as the test runners.

I would like to skip these tests, to speed up the commit queue, since they are not effective in finding any errors.
Even new runtime failures would not show up, because the tests are already marked flaky.

We should also find the source of these failures, and fix it. That is my first priority, to get agreement on skipping these tests.

I notice that the dartdevc testing is reporting most of these tests as "double reporting tests", and this may have to do
with the way the test runner detects that a dartdevc test has an async main method, and the handling of asyncStart and asyncEnd helpers for these tests.  This was worked on recently in CL https://dart-review.googlesource.com/c/sdk/+/265564

Here are some links and tables showing the problem.  I have copied the tables of flakiness data from the flakiness explorer:
![image](https://github.com/dart-lang/sdk/assets/4905639/8831e35d-030f-4710-bf10-761d2a046937)

This is a current results view that shows the relevant flaky tests: https://dart-current-results.web.app/#/filter=co19_2/LibTest/async,co19/LibTest/async,dart2js-,ddc-&flaky

And here is some information showing the four most used dart web try builders, and the number of seconds they spend running tests that time out:
 ```
 "builder":                    "timeoutTime" "countTimeouts"  "countTests"  "testTime"   
dart2js-hostasserts-linux-unsound  8193,              26,         39850,       179824   5%
ddc-linux-chrome-unsound           1951,              26,         39424,        40647   5%
ddc-linux-chrome                   1035,              14,         20481,        20614   5%
dart2js-linux-chrome                544,               8,         20654,        60251   1% 
```

**Comment by whesse** [comment]
More of the flakiness dashboard:  Use filters Active = True and Name contains LibTest/async.

![image](https://github.com/dart-lang/sdk/assets/4905639/b94c0689-3734-4efb-9360-895d286826ae)

**Comment by whesse** [comment]
The double-reporting issue is due to the fact that dartdevc test running automatically uses the async_helpers package for testing, and hooks it into all async operations using dartdevc hooks addAsyncCallback.

co19 tests use their own async helper tracking, that calls its own asyncStart() and asyncEnd() to track chosen async calls, and ensure that they complete before the test is considered finished.

Both these packages communicate with the browser test infrastructure, and both send the 'unittest-suite-wait-for-done' and 'unittest-suite-done' messages to it.  The infrastructure code is not that smart, and just sends "PASS" the first time it sees the unittest-suite-done message.

So this is strange, and causes warnings, but strangely does not seem to be the cause of any failures.  The double-reporting tests will not be tracked further on this issue, since it doesn't seem to be the cause of the flaky timeouts, which are happening identically on dart2js and dartdevc.

**Comment by whesse** [comment]
The list of tests skipped on co19_2 and co19 due to flakily or consistently timing out more than 10% of the time is:

co19_2 ddc:
```
[ $compiler == ddc && $runtime == chrome ]
Language/Statements/Yield_and_Yield_Each/Yield/execution_async_t04: Skip # Times out flakily
LibTest/async/Future/forEach_A01_t03: Skip # Times out flakily
LibTest/async/Stream/Stream.fromFutures_A04_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A01_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A02_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A03_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A04_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A04_t02: Skip # Times out flakily
LibTest/async/StreamController/stream_A02_t01: Skip # Times out flakily
LibTest/async/StreamController/stream_A03_t01: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_A08_t02: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_A09_t01: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_A10_t01: Skip # Times out flakily
LibTest/async/Timer/isActive_A01_t02: Skip # Times out flakily
LibTest/async/Timer/Timer.periodic_A01_t01: Skip # Times out flakily
LibTest/async/Zone/createPeriodicTimer_A01_t01: Skip # Times out flakily
LibTest/core/Stopwatch/elapsedMicroseconds_A01_t01: Skip # Times out flakily
LibTest/core/Stopwatch/elapsedMilliseconds_A01_t01: Skip # Times out flakily
LibTest/core/Stopwatch/elapsedTicks_A01_t01: Skip # Times out flakily
LibTest/core/Stopwatch/elapsedTicks_A01_t02: Skip # Times out flakily
LibTest/core/Stopwatch/elapsedTicks_A01_t03: Skip # Times out flakily
LibTest/core/Stopwatch/stop_A01_t01: Skip # Times out flakily
LibTest/html/Window/animationFrame_A01_t01: Skip # Times out flakily
```

co19_2 dart2js
```
[ $compiler == dart2js && $runtime == chrome ]
Language/Statements/Yield_and_Yield_Each/Yield/execution_async_t04: Skip # Times out flakily
LibTest/async/Stream/Stream.fromFutures_A04_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A02_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A04_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A04_t02: Skip # Times out flakily
LibTest/async/StreamController/stream_A02_t01: Skip # Times out flakily
LibTest/async/StreamController/stream_A03_t01: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_A08_t02: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_A09_t01: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_A10_t01: Skip # Times out flakily
LibTest/async/Timer/Timer.periodic_A01_t01: Skip # Times out flakily
LibTest/core/Stopwatch/stop_A01_t01: Skip # Times out flakily
LibTest/html/Element/loadEvent_A01_t01: Skip # Times out
LibTest/html/Element/mouseWheelEvent_A01_t01: Skip # Times out
LibTest/html/Element/onLoad_A01_t01: Skip # Times out
LibTest/html/Element/onMouseWheel_A01_t01: Skip # Times out
LibTest/html/Element/onTransitionEnd_A01_t01: Skip # Times out
LibTest/html/Element/transitionEndEvent_A01_t01: Skip # Times out
LibTest/html/HttpRequest/onError_A01_t02: Skip # Times out
LibTest/html/HttpRequest/responseText_A01_t02: Skip # Times out
LibTest/html/HttpRequestUpload/onError_A01_t02: Skip # Times out
LibTest/html/HttpRequestUpload/onLoadEnd_A01_t01: Skip # Times out
LibTest/html/HttpRequestUpload/onLoadStart_A01_t01: Skip # Times out
LibTest/html/HttpRequestUpload/onLoad_A01_t01: Skip # Times out
LibTest/html/IFrameElement/blur_A01_t01: Skip # Times out flakily
LibTest/html/IFrameElement/focus_A01_t01: Skip # Times out flakily
LibTest/html/IFrameElement/onMouseWheel_A01_t01: Skip # Times out
LibTest/html/IFrameElement/onTransitionEnd_A01_t01: Skip # Times out
LibTest/html/Window/animationFrame_A01_t01: Skip # Times out flakily
```

and co19 ddc and dart2js:
```
Language/Statements/Yield_and_Yield_Each/Yield/execution_async_A03_t03: Skip # Times out flakily
LibTest/async/Future/forEach_A01_t03: Skip # Times out flakily
LibTest/async/Stream/Stream.fromFutures_all_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A01_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A02_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_A03_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_all_t01: Skip # Times out flakily
LibTest/async/Stream/Stream.periodic_all_t02: Skip # Times out flakily
LibTest/async/StreamController/stream_all_A01_t01: Skip # Times out flakily
LibTest/async/StreamController/stream_all_A02_t01: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_A08_t02: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_Stream_all_A01_t01: Skip # Times out flakily
LibTest/async/StreamController/StreamController.broadcast_Stream_all_A02_t01: Skip # Times out flakily
LibTest/async/Timer/Timer.periodic_A01_t01: Skip # Times out flakily
LibTest/async/Zone/createPeriodicTimer_A01_t01: Skip # Times out flakily
LibTest/core/Stopwatch/stop_A01_t01: Skip # Times out flakily
LibTest/html/Window/animationFrame_A01_t01: Skip # Times out flakily
```

**Comment by rakudrama** [comment]
I am worried skipping tests when we don't know whether it is the headless browser, test infra or web implementation runtimes.
There are non-async tests that are flaky only in when the tests are run on the try-bots (e.g. the "blur" one).

When the tests time out, are they busy, or are they finished, but just in a way that the test harness fails to detect?
Are the thousands of seconds billable cpu or just wallclock delay to getting the test suite done?

Could the tests be sharded so that all the bad ones are in one small shard that can be retried early?

I might be a little less worried if the proposal was to skip just the legacy "_2" tests.

**Comment by whesse** [comment]
The tests are hanging, or completing In A way that is not detected, not
just slow. As long as the hanging can be reproduced locally, I would like
the work on fixing it to be done while the tests are skipped in the ci,
since they give no useful information on the ci, except that they hang half
the time.  I don't think keeping them running on the ci gives any further
urgency to fixing them, since they have been hanging for years, probably,
without anyone filing an issue.  They are taking 5% on the test time on
those builders, which increases the latency of all builders during peak
times, not just the dart web ones.

**Comment by nshahan** [comment]
Overall we are strongly in favor of saving resources and time spent running the web trybots but are nervous about just skipping the tests. We had a team discussion today to brainstorm alternative ideas. Here are some key points that maybe you could comment on:

We are unsure how to even begin investigating these timeouts. In our experience we haven't been able to reproduce the problem locally. If we skipped them how can we work towards running them again?

From our perspective, marking tests as skipped is just one step away from simply deleting the test. We lose all coverage, and the ability to see the recent history using the Results Feed.

Possible alternatives to skipping the tests:
- Configure these tests to not retry on timeout.
- Configure these tests to have shorter timeouts.
- Somehow run this subset of tests less frequently.
- Create configurations that runs less frequently that where we can quarantine tests like these until we know how to solve the issue.

@sigmundch @rakudrama @fishythefish 
Feel free to comment or edit if I missed anything from our discussion.

**Comment by fishythefish** [comment]
I think being able to specify a shorter timeout and/or fewer retries would be preferable. It was noted that running these tests less frequently may be a problem - if something causes the tests to start producing consistent results, it'll take longer for the flakiness to be cleared.

**Comment by whesse** [comment]
I investigated these timeouts, trying to reproduce them, and I could only reproduce them when the test tab went into the background or was hidden.  I have a CL that may fix all or most of these, https://dart-review.googlesource.com/c/sdk/+/325780. If that fixes them, then further discussion isn't needed, except that
other, more individually timing out tests should be skipped when gardening the rest of the non-co19 tests, and
we may have the same discussion for them.

If this fix does stop the timeouts, then probably some currently-skipped tests or slow tests should be investigated to see if they have been fixed as well.

Addressing the concerns about skipping these tests:

There is no retrying of these tests on timeout.  The only retry that ever happens is in the deflaking step, so once tests are flakey, there are no retries.

They could have shorter timeouts, but they still give no useful information by running.

Running tests less frequently requires a separate configuration, since otherwise they will appear to change from new test to skipped and back. But if we want to run all timing-out skipped tests, to see if some of them start having runtime failures, or start passing quickly, then that could be a long-term project that should apply to all skipped tests on all configurations.

Regarding running them less frequently and flakiness - there has recently been a change that makes flakiness expire after only one week.  So if these ran daily, then only 7 runs with the same result would mark them stable again, and put a new failure (possibly) on the results feed that would need to be approved.  They would also run 5 times then for deflaking, taking time again.

Quarantining these tests until the issue is fixed is exactly what skipping them and filing an issue is.

The skipped tests can be run on try bots by running tryjobs on a CL that unskips them.

I am unclear on what the purpose would be of running these tests, but less frequently, or with less impact.
Exactly what info would be looked as a result of running these, by who, and when? It doesn't seem like it could
help the person working on debugging this problem at all, and it doesn't seem like it would be meaningful in any
other way.

It is extremely unlikely that these tests will fix themselves, but possible that they could start having a runtime error or start timing out consistently.  A consistent timeout would not lead to any more action, since they are already marked as timing out in an active issue.

If the concern is that by skipping them, they will be forgotten, or fixing them will be deprioritized, that seems misguided, because they are already very effectively forgotten and deprioritized now, since they are (mostly) marked flaky.  Active issues, or some other way of tracking work, should be effective, and some mostly-ignorable status that is hidden in deeper links of the results UI does not seem like it should be relied on.

**Comment by sigmundch** [comment]
Thanks so much for taking a closer look @whesse! I have also been debugging and trying to repro some of these issues in the lasts several days.

**regarding the test behavior**
In my investigation I saw some of the tests are not written accounting for how browsers behave. For example, some tests expect that `setTimeout` will only trigger after the requested period, but browsers sometimes trigger it early. In my local testing in chrome, I used a `setInterval` of `100`, and saw 50% of events firing early, mostly in `96ms` and `97ms`.

I was expecting tests relying on this to sometimes report runtime failures. In FF one of those tests indeed flaked between Pass/RuntimeError, but in chrome it flaked between Pass/Timeout. This inconsistency between browsers was suspicious and I thought maybe there could be an infrastructure issue in either how the browser driver communicates with the browser iframe, or something to do with async-helper. The issue you just discovered could totally explain this too (btw, that's an amazing discovery!).


**regarding skip vs non skip**

I found the dashboards with historical data about flakes to be extremely helpful in the investigation. Seeing the distributions of how many times tests timed out vs passed vs failed also helps prioritize the process (e.g. I focused on tests with >50% flakes, instead of 3% flakes). I worry that this kind of data would be unavailable if we mark a test as skipped. We would be able to recover that kind of data by reenabling a skipped test on a CL and testing it in the try bots alone.

That's why we were brainstorming how we can address the current costs without loosing the ability to track that a test was and continues to flake. Our hope is that we could find a way to bound the cost of the flaky tests to be roughly close to the cost of non-flaky tests. Ironically, the suggestion we think will help the most here is to give those tests a tighter time bound (e.g. 20s or less)

**Comment by whesse** [comment]
I think the flakiness data will remain in the dashboard even if the test is skipped (and it remains in flaky.json in cloud storage), it just won't have new data added to it.

But once the number of timing-out flaky tests is reduced to a more manageable number, adding a timeout that is closer to the passing time would reduce the amount of extra time wasted.

The time spent on timeouts doesn't just delay the results from that builder - in overloaded periods, it compounds, and increases the latency of all builds by a compounded delay (since the total runtime queued load is increased by multiple instances of the tests, persisting until the queue length drops to 0, perhaps in 6 or 8 hours).

**Comment by whesse** [comment]
By the way, this has inspired me to think about building a flutter app that will download the historical test results for a single configuration, and display for any test the percentage of passes, fails, and timeouts, and the distribution of test runtimes for that test.

There is really no other way to get the distribution of test runtimes for a test, and if we need a program to read JSON data from the web and display it in an interactive graph, there is nothing better to write it in than Flutter.

**Comment by whesse** [comment]
The fix to disable background throttling seems to have worked: All the flaky co19 web tests have been passing for the last 11 runs, since the fix landed:
![image](https://github.com/dart-lang/sdk/assets/4905639/27d65613-62db-4d80-8bd0-54105f0551f0)

I will close this issue, and perhaps open more specific later ones, about skipping some individual tests.

**Comment by nshahan** [comment]
That looks really promising, thanks for finding that Chrome option @whesse! I'm seeing the same thing on DDC configs for most of the flaky tests across all the suites.

**Comment by whesse** [comment]
I wrote a flutter app to load and display the timing data for tests on a configuration (it only took 4 hours!).  Here are graphs of one of these flaky tests, first chronologically, with now on the left, and second sorted by time:
![image](https://github.com/dart-lang/sdk/assets/4905639/4cd8d7e9-c9dd-4262-8bdc-7c5f7beb89c5)
![image](https://github.com/dart-lang/sdk/assets/4905639/06837627-b36f-4dd9-b45e-2422082c2482)

**Comment by sigmundch** [comment]
woohoo! 🎉 that's amazing Bill! So exciting!

**Comment by nshahan** [comment]
@whesse 
>I notice that the dartdevc testing is reporting most of these tests as "double reporting tests", and this may have to do
with the way the test runner detects that a dartdevc test has an async main method, and the handling of asyncStart and asyncEnd helpers for these tests. This was worked on recently in CL https://dart-review.googlesource.com/c/sdk/+/265564

I did touch that code recently to make the implementation agnostic to the two runtime type system we are using at the moment (stable vs canary) but it was double reporting before that too. It has been for many years and I've never understood why.

**Comment by sigmundch** [comment]
@whesse - I have question on a related note:

I was looking at some of the remaining flakes, and came across a couple tests that seem to be timing out during compile-time. On a successful run they take 30s, but sometimes they take over a minute and get interrupted.

See for example pkg/js_ast/test/printer_callback_test.
* A recent timeout: https://dart-ci.appspot.com/log/dart2js-linux-chrome/dart2js-linux-chrome/1352/pkg/js_ast/test/printer_callback_test
* A recent pass under 32s: https://chromium-swarm.appspot.com/task?id=64cd7cae8f162210

I wonder what could be behind the timing differences. Are the various bots different in architecture/resources or are they homogeneous? Are too many jobs scheduled in parallel that we could be starving some processes in the test runner?
