### ISSUE TITLE
Failures on [vm, service] Fix discrepancy between VM generating kind `_TypeParameters` and service.md claiming the existence of kind `TypeParameters`.

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#53093]
There are new test failures on [[vm, service] Fix discrepancy between VM generating kind `_TypeParameters` and service.md claiming the existence of kind `TypeParameters`.](https://github.com/dart-lang/sdk/commit/5e49ea5ad89d3bddf4c6c2dc85bbea54195dfa5e).

The tests
```
service/fetch_all_types_test/dds RuntimeError (expected Pass)
service/fetch_all_types_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-android-release-arm64c
vm-aot-linux-debug-x64
vm-aot-linux-debug-x64c
vm-aot-win-debug-arm64
vm-aot-win-debug-x64c
```

**Comment by rmacnak-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/317800
