### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by chensirui2008** [dart-lang/sdk#53107]
my dart plugin always show **Analysis server has terminated**

## 版本信息

- `IDEA IU-232.8660.185`
- `3.0.6`
- `IU-232.8660.185, JRE 17.0.7+7-b1000.6x64 JetBrains s.r.o., OS Mac OS X(aarch64) v14.0, screens 3600.0x2338.0  Retina`

**Comment by mraleph** [comment]
You need to provide logs. 

@scheglov can you share instructions on how to find analysis server termination reason?

**Comment by scheglov** [comment]
If you have any files in `~/.dartServer/.analysis-driver/ex` please archive them, and send to me scheglov@google.com
Please note, that these files might contain source code for libraries that are referenced by the code under analysis.

**Comment by srawlins** [comment]
There is nothing more to be done with this issue without more details. If you encounter this again, please file a new issue, and include as much detail as you can, or follow @scheglov 's instructions above.
