### ISSUE TITLE
dart2js: toString() breaks for the JS Symbol type

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#53106]
Reproduction:

```dart
import 'package:js/js.dart';

@JS("Symbol")
class JSSymbol {}

@JS("Symbol")
external JSSymbol createJSSymbol(String name);

void main() {
  createJSSymbol("foo").toString();
}
```

Compiling to JS with dart2js (Dart 3.0.7) and running in the browser throws `method not found: 'toString$0' (J.getInterceptor$(...).toString$0 is not a function)`.

**Comment by rakudrama** [comment]
There is likely a similar issue with the other primitive JavaScript type introduced since ES5: `typeof x == "bigint"`.
/cc @nshahan What does DDC do here?

**Comment by nex3** [comment]
I can confirm that this happens for BigInt as well.

**Comment by rakudrama** [comment]
I want to keep open the option of using JavaScript's BigInt for Dart's BigInt.
That would mean having full special-case interceptors like we do for numbers and bools.
What is tricky here is that the primitive JavaScript objects `number`, `string` and `boolean` and now `bigint` and `symbol` are not really classes. This means much deeper integration with how dart2js models these things including generating special cases in `getInterceptor`.

@srujzs - One thing I am not clear on is how `@JS()` interop and the new static interop is supposed to call the right methods (`toString, `hashCode` etc) for intercepted classes like `Uint8Array` which have a first-class `@Native` interpretation, and these primitive objects which are not even JavaScript Objects.

**Comment by nshahan** [comment]
Currently this crashes in DDC as well when it tries to call the Dart `.toString()` member on the symbol. Coincidentally the changes I'm about to land to the calling conventions of the Dart Core Object APIs will fix the crash and instead it will call the native JavaScript `.toString()` member which returns `'Symbol(foo)'`.

**Comment by srujzs** [comment]
> One thing I am not clear on is how `@JS()` interop and the new static interop is supposed to call the right methods (`toString`, `hashCode`, etc) for intercepted classes like `Uint8Array` which have a first-class `@Native` interpretation, and these primitive objects which are not even JavaScript Objects.

We really haven't specified a behavior here beyond what occurs at runtime (we should). In the case of `@staticInterop` where it can be  `typed_data` or `dart:html` objects, we should be getting their corresponding interceptors at runtime and then calling the `Object` methods from there. For the `dart:js_interop` types (of which, there are primitives), I'd expect the same. Are you implying they should be different than that behavior?

We do want to expose `Symbol` and `BigInt` through `dart:js_interop` but we should probably wait until we have interceptors for them.

**Comment by srujzs** [comment]
@nex3 Both DDC and dart2js now intercept `Symbol`s and `BigInt`s as separate interceptors instead of as `LegacyJavaScriptObject`. This means two things:

1. `toString` should now work correctly by calling the external `toString`/`String(#)` method.
2. You can't use `package:js` classes to interop with these types as they're not a subtype of `JavaScriptObject` but rather `Interceptor`. We've introduced types in `dart:js_interop` called `JSSymbol` and `JSBigInt` to use instead. If you opt into the extension types experiment, you can interop using those as your representation type. Another alternative is `js_util` of course.
