### ISSUE TITLE
dart2js crashes when catching a JS string in strict mode

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#53105]
If dart2js-compiled code is run in strict mode (such as when it's loaded as an ECMAScript module as in the browser), and it tries to catch an exception from JavaScript that's just a string, it will crash with `TypeError: Cannot create property '$cachedTrace' on string`. This is because of the helper function `getTraceFromException()`:

```js
getTraceFromException(exception) {
  var trace;
  if (exception instanceof A.ExceptionAndStackTrace)
    return exception.stackTrace;
  if (exception == null)
    return new A._StackTrace(exception);
  trace = exception.$cachedTrace;
  if (trace != null)
    return trace;
  return exception.$cachedTrace = new A._StackTrace(exception);
}
```

Specifically, `exception.$cachedTrace =` is not valid in strict mode if `exception` is a JS value type. Here's a simple reproduction (you can imagine that the exception might come from a JS callback instead of `jsThrow()`):

```js
// test.dart
import 'package:js/js.dart';

@JS("Function")
class JSFunction {
  external JSFunction(String arg1, [String? arg2, String? arg3]);
  external Object? call([Object? arg1, Object? arg2, Object? arg3]);
}

/// Throws [error] like JS would, without any Dart wrappers.
Never jsThrow(Object error) => _jsThrow.call(error) as Never;

final _jsThrow = JSFunction("error", "throw error;");

void main(List<String> args) {
  try {
    jsThrow('oh no');
  } catch (error, stackTrace) {
    print('error: $error, trace: $stackTrace');
  }
}
```

Compile this to JS, load it with `import` in a browser, and you'll see `TypeError: Cannot create property '$cachedTrace' on string 'oh no'`.

**Comment by rakudrama** [comment]
Fixed via https://github.com/dart-lang/sdk/commit/9d15643d7a591aaf852b0858b1642f6b08bdf2be
