### ISSUE TITLE
CFE: textualOutline returns null on pattern stuff

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#53116]
These weak tests fail with semi fuzz enabled:

offsets/step_through_patterns: SemiFuzzFailure
patterns/exhaustiveness/issue2878_example1: SemiFuzzFailure
patterns/exhaustiveness/issue2878_example2: SemiFuzzFailure
patterns/exhaustiveness/issue2878_example3: SemiFuzzFailure
patterns/exhaustiveness/issue2878_example4: SemiFuzzFailure
patterns/issue51489: SemiFuzzFailure
patterns/issue52191: SemiFuzzFailure
patterns/map_lookup: SemiFuzzFailure
patterns/negative_length: SemiFuzzFailure
patterns/pattern_inForInitializer_element: SemiFuzzFailure
patterns/simple_c_style_pattern_for_in_collections: SemiFuzzFailure
patterns/simple_if_case_in_lists: SemiFuzzFailure
patterns/simple_if_case_map_entries: SemiFuzzFailure
patterns/switchExpression_onePattern_noTrailingComma: SemiFuzzFailure
patterns/switchExpression_onePattern_trailingComma: SemiFuzzFailure
patterns/switchExpression_twoPatterns: SemiFuzzFailure
records/block_combine_statements: SemiFuzzFailure
records/for_in_without_variable: SemiFuzzFailure

**Comment by johnniwinther** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/320520
