### ISSUE TITLE
`dart create -t cli` to create an app that uses `package:args`

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#53126]
It would be neat if there was a `dart create -t cli` option that created an app that used `package:args`. Right now making a CLI app requires adding a bunch of boilerplate code to the default `-t console` app template.

**Comment by parlough** [comment]
That is a neat idea!

It would make a new tutorial I have planned for dart.dev easier as well :) 

\cc @mit-mit

**Comment by mit-mit** [comment]
Could we just add it to the `console` template?

**Comment by parlough** [comment]
> Could we just add it to the console template?

That could work, but I think that template serves as the best way for a blank template to test or run some Dart code locally, and that often won't need `package:args`.

> requires adding a bunch of boilerplate code to the default -t console app template.

@Hixie Could you elaborate on what kind of boilerplate code you are thinking of? If there's enough concrete changes that would be useful in the common case, it may better justify the new template.

**Comment by Hixie** [comment]
Honestly I usually just don't bother using `package:args` because the code I'm writing is one-off and it seems not worth the bother of learning how the API works again, but basically I'm imagining a template that imports `args` and has some of the code that's in https://pub.dev/packages/args -- creating an ArgParser, declaring `--verbose`, `--help`, and `--version`, and implementing those three in some basic way. Basically stuff that every CLI app probably wants to do.

**Comment by mit-mit** [comment]
Got it. A new template like that makes sense.

**Comment by bkonyi** [comment]
I've got the following as a possible template:

```dart
import 'package:args/args.dart';

const String version = '0.0.1';

ArgParser buildParser() {
  return ArgParser()
    ..addFlag(
      'help',
      abbr: 'h',
      negatable: false,
      help: 'Print this usage information.',
    )
    ..addFlag(
      'verbose',
      abbr: 'v',
      negatable: false,
      help: 'Show additional command output.',
    )
    ..addFlag(
      'version',
      negatable: false,
      help: 'Print the tool version.',
    );
}

void printUsage(ArgParser argParser) {
  print('Usage: dart __projectName__.dart [arguments]');
  print(argParser.usage);
}

void main(List<String> arguments) {
  final argParser = buildParser();
  try {
    final results = argParser.parse(arguments);
    if (results.wasParsed('help')) {
      printUsage(argParser);
      return;
    }
    if (results.wasParsed('version')) {
      print('__projectName__ version: $version');
      return;
    }
    print(results.arguments);
  } on FormatException catch (e) {
    // Print usage information if an invalid argument was provided.
    print(e.message);
    print('');
    printUsage(argParser);
  }
}
```

Any thoughts?

Also, do we want a `cli-simple` (basic argument parsing using only `package:args/args.dart`, as seen in the template above) and `cli` (argument parsing using `package:args/command_runner.dart`)?

**Comment by Hixie** [comment]
I like it!

I would just stick with the above; as much as we do seem to use subcommands a lot in our own CLI tooling, the vast majority of CLI apps don't have subcommands.

I wonder if there's anything else it would make sense to add to a basic CLI app.

**Comment by Piero512** [comment]
I think the last example might be missing a sample work, like adding all the numbers outside of the arguments and some tiny validation, but it's nice! 

I usually use the console template to create some one-off packages that happen to run with dart run. Last one I wrote was basically one big main. Don't know if anyone else does that,though.

**Comment by bkonyi** [comment]
Thanks for the feedback! I've gone ahead and added some basic functionality so the script does _something_, but didn't want to make things too complex since developers will basically just delete it right away anyway... :)

The CL adding the template is [up for review](https://dart-review.googlesource.com/c/sdk/+/321800).
