### ISSUE TITLE
Ability to create instance of generic type

### ISSUE THREAD

**Issue by Oleh-Sv** [dart-lang/sdk#53130]
I want to have ability to create instance of generic type in similar way as in C# for example.

Sometimes I want to use methods from generic type, but I don't have instance of it.

Main problem for such feature - we don't know which constructor have generic type.

I propose extend syntax for generic types

```
int func<T extends MyNumbersClass has T()>(int a){
   final result = T().getSpecificNumber(a);
   return result;
}
```

in example above we show that we can accept only classes with empty constructor

**Comment by halildurmus** [comment]
Related to https://github.com/dart-lang/sdk/issues/30074 and https://github.com/dart-lang/language/issues/356.

This is one of the features I really want Dart to have. As a workaround, I'm currently passing around the constructor functions as in the example [here](https://stackoverflow.com/questions/23112130/creating-an-instance-of-a-generic-type-in-dart/28556110#28556110).

So, in your example it could be something like this:
```dart
abstract class MyNumbersClass {
  int getSpecificNumber(int a);
}

class MyNumbersClassImpl implements MyNumbersClass {
  @override
  int getSpecificNumber(int a) => a + 2;
}

int func<T extends MyNumbersClass>(T Function() creator, int a) {
  final result = creator().getSpecificNumber(a);
  return result;
}

void main() {
  print(func(MyNumbersClassImpl.new, 2)); // prints 4
}
```

**Comment by matanlurey** [comment]
This would be bringing back quasi-reflection, and would adversely affect tree-shaking.

If you wanted to do this (mind you, in non-Flutter Dart VM only):

```dart
import 'dart:mirrors';

int func<T extends MyNumbersClass>(int a){
   final result = (reflectClass(T).newInstance().reflectee as T).getSpecificNumber(a);
   return result;
}
```

The recommendation will be to pass around the constructor instead, because now constructors across the rest of the program can be tree-shaken.
