### ISSUE TITLE
[cfe] Missing check for superbounded extension types

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#53139]

**Comment by johnniwinther** [comment]
Currently failing:

`co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t02`
`co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A20_t01`

**Comment by rajesh604** [comment]
Hey there I am a newbie to open source I want to contribute to dart can anyone tell me how to get started with it . It would be a great help for me

**Comment by eernstg** [comment]
Hello @rajesh604, perhaps check out [the Dart community page](https://dart.dev/community) and the [dart-misc mailing list](https://groups.google.com/a/dartlang.org/g/misc).
