### ISSUE TITLE
GC crashes of `vm/dart/gc` tests on arm64-linux

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#53138]
The tests
```
vm/dart/gc/fragmentation_typed_data_test/0 Crash (expected Pass)
vm/dart/gc/fragmentation_typed_data_test/1 Crash (expected Pass)
vm/dart/gc/fragmentation_typed_data_test/4 Crash (expected Pass)
vm/dart/gc/fragmentation_typed_data_test/5 Crash (expected Pass)
vm/dart/trigger_gc_in_native_test/1 Crash (expected Pass)
```
are failing on configurations
```
vm-linux-release-arm64
```

It's a little unclear why it's crashing. I don't have arm64 HW atm to try to reproduce.

It may also that this has been happening for a while, but was re-surfaced after test renames in ac77af1c077a9e37e489efd54c8e398b9297bd96

**Comment by rmacnak-google** [comment]
These all ended with -9 / SIGKILL. I suspect from the OOM killer: I notice the bot is timing out purple which might be from low memory / paging.
