### ISSUE TITLE
"Corrupt heap?" on long-running dart tests, rare issue

### ISSUE THREAD

**Issue by mkorbel1** [dart-lang/sdk#53153]
We're hitting a recurring stability/spurious failure issue on some long-running dart tests.  I've included two such cases below.  I had to redact some stuff but I hope it's not relevant to the debug.

We don't know how to reliably reproduce the issue.  The tests that fail run for between 1-2 minutes and fail maybe about 1% of the time, roughly, with issues like this.

We're running in a Docker container running Ubuntu 20.04 which has this version of Dart installed:
Dart SDK version: 3.0.5 (stable) (None) on "linux_x64"

We're using Bazel to orchestrate build and test for the project.

Sorry, we're not sure what other details might be helpful here to debug.  Please let us know if there's something else we could provide.

Here's one of them:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from **REDACTED**
-----------------------------------------------------------------------------
../../runtime/vm/raw_object.cc: 356: error: Invalid cid: 0, obj: 0x7f9c7b25fd98, tags: 0. Corrupt heap?
version=2.19.0-444.2.beta (beta) (Thu Dec 15 17:12:16 2022 +0000) on "linux_x64"
pid=2144, thread=2150, isolate_group=main(0x55ce8da4a000), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=55ce8c4c6140, vm_instructions=55ce8c4c6140
  pc 0x000055ce8c72e49c fp 0x00007f9c897fc740 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x000055ce8c4c6334 fp 0x00007f9c897fc820 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x000055ce8c73f20b fp 0x00007f9c897fc850 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/66/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x223c20b
  pc 0x000055ce8c7e1e1b fp 0x00007f9c897fc880 dart::Page::VisitObjectPointers(dart::ObjectPointerVisitor*) const+0x5b
  pc 0x000055ce8c7dd3e0 fp 0x00007f9c897fc910 dart::GCMarker::IterateRoots(dart::ObjectPointerVisitor*)+0xe0
  pc 0x000055ce8c7ddf6c fp 0x00007f9c897fc9d0 dart::GCMarker::StartConcurrentMark(dart::PageSpace*)+0x27c
  pc 0x000055ce8c7e5b90 fp 0x00007f9c897fcb20 dart::PageSpace::CollectGarbageHelper(dart::Thread*, bool, bool)+0x2d0
  pc 0x000055ce8c7e587a fp 0x00007f9c897fcb90 dart::PageSpace::CollectGarbage(dart::Thread*, bool, bool)+0x12a
  pc 0x000055ce8c7daf4b fp 0x00007f9c897fcc50 dart::Heap::StartConcurrentMarking(dart::Thread*, dart::GCReason)+0x9b
  pc 0x000055ce8c7da462 fp 0x00007f9c897fccb0 dart::Heap::CheckConcurrentMarking(dart::Thread*, dart::GCReason, long)+0xc2
  pc 0x000055ce8c7ead9a fp 0x00007f9c897fcd00 dart::Scavenger::TryAllocateNewTLAB(dart::Thread*, long, bool)+0xca
  pc 0x000055ce8c7d97fd fp 0x00007f9c897fcd30 dart::Heap::AllocateNew(dart::Thread*, long)+0xad
  pc 0x000055ce8c6b0f88 fp 0x00007f9c897fcdb0 dart::Object::Allocate(long, long, dart::Heap::Space, bool)+0x78
  pc 0x000055ce8c6f2ca4 fp 0x00007f9c897fce10 dart::String::FromUTF8(unsigned char const*, long, dart::Heap::Space)+0x104
  pc 0x000055ce8cb93190 fp 0x00007f9c897fce50 dart::kernel::TranslationHelper::DartString(dart::kernel::StringIndex, dart::Heap::Space)+0xb0
  pc 0x000055ce8cb9cb77 fp 0x00007f9c897fce80 dart::kernel::KernelReaderHelper::ReadNameAsGetterName()+0x197
  pc 0x000055ce8cb698b7 fp 0x00007f9c897fcf10 dart::kernel::StreamingFlowGraphBuilder::BuildInstanceGet(dart::TokenPosition*)+0xc7
  pc 0x000055ce8cb73137 fp 0x00007f9c897fcf90 dart::kernel::StreamingFlowGraphBuilder::BuildVariableDeclaration(dart::TokenPosition*)+0x1c7
  pc 0x000055ce8cb7003a fp 0x00007f9c897fcff0 dart::kernel::StreamingFlowGraphBuilder::BuildBlock(dart::TokenPosition*)+0x8a
  pc 0x000055ce8cb70599 fp 0x00007f9c897fd060 dart::kernel::StreamingFlowGraphBuilder::BuildLabeledStatement(dart::TokenPosition*)+0x69
  pc 0x000055ce8cb707a5 fp 0x00007f9c897fd0f0 dart::kernel::StreamingFlowGraphBuilder::BuildWhileStatement(dart::TokenPosition*)+0x55
  pc 0x000055ce8cb7003a fp 0x00007f9c897fd150 dart::kernel::StreamingFlowGraphBuilder::BuildBlock(dart::TokenPosition*)+0x8a
  pc 0x000055ce8cb68794 fp 0x00007f9c897fd1e0 dart::kernel::StreamingFlowGraphBuilder::BuildFunctionBody(dart::Function const&, dart::LocalVariable*, bool)+0xf4
  pc 0x000055ce8cb68ecc fp 0x00007f9c897fd370 dart::kernel::StreamingFlowGraphBuilder::BuildGraphOfFunction(bool)+0x27c
  pc 0x000055ce8cb692bb fp 0x00007f9c897fd420 dart::kernel::StreamingFlowGraphBuilder::BuildGraph()+0x12b
  pc 0x000055ce8cb7f255 fp 0x00007f9c897fd6e0 dart::kernel::FlowGraphBuilder::BuildGraph()+0x65
  pc 0x000055ce8c7c9e10 fp 0x00007f9c897fd900 dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool)+0x40
  pc 0x000055ce8c7caf31 fp 0x00007f9c897fe030 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x581
  pc 0x000055ce8c7cba71 fp 0x00007f9c897fe710 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/66/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x22c8a71
  pc 0x000055ce8c7cc0a4 fp 0x00007f9c897fe7b0 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)+0x124
  pc 0x000055ce8c7cc816 fp 0x00007f9c897fed00 dart::BackgroundCompiler::Run()+0xf6
  pc 0x000055ce8c7b8fbb fp 0x00007f9c897fed80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x13b
  pc 0x000055ce8c7b9408 fp 0x00007f9c897fedb0 dart::ThreadPool::Worker::Main(unsigned long)+0x78
  pc 0x000055ce8c72a696 fp 0x00007f9c897fee70 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/66/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x2227696
-- End of DumpStackTrace
=== Crash occurred when compiling dart:async__Future@4048458__propagateToListeners@4048458 in optimizing JIT mode in unknown pass
=== Flow Graph not available
/github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/66/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/**REDACTED**: line 27:  2144 Aborted                 (core dumped) "$dart" --packages="$package_spec" "$script_file" "$@"

```

And another one:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //**REDACTED**
-----------------------------------------------------------------------------
../../runtime/vm/raw_object.cc: 356: error: Invalid cid: 0, obj: 0x7f758a3577f8, tags: 0. Corrupt heap?
version=2.19.0-444.2.beta (beta) (Thu Dec 15 17:12:16 2022 +0000) on "linux_x64"
pid=5227, thread=5233, isolate_group=main(0x558339262000), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=558337707140, vm_instructions=558337707140
  pc 0x000055833796f49c fp 0x00007f75973fd270 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x0000558337707334 fp 0x00007f75973fd350 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x000055833798020b fp 0x00007f75973fd380 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/198/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x223c20b
  pc 0x0000558337a22e1b fp 0x00007f75973fd3b0 dart::Page::VisitObjectPointers(dart::ObjectPointerVisitor*) const+0x5b
  pc 0x0000558337a1e3e0 fp 0x00007f75973fd440 dart::GCMarker::IterateRoots(dart::ObjectPointerVisitor*)+0xe0
  pc 0x0000558337a1ef6c fp 0x00007f75973fd500 dart::GCMarker::StartConcurrentMark(dart::PageSpace*)+0x27c
  pc 0x0000558337a26b90 fp 0x00007f75973fd650 dart::PageSpace::CollectGarbageHelper(dart::Thread*, bool, bool)+0x2d0
  pc 0x0000558337a2687a fp 0x00007f75973fd6c0 dart::PageSpace::CollectGarbage(dart::Thread*, bool, bool)+0x12a
  pc 0x0000558337a1bf4b fp 0x00007f75973fd780 dart::Heap::StartConcurrentMarking(dart::Thread*, dart::GCReason)+0x9b
  pc 0x0000558337a1b462 fp 0x00007f75973fd7e0 dart::Heap::CheckConcurrentMarking(dart::Thread*, dart::GCReason, long)+0xc2
  pc 0x0000558337a1c139 fp 0x00007f75973fd820 dart::Heap::CheckCatchUp(dart::Thread*)+0x69
  pc 0x0000558337a2943d fp 0x00007f75973fd840 dart::ForceGrowthSafepointOperationScope::~ForceGrowthSafepointOperationScope()+0x4d
  pc 0x00005583378a99ed fp 0x00007f75973fd900 dart::IsolateGroup::RunWithStoppedMutatorsCallable(dart::Callable*, dart::Callable*, bool)+0x2bd
  pc 0x0000558337a0c310 fp 0x00007f75973fe030 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x960
  pc 0x0000558337a0ca71 fp 0x00007f75973fe710 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/198/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x22c8a71
  pc 0x0000558337a0d0a4 fp 0x00007f75973fe7b0 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)+0x124
  pc 0x0000558337a0d816 fp 0x00007f75973fed00 dart::BackgroundCompiler::Run()+0xf6
  pc 0x00005583379f9fbb fp 0x00007f75973fed80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x13b
  pc 0x00005583379fa408 fp 0x00007f75973fedb0 dart::ThreadPool::Worker::Main(unsigned long)+0x78
  pc 0x000055833796b696 fp 0x00007f75973fee70 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/198/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x2227696
-- End of DumpStackTrace
=== Crash occurred when compiling package:rohd/src/modules/bus.dart_Swizzle__execute@115002621 in optimizing JIT mode in unknown pass
=== Flow Graph not available
/github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/198/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/**REDACTED**: line 27:  5227 Aborted                 (core dumped) "$dart" --packages="$package_spec" "$script_file" "$@"
```

**Comment by rmacnak-google** [comment]
We would need a reproduction to debug this.

**Comment by mkorbel1** [comment]
We're not sure what aspect of our program may be exciting the issue and it's pretty rare to reproduce it.  Do you have any suspicion or suggestions of what types of workloads might make reproduction easier?

We're observing the issue in relatively long-running [ROHD](https://github.com/intel/rohd) simulations.  The simulator is effectively a loop of events, each of which propagate signal transitions synchronously through a deep call stack, each of which may trigger additions to synchronous broadcast `Stream`s with multiple listeners. We've run somewhat long-running simulations like this in a variety of scenarios and designs and it's unclear if this particular design just hits the issue much more often or has something unique that makes it possible.  Unfortunately, we cannot share the code for this, but we can try to recreate some subset of it if we knew what direction to look for reproduction.

**Comment by a-siva** [comment]
@mkorbel1 your description states that you were using Dart version 3.0.5 (stable) but the stack traces seem to show Version 2.19.0-444.2.beta (beta) being used

```
../../runtime/vm/raw_object.cc: 356: error: Invalid cid: 0, obj: 0x7f758a3577f8, tags: 0. Corrupt heap?
version=2.19.0-444.2.beta (beta) (Thu Dec 15 17:12:16 2022 +0000) on "linux_x64"
pid=5227, thread=5233, isolate_group=main(0x558339262000), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no

```

Is it possible to try your application of the stable Dart 3.0.5 release and see if you still get this crash ?

**Comment by mkorbel1** [comment]
We had a bazel setting that was using a different version of dart than the one installed in the container, thanks for pointing that out.  We're trying it with 3.0.7 stable now and will report back if we get any failures after a handful of runs.

**Comment by mkorbel1** [comment]
We fixed the Dart version issue but are still seeing the issue reproduce with version 3.0.7.  I've included a couple more logs below.  Interestingly (maybe), these two look very similar to each other.

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from **REDACTED**
-----------------------------------------------------------------------------
../../runtime/vm/raw_object.cc: 363: error: Invalid cid: 0, obj: 0x7f5db959c108, tags: 0. Corrupt heap?
version=3.0.7 (stable) (Mon Jul 24 13:17:56 2023 +0000) on "linux_x64"
pid=5431, thread=5440, isolate_group=main(0x555f14ffc000), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=555f1314e3e0, vm_instructions=555f1314e3e0
fp=7f5dc00fea60, sp=7f5dc00fe928, pc=555f1339386c
  pc 0x0000555f1339386c fp 0x00007f5dc00fea60 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x0000555f1314e5d4 fp 0x00007f5dc00feb40 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x0000555f133a19e9 fp 0x00007f5dc00feb70 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/212/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x23659e9
  pc 0x0000555f134334cb fp 0x00007f5dc00feba0 dart::Page::VisitObjectPointers(dart::ObjectPointerVisitor*) const+0x5b
  pc 0x0000555f1342eee0 fp 0x00007f5dc00fec30 dart::GCMarker::IterateRoots(dart::ObjectPointerVisitor*)+0xc0
  pc 0x0000555f13431289 fp 0x00007f5dc00fecd0 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/212/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x23f5289
  pc 0x0000555f134318d0 fp 0x00007f5dc00fed00 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/212/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x23f58d0
  pc 0x0000555f1340c0db fp 0x00007f5dc00fed80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14b
  pc 0x0000555f1340c528 fp 0x00007f5dc00fedb0 dart::ThreadPool::Worker::Main(unsigned long)+0x78
  pc 0x0000555f1338f9d6 fp 0x00007f5dc00fee70 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/212/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x23539d6
-- End of DumpStackTrace
/github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/212/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/**REDACTED**: line 27:  5431 Aborted                 (core dumped) "$dart" --packages="$package_spec" "$script_file" "$@"
```

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from **REDACTED**
-----------------------------------------------------------------------------
../../runtime/vm/raw_object.cc: 363: error: Invalid cid: 0, obj: 0x7fc5deb56388, tags: 0. Corrupt heap?
version=3.0.7 (stable) (Mon Jul 24 13:17:56 2023 +0000) on "linux_x64"
pid=4109, thread=4114, isolate_group=main(0x55612d03e000), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=55612b7733e0, vm_instructions=55612b7733e0
fp=7fc5f1e7ea60, sp=7fc5f1e7e928, pc=55612b9b886c
  pc 0x000055612b9b886c fp 0x00007fc5f1e7ea60 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x000055612b7735d4 fp 0x00007fc5f1e7eb40 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x000055612b9c69e9 fp 0x00007fc5f1e7eb70 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/156/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x23659e9
  pc 0x000055612ba584cb fp 0x00007fc5f1e7eba0 dart::Page::VisitObjectPointers(dart::ObjectPointerVisitor*) const+0x5b
  pc 0x000055612ba53ee0 fp 0x00007fc5f1e7ec30 dart::GCMarker::IterateRoots(dart::ObjectPointerVisitor*)+0xc0
  pc 0x000055612ba56289 fp 0x00007fc5f1e7ecd0 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/156/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x23f5289
  pc 0x000055612ba568d0 fp 0x00007fc5f1e7ed00 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/156/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x23f58d0
  pc 0x000055612ba310db fp 0x00007fc5f1e7ed80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14b
  pc 0x000055612ba31528 fp 0x00007fc5f1e7edb0 dart::ThreadPool::Worker::Main(unsigned long)+0x78
  pc 0x000055612b9b49d6 fp 0x00007fc5f1e7ee70 /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/156/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/../dart_linux_x86_64/dart-sdk/bin/dart+0x23539d6
-- End of DumpStackTrace
/github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/processwrapper-sandbox/156/execroot/__main__/bazel-out/**REDACTED**.runfiles/__main__/**REDACTED**: line 27:  4109 Aborted                 (core dumped) "$dart" --packages="$package_spec" "$script_file" "$@"
```

**Comment by a-siva** [comment]
@mkorbel1 this is going to be hard to debug without a reproduction. Is it possible to monitor your process to see if the memory footprint is increasing and somehow we are running out of memory but in some path we are missing a check leading to a corruption.

**Comment by mraleph** [comment]
@mkorbel1 

Is it possible to take a test which you know fails and then launch it continuously under `rr record dart ...` or maybe even `rr record -h dart` (chaos mode) until you hit a reproduction? You might just leave this to run over night until it crashes.

If you get a `rr` recording we could collaborate with you to do a bit of reverse debugging over chat to try to narrow this down. 

Alternatively we could think about possible instrumentations we could add to the VM to try narrowing it down and produce a custom Dart SDK build with these.

**Comment by mkorbel1** [comment]
> Is it possible to monitor your process to see if the memory footprint is increasing and somehow we are running out of memory but in some path we are missing a check leading to a corruption.

> Is it possible to take a test which you know fails and then launch it continuously under rr record dart ... or maybe even rr record -h dart (chaos mode) until you hit a reproduction? You might just leave this to run over night until it crashes.

I'm trying to run it in loops and on the same machine to confirm that I can reproduce it without it being launched from our CI.  I'm monitoring the memory usage and even with 50% more tests running on the machine than we normally allow it's not even using more than half the available memory (24GB).  I'll try to use the `rr record` once I confirm this is able to reproduce it (eventually).  It's unfortunately pretty rare and inconsistent.

**Comment by mkorbel1** [comment]
I'm having trouble getting `rr record` to run so far, perhaps because it's a virtualized machine on a cloud system (guess from googling)?  I haven't used the tool before, I'll keep trying a bit longer though.  Is there another way to collect data on a failing test that may be helpful?

**Comment by mraleph** [comment]
> I'm having trouble getting `rr record` to run so far, perhaps because it's a virtualized machine on a cloud system (guess from googling)?

`rr` user performance counters under the hood, so it does not work on the virtualized hardware unless it has special support for exposing performance counters. 

You could try to do the following: 

1. Enable core dumps (`ulimit -c unlimited`) and set core pattern to something more complicated than `core` to prevent cores stamping on each other (e.g. `echo core.%t.%p | sudo tee /proc/sys/kernel/core_pattern`). 
2. Run your test with `--verify_store_buffer --verify_after_gc` passed to the Dart VM. This will make things _very_ slow, but should help catch invariant violations closed to the place where they occure.

Sometimes when reproducing non-deterministic issues it helps to add additional load to the machine to randomise scheduling decisions. I often do this:

```bash
N=100 # select large enough to stress machine, but not too large to make it fall apart 
for i in $(seq 0 N)
do
  dart ... &
done   
```

**Comment by mkorbel1** [comment]
I've been able to reproduce the issue with a core dump (without those flags).  I'm now trying more runs with the flags again to see if it can be reproduced with them.

What are the next steps to debug with the dump in hand?

**Comment by mraleph** [comment]
@mkorbel1 sorry for the late reply, I have been travelling. I am thinking that maybe we could write a Python script which you can run in the GDB which will try to traverse the heap and maybe we figure out what possibly went wrong. 

Can you tell the exact Dart SDK version (output of `dart --version`) for which you got the crash? I can then try to write something. 

@rmacnak-google do you have some ideas of what we could do if we just have a crash dump? I thinking I could at the very least traverse the heap graph and try to find out what kind of corruption it is. Maybe we figure something out from that.

**Comment by mkorbel1** [comment]
No problem, thanks for getting back to this!

The version we were running was configured in Bazel as follows:
```
dart_repositories(
    sdk_channel = "stable",
    sdk_version = "3.0.7",
    linux_x64_sha = "cccd5300faa5a9abce12a5f77586e26350028cea82bb4ff8eeb55641b58a2e1d",
)
```

**Comment by a-siva** [comment]
@mkorbel1 does your app use bigints ? 
A fix was made recently for an out-of-bounds access issue in the bigint code which could potentially corrupt the heap https://dart-review.googlesource.com/c/sdk/+/325122

**Comment by mkorbel1** [comment]
> @mkorbel1 does your app use bigints ?

Yes, @a-siva, we're using `BigInt`'s and [ROHD](https://github.com/intel/rohd) (package we're using for simulation) uses `BigInt`s as well.

Is there a way to easily test that this was the issue?  Is there a version of Dart we can try to see if we no longer reproduce the issue?  We can switch to it and run all our normal CI and also stress it a bit and see if anything shows up still.  That would be great if that's the issue!

**Comment by a-siva** [comment]
> Is there a way to easily test that this was the issue? Is there a version of Dart we can try to see if we no longer reproduce the issue? We can switch to it and run all our normal CI and also stress it a bit and see if anything shows up still. That would be great if that's the issue!

We have bleeding edge builds available at
`https://storage.googleapis.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-linux-x64-release.zip`
This is an unsigned build from the main branch of the Dart SDK repository. Main channel builds are suitable only for experimental development use, not for production use.

**Comment by mraleph** [comment]
Alternatively (to remove other variables from the equation) I have made a built of 3.0.7 `dart` binary with the `BigInt` fix. You can download this [archive](https://drive.google.com/file/d/19f-C-Mnz9QB6FKYNJS4-nXaAMPulQTrK/view?usp=sharing) and then use `out/ReleaseX64/exe.stripped/dart` to replace your `dart-sdk/bin/dart`. (Though you probably would need to do some Bazel tweaks - given that you have it handling Dart toolchain).

**Comment by mkorbel1** [comment]
Is the fix likely to land in the next "dev" channel release?  Seems like those come out more often than weekly? Or I see one was released today, is it in there?

You're right that we'd need to do some custom modifications to the dart bazel tooling in a fork, which I'm not sure what it will entail to get it working right.  If a signed release that's compatible with the bazel tooling will be available within a handful of days it might be easier to wait.

**Comment by a-siva** [comment]
> Is the fix likely to land in the next "dev" channel release? Seems like those come out more often than weekly? Or I see one was released today, is it in there?

No the one released today does not have the change, will update you when a dev release with the change is available.

**Comment by mraleph** [comment]
Here is something we could try with one of these cores @mkorbel1. Download this [archive](https://drive.google.com/file/d/1PHbb51saXV8JnW-hU-qQM0SXSE5N9KAu/view?usp=sharing). It has a Python file and a `dart` executable. The `dart` executable is there just to provide symbols (it matches 3.0.7 build, but is unstripped). 

Execute the following command line from the directory where you unzipped the archive:

```console
$ gdb -q -ex 'source analysis.py' -ex 'quit' dart $path_to_your_core_file
```

Hopefully you should get output like this:

```
Trying to get current OSThread
Current thread 0x560e6b9c6000
Heap 0x560e6b99e580
Isolate Group 0x560e6b968000
0x560e6b9d4000
0x560e6b9da000
  Isolate(560e6b969800, main)
Checking new space pages
  Iterating Page(7f567f880000-7f567f900000, new)
    objects range 7f567f880058 - 7f567f8fffe8
Incorrect object at 7f567f8e5968
--- PRECEEDING OBJECT IS AT 7f567f8e5948 ---
dart::kGrowableObjectArrayCid
Traceback (most recent call last):
  File "analysis.py", line 360, in <module>
    DumpHeapStructure(heap)
  File "analysis.py", line 326, in DumpHeapStructure
    IteratePage(page)
  File "analysis.py", line 309, in IteratePage
    raise Exception('Found incorrect object')
Exception: Found incorrect object
```

This should give us a good idea whether the crash you are seeing is `BigInt` related.

**Comment by a-siva** [comment]
> 
> No the one released today does not have the change, will update you when a dev release with the change is available.

The latest dev release that is availble on the web page `3.2.0-150.0.dev`  has the fix.

**Comment by a-siva** [comment]
@mkorbel1 any updates on using the dev release builds to see if the corrupt heap issue was resolved by it

**Comment by mkorbel1** [comment]
> Execute the following command line from the directory where you unzipped the archive:

@mraleph Unfortunately it looks like something's (probably?) wrong when I try to run your script, any suggestion based on the below output?

```
Reading symbols from dart...

warning: Can't open file /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/external/dart_linux_x86_64/dart-sdk/bin/dart during file-backed mapping note processing

warning: Can't open file /memfd:dart-heap (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:dart-code (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:dart-zone (deleted) during file-backed mapping note processing

warning: Can't open file /github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/external/dart_linux_x86_64/dart-sdk/bin/snapshots/kernel-service.dart.snapshot during file-backed mapping note processing

warning: Can't open file /memfd:dart-timeline (deleted) during file-backed mapping note processing

warning: Can't open file /usr/lib/x86_64-linux-gnu/libc-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/x86_64-linux-gnu/libm-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/x86_64-linux-gnu/libpthread-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/x86_64-linux-gnu/libdl-2.31.so during file-backed mapping note processing

warning: Can't open file /usr/lib/x86_64-linux-gnu/ld-2.31.so during file-backed mapping note processing

warning: core file may not match specified executable file.
[New LWP 23]
[New LWP 21]
[New LWP 22]
[New LWP 24]
[New LWP 19]
[New LWP 16]
[New LWP 18]
[New LWP 27]

warning: .dynamic section for "/lib/x86_64-linux-gnu/libdl.so.2" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib/x86_64-linux-gnu/libpthread.so.0" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib/x86_64-linux-gnu/libc.so.6" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/ld-linux-x86-64.so.2" is not at the expected address (wrong library or version mismatch?)

warning: File "/usr/lib/x86_64-linux-gnu/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib/x86_64-linux-gnu/libthread_db.so.1
line to your configuration file "/home/max/.config/gdb/gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/max/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/github/home/.cache/bazel/_bazel_root/a123cf36ebc006f1596267b74dece3a6/sandbox/'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f11914e500b in __vfwscanf_internal (s=<optimized out>, format=<optimized out>, argptr=<optimized out>, mode_flags=<optimized out>)
    at ./stdio-common/vfscanf-internal.c:1476
1476	./stdio-common/vfscanf-internal.c: No such file or directory.
[Current thread is 1 (LWP 23)]
Trying to get current OSThread
Traceback (most recent call last):
  File "analysis.py", line 332, in <module>
    thread =  gdb.parse_and_eval("'dart::OSThread::current_vm_thread_'").cast(type_Thread_ptr)
gdb.error: Cannot find thread-local storage for LWP 23, executable file /home/max/work/dart_sdk_bugs/stack_53153/dart:
Cannot find thread-local variables on this target

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "analysis.py", line 334, in <module>
    raise Exception("Failed to find current thread")
Exception: Failed to find current thread

```

@a-siva I'll run our tests in a loop with that dev version and report back if I see the exception occur again (or if it's clean for a long time).

**Comment by a-siva** [comment]
> @a-siva I'll run our tests in a loop with that dev version and report back if I see the exception occur again (or if it's clean for a long time).

Thanks

**Comment by mkorbel1** [comment]
I ran it a whole bunch and haven't seen that crash again, so that's a good sign (but maybe not conclusive)!  We're seeing a different weird bazel cache hang that appears to have increased in frequency, but that could very well be unrelated.  I'll keep posted if we see the crash again with this dev version.

**Comment by a-siva** [comment]
> I ran it a whole bunch and haven't seen that crash again, so that's a good sign (but maybe not conclusive)! We're seeing a different weird bazel cache hang that appears to have increased in frequency, but that could very well be unrelated. I'll keep posted if we see the crash again with this dev version.

Thanks for verifying this. Would you be able to upgrade to the new version in your set up or do you need a hotfix on the version that you are currently running ?

**Comment by mkorbel1** [comment]
I'm inclined to just switch to this dev version for our mainline and keep an eye out for this showing up again in any of our CI.  A hotfix shouldn't be necessary unless we find something else really broken in this version, but I expect we should be good since I just ran it many times.  Thanks for the help here, hopefully this fix proves to be exactly what we needed!

**Comment by mkorbel1** [comment]
As an update, I believe we've not seen the error on any runs since switching to this dev version.  Do we know which dart release version will have/already has this fix?

**Comment by a-siva** [comment]
Dart 3.2.0-210.4.beta has the fix and this version is slated to become Dart 3.2 stable on Nov 15th.

**Comment by a-siva** [comment]
marking issue as closed based on the verification done above by @mkorbel1
