### ISSUE TITLE
[CP] Fix for Random crashes on Hot Reload (EXC_BAD_ACCESS)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#53160]
### Commit(s) to merge

7d48bd0e2fdc19615248bce572042374d6f2999b e50470568bbb14bdb2247d4a0dd053702f27513a  5cf55de40926dafa41076e9a49e7caa2d8b40696  79f1e70a32c655e3ca7e39d5c6eca3e0f5d70337

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/319280

### Issue Description

Developers are seeing random crashes while hot reloading, the crashes happen on all platforms.
Please see https://github.com/flutter/flutter/issues/129177

### What is the fix

Handling of enums during hot reload was redone.

### Why cherry-pick

Developers are encountering these random crashes during their development cycles causing productivity loss.

### Risk

high

### Issue link(s)

 https://github.com/flutter/flutter/issues/129177

### Extra Info

The cherry pick fuses four related changes from main.

**Comment by a-siva** [comment]
//cc @rmacnak-google

**Comment by a-siva** [comment]
Considering https://github.com/flutter/flutter/issues/129177#issuecomment-1670792357 maybe it is not worth the extra risk of cherry picking this so late in the stable release cycle.

**Comment by a-siva** [comment]
Let us keep this on hold for one more week, I will ping on the issue as to whether folks where able to download Dart 3.2 beta version and are ok using it.

**Comment by itsjustkevin** [comment]
Thanks @a-siva!

**Comment by itsjustkevin** [comment]
@a-siva looks like https://github.com/flutter/flutter/issues/129177 is closed and locked.  Do we want to close this?

**Comment by a-siva** [comment]
We decided to not cherry pick this into the Dart 3.1 stable so closing issue.
