### ISSUE TITLE
Clarify when a non-nullable final field may not have an initializer in kernel

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#53173]
I'm not sure if this is a bug or not, but in the program below, front-end or TFA (not sure which) drops the field initializer of `IndexError.length` even though the kernel `Field` is still in `Class`.

```dart
void main() {
  final error = IndexError(1, new Object(), "a", "b");
  print(error);
}
```

Relevant parts of the class:

```dart
class IndexError extends ArgumentError implements RangeError {
  final Object? indexable;

  final int length;

  IndexError(int invalidValue, dynamic indexable,
      [String? name, String? message, int? length])
      : this.indexable = indexable,
        this.length = length ?? indexable.length,
        super.value(invalidValue, name, message ?? "Index out of range");
}
```

If I print the `Field`s, `Field.initializer`s, and the initializer lists, I get these:

```
Initializers = [
    LocalInitializer(VariableDeclaration(dynamic #0)),
    SuperInitializer(super.value(invalidValue, "a", let final String? #0 = "b" in #0{String}))
]
Fields = [IndexError.length]
Field initializers = [null]
```

Note that the field `IndexError.length` doesn't have an initializer in the `Field` or in the initializer list. So we don't know what the value of it should be when generating allocating the object.

Currently this works only accidentally: the Wasm field type for this field is `I64`, which is implicitly initialized as `0`.

My questions are:

- Is it expected to not have an initializer in the `Field` or in the initializer list of a constructor for a non-nullable final field?
- If yes, how do we know what the default value must be?

If the answer is no then this is a bug, probably in one of CFE or TFA.

Issue originally discovered by @jessicalally.

**Comment by alexmarkov** [comment]
Kernel of `IndexError` constructor after TFA (in AOT):

```
    constructor •([@vm.inferred-type.metadata=dart.core::Object] dynamic indexable) → core::IndexError
      : dynamic #t482 = block {
        _in::unsafeCast<core::int>(let final has-declared-initializer core::int? #t483 = #C2 in [@vm.inferred-type.metadata=! (receiver not int)] indexable{dynamic}.length);
      } =>throw "Attempt to execute code removed by Dart AOT compiler (TFA)", super core::ArgumentError::value(#C28, #C1313, let final core::String? #t484 = #C1314 in #t484{core::String})
      ;
```

The initialization of this field is removed as it is not reachable - `indexable.length` always throws an exception as `indexable` is `new Object()`.

Initialization of a `final` field can be omitted only if that initialization is unreachable. You can use an arbitrary default value to initialize this field (or leave it uninitialized if wasm permits that - constructor will not complete and the field will not be be accessed).

**Comment by osa1** [comment]
> Initialization of a final field can be omitted only if the initialization code is unreachable. You can use an arbitrary default value to initialize such field

This part is a bit tricky with @jessicalally's work (https://dart-review.googlesource.com/c/sdk/+/315820) which makes Wasm struct fields non-nullable. In the example above we can still use `0` as the default value, but with non-nullable Wasm field types we won't have a default/dummy value to use when the field type is a non-nullable class.

I also still think that the TFA behavior is not quite right,

> constructor will not complete and the field will not be be accessed

Constructor will not complete, but the initializer will complete, and I need a receiver to pass to the constructor. Without initializers for the final fields I don't know how to allocate the receiver that I'll pass to the constructor.

To elaborate, compilation of a constructor in dart2wasm in the CL linked above works like this:

- Initializer lists and constructor bodies are complied separately to separate functions.
- An initializer list function evaluates values of fields, allocates and returns the object being allocated.
- Constructor takes the allocated object as an argument.

In the example above, constructor throws, but initializer list succeeds. So we need to somehow allocate the object and pass it to the constructor, which will then throw.

(The way this works today is all Wasm fields are nullable and they're implicitly initialized as `null`. In the CL above, we're changing this to make non-nullable Dart fields non-nullable in Wasm.)

**Comment by osa1** [comment]
We discussed this more offline. If a constructor is missing an initializer for a field, it means that allocation is never going to succeed and we can generate `unreachable` (or `throw` etc.) instead of `struct.new`. We'll implement this.
