### ISSUE TITLE
`dart:developer`'s `registerExtension` doesn't use `Zone.current.bindBinaryCallback`

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#53178]
`dart:developer`'s registerExtension should use `Zone.current.bindBinaryCallback` to make sure callbacks are invoked in the right `Zone`.

A symptom of this is https://github.com/flutter/flutter/issues/93676.

**Comment by lrhn** [comment]
Looking at the ["implementation"](https://api.dart.dev/stable/3.0.7/dart-developer/registerExtension.html) code in the dartdoc, it looks like `bindBinaryCallback` is called.

**Comment by mkustermann** [comment]
This was fixed December 2022 in https://github.com/dart-lang/sdk/commit/ca03588d2b2c57b29cb9ee77022ec8b02d4d50ba

**Comment by mkustermann** [comment]
Though there was seemingly not a single test for `dart:developer`'s `registerExtension()` and the bugfix didn't come with a regression test either. 

So I've added one here: https://github.com/dart-lang/sdk/commit/166c5d7b41cfb7aa8da975c4d8a43c6160bfa718

**Comment by Hixie** [comment]
awesome, thanks!
