### ISSUE TITLE
if case with multiple predicates

### ISSUE THREAD

**Issue by xvrh** [dart-lang/sdk#53171]
I like the `if (a.foo case var foo?)` pattern.

Today I noticed that we can only have one predicate in the if expression?

```dart
void main() {
  var a = {};

  if (a['foo'] case var foo? && DateTime.now().day == 1) {
    print(foo);
  }
}
```

This results in a very weird errors messages saying `DateTime.now isn't a type` and `Expected to find ')'`.

<img width="674" alt="Screenshot 2023-08-10 at 12 10 26" src="https://github.com/dart-lang/sdk/assets/5110923/c0587a5f-1685-408a-808b-06a16bf6b966">

I think the error message should be improved and explain the reason why it doesn't work.

Also I understand that we cannot have a second `||` predicate, why doesn't `&&` work?

**Comment by lrhn** [comment]
An `if` can only have one `case`. That `case` can have a `when` clause to do more testing after the pattern has matched.

In your case, you can write it as:
```dart
if (a['foo'] case var foo? when DateTime.now().day == DateTime.monday) { 
   print(foo);
}
```

You can think of the `when` clause of such an `if`-`case` as the *normal* `if` condition, so a "classical" `if`,
```dart
if (condition) ...
```
is really like an `if`-`case`
```dart
if (expr case pattern when condition) ...
```
with an empty pattern-match part.

**Comment by lrhn** [comment]
I guess you are right that the error message could be better. The problem here is that you can have `&&` in side patterns, like `if (a['foo'] case var foo? && String(isEmpty: false)) { ... }`, so it's parsing `DateTime.now().day == 1` as a malformed pattern, not a boolean expression.

**Comment by xvrh** [comment]
Thank you very much for the explanation.
