### ISSUE TITLE
Failures on co19/LibTest/io/WebSocket/closeCode_A01_t02 (flaky to RuntimeError)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#53181]
The tests
```
co19/LibTest/io/WebSocket/closeCode_A01_t02 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-win-release-x64
```

[https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-aot-win-release-x64/1023](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-aot-win-release-x64/1023)

**Comment by a-siva** [comment]
//cc @brianquinlan

**Comment by derekxu16** [comment]
deduping to https://github.com/dart-lang/sdk/issues/52011
