### ISSUE TITLE
[analyzer] Incorrect functionality and documentation of `invalid_dependency` diagnostic

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#53217]
I went through the pub diagnostics recently but got confused by [`invalid_dependency`](https://dart.dev/tools/diagnostic-messages#invalid_dependency).

The current description says:

> The analyzer produces this diagnostic when a package under either dependencies or dev_dependencies **isn’t** a pub, git, or path based dependency.

But it does trigger on git and path dependencies, contradicting the description. Which makes sense to me, since as far as I understand, pub.dev doesn't allow path or git hosted dependencies.

Also it mentions producing the diagnostic on dev_dependencies, but I don't believe it does, and I don't believe it should.

Then it presents the following example using a (non-pub) hosted dependency and indicates it is triggered on this:

> ```yaml
> name: example
> dependencies:
>   transmogrify:
>     hosted:
>       name: transmogrify
>       url: http://your-package-server.com
>     version: ^1.4.0
> ```

However it looks like the diagnostic is not triggered by this. I'm not sure if non-pub.dev hosted sources are allowed, but as far as I can tell, they aren't?

Please let me know if my assumptions are correct, then I'd be happy to update the diagnostic to trigger on the non-pub.dev hosted dependency and update the messaging to match the desired/actual behavior.

<details>
  <summary><strong>Expand for proposed documentation</strong></summary>

````md
#### Description

The analyzer produces this diagnostic when a package under `dependencies`
isn't a `pub.dev` based dependency.

To learn more about the different types of dependency sources,
check out [Package dependencies](https://dart.dev/tools/pub/dependencies).

#### Example

The following code produces this diagnostic because the dependency on the
package `transmogrify` isn't a `pub.dev` based dependency:

```yaml
%uri="pubspec.yaml"
name: example
dependencies:
  transmogrify:
    [!hosted!]: http://your-package-server.com
    version: ^1.4.0
```

#### Common fixes

If you want to publish your package to `pub.dev`, then change the
dependency to one that that is published on `pub.dev`.

If you don't want to publish your package to `pub.dev`, then add a
`publish_to: none` entry to mark your package as not intended to
be published:

```yaml
%uri="pubspec.yaml"
name: example
publish_to: none
dependencies:
  transmogrify:
    hosted: http://your-package-server.com
    version: ^1.4.0
```
````
</details>

**Comment by parlough** [comment]
\cc @jonasfj or @sigurdm Could one of you verify if my understanding of how this diagnostic should work(/should be documented) is correct? I appreciate it!

**Comment by sigurdm** [comment]
Yes, I think you are right, and the text is broken.
