### ISSUE TITLE
Failures on Extension types. Report when await of not Future subtype.

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#53219]
There are new test failures on [Extension types. Report when await of not Future subtype.](https://github.com/dart-lang/sdk/commit/759d5a5a01c3b585c87fafc72d3274793c0bb062).

The tests
```
co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A08_t02 CompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-linux
analyzer-asserts-mac
```

If the test needs to be fixed, please file an issue on the co19 repo.

**Comment by eernstg** [comment]
The test has been fixed in https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/static_analysis_extension_types_A08_t02.dart, fix should be effective after next roll.
