### ISSUE TITLE
[CP] Fix for immediate crash when launching dart on Windows 7

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#53215]
### Commit(s) to merge

https://dart.googlesource.com/sdk/+/987dbe0b728319671d49848180c0a6ef9a5893aa

### Target

both

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/320702
https://dart-review.googlesource.com/c/sdk/+/320703

### Issue Description

Fixes dart crash on Windows 7 where dart executable attempted to load a function which was not introduced until Windows 8.

### What is the fix

Revert to use posix-verson of looking up local host name. This reintroduces https://github.com/dart-lang/sdk/issues/52701 though.

### Why cherry-pick

Fix crash on Window 7, which prevents dart from running on Windows 7.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/130554

**Comment by itsjustkevin** [comment]
Holding https://dart-review.googlesource.com/c/sdk/+/320703 for the release of the next beta.

**Comment by vsmenon** [comment]
lgtm

**Comment by itsjustkevin** [comment]
@aam we can merge https://dart-review.googlesource.com/c/sdk/+/320703 now that the beta branch is live.

**Comment by itsjustkevin** [comment]
In queue for next beta release.
