### ISSUE TITLE
[ANTLR] configurable exports are being rejected.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#53214]
Consider:

```dart
export "dart:core"
  if (vm) "dart:core";

void main() {
  print("foo");
}
```

which, as expected, compiles and exits with no errors.

However, according to the antlr grammar:

https://github.com/dart-lang/sdk/blob/332f874bd015d6c2d2d92207008ca896df5ef8ba/tools/spec_parser/Dart.g#L1387

the `uri` in a libraryExport is not configurable.

It looks like the `uri` is meant to be a `configurableUri`.

[the spec does not have this issue](https://github.com/dart-lang/language/blob/7ff7669e10470a0a0f5a396e1779b7d77d586166/specification/dartLangSpec.tex#L20137), that is, the uri in a `libraryExport` is a `configurableUri`.

**Comment by eernstg** [comment]
Good catch, thank you! Dart.g needs to be fixed, cf. https://dart-review.googlesource.com/c/sdk/+/320560.
