### ISSUE TITLE
Difference between analyzer and CFE wrt. mixin on sealed class

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#53221]
Example:
```dart
sealed class S {}
mixin M on S {}
class C1 extends S with M {}
class C2 extends S with M {}
void main() {
  S s = C2() as S;
  (switch (s) {
    C1 _ => 0,
    C2 _ => 1,
  }); 
}
```
The CFE rejects this program, saying that the switch is not exhaustive, because it doesn't include the subtype `M` of the sealed class `S`.
```
mixseal.dart:7:12: Error: The type 'S' is not exhaustively matched by the switch cases since it doesn't match 'M()'.
 - 'S' is from 'mixseal.dart'.
Try adding a wildcard pattern or cases that match 'M()'.
  (switch (s) {
           ^
```

The analyzer accepts the program, not counting `M` as a subtype that needs to be exhausted.

The class modifier specification is not directly relevant here, the rules for which types counts towards exhaustiveness are in the [exhaustivness specification](https://github.com/dart-lang/language/blob/main/accepted/3.0/patterns/exhaustiveness.md).

According to that, the analyzer is correct. The definition of the "space" for a sealed class starts with:
> * The declaration `D` of `T` is a sealed type:
>
>     * For each declaration `C` in the library of `D` that has `D` in an `implements`, `extends`, or `with` clause:

... add something to the space. 
This doesn't mention the `on` clause, so an `on S` does not introduce a subtype that is part of space that exhausts the sealed type, so mathcing `M` should not be needed to exhaust `S` above.

That could also be *sound*, since an `on S` does introduce a subtype, but it's a subtype which only really works if it is mixed in on another *concrete* type which otherwise implements `S`, which means it should be a subtype of one of the "real" subtypes of the sealed type. 
However, I can't find a rule against *implementing* `M` from above from another library (it's not marked `base`), or from the same library, which means that it's possible to create an instance of a subtype of `S` which is not a subtype of `C1` or `C2`, which means that the exhaustiveness is not sound if it doesn't include `M`.

So, we can go one of two ways:
* Allow `M` to not be counted as a subtype for exhaustiveness, but then not allow implementing it, even inside the same library.
* Count `M` towards exhaustiveness.

The second choice is easier, and safer.

The only argument against doing that is that declaring a mixin that can be applied to some of the subclasses of the sealed class, and which can call some of the methods of the sealed class, can actually be *useful*. 
And you can't do `mixin M implements S { ... }` because then it will *certainly* be counted as a subtype for exhaustion.

On the other hand, maybe you *want* the mixin to be counted towards exhaustiveness. (Doubtful, since there really is not a lot you can do with a mixin with an `on SealedType` other than apply it to other types that are *also* already subtypes of the sealed type, at which point it being counted towards exhaustiveness is is pointless. Or you can implement it, in which case it should count, but why was it a mixin then?)

So, the formal specificaiton of the first approach would be:
* We keep the current exhaustiveness rules about which types count twards exhaustiveness, which exclude mixins with only an `on` reference to the sealed class.
* We add the following restrictions on `mixin ... on SealedClass` and its uses:
    * It's a compile-time error if a `mixin` declaration *M* has a sealed _(necessarily `class`)_ declaration *S* as a declared `on` type, *M* does not have *S* as a declared interface, and *M* is not marked `base`.
    * It's a compile-time error if any declaration has a `mixin` declaration *M* as declared interface, *M* has a sealed declaration *S* as declared `on` type, and *M* does not have *S* as a declared interface. _(Even inside the same library. Really, only inside the same library, otherwise the "implementing a `base` type" error should take precedence.)_

That is, if a mixin introduces a subtype of a sealed type through its `on` type, and it's not counted towards exhaustiveness (so not also implementing the sealed type), then the mixin *must not* be implemented. Not locally, and not remotely.
The `base` documents and enforces this for remote use, and the rule against directly implementing in the same library ensures that any subtype of the mixin must be created by applying the mixin to a superclass which already implements the sealed class.

WDYT
@dart-lang/language-team @johnniwinther

**Comment by eernstg** [comment]
> This doesn't mention the `on` clause,

The `on` clause introduces a subtype relationship, so it should be taken into account.

**Comment by munificent** [comment]
> This doesn't mention the `on` clause, so an `on S` does not introduce a subtype that is part of space that exhausts the sealed type, so matching `M` should not be needed to exhaust `S` above.

Yes, that was a deliberate design choice. Some related discussion [here](https://github.com/dart-lang/language/issues/2832).

> That could also be _sound_, since an `on S` does introduce a subtype, but it's a subtype which only really works if it is mixed in on another _concrete_ type which otherwise implements `S`, which means it should be a subtype of one of the "real" subtypes of the sealed type. 

Yes, that was exactly the intent. Every instance of a mixin will also be an instance of some subtype of the mixin. If it's a mixin whose `on` clause is a sealed type, then any instance of that mixin should be an instance of a subtype of some other known subtype of the sealed type.

> However, I can't find a rule against _implementing_ `M` from above from another library (it's not marked `base`), or from the same library, which means that it's possible to create an instance of a subtype of `S` which is not a subtype of `C1` or `C2`, which means that the exhaustiveness is not sound if it doesn't include `M`.

Oops! I think we overlooked this case. :(

> So, we can go one of two ways:
> 
> * Allow `M` to not be counted as a subtype for exhaustiveness, but then not allow implementing it, even inside the same library.
> * Count `M` towards exhaustiveness.
> 
> The second choice is easier, and safer.

The first choice is tempting because it does allow some more complex class hierarchies without requiring seemingly pointless cases to be exhaustive. But the additional complexity is worrisome. It will be very confusing whenever users run into it, and it's hard for me to imagine that the use cases it allows will be common or very compelling.

Could we maybe say that a mixin with an `on` clause on a `sealed` is counted for exhaustiveness unless the mixin is also marked `base`?

If that doesn't plug the hole, I think we should just take the second choice.

**Comment by munificent** [comment]
I'm going to bump the priority because if we take the second choice, that's a breaking change and we'll want to do it sooner rather than later.

**Comment by srawlins** [comment]
I'm going to remove the CFE and analyzer labels, as this is a language issue. A P1 language issue.

**Comment by eernstg** [comment]
This change has been handled: The breaking change request in https://github.com/dart-lang/sdk/issues/53325 was approved, and implementation issues were created here: https://github.com/dart-lang/sdk/issues/53390 (area-meta), https://github.com/dart-lang/sdk/issues/53391 (analyzer subtask), https://github.com/dart-lang/sdk/issues/53392 (CFE subtask).

**Comment by srawlins** [comment]
Excellent. Closing this issue then.

**Comment by eernstg** [comment]
Excellent indeed! 😄
