### ISSUE TITLE
[analyzer] Analyzer disallows external fields on extension types

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#53226]
Analysis on the following example:

```dart
// SharedOptions=--enable-experiment=inline-class

import 'dart:js_interop';

extension type E._(JSObject _) {
  external String field;
}

void main() {}
```

fails with:

`error • field_test.dart:6:19 • Extension types can't declare instance fields. Try replacing the field with a getter. • extension_type_declares_instance_field`

Dart version:
`Dart SDK version: 3.2.0-edge.820b0f799c8dc33ffde17431074a2abfcc5036cf (be) (Mon Aug 14 13:07:06 2023 -0400) on "macos_x64"`

**Comment by eernstg** [comment]
An external instance variable should be treated as an external getter and an external setter (if not final), so that should be allowed.

**Comment by sgrekhov** [comment]
Seems that this issue was fixed. 
Retested on `Dart SDK version: 3.2.0-edge.09f7f356db63e99a43602e0d2e7061088b31991e (be) (Thu Sep 28 04:02:06 2023 +0000) on "linux_x64"`
Closing this item
@srujzs feel free to reopen it if you believe that these is anything that still should be fixed
