### ISSUE TITLE
Verify docs test is timing out

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#53229]
The `pkg/analyzer/test/verify_docs_test` is timing out, which is causing the bots to fail.

@parlough I'm not sure whether this is related to your recent changes. The bot output makes it appear to be from https://dart-review.googlesource.com/c/sdk/+/320520, but that CL had nothing to do with the analyzer as far as I can see.

**Comment by parlough** [comment]
I'm taking a look now.

**Comment by parlough** [comment]
I'm taking a look and I'm not super familiar, but it doesn't look like any of my recent CLs should have caused this. I didn't touch the docs or analysis itself.

Is that the first time the test has timed out?

**Comment by bwilkerson** [comment]
The bot's been red for a while, but I didn't look to see how long it's been for this reason.

Anyway, if it's not because of your recent changes then we can assign it to someone else. Thanks for looking, though!

**Comment by dcharkes** [comment]
Flipped to red again.

**Comment by dcharkes** [comment]
And again.

**Comment by bwilkerson** [comment]
I did a little investigating, and this is to capture the results.

Running the test locally, it's taking a little over a minute (0:01:06.264271).

The test itself hasn't been changed for 6 months. The files that it's looking at [1] haven't been changed for 2 weeks, and the most recent change is to a file that doesn't contain any code snippets.

None of this explains why it recently started timing out.

[1] The test verifies that code snippets in the `analyzer/doc` directory all compile without diagnostics.

**Comment by srawlins** [comment]
Maybe all of the file reads in CI are slower... 🤷  Can we split the code up so it is multiple `test` cases? Actually, it looks like today it is zero test cases; just one `fail` call that can fail the test. Each `verifyFile` can be a test case?

**Comment by bwilkerson** [comment]
In process. I had the same thought shortly after posting the previous comment.

**Comment by bwilkerson** [comment]
Appears to be fixed after https://dart-review.git.corp.google.com/c/sdk/+/328362.
