### ISSUE TITLE
[release process] Incorporate DevTools changes in SDK changelog

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#53230]
DevTools is _(now)_ included and updated alongside the Dart SDK and the SDK changelog is the main point of reference for tracking changes to Dart by the community. 

It doesn't have to be a complete changelog, but in the tools category, something simple like the following could still be helpful:

```md
### Tools

#### DevTools

Incorporates the [2.24.0](https://docs.flutter.dev/tools/devtools/release-notes/release-notes-2.24.0) 
and [2.25.0](https://docs.flutter.dev/tools/devtools/release-notes/release-notes-2.25.0) releases of DevTools.
```

As a side note, DevTools likely should consider dropping its separate version number. It's a little confusing now that it's not vendored as a pub package, especially for someone looking for DevTools changes for a new Dart/Flutter release.

**Comment by parlough** [comment]
\cc @itsjustkevin @kenzieschmoll Something to consider :)

**Comment by itsjustkevin** [comment]
@parlough I think this is a great idea as long as @kenzieschmoll is okay with it, I am willing to add these.

**Comment by kenzieschmoll** [comment]
SGTM!
