### ISSUE TITLE
Failures on [cfe] Use InferableTypeBuilder for primary constructor parameters

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#53231]
There are new test failures on [[cfe] Use InferableTypeBuilder for primary constructor parameters](https://dart-review.googlesource.com/c/sdk/+/320762).

The tests
```
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_ddc_sound_test RuntimeError (expected Pass)
```
are failing on configurations
```
web-dev-unittest-asserts-linux
```

**Comment by johnniwinther** [comment]
@srujzs The CL fixed the types of the parameters to be correct (and not `dynamic`). This caused the test to fail because it tries to create an extension type with an argument of the wrong type. I'm not sure what the right fix of the test is.

**Comment by johnniwinther** [comment]
This seems to happen also for
```
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_amd_sound_test
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_amd_unsound_test
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_ddc_unsound_test
```

**Comment by Markzipan** [comment]
@annagrin has recently been working with these tests - maybe she can add some details here?

**Comment by srujzs** [comment]
Have a CL here: https://dart-review.googlesource.com/c/sdk/+/321202

**Comment by annagrin** [comment]
Thanks @srujzs!
