### ISSUE TITLE
Remove `--target-os` from `dart compile exe` (or making it a NOP)

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#53247]
Right now the `dart compile exe` command cannot cross compile, so we always know the target operating system. There's therefore no point in providing a `--target-os` option, the tool knows internally what OS to use.

@sstrickl could you either remove this option or make it a NOP and make the tool auto-detect the OS?

**Comment by mit-mit** [comment]
I suggest we for `dart compile exe`:

1. default `--target-os` to the current OS
2. print an error if `--target-os` is passed stating that we currently do not support cross compilation for executables

**Comment by sstrickl** [comment]
For 2, I'd only print an appropriate error if the argument to `--target-os` differs from the current OS, just so that we don't break any current workflows that, for some reason, passes it explicitly since we exposed it, which is how I plan to implement it ATM.

**Comment by mit-mit** [comment]
SGTM
