### ISSUE TITLE
thisOrAncestorOfType (bottleneck)

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/sdk#53255]
https://github.com/dart-lang/sdk/blob/7289baece5d304420d7962244aa792112d6f8f6f/pkg/analyzer/lib/src/dart/element/element.dart#L2427

This is the referenced method:
```dart
  @override
  E? thisOrAncestorOfType<E extends Element>() {
    Element? element = this;
    while (element != null && element is! E) {
      if (element is CompilationUnitElement) {
        element = element.enclosingElement;
      } else {
        element = element.enclosingElement;
      }
    }
    return element as E?;
  }

```

Why check for `CompilationUnitElement` if in both cases `element.enclosingElement` is called?

Note that `instanceOf` is a bottleneck in the analyzer CPU, and reduce the unnecessary calls is important.

**Comment by bwilkerson** [comment]
@scheglov In case you have some additional context.

**Comment by gmpassos** [comment]
> @scheglov In case you have some additional context.

?

It's only increasing CPU usage.

**Comment by gmpassos** [comment]
My recommendation for this methods:

```dart
  
  @override
  E? thisOrAncestorOfType<E extends Element>() {
    Element element = this;
    
    while (element is! E) {
      var ancestor = element = element.enclosingElement;
      if (ancestor == null) return null;
      element = ancestor ;
    }
    
    return element;
  }
  
```

**Comment by gmpassos** [comment]
PR:
https://github.com/dart-lang/sdk/pull/53288
