### ISSUE TITLE
Convert JNI to Dart

### ISSUE THREAD

**Issue by UMHoai** [dart-lang/sdk#53265]
extern "C" JNIEXPORT jstring JNICALL
Java_com_example_MainActivity_loadModelJNI(
        JNIEnv* env,
        jobject /* this */,
        jobject assetManager,
        jstring fileName,
        jint is_recorded)
        
How to convert to dart with JNIEnv* env parameter?

**Comment by mit-mit** [comment]
cc @HosseinYousefi

**Comment by HosseinYousefi** [comment]
I don't understand the question @UMHoai. Have you tried using [package:jnigen](https://github.com/dart-lang/jnigen) to call Java code from Dart?
