### ISSUE TITLE
3.1 Docker Image still not up

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#53269]
https://hub.docker.com/_/dart

**Comment by sortie** [comment]
We upstreamed the image 2 days ago in https://github.com/docker-library/official-images/pull/15213 so this may be slowness on the docker side?

@itsjustkevin @athomas

**Comment by sortie** [comment]
Aha. That pull request was closed without landing. We'll make a new one :)

**Comment by whesse** [comment]
PR uploaded to docker-library/official-images#15227

**Comment by mnordine** [comment]
I see there is still nobody assigned to that PR?

**Comment by itsjustkevin** [comment]
> I see there is still nobody assigned to that PR?

No assignee is typically assigned, see https://github.com/docker-library/official-images/pull/15096

**Comment by mnordine** [comment]
Got it, thx!

**Comment by mnordine** [comment]
Up now, thx 👍
