### ISSUE TITLE
Organize imports isn't being run by `dart fix`

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#53261]
Running `dart fix` appears to fail to organize imports, at least under some conditions.

I suspect the problem is in this method: https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/bulk_fix_processor.dart#L754. I believe that we need to special case the lint code for `directives_ordering`. It needs to be run at the end, just like the other directives related fixes, so it isn't marked as being bulk fixable, but I think it shouldn't be filtered out here.

**Comment by bwilkerson** [comment]
@kenzieschmoll @DanTup

**Comment by DanTup** [comment]
Yep, you're right - it's possible I broke this when I added the optimisation linked above 😔

I've got a fix w/ test at https://dart-review.googlesource.com/c/sdk/+/321881, and running "dart fix" from source with Kenzie's example seems to work with this change.
