### ISSUE TITLE
Timezone reported as UTC even though it is GMT+02:00

### ISSUE THREAD

**Issue by andynewman10** [dart-lang/sdk#53276]
### Steps to reproduce

1. Create a Flutter application on a device running Android 7.1.1. You can use an Android 7.1.1 emulator or, eg., a Sony Xperia Z5 Compact device running Android 7.1.1 (both experience the same issue)
2. Go to the Settings, Date/Time and make sure automatic time is on ; manually set the time zone to something other than GMT (for instance: I use Paris, France, which is GMT+2 in Summer)
3. Add the following code:
```
DateTime dateTime = DateTime.now();
```
4. Run the code and inspect the value of `dateTime`, either by printing it or using the debugger (I use VS code).

### Expected results

In Paris, France, `dateTime.toString()` should be equal to
```
DateTime (2023-08-17 21:23:23.241901)
```
and the time zone should be:
```
timeZoneName: "CEST"
timeZoneOffset: Duration (2:00:...)
```
In other words, the time should be `21:23` in the `CEST` timezone.

### Actual results

`dateTime.toString()` is
```
DateTime (2023-08-17 19:23:23.241901)
```
and the timezone reported is:
```
timeZoneName: "GMT"
timeZoneOffset: Duration (0:00:...)
```
In other words, the time is correct (in its reported timezone: it really is `19:23` in `UTC/GMT` timezone), but the timezone is not correct.

The same program runs fine (no timezone error) on

- an iPhone 8 with iOS 16.6
- a Samsung S5 Mini (SM-G800F) with Android 6.0.1

### Comparison with a native Android implementation

I tested with native (Java) code on a native Android application on my Sony Z5 Compact. I use Android Studio Electric Eel.

1. Create a native Android application in Android Studio, use the "Basic Activity" template
2. Add the following code:

```
                SimpleDateFormat timezoneOffsetFormatter = new SimpleDateFormat("ZZZZZ");
                String timezoneNotation = timezoneOffsetFormatter.format(new Date()); // "+02:00"
                String timezoneLocation = TimeZone.getDefault().getID(); // "Europe/Paris"
                String tzString = timezoneNotation + "," + timezoneLocation;
```
3. Run the application on the same device (Android 7.1.1 emulator or Sony Xperia Z5 Compact with Android 7.1.1).

Look at the `tzString` value. This value is `+02:00,Europe/Paris`.

### Code sample

<details><summary>Code sample</summary>

```dart
DateTime dateTime = DateTime.now();
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [version 10.0.22000.2295], locale fr-FR)
    • Flutter version 3.10.6 on channel stable at C:\Users\fred\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\fred\AppData\Local\Android\sdk
    • Platform android-33, build-tools 34.0.0
    • Java binary at: C:\Users\fred\Documents\Applications\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\fred\Documents\Applications\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Users\fred\Documents\Applications\IntelliJ
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\fred\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22000.2295]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.203

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by brianquinlan** [comment]
I don't think that there is anything special about CEST - I can reproduce this on a device set to PST on Android 7.1.1 (Nougat) but not on Android 8.0 (Oreo) or later.

Dart is getting the time zone string from [`localtime_r`](https://github.com/dart-lang/sdk/blob/98fd1b737234aa5225d3569ed81ca1999fde1f94/runtime/vm/os_android.cc#L104). I suspect that `localtime_r` was broken on Android in Nougat.

**Comment by brianquinlan** [comment]
I think that I found the fix in Android: https://android-review.git.corp.google.com/c/platform/bionic/+/321708/2/libc/tzcode/localtime.c#1568

**Comment by brianquinlan** [comment]
I think that the workaround would be calling `tzset` before we call `localtime_r`.

**Comment by a-siva** [comment]
Reverted the above change as it causes TSAN failures, calling tzset before calling localtime_r doesn't seem viable.

**Comment by a-siva** [comment]
The CL was reverted so reopening this issue.

**Comment by a-siva** [comment]
Seems like an eager call to tzset during initialization causes performance regressions and a delayed call just before the call to localtime_r is racy. What are the other options here? Do we need to do the delayed call with some kind of locking ?

**Comment by brianquinlan** [comment]
I need to try it but we could limit the performance issues by only running the setup where necessary:

```dart
if (android_get_device_api_level()) < 26) { // Oreo
```

It would also possible to do this on first use of `localtime_r` but that would trade startup time for runtime performance.

**Comment by brianquinlan** [comment]
At least at head, `android_get_device_api_level` seems like it should be pretty fast - it is calling `atoi` and looking up a system property in an in-memory `std::map`

**Comment by a-siva** [comment]
@brianquinlan did the use of `android_get_device_api_level` pan out? Can we use the solution you propose ?

**Comment by brianquinlan** [comment]
I'm trying to test it now.

**Comment by brianquinlan** [comment]
Changing the code like:

```dart
void OS::Init() {
  if (android_get_device_api_level() < 26) {
    tzset();
  }
}
```

produces correct output and no performance difference for Android > 7.1.1.

I'm running the benchmarks on 7.1.1 right now.

**Comment by brianquinlan** [comment]
It turns out getting the benchmarks to run on API 25 was harder than I thought - they completed and it looks like `tzset` doesn't cause a significant reduction in startup latency.

A/B testing this on a Pixel XL running API version 25 produces these results:
![image](https://github.com/user-attachments/assets/896ddce6-7611-4dec-90d2-318efad374f3)

So, an ~2ms increase in mean startup latency. That seems acceptable to me.
