### ISSUE TITLE
LSP: Incorrect Content-Length for dart/textDocument/publishFlutterOutline response

### ISSUE THREAD

**Issue by 5hirish** [dart-lang/sdk#53289]
I've encountered a potential issue with the `dart/textDocument/publishFlutterOutline` method where the `Content-Length` specified in the header doesn't match the actual content length. This mismatch is causing my LSP stream parser to crash at the JSON decoder due to an extra 2 characters.

**Steps to reproduce**:
1. Receive data from the `dart/textDocument/publishFlutterOutline` method.
2. Parse the `Content-Length` from the header.
3. Check the length of the content based on the header.
4. Compare the parsed `Content-Length` with the actual length of the content.

**Observed behavior**:
For the attached IO dump, the specified `Content-Length` in the header was `8928`. However, upon examining the content, its length was found to be `8926`, leading to a difference of 2 characters.
[lsp_bug_quinine.log](https://github.com/dart-lang/sdk/files/12394132/lsp_bug_quinine.log)

**Expected behavior**:
The `Content-Length` specified in the header should match the actual content length.

I've attached a snippet of the string buffer during the time of the issue for further insight.

You can observe that the header's `Content-Length` and the actual length of the content differ by 2 characters.

I believe there might be a discrepancy in how the `Content-Length` is being computed or set for this specific method. It would be great if you could take a look.

Thanks for your assistance!

> Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_arm64"
---

Here is my LSP client parser: 

[5hirish/quinine/lib/services/lsp/buffer.dart#L59-L70](https://github.com/5hirish/quinine/blob/6b192147d3eccda139f30ecfaa8399a46eab71b1/lib/services/lsp/buffer.dart#L59-L70)

**Comment by 5hirish** [comment]
I will try to reproduce this in a smaller project.

**Comment by 5hirish** [comment]
My guess is the file URI format is causing this issue.
My LSP client creates URI like this -
`file:///Volumes/Macintosh%20HD/Users/felix/StudioProjects/tonic-ide/lib/main.dart`
Where as VSCode -
`file::///Users/felix/StudioProjects/tonic-ide/lib/main.dart`

in the key `uri` could it be the white space being encoded messes up the content length?

**Comment by DanTup** [comment]
I think I can reproduce this - taking a look. I don't think it's the %20 as if the length was treated that as decoded, the content-length would be 2 characters less, but it seems like it's 2 characters more.

It's possible there's a trailing \r\n included in the payload that I'm not logging (in which case it might add up), but I don't think that would explain your issue.

**Comment by DanTup** [comment]
Ok, I found the difference here is in the number of bytes vs the number of characters. If I log `message.length` and `message.codeUnits.length` I see:

```
Length:: 8916
Code Units:: 8914
```

The LSP spec describes content-length as:

> The length of the content part in bytes. This header is required.

So my feeling is that the server is doing the right thing. Looking at your code, I think you are using content-length to read numbers of characters (by using substring):

```
var rawMessage = bufferString.substring(messageStart, messageLength);
```

Whereas in the servers code, we keep the buffer as raw bytes until we have the correct length and then decode using utf8:

https://github.com/dart-lang/sdk/blob/4d4a922638cda394c59605936a56874f75819b9e/pkg/analysis_server/lib/src/lsp/lsp_packet_transformer.dart#L51-L58

So I think if you change your code to keep the buffer of bytes and take a slice of that once you have the length, that will solve the issue (it might also prevent some other issues [like this](https://github.com/Dart-Code/Dart-Code/issues/2140) which I had in VS Code when multi-byte characters were split by the buffering in stdout 🙃).

**Comment by 5hirish** [comment]
Oh let me try switching to a bytes buffer and see what's up. Thanks for explaining this.

**Comment by pq** [comment]
It looks like this is WAI. Feel free to re-open if you feel otherwise?  Thanks for the thoughtful replies @DanTup!

**Comment by 5hirish** [comment]
@DanTup just switched to bytes buffer, works like a charm. Thanks a bunch!

**Comment by DanTup** [comment]
Excellent, thanks for confirming!
