### ISSUE TITLE
`Isolate.packageConfigSync` and `Isolate.resolvePackageUriSync` APIs are missing in Dart v3.1

### ISSUE THREAD

**Issue by halildurmus** [dart-lang/sdk#53285]
These APIs are documented in the CHANGELOG under the v3.1.0:
https://github.com/dart-lang/sdk/blob/cfa03ed97198307f265dfd8071190164eeb4bc81/CHANGELOG.md?plain=1#L119-L121

However, they seem to be missing in Dart v3.1.

Here's the link to the `Isolate` class from the stable branch: https://github.com/dart-lang/sdk/blob/stable/sdk/lib/isolate/isolate.dart

In the main branch, these APIs are defined as:
https://github.com/dart-lang/sdk/blob/cfa03ed97198307f265dfd8071190164eeb4bc81/sdk/lib/isolate/isolate.dart#L345-L346
https://github.com/dart-lang/sdk/blob/cfa03ed97198307f265dfd8071190164eeb4bc81/sdk/lib/isolate/isolate.dart#L396-L397

Here's the commit where these APIs are added: https://github.com/dart-lang/sdk/commit/4fddaf9486c4680ea703eef94792b421db50a1ce

Dart version:
```
Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "windows_x64"
```

**Comment by 24junio200892** [comment]
Liberar
