### ISSUE TITLE
Reading float32 introduces extra precision

### ISSUE THREAD

**Issue by aeb-dev** [dart-lang/sdk#53284]
I am not sure if this is a bug

```dart
var f = 1.23;
var l = Uint8List(4);
l.buffer.asByteData().setFloat32(0, f);
var v = l.buffer.asByteData().getFloat32(0);
print("f: $f, v: $v");
```

`Output: f: 1.23, v: 1.2300000190734863`

I thought this might be a bug because float32 supports 8 digit fraction but the fraction continues after 8th digit (I mean this part: 190734863), but `float32` should not support(?) those values. So, If I read a float32 I should not be getting float64.

* Dart SDK Version: Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "windows_x64"

I opened the same issue on https://github.com/dart-lang/typed_data/issues/71 but I realized it is related to core library so creating also here

**Comment by lrhn** [comment]
That is the intended, and indeed required, behavior.

There is no double with the numerical value 1.23. The closest double has the precise value
1.229999999999999982236431605997495353221893310546875
(Exactly 0x13ae147ae147ae / 2^52, a number with 53 bits of precision)
The `double.toString` conveniently displays that number as `1.23`, the *shortest* numeral which is closer to the exact value than to any other double value.

When you then convert that to a Float32, which only has 24 bits of precision, it's rounded to
0x13ae1480000000 / 2^52, aka 1.230000019073486328125

Then you read that Float32 value back out and convert it back to a double, which doesn't require any rounding at all,
so it's still 0x13ae1480000000 / 2^52.

That's a different number from the one you started with, so it has a different `toString` result.
The toString has as many digits as are needed to ensure that its values is closer to this number, than to, e.g.,
0x13ae1480000001 / 2^52 or 0x13ae147fffffff / 2^52.

All is working precisely according to specification for floating point numbers.
