### ISSUE TITLE
Regression: pattern_never_matches_value_type triggered on enums that implement sealed class

### ISSUE THREAD

**Issue by mernen** [dart-lang/sdk#53287]
Example:

```dart
sealed class Sum {}

enum A implements Sum { x }

void example(Sum value) {
  if (value case A _) {
    //           ^ The matched value type 'Sum' can never match the required type 'A'.
  }
}
```

This worked fine in Flutter 3.10 (Dart 3.0), now causes the warning in the comment. Execution seems fine, at first glance.

Tested on:

* Dart SDK 3.1.0 (Flutter 3.13.0)
* DartPad master channel: Dart SDK 3.2.0-77.0.dev

**Comment by lrhn** [comment]
Analyzer is a little too early with that warning, given that
```dart
(switch(value){ A _ => 0});
```
gives it too, but is also considered exhaustive.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/323232
