### ISSUE TITLE
Fuchsia arm64 FFI stubs are copy-pasta (and wrong)

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#53296]
https://github.com/dart-lang/sdk/blob/f61107b4f6fb49e3ca329449b27002123dd7c017/runtime/vm/compiler/stub_code_compiler_arm64.cc#L620

That line presumably wants to be DLRT_ExitTemporaryIsolate.

FYI @dcharkes

**Comment by eseidel** [comment]
Maybe the real solution is just #52579

**Comment by dcharkes** [comment]
You're probably right, it looks like a copy-paste from the lines above. 🤓

**Comment by liamappelbe** [comment]
Oops. Yeah, we only have 2 bots testing Fuchsia, an arm64 and an x64, and I think the arm64 bot only builds the SDK.
