### ISSUE TITLE
[Release process] Verify changelog entries when making stable release

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#53298]
The changelog is the primary view into Dart SDK changes by developers. However, in the Dart 3.1 release, the changelog included entries that didn't make the cut-off and are instead part of 3.2. This has caused confusion for developers (https://github.com/dart-lang/sdk/issues/53285), tech writers (https://github.com/dart-lang/site-www/pull/5115), and potentially content creators who share about Dart/Flutter releases.

There were at least two changes that were included in the [3.1.0 changelog](https://github.com/dart-lang/sdk/blob/3.1.0/CHANGELOG.md#310---2023-08-16) but not part of the release. The following two CLs move them to the 3.2.0 header.

- [`utf8.encode` return type change](https://dart-review.googlesource.com/c/sdk/+/321260)
- [`packageConfigSync` and `resolvePackageUriSync`](https://dart-review.googlesource.com/c/sdk/+/322040)

I'm not exactly sure how it happened as usually the changelog entries would be moved with the source changes themselves. It could happen with a manual changelog update to add missing items, accidentally when merging changes to the beta branch, or if a change was (partially) reverted.

To avoid potential confusion in the future, as part of making the final beta cut-off and/or moving the changes to stable, the changelog should be verified as having up-to-date entries.

\cc @itsjustkevin @mit-mit (@MaryaBelanger)

**Comment by parlough** [comment]
Thanks for taking a look!

> I think one quick change here that could benefit the team is adding the tech writing team to the reviews.

Good idea! That does seem like it would benefit the team overall, for this and potentially other concerns. However I'll defer to @MaryaBelanger and @atsansone on their desire to be included in that review process.

While I do think that could help in general, it might not help much with verifying accuracy of the changelog, as they don't interact directly with the SDK much.

**Comment by itsjustkevin** [comment]
Another interesting idea here:  What if we parsed the links in the stable changelog and verify that they landed on the branch that they are under for stable?  

Commit abc123's latest tag is 3.1.0 meaning that it shouldn't be under the 3.2.0 section.  Riffing here, but trying to speak out the idea.

**Comment by parlough** [comment]
I like the idea or some variation of it! I'm all for more view into how changes are made, since I think Dart developers are curious, and that would help enable more insight.

The challenge there would be adding the commit references themselves, knowing when to do so, and who would do that.

---

I guess before any more expensive solution is made, is to determine why this happened this time. Normally the changelog entry wouldn't move to the stable channel without the change itself, and the [last published beta](https://github.com/dart-lang/sdk/blob/3.1.0-262.3.beta/CHANGELOG.md) didn't have the accidental entries. So they must have been accidentally added when releasing stable by copying the changelog for 3.1.0 from the `main` branch changelog.

So perhaps the source of the problem is those entries being added under 3.1.0 in `main` even though it was after the cut off but the CL authors not realizing. Perhaps the solution is to just make sure the next release is added to the changelog at the same time the cut off is made. Or maybe a check to make sure developers add their change to the correct version entry in the original CL. 

Misunderstood versions can have other effects too, much more important than the changelog, such as in https://dart-review.googlesource.com/c/sdk/+/322040 which marks the added APIs available in Dart 3.1 with `Since` annotations, potentially resulting in a lack of a diagnostic reporting the API as unavailable for package authors developing with a beta SDK (3.2) release, but wanting to support stable (3.1) releases.

**Comment by Cat-sushi** [comment]
Release date on the CHANGELOG.md should also be maintained.
https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#310

**Comment by annagrin** [comment]
Suggestion by  @nshahan - mark all the dev versions in the release window (for example, 3.1.0-348.0-dev, which is past 3.1.x but but before the change to 3.2.0-dev to `3.1.0-348.0-dev`and make pub aware of it (ie issue warning when we try to publish something including this constraint). 

Another options is to make pub aware of out-of-order SDK versions and correct for it during constraint soling somehow (i.e. treat 3.1.0-348.0-dev as > 3.1.x. but < 3.2.0.-0

**Comment by parlough** [comment]
I think the core issue here was due to the final beta cutoff being made but the `main` branch not updating to the next update in lock-step with that.

The final cut off for 3.3 was today and an updated release process resulted in the `main` branch being updated accordingly to 3.4 (https://github.com/dart-lang/sdk/commit/8158275a941910f61f27b1830e62a0346cb71afe), including the changelog entry.

I think this process will sufficiently prevent confusion about what version a change is landing in. I'll monitor the next few releases to verify no issues pop up. Thanks everyone for your help and the discussion!

**Comment by sigmundch** [comment]
Thanks @parlough for following up and keeping and eye on this!

Indeed, as a result of this issue we debated a few options for how to tweak the release process to prevent this from happening again. We debated many ideas, but figured out a way to bump `main` to the next minor version quickly right after branching so we don't risk creating these periods where semantic versioning is broken.
