### ISSUE TITLE
Issues with implied types in generic type parameters

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#53302]
Copied from Flutter plugin for IJ issue here: https://github.com/flutter/flutter-intellij/issues/6867.

----

I noticed that sometimes the completion for the generic type of the type of a property/method is not working. Unfortunately I couldn't find the exact conditions that lead to this issue, but I found that using the annotation immutable on the class will help to reproduce the issue.

----

Here is a working example where I'm trying to autocomplete `bool`:

```
class Foo {
  final List<bo>
}
```

----

When my cursor is here after `<bo` and before `>`, I press ctrl + space to autocomplete it works as expected, it will complete to become bool.

Now the same example when I apply the annotation immutable from flutter/widget.dart.
It will *NOT* work.

```
import 'package:flutter/widgets.dart';

@immutable
class Foo {
  final List<bo>
}
```

When my cursor is here after `<bo` and before `>`, I press ctrl + space to autocomplete, nothing happens.

----

Now the previous example but modified with the name of the properties (I added foo after List<bo>). It doesn't matter if there is a final semicolon or not ;.
It will work.

```
import 'package:flutter/widgets.dart';

@immutable
class Foo {
  final List<bo> foo
}
```

When my cursor is here after `<bo` and before `>`, I press ctrl + space to autocomplete it works as expected

**Comment by scheglov** [comment]
It looks that this also got fixed with 081cff0cc49f6158a6e725492c4b340443d51a08.
