### ISSUE TITLE
Not possible to use Records with jsonEncode

### ISSUE THREAD

**Issue by maks** [dart-lang/sdk#53304]
It would be nice to be able to use Records with named fields with jsonEncode:
```
import 'dart:convert';

void main() {
  final ({String name, int id}) data = (name: "test", id: 42);
  final encoded = jsonEncode(data);
  print("json data:$encoded");
}
```
But the above gives an error:
```
Uncaught Error: Converting object to an encodable object failed: Record (id: 42, name: "test")
```

or am I missing something obvious here?

**Comment by ykmnkmi** [comment]
I want it too, from `(1, name: 'value')` to `'{"1": 1, "name": "value"}'`.

Also, the ability to convert records to JS objects with the new `dart:js_interop` library.

**Comment by mit-mit** [comment]
@lrhn

**Comment by lrhn** [comment]
You can provide your own `toEncodable` function to the conversion, which is called on all objects that the JSON encoder cannot handle directly.

You can write a function which converts the record shapes that you care about to the map format that you want them to have.

There is no automatic conversion from record types, and won't be any, not any more than there is for any arbitrary class type. Record types really are just like predefined class types for each shape, and unrelated to each other.

**Comment by maks** [comment]
Thanks for the explanation @lrhn 👍🏻 , that does make sense, I think I need to adjust my mental model of Records a bit as being more like "light weight classes" vs like Maps. And yes I'll have a go at using `toEncodeable` for my specific usecase.
