### ISSUE TITLE
FfiCallbackTrampolineStub allows CSP and SP to overlap, potentially crashing on signals

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#53303]
https://github.com/dart-lang/sdk/blob/92ca7985a50f8f0c7dbce7be026e9e663af570a3/runtime/vm/compiler/stub_code_compiler_arm64.cc#L513
FfiCallbackTrampolineStub allows CSP and SP to overlap, potentially crashing on signals.  More over it not only sets them to be the same, but allows SP to grow above CSP.

This was caught by trying to run the FFI trampoline in the simulator.  In Debug mode, the simulator spams 4 words below the CSP on every SP set (to simulate potential signal handling, I think?)
https://github.com/dart-lang/sdk/blob/92ca7985a50f8f0c7dbce7be026e9e663af570a3/runtime/vm/simulator_arm64.cc#L970

So one of these are wrong.  I think it's the FFI trampoline code which is unsafe?  @dcharkes @rmacnak-google  @kmillikin

We found this as part of trying to update our fork of Dart (for Shorebird) which has made FFI work from the simulator.

We can get past this by disabling the Simulator's debug writes below the CSP for now.

[edit, sorry Zach, I just associate you in my brain with the simulator.  Actually blaming the debug lines, they were added by @rmacnak-google]

**Comment by rmacnak-google** [comment]
Right, the stub code is signal-unsafe.

Beyond the [missing entry frame issue](https://github.com/dart-lang/sdk/issues/52814), this is another way FFI is profiler-unsafe.

**Comment by mraleph** [comment]
I think we should just bump CSP enough ahead to prevent this issue. 

[I am hoping to get rid of CSP vs SP by the end of the year. Plus minus.]

**Comment by kmillikin** [comment]
Thanks.  Out of curiosity, is alignment the only reason that `csp` and `sp` are different on arm64?

**Comment by kmillikin** [comment]
> the simulator spams 4 words below the CSP on every SP set (to simulate potential signal handling, I think?)

I think we would have found this more quickly if it used a marker value instead of the instruction number.  `0xbad5144` (badSIM).
