### ISSUE TITLE
Convert `interface` to `abstract` fix doesn't work

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#53305]
Consider this code:

```dart
interface class JsonDeserializer<T> {
  T fromJson(Map<String, Object?> json);
}
```

It generates this error:

>'fromJson' must have a method body because 'JsonDeserializer' isn't abstract.

And this fix:

<img width="415" alt="Screenshot 2023-08-22 at 11 08 16 am" src="https://github.com/dart-lang/linter/assets/8120472/1c3f9289-3dc9-4375-b949-c8670620bbbf">

Which creates this code:

```dart

interface abstract class JsonDeserializer<T> {
  T fromJson(Map<String, Object?> json);
}
```

Which doesn't compile.

The fix should put the `abstract` keyword at the beggining.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/04aa5727bef315d9f34c95b7f334c5b961b726b5 which is in 3.2.0 stable.
