### ISSUE TITLE
[CFE] Least upper bound calculation should take `Object?` into account

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53319]
Accordint to the https://github.com/dart-lang/language/pull/3276 upper bound calculation algorithm should take Object? into account

**Comment by chloestefantsova** [comment]
I believe this issue is resolved by https://github.com/dart-lang/sdk/commit/c658b463f41c7aa7a8c02a0ce0a14271178115ac and https://github.com/dart-lang/sdk/commit/871d0b1b71394070c1edeaf9716ab136bee813ca. Please reopen the issue if needed.
