### ISSUE TITLE
pkg/linter unit test files in test_data directory have analysis failures

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#53317]
The pkg/linter/test unit tests are failing analysis checks on the CI.

The tests

- pkg/linter/test/experiments_test
- pkg/linter/test/integration_test
- pkg/linter/test/rule_test
- pkg/linter/test/unmocked_sdk_rule_test

fail when the analyzer tries to analyze the dart files in linter/test_data.

Part of the migration plan for linter is to migrate the tests to drop these test_data files.

See https://github.com/dart-lang/linter/issues/4411

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/sdk/commit/76e4e80ceb16f6ff1879a13203167f0d1b8a993d
