### ISSUE TITLE
Unexpected behaviour while using TCPsocket to get a streamed file [Syncing files to device Windows...]

### ISSUE THREAD

**Issue by Satyam1Vishwakarma** [dart-lang/sdk#53313]
### Code sample
```import 'dart:io';
import 'dart:convert';
import 'dart:async';

main() async {
Socket socket = await Socket.connect('127.0.0.1', 8081);
print('connected');

// listen to the received data event stream
socket.listen((List event) {
print(utf8.decode(event));
});

// send hello
socket.add(utf8.encode('hello'));

// wait 5 seconds
await Future.delayed(Duration(seconds: 5));

// .. and close the socket
socket.close();
}
```
### Expected results

Should print binary of the file send through the server

### Actual results

Syncing files to device Windows...

### This tracker is for issues related to:
*Dart core libraries (`dart:async`, `dart:io`, etc.)

**Comment by julemand101** [comment]
Try call `socket.flush()` after adding the data.

**Comment by mraleph** [comment]
Sorry this does not have enough information to really help you. What is the server you are connecting to? Where exactly do you get `Syncing files to device Windows...`: is it the Dart program you are running? is it the server that prints it?

**Comment by Satyam1Vishwakarma** [comment]
> Sorry this does not have enough information to really help you. What is the server you are connecting to? Where exactly do you get `Syncing files to device Windows...`: is it the Dart program you are running? is it the server that prints it?

The server is located at 127.0.0.1 written in rust which is a tcp server.
The client is in dart.
The server starting streaming audio file as user connects

**Comment by mraleph** [comment]
Is it the Dart program that prints "Syncing files to device Windows"? Why do you think that this is not what the rust server sent?

**Comment by Satyam1Vishwakarma** [comment]
> Is it the Dart program that prints "Syncing files to device Windows"? Why do you think that this is not what the rust server sent?
"Syncing files to device Windows" is by dart program as I am not sending any text just binary.

**Comment by mraleph** [comment]
Are you using Flutter? I don't think Dart will ever print this line. Flutter on the other hand would print it when you start an app. 

When happens when you just try to run your Dart program via `dart path-to-you-file.dart` rather than `flutter run ...`?

**Comment by Satyam1Vishwakarma** [comment]
Yeh I was using flutter

**Comment by Satyam1Vishwakarma** [comment]
Yeh I was using flutter

**Comment by mraleph** [comment]
And what happens if you just use Dart? What does it print?

**Comment by Satyam1Vishwakarma** [comment]
> And what happens if you just use Dart? What does it print?

Nothing,

**Comment by mraleph** [comment]
> Nothing,

Not even "connected"?

> Am not sending any kind of even pure bytes of file
> But it's not being displayed

Sorry, if you are *not* sending any bytes why do you expect something to be displayed?

Anyway, I think this is more of a question for community support channels, see dart.dev/community. 

If you discover an actual bug, feel free to file one or comment here. But we will need an end-to-end runnable reproduction. 

I also would recommend reading [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), right now it is excruciatingly difficult to get information out of you.
