### ISSUE TITLE
[breaking change] Make `on` edges from mixins count with respect to exhaustiveness

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#53325]
## Intended change in behavior

During static analysis of exhaustiveness, `on` edges in the superinterface graph from mixin declarations to sealed types must be included. *For instance, the mixin `M` in the example below must be included in order to exhaust `S`.*

The behavior of the analyzer must change, but the common front end remains unchanged (the CFE already does this).

## Justification for making the change

Here is an example showing the soundness issue with the current behavior of the analyzer, where such `on` edges are ignored during exhaustiveness analysis:

```dart
sealed class S {}
mixin M on S {}
class C extends S {}
class F implements M {}

void main() {
  S s = F();
  var v = switch (s) { C() => 1 };
}
```

According to the analyzer exhaustiveness analysis, the switch is exhaustive. However, the value of the scrutinee `s` is actually an instance of `F`, which does not match any case. The proposed change is needed in order to maintain soundness.

The existing rules aim to prevent this soundness issue in various ways, but it turns out that there is a loophole, and the change proposed here is simpler and safer.

## Expected impact

This change is likely to impact a very small amount of code, because the CFE already reports the errors that will be reported by the analyzer after the change.

## Steps for mitigating the change

Some switch expressions which were previously accepted with no errors (by the analyzer, so presumably they have never been processed by the CFE) may now be flagged as non-exhaustive. The typical mitigation will be to add the missing cases.

## Specification updates

The specification documents will be accordingly. It is currently being clarified which documents to adjust and how.

**Comment by eernstg** [comment]
@itsjustkevin, I believe you can take the next step to proceed with this breaking change process?

**Comment by itsjustkevin** [comment]
@vsmenon @Hixie @grouma could you take a look?

**Comment by Hixie** [comment]
sounds good to me. I'd also be fine with just not allowing `implements` of a `sealed` class at all (even within the same library, I mean).

**Comment by grouma** [comment]
SGTM. Unlikely to impact ACX.

**Comment by vsmenon** [comment]
LGTM as is

That said: to Ian's question, are we getting value out of allowing mixins and/or implements on sealed hierarchies?  Would it make sense to only allow extends?

**Comment by leafpetersen** [comment]
> That said: to Ian's question, are we getting value out of allowing mixins and/or implements on sealed hierarchies?

We discussed this at some length (an option on the table was to simply disallow this).  There are use cases, and we've had people organically encounter this and file issues.  This change brings our implementations into alignment (and makes the specification sound, whereas currently the CFE implementation is sound but the analyzer and specification behaviors are unsound).  We can consider a follow on breaking change to disallow this entirely, or to allow mixins to be declared as sealed.  The latter would enable a design pattern (which we have, I believe, had users bring up organically) in which a library exposes a sealed hierarchy along with functionality that can mixed in without disturbing the exhaustiveness behavior of the sealed hierarchy.  On balance, the team felt that the right path was to bring the implementations into alignment, and to consider adding support for sealed mixins in the future.

**Comment by vsmenon** [comment]
Thanks @leafpetersen - still lgtm.

**Comment by eernstg** [comment]
The language team decided that the breaking change proceeds. I just created an implementation issue here: https://github.com/dart-lang/sdk/issues/53390.

**Comment by eernstg** [comment]
Closing: The implementation of this change is handled in https://github.com/dart-lang/sdk/issues/53390.
