### ISSUE TITLE
Why is the quick fix for `directives_ordering` not applied when running `dart fix --apply`.

### ISSUE THREAD

**Issue by jtdLab** [dart-lang/sdk#53336]
When running `dart fix --apply` in a project with [`directives_ordering`](https://dart.dev/tools/linter-rules/directives_ordering) lint enabled directives do not get sorted.
Why is this the case? Afaik `dart fix --apply` should apply quick fixes if they are unambiguous. And sorting directives (organize imports) should fall into that category?!

**Comment by bwilkerson** [comment]
That was a bug. I believe that it was fixed by https://dart-review.googlesource.com/c/sdk/+/321881, and should be available in the next release.
