### ISSUE TITLE
[analyzer] Wrong error is reported if an extension type declares an external variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53335]
Analyzer reports an error if an extension type declares an external variable
```dart
extension type ET1(int id) {
  external int m; // COMPILE_TIME_ERROR.EXTENSION_TYPE_DECLARES_INSTANCE_FIELD. Extension types can't declare instance fields.
}
```
According to the [spec](https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md#syntax) external instance variables are allowed

> A compile-time error occurs if the extension type declaration declares any instance variables, unless they are external.
> 
> _An external instance variable is just a convenient notation for an external getter and (if not final) an external setter. They are allowed._

Tested on the edge (Aug 24, 2023) SDK on Linux x64

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/322982
