### ISSUE TITLE
Add support for `--enable-asserts` in AOT runtimes

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#53343]
Currently we don't support assertions in AOT mode, but we'd only need to do some plumbing to add support.

If we decide to add support for assertions, we'll need to update the `dart compile` `aot-snapshot` and `exe` subcommands to support this option. We'll also need to update our test infrastructure to have an AOT configuration that enables assertions for testing.

cc @alexmarkov

**Comment by bkonyi** [comment]
@mit-mit is this something that should be prioritized? Given that lack of support for assertions in AOT hasn't come up until this point I'm guessing there's not a high demand for this.

**Comment by mit-mit** [comment]
I think we can wait and see what the demand is.

**Comment by jensjoha** [comment]
I for one would really like this option.
E.g. on the `front-end-nnbd-linux-release-x64` bot we run the compiler with assertions enabled, but we would likely still benefit from AOT compilation (decreased test times thus decreased waiting for try bots etc).

**Comment by a-siva** [comment]
bumping priority based on the flutter issue

**Comment by aam** [comment]
@bkonyi with 03a2f7da124079fe4e5f106889bfa160d2614957 landed you can pass `--enable-asserts` to gen_snapshot and other tools that are used to build AOT artifacts. Dart VM has https://dart-current-results.web.app/#/filter=language/assert/assert_test&showAll that runs on all platforms to confirm that asserts are indeed working there.
There is remaining work to address https://github.com/dart-lang/sdk/issues/34110 - to ensure that message source line is preserved in the raised exception.

**Comment by aam** [comment]
> As for https://github.com/dart-lang/sdk/issues/34110, it's currently marked as closed. Should it be reopened?

Yeah, I think so.

**Comment by a-siva** [comment]
> > As for #34110, it's currently marked as closed. Should it be reopened?
> 
> Yeah, I think so.

Can't we use this issue for tracking it and not have multiple issues.

**Comment by aam** [comment]
> Can't we use this issue for tracking it and not have multiple issues.

I think this can be closed once --enable-asserts can be used in aot and asserts do work in all aot builds. The other issue will track the work of making the **message** produced by assert in aot similar to jit.
