### ISSUE TITLE
`kIsWeb` (and others) trigger `non_bool_condition` in default parameter value

### ISSUE THREAD

**Issue by Bungeefan** [dart-lang/sdk#53363]
I have a project that was completely valid in **Dart 3.0.0** (up to 3.0.7) but produces analyzer issues with **3.1.0**.
_In Flutter words, this means 3.10.X works fine, 3.13 produces issues._

In short, the analyzer now starts complaining about the usage of a `const bool` (e.g. `kIsWeb`) in a `const` list in a default value of a constructor parameter. Yet, the project is still working and compiles/builds fine, even with Flutter 3.13.0.

The analyzer produces this "error":
```
Analyzing debug_overlay.dart...                                         

  error • Conditions must have a static type of 'bool' • lib/src/debug_overlay.dart:118:11 • non_bool_condition

1 issue found. (ran in 0.8s)
```

Using `bool.fromEnvironment('dart.library.js_util')` directly produces the same "error".

The code in question is available under https://github.com/Bungeefan/flutter_debug_overlay/blob/7169bded3afec112d83af2ea638d5078b29c3a22/lib/src/debug_overlay.dart#L105-L110

This happened without making any changes to the code. For example, [pub.dev](https://pub.dev/packages/flutter_debug_overlay/score) also started showing the same problem when using dart 3.1.0 for analysis.

<details>
<summary>Dart Info</summary>

#### General info

- Dart 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "linux_x64"
- on linux / Linux 6.4.9-1-MANJARO # 1 SMP PREEMPT_DYNAMIC Wed Aug  9 08:32:12 UTC 2023
- locale is de_AT.UTF-8

#### Project info

- sdk constraint: '>=2.17.0 <4.0.0'
- dependencies: collection, device_info_plus, dio, flutter, flutter_json, http, http_parser, multi_long_press_gesture_recognizer, package_info_plus, sliver_tools
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory |   CPU | Elapsed time | Command line                                                                               |
| -----: | ----: | -----------: | ------------------------------------------------------------------------------------------ |
| 465 MB | 87.7% |        00:06 | dart language-server --client-id=Android-Studio --client-version=AI-223.8836.35 --protocol=analyzer |
|  75 MB |  6.6% |        00:06 | flutter_tools.snapshot daemon 
</details>

**Comment by lrhn** [comment]
Does look like a weirdness in the analyzer.
```dart
const kYes = true;
const bool kMaybe = bool.hasEnvironment("dart.library.js_util");
const bool kIsWeb = bool.fromEnvironment('dart.library.js_util');
const bool kIsWebString = String.fromEnvironment('dart.library.js_util') == "true";
void main() {
  const c = [if (kYes) 42, if (kMaybe) 42, if (kIsWeb) 42, if (kIsWebString) 42,];
  print(c);
}
```
In this code, only the `kIsWeb` is reported as an error, with the error message:
```
line 6 • Conditions must have a static type of 'bool'. 
```
The type of `kIsWeb` *is* bool.
Changing the *string argument* to `bool.fromEnvironment` to something not representing a Dart platform library, like adding `x` to the string, makes the error go away.
Changing it to another library which does exists, like `'dart.library.html'`, or which doesn't exist (in DartPad), like `'dart.library.io'`, makes the error go away.

It seems to be very specific to precisely `const bool.fromEnvironment('dart.library.js_util')`.

**Comment by kallentu** [comment]
This is the same issue as https://github.com/dart-lang/sdk/issues/51607, except because of recent changes I've made, it now produces a different error. It used to be something like `A value of type 'Null' can't be assigned to a parameter of type 'List<int>' in a const constructor. Try using a subtype, or removing the keyword 'const'. •
          const_constructor_param_type_mismatch`, which is just as nonsensical as the one seen here.

I'll try relooking into it.

**Comment by kallentu** [comment]
Pushed a fix for this involving unknown bool constants in lists [40aacb3](https://github.com/dart-lang/sdk/commit/40aacb348252f47fb479d539110ffe59e8d4670c).
Closing.
