### ISSUE TITLE
Bad state: Future already completed in _secureHandshakeCompleteHandler

### ISSUE THREAD

**Issue by sudha-anecure** [dart-lang/sdk#53369]
We see this exception in our error logs from our app on production about once a day. 

Bad state: Future already completed
Stack trace:
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35)
#1      _RawSecureSocket._secureHandshakeCompleteHandler.<anonymous closure> (dart:io/secure_socket.dart:947)
#2      _rootRun (dart:async/zone.dart:1383)
#3      _CustomZone.run (dart:async/zone.dart:1293)
#4      _CustomZone.runGuarded (dart:async/zone.dart:1201)
#5      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241)
#6      _rootRun (dart:async/zone.dart:1391)
#7      _CustomZone.run (dart:async/zone.dart:1293)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1225)
#9      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:420)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

Flutter version: 3.10.3 

Unfortunately, we only have stack trace and no repro steps.

**Comment by srawlins** [comment]
Issue with `dart:io`?

**Comment by a-siva** [comment]
@brianquinlan The `_reportError` method in secure_socket.dart doesn't appear to reset `_connectPending` to false, wondering if this could be the issue here. If we encounter an error, report the error and then secureHandshakeCompleteHandler runs we could get into this 'Bad state: Future already completed' state,

**Comment by a-siva** [comment]
@sudha-anecure do you have any repro instructions so we can reproduce and test the fix out.

**Comment by sudha-anecure** [comment]
As I mentioned above, when I reported the case, we see this exception in our error logs from our app on production about once a day. They are from customer devices. We have no repro steps. But this is an error in the core libraries and should be addressed.
