### ISSUE TITLE
[Feature request] allow for record destructuring in methods params

### ISSUE THREAD

**Issue by eximius313** [dart-lang/sdk#53361]
Having such code:
```dart
Future<({String s, int i})> doSomething() async => (s: '', i: 1);
```
it is possible to do this:
```dart
var (:s, :i) = await doSomething();
print("$s $i");
```
or this:
```dart
doSomething()
  .then((value) => print("${value.s} ${value.i}"));
```

But it's not possible to do this:
```dart
doSomething()
  .then(var (:s, :i) => print("$s $i"));

```
nor this:
```dart
void fun(var ({String s, int i})){
  print("$s $i");
}
```

Could you please allow for destructuring in such cases?

----
In your issue, please include:
* Dart version and tooling diagnostic info (`dart info`) -> `- Dart 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "windows_x64"`
* Whether you are using Windows, macOS, or Linux (if applicable) -> Windows 10
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) -> N/A

**Comment by lrhn** [comment]
This is actually a language request, so it should be in the language repository.
There is already an issue for it there, https://github.com/dart-lang/language/issues/3001, so I'll close this as a duplicate.

**Comment by eximius313** [comment]
Thank you @lrhn
