### ISSUE TITLE
[Feature Request] Conditional dependencies based on compilation strategy

### ISSUE THREAD

**Issue by btrautmann** [dart-lang/sdk#53379]
**dart info**

- Dart 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_arm64"
- on macos / Version 13.5 (Build 22G74)
- locale is en-US

**This content was originally posted [here](https://github.com/flutter/flutter/issues/81650#issuecomment-1698047523), but I'm copying/pasting it here for ease of readability:**

We'd like to be able to exclude/include packages from a Flutter application (though I suppose this could be broadened to include pure dart projects) based on the runtime/compilation strategy (AOT v JIT, `flutter --release` v `flutter run`). The reason for this need is that we'd like to have some functionality in our app that behaves differently under test than it does in production, and _ideally_ that production implementation is a no-op that does not necessitate the dependencies that the test implementation does. Currently, "conditional dependencies" is not a thing in pubspec land, but I could imagine a syntax similar to the one proposed above for platforms:

```dart
flutter:
  package_exclusions:
    charlatan:
      - aot
    test_implementation:
      - aot
    prod_implementation:
      - jit
```

My next best alternative, as far as I'm aware, would be direct manipulation of the `pubspec.yaml` via some pre-build hook, which feels tricky at best and dangerous at worst. One thing worth mentioning is that I come from a native Android background where this was achievable via [dependency configurations](https://developer.android.com/build/dependencies) (e.g `testImplementation` versus just `implementation` IIRC), so my mind is going to a similar solution which may just be flat-out wrong in dart.

**Note:** I likely haven't given enough thought to how the consuming could would look, but I suspect at some point we'd need to make use of conditional imports which I imagine would pose another set of obstacles (though I may be over-complicating this, as I've never gone down this road too far as I've always known it to be a dead-end)

**Comment by srawlins** [comment]
Can you give some concrete examples of code that would be able to be compiled either with or without the presence of a certain dependency? I'm wondering how the prod version would be compilable with references to the package-only-needed-for-tests.

**Comment by btrautmann** [comment]
> Can you give some concrete examples of code that would be able to be compiled either with or without the presence of a certain dependency? I'm wondering how the prod version would be compilable with references to the package-only-needed-for-tests.

Yeah my note at the very end was intended to highlight that I probably haven't put enough thought into this from a dart perspective. I'm going to play with this a bit today and hopefully come back with something tangible!

**Comment by btrautmann** [comment]
@srawlins Ok so this is a brain dumb of sorts, and I'm unsure whether this is a big value-add (maybe I'm over-complicating my problem?), but I've put together a sample repo [here](https://github.com/btrautmann/dart-lang-53379).

In the Flutter project, I define an [interface](https://github.com/btrautmann/dart-lang-53379/blob/main/i_message/lib/src/i_message_base.dart) in a package `i_message` along with a top-level function that produces an instance of that interface. That top-level function is referenced back in the `main.dart` file of the Flutter project [here](https://github.com/btrautmann/dart-lang-53379/blob/main/lib/main.dart#L11-L13). **Note** that to make this work, as you mentioned, a conditional import is necessary. For now, since [custom import conditions are not supported](https://medium.com/@dvargahali/dart-2-conditional-imports-update-16147a776aa8), I've used existing ones for native/web. Maybe what I'm yearning for is conditional imports? With this setup, you can see that depending on _platform_ (though ideally this would be "compilation strategy"), the correct message is used, even though the top-level function referenced in `main.dart` would throw an error if not for the conditional imports.

<img width="2026" alt="Screenshot 2023-08-30 at 10 43 04" src="https://github.com/dart-lang/sdk/assets/8343465/3d559f5d-12b7-4db3-bda2-039badaf7889">

In my `pubspec.yaml`, I've added _everything_ as a runtime dependency, and a (commented out) section that would aim to tree-shake the packages we don't need at runtime depending on compilation. I'm making a huge assumption here that it would be possible to tree-shake/ignore the non-applicable import branches as well, so the app could actually compile. This would, in turn, guarantee, that `test_message` is not reachable/usable at runtime, which is what I'm looking for. Note that this becomes more valuable when you add dependencies _to_ your test implementations that are not added to your runtime implementations, which is not shown in this sample.

In order to demonstrate where my thoughts are coming from, I've added a native Android project under the [`native` directory](https://github.com/btrautmann/dart-lang-53379/tree/main/native). In it, there's a similar structure, but the notable differences are:

1. In the `app/build.gradle.kts`, you can see I can specify dependencies for a given build configuration (`debug` versus `release`). That's shown [here](https://github.com/btrautmann/dart-lang-53379/blob/main/native/app/build.gradle.kts#L51-L53).
2. I can align my directory structure _with_ those build configurations (this holds true for flavors, and build variants, which are a combination of build type and flavor, but that's out of scope here). Therefore, I have a [`debug` `MessageCreatorProducer`](https://github.com/btrautmann/dart-lang-53379/blob/main/native/app/src/debug/java/com/example/compilationex/MessageCreatorProducer.kt) that creates a `DebugMessageCreator` (from the `test_message` module) and a [release one](https://github.com/btrautmann/dart-lang-53379/blob/main/native/app/src/release/java/com/example/compilationex/MessageCreatorProducer.kt) that creates a `ProdMessageCreator` (from the `prod_message` module). When I switch build types (you can do this by opening up Android Studio, hitting CMD+Shift+A, typing `Build Variants` and selecting `debug` or `release` for the `app` module), the build system knows which version of the `MessageCreatorProducer` to use. This, to me, is akin to what I'd like to see happen in a dart build based on "compilation strategy".

**So the TLDR here** is I'm longing for a way to have a build-system guarantee that test dependencies used in a `kDebugMode` (I understand that's a Flutter specific constant) environment are not compiled with the app in a `kReleaseMode` environment. Conditional imports seem to be the only way to hook this up, but I imagine a directory structure similar to what Gradle supports (or maybe it's the AGP, I really don't know) for Android would be a great way to get rid of the need for those.

**Comment by jonasfj** [comment]
I think conditional dependencies is the wrong tool here. As it brings along all sorts of other problems.

Suddenly you have two dependency resolutions: how do you make sure that the version of `retry` used in testing is also the one used in production?
Today, you do this using `pubspec.lock`, with conditional dependencies, you won't -- or we'll need new solutions for that.

Unless there is a dependency conflict, there generally no reason not to include a dependency.
And if conditional dependencies is used to solve dependency conflicts, then I don't think it makes sense to have platforms or compilation targets as conditions. Hence, I'm generally of the opinion that conditional dependencies is undesirable.

It is useful to have dependencies like `dev_dependencies` that are only fetched in certain contexts, but we don't have too many contexts like that, where the contexts don't eventually all merge anyways. But now I'm on a side track, conditional dependencies is not the solution.

Conditional imports is the solution to this kind of problem. If we need to make additional conditions a possibility that might be a reasonable thing to do. I think `-D my_condition` works, but you might only be able to use it inside `String/bool.fromEnvironment('my_condition')`.

However, in release-mode the tree-shaker should be pretty solid, it should definitely keep conditional imports not selected out of your binary, and it should even keep things like:
```dart
if (bool.fromEnvironment('my_condition')) {
  // only included when: 'dart -D my_condition=true' is used to compile.
}
```
out of the final binary.

I'd suggest relying on conditional imports if feasible, and if paranoid about accidentally include test-only code in a production release: maybe there is a way to verify this by grepping the compiled binary for symbols?

**Comment by btrautmann** [comment]
> Conditional imports is the solution to this kind of problem. If we need to make additional conditions a possibility that might be a reasonable thing to do. I think `-D my_condition` works, but you might only be able to use it inside `String/bool.fromEnvironment('my_condition')`.

Oh, interesting. From the article I linked above:

> What you no longer can do is use custom conditions. Most of what I wrote in my previous article no longer applies. -D is no longer taken into consideration. This was confirmed by Dart Team members and support for user defined conditions is unlikely to land in Dart.

I didn't investigate this myself further, but I'll take a deeper look and see if this gets me most of what I want.

I can definitely appreciate that my proposal would make the things you outlined above overly complex and therefore the juice doesn't seem worth the squeeze. With that said, I'm going to keep this issue open temporarily to facilitate discussion on conditional imports (in case `-D` doesn't work, etc.) and close it out with a (hopefully helpful) comment on my findings.

**Comment by btrautmann** [comment]
Hm, I've added a [commit](https://github.com/btrautmann/dart-lang-53379/commit/f0fca770d928106cdc81210610fe652fc21f0381) that adds a pure dart (console) project and uses the same interfaces/implementations as before (all as runtime deps) but `-D` doesn't seem to work. As a side note, Flutter supports `--dart-define` (which I assume is it's corollary) but conditional imports don't work with that either (I tried that after trying `-D`, which didn't allow a successful build).

You can run that project with the bottom config found in `launch.json` which should print `isProd` but it prints `isNotProd`.

**Comment by jonasfj** [comment]
Yes, the article mentioned that `-D` doesn't affect conditional imports.

But dont `-D` allow: `String.fromEnvironment` to create a constant you can use in an `if(..` statement -- which it's then likely the tree shaker would be able to eat.
