### ISSUE TITLE
Memory leak in Process.run

### ISSUE THREAD

**Issue by MegatronKing** [dart-lang/sdk#53370]
We have received some user feedback for the Flutter windows app, the app has serious memory leaks on some devices. Finally, I located the issue in `Process.run`. Logically, the app will frequently execute some commands, such as this
```dart
final ProcessResult result = await Process.run('reg', [
    'query',
    'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings',
]);
```
When the number of executions increases, a large amount of memory will be occupied. In normal, the app will only occupy 200M of memory, but now it will grow to 3700M  and more.

![260617279-fc16af3f-dca6-4946-a85d-b16b293a33fe](https://github.com/dart-lang/sdk/assets/15059084/d918e223-30b6-41d5-b9b0-b6087e939f95)

Of course, it’s not just this command, we’ve tried other commands as well. But strangely, not all windows devices have this issue.

Attach my dart info here
```
Dart 3.0.3 (stable) (Wed May 31 15:35:05 2023 +0000)
```

**Comment by MegatronKing** [comment]
We have not found similar issues on the mac system so far.

**Comment by a-siva** [comment]
//cc @aam can you see if this is reproducible in standalone Dart on Windows

**Comment by aam** [comment]
I can't reproduce memory leak behavior. Something as simple as below works as expected without memory growth.

```dart
import 'dart:io';

main() async {
  for (int i=0; i < 1000; i++) {
    final ProcessResult result = await Process.run('reg', [
      'query',
      'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings',
    ]);
    print(result);
  }
}
```

@MegatronKing please provide more reproducible instructions.

**Comment by MegatronKing** [comment]
@aam In fact, this issue cannot be reproduced on my windows device. But I have received some user feedback, and after their tests, the version that removes `Process.run` has no memory leak issue.

**Comment by a-siva** [comment]
> @aam In fact, this issue cannot be reproduced on my windows device. But I have received some user feedback, and after their tests, the version that removes `Process.run` has no memory leak issue. There is one thing in common, they are all win 10 professional.

@MegatronKing can you get information from your user base on what environment they are using and some instructions on how to reproduce the problem. We will not be able to make any progress on this until we are able to reproduce the problem.
