### ISSUE TITLE
Flakily failing service/kill_running_test/dds

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#53373]
From [this log](https://dart-ci.appspot.com/log/vm-win-release-ia32/vm-win-release-ia32/147/service/kill_running_test/dds)
```
--- Command "vm" (took 51.000316s):
set DART_CONFIGURATION=ReleaseIA32 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseIA32\crashpad_handler.exe & out\ReleaseIA32\dart.exe -DUSE_DDS=true --sound-null-safety -Dtest_runner.configuration=vm-win-release-ia32 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\runtime\observatory\tests\service\kill_running_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: kill_running_test.dart (DDS)[0m

** Launching SERVICE_TEST_TESTEE=true out\ReleaseIA32\dart.exe --disable-dart-dev --write-service-info=file:///C:/b/s/w/itv2jwe5td/dart_service3c2cec38/service_info.json --profiler -DUSE_DDS=true --sound-null-safety -Dtest_runner.configuration=vm-win-release-ia32 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json --enable-vm-service:0 C:\b\s\w\ir\runtime\observatory\tests\service\kill_running_test.dart

>testee>out> The Dart VM service is listening on http://127.0.0.1:50265/RbFHR3TyPCo=/

>testee>out> 

>testee>out> 1

** Signaled to run test queries on http://127.0.0.1:50286/y0fcO9hXxhA=/ (DDS)

Loading VM...

Done loading VM

Running kill_running_test.dart [1/1]

>testee>err> isolate terminated by Kill service request

All service tests completed successfully.

** Killing script

00:21 [32m+0[0m[31m -1[0m: kill_running_test.dart (DDS) [1m[31m[E][0m[0m

  ServerRpcException(Service has disappeared)
  
  This test failed after it had already completed.
  Make sure to use a matching library which informs the test runner
  of pending async work.

  ServerRpcException(Service has disappeared)
  ServerRpcException(Service has disappeared)
  ...
  ServerRpcException(Service has disappeared)
  ServerRpcException(Service has disappeared)
  ServerRpcException(Service has disappeared)
  ServerRpcException(Service has disappeared)

  ServerRpcException(Service has disappeared)

00:21 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n vm-win-release-ia32 service/kill_running_test/dds

```

**Comment by dcharkes** [comment]
This test is meta flaking: https://dart-ci.web.app/#showLatestFailures=false&test=service/kill_running_test/dds

And also flaking: https://dart-current-results.web.app/#/filter=service/kill_running_test/dds&showAll

<img width="336" alt="image" src="https://github.com/dart-lang/sdk/assets/3601775/dffbfdc6-b4aa-40c2-b3a0-5990647eb04e">

@bkonyi can we either fix the test, implementation, or disable the test?

It seems to be only meta flaking on ia32.

**Comment by dcharkes** [comment]
![image](https://github.com/dart-lang/sdk/assets/3601775/ba6d6c5d-030b-4be7-ad1a-fac1f18150f3)
Can we please do something about this @bkonyi.

**Comment by bkonyi** [comment]
CL to remove these tests is up for review: https://dart-review.googlesource.com/c/sdk/+/338981

Sorry for the headache around these service tests. I've been spending most of my time migrating these tests to the pkg/vm_service test suite and have ensured they've been deflaked there.

The plan is to stop running the service tests on all but two configurations, just to keep some test coverage for the Observatory VM service APIs. We're going to instead start running the pkg/vm_service test suite on a subset of the VM configurations (see this [WIP CL](https://dart-review.googlesource.com/c/sdk/+/337300)), so deflaking this test suite is lower priority.

**Comment by dcharkes** [comment]
Thanks @bkonyi !
