### ISSUE TITLE
Dart VM crash (version 3.0.0) ../../runtime/vm/runtime_entry.cc: 3118: error: unreachable code

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#53377]
See full core-dump:
https://gist.github.com/jonasfj/46bbd4d6d3bad05e0e151619ec2357d0

This happened in pub.dev, we're upgrading to a later version of the Dart SDK.

Feel free to close this, if it's plausibly already fixed. We'll upgrade and keep and eye on whether or not it keeps happening.

**Comment by a-siva** [comment]
@jonasfj  curious why you upgraded to version 3.0.0 and not version 3.0.7 which is latest hot fix release fot Dart 3.0
we did make some hot fixes for crashers.

**Comment by jonasfj** [comment]
I think we upgraded to 3.0.0 when it was released. Obviously, we should have upgraded to 3.0.7 later.

Now we're moving to 3.1.0 :D

---------------

I guess we can close, and reopen if it happens agian.
