### ISSUE TITLE
the Dart compiler exited unexpectedly, if I place a breakpoint inside a certain function

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#53382]
```
Unhandled exception:
FormatException: Invalid radix-10 number (at character 1)
package:functional_listener/functional_listener.dart
functional_listener.dart:1
^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:152:16)

#2      int._parse (dart:core-patch/integers_patch.dart:98:12)
#3      int.parse (dart:core-patch/integers_patch.dart:60:12)
#4      parseDefinitionTypes (package:front_end/src/api_prototype/expression_compilation_tools.dart:113:36)
#5      createDefinitionsWithTypes (package:front_end/src/api_prototype/expression_compilation_tools.dart:32:7)
#6      IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:219:50)
#7      FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:981:45)
#8      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1452:26)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#14     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#15     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:164:13)
#16     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131:7)
#17     StringConversionSink.add (dart:convert/string_conversion.dart:39:5)
````

It only happens when I set a breakpoint inside 

![image](https://github.com/dart-lang/sdk/assets/16635729/ab0d27f1-475f-40f8-88d5-7571640b9e2a)

if I remove the breakpoint the app doesn't crash.
I also have no idea where I should do an int.parse to get such an exception.  also thee reported file as place where it happens doesn't make sense as the listen function only looks like this

```dart
  ListenableSubscription listen(
    void Function(T, ListenableSubscription) handler,
  ) {
    final subscription = ListenableSubscription(this);
    subscription.handler = () => handler(this.value, subscription);
    this.addListener(subscription.handler);
    return subscription;
  }
```

happens on: Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.19045.3324], locale de-DE)

**Comment by escamoteur** [comment]
unfortunately I couldn't reproduce it with the example from you. I can still reproduce it in our real app project. Still wondering why it crashes in 

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126:5)

and the stack trace seems to have no connection to my code whatsoever.

Is there anything that I can add to my code to get more details? 
Because I have no idea how to reproduce this in a smaller demo project?

**Comment by derekxu16** [comment]
Since you're using VSCode, can you please follow [these instructions](https://dartcode.org/docs/logging/#vmservice) and paste the contents of the log here?

**Comment by escamoteur** [comment]
[dart.log](https://github.com/dart-lang/sdk/files/12498653/dart.log)

**Comment by escamoteur** [comment]
`di` is a global variable defined in my package watch_it

**Comment by escamoteur** [comment]
ok and its a callable class

**Comment by johnniwinther** [comment]
This might be related to https://github.com/dart-lang/sdk/issues/53453 where the crash also originates from `FrontEndCompiler.compileExpression` where an invalid `definitionTypes` value can cause the crash.

@derekxu16 @mraleph Do you know where these values are created?

**Comment by johnniwinther** [comment]
@aam Do you know where calls to `compileExpression` comes from when called through Flutter?

I can see the change that added the `definitionTypes` argument (https://github.com/flutter/flutter/commit/09c0706734010b0dbc8d03157d8eddfb82668da7) but I cannot see any call-site changes other than in tests.

**Comment by aam** [comment]
@johnniwinther wrote
> @aam Do you know where calls to `compileExpression` comes from when called through Flutter?
> 
> I can see the change that added the `definitionTypes` argument ([flutter/flutter@09c0706](https://github.com/flutter/flutter/commit/09c0706734010b0dbc8d03157d8eddfb82668da7)) but I cannot see any call-site changes other than in tests.

Flutter registers `compileExpression` service https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L260, which is invoked by dart vm in https://github.com/dart-lang/sdk/blob/main/sdk/lib/vmservice/running_isolates.dart#L148, which runs when `evaluate` or `evaluateInFrame` service requests were made.

**Comment by derekxu16** [comment]
@johnniwinther do you suspect that your fix for https://github.com/dart-lang/sdk/issues/53453 also fixes this issue?

**Comment by johnniwinther** [comment]
Yes.

**Comment by derekxu16** [comment]
@escamoteur if you try switching to the `master` channel with `flutter channel master` (https://docs.flutter.dev/release/upgrade#changing-channels), you should not see the same compiler crash anymore. Please let us know if you do.

**Comment by escamoteur** [comment]
A bit busy at the moment will try today or tomorrow

**Comment by escamoteur** [comment]
I would really love to but I get suddenly this errors if I switch to master channel

```
PS C:\Entwicklung\projects\watchcrunch-mobile-v2> flutter run
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.6.0/lib/src/internal/image_provider.dart:61:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.6.0/lib/src/internal/image_provider.dart:86:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.6.0/lib/src/internal/image_provider.dart:61:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.6.0/lib/src/internal/image_provider.dart:86:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Error: Type 'DecoderCallback' not found.
      image_provider.CachedNetworkImageProvider key, DecoderCallback decode) {
                                                     ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:99:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode,
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Error: 'DecoderCallback' isn't a type.
      image_provider.CachedNetworkImageProvider key, DecoderCallback decode) {
                                                     ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:99:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode,
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/_image_loader.dart:25:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode,
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/_image_loader.dart:25:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode,
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image_platform_interface-2.0.0/lib/cached_network_image_platform_interface.dart:29:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode,
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image_platform_interface-2.0.0/lib/cached_network_image_platform_interface.dart:29:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode,
    ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_image.dart:32:48: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(BlurHashImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
                                               ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_image.dart:32:48: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(BlurHashImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
                                               ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_widget.dart:218:42: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(UiImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
                                         ^^^^^^^^^^^^^^^
/C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_widget.dart:218:42: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(UiImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
                                         ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'C:\Users\escam\fvm\versions\3.13.4\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1343

* What went wrong:
Execution failed for task ':app:compileFlutterBuildProductionDebug'.
> Process 'command 'C:\Users\escam\fvm\versions\3.13.4\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Running Gradle task 'assembleDebug'...                              6,5s
Exception: Gradle task assembleDebug failed with exit code 1
PS
```

**Comment by johnniwinther** [comment]
@derekxu16 Can we close this, given your verification of the fix for the similar error in #53637 ?

**Comment by derekxu16** [comment]
> @derekxu16 Can we close this, given your verification of the fix for the similar error in #53637 ?

SGTM

**Comment by honeybansal2968** [comment]
> I would really love to but I get suddenly this errors if I switch to master channel
> 
> ```
> PS C:\Entwicklung\projects\watchcrunch-mobile-v2> flutter run
> Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.6.0/lib/src/internal/image_provider.dart:61:5: Error: Type 'DecoderCallback' not found.
>     DecoderCallback decode, // ignore: deprecated_member_use
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.6.0/lib/src/internal/image_provider.dart:86:5: Error: Type 'DecoderCallback' not found.
>     DecoderCallback decode, // ignore: deprecated_member_use
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.6.0/lib/src/internal/image_provider.dart:61:5: Error: 'DecoderCallback' isn't a type.
>     DecoderCallback decode, // ignore: deprecated_member_use
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.6.0/lib/src/internal/image_provider.dart:86:5: Error: 'DecoderCallback' isn't a type.
>     DecoderCallback decode, // ignore: deprecated_member_use
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Error: Type 'DecoderCallback' not found.
>       image_provider.CachedNetworkImageProvider key, DecoderCallback decode) {
>                                                      ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:99:5: Error: Type 'DecoderCallback' not found.
>     DecoderCallback decode,
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:78:54: Error: 'DecoderCallback' isn't a type.
>       image_provider.CachedNetworkImageProvider key, DecoderCallback decode) {
>                                                      ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/cached_network_image_provider.dart:99:5: Error: 'DecoderCallback' isn't a type.
>     DecoderCallback decode,
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/_image_loader.dart:25:5: Error: Type 'DecoderCallback' not found.
>     DecoderCallback decode,
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image-3.2.3/lib/src/image_provider/_image_loader.dart:25:5: Error: 'DecoderCallback' isn't a type.
>     DecoderCallback decode,
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image_platform_interface-2.0.0/lib/cached_network_image_platform_interface.dart:29:5: Error: Type 'DecoderCallback' not found.
>     DecoderCallback decode,
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/cached_network_image_platform_interface-2.0.0/lib/cached_network_image_platform_interface.dart:29:5: Error: 'DecoderCallback' isn't a type.
>     DecoderCallback decode,
>     ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_image.dart:32:48: Error: Type 'DecoderCallback' not found.
>   ImageStreamCompleter load(BlurHashImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
>                                                ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_image.dart:32:48: Error: 'DecoderCallback' isn't a type.
>   ImageStreamCompleter load(BlurHashImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
>                                                ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_widget.dart:218:42: Error: Type 'DecoderCallback' not found.
>   ImageStreamCompleter load(UiImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
>                                          ^^^^^^^^^^^^^^^
> /C:/Users/escam/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_widget.dart:218:42: Error: 'DecoderCallback' isn't a type.
>   ImageStreamCompleter load(UiImage key, DecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
>                                          ^^^^^^^^^^^^^^^
> Target kernel_snapshot failed: Exception
> 
> 
> FAILURE: Build completed with 2 failures.
> 
> 1: Task failed with an exception.
> -----------
> * Where:
> Script 'C:\Users\escam\fvm\versions\3.13.4\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1343
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildProductionDebug'.
> > Process 'command 'C:\Users\escam\fvm\versions\3.13.4\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ==============================================================================
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> java.lang.StackOverflowError (no error message)
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ==============================================================================
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 5s
> Running Gradle task 'assembleDebug'...                              6,5s
> Exception: Gradle task assembleDebug failed with exit code 1
> PS
> ```

@derekxu16 have you found any fix for decodercallback?

**Comment by mraleph** [comment]
@honeybansal2968 Don't ask random questions on random unrelated issues. `DecoderCallback` was removed. So you need to upgrade your dependencies or your code. See https://docs.flutter.dev/release/breaking-changes/3-13-deprecations#updates-to-imageprovider-and-paintingbinding
