### ISSUE TITLE
Failures on Bump actions/checkout from 3.5.3 to 3.6.0...migrate `unnecessary_nullable_for_final_variable_declarations` nnbd experiment tests

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#53393]
There are new test failures on [Bump actions/checkout from 3.5.3 to 3.6.0...migrate `unnecessary_nullable_for_final_variable_declarations` nnbd experiment tests](https://github.com/dart-lang/sdk/compare/595b6542a0c48b9589ab39d5092edc395f8d272a~...aa4760e9615f4ba4681e1b62be821b946b408369).

The tests
```
pkg/linter/test/experiments_test RuntimeError (expected Pass)
pkg/linter/test/rule_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac
unittest-asserts-release-mac-arm64
```

@pq

**Comment by pq** [comment]
Sorry about the noise here. I just removed `experiments_test` (https://dart-review.googlesource.com/c/sdk/+/323447) and I'm hoping that should resolve the issue.  I'll keep an eye on the build.

**Comment by pq** [comment]
Looks green now. Sorry for the hassle!
