### ISSUE TITLE
issue on analyzing & formatting pattern matching for-loop iteration

### ISSUE THREAD

**Issue by anasfik** [dart-lang/sdk#53395]
First, Thank you for maintaining the Dart SDK and having time to check issues, we really appreciate it.

This tracker is for issues related to:

* Dart analyzer and linter

Some other pieces of the Dart ecosystem are maintained elsewhere.
Please file issues in their repository:

* Dart language: https://github.com/dart-lang/language

If you aren't sure, file the issue here, and we'll find the right home for it.
In your issue, please include:

`dart info`:

```dart

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "windows_x64"
- on windows / "Windows 10 Home" 10.0 (Build 19045)
- locale is en-US

#### Project info

- sdk constraint: '>=2.19.0 <4.0.0'
- dependencies: args, cli_completion, equatable, hive, http, mason_logger, pub_updater
- dev_dependencies: build_runner, build_verify, build_version, mocktail, test, very_good_analysis

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
| 365 MB |  -- |              | dart.exe     |
|  79 MB |  -- |              | dart.exe     |
```

I am using Windows.

I don't think I should get compile-time error pointing in the pattern matching iteration for a `Map` entries, this issue is found in another use-case, but it is applicable to the [For and for-in loops](https://dart.dev/language/patterns#for-and-for-in-loops) example in the patterns page documentation.

```dart
Map<String, int> hist = {
  'a': 23,
  'b': 100,
};

for (var MapEntry(key: key, value: count) in hist.entries) {
  print('$key occurred $count times');
}
```

This is not analyzed and formatted properly in my vscode, I triedn on dartpad as well and the same issue occurs:

<img width="1280" alt="image" src="https://github.com/dart-lang/sdk/assets/25140579/5ad26a02-29c9-459b-a644-24a0aed84524">

literally the same code is running fine on [dartpad](https://dartpad.dev/).

I could just go with the usual for-loop iteration of course, but I just wanted to adress this if it can be helpful,

**Comment by lrhn** [comment]
Your SDK constraint says `>=2.19.0`.
That means that the language version used to compile your code is 2.19, and patterns require Dart 3.0.

Try using the minimum SDK version on the `pubspec.yaml` to `>=3.0.0`.

**Comment by anasfik** [comment]
Thank you, didn't notice this.
