### ISSUE TITLE
Remove special handling for linter package in generate_package_config

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#53400]
The linter package has been moved from third_party/pkg/linter in DEPS to pgk/linter in the repo.

A workaround was added to generate_package_config to handle the case that both copies of linter were present.

Linter was removed from DEPS on 2023/08/28, so we can remove this workaround about one week later.
All the bots should have refreshed, and removed it from their caches.
Developers may still have a copy in third_party unless they have run "gclient sync -D".  They will have
seen warning messages saying that linter has been removed, and to run this command, if they
have synced since it was removed from DEPS.

I don't think an added warning, besides the one that already comes from gclient sync and the failure
of generate_package_config, saying the the linter package was found in two places, is needed.

Move of linter into the Dart SDK repo is tracked at (closed) issue:
https://github.com/dart-lang/linter/issues/4411

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/979f5d097cf912389dc4efcf1efa94c2a96b4fd1
