### ISSUE TITLE
PATTERN_NEVER_MATCHES_VALUE_TYPE not raised for record patterns

### ISSUE THREAD

**Issue by shilangyu** [dart-lang/sdk#53405]
Tested on newest master `3.2.0-77.0.dev`.

When performing a pattern match using a record pattern, the diagnostic warning PATTERN_NEVER_MATCHES_VALUE_TYPE will not be raised when expected to.

## Examples

When shape of a record does not match:
```dart
void f(({int a, int b}) x) {
  // no pattern_never_matches_value_type raised
  if (x case (:int f1, :int f2,)) {}
}
```

In fact the type of the matched upon value does not matter, the warning will not be raised even for the following:

```dart
void f(int x) {
  // no pattern_never_matches_value_type raised
  if (x case (:String hello)) {}
}
```

However when the record is used as a type pattern, the warning is correctly raised:

```dart
void f(({int f1,}) x) {
  // warning is raised
  if (x case ({int f1, int f2,}) _) {}
}
```

Finally, this doesn't seem to be a general problem with destructuring patterns, because for example a list pattern does raise the warning:

```dart
void f(int x) {
  // warning is raised
  if (x case [String t]) {}
}
```

Potentially related previous work: https://github.com/dart-lang/sdk/issues/52103

If this is not expected and needs a fix, I would love to dedicate a weekend to dig into this if outside contribution will be welcome here.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/323685
