### ISSUE TITLE
[cfe] Private fields promotion doesn't work for external fields

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53419]
The following test works in analyzer but fails in CFE
```dart
// SharedOptions=--enable-experiment=inference-update-2

class C {
  external final int? _x;

  void test() {
    if (_x is int) {
      _x.isOdd; // CFE. Error: Property 'isOdd' cannot be accessed on 'int?' because it is potentially null.
    }
  }
}

main() {
  C().test();
}
```
cc @stereotype441 

Tested on the edge (Sept 4, 2023) SDK on Linux x64 and on `Dart SDK version: 3.2.0-123.0.dev (dev) (Tue Aug 29 17:03:26 2023 -0700) on "windows_x64"`

**Comment by lrhn** [comment]
That looks correct.

An external field declaration is effectively an external getter and setter. Nothing guarantees that it will return the same value if read twice, so it must not promote.

**Comment by sgrekhov** [comment]
Is that an analyzer issue then? It reports no errors in this test.

**Comment by sgrekhov** [comment]
Created https://github.com/dart-lang/sdk/issues/53426 for the analyzer
