### ISSUE TITLE
Add `// ignore: type=warning` similar to `// ignore: type=lint`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#53420]
Hello!

As of late, numerous lints have moved to using "warning" instead of "info".
This is fine, but code-generators like to disable all lints in generated files. In particular, we had `// ignore_for_file: type=lint` for this

But warnings do not seem to be considered with "ignore type=lint".

Could we either:
- Have type=lint ignore warnings too
  This could be reasonable since it is "lint" not "info"
- Add an "ignore type=warning" for similar purposes

**Comment by lrhn** [comment]
Would that effectively be `type = all`, if you ignore both lints and warnings?

**Comment by rrousselGit** [comment]
We probably wouldn't want to ignore errors

**Comment by rrousselGit** [comment]
> You wouldn't/shouldn't be able to ignore errors

There have been times when we could :)


Folks can provide their own errors using analyzer plugins, and macros seem to enable this too. Maybe those would be ignorable

**Comment by srawlins** [comment]
Implemented with https://github.com/dart-lang/sdk/commit/c93e385975f69be5610976ec893991a6d212cbc6.
