### ISSUE TITLE
Invalid analyzer error for forwarding generative constructor.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#53429]
Example:
```dart
class Super{
  factory Super() = Super._;
  const Super._();
}
class Sub extends Super {
  const Sub.name() : this._();
  const Sub._() : super._();
}
```
The analyzer gives an error on the `Sub.name()` constructor (master branch in DartPad, found locally on tip-of-tree):

> error
> line 6 • A constant constructor can't call a non-constant super constructor of 'Super'.[(view docs)](https://dart.dev/diagnostics/const_constructor_with_non_const_super)
> Try calling a constant constructor in the superclass, or removing the keyword 'const' from the constructor.

The CFE shows no issues.

If I comment out the factory constructor `Super()`, the problem goes away. 
If I add `const` to the `Super()` constructor, the problem goes away.
If I remove `const` from `Sub.name()`, the problem goes away.
It makes no difference whether `Sub.name` is named or unnamed.

In none of the cases does the `Sub.name()` constructor call, or depend on, the `Super()` constructor, so the analyzer seems to be creating a spurious connection between a constant redirecting generative constructor the unnamed constructor of the superclass, if it has an unnamed constructor, and requires the superclass constructor to be constant. If there is no unnamed superclass constructor, that's not a problem.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/324262
