### ISSUE TITLE
[cfe] No error if local variable is referenced before its initialization

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53422]
The following [test](https://github.com/dart-lang/co19/blob/master/Language/Statements/Local_Variable_Declaration/reference_error_A01_t02.dart) fails in CFE (works well in analyzer)
```dart
var x = 0;

f(y) {
  var z = x; // No expected error in CFE
//        ^
// [analyzer] unspecified
// [cfe] unspecified
  if (y) {
    x = x + 1; // No expected error in CFE
//  ^
// [analyzer] unspecified
// [cfe] unspecified
    print(x); // No expected error in CFE
//        ^
// [analyzer] unspecified
// [cfe] unspecified
  }
  var x = x++;
//        ^
// [analyzer] unspecified
// [cfe] unspecified
  print(x);
}

main() {
  f(true);
}
```
Tested on the edge (Sept 4, 2023) SDK on Linux x64

**Comment by chloestefantsova** [comment]
It seems that the CFE does report an error, but in a different way: the declaration of the local variable is treated as the error, and its uses before the declaration are treated as the context.

I suggest adjusting the error expectations for the test as shown below. @johnniwinther WDYT?

```dart
var x = 0;

f(y) {
  var z = x;
//        ^
// [analyzer] unspecified
  if (y) {
    x = x + 1;
//  ^
// [analyzer] unspecified
    print(x);
//        ^
// [analyzer] unspecified
  }
  var x = x++;
//        ^
// [analyzer] unspecified
//    ^
// [cfe] unspecified
  print(x);
}

main() {
  f(true);
}
```

**Comment by johnniwinther** [comment]
Could we (easily?) report the error on the uses (instead of the declaration) ? It looks like that would be more hopeful.
