### ISSUE TITLE
[analyzer] An external private field is erroneously promoted

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53426]
The code below produces an error in CFE but no error is reported in the analyzer
```dart
// SharedOptions=--enable-experiment=inference-update-2

class C {
  external final int? _x;

  void test() {
    if (_x is int) {
      _x.isOdd; // CFE. Error: Property 'isOdd' cannot be accessed on 'int?' because it is potentially null.
    }
  }
}

main() {
  C().test();
}
```
Seems that private fields promotion works here but it shouldn't. An external field declaration is effectively an external getter and setter. Nothing guarantees that it will return the same value if read twice, so it must not promote.

See https://github.com/dart-lang/sdk/issues/53419

**Comment by stereotype441** [comment]
I'll work on this.

**Comment by stereotype441** [comment]
The failure mentioned in https://github.com/dart-lang/sdk/issues/53426#issuecomment-1713387330 was addressed by https://github.com/dart-lang/co19/pull/2309.
