### ISSUE TITLE
[vm/ffi] Add example snippet to `NativeCallable.listener`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53435]
We have users who want to start using the `NativeCallable.listener` https://github.com/dart-lang/sdk/issues/37022#issuecomment-1707818318.

However, we don't have code samples illustrating its use in the API docs.

* https://api.dart.dev/stable/3.1.0/dart-ffi/NativeCallable-class.html

To aid users getting started with this new feature, the API docs should contain some sample code.

Some examples in API docs containing sample code:

* https://api.dart.dev/stable/3.1.0/dart-ffi/AbiSpecificInteger-class.html
* https://api.dart.dev/stable/3.1.0/dart-ffi/NativeFinalizer-class.html

@liamappelbe Could you take a stab at this?

**Comment by akshayjadhav2002** [comment]
hey @dcharkes can you assign it yo me so i can fix it !

**Comment by dcharkes** [comment]
Sure. Feel free to submit a PR.

Or even to just draft it in this thread. We usually ask someone from the language team for feedback on API/docs.
