### ISSUE TITLE
[gardening] exported_symbols_test fails on sanitizers

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53438]
There are new test failures on [[build] Don't export all symbols to the dynamic table.](https://github.com/dart-lang/sdk/commit/b8ee3a999676b0e502c0a2a9cba9730374d9bf83).

The tests
```
vm/dart/exported_symbols_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-asan-linux-release-x64
vm-aot-msan-linux-release-x64
vm-aot-ubsan-linux-release-x64
vm-asan-linux-release-x64
vm-msan-linux-release-x64
vm-tsan-linux-release-x64
vm-ubsan-linux-release-x64
```

Example log: https://dart-ci.appspot.com/log/vm-asan-linux-release-x64/vm-asan-linux-release-x64/200/vm/dart/exported_symbols_test

The sanitizers export extra symbols, should we just skip this test on the sanitizer builds @rmacnak-google ?

**Comment by rmacnak-google** [comment]
Yeah, sounds reasonable to me.
