### ISSUE TITLE
[CP] Fix Dart2JS crash on record pattern outside function body

### ISSUE THREAD

**Issue by biggs0125** [dart-lang/sdk#53449]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/323020

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/324600

### Issue Description

Dart2JS was crashing when a record pattern was used outside the scope of a function body. This could happen in constructor initializers or field initializers.

The crash was due to the CFE's lowering of these patterns to statements containing late local variables. Dart2JS's late lowering assumed that late locals would always be within function bodies and this was true prior to the introduction of the CFE's record pattern lowering.

### What is the fix

The fix is to allow for late locals within more contexts. This just means setting up a scope context for them around field initializers and around constuctors.

### Why cherry-pick

Dart2JS crashes on valid inputs. The fix is simple enough to be low risk.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/53358

**Comment by sigmundch** [comment]
I'm supportive of this cherry-pick

It fixes a crasher in dart2js, while the presence of the issue may be rare, in my opinion the low risk makes the cherry-pick worthwhile.
