### ISSUE TITLE
[gardening] IsolateReload_EnumInMainLibraryModified leaks in asan

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53443]
There are new test failures on [Revert "Revert "linter: Refactor prefer_collection_literals to use context type more""...Test field promotion interaction with `dynamic`.](https://github.com/dart-lang/sdk/compare/783b1aa64ac84f5cab7e2140da1965dab0fb74c8~...4bddf8a25ff894f6a8ac9ee122a1eb2112fd2dd1).

The tests
```
vm/cc/IsolateReload_EnumInMainLibraryModified Crash (expected Pass)
```
are failing on configurations
```
vm-asan-linux-release-x64
```

```
--- Command "run_vm_unittest" (took 04.000211s):
DART_CONFIGURATION=ReleaseASANX64 out/ReleaseASANX64/run_vm_tests --dfe=/b/s/w/ir/out/ReleaseASANX64/gen/kernel-service.dart.snapshot --enable-experiment=records --sound-null-safety --ignore-unrecognized-flags IsolateReload_EnumInMainLibraryModified

exit code:
-6

stdout:
Running test: IsolateReload_EnumInMainLibraryModified
Done: IsolateReload_EnumInMainLibraryModified

stderr:
RELOAD REPORT:
{"type":"ReloadReport","success":true,"details":{"finalLibraryCount":19,"receivedLibraryCount":0,"receivedLibrariesBytes":0,"receivedClassesCount":0,"receivedProceduresCount":0,"savedLibraryCount":18,"loadedLibraryCount":1,"shapeChangeMappings":[{"type":"ShapeChangeMapping","class-id":1189,"instanceCount":1,"fieldOffsetMappings":[[8,8]]}]}}

=================================================================
==290079==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 94 byte(s) in 1 object(s) allocated from:
    #0 0x5582792dfe5d in strdup ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/asan/asan_interceptors.cpp:475:3
    #1 0x5582795e7967 in dart::Dart_TestHelperIsolateReload_EnumInMainLibraryModified(dart::Thread*) out/ReleaseASANX64/../../runtime/vm/isolate_reload_test.cc:6196:3
    #2 0x5582795e7967 in dart::Dart_TestIsolateReload_EnumInMainLibraryModified() out/ReleaseASANX64/../../runtime/vm/isolate_reload_test.cc:6174:1
    #3 0x55827932abca in dart::TestCase::Run() out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:53:3
    #4 0x55827932aecf in dart::TestCaseBase::RunTest() out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:65:11
    #5 0x5582799d3102 in dart::TestCaseBase::RunAll() out/ReleaseASANX64/../../runtime/vm/unit_test.cc:86:13
    #6 0x55827932b749 in dart::Main(int, char const**) out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:414:3
    #7 0x55827932b01a in main out/ReleaseASANX64/../../runtime/bin/run_vm_tests.cc:445:29
    #8 0x7f56bbaf9082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 94 byte(s) leaked in 1 allocation(s).

--- Re-run this test:
python3 tools/test.py -n vm-asan-linux-release-x64 vm/cc/IsolateReload_EnumInMainLibraryModified
```

https://dart-ci.appspot.com/log/vm-asan-linux-release-x64/vm-asan-linux-release-x64/200/vm/cc/IsolateReload_EnumInMainLibraryModified

I don't see an obvious commit in the range, will bisect locally.

```
tools/bisect.dart \
-Dend=783b1aa64ac84f5cab7e2140da1965dab0fb74c8 \
-Dstart=4bddf8a25ff894f6a8ac9ee122a1eb2112fd2dd1 \
-Dtest_command="python3 tools/build.py -mrelease --sanitizer=asan runtime run_vm_tests" \
-Dtest_command="python3 tools/test.py -n vm-asan-linux-release-x64 vm/cc/IsolateReload_EnumInMainLibraryModified" \
-Dfailure_string="leaked"
```

Ensuring failure reproduces on 4bddf8a25ff894f6a8ac9ee122a1eb2112fd2dd1.
Commit 4bddf8a25ff894f6a8ac9ee122a1eb2112fd2dd1, reproduces failure.
Ensuring failure does not reproduce on 144ea5b2066.
Commit 144ea5b2066, does not reproduce failure.
Bisecting 4bddf8a25ff...82bd6a2e43b (17 commits). Trying 5e60f8816a3.
Commit 5e60f8816a3, does not reproduce failure.
Bisecting 4bddf8a25ff...675a83240bb (8 commits). Trying f064b6149b8.
Commit f064b6149b8, does not reproduce failure.
Bisecting 4bddf8a25ff...ebc96ecb832 (4 commits). Trying b8ee3a99967.
Commit b8ee3a99967, does not reproduce failure.
Bisecting 4bddf8a25ff...53fb57ea5e9 (2 commits). Trying 53fb57ea5e9.
Commit 53fb57ea5e9, reproduces failure.
Bisected to 53fb57ea5e9.

**Comment by dcharkes** [comment]
@rmacnak-google it looks like the restoring of some shutdown logic is leaking some memory.

Possibly related:

* https://github.com/dart-lang/sdk/issues/53441

Did we by restoring the shutdown logic create some of the races again?
Are these failures expected?

**Comment by aam** [comment]
Looks like a genuine problem with the test - we should not attempt to reset callback if we never set it.

https://dart-review.googlesource.com/c/sdk/+/324562 with the fix
