### ISSUE TITLE
Tiny typo in bool.hasEnvironment method documentation

### ISSUE THREAD

**Issue by ycherniavskyi** [dart-lang/sdk#53452]
There is a tiny typo in [`bool.hasEnvironment`](https://api.dart.dev/stable/3.0.1/dart-core/bool/bool.hasEnvironment.html) method [documentation](https://github.com/dart-lang/sdk/blob/2bbf99351e0274643b8ab0c14904efbb650ded8b/sdk/lib/core/bool.dart#L60C20-L60C23): `iff` must be replaced by `if`.

**Comment by eernstg** [comment]
Cf. https://www.merriam-webster.com/dictionary/iff.

**Comment by mraleph** [comment]
We should really consider expanding all occurrences of `iff` in the documentation into `if and only if`. Not everybody reading this documentation studied formal math and even if they did - they might have done it some other language (not English), so they are unfamiliar with this contraction. 

Any objections @eernstg @lrhn?

**Comment by eernstg** [comment]
No objections, that makes sense!

**Comment by eernstg** [comment]
Created https://github.com/dart-lang/language/issues/3329.

**Comment by ycherniavskyi** [comment]
@eernstg thank you for the explanation. For sure `iff` makes sense with the provided context. But I also agree with @mraleph that for not a native speaker it is a bit confusing.
