### ISSUE TITLE
Pattern matching invalid never matches

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/sdk#53457]
Following code produces `composite` and doesn't report dead code.
Annotations file is too large to post and it's hard to dissect exact class hierarchy, so I've attached it as a text file.

```dart
void main(List<String> args) {
  pack.NumberType type = pack.CompositeIntegerType.int16;

  switch(type) {
    case pack.CoreNumberType():
      print('core');
    case pack.CompositeIntegerType():  // The matched value type 'NumberType' can never match the required type 'CompositeIntegerType'.
      print('composite');
  }
}
```

[annotations.dart.txt](https://github.com/dart-lang/sdk/files/12548429/annotations.dart.txt)

**Comment by lrhn** [comment]
What do you expect the code to do?


The subtypes of  `NumberType` are declared, if I read it correctly, as:
```dart
sealed class NumberType implements Comparable<NumberType>  {...}
sealed class CoreNumberType implements NumberType {}
sealed class IntegerType implements NumberType {...}
sealed class FloatType implements NumberType {}
enum CoreIntegerType with _NumberTypeCompare implements IntegerType, CoreNumberType {...}
enum CompositeIntegerType with _NumberTypeCompare implements IntegerType {...}
enum CoreFloatType with _NumberTypeCompare implements FloatType, CoreNumberType {}
```
That is quite a sealed hierarchy, so we shouldn't need to worry about any subclasses from other librariies.

The enum value, `CompositeIntegerType.int16`'s runtime type is `CompositeIntegerType`, so it should match the `case CompositeIntegerType():`.

The `case CoreNumberType()` exhaust both `CoreIntegerType` and `FloatType` (because the latter is sealed, and `CoreNumberType` exhausts the only subtype `CoreFloatType`).

**Comment by Zekfad** [comment]
Code works as expected, but analyzer reports that pattern is unmatchable which is not true:

![image](https://github.com/dart-lang/sdk/assets/8970959/4a4ff433-ead8-4de1-81a3-cc1ce3785135)

**Comment by lrhn** [comment]
Thanks. Definitely does not look right.

Pasting this main function into the `annotations.dart` file, and putting it into DartPad, does give the warning:
> warning
> line 261 • The matched value type 'NumberType' can never match the required type 'CompositeIntegerType'.
> Try using a different pattern.

and running it prints "composite", so the analyzer is wrong.

**Comment by denniskaselow** [comment]
As a bit of extra weirdness, the following code shows the same `The matched value type 'Foobar' can never match the required type 'Foo'.` warning, but uncommenting the `Thing`-class and case removes the warning. Seems like this warning only occurs if it's only enums implementing the sealed class.

```dart
void main() {
  Foobar foobar = Foo.foo;
  final result = switch (foobar) {    
    Foo foo => 'foo: $foo',
    Bar bar => 'bar: $bar',
//     Thing thing => 'this is thing $thing',
  };
  print(result);
}

sealed class Foobar {}
enum Foo implements Foobar { foo; }
enum Bar implements Foobar { bar; }
// class Thing implements Foobar {}
```

**Comment by Velkamhell97** [comment]
So it is a bug of the analyzer ?

**Comment by scheglov** [comment]
Support for extension types was fixed as https://github.com/dart-lang/sdk/issues/54561.

**Comment by eernstg** [comment]
Very good, I'll close the issue.
