### ISSUE TITLE
Stdin/out issue on Mac

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53456]
The following [test](https://github.com/dart-lang/co19/blob/master/LibTest/io/Stdin/readByteSync_A02_t01.dart) works on Windows and Linux but fails on Mac. The test is
```dart
import "../../../Utils/expect.dart";
import "dart:async";
import "dart:io";

List<T> flattenList<T>(List list) =>
    list.expand((e) => e is List ? e : [e]).cast<T>().toList();

run_process() async {
  // Read and print the first byte ([5])
  stdout.write(stdin.readByteSync());
  // Try to read and print the second byte (no input here, [-1] passes when
  // process finishes) - all is blocked before
  stdout.write(stdin.readByteSync());
  // print [OK] finally
  print("OK");
}

run_main() async {
  String executable = Platform.resolvedExecutable;
  String eScript = Platform.script.toString();
  int called = 0;

  await Process.start(
          executable, [...Platform.executableArguments, eScript, "test"],
          runInShell: true)
      .then((Process process) async {
    process.stdin.add([5]);
    await new Future.delayed(new Duration(seconds: 2)).then((_) async {
      process.kill();
      await process.exitCode.then((_) async {
        process.stderr.toList().then((errors) {
          Expect.isTrue(errors.isEmpty);
        });
        await process.stdout.toList().then((out) {
          // Expected result is: [5-1OK] string
          Expect.listEquals([53, 45, 49, 79, 75, 10], flattenList<int>(out)); // On Mac deepEquals([53, 45, 49, 79, 75, 10], [53], ) fails
          called++;
        });
      });
    });
  });
  Expect.equals(1, called);
}

main(List<String> args) {
  args.length > 0 ? run_process() : run_main();
}
```

On Mac we have
```
deepEquals([53, 45, 49, 79, 75, 10], [53], ) fails
   [cause: Expect.equals(expected: <6>, actual: <1>Collection lengths are not equal: expected length=6, actual length=1) fails.]
```
Why only the first character ("5") is read from `stdout` on MAC? Is this an issue of Dart API on Mac, or a test issue? On Windows and Linux this test works well

**Comment by mraleph** [comment]
I am not sure there is a specific guarantee in `dart:io` that we flush stdout on exit. 

Have you tried changing your code to do an explicit flush? e.g.:

```dart
Future<void> run_process() async {
  // Read and print the first byte ([5])
  stdout.write(stdin.readByteSync());
  // Try to read and print the second byte (no input here, [-1] passes when
  // process finishes) - all is blocked before
  stdout.write(stdin.readByteSync());
  // print [OK] finally
  print("OK");
  await stdout.flush();
}

// ...

void main(List<String> args) async {
 await (args.length > 0 ? run_process() : run_main());
}
```

**Comment by sgrekhov** [comment]
Adding `await stdout.flush();` doen't change anything. Modified test is still failing on Mac and works on Linux and Windows

**Comment by rmacnak-google** [comment]
Possibly the same underlying issue as https://github.com/dart-lang/samples/issues/195

**Comment by sgrekhov** [comment]
@rmacnak-google thank you for looking into it but I don't think that it's the same issue. To check I tried to add `exit(0);` and `await stdout.flush(); exit(0);` but it didn't change anything.

We need to figure out if this is a bad test or API or documentation issue. In Dart API documentation I didn't find anything describing that `Stdin` behaviour on Mac differs from Windows and Linux. So now I believe that it is an API issue

**Comment by mraleph** [comment]
I read the test again - and only now understood what it tries to do: spawns a process, writes "5" to stdin, waits 2 seconds and kills it. On the child side it reads two bytes synchronously and expects that the second read would return -1 (presumably when the process is being killed?). I don't think this tests any sort of specified behaviour: i.e. there is no guarantee that when you do `process.kill()` the killed process will have a chance to react to its stdin being closed. 

What you could do is to replace `process.kill` with `await process.stdin.close();`. Then I think the test becomes more meaningful - it starts testing that closing stdin would unblock `readByteSync` with -1 result.

**Comment by sgrekhov** [comment]
@mraleph thank you! Updated tests works on all platforms. So, this is a test issue.  Cool!
