### ISSUE TITLE
Create a way to see if a Flutter application for Web is getting close to out of memory crash.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#53463]
It is needed to complete https://github.com/flutter/devtools/issues/6144

We need to alert user if what they are doing has risk to crash application, and what is alternative, so that they are not get so upset when crash really happens.

Flutter for desktop has an API `ProcessInfo.currentRss`, that can be watched in order to trigger such an alert: https://api.flutter.dev/flutter/dart-io/ProcessInfo-class.html

DevTools is hosted on web, so it would be great if similar API is implemented for web.

**Comment by annagrin** [comment]
I wonder if we can use https://web.dev/monitor-total-page-memory-usage/ to collect the memory usage data in devtools itself. I will try it out an report back:)

Alternatively we could try connecting to chrome devtools and use https://chromedevtools.github.io/devtools-protocol/tot/Performance/ but it looks a little complicated.

**Comment by sigmundch** [comment]
Good find @annagrin !

@polina-c - this means you don't need anything else from us, as you can access this API directly using js interop. For example:


```dart
import 'dart:js_interop';

@JS()
@anonymous
class UserAgentSpecificMemoryResult {}

extension UserAgentSpecificMemoryResultExtension on UserAgentSpecificMemoryResult {
  external int get bytes;
}


@JS('performance.measureUserAgentSpecificMemory')
external JSPromise _measureUserAgentSpecificMemory();

Future<UserAgentSpecificMemoryResult> measureUserAgentSpecificMemory() =>
   promiseToFuture(_measureUserAgentSpecificMemory());
```

Here is the official API: https://developer.mozilla.org/en-US/docs/Web/API/Performance/measureUserAgentSpecificMemory

Note:
* This is only supported in chrome and edge, but not in FF or Safari
* it only works if the app is running within a secure context ([see notes](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measureUserAgentSpecificMemory#security_requirements))
