### ISSUE TITLE
Can't see the library documentation in unnamed library declarations

### ISSUE THREAD

**Issue by halildurmus** [dart-lang/sdk#53476]
*Named libraries* provide the convenience of accessing library documentation by simply hovering over the library's name:

![named library](https://github.com/dart-lang/sdk/assets/45524029/6fa8e92b-4316-43e2-8f14-a4fa4c8d0d9a)

However, the same functionality isn't available for *unnamed libraries*. I initially anticipated that hovering over the `library` keyword would show the library's documentation, but unfortunately, it doesn't:

![unnamed library](https://github.com/dart-lang/sdk/assets/45524029/aa62a6f4-e9d3-4be9-8670-8f9edf2071c6)

To access the library documentation for *unnamed libraries*, I'm forced to hover over the import statement for that specific library. This extra step can be cumbersome, especially when I need a quick look at the documentation while actively editing it.

**Comment by bwilkerson** [comment]
It would definitely be reasonable to get the documentation when hovering over the `library` keyword, especially when there's no name.

**Comment by halildurmus** [comment]
https://dart-review.googlesource.com/c/sdk/+/380520
