### ISSUE TITLE
[CFE] Setter with the same name as representation type variable produces an error

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53485]
The following test produces an error on CFE (works on Analyzer)
```dart
// SharedOptions=--enable-experiment=inline-class

extension type I(int id) {
  void set id(int i) {}
}

extension type ET1(int id) {
  void set id(int i) {}
}

extension type ET2(int id) implements I {}

main() {
  ET1 et1 = ET1(1);
  et1.id = 0; // CFE Error: The setter 'id' isn't defined for the class 'ET1'.

  ET2 et2 = ET2(2);
  et2.id = 0; // CFE Error: The setter 'id' isn't defined for the class 'ET2'.
}
```
Instance setter with the same basename as the representation type is allowed
cc @eernstg to confirm

Tested on the edge SDK (Sept 11, 2023) on Linux x64

**Comment by eernstg** [comment]
Yes, it should be allowed to have a representation variable named `id` and a setter named `id=` in the same extension type declaration.
