### ISSUE TITLE
vm/dart/heapsnapshot_cli_test flaky -> Timeout

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#53491]
There are new test failures on [[dart2js] Sort holders before emitting them....[kernel] Add sealed classes GenericDeclaration and GenericFunction](https://github.com/dart-lang/sdk/compare/e401b6f18aca53860f0807d1ee8e13edbc7bbaa0~...b6e3c5cffd859e33a5393da1244f575c320935cc).

The tests
```
vm/dart/heapsnapshot_cli_test Timeout (expected Pass)
```
are failing on configurations
```
vm-tsan-linux-release-x64
```

Log: https://dart-ci.appspot.com/log/vm-tsan-linux-release-x64/vm-tsan-linux-release-x64/211/vm/dart/heapsnapshot_cli_test

/cc @mkustermann

**Comment by dcharkes** [comment]
As per https://github.com/dart-lang/sdk/issues/55227, we don't have issues with timeouts anymore.
