### ISSUE TITLE
package:test dart2wasm integration tests failing

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#53493]
See https://github.com/dart-lang/test/actions/runs/6133921048 - this is only failing at HEAD of the dart sdk.

You can repro the failure locally by checking out the dart-lang/test repo and doing the following:

```
cd integration_tests/wasm
dart test --run-skipped
```

This will time out (fails to load). Unfortunately, it is very hard to diagnose this situation as we are getting no logs and `--pause-after-load` doesn't work because it fails to even start the test properly.

Feel free to ping me directly for help investigating this.

**Comment by osa1** [comment]
I just tried this, with the current SDK main (41ee6a5a946) the tests pass on both Chrome (latest stable) and Firefox (nightly). It looks like we only test with Chrome on CI, so one or both of [SDK, Chrome] need to be updated.

**Comment by jakemac53** [comment]
Oh, I actually did recently unskip these tests as they appeared to be passing now, so this can be closed.
