### ISSUE TITLE
[CP] Fix type promotion of late final fields on DDC and dart2wasm.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#53490]
### Commit(s) to merge

1da590fc3f6af8dc505e926551c0986fc05a67b6

### Target

Beta

### Prepared changelist for beta/stable

~~N/A (see notes below)~~ https://dart-review.googlesource.com/c/sdk/+/325142

### Issue Description

During the rollout of field promotion to google3, it was discovered that late final fields are not properly promoted during DDC and Dart2wasm builds. For example, the code below works in the VM and dart2js, but gets a compile error when building for DDC and Dart2wasm:
```dart
class C {
  late final int? _finalWithInitializer = 0;
  late final int? _finalWithoutInitializer;

  C() {
    _finalWithoutInitializer = 0;
  }

  void test() {
    if (_finalWithInitializer != null) {
      print(_finalWithInitializer + 1);
    }
    if (_finalWithoutInitializer != null) {
      print(_finalWithoutInitializer + 1);
    }
  }
}
```
The reason for the bug is that in DDC and Dart2wasm builds, late fields are lowered to a synthetic getter that accesses a hidden variable (or variables). The lowering was happening before the compilation of code that might refer to the late field. Therefore, type promotion was seeing a reference to a getter rather than a field, and incorrectly concluding that the field was not promotable.

### What is the fix

The fix is to update the kernel representation of getters so that it keeps track of whether a getter arose from the lowering of a late field, and to augment the field promotion logic so that when it sees such a getter, it treats it as a field.

### Why cherry-pick

Cherry-picking this change will allow users of the beta channel to try out field promotion without running into incompatibilities between platforms. I believe it is a low risk change, because it has successfully rolled into google3 without creating any test breakages.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/53462

### Extra Info

~~I can't make a CL for the cherry-pick yet, because origin/beta is still pointing at an old SHA. As soon as origin/beta is updated to point to a recent commit, I'll be happy to create the cherry-pick CL.~~ (see correction below)

**Comment by stereotype441** [comment]
> I can't make a CL for the cherry-pick yet, because origin/beta is still pointing at an old SHA. As soon as origin/beta is updated to point to a recent commit, I'll be happy to create the cherry-pick CL.

I was wrong about this. It turns out that the CL in question cherry-picks cleanly onto the current state of origin/beta, even though it's at an old SHA. I've uploaded the cherry-pick here: https://dart-review.googlesource.com/c/sdk/+/325142

**Comment by itsjustkevin** [comment]
@sigmundch @athomas could you take a look at this cherry-pick?

**Comment by sigmundch** [comment]
The cherry-pick request LGTM, and the CL looks good (I also added a +1 there)

If I understand correctly the scope is pretty limited: This is only for beta, and we even have another beta planned by the end of the month, so this CP doesn't change what will be part of the next stable release. Also, the feature is still under a language experiment flag, so it only affects users of the flag. Seems reasonable to me to approve to get more test coverage of the feature before we enable it.

It appears like the riskiest piece in the CP is that we had to do a kernel format change. Assuming there are no downstream risks associated with that, I believe we are good to go here.

**Comment by itsjustkevin** [comment]
Thank you, cherry-pick approved, we can let the reviewers do the rest of the magic on the CL 🙂.

**Comment by stereotype441** [comment]
@sigmundch 
> The cherry-pick request LGTM, and the CL looks good (I also added a +1 there)
> 
> If I understand correctly the scope is pretty limited: This is only for beta, and we even have another beta planned by the end of the month, so this CP doesn't change what will be part of the next stable release. Also, the feature is still under a language experiment flag, so it only affects users of the flag. Seems reasonable to me to approve to get more test coverage of the feature before we enable it.

The scope is not quite that limited. The feature is under a language experiment flag, but the flag is considered _enabled_ as of language version 3.2. So it affects any user that decides to try Dart language version 3.2, either by putting a `// @dart=3.2` comment in their file or by setting their SDK constraint lower bound to `3.2.0-0`.

However, everything else you say about risk is accurate.

I now have review from Johnni on the CL. I'll wait for an acknowledgement from you about risk before landing, and if I don't hear from you by morning I'll ping you on chat.

**Comment by sigmundch** [comment]
Thanks for the clarification! That makes sense, still LGTM :smile:

**Comment by stereotype441** [comment]
> Thanks for the clarification! That makes sense, still LGTM 😄

Thanks! Sending to CQ now.
