### ISSUE TITLE
[CP] Add a CHANGELOG entry for private field promotion.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#53494]
### Commit(s) to merge

0428501a599fde66e4313eac72754adde076d1ae

### Target

Beta

### Prepared changelist for beta/stable

N/A (see below)

### Issue Description

When I turned on field promotion I forgot to include an update to the CHANGELOG explaining the change. I didn't remember until after the Beta cutoff.

### What is the fix

Add the changelog entry.

### Why cherry-pick

Cherry-picking this change will help beta users to see what changes they can expect in Dart 3.2, and encourage them to test out the new functionality.

The change is extremely low risk since the only affected file is the CHANGELOG itself.

### Risk

low

### Issue link(s)

N/A

### Extra Info

I can't yet create a CL for this cherry-pick because the origin/beta branch is currently at an old SHA, but I have a branch ready to go as soon as origin/beta is updated.

**Comment by mit-mit** [comment]
SGTM

**Comment by sortie** [comment]
Currently Dart does not attempt to maintain a changelog for beta.

This is unlike the stable branch where we have a well defined process & workflow for writing it with mandatory CHANGELOG.md entries for cherry picks. The changelog on the beta branch is usually just the changelog as forked from the dev branch at the branch point, which is usually good enough.

The changelog from main is automatically copied into the stable release when we merge from beta to stable, replacing whatever changelog was on beta. If you commit the changelog entries on main, then they will make it into the final 3.2.0 release. :)

**Comment by stereotype441** [comment]
Fortunately the beta branch point that was chosen (based on 3.2.0-134.0.dev) already includes 0428501a599fde66e4313eac72754adde076d1ae, so the question is moot. Closing this CP request.
