### ISSUE TITLE
[stable, beta][CP] Please cherry pick "Don't export all symbols to the dynamic table"

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#53503]
### Commit(s) to merge

b8ee3a999676b0e502c0a2a9cba9730374d9bf83

### Target

stable, beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/325126  (stable)
https://dart-review.googlesource.com/c/sdk/+/326246  (beta)

### Issue Description

Process terminates with handled exceptions in FFI library, We are seeing consistent process termination with the latest stable Dart executable on Linux with FFI (Please see https://github.com/dart-lang/sdk/issues/53267)

### What is the fix

We were exporting all symbols to the dynamic table so that they could be looked up using `dladdr` for the profiler and backtracer. The symbols include our statically-linked libcxx, which can create trouble when another DSO has a different version of libcxx. Now we export only the VM embedding API functions (`Dart_*`) and use a specially produced table to do the symbolization.

### Why cherry-pick

Users are hitting this issue as segmentation faults and there is no workaround for it.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/53267

**Comment by itsjustkevin** [comment]
@rmacnak-google @jakemac53 could you take a look at this cherry-pick?

**Comment by itsjustkevin** [comment]
Stable has been pushed, keeping this open until the beta is also released.

**Comment by a-siva** [comment]
The next beta of Dart (Dart 3.2 Beta 3) is going to be released soon (Oct 11th) and so it doesn't seem to make sense to cherry pick the change into the current beta. The next beta will have the change.
Closing this issue.
