### ISSUE TITLE
[extension types] Annotating primary constructors

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#53508]
We have a bunch of annotations in `package:meta` that can be used to annotate members and in updating our support for extension types, I'm hitting a challenge with how primary constructors are declared (and can't be annotated).

Take this example:

```dart
extension type E(int i) { 
  E.zero(): this(0);
}
```

Now, suppose I wanted to deprecate the primary constructor... How could I express that?

The closest thing I can think to do is something like this:

```dart
@deprecated
extension type E(int i) {
  E.zero(): this(0);
}
```

and have the deprecation flow down to the `E` primary constructor. The rub is this code could be communicating that _all_ of `E` is deprecated. A very different intent.

Is this something folks have considered? Is there something obvious I'm overlooking?

Was a grammar that would allow something like this considered?

```dart
extension type @deprecated E(int i) { 
   E.zero(): this(0);
}
```

Thanks in advance!

@dart-lang/language-team

**Comment by pq** [comment]
I guess one answer is just to say that primary constructors can't be annotated leaving us to arrive at the desired deprecation in a way something like this:


```dart
extension type E._(int i) {
  @deprecated
  E(int i): this._(i);
  E.zero(): this(0);
}
```

**Comment by bwilkerson** [comment]
Yep. I was just about to comment with exactly that. `@deprecated` is probably not a good example because there has to be a primary constructor, so you can change it but you can't just deprecate it. In this case, just name the primary constructor and create an unnamed constructor in the body and mark the constructor in the body as being deprecated.

But there are other annotations you might want to use on the primary constructor, and the only way to do so is to attach them to the extension type. That's a bit ugly, but doable, unless, like `@deprecated` is can also validly be applied to the extension type.

**Comment by eernstg** [comment]
> I guess one answer is just to say that primary constructors can't be annotated leaving us to arrive at the desired deprecation in a way something like this:

```dart
extension type E._(int i) {
  @deprecated
  E(int i): this._(i);
  E.zero(): this._(0);
}
```

I think this is the best solution with the current design. In general, primary constructors [as I've been thinking about them](https://github.com/dart-lang/language/blob/main/working/2364%20-%20primary%20constructors/feature-specification.md) are intended to make simple usages concise. Any case which is not covered, or which is too unwieldy when expressed as a primary constructor, should simply be expressed as a regular (i.e., non-primary) constructor.

I hope, if and when we actually introduce primary constructors to the language in general, that the language team will be willing to generalize extension types such that it is possible to omit the (presumably useless) primary constructor `E._`.

**Comment by stereotype441** [comment]
Another option Phil and I discussed was to have a special annotation that takes another annotation as an argument. The new annotation is allowed to be applied to any declaration that implicitly declares a primary constructor, and its meaning is that it applies its argument to that implicit primary constructor, e.g. this declaration deprecates the implicit unnamed constructor of `E`:
```dart
@primaryConstructor(deprecated)
extension type E(int i) {
  E.zero(): this(0);
}
```
Whereas this declaration deprecates the entire type `E`:
```dart
@deprecated
extension type E(int i) {
  E.zero(): this(0);
}
```
By extension, we could say that when a class has a default constructor, the same annotation may be used to apply annotations to the default constructor, e.g.:
```dart
// constructor C.new() is visible for testing; type C is visible everywhere
@primaryConstructor(visibleForTesting)
class C {}
```

**Comment by pq** [comment]
Excellent. Thanks for the conversation all!

I'm content requiring a more verbose expression in the (odd?) case where folks want to annotate what would be a primary constructor. If this turns into an issue we can consider other options (like @stereotype441's).

**Comment by pq** [comment]
Closing for now. Feel free to re-open if folks want to continue the conversation.

**Comment by natebosch** [comment]
> to have a special annotation that takes another annotation as an argument

We have multiple implementations of tools that read and react to annotations - this new annotation would require explicit support in every implementation that needs to read the "real" annotation.
