### ISSUE TITLE
[dart2wasm] Constructor body type mismatch

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#53506]
https://dart-review.googlesource.com/c/sdk/+/315820 has broken the flutter engine unit tests. When attempting to instantiate the module in Chrome, we get the following error:

```
Failed to load "geometry_test.dart": Failed to fetch and instantiate wasm module: CompileError: WebAssembly.compileStreaming(): Compiling function #4727:"Highlighter. constructor body" failed: call[0] expected type (ref 384), found local.get of type (ref 47) @+688087
```

When running `wasm-opt -all --print` on our wasm modules, we get the following validation error:

```
[wasm-validator error in function Highlighter.\20constructor\20body] call param types must match, on 
(call $Highlighter._\20constructor\20body
 (local.get $4)
 (local.get $5)
 (local.get $6)
)
(on argument 0)
```

So there appears to be some sort of type mismatch going on when using this constructor. My best guess is that this is the class that is attempting to be instantiated: https://github.com/dart-lang/source_span/blob/48d0f574ee0a92a241c865d47f461803a664b5ba/lib/src/highlighter.dart#L19

Although honestly I'm not sure how that dependency gets pulled in when compiling the web engine.

**Comment by osa1** [comment]
The commit that introduced the bug was reverted in 67f0d4daf0f. Reland CL with the bug fix: https://dart-review.googlesource.com/c/sdk/+/326080.
