### ISSUE TITLE
Code completion includes the wrong elements when local variables/parameters shadow other members/symbols

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#53515]
The type of `aaa` here is `int`, but code completion only shows the `String` from `this.aaa` instead of the parameter. Completing `aaa` then hovering over it shows `int`.

![image](https://github.com/dart-lang/sdk/assets/1078012/d1080d62-ca58-495c-92c3-1de32af92ea5)

The impact of this is probably low, but it results in some missed completions in the code completion metrics scripts.

**Comment by DanTup** [comment]
Maybe the same issue for local variables too:

![image](https://github.com/dart-lang/sdk/assets/1078012/01ac8e54-9864-4b72-bea0-9104d7f13113)

The dartdocs here are because it's picking the field over the local variable (in this case it probably results in a better experience, but only because the local variable happens to be the same as the member).

**Comment by DanTup** [comment]
Similar issue in functions, but not sure if it's the same or not. The local variable `min` here doesn't show up.

![image](https://github.com/dart-lang/sdk/assets/1078012/7b8ba2ad-19b2-4cc5-a0ed-ca3362b9df86)

**Comment by DanTup** [comment]
The first two issue are that the parameter/local variable is added second, but is skipped by this code here (`laterReplacesEarlier` is `false`):

https://github.com/dart-lang/sdk/blob/578f95ad2eb034d7a607d21737ab3f047e8e8878/pkg/analysis_server/lib/src/services/completion/dart/suggestion_builder.dart#L1289

The third issue is the opposite - the local variable is added first, but `laterReplacesEarlier` is `true` so it's overwritten by the `min` function from `dart:math`.

The code here explicitly sets `laterReplcesEarlier` to `false` before walking locals which feels wrong, but I wonder if it's set to work correctly for things being suggested by this contributor, and not considering things that have already been added by other contributors?

https://github.com/dart-lang/sdk/blob/578f95ad2eb034d7a607d21737ab3f047e8e8878/pkg/analysis_server/lib/src/services/completion/dart/local_reference_contributor.dart#L74-L75

**Comment by DanTup** [comment]
(fyi @bwilkerson - I don't know what the right fix for this is, or if it'll be affected by your completion changes, so I won't attempt to fix it unless it's appropriate and you can provide some pointers)

**Comment by bwilkerson** [comment]
The plan is for the rewrite to have a single method that will produce all of the suggestions that are based on names in scope, so the code referenced above, while portions of it might be copied, will be combined and changed in the process. One of the goals for the new implementation will be to remove the need for `laterReplacesEarlier`, reducing the risk of this kind of bug occurring in the future.

**Comment by keertip** [comment]
Cannot reproduce this issue with any of the given examples. 

```
import 'dart:math' show min;

void f()  {
  var min = 1;
  min^
}
```

In this code, the completion shows the local variable only, no min from dart:math. 

The completion code refactor fixed this issue.

**Comment by keertip** [comment]
https://dart-review.googlesource.com/c/sdk/+/358141
