### ISSUE TITLE
Private field is promotable in spite of `noSuchMethod` forwarder

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53510]
The following test fails in both analyzer and CFE
```dart
class A {
  final int? _x = 42;

  void testA() {
    if (_x != null) {
      _x.isOdd;  // No expected error
//       ^^^^^
// [analyzer] unspecified
// [cfe] unspecified
    }
  }
}

class C {
  void _x();

  dynamic noSuchMethod(Invocation inv) {}
}

main() {
  A a = A();
  if (a._x is int) {
    a._x.isEven;  // No expected error
//       ^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
  }
  a.testA();
}
```
According to the https://github.com/dart-lang/language/issues/2020#issuecomment-1663069707 if there is an implicit `noSuchMethod` forwarder in the same library field should not be promotable

cc @stereotype441 

Tested on `Dart SDK version: 3.2.0-edge.655687db777cf07cb4d75398f9eaf2d30ab6af44 (be) (Wed Sep 13 02:35:01 2023 +0000) on "macos_x64"`

**Comment by stereotype441** [comment]
Sorry, that comment doesn't reflect what I actually implemented. What I actually implemented was exactly what @eernstg suggested, namely that a forwarder for a _method_ does not interfere with the getter of a final instance variable. Promotion is only cancelled if there is a noSuchMethod forwarder with the same name which is a getter. I've updated that comment accordingly.

So in @sgrekhov's example, no error should be reported. Which matches the behaviour as of b555e71ecdcca112f449da1656b273663aa65d83.

I'm assigning this issue to myself as a reminder to update the text in the CHANGELOG to reflect this subtlety.
