### ISSUE TITLE
[dart2wasm] Support final encodings for WasmGC

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#53517]
The V8 team is preparing to change over to the final encodings for WasmGC instructions. We need to prepare for this on the dart2wasm side as well. The final encodings are scheduled to land in Chrome 119, and this is a breaking change, the old encodings will not work at all. As a result, we will need a plan for how to transition gracefully to the new encodings. My suggested plan of action:

* Add a flag to dart2wasm for `--emit-final-encodings` or something like that, so that final encodings are opt-in and we don't immediately break anything. The compiler will need to still be able to emit the old encodings if this flag is not passed
* When Chrome 119 ships to stable, the flutter engine and framework will switch to `--emit-final-encodings` when building unit tests and apps, and switch to 119 for its testing/benchmarking in the same change.
* Once both the engine and the framework have shippped this change, remove the old encodings from the compiler and make `--emit-final-encodings` a no-op
* Remove the `--emit-final-encodings` from the flutter engine and framework
* Remove the `--emit-final-encodings` flag completely from dart2wasm

This will avoid any breaking changes along our pipeline.

**Comment by mkustermann** [comment]
@osa1 @askeksa  Could someone look at this (also find tracking issue of binaryen for this)?

**Comment by osa1** [comment]
Binaryen currently supports both encodings, but the encoding to use is [configured when building binaryen][1].

Since `wasm-opt` generates the final .wasm files we need it to be able to generate both old and new encodings. Some options:

- Add a command line flag to binaryen to choose the encoding to use. I think this would be ideal.
- Ship two versions of `wasm-opt`.
- Fork binaryen temporarily during the transition period to add the command line flag.

[1]: https://github.com/WebAssembly/binaryen/blob/2cbe448eb4df17010f0e5f360a8e705da710f3e0/src/wasm-binary.h#L26

**Comment by mkustermann** [comment]
As chrome itself will only support one version and does a breaking change, it means that we shouldn't be concerned about breaking real apps in the world (if there's any such apps atm, they will stop working anyway as soon as users get an update of chrome which requires new encodings). Furthermore 3rd party users can stick with older flutter master channel version.

It may take only 2-3 weeks until new V8 (with new encodings) lands in chrome beta. Maybe we can just switch over at that point dart2wasm & flutter and do solid testing on chrome beta (so when chrome goes to stable, we know flutter+dart2wasm work well there)?

**Comment by osa1** [comment]
Firefox issue for switching to the final encodings: https://bugzilla.mozilla.org/show_bug.cgi?id=1845374.

**Comment by eyebrowsoffire** [comment]
Here is the story so far on landing the final encodings:
* The dart-sdk side change to switch to the final encodings is here: https://dart-review.googlesource.com/c/sdk/+/326300
* Chrome 119 is in beta currently.
* I have opened up draft PRs switching the engine and the framework to Chrome 119. As expected, the wasm bits break on these PRs, but the rest of the CI steps pass.
  - https://github.com/flutter/engine/pull/46841
  - https://github.com/flutter/flutter/pull/136470
* I manually validated the following bits locally on my machine:
  - Ran all web engine unit tests with dart2wasm with the final encodings against Chrome 119, all web engine unit tests are passing.
  - Ran web benchmarks in the framework on Chrome 119 with dart2wasm.
  - Built and ran the Material 3 Demo app in Chrome 119 with dart2wasm + canvaskit with the new encodings. (Also tested against Firefox nightly, which also worked).

Given this validation, I think we're pretty close to being able to try to land the coordinated breaking change. One thing we are still waiting for is to move dart's CI steps to Chrome 119, which should be added as part of https://dart-review.googlesource.com/c/sdk/+/326300.

**Comment by eyebrowsoffire** [comment]
With https://github.com/flutter/flutter/pull/136564 merged, the final encodings support has bubbled all the way through the engine and the framework and is officially landed.
