### ISSUE TITLE
Improve `invalid_reference_to_this` diagnostic message description

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53529]
See https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=invalid_reference_to_this#invalid_reference_to_this

> Description
> The analyzer produces this diagnostic when this is used outside of an instance method or a generative constructor. The reserved word this is only defined in the context of an instance method or a generative constructor.

According to the [specification ](https://github.com/dart-lang/language/blob/4d1e9964352f1777a070315230c9f0ca247f0d08/specification/dartLangSpec.tex#L2842-L2854)(10. Classes) access to `this` is also allowed in the initializing expression of a late instance variable declaration

> The current instance (and hence its members) can only be accessed at specific
> locations in a class: We say that a location ℓ has access to this iff ℓ is inside the 
> body of a declaration of an instance member or a generative constructor, or in
> the initializing expression of a late instance variable declaration

**Comment by eernstg** [comment]
Makes sense! However, I think it should be reported [here](https://github.com/dart-lang/site-www/issues/new?template=1_page_issue.yml&title=[PAGE%20ISSUE]:%20%27Diagnostic%20messages%27&page-url=https://dart.dev/tools/diagnostic-messages.html&page-source=https://github.com/dart-lang/site-www/tree/main/src/tools/diagnostic-messages.md). (Link from 'bug' symbol at the top of the specified documentation page).

**Comment by sgrekhov** [comment]
Thank you! Reported https://github.com/dart-lang/site-www/issues/5172. Closing this issue
