### ISSUE TITLE
[dart2wasm] Skwasm unit tests in flutter engine broken on dart roll

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#53521]
https://dart-review.googlesource.com/c/sdk/+/323445 has broken the skwasm unit tests in the flutter engine, specifically `test/ui/image_golden_test.dart`. I am starting a revert now.

I haven't really isolated this down much, but to reproduce this problem, you can do the following:
1) Build the dart sdk on a version with the https://dart-review.googlesource.com/c/sdk/+/323445 change
2) Set the `DART_SDK_DIR` environment variable to point to the built `dart-sdk` directory
3) In the flutter engine repo:
  * `cd` into the `flutter/lib/web_ui` directory
  * `gclient sync`
  * `./dev/felt build`
  * `./dev/felt test --renderer=skwasm --start-paused test/ui/image_golden_test.dart`
  * Press enter a few times to start the unit tests
4) This should open a browser window and run the unit tests. On the `toImage_rgba` tests, there should be an exception.

This issue is resolved if https://dart-review.googlesource.com/c/sdk/+/323445 is reverted.

**Comment by srujzs** [comment]
Per the CL, I'm guessing there are some callbacks with parameters that are either using `int` where the passed value is not an integer value, or a non-nullable static interop type where the passed value is either `null` or `undefined`. Once the CL is reverted, I'm happy to take a look and fix these tests.

**Comment by eyebrowsoffire** [comment]
This was fixed a while ago.
