### ISSUE TITLE
Inconsistent behavior with static functions inside extensions while importing with alias

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#53522]
![imagen](https://github.com/dart-lang/sdk/assets/73592852/ba746d39-e9d6-4ff0-9ba4-74e73eb84865)

![imagen](https://github.com/dart-lang/sdk/assets/73592852/b86636a5-aee0-4afe-acac-a4de4ede926d)

```
import 'dart:io';

extension DirectoryExtension on Directory {
  static String toJson(Directory directory) => directory.path;

  static Directory fromJson(String path) => Directory(path);
}

class TestClass {
  static String toJson(Directory directory) => directory.path;

  static Directory fromJson(String path) => Directory(path);
}
```

Discussed on Discord:
![267843117-4b86c2c9-481b-4617-9bfa-3c3188e08199](https://github.com/dart-lang/sdk/assets/73592852/c7f011ea-eb80-4284-9faa-e5b08321f996)

**Comment by busslina** [comment]
Discussed on Discord:

![imagen](https://github.com/dart-lang/sdk/assets/73592852/4b86c2c9-481b-4617-9bfa-3c3188e08199)

**Comment by busslina** [comment]
https://github.com/dart-lang/language/issues/3347

**Comment by busslina** [comment]
Closing duplicate

**Comment by lrhn** [comment]
This is an implement bug, so reopening the issue here and closing the language one.

It should work.
It works in the front end, so it's a bug in the analyzer that it complins.
