### ISSUE TITLE
[FFI][`Pointer`] how to allocate aligned memory using `posix_memalign`, not `aligned_alloc`

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#53525]
hello,

I have written a DBMS in dart, working perfect in, in-memory storage, but next step is to go persistent.

How may I allocate storage's block-size aligned memory blocks, using `ffi.DynamicLibrary.process()`.[posix_memalign](https://man7.org/linux/man-pages/man3/posix_memalign.3p.html).

The following code does not work, because making objects of `ffi.Pointer<ffi.Pointer<ffi.Uint8>>` is not allowed.

```dart
import "dart:ffi" as ffi;

void main(){
  final ffi.Pointer<ffi.Pointer<ffi.Uint8>> pointer = ffi.Pointer<ffi.Pointer<ffi.Uint8>>();

  ffi.DynamicLibrary.process().lookupFunction<
      ffi.Int32 Function(ffi.Pointer<ffi.Pointer<ffi.NativeType>> memptr, ffi.Uint64 alignment, ffi.Uint64 size), //
      int Function(ffi.Pointer<ffi.Pointer<ffi.NativeType>> ptr, int alignment, int size)>(
    "posix_memalign",
  )(
    pointer,
    4096,
    (2 * 4096),
  );
}
```

thanks

**Comment by gintominto5329** [comment]
Note:  `ffi::Allocator.allocate` has an optional argument, for alignment, but its ignored by the allocator, as check in the code, of package-ffi's malloc.

**Comment by mraleph** [comment]
Allocate enough memory for storing a pointer (e.g. via `malloc(sizeOf<Pointer<Void>>())`) then pass that to `posix_memalign`.
