### ISSUE TITLE
[FFI] how to `#define _GNU_SOURCE 1`

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#53527]
hello,

In C, I just copy-paste these lines, before all the `#include`s

```
#define _GNU_SOURCE 1
#define _FILE_OFFSET_BITS 64
```

How may I mimic this in dart::ffi

thanks

**Comment by mraleph** [comment]
In `dart:ffi` you describe layouts and signatures explicitly - so just make sure you align those with what these defines imply (they change structure layouts, function signatures and redirect functions, e.g. `open` redirects to `open64`).
