### ISSUE TITLE
Code completion suggests only keywords after `.` inside switch-expression's case's expression

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#53535]
Here's some code:

```dart
void f(num e) {
  switch (e) {
    int() => print(e.^),
  };
}
```

At the carat, I get exactly two completions: `case` and `default:`.

<img width="282" alt="Screenshot 2023-09-14 at 12 43 07 PM" src="https://github.com/dart-lang/sdk/assets/103167/742a65b3-1880-4034-bd4a-e35e1e3326f0">

This is on a fairly recent 3.2.0-dev build.

**Comment by srawlins** [comment]
I think this is exclusively happening because that code is not recognized as a switch expression. If I write `return ` in front of `switch`, the completions are good.

Is this not a legal switch-expression expression-statement?

**Comment by scheglov** [comment]
Yes, `switch` happens where a statement starts, it is a switch statement, not a switch expression.

**Comment by srawlins** [comment]
Ah ok, if I wrap the switch in `(` and `)` then the suggestions are OK there too.

Is this too strange a case to provide better recovery / completions? We can close if this code is too broken to expect good completions.

**Comment by scheglov** [comment]
Well, if the parser does not recover, we cannot do good work in completion here.

**Comment by bwilkerson** [comment]
That isn't necessarily true, but there is a point at which poor recovery means that the code completion engine would essentially need to re-implement some of the parsing logic to determine whether this could have been interpreted as a switch expression. For some cases I think it's worth doing, but in other cases it isn't. I'd have to look at the AST structure the parser produced to know whether it's reasonable in this case.

**Comment by srawlins** [comment]
I'll close; I don't think worth thinking about too much; no reason to continue typing my expression in a broken outer switch expression/statement.
