### ISSUE TITLE
Analyzer support for importing dart:_wasm from package:ui

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#53543]
Is it possible to do something similar to:

https://dart-review.googlesource.com/c/sdk/+/325620

in the Analyzer?

**Comment by vsmenon** [comment]
fyi - @bwilkerson @eyebrowsoffire - marking this P1 and assigning to brian for now.  My understanding is that we need this to unblock flutter wasm (skwasm) to work on chrome stable.

**Comment by vsmenon** [comment]
fyi - @jacob314 - is there someone with cycles to look at this?  and at least assessing if something relatively trivial compared to the cl above is doable?

it's blocking our ability to test wasm variants on various devices.

**Comment by bwilkerson** [comment]
Sorry, I didn't realize just how urgent this was (I missed the P1). Looking at it now.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/326727
