### ISSUE TITLE
Package assets and AOT compilation

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#53569]
When I build a web application, all assets from packages are stored in `outputDir/packages/_package_name_/*`. When I need the same files in a VM application, I use `Isolate.resolvePackageUri` and `File.fromUri`.

What about AOT compilation?
Why not use the same logic as the web build system for AOT compilation to store all asset files in `outputDir/packages/_packageName_`, with Isolate.resolvePackageUri resolving to this folder.

I share many common files in shared packages.

**Comment by a-siva** [comment]
This is being tracked in https://github.com/dart-lang/sdk/issues/39576.

**Comment by a-siva** [comment]
Closing this as a duplicate of https://github.com/dart-lang/sdk/issues/39576
