### ISSUE TITLE
[dart2wasm] import not listed in module imports if there is no `.` in the pragma

### ISSUE THREAD

**Issue by jiahaog** [dart-lang/sdk#53570]
If we use either of the following `@pragma('wasm:import')`s, the import won't be listed in the wasm module imports (I'm using the `WebAssembly.Module.imports` function in d8 to check):

```dart
@pragma('wasm:import', 'fooImport')
external int fooImport(int x);

@pragma('wasm:import')
external int fooImport(int x);
```

This looks to be because we drop the function unless the import name has a `.` in it: https://github.com/dart-lang/sdk/blob/bbbed58d438bdc62c08bd8b9f8df4a85ff9de9a0/pkg/dart2wasm/lib/functions.dart#L54

```dart
// ok
@pragma('wasm:import', 'something.fooImport')
external int fooImport(int x);
```

Should we default to some module, or throw an exception when that happens?

**Comment by osa1** [comment]
In Wasm an import needs two names, a module and for the thing being imported from the module.

I'm not sure if a default module makes sense or whether it's even possible. The only module that we import always is "dart2wasm", which is for the compiler builtins.

I suggest we throw an exception for now. If we later decide to default to a module that will be a backwards compatible change.
