### ISSUE TITLE
How to statically build dart sdk?

### ISSUE THREAD

**Issue by yingshaoxo** [dart-lang/sdk#53585]
I simply found dart can't get running in Ubuntu 7.

It requires a higher version of libc.

When compile nodejs, they have an static building option, so the final node binary executable can get running without libc or shared_library.

How can I do the same thing with dart?

![IMG_20230921_214241_064](https://github.com/dart-lang/sdk/assets/17190829/118f0617-2bc5-481b-bd07-9177a7a709e6)

**Comment by sortie** [comment]
Ubuntu from 2007??

Yeah that's not supported. Even if you somehow linked it, the kernel wouldn't have the needed features I bet. I suggest you just get a newer Linux.

Dart supports Debian stable and Ubuntu LTS under their normal supported release schedules: https://dart.dev/get-dart#linux

**Comment by yingshaoxo** [comment]
I tried to statically compile newest python 3.10 with alpine and musl.

I did a test on ubuntu8. Python works fine. Even if it is 2007 version of Ubuntu.
