### ISSUE TITLE
Incorrect type inference for enums implementing classes

### ISSUE THREAD

**Issue by Quijx** [dart-lang/sdk#53595]
The closest common super class for two enums implementing the same class is inferred to be `Object` instead of that class.

For example
```dart
class Foo {}

enum Bar implements Foo { bar }

enum Baz implements Foo { baz }

Foo getFoo(bool b) {
  return b ? Bar.bar : Baz.baz;
  //     ^^^^^^^^^^^^^^^^^^^^^
  //     A value of type 'Object' can't be returned from the function 'getFoo' because it has a return type of 'Foo'.
}
```
does not compile because the type of `b ? Bar.bar : Baz.baz` is inferred as `Object` and not `Foo`.
If we change this to the following, it compiles fine:
```dart
class Bar implements Foo {
  const Bar._();
  static const bar = Bar._();
}

class Baz implements Foo {
  const Baz._();
  static const baz = Baz._();
}

Foo getFoo(bool b) {
  return b ? Bar.bar : Baz.baz;
}
```

**Comment by eernstg** [comment]
This is working as specified. However, you can take a look at [this topic](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Aleast-upper-bound) in order to see that it isn't quite working as desired.

**Comment by eernstg** [comment]
I'll close this issue because it reports on an issue which has already been covered in https://github.com/dart-lang/language/issues/1618 and elsewhere.

**Comment by Quijx** [comment]
@eernstg Thank you for the explanation. Now that I understand the problem, I found the following workaround:

```dart
class Foo {}

class _Foo extends Foo {}

enum Bar implements _Foo { bar }

enum Baz implements _Foo { baz }

Foo getFoo(bool b) {
  return b ? Bar.bar : Baz.baz;
}
```

This way `Enum` and `_Foo` are on the same level, but `Foo` is uniquely on the level above and is returned as standard upper bound.

**Comment by eernstg** [comment]
Cool! 

(Actually, I haven't checked, but I think the type of the conditional expression is now `_Foo`, which is an OK type for a value which is returned when the declared return type is `Foo`. Anyway, it's great that it works! ;-).

**Comment by Quijx** [comment]
@eernstg Huh.. I didn't actually try to run the code until now, but just pasted it in and the analyzer didn't complain, so I figured it was fine.
However now when I try to run it, it does not compile:

`type_bug.dart`:
```dart
class Foo {}

class _Foo extends Foo {}

enum Bar implements _Foo { bar }

enum Baz implements _Foo { baz }

Foo getFoo(bool b) {
  return b ? Bar.bar : Baz.baz;
}

void main() {
  print(getFoo(true));
}
```

`dart run bin/type_bug.dart`:
```
bin/type_bug.dart:10:12: Error: A value of type 'Object' can't be returned from a function with return type 'Foo'.
 - 'Object' is from 'dart:core'.
 - 'Foo' is from 'bin/type_bug.dart'.
  return b ? Bar.bar : Baz.baz;
```

`dart analyze`:
```
Analyzing type_bug...
No issues found!
```

This is a bug though right? Either the analyzer should also complain or the compiler should accept, right?
Should I open a report for this?

**Comment by eernstg** [comment]
You're making adjustments to the superinterface graph until the graph search algorithm will make the choice that you want. Here is one way to do it that matches the superinterface graphs of the analyzer as well as the VM:

```dart
class __Foo {} // Depth 2, below `Object`.

class _Foo extends __Foo {} // Depth 3.

class Foo extends _Foo {} // Depth 4.

enum Bar implements Foo { bar } // .. and `_Enum` has depth 3, so `Foo` wins.

enum Baz implements Foo { baz }

Foo getFoo(bool b) {
  return b ? Bar.bar : Baz.baz;
}

void main() {
  print(getFoo(true));
}
```

This might be a useful trick even though it feels fragile and arbitrary: If you can live with the fact that one library has some weird subclass hierarchies then the rest of the world will just see that `UP(Bar, Baz)` is `Foo`, and that's all they want.

It _is_ a bug, but that's already covered by https://github.com/dart-lang/language/issues/3290. You might be interested in some figures like this one: https://github.com/dart-lang/language/issues/3290#issuecomment-1685207601.
