### ISSUE TITLE
Expected promotion, but analyzer flags to cast and unwrap

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#53602]
Came up in https://github.com/flutter/flutter/pull/133581#discussion_r1334857027, where the getter debugParentDataType is being added to `ParentDataElement<ParentData>`

There are two casts below that seem like they should not be necessary, but are flagged as necessary by the analyzer for:
- (1) two complaints from the analyzer
  -  unchecked_use_of_nullable_value (but we already know it is not null)
  - undefined_getter (but we already know it is `ParentDataElement<ParentData>` not `Element`)
- (2) one complaint
  - undefined_getter (but we already, now definitely, know it is `ParentDataElement<ParentData>` not `Element`)

```dart
    Element? ancestor = _parent;
    while (ancestor != null && ancestor is! RenderObjectElement) {
      if (ancestor is ParentDataElement<ParentData>) {
        assert(() {
          if (!debugAncestorTypes.add(ancestor.runtimeType)) {
            debugAncestorCulprits.add(ancestor.runtimeType);
          }
          
          // Both of the following casts are required by the analyzer
          // (1)
          if (!debugParentDataTypes.add((ancestor! as ParentDataElement<ParentData>).debugParentDataType)) {
            // (2)
            if (!debugParentDataCulprits.contains((ancestor as ParentDataElement<ParentData>).debugParentDataType)) {
              // Add the first one we had put in the Set of Types.
              debugParentDataCulprits.add(ancestor.debugParentDataType);
            }
            debugParentDataCulprits.add(ancestor.debugParentDataType);
          }
          return true;
        }());
        result.add(ancestor);
      }
      ancestor = ancestor._parent;
    }
```

**Comment by lrhn** [comment]
The `assert `contains a closure. The analysis doesn't know when that closure will be called, so it doesn't promote inside the closure. 
(I know that it's an immediately invoked function expression, but that's not a concept known to the inference. It's a closure. It might get invoked ... whenever. Which could mean outside of the condition which does the promotion. The inference also doesn't realize that `ancestor` can't change, so whatever type it definitely has right here, it will definitely have everywhere. All it can see is that the variable exists in places where it's not promoted, and the function might get called there, and that's Bad.)

If you change the assert to
```dart
        assert((ParentDataElement<ParentData> ancestor) {
          if (!debugAncestorTypes.add(ancestor.runtimeType)) {
            debugAncestorCulprits.add(ancestor.runtimeType);
          }
          if (!debugParentDataTypes.add(ancestor.debugParentDataType)) {
            if (!debugParentDataCulprits.contains(ancestor.debugParentDataType)) {
              debugParentDataCulprits.add(ancestor.debugParentDataType);
            }
            debugParentDataCulprits.add(ancestor.debugParentDataType);
          }
          return true;
        }(ancestor));
```
which passes the promoted type variable into the closure with the correct type, creating a *new* variable at that type which doesn't need promotion, or risk demotion, then it should work without any casts.

**Comment by Piinks** [comment]
Ooo! Thank you very much, I really appreciate the explanation and code update. :)
cc @goderbauer who was wondering about this with me. 

I think we can close this then?

**Comment by Piinks** [comment]
It looks like microseconds per gesture applied, but I am not sure.
