### ISSUE TITLE
Can we export our flutter package in our another project without exposing our code?

### ISSUE THREAD

**Issue by Surajit-Roy** [dart-lang/sdk#53609]
In Android, I can create two applications: one as the parent and the other as the child. In the child app, my intention is solely to use it as a library (.aar). I can then invoke this library in my parent application, ensuring its security so that no one can view my code. Can I achieve a similar setup in Flutter, with one app as the parent and another as the child? In this case, I'd like to use the child application as a library in the parent application while maintaining code security. It's important to note that I do not want to expose any code paths or use pub.dev for this purpose, as I'm prioritizing security. Please provide a valid code solution that meets these requirements.

**Comment by athomas** [comment]
@Surajit-Roy this issue tracker is for reporting issues in the Dart SDK. Your question is a) a question about Flutter, and b) not an issue with the Dart SDK. Please try one of the options on https://flutter.dev/community if you want to get in touch with other Flutter users.
