### ISSUE TITLE
update pkg/dap for the use_super_parameters lint

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#53600]
We're excluding pkg/dap from using the new `use_super_parameters` due to some work required in the code generator (the generated code is triggering the lint). This issue tracks updating the generator and generator code (the work is not expected to be great).

cc @DanTup

**Comment by DanTup** [comment]
> Is there not a label to use for package:dap issue?

The DAP implementation is still in DDS (only the protocol classes were moved out into their own package), so the label is (at least currently) `dds-dap`.
