### ISSUE TITLE
Use sound return types when overriding methods

### ISSUE THREAD

**Issue by martynov-oleg** [dart-lang/sdk#53621]
Include a permanent link to the error if possible.

https://help.github.com/en/articles/getting-permanent-links-to-files

Hello, please tell me why there is an error in the code with the Root class (taken from documentation)
![image](https://github.com/dart-lang/language/assets/5542487/ce5bf8ae-5221-42fd-a887-881512a69eae)

**Comment by parlough** [comment]
Thanks for reporting this!

I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/5372 on the dart.dev repository since I can't seem to transfer this issue there.
