### ISSUE TITLE
analyzer: InheritanceManager3.getInheritedConcreteMap2 throws, given an extension type

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#53638]
Ran across this while working extension type support into dartdoc. I think it is valid to pass an extension type-derived InterfaceElement to `InheritanceManager3.getInheritedConcreteMap2`, but that method then throws this:

```none
Bad state: No element

dart:core-patch/array.dart 56:5                                           _Array.last
package:analyzer/src/dart/element/inheritance_manager3.dart 178:39        InheritanceManager3.getInheritedConcreteMap2
pkg/analyzer/test/src/dart/element/inheritance_manager3_test.dart 448:27  InheritanceManager3Test_ExtensionType.test_getInheritedConcreteMap_x
===== asynchronous gap ===========================
package:test_reflective_loader/test_reflective_loader.dart 281:21         _runTest.<fn>
===== asynchronous gap ===========================
package:test_api/src/backend/declarer.dart 215:9                          Declarer.test.<fn>.<fn>
===== asynchronous gap ===========================
package:test_api/src/backend/declarer.dart 213:7                          Declarer.test.<fn>
===== asynchronous gap ===========================
package:test_api/src/backend/invoker.dart 258:9                           Invoker._waitForOutstandingCallbacks.<fn>
```

because `InheritanceManager3._getInterfaceExtensionType` returns `Interface._(..., superImplemented: const [])`.

CC @scheglov

**Comment by scheglov** [comment]
The documentation says about superclasses and mixins.
```dart
  /// Return signatures of all concrete members that the given [element] inherits
  /// from the superclasses and mixins.
  Map<Name, ExecutableElement> getInheritedConcreteMap2(
      InterfaceElement element) {
    var interface = getInterface(element);
    return interface.superImplemented.last;
  }
```
And extension types don't have them.

What is the use case for invoking it for extension types?

**Comment by srawlins** [comment]
Given this code:

```dart
extension type ET(int it) implements num {}
```

I can call `.abs()` on an expression of type `ET`. But ET does not declare `abs`. If it doesn't "inherit" it either, what word do we use?

Even if I should not be calling `getInheritedConcreteMap2` with an extenion type, it should not crash.

**Comment by scheglov** [comment]
Inherited methods are not necessary concrete.
So, `getInheritedConcreteMap2()` is wrong API for this.
I think we should use `getInheritedMap2()` instead.

https://dart-review.googlesource.com/c/sdk/+/329782 adds a check to prevent the crash, and expands the test to print `inheritedMap`.
