### ISSUE TITLE
`NativeCallable.listener` constructor should accept functions returning `Null`.

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#53659]
At the moment `NativeCallable.listener` only accepts functions returning `void`, but lambdas that have no result return `Null`. So we have to write:

```dart
void callbackFunction() {
  print("Hello");
}
final callback = NativeCallable<CallbackNativeType>.listener(callbackFunction);
```

Instead of:

```dart
final callback = NativeCallable<CallbackNativeType>.listener(() {
  print("Hello");
});
```

To fix this we just have to weaken the check in the CFE to allow `Null` returns. `void` functions return `null` under the hood anyway, so this makes no difference from the VM's perspective.

**Comment by lrhn** [comment]
If the `void` is the Dart `void` type, then accepting a `void`-returning function should mean accepting any return type.
A `Null Function()` is assignable to `void Function()`, and so is an `int Function()`. There is no good reason to disallow any return type, and the Dart type system wouldn't.

**Comment by liamappelbe** [comment]
@lrhn You're not worried that we're implying to the user that we're going to do something with the return value, by accepting any return type? Maybe it's fine as long as we keep the restriction on the type param passed to the class (the `T` in `NativeCallable<T>`), and only remove the restriction on the function passed to the `listener` constructor.

**Comment by lrhn** [comment]
I'd definitely keep the restriction on the type parameter. A native `void` (aka. `Void`) returning function is different from a `Null` (aka `Pointer<Void>`?) function.

And I believe the type argument is required, not inferred, so it's not something the author can miss completely.

Then the Dart function can be any function which is assignable to a Dart `void`-returning function, which is no constraint at all.

**Comment by dcharkes** [comment]
Why is the inferred return type `Null` instead of `void`?

I guess we don't have a explicit return type syntax for lambdas?

The `CallbackNativeType` in the example is undefined (it's not defined in dart:ffi itself). So inlining the type argument would be:

```dart
final callback = NativeCallable<Void Function()>.listener(() {
  print("Hello");
});
```

This should already make it clear that the return type is void.

I'm fine with accepting `Null` return types for lambdas if that's what the Dart language does. (Again, why `Null` and not `void`? 🤔 )

We should ensure to keep giving static errors on non-null non-void return types.

**Comment by thumbert** [comment]
I think I'm running into this issue. 

```dart
  void callable(Size iter, Pointer<Void> params,
      Pointer<gsl_multifit_nlinear_workspace> w) {
    print('Boo');
  }

  var pCallable = NativeCallable<
          Void Function(Size, Pointer<Void>,
              Pointer<gsl_multifit_nlinear_workspace>)>.listener(callable)
      .nativeFunction;
  // what I want:  Pointer<NativeFunction<Void Function(Size, Pointer<Void>, Pointer<gsl_multifit_nlinear_workspace>)>>
```

I get the error:
```
The type 'void Function(Size, Pointer<Void>, Pointer<gsl_multifit_nlinear_workspace>)' must be a subtype of 'Void Function(Size, Pointer<Void>, Pointer<gsl_multifit_nlinear_workspace>)' for 'NativeCallable'.
Try changing one or both of the type arguments.dart[must_be_a_subtype](https://dart.dev/diagnostics/must_be_a_subtype)
void callable(
  Size iter,
  Pointer<Void> params,
  Pointer<gsl_multifit_nlinear_workspace> w,
)
```
If I change the return type of callable to `Void` I get the error  
```
The body might complete normally, causing 'null' to be returned, but the return type, 'Void', is a potentially non-nullable type.
Try adding either a return or a throw statement at the end.dart[body_might_complete_normally](https://dart.dev/diagnostics/body_might_complete_normally)
Void callable(
  Size iter,
  Pointer<Void> params,
  Pointer<gsl_multifit_nlinear_workspace> w,
)
```

Any suggestions of how to get to the type that I need  `NativeFunction<Void Function(Size, Pointer<Void>, Pointer<gsl_multifit_nlinear_workspace>)>`?

Thank you,
T

**Comment by liamappelbe** [comment]
@thumbert That's a different problem, and not a bug in Dart.

You definitely need to return `void` from your function, not `Void`. `Void` is not a real type that's constructable in Dart code, it's just an indicator type used to define other native types like `NativeFunction<Void Function()>` or `Pointer<Void>`.

In a similar vein, `Size` is not a real Dart type, and you can't take it as a parameter to your function. I think this is what's causing your first error message. Change the first arg from `Size iter` to `int iter`.

In general, keep in mind the difference between the Dart function type and the FFI native function type (the type passed to `NativeFunction<...>`). You seem to be mixing them up a bit. There's [a bit of documentation here](https://dart.dev/interop/c-interop#interfacing-with-native-types), but basically there are a bunch of marker types that FFI uses to solve mismatches between Dart's type system and C's (for example, Dart doesn't have different sizes of int, like `int16_t`, just `int`). This distinction is important when loading functions from a dylib into Dart, or creating callbacks to Dart functions.

C function: `int64_t foo(int32_t a, int16_t b) { ...`
Dart FFI native function type: `Int64 Function(Int32, Int16)`
Dart Function type (what you'd get if you load `foo` from a dylib): `int Function(int, int)`
Equivalent Dart function: `int foo(int a, int b) { ...`

**Comment by thumbert** [comment]
@liamappelbe Thanks for the help.  I was able to make it to work.  So easy to get confused between the types on each side!

I have now successfully wrapped the GSL [non-linear optimization example](https://www.gnu.org/software/gsl/doc/html/nls.html#exponential-fitting-example) in Dart.  My first non trivial example.    

T.

**Comment by liamappelbe** [comment]
@dcharkes I was looking into this today. The key function I need to update is `ensureNativeTypeToDartType` at [pkg/vm/lib/transformations/ffi/common.dart:1529](https://github.com/dart-lang/sdk/blob/main/pkg/vm/lib/transformations/ffi/common.dart#L1529). I need to make it so that this function allows the `dartType` to return *anything* when the `correspondingDartType` returns `void`. But I'm confused by two things in this function:

1. It seems like the subtyping check in `ensureNativeTypeToDartType` at pkg/vm/lib/transformations/ffi/common.dart:1529 is backwards. I think we should be checking `dartType is correspondingDartType`, but we're actually checking `correspondingDartType is dartType`. At the moment this check fails for my case. But when I tried just switching them, a bunch of other stuff broke.
2. The rest of the checks nested inside that if statement are explicitly requiring that if either type returns `void`, both do. Why is this check necessary? I was planning to add an optional param to this function to disable this check, but I'm not sure why it exists in the first place.

**Comment by dcharkes** [comment]
> 2. The rest of the checks nested inside that if statement are explicitly requiring that if either type returns `void`, both do. Why is this check necessary? I was planning to add an optional param to this function to disable this check, but I'm not sure why it exists in the first place.

A sanity check. I wanted to avoid having users write FFI bindings that have `void` as the Dart signature but something else as an FFI signature on normal FFI calls. (Having non-void on the FFI call would also mean we do some marshalling on the return value before we forget it, so it would be wasteful.)

Adding a bool to allow anything and only applying it for `NativeCallable`s so that we can take closures SGTM.

> 1. It seems like the subtyping check in `ensureNativeTypeToDartType` at pkg/vm/lib/transformations/ffi/common.dart:1529 is backwards. I think we should be checking `dartType is correspondingDartType`, but we're actually checking `correspondingDartType is dartType`. At the moment this check fails for my case. But when I tried just switching them, a bunch of other stuff broke.

Good point. This code was likely written for FFI calls, and then used for callbacks later. But the typing direction is the other way around for callbacks.

Could you try adding another named boolean param to that method and inverting the direction for FFI callbacks only? (Please also add some tests that catch the current wrong behavior.)

**Comment by liamappelbe** [comment]
Oh right, that makes sense. This check was written for the case where a function is being loaded, and in that case it's correct. Really we should have 2 separate checks, one for when we're returning a native type from an ffi API (how the check is currently written), and another for when we're accepting a native type as a parameter (needs the inverted check). I think it makes sense to write totally separate checks for these cases, so we don't mix them up again.

**Comment by dcharkes** [comment]
> I think it makes sense to write totally separate checks for these cases, so we don't mix them up again.

Whatever solution produces the cleanest and least duplicated code sgtm. 👌
