### ISSUE TITLE
Failures in CI pkg/linter/test/verify_machine_json_test runtime error

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#53650]
There are new test failures on [Increase timeout for dart dev create_integration tests](https://dart-review.googlesource.com/c/sdk/+/328580).

The tests
```
pkg/linter/test/verify_machine_json_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-linux
```

**Comment by bwilkerson** [comment]
I believe the immediate issue was resolved yesterday by https://dart-review.git.corp.google.com/c/sdk/+/328660.

The underlying source of the problem has not been, but there's a different issue discussing solutions. (Sorry, I don't have a link handy.)

**Comment by pq** [comment]
Yep. Hardening this is being tracked in https://github.com/dart-lang/linter/issues/4756.

Disabling it for now: https://dart-review.googlesource.com/c/sdk/+/328684
