### ISSUE TITLE
Unnamed extension of a generic class with a static function ought to be a compiler error

### ISSUE THREAD

**Issue by notcancername** [dart-lang/sdk#53660]
The following code:
```dart
class Foo<T> {}

extension on Foo<int> {
    static void f() {}
}
```
should not be allowed to compile, as `f` cannot be referenced:
```dart
void main() {
    Foo<int>.f(); // compile error: no such named constructor
    Foo.f(); // compile error: no such function
}
```
A note, suggesting naming the extension, should be added.

**Comment by lrhn** [comment]
A static method in an unnamed scope, which has no other members mentioning the member, is unreachable.
But so is a privately named static method which nobody mentions, which I believe the analyzer warns about, so making it a compile-time error might be overkill.

Does warrant a warning, as any dead code.

**Comment by srawlins** [comment]
What a great catch!!

**Comment by srawlins** [comment]
I do get an "unused element" warning here.

> line 4 • The declaration 'f' isn't referenced.

I think there is nothing left to do...
