### ISSUE TITLE
<optimized out> in vs code when debugging if statement value 

### ISSUE THREAD

**Issue by heshesh2010** [dart-lang/sdk#53675]
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A344 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!`

![Screenshot 2023-10-03 at 11 38 44 AM](https://github.com/dart-lang/sdk/assets/16393042/2881c4d1-f97e-43c1-bcab-02969cde8467)

**Comment by a-siva** [comment]
//cc @bkonyi @derekxu16

**Comment by derekxu16** [comment]
deduping to https://github.com/dart-lang/sdk/issues/53654
