### ISSUE TITLE
Relative links to directories don't work on Windows

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53689]
`Link.create()` [documentation](https://github.com/dart-lang/sdk/blob/c04cdf119e59178144a248208f4fe2b2f017e04e/sdk/lib/io/link.dart#L35-L63) says nothing special about relative links on Windows. So, seems, that they should work. But they don't. For example, the tests below works well on Linux but fails on Windows

```dart
import "dart:io";

main() async {
  Directory sandbox = Directory.systemTemp.createTempSync();
  try {
    Directory target =
      new Directory(sandbox.path + Platform.pathSeparator + "dir1");
    target.createSync();
    Link link = new Link(sandbox.path + Platform.pathSeparator + "link.lnk");
    await link.create("dir1").then((Link created) {
      print(created.targetSync()); // Linux: dir1, Windows: dir1
      print(FileSystemEntity.typeSync(created.path)); // Linux: directory, Windows: link
      print(created.resolveSymbolicLinksSync()); // Linux: /tmp/PRVKQP/dir1, Windows: FileSystemException: Cannot resolve symbolic links, path = 'C:\Users\sgrek\AppData\Local\Temp\aba06b27\link.lnk' (OS Error: Access denied , errno = 5)
    });
  } finally {
    sandbox.deleteSync(recursive: true);
  }
}

```
On Windows, `Link` pointing to a not existing entity has type `link` (see https://github.com/dart-lang/sdk/issues/53684#issuecomment-1748329997). So, exception is, probably, also caused by the fact that relative link on Windows cannot find its target. Anyway, please fix it or document that relative links on Windows not supported or have some limitations

Probably this is the same issue as #45981

Tested on `Dart SDK version: 3.2.0-228.0.dev (dev) (Tue Oct 3 21:02:12 2023 -0700) on "windows_x64"`

**Comment by brianquinlan** [comment]
I can't reproduce this. The output using Dart 3.4.0 is:

```
dir1
directory
C:\Users\brian\AppData\Local\Temp\d89223bb\dir1
```

Possibly this was fixed in https://github.com/dart-lang/sdk/commit/097c84f11b04c48fc7a74965ff6f7e5e4175f8cd ?

If these tests are disabled in `co19`, could you try to reenable them and see if they still fail?

**Comment by sgrekhov** [comment]
Yes, the issue was fixed in https://github.com/dart-lang/sdk/commit/097c84f11b04c48fc7a74965ff6f7e5e4175f8cd and appropriate co19 tests updated accordingly.
See https://github.com/dart-lang/co19/commit/d04448ab450608d05460ee467db2d5e4fc245295 and https://github.com/dart-lang/co19/commit/3011a2e78f407ba3f9a3cf543fe17f5e8f2cc294. So, I believe, this issue can be closed.
