### ISSUE TITLE
Generic type parameter is inferred as Object instead of a bounded type

### ISSUE THREAD

**Issue by a-vachasov** [dart-lang/sdk#53685]
When creating a list of instances of a generic class that has a bounded type parameter, Dart seems to infer the type parameter as `Object` rather than using the bound. This behavior is unexpected, especially when all instances in the list satisfy the bounded type.

Below is a minimal code example that showcases the problem:

```
abstract class BlocBase {}

class Cubit extends BlocBase implements ErrorSink {}

class Bloc extends BlocBase implements ErrorSink {}

abstract class ErrorSink {}

class BlocBaseFactory<T extends BlocBase> {
  final T Function() _factory;
  BlocBaseFactory(this._factory);

  T create() => _factory();
}

void main() {
  final factories = [
    BlocBaseFactory(() => Bloc()),
    BlocBaseFactory(() => Cubit()),
  ];
  print(factories.runtimeType);  // Expected: List<BlocFactory<BlocBase>>, Actual: List<BlocFactory<Object>>
}
```

In this example, the BlocFactory class has a generic type parameter T which is bounded by BlocBase. Both Bloc and Cubit extend BlocBase. However, when creating a list of BlocFactory instances, Dart infers the type of the list as `List<BlocFactory<Object>>` instead of the expected `List<BlocFactory<BlocBase>>`. 
Given the bounded type parameter and the provided instances, I would expect Dart to infer the list type as List<BlocFactory<BlocBase>> and definitely never expected `List<BlocFactory<Object>>` because Object is not a BlocBase.

This behavior adds complexity to codebases that heavily utilize generics with bounded type parameters, forcing developers to explicitly specify types to achieve the expected behavior.

dart --version output:
`Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_arm64"`

**Comment by a-vachasov** [comment]
I played with it a bit more and discovered that making BlocBase a generic class changes the behavior, but confuses even more.

Here's the example:
```  
  abstract class BlocBase<T> {}

  class Cubit extends BlocBase<String> implements ErrorSink {}

  class Bloc extends BlocBase<int> implements ErrorSink {}

  abstract class ErrorSink {}

  class BlocFactory<T extends BlocBase> {
    final T Function() _factory;
    BlocFactory(this._factory);

    T create() => _factory();
  }

  void main() {
    final factories = [
      BlocFactory(() => Bloc()),
      BlocFactory(() => Cubit()),
    ];

    print(factories.runtimeType);  // Expected: List<BlocFactory<BlocBase>>, Actual: List<BlocFactory<ErrorSink>>
  }
```

Now the type of the list is inferred as `List<BlocFactory<ErrorSink>>`. The only difference is that BlocBase class is generic.

**Comment by a-vachasov** [comment]
Also, changing the type of the factories list changes the runtime type of the bloc factories within the list.

```
    // Type inference - List<BlocFactory<BlocBase<dynamic>>>
    final factories = <BlocFactory>[  
      BlocFactory(() => Bloc()),
      BlocFactory(() => Cubit()),
    ];

    print(factories.whereType<BlocFactory<Bloc>>()); // Result is an empty list
```

```
    // Automatic type inference - List<BlocFactory<EventSink>>
    final factories = [
      BlocFactory(() => Bloc()),
      BlocFactory(() => Cubit()),
    ];

    print(factories.whereType<BlocFactory<Bloc>>()); // Result is "(Instance of 'BlocFactory<Bloc>')"
```

**Comment by eernstg** [comment]
This is a FAQ. It is working as specified, but not quite as desired.

Here is a set of issues where this topic is discussed: https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Aleast-upper-bound

You can find an explanation about why you get an overly general type in an issue about a very similar situation here: https://github.com/dart-lang/sdk/issues/53663#issuecomment-1741749925.

**Comment by dgreensp** [comment]
Isn't this a bit more serious than the typical case, because Dart is inferring `BlocBaseFactory<Object>` without respecting the bound on the type parameter of `BlocBaseFactory`?  Isn't ignoring the bound unsound?  If the bound can't be used somehow in inference, it seems like there should at least be a compile-time error.

It's weird that a variable can have a static type (and runtime type of its value) of `Foo<Object>`, even if it would be a compile-time error to annotate it as `Foo<Object>`.

I came across this issue because I am in a different situation where I wish the bound on a type parameter was used in inference.

**Comment by eernstg** [comment]
You're right, @dgreensp! The overly general result from the upper bound computation is a FAQ, but I misread the bound violation. Sorry about that.

I've extracted a minimal example that gives rise to the malbounded type and submitted it as https://github.com/dart-lang/sdk/issues/55376.

By the way, we do have a notion of super-bounded types, described in the section 'Super-bounded types' in [the language specification](https://spec.dart.dev/DartLangSpecDraft.pdf), and they are all about passing actual type arguments that do not satisfy the bounds (in a specific, constrained manner). They are useful in cases where we wish to specify a common supertype that cannot be expressed by simply using the bound (e.g., a common supertype of `class C<X extends C<X>> {}` for all `X` which is more specific than `Object`).

But `BlocBaseFactory<Object>` is not a correctly super-bounded type, and inference should not produce a malbounded type, ever.
