### ISSUE TITLE
[VS Code] Icons are incorrect for flutter run

### ISSUE THREAD

**Issue by AbhishekDoshi26** [dart-lang/sdk#53690]
With the latest VS Code version, the icons are not correct when we run the app. You can see that the reload icon is changed.

Is this from Dart/Flutter side or VS Code side?

<img width="357" alt="Screenshot 2023-10-05 at 6 26 22 PM" src="https://github.com/dart-lang/sdk/assets/52591247/52865d4f-aaec-439d-8287-6636da7d1e5a">

CC: @DanTup

**Comment by DanTup** [comment]
This might be a VS Code issue - it seems to be rendering the icon differently in different locations:

https://github.com/microsoft/vscode/issues/194710

**Comment by DanTup** [comment]
This issue has been fixed in VS Code (the editor itself, not the Dart extension) in version 1.83.1.
