### ISSUE TITLE
[CP] Re-enable waitFor for 3.2

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#53691]
### Commit(s) to merge

f8086ed78c206e5c3acf2603478e3ac35e85ba0f

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/329560

### Issue Description

Some packages like `cli_pkg` use `waitFor` to synchronously resolve package uris `waitFor(Isolate.resolvePackageUri(...))`. 

To satisfy this use case we have introduced `Isolate.resolvePackageUriSync` in 3.2.

This unfortunately means that disabling `waitFor` already in 3.2 makes migration unnecessarily bumpy - so we are going to release 3.2 without disabling `waitFor` (but with new API that helps migrating away from it) and then disable `waitFor` in 3.3

### What is the fix

Re-enable `waitFor`

### Why cherry-pick

To make customers migration more smooth.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52121

**Comment by itsjustkevin** [comment]
@vsmenon and @leafpetersen for review please.

**Comment by vsmenon** [comment]
lgtm - thanks!

**Comment by mit-mit** [comment]
SGTM
