### ISSUE TITLE
stdout of Process.start has wrong encoding?

### ISSUE THREAD

**Issue by dHanel** [dart-lang/sdk#53698]
there seems to be a problem with decoding umlauts. my cli is currentling using the german language. running this will result in an unhandeled exception "FormatException: Unexpected extension byte (at offset 18)"
```
Future<void> main() async {
  var process = await Process.start("ping", ["8.8.8.8"], runInShell: false);

  await for (var out in process.stdout.transform(utf8.decoder)) {
    print(out);
  }
}
```
those are the first characters returned by stoud
```
  var chars = const [13, 10, 80, 105, 110, 103, 32, 119, 105, 114, 100, 32, 97, 117, 115, 103, 101, 102, 129, 104, 114, 116, 32, 102, 129, 114, 32, 56, 46, 56, 46, 56, 46, 56, 32, 109, 105, 116, 32, 51, 50, 32, 66, 121, 116, 101, 115, 32, 68, 97, 116, 101, 110, 58, 13, 10];
```

printing them `(print(String.fromCharCodes(chars));` will result in `Ping wird ausgefhrt fr 8.8.8.8 mit 32 Bytes Daten:` while it should be `Ping wird ausgeführt für 8.8.8.8 mit 32 Bytes Daten:`

it seems the bytes returned by stdout are already in a format not being able to be decoed to utf8. i didnt find anything to specify in which format stoud should be returned.

**Comment by lrhn** [comment]
Processes output bytes. The `ping` process seems to be outputting something which is not UTF-8 bytes. The way to control that is probably by setting the locale of the operating system.

That means you should not be using the UTF-8 decoder to convert those bytes to a Dart `String`:

I can't tell precisely which converter you *should* use.
The byte at offset 18 is 129, which is undefined in both Latin-1 and Windows 1252.
Maybe it's code-page 437, where 129 is "ü".


You can create a decoder for CP-437 using `package:convert`, as:
```dart
import 'package:convert/convert.dart' show CodePage;

final CodePage cp437 = CodePage('CP437', _cp437);

const _ascii =
    '\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f'
    '\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f'
    r''' !"#$%&'()*+,-./0123456789:;<=>?'''
    r'@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_'
    '`abcdefghijklmnopqrstuvwxyz{|}~\x7f';

const _cp437 = '$_ascii'
    'ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒ'
    'áíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐'
    '└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀'
    'αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■\xA0';
```
(This is a variant of CP-437 which has control characters, the original CP-437 had special printable characters in those positions.)

It'd probably be better to make the process see a locale that makes it print Latin-1 or UTF-8.
I do not know how to do that.

**Comment by dHanel** [comment]
my cli uses codepage 850 which does contain the letter 'ü'
i created the cp850 like you did in your example but then i get the following error:

"UnsupportedError (Unsupported operation: This converter does not support chunked conversions: Instance of '_BmpCodePageDecoder')"

i guess setting the machine locale to english does work but limiting your program to work only with english proccess output is not ideal.

im running out of ideas and honestly dont know why exactly its not working besides that its an encoding problem....

**Comment by lrhn** [comment]
It is a problem that there is no easy way to predict which encoding the process you start will emit. It's also hard to solve, because it's decided by that process, and Dart cannot know for certain what it will do. It can, at most, make an educated guess based on the locale settings that it can see, but there are many more code pages that might be used, than what the Dart platform libraries know about. And done programs may just do their own thing instead of using the locale. Like Dart programs, where you can decide the `stdout` encoding yourself.

I don't know if there is a way to set a specific locale when spawning a new process. I know you can do something using the environment on Unixes, but that may not be sufficient on Windows. And it'll definitely be different, so whatever is done is OS specific.

**Comment by brianquinlan** [comment]
I'm triaging this with the idea that we should fix `_BmpCodePageDecoder` by implementing `startChunkedConversion`.

If there are other issues to fix, let's file them separately.

**Comment by lrhn** [comment]
It should be trivial to implement chunked conversion, a one-to-one conversion means each chunk can be converted independently, using the base `convert` method.

**Comment by brianquinlan** [comment]
I have a PR that adds that functionality here: https://github.com/dart-lang/convert/pull/91

**Comment by brianquinlan** [comment]
This will be fixed in the next `package:convert` release.
