### ISSUE TITLE
Inconsistent type inference between analyzer and cfe

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#53695]
This tracker is for issues related to:

* Dart analyzer and linter

SDK: `Dart SDK version: 3.2.0-229.0.dev (dev) (Wed Oct 4 01:03:39 2023 -0700) on "macos_arm64"`

The analyzer does not give an error for the following program:

```dart
int? a;

void main() async {
  final (int b, int c) = await (
    Future.value(1),
    a != null ? Future.value(a) : Future.value(1)
  ).wait;
}
```

But running it with the VM results in a compile time error:

```
main.dart:4:21: Error: The matched value of type 'int?' isn't assignable to the required type 'int'.
Try changing the required type of the pattern, or the matched value type.
  final (int b, int c) = await (
                    ^
```

**Comment by lrhn** [comment]
Let's close this issue, and keep the other open. This issue should be linked from there automatically.
