### ISSUE TITLE
[CP] [beta] Cherry pick https://dart-review.googlesource.com/c/sdk/+/328380

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#53713]
### Commit(s) to merge

f36c1094710bd51f643fb4bc84d5de4bfc5d11f3

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/329804

### Issue Description

Crash with EXC_BAD_ACCESS on ios when profiling.

### What is the fix

Don't assume the isolate has a mutator during a profile sample. A profiling sample can be taken when Thread::Current() and Thread::Current()->isolate() are non-NULL. When a thread is entering or exiting an isolate, there is a brief window between the TLS being set/cleared and Isolate::mutator_thread_ being set/cleared

### Why cherry-pick

The bug manifests as a crash when users are profiling their apps and hampers developedr productivity.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/134548

**Comment by itsjustkevin** [comment]
@a-siva it missed the cutoff for this week's release but will be included next week.

Marking as approved as @rmacnak-google has already approved the CL.  If there are opinions against, please speak up.

**Comment by a-siva** [comment]
The change has been merged into the beta branch.

**Comment by itsjustkevin** [comment]
Reopening:  Will close this when it lands in a release
