### ISSUE TITLE
Analyzer fails to downcast from dynamic at `yield`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#53731]
Example:
```dart
// ...
Iterable<T> iterate2<T>(dynamic v1, dynamic v2) sync* {
  yield v1;
  yield v2;
}
```
The analyzer gives errors for the yields, e.g.:
```
line 5 • A yielded value of type 'dynamic' must be assignable to 'T'.[ (view docs)](https://dart.dev/diagnostics/yield_of_invalid_type)
```

That's a bad diagnostic by itself, because `dynamic` *is* assignable to `T`.

The front-end (DartPad, master branch) gives no errors.

It does not appear to affect other coercions. There are no errors in:
```dart
class Callable {
  int call(int x) => x;
}
T generic<T>(T value) => value;

Iterable<int Function(int)> foo(dynamic f) sync* {
  yield Callable();
  yield generic;
}
```

I believe this to be a bug (unless the spec for `sync*`/`yield` is ambiguous or underspecified).

**Comment by eernstg** [comment]
The specification [explicitly states](https://github.com/dart-lang/language/blob/004e8cdeec92b021dece9a8f99a9cfa9e91e8181/specification/dartLangSpec.tex#L19260) that

> It is a compile-time error if the static type of `e` may not be assigned to the element type of `f`

where we're considering a statement `yield e` that occurs in the function `f`, and assignability is [defined](https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/feature-specification.md#assignability) such that an expression of type `dynamic` is assignable to anything. So the specification doesn't seem to be ambiguous or underspecified.
