### ISSUE TITLE
[ddc] `<Object?>[]` incorrectly classified as being `List<Object>`

### ISSUE THREAD

**Issue by askeksa** [dart-lang/sdk#53738]
```dart
bool top<T>() => <Object?>[] is List<T>;

void test<B>() {
  assert(!top<B>());
}

main() {
  test<Object>();
}
```
The assert fails on DDC. This is also triggered by the test added by https://dart-review.googlesource.com/c/sdk/+/320821

**Comment by nshahan** [comment]
What test configuration did you discover this in? I'm not able to reproduce the assertion failure when running with sound null safety. I do see it failing when running with unsound null safety but that seems correct to me.

**Comment by sigmundch** [comment]
FWIW - the test passes in dart2js because the failure is within an assert and none of the dart2js configurations is enabling asserts today.
