### ISSUE TITLE
dart:developer for JS is using performance.mark which is broken on d8

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#53734]
af8fb2cd73c3b5ec96a39c59e85f470efe78d8a4 has provided a Web implementation of `Timeline` APIs from `dart:developer` using `performance.mark`. 

However this API is unfortunately broken on `d8` (which decided to implement only a rudimentary version of it), this means that we can no longer run any code which uses `Timeline` on `d8`. It will fail with the following error:

```
Error: Invalid 'startMark' argument: Not an Object
```

There does not seem to be any way to fully tree-shake or disable `Timeline` implementation in compile time, so if you annotate your code with timeline spans this instrumentation will be included into the production bundle and there is no way to opt out of that. 

/cc @sigmundch

**Comment by sigmundch** [comment]
Thanks, indeed this API is broken in d8, which was the reason @elliette marked the d8 tests as skipbydesign in https://dart-review.googlesource.com/c/sdk/+/310974/10/tests/lib/lib.status#29

She filed a v8 bug here: https://bugs.chromium.org/p/v8/issues/detail?id=14129

**Comment by fishythefish** [comment]
Closing since https://dart-review.googlesource.com/c/sdk/+/310974 is merged.

**Comment by mraleph** [comment]
Status file skips don't actually fix anything e.g. we can't run Flute benchmark on `d8` (or `jsshell` or JSC) for that matter.

I have a fix here which is going to fix this.
