### ISSUE TITLE
"non const arg to const constructor invocation" error should have a fix that changes up const modifiers

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#53744]
Take this code:

```dart
import 'package:meta/meta.dart';

void f(int y) {
  const list = [
    C(y),
    C(),
    ...[C(), C(), C()],
  ];
  print(list);
}

@immutable
class C {
  const C([int? x = 1]);
}
```

This code has an error at `C(y)`: `y` is not constant, so the construction cannot be, and the list cannot be. If a user replaces `const list` with `var list`, they will get 4 new diagnostics about how `C()` should be called as const.

We should offer a fix which finds the "source" of a const context (in this case, `const list`), remove the const keyword, and _add_ the const keyword to sub-expressions, in order to re-create as much of the const context as possible.

**Comment by srawlins** [comment]
CC @stereotype441 @bwilkerson @DanTup @johnpryan

**Comment by srawlins** [comment]
Related: https://github.com/dart-lang/sdk/issues/52046

**Comment by johnpryan** [comment]
Here's a Flutter-y snippet. Adding the the `isVertical` expression causes the Column to be non-const. Removing the `const` from the Column causes the children to be non-const, which triggers the `prefer_const_constructors` lint.

```dart
bool isVertical = false;
Widget build() {
	return const Column(
    direction: isVertical ? 'vertical' : 'horizontal',
    children: [
      Widget(),
      Widget(),
    ],
  );
}

class Widget {
  const Widget();
}

class Column extends Widget {
  final List<Widget> children;
  final String? direction;
  const Column({required this.children, this.direction = 'vertical'});
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/371022

**Comment by srawlins** [comment]
CC @goderbauer

**Comment by johnpryan** [comment]
This is great! Does it work for sub-expressions that are deeply nested too?

**Comment by scheglov** [comment]
Theoretically it should go up to the level where `const` first appears, and remove it there, and the push `const` down to the first node where it can be syntactically added (excluding the node where the error was). So, yes, but if you have a test case in mind, show it, or try it.
