### ISSUE TITLE
Means to optionally include a named argument

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#53764]
If a function makes a named parameter optional by specifying a default value, rather than by making it nullable, then there is no inline syntactical way of conditionally providing an argument to the parameter:

```dart
void x({int? y}) {}
void z({int y = 0}) {}

void baz(bool cond) {
  x();  // (1)
  z();  // (2)
  x(y: cond ? 10 : null);  // (3)
  if (cond) {  // (4)
    z(y: 10);
  } else {
    z();
  }

  // Does not work, but I wish it did:
  z(if (cond) y: 10);  // (5)
}
```

Both default values and a nullable type allow a named parameter not to be specified (`(1)` and `(2)`).

However, while you can conditionally provide an arg to a named parameter if it is nullable (`(3)`), you can't do it if a parameter is not nullable, even if it has a default value -- you have to use an `if`-statement (`(4)`).

It would be great if `if`-statements could be used to optionally provide named arguments (`(5)`). This is analogous to how `if`-statements can be used to optionally include elements in list literals.

**Comment by lrhn** [comment]
That sounds like something like https://github.com/dart-lang/language/issues/2316
I'd suggest using that issue for discussing more ideas.

**Comment by lukehutch** [comment]
Thanks, yes, it's the same request.
