### ISSUE TITLE
Child process continues to run after app is closed on linux

### ISSUE THREAD

**Issue by thiagorb** [dart-lang/sdk#53772]
According to [this documentation](https://api.flutter.dev/flutter/dart-io/Process/start.html), a child process started with mode [ProcessStartMode.detached](https://api.flutter.dev/flutter/dart-io/ProcessStartMode/detached-constant.html) will continue to run even after the application ends, which implies that when using the default mode ([ProcessStartMode.normal](https://api.flutter.dev/flutter/dart-io/ProcessStartMode/normal-constant.html)) that is not the case, i.e., if the child process is started with [ProcessStartMode.normal](https://api.flutter.dev/flutter/dart-io/ProcessStartMode/normal-constant.html), the child process will be terminated when the application ends. Is that the right interpretation?

I tried to run the script below:
```dart
import 'dart:io';

Future<void> main() async {
  final process = await Process.start('bash', ['-c', 'while true; do echo "Hello from bash!"; sleep 1; done;']);

  process.stdout.pipe(stdout);

  await Future.delayed(const Duration(seconds: 3));
  exit(0);
}
```

My expectation was that the bash script started by my application would be terminated together with the application, but it was not. Instead it was re-parented by the OS, and continued to run in the background, as can be seen in the video below:
[output.webm](https://github.com/dart-lang/sdk/assets/821208/c31078b5-c63b-4eb6-ad9b-fd6953529616)

### dart info output

```console
#### General info

- Dart 3.1.3 (stable) (Tue Sep 26 14:25:13 2023 +0000) on "linux_x64"
- on linux / Linux 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2
- locale is en_US.UTF-8

#### Process info

No Dart processes found.
```

**Comment by brianquinlan** [comment]
On POSIX, we are using `execvp` to start subprocesses. 

In normal mode the process organization looks like this (`sleep 1000`) is the subcommand:

| COMMAND | PID | PPID | PGID | TPGID | TT | STAT | TIME |
| - | - | - | - | - | - | - | - |
| dart childproces | 56569 | 54898 | 56569 | 56569 | s023 | S+ | 0:00.25 |
| sleep 1000 |  56572 | 56569 | 56569 | 56569 | s023  | S+ | 0:00.00 |

In detached mode the process organization looks like this (`sleep 1000`) is the subcommand:

| COMMAND | PID | PPID | PGID | TPGID | TT | STAT | TIME |
| - | - | - | - | - | - | - | - |
| dart childproces | 55565 | 54898 | 55565 | 55565 | s023 | S+ |  0:00.26 |
| sleep 1000 |  55568 | 1 | 55567 | 0 | ?? | S | 0:00.00 |

From the Linux documentation for exit:

>        Except in the above cases, where the signalled processes may be
>        children of the terminating process, termination of a process
>        does not in general cause a signal to be sent to children of that
>        process.  However, a process can use the [prctl(2)](https://www.man7.org/linux/man-pages/man2/prctl.2.html)
>        PR_SET_PDEATHSIG operation to arrange that it receives a signal
>        if its parent terminates.

Probably the right place to document this is in `exit`.

**Comment by brianquinlan** [comment]
`ExitProcess` behaves the same on Windows.

**Comment by a-siva** [comment]
The documentation has been updated, closing this issue.
