### ISSUE TITLE
[Analyzer] Error when calculating upper bound of an extension type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53781]
The following tests failing in analyzer (works in CFE)
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/upper_bound_A01_t01.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/upper_bound_A01_t04.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/upper_bound_A01_t05.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/upper_bound_A01_t06.dart

Example:

```dart
// SharedOptions=--enable-experiment=inline-class

import '../../Utils/static_type_helper.dart';

extension type ET1(Object? o) {}
extension type ET2(Object o) {}

extension type ET3(Object? o) implements ET1 {}
extension type ET4(Object o) implements ET2 {}

main() {
  var v1 = 2 > 1 ? ET1(Object()) : ET2(Object());
  v1.expectStaticType<Exactly<Object?>>(); // Fails, actual type Object in the analyzer

  var v2 = 2 > 1 ? ET1(null) : ET2("String");
  v2.expectStaticType<Exactly<Object?>>();  // Fails, actual type Object in the analyzer

  var v3 = 2 > 1 ? ET1(Object()) : ET3(Object());
  v3.expectStaticType<Exactly<ET1>>();

  var v4 = 2 > 1 ? ET1(Object()) : ET4(Object());
  v4.expectStaticType<Exactly<Object?>>();  // Fails, actual type Object in the analyzer

  var v5 = 2 > 1 ? ET2(Object()) : ET4(Object());
  v5.expectStaticType<Exactly<ET2>>();
}
```
Tested on `Dart SDK version: 3.3.0-edge.e4bb5b608b42b97012e968866866922ccf175eba (be) (Tue Oct 17 10:28:23 2023 +0000) on "linux_x64"`

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/330900
