### ISSUE TITLE
Failures Reland "[vm/compiler] Change MemoryCopy to also take untagged addresses."

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#53789]
There are new test failures on [Extension type. Issue 53725. Use representationTypeErasure of the matched type....Reland "[vm/compiler] Change MemoryCopy to also take untagged addresses."](https://github.com/dart-lang/sdk/compare/4d1bdaaca9f600545e8517349714f6bf683ebbe3~...e4dfda311b9c45c0d6f948dcf333e8dbd66c2002).

The tests
```
ffi/extension_methods_test Crash (expected Pass)
ffi_2/extension_methods_test Crash (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-x64
dartkp-linux-release-x64
```

See [log](https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-debug-x64/dartkp-linux-debug-x64/14378/ffi_2/extension_methods_test)

/cc @sstrickl Could this be related to your changes?

**Comment by sstrickl** [comment]
Thanks, looking into it now!
