### ISSUE TITLE
Bug when has PIPE operator in value through --define in cli

### ISSUE THREAD

**Issue by marcusedu** [dart-lang/sdk#53794]
Consider te programm:
```dart
void main(List<String> args){
    print(String.fromEnvironment('SAMPLE', defaultValue: 'error'));
}
```
when run ```dart ./main.dart --define="SAMPLE=success"``` the output is ```success```
but if has **|** (pipe) in the value doesn't works
```dart ./main.dart --define="SAMPLE=success|fails"``` 
the output is ```'fails' is not recognized as an internal command or external command, an operable program, or a batch file.```

dart info output:
```bash
dart info


If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.1.3 (stable) (Tue Sep 26 14:25:13 2023 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22621)
- locale is pt-BR

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
```

**Comment by eernstg** [comment]
@johnniwinther, is the management of the compilation environment determined by the common front end? If that's not true then it would be great if you could say something about who's a good contact person (or maybe we need more than one) for this topic!

**Comment by lrhn** [comment]
This sounds more like that `dart` script is not escaping the command line entries before running a secondary executable. 
That is, it's a command-line issue.

**Comment by bkonyi** [comment]
Since this is a bug originating from a script shipped with Flutter, I've filed https://github.com/flutter/flutter/issues/137079.
