### ISSUE TITLE
How to add a property to UntaggedClass

### ISSUE THREAD

**Issue by hbwangcaihua** [dart-lang/sdk#53802]
I have download flutter engine to Local, it is run well when I use it in my local。
But when I add a property in UntaggedClass (like below picture), it crash in Deserializer::Deserialize
![image](https://img-blog.csdnimg.cn/278451c77efb4ffa86f17e2567f7187b.jpeg)
and the carsh info is below
![image](https://img-blog.csdnimg.cn/72631c40e7b54fe985e2447081f70d99.png)

what else I should do?

**Comment by hbwangcaihua** [comment]
I have try add F(Class, test_add_custom_)  and  modified runtime_offsets_extracted.h
all is not ok

**Comment by mraleph** [comment]
It should work without any additional modifications.  Are you sure you are deserializing snapshot which has a matching version? (e.g. if you add a field then you can no longer deserialize snapshots created by `gen_snapshot` which did not contain this field). Trying building debug version of the VM and see if any assertions trigger.

**Comment by hbwangcaihua** [comment]
> It should work without any additional modifications. Are you sure you are deserializing snapshot which has a matching version? (e.g. if you add a field then you can no longer deserialize snapshots created by `gen_snapshot` which did not contain this field). Trying building debug version of the VM and see if any assertions trigger.

Thanks for your answer
I use  "flutter build ios --local-engine-src-path=xxxxx/engine/src  --local-engine=ios_release_unopt --release"  to generate app.framework，and the flutter.framework also is just generated by "ninja -C out/ios_release_unopt -j 6"
I don't think it is the version problem

**Comment by mraleph** [comment]
Then it should work. Is this the only change or are you changing something else as well: do you just add a field or do you actually put something into this field?

**Comment by hbwangcaihua** [comment]
> Then it should work. Is this the only change or are you changing something else as well: do you just add a field or do you actually put something into this field?

 I just add a field  (other place no change,  include the whole flutter engine code)， in order to resolve the problem
else, the code is flutter 3.7.8 version , and the dart is 2.19.5

**Comment by mraleph** [comment]
Then it _should_ work. Just to verify that we did not break anything I have testing it locally and I can see that it works just as expected. You will have to step through in the debugger to figure out what exactly is going wrong.

**Comment by hbwangcaihua** [comment]
> Then it _should_ work. Just to verify that we did not break anything I have testing it locally and I can see that it works just as expected. You will have to step through in the debugger to figure out what exactly is going wrong.

I find the reason.   After I "flutter clean",  and then "flutter build ios --local-engine-src-path=xxxxx/engine/src --local-engine=ios_release_unopt --release",  it is work

**Comment by mraleph** [comment]
Great to hear. So it was a snapshot version mismatch after all.
