### ISSUE TITLE
Python-style function decorators

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#5381]
Without Python-like decorators, or being able to redefine a function, it becomes very hard to wrap recursive functions to do things like automatically memoize them, log calls, transform results, etc. It's actually impossible to do without designing the function to be wrapped in the first place by taking itself as an argument, or possibly by using a class rather than a function. Neither approach is as elegant as decorators.

Decorators would allow this wrapping by redefining the function at compile time with the result of the decorator. It would fit in nicely with Dart's less dynamic that Javascript or Ruby nature while still allowing a few of the use cases for rebinding function names to be covered.

**Comment by kirbyfan64** [comment]
IMO this would be nicer now that there are *multiple* Dart systems that don't support mirrors (before dart2js, now also Flutter).

**Comment by Levi-Lesches** [comment]
I know this is outdated, but I couldn't find anything else on this. Why is this obsolete? I think a way to quickly wrap a function would be nice. My use-case is wrapping CPU-heavy code in Firebase performance tracing. Of course, I could just manually write the code over and over again, but it really is basic: 

```dart
Future<void> doExpensiveOperation() async {
  // start trace
  final data = await getData();  // takes a while
  final userModel = UserModel(data);  // needs to process data, also takes a while
  writeToFile(userModel.toJson());  // IO *could* add to the wait time, but also could be async...
  // stop trace
}
```
I'd like if I could just simplify that into: 
```dart
@trace("Description of expensive operation to appear in Firebase console")
Future<void> doExpensiveOperation() async {
  final data = await getData();
  final userModel = UserModel(data);
  writeToFile(userModel.toJson());
}
```

**Comment by mraleph** [comment]
@Levi-Lesches It is obsolete because original motivation for it has disappeared. That is not to say that this will never be considered again, but it is not currently being looked at by the language team.

For you particular use case you could do this instead:

```
Future<void> doExpensiveOperation() => trace("Description of expensive operation to appear in Firebase console", () async {
  final data = await getData();
  final userModel = UserModel(data);
  writeToFile(userModel.toJson());
});
```

which is roughly the same thing. (a bit less magical and maybe a bit less readable too)

**Comment by Levi-Lesches** [comment]
Ah, thanks. Sometimes I forget about Functions being first-class.

**Comment by andy1xx8** [comment]
> @Levi-Lesches It is obsolete because original motivation for it has disappeared. That is not to say that this will never be considered again, but it is not currently being looked at by the language team.
> 
> 
> 
> For you particular use case you could do this instead:
> 
> 
> 
> ```
> 
> Future<void> doExpensiveOperation() => trace("Description of expensive operation to appear in Firebase console", () async {
> 
>   final data = await getData();
> 
>   final userModel = UserModel(data);
> 
>   writeToFile(userModel.toJson());
> 
> });
> 
> ```
> 
> 
> 
> which is roughly the same thing. (a bit less magical and maybe a bit less readable too)
> 
> 
> 
> 
> 
> 

Yes but the idea of @Levi-Lesches is better. It is not change the original code base keep the code is readable and stick to its job
