### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Muhammadsaid22** [dart-lang/sdk#53816]
## Version information

- `IDEA AI-213.7172.25.2113.9123335`
- `3.0.3`
- `AI-213.7172.25.2113.9123335, JRE 11.0.13+0-b1751.21-8125866x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 , screens 1366.0x768.0`

When i update my Android Studio i get some kind of error every time. Why Android studio release new version with some bugs ?

**Comment by lrhn** [comment]
I'm not sure this is the most useful forum for asking questions about Android Studio updates. I recommend finding a forum about Android Studio.
