### ISSUE TITLE
Constant evaluator assumes all `dart.library.x` strings exist in compilation environment.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#53815]
The constant evaluator assumes a compilation environment where, e.g., `dart.library.core` is set to `"true"`, which is correct, but also assumes that *every* string starting with `dart.library.core` has a value which is either `"true"` or `""`.
That's *incorrect*.

It should behave as if there is only a `true` entry for the libraries that exist, and no entry for everything else.

It makes a difference because the VM can do *runtime* lookups of the same keys, and only sees entries for libraries that are actually there (it doesn't have an infinite number of declarations in the environment), which means we have `bool.hasEnvironment` giving different results for the same key in different parts of the same program. 
That's a violation of the rules for the compilation environment (it must be consistent across a single program).

Example:
```dart
void main() {
  print(const bool.hasEnvironment("dart.library.banana")); // true
  print(bool.hasEnvironment("dart.library.banana")); //       false
}
```

The fix, as stated above, is to treat the entries which is assumed to have an empty string as value, instead as not being there.
That makes no difference for conditional imports/exports.

The code is in `constant_evaluator.dart`:
```dart
  String? lookupEnvironment(String key) {
    if (DartLibrarySupport.isDartLibraryQualifier(key)) {
      String libraryName = DartLibrarySupport.getDartLibraryName(key);
      String? value = (_supportedLibrariesCache ??=
          _computeSupportedLibraries())[libraryName];
      return value ?? "";
    }
    return _environmentDefines![key];
  }

  bool hasEnvironmentKey(String key) {
    if (key.startsWith(DartLibrarySupport.dartLibraryPrefix)) {
      return true;
    }
    return _environmentDefines!.containsKey(key);
  }
```

This *will* change the answer for `bool.hasEnvironment`, from constantly true for `dart.library.xyz` to depending on whether the `xyz` library is there.
Similarly it will change `String.fromEnvironment` to use the default value instead of always giving `""`.

But since the current behavior is completely constant, it's unlikely anyone is actually asking.

**Comment by johnniwinther** [comment]
@lrhn I remember seeing some CL related to this. Did you fix it or is there still more work to do?
