### ISSUE TITLE
[CFE] [Extension type] No error if member is called on nullable representation type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53822]
UPD Changed to be a CFE issue

The following code produces errors in CFE but not in an analyzer
```dart
// SharedOptions=--enable-experiment=inline-class

extension type ET<T>(T _) {
  void test() {}
}

main() {
  ET(null).test();  // CFE: Error: Method 'test' cannot be called on 'ET<Null>' because it is potentially null.
  ET<int?>(42).test();  // CFE: Error: Method 'test' cannot be called on 'ET<int?>' because it is potentially null.
}
```

cc @eernstg to confirm that it is an analyzer issue

Tested on `Dart SDK version: 3.3.0-edge.849459109a364f7f80ca82647ad088a4a6157ebc (be) (Sat Oct 21 02:18:48 2023 +0000) on "macos_x64"`

**Comment by bwilkerson** [comment]
@scheglov

**Comment by lrhn** [comment]
Not sure I agree.

The extension type itself might not be non-nullable, but it doesn't have to be to get methods called, just like you can call regression methods `on` nullable types.

The `test` method exists on all instantiations of `ET`, and you should be able to invoke it using the code shown here. No member of the representation object is invoked, so it shouldn't matter that it's `null`.

I think it's CFE who's wrong here.

**Comment by lrhn** [comment]
Not sure I agree.

The extension type itself might not be non-nullable, but it doesn't have to be to get methods called, just like you can call regression methods `on` nullable types.

The `test` method exists on all instantiations of `ET`, and you should be able to invoke it using the code shown here. No member of the representation object is invoked, so it shouldn't matter that it's `null`.

I think it's CFE who's wrong here.

**Comment by eernstg** [comment]
Agreeing with @lrhn, this is a CFE issue.

It makes no difference for an extension type `E` whether it is potentially nullable or it is non-nullable, it is in any case allowed to invoke a member of the interface of `E` on a receiver whose static type is `E`.

This is similar to the treatment of extension members (`extension`, not `extension type`), where the on-type can be potentially nullable or nullable, but that won't make it an error to call the extension method on any receiver that matches that on-type.

```dart
extension E on int? {
  int? operator +(int? other) => switch ((this, other)) {
    (null, _) || (_, null)=> null,
    _ => this + other,
  };
}

void main() {
  int? i = null;
  print(i + i);
}
```

On the other hand, a type of the form `T?` has the usual effect:

```dart
extension type E(int it) {
  E operator +(E other) => E(it + other.it);
}

void main() {
  E? e;
  print(e + E(1)); // Error: `e` can be null.
}
```
