### ISSUE TITLE
Missing switch-case quick fix returns null

### ISSUE THREAD

**Issue by firephreek** [dart-lang/sdk#53832]
The quick fix for missing case statements for switch expressions generates code that returns 'null'. Darts null-safety-by-default means this turns entire blocks of code into big error blocks which is distracting and obfuscates the now-offending line of code.  Additionally, each statement is accompanied by a 'TODO' comment line which adds more noise to the generated code.

Instead of returning null (` => null`), we opt for  ` => throw UnimplementedError(\'Handle this case'\)`.  This code is still unambiguous about it's requirements, creates an in-app error that encourages developers to address the code correctly, and satisfies darts null-safety requirements meaning no error is reported by the analyzer.

**Comment by bwilkerson** [comment]
Fixed by https://dart-review.git.corp.google.com/c/sdk/+/331843.
