### ISSUE TITLE
Dart Tooling Daemon: Overall Progress

### ISSUE THREAD

**Issue by CoderDake** [dart-lang/sdk#53841]
See https://github.com/orgs/dart-lang/projects/80 for up to date progress.(You may need to ping me for permissions in discord)

[https://docs.flutter.dev/go/dart-tooling-daemon](https://docs.flutter.dev/go/dart-tooling-daemon)

**Comment by CoderDake** [comment]
https://github.com/dart-lang/sdk/issues/53842
https://github.com/dart-lang/sdk/issues/53843
https://github.com/dart-lang/sdk/issues/53844
https://github.com/dart-lang/sdk/issues/53297
https://github.com/dart-lang/sdk/issues/53300
https://github.com/dart-lang/sdk/issues/53845
https://github.com/dart-lang/sdk/issues/53846
https://github.com/dart-lang/sdk/issues/53847
https://github.com/dart-lang/sdk/issues/53841

**Comment by parlough** [comment]
Do you have one or more design docs added as go links on flutter.dev that you can link to from this issue?

**Comment by CoderDake** [comment]
@parlough what do you mean by on flutter.dev?
I have a go link to the design doc in google docs, but I'm not sure about flutter.dev

**Comment by parlough** [comment]
Maybe one is already added or you're not ready to share publicly, I'm not sure.

But if/when you're ready to share a design doc publicly (which is great <3), you can add a public `/go` link redirect on the flutter.dev website. The [design doc template](https://docs.google.com/document/d/1SFRO8U2toOlAaZ38dsuEU7Wm5fn41wvBCWKiwADqfmw/edit) discusses how, but it's essentially opening a PR to a redirect to the website's [`firebase.json`](https://github.com/flutter/website/blob/main/firebase.json#L220).

**Comment by CoderDake** [comment]
Design doc added to description of the issue :)

**Comment by alestiago** [comment]
@CoderDake I would like to have access to https://github.com/orgs/dart-lang/projects/80. I couldn't find your Discord account to ping you.
