### ISSUE TITLE
Isolate.removeErrorListener causes output from uncaught errors to be suppressed

### ISSUE THREAD

**Issue by abitofevrything** [dart-lang/sdk#53850]
When adding an error listener to an isolate using `Isolate.addErrorListener`, uncaught errors in that isolate do not cause an `Uncaught exception: ...` message to be printed to stderr - this is expected. However, removing listeners using `Isolate.removeErrorListener` does not make uncaught errors start printing the message again.

For example, this program has no output on stderr (or on stdout):
```dart
import 'dart:isolate';

void main() {
  final port = ReceivePort();
  Isolate.current.addErrorListener(port.sendPort);
  Isolate.current.removeErrorListener(port.sendPort);
  port.close();

  throw Exception('Oops!');
}
```
I would expect to see this printed:
```
Unhandled exception:
Exception: Oops!
#0      main (file:///home/abitofevrything/Programming/sdk/sdk/test.dart:9:3)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

The issue is caused by [this line](https://github.com/dart-lang/sdk/blob/main/runtime/vm/isolate.cc#L2315) not accounting for the fact that `listeners` may be non empty but containing only null values (as its size is not decreased when a listener is removed, instead the slot containing the listener is set to null).

**Comment by lrhn** [comment]
Does seem like a bug. I agree that the loop should record whether it finds a non-`Null` entry, rather than assuming that there is one if `Length() > 0`.
