### ISSUE TITLE
State of the linting rule `avoid_unstable_final_fields`

### ISSUE THREAD

**Issue by Leptopoda** [dart-lang/sdk#53852]
On dart.dev the linting rule `avoid_unstable_final_fields` is marked as experimental and unreleased but 
https://github.com/dart-lang/sdk/commit/cdc16e7d3d4cd4cfd62c5834512dc7d4786e92c2#diff-fd5138d1eb285c3d5cbf3d85106baab5896c517ebe071b602518f07108f36f17 marked it as available since `3.1` in the sdk.yaml file.

I think is is falsely documented as such as the rule is not yet available in dart 3.1.4 and the mentioned commit is tagged with `3.3.0` .

I'll happily open a PR if this is indeed an issue.

**Comment by parlough** [comment]
Sorry this was an accident when it landed. It's only available in Dart 3.3.0-dev releases currently.

I opened a fix for the information a few days at https://dart-review.googlesource.com/c/sdk/+/331340.

**Comment by bwilkerson** [comment]
@parlough I just removed the +2 from your CL.

Unless we (the analyzer team) hear of some compelling reason to support this lint we have decided not to do so. Our evaluation is that it does not provide enough value as currently written compared to the maintenance burden we'd be taking on.

**Comment by parlough** [comment]
@bwilkerson That's fine by me, I mostly wanted to fix the incorrect version information to avoid confusion. Will it be removed in the mean time?

**Comment by bwilkerson** [comment]
That's my expectation, yes.
