### ISSUE TITLE
[CP] [vm/ffi] Fix FFI callbacks on iOS 17

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53859]
### Commit(s) to merge

https://github.com/dart-lang/sdk/commit/bd57548de127c0b7570f985d1969e54718474963

### Target

everything

### Prepared changelist for beta/stable

stable: https://dart-review.googlesource.com/c/sdk/+/332430
beta: https://dart-review.googlesource.com/c/sdk/+/332431

### Issue Description

Apple's iOS 17 beta contains a new Secure Page Table Monitor on Bionic A15 and A16 chips (2022-2023 devices) which conflicts with our FFI callback implementation in JIT because we're duplicating RX memory with `vm_remap` which is not signed.

This is not an issue on AOT, because then the source memory is signed.

* https://github.com/flutter/flutter/issues/136980

### What is the fix

Instead of remapping the memory, swap the memory from RX to RW, then copy and then swap back to RX. (This is the logic we use for all other OSes already.)

### Why cherry-pick

Once iOS 17 comes out of beta, Flutter apps using https://pub.dev/packages/drift and https://pub.dev/packages/realm (or any other packages using FFI callbacks) will crash in debug mode.

Release mode is not affected, as it uses AOT.

(We could skip a cherry pick to stable if we think we'll have a new flutter release containing the fix by the time iOS 17 becomes more common or if we're fine pushing developers to dev on the master branch.)

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/136980

### Extra Info

Cherry pick risk should be low, it's a 3 line diff.

cc @mraleph

**Comment by mit-mit** [comment]
Picking SGTM

**Comment by zanderso** [comment]
DBC: CP to Flutter 3.16 beta branch sgtm since it will have some more time to bake before it is promoted to stable, but I'd be worried about a CP to Flutter 3.13 stable since I don't think we have test coverage for this and the patch itself does not appear to have a test.

**Comment by dcharkes** [comment]
> DBC: CP to Flutter 3.16 beta branch sgtm since it will have some more time to bake before it is promoted to stable, but I'd be worried about a CP to Flutter 3.13 stable since I don't think we have test coverage for this and the patch itself does not appear to have a test.

We don't have a test setup for iOS in the Dart repo, so we can't test for iOS.
Each and every test that does a callback would trigger this phone restart.

I'm fine with either of the two options for Flutter developers:

1. Cherry pick to stable
2. Tell developers to upgrade to 3.16

**Comment by mraleph** [comment]
Note that this patch is just reverting iOS to use code path that is used on all other platforms - so it is far from being untested.

**Comment by dcharkes** [comment]
Friendly ping for @vsmenon @itsjustkevin and @athomas.

**Comment by itsjustkevin** [comment]
> I'm fine with either of the two options for Flutter developers:
> 
> 1. Cherry pick to stable
> 2. Tell developers to upgrade to 3.16

I am going to tag this cherry-pick approved for the beta branch with a possible stable coming also.

@dcharkes I don't see a link the the beta or stable cherry-picks, could you post those so we can merge the beta?

**Comment by dcharkes** [comment]
stable: https://dart-review.googlesource.com/c/sdk/+/332430
beta: https://dart-review.googlesource.com/c/sdk/+/332431

**Comment by oelburk** [comment]
Any chance this will be in the official beta release soon? Better yet, the stable release? Thanks guys

**Comment by dcharkes** [comment]
> Any chance this will be in the official beta release soon?

Yes, @itsjustkevin is on it.

> Better yet, the stable release? Thanks guys

I think that's for Kevin to answer.
