### ISSUE TITLE
[analyzer] Failure on inherited combined member signature

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#53865]
The analyzer fails on inherited combined member signature as seen in this test:
```
language/extension_type/inherited_combined_member_signature_test
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
```dart
abstract class A<T> {
  (Object?, dynamic, dynamic) method(T t);
}

abstract class B<T> {
  (dynamic, Object?, dynamic) method(T t);
}

abstract class C<T> implements A<T>, B<T> {}

abstract class D<T> {
  (dynamic, dynamic, Object?) method(T t);
}

abstract class E<T> implements C<T>, D<T> {}

extension type F<T>(C<T> c) implements A<T>, B<T> {}

extension type G<T>(E<T> e) implements F<T>, D<T> {}
```

Ah, interesting.
We check whether a member is an extension type member, or non-extension type member by looking at its enclosing element.
When we combine signatures from `A` and `B`, we set the enclosing element of the result to `F`.
So, it becomes "an extension type member", even it its origins are non-extension type members.
I guess we need a more specific signal to distinguish them.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/332370
