### ISSUE TITLE
Improve server performance by decreasing the number of Analysis context's created

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#53874]
We have seen the analysis server consume large memory such that it is rendered unusable.
 #52447  
 #41793 

Reducing the number of `AnalysisContext`'s creates and used when analyzing user code will result in improvement of performance and memory usage.

Two arcs of work have been identified as a way to reduce the number of contexts

- [ ] support a monorepo workspace, based on changes to pub proposal [#4022](https://github.com/dart-lang/pub/issues/4022)
- [x] #53876
  - [x] move strictCasts bool field out of TypeSystemImpl https://github.com/dart-lang/sdk/issues/53873

**Comment by srawlins** [comment]
Okie doke, P1 issue, any recent updates?

**Comment by pq** [comment]
Context work is waiting for #54858. Maybe @keertip can speak to the monorepo bits?

**Comment by keertip** [comment]
The monorepo work in the analyzer has landed and awaiting the pub work to be done so that it can be tested. Pub work is tracked in [dart-lang/pub/#4127](https://github.com/dart-lang/pub/issues/4127.)

**Comment by bwilkerson** [comment]
Any updates?

**Comment by pq** [comment]
Context work is still in progress. There are some bot failures I'm still trying to reproduce under test (https://github.com/dart-lang/sdk/issues/54858).

**Comment by bwilkerson** [comment]
Any updates?

**Comment by pq** [comment]
We're wating for https://dart-review.googlesource.com/c/sdk/+/362442 to fully make it through a flutter roll before we can turn on multi-option contexts (see https://github.com/dart-lang/sdk/issues/55413).

**Comment by pq** [comment]
https://github.com/dart-lang/sdk/commit/22da6ed1ccc84fa5fb31433ba4465542733195fe flips the bit for multi-option contexts, but we've reverted related changes twice so I think we want to let it bake for a few more days at least before declaring victory.

**Comment by bwilkerson** [comment]
Any progress?

I know that we're waiting for @keertip to test the monorepo support, but I believe the analysis options work is done. Is that correct?

**Comment by pq** [comment]
Yep. I think the analysis options work is done.
