### ISSUE TITLE
Why there is a difference between 'readSync' and 'readIntoSync'

### ISSUE THREAD

**Issue by cgztzero** [dart-lang/sdk#53886]
I have a question,I use RandomAccessFile class and read a file chunk by chunk.
But there is a difference between 'readSync' and 'readIntoSync',

![1](https://github.com/dart-lang/sdk/assets/8406065/6c0af339-7789-418d-9f5f-901783cef6fe)

but the two results are not same

![1](https://github.com/dart-lang/sdk/assets/8406065/48386436-eaaf-486f-afaf-389e91082ac8)

Could anyone answer my question？

**Comment by lrhn** [comment]
Does that change if you set the position back to `uploadStart` before calling `readSync`?
