### ISSUE TITLE
[breaking change] Disambiguate `extension type` to declare an extension type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#53883]
### Change Intent

The Dart grammar currently allows `extension type on (int i,) {}` as a declaration of an `extension` whose name is `type` and whose on-type is a record type.

With the upcoming introduction of extension type declarations, the language team wishes to ensure that it cannot be an `extension`, such that a reader of Dart code can safely assume that a declaration starting with `extension type` will be an `extension type` declaration.

The change proposed here is an adjustment of the grammar such that this goal is achieved. Details here: https://github.com/dart-lang/language/pull/3431.

### Justification

The introduction of extension type declarations creates an ambiguity, and it must be resolved. The language team prefers to ensure that a declaration that starts with `extension type` actually declares an extension type and not a plain extension, because that is considered to be the least surprising choice. Also, the value of being able to have an `extension` whose name is `type` is considered low.

### Impact

Probably very low: It only affects `extension` declarations whose name is `type`, and that choice of name violates the general rule that type-like entities should have a capitalized name.

### Mitigation

Rename the extension named `type` to some other name. This will affect explicitly resolved extension member invocations (where `type` must be replaced by the new name). It is expected to be a very rare phenomenon: Extensions named `type` are presumably very rare, and only few extension member invocations are resolved explicitly: Low probability times low probability is even lower probability.

### Change Timeline

As soon as possible. This ambiguity will have to be handled at some point anyway.

### Associated CLs

None, yet.

**Comment by leafpetersen** [comment]
cc @itsjustkevin @Hixie @vsmenon 

I'd like to expedite review on this since it's on the critical path for release.  This is a small technical breaking change which I don't expect to break anything in practice.

**Comment by vsmenon** [comment]
lgtm

**Comment by grouma** [comment]
SGTM.

**Comment by Hixie** [comment]
i strongly support this

**Comment by eernstg** [comment]
Very good, thanks!

The behavior has been implemented already, so there will not be a separate 'implementation' issue.

**Comment by eernstg** [comment]
@sgrekhov, I believe we also have co19 tests for this topic, right?

**Comment by sgrekhov** [comment]
For extension we have
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-methods/syntax_t05.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-methods/syntax_t06.dart

I'll add this corner case with record type as well
