### ISSUE TITLE
Error sending List<Uint8List> via Isolate.spawnUri 

### ISSUE THREAD

**Issue by nmfisher** [dart-lang/sdk#53890]
Sending a `List<Uint8List>` via `Isolate.spawnUri` throws the error below. Sending the same as `List<List<int>>` succeeds, as does sending a single `Uint8List`.

Reproducible example:
main1.dart
```
import 'dart:isolate';
import 'dart:typed_data';

void main() async {
  await Isolate.spawnUri(Uri.parse('main2.dart'), [], <Uint8List>[
    Uint8List.fromList([1])
  ]);
  await Future.delayed(Duration(seconds: 5));
}
```

main2.dart
```
import 'dart:typed_data';

@pragma('vm:entry-point')
void main(List<String> args, Uint8List message) {
  print(args);
}
```

```
> dart run main1.dart 
Unhandled exception:
Invalid argument: is a Type: Uint8List
#0      Isolate._spawnUri (dart:isolate-patch/isolate_patch.dart:532:25)
#1      Isolate.spawnUri (dart:isolate-patch/isolate_patch.dart:459:7)
#2      main (package:flutter_isolate_example/main1.dart:5:17)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

* Dart version and tooling diagnostic info (`dart info`)
#### General info

- Dart 3.3.0-71.0.dev (dev) (Fri Oct 27 11:31:10 2023 -0700) on "macos_arm64"
- on macos / Version 13.5.1 (Build 22G90)
- locale is en-SG

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                            |
| -----: | ---: | -----------: | --------------------------------------------------------------------------------------- |
|  13 MB | 0.0% |     06:47:35 | dart devtools --machine --try-ports 10 --allow-embedding                                |
|  65 MB | 0.0% |        59:31 | dart devtools --machine --try-ports 10 --allow-embedding                                |
|  49 MB | 0.0% |     01:03:59 | dart devtools --no-launch-browser                                                       |
|  23 MB | 0.0% |     06:47:35 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.74.0         |
|  95 MB | 0.0% |     05:12:17 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.74.0         |
| 841 MB | 0.0% |        59:31 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.74.0         |
|  62 MB | 0.4% |     05:12:17 | flutter_tools.snapshot daemon                                                           |
| 102 MB | 0.4% |        59:31 | flutter_tools.snapshot daemon                                                           |
|  91 MB | 0.0% |     01:04:12 | flutter_tools.snapshot debug_adapter                                                    |
| 319 MB | 0.1% |     01:04:12 | flutter_tools.snapshot run --machine --start-paused -d chrome --target <path>/main.dart |
* Whether you are using Windows, macOS, or Linux (if applicable)
macOS
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A

**Comment by lrhn** [comment]
Working at currently intended.

The only objects you can send to an isolate in another isolate group, including when starting them, are JSON-like structures of pain lists, plain string-keyed maps, "primitive" values, plus send ports and capabilities.

Typed data lists are not included. They can only be sent to isolates in the same isolate group.

**Comment by nmfisher** [comment]
Should Uint8List be sendable then?

**Comment by mraleph** [comment]
@nmfisher as @lrhn said: `Uint8List` is not currently sendable between isolate groups. You can do `TransferableTypedData([uint8List])` if you want to send it.  

I am not entirely sure why the restriction is there though... All type-data classes are entry-points anyway so we can't tree-shake them, so they should be present in all isolate groups @mkustermann @aam?

**Comment by nmfisher** [comment]
@mraleph thanks, but I think I wasn't very clear with my response. It seems it *is* possible to send a `Uint8List` between isolate groups:

main1.dart
```
import 'dart:isolate';
import 'dart:typed_data';

void main() async {
  await Isolate.spawnUri(Uri.parse('main2.dart'), [], Uint8List.fromList([1]));
  await Future.delayed(Duration(seconds: 5));
}
```

main2.dart
```
import 'dart:typed_data';

@pragma('vm:entry-point')
void main(List<String> args, Uint8List message) {
  print(message);
}
```

```
> dart run main1.dart
[1]
```

But sending a `List<Uint8List>` fails. What I meant by my response was that "if it's expected behaviour that I can't send a List<Uint8List>, then shouldn't sending a Uint8List also fail?"

**Comment by mraleph** [comment]
@nmfisher Thanks for clarifying. Yeah, we need to probably fix the check to allow typed data types to be sent across the boundary and update the documenation. 

However there is also an argument to update restriction the other way - though it will be too breaking (I think). 

@mkustermann will make a call

**Comment by mkustermann** [comment]
We may be able to debate whether sending typed data classes is a good idea (thereby preventing those classes from being tree shaken in AOT), but if we can already send typed data objects, I think it would be too breaking to remove this capability.

So I'd suggest we change our verification to allow typed data classes in type arguments, such as `List<Uint8List>` in the example above.

@aam Would you like to implement this?
