### ISSUE TITLE
DWARF stack traces and deferred units

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#53902]
Current implementation of DWARF stack traces does not take deferred units into account. 

* Stack format needs to print build-id per frame or print build-id + PC range 
* Tooling (`package:native_stack_traces`) needs to accept multiple symbol files.

There might be more integration work necessary for services like Crashlytics and Sentry. 

/cc @mkustermann @sstrickl

**Comment by mkustermann** [comment]
Assigning to @sstrickl as she worked on this area before

**Comment by a-siva** [comment]
@sstrickl would it be possible for you to publish a new version of 
`pkg/native_stack_traces `so that Flutter can pick it up and see if it resolved the issue they were encountering in https://github.com/flutter/flutter/issues/137527

**Comment by sstrickl** [comment]
Thanks for the reminder. Done!

**Comment by mkustermann** [comment]
@sstrickl Could you also roll this into flutter/flutter and do any needed changes?

**Comment by sstrickl** [comment]
Yep, I'll see about making an appropriate pull request today.
