### ISSUE TITLE
dart:io File.openRead when File does not exist does not throw

### ISSUE THREAD

**Issue by jakobleck** [dart-lang/sdk#53904]
```
import 'dart:io';

void main() async {
  File file = File("test_file.txt");
  print("a");
  final stream = file.openRead();
  print("b");
  await for (var chunk in stream) {
    print("chunk: $chunk");
  }
  print("c");
}

```
(for a file that does not exist) yields the output
```
a
b
Unhandled exception:
FileSystemException: Cannot open file, path = 'test_file.txt' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
#1      _FileStream._start.onOpenFile (dart:io/file_impl.dart:125:5)
<asynchronous suspension>

```
i.e. the exception is not thrown on the `openRead` call, but at the `await for`.

Is there a particular reason for this behaviour? Not an issue, just a question. I find it suprising that the native code fails to open a file not when I "open"Read a file, but when I start using the result.

**Comment by brianquinlan** [comment]
`openRead` is non-blocking; it does not actually open the file before returning the `Stream`. When the file fails to open then the error will be added to the `Stream`.

I'll will clarify that behavior in the documentation.

**Comment by a-siva** [comment]
@brianquinlan has the documentation been updated ? Can we close this if so,
