### ISSUE TITLE
Format exception: Invalid HTTP header field value

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/sdk#53914]
```
dart --version
Dart SDK version: 3.1.4 (stable) (Tue Oct 17 14:55:53 2023 +0000) on "macos_arm64"
```

When running this code

```dart
void main() {
  final city = 'Bogotá';

  final client = HttpClient();
  client
      .getUrl(Uri.parse('http://localhost:3000'))
      .then((req) {
        req.headers.add('x-city', city);
        return req.close();
      })
      .then((res) => res.pipe(stdout))
      .catchError((e) => stderr.writeln(e));
}
```

I get the following error:

```
FormatException: Invalid HTTP header field value: "Bogotá" (at character 6)
Bogotá
```

I can encode the value with `Uri.encodeComponent` before adding the header, and decode it back on receiving end, but I'm curious if this is a dart bug or an http spec requirement.

**Comment by lrhn** [comment]
The syntax of HTTP header [field values](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.5) is somewhat permissive, but does not define any *encoding*, so non-ASCII (or at least non-ISO-8859-1) characters are not supported.

You must do the encoding yourself, somehow, and make the result be a simple string with no code unit above 255, then it can be sent. Then you can decode it yourself at the other end.


Also, see https://datatracker.ietf.org/doc/html/rfc6648

**Comment by brianquinlan** [comment]
One relevant section is:

Specifications for newly defined fields SHOULD limit their values to visible US-ASCII octets (VCHAR), SP, and HTAB. A recipient SHOULD treat other allowed octets in field content (i.e., [obs-text](https://www.rfc-editor.org/rfc/rfc9110.html#fields.values)) as opaque data.

I'm going to close this, please reopen if you disagree with the conclusion that it is the users responsibility to encode the header fields if they want to transmit non-VCHAR data.
