### ISSUE TITLE
[analyzer] Assigned final fields in const classes are incorrectly considered to be const

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#53927]
If a final field is assigned in its declaration (not in a generative constructor) in a class with a constant constructor, constant evaluation incorrectly allows it to be used as a constant.

```dart
class Test {
  final String fakeConst = '';
  
  const Test();
  
  List<String> te() => const [fakeConst];
                          /// ^^^^^^^^^ No error, but expect non_constant_list_element
}
```

CFE correctly identifies it as not a constant expression.

Doesn't affect 3.1 stable. Affects 3.2-`beta`, 3.3-`dev`, and BE(8b3d93234d1df69c3db5428fa02bb6b39c671ed8). Consider fix for cherry pick to 3.2 beta if it's simple enough since it's a regression and I think this is a case developers could hit :)

**Comment by parlough** [comment]
\cc @kallentu

**Comment by parlough** [comment]
Thanks for the fix @kallentu :)

**Comment by kallentu** [comment]
NP! Thanks for surfacing this, Parker :D
