### ISSUE TITLE
[Extension types] Analyzer reports incorrect "const eval throws" for extension constructor.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#53935]
Example:
```dart
extension type const Num(num value) {
  const Num.add(Num v1, Num v2) : this((v1 as num) + (v2 as num));
  const Num.sub(Num v1, Num v2) : this((v1 as num) - (v2 as num));
  const Num.mul(Num v1, Num v2) : this((v1 as num) * (v2 as num));
  //                                    ^^^^^^^^^
}

void main() {
  const n = Num.sub(Num.mul(Num(7), Num(7)), Num(7));
  print(n.value);
}
```
The CFE (VM) prints `42` as expected, with nothing throwing.

The analyzer reports:
```
  error - const-eval.dart:4:41 - Evaluation of this constant expression
          throws an exception. - const_eval_throws_exception
```
The marked position is what is shown in dartpad.dev, which is at the `v1 as num` cast of `mul`.

That is the first cast to be reached in the computation, so most likely the analyzer's constant evaluator doesn't recognize that an expression with runtime value `7` and static type `Num` can be safely cast to `num`.

(I use `as num` instead of `._` because the former is a potentially constant expression, and the latter is not. Either should be no-ops at runtime, but only one is allowed in a `const` constructor.

**Comment by bwilkerson** [comment]
@kallentu

**Comment by kallentu** [comment]
I don't think any additional support has been added to the const evaluator to handle extension types.
@scheglov Are you going to be working on this at some point? I'm not sure where the feature last ended off.

**Comment by scheglov** [comment]
Honestly, I hoped that you will implement this portion, given your new experience with constant evaluation.

**Comment by scheglov** [comment]
Clarification for https://github.com/dart-lang/sdk/issues/53935#issuecomment-1791103748.
I did not try to be rude or something.

Here is the translation of what I wanted to say through an LLM.

I'm currently occupied with other commitments, but I'm eager to get this task completed. I understand that @kallentu has experience with constant evaluation, and I would greatly appreciate their assistance if they are available. If @kallentu is unable to contribute, I'm fully prepared to take on the responsibility. Additionally, if anyone else is interested in helping, I'm open to their involvement and would be grateful for their support.

**Comment by kallentu** [comment]
@scheglov No problem! I don't think I have the capacity to complete the fix for this, unfortunately. If you or someone else could take this, that would be great.

I did have a quick glance at what the issue might be though and it's in `DartObjectImpl.castToType` which calls `typeSystem.isSubtypeOf` and the subtyping algorithm doesn't handle the difference between the extension type `Num` and `num` in this case. Perhaps an update is needed there.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/334862
