### ISSUE TITLE
[analyzer][Extension types] No error if the name of an extension type is a built-in identifier

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53930]
The following test works in CFE but fails in analyzer
```dart
// SharedOptions=--enable-experiment=inline-class

extension type abstract(int id) {} // No expected error in analyzer
//             ^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
```

Tested on `Dart SDK version: 3.3.0-edge.27a2c2e461e11a43ae1a6b2f1403e7c64f03940f (be) (Wed Nov 1 22:57:09 2023 +0000) on "macos_x64"`

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/333600
