### ISSUE TITLE
Method to return a sublist slice of an arbitrary Iterable

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#53937]
I would like something like the following method:
```dart
List<E> sublistOfIterable<E>(Iterable<E> iterable, int start, {int? end, bool growable = false}]) {
  ???
}
```
The method produces the same result and range errors as
```dart
iterable.toList().sublist(start, end).toList(growable: growable)
```
except  (1) it does not call `Iterator.current` on any element outside the _`[start, end)`_ range, (2) does not call `Iterator.current` more than once on any element, and (3) avoids unnecessary allocations.

It is quite challenging to extract a properly checked _`[start, end)`_ sublist of a lazy `Iterable`.
Naive approaches based on `iterable.skip(start).take(end - start)` fail to distinguish edge cases.
See https://github.com/dart-lang/sdk/issues/50253#issuecomment-1287882913.

I would suggest this for `package:collection` except that I want to use it in the SDK for solving #50253.

/cc @natebosch

**Comment by natebosch** [comment]
cc @lrhn

**Comment by lrhn** [comment]
Why?

More precisely: why start with an `Iterable`, where you are not supposed to know the length, and still use a method which gives errors if you guess the length wrong?
That's an unsafe combination of operations, which means it's a bad design for a single operation.

Why _not_ return an empty or truncated list of the star/end are beyond the available values?

Or a composite result of the available values and the index of them last seen value, which is at or below `end`.

**Comment by rakudrama** [comment]
> I wouldn't start with an `Iterable`, where you are not supposed to know the length, and use a method which gives errors if you guess the length wrong. That's an unsafe combination of operations, which means it's a bad design for a single operation.

This 'bad design' _is_ the design of `String.fromCharCodes`.

I think that there is some path dependence in the bad design - the slice arguments were added later. If the slice arguments were in the initial signature, I suspect `codePoints` would have been a `List`, and we would not be having this discussion.

So I understand not wanting to have this sublist-of-Iterable operation to discourage similar signatures. But it does mean we have to be very inventive where we have the bad design, and each place will have complex and possibly buggy code.
At least the code in the dart: libraries has access to EfficientLengthIterable.

> 
> I'd rather just return an empty or truncated list of the start/end are beyond the available values.
> 
> Or a composite result of the available values and the index of them last seen value, which is at or below `end`. But probably just the empty result.
> 
> If there is a use-case which repaired the throwing, I'd look to change that instead. 

I'm not sure I understand what is meant by 'repaired the throwing'.

> For the `fromCharCodes`, just let it accept too large start and end, like a proper `Iterable` processor.

The documentation says "The start and end values must satisfy `0 <= start <= end <= charCodes.length`.".
Generally the core library validates such requirements. The validation is part of the tests, and in this case, there are corelib tests that the validation occurs that will fail with skip/take slice.

**Comment by lrhn** [comment]
"required". Damn mobile keyboards.

And yes, I suggest just changing the behavior of `fromCharCodes`. Being not permissive it's not a breaking change.

**Comment by natebosch** [comment]
+1 to changing the other API to be more permissive over adding another restrictive API to match.
