### ISSUE TITLE
`dart compile exe` from `.dill` (kernel)  files

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/sdk#53971]
Today, when we try to use `dart compile exe bin/foo.dill`, it doesn't work (on macOS, it consumes memory until it crashes).

It would be great to have the ability to compile to a self-contained native executable from the `.dill` file since this already accounts for about 50% of the process.

**Comment by mraleph** [comment]
Could you elaborate why you want this? Where are you going to get `dill` file from? You still need to recompile this `dill` whenever your source changes.

It is possible to implement this - it is just unclear what value it provides. 

[This was previously asked https://github.com/dart-lang/sdk/issues/41046]

**Comment by gmpassos** [comment]
I can compile to .dill, then compile to native for each target os (macOS, windows, Linux), reducing CI time.

**Comment by ykmnkmi** [comment]
Dart has a incremental compiler now. Why not use it here?

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by gmpassos** [comment]
Any update?

**Comment by bkonyi** [comment]
No updates yet. I might be able to pick this up in the next week or two, but I'm not sure how much work this will be without taking a closer look.

**Comment by mkustermann** [comment]
> I can compile to .dill, then compile to native for each target os (macOS, windows, Linux), reducing CI/build time.

This isn't really something you should do: We have 2 different kinds of kernel files:

  * Those that can run on the Dart VM JIT: They are simple kernel AST representation of the input program, they are target-OS independent, they haven't gone through global analysis, haven't been tree shaken.
  
  * Those that can be compiled via Dart VM's AOT compiler: They went through global analysis, are tree shaken, are target-OS specific, are annotated with global analysis results (which allow the VM's AOT compiler to unbox parameters, emit devirtualized calls, ...)

So even after @bkonyi 's https://github.com/dart-lang/sdk/commit/5a386442951ba931c8f575ea70b16c0c7f0db2ea, the actual executables you get out of

```
% dart compile app.dart
% dart compile exe app.dill
```
aren't really optimized - they may be significantly bigger & run significantly slower than using the `dart compile exe app.dart`.


Right now `dart compile kernel` is producing a kernel file that's intended to run on the Dart VM JIT, not compiled with our AOT compiler. We may in the future be in a situation where our AOT compiler relies on certain information in the AOT-ready kernel that the JIT kernel doesn't have (or vice versa: The JIT may require things in a kernel that a AOT-ready kernel doesn't have).

**Comment by mkustermann** [comment]
(Never mind my message (deleted now): It compiles to JIT kernel and then optimizes that to AOT kernel and then AOT compiles it)
