### ISSUE TITLE
[CP] DevTools 2.28.2 Hotfix

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#53979]
### Commit(s) to merge

The requested change (https://dart-review.googlesource.com/c/sdk/+/334580) to cherry pick is not merged yet. It cannot be merged on the SDK master branch because we don't want to downgrade the devtools version on SDK master (and we wouldn't be able to anyway because of some version constraint issues).

### Target

beta (targeting the upcoming November stable release)

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/334580

### Issue Description

To detect DevTools extensions for a Dart or Flutter application connected to DevTools, we need to look up a connected app's root library and send that information to the DevTools server. We are using this information to detect where a project's `.dart_tool/package_config.json` file is.

We were determining a connected app's root path by assuming that the root library for the main isolate would include `lib/`. This is true for a dart entry point at  `lib/main.dart`, but it false for an entry point under `test`, `integration_test`, or `bin`. So for any connected application with a dart entry point that lives outside of `lib/main.dart`, we were incorrectly showing no extensions available.

### What is the fix

This PR modifies the RegExp used in DevTools to include other targets within a project (`test`, `integration_test`, and `bin`)

### Why cherry-pick

The DevTools extension author who submitted this fix will not be able to publish their extension unless this cherry-pick goes through. This will delay them shipping their extension until the next flutter stable. This author will not be the only user affected, but was just the first to notice this bug while testing out the DevTools extensions support in beta.

Since this upcoming Flutter stable release will be the first that includes DevTools extension support altogether, it would also be ideal to not release with this bug that limits the type of debugging tools DevTools extensions authors can provide.

### Risk

low

### Issue link(s)

https://github.com/flutter/devtools/pull/6644

### Extra Info

Filed a CP issue on flutter/flutter too: https://github.com/flutter/flutter/issues/138003.

I am not sure how to push this DevTools cherry-pick through, so I'll be very descriptive here and hopefully can get some guidance from the Flutter / Dart SDK rollers.

The issue in DevTools was fixed by https://github.com/flutter/devtools/pull/6644.

The current DevTools version set to go into the November Dart / Flutter stable release is 2.28.1. I created a branch on the `flutter/devtools` repo [2.28.2](https://github.com/flutter/devtools/commits/2.28.2). This branch is created from 2.28.1 and cherry picks the fix from https://github.com/flutter/devtools/pull/6644 as well as bumps the version to 2.28.2 (see [diff](https://github.com/flutter/devtools/compare/v2.28.1...2.28.2)).

The Dart SDK CL here (https://dart-review.googlesource.com/c/sdk/+/334580) updates the "devtools_rev" hash in the SDK DEPS file to `8db42fc4a0b7a4ca180ba73fc387b81b0927e8a0`, which is the tip of flutter/devtools @ branch 2.28.2. However, this hash does not correspond to a devtools build in CIPD because the [DevTools LUCI builder](https://ci.chromium.org/ui/p/dart-internal/builders/flutter/devtools) only uploads DevTools builds to CIPD for commits to `flutter/devtools` @ `master`. @sortie 

A lot has changed with the DevTools release process since we last had to do a cherry pick, so I will document the DevTools cherry-pick process for DevTools with the recommended steps once we outline them here. Thanks.

**Comment by sortie** [comment]
@kenzieschmoll I already planned for the cherry-pick case and the procedure is documented at go/dart-engprod/devtools.md which should already be in your documentation :)

**Comment by kenzieschmoll** [comment]
The instructions at https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel#cherry-picking-a-commit-in-a-dependency do not seem to directly apply to DevTools. I am up to the point now where I have a branch that has been mirrored to dart.googlesource.com: https://dart.googlesource.com/external/github.com/flutter/devtools/+/refs/heads/2.28.2. 

From [go/dart-engprod/devtools.md](go/dart-engprod/devtools.md), I am unclear what it means to "Follow the [cherry picking a commit in a dependency](https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel#cherry-picking-a-commit-in-a-dependency) instructions to author the cherry-pick commit in the devtools repository and merge it back to master." 

As of right now, I have a branch that has been mirrored to dart.googlesource.com: https://dart.googlesource.com/external/github.com/flutter/devtools/+/refs/heads/2.28.2. The commit at the tip of this branch is what I want to change the "devtools_rev" hash to in the DEPS file (this [CL](https://dart-review.googlesource.com/c/sdk/+/334580))

What is the next step after this? Or am I already in an unrecoverable state?

**Comment by itsjustkevin** [comment]
@jacob314 can you take a look at this cherry-pick request?

CC: @christopherfujino

**Comment by christopherfujino** [comment]
> CC: @christopherfujino

LGTM fwiw :)

**Comment by kenzieschmoll** [comment]
Rebuild of stable is complete: https://dart-review.googlesource.com/c/sdk/+/335022.
