### ISSUE TITLE
[ffi] Mocking FFI implementation when testing code using native assets

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53980]
When using the native assets feature and `@Native external` functions, one might want to mock their C implementation.

We can pursue multiple approaches.

### 1. Wrap FFI use in a Dart class that is mockable (currently possible)

Pros:

* Mocks are written in Dart, this is easy to debug.

Cons:

* Mocks are not crossing the FFI boundary, so any errors in the FFI layer are not caught

The native code should have its own unit tests written in the native code.

And integration tests should use the real native code.

### 2. Single native mock implementation

We could add a define `TESTING` or `USE_MOCKS` to the `build.dart` invocation when running for `dart test` / `flutter test`.

Pros:

* Tests the FFI layer

Cons:

* Single dylib that is the same for all tests. That is usually not what is needed in tests.
  * One way to achieve that would be to have the dylib have a bunch of function pointers that can be populated by callbacks into Dart with `Pointer.fromFunction`. But this would only work for non-async tests, and tests need to be prevented from running concurrently.

### 3. Native mock implementation per test

We could consider somehow supporting compiling different C code _per_ dart test.

This would require invoking a C build for every test and separate kernel compilation for every test though. So this would be a rather invasive solution.

cc @craiglabenz

I'm inclined to say that option 1 should be the go to for now.

The FFI layer should be correct by construction when using `package:ffigen` (famous last words)

Maybe @mraleph or @mkustermann have seen testing patterns in the context of code using FFI before.

**Comment by mkustermann** [comment]
IMHO it's our job to make sure that the bindings are correct, so we shouldn't aim for testing the bindings.

Being able to mock the `external` methods (to simulate what the actual native code would do) doesn't seem very appealing in any way (the mock would need to deal with `Handle` / `Pointer` objects - possibly do C allocations / etc).

Users will make abstractions over the FFI bindings and those abstractions don't have to deal with low-level FFI types and can be made mockable by users.

If users want to test that the abstractions themselves (and their FFI-based implementations) are working, they should write a test that exercises them, including the real native code (can be without UI).

So I imagine e.g. if we have a `package:sqlite` that includes the native `sqlite3` library, that package have tests in the `test/` directory.
=> So we should ensure that `dart test` / `flutter test` / `package:test` work correctly with native assets (i.e. native assets get built, loaded at runtime & symbols get resolved).

**Comment by dcharkes** [comment]
> IMHO it's our job to make sure that the bindings are correct, so we shouldn't aim for testing the bindings.

➕ ➕ 

> => So we should ensure that `dart test` / `flutter test` / `package:test` work correctly with native assets (i.e. native assets get built, loaded at runtime & symbols get resolved).

They do, integration tests using the actual dylib work.

> Users will make abstractions over the FFI bindings and those abstractions don't have to deal with low-level FFI types and can be made mockable by users.

➕ ➕ 

@craiglabenz was saying that MediaPipe loads a 40 MB model and engine for every test. So writing every test as an integration test that runs the actual native code might be too heavy weight. So for those cases I suggested wrapping the native code in a Dart class that can be mocked. That way all Dart abstractions written on top of the native code can be unit tested without running the native code.

**Comment by mkustermann** [comment]
> @craiglabenz was saying that MediaPipe loads a 40 MB model and engine for every test. So writing every test as an integration test that runs the actual native code might be too heavy weight.

The `package:test` exposes `setUpAll()` that will run before executing all tests and `tearDownAll` that will run after all tests are done. So I'd recommend using that for heavy-weight things, so it's not performed for every individual test.

If the tests do need a fresh MediaPipe / model / engine, then well it has to do that - or mock the abstraction as @dcharkes points out.

**Comment by dcharkes** [comment]
> The `package:test` exposes `setUpAll()` that will run before executing all tests and `tearDownAll` that will run after all tests are done. So I'd recommend using that for heavy-weight things, so it's not performed for every individual test.

Heh, I was saying the same in the chat. I guess I should have pasted the whole chat here. 😄 

I think we can close this issue as not planned.

**Comment by craiglabenz** [comment]
Thanks for the discussion. I do think it should be possible to fully handle this without adding this feature :)
