### ISSUE TITLE
LinterContext fields analysisOptions and declaredVariables can be made private.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#53983]
These do not appear to be used outside of the file in which LinterContext is declared, so they can be removed or made private.

Any objections?

CC @pq @bwilkerson

**Comment by bwilkerson** [comment]
@incendial @rrousselGit In case either of you are using these getters or know anyone who is.

**Comment by incendial** [comment]
I think `LinterContext` is not available to the plugins. But if I'm wrong, then I definitely never used it.

**Comment by bwilkerson** [comment]
Oh, you're right. It looks like all of the support we have for the `linter` package is in `lib/src`. I'd thought we'd made some of it public.

In which case we ought to be able to make any changes we want without impacting anyone. Thanks!

**Comment by srawlins** [comment]
Closed in 7629e1e669d0309c35c9e568d1758bd495b67de8
