### ISSUE TITLE
[dart2js] Minify enum names please.

### ISSUE THREAD

**Issue by hamsbrar** [dart-lang/sdk#53988]
```dart
enum E {
  descriptiveName1,
  descriptiveName2,
  descriptiveName3,
}

void main() {
  for (var e in E.values) {
    print(e.index);
  }
}

```
Output of `dart js compile -O4` contains:

```js
B.b=new A.r(0,"descriptiveName1")
B.c=new A.r(1,"descriptiveName2")
B.d=new A.r(2,"descriptiveName3")
//             ^^^^^^^^^^^^^^^^ these ones
// ...

r:function r(a,b){this.a=a
this.b=b},

// main()
bX(){for(var t=0;t<3;++t)A.bZ(""+B.i[t].a)},
```
```sh
> dart --version
Dart SDK version: 3.1.5 (stable) (Tue Oct 24 04:57:17 2023 +0000) on "linux_x64"
```
Same on the newest dev release(`3.3.0-84.0.dev (dev) (Tue Oct 31 17:06:17 2023 -0700)`).
___
Also, not using `Enum.name` anywhere but it's part of the output, appears to be required by `toString`: 
```js
// non-minfied output:

B.E_0 = new A.E(0, "descriptiveName1");
B.E_1 = new A.E(1, "descriptiveName2");
B.E_2 = new A.E(2, "descriptiveName3");
B.List_q2S = makeConstList([B.E_0, B.E_1, B.E_2]);

// ...

E: function E(t0, t1) {
  this.index = t0;
  this._name = t1;
},

A._Enum.prototype = {
  toString$0(_) {
    return this._enumToString$0();
  }
};

A.E.prototype = {
  _enumToString$0() {
    return "E." + this._name;
  }
};
```

**Comment by lrhn** [comment]
The name is required by `toString`, stated explicitly on the language specification, and `toString` is notoriously hard to tree shake.

**Comment by rakudrama** [comment]
> Can't I just nuke `T.toString` when `T.toString` is not in-use and there's no upcast?

Unfortunately, `.toString()` is called from many places that can accept anything, for example, [`Iterable.join`](https://api.flutter.dev/flutter/dart-core/Iterable/join.html) and [`StringBuffer.write`](https://api.flutter.dev/flutter/dart-core/StringBuffer/write.html).

It is essentially impossible to efficiently prove that the enum values do not pass to those places. The kind of query 'does X definitely not flow here' generally amounts to 'find all the things that flow here and see that X is not included'. If we have a concise summary for 'all the things', e.g. 'an `Object`' or 'an `Enum`', then X is included and the test fails to remove X. If we make a precise summary, it is huge, and its computation and representation are generally superlinear in the size of the program. It just doesn't work for real-world applications. Other ways of answering that kind of query are also expensive.

> 
> Like using `E1.descriptiveName.index` forces compiler to preserve `E2.descriptiveName.index` as well while it should've stripped both `Enum.index` and `E2.descriptiveName.index` of. Probably trying that already or probably doesn't worth the effort(for fields) or probably that's not how it's done(for fields/methods).

A further complication is that the base class of enums, `_Enum`, is where the fields reside.
All it takes is for one enum to need the `index` or `_name`, and they all get it.
So it is really an illusion that `index` can be removed in a real program.

> The name seems to be there for debugging purpose. Specification doesn't seem to have any notion of production mode so I'm left with minification as the only option that compiler currently isn't doing.

Changing the name would change the result of [`Enum.compareByName`](https://api.dart.dev/stable/3.1.5/dart-core/Enum/compareByName.html). This is not something that a compiler should do by itself.

The best I can come up with is to rename your enum values, and use the 'enhanced enum' feature to add back the descriptive names in the enum scope, something like:
```dart
enum E {
  _0,
  _1,
  _2;
  static const descriptiveName1 = _0;
  static const descriptiveName2 = _1;
  static const descriptiveName3 = _2;
}
```

**Comment by sigmundch** [comment]
Thanks for the engaging discussion, I hope the answers above provide a bit more clarity into the complexity of this issue! I'm just marking this as "closed as not planned" based on the explanations above.

**Comment by sigmundch** [comment]
Thanks for clarifying, I missed that detail.

**Comment by rakudrama** [comment]
@hamsbrar Can you say more about the impact of the enum names on your application? Does it prevent you from shipping an application? Does it increase the size by X% where X% clearly a significant overhead? Is there some other negative impact?

**Comment by rakudrama** [comment]
> I'm not bothered by the other 97-99%. There definitely are places where I could've done better, like way better than what I actually did. Sometime I just fail not to make stupid mistakes and then things stop being worthy of any effort. But this 1-3% are the characters that no-one on this planet need and compiler knows that.

The compiler _doesn't_ know that because some developers _do_ need the name.

We can't minify the name. Developers have come to expect the current behaviour of `Enum.toString`, and the name is also available to general code [via `.name`](https://github.com/dart-lang/sdk/blob/69cf1dfa5c8be85c0cc2341e9971673241db31f2/sdk/lib/core/enum.dart#L136).
There before we added `.name`, we would see folks doing `enumValue.toString().split('.').last`.

**Comment by sigmundch** [comment]
Thanks @hamsbrar for the additional discussion and sharing the numbers. Marking it now as closed :)
