### ISSUE TITLE
`dart analyze` yields different results on macos and linux

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#53992]
Here is an example run on linux that produces warnings:
https://github.com/flutter/devtools/actions/runs/6803035154/job/18497485917?pr=6673

Running `dart analyze` on macos does not show any warnings: https://github.com/flutter/devtools/actions/runs/6803718135/job/18499691597?pr=6676

I have reproduced this locally as well 

```
Flutter and Dart SDK versions:
 > /Users/kenzieschmoll/develop/flutter/bin/flutter --version
Flutter 3.17.0-3.0.pre • channel [user-branch] • unknown source
Framework • revision 5ff09c27f8 (35 hours ago) • 2023-11-07 03:35:26 -0500
Engine • revision 99149d59cb
Tools • Dart 3.3.0 (build 3.3.0-102.0.dev) • DevTools 2.30.0-dev.1
 > dart --version
Dart SDK version: 3.3.0-102.0.dev (dev) (Mon Nov 6 20:04:51 2023 -0800) on "macos_x64"
```

**Comment by srawlins** [comment]
The CI jobs in the two logs pasted use two different versions as well:

* https://github.com/flutter/devtools/actions/runs/6803035154/job/18497485917?pr=6673 (linux) says "flutter-sdk-Linux-refs/tags/3.17.0-3.0.pre"
* https://github.com/flutter/devtools/actions/runs/6803718135/job/18499691597?pr=6676 (macos) says "flutter-sdk-macOS-refs/tags/3.17.0-4.0.pre"

It is interesting that you reproduce the _macos_ state (no warnings) locally with "Flutter 3.17.0-3.0.pre". 😦

**Comment by kenzieschmoll** [comment]
Oh yep looks like a version bump snuck into the run I linked. I did repro this locally with `Flutter 3.17.0-3.0.pre` on both linux and mac

**Comment by srawlins** [comment]
Are these logs from presubmit CI runs? I'd like to see the PRs; we need to see what the language version is in all of those files.

**Comment by kenzieschmoll** [comment]
Yep they are from CI runs on PRs
linux: https://github.com/flutter/devtools/pull/6673
macos: https://github.com/flutter/devtools/pull/6676

**Comment by kenzieschmoll** [comment]
With new flutter version, the analysis errors matched what I saw on linux with `Flutter 3.17.0-3.0.pre`: https://github.com/flutter/devtools/pull/6694

**Comment by srawlins** [comment]
Is this solved then? Some transient problem that is cleared now?

**Comment by kenzieschmoll** [comment]
Yeah we can probably close this. It should repro on Flutter 3.17.0-3.0.pre, but went away with Flutter 3.17.0-4.0.pre, so not sure it's worth investigating.
