### ISSUE TITLE
Syntax(?) to reload closure on hot reload

### ISSUE THREAD

**Issue by AlexanderFarkas** [dart-lang/sdk#53998]
Hot-reloading after changing body of the function is not "reloading" the function, since the code is not rerun.

```dart
class CounterViewModel extends ViewModel {
  late final counter = state(0);
  late final doubledCounter = computed((watch) => watch(counter) * 2);
}
```

If I change body of the lambda to:
```dart
(watch) => watch(counter) * 3
```
It has no effect until program is hot restarted. Related [issue](https://github.com/flutter/flutter/issues/59899)

Is that possible to add some `annotation` or syntax to instruct VM how to reload the closure? 
E.g.
```dart
class Computed<T> {
  @pragma("vm:closure-recapture")
  final T Function(Watch watch) computed;
  // ...
}
```

Which clears captured variables and takes them from a new function.

I believe, [`riverpod`](https://pub.dev/packages/riverpod) used by lots of people will benefit from that.

**Comment by mraleph** [comment]
For the context: https://github.com/flutter/flutter/issues/59899#issuecomment-647424702 outlines why reloading closures is complicated. It is not _impossible_ to support this specific case (e.g. marker function call, no change in captured variables), but then we end up in a situation where some closures are reloaded and some are not reloaded - which might be even more cryptic.

Consider for example that you reload this:

```dart
void foo(void Function() f) {
  o.onClick = f;
}

void bar() {
  foo(() { print("clicked") });
}
```

with this:

```dart
void foo(void Function() f) {
  o.onScroll = f;
}

void bar() {
  foo(() { print("scrolled") });
}
```

Here there is a single closure in the scope, captures don't change... but just replacing the body of previous version of closure (one that prints `clicked`) with `print("scrolled")` is going to be wrong.

**Comment by AlexanderFarkas** [comment]
Consider this example with method declarations instead of closures.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const _App());
}

class _App extends StatefulWidget {
  const _App({super.key});

  @override
  State<_App> createState() => _AppState();
}

class _AppState extends State<_App> {
  final scrollController = ScrollController();
  final textEditingController = TextEditingController();

  @override
  void initState() {
    scrollController.addListener(printInfo);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(
          controller: scrollController,
          children: [
            TextField(controller: textEditingController),
            for (var i = 0; i < 10; i++)
              Placeholder(
                fallbackHeight: 200,
              )
          ],
        ),
      ),
    );
  }

  void printInfo() {
    print('Scrolled');
  }
}
```

If I change:
```dart 
scrollController.addListener(printInfo);
// ...
print('Scrolled');
```
to:
```dart
textEditingController.addListener(printInfo);
// ...
print('Typed');
```

It starts printing "Typed" on scroll, which is also confusing.

**Comment by AlexanderFarkas** [comment]
> but then we end up in a situation where some closures are reloaded and some are not reloaded - which might be even more cryptic.

I can't speak for all, but as a user of Flutter, absence of hot reloading in closures were unknown to me until I started developing my own library relying on closures. 

I used to not associate absence of hot reloading to usage of closures. So I just considered it a periodically occurring bug.
So **presence** of **some** hot-reloading would really enhance my Developer Experience.

**Comment by AlexanderFarkas** [comment]
@mraleph 
If closure doesn't capture mutable references (or captures them as immutable), might it be promoted to a function declaration during compile time? 

I understand that task might be much more complex, but still.

**Comment by mraleph** [comment]
> Consider this example with method declarations instead of closures.

This is true, but you made this example intentionally obtuse for the sake of argument. Usually the method would have a more specific name, rather than `printInfo`:

```
scrollController.addListener(onScroll);
// ...
print('Scrolled');
```

to

```
textEditingController.addListener(onTextEdit);
// ...
print('Typed');
```

And the problem will not occur. 

> I can't speak for all, but as a user of Flutter, absence of hot reloading in closures was unknown to me until I started developing my own library relying on closures.

FWIW hot-reload philosophy, capabilities and limitations are extensively [documented](https://github.com/dart-lang/sdk/wiki/Hot-reload). It's worth reading that page if you want to know what hot-reload can and can't do and why. 

> If closure doesn't capture mutable references (or captures them as immutable), might its body be promoted to a function declaration during compile time?

It does not really help. The problem is that closure literal has no _identity_ which can be used for identifying it during reload - and its relative position within the source is not reliable. Library URIs, class names and method names --- that's what drives reconciliation between old and new program, but closures (especially anonymous) can't be distinguished the same way (at least not reliably & predictably).

As I said we _could_ add support for the following:

```dart
void foo(@pragma('vm:reloadable-closure-literal') CallbackType f) {
}

// The closure body below will be reloaded if 
// 1) it is the only closure in the scope.
// 2) there is no change in captured variables. 
foo(() { /* */ })
```

But it is going to be rather fragile and it seems like a hack which is targeting specific problem.

**Comment by AlexanderFarkas** [comment]
> This is true, but you made this example intentionally obtuse for the sake of argument. Usually the method would have a more specific name, rather than printInfo:

Oh, that was unintentional. Now I get it. 

Since macros will help here, there is no practical sense in adding this kind of annotation. 
Thank you for the explanation and useful links/examples.

**Comment by vimhead** [comment]
@mraleph Out of curiosity, since macros were cancelled, might the Dart Team's opinion has been changed on this issue?

**Comment by mraleph** [comment]
Not really. We have no plans to lift this limitation because it is not entirely clear how it can be lifted in a robust way. If somebody comes us with a good design for this we can certainly reconsider, but so far we have not been able to come up with one.
