### ISSUE TITLE
[dart2wasm] Remove support for package:js and dart:js_util in favor of dart:js_interop and dart:js_interop_unsafe

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#54004]
`package:js` and `dart:js_util` is not restrictive enough for our purposes and may lead to unexpected behavior (either due to odd semantics or lack of support) and/or performance cliffs. This will require migrating internal usage, but for now we should treat these two libraries as deprecated for dart2wasm. Support for these libraries will continue on dart2js and ddc until we feel ready to start deprecating and migrating.

This will require migrating any Flutter usages to use `dart:js_interop`, but we can allowlist existing usages for now and disallow these libraries in dart2wasm for 3.3.

This will also require making sure `dart:js_interop` reaches parity with `package:js` and `dart:js_util` by providing any missing functionalities.

cc @kevmoo

**Comment by parlough** [comment]
For reference for those viewing the issue, the commit that fixed this the second time was https://github.com/dart-lang/sdk/commit/3a80ec26be56cc2f1e9fe8d89a1d8143d6c24030.

Thanks Srujan! This work will help making migration easier and clearer for developers trying out Wasm compilation.

**Comment by srujzs** [comment]
Thanks! I wish we had Github support to handle reverts and relands (essentially automatically reopening and reclosing the issue), but this is likely pretty complicated to support.
