### ISSUE TITLE
FutureOr<T> is incompatible with Future<T> and T

### ISSUE THREAD

**Issue by medz** [dart-lang/sdk#54033]
This tracker is for issues related to:

`dart:async`

#### General info

- Dart 3.1.5 (stable) (Tue Oct 24 04:57:17 2023 +0000) on "macos_arm64"
- on macos / Version 14.1.1 (Build 23B81)
- locale is zh-Hans-CN

#### Project info

- sdk constraint: '^3.1.5'
- dependencies:
- dev_dependencies: lints, test

## Example 1

```dart
import 'dart:async';

R test<T, R extends FutureOr<T>>(T value) {
  // return Future.value(
  //     value); // A value of type 'Future<T>' can't be returned from the function 'test' because it has a return type of 'R'.

  return value; // A value of type 'T' can't be returned from the function 'test' because it has a return type of 'R'.
}
```

## Example 2

```dart
import 'dart:async';

R test<T, R extends Future<T>>(T value) {
  return Future.value(value); // A value of type 'Future<T>' can't be returned from the function 'test' because it has a return type of 'R'.
}
```

## Example 3
```dart
// Functions marked 'async' must have a return type which is a supertype of 'Future'.
R test<T, R extends Future<T>>(T value) async {
  return value;
}
```

## Why do I do this?

I'm building a tool library that has a closure method that returns T when passed (T) => T, and a Future<T> when passed (T) async => Future<T>.

<img width="518" alt="image" src="https://github.com/dart-lang/sdk/assets/5564821/c89f4eb5-26e8-48e7-ae96-b6b9bf9503df">
<img width="533" alt="image" src="https://github.com/dart-lang/sdk/assets/5564821/7c1f8f3d-25dd-442a-b1ad-71a43c41f694">

```dart
extension DsvTransform<T> on DsvValidator<T> {
  /// Create a validator that will transform the value using the given
  /// [transform].
  DsvValidator<R> transform<V, R extends FutureOr<V>>(
    R Function(DsvContext context, T value) transform,
  ) {
    if (transform is Future Function(DsvContext, T)) {
      return _AsyncTransformValidator<T, V, R>(this, transform);
    }

    return _TransformValidator(this, transform.asSync);
  }
}
```

**Comment by lrhn** [comment]
This is working correctly.

The error is there because the types are not sound. Consider:
```dart
int x = test<num, int>(1.5);
```
The type arguments are valid for, `R test<T, R extends FutureOr<T>>(T value)`, since `int <: FutureOr<num>`.
In every example, the value that the code tries to return is not an `int`.

If you change the function  signature to
```dart
FutureOr<T> test<T>(T value) {
```
or for the real example:
```dart
extension DsvTransform<T> on DsvValidator<T> {
  /// Create a validator that will transform the value using the given
  /// [transform].
  DsvValidator<FutureOr<V>> transform<V>(
    FutureOr<V> Function(DsvContext context, T value) transform,
  ) {
    if (transform is Future<V> Function(DsvContext, T)) {
      return _AsyncTransformValidator<T, V, Future<T>>(this, transform);
    }

    return _TransformValidator(this, transform.asSync);
  }
}
```
then that code will likely also be valid.

**Comment by medz** [comment]
@lrhn I think this is incorrect. FutureOr<T> is the signature of T | Future<T>. My purpose is that I am threading T type data, so the returned signature should be T. What I am threading is Future< T> data, the return signature should be Future<T>

After I modified it according to your method, the return signature is always FutureOr<T>. This does not conform to the data logic of Union. FutureOr is a built-in Union type.
