### ISSUE TITLE
pkg/vm_service/test/uri_mappings_lookup_test is flaky on unittest-asserts-release-win-arm64

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#54034]
I think sometimes the resolved URI returned has an uppercase drive letter and sometimes it has a lowercase one.

Example failure:
```
00:04 [32m+0[0m[31m -1[0m: uri_mappings_lookup_test.dart [1m[31m[E][0m[0m

  Expected: 'file:///C:/opt/s/w/ir/cache/builder/sdk/pkg/vm_service/test/uri_mappings_lookup_test.dart'
    Actual: 'file:///c:/opt/s/w/ir/cache/builder/sdk/pkg/vm_service/test/uri_mappings_lookup_test.dart'
     Which: is different.
            Expected: file:///C:/opt/s/w ...
              Actual: file:///c:/opt/s/w ...
                              ^
             Differ at offset 8
  

  package:matcher/src/expect/expect.dart 149:31           fail
  package:matcher/src/expect/expect.dart 144:3            _expect
  package:matcher/src/expect/expect.dart 56:3             expect
  pkg\vm_service\test\uri_mappings_lookup_test.dart 30:5  tests.<fn>
  ===== asynchronous gap ===========================
  pkg\vm_service\test\common\test_helper.dart 312:13      _ServiceTesterRunner.run.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9        Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7        Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9         Invoker._waitForOutstandingCallbacks.<fn>
```

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release-arm64/81/overview

**Comment by derekxu16** [comment]
One possible solution is to change the line

https://github.com/dart-lang/sdk/blob/92e61ea4b7f0805e9610afb406519ef8f45761de/pkg/vm_service/test/uri_mappings_lookup_test.dart#L30

to

```
if (Platform.isWindows || Platform.isMacOS) {
  expect(uris[1].toLowerCase(), Platform.script.toString().toLowerCase());
} else {
  expect(uris[1], Platform.script.toString());
}
```

What do you think, @bkonyi?

**Comment by bkonyi** [comment]
> One possible solution is to change the line
> 
> https://github.com/dart-lang/sdk/blob/92e61ea4b7f0805e9610afb406519ef8f45761de/pkg/vm_service/test/uri_mappings_lookup_test.dart#L30
> 
> to
> 
> ```
> if (Platform.isWindows || Platform.isMacOS) {
>   expect(uris[1].toLowerCase(), Platform.script.toString().toLowerCase());
> } else {
>   expect(uris[1], Platform.script.toString());
> }
> ```
> 
> What do you think, @bkonyi?

I think that would work. However, I thought MacOS had similar behavior to Linux when it came to paths? If that's not the case, maybe it's just worth running `toLowerCase()` on paths in all situations?

**Comment by derekxu16** [comment]
I read this comment so I thought it would be safe to compare the lowercase versions of paths on Windows and MacOS:

https://github.com/dart-lang/sdk/blob/307a46f991f2c4f6db9d54f715c416b86790a4d4/runtime/vm/service.cc#L5403-L5404

The test isn't flaky on MacOS, so we could add a check for only `Platform.isWindows`.

**Comment by bkonyi** [comment]
> I read this comment so I thought it would be safe to compare the lowercase versions of paths on Windows and MacOS:
> 
> https://github.com/dart-lang/sdk/blob/307a46f991f2c4f6db9d54f715c416b86790a4d4/runtime/vm/service.cc#L5403-L5404
> 
> The test isn't flaky on MacOS, so we could add a check for only `Platform.isWindows`.

Oh, in that case, let's go with your initial proposal.
