### ISSUE TITLE
Incomplete sentence `argument_must_be_a_constant`

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/sdk#54036]
https://github.com/dart-lang/sdk/blob/c2301ae2ef4c5dffed48558703c1b1f06fa6316f/pkg/analyzer/messages.yaml#L18184

I think the rest of this sentence got cut off:

>    The analyzer also produces this diagnostic when the value of the
      `exceptionalReturn` argument of `Pointer.fromFunction` or
      `NativeCallable.isolateLocal`.

"...when the value of ... or ..." when those values do what?

**Comment by bwilkerson** [comment]
@dcharkes

**Comment by dcharkes** [comment]
I'm unsure what this is referring to. The file linked has the rest of the sentence on the next line?

**Comment by MaryaBelanger** [comment]
@dcharkes referring to the entire paragraph on lines [18184-18186](https://github.com/dart-lang/sdk/blob/c2301ae2ef4c5dffed48558703c1b1f06fa6316f/pkg/analyzer/messages.yaml#L18184C1-L18186C37) 

It says "The analyzer also produces this diagnostic _**when**_ the value of the `x` argument of `y` or `z`."  But it doesn't complete the sentence and tell me what the condition is, it just says "_when_ the argument..." _When_ the argument is/does _what_? 

For example, [the paragraph right before it](https://github.com/dart-lang/sdk/blob/c2301ae2ef4c5dffed48558703c1b1f06fa6316f/pkg/analyzer/messages.yaml#L18180-L18182) says:

> The analyzer produces this diagnostic when an invocation of either
   `Pointer.asFunction` or `DynamicLibrary.lookupFunction` **_has an `isLeaf`
   argument whose value isn't a constant expression._**

Is it the same condition? I.e. should line 18186 be followed by **_has an `isLeaf`argument whose value isn't a constant expression._**?

>    The analyzer also produces this diagnostic when the value of the
      `exceptionalReturn` argument of `Pointer.fromFunction` or
      `NativeCallable.isolateLocal` **_has an `isLeaf`argument
      whose value isn't a constant expression._**?

(This was updated ~3 months ago, but even before that [the sentence was incomplete](https://github.com/dart-lang/sdk/commit/e8d7425c4ea8765c1e349db9197563dcb45b9638#diff-dbce93c451b4be75ac3f4a86a1024389ceb41ffb253e17d5fe564a7f907e57acL18138). Maybe @liamappelbe (last commit in the blame) has the answer?)

**Comment by MaryaBelanger** [comment]
Thank you!
