### ISSUE TITLE
Add an `sdkVersionConstraint` getter to `WorkspacePackage`

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#54043]
See discussion in https://dart-review.googlesource.com/c/sdk/+/335063/3/pkg/analysis_server/lib/src/services/user_prompts/dart_fix_prompt_manager.dart.

**Comment by bwilkerson** [comment]
Let me summarize where I think that conversation landed. Let me know if I've misunderstood.

We're moving from `AnalysisContext.analysisOptions` to `AnalysisContext.getAnalysisOptionsForFile` (though we might want to consider dropping the `get` in the process). That is, the API will allow different files within an analysis context to have different analysis options.

We're moving from `AnalysisContext.analysisOptions.sdkVersionConstraint` to `AnalysisContext.contextRoot.workspace.findPackageFor.sdkVersionConstraint`. That is, the SDK constraints will be the same for everything within a package, but can be different from package to package within an analysis context.

We're postponing the decision about whether to wrap these values in an internal object for convenience and safety until we've had a change to understand what the impact would actually be.

**Comment by pq** [comment]
That sounds right. Does it follow that`Workspace` will get a new `sdkVersionConstraint` property and it will be up to the concrete workspace types (Blaze, Gn, Pub, etc) to implement it?

**Comment by scheglov** [comment]
Do you mean `WorkspacePackage`, not `Workspace`?

**Comment by bwilkerson** [comment]
Yes, the proposal is that there will be a new `WorkspacePackage.sdkVersionConstraint` getter.

**Comment by bwilkerson** [comment]
@keertip For visibility.

**Comment by pq** [comment]
@keertip: I was possibly going to take a look at this (unless you want to?)

**Comment by keertip** [comment]
@pq, that's fine by me, have not had the cycles to start on this as yet.

**Comment by pq** [comment]
Implemented w/ a354347178746c4d828ee073a1a8ece28203897e.
