### ISSUE TITLE
Reconsider how we configure lint rules in analysis options objects

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#54045]
In https://dart-review.googlesource.com/c/sdk/+/335063/3/pkg/linter/test/rule_test.dart, @scheglov notes:

> I understand that we need to configure lint rules in some way, but I'm concerned about the current approach of modifying the analysis options object directly. This can lead to code that is difficult to maintain and understand.

> I would propose an alternative approach that involves using or generating an analysis_options.yaml file. This would allow us to define lint rules in a more declarative and maintainable way, and it would also align with how the analysis server handles lint rules.

> I believe that this change would make our code more readable, easier to understand, and less prone to errors. I would be happy to discuss this further if you have any questions.

**Comment by scheglov** [comment]
Let me re-state it a bit easier, without LLM nonsense.

I hoped to be able to use `AnalysisContextCollection[Impl]` for all our analysis uses.
And I did a big push to use it for the analysis server itself.
Just give it the correctly configured file system, and let the analyzer do its work.
Don't go to the low level, and don't patch internal data.
This should be the last resort, if we really cannot do otherwise.

**Comment by srawlins** [comment]
I made a big step in this direction with

* https://dart-review.googlesource.com/c/sdk/+/390660 - make 11 fields in AnalysisOptionsImpl final. Woohoo!
* https://dart-review.googlesource.com/c/sdk/+/391020 - make the three strict modes part of the public API.

However, a few fields remain mutable. In particular `enabledLegacyPluginNames` is still writable and is still modified in tests.

**Comment by srawlins** [comment]
And with https://dart-review.googlesource.com/c/sdk/+/392240 I think this can be closed. We still pass around this annoying `updateAnalysisOptions` argument around various functions, like AnalysisContextCollectionImpl. We do not update lint rules with that function; it's usually `warning`, `lint`, and `contextFeatures`. Please re-open if there are more specific actions to take here.
