### ISSUE TITLE
[analyzer] Unused type parameter in return type seems to disrupt type checks

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54055]
Consider the following program:

```dart
class A {}
class B {}
class R {}

typedef F<X> = X Function(R);

F<B> Function<Unused>(F<A>) foo(B Function(A) f) => throw 'Whatever';
F<B> Function(F<A>) bar(F<B> g) => foo((A _) => g);

void main() {}
```

This program is rejected by the CFE (commit 0fa6a6b8b754a2ab99db03fc59e7918437d6f0e6):

```
n010.dart:8:49: Error: A value of type 'B Function(R)' can't be returned from a function with return type 'B'.
 - 'B' is from 'n010.dart'.
 - 'R' is from 'n010.dart'.
F<B> Function(F<A>) bar(F<B> g) => foo((A _) => g);
                                                ^
```

However, the analyzer accepts the program without errors (same commit). 

Surprisingly, the tools agree on the error if `<Unused>` is removed from the program. Seems like the analyzer gets confused by the fact that `foo` returns a generic function, to such a degree that it garbles the type checks on actual arguments even when the given type parameter is unused.

I've used the label 'soundness' as well, because this kind of error would (assuming that the other tools had the same behavior) allow `foo` to be called with an actual argument whose type isn't a subtype of the declared type of the formal parameter.

**Comment by eernstg** [comment]
@srawlins, I just tried the example, and it looks like this issue has been resolved already?

**Comment by srawlins** [comment]
Haha could be. I don't know if anyone explicitly looked at this.

**Comment by eernstg** [comment]
OK, I double-checked, and I think this issue can be closed (unless someone in the analyzer team thinks otherwise).

**Comment by bwilkerson** [comment]
Thanks for checking! If it turns out that there's still a bug here we can either re-open this issue or create a new one.
