### ISSUE TITLE
findProxyFromEnvironment is not picking up environment variables defined by `flutter run --dart-define=...`

### ISSUE THREAD

**Issue by ManuelRauber** [dart-lang/sdk#54053]
Hi,

I'm using the following code to create a `HttpClient` and make a request (Flutter 3.13.9, Dart 3.1.5, macOS, iOS Simulator):

```dart
print(const String.fromEnvironment('HTTPS_PROXY');
final httpClient = HttpClient()
      ..idleTimeout = const Duration(seconds: 3)
      ..findProxy = HttpClient.findProxyFromEnvironment;

    await httpClient.getUrl(Uri.parse('https://my-example-api.com/foobar'));
```

I run this piece of code via `flutter run --dart-define=HTTPS_PROXY=localhost:8888`.

As expected from the `print`, I get whatever I've set in `--dart-define`, in this case it prints `localhost:8888` to the console.

However, I can see, that `findProxyFromEnviroment` is not using the proxy.

Then, I've tried this here:

```dart
print(const String.fromEnvironment('HTTPS_PROXY');
final httpClient = HttpClient()
      ..idleTimeout = const Duration(seconds: 3)
      ..findProxy = (final uri) => 'PROXY ${const String.fromEnvironment('HTTPS_PROXY')}';

    await httpClient.getUrl(Uri.parse('https://my-example-api.com/foobar'));
```

And suddenly, the proxy is working as expected. 

According to the documentation of [findProxyFromEnviroment](https://api.flutter.dev/flutter/dart-io/HttpClient/findProxyFromEnvironment.html), it should pick it up from `HTTPS_PROXY`, but it does not.

// Edit

If I do the following:

```dart
class ProxyOverrides extends HttpOverrides {
  @override
  String findProxyFromEnvironment(final Uri url, final Map<String, String>? environment) =>
      super.findProxyFromEnvironment(url, {
        // ignore: do_not_use_environment
        'HTTP_PROXY': const String.fromEnvironment('HTTP_PROXY'),
        // ignore: do_not_use_environment
        'HTTPS_PROXY': const String.fromEnvironment('HTTPS_PROXY'),
      });
}

// in main:
HttpOverrides.global = ProxyOverrides();
```

then it works also as expected. No sure, if this is the real solution, or if the documentation is wrong for Flutter, or if the implementation has a bug.

**Comment by mraleph** [comment]
You are being confused by poor choice of naming in `dart` core libraries. 

There are two different things which are called almost the same: 

* OS _environment **variables**_: things you can define in your shell by doing `export HTTPS_PROXY=...`;
* Dart's _environment **declarations**_: compile time values passed via `--dart-define` and `-D` flags.

[findProxyFromEnviroment](https://api.flutter.dev/flutter/dart-io/HttpClient/findProxyFromEnvironment.html) is looking at OS environment variables. 

@lrhn should we maybe deprecate `int.fromEnvironment` and friends and provide a more aptly named `int.fromDartDefine`?

**Comment by ManuelRauber** [comment]
> You are being confused by poor choice of naming in `dart` core libraries.
> 
> There are two different things which are called almost the same:
> 
> * OS _environment **variables**_: things you can define in your shell by doing `export HTTPS_PROXY=...`;
> * Dart's _environment **declarations**_: compile time values passed via `--dart-define` and `-D` flags.
> 
> [findProxyFromEnviroment](https://api.flutter.dev/flutter/dart-io/HttpClient/findProxyFromEnvironment.html) is looking at OS environment variables, not at Dart's environment declarations.
> 
> @lrhn should we maybe deprecate `int.fromEnvironment` and friends and provide a more aptly named `int.fromDartDefine`?

Gotcha.

so my "workaround" I've edited is the solution for the issue because it now looks at the dart environment declarations. Ok, it would be nice if the wording would be more precise in the future because, according to the documentation, I'm in the flutter documentation, so I was kind of expecting it to work.

![image](https://github.com/dart-lang/sdk/assets/740791/b562f089-c532-4a96-86e2-c5713521ba22)
