### ISSUE TITLE
Add a quick fix for a missing semicolon

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#54063]
Not sure we want a single fix for every missing token because sometimes the parser gets confused and what it reports as missing isn't what we'd want to add, but for semicolons it seems to do a fairly good job of recovering and we have feedback from a user that it would be nice to have.

It should have a 'fix-all-in-file' mode.

**Comment by bernaferrari** [comment]
For me, if parser is able to say "missing semicolon at line X" it should be fixable. Most complex cases it is fine, but I'm used to type `let a = 1` and 'command+shift+l" on JS world to get the ";" automatically.

**Comment by lrhn** [comment]
If the parser suggests a semicolon that is not at the end of a line, it's probably spurious.
Only inserting semicolons at the end of existing lines is more likely to be correct.

Or maybe check if there are other errors shortly after the suggested semicolon, within the next statement, and if so, the semicolon might not be the correct recovery.
If not, the recovery was successful, so the semicolon is probably correct.

**Comment by keertip** [comment]
@bwilkerson , we have a fix for insert semicolon, but it is not have a 'fix-all-in-file' mode. Is that what this issue is about?

**Comment by bernaferrari** [comment]
can I write without the ";", tap command+shift+l, and the IDE adds it for me?

**Comment by bwilkerson** [comment]
> we have a fix for insert semicolon, but it is not have a 'fix-all-in-file' mode. Is that what this issue is about?

I didn't realize we had that fix already. So, yes, I believe adding support for applying it to a whole file would fix this issue.

> can I write without the ";", tap command+shift+l, and the IDE adds it for me?

I don't know what that command does, so I can't answer that question. I suspect it depends on which IDE you're using and maybe which platform it's running on.

**Comment by bernaferrari** [comment]
format/dart fix (I guess)

**Comment by bernaferrari** [comment]
would it be possible for dart format to actually fix this?

**Comment by bwilkerson** [comment]
I don't know whether it would be possible, but we're actually trying to move all of the formatter-provided fixes into `dart fix` so that the formatter only formats code, so adding a new kind of fix to the formatter is probably not going to happen.

**Comment by bernaferrari** [comment]
what if there were an option to call dart fix when formatter is called? Even with a hit, I would love something like that, because it would simplify my development.

**Comment by bernaferrari** [comment]
I understand, but it still makes Dart a lot harder to use than Rust, TypeScript and most other languages that add the ";" (and sometimes fixes the code) as you format.

**Comment by mossmana** [comment]
I am planning on implementing the fix-in-file support for the ';'. https://docs.google.com/document/d/1sv58TvkUUytp3TseNeXxZo5dwbXkPptGYsK2YIsizJc/edit?usp=sharing

However, adding support to the formatter will require additional discussion.

> I understand, but it still makes Dart a lot harder to use than Rust, TypeScript and most other languages that add the ";" (and sometimes fixes the code) as you format.

@bernaferrari Would you mind filing a separate issue for adding support to the formatter?

**Comment by bernaferrari** [comment]
My understanding is that the team has zero desire to add to the formatter, even though the experience would be substancially better (and make Dart be easier to use, just like TS and Rust are). So, I guess you don't need to worry about that for now.

**Comment by bwilkerson** [comment]
> I am planning on implementing the fix-in-file support for the ';'.

Note the class `InsertSemicolon` in `analysis_server/lib/src/services/correction/dart/insert_semicolon.dart`. It might work as-is, or it might need additional support.

**Comment by lrhn** [comment]
JavaScript has optional semicolons to begin with, so adding them when formatting doesn't change behavior. That's something you'd want for a formatter. 

Rust makes semicolons semantic, you can omit then but then the code means something else, but they make no difference for non-tail expressions, so it's safe to insert them there. I guess that's what the formatter does.

Dart does not have optional semicolons, they're usually either required or disallowed, only in very few places will a program be valid both with and without a semicolon. Inserting semicolons would not be _formatting_, it would be rewriting the program (or something which is not a valid Dart program at all), by inserting new characters at heuristically chosen positions. 
Not a formatter job.

**Comment by mossmana** [comment]
https://dart-review.googlesource.com/c/sdk/+/373326
