### ISSUE TITLE
[analysis_server] `convert_to_if_case_statement_chain` assist deletes switch with empty body

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#54077]
```void
void main() {
  switch (3) {}
}
```

If you try a quick fix on `switch`, it will offer to apply `convert_to_if_case_statement_chain`, which removes the switch. Technically it doesn't change the behavior in this situation, but I'd rather this not be offered even in that case. If the expression being matched does have side effects though, the quick fix will change behavior.

**Comment by bwilkerson** [comment]
I agree. The assist isn't useful if there are no cases.
