### ISSUE TITLE
[Extension type] Implement new nullaility rules in analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54079]
Changes according to the https://github.com/dart-lang/language/pull/3434 has been implemented in CFE but not implemented in the analyzer yet. This causes failures of 
```
co19/LanguageFeatures/Extension-types/upper_bound_A01_t05
co19/LanguageFeatures/Extension-types/upper_bound_A01_t06
```

**Comment by scheglov** [comment]
This was implemented in e6b02b5895c616977ebf0a9f002b3e213629ca95, these tests don't fail anymore.
