### ISSUE TITLE
Failures on [vm/ffi] Tests with `Handles` and constants...[dart2wasm] Add option to verify type check implementations

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#54072]
There are new test failures on [[vm/ffi] Tests with `Handles` and constants...[dart2wasm] Add option to verify type check implementations](https://github.com/dart-lang/sdk/compare/80a69223e075af3349bf6eff15e0729c25c7496c~...c6a85b81f4bdca27f670e1e50c1a967c0e7f0867).

The tests
```
ffi/ffi_native_handles_test Crash (expected Pass)
```
are failing on configurations
```
vm-aot-win-release-x64
```

The test was added in https://dart-review.googlesource.com/c/sdk/+/336661 and immediately starts crashing.
@dcharkes Could you take a look?

**Comment by dcharkes** [comment]
Probably: https://github.com/dart-lang/sdk/issues/40579
