### ISSUE TITLE
[dart2js] pkg/compiler/test/deferred_loading/deferred_load_id_map_test flaky/timeout

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#54084]
```
pkg/compiler/test/deferred_loading/deferred_load_id_map_test Timeout (expected Pass)
```
changed from flaky to timeout on
```
web-unittest-asserts-linux
```

**Comment by biggs0125** [comment]
My guess is there are just too many test cases being run here. We run every test case twice in this one test, once with "simple ids" and once normally. I think I can just break this into 2 tests to fix this.
