### ISSUE TITLE
Analysis regression of `prefer_const_constructors` in version 3.2.0 in relation to generic constructors

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#54092]
Consider, the following program and analysis options files:

```dart
// main.dart
class A<T> {
  const A();
}

class B<T> {
  final A<T> Function() fn;

  const B(this.fn);
}

B<T> fn<T>() {
  return B(A<T>.new); // analyzer shows info message, when it shouldn't
}
```

```yaml
# analysis_options.yaml
linter:
    rules:
        prefer_const_constructors: true
```

Running `dart analyze` returns the response:
```txt
  info • main.dart:12:10 • Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. •
          prefer_const_constructors
```

However, if we add const before `B(A<T>.new)`, the analyzer produces an error, since T is not static.

**dart --version**
`Dart SDK version: 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "macos_x64"`

The program is correctly analyzed in version 3.1.

**Comment by scheglov** [comment]
@kallentu - may this be related to any constant evaluation changes that you did recently?
