### ISSUE TITLE
Analyzer allows instantiation of an instance tearoff in a field initializer

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#54091]
The following code is accepted by the analyzer but rejected by the CFE:
```dart
class C {
  final x = f<int>;
  f<T>() {}
}

main() {}
```

The CFE reports:
```
../../tmp/proj/test.dart:2:13: Error: Can't access 'this' in a field initializer to read 'f'.
  final x = f<int>;
```

The CFE is correct; this code should be rejected.

**Comment by srawlins** [comment]
Good catch, Paul. I think we're not reporting a few errors on these function references. I've got a fix.
