### ISSUE TITLE
[CFE] No error in CFE if an extension type is not well-bounded

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54097]
The following program produces an expected error in analyzer but not in CFE
```dart
// SharedOptions=--enable-experiment=inline-class

extension type V<T extends V<T>>(T id) {}
//                         ^
// [analyzer] unspecified
// [cfe] unspecified

main() {
  print(V<Never>);
}
```
After extension type erasure we'll have here `extension type V<T extends T>(T id) {}` which is an error. So, analyzer correctly expects `COMPILE_TIME_ERROR.TYPE_PARAMETER_SUPERTYPE_OF_ITS_BOUND` here

Tested on `Dart SDK version: 3.3.0-edge.5918e012cc875df2b96ec25e3fee0de263feed80 (main) (Mon Nov 20 08:03:39 2023 +0000) on "linux_x64"`

**Comment by chloestefantsova** [comment]
Thanks for reporting that, @sgrekhov! As far as I understand, the related passage in the spec is the following:

> Let X1 extends B1, .. Xs extends Bs be a declaration of the type parameters of a generic entity (it could be a generic class, extension type, mixin, typedef, or function). Let BBj be the extension type erasure of Bj, for j in 1 .. s. It is a compile-time error if X1 extends BB1, .. Xs extends BBs has any compile-time errors.

Also, the compile-time message emitted by the Analyzer could be more helpful. Currently it says `'T' can't be a supertype of its upper bound.`, even though `T` is not a supertype of its bound, `V<T>`.

**Comment by eernstg** [comment]
> has any compile-time errors.

I don't know if this is obvious, but the transformation that replaces each bound by its extension type erasure could of course create compile-time errors in the body whenever a receiver has a type which is a type variable, and it used to invoke an extension type member (but when the bound is no longer that extension type, the member does not exist, or it has a different member signature). So we're only requiring that it would not be an error of a type parameter to declare the type parameters as bounded by the extension type erasures, we don't care that there could be errors where the type parameter is used.
