### ISSUE TITLE
Allowing the instantiation of a generic type by calling a no-arg constructor

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#54106]
I want to be able to instantiate generic types, whenever those types have a no-arg constructor:

```dart
class Foo<T> {
  T createT() => T();
}
```

This seems to be the best that can be done right now:

```dart
class Foo<T> {
  final T Function() newT;
  Foo(T Function() newT);

  T createT() => newT();
}

void x() {
  final foo = Foo<Bar>(Bar.new);
  final bar = foo.createT();
}
```

(I'm sure this has been raised before, although I can't find an issue on this...)

**Comment by leafpetersen** [comment]
Re-opened the referenced issue to serve as a the canonical tracking bug for the request.
