### ISSUE TITLE
Failures on [infra] Upgrade firefox to 120.0

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#54118]
There are new test failures on [[infra] Upgrade firefox to 120.0](https://dart-review.googlesource.com/c/sdk/+/337541).

The tests
```
lib/html/cache_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-linux-firefox
ddc-linux-firefox
```

**Comment by srujzs** [comment]
I don't think `ApplicationCache` exists anymore as a browser type. I can't access this type or member in Chrome either.

@sigmundch I say let's delete this test.

**Comment by rakudrama** [comment]
+1. The other browsers were already failing this test.

**Comment by srujzs** [comment]
https://dart-review.googlesource.com/c/sdk/+/338427
