### ISSUE TITLE
[dart:js_interop] Add `has` member as a shorthand equivalent for hasProperty

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#54126]
We have short-hand equivalents for `getProperty`/`setProperty` (`[]`/`[]=`, respectively) that take in a `String` to reduce the amount of code users have to write in the common case. We still keep around `getProperty`/`setProperty` in case the property is not a `String` or if users don't want the conversions. We should do something similar for `hasProperty` e.g.

`external bool has(String property)`

This takes code that look like this:

`if (jsObj.hasProperty(prop.toJS).toDart)`

to

`if (jsObj.has(prop))`

cc @kevmoo

**Comment by redDwarf03** [comment]
Hello

So, is it possible to convert a method like that from `dart:js` to `dart:js_interop` ?

```
/// SPDX-License-Identifier: AGPL-3.0-or-later
import 'dart:js' as js;

class BrowserUtil {
  bool isBraveBrowser() {
    return js.context.hasProperty('navigator') &&
        js.context['navigator'].hasProperty('brave');
  }

  bool isEdgeBrowser() {
    return js.context.hasProperty('navigator') &&
        js.context['navigator'].hasProperty('userAgent') &&
        js.context['navigator']['userAgent'].toString().contains('Edg/');
  }

  bool isInternetExplorerBrowser() {
    return js.context.hasProperty('navigator') &&
        js.context['navigator'].hasProperty('userAgent') &&
        (js.context['navigator']['userAgent'].toString().contains('MSIE ') ||
            js.context['navigator']['userAgent']
                .toString()
                .contains('Trident/'));
  }
}
```

**Comment by srujzs** [comment]
Correct (using `has`). Here `context` corresponds to the global context, so use `globalContext` as the equivalent, or an interop member for `window` if you want to be explicit.

Closing the original issue as it's done.
