### ISSUE TITLE
Failures on 329961: Adding the `resource-identifier` functionality from the compiler to the vm

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#54129]
There are new test failures on [Adding the `resource-identifier` functionality from the compiler to the vm](https://github.com/dart-lang/sdk/compare/099721d8a2ebecf71739ae3585f210b35ba20ac0).

The tests
```
pkg/vm/test/transformations/resource_identifier_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win-arm64
unittest-asserts-release-win-x64
```

Example log:
https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win-x64/26691/pkg/vm/test/transformations/resource_identifier_test

**Comment by lrhn** [comment]
Commit does seem to put a `Directory.path` directly into a `Uri(path: ...)` at some point.

Always us `Directory.uri` or `Uri.directory` to convert a `Directory` to a `Uri`, and `Directory.fromUri` for the other direction.
Only use `path.join` on file paths, only `Uri.resolve` on URI paths, to ensure that file paths use the platform path separator, and URIs use `/` as path segment separator.

**Comment by mosuem** [comment]
Thanks! Is there a way of running these tests before submitting?

**Comment by lrhn** [comment]
Seems the build-bot found the issue, so uploading a CL and triggering one of the `win`-buildbots above should work.

**Comment by a-siva** [comment]
> Thanks! Is there a way of running these tests before submitting?

@mosuem do you a CL with the fix ?

**Comment by parlough** [comment]
I'm planning to work on some related code so I opened a fix at https://dart-review.googlesource.com/c/sdk/+/343360.

**Comment by dcharkes** [comment]
Still failing on arm64: https://dart-current-results.web.app/#/filter=pkg/vm/test/transformations/resource_identifier_test&showAll

Log: https://dart-ci.appspot.com/log/any/unittest-asserts-release-win-arm64/462/pkg/vm/test/transformations/resource_identifier_test

```
  The first difference is at line 11.
  Actual:         "uri": "../../../../../../../../C:/opt/s/w/ir/cache/builder/sdk/pkg/vm/testcases/transformations/resource_identifier/simple.dart",
  Expected:       "uri": "pkg/vm/testcases/transformations/resource_identifier/simple.dart",
```

**Comment by dcharkes** [comment]
Bot config:

https://github.com/dart-lang/sdk/blob/70783e5eb0e4bbb42de021d616a42feca6e35924/tools/bots/test_matrix.json#L2866-L3100

The tests are not run on shards for arm64, which could explain why the tests are run in a different manner.

**Comment by dcharkes** [comment]
@parlough or @mosuem, Could you try running the test manually with `dart ...` with an absolute path to see if that reproduces the issue on x64 as well?
