### ISSUE TITLE
`Enum.values.byName` also needs a `Enum.values.byNameOrNull`

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#54137]
`Enum.values.byName` exists currently, which throws an exception if the named enum constant does not exist. But `Enum.values.byNameOrNull` does not, which should simply return `null` in this case.

This requires you to wrap your `byName` call in `try {} catch {}`, rather than simply using `??` to handle enum values that are not found by name.

The list filtering iterators e.g. `firstWhere` all have `...OrNull` alternatives that do not throw an exception, and they are very useful.

Can `Enum.values.byNameOrNull` please be added?

**Comment by lrhn** [comment]
Enums have a fixed set of statically known names. The intended use case for  `byName` is that you get one of these names, perhaps from a serialization, and find the corresponding enum value.
It's not intended for testing whether an enum has a value with a particular name, or using some random input as an argument. It's not intended as introspection.

If you want to introspect, iterate the values, or use the `asNameMap` method to get a map from names to values, and use it's lookup or `containsKey`.
