### ISSUE TITLE
[Flutter] In Android REST API Calls are slow compared to iOS

### ISSUE THREAD

**Issue by sabachimp** [dart-lang/sdk#54131]
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (4 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

We are creating business-critical application in flutter for Android and IOS. 

This application is mainly based on REST API calls and we are using the [http](https://pub.dev/packages/http) package for network library. 

Observed significant performance change while comparing Android and IOS in REST API calls response time. IOS is faster while comparing the Android response time.

As I searched the existing issues there is no relevant information. 

So I request your kind attention on this important issue.

**Comment by lrhn** [comment]
The `http` package is [here](https://github.com/dart-lang/http/tree/master/pkgs/http), but it's likely that its performance characteristics come from `dart:io`'s HTTP implementation.

**Comment by parlough** [comment]
I am not familiar with the http client implementations, but I was wondering if you could try using https://pub.dev/packages/cronet_http as the underlying `package:http` client on Android? It is experimental, but might provide a useful point of comparison.

**Comment by mraleph** [comment]
This is not really actionable unless you provide more information and some sort of reproduction. There are so many factors involved here that the problem can be anywhere in the stack (including differences in the networking stack and even hardware). 

iOS device might simply be faster than Android device you are comparing against - start by making sure they are comparable.
