### ISSUE TITLE
`dart compile exe` says "require the native assets feature to be enabled" and fails even after `--enable-experiment=native-assets` is added

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#54132]
Hi, thanks for the toolchain!

When running `dart compile exe`, it seems that even if I add `--enable-experiment=native-assets`, it still complains that the flag should be enabled.

P.S. I am (currently) using `build.dart` (in flutter_rust_bridge's pure-dart example) to build a dynamic library, and has not used `@Native` yet, so it is not related to static linking issue (if any).

Shell output:

```
(base) ➜  native git:(main) ✗ cd pkgs/native_assets_cli/example/native_add_app 

(base) ➜  native_add_app git:(main) ✗ dart compile exe bin/native_add_app.dart 
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.
(base) ➜  native_add_app git:(main) ✗ dart --enable-experiment=native-assets compile exe bin/native_add_app.dart 
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.

(base) ➜  native_add_app git:(main) ✗ dart run  bin/native_add_app.dart         
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.
(base) ➜  native_add_app git:(main) ✗ dart  --enable-experiment=native-assets run bin/native_add_app.dart 
Invoking a native function to calculate 1 + 2.
Invocation success: 1 + 2 = 3.
```

Also commented here: https://github.com/dart-lang/sdk/issues/50565#issuecomment-1822185037

**Comment by navaronbracke** [comment]
See https://github.com/flutter/flutter/issues/138727#issuecomment-1819759190

In short the name `build.dart` is what the tooling checks for for native assets.

**Comment by fzyzcjy** [comment]
@navaronbracke Thank you, I agree. But I have added `--enable-experiment=native-assets` and it still says the error and refuse to compile...

**Comment by navaronbracke** [comment]
What if you make your `build.dart` file conform to the native assets configuration (but just output nothing).
See a bit further in the thread:

```
One hacky workaround: Ensure that the build.dart also conforms to the native assets protocol, and just outputs no assets, and enable the feature.
```

**Comment by mraleph** [comment]
@fzyzcjy Could you try `dart compile exe --enable-experiment=native-assets` instead? I think you are putting the flag into the wrong position. (e.g. it enables experiments for the `dart` VM which runs CLI, rather than passes it down to the CLI itself).

**Comment by fzyzcjy** [comment]
Thanks for the replies!

@navaronbracke Hi, I am using the `native_add_app` example (`native/pkgs/native_assets_cli/example/native_add_app`) provided by Dart, i.e. https://github.com/dart-lang/native/blob/main/pkgs/native_assets_cli/example. So I guess the protocol is correct.

@mraleph Hi, here are the results:

```
(base) ➜  native_add_app git:(main) dart compile exe --enable-experiment=native-assets bin/native_add_app.dart
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.

(base) ➜  native_add_app git:(main) dart --enable-experiment=native-assets compile exe bin/native_add_app.dart
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.

(base) ➜  native_add_app git:(main) dart compile --enable-experiment=native-assets exe bin/native_add_app.dart
Could not find an option named "enable-experiment".

Usage: dart compile <subcommand> [arguments]
-h, --help    Print this usage information.

Available subcommands:
  aot-snapshot   Compile Dart to an AOT snapshot.
  exe            Compile Dart to a self-contained executable.
  jit-snapshot   Compile Dart to a JIT snapshot.
  js             Compile Dart to JavaScript.
  kernel         Compile Dart to a kernel snapshot.

Run "dart help" to see global options.

(base) ➜  native_add_app git:(main) dart compile exe bin/native_add_app.dart           
Package(s) native_add_library require the native assets feature to be enabled. Enable native assets with `--enable-experiment=native-assets`.

**Comment by dcharkes** [comment]
> Hi, when running `dart compile exe`, it seems that even if I add `--enable-experiment=native-assets`, it still complains that the flag should be enabled.

Depends on where you add it `dart --enable-experiment=native-assets compile exe`. It's a flag to dart not to the compile or exe subcommands.

However you want to use `dart build` instead of `dart compile`. Native assets are built to dynamic libraries, and `dart compile` returns a single file. `dart build` creates a directory instead.

**Comment by fzyzcjy** [comment]
@dcharkes Hi, thanks for the information!

> However you want to use dart build instead of dart compile. Native assets are built to dynamic libraries, and dart compile returns a single file. dart build creates a directory instead.

Sorry I did not find `dart build` in https://dart.dev/tools/dart-tool, do you mean `flutter build`? (But I am working on a pure-Dart example so do not want to touch Flutter)

**Comment by dcharkes** [comment]
`dart --enable-experiment=native-assets build` is also gated behind the experiment flag.

**Comment by fzyzcjy** [comment]
Aha, it runs, thank you!

P.S. I can never find this hidden magic by myself 😆

```
(base) ➜  native_add_app git:(main) dart --enable-experiment=native-assets build bin/native_add_app.dart 
Building native assets.
Copying native assets.
Generated: /Volumes/MyExternal/ExternalRefCode/native/pkgs/native_assets_cli/example/native_add_app/bin/native_add_app/native_add_app.exe
(base) ➜  native_add_app git:(main) bin/native_add_app/native_add_app.exe 
Invoking a native function to calculate 1 + 2.
Invocation success: 1 + 2 = 3.
```
