### ISSUE TITLE
No way to get enum values for `<T extends Enum>` generic type?

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#54136]
I keep running into problems with using enums in generic parameters.

I want to do something like the following:

```dart
List<T> getEnumValues<T extends Enum>() => T.values;
```

However, `T extends Enum` seems to only create a type for one *value* of an enum, not for the `Enum` class itself.

So even though all `Enum` classes have the `.values` getter, there is no way to call it generically. (Or am I mistaken?)

**Comment by lrhn** [comment]
No, you are absolutely right, there is no way to go from a type variable to a static member of that type variable's type.
 
Also, not all subtypes of `Enum` has a `values` static member. It's possible to have abstract interface classes and mixins which implant `Enum`, the only thing you do know is that if it's a concrete type, it's an `enum`-declared type, which will have a `values`static member. You can't tell if a type variable type is such a s type.

With extension types, even that won't be true. You can have subtypes of `enum`-declared types which have no `values`.
