### ISSUE TITLE
"Generate Constructor" uses old super-parameter convention

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#54156]
I changed some fields in a class:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/0b99ba21-d952-4366-a872-136ad74fd082)

I then selected "Generate Constructor" from the quick fix list:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/9ba95a80-554e-449c-8bbc-e7a06a2da8b3)

Now I have to apply the quick fix for "Convert 'key' to a super parameter":

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/daa8fd73-fbae-40d0-ba53-23613cabca1a)

Dart SDK version: 3.3.0-91.0.dev (dev) (Thu Nov 2 09:10:03 2023 -0700) on "linux_x64"

**Comment by FMorschel** [comment]
Just to clarify, which "Create Constructor" option did you use? I've tested some combinations of fixes but I could not repro your example.

Things I noticed:

```dart
class C {
  final int a;

  C({required this.a});
}

class D extends C {
  final int b;
}
```

1. When using the fix on `D` the generated constructor ignores `b`.
2. When using the fix on `b` "required named" all works fine
3. When using the fix on `b` for "final fields" (no required named) it doesn't add `a`.
    When doing this, on the generated constructor `D(this.b);` there is a fix on `D` there are two options :
    a. "Add super constructor invocation" which _could be_ what you meant
    b. "Add required parameter" which produces invalid code `D(, {required super.a}this.b);` (latest master)

**Comment by lukehutch** [comment]
1. Use "Flutter Statless Widget" template: ![image](https://github.com/user-attachments/assets/9dc6fcda-6aa6-48ed-8961-cfc5a1775f9c)
2. Add a field: 
![image](https://github.com/user-attachments/assets/32096518-a615-4d02-a228-ecdd6d3279de)
3. Use Quick Fix -> Generate Constructor: 
![image](https://github.com/user-attachments/assets/93aa965e-1341-459e-91f5-993b84293418)

**Comment by FMorschel** [comment]
Sorry, I can't seem to find "Generate Constructor" - I'm on the latest Flutter Stable with Dart 3.5.3.

![image](https://github.com/user-attachments/assets/9add7284-710b-4058-a26c-bac4915b8216)

![image](https://github.com/user-attachments/assets/112c1a9b-b75b-4c18-a243-a777f35ac891)

![image](https://github.com/user-attachments/assets/d46d7fb3-8182-4fbe-b696-7b068ff6a952)

**Comment by lukehutch** [comment]
Weird. It's there in my list...

**Comment by FMorschel** [comment]
Can you provide a screenshot? Also, you can try with only the official Dart/Flutter extensions enabled temporarily to see. 

One thing I noticed was that you mentioned Dart 3.3.0 in your original message, what version are you using? Is it still that one? As I mentioned above, I tested on the latest stable. A run of `flutter doctor -v` should show us your version.

**Comment by lukehutch** [comment]
![image](https://github.com/user-attachments/assets/ad749dd1-5e21-48a2-953b-9696585d8a9a)

> Also, you can try with only the official Dart/Flutter extensions enabled temporarily to see.

@FMorschel Oops! That was it. I had an extension "Dart Data Class Generator" that I must have installed a long time ago and forgotten about. That was providing the quick fix.

My apologies, this is not a Dart or Dart-Code issue at all! I assume that this extension added quick fixes that the analyzer knows nothing about.

I'll go ahead and close this! Although I will say, maybe there should be a way to list which extension added which menu item or button to which menu or pane, so that it's easier to get to the bottom of what's going on in these sorts of situations.

Thanks for trying to repro this -- sorry for the wild goose chase!
