### ISSUE TITLE
Remove the widget cache experiment

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#54168]
The widget cache experiment is obsolete and can be removed.

I tried [submitting a patch to do this](https://dart-review.googlesource.com/c/sdk/+/319871) months ago but it never got reviewed. Someone should take that CL and run with it; while the contribution process for Dart is as unrewarding and non-standard as it is today, I don't expect I'll have the motivation to follow up on this myself.

**Comment by devoncarew** [comment]
This looks like some useful cleanup. It looks like this may have originally been written by Jonah?

> the contribution process for Dart is as unrewarding and non-standard

Surprisingly enough, there's some disagreement about whether we should even improve it.

**Comment by johnniwinther** [comment]
The CL has landed.
