### ISSUE TITLE
[pkg][analyzer][gardening] Verify docs test is timing out

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54183]
This test is timing out again.

Previous attempts:

* https://github.com/dart-lang/sdk/issues/53229
* https://github.com/dart-lang/sdk/issues/52738

cc @bwilkerson @srawlins

**Comment by dcharkes** [comment]
I'll approve the failure so we get a signal of any other failures on pkg bots.

**Comment by bwilkerson** [comment]
Yes. I have a CL out now that will hopefully fix the timeout by increasing the amount of time the test is allowed to run, but we need a better long term solution.

The test is ensuring that example code in our documentation analyzes cleanly. The more documentation we write the longer it takes to find an analyze the examples. We call the `test` method once per file, so we're only timing out for larger files.

We could investigate parsing the files to find example code and then calling `test` once per example.

We could also investigate writing shorter files. :-)

Other ideas are welcome.
