### ISSUE TITLE
SDK Version at 3.2.2, docker image still at 3.2.0

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#54184]
https://hub.docker.com/_/dart

**Comment by parlough** [comment]
I've opened https://github.com/docker-library/official-images/pull/15790 to update Docker hub.

\cc @itsjustkevin Is this something that can be automated?

**Comment by mnordine** [comment]
I see 3.2.2 is up now, thanks, 👍

**Comment by athomas** [comment]
It is part of our release process to publish to docker. Some hick-ups happened in the release process of 3.2.1 so it didn't get published and yesterday we had a day long outage in our Windows release infrastructure that blocked the final steps (docker is the last step and that was completed by https://github.com/docker-library/official-images/pull/15796). It's also only semi-automated.

Docker official images will not be ready immediately after a new Dart SDK is published. But if no PR is filed to official images the by the next day, please do report it so we can fix it.
