### ISSUE TITLE
How to use ASAN to check Dart AOT + dynamic library (via FFI)?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#54193]
Hi thanks for the language! I am trying to add ASAN to flutter_rust_bridge for extra checks (though we have Valgrind already).

More specifically, the use case is that: Firstly, run `dart compile exe something.dart`. Then, execute that compiled binary with some dynamic / static library compiled from Rust.

I have tried https://github.com/dart-lang/sdk/wiki/Debugging-Dart-VM-with-AddressSanitizer#addresssanitizer to build a dart release with ASAN. The `out/ReleaseASANX64/dart` does look good, but the error happens when I want to compile:

```
out/ReleaseASANX64/dart compile exe ~/a.dart ~/a.out
Could not find dart-sdk/sdk/out/ReleaseASANX64/snapshots/gen_kernel_aot.dart.snapshot. Have you built the full Dart SDK?
```

In addition, it seems that by following that doc, I am building a Dart runtime that has ASAN, but I am not sure whether what *the AOT compiler generates* is with ASAN. In my case, I do not need the Dart JIT / Dart compiler / ... to have ASAN, but only need the binary compiled via `dart compile` to have ASAN support.

Thanks for any suggestions!

P.S. I do see https://github.com/dart-lang/sdk/wiki/Debugging-Dart-VM-with-AddressSanitizer#development says 

> AddressSanitizer works at the C++ language level, hence does not automatically know about code that Dart VM's JIT compiler generates, nor about low-level direct manipulation of the stack from C++ code.
Use the macro ASAN_UNPOISON(ptr, len) to explicitly inform ASan about a region of the stack that has been manipulated outside normal portable C++ code.

But I am not sure whether this means the AOT outputs have ASAN or not.

----

EDIT: Related (but in another repo): https://github.com/dart-lang/native/issues/840

**Comment by rmacnak-google** [comment]
The missing resource is related to running from `out/ReleaseASANX64/dart` instead of `out/ReleaseASANX64/dart-sdk/bin/dart`.

Using the sanitizers causes the runtime to be instrumented, but mostly does not cause the generated Dart code to be instrumented. There is enough instrumentation in the generated code to avoid false-positives for accesses from the runtime, but use of bad addresses, uninitialized memory, etc from Dart code through dart:ffi or external typed data will not trigger sanitizer warnings.

**Comment by fzyzcjy** [comment]
@rmacnak-google Thank you very much! So I guess I should the JIT mode for checking instead of AOT mode?

(Btw I see https://ci.chromium.org/ui/p/dart/builders/try/vm-aot-asan-linux-release-x64-try/2/overview and seems that Dart itself's CI is using AOT mode asan test, but I am not very sure what is that)

**Comment by dcharkes** [comment]
In addition to what Ryan wrote.

> In addition, it seems that by following that doc, I am building a Dart runtime that has ASAN, but I am not sure whether what _the AOT compiler generates_ is with ASAN. In my case, I do not need the Dart JIT / Dart compiler / ... to have ASAN, but only need the binary compiled via `dart compile` to have ASAN support.

The machine code we generate for the FFI has some extra instrumentation for sanitizers.
Yes, the compiler itself also has the sanitizers enabled.
We don't support cross-compiling from a non-instrumented SDK to a sanitizer instrumented aot snapshot.

> P.S. I do see https://github.com/dart-lang/sdk/wiki/Debugging-Dart-VM-with-AddressSanitizer#development says
> 
> > AddressSanitizer works at the C++ language level, hence does not automatically know about code that Dart VM's JIT compiler generates, nor about low-level direct manipulation of the stack from C++ code.
> > Use the macro ASAN_UNPOISON(ptr, len) to explicitly inform ASan about a region of the stack that has been manipulated outside normal portable C++ code.
> 
> But I am not sure whether this means the AOT outputs have ASAN or not.

The machine code we generate for the FFI has some extra instrumentation for sanitizers. I think the note above is mostly for VM engineers to add that extra instrumentation.

If you're interested in the nitty gritty details, for the FFI specifically we have things such as:

* Instrumenting outgoing arguments on FFI calls https://dart-review.googlesource.com/c/sdk/+/259102 https://dart-review.googlesource.com/c/sdk/+/329582
* Instrumenting writes via `Pointer`/`TypedData` to C memory  https://dart-review.googlesource.com/c/sdk/+/303360 https://dart-review.googlesource.com/c/sdk/+/327201

For ASAN specifically, we don't need something special, as via FFI you'd be using `malloc` / `free` from the C runtime already. Note that the C runtime included in the dartaotruntime must be ASAN instrumented for that to work. (As noted above everything is instrumented also the JIT compiler.)

> Btw I see https://ci.chromium.org/ui/p/dart/builders/try/vm-aot-asan-linux-release-x64-try/2/overview and seems that Dart itself's CI is using AOT mode asan test, but I am not very sure what is that

It compiles both the Dart SDK and the FFI test function dylibs used in the FFI tests with ASAN enabled. And has already caught many missing `free`s in FFI tests. 🤓  (A recent one: https://dart-review.googlesource.com/c/sdk/+/275260)

**Comment by fzyzcjy** [comment]
Thank you very much for the info!

By the way, I have already been setting up a (basic, JIT only) CI and test infra for flutter_rust_bridge: 

* https://github.com/fzyzcjy/dart_lang_ci/actions/ to build artifacts
* https://github.com/fzyzcjy/flutter_rust_bridge/blob/feat/11073/tools/frb_internal/lib/src/misc/dart_sanitizer_tester.dart (and the files it calls) for execution

And so far flutter_rust_bridge does not have any issues ;)

> It compiles both the Dart SDK and the FFI test function dylibs used in the FFI tests with ASAN enabled. And has already caught many missing frees in FFI tests. 🤓 (A recent one: [dart-review.googlesource.com/c/sdk/+/275260](https://dart-review.googlesource.com/c/sdk/+/275260))

I see 😆

**Comment by a-siva** [comment]
I presume the question has been answered so closing issue,
