### ISSUE TITLE
`dart compile exe` fails on armv7 build within Docker buildx `si_signo=Illegal instruction(4), si_code=2, si_addr=0x3ed8a1c8`

### ISSUE THREAD

**Issue by cpswan** [dart-lang/sdk#54198]
When building a trivial application ([dartshowplatform](https://github.com/atsign-company/at_dockerfiles/blob/trunk/dartshowplatform/showplatform.dart)) within a docker container using `docker buildx` for multi platform support the armv7 version fails with `si_signo=Illegal instruction(4), si_code=2, si_addr=0x3ed8a1c8`:

```
#24 [linux/arm/v7 build 4/4] RUN dart compile exe /app/showplatform.dart -o /app/dartshowplatform
#24 6.169 
#24 6.169 ===== CRASH =====
#24 6.169 si_signo=Illegal instruction(4), si_code=2, si_addr=0x3ed8a1c8
#24 6.242 Error: AOT compilation failed
#24 6.244 Generating AOT kernel dill failed!
#24 ERROR: process "/bin/sh -c dart compile exe /app/showplatform.dart -o /app/dartshowplatform" did not complete successfully: exit code: 64
```

The [full build logs](https://github.com/atsign-company/at_dockerfiles/actions/runs/7043453384/job/19176546183) that the snippet is taken from are available.

The same error appeared on two repeated runs.

The failure doesn't occur when building on armv7 hardware such as a Raspberry Pi 4 model B running 32bit Raspberry Pi OS (which presents as `armv7l` with `uname -m` and `armhf` with `dpkg --print-architecture`)

This seems like a slide back to the issues identified by @abasty at https://github.com/dart-lang/dart-docker/issues/11#issuecomment-867901079 which got fixed, as armv7 builds have been working inside Docker buildx since Nov 2021

I don't know whether the problem was introduced with 3.2.0 or 3.2.2, as the former was never tested in this way due to https://github.com/dart-lang/site-www/issues/5355

The last known working version was 3.1.5

* Dart version and tooling diagnostic info (`dart info`)
```
#### General info

- Dart 3.2.2 (stable) (Tue Nov 28 11:22:54 2023 +0000) on "linux_arm"
- on linux / Linux 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
- locale is en_GB.UTF-8
 ```
* Whether you are using Windows, macOS, or Linux (if applicable)
  * Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
  * NA

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by cpswan** [comment]
@bkonyi thanks for the suggestion. The good news is that it seemed to still work on armv7 hardware. Sadly the bad news is that it doesn't help with the QEMU environment of docker buildx:

```
#22 [linux/arm/v7 build 4/4] RUN dart compile exe --extra-gen-snapshot-options=--target_unknown_cpu   /app/showplatform.dart -o /app/dartshowplatform
#22 5.692 
#22 5.692 ===== CRASH =====
#22 5.692 si_signo=Illegal instruction(4), si_code=2, si_addr=0x3ed8a1c8
#22 5.736 Error: AOT compilation failed
#22 5.737 Generating AOT kernel dill failed!
#22 ERROR: process "/bin/sh -c dart compile exe --extra-gen-snapshot-options=--target_unknown_cpu   /app/showplatform.dart -o /app/dartshowplatform" did not complete successfully: exit code: 64
```

**Comment by rmacnak-google** [comment]
Oh, I missed that it's the compilation step itself, not the output. The thing that changed that triggered this would be the front-end snapshots switching to AOT. We'll need to fix the SDK build too.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/339104

**Comment by a-siva** [comment]
Closing this here, the cherry pick progress will be tracked in https://github.com/dart-lang/sdk/issues/54215
