### ISSUE TITLE
Storing `null` into typed data lists works

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#54195]
The tests
```
standalone/typed_data_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-weak-asserts-linux-release-x64
```

**Comment by mkustermann** [comment]
Probably https://github.com/dart-lang/sdk/commit/6249b7ed3402a5bcbecacd29370cc2169f71f8f7

**Comment by lrhn** [comment]
The `weak` mode tests might not be necessary any more. The VM should probably just refuse to compile in unsound mode entirely.

**Comment by a-siva** [comment]
> The `weak` mode tests might not be necessary any more. The VM should probably just refuse to compile in unsound mode entirely.

We have been told to hold off on the change to refuse compilation/execution in unsound mode until all the internal Flutter apps are migrated to be sound null safe.
