### ISSUE TITLE
Dart does not seem to understand `^` in powershell, while other langauges do, thus `dart pub add something:^1.2.3` does not work

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#54191]
Hi thanks for the language! I find a little bug when running my flutter_rust_bridge v2's CI because the `pub add` script fails:

Suppose we have these simple programs to print out args:

```
cat a.dart
void main(args) => print('$args');

cat a.py
import sys
print(sys.argv[1:])
```

Run them:

```
python a.py x^y z
['x^y', 'z']

dart a.dart x^y z
[xy, z] # NOTE this is wrong
# NOTE: On MacOS it is `[x^y, z]` which is correct
```

The `^` seems to be missing.

This makes `dart pub add something:^1.2.3` fail on windows (it wrongly interprets it as `something:1.2.3`, while works well on macos and windows.

**Comment by mraleph** [comment]
Are you using `dart` through Flutter SDK? 

I think `^` and `!` get swallowed by expansion process - though I think this was supposed to be fixed. See https://github.com/dart-lang/sdk/issues/46426 for context.

**Comment by fzyzcjy** [comment]
Yes, the one installed by flutter. Thanks for the information!

**Comment by mraleph** [comment]
Ok, if this is the one installed by flutter you should report the issue to Flutter folks.
