### ISSUE TITLE
What happens if `Dart_CObject_kExternalTypedData` is modified externally?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#54197]
Hi thanks for the language! I wonder what happens if `Dart_CObject_kExternalTypedData` is modified externally? For example:

```
// 1. In C, post an object
void* bytes = malloc(1000000);
Dart_PostCObject(Dart_Cobject..as_external_typed_data = the bytes);

// 2. In C, modify the bytes (we can ensure this happens before the data is deallocated, by utilizing `Dart_HandleFinalizer callback`
bytes[0] = 42;
```

What happens to the Dart code that reads/writes the Uint8List that is posted from C?

If it is undefined behavior, I hope (and can PR) to https://github.com/dart-lang/sdk/blob/54760c038262b1663bfa88e29b81379bfdb5495d/runtime/include/dart_native_api.h#L32 to mention this. Because currently it only says "ownership" is moved to dart vm, but this does not mean we cannot "borrow mutably" (rust term) and write to the data at the same time ;) In addition, I suspect this is not undefined behavior, because the finalizer `callback` will be called, and at least at that time we can touch and modify data (though useless).

If it is allowed, then we can do a lot of fancy hacky things. For example, we can even share memory between Dart isolates. This can be done by allocating a buffer in C, and then Dart_PostCObject to two isolates, and let those isolates read/write the Uint8Lists.

**Comment by a-siva** [comment]
It is going to depend on the memory ordering of the system on which you are running the code, Dart does not define a memory model and hence the behaviour could be undefined especially if there are multiple isolates executing the Dart code and the native modification happen on some random thread, the modified value may or maynot be seen by the Dart code running on these isolates. The native code making the modification would have to issue the apporpriate memory barrier instructions to ensure visibility of the changes.

**Comment by fzyzcjy** [comment]
@a-siva Thank you for the information! Then I guess things like this will work if we want to share memory between two isolates:

```
// C
void* bytes = malloc(1000000);
Dart_PostCObject(Dart_Cobject..as_external_typed_data = the bytes, target -> isolate A);
Dart_PostCObject(Dart_Cobject..as_external_typed_data = the bytes, target -> isolate B);

// Dart, isolate A
bytes[0] = 42;
call_C_function_which_calls_memory_barrier_things();
notify_isolate_B_there_is_new_data();

// Dart, isolate B, when notified
print(bytes[0]); // should see new data
```

In other words, if I understand correctly,

1. Modifying the memory already sent to Dart VM via as_external_typed_data is explicitly *allowed* (instead of forbidden, or undefined)
2. As long as I use proper synchronization primitives (call them in C / Rust / ...), the memory write is guaranteed to be visible to others

**Comment by a-siva** [comment]
No that won't work because Dart_PostCObject copies the native external array into Dart memory when writing the message to the isolate.

**Comment by a-siva** [comment]
I had initially assumed you were using some kind of ffi code to create the external object and sharing the native pointer among isolates, did not see your use of Dart_PostCObject.

**Comment by fzyzcjy** [comment]
Thanks for the reply! Hmm IMHO the doc of as_external_typed_data explicitly say it does not *copy* memory at all? it is as_typed_data that does the copy.
