### ISSUE TITLE
Is it a typo in ASAN doc?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#54204]
Hi, I wonder whether the place arrow points to is LSAN instead of ASAN?

![image](https://github.com/dart-lang/sdk/assets/5236035/a8a55765-f409-4138-b274-6092dbe7504c)

**Comment by mraleph** [comment]
No this is not a typo.

tldr we are using leak sanitizer on top of address sanitizer. Notice `detect_leaks=1` in the ASAN_OPTIONS string.

**Comment by fzyzcjy** [comment]
Oh I see, thank you very much!
