### ISSUE TITLE
How do you symbolicate Dart AOT-compiled binary? / How do you draw a Dart (FFI) flamegraph?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#54207]
Hi thanks for the language and SDK! I am trying to profile the code (across FFI boundary) and draw a flamegraph.

I did a simple experiment using https://github.com/flamegraph-rs/flamegraph, with AOT binary (`dart --enable-experiment=native-assets build`) and get something like:

<details>

![image](https://github.com/dart-lang/sdk/assets/5236035/86e7019d-2b41-4140-a60a-bad6d322da71)

</details>

As you can see, the Rust symbols are good (the ones in libfrb_example_pure_dart.dylib). However, most symbols are missing, which I guess are the symbols that should be in the Dart AOT binary.

Since profiling some Dart AOT code is surely a common need when developing Dart itself, and I cannot find doc about this, I wonder what do you do to symbolicate Dart AOT-compiled binary? Or, how do you profile and draw a Dart (FFI) flamegraph? Thanks for any suggestions!

P.S. Also no luck if using aot compile: `dart --enable-experiment=native-assets compile aot-snapshot`, `sudo flamegraph dartaotruntime benchmark/simple_benchmark.aot`

<details>

![image](https://github.com/dart-lang/sdk/assets/5236035/19f5dfb0-917f-4d8a-bc44-a7b0c7b02be5)

</details>

**Comment by mkustermann** [comment]
The `dart compile aot-snapshot` should produce an ELF file that has static symbols in it. When I build the SDK at `main` and run
```
% cat hello.dart
main() {
  while (true) {}
  print("hello");
}

% dart compile aot-snapshot hello.dart
Generated: /.../hello.aot

% perf record -g dartaotruntime hello.aot
...
<ctrl-c>
% perf report --no-children
-   99.99%  DartWorker       hello.aot             [.] main                                                                                                    ▒
   - main                                                                                                                                                      ◆
      - _Closure.call                                                                                                                                          ▒
        _delayEntrypointInvocation.<anonymous closure>                                                                                                         ▒
        _Closure.call                                                                                                                                          ▒
        _RawReceivePort._handleMessage                                                                                                                         ▒
        stub InvokeDartCode                                                                                                                                    ▒
        0x5616e3df5d32                                                                                                                                         ▒
        0x5616e3df74df                                                     
```

This won't work for `dart compile exe` because the produced executable ELF file has another ELF file embedded inside it (the app isn't statically linked together with the aot runtime).

**Comment by fzyzcjy** [comment]
Thank you very much! It successfully works on Linux. 

P.S. MacOS still does not work yet, checking what is going on (maybe dtrace system integrity protection problem)

```
(base) ➜  hello_dart dart compile aot-snapshot bin/hello_dart.dart              
Generated: /Users/tom/temp/hello_dart/bin/hello_dart.aot
(base) ➜  hello_dart sudo flamegraph -- ~/temp/dartaotruntime bin/hello_dart.aot                       
Password:
dtrace: system integrity protection is on, some features will not be available

dtrace: description 'profile-997 ' matched 1 probe
```

**Comment by fzyzcjy** [comment]
So, has anyone succeeded in profiling and getting symbols in MacOS before? Or, is there any ways to let `.aot` file generate symbols suitable for MacOS?

Thanks!

**Comment by mkustermann** [comment]
> So, has anyone succeeded in profiling and getting symbols in MacOS before? Or, is there any ways to let .aot file generate symbols suitable for MacOS?

The way to achieve this is to tell our AOT compiler to emit assembly and then compile that manually to a MachO file.

To avoid requiring users to have an assembler/compiler/linker to be installed, the `dart build` / `dart compile` tools use ELF on all platforms and there doesn't seem to be an option to change this behavior.

Though all tools are there. On linux I can do that with
```
% export DART_SDK=<path-to-dart-sdk>
% $DART_SDK/bin/dartaotruntime $DART_SDK/bin/snapshots/gen_kernel_aot.dart.snapshot --platform=$DART_SDK/lib/_internal/vm_platform_strong.dill --aot --tfa -o hello.dill hello.dart
% $DART_SDK/bin/utils/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=hello.S hello.dill
% perf record -g $DART_SDK/bin/dartaotruntime hello.so      
% perf report --no-children
```

=> On MacOS this should also work by using the mac compiler/linker to generate a `dylib` file

**Comment by fzyzcjy** [comment]
Thank you! I will try that assembly approach later.

**Comment by mkustermann** [comment]
Although one can kind of work around the issue manually, this is a valid feature request. Filed https://github.com/dart-lang/sdk/issues/54254 to track this.

**Comment by fzyzcjy** [comment]
Thank you!
