### ISSUE TITLE
[dart2wasm] very slow compilation to wasm

### ISSUE THREAD

**Issue by renlite** [dart-lang/sdk#54216]
Flutter 3.18.0-1.0.pre.19 • channel master
I compiled the strating app from ```flutter create```  with ```flutter build web --wasm --wasm-opt=none``` to get the fastest build.
Firt compilation takes about 25 s.
Second compilation takes about 18 s.
After minimal change in ```main.dart``` the compilation takes 18 s.
Compilation without ```--wasm-opt``` takes about 80 s.

1. Why is the compilation so slow?
2. Is there no IC?
3. Is canvaskit.wasm and skwasm.wasm compiled repeatedly? Why isn't it possible to reuse the compiled libs?
4. Is JS-code compiled in parallel for compatibility reasons? Can this be turned off?

I personaly don't need hot-reload after saving the code. I would prefer a fast IC (without tree-shaking, optimizations ans so on) with compilation time about under 6 s without all the "hot-relaod overhead".

**Comment by mkustermann** [comment]
@renlite `flutter build` is used for making production builds that can be deployed. Those builds perform whole-world program optimizations that are expensive (we want small & fast code for production builds after all).

For development users should use `flutter run` (which uses DDC with hot-restart (**) on web and VM JIT with hot-reload-mode for running natively). (**) DDC may obtain hot-reload functionality at some point.

For the short/medium term we have no plans to make a wasm-based development experience. So I'm going to close this issue.

(It should be sufficient to use `flutter run` during development and only use `flutter build --wasm` for deploying. There's small semantic differences between the two that we're in the process of ironing out atm).
