### ISSUE TITLE
[CP] Remove unused co19_2 directory

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#54228]
### Commit(s) to merge

be098f08e1df736331cbb7adf8c05637b599957b

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/339901

### Issue Description

The co19_2 directory was accidentally revived as a git submodule.

### What is the fix

Delete the incorrect submodule.

### Why cherry-pick

The submodule should not be there, and can cause unexpected side effects with tooling that doesn't expect submodules in the Dart SDK checkout.

### Risk

low

### Issue link(s)

N/A

**Comment by a-siva** [comment]
lgtm

**Comment by mit-mit** [comment]
@athomas is this still relevant?

**Comment by athomas** [comment]
No, forgot to close it.
