### ISSUE TITLE
DevTools should print messages to stderr instead of stdout

### ISSUE THREAD

**Issue by ntkme** [dart-lang/sdk#54227]
Currently when running with `--observe`, the message `The Dart VM service is listening on` and `The Dart DevTools debugger and profiler is available at:` are printed to stdout, thus polluting applications' stdout stream.

```
$ dart run --pause-isolates-on-start --observe main.dart

The Dart VM service is listening on http://127.0.0.1:8181/afZySiNbDPg=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/afZySiNbDPg=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2FafZySiNbDPg%3D%2Fws
```

For application like embedded `dart-sass` (`sass --embedded`) that uses a binary stdout stream, having a polluted stdout is painful. In order to run the DevTools I will have to consume exact two lines in UTF-8, and then convert the stream to binary mode.

In [ruby it is already pretty messy](https://github.com/ntkme/sass-embedded-host-ruby/blob/9bd0454da1e74f88f4f1d45975560dd5101687d3/lib/sass/compiler/connection.rb#L30-L43), and just imagine how to deal with the binary stdout stream polluted with plain text in an event driven language like node or dart itself.

In general, all debug related output should never be printed to stdout, and should go to stderr instead.

**Comment by devoncarew** [comment]
cc @bkonyi

**Comment by bkonyi** [comment]
Hi @ntkme, thanks for the feedback.

While I completely agree with your assessment, I don't think this is something we're going to be able to change. There's a lot of tooling that relies on scraping these URIs from stdout, so changing this to stderr would be a major breaking change.

**Comment by ntkme** [comment]
> There's a lot of tooling that relies on scraping these URIs from stdout

That's what I thought. Aside from 3rd party tools, when I looked at this code base itself I found too many internal code and tests relying on this behavior.

**Comment by a-siva** [comment]
Based on comments above it looks like this is something we will be able to change without undertaking a major breaking change. Marking issue as not planned..
