### ISSUE TITLE
developer.log not working as expected.

### ISSUE THREAD

**Issue by suhail600** [dart-lang/sdk#54249]
https://github.com/flutter/flutter/issues/139131#issue-2014193589

The issue reported on the Flutter repository is about the developer.log functionality not working as expected after upgrading to version 3.16.0. The developer.log should capture and display log messages as it did in version 3.10.5 and before, but it is not logging messages as expected in the new version. The issue includes a code sample and the Flutter Doctor output. The problem is related to the developer.log function from the dart:developer package, which is used for logging in Flutter apps. The issue is closed but unresolved as it is handled by dart repo. The developer.log function is important for debugging and displaying log messages in Flutter apps, and its malfunctioning can affect the development and debugging process.

**Comment by lrhn** [comment]
How do you run the code?

When I run the linked program in VSCode using "Debug", the text is printed.
When I run it using "Run", no text is printed.

That suggests that the `log` method is only enabled in debug/development mode, which is reasonable for something from the `dart:developer` library. That library is not intended for use in production.

**Comment by suhail600** [comment]
> How do you run the code?
> 
> When I run the linked program in VSCode using "Debug", the text is printed. When I run it using "Run", no text is printed.
> 
> That suggests that the `log` method is only enabled in debug/development mode, which is reasonable for something from the `dart:developer` library. That library is not intended for use in production.
> 
> (A [very quick check](https://github.com/dart-lang/sdk/commit/aaa0867567f19de61a205b4cce0808cdc102f349#diff-f1d2a5c65508a78c0aac72d7d81f5ad4da594b356d2f9cce85b3044eda894821L44) suggests that the VM has ignored `log` in production mode for about 8 years. Has something changed in how Flutter compiles the VM, or how VSCode integration launches the program?)

its working now, tested on multiple systems ,  its working fine now i have not updated the dart till now , somehow its working as expected.
