### ISSUE TITLE
[gardening][ubsan] vm/dart/heapsnapshot_cli_test Crash

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54243]
Edit: locally failing far back. And AOT is flaky.

There are new test failures on [Parser: fix error reporting when pattern assignment declares a variable without a name....[tests] Remove now unused co19_2 directory](https://github.com/dart-lang/sdk/compare/be098f08e1df736331cbb7adf8c05637b599957b~...6fcd15c1aa024bd42056487374a146be492277a2).

The tests
```
vm/dart/heapsnapshot_cli_test Crash (expected Pass)
```
are failing on configurations
```
vm-aot-ubsan-linux-release-x64
vm-ubsan-linux-release-x64
```

Log:

```
stderr:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=SEGV_MAPERR(1), si_addr=0x7fad862c4ff8
version=3.3.0-edge.6fcd15c1aa024bd42056487374a146be492277a2 (main) (Mon Dec 4 22:45:00 2023 +0000) on "linux_x64"
pid=200931, thread=200931, isolate_group=main(0x5620ff7998c0), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=5620fd54c160, vm_instructions=5620fd54c160
fp=7ffcb35468a0, sp=7ffcb3546870, pc=5620fe174145
  pc 0x00005620fe174145 fp 0x00007ffcb35468a0 dart::FinalizablePersistentHandle::Finalize+0x7d
  pc 0x00005620fd91c7d5 fp 0x00007ffcb35468f0 dart::Handles<5, 64, 0>::HandlesBlock::Visit+0x95
  pc 0x00005620fd91c701 fp 0x00007ffcb3546930 dart::Handles<5, 64, 0>::Visit+0x91
  pc 0x00005620fd9146bd fp 0x00007ffcb3546980 dart::Isolate::LowLevelCleanup+0x1d5
  pc 0x00005620fd916b8e fp 0x00007ffcb3546ec0 dart::Isolate::Shutdown+0x1fe
  pc 0x00005620fe179ff8 fp 0x00007ffcb3547400 Dart_ShutdownIsolate+0x1c0
  pc 0x00005620fd4dbe89 fp 0x00007ffcb35474a0 dart::bin::RunMainIsolate+0x331
  pc 0x00005620fd4dd33d fp 0x00007ffcb35475e0 dart::bin::main+0xa25
  pc 0x00005620fd4dbb15 fp 0x00007ffcb3547600 main+0xd
-- End of DumpStackTrace

--- Re-run this test:
python3 tools/test.py -n vm-ubsan-linux-release-x64 vm/dart/heapsnapshot_cli_test
```

~~I suspect b91dcdf422ca15e5f5e1fcc760261a537664f9d5 which changes mapping.~~ Nope, also reproduces on 7abab94d97f9c6fa7b743457882d2d825b699ff4.

I'll do a bisection locally.

```
tools/bisect.dart \
-Dend=be098f08e1df736331cbb7adf8c05637b599957b \
-Dstart=6fcd15c1aa024bd42056487374a146be492277a2 \
-Dtest_command="python3 tools/build.py -mrelease --sanitizer=ubsan run_vm_tests create_platform_sdk" \
-Dtest_command="python3 tools/test.py --build -n vm-ubsan-linux-release-x64 vm/dart/heapsnapshot_cli_test" \
-Dfailure_string="SEGV_MAPERR"
```

**Comment by dcharkes** [comment]
This failure reproduces on earlier commits as well.

Commit range b1620d1ba05...6fcd15c1aa024bd42056487374a146be492277a2.
Ensuring SDK repo in /usr/local/google/home/dacoharkes/dart-sdk/sdk/.
Ensuring failure reproduces on 6fcd15c1aa024bd42056487374a146be492277a2.
Commit 6fcd15c1aa024bd42056487374a146be492277a2, reproduces failure.
Ensuring failure does not reproduce on b1620d1ba05.
Commit b1620d1ba05, reproduces failure.

**Comment by dcharkes** [comment]
@rmacnak-google I don't know why the failure only popped up on our CI now, but it seems that https://github.com/dart-lang/sdk/commit/ef89de9dc1dcf55be2dfaa9658916806699554ac from 3 weeks ago caused this.

**Comment by rmacnak-google** [comment]
Prior to ef89de9dc1dcf55be2dfaa9658916806699554ac, the same crash would not include "SEGV_MAPERR" in the output, only si_code=1. "Segmentation fault" would still be present before that though.

**Comment by dcharkes** [comment]
> Prior to [ef89de9](https://github.com/dart-lang/sdk/commit/ef89de9dc1dcf55be2dfaa9658916806699554ac), the same crash would not include "SEGV_MAPERR" in the output, only si_code=1. "Segmentation fault" would still be present before that though.

So much for my bisection script smartness. 😆

**Comment by dcharkes** [comment]
Do we maybe get the UBSAN from depot tools instead of DEPS? That could explain why it recently started failing, but now fails locally for older commits.

**Comment by rmacnak-google** [comment]
UBSAN should be coming from Clang and only be affected by Clang rolls.

The jumps near the faulting load are for something to report a type mismatch, so I think UBSAN is crashing trying to load type information for a function pointer.

**Comment by rmacnak-google** [comment]
Possibly this is the finalizer from pkg:mmap use of Dart_NewExternalTypedDataWithFinalizerDart. The finalizer was JIT'd by pkg:mmap, and doesn't have UBSAN type information.

**Comment by a-siva** [comment]
@rmacnak-google can this be closed ?
