### ISSUE TITLE
`// ignore: foo (bar)` doesn't ignore `foo`

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#54247]
It appears that we don't treat a space character as a delimiter ending an `ignore` directive, which makes this intuitively correct code:

```dart
  // ignore: something_or_other (because of this and that)
```

...not ignore `something_or_other`.

**Comment by srawlins** [comment]
It seems like it would be super intuitive to consider whitespace a delimiter.

**Comment by pq** [comment]
> It seems like it would be super intuitive to consider whitespace a delimiter.

I agree.

It'd also be interesting to consider a new diagnostic that flags malformed `ignore`s.

**Comment by pq** [comment]
.fyi @bwilkerson
