### ISSUE TITLE
Extension type methods and mirrors?

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#54266]
I initially tried mimicking the extension member support in mirrors for extension type member support in https://dart-review.googlesource.com/c/sdk/+/339960/1 but it failed and I gave up.
Someone (who knows something about mirrors?) should probably figure out if a change is actually needed and if so make it.

/cc @alexmarkov

**Comment by alexmarkov** [comment]
I'm not sure dart:mirrors support for extension types would be useful, but having a minimal support won't hurt. https://dart-review.googlesource.com/c/sdk/+/340284 adds dart:mirrors support for extension type members similarly to extension methods. This includes `MethodMirror.isExtensionTypeMember` and `VariableMirror.isExtensionTypeMember` getters.

**Comment by a-siva** [comment]
@alexmarkov should we really be providing this support.
`dart:mirrors `is an unsupported library and we don't want to make changes to it or adjust it for a new language features.
My inclination would be to close this issue as 'not planned'
