### ISSUE TITLE
[analyzer] `withNullability` drops `alias` from `RecordTypeImpl`

### ISSUE THREAD

**Issue by dnys1** [dart-lang/sdk#54260]
In the following example, we create a typedef'd record type. Upon calling `withNullability` on the record type, the record's `alias` is lost.

```dart
import 'package:analyzer/dart/element/nullability_suffix.dart';
import 'package:analyzer/src/dart/element/element.dart';
import 'package:analyzer/src/dart/element/type.dart';

void main() {
  // typedef Empty = ();
  final recordType = RecordTypeImpl(
    positionalFields: [],
    namedFields: [],
    nullabilitySuffix: NullabilitySuffix.none,
    alias: InstantiatedTypeAliasElementImpl(
      element: TypeAliasElementImpl('Empty', 0),
      typeArguments: [],
    ),
  );
  final nullableRecordType =
      recordType.withNullability(NullabilitySuffix.question);
  print(nullableRecordType.alias); // null
}
```

Browsing the source code, this appears to be an accident, but I could be wrong. Notice how in the `withNullability` implementation of `FunctionTypeImpl`, the `alias` is passed:

https://github.com/dart-lang/sdk/blob/30c5a535fb4cb1206fb8aece3583bc3d32d4ca0b/pkg/analyzer/lib/src/dart/element/type.dart#L286-L296

But for `RecordTypeImpl` (and a few others), it's not:

https://github.com/dart-lang/sdk/blob/30c5a535fb4cb1206fb8aece3583bc3d32d4ca0b/pkg/analyzer/lib/src/dart/element/type.dart#L1196-L1207

**Comment by pq** [comment]
@scheglov?

**Comment by scheglov** [comment]
@dnys1 Thank you for detailed report. I almost expected to see the fix CL from you at the end :-)
You are right, it was my oversight.
https://dart-review.googlesource.com/c/sdk/+/340383 should fix it.

**Comment by dnys1** [comment]
Thanks for the quick fix, @scheglov! I'd be happy to take a stab at contributing in the future 😄 

I was a bit unsure about how this would be tested, so your PR helps me understand that better. Were the updates to `element_test` done manually by running the test and copying over the correct text?

Thanks again!

**Comment by scheglov** [comment]
In this case - yes, I copied results manually.

When we have to do more wide changes, I turn auto-updating https://github.com/dart-lang/sdk/blob/be6890e344b45c07baed4e348e2c5cfd228596c7/pkg/analyzer/test/src/dart/resolution/node_text_expectations.dart#L22 to `true`, and review the diff.

**Comment by dnys1** [comment]
Makes sense, thanks!
