### ISSUE TITLE
How can I invoke a callback from native code using ffi?

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#54276]
It looks like `Dart_Invoke` is conspicuously missing from `dart_api_dl.h`.

In my use case, I know that I am on the correct thread and would like to call back into Dart code from C code.

**Comment by johnmccutchan** [comment]
@bdero @chinmaygarde FYI

**Comment by liamappelbe** [comment]
Since you know you're on the correct thread, you can use [`NativeCallable.isolateLocal`](https://api.dart.dev/stable/3.2.3/dart-ffi/NativeCallable/NativeCallable.isolateLocal.html). On older SDKs you can use [`Pointer.fromFunction`](https://api.dart.dev/stable/3.2.3/dart-ffi/Pointer/fromFunction.html).

**Comment by mkustermann** [comment]
> In my use case, I know that I am on the correct thread and would like to call back into Dart code from C code.

@liamappelbe has answered this. You can create callback pointers in Dart (using `Pointer.fromFunction` or `NativeCallable.isolateLocal`), pass them to C where they can be invoked.

**Comment by johnmccutchan** [comment]
Yes, thanks for the context! One last question: Where can I find examples of its usage including passing parameters and return values?

**Comment by dcharkes** [comment]
https://api.dart.dev/stable/3.2.3/dart-ffi/NativeCallable/NativeCallable.isolateLocal.html does not have an example in the documentation. cc @liamappelbe 

https://api.dart.dev/stable/3.2.3/dart-ffi/NativeCallable/NativeCallable.listener.html has an example without return (as it's async).

Our tests contain examples: https://github.com/dart-lang/sdk/blob/main/tests/ffi/isolate_local_function_callbacks_test.dart
