### ISSUE TITLE
[CP] Deprecate avoid_unstable_final_fields

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#54278]
### Commit(s) to merge

https://dart-review.git.corp.google.com/c/sdk/+/340285

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.git.corp.google.com/c/sdk/+/340385

### Issue Description

The lint rule `avoid_unstable_final_fields` is incomplete and will be removed rather than being finished. Unfortunately, it had been erroneously marked as `stable`, so it will appear to users of the beta as if the rule is usable, which it isn't.

### What is the fix

Rather than attempt to remove the rule from the beta (a more invasive change) we are marking it as `deprecated` to send a clear signal to users that they should not use it.

### Why cherry-pick

If we don't cherry pick this change then beta users might start using the lint despite the fact that it isn't ready for production and will be removed in the next stable build.

### Risk

low

### Issue link(s)

There was no issue created.

**Comment by itsjustkevin** [comment]
@srawlins could you take a look at this cherry-pick request?

**Comment by srawlins** [comment]
+1; super low risk, and will avoid a lot of confusion and complaints.

**Comment by itsjustkevin** [comment]
@bwilkerson please feel free to merge this CL.
