### ISSUE TITLE
vm/dart/in_memory_elf_test is slow on windows arm64 bot vm-aot-win-debug-arm64 purple

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#54275]
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8762537846753136625/+/u/deflaking/vm_tests/stdout)

vm/dart/in_memory_elf_test is slow, causing vm-aot-win-debug-arm64 to turn purple

**Comment by alexmarkov** [comment]
Still happening: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8762286007168608209/+/u/deflaking/vm_tests/stdout
