### ISSUE TITLE
Make `dart compile wasm` support `--delete-tostring-package-uri` invoking existing `ToStringTransformer`

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#54280]
We should add `dart compile wasm` support for the `ToStringTransformer`. The frontend server accepts `--delete-tostring-package-uri` when compiling to kernel. In g3 build rules flutter passes `dart:ui` and `package:flutter` - which causes the `toString()` method bodies to be replaced with `super.toString()`.

See [kernel_front_end.dart](https://github.com/dart-lang/sdk/blob/d27b887fecb5c7e7060d9/pkg/vm/lib/kernel_front_end.dart#L154)

/cc @osa1 @dnfield

**Comment by dnfield** [comment]
Many of the types in `sdk/lib/_internal/wasm/lib/type.dart` have toString implementations that may be expensive as well.

It'd be really nice to have some tooling to inspect the sizes of these. So far it looks like existing tooling for wasm to do this is abandonware that doesn't know how to get information out of our WasmGC modules.

**Comment by mkustermann** [comment]
> It'd be really nice to have some tooling to inspect the sizes of these. So far it looks like existing tooling for wasm to do this is abandonware that doesn't know how to get information out of our WasmGC modules.

We've discussed a bit what kind of tooling we'd want. What makes this a little difficult is that `dart2wasm` is outputting unoptimized code. So even if we make it print detailed information what retains what, then it doesn't help so much because binaryen / `wasm-opt` may completely change sizes of functions, etc.

**Comment by mkustermann** [comment]
> > but the RTT stringification is something that cannot removed.

> I'd love to disprove that. It's not going to be easy,

Absolutely. Have been advocating for this for years, see https://github.com/dart-lang/sdk/issues/48901
All I'm saying is, we have to support it *at this moment* - possibly we can remove guarantees around it in the future.
