### ISSUE TITLE
How to call Dart_Null from ffi?

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#54296]
I've imported dart_api_dl, etc into my project and can successfully call functions like `Dart_NewWeakPersistentHandle_DL`. 

However, I don't see `Dart_Null_DL`, how should I create a Null handle?

**Comment by mkustermann** [comment]
@dcharkes I think john is looking for `Dart_Null()` which returns a handle representing the `null` object, not `Dart_IsNull()` that tests whether an object is `null`.

**Comment by dcharkes** [comment]
Oh, I missed that.

@johnmccutchan If you can do an FFI call, you can pass a `null` into a `Handle`, then you'll have a `Dart_Null()`.

We could add it to the dl list as well, feel free to make a PR, I don't see any risk in adding it.

**Comment by mraleph** [comment]
@johnmccutchan do you have some doc about what you are trying to achieve with FFI?

**Comment by johnmccutchan** [comment]
@dcharkes I'll put together a PR that exposes Dart_Null() in dart_api_dl. It'll be a good refresher exercise for me to land something in dart-lang/sdk :)

**Comment by dcharkes** [comment]
> @mraleph No document but I'll try and describe it here. I would definitely appreciate any feedback on how I'm holding dart:ffi.

I guess that's a bit beyond the point of this GitHub issue, but here we go.

> I'm wrapping the [Bullet Physics Engine](https://pybullet.org/wordpress/) so it is usable from Dart.
> 
> Bullet is a C++ project so I've been working on a small C interface on top. You can see the C interface here: [flutter_bullet.h](https://github.com/johnmccutchan/flutter_bullet/blob/main/native/flutter_bullet.h) and [flutter_bullet.cc](https://github.com/johnmccutchan/flutter_bullet/blob/main/native/flutter_bullet.cc). I am utilizing `ffigen` to produce the low level Dart bindings (these are not exposed to the user of my library).
> 
> I'm then wrapping those low level Dart bindings with classes I expect developers to use Some of the the Dart code is [world.dart](https://github.com/johnmccutchan/flutter_bullet/blob/main/lib/src/world.dart) and [collidable.dart](https://github.com/johnmccutchan/flutter_bullet/blob/main/lib/src/collidable.dart) -- you can find the rest in the same directory as those two files.
> 
> Some issues that came up for me in doing this work:
> 
> * I need bi-directional references between the C++ RigidBody object and the Dart RigidBody wrapper.

Yes, this a pattern we've seen more. The flutter engine uses a similar pattern for a bidirectional mapping between C++ and Dart objects in `dart:ui`s implementation.

> I need this to support things like "Shoot a ray into the world and give me the RigidBodies I hit", the actual ray casting is done in C++ and I need to be able to map back to the Dart object. I ended up going with this design: my Dart RigidBody implements ffi.Finalizable and is the owner of the C++ RigidBody. The C++ RigidBody holds a weak reference back to the Dart RigidBody so I can map it back before invoking the Dart callback that the user has provided.

Yep, weak references are a good way to break the cycle.

> * When the user does a ray cast into the world I need to be able to invoke their callback for each object that is hit by the ray. In Bullet this is guaranteed to be called on the Isolate's thread so I'm using ffi.NativeCallable<>.isolateLocal [example](https://github.com/johnmccutchan/flutter_bullet/blob/main/lib/src/world.dart#L79C40-L79C40).
> 
> Both seem to be working fine for me now but I would appreciate any expert advice on how I'm holding everything together now before I start to expand the amount of code I've wrapped.

This sounds like the right thing to do. Maybe @mraleph has some more to say about this.

> One issue I haven't investigated but am concerned about is distribution of my pub package and build system support. Bullet is a C++ project that uses cmake to build itself into a set of static libraries. I've added a dynamic library target that includes my C shim code. I don't want the user to have to deal with these details, that is, I want someone to be able to just add a pub dependency and have `flutter run` do the right things for building everything based on the target chosen by flutter run. This isn't blocking me right now as I just have a simple shell script that does everything for me in my local environment.

The native assets feature (https://github.com/flutter/flutter/issues/129757) should help with this. If you don't want the user to deal with any native code or native toolchains at all, then you should precompile the dynamic libraries and download them from a CDN during `build.dart`.

Alternatively, if you do want to compile the native code on the users machine, your `build.dart` should invoke the `cmake` on the users' system and complain if cmake cannot be found.

**Comment by johnmccutchan** [comment]
@dcharkes https://dart-review.googlesource.com/c/sdk/+/341061
