### ISSUE TITLE
The type 'IntPtr Function()' must be a subtype of 'IntPtr Function()' for 'lookupFunction'.

### ISSUE THREAD

**Issue by lpSharif** [dart-lang/sdk#54298]
```dart
class User32 {
  static final ffi.DynamicLibrary user32 = ffi.DynamicLibrary.open('user32.dll');

  static ffi.IntPtr GetForegroundWindow() {
    return user32.lookupFunction<ffi.IntPtr Function(), ffi.IntPtr Function()>('GetForegroundWindow')();
  }
}
``` 
This shows `The type 'IntPtr Function()' must be a subtype of 'IntPtr Function()' for 'lookupFunction'.`
Any solution please?

**Comment by halildurmus** [comment]
The `lookupFunction`'s second type argument should represent the Dart function signature for the corresponding Win32 function. For example, considering that `GetForegroundWindow` returns an `IntPtr`, its Dart signature would be `int`:
```dart
static int GetForegroundWindow() {
  return user32.lookupFunction<IntPtr Function(), int Function()>(
      'GetForegroundWindow')();
}
```

Creating these function bindings manually can be error-prone. An easier alternative is to use the [win32](https://pub.dev/packages/win32) package, which provides access to some of the most common Win32 APIs, such as `GetForegroundWindow`. 

Here's how you can use it:
```dart
import 'package:win32/win32.dart';

void main() {
  final handle = GetForegroundWindow();
  // Do something with that handle
}
```

**Comment by lpSharif** [comment]
It was a big help. Thanks a lot. This suggestion also helped me to solve couple of other issues too.
