### ISSUE TITLE
`NativeCallable.isolateLocal` claims to not keep isolates alive, but it does

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#54294]
The documentation of `NaticeCallable.isolateLocal` explains that:

> This callback must be [close](https://api.dart.dev/stable/3.2.3/dart-ffi/NativeCallable/close.html)d when it is no longer needed, but it will not keep its [Isolate](https://api.dart.dev/stable/3.2.3/dart-isolate/Isolate-class.html) alive. After the isolate is terminated, or [NativeCallable.close](https://api.dart.dev/stable/3.2.3/dart-ffi/NativeCallable/close.html) is called, invoking the [nativeFunction](https://api.dart.dev/stable/3.2.3/dart-ffi/NativeCallable/nativeFunction.html) from native code will cause undefined behavior.

On me, this left the impression that forgetting to call `close` may leak memory but would still shut down isolates. And yet, this Dart script terminates:

```dart
import 'dart:ffi';

void main() async {
  final x = NativeCallable<Int32 Function()>.isolateLocal(() => 3,
      exceptionalReturn: 3);
  x.close();
}
```

And this one doesn't:

```dart
import 'dart:ffi';

void main() async {
  final x = NativeCallable<Int32 Function()>.isolateLocal(() => 3,
      exceptionalReturn: 3);
}
```

Tested with `Dart SDK version: 3.2.3 (stable)`.

**Comment by mraleph** [comment]
@liamappelbe can you take a look?

**Comment by liamappelbe** [comment]
This is just a mistake in the documentation. The initial version of `NativeCallable.isolateLocal` I wrote didn't keep the owner isolate alive by default (for consistency with `Pointer.fromFunction`), but during review we decided to instead make it consistent with `NativeCallable.listener` and keep the isolate alive. Looks like I forgot to update the documentation when I switched it over. I'll send out a fix.

You can control this behaviour by setting [`NativeCallable.keepIsolateAlive`](https://api.dart.dev/stable/3.2.2/dart-ffi/NativeCallable/keepIsolateAlive.html). In any case, these callbacks are all cleaned up when the isolate shuts down, so won't leak memory regardless of how you set this flag.
