### ISSUE TITLE
Field of type `ExtensionType?` cannot be assigned `null` during const evaluation

### ISSUE THREAD

**Issue by ecstatic-morse** [dart-lang/sdk#54302]
[dartpad](https://dartpad.dev/?channel=master&id=7eb4cba1572e3873e92e58555aa945bd)

```dart
extension type Id(int id) {}

class MaybeId {
  final Id? value;
  const MaybeId.none() : value = null;
}

const MaybeId no = MaybeId.none(); // line 8
```

On the latest master with `--enable-experiment=inline-class`, this code gives the following error:

```
line 8 • Evaluation of this constant expression throws an exception.
The exception is 'In a const constructor, a value of type 'Null' can't be assigned to the field 'value', which has type 'Id?'.' and occurs here.
```

It will, however, run successfully (at least in the javascript runtime).

**Comment by eernstg** [comment]
That's right, `Null` is assignable to `T?` for any type `T`, including extension types.

**Comment by kallentu** [comment]
cc @scheglov 
I think this has to do with type erasure with the constant evaluator.

**Comment by lrhn** [comment]
Concrete example code that fails with this. (Written independently, not to hit this issue, abbreviated.)
```dart
typedef Opt<T> = Some<T>?;
extension type const Some<T>._(({T value}) _) {
  const Some(T value) : this._((value: value));
  T get value => _.value;
}
const Opt<Never> none = null;
void main() {
  var rnd = DateTime.now().millisecondsSinceEpoch.isEven;
  var maybeValue = rnd ? none : Some(42);
  print(switch (maybeValue) {
    Some(: var value) => "Value: $value",
    none => "No value",
  });
}
```
Gives error on the `none = null;` initialization
(And, in current DartPad, a warning that a `Some<int>` pattern can't match a `Some<int>?` value.)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/343580
