### ISSUE TITLE
`fetch dart` fails for Python version 3.12.0 due to imp module

### ISSUE THREAD

**Issue by galacticalex** [dart-lang/sdk#54306]
## Situation

I'm building the sdk on Fedora by following the wiki instructions (which, until now, was working well by the way).

But Fedora 39 packages Python **3.12.0** by default (Debian stable currently uses **3.11.2**).

## Problem 

When running `fetch dart` the setup fails due to the use of the Python module **imp** which has been [deprecated as of 3.12.0](https://docs.python.org/3.12/whatsnew/3.12.html#imp). 

The file that caused the issue was [tools/utils.py](https://github.com/dart-lang/sdk/blob/main/tools/utils.py#L14), but there are a few others which will cause the same issue (see attachment below).

Here is the console output of `fetch dart` failing: [console_output.txt](https://github.com/dart-lang/sdk/files/13637993/console_output.txt)
And a `grep` of the repo for **imp** usage: [grep_import_imp.txt](https://github.com/dart-lang/sdk/files/13638013/grep_import_imp.txt)

## Fix

As a temporary fix, running `fetch dart` within a **3.11** virtual environment (created with `python3.11 -m venv ...`) resolves the issue. 

A permanent fix is provided in the Python docs (see link above).

As you will run into this, I wanted to give you a heads-up.

Cheers 

~ Alex

**Comment by rmacnak-google** [comment]
`fetch` comes from depot_tools, which uses the Chromium issue tracker. See https://bugs.chromium.org/p/chromium/issues/detail?id=1487454

**Comment by athomas** [comment]
Fetching and building with python 3.12 works now. There are some remaining syntax warnings that will be fixed by https://dart-review.googlesource.com/c/sdk/+/346022.
