### ISSUE TITLE
evaluate where we call `workspace.findPackageFor(file)` and seek improvements

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#54310]

**Comment by pq** [comment]
I'm actually not seeing the opportunities I expected here.

@scheglov: can you recall what motivated this? (I think I was inspired by a conversation we had...) 🤔

**Comment by scheglov** [comment]
I also don't remember :-(

**Comment by pq** [comment]
No worries. We can always re-open. Thanks!
