### ISSUE TITLE
[ddc] Async return type `FutureOr<Object>` returns `Future<dynamic>`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54318]
This is the DDC specific issue for the behavior reported in #54311, which has the details  (some details here: https://github.com/dart-lang/sdk/issues/54311#issuecomment-1851558442).

The main point is that we can have an async function with declared return type `FutureOr<Object>` that actually returns a `Future<dynamic>` (it should return a `Future<Object>`). The Kernel code which is generated for the example program seems to be [correct](https://github.com/dart-lang/sdk/issues/54311#issuecomment-1852027259), so the issue seems to be caused by the processing of this Kernel code in backends.

**Comment by eernstg** [comment]
This issue might have been resolved already:

```dart
import 'dart:async';

void main() async {
  final value = await fn();
  print(value); // Correct: '42', wrong: 'Instance of Future<dynamic>'.
}

FutureOr<Object> fn() async {
  return Future<Object>.value(42);
}
```

DartPad (any channel) prints '42'.

@sigmundch or @nshahan, can we close this issue now? (which would also allow us to close https://github.com/dart-lang/sdk/issues/54311)

**Comment by sigmundch** [comment]
@eernstg thanks for the follow up. I was chatting with @nshahan about it this week and I think it's fair to close it.

We don't recall doing any specific changes for it, but It's possible that we missed the issue it was first filed and that this was always working in DDC. I just tried with a Dart 3.2.0 SDK, which existed prior to this issue, and it was also printing 42 then.
