### ISSUE TITLE
migrate away from (singleton) `contextRoot.optionsFile` accesses

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#54312]
~~TL;DR it is no longer surely just one options file and could be many.~~

**EDIT**: wrong assumption. See discussion below.

**Comment by pq** [comment]
I may have misunderstood this. Looking at the `ContextLocator.locateRoots` docs, it appears the intention is to allow for a way to override options files discovered in context creation.

```
  /// If an [optionsFile] is specified, then it is assumed to be the path to the
  /// `analysis_options.yaml` file that should be used in place of the ones that
  /// would be found by looking in the directories containing the context roots.
```

@bwilkerson, @scheglov: is that accurate?

If so maybe `ContextRoot`s should still have such a field (though possibly renamed) that handles the case where we want to be able to override an discovered analysis options. 🤔 

WDYT?

**Comment by scheglov** [comment]
It depends on design decisions, but most probably the field is not necessary.
We have, theoretically `AnalysisOptionsProvider` interface.
Usually we use the implementation that walks the file system up.
And when we have override, it could be a different implementation of this interface.

**Comment by bwilkerson** [comment]
I don't know whether it's still supported, but it used to be possible to run `dartanalyzer` with a command-line argument that told it which analysis options file to use. After a quick glance at the code it looks like that option might have been removed, but I'm not 100% confident that I didn't miss something.

That's the functionality that the `optionsFile` parameter was intended to support.

**Comment by pq** [comment]
It's definitely still used that way by `pub`.


```dart

ContextBuilder()
            .createContext(
              contextRoot: ContextLocator().locateRoots(
                includedPaths: [p.absolute(p.normalize(packagePath))],
                optionsFile:
                    // We don't want to take 'analysis_options.yaml' files into
                    // account. So we replace it with an empty file.
                    Platform.isWindows ? r'C:\NUL' : '/dev/null',
              ).first,

```

(in `lib/src/dart.dart`).

In any event, I think there are two things going on here.

1. I was mistaken in thinking that `optionsFile` in a context root should evolve to support potentially multiple options -- seeing at an options override clarifies things. At the same time,
2. There may be better ways to support these desired semantics.

For the purposes of decoupling analysis options from one context, I don't think we need to change the current API (though I do think it could do with some clarifying documentation).

(Oh and fyi @keertip who may find this conversation interesting.)

**Comment by pq** [comment]
Closing as WAI.
