### ISSUE TITLE
Implement implicit call method tear-offs with extension typed receivers

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54339]
This implementation issue is associated with the proposal in https://github.com/dart-lang/language/issues/3467, that is, the proposal to support implicit `call` method tear-offs for receivers whose static type is an extension type.

Consider the following example:

```dart
extension type Ext(Function it) {
  String call() => 'call from Ext: ${it()}';
}

class C {
  String call() => 'call from C';
}

class D {
  Function get fgetter => Ext(C()); // (1)
}

void main() {
  var d = D();
  print(d.fgetter());
}
```

At (1) in this example, we evaluate the expression `Ext(C())` with a context type of `Function`. Following the treatment of a receiver of an interface type that has a method named `call`, this expression should be implicitly transformed into `Ext(C()).call`, and the resulting program would then be type correct.

(Of course, `C()` will be subject to the same transformation because that's the case that we already support, yielding `Ext(C().call).call`.)

This issue serves as a request to implement this feature. It may be implemented in the analyzer already, but the CFE reports an error when `Ext(...)` is encountered with context type `Function`. I'll create subtask issues for both, and then the analyzer subtask may be trivial.

Subtasks:
- https://github.com/dart-lang/sdk/issues/54340
- https://github.com/dart-lang/sdk/issues/54341

**Comment by johnniwinther** [comment]
Yes

**Comment by eernstg** [comment]
Done.
