### ISSUE TITLE
"Convert to named arguments" fix should not include names already used by existing arguments

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#54336]
Moving from https://github.com/Dart-Code/Dart-Code/issues/4895.. the "convert to named arguments" fix can insert argument names that are already used, fixing the original issue and introducing a different one:

https://github.com/Dart-Code/Dart-Code/assets/1078012/ec9a3b3f-4240-4593-bff9-dba28adc5002

**Comment by TheComputerM** [comment]
What should be the correct behavior, should it not display the quick fix option at all or ...?

**Comment by DanTup** [comment]
I think probably it shouldn't show up unless it can assign an unused parameter name. I think it already only shows up if it can map all arguments onto parameters, but perhaps it should just exclude parameters already being used from the potential candidates.

**Comment by bwilkerson** [comment]
I agree. It's almost always better to not offer users an action that we already know can't be performed.

**Comment by TheComputerM** [comment]
Hmm @bwilkerson, would it be possible for me to take a shot at resolving this issue?

**Comment by bwilkerson** [comment]
Yes, contributions are always welcome. I've assigned it to you; please let us know if you decide not to fix it.

**Comment by TheComputerM** [comment]
Thanks, here it is: https://dart-review.googlesource.com/c/sdk/+/357801
