### ISSUE TITLE
[analyzer] Implement implicit call method tear-offs with extension typed receivers

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54340]
This is the analyzer specific issue for https://github.com/dart-lang/sdk/issues/54339 which has the details.

(Note that this might be a trivial task, the behavior seems to be implemented already).

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
Indeed, it works because we treat extension types as `InterfaceType`s, so the previous logic just worked.
I'm added a separate test just to prevent a regression.
https://dart-review.googlesource.com/c/sdk/+/344900
