### ISSUE TITLE
Analyzer fails to canonicalize type objects for nullable extension types.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54359]
Example:
```dart
import "dart:async";
void main() {
  const c1 = identical(typeof<int>, typeof<ExInt>) ? 0 : (1 ~/ 0);  
  const c2 = identical(typeof<int?>, typeof<ExInt?>) ? 0 : (1 ~/ 0); // Analyzer error
  const c3 = identical(typeof<FutureOr<int>>, typeof<FutureOr<ExInt>>) ? 0 : (1 ~/ 0);  
}
typedef typeof<T> = T;
extension type const ExInt(int _) implements int {}
```
The analyzer considers `typeof<int?>` and `typeof<ExInt?>` different, even though both are constant `Type` objects for the type `int?`.

It seems to only affect nullability (at least `FutureOr` doesn't cause any problems).

CFE has no issue.

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
This code works now.
I believe it was fixed as https://github.com/dart-lang/sdk/issues/54302.
