### ISSUE TITLE
[analyzer] Implicitly tear off call from receiver whose type is a type variable

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54353]
This is the analyzer specific issue for https://github.com/dart-lang/sdk/issues/54351 which has the details.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
```dart
class A {
  void call() {}
}

Function f<X extends A>(X x) => x;
```

We might not do rewrite to `ImplicitCallReferenceImpl` for `=> x`.
IIRC, @srawlins started adding such rewrites, but we did not have time to do it everywhere.
I also will not have time to do this short term.
