### ISSUE TITLE
Analyzer: Constant record types should be allowed as constant types.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54354]
The record specification fails to say so directly, but a record type with constant field types should be a constant type.
It's also implemented almost consistently, so that's fine.

The exception is the analyzer, which fails to recognize a record type literal as constant when the type is written directly in a constant `is` or `as` clause, but not when it occurs as a type argument to a type alias in a similar constant expression.

Example:
```dart
// ignore_for_file: unnecessary_type_check
// ignore_for_file: unnecessary_cast
void main() {
  const b1 = (1, 1) is int; // OK, false
  const b2 = (1, 1) is (int, int); // Error, (int, int) not recognized as a constant type.
  const b3 = (1, 1) is typeof<(int, int)>; // OK, true. ?!?

  const v1 = (1, 1) as (int, int) ; // Error too.
  const v2 = (1, 1) as typeof<(int, int)> ; // Works.
  
  print("$b1, $b2, $b3, $v1, $v2"); // false, trye, true, (1, 1), (1, 1)
}
typedef typeof<T> = T;
```

Since `is typeof<(int, int)>` is allowed, clearly the type *is* constant, so something else is going on.

Is the constant evaluator bailing out eagerly, saying that something starting with `(` cannot be a constant type, so `as (` cannot be a constant expression?

CFE has no issue, and compiles the above without issue.

Found while testing extension types, but wasn't limited to those.

**Comment by srawlins** [comment]
Constant records were implemented recently in analyzer, and this code no longer produces unexpected errors, as of at least 3.5.0-180.3.beta.
