### ISSUE TITLE
Analyzer constant evaluation considers `NaN` to equal `NaN`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54355]
Example:
```dart
void main() {
  const v = (double.nan == double.nan) ? (1 ~/ 0) : 0; // Analyzer says `(1 ~/ 0)` throws.
  print(v); // CFE prints 0.
}
```
The code above compiles on CFE, fails in analyzer with an error saying that `(1 ~/ 0)` throws. That expression should never be evaluated.

The analyzer's constant evaluation seems to "optimize" `e1 == e2` by checking whether the two values are identical, but if they are, it then fails to check whether they are `double.nan`, which is the one value which is allowed in constant `==` and is *not* equal to itself.

**Comment by srawlins** [comment]
If you're curious, @kallentu
