### ISSUE TITLE
[macOS] Hang at `dart::bin::ProcessStarter::Start()`

### ISSUE THREAD

**Issue by sergiy-sc** [dart-lang/sdk#54360]
We have a game that embeds Flutter (3.16.2). Flutter engine is created when the app is started and while the game is loading, C++ sends several messages to Dart. It works 9 out of 10 times. 10th time app stuck. Here is a stack trace of main thread:
<img width="896" alt="image" src="https://github.com/dart-lang/sdk/assets/99789323/587d20f2-4330-43bf-897e-af2502343416">

I don't know how Dart can cause that, but I thought the whole context could be useful.
When I examine other threads, I see that when the app stuck, so does `flutter.ui` thread:

![image](https://github.com/dart-lang/sdk/assets/99789323/a03746e0-7a58-4000-8f63-eddd3b4ba1e5)

(I can repro this issue with released 3.16.2 flutter and with the one I build myself from sources with debug information, the stack trace above is from my custom build, because released version doesn't have debug symbols)

From the logs I can see that that code (sometimes) works once or several times and only then hangs.
I also added this kind of code, just to make sure that main dispatch queue always has something to do:
```c++
recursiveBlock = ^{
            NSLog(@"***** Block is executing");

            dispatch_queue_main_t mainQueue = dispatch_get_main_queue();
            // Re-add the block to the main queue after a delay of 1 second
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), mainQueue, recursiveBlock);
        };

        // Initially add the block to the main queue
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), recursiveBlock);
        return NSApplicationMain(argc, argv);
```

and that also hanged.
I checked how `fork()` is called and noticed that it's wrapped into `while` loop:
```c++
#define TEMP_FAILURE_RETRY(expression)                                         \
  ({                                                                           \
    ThreadSignalBlocker tsb(SIGPROF);                                          \
    intptr_t __result;                                                         \
    do {                                                                       \
      __result = (expression);                                                 \
    } while ((__result == -1L) && (errno == EINTR));                           \
    __result;                                                                  \
  })

int Start() {
    // Create pipes required.
    int err = CreatePipes();
    if (err != 0) {
      return err;
    }

    // Fork to create the new process.
    pid_t pid = TEMP_FAILURE_RETRY(fork());
```
but I'm pretty sure that it doesn't really spin there, it is just trapped inside `fork()`.
I don't have a small repro app, but I could try anything (I can build Flutter and Dart SDK).
Any idea what can cause this?

**Comment by a-siva** [comment]
> but I'm pretty sure that it doesn't really spin there, it is just trapped inside fork().
> I don't have a small repro app, but I could try anything (I can build Flutter and Dart SDK).

Can you confirm that it does not spin there by adding some print statements before and after the calls to `fork()` inside the while loop.

>Any idea what can cause this?

If the hang is in the call to `fork()` it could be some underlying issue with the OS. What process are you starting? Could there be a resource issue in that you are starting these processes and they are not exiting correctly resulting in a resource issue which causes the underlying `fork() ` to hang.

**Comment by mraleph** [comment]
From the screenshot it looks like preparing for the fork got stuck while executing callbacks registered via `pthread_atfork` - it is trying to take some lock and can't. Can you look into `fork_prepare_handler` and see where this is coming from and what is it trying to do? I don't think we use `pthread_atfork` in Dart SDK or Flutter engine - so I would think this is coming from one the dependencies or your game engine code. I could not find anything in the Apple's open source code with the same name.

**Comment by sergiy-sc** [comment]
Thanks @mraleph and @a-siva! Slava's idea could explain all the symptoms. I noticed that `Sentry` is registering something there. Trying to see if it could cause a deadlock.
