### ISSUE TITLE
[analyzer] spread properties from method invocation using static variables have no `staticElement`

### ISSUE THREAD

**Issue by JordyLangen** [dart-lang/sdk#54369]
We have a tool internally that looks for method invocations on a certain api to generate documentation based on the codebase.

I've noticed some behavior that I would not expect. 

Given the following setup:

```dart
void main() {
  Middleware().onSomeEvent();
}

class Middleware {
  // this would be a method on a specific class instance normally
  void logEvent(Map<String, String> properties) {}

  void onSomeEvent() {
    logEvent(_properties());
  }

  Map<String, String> _properties() => {_foo: "bar"};

  static const _foo = "oof";
}
```

We start analyzing, and we see this happening:

- The analyzer will report the `{..._properties()}` as a `SetOrMapLiteral`
- `_properties()` is reported as a `MethodInvocation`
- `_properties` is reported as a `SimpleIdentifier`
- We lookup the `staticElement`, and get the `ParsedLibraryResult` using the `staticElement`'s `library` using the analysis context/session
- We lookup the `ElementDeclarationResult` from the library element using the `staticElement`s `nonSynthetic`
- We find a `MapLiteralEntry` in tree of children of the element declaration, which contains a child in tree which is a `SimpleIdentifier` which refers to `_foo`
- **`_foo` does not have a `staticElement` (its `null`)**

I would not expect the `staticElement` to be null for `_foo`

Our code to get the compilation units and analysis sessions:

```dart
      final analysisContext = AnalysisContextCollection(
        includedPaths: files.map((file) => file.absolute.path).toUnmodifiableList(),
        sdkPath: dartSdkPath,
      );

      final compilationUnits = <String, CompilationUnit>{};
      final sessions = <String, AnalysisSession>{};

      for (final file in files) {
        final context = analysisContext.contextFor(file.absolute.path);
        final resolvedUnit = await context.currentSession.getResolvedUnit(file.absolute.path);

        sessions[file.path] = context.currentSession;

        if (resolvedUnit is ResolvedUnitResult) {
          compilationUnits[resolvedUnit.path] = resolvedUnit.unit;
        }
      }
```

In below example we follow the same strategy, which works without issue (read: we get a `staticElement` for a given `SimpleIdentifier`):

```dart
void main() {
  final properties = {"oob": "fab"};

  logEvent(properties);
}
```

(here `properties` is also a `SimpleIdentifier` which we can look up) 

I would almost assume this is a bug, but it could also be my knowledge lacking.

```
- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_arm64"
- on macos / Version 13.5.2 (Build 22G91)
- locale is en-NL
```

**Comment by bwilkerson** [comment]
> We lookup the `staticElement`, and get the `ParsedLibraryResult` using the `staticElement`'s `library` using the analysis context/session

I suspect that this is the cause of the problem. The AST structure has two visible states: the parsed state and the resolved state. In the resolved state all of the fields that contain types or elements are `null`. In the resolved state these fields have been populated. We offer both because a parsed AST is much less expensive to produce and suitable for some uses. Just not for yours.

I suspect that you'll to be able to access the information you need if you access the `ResolvedLibraryResult` for the `staticElement`.

**Comment by JordyLangen** [comment]
@bwilkerson thanks! this indeed resolves the issue. Is there any documentation somewhere on all this?

**Comment by bwilkerson** [comment]
Yes, there's a description in `sdk/pkg/analyzer/doc/tutorial/ast.md`.
