### ISSUE TITLE
Crash in dart web dev compiler if record member has the name `values`

### ISSUE THREAD

**Issue by mspb1g12** [dart-lang/sdk#54375]
Came across what looks like an odd crash in the dart web debug compiler (DDC?) where if a record contains `values` as a named member then it crashes at runtime. This doesn't appear to happen with other dart backends or the web release compiler.

```
RangeError: Maximum call stack size exceeded
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/records.dart 42:47      new
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/records.dart 171:18     new
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/records.dart 208:10     recordLiteral
packages/test/main.dart 1:29                                                      get a
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1293:8  get
packages/test/main.dart 6:11                                                      main$
web_entrypoint.dart 24:31                                                         <fn>
lib/ui_web/ui_web/initialization.dart 41:9                                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                <fn>
```

Reproduction code:
```
final ({String values}) a = (
  values: 'anything'
);

void main() {
  print(a.values);
}
```

**Comment by parlough** [comment]
It seems this reproduces on `main` too.

\cc @nshahan

**Comment by nshahan** [comment]
Thanks for the report! This is definitely a bug in the DDC implementation unrelated to the type system changes.

cc @Markzipan here are some possible fixes that come, WDYT?

There is a name collision with the property `.values` where we store the elements of the record, and the getter `.values` the getter matching the named element "values" that we add to the record prototype. The same collision bug exists for a named element "shape" although it manifests when DDC needs to access the shape of a record during a type test.

One possible fix would be to manually use JavaScript symbols to store the shape and values on a record object. We will always have to access them via the symbols throughout the SDK runtime libraries.

Investigating this made me realize we also have collision bugs with the named elements "constructor" and "prototype". In this case they are recognized as getters that must be renamed when generating the accesses but they were actually renamed when the getters were created at runtime. This means any time you try to access named record elements `.constructor` or `.prototype` they return `undefined`.

A fix for this would be to always check element names and rename when needed to avoid collision when we add the getters at runtime.
