### ISSUE TITLE
[dart2wasm] Minimize type names in release builds

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#54372]
In release mode we should use short names for types in type errors, to save binary space.

We may also be able to use runtime-generated class names like `"Class${classId}"` to avoid class names altogether.

Class names are generated here: https://github.com/dart-lang/sdk/blob/d0b6ce505acba68400393bc9395703e09ae60a80/pkg/dart2wasm/lib/types.dart#L207-L220

**Comment by mkustermann** [comment]
In `-O2` / `-O3` / `-O3` mode we now use `--minify` which will (introduced in 7f668b63c358248e6bb64bf4d7f1b802a44fa5cf) omit class names and make `<obj>.runtimeType.toString()` use `minified:Class<cid>` names.

So I think this can be closed.
