### ISSUE TITLE
[dart:js_interop] Support allowInteropCaptureThis in some manner

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#54381]
Previous iterations of JS interop allowed wrapping callbacks that allowed you to capture the calling `this` object. 

https://github.com/dart-lang/sdk/blob/b7aa9106a86ec4dce6234d039ea4d26a7ba55cb7/sdk/lib/js_util/js_util.dart#L281

While we do have support for `allowInterop` through `Function.toJS`, we don't support capturing `this`. Currently, that js_util method is unsupported in dart2wasm and the usage is low, but it would be nice to support the capture through something like `.toJSWithThis` so users can migrate off of `dart:js_util` easier.

**Comment by ykmnkmi** [comment]
Not necessary, but I need this.

**Comment by srujzs** [comment]
FYI @nex3, iirc, Sass was one of the few codebases using this. There might be a way to work around this in the meantime, but I haven't gotten a chance to dig deeper. Let me know if this is a blocker.

**Comment by nex3** [comment]
Yes, this is necessary. Generally speaking, JS libraries treat `this` as part of the API surface area for callbacks.

**Comment by Zekfad** [comment]
Currently it is possible to partially workaround this by using raw JS wrapper function, although this will fail in contexts where CSP does not allow `unsafe-eval`.
```dart
@JS('Function')
external JSFunction _createDynamicJSFunctionUnsafe$1(JSString argument, JSString body);

final _captureThis = () {
  try {
    return _createDynamicJSFunctionUnsafe$1(
      'f'.toJS,
      'return function (...args) { return f.call(this, this, ...args); };'.toJS,
    );
  } catch(e) {
    return null;
  }
}();

JSFunction _tryCaptureThis$0<R extends JSAny?>(R Function(JSObject? context) f) {
  final jsF = f.toJS;
  if (_captureThis == null) {
    return (() => f(null)).toJS;
  }
  return _captureThis!.callAsFunction(_captureThis, jsF)! as JSFunction;
}

JSFunction _tryCaptureThis$1<R extends JSAny?, Arg1 extends JSAny?>(R Function(JSObject? context, Arg1 arg1) f) {
  final jsF = f.toJS;
  if (_captureThis == null) {
    return ((Arg1 arg1) => f(null, arg1)).toJS;
  }
  return _captureThis!.callAsFunction(_captureThis, jsF)! as JSFunction;
}
```
