### ISSUE TITLE
[dart2wasm] co19/LibTest/async/StreamController/stream_all_A01_t03 is flaky on dart2wasm-linux-firefox

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#54398]
This test flips between Pass and RuntimeError from time to time on the unrelated changes:

https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=co19/LibTest/async/StreamController/stream_all_A01_t03

/cc @osa1

**Comment by osa1** [comment]
The test has a bug.
```dart
import "dart:async";
import "../Stream/allTests_A03.lib.dart";

Stream<T> create<T>(Iterable<T> data, {bool isError(T element)?}) {
  StreamController<T> sc = new StreamController<T>();
  for (T e in data) {
    if (isError != null && isError(e)) {
      sc.addError(e as Object);
    } else {
      sc.add(e);
    }
  }
  new Future(() => sc.close()); // close stream controller later
  return sc.stream;
}

main() {
  test(create);
}
```

We need a `asyncStart` before creating the future that closes the stream, and call `asyncEnd` after `sc.close()`.

I was going to report this in co19, but the test was removed 2 weeks ago: https://github.com/dart-lang/co19/pull/2421.

So we just need to update co19.

**Comment by osa1** [comment]
While looking at some of the other tests in the same directory I found the same bug in another test: https://github.com/dart-lang/co19/issues/2440.

**Comment by osa1** [comment]
Closing as the test disappeared, probably after a co19 roll. (https://dart-current-results.web.app/#/filter=dart2wasm)

The other issue I found is being tracked in the co19 issue linked above.
