### ISSUE TITLE
Failures on [dart:js_interop] Add generics to JSArray and JSPromise...Adjust UP to move the intersection type rules up

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#54409]
There are new test failures on [[dart:js_interop] Add generics to JSArray and JSPromise...Adjust UP to move the intersection type rules up](https://github.com/dart-lang/sdk/compare/f9d64593ff5144ce9b1006ce1f8713152b7391e8~...e6a313568c5835f177cf2c354a79ffbee8246adf).

The tests
```
co19/LibTest/typed_data/Int32List/setRange_A06_t02 RuntimeError (expected Pass)
co19/LibTest/typed_data/Int64List/setRange_A06_t01 RuntimeError (expected Pass)
co19/LibTest/typed_data/Uint32List/setRange_A06_t02 RuntimeError (expected Pass)
co19/LibTest/typed_data/Uint64List/setRange_A06_t01 RuntimeError (expected Pass)
lib/js/static_interop_test/js_function_conversions_test Timeout (expected Pass)
```
are failing on configurations
```
dart2wasm-linux-firefox
dart2wasm-linux-jscm-chrome
```

**Comment by osa1** [comment]
It looks like when implementing `setRange` on JS typed arrays, we can't mix `BigInt64Array` and other types of arrays. For example, this works:

```js
let dest = new Int16Array(10);
let source = new Int32Array([1, 2, 3]);
dest.set(source);
```

But if one of the arrays is `BigInt64Array` it fails:

```js
let dest = new BigInt64Array(10);
let source = new Int32Array([1, 2, 3]);
dest.set(source);
```

Fails with:

```
Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions
    at BigInt64Array.set (<anonymous>)
```

There may be other issues as well.

**Comment by osa1** [comment]
`setRange` issues fixed in https://dart-review.googlesource.com/c/sdk/+/343160.

`js_function_conversions_test` is a different issue, I'll fix it separately.

**Comment by osa1** [comment]
`js_function_conversions_test` triggers a Firefox crash. I'll try with the latest Firefox nightly and report it in Firefox issue tracker if the issue persists.

**Comment by mkustermann** [comment]
@osa1 Can we close this issue?

**Comment by osa1** [comment]
@mkustermann We haven't updated Firefox yet so the test `js_function_versions_test` is still crashing on Firefox.

**Comment by mkustermann** [comment]
I think this is working now. I'll also update firefox.
