### ISSUE TITLE
Quick-fixes that insert text with completion/choices show backslashes in front of closing curly braces

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#54403]
**Describe the issue**

When using the quick-fix for missing override, with an `Iterable<Record>` (tested with `Set` and `List` as well), the last item inside the record always ends with `\` at the end.

**To Reproduce**

1. Add the following code to your project in vscode:

```dart
abstract class A {
  void fn(Iterable<({int a, int b})> r);
}

class B extends A {
}

abstract class C {
  void fn(({int a, int b}) r);
}

class D extends C {
}
```
2. Quick fix for missing override.

**Expected behavior**

Expected the quick fix to not add `\` at the end.

**Screenshots**

https://github.com/Dart-Code/Dart-Code/assets/52160996/0aa5abcd-8a67-4725-b93d-59f2b80b61e8

**Comment by DanTup** [comment]
Apparently this isn't a bug and we should not escape any characters for the specific cases that don't require it (eg. in choices, we cannot escape `}` even though we escape it on the others).

I've opened some PRs to VS Code + LSP docs to try and make this concrete before I start changing things:

https://github.com/microsoft/language-server-protocol/pull/1868
https://github.com/microsoft/vscode-docs/pull/6928

**Comment by DanTup** [comment]
The VS Code docs + LSP changes landed. I've opened a server fix at https://dart-review.googlesource.com/c/sdk/+/345661
