### ISSUE TITLE
[analyzer] `RecordTypeImpl.==` and `RecordTypeImpl.hashCode` are insufficient for comparing record types

### ISSUE THREAD

**Issue by dnys1** [dart-lang/sdk#54407]
The implementation of `RecordTypeImpl.hashCode` seems insufficient for distinguishing record types in a collection (Set/Map). Is the intention to be able to support using `RecordTypeImpl` (and `TypeImpl` in general) in this way?

https://github.com/dart-lang/sdk/blob/1de6bc74d28421548ce465f96daccb22b1a77657/pkg/analyzer/lib/src/dart/element/type.dart#L1125-L1131

Likewise `RecordTypeImpl.==` is nearly complete, but fails to account for two record types which only differ by the presence of an `alias`.

https://github.com/dart-lang/sdk/blob/1de6bc74d28421548ce465f96daccb22b1a77657/pkg/analyzer/lib/src/dart/element/type.dart#L1137-L1179

This should probably read:

```dart
    if (other.nullabilitySuffix != nullabilitySuffix) {
      return false;
    }

    if (other.alias != alias) {
      return false;
    }
```

Happy to submit a fix, but wanted to clarify the intention of `hashCode` before submitting. Thanks!

**Comment by parlough** [comment]
\cc @scheglov
