### ISSUE TITLE
async* inconsistency in DDC

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#54411]
We know we have several inconsistencies so far, here is a case originally reported in the flutter repo: https://github.com/flutter/flutter/issues/140199

```dart
import 'dart:async';

Future main() async {
  Stream<int> step1() async* {
    yield 0;
    await Future.delayed(const Duration(milliseconds: 100));
    yield 1;
    throw Exception('error');
  }

  Stream<int> step2() async* {
    await for (final v in step1()) {
      yield v;
    }
  }

  try {
    await for (final v in step2()) {
      print('v: $v');
    }
  } catch (e) {
    print('e: $e');
  }
  print('finish');
}
```

Output in VM and dart2js:
```
v: 0
v: 1
e: Exception: error
finish
```

Output in DDC:
```
v: 0
v: 1
```

**Comment by nietsmmar** [comment]
Is there any progress on this? I find it quite difficult to debug my applications with this wrong behavior in dev build.
Thanks :)

**Comment by nietsmmar** [comment]
@sigmundch are there any updates on this?

**Comment by sigmundch** [comment]
Thanks for following up, unfortunately no, we haven't been able to prioritize this :disappointed: 

This may not be very helpful or you may already be aware of this, but just in case: some developers find useful to do some additional debugging with the `--profile` mode. That mode runs the `dart2js` compiler (same one use for release builds) in a mode that keeps around the original names of your classes and members. That compiler will have the correct async* semantics. However, it can only be used with the default browser devtools and not via the Dart Devtools. Anyways, sometimes it can provide a bit of additional info that it's otherwise hard to get in other ways today.

**Comment by nshahan** [comment]
@natebiggs
I believe this has been corrected with your change. WDYT?

**Comment by biggs0125** [comment]
I just verified locally that DDC, with the new async changes, now shows an output aligned with the VM and dart2js. These changes should roll into Flutter soon but likely won't be in a stable release for a few months. Going to close out this issue though as the fix has been landed in the Dart SDK.

**Comment by sigmundch** [comment]
Just wondering, is it safe to assume the current test coverage also covers this case, or is it worth adding it as a regression test case?
