### ISSUE TITLE
[CP] DDS and DevTools server change: fix an issue with serving static DevTools assets.

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#54428]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/343000

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/343002

### Issue Description

There was an issue when serving static assets from DevTools. If we could not find the file, the devtools server would just crash instead of handling the failure gracefully.

### What is the fix

The fix was to add try catch blocks around the problematic code and return a `Response.notfound` in the event that we could not find the file.

### Why cherry-pick

This is preventing DevTools extensions from loading properly.

### Risk

low

### Issue link(s)

n/a

**Comment by mit-mit** [comment]
SGTM
