### ISSUE TITLE
Failures on [analyzer,cfe] Support contained types is as-pattern

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#54420]
There is a new test failure on [[analyzer,cfe] Support contained types is as-pattern](https://dart-review.googlesource.com/c/sdk/+/338760).

The test
```
language/patterns/exhaustiveness/unsound_cast_3_2_test RuntimeError (expected Pass)
```
is failing on configuration
```
dart2wasm-linux-chrome
```

The test exposes an unsoundness found in the exhaustiveness checking, which the test uses to create a `null` value in for an non-nullable type. The test might be failing because dart2wasm assume the soundness and have optimized the generated code accordingly.

**Comment by osa1** [comment]
I'm confused about how other targets handle this. Smaller repro:

```dart
sealed class S {}

class A extends S {}

class B extends S {}

class X extends A {}

class Y extends B {}

class Z implements A, B {}

int unsound(S s) => switch (s) {
      X() as A => 0,
      Y() as B => 1,
    };

main() {
  print(unsound(Z()));
}
```

VM prints `null`, dart2wasm print `0`.

When I look at the kernel for `unsound`, it has no type tests and no code paths that return `null`:

```
static method unsound(test::S s) → core::int
    return block {
      core::int #t1;
      final synthesized test::S #0#0 = s;
      #L1:
      {
        {
          if(let final dynamic #t2 = _in::unsafeCast<test::A>(#0#0) in block {
            _in::unsafeCast<test::A>(#0#0);
          } =>false) {
            #t1 = 0;
            break #L1;
          }
        }
        {
          if(let final dynamic #t3 = _in::unsafeCast<test::B>(#0#0) in block {
            _in::unsafeCast<test::B>(#0#0);
          } =>false) {
            #t1 = 1;
            break #L1;
          }
        }
      }
    } =>#t1;
```

I don't understand how can VM (or any other target) can compile this to return `null`.

I wonder how this works in VM?

**Comment by johnniwinther** [comment]
This is the unsoundness. Before the change, the exhaustiveness checking deemed the switch expression to be exhaustive, but as you can see, `Z` shows us this not correct; `Z` is an `A` so it passes the `as A` but is _not_ an `X` so it doesn't match the `X()` pattern, similarly `Z` is a `B` so it passes the `as B` but it is _not_ a `Y` so it doesn't match the `Y()` pattern. This means that `Z()` falls through the switch expression without ever assigning a value to `#t1`, thus returning `null`.

**Comment by johnniwinther** [comment]
The reason for using language version is that there is no simple relation between 3.2 and 3.3 semantics; some sound programs are allowed in 3.2 but not in 3.3 and some sound programs are allowed in 3.3 but not in 3.2.

I'll create a CL that adds a `throw` in 3.2 where the unsoundness could occur.
