### ISSUE TITLE
[analyzer] Spurious warning about guaranteed non-match

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54421]
Consider the following program:

```dart
enum E { one, two }

extension type const ET(E it) {}

const et1 = ET(E.one);
const et2 = ET(E.two);

void main() => switch (et1) {
      et1 => 1,
      et2 => 2,
    };
```

The analyzer reports a warning on each of the cases of the switch expression, indicating that

```
The matched value type 'ET' can never be equal to this constant of type 'E'.
```

This is not true because both the scrutinee and the value of the constant pattern of the first case is the same object, `E.one`. It is definitely not helpful to warn that the match is impossible when that isn't true.

Presumably, the decision about whether to emit this warning should be made based on the extension type erasure of the matched value type.

The constant pattern value is considered to be `E.one` because of constant expression evaluation (we know exactly which object this will be). This means that an extension type (and indeed the static type of the constant expression, whatever it is) has been eliminated, and the constant pattern expression is simply considered to denote `E.one`. So we only need to take the erasure of the matched value type, which will make the two elements line up as usual.

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/342729 should fix this too.
