### ISSUE TITLE
[dart:io] HTTP Request within idleTimeout & persistentConnection = true hangs when IP changed on macOS/iOS

### ISSUE THREAD

**Issue by jankuss** [dart-lang/sdk#54436]
In my flutter application, I was debugging an issue with stuck/hung http requests. When the user changed between WiFi and Cellular on iOS, the next HTTP Request the user did would hang/is stuck until it timed out.

Analyzing the issue further, the problem occurs only when: 
- The request is not the first HTTP Request made with the `HttpClient`
- The request has `persistentConnection` = true (default)
- The request is performed during the specified `idleTimeout`
- The IP Address of the user changed

After further research: The TCP connection to the server is being reused until the `idleTimeout` is reached. When a request is made within that `idleTimeout`, it will go through the existing TCP connection.

Appearantly, this TCP connection is kept within the HttpClient, even when the user changed IP addresses and the connection should be dead.

I would expect the next request after a connection change to respond normally.

<details>
  <summary>Minimum reproduction</summary>

To reproduce, run this script (`http` dependency is required).

After 5 seconds, change the network so the IP address changes - For example: I used my phones cellular hotspot and my home internet to change IP addresses.

```dart
import 'dart:async';
import 'dart:io';

import 'package:http/io_client.dart';

void main(List<String> arguments) async {
  final http = IOClient(HttpClient()..idleTimeout = Duration(seconds: 200));
  print("STARTED");

  final response1 = await http.get(Uri.parse('https://example.org'));
  print("Response 1: ${response1.statusCode}");


  final myIp = await getCurrentIp();

  while (true) {
    if (myIp == await getCurrentIp()) {
      print("IP DID NOT CHANGE, WAITING");
      await Future.delayed(Duration(seconds: 5));
      continue;
    } else {
      break;
    }
  }

  print("IP CHANGED - NOW LETS TRY REQUEST AGAIN");
  final response2 = await http.get(Uri.parse('https://example.org'));

  // THIS IS NEVER REACHED - IT SHOULD PRINT THE STATUS CODE
  print("Response 2: ${response2.statusCode}");
}

Future<String> getCurrentIp() async {
  final http = IOClient(HttpClient());
  try {
    final response = await http.get(Uri.parse('https://ipinfo.io/ip'));
    return response.body;
  } finally {
    http.close();
  }
}
```
</details>

<details>
<summary>dart info</summary>
#### General info

```
- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_arm64"
- on macos / Version 14.0 (Build 23A344)
- locale is de-DE
```

</details>

Issues that might be related:
https://github.com/dart-lang/sdk/issues/47807
https://github.com/dart-lang/sdk/issues/53040

**Comment by brianquinlan** [comment]
If you are using Flutter, I'd suggest using `package:cupertino_http`. I think that it will correctly discard the connection pool on IP changes.

**Comment by jankuss** [comment]
@brianquinlan We tried `package:cupertino_http` out and it performs very well. We are not seeing the issue anymore. The only downside now is that we are not seeing the HTTP traffic in the Flutter DevTools, making it harder for us to debug HTTP requests on iOS.

**Comment by brianquinlan** [comment]
@jankuss The DevTools integration is in place now. It would be great if you could try it out!
