### ISSUE TITLE
[extension types] Switch statement is not exhaustive on sealed class

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54444]
Switch statement with the matched value an extension type with a dyrect subrtype of a sealed class as a representation type is not exhaustive. But similar switch expression is. Example
```dart
// SharedOptions=--enable-experiment=inline-class

sealed class A {}

class B extends A {}

extension type BET(B _) {}

String test1(BET b) { // Error. The body might complete normally, causing 'null' to be returned, but the return type, 'String', is a potentially non-nullable type.
  switch (b) {
    case B _: return 'B';
  }
}

String test2(BET b) => switch (b) {
    B _ => 'B'
  };

main() {
  test1(BET(B()));
  test2(BET(B()));
}
```
Is this expected or issue?

Tested on on `Dart SDK version: 3.3.0-edge.3e09072221b5fe4e8ea3d4fb69f120af8aa499cd (main) (Fri Dec 22 00:37:15 2023 +0000) on "linux_x64"`

**Comment by eernstg** [comment]
The error message comes from the flow analysis. This analysis has not yet been specified in all details. However, I would recommend that the flow analysis relies on the extension type erasure when it is computing whether or not it the switch statement can complete normally: The erasure yields the most precise approximation to the actual run-time behavior that we have.

@stereotype441, do you agree?

**Comment by lrhn** [comment]
The extension type erasures are the only types that precisely describe runtime behavior, so they are the ones we need to use at compile-time to statically predict runtime behavior.

Since the matched value can, hypothetically, contain any possible value of the erased representation type, that is the type that must be exhausted. The type checks performed by the case patterns are done using erased types too, because that's all that exist at runtime.

**Comment by eernstg** [comment]
The language design question has been posed here: https://github.com/dart-lang/language/issues/3534.

If that proposal is accepted then the error in `test1` should no longer be reported, but for now we're blocked on https://github.com/dart-lang/language/issues/3534.

**Comment by sgrekhov** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/345822
