### ISSUE TITLE
CFE and analyzer do not agree on common super type with extends in generic types

### ISSUE THREAD

**Issue by Quijx** [dart-lang/sdk#54452]
I have the following code:
```dart
void main() {
  final foo = Foo(barA: 1, barB: 1.5);
  print(foo.getBar(useA: true));
}

class Foo<Bar, BarA extends Bar, BarB extends Bar> {
  Foo({required this.barA, required this.barB});

  final BarA barA;
  final BarB barB;

  Bar getBar({required bool useA}) {
    return useA ? barA : barB;
  }
}
```
The analyzer shows no errors. However when I execute the file using `dart run` I get the following error:

```
bin/dart_bug.dart:14:17: Error: A value of type 'Object?' can't be returned from a function with return type 'Bar'.
 - 'Object' is from 'dart:core'.
    return useA ? barA : barB;
```
The analyzer seems to infer the type of the expression `useA ? barA : barB` as `Bar`, while the CFE infers it as `Object?`.
My dart version here is `Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "linux_x64"` it.

This code was working fine for example in `Dart SDK version: 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "linux_x64"`. I haven't pinned down the exact version in which it broke.

**Comment by lrhn** [comment]
On dartpad.dev, the problem occurs on the stable branch (Dart 3.2.3), but appears to have been fixed on the master branch (3.3.0-238.0.dev)
