### ISSUE TITLE
Analyzer infers incorrect return type of operator used in extension

### ISSUE THREAD

**Issue by Quijx** [dart-lang/sdk#54462]
When using a binary operator that returns a type `F` in an extension of the form `extension FooExtension<F extends Foo> on F`, the return type is incorrectly determined at a use site inside the extension.
This does not seem to be a problem with unary operators.

For example the following code shows an analyzer error at the operator use site inside the extension, while an eqivalent method use site shows no error:
```dart
void main() {
  final fooBar = FooBar();
  print(fooBar.next1);
  // Operator call outside the extension infers the correct type.
  final FooBar nextFooBar = fooBar + 1;
}

class Foo {}

class FooBar extends Foo {}

extension FooExtension<F extends Foo> on F {
  F add(int i) => this;

  F operator +(int i) => this;

  // This shows an analyzer error
  F get next1 => this + 1;
  //             ^^^^^^^^
  // A value of type 'Foo' can't be returned from the function 'next1'
  // because it has a return type of 'F'. - return_of_invalid_type

  // This shows no errors
  F get next2 => this.add(1);
}
```
The code compiles and executes fine. Just the analyzer complains.

This happens in Dart SDK version: 3.2.3 (stable), as well as the current master channel in dartpad.dev.

**Comment by srawlins** [comment]
CC @scheglov

**Comment by srawlins** [comment]
Oh nvm, this is for extension, not extension type.
