### ISSUE TITLE
Expose external typed arrays in dart_api_dl.h

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#54465]
I'd like to be able to construct external typed arrays in dart_api_dl.h.

Can I expose the APIs?

**Comment by dcharkes** [comment]
@johnmccutchan What is your use case?

Why not pass a `Pointer` as return value from an FFI call or as an argument in a callback? And then use [`asTypedList`](https://api.dart.dev/dev/3.3.0-263.0.dev/dart-ffi/Uint8Pointer/asTypedList.html) to take ownership of the data and attach a finalizer that calls `free`?

**Comment by johnmccutchan** [comment]
I tried that but I don't like the lifecycle requirements and ergonomics.

Correct me if I'm wrong but I would need something like the following for the finalizer and the life cycle would be pinned to the NativeTypedData:

```
class NativeTypedData<T> implements ffi.Finalizable {
  // ...finalizer
  // ffi.Pointer<T>

  Object /* one of TypedLists. */ asTypedList();
}
```

The main problem I have with it is that the lifecycle is tied to NativeTypedData<T> and not to the, say, Float32List that I actually want.

And unfortunately, I can't make a specialized `NativeTypedData` that implements, say, `Float32List` because `implements Float32List` is a [compilation error](https://api.flutter.dev/flutter/dart-typed_data/Float32List-class.html).

I'm going to be vending these arrays out to user code and the life cycle will be too subtle and tricky if they have to keep this other object alive when they are really only interested in the typed list.

Maybe I'm holding Finalizable wrong?

**Comment by dcharkes** [comment]
> Correct me if I'm wrong but I would need something like the following for the finalizer:
> 
> ```
> class NativeTypedData<T> implements ffi.Finalizable {
>   // ...finalizer
>   // ffi.Pointer<T>
> 
>   Object /* one of TypedLists. */ asTypedList();
> }
> ```

No, you should not be needing a `Finalizable`, `asTypedList` has a `finalizer` argument.

> I'm going to be vending these arrays out to user code and the life cycle will be too subtle and tricky if they have to keep this other object alive when they are really only interested in the typed list.

Yes, you want to create that `Float32List` with a `finalizer` argument such that the finalizer is attached to the `Float32List` and you can give that one to the user.

**Comment by johnmccutchan** [comment]
Okay, so that solves the finalizer part.

Now I'll need to convert it back to a float* when passing it to native code, I suppose I should use a leaf function and have it automatically unwrapped ?

**Comment by dcharkes** [comment]
> Now I'll need to convert it back to a float* when passing it to native code, I suppose I should use a leaf function and have it automatically unwrapped ?

Correct.

(Please note you need to be on the dev/main branch for that, it landed in December. https://dart-review.googlesource.com/c/sdk/+/338620)
