### ISSUE TITLE
jsonEncode with generic class throws exception NoSuchMethodError: Class has no instance method 'toJson' with matching arguments.

### ISSUE THREAD

**Issue by codelovercc** [dart-lang/sdk#54479]
```shell
% dart --version
Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_x64"

```

```shell
 % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 12.7.1 21G920 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[!] Network resources                   
    ✗ A network error occurred while checking "https://maven.google.com/": Operation timed out
    ✗ An HTTP error occurred while checking "https://github.com/": Connection closed before full header was received

! Doctor found issues in 1 category.
```

Ignoring the network issue  🙁 

```dart
@JsonSerializable(genericArgumentFactories: true)
class DataResponse<T> {
  OperationCode code;

  String message;

  final T? data;

  DataResponse({required this.code, required this.message, this.data});

  factory DataResponse.fromJson(
          Map<String, dynamic> json, T Function(Object? json) fromJsonT) =>
      _$DataResponseFromJson(json, fromJsonT);

  Map<String, dynamic> toJson(Object? Function(T value) toJsonT) =>
      _$DataResponseToJson(this, toJsonT);
} 
```
As we can see method `Map<String, dynamic> toJson(Object? Function(T value) toJsonT)` is not the `toJson()` form.
I use `json_serializable: ^6.7.1` for generate `_$DataResponseToJson`. it takes an argument `Object? Function(T value) toJsonT` for serialize generic type `T`. 

Reproduce step:

```dart
var r = DataResponse.fromJson({"code":5,"message":"incorrect username or password."}, (json)=>null);
print(r.toJson(value) => null)); // this work
print(jsonEncode(r)); // this throws the exception

```

**Comment by lrhn** [comment]
This is working as designed.

The `jsonEncode` function and `JsonEncoder` class of `dart:convert` are intended for converting simple values, lists and maps to JSON text.

The legacy support for calling `toJson` on an object that is not directly encodable is not intended as a way to provide general serialization of arbitrary objects. If anything, it's just not intended to be used at all, and you should use the `toEncodable` parameter instead, and write the special casing for your own types. The dynamic `toJson` call it's just not a good idea, or design.

Preferably, any conversion should be handled prior to calling `jsonEncode`, so it only has to work on simple, directly encodable list/map structures.

That `json_serializable` introduces a method with the same name is just an accident. It's completely unrelated to what `jsonEncode` does, and should only be used as intended by that package.
