### ISSUE TITLE
Callback throwing an exception when inside pattern matching.

### ISSUE THREAD

**Issue by lucasshiva** [dart-lang/sdk#54477]
First of all, I apologize if this is not the right place to create such issue.

The problem I'm facing is that I have a class that contains a callback, and pattern matching seems to have a problem with said callback. I get the following exception whenever I try to use it: `_TypeError (type '(Sorting) => String' is not a subtype of type '((Enum) => String)?' in type cast)`

For context, this is what I'm doing. Note that `Filter` is an empty class, just for typing purposes.

```dart
class RadioFilter<T extends Enum> extends Filter {
  const RadioFilter({
    required this.options,
    required this.selectedOption,
    required this.optionDisplayNameBuilder,
  });

  final List<T> options;
  final T selectedOption;

  // The callback in question.
  final String Function(T option)? optionDisplayNameBuilder;

  @override
  List<Object?> get props => [options, selectedOption];
 }
 
enum Sorting {
  favorites,
  views,
  random;
}

extension CapitalizeX on Enum {
  String capitalize() => name.substring(0, 1).toUpperCase() + name.substring(1);
}
```

The UI:

```dart
// This is the content of a BottomSheet.
class _VisibleStyleWidget extends StatefulWidget {
  const _VisibleStyleWidget();

  @override
  State<_VisibleStyleWidget> createState() => _VisibleStyleWidgetState();
}

class _VisibleStyleWidgetState extends State<_VisibleStyleWidget> {
  final filters = <Filter>[
    const FilterHeader(
      name: "Sorting",
      description: "Method of sorting results",
    ),
    RadioFilter(
      options: Sorting.values,
      selectedOption: Sorting.favorites,
      // Filters may require different logic in order to print the options in a pretty format.
      optionDisplayNameBuilder: (Sorting option) => option.capitalize(),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [for (final filter in filters) _buildFilter(filter)],
    );
  }

  Widget _buildFilter(Filter filter) {
    return switch (filter) {
      FilterHeader() => ...
      FilterSeparator() => ...
      FilterNote() => ...

      // Here is the error.
      RadioFilter(
        :final options,
        :final selectedOption,
        // If we unpack the callback, the exception happens on this line.
        // Otherwise, it happens below when calling `filter.optionDisplayNameBuilder`
        :final optionDisplayNameBuilder
      ) =>
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              for (final option in options)
                FilterChip(
                  label: Text(optionDisplayNameBuilder?.call(option) ?? option.name),
                  selected: option == selectedOption,
                  onSelected: (value) {},
                )
            ],
          ),
        ),
    };
  }
}
```

Considering that `Sorting` is an Enum, I don't understand why we get a `TypeError`. Also, everything works if we move the code inside the class, like so:

```dart
class RadioFilter<T extends Enum> extends Filter {
  const RadioFilter({
    required this.options,
    required this.selectedOption,
    required this.optionDisplayNameBuilder,
  });

  final List<T> options;
  final T selectedOption;

  final String Function(T option)? optionDisplayNameBuilder;

  @override
  List<Object?> get props => [options, selectedOption];

  Widget buildChips(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      child: Wrap(
        spacing: 8,
        runSpacing: 8,
        children: [
          for (final option in options)
            FilterChip(
              label: Text(optionDisplayNameBuilder?.call(option) ?? option.name),
              selected: option == selectedOption,
              onSelected: (_) {},
            ),
        ],
      ),
    );
  }
}
```

Then, in the UI, we call the method instead:

```dart
Widget _buildFilter(Filter filter) {
    return switch (filter) {
      FilterHeader() =>...
      FilterSeparator() => ...
      FilterNote() => ...
      
      // This works as expected.
      RadioFilter() => filter.buildChips(context),
    };
  }
```

I am rather new to Dart (and Flutter), so this may be intended rather than a bug. But, in my opinion, the callback should work like it does when called inside the `RadioFilter` class.

**Comment by lucasshiva** [comment]
> This is a getter where the class type-variable occurs contravariantly. That's generally unsafe. You're allowed to write it, but you really, really have to be careful when using it.

I don't quite understand this. Are you saying that I should be more careful with writing callbacks with generics like this?

```dart
final String Function(T option)? optionDisplayNameBuilder;
```
Because I do it quite a lot. Or maybe the problem is the way I'm using it? As I said, I'm still quite new to Dart (and programming in general), I haven't got around all the dos and don'ts yet.

> In this case, a RadioFilter<Sorting> is effectively up-cast to RadioFilter<Enum>. It's optionDisplayNameBuilder has type String Function(Sorting), but is read by a location which expects a String Function(Enum), which `String Function(Sorting) is not!.

Giving that the exception was a `TypeError`, I assumed that was most likely the problem. However, since `Sorting` _is_ an `Enum`, shouldn't this work rather than throwing an error?

**Comment by lrhn** [comment]
That's where contravariant comes in.

Function types are contravariant in their argument types, which means that if `A` is  a subtype of `B`, `A` \<: `B`, then
`C Function(A)` is a _supertype_ of `C Function(B)`.

It has to be that way for the types to be sound.

So a `String Function(Sorting)` is not a valid value where a `String Function(Enum)` is expected, because the latter must be able to accept any `Enum` value as argument, and the former is not able to do that.

**Comment by lucasshiva** [comment]
I get it now, thanks for your time.
