### ISSUE TITLE
[analyzer] Report a compile-time error for external initializing formals

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54485]
Consider the following program:

```dart
class A {
  final int i;
  external A(this.i);
}

void main() {}
```

The CFE reports a compile-time error on this library. The analyzer accepts it with no errors.

It was previously only mentioned in commentary that it is a compile-time error for an external generative constructor to have an initializing formal parameter, but in https://github.com/dart-lang/language/pull/3517 the specification was clarified such that it is now clearly specified to be a compile-time error.

This issue is the implementation issue for that implementation effort. It is 'area-analyzer' rather than 'area-meta', with sub-issues, because there is nothing to implement in any other tool than the analyzer.

It is not a breaking change, because every external constructor declaration that has an initializing formal is reported as a compile-time error by the CFE already today.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/344180

**Comment by sgrekhov** [comment]
Seems that issue still exists for optional parameters. The following tests fail (no expected errors):
```
co19/Language/Classes/Constructors/Generative_Constructors/initializing_formal_parameter_A02_t02
co19/Language/Classes/Constructors/Generative_Constructors/initializing_formal_parameter_A02_t03
co19/Language/Classes/Constructors/Generative_Constructors/initializing_formal_parameter_A02_t04
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/345081
