### ISSUE TITLE
[dart2js] Not compiled html.DedicatedWorkerGlobalScope get self in dart 3.2 (flutter 3.16)

### ISSUE THREAD

**Issue by NickNevzorov** [dart-lang/sdk#54482]
I have a simple dart file (web worker):

```
@JS()

import 'dart:html' as html;
import 'dart:js_interop';
import '../src/device_state_thread.dart';

@JS('self')
external html.DedicatedWorkerGlobalScope get self;

void main() async {

  await DeviceStateThread().main(self);

}
```

In Flutter 3.16 (dart 3.2) it is not compiled with error:

```
Error: Type 'DedicatedWorkerGlobalScope' is not a valid type for external `dart:js_interop` APIs. The only valid types are: @staticInterop types, JS types from `dart:js_interop`, void, bool, num, double, int, String, and any extension type that erases to one of these types.
 - 'DedicatedWorkerGlobalScope' is from 'dart:html'.
Use one of the valid types instead.
external html.DedicatedWorkerGlobalScope get self;
```

The code is a part of https://pub.dev/packages/dart_thread package
In Flutter 3.13 all ok

**Comment by srujzs** [comment]
We removed these type-check errors a bit too eagerly for 3.1 and this is us re-adding needed restrictions in 3.2.

However, maybe this error is unneeded for `dart:html` types and we should allow users to write them on `dart:js_interop` APIs as long as they're a subtype of `JavaScriptObject`. I believe we allow extension types whose representation type is a `dart:html` type so if that's the case, we should allow this.

The workaround is typing it as `JSObject` and then cast a call to `self` to the `dart:html` type you want e.g.

```dart
@JS('self')
external JSObject get _self;
html.DedicatedWorkerGlobalScope get self;
```

**Comment by NickNevzorov** [comment]
@sigmundch Thanks, it works!

**Comment by srujzs** [comment]
No problem! I'm going to reopen just so we can track fixing this.
