### ISSUE TITLE
`prefer_final_locals` broken quick fix in for-loop destructured records

### ISSUE THREAD

**Issue by Leptopoda** [dart-lang/sdk#54497]
**Describe the issue**
Similar to: dart-lang/linter#4539 but that the quick fix is broken.

**To Reproduce**
```dart
  for (var (a, b) in [(1, 2)]) {
    print(a);
    print(b);
  }
```
is fixed to

```dart
  for (final (final a, final b) in [(1, 2)]) {
    print(a);
    print(b);
  }
```

Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "linux_x64"

**Expected behavior**
quick fix makes the record final and does not try to make the record fields final.

**Additional context**
Looks like the lint falsely fires when the parameter is not reassigned.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/371162
