### ISSUE TITLE
Front-end has incorrect constant `==` on records containing extension typed expressions.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54491]
```dart
void main() {
  const Chk((Ex(1),), eq: (1,));
}
class Chk {
  const Chk(Object? v, {required Object? eq}) :
    assert(v == eq, "Not equal ${(v, eq: eq)}");
}

extension type const Ex(Object? value) {}
```

This errors with:
```
cferec.dart:2:9: Error: Constant evaluation error:
  const Chk((Ex(1),), eq: (1,));
        ^
cferec.dart:6:47: Context: The constant value '((1), {eq: (1)})' can't be used as part of a string interpolation in a constant expression.
Only values of type 'null', 'bool', 'int', 'double', or 'String' can be used.
    assert(v == eq, "Not equal ${(v, eq: eq)}");
```
That message means that the `v == eq` test failed, even if both values were the singleton record `(1,)`.

The constant evaluator seems to get confused by the static record type being the unrelated `(Ex,)`, but `==`, even constant `==`, should use runtime behavior.

Removing the `const` in front of `Chk` removes the error, so the constant behavior differs from runtime behavior.

**Comment by chloestefantsova** [comment]
It looks like it's not only records, but other compound literals are affected as well.

**Comment by lrhn** [comment]
Cannot reproduce it for lists (in DartPad).

```dart
void main() {
  const Chk([Ex(1)], eq: <Object?>[1,]);
}
class Chk {
  const Chk(Object? v, {required Object? eq}) :
    assert(v == eq, "Not equal ${(v, eq: eq)}");
}

extension type const Ex(Object? value) {}
```
This shows me no error. 

(It's necessary to put the `<Object?>` on `eq:` list, otherwise it will infer `<int>`, which is not the same as the erasure of `Ex`.)

**Comment by chloestefantsova** [comment]
> (It's necessary to put the `<Object?>` on `eq:` list, otherwise it will infer `<int>`, which is not the same as the erasure of `Ex`.)

Interesting. It means that even after the erasure is applied to the static type of the record literal, the original example will still be a compile-time error, since the two record types will be `(Object?,)` and `(int,)`. Is that the expected behavior?

**Comment by lrhn** [comment]
Record values are structurally typed, they do not (or should not) remember the static type they had at creation.
The runtime type of a record is defined by its shape and the runtime types of its fields, nothing else.

So the runtime type of the `(Ex(1),)` is `(int,)`. The value is simply `(1,)` with no further information available (shape: single positional field, that field's value: integer 1).
Record equals is always "other has same shape, and each field of this `==` same field of other`.

So, the *static type* is irrelevent to `==` for records. The only difference between `(1,)` and `(Ex(1),)` is the static type. That's important in other situations, but not here.

**Comment by chloestefantsova** [comment]
> Record values are structurally typed,

Thanks for the clarification! The error is apparent here: we do use the static type of record literals when we compare them for equality. That's the culprit.
