### ISSUE TITLE
"Dart compiler exited unexpectedly" happening on Linux machine

### ISSUE THREAD

**Issue by ClaireDavis** [dart-lang/sdk#54508]
I'm attempting to upgrade my Dart SDK on my Flutter project from 3.0.7 to 3.2.3.  When I make this upgrade, and run my CI on a Linux machine, I get the following stacktrace sporadically:

```
1 error, see stacktrace for details
Error: Exception: the Dart compiler exited unexpectedly.\n\nStacktrace:
package:flutter_tools/src/base/common.dart 10:3  throwToolExit
package:flutter_tools/src/compile.dart 874:9     DefaultResidentCompiler._compile.<fn>
dart:async/zone.dart 1407:47                     _rootRunUnary
dart:async/future_impl.dart 846:45               Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 875:13               Future._propagateToListeners
dart:async/future_impl.dart 647:5                Future._completeWithValue
dart:async/future_impl.dart 721:7                Future._asyncCompleteWithValue.<fn>
dart:async/zone.dart 1399:13                     _rootRun
dart:async/zone.dart 1301:19                     _CustomZone.run
dart:async/zone.dart 1209:7                      _CustomZone.runGuarded
dart:async/zone.dart 1249:23                     _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 40:21         _microtaskLoop
dart:async/schedule_microtask.dart 49:5          _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 118:13     _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 185:5      
```

Important things to note:
* This failure isn't isolated to one test, and doesn't happen consistently.  Different tests will fail with this stack trace sporadically, but I always seem to get at least one failure
* This failure doesn't occur when I run on a MacOS machine.
* This has only been happening in CI, so the machine has a fresh dart installation.

It is odd to me that this is appearing as a compile error, but doesn't consistently fail.

I'm finding it incredibly hard to isolate the issue and create a consistent and reproducible error, but I'm wondering if you know of any changes between 3.0.7 and 3.2.3 that might trigger this type of issue.

**Comment by mraleph** [comment]
It looks like the compiler process might be crashing for some reason. Is this the only output you get? 

Could you try running `flutter test` CLI with `-v` and see if you get any additional information?

Alternatively you could add something like this to your CI commands:

```
ulimit -c unlimited 
echo /tmp/core.%e.%p | sudo tee /proc/sys/kernel/core_pattern 
flutter ... # here your CI commands running flutter test CLI
ls -al /tmp/core.*
```

And see if you get some core dumps generated. If you get some core dumps then we can try to add more commands to the CI to dump stack traces from the core dumps to try understanding where things are crashing.

**Comment by ClaireDavis** [comment]
Thanks for the response @mraleph!  It appears that the issue was that my CI pipeline was running out of memory while running the tests with the new upgrade.  I was able to fix my issue by bumping up my resource class.

**Comment by a-siva** [comment]
@ClaireDavis thanks for the clarification, will close the issue.
