### ISSUE TITLE
[vm/ffi] `Array` allocation in native memory

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54527]
After https://github.com/dart-lang/sdk/issues/54526 is addressed, allocating arrays in native memory will look something like:

```dart
void main() {
  final array = calloc<MyStruct>(10).asArray(5, 2);
}
```

This repeats the array length.

We could consider adding some methods to `Allocator` to simplify this.

```dart
extension AllocatorAlloc on Allocator {
  external Array<T> array<T extends NativeType>(int dimension1,
      [int dimension2,
      int dimension3,
      int dimension4,
      int dimension5]);

  external Array<T> arrayMulti<T extends NativeType>(List<int> dimensions);
}
```

Which would allow us to write:

```dart
void main() {
  final array = calloc.array<MyStruct>(5, 2);
}
```

### Side note: `Pointer<Array<...>>`

Note that there is no such thing as a `Pointer<Array<...>>`. The Pointer object would not know what the array dimensions are, so it could not have `operator []` and `operator []=`. Instead it would need methods that take array dimensions. We could consider going that route instead.

However, that would lead to other issues. For example: `calloc<Array<MyStruct>>()` would not know how large the array is.

**Comment by mkustermann** [comment]
Not sure if this makes sense. Allocators are allocating memory and returning pointers. These pointers have to be eventually freed. The `Array` objects don't provide a way to get the pointer of the underlying data, so it wouldn't be possible to free those arrays anymore, would it?

**Comment by dcharkes** [comment]
Right, that's the same issue as with structs and unions. Except for we wouldn't have access to the underlying pointer at all...

Where's my coffee? ☕  🤓 

If we want to have the underlying pointer, you would use exactly what we would already have with introducing `asArray`.

Closing as not planned.
