### ISSUE TITLE
Does `Isolate.spawnUri` accepts an aot-snapshot in JIT mode?

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#54528]
Take the following two files as an example:

```dart
/* file: func.dart */
void main() {
  print('func.dart');
}

/* file: main.dart */
import 'dart:isolate';

void main() async {
  final isolate = await Isolate.spawnUri(Uri.parse('func.aot'), [], null);
  print('...'); // never reached
}
```

Then:

- run `dart compile aot-snapshot func.dart`
- run `dart run main.dart`
- program never exits or throw an error

I assume it's not possible to run an `aot-snapshot` in JIT mode? If so, maybe sending an error to the `onError` port or throwing an exception here would be helpful. For instance, `spawnUri` throws an exception in AOT mode if `jit-snapshot`, `kernel` or a dart library were given (e.g. ```The uri provided to `Isolate.spawnUri()` does not contain a valid AOT snapshot.```)

> Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_x64"

**Comment by a-siva** [comment]
No we currently do not support loading an AOT snapshot into the JIT VM, agree that we need to produce a better error message for this. Will use this issue for the change to provide a clear error message,

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/346060
