### ISSUE TITLE
[dart2js] fix precedence issues in js_ast

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#54534]
The js_ast implementation currently doesn't respect precedence in several scenarios:
* new expressions: `new a.b().c()` vs `(new a.b()).c()`
* exponentiation: `-1 ** 2` vs `(-1) ** 2`
* for-initializers: `for (i = (0 in o) || (1 in o); x; y)` vs `for (i = (0 in o || 1) in o; x; y)`

We never came across these issues in the past because they can't be triggered directly by dart2js generated code. However, they can be triggered by new code patterns introduced via `dart:js_interop` and its corresponding lowering operations. The precedence for `new` expression is especially critical because it's a result of a common declaration for factory interop constructors. 

Here are example test repros for each case. Note that some of these issues only occur with `--omit-implicit-checks`, which causes subexpressions to be combined into a single JS expression in the JS-ast:

**new**: only fails with `--omit-implicit-checks`, instead of calling `new (globalThis.f().classA)()`, calls `(new globalThis.f()).classA()`:
```dart
import 'dart:js_util';

void main() {
  callMethod(globalThis, 'eval', ['''
      class A {}
      self.f = function F() { return {ClassA: A}; }
      ''']);
  final f = callMethod(globalThis, 'f', const []);
  final o = callConstructor(getProperty(f, 'ClassA'), const []);
  print(getProperty(getProperty(o,'constructor'), 'name'));
}
```

**exponentiation**: produces a syntax error
```dart
import 'dart:js_util';
main() => print(exponentiate<int>(-1, 2));
```

**for loop**: produces syntax error because `in` is parsed as part of the for loop accidentally:
```dart
import 'dart:js_util';
main() {
  final x = newObject();
  for(var o = or(hasProperty(x, 0), hasProperty(x, 1)); o != 1; o = 1) print(o);
}
```

_Note: this is a high priority issue that already affected internal and external developers. It causes issues with the new JS interop that is about to be released in Dart 3.3. Fixing this issue will require a cherry-pick to the beta channel as well._

See also: b/313833546

**Comment by sigmundch** [comment]
cc @itsjustkevin FYI

**Comment by srujzs** [comment]
If we think this may be a hard fix, do we see the possibility of doing something different in our interop lowering so that this has less of an impact? One option is to expose a `_self` in `js_util` just for this purpose for dart2js.

**Comment by srujzs** [comment]
> Regarding your suggestion, could you clarify how the _self is different from globalContext? I was imagining it as a getter as well, which could have the same vulnerability we have today.

We used to use `globalThis` from `js_util` which is also a getter before we moved to `staticInteropGlobalContext`. I'm not sure why it avoided the precedence problem before, but I'm assuming it may have to do with either `globalThis` being an `external`, patched member or the `prefer-inline` pragma. I figured if that avoids the issue, we could use a `_self` to avoid exposing a public member and continue using JS' `self` until this issue is resolved.

**Comment by sigmundch** [comment]
I see - yeah, I had a hard time reproing the issue because sometimes inlining does the right thing and inlines globalContext. The pragma is there, but there is a chance that it is not properly dealt with while patching the SDK. We should also look into that, or add the annotation also on the public interface if that helps get it right.

**Comment by srujzs** [comment]
A small distinction is that we inline using `staticInteropGlobalContext` and not `globalContext`, which just reexports the former, which doesn't have the pragma. If the pragma is the difference, we can try adding one to the former member. Maybe we always had this problem, but the pragma made it very rare.
