### ISSUE TITLE
[ANTLR] Migrating from Java actions to Dart actions.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#54540]
Consider [Dart.g](https://github.com/dart-lang/sdk/blob/master/tools/spec_parser/Dart.g).

It contains platform-dependent actions to make it easier to express certain syntactical restrictions.

The platform-dependent actions are written in Java.

There's a [Dart target](https://github.com/antlr/antlr4/pull/2728) that landed a couple of years ago, and I've been [using](https://github.com/modulovalue/dart_antlr_dart_experiments.dart) it with great success for finding inconsistencies between the spec and implementation.

I want to propose migrating the actions in Dart.g from Java to Dart.

This would simplify things by removing a dependency on Java. It would also make it much easier to plug in parsers generated from the ANTLR grammar into some existing pipeline, allowing us to ensure that the analyzer and ANTLR grammar are in sync in terms of what they implement and specify, respectively.

The main risk that I see is that the Java target is better maintained, and there's a possibility that the Dart target gets abandoned. However, there's reason to believe that the probability of that is not as high as it might appear, as [for the past three years, the Dart target has received plenty of contributions](https://pub.dev/packages/antlr4/versions) that have kept it up to date.

@eernst how strongly do you feel about having Java bindings, and what do you think about moving from Java to Dart? I can submit a PR if you have no objections.

**Comment by eernstg** [comment]
I actually thought about doing that already a while ago, and I'm certainly not against the idea. However, it might cause some problems during continuous integration testing. I'm asking around in order to learn more.

**Comment by modulovalue** [comment]
> However, it might cause some problems during continuous integration testing. I'm asking around in order to learn more.

@eernstg did you learn something that would block us from supporting Dart actions instead of Java actions in Dart.g? Would you mind if I submitted a Dart.g that uses actions written in Dart instead of Java or is it unlikely that such a change would land?

**Comment by eernstg** [comment]
@modulovalue, that submission would be very welcome! It would be convenient if the new Dart.g is located in `$SDK/tools/spec_parser/dart_spec_parser` such that we can continue to use the Java based spec parser (presumably just for a while until everything is working well with the Dart based spec parser). We would then have a lot of freedom to switch to the Dart based spec parser for different purposes when we're ready.

**Comment by modulovalue** [comment]
Thank you @eernstg!

Fixed by: https://github.com/dart-lang/sdk/pull/54781 / https://dart-review.googlesource.com/c/sdk/+/349408
