### ISSUE TITLE
[analyzer] Spurious `unused_element`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54543]
Consider the following library:

```dart
// Library 'n010lib.dart'.

typedef E<X> = _E<X>;

extension type _E<X>._(X x) {
  _E.named(X x) : this._(x);
}
```
This library gives rise to the following diagnostic when processed by the analyzer (6672353e0f2d5ca8da93bd92d3c068d52564b885):
```
Analyzing n010lib.dart...              0.4s

   info • n010lib.dart:6:6 • The declaration '_E.named' isn't
          referenced. Try removing the declaration of '_E.named'. •
          unused_element

1 issue found.
```
However, it isn't true that `_E.named` is known to be unused. For example, we can use it from a library `n010.dart` with the following contents:
```dart
// Library 'n010.dart'.
import 'n010lib.dart';

void main() {
  E<int>.named(1);
}
```
The point is that `_E` should not be considered to be a private type when it has been made reachable via a type alias.

**Comment by bwilkerson** [comment]
@srawlins
