### ISSUE TITLE
Analyzer prohibits non-bottom representation type for being a bottom type

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54548]
Examples:
```dart
extension type ENeverTQ<T extends Never>(T? n) {} // Analyzer bug.
extension type ENeverTSQ<T extends Never, S extends T>(S? n) {} // Analyzer bug.
extension type ENeverTQS<T extends Never, S extends T?>(S n) {} // Analyzer bug.
```
The analyzer (Dartpad, master branch) rejects these declarations, saying that `T?`/`S?`/`S` is not allowed to be a bottom type.
It is not a bottom type, so it should be allowed.
(Possibly just a case of forgetting to check the nullability of a type variable when checking if it's a bottom type?)

CFE has no issue.

The code
```dart
extension type ENeverQ(Never? n) {}
```
is, correctly, accepted, so it's probably only an issue for type variables.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/345440
