### ISSUE TITLE
Analyzer allows user-extension operators in constant expressions.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54545]
Example:
```dart
extension type const ExInt(int value) implements int {
  num operator +(num other) => value + other;
}
void main() {
  const c = ExInt(1) + 1;
}
```
This gives no analyzer error. It should, since it's only a valid constant expression when `+` denotes the *instance* member of `int`. The invocation of `ExInt.operator+` is not a valid constant operation.

**Comment by eernstg** [comment]
Note the overlap with https://github.com/dart-lang/sdk/issues/54532.

**Comment by srawlins** [comment]
This was fixed at some point; an error is now reported at DartPad.
