### ISSUE TITLE
Support Multi-Case Switch Statements with the "Convert to switch expression" VScode code action

### ISSUE THREAD

**Issue by verygoodstefan** [dart-lang/sdk#54567]
Note: I originally [raised this issue in dart-code](https://github.com/Dart-Code/Dart-Code/issues/4909), and was directed to raise it here.

There's a neat code action to convert switch statements into expressions that take advantage of Dart 3's pattern matching:
 
![Screenshot 2023-12-20 at 10 46 01 AM](https://github.com/Dart-Code/Dart-Code/assets/125310677/7ec00b88-fc7f-436b-a778-e3fe029e9aea)

Unfortunately, it does not work with switches with multiple cases giving the same return value:

![Screenshot 2023-12-20 at 10 46 15 AM](https://github.com/Dart-Code/Dart-Code/assets/125310677/340c5637-94c0-4f35-b7d6-9845876b75a2)

It would be nice to be able to convert a multi-case switch like the following:

```
String myMultipleReturnEnumStatement(MyEnum enumVal) {
  switch (enumVal) {
    case MyEnum.first:
    case MyEnum.second:
    case MyEnum.third:
      return 'first, second, or third';
    case MyEnum.fourth:
    case MyEnum.fifth:
      return 'fourth or fifth';
    default:
      return 'default';
  }
}
```

into:
```
String myMultipleReturnEnumStatement(MyEnum enumVal) {
  return switch (enumVal) {
    MyEnum.first || MyEnum.second || MyEnum.third => 'first, second, or third',
    MyEnum.fourth || MyEnum.fifth => 'fourth or fifth',
    _ => 'default',
  };
}
```

I published [a custom extension ](https://marketplace.visualstudio.com/items?itemName=shodgeskluck.dart-switch-converter) that supports this behavior, however, if it would be useful to enough people, it might be nice to have this behavior supported in the basic Dart VS code functionality.

* Dart version: 3.0.6
* Flutter SDK: 3.10.6

**Comment by bwilkerson** [comment]
That's very cool! And this is definitely the right issue tracker.

I'd love to see our support extended to cover this case, and I expect that it wouldn't be too difficult to do.
