### ISSUE TITLE
Sockets dart:io exceptions catching bug

### ISSUE THREAD

**Issue by EnriqueSanVic** [dart-lang/sdk#54570]
This tracker is for issues related to:

* Dart core libraries (`dart:async`, `dart:io`, etc.)

I'm developing a server program in Dart and I've run into a strange situation about exception handling in the `dart:io` library.

In my program I send large amounts of data and when the client closes the socket connection unexpectedly, exceptions are thrown:

- SocketException: Write failed
- SocketException: Broken pipe

In the socket write function in principle I catch the exception in the following way:

```dart
try {
      if (data is List<int>) {
        _socket!.add(data);
        return;
      }
      _socket!.write(data);
} on SocketException catch (ex, stacktrace) {
      Printer.error('Error when write in socket: $ex', stacktrace);
}
```

In the SecureServerSocket and Socket listeners I have configured the option cancelOnError in false.

The problem is because the SocketException is apparently catched and the program stops execution with exit code 255. It is as if it ignores the try catch and the exception transcends. 

The call stack gives me no information about where in my code the exception is thrown, this reinforces the hypothesis that it is an exception that somehow forces the program to stop.

The socket is also closed and destroyed elsewhere in the execution but I think I have ruled out the closing action as the culprit.

Exceptions examples:
```
Unhandled exception:
 SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 0.0.0.0, port = 443
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1246:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2004:15)
#2      _ExternalBuffer.readToSocket (dart:io/secure_socket.dart:1327:26)
#3      _RawSecureSocket._writeSocket (dart:io/secure_socket.dart:1089:16)
#4      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1035:13)
<asynchronous suspension>
```

and 

```
Unhandled exception:
SocketException: Broken pipe (OS Error: Broken pipe, errno = 32), address = 0.0.0.0, port = 443
```

I've been trying for many hours to find where in my code the exception occurs to catch it but nothing has worked, I think it could be a bug in the `dart:io` library. I would be grateful if someone could explain this strange behaviour. 

Thank you very much for your help.

**Comment by lrhn** [comment]
The `add` and `write` (which calls `add`) methods are non-blocking. If there is an error, it might not be reported immediately.
The [documentation](https://api.dart.dev/stable/3.2.4/dart-io/IOSink/add.html) says:
> This operation is non-blocking. See [flush](https://api.dart.dev/stable/3.2.4/dart-io/IOSink/flush.html) or [done](https://api.dart.dev/stable/3.2.4/dart-io/IOSink/done.html) for how to get any errors generated by this call.

**Comment by EnriqueSanVic** [comment]
The problem I think is that the exception is not raised by the onError listener of the Socket.

This is my socket listener function:

```dart
void _handleConnection(SocketHandler socketState, bool hasHttpsRedirection) {
    socketState.socket!.listen(
      (Uint8List data) async {
        // handle data 
      },
      onDone: () {
        socketState.socketIsClosedByClient();
      },
      onError: (Object error) {
        socketState.socketIsClosedByClient();
        Printer.error('Socket error: $error');
      },
      cancelOnError: false,
    );
  }
```

**Comment by EnriqueSanVic** [comment]
It's resolved with this: [https://stackoverflow.com/questions/32810051/cannot-catch-socketexception](https://stackoverflow.com/questions/32810051/cannot-catch-socketexception)

The exception must  be handled with the done Future after writing in socket:

```dart
Future<void> writeInSocket(Object data) async {
    if (_socketIsClosed) {
      print('Trying write in closed socket');
      return;
    }

    if (data is List<int>) {
      _socket!.add(data);
    } else {
      _socket!.write(data);
    }

    try {
      await _socket!.done;
    } catch (error) {
      _socketIsClosed = true;
      print('Socket done with error $error');
    }
  }
```
