### ISSUE TITLE
[CP] Disable dual mapping and write protection of code

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#54583]
### Commit(s) to merge

e9f51b853456fabd76c31e372b59bac46807184b, 3e0ae6da5fedfd8e0a135ac20c6e7932856b9333

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/345663

### Issue Description

* Users experience random crashes when running X64 Linux binaries within Docker on Apple Silicon Macs
* Users are unable to run Linux binaries inside WSL 

### What is the fix

* Remove dual mapping of code which is causing problems with Rosetta.
* Additionally disable write protection of code to avoid any accidental regressions in performance which were previously compensated by dual mapping of code.

### Why cherry-pick

Unlocks usage of Dart inside Linux emulation on Apple Silicon & Windows. 

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/54446, https://github.com/dart-lang/sdk/issues/48420, https://github.com/dart-lang/sdk/issues/45625, https://github.com/dart-lang/dart-docker/issues/172, https://github.com/dart-lang/sdk/issues/54581

**Comment by mkustermann** [comment]
@itsjustkevin LGTM

**Comment by itsjustkevin** [comment]
Cherry-pick approved, please merge @mraleph

**Comment by mraleph** [comment]
Merged.
