### ISSUE TITLE
Is it allowed to have invalid pointers in `Pointer<Void>`?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#54597]
Hi thanks for the sdk! When developing flutter_rust_bridge, I use `NativeFinalizer.attach`. However, its signature is:

```dart
  void attach(Finalizable value, Pointer<Void> token,
      {Object? detach, int? externalSize});
```

In my scenario, I want the token to be an integer (instead of a *real* pointer pointing to somewhere in the memory), so I wonder whether this is allowed?

More generally, the question is: When seeing a type `Pointer<Void>`, am I allowed to put in *arbitrary* non-negative integer values (as long as it is within range)? Or is there any implicit constraints? (I am just passing it around, not dereferencing the underlying memory)

If I am only using C, I will think this is definitely allowed, since pointers are just numbers. However, since I also use Rust, I know there can be extra optimizations and assumptions on types, e.g. something needs to be aligned, be not too large, be nonzero, etc. I have checked Dart's doc and does not find the answer, thus create this issue.

**Comment by mraleph** [comment]
You can put anything pointer sized there. Dart does not look at it (or assume anything about it) unless you ask it to dereference the pointer. 

You can also just allocate a box for you value and use that as a token, but of course I understand desire to avoid boxing small values.

**Comment by fzyzcjy** [comment]
Thank you, I see!
