### ISSUE TITLE
Failures on [vm] Add tests for missing write barriers in SuspendState suspend and clone....Revert "Update analyze_flutter_flutter.sh"

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#54590]
There are new test failures on [[vm] Add tests for missing write barriers in SuspendState suspend and clone....Revert "Update analyze_flutter_flutter.sh"](https://github.com/dart-lang/sdk/compare/78e5a3dd92baae117d50c58cae3b9eba4fa02563~...a6edfb5904704d6fade7433cb744a2b1655c4443).

The tests
```
vm/dart/gc/chunked_binary_trees_async_test/0 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_async_test/1 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_async_test/2 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_async_test/3 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_async_test/4 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_async_test/5 Timeout (expected Pass)
vm/dart/gc/chunked_binary_trees_async_test/6 Timeout (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-simarm_x64
vm-mac-debug-x64
```

These newly added tests are failing with timeouts on some bots.

@rmacnak-google Could you take a look?

**Comment by rmacnak-google** [comment]
Sigh, I thought I was including the slowest bots when I tried with the sanitizers...
