### ISSUE TITLE
Analyzer does not detect conflict between extension type representation getter and type name

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54593]
Example:
```dart
extension type E2(Object? E2) {} // No error.
```
A class or extension type may not have a member with the same name as the type itself. This is detected for other declarations:
```dart
class C {
  void get C {} // Cannot have member with same name as enclosing class
}

extension type E1(Object? _) {
  void get E1 => _; // Cannot have member with same name as enclosing class [sic]
}
```
The analyzer does not detect that the representation object getter is a member with the same name as the type.
CFE does. (Dartpad, master branch)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
We mostly rely on the parser to report `ParserErrorCode.MEMBER_WITH_CLASS_NAME`.
But the representation field in not quite the same as other class members.
So, apparently the parser does not report it, and instead some CFE mechanism does.
So, I will add the corresponding special case into the analyzer parser integration.
https://dart-review.googlesource.com/c/sdk/+/345829
