### ISSUE TITLE
[dart2js] Hint to use preamble needs new trigger

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#54596]
The hint that you may need to use a preamble on CLI is quite useful, but now it's triggering on normal web builds and Flutter web builds as they don't use `dart:html` anymore. I think the message will result in confusion for Dart and Flutter developers as it refers to an internal SDK directory.

I'm not sure what the logic could be now as `dart:js_interop` doesn't imply being used on web. Perhaps being compiled with `--server-mode`?

https://github.com/dart-lang/sdk/blob/1572bb563f523b2dcfcbc3bbd3ab575bcb7141d7/pkg/compiler/lib/src/js_emitter/startup_emitter/model_emitter.dart#L350-L353

**Comment by sigmundch** [comment]
Good point @parlough!

I think your idea of aligning it with server-mode is very reasonable. Oddly, just like we discussed in the other issue about the node-specific logic for windows, one day we wont have even the presence of `html` as a library and at that point server-mode may disappear, but we can cross that bridge when we get there.

**Comment by parlough** [comment]
> but we can cross that bridge when we get there.

Yeah it sounds like there are many fun discussions to be had :)

I was going to make this change, but I had no idea where/how to test the behavior. dart2js has so many interconnected parts 🧐, I get lost easily.
