### ISSUE TITLE
CFE does not report name clash between extension type and its type parameter.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54602]
A class's type parameter must not have the same name as the class.
The same naming conflict rules apply to extension types.
The CFE generally gets this right, but misses one case:
```dart
extension type E5<E5>(Object? _) {}
```
which does not show any error (Dartpad, master branch).

The similar class has an error:
```dart
class C5<C5> {}
```
with error:
```
Error: A type variable can't have the same name as its enclosing declaration.
class C5<C5> {} // Error on C5
         ^^
```

**Comment by chloestefantsova** [comment]
Addressed by https://dart-review.googlesource.com/c/sdk/+/346043.
