### ISSUE TITLE
[CP] Clean up maps in a type visitor to prevent a memory leak

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#54605]
### Commit(s) to merge

bdde1783f84c459a74553e875fe74cec00c225b6

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/346020

### Issue Description

A recent change that's already in beta, but not yet in the stable, is causing a memory leak. It should be visible on all platforms, even though our internal testing tool only works on Linux.

### What is the fix

The fix is to clean up the maps that were accumulating references over time to the objects that should have been otherwise released and garbage collected.

### Why cherry-pick

Cherry-picking is necessary to avoid shipping a stable version with the memory leak.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/54604

### Extra Info

The leak is visible when using the following internal testing command.

```
tools/bots/flutter/compile_flutter.sh --leakTest
```

In the presence of the leak the tool stops abruptly reporting the leak. In the absence of the leak the test runs for about an hour and doesn't report the leak.

**Comment by itsjustkevin** [comment]
@johnniwinther can you take a look at this cherry-pick request?

**Comment by johnniwinther** [comment]
LGTM
