### ISSUE TITLE
[DDC] debugging metadata is incorrect for record types

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#54609]
`getObjectMetadata` returns `dart:_runtime` library and `RecordType` class for a record type that is now an instance of `_Type` after change to the new type system.

**Comment by nshahan** [comment]
After talking yesterday I was thinking about this more and if we are calling `getObjectMetadata` on the value returned from a `.runtimeType` getter, then technically `dart:_runtime library` and `RecordType` were incorrect with the old type system too. That is the old internal representation and not what was returned from `.runtimeType` in the old type system. We probably should have always reported `dart:core` and `Type`, as the class along with RecordTypeKind.

**Comment by annagrin** [comment]
We probably never run into that case due to `runtimeType` being a getter in the old system and not showing getters before in VSCode
