### ISSUE TITLE
[CP] Fix handling of extension types in relational patterns.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#54612]
### Commit(s) to merge

973eca72f559493ee504bf694845d1389546ec39

### Target

Beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/345826

### Issue Description

The assignability rule for relational patterns using `==` and `!=` was implemented incorrectly when patterns were first implemented. The rule should have been:
> a compile-time error occurs if `C` is not assignable to `A?`.

(where `C` is the static type of the expression to the right of the relational operator, and `A` is the type of the formal parameter of the `operator==` declaration.)

What was implemented was:
> a compile-time error occurs if **NonNull**(`C`) is not assignable to `A`.

Prior to the introduction of extension types, it was extremely unlikely for a user to notice the difference. The difference was only observable if `C` took the form `FutureOr<T?>` for some `T`, and `A` was a subtype of `Object`. Since it is extremely rare for constants to have a static type based on `FutureOr`, this basically never came up (which explains why the mistake wasn't caught in testing).

However, with the introduction of extension types, the problem is much more severe, because by default, extension types extend `Object?` but not `Object`, and by default, the formal parameter of `operator==` has type `Object`. Which means that if no changes are made, then an attempt to use an extension type as the operand of an `==` or `!=` pattern will typically result in a bogus compile-time error. For example:

```dart
extension type const E(int i) {}

f(E e) {
  switch (e) {
    case == const E(0): // Error: The argument type 'E' can't be assigned to the parameter type 'Object'.
      print('E(0)');
    default:
      print('some other value');
  }
}
```

### What is the fix

The fix is to use the specified assignability rule for relational patterns, namely:
> a compile-time error occurs if `C` is not assignable to `A?`.

### Why cherry-pick

If we cherry-pick the fix, that will ensure that in every stable release of Dart that supports extension types, they can be used as the operand of relational patterns that use `==` or `!=`.  The fix is fairly targeted, since the affected code in the compiler is only executed when a relational pattern is encountered.

If we don't cherry-pick the fix, then either (a) users of Dart 3.4 and later will be able to use extension types as the operand of relational patterns that use `==` or `!=`, but if they publish a package containing such a usage, their package will fail to work on Dart 3.3. Or (b) we will have to update the bug fix to be language-versioned, so that language versions prior to Dart 3.4 preserve the buggy behavior.

IMHO, cherry-picking the fix is the best option.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/54594

### Extra Info

FYI, this problem was caught by a co19 test, and an incorrect fix was submitted in https://dart-review.googlesource.com/c/sdk/+/345082. The incorrect fix did not make it into the main branch before the beta cutoff.

**Comment by itsjustkevin** [comment]
@leafpetersen could you take a look at this cherry-pick?

**Comment by itsjustkevin** [comment]
Cherry-pick approved, you are good to submit the CL @stereotype441 🙂.
