### ISSUE TITLE
no longer suggest package imports for `dart:html` (and related) packages

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#54610]
For quick fixes and code completion, we suggest classes from dart:html when that library isn't imported, and offer quick fixes to add an import when there's an unresolved class. We should no longer suggest from the dart:html library (unless it's already imported). We're going to start recommending that people use `package:web` for new projects, and these existing quick fixes will make the migration story less clear. 

See https://api.dart.dev/main/95cad9c8a6911dc8feb93f0ee75acf52ea959bfe/index.html for the 'legacy' web libraries:

- dart:html
- dart:indexed_db
- dart:js
- dart:js_util
- dart:svg
- dart:web_audio
- dart:web_gl

If people are already using them that's fine, we just don't want to suggest adding an import for them.

Related discussion on https://github.com/dart-lang/web/pull/141#issuecomment-1889635935.

cc @kevmoo

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/348081

**Comment by bwilkerson** [comment]
> We're going to start recommending ...

🎉 

What's the time frame for this? We have users that are using the nightly builds, and I want to make sure that the alternative is available before we stop suggesting the current solution.

I know that there's additional tooling work that we are hoping to do (minimally some lints), but I don't know whether we want to try to finish that work before the proposed completion change.

**Comment by parlough** [comment]
> What's the time frame for this?

\cc @kevmoo 

> I want to make sure that the alternative is available before we stop suggesting the current solution...

The current replacements are all available in some form:

- [`dart:js_interop`](https://api.dart.dev/main/dart-js_interop/dart-js_interop-library.html)
- [`dart:js_interop_unsafe`](https://api.dart.dev/main/dart-js_interop_unsafe/dart-js_interop_unsafe-library.html)
- [`package:web`](https://pub.dev/packages/web)

I am curious is the suggested change if a library doesn't import it or a package doesn't? Some app and package developers may not have a chance to migrate yet or might choose to stay on a Dart version with `dart:html` and not surfacing suggestions could be quite painful. Personally, I still like a toggle of some sort as an intermediate step (https://github.com/dart-lang/sdk/issues/54347) towards this point.

**Comment by devoncarew** [comment]
The doc changes for this recommendation have already landed (eg. see https://api.dart.dev/main), and package:web is already something people can use (dartpad has migrated, flutter, ...).

Note that the intention here isn't to prevent people from using dart:html, but that we don't re-add imports to it when they're in the process of migrating to package:web.

cc @kevmoo wrt timing and messaging

**Comment by kevmoo** [comment]
We should be careful pushing the ENTIRE ecosystem here. Like we don't want warning showing up in Google3, etc.

I *think* this is okay for Dart 3.4. We're just talking about suggestions, right?

**Comment by devoncarew** [comment]
Yes, just suggestions to add the import; I think the comment here illustrates the problem best: https://github.com/dart-lang/web/pull/141#issuecomment-1889635935

**Comment by kevmoo** [comment]
> But is it ok for people on the nightly build to get it tomorrow, or for people on the dev release channel to get it next week?

Yep. See if we get any reports. A good canary in the coal mine.
