### ISSUE TITLE
CFE allows calling record with `call` field as a function.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54616]
Example:
```dart
void main() {
  var c = (call: (int x) => x);
  var v = c(1);
  Chk(v).staticType<E<int>>(); // CFE accepts if type is `int`.
  Chk(v).staticType<E<dynamic>>();  // Analyzer accepts if type is `dynamic`.

  var c2 = (call: intId);
  var v2 = c2(1);
  Chk(v2).staticType<E<int>>();

  var c3 = (call: <T>(T x) => x);
  var v3a = c3(1);
  Chk(v3a).staticType<E<int>>();
  var v3b = c3("a");
  Chk(v3b).staticType<E<String>>();
}

int intId(int x) => x;

class Chk<T> {
  const Chk(T value);
  void staticType<X extends E<T>>() {}
}
typedef E<T> = void Function<StaticType extends T>();
```

Both `c(1)` and `c2(1)` should be compile-time errors since their static type is not a function type,
and it's not a type which has a `call` method. It has a `call` getter, but that's not sufficient to allow a `.call` insertion to be performed.

The analyzer allows it, but then doesn't know what to do about it, so the type of the call ends up as `dynamic`.
The front-end allows it and gives the return type of the function.

See: https://github.com/dart-lang/language/issues/3558

**Comment by lrhn** [comment]
Just read https://github.com/dart-lang/sdk/issues/54351 where it's economically mentioned that we don't want `call` getters on records to be callable.

**Comment by johnniwinther** [comment]
@chloestefantsova Can you take a look at this for the CFE? (I don't think this is done in shared code)

**Comment by chloestefantsova** [comment]
> @chloestefantsova Can you take a look at this for the CFE? (I don't think this is done in shared code)

Sure! Will do.

**Comment by lrhn** [comment]
Since this is (probably) not shared code, I split it into an analyzer issue (#54651), and made this issue CFE-specific.

**Comment by chloestefantsova** [comment]
> Both `c(1)` and `c2(1)` should be compile-time errors

Am I right to assume the calls to `c(3)` should be compile-time errors as well?

**Comment by lrhn** [comment]
Yes. A record type is not a callable type since it doesn't have a `call` _method_.
Having a `call` getter doesn't apply, same as for any other type.

(It can accept an extension `call` method like any other type, if it doesn't have a member base-named `call`.)
