### ISSUE TITLE
10%+ regression of `UiMatrix` / ` SkeletalAnimation` on arm32

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#54621]
The change in https://github.com/dart-lang/sdk/commit/1827fcbf68bf74b2a7d13b6a189c65197bef0dd8 had 10%+ regressions on the `UiMatrix` / ` SkeletalAnimation` benchmarks. Seems to be 32-bit arm specific

@sstrickl could you take a look?

**Comment by sstrickl** [comment]
Starting investigation now.
