### ISSUE TITLE
[analyzer] Record type is not treated as a constant in the analyzer in `as` cast

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54620]
The code below works in VM but produces an `const_initialized_with_non_constant_value` error in the analyzer
```dart
extension type const IntET1(int _) {}
extension type const IntET2(int _) implements int {}

main() {
  const c1 = int;
  const c2 = (int,);
  const c3 = IntET1;
  const c4 = IntET2;
  const c5 = (IntET1,);
  const c6 = (IntET2,);
  const c7 = IntET1(1) as int;
  const c8 = IntET2(1) as int;
  const c9 = (IntET1(1),) as (int,); // const_initialized_with_non_constant_value. Const variables must be initialized with a constant value.
  const c10 = (IntET2(1),) as (int,); // const_initialized_with_non_constant_value. Const variables must be initialized with a constant value.
  const c11 = [IntET1(1)] as List<int>;
  const c12 = [IntET2(1)] as List<int>;
}
```
Tested on `Dart SDK version: 3.4.0-edge.e871af629a70f2b954c57869891cf1ac69f41a5c (main) (Sun Jan 14 23:30:59 2024 +0000) on "linux_x64"`

**Comment by eernstg** [comment]
Right, I don't see a reason why `c9` and `c10` should be flagged as non-constant.

Also, the type cast should succeed at run time, so we shouldn't get the special "would throw at run time" error during constant evaluation (but we actually don't get that anyway).

All in all, I don't see why there would be an error at the declaration of `c9`, or at `c10`.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by sgrekhov** [comment]
The issue exists for `is T` as well

**Comment by lrhn** [comment]
Seems to depend on the syntax:
```dart
typedef Value = ({Object? value});
typedef typeof<T> = T;
void main() {
   const v1 = (value: 42) as Value;  // No error
   const v2 = (value: 42) as typeof<({Object? value})>;  // No error
   const v3 = (value: 42) as ({Object? value});  // Error!
}
```
It's the same type being tested in the three cases, but only one is an error, the one where the record type occurs directly in the syntax.

**Comment by srawlins** [comment]
Thanks for all the help! Constant records were implemented recently in analyzer, and this code no longer produces unexpected errors, as of at least 3.5.0-180.3.beta.
