### ISSUE TITLE
DateTime doesn't respect the ISO 8601 standard

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/sdk#54633]
My current timezone is GMT-3, which can be verified by this code:

```dart
final now = DateTime.now();

print(now.timeZoneName);
print(now.timeZoneOffset);
```

This prints `Brasilia Standard Time` and `-3:00:00.000000`.

I need to send data to a server that can have times in 3 different time zones, so it is important that date is correctly expressed in ISO 8601, but Dart has a *bug* that it doesn't add the timezone in the output, **as it is dictated by the ISO standard**

So,

```dart
final now = DateTime.now();
final serverData = now.toIso8601String();

print(serverData);
```

This prints `2024-01-15T18:33:28.414`, which is INCORRECT.

This extension method fixes the issue:

```dart
extension DateTimeExtensions on DateTime {
  String toISO() {
    return "${year}-"
        "${month.toString().padLeft(2, "0")}-"
        "${day.toString().padLeft(2, "0")}T"
        "${hour.toString().padLeft(2, "0")}:"
        "${minute.toString().padLeft(2, "0")}:"
        "${second.toString().padLeft(2, "0")}."
        "${millisecond.toString().padLeft(3, "0")}"
        "${timeZoneOffset.isNegative ? "-" : "+"}"
        "${(timeZoneOffset.inMinutes.abs() ~/ 60).toString().padLeft(2, "0")}:"
        "${(timeZoneOffset.inMinutes.abs() % 60).toString().padLeft(2, "0")}";
  }

  static DateTime fromISO(String isoDateTime) {
    return DateTime.parse(isoDateTime).toLocal();
  }
}
```

With this code, dates are correctly converted to a valid ISO 8601 string (with the correct time zone) and the parse is also correct (`fromISO` correctly returns a `isLocal = true` DateTime with the correct local time.

Notice that `DateTime.parse("2024-01-15T18:35:19.657-02:00")` also work, showing the time 1 hour before it is now (because my tz is -3), so, Dart can correctly parse ISO with time zone without any kind of issue, **BUT** it doesn't set correctly the `timeZoneName` and `timeZoneOffset`, so:

```dart
final a = DateTime.parse("2024-01-01T20:00:00.000Z");
final b = DateTime.parse("2024-01-01T20:00:00.000-03:00");
final c = DateTime.parse("2024-01-01T20:00:00.000-02:00");

print(a);
print(b);
print(c);
print(a.timeZoneName);
print(b.timeZoneName);
print(c.timeZoneName);
print(a.timeZoneOffset);
print(b.timeZoneOffset);
print(c.timeZoneOffset);
```

Shows 

```console
2024-01-01 17:00:00.000
2024-01-01 20:00:00.000
2024-01-01 19:00:00.000
Brasilia Standard Time
Brasilia Standard Time
Brasilia Standard Time
-3:00:00.000000
-3:00:00.000000
-3:00:00.000000
```

Which is counter-intuitive, but correct (after all, 20:00 at GMT-02 is 19:00 at GMT-3) and only local time matters on client anyways.

Problem is that we need to know what TZ a datetime was when it was recorded to a local database or sent to the server (and, no, I don't want to use the crappy unix timestamp, nor force all my systems to use UTC, since almost 90% of my country population lives at GMT-03).

So, please, fix the `DateTime.toIso8601String` to actually output a ISO 8601 compliant string, as shown in the above extension. **This is important for data serialization!!!**

**Comment by mraleph** [comment]
I think the answer is given here: https://github.com/dart-lang/sdk/issues/54422#issuecomment-1864870391

@lrhn can you comment on this?

**Comment by lrhn** [comment]
Yes, the linked comment describes the situation correctly.

A local-time `DateTime` is not in a covered time zone.

When you write it to a string and read it back, you get the same local-tone value back. That wouldn't work if it wrote a time zone.

There is no way for a `DateTime` to represent UTC+3. It can be local time, where local time happens to be UTC+3, but that's not a property of the `DateTime` itself.

**Comment by JCKodel** [comment]
It doesn't matter. The only thing it matters is to output the `DateTime.timeZoneOffset` in the `DateTime.toISO8601String()`.

It doesn NOT matter what kind of TZ (or none) DateTime uses, but it MATTERS to serialize the DateTime correctly informing the TZ offset, **WHICH DART ALREADY HAS ACCESS TO**.

**Comment by lrhn** [comment]
The output of `toIso8601String()` is a correct ISO-8601*local time* format, representing that the time it represents is a local-time `DateTime`.

It's not the output that you *want*, but it is a perfectly valid result for *what it is* and what it wants to achieve (that `DateTime.parse` on the result gives the same object back).

So your problem is that you don't have a way to get a string which includes that `-03:00`. (Other than appending it manually, which I can see is not optimal).

A way to get such a string would be a fair request. We could add functionality to allow that, maybe a flag like `toIso8601String(includeLocalTimeZone: true)`, which would be documented as generating a string which will *not* give an equivalent `DateTime` if parsed back.

The currently recommendation is to use UTC-`DateTime` for any communication, and only use local-time `DateTime` objects for displaying locally. (Even then, one should worry that "locally" migth be a laptop crossing a time zone boundary.)

**Comment by JCKodel** [comment]
I got it. Let's make the language harder to use because of reasons and fuck the community.

Noted.
