### ISSUE TITLE
[dart:io] stdio handle is being invalid in git bash in Windows

### ISSUE THREAD

**Issue by codesculpture** [dart-lang/sdk#54630]
While Analyzing this https://github.com/dart-lang/sdk/issues/54588, 
I came to address this same issue in deno https://github.com/denoland/deno/issues/21950

The Stdio Handle is being invalid in git bash (these cases are positive in powershell), so i guess there could be different resource id for stdio for git bash, since i guess git bash window is generated differently than powershell.

This below program would throw an error in git bash (Windows),
```dart
import "dart:io";

void main(){
        stdin.echoMode = false;
        stdin.lineMode = false;
        print(stdin.lineMode);
}

```

Error: 
```
Unhandled exception:
StdinException: Error setting terminal echo mode, OS Error: The handle is invalid.
, errno = 6
#0      Stdin.echoMode= (dart:io-patch/stdio_patch.dart:85:7)
#1      main (package:playground/lineMode.dart:4:8)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by codesculpture** [comment]
Yes, the problem is that `GetStdHandle` would return the redirected handle which is piped to original handle, this is happens from `mintty` (git bash) by `SetStdHandle`, so `SetConsoleMode` could actually expect a original pipe handle not a piped handle. We need to retrieve the original handle (seems its possible, read from `SetStdHandle`).

**Comment by codesculpture** [comment]
> The standard handles of a process may have been redirected by a call to SetStdHandle, in which case GetStdHandle will return the redirected handle. If the standard handles have been redirected, you can specify the CONIN$ value in a call to the CreateFile function to get a handle to a console's input buffer

From [here](https://learn.microsoft.com/en-us/windows/console/setstdhandle)

We need to get the original input handle, through `CreateFileA` when the stdio is opened in `pipe` mode.

**Comment by brianquinlan** [comment]
I'm calling this a P3 because running in git bash on Windows is probably a fairly rare use case.

**Comment by notAravind** [comment]
I used to believe git bash is the only good terminal until windows 11 introduced their new terminal, so i guess many windows users still using git bash, but the only rare thing is would someone changing the `lineMode` and `echoMode` during runtime.

**Comment by codesculpture** [comment]
I used to believe git bash is the only good terminal until windows 11 introduced their new terminal, so i guess many windows users still using git bash, but the only rare thing is would someone changing the `lineMode` and `echoMode` during runtime. Btw, i got the solution will raise a PR and let u know @brianquinlan :) (sorry for the delay)

**Comment by codesculpture** [comment]
https://github.com/dart-lang/sdk/pull/54799#discussion_r1476931352 as @aam mentioned that updating modes on console input handle would give false success to the user, since updating modes on console input handle by `CreateFile` would not actually updating the redirected pipe handle in mintty, this been reported seems it was solved but still cant understand how its been fixed
Heres the mintty issue https://github.com/mintty/mintty/issues/56

**Comment by codesculpture** [comment]
After digging in seems the git bash throw this only when env variable `ConPTY` is false, as @mintty suggested here https://github.com/mintty/mintty/issues/56#issuecomment-1926597500 , we can enable `ConPTY` and `SetStdHandle` would not throw error. So nothing from dart handled here, but it only works on latest windows sdk version 10.0.22621 which is different from dart's current windows sdk version, are we plan to upgrade windows sdk version?

**Comment by codesculpture** [comment]
After digging in seems the git bash throw this only when env variable `ConPTY` is false, as @mintty suggested here https://github.com/mintty/mintty/issues/56#issuecomment-1926597500 , we can enable `ConPTY` and `SetConsoleMode` would not throw error. So nothing from dart handled here, but it only works on latest windows sdk version 10.0.22621 which is different from dart's current windows sdk version, are we plan to upgrade windows sdk version?

**Comment by aam** [comment]
> but it only works on latest windows sdk version 10.0.22621 which is different from dart's current windows sdk version

What do you refer to as dart's current windows sdk version?
What did you have to do to make dart sample program work besides setting `ConPTY` environment variable?

**Comment by codesculpture** [comment]
https://github.com/dart-lang/sdk/blob/main/build/toolchain/win/setup_toolchain.py#L187 here we have a older version of windows SDK , if we change that version to 10.0.22621is not throwing error when ConPTY is on while executing above program, i locally builded dart with the windows sdk version 10.0.22621 and ran the above program in git bash while ConPTY is on, the reason is worked on this windows sdk version is they might support conpty in newer version only but not sure since i cant find any release notes or change log for windows sdk

**Comment by aam** [comment]
Ah, got you. Moving up the dependency on sdk version seems reasonable, especially since chromium is already on that version https://chromium.googlesource.com/chromium/src/+/refs/heads/main/build/toolchain/win/setup_toolchain.py#25.

**Comment by codesculpture** [comment]
Finally i have one reason to update sdk version thanks to chromium and thanks @aam for refering this.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/350655 with proposed update of windows sdk version

**Comment by codesculpture** [comment]
Seems there are bunch of files including windows sdk version, needs to change? https://github.com/dart-lang/sdk/blob/main/tools/generate_idefiles.py#L87-L90

**Comment by aam** [comment]
Good point @codesculpture . @dcharkes what do you think? Are hardcoded paths should be updated or rather todo addressed?

**Comment by dcharkes** [comment]
> Good point @codesculpture . @dcharkes what do you think? Are hardcoded paths should be updated or rather todo addressed?

No strong opinion. Whatever works. 👍  Thanks for noticing @codesculpture!

**Comment by codesculpture** [comment]
Changing version could be done in a single place but here we seem to do it in multiple places also this (generate_idefiles.py) has some hardcoded paths to sdk with some random hashes is this necessary? Since it doesnt break anything when i changed the version only in setup_toolchain.py 

This may out of the scope of this issue, but just asking this out of my curiosity :)

**Comment by dcharkes** [comment]
> Changing version could be done in a single place but here we seem to do it in multiple places also this (generate_idefiles.py) has some hardcoded paths to sdk with some random hashes is this necessary? Since it doesnt break anything when i changed the version only in setup_toolchain.py
> 
> This may out of the scope of this issue, but just asking this out of my curiosity :)

If you can make the script work with the paths, it would be nicer if it's not hardcoded. But I vaguely remember that not being trivial (hence why I landed hardcoded paths to begin with). I don't want to block landing an update to the toolchain by requiring someone to clean up the mess. But feel free to clean up if you want. 😄

**Comment by codesculpture** [comment]
The reason why i raised this question was i actually planned to upgrade the sdk version by myself but i saw that hardcoded patha which has hashes as part of its path and i confused and planned to seek help from someone from dart.

And yeah i also dont have a thought to block this sdk upgrade due to this hardcoded path issue. I will try to clean this seperately

Thanks for the info @dcharkes :)

And @aam just post an update here whenever the fix is landed, then this can be closed :)

**Comment by codesculpture** [comment]
This been merged into main by @aam, closing this

Summary: 
To make SetConsoleMode work in git bash ConPTY must be enabled since its not enabled by default, to enable that as @minnty mentioned here https://github.com/mintty/mintty/issues/56#issuecomment-1926597500 `echo ConPTY=on >> ~\.minttyrc` and the windows native operations such as SetConsoleMode would work and seems this was only supported in latest windows sdk version (10.0.22621) so all dart is upgrading to that version with no objection because of chromium is already in that version :)
