### ISSUE TITLE
Failures on [VM/Service] Include newline in the stdout service event

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#54641]
There are new test failures on [[VM/Service] Include newline in the stdout service event](https://dart-review.googlesource.com/c/sdk/+/346084).

The tests
```
pkg/vm_service/test/stdio_newline_test Timeout (expected Pass)
service/capture_stdio_test/dds Timeout (expected Pass)
service/capture_stdio_test/service Timeout (expected Pass)
service/dds_stdout_stderr_history_test/dds Timeout (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-x64
vm-aot-mac-release-arm64
vm-aot-win-release-x64
vm-linux-debug-x64
```

Logs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8758719036256220721/+/u/test_results/new_test_failures__logs_

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/346685 should account for the failures
