### ISSUE TITLE
[analyzer] Implement error about awaiting a type that is incompatible with await

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54648]
This is the analyzer specific issue for https://github.com/dart-lang/sdk/issues/54647 which has the details.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by stereotype441** [comment]
An update on the state of things:

The initial specification for this error was made in https://github.com/dart-lang/language/pull/3560 on Jan 17. The specification was updated in https://github.com/dart-lang/language/pull/3598 on Jan 31.

The analyzer implemented the initial specification in adee0a23999661d7e3c9d25ea44e3fbd399252aa on Feb 9. It has not implemented the update yet, as evidenced by [these test failures](https://dart-current-results.web.app/#/filter=language,await_incompatible_test).

We (the language team) would like to get this finished ASAP (see https://github.com/dart-lang/sdk/issues/54647#issuecomment-1977014439 for further details). Looking at the code, I believe there's not much work to do. I'll coordinate with @scheglov.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/355500
