### ISSUE TITLE
Timeout on http_big_header_test

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#54655]
There are new test failures on [[VM/vm_service] Fix for https://github.com/dart-lang/sdk/issues/54641](https://github.com/dart-lang/sdk/commit/c539f57b0029f60a9385f63bedab7e1a4d8da48f).

The tests
```
standalone/io/http_big_header_test Timeout (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-simarm_x64
```

**Comment by a-siva** [comment]
This is a duplicate of https://github.com/dart-lang/sdk/issues/52110
