### ISSUE TITLE
Clarify that `.name` can be used on enum values in the API docs

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#54679]
I keep forgetting you can use `.name` because the only sign that it exists in the `Enum` documentation is the in-passing mention that `Enum` has an extension, without mentioning why. It would be nice for the docs to be clearer.

I tried [submitting a PR](https://github.com/dart-lang/sdk/pull/53164) to fix this but after more than five months of trying to get it landed I gave up.

**Comment by a-siva** [comment]
> I tried [submitting a PR](https://github.com/dart-lang/sdk/pull/53164) to fix this but after more than five months of trying to get it landed I gave up.

Looks like @lrhn reviewed and approved the CL, why not land it?

**Comment by parlough** [comment]
Aside from the CL landing, which it should, I'm just making sure to note there is a pressing issue to solve this from a broader perspective:

We need to think a lot about how to better surface extensions in the API docs as well, outside of one-off solutions like these, as JS interop (and other forms of FFI) rely on them heavily. Issue: https://github.com/dart-lang/dartdoc/issues/2021

**Comment by Hixie** [comment]
> Looks like @lrhn reviewed and approved the CL, why not land it?

I have no idea (I don't have commit access so it's not up to me).

**Comment by parlough** [comment]
Fix landed in https://github.com/dart-lang/sdk/commit/64b03d1998faa78510375a390597a68a2ffe4b0e, thanks @Hixie!
