### ISSUE TITLE
Remaining tasks for allowing flutter tools to use `dart compile wasm` instead of invoking dart2wasm AOT snapshot & wasm-opt directly

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#54675]
Here's a list of remaining things we probably need to do before `dart compile wasm` can be used by flutter tools (right now it invokes the dart2wasm AOT snapshot burried in our SDK directly and `wasm-opt` with it's own set of binaryen flags):

* Performance 16x slower (see below)
* Support `-D` defines
* Support `--dart-sdk` & `--platform`
* Support `--import-shared-memory` & `--shared-memory-max-pages`
* Support `--depfile`
* Support passing through arbitrary args to dart2wasm (may also be used to do the above) - similar to (`--extra-gen-snapshot-options` in VM)

**Performance**
`dart compile wasm` is running the dart2wasm compiler in it's implementation (it doesn't use the dart2wasm AOT snapshot). Though the DartDev AppJIT training doesn't include dart2wasm compilation. That means the code will run slow.

It takes 8.5 seconds to run `dart compile wasm` vs 0.5 seconds by running the AOT snapshot (what flutter does):
```
% echo 'main() {}' > hello.dart

% time out/ReleaseX64/dart-sdk/bin/dart compile wasm --no-optimize hello.dart
*NOTE*: Compilation to WasmGC is experimental.
The support may change, or be removed, with no advance notice.

Generated wasm module 'hello.wasm', and JS init file 'hello.mjs'.
out/ReleaseX64/dart-sdk/bin/dart compile wasm --no-optimize hello.dart  12.87s user 1.81s system 173% cpu 8.471 total

% time out/ReleaseX64/dart-sdk/bin/dartaotruntime out/ReleaseX64/dart-sdk/bin/snapshots/dart2wasm_product.snapshot --platform=$PWD/out/ReleaseX64/dart-sdk/lib/_internal/dart2wasm_platform.dill --dart-sdk=$PWD/out/ReleaseX64/dart-sdk hello.dart hello.wasm
out/ReleaseX64/dart-sdk/bin/dartaotruntime    hello.dart hello.wasm  0.48s user 0.15s system 111% cpu 0.564 total
```

It's a little unclear to my why we wouldn't just run the dart2wasm AOT snapshot that we already bundle in the SDK for doing the compilation.

/cc @mit-mit

**Comment by mit-mit** [comment]
About the performance part, I believe @bkonyi and @a-siva have been looking at running all of dartdev as AOT. Any news about that?

**Comment by a-siva** [comment]
We could switch the implementation of 'compile dart2wasm' to spawn a process using the AOT snapshot instead of the way it is currently run (included in dartdev appJIT with no training for dart2wasm). This might speed it up. It appears to already spawn a process for the optimize step.

Work on running dartdev itself in AOT mode is progressing, we should not wait for that to complete. Let me take a look at switching the implementation and see how fast it gets.

**Comment by mkustermann** [comment]
> We could switch the implementation of 'compile dart2wasm' to spawn a process using the AOT snapshot instead of the way it is currently run (included in dartdev appJIT with no training for dart2wasm). This might speed it up. It appears to already spawn a process for the optimize step.

Already made [cl/347902](https://dart-review.googlesource.com/c/sdk/+/347902) to do that.

Though it's still meaningfully slower than running the AOT snapshot directly, seemingly going via DartDev middle man adds 1 second (which seems extraordinary high given that does very little except for shelling out to subprocesses).

**Comment by mkustermann** [comment]
I've just landed https://github.com/flutter/flutter/pull/143298 which makes flutter now use `dart compile wasm`. That will conclude what I've planned here.

Though I'd like to repeat what I wrote above:

> Though it's still meaningfully slower than running the AOT snapshot directly, seemingly going via DartDev middle man adds 1 second (which seems extraordinary high given that does very little except for shelling out to subprocesses).

I think the owners of dartdev should continue optimizing the performance of various `dart <command>`s. It's not as fast as it should be.
