### ISSUE TITLE
Analyzer claims record type cannot match itself as part of a `FutureOr`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54686]
Example:
```dart
  FutureOr<(int,)> fri = (1,) as dynamic;
  print(switch (fri) {
    (int,) _ => 1,  // Analyzer warning.
    Future<(int,)>() => 2,
  });
```
The analyzer (DartPad, master branch) warns:
```
The matched value type 'FutureOr<(int,)>' can never match the required type '(int,)'.
```
which is clearly incorrect.

This only appears to happen for `FutureOr` of something containing a record type, and a pattern which is a record type, whether aliased or not.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/347643
