### ISSUE TITLE
[analysis_server] Shouldn't include dev dependencies in suggestions within `/bin`

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#54684]
The analysis server includes dev dependencies in completion suggestions within the `/bin` directory, but correctly does not within `/lib`. It should not include them for `/bin` either.

Tested on 3.2.5 and current `main`: https://github.com/dart-lang/sdk/commit/cb16f98c0a4d24b3eeb3f31cd332d582f0b9d070

Reproduced with IJ and VSCode.

**Comment by srawlins** [comment]
Oooh love it. Or anywhere outside `lib/`.

**Comment by srawlins** [comment]
Ah I see. Yes, they should not be suggested for files in `bin/`. Your original description is accurate.
