### ISSUE TITLE
Simple dart script triggers a large number of GCs when fetching from bbc.co.uk with HttpClient.get() and not consuming the response stream

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#54692]
I opened the Logging page in DevTools to test something and was greeted by a huge number of apparent GC events per second:

![image](https://github.com/dart-lang/sdk/assets/1078012/827dadb8-507e-48f5-8f14-34f3ee9d0fc8)

The script was mostly idle (it does a HTTP request and then sleeps for 30s). I can reproduce from the terminal by running the script with `dart --observe run bin/foo.dart`, clicking the DevTools link and then going to the Logging page. Occurs in 3.2.2 stable and a recent bleeding-edge build.

The code I'm using to test is:

```dart
import 'dart:io';

Future<void> main(List<String> arguments) async {
  var client = HttpClient();
  while (true) {
    var request = await client.getUrl(Uri.parse('https://www.bbc.co.uk/'));
    var response = await request.close();
    print('Status code: ${response.statusCode}!');
    await Future.delayed(const Duration(seconds: 30));
  }
}
```

It's not clear why the GC events are being recording with such high frequency. A number of changes to the code prevent it from occurring, including:

- Fetching `https://example.org` instead of the BBC page
- Calling `await response.drain()`
- Calling `response.listen()` (for example `response.listen((event) {}, onDone: () => print('Done!'));`)

(cc @bkonyi @brianquinlan )

**Comment by rmacnak-google** [comment]
The generational hypothesis is holding extremely well in this program, so the heap never grows from its starting size and there are frequent, fast scavenges.

The units on that page are incorrect. It should say microseconds, not milliseconds. (Compare to the timeline events.)

**Comment by DanTup** [comment]
> the heap never grows from its starting size and there are frequent, fast scavenges.

Does that mean this is working as expected? (any guesses why the behaviour is different for other pages or if I consume the stream?).

> The units on that page are incorrect. It should say microseconds, not milliseconds.

Thanks - I'll file an issue in DevTools about that.

**Comment by rmacnak-google** [comment]
> Does that mean this is working as expected? (any guesses why the behaviour is different for other pages or if I consume the stream?).

Yes. Though it is unusual for the working setting of a program to be small enough for this to happen to this degree. Probably without actually consuming the data, the incoming data gets dropped pretty quickly and this server happens to send in smaller chunks. Normally a big chunk arriving or concatenating smaller chunks for consumption would be enough to encourage the heap to grow and GC to become less frequent.

**Comment by brianquinlan** [comment]
> The code I'm using to test is:
> 
> ```dart
> import 'dart:io';
> 
> Future<void> main(List<String> arguments) async {
>   var client = HttpClient();
>   while (true) {
>     var request = await client.getUrl(Uri.parse('https://www.bbc.co.uk/'));
>     var response = await request.close();
>     print('Status code: ${response.statusCode}!');
>     await Future.delayed(const Duration(seconds: 30));
>   }
> }
> ```
> 
> It's not clear why the GC events are being recording with such high frequency. A number of changes to the code prevent it from occurring, including:
> 
> * Fetching `https://example.org` instead of the BBC page
> * Calling `await response.drain()`

Forgetting about the GC question, not consuming the response of the HTTP request will potentially keep the HTTP connection alive until the server decides to disconnect you due to timeout.

**Comment by DanTup** [comment]
> not consuming the response of the HTTP request will potentially keep the HTTP connection alive until the server decides to disconnect you due to timeout.

Yeah, this code wasn't real I was just testing something on the logging/network pages and needed something that would cause a small amount of data to show up there (and apparently I just happened to hit a magic combination that caused quite a lot of data to turn up 😄)
