### ISSUE TITLE
[CP] [Stable][Beta] Please cherry pick 82520abfb1dd82b36e4a50371e71572b2bd95b73 and 84b38aee393d9afc5f2cc83b8a816230478d0646

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#54699]
### Commit(s) to merge

82520abfb1dd82b36e4a50371e71572b2bd95b73 and 84b38aee393d9afc5f2cc83b8a816230478d0646

### Target

stable and beta

### Prepared changelist for beta/stable

stable - https://dart-review.googlesource.com/c/sdk/+/347650
beta - https://dart-review.googlesource.com/c/sdk/+/347760

### Issue Description

The change fixes the following
- an issue that causes Flutter apps to freeze when breakpoints are added to multiple isolates at the same time
- an issue that causes Flutter apps to crash during hot reload

### What is the fix

- Use safepoint-safe RwLock for breakpoint locations locks
- Ensure setting breakpoints is lock-safe

### Why cherry-pick

Flutter app developers have encountered these scenarios effecting developer productivity.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/54650
https://github.com/flutter/flutter/issues/140878

**Comment by a-siva** [comment]
//cc @aam

**Comment by a-siva** [comment]
@mit commented with a SGTM on the other issue.

**Comment by a-siva** [comment]
@itsjustkevin thanks for taking care of the stable merge, should I go ahead and submit the beta branch CL ?

**Comment by mellowcello77** [comment]
Just checking how long this fix will take to be available? I've been very eagerly tracking and waiting for a resolution to this issue while I cant debug my projects. Appreciate your efforts on this.

**Comment by a-siva** [comment]
> Just checking how long this fix will take to be available? I've been very eagerly tracking and waiting for a resolution to this issue while I cant debug my projects. Appreciate your efforts on this.

I believe a hotfix release of Flutter is slated for today.

**Comment by DanTup** [comment]
Thank you! I just verified this on the new stable Flutter and all looks good :-)
