### ISSUE TITLE
[CP] [Stable] Please cherry pick 82520abfb1dd82b36e4a50371e71572b2bd95b73 and 84b38aee393d9afc5f2cc83b8a816230478d0646

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#54698]
### Commit(s) to merge

82520abfb1dd82b36e4a50371e71572b2bd95b73 and 84b38aee393d9afc5f2cc83b8a816230478d0646

### Target

stable and beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/347760

### Issue Description

The change fixes the following
- an issue that causes Flutter apps to freeze when breakpoints are added to multiple isolates at the same time
- an issue that causes Flutter apps to crash during hot reload

### What is the fix

- Use safepoint-safe RwLock for breakpoint locations locks
- Ensure setting breakpoints is lock-safe

### Why cherry-pick

Flutter app developers have encountered these scenarios effecting developer productivity.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/54650

**Comment by mit-mit** [comment]
SGTM

**Comment by a-siva** [comment]
Closing this as a duplicate of https://github.com/dart-lang/sdk/issues/54699. Will carry over @mits comment to the other issue.
