### ISSUE TITLE
fetch fails with package web

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#54701]
Figured I'd try `web`. Cracked open editor with SDK `3.4.0-11.0.dev` and tried this:

```dart
import 'dart:js_interop';

import 'package:web/web.dart';

Future<void> main() async {
  try {
    final response = await window.fetch('https://www.google.com'.toJS).toDart;
    print(response);
  } catch (e) {
    print('error: $e');
  }
}
```

Get error:
```
error: TypeError: Failed to fetch
```

**Comment by srujzs** [comment]
You may be coming across CSP issues, but the JS error isn't making that obvious. Opening the console gives me more info:

> Refused to connect to 'https://www.google.com/' because it violates the document's Content Security Policy.

**Comment by mnordine** [comment]
Thanks, I had not seen that. Should we keep this open so the developer experience is improved with a more descriptive error? Or close?

**Comment by srujzs** [comment]
I'll close for now, but if we think there's a better way for users to see the errors, it's worth sharing here for future reference.
