### ISSUE TITLE
Assembler::str on arm64 treats CSP as ZR without an assert or warning

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#54703]
If you happen to write:
```
__ str(CSP, Address(...));
```
It will happily compile and store a 0 at the address instead of the CSP.

That's all fine, just I expect the Assembler intends to assert about this (which is why CSP != R31 != ZR in constants_arm64.h).

I suspect the missing assert goes in:
```cc
  void EmitLoadStoreReg(LoadStoreRegOp op,
                        Register rt,
                        Address a,
                        OperandSize sz) {
    // Unpredictable, illegal on some microarchitectures.
    ASSERT((op != LDR && op != STR && op != LDRS) || a.can_writeback_to(rt));

    const int32_t size = Log2OperandSizeBytes(sz);
    const int32_t encoding =
        op | ((size & 0x3) << kSzShift) | Arm64Encode::Rt(rt) | a.encoding(sz);
    Emit(encoding);
  }
  ```
And it should ASSERT(rt != CSP)?  I'm not sure though (hence why I'm filing a bug).  Thanks!

**Comment by eseidel** [comment]
https://github.com/dart-lang/sdk/blob/main/runtime/vm/compiler/assembler/assembler_arm64.h#L1091
https://github.com/dart-lang/sdk/blob/main/runtime/vm/compiler/assembler/assembler_arm64.h#L2903
Is the code in question.

**Comment by eseidel** [comment]
And https://github.com/dart-lang/sdk/blob/main/runtime/vm/constants_arm64.h#L71 is the suggestion that calls which can be confused like this should assert (and some of them seem to).

**Comment by a-siva** [comment]
//cc @rmacnak-google

**Comment by parlough** [comment]
Thanks Ryan!

@eseidel Do Ryan's changes in https://github.com/dart-lang/sdk/commit/7fd8d79e9113220caef60d253bd8067abbfa3ac0 match what you were expecting/suggesting?

**Comment by eseidel** [comment]
lgtm, thanks!
