### ISSUE TITLE
Analyzer stuck in a loop

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#54708]
I am currently on the analyzer from 8a2f6495b3edb1fd65be203e82eb83cef4833cfc.
It has somehow gotten into a loop where `_requestedLibraries` contains one element that is "the same but different" to the element in `_resolvedLibraryCache`.

Standing at the return in this code:
https://github.com/dart-lang/sdk/blob/8a2f6495b3edb1fd65be203e82eb83cef4833cfc/pkg/analyzer/lib/src/dart/analysis/driver.dart#L1187-L1191

I get this:

```
$ p identityHashCode(_requestedLibraries.keys.single)
= 938137485
$ p identityHashCode(_requestedLibraries.keys.single.file)
= 3984166223
```

(and it continues to be that when it gets there again and again and again).

From the call to `_getResolvedLibrary` it uses the `library` to lookup in `_resolvedLibraryCache`.
The map `_resolvedLibraryCache` has one entry as well:

```
$ p identityHashCode(_resolvedLibraryCache.keys.single)
= 97408124
$ p identityHashCode(_resolvedLibraryCache.keys.single.file)
= 3984166223
```

Notice how the key is different but that the `file` inside it is the same.
So, in `_getResolvedLibrary` it looks up in `_resolvedLibraryCache` but doesn't find it because of this.
So it calls `_analyzeFile(library.file.path)`, i.e. pulls out the path of the file.
`_analyzeFile` looks it up via `_fsState.getFileForPath(path)` 

```
$ p identityHashCode(_fsState.getFileForPath(_resolvedLibraryCache.keys.single.file.path))
= 3984166223
```

So this gives the same `file` as we've had all along. So far so good.
It then does

https://github.com/dart-lang/sdk/blob/8a2f6495b3edb1fd65be203e82eb83cef4833cfc/pkg/analyzer/lib/src/dart/analysis/driver.dart#L1314-L1315
[...]
https://github.com/dart-lang/sdk/blob/8a2f6495b3edb1fd65be203e82eb83cef4833cfc/pkg/analyzer/lib/src/dart/analysis/driver.dart#L1428-L1433

But - given there's an infinite loop - to no surprise

```
$ p identityHashCode(_resolvedLibraryCache.keys.single.file.kind.library)
= 97408124
```

So just to point out the obvious:
```
$ p _resolvedLibraryCache[_resolvedLibraryCache.keys.single.file.kind.library]
= ResolvedLibraryResultImpl {  ⊞  }
$ p _requestedLibraries[_resolvedLibraryCache.keys.single.file.kind.library]
= null
```

i.e. we put the result in to `_resolvedLibraryCache` via this `library` key - but to no change as it's already there.
Then try to remove it from `_requestedLibraries` with the same key, but it doesn't do anything because there it's stored by another key.
It is thus left, we still have the entry in `_requestedLibraries` and we thus do another run and do the same thing again.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
This is a wonderful bug report, thank you so much.
It was super easy for me to reproduce.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/348082
