### ISSUE TITLE
classes that extend other classes not working when deployed to internet

### ISSUE THREAD

**Issue by psatoor1** [dart-lang/sdk#54726]
In general I have an application written in Dart that works fine inside Webstorm but doesn't work properly when loaded on the internet (using AWS).

I have class SpriteX extends Sprite.  SpriteX works fine on the internet.

I have class CurveX extends SpriteX.  CurveX works fine on the internet.

I have class CircleX extends CurveX.  CircleX does NOT work on the internet but it DOES work inside Webstorm.

You can reproduce this error by entering

      http://maths999.s3-website.eu-central-1.amazonaws.com/

in any browser.

When the app loads…

Enter 0025 in the search field at the top of the screen and the app DOES work.

Enter 0113 in the search field and the app does NOT work.

**Comment by lrhn** [comment]
Following the instructions, the browser console shows the error message:
```
Uncaught TypeError: Instance of 'minified:b4': type 'minified:b4' is not a subtype of type 'minified:a5
```

I can't debug minified code (our web compiler developers might be better), but if you try compiling without minification, it should be possible to which types are involved.

If it works locally, but not when deployed, could it be a difference between dev-compiler and dart2js?

**Comment by sigmundch** [comment]
The kind of error @lrhn noticed leads me to believe it's more likely a dev vs production discrepancy. Unfortunately, it's not possible for us to investigate only looking at the deployed app.

My recommendation would be:
* try to locally run the application in production mode. I'm not familiar with how webstorm integrates Dart, but the goal is to use the production compiler (aka dart2js).
* try disabling minification when you build the app to debug it locally (dart2js accepts a `--no-minify` flag, using `-O1` also works). If the integration from webstrom is via webdev or build_runner, you can probably configure these flags in the build.yaml configuration file.
* try to create a small example in Dart that it is OK to share publicly that reproduces the discrepancy.

**Comment by psatoor1** [comment]
Thanks for your reply.
I think I'll try the no minify compile option.
