### ISSUE TITLE
Multiple notifications that analysis is done sent to `dart analyze`

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#54738]
In a recent build of the SDK, with protocol logging added for debugging purposes, it was observed that the analysis server was sending multiple pairs of analyzing/not analyzing status notifications to `dart analyze`. This is a problem because `dart analyze` uses the first such notification as a signal that it has received all of the analysis error notifications that it's going to, but that signal is no longer valid.

This was observed while testing macros, so there's a chance that it only happens when macros are being used.

```
% dart analyze
Analyzing macro_try1...                /==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["/usr/local/google/home/jwren/samples/macro_try1"],"excluded":[]}}
-<== {"event":"server.connected","params":{"version":"1.35.0","pid":1955538}}
<== {"id":"1"}
\<== {"event":"analysis.errors","params":{"file":"/usr/local/google/home/jwren/samples/macro_try1/analysis_options.yaml","errors":[]}}
<== {"event":"analysis.errors","params":{"file":"/usr/local/google/home/jwren/samples/macro_try1/pubspec.yaml","errors":[]}}
<== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
|<== {"event":"analysis.errors","params":{"file":"/usr/local/google/home/jwren/samples/macro_try1/lib/test.dart","errors":[]}}
<== {"id":"2"}
<== {"event":"analysis.errors","params":{"file":"/usr/local/google/home/jwren/samples/macro_try1/lib/test2.dart","errors":[]}}
<== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
==> {"id":"3","method":"server.shutdown","params":null}
<== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
<== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
<== {"event":"analysis.flushResults","params":{"files":["/usr/local/google/home/jwren/samples/macro_try1/analysis_options.yaml","/usr/local/google/home/jwren/samples/macro_try1/pubspec.yaml","/usr/local/google/home/jwren/samples/macro_try1/lib/test.dart","/usr/local/google/home/jwren/samples/macro_try1/lib/test2.dart"]}}
<== {"id":"3"}
0.3s
No issues found!
```

**Comment by scheglov** [comment]
Apparently, there is an existing way to see the protocol: `dart analyze --diagnostics path/`.

**Comment by scheglov** [comment]
This is unrelated to macros, I can see it on `dartdev`.

**Comment by scheglov** [comment]
I also don't believe that this is a bug.

We asked AD to analyze the set of files, it switched to `working`, produced diagnostics, switched to `idle`.

The we asked to shutdown, this is a task in AD. It switched to `working`, did necessary disposing of AD (stopping macro executors, if any), switched to `idle`.

The protocol is not violated, all diagnostics produced before first `{"isAnalyzing":false}`.

**Comment by bwilkerson** [comment]
Excellent. Happy to not have a bug here.
