### ISSUE TITLE
List<Function> type resolution

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#54750]
I was trying to understand the type resolution of function types (case-1b below), and I came across an interesting type resolution (case-2a and case-2b below):

```dart
// ignore_for_file: unnecessary_type_check, prefer_function_declarations_over_variables

typedef Func<Return, Argument> = Return Function(Argument);

void main() {
  final f1 = (String y) => y;

  // case-1a
  print(f1 is Func<String, String>); // prints: true

  // case-1b
  print(f1 is Func<Object, Object>); // prints: false 

  // case-2a
  final f2a = (int x) => x;
  final list = [f1, f2a];
  print(list.runtimeType); // prints: List<(Never) => Object>

  // case-2b
  final f2b = (Object x) => x;
  final list2 = [f1, f2b];
  print(list2.runtimeType); // prints: List<(String) => Object>
}
```

I am assuming that case-1b has to do with how the the upper bounds are evaluated as explained here https://github.com/dart-lang/sdk/issues/54387#issuecomment-1859290687 by @eernstg. 

But as I was tinkering around, I came across case-2a and case-2b and I was surprised of the type resolution. I expected the type of both cases to be inferred as `List<Function>`.

> Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_x64"

**Comment by lrhn** [comment]
When figuring out the element type of a list literal by looking at the type of the element expressions, the compiler attempts to find the _least upper bound_ of the element expression types.

And out succeeds. Here, for 2a, it finds `Object Function(Never)`, which is an upper bound of `int Function (int)` and `String Function(String)`. (Not sure it's the last upper bound, since `Comparable<Object> Function(Never)` is lower, but it's _good enough_.)
And it _is_ below `Function`, so it's a better approximation of the least upper bound.

For 2b, type going by inference is again a supertype of both element expression types. You can test that both objects satisfy `is Object Function(String)`.

So this is working as intended.

**Comment by osaxma** [comment]
> For 2b, the type found by inference is again a supertype of both element expression types. You can test that both objects satisfy `is Object Function(String)`.

I think what confused me, and where I seem to have a misunderstanding, is how the function argument type is being resolved as a lower bound instead of an upper bound of the specified types. 

For example, in the following cases, with my prior understanding, I would've expected the opposite for all of them:

```dart
  print(((int x) => x) is Object Function(Object)); // prints false
  print(((int x) => x) is Object Function(Never));  // prints true

  print(((num x) => x) is Object Function(int));    // prints false
  print(((int x) => x) is Object Function(num));    // prints true
```
In other words, this is the type lattice I had in mind when I was looking at it, and I assumed `Object Function(Object)`, or `Function`, would be resolved:

```mermaid
graph TD
    subgraph "My Incorrect understanding"
        A(Object) --> B(Function)
        B --> C("Object Function(Object)")
        C --> D("int Function(int)")
        C --> E("String Function(String)")
        D --> F(Never)
        E --> F
    end
```

I would appreciate it if you would help me understand: why the type of the function argument seem to be resolved in different direction than that of the return type?

**Comment by osaxma** [comment]
I think after reading about [Covariance and contravariance (wikipedia)](https://en.m.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)), I understood that argument type in the Function constructor is contravariant which answers my previous question.

They also kindly mentioned in the article:
> ... programmers often find contravariance unintuitive

... and I had to agree with them 😅

Thanks a lot.

**Comment by lrhn** [comment]
Indeed, the graph is more like:
```mermaid
graph TD
    subgraph "Type hierarchy of int Function(int)"
        O("Object") --> F
        F("Function") --> ON
        ON("Object? Function(Never)") --> IN
        ON --> OI
        IN("int Function(Never)") --> NN
        IN --> II
        OI("Object Function(int)") --> II
        OI --> OO
        NN("Never Function(Never)") --> NI
        II("int Function(int)") --> NI
        II --> IO
        OO("Object? Function(Object?)") --> IO
        NI("Never Function(int)") --> NO
        IO("int Function(Object?)") --> NO
        NO("Never Function(Object?)") --> N           
        N("Never")
    end
```
In (covariant) return position, going from `Object?` to `int` to `Never` (or generally to a subtype) creates a subtype.
In contravariant parameter position, going from `Never` to `int` to `Object?`, or a any *super*type, creates a subtype.

And it's all about what subtyping means: [**Substitutability**](https://en.wikipedia.org/wiki/Liskov_substitution_principle). A value of the subtype must be usable where a value of the supertype is expected. A value of the subtype *is-a* value of the supertype, and satisfies all requirements that the supertype has. 
For a function, that means it must return *at most* the same values as the supertype, and must accept *at least* the same arguments that the code might pass to the supertype. 
Accepting more arguments is OK, someone expecting a supertype value won't be calling it with more than what the supertype accepts. Accepting fewer is not OK. 
Returning fewer results (only `int`s and not fx `num`) is also OK, the supertype *could* return `int`s, so a caller will not be surprised.

**Comment by osaxma** [comment]
It's pretty clear to me know -- thanks a lot for the detailed explanation, @lrhn  🙏🏽
