### ISSUE TITLE
InternetAddress does not support local mdns as address

### ISSUE THREAD

**Issue by guyluz11** [dart-lang/sdk#54751]
I am trying to create an `InternetAddress` instance with the local device mDNS name.

The mDNS is in my home **local network** (not in the www).

Example:
`InternetAddress('deviceMdnsName.local')`

Error:
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Invalid internet address deviceMdnsName.local

In my terminal I can ping `deviceMdnsName.local` successfully.

Calling the `InternetAddress` with the device IP does work.

I am running on Flutter Linux

```dart
flutter --version
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (6 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Comment by mraleph** [comment]
`InternetAddress` is naturally an _address_, not a host name. 

You need to use https://api.dart.dev/dev/3.4.0-47.0.dev/dart-io/InternetAddress/lookup.html if you want to resolve a host name to an address.

**Comment by guyluz11** [comment]
It seems that `InternetAddress.lookup` does not work on Android 14 (it is working on Flutter Linux).

**Comment by mraleph** [comment]
@guyluz11 

`InternetAddress.lookup` just calls `getaddrinfo`, which should work if mDNS is supported by the device (https://source.android.com/docs/core/ota/modular-system/dns-resolver). 

You should try testing if `adb shell ping6 deviceMdnsName.local` works and then test resolving host name from Java. 

If resolving from Java works, but from Dart does not, you should file an issue. 

There might also be some permission issue, e.g. `CHANGE_WIFI_MULTICAST_STATE` might be required for receiving multicasts over WiFi - meaning that mDNS might not work without that permission, though it is unclear from documentation.
