### ISSUE TITLE
[dtd] add a flag to disable secrets to the `dart tooling-daemon` command

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#54762]
When this flag is passed, the file system API should work without checking for project directories, and DTD should operate with the assumption that it does not need to generate a secret or check it anywhere.

This will be used for debugging purposes. When IDEs start DTD, they will still require a secret for setting project directories.

Naming: maybe `--disable-secrets` or `--no-secret`.

@CoderDake @bkonyi 

This is blocking https://github.com/flutter/devtools/issues/7107

**Comment by a-siva** [comment]
same question here, why is it an 'area-vm' issue? Sounds like a DTD issue ?

**Comment by CoderDake** [comment]
@kenzieschmoll How would you feel about this being '--unsecured' instead?

I feel like `--no-secret` implies that the functions requiring a secret, no longer need one. Which is different from the FileSystem service no longer checking the workspace directories

**Comment by kenzieschmoll** [comment]
Discussed offline. This is implemented at `--unrestricted` here: https://dart-review.googlesource.com/c/sdk/+/352921
