### ISSUE TITLE
Code completion: no `void` item when trying write `Future<void>`

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#54773]
Dart SDK 3.2.6, both IntelliJ IDEA and VS Code
```
Future<v|>
//      ^  caret here
```
**Expected:** `void` completion item is suggested 
**Actual:** Analysis Server doesn't return any completion items

P.S. Fun fact is that `void` item appears in this case:
```
Future<v|> foo
//      ^  caret here
```

**Comment by parlough** [comment]
I can reproduce this on `main` (https://github.com/dart-lang/sdk/commit/21b36928b6c55cf09cd31fcf564431600e7540b8).

**Comment by scheglov** [comment]
@bwilkerson

**Comment by bwilkerson** [comment]
I figured out why it's behaving this way. The parser is seeing the incomplete code and interpreting it to be the declaration of a function named `Future` with a type parameter and no return type, as if you'd written:
```dart
Future<v>() {}
```

As a result, the code completion engine thinks you're trying to complete the name of a type parameter, and we don't complete names at declaration sites.

If there's a name afterward, then it decides that the `Future<v>` is the type of a variable named `foo`, the `v` appears to be a type argument, and we know how to complete those.

It would be better if the parser recovered by assuming it was a top-level variable of the form `Function<v> s;`. There would be fewer synthetic tokens to create and it would be right more often. But if that proves to be too hard we could work around it.

I have a test written that I'll commit soon, either with or without a fix.

**Comment by bwilkerson** [comment]
Failing test added in https://dart-review.googlesource.com/c/sdk/+/354040.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/357382

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/357460

**Comment by keertip** [comment]
@scheglov , could this be the same issue as [#53302](https://github.com/dart-lang/sdk/issues/53302)?
