### ISSUE TITLE
FormatException: Invalid double   4,995

### ISSUE THREAD

**Issue by hiteshshimpi-55** [dart-lang/sdk#54778]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Dart core libraries : dart:core_patch
* Dart version: 3.1.5 Stable
* Using Windows

**Issue**: Whenever I am trying to parse a string eg. 4,132 the compiler gives me Format Exception. So the number string with (' , ') won't work. 

** Fix **: 
 ```
    String num = "4,995";
    try {
      double value = double.parse(num.replaceAll(',', ''));
      log(value.toString());
    } catch (e) {
      log(e.toString());
    }
```
here I tried to replace ( , ) with an empty character and it solved the problem.
Maybe we can add this method to the core library itself.  I am currently new to contribution and don't know if this issue is relevant or not.

**Comment by lrhn** [comment]
The `double.parse` function is only intended to parse the output of `double.toString`, or `num.toString`.
Thousands separators, alternative decimal separators, or any other non-standard notation is outside of its scope.

For what you're doing, you should probably use the `intl` package's [`NumberFormat`](https://pub.dev/documentation/intl/latest/intl/NumberFormat-class.html) class.
