### ISSUE TITLE
[CP][beta] Revert "[vm/ffi] Unwrap typed data in FFI calls"

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54771]
### Commit(s) to merge

None, no revert landed yet on main. Doing beta first as suggested by @athomas offline.

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/349320

### Issue Description

40094c8cfd41f8f76e61ae9041fdf5f932e743da introduces an API to `dart:ffi` that we later realized is problematic.

See the discussion in https://github.com/dart-lang/sdk/issues/54739#issuecomment-1914182960. TL;DR: FFIgen cannot run blindly on headers because it would need to make a decision on what Dart type to expose for a C type.

### What is the fix

Revert 40094c8cfd41f8f76e61ae9041fdf5f932e743da, so that we can work on introducing a better API for our users.

### Why cherry-pick

If we don't do a cherry pick, the new API will be added to Dart 3.3, and then we'd need to do a breaking change request for removing it again in Dart 3.4.

### Risk

medium

### Issue link(s)

https://github.com/dart-lang/sdk/issues/54739#issuecomment-1914182960

### Extra Info

Risk is medium: 
* The PR doesn't cleanly revert and is big. I have fixed all the merge conflicts and minimized the diff in https://dart-review.googlesource.com/c/sdk/+/349320.
* The revert itself is mostly only removing code, so I believe it does the right thing.

**Comment by vsmenon** [comment]
@mkustermann - what's your recommendation on reversion and risk?

**Comment by mkustermann** [comment]
> @mkustermann - what's your recommendation on reversion and risk?

Although it touches quite some code, it seems like a clean revert (very minor difference between first patch set and latest). Also IMHO we shouldn't be afraid of reverting (or cherry-picking for that matter) to beta/stable branches - we have an extensive CI we can and should rely on. So if the revert turns green: LGTM

It makes sense to not include this in the stable, as we plan on offering it in a more general way that works better for users.

**Comment by itsjustkevin** [comment]
@mkustermann and @dcharkes everything is green, please land.
