### ISSUE TITLE
General flakiness on vm-aot-win-debug-x64c and vm-win-debug-x64c

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54780]
Errors occurring in multiple flakes:

```
../../runtime/vm/virtual_memory_compressed.cc: 131: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 504: error: expected: os_thread != nullptr
```

On both vm-aot-win-debug-x64c and vm-win-debug-x64c.

(Adding these bots to the CI usually prevents CLs from landing due to 10 new different flakes on every run.)

Logs from the flakiness dashboard:

* https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8757412948138370577/+/u/test_results/ignored_flaky_test_failure_logs
* https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8757412948032523233/+/u/test_results/ignored_flaky_test_failure_logs
* https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8757503551568640001/+/u/test_results/ignored_flaky_test_failure_logs
* Log from 2023-09 https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8769190560677540561/+/u/test_results/ignored_flaky_test_failure_logs
* Log from 2023-07 https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8774898170669692225/+/u/test_results/ignored_flaky_test_failure_logs

@rmacnak-google Could you please take a look?

**Comment by alexmarkov** [comment]
Duplicate to https://github.com/dart-lang/sdk/issues/51170.
