### ISSUE TITLE
Debugger treats Streams that throw and have an error handler supplied through .listen() as uncaught

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#54788]
Consider the following example:
```dart
void main() async {
  _stream().listen(print, onError: print);
}

Stream<int> _stream() async* {
  for (var i = 0; i < 10; i++) {
    yield i;
  }

  throw Exception('Debugger always treats it as uncaught!');
}
```

Steps to reproduce:
1. Run `dart run --observe --pause-isolates-on-start streams.dart`
2. Open DevTools debugger
3. Select `Stop on uncaught exceptions`
4. Continue
5. Observe the debugger stop at throw even though the error is handled via listen.

However, if we rewrite the example to:
```dart
void main() async {
  try {
    await for (var item in _stream()) {
      print(item);
    }
  } catch (e) {
    print(e);
  }
}

Stream<int> _stream() async* {
  for (var i = 0; i < 10; i++) {
    yield i;
  }

  throw Exception('Debugger always treats it as uncaught!');
}
```

The debugger does not pause. As expected...

If we yet again, however, rewrite the example to use `.asBroadcastStream()`:
```dart
void main() async {
  try {
    await for (var item in _stream().asBroadcastStream()) {
      print(item);
    }
  } catch (e) {
    print(e);
  }
}

Stream<int> _stream() async* {
  for (var i = 0; i < 10; i++) {
    yield i;
  }

  throw Exception('Debugger always treats it as uncaught!');
}
```
There is a pause again on the throw.

Personally, I've encountered this issue when using some firebase packages, and
thinking I did some error handling wrong, only to figure out after some time,
that the errors were in fact handled, but the debugger reported them as not.

Dart version:
`Dart SDK version: 3.2.6 (stable) (Wed Jan 24 13:41:58 2024 +0000) on "macos_arm64"`

**Comment by devoncarew** [comment]
This may be working as expected, but I'll let @bkonyi confirm.

**Comment by aam** [comment]
cc @mraleph (given https://dart.googlesource.com/sdk/+/a52f2b96179ebdf29c38cab47e73dd1c6ec6bdff)

**Comment by aam** [comment]
perhaps https://github.com/dart-lang/sdk/blob/12841a6e295666ce7c2de5381dfed85571a2eabc/runtime/vm/stack_trace.cc#L414 should have code similar to https://github.com/dart-lang/sdk/blob/12841a6e295666ce7c2de5381dfed85571a2eabc/runtime/vm/stack_trace.cc#L410

**Comment by mraleph** [comment]
I have been sitting on a CL which should help here, but I have been delaying landing it because I have been slowly thinking through _what we should even do with this?_ question.

**Comment by aam** [comment]
> _what we should even do with this?_ question.

It might be that in this issue the problem is simpler and clearer: we don't recognize that particular stream listener has an exception handler.

**Comment by a-siva** [comment]
> > _what we should even do with this?_ question.
> 
> It might be that in this issue the problem is simpler and clearer: we don't recognize that particular stream listener has an exception handler.

Agree we should probably get the immediate issue fixed while @mraleph works on the CL listed above
