### ISSUE TITLE
Quick fix "Use imported library ... with prefix ..." should update `show` combinator

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#54786]
Reproduced at 3636c8a08bc1a0dfbec39305df05632247f83472 using VSCode.

Start with the following code:
```dart
import 'dart:math' as math show log; // (1)

main() {
  print(sqrt2); // (2)
}
```
This code has a compile-time error at (2) (`undefined_identifier`).

Trigger quick fixes at that point, and select the fix "Use imported library 'dart:math' with prefix 'math'".

This causes line (2) to change to:
```dart
  print(math.sqrt2); // (2)
```

Which, unfortunately, still has a compile-time error, since the import at (1) doesn't show `sqrt2`.

It would be nice if the quick fix also updated the import's `show` combinator.

**Comment by FMorschel** [comment]
Related https://github.com/Dart-Code/Dart-Code/issues/5238

**Comment by FMorschel** [comment]
https://dart-review.googlesource.com/c/sdk/+/392400
