### ISSUE TITLE
String clickedValue = (index < 9) ? (index + 1).toString(): (index == 9)  ? '0' : (index == 10)? '.' : String.fromCharCode(0xe0c5); 

### ISSUE THREAD

**Issue by neha-ann** [dart-lang/sdk#54797]
This code is not working for showing backspace
String clickedValue = (index < 9) ? (index + 1).toString(): (index == 9) ? '0' : (index == 10)? '.' : String.fromCharCode(0xe0c5);

**Comment by parlough** [comment]
Hi @neha-ann! Could you explain what you are trying to do? It's not clear from your code snippet what's not working or what you mean by "showing backspace". Thanks!

**Comment by sgrekhov** [comment]
There's nothing wrong in this code and it works.

**Comment by parlough** [comment]
I'm going to close this as the code posted works like it should.

The question is what you were trying to do with the code. Please feel free to respond with more information and we might be able to help. Thank you!
