### ISSUE TITLE
[vm] `--force_load_elf_from_memory` causes `Loading failed: Expected little-endian ELF object.` on arm64 mac

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54807]
```
stderr:
Loading failed: Expected little-endian ELF object.
VM initialization failed: Invalid vm isolate snapshot seen

--- Re-run this test:
python3 tools/test.py -m debug -c dartk,dartkp ffi/ffi_induce_a_crash_test/1
```

On arm64.

@a-siva Could this be a result of your change?

Side note: This test was failing already in a different way before it started failing this new way.

* https://github.com/dart-lang/sdk/issues/39487

**Comment by a-siva** [comment]
It could be, let me take a look.

**Comment by a-siva** [comment]
This doesn't appear to reproduce on top of tree, closing issue, please reopen if it shows up again.
