### ISSUE TITLE
2 packages failing dart2wasm tests

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#54800]
Reproduction: clone, `dart pub get`, `dart test -p chrome --compiler dart2wasm`

- [x] pkg:crypto - almost all tests fail due to time outs
  - [x] Waiting for dev SDK to roll to land PR - https://github.com/dart-lang/crypto/pull/162
- [ ] pkg:async - one tests fail
  - [ ] See https://github.com/dart-lang/sdk/issues/55025

```
test/subscription_stream_test.dart: cancelOnError source: no: - subscriptionStream: no [E]
  Expected: [1, 2, 'To err is divine!', 4]
    Actual: [1, 2, 'To err is divine!']
     Which: at location [3] is [1, 2, 'To err is divine!'] which shorter than expected
```

**Comment by mkustermann** [comment]
@kevmoo Could you provide instructions on how to run those tests?

**Comment by kevmoo** [comment]
done!

**Comment by mkustermann** [comment]
Also landed [cl/350322](https://dart-review.googlesource.com/c/sdk/+/350322) for perf fix.

**Comment by kevmoo** [comment]
`pkg:crypto` tests all pass now! 🥳

**Comment by kevmoo** [comment]
@mkustermann – still getting ONE failure (due to timeouts) on crypto: https://github.com/dart-lang/crypto/actions/runs/7801915494/job/21380589146#step:7:674

**Comment by mkustermann** [comment]
@kevmoo I can have a look. For me all `package:crypto` tests passed locally, may be flaky or a perf issue. For `package:async` there is now one failure remaining, it's a `async*` semantics issue that's somewhat very rare, I'll have to see how much work it is to fix and whether it makes sense to prioritize it now or not.

**Comment by mkustermann** [comment]
> @mkustermann – still getting ONE failure (due to timeouts) on crypto: https://github.com/dart-lang/crypto/actions/runs/7801915494/job/21380589146#step:7:674

The error message from this link seems to be
```
[Chrome, Dart2Wasm] loading test/hmac_sha2_test.dart (failed)
  Failed to load "test/hmac_sha2_test.dart":
  Timed out waiting for browser to load test suite.
```
It says it timed out waiting for the test suite to load, not even to run it. Could this be some flaky infra issue?


For me all tests pass just fine (also when running the failing test from your link individually) using `origin/main` of Dart SDK
```
<sdk>/third_party/pkg/crypto % xvfb-run -a dart test -p chrome --compiler dart2wasm                           
Building package executable... 
Built test:test.
01:02 +822: All tests passed!                                                                  

<sdk>/third_party/pkg/crypto % xvfb-run -a dart test -p chrome --compiler dart2wasm test/hmac_sha2_test.dart  
Building package executable... (4.7s)
Built test:test.
00:02 +7: All tests passed!                  
```

**Comment by kevmoo** [comment]
using `-j 1` also helps. (which is similar to running just one test directly) 

It seems that the `large fire produces correct hash` test is randomly slow with wasm.

**Comment by kevmoo** [comment]
Crypto is working and committed!

**Comment by osa1** [comment]
With the current SDK main branch async tests also pass:

```
$ dart test -p chrome --compiler dart2wasm
Building package executable... (3.9s)
Built test:test.
00:06 +290: [Chrome, Dart2Wasm] test/stream_queue_test.dart: startTransaction operation produces a transaction that when rejected can reject a transaction where one copy is fully consumed in a transaction and a second copy is made
  Skip: https://github.com/dart-lang/async/issues/229
00:14 +606 ~1: All tests passed!
```
