### ISSUE TITLE
Streams returned by StreamController.stream are not treated as equal when used as keys for Expando

### ISSUE THREAD

**Issue by kaboc** [dart-lang/sdk#54818]
https://github.com/dart-lang/sdk/issues/11904#issuecomment-108381453

> The controller doesn't return the same Stream object every time, but they are equal.

This seems true, so I thought two Streams returned by the `stream` getter on the same `StreamController` could be used as the same key to get a value from `Expando`. However, the result was different as follows.

```dart
import 'dart:async';

final Expando<Stream<Object?>> _streams = Expando();

void main() {
  var controller = StreamController<Object?>();
  final stream1 = controller.stream;
  final stream2 = controller.stream;
  _streams[stream1] = stream1.asBroadcastStream();
  
  print(stream1 == stream2); // true
  print(_streams[stream1]);  // Instance of '_AsBroadcastStream<Object?>'
  print(_streams[stream2]);  // null
}
```

Map behaves differently. It is what I expected for `Expando` too.

```dart
import 'dart:async';

final Map<Stream<Object?>, Stream<Object?>> _streams = {};

void main() {
  var controller = StreamController<Object?>();
  final stream1 = controller.stream;
  final stream2 = controller.stream;
  _streams[stream1] = stream1.asBroadcastStream();
  
  print(stream1 == stream2); // true
  print(_streams[stream1]);  // Instance of '_AsBroadcastStream<Object?>'
  print(_streams[stream2]);  // Instance of '_AsBroadcastStream<Object?>'
}
```

**Comment by lrhn** [comment]
That is the expected behavior.
The stream objects of a controller are equal, but not identical, and `Expando` relies on identity.

**Comment by kaboc** [comment]
> `Expando` relies on identity.

Map does not seem to rely on identity. Is the reason for the difference because `Expando` checks the identity to see if the object used as the key is still accessible, while Map does not need it? Is the check not possible by equality instead of identity?

The current behaviour does not allow packages to use `Expando` with the Stream passed in to a function. Below is an example, although it is contrived for simplicity. It is a bad experience for users that they are forced to cache the Stream returned by `controller.stream` so that the same instance is used for multiple calls. 

```dart
// Package
final Expando<Stream<MyEvent>> _subsriptions = Expando();

StreamSubscription<MyEvent> watch(Stream<MyEvent> stream) {
  // The intention of this function is to avoid adding multiple listeners.
  // However, _subscriptions[stream] is null if the stream is different,
  // and thus a new listener is added on every call.
  return _subscriptions[stream] ??= stream.listen(...);
}
```

```dart
// Code using the package
watch(controller.stream); // Wrong
watch(cachedStream);      // Good
```

The document of `Expando` has several sentences with the word "identical" or "identity", but it is not clear that the key must be identical to obtain the same value. How about stating it first instead of suddenly explaining "Since you can always create a new number that is identical to an existing number..."?

**Comment by mraleph** [comment]
I think [documentation of `Expando.operator []`](https://api.dart.dev/dev/3.4.0-94.0.dev/dart-core/Expando/operator_get.html) is pretty unambiguous:

>  Gets the value of this [Expando](https://api.dart.dev/dev/3.4.0-94.0.dev/dart-core/Expando-class.html)'s property on the given object.
>
> If the object hasn't been expanded, the result is the `null` value.

It is quite explicitly saying _**on the given object**_. 

> Is the check not possible by equality instead of identity?

`Expando` is a holding its keys weakly - if the `key` is otherwise unreachable it will be purged from the `Expando`. This means `Expando` based on `operator==` is not that useful. Consider:

```dart
class O {
  final int v; 
  O(this.v);
  bool operator == (Object other) => other is O && other.v == this.v;
  int get hashCode => v.hashCode;
}

final e = Expando();
e[O(10)] = true;
// Can print `true`, can print `null`. Because original key is already eligible for collection. 
print(e[O(10)]); 
```

**Comment by kaboc** [comment]
> It is quite explicitly saying on the given object.

I wasn't aware of the documentation. Thank you. I think it is clear and sufficient, as long as the reader notices the page, unlike me. However, because it is one of the basics we should know when using `Expando`, it would be better if it was stated in the document of the `Expando` class itself as well. (But I'm guessing documentation of Dart APIs has a rule or something that the same explanation shouldn't be repeated in various places.)

> `Expando` is a holding its keys weakly - if the `key` is otherwise unreachable it will be purged from the `Expando`. This means `Expando` based on `operator==` is not that useful.

Thank you for the clarification.

As an another related issue, I think it is misleading that `StreamController.stream` creates a new instance. The fact that it is a getter makes users think it returns an existing Stream, and they may not notice it is behaving differently until they look into the implementation.

But anyway, thank you so much for your time, @lrhn and @mraleph.
