### ISSUE TITLE
DAS diagnostics page is displaying *all* options files for each context

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#54816]
For example:

![image](https://github.com/dart-lang/sdk/assets/67586/d16b3aa7-15f8-4be1-bd8a-8640db1f758c)

Better if it only showed the one(s) associated w/ the contexRoot.

**Comment by pq** [comment]
w/ https://dart-review.googlesource.com/c/sdk/+/350080:

<img width="1155" alt="image" src="https://github.com/dart-lang/sdk/assets/67586/b26ddad9-216c-4570-a7cd-c34c5969fa53">

**Comment by bwilkerson** [comment]
I'm not convinced that that's better. Why do you think it's a problem to show all of the analysis options files that are controlling the analysis of files within the context? It seems to me like a misrepresentation to imply that there's a single set of options for the whole context when there are multiple sets of options.

**Comment by pq** [comment]
> Why do you think it's a problem to show all of the analysis options files that are controlling the analysis of files within the context?

Sorry to be unclear. The issue is we're showing ALL the options files for ALL the contexts in **each context**.

In the example above, you can see options for the linter, meta, kernel, etc. all associated w/ the analyzer context.

**Comment by bwilkerson** [comment]
Yes, sorry I missed that detail. We definitely don't want to be showing options files associated with other contexts.
