### ISSUE TITLE
[vm/ffi] Allow omitting `@Native` type if it can be inferred from the Dart signature

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54810]
On struct fields, we don't require annotating the native types if they are identical to the Dart type. This is true for `Pointer`, and subtypes  of `Struct` and `Union`. In the context of function types `Void` is also non-ambigious.

As @mkustermann suggested in https://github.com/dart-lang/sdk/issues/54739#issuecomment-1914182960, we should consider making the type argument for `@Native` external functions omittable if it is pinned down by the Dart type:

```dart
@Native(isLeaf: true)
external void myFunc(Pointer<Int8>);
```

The only valid signature for this would be:

```dart
@Native<Void Function(Pointer<Int8>)>(isLeaf: true)
external void myFunc(Pointer<Int8>);
```

Which does not add any extra info.

And in contrast to the `DynamicLibrary` API, we also won't have a `Pointer<NativeFunction<Void Function(Pointer<Int8>)>>` type in our program that we would type check against.

**Comment by halildurmus** [comment]
I created a CL that implements this https://dart-review.googlesource.com/c/sdk/+/400840
