### ISSUE TITLE
Add saveData to NetworkInformation

### ISSUE THREAD

**Issue by n-bernat** [dart-lang/sdk#54840]
[Save-Data](https://web.dev/articles/optimizing-content-efficiency-save-data) setting allows developers to check whether a user has Data Saver/Low Data Mode enabled. It's useful in areas with expensive and/or slow internet connection.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/saveData) it's currently supported by all Chromium-based web browsers.

By looking at https://github.com/dart-lang/sdk/commit/8ebed3d806260900a6f7bfc20f6407967c4e7ce9 it seems that there isn't a lot of work to do in order to update bindings, so maybe I can give it a try and make a PR if it's something that we want?

**Comment by devoncarew** [comment]
Heads up that our planned path forward wrt web interop is `package:web` - bindings generated from the IDL and using our newer (zero-cost) interop. We'll support `dart:html` but are unlikely to invest more in them. package:web has the advantage that it will also support compiling to WASM.

Perhaps see if package:web / https://github.com/dart-lang/web works for your use case?

**Comment by n-bernat** [comment]
Yes, it's perfect. As `dart:html` isn't getting new updates I will close this issue. Thanks a lot!
