### ISSUE TITLE
[macros] suppress lints in augmentations

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#54875]
We're currently producing lints in generated augmentation libraries. In the long run (and as discussed), we will likely want to make seeing them configurable but in the short-run we should consider just suppressing them.

<img width="1339" alt="image" src="https://github.com/dart-lang/sdk/assets/67586/4dd61614-1f52-461a-a513-9be16176d279">

(Sorry BTW if this is a duplicate issue -- I couldn't find one open already.)

Happy to take a look at this if no one is already.

/fyi @bwilkerson @scheglov @keertip

**Comment by bwilkerson** [comment]
I agree, until we've decided on a longer-term plan we should either stop running lints over generated files or we should filter them all out (emulating what `ignore_for_file: type=lint` would do).

**Comment by scheglov** [comment]
We probably mean here not just any augmentations, but specifically macro generated augmentations.

**Comment by pq** [comment]
See also: https://github.com/dart-lang/language/issues/3346
