### ISSUE TITLE
`dart analyze --format=json` does not print a machine readable output

### ISSUE THREAD

**Issue by kzrnm** [dart-lang/sdk#54877]
`dart analyze --format=json` has extra output before the JSON, which must be removed before it can be read by the machine. 

I think it should not output extra, as `dart analyze --format=machine` does.

```
$ dart analyze --format=json
Analyzing appName...
{"version":1,"diagnostics":[{"code":"avoid_print","severity":"INFO","type":"LINT","location":{"file":"/home/workspace/appName/lib/main.dart","range":{"start":{"offset":1004,"line":28,"column":3},"end":{"offset":1009,"line":28,"column":8}}},"problemMessage":"Don't invoke 'print' in production code.","correctionMessage":"Try using a logging framework.","documentation":"https://dart.dev/lints/avoid_print"}]}
$ dart analyze --format=machine
INFO|LINT|AVOID_PRINT|home/workspace/appName/lib/main.dart|28|3|5|Don't invoke 'print' in production code.
```

https://github.com/dart-lang/sdk/blob/3ab1eaa03fbda3a06a9c4cf2dd4fbc132c3aff87/pkg/dartdev/lib/src/commands/analyze.dart#L109-L110

----

If there are no errors, the output is not a JSON . This has already been mentioned in #49905.

```
$ dart analyze --format=json
Analyzing appName...
No issues found!
$ dart analyze --format=machine
$
```

**Comment by anamika1804** [comment]
Hey @kzrnm I think a sed command would work for it,
`dart analyze --format=json | sed -n '/^{/,/}$/p'
`
where the JSON part will be extracted from the first { and last }. basically removes the additional text before or after the JSON output.

**Comment by kzrnm** [comment]
@anamika1804 I am just reporting a bug where the help says "A machine readable output in a JSON format." but it is outputting something like json.
https://github.com/dart-lang/sdk/blob/3ab1eaa03fbda3a06a9c4cf2dd4fbc132c3aff87/pkg/dartdev/lib/src/commands/analyze.dart#L63

**Comment by lrhn** [comment]
Agree. If the output is intended as machine readable, then the header should probably be suppressed.

**Comment by kzrnm** [comment]
Fixed
