### ISSUE TITLE
Windows using Dart.exe as DLL malloc Crash

### ISSUE THREAD

**Issue by DerKleinePunk** [dart-lang/sdk#54880]
I build an Test repro to Test the DLL (Lib) Functions.

https://github.com/DerKleinePunk/HostDartVM

When i debug the output malloc Crash. I have also Test with an Debug Build from this Repro

![image](https://github.com/dart-lang/sdk/assets/20199046/c3b7737f-7aa6-40d3-8d55-6fb895c6667f)

Hast some an Hint for me to fix this ?

**Comment by mraleph** [comment]
I don't think you can just load `dart.exe` as a shared library in this manner and expect it to work. Especially not with all the wonkiness Windows has around how CRT `malloc` and local heaps work.

I think your only chance to make this work is to build a proper Dart VM LIB/DLL from sources for embedding purposes. You can see how to do it by looking at @fuzzybinary's example here https://github.com/fuzzybinary/dart_shared_libray

**Comment by DerKleinePunk** [comment]
@mraleph 
And why dart generate an lib when you not can do this ?
dart_shared_libray i have try but it is not building...

**Comment by mraleph** [comment]
`lib` is there as a left over from native extensions: you could create DLLs that use Dart VM C API exposed by `dart.exe`. `dart.exe` will be the one loading these DLLs. We should probably remove the `.lib` given that we no longer recommend writing native extensions like this. Any opinion @mkustermann?

**Comment by mkustermann** [comment]
Yes, we should definitly not have a `bin/dart.lib` file in our windows Dart SDK! We may also want to not expose any dynamic symbols from `dart.exe` - except for the API we also offer via `dart_dl_api.h` (i.e. not provide `Dart_Initialize()`).

**Comment by fuzzybinary** [comment]
@DerKleinePunk If you're having trouble with dart_shared_library open up an issue on that repo and I'll see if I can help you get it building.

**Comment by DerKleinePunk** [comment]
> Yes, we should definitly not have a `bin/dart.lib` file in our windows Dart SDK! We may also want to not expose any dynamic symbols from `dart.exe` - except for the API we also offer via `dart_dl_api.h` (i.e. not provide `Dart_Initialize()`).

![image](https://github.com/dart-lang/sdk/assets/20199046/66dda760-58a4-4b1a-903d-c787d6d6cc3f)

**Comment by mkustermann** [comment]
Have landed d3d83e639cde6ad8165cd3ec40e5ef626f25a245 to remove the `dart.lib` in the Dart SDK.
