### ISSUE TITLE
Analysis Never Completes When `custom_lint Plugin` Added to `analysis_options.yaml`

### ISSUE THREAD

**Issue by ykaito21** [dart-lang/sdk#54883]
### Environment
- **Visual Studio Code Version**: 1.86.1
- **Dart Plugin Version**: v3.83.20240207
- **Flutter Plugin Version**: v3.83.20240201 
- **Flutter SDK Version**: Channel stable, 3.16.9

### Description
After adding the `custom_lint` plugin to my `analysis_options.yaml` and including the plugin in my `pubspec.yaml`, the Dart analyzer in Visual Studio Code never completes. This issue occurs even without making any code changes after initializing a new Flutter project with `flutter create`. Removing the `custom_lint` plugin resolves the issue, suggesting that the problem is specifically related to the interaction between the Dart analyzer and the `custom_lint` plugin in Visual Studio Code.

### Steps to Reproduce
1. Create a new Flutter project with `flutter create`.
2. Add `custom_lint: ^[version]` to the `dev_dependencies` section of `pubspec.yaml`.
3. Add the following to `analysis_options.yaml`:
   ```yaml
   analyzer:
     plugins:
       - custom_lint
   ```
4. Open the project in Visual Studio Code.
5. Observe that the Dart analysis never completes.

### Expected Behavior
The Dart analyzer should complete its analysis of the project, including when the `custom_lint` plugin is added.

### Actual Behavior
The Dart analyzer gets stuck and never completes its analysis when the `custom_lint` plugin is included.

### Additional Information
- The issue persists even after restarting Visual Studio Code and reloading the project window.
- Running `flutter analyze` from the command line completes without issues, suggesting that the problem is specific to Visual Studio Code.
- No relevant output or error messages are visible in the Dart and Flutter extension logs in the Output panel of VS Code.

### Doctor Result
```
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.4 22F66 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.86.1)
[✓] Network resources
```

This issue is also tracked in https://github.com/invertase/dart_custom_lint/issues/226#issue-2129810227

I suspect there may be a compatibility issue or a bug related to the `custom_lint` plugin's interaction with the Dart analyzer in Visual Studio Code. Any insights or assistance in resolving this problem would be greatly appreciated.

**Comment by rrousselGit** [comment]
Oops, wrong repo.

I doubt that this is an SDK issue. Let's switch discussion to the custom_lint repo.

**Comment by bwilkerson** [comment]
Let us know if it turns out to be an issue in the SDK. I'm going to go ahead and close this issue for now.
