### ISSUE TITLE
[pkg/analysis_server] Sort imports fix - issue with multi-line import 

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#54893]
Applying `sort imports` fix when there's an import statement that spans across two lines does not work properly:

https://github.com/dart-lang/sdk/assets/46427323/ce45d8a8-b0dc-4cd2-aaf2-56cf971b467e

## Code Sample:

The code sample is for reproduction purposes. In reality, this is an issue with long paths where the formatter would move the show combinator to the next line if the import statement exceeds the specified formatting length.  

```dart
import 'dart:math';
import 'dart:collection' 
  show HashMap;
```

p.s. please advice if this is Dart Code issue and I will transfer the issue there. 

> Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_x64"

**Comment by bwilkerson** [comment]
Thanks for the report. This is the correct repo for reporting the issue.

**Comment by osaxma** [comment]
Hi @keertip 

The fix in question is `Sort Imports` which would appear under "Quick Fix" (by clicking the light bulb or "command + dot". 

I was not aware of `Organize Imports` but that works fine (tho it seems it'd delete unused imports as well).

**Comment by keertip** [comment]
@osaxma, I do not see an option `Sort Imports` in the quick fix menu, either from the light bulb or command+dot. Is there anything else in your setup that's unique?

**Comment by osaxma** [comment]
Oops! I've always thought the "Sort Imports" is part of the Dart Code Extension but apparently it comes from from [Dart Data Class Generator](https://marketplace.visualstudio.com/items?itemName=dotup.dart-data-class-generator) extension.

Sorry about that!
