### ISSUE TITLE
VM Service removes breakpoints during a hot-restart when the app is paused

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#54898]
Steps to repro:

- Set a breakpoint (or several) in Dart DevTools
- Hit one of the breakpoints
- While paused, perform a hot-restart
- For each breakpoint that was set, DevTools receives a `kBreakpointRemoved` event: https://github.com/flutter/devtools/blob/2859d24b610d4dcf9d8e3248a9ae4eff862186ad/packages/devtools_app/lib/src/screens/debugger/breakpoint_manager.dart#L286

Expected result: There should be no `kBreakpointRemoved` events being sent.

I have verified that Dart DevTools is not sending a request to remove these breakpoints itself. 

Note that when Dart DevTools triggers a hot restart while the app is **not** paused,  then there are not `kBreakpointRemoved` events sent.

FYI @bkonyi

**Comment by elliette** [comment]
Thinking about this more, I'm guessing it's because the vm_service first resumes the isolate before starting the hot-restart. Since we don't want to hit any breakpoints while resuming, it makes sense that the vm_service would first remove them all.

**Comment by bkonyi** [comment]
So it looks like this isn't a VM issue, but behavior in [Flutter tools](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L653). So it looks like this is expected.
