### ISSUE TITLE
Autocompletion during destructuring should not list variables that are already destructured.

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#54896]
Consider the following named record:

```dart
const tuple = (value: 42, another: 21);
```

When using destructuring to create new variables, autocomplete currently keeps suggesting variables that were already assigned.

See:

<img width="405" alt="Screenshot 2024-02-12 at 22 39 20" src="https://github.com/dart-lang/sdk/assets/20165741/830ad902-f6d5-41c2-85b7-916fc016513e">

<img width="405" alt="Screenshot 2024-02-12 at 22 39 51" src="https://github.com/dart-lang/sdk/assets/20165741/8cb2f148-30f8-4ea5-99ed-de08b445e984">

As you can see, even though we already used `:another`, the autocompletion keeps suggesting `:another`. 
This makes no sense, as `final (:another, :another, :value) = tuple` is not valid syntax.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/355622
