### ISSUE TITLE
Platform.localname returns "de_DE" instead of "de_CH" for Swiss German under Windows (iOS and MacOS work correctly)

### ISSUE THREAD

**Issue by 2S-Software** [dart-lang/sdk#54904]
**Bug Description**
Platform.localname and findSystemLocale() return the wrong code "de_DE" instead of "de_CH" for Swiss German under Windows. The effect is that the wrong currency "EUR" instead of "CHF" is used under Windows.
On macOS and iOS, however, the code is returned correctly!

```
import 'dart:io';

void main() {
  print(Platform.localeName);  // returns "de_DE" instead of "de_CH"
}
```

Regional settings with "Swiss German" under Windows 11:
![image](https://github.com/dart-lang/i18n/assets/97222956/e4b87092-312c-4f47-92d6-d287ffcca2d2)

**System info**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22621.3007], locale de-CH)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.86.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

---

Dart SDK 3.2.6
Flutter SDK 3.16.9
hello_flutter 1.0.0+1

dependencies:
- cupertino_icons 1.0.6
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]   

transitive dependencies:
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- path 1.8.3
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- web 0.3.0

**Comment by mosuem** [comment]
Moved to this repo, as it is not specific to `package:intl`.

**Comment by mraleph** [comment]
How do you run this code to get the wrong output? Are you doing `dart.exe test.dart`? I can see that `flutter doctor` prints locale name correctly, which indicates to me that you are not running this test just by doing `dart.exe test.dart`. 

Dart CLI just calls `GetUserDefaultLocaleName` and returns that - so I would not expect any problems there. 

If you are running this code through Flutter engine somehow - then it is behavior specific to the engine. It overrides `Platform.localeName` with its own implementation which is much more complicated. So if you are not running this test through `dart.exe` then you should file a bug against Flutter instead.

**Comment by 2S-Software** [comment]
You are right. I run the code in Flutter and not in Dart. In this case, it is a flutter issue if there is a separate implementation in Flutter for this. I will create a new, separate ticket for this.
Thank you for your prompt analysis!
