### ISSUE TITLE
Analyzer should report an error for macro applications too close to the macro impl

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#54915]
Per the spec, macros are not allowed to be used in the same library they are defined, or in the same library cycle.

So, the analyzer should report an error.

Tests:

language/macros/error/declare_and_use_same_library_test
language/macros/error/declare_and_use_same_library_cycle_test

[added here](https://dart-review.googlesource.com/c/sdk/+/352522)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/354382
