### ISSUE TITLE
Add obfuscation string to DTD uri

### ISSUE THREAD

**Issue by CoderDake** [dart-lang/sdk#54932]
@DanTup pointed out that we should add an obfuscation string to DTD's uri to help obsure open access through localhost.

**Comment by DanTup** [comment]
Looks like this was done in https://github.com/dart-lang/sdk/commit/68c74e2a97129ef3b1d0ba269aecfe615d224ba7.

However, it looks like there's no flag to opt out of this, which makes some local development scenarios a little tricker (I wanted to use a VS Code task to launch a DTD in the background that could be used by the mock editor). @bkonyi @CoderDake any objections to adding a flag (similar to what we have for VM Service tokens)?

**Comment by bkonyi** [comment]
I have no objections. Maybe use `--disable-service-auth-codes` to be consistent with our other services?

**Comment by DanTup** [comment]
I've opened https://dart-review.googlesource.com/c/sdk/+/373340.

Closing this, since this issue was already done.
