### ISSUE TITLE
pkg/vm/test/transformations/ffi_test goes from flaky to Timeout failures

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#54950]
The tests
```
pkg/vm/test/transformations/ffi_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux-x64
```

**Comment by a-siva** [comment]
//cc @dcharkes

**Comment by a-siva** [comment]
Link to failure log https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-linux-debug/19552/overview

**Comment by dcharkes** [comment]
This test runs multiple tests in sequence, and every time we add new features to the FFI we add tests.

We should consider setting up the tests differently so that not every test case is run in sequence. (Possibly also for the other transform tests.)

I'll just mark it slow for now.

**Comment by a-siva** [comment]
Closing for now.
