### ISSUE TITLE
pkg/test_runner/test/static_error_test.dart failures

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#54964]
Test failures which could potentially be related to 
https://dart-review.googlesource.com/c/sdk/+/345541

The tests
```
pkg/test_runner/test/static_error_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win-arm64
unittest-asserts-release-win-x64
```

**Comment by a-siva** [comment]
//cc @davidmorgan

**Comment by davidmorgan** [comment]
On it...

**Comment by davidmorgan** [comment]
https://dart-review.googlesource.com/c/sdk/+/353400

**Comment by davidmorgan** [comment]
Merged / fixed. Thanks!
