### ISSUE TITLE
Support for omitting bounds checks

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#54962]
Dart2js's `-O4` mode implies `--trust-primitives`. `--trust-primitives` in return will turn off checking of bounds on certain operations.

To make performance comparisons between dart2wasm and dart2js comparable we may want to implement this. Implementing this will then make `_ListBase.[]` and similar operations smaller in `-O4` mode. That in return makes it easier to inline for us, binaryen and V8 without regressing size.

/cc @osa1

**Comment by osa1** [comment]
Related: #54395.

With inlining hints (https://github.com/WebAssembly/compilation-hints/issues/3) I think we could achieve good performance by making sure error throwing parts of the accessors are in separate functions that are never inlined (as described in the linked issue), but it will probably take a while to design and implement inlining hints for Wasm.
