### ISSUE TITLE
NoSuchMethodError: The method 'any' was called on null, cannot explain

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#54967]
See https://dart-review.googlesource.com/c/sdk/+/353229

I run it as `dart /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/analysis/test_all.dart`

```console
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (aa-augment-finalField-constConstructor)$ dart --version
Dart SDK version: 3.3.0-edge.6b5b3cc98a23afb58ffdaebf37941aed257ce885 (be) (Mon Nov 13 09:15:13 2023 +0000) on "macos_arm64"
```

See `pkg/analyzer/lib/src/summary2/library_builder.dart`, look for `// TODO(scheglov): uncomment`.

The crash does not make sense to me. `get constructors` never returns `null`.

```
NoSuchMethodError: The method 'any' was called on null.
Receiver: null
Tried calling: any(Closure: (ConstructorElement) => bool)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      LibraryBuilder.replaceConstFieldsIfNoConstConstructor (package:analyzer/src/summary2/library_builder.dart:606:47)
#2      Linker._replaceConstFieldsIfNoConstConstructor (package:analyzer/src/summary2/link.dart:377:15)
#3      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:227:5)
<asynchronous suspension>
#4      Linker.link (package:analyzer/src/summary2/link.dart:102:5)
```

**Comment by aam** [comment]
@scheglov can you clarify whether you got this `NoSuchMethodError` on your repro cl without any further changes to dart sdk?

If I pick that CL up, the test passes for me
```
$ git fetch https://dart.googlesource.com/sdk refs/changes/29/353229/1 && git checkout -b change-353229 FETCH_HEAD 
...
```
rebuild dart sdk and run the test, it passes for me
```
$ out/ReleaseX64/dart --version
Dart SDK version: 3.4.0-edge.b6036611deab79dae67e76cd6a5032f5994e26e8 (main) (Tue Feb 20 13:55:35 2024 -0800) on "linux_x64"
$ out/ReleaseX64/dart pkg/analysis_server/test/analysis/test_all.dart  
...
00:21 +123: All tests passed!
$ 
```

**Comment by mraleph** [comment]
@aam I think @scheglov (based on the version string provided) was testing with prebuilt Dart binary, e.g. it reproduces for me with Dart from Flutter 3.19.1:

```
$ dart --version
Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"
$ dart pkg/analysis_server/test/analysis/test_all.dart
...
[e: NoSuchMethodError: The method 'any' was called on null.
```

The test also passes with `--no-use-field-guards`, so I strongly suspect that this might simply be another instance of https://github.com/flutter/flutter/issues/142532 which @alexmarkov has fixed by 97164b3a017122a111151417b1184b2f31fb89f6

**Comment by alexmarkov** [comment]
Cherry-picked 97164b3a017122a111151417b1184b2f31fb89f6 on top of 6b5b3cc98a23afb58ffdaebf37941aed257ce885 and confirmed that it indeed fixes this bug.

**Comment by scheglov** [comment]
Thank you! :-)
