### ISSUE TITLE
`UserTag` class not implemented on wasm platform

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#54991]
The external functions declared in `sdk/lib/developer.dart` (the `UserTag` class) have no implementation in dart2wasm. Both the vm and js_runtime platforms have patch files that implement these members, but no such file is included in the wasm platform. This causes a `NoSuchMethodError` error to be fired when compiling a flutter app in `--profile` mode, as some of flutter's framework code that is enabled in the `--profile` build attempts to call the `UserTag.defaultTag` API.

Steps to reproduce:
* Build a web app with `flutter build web --wasm --profile`
* Host the web app (with proper COOP/COEP HTTP headers to enable `crossOriginIsolated`) and open it in the browser

Results:
* `NoSuchMethodError` when invoking `UserTag.defaultTag`

**Comment by mkustermann** [comment]
What is the exact difference in `flutter build web --wasm` and `flutter build web --wasm --profile`?

For the VM the difference is that the profile build has `vm-service` to which DevTools can talk to (and e.g. cpu profile app, analyze memory, etc), whereas in release mode this is not possible.

If wasm doesn't support anything at runtime in `--profile` mode (such as `vm-service` in the VMs case), then maybe we can make `--profile` simply enable `--no-strip-wasm` and **always** pass `-Ddart.vm.product=true` to the compiler? (e.g. our Dart CI bots do not test both modes)

**Comment by eyebrowsoffire** [comment]
There is some framework specific code that does certain things in profile mode, and I'm not sure I know comprehensively all the call sites that deal with it. I don't think changing the meaning of the `--profile` flag for the wasm case is the correct answer to this issue. The APIs in `sdk/lib/developer.dart` exist and are visible to user code, so I think we need an implementation there, even if it's just a dummy no-op implementation.

I do agree with you that `--profile` should probably enable `--no-strip-wasm` but that's a bit orthogonal to this issue.

**Comment by mkustermann** [comment]
> The APIs in sdk/lib/developer.dart exist and are visible to user code, so I think we need an implementation there, even if it's just a dummy no-op implementation.

👍  Yes, we should certainly add a dummy implementation.

The question whether we have to conditionally pass `-Ddart.vm.product=true` or `-Ddart.vm.profile=true` is somewhat orthogonal. I guess users could write some code that only runs in debug/profile/release mode, so maybe we should be supporting that. But at least core libraries shouldn't depend on that because we have only one `dart2wasm_platform.dill` file (and not one per mode, as the VM has). If we don't have code depending on the modes in the SDK, then we also don't have to test different modes on CI. So I guess that answers the question :-)

**Comment by eyebrowsoffire** [comment]
Just a heads up, it turns out this issue is actually blocking me relanding https://github.com/flutter/flutter/issues/140429. The code path in the framework that uses this API is exercised when we add frame timings, and our benchmarks are run with `--profile`. So I won't be able to reland that until this is fixed.

**Comment by mkustermann** [comment]
Will try to make all of `dart:developer` that works in dart2js also work in dart2wasm.
