### ISSUE TITLE
[dart2wasm] WASM Module contains real system paths.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#54995]
Can I hide them?

![image](https://github.com/dart-lang/sdk/assets/53435297/b2c7f972-6ca6-4f66-b08c-1665dc7fe1f7)

#### General info
- Dart 3.4.0-160.0.dev (dev) (Tue Feb 20 20:02:57 2024 -0800) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 19042)
- locale is en-KZ

#### Project info
- sdk constraint: '^3.3.0'
- dependencies: meta, web
- dev_dependencies: build_runner, build_web_compilers, lints

**Comment by mkustermann** [comment]
These are static symbols that are useful in stack traces etc.
In flutter these are stripped by default in release builds (`flutter build web --wams`) but can be kept via `--no-strip-wasm`
In dart standalone those can be striped via `dart compile wasm --no-name-section`.

(You can see these hidden - and not yet stable flags - via passing `--verbose`, e.g. via `dart compile wasm --help --verbose`)

Hope that helps.
