### ISSUE TITLE
The analyzer reports a potentially null receiver error for an extension member, and this error seems spurious

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#55000]
Consider the following program:

```dart
typedef E<X> = X Function(X);

extension<X> on X {
  X m<Y extends E<X>>() => this;
}

Future<void> f<X extends Future<Never>?>(X x) async {
  (await x).m<E<Never?>>();
}

void main() async {
  f<Null>(null);
}
```

This program is rejected by the analyzer with the following messages:

```
  error • scratch.dart:8:13 • The method '{0}' can't be unconditionally invoked because the receiver can be 'null'. Try making the call conditional (using '?.') or adding a null check to the target ('!'). • unchecked_use_of_nullable_value
   info • scratch.dart:4:5 • The declaration 'm' isn't referenced. Try removing the declaration of 'm'. • unused_element
```

Both of these diagnostics are surprising. The static type of `await x` ought to be `Never?`, so it isn't surprising that the receiver can be null (it can't be anything else ;-), but the extension method `m` should be applicable also to a receiver whose type is nullable.

Also note that '{0}' seems to be an unprocessed element in a string template. Finally note that almost all the elements need to be there for this behavior to occur, the program is accepted without issues if `<E<Never?>>()` is removed, or just `()`.

The CFE accepts the program with no errors or warnings.

**Comment by bwilkerson** [comment]
@scheglov @srawlins (I suspect that there's more than one bug here.)
