### ISSUE TITLE
Platform.script is returning a bad (non existent) file

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#55004]
In Flutter, I'm trying to get the current script file and it is giving me an incorrect one. My `launch.json` is this and I'm executing on `Windows`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Website Manager (Windows)",
            "request": "launch",
            "type": "dart",
            "program": "lib/main_windows.dart"
        },
        {
            "name": "Website Manager (Android)",
            "request": "launch",
            "type": "dart",
            "program": "lib/main_android.dart"
        },
        {
            "name": "Website Manager (Web)",
            "request": "launch",
            "type": "dart",
            "program": "lib/main_web.dart"
        },
    ]
}
```
This is giving me a wrong file path and returning `false` on `existsSync`:
```dart
static void testDir() {
    final scriptFile = File(Platform.script.path);

    debug('Script path: ${scriptFile.path}');
    debug('Exists: ${scriptFile.existsSync()}');
  }
```
Output: 
```
flutter: [DEBUG] -- Script path: /C:/Users/bussl/workspace/FLUTTER/website-manager/main.dart
flutter: [DEBUG] -- Exists: false
```
It should be: `/C:/Users/bussl/workspace/FLUTTER/website-manager/lib/main_windows.dart` instead of `/C:/Users/bussl/workspace/FLUTTER/website-manager/main.dart`

Any idea on what's happening?

[weird-script-file.webm](https://github.com/dart-lang/sdk/assets/73592852/2223cd0c-35a0-45ba-9a24-94d5dc8ff48c)

**Comment by busslina** [comment]
I removed the ``.dart_tool` and `build` directories but I get the same result

**Comment by mraleph** [comment]
This issue should be filed against Flutter. VM just returns what embedder provides to it when configuring isolate.
