### ISSUE TITLE
JS interop pain

### ISSUE THREAD

**Issue by travishaagen** [dart-lang/sdk#55012]
Hey. I have a build of Chromium with a custom Sensor object, and I'm trying to bind to it. The Sensor is similar to this one found in `html_dart2js.dart`:

```
@Native("Accelerometer")
class Accelerometer extends Sensor {
  // To suppress missing implicit constructor warnings.
  factory Accelerometer._() {
    throw new UnsupportedError("Not supported");
  }

  factory Accelerometer([Map? sensorOptions]) {
    if (sensorOptions != null) {
      var sensorOptions_1 = convertDartToNative_Dictionary(sensorOptions);
      return Accelerometer._create_1(sensorOptions_1);
    }
    return Accelerometer._create_2();
  }
  static Accelerometer _create_1(sensorOptions) =>
      JS('Accelerometer', 'new Accelerometer(#)', sensorOptions);
  static Accelerometer _create_2() =>
      JS('Accelerometer', 'new Accelerometer()');

  num? get x native;

  num? get y native;

  num? get z native;
}
```

However, the above is using some internal APIs, and I can't seem to get past setting `sensorOptions` on my version.

```
@JS()
extension type CustomSensor._(JSObject _) implements JSObject {
  external CustomSensor(SensorOptions sensorOptions);

  external void start();

  external void stop();

  external num get myValue;

  external void addEventListener(String type, JSFunction? callback, [JSAny options]);
}

@JS()
@anonymous
extension type SensorOptions._(JSObject _) implements JSObject {
  external factory SensorOptions({num frequency});

  external num get frequency;
}
```

The errors complain about the constructor. `SensorOptions` is supposed to be like a JS dictionary object, so that's why I was trying `@anonymous`. Any ideas?

**Comment by navaronbracke** [comment]
This works fine on my end:

```dart
import 'dart:js_interop';

/// The JS `Accelerometer` as an extension typed JS binding.
///
/// The extension type defines the primary constructor as private.
@JS()
@staticInterop
extension type Accelerometer._(JSObject _) implements JSObject {
  external factory Accelerometer([SensorOptions? options]);

  external num? get x;

  external num? get y;

  external num? get z;
}

@JS()
@staticInterop
@anonymous
extension type SensorOptions._(JSObject _) implements JSObject {
  external factory SensorOptions({double frequency});
}
```

**Comment by srujzs** [comment]
FYI - You don't need the `@staticInterop` or `@anonymous` annotations anymore, they don't do anything for extension types and might just get in the way. Extension types are static by definition, so `@staticInterop` isn't necessary. Simply having a constructor with named arguments will make it an [object literal constructor](https://dart.dev/interop/js-interop/usage#interop-type-members), so `@anonymous` isn't needed anymore either. I should add an error to make that obvious.

I assume you're coming across the [bug mentioned in the above link](https://github.com/dart-lang/sdk/issues/54801) where you need to have an `@JS` annotated library until 3.4 for object literal constructors, so this should work:

```dart
@JS()
library;

import 'dart:js_interop';

extension type CustomSensor._(JSObject _) implements JSObject {
  external CustomSensor(SensorOptions sensorOptions);

  external void start();
  external void stop();
  external num get myValue;
  external void addEventListener(String type, JSFunction? callback, [JSAny options]);
}

extension type SensorOptions._(JSObject _) implements JSObject {
  external factory SensorOptions({num frequency});

  external num get frequency;
}
```

Let me know if you're hitting some other bug instead.

**Comment by srujzs** [comment]
Ah yeah, you'll need a `.toJS` call so that it can be converted to a JS function: https://dart.dev/interop/js-interop/js-types#conversions.

**Comment by travishaagen** [comment]
Compiler appeared happier with,

```
var readingInterop = js_util.allowInterop(readingCallback) as JSExportedDartFunction;
mySensor.addEventListener("reading", readingInterop);
```

What are my options for handling the `Event` that gets passed to the callback? The event I'm receiving has custom properties.

**Comment by srujzs** [comment]
> `var readingInterop = js_util.allowInterop(readingCallback) as JSExportedDartFunction;`

I'd avoid using `allowInterop` (or `js_util` in general) for this purpose since it won't be Wasm-compatible. Can you share what compilation issues you came across with using `Function.toJS`? I'm guessing the compiler gave you an error on one or more of the types of the Dart callback you tried to convert? If so, [this](https://dart.dev/interop/js-interop/js-types#requirements-on-external-declarations-and-function-tojs) might be relevant and all you may need to do is provide the right types.

> What are my options for handling the Event that gets passed to the callback? The event I'm receiving has custom properties.

If it's a custom `Event`, you can declare your own interop type like how we do in `package:web` e.g.

```dart
extension type CustomEvent(JSObject o) implements Event {
  // declare whatever custom properties here
}
```

`implements Event` allows you to reuse the `Event` members from `package:web` which I presume you'd want. Then, use `CustomEvent` as the type of the `Event` in the callback:

```dart
void readingInterop(CustomEvent event) {
  // do something with `event`
}
mySensor.addEventListener("reading", readingInterop.toJS);
```

**Comment by travishaagen** [comment]
Thanks both of you for the help!

I was passing in a `Function` callback, but by using a local, typed callback function it started working.

I used a `StreamController` to broadcast the events to subscribers.
