### ISSUE TITLE
Some completion items from the current library come from NotImportedContributor (and show import URIs)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#55013]
Splitting from https://github.com/dart-lang/sdk/issues/55010#issuecomment-1962374403

Given the following code inside the `test` folder:

```dart
String? wrapper(String? value) => value;

class SomeClass {
  final String? first;
  const SomeClass(this.first);
}

void fn() {
  wrappe()
  SomeClass(wrappe());
}
```

Completing after the first `wrappe` looks like (good):

![image](https://github.com/dart-lang/sdk/assets/1078012/3212d4f8-df46-43ee-a51f-d29a4c0d42f3)

However on the second one, there's an unexpected full file path:

![image](https://github.com/dart-lang/sdk/assets/1078012/14f9ec07-4a62-49ab-8424-d7ce15d58dc5)

I don't see any reason that these should be different, nor why we'd include a file path for a symbol already available (in the same file!).

**Comment by DanTup** [comment]
It seems like this entry is being suggested by `NotImportedContributor` which thinks it's not imported (technically, it's not imported.. because it's already in the current file). This results in building a completion that's marked as needing an import (and we're then incorrectly formatting that as an absolute path).

So there are two issues:

1. The full path instead of a relative path as would be imported if we triggered this import (although in this case it's a no-op because it's the current file)
2. This item is being suggested as a not-imported element even though it's in the current file

The first one is probably easy, the second one needs some more investigation.. it's not clear to me if the top-level function should already be in `_importedElements` (because it's not imported, but it is in the current scope).

![image](https://github.com/dart-lang/sdk/assets/1078012/97f21b80-9878-4d9f-a00b-2094cfa710d8)

**Comment by bwilkerson** [comment]
Treating the current library as being already imported is probably the easiest and cleanest way to handle this. All elements declared in the imported library will already be suggested if they're appropriate.

**Comment by scheglov** [comment]
Interesting, I can reproduce this.
Not through IDE, but only when I leave `NotImportedContributor` as the only contributor.
Probably because otherwise we de-duplicate suggestions, and the local ones added first.

**Comment by scheglov** [comment]
Hm... Fixing `NotImportedContributor` breaks tests.
The reason, I think, is that there are bugs in `DeclarationHelper` and `InScopeCompletionPass`.
For example, they don't suggest class names into const context.

https://dart-review.googlesource.com/c/sdk/+/356925


For example, I don't get `A01` suggestion, even though with it the code is valid.
Stupid, but valid.
```dart
class A01 {}

void f(Object? x) {
  switch (x) {
    case [A0^]:
      break;
  }
}
```

So, the bug in `NotImportedContributor` was masking bugs somewhere else :-)

@bwilkerson How do you prefer to proceed? Fix `InScopeCompletionPass` atomically with `NotImportedContributor` fixes? Or fix `NotImportedContributor` and mark failing tests as such?

**Comment by scheglov** [comment]
I definitely agree that breaking users is not good :-)
So, I will try fix `InScopeCompletionPass` to produce missing suggestions.

**Comment by DanTup** [comment]
(updated the title to be a bit more accurate since the full paths are gone)


>  and add uses of the new helper in `InScopeCompletionPass`

Do not-imported items belong in `InScopeCompletionPass`? (if so, I'm curious what would be outside of `InScopeCompletionPass`?)

I'm also curious if at the end there will be any difference (besides the libraries being suggested from) between imported/not-imported completions? (eg. is there any difference in the logic that's choosing what to suggest, or is it just the same code running over a different set of libraries?)

**Comment by bwilkerson** [comment]
> Do not-imported items belong in `InScopeCompletionPass`?

Good question. The original design was for those suggestions to be computed in a separate pass that could be skipped if there wasn't time to compute them. It also called for a separate pass for override suggestions. But when I started converting the contributors I started to wonder whether that actually made sense, or whether we wanted to compute all of the suggestions in one place and add the time-based guards there. Something like
```dart
void visitSomeNode(SomeNode node) {
  suggestKeywordsAndLocalDeclarations();
  if (thereIsTime) {
    suggestOverrides();
    if (thereIsTime) {
      suggestNotYetImported();
    }
  }
}
```

One of the biggest reasons I'm considering the second is that I don't particularly want to either (a) duplicate the 'where are we in the AST' logic or (b) set some kind of state that would need to be passed from pass to pass.

I'm open to suggestions.

> I'm also curious if at the end there will be any difference (besides the libraries being suggested from) between imported/not-imported completions? (eg. is there any difference in the logic that's choosing what to suggest, or is it just the same code running over a different set of libraries?)

No, I'm not aware of any difference in terms of what's suggested. The biggest difference I can think of off-hand is that not-yet-imported suggestions might need to add a prefix before the element name in order to avoid conflicts.

**Comment by scheglov** [comment]
Depending on the number of locations where we need to check `thereIsTime`, it might be fine.
It seems to me that we will not have too many of them.

`InScopeCompletionPass` would not be an ideal name then :-)
But we can rename it much later.

**Comment by scheglov** [comment]
Given that we removed NotImportedContributor, I suspect that Brian did whatever was necessary here.
