### ISSUE TITLE
GeneralizingAstVisitor.visitNamedType does not call `visitTypeAnnotation`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#55011]
Hello!

Currently the implementation of `GeneralizingAstVisitor.visitNamedType` is:

```dart
@override
R? visitNamedType(NamedType node) => visitNode(node);
```

The thing is, `NamedType` is a subclass of `TypeAnnotation`. It would likely be more correct to have:

```dart
@override
R? visitNamedType(NamedType node) => visitTypeAnnotation(node);
```

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/354440
