### ISSUE TITLE
New api.dart.dev cookie banner broken

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#55015]
https://api.dart.dev/main

The new cookie banner is showing up a the top of the page unstyled and unfunctional, there is a full-viewport length controls button at the bottom of the page that is not functional, and it is adding a lot of empty space to the footer.

This seems to happen both in the EU and US, and there are no errors in the browser console.

**Screenshot:**
<img width="800" alt="Screenshot of cookie banner" src="https://github.com/dart-lang/sdk/assets/18372958/6cbe49ef-3a70-4ce1-86a0-835454c0c4ed">

**Comment by athomas** [comment]
Known issue caused by the dartdoc header not being included because the header doesn't exist on stable, yet.

**Comment by parlough** [comment]
Thanks for the response. I'm not sure I fully understand though.

Why would the header existing on stable affect the `main` version of these docs?

**Comment by athomas** [comment]
Because the CI is currently configured with the same options across all channels and dartdoc fails if the header file is missing. This is a CI configuration issue, not an issue with the Dart SDK.
