### ISSUE TITLE
`dart fix` rename refactor not offered in type argument lists

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#55022]
We're using several declarative `dart fix` rename refactors to help people migrate from `dart:html` types to `package:web` types. We're seeing many places (50%?) where the rename refactors are not offered where they should be.

This location will be corrected offered a rename refactor (renaming to `HTMLLinkElement`):

<img width="576" alt="Screenshot 2024-02-24 at 10 39 05 AM" src="https://github.com/dart-lang/sdk/assets/1269969/7520c229-59ae-41f4-a9b5-0fd4cc77c768">

However, this location will not offer a refactor:

<img width="524" alt="Screenshot 2024-02-24 at 10 38 49 AM" src="https://github.com/dart-lang/sdk/assets/1269969/ded3fcd8-b234-446b-8a18-4191104c395e">

The dart fix data is declared here: https://github.com/dart-lang/web/blob/main/lib/fix_data.yaml.

cc @keertip

**Comment by devoncarew** [comment]
I'll take a look at my project, but from memory, they may all be in type  argument lists.

**Comment by bwilkerson** [comment]
Thanks.

The alternative is that we can fix the one known case and then you can let us know if there are other cases that are still failing. Might take longer to get everything working, but I'm hoping that this is the only case we missed, so maybe not.

**Comment by devoncarew** [comment]
I renamed this to `dart fix rename refactor not offered in type argument lists`; happy to file more specific issues if I do encounter additional places.

**Comment by keertip** [comment]
Thanks Devon! Do let us know if there are other places where this is not working as intended.

**Comment by srawlins** [comment]
Marked P2, but if this should be P1 for `package:web` let me know.

**Comment by devoncarew** [comment]
W/ the next sdk release, we are changing our messaging - new projects should start with package:web, dart:html is deprecated (or close), and people that want to support compiling their app to wasm will need to convert from using dart:html to package:web. So, addressing this issue (the main one I saw when migrating a medium sized app to package:web) would be nice :)

cc @srujzs @sigmundch
