### ISSUE TITLE
[dart:js_interop] Can't create an empty JS object with extension types.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#55041]
For example:

```dart
extension type AppProperties._(JSObject ref) implements JSObject {
  external AppProperties();
}
```

Got `TypeError: dart.global.AppProperties is not a constructor at ...` and `TypeError: self.AppProperties is not a constructor ...`.

**Comment by kevmoo** [comment]
@srujzs ?

**Comment by srujzs** [comment]
> фт

I'm guessing something got parsed incorrectly. :)

If there are no named parameters, `external` constructors are interpreted as named constructors i.e. it looks for a type "AppProperties" in JS.

If you just want an empty object, use `JSObject()`:

```dart
extension type AppProperties._(JSObject ref) implements JSObject {
  AppProperties() : ref = JSObject();
}
```
