### ISSUE TITLE
dart2js (dart compile js) allows compiling with dart:io import - runtime error

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/sdk#55048]
I've noticed that `dart compile js` allows import for `dart:io`, while `build_web_compilers` does not. 

This causes a situation where running tests with `dart run test -p "chrome"` will result in false "green" tests while projects depending on the package/library compiled with `build_web_compilers` will fail compiling.

A super simple repro code to demonstrate:

```dart
// in web/main.dart.js
import 'dart:io';

void main() {  
  stdout.writeln('Will it work with dart compile js?');  
}
```

This will compile with `dart compile js` command (though will throw a runtime error) but will fail to compile with `dart run build_runner build -r`.

I tested this behavior with 2.19 and 3.2.6 SDKs.

What am I missing? Why is it this way? What are the best practices here?

<details><summary>dart info</summary>
<p>

```
If providing this information as part of reporting a bug, please review the information below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "linux_x64"
- on linux / Linux 6.7.5-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Feb 17 17:20:08 UTC 2024
- locale is en_US.UTF-8

#### Project info

- sdk constraint: '>=2.19.0 <4.0.0'
- dependencies: 
- dev_dependencies: build_runner, build_test, build_web_compilers, lints, test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
| 582 MB | 1.1% |        25:41 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.82.0 |
| 407 MB | 1.1% |        23:40 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.82.0 |
```

</p>
</details>

**Comment by sigmundch** [comment]
Thanks for filing this issue @daniel-v! This indeed has a complex history. We have another issue tracking the same problem here https://github.com/dart-lang/sdk/issues/46917, so I'll mark this as a duplicate. You can read some historical context on [this comment](https://github.com/dart-lang/sdk/issues/46917#issuecomment-899640778).

In short, we are also sad about this and would love to fix it, but doing so is a big effort and not something we are prioritizing at the moment.

**Comment by daniel-v** [comment]
Thank you @sigmundch !
