### ISSUE TITLE
Dartdoc does not seem to parse `[namedtype]:` 

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#55043]
Consider the following dartdoc:

```dart
class Foo {}

/// See also [Foo]:
/// < some more docs >
class Bar {}
```

In this case, `[Foo]:` won't be interactive in the IDE: 

<img width="215" alt="Screenshot 2024-02-28 at 11 26 32" src="https://github.com/dart-lang/sdk/assets/20165741/90d0cd8d-afee-4082-b968-28641cb6d19d">

Removing the `:` or adding a whitespace after it fixes the issue:

```dart
/// See also [Foo] :
class Bar {}
```

<img width="212" alt="Screenshot 2024-02-28 at 11 27 53" src="https://github.com/dart-lang/sdk/assets/20165741/538813f4-f831-4153-9710-1a4688a259c1">

**Comment by rrousselGit** [comment]
Tested on Dart SDK version: 3.4.0-175.0.dev (dev) (Sat Feb 24 00:03:30 2024 -0800) on "macos_arm64"

**Comment by bwilkerson** [comment]
@srawlins @kallentu

**Comment by srawlins** [comment]
This was fixed at some point. We have a test case, `test_commentReference_followedByColon`, for this.
