### ISSUE TITLE
[dart2js] Root zone continues after async error

### ISSUE THREAD

**Issue by LewisHolliday** [dart-lang/sdk#55047]
```dart
import 'dart:async';

void main() {
  scheduleMicrotask(() {
    throw Error();
  });
  scheduleMicrotask(() {
    print('Did not stop');
    while (true){}
  });
}
```

On VM, the second microtask does not run, which is expected.

[root-constant](https://api.dart.dev/stable/3.3.0/dart-async/Zone/root-constant.html)
[handleUncaughtError](https://api.dart.dev/stable/3.3.0/dart-async/Zone/handleUncaughtError.html):
'By default, when handled by the root zone, uncaught asynchronous errors are treated like uncaught synchronous exceptions.'

**Comment by lrhn** [comment]
On the VM, an uncaught asynchronous error will terminate the isolate, unless the errors-are-fatal of the isolate is set to `false`.

On the web, uncaught errors are never fatal, because scripts cannot crash the browser or page.

So this is working as expected.

Fatal errors prevent all further execution, non-fatal errors are reported, and nothing much else happens.

What did you expect to happen here?

**Comment by LewisHolliday** [comment]
I expected the second microtask not to run based on existing documentation. That's because of the phrasing from the language spec and more specifically [root-consant](https://api.dart.dev/stable/3.3.0/dart-async/Zone/root-constant.html), which says, 'All isolate entry functions (main or spawned functions) start running in the root zone'. Until your response, I thought my above program was considered to be running in an isolate (regardless of platform) and would therefore suspend after an uncaught exception.

**Comment by lrhn** [comment]
Even on the VM, you can keep the isolate alive after an uncaught error. That also means it won't print the error, so if you want to know that it happened, you need to listen for it yourself, which you also can.
```dart
import "dart:async";
import "dart:isolate";
void main() async {
  var p = ReceivePort();
  var e = ReceivePort();
  e.take(3).forEach((l) {
    print(l[0]);
  });
  Isolate.current.setErrorsFatal(false);
  Isolate.current.addErrorListener(e.sendPort);
  Isolate.current.ping(p.sendPort);
  await p.first; // Wait for isolate command to have been processed.
  
  Timer(Duration(seconds: 1), () { print("tock"); });
  print("tick");
  Timer(Duration(milliseconds: 25), () { 
    throw AssertionError("Bim!"); 
  });
  scheduleMicrotask(() {
    throw AssertionError("Bum!");
  });
  throw AssertionError("Bam!");
}
```
