### ISSUE TITLE
[vm/ffi] Enable sending `NativeFinalizer`s over `Isolate.exit`?

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55050]
After https://dart-review.googlesource.com/c/sdk/+/354902, we will allow sending deeply immutable `Finalizable`s to other isolates in the same group. However, if a `NativeFinalizer` lives in an isolate that exits, but deeply immutable `Finalizable`s are still alive in other isolates, the native resources are prematurely finalized. Therefore, we should enable sending `NativeFinalizer`s to another isolate via `Isolate.exit`.

Currently, sending `NativeFinalizers`s is disallowed:

https://github.com/dart-lang/sdk/blob/83ba5916b7cefe7e1ae80925b58a7b1e0f11cb0f/runtime/vm/object_graph_copy.cc#L873

https://github.com/dart-lang/sdk/blob/83ba5916b7cefe7e1ae80925b58a7b1e0f11cb0f/runtime/vm/isolate.cc#L2389

Sending a `NativeFinalizer` to another isolate should have the effect of changing the isolate pointer to the receiving isolate.

Some open questions:

* What is the state in between that the message is send and that it is received? Running finalizers has the side effect of cleaning up the entries in the Dart heap via a message to the isolate. If there is temporarily no isolate while the finalizer is in flight, where should the clean up message be sent? (Presumably we _can_ run the native finalizer while it is in flight from one isolate to another, we do have access to the heap to access the address of the native callback and the token.)
* What is the state if the exit message is never handled?

If we do decide to support this, maybe we should add a `NativeFinalizer.adopt(NativeFinalizer other)` that will check if the native callback function is equal and then merge all the entries from the other finalizer. This will enable storing a finalizer in a static field and on isolate shutdown sending it to another isolate and merging it into the finalizer that's in the "same" static field already. (The alternative is that one might have a collection of adopted finalizers and can never clean up that collection.)

If we do not decide to support it, probably the best practise is that `NativeFinalizer`s should live on, and `Finalizable`s should be created on, an isolate that will stay alive until the end of the program (the main isolate or platform isolate). cc @liamappelbe @HosseinYousefi Do you have use cases where you want to create a `Finalizable` on a helper isolate that is subsequently going to exit after you've sent the `Finalizable` to the main isolate?

cc @mkustermann @mraleph 

(Things would be much easier if we could just mark the `NativeFinalizer` static field as `shared` across all isolates in the group, a la https://github.com/dart-lang/language/pull/3531, `shared final NativeFinalizer = ...`. We would not need to worry about sending it to another isolate on exit.)

**Comment by lrhn** [comment]
If you have a finalizer attached to an object, and you send that object through `Isolate.exit`, will the finalizer stay alive too (being implemented by heap merging would suggest so, but I can see arguments in either direction).
If so, that effectively keeps its callbacks alive, and allows them to run in the remaining isolate.
If not, I also assume the finalizer won't run, because cleaning up a reachable object is bad.

(I should check.)

But this is about native finalizers, which only do callouts to native functions, right?

Here it also matters what happens on `Isolate.exit`, even if you don't send the finalizer. Will it trigger, stay alive, or quietly go away with its isolate?

Sending (merging) the native finalizer to another isolate with `Isolate.exit` shoulder change how it behaves much, over not sending it, but it does allow you to interact and update the object during sending.

(Why does a native finalizer need an isolate reference? Is the native code run in a way that makes it being to that isolate?)

Whether an exit message is _handled_ shouldn't matter. It exists, and is delivered. Whether someone looks at it after that is up to them. If it languishes in the buffer of a paused `SteamSubscription`, that's what someone asked for.

The `adopt` functionality seems reasonable. Biggest question is whether later additions to the adoptee should be forwarded to the adopter too.

**Comment by dcharkes** [comment]
From a discussion with @HosseinYousefi:

* Migrating a NativeFinalizer to the longest living isolate is a leaky abstraction. We can’t encapsulate `JObject` properly. Users would need to know about the `NativeFinalizer` and send it to the longest living isolate with `Isolate.exit`. It is undesirable to burden users with this.
* Refcounting requires us to add a finalizer on messages send with `SendPort.send` not delivered. This can also not be encapsulated in `package:jni` and `package:jnigen`. The user would need to write the native finalizer argument in the `SendPort.send`, or we would need to provide `JObject.send(SendPort)`. Both don’t enable writing abstractions (larger object graphs containing JObjects).
   * We could introduce a `interface class MessageNotDeliveredNativeFinalizer` with a `get NativeFinalizerFunction callback`. Then if the message is not delivered we have a O(N) traversal of the full graph reachable from the message to see which objects implement this. (We cannot do this on message send, because deeply immutables on send because are O(1).)
* We could consider annotating NativeFinalizers with `@pragma('vm:sharable')` and allow users to mark static fields with `@pragma(‘vm:shared’)`. Basically we would need to make all operations on `NativeFinalizer`s concurrency safe. (We have some `Set` and `Expando` operations internally.)
  * Currently (without `shared`), we cannot say a native finalizer in an isolate group is going to stay alive forever, because a Dart code writer would not be able to say that this native finalizer object itself can be GCed. With a `shared`/`@pragma('vm:shared')` we can.
  * This is basically implementing a subset of https://github.com/dart-lang/language/pull/3531, but we would not allow users to annotate things `@pragma('vm:sharable')`.
  * It would be safe to annotate `Finalizables` with  `@pragma('vm:deeply-immutable')` only if the `NativeFinalizer` is in a static field marked `@pragma('vm:shared')`.

**Comment by mkustermann** [comment]
> Sending a NativeFinalizer to another isolate should have the effect of changing the isolate pointer to the receiving isolate.

If we have an object sharable across isolates, that object doesn't have an owning isolate. If this sharable object represents a resource, the resource is owned by the isolate group - not by an individual isolate.

=> We may want to disallow attaching native finalizers (with run-eagerly-on-isolate-shutdown semantics) to sharable objects.

**Comment by mkustermann** [comment]
> => We may want to disallow attaching native finalizers (with run-eagerly-on-isolate-shutdown semantics) to sharable objects.

This is somewhat of a separate issue, but may be worthwhile fixing.

Already today one can create deeply immutable objects (dart constants, but also deeply immutable typed data arrays). Attaching finalizers to them seems not a good idea. @dcharke could you make a CL to disallow that?

**Comment by dcharkes** [comment]
Okay, I think the conclusion is that we do not want to support sending `NativeFinalizer`s to other isolates. Rather we should support https://github.com/dart-lang/sdk/issues/55062.
