### ISSUE TITLE
Typo and a broken link in the dart2js pragma annotations docs

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#55063]
Hi,

`dart2js:resource-identifer` should probably be `dart2js:resource-identifier` instead and the current link is broken and is probably expected to be `resource_identifiers.md`.

The doc page: https://github.com/dart-lang/sdk/blob/main/pkg/compiler/doc/pragmas.md

**Comment by sigmundch** [comment]
Thanks for the issue and the PR to fix it! Closing now that #55064 landed.
