### ISSUE TITLE
Convert all formal parameters to named offered when there are no positional parameters to convert

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#55069]
Given a constructor with no positional parameters, such as
```dart
class C {
  C();
}
```
or
```dart
class C {
  C({int c});
}
```
the "Convert all formal parameters to named" refactoring is offered, even though there's no work for it to do.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Ah, I would be happy to fix this :-)

**Comment by scheglov** [comment]
For https://dart-review.googlesource.com/c/sdk/+/355302
