### ISSUE TITLE
[vm/ffi] Disallow attaching `NativeFinalizer`s to deeply immutable objects

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55067]
> => We may want to disallow attaching native finalizers (with run-eagerly-on-isolate-shutdown semantics) to sharable objects.
>
> This is somewhat of a separate issue, but may be worthwhile fixing.
>
> Already today one can create deeply immutable objects (dart constants, but also deeply immutable typed data arrays). Attaching finalizers to them seems not a good idea. @dcharkes could you make a CL to disallow that?

_Originally posted by @mkustermann in https://github.com/dart-lang/sdk/issues/55050#issuecomment-1971477405_

**Comment by dcharkes** [comment]
`CheckWritableInstr` is specialized for TypedData currently.

https://github.com/dart-lang/sdk/blob/f7434789d68f828aa5ede645d10314935c97389c/runtime/vm/runtime_entry.cc#L149-L151

We could parameterize `WriteEntryInstr` with en enum for what error to throw, and duplicate the runtime entry.

We could generalize the error message to "The object is immutable.", but that makes the error messages poor (both for trying to modify an immutable typed data and for trying to attach a native finalizer to an immutable object).

It might not be needed to go the slow-path + runtime entry route for `NativeFinalizer.attach` (it does a bunch of other checks as well). So we could also introduce a new `IsImmutableInstr` that just returns a bool and do the throwing in Dart code instead. On the other hand, it might not hurt to optimize `NativeFinalizer.attach` to do the throwing in a stub.

@rmacnak-google Any preferences?

**Comment by rmacnak-google** [comment]
I definitely prefer separate error messages over a vague general error message.  

Parameterizing WriteEntryInstr or a new IsImmutableInstr both seem fine to me, so whatever you find more convenient.
