### ISSUE TITLE
generated_plugin_registrant is adding _ to import file

### ISSUE THREAD

**Issue by hanumanAbacus** [dart-lang/sdk#55077]
Hi,

The class generated_plugin_registrant.cc generated for windows, linux as adding _ 

my class name is ABSPrinterPlugin, while generating the generated_plugin_registrant.cc its adding _ i.e a_b_c for the capital first three letters

#include <abs_printer/a_b_s_printer_plugin_c_api.h>

actual include file which is
#include <abs_printer/abs_printer_plugin_c_api.h>

**Comment by lrhn** [comment]
I believe this file is created by the Flutter SDK, so I recommend asking about it in the Flutter repository.
