### ISSUE TITLE
Unable to create NativeCallback from function

### ISSUE THREAD

**Issue by fusionconsulting** [dart-lang/sdk#55072]
I'm working on a Dart project that needs to call a dylib in Linux and receive a callback via a function pointer. All functions that call into the library are working as expected but I can't get the callback to work and there is very sparse information available to help find the problem.

    typedef EventHandlerFunction = UnsignedInt Function(UnsignedInt inEvent, UnsignedInt inPropertyID, UnsignedInt inParam, ffi.Pointer<Void> inContext); 

    UnsignedInt handleStateEvent(UnsignedInt inEvent, UnsignedInt inPropertyID, UnsignedInt inParam, ffi.Pointer<Void> inContext) {

      return const UnsignedInt();
    }

    final callback = NativeCallable<EventHandlerFunction>.isolateLocal(handleStateEvent, exceptionalReturn: 0);
                                                                       ^^^^^^^^^^^^^^^^
This appears to match the only examples I've found but I get the error:

    The type 'UnsignedInt Function(UnsignedInt, UnsignedInt, UnsignedInt, Pointer<Void>)' must be a subtype of 'UnsignedInt Function(UnsignedInt, UnsignedInt, UnsignedInt, Pointer<Void>)' for 'NativeCallable'
    
The required type matches the specified type so I'm stumped as to what the problem is. Can anyone shed any light on this?

**Comment by dcharkes** [comment]
Hi @fusionconsulting!

Your Dart function must be the Dart types, not the C types:

```dart
typedef EventHandlerFunction = UnsignedInt Function(UnsignedInt inEvent, UnsignedInt inPropertyID, UnsignedInt inParam, ffi.Pointer<Void> inContext); 

int handleStateEvent(int inEvent, int inPropertyID, int inParam, ffi.Pointer<Void> inContext) {

  return const UnsignedInt();
}

final callback = NativeCallable<EventHandlerFunction>.isolateLocal(handleStateEvent, exceptionalReturn: 0);
```

Sorry for the suboptimal error messages!

**Comment by fusionconsulting** [comment]
Ahh, thanks! I've been staring at that message for hours trying to work out what was different. I've updated to Dart types and it works as expected.
