### ISSUE TITLE
[macOS] OS::GetCurrentMonotonicTicks should probably use `CLOCK_UPTIME_RAW`.

### ISSUE THREAD

**Issue by knopp** [dart-lang/sdk#55071]
This would corresponds to other macOS API such as `CACurrentMediaTime()`. Otherwise we have a problem where DisplayLink callback gives target timestamp in based on `CLOCK_UPTIME_RAW`, but `fml::TimePoint` expects `CLOCK_MONOTONIC_RAW`.

Also the [documentation for `mach_absolute_time`](https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time) suggests `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)` as suitable replacement and `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)` is not mentioned in the [prohibited boot time API list](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api).

@rmacnak-google

**Comment by cbracken** [comment]
@rmacnak-google
For reference, the related patch that switched from `mach_absolute_time` to `clock_gettime_nsec_No problem!` which caused the issue: 
https://dart-review.googlesource.com/c/sdk/+/348044

**Comment by rmacnak-google** [comment]
`mach_absolute_time` and `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)` access the same clock and so have the same fingerprinting privacy implications.

`Dart_TimelineGetTicks/Micros` and `Timeline.now` do not promise any particular clock, only that it is suitable for measuring duration and for use with `Dart_RecordTimelineEvent`. If an application needs some particular clock, it should access that clock itself instead of assuming Dart timeline APIs use the same clock.

**Comment by knopp** [comment]
So does `CACurrentMediaTime()` and yet it's not mentioned in the document. I would assume there is a reason why apple singled out `mach_absolute_time` in the document and not mentioned either `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)` or `CACurrentMediaTime()`.

The issue here is that `Dart_TimelineGetTicks` is used in `fml::TimePoint` in Flutter, which right now leaks through the embedder API. I opened this issue because I think that maybe the original PR was overly cautious, but if that's not the case we'll need to handle this in the embedder.

**Comment by knopp** [comment]
I gave this another though - I think the correct solution is to not assume anything about the embedder API clock and always rebase the time, i.e. `CACurrentMediaTime()` -> `FlutterEngineGetCurrentTime()`.

I still think that maybe `CLOCK_MONOTONIC_RAW` is bit too defensive since we're using `CACurrentMediaTime()` anyway in other places of engine and can't really get rid of it, but the engine API doesn't make any guarantees about the clock and embedder should handle that properly.

**Comment by a-siva** [comment]
@knopp is there anything actionable on the Dart side for this ?

**Comment by knopp** [comment]
I don't think so. I'll close the issue.
