### ISSUE TITLE
Convert all formal parameters to named changes optional named parameters to required

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#55070]
Given the code
```dart
class C {
  C(int x, {int y = 0});
}
```
Using "Convert all formal parameters to named" changes the parameter `y` from an optional parameter into a required parameter. I think that it shouldn't.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/355302
