### ISSUE TITLE
[dart2wasm] Implement structs backed by TypedData

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55083]
Currently, dart2wasm assumes that all structs are backed by a `Pointer`.

https://github.com/dart-lang/sdk/blob/42ccd79cd12a640359fb729537f5b14a06055188/pkg/dart2wasm/lib/intrinsics.dart#L186-L193

dart2wasm can currently assume this, because it does not implement support for:

* Returning struct by value from FFI calls.
* `Struct.create`.

If either of these features is implemented in dart2wasm, compounds cannot be represented as the int address of the pointer.

Also, it would break nested compounds if the suggestion in https://github.com/dart-lang/sdk/issues/54892 is implemented, as the `_offsetInBytes` would not be saved anywhere.

**Comment by dcharkes** [comment]
> Also, it would break nested compounds if the suggestion in #54892 is implemented, as the `_offsetInBytes` would not be saved anywhere.

@mkustermann @osa1 @eyebrowsoffire Are you aware of any uses of nested structs or arrays in current `dart:ffi` usage (only skwasm right?) in dart2wasm?

**Comment by mkustermann** [comment]
We currently don't consider `dart:ffi` as a supported thing that end users will use. There's a limited use in flutter web engine, which is supported. I believe that limited use doesn't use structs by value and is also restricted to static `@Native` interop usages. None of the ffi tests in the `tests/ffi` test suite run on wasm - we only have `tests/web/wasm/ffi_native_test.dart`.

Longer term we'll require multiple memories for wasm. We'll have to see what functionality of `dart:ffi` we want to support and how to expose it to users - maybe through `dart:ffi` library - maybe not.

So for now we should ensure that the ffi features which the flutter web engine requires are tested in `tests/web/wasm/ffi_native_test.dart` and we keep that supported.

**Comment by mkustermann** [comment]
I'm going to close this in favor of the more general [Implement dart:ffi for the web](https://github.com/dart-lang/sdk/issues/46690).
