### ISSUE TITLE
[analyzer] Incorrect completion for redirecting constructors

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#55086]
Consider the following example:

```dart
class SomeClass {
  final String value;

  const SomeClass(this.value);

  const SomeClass.fromMap(Map<String, Object?> _) : value = '1';

  factory SomeClass.fromJson(Map<String, Object?> map)  // <-- start typing `=` here and then choose `SomeClass.fromMap`
}
```

what we get currently is `=SomeClass.fromMap(_)` when the correct redirecting constructor would be `= SomeClass.fromMap;`.

Side note: right now it also suggest all other constructors that have a different list of parameters and therefore cannot be used as a redirecting constructor. Not sure whether this is a desired behaviour.

**Comment by scheglov** [comment]
Looks similar to https://github.com/dart-lang/sdk/issues/53016 that I'm looking at.

**Comment by incendial** [comment]
The only difference is the point at which the suggestion appears. In my case it's right after typing `=` and in #53016 it's only after typing the constructor name.

Not sure how it affects a potential fix though.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/356286

**Comment by scheglov** [comment]
Not sure about checking for compatibility of formal parameters.
Our general rule is to over-suggest.
OTOH, we filter by `const`.
And the ultimate over-suggest is to suggest absolute everything :-)
Here we probably have not so many suggestions, so I will not implement such filtering by formal parameters for now.
