### ISSUE TITLE
IPV6 uri resolving creates invalid host

### ISSUE THREAD

**Issue by Leptopoda** [dart-lang/sdk#55085]
Trying to resolve two IPV6 Uri's against each other yields in an invalid result:
```dart
void main() {
  final $base = Uri.parse('http://[::1]');
  final reference = Uri.parse("http://[::1]/core/img/logo/logo.svg?v=0");
  final resolved = $base.resolveUri(reference);

  print($base);     // http://[::1]
  print(reference); // http://[::1]/core/img/logo/logo.svg?v=0
  print(resolved);  // http://::1/core/img/logo/logo.svg?v=0
  
  Uri.parse('http://::1/core/img/logo/logo.svg?v=0');  // throws a FormatException 
}
```

I'd expect the resolved URI to also contain the brackets as defined in https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2.
> A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").

I've reproduced the issue on `Dart 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "linux_x64"` and the current dartpad.

**Comment by lrhn** [comment]
The `reference` is a fully qualified URI, so it shouldn't do anything during resolution, just use the existing values.
Seems it uses the "host name", not the host name *source*.
