### ISSUE TITLE
quick-fix for `use_named_constants`

### ISSUE THREAD

**Issue by nate-thegrate** [dart-lang/sdk#55087]
`used_named_constants` doesn't have a quick-fix yet.

![named constant](https://github.com/dart-lang/linter/assets/10457200/d981a974-6f0b-458c-a911-f1a86413bc53)

But the lint messages already have the appropriate constant names, so hopefully this will be a quick quick-fix. :)

**Comment by Sahil-kachhap** [comment]
@srawlins can I work on this issue? I have read the relevant analysis server docs, and I am interested in working on this issue

**Comment by bwilkerson** [comment]
We always welcome contributions. You'll also need to read [the document about contributing](https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md#before-you-contribute), especially the linked section which explains how to sign the CLA that needs to be signed before we can accept a code contribution.

> Does there already exist a correction producer for this issue? I asked it since the image shows the relevant correction widget in the Lint message.

I'm not sure what you mean by "the relevant correction widget", but I'm not aware of a correction producer for this case. It's possible that one exists that I'm not seeing.

**Comment by Sahil-kachhap** [comment]
> We always welcome contributions. You'll also need to read [the document about contributing](https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md#before-you-contribute), especially the linked section which explains how to sign the CLA that needs to be signed before we can accept a code contribution.
> 
> > Does there already exist a correction producer for this issue? I asked it since the image shows the relevant correction widget in the Lint message.
> 
> I'm not sure what you mean by "the relevant correction widget", but I'm not aware of a correction producer for this case. It's possible that one exists that I'm not seeing.

Thanks, @bwilkerson, that was the first thing I did when I landed in this repo, I have gone through the guidelines and have also signed the CLA already.

Sorry I was not able to explain that "correction widget", I meant in the image shown above, the Lint message displays the correct widget to place there, so I thought there might be some logic or correction producer there.

**Comment by bwilkerson** [comment]
> ... the Lint message displays the correct widget to place there ...

That makes sense, thanks. No, there's no correction producer; the logic is currently all within the lint rule itself.

> Anything you can share like the relevant file to look for to know from where this Lint message gets formatted?

The logic to find a named constant is in [the implementation of the lint rule](https://github.com/dart-lang/sdk/blob/main/pkg/linter/lib/src/rules/use_named_constants.dart#L62). Specifically, the name of the constant is computed on line 86.

**Comment by srawlins** [comment]
Thanks @nate-thegrate for looking into this; let us know of any other questions along the way!

**Comment by Sahil-kachhap** [comment]
@bwilkerson The following test file snippet I wrote throws an error:- Target URI doesn't exist 'dart:ui' and name Offset isn't a class, should I also create a mock package in the ```mock_packages``` directory to mimic the Offset functionality or you have any other suggestion, I just need to test the quick-fix I have implemented before sending a PR?

```
// Copyright (c) 2022, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:analysis_server/src/services/correction/fix.dart';
import 'package:analysis_server/src/services/linter/lint_names.dart';
import 'package:analyzer_plugin/utilities/fixes/fixes.dart';
import 'package:test_reflective_loader/test_reflective_loader.dart';
import 'fix_processor.dart';

void main() {
  defineReflectiveSuite(() {
    defineReflectiveTests(UseNamedConstantsTest);
  });
}

@reflectiveTest
class UseNamedConstantsTest extends FixProcessorLintTest {
  @override
  FixKind get kind => DartFixKind.USE_NAMED_CONSTANTS;

  @override
  String get lintCode => LintNames.use_named_constants;

  Future<void> test_use_named_constant() async {
    await resolveTestCode('''
import 'dart:ui';
final value = const Offset(0, 0);
''');

    await assertHasFix('''
import 'dart:ui';
final value = Offset.zero;
}
''');
  }
}
```

**Comment by bwilkerson** [comment]
Our general approach for writing this kind of test is to make them self contained (and completely generic) whenever possible. I'd probably write the test code something like
```dart
final value = const C(0);

class C {
  final int f;
  const C(this.f);
  static const c = C(0);
}
```

That test doesn't require any code outside itself (and `dart:core`) so it's easier to see exactly what's required.

There are times when we need to use code from a specific package, so we do have mocks of those packages, but we try to avoid using them as much as possible. (It minimizes the number of uninteresting changes required when updating the mock packages to track with the real package.)

**Comment by Sahil-kachhap** [comment]
Thanks @bwilkerson , I have pushed the changes for review.

https://dart-review.googlesource.com/c/sdk/+/357400

**Comment by Sahil-kachhap** [comment]
@srawlins this issue can now be closed. My patch has been merged.

**Comment by nate-thegrate** [comment]
Thank you @Sahil-kachhap!
