### ISSUE TITLE
☂️ Move Dart SDK to AOT compiled tools

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#55091]
Dart SDK currently ships with a bunch of tools in App JIT snapshot form. This is a maintenance and performance liability given that:

- we have not been investing in JIT performance for many years now
- AOT has a better: startup, memory usage, performance.
- the same tooling is used in AOT compiled form internally. 

Because of that we are going to switch **all** tools to be AOT compiled - targeting 3.5 at latest. 

Here is the current list of snapshots:

- [ ] `analysis_server.dart.snapshot`
- [ ] `kernel-service.dart.snapshot`
- [ ] `dart_tooling_daemon.dart.snapshot`
- [x] `gen_kernel_aot.dart.snapshot`
- [ ] `dartdevc.dart.snapshot`
- [ ] `dart2js.dart.snapshot`
- [ ] `dartdev.dart.snapshot`
- [x] `frontend_server_aot.dart.snapshot`
- [ ] `kernel_worker.dart.snapshot`
- [ ] `frontend_server.dart.snapshot`
- [x] `dds_aot.dart.snapshot`
- [x] `dart2wasm_product.snapshot`

**Comment by a-siva** [comment]
This seems like a duplicate of https://github.com/dart-lang/sdk/issues/53576

**Comment by mraleph** [comment]
Guh. I knew we must have the issue, but I just could not find it. Thanks, Siva.

**Comment by mraleph** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/53576
