### ISSUE TITLE
[CP] Implement error about awaiting a type that is incompatible with await

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#55095]
### Commit(s) to merge

bf17088787e78e0eed7e4b4b7d662554c6efbf2a, 1672177c2023350aeb3e04794a0809cf3310185d, a5bbbe814fca8856416361ec884482c18c08e470, adee0a23999661d7e3c9d25ea44e3fbd399252aa, 690d49c1530d7acf621c285835608c7524eaab85

### Target

Stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/355542

### Issue Description

The new extension types feature contains a rule preventing an extension type from being used as the operand of an `await`, unless the extension type implements `Future`. However, the logic that was released in Dart 3.3.0 has a loophole in that it allows some types _based_ on an extension type to be used as the operand of an `await`, such as:
- A nullable extension type where the extension type doesn't implement future.
- A promoted type variable, where the promoted type is incompatible with await.
- A type variable with a bound that is incompatible with await.

The loophole was fixed in the specification on Jan 17 (https://github.com/dart-lang/language/pull/3560) and Jan 31 (https://github.com/dart-lang/language/pull/3598). However, the implementation of this fix didn't land until after the release cutoff for Dart 3.3. This cherry-pick closes the loophole for the stable release.

### What is the fix

- bf17088787e78e0eed7e4b4b7d662554c6efbf2a contains the test cases that validate the implementation against the specification.
- 1672177c2023350aeb3e04794a0809cf3310185d contains the initial CFE implementation of the new error.
- a5bbbe814fca8856416361ec884482c18c08e470 contains a refinement of the CFE implementation of the new error, based on https://github.com/dart-lang/language/pull/3598.
- adee0a23999661d7e3c9d25ea44e3fbd399252aa contains the initial analyzer implementation of the new error.
- 690d49c1530d7acf621c285835608c7524eaab85 contains a refinement of the analyzer implementation of the new error, based on https://github.com/dart-lang/language/pull/3598.

### Why cherry-pick

Since the extension types feature is so new, it's highly unlikely that it's seen enough widespread usage for anyone to have run into the loophole described above. It's far better to cherry-pick a fix to the loophole now, than to defer the fix until Dart 3.4.0 (at which point, use of the feature will probably be much more widespread).

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/54647

**Comment by itsjustkevin** [comment]
@johnniwinther and @mraleph can you take a look at this cherry-pick request.

**Comment by mraleph** [comment]
LGTM based on the following:

- Change localized to a newly released feature;
- Good test overage;
- Desire to prevent subsequent breaking change in the next release;

**Comment by johnniwinther** [comment]
LGTM
