### ISSUE TITLE
Macro `code` class `kind` field

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#55099]
I just noticed the `Code` object has a `kind` field described as:
```dart
  /// Can be used to more efficiently detect the kind of code, avoiding is
  /// checks and enabling switch statements.
  CodeKind get kind;
```

I don't think this comment is actually correct. While it can *possibly* be more efficient to do `code.kind == CodeKind.expressionCode` than `code is ExpressionCode`, it doesn't actually let you use the `code` object as an `ExpressionCode`.

The `Code` class hierarchy is `sealed`/`final` and the classes are not generic. It should be possible to do an `is ExpressionCode`, a leaf type, as a single "class ID" equality check, basically the same as `.kind == some_constant`, so if compilers are good enough at optimizing `is` checks, the "efficiency" part isn't necessarily true.
Same in a `switch`. A switch over a hierarchy of sealed supertypes with final leaf types, and non-generic, should be implementable as a computed goto, the class ID of the object allowing you to go directly to the correct branch.

However, both `is` and `switch`-with-type-check allows *promoting* the value to the actual type, which is necessary to actually use it. The `Code` object has only one useful field, the `List<Object> parts;`. Many of the subtypes have more fields, which means that even if I do `if (code.kind == CodeKind.namedTypeAnnotation)`, I still need to do `code as NamedTypeAnnotationCode` afterwards to actually use it, so using the `kind` is more work, not less.
(There are some code kinds that are nothing but their parts, including `CommentCode` and `ExpressionCode`. I'll bet at least some of those will get more fields later, like a comment maybe exposing its comment delimiters.)

I suggest removing the `kind`, and recommending people use `is` and `switch` on the types. Then we should work with the compilers (maybe just the VM) to make sure such checks and switches are as efficient as possible.

(I'm also not convinced that the use of Dart lists for `parts`, including creating new lists in `part` getters, is a good choice. Maybe consider a linked list of nodes, so that a nullable type annotation can just attach a `?` node after the last node of its underlying type, and say that it starts at the same node, and ends one node later. Then there won't be any copying.)

**Comment by davidmorgan** [comment]
This will likely look different with `dart_model`, we'll see.
