### ISSUE TITLE
Binding an rvalue StringRAII to a non-const lvalue reference, still StringRAII

### ISSUE THREAD

**Issue by CodeVisio** [dart-lang/sdk#55108]
Hi, 

inside sdk/tree/main/runtime/bin/file_win.cc at lines 413 through 416 a StringRAII rvalue is created and assigned to a StringRAII non-const lvalue reference, the explicit constructor of StringRAII (pls, see lines 325 and below).

```
413  StringRAII absolute_path_raii(
414      File::IsAbsolutePath(path)
415          ? StringRAII(path)
416          : StringRAII(ConvertToAbsolutePath(path, &is_ok)));
```

```
325 class StringRAII {
326  public:
327   explicit StringRAII(StringRAII& origin) {  // NOLINT
328    own_ = origin.own_;
329    s_ = origin.release();
330  }
331
332  explicit StringRAII(const char* s) : own_(false), s_(s) {}
333  explicit StringRAII(char* s) : own_(true), s_(s) {}
334  ~StringRAII() {
335    if (own_) {
336      free(const_cast<char*>(s_));
337    }
338  }
339  const char* str() const { return s_; }
340  const char* release() {
341    own_ = false;
342    return s_;
343  }
344
345 private:
346  bool own_;
347  const char* s_;
348 };

```

only msvc complains about that issue (even if in the wrong way, )while gcc & clang compile fine.
Please have [look](https://godbolt.org/z/jPc6bdbfj).

That is the classical example where a move constructor is more appropriate.

Did I miss something from the standard or is that a bug?

Thanks

**Comment by aam** [comment]
msvc ide seems to be unhappy with constructor `StringRAII(StringRAII& origin)` being `explicit`, not sure why.
It is declared as `explicit` to follow dart vm convention to prevent such constructors quietly added by the compiler.
Having said that msvc compiler seems to be fine with this - we have windows buildbot that builds dart vm using msvc compiler https://ci.chromium.org/ui/p/dart/builders/luci.dart.ci.sandbox/vm-msvc-windows

Are there concerns about this beyond ide warnings?

**Comment by aam** [comment]
Landed https://dart-review.googlesource.com/c/sdk/+/356140 that should address this..
