### ISSUE TITLE
gen_snapshot issues on vm-aot-mac-release-x64

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#55105]
The tests `vm/dart/v8_snapshot_profile_writer_test`, `vm/dart/unobfuscated_static_symbols_test`, and `vm/dart/use_add_readonly_data_symbols_flag_test` went from Pass -> RuntimeError on vm-aot-mac-release-x64.

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-aot-mac-release-x64/1604/overview

The following lines appear in the logs for all three failures:

```
Running clang -m64 -Wl,-no_compact_unwind -dynamiclib -nostdlib -o $name.so $name.S
Subcommand terminated with exit code 1.
Subcommand stderr:
ld: dynamic executables or dylibs must link with libSystem.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by whesse** [comment]
The Intel Mac builder machines were changed. We now have MacOS 13.6.4 instead of MacOS 10.15.7.
This change can't be reversed, so the build should be fixed to work on the new MacOS version. Backward compatibility can be followed-up on, but I think the newer OS version needs to work.
