### ISSUE TITLE
[analyzer] No error for some duplicate top-level declarations in augment library

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#55113]
According to the [Augmentation library specification](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md#defining-an-augmentation)

> It is a compile-time error if:
> 
>  - A top-level declaration in an augmentation has the same name as a declaration in the main library or another of its augmentations (unless it is an augmenting declaration, described below). This is the same error conceptually as having a name collision in one file.

But analyzer doesn't report errors for mixins, extensions and extension types. Example
```dart
// main_lib.dart
import augment 'aug_lib.dart';

class C {}

mixin M {}

enum E {e;}

void foo() {}

typedef void Foo();

typedef StringAlias = String;

int get getter => 42;

void set setter(int _) {}

extension Ext on List {}

extension type ET(int _) {}

var x = 0;

const c = 0;

main() {
  print(C);
  print(M);
  print(E);
  print(foo);
  print(Foo);
  print(StringAlias);
  print(getter);
  setter = 1;
  print(List);
  print(ET);
  print(x);
  print(c);
}

// aug_lib.dart
library augment 'main_lib.dart';

class C {} // Ok, error reported

mixin M {} // No error

enum E {e;} // Ok, error reported

void foo() {} // Ok, error reported

typedef void Foo(); // Ok, error reported

typedef StringAlias = String; // Ok, error reported

int get getter => 42; // Ok, error reported

void set setter(int _) {} // Ok, error reported

extension Ext on List {} // No error

extension type ET(int _) {} // No error

var x = 0; // Ok, error reported

const c = 0; // Ok, error reported
```
Tested using `Dart SDK version: 3.4.0-edge.59035021cf3ceb5aecf4c85ba0affd1d6aab8fa6 (main) (Wed Mar 6 01:30:11 2024 +0000) on "linux_x64"`

**Comment by bwilkerson** [comment]
Any updates?

**Comment by pq** [comment]
_Friendly triage ping_: any updates on this one?

**Comment by srawlins** [comment]
_Friendly triage ping_: any updates on this one?

**Comment by bwilkerson** [comment]
@scheglov Any updates?

**Comment by scheglov** [comment]
No.

**Comment by srawlins** [comment]
Is this P1 for the Dart 3.4 release? Is it being worked on or should someone else take it on?

**Comment by scheglov** [comment]
No, I downgraded it.

**Comment by sgrekhov** [comment]
Retested on `Dart SDK version: 3.6.0-edge.a6a2c57d689c5aca7d9fadd5dbf04615246ed198 (main) (Fri Sep 13 23:29:47 2024 +0000) on "linux_x64"` (augmentation libraries replaced with parts in the code above). No this issue now. Closing.
