### ISSUE TITLE
Clarify "Web int" for Wasm

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#55119]
We should update the text here:

https://dart.dev/guides/language/numbers

to clarify that `int` will be 64-bit (same as "Native") when dart2wasm is used instead of dart2js or ddc.

**Comment by parlough** [comment]
Thanks for the issue :) 

Going to close this in favor of https://github.com/dart-lang/site-www/issues/5609 and https://github.com/dart-lang/site-www/issues/5345 where we're tracking this update and other necessary changes. Feel free to add specific thoughts there :D
