### ISSUE TITLE
[dart2wasm]: Incorrect assignment of the variable `dartInstance` in the output.mjs

### ISSUE THREAD

**Issue by TheComputerM** [dart-lang/sdk#55140]
This tracker is for issues related to: dart2wasm

---

I have a file called `dart.main`.
```dart
void main(List<String> args) {
  final now = DateTime.now();
  print('now: ${now.hour}:${now.minute}');
}
```

I compile it to dart using `dart --enable-asserts ../dart_sdk/pkg/dart2wasm/bin/dart2wasm.dart ./lib/main.dart ./src/dart.wasm` (PS: same problem occurs if I compile using `dart compile wasm`). Which generates two files: `dart.wasm` and `dart.mjs`

I created a quick web app for importing the wasm build:
```js
import * as dart from "./dart.mjs";
import wasm_url from "./dart.wasm?url";

dart.instantiate(
    fetch(wasm_url).then((response) => response.arrayBuffer())
).then(({ instance, module }) => {
    console.log(dart.invoke(instance, "Hello"));
});
```
This results in an error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$makeStringList')
    at buildArgsList (dart.mjs:79:47)
    at Module.invoke (dart.mjs:233:22)
    at main.js:8:22
```

This is because dartInstance (which is supposed to be of type *WebAssembly.Instance*) is initialized to be of type *WebAssembly.WebAssemblyInstantiatedSource*. 
```js
// around line 220 in dart.mjs
dartInstance = await WebAssembly.instantiate(...);
```

To solve this we can just rewrite the above code as:
```js
const dartInstanceSource = await WebAssembly.instantiate(...);
dartInstance = dartInstanceSource.instance;
return dartInstanceSource;
```

which results in the correct console output: `now: 5:48`

General System info:
- Dart 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "linux_x64"
- on linux / Linux 6.7.8-zen1-1-zen
- Microsoft Edge Version 122.0.2365.63

**Comment by ykmnkmi** [comment]
Try this:
```html
<script type="module">
  import { instantiate, invoke } from './main.dart.mjs';
  const response = await fetch('main.dart.wasm');
  const bytes = await response.arrayBuffer();
  const module = new WebAssembly.Module(bytes);
  const instance = await instantiate(module, {});
  invoke(instance);
</script>
```

**Comment by TheComputerM** [comment]
Thanks, sorry my bad, I did not figure out that you have to initialize a WebAssembly.Module and figured you can pass the byte array.
