### ISSUE TITLE
Analysis server has terminated.

### ISSUE THREAD

**Issue by kanishk1046** [dart-lang/sdk#55151]
## Version information

- `IDEA AI-223.8836.35.2231.10811636`
- `3.1.5`
- `AI-223.8836.35.2231.10811636, JRE 17.0.6+0-17.0.6b829.9-10027231x64 JetBrains s.r.o., OS Mac OS X(aarch64) v14.1.2, screens 3360.0x2100.0  Retina`
<img width="1243" alt="Screenshot 2024-03-10 at 11 37 54" src="https://github.com/dart-lang/sdk/assets/103512864/c5badbfc-8af7-4831-8de3-b0676de719fa">

**Comment by kanishk1046** [comment]
please help me with this issue

**Comment by pq** [comment]
Sorry for the inconvenience, @kanishk1046! The first thing I'd do is make sure I'm on the latest version of Dart and the latest version of IDEA. If the issue persists, we'll need some more information. Anything you can tell us about what you were doing when server crashed? Can you reproduce it consistently? Failing easy steps, logs would be great. A few notes on capturing logs are here:

https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/tutorial/instrumentation.md
