### ISSUE TITLE
Immediate128 support in the object pool is unused

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#55166]
AFAICT it's dead code.

The only two possible entry points are:
https://github.com/dart-lang/sdk/blob/0cd55a18c1441fa9c64a1bee7fe55d9e0e066e6c/runtime/vm/compiler/assembler/object_pool_builder.h#L241
https://github.com/dart-lang/sdk/blob/0cd55a18c1441fa9c64a1bee7fe55d9e0e066e6c/runtime/vm/compiler/assembler/object_pool_builder.h#L272

And the former is never called, and the latter is never called with kImmediate128.  So as far as I can tell all the support in the object pool for 128 bit values is dead code?

Looks like it was added in https://github.com/dart-lang/sdk/commit/4ee35ee998eb1040de4938793cb7a11bc49b83c6 by @rmacnak-google and @aam.

Maybe I'm missing something and it is used somewhere?

**Comment by eseidel** [comment]
I missed one:

```cc
void Assembler::LoadQImmediate(VRegister vd, simd128_value_t immq) {
  ASSERT(constant_pool_allowed());
  intptr_t index = object_pool_builder().FindImmediate128(immq);
  intptr_t offset = target::ObjectPool::element_offset(index);
  LoadQFromOffset(vd, PP, offset);
}
```

But it turns out that's not called either.

**Comment by aam** [comment]
The https://github.com/dart-lang/sdk/commit/4ee35ee998eb1040de4938793cb7a11bc49b83c6 was followed by https://github.com/dart-lang/sdk/commit/bdacbb8decbab527a43ff1fbe289c8e55b0f6ba6 , but that one got reverted due to some test failures.

**Comment by a-siva** [comment]
@rmacnak-google do you know why https://dart-review.googlesource.com/c/sdk/+/244181 was not relanded ?

**Comment by aam** [comment]
Relanded 2bc1ace7fcfbd5a27f7066e2612efc9efb00a809
