### ISSUE TITLE
[CFE] Library cannot augment itself

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#55168]
Now the following code is accepted by CFE.
```dart
// Library 'main_lib.dart'.
library augment 'main_lib.dart';
import augment 'main_lib.dart';
...
```
According to the https://github.com/dart-lang/language/issues/3646 it should be a compile-time error

Tested with 
`Dart SDK version: 3.4.0-204.0.dev (dev) (Tue Mar 5 20:04:06 2024 -0800) on "windows_x64"`
`Dart SDK version: 3.4.0-edge.dfe0457f84352a402c7fe590c743cef3e2280509 (main) (Tue Mar 12 00:50:43 2024 +0000) on "linux_x64"`

**Comment by davidmorgan** [comment]
This is obsolete with https://github.com/dart-lang/language/issues/3848
