### ISSUE TITLE
Failures on [macros] Replace hardcoded skip with status file skip.

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#55162]
There are new test failures on [[macros] Replace hardcoded skip with status file skip.](https://github.com/dart-lang/sdk/commit/ebcae76d0d2e9011ccce911be845d05bc4558a81).

The tests
```
macro_build/cfe_lt_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux-x64
```

**Comment by davidmorgan** [comment]
It passed there--as I think it should--does that mean the failure is stale?

**Comment by bkonyi** [comment]
Oh that's interesting... I'm not sure why this test is still failing then. Maybe @athomas or @whesse will have some insight as to what's going on.

**Comment by davidmorgan** [comment]
Maybe it relates to me making a test change and a status file change in two PRs that landed simultaneously ... anyway let's try changing things a bit, I think it would be better on the "release" bot anyway

https://dart-review.googlesource.com/c/sdk/+/356840

**Comment by davidmorgan** [comment]
Looks like it went green :)
