### ISSUE TITLE
Dart WASM GC module interop with another Dart WASM GC module

### ISSUE THREAD

**Issue by alienself** [dart-lang/sdk#55175]
Hi,

Is it currently possible to create interops between two compiled dart wasm modules?

The use case would be to have dart library as a wasm module consumed by another "scripting" module.

Is it possible to avoid a js glue layer by sharing the same gc memory?

Otherwise is possible to load/link a dart dynamic library at runtime within a single wasm module? for instance does `final dylib = DynamicLibrary.open(path);` work on the web?

I have searched everywhere online but unable to get any info about this, I always see a single module being executed.

**Comment by devoncarew** [comment]
cc @osa1

**Comment by mkustermann** [comment]
> Is it currently possible to create interops between two compiled dart wasm modules?

Right now our focus is making one dart app compiled to wasm work well (remaining language/library work, interop with JS, code size, startup, performance, ...).

We do not offer a supported & stable way to interact with other wasm modules yet, but it may come (stay tuned!):

* **Dart app compiled to wasm interact with linear memory wasm**: In some sense a variant of `dart:ffi` for web / wasm. (We do have limited support for a subset of `dart:ffi` already: It's used by flutter web engine to directly call into another linear-memory wasm module instance, but we consider this as internal for now - as it only supports a subset of our `dart:ffi` and may require a redesign to work well for wasm). see e.g. https://github.com/dart-lang/sdk/issues/46690
* **Several dart apps compiled to wasm interact with each other**: If two dart apps are compiled independently to wasm then they are tree shaken independently atm, so their types may not even be compatible (imagine both apps use a class `Foo` but one of them uses only field `Foo.fieldA` and the other `Foo.fieldB` - then our tree shaker would have different wasm structs for `Foo` in the two apps, making it not possible to pass an object to another module, ...).

**Comment by mkustermann** [comment]
I'm going to close this in favor of two other bugs

* [Add `dart:ffi` support for the web](https://github.com/dart-lang/sdk/issues/46690)
* [Low-level `dart:wasm` support](https://github.com/dart-lang/sdk/issues/55856)
