### ISSUE TITLE
A language test involving timezones potentially needs an update to account for daylight saving time changes

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#55171]
I discovered the issue while working on https://dart-review.googlesource.com/c/sdk/+/356760, which doesn't involve timezones in any ways. Test `corelib/date_time7_test` was failing in configuration `vm-win-release-x64-try`.

The reported error is as follows:

```
Unhandled exception:
Expect.equals(expected: <-7>, actual: <-8>) fails.
#0      Expect._fail (package:expect/expect.dart:721:5)
#1      Expect.equals (package:expect/expect.dart:145:5)
#2      testLocal.checkOffset (file:///C:/b/s/w/ir/tests/corelib/date_time7_test.dart:36:16)
#3      testLocal (file:///C:/b/s/w/ir/tests/corelib/date_time7_test.dart:46:3)
#4      main (file:///C:/b/s/w/ir/tests/corelib/date_time7_test.dart:55:3)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
It seems unrelated to the change I was working on, so I believe it's an issue with the test.

It's strange that the error manifests only in one configuration.

**Comment by mkustermann** [comment]
Maybe this is somehow related to US switching to summer time?

**Comment by parlough** [comment]
Have you rebased after https://github.com/dart-lang/sdk/commit/b0236fdde5eec3adb60db672d82c089bae6af780 landed?

**Comment by chloestefantsova** [comment]
> Have you rebased after [b0236fd](https://github.com/dart-lang/sdk/commit/b0236fdde5eec3adb60db672d82c089bae6af780) landed?

I think so: whenever I try to use the rebase button in Gerrit, it says the CL is already up to date. Yet, it shows the failure on the bot. Maybe the build system haven't picked up https://github.com/dart-lang/sdk/commit/b0236fdde5eec3adb60db672d82c089bae6af780 yet.

<img width="1534" alt="Screenshot 2024-03-12 at 12 59 26" src="https://github.com/dart-lang/sdk/assets/519320/ed7711e7-bb1a-4dc6-9c8b-76ee8cad1b91">

**Comment by chloestefantsova** [comment]
It's possible that Gerrit doesn't see https://github.com/dart-lang/sdk/commit/b0236fdde5eec3adb60db672d82c089bae6af780 in my case due to my CL using `stable` in the upstream, and https://github.com/dart-lang/sdk/commit/b0236fdde5eec3adb60db672d82c089bae6af780 is merged into `main`.

**Comment by mraleph** [comment]
Stable does not have the fix - so we should just approve the failure.

**Comment by chloestefantsova** [comment]
> Stable does not have the fix - so we should just approve the failure.

Ok, I'm closing the issue then.
