### ISSUE TITLE
Update InScopeCompletionPass to include all local and imported suggestions

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#55177]
So that if `NotImportedContributor` is disabled, we still get these suggestions.

Split from https://github.com/dart-lang/sdk/issues/55013

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/357210

**Comment by DanTup** [comment]
> So that if `NotImportedContributor` is disabled

I think also if we make this change:

https://github.com/DanTup/sdk/commit/7e67a5632674df8e32ffebe4f845bba99e67c68e#diff-85f9a1df801583aa0f54dd9f6ed5a5d7f09147c690d70a610e20789a85bb7881L53-R53

(which I think we should, when it doesn't result in test failures?)

**Comment by bwilkerson** [comment]
Yes, code cleanup is always reasonable.

**Comment by scheglov** [comment]
Yes, this is preparing for the case when `NotImportedContributor` is not suggesting local declarations.
Once in-scope logic is updated, we can land the not-yet-imported fix.

**Comment by scheglov** [comment]
Given that we removed `NotImportedContributor`, I suspect that Brian did whatever was necessary here.
