### ISSUE TITLE
No name completion after `in`

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#55186]
```dart
class InputValue {}

class A {
  final InputValue in^;
}
```
By some reason I get `int` here, but for `inp` I get `inputValue`.
Apparently we parse `in` (a keyword) specially, and this does not work well for completion.

**Comment by scheglov** [comment]
Similarly for
```dart
    required this.in,
```

**Comment by DanTup** [comment]
Maybe dupe of https://github.com/dart-lang/sdk/issues/48883?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/358020

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/357943
