### ISSUE TITLE
dart2js: doesn't report expected compile-time errors

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#5519]
The following tests are failing after changing test.dart to distinguish between compile-time and runtime errors:

co19/Language/11_Statements/14_Throw_A03_t01: fail
co19/Language/13_Libraries_and_Scripts/4_Scripts_A03_t01: fail
co19/Language/13_Libraries_and_Scripts/4_Scripts_A03_t03: fail

language/bad_constructor_test/04: fail
language/bad_constructor_test/05: fail
language/bad_constructor_test/06: fail
language/constructor_named_arguments_test/01: fail
language/external_test/10: fail
language/getter_no_setter2_test/01: fail
language/getter_no_setter_test/01: fail
language/illegal_invocation_test/03: fail
language/isnot_malformed_type_test/01: fail
language/new_expression_type_args_test/01: fail
language/not_enough_positional_arguments_test/01: fail
language/not_enough_positional_arguments_test/02: fail
language/optional_named_parameters_test/01: fail
language/optional_named_parameters_test/03: fail
language/optional_named_parameters_test/05: fail
language/optional_named_parameters_test/07: fail
language/optional_named_parameters_test/09: fail
language/setter_no_getter_call_test/01: fail
language/setter_no_getter_test/01: fail

I suspect some of these tests are incorrect (due to relaxed semantics in Dart Programming Language Specification 0.11).

More investigation is needed.

**Comment by sigmundch** [comment]
seems that all these has been fixed except one case, where we are reporting an error that is too strong. I'm closing this bug and created #25225 to track that.
