### ISSUE TITLE
ObjectPoolBuilderEntry empty constructor uses uninitialized memory

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#55199]
Unless I'm reading this wrong, I'm pretty sure this does not actually initialize:

https://github.com/dart-lang/sdk/blob/0cd55a18c1441fa9c64a1bee7fe55d9e0e066e6c/runtime/vm/compiler/assembler/object_pool_builder.h#L79

Which calls simd128_value_t(), which if I remember my C++, does not actually initialize:
https://github.com/dart-lang/sdk/blob/0cd55a18c1441fa9c64a1bee7fe55d9e0e066e6c/runtime/platform/globals.h#L146

I'm not sure this actually matters?  We were just trying to track down what appears to be uninitialized memory usage during ObjectPool construction in our Dart Fork, and saw this potential miss?

**Comment by eseidel** [comment]
Hmm. Supposedly the C++ default constructor will initialize pod types to 0?  Maybe I'm just used to C++ 98 or whatever 🤣 

https://stackoverflow.com/questions/321351/initializing-a-union-with-a-non-trivial-constructor

So I guess this can be closed?

**Comment by mraleph** [comment]
It will be 0 initialized.

**Comment by eseidel** [comment]
In my defense, we just lost a day due to the fact that C++ does *not* initialize this to zero:

```cc
class Hasher {
   void DoTheThing();
   uint32_t hash_;
}

Hasher hasher;
hasher.DoTheThing(); // Was happily starting from a non-zero value when compiled with -O2 (-O0 works fine)
```
😭
