### ISSUE TITLE
[native-assets] Windows lookup fails when exe is symlinked

### ISSUE THREAD

**Issue by dnys1** [dart-lang/sdk#55207]
From the `native_add_app` example, run the following:

```sh
$ dart --enable-experiment=native-assets build .\bin\native_add_app.dart
$ .\bin\native_add_app\native_add_app.exe
Invoking a native function to calculate 1 + 2.
Invocation success: 1 + 2 = 3.
```

All good. 

Now, create a symlink for the exe and run that:

```sh
$ New-Item -Path .\native_add_app.exe -ItemType SymbolicLink -Value .\bin\native_add_app\native_add_app.exe
$ .\native_add_app.exe
Invoking a native function to calculate 1 + 2.
Unhandled exception:
Invalid argument(s): Couldn't resolve native function 'add' in 'package:native_add_library/native_add_library.dart' : Failed to load dynamic library 'native_add_library.dll': Failed to load dynamic library 'c:/workspace/native/pkgs/native_assets_cli/example/native_add_app/native_add_library.dll': The specified module could not be found.
 (error code: 126).

#0      Native._ffi_resolver.#ffiClosure0 (dart:ffi-patch/ffi_patch.dart)
dart-lang/native#1      Native._ffi_resolver_function (dart:ffi-patch/ffi_patch.dart:1386)
dart-lang/native#2      add (package:native_add_library/native_add_library.dart)
dart-lang/native#3      main (file:///c:/workspace/native/pkgs/native_assets_cli/example/native_add_app/bin/native_add_app.dart:9)
dart-lang/native#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
dart-lang/native#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

The relative lookup of the native assets seems to be dependent on the location of the executable file, but not the resolved executable file. Note that this behavior is only present on Windows. Performing the same on macOS/Linux works.

```sh
$ dart --enable-experiment=native-assets build bin/native_add_app.dart
$ ./bin/native_add_app/native_add_app.exe
Invoking a native function to calculate 1 + 2.
Invocation success: 1 + 2 = 3.
$ ln -s ./bin/native_add_app/native_add_app.exe native_add_app.exe 
$ ./native_add_app.exe
Invoking a native function to calculate 1 + 2.
Invocation success: 1 + 2 = 3.
```

This came up when bundling an AOT-compiled CLI for Windows which requires using execution aliases on Windows (e.g. symlinks). There are currently no good workarounds for this, in part because the eventual path of the resolved exe is unknown at compilation time -- best I have found is downloading the DLL separately to a known path and using `DynamicLibrary.open` to trick the native assets feature into working.

**Comment by dcharkes** [comment]
Thanks for the report @dnys1!

I think this will need to be fixed in the VM.

A relevant test should most likely be added somewhere here: https://github.com/dart-lang/sdk/blob/main/tests/ffi/native_assets/asset_relative_test.dart

The fix must most likely be in https://github.com/dart-lang/sdk/blob/main/runtime/lib/ffi_dynamic_library.cc.

We're open to contributions!

**Comment by dnys1** [comment]
Sounds good. Thanks @dcharkes!

**Comment by dnys1** [comment]
It seems like all the utilities to do resolve symlinks are available in `runtime/bin/file_win.cc` but these are not currently accessible in `ffi_dynamic_library.cc`. How should I think about reusing this code vs. exploring a different approach?

**Comment by dcharkes** [comment]
We have the following code layering in our codebase:

https://github.com/dart-lang/sdk/blob/1eab8550ea6c4cfb6bc1d380d00396e2f10f3bfd/runtime/tools/embedder_layering_check.py#L16-L55

1. runtime/platform should not import from runtime/(lib|vm), and runtime/bin
2. runtime/(lib|vm) should not import from should not import from runtime/bin
3. runtime/bin should not import from runtime/(lib|vm)

So, `runtime/lib/ffi_dynamic_library.cc`, cannot import `runtime/bin/file_win.cc` because of 2.

Both runtime/lib and runtime/bin can import from runtime/platform, we should move the symlink resolution logic in `File::GetCanonic` to runtime/platform.
(`Utils::LoadDynamicLibrary` is already in runtime/platform for example.)

I think it would be fine to create a `FileGetCanonicalPath` in `runtime/platform/file_win.cc` (and `.h`) and use that in both `runtime/bin/file_win.cc` and  `runtime/lib/ffi_dynamic_library.cc`.

**Comment by dnys1** [comment]
Hey @dcharkes, I took a stab a this but I keep running into walls. It seems like a pretty large lift as there are a lot of functions and classes which would need to be moved from `runtime/bin` to `runtime/platform`. Doing so also means that functions like `DartUtils::ScopedCString` , which are used in string processing, can no longer be used.

I don't know much C++ so it's possible I'm over-complicating it. I would appreciate your eyes whenever you get a chance. Thanks!

**Comment by dnys1** [comment]
Working around this has been trying as well. Some things I've tried and arrived at:

1. ❌ Using process lookup on Windows and manually loading the dylib by path at runtime.

This almost works but means that the CLI will not bundle the asset, so I would need to compile & bundle it myself.

2. ❌ Output a second asset with the same ID only for Windows with type process as a "fallback" to the bundled asset.

The runtime does not allow multiple resolution mechanisms for the same asset ID.

3. ❌ Output a second asset with a dummy ID for Windows with type process

The native asset resolver will always try to load the specific asset ID, even for a symbol already loaded into the process.

4. ✅😓 Create a wrapper over two versions of the native asset, bundled + loaded, and at runtime choose between one of the two.

This works, but boy is it a mess. I need a total of three ffigen files: one for each resolution strategy and a third with common symbols so that the two sets of functions can share an interface.

https://github.com/celest-dev/celest/commit/572cf633a000634df18cd2ab849515a54a3c0f66#diff-3651bca4d8be3c242eb1754187ab0a504bd7777beb044e14a55f22218b8fc7cd

**Comment by dnys1** [comment]
Makes sense. What do you think about fallback resolution? In general, this seems like it could be useful. Maybe not with bundled assets, since they should always be there, but I could imagine a case where you may want to search different system paths like many libraries currently do with non-Native FFI.

**Comment by dcharkes** [comment]
Looping back here. @dnys1 No surprise you got stuck. After some discussions it has become clear that the embedder should be responsible for resolving uris. We should do the same for `DynamicLibrary.open` (https://github.com/dart-lang/sdk/issues/37771). (The flutter embedder might subsequently use the C++ code from the Dart embedder to do such thing. That is how dart:io is implemented in Flutter, it reuses the C++ code.)

This is a rather involved change, thanks for taking an initial stab! (And sorry for sending you into the weeds! 😅 )

**Comment by dnys1** [comment]
@dcharkes ah great to hear and thanks for diving into it! Really appreciate the help 💪

And no worries at all, I relish in the chance to see the weeds (more like flowers in Dart's case 😜)!

**Comment by dcharkes** [comment]
@dnys1 I've created a prototype in case you're curious about a possible solution: https://dart-review.googlesource.com/c/sdk/+/361881

This respects the layering by moving the actual dlopen and dlsym calls to the standalone embedder (`bin/`) and removes that logic from the VM (`runtime/`). The VM then calls the embedder API to do these calls. And the flutter embedder will have to import the dart standalone embedder C++ code to register the same dlopen and dlsym callbacks. 🚧 🔨 🪚

**Comment by dcharkes** [comment]
@dnys1 This should have landed in the dev branch last week.

**Comment by dnys1** [comment]
Hey @dcharkes, thank you so much for your hard work on this. I was watching the PRs and saw the complexity involved.

I can confirm this works in all but one use case, and that's when there is a space in the path of the resolved executable. In that case, the spaces appear as `%20` in the `LoadLibraryW` call which Windows is not happy about. This can happen, for example, when the resolved executable lives in `Program Files`.

The following example demonstrates this behavior (using `native_add_app` again):

```powershell
$ dart --enable-experiment=native-assets build --output="native output" .\bin\native_add_app.dart
$ New-Item -Path .\native_add_app.exe -ItemType SymbolicLink -Value ".\native output\native_add_app.exe"
$ .\native_add_app.exe
Invoking a native function to calculate 1 + 2.
Unhandled exception:
Invalid argument(s): Couldn't resolve native function 'add' in 'package:native_add_library/native_add_library.dart' : Failed to load dynamic library 'lib\native_add_library.dll': Failed to load dynamic library 'c:/workspace/native/pkgs/native_assets_cli/example/build/native_add_app/native%20output/lib/native_add_library.dll': The specified module could not be found.
 (error code: 126).

#0      Native._ffi_resolver.#ffiClosure0 (dart:ffi-patch/ffi_patch.dart)
#1      Native._ffi_resolver_function (dart:ffi-patch/ffi_patch.dart:1523)
#2      add (package:native_add_library/native_add_library.dart)
#3      main (file:///c:/workspace/native/pkgs/native_assets_cli/example/build/native_add_app/bin/native_add_app.dart:9)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

This is running against the current `main`:

```
Dart SDK version: 3.5.0-edge.09e87e6d7bd18e3b08cc96c3a42b8e3f37a096d6 (main) (Wed Jun 19 14:50:30 2024 +0000) on "windows_x64"
```
