### ISSUE TITLE
[analyzer] TypeParameterElement Return Wrong Name

### ISSUE THREAD

**Issue by hakanberkbalcilar** [dart-lang/sdk#55208]
I have this kind getter
`Table<Passenger> get passengers =>`

and i try to get typeParameters of returnType of passengers which is Table<Passenger>.

when i try .name or .displayName methods they return 'T';

I was also try to use bound method but its element return name of class which T extends.

Did i try wrong methods or there is a bug that affects generic types?

analyzer: ^6.4.1
Dart version: 3.3.1

**Comment by bwilkerson** [comment]
Can you provide a bit more detail?

Are you getting the element for the getter from the declaration site or from an invocation site?

Which APIs are you using? Maybe just a small code snippet showing how you've written your code.

**Comment by bwilkerson** [comment]
Thanks. So in the line
```dart
final typeParameters = (table.element as ClassElement).typeParameters;
```
what is the static type of `table`?

If it's an `InterfaceType`, then I believe that what you're looking for is
```
final genericType = type.typeArguments.first;
```

The type parameters are the variables in the declaration of the type that represent an as-yet-unknown type, and the type arguments are the values of those parameters.

**Comment by hakanberkbalcilar** [comment]
> typeArguments

It is return 'T'

this is the new code

```
        final typeArguments = (table.returnType.element as ClassElement).thisType.typeArguments;

        final genericType = typeArguments.first;

        buffer.writeln(genericType.element?.name);
```

**Comment by bwilkerson** [comment]
Sorry, for the confusion. The critical question was: what class of object is stored in `table`? I then made the mistake of guessing a class and proposing a solution, which probably confused the conversation.

**Comment by hakanberkbalcilar** [comment]
> Sorry, for the confusion. The critical question was: what class of object is stored in `table`? I then made the mistake of guessing a class and proposing a solution, which probably confused the conversation.

'Car' or 'Passenger' which are extends from Entity interface and i can only get 'Entity' as a name

**Comment by bwilkerson** [comment]
I meant the variable `table` in `table.returnType.element`. If you write `print(table.runtimeType())`, what get's printed out?

My guess is that it will print `FunctionTypeImpl`, and that the runtime type of `table.returnType` is an `InterfaceTypeImpl`.

If that's correct, then you need to write `table.returnType.typeArguments.first` to get the type you're looking for.

**Comment by hakanberkbalcilar** [comment]
> I meant the variable `table` in `table.returnType.element`. If you write `print(table.runtimeType())`, what get's printed out?
> 
> My guess is that it will print `FunctionTypeImpl`, and that the runtime type of `table.returnType` is an `InterfaceTypeImpl`.
> 
> If that's correct, then you need to write `table.returnType.typeArguments.first` to get the type you're looking for.

The code that i share with you is in for loop and each
table is already pointing the returnType of each get method.

```
Table<Car> get cars => table<Car>();
Table<Passenger> get passengers => table<Passenger>();

```

**Comment by bwilkerson** [comment]
When you're using the `analyzer` package to analyze a piece of code, it builds a representation of the code being analyzed. The representation consists of AST nodes, elements, and types. The value of the variable `table` is a _representation_ of `Table<Car>` or some other type, but it's an instance of one of the classes defined in the analyzer package, not a class in the code being analyzed. What I've been trying to find out is the class defined in the analyzer package that you have an instance of (which is what printing the `runtimeType` would tell you).

> The code that i share with you is in for loop and each

But, maybe the better way to try to get to an answer is to go back to the code you originally sent:

```
final typeParameters = (table.element as ClassElement).typeParameters;
final genericType = typeParameters.first;
buffer.writeln(genericType.declaration.name);
```

I'm guessing that this code is the body of the for loop you mentioned in the quoted line above.

If that's the case, try replacing the body of the for loop with exactly the following:

```
final genericType = table.typeArguments.first;
buffer.writeln(genericType.declaration.name);
```

If that doesn't compile, try `(table as InterfaceType).typeArguments.first`. What gets written out when you do that?

**Comment by hakanberkbalcilar** [comment]
> (table as InterfaceType).typeArguments.first

last code you mention is worked thanks
