### ISSUE TITLE
[bug wasm/js] jsify/dartify issue converting a simple int

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/sdk#55203]
I'm using flutter master 3.21.0.7.0.pre.47 and dart 3.4.0

The following code:
```
print(1.jsify().dartify());
print(1.toJS.dartify());
```

prints `1` when compiled as javascript and `1.0` when compiled as wasm (following flutter instructions)

So it seems all int are converted to double. Is this normal? If yes, how to properly do a int or double conversion in wasm without loosing the type?

**Comment by mkustermann** [comment]
The documentation of [jsify](https://api.dart.dev/dev/3.4.0-227.0.dev/dart-js_interop/NullableObjectUtilExtension/jsify.html) and [dartify](https://api.dart.dev/dev/3.4.0-227.0.dev/dart-js_interop/JSAnyUtilityExtension/dartify.html)  discourage usage of this.

/cc @srujzs Could we remove those entirely? (they make a choice for int/double internally which isn't necessarily what users expect, so we may want to force users to make this choice by using the normal `jsNumber.toDart{Int,Double}`)

> So it seems all int are converted to double. Is this normal? If yes, how to properly do a int or double conversion in wasm without loosing the type?

JS only has doubles
* Dart2JS has only one number representation, the JS numbers, which are doubles. The printing may print the double as it were an integer if it has no fractional part.
* Dart2Wasm has real wrap-around `int64` and `double`s, but once you go to JS you give up that distinction and have a JS double (may loose precision from the `int64`).

When getting a JS number (which is a double) one can represent it precisely as a Dart `double`. Representing it as a `int` may loose precision. One could argue we should represent it as `int64` if the double is representable as it, but it's still not consistent behavior.

If you work with JS numbers you have a JS number (i.e. double) and should make a choice how to represent it in Dart:
```dart
import 'dart:js_interop';

void main() {
  int dartInt = 4;
  double dartDouble = 4.2;

  JSNumber jsNumber1 = dartInt.toJS;   // User responsible that this isn't losing precision
  JSNumber jsNumber2 = dartDouble.toJS;

  int dartInt2 = jsNumber1.toDartDouble;
  double dartDouble2 = jsNumber2.toDartInt;  // User responsible that this isn't losing information
}
```

**Comment by alextekartik** [comment]
Thank you for the explanation. This will however change the behavior of some apps moving to wasm for example reading complexed (javascript) data from indexeddb as any integer will be read as a double by default.

I ended up writing my own dartify when moving [`idb_shim`](https://pub.dev/packages/idb_shim) (that wraps web/indexed db to the existing dart:indexed_db dart api) to support wasm - i try to convert number to int first - here: https://github.com/tekartik/idb_shim.dart/blob/1494b87f870b03b18837f90409f2a5fafc98c77f/idb_shim/lib/src/native_web/js_utils.dart#L117-L172

What would be the best way to dartify the data read (the int value might be deep down in a sub map or sub list of the record data) in such case ?

**Comment by mkustermann** [comment]
> Thank you for the explanation. This will however change the behavior of some apps moving to wasm for example reading complexed (javascript) data from indexeddb as any integer will be read as a double by default.

As you point out, one can write custom `jsify()` / `dartify()` with different semantics.

I've filed https://github.com/dart-lang/sdk/issues/55222 to discuss this problemantic API on our team, maybe we should remove it or offer different API for different use cases.

> What would be the best way to dartify the data read (the int value might be deep down in a sub map or sub list of the record data) in such case ?

I'd encourage you to avoid using exceptions: If you always try `toDartInt` and end up having many doubles, it will throw many exceptions - which will be very slow.

A better way is to always convert JS number to Dart doubles. Then use a conditional import  (e.g. conditional import can use `if (dart.library.html)` condition to detect dart2js) which on
* dart2js will be a NOP (as dart2js doesn't distinguish ints from doubles)
* dart2wasm: Doing something like this
 ```dart
  final double jsDouble = value.toDartDouble;
  final int jsInt = jsDouble.truncate();
  return (jsInt.toDouble() == jsDouble) ? jsInt : jsDouble; 
 ```

I'm going to close this in favor of https://github.com/dart-lang/sdk/issues/55222 which discusses the current `jsify()` / `dartify()` API.
