### ISSUE TITLE
No error in analyzer if augmentation libraries have different versions

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#55205]
According to the augmentation library specification

>  It is a compile-time error if:
>  ...
>  - The main library and its augmentations do not all have the same language
>    version. There is only one user-visible library at the end, and it should
>    have a consistent version across its entire surface area.

But the following [test](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Augmentation-libraries/applying_augmentation_library_A04_t01.dart) produces no error in the analyzer
```dart
// applying_augmentation_library_A04_t01.dart
// @dart=3.4

// SharedOptions=--enable-experiment=macros

import augment 'applying_augmentation_library_A04_t01_lib.dart';
//              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified

main() {
}

// applying_augmentation_library_A04_t01_lib.dart
// @dart=3.3

// SharedOptions=--enable-experiment=macros

library augment 'applying_augmentation_library_A04_t01.dart';
```

**Comment by davidmorgan** [comment]
I expect this will be obsoleted by https://github.com/dart-lang/language/issues/3848
