### ISSUE TITLE
[CP] Ensure CpuInfo Windows flag detection works, doesn't crash on pre-sse41 cpus

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#55211]
### Commit(s) to merge

c5946a11952b43b80cf6572965696ae29f0259d4

### Target

both

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/357983
https://dart-review.googlesource.com/c/sdk/+/358040

### Issue Description

CPU detection wasn't working correctly on Windows, caused crashes of dart and flutter apps when running on older pre-sse41 cpus.

### What is the fix

Ensure information about detected cpu features is properly used on Windows.

### Why cherry-pick

Fix flutter and dart crashes for Windows users who also use older machines.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/140138, https://github.com/flutter/flutter/issues/138784, https://github.com/flutter/flutter/issues/138693

**Comment by mit-mit** [comment]
SGTM

**Comment by itsjustkevin** [comment]
@aam this CL is still showing errors on both beta and stable.  Are these expected?

**Comment by aam** [comment]
@itsjustkevin yeah, errors are unrelated and are expected: one set of failures are due to https://github.com/dart-lang/sdk/issues/55212 that recently affected infra, another - due to https://github.com/dart-lang/sdk/issues/55212 which is caused test failures due to transition from PST to PDT.

**Comment by itsjustkevin** [comment]
Thanks @aam please go ahead and submit if that is the case.

**Comment by aam** [comment]
Submitted.

**Comment by itsjustkevin** [comment]
@FifoTheHein if you’re seeing an issue, please open a new one.  We do not review closed issues when triaging.

**Comment by helgoboss** [comment]
@FifoTheHein If you create a new issue, could you please post a link to it here? If this issue is really back (I hope not), I would like to subscribe to it ;) Thanks!
