### ISSUE TITLE
Cannot kill child process using 'dart run'

### ISSUE THREAD

**Issue by schultek** [dart-lang/sdk#55219]
It is impossible to properly kill a child process that is spawned through `Process.start('dart', ['run', ...`.

Any tries to kill the so created process will leave the child process running. See the following snippet:

```dart
// This file is 'runner.dart'
import 'dart:io';

void main(List<String> args) async {
  bool killed = false;
  ProcessSignal.sigterm.watch().listen((event) {
    print('[$pid] SIGTERM received.');
    killed = true;
  });

  if (args.firstOrNull == '--child') {
    int iter = 0;

    while (!killed) {
      print("[$pid] Child iteration: $iter");
      await Future.delayed(Duration(seconds: 1));
      iter++;
    }
    return;
  }

  print("[$pid] Starting child...");
  var p = await Process.start('dart', ['run', 'runner.dart', '--child']);
  p.stdout.pipe(stdout);
  p.stderr.pipe(stderr);
  print("[$pid] Started ${p.pid}.");

  await Future.delayed(Duration(seconds: 5));

  print("[$pid] Killing child...");
  p.kill();
  // These have the same outcome:
  // Process.killPid(p.pid);
  // Process.runSync('kill', ['${p.pid}']);
  print("[$pid] Killed.");
}
```

The output of running `dart run runner.dart' outputs:
```
[67301] Starting child...
[67301] Started 67302.
[67316] Child iteration: 0
[67316] Child iteration: 1
[67316] Child iteration: 2
[67316] Child iteration: 3
[67316] Child iteration: 4
[67301] Killing child...
[67301] Killed.
[67316] Child iteration: 5
[67316] Child iteration: 6
[67316] Child iteration: 7
[67316] Child iteration: 8
[67316] Child iteration: 9
```
where the child iterations continue forever (until manually killed).

Expected output would look like:
```
[67301] Starting child...
[67301] Started 67302.
[67316] Child iteration: 0
[67316] Child iteration: 1
[67316] Child iteration: 2
[67316] Child iteration: 3
[67316] Child iteration: 4
[67301] Killing child...
[67316] SIGTERM received
[67301] Killed.
```

It seems like the `dart run` command does not properly send through termination signals to its target process.

**Comment by bkonyi** [comment]
I have a feeling this isn't a problem specific to `dart run`, just how processes spawned via `dart:io` are handled. @schultek what platform are you running on? Would you mind providing the output of `dart info`?

**Comment by a-siva** [comment]
> cc @brianquinlan and @a-siva who probably have the most context on this behavior these days.

@bkonyi, I don't believe this is the same issue that we were discussing last week. The change to use external processes for the 'run' command has not landed yet.

**Comment by schultek** [comment]
> @schultek what platform are you running on? Would you mind providing the output of `dart info`?

#### General info

- Dart 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
- on macos / Version 14.1 (Build 23B74)
- locale is de-DE

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                               |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
| 5653 MB | 0.0% |     18:50:36 | dart language-server --client-id=IntelliJ-IDEA --client-version=IU-232.10203.10 --protocol=analyzer |
|   42 MB | 0.0% |     19:50:19 | dart run runner.dart                                                                       |
|   42 MB | 0.0% |     19:50:18 | dart run runner.dart --child                                                               |
|   42 MB | 0.0% |     19:46:52 | dart run runner.dart --child                                                               |
|   42 MB | 0.0% |     19:45:13 | dart run runner.dart --child                                                               |
|   64 MB | 0.0% |  02-20:32:32 | flutter_tools.snapshot daemon                                                              |

> I have a feeling this isn't a problem specific to dart run, just how processes spawned via dart:io are handled

I think it does. When I compile the programm to an executable and change the line to
```diff
- var p = await Process.start('dart', ['run', 'runner.dart', '--child']);
+ var p = await Process.start('./runner', ['--child']);
```
then it behaves as expected:

```
[82927] Starting child...
[82927] Started 82928.
[82928] Child iteration: 0
[82928] Child iteration: 1
[82928] Child iteration: 2
[82928] Child iteration: 3
[82928] Child iteration: 4
[82927] Killing child...
[82927] Killed.
[82928] SIGTERM received.
```

**Comment by a-siva** [comment]
I tried the example provided above on main branch of Dart 
(Dart SDK version: 3.4.0-edge.db1b6018caed19d10d81774278e6515162237dd9 (main) (Fri Mar 15 18:09:29 2024 +0000) on "macos_x64")

and I get the following output

```
asiva-macbookpro1:sdk asiva$ xcodebuild/ReleaseX64/dart-sdk/bin/dart /tmp/runner1.dart parent
[86893] Starting child...
[86893] Started 86906.
[86906] Child iteration: 0
[86906] Child iteration: 1
[86906] Child iteration: 2
[86906] Child iteration: 3
[86906] Child iteration: 4
[86893] Killing child...
[86893] Killed.
[86906] SIGTERM received.
```

The two process (parent and child) do not die as we have the watch signal watch method still watching for signals (both parent and child).

I changed the signal handler as follows
```
ProcessSignal.sigterm.watch().listen((event) {
    print('[$pid] SIGTERM received.');
    killed = true;
    exit(0);
  });
```
and the child process dies.

We don't have a way of explicitly cancelling the signal watching.

Re writing the code as follows makes it work
```
import 'dart:io';

void main(List<String> args) async {
  bool killed = false;

  if (args.firstOrNull == '--child') {
    int iter = 0;
    ProcessSignal.sigterm.watch().listen((event) {
      print('[$pid] SIGTERM received.');
      killed = true;
      exit(0);
    });

    while (!killed) {
      print("[$pid] Child iteration: $iter");
      await Future.delayed(Duration(seconds: 1));
      iter++;
    }
    return;
  }

  print("[$pid] Starting child...");
  var p = await Process.start(Platform.executable, ['run', '/tmp/runner1.dart', '--child']);
  p.stdout.pipe(stdout);
  p.stderr.pipe(stderr);
  print("[$pid] Started ${p.pid}.");

  await Future.delayed(Duration(seconds: 5));

  print("[$pid] Killing child...");
  p.kill();
  // These have the same outcome:
  // Process.killPid(p.pid);
  // Process.runSync('kill', ['${p.pid}']);
  print("[$pid] Killed.");
}

```

**Comment by a-siva** [comment]
@schultek I tried your example on the latest version of Dart and it appears to work, I made a slight modification to your code to cancel the subscription, see below
```
import 'dart:async';
import 'dart:io';

late StreamSubscription subscription;

main(List<String> args) async {
  bool killed = false;
  subscription = ProcessSignal.sigterm.watch().listen((event) {
    print('[$pid] SIGTERM received.');
    killed = true;
    print('[$pid] set killed to $killed');
    subscription.cancel();
  });

  if (args.first == '--child') {
    int iter = 0;

    while (!killed) {
      print("[$pid] Child iteration: $iter");
      await Future.delayed(Duration(seconds: 1));
      iter++;
    }
    return;
  }

  print("[$pid] Starting child...");
  var p = await Process.start(Platform.executable, ['run', '/usr/local/google/home/asiva/tmp/runner.dart
', '--child']);
  p.stdout.pipe(stdout);
  p.stderr.pipe(stderr);
  print("[$pid] Started ${p.pid}.");

  await Future.delayed(Duration(seconds: 5));

  print("[$pid] Killing child...");
  p.kill();
  print("[$pid] Killed.");
  subscription.cancel();
}

```

and it works as expected

```
[2176902] Starting child...
[2176902] Started 2176913.
[2176922] Child iteration: 0
[2176922] Child iteration: 1
[2176922] Child iteration: 2
[2176922] Child iteration: 3
[2176922] Child iteration: 4
[2176902] Killing child...
[2176902] Killed.
sigterm watcher called
```

Closing issue, if you think there is still an issue please reopen.
