### ISSUE TITLE
Is there any document about `ext.flutter.name` or `ext.flutter.inspector.name`?

### ISSUE THREAD

**Issue by takassh** [dart-lang/sdk#55214]
Hi, I'm looking into this document to make my Flutter inspector and vm client.
https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#private-rpcs-types-and-properties

It's well-organized document about public RPCs like `getVM` (thank you!) but I couldn't find `ext.flutter.name` or `ext.flutter.inspector.name` methods although they look no private method.
I have looked into Flutter repository but I only found https://github.com/flutter/flutter/blob/7c860ddf970575d4ca6dd0ccc4bd823613a16359/packages/flutter/lib/src/widgets/widget_inspector.dart#L843

If I missed anything, I'm sorry but do you have any public document about them? and If no, why?

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by a-siva** [comment]
//cc @kenzieschmoll could you reply to this question.

**Comment by a-siva** [comment]
@takassh I believe this is a Flutter issue, could you create a new issue for this under Flutter and close this.

**Comment by kenzieschmoll** [comment]
It looks like you are referring to service extensions. Service extensions can be registered on the vm service and then called from another client. The Flutter inspector registers several service extensions in the Flutter framework that can be called from another VM service client like Dart DevTools. If you'd like to discuss further, please file a Flutter issue and tag me or reach out on the #hackers-devtools discord channel and we can discuss there (https://discord.com/channels/608014603317936148/1106667330093723668). It would be helpful to understand further what exactly you are trying to do.
