### ISSUE TITLE
Exception: 'type 'Null' is not a subtype of type 'int' in type cast'

### ISSUE THREAD

**Issue by pri-ai** [dart-lang/sdk#55217]
![Screenshot (709)](https://github.com/dart-lang/sdk/assets/64066509/f5100473-3a1b-4420-add6-2fd0cdf282cb)

**Comment by pri-ai** [comment]
I'm trying to run my flutter web app but its not showing any devices. If I try to run any comments like flutter upgrade or flutter doctor its throwing this error. Any solution for this ?

**Comment by mraleph** [comment]
Duplicate of #55212
