### ISSUE TITLE
cannot run any flutter command 

### ISSUE THREAD

**Issue by upasana-khatiwada** [dart-lang/sdk#55212]
**Admin note**:

Developers who used the Flutter `main` channel last Friday, March 15th may see the following error due to https://github.com/dart-lang/tools/issues/252:

```
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:94:43)
```
From our understanding those that use only `stable` and `beta` channels were not affected.

The issue can be worked around by taking these steps:
   1. Locate the telemetry session file: `$HOME/.dart-tool/dart-flutter-telemetry-session.json`
   2. Delete this file (it will get re-created when you run `dart` or `flutter` again

-----------------

Original issue:

```
C:\Windows\System32>flutter doctor

Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:427:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:96:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#20     Future._completeError (dart:async/future_impl.dart:651:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5) 
```
yes i have checked environment variables
reinstall dart and flutter extension ,
dart version is:
```
C:\Windows\System32>dart --version
Dart SDK version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "windows_x64" 
```

i cannot run `flutter --version` as it shows same above error but its 3.19.3 Reinstall Flutter,Restart Command Prompt , restart vs code , restart computer everything 

please kindly help

**Comment by nielsenko** [comment]
Same here. Actually running dart will fail. I tried both flutter channel `stable`, `beta`, and `master`

**Comment by nielsenko** [comment]
Running `dart --disable-analytics` (with the `dart` from flutter master channel) will make everything work again.

**Comment by nielsenko** [comment]
If you can't be bothered to install _flutter master_ just to disable analytics, then you can instead edit `~/.dart-tool/dart-flutter-telemetry.config`
```diff
diff --git a/.dart-tool/dart-flutter-telemetry.config b/.dart-tool/dart-flutter-telemetry.config
index 795800f..2065c2d 100644
--- a/.dart-tool/dart-flutter-telemetry.config
+++ b/.dart-tool/dart-flutter-telemetry.config
@@ -15,7 +15,7 @@
 #
 # To disable telemetry reporting, set "reporting" to
 # the value "0" and to enable, set to "1":
-reporting=1
+reporting=0
```

**Comment by upasana-khatiwada** [comment]
PS C:\> flutter channel master


Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:427:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:96:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#20     Future._completeError (dart:async/future_impl.dart:651:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5) channel master is also not working for me 
i have completely removed and install flutter sdk and checked in environment variables any other requirement part this issue is not from my side

**Comment by rutvik110** [comment]
> Running `dart --disable-analytics` (with the `dart` from flutter master channel, since trying with `dart` from one of the other channels will fail immediately) will make everything work again - on all channels.

Facing the same issue on macOS on latest Flutter stable `v3.19.3`. Disabling analytics does resolves the issue.

**Comment by upasana-khatiwada** [comment]
But  for that i need to switch to flutter channel master but this command is not taken or any other flutter command is not taken 

PS C:\Users\upasa> flutter channel master


Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:427:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:96:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#20     Future._completeError (dart:async/future_impl.dart:651:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
PS C:\Users\upasa>  dart --disable-analytics
An unexpected error was encountered by the Dart CLI.
Please file an issue at https://github.com/dart-lang/sdk/issues/new with the following details:

Invocation: 'dart --disable-analytics'
Exception: 'type 'Null' is not a subtype of type 'int' in type cast'
Stack Trace:
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:427:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#5      createUnifiedAnalytics (package:dartdev/src/unified_analytics.dart:23:10)
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:182:27)
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#8      new Future.sync (dart:async/future.dart:305:31)
#9      CommandRunner.run (package:args/command_runner.dart:122:14)
#10     runDartdev (package:dartdev/dartdev.dart:57:29)
#11     main (file:///C:/b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:33)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by nielsenko** [comment]
@upasana-khatiwada The easiest way is just to edit `~/.dart-tool/dart-flutter-telemetry.config` so that `reporting=0`. That way you don't need to install `dart` from flutter channel master first.

**Comment by Sid1214** [comment]
@nielsenko where can I find this config file?

**Comment by mraleph** [comment]
We are experiencing some serious breakage with analytics. Can you take a look @eliasyishak?

This spread to our own checked in SDK and broke local builds as well. We might need to roll something back or land a hot fix _quickly_. 

cc @mit-mit @a-siva @bkonyi @athomas

**Comment by eliasyishak** [comment]
The changes to fix this issue are now at the tip of master for dart-lang/tools and should be rolling downstream.

The issue here is that we mistakingly removed a key from the json file we use for the package but have returned it in the latest version 5.8.8.

Deleting the json file should reset the state back to working if you can't wait for the downstream roll.

The file is located at $HOME/.dart-tool/dart-flutter-telemetry-session.json

**Comment by mit-mit** [comment]
Dart roll of the fix from /tools to SDK in https://dart-review.googlesource.com/c/sdk/+/358220

**Comment by alexmarkov** [comment]
Roll 87473f8e653f948430ccaf880a4e1e4f4d6a1953 doesn't fix the problem for me.
I still see this error when building Dart SDK locally at d243eb1254749fe67909a118c063449f9710872e:

```
Invocation: 'dart compile js -o gen/runtime/observatory/observatory/web/main.dart.js --packages=../../.dart_tool/package_config.json ../../runtime/observatory/web/main.dart --minify'
Exception: 'type 'Null' is not a subtype of type 'int' in type cast'
Stack Trace:
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:421:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#5      createUnifiedAnalytics (package:dartdev/src/unified_analytics.dart:23:10)
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:177:27)
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#8      new Future.sync (dart:async/future.dart:306:31)
#9      CommandRunner.run (package:args/command_runner.dart:122:14)
#10     runDartdev (package:dartdev/dartdev.dart:58:29)
#11     main (file:///b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:33)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

This error is issued by `dart` from checked-in Dart SDK version (3.4.0-108.0.dev).
Dart SDK builds on Golem bots are also affected.

**Comment by bkonyi** [comment]
I encountered the same thing. I think we need to get a new checked-in version of the Dart SDK with the roll to fix this issue.

**Comment by bkonyi** [comment]
I've got a CL here to update the pinned SDK to a dev build from this morning: https://dart-review.googlesource.com/c/sdk/+/358540. Not sure if there's a process to do this, but I just followed the README from `tools/sdks/`.

**Comment by mit-mit** [comment]
@eliasyishak @bkonyi anymore known work here, or can we resolve this?

**Comment by bkonyi** [comment]
I think this can probably be resolved. The fix has rolled into the SDK and the pinned SDK has been rolled so we're not seeing this error during builds anymore.

**Comment by mraleph** [comment]
I was under the impression that original reporters were Flutter developers? Should something be cherry-picked into the stable / beta to prevent breakages when developers jump between channels?

**Comment by mraleph** [comment]
@eliasyishak thanks for confirming!

**Comment by SaugatPoudell** [comment]
How did you guys solved  the above mentioned problem??
