### ISSUE TITLE
[dart2wasm] Debugging information for release builds (e.g. dwarf, source maps)

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55229]
For release builds we are stripping the static name section from the wasm by-default. For local debugging one can compile with name section included (e.g. `flutter build web --wasm --no-strip-wasm`) but apps are usually deployed without symbols to reduce the wasm file size.

This means stack traces at runtime are non-symbolic. There's several ways one could get symbolic stack traces:

* Make stripping the name section a separate pass, remember the mapping, provide offline decoding tool
* Emit source maps in the compiler, which binaryen preserves across optimizations
* Emit dwarf in the compiler, which binaryen may preserve to some extent

I stumbled upon this code in the binaryen sources in [pass.cpp](https://github.com/WebAssembly/binaryen/blob/c166ca015860b337e9ce07a5e02cb707964056ba/src/passes/pass.cpp#L562):
```c++
void PassRunner::addDefaultFunctionOptimizationPasses() {
  // All the additions here are optional if DWARF must be preserved. That is,
  // when DWARF is relevant we run fewer optimizations.
  // FIXME: support DWARF in all of them.
  ...
```

Because of that, I think we should avoid DWARF for the time being and instead emit source maps.

**Comment by osa1** [comment]
I started working on generating source maps.
