### ISSUE TITLE
pkg/front_end/tool/fasta hardcodes ReleaseX64

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#55237]
Dart version: `Dart SDK version: 3.4.0-edge.02948896f64fc38a349ca4138020bf2354de8fa6 (main) (Mon Mar 18 13:56:38 2024 -0700) on "macos_arm64"`

`pkg/front_end/tool/fasta` explicitly sets `DART_CONFIGURATION` to [`ReleaseX64`](https://github.com/dart-lang/sdk/blob/408918d6f5e28250cb48f50bd2b444bcc2f7982f/pkg/front_end/tool/fasta#L24). Since I'm on an `ARM64` laptop, this results in errors when looking up the Dart binary:

```
/Users/srujzs/dart-sdk/sdk/sdk/bin/dart: line 56: /Users/srujzs/dart-sdk/sdk/sdk/bin/../../xcodebuild/ReleaseX64/dart: No such file or directory
/Users/srujzs/dart-sdk/sdk/sdk/bin/dart: line 56: exec: /Users/srujzs/dart-sdk/sdk/sdk/bin/../../xcodebuild/ReleaseX64/dart: cannot execute: No such file or directory
```

Commenting this line out seems to suffice as the `sdk/bin/dart` script seems to do the lookup [itself](https://github.com/dart-lang/sdk/blob/408918d6f5e28250cb48f50bd2b444bcc2f7982f/sdk/bin/dart#L31).

**Comment by johnniwinther** [comment]
cc @jensjoha
