### ISSUE TITLE
Record types rejected as errors in constant initializer list

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#55247]
Consider the following program:

```dart
class A {
  final bool b;
  const A(r) : b = r is (int,) ? true : true; // Error.
}

const c1 = () is (int,); // OK.

typedef Id<X> = X;
const c2 = Id<(int,)>;

void main() {}
```

This program is accepted and executed with no errors by `dart`, but the analyzer rejects it as follows:

```
Invalid const value
```

which is reported at `(int,)`, and the behavior is the same if we replace `(int,)` by a different record type, e.g., `(int, int)`.

This is not an error, and it is indeed not reported for several other occurrences of `(int,)` as a type in a constant expression.

Hence, it looks like the analyzer emits a spurious error message in the combination of circumstances shown in the `A` constructor.

[Edit: I did not need the assert after all, changed the title accordingly.]

**Comment by pq** [comment]
@scheglov
