### ISSUE TITLE
[CP] Fix DateTime.timeZoneName on Windows

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#55240]
### Commit(s) to merge

b0236fdde5eec3adb60db672d82c089bae6af780

### Target

beta and stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/358420
https://dart-review.googlesource.com/c/sdk/+/358440

### Issue Description

`DateTime.timeZoneName` returns incorrect value on Windows when the machine is in the summer time but the given moment is in the standard time and vice versa.

### What is the fix

Fix the implementation of the function to use the given moment rather then to look at the current time zone.

### Why cherry-pick

There is a test failing on stable and beta branches - which makes other cherry picks harder.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55159

### Extra Info

/cc @a-siva

**Comment by mit-mit** [comment]
LGTM
