### ISSUE TITLE
Suggestion variable name for DeclaredVariablePattern

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#55251]
```dart
class MyValue {}

void f(Object? x) {
  switch (x) {
    case MyValue ^
  }
}
```
I want to get `value` and `myValue` suggestions.

**Comment by NBCBM** [comment]
class MyValue {}

void f(Object? x) {
  switch (x) {
    case MyValue:
      // Here, x is guaranteed to be an instance of MyValue
      // You can access and use MyValue-specific properties or methods here.
      break;
    default:
      // Handle other cases if needed
  }
}

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/360200
