### ISSUE TITLE
[breaking change] Change return type of isTruthy and not

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#55267]
Some more context here: https://github.com/dart-lang/sdk/issues/55238. This is the "reverse" of that change - move all operators to use JS types instead of returning Dart types.

### Intended Change

`dart:js_interop`'s `isTruthy` and `not` should now return a `JSBoolean` instead of a `bool`.

`dart:js_interop` exposes [`isTruthy`](https://api.dart.dev/dev/3.4.0-250.0.dev/dart-js_interop/JSAnyOperatorExtension/isTruthy.html) and [`not`](https://api.dart.dev/dev/3.4.0-250.0.dev/dart-js_interop/JSAnyOperatorExtension/not.html) operators to be consistent with `dart:js_util` API. They currently return a `bool`, as the result is always a boolean JS value.

### Justification

JS operator utility members should use JS types instead of their Dart equivalents for performance. They are likely to be used when the conversion is deemed costly (otherwise, users could just convert to the Dart value and use Dart operators) and they are likely to be composed on one other e.g. `b1.and(b2.or(b3))`. In the case of composition, this adds several additional unneeded conversions.

### Impact

Minimal. There are no usages in google3, in Flutter, in the SDK, or on GitHub.

### Mitigation

Convert the resulting `JSBoolean` to a `boolean` with `toDart`:

```dart
bool b1 = true.toJS.not;
bool b2 = true.toJS.isTruthy;
```

```dart
bool b1 = true.toJS.not.toDart;
bool b2 = true.toJS.isTruthy.toDart;
```

cc @sigmundch

**Comment by sigmundch** [comment]
LGTM :+1:, this would bring all operators to have a consistent API: all other operators today return a JS type, this would make the `dart:js_interop` library homogeneous.

cc @lrhn @kevmoo 

cc @itsjustkevin - for the breaking change process

---

In terms of timing, I'm open to either having this in 3.4 or 3.5, given the cutoff date, I'm fine waiting until 3.5. Usage is low enough that we don't expect much impact later either, but we may want to suggest a backward compatible way to write code if we don't release it in 3.4. For example:

```dart
bool isReallyTruthy(JSAny a) {
  Object o = a.isThruthy;
  return o is bool ? o : (o as JSBoolean).toDart;
}
```

**Comment by itsjustkevin** [comment]
@vsmenon @Hixie @grouma for review.

**Comment by grouma** [comment]
SGTM.

**Comment by itsjustkevin** [comment]
Pinging @vsmenon and @Hixie

**Comment by itsjustkevin** [comment]
CC: @leonsenft

**Comment by Hixie** [comment]
no objection; seems reasonable but i don't have enough context to fully evaluate.

**Comment by vsmenon** [comment]
lgtm

**Comment by itsjustkevin** [comment]
Breaking change approved
