### ISSUE TITLE
Remove `dart:js` from dart2wasm

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#55266]
This library was added to support `allowInterop`. All of the methods throw and importing `dart:js` returns a static error. However, doing conditional imports e.g. `if (dart.library.js)` succeeds in dart2wasm, because the library still exists in libraries.json. Since `allowInterop` is now no longer defined in `dart:js`, we should just remove this library altogether from the platform.

**Comment by srujzs** [comment]
There's already a static error we've added to disallow importing `dart:js` in dart2wasm: https://github.com/dart-lang/sdk/blob/2250404330cb0483f7650fee55b95c8a29030616/pkg/_js_interop_checks/lib/js_interop_checks.dart#L541.

**Comment by osa1** [comment]
Do we need to make any changes in Flutter for this? I've created an SDK CL to remove `dart:js` from the platform: https://dart-review.googlesource.com/c/sdk/+/368642.

**Comment by mkustermann** [comment]
> Do we need to make any changes in Flutter for this? I've created an SDK CL to remove dart:js from the platform: https://dart-review.googlesource.com/c/sdk/+/368642.

Maybe this issue also includes `dart:js_util` (which we currently use internally in the implementation of `dart:js_interop`)

**Comment by srujzs** [comment]
I don't think Flutter uses `dart:js` anywhere. I'm not sure why your CL results in `package:js` complaining about exporting `dart:_js_annotations` now. That should be tangential but I'll have to take a deeper look.

> Maybe this issue also includes dart:js_util (which we currently use internally in the implementation of dart:js_interop)

There are a few migrations that need to happen in Flutter and elsewhere (as well as migrating our own implementation of `dart:js_interop` like you note) before `package:js` and `dart:js_util` can be removed from dart2wasm. I'd expect it to be harder than removing `dart:js`.

**Comment by osa1** [comment]
@sigmundch I don't remember what the problem was. I think I was busy with other things and didn't want to spent too much time on this at the time and stopped after seeing the test failures.

**Comment by simolus3** [comment]
Some Dart programs rely on detecting the compiler in conditional imports (to e.g. switch implementations depending on whether we have 64bit ints).
Dropping `dart:js` support from `dart2wasm` gives us a way to uniquely identify DDC and dart2js by checking for `dart.library.js`, which is great.

However, the 3.5 release announcement also described plans to eventually discontinue all of the SDK web bindings (including `dart:js`) in favor of `package:web` and `dart:js_interop`. I'm worried that this will bring back the problem of not being able to identify dart2wasm in conditional imports - will this be considered or is there a proper way to set up conditional imports now that avoids this future problem?

**Comment by mkustermann** [comment]
> Some Dart programs rely on detecting the compiler in conditional imports (to e.g. switch implementations depending on whether we have 64bit ints).
> Dropping dart:js support from dart2wasm gives us a way to uniquely identify DDC and dart2js by checking for dart.library.js, which is great.
>
> However, the 3.5 release announcement also described plans to eventually discontinue all of the legacy SDK web bindings (including dart:js) in favor of package:web and dart:js_interop. I'm worried that this will bring back the problem of not being able to identify dart2wasm in conditional imports - will this be considered or is there a proper way to set up conditional imports now that avoids this future problem?

/cc @dart-lang/language-team Maybe it's time to allow more than `dart.library.*` in conditional imports ( https://github.com/dart-lang/sdk/issues/54785)?

**Comment by sigmundch** [comment]
Good observation @simolus3, indeed!

@mkustermann - I agree, I made a similar suggestion in https://github.com/dart-lang/crypto/issues/180#issuecomment-2289802897 :smile: - We need to start using tests that directly correspond to what developers want to know. For example, if you want to condition on a platform, then use a variable that describes the platform, like `dart.tool.dart2wasm`, rather than an indirect observation, like whether a library is available.

**Comment by natebosch** [comment]
IIRC the bazel support is implemented as a fixed list of platforms and what variables they correspond to, so adding variables like `dart.tool.dart2wasm` might be aligned. Whatever we do with configurable imports we should plan to get input about the bazel implementation.
