### ISSUE TITLE
Inferring type parameters from function signatures seems broken

### ISSUE THREAD

**Issue by skylon07** [dart-lang/sdk#55278]
## Issue

To preface my issue, I am not sure if this is expected behavior or not. With that being said, I'll take you through what I think is a problem and why I think it is one.

### TL;DR

`doSpecific_BAD()` should throw an error like `handleDoerSpecific_GOOD()`.

```dart 
void doThing<DoerT extends ThingDoer>(
  Object maybeDoer,
  void Function(DoerT) doImpl,
) {
  switch (maybeDoer) {
    case DoerT(): return doImpl(maybeDoer);
    default: throw ArgumentError("argument not a $DoerT, was ${maybeDoer.runtimeType}");
  }
}

void doSpecific_BAD(Object maybeDoer) {
  // does not throw compilation error -- this is unexpected...?
  // expected something like "`void Function(int)` can't be a `void Function(DoerT)`"
  doThing(maybeDoer, (int doer) {});
}


void handleDoer<DoerT extends ThingDoer>(DoerT maybeDoer) {
  return;
}

void handleDoerSpecific_GOOD(Object maybeDoer) {
  // throws compilation error, despite its similarities to `doSpecific_BAD()`
  handleDoer(maybeDoer);
}


sealed class ThingDoer {}
final class MyDoer1 extends ThingDoer {}
final class MyDoer2 extends ThingDoer {}
```

#### Note: This is a bit long -- no need to read it if you already agree with the TL;DR

I wrote a program which effectively reduced to this:

```dart
void doThing<DoerT extends ThingDoer>(
  Object maybeDoer,
  void Function(DoerT) doImpl,
) {
  switch (maybeDoer) {
    case DoerT(): return doImpl(maybeDoer);
    default: throw ArgumentError("argument not a $DoerT, was ${maybeDoer.runtimeType}");
  }
}

void doSpecific(Object maybeDoer) {
  // oops, accidentally wrote the wrong parameter type!
  doThing(maybeDoer, (int doer) {}); 
}

sealed class ThingDoer {}
final class MyDoer1 extends ThingDoer {}
final class MyDoer2 extends ThingDoer {}
```

I had accidentally wrote the wrong type in my `doImpl()`! (In this case, `int`, instead of something else). I noticed this error as I was working on the body of the function (properties on `doer` were missing that I expected to be there), however once I realized my error, I was surprised that the compiler didn't tell me this beforehand when I had initially wrote out the function parameters. I did some experimenting and realized it had something to do with inferring the type parameter `DoerT`:

```dart
void doThing<DoerT extends ThingDoer>(
  Object maybeDoer,
  void Function(DoerT) doImpl,
) {
  switch (maybeDoer) {
    case DoerT(): return doImpl(maybeDoer);
    default: throw ArgumentError("argument not a $DoerT, was ${maybeDoer.runtimeType}");
  }
}

void doSpecific_GOOD<DoerT extends ThingDoer>(Object maybeDoer) {
  // throws compilation error -- as expected
  doThing<DoerT>(maybeDoer, (int doer) {});
}

void doSpecific_BAD(Object maybeDoer) {
  // does not throw compilation error -- this is unexpected...?
  // expected something like "`void Function(int)` can't be a `void Function(DoerT)`"
  doThing(maybeDoer, (int doer) {});
}
```

If I actually try to run `doSpecific_BAD()`, I get this error (from `doThing()`):

```
Unhandled exception:
Invalid argument(s): argument not a Never, was MyDoer1
#0      doThing (file:///...test.dart:94:14)
#1      doSpecific_BAD (file:///...test.dart:105:3)
#2      main (file:///...test.dart:131:3)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

So... it inferred `DoerT` as `Never` in my case. This does make sense, I guess, since `doThing()` will always throw an exception if `DoerT` is `int` -- the problem is, the phrase `doThing<DoerT extends ThingDoer>` should *guarantee* that `DoerT` is not ever `int` (or anything else not a `ThingDoer`), right? For example, this situation is similar to `doSpecific_BAD()`, but it does throw a useful compilation error:

```dart
void handleDoer<DoerT extends ThingDoer>(DoerT maybeDoer) {
  return;
}

void handleDoerSpecific_GOOD(Object maybeDoer) {
  // throws compilation error, despite its similarities to `doSpecific_BAD()`
  handleDoer(maybeDoer);
}
```

The error being:

```
Couldn't infer type parameter 'DoerT'.

Tried to infer 'Object' for 'DoerT' which doesn't work:
  Type parameter 'DoerT' is declared to extend 'ThingDoer' producing 'ThingDoer'.
The type 'Object' was inferred from:
  Parameter 'maybeDoer' declared as     'DoerT'
                        but argument is 'Object'.

Consider passing explicit type argument(s) to the generic.
```

So to wrap it all up, what I think is that `doSpecific_BAD()` should not compile, producing an error similar to that of `handleDoerSpecific_GOOD()`. Sorry if this was a little long -- I did warn you!

## Info

Results of `dart info`:

#### General info

- Dart 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "macos_arm64"
- on macos / Version 14.0 (Build 23A344)
- locale is en-US

#### Project info

- sdk constraint: '^3.1.0'
- dependencies: 
- dev_dependencies: test

[dartpad.dev](http://dartpad.dev) version (as of posting):

Dart 3.3.0

**Comment by lrhn** [comment]
The bound does guarantee the `DoerT` is never `int`, and it isn't. It's `Never`, which is a subtype of the bound.

The constraints inferred by type inference are `DoerT <: ThingDoer` and `DoerT <: int`, and it solves successfully for that.

Your problem is that the only occurrence of the type parameter is contravariant. That introduces another upper bound, just like the type parameter bound, but you have no lower bound, so `Never` is always a valid solution.

**Comment by skylon07** [comment]
If I'm understanding you correctly, you're saying `DoerT` is inferred as `Never` because that's the only type that is a subtype of both `ThingDoer` and `int` is `Never`, effectively resulting in
```dart
void doThing(
  Object maybeDoer,
  void Function(Never) doImpl,
) {
  switch (maybeDoer) {
    case Never(): return doImpl(maybeDoer);
    default: throw ArgumentError("argument not a $DoerT, was ${maybeDoer.runtimeType}");
  }
}
```

That makes sense to me, at least from the standpoint of "what should `DoerT` be?".

> the phrase `doThing<DoerT extends ThingDoer>` should *guarantee* that `DoerT` is not ever `int` (or anything else not a `ThingDoer`), right?

I guess I was wrong suggesting that this guarantee wasn't  there. You're right, `DoerT` is never assigned the type `int` in my case. However I'm still hung up on why this would be allowed, but something like my `handleDoerSpecific_GOOD()` example is rejected.

...

Scratch that, after more experimenting I realized what's going on. I think I just misunderstood how the type inference system was coming up with its answers. Thinking about it in terms of the upper bounds you had mentioned makes sense why it would infer `Never` in this case, and why the program would still compile/run totally fine despite this (well, if it weren't for the fact I throw an error right after checking, heh). Because `maybeDoer` is "never" an `int`, `DoerT` becomes `Never`. This is probably just a case where if I want `doSpecific_BAD()` to not compile, I should just pass the type argument explicitly.

Sorry for bugging you with all of this -- I'm still somewhat new to the idea of covariance/contravariance (and how the compiler should/does handle that).

**Comment by lrhn** [comment]
There was a reason the orginal design of Dart chose all type parameters to be covariant. Most people can't wrap their head around contravariance in general. Almost nobody can do it correctly all the time, even when they know all there is to know about it. It's just ... contra-logical! :sunglasses:
