### ISSUE TITLE
[dart2wasm] Add the name of named functions in local scope to the name section

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#55279]
Some framework test in flutter introspect the call stack in debug mode. However, even at the lowest optimization level, `dart2wasm` inlines functions fairly aggressively. Even using the `--no-inlining` flag doesn't really prevent much, because it seems like the TFA is already doing a bunch of inlining as well. I think for debug purposes, it might make sense to have a mode for dart2wasm that just skips the TFA altogether, so that we can keep more expressive call stacks and 1:1 relationships with functions in actual code.

**Comment by osa1** [comment]
> because it seems like the TFA is already doing a bunch of inlining as well

I asked this to @alexmarkov and he says TFA doesn't do inlining.

> Even using the --no-inlining flag doesn't really prevent much

I suspect one or both of these are happening:

- The flag is not properly propagated to wasm-opt, either by `dart compile wasm` command, or if Flutter still runs wasm-opt itself, by `flutter`.

- The inlinings you see are in the platform file, which is compiled with inlinings + other optimizations separately.

**Comment by eyebrowsoffire** [comment]
I looked a little deeper into this, and I am mistaken, the function is not being inlined, but it is a named locally scoped function and its name is not being added to the name section, so it does not appear in the stacktrace. The framework test in question looks something like this:

```
  testWidgets(
    'Ticker control test', (WidgetTester tester) async {
    late Ticker ticker;
    addTearDown(() => ticker.dispose());

    void testFunction() {
      ticker = Ticker((Duration _) { });
    }

    testFunction();

    expect(ticker, hasOneLineDescription);
    expect(ticker.toString(debugIncludeStack: true), contains('testFunction'));
  });
```

The stack that is recorded by the Ticker has this in the stack frame where the `testFunction` should be:

```
at main closure at org-dartlang-app:///scheduler/ticker_test.dart:110:22 (http://localhost:50821/scheduler/main.dart.wasm:wasm-function[7646]:0x15c128)
```

So I think maybe the bug here is that if we have a named function in the local scope, we should try to put that name in the name section.
