### ISSUE TITLE
Extension type doesn't extend `Object`

### ISSUE THREAD

**Issue by Tienisto** [dart-lang/sdk#55288]
I have the following extension type:

```dart
extension type Instant(int millisSinceEpoch) {
  static Instant ofDateTime(DateTime dateTime) => Instant(dateTime.millisecondsSinceEpoch);

  operator <(Instant other) => millisSinceEpoch < other.millisSinceEpoch;
}
```

Now I want to use it in [dart_mappable](https://pub.dev/packages/dart_mappable):

```dart
class InstantMapper extends SimpleMapper<Instant> {
  const InstantMapper();

  @override
  Instant decode(dynamic value) {
    return Instant.ofDateTime(DateTime.parse(value as String));
  }

  @override
  dynamic encode(Instant self) {
    return DateTime.fromMillisecondsSinceEpoch(self.millisSinceEpoch).toIso8601String();
  }
}
```

However, it doesn't compile because the `SimpleMapper` requires `SimpleMapper<T extends Object>`:

```text
Error: Type argument 'Instant' doesn't conform to the bound 'Object' of the type variable 'T' on 'SimpleMapper'.
```

It seems that my new type `Instant` is not an `Object` but shouldn't it be?

If this is intended, then what is the alternative to express `<T extends Object>` which is "any type but not null"?

**Comment by blaugold** [comment]
You can make an extension type implement a type that is implemented by the wrapped type, so in this case: 

```dart
extension type Instant(int millisSinceEpoch) implements Object {
  ...
}
```

**Comment by Tienisto** [comment]
Thank you! This indeed solved the problem!
