### ISSUE TITLE
Add a unified analytics API to DTD

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#55280]
This API should allow a client to get the status of analytics opt in / opt out, get the consent message, and send events.

DevTools, IntelliJ and VS Code can all use this API by proxy of DTD.

**Comment by srawlins** [comment]
What is a DTD? I need to triage this to some area.

**Comment by a-siva** [comment]
DTD is Dart tooling daemon [ DTD doc](https://docs.google.com/document/d/1qJNwgg1e_4KzY_fSU3rmSj9CXqtpGC5GmQb0cXkUGfo/edit?tab=t.0)

I am triaging it to the tools area.
