### ISSUE TITLE
Inconsistent behavior of `if case` pattern with type promotion in Dart when compiling to JavaScript vs Native

### ISSUE THREAD

**Issue by leynier** [dart-lang/sdk#55309]
I've encountered an inconsistency in the behavior of the `if case` pattern with type promotion in Dart, depending on the compilation target (JavaScript vs Native). Specifically, when using the same identifier for the promoted variable in the pattern of an `if case` statement, the condition evaluates to true when compiled to native but does not evaluate when compiled to JavaScript.

The issue can be demonstrated with the following Dart code:

```dart
void main() {
  f1('es');
  f2('es');
}

void f1(String? language) {
  if (language case String l) {
    print('f1: ${l.length}');
  }
}

void f2(String? language) {
  if (language case String language) {
    print('f2: ${language.length}');
  }
}
```

When compiled to native, the output is as expected:

```
f1: 2
f2: 2
```

However, when compiled to JavaScript, the output is different:

```
f1: 2
```

This discrepancy suggests a potential issue with the type promotion or pattern matching implementation when compiling to JavaScript. Notably, the same behavior is observed with Flutter, showing the same inconsistency between compiling to native and compiling to the web.

**Screenshots:**
1. DartPad (compiling to JS)

![telegram-cloud-photo-size-1-4906771987473476679-y](https://github.com/dart-lang/sdk/assets/36774373/a434bcda-7d68-4db1-af9a-f4cc89618957)

2. VSCode (compiling to Native)

![telegram-cloud-photo-size-1-4909023787287162731-y](https://github.com/dart-lang/sdk/assets/36774373/79374291-154d-4b75-b818-d32c1f03f942)

Additionally, I have verified that this behavior persists across different environments, indicating a broader issue with the Dart compiler or runtime when targeting JavaScript.

I believe this inconsistency could impact developers working on cross-platform Dart or Flutter projects, especially those relying on type promotion within conditional patterns. Any insights or fixes for this discrepancy would be greatly appreciated.

**Comment by eernstg** [comment]
This seems to have been corrected recently: As you mention, `dart` on the command line does not have the issue. However, DartPad using the 'main' or 'beta' channels also do not have the issue.

I believe this could be the issue which was handled here: https://github.com/dart-lang/sdk/issues/54559.

I'll close the issue based on the assumption that the fix is already in the pipeline.

@sigmundch, do you agree?

**Comment by eernstg** [comment]
Looking at #54559, this seems to have been a CFE issue. @johnniwinther, do you have further comments?

**Comment by sigmundch** [comment]
Yes, I agree. Thanks @eernstg, indeed the latest dart2js and ddc are producing the same result as the native behavior in the VM.
