### ISSUE TITLE
RegExp breaks when passing parenthesis `()`

### ISSUE THREAD

**Issue by petermusembi69** [dart-lang/sdk#55308]
While creating a regex expression, having parenthesis, introduces bugs. This happens when creating RegExp matching string variables. 

```dart
//Example without parenthesis
void main() {
    var expression = 'CostUSD';
    print(expression);
    final fieldName = RegExp(r'' + expression);
    print(fieldName);
    expression = expression.replaceAll(fieldName, 'riri');
    print(expression);
}
```
![image](https://github.com/dart-lang/sdk/assets/29660093/f8306126-db72-44ce-8f76-b0e87f18dc47)

```dart
//Example with a complete pair of parenthesis
void main() {
    var expression = 'Cost(USD)';
    print(expression);
    final fieldName = RegExp(r'' + expression);
    print(fieldName);
    expression = expression.replaceAll(fieldName, 'riri');
    print(expression);
}
```
![image](https://github.com/dart-lang/sdk/assets/29660093/d277b31e-5e64-42ff-b908-ed9a00f93bf1)

```dart
//Example with a single parenthesis
void main() {
    var expression = 'Cost(USD';
    print(expression);
    final fieldName = RegExp(r'' + expression);
    print(fieldName);
    expression = expression.replaceAll(fieldName, 'riri');
    print(expression);
}
```
![image](https://github.com/dart-lang/sdk/assets/29660093/f7352e15-9b5f-4eeb-baba-8bde56ed5d97)

**Comment by julemand101** [comment]
If you are building your regular expression from pieces of (user) data then it is very much recommended to use `RegExp.escape` to escape the input to ensure this kind of issue does not happen. So your last example could be fixed by doing:
```dart
//Example with a single parenthesis
void main() {
  var expression = 'Cost(USD';
  print(expression);
  final fieldName = RegExp(r'' + RegExp.escape(expression));
  print(fieldName);
  expression = expression.replaceAll(fieldName, 'riri');
  print(expression);
}
```
Which makes it return:
```
Cost(USD
RegExp: pattern=Cost\(USD flags=
riri
```

**Comment by petermusembi69** [comment]
Aha I see, I missed this on the doc, thanks @julemand101
