### ISSUE TITLE
Analyzer incorrectly allows nullable receiver when extension type is involved

### ISSUE THREAD

**Issue by dgreensp** [dart-lang/sdk#55306]
Dart version: 3.3.2

The analyzer (as seen in DartPad or VS Code) does not seem to consider it an error to call methods on `Foo?` if `Foo` is an extension type, even though this is a compile-time error when compiling.

Here is a simple example:

```dart
extension type Foo(int _) {
  void bar() {}
}

void run(Foo? f) {
  f.bar(); // is a compile-time error, but not an analyzer error
}
```

I came across this issue when writing this code against `package:web`:

```dart
final body = document.body; // analyzes as HTMLElement?, correctly
body.appendChild(HTMLDivElement()); // no error in IDE, only when compiling
```

The fact that this is a bug is supported by [this comment](https://github.com/dart-lang/sdk/issues/53822#issuecomment-1775799877) on #53822, which is an issue about something slightly different, but it says that this code should have an error because, regardless of the representation of E, `E?` is a nullable (and therefore bad) receiver:

```dart
extension type E(int it) {
  E operator +(E other) => E(it + other.it);
}

void main() {
  E? e;
  print(e + E(1)); // Error: `e` can be null.
}
```

**Comment by dgreensp** [comment]
This is already fixed on main channel, as hypothesized on Discord and confirmed on DartPad.

**Comment by parlough** [comment]
Thanks for the issue and the conclusion :)

For reference: https://github.com/dart-lang/sdk/commit/421ffd331a1262e0bd23ea69298c3cd52718c04f likely fixed this
