### ISSUE TITLE
"Invalid argument(s):: InterfaceType(s) can only be created for declarations" when using augmentations

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#55312]
Given the following code:

```dart
class A {
   void foo() {}
}

augment class A {
  augment void foo() {}
}
```

Putting the caret in `foo()` for the augmentation triggers a `textDocument/codeAction` request which fails with the following:

```
1711537670051:Ex:An error occurred while handling textDocument/codeAction request
Invalid argument(s):: InterfaceType(s) can only be created for declarations
#0      new InterfaceTypeImpl (package::analyzer/src/dart/element/type.dart::479::7)
#1      InterfaceElementImpl.instantiate (package::analyzer/src/dart/element/element.dart::3650::20)
#2      InterfaceElementImpl.thisType (package::analyzer/src/dart/element/element.dart::3575::26)
#3      AddDiagnosticPropertyReference.compute (package::analysis_server/src/services/correction/dart/add_diagnostic_property_reference.dart::48::69)
#4      AssistProcessor._addFromProducers.compute (package::analysis_server/src/services/correction/assist_internal.dart::210::24)
#5      AssistProcessor._addFromProducers (package::analysis_server/src/services/correction/assist_internal.dart::230::15)
#6      AssistProcessor.compute (package::analysis_server/src/services/correction/assist_internal.dart::179::11)
#7      DartCodeActionsProducer.getAssistActions (package::analysis_server/src/lsp/handlers/code_actions/dart.dart::133::39)
<asynchronous suspension>
#8      OperationPerformanceImpl.runAsync (package::analyzer/src/util/performance/operation_performance.dart::172::14)
<asynchronous suspension>
#9      CodeActionHandler.handle (package::analysis_server/src/lsp/handlers/handler_code_actions.dart::235::16)
<asynchronous suspension>
#10     ServerStateMessageHandler.handleMessage (package::analysis_server/src/lsp/handlers/handlers.dart::396::11)
<asynchronous suspension>
#11     LspAnalysisServer._handleRequestMessage (package::analysis_server/src/lsp/lsp_analysis_server.dart::1001::20)
<asynchronous suspension>
#12     LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package::analysis_server/src/lsp/lsp_analysis_server.dart::461::15)
<asynchronous suspension>
#13     OperationPerformanceImpl.runAsync (package::analyzer/src/util/performance/operation_performance.dart::172::14)
<asynchronous suspension>
#14     LspAnalysisServer.handleMessage.<anonymous closure> (package::analysis_server/src/lsp/lsp_analysis_server.dart::444::11)
<asynchronous suspension>

:null
```

**Comment by DanTup** [comment]
This fails here:

```dart
final classDeclaration = node.thisOrAncestorOfType<ClassDeclaration>();
if (classDeclaration == null ||
    !Flutter.isDiagnosticable(classDeclaration.declaredElement!.thisType)) {
  return;
}
```

@scheglov I was going to look at this, but it's not clear to me what the fix is here (both whether this fix should be trying to do anything here, and whether `thisType` on a class augmentation in general should fail in this way).

**Comment by scheglov** [comment]
You cannot ask an augmentation for its `thisType`, you should only ask the declaration. If we have distinction between in form of separate `ClassElement` and `ClassAugmentationElement`, it would be shown by types. But we eventually decided to check `ClassElement.isAugmentation` instead.

**Comment by DanTup** [comment]
> You cannot ask an augmentation for its `thisType`

Out of interest, why is this? (As I understand, `this` is valid inside a class member augmentation?).

I wonder how much code might be doing something like the above and assuming it can get to `thisType`. Could the `thisType` getter be nullable if it's not always available? It feels awkward to have to check another property (`isAugmentation`) before calling this getter because it throws rather than returning `null`.

(I'll fix up this assist, but I worry this might not be the only place this shows up)

**Comment by DanTup** [comment]
A possible fix (with some questions): https://dart-review.googlesource.com/c/sdk/+/360043

**Comment by bwilkerson** [comment]
> You cannot ask an augmentation for its `thisType`

I have the same question. The documentation for the getter is

> The type of `this` expression.

It seems like the getter ought to return the type of `this` for any element where it's valid to use `this` in an instance member, including augmentations of such elements.

**Comment by DanTup** [comment]
Friendly ping - the CL https://dart-review.googlesource.com/c/sdk/+/360043 to stop this exception is unreviewed.

I'm also still curious about the question above.. I think if `thisType` worked, the assist might add code to the wrong place (the original declaration and not where the new field was added), though I don't know if that's the reason. (If it must be this way, I also wonder why throw at runtime instead of making it nullable and force code to deal with this case).

**Comment by bwilkerson** [comment]
Sorry for the incomplete response above ("the getter is" what?), and for the delay in getting back to you. I wanted to resolve the question above before deciding on the CL.

> You cannot ask an augmentation for its `thisType`
>
> Out of interest, why is this?

Konstantin and I spoke off-line and I believe that it came down to a difference in our design perspectives. I believe we agreed that `thisType` should always return the type that `this` has in the instance members of the enclosing container (class, enum, mixin, etc., including augmentations).

> I think if `thisType` worked, the assist might add code to the wrong place (the original declaration and not where the new field was added), though I don't know if that's the reason.

That isn't the reason, but I agree that the code would probably produce the wrong result. The right behavior, IMO, is for the fix to add an extension on the method if it's already declared in the base class (and to either add the method to the class augmentation or to add it to the base class and then augment it, I'm not sure which).

I'm ok with your CL to temporarily disable the fix and prevent the exception, but we should open another issue (or repurpose this one) to keep track of the need to extend the fix.

**Comment by DanTup** [comment]
> Konstantin and I spoke off-line and I believe that it came down to a difference in our design perspectives. I believe we agreed that `thisType` should always return the type that `this` has in the instance members of the enclosing container (class, enum, mixin, etc., including augmentations).

sgtm, thanks :)


> I'm ok with your CL to temporarily disable the fix and prevent the exception, but we should open another issue (or repurpose this one) to keep track of the need to extend the fix.

Agreed - I opened https://github.com/dart-lang/sdk/issues/55326 for that (and I'm interested in trying to implement that to improve my understanding of these AST classes, though I haven't look at it yet).
