### ISSUE TITLE
[dart2wasm] Include the text of the condition when throwing an assertion

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#55317]
When dart2wasm throws an assertion, it just throws "assertion failed" but does not include the text of the condition like other backends do. We should do this, some flutter framework tests rely on it.

**Comment by eyebrowsoffire** [comment]
I have a fix out for review: https://dart-review.googlesource.com/c/sdk/+/360460

**Comment by rakudrama** [comment]
FWIW, dart2js does not include the file / line / condition.
@eyebrowsoffire are these flutter framework tests never run on dart2js?

**Comment by eyebrowsoffire** [comment]
@rakudrama That is correct, they are only compiled via DDC (and now dart2wasm).
