### ISSUE TITLE
Null checks not narrowing types for instance variables

### ISSUE THREAD

**Issue by alexandradeas** [dart-lang/sdk#55323]
Null checks appear to not be coercing the type for instance variables. With the following code the expectation is `Foo.doesNotWork` will compile due to the `x != null` check 

```dart
int works({required List<String> xs, String? x}) {
  return x != null ? xs.indexOf(x) : 0; // no error
}

class Foo {
  const Foo({
    required this.xs,
    this.x,
  });

  final List<String> xs;
  final String? x;

  int doesNotWork() {
    return x != null ? xs.indexOf(x) : 0; // error: 'T?' can't be assigned to type: 'T'
  }
  
  int works() {
    final x = this.x;
    return x != null ? xs.indexOf(x) : 0; // no error
  }
}
```

Tested with Dart v3.3.2

**Comment by lrhn** [comment]
Correct. You can only promote local variables, and a few select privately named `final` instance variables, where the compiler is absolutely certain that the value can't change between two reads.

In general, assume you can only promote local variables.

**Comment by parlough** [comment]
If you'd like to learn more about various promotion failures and how to work around them, check out https://dart.dev/tools/non-promotion-reasons#other-causes-and-workarounds :)
