### ISSUE TITLE
Top-level `unused_elements` are not ignored by `// ignore_for_file: type=lint`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#55332]
Hello!  
Consider the following:

```dart
// ignore_for_file: type=lint

const _fn = 42;
```

This will warn that `_fn` is unused.  
My guess is that this is because some `unused_elements` diagnostics come-up as warnings, while some are infos (such as this case).

**Comment by srawlins** [comment]
`unused_element` can now be ignored via `// ignore_for_file: type=warning`.
