### ISSUE TITLE
[dart2wasm] Getting `illegal cast`, only when compiled with `-O0`

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#55341]
This is a minimum reproducible case, distilled from some code in the flutter framework that was causing this problem.

Steps to reproduce:

(1) Compile the following code with `dart compile wasm -O0 --extra-compiler-option=--enable-asserts`:
```
void main() {
  final Map<String, Map<String, String>> nestedMap = <String, Map<String, String>>{};
  nestedMap?['hello'] ??= <String, String>{};
  nestedMap?['hello']!['world'] = 'foo';

  print('map: $nestedMap');
}

bool get isDebug => !bool.fromEnvironment('dart.vm.product') && !bool.fromEnvironment('dart.vm.profile');

Map<String, Map<String, String>>? getNestedMap() {
  return isDebug ? <String, Map<String, String>>{} : null;
}
```

(2) Instantiate and run the output in a browser.

Results:
This crashes, with the following appearing in console:
```
assert_text.wasm:0xbb2e Uncaught RuntimeError: illegal cast
    at main (assert_text.wasm:0xbb2e)
    at main tear-off trampoline (assert_text.wasm:0xbb87)
    at _invokeMain (assert_text.wasm:0xbd73)
    at invoke (assert_text.mjs:227:28)
    at (index):7:9
```

Note: This seems to not occur when running at `-O1` or higher, so something in the `wasm-opt` transformations somehow smooths out whatever issue is occurring here.

**Comment by osa1** [comment]
This looks like a CFE bug. Slightly smaller repro:

```dart
void main() {
  final Map<String, Map<String, String>> nestedMap = <String, Map<String, String>>{};
  nestedMap?['hello'] ??= <String, String>{};
  print('map: $nestedMap');
}
```

Kernel: (slightly simplified and formatted)

```
static method main() → void {
  final Map<String, Map<String, String>> nestedMap = <String, Map<String, String>>{};

  let final Map<String, Map<String, String>> #t1 = nestedMap in #t1 == null
      ? {Map<String, String>?} null
      : let final String #t2 = "hello" in #t1.{Map::[]}(#t2){(Object?) → Map<String, String>?} == null
          ? {Map<String, String>} #t1.{Map::[]=}(#t2, <String, String>{}){(String, Map<String, String>) → void}
          : null;

  print("map: ${nestedMap}");
}
```

Here type of `#t1` is non-nullable, but the else branch of the else branch returns `null`.

@johnniwinther is my reading of the kernel correct? Do you agree that this is a CFE bug? Here's the full kernel as printed by SDK:

```
  static method main() → void {
    final core::Map<core::String, core::Map<core::String, core::String>> nestedMap = <core::String, core::Map<core::String, core::String>>{};
    let final core::Map<core::String, core::Map<core::String, core::String>> #t1 = nestedMap in #t1 == null ?{core::Map<core::String, core::String>?} null : let final core::String #t2 = "hello" in #t1.{core::Map::[]}(#t2){(core::Object?) → core::Map<core::String, core::String>?} == null ?{core::Map<core::String, core::String>} #t1.{core::Map::[]=}(#t2, <core::String, core::String>{}){(core::String, core::Map<core::String, core::String>) → void} : null;
    core::print("map: ${nestedMap}");
  }
```

**Comment by osa1** [comment]
Slightly smaller repro:

```dart
void main() {
  final Map<String, Map<String, String>> nestedMap = <String, Map<String, String>>{};
  nestedMap?['hello'] ??= <String, String>{};
  print('map: $nestedMap');
}
```

Kernel: (simplified)

```dart
static method main() → void {
  final Map<String, Map<String, String>> nestedMap = <String, Map<String, String>>{};

  let final Map<String, Map<String, String>> #t1 = nestedMap in
    #t1 == null
      ?{Map<String, String>?} null
      : let final String #t2 = "hello" in
          #t1.{Map::[]}(#t2){(Object?) → Map<String, String>?} == null
            ?{Map<String, String>} #t1.{Map::[]=}(#t2, <String, String>{}){(String, Map<String, String>) → void}
            : null;

  print("map: ${nestedMap}");
}
```

When compiling conditional with the `Map.[]` call we try to cast the return type to `ref Object` because that's the `expectedType` argument passed to the compiler (I don't know when compiling which library function), but the else branch returns `null`.

**Comment by johnniwinther** [comment]
I think we set the static type of the last conditional expression wrongly. From the language perspective it is correct that the whole expression is known to return `Map<String, String>` but since we see that the value is not used we use `null` as the false case of the conditional expression. We should either _not_ optimize for this case (and use the value of `nestedMap['hello']` as the result) or update the static type of the `ConditionalExpression` to be nullable.

@chloestefantsova What do you think is the best approach?

**Comment by chloestefantsova** [comment]
> @chloestefantsova What do you think is the best approach?

Intuitively it feels that adjusting the type of the conditional expression should be an easier route. Let me look into it a bit more close.

**Comment by chloestefantsova** [comment]
I'm experimenting with a potential solution at https://dart-review.googlesource.com/c/sdk/+/360865.

**Comment by akalankavinda** [comment]
Hello. 
I am simply trying to pass a string to dart function.

`@pragma("wasm:export")
void onKeyup(String elemntId) {
  print(elemntId);
}`

but it fails with the following error on the browser.
![image](https://github.com/dart-lang/sdk/assets/23008400/8a0a0cfc-0c1f-4002-b5b8-c42a505173af)

can you suggest me a fix for this please ?
