### ISSUE TITLE
None of the patterns in the switch expression the matched after hot-reload

### ISSUE THREAD

**Issue by petrnymsa** [dart-lang/sdk#55350]
Issue originally discussed on  [X (Twitter)](https://twitter.com/petrnymsa/status/1768353866796470492) with @mraleph.

Example project with a reproducible issue is originally stripped down version of our large project. I tried to minimize code to absolute minimum with some files which I believe are interesting and related to this issues.

## What is happening?
Project is monorepo based application. Application is in `apps` folder and there is also `core` packages containing some "core" domain types.

We have enhanced enum `ModuleType` in "core" package. This enum describes available module of app (doesn't really matter for issue]. In `app` there is `module_type_extension` - a extension on `ModuleType` with simple switch expression returning some value based on ModuleType's value (for example path to icon). 

**After hot-reload** sometimes issue  appears:

```
None of the patterns in the switch expression the matched input value. See https://github.com/dart-lang/language/issues/3488 for details
```

but I don't understand why. 

Some noticeable things
- issues is gone if we remove "BlocBuilder" (Flutter_Bloc) from home_page
- issue is gone if I completely remove `apps/patterns_repro/lib/shared/widgets/dialogs/action/action_dialog.dart` - this file is not used by home_page and related widgets BUT still somehow affects.

**What I suspect**: Issues seems to be related somehow to "barell" files and cyclic imports and exports. But my knowledge is falling behind to understand it. 

## How to repro step by step
- Run project on Android or iOS (emulator or rea device, should not matter)
- Change value of `height` on line 9 in `apps/patterns_repro/lib/modules/home/widgets/enabled_modules_view.dart`. (Or just anything there to invoke hot reload)
- Notice that mentioned issue appears

However like I said before
- Remove action_dialog.dart
- Uncomment  lines 23 - 27 in home_page.dart returning EnabledModulesView directly. Issues seems to be gone no matter how ModyleType type is imported.

### Dart and Flutter versions
```
Flutter 3.19.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68bfaea224 (12 days ago) • 2024-03-20 15:36:31 -0700
Engine • revision a5c24f538d
Tools • Dart 3.3.2 • DevTools 2.31.1
```

NOTE: Tested on different machines with Windows and MacOS.

Link to project: [https://github.com/petrnymsa/dart-pattern-none-issue](https://github.com/petrnymsa/dart-pattern-none-issue)

**Comment by a-siva** [comment]
@petrnymsa There doesn't seem to be any licensing information associated with the code you provided for reproduction,, would it be possible to extract a reproduction into a simpler test case and post it here or add an open source license to your code that permits us to use the reproduction you have.

**Comment by petrnymsa** [comment]
> @petrnymsa There doesn't seem to be any licensing information associated with the code you provided for reproduction,, would it be possible to extract a reproduction into a simpler test case and post it here or add an open source license to your code that permits us to use the reproduction you have.

Added LICENSE - MIT. Code is similar to minimal version from our, private project, but classes are renamed and simplified.
