### ISSUE TITLE
[Query]: Facing difficulty in setting up this repo locally

### ISSUE THREAD

**Issue by Sahil-kachhap** [dart-lang/sdk#55366]
I have followed the contribution guidelines to get the source code using `fetch dart` command. But once I open the respective folder in vscode. I am unable to get all the dependencies.

For instance, Here I have opened the analysis_server package in the IDE. On running `dart pub get`, it throws the following error. Can anyone please share any solution to get all the dependencies here. 

![setup issue](https://github.com/dart-lang/sdk/assets/54017876/15708b91-4ccc-439c-99b9-4ec297709b9a)

**Comment by mraleph** [comment]
SDK does not use `pub` for managing dependencies. Delete any `.dart_tool` folders which were created by attempts to run `dart pub get`.

Instead make sure that at the root of the SDK checkout there is `.dart_tool/package_config.json`. If there is none - run `gclient runhooks`. 

After that IDE should be able to resolve SDK specific packages.
