### ISSUE TITLE
Arm64 ResumeStub uses R0 as kTemp which seems unsafe?

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#55365]
Arm64's ResumeStub uses R0 as a temp register.  I it appears to not actually be a temp register.  If you set it to a value later parts of the code fail.

https://github.com/dart-lang/sdk/blob/2dae577c676a16afe99f9a7058de51ef381b983f/runtime/vm/compiler/stub_code_compiler.cc#L2253
https://github.com/dart-lang/sdk/blob/2dae577c676a16afe99f9a7058de51ef381b983f/runtime/vm/constants_arm64.h#L429

```cc
void StubCodeCompiler::GenerateResumeStub() {
  const Register kSuspendState = ResumeStubABI::kSuspendStateReg;
  const Register kTemp = ResumeStubABI::kTempReg;
```

The normal Jump to the resumePc happens here:
https://github.com/dart-lang/sdk/blob/2dae577c676a16afe99f9a7058de51ef381b983f/runtime/vm/compiler/stub_code_compiler.cc#L2395

It seems in !precompiled kTemp ends up as zero:
https://github.com/dart-lang/sdk/blob/2dae577c676a16afe99f9a7058de51ef381b983f/runtime/vm/compiler/stub_code_compiler.cc#L2380-L2389

But in other cases it ends up as maybe the last bytes of the frame!?
https://github.com/dart-lang/sdk/blob/2dae577c676a16afe99f9a7058de51ef381b983f/runtime/vm/compiler/stub_code_compiler.cc#L2342

If you modify the code to set kTemp (R0) to something before jumping:

```diff
diff --git a/runtime/vm/compiler/stub_code_compiler.cc b/runtime/vm/compiler/stub_code_compiler.cc
index d2e9ffeb060..e525e17d090 100644
--- a/runtime/vm/compiler/stub_code_compiler.cc
+++ b/runtime/vm/compiler/stub_code_compiler.cc
@@ -2376,6 +2376,7 @@ void StubCodeCompiler::GenerateResumeStub() {
   __ LoadFromOffset(CallingConventions::kReturnReg, FPREG,
                     param_offset + 3 * target::kWordSize);
 
+  __ LoadImmediate(kTemp, 42);
   __ Jump(kResumePc);
 
   __ Comment("Call runtime to throw exception or deopt");
```

Then builds fail (you can build smaller sections of Dart, but dart itself no longer can do async execution correctly):
```
eseidel@erics-mbp sdk % ./tools/build.py --mode debug --arch arm64 --gn-args=dart_debug_optimization_level=0
Generating Xcode projects took 27ms
Done. Made 441 targets from 121 files in 751ms
buildtools/ninja/ninja -C xcodebuild/DebugARM64
ninja: Entering directory `xcodebuild/DebugARM64'
[39/52] ACTION //utils/kernel-service:kernel-service_snapshot(//build/toolchain/mac:clang_arm64)
FAILED: gen/kernel-service.dart.snapshot 
python3 ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=../../.dart_tool/package_config.json --snapshot=gen/kernel-service.dart.snapshot --snapshot-depfile=gen/kernel-service.dart.snapshot.d --snapshot-kind=app-jit --dfe=../../utils/kernel-service/NEVER_LOADED gen/utils/kernel-service/kernel-service_snapshot.dart.dill --train file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart
Command failed: /Users/eseidel/Documents/GitHub/dart-sdk/sdk/xcodebuild/DebugARM64/dart --deterministic --packages=../../.dart_tool/package_config.json --snapshot=gen/kernel-service.dart.snapshot --snapshot-depfile=gen/kernel-service.dart.snapshot.d --snapshot-kind=app-jit --dfe=../../utils/kernel-service/NEVER_LOADED gen/utils/kernel-service/kernel-service_snapshot.dart.dill --train file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart
output: Unhandled exception:
type 'int' is not a subtype of type 'List<int>?' of 'value'
#0      Future._completeWithValue (dart:async/future_impl.dart:647:29)
<asynchronous suspension>
#1      ProcessedOptions.loadSdkSummaryBytes (package:front_end/src/base/processed_options.dart:151:26)
<asynchronous suspension>
#2      _processLoadRequest (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:975:20)
<asynchronous suspension>
#3      trainInternal (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:1154:3)
<asynchronous suspension>
#4      train (file:///Users/eseidel/Documents/GitHub/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart:1098:3)
<asynchronous suspension>

[40/52] ACTION //utils/dartdev:generate_dartdev_snapshot_dill(//build/toolchain/mac:clang_arm64)
ninja: build stopped: subcommand failed.
BUILD FAILED
```

I think at best this is a variable naming/register assignment error (e.g. kTemp really should be R16 or something)?   But probably there is some sort of async/await functionality broken in subtle ways on ARM64 due to this register stomping?

I'm really not sure.

**Comment by alexmarkov** [comment]
ResumeStubABI defines allocation of registers used in ResumeStub. ResumeStub can clobber any registers, so they are picked more or less arbitrarily. That includes ResumeStubABI::kTempReg which is a temporary (scratch) register.

However, when ResumeStub resumes the code, it needs to return a value. That value is put into `R0` according to Dart calling conventions. This is done at the end of ResumeStub, right before jumping to a resume PC:

https://github.com/dart-lang/sdk/blob/51d7b8477d4abe6cc54b203dcf6fae3a45f0c7db/runtime/vm/compiler/stub_code_compiler.cc#L2376-L2379

Note that `CallingConventions::kReturnReg` also maps to `R0`. So your code modification which clobbers `kTemp` right before the `Jump(kResumePc)` in fact clobbers the return value loaded in a previous instruction and it is not correct.

The current uses of `kTemp` in ResumeStub look safe to me.

**Comment by felangel** [comment]
> ResumeStubABI defines allocation of registers used in ResumeStub. ResumeStub can clobber any registers, so they are picked more or less arbitrarily. That includes ResumeStubABI::kTempReg which is a temporary (scratch) register.
> 
> However, when ResumeStub resumes the code, it needs to return a value. That value is put into `R0` according to Dart calling conventions. This is done at the end of ResumeStub, right before jumping to a resume PC:
> 
> https://github.com/dart-lang/sdk/blob/51d7b8477d4abe6cc54b203dcf6fae3a45f0c7db/runtime/vm/compiler/stub_code_compiler.cc#L2376-L2379
> 
> Note that `CallingConventions::kReturnReg` also maps to `R0`. So your code modification which clobbers `kTemp` right before the `Jump(kResumePc)` in fact clobbers the return value loaded in a previous instruction and it is not correct.
> 
> The current uses of `kTemp` in ResumeStub look safe to me.

Thanks for clarifying! I missed the fact that `CallingConventions::kReturnReg` also maps to `R0`. It seems like an improvement would be to adjust `ResumeStubABI::kTempReg` to map to a different register and avoid conflicting with `CallingConventions::kReturnReg` since it currently gives the impression that it's ok to clobber `kTemp`.

**Comment by eseidel** [comment]
Thanks.  Apologies for the noise.  I guess we added code between when the return reg was set and when the jump was made which used kTemp and didn't realize kTemp and kReturnReg were the same.  Feel free to close. 🤷

**Comment by eseidel** [comment]
(We ended up solving this in our code by changing kTemp to = TMP (R16) on arm64).
