### ISSUE TITLE
Analyzer crash due to clashing macro-generated types

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#55360]
From this test

https://dart-review.googlesource.com/c/sdk/+/360840

two clashing new types generated in the same library cycle causes an exception like

```
Bad state: [_classIndex: 1][classes.length: 1][classes: [class A]][element.source: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/tests/language/macros/library_cycle/clashing_new_types_test.macro.dart][libraryFilePath: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/tests/language/macros/library_cycle/clashing_new_types_test.dart][unitFilePath: /usr/local/google/home/davidmorgan/git/dart-sdk/sdk/tests/language/macros/library_cycle/clashing_new_types_test.macro.dart]
#0      ElementWalker.getClass (package:analyzer/src/generated/element_walker.dart:164:7)
#1      ResolutionVisitor.visitClassDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:293:48)
#2      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2759:50)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12308:20)
```

this happens if they are in the same file or if they are in different files.

In the same file it should be an "already declared" error.

In different files--as in the linked test--the code is correct, they don't actually clash. But the analyzer crashes the same :)

**Comment by davidmorgan** [comment]
Thanks, that helps me to make progress!

https://github.com/dart-lang/sdk/issues/55360 and the linked test appears to find a different issue now.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/361243
