### ISSUE TITLE
The dart vm should not run a file, if it has the name of a sub-command 

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#55370]
`dart <p>` will run the file `<p>` if it exists. Otherwise it will defer to dartdev and its command parsing

This is quite brittle - for example:

```
> echo "main() => print('All your base are belong to us');" > pub
> dart pub get
All your base are belong to us
```

This seems to be a way to override the dart commands in a local directory and cause very surprising (and potentially malicious) behavior.

**Comment by lrhn** [comment]
See also: https://github.com/dart-lang/sdk/issues/51932

**Comment by sigurdm** [comment]
Working on a fix in https://dart-review.googlesource.com/c/sdk/+/361363
