### ISSUE TITLE
[CP] Fix package name when refreshing binstubs

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#55373]
### Commit(s) to merge

https://github.com/dart-lang/pub/pull/4205
Was rolled to sdk main in https://dart-review.googlesource.com/c/sdk/+/361061

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/361102

### Issue Description

`dart pub global run` would (under some circumstances) rewrite binstubs with bad contents. Making them unrunable.

### What is the fix

Write the correct binstub instead of the broken one.

### Why cherry-pick

This potentially affects all users of pub binstubs

### Risk

Medium-Low

### Issue link(s)

https://github.com/dart-lang/pub/issues/4206

**Comment by itsjustkevin** [comment]
@jonasfj and @athomas can you take a look at this cherry-pick?

**Comment by jonasfj** [comment]
LGTM
