### ISSUE TITLE
Build fails on 3.1.0 and following without any clear error

### ISSUE THREAD

**Issue by gerritwalther** [dart-lang/sdk#55381]
First of all my project was mainly build using Dart 1.0 quite a while ago and I almost only migrated first to Dart 2.0 and recently to 3.0. With Dart 3.0.7 the project builds fine, but I had an issue with 3.2.4 on my server. I used `asdf` to test different Dart versions and switching from Dart 3.0.7 to 3.1.0 produces the following error. There are no obvious `webdev` or `build_web_compilers` changes switching between these versions, so I'm not quite sure where this error is coming from and what even might be the problem. The output is generated using `webdev build -v -o bin:build`:

```
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 805ms
[INFO] 
[INFO] Starting daemon...
[INFO] BuildDefinition: Initializing inputs
[INFO] BuildDefinition: Reading cached asset graph...
[INFO] BuildDefinition: Reading cached asset graph completed, took 412ms

[INFO] BuildDefinition: Checking for updates since last build...
[INFO] BuildDefinition: Checking for updates since last build completed, took 1.3s

[SEVERE] Initializing inputs
[SEVERE] Reading cached asset graph...
[SEVERE] Reading cached asset graph completed, took 412ms
[SEVERE] 
[SEVERE] Checking for updates since last build...
[SEVERE] Checking for updates since last build completed, took 1.3s
[SEVERE] 
[SEVERE] Setting up file watchers...
[SEVERE] Setting up file watchers completed, took 12ms
[SEVERE] 
[INFO] About to build [bin]...
[INFO] Build: Running build...
[INFO] Build: Running build completed, took 228ms

[INFO] Build: Caching finalized dependency graph...
[INFO] Build: Caching finalized dependency graph completed, took 265ms

[SEVERE] build_web_compilers:entrypoint on bin/main.dart (cached): ExitCode:0
StdOut:
Compiled 10,006,579 input bytes (5,219,522 characters source) to 238,243 characters JavaScript in 3.45 seconds using 264.230 MB of memory

StdErr:


[SEVERE] Build: Failed after 505ms
[SEVERE] FailureType: 1
```

The project is public. Checking out the `master` branch and either executing `make release` or without Make do a simple `dart pub get` followed by the above command should reproduce the error.

Project: https://github.com/gerritwalther/sg2o

My `dart info` response using Dart 3.1.0 :

```
$ dart info

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "linux_x64"
- on linux / Linux 6.6.24-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Apr  4 04:33:21 UTC 2024
- locale is en_GB.UTF-8

#### Project info

- sdk constraint: '>=3.0.0 <4.0.0'
- dependencies: html, path
- dev_dependencies: build_runner, build_web_compilers

#### Process info

No Dart processes found.
```

**Comment by jakemac53** [comment]
I see you are passing a `-o` argument to dart2js in your build.yaml file - can you try removing that? There is already an implicit `-o` flag being passed, and we require it to go to a specific place. I think maybe it is failing because it doesn't see the expected output.

**Comment by gerritwalther** [comment]
> I see you are passing a `-o` argument to dart2js in your build.yaml file - can you try removing that? There is already an implicit `-o` flag being passed, and we require it to go to a specific place. I think maybe it is failing because it doesn't see the expected output.

Yes, that solved my issue, thank you very much for your help. I guess you changed the behavior in 3.1.0?

I'm still getting the `SEVERE` errors/warnings, but those don't interfere with my build. The output also looks fine to me.

```
[SEVERE] Initializing inputs
[SEVERE] Building new asset graph...
[SEVERE] Building new asset graph completed, took 1.3s
[SEVERE] 
[SEVERE] Checking for unexpected pre-existing outputs....
[SEVERE] Checking for unexpected pre-existing outputs. completed, took 0ms
[SEVERE] 
[SEVERE] Setting up file watchers...
[SEVERE] Setting up file watchers completed, took 4ms
[SEVERE] 
```

**Comment by jakemac53** [comment]
> Yes, that solved my issue, thank you very much for your help. I guess you changed the behavior in 3.1.0?

I don't remember any particular change here, it was never intended to be supported at least (in build_runner). The flag is supported by dart2js itself still, it just doesn't make sense to use in this context.

**Comment by gerritwalther** [comment]
> I don't remember any particular change here, it was never intended to be supported at least (in build_runner). The flag is supported by dart2js itself still, it just doesn't make sense to use in this context.

I guess I just moved it along when migrating from Dart 1 to 2 and never changed it while it was working. Thank you again for your help.
