### ISSUE TITLE
_writeSuperMemberInvocation in change_builder_dart does not include proper convention for named parameters while generating override method with super invocation

### ISSUE THREAD

**Issue by Devenik7** [dart-lang/sdk#55384]
This is how the Intellisense currently generates a super method invocation while using autocomplete for override methods.

<img width="689" alt="Screenshot 2024-04-05 at 3 02 11 PM" src="https://github.com/dart-lang/sdk/assets/8947158/8e80706c-d974-45f5-9173-eb449a24ad89">

What is expected -
It is expected to generate this.

<img width="689" alt="Screenshot 2024-04-05 at 3 03 04 PM" src="https://github.com/dart-lang/sdk/assets/8947158/83ec77cd-dd89-4505-b45d-1579bec0a05e">

I have raised a PR for the same.

https://github.com/dart-lang/sdk/pull/55383

**Comment by Devenik7** [comment]
I have raised a PR for the same

https://github.com/dart-lang/sdk/pull/55383

This is my first time contributing to Open Source. Please guide me. Thanks.

**Comment by Devenik7** [comment]
Opened new PR since last one was closed

https://github.com/dart-lang/sdk/pull/55697

**Comment by keertip** [comment]
The PR was submitted, so this issue has been fixed.
