### ISSUE TITLE
[CP] Add missing details about pub feature to CHANGELOG

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#55385]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/361381

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/361382

### Issue Description

We forgot to mention new behavior of the pub client

### What is the fix

Add a paragraph to the CHANGELOG

### Why cherry-pick

A shame to not let users know about this.

### Risk

Low

### Issue link(s)

https://dart-review.googlesource.com/c/sdk/+/361382

**Comment by mit-mit** [comment]
I don't have a problem with changing this in beta, but @athomas don't we typically just edit the CHANGELOG in the main channel and then link folks to that?

**Comment by sortie** [comment]
This CP is not needed. The change just needs to be landed on the main CHANGELOG and the stable branch will later pick it up automatically.
