### ISSUE TITLE
Add TargetKind: instanceMember

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#55387]
After reviewing our annotation offerings in the meta package, I've seen that more than a handful would benefit from a new TargetKind, `instanceMember`, as many are concerned with inheritance. E.g. `@mustCallSuper`, `@visibleForOverride`, `@protected`, etc.

We could add specific variants, for instance methods, fields, setters, etc. but I think that would add unnecessary complexity, and error-prone.

**Comment by srawlins** [comment]
CC @pq @bwilkerson

**Comment by srawlins** [comment]
Specifically, I would advocate for these changes:

* `@mustBeOverridden` -> only `TargetKind.instanceMember`
* `@mustCallSuper` -> only `TargetKind.instanceMember`
* `@protected` -> only `TargetKind.instanceMember`
* `@visibleForOverriding` -> only `TargetKind.instanceMember`

In the first two cases, this effectively would start reporting annotations on static members as invalid.

In the last two cases, there are no TargetKinds specified, so it would be replacing the custom rules implemented in the analyzer.

**Comment by bwilkerson** [comment]
The original design for `TargetKind` constants was for each constant to specify a set of elements. Having a target kind named `instanceMember` is perfectly reasonable under that design.

Having different kinds for instance getters (or other subsets of `instanceMember`) is also perfectly reasonable, though as we discussed elsewhere I don't think we need to add every possible variant until we have a use case for it.

**Comment by pq** [comment]
I agree with everything Brian said. +1 to `instanceMember` to start.
