### ISSUE TITLE
Please provide a way to set untranslated I/O mode on Windows

### ISSUE THREAD

**Issue by projektorius96** [dart-lang/sdk#55393]
So I am writing a [Native messaging host](https://developer.chrome.com/docs/extensions/develop/concepts/native-messaging#native-messaging-host) for Chromium-based browser in Dart, I have a working draft of transcoding [implementation](https://github.com/projektorius96/native_messaging_host) and it works for `decodeMessage` (at least I can see that on my side with `stdout` redirected to file), but it seems that it breaks on `dart_io.stdout.write` call, and not because of `encodeMessage` implementation itself, but due to default (i.e. `_O_TEXT`) Windows's I/O translation mode, which in turn corrupts the encoded message with the respond from Chromium-based browser Extension system `Error when communicating with the native messaging host.` 

I am writing this to to **request a feature**, which as far as I do understand does not currently (2024 Q1) exist on higher level end of Dart VM, i.e. **to control the I/O mode for Windows via Dart VM** . Please understand that FFI to C via Win API is my last resort.

_P.S. I am willing to share the final codebase with Dart community once I get it done working_

Thank you.

---

This tracker is for issues related to:

* Dart core libraries
* Dart native compilers
* Dart VM

**Comment by projektorius96** [comment]
**Windows users only!**

Consider the following [alternative](https://github.com/projektorius96/ws-nmh) instead of Native Messaging Host – the motivation of using this, could be a simpler set up and no registry involved.

Cheers ! ♥

**Comment by brianquinlan** [comment]
@projektorius96 I don't understand your issue; `stdout.write` does not do new line translation by default (in Dart 3.4, you will be able to control that behavior with the [`lineTerminator` field](https://api.dart.dev/beta/3.4.0-282.1.beta/dart-io/Stdout/lineTerminator.html).

Do you have a minimal example that demonstrates the issue?

**Comment by projektorius96** [comment]
> @projektorius96 I don't understand your issue; `stdout.write` does not do new line translation by default (in Dart 3.4, you will be able to control that behavior with the [`lineTerminator` field](https://api.dart.dev/beta/3.4.0-282.1.beta/dart-io/Stdout/lineTerminator.html).
> 
> Do you have a minimal example that demonstrates the issue?

I have couple of arbitrarily defined functions as per [implementation](https://github.com/projektorius96/native_messaging_host_use-case/blob/main/lib/src/native_messaging_host_base.dart) : 
- `decodeMessage` works just fine, stream redirection to file shows exactly same message sent from service-worker via `sendNativeMessage` [source](https://github.com/projektorius96/native_messaging_host_use-case/blob/main/unpacked-extension/service-worker.js)
- `encodeMessage` somehow corrupts a message and I naturally suspected the I/O translation mode keeping in mind it is documented in Debugging as described per original post; After all, it can be something wrong with `encodeMessage` itself, but in that case, I'd say Chromium is really nit-picky if it cannot pick up even broken message, rather than giving me the aforementioned error as follows "`Error when communicating with the native messaging host.`" .

It's just my very first try doing something relatively low, but in higher programming language, and I even fail at that. Not saying I am not bad at other things, yet it can be something with my codebase simply due to lack of knowledge. Cheers !

**Comment by brianquinlan** [comment]
Hi @projektorius96 

I'm going to close this issue. If you manage to reduce this enough to demonstrate a bug in dart:io, please reopen it!

**Comment by projektorius96** [comment]
@brianquinlan so apparently I have to admit I was wrong, I mean well like I said "lack of knowledge", if you ever eyeballed on my codebase, you perhaps you had said that I need to `await stdout.flush()`, but nah it took me couple of yours to figure out it by myself, perhaps ill-service would not serve me for better as developer, yet I was expecting a bit of the help out here and got none. Crocodile tears haha

Tagging @parlough as just wanted to emphasize that I am polishing the Native Messaging Host (hereinafter – NMH) codebase and I will defo raise another issue (more precisely, feature request) to updating Dart docs CLI section with this NMH example, if permission would be granted, I could contribute too, but in that case could you at least please send me some instructions to follow so I could fork the current tip-of-tree and PR to your end, guys. Not closing yet, requesting general feedback.

Cheers !

**Comment by projektorius96** [comment]
If interested, you can follow up the related discussion on this [issue](https://github.com/dart-lang/site-www/issues/5705#issuecomment-2062593820). I am closing this myself, if you have anything to add, please re-open.

Cheers !
