### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by AzizEshpolatov** [dart-lang/sdk#55398]
## Version information

- `IDEA AI-231.9392.1.2311.11255304`
- `3.3.2`
- `AI-231.9392.1.2311.11255304, JRE 17.0.7+0-b2043.56-10550314x64 JetBrains s.r.o., OS Windows 11(amd64) v10.0 , screens 2400.0x1350.0`

**Comment by vsmenon** [comment]
Hi, can you please resubmit with more info on the actual error?
