### ISSUE TITLE
[vm] vmspecific_handle_test crash

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55399]
There are new test failures on [DAS: Refactor the logic determining the location of a new ignore-comment...[vm/compiler] Add the capability for Slots on non-Dart objects.](https://github.com/dart-lang/sdk/compare/cf4a4a3c00a4e160b3c924cc3081582dd42b26f7~...df707ac85e9a81b73c80638b759aede6be80ebbb).

The tests
```
ffi/vmspecific_handle_test Crash (expected Pass)
```
are failing on configurations
```
vm-aot-optimization-level-linux-release-x64
```

```
callback() returned an error, propagating error
testNull
ReturnHandleInCallback 0x7fc33fc30480
returnHandleCallback returning null

stderr:
../../runtime/vm/runtime_entry.cc: 300: error: hit null error with cid 30, caller context: [sp+0] 00007fc33fb884e1(000044110001e170), [sp+1] 00007fc33f484919(000000000005941c), [sp+2] 00007fc33f484919(000000000005941c), [sp+3] 00007fc3402901e1(18ffbbac0005d332), [sp+4] 000000000000000a, [sp+5] 0000000000000005, [sp+6] 0000000000000001, [sp+7] 0000000000000017, [sp+8] 0000000000000002
version=3.5.0-edge (main) (Unknown timestamp) on "linux_x64"
pid=255991, thread=255996, isolate_group=main(0x55f13f759340), isolate=main(0x55f13f760fb0)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=7fc340108280, vm_instructions=7fc340101100
fp=7fc33f47dc50, sp=7fc33f47db20, pc=55f13ebd061c
  pc 0x000055f13ebd061c fp 0x00007fc33f47dc50 dart::Profiler::DumpStackTrace+0x7c
  pc 0x000055f13ea37954 fp 0x00007fc33f47dd30 dart::Assert::Fail+0x84
  pc 0x000055f13ebf70a9 fp 0x00007fc33f47dda0 dart::ReportImpossibleNullError+0x189
  pc 0x000055f13ebf71fb fp 0x00007fc33f47e3a0 dart::DRT_DispatchTableNullError+0x14b
  pc 0x00007fc340105afe fp 0x00007fc33f47e3d8 _kDartVmSnapshotInstructions+0x49fe
  pc 0x00007fc3401f686c fp 0x00007fc33f47e3f0 _kDartIsolateSnapshotInstructions+0xee5ec
```

[log](https://dart-ci.appspot.com/log/vm-aot-optimization-level-linux-release-x64/vm-aot-optimization-level-linux-release-x64/177/ffi/vmspecific_handle_test)

Will bisect locally.

```
$ dart tools/bisect.dart \
-Dend=cf4a4a3c00a4e160b3c924cc3081582dd42b26f7 \
-Dstart=df707ac85e9a81b73c80638b759aede6be80ebbb \
-Dtest_command="python3 tools/test.py --build -n vm-aot-optimization-level-linux-release-x64 ffi/vmspecific_handle_test" \
-Dfailure_string="hit null error with cid 30"
```

**Comment by dcharkes** [comment]
Commit range e588c8b379e...df707ac85e9a81b73c80638b759aede6be80ebbb.
Ensuring SDK repo in /usr/local/google/home/dacoharkes/master-dart-sdk/sdk/.
Ensuring failure reproduces on df707ac85e9a81b73c80638b759aede6be80ebbb.
Commit df707ac85e9a81b73c80638b759aede6be80ebbb, reproduces failure.
Ensuring failure does not reproduce on e588c8b379e.
Commit e588c8b379e, does not reproduce failure.
Bisecting e588c8b379e...df707ac85e9 (12 commits). Trying 85f3948d441.
Commit 85f3948d441, reproduces failure.
Bisecting e588c8b379e...85f3948d441 (6 commits). Trying da0540dfc7d.
Commit da0540dfc7d, reproduces failure.
Bisecting e588c8b379e...da0540dfc7d (3 commits). Trying 0833f8c0112.
Commit 0833f8c0112, reproduces failure.
Bisecting e588c8b379e...0833f8c0112 (2 commits). Trying cf4a4a3c00a.
Commit cf4a4a3c00a, reproduces failure.
Bisected to cf4a4a3c00a.

cc @sstrickl

**Comment by dcharkes** [comment]
@sstrickl I'm thinking this might be the conversion of of `Slot::LocalHandle_ptr`.

Not sure why we hit this with a `kSentinelCid`.

Could you please take a look?

**Comment by sstrickl** [comment]
Investigating now.

**Comment by sstrickl** [comment]
The issue is the assumption in `StoreFieldInstr::Canonicalize` that all tagged slots in Dart objects are initialized to null, so an initializing store of `null` can be dropped[^1].

The issue here is when generating the FFI trampoline for `returnNullHandleCallback`:
```
==== dart:ffi_::__FfiCallbackreturnNullHandleCallback (FfiTrampoline)
B0[graph]:0 {
      v0 <- Constant(#null)
      v1 <- Constant(#<optimized out>)
}
B1[native function entry]:2
    CheckStackOverflow:4(stack=0, loop=0)
    goto:8 B2
B2[join try_idx 0]:6 pred(B1)
    v13 <- StaticCall:10( returnNullHandleCallback<0> )
    v14 <- LoadThread() untagged
    v15 <- LoadField(v14 . Thread.api_top_scope) untagged
    v16 <- LoadThread() untagged
    v17 <- LoadUntagged(v16, 1456) untagged
    v18 <- CCall(target_address=v17, v15) untagged
    StoreField(v18 . LocalHandle.ptr = v13)
    NativeReturn(v18 (@rax int64))
B3[target catch try_idx -1 catch_try_idx 0] {
      v2 <- Parameter(0 @fp[-1])
      v3 <- Parameter(1 @fp[-2])
      v4 <- Parameter(2 @rax)
      v5 <- Parameter(3 @rdx)
      v6 <- Parameter(4 @fp[-5])
}
    v7 <- AllocateObject:14(cls=UnhandledException)
    StoreField(v7 . UnhandledException.exception = v4, NoStoreBarrier)
    StoreField(v7 . UnhandledException.stacktrace = v5, NoStoreBarrier)
    v8 <- LoadThread() untagged
    v9 <- LoadField(v8 . Thread.api_top_scope) untagged
    v10 <- LoadThread() untagged
    v11 <- LoadUntagged(v10, 1456) untagged
    v12 <- CCall(target_address=v11, v9) untagged
    StoreField(v12 . LocalHandle.ptr = v7)
    NativeReturn(v12 (@rax int64))
```

After inlining `returnNullHandleCallback`,  the code in `B2` becomes:
```
B2[join try_idx 0]:6 pred(B1)
    v36 <- LoadStaticField:4(_printClosure@9040228, CallsInitializer) T{_Closure}
    v33 <- ClosureCall:18( closure=v36 T{_Closure}<0>, v36 T{_Closure}, v22 T{_OneByteString})
    v14 <- LoadThread() untagged
    v15 <- LoadField(v14 . Thread.api_top_scope) untagged
    v16 <- LoadThread() untagged
    v17 <- LoadUntagged(v16, 1456) untagged
    v18 <- CCall(target_address=v17, v15) untagged
    StoreField(v18 . LocalHandle.ptr = v0)
    NativeReturn(v18 (@rax int64))
```

Since the `StoreField` is an initializing store with a `null` value, it gets dropped. However, the instance being stored into here isn't a Dart object (`slot().has_untagged_instance()`), so I've added `!slot().has_untagged_instance()` to the check for potentially dropping a null initialization in [https://dart-review.googlesource.com/c/sdk/+/361601](CL 361601).

[^1]: Except for freshly allocated uninitialized contexts, in which case the context slots are not null-initialized and so the store is not dropped.
