### ISSUE TITLE
[extension types] Analyzer incorrectly says that patterns involving extension types will never match

### ISSUE THREAD

**Issue by Quijx** [dart-lang/sdk#55406]
The analyzer shows a warning when a pattern matches an extension type saying that the value will never match the required type, when it clearly will.

The following dart code contains some examples and the corresponding analyzer warnings that are shown.
```dart
extension type const Id(int i) {}

class Foo {
  const Foo(this.id, this.ids);

  final Id id;
  final List<Id> ids;
}

void main() {
  const foo = Foo(Id(0), [Id(1), Id(2)]);
  switch (const Id(0)) {
    case Id():
      // ^^ The matched value type 'Id' can never match the required type 'Id'.
      print('id');
  }
  switch (foo) {
    case Foo(:final id):
      //      ^^^^^^^^ The matched value type 'Id' can never match the required type 'Id'.
      print(id);
  }
  switch (foo) {
    case Foo(:final ids):
      //      ^^^^^^^^^ The matched value type 'List<Id>' can never match the required type 'List<Id>'.
      print(ids);
  }
}
```

When switching the extension type with a corresponding class, the warnings disappear.
The program executes as expected and the cases are matched.

This happens in `Dart SDK version: 3.3.0 (stable)` as well as on the current master channel on dartpad.

**Comment by eernstg** [comment]
Thanks for the issue, @Quijx!

This issue [has been reported](https://github.com/dart-lang/sdk/issues/54561) and a fix is in the pipeline: The bogus warnings are not emitted in the main or beta channels.

I'll close the issue because the matter has been resolved and we're just waiting for the fix to arrive in the stable version of the tools.
