### ISSUE TITLE
Flutter app returns a different public IP when making a get request https://api.ipify.org using HttpClient

### ISSUE THREAD

**Issue by subinsv** [dart-lang/sdk#55405]
Issue:
* Flutter app returns a different public IP when making a GET request to https://api.ipify.org. Eg: 152.58.XX.XX

Notes:
* When loading the same URL in default mobile browser or on Native Android or iOS apps, the result matches. Eg: 152.58.YY.YY
* This happens only when on JIO Mobile network. On Airtel both flutter and native apps returns same result.

Test info:
**Case 1: JIO:**
Flutter App [HttpClient] -> 152.58.XX.XX **[Not expected]**
Android/iOS browser -> 152.58.YY.YY **[Expected]**
Android/iOS native app -> 152.58.YY.YY **[Expected]**
Flutter App [Flutter wrapper over native Android okHttp client] -> 152.58.YY.YY **[Expected]**

**Case 2: Airtel:**
Flutter App [HttpClient] -> 152.58.YY.YY **[Expected]**
Android/iOS browser -> 152.58.YY.YY **[Expected]**
Android/iOS native app -> 152.58.YY.YY **[Expected]**
Flutter App [Flutter wrapper over native Android okHttp client] -> 152.58.YY.YY **[Expected]**

We ran tests on multiple devices and it happens on all.
Why do we see different IP only when using flutter HttpClient with jio? Shouldn't it be same, or is this the expected case.

Repo to reproduce issue:
https://github.com/subinsv/flutter_ip_issue
![ip_issue](https://raw.githubusercontent.com/subinsv/flutter_ip_issue/main/ip_issue_1.jpeg)

#### General info

- Dart 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "macos_arm64"
- on macos / Version 14.4.1 (Build 23E224)
- locale is en-IN

**Comment by vsmenon** [comment]
Is this an issue with http_client?  If so, please file the issue in that repository.  Thanks!

**Comment by subinsv** [comment]
@vsmenon it happens with httpClient from dart.io as well. 

https://api.flutter.dev/flutter/dart-io/HttpClient-class.html

**Comment by devoncarew** [comment]
@brianquinlan - can you triage this issue?

**Comment by subinsv** [comment]
@mraleph It might not be bug. But I wonder why this happens only on Dart/Flutter.
As you can see in the screenshot, when we wrap it with native http client, it returns the proper IP address in the same session.
so, if it is a system wide proxy or multiple network interfaces, why dart client chooses a different one than the native part?

**Comment by subinsv** [comment]
@mraleph @devoncarew 

Thanks for the info. As, you said, this might not be a bug. But I would like to understand why it happens only on Flutter and not on any native apps or flutter plugin wrapper native http client. We were able to observe the same behaviour on multiple devices both Android and iOS running mobile data with Jio SIM. 

I tested the system wide proxy config, it is not set, and it is empty. So, I believe this is not the case.
Also, I don't see multiple interfaces with different IP in my phone. 

I just wonder how a phone app can see 2 different IP address within a single session as shown in screenshot. Can it be something how dart handles the request? 

I can help you debug the issue, if someone wish to continue.

**Comment by mraleph** [comment]
@subinsv Could you try running this: 

```
  final addresses = await InternetAddress.lookup('api.ipify.org');
  print(addresses);
  for (var addr in addresses) {
    final s = await Socket.connect(addr, 80);
    s.write(
        "GET / HTTP/1.1\r\nHost: api.ipify.org\r\nConnection: close\r\n\r\n");
    utf8.decoder.bind(s).join().then((data) {
      print('$addr responded: $data');
      s.close();
    });
    await s.flush();
  }
```

And see if it reveals anything interesting?

**Comment by subinsv** [comment]
Thanks @mraleph.
That gave me some interesting result. Looks like it happens when on IPV6. 
This looks like the expected behavior, but is there any reason for Dart behaving this way and native not? 
 
`
LoadingInternetAddress('64:ff9b::681a:ccd', IPv6) HTTP/1.1 200 OK
Date: Mon, 22 Apr 2024 08:26:19 GMT
Content-Type: text/plain
Content-Length: 13
Connection: close
Vary: Origin
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 87843a715d597fd0-MAA
[152.58.204.99]
*****
InternetAddress('64:ff9b::681a:dcd', IPv6) HTTP/1.1 200 OK
Date: Mon, 22 Apr 2024 08:26:20 GMT
Content-Type: text/plain
Content-Length: 13
Connection: close
Vary: Origin
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 87843a7418213f65-SIN
[152.58.204.99]
*****
InternetAddress('64:ff9b::ac43:4a98', IPv6) HTTP/1.1 200 OK
Date: Mon, 22 Apr 2024 08:26:20 GMT
Content-Type: text/plain
Content-Length: 13
Connection: close
Vary: Origin
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 87843a772d473f71-SIN
[152.58.204.99]
*****
InternetAddress('[104.26.13.205](http://104.26.13.205/)', IPv4) HTTP/1.1 200 OK
Date: Mon, 22 Apr 2024 08:26:21 GMT
Content-Type: text/plain
Content-Length: 14
Connection: close
Vary: Origin
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 87843a79f9ca44a1-SIN
[152.58.221.153]
*****
InternetAddress('[172.67.74.152](http://172.67.74.152/)', IPv4) HTTP/1.1 200 OK
Date: Mon, 22 Apr 2024 08:26:21 GMT
Content-Type: text/plain
Content-Length: 14
Connection: close
Vary: Origin
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 87843a7c98bf179b-MAA
[152.58.221.153]
*****
InternetAddress('[104.26.12.205](http://104.26.12.205/)', IPv4) HTTP/1.1 200 OK
Date: Mon, 22 Apr 2024 08:26:22 GMT
Content-Type: text/plain
Content-Length: 14
Connection: close
Vary: Origin
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 87843a7e99027eee-MAA
[152.58.221.153]
*****
`

**Comment by mraleph** [comment]
> This looks like the expected behavior, but is there any reason for Dart behaving this way and native not?

There is a bunch of custom logic in `dart:io` socket implementation which tries to prioritize connecting over IPv4 to work around some broken networks where trying to connect over IPv6 causes strange delays and timeouts (see https://dartbug.com/50868). That's likely the source of the discrepancy between native client and Dart's implementation.

**Comment by clickyzeeshan** [comment]
use this 

  public_ip_address: ^1.2.0


   IpAddress _ipAddress = IpAddress();
   var ip = await _ipAddress.getIp();
   print("IP Address:  " +  ip);
