### ISSUE TITLE
Failures on Reapply "[ DDS ] Add support for google3 URI conversion"

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#55411]
There are new test failures on [Reapply "[ DDS ] Add support for google3 URI conversion"](https://github.com/dart-lang/sdk/commit/c1dc26ab8dc773c18e63fde2cc1fbd0b41dbcccf).

The tests
```
pkg/dds/test/uri_converter_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-linux-arm64
unittest-asserts-release-mac-arm64
```

**Comment by sstrickl** [comment]
Reopening since the same error is happening again after [37c16d](https://github.com/dart-lang/sdk/commit/37c16d095c9ab20c47b73cb93c6cb73d1134a4f8).
