### ISSUE TITLE
[multi-option contexts] spurious `MISSING_DEPENDENCY` reported on a flutter customer app

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#55413]
Follow-up from: https://github.com/flutter/flutter/issues/146506

Reproducing locally:

```
☁  super_editor [bcba7282] dart fix -n
Computing fixes in super_editor (dry run)... 69.0s

75 proposed fixes in 64 files.

example/lib/marketing_video/main_marketing_video.dart
  unnecessary_cast • 1 fix

example/pubspec.yaml
  MISSING_DEPENDENCY • 1 fix

... <snip>

To fix an individual diagnostic, run one of:
  dart fix --apply --code=MISSING_DEPENDENCY
```

Next step is to figure out why we're detecting a `MISSING_DEPENDENCY` in `example/pubspec.yaml`.

/cc @keertip

**Comment by pq** [comment]
Keerti's fix in https://dart-review.googlesource.com/c/sdk/+/362161 should hopefully fix this 🤞

**Comment by bwilkerson** [comment]
Any updates? Did the above mentioned CL fix the problem?

**Comment by pq** [comment]
The CL was reverted and a new one landed. We need to give that a day or so to make sure it gets safely rolled. It **should** fix the issue.

**Comment by pq** [comment]
https://github.com/dart-lang/sdk/commit/0199e9d2d074bea834bf2b6dc757c2e0c6236a34 should fix the last blocker here. I'll try the bit flip again and hopefully we can close this out 🤞

**Comment by pq** [comment]
Marking fixed. 🎉
