### ISSUE TITLE
vm/dart/disassemble_determinism_test flaky -> Timeout on vm-mac-release-x64

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#55421]
There are new test failures on [[dart2wasm] Fix array.new_fixed calls with too large size...Store scope objects directly in AstNodes.](https://github.com/dart-lang/sdk/compare/a50a356eb2116decb43b47618fb9cd651eef1d53~...c7834b676494a212e076da3fe39de38d663cbe5d).

The tests
```
vm/dart/disassemble_determinism_test Timeout (expected Pass)
```
are failing on configurations
```
vm-mac-release-x64
```

Log: https://dart-ci.appspot.com/log/vm-mac-release-x64/vm-mac-release-x64/4350/vm/dart/disassemble_determinism_test

The test is also flaky on `vm-linux-release-x64` and `vm-appjit-linux-release-x64`.

**Comment by a-siva** [comment]
//cc @rmacnak-google
