### ISSUE TITLE
`dart:js_interop`'s `importModule` should support `TrustedTypes` API

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#55429]
`dart:js_interop` exposes a `importModule` API, which does a [dynamic import of an ES module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import).

However, `importModule` takes a `String` as the parameter which makes it incompatible with the [TrustedTypes API](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API). Basically, TrustedTypes essentially allows the URL to either be a string, or a `TrustedScriptURL`. So in order for this to actually be supported, `importModule` probably should take a `JSAny`.

**Comment by kevmoo** [comment]
*cough* I want union types! *cough*

**Comment by kevmoo** [comment]
@eyebrowsoffire – should this fix get into beta?

**Comment by srujzs** [comment]
> should this fix get into beta?

Can it be cherry-picked if it's a breaking change?

**Comment by eyebrowsoffire** [comment]
I personally don't think we need to worry about cherry-picking this.

**Comment by srujzs** [comment]
I'll send out an email to announce@dartlang.com here for the breaking change (and file an issue along with it), but I think the best justification I can find for this is https://github.com/tc39/proposal-dynamic-import-host-adjustment, which is a somewhat-related proposal. I still want to dig around and see if there's a concrete specification somewhere saying that this is intended if that makes sense.
