### ISSUE TITLE
Why does Dart use the Actor model?

### ISSUE THREAD

**Issue by SkUnK-cc** [dart-lang/sdk#55434]
Why does Dart use the Actor model?  Why doesn't Dart use the Thread model? 
Is Thread model not suitable for Dart?
Can anyone tell me why?

**Comment by julemand101** [comment]
https://github.com/dart-lang/language/blob/main/working/333%20-%20shared%20memory%20multithreading/proposal.md

**Comment by mraleph** [comment]
The simple answer is that Dart is using the model which was the only one available on the Web at the time when Dart was conceived. Original language designers also believed it to be simpler for developers.

**Comment by SkUnK-cc** [comment]
> The simple answer is that Dart is using the model which was the only one available on the Web at the time when Dart was conceived. Original language designers also believed it to be simpler for developers.

Is this reason？
[The State Of Web Workers In 2021](https://www.smashingmagazine.com/2021/06/web-workers-2021/)
![image](https://github.com/dart-lang/sdk/assets/30128419/6473740c-eca3-4f9c-a4e8-a7ded2d4eb86)
