### ISSUE TITLE
[CP] Use node's enclosing library annotation for lowerings

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#55430]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/361241

### Target

beta/stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/362195
https://dart-review.googlesource.com/c/sdk/+/362190

### Issue Description

Some JS interop members rely on the enclosing library's `@JS` annotation value to find the relevant JS member to dispatch to. In dart2wasm, the code to do so used the *invocation's* enclosing library's `@JS` annotation for this determination. This isn't an issue for many JS interop members because we replace the interop declaration for those members, but it is an issue for JS interop methods/constructors as we replace the interop invocation instead. This then leads to calling the wrong JS member because we failed to include the correct library annotation value, which may then lead to a crash due to a missing member.

This is only an issue on dart2wasm. This affects the following JS interop members: top-level methods, constructors, and static methods.

### What is the fix

Always use the declaration's enclosing library's annotation value and avoid caching the library's annotation value.

### Why cherry-pick

JS interop code that may work fine when compiling to JS may now crash when compiling to Wasm, and may lead to a frustrating debugging experience.

This affected two users so far. It affected the original user who filed the issue: https://github.com/dart-lang/sdk/issues/55359. It also affected the I/O demo app that @kevmoo has been working on.

### Risk

Low - this only affects the code to determine which JS interop member to use.

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55359

**Comment by kevmoo** [comment]
LGTM! Minimal risk, but clearly fixing an issue with Firebase!

**Comment by kevmoo** [comment]
Need to make sure this is merged into BETA, although getting it into the current stable is also nice

**Comment by itsjustkevin** [comment]
Please open a beta CL also, we are currently prioritizing beta cherry-picks as we stabilize before the next quarterly release.

**Comment by srujzs** [comment]
Done!

**Comment by sigmundch** [comment]
I support this CP too, for both stable and beta. I expect we'll see more usage on dart2wasm after 3.4, so I'd especially want to include it in 3.4 beta before it goes out as stable.

@srujzs - consider updating the description above to clarify which kind of JS interop member/methods are affected. I believe it's only top-level methods and possibly static class methods and properties?

cc @mkustermann

**Comment by srujzs** [comment]
> consider updating the description above to clarify which kind of JS interop member/methods are affected. I believe it's only top-level methods and possibly static class methods and properties?

Updated. It affects any JS interop member that uses the enclosing library's JS annotation and *could* contain optional parameters - top-level methods, constructors, and static methods.
