### ISSUE TITLE
Allow dependency_overrides for dependencies of dependencies

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#55440]
Right now it is possible to use `dependency_overrides` for the dependencies of your own project, but not for the dependencies of your dependencies. This frequently leads to the following kind of problem:

https://github.com/appsup-dart/firebase_admin/issues/40

Issues like this can sit for months or years, if the repo is abandoned, even with a PR:

https://github.com/appsup-dart/firebase_admin/pull/41/files

Eventually a repo like this will have to be forked by somebody who will actually bring it up to date and maintain it, but in the short term, it means that every user of this repo who needs to work with a newer version of a library (due to the version constraints of other dependencies in their project) needs to fork the abandoned repo themselves, and update the pubspec in that repo.

A better solution would be to be able to do something like the following, to override the dependencies of the dependency:

```yaml
dependencies:
  firebase_admin: ^0.2.0
    dependency_overrides:
      http: '>=0.13.0 <2.0.0'
```

**Comment by devoncarew** [comment]
My understanding of `dependency_overrides ` is that is should force constraint resolution to use the indicated version (https://dart.dev/tools/pub/dependencies#dependency-overrides), irrespective of the version constraint specified in either your direct `dependencies:` section or the version constraint from any direct or transitive dep.

Can you confirm that you are seeing something different from this? Preferably via a minimal repro. Thanks!

**Comment by lukehutch** [comment]
@devoncarew Correct, based on the current usage of `dependency_overrides`, which affects only the dependencies of your own project.

I am proposing augmenting the `pubspec.yaml` syntax to add a new `dependency_overrides` section *as a child of any dependency*, so that the *dependencies of the dependency* can be forced to a specific version.

The "repro" is the bug report I linked. Basically, tyr depending upon `firebase_admin: ^0.2.0` and `http: ^1.0.0` in the same project, and you will see the problem. `firebase_admin` is compatible with `http: ^1.0.0`, but its own dependency on this is `http: ^0.13.0`, so you cannot use  if your project needs `http: ^1.0.0` (possibly because another dependency you are using depends upon it), you can't build your project, even though all the code would compile and work just fine with `http: ^1.0.0`.

Therefore, currently the only fix is to fork the `firebase_admin` project, change your fork's dependency to `http: '>=0.13.0 <2.0.0'`, then change your project to depend upon your fork. This is a pain in the butt, and leads to a lot of different projects having to fork the same project just to get their build dependencies to resolve.

What I am proposing is allowing the user to override the version requirement of *any dependency of any dependency of your project*. This is not what `dependency_overrides` currently does. Look where I wrote `dependency_overrides` in the yaml example I gave. Currently you can't use `dependency_overrides` there. I am proposing that it should be allowed, for dependency-specific transitive dependency overrides.

**Comment by devoncarew** [comment]
> @devoncarew Correct, based on the current usage of `dependency_overrides`, which affects only the dependencies of your own project.

To be clear, is _does_ affect the transitive dependencies. `dependency_overrides` can be and is used to work around the problem of a dep not updating one of it's own dependencies. `dependency_overrides` lets you ignore the version constraints that your pubspec + transitive deps would otherwise impose on that dep.

https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages#i-see-issues-through-one-of-my-dependencies-but-they-cant-immediately-release-a-new-version mentions this as a way to get around periodic issues with flutter pinned packages.

**Comment by lukehutch** [comment]
> To be clear, is _does_ affect the transitive dependencies.

Ah, OK, thank you for explaining that. I jumped to the conclusion that I couldn't override dependencies in other packages using a directive in my own package. Thanks, I'll close this!
