### ISSUE TITLE
[analyzer] Report of `#const_with_type_parameters` with raw type but not alias, and compiler still works

### ISSUE THREAD

**Issue by mattrberry** [dart-lang/sdk#55459]
```dart
class Wrapper<T> {
  const Wrapper();
}
typedef TD = A Function<A>(A);
const token1 = Wrapper<TD>();
const token2 = Wrapper<A Function<A>(A)>();

void main() {
  print(token1);
  print(token2);
}
```

Prints
```
Instance of 'Wrapper<<T1>(T1) => T1>'
Instance of 'Wrapper<<T1>(T1) => T1>'
```

Produces error:
```
A constant creation can't use a type parameter as a type argument. #const_with_type_parameters
A constant creation can't use a type parameter as a type argument. #const_with_type_parameters

const token2 = Wrapper<A Function<A>(A)>();
                       ^             ^
```

It seems odd to me that the analyzer
- cares about the type param in the constant declaration but not for the type alias
- reports an error yet the compiler still succeeds

SDK version: 3.3.3

**Comment by lrhn** [comment]
Seems like an analyzer bug. There is nothing wrong with the type argument to `Wrapper`, it's a valid constant type term.

**Comment by srawlins** [comment]
The ability to "use a generic function type as a type argument" was [introduced in Dart 2.14](https://github.com/dart-lang/language/blob/main/accepted/2.14/small-features-21Q1/feature-specification.md). If you prepend your example with `// @dart=2.13`, the VM also gives errors:

```none
a.dart:7:16: Error: A generic function type can't be used as a type argument.
Try using a non-generic function type.
const token1 = Wrapper<TD>();
               ^
a.dart:8:16: Error: A generic function type can't be used as a type argument.
Try using a non-generic function type.
const token2 = Wrapper<A Function<A>(A)>();
               ^
```

I'm not sure how related that is... but it seems maybe we didn't finsh implementing that feature. I thought this issue might be related to the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/main/accepted/2.15/constructor-tearoffs/feature-specification.md), introduced in 2.15, in which type variables became potentially constant:

> If _T_ denotes a type variable then _T_ is a potentially constant type expression, and a potentially constant expression.

But the VM accepts the program with `// @dart=2.14` (pre-constructor-tearoffs), so 🤷 .
