### ISSUE TITLE
Failures on Ensure that dtd handles relative paths correctly.

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#55476]
There are new test failures on [Ensure that dtd handles relative paths correctly.](https://github.com/dart-lang/sdk/commit/ba8306735d7efa8aabfbf4d8f9a618bd00bfbcbd).

The tests
```
pkg/dtd/test/file_system_service_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win-arm64
unittest-asserts-release-win-x64
```

Example log: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8750582350503425889/+/u/test_results/new_test_failures__logs_

**Comment by DanTup** [comment]
I hit these failures locally today and included a fix in https://dart-review.googlesource.com/c/sdk/+/378461, so hopefully they'll be green once that lands.
