### ISSUE TITLE
Failures on Reland "[vm] Implement typed data view GetIndexed in flow graph builder"

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#55497]
There are new test failures on [[infra] Remove VM-specific weak mode testing on the CFE...Reland "[vm] Implement typed data view GetIndexed in flow graph builder"](https://github.com/dart-lang/sdk/compare/ad95bb6f89eb3aa36b129320fba47c29574b7084~...ce840baa4c6ee2b8b9ba74baf251bd0f5445ebfc).

The tests
```
lib/typed_data/typed_data_load2_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-optimization-level-linux-release-x64
```

**Comment by alexmarkov** [comment]
Duplicate to https://github.com/dart-lang/sdk/issues/55493.
