### ISSUE TITLE
Not always able to rename `extension type E` using "rename symbol"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#55495]
I am not sure if this is specific to VSCode, I'd imagine it's an LSP/Analysis server thing.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.86.0

App: Visual Studio Code
App Host: desktop
Version: mac 1.88.1

Workspace type: Dart (LSP)

Dart (3.3.1): /opt/homebrew/Caskroom/flutter/3.19.3/flutter/bin/cache/dart-sdk
Flutter (3.19.3): /opt/homebrew/Caskroom/flutter/3.19.3/flutter (No device)

```

</details>

```dart
extension type Foo(int v) {
  Foo.bar() : this(0);

  Foo get baz => Foo(0);
}
```

Imagine I want to rename this from `Foo` to `Bar`, so I right-click `Foo` and hit "rename symbol".

It works sometimes, but not other times - here is what I see:

1. ✅ Right-click `Foo` in `extension type Foo(int v) { ... }`:

    ![](https://github.com/dart-lang/sdk/assets/168174/8edcd012-d311-45e2-81c6-5e081d1543da)

2. ❌ Select `Foo` first, and then right-click/rename:

    Note that `foo` is selected, unlike in (1) where I've highlighted/selected nothing:

    ![](https://github.com/dart-lang/sdk/assets/168174/4e6c8e84-d7bc-441b-bfe7-e54db06d511e)
    
    `v` is accidentally selected as what I intended to rename, instead of `Foo`:
    
    ![](https://github.com/dart-lang/sdk/assets/168174/a860532c-e26c-4ccb-a6ad-8fc2a9f53ec6)

3. ❌ Right-click `Foo` in `Foo.bar() : this(0)`:

    ![](https://github.com/dart-lang/sdk/assets/168174/b9a1888c-d534-43c2-bde4-a8fcb21d29e4)

    `bar` is accidentally selected as what I intended to rename, instead of `Foo`:

    ![](https://github.com/dart-lang/sdk/assets/168174/00ebfcec-c9af-4511-938c-2e26d9d5f8c7)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
2. It looks that LSP version leans right.
3. Renaming the constructor instead of the class in `Foo.bar() : this(0)` is a feature.

**Comment by matanlurey** [comment]
> 3\. Renaming the constructor instead of the class in `Foo.bar() : this(0)` is a feature.

Ah interesting, it looks like this is how it works for _all_ constructors.

I do think it's confusing though, for default constructors it works as expected:

![Screenshot 2024-04-17 at 2 33 04 PM](https://github.com/dart-lang/sdk/assets/168174/9cff929b-8eeb-4e12-8382-5b21745c26b2)

But selecting the class prefix in a named constructor assumes I want to rename the constructor:

![Screenshot 2024-04-17 at 2 33 32 PM](https://github.com/dart-lang/sdk/assets/168174/5296fe52-6283-4a5e-8cda-5bbdef04a464)

**Comment by bwilkerson** [comment]
I agree that it's a little confusing, but it's the best UX we could find for renaming the unnamed constructor. And making it work differently, depending on whether the constructor was named or not, seemed even more confusing.

Suggestions for a better UX are welcome.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/363481

**Comment by matanlurey** [comment]
> I agree that it's a little confusing, but it's the best UX we could find for renaming the unnamed constructor. And making it work differently, depending on whether the constructor was named or not, seemed even more confusing.
> 
> Suggestions for a better UX are welcome.

I think selecting the LHS should select the class not the constructor. I also don't think it's a huge problem that needs solving.

Thanks!

**Comment by matanlurey** [comment]
Appreciate the quick fixes!
