### ISSUE TITLE
API doc issue: The "dart:html" library page should probably say to start migrating to "packages:web"

### ISSUE THREAD

**Issue by dtonhofer** [dart-lang/sdk#55491]
At the page

https://api.dart.dev/stable/3.3.3/dart-html/dart-html-library.html

no mention is made of deprecation. However at

https://dart.dev/libraries/dart-html

we find the following message:

> dart:html is being replaced with [package:web](https://pub.dev/packages/web). Package maintainers should migrate to package:web as soon as possible to be compatible with Wasm. Read the [Migrate to package:web](https://dart.dev/interop/js-interop/package-web) page for guidance.

That warning should probably be reflected in the API docs, too.

**Comment by devoncarew** [comment]
cc @srujzs
