### ISSUE TITLE
[CP] Update with DevTools that does not fail heap snapshotting.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#55509]
### Commit(s) to merge

Fix on DevTools master: https://github.com/flutter/devtools/pull/7597
DevTools master will be released to Dart SDK main with its normal process, at the end of the month. 

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/363642

### Issue Description

DevTools fails when user triggers memory snapshot of the connected application. The issue is flaky and is caused by snapshot deserialization process in vm_service. vm_service is fixed, DevTools is updated with new vm_service this issue is about patching dart SDK with fixed DevTools.

https://github.com/dart-lang/sdk/issues/55475

### What is the fix

Upgraded version of vm_service in DevTools from 14.2.0 to 14.2.1. 14.2.0 contained wrong parsing. 
Fix in vm_service:  https://dart-review.googlesource.com/c/sdk/+/363120

### Why cherry-pick

DevTools sometimes fails to snapshot memory with vm_service to 14.2.0

### Risk

No visible risk. vm_service 14.2.1 passed regression tests and manual tests with devtools.

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55475

**Comment by jacob314** [comment]
LGTM

**Comment by polina-c** [comment]
Thank you!
Fixed description and replied https://github.com/dart-lang/sdk/issues/55475#issuecomment-2065627412

**Comment by sortie** [comment]
https://github.com/dart-lang/sdk/issues/55475#issuecomment-2064691121 points out the devtools CP build somehow still contains vm_service 14.2.0 and a new CP build would be required.

**Comment by polina-c** [comment]
> [#55475 (comment)](https://github.com/dart-lang/sdk/issues/55475#issuecomment-2064691121) points out the devtools CP build somehow still contains vm_service 14.2.0 and a new CP build would be required.

Nope, it does not. That comment was made before I created CP to point out to the problem of the existing version of DevTools for beta, explaining why we need CP. There are two CPs in this issue: one for Dart SDK and one for DevTools.

**Comment by vsmenon** [comment]
lgtm
