### ISSUE TITLE
[breaking change] Change parameter type of `importModule` from `String` to `JSAny`

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#55508]
### Change Intent

`dart:js_interop`'s [`importModule`](https://api.dart.dev/main/215323ad51930a58fd1e58df885aa1e354067e5e/dart-js_interop/importModule.html) should accept a `JSAny` instead of a `String`.

Original issue here: https://github.com/dart-lang/sdk/issues/55429

### Justification

JavaScript's [`dynamic import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) function can accept more than just `String`s. See https://tc39.es/proposal-dynamic-import/#sec-import-call-runtime-semantics-evaluation and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#importing_modules_with_a_non-literal_specifier. One key usage is the ability to pass a `TrustedScriptURL`, allowing a sanitized specifier to be imported.

### Impact

Minimal. There's only one usage in GitHub, and no usages in the SDK, google3, or Flutter.

### Mitigation

The fix is to convert the `String` to a `JSString` using `toJS` e.g.

`importModule('module')` -> `importModule('module'.toJS)`

I don't believe mitigation is possible due to it being a parameter and not a return type. There's no way to "test" that a function takes in a specific type. One possibility that may work if it only needs to be mitigated for DDC and dart2js is to use `dynamic` to pass the value to `importModule` e.g.

```dart
importModule('module' as dynamic);
```

Since `JSString` is a Dart `String` when compiling to JS, this will avoid the breakage. This won't work for mitigating the issue for dart2wasm.

### Change Timeline

This is a simple change and should go in Dart 3.5. No specific beta is planned yet.

### Associated CLs

WIP CL here: https://dart-review.googlesource.com/c/sdk/+/363504

**Comment by srujzs** [comment]
@itsjustkevin FYI - I just sent out an email to announce@dartlang.org for both this and https://github.com/dart-lang/sdk/issues/55267.

**Comment by kevmoo** [comment]
Looks good to me!

**Comment by itsjustkevin** [comment]
@Hixie @grouma @vsmenon please take a look.

**Comment by sigmundch** [comment]
lgtm as well

**Comment by grouma** [comment]
LGTM

**Comment by Hixie** [comment]
no objection

**Comment by itsjustkevin** [comment]
@vsmenon ping

**Comment by vsmenon** [comment]
lgtm

**Comment by itsjustkevin** [comment]
This breaking change has been approved
