### ISSUE TITLE
[frontend_server] Enable native-assets dill compilation without dart program

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55503]
In Flutter, we want to compile the dart program and the `native_assets.yaml` into kernel files separately, so that the AOT information from the Dart compilation can be used before the `native_assets.yaml` is created.

* https://github.com/flutter/flutter/issues/146270

Flutter uses the resident_server.

Currently, the resident server cannot compile without an entry point. Neither in single-run mode, nor in stdin-protocol mode.

For single shot mode we likely need an extra flag, such as `--no-entry-point` to eager compile with no entry point:

https://github.com/dart-lang/sdk/blob/3eb9f5374e71397130722e7ed94f489343823450/pkg/frontend_server/lib/starter.dart#L100-L105

And for compilation requests for a running server, we'd need to modify the protocol to accept a newline immediately after 'compile' in the stdin protocol:

https://github.com/dart-lang/sdk/blob/3eb9f5374e71397130722e7ed94f489343823450/pkg/frontend_server/lib/frontend_server.dart#L1308-L1311

cc @jensjoha

**Comment by dcharkes** [comment]
That makes sense. 👍 

I have no idea if we are ever in a situation where we would have two different byproducts that we want to compile in a single invocation. But assuming no, specifying byproduct-only makes more sense than not-main-thing.

Startup / single shot commandline API:

* (already existing) `--native-assets=<file>` sets the side product for when compiling the full thing, either immediately or with subsequent `compile`s over the protocol.
* (new option A) `--native-assets-only` (no file), should be supplied together with `--native-assets=<file>`
* (new option B) `--native-assets-only=<file>`

The protocol

* (already existing) `native-assets <file>` sets the side product for when compiling the full thing with subsequent `compile`s.
* (new option A) `native-assets-only` after already having sent `native-assets <file>` before
* (new option B) `native-assets-only <file>`

@jensjoha any preference for whether we add the `<file>` to `native-assets-only`, or whether it should be supplied with the already existing flag and command?

**Comment by jensjoha** [comment]
Already having `--native-assets=<file>` and `native-assets <file>` I suppose the `native-assets-only` without file makes more sense. I don't immediately have strong feelings about it though ;)

**Comment by dcharkes** [comment]
> Already having `--native-assets=<file>` and `native-assets <file>` I suppose the `native-assets-only` without file makes more sense. I don't immediately have strong feelings about it though ;)

I had the same, not so strong, feelings. 👍

**Comment by lrhn** [comment]
Compiling without an entry point could affect tree shaking (basically make it impossible, it has no root). 
It's that a problem?

**Comment by dcharkes** [comment]
> Compiling without an entry point could affect tree shaking (basically make it impossible, it has no root). It's that a problem?

"Compiling" is a bit of a strange word here. We're creating an encoding of the `native_assets.yaml` in a dart library.

https://github.com/dart-lang/sdk/blob/637f3b216a85759d379af044dd88ac89ef922444/pkg/vm/lib/native_assets/synthesizer.dart#L46-L55

And yes, this encoding only uses VM-recognized classes (list, string, map, and pragma), so that tree-shaking of the Dart program this special library is concatenated to can be read by the VM.
