### ISSUE TITLE
No published analyzer available for language version 3.5.0

### ISSUE THREAD

**Issue by deminearchiver** [dart-lang/sdk#55504]

**Comment by srawlins** [comment]
@scheglov

**Comment by scheglov** [comment]
Analyzer cannot be published right now, because it depends on
```yaml
  macros: '>=0.1.0 <0.1.1'
```
Which, I think, is not published yet.
@jakemac53

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/364968
