### ISSUE TITLE
What if VScode would suggest the `~/` operator if the `/` operator does not exist?

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#55512]
It would be great if VScode would suggest the `~/` operator if the `/` operator does not exist.
This would be great when working with `Duration` for example.

you can have a look at the conversation here with the Flutter team:
https://github.com/flutter/flutter/issues/146997

**Comment by bwilkerson** [comment]
Where are you proposing that the language server suggest `~/`? Are you thinking of this as a code assist (quick fix)?

**Comment by stephane-archer** [comment]
Here or the quick fix:
<img width="656" alt="Screenshot 2024-04-19 at 21 32 47" src="https://github.com/dart-lang/sdk/assets/2981437/a59fff42-06af-4549-becb-265cf613a088">
I'm not sure what is the best/easiest.

**Comment by FMorschel** [comment]
I opened a CL for this https://github.com/dart-lang/sdk/issues/55512

**Comment by FMorschel** [comment]
Here is my CL for this https://dart-review.googlesource.com/c/sdk/+/388074
