### ISSUE TITLE
Make `dart compile wasm -O4` not omit explicit type checks

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55516]
Now that we have optimized `is` / `as` type checks using short & fast cid-range checks, we may consider no longer omitting explicit `as` checks.

This will naturally result in worse size & performance, so we should investigate the differences and see what can be done about it.

One area where this will show up is in the interator implementations as they have as checks in them, but they can be optimized to null checks.

**Comment by mnordine** [comment]
If your investigation yields a decision to keep them for `-O4`, will there still be a flag to omit them?

**Comment by mkustermann** [comment]
> If your investigation yields a decision to keep them for -O4, will there still be a flag to omit them?

Right now it's not explicitly exposed by `flutter build web` or `dart compile wasm`, but one could use it via `dart compile wasm --extra-compiler-option=--omit-explicit-checks`.

(Notice that `dart2js -O4` drops *implicit* checks but keeps *explicit* checks. So this issue is tracking us to align with dart2js)

**Comment by sigmundch** [comment]
Cool to see this @mkustermann!

About the iterator example you mention. Are you referring to covariant checks? Or actual explicit `as` expressions? I ask also for the purpose of aligning with dart2js: `dart2js -O3` not only omits implicit downcasts from dynamic, but also implicit parameter checks (which can come from a dynamic invocation or an explicit covariance check)

**Comment by rakudrama** [comment]
@sigmundch The optimization is for the explicit `as` used in many `Iterator.current` implementations ([example](https://github.com/dart-lang/sdk/blob/8c26c35950a5f23c95a528b53d8aa7ce13513856/sdk/lib/internal/iterable.dart#L342))

```dart
  E? _current;
  ...
  E get current => _current as E;
```

The transform is to change  `_current as E` to `_current == null ? _current as E : _current`, since the only value that needs checking when casting from `E?` to `E` is `null`.

dart2js does this in the SSA builder.

**Comment by mkustermann** [comment]
After many optimizations to the RTT data structures and `is` / `as` implementation this has been completed.

Dart2wasm should now always perform user-written `as` checks, even in `-O4` mode.
