### ISSUE TITLE
What do you keep some asynchronous file I/O methods that you recommend avoiding in your lint rules?

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#55527]
In your linter rules, you recommend not using some async functions and using their synchronous version. Why then keep them in the standard library?
https://dart.dev/tools/linter-rules/avoid_slow_async_io
```
AVOID using the following asynchronous file I/O methods because they are much slower than their synchronous counterparts.

Directory.exists
Directory.stat
File.lastModified
File.exists
File.stat
FileSystemEntity.isDirectory
FileSystemEntity.isFile
FileSystemEntity.isLink
FileSystemEntity.type

```

**Comment by julemand101** [comment]
I can still see them useful in case you are dealing with network shares where those actions would again be something that can be time consuming enough for using the async version. Could also be a benefit if you are doing some of those actions against a lot of files and still wanted to execute some events on the micro-event queue while this is going on.
