### ISSUE TITLE
[dart2wasm] Get rid of the warning that compiling to WasmGC is experimental.

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#55526]
https://github.com/dart-lang/sdk/blob/1998c87bff783f39ebc7db4e037280e8da488c8c/pkg/dartdev/lib/src/commands/compile.dart#L695-L697

We are no longer experimental.

**Comment by osa1** [comment]
Another mention of "experimental" here: https://github.com/dart-lang/sdk/blob/c78ad94e90f80a056203c67186d0ec2682bd7dcf/pkg/dartdev/lib/src/commands/compile.dart#L542-L543

**Comment by kevmoo** [comment]
We should ditch both!

**Comment by kevmoo** [comment]
@mit-mit is cranking on https://dart-review.googlesource.com/c/sdk/+/365462
