### ISSUE TITLE
[dart:js_interop] Can't pass an function reference to external function when assertions are enabled.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#55549]
For example:
```dart
import 'dart:js_interop';

@JS('set_property')
external void _setProperty(JSObject object, String name, ExternalDartReference? value);

void setProperty(JSObject object, String name, Object? value) {
  _setProperty(object, name, value?.toExternalReference);
}
```
throws this (DDC, dart2js)
```
Assertion failed: "Dart function requires `allowInterop` to be passed to JavaScript."
```

Dart SDK version: 3.5.0-edge.936b3a2ccf38aaf8ab3cd7e50f84231a053d669c (main) (Wed Apr 10 23:48:20 2024 +0000) on "windows_x64".

**Comment by srujzs** [comment]
This was needed with previous versions of interop as we didn't have enough static type information. I think we can safely disable the checks for `dart:js_interop` methods. While it's possible users might try to use this Dart function in JS, that's much less likely than wanting to pass a Dart function around using `ExternalDartReference`.
