### ISSUE TITLE
proposal: noop_primitive_operations allows empty string interpolations

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#55541]
Would it be reasonable to allow the following pattern:

```dart
const message = '' // LINT
  'Warning: This is a test message.\n'
  '\n'
  'Next time, it won't be a test!';
```

Basically, using a leading empty string literal for dart format compliance :)

**Comment by matanlurey** [comment]
CL out: https://dart-review.googlesource.com/c/sdk/+/364204.

**Comment by bwilkerson** [comment]
Thanks. Looking at the CL made me think of a couple of cases that I thought might be better to discuss here than in the issue.

The overarching question is whether there's ever value in flagging empty adjacent strings.

For example, if the primary goal is to allow empty strings to improve formatting, should we
- only allow an empty string at the beginning or end of the list?
- only allow an empty string if it's on a different line that the previous or next string?
- only allow one empty string (so `'' '' 'a'` would still be flagged)?

**Comment by matanlurey** [comment]
I'm supportive of reducing to [allowing] "an empty string at the beginning or end of a list of strings".

Re: different line, I think this is dartfmt-'s territory and I'd prefer not to think about it at all.

**Comment by bwilkerson** [comment]
> Re: different line, I think this is dartfmt-'s territory ...

That's reasonable.

**Comment by matanlurey** [comment]
Closed in https://github.com/dart-lang/sdk/commit/6f14fa12e624855af64a4b3ccbf6f24adcb8cc77.
