### ISSUE TITLE
should ignore statements implicitly apply to augmentations?

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#55540]
In https://github.com/dart-lang/linter/issues/4943#issuecomment-2070358120, @lrhn noticed that we should define semantics for ignores vis a vis augmentations:

> More interesting question is whether an // ignore on the parent declaration should implicitly apply to the child too, since the author has shown intent to ignore that lint for this declaration.
> 
> I could go either way on that. The easiest is to require an // ignore for every occurrence that needs to be ignored.

My inclination is to not implement any kind of inheritance ad require them on every occurrence but I'd be very curious to hear what other folks think.

/fyi @jakemac53 @bwilkerson @munificent @natebosch @srawlins

**Comment by bwilkerson** [comment]
An `// ignore_for_class` comment would presumably apply only to the class augmentation being written by the macro and not to the whole class, so (a) it's still a lexical range and (b) it isn't changing the semantics of an `// ignore` comment. The two things that I think are being suggested are to change the semantics of `// ignore` and to have an ignore comment on a base class implicitly apply to augmentations (or maybe even the other way around). I don't think we want to make either of those two changes.

(I do have a concern about the potential number of new ignore comment forms something like `// ignore_for_class` would require, but I don't have any problem with the general concept and I assume we can fine-tune the actual design.)

**Comment by jakemac53** [comment]
Or possibly `// ignore_for_library`, which would apply to all augmentations/parts of the library?

In general, I do not think most lints should apply to macro generated code though. It is not reasonable to expect macro generated code to conform to your projects lints or style.

The exception would be for security/correctness related lints.

**Comment by lrhn** [comment]
What @jakemac53 says: Macro generated code *is* generated code, and shouldn't be linted the same way as user written code.
It's effectively *third-party* code that just happens to belong to the same package.

**Comment by srawlins** [comment]
+1 to `// ignore_for_library`.

I think about this differently though, just for two cents: it is reasonable to expect a macro author to want the same static analysis in their macro-generated augmentations (`avoid_types_as_parameter_names` ("whoops!"), `await_only_futures` ("oh, I see"), `collection_methods_unrelated_type` ("good catch!"), etc). An exception then might be style-motivated rules.

> It's effectively third-party code that just happens to belong to the same package.

I agree, but hope we can reliably determine whether the augmentations are being generated into _the same package_ as where the macro definition lives, to support the above author experience in their test cases and examples. Another example of this motivation is errors and warnings: we do not report errors and warnings in third party code (e.g. in your pub dependencies), but it is reasonable to expect a package author to be informed when they are generating code that newly violates `deprecated_member_use` or `deprecated_colon_for_default_value`, etc.

**Comment by lrhn** [comment]
> I agree, but hope we can reliably determine whether the augmentations are being generated into the same package as where the macro definition lives

The macro code belongs to the package of the library that it is generated into a part of.
All the fiddling with `dart-macro+package:` URIs was to give the generated code a unique location that was also able to be recognized as in the same package.

I don't expect to support a library having code that belongs to different packages. 
(If for no other reason, then because the two packages might have different default language versions.)

**Comment by davidmorgan** [comment]
Not quite sure what's left to do for this issue:

Did it turn into a feature request for `// ignore_for_library`?

**Comment by bwilkerson** [comment]
I think we don't want to change the definition of a simple `ignore` comment.

There has been discussion of adding both `ignore_for_class` and `ignore_for_library` comments, but I don't believe that either has been discussed enough to be able to decide whether we should implement the feature or what those features would look like. And I don't think we can even know for sure whether we need either of these until we've resolved the question of which diagnostics (errors, warnings, and lints), if any, are going to be reported against macro generated code.

Personally I'd like to close this issue (to change `ignore`) as not-planned. Then I'd like us to resolve the open question about reported diagnostics. Then, if there's still a use case for other styles of `ignore_x` comments we should open issues (one per style) to discuss the semantics and determine feasibility.

(Handling of `ignore` comments currently has a very nice property, which is that the comments are lexically scoped, making it inexpensive to apply the ignores. If comments start impacting code outside the file in which they appear then there are some performance implications that we'll also need to consider.)

**Comment by pq** [comment]
I'm in favor of closing this issue too. Feel free to re-open if anyone wants to continue the conversation. Thanks!
