### ISSUE TITLE
Possible bug in diagnostics for `doNotSubmit`

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#55558]
I expected to have a diagnostic produced by the following code, but there is none.

```dart
import 'package:meta/meta.dart';

@doNotSubmit
void a() {}

void b() => a();
```

Should there be one?

**Comment by bwilkerson** [comment]
@matanlurey

**Comment by matanlurey** [comment]
@srawlins thoughts?

**Comment by srawlins** [comment]
I like the sentiment that `doNotSubmit` might need to be used locally. This is similar to how we don't report usage of a `@deprecated` element from within another `@deprecated` element.

But that exact shape might not be helpful here. Do you know, specifically for `solo` in package:test, @matanlurey ?

**Comment by matanlurey** [comment]
I think that, for say:

```dart
void test({@doNotSubmit bool solo = false}) {
  if (solo) { ... }
}
```

... this should work out of the box (and does today). The question is if this should be flagged:

```dart
void test({@doNotSubmit bool solo = false}) {}

// Same library.
void megaTest() {
  test(solo: true);
}
```

**Comment by bwilkerson** [comment]
What is the use case for allowing it to be executed outside of another function that's also marked as `@doNotSubmit`?

If there isn't one, it might be better to be more restrictive in v1 and to relax it when we have a use case. Making a check like this more restrictive can be a huge breaking change, and sometimes impossible.

**Comment by matanlurey** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/364382.
