### ISSUE TITLE
Add TargetKind: optionalParameter

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#55567]
I think there are many annotations that are valid on parameters, but only on _optional_ parameters (be they named or positional):

* `@deprecated` (lives in the dart:core)
* `@doNotSubmit`
* `@experimental`
* `@internal`
* `@visibleForTesting`

These all kind of fit a "do not use unless you really need to" or "do not use except in use cases fitting a certain requirement".

So I propose `TargetKind.optionalParameter`.

Without this TargetKind, we have to double the work in these situations: include `TargetKind.parameter` for such an annotation, _and_ write explicit code (e.g. in BestPracticesVisitor) that then reports usage on a required parameter.

**Comment by bwilkerson** [comment]
I think that's reasonable, and it fits with the general design of the constants in the class.

There's no reason why we can't add a `TargetKind.parameter` later if we have a use case for it.
