### ISSUE TITLE
Inconsistent runtime behaviour with `dynamic` type on web and native

### ISSUE THREAD

**Issue by hugovangalen** [dart-lang/sdk#55570]
(Edit: The original title was "Potential type system bypass with Map lookups on Web platform" when I erroneously thought this pertained to Maps, but it's specifically related to the `dynamic` type so updated the title.)

I am not sure whether this is a feature or a bug. Considering Dart is supposed to have a sound type system, I am leaning towards a bug, especially because there is a difference in runtime operation between platforms right now (I am comparing native and web).

### THE CODE
Consider the following test-case:
```
void main() {
  final Map<String,dynamic> test = Map.from( {
      "value1": 1,
      "value2": "1"
  });

  int value1 = test['value1'];
  int value2 = test['value2']; // this would trigger rte
  
  print( value1.runtimeType );
  print( value2.runtimeType );
  
  print( value1.compareTo( value2 ) );
}
```

### EXPECTED BEHAVIOUR
As you would expect this fails with a run-time exception:
```type 'String' is not a subtype of type 'int'```

### WHAT HAPPENS ON WEB
However, on web, this exception is not triggered and proceeds to comparing the values and proceeds to print out the following to the console:

```
int
int
-1
```

This was doing my head in for way too long until I started stepping through the compiled JavaScript and noticed that a value contained a string literal and not a numeric value.

### WORKAROUND
As a workaround, I can change it to the following, which /does/ trigger a runtime exception and so prevents any faulty equality checks later.

```
int value2 = test['value2'] as int; // this does generate rte
```
That throws the following exception:
```
Rejecting promise with error: TypeError: "1": type 'String' is not a subtype of type 'int'
```

FWIW I am using Dart 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "linux_x64", my locale is en_US.UTF-8 and my browser is Chrome.

**Comment by navaronbracke** [comment]
I believe this is working as intended.

If you change 

```
  final Map<String,dynamic> test = Map.from( {
      "value1": 1,
      "value2": "1"
  });
```

to use `Object?` instead of `dynamic`, you should get a type error.

```
  final Map<String, Object?> test = Map.from( {
      "value1": 1,
      "value2": "1"
  });
```

When you use `dynamic`, type checks are omitted, so the assignment to `int value2 = test['value2'];` is actually unchecked.

**Comment by hugovangalen** [comment]
> When you use `dynamic`, type checks are omitted, so the assignment to `int value2 = test['value2'];` is actually unchecked.

Interesting. This isn't unchecked on native. Are you implying that the problem lies in the native runtime?

This for example throws an RTE on native (Linux command line) yet no RTE on web:
```
    dynamic string3 = "3";
    int value3 = string3;
```
Regardless, it is inconsistent. I believe the exception should happen either in both, or in niether.

(Also, it appears my title for this bug is incorrect as I now realise this doesn't affect Maps. It boils down to "Inconsistent runtime behaviour with `dynamic` type on web and native" and I will update that accordingly.)

**Comment by mraleph** [comment]
This is working as intended: `dart2js` compiler omits implicit type checks at `-O3` optimization level or above. (and `dart2wasm` even omits _explicit_ type checks). Native compilers never omit type checks.

So you need to write all your type checks explicitly if you don't want them to be omitted (e.g. if they are validating input data from JSON).

**Comment by hugovangalen** [comment]
Okay thanks for clearing that up!
