### ISSUE TITLE
Possible bug in diagnostics for `mustBeConst`

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#55573]
I would expect the following code to be valid, but it generated a diagnostic claiming that the argument to `g` isn't a constant expression, even though it is a constant expression:

```dart
import 'package:meta/meta.dart';

void f() {
  g(const C());
}

void g(@mustBeConst C c) {}

class C {
  const C();
}
```

Is that behavior intentional? Is it intended that only uses of const variables is allowed?

**Comment by bwilkerson** [comment]
@mosuem

**Comment by mosuem** [comment]
I don't think that's intentional, let me check.

**Comment by dnys1** [comment]
The linter doesn't seem to consider const expressions as valid, only const variable references:

```dart
import 'package:meta/meta.dart';

class A {
  A(@mustBeConst this.value);

  final B value;
}

class B {
  const B();
}

const value = B();
final valid = A(value);
final invalid = A(const B());
```

<img width="961" alt="Screenshot 2024-09-30 at 9 16 16 AM" src="https://github.com/user-attachments/assets/08104c07-9e2c-4396-a216-524b07ca3090">

**Comment by mosuem** [comment]
The code for recognizing constness uses the [`ConstantEvaluator`](https://github.com/dart-lang/sdk/blob/7bb6899a2c493b7946ce7ac6290c43050e6068b1/pkg/analyzer/lib/src/dart/ast/constant_evaluator.dart#L12), which only resolves primitives. Looking at the tests, it seems to operate on the parsed non-resolved AST, meaning it cannot handle things like `SimpleIdentifiers` etc.

Is there another `ConstantEvaluator` which I could use? This use case doesn't even need the actual value, just to know if it is `const` or not. The current solution of the `ConstantEvaluator` + some [manual patch code](https://github.com/dart-lang/sdk/blob/7bb6899a2c493b7946ce7ac6290c43050e6068b1/pkg/analyzer/lib/src/error/const_argument_verifier.dart#L117) seems to be less than ideal.

Any ideas @bwilkerson @srawlins @scheglov ?

**Comment by bwilkerson** [comment]
Would the method `Expression.inConstantContext` satisfy the requirement?

**Comment by mosuem** [comment]
I think it does not - 16/40 [test cases](https://github.com/dart-lang/sdk/blob/bc15ff6d530a4bb0ae16eb85494970700c8d4984/pkg/analyzer/test/src/diagnostics/non_const_argument_for_const_parameter_test.dart#L4) fail when relying solely on `Expression.inConstantContext`.

**Comment by bwilkerson** [comment]
Based on a quick glance at the tests, and having no idea which tests are failing (so not a very thorough investigation), I'm guessing that the problem is references to simple identifiers. The reference doesn't have to be in a constant context, it just has to be a reference to a constant variable. For that, all you need to do is get the element, ensure that it's a variable, and ask whether the variable was declared as being `const`.

(Is the algorithm that you're trying to implemented documented somewhere? I might be able to give better answers if I understood the problem better.)

**Comment by mosuem** [comment]
That sounds good - I will try to implement a custom set of rules to catch the cases as good as possible. I filed https://dart-review.googlesource.com/c/sdk/+/387721.

> Is the algorithm that you're trying to implemented documented somewhere?

It is not - the idea is just to recognize `const` parameters as well as possible, with the idea that those arguments can then possibly be recorded at compile time.
