### ISSUE TITLE
Analyzer and compiler disagree on whether extension type implementing Future is FutureOr

### ISSUE THREAD

**Issue by dgreensp** [dart-lang/sdk#55578]
An extension type on Future that implements Future can be assigned to FutureOr, as far as the analyzer is concerned, but not as far as the compiler is concerned:

```dart
import "dart:async";

void main() async {
  // analyzer is ok with assigning a `Foo` to `FutureOr<int>`;
  // compilers (compileDDC, dart2js) give an error here
  final FutureOr<int> x = Foo(Future(() => 123));
  // use it
  print(x is Future<int> ? (await x) : x);
}

extension type Foo(Future<int> rep) implements Future<int> {}
```

Personally, I would prefer it be allowed, if it isn't too much trouble.

**Comment by johnniwinther** [comment]
cc @eernstg @chloestefantsova

**Comment by eernstg** [comment]
The type `Foo` is a subtype of `Future<int>` which is a subtype of `FutureOr<int>`, and there should not be an error at the initialization of `x`.

**Comment by eernstg** [comment]
@sgrekhov, I think it would be useful to take a look at this and see why we don't have a test that catches this case. I noticed that the other union type does not get the same treatment:

```dart
// ignore_for_file: unused_local_variable

void main() async {
  final int? iq = Bar(42);
  int j = iq is int ? iq : 24; // OK.
}

extension type Bar(int _) implements int {}
```

**Comment by eernstg** [comment]
Whoosh! That was fast, @chloestefantsova! 😄
