### ISSUE TITLE
Operator overloading doesn't work as expected for * operator.

### ISSUE THREAD

**Issue by prabinlamsal19** [dart-lang/sdk#55619]
This tracker is for issues related to:

* Dart analyzer and linter
```dart
extension type HeightWidth(num size) implements num {
  HeightWidth operator /(num denominator) {
    final b = size / denominator;
    return HeightWidth(size / denominator);
  }
  HeightWidth operator *(num multiplier) {
    return HeightWidth(size * multiplier);
  }
  HeightWidth times(num multiplier) {
    return HeightWidth(size * multiplier);
  }
}

final HeightWidth d_margin05 = d_margin1 / 2;          
   // The / operator successfully works

final HeightWidth d_margin1025 = d_margin1 *1.25;
    // This gives syntax error as it returns a double, not HeightWidth


final HeightWidth d_margin105 = d_margin1.times(1.5); 
 //Works well as well 
```

There is no reason why we couldn't override the * operator.  The default ' * ' implementation returns a double. My theory is that this default ' * '  is being used here instead of the overloaded  ' * '. 
This is the problem. 

In case of ' / ' , even though the code is the same, it works fine and returns HeightWeight type as output.

**Comment by eernstg** [comment]
I can't reproduce this behavior using this program (using the DartPad stable or main channel):

```dart
extension type HeightWidth(num size) implements num {
  HeightWidth operator /(num denominator) {
    final b = size / denominator;
    return HeightWidth(size / denominator);
  }

  HeightWidth operator *(num multiplier) {
    return HeightWidth(size * multiplier);
  }

  HeightWidth times(num multiplier) {
    return HeightWidth(size * multiplier);
  }

  String get asString => 'HeightWidth($size)';
}

final d_margin1 = HeightWidth(1); // Was undefined.
final HeightWidth d_margin05 = d_margin1 / 2;
final HeightWidth d_margin1025 = d_margin1 * 1.25;
final HeightWidth d_margin105 = d_margin1.times(1.5);

void main() {
  print('${d_margin05.asString}, '
      '${d_margin1025.asString}, '
      '${d_margin105.asString}');
}
```

Perhaps your tool chain is too old? What's the version?

**Comment by lrhn** [comment]
The only issue I see with the code is the typo:
```dart
final HeightWIdth d_margin1025 = d_margin1 *1.25;
    // This gives syntax error as it returns a double, not HeightWidth
```
The `I` in `WIdth` is capitalized.

That should not give a *syntax* error.

So, can you provide the correct program which has this issue, and say how you execute it?

**Comment by prabinlamsal19** [comment]
Thank you for the response.
I am really sorry for the typo while posting the issue here. The typo is not present in my editor. (I have updated the original post's spelling also.)

The same code that you are writing is giving me errors in Dartpad also. Please look at this screenshot. 

![image](https://github.com/dart-lang/sdk/assets/51435770/c5e6f064-3357-403a-8db0-176582a03d84)

**Comment by lrhn** [comment]
Try switching DartPad to use the beta or master channels, and see if the issue goes away.
If it does, then it's already fixed.

**Comment by prabinlamsal19** [comment]
It worked when I switched to the latest. Thanks for the trouble.
