### ISSUE TITLE
Dart needs basic image scaling API

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#55616]
Right now the only real image processing library in pure Dart is `image`, which is horrendously slow.

In Flutter, there are many libraries that use the native platform's image handling libraries to scale, crop, and encode/decode images. However, these don't work in a Dart server process.

We really need some basic image processing capabilities (mostly crop and scale) in Dart, which could be accelerated differently on different platforms. Also support for quickly encoding and decoding JPEG, PNG, and WEBP in Dart (not in Flutter) would be huge. (I don't know what the policy is for linking to native libraries from the Dart runtime...)

Alternatively, perhaps the `image` library would be a good testbed for optimizing the Dart compiler. I have written a lot of pixel-level image processing code in C in my time, and given how fast Dart code normally runs, I have a hard time understanding why `image` is so slow for even basic operations (perhaps it is lack of richness in Dart's number type system, e.g. lack of direct support for `int8`? https://github.com/dart-lang/language/issues/3197 ).

**Comment by kevmoo** [comment]
This is not an SDK-type issue. This is likely better filed at https://github.com/flutter/flutter/

**Comment by lukehutch** [comment]
As I said, I am not looking for a Flutter solution, I am looking for something in the Dart standard libraries that will work on a Flutter-less Dart server process. Most languages ship with basic libraries for image processing that are not reliant on a UI framework.

**Comment by mraleph** [comment]
We have no plans to provide image processing libraries as part of Dart standard libraries. There is no reason why image processing should even be part of Dart standard libraries. Your best coarse of action is to select a native library which suits your needs and then write Dart bindings for it using FFI. Alternatively you can just shell out to something like ImageMagick.
