### ISSUE TITLE
Hide `@nonVirtual` methods in autocomplete?

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#55628]
When a method is marked [`@nonVirtual`](https://main-api.flutter.dev/flutter/meta/nonVirtual-constant.html) it should not be overridden. Yet, my IDE suggests it as an overridable method (see below) and as soon as I accept that suggestion, the analyzer complains that I should not be overriding this method (`invalid_override_of_non_virtual_member`). Should `@nonVirtual` methods just be excluded from the suggestion list of overridable methods?

<img width="582" alt="Screenshot 2024-05-02 at 1 07 33 PM" src="https://github.com/dart-lang/sdk/assets/1227763/da87ee77-20d1-4d10-844c-1d4de59ec511">

**Comment by goderbauer** [comment]
cc @bwilkerson as I assume these suggestions are powered by the analyzer?

I ran into this working on the `@Stateful` macro while looking for ways to stop the "fake" superclass methods (that are only there to satisfy the type system hack) from messing up people's autocomplete.

**Comment by bwilkerson** [comment]
Yes, these suggestions come from the analysis server, and yes, we should exclude non-virtual methods.
