### ISSUE TITLE
[vm] Dart AOT runtime should refuse to run snapshots with incompatible sanitizers

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55637]
We should make the Dart precompiled runtime refuse to run AOT snapshots that are not built with the same sanitizers.

Our machine code generation emits different machine code if sanitizers are enabled. If the build is somehow misconfigured, it could happen that an AOT snapshot without the extra runtime-calls for unpoisoning, leading to sanitizers complaining.

(Such check would have saved me half a day of debugging. 🙃 )

**Comment by dcharkes** [comment]
@sstrickl Might you know what would be the best place to put some bits in an Elf and assembly snapshot that we can read out in the aot runtime?

**Comment by rmacnak-google** [comment]
`Dart::FeaturesString` is where we check a bunch of runtime/snapshot compatibility things like mode and architecture. It already has something for TSAN, but not MSAN.
