### ISSUE TITLE
[analyzer] incorrectly marking as dead code when accessing record property in ternary

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/sdk#55642]
In the following program, you get an incorrect dead code waring for the code after the ternary expression:

```dart
void main() {
  const position = (x: 4, y: 4);
  true ? position.x : position.y;
  // everything below is erroneously marked dead code
  print('this code is reachable');
}
```

There is no dead code warning if `position` is a class with `x` and `y` fields, so it appears to be specific to records. 

```dart
class Position {
  const Position({required this.x, required this.y});
  final int x;
  final int y;
}

void main() {
  const position = Position(x: 4, y: 4);
  true ? position.x : position.y;
  // No dead code warning below, working as intended
  print('this code is reachable');
}
```

However it only seems to fail on variables containing records, it works fine when using record literals in the ternary expression:

```dart
void main() {
  true ? (x: 4, y: 4).x : (x: 4, y: 4).y;
  // No dead code warning below, working as intended
  print('this code is reachable');
}
```

**Comment by srawlins** [comment]
Can you say what version of Dart you are using? When I plug your first example into dartpad, stable channel, beta channel, or main channel, I only see that `position.y` is marked as dead.

**Comment by mmcdon20** [comment]
@srawlins 

Issue is happening with:

`Dart SDK version: 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "windows_x64"`

and

`Dart SDK version: 3.5.0-131.0.dev (dev) (Fri May 3 09:02:58 2024 -0700) on "windows_x64"`

I don't see the issue on dartpad either, but it's happening in vscode.  

![deadcode](https://github.com/dart-lang/sdk/assets/5104543/e861818b-adda-4cf4-a38a-3af6042a803d)

**Comment by srawlins** [comment]
Weeird I can repro this in vscode as well. Thanks for the instructions, great find, and great investigation!

**Comment by srawlins** [comment]
Ah the issue is that ResolverVisitor.visitConditionalExpression rewrites the syntax nodes of `position.y` from bring a PrefixedIdentifier to being a PropertyAccess. Then `DeadCodeVerifier._containsFirstDeadNode` misses that `_firstDeadNode` _should_ equal `parent`.
