### ISSUE TITLE
[CP] Cherry-Pick "[cfe] Ensure default values in synthesized function nodes"

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55656]
### Commit(s) to merge

https://github.com/dart-lang/sdk/commit/54031e2752d76a95fa7fa069bf1b41a21260b5e9

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/365580

### Issue Description

Without this fix some apps run into crashes of the dart2wasm compiler, see https://github.com/dart-lang/sdk/issues/55529

### What is the fix

The fix is to ensure synthetic functions created by CFE have default values for parameters where needed.

### Why cherry-pick

We don't want customers to run into dart2wasm crashes in next stable branch.

### Risk

If we run all CI tests on cherry-pick requests then risk is low. /cc @johnniwinther @chloestefantsova wdyt?

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55529

**Comment by johnniwinther** [comment]
LGTM

**Comment by vsmenon** [comment]
lgtm

**Comment by itsjustkevin** [comment]
@mkustermann go ahead and merge please.

**Comment by mkustermann** [comment]
@itsjustkevin The cherry-pick landed last week. That will ensure it will be included in the stable release for I/O, correct? If so, we can close this issue.

**Comment by itsjustkevin** [comment]
We can close this issue @mkustermann.  This cherry-pick missed the cutoff for the next release.  If we create the cherry-pick again on top of the stable branch, we can get it in the first hotfix release. 

CC @kevmoo

**Comment by mkustermann** [comment]
> We can close this issue @mkustermann. This cherry-pick missed the cutoff for the next release. If we create the cherry-pick again on top of the stable branch, we can get it in the first hotfix release.

Filed a CP for `stable` here: https://github.com/dart-lang/sdk/issues/55714
