### ISSUE TITLE
[Wildcard Variables] Experiment Flag

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#55654]
This is the implementation issue for a potential new language feature being considered: https://github.com/dart-lang/language/issues/3712

- [x] Complete the feature specification #55661
- [x] Add an experiment flag named `wildcard-variables`
- [ ] Eventually, add an experiment and release version to gate the feature.
- [ ] Then enable by default when ready to release.

**Comment by lrhn** [comment]
Suggestion: Name the experiment `wildcard-variables`, or `non-binding-variables`. (Probably the former, it's a better *name*.)

"Wildcards" by itself is little too vague (I can imagine several different features that could use that name, most involving types).

**Comment by kallentu** [comment]
cc. @dart-lang/language-team if you have any other suggestions and/or opinions.

Sure, we can name it `wildcard-variables`. If that is what we decide to move forward on, I'll change the issue names and labels for the feature.

**Comment by sgrekhov** [comment]
Please note that `ERROR: Flag "wildcard-variables" not recognized.` occurs if tests with `// SharedOptions=--enable-experiment=wildcard-variables` run via `test.py`

Try `python3 tools/test.py -n analyzer-asserts-mac co19/LanguageFeatures/Wildcards/binding_A01_t01` to reproduce

Tested on `Dart SDK version: 3.5.0-edge.3dfee274cc75ba4686f709e94496cd4d59b13772 (main) (Tue May 14 07:29:53 2024 +0000) on "macos_arm64"`
