### ISSUE TITLE
`dart test` with `--pause-after-load` flag does not print DevTools URI

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#55674]
```
dart test test/nested/simple_test_1.dart --pause-after-load
Resolving dependencies in `/Users/kenzieschmoll/develop/devtools/packages/devtools_extensions/example/app_that_uses_foo`...
Downloading packages...
Got dependencies in `/Users/kenzieschmoll/develop/devtools/packages/devtools_extensions/example/app_that_uses_foo`.
Building package executable... (6.5s)
Built test:test.
00:01 +0: loading test/nested/simple_test_1.dart

Observatory URL: http://127.0.0.1:58787/zPMwLkxnluk=/#/inspect?isolateId=isolates%2F6734125496635939&objectId=libraries%2F%4018483025
The test runner is paused. Open the Observatory and set breakpoints. Once you're finished, return to this terminal and
press Enter.
```

Opening the observatory URI shows this:
![Screenshot 2024-05-08 at 10 39 47 AM](https://github.com/dart-lang/sdk/assets/43759233/bc869567-8a47-4b80-936c-e172cc273c2a)

@jakemac53 @bkonyi

**Comment by jakemac53** [comment]
@natebosch can you look at this one?

**Comment by bkonyi** [comment]
FYI, this is related to https://github.com/dart-lang/test/issues/2185

**Comment by natebosch** [comment]
From the linked issue it looks like there is some required work in `dart test`. Have we verified that `dart test` is capable of serving dev tools?

**Comment by a-siva** [comment]
Looks like this is fixed and the pending work for pkg:test is being tracked in https://github.com/dart-lang/test/issues/2185

**Comment by bkonyi** [comment]
SDK fix landed [here](https://dart-review.googlesource.com/c/sdk/+/375000).
