### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by abh2311** [dart-lang/sdk#55683]
## Version information

- `IDEA AI-233.14808.21.2331.11709847`
- `3.2.4`
- `AI-233.14808.21.2331.11709847, JRE 17.0.10+0--11572160x64 JetBrains s.r.o., OS Windows 11(amd64) v10.0 , screens 2400.0x1350.0`

**Comment by devoncarew** [comment]
@alexander-doroshko, virtually all of these `Analyzer Feedback from IntelliJ` issues are empty; I suspect most people are hitting the action unintentionally and / or aren't realizing they're filing issues. Can we just remove it? We have better mechanisms now for users to provide us feedback.

https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/ide/errorTreeView/AnalysisServerFeedbackAction.kt

**Comment by alexander-doroshko** [comment]
@devoncarew Sure, I don't mind removing it if it hasn't proved to be useful. Shall we notify our email group just to check that there are no other ideas or objections?

**Comment by devoncarew** [comment]
> @devoncarew Sure, I don't mind removing it if it hasn't proved to be useful. Shall we notify our email group just to check that there are no other ideas or objections?

Sounds good. As a data point, we get on the order of a dozen of these issues filed a month, and I don't remember when the last non-empty one was.
