### ISSUE TITLE
`dart2wasm`: Export constant identifying the compiler

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#55694]
I'd like to have a reliable way of knowing whether my Dart code is running as WebAssembly. This is useful to work around some implementation differences (e.g. references vs. copies when viewing typed data).

https://github.com/dart-lang/sdk/issues/54785 suggests a suitable constant could be `dart.tool.dart2wasm = true`. Which such a constant, I could select suitable code paths depending on whether my code is compiled to JavaScript or WebAssembly.
There are existing workarounds with a combination of conditional library imports or `identical(0, 0.0)` hacks, but an officially supported constant would be a lot cleaner.

I've opened https://dart-review.googlesource.com/c/sdk/+/365822/1 for this.

**Comment by lrhn** [comment]
As you link to #54785, this is something that can be useful for more than just Dart2Wasm.
I'd prefer a general solution to something that only works for one compiler.
(Preferably entries that distinguish, at least, whether running natively, in JS or in Wasm, and possibly also whether compiled in development mode or production mode, and whether asserts are enabled.)

**Comment by JaffaKetchup** [comment]
Need this here as well! Could be very useful for example projects for packages to show an indicator as to whether it's running with WASM, to verify potential performance improvements.

**Comment by simolus3** [comment]
>  I'd prefer a general solution to something that only works for one compiler.

I'm not claiming this fixes #54785 :) I just need the identification in dart2wasm and I think it would be nice to have it in a format that will eventually be consistent between all tools.

**Comment by osa1** [comment]
@lrhn is there a problem with adding `dart.tool.dart2wasm` now, without waiting for #54785?

It looks like dart2js added it ~9 months ago: https://github.com/dart-lang/sdk/blob/1d0c90c145297f4f93705172f032a22e880c0b0f/pkg/compiler/lib/src/options.dart#L1089
