### ISSUE TITLE
Uncaught RuntimeError: illegal cast - when trying to access string passed from Javascript to dart wasm

### ISSUE THREAD

**Issue by akalankavinda** [dart-lang/sdk#55715]
I have exported the following function in my dart wasm code

`@pragma("wasm:export")`
`void foo(JSString x) {`
`   print(x.toString());`
`}`

but whe I try to invoke this method from the javascript side,
I get the following error:

![image](https://github.com/dart-lang/sdk/assets/23008400/f4d4243b-6d26-4efc-b55f-0b755413a39c)

It points out to the following place in wasm library

![image](https://github.com/dart-lang/sdk/assets/23008400/0eb5d559-b60a-4ce9-84ed-6d39f109c709)

Am I doing this the wrong way or is this an issue with compiler ?

PS: I was playing around with the following repo 
https://github.com/mit-mit/sandbox/tree/main/demos/webwasm

**Comment by srujzs** [comment]
Prefer using [`Function.toJS`](https://api.dart.dev/main/6824371d2fba6b3eae468d7b829ce7872ba47ecf/dart-js_interop/FunctionToJSExportedDartFunction/toJS.html) to export a Dart function.

Here's an example:

```dart
import 'dart:js_interop';

@JS()
external set foo(JSFunction f);

void main() {
  void f(JSString x) {
   print(x.toString());
  }
  foo = f.toJS;
}
```

Here, we wrap a Dart function with a JS function and set it in the property `foo` in `globalThis`. So, you can call `globalThis.foo('hello world')` in JS after this function is set.

**Comment by lrhn** [comment]
(Maybe also use [`x.toDart()`](https://api.dart.dev/stable/3.4.0/dart-js_interop/JSStringToString/toDart.html) instead of `x.toString()` to convert a `JSString` to a Dart `String`.)

**Comment by srujzs** [comment]
I missed that. :) Yes, convert it back into a `String` using `toDart`. `toString` will likely do the right thing anyways, but prefer the conversion.

**Comment by akalankavinda** [comment]
Thanks @srujzs @lrhn for the support.

With your suggestions, I modified my code as follows
```
import 'dart:js_interop';

@JS()
external set _onKeyup(JSFunction fn);

void main() {
  _onKeyup = _onKeyupDart.toJS;
}

void _onKeyupDart(JSString val) {
  print(val.toDart);
}
```

Now from the JavaScript side `_onKeyup()` is globally available and it is **working as expected**
