### ISSUE TITLE
Dart 'analyzer' package reports [ANALYSIS ISSUE] on pub.dev

### ISSUE THREAD

**Issue by ryanhanks-bestow** [dart-lang/sdk#55710]
I noticed the issue when heading to https://pub.dev/packages/analyzer to read the docs.

<img width="731" alt="Screenshot 2024-05-13 at 8 45 18 PM" src="https://github.com/dart-lang/sdk/assets/87093311/a10bab53-c0ef-4513-b548-5a34f2d67ef4">

The impact of the issue appears to be an absence of API Reference docs available from the pub.dev package page.

We typically find an 'API reference' link in this sidebar nav:

<img width="213" alt="Screenshot 2024-05-13 at 8 55 06 PM" src="https://github.com/dart-lang/sdk/assets/87093311/96def0a3-c725-4ff1-8eb8-8ec7d4d02a07">

**Comment by ryanhanks-bestow** [comment]
The 6.4.1 version on pub looks fine, btw https://pub.dev/packages/analyzer/versions/6.4.1

**Comment by scheglov** [comment]
I don't see `[analysis issue]` currently.
Might be a flake.
