### ISSUE TITLE
LinkedHashMap is unable to find an existing key

### ISSUE THREAD

**Issue by rebaz94** [dart-lang/sdk#55722]
I've come across a bug in the map where the key exists in the map, but it can't be found.

```dart
final LinkedHashMap<String, dynamic> data = LinkedHashMap.identity();
print(data['key1']); // returns null
print(data.containsKey('key1')); // returns false
print(data.keys.contains(id)); // returns true
```

In this example, despite 'key1' being present in the map but it return null, and containsKey incorrectly reports its absence. However, when checking the map's entries, using `keys` or checking with `==` equality return the value

https://github.com/dart-lang/sdk/assets/11982812/6c206a4f-b777-49c2-8854-621abfdb17c9

**Comment by lrhn** [comment]
Not entirely sure what the example is showing. The map does not contain the string `"key1"`, but it does contain the string in `id`, which is not the string `"key1"`. That looks consistent. What makes you think that `"key1"` is a key of the map?

**Comment by rebaz94** [comment]
sorry for bad example, This code snippet just an example how I utilized the map. please check the video
> ```dart
> final LinkedHashMap<String, dynamic> data = LinkedHashMap.identity();
> print(data['key1']); // returns null
> print(data.containsKey('key1')); // returns false
> print(data.keys.contains(id)); // returns true
> ```

**Comment by mraleph** [comment]
@rebaz94 Dart does not require `String` instances to be globally canonicalized (with some exceptions around compile time constants). This means two strings can be equal but not identical (because they are represented by different objects). 

This means using `LinkedHashMap<String, ...>.identity()` is not a good idea unless you somehow ensure canonicalization (e.g. you have another `Map<String, String>` somewhere which stores canonical instances).

**Comment by rebaz94** [comment]
Ah, got it. Thank you for the clarification.

**Comment by lrhn** [comment]
I'm still worried that `.keys.contains` does not answer the same as `.containsKey`. That suggests that `.keys.contains` is probably also not *efficient*. The documentation for `keys` states that it must have efficient `contains` (fx. backed by the map's `containsKey`.)

**Comment by mraleph** [comment]
@lrhn I think what it shows is that `.keys` iterable does not override its `contains` to use equality inherited from the `Map` itself. It just uses default equality (via `operator==`). This _is_ probably a bug, though it is rather niche.

**Comment by lrhn** [comment]
If the Iterable uses `==` then it probably doesn't use the map's 'contains' or lookup operations. Those so use the correct equality. And then it's probably linear, not constant time, which was my worry, even when `==` actually agrees with the map equality.
