### ISSUE TITLE
[Wildcard Variables] IntelliJ support

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#55725]
This issue tracks the wildcard variables work needed for IntelliJ.
If no work needs to be done, feel free to close it.

cc @jwren

**Comment by jwren** [comment]
https://youtrack.jetbrains.com/issue/IDEA-355469/New-Dart-language-feature-Wildcard-Variables

**Comment by jwren** [comment]
I believe that this is a no-op.  YouTrack issue created for Alex to validate this as well.

**Comment by kallentu** [comment]
Alex also validated that there's no work needed.
Closing this issue now.

Thanks @jwren!
