### ISSUE TITLE
[Wildcard Variables] Update `UNUSED_CATCH_STACK` reporting

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#55721]
Like `UNUSED_LOCAL_VARIABLE`s, we'll want to flag binding `__`s in `UNUSED_CATCH_STACK`.

For example we do not report on the `__` below

```dart
try {

} catch(e, __) { }
```

(but should).

/fyi @kallentu

**Comment by kallentu** [comment]
Documenting some thoughts from a chat @pq and I had:

1.

Once we flag the binding `__`s, we'll report `UNUSED_CATCH_STACK` which has a quick fix to remove the catch stack trace parameter.

2.
```dart
try {
} catch(e, _) { 
  // ..
  // e used somewhere 
}
```
In this scenario with a wildcard, the stack trace isn't used, but could we not write the above as the following code? It's a small thing, but maybe it's nice to have a quick fix for this? 

```dart
try {
} catch(e) { 
  // ..
  // e used somewhere 
}
```

@lrhn mentioned this in https://github.com/dart-lang/sdk/issues/55723#issuecomment-2111835359, but _shrug_ I feel like it'd be nice.

**Comment by lrhn** [comment]
If there is a quick-fix to remove the unnecessary `, _`, then it's probably fine to warn about it.
I don't expect many people to see analyzer warnings, and not have access to the quick-fixes.
