### ISSUE TITLE
[dart2wasm] Generics unexpected runtimeType when extends to nullable

### ISSUE THREAD

**Issue by huanghui1998hhh** [dart-lang/sdk#55741]
```dart
void main() {
  print(AlwaysNullableData('').runtimeType);
}

abstract class BaseData<T> {
  BaseData(this.data);

  T data;
}

class AlwaysNullableData<T> extends BaseData<T?> {
  AlwaysNullableData(super.data);
}
```
This code will print `AlwaysNullableData<String>` on other platform, but on `dart2wasm` it print `AlwaysNullableData<String?>`

**Comment by mkustermann** [comment]
> That is a bug. The inferred type argument of AlwaysNullableData('') is <String>, so that's what T should be bound to, and then the type argument to BaseData is T?.

@lrhn to clarify: It should print `AlwaysNullableData<String?>`? Then it would be a bug in other platforms, not in wasm, right?

**Comment by mkustermann** [comment]
Don't know what I was thinking, yes of course the RTT is from the bottom class and it has to print the non-nullable one.

I think the type parameter sharing we do doesn't consider nullability, we'll fix it.

**Comment by lrhn** [comment]
> doesn't consider nullability

That sound ... plausible.

**Comment by mkustermann** [comment]
[cl/366940](https://dart-review.googlesource.com/c/sdk/+/366940) should fix it.
