### ISSUE TITLE
Analyzer crashing while processing macro usage

### ISSUE THREAD

**Issue by helightdev** [dart-lang/sdk#55756]
While playing around with macro experiment, I found following analyzer crash:

```log
[11:55:10 AM] [Analyzer] [Error] [UnimplementedError: Null
#0      DeclarationBuilder.resolveIdentifier (package:analyzer/src/summary2/macro_declarations.dart:308:9)
#1      _Builder._buildIdentifier (package:_macros/src/executor/augmentation_library.dart:73:53)
#2      _Builder._buildCode (package:_macros/src/executor/augmentation_library.dart:133:9)
#3      _Builder._buildCode (package:_macros/src/executor/augmentation_library.dart:131:9)
#4      _Builder._buildCode (package:_macros/src/executor/augmentation_library.dart:131:…
```
[Full Log](https://gist.github.com/helightdev/83b9ed4d704baaf8f472367175e4232e)
[Full Reference Code](https://github.com/helightdev/AnalyzerCrashResolveIdentifier)

This analyzer only crashes once I uncomment `builder.declareInType(metaCode)` in `content.dart`.

```dart
Future introspectTest(
    ClassDeclaration clazz, MemberDeclarationBuilder builder) async {
  /// [...]
  var methods = await builder.methodsOf(clazz);
  for (var method in methods) {
    /// [...]
    var annotations = method.metadata.map(rebuildMetadata).toList();

    var metaCode = DeclarationCode.fromParts([
      "dynamic meta_",
      method.identifier.name,
      " = ",
      "[",
      ...annotations.expand((e) => [e, ","]),
      "];"
    ]);
    //builder.declareInType(metaCode);
  }
}

Code rebuildMetadata(MetadataAnnotation annotation) {
  if (annotation is IdentifierMetadataAnnotation) {
    return RawCode.fromParts([annotation.identifier]);
  } else if (annotation is ConstructorMetadataAnnotation) {
    var parts = <Object>[annotation.type.code, "("];
    for (var arg in annotation.positionalArguments) {
      parts.add(arg);
      parts.add(",");
    }
    for (var arg in annotation.namedArguments.entries) {
      parts.add(arg.key);
      parts.add(":");
      parts.add(arg.value);
      parts.add(",");
    }
    parts.add(")");
    return RawCode.fromParts(parts);
  }
  return RawCode.fromString("null");
}

```

**Comment by scheglov** [comment]
I can reproduce this.
<img width="916" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/9756f0ed-ccfb-4775-92a5-518956dbe04b">

Code
```dart
import 'package:macro_test/macro_test.dart';

@ControllerMacro()
class MyControllerText {
  @CustomAnnotation()
  void main() {}
}

class CustomAnnotation {
  const CustomAnnotation();
}
```

The reason it crashes is that the macro attempts to access the identifier `@CustomAnnotation` during the declarations phase. At this time this identifier is not resolved yet - we resolve metadata after the declarations phase, but before the definitions phase.

The reason we cannot resolve annotations until after the declarations phase is that resolution potentially depends on constructors that might be added at any point during the declarations phase.

From the macro API implementation inside the analyzer we don't have any better solution than to throw - `macro.ResolvedIdentifier resolveIdentifier()` must return something, and if the identifier cannot be resolved, there is nothing to return.

@jakemac53 For any API suggestions.

**Comment by scheglov** [comment]
With https://dart-review.googlesource.com/c/sdk/+/366966 we will tell the name of the unresolved identifier.

Theoretically we know much more - the exact AST node (so the offset), and the content of the file. So, if this happens regularly, we can provide more details to simplify identification of the problematic identifier.

**Comment by jakemac53** [comment]
> The reason we cannot resolve annotations until after the declarations phase is that resolution potentially depends on constructors that might be added at any point during the declarations phase.

The type is definitely already known, and it seems like we should be able to then know the _assumed_ "identifier" for any constructor (it must be a const constructor with that name on that known type). So, while you can't tie the constructor identifier to a specific AST node or element, we should know everything we need to know to output a reference to that identifier as Code, which is the important part (the import URI for it plus the scope (class name) and the name of the constructor)?

**Comment by scheglov** [comment]
True, we should be able to resolve the type element.

**Comment by scheglov** [comment]
BTW, here is the script that I use to see if the example runs well, and generated code.
```dart
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/src/dart/analysis/analysis_context_collection.dart';

void main() async {
  var collection = AnalysisContextCollectionImpl(
    includedPaths: [
      '/Users/scheglov/tmp/2024-05-17/AnalyzerCrashResolveIdentifier/lib/controller.dart',
    ],
  );

  var timer = Stopwatch()..start();
  for (var analysisContext in collection.contexts) {
    print(analysisContext.contextRoot.root.path);
    var analysisSession = analysisContext.currentSession;
    for (var path in analysisContext.contextRoot.analyzedFiles()) {
      if (path.endsWith('.dart')) {
        var libResult = await analysisSession.getResolvedLibrary(path);
        if (libResult is ResolvedLibraryResult) {
          for (var unitResult in libResult.units) {
            print('    ${unitResult.path}');
            var ep = '\n        ';
            print('      errors:$ep${unitResult.errors.join(ep)}');
            print('---');
            print(unitResult.content);
            print('---');
          }
        }
      }
    }
  }
  print('[time: ${timer.elapsedMilliseconds} ms]');

  await collection.dispose();
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/366895 fixes the crash.

**Comment by helightdev** [comment]
The solution now indeed works for the const constructor annotations, though using a reference to a global const field still results in a crash.

```dart
import 'package:macro_test/macro_test.dart';

@ControllerMacro()
class MyControllerText {
  @CustomAnnotation()
  @refAnnotaiton
  void main() {

  }
}

class CustomAnnotation {
  const CustomAnnotation();
}

const refAnnotation = CustomAnnotation();
```

This code now fails with
```log
Invalid argument(s): Unresolved identifier: ref
#0      DeclarationBuilder.resolveIdentifier (package:analyzer/src/summary2/macro_declarations.dart:308:9)
#1      _Builder._buildIdentifier (package:_macros/src/executor/augmentation_library.dart:73:53)
#2      _Builder._buildCode (package:_macros/src/executor/augmentation_library.dart:133:9)
#3      _Builder._buildCode (package:_macros/src/executor/augmentation_library.dart:131:9)
#4      _Builder.build (package:_macros/src/executor/augmentation…
```

As expected since 2fa0501 now outputs the reference to the offending identifier.

Could there be a possibility to also assume the identifier code of the const field similarly to how constructors identifiers are assumed or is this not possible with the information known in the declaration phase? Reading @jakemac53's explanation on how this is possible for constructors also let's me assume this is possible for const fields, since we should know both the import uri of the const field's library as well as the name of the global field.

**Comment by scheglov** [comment]
During the declarations phase we cannot resolve identifiers that are not guaranteed to be names of types.
Because resolution `@refAnnotation` could change if the next macro will declare `refAnnotation` in this library.
Of course we technically _can_ do this in the analyzer, but the result might be sometimes surprising.

My reading of @jakemac53 comment "you can't tie the constructor identifier to a specific AST node or element" - we don't know the element, but this does not matter because we can output the constructor name, and regardless what it is, it will be the same as the referenced by the annotation.

**Comment by helightdev** [comment]
Ah okay I see the problem. So if I want to have declarative macros which are copying metadata, this will only work for const constructor invocations. Thanks for clarifying!
