### ISSUE TITLE
[CP] Fix `dart run` missing fast path when using Flutter

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#55758]
### Commit(s) to merge

https://github.com/dart-lang/pub/commit/e70850b53ef9b15a08af7fb0f0f2dcdbfa762b34
Rolled to the sdk in: https://dart-review.googlesource.com/c/sdk/+/367024?tab=checks

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/367060

### Issue Description

Without this it is hard/impossible to use build_runner together with localization on flutter.

`dart run build_runner build` would wrongly think that the current resolution is stale, and redo it. Missing the flutter_gen package that `flutter pub get` injects to the package config.

This is a regression that was introduced in: https://github.com/dart-lang/pub/pull/4160 rolled to the sdk in https://github.com/dart-lang/sdk/commit/74c94ee2d3ea98a1ac1365cc759ed97c73002fc2

See https://github.com/dart-lang/build/issues/3705

### What is the fix

By fixing the fast-path check, we will not replace the package_config if it is up-to-date.

This does not fix the underlying problem that `dart run` doesn't inject the flutter_gen package when the resolution is stale, but at least makes it possible to run build_runner when localization is enabled.

### Why cherry-pick

To fix the regression

### Risk

Medium-low

### Issue link(s)

See https://github.com/dart-lang/build/issues/3705

**Comment by itsjustkevin** [comment]
@jonasfj @jakemac53 could you take a look at this cherry-pick request?

**Comment by jakemac53** [comment]
LGTM
