### ISSUE TITLE
vm_service_tester.dart has a wrong uri

### ISSUE THREAD

**Issue by onism0106** [dart-lang/sdk#55753]
vm_service_tester.dart has a wrong uri

`final wsUri = 'ws://$host$port/ws';`
should be 

`final wsUri = 'ws://$host:$port/ws';`

**Comment by devoncarew** [comment]
https://github.com/dart-lang/sdk/blob/main/pkg/vm_service/example/vm_service_tester.dart

cc @bkonyi
