### ISSUE TITLE
[Wildcard Variables] Dart2JS Implementation

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#55750]
This issue tracks the work needed for the wildcard variables feature to be supported in Dart2JS.

We may need to do some additional work to support multiple wildcard parameters in functions.
```dart
class A {
  int add(int a, int b) => 3;
}

class C implements A {
  int add(int _, int _) => 3;
}
```

cc. @sigmundch Feel free to tag or reassign as you see fit. 
I'd also appreciate more details so we don't lose that context.

**Comment by sigmundch** [comment]
Thanks @kallentu, similar comments to what I posted in the DDC issue:

- the work here depends a lot on what kind of lowering we end up doing in the CFE
- the lowering will likely convert the wildcard variables into something, potentially a variable declaration that is never read.
- if the lowering uses the existing representation of variable declarations and guarantees uniqueness of variable names like today parameters have, then the backend may not need to do anything special for it to generate valid JavaScript. However, if the variable is represented by a new kernel node or a node that breaks current invariants, we may need some relatively small amount of work to emit valid JavaScript function declarations. The work could be similar to what DDC already does for temporary variables in Let expressions.

**Comment by kallentu** [comment]
Following up, is there any work to be done here? Could we close this ticket for Dart2JS?
cc @sigmundch @natebiggs

**Comment by biggs0125** [comment]
It looks like all the dart2js tests are passing. I think with your change to add the unique names, dart2js should be good to go. Closing this out.
