### ISSUE TITLE
DART_VM_OPTIONS for self-executables not working!

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/sdk#55767]
As mentioned on README, Dart 3.4.0 supports `DART_VM_OPTIONS` for self-executables:

`README.md`:
```markdown
...
### Dart Runtime

- Dart VM flags and options can now be provided to any executable generated
  using `dart compile exe` via the `DART_VM_OPTIONS` environment variable.
  `DART_VM_OPTIONS` should be set to a list of comma-separated flags and options
  with no whitespace. Options that allow for multiple values to be provided as
  comma-separated values are not supported (e.g.,
  `--timeline-streams=Dart,GC,Compiler`).

  Example of a valid `DART_VM_OPTIONS` environment variable:

   DART_VM_OPTIONS=--random_seed=42,--verbose_gc

...
```

---

Example:

`foo.dart`:
```dart
void main(List<String> args) {
  print("FOO>> args: $args");
}
```

`run-foo.sh`:
```shell
#!/bin/bash

dart compile exe foo.dart

export DART_VM_OPTIONS=--random_seed=42,--verbose_gc
echo "DART_VM_OPTIONS: $DART_VM_OPTIONS"

echo "Running executable:"
./foo.exe

```

Output of `./run-foo.sh`:
```text
Generated: /private/tmp/dart-test-foo/foo.exe
DART_VM_OPTIONS: --random_seed=42,--verbose_gc
Running executable:
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]

Executes the Dart script <dart-script-file> with the given list of <script-arguments>.

Common VM flags:
--help or -h
  Display this message (add -v or --verbose for information about
  all VM options).
--packages=<path>
  Where to find a package spec file.
--define=<key>=<value> or -D<key>=<value>
  Define an environment declaration. To specify multiple declarations,
  use multiple instances of this option.
--snapshot-kind=<snapshot_kind>
--snapshot=<file_name>
  These snapshot options are used to generate a snapshot of the loaded
  Dart script:
    <snapshot-kind> controls the kind of snapshot, it could be
                    kernel(default) or app-jit
    <file_name> specifies the file into which the snapshot is written
--version
  Print the SDK version.
```

For some reason it's always showing the `dart` CLI help message.

---

`dart --version`:

```text
Dart SDK version: 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "macos_x64"
```

---

**Comment by gmpassos** [comment]
FYI: @bkonyi

**Comment by bkonyi** [comment]
Thanks for the heads up @gmpassos. I'm able to reproduce and it looks like there was some oversights in the implementation that wasn't caught by testing. I have a fix up for review [here](https://dart-review.googlesource.com/c/sdk/+/367720).

**Comment by gmpassos** [comment]
> ... I have a fix up for review [here](https://dart-review.googlesource.com/c/sdk/+/367720).

Please add documentation for `DART_VM_OPTIONS`, especially for self-executables. This is not documented anywhere.

**Comment by bkonyi** [comment]
Cherrypick request has been filed here: https://github.com/dart-lang/sdk/issues/55818.

**Comment by bkonyi** [comment]
> Please add documentation for `DART_VM_OPTIONS`, especially for self-executables. This is not documented anywhere.

There's not any obvious spot to put this on the website since it's relatively niche functionality, but I've added documentation in the SDK that should make this a bit easier to discover: https://dart-review.googlesource.com/c/sdk/+/367800

**Comment by gmpassos** [comment]
> ... it's relatively niche functionality.

The default max heap size is 30GB:
https://github.com/dart-lang/sdk/blob/f4cc1eb6480b7838fe30c3700b04974935739b49/runtime/vm/globals.h#L62

IMHO, every self-executable in production should define its memory limit, since running any application with a heap limit higher than the available memory is a recipe for disaster.

Since the only way to define the max heap size in a self-executable is by using `DART_VM_OPTIONS`, this shouldn't be treated as a hidden property.

**Comment by a-siva** [comment]
I believe this can be closed ?

**Comment by bkonyi** [comment]
> I believe this can be closed ?

It's already closed :-)
