### ISSUE TITLE
[Wildcard Variables] VM Debugging Support

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#55765]
This issue tracks any work required for wildcard variables in the VM debugger.

### References

> Correct - I think the nuance here is that in the code we emit in JavaScript we need to introduce a placeholder name to generate a valid function signature.
> 
> 
> 
> While our intent was to eventually make dwds model all of its state based on what we know from the dart program, there were cases in the past where it created its internal model based on the Chrome debugger's state of the application. If that is still the case today, we may need to do some work to ensure those synthetic variables are properly ignored/hidden. 

 _Originally posted by @sigmundch in [#55751](https://github.com/dart-lang/sdk/issues/55751#issuecomment-2117883572)_

cc. @bkonyi

**Comment by a-siva** [comment]
One potential work item that came up from our discussion with the CFE team this afternoon
- wildcard locals would have to be filtered out when sending information about local variables to the client as part of the vm service reply
