### ISSUE TITLE
`Convert to async function body` refactoring should handle `FutureOr` return types

### ISSUE THREAD

**Issue by pattobrien** [dart-lang/sdk#55773]
## Description

Given a return type of `FutureOr<Foo>`, the code assist `Convert to async function body` improperly adds another `Future` to the return type, resulting in a new return type of `Future<FutureOr<Foo>>`. 

Before assist:

```dart
@override
  FutureOr<void> buildDefinitionForMethod(
    MethodDeclaration method,
    FunctionDefinitionBuilder builder,
  ) { /* ... */ }
```

After assist:

```dart
@override
  Future<FutureOr<void>> buildDefinitionForMethod(
    MethodDeclaration method,
    FunctionDefinitionBuilder builder,
  ) async { /* ... */ }
```

### Info

Dart SDK version: 3.5.0-159.0.dev (dev) (Wed May 15 13:03:12 2024 -0700) on "macos_arm64"

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/369502
