### ISSUE TITLE
Unhandled Exception: type '_Type' is not a subtype of type 'IBaseModel' in type cast

### ISSUE THREAD

**Issue by warioddly** [dart-lang/sdk#55788]
```dart

abstract class IBaseModel {
  String get table => throw UnimplementedError();
}

class BotModel extends IBaseModel {
  @override
  String get table => "bots";
}


abstract class IBaseMigration<T extends IBaseModel> {

  const IBaseMigration();

  String get table => (T as IBaseModel).table;

  Future<void> up(Database db) {
    throw UnimplementedError();
  }

}


class BotMigration extends IBaseMigration<BotModel> {

  const BotMigration();

  @override
  Future<void> up(Database db) async {
    print("table $table");  //  Unhandled Exception: type '_Type' is not a subtype of type 'IBaseModel' in type cast
  }

}




// But if i'am print table getter like this
abstract class IBaseMigration<T extends IBaseModel> {
  const IBaseMigration();

  // here 
  Type get table => T;

  Future<void> up(Database db) {
    throw UnimplementedError();
  }

}


class BotMigration extends IBaseMigration<BotModel> {

  const BotMigration();

  @override
  Future<void> up(Database db) async {

    print("model $table"); // output: model BotModel
    print("is IBaseModel ${table is IBaseModel}"); // output // is IBaseModel false

}

```

This tracker is for issues related to:
* Dart VM

If you aren't sure, file the issue here, and we'll find the right home for it.
In your issue, please include:

- Dart 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22621)

**Comment by warioddly** [comment]
and the second question is, when inheriting in generic, methods or properties are not visible 
![image](https://github.com/dart-lang/sdk/assets/53710487/4030f5a4-a20f-43cd-b71f-6d51406fb150)

Expected these methods:
![image](https://github.com/dart-lang/sdk/assets/53710487/6c924420-54c6-426a-bca4-2fcba870d064)

**Comment by lrhn** [comment]
Dart does not allow access to static methods through type variables. That's why the only members you can see for `T.` are the ones on `Type` objects.

That's also why `(T as IBaseModel)` fails, the type variable `T` is evaluated as an expression which gives you a `Type` object, an instance of the class `Type`, which cannot be cast to `IBaseModel`, so the cast throws.

**Comment by warioddly** [comment]
@lrhn I understand you, thanks so much🔥
