### ISSUE TITLE
The SDK configured in dart.flutterSdkPath is not a valid SDK folder.

### ISSUE THREAD

**Issue by hyufdd** [dart-lang/sdk#55785]
I just opened up my first flutter project and a box popped up in the corner. It read "The SDK configured in dart.flutterSdkPath is not a valid SDK folder." How do I fix this?

**Comment by mkustermann** [comment]
This seems more related to configuration of your editor (which may be VSCode?). The VSCode `settings.json` for your project may contain a `dart.flutterSdkPath` which is incorrect?

If you need more help with VSCode setup, consider reaching out to support channels for VSCode plugins for Dart (https://github.com/Dart-Code/Dart-Code) and Flutter (https://github.com/Dart-Code/Flutter) - this issue tracker is for Dart SDK issues.
