### ISSUE TITLE
MSAN use-of-uninitialized-value in FFI tests

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#55783]
ffi/function_structs_by_value_generated_args_native_test [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8747628483217070977/+/u/test_results/ignored_flaky_test_failure_logs)
ffi/function_structs_by_value_generated_ret_arg_native_test [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8747719079422495521/+/u/test_results/ignored_flaky_test_failure_logs)
ffi/function_structs_by_value_generated_args_test [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8748081467428923073/+/u/test_results/ignored_flaky_test_failure_logs)

are flaky failing for both X64 and ARM64.

@dcharkes

**Comment by dcharkes** [comment]
Thanks @rmacnak-google.

Relevant logs:

```
stderr:
==27580==WARNING: MemorySanitizer: use-of-uninitialized-value
/b/s/w/ir/cache/builder/sdk/buildtools/linux-arm64/clang/bin/llvm-symbolizer: error: '[anon:dart-code]': No such file or directory
    #0 0xffffe74df9b0 in PassStructStruct16BytesMixed3x10 out/ReleaseMSANARM64/../../runtime/bin/ffi_test/ffi_test_functions_generated.cc:3808:25
    #1 0xfffff7587024  ([anon:dart-code]+0x7024)
    #2 0xffffe73bafe0  ([anon:dart-code]+0x3afe0)
```

```
stderr:
==27376==WARNING: MemorySanitizer: use-of-uninitialized-value
/b/s/w/ir/cache/builder/sdk/buildtools/linux-arm64/clang/bin/llvm-symbolizer: error: '[anon:dart-code]': No such file or directory
    #0 0xffffe7ffd9e4 in ReturnStructNestedIntStructAlignmentInt32 out/ReleaseMSANARM64/../../runtime/bin/ffi_test/ffi_test_functions_generated.cc:6238:13
    #1 0xfffff7587e04  ([anon:dart-code]+0x7e04)
    #2 0xfffff50e6858  ([anon:dart-code]+0x66858)
```

```
stderr:
==725132==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fd3d1c5003e in ReturnStructArgumentStructStruct32BytesHomogeneous out/ReleaseMSANX64/../../runtime/bin/ffi_test/ffi_test_functions_generated.cc:5962:36
    #1 0x7fd3e1486e3a  (<unknown module>)
    #2 0x7fd3de94448e  (<unknown module>)
```

```
stderr:
==725150==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f47351510f0 in ReturnStructNestedIntStructAlignmentInt32 out/ReleaseMSANX64/../../runtime/bin/ffi_test/ffi_test_functions_generated.cc:6238:13
    #1 0x7f4744185f79  (<unknown module>)
    #2 0x7f474185dbdd  (<unknown module>)
    #3 0x7f474185d6cf  (<unknown module>)
```

```
stderr:
==15165==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f4191c765e2 in PassStruct8BytesInlineArrayIntx4 out/ReleaseMSANX64/../../runtime/bin/ffi_test/ffi_test_functions_generated.cc:3412:13
    #1 0x7f41a1e85f79  (<unknown module>)
    #2 0x7f4192699cc2  (<unknown module>)
```

Seems to happen with multiple combinations of vm flags.

And it's all when `std:cout`ing parameters.

(And as opposed to earlier issues with `std::cout` (https://github.com/dart-lang/sdk/issues/43075), this is not failing inside the std lib, but on the actual parameters.)

Link to flakes on dashboard: https://dart-current-results.web.app/#/filter=ffi/function_structs_by_value&flaky

Link to flakiness dashboard: [msan and ffi](https://dashboards.corp.google.com/_0d7e1e34_2c58_4d29_bf12_cf7bed10396d?fb=name:ct:ffi&fb=configuration:ct:msan&fh=eJzdjTHKwzAMhe-i2ZPJ0tygc8aQQThqK7BlY6RCKbl7LCj0p0f4x09P733rG3iHGQQLQYBUsxX5sr4aDWJppgN3VFwapatXYrxMU_TSA7v6ad0CFMvKC2VKCrN2ozHCmn0FjvCxpSo3vltH5Sp_tb_B__IH6FTqk8arJ8d2Ak3-fI8).

Some more similar existing failures:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8747900274836325473/+/u/test_results/ignored_flaky_test_failure_logs

```
stderr:
==572662==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fd6ca648b0c in PassUnion9BytesNestedIntx10 out/ReleaseMSANX64/../../runtime/bin/ffi_test/ffi_test_functions_generated.cc:4425:57
    #1 0x7fd6da385f79  (<unknown module>)
    #2 0x7fd6caf3df24  (<unknown module>)
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8749893407485939393/+/u/test_results/ignored_flaky_test_failure_logs

```
stderr:
==311022==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f537f8c944e in PassUint8Struct32BytesInlineArrayMultiDimensionalI out/ReleaseMSANX64/../../runtime/bin/ffi_test/ffi_test_functions_generated.cc:3918:13
    #1 0x7f538f286e3a  (<unknown module>)
```

This has been happing for a while, going as far back as 2023-05-xx.
