### ISSUE TITLE
Dart cannot open a socket on Android device, not simulator

### ISSUE THREAD

**Issue by Aquarius-M** [dart-lang/sdk#55791]
When connecting to an Android device, it will prompt "Connection Refused". Changing it to 10.0.2.2 will also cause the issue

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 37358`

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 10.0.2.2, port = 37358`

```
E/flutter (12192): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 37358  

E/flutter (12192): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)

E/flutter (12192): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1914:26)

E/flutter (12192): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)

E/flutter (12192): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:2138:22)

E/flutter (12192): #4      Socket.startConnect (dart:io/socket.dart:805:21)

E/flutter (12192): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2487:20)

E/flutter (12192): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2926:12)

E/flutter (12192): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2931:12)

E/flutter (12192): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2786:12)

E/flutter (12192): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2623:7)

E/flutter (12192): #10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)

E/flutter (12192): #11     WebSocket.connect (dart:_http/websocket.dart:320:22)

E/flutter (12192): #12     vmServiceConnectUriWithFactory (package:vm_service/vm_service_io.dart:26:44)

E/flutter (12192): #13     vmServiceConnectUri (package:vm_service/vm_service_io.dart:12:10)
```

**Comment by mkustermann** [comment]
It's a little unclear what code is using `package:vm_service` to connect to the VM, where that code is run and where the VM it is trying to connect runs on.

If you try to connect from another machine to a Dart VM running on an android device you have to ensure you can connect to the device / ip / port first (see e.g. documentation for port forwarding using `adb` athttps://developer.android.com/tools/adb#forwardports)

This error is an error from the operating system saying that the process cannot connect to that TCP IP/Port - it's not something dart specific.

@Aquarius-M please provide more details / evidence this is a Dart issue, otherwise we'd close this issue.

**Comment by Aquarius-M** [comment]
The problem occurred during the connection

```
  Future<vm.VmService> getVMService() async {
    if (_service != null) {
      return _service!;
    }
    ServiceProtocolInfo info = await Service.getInfo();
    String url = info.serverWebSocketUri.toString();
    debugPrint(url);

    _service = await vmServiceConnectUri(url);
    debugPrint(_service.toString());
    return _service!;
  }

```

print url is `ws://127.0.0.1:62915/2aKmlfsudA0=/ws`， but error print is 
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 39516`

maybe port error?

**Comment by bkonyi** [comment]
Can you try running with the `--disable-dds` flag and see if that fixes your issue? If there's a connected Dart Development Service (DDS) instance, the URI returned from `Service.getInfo()` points to that URI, not the local VM service. In the case of Flutter DDS runs on the host, not on the target (i.e., the Android device), so the `localhost` URI is unaccessible from the app.

**Comment by Aquarius-M** [comment]
i'll try

**Comment by Aquarius-M** [comment]
> 您可以尝试使用该`--disable-dds`标志运行，看看是否能解决您的问题？如果存在连接的 Dart 开发服务 (DDS) 实例，则返回的 URI`Service.getInfo()`指向该 URI，而不是本地 VM 服务。对于 Flutter，DDS 在主机上运行，​​而不是在目标（即 Android 设备）上运行，因此`localhost`无法从应用程序访问 URI。

It's worked
