### ISSUE TITLE
Invalid fixes being suggested

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#55804]
Given a file containing the following:
```dart
void f(C c) {
  var x = c.x;
  print(x);
}

class C {}
```
Server will suggest four fixes, only two of which are reasonable:
- Create getter 'x'
- Create local variable 'x'
- Create mixin 'x'
- Create field 'x'

It should not be suggesting to create either a mixin or a local variable because neither of these would leave the code in a valid state.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/368681

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/368701
