### ISSUE TITLE
Erroneous RangeError when compiling to WASM

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/sdk#55817]
https://github.com/flyerhq/flutter_chat_ui/issues/596

```console
Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 1
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      Intrinsifier.generateInstanceIntrinsic (package:dart2wasm/intrinsics.dart:337)
#2      CodeGenerator.visitInstanceInvocation (package:dart2wasm/code_generator.dart:1817)
#3      InstanceInvocation.accept1 (package:kernel/ast.dart:5803)
```

```dart
String _multiUserTextBuilder(List<types.User> author) {
  if (author.isEmpty) {
    return '';
  } else if (author.length == 1) {
    return '${author.first.firstName} is typing';
  } else if (author.length == 2) {
    return '${author.first.firstName} and ${author[1].firstName}'; // This line is the issue
  } else {
    return '${author.first.firstName} and ${author.length - 1} others';
  }
}
```

As far as I can tell, this is perfectly valid Dart code failing to compile to WASM

See also: https://github.com/flutter/flutter/issues/148617

**Comment by kevmoo** [comment]
@Rexios80 – confirm 3.5.0 (build 3.5.0-167.0.dev) – right?

**Comment by osa1** [comment]
I've started debugging this, but the package cannot be built right now without making some changes in the dependencies, see https://github.com/flyerhq/flutter_chat_ui/issues/596#issuecomment-2126565177.

**Comment by mkustermann** [comment]
I think this is an incorrect optimization: We see that the `List<types.User> author` list is actually always a `const <types.User>[]`. Then our compiler wants to optimize the code by performing the list index at compile-time, but it doesn't check whether the index is in-bounds.

=> [cl/368302](https://dart-review.googlesource.com/c/sdk/+/368302) should fix this.

**Comment by mkustermann** [comment]
Filed cherry-pick request for stable: https://github.com/dart-lang/sdk/issues/55853
