### ISSUE TITLE
Dart WebSocket Connection to webserver Exhibits Inconsistent Behavior and Premature Closure

### ISSUE THREAD

**Issue by vfiruz97** [dart-lang/sdk#55810]
**Issue Description:**
When attempting to use Dart's WebSocket class to establish a WebSocket connection to the server wss://mob-backdev.dentro.ru:444, unexpected behavior occurs. Although the server is expected to echo the sent messages, the received data is inconsistent, and sometimes the connection closes prematurely with a SocketException.

**Steps to Reproduce:**

1. Run the provided Dart code to establish a WebSocket connection to the server.
2. Send five messages sequentially to the server with a delay of 1 second between each message.
3. Listen for incoming messages and track the count.
4. Observe the received data and the behavior of the connection.

**Expected Behavior:**

1. All five messages are successfully sent to the server.
2. The server echoes each message back to the client.
3. The connection remains open until all messages have been received.
4. The connection closes gracefully after receiving all echoed messages.

**Actual Behavior:**

1. The received data is inconsistent and sometimes includes unexpected characters.
2. The connection occasionally closes prematurely with a SocketException.
3. The observed behavior varies between runs.

**Additional Information:**

- Dart SDK version: 3.4.0 (stable)
- Operating System: macOS
- Tested with other WebSocket servers (e.g., wss://echo.websocket.org) without encountering similar issues.
- A recorded video demonstrates testing the WebSocket server using Postman without issues.

**Code Snippet:**
```dart
import 'dart:io';

void main() async {
  try {
    final socket = await WebSocket.connect(
      'wss://mob-backdev.dentro.ru:444',
      headers: {'dentro-token': '86F1A241876A2B46BFEFED38C88936D8'},
    );

    var receivedCount = 0;
    socket.listen(
      (data) {
        print('Received: $data');
        receivedCount++;
        if (receivedCount == 5) {
          socket.close();
        }
      },
      onError: (error) {
        print('Error: $error');
      },
      onDone: () {
        print('Connection closed by server!');
      },
    );

    Future.delayed(Duration(seconds: 1)).then((_) {
      socket.add('Message 1');
      Future.delayed(Duration(seconds: 1)).then((_) {
        socket.add('Message 2');
        Future.delayed(Duration(seconds: 1)).then((_) {
          socket.add('Message 3');
          Future.delayed(Duration(seconds: 1)).then((_) {
            socket.add('Message 4');
            Future.delayed(Duration(seconds: 1)).then((_) {
              socket.add('Message 5');
            });
          });
        });
      });
    });
  } catch (e) {
    print('Error connecting to the WebSocket server: $e');
  }
}

```

**Outputs:**
```bash
➜  ws git:(main) ✗ dart lib/test.dart 
Received: Message 0
Received: Message 1
Connection closed by server!

➜  ws git:(main) ✗ dart lib/test.dart
Received: 5gn5gn5
Connection closed by server!

➜  ws git:(main) ✗ dart lib/test2.dart
Received: Message 0
Connection closed by server!
Unhandled exception:
SocketException: Reading from a closed socket
#0      _RawSecureSocket.read (dart:io/secure_socket.dart:779:7)
dart-lang/io#1      _Socket._onData (dart:io-patch/socket_patch.dart:2448:28)
dart-lang/io#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
dart-lang/io#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
dart-lang/io#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
dart-lang/io#5      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
dart-lang/io#6      _StreamController._add (dart:async/stream_controller.dart:658:7)
dart-lang/io#7      _StreamController.add (dart:async/stream_controller.dart:606:5)
dart-lang/io#8      _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1116:19)
dart-lang/io#9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
dart-lang/io#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
dart-lang/io#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
dart-lang/io#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

➜  ws git:(main) ✗ dart lib/test2.dart
Received: Message 1
Received: .\sm.\sm.
Received: G嚕G嚕G
Connection closed by server!

```

**Test in Postman**

https://github.com/dart-lang/io/assets/43540889/236c4804-d3be-43ee-9894-567a5fdd40d4

**Comment by mraleph** [comment]
I think this is a bug in the server implementation of WebSocket protocol which is used by `wss://mob-backdev.dentro.ru:444` backend. Do you know what kind of library that uses? 

I managed to narrow it down to the following intrinsic behavior of Dart's `WebSocket`: when forming a `WebSocket` frames we don't send header and payload "atomically", instead we write them out separately and whatever buffering happens in the bottom layers might merge things together or not. 

I think whatever 

If I replace the following lines of code https://github.com/dart-lang/sdk/blob/698bf0846b7ebf3f399db0a1ff2e10ca5460eaa3/sdk/lib/_http/websocket_impl.dart#L838 with 

```dart
      Uint8List result = Uint8List(header.length + data.length);
      result.setRange(0, headerSize, header);
      result.setRange(headerSize, headerSize + data.length, data);
      return [result];
```

Then server starts behaving correctly. 

I actually think the server might be reading out of bounds from input buffers when it receives "split" frames (e.g. it expects that if WebSocket frame header says it has 80 bytes then it actually tries to read 80 bytes from the buffer that does not have enough data). So there might even be a vulnerability on the server side.

**Comment by vfiruz97** [comment]
Dear @mraleph,

Thank you for your detailed analysis of the WebSocket behavior in Dart and your observations regarding our server implementation. We appreciate your effort in narrowing down the issue and proposing potential solutions.

Our server is written probably in pure C++. I asked some piece of code from backend. Here I provided them below.
[wsServer.hpp](https://gist.github.com/vfiruz97/8c79aac1524a1fbff77d951a745c7827)
[wsServer.cpp](https://gist.github.com/vfiruz97/24dfbc88e5cc83c0719cf4631e6db5da)

**Comment by mraleph** [comment]
@vfiruz97 Thanks. Yeah, the bug in the server is exactly what I would have expected: [here](https://gist.github.com/vfiruz97/24dfbc88e5cc83c0719cf4631e6db5da#file-wsserver-cpp-L298-L328) the code assumes that `recv` would have returned the whole frame, but there is nothing that guarantees this. 

I would recommend to use some C++ WebSocket library rather than hand-coding this stuff.
