### ISSUE TITLE
Do data classes require code gen?

### ISSUE THREAD

**Issue by FireSourcery** [dart-lang/sdk#55838]
If we were to discount the code gen provided by `enum`, then it would seem `Map` and `enum` alone contain all the constituents necessary for a data class.

```dart
// a key to each field, with a generated string, use as json key; a type parameter, effectively describe the memory allocation requirements
enum PersonField<V> with DataField<V> {
  id<int>(),
  age<int>(),
  name<String>();
}

class Person extends DataMap<PersonField> {
  final String name;
  final int id;
  final int age;

  const Person(this.id, this.name, this.age);

  // the user side class only needs to provide a function to map the values of a known memory layout/interface to the user's class' memory layout
  Person.initWith(DataMap<PersonField> map)
      : id = PersonField.id(map), // map[PersonField.name] as V
        name = PersonField.name(map),
        age = PersonField.age(map);

  // and a function using a known interface access the fields of the user's class, maps ids to getters
  @override
  Object operator [](PersonField key) {
    return switch (key) { PersonField.id => id, PersonField.name => name, PersonField.age => age };
  }

  // in this case, we must go through a intermediary step of jsonMap -> known memory layout/interface -> user's class, at runtime.
  // where as code gen can directly map jsonMap -> user's class, which is less cost during runtime. although this approach is in principle the same as [StringBuffer]
  factory Person.fromJson(Map<String, Object?> json) {
    return Person.initWith(DataMapBuilder(PersonField.values).fromJson(json));
  }

  @override
  List<PersonField> get keys => PersonField.values;

  // Alternatively passing the initWith constructor to the parent class could make this more concise
   Person updateAge(int age) => Person.initWith(DataMapBuilder(keys).fillWithEntry(PersonField.age, age));
}
```

While I cant imagine a world of users requesting data class without good reason, I am a bit puzzled to why this more primitive approach is not supported.

One potential advantage to this approach, is that since each data class extends from an common underlying interface, functions on that common interface can be shared. For example, a Widget view on the UI side, displaying all contents of a data class. (Quite similar to the approach of of extending Widget)

The rest is working out the implementation details. Here's a preliminary solution, untested:
```dart
/// assigns key and name to Map-like classes, using Enum as keys
abstract mixin class EnumMap<E extends Enum, V> implements MapBase<E, V> {
  @override
  List<E> get keys;

  @override
  V operator [](covariant E key);

  // if this accepts null then, clear can call to reset
  @override
  void operator []=(E key, V value);

  @override
  void clear();

  @override
  V? remove(covariant E key) => throw UnsupportedError('EnumMap does not support remove operation');

  Iterable<({String name, V value})> get namedValues => keys.map((e) => (name: e.name, value: this[e]));

  // MapEntries as Records
  Iterable<(E, V)> get pairs => keys.map((e) => (e, this[e])); 

  S fillWithEntry<S extends EnumMap>(E key, V value) => (this..[key] = value) as S;

  /// [EnumMap] asserts all keys are present
  /// fills values, user may call from 'static' constructor
  S fromMap<S extends EnumMap>(EnumMap<E, V> map) => (this..addAll(map)) as S;

  S toMap<S extends EnumMap>() => this as S;

  /// [Map] includes updated values
  S fillWithMap<S extends EnumMap>(Map<E, V> map) => (this..addAll(map)) as S;

  S fromMapByName<S extends EnumMap>(Map<String, V> map) => (this..addEntries(map.entries.map((e) => MapEntry(keys.byName(e.key), e.value)))) as S;

  Map<String, V> toMapByName() => {for (final key in keys) key.name: this[key]};
}

// keys with type effectively define memory layout
abstract mixin class DataField<V> implements Enum {
  const DataField();
  Type get type => V;
  bool compareType(Object? object) => object is V;
  V call(DataMap dataMap) => dataMap[this] as V;
}

/// Data as mixed value type maps
// immutable wrap + mixed values types
abstract mixin class DataMapBase<E extends DataField<Object?>> implements MapBase<E, Object?>, EnumMap<E, Object?> {
  const DataMapBase();

  // fill values from json
  S fromJson<S extends DataMap>(Map<String, Object?> json) {
    // for (final key in keys) {
    //   if (key.compareType(json[key.name])) this[key] = json[key.name];
    // }
    // return this as S;
    for (final key in keys) {
      if (!key.compareType(json[key.name])) throw FormatException('DataMap.fromJson: ${key.name} is not of type ${key.type}');
    }
    return fromMapByName(json);
  }

  Map<String, Object?> toJson() => toMapByName();

  @override
  void clear() => throw UnsupportedError('DataMap does not support clear');

  @override
  void operator []=(E key, Object? value);

  @override
  Object? operator [](covariant E key);
  @override
  List<E> get keys;
}

abstract class DataMap<E extends DataField<Object?>> with MapBase<E, Object?>, EnumMap<E, Object?>, DataMapBase<E> {
  const DataMap();

  // overridden in builder.
  @override
  void operator []=(E key, Object? value) => UnsupportedError('DataMap does not support assignment');
}

// allow a stand alone DataMap without named accessors.
class _DataMap<E extends DataField<Object?>> extends DataMap<E> {
  _DataMap._(this._keys, this._map);
  _DataMap(List<E> keys) : this._(keys, {for (final key in keys) key: null});

  final List<E> _keys;
  final Map<E, Object?> _map;
  @override
  Object? operator [](covariant E key) => _map[key];
  @override
  List<E> get keys => _keys;
}

// a builder surrogate for simplifying child class constructors
// allocate a map with keys
class DataMapBuilder<E extends DataField<Object?>> extends _DataMap<E> {
  DataMapBuilder(super.keys);

  @override
  void operator []=(E key, Object? value) => _map[key] = value;
}

**Comment by lrhn** [comment]
Not entirely sure what the question here is. 

This looks like a very complicated model, with multiple classes per "data class" and intricate operations on each data field.
That's precisely the kind of code I would _want_ to generate instead of writing by hand.

I'd also prefer a much simpler implementation in most cases, depending on what I want to use my classes for. 

The point of using code generation instead of building on a language feature, is that this is a case where one size does not fit all. Every time data classes has been discussed, people with different and sometimes contradictory requirements have shown up.

**Comment by FireSourcery** [comment]
Thank you for your feedback. Apologies if I made that unclear. Please allow me to clarify. 

My first question is of the advisory type and for discussion, do we we have a consensus on the following?
The crux of data classes is accessing fields via _names_ (whether that takes the form of String, enum Id, or Symbol). It is this requirement alone that necessitates code gen, as it cannot be achieved any other way, that's the inherent nature of referring to a piece of memory by name. However, `enum` provides a generated String name already. Given that this portion is handled, then some of the requirements pushed to code gen as a solution, (e.g. fromJson/toJson) is filling some repeated logic, generating similar logic, which can perhaps be handle by a code library instead.

My second question is of the request type. Essentially, can we have data classes with built in uniformed access? So that implemented logic can be reused. For example fromJson/toJson, perhaps some UI format. Personally, I'd like to not reimplement similar logic, then this heterogeneous data format must implement or derive from some uniform interface. 

It can very well be possible, that the preferred approach as designated by the language designers, is to use code gen first - some repeated logic may be generated, it is free of effort to the user, and code size is practically a negligible concern these days. From there the user can selectively implement a uniform interface e.g. `List`, `Map` on their data class.

**Comment by FireSourcery** [comment]
Again, thank you for the detailed response. This helps me immensely in selecting my own priorities. That essentially concludes any practical inquiries for me. Whichever direction the language goes with can be applied to my use case.

Please allow me to clarify:

I am absolutely not suggesting runtime introspection. I can see that as being far too expensive as well. What I am suggesting is parameterizing the fields of a data class, their attributes, at compile time and passing that information to a super interface. Simply a name/identifier and type will do, effectively a way of referring to the getter, and memory allocation requirement. Nothing more than 

```dart
enum PersonField<V> with DataField<V> {
  id<int>(),
  age<int>(),
  name<String>();
}
```
A list of function pointers, perhaps even the virtualization table belonging to the data class, would likely suffice in absence of the serialization use cases. Perhaps I should have clarified, by "referring to fields by name", I do mean to included a _named_ getter, it just so happens we'd like a corresponding String as well. 

This much could be even be generated. From there a super interface should have all necessary information for general operations, reusable routines, including a hash and == operator. For this example I selected primitive data types for simplicity. The general case would complicate things a bit, handling could be done with a Composite/tree pattern nonetheless. The final piece is the user's data class must provide a function to map the contents of the super interface to that particular data class. As far as performance/optimization is concerned - The super interface may need to do some amount of buffering. This should only involve holding a reference to the data contents and not involve buffering the data itself. Fields are often not many. I am currently playing with the idea of using a simple fixed map... better illustrated

```dart
class FixedMapModified<E extends Enum, V> with MapBase<E, V>, FixedMap<E, V> {
  const FixedMapModified(this._source, this._modified);
  final FixedMap<E, V> _source;
  final Iterable<MapEntry<E, V>> _modified;

  @override
  List<E> get keys => _source.keys;
  @override
  V operator [](E key) {
    return _modified.firstWhere((element) => element.key == key, orElse: () => MapEntry(key, _source[key]!)).value;
  } 
}

class FixedMapBuffer<E extends Enum, V> with MapBase<E, V?>, FixedMap<E, V?> {
  FixedMapBuffer(this._keys, [List<V>? values]) : _values = values ?? List<V?>.filled(_keys.length, null);

  final List<E> _keys;
  final List<V?> _values;
  @override
  List<E> get keys => _keys;
  @override
  V? operator [](E key) => _values[key.index];
  @override
  void operator []=(E key, V? value) => _values[key.index] = value; 
}
```

A `Iterable.generate` or  `sync*` generator variety may optimize further.

I did not expect code size to be of a major concern. But if that's the case, then even more so are the benefits of this approach, parameterizing fields and delegating to reusable routines. It almost certainly results in smaller code size, as the only unique code to each data class is the description of fields. What I personally find favorable in this approach is that it provides a common platform for further development, the general motivation for any interface.
