### ISSUE TITLE
Analyzer quick-fix: Add import with `show`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#55842]
The analyzer has a quick-fix, "Import library ...", for adding an import for a name that's not in the current library's scope.

I'd like a variant of that, which adds the same import, but with a `show Name` added, an `Import library ... with show ...`, or something like that.

The functionality to add a name to a `show` clause already exists:
- I can move the cursor the import and select "add explicit 'show' combinator" which adds the `show` clause for all already used names, and
- if I add the `show Name` myself, then writes the name of another declaration from the same library, I get an "Update library ... import" which adds the name to the `show` clause. 

I just want to avoid moving the cursor away from where I'm writing, and get the `show` clause from the start.

Example of what I'd want:
```dart
void main() {
  Queue/* Press ctrl+. here, select "import library 'dart:collection' with show" */ queue;
  HashMap/* Press ctrl+.here, select "Update library 'dart:collection' import" */ map;
}
```

**Comment by FMorschel** [comment]
Related to https://github.com/dart-lang/sdk/issues/32234.

**Comment by FMorschel** [comment]
https://dart-review.googlesource.com/c/sdk/+/396564
