### ISSUE TITLE
[CP] [dart2wasm] Only perform compile-time lookup in constant list if index is in-bounds

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55853]
### Commit(s) to merge

827a7c4e95e7e453f18f9fd04fb1cff0fdd6af63

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/368304

### Issue Description

Compiler crashes when compiling list index access code when it can infer the list to be a constant list and the index to be constant but the index is out-of-bounds.

### What is the fix

Only perform the optimization if the list index is in-bounds.

### Why cherry-pick

Users have hit this issue.

### Risk

Low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55817

**Comment by athomas** [comment]
@mraleph please review.

**Comment by mraleph** [comment]
LGTM

**Comment by mkustermann** [comment]
The CL has been merged to stable channel

**Comment by mkustermann** [comment]
It seems 3.4.2 was released. @athomas can the CP github issues (like this) be closed now?
