### ISSUE TITLE
[CP] [dart2wasm] Remove experimental warning for dart compile wasm and make `dart compile --help` show the wasm subcommand

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55857]
### Commit(s) to merge

004d6a3fad85e53c0b6f36d7b4e84993db9e1050

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/368420

### Issue Description

The `dart compile wasm` command is hidden and running it gives an experimental warning.

### What is the fix

Make the `dart compile wasm` command public and remove the experimental warning.

### Why cherry-pick

Avoids user confusion about us advertising dart2wasm as being stable but still issuing experimental warning

### Risk

Low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/32894

**Comment by athomas** [comment]
LGTM

**Comment by mkustermann** [comment]
The CL landed on stable branch.

**Comment by mit-mit** [comment]
LGTM

**Comment by athomas** [comment]
Released in 3.4.2.
