### ISSUE TITLE
[DAP] `--pause-isolates-on-start` and `--pause-isolates-on-exit` flags are not set for attach workflows

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#55859]
If the VM flags `--pause-isolates-on-start` and `--pause-isolates-on-exit` are not already set before the DAP attach workflow, then they never get set. 

That's because we never set them after looping through all the VM flags here: https://github.com/dart-lang/sdk/blob/238a29d8a14b7112e00db98c39e261315a96991d/pkg/dds/lib/src/dap/adapters/dart.dart#L857

FYI @DanTup - I have a fix prepared and will send it out shortly.

**Comment by DanTup** [comment]
@elliette I'm not sure I understand why this doesn't work. Wouldn't they be set during the loop?

We enumerate the flags (which comes from getFlagList() and includes all flags), then when we find pauseOnStart/pauseOnExit, the condition on line 857 is false (the name is not null and it is a pause-isolates flag) so we carry on. The condition on 859 is false (the flag is not already true), so we fall into 867 which calls `_setVmflagTo` (and the booleans like `pauseIsolatesOnStartSetByDap` defaulted to true so already match)?

(maybe it'll be clearer when I see your fix though :-) )

**Comment by elliette** [comment]
Hmm in g3 this call to `getFlagList` is returning an empty list: https://github.com/dart-lang/sdk/blob/238a29d8a14b7112e00db98c39e261315a96991d/pkg/dds/lib/src/dap/adapters/dart.dart#L852

**Comment by elliette** [comment]
> Hmm in g3 this call to `getFlagList` is returning an empty list:
> 
> https://github.com/dart-lang/sdk/blob/238a29d8a14b7112e00db98c39e261315a96991d/pkg/dds/lib/src/dap/adapters/dart.dart#L852

Ah hah: https://github.com/dart-lang/webdev/blob/15028c4fd1488376de701230bb57ac214549526b/dwds/lib/src/services/chrome_proxy_service.dart#L760-L764

So maybe the right fix is to implement this in DWDS

**Comment by DanTup** [comment]
Ah, I see. The docs for `getFlagList()` say:

> The getFlagList RPC returns a list of all command line flags in the VM along with their current values.

I don't know if it's reasonable for web to have all the CLI flags in there, but if web has behaviour for pause-on-start/exit then probably it should at least include those there (and with the correct values that were set).
