### ISSUE TITLE
Switch Expressions conversion assist should use logical-or when multiple cases share a body

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#55861]
From the [docs](https://dart.dev/language/patterns#switch-statements-and-expressions):

> [Logical-or patterns](https://dart.dev/language/pattern-types#logical-or) are useful for having multiple cases share a body in switch expressions or statements:
> 
> ```dart
> var isPrimary = switch (color) {
>   Color.red || Color.yellow || Color.blue => true,
>   _ => false
> };
> ```

When we have a switch statement like the following, the assist for turning it into a switch expression doesn't show:

```dart
int a(int x) {
  switch (x) {
    case 0:
      return 0;
    case 2:
    case 1:
      return 1;
    default:
      return throw UnimplementedError();
  }
}
```

![image](https://github.com/dart-lang/sdk/assets/52160996/5b1a52a7-48e1-4bb7-b4d0-01ec513fe20f)

Only if there is a single case with a specific body:

![image](https://github.com/dart-lang/sdk/assets/52160996/95ee4bdf-3b4a-4f19-a0aa-28e61a6d331e)

In this case, I believe the assist should appear and create a logical-or pattern for them.

**Comment by FMorschel** [comment]
I'm not sure if you agree, but I think _maybe_ there could be an assist for merging all of those cases with a logical-or pattern. And that could be run separately or with this assist.

So cases like the above could become:

```dart
switch (x) {
  case 0:
    return 0;
  case 1 || 2: // or swapped I'm not sure what to put first here (not sure it matters, just an UX question)
    return 1;
  default:
    return throw UnimplementedError();
}
```

And then the assist for replacing the switch does appear.

**Comment by FMorschel** [comment]
Created https://github.com/dart-lang/sdk/issues/56180 for the above comment.

**Comment by FMorschel** [comment]
Looking at the code and blame for this feature and trying to understand it to implement it by myself, I just wanted to point out that this is already something working but for some reason not all cases.

Here is the original issue: https://github.com/dart-lang/sdk/issues/54567

If I try to do something like:

```dart
enum A {
  a,
  b,
  c,
  d
}

int a(A x) {
  switch (x) {
    case A.a:
      return 0;
    case A.b:
    case A.c:
      return 1;
    default:
      return throw UnimplementedError();
  }
}
```

Then the assist does appear. So something is not working as it should. Maybe something related to integers not having a finite amount of options? 

Will take a look into it whenever I can, just a little update here.

**Comment by bwilkerson** [comment]
In the latest version (on HEAD), if I paste the original example into a file:
```dart
int a(int x) {
  switch (x) {
    case 0:
      return 0;
    case 2:
    case 1:
      return 1;
    default:
      return throw UnimplementedError();
  }
}
```

When I click on the `switch` keyword and open the lightbulb menu, I see a 'Convert to switch expression' option that produces the following:
```dart
int a(int x) {
  return switch (x) {
    0 => 0,
    2 || 1 => 1,
    _ => throw UnimplementedError()
  };
}
```

It appears to me that the limitation has been fixed, but the issue wasn't updated appropriately.

If I'm missing something please let me know and I'll re-open the issue, but for now I'm going to close it.
