### ISSUE TITLE
[CP] Revert "[vm, gc] Incremental compaction, take 2."

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55867]
### Commit(s) to merge

f2f9e7f89af4ad5b82f5fe6e7775c70081e087f6

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/368620

### Issue Description

The `origin/beta` contains a GC bug which was recently introduced and reverted on main, we should include the revert in the beta branch

### What is the fix

Revert the GC change that caused random crashes

### Why cherry-pick

To avoid random crashes

### Risk

If CI is green: Low

### Issue link(s)

various-g3-crashes

**Comment by athomas** [comment]
LGTM
