### ISSUE TITLE
Divergent execution with ARM64 vsub

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#55879]
```dart
import 'dart:typed_data';

Float32x4 var35 = Float32x4.zero();
Int32x4 var37 = Int32x4.bool(true, true, true, true);

main() {
  var35 -= var35.clamp(Float32x4.fromInt32x4Bits(var37),
                       Float32x4.splat(0.8757579678595059));
  print('var35: $var35');
}
```
```
out/DebugSIMARM64/dart --old_gen_heap_size=128 fuzz.dart
out/ReleaseSIMARM64C/dart --intrinsify=false --use-slow-path --old_gen_heap_size=128 fuzz.dart
diff a.txt b.txt
1c1
< var35: [nan, nan, nan, -nan]
---
> var35: [-nan, -nan, -nan, -nan]

```

[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8746906971663123073/+/u/collect_shards/dartfuzz_-_generated_programs_shard_37/task_stdout_stderr:_dartfuzz_-_generated_programs_shard_37)

**Comment by lrhn** [comment]
That seems to be within documented behavior for `Int32x4.bool` (read: constructor is completely undocumented, I have no idea what it's intended to do).

The documentation for `double.toString` says: 
> Returns "NaN" for the Not-a-Number value.

That's not entirely covering, because there is no "_the_ NaN value", there are 2<sup>53</sup> -2 of them. 
Still, I'd prefer if they all printed `NaN` without a sign, no matter what the sign bit is.

**Comment by rmacnak-google** [comment]
It's concerning that intrinsified version has output lanes that differ even though all the input lanes are the same.

**Comment by AkashKeote** [comment]
import 'dart:typed_data';

Float32x4 var35 = Float32x4.zero();
Int32x4 var37 = Int32x4.bool(true, true, true, true);

bool isNaN(Float32x4 value) {
  return value.x.isNaN || value.y.isNaN || value.z.isNaN || value.w.isNaN;
}

Float32x4 normalizeNaN(Float32x4 value) {
  return Float32x4(
    value.x.isNaN ? 0.0 : value.x,
    value.y.isNaN ? 0.0 : value.y,
    value.z.isNaN ? 0.0 : value.z,
    value.w.isNaN ? 0.0 : value.w,
  );
}

void main() {
  var clampedValue = var35.clamp(Float32x4.fromInt32x4Bits(var37), Float32x4.splat(0.8757579678595059));

  if (isNaN(clampedValue)) {
    clampedValue = normalizeNaN(clampedValue);
  }

  var35 -= clampedValue;

  print('var35: $var35');
}

**Comment by AkashKeote** [comment]
tell me is this work now

**Comment by rmacnak-google** [comment]
dartfuzz found another one with Float64x2.

```
import 'dart:typed_data';

Float64x2 var39 = Float64x2.splat(-0.40150792030288873);

main() {
  var39 -= var39.sqrt();
  print(var39);
  if (!identical(var39.x, var39.y)) {
    throw "Wrong!";
  }
}
```
