### ISSUE TITLE
[CP] [dart2wasm] Fix array.new_fixed calls with too large size

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55873]
### Commit(s) to merge

c7834b676494

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/368644

### Issue Description

Certain large apps can result in dart2wasm emitting an `array.new_fixed` instruction with more than 10000 elements, which causes a runtime error when running in browsers.

### What is the fix

Avoid using `array.new_fixed` if the array is larger than 10000

### Why cherry-pick

Users are hitting this on stable channel.

### Risk

Low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55396, https://github.com/dart-lang/sdk/issues/55872

**Comment by itsjustkevin** [comment]
@mraleph could you take a look at this cherry-pick request?

**Comment by mraleph** [comment]
LGTM

**Comment by mkustermann** [comment]
@itsjustkevin if you approve, I'll merge the CL

**Comment by itsjustkevin** [comment]
Approved! Merge away @mkustermann!
