### ISSUE TITLE
[CP] Release DevTools 2.36.0

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#55876]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/368720

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/368762

### Issue Description

This beta release of DevTools missed the code cutoff because we were targeting the date listed on go/dash-team-releases. Since the beta release went out early, we missed the cut off and need to cherry-pick.

### What is the fix

Cherry pick the commit that releases DevTools 2.36.0 into the Dart SDK, onto the Dart / Flutter beta branch.

### Why cherry-pick

This is the regularly scheduled monthly DevTools release that missed the cutoff. If we do not CP, we will miss an entire release cycle before the next Dart / Flutter beta releases.

### Risk

Low. 

### Issue link(s)

n/a

### Extra Info

This CP also requires a CP into Flutter: https://github.com/flutter/flutter/pull/149345.

**Comment by athomas** [comment]
LGTM
