### ISSUE TITLE
data transfer between two socket using pipe not working correctly

### ISSUE THREAD

**Issue by superorange** [dart-lang/sdk#55885]
dart info
#### General info

- Dart 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "macos_x64"
- on macos / Version 13.2.1 (Build 22D68)
- locale is zh-Hans-CN

#### Project info

- sdk constraint: '^3.3.4'
- dependencies: crypto, ffi, ffigen
- dev_dependencies: lints, test

#### Process info

| Memory |   CPU | Elapsed time | Command line                                                                               |
| -----: | ----: | -----------: | ------------------------------------------------------------------------------------------ |
| 268 MB |  3.8% |     22:25:24 | dart language-server --client-id=IntelliJ-IDEA --client-version=IU-241.14494.240 --protocol=analyzer |
|  30 MB |  0.0% |     22:24:10 | dart language-server --client-id=IntelliJ-IDEA --client-version=IU-241.14494.240 --protocol=analyzer |
|  16 MB |  0.0% |     22:24:03 | dart language-server --client-id=IntelliJ-IDEA --client-version=IU-241.14494.240 --protocol=analyzer |
|  74 MB | 57.4% |        00:01 | dart pub outdated --show-all --json                                                        |
|  23 MB |  0.1% |     22:25:20 | flutter_tools.snapshot daemon                                                              |
|  13 MB |  0.0% |     22:24:05 | flutter_tools.snapshot daemon                                                              |
|  14 MB |  0.1% |     22:23:59 | flutter_tools.snapshot daemon                                                              |

dart code
```dart
import 'dart:io';
import 'dart:async';

Future<void> forwardClientConnection(Socket clientSocket) async {
  final serverSocket = await Socket.connect('127.0.0.1', 5201);
  transfer(clientSocket, serverSocket);
  transfer(serverSocket, clientSocket);
}

void transfer(Socket src, Socket dest) {
  src.cast<List<int>>().pipe(dest);
}

void main() async {
  final server = await ServerSocket.bind(InternetAddress.anyIPv4, 8084);
  print('Listening on port 8084');
  await for (final clientSocket in server) {
    print('Accepted connection from ${clientSocket.remoteAddress}');
    forwardClientConnection(clientSocket);
  }
}

```
Stpes
```bash
dart run main.dart
iperf3 -s 
iperf3 -c 127.0.0.1 -p 8084  -R
```
No data return
result:
Connecting to host 127.0.0.1, port 8084
Reverse mode, remote host 127.0.0.1 is sending
[  5] local 127.0.0.1 port 55412 connected to 127.0.0.1 port 8084
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec

**Comment by superorange** [comment]
Observed that the client does not receive data, and the memory usage of the dart run command increases sharply.

**Comment by aam** [comment]
This seems to be due to aggregating all incoming bytes until everything was consumed https://github.com/dart-lang/sdk/blob/43791032fcf75102b21bf84f77eb2db24797caca/sdk/lib/_internal/vm/bin/socket_patch.dart#L1115.
We perhaps should set maximum aggregated buffer size to avoid out of memory problems.

Also `BytesBuilder` set up at https://github.com/dart-lang/sdk/blob/43791032fcf75102b21bf84f77eb2db24797caca/sdk/lib/_internal/vm/bin/socket_patch.dart#L1106 should not copy received bytes.
