### ISSUE TITLE
[CP]  [dart2wasm] Only share type parameter fields if nullability allows

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55895]
### Commit(s) to merge

e6e9b4e5953dc554c513932c64f57d18ad08cb90

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/369241

### Issue Description

A bug in the dart2wasm compiler can lead to a type parameter type to have incorrect nullability

### What is the fix

Fix sharing of type parameter values with super types if nullability is changed.

### Why cherry-pick

External user hit this (https://github.com/dart-lang/sdk/issues/55741)

### Risk

Low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55741

**Comment by athomas** [comment]
Limited impact, has coverage, LGTM
