### ISSUE TITLE
[CP] [dart2wasm] Make `dart compile wasm` accept --enable-experiment flags and pass those to compiler

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55894]
### Commit(s) to merge

3b02e41af1e9f5c60c7526cc87d47ae80a14c6c3

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/369240

### Issue Description

We want `dart compile wasm` to support `--enable-experiment` so that e.g. the test runner can use it (https://github.com/dart-lang/test/pull/2233)

### What is the fix

Add `dart compile wasm` support for `--enable-experiment`.

### Why cherry-pick

So that e.g. the test runner can use it (https://github.com/dart-lang/test/pull/2233)

### Risk

Low

### Issue link(s)

-

**Comment by kevmoo** [comment]
LGTM!

**Comment by mit-mit** [comment]
SGTM

**Comment by mkustermann** [comment]
The CP was merged.
