### ISSUE TITLE
dart2wasm --debug flag not working

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/sdk#55903]
The following command runs code with assertions disabled, which means that it is not running in debug mode:
```console
dart test -p chrome -c dart2wasm --debug
```

Unsure if this affects dart2wasm directly or the flag just isn't being passed

Related issues:
https://github.com/flutter/flutter/issues/148850

**Comment by mkustermann** [comment]
> The --debug flag does not seem to work for dart2wasm either. That is probably the root cause of this

The Dart2Wasm compiler is only used for `--profile` / `--release` builds (just like Dart2JS). For iterative development the DDC compiler (which also compiles to JS) is used (or the VM's JIT). In the short term dart2wasm will not have a development compiler (with hot-restart / hot-reload).

That being said, one can use Dart2Wasm for profile/release builds and still enable assertions - via `dart compile wasm --enable-asserts test.dart`.

`dart test ...` is using `package:test` under the hood which doesn't seem to have a way to enable assertions when running under wasm - see [package:test_core/src/runner/wasm_compiler_pool.dart](https://github.com/dart-lang/test/blob/43ad4cd8408d8d156b1322/pkgs/test_core/lib/src/runner/wasm_compiler_pool.dart#L36).

@Rexios80 Is your main request to run tests with assertions enabled? In that case consider filing an issue at https://github.com/dart-lang/test instead.

/cc @kevmoo

**Comment by Rexios80** [comment]
No it's just a similar issue I thought might be related, but after what you said they're not actually related issues

**Comment by Rexios80** [comment]
Yes you are correct. I will file an issue there instead. Thanks!
