### ISSUE TITLE
[Null-aware elements] Experiment flag

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#55926]
This is the implementation issue for a new language feature: https://github.com/dart-lang/language/blob/main/working/0323-null-aware-elements/feature-specification.md

- [ ] Add an experiment flag named `null-aware-elements`
- [ ] Eventually, add an experiment and release version to gate the feature.
- [ ] Then enable by default when ready to release.

**Comment by sgrekhov** [comment]
There is a typo above. Experimental flag name, according to the specification, should be `null-aware-elements`

**Comment by lrhn** [comment]
Fixed.
