### ISSUE TITLE
[dart2wasm] iFrame locks position on transition into view

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#55942]
In DevTools, we use iFrames for a couple of features:
1) The embedded Perfetto trace viewer on the Performance page
2) DevTools extensions

In both cases, the iFrame is transitioned into view by a Flutter tab view. Upon selecting the "Timeline Events" tab on the Performance page or upon selecting a top level tab for a DevTools extension, the iFrame locks its position before fully transitioning into view:
![Screenshot 2024-06-05 at 9 56 17 AM](https://github.com/dart-lang/sdk/assets/43759233/9a1e3a6a-0408-406c-b97a-75aeaa565411)
![Screenshot 2024-06-05 at 9 55 52 AM](https://github.com/dart-lang/sdk/assets/43759233/d3ec0495-d3ea-4d6b-85de-021cfa89737d)

Requirements:
- Pull the latest code from the flutter/devtools master branch
- Pull the latest code from the Dart SDK (or patch [this change](https://dart-review.googlesource.com/c/sdk/+/369100) if it has not landed yet.)
- Set up your DevTools environment so that
  - You have access to the `devtools_tool` executable - [docs](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#set-up-your-devtools-environment)
  - You have the LOCAL_DART_SDK environment variable set - [docs](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#frontend--devtools-server)

Repro steps:
1. Build DevTools from source with wasm: `devtools_tool serve --wasm`. If you want to build with `--no-strip-wasm`, add the flag [here](https://github.com/flutter/devtools/blob/master/tool/lib/commands/build.dart#L103) before serving DevTools.
2. Run the Flutter gallery app (this app depends on `package:provider`, which has a DevTools extension)
3. Copy the VM service URI from the Flutter gallery app and connect it to the DevTools instance you just served with wasm.
4. Navigate to either the Performance screen > Timeline Events OR to the top level Provider screen tab (should be present as long as you are running flutter gallery) to observe the incorrect iFrame position.

If this does not repro on the first try, refresh the DevTools window in the browser and try again.

**Comment by mkustermann** [comment]
@kenzieschmoll Is there any indication this is a compiler or library bug? If not, I would suggest to move this to the flutter issue tracker and have the flutter web team have a look (/cc @eyebrowsoffire @yjbanov ) as the issue may very well be something higher up the stack.

**Comment by eyebrowsoffire** [comment]
Yes, this should be assigned to flutter. I am pretty sure this is because https://github.com/flutter/flutter/issues/133466 is not implemented yet.

**Comment by kenzieschmoll** [comment]
Transferred to the flutter/flutter repo: https://github.com/flutter/flutter/issues/149909. Closing this issue in favor of that one.
