### ISSUE TITLE
[CP] [vm/ffi] Fix variadic arguments on MacOS Arm64

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55943]
### Commit(s) to merge

* c0b938c2286d99be3ff65f62bb3e627dd0fb2361

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/369822

### Issue Description

Variadic arguments on Mac Arm64 weren't working correctly due to misalingment.

### What is the fix

Distinguishing stack alignment of FFI call arguments between varargs and non-varargs.

### Why cherry-pick

To prevent JNIgen having to target the 3.5 master branch for Flutter/Dart.

* https://github.com/dart-lang/http/issues/1213#issuecomment-2147125270

### Risk

Small: It's a couple of lines of code CL (with many lines of code tests).

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55471

**Comment by mit-mit** [comment]
sgtm

**Comment by athomas** [comment]
Released in 3.4.4.
