### ISSUE TITLE
`meta` limitation: `useResult` not available in `factory` constructors

### ISSUE THREAD

**Issue by bwc-x** [dart-lang/sdk#55962]
Can't seem to find any existing open/closed issue regarding this. 

Currently facing a situation, roughly akin to:

```dart
import 'package:meta/meta.dart';

extension Ext on Class {
  void doSomeWork(int i) {
    print('$this + $i = ...');
    return this;
  }
}

class Class {
  const Class();
  const factory Class.sub() = SubClass;
}

class SubClass extends Class {
  const SubClass();
}

void main() {
  Class.sub(); // .doSomeWork(5) meant to be called, yet skipped on accident
}
```

Given a new instance, built using a factory - sometimes containing a great deal of inner parameters, passed to it - it is impossible to check whether the result is actually used. The slightly more practical (actual) use case for this involves passing a rather complex instance, built through a redirecting `const factory` into a Flutter's `BuildContext` for subsequent state propagation / widget tree update. Assigning it to a temporary variable beforehand, though necessary at times, is completely redundant in the rest of cases.

The `@useResult` annotation would be nothing short of perfect for this. Yet it vehemently refuses to do its job, insisting that `The annotation 'useResult' can only be used on fields, getters, methods, top-level functions, or top-level variables.` While ignoring that message makes it ignore **all** the uses of the resulting instance completely. 

![image](https://github.com/dart-lang/sdk/assets/66522734/de5da7ab-ed4a-416d-85e6-4bc045538e0b)

Any way to patch this up? 

A rather messy fix for this currently involves either prior redundant assignment, or an even more redundant `static` method declaration - reduplicating the whole factory constructor in whole merely for a chance to annotate it with `@useResult`. 

```dart
class Class {
  const Class();
  @useResult // no errors
  static Class sub() => SubClass();
}
```

Wouldn't mind doing this either, if it wasn't for the `freezed` 's own reliance on factory constructors for its code generation.

**Comment by srawlins** [comment]
I don't see why you shouldn't be able to annotate any kind of constructor with `@useResult`. The docs don't include it currently. https://pub.dev/documentation/meta/latest/meta/useResult-constant.html

@bwilkerson @pq any opinions?

**Comment by pq** [comment]
> I don't see why you shouldn't be able to annotate any kind of constructor with `@useResult`. 

I agree. I expect it was just an oversight.

**Comment by bwilkerson** [comment]
I also agree. I would think that allowing it on constructors should be well defined and reasonable.

**Comment by srawlins** [comment]
Short memory. I did this two months ago. You just need the next Dart version. :D Maybe not released yet. https://github.com/dart-lang/sdk/commit/eb7ba49329a4e19b864d32ee8c4c76a7d5fc9e87
