### ISSUE TITLE
future doesn't throw correctly inside try block  

### ISSUE THREAD

**Issue by SamMotta** [dart-lang/sdk#55970]
Flutter 3.22.1
Dart 3.4.1

packages: riverpod and fpdart

I use `unnecessary_await_in_return` lint

Code:
![image](https://github.com/dart-lang/sdk/assets/49457269/1e954dbd-1db8-4abd-bcf9-e62e775ace3c)

![image](https://github.com/dart-lang/sdk/assets/49457269/45043382-c594-46f8-99ec-3f44e0424d4d)

if await is removed in first image, it doesn't throw like intended.

**Comment by lrhn** [comment]
Known issue. The `await` is not unnecessary if you are returning a future inside a `try`/`catch`, because of a long-standing bug in returning futures.
