### ISSUE TITLE
[CP] [dart2wasm] Make `dart compile wasm` compiled apps disable `dart.library.ffi`

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55979]
### Commit(s) to merge

847c35612ad295f44b5d6e1b061f7423efa817cf

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/370880

### Issue Description

Packages on pub use conditional imports that branch on `dart.library.ffi`. The ffi-specific code is meant to be run on the VM. Unfortunately currently this also evaluates to `true` in dart2wasm, which makes apps that work with dart2js not work with dart2wasm due to different evaluation of the conditional import.

### What is the fix

Change dart2wasm to make this conditional import evaluate to `false`.

### Why cherry-pick

Users are hitting this when using `package:flutter_svg` which uses `package:vector_graphics_compiler` which uses `dart:ffi.

### Risk

As always: If CI passes the risk is low.

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55948

**Comment by mkustermann** [comment]
/cc @athomas for awareness

If flutter also releases a new stable with this CP in, it may need to cherry-pick:
* in engine https://github.com/flutter/engine/commit/1f3938d80e6e60dd02b70b71a940f84a1d519c57 & https://github.com/flutter/engine/commit/ae9e09285c8a6b73d6d6a47652d8cc835639a1e1 (get rid of `dart.library.ffi` conditional imports usage in engine)
* in framework https://github.com/flutter/flutter/commit/c0b2645b8a15b69f5697afef0523936bafb0fe73 (gets rid of `const bool.fromEnvironment('dart.library.ffi')` usage in framework)

**Comment by athomas** [comment]
LGTM

**Comment by mkustermann** [comment]
The CL landed.

**Comment by mkustermann** [comment]
I believe this was released yesterday with `Dart SDK 3.4.4` . So we can close this.
