### ISSUE TITLE
[CP] Pub: Properly handle case where the client is unable to fetch advisories

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#55981]
### Commit(s) to merge

Landed in pub as https://github.com/dart-lang/pub/commit/e05f76bf2cbd44b0622d5da86486fd6b1243df94
Rolled to sdk in https://dart-review.googlesource.com/c/sdk/+/370882

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/370885

### Issue Description

When attempting to fetch advisories from a pub server, the client would crash if they were not available.

This breaks pub for mirrors of pub.dev that fail to proxy advisories.

### What is the fix

Print a warning instead of crashing

### Why cherry-pick

This impacts users of mirrors that have not been updated to mirror advisories - they are not able to get a resolution with pub.

### Risk

Medium-low

### Issue link(s)

https://github.com/dart-lang/pub/issues/4269

**Comment by mit-mit** [comment]
sgtm

**Comment by sigurdm** [comment]
cc @szakarias

**Comment by athomas** [comment]
Small change, good coverage, LGTM

**Comment by athomas** [comment]
Released in 3.4.4.
