### ISSUE TITLE
dart.exe take %97 of memory make pc laggy 

### ISSUE THREAD

**Issue by mohammedkh96** [dart-lang/sdk#55984]
![image](https://github.com/dart-lang/sdk/assets/128855514/922e853e-76bf-478e-9bd4-0c40cf14a5dd)

**Comment by parlough** [comment]
Could you provide more details about your Dart setup and running processes (`dart info` provides this) when this is happening? Any other details about the project(s) you are working on/analyzing would be helpful as well. Thanks so much!

**Comment by mohammedkh96** [comment]
this was happened only by running any flutter or dart command in terminal 
like ( flutter pub get , flutter doctor , flutter upgrade , flutter run ,)

**Comment by devoncarew** [comment]
Can you run `dart info` and post the results here? It'll provide details about the running dart applications.

**Comment by mraleph** [comment]
Unactionable without additional information.
