### ISSUE TITLE
[wildcards] Consider quick fix: convert `UNUSED_CATCH_CLAUSE` to wildcard

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#55980]
Specifically,

```dart
f() {
  try {
  } on String catch (exception) {
  }
}
```

_might_ be fixed to:

```dart
f() {
  try {
  } on String catch (_) {
  }
}
```

in addition to the current fix which removes the clause altogether:

```dart
f() {
  try {
  } on String {
  }
}
```

**Question:** does such a fix add value?

@kallentu @bwilkerson

**Comment by bwilkerson** [comment]
The two fixes seem to me to be semantically equivalent. The code will be executed if a `String` is thrown, and in neither case can the user refer to either the thrown object or the stack trace.

I would want an `unnecessary_catch_clause` warning on the longer version.

**Comment by pq** [comment]
> I would want an unnecessary_catch_clause warning on the longer version.

In that case we don't want a fix to get us to it. My feeling too. Thanks!
