### ISSUE TITLE
pkg-bot tests are failing due to pub tar error

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55994]
There are new test failures on [[test] Fix isolate concurrency test to not pass in sound-null-safety flag](https://github.com/dart-lang/sdk/commit/e23e032406e2ab41641a5ea16a5f7020e06ff83b).

The tests
```
pkg/dartdev/test/commands/create_integration_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux-x64
unittest-asserts-release-mac-x64
unittest-asserts-release-win-arm64
```

Log:

```
Failed to extract `/Volumes/Work/s/w/ir/x/t/pub_YcbOxK/devtools_shared-10.0.0.tar.gz`: Invalid tar entry: ..
```

https://dart-ci.appspot.com/log/pkg-linux-debug/unittest-asserts-debug-linux-x64/20704/pkg/dartdev/test/commands/create_integration_test

Caused by:

* https://github.com/dart-lang/pub/issues/4305

**Comment by parlough** [comment]
This seems to be passing now (https://dart-current-results.web.app/#/filter=pkg/dartdev/test/commands/create_integration_test&showAll), closing in favor of https://github.com/dart-lang/pub/issues/4305 which was fixed.
