### ISSUE TITLE
unused variable warning no longer reporting when creating multiple variables in irrefutable pattern match and only using some variables

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/sdk#56005]
In the following code `b`, `x` and `isEmpty` should produce an analyzer warning for unused variable, but in recent versions of dart it does not. 

```dart
void main() {
  final (a, b) = (1, 2);
  final [x, y] = [1, 2];
  final String(:length, :isEmpty) = 'hello';
  print(a);
  print(y);
  print(length);
}
```

I am using `Dart SDK version: 3.5.0-254.0.dev (dev) (Wed Jun 12 05:04:01 2024 -0700) on "windows_x64"` locally.

On dartpad, you can see no warning reported when switching to `beta` or `main` channel, but it works correctly on `stable`.

**Comment by srawlins** [comment]
This is intentional, to allow for variables to be present for documentation purposes. See https://github.com/dart-lang/sdk/issues/54854
