### ISSUE TITLE
[breaking change] Remove `Object` from `ExternalDartReference`'s implemented types

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#56015]
### Change Intent

`dart:js_interop`'s [`ExternalDartReference`](https://api.dart.dev/main/dart-js_interop/ExternalDartReference-extension-type.html) allows users to pass opaque references to Dart objects such that they can be passed through JavaScript back to Dart efficiently. The library provides two extension methods: `toExternalReference` and `toDartObject` to convert to and from the opaque reference.

`ExternalDartReference` will now instead be generic and `toExternalReference` will return a reference to any `T`, including `null`. Therefore, the extension type can longer implement `Object`, as the representation type will be nullable.

### Justification

`ExternalDartReference` should be generic to avoid extra downcasts when compiling to JS, and to be able to represent what type of Dart object the reference refers to.

On top of this, we should include `null` values i.e. `T extends Object?` instead of `T extends Object`, so that other generic interfaces e.g. `Finalizer` that have an unbounded `T` do not have to include extra null-checks to be able to convert to and from an `ExternalDartReference`.

Original issues: https://github.com/dart-lang/sdk/issues/55536, https://github.com/dart-lang/sdk/issues/55342

### Impact

Low. There is low usage in two repos:

1. Flutter engine in order to use the JS `FinalizationRegistry`. [0](https://github.com/flutter/engine/blob/be29403c8b0c18f22abf370b52abbe12d0d19aef/lib/web_ui/lib/src/engine/dom.dart#L3665) [1](https://github.com/flutter/engine/blob/be29403c8b0c18f22abf370b52abbe12d0d19aef/lib/web_ui/lib/src/engine/skwasm/skwasm_impl/memory.dart#L29) [2](https://github.com/flutter/engine/blob/be29403c8b0c18f22abf370b52abbe12d0d19aef/lib/web_ui/lib/src/engine/canvaskit/native_memory.dart#L23) [3](https://github.com/flutter/engine/blob/be29403c8b0c18f22abf370b52abbe12d0d19aef/lib/web_ui/test/canvaskit/canvaskit_api_test.dart#L1946)
2. [`svelte_js.dart`](https://github.com/ykmnkmi/svelte_js.dart). The owner is the same user who originally filed [the request](https://github.com/dart-lang/sdk/issues/55536).

### Mitigation

Any assignment of `ExternalDartReference` to `Object` can instead be made an assignment to `Object?`. For example:

```dart
// Object o = 0.toExternalReference;
Object? o = 0.toExternalReference;
```

```dart
// void f(Object o) {}
void f(Object? o) {}

f(0.toExternalReference);
```

### Change Timeline

The implementation is already done (see below). Ideally, this should go in beta 2 so that we don't have to wait for the next stable to submit this as breaking changes can't be submitted in the last beta.

### Associated CLs

https://dart-review.googlesource.com/c/sdk/+/370663

**Comment by srujzs** [comment]
@itsjustkevin I sent out an email to [announce@dartlang.org](mailto:announce@dartlang.org) for this. Let me know if you need anything else to start the review process. Thanks!

**Comment by kevmoo** [comment]
LGTM!

**Comment by sigmundch** [comment]
Thanks @srujzs. Breaking change LGTM too.

cc @mkustermann

**Comment by mkustermann** [comment]
@mit-mit @vsmenon The cutoff for next stable seems to be 1st of July. Can we get this approved beforehand to ensure it's included in the next stable? (If we delay this, people may start relying on this API more widely and changing it will cause more trouble for ecosystem, so the sooner we do it the better)

**Comment by mit-mit** [comment]
LGTM

**Comment by mit-mit** [comment]
Please make sure to post on dart-announce

**Comment by sigmundch** [comment]
Thanks, it was posted [last week](https://groups.google.com/a/dartlang.org/g/announce/c/jyEd69xaG7s). Usage currently is extremely minimal, so we don't expect to hear much.

**Comment by mkustermann** [comment]
@itsjustkevin Does it need signoff from anyone else or can this be marked as approved and @srujzs can go ahead and land the change?

**Comment by sigmundch** [comment]
FYI @itsjustkevin is OOO this week. We believe he will be back next week.

**Comment by sigmundch** [comment]
Looking at the updated calendar, it seems @itsjustkevin will be OOO until mid week. I reviewed previous breaking change requests and it appears we typically seek approval from representatives in Flutter and ACX as well.

@Hixie @leonsenft @vsmenon - could you take a look at this breaking change request? Thank you!

**Comment by leonsenft** [comment]
LGTM 👍

**Comment by Hixie** [comment]
no objection from me. cc @yjbanov

**Comment by vsmenon** [comment]
lgtm
