### ISSUE TITLE
[vm/ffi] Custom snapshot serializer/deserializers for user-defined classes backed by native state

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56026]
Pointers are not allowed to be in snapshots, due to the fact that when loading a snapshot it will be in a new process. So all pointers to memory regions or to symbols would be bogus.

The code should be written in a way such that all pointers are re-resolved when a snapshot is loaded. (E.g. `@Native`s for functions are reresolved.)

However, there are two cases in which we're going to have `Pointer`s when snapshotting in user-defined classes.

1. Native state that should be serializable and reconstructed during deserialization. The Dart code relies on the native state being faithfully reconstructed during appjit snapshot deserialization. For example a `Mutex`. (https://github.com/dart-lang/sdk/issues/56016)
2. Native state that should be reset during serialization. The Dart code relies on the native state being nulled out during deserialization. For example a `File`, it should be reopened.

If such objects are VM-defined, we can write custom serializers and deserializers for them. But if they are user-defined, users cannot currently.

Maybe we should consider having user-defined serialization/deserialization for snapshotting Dart objects backed by native state.

cc @kustermann @vegorov

**Comment by mkustermann** [comment]
> Maybe we should consider having user-defined serialization/deserialization for snapshotting Dart objects backed by native state.

I'm not sure I understand what you mean here.

The Dart VM has snapshot mechanism to snapshot the application program and corresponding VM-internals (e.g. JIT'ed code). Our snapshots do **not include** any runtime state of the application and I don't see why we would need that.

The [cl/370064](https://dart-review.googlesource.com/c/sdk/+/370064) may have included changes where it serializes application state accidentally, which would be a bug and I guess https://github.com/dart-lang/sdk/issues/56016 is tracking this, no?

**Comment by dcharkes** [comment]
Don't appjit snapshots capture application state?

**Comment by mkustermann** [comment]
> Don't appjit snapshots capture application state? (Like a smalltalk VM pause.)

No

Imagine our Dart SDK which contains AppJIT snapshots of our tools. If those snapshots would contain application state (e.g. open sockets when the AppJIT snaphot was created) - how would users that download the SDK and run those AppJIT snapshots re-create this native state (e.g. open socket)?

**Comment by dcharkes** [comment]
Allright!
