### ISSUE TITLE
Create the `dart:function` api to standardize the Callback implementation

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [dart-lang/sdk#56024]
Greetings, my proposal is simple and clear to standardize in a single place the commonly used higher-order function declarations to avoid repeated code that is difficult to maintain and repair. This idea is inspired by the JDK [java.util.function](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html) package.

This API could be implemented in 2 ways, which are as follows:

using [functional interfaces](https://github.com/dart-lang/language/issues/3889), personally I prefer this way you are the ones who decide, this would look like the following syntax

```dart
@functionalInterface
abstract interface class Consumer<T> {
  void apply(T value);
}
```

The other way to implement this API is to use `typedef`. This would look like this:

```dart
typedef Consumer<T> = void Function(T value);
```

As you can see this API is a fairly simple implementation that will really help improve the experience of using the Dart language base SDK. Personally I could create an implementation and upload it in pub.dev, the value of this implementation is that it is separate from the base SDK

**Comment by mraleph** [comment]
We have no plans to do this.
