### ISSUE TITLE
Optimize the `dart:async` API to use functional programming

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [dart-lang/sdk#56025]
Greetings, I want to describe the news to incorporate functional programming in the `dart:async` api

### Cambios para `Stream`

The Stream is one of those features that was already optimized from the beginning for functional programming, however it still has room for improvement thanks to the new [dart:function](https://github.com/dart-lang/sdk/issues/56024) api that will allow it to provide higher order functions that will be usable from the Stream itself. Let's see a example:

```dart
import "dart:function";
import "dart:isolate";

void main() {

  final Consumer<int> fn = (value) => print(value);

  Stream.fromIterable([1,2,3,4,5,6,7])
    .forEach(fn);
}

```

### Create Parallel Streams

The great novelty is the `Stream Parallel` is the ability to execute a Stream on multiple Isolates to execute in parallel, this allows greater performance to execute our algorithms.

For our Streams to be parallel, it is necessary to have an `Isolate Pool` provided by the [dart:isolate](https://github.com/dart-lang/sdk/issues/56022) api that allows all concurrency to be managed in an automated way, which is why the IsolatePoolExecutor class is used. Let's look at an example of a simple `Parallel Stream`.

```dart
import "dart:isolate";

void main() {

  ParallelStream.fromIterable([1,2,3,4,5,6,7])
    .map((value) => value * 2)
    .forEach((value) => print(value));
}
```

If we want to configure our own `Isolate Pool` we could do it in the following way:

```dart
import "dart:isolate";

void main() {
 late pool;

 if (System.isGpuAvailable) {
   final GpuInformation info = System.getGpu();

   pool = IsolatePoolExecutor.newGpuIsolatePool(info.numberOfCore);
 } else {
   final CpuInformation info = System.getCpu();

   pool = IsolatePoolExecutor.newFixedIsolatePool(info.numberOfCorePerformance, onlyPerformance: true);
 }

 ParallelStream.fromIterableWithIsolatePool(pool, [1,2,3,4,5,6,7])
    .map((value) => value * 2)
    .forEach((value) => print(value));
}
```

As you can see, with this implementation you can combine all the power of the Stream with the Isolate to create algorithms that take full advantage of the hardware, occupying all the processing cores or graphics cards for parallel computing.

Thanks to this implementation we can get closer to the world of 'Accelerated Computing', a philosophy promoted by Nvidia to create and promote its products, this is the future

**Comment by mraleph** [comment]
While we might introduce something like this in the future (we are looking at the ways to improve Dart's concurrency story), I don't see any reason to keep this extremely high level issue open.
