### ISSUE TITLE
Having an issue trying to convert an async function

### ISSUE THREAD

**Issue by andibardhi** [dart-lang/sdk#56032]
I am using the [JS](https://pub.dev/packages/js) package, and when trying to convert a method, I am encountering issues. The method has four parameters, one of which is a function called complete which is called at the end to finish everything. 

The syntax in JavaScript is as follows:

```
async (result, errors, complete, logs) => {
    // await a call to the BE  
    complete();
}
```

The syntax I have used in Flutter is as follows:

```
import 'dart:js' as js;

js.allowInterop(
  (result, errors, complete, logs) async {
    // await a call to the BE  
    complete();
  },
);
```

When I use plain JavaScript, it works without any issues. However, when I use the Dart function, I am getting this error: "Uncaught TypeError: T[_eval] is not a function". I haven't had issues before with async functions so I am not sure what the issue might be.

This documentation might help with the method I am trying to parse: https://docs.getnuvo.com/sdk/results

**Comment by srujzs** [comment]
That error looks like it's related to the RTI, but is general enough that it's hard to tell where the error is coming from. Is there a simple repro/your Dart code you can add here?

One thing that I suspect may be an issue (although may not be the current issue) is that with JS, the async function returns a `Promise`, whereas with a Dart async function, it returns a `Future<void>`. Any code that assumes that that function returns a `Promise` might not work. Converting the resulting `Future<void>` to a `JSPromise` using `dart:js_interop`'s [`toJS`](https://api.dart.dev/main/77496338dc0bf8716313f4321c63423e802937a3/dart-js_interop/FutureOfVoidToJSPromise/toJS.html) could work, but I'd need to see the code to figure out where that should go.

**Comment by andibardhi** [comment]
@srujzs Thanks for the response. I checked the scenario with `toJS` but didn't seem to work. I published this [repo](https://github.com/andibardhi/dart_js) with minimal code to test it out. You can use the attached file (upload_file.xlsx) for upload testing. You need to go through the whole cycle of the upload in order to see the error.
[upload_file.xlsx](https://github.com/user-attachments/files/15882802/upload_file.xlsx)

**Comment by andibardhi** [comment]
@srujzs Thanks for the response. I checked the scenario with `toJS` but didn't seem to work. I published this [repo](https://github.com/andibardhi/dart_js) with minimal code to test it out. You can use the attached file (upload_file.xlsx) for upload testing. You need to go through the whole cycle of the upload in order to see the error.
[upload_file.xlsx](https://github.com/user-attachments/files/15882802/upload_file.xlsx)

**Comment by srujzs** [comment]
Thanks for the repro! It does look related to converting `Future`s back and forth. I mentioned how a Dart `async` function returns a `Future` that needs to be converted to a `Promise`, but a JS `async` function also returns a `Promise` that needs to be converted to a `Future` so you can use it in Dart. Here's how I'd patch your repro with `dart:js_interop`:

<details>
  <summary>Patch</summary>

```
diff --git a/lib/js_helper.dart b/lib/js_helper.dart
index a4e6555..6b69429 100644
--- a/lib/js_helper.dart
+++ b/lib/js_helper.dart
@@ -1,11 +1,7 @@
 @JS()
 library nuvo;

-import 'package:js/js.dart';
+import 'dart:js_interop';

 @JS()
-external dynamic testJS(
-  Function(
-    String text,
-  ) onResults,
-);
+external JSPromise<JSAny?> testJS(JSExportedDartFunction onResults);
diff --git a/lib/main.dart b/lib/main.dart
index 82ba815..c52f1d0 100644
--- a/lib/main.dart
+++ b/lib/main.dart
@@ -1,11 +1,17 @@
+import 'dart:js_interop';
+
 import 'package:flutter/material.dart';
-import 'package:js/js.dart';
 import 'package:js_testing/js_helper.dart';

 void main() {
   runApp(const MainApp());
 }

+JSPromise<JSString> func(String text) =>
+    Future<JSString>.delayed(const Duration(seconds: 1), () {
+      return text.toJS;
+    }).toJS;
+
 class MainApp extends StatelessWidget {
   const MainApp({super.key});

@@ -16,14 +22,7 @@ class MainApp extends StatelessWidget {
         body: Center(
           child: TextButton(
             onPressed: () {
-              testJS(
-                allowInterop(
-                  (text) async {
-                    Future.delayed(const Duration(seconds: 1));
-                    return text;
-                  },
-                ),
-              );
+              testJS(func.toJS).toDart;
             },
             child: const Text('Test'),
           ),
```
</details>

With the above changes, `test` is printed to the console.

**Comment by andibardhi** [comment]
Thank you, @srujzs! This is incredibly helpful.
