### ISSUE TITLE
Network paths don't work after 3.4.0

### ISSUE THREAD

**Issue by BananaMasterz** [dart-lang/sdk#56049]
Running the following code in dart 3.4.0 on **WINDOWS** raises `PathNotFoundException`

```dart
import 'dart:io';

void main() async {
  print(await File(r'\\my_srv\some_path\test.txt').exists());
  File(r'\\my_srv\some_path\test.txt').copy(r'C:\path\test.txt');
}
```

but works fine in earlier versions (like 3.3.4 and 3.0.0).

I see there have been some changes like this [one](https://github.com/dart-lang/sdk/commit/c2e9ceeb6b97329f75a84bd41e40b540dd40e7a4) (maybe some more) that could be the cause.

I also see that there are not tests set up for network paths so this isn't caught.

Finally I'm not sure why `File().exists())` returns `true` but `.copy()` can't see the file... shouldn't both methods resolve the paths in the same manner?

This is my OS:
```
Edition	Windows 11 Pro
Version	23H2
Installed on	‎27/‎3/‎2024
OS build	22631.3737
```

**Comment by devoncarew** [comment]
cc @mraleph @brianquinlan

**Comment by mraleph** [comment]
Yeah it was c2e9ceeb6b97329f75a84bd41e40b540dd40e7a4 that broke this.

Well, our handling of long UNC paths apparently was always broken and the change in question simply forced `copy` to use it - which  revealed its bugyness. 

I am going to fix this. I also realized that `File::Copy` forces wrong path into "long" format. It is supposed to force destination into long form - but instead forces source, which makes no sense. 

Need to fix that as well and write a test.

**Comment by mraleph** [comment]
I think this should fix it: https://dart-review.googlesource.com/c/sdk/+/372400 - will finish it up tomorrow.
