### ISSUE TITLE
Cannot resolve top-level methods with docimports

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#56088]
I am trying to get this `[runApp]` reference to resolve with docimports:

https://github.com/flutter/flutter/blob/1d1367678a56ce5d3e02175456ee29f50363da83/packages/flutter/lib/src/foundation/binding.dart#L431

I added the following doc import for the widget library (which exports runApp from https://github.com/flutter/flutter/blob/1d1367678a56ce5d3e02175456ee29f50363da83/packages/flutter/lib/src/widgets/binding.dart#L1397):

```dart
/// @docImport 'package:flutter/widgets.dart';
library;
```

It doesn't work, though. The `comment_references` lint continues to complain about the `[runApp]` reference and clicking through in the IDE on `[runApp]` also results in a "Cannot find declaration to go to" error.

**Comment by goderbauer** [comment]
cc @srawlins

**Comment by goderbauer** [comment]
FWIW, `[runApp]` resolves properly if I add a regular import:

```dart
import 'package:flutter/widgets.dart';
```

**Comment by srawlins** [comment]
Actually I think this was the same issue as https://github.com/dart-lang/sdk/issues/56100, since `debugZoneErrorsAreFatal` is a field. I'm closing as duplicate, but after that fix rolls into flutter, if you still hit this error, please re-open.
