### ISSUE TITLE
docImports failing to allow for resolution in some flutter animation library code

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#56100]
From https://github.com/flutter/flutter/pull/150798:

I (@goderbauer) turned on the `comment_references` lint and looked at what needed fixing inside of the `animation` library.

There are a couple of places where for some reason adding a docImport didn't fix the `comment_references` warning:

- [x] All the references in the doc on the `library` statement of the animations library (no doc import helps), example: https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/animation.dart#L12
- [ ] The docImport of `package:flutter/material.dart` is for some reason unable to resolve `[Easing.legacy]`: https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/src/animation/curves.dart#L1831
- [ ] The docImport of `package:flutter/widgets.dart` is for some reason unable to resolve `[State]` and `[AnimationController]` in https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/src/animation/animations.dart#L50 https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/src/animation/animations.dart#L410

**Comment by srawlins** [comment]
With https://dart-review.googlesource.com/c/sdk/+/373620, hopefully the first issue is fixed.

**Comment by srawlins** [comment]
@goderbauer. Weird question. You say that a `@docImport` doesn't help `[AnimationController]` at _one_ location in https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/src/animation/animations.dart.

But I notice there are, I think, 5 such references like `[AnimationController]`. So my questions: are all 5 unresolved (not ctrl-clickable) without the doc-import? And do all-but-one become resolvable _with_ the doc-import?

**Comment by goderbauer** [comment]
All five are unresolvable _without_ the docimport. When adding the docimport, three of them resolve and two remain unresolved. 

With the doclink, these two don't resolve:

* https://github.com/flutter/flutter/blob/47e65e806f753c2b597958f91085cc330e384793/packages/flutter/lib/src/animation/animations.dart#L52
* https://github.com/flutter/flutter/blob/47e65e806f753c2b597958f91085cc330e384793/packages/flutter/lib/src/animation/animations.dart#L84


While these three resolve without trouble:
* https://github.com/flutter/flutter/blob/47e65e806f753c2b597958f91085cc330e384793/packages/flutter/lib/src/animation/animations.dart#L342
* https://github.com/flutter/flutter/blob/47e65e806f753c2b597958f91085cc330e384793/packages/flutter/lib/src/animation/animations.dart#L373
* https://github.com/flutter/flutter/blob/47e65e806f753c2b597958f91085cc330e384793/packages/flutter/lib/src/animation/animations.dart#L374

**Comment by srawlins** [comment]
Perfect; the issue is when a field or top-level variable has the doc comment. I have mailed a fix.
