### ISSUE TITLE
[CP] Pub: Fix to using path dependencies in git dependencies on windows

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#56116]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/373861 (rolling https://github.com/dart-lang/pub/pull/4315)

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/373861

### Issue Description

On windows the path would be written with a `\` instead of `/` the pubspec lock, making it incompatible with the mac/linux pubspec.lock

### What is the fix

Always use '/' in pubspec.lock for path-dependencies in git-dependencies.

### Why cherry-pick

Windows users using the path-dependencies from git-dependencies feature are impacted, and will get an inconsistent pubspec.lock.

### Risk

Low

### Issue link(s)

https://github.com/dart-lang/pub/issues/4314

### Extra Info

We could consider also picking this to stable, but given that this was only discovered late, it might not be a broadly used feature, and we can get away with a beta CP.

**Comment by jonasfj** [comment]
Support for relative path-dependencies from git-dependencies was introduced in Dart 3.4, this bug has existed since.

I don't think the feature has been widely promoted.

But it would be nice to get the fix into 3.5.

**Comment by itsjustkevin** [comment]
@sigurdm and @jonasfj will mark this as approved, please have the associated CL reviewed.
