### ISSUE TITLE
string.allMatches returns an Iterable of length pattern.length + 1 when aString is empty

### ISSUE THREAD

**Issue by SirioRigel** [dart-lang/sdk#56115]
So I was messing around with strings and I found this interesting behaviour: if you try to get all matches of a specific pattern from an empty string, allMatches returns a Iterable of length pattern.length + 1 if there are no matches and the String is empty.

I tried the following code in dartpad.dev (https://dartpad.dev/):

``` Dart
void main() {
  String s = "";
  Iterable<Match> matches = s.allMatches("X");
  int length= matches.length; 
  
  // should print 0 but prints 2
  print(length); 
  
  // Shouldn't even executes but prints 0 and 1.
  for(Match v in matches) {
    print(v.start);
  }
}
```
And the result is that the "length" variable will be 2, while the for loop, which shouldn't execute since the String is empty and thus there shouldn't be any matches for any specific pattern, prints out two elements whose starting indexes are 0 and 1.  If you try with a String like "ABCD", the length variable will have a value of 5 (pattern.length + 1).

Maybe I'm getting something wrong here, but if the String is empty, the "matches" iterable shouldn't be an empty Iterable?

**Comment by jakemac53** [comment]
This is actually matching the current pattern (empty string), against the value you passed in ("X").

Matching the empty string against anything is a bit weird, but it doesn't seem reasonable for it to return this result, there is an "empty string" at every position, sort of.

But, @lrhn should probably confirm this is the intended behavior.

**Comment by SirioRigel** [comment]
I know that it doesn't make any sense to check allMatches of some pattern on an empty String, but I just found it very interesting that it had this kind of behaviour.

**Comment by jakemac53** [comment]
> I know that it doesn't make any sense to check allMatches of some pattern on an empty String, but I just found it very interesting that it had this kind of behaviour.

You are matching the empty string, against the string "M" - not the other way around.

**Comment by SirioRigel** [comment]
Got it, thanks!

> Is working as intended.
> 
> Dart has the great feature that `RegExp` is not the only kind of pattern. Instead of having to do something like `RegExp(RegExp.escape(string))` to create a regexp that matches a literal string, the `String` itself implements `Pattern` and can be used as one.
> 
> That does have the failure mode of being able to accidentally swap the pattern and the source. It's `pattern.allMatches(source)`, not the other way around, even if it's a method on `String`. (As a rule: If something returns a `Match`, the method is probably from the `Pattern` interface, and treats the string it's on as the pattern. If it returns `String`, it's probably from `String` itself, and may take a patterns as argument, like `String.replaceAll`).
