### ISSUE TITLE
pkg/dds/test/devtools_server/instance_reuse_test timing out

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56111]
There are new test failures on [Update DevTools rev to 70375f6c6d81faa8f3069aa6dcf2a98c69445455](https://github.com/dart-lang/sdk/commit/b792a0c914a4bf59d4519fb4e5247b8ca6f9aca7).

The tests
```
pkg/dds/test/devtools_server/instance_reuse_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux-x64
unittest-asserts-release-mac-arm64
unittest-asserts-release-mac-x64
```

The tests started timing out on multiple configurations.

[logs Linux](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8743854105206571329/+/u/test_results/new_test_failures__logs_)

[logs MacOS](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8743853786780385921/+/u/test_results/new_test_failures__logs_)

cc @bkonyi

**Comment by elliette** [comment]
Thanks! I think this is a regression in DevTools, so I'm tracking the fix in https://github.com/flutter/devtools/issues/8008

@dcharkes I'm not very familiar with SDK infra, is there anything that needs to be done on the SDK side (e.g. skip the test until the DevTools patch is in)? Or do failing tests automatically get removed from the CI test suite?

**Comment by dcharkes** [comment]
> @dcharkes I'm not very familiar with SDK infra, is there anything that needs to be done on the SDK side (e.g. skip the test until the DevTools patch is in)? Or do failing tests automatically get removed from the CI test suite?

I marked the tests as approved. So they will be approved failing until they turn succeeding again. So before closing this issue  you should check that the tests started succeeding.

**Comment by elliette** [comment]
The test has been confirmed fix with https://dart-review.googlesource.com/c/sdk/+/374298

![Screenshot 2024-07-03 at 11 18 23 AM](https://github.com/dart-lang/sdk/assets/21270878/43668815-2f97-4889-a74d-846c15eefd41)


https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8743415429110567985/+/u/find_tests_that_began_passing/raw_io.output_text
