### ISSUE TITLE
`IOSink.flush()` appears to be able to end a Dart program immediately

### ISSUE THREAD

**Issue by andrewkolos** [dart-lang/sdk#56119]
1. Create a new Dart project with this entry point code:

```dart
import 'dart:async';
import 'dart:io';

void main(List<String> arguments) async {
  final StreamController<List<int>> controller = StreamController();
  final sink = IOSink(controller.sink);
  sink.write('lorem ipsum');
  await sink.flush();


  File('hello').writeAsStringSync('uh');
  print('I should be visible if the program reaches this point.');
}
```

2. Run the program (e.g. with `dart run`)

**Expected result.** Program either 1) gets stuck at `await sink.flush();` or 2) completes, resulting in the `hello` file getting created and the `print` statement appearing in the output.

**Observed result.** Program terminates, but the `hello` file isn't created, and the program output is empty.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.90.0
Flutter extension: 3.91.20240529 (not activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.90.2

Workspace type: Dart (LSP)

Dart (3.5.0-321.0.dev): /Users/andrewkolos/Documents/GitHub/flutter/bin/cache/dart-sdk
Flutter (3.23.0-14.0.pre.89): /Users/andrewkolos/Documents/GitHub/flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/andrewkolos/Documents/GitHub/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.0-321.0.dev (dev) (Mon Jul 1 13:02:44 2024 -0700) on "macos_arm64"
- on macos / Version 14.5 (Build 23F79)
- locale is en

#### Project info

- sdk constraint: '^3.5.0-321.0.dev'
- dependencies: 
- dev_dependencies: lints, test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|  22 MB | 0.0% |     03:16:34 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/5UwdyN9F4UG4Z7fh  |
|  48 MB | 0.0% |     03:16:34 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.90.0 |
| 188 MB | 0.4% |        05:38 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.90.0 |
|  18 MB | 0.0% |     03:16:34 | dart tooling-daemon --machine                                                   |
|  25 MB | 0.0% |        05:38 | dart tooling-daemon --machine                                                   |

</details>

Discovered while working on https://github.com/flutter/flutter/issues/137184.

**Comment by lrhn** [comment]
Working as currently designed. 

The future returned from `flush` never completes. 
The `await` suspends execution and returns control to the event loop. That works by adding listeners to the future, which will never be called. 

At that point, the program is done. 
There are no pending events, no scheduled timers, and no open communication ports. 
Nothing is happening, and nothing can ever happen again, so the VM decides that the program has finished executing.

**Comment by andrewkolos** [comment]
Thanks for the quick clarification! I didn't know the VM had this behavior—I assumed the program would hang if anything.

Closing.
