### ISSUE TITLE
DartDoc comment of `spawnUri` needs updates

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#56124]
For example, it mentions 'checked mode', which hasn't been a thing since before Dart 2.0, and it also mentions 'Dart2 strong mode'.

**Comment by julemand101** [comment]
When doing the update, maybe consider also doing: https://github.com/dart-lang/sdk/issues/52186

**Comment by a-siva** [comment]
//cc @aam

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/374202 should address this.
