### ISSUE TITLE
[CP] beta - devtools server can reuse disconnected DevTools instance

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#56128]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/374298

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/374460

### Issue Description

https://github.com/flutter/devtools/issues/8008

When a user launched DevTools from their IDE in a new window, disconnected from their app, and then tried to relaunch DevTools, they would see an infinite spinner on the opened window instead of a DevTools connection to their app.

### What is the fix

Fix: https://github.com/flutter/devtools/pull/8009

Makes sure that DevTools receives a connect event from the devtools_server, even after disconnection.

### Why cherry-pick

This prevents users from re-connecting to DevTools in an existing browser window. 

### Risk

Low. Only changes are in DevTools to fix the issue described above:

https://github.com/flutter/devtools/compare/v2.37.0..v2.37.1

The test that caught the regression has been confirmed fixed after https://dart-review.googlesource.com/c/sdk/+/374298, see https://github.com/dart-lang/sdk/issues/56111#issuecomment-2206939914

### Issue link(s)

https://github.com/flutter/devtools/issues/8008

**Comment by vsmenon** [comment]
@kenzieschmoll - do you also recommend cherry picking?

**Comment by kenzieschmoll** [comment]
Yes, I do. CP LGTM. This regression has not yet made its way to stable, so it is important that we prevent the bug from going out to stable users.

**Comment by itsjustkevin** [comment]
@kenzieschmoll could you review the CL?  @elliette after review by @kenzieschmoll you can go ahead and merge to beta!

**Comment by elliette** [comment]
Thanks! It's been merged
