### ISSUE TITLE
File copying on Windows buildbots is broken

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#56125]
For example https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-aot-win-debug-x64/167/overview

Failure:

```
INFO: Enabling coredump archiving into C:\b\s\w\ir\cache\builder\sdk\crashes
INFO: Core dump archiving is activated
No build targets found.
Test configuration:
    vm-aot-win-debug-x64(architecture: x64, compiler: dartkp, mode: debug, runtime: dart_precompiled, system: win)
Suites tested: co19, corelib, ffi, kernel, language, lib, samples, standalone, utils, vm
Unhandled exception:
FileSystemException: Cannot copy file to 'C:/b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_compilations/vm-aot-win-debug-x64/runtime_tests_vm_dart_split_aot_kernel_generation2_test/../../../../tests/language/mixin/regress_flutter_55345_test.dart', path = 'C:\b\s\w\ir\cache\builder\sdk\tests\language\mixin\regress_flutter_55345_test.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.copySync (dart:io/file_impl.dart:366:5)
#2      StandardTestSuite._makeCommands (package:test_runner/src/test_suite.dart:850:39)
#3      StandardTestSuite._enqueueStandardTest (package:test_runner/src/test_suite.dart:770:22)
#4      StandardTestSuite._testCasesFromTestFile (package:test_runner/src/test_suite.dart:751:7)
#5      StandardTestSuite.findTestCases (package:test_runner/src/test_suite.dart:660:7)
#6      TestCaseEnqueuer.enqueueTestSuites (package:test_runner/src/process_queue.dart:234:13)
#7      new ProcessQueue (package:test_runner/src/process_queue.dart:172:22)
#8      testConfigurations (package:test_runner/src/test_configurations.dart:283:3)
#9      main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/test_runner/bin/test_runner.dart:52:9)
<asynchronous suspension>
INFO: No unexpected crashes recorded
***************** Killing dart *****************
  No dart processes found.
***************** Killing gen_snapshot *****************
  No gen_snapshot processes found.
***************** Killing dartaotruntime *****************
  No dartaotruntime processes found.
***************** Killing dart_precompiled_runtime *****************
  No dart_precompiled_runtime processes found.
```

cc @mraleph

**Comment by aam** [comment]
The culprit is https://dart-review.git.corp.google.com/c/sdk/+/372400 which started to convert destination to long-prefixed form.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/374220 with proposed fix

**Comment by aam** [comment]
and https://dart-review.googlesource.com/c/sdk/+/374181 with the prebuilt roll

**Comment by mraleph** [comment]
Thanks for looking at this @aam. 

Note that the fix landed in [b207aed](https://github.com/dart-lang/sdk/commit/b207aed8b7f45e5ed3c515e9c8da8aca56cc4240) is incomplete I think. What this bug shows is that our `IsAbsolutePath` predicate is incorrect to begin with. So the fix did not fix the full problem e.g. consider situations where `force_long_prefix` is `false` but we have long "pseudo-absolute" path which starts with `C:\` but has `..` segments inside.

I wonder if we should just start using `PathCchCanonicalizeEx`? Our minimum supported Windows version allows us to use it.

**Comment by aam** [comment]
Good point! But my thinking was that it's only when we use `force_long_prefix` the `..` segments cause issues in "absolute paths".

**Comment by mraleph** [comment]
> But my thinking was that it's only when we use `force_long_prefix` the `..` segments cause issues in "absolute paths".

`force_long_prefix` is just a short-cut in some sense. So whatever problem exists with it, will also exist with paths that are just long by themselves.

**Comment by aam** [comment]
Shortcut in what sense?  I thought presence of long prefix disables some file/directory name processing and validation - stuff like handling of `..`

**Comment by mraleph** [comment]
@aam in the implementation sense. I added `force_long_prefix` to simplify implementation of `Copy` which would otherwise need to worry with path length.

**Comment by mraleph** [comment]
@aam Would you submit a follow up change to fix the whole issue?

**Comment by aam** [comment]
@mraleph  wrote
> Would you submit a follow up change to fix the whole issue?

Is this what you had in mind https://dart-review.googlesource.com/c/sdk/+/375421 ?
