### ISSUE TITLE
[CP] Fix crash in `DateTime.timezoneOffset`

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#56133]
### Commit(s) to merge

https://github.com/dart-lang/sdk/commit/b3ce1647a8c29f51b2cec3d156d7aa7a3ae2995b

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/374441

### Issue Description

In some combinations of dart2js compile flags, `DateTime.timezoneOffset` can crash.
This has been observed on Firefox for Ads properties.
It is one of their leading crashes.

### What is the fix

The fix is to handle fractional minutes (i.e. seconds expressed as the fractional part of a double).

### Why cherry-pick

Developers can access the combination of compiler flags that cause the problem to become an app crash.

### Risk

Low - relatively simple scaling minutes to seconds and clipping to `int` value.

### Issue link(s)

b/350561030

**Comment by itsjustkevin** [comment]
@sigmundch and @a-siva can you take a look at this cherry-pick request?

**Comment by sigmundch** [comment]
Overall, I am supportive, but I'm trying to gauge the need for a cherry-pick. In terms of risk, this is very contained and doesn't give me concern. However, the internal case that was affected is already addressed, so this would only make sense to cherry-pick if it can affect external users.

@rakudrama - is that combination of flags actually possible externally? Other than `--extra-sound-null-safety-checks`, is there another way to expose the issue in SNS programs (e.g. with `-O2`) or is the check causing the failure always (improperly) optimized away?

**Comment by rakudrama** [comment]
@sigmundch My main concern was that one of the other dart2js flags for adding checks (e.g. on native calls) would have a similar effect, or that we could cause other places along the flow of the value to have checks, for example, dart2js adds checks in static methods to make them implement a dynamic entry-point. Luckily the only place the value flows is into the `Duration` constructor, and constructor tear-offs are done via a separate synthesized static function, so the synthetic function is where the 'dynamic' entry checks end up.

On balance, after trying harder to make them happen, I now think these failure modes are unlikely and withdraw the request.
