### ISSUE TITLE
VM and analyzer disagree on whether static extension type methods can be used in constant expressions

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#56148]
Given this code:

```dart
import '' as self;
extension type ET(int it) {
  static int f(String s) => 7;
}
const g = self.ET.f;

void main() {
  print(g);
}
```

`dart analyze` claims:

> Extension type methods can't be used in constant expressions. (`CompileTimeErrorCode.CONST_EVAL_EXTENSION_TYPE_METHOD`)

But the dart VM produces:

`Closure: (String) => int from Function 'ET|f': static.`

Who is right? CC @eernstg @lrhn

**Comment by lrhn** [comment]
Analyzer is wrong.
Static extension type methods are just static methods, they're just as constant as any other static methods.
They're not _extension type methods_, which is a distinction made on methods of an extension type _type_, which are either extension type members, which are non-virtual, or not ("'object instance members" I sometimes call them, but the technical term is "non-extension type members") which are backed by instance members of the representation type. 

Neither is constant.
