### ISSUE TITLE
from my understanding in `dart:io` there is no way to get a sorted stream of `FileSystemEntity`

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#56147]
from my understanding in `dart:io` there is no way to get a sorted stream of `FileSystemEntity`
I only found this:
``` 
Stream<FileSystemEntity> Directory.list(
      {bool recursive = false, bool followLinks = true});
```

I would like to have a sorted stream, I know I can wait for all the results and sort the list but that means waiting for all the results before starting processing, is there a way to make it faster at a lower level by returning a sorted stream?

**Comment by lrhn** [comment]
There is no way to make it faster at a lower level. If you want a sorted list of entities, you need to have all the entities available before you can sort them. 

(I guess you could incrementally sort each time you received a chunk, maybe in a way that makes the final waiting time lower, but I don't think it's the sorting that's going to be the biggest overhead. But having a comparison function that ignores the common path prefix is probably more important.)

**Comment by stephane-archer** [comment]
thank you @lrhn, I will try your approach
