### ISSUE TITLE
Dart compile define flag doesn't work when compiling exe

### ISSUE THREAD

**Issue by TarasMazepa** [dart-lang/sdk#56146]
> Dart 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "windows_x64"

I'm running `dart compile exe -Dversion="1.0" .\cli\bin\cli.dart` on the [source code](https://github.com/TarasMazepa/stax).

When I try to run the resulting binary to get the version passed through the compilation flag, `String.fromEnvironment("version", defaultValue: "unknown")` results in `unknown` output.

```
> .\cli\bin\cli.exe version
unknown
```

I have also tried to pass a different version of the define flag with the same result.
```
dart compile exe --define=version="1.0" .\cli\bin\cli.dart
```

Also, I have tried the same on Windows Subsystem for Linux (WSL); the behavior is the same. Note that on WSL Linux, the dart-sdk toolchain is used.

But once I put `const` in front of `String.fromEnvironment("version", defaultValue: "unknown")` it starts working for some reason.

You can also find some people also find it confusing https://stackoverflow.com/a/76718173/563732

**Comment by julemand101** [comment]
> But once I put const in front of String.fromEnvironment("version", defaultValue: "unknown") it starts working for some reason.

If you read the documentation, this is the expected behavior: https://api.dart.dev/stable/3.4.4/dart-core/String/String.fromEnvironment.html

> This constructor is only guaranteed to work when invoked as const. It may work as a non-constant invocation on some platforms which have access to compiler options at run-time, but most ahead-of-time compiled platforms will not have this information.

**Comment by TarasMazepa** [comment]
@julemand101 thanks! Maybe moving that statement to the top of the doc would be better for future readers 😅 I have skipped that. Another thing would be to have a linter which would highlight this potential problem.

**Comment by bkonyi** [comment]
We definitely need a lint for this, or some way to throw an error when the non-const constructor is used, but as @julemand101 described this is expected behavior.
