### ISSUE TITLE
pkg:json - Support DateTime attributes

### ISSUE THREAD

**Issue by azeldaniel** [dart-lang/sdk#56175]
Attempting to use a `DateTime` attribute within any `@JsonCodable()` annotated class throws an unsupported error. DateTime is a commonly used type in dart and other languages to represent timestamps for creation data points etc.

Consider the code:

```dart
@JsonCodable()
class Person {
  final DateTime birthday;
}
```

It throws the following errors:

```
Unable to deserialize type, it must be a native JSON type or a type with a `fromJson(Map<String, Object?> json)` constructor
Unable to serialize type, it must be a native JSON type or a type with a `Map<String, Object?> toJson()` method.
```

If supporting DateTime is not within the scope of this package, can you suggest a possible hack or workaround?

**Comment by devoncarew** [comment]
@jakemac53, thoughts? Note that there's now a related CL.

**Comment by jakemac53** [comment]
Reviewing the CL, I am generally fine with adding this.

**Comment by jakemac53** [comment]
This is completed now
