### ISSUE TITLE
Cleanup `pkg/dtd_impl` file structure

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#56178]
There are several classes defined under `lib` that are used under `src`. We should restructure this code so that `src/` files only import code from other `src/` files, and so that the files under `lib` export files from `src`.

See this [comment thread](https://dart-review.googlesource.com/c/sdk/+/372940/comment/5613bbb4_37aca857/) for context.

**Comment by DanTup** [comment]
Working on this at https://dart-review.googlesource.com/c/sdk/+/374981
