### ISSUE TITLE
[Digit separators] Syntax highlighters implementation

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#56187]
* [x] https://github.com/dart-lang/dart-syntax-highlight/ (@DanTup, https://github.com/dart-lang/dart-syntax-highlight/pull/73)
* [x] https://youtrack.jetbrains.com/issue/IDEA-356065/Support-Dart-digit-separators-in-number-literals
* [ ] google3
* [x] https://github.com/highlightjs/highlight.js (https://github.com/highlightjs/highlight.js/pull/4081)
* [x] https://github.com/codemirror/CodeMirror/ CodeMirror 5 is deprecated and CodeMirror 6 has no support for Dart. But DartPad runs on CodeMirror 5, so we still need support here. https://github.com/codemirror/codemirror5/pull/7105

**Comment by srawlins** [comment]
I think we should skip CodeMirror (and can skip it for language features going forward).

AFAICT there is only existing Dart support for CodeMirror 5. For CodeMirror 6 there is a new way to specify a language mode, a new way to specify the parser, and there is no support for Dart as a language in CodeMirror 6. It would be great to add that support, but as for the Digit separators feature, I think it is not important to bump the support for CodeMirror 5, and a separate effort to wire up CodeMirror 6.

**Comment by bwilkerson** [comment]
@anderdobo @mossmana

**Comment by srawlins** [comment]
I added back CodeMirror 5 since DartPad actually still runs on CodeMirror 5.

**Comment by srawlins** [comment]
Calling this done. google3 can be tracked separately.
