### ISSUE TITLE
Quick fix doesn't create a correct recommendation when checking for exhaustiveness of a list pattern

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#56219]
- When a list pattern doesn't capture all of the potential patterns, the quick fix 

```
void main() {
  var list = ['a', 'b', 'c'];
  var result = switch (list) {
    ['a', ...] => 'Starts with a',
  };
  print(result);
}
```

Which produces this error:

```
error: The type 'List<String>' is not exhaustively matched by the switch cases since it doesn't match '[]'.
```

The Quick Fix offers the option to add an empty list pattern, like this:

```
  var result = switch (list) {
    ['a', ...] => 'Starts with a',
    // TODO: Handle this case.
    [] => throw UnimplementedError(),
  };
```

But this still produces an analysis error:

```
error: The type 'List<String>' is not exhaustively matched by the switch cases since it doesn't match '[String(), ...[...]]'.
```

One more quick fix is offered, which correctly handles all the potential patterns

```
  var result = switch (list) {
    ['a', ...] => 'Starts with a',
    // TODO: Handle this case.
    [] => throw UnimplementedError(),
    // TODO: Handle this case.
    [_, ...] => throw UnimplementedError(),
  };
```

@munificent It sounds like this is a result of the algorithm the exhaustiveness checker is using to produce a "witness" for an incomplete set of patterns. Maybe there's a way to iterate over the potential quick fixes until we produce a pattern that passes exhaustiveness?

**Comment by johnpryan** [comment]
@johnniwinther @bwilkerson It sounds like this may be fixed in a newer version of the SDK?

**Comment by bwilkerson** [comment]
The behavior as of this morning is for the fix (from the original example) to produce:
```dart
void main() {
  var list = ['a', 'b', 'c'];
  var result = switch (list) {
    ['a', ...] => 'Starts with a',
    // TODO: Handle this case.
    [] => throw UnimplementedError(),
    // TODO: Handle this case.
    [_, ...] => throw UnimplementedError(),
  };
  print(result);
}
```

So I believe that this is now working as intended.
