### ISSUE TITLE
Failures on Support digit separators

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#56215]
There are new test failures on [Support digit separators](https://github.com/dart-lang/sdk/commit/5e8ee777729a34187815465ad756079dbe6d601a).

The tests
```
coverage/package:front_end/src/source/source_compilation_unit.dart Fail (expected Pass)
```
are failing on configurations
```
cfe-unittest-asserts-release-linux
```

**Comment by a-siva** [comment]
// @srawlins

**Comment by srawlins** [comment]
Thanks, @a-siva . Is there a way to see these failures?

**Comment by srawlins** [comment]
I found a log: https://dart-ci.appspot.com/log/front-end-linux-release-x64/cfe-unittest-asserts-release-linux/26061/coverage/package:front_end/src/source/source_compilation_unit.dart
