### ISSUE TITLE
Send Pointer through SendPort without an error, which is different from the doc.

### ISSUE THREAD

**Issue by laishere** [dart-lang/sdk#56236]
Quote from https://api.dart.dev/stable/3.4.4/dart-isolate/SendPort/send.html
>If the sender and receiver isolate share the same code (e.g. isolates created via [Isolate.spawn](https://api.dart.dev/stable/3.4.4/dart-isolate/Isolate/spawn.html)), the transitive object graph of message can contain any object, with the following exceptions:
Objects with native resources (subclasses of e.g. NativeFieldWrapperClass1). A [Socket](https://api.dart.dev/stable/3.4.4/dart-io/Socket-class.html) object for example refers internally to objects that have native resources attached and can therefore not be sent.
[ReceivePort](https://api.dart.dev/stable/3.4.4/dart-isolate/ReceivePort-class.html)
[DynamicLibrary](https://api.dart.dev/stable/3.4.4/dart-ffi/DynamicLibrary-class.html)
[Finalizable](https://api.dart.dev/stable/3.4.4/dart-ffi/Finalizable-class.html)
[Finalizer](https://api.dart.dev/stable/3.4.4/dart-core/Finalizer-class.html)
[NativeFinalizer](https://api.dart.dev/stable/3.4.4/dart-ffi/NativeFinalizer-class.html)
[Pointer](https://api.dart.dev/stable/3.4.4/dart-ffi/Pointer-class.html)
[UserTag](https://api.dart.dev/stable/3.4.4/dart-developer/UserTag-class.html)
MirrorReference

It says Pointer is not supported to send through SendPort. However, I tested on my PC, it shows that no error is raised and I can actually print the pointer in the Isolate.

Is the doc out of date?

**Comment by dcharkes** [comment]
Yes, that doc is out of date as of https://dart-review.googlesource.com/c/sdk/+/350822.

Thanks for the report @laishere!

**Comment by dcharkes** [comment]
Fix underway: https://dart-review.googlesource.com/c/sdk/+/375820
