### ISSUE TITLE
[CP] [dart2wasm] Generate source maps

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#56239]
### Commit(s) to merge

We'd like the source map support for dart2wasm to be included in the next stable to be released (which current beta will be the base for I assume).

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/375660

### Issue Description

Flutter web developers get only names in stack traces but no line numbers.

### What is the fix

Cherry-pick the source map support.

### Why cherry-pick

To make stack traces more readable in local development we'd like users of dart2wasm to get source map support. Due to infrequent releases of stable, we'd like to cherry-pick this into the beta (which I assume will become the upcoming stable)

### Risk

Low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/55763

**Comment by vsmenon** [comment]
lgtm

**Comment by sigmundch** [comment]
LGTM - we discussed this at the scrum meeting today and concluded to move forward with the CP (together with the flutter CP as well)

**Comment by itsjustkevin** [comment]
@mkustermann cherry-pick approved, please merge.

**Comment by mkustermann** [comment]
> @mkustermann cherry-pick approved, please merge.

Merged.
