### ISSUE TITLE
Enum hashCode is different when hot reloading

### ISSUE THREAD

**Issue by naamapps** [dart-lang/sdk#56248]
Hello,
I have encountered an issue when hot reloading in Flutter and using a simple equality check with an enum and a variable.
It seems that the hashCode of the enum value itself is different somehow.

I didn't have success replicating it outside of my project unfortunately. 

This is the enum code:
```dart
enum PersistenceGraphFrequency { daily, weekly, monthly, yearly, decade }
```

When printing to console these lines:
```dart
print('frequency: $frequency');
print('frequency: ${frequency.hashCode}');
print('daily: ${PersistenceGraphFrequency.daily.hashCode}');
print('frequency == PersistenceGraphFrequency.daily: ${frequency == PersistenceGraphFrequency.daily}');
```

The output is:
```
I/flutter ( 1711): frequency: PersistenceGraphFrequency.daily
I/flutter ( 1711): frequency: 864014486
I/flutter ( 1711): daily: 927735851
I/flutter ( 1711): frequency == PersistenceGraphFrequency.daily: false
```

After hard reload, the output is:
```
I/flutter ( 1711): frequency: PersistenceGraphFrequency.daily
I/flutter ( 1711): frequency: 636379493
I/flutter ( 1711): daily: 636379493
I/flutter ( 1711): frequency == PersistenceGraphFrequency.daily: true
```

Dart version: 3.4.3
Env: MacOS 13.6
Device: Android 14

**Comment by rmacnak-google** [comment]
I was not able to reproduce a case where the hash changed.

**Comment by mraleph** [comment]
Likely just a duplicate of https://github.com/dart-lang/sdk/issues/55350 which @rmacnak-google fixed in 3.5 and above

**Comment by biggs0125** [comment]
Dart/Flutter Web does not support hot reload (yet). So if you trigger a hot reload it should actually be hot restarting at which point the program is essentially a new program and the hash is expected to fully change.

**Comment by HeropolisDa2ny** [comment]
Yes I've seen that in the official flutter documentation, however it has the same behavior with flutter hot restart from Android Studio. However if I restart completely the application on my web it is working fine. Probably the flutter hot restart also has some issue ?
