### ISSUE TITLE
Seemingly incorrect "FormatException" when using `stream.transform(json.decoder)`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#56264]
Hello!

Consider:

```dart
import 'dart:convert';

void main() {
  Stream.fromIterable([
    '{"type":"list_lints","lints":["my-lint-rule: This is a custom lint rule."]}',
    '{"type":"lint_done"}',
  ]).transform(json.decoder).listen((event) {
    print(event);
  });
}
```

This throws with:

```
FormatException: Unexpected character (at character 1)
{"type":"lint_done"}
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:866:48)
#2      _JsonStringDecoderSink.addSlice (dart:convert-patch/convert_patch.dart:1551:13)
#3      _JsonStringDecoderSink.add (dart:convert-patch/convert_patch.dart:1556:5)
#4      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#5      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#9      _MultiStreamController.addSync (dart:async/stream_impl.dart:1127:36)
#10     new Stream.fromIterable.<anonymous closure>.next (dart:async/stream.dart:375:26)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

This seems unexpected. As changing `.transform(json.decoder)` to `.map(jsonDecode)` removes the exception.

Dart:
Dart SDK version: 3.5.0-323.0.dev (dev) (Tue Jul 2 06:25:57 2024 -0700) on "macos_arm64"

**Comment by rrousselGit** [comment]
`json.decoder`'s doc mentions:

> It may be stateful and should not be reused.

I assume that's the gist of the issue?
But then, why does `json.decoder` implement `StreamTransformer` if we shouldn't use it for `stream.transform`?

I'm probably missing something :)

**Comment by lrhn** [comment]
The JSON decode can only decode *one* JSON value, because the concatenation of two JSON values is not valid JSON. (It might be valid something else, like "JSON-lines", but that's not what is decoded.)

You can use a streaming JSON decoder to decode a single large JSON input that arrives in multiple packages, without having to accumulate and concatenate all the strings before decoding.
If your input is a `Stream<Uint8List>`, like a network connection, then something like `var result = await input.transform(utf8.decoder).transform(json.decoder).first;` should work.
