### ISSUE TITLE
[CP] [ dart:io ] Fix minor bugs in network profiler | https://dart-review.googlesource.com/c/sdk/+/375800

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#56273]
### Commit(s) to merge

791163eef8dd8d2deaaaf5e9c3ecb96308d8a7b3

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/376125

### Issue Description

- Socket data in the DevTools network profiler displays addresses as `InternetAddress(<address>, <address type>)`
- If `HttpClientResponse.listen` isn't invoked, HTTP requests never show up as completed in the network profiler

### What is the fix

- Call `.address` on `InternetAddress` instead of `.toString()`
- Move HTTP response completion logic to complete when the `HttpClientResponse` is drained, not only 

### Why cherry-pick

The network page is difficult to use and confusing for Socket traffic without this change. We have several users blocked by this broken experience. The issue had 10 upvotes, several other duplicate issues filed, and chatter on Discord.

### Risk

Low

### Issue link(s)

flutter/devtools#8050, flutter/devtools#3033, flutter/devtools#6642

**Comment by bkonyi** [comment]
cc @kenzieschmoll

**Comment by a-siva** [comment]
lgtm

**Comment by bkonyi** [comment]
@itsjustkevin is this safe to merge?

**Comment by itsjustkevin** [comment]
Yes @bkonyi please merge.
