### ISSUE TITLE
[CP] [ CLI ] Fix issue where 'dart build' would fail to find the 'dart' when run from PATH

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#56303]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/376860

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/377140

### Issue Description

`dart build` was exiting with an error stating that the `dart` executable could not be found

### What is the fix

Use the resolved SDK path determined by DartDev for locating snapshots to locate the path of the `dart` executable rather than relying solely on `Platform.executable`.

### Why cherry-pick

`dart build` is completely unusable when `dart` is on the path without this fix.

### Risk

Low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/56080

**Comment by bkonyi** [comment]
cc @a-siva @dcharkes

**Comment by a-siva** [comment]
lgtm

**Comment by a-siva** [comment]
lgtm

**Comment by itsjustkevin** [comment]
@bkonyi I see this cherry-pick was reverted, should we close this issue?

**Comment by bkonyi** [comment]
I think so, especially if we're no longer accepting cherry picks until the release. We had a failing test on Windows that I was unable to debug remotely, so we felt it was safer to revert the CL until we could investigate properly.

**Comment by dcharkes** [comment]
If no one is using `dart build` yet, that's fine with me. It means that we won't be testing the last stable `dart build`:

* https://github.com/dart-lang/native/issues/1232

We'd be pinning our CI there to Dart 3.4 stable for the time being.
