### ISSUE TITLE
[CP] [ DDS ] Fix DevTools URI not including a trailing '/' before query parameters

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#56302]
### Commit(s) to merge

dart-review.googlesource.com/c/sdk/+/376762

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/377121

### Issue Description

When opening the DevTools URI printed by the standalone VM:

```The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/devtools?uri=ws://127.0.0.1:8181/ws```

The browser navigates to a blank white page rather than the DevTools landing page.

### What is the fix

The DevTools URI was missing a `/` after `/devtools` in the path that was being printed.

### Why cherry-pick

The DevTools URI in the message printed by the VM doesn't work, preventing users from accessing DevTools from the CLI.

### Risk

Low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/56294

**Comment by bkonyi** [comment]
cc @a-siva

**Comment by vsmenon** [comment]
lgtm

**Comment by bkonyi** [comment]
The cherry pick CL has been merged.
