### ISSUE TITLE
Expression evaluation returns `true` (instead of an error) for `"a is X"` when `X` is an unresolved identifier (in Flutter?)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#56300]
I'm not sure if this is a Dart or Flutter issue - I seem to only be able to reproduce in Flutter, but I assume expression evaluation is done here (@bkonyi you might be more familiar with this - if you think I should move to flutter/flutter, let me know!)

@FMorschel reported to me conditional breakpoints not working as expected, and we tracked it back to expression evaluation returning `true` for conditions that we didn't expect. We managed to reproduce it with just simple expression eval:

![image](https://github.com/user-attachments/assets/f1c5e5d0-ec68-4119-938d-00cf188eb64f)

The error messages shown here only show up because I'm running in `-verbose` mode, otherwise you'd only see the `true` responses. When doing `x is A` where `A` is some class that's apparently not in scope, the result is just `true`. For non-Flutter dart, you get a reasonable error:

![image](https://github.com/user-attachments/assets/5b8722c6-5d1d-4973-a01e-2d28c64d4a6d)

The VM traffic is below. The `flutter run` `stdout` output shows the error in verbose mode, but the VM Service response to `evaluateInFrame` returns a valid boolean of `true` with no indication that the request failed.

```js
==> [VM] {
	"jsonrpc": "2.0",
	"id": "741",
	"method": "evaluateInFrame",
	"params": {
		"isolateId": "isolates/3676968675006663",
		"frameIndex": 0,
		"expression": "a is FutureOr<int>",
		"disableBreakpoints": true
	}
}
<== [Flutter] [+44567 ms] org-dartlang-debug:synthetic_debug_expression:1:6: Error: 'FutureOr' isn't a type.
<== [Flutter] [        ] a is FutureOr<int>
<== [Flutter] [        ]      ^^^^^^^^
<== [VM] {
	"jsonrpc": "2.0",
	"result": {
		"type": "@Instance",
		"_vmType": "Bool",
		"class": {
			"type": "@Class",
			"fixedId": true,
			"id": "classes/62",
			"name": "bool",
			"location": {
				"type": "SourceLocation",
				"script": {
					"type": "@Script",
					"fixedId": true,
					"id": "libraries/@0150898/scripts/dart%3Acore%2Fbool.dart/0",
					"uri": "dart:core/bool.dart",
					"_kind": "kernel"
				},
				"tokenPos": 508,
				"endTokenPos": 9302,
				"line": 15,
				"column": 1
			},
			"library": {
				"type": "@Library",
				"fixedId": true,
				"id": "libraries/@0150898",
				"name": "dart.core",
				"uri": "dart:core"
			}
		},
		"identityHashCode": 0,
		"kind": "Bool",
		"fixedId": true,
		"id": "objects/bool-true",
		"valueAsString": "true"
	},
	"id": "741"
}
```

**Comment by a-siva** [comment]
This appears to be a Flutter issue, possibly the Flutter tools code that interacts with the frontend is not checking for the return code correctly.

**Comment by a-siva** [comment]
//cc @andrewkolos

**Comment by jensjoha** [comment]
I'm unassigning myself as it is concluded above that this is not a CFE/expression compilation issue.

**Comment by bkonyi** [comment]
@DanTup sorry for the delay, this should probably be moved to the Flutter repo since it's probably an implementation issue with Flutter's expression evaluation.

**Comment by DanTup** [comment]
np - I've moved this to https://github.com/flutter/flutter/issues/157922
