### ISSUE TITLE
An `internal` implementation of an instance, as a `Map`?

### ISSUE THREAD

**Issue by bwc-x** [dart-lang/sdk#56329]
As thorough as the [`reflectable`](https://pub.dev/packages/reflectable) package alongside most of the current [code](https://pub.dev/packages/json_serializable) [generation](https://drift.simonbinder.eu/api/drift/driftdatabase-class) utilities are, they add quite a bit of overhead - both in terms of cognitive load and compile time wise. Listing a given instance's fields, in particular - is an incredibly common sore point. Whether it's to serialize/deserialize JSON, create type-safe database wrappers, the list goes on. Which does make one wonder.

How difficult/problematic would it be to implement an extensible class, which would allow to merely iterate through its own getters?

```dart
class Example extends ObjectMap {
  final String text = "...";
  final int number = 0;
  final bool isTrue = false;
  static final test = Example();
}

void main() {
  final values: Map<Symbol, Object?> = ObjectMap.valuesOf(Example.test);
  // { #text: "...", #number: 0, #isTrue: false }
  final types: Map<Symbol, Type> = ObjectMap.typesOf<Example>();
  // { #text: String, #number: int, #isTrue: bool }
  final field: String = Example[#text]; 
  // assert(field == "...");
  final none: Null = Example[#notDeclared]; 
  // assert(none == null);
}
``` 

Provided a straightforward named constructor, the destructured class can later on be reassembled via a custom parsing and a [`Function.apply`](https://api.dart.dev/stable/3.4.4/dart-core/Function/apply.html) call, depending on the exact use case. No `build_runner`-s, taking anywhere in between several to 60-180 seconds on each run. No code generation. No manual specification of [`introspection`](https://github.com/google/reflectable.dart/blob/master/reflectable/doc/TheDesignOfReflectableCapabilities.md#specifying-mirror-api-based-capabilities) capability within a separate declaration of a `Reflectable`, to annotate every class in question. Would it be that problematic to piece together, via an `external` call to a lower-level implementation?

**Comment by lrhn** [comment]
I think this is something that can safely and efficiently be handled by macros.

Adding it as a language feature doesn't seem necessary, and it doesn't seem worth the effort. There is always the risk that whatever is built into the language fails to meet the needs of some of the use cases. A macro, or different macros, can provide precisely the behavior that is needed

**Comment by bwc-x** [comment]
Very much looking forward to them being stabilized. Build runner and its config aren't exactly ideal for most common use cases.
