### ISSUE TITLE
Code completion contains many duplicated items for extensions

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#56320]
Working on current analyzer code (b72781bb82e) using Dart SDK version: 3.6.0-edge.0b965a1ac8370935ccefa7ca11076b79a2a73037 (main) (Mon Jul 22 08:59:36 2024 +0000) on "windows_x64", I see a lot of odd duplicated things in code completion like this:

![image](https://github.com/user-attachments/assets/c10dfdf5-d970-4419-9747-16ee795dca2c)

![image](https://github.com/user-attachments/assets/deff0322-4ad6-4091-8a91-1bb8a2e30388)

Selecting one of these items adds an import as was shown, but that doesn't make this extension(?) accessible, so produces an error:

![image](https://github.com/user-attachments/assets/ca1de073-84b3-4fca-8bfd-da2480ec53bb)

**Comment by DanTup** [comment]
@bwilkerson this keeps catching me out so I had a look at fixing it. It appears that whenever we build the set of completions for not-imported-libraries, we include the extensions that are _available to_ each not-imported library, instead of only the ones it declares or exports.

So if `a.dart` imports `extensions.dart`, then every extension from `extensions.dart` _also_ shows up as available for `a.dart` (even though it does not declare or export them).

I believe the issue is somewhere around [`addNotImportedExtensionMethods`](https://github.com/dart-lang/sdk/blob/1f6151d11d626648ecf4f4fb83c8cdd3cd3601ab/pkg/analysis_server/lib/src/services/completion/dart/declaration_helper.dart#L460) here, but it's not clear to me where about these should be filtered out. Initially, we look in [`library.accessibleExtensions`](https://github.com/dart-lang/sdk/blob/1f6151d11d626648ecf4f4fb83c8cdd3cd3601ab/pkg/analyzer/lib/dart/element/element.dart#L2064) which is documented as "The extension elements accessible within this library" (_not_ which extension elements _exported/declared by this library), so the incorrect (imported) extensions are showing up here.

We then filter using `applicableTo`, but I think this is only looking at the types and not visibility.

We finally filter with `isVisibleIn` but that only filters based on whether it's private or not (either it's not private _or_ it's in the same library).

My feeling is that the first step is wrong, and we should never have started with extension elements from `extensions.dart` when we're adding unimported items for `a.dart` (I think maybe `library.accessibleExtensions` is intended for local use within the file and we need something slightly different - though I don't know such a thing already exists).

**Comment by bwilkerson** [comment]
> My feeling is that the first step is wrong ...

I agree. Using `accessibleExtensions` is clearly the wrong thing to do here.

I also don't know whether there's an accessor for 'extensions declared in or exported from this library'. @scheglov ?

**Comment by scheglov** [comment]
Yeah, I think this is a relatively recent regression, probably cause by switching from not-yet-imports libraries contributor. I was sad that it did not work myself, but did not get my hands to it so far. Good that someone else does :-)

I believe the answer is somewhere in
https://dart-review.googlesource.com/c/sdk/+/366021
https://dart-review.googlesource.com/c/sdk/+/366968

And yes, `LibraryElement.accessibleExtensions` is extensions that you can use in this library. No, what you can use if you import this library. It seems that in the CLs above we suggest only extensions that are declared in the library. But we could just as well suggest extensions from `exportNamespace`. Nobody asked it though in the past.

**Comment by bwilkerson** [comment]
Using the `exportNamespace` to find the extensions sounds promising.

**Comment by DanTup** [comment]
@giapsoft unfortuantely the fix has not made it to a stable release yet. It's fixed on master/beta and will be included in the next stable release.

**Comment by burakJs** [comment]
I am still facing this problem @DanTup 
> flutter --version                                                 
Flutter 3.24.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision dec2ee5c1f (12 days ago) • 2024-11-13 11:13:06 -0800
Engine • revision a18df97ca5
Tools • Dart 3.5.4 • DevTools 2.37.3

**Comment by DanTup** [comment]
@burakJs the 3.24.5 release this month was just a hotfix release (which only includes critical fixes). Since this fix is not critical it'll show show up in the next non-hotfix release (which I think will be 3.27 since that's the current beta).

**Comment by burakJs** [comment]
> @burakJs the 3.24.5 release this month was just a hotfix release (which only includes critical fixes). Since this fix is not critical it'll show show up in the next non-hotfix release (which I think will be 3.27 since that's the current beta).

I will be eagerly waiting for the new version. Thank you for your response.
