### ISSUE TITLE
ffi/native_assets/asset_relative_test flaky Timeout

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#56330]
The tests are `flaky -> Timeout`
```
ffi/native_assets/asset_relative_test Timeout (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-arm64
```

e.g. [this log](https://dart-ci.appspot.com/log/vm-aot-linux-release-arm64/vm-aot-linux-release-arm64/447/ffi/native_assets/asset_relative_test)

**Comment by mkustermann** [comment]
Could you take a look @dcharkes ?

**Comment by dcharkes** [comment]
It's the slowest out of the tests in that directory. 57 seconds on an M1.

I believe those arm64 linux machines are a fair bit slower. We can try marking it slow or splitting up the test.
