### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by manimal001** [dart-lang/sdk#56349]
E/flutter ( 8322): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Connection timed out
E/flutter ( 8322): #0      IOClient.send (package:http/src/io_client.dart:94:7)
E/flutter ( 8322): <asynchronous suspension>
E/flutter ( 8322): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
E/flutter ( 8322): <asynchronous suspension>
E/flutter ( 8322): #2      RemotePopularCategoryService.get (package:my_grocery/service/remote_service/remote_popular_category_service.dart:9:20)
E/flutter ( 8322): <asynchronous suspension>
E/flutter ( 8322): #3      HomeController.getPopularCategories (package:my_grocery/controller/home_controller.dart:40:20)
E/flutter ( 8322): <asynchronous suspension>
E/flutter ( 8322): 
E/flutter ( 8322): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Connection timed out
E/flutter ( 8322): #0      IOClient.send (package:http/src/io_client.dart:94:7)
E/flutter ( 8322): <asynchronous suspension>
E/flutter ( 8322): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
E/flutter ( 8322): <asynchronous suspension>
E/flutter ( 8322): #2      RemoteBannerService.get (package:my_grocery/service/remote_service/remote_banner_service.dart:9:20)
E/flutter ( 8322): <asynchronous suspension>
E/flutter ( 8322): #3      HomeController.getAdBanners (package:my_grocery/controller/home_controller.dart:28:20)
E/flutter ( 8322): <asynchronous suspension>
E/flutter ( 8322):

**Comment by a-siva** [comment]
@manimal001 it appears that the server you are trying to connect to from the application is not responding to your request. You need to first figure if the server is up and functional, you could do that by pinging the server or trying the same http request from a browser to see if that is functional.

From the exception trace you have provided it does not appear to be a problem with Flutter or Dart.
