### ISSUE TITLE
DevTools server failing to start on beta

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#56347]
Running Dart-Code's integration tests on GitHub actions I'm seeing some failures to start the DevTools server like this:

```
[DevTools] [Error] Invalid argument(s): A directory corresponding to fileSystemPath "/home/runner/work/Dart-Code/Dart-Code/./devtools" could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:dds/src/devtools/handler.dart:62:38)
#2      DevToolsServer.serveDevTools (package:dds/devtools_server.dart:298:23)
<asynchronous suspension>
#3      DevToolsServer.serveDevToolsWithArgs (package:dds/devtools_server.dart:458:12)
<asynchronous suspension>
#4      DevToolsCommand.run (package:dartdev/src/commands/devtools.dart:58:20)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:236:18)
<asynchronous suspension>
#7      runDartdev (package:dartdev/dartdev.dart:47:16)
<asynchronous suspension>
#8      main (file:///b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:13:5)
<asynchronous suspension>
```

I've scanned through the code but can't figure out why this would happen... I feel like `devToolsBinaries` here:

https://github.com/dart-lang/sdk/blob/beta/pkg/dartdev/lib/src/commands/devtools.dart#L54

Might be somehow `./devtools` and not an absolute path? I will try to do some debugging to see if I can get more info or reproduce locally and post an update here.

(@bkonyi @kenzieschmoll FYI)

**Comment by DanTup** [comment]
Haven't been able to repro this on Windows or macOS locally yet. It seems it might only be occurring for the Bazel tests, which start DevTools [through a custom shell script](https://github.com/Dart-Code/Dart-Code/blob/master/src/test/test_projects/bazel_workspace/scripts/custom_devtools.sh). I'm not sure why that should matter (or why the behaviour differs in beta vs stable), but I'll see if I can make a minimal repro on GH actions that might make things clearer.

**Comment by bkonyi** [comment]
I recently made a change that makes it so `sdk.dart` can possibly return the unresolved path to the VM. This means, if `dart` is invoked from path, `path.dirname(sdk.dart)` can return `'.'`. The `devtools` command shouldn't be trying to build the path to the assets itself, but using the `sdk.devToolsBinaries` getter.

**Comment by DanTup** [comment]
> This means, if `dart` is invoked from path

It is in this case. For the test above it's going through a shell script that runs `dart devtools`.

I see it doesn't use `devToolsBinaries` if `sdk.dart` doesn't end with `bin` as the last folder segment:

```
final sdkDir = path.dirname(sdk.dart);
final fullSdk = sdkDir.endsWith('bin');
final devToolsBinaries =
    fullSdk ? sdk.devToolsBinaries : path.absolute(sdkDir, 'devtools');
```

However I can't see why `sdk.dart` wouldn't be the complete path. Right now I can only repro this in my integration tests on GitHub actions (on Linux - not sure about others).. I'll continue to see if I can strip the repro down to something simpler that might help understand what's happening.

**Comment by DanTup** [comment]
@bkonyi is it possible this is happening here:

https://github.com/dart-lang/sdk/blob/3b7c06f04c4a8efc289b86401a5308728f6b9415/pkg/dartdev/lib/src/sdk.dart#L40

There is a `Platform.resolvedExecutable` that says it's absolute, but `platform.executable` says it can be relative.

**Comment by bkonyi** [comment]
Yes, that's exactly it. However, the version you're pointing to works :-)

I landed that fix on main and submitted [this cherry-pick to beta](https://dart-review.googlesource.com/c/sdk/+/377140) last week. However, it was causing a test failure on Windows and had to be reverted on the beta branch and we missed the cherry-pick window. I plan on cherry-picking this into beta/stable once the window opens again.

**Comment by bkonyi** [comment]
Yes, this is a known issue (see https://github.com/dart-lang/sdk/issues/56080). I'll close this issue and use the other issue to track the CP.
