### ISSUE TITLE
Bug Causing Dart.exe to Eat Up All Available Memory. 

### ISSUE THREAD

**Issue by aalharbi169638** [dart-lang/sdk#56355]
There's a reproducible bug that causes dart.exe to take up all available RAM in my device; I was able to reproduce this bug multiple times. I couldn't find any good solution online though.

the only packaged I used for this project is the http package published by dart.dev.

The issue occurs exactly when i type "http.Response response = http.g" inside the Future method to use the get method for that package.

Thank you,  

![code causing issue](https://github.com/user-attachments/assets/fbac5144-3f71-4dab-9a98-ab49d22a8f1b)
![RAM taken](https://github.com/user-attachments/assets/d3a9bd6d-56f5-407a-a94a-665ca41ec586)
![notification error](https://github.com/user-attachments/assets/aa0b7a23-2131-4bb1-bda9-34ab0e094831)

**Comment by aam** [comment]
It reproduces  locally on gWindows with following log:

```
## Dart analysis issue

Out of Memory

## Version information

- Dart SDK 3.5.0-176.0.dev
- Dart IntelliJ 212.5744
- Android Studio Chipmunk | 2021.2.1 Patch 2
- Windows 10 10.0

## Details

Out of Memory

```
#0      List._growToNextCapacity (dart:core-patch/growable_array.dart:397:5)
#1      AstNodeExtension.allTokens (package:analyzer/src/utilities/extensions/ast.dart:14:14)
#2      AstNodeExtension.commentTokenCovering (package:analyzer/src/utilities/extensions/ast.dart:29:23)
#3      PostfixCompletionProcessor.isApplicable (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:441:16)
#4      EditIsPostfixCompletionApplicableHandler.handle (package:analysis_server/src/handler/legacy/edit_is_postfix_completion_applicable.dart:37:31)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:890:13)
#9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:736:7)
#10     _rootRun (dart:async/zone.dart:1399:13)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

## Debug log

```
1722457584164 => {"id":"303","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457584440 => {"id":"304","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457584440 => {"id":"305","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457584683 => {"id":"306","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457584683 => {"id":"307","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457584941 => {"id":"308","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457584941 => {"id":"309","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457585212 => {"id":"310","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457585212 => {"id":"311","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457585486 => {"id":"312","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457585486 => {"id":"313","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457585749 => {"id":"314","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457585749 => {"id":"315","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457586021 => {"id":"316","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457586021 => {"id":"317","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457591030 => {"id":"318","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457596366 => {"id":"319","method":"edit.getAssists","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"length":0},"clientRequestTime":1722457596366}
1722457601100 => {"id":"320","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457601100 => {"id":"321","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457601364 => {"id":"322","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457601364 => {"id":"323","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457601621 => {"id":"324","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457601621 => {"id":"325","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457601830 => {"id":"326","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457601830 => {"id":"327","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457602139 => {"id":"328","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457602139 => {"id":"329","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457602733 => {"id":"330","method":"analysis.updateContent","params":{"files":{"C:\\src\\d1\\sdk\\b56355.dart":{"type":"add","content":"import 'package:http/http.dart' as http;\n\nclass CurrencyExc...
1722457602733 => {"id":"331","method":"completion.getSuggestions2","params":{"file":"C:\\src\\d1\\sdk\\b56355.dart","offset":206,"maxResults":100,"completionCaseMatchingMode":"FIRST_CHAR","completionM...
1722457607445 <= {"id":"110","error":{"code":"SERVER_ERROR","message":"Out of Memory","stackTrace":"#0      List._growToNextCapacity (dart:core-patch/growable_array.dart:397:5)\n#1      AstNodeExtensi...
```

**Comment by aam** [comment]
cc @scheglov

**Comment by mraleph** [comment]
Analyzer eating through all available memory should not be P2. Can somebody look at this?

**Comment by mraleph** [comment]
@aam can you still reliable reproduce this? I have tried different variants of 

```
import 'package:http/http.dart' as http;

class CurrencyExchanger {
  final Uri? currencyURL;

  const CurrencyExchanger({required this.currencyURL});

  Future getData(){
    http.Response response = http.G
  }
}
```

and none of them cause OOM.

**Comment by aam** [comment]
@mraleph wrote
> can you still reliable reproduce this? I have tried different variants of

I think so, yes. I have ```import 'package:http/http.dart' as http;

class CurrencyExchanger {
  final Uri? currencyURL;

  const CurrencyExchanger({required this.currencyURL});

  Future getData() {
    http.Response response = http
  }
}``` in the root of dart sdk repo that I go back and forth adding/removing characters after "http".

The runaway growth starts at second 44 from the video below
https://github.com/user-attachments/assets/886a52c6-5925-4373-b430-ba90cdcb3cf2

That is on
- Dart SDK 3.6.0-149.3.beta
- Dart IntelliJ 212.5744
- Android Studio Chipmunk | 2021.2.1 Patch 2
- Windows 10 10.0

**Comment by mraleph** [comment]
I still can't reproduce OOM myself but what I managed to reproduce is analyzer getting stuck. If I start with 

```dart
import 'package:http/http.dart' as http;

class CurrencyExchanger {
  final Uri? currencyURL;

  const CurrencyExchanger({required this.currencyURL});

  Future get() {
    http.Response response = http
  }
}
```

and then I type `Data` after `get` then analyzer stops responding. It seems that `import` might not even be necessary to reproduce this.

@scheglov does analyzer team have some easy way of replaying reproductions like this?

**Comment by scheglov** [comment]
I don't think we have an existing way to replay Analysis Server protocol logs.

**Comment by scheglov** [comment]
I can reproduce it manually though, and see in Observatory where it goes into a cycle, or at least uses too much CPU.

**Comment by bwilkerson** [comment]
> I don't think we have an existing way to replay Analysis Server protocol logs.

I don't think we do either, but we _can_ write a test that sends repeated 'overlay' requests to the server simulating what happens as the user types.

**Comment by scheglov** [comment]
Can be reduced to requesting completion at `^`.
```dart
void get^() {
  http.Response response = http
}
```
So far it seems that linking of tokens via `previous` has a cycle.

**Comment by scheglov** [comment]
It looks that there is an issue with parser recovery.
I enhanced the printer for AST and tokens in the analyzer, and see this for the code above.
Note `previousX` - these are references to tokens that must have been already seen, but actually we don't.
And `T8 T9 T10 T11` form a cycle via `previous`.

```
FunctionDeclaration
  returnType: NamedType
    name: T0 void @0
      next: T1 |get|
  name: T1 get @5
    previous: T0 |void|
    next: T2 |(|
  functionExpression: FunctionExpression
    parameters: FormalParameterList
      leftParenthesis: T2 ( @8
        previous: T1 |get|
        next: T3 |)|
      rightParenthesis: T3 ) @9
        previous: T2 |(|
        next: T4 |{|
    body: BlockFunctionBody
      block: Block
        leftBracket: T4 { @11
          previous: T3 |)|
          next: T5 |http|
        statements
          ExpressionStatement
            expression: PrefixedIdentifier
              prefix: SimpleIdentifier
                token: T5 http @15
                  previous: T4 |{|
                  next: T6 |.|
              period: T6 . @19
                previous: T5 |http|
                next: T7 |Response|
              identifier: SimpleIdentifier
                token: T7 Response @20
                  previous: T6 |.|
                  next: T8 |response|
            semicolon: T9 ; @45 <synthetic>
              previousX: T10 http @40
                previousX: T11 = @38
                  previous: T8 |response|
                  next: T10 |http|
                next: T9 |;|
              next: T8 |response|
          ExpressionStatement
            expression: SimpleIdentifier
              token: T8 response @29
                previous: T9 |;|
                next: T12 |;|
            semicolon: T12 ; @45 <synthetic>
              previous: T8 |response|
              next: T13 |}|
        rightBracket: T13 } @45
          previous: T12 |;|
          next: T14 ||
```

**Comment by mraleph** [comment]
cc @jensjoha for recovery issues.

**Comment by jensjoha** [comment]
This is not the parser.
The analyzer rewrites here:

https://github.com/dart-lang/sdk/blob/9f23661055f84cef0bb4766af839ae0c837b1606/pkg/analyzer/lib/src/fasta/ast_builder.dart#L3649

even *while* we're parsing.

All the rewrites happening on

```
void get() {
  http.Response response = http
}
```

in `test_recovery_body_issue56355` are:

From Parser.ensureSemicolon via Parser.parseVariablesDeclarationRest
Before: void get ( ) { http . Response response = http }
After: void get ( ) { http . Response response = http ; }

From AstBuilder.endVariablesDeclaration via Parser.parseVariablesDeclarationRest
Before: void get ( ) { http . Response response = http ; }
After: void get ( ) { http . Response (bad previous here) response }

From Parser.ensureSemicolon via Parser.parseExpressionStatement
Before: void get ( ) { http . Response (bad previous here) response }
After: void get ( ) { http . Response (bad previous here) response ; }

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/392460
