### ISSUE TITLE
`dart:io` File locking and writing to files on Windows

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56378]
I was expecting to be able to use 

```dart
void main() async {
  test('Single invocation', () async {
    await inTempDir((tempUri) async {
      final file = File.fromUri(tempUri.resolve('.lock'));
      final randomAccessFile = await file.open(mode: FileMode.write);
      await randomAccessFile.lock(FileLock.exclusive);
      await file.writeAsString('foo');
    });
  });
}
```

However, I get the following error

```
00:00 +0 -1: Single invocation [E]

  PathAccessException: writeFrom failed, path = 'C:\Users\dacoharkes\AppData\Local\Temp\d87914ab\.lock' (OS Error: The process cannot access the file because another process has locked a portion of the file.
  , errno = 33)

  dart:io/common.dart 55:9                                    _checkForErrorResponse
  dart:io/file_impl.dart 885:7                                _RandomAccessFile.writeFrom.<fn>
  dart:async/zone.dart 1407:47                                _rootRunUnary
  dart:async/zone.dart 1308:19                                _CustomZone.runUnary
  ===== asynchronous gap ===========================
  dart:io/file_impl.dart 635:64                               _File.writeAsBytes.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:io/file_impl.dart 744:3                                _RandomAccessFile.close
  ===== asynchronous gap ===========================
  pkgs\native_assets_cli\test\locking\locking_test.dart 22:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  pkgs\native_assets_cli\test\helpers.dart 26:5               inTempDir
  ===== asynchronous gap ===========================
  pkgs\native_assets_cli\test\locking\locking_test.dart 18:5  main.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9            Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7            Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9             Invoker._waitForOutstandingCallbacks.<fn>
```

It should be the same process!

So either our implementation is broken, and the snippet should work.

Or, the error message is bad (if our implemenation can't support this).

cc @brianquinlan

**Comment by mraleph** [comment]
On Windows locks are bound to specific handles, so if you open the file again (even within the same process) you don't have access to the locked file.  See documentation for [`LockFileEx`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-lockfileex#remarks) (emphasis mine):

> **Locking a region of a file is used to acquire shared or exclusive access to the specified region using this file handle**. If the file handle is inherited by a process created by the locking process, the child process is not granted access to the locked region. **If the locking process opens the file a second time, it cannot access the specified region through this second handle until it unlocks the region**.

**Comment by dcharkes** [comment]
The Dart snippet that I wrote could possible still work if the multiple Dart objects operate on the same file handle.

`randomAccessFile.lock` doesn't create a new handle, it uses the existing one.
`file.open` creates a new handle.
`File::Write` assumes there's already a file handle.
Since `file.open` is not necessary in Dart, I'm assuming that `File()` in Dart also creates a handle. So having both `File()` and doing an `open()` on that file creates two handles? The first one trying to be used for the writing, the second one for the lock?  🤷

**Comment by mraleph** [comment]
> Since `file.open` is not necessary in Dart, I'm assuming that `File()` in Dart also creates a handle. 

`File` does not contain a handle - but `writeAsString` is a compound operation (open-write-close) so it does open a file again. 

We could cache and share handles - but I think this will get out of hand quickly (e.g. consider situations with different file paths, symlinks, multiple isolates, etc).
