### ISSUE TITLE
[proposal] Adding the keyword 'interface'

### ISSUE THREAD

**Issue by Majestio** [dart-lang/sdk#56370]
Hello!

I have only recently started learning Dart, so I apologise if my suggestion comes across as silly.

I would like the Dart language to implement the `interface` keyword, which would be understood by the compiler identically to the `abstract class`. For example, the following two code fragments should be perceived identically by the compiler:
```
abstract class Person {
  void display();
}
```
```
interface Person {
  void display();
}
```
I realise this is syntactic sugar. But it would be great! :+1:

**Comment by lrhn** [comment]
That is a valid idea. It's already suggested in the language issue tracker as https://github.com/dart-lang/language/issues/3736
