### ISSUE TITLE
`unnecessary_breaks` quick-fix/assist should run when converting switch statement to if-case statement

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56371]
Consider the following code sample:

```dart
void main() {
  final v = 1;
  switch (v) {
    case 1:
      print('1');
      break;             // <- unnecessary_breaks
    case 2:
      print('2');
    default:
      print('default');
  }
}
```

The suggested assists for the switch are:

![Convert to if-case statement & convert to switch expression](https://github.com/user-attachments/assets/5c7d8a97-92f0-448e-9af7-e6d5ed73a58a)

1. When we select the first option to convert to an if-case statement this is the code we get:

```dart
void main() {
  final v = 1;
  if (v case 1) {
    print('1');
    break;            // <- break_outside_of_loop
  } else if (v case 2) {
    print('2');
  } else {
    print('default');
  }
}
```

So I believe the `unnecessary_breaks` assist should be run before the actual assist for the if-case statement transformation.

2. I believe that the `unnecessary_breaks` quick-fix should be an option at the _switch_ keyword for old switches with multiple breaks and also for cases like the above which would make them more self-explanatory.

If you think I should create more than one issue for these requests, tell me and I'll do so.

**Comment by scheglov** [comment]
@fshcheglov I think this is a good issue for you to solve.

**Comment by fshcheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/383931 

It will remove unnecessary breaks while converting to if/else chains.

I don't believe activating quick fix for unnecessary break on the switch statement itself is useful, however. There is already a quick-fix option to remove all unnecessary break statements in the file.

**Comment by scheglov** [comment]
I agree that associating the removing unnecessary `break` quick fix with the `switch` keyword is not useful.

**Comment by FMorschel** [comment]
My point in asking for the assist on the `switch` keyword was because for me it makes no sense to remove `break`s individually. Maybe we could have a new issue about it? I'm not sure we have any lints or similar that only solve that for the whole file.

**Comment by scheglov** [comment]
We can run the quick fix on the whole file as @fshcheglov mentioned.
You should enable `unnecessary_breaks` lint.

```dart
void f(int x) {
  switch (x) {
    case 0:
      0;
      break;
    case 1:
      0;
      break;
  }
}
```

<img width="516" alt="image" src="https://github.com/user-attachments/assets/29b80121-0b9f-45d0-9ac6-a90dfe58d07e">

**Comment by FMorschel** [comment]
I know I can. Sorry if I'm not clear enough. My point is that there should be no use for the `Remove break` option just above. There is no reason for someone to remove only one break at a time. That's what I was trying to say. Removing that stand-alone option would do as well. That's why:

> I'm not sure we have any lints or similar that only solve that for the whole file.

Focus on the _only_ in this phrase.

**Comment by scheglov** [comment]
I agree, there is little use in removing just one `break`, and not all of them.
Consider opening a separate issue to exclude individual `Remove break` from UI.

**Comment by FMorschel** [comment]
Created https://github.com/dart-lang/sdk/issues/56680. Thanks!

**Comment by FMorschel** [comment]
Hey! A follow-up on this. Missing breaks when converting back from empty if-case to switch statement: https://github.com/dart-lang/sdk/issues/56682.
