### ISSUE TITLE
Where is the documentation of Dart's Debug Adapter Protocol extensions?

### ISSUE THREAD

**Issue by sebthom** [dart-lang/sdk#56379]
There used to be a very informative documentation of the DAP at https://github.com/dart-lang/sdk/blob/main/pkg/dds/tool/dap/README.md it got removed as part of this commit https://github.com/dart-lang/sdk/commit/e609c8232b8f5b9b64544a146bd53f7cafeaf71a

Where can the up-to-date documentation of the Dart Debug Adapter and it's protocol extensions be found now? I searched the github org but couldn't find anything.

@DanTup

**Comment by DanTup** [comment]
@sebthom the document got moved to here:

https://github.com/dart-lang/sdk/blob/main/third_party/pkg/dap/tool/README.md

And the Flutter-specific parts are here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/README.md

Looks like there's a broken link in [this doc](https://github.com/dart-lang/sdk/blob/main/third_party/pkg/dap/README.md) pointing at the old URL so I'll send a fix. If there is anywhere else you see the old URL, please let me know so I can update.

**Comment by sebthom** [comment]
@DanTup  Thanks a lot!
