### ISSUE TITLE
[CP] [dart2wasm] Fix bug in setter type checker argument checking implementation

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#56374]
### Commit(s) to merge

2cf3222e4f1c00c36e1b072c1de8db31dad01de7

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/378860

### Issue Description

Flutter code that uses dynamic calls where the dynamic call targets a setter with a generic argument will (in `-O3` / `-O4` mode - the ladder which is flutter builds default) sets `null` instead of the actual value.

### What is the fix

Make compiler in `-O3` / `-O4` mode correctly set the field value in the implicit setter.

### Why cherry-pick

Flutter users have hit this.

### Risk

If tests pass: low

### Issue link(s)

https://github.com/flutter/flutter/issues/152029

**Comment by vsmenon** [comment]
lgtm

**Comment by mkustermann** [comment]
@itsjustkevin any chance we could get this approved & landed to be included in time for upcoming dot release?

**Comment by itsjustkevin** [comment]
@mkustermann approved. Please write a changelog update pointing back to this issue to satisfy the submit requirements.

**Comment by mkustermann** [comment]
> @mkustermann approved. Please write a changelog update pointing back to this issue to satisfy the submit requirements.

The CL landed
