### ISSUE TITLE
what is dart develop service ？

### ISSUE THREAD

**Issue by zhumingwei** [dart-lang/sdk#56389]
what is dart develop service ？
and
why can I use flutter DevTools from website when i try the --disable-dds flag 
image

if i disable DSS，what will be impact？
thank you @bkonyi 
#55791

**Comment by bkonyi** [comment]
The Dart Development Service (DDS) is middleware that sits between the Dart runtime (both native and web) that IDEs and tools (like Dart/Flutter DevTools) communicate with to interact with the running Dart program for debugging, profiling, etc.

Each runtime implements the [Dart VM service protocol](https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md), which contains core functionality that needs explicit knowledge about internals of the runtime to work (e.g., setting breakpoints). To avoid reimplementing functionality that doesn't need explicit knowledge of runtime internals, [DDS provides its own extensions on the Dart VM service protocol](https://github.com/dart-lang/sdk/blob/main/pkg/dds/dds_protocol.md).

Disabling DDS can potentially degrade some tooling (e.g., DevTools won't have access to logs from the time before it connected) or, in theory, cause some tools to not work at all. In the future, DDS will likely be responsible for hosting DevTools, so disabling it will also disable DevTools. In general, you shouldn't disable DDS unless you're encountering a bug with it, and even then you should file an issue so we can try and find a fix.
