### ISSUE TITLE
Graduate the `invalid_runtime_check_with_js_interop_types` lint out of experimental

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#56396]
We're considering adding the `invalid_runtime_check_with_js_interop_types` lint to the package:lints lint set; we'd want to graduate the rule out of experimental before that.

cc @srujzs

**Comment by srujzs** [comment]
What does this entail? I thought it was connected to the `LintRule`, but `LintRule.state` is stable for this lint.

**Comment by devoncarew** [comment]
I don't know; it shows as experimental here: https://dart.dev/tools/linter-rules/invalid_runtime_check_with_js_interop_types; perhaps there's something still to toggle, or perhaps it's been changed and there's some latency in updating that page.

**Comment by bwilkerson** [comment]
@parlough

**Comment by kevmoo** [comment]
I think we need to update the website lints.

https://github.com/dart-lang/site-www/pull/6025 this PR landed, but I think the JSON file is old!

**Comment by kevmoo** [comment]
I take that back. I just ran the update script against `stable` – and it all lines up. 🤷

**Comment by kevmoo** [comment]
https://github.com/dart-lang/site-www/blob/main/src/_data/linter_rules.json#L1330 – it's updated!

hrm...

**Comment by kevmoo** [comment]
is there a cache that's...old?
or something not rebuilt @parlough ?

**Comment by srujzs** [comment]
Is this because of the `3.5.0-wip` SDK dependency? It looks like the equivalent code in the SDK has been updated by @parlough [yesterday](https://github.com/dart-lang/sdk/commit/c50c194d419c09bdbc9267eb8ed045819fb0beed) (thanks!).

**Comment by devoncarew** [comment]
I'd guess something similar; I don't think there's anything to update here wrt the impl. or state flag of the lint.

**Comment by parlough** [comment]
I'm updating dart.dev in https://github.com/dart-lang/site-www/pull/6033 which will surface it as stable and released in 3.5. I didn't do it right away as I had to account for lints no longer being part of 3 predefined categories.
