### ISSUE TITLE
[vm/ffi] `@Array.variable()` reports `variable_length_array_not_last` error for getters/setters

### ISSUE THREAD

**Issue by halildurmus** [dart-lang/sdk#56399]
The following code
```dart
import 'dart:ffi';

base class MyStruct extends Struct {
  @Size()
  external int length;

  @Array.variable()
  external Array<Uint8> inlineArray;

  bool get foo => true;
}
```

produces this error:

![Screenshot 2024-08-08 113044](https://github.com/user-attachments/assets/633c83b4-38fc-4051-bbb9-c460fd347100)

I believe this error is incorrect and the following code should be updated to exclude getters/setters in Ln 1484:
https://github.com/dart-lang/sdk/blob/da48538b1025d0d10ccd16cd32b4d2bef04d2bc6/pkg/analyzer/lib/src/generated/ffi_verifier.dart#L1480-L1492

/cc @dcharkes

**Comment by dcharkes** [comment]
Thanks @halildurmus!

Do you have the setup to submit a PR to fix this? (It should be a relatively easy fix indeed.) Otherwise I'll make one.

**Comment by halildurmus** [comment]
> Do you have the setup to submit a PR to fix this? (It should be a relatively easy fix indeed.) Otherwise I'll make one.

I don't have the setup ready at the moment, but this could be a great opportunity for me to get it done. I've been looking to contribute more to Dart, so I'll work on it and submit a PR in a few days. Feel free to assign the issue to me. Thanks!

**Comment by dcharkes** [comment]
If you're in vscode you can run the analyzer from source in the debugger with:

```
			{
				"name": "dart analyzer.dart",
				"type": "dart",
				"request": "launch",
				"program": "pkg/analyzer_cli/bin/analyzer.dart",
				"args": [
					"tests/ffi/static_checks/vmspecific_static_checks_array_test.dart",
				],
				"toolArgs": [],
				"enableAsserts": true,
				"cwd": "${workspaceFolder}",
			},
```

That file would also be the place to add a new test. (but one that doesn't throw an error. 😄 

Tests can be run with

```
$ tools/build.py -mrelease runtime create_platform_sdk && tools/test.py -mrelease -cfasta tests/ffi/static_checks/vmspecific_static_checks_array_test.dart
$ tools/build.py -mrelease runtime create_platform_sdk && tools/test.py -mrelease -cdart2analyzer tests/ffi/static_checks/vmspecific_static_checks_array_test.dart
```

**Comment by halildurmus** [comment]
https://dart-review.googlesource.com/c/sdk/+/379622
