### ISSUE TITLE
Remove Widget also in list Widgets

### ISSUE THREAD

**Issue by JulianHock** [dart-lang/sdk#56390]
### Use case

Sometimes I want to remove a Widget from a list like in a Column or Row. I have to delete it manually, which is quite complicated if it´s a bigger one and wastes time. 

### Proposal

In single nested Widgets I have the possibility to use the suggestions to delete this Widget like when you have a Container in a Container. I would love to have this feature also for deleting single Widgets in list Widgets like Column or Row.
<img width="266" alt="image" src="https://github.com/user-attachments/assets/c7b54138-ebb2-4d56-9e3c-d303f63b1811">
<img width="248" alt="image" src="https://github.com/user-attachments/assets/387567ec-3fa8-4e49-9065-87fe3338862e">

**Comment by pq** [comment]
@bwilkerson

**Comment by bwilkerson** [comment]
Sounds reasonable to me.

**Comment by JulianHock** [comment]
Any news? Will this be implemented?

**Comment by tenhobi** [comment]
I have just added some functionality for this assist in https://github.com/dart-lang/sdk/issues/56637, so I can also enhance it of this request. Or maybe rather do it later in separate PR?

**Comment by tenhobi** [comment]
I have working solution for this. @pq @bwilkerson do you think I can add it to the mentioned PR https://github.com/dart-lang/sdk/pull/56638, since it affects the same code? Thanks :)

**Comment by pq** [comment]
Adding it to the existing PR works for me. Thanks!

**Comment by tenhobi** [comment]
Great, I have added the update for this issue to the PR. :) Feel free to review it.

**Comment by FMorschel** [comment]
The CL was merged. We can close this now @bwilkerson or @JulianHock.
