### ISSUE TITLE
pkg/dds/test/devtools_server/instance_reuse_test is failing and flaking

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#56407]
There are new test failures on [[ddc] Turning down unsound testing on canary (2)](https://github.com/dart-lang/sdk/commit/6c9b36fdc9a5185bbad9d9e555477a158e3e3523).

The tests
```
pkg/dds/test/devtools_server/instance_reuse_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-x64
```

**Comment by aam** [comment]
dup of https://github.com/dart-lang/sdk/issues/50237
