### ISSUE TITLE
"Wrap with Padding" assist should consider `prefer_int_literals`

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56413]
When `prefer_int_literals` is set to true, the assist for `Wrap with Padding` should set the `EdgeInsets.all(8.0)` to `EdgeInsets.all(8)` by default.

```dart
Padding(
  padding: const EdgeInsets.all(8.0), // <- lint prefer_int_literals
  child: const Placeholder(),
)
```

Would then become:

```dart
Padding(
  padding: const EdgeInsets.all(8), // <- no lint
  child: const Placeholder(),
)
```

**Comment by scheglov** [comment]
@fshcheglov I think this is a good issue for you to solve.

**Comment by fshcheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/384100
