### ISSUE TITLE
In Dart 3.5.0 analysis_options.yaml don't seem to be used under certain conditions

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#56416]
I'm attaching a zip file containing the source code for a reproducer. [source.zip](https://github.com/user-attachments/files/16558732/source.zip)

Summary:
When editing a project in a specific way, `analysis_options.yaml` file doesn't get picked up and the project lacks the enabled lints.

The project structure is as follows:
```
app/                                    <- this is where the app implementation lives
app/main_app/                           <- this is the dart package root for the main app
app/main_app/lib/main.dart
app/main_app/lib/src/a.dart
app/main_app/analysis_options.yaml
app/main_app/pubspec.yaml
extra/                                  <- custom lints live here
extra/lib/analysis_options.yaml         <- our custom lints
extra/pubspec.yaml
```

```yaml
# extra/lib/analysis_options.yaml
include: package:lints/recommended.yaml

linter:
  rules:
    prefer_relative_imports: true
```

```dart
// app/main_app/lib/main.dart

import 'package:main_app/src/a.dart';

void main(List<String> args) {
  print(A());
}
```

```dart
// app/main_app/lib/src/a.dart

class A {}
```

```yaml
# app/main_app/analysis_options.yaml
include: package:extra/analysis_options.yaml
```

Steps to reproduce:
1. Open `app/` in an editor
3. Open `main_app/lib/main.dart`
4. There should be a lint for the import, but there is none.
Running `dart analyze` on `app/` produces the same behavior.

On the other hand, if we open `app/main_app` directly or run `dart analyze` on it. We observe all the expected lints.

In addition if we copy over the lints from `extra/lib/analysis_options.yaml` to `app/main_app/analysis_options.yaml`, we are correctly notified of all lints even when editing the project from `app`.

So it seems when a project is opened from a directory above it, lints from included files are not picked up.

**dart --version**
`Dart SDK version: 3.5.0 (stable) (Tue Jul 30 02:17:59 2024 -0700) on "macos_arm64"`

Perhaps this is related to #55975.

**Comment by pq** [comment]
@keertip: do we think this is handled by your recent fixes?

**Comment by keertip** [comment]
Yes, this should be handled with the recent fixes.

@jellynoone, which channel of dart are you on? The latest dev channel has the fix, the other channels (stable, beta) probably not.

**Comment by jellynoone** [comment]
Originally tested this on stable, 3.5.0. Since then tested this on dev, and everything works as expected.

Will this be cherry-picked?

**Comment by bwilkerson** [comment]
@itsjustkevin

**Comment by lucasjinreal** [comment]
The functionality is impaired. It is kindly requested to upgrade to at least a minimally operational Dart release before pushing to Flutter....!!

**Comment by lishaduck** [comment]
To clarify what @lucasjinreal said, this is also broken in Flutter. It drove me crazy last night, and I was about to file a Dart-Code issue 🤣
I can check if it's in the flutter dev channel, though I would assume it is?

**Comment by lucasjinreal** [comment]
@lishaduck Thank you for your expression! I uninstalled Flutter and reinstalled the beta channel, but the same issue occurred. Now this is truly troublesome!

**Comment by lishaduck** [comment]
> I uninstalled Flutter and reinstalled the beta channel, but the same issue occurred. Now this is truly troublesome! [...] Beta channel actually not work at all!!

As @keertip said,

> The latest dev channel has the fix, the other channels (stable, beta) probably not.

`dev` == `main`

Try `flutter channel main`, that _should_ fix it. If not, we just need to wait for a new version of Dart to make it to Flutter. Notifying everyone subscribed doesn't get it fixed any faster.

**Comment by lucasjinreal** [comment]
No, it's master.

**Comment by lucasjinreal** [comment]
> Originally tested this on stable, 3.5.0. Since then tested this on dev, and everything works as expected.

main master dev stable beta ....

We are just getting extremly confused.

**Comment by jellynoone** [comment]
> > Originally tested this on stable, 3.5.0. Since then tested this on dev, and everything works as expected.
> 
> main master dev stable beta ....
> 
> We are just getting extremly confused.

I was talking about the [Dart channel](https://dart.dev/get-dart#dev-channel) here, not the Flutter branch.

**Comment by lucasjinreal** [comment]
@jellynoone  Hi, what is the meaning of `by editing the project at its root`? Could you elaborate a little on how to modify the YAML files? Which part needs to be changed?

**Comment by lucasjinreal** [comment]
In my case, I think I am actually opened the `main_app`, my is just a bare flutter project, looks like:

```
main_app/                
    lib/
      main.dart
    analysis_options.yaml
    pubspec.yaml
```

typically I will `code ./main_app` which opens the root as you suggested, but is where the error comes.

**Comment by lishaduck** [comment]
In that case, it's a different issue. This issue is about includes from monorepos.

**Comment by lucasjinreal** [comment]
To me, it's the same issue, but don't know why your solution works in your situation.

**Comment by lishaduck** [comment]
> To me, it's the same issue, but don't know why your solution works in your situation.

I think they're different bugs, with similar symptoms.
@jellynoone & I both use monorepos, and for both of us, the include directive doesn't work.

If analysis_options also doesn't work under _other_ conditions now, that _is_ also a bug, but not what _this_ thread is about.

**Comment by lucasjinreal** [comment]
Yes, the symptoms are identical (as indicated by the error messages), nonetheless, it does not necessarily imply that the root cause is also the same, unless we determine the reason. 

Currently, I can only wait for the next Flutter release. It is blocked.

**Comment by lishaduck** [comment]
Duplicate of #56047.
Fixed by b513402ee7d3424f585f2d92ccba8c89664908d9.
Pending #56464.

As @lucasjinreal said, all we can do is wait.

**Comment by jellynoone** [comment]
Tried to reproduce the issue with Dart 3.5.1 and I couldn't.

**Comment by lishaduck** [comment]
Flutter [3.24.1](https://github.com/flutter/flutter/releases/tag/3.24.1) cherrypicked this, file a new issue if upgrading doesn't resolve it, @lucasjinreal
