### ISSUE TITLE
Struct member's values are being incorrect except the last one when unwraped in native by its address

### ISSUE THREAD

**Issue by codesculpture** [dart-lang/sdk#56425]
Native
```c
void unWrapPointer(int* a) {
        printf("%d\n", *a);
}
```

Dart Native Binding
```dart
@Native<Void Function(Pointer<Int8>)>(isLeaf: true)
external void unWrapPointer(Pointer<Int8> a);

final class SampleStruct extends Struct {
  @Int8()
  external int a;
  @Int8()
  external int b;
}
```

Actual dart to execute
```dart
final struct = Struct.create<SampleStruct>();
struct.a = 2;
struct.b = 2;
unWrapPointer(struct.a.address);
unWrapPointer(struct.b.address);
```

The expected output:
2
2

But actual output:
514
2

Also it turned out, the more members you add in the struct only the last member's value is correct 
For ex:
```dart
final class SampleStruct extends Struct {
  @Int8()
  external int a;
  @Int8()
  external int b;
  @Int8()
  external int c;
  @Int8()
  external int d;
}

```
From the above, only the d's pointer is unwrapped correctly, else are seems exponential integers in descending order (which are seems offset because the more the members the more the first element value is, but not sure)

**Comment by mkustermann** [comment]
```
void unWrapPointer(int* a) {
        printf("%d\n", *a);
}
```
Shouldn't this code be using `int8_t* a` as argument instead of `int* a`?

**Comment by codesculpture** [comment]
Yup @mkustermann , the two int's are different here which is the C's `int` is 32bit but in the struct there was `Int8` which is 8bit.

If i correctly map the int types, the results are expected. Seems it isn't a bug 
Please someone confirm
Sorry for it @mkustermann @dcharkes

**Comment by mkustermann** [comment]
> Seems it isn't a bug

No worries, @codesculpture. 
Seems like we can close it as working-as-intended.
