### ISSUE TITLE
[CP] [dart2wasm] Pass source maps to wasm-opt when optimizing

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#56423]
### Commit(s) to merge

1b1740e941c33d64ed1bbca4914d0e6ad6b22cbb
075c443f2e24f022d9382f83d9f25036eb33c5f8

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/379782

### Issue Description

dart2wasm currently does not pass the generated source map to wasm-opt when optimizing with wasm-opt.

As a result the source map becomes invalid when the optimizations are enabled (i.e. always when `-O0` is not used).

### What is the fix

With this commit we pass the source map file to wasm-opt, which then updates it as it transforms the code.

### Why cherry-pick

Source map support in dart2wasm was cherry-picked to stable in https://github.com/dart-lang/sdk/issues/56239, but they are useless when optimizations are enabled.

### Risk

Assuming good test coverage of wasm-opt, I don't expect this change to break anything.

### Issue link(s)

We don't have a GitHub issue for this issue.

**Comment by mkustermann** [comment]
@itsjustkevin any chance we could get this approved & landed to be included in time for upcoming dot release?

**Comment by jason-simmons** [comment]
Flutter is seeing a regression with https://github.com/dart-lang/sdk/commit/1b1740e941c33d64ed1bbca4914d0e6ad6b22cbb

Flutter's tooling is passing the `--extra-compiler-option=--no-source-maps` flag.  With that flag I'm seeing an exception:

```
PathNotFoundException: Cannot rename file to '.../.dart_tool/flutter_build/0c09e3329b6c595a7b1c1f0a8ae9b18f/main.dart.unopt.wasm.map', path = '.../.dart_tool/flutter_build/0c09e3329b6c595a7b1c1f0a8ae9b18f/main.dart.wasm.map' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.renameSync (dart:io/file_impl.dart:349:5)
#2      CompileWasmCommand.run (package:dartdev/src/commands/compile.dart:860:33)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      DartdevRunner.runCommand (package:dartdev/dartdev.dart:236:18)
<asynchronous suspension>
#5      runDartdev (package:dartdev/dartdev.dart:47:16)
<asynchronous suspension>
#6      main (file:///usr/local/google/home/jsimmons/sky/engine/src/flutter/third_party/dart/pkg/dartdev/bin/dartdev.dart:13:5)
```

**Comment by osa1** [comment]
The issue above should be fixed with 075c443f2e24f022d9382f83d9f25036eb33c5f8.

I'll add that commit to my cherry-pick CL: https://dart-review.googlesource.com/c/sdk/+/379782.

**Comment by itsjustkevin** [comment]
@osa1 approved, please merge

**Comment by mkustermann** [comment]
> @osa1 approved, please merge

The CL was merged.
