### ISSUE TITLE
Why isn't a WeakReference not garbage collected although its Retaining Path is just `ObjectPool`

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/sdk#56432]
While trying to solve a feature request of a user of get_it I made my first tests with WeakReference and somehow the instance that I save in the WeakReference is never freed.
Looking at the memory view in profile mode I get the Shortest Retaining Path only:

```
ObjectPool
```

so I don't understand why even after triggering the GC multiple times and using the app, that this instance is still in Memory.

**Comment by escamoteur** [comment]
ok, after realizing that enums also are in the object pool I removed the const of the constructor and now the path looks like this

```
dart:core/_WeakReference
get_it/_ServiceFactory
dart:core/_List
dart:core/_GrowableList
get_it/_TypeRegistration
dart:collection/_Map
get_it/_Scope
get_it/_GetItImplementation
Isolate
```

But still the instance keeps in memory even after multiple GC calls

**Comment by julemand101** [comment]
Be aware that the Memory overview in DevTools might be kinda broken in 3.5.0: https://github.com/dart-lang/sdk/issues/56408

Where the issue could make objects stay in memory while you are looking at the Memory overview...

**Comment by mkustermann** [comment]
@escamoteur The most likely case here is that whatever the `WeakReference` points to is also referenced by some other object (i.e. there's a strong reference).

We do have some more advanced heap analysis tools. I could encourage you to give [runtime/tools/heapsnapshot](https://github.com/dart-lang/sdk/tree/main/runtime/tools/heapsnapshot) a try - see it's README.md. In it's retaining path calculation it doesn't (iirc) consider weak references, so you'll see where the strong references are.

**Comment by escamoteur** [comment]
So you mean that there could be an additional strong reference that is not listed by the memory view?

**Comment by escamoteur** [comment]
just one clarification, how to do I run the load script? and can it use dumps that where created with the devtools?

**Comment by mkustermann** [comment]
> just one clarification, how to do I run the load script? 

IIRC It can also accept a Uri to a running VM and will request a heapsnapshot (same way DevTools obtains it).

> and can it use dumps that where created with the devtools?

Should work. The heapsnapshot format should be the same. But use a compatible version (the format rarely changes).

> So you mean that there could be an additional strong reference that is not listed by the memory view?

Well, the path that you show above, i.e.
```
dart:core/_WeakReference
get_it/_ServiceFactory
dart:core/_List
dart:core/_GrowableList
get_it/_TypeRegistration
dart:collection/_Map
get_it/_Scope
get_it/_GetItImplementation
Isolate
```
Looks like a retaining path to the `WeakReference` object, not to the actual object the `WeakReference` points to. Maybe DevTools treats `WeakReference` as strong references when calculating retaining paths?

In any case using [`runtime/tools/heapsnapshot`](https://github.com/dart-lang/sdk/tree/main/runtime/tools/heapsnapshot) should give you precise & detailed answers.

**Comment by escamoteur** [comment]
Thanks, after some trying there is indeed a reference in completer that was never completed.
there should be a link to this tool in the docs of the weak reference

**Comment by mkustermann** [comment]
> Thanks, after some trying there is indeed a reference in completer that was never completed.
> there should be a link to this tool in the docs of the weak reference

IMHO this tool's capabilities should be integrated into DevTools - as it's much more powerful way to analyze heap snapshots than what DevTools offers today. /cc @kenzieschmoll

**Comment by escamoteur** [comment]
absolutely

**Comment by mkustermann** [comment]
@escamoteur Happy you found it useful. Can this bug then be closed (as it's not a GC bug)?

**Comment by escamoteur** [comment]
Yep. although I'm surprised that a completed Completer keeps a reference

**Comment by mkustermann** [comment]
> Yep. although I'm surprised that a completed Completer keeps a reference

If the `Completer` is referenced and alive, then `Completer.future` will be alive.
Even when a `Future` is completed, one can still register more listeners (e.g. via `await future` or `future.then((value) => print(value)`). That means it *has* to keep the value, in case someone consumes it (futures can be listened to many times)

**Comment by escamoteur** [comment]
Yeah, I now realized that too. I was able to refactor that part so that this isn't a problem anymore
