### ISSUE TITLE
Analysis server crash

### ISSUE THREAD

**Issue by iamkachigo** [dart-lang/sdk#56433]
[Error - 02:34:47] The Dart Analysis Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 02:34:47] Dart Analysis Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 02:34:47] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by keertip** [comment]
@iamkachigo, we need more information from you to figure out what might be the issue here? Are there any more logs that you can send?

**Comment by iamkachigo** [comment]
[Error - 00:30:52] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 00:30:52] Connection to server got closed. Server will restart.
true
[Error - 00:30:52] Dart Analysis Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:30:53] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 00:30:53] Connection to server got closed. Server will restart.
true
[Error - 00:30:53] Dart Analysis Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:30:53] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 00:30:53] Connection to server got closed. Server will restart.
true
[Error - 00:30:53] Dart Analysis Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:30:53] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:30:53] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 00:30:53] Connection to server got closed. Server will restart.
true
[Error - 00:30:53] Dart Analysis Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:30:53] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:30:53] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:30:53] The Dart Analysis Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 00:30:53] Dart Analysis Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:30:53] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by srawlins** [comment]
@iamkachigo thanks for the report. Can you collect an instrumentation log, by following the instructions here: https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/tutorial/instrumentation.md

Thanks!

**Comment by mraleph** [comment]
This is unactionable without additonal information.
