### ISSUE TITLE
[CP] Fix crashes due to unhandled StructuralParameterTypes in UP in the CFE

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#56439]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/379800

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/380001

### Issue Description

The algorithm for computing the standard upper bound of two types, also known as UP, was partially missing its implementation for `StructuralParameterType` objects. In some corner casing the lacking implementation resulted in a crash of the compiler. All platforms using the CFE were affected.

### What is the fix

The fix adds the missing part of the UP algorithm.

### Why cherry-pick

The crashes due to the lacking implementation of UP in the CFE were reported by Flutter users: https://github.com/flutter/flutter/issues/152984.

### Risk

Low. The update is local and minimal and passes our CQ tests. Moreover, the missing part of the algorithm is implemented via abstracting a similar part of the same algorithm for `TypeParameterType` objects and applying it to `StructuralParameterType` objects.

### Issue link(s)

https://github.com/flutter/flutter/issues/152984

**Comment by itsjustkevin** [comment]
@chloestefantsova is this meant for stable? This will land in the next Dart beta branch coming soon, we won’t need to cherry-pick to beta.

**Comment by chloestefantsova** [comment]
@itsjustkevin I'm not entirely sure. @mraleph requested a CP, and @johnniwinther suggested it should be in beta. I'm happy to recreate the request for stable if needed.

**Comment by johnniwinther** [comment]
Move it to stable. It's satisfactory to have it in the next beta.

**Comment by chloestefantsova** [comment]
Following the discussion above, I'm closing this request. I've created the CP for `stable` instead: https://github.com/dart-lang/sdk/issues/56457.
