### ISSUE TITLE
[Wildcard Variables][analyzer] Const wildcard functions have no errors when referenced

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#56447]
```
void _(int a) {}
const x = _;
```

**Produces no error** currently, but should have an error.

In comparison, the CFE correctly produces an error like:
```
// ../temp.dart:3:13: Error: Undefined name '_'.
//   const x = _;
```

cc. @pq

**Comment by pq** [comment]
Same question as https://github.com/dart-lang/sdk/issues/56446, are these top-level declarations?
