### ISSUE TITLE
[CP] [dart2wasm] Fix partial instantiation constants

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#56440]
### Commit(s) to merge

f7fc4d037466a099000962f3f0eb20e01048e37c

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/380120

### Issue Description

Using partial instantiation constants of generic methods with named parameters can in certain situations lead to compiler crashes.

### What is the fix

Fix the code that handles partial instantiation constants in dart2wasm.

### Why cherry-pick

Users have hit this problem.

### Risk

If all tests pass: low.

### Issue link(s)

https://github.com/dart-lang/sdk/issues/56372

**Comment by mkustermann** [comment]
@athomas Could we get this approved so it gets included in the upcoming hotfix release?

**Comment by itsjustkevin** [comment]
@mkustermann based on previous discussions, I am going to mark this cherry-pick approved.

**Comment by mkustermann** [comment]
> @mkustermann based on previous discussions, I am going to mark this cherry-pick approved.

Thanks a lot, @itsjustkevin. No more cherry-picks for dart2wasm in the SDK (still one dependent in flutter/flutter - https://github.com/flutter/flutter/pull/153310)
