### ISSUE TITLE
[Wildcard Variables][analyzer] Const wildcard variables have no errors when referenced

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#56446]
```
const _ = true;
const x = _;
```

**Produces no error** currently, but should have an error.

In comparison, the CFE correctly produces an error like:
```
// ../temp.dart:4:13: Error: Undefined name '_'.
//   const x = _;
```

cc. @pq

**Comment by pq** [comment]
Are these top-level variables? If that's the case, I'd expect `const _` to be binding and not to produce an error. Or?

https://github.com/dart-lang/language/blob/main/working/wildcards/feature-specification.md#other-declarations

**Comment by kallentu** [comment]
You're right. Same with the others. I'll close these out and add the tests to const eval.
