### ISSUE TITLE
ZLibDecoder regression in 3.5.0

### ISSUE THREAD

**Issue by vHanda** [dart-lang/sdk#56481]
I've been using the ZLib decoder as part of the [dart-git](https://github.com/GitJournal/dart-git) project. With the 3.5.0 release decoding packfiles was now failing. Here is a simple test case -

```dart
import 'dart:convert';
import 'dart:io';

void main() {
  var inputBase64 =
      'eJwzNOQCAAECAG0zeJwzMuICAAEHAG+gBHicMzQwMDMxUTDUy01h2HLP0j09OHF5Oa/mjhk6DtV8xzYtMITIG4Hkta8uWNlldoZj7YruBl/rB+7PVkV3AQC3+Bg/oAR4nDM0MDAzMVEw1MtNYdhyz9I9PThxeTmv5o4ZOg7VfMc2LTCEyBuB5Hl+f+ho+7Nypcz24DftJif8Tz/VmQ8AyhIZkDJ4nDPiAgAAcAA9oAR4nDM0MDAzMVEw1MtNYbjAMvFvXfS2XxpHxRfsNtqxlS14rq8hRN4IJM/z+0NH25+VK2W2B79pNznhf/qpznwACNQa3jJ4nDPkAgAAbgA8oAJ4nDM0MDAzMVEw1MtNYbjAMvFvXfS2XxpHxRfsNtqxlS14ri8As6AMrFeTuOFQovZrxXbBpf1PlYRP5yUE';
  var inputBytes = base64.decode(inputBase64);
  zlib.decoder.convert(inputBytes);
  print('Everything worked');
}
```

This code worked in dart 3.4.0 but throws the following exception with dart 3.5.0 -

 ```
Unhandled exception:
FormatException: Filter error, bad data
#0      _FilterImpl.processed (dart:io-patch/filter_patch.dart:13:71)
#1      _FilterSink.addSlice (dart:io/data_transformer.dart:503:29)
#2      _FilterSink.add (dart:io/data_transformer.dart:489:5)
#3      ZLibDecoder.convert (dart:io/data_transformer.dart:363:9)
#4      main (file:///Users/vishesh/src/gitjournal/dart-git/test.dart:8:16)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Here is the [original test](https://github.com/GitJournal/dart-git/blob/master/test/commit_test.dart)  from which I created the smaller test case. Here is the [Packfile zlib decompresssion code](https://github.com/GitJournal/dart-git/blob/master/lib/plumbing/pack_file.dart#L136)

I think this is caused by [this change](https://dart-review.googlesource.com/c/sdk/+/363964) by @brianquinlan 

Please could you provide a workaround or let me know if this can be fixed in time for the flutter Sept release. Accordingly, I'll roll back upgrading GitJournal to the latest flutter version.

**Comment by brianquinlan** [comment]
Python can decompress this data:

```python
>>> import zlib
>>> import base64
>>> input = base64.b64decode('eJwzNOQCAAECAG0zeJwzMuICAAEHAG+gBHicMzQwMDMxUTDUy01h2HLP0j09OHF5Oa/mjhk6DtV8xzYtMITIG4Hkta8uWNlldoZj7YruBl/rB+7PVkV3AQC3+Bg/oAR4nDM0MDAzMVEw1MtNYdhyz9I9PThxeTmv5o4ZOg7VfMc2LTCEyBuB5Hl+f+ho+7Nypcz24DftJif8Tz/VmQ8AyhIZkDJ4nDPiAgAAcAA9oAR4nDM0MDAzMVEw1MtNYbjAMvFvXfS2XxpHxRfsNtqxlS14rq8hRN4IJM/z+0NH25+VK2W2B79pNznhf/qpznwACNQa3jJ4nDPkAgAAbgA8oAJ4nDM0MDAzMVEw1MtNYbjAMvFvXfS2XxpHxRfsNtqxlS14ri8As6AMrFeTuOFQovZrxXbBpf1PlYRP5yUE')
>>> zlib.decompress(input)
b'11\n'
```

I'm surprised that there are only 3 bytes of output though for 318 bytes of input.

**Comment by brianquinlan** [comment]
The compressed data looks like this:
```
00000000: 789c 3334 e402 0001 0200 6d33 789c 3332  x.34......m3x.32
00000010: e202 0001 0700 6fa0 0478 9c33 3430 3033  ......o..x.34003
00000020: 3151 30d4 cb4d 61d8 72cf d23d 3d38 7179  1Q0..Ma.r..==8qy
...
```

789c is the start of the ZLib header and means default compression. Dart (and Python) decompresses bytes [0, 10] into "11\n".

Dart then looks for the next compression block at byte 11, which starts with 0x33. A ZLib header cannot start with 0x33 so Dart throws. It looks like Python just ignores the data.

Bytes [12,...] **do** represent valid ZLib data:

```python
>>> zlib.decompress(input[0:11])
b'11\n'
>>> zlib.decompress(input[12:24]) # Notice how we are skipping input[11]
b'22\n'
>>> zlib.decompress(input[0:11] + input[12:])
b'11\n'. # This is surprising...
```

**Comment by brianquinlan** [comment]
[RFC-1950](https://www.rfc-editor.org/rfc/rfc1950) says:

> Any data which may appear after ADLER32 are not part of the zlib stream.

**Comment by brianquinlan** [comment]
I have a PR in the works:
https://dart-review.googlesource.com/c/sdk/+/380861
