### ISSUE TITLE
Weird error: The argument type 'Object' can't be assigned to the parameter type 'Object'. 

### ISSUE THREAD

**Issue by martin-east** [dart-lang/sdk#56480]
```
typedef Equator = bool Function(Object, Object);
class ObjectProblem<Object> {
  ObjectProblem(this.i, this.equator);
  final Iterator<Object> i; 
  final Equator equator;
  bool get test1 => equator(i.current, i.current); // produces below error message for each i.current
  bool get test2 => (equator as bool Function(Object, Object))(i.current, i.current); // this compiles
  bool get test3 => equator(3, 4); // this also compiles
 ```
VSCode produces this rather illogical error for test1: 
"The argument type 'Object' can't be assigned to the parameter type 'Object'." 

Background: I extended Object earlier in the code, might this be relevant? 
I'm using Dart sdk: '^3.3.0'

I think this might be a compiler bug. If not, can anyone tell me how to call equator with i.current without having to cast it?

Thanks for any help

**Comment by eernstg** [comment]
It's rarely a good idea to declare a type parameter whose name is the same as an existing type. It's better to use a fresh name for type parameters, in this case `X`:

```dart
typedef Equator = bool Function(Object, Object);

class ObjectProblem<X> {
  ObjectProblem(this.i, this.equator);
  final Iterator<X> i; 
  final Equator equator;
  bool get test1 => equator(i.current, i.current); // Error
  bool get test2 => (equator as bool Function(X, X))(i.current, i.current);
  bool get test3 => equator(3, 4);
}
```

**Comment by martin-east** [comment]
Erik, I would like to thank you for your rapid and detailed response. It's very helpful and much appreciated.
 
The problem comes down to me incorrectly defining the type parameter in ObjectProblem. I thought I was specifying that it must be a subtype of Object but all I was doing was defining a type parameter named Object, confusingly by default a subtype of Object?  
 
Your suggested correction to ObjectProblem(X extends Object) solves my problem, but I have two suggestions: 

1) a linter rule that discourages declaring a type parameter whose name is the same as an existing type
2) making the error message less confusing by including the type of which the type parameter must be a subtype

Once again many thanks for your help

**Comment by eernstg** [comment]
Thanks for the kind words!

> a linter rule that discourages declaring a type parameter whose name is the same as an existing type

Indeed, I created https://github.com/dart-lang/linter/issues/5066 for that.

> making the error message less confusing by including the type of which the type parameter must be a subtype

@bwilkerson, WDYT?
