### ISSUE TITLE
Failures on [DEPS] Update chrome_tag to latest beta (128.0.6613.36)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#56519]
There are new test failures on [[DEPS] Update chrome_tag to latest beta (128.0.6613.36)](https://github.com/dart-lang/sdk/compare/30a720b795c5da14d2d5b4b924de1f00d879e1f2~...37bda88ce7e9cedbe8e78228f4327e34622981cb).

The tests
```
pkg/dds/test/devtools_server/remote_control_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8739137491030815569/+/u/test_results/new_test_failures__logs_

**Comment by a-siva** [comment]
//cc @fishythefish

**Comment by srujzs** [comment]
Better logs here: https://dart-ci.appspot.com/log/any/unittest-asserts-release-mac-arm64/14137/pkg/dds/test/devtools_server/remote_control_test

It looks like this test is flaky already on all configurations. Perhaps this pushed it over the timeout threshold consistently on that configuration?

**Comment by fishythefish** [comment]
FWIW, the bot just turned red for two runs and then went back to green:
https://screenshot.googleplex.com/6tzFoG88sL5UYA6

**Comment by a-siva** [comment]
> FWIW, the bot just turned red for two runs and then went back to green: https://screenshot.googleplex.com/6tzFoG88sL5UYA6
> […](#)

It went back to green I presume because I approved the failure after filing this issue.

**Comment by fishythefish** [comment]
Ah, I missed that.

**Comment by srujzs** [comment]
It looks like the chrome_tag update also led to some timeouts with the expression compiler tests: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8739133313427483313/+/u/test_results/new_test_failures__logs_. I'll go ahead and revert this for now, but we should figure out what the issue is before the next stable.

**Comment by srujzs** [comment]
Reverted in https://dart-review.googlesource.com/c/sdk/+/381387.

**Comment by srujzs** [comment]
This has been re-rolled with some changes to how we start up Chrome, and should avoid the aforementioned timeouts.
