### ISSUE TITLE
[Dart VM] Cannot set pause_isolates_on_exit at runtime

### ISSUE THREAD

**Issue by gogolon** [dart-lang/sdk#56542]
Setting `pause_isolates_on_exit` flag using `VmService.setFlag` does not seem to have any effect.

**Reproduction**
1. Create a new dart project using `dart create minimal_sample`
2. Replace the code inside `bin/minimal_sample.dart` with the following snippet:
```dart
import 'dart:developer';
import 'dart:isolate';

import 'package:vm_service/vm_service_io.dart';

Future<void> main(List<String> arguments) async {
  final info = await Service.controlWebServer(enable: true);
  final vmService =
      await vmServiceConnectUri(info.serverWebSocketUri.toString());
  final success = await vmService.setFlag('pause_isolates_on_exit', 'true');
  print("setFlag response: $success");
  final mainIsolateRef =
      await vmService.getIsolate(Service.getIsolateId(Isolate.current)!);
  print("pause on exit: ${mainIsolateRef.pauseOnExit}");
  await vmService.dispose();

  print('hello world');
}
```
3. While at package's root, run `dart bin/minimal_sample.dart`. The program runs, exits and produces the following output:
```
setFlag response: [Success]
pause on exit: false
hello world
```
4. While at package's root, run `dart --pause-isolates-on-exit bin/minimal_sample.dart`. The process is kept alive due to the main isolate not exiting, and the output is:
```
setFlag response: [Success]
pause on exit: true
hello world
```

Despite `setFlag` returning Success, the isolate is not paused on exit - the flag only works when passed as an argument to `dart` command.

Here's the _General info_ section of my `dart info` output:
```
#### General info

- Dart 3.4.4 (stable) (Wed Jun 12 15:54:31 2024 +0000) on "macos_arm64"
- on macos / Version 14.6.1 (Build 23G93)
- locale is en-PL
```

**Comment by bkonyi** [comment]
This is currently working as intended. These flags are set for each isolate when the isolate is spawned, so isolates spawned after this flag is updated using `setFlag` will pause on exit.

However, given that there's 9 👍's what's the use case for fixing this behavior?

**Comment by gogolon** [comment]
Given that it's possible to just set the flag for each isolate using `setIsolatePauseMode`, I don't think there is any specific use case that would require changing the current behaviour. It confused me because it seemed intuitive that setting the flag at runtime should have the exact same effect as setting the flag when invoking the `dart` command, and it made me spend some time on trying to figure it out, but now I see that the note about it this is indeed included in the doc comment - I just missed it.
