### ISSUE TITLE
Obfuscation: A need for serious commitment in dart and flutter

### ISSUE THREAD

**Issue by junaid1460** [dart-lang/sdk#56543]
This is really time to build obfuscation like aar. One of the options what folks do is write in native code and then call that as dependency to prevent copying of the source code, this way dart and flutter would remain undeveloped for most cases. 

Can we explore this area ?

**Comment by bivens-dev** [comment]
Mostly just adding this for context but the popular hacking zine Phrack just released their latest issue after a long hiatus and one of the articles this month was specifically about someone’s attempt at this topic from the attackers perspective that could be an interesting read if nothing else: https://phrack.org/issues/71/11.html#article

**Comment by lrhn** [comment]
"Obfuscation" would be something that allows you to expose a package or library in a format other than plain source, which makes the code still usable in other programs, but which makes it "hard" to reproduce understandable source code from that format. 

Or do you want to obfuscate what's generated by compounding entire applications to maybe code? Or to JavaScript?

It'll only ever be "hard", not impossible. People can reproduce source code from machine code, the hard part is recognizing the logical structure and "putting back the names" ... and comments. That's a matter of dedication and how skilled the reverse engineerer is.
I expect AI-guided tools to improve the state of the art on this.

I personally question the cost effectiveness of the idea.
Obfuscation is not useful as hard security, and it's not useful as copyright protection, so it's probably about protecting trade secrets.
The value that would be lost if someone does reverse engineer the obfuscated code must be small enough that "hard" is enough deterrent, but non-zero to make the step of obfuscation worth doing.

And that's where I question whether the people who want to obfuscate their code really have a correct evaluation of their value _and_ threat model.

**Comment by mraleph** [comment]
If you are talking about obfuscation of deployed applications then just follow Flutter [guide](https://docs.flutter.dev/deployment/obfuscate). If you use `--obfuscate --split-debug-info=...` when building Flutter application the Dart code will be just as hard to reconstruct from its compiled form as C/C++ code. It is security through obscurity though - code can always be decompiled one way or another. 

If you are talking about hiding code of Dart packages (e.g. creating proprietary packages which hide their own code) then we currently have no plans to explore this (https://github.com/dart-lang/sdk/issues/42863)

**Comment by junaid1460** [comment]
Also a request, please don't close without notice/resolution.

**Comment by mraleph** [comment]
> I am talking about obfuscation at library distribution end.

Then it is a duplicate of https://github.com/dart-lang/sdk/issues/42863 - and the resolution remains the same: we have no current plans to provide this.
