### ISSUE TITLE
Build issue with js_interop `isA`

### ISSUE THREAD

**Issue by arnaud-secondlayer** [dart-lang/sdk#56564]
I'm creating a generic function that leverages `isA` and get a build error when building to javascript.
I'm not able to find a solution.

I have the following script:
```
import 'dart:js_interop';
import 'package:web/web.dart' as web;

bool myIsA<T extends web.Element>(JSAny element) => element.isA<T>();

int main(){
  return 0;
}
```

There is the build error with `dart compile js a.dart`:

```
a.dart:4:61:
Error: Type argument 'T' needs to be an interop 'ExtensionType'.
bool myIsA<T extends web.Element>(JSAny element) => element.isA<T>();
                                                            ^
Error: Compilation failed.
```

```
dart --version
Dart SDK version: 3.5.1 (stable) (Tue Aug 13 21:02:17 2024 +0000) on "macos_arm64"
```

**Comment by sigmundch** [comment]
Thanks so much for reaching out. This is a great question!

cc @srujzs

Unfortunately, I don't believe this pattern can be supported. 

The way the `isA` method works, is through a static compiler transformation that needs to see explicitly the actual type passed to it. For example, the list of cases mentioned in the [isA API docs][1] are all resolved statically:
```
e.isA<JSBoolean>()  -- becomes --> typeof e == 'boolean'
e.isA<DivElement>() -- becomes --> instanceof e == 'HTMLDivElement'
...
```

The pattern you show, where `isA` gets wrapped in a generic method, makes the instantiation of `T` happen later at runtime, and as a result the compiler no longer knows what to generate. Note that most information about interop types is erased during compilation, so there is no runtime alternative to achieve the same goal.

One small action item we can do here is to improve the error message and to add a note about this in the API docs. 

[1]: https://api.dart.dev/stable/3.5.1/dart-js_interop/JSAnyUtilityExtension/isA.html
