### ISSUE TITLE
Extension methods on records are not suggested

### ISSUE THREAD

**Issue by s0nerik** [dart-lang/sdk#56572]
This happens to all types of records, in any editor, even if the extension is already imported. Here's an example with [`FutureRecord2.wait`](https://api.flutter.dev/flutter/dart-async/FutureRecord2/wait.html):

![CleanShot 2024-08-26 at 13 14 19@2x](https://github.com/user-attachments/assets/bbbf8ade-1075-4bcf-a831-97173f0858a8)
![CleanShot 2024-08-26 at 13 18 07@2x](https://github.com/user-attachments/assets/b2ce7293-1d2f-4c7a-97ba-b99cb3f44487)

```
dart --version
Dart SDK version: 3.5.0 (stable) (Tue Jul 30 02:17:59 2024 -0700) on "macos_arm64"
```

**Comment by scheglov** [comment]
@fshcheglov

**Comment by fshcheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/382261
