### ISSUE TITLE
Cascading and callable

### ISSUE THREAD

**Issue by Solido** [dart-lang/sdk#56586]
* Dart analyzer and linter

Callable is not compatible with cascading.

In my case it is used as an `init()` lifecycle but I want to keep the reference 
of the A instance. 

If force 2 lines declaration and it's surprising to have
to make a direct reference to `call`.

Thanks!

``` dart
void main() {
  A()..call('OK');
  A()..('Fail');
}

class A {
  
  call(String s) {
    ...
  }
}
```

**Comment by lrhn** [comment]
Correct, you have to use `.call`. Same for `o?.call(...)`.

The latter has advantages over `o?(...)` in the it doesn't conflict with the conditional operator so easily.

There are no current plans to allow `(...)` after a `..` or `?.`. Definitely not after `?.`, and probably not after just one of them either.

**Comment by Solido** [comment]
It saddens me but they're reasons and these are the specs.
Thanks!
