### ISSUE TITLE
Failures on Make async error injection set stack trace on errors.

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#56585]
There are new test failures on [Make async error injection set stack trace on errors.](https://github.com/dart-lang/sdk/commit/310d91aee82890fd065768b21bce952ca33ea745).

The tests
```
vm/dart/isolates/concurrency_stress_sanity_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-appjit-linux-release-x64
vm-linux-release-x64
```

Log: https://dart-ci.appspot.com/log/vm-linux-release-x64/vm-linux-release-x64/3737/vm/dart/isolates/concurrency_stress_sanity_test

Looks like some of the tests that were deleted are still referenced here.

**Comment by dcharkes** [comment]
https://dart-review.googlesource.com/c/sdk/+/382561
