### ISSUE TITLE
Macro API to identify super/this parameters in constructors

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#56593]
For macros that want to generate fields for parameters of a constructor it would be useful if the macro could differentiate between super parameters and this parameters ("initializing formal parameter") since the macro shouldn't be generating extra fields for those.

Example:

From the following user-written code...

```dart
@GenerateFields()
class Foo extends Bar {
  const Foo({
    super.arg1,
    this.arg2,
    required int arg3,
  });

  final int arg2;
}
```

... the `@GenerateFields()` macro should be able to generate the following augmentation:

```dart
augment class Foo {
  augment const Foo({
    super.arg1,
    this.arg2,
    required int arg3,
  }) : arg3 = arg3;

  final int arg3;
}
```

This would require some kind of macro API to identify which parameters of the constructor are super/this parameters and which aren't.

**Comment by jakemac53** [comment]
@davidmorgan I plan on going ahead and adding this to the existing API in order to unblock flutter, and the work should be fairly minimal. We will want to make sure it ends up in the new APIs as well.

**Comment by davidmorgan** [comment]
@jakemac53 SGTM, thanks.
