### ISSUE TITLE
un-expected type-error with null-safety

### ISSUE THREAD

**Issue by aditya-ekam** [dart-lang/sdk#56599]
hi ,

the following code should compile ,but it does not

```class c {}

void f<t extends c>(
  final t v,
) {
  print(v);
}

void f_1<t extends c?>(
  final t v,
) {
  if (v == null) {
    return;
  }

  f(v);
}

void main() {
  c? v = c();
  f_1(v);
}
```
(`c` can be replaced with `Object` ,but the result is same ,compile error)

compile error :
```
compileDDC
main.dart:16:3: Error: Inferred type argument 't' doesn't conform to the bound 'c' of the type variable 't' on 'f'.
 - 'c' is from 'package:dartpad_sample/main.dart' ('/tmp/dartpadOUUSQP/lib/main.dart').
Try specifying type arguments explicitly so that they conform to the bounds.
  f(v);
  ^
main.dart:3:8: Context: This is the type variable whose bound isn't conformed to.
void f<t extends c>(
```

thanks

**Comment by eernstg** [comment]
This is working as intended. We don't have a way to denote the non-nullable type corresponding to a type variable like `T extends C?`, so there's no way to infer an actual type argument for the invocation of `f_1` that makes it type safe.

**Comment by aditya-ekam** [comment]
do we have a solution ,thanks

**Comment by eernstg** [comment]
Right, you can cast like `f(v as C)` in the body of `f_1`, but that isn't quite good enough in some cases:

```dart
List<T> f<T extends C>(
  final T v,
) {
  return [v];
}

List<T> f_1<T extends C?>(
  final T v,
) {
  if (v == null) {
    return [];
  }

  return f(v as C); // Error.
}
```

The problem is that `v as C` forgets everything about `T` except the upper bound, so we won't be able to create a `List<C2>` where `C2` is some subtype of `C` that you have passed as the actual type argument to `f_1`.

It _will_ work if you use the declaration `T extends C` and the parameter type `T?`:

```dart
List<T> f<T extends C>(
  final T v,
) {
  return [v];
}

List<T> f_1<T extends C>(
  final T? v,
) {
  if (v == null) {
    return [];
  }

  return f(v); // OK
}
```

**Comment by aditya-ekam** [comment]
> `T extends C` and the parameter type `T?`

won't "T extends C and the parameter type T?" loose type-safety ,because the param. will always be shown as null to the type-system ,irrespective of the generic type ?

is this issue because of sub-typing ?

thanks

**Comment by eernstg** [comment]
It is true that the formal parameter will always have a nullable type when it is declared as `T?`, no matter how you declare the type variable `T` in the first place. In that sense you do remove the ability to require that the actual argument to `f_1` is non-null. However, the body of `f_1` immediately tests whether the argument is null, which means that you would turn this test into dead code for the case where the type of `v` is non-nullable, so perhaps the ability to make this type non-nullable isn't that relevant for `f_1` as written? Perhaps `f_1` wouldn't be able to do anything that it can't already do if you were to find a way to make that parameter type non-nullable in some cases?

You could also argue that `f_1` yields a _stronger_ typing than it would have done if the type variable `T` had been able to have a value which is a potentially nullable type: It returns a `List<T>`, which is now known to be a subtype of `List<Object>` (and a subtype of `List<C>`, but `List<Object>` is enough to make the point), and this means that we don't have to worry about elements in the list whose value is null.

If you insist then you can still perform the invocation of `f` from `f_1` when it is justified by the actual type argument, but this approach goes a step further than the static analysis (that is, the type checker doesn't know that it is safe):

```dart
class C {}

List<T> f<T extends C>(
  final T v,
) {
  return [v];
}

List<T> f_1<T extends C?>(
  final T v,
) {
  if (v == null) {
    return [];
  }

  if (<T>[] is List<C>) {
    // `T <: C`, even though the type checker doesn't know.
    return (f as Function)<T>(v);
  } else {
    // `T <: C?` but not `T <: C`, so `T` is a nullable type.
    return <T>[v, null as T]; // OK
  }
}

class C2 extends C {}

void main() {
  C2? v = C2() as dynamic; // Cast to prevent promotion.
  print(f_1(v).runtimeType); // 'List<C2?>'.
}
```

The crucial step is that we're testing dynamically whether the given actual argument for `T` is a subtype of `C`, which can be done via a generic type like `List`. When we know for sure that `T <: C` then we can also pass `T` as the actual type argument to `f` in the body of `f_1`, using `(f as Function)<T>(...)` to turn the static type checker off for that particular function invocation.

So you can do it, but I doubt that it will be a great idea. ;-)
