### ISSUE TITLE
[analyzer] broken import suggestions for package:collection

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#56590]
Hi, not sure if this is limited to the `collection` package, but that's the one I have a stable reproduce for.

1. install the package
2. create `a.dart` that imports `import 'package:collection/collection.dart';`
3. create `b.dart` with 
```dart
void fn() {
  [].mapIn // <-- continue typing "mapIndexed" here
}
```
**expected:** code completion suggests `package:collection/collection.dart` and there is only one entry for `mapIndexed`.

**result:** 
<img width="563" alt="Screenshot 2024-08-28 at 16 55 07" src="https://github.com/user-attachments/assets/78273d1f-af57-4440-b981-69cc9e68510b">

None of those files re-exports `collection` and applying any code completion suggestion does not work.

Dart SDK version: 3.5.1 (stable) (Tue Aug 13 21:02:17 2024 +0000) on "macos_arm64"

**Comment by incendial** [comment]
@DanTup fyi, not sure if this only happens in VS Code

**Comment by DanTup** [comment]
There's an existing issue for this at https://github.com/dart-lang/sdk/issues/56320 (which by coincidence, I was just looking at earlier because I saw it numerous times this morning!).
