### ISSUE TITLE
[`async*`]: when using `await for` with an infinite `Stream`, `finally` block is not called when cancelling `StreamSubsription`

### ISSUE THREAD

**Issue by hoc081098** [dart-lang/sdk#56619]
This tracker is for issues related to:

* Dart core libraries (`dart:async`)
* Dart native and web compilers
* Dart VM

In your issue, please include:

* Dart version and tooling diagnostic info (`dart info`)
Dart 3.5.1

* Whether you are using Windows, macOS, or Linux (if applicable)
https://dartpad.dev/

## Details

When using `await for` with an infinite `Stream`, and `yield` inside loop, the `finally` block is not called when we cancel `StreamSubsription` (or `take(1)` for the same purpose):

### With RxDart 

```dart
import 'dart:async';

import 'package:rxdart/rxdart.dart';

void main() async {
  late StreamSubscription<void> sub;
  sub = getStream().listen((v) {
    print('Cancelling...');
    sub.cancel().then((_) => print('Cancelled...'));
  });
  
  await Future<void>.delayed(const Duration(seconds: 1));
  print('---');
  
  getStream().take(1).forEach(print);
}

Stream<String> getStream() async* {
  final s = Stream.value("Hello").concatWith([Rx.never()]);
  // or:  final s = BehaviorSubject.seeded('Hello');
  try {
    await for (final innerValue in s) {
      yield innerValue;
    }
  } finally {
    print('Done');
  }
}
```

### Without RxDart

```dart
import 'dart:async';

void main() async {
  late StreamSubscription<void> sub;
  sub = getStream().listen((v) {
    print('Cancelling...');
    sub.cancel().then((_) => print('Cancelled...'));
  });
  
  await Future<void>.delayed(const Duration(seconds: 1));
  print('---');
  
  getStream().take(1).forEach(print);
}

Stream<String> getStream() async* {
  final controller = StreamController<String>();
  controller.onListen = () {
    controller.add('Hello');
  };
  
  try {
    await for (final innerValue in controller.stream) {
      yield innerValue;
    }
  } finally {
    print('Done');
  }
}
```

### Console

```
Cancelling...
---
Hello
```

### Note

When using `Stream.value('Hello');` (finite Stream), this issue does not occur.
```
Cancelling...
Done
Cancelled...
---
Hello
Done
```

https://github.com/dart-lang/sdk/issues/42717#issuecomment-2314741715 🙏

**Comment by lrhn** [comment]
Most likely cause it's that the implementation did not wait for the `yield` event to be _delivered_ before deciding whether to continue after the yield. 

The `yield` should make sure that the event has been delivered, so that the listener has a chance to synchronously cancel, or just pause, before continuing from the `yield`.

Tha, in turn, means that the function body code continues round the loop to the `await for`, where it blocks forever on a stream that never sends another event.

**Comment by lrhn** [comment]
Having checked, using this program:
```dart
```
both dart2js and the VM seem to behave correctly, so filing this against DDC.
(I don't know what dart2wasm does, and I'm not entirely sure how to easily find out, short of creating a test in the Dart repo. I believe such a test already exists, somewhere.)

**Comment by biggs0125** [comment]
This is fixed by the new async transformation recently added to DDC. To confirm, I tested the above examples at head and they work as expected. 

Closing this out as this fix should be in the next Dart release.
