### ISSUE TITLE
runtime types issues

### ISSUE THREAD

**Issue by 1999ali1999** [dart-lang/sdk#56618]
### Commit(s) to merge

unknown

### Target

unknown

### Prepared changelist for beta/stable

unknown

### Issue Description

"The runtime type always matches the static type": Almost always.. Due to type parameters being covariant by default.  this is the most annoying design choice it has.

### What is the fix

unknown

### Why cherry-pick

"The runtime type always matches the static type": Almost always.. Due to type parameters being covariant by default.  this is the most annoying design choice it has.

### Risk

unknown

### Issue link(s)

unknown

### Extra Info

Not found

**Comment by mraleph** [comment]
Please don't spam issue tracker with duplicate issues.
