### ISSUE TITLE
Function with bounded generic type in typedef doesn't compile since 3.2.0

### ISSUE THREAD

**Issue by 8symbols** [dart-lang/sdk#56633]
We are updating the Flutter version in our project and have encountered that the code we used in Dart 2.19.6 doesn't compile anymore in 3.3.4. It seems to have been broken in 3.2.0. Here is a simplified example that can be run in DartPad (3.5.1). The problem is also reproducible on latest (3.6.0-edge.fe88cdb5aa822d72788a1b5109cd08a922cf4ef7) main:
```dart
typedef Inner<Parent, Child extends Parent> = void Function();

typedef Outer<Parent> = void Function<Child extends Parent>(
  Inner<Parent, Child> foo,
);

void main() {}
```

Analyzer doesn't issue any warnings, but if you run the program, the following error appears:
```
main.dart:4:3: Error: Type argument 'Child' doesn't conform to the bound 'Parent' of the type variable 'Child' on 'Inner'.
Try changing type arguments so that they conform to the bounds.
  Inner<Parent, Child> foo,
  ^
main.dart:1:23: Context: This is the type variable whose bound isn't conformed to.
typedef Inner<Parent, Child extends Parent> = void Function();
                      ^
```
If you replace the typedefs with their contents, everything will work fine.

**Comment by eernstg** [comment]
This looks like a bug in the common front end. During the bounds check on the type `Inner<Parent, Child>`, it should be assumed that `Child` is a subtype of `Parent`, which would make that type regular bounded, hence OK.
