### ISSUE TITLE
`NativeFinalizer` and `Finalizer`: Should calling `detach` throw an error instead of be a no-op if nothing is detached?

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56632]
>> Trying to detach from a non-shared static nativeFinalizer would lead to a no-op 
>
> Wouldn't it throw a nice exception: "You cannot detach object `foo` from this finalizer as it was not attached" ?

_Originally posted by @mkustermann in https://github.com/dart-lang/sdk/issues/56227#issuecomment-2324609670_

Changing it now, would be a breaking change.

Also, it would mean that code racing with the GC to detach/run the finalizer if you only hold on to the detach key would start throwing if the finalizer is run first. Arguably, such code is likely broken.

I don't remember if we discussed this, and if we made it a no-op for a specific reason. (I don't see any discussion on https://dart-review.googlesource.com/c/sdk/+/238086.) Maybe @lrhn remembers.

cc @rakudrama @sigmundch for `Finalizer` on JS backend.

**Comment by mkustermann** [comment]
> Also, it would mean that code racing with the GC to detach/run the finalizer if you only hold on to the detach key would start throwing if the finalizer is run first. Arguably, such code is likely broken.

Ah, the finalizer `detach` API doesn't require the object that has a finalizer attached, so that makes this probably not possible.
