### ISSUE TITLE
VM does unnecessary pause after `yield` inside `await for`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#56640]
The VM's implementation of `yield` in an `async*` functtion seems to have an asynchronous gap after delivering the event.
This is visible inside an `await for` where that leads to the loop subscription being paused.

It seems the VM on loop like this:
```dart
Stream<int> foo(Stream<int> source) async* {
  await for (value in source) {
    print("before");
    yield value;
    print("after");
  }
}
```
where the execution is associated with a stream subscription *T*,
and the `await for` loop has a subscription *S*:

* Receives value from *S*
* Prints "before".
* Emits value synchronously on *T*
    * Data event handler runs and returns. It does not pause or cancel *T*.
* Schedules microtask for code after `yield`.
* Pauses *S*.
* Returns to event loop.

The the schedule microtask eventually runs and does:
* Prints "after"
* Loops back to `await for` loop.
* Resumes *S*.
* Returns to event loop.

The *pause and microtask* are not necessary.
An `await for` loop only needs to pause its source stream subscription if it contains an async gap.
This code does not *need* to contain an async gap when the *T* subscription is neither paused
nor cancelled after delivering the `yield` event. It *can* continue executing synchronously after the `yield`.

It's not *wrong* do dally after delivering an event. If the delivery may not be synchronous, the safe approach is to pause *before* delivering the event, but here I can see that the delay isn't necessary. There will be an asynchronous gap when control reaches back to the `await for` loop anyway.

**Comment by lrhn** [comment]
The yield is specified to deliver the event to the stream subscription listener (invoking its `onData` handle), and after doing that, to check if the subscription is paused or cancelled, and if so take appropriate scrub.
(It can also check before, but if the stream subscription is paused or cancelled, the effect will be the same.)

There is no requirement of an asynchronous gap, a return to the event loop, after a yield that manages to deliver the event synchronously, and where the subscription is not paused or cancelled afterwards. It doesn't have to pause, and it may continue synchronously.

(At least that's what I tried to ensure when writing it. And I think that version is in the language spec. I'll check.)

**Comment by alexmarkov** [comment]
I gave it a try: https://dart-review.googlesource.com/c/sdk/+/383381.
15 tests failed: https://dart-ci.firebaseapp.com/cl/383381/1

I looked at some of these tests and it seems like they actually expect the execution to be paused at `yield`. They currently pass on the VM as well as other Dart implementations (dart2js, dart2wasm etc.), so this behavior is not VM-specific and changing it would be breaking.

**Comment by lrhn** [comment]
And `async_star_await_for` is probably a test I wrote myself. Ouch.

I have no doubt that it would break a lot of internal tests too.

OK, not easy to just change, even if I want to, because it could improve performance.
(We really should have made sync timing less predictable to avoid people depending on implementation details. Might be too late now.)
