### ISSUE TITLE
[extension types] A switch over a sealed class with an `extension type` as its `type parameter` leaks the underlying type?

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#56652]
Consider:

```dart
void main() {
  final Foo<S> f = FooCase(S("abc"));

  switch (f) {
    case FooCase<String>(:final t):
      print(t);
  }
}

sealed class Foo<T> {}

final class FooCase<T> implements Foo<T> {
  final T t;

  const FooCase(this.t);
}

extension type S(String str) {}

```

This program compiles, but I expected it not to compile because I intuitively expected `case FooCase<String>(:final t):` to produce a static error because f is never a `FooCase<String>` (at least statically?).

I wanted to ask, is this expected behavior?

**Comment by eernstg** [comment]
> I wanted to ask, is this expected behavior?

Yes, exhaustiveness analysis uses the underlying representation type when it encounters an extension type, even when the extension type is an actual type argument. This matches the actual run-time semantics.

We could introduce some warnings when a compile-time only type is tested dynamically. After all, we _know_ that it's just going to be the representation type, so why not tell the developer to ask about the representation type in the first place?

However, you can use this to "dress up" an object with a set of extension type methods that may be convenient to have in the body of that switch case:

```dart
extension type E2(List<int> xs) implements List<int> {
  int get second => xs[1];
}

extension type E3(List<int> xs) implements E2 {
  int get third => xs[2];
}

void main() {
  var xs = [4, 5, 6];
  switch (xs) {
    case E3(length: 3):
      print('Tail sum: ${xs.second + xs.third}');
  }
}
```

**Comment by modulovalue** [comment]
Thank you, @eernstg , so this is indeed expected behavior and not a bug. From my side this issue could be closed.

> [...] If you're casting into an extension type then the object hasn't been vetted for that type, which may break some invariants. If you're casting out of an extension type then the object may be used in ways that the extension type was intended to prevent.

I think that sums up the observation that has lead me to file this and the other issue  (https://github.com/dart-lang/sdk/issues/56653) very nicely: it is possible to implicitly cast to and from an extension type by, for example, using switch statements.

The wrong assumption that I had was that I can only get values with a static type that was introduced by an extension type by either using a constructor from an extension type or a cast expression, but now I see that, for example, switch statements can also be used to do that.

---

> We could introduce some warnings when a compile-time only type is tested dynamically

> We could then lint the case where a plain extension type is obtained by a dynamic type check, e.g., via pattern matching. Conversely, an open extension type can freely be obtained by pattern matching or casts.

If that could help with catching accidental casts to/from an extension type, then that sounds very useful to me.
