### ISSUE TITLE
Missing addition of `break` in convert empty `if-case` to `switch statement`

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56682]
Following from https://github.com/dart-lang/sdk/issues/56371.

If we have the following switch:

```dart
switch (v) {
  case 5:
    break;
  case 6:
    0;
    break;
  default:
    1;
}
```

Turns into:

```dart
if (v case 5) {
} else if (v case 6) {
  0;
} else {
  1;
}
```

If we turn it back, it should add the `break` at the `case 5`, but it doesn't.

This is the current output:

```dart
switch (v) {
  case 5:      // Missing `break;`
  case 6:
    0;
  default:
    1;
}
```

**Comment by fshcheglov** [comment]
I can reproduce this problem and am currently working on a fix.

**Comment by fshcheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/384306
