### ISSUE TITLE
dart2js code should start passing a language version to dart_style

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#56686]
Greetings dart2js team friends!

The formatter is [moving to being language version aware](https://github.com/dart-lang/dart_style/issues/1402). This means that when it's parsing some code, it needs to be told what language version to parse it as. The `DartFormatter` constructor now takes [an optional parameter where you can pass in the language version](https://github.com/dart-lang/dart_style/blob/003cb15b8d27e4a72eb25dba6f695cd2c7a6f4fb/lib/src/dart_formatter.dart#L83). In a future version of dart_style, that parameter will become mandatory.

If you own code that uses dart_style as a library, you should update your code to pass in a language version. To migrate:

1. If this code is inside a package (as opposed to, say, the Dart core libraries), then update your constraint on dart_style to `^2.3.7`. That's the version where the new parameter was added.

2. If you know the precise language version the code should be parsed as, then pass in that version (as an instance of the [pub_semver package's `Version` class](https://pub.dev/documentation/pub_semver/latest/pub_semver/Version-class.html)). This is what "real" tools should do.

    For simple one-off scripts and other utilities where precise behavior doesn't matter much, you can pass in [`DartFormatter.latestLanguageVersion`](https://github.com/dart-lang/dart_style/blob/003cb15b8d27e4a72eb25dba6f695cd2c7a6f4fb/lib/src/dart_formatter.dart#L30) to unconditionally parse the code as the latest language version that the formatter itself supports.

When the `--tall-style` experiment flag ships, the passed in language version will also be used to determine whether you get the current formatting style or the [new "tall" style](https://github.com/dart-lang/dart_style/issues/1253).

I did a search through the SDK, and the constructor calls that I think are relevant are:

```
~/dev/dart/sdk/pkg/compiler/test/tool/graph_isomorphizer/graph_isomorphizer_test.dart:
   45:       DartFormatter().format(contents.toString()), expectations[filename]!);

~/dev/dart/sdk/pkg/compiler/tool/graph_isomorphizer.dart:
  461:     sink.write(DartFormatter().format(contents.toString()));

~/dev/dart/sdk/sdk/lib/_internal/js_dev_runtime/private/debugger.dart:
   43: var _devtoolsFormatter = JsonMLFormatter(DartFormatter());
  466:   DartFormatter()
```

Thank you!

**Comment by biggs0125** [comment]
Hey Bob, thanks for the detailed description! The two graph_isomorphizer files aren't heavily used and we don't necessarily care about the format of the code being emitted so I've added a change to have those specify `DartFormatter.latestLanguageVersion`.

`sdk/sdk/lib/_internal/js_dev_runtime/private/debugger.dart` is actually referencing a local class named `DartFormatter` so that one doesn't need updating.

**Comment by munificent** [comment]
Thanks!
