### ISSUE TITLE
Add HTTP error code to WebSocketException for failed HTTP upgrade requests

### ISSUE THREAD

**Issue by tguerin** [dart-lang/sdk#56694]
Currently, when opening a WebSocket connection and the HTTP upgrade request fails (e.g., receiving a status code other than `101 Switching Protocols`), the WebSocket connection fails with a generic error message like:

`Connection to '$uri' was not upgraded to websocket`

This error message provides no additional information about why the HTTP upgrade request failed, which can be problematic, especially when dealing with authenticated proxies or other scenarios where specific HTTP status codes like `401 Unauthorized` or `403 Forbidden` are returned.

### Proposal
It would be beneficial to extend the `WebSocketException` class to include an optional `httpErrorCode` or `httpStatusCode`  field, which would propagate the actual HTTP status code received during the upgrade request.

**Comment by brianquinlan** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/e4b505b3669b05a5a19e4e6e3ffc5b75764cf29b
