### ISSUE TITLE
Failures on [vm] Simplify implementation of native ports

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#56709]
There are new test failures on [[vm] Simplify implementation of native ports](https://github.com/dart-lang/sdk/commit/5a32d8bc7c5569efde3aec844b7f26d33e1bd86e).

The tests
```
ffi/regress_47594_test Timeout (expected Pass)
```
are failing on configurations
```
vm-appjit-linux-debug-x64
vm-appjit-linux-release-x64
```

**Comment by a-siva** [comment]
//cc @mraleph

**Comment by mraleph** [comment]
This has the same underlying issue as `DartIsolateTest.CanCreateServiceIsolate` failure on Flutter Engine unittests: service isolate does not correctly handle situation when its main errors.

This will be fixed by https://dart-review.googlesource.com/c/sdk/+/384482
