### ISSUE TITLE
`dart` seems to stop reporting errors after having reported several

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#56721]
With the following library, `dart` reports errors as expected until line 41. In particular, errors expected in lines 42 and up are not reported. However, those errors _are_ reported if earlier lines in the library are commented out.

The behavior is specific to `dart` and `dart run` (`dart compile js` and `dart compile exe` do report all the errors as expected).

```dart
import 'dart:async';

void f1() { return; }
dynamic f2() { return; }
Null f3() { return; }

int f4() { return; } // Error
Object? f5() { return; } // Error
FutureOr<Object>? f6() { return; } // Error
FutureOr<Object?> f7() { return; } // Error
FutureOr<void> f8() { return; } // Error

class A {
  factory A.f4() { return; } // Error
}

Future<void> g01() async { return; }
Future<dynamic> g02() async { return; }
Future<Null> g03() async { return; }

FutureOr<void> g04() async { return; }
FutureOr<dynamic> g05() async { return; }
FutureOr<Null> g06() async { return; }

Future<void>? g07() async { return; }
Future<dynamic>? g08() async { return; }
Future<Null>? g09() async { return; }

FutureOr<void>? g10() async { return; }
FutureOr<dynamic>? g11() async { return; }
FutureOr<Null>? g12() async { return; }

void g13() async { return; }
dynamic g14() async { return; }

dynamic? g16() async { return; }

Future<int> g17() async { return; } // Error
Future<Object?> g18() async { return; } // Error
Future<FutureOr<Object>?> g19() async { return; } // Error
Future<FutureOr<Object?>> g20() async { return; } // Error
Future<FutureOr<void>> g21() async { return; } // Error

FutureOr<int> g23() async { return; } // Error
FutureOr<Object?> g24() async { return; } // Error
FutureOr<FutureOr<Object>?> g25() async { return; } // Error
FutureOr<FutureOr<Object?>> g26() async { return; } // Error
FutureOr<FutureOr<void>> g27() async { return; } // Error

Future<int>? g29() async { return; } // Error
Future<Object?>? g30() async { return; } // Error
Future<FutureOr<Object>?>? g31() async { return; } // Error
Future<FutureOr<Object?>>? g32() async { return; } // Error
Future<FutureOr<void>>? g33() async { return; } // Error

FutureOr<int>? g35() async { return; } // Error
FutureOr<Object?>? g36() async { return; } // Error
FutureOr<FutureOr<Object>?>? g37() async { return; } // Error
FutureOr<FutureOr<Object?>>? g38() async { return; } // Error
FutureOr<FutureOr<void>>? g39() async { return; } // Error

void main() {}
```

Perhaps it's a missing flush on stderr?

I've added the labels 'area-vm' as well as 'area-front-end' because this seems to be clearly a CFE matter, but some element of `dart` and `dart run` makes a difference as well.

**Comment by johnniwinther** [comment]
The VM has a fixed limit on the number of emitted messages. It is an old limit for which I don't know the motivation.

@a-siva Do you know why we have this limit?

**Comment by a-siva** [comment]
> The VM has a fixed limit on the number of emitted messages. It is an old limit for which I don't know the motivation.
> 
> @a-siva Do you know why we have this limit?

I am not aware of the reason for this limit, will investigate and get back to you.

**Comment by a-siva** [comment]
The truncation seems to happen in the errorString method which limits itself to 10 errors in the list
```
class _CompilationError extends _CompilationFail {
  final Uint8List? bytes;
  final List<String> errors;

  _CompilationError(this.errors, this.bytes);

  @override
  Status get status => Status.error;

  @override
  String get errorString => errors.take(10).join('\n');

  String toString() => "_CompilationError(${errorString})";

  List toResponse() => [status.index, payload, bytes];
}
```
Looking through the log, it appears that this was added here https://codereview.chromium.org/2976543002, maybe @sigmundch has some context on the limitation.

**Comment by sigmundch** [comment]
It appears my change was only moving parts of the logic from one file to another, tracing it further:
* I moved it from fasta/vm.dart in b71bd543a98c903117045304d2175f02b5714c9a
* it was moved there from kernel-service.dart in c19b49ff2602ac50abc3e5bd365358dff2143521
* it was introduced by @mraleph in 43a0500e37c67184f8cc8abe5afa6ff1525837f3 when we first integrated the CFE with the VM in 2017

If I have to guess, this is not a limitation we need to keep. Most likely back then we had a widely evolving system and showing the first 10 errors was sufficient to iterate quickly without accidentally producing walls of error messages.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/385360
