### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by moluopro** [dart-lang/sdk#56734]
I followed the steps in the https://github.com/dart-lang/sdk/blob/main/docs/Building.md documentation and still encountered the following error. My guess is that the documentation is missing a description of one of the pre-steps.  
> When I manually compiled `gn` and placed it in the `sdk/buildtool` directory, I found that there was no such directory. There must be a missing step in the documentation that caused my `sdk/buildtool` directory to not be generated and tools like `gn` and `ninja` to be missing.

```bash
moluo@lubuntu0:~/work/dart-build$ gclient
Usage: gclient.py <command> [options]

Meta checkout dependency manager for Git.

Commands are:
  config       creates a .gclient file in the current directory
  diff         displays local diff for every dependencies
  fetch        fetches upstream commits for all modules
  flatten      flattens the solutions into a single DEPS file
  getdep       gets revision information and variable values from a DEPS file
  gitmodules   adds or updates Git Submodules based on the contents of the DEPS file
  grep         greps through git repos managed by gclient
  help         prints list of commands or help for a specific command
......(Omit some of the printed information)

moluo@lubuntu0:~/work/dart-build$ cd sdk

moluo@lubuntu0:~/work/dart-build/sdk$ ./tools/build.py --no-clang --mode release --arch riscv64 create_sdk
Traceback (most recent call last):
  File "/home/moluo/work/dart-build/sdk/./tools/build.py", line 325, in <module>
    sys.exit(Main())
             ^^^^^^
  File "/home/moluo/work/dart-build/sdk/./tools/build.py", line 301, in Main
    gn_py.RunGnOnConfiguredConfigurations(options, env)
  File "/home/moluo/work/dart-build/sdk/tools/gn.py", line 675, in RunGnOnConfiguredConfigurations
    BuildGnCommand(args, mode, arch, target_os, sanitizer,
  File "/home/moluo/work/dart-build/sdk/tools/gn.py", line 644, in BuildGnCommand
    raise Exception("Couldn't find the gn binary at path: " + gn)
Exception: Couldn't find the gn binary at path: /home/moluo/work/dart-build/sdk/buildtools/gn
```
  
My complete steps are as follows (Ubuntu24_LTS_x64):  
```bash
sudo apt install git python3 curl xz-utils

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH="$PATH:/home/moluo/work/dart-build/depot_tools"
export DEPOT_TOOLS_UPDATE=0

git clone https://github.com/dart-lang/sdk
cd sdk

./tools/build.py --no-clang --mode release --arch riscv64 create_sdk
```

**Comment by moluopro** [comment]
Sorry, I was careless and didn't see the note in the documentation. I should have used `fetch dart` to get the source code and the accompanying toolchain.
  
Documenting my compilation process here. I'm continuing to experiment at the moment: 
```bash
# set http proxy ( If you are using vpn )
export https_proxy=http://127.0.0.1:8001
export http_proxy=http://127.0.0.1:8001

# get depot_tools
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

export PATH="$PATH:$PWD/depot_tools"
export DEPOT_TOOLS_UPDATE=0

src_path="dart-sdk"
rm -rf $src_path

mkdir $src_path
cd $src_path
# get src & toolchain
fetch dart

# If you encounter a network error, you can retry this command multiple times
gclient sync
```

**Comment by moluopro** [comment]
Ignoring the flutter-related errors I just mentioned, I went ahead and compiled directly, and it still failed.   

The error message is as follows:  
```bash
moluo@lubuntu0:~/work/dart-build/dart-sdk$ cd sdk
moluo@lubuntu0:~/work/dart-build/dart-sdk/sdk$ ./tools/build.py --no-clang --mode release --arch riscv64 create_sdk
Done. Made 542 targets from 123 files in 330ms
buildtools/ninja/ninja -C out/ReleaseXRISCV64 create_sdk
ninja: Entering directory `out/ReleaseXRISCV64'
ninja: error: '../../.dart_tool/package_config.json', needed by 'vm_platform_strong_stripped.dill', missing and no known rule to make it
BUILD FAILED
```

**Comment by rmacnak-google** [comment]
You might try running `gclient runhooks`. This normally runs as part of `gclient sync` after all the downloads succeed, and among other things generates the missing `package_config.json`.

**Comment by kranurag7** [comment]
Hey @rmacnak-google I've a similar question w.r.t. build here. 

I'm using the following command here:
```bash
./tools/build.py --mode release --arch x64 create_sdk
```
the build is working fine and looks like everything is okay but there's a problem I'm running into when it comes to dependency resolution. 

<details><summary> failed logs </summary>
<p>

```bash
IO  : HTTP GET https://pub.dev/api/packages/shelf_web_socket
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: linux
    | X-Pub-Command: deps
    | X-Pub-Session-ID: 90429DE2-64E9-416E-8078-2DAF04034E53
    | user-agent: Dart pub 3.5.3
IO  : Attempt #5 for fetching versions for "shelf_packages_handler" from "https://pub.dev/api/packages/shelf_packages_handler"
IO  : Attempt #2 for fetching versions for "shelf_web_socket" from "https://pub.dev/api/packages/shelf_web_socket"
IO  : HTTP GET https://pub.dev/api/packages/lints
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: linux
    | X-Pub-Command: deps
    | X-Pub-Session-ID: 90429DE2-64E9-416E-8078-2DAF04034E53
    | X-Pub-Reason: dev
    | user-agent: Dart pub 3.5.3
IO  : HTTP GET https://pub.dev/api/packages/node_preamble
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: linux
    | X-Pub-Command: deps
    | X-Pub-Session-ID: 90429DE2-64E9-416E-8078-2DAF04034E53
    | user-agent: Dart pub 3.5.3
SLVR: Version solving took 0:00:29.013977 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (29.021s).
ERR : Got TLS error trying to find package test at https://pub.dev.
FINE: Exception type: WrappedException
FINE: package:pub/src/utils.dart 573:5                       fail
    | package:pub/src/source/hosted.dart 1692:7              HostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 499:7               HostedSource._fetchVersionsNoPrefetching
    | ===== asynchronous gap ===========================
```

</p>
</details> 

I'm not behind any corporate environment. I tried it on different machines and running into same problems. 

reading https://github.com/askeksa-google/sdk/blob/2178411b062685557c6ade2085b8ee747cedfb92/CHANGELOG.md?plain=1#L4248-L4256 

I verified and I've `/etc/ssl/certs/ca-certificates.crt` on my system. 

What seems to be working is the following command: 
```bash
 # dart --root-certs-file=/etc/ssl/certs/ca-certificates.crt pub deps
Resolving dependencies...
Downloading packages...
Got dependencies.
Dart SDK 3.5.3
cli 1.0.0
├── lints 4.0.0
└── test 1.25.8
    ├── analyzer 6.8.0
    │   ├── _fe_analyzer_shared 73.0.0
    │   │   └── meta...
    │   ├── convert 3.1.1
    │   │   └── typed_data...
# truncated output
```

I'm not sure if I missed something here during building docs but it would be great if I can get this working without passing in that flag. I also looking at the flags of `./tools/build.py --help` output but there was none to specify the cert file that needs to be used at runtime. Out of the box, it should be able to read `/etc/ssl/certs` directory and given cert is there, it should work but I don't know as of now if I missed something. I'll appreciate your guidance here.

**Comment by rmacnak-google** [comment]
There is no flag to build.py that would change the default locations to look for certificates.

Is the failing command something that is running during the build, or is it failing after when you try to use the SDK you just build? Does the same command also fail when you use the pre-built Dart SDK?

Does the command succeed if you use --bypass-trusting-system-roots (which forces the use of the compiled-in root certificates)?

What distribution of Linux are you using? Our default locations might be need to be updated.

**Comment by kranurag7** [comment]
> Is the failing command something that is running during the build, or is it failing after when you try to use the SDK you just build? 

The build is compiling good and it is only failing after I try the build. `./tools/build.py --mode release --arch x64 create_sdk` is working really good but when I try the SDK using the command `dart create -t console cli` it never succeeds because dependencies are not resolved.

> Does the same command also fail when you use the pre-built Dart SDK?

No when I extract dart from the official dart.dev sources then it doesn't. Also the dart official container works on the host too. 

> Does the command succeed if you use --bypass-trusting-system-roots (which forces the use of the compiled-in root certificates)?

Yes it does and `dart --root-certs-file=/etc/ssl/certs/ca-certificates.crt pub deps` command works too. 

> What distribution of Linux are you using?

I'm bootstrapping dart for wolfi here https://github.com/wolfi-dev/os/pull/29644 

>  Our default locations might be need to be updated.

I think as per changelog here https://github.com/askeksa-google/sdk/blob/2178411b062685557c6ade2085b8ee747cedfb92/CHANGELOG.md?plain=1#L4248-L4256 it looks into /etc/ssl/certs and inside that there is a ca-certificates.crt file for sure but even after that somehow dependencies are not getting resolved.
```bash
 $ docker run --rm cgr.dev/chainguard/wolfi-base:latest ls /etc/ssl/certs
ca-certificates.crt
```

To reproduce following steps can be followed: 
```bash
docker run --rm -it cgr.dev/chainguard/wolfi-base:latest 
# using your editor, append the following to `/etc/apk/repositories` 
# https://apk.cgr.dev/wolfi-presubmit/25a50ddf010a31b8e2e2c80ccd74e31b947ce7c0
apk add --allow-untrusted dart
dart create -t console cli
```

_Happy to share any more details if required._

**Comment by rmacnak-google** [comment]
On my Debian-based system, /etc/ssl/certs is full of .pem files with a bunch of hashed symlinks. On wolfi, /etc/ssl/certs only contains ca-certificates.crt, but the directory does exist, so the search root certificates concludes that it found a cert cache that happens to be empty. I think Dart should just search in more places.

**Comment by kranurag7** [comment]
that's exactly right. 

I look at the code here https://github.com/dart-lang/sdk/blob/4fe2944776a0f8b24a7b8a63f67c06b82a808070/runtime/bin/security_context_linux.cc#L60-L70 

Below is the strace output of running `strace -f dart pub deps` 
```bash
[pid    40] stat("/etc/ssl/certs/58f6ac30.0", 0x7eb96a2fcd08) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/902e8ac6.0", 0x7eb96a2fcd08) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/1001acf7.0", 0x7eb96a2fcd08) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/f013ecaf.0", 0x7eb96a2fcd08) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/5ad8a5d6.0", 0x7eb96a2fcd08) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/b0f3e76e.0", 0x7eb96a2fcd08) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/5ad8a5d6.0", 0x7eb96a2fcd08) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/b0f3e76e.0", 0x7eb96a2fcd08) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/6bd5b8ba.0", 0x7eb96a2fce58) = -1 ENOENT (No such file or directory)
[pid    40] stat("/etc/ssl/certs/fdadd2b5.0", 0x7eb96a2fce58) = -1 ENOENT (No such file or directory)
```

Looks like `dart` is only looking for those files only which doesn't exist in wolfi.

but sure enough I see that inside the `dart:stable` image. 

```bash
lrwxrwxrwx 1 root root     20 Sep 27 05:18  f51bb24c.0 -> Certigna_Root_CA.pem
lrwxrwxrwx 1 root root     20 Sep 27 05:18  fa5da96b.0 -> GLOBALTRUST_2020.pem
lrwxrwxrwx 1 root root     41 Sep 27 05:18  fc5a8f99.0 -> USERTrust_RSA_Certification_Authority.pem
lrwxrwxrwx 1 root root     20 Sep 27 05:18  fd64f3fc.0 -> TunTrust_Root_CA.pem
lrwxrwxrwx 1 root root     19 Sep 27 05:18  fe8a2cd8.0 -> SZAFIR_ROOT_CA2.pem
```

For now, the temporary fix for me is that I create a copy of `/etc/ssl/certs/ca-certificates.crt` at `/etc/pki/tls/certs/ca-bundle.crt` and that works because in dart, that is hardcoded in the code. 

I think the main reason here issue I'm looking here is that there is difference in `ca-certificates` package of wolfi and debian. Debian creates a lot of symlinks and that is what dart is looking at. It's not looking at each `*.crt` file in `/etc/ssl/certs` otherwise should have been resolved.
