### ISSUE TITLE
LateInitializationError when a late global variable is accessed in another isolate despite it has been initialized before spawning.

### ISSUE THREAD

**Issue by miklcct** [dart-lang/sdk#56751]
# Example code
```dart
import 'dart:isolate';

late int x;

void main() async {
  x = 0;
  print(await Isolate.run(() => x));
}
```

# Expected result
It prints `0`

# Actual result
The program crashes with `Field 'x' has not been initialized.`

**Comment by mraleph** [comment]
That's why isolates are called isolates. They are _isolated_ from each other and each isolate has its own static variables.

**Comment by miklcct** [comment]
> That's why isolates are called isolates. They are _isolated_ from each other and each isolate has its own static variables.

If x is a local variable, it is captured in the closure's state and copied into the isolate, so the program works as intended. How is it different with a top-level variable? Isn't a top-level <code>x</code> captured in the closure as well?
