### ISSUE TITLE
Pattern matching inside collection literal can cause crash in release builds

### ISSUE THREAD

**Issue by Yegair** [dart-lang/sdk#56756]
When using an `if(someValue case final Type typedValue)` guard within collection literals, there can be runtime errors that I think are caused by an incorrect compilation. They only happen in release builds (`dart compile exe`) and don't happen in development builds (`dart run`).

I encountered this issue with Dart `3.5.3`, but I did not test if it is present in other Dart versions also.

# Reproduction

```dart
import 'dart:math';

class RandomValue {
  final bool shouldReturnValue;

  const RandomValue(this.shouldReturnValue);

  String? get valueOrNull {
    return shouldReturnValue ? "${Random().nextInt(42)}" : null;
  }
}

void main() {
  final values = [
    RandomValue(true),
    RandomValue(true),
    RandomValue(false),
    RandomValue(true),
  ];

  final nonNullValues = [
    for (final value in values)
      if (value.valueOrNull case final String aString) aString,
  ];

  print(nonNullValues);
}
```

When running the code above with `dart run`, it will correctly print out 3 random values, such as `[10, 32, 29]`.

However, when compiling it to an executable and then running it, it will throw an error like

```
Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0 ...
```

And the stack-trace pointing to the line with the statement

```dart
  print(nonNullValues);
```

---

I assume the line

```dart
      if (value.valueOrNull case final String aString) aString,
```

somehow gets erased by the compiler, which then causes the `null` value to end up in the `nonNullValues` list.

Also some observations I have made:
- changing `String? get valueOrNull` to `int? get valueOrNull` and then pattern matching on `... case final int ...` does not seem to cause the same problem
- changing
   ```dart
   String? get valueOrNull {
    return shouldReturnValue ? "${Random().nextInt(42)}" : null;
  }
   ```
   to
   ```dart
   String? get valueOrNull {
    return null;
  }
   ```
   also causes the error to vanish

**Comment by alexmarkov** [comment]
`Canonicalize` pass converted
```
B27[join]:28 pred(B25, B26) { 
      v62 <- phi(v66, v0 T{Null?}) alive T{String?}
}   
    v21 <- LoadClassId(v62) int64 
    v19 <- TestRange(v21 in [94-95]) T{bool}
    Branch if StrictCompare:50(===, v19, v4) goto (5, 6)
```
to
```
B27[join]:28 pred(B25, B26) {
      v62 <- phi(v66, v0 T{Null?}) alive T{String?}
}
    Branch if StrictCompare:50(===, v4 T{bool}, v4) goto (5, 6)
```
