### ISSUE TITLE
Auto complete shows too many suggestions on types that have custom extension methods/properties

### ISSUE THREAD

**Issue by ManuelRauber** [dart-lang/sdk#56760]
## **Steps to reproduce**

1. Open [the project](https://github.com/manuelrauber/code-completion-bug) using Android Studio.
2. Open `lib/package-c/example-c.dart`.
3. Within the method just start typing `c.hasContent` and observe the auto complete suggestions:
![image](https://github.com/user-attachments/assets/1c7dacf6-a9ff-4057-b9ed-c8033a1425ba)

The auto complete shows too many completion suggestions.
There should only be the last one.
The other two suggestions are just files _importing_ the extensions as well, but not (re-) exporting them.
If you create more files importing the extensions the more suggestions you will get.

### **Expected result:**
I expect only to see the correct import of the file that also exports the extensions.

### **Actual result**:
I see suggestions of files that only import the extensions for their own usage.

### **Additional information**

[Here](https://github.com/manuelrauber/code-completion-bug) is a GitHub Repo with an example to test yourself.

## Used versions

* Android Studio Koala Feature Drop | 2024.1.2 Patch 1 (Build #AI-241.19072.14.2412.12360217)
* Dart: 3.5.2
* Dart Plugin Version: 241.18968.26

**Comment by FMorschel** [comment]
I have a feeling this is the same as https://github.com/dart-lang/sdk/issues/56320. Please take a look.

**Comment by ManuelRauber** [comment]
@FMorschel Oh, you're right! It was my fault; I was only searching for open issues, so I did not see a report or a fix that would ship soon. Thanks for pointing that out! :)
