### ISSUE TITLE
dart2js crashes in pkg:kernel

### ISSUE THREAD

**Issue by SwederSchellens** [dart-lang/sdk#56773]
cmd.exe /c rebuild.bat

G:\Imagine\Imaginator>call clean.bat 

G:\Imagine\Imaginator>echo Cleaning... 
Cleaning...

G:\Imagine\Imaginator>call flutter clean web 
Deleting build...                                                    9ms
Deleting .dart_tool...                                               6ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Cleaning... Done
Building...
Resolving dependencies...
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  http_parser 4.0.2 (4.1.0 available)
  image_picker 0.8.9 (1.1.2 available)
  image_picker_for_web 2.2.0 (3.0.5 available)
  leak_tracker 10.0.5 (10.0.7 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.2 (0.7.3 available)
Got dependencies!
10 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Compiling lib\main.dart for the Web...                          
Compiling lib\main.dart for the Web...                             12.5s
Target dart2js failed: ProcessException: Process exited abnormally with exit code 253:
.dart_tool/flutter_build/de6c63646dd75acc6a6cb39905a9acb2/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system, Windows 10, see attachment
![Screenshot 2024-09-24 085152](https://github.com/user-attachments/assets/89b71660-1605-4158-b71f-516d6ec693b5)

* the Dart SDK build number (3.5.1), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: RangeError (length): Invalid value: Not in inclusive range 0..3: 241
#0      _Array.[] (dart:core-patch/array.dart)
#1      BinaryBuilder._readSimpleInterfaceType (package:kernel/binary/ast_from_binary.dart:3908:27)
#2      BinaryBuilder.readDartType (package:kernel/binary/ast_from_binary.dart:3806:16)
#3      BinaryBuilder.readDartTypeList.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:3774:55)
#4      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#5      new List.generate (dart:core-patch/array_patch.dart:46:13)
#6      BinaryBuilder.readDartTypeList (package:kernel/binary/ast_from_binary.dart:3774:16)
#7      BinaryBuilder._readSimpleFunctionType (package:kernel/binary/ast_from_binary.dart:3949:33)
#8      BinaryBuilder.readDartType (package:kernel/binary/ast_from_binary.dart:3810:16)
#9      BinaryBuilder._readInstanceInvocation (package:kernel/binary/ast_from_binary.dart:2528:23)
#10     BinaryBuilder.readExpression (package:kernel/binary/ast_from_binary.dart:2173:16)
#11     BinaryBuilder._readExpressionStatement (package:kernel/binary/ast_from_binary.dart:3528:36)
#12     BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:3468:16)
#13     BinaryBuilder.readStatementListAlwaysGrowable.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:3442:56)
#14     new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#15     BinaryBuilder.readStatementListAlwaysGrowable (package:kernel/binary/ast_from_binary.dart:3442:16)
#16     BinaryBuilder._readBlock (package:kernel/binary/ast_from_binary.dart:3721:28)
#17     BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:3472:16)
#18     BinaryBuilder.readStatementOrNullIfEmpty (package:kernel/binary/ast_from_binary.dart:3447:22)
#19     BinaryBuilder._readIfStatement (package:kernel/binary/ast_from_binary.dart:3637:44)
#20     BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:3484:16)
#21     BinaryBuilder.readStatementListAlwaysGrowable.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:3442:56)
#22     new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#23     BinaryBuilder.readStatementListAlwaysGrowable (package:kernel/binary/ast_from_binary.dart:3442:16)
#24     BinaryBuilder._readBlock (package:kernel/binary/ast_from_binary.dart:3721:28)
#25     BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:3472:16)
#26     BinaryBuilder.readStatementOption (package:kernel/binary/ast_from_binary.dart:3456:38)
#27     BinaryBuilder._setLazyLoadFunction.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:2088:21)
#28     FunctionNode._buildLazy (package:kernel/ast.dart:3741:23)
#29     FunctionNode.body (package:kernel/ast.dart:3746:5)
#30     FunctionNode.transformChildren (package:kernel/ast.dart:3904:9)
#31     Transformer.defaultTreeNode (package:kernel/visitor.dart:1805:10)
#32     TreeVisitorDefaultMixin.visitFunctionNode (package:kernel/visitor.dart:577:45)
#33     FunctionNode.accept (package:kernel/ast.dart:3872:38)
#34     Transformer.transform (package:kernel/visitor.dart:1771:17)
#35     Procedure.transformChildren (package:kernel/ast.dart:3247:18)
#36     Transformer.defaultTreeNode (package:kernel/visitor.dart:1805:10)
#37     TreeVisitorDefault.defaultMember (package:kernel/visitor.dart:626:35)
#38     MemberVisitorDefaultMixin.visitProcedure (package:kernel/visitor.dart:411:39)
#39     StaticInteropClassEraser.visitProcedure (package:_js_interop_checks/src/transformations/static_interop_class_eraser.dart:179:18)
#40     Procedure.accept (package:kernel/ast.dart:3228:40)
#41     Transformer.transform (package:kernel/visitor.dart:1771:17)
#42     Transformer.transformList (package:kernel/visitor.dart:1788:18)
#43     Class.transformChildren (package:kernel/ast.dart:1525:7)
#44     Transformer.defaultTreeNode (package:kernel/visitor.dart:1805:10)
#45     TreeVisitorDefaultMixin.visitClass (package:kernel/visitor.dart:556:31)
#46     Class.accept (package:kernel/ast.dart:1471:38)
#47     Transformer.transform (package:kernel/visitor.dart:1771:17)
#48     Transformer.transformList (package:kernel/visitor.dart:1788:18)
#49     Library.transformChildren (package:kernel/ast.dart:609:7)
#50     Transformer.defaultTreeNode (package:kernel/visitor.dart:1805:10)
#51     TreeVisitorDefaultMixin.visitLibrary (package:kernel/visitor.dart:565:35)
#52     StaticInteropClassEraser.visitLibrary (package:_js_interop_checks/src/transformations/static_interop_class_eraser.dart:119:18)
#53     Library.accept (package:kernel/ast.dart:585:38)
#54     Transformer.transform (package:kernel/visitor.dart:1771:17)
#55     Transformer.transformList (package:kernel/visitor.dart:1788:18)
#56     Component.transformChildren (package:kernel/ast.dart:14644:7)
#57     Transformer.defaultTreeNode (package:kernel/visitor.dart:1805:10)
#58     TreeVisitorDefaultMixin.visitComponent (package:kernel/visitor.dart:600:39)
#59     _doTransformsOnKernelLoad (package:compiler/src/phase/load_kernel.dart:172:41)
#60     _loadFromSource (package:compiler/src/phase/load_kernel.dart:328:5)
<asynchronous suspension>
#61     run (package:compiler/src/phase/load_kernel.dart:412:36)
<asynchronous suspension>
#62     Compiler.loadKernel (package:compiler/src/compiler.dart:392:9)
<asynchronous suspension>
#63     Compiler.produceKernel (package:compiler/src/compiler.dart:399:36)
<asynchronous suspension>
#64     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:633:20)
<asynchronous suspension>
#65     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:316:7)
<asynchronous suspension>
#66     Compiler.runInternal (package:compiler/src/compiler.dart:315:5)
<asynchronous suspension>
#67     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:236:11)
<asynchronous suspension>
#68     compile.<anonymous closure> (package:compiler/compiler_api.dart:256:30)
<asynchronous suspension>
#69     compile.compilationDone (package:compiler/src/dart2js.dart:723:3)
<asynchronous suspension>
#70     main (package:compiler/src/dart2js.dart:1226:3)
<asynchronous suspension>
  Command: G:\flutter_windows_3.24.0-stable\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev G:\flutter_windows_3.24.0-stable\flutter\bin\cache\dart-sdk\bin\snapshots\dart2js.dart.snapshot --platform-binaries=G:\flutter_windows_3.24.0-stable\flutter\bin\cache\flutter_web_sdk\kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/c9b9d5780da342eb3f0f5e439a7db06f7d112575/ --native-null-assertions --no-source-maps -o G:\Imagine\Imaginator\.dart_tool\flutter_build\de6c63646dd75acc6a6cb39905a9acb2\app.dill --packages=.dart_tool/package_config.json --cfe-only G:\Imagine\Imaginator\.dart_tool\flutter_build\de6c63646dd75acc6a6cb39905a9acb2\main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:370:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:203:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Error: Failed to compile application for the Web.
Building... Done

Process finished with exit code 1

**Comment by jensjoha** [comment]
With what it's seemingly trying to do (and - at least if I'm reading it right - this being a just cleaned working directory) my first guess would be file corruption.

What does your `G:\flutter_windows_3.24.0-stable\flutter\bin\cache\flutter_web_sdk\kernel` directory look like?

Does this happen every time?

**Comment by SwederSchellens** [comment]
Hi, thanks for getting back to me about this.

I think you are right with your  suggestion.
It happened out of nowhere, I was working on dockerizing my stuff.
After rebooting my PC, problem was solved.

Could you close the ticket for me?

Kind regards,

Sweder Schellens

**Comment by julemand101** [comment]
> Could you close the ticket for me?

If you go to your issue on: https://github.com/dart-lang/sdk/issues/56773

You can close it yourself under the comment input field.
