### ISSUE TITLE
[gardening] vm/cc/IsolateReload_LibraryLookup is flaky on simarm

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56785]
The tests
```
vm/cc/IsolateReload_LibraryLookup Fail (expected Pass)
```
are failing on configurations
```
vm-linux-release-simarm
```

```
--- Command "run_vm_unittest" (took 07.000469s):
DART_CONFIGURATION=ReleaseSIMARM out/ReleaseSIMARM/run_vm_tests --dfe=/b/s/w/ir/out/ReleaseSIMARM/gen/kernel_service.dill --suppress-core-dump --sound-null-safety --ignore-unrecognized-flags IsolateReload_LibraryLookup

exit code:
255

stdout:
Running test: IsolateReload_LibraryLookup
Done: IsolateReload_LibraryLookup

stderr:
RELOAD REPORT:
{"type":"ReloadReport","success":true,"details":{"finalLibraryCount":22,"receivedLibraryCount":0,"receivedLibrariesBytes":0,"receivedClassesCount":0,"receivedProceduresCount":0,"savedLibraryCount":20,"loadedLibraryCount":2,"shapeChangeMappings":[]}}
RELOAD REPORT:
{"type":"ReloadReport","success":true,"details":{"finalLibraryCount":22,"receivedLibraryCount":0,"receivedLibrariesBytes":0,"receivedClassesCount":0,"receivedProceduresCount":0,"savedLibraryCount":21,"loadedLibraryCount":1,"shapeChangeMappings":[]}}
../../runtime/vm/isolate_reload_test.cc: 1119: error: expected: Dart_IsError(result)

--- Re-run this test:
python3 tools/test.py -n vm-linux-release-simarm vm/cc/IsolateReload_LibraryLookup
```

It moved from failing to flaky to now failing again. I don't see any approvals on the previous failures.

https://dart-ci.web.app/#showLatestFailures=false&test=vm/cc/IsolateReload_LibraryLookup&configurations=vm-linux-release-simarm

It's flaking & failing on multiple configurations:

https://dart-ci.web.app/#showLatestFailures=false&test=vm/cc/IsolateReload_LibraryLookup

Related issue with different error message on different config:

* https://github.com/dart-lang/sdk/issues/43056

cc @a-siva that issue has been open for a while, who is the best person to look into isolate reload?

**Comment by a-siva** [comment]
//cc @rmacnak-google

**Comment by rmacnak-google** [comment]
It looks like it stopped being flaky. The flaky crash had the same stack as https://github.com/dart-lang/sdk/issues/56744, which was recently fixed.
