### ISSUE TITLE
[CP] [build] Update docker source for debian image

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#56795]
### Commit(s) to merge

3b36b20d6b92d881b7c59cd47a7e4e61ce1dbee8

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/387220

### Issue Description

This is a release blocker, we can't build debian packages without picking this infra change.

### What is the fix

A deprecated docker URL changed and needed to be updated.

### Why cherry-pick

This is a release blocker, we can't build debian packages without picking this infra change.

### Risk

Low

### Issue link(s)

N/A

**Comment by athomas** [comment]
LGTM, obviously :)

**Comment by itsjustkevin** [comment]
LGTM, please merge
