### ISSUE TITLE
[DAP] Use Service ID zones where beneficial

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#56794]
The APIs for managing Service ID zones have been released in [`package:vm_service 14.3.0`](https://pub.dev/packages/vm_service/versions/14.3.0). These APIs can be used to free object IDs when they are no longer needed, to ensure that objects associated with those IDs are not retained for longer than necessary.

**Comment by a-siva** [comment]
@DanTup now that this functionality has landed in vm service what is the possibility of wiring this up in DAP

**Comment by DanTup** [comment]
I'm hoping to look at this soon, I think it should be fairly straight-forward. The DAP spec says that `variableReference`s (which roughly map to the `InstanceRef`s we get from the VM) expire when execution resumes, so it should be fairly simple to manage the zone lifetimes around that.

**Comment by DanTup** [comment]
I've a change in progress for this, but I want to do some additional manual testing with Dart+Flutter. I have a slight concern about race conditions (eg. we decide to invalidate a zone, but at the same time we start processing some event like a debugger pause where we might evaluate breakpoint conditions) and the tests don't tend to generate the same level of traffic as a real app.

(If someone is able to trigger the trybots in the meantime though, that would be appreciated!)
