### ISSUE TITLE
_TypeError when adding to a typed list

### ISSUE THREAD

**Issue by Tomeye** [dart-lang/sdk#56790]
Reproduced with Dart Version 3.5.3.
Minimal Code to reproduce:

```dart
void main() {
  final List<Object> test = [42].map((e) => "test").toList();
  test.add(42);
}
```

Exception:
> DartPad caught unhandled _TypeError:
> TypeError: 42: type 'int' is not a subtype of type 'String'

**Comment by mraleph** [comment]
This is working as expected because the map produces `Iterable<String>` which becomes `List<String>`. The context type does not influence this.

There is an effort to address this, see https://github.com/dart-lang/language/issues/3527
