### ISSUE TITLE
[vm/ffi] Introduce a `Pointer<T extends Struct>.refWithFinalizer(finalizer, token)`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56796]
It's quite common to want to return a struct from Dart code using `dart:ffi` and having a call with the pointer inside that code (https://github.com/dart-lang/native/issues/1601, https://github.com/dart-lang/native/issues/1480#issuecomment-2348112178).

That currently requires the following dance:

1. `calloc` a `Pointer<MyStruct>`
2. `cast` the struct to `<Uint8>`
3. call `asTypedList` with `calloc.nativeFree` as finalizer
4. call `Struct.create<MyStruct>` with the typed data

Maybe we could simplify step 2 to 4 by introducing:

```dart
/// Extension on [Pointer] specialized for the type argument [Struct].
@Since('2.12')
extension StructPointer<T extends Struct> on Pointer<T> {
  /// A Dart view of the struct referenced by this pointer.
  ///
  /// Attaches [finalizer] to the backing store of the struct.
  /// The pointer (`this`) must _not_ be used anymore if the struct is _not_ guaranteed to be kept alive.
  /// Prefer doing any native calls with the pointer _before_ calling `refWithFinalizer`.
  ///
  /// Reading [ref] creates a reference accessing the fields of this struct
  /// backed by native memory at [address].
  /// The [address] must be aligned according to the struct alignment rules of
  /// the platform.
  ///
  /// Assigning to [ref] copies contents of the struct into the native memory
  /// starting at [address].
  ///
  /// This extension method must be invoked on a receiver of type `Pointer<T>`
  /// where `T` is a compile-time constant type.
  external T refWithFinalizer(Pointer<NativeFinalizerFunction>? finalizer, @Since('3.1') Pointer<Void>? token);
```

**Comment by codesculpture** [comment]
Hey @dcharkes , what's `Pointer<Void> token` for ?

**Comment by dcharkes** [comment]
See https://api.flutter.dev/flutter/dart-ffi/NativeFinalizer/attach.html documentation.

**Comment by codesculpture** [comment]
@dcharkes i am not fully understand this requirement, i understood the problem (from the comments), so can you provide a example snippet of solving the (calloc  the struct) problem with the `refWithFinalizer` method

**Comment by dcharkes** [comment]
```dart
  final pointer = malloc<MyStruct>();
  final myStruct = pointer.refWithFinalizer(malloc.nativeFree);
```

**Comment by codesculpture** [comment]
One doubt, why this being marked as `external`, the actual implementation needs to be written here right ? @dcharkes , btw thanks for the snippet.

**Comment by codesculpture** [comment]
@dcharkes i was almost done implementing this, one small doubt (might be a correction),
The signature you refer,

```
external T refWithFinalizer(Pointer<NativeFinalizerFunction>? finalizer, @Since('3.1') Pointer<Void>? token);
```

where the params should be named params right ? Since that is how it is for `asTypedList` (and also that is how this benefit "optional" params (i.e without sending `null` explicitly)).

**Comment by codesculpture** [comment]
@dcharkes Also am facing an issue, am doing this addition
```dart
--- a/pkg/vm/lib/modular/transformations/ffi/common.dart
+++ b/pkg/vm/lib/modular/transformations/ffi/common.dart
@@ -197,6 +197,9 @@ class FfiTransformer extends Transformer {
   final Procedure nativeEffectMethod;
+  final Procedure asUint8TypedList;
@@ -450,6 +453,11 @@ class FfiTransformer extends Transformer {
         allocatorAllocateMethod =
             index.getProcedure('dart:ffi', 'Allocator', 'allocate'),
         castMethod = index.getProcedure('dart:ffi', 'Pointer', 'cast'),
+        asUint8TypedList =
+            index.getProcedure('dart:ffi', 'Uint8Pointer', 'asTypedList'),
```

But while debugging using this config in vscode
```json
    {
      "name": "dart_gen_kernel.dart",
      "type": "dart",
      "request": "launch",
      "program": "pkg/vm/bin/gen_kernel.dart",
      "args": [
        "--platform=${workspaceFolder}/out/ReleaseX64/vm_platform_strong.dill",
        "new_test.dart"
      ],
      "toolArgs": [],
      "enableAsserts": true,
      "cwd": "${workspaceFolder}"
    },
``` am not getting any errors, whereas if i once build and then run the new builded dart binary, am getting this error
`Lookup failed: Uint8Pointer|asTypedList in @methods in dart:ffi`
But it is clearly there, isn't it ? 
Am i missing something to get `asTypedList` from 'Uint8Pointer' ( i did similar to how procedures of `StructPointer` and `UnionPointer` were retrieved )

Btw, to build i tried
`python3 tools/build.py -mrelease -ax64 create_sdk runtime create_platform_sdk`

**Comment by dcharkes** [comment]
Hi! It seems we had two people working on this in parallel. We've already got a working solution in https://dart-review.googlesource.com/c/sdk/+/399600. I completely missed this, sorry for the duplicate work! 🙊 

One thing you could try is completely remoing `out/ReleaseX64/` it might be that something is out of date in the build. Just looking that the commands it looks like you are doing the right thing.

**Comment by halildurmus** [comment]
@codesculpture I saw your earlier comments on this issue, but since some time had passed without updates and the issue wasn’t assigned, I thought maybe you weren’t working on it anymore. I should’ve checked with you first or shared the link to my CL as soon as I created it. Apologies for unintentionally duplicating the work!

**Comment by codesculpture** [comment]
> @codesculpture I saw your earlier comments on this issue, but since some time had passed without updates and the issue wasn’t assigned, I thought maybe you weren’t working on it anymore. I should’ve checked with you first or shared the link to my CL as soon as I created it. Apologies for unintentionally duplicating the work!

Hey nothing to apologize, am the one who is lazy to not working on this since my previous comment, btw nice change because i compared with my change, your's is more clear !
