### ISSUE TITLE
Support for sparse files 

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#56801]
As most modern file systems support [sparse files](https://en.wikipedia.org/wiki/Sparse_file) it would be nice if the `dart:io` package would provide some support to create and work with such files.

**Comment by lrhn** [comment]
What would this support look like?
If the underlying operating system supports sparse files, would it be enough to be able to *create* a spares (empty) file, and then use a `RandomAccessFile` to write parts of it?

If the sparse file support is in the operating system (like NTFS with sparse files enabled) I don't think Dart needs to do anything. Large sequences of zeros being written are automatically not allocated on disk.

**Comment by isoos** [comment]
> Large sequences of zeros being written are automatically not allocated on disk.

Oh, last time I have looked into this closely I think it was a separate system call to mark a region of the file as empty. If writing zeros does it, then I guess the issue is obsolete (or maybe we still need to mark it on creation?).

**Comment by mraleph** [comment]
IIUC Windows and Linux/Mac OS X have different behavior. Windows requires explicit `FSCTL_SET_SPARSE` via `DeviceIoControl`. Linux/Mac OS X file systems handle this transparently: if you for example `ftruncate` a file to a larger size that creates a hole in file, similarly you can seek through the file to a nonexistent offset - and that would also create a hole.

Note that AFAIK writing zeros into the hole will actually fill it up, OS does not actually check that you are writing all zeros. Windows has explicit `FSCTL_SET_ZERO_DATA` for that. Linux `fallocate` with `FALLOC_FL_PUNCH_HOLE`. Mac OS X - `fcntl` with `F_PUNCHHOLE`.

I am not sure this API is a very good fit for `dart:io`.

**Comment by lrhn** [comment]
If there was a way to memory-map a file, then it *could* special-case `.fillRange(start, end, 0)` when the underlying OS supports it.
The option that could make sense for the current `dart:io` API could be adding a way to explicitly write "zeros" to `RandomAccessFile`, and then have that use the OS support if available.

It's still not something you can rely on, which means that if you create a large file and expects it to be sparse, then you might get a suprising "disk full" error if the file system doesn't support it, or it does so in a way that `dart:io` doesn't recognize.

And adding members to existing types is breaking, even if it's `RandomAccessFile` which I haven't seen anyone implementing.

**Comment by a-siva** [comment]
I am not sure if this is a case for inclusion into 'dart:io' , maybe FFI can be used to support this, similar to the way mmaping of files is supported,
