### ISSUE TITLE
API doc issue: spelling error

### ISSUE THREAD

**Issue by zcsrssrs** [dart-lang/sdk#56810]
https://github.com/dart-lang/sdk/blob/main/sdk/lib/io/stdio.dart

Line 42:       
 /// Lines my be terminated by either `<CR><LF>` or `<LF>`. On Windows,
should be   
/// Lines may be terminated by either `<CR><LF>` or `<LF>`. On Windows,

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/387603
