### ISSUE TITLE
[CP] [dart2wasm] Fix hash code of _RecordType

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#56817]
### Commit(s) to merge

09e47b67a77

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/387480

### Issue Description

dart2wasm overrides `operator ==` or the record runtime type representation to implement structural equality, but we previously didn't update `hashCode`.

### What is the fix

Override `hashCode` of the runtime types of record types.

### Why cherry-pick

This causes issues when runtime type of a record is used in hash maps, sets, or similar code that uses both the `hashCode` and `operator ==`.

In particular, a user noticed that using the [provider](https://pub.dev/packages/provider) library and to add a provider for a record type does not work, as the record type is used as a hash map key in the library.

In general, any code that uses a record type in a hash map or set will be broken without the fix.

### Risk

None.

### Issue link(s)

https://github.com/flutter/flutter/issues/155510

**Comment by vsmenon** [comment]
lgtm
