### ISSUE TITLE
Breakpoints move to a different line to the one they were added on

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#56820]
Raised by @FMorschel at https://github.com/Dart-Code/Dart-Code/issues/5157, moving here because it seems to be a VM/debugger issue.

Given this code:

```dart
void main(List<String> arguments) {
  [
    for (final x in [1]) ...[
      x, // Breakpoint on this line
    ]
  ];

  print('a'); // Breakpoint gets moved here
}
```

With a breakpoint on the first marked line (4), the VM moves the breakpoint to the second marked line (8):

![image](https://github.com/user-attachments/assets/7a05686f-2edf-41df-859b-a4e2a057777e)

![image](https://github.com/user-attachments/assets/8f162228-8c0f-416b-8e7a-a87055d63a2d)

The VM traffic looks like this (note `"line": 4` in the request, but `"line": 8,` in both the breakpoint added event and the response):

```
==> {
	"jsonrpc": "2.0",
	"id": "15",
	"method": "addBreakpointWithScriptUri",
	"params": {
		"isolateId": "isolates/5236497997359299",
		"scriptUri": "file:///D:/Dev/Test%20Projects/dart_sample/bin/moving_breakpoints.dart",
		"line": 4
	}
}
<== {
	"jsonrpc": "2.0",
	"method": "streamNotify",
	"params": {
		"streamId": "Debug",
		"event": {
			"type": "Event",
			"kind": "BreakpointAdded",
			"isolateGroup": {
				"type": "@IsolateGroup",
				"id": "isolateGroups/763439454971288",
				"name": "D:\\Dev\\Test Projects\\dart_sample\\bin\\moving_breakpoints.dart",
				"number": "763439454971288",
				"isSystemIsolateGroup": false
			},
			"isolate": {
				"type": "@Isolate",
				"id": "isolates/5236497997359299",
				"name": "main",
				"number": "5236497997359299",
				"isSystemIsolate": false,
				"isolateGroupId": "isolateGroups/763439454971288"
			},
			"timestamp": 1727710630927,
			"breakpoint": {
				"type": "Breakpoint",
				"fixedId": true,
				"id": "breakpoints/1",
				"enabled": true,
				"breakpointNumber": 1,
				"resolved": true,
				"location": {
					"type": "SourceLocation",
					"script": {
						"type": "@Script",
						"fixedId": true,
						"id": "libraries/@20428661/scripts/file%3A%2F%2F%2FD%3A%2FDev%2FTest%2520Projects%2Fdart_sample%2Fbin%2Fmoving_breakpoints.dart/19243941340",
						"uri": "file:///D:/Dev/Test%20Projects/dart_sample/bin/moving_breakpoints.dart"
					},
					"tokenPos": 127,
					"line": 8,
					"column": 3
				}
			}
		}
	}
}
<== {
	"jsonrpc": "2.0",
	"result": {
		"type": "Breakpoint",
		"fixedId": true,
		"id": "breakpoints/1",
		"enabled": true,
		"breakpointNumber": 1,
		"resolved": true,
		"location": {
			"type": "SourceLocation",
			"script": {
				"type": "@Script",
				"fixedId": true,
				"id": "libraries/@20428661/scripts/file%3A%2F%2F%2FD%3A%2FDev%2FTest%2520Projects%2Fdart_sample%2Fbin%2Fmoving_breakpoints.dart/19243941340",
				"uri": "file:///D:/Dev/Test%20Projects/dart_sample/bin/moving_breakpoints.dart",
				"_kind": "kernel"
			},
			"tokenPos": 127,
			"line": 8,
			"column": 3
		}
	},
	"id": "15"
}
```

In the [VM service spec](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#addbreakpointwithscripturi), it says:

> If no breakpoint is possible at that line, the 102 (Cannot add breakpoint) [RPC error](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#rpc-error) code is returned.

It's not clear to me if the breakpoint location is invalid or valid. If it's valid, then it shouldn't move and execution should pause there. If it's invalid, then the breakpoint should fail to resolve (staying grey in the editor) and not trigger at all so that the user understands this is not a valid location.

**Comment by a-siva** [comment]
//cc @derekxu16

**Comment by DanTup** [comment]
Thanks! While testing this I noticed that we have reasons for this, so I've opened https://github.com/Dart-Code/Dart-Code/issues/5314 about getting them back into the UI so this will be even clearer to the user.
