### ISSUE TITLE
Dart Analysis Poor Performance - Group Issue

### ISSUE THREAD

**Issue by AndryHTC** [dart-lang/sdk#56838]
What I love most about Dart is the developer experience.

For me, a huge part—roughly 90%—of this positive DX stems from features like method and attribute inspection via autocomplete, which provides instant feedback on the correctness of your code.

The Dart and Flutter communities have embraced this philosophy, and it's evident in how they design their packages to support this intuitive workflow.

That’s why fast and robust static analysis is essential and must remain a top priority for Dart.

This is a recurring group of issues that our team has been experiencing for years, such as:
- #56755
- #56433
- #56355
- #56307
- #56247
- #55281
- #52947
- #51127
- #50962
- #48788
- #45723
- #43943
- #43765
- #33039

Most of them are P2-P3 and stuck for months even years.
What I'm asking is to give more priority to one of Dart's biggest strengths, the static analysis.

**Comment by mraleph** [comment]
Thanks for filing the issue - but it is not really actionable. Some of these are not even analyzer issues at all (e.g. https://github.com/dart-lang/sdk/issues/56755). It is not like there is a single solution for all these issues - analyzer simply does a lot of things and the more code your throw at it the slower it gets.

We have been looking at this from different angles for a while now, for example [workspaces](https://github.com/dart-lang/sdk/issues/53875) should significantly improve analyzer memory usage and responsiveness on monorepos. 

If you have some concrete problems with the analyzer it would help us more if you file _those_ with reproductions as separate issues.

**Comment by AndryHTC** [comment]
Hi @mraleph,

Thanks for your response. Nobody said there's a one-size-fits-all solution, but seeing so many related issues open for years feels like there's an underlying problem with the analyzer.

Even small projects are experiencing these performance issues, as exposed by many, which makes me think it's not just about large codebases. Grouping these problems together was meant to show that it's a widespread issue affecting many developers.

If nothing can be done, I understand closing the group issue. What I don't understand is not closing the years-old issues.
I hope the team can take a closer look at these recurring problems to improve the analyzer's performance for everyone.

**Comment by mraleph** [comment]
> Even small projects are experiencing these performance issues, as exposed by many, which makes me think it's not just about large codebases.

I am not so sure about this - so far we were never able to reproduce any performance issues on small projects (outside of issues like https://github.com/dart-lang/sdk/issues/56355 - which is obviously just a bug with an infinite loop of some sort).  Analyzer is rather responsive on small code bases (though it might still consume more memory than truly necessary). Scalability problems only surface when you start throwing significant amount of code at it.

**Comment by AndryHTC** [comment]
Well... the reality is that it is. But maybe you have noticed that in issues like #55281 and #56307, as I've seen you've already moved the waters in plenty of the issues that I've referenced. I'm so happy for your efforts 👍 

Also, I don't know what "significant amount of code" translates, in this context. 10 000 lines? 1 000 files?
