### ISSUE TITLE
Datagram Transport Layer Security in pure dart

### ISSUE THREAD

**Issue by Kellykinyama12** [dart-lang/sdk#56837]
We have started a pure implementation in pure dart. But due the enormous nature of the project, any contributions or welcome. The link is on this repo:
 - https://github.com/Kellykinyama12/dart-pure-dtls

**Comment by lrhn** [comment]
This is not about the Dart SDK repository, so it's not really on-topic in this issue tracker. 
I recommend posting this on the [misc@dartlang.org](mailto:misc@dartlang.org) mailing list instead.
