### ISSUE TITLE
"Go to Type Definition" on closure parameters not working

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56844]
Take the following code:

```dart
void foo(List<int> list) {
  list.map((e) => e);
}
```

If you ask for "Go to Type Declaration" on the last `e`, you get redirected to the declaration for `int`, but if you go to the first, you get a message telling you "No type definition found for 'e'":

![image](https://github.com/user-attachments/assets/5e696465-bf2d-406c-ac9c-dd06c28cf72f)

I volunteer to fix this.

---

CC: @DanTup

**Comment by scheglov** [comment]
It looks that we support `VariableDeclaration`, but not `FormalParameter`.
