### ISSUE TITLE
Serving and debugging a web app prints unactionable survey errors

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#56843]
I'm not sure where this should be resolved (dds/dwds/webdev), so opening the issue here.

But when I try running and debugging a web app with `webdev serve --debug`, I get repeated survey errors that are unactionable and aren't relevant to developers:

```
[INFO] Serving DevTools at http://127.0.0.1:56627
[INFO] Serving `web` on http://127.0.0.1:8080
[INFO] Running build completed, took 54ms
[INFO] Caching finalized dependency graph completed, took 90ms
[INFO] Succeeded after 146ms with 0 outputs (0 actions)
[INFO] Debug service listening on sse://127.0.0.1:56677/ecP-qts8hmU=/$debugHandler

ERROR: setActiveSurvey not called. - api/getSurveyShownCount
ERROR: setActiveSurvey not called. - api/getSurveyActionTaken
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Reproduction steps:

1. `dart create -t web web_app`
2. `dart pub add dev:webdev`
3. `dart run webdev serve --debug`
4. Open DevTools, either through the output link or the debug extension.

**Comment by nshahan** [comment]
Closing in favor of the DevTool issue https://github.com/flutter/devtools/issues/8405.
