### ISSUE TITLE
web/wasm/multi_module_stress_test goes from flaky to RuntimeError

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#56858]
The tests
```
web/wasm/multi_module_stress_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2wasm-linux-jscm-chrome
```

//cc @natebiggs

**Comment by biggs0125** [comment]
Locally I see a timeout for this test. This test is unpacking a dill file which involves a lot of String operations. In JS string compatibility mode these operations are much slower and therefore take too long for the test harness.

I don't think there's a fix here, necessarily. We just shouldn't run this test in jscm mode.

I've opened a change that would allow us to disable compatibility mode for this test (and any others that run into similar issues).
