### ISSUE TITLE
Failures in pkg/json/test/json_*_test on Bump dart version to 3.7

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#56867]
There are new test failures on [Bump dart version to 3.7](https://dart-review.googlesource.com/c/sdk/+/388600).

The tests
```
pkg/json/test/json_codable_test CompileTimeError (expected Pass)
pkg/json/test/json_decodable_test CompileTimeError (expected Pass)
pkg/json/test/json_encodable_test CompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-linux
```

**Comment by athomas** [comment]
I think adding this to the version bump CL will fix it:
```
diff --git a/pkg/json/pubspec.yaml b/pkg/json/pubspec.yaml
index 98a28ee251f..d58a51b230a 100644
--- a/pkg/json/pubspec.yaml
+++ b/pkg/json/pubspec.yaml
@@ -7,7 +7,7 @@ description: >
 repository: https://github.com/dart-lang/sdk/tree/main/pkg/json
 version: 0.20.2
 environment:
-  sdk: ^3.6.0-edge
+  sdk: ^3.7.0-edge
 dependencies:
   macros: ^0.1.0-main.5
 dev_dependencies:
```

**Comment by athomas** [comment]
@jakemac53 is this failure caused by not having published a new pkg/json version? Can you publish one if that's the reason?

pkg/dartdev/test/commands/create_integration_test RuntimeError (expected Pass)
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8734646128009074417/+/u/test_results/new_test_failures__logs_

**Comment by jakemac53** [comment]
> @jakemac53 is this failure caused by not having published a new pkg/json version? Can you publish one if that's the reason?

I don't believe we should need a new one published, looking

**Comment by jakemac53** [comment]
There don't appear to be any useful logs here. But, I can take a wild guess that this is related to the need for a new build_web_compilers and build_modules package. Those were published yesterday so you could see if the test passes now.

**Comment by athomas** [comment]
Yes, https://dart-current-results.web.app/#/filter=pkg/dartdev/test/commands/create_integration_test&showAll is passing now. Closing this issue.

**Comment by jakemac53** [comment]
> The change above fixed the tests. Leaving this issue open because pkg/json may need to be re-published.

Note that the language version should not have needed to be updated, the release version for the experiment was set to `3.3.0`.

Everything seems to be working fine for me locally with the old version so I will try reverting that change and see if it still fails.

**Comment by jakemac53** [comment]
Ahh, the problem is we created a new experiment (enhanced-parts), which doesn't have a release version, so this broke package:json.

The correct fix is probably to add an experimental release version to that experiment of 3.6.

**Comment by jakemac53** [comment]
https://dart-review.googlesource.com/c/sdk/+/389240 has the fix
