### ISSUE TITLE
[Proposal] Lint rule or analyzer code for unresolved DartDoc symbols, post `@docImport` introduction

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#56878]
With the new `@docImport` feature, I was looking for a way to have unresolved doc references be flagged, since we now have an extra option of dealing with this problem.

We do have https://github.com/dart-lang/sdk/issues/55414 for a similar case: Warn when a doc import is unused.

However, it would be nice if we had a rule for unresolved doc references in DartDoc.
For example:

```dart
/// This class references an unresolved class [Bar].
class Foo {}
```

This would warn on [Bar] not being found. It could suggest either:
- adding a `@docImport`
- importing the library normally
- fixing the reference if it was a typo or if the symbol no longer exists (which could be the case if docs were not updated)

I think that _if_ we implement something like this, it could be very helpful for the quality of DartDoc in IDE's.

I'm not sure if this should become a code in the analyzer (like the issue mentioned above) or a lint rule.

**Comment by srawlins** [comment]
This is the `comment_references` lint rule.

**Comment by pq** [comment]
@navaronbracke: check out `comment_references` and if it doesn't work for you please re-open this request with more details. Thanks!

**Comment by navaronbracke** [comment]
TIL about that lint. Working as expected, thanks!
