### ISSUE TITLE
Wrong type inference with nested getter function

### ISSUE THREAD

**Issue by mrgnhnt96** [dart-lang/sdk#56896]
Repro:

```dart
abstract class BaseA {
  String Function() get content;
}

class A implements BaseA {
  const A(this.content);

  @override
  final String Function() content;
}

class B {
  const B(this.a);

  final BaseA a;
}

A? getA() {
  return A(() => '');
}

B? getB() {
  return null;
}

void main() {
  final a = getA();
  final aContent = a?.content(); // String?
  if (aContent == null) {}

  final b = getB();
  final bContent = b?.a.content(); // String
  if (bContent == null) {} // lint_warning: unnecessary_null_comparison
}
```

`bContent` should be a type `String?` given that `b` can be `null`.

---

Dart Version: `Dart SDK version: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"`

**Comment by eernstg** [comment]
Good catch! It is actually not a matter of wrong type inference, it's the expression `b?.a.content()` whose static type is computed as `String` even though it should have been `String?`.

Here is a somewhat smaller example that shows the same behavior:

```dart
class A {
  const A(this.content);
  final String Function() content;
}

class B {
  const B(this.a);
  final A a;
}

void main() {
  final bContent = (null as B?)?.a.content();
  bContent.substring(1); // Accepted by the analyzer, should be an error.
}
```

**Comment by mrgnhnt96** [comment]
Thanks @eernstg! Thats exactly whats happening, thanks for simplifying the example

**Comment by pq** [comment]
/fyi @stereotype441 (who may find this interesting)
