### ISSUE TITLE
type 'int' is not a subtype of type 'double?'

### ISSUE THREAD

**Issue by dhilshana** [dart-lang/sdk#56913]
This usually happens when an API response or data processing step returns an int value, but my model or function is expecting a double?.

When a double variable is assigned an int value, implicit conversion from int to double is possible. However, the mentioned error occurs in this case.

**Comment by jasimrazi** [comment]
I'm experiencing the same problem. Can you suggest a solution?

**Comment by mraleph** [comment]
Dart[^1] does not implicitly coerce `int` to `double` (or vice versa), because (among other reasons) such conversions are not loss-less. You have to explicitly convert using `num.toDouble()` or `num.toInt()`.  

[^1]: With the exception of JavaScript backend (`dart2js`) which uses JavaScript numbers to represent both `int` and `double`.

**Comment by ulisseshen** [comment]
its confuse, because if you declare a variable as `double my_double = 100;` it will be acepted and no static erros will happen. It suggest to us that the same will work in the `double.parse('100')` when we received it from API or other data source.

**Comment by bwilkerson** [comment]
I can see how that can be confusing. It happens because of the following text in the language spec:

> Let _l_ be an integer literal that is not the operand of by a unary minus operator, and let _T_ be the static context type of _l_. If `double` is assignable to _T_ and `int` is not assignable to _T_, then the static type of _l_ is `double`; otherwise the static type of _l_ is `int`.
>
> _This means that an integer literal denotes a `double` when it would satisfy the type requirement, and an `int` would not. Otherwise it is an `int`, even in situations where that is an error._

That can make it seem as if Dart does coercions, but it doesn't, it just changes the interpretation of a numeric literal under one special condition.
