### ISSUE TITLE
Dart analyzer not analyzing correct after If(variable case class)

### ISSUE THREAD

**Issue by abikko** [dart-lang/sdk#56914]
* Dart version and tooling diagnostic info (`dart info`)
![Screenshot 2024-10-18 at 14 05 18](https://github.com/user-attachments/assets/df85c2e0-ed02-4896-a5f2-86faa7c347ad)

* Whether you are using Windows, macOS, or Linux - **macOS**
* Whether you are using Chrome, Safari, Firefox, Edge - doesn't matter

Hello Dart team!

I have a problem, I searched the probably existing issues, but didn't find anything relating to this issue.

So, consider example, we have a sealed class with child classes like in screenshot below:
![Screenshot 2024-10-18 at 14 12 57](https://github.com/user-attachments/assets/0758f9fa-65f2-4dd2-b6e7-a8adfa301ded)

And if we will write code like this:

![Screenshot 2024-10-18 at 14 30 59](https://github.com/user-attachments/assets/8415305f-0cdb-4ae2-83db-5d7b34e57e9e)

Dart analyzer will warn us that `testor` is `A`, not **B after checking pattern**.
![Screenshot 2024-10-18 at 14 31 38](https://github.com/user-attachments/assets/f3355ae2-14d8-4c41-a7a7-8f53ee8bcccf)

**Comment by mraleph** [comment]
It should be `case B()` not `case B` then it will work as you want it.
