### ISSUE TITLE
thisOrAncestorOfType2() behaves unexpectedly on MixinElement2

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#56917]
While migrating some code, I got ` MixinElement2` like this:

```dart
MixinDeclaration x;
var element = x.declaredFragment.element;
```

The `runtimeType` is `NotAugmentedMixinElementImpl`. I passed it to some shared code calls `thisOrAncestorOrType2<InterfaceElement2>()` which I expected to return itself, however it throws:

```
Unsupported operation: Cannot get an enclosingElement2 for a fragment
#0      ElementImpl.enclosingElement2 (package:analyzer/src/dart/element/element.dart:2449:7)
#1      ElementImpl.thisOrAncestorOfType2 (package:analyzer/src/dart/element/element.dart:3092:30)
#2      MaybeAugmentedInstanceElementMixin.thisOrAncestorOfType2 (package:analyzer/src/dart/element/element.dart:7149:19)
#3      DartUnitHoverComputer.Eval ()
```

If I evaluate `element is InterfaceElement2` I get `true`, so I would have expected it to return itself before even looking at any ancestors (but if it did look at ancestors, I would never expect it to get to a `Fragment`). The implementation of `MaybeAugmentedInstanceElementMixin.thisOrAncestorOfType2` seems to go to `.declaration` which doesn't seem correct (at least not in this case where I expect to be entirely in the `Element2` model with no `Fragment`s).

(Some more discussion about this issue was [on Discord](https://discord.com/channels/608014603317936148/1296495521917304853))

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/390811

**Comment by DanTup** [comment]
Thanks! :)
