### ISSUE TITLE
Dart analyze takes alot of ram nearly 6GB out of 8GB

### ISSUE THREAD

**Issue by Elfandy** [dart-lang/sdk#56923]
i am building an app in flutter and i noticed a problem on all my devices that i develop on, that dart anlyze take alot of ram (min is 1.5 gb to max 7 GB) somtimes vscode crashes from that.
when the ram usage spikes the dart sdk just frezze and not letting vscode make any suggestions or debugging 
i don't run any virtual machine withit i deveolp on physcal device over wireless debugging using adb connection
Dart verison: 3.5.1
flutter version: 3.24.1
ram:8gb
os:widnows 11
editor: VsCode
cpu:Intel(R) Core(TM) i7-1065G7 CPU

**Comment by mraleph** [comment]
What is the size of your code base? Is it split into a large number of small packages? If it is - please try adopting [_workspaces_](https://docs.google.com/document/d/1UEEAGdWIgVf0X7o8WPQCPmL4LSzaGCfJTM0pURoDLfE/edit?resourcekey=0-c5CMaOoc_pg3ZwJKMAM0og&tab=t.0).

If you open diagnostics page (`Dart: Open Analyzer Diagnostics` in command pallette), what is the number of _contexts_ you see (it will be in column on the left hand side).

**Comment by cheymos** [comment]
> What is the size of your code base? Is it split into a large number of small packages? If it is - please try adopting [_workspaces_](https://docs.google.com/document/d/1UEEAGdWIgVf0X7o8WPQCPmL4LSzaGCfJTM0pURoDLfE/edit?resourcekey=0-c5CMaOoc_pg3ZwJKMAM0og&tab=t.0).
> 
> If you open diagnostics page (`Dart: Open Analyzer Diagnostics` in command pallette), what is the number of _contexts_ you see (it will be in column on the left hand side).

Hi! I was passing by and happened to see a talk about workspaces. Could you please tell me if they are available in version 3.5.3?

**Comment by mraleph** [comment]
@cheymos pub only got support for workspaces in 3.6 (though some analyzer bits were already available in 3.5.3). so unfortunate I think the answer is no. please correct me if I am wrong @sigurdm

**Comment by sigurdm** [comment]
The biggest missing piece in 3.5 is flutter tools.
If you work in Dart only, 3.5 should work fine. That is why we announce it only with 3.6.
