### ISSUE TITLE
New assist - inline if with outer else

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56924]
Could we add the option to join inner `if` with `else`:

```dart
if (a) {
} else {
  if (b) {
  } else if (c) {
  }
}
```

Could become:

```dart
if (a) {
} else if (b) {
} else if (c) {
}
```

_Originally posted by @FMorschel in https://github.com/dart-lang/sdk/issues/56715#issuecomment-2424405227_

I made a CL https://dart-review.googlesource.com/c/sdk/+/391021

**Comment by scheglov** [comment]
Look useful to me!
