### ISSUE TITLE
multiple duplicate tooltips

### ISSUE THREAD

**Issue by ChaserVasya** [dart-lang/sdk#56937]
<img width="802" alt="Снимок экрана 2024-10-22 в 13 02 30" src="https://github.com/user-attachments/assets/dacc45c6-ec3f-489d-95ce-ee3bab6b5643">

# fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 15.0.1 24A348 darwin-arm64, locale ru-RU)
    • Flutter version 3.24.1 on channel stable at /Users/vasilijisajkin/fvm/versions/3.24.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (9 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/vasilijisajkin/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/vasilijisajkin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • iPhone (василий) (mobile)       • 00008101-001D69421E41001E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.101

[✓] Network resources
    • All expected network resources are available.

• No issues found!
<img width="374" alt="Снимок экрана 2024-10-22 в 13 04 15" src="https://github.com/user-attachments/assets/c01157e5-f652-46c6-a5d7-08515014cc15">

**Comment by FMorschel** [comment]
I'm unsure if this is the same thing but I think @DanTup has worked on a similar issue before. I think it was maybe over at the vscode extension issue tracker though.

**Comment by DanTup** [comment]
Yep, this is the same as https://github.com/dart-lang/sdk/issues/56320 which was recently fixed.
