### ISSUE TITLE
displayString2() loses type substitutions for constructor invocation with type arguments

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#56933]
I hit this issue trying to migrate some code to the new Element model, but I couldn't figure out what the fix was...

The code I'm migrating is testing the hover on some code like `new A<String>()`. Calling `getDisplayString()` returns `"A<String> A()"` but calling `displayString2()` returns `"A<T> A()"`:

![image](https://github.com/user-attachments/assets/f76b0cc0-3e41-40db-a409-ad63eca61d23)

Stepping through `getDisplayString()`, it accesses `ExecutableMember.type` which calls `_substitution.substituteType` before returning the type.

However when stepping through `displayString2()` it accesses `_element2` which accesses `declaration.asElement2`. I don't know if it's this use of `declaration` that is losing the type substitutions?

Here's a small repro test:

```dart
  @soloTest
  Future<void> test_danny() async {
    await resolveTestCode('''
class A<T> {}
void f() {
  new A<String>();
}
''');

    var element =
        findNode.instanceCreation('A<String>').constructorName.staticElement!;

    expect(
      (element as Element2).displayString2(),
      element.getDisplayString(),
    );
  }
```

Which fails with:

```
00:00 +0 -2: SearchEngineImplWithNonFunctionTypeAliasesTest | test_danny [E]

  Expected: 'A<String> A()'
    Actual: 'A<T> A()'
     Which: is different.
            Expected: A<String> A( ...
              Actual: A<T> A()
                        ^
             Differ at offset 2
```

@bwilkerson

**Comment by bwilkerson** [comment]
Given that you have a `ConstructorMember`, you're probably running the implementation of `displayString2` from `ExecutableMember`:

```dart
  String displayString2(
      {bool multiline = false, bool preferTypeAlias = false}) {
    return _element2.displayString2(
        multiline: multiline, preferTypeAlias: preferTypeAlias);
  }
```

My guess is that the use of `_element2` is where the type information is discarded.

That method probably needs to be rewritten to create an `ElementDisplayStringBuilder` and pass it to `appendTo`.
