### ISSUE TITLE
MutatorMarkerRace_DetectInTLAB test compile error on GCC

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#56962]
The GCC bot doesn't like the new MutatorMarkerRace_DetectInTLAB test added in https://dart-review.googlesource.com/c/sdk/+/390263

Logs: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8733223566365977505/+/u/build_dart_debug_ia32/stdout

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/392063 should fix this issue.
