### ISSUE TITLE
Analysis server should not need to resolve a file in order to format it

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#56960]
The analysis server code for running the formatter calls `AnalysisDriver.getResolvedUnit`, which means that it won't be able to format the file until it's fully resolved it. It would be nice if it could use an analysis API that didn't require resolution, since that could in principle make formatting much faster.

The reason it currently uses `AnalysisDriver.getResolvedUnit` is because it needs `unit.libraryElement2.effectiveLanguageVersion` in order to tell the formatter which language version to use for formatting. But this feels like overkill; it should be possible to figure out the langauge version based on the unresolved AST and some information from the context.

See discussion here: https://dart-review.googlesource.com/c/sdk/+/391840/comment/5e5314af_b5c7db9a/

**Comment by bwilkerson** [comment]
See also https://dart-review.googlesource.com/c/sdk/+/391663/2/pkg/analysis_server/lib/src/lsp/source_edits.dart, which indicates that the problem can be resolved by adding one public getter to `CompilationUnit` (a getter that's already implemented in `CompilationUnitImpl`).

**Comment by munificent** [comment]
I ran into a [similar issue](https://github.com/dart-lang/sdk/issues/56941) with the IDE integration and @DanTup [got that sorted out](https://github.com/dart-lang/sdk/commit/93fda3ea7d823310a39e76ac9eefcbf94a7809b3) so maybe we can do something similar here.

**Comment by DanTup** [comment]
Ah, my fix was only for LSP (which was already using only a parsed AST). I'm looking at some changes so all `CompilationUnit`s have a non-null version, so I'll fix this while I'm at it.
