### ISSUE TITLE
Type arguments don't have null safety

### ISSUE THREAD

**Issue by nate-thegrate** [dart-lang/sdk#56998]
I should preface by saying: this is super niche, and it's not a big deal to me if/when it gets fixed.
But I noticed this problem and thought it'd be nice to report it.

## Summary

If a value's type is defined by a type argument, a switch expression can be missing the `null` case, and it isn't noticed until runtime.

## Example

```dart
int foo<T extends int?>(T value) => switch (value) { int() => value };

void main() {
  final int value = foo<int?>(null);

  print(value);        // prints "null"
  print(value.isEven); // throws an error
}
```

<br>

The same issue happens when there aren't any type constraints:
```dart
int foo<T>(T value) => switch (value) { Object() => value };

void main() {
  final Object value = foo(null);
  print(value == null);
}
```

According to static analysis, `The operand can't be 'null', so the condition is always 'false'.`
But the program prints "true".

<br><br>

I've only seen this situation [once](https://github.com/flutter/flutter/pull/154753#discussion_r1783573549) in the "real world", so perhaps it's not a huge deal :)

**Comment by eernstg** [comment]
> not a big deal

A soundness issue is always a big deal - thanks for the heads-up!
