### ISSUE TITLE
Missing quick fix for `omit_obvious_property_types` in Dart Analysis view in IntelliJ

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/sdk#57017]
This line triggers the `omit_obvious_property_types` lint:

```dart
final String foo = '';
```

When using right click in the Analysis View in IntelliJ, there is no quick fix shown:
![image](https://github.com/user-attachments/assets/0f0a47a1-c138-4db0-b4b3-b53050117626)

Pressing Alt+Enter directly on the type annotation where the lint occurs shows a quick fix:
![image](https://github.com/user-attachments/assets/c277ae8a-0645-476a-8b6a-d7e296136c62)

If it's declared as a local variable (`omit_obvious_local_variable_types`), the quick fix is shown in the Analysis View:
![image](https://github.com/user-attachments/assets/7e45dfc7-aaad-4ea9-a08f-d0d8980c1c24)

Additionally Alt+Enter has the yellow light bulb for quick fixes:
![image](https://github.com/user-attachments/assets/c188074a-68bd-4586-915e-86f014438287)

One obvious difference between both lints is that one `hasFix`, while the other `needsEvaluation` (if this matters):
https://github.com/dart-lang/sdk/blob/5b6e6865b03f808d9e1e74e4638c997650294839/pkg/analysis_server/lib/src/services/correction/error_fix_status.yaml#L2199-L2202

Dart version: Dart SDK version: 3.7.0-81.0.dev (dev) (Tue Oct 29 17:06:42 2024 -0700) on "windows_x64"

**Comment by eernstg** [comment]
Thanks! https://dart-review.googlesource.com/c/sdk/+/393280.

**Comment by bwilkerson** [comment]
The status in `[error_fix_status.yaml](https://github.com/dart-lang/sdk/blob/5b6e6865b03f808d9e1e74e4638c997650294839/pkg/analysis_server/lib/src/services/correction/error_fix_status.yaml#L2199-L2202)` doesn't actually control anything. It's there only as away for us to track which diagnostics could have a fix that don't.

It is, however, required to match reality by having a test that compares it to the table used to produce fixes for diagnostics. It was the absence of a mapping in this table that prevented the fix from being displayed.

Thanks @eernstg for the CL to add the mapping to the table (and fix the status file to be consistent).

**Comment by denniskaselow** [comment]
fixed in https://github.com/dart-lang/sdk/commit/c9391d7f19c19c012956eb74d00e0b0dcea82c41
