### ISSUE TITLE
riscv32 build is broken

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#57021]
https://dart-review.googlesource.com/c/sdk/+/392740 broke riscv32 build. 

```
$ tools/build.py -mrelease -asimriscv32 dart gen_snapshot create_sdk
...
../../runtime/vm/compiler/backend/il_riscv.cc:6878:14: error: unused variable 'in_hi' [-Werror,-Wunused-variable]
 6878 |     Register in_hi = in_pair->At(1).reg();
      |              ^~~~~
1 error generated.
```

This showed up as broken fuzz bot
https://ci.chromium.org/ui/b/8732415745790097697

cc @alexmarkov

**Comment by alexmarkov** [comment]
@aam Un-assigned the issue from myself as I saw your fix https://dart-review.googlesource.com/c/sdk/+/393361.

@rmacnak-google What is the status of 32-bit RISC-V support? If we support it, should we have at least one (nightly?) bot for testing it? Fuzz bot doesn't send e-mails and doesn't have a corresponding try-bot which would prevent such trivial compilation errors.

**Comment by aam** [comment]
I have put together https://dart-review.googlesource.com/c/sdk/+/393380 that adds simriscv32 to nightly builds
