### ISSUE TITLE
Missing keywords in code completion suggestions

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#57032]
Create a file containing the following (with the caret removed):
```dart
void f() => <String, int>{"": ^};
```
Place the cursor in the location of the caret and request completions. Lots of identifiers will be suggested, but none of the keywords that are valid at that location are suggested.

If you type part of a keyword and request completions at the end of the identifier
```dart
void f() => <String, int>{"": co^};
```
The same behavior occurs, which suggests that this isn't just a problem with recovery.

However, if you type the whole keyword
```dart
void f() => <String, int>{"": const^};
```
and request completions, then the keyword will be suggested.

**Comment by FMorschel** [comment]
Working on https://github.com/dart-lang/sdk/issues/56936 I noticed the keywords were showing up, there may be something else here (take a look at ~15s for `const`):

https://github.com/user-attachments/assets/a1b706e5-799d-4f61-9eb3-fe82012454ee

I can see if I find something later.

**Comment by FMorschel** [comment]
Here is my CL https://dart-review.googlesource.com/c/sdk/+/393940. I'm not 100% sure the implementation is what we'd expect but we can discuss it.
