### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by RajeshMCA1214** [dart-lang/sdk#57059]
## Version information

- `IDEA AI-232.10300.40.2321.11567975`
- `3.3.3`
- `AI-232.10300.40.2321.11567975, JRE 17.0.9+0--11185874x64 JetBrains s.r.o., OS Windows 11(amd64) v10.0 , screens 2880.0x1620.0`

**Comment by RajeshMCA1214** [comment]
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future releas
BUILD FAILED in 11s

**Comment by devoncarew** [comment]
Hi - I don't think this is the right forum for your issue; you might see https://flutter.dev/go/flutter-gradle-plugin-apply to see if the info there is helpful.
