### ISSUE TITLE
Wrong error in `await e` expression when `e` has type `void`

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#57065]
According to the Dart specification https://github.com/dart-lang/language/blob/48d3cbdb3dd4d75459453c69ef255064a4b89f13/specification/dartLangSpec.tex#L22709

> The occurrence of an expression of type void is a compile-time error unless it is
> permitted according to one of the following rules.
> ...
> - In an expression of the form `await e`, `e` may have type `void`.

But the code below produce compile-time errors in the both analyzer and CFE.
```dart
void foo() {}

main() async {
  void e = 0;
  await e; // Error: This expression has type 'void' and can't be used.
  await foo(); // Error: This expression has type 'void' and can't be used.
}
```
`Dart SDK version: 3.7.0-99.0.dev (dev) (Mon Nov 4 08:02:58 2024 -0800) on "windows_x64"`

**Comment by eernstg** [comment]
I think this one has been updated: With NNBD, it is (luckily!) no longer allowed for `await` to have an operand of type `void`.

**Comment by sgrekhov** [comment]
Thank you! Closing this issue then.
