### ISSUE TITLE
Overflowing smi range for port ids with native ports

### ISSUE THREAD

**Issue by madsager** [dart-lang/sdk#5711]
In dart:io we use native ports to post data to the thread pool. We are seeing issues where we are overflowing smi range for port ids.

The scenario is:

&nbsp;&nbsp;&nbsp;nativePort.call(request).transform((result) { ... });

For each call, a receive port is allocated. We perform these calls for each little chunk of file data that we process. Port ids are allocated by just incrementing a counter which is never reset. On servers that run for days and process a lot of file data, this has started overflowing smi range for the port ids.

**Comment by iposva-google** [comment]
Stale.
