### ISSUE TITLE
`dart fix --fail-fast` runs full loops to complete

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#57118]
For the following code, we have 100 runs for `Test $i`. Even with `--fail-fast` the full loops are completed before the test stops. Can this be fixed so that if a test fails (with `--fail-fast`) it works as a `break` in all loops or something?

Repro:

```dart
import 'package:test/test.dart';

void main() {
  group('Tests', () {
    for (var i = 0; i < 100; i++) {
      group('Tests J $i', () {
        for (var j = 0; j < 100; j++) {
          print('Test $i - $j');
          test('Test $i', () {
            expect(i, 1);
            expect(j, 1);
          });
        }
      });
    }
  });
}
```

**Comment by bwilkerson** [comment]
This sounds like a question about `package:test`. If so, you might get a better answer at https://github.com/dart-lang/test.

**Comment by FMorschel** [comment]
Thanks for pointing it out. Here is the new issue https://github.com/dart-lang/test/issues/2417.
