### ISSUE TITLE
VM should provide more actionable details for typedef mismatch

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#5740]
For an error such as:

Exception: type '(int) =&gt; void' is not a subtype of type 'RequestAnimationFrameCallback' of 'callback'.
Stack Trace: #­0      \_DOMWindowImpl.requestAnimationFrame (/Volumes/data/b/build/slave/dartium-mac-full/build/src/xcodebuild/DerivedSources/Release/webkit/bindings/dart/dart/WindowImpl.dart:190:59)
#­1      SolarSystem.requestRedraw (http://127.0.0.1:3030/Users/sethladd/Code/Dart/dart/samples/solar/solar.dart:145:33)
#­2      SolarSystem._start (http://127.0.0.1:3030/Users/sethladd/Code/Dart/dart/samples/solar/solar.dart:111:18)
#­3      SolarSystem.start.&lt;anonymous closure&gt; (http://127.0.0.1:3030/Users/sethladd/Code/Dart/dart/samples/solar/solar.dart:72:13)
#­4      FutureImpl._complete (bootstrap_impl:605:19)
#­5      FutureImpl._complete (bootstrap_impl:613:5)
#­6      FutureImpl._setValue (bootstrap_impl:627:14)
#­7      CompleterImpl.complete (bootstrap_impl:710:26)
#­8      \_completeMeasurementFutures._completeMeasurementFutures (/Volumes/data/b/build/slave/dartium-mac-full/build/src/dart/lib/html/src/Measurement.dart:115:35)
#­9      \_MeasurementScheduler._onCallback (/Volumes/data/b/build/slave/dartium-mac-full/build/src/dart/lib/html/src/Measurement.dart:34:19)
#­10     \_MutationObserverScheduler._handleMutation._handleMutation (/Volumes/data/b/build/slave/dartium-mac-full/build/src/dart/lib/html/src/Measurement.dart:63:21)

It would be very nice if the error message also reported what RequestAnimationFrameCallback's signature is. The current message doesn't tell me how to fix the problem.

Also, the &quot;of 'callback'&quot; isn't clear.

**Comment by iposva-google** [comment]
dart ~/dart/Bug5740.dart
Unhandled exception:
Closure call with mismatched arguments: function 'main.<anonymous closure>'

NoSuchMethodError: incorrect number of arguments passed to method named 'main.<anonymous closure>'
Receiver: Closure: () => dynamic
Tried calling: main.<anonymous closure>(1)
Found: main.<anonymous closure>()
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      run (file:///Users/iposva/dart/Bug5740.dart:4:11)
#3      main (file:///Users/iposva/dart/Bug5740.dart:8:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
