### ISSUE TITLE
Hot replace of stateless classes

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#5752]
It would be great for Dart t support HotReplace for stateless classes. Very usefull for serverside developement.
////////////////////////////////////////////////////////////////////////////////////
Editor: 13122 (2012-10-02)
OS: Windows 7 - amd64 (6.1)
JVM: 1.7.0_04

SDK installed: true
Dartium installed: true

[from editor feedback]

**Comment by iposva-google** [comment]
Stale.
