### ISSUE TITLE
Add configuration for testing dart2js with --minify flag.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#5820]
The html test suite needs to be tested on at least some drt / browser configuration with the --minify flag

**Comment by kevmoo** [comment]
@rakudrama has this been done yet?

**Comment by sigmundch** [comment]
I don't believe so - we have the bots covering --minify in d8, but not in chrome or drt.

We have a similar issue with --cps-ir: we only have coverage on d8 at this time.
