### ISSUE TITLE
Bad error message for missing closing parenthesis

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#5830]
The error message for the following code is slightly off:

foo(state {  // &lt;= missing closing parenthesis
&nbsp;&nbsp;return state;
}

&equals;&equals;&equals;

$ out/ReleaseIA32/dart t/bug.dart
'file:///mnt/ssd/floitsch/code/dart/dart/t/bug.dart': Error: line 5 pos 1: unexpected token 'foo'
foo(state {
^

**Comment by mhausner** [comment]
Committed patchset #2 (id:20001) manually as
d68a7de36a18db3da3ac92731d19a1592983effb (presubmit successful).
