### ISSUE TITLE
No warning when abstract class from imported library is also declared in file

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#5871]
Consider this code:

import 'dart:html';

var screens = new Map&lt;String, Screen&gt;();

addScreen(String name) {
&nbsp;&nbsp;screens[name] = new Screen();
}

Screen returnScreen(String name) {
&nbsp;&nbsp;return screens[name];
}

class Screen {
&nbsp;&nbsp;
}

main() {
&nbsp;&nbsp;addScreen(&quot;foo&quot;);
&nbsp;&nbsp;var s = returnScreen(&quot;foo&quot;);
&nbsp;&nbsp;print(s.runtimeType);
}

When you run it, you get this error:

Exception: type 'Screen' is not a subtype of type 'Screen' of 'function result'.
Stack Trace: #­0      returnScreen (http://127.0.0.1:3030/Users/sethladd/dart/dupehtmlclassname/dupehtmlclassname.dart:13:17)
#­1      main (http://127.0.0.1:3030/Users/sethladd/dart/dupehtmlclassname/dupehtmlclassname.dart:22:23)

There is an abstract class named Screen in dart:html.

I would expect some sort of warning from the Editor when I declared a class named Screen.

**Comment by bwilkerson** [comment]
We have improved the error message, so hopefully the UX is better now. Closing as stale.
