### ISSUE TITLE
`depend_on_referenced_packages` false positives for `dev_dependencies`

### ISSUE THREAD

**Issue by olavemil** [dart-lang/sdk#58743]
**Describe the issue**
The lint `depend_on_referenced_packages` reports wrongly when a dependency is used from within `/bin/*.dart` and declared as _only_ a dev_dependency.

**To Reproduce**
- Create a new flutter project `flutter create depend_on_referenced_packages_test`
- Create `/bin/repro.dart`
- Add the line `import 'package:flutter_lints/flutter.yaml';`
-- The yaml file used here is of course not a dart file, but will trigger the lint, and `flutter_lints` is  already declared a dev_dependency by default. Any other dependency will do, and the ones I get this for are the `args` and `yaml` package.
- The lint now triggers for any such dependencies.
- Adding them as regular dependencies will remove the warnings.

**Expected behavior**
No error when a dependency is imported in `/bin/*.dart` and declared as a dev_dependency.

**Additional context**
I started seeing this after upgrading to Flutter 3.0.0 / Dart 2.17.0.

So far I've reproduced on both Windows and macOS.

**Comment by jonasfj** [comment]
> No error when a dependency is imported in /bin/*.dart and declared as a dev_dependency.

This is not expected.

Packages used in `bin/` should **not** be `dev_dependencies`.

----

Closing as working as intended.
