### ISSUE TITLE
remove stale entries from `rules.json`

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#59176]
I'd like to remove a few things from our generated json descriptions of lint rules (https://github.com/dart-lang/linter/blob/gh-pages/lints/machine/rules.json).

Specifically, I'd like to remove:

* `"maturity"` (now state)
* `"sinceLinter"` (see: https://github.com/dart-lang/sdk/issues/59174)

@parlough, @devoncarew: do you have any idea who (if anyone) is using this file?

(I feel like I put this together for @csells a while back but can't recall how it's use has evolved...)

**Comment by csells** [comment]
no tools I know of use either of those two field, @pq

**Comment by devoncarew** [comment]
Hi - this issue just got re-pinged due to the repo transfer (https://github.com/dart-lang/linter/issues/5127).
