### ISSUE TITLE
`use_build_context_synchronously` is triggered when using `switch` statement

### ISSUE THREAD

**Issue by maRci002** [dart-lang/sdk#59260]
**Describe the issue**

When using `BuildContext` inside a switch statement, if the first case awaits an async method, the second case triggers the `use_build_context_synchronously` lint rule. However, this is a false positive.

**To Reproduce**
```dart
import 'package:flutter/material.dart';

Future<void> test(BuildContext context) async {
  if (context.mounted) {
    switch (1) {
      case 1:
        await Future<void>.delayed(Duration.zero);
        break;
      case 2:
        Theme.of(context); // Don't use 'BuildContext's across async gaps.
        break;
    }
  }
}
```

**Expected behavior**
`use_build_context_synchronously` lint works fine.

**Comment by deakjahn** [comment]
More than a year leater, still there.
