### ISSUE TITLE
It is not an error to have a constructor with the same name as the class

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#5940]
The specification (as of October 8, 2012) says:

&quot;A constructor name always begins with the name of its immediately enclosing class, and may optionally be followed by a dot and an identifier id. It is a compile-time error if id is the name of a member declared in the immediately enclosing class. It is a compile-time error if the name of a constructor is not a constructor name.&quot;

This means that this is not an error:

class C {
&nbsp;&nbsp;C.C();
}

main() {
&nbsp;&nbsp;print(new C.C());
}

I think this should be an error.

**Comment by munificent** [comment]
This would be a breaking change at this point, so it's not likely to happen.
