### ISSUE TITLE
proposal: `avoid useless conversion`

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#59487]
I changed a double to int in my program and found myself doing `toInt` on it quite a lot.

```
void foo(int i) {
  int j = i.toInt(); // the linter should warm the user here of a useless conversion
}
```
doing `toInt` on an `int`, `toString` on a `String`, `toDouble` on a `Double`

**Comment by FMorschel** [comment]
What would differ from https://dart.dev/tools/linter-rules/noop_primitive_operations?

**Comment by stephane-archer** [comment]
I wasn't aware of “noop_primitive_operations”, thank you!
