### ISSUE TITLE
`AMBIGUOUS_EXTENSION_MEMBER_ACCESS` fix doesn't trigger for methods

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#59543]
Even after https://github.com/dart-lang/sdk/issues/49489 got closed when we have a method this fix is not called.

```dart
void foo(int i) {
  0.0.foo();
  0.foo();
  i.foo();
}

extension E1 on num {
  void foo() {}
}

extension E2 on num {
  void foo() {}
}
```

Is there a specific reason for this @bwilkerson? As far as I know, methods are also members (I mean, the error does say so). I can open a CL to fix this if this is not intended.

**Comment by bwilkerson** [comment]
No, I don't know of any reason why the fix wouldn't trigger in those cases.

**Comment by FMorschel** [comment]
https://dart-review.googlesource.com/396741
