### ISSUE TITLE
[js_interop] How to handle JS definition that uses explicit default arguments

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#59568]
The new interop docs state the following for optional parameters:

```
Unlike with non-external methods, optional arguments do not get replaced with their default value, but are instead omitted.
```

See https://dart.dev/interop/js-interop/usage#parameters

However, what if the underlying definition you're using _does_ provide a default argument, which it relies on?
In Dart, default arguments have to be const, but in JS that isn't the case.

Is there any guidance on this?

Concrete example, from the Auth0 JS SDK:

```
  // JS
  public async handleRedirectCallback<TAppState = any>(
    url: string = window.location.href
  ): Promise<RedirectLoginResult<TAppState>> {
    const queryStringFragments = url.split('?').slice(1);
    
    // irrelevant code...
  }
  
  // Dart
  external Future<RedirectLoginResult> handleRedirectCallback([
    final String? url,
  ]);
``` 

I'm using Dart 3.5.3

**Comment by lrhn** [comment]
If the JS function has a default value, omitting the argument from the Dart side is exactly what you want.

I tried this in dartpad.dev:
```dart
import "dart:js_interop";

@JS()
external void eval(String text);
@JS()
external int ctr([int value]);

void main() {
  // Set up function with default value.
  eval(r"var $ctr = 0; function ctr(value = ++$ctr) { return $ctr = value; }");
  print(ctr());
  print(ctr());
  print(ctr(42));
  print(ctr());
}
```
The Dart external `ctr` function has an optional parameter with no given default, and if called without an argument, that invokes the JS function with no argument too.

**Comment by navaronbracke** [comment]
Hmm, this does seem to work locally on a new sample. So this is probably an issue on my end.
However, the package that I saw this on did use a very old language version.
