### ISSUE TITLE
proposal: `strict_top_level_inference`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#59562]
## Description

Missing top-level declaration type defaulted to `dynamic`.

## Details

Based on discussion on `always_declare_return_types`, and why it's not suitable for inclusing in the recommended set.
This is an amalgam of 2-3 other lints to hit the precisely the warnings that we would be comfortable recommending.

The lint warns about every omitted

* return type,
* parameter type, and
* variable type

of a top-level declaration or class-like-namespace-level declaration (static or instance member- or constructor declaration), which is not given a type by inference, and which therefore _defaults to `dynamic`_.

The only omitted types that _can_ be given a type by top-level inference, are those of variable declarations with initializer expressions, and return and parameter types of instance variables that override a consistent combined super-interface signature.

## Rationale

Not writing a type in these places defaults (silently) to `dynamic` which can easily hide mistakes. There is nothing wrong with having `dynamic` as a type, but it should be done deliberately, and the best way to show deliberation is to write it explicitly.

It’s a bigger issue for return types, because users are likely somewhat used to omitted parameter types meaning `dynamic`, but they may also be used to local type inference that infers return types of local functions, and may miss that top-level functions use top-level inference that does not do function return type inference.

This lint covers all the places where *top-level inference* will fail and introduce `dynamic`, including return types. _There could have been a lint only for return types, since those are more likely to be introduced by a mistaken assumption that the return type would be inferred, but the underlying problem is the implicitly inferred dynamic, so this lint aims at that problem in general._

## Kind

Guards against (silently hiding) errors.

## Bad Examples

```
var /*LINT*/ _zeroPointCache;
class Point {
  /*LINT*/ get zero => _zeroPointCache ??= Point(0, 0);
  final int x, y;
  Point(/*LINT*/ x, /*LINT*/ y) : this.x = x, this.y = y;
  /*LINT*/ closest(/*LINT*/ b, /*LINT*/ c) => 
      (a.distance(b) <= a.distance(c)) ? b : c;
  /*LINT*/ distance(/*LINT*/ other) => 
      sqrt(_sq(x - other.x) + _sq(y - other.y));
}
/*LINT*/ _sq(/*LINT*/ v) => v * v;
```

## Good Examples 

```
Point? _zeroPointCache;
class Point {
  Point get zero => _zeroPointCache ??= Point(0, 0);
  final int x, y;
  Point(int x, int y) : this.x = x, this.y = y;
  Point closest(Point b, Point c) => 
      (a.distance(b) <= a.distance(c)) ? b : c;
  double distance(Point other) => 
      sqrt(_sq(x - other.x) + _sq(y - other.y));
}
int _sq(int v) => v * v;
```

## Discussion

This lint is based on the same reasoning as the `type_annotate_public_apis`, `always_declare_return_types` and `strict_inference` lints, but is more selective in where it applies.
Each of those three lints *also* apply to some cases where omitting types isn't the same problem as it is in other places,
which makes it hard to recommend those lints in general. See below.

### Future language features

With augmentations, the lint should apply to the fully augmented declaration.

It shouldn’t matter because type inference is performed on the base expression, and later augmentations must match that type, but if augmenting declarations are allowed to omit types, effectively inheriting them from the augmented declaration, this lint should not trigger for those augmenting declarations.
The final, fully augmented, declaration will not have an implicit `dynamic`.

### Other lints

This lint intersects with:

* `always_declare_return_types`. That lint also applies to local functions, likely because it’s based on an [outdated Dart Style](https://dart.dev/effective-dart/design#do-annotate-return-types-on-function-declarations) rule which says that return types are never inferred. They actually are inferred by local inference for local functions. (And Dart Style has been updated since this was first written.)
* `type_annotate_public_apis`. Likely mostly the same, but requires type annotations on variable declarations with initializer expressions, which is one place where top-level inference does infer a type. That alone is likely why this lint isn’t enabled in the internal repository.
* `strict_inference`. Reports all places where inference fails and defaults to `dynamic`, also in local inference. While valuable, it’s not something we definitely want to enforce on all users, so it’s not a good fit for the recommended lint set.

The new lint:

* Only applies to top-level/class(like)-level declarations (like `type_annotate_public_apis`.)
* Only applies if type inference has to default to `dynamic` (like `strict_inference`, so not variables with initializers.)

The new lint *might* be able to replace some of the existing lints, if most users like the scope of this lint better.
_If possible, only one warning should be emitted in the same declaration triggers more than one of these lints._

The name of this lint looks like the strict “modes”. Those should also just be lints, there is no significant difference from a user perspective, it’s just lints that have to be written in a different place in the `analysis_options.yaml` file for no apparent reason.

Another option is to change the behavior of `type_annotation_public_apis` to match, since it's the lint that is *closest* to the new lint in scope.

**Comment by bwilkerson** [comment]
> This lint covers all the places where top-level inference will fail and introduce `dynamic`, including return types.

At first glance, it sounds like the simplest implementation is to look for any resolved type of `dynamic` where the type `dynamic` wasn't explicitly provided, but that would fail in cases where type inference is inferring a `dynamic` rather than defaulting to `dynamic`

@stereotype441 Is this information that we could get during the inference process? I'd like to avoid duplicating the logic for inference in a lint rule if possible.

> Another option is to change the behavior of `type_annotation_public_apis` to match, since it's the lint that is closest to the new lint in scope.

I don't think we have a good way to alter the behavior of a lint rule without impacting existing users of the lint rule. I'm guessing that we'll want to add a new lint in order to maintain backward compatibility.

**Comment by stereotype441** [comment]
> > This lint covers all the places where top-level inference will fail and introduce `dynamic`, including return types.
> 
> At first glance, it sounds like the simplest implementation is to look for any resolved type of `dynamic` where the type `dynamic` wasn't explicitly provided, but that would fail in cases where type inference is inferring a `dynamic` rather than defaulting to `dynamic`
> 
> @stereotype441 Is this information that we could get during the inference process? I'd like to avoid duplicating the logic for inference in a lint rule if possible.

Yeah, recording this information during the type inference process sounds like the right approach to me, and I think it would be fairly straightforward.

**Comment by srawlins** [comment]
> The only omitted types that can be given a type by top-level inference, are those of variable declarations with initializer expressions, and return and parameter types of instance variables that override a consistent combined super-interface signature.

I looked in the GOOD examples and BAD examples for these cases, but did not find any 😄 . In particular, I don't know what a "_consistent_ combined super-interface signature" is (or conversely, what an "_inconsistent_ combined super-interface signature" is).

Also, off the top of my head, would this include extension type representation variables?

It looks like this _doesn't_ flag any parameter types or return types in function types? E.g. `typedef T = Function({one, two});` Similarly for record types? E.g. `typedef T = ({one, two});`

**Comment by srawlins** [comment]
As far as implementation, I think it is going to be easier to take the same approach as `always_specify_types`. The implementation can be purely syntactic, plus considerations for overrides:

* For top-level variables and functions, constructors, and static fields and methods:
  * Is there a type at an expected position? If yes, it's good.
  * If no, is there an initializer (for variables)? If yes, it's good. If no, report lint.
* For instance fields and methods:
  * Is there a type at an expected position? If yes, it's good. 
  * If no, is there a consistent combined super-interface signature? If yes, it's good. If no, report lint.

The correction that needs to be made must take into consider various keywords; if `var` is present, then the type must _replace_ the keyword. If `final` is present, then the type must _follow_ the keyword. If there are multiple variables being declared, some without initializers, then the fix is possibly to split the declaration list. `always_specify_types` takes care to report the correct thing.

**Comment by stereotype441** [comment]
@srawlins just to make sure we're on the same page here, note that the analyzer's top-level type inference logic already figures out, for instance fields and methods that aren't explicitly typed, whether there is a consistent combined super-interface signature. (It has to, because computing that signature is part of the type inference process). So when you say "If no, is there a consistent combined super-interface signature?", I hope your intention is to answer this question by consulting some information that was recorded by the analyzer during the type inference process, rather than duplicating that logic inside the linter. It would be a shame to duplicate the logic and then have it get out of sync as future language improvements are made.

**Comment by scheglov** [comment]
It should be easy to set a flag on the element at the point where the summary linker sets `dynamic` type when inference otherwise cannot produce anything better.

**Comment by bwilkerson** [comment]
> It would be a shame to duplicate the logic and then have it get out of sync as future language improvements are made.

Agreed. That's my primary concern here (and the reason I asked about getting this signal from inference. As type inference evolves I want the lint to evolve with it without the need for the lint to be modified.

**Comment by srawlins** [comment]
SGTM. This is probably the same point at which the analyzer decides to report 'strict-inference' warnings.

**Comment by srawlins** [comment]
Is an omitted parameter type or return type in a method/field that has an _inconsistent_ combined super-interface signature illegal? Always? The analyzer seems to report this as `NO_COMBINED_SUPER_SIGNATURE`. is the "consistent combined super-interface" consideration just to avoid double reporting?

**Comment by lrhn** [comment]
I think it is always an error if an instance member declaration omits *any* return or parameter type, and the super-interfaces do not have a valid combined super-interface member signature for that member.
(Probably except return types of setters, which we ignore since they have to be `void` anyway, so they're always consistent.)

Which means that for the linter, it's probably not something it has to worry about, an error will have occurred before if there are super-members, they are needed, and they don't have a consistent combined signature.

The linter can just check if a subclass declaration has no declared type, and there is *no* super-interface member, or there is no super-interface declared parameter for a particular parameter.

Example:
```dart
abstract interface class I1 {
  Object foo(int x);
} 
abstract interface class I2 {
  String foo(num x);
} 
class C implements I1, I2 {
  String foo([x = 0, y = 0]) => throw 0;
}
```
In this case, the combined member signature is `String Function(num)`, which doesn't introduce any type for `y`.
You can see that by looking at all the super-interfaces and seeing that they have no second parameter, without needing to find the combined member signature.

That means that `y` gets the default type of `dynamic`, since it cannot inherit a type. That's what should be linted.

So:
* Lint if an instance function/getter has no return type, and there is no declaration for it in any super-interface.
* Lint if an instance function/setter has no parameter type for a parameter, and there is no declaration for that parameter in any super-interface.

There being no declaration for a parameter can be because there is no declaration for the member at all, or because none of those declarations have a parameter with that position or name (and it's going to be optional in the subclass).


(I think our "combined super-interface member signature" algorithm is a little stupider than necessary, since it can't handle
```dart
abstract interface class I1 {
  String foo(int x, [int z]);
} 
abstract interface class I2 {
  String foo([num x]);
} 
class C implements I1, I2 {
  String foo([x = 0, y = 0]) => throw 0;
}
```
The combined signature *could* be `String Function([num x, int z])`.)

**Comment by lrhn** [comment]
> Also, off the top of my head, would this include extension type representation variables?

Those cannot omit types at all, so no.

> Can a wildcard parameter have an omitted type?

I'd say no. This is not about having a type inside the function, so whether the parameter can be referenced or not doesn't matter. It's about making sure that the parameter has a type in the API, and doesn't default to `dynamic`.

It's all about not defaulting to `dynamic` because nobody wrote a type anywhere, while still allowing `dynamic` if you ask for it.

Which means you can probably completely avoid looking at any declaration which has no `dynamic` in its signature, or that has explicit types declared everywhere. 
Then, as you say:
* If a variable declaration has an initializer, it's OK to infer from that.
* If an instance variable declaration has an inherited super-declaration for getter or setter, I think it inherits from those. Somehow.
* If an instance method, getter or setter has super-declaration (and no error has happened yet, so if there is more than one, they're consistent), and every parameter occurs in a super-declaration, then you can assume that type were inherited, without caring how or what those types are.
* Otherwise there is a declaration with no explicit type, with no way to get a type from context, and with a value of `dynamic` which it (certainly?) defaulted to. This is where it should lint.
