### ISSUE TITLE
dart-sdk's c++ guidelines (not google's general ones) ,like no-exceptions

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#59589]
hi ,

are there any guidelines for sdk engineers ,regarding :
- programming practices ,and
- lang. features to avoid ,like c++'s exceptions ,`shared_ptr` ,etc.
- not `web://github/google/styleguide/cppguide`

because im planing to create a new lua-like embed-able scripting lang.
  ,so considering forking dart's impl. ,then massively removing the un-necessary code

thanks

**Comment by mraleph** [comment]
In general we follow a fusion of 

* https://google.github.io/styleguide/cppguide.html
* https://chromium.googlesource.com/chromium/src/+/main/styleguide/c++/c++.md
* Plus some Dart VM specific rules: e.g. avoiding depending on STL containers and algorithms - though we have been a bit more lax about this recently. 

Things not written in Google C++ Style Guide is mostly enforced through code review and not written anywhere, AFAIK.
