### ISSUE TITLE
`pkg/dds/test/log_history_size_gigantic_test` is timing out on `unittest-asserts-release-win-arm64`

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#59597]
The tests
```
pkg/dds/test/log_history_size_gigantic_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win-arm64
```

https://dart-ci.appspot.com/log/pkg-win-release-arm64/unittest-asserts-release-win-arm64/3383/pkg/dds/test/log_history_size_gigantic_test

**Comment by derekxu16** [comment]
I was unable to reproduce this on my Windows x86-64 machine.

**Comment by a-siva** [comment]
Probably the test needs to be skipped on Windows arm64 configuration.
