### ISSUE TITLE
Unexpected build error with `extension type` and `nonNulls`

### ISSUE THREAD

**Issue by arnaud-secondlayer** [dart-lang/sdk#59598]
This build error is reproduced on `https://dartpad.dev` with version 3.5.4.

```
extension type Int(int i) {}

void main() {
  final a = [Int(0), null].nonNulls;
}
```

Error:
```
The getter 'nonNulls' isn't defined for the type 'List<Int?>'.
```

**Comment by lrhn** [comment]
Seems correct. 
The `nonNulls` extension is defined as
```dart
Extension SomeName<T extends Object> on Iterable<T?> {
  Iterable<T> get nonNulls {…}
}
```
The type `Int` is not a subtype of `Object`, and the list type is `List<Int?>`, so the compiler cannot find a type for `T` that satisfies the requirement. 

Try adding `implements Object` to the `extension type Int`.

**Comment by arnaud-secondlayer** [comment]
I still think the behavior is quite confusing and is an unnecessary limitation to `extension type`.

This builds:
```
void main() {
  final ints = [0, null].nonNulls;
  final strings = ['hello', null].nonNulls;
}
```

This doesn't build:
```
extension type Int(int i) {}
extension type StringExt(String s) {}

void main() {
  final ints = [Int(0), null].nonNulls;
  final strings = [StringExt('hello'), null].nonNulls;
}
```
