### ISSUE TITLE
Bridging Dart Exceptions with Isolates: Addressing the Incompatibility

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#59608]
When exploring the Dart standard library, it becomes evident that exceptions are the primary mechanism for handling errors. This approach works seamlessly in most scenarios—until you introduce isolates into the equation. Isolates rely on values to handle errors, creating a dissonance between the two paradigms.

This mismatch forces developers to write wrapper functions to convert exceptions into value-based errors to make them compatible with isolates. This process can be tedious and introduces unnecessary complexity, especially when working with existing Dart codebases.

A potential improvement would be enabling isolates to propagate exceptions back to the sender. This enhancement could significantly reduce the friction caused by this inconsistency, allowing for a more harmonious interaction between isolates and Dart's standard error-handling mechanisms.

Currently, this disconnect makes it cumbersome to leverage isolates effectively within Dart, particularly in projects that depend on exception-driven error handling.

**Comment by lrhn** [comment]
> Isolates rely on values to handle errors, creating a dissonance between the two paradigms.

Isolates rely on sending objects (errors are objects too) to communicate *anything* between different isolates.
Exceptions are control flow based. you throw them and they unwind the control flow stack until they are handled, or until reaching the top level where they too are treated as objects. (Asynchronous errors are also just objects until they are re-raised using an `await`.) 
Different isolates do not share any control flow, so they can't communicate using thrown objects. So, yes, isolates communicate objects, by necessity.

What do you *suggest* to do?

The current `Isolate.run` does communicate errors back as as asynchronous errors in the returned future.

It's definitely possible to run a computation that returns a `Stream` in a different isolate and communicate back the events and errors. (The biggest question is whether to use messages or `Isolate.pause`/`Isolate.kill` for push-back, the rest is basic.)

**Comment by stephane-archer** [comment]
@lrhn I have limited knowledge of Isolate so I might be doing something wrong.

I have a function `Fibonacci` that can throw errors.
I have a list of numbers that are all messages for `Fibonacci`
I want all of these computations to run in parallel so on different Isolte
``` Dart
List<Future> futures;
for (var message in messages) {
   var future = compute(Fibonacci, message);
   futures.add(future);
}
try {
results = Future.wait(futures)
} catch (e) {
    print("I lost everything if one fail!") 
}
```
from my understanding if one of the Fibonacci calls throw I lose everything
I don't know any good way to `await` multiple futures and have a list of results and a list of failures on the other side.

My really ugly solution is wrapping Fibonacci into:
``` Dart
(int result, String error) FibonachiWithoutException(int message) {
try {
     return Fibonachi(message), null
} catch(e) {
   return 0, e.toString();
}
}
```
so I have a list of results and I can check if it's an error or a value (really golang style)

removing the need for `FibonachiWithoutException` is what I want

**Comment by lrhn** [comment]
This doesn't seem to be about isolates, just got to combine multiple synchronous results. 

You have a number of futures, where done may contain errors, and you want to combine those into a single result, somehow, that represents all of the results.

If you change `await Future.wait(futures)` to `await futures.wait` then you're a big step closer. The [`.wait`](https://api.dart.dev/dart-async/FutureIterable/wait.html) extension operation on a `List<Future<T>>` will return a `Future<List<T>>` with all the results if nothing throws, or will throw a `ParallelWaitError<List<T?>, List<AsyncError?>>` which will contain the results split into errors and values (with a `null` at a position if the result of that future is in the other list).

Then you have all the results, and can decide how you want to continue with those.

**Comment by stephane-archer** [comment]
@lrhn thanks for your great answer!

> This doesn't seem to be about isolates, just how to combine multiple synchronous results.

`await compute(Fibonacci, message);` would result in no parallelism regarding computing values.
And from my understanding, because of exceptions, you should always `await` at the same time, all the future you have access to. 

Because of this, I came up with this solution, but it's more about, "How to compute multiple values in parallel using Dart Isolate?"

I don't care about having all the results all at once, I would much prefer to get their results as soon as they are finished (with some clue of which message has been sent to them preferably) so I can show a progress indication for example or move to the next steps for those fast to compute values.

Do you see any more relevant way to compute multiple values in parallel?
I imagine some streams might be useful.

**Comment by stephane-archer** [comment]
``` Dart
class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return DropTarget(
      onDragDone: _processDroppedFiles,
      child: Text("Hello world"),);
    }

  Future<void> _processDroppedFiles(DropDoneDetails dropDoneDetails) async {
    var pool = IsolatePool(4);
    await pool.start(); // never returns
    ... try to use the pool to work in parallel on the files
    }
}
```

**Comment by lrhn** [comment]
You'd have the same issue here if `compute` started asynchronous computations in the same isolate, that run by interleaving instead of concurrently. You have a number of futures created at the same time, where you need to listen to the futures immediately (that's correct), and want to get the results when they're ready. 

I would use a steam for that, if you don't need to know by the original order of the futures.

**Comment by stephane-archer** [comment]
@lrhn Thanks again for this great explanation,

You are right that my issue was not about Isolates but what was the correct way to generate as many future as possible (concurent computation) while still beieng able to `await` them properly. 

I'm not used to the `future.then` syntax and always use the `await` syntax instead but I just realize that they have totally different behavior! one is blocking while the other is not (that's really surprising to me, I was really thinking they were equivalent)

Let's take your example:
``` Dart
// Nothing to do on `.onListen`/`onCancel`/`onPause`/`onResume`, can't stop the computations anyway.
var controller = StreamController<int>(sync: true);
var onValue = controller.add;
var onError = controller.addError;
for (var message in messages) {
   var future = compute(Fibonacci, message);
   future.then(onValue, onError: onError);
}
var results = controller.stream;
```
if I was using `await` this would not behave the same!
```Dart
var controller = StreamController<int>(sync: true);
var onValue = controller.add;
var onError = controller.addError;

Future<void> processMessages() async {
  for (var message in messages) {
    try {
      var result = await compute(Fibonacci, message); // It will only compute one at a time here!
      onValue(result);
    } catch (error) {
      onError(error);
    }
  }
}
var results = controller.stream;
```

Do you see any elegant equivalent using `await`, the `await futures.wait` is much less elegant than the `future.then` option.

I didn't knew it was doing different thing... how would you choose between when to use `await` vs the `future.then` syntax?

**Comment by lrhn** [comment]
An `await` blocks a function call and waits for *one* future. It works as if it was calling a `.then` (because it is) with a callback that is the *entire rest of the current function invocation*, the "continuation" of the computation.

Since, as you pointed out above, you should do *something* to a future immediately, if the only thing you use is `await`, you'll immediately block and wait for that one future, and only continue when that asynchronous computation completes.
That makes your program *single-threaded*.

If you want to have concurrent computations, you need to do something other than just `await`'ing every future.

You don't have to use `.then`, you can also use `async`/`await` and just not await one of the futures.
For example changing the loop above to:
```dart
  ...
  void receiveResult(Future<T> future) async {
    try {
      controller.add(await future);
    } catch (e, s) {
      controller.addError(e, s);
    }
  }
  for (var message in messages) {
     var future = compute(Fibonacci, message);
     receiveResult(future); // Runs asynchronously, but is not awaited.
  }
 ...
```

There are many ways to run things in parallel, but they all require not immediately `await`'ing some future,
or using event kinds other than future completion (timers, streams, etc.)
Or just collecting a bunch of futures and using `await [bunch, of, futures].wait` to wait for all of them at once.

Which strategy to use depends on how you need the results.

**Comment by stephane-archer** [comment]
thanks, @lrhn, our conversation was eye-opening to me.

Of all the strategies discussed, I think I like the most `future.then` because the elements are treated one by one as opposed to `await [bunch, of, futures].wait` and I'm not a fan of running async code without `await` because it can't throw (until I can because you change it later)
