### ISSUE TITLE
[cfe] `dart compile kernel  --depfile` does not include `package_config.json`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#59637]
Steps to reproduce

```
dart compile kernel --packages=path/to/package_config.json --output=xyz.dill --depfile=xyz.dill.d xyz.dart
```

Expected result:

`xyz.dill.d` contains `path/to/package_config.json`

Actual result:

`xyz.dill.d` contains only the list of `.dart` files.

@johnniwinther @jensjoha @chloestefantsova Is the omission of the package_config intentional or an oversight? The kernel compilation would most likely need to be rerun when the contents of the file passed in `--packages` changes.

**Comment by johnniwinther** [comment]
I think it's an oversight.

**Comment by jensjoha** [comment]
I think the thing was introduced in https://github.com/dart-lang/sdk/commit/9f4f0acb9e01b73b27658baa6d7b00319f4faa4e --- and has seemingly always been by taking component.uriToSource.keys which is only the dart files.

As this is not really a CFE feature but a VM one I can't speak to whether this is by design or not.

If you want something more you should give the file system a tracker:
```
  FileSystemDependencyTracker tracker = new FileSystemDependencyTracker();
  compilerOptions.fileSystem = StandardFileSystem.instanceWithTracking(tracker);
```

which records everything read through the file system object, e.g.

```
$ out/ReleaseX64/dart pkg/front_end/tool/deps.dart hello.dart
$ cat hello.dart.dill.d
hello.dart.dill: \
  .dart_tool/package_config.json \
  hello.dart \
  out/ReleaseX64/vm_platform_strong.dill
```

**Comment by dcharkes** [comment]
Thanks @jensjoha!

> which records everything read through the file system object, e.g.
> [...]
> `vm_platform_strong.dill`

If we'd go that way, you'd also have to report the Dart executable itself. Or basically anything that influences when Dart changes instead of the program sources. (Which we do need to do in the context of the work in https://github.com/dart-lang/native/issues/1770, but we don't want to go and content-hash the `dart.exe` all the time, instead we'd like to rely on the `version` file. @mkustermann)

So I think we can safely say that this feature is meant to track the sources of the program, not the version of Dart.

I don't see any obvious uses in the Flutter Tools or Dart SDK that would break by adding the package_config.json to the DEPS, so let me make a PR to do that.

**Comment by dcharkes** [comment]
@jensjoha What are your thoughts about the `KernelCompilationResults` reporting which `packages_config.json` it discovered on the file system?
