### ISSUE TITLE
Failures on vm/dart_2/isolates/closure_entrypoint_test/3

### ISSUE THREAD

**Issue by jyameo** [dart-lang/sdk#59645]
There are new test failures on [[vm/dart_2/isolates/closure_entrypoint_test/3] caused by Roll co19 to d50a305d1b4455b4e72ba45a2cf2ab1c37004bc6](https://github.com/dart-lang/sdk/commit/bb1de17551dc3c9b2b97914d00f1cf12f2a56174).

The tests
```
vm/dart/isolates/closure_entrypoint_test/3 Crash (expected Pass)
```
are failing on configurations
```
vm-aot-tsan-linux-release-x64 
vm-appjit-linux-product-x64
```

[LOGS](https://dart-ci.appspot.com/log/vm-aot-tsan-linux-release-x64/vm-aot-tsan-linux-release-x64/652/vm/dart/isolates/closure_entrypoint_test/3)

**Comment by rmacnak-google** [comment]
Same cause as #59632
