### ISSUE TITLE
Type unexpectedly inferred as "Object" in "return x ? y : z"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#59667]
While working in the analyzer, I got this analysis error:

![image](https://github.com/user-attachments/assets/e55a6966-eb48-4d85-a40d-9a026490a257)

For some reason, the inferred type is `Object`. If I change `this` to `this as Element2` then the error goes away:

![image](https://github.com/user-attachments/assets/a6f83917-8067-4343-b1c6-fb545e0042de)

However, if I rewrite the code using if/else, there is no problem without the cast:

![image](https://github.com/user-attachments/assets/73ccfb02-3319-460a-a233-a1782f8efc0f)

As far as I can tell, these are functionally the same?

The class `ConstructorElementImpl2` is an `Element2` via this chain: `ConstructorElementImpl2 extends ExecutableElementImpl2 extends FunctionTypedElementImpl2 extends TypeParameterizedElementImpl2 extends ElementImpl2 implements Element2`.

**Comment by eernstg** [comment]
The feature known as ['inference-update-3'](https://github.com/dart-lang/language/issues/1618) was enabled in Dart 3.4.0, does your tool chain have that? Otherwise, that might make the typing succeed &mdash; it's very much about improving the type of conditional expressions.

**Comment by DanTup** [comment]
Ah, that's it. The analyzer package is still on 3.3, and if I change it to 3.4 the error indeed goes away. Thanks for the explanation!
