### ISSUE TITLE
Mirror https://github.com/dart-lang/io on dart.googlesource.com

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#59673]
Package test_core depends on package io, so it should be included in the DEPS.

**Comment by parlough** [comment]
Should it instead move to https://github.com/dart-lang/core which is already mirrored? It seems the other core library utility packages have already moved there.

Or https://github.com/dart-lang/tools.

**Comment by sigurdm** [comment]
Yeah - that would work as well

**Comment by mosuem** [comment]
It will move to `dart-lang/tools` soon.

**Comment by sigurdm** [comment]
In that case I'll close this issue!

**Comment by devoncarew** [comment]
> Should it instead move to https://github.com/dart-lang/core which is already mirrored?

👍 - good idea
