### ISSUE TITLE
 This is a 3 years old flutter project and i keep facing huge amout of errors.

### ISSUE THREAD

**Issue by MoaazELDemery** [dart-lang/sdk#59691]
This is a 3 years old flutter project and i keep facing huge amout of errors because the used packages most of them are not supported any more and the sdk version i got requires null safety but the packages do not offer null safety versions. Even after deleting them off i faced .gradle version errors.  So if someone can help i would be so much appreciated.
"The current Dart SDK (3.5.4)"

version: 1.0.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  hijri: ^2.0.3
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  localize_and_translate: ^4.0.1
  audioplayers: ^0.19.1
  youtube_player_flutter: ^8.0.0
  share: ^2.0.4
  advance_pdf_viewer: ^2.0.0
  splashscreen: ^1.3.5
  flutter_html: ^0.8.2
  webview_flutter: ^2.0.9
  flutter_advanced_drawer: ^1.2.3
  auto_size_text: ^2.1.0
  url_launcher: ^6.0.9
  provider: ^5.0.0
  overlay_support: ^1.2.1
  internet_connection_checker: ^0.0.1+2
  connectivity_plus: ^1.1.0
  fluttertoast: ^8.0.8
  scrollable_positioned_list: ^0.2.2
  shared_preferences: ^2.0.7
  sqflite: ^2.0.0+4
  path_provider: ^2.0.4
  path: ^1.8.0
  flutter_paginator: ^0.0.6
  syncfusion_flutter_pdfviewer: ^19.3.55-beta

repo link:
[https://github.com/MoaazELDemery/AboElazayem_old](url)

**Comment by julemand101** [comment]
This is the issue tracker for the implementation of the Dart language and Dart SDK and should be used for feature requests and issues for Dart itself (and related first party components) and not third party programs, packages or apps.

It should not be considered a forum or a place where you can ask for help with your projects.

Please seek the community options listed here for getting general help about your project: https://flutter.dev/community#community-grid
