### ISSUE TITLE
Instead of new FEATURES, focus on 8K+ issues and minor issues on GITHUB, and reply to each GITHub Issue

### ISSUE THREAD

**Issue by fisforfaheem** [dart-lang/sdk#59700]
Dart needs so many fixes that, instead of adding new features, I think you should focus on the 5K+ bugs and minor issues posted on GitHub and reply to each GitHub issue.

**Comment by FMorschel** [comment]
I've been fixing things myself and I'm not in any way related to the Dart team (see here https://github.com/dart-lang/sdk/commits?author=FMorschel - there are also new things I made like `Go to Imports`). You can always help. 

The SDK is mostly written in Dart so you only need to understand the project to start and the team is really helpful. I disagree and I'd prefer they make new things for us and we can help them make everything work the best way we can.

There is only so much you can do with limited time (and a single team) and bugs will always show up.

**Comment by julemand101** [comment]
@fisforfaheem This issue tracker are used for multiple components related to Dart and also includes features and subtasks for those features. It is not really fair to say that all 5k issues are actual issues in the software.

Also lot of GitHub issues are suggestions and discussions topics. Some of this are planned as potential upcoming features and therefore the issues are not closed.

Do you have any specific examples of issues that should be prioritized in your opinion? Also, as @FMorschel also mention, you are welcome to take part in fixing issues (start with more simple ones).

**Comment by fisforfaheem** [comment]
I believe the dart analyzer can be improved, also dart Analysis server has become slower and very unreliable.


I think team should focus on making dart lint's, analyzer and other related hints and hover info better and super low latency instead of new language features for some months.

**Comment by FMorschel** [comment]
If you want any help with how to start to contribute, feel free to contact me privately or tag me in an issue or on Discord or whatever (same nickname). What I did: posted some issues, and when I got them closed, I looked at the implementations and started doing the same kinds of changes for other people's issues I found similar to mine. Now I understand the broad context around the changes I made and can implement other fixes.

**Comment by fisforfaheem** [comment]
Actually I am a front end developer and use flutter sdk, not dart directly 

Also can the team add those recent fixes and latency fixes to latest flutter sdk release

**Comment by FMorschel** [comment]
@fisforfaheem, you can use the beta/main (master on Flutter) channels for new changes faster. But you also can look for improvements you really need and ask them to CP (cherry pick) those commits for the stable version (thats why you get the last number with the versioning e.g. 3.6.1 <- bug fix)

**Comment by mraleph** [comment]
Thanks for your input.
