### ISSUE TITLE
The eol_at_end_of_file lint reads file content from disk and can slow down linting

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#59704]
Splitting this out of https://github.com/dart-lang/sdk/issues/55281#issuecomment-2519977056 so it doesn't get lost.

This lint reads the content in a way that appears that it can hit the disk and can be quite slow when analyzing a lot of files (or a large library):

https://github.com/dart-lang/sdk/blob/33bdacc604f09199d5b89685ea4c0de8a91833e7/pkg/linter/lib/src/rules/eol_at_end_of_file.dart#L38

One simple option suggested by @bwilkerson was:

```
    var unitContext =
        context.allUnits.firstWhereOrNull((unit) => unit.unit == node);
    var content = unitContext.content;
```

And @scheglov:

> And yes, I think `registerNodeProcessors()` should have access to the current `LintRuleUnitContext` instance. Currently it knows all units of the library, and its defining unit, but not the current.

I had a quick look at this, but I am a little confused by `LinterContext.definedUnit` because it seems like there is code that passes each individual unit in for it. For example this call here happens inside a loop for all units within a library (called `currentUnit`):

https://github.com/dart-lang/sdk/blob/0d72db1b8866c647602a02064c8ce948b7744cc8/pkg/analysis_server/lib/src/services/correction/bulk_fix_processor.dart#L293

And then `currentUnit` is passed as `definingUnit`:

https://github.com/dart-lang/sdk/blob/0d72db1b8866c647602a02064c8ce948b7744cc8/pkg/analysis_server/lib/src/services/correction/bulk_fix_processor.dart#L557

So I wonder whether `definingUnit` could just be rename and repurposed as `currentUnit` or whether any lints really do need/want the defining unit?

**Comment by bwilkerson** [comment]
I don't know whether any of the existing lints need the defining compilation unit. If there are any, then at least some of them are likely using it to get to the imports and that logic will need to be changed to support enhanced-parts. The only way for me to find the answer to that question would be to look at all uses of `definingUnit` and try to determine why it's being used.
