### ISSUE TITLE
dart fix is broken after the latest flutter stable release

### ISSUE THREAD

**Issue by benthillerkus** [dart-lang/sdk#59707]
Running dart fix now seems to apply the same fix multiple times.

Examples:
- missing `const`-> `const const const`
- trailing commas -> `,,`
- missing `override` -> `@override\n@override`

I can reproduce this on macos 15.0.1 (24A348)
```

Flutter 3.27.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8495dee1fd (2 days ago) • 2024-12-10 14:23:39 -0800
Engine • revision 83bacfc525
Tools • Dart 3.6.0 • DevTools 2.40.2
```

and in our CI on GitHub Actions (Ubuntu 22.04)

```
Flutter 3.27.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 495dee1fd (2 days ago) • 2024-12-10 14:23:39 -0800
Engine • revision 83bacfc525
Tools • Dart 3.6.0 • DevTools 2.40.2
```

Invocation:
```sh
dart fix --apply --code=require_trailing_commas,unused_import,unnecessary_import,annotate_overrides,prefer_const_constructors,use_super_parameters
```

**Comment by pq** [comment]
@FMorschel : Thanks for taking a look! Out of curiosity, did you try this with the `--code` command line option?

**Comment by FMorschel** [comment]
Yes, I did (his full command). Also with both a missing const and override so it would need to trigger two things. 

Didn't try all of his errors so there may be something in any of the others?

**Comment by pq** [comment]
Perfect. Thanks!

@benthillerkus: any tips you can provide to help us reproduce would be fantastic.

**Comment by benthillerkus** [comment]
The issue seems to be related to part directives

https://github.com/benthillerkus/dart_fix_repro

**Comment by FMorschel** [comment]
https://github.com/dart-lang/sdk/issues/59572

**Comment by benthillerkus** [comment]
Yeah, seems to be the same issue
