### ISSUE TITLE
"InternalError: No batch result object ID" error when inspecting getters

### ISSUE THREAD

**Issue by Reprevise** [dart-lang/sdk#59766]
I'm using VSCode, Dart 3.6.0 (Flutter 3.27.1) and sometimes when debugging I get `InternalError: No batch result object ID.` errors instead of the computed getter values. This is happening when making a Flutter web app.

![image](https://github.com/user-attachments/assets/2a2900c2-9e5b-4999-bae2-f700d92bd140)

**Comment by biggs0125** [comment]
Hi @Reprevise, would you mind including a code snippet where you've run into this to help us reproduce the issue?

**Comment by Reprevise** [comment]
Hi @biggs0125. I can reproduce the problem in this code sample:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  Iterable<int> _numbers() sync* {
    for (var i = 1; i <= 10; i++) {
      yield i;
    }
  }

  @override
  Widget build(BuildContext context) {
    final _ = _numbers();

    return MaterialApp(
      title: 'Sample App',
      home: const Column(
        children: [
          Text('Sample'),
        ],
      ),
    );
  }
}
```

**Comment by biggs0125** [comment]
Marking as closed and tracking fix in https://github.com/dart-lang/webdev/issues/2551
