### ISSUE TITLE
Setting of super.named parameter is recognized as unused or incorrect

### ISSUE THREAD

**Issue by ChaserVasya** [dart-lang/sdk#59792]
# Snippet
```
class A{
  final bool b;

  A({this.b = false});
}


class _B extends A{
  _B({super.b = true});
}

class _C extends A{
  _C(): super.b = true;
}

void fn(){
  _B(); 
  _C();
}
```

# What I want
I want to avoid `_B({b: true})` when I can set in constructor and to pass analyzer lints

# Problem
B.b: is unused. (Okay. It looks like expected. But it has not hotfix by analyzer and I create hotfix as `_C` class)
C.b: error:` 'b' isn't a field in the enclosing class`.

<img width="441" alt="Снимок экрана 2024-12-22 в 14 42 53" src="https://github.com/user-attachments/assets/767ddc30-2be9-4fa1-ad91-7781d6d02792" />

# Version
Dart SDK version: 3.5.4 (stable) (Wed Oct 16 16:18:51 2024 +0000) on "macos_arm64"

**Comment by incendial** [comment]
For `C` this should work:

```dart
```

**Comment by lrhn** [comment]
The code is recognized as incorrect. It is incorrect, the syntax, `super.id = e` in an initializer list, is not allowed, and it's not even clear what it should mean. 
It looks like it assigns a value to a superclass instance variable, but that's not allowed and likely never will be. It breaks abstraction to rely on a superclass implementing a getter using an instance variable. The subclass only less that the superclass has a getter and a constructor parameter, the rest is implementation details.

It can mean passive the expression's value to the super-constructor parameter of the same name, but that's not how you pass parameters (and even if it was made to work, it won't work with positional parameters).
If that's what you want, the syntax is `_C(): super(b: true);`.
