### ISSUE TITLE
@immutable should be moved to flutter sdk?

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#59803]
### Use case

``` Dart
import 'package:flutter/material.dart';

@immutable
class Resolution {
  final int width;
  final int height;
  const Resolution(this.width, this.height);
  double get aspectRatio {
    return width / height;
  }
}
``` 

immutable is not related to material app. I think the immutable annotation should be located somewhere else. Maybe it can be part of the dart SDK? I don't see how this is Flutter-specific.

### Proposal

move @immutable

https://github.com/flutter/flutter/issues/160820

**Comment by bwilkerson** [comment]
The annotation is defined in [`package:meta/meta.dart`](https://github.com/dart-lang/sdk/blob/main/pkg/meta/lib/meta.dart#L174), which is in the sdk repository. It is exported by [`package:flutter/foundation.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/foundation.dart#L15).
