### ISSUE TITLE
Add @protected metadata (annotation)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#6119]
This is in the spirit of issue #3.

Think of it as a sister to @­override.

1) Like other metadata/annotations: zero effect on runtime semantics. Purely for tooling.
2) Calls/References to such members outside of the class and subclasses yield warnings in tools

**Comment by pq** [comment]
This is now in the `meta` package.  See: https://github.com/dart-lang/sdk/issues/25841.
