### ISSUE TITLE
assert should take an optional message

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#6190]
Currently the assert statement cannot provide any runtime information about what went wrong. Adding an addition message argument to the assert statement could provide such runtime information. For instance

assert(foo.isBar(), '$foo is not Bar');

could provide runtime information about the particalur foo instance that failed and not only, as now, that some foo instance failed. Such additional information would be valuable in debugging failed assertions.

**Comment by sethladd** [comment]
@lrhn what do you think about this request?

(A customer asked to be able to add a message to assert.)

**Comment by lrhn** [comment]
It's a language change, not a library change, so if anything, it should be a DEP proposal.

I think there's a reason nothing has been done on this in almost three years - it's not that important.
I'm personally split on whether it's even a good idea.

The simple work-around is to use assert with a function:
```dart
assert(() => test || throw "message");
```

**Comment by sethladd** [comment]
Thanks for the feedback. If we don't plan to do this, let's close the issue.

**Comment by gramster** [comment]
You could possibly make the argument that Dart is mature enough now to not need things like language-level assert, but that's probably a non-starter.

**Comment by Hixie** [comment]
FWIW, we use asserts extensively in our library, to help users of our library understand when they are violating our library's contract. We would love to be able to direct users of our library to documentation when they hit an assert; currently the asserts aren't very actionable. Making them throw a message is certainly one option we will consider in the meantime.

**Comment by sethladd** [comment]
DEP proposal created: https://github.com/sethladd/dep_assert_with_optional_message/blob/master/proposal.md

**Comment by jxson** [comment]
Wanted to ping this thread to see what the status is. I have been using asserts in a similar manner to Flutter and would like to pass some actionable messages to users when runtime assertions fail.

**Comment by zoechi** [comment]
@jxson see #27154

**Comment by jxson** [comment]
@zoechi Thanks for the pointer, watching that issue now.

**Comment by munificent** [comment]
We're doing this now. Tracking it here: #24213.
