### ISSUE TITLE
Const typed data (Int8List, et al.)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#6378]
e.g:

const Int8Array int8 = const [10, 100];

does not work, instead we need to write code as follows:
Int8Array initInt8Array() {
&nbsp;&nbsp;var list = new Int8Array(2);
&nbsp;&nbsp;list[0] = 10;
&nbsp;&nbsp;list[1] = 100;
&nbsp;&nbsp;return list;
}
Int8Array int8 = initInt8Array();

We should try and make it possible to initialize constant scalar lists
similar to how we initialize all lists.

**Comment by munificent** [comment]
Not unreasonable, but not planned either. The set of classes and operations that could be usefully made const is potentially unbounded and it's hard to decide what makes the cut and what doesn't. At least for now, we don't have any intention of including typed_data's types in it.

**Comment by truongsinh** [comment]
any update for const typed data, is it still unplanned for the time being?

**Comment by lrhn** [comment]
There are still no current plans.

**Comment by truongsinh** [comment]
So `const a = [4,3,5]` and `final b = Uint8List.fromList([4,3,5])` which one is more preferred, or does it depend on scenarios? I understand that the reason we have typed data in the first place is for performance (time and space), but I assume having a compile-time const also has it's advantages.

**Comment by truongsinh** [comment]
@munificent @lrhn  any recommendation for performance junkies?

**Comment by lrhn** [comment]
For performance, I'd definitely go with:
```dart
final b = Uint8List(3)..[0] = 4..[1] = 3..[2] = 5;
```
If I could trust the compiler to optimize `Uint8List.from(listLiteral)`, then that would be nice. Until then I'd avoid the extra allocation and iteration.

Creating and populating a `Uint8List` increases code-size. 
A const list may or may not increase code size or memory pressure, depending on how it's implemented.

Also consider:
```dart
final b = "\x04\x03\x05].codeUnits; 
```
:imp:
