### ISSUE TITLE
dart2js --watch

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#6478]
Would be great to have a --watch option for dart2js command-line tool. I don't want to run it manually all the time.
////////////////////////////////////////////////////////////////////////////////////
Editor: 13679 (2012-10-16)
OS: Mac OS X - x86_64 (10.8.2)
JVM: 1.6.0_35

SDK installed: true
Dartium installed: true

**Comment by dgrove** [comment]
If we did this, it wouldn't be part of dart2js.
