### ISSUE TITLE
dart2js: should provide a complete implementation of dart:mirrors at runtime

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#6490]
In r14469 we stubbed out some of how runtime mirrors can work in dart2js.

There are great technical challenges to overcome in implementing mirrors for dart2js, and we expect there wil be a non-trivial overhead for the most general usages.

At the time of writing, mirrors for are not being actively developed as the dart2js team is focusing on performance and language feature completeness. But patches are welcome!

**Comment by sigmundch** [comment]
we are now tracking missing features on individual bugs, so we can close this one.
