### ISSUE TITLE
Tests still use #library #import #source

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#6512]
+big_integer_vm_test: Fail, OK
+collection_to_string_test: Fail, OK
+exception_implementation_test: Fail, OK
+futures_test: Fail, OK
+map_test: Fail, OK
+maps_test: Fail, OK
+queue_test: Fail, OK
+splay_tree_test: Fail, OK
+string_base_vm_test: Fail, OK
+stopwatch_test: Fail, OK

+isolate2_negative_test: Pass
+compute_this_script_browser_test: Pass

+arithmetic_test: Fail, OK
+call_constructor_on_unresolvable_class_test/none: Fail, OK
+call_constructor_on_unresolvable_class_test/01: Fail, OK
+call_constructor_on_unresolvable_class_test/02: Fail, OK
+call_constructor_on_unresolvable_class_test/07: Fail, OK
+call_constructor_on_unresolvable_class_test/03: Fail, OK
+closure_type_test: Fail, OK
+const_var_test: Fail, OK
+ct_const4_test: Fail, OK
+cyclic_import_test: Fail, OK
+function_type_alias3_test: Fail, OK
+getter_setter_in_lib_test: Fail, OK
+import_collection_no_prefix_test: Fail, OK
+import_core_no_prefix_test: Fail, OK
+import_core_prefix_test: Fail, OK
+import_core_test: Fail, OK
+intrinsified_methods_test: Fail, OK
+issue1363_test: Fail, OK
+library5_test: Fail, OK
+library_private_in_constructor_test: Fail, OK
+numbers_test: Fail, OK
+prefix101_test: Fail, OK
+prefix10_negative_test: Pass
+prefix10_test: Fail, OK
+prefix11_test: Fail, OK
+prefix12_test: Fail, OK
+prefix1_negative_test: Pass
+prefix21_test: Fail, OK
+prefix4_negative_test: Pass
+prefix5_negative_test: Pass
+prefix_new_test: Fail, OK
+prefix_test: Fail, OK
+private_member3_negative_test: Pass
+private_member_test: Fail, OK
+top_level_prefixed_declaration_test: Fail, OK
+typed_message_test: Fail, OK

+crypto/base64_test: Fail, OK
+crypto/hmac_md5_test: Fail, OK

+json_test: Fail, OK
+utf8_test: Fail, OK

**Comment by srawlins** [comment]
This can be closed. Nothing uses this syntax any more.
