### ISSUE TITLE
Dart VM cannot load files from paths containing non-ASCII characters

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#6574]
1. Be on Windows 7.
2. Create a directory C:\hey☺
3. In that, place hello.dart:

&nbsp;&nbsp;&nbsp;main() =&gt; print('Hello.');

4. Open a command prompt and navigate to that directory:

&nbsp;&nbsp;&nbsp;$ cd C:\hey☺

5. Run the script:

&nbsp;&nbsp;&nbsp;$ dart hello.main

When I try this, I get:

Unable to open file: C:/hey

**Comment by iposva-google** [comment]
Duplicate of #6587.
