### ISSUE TITLE
Dart2js does not handle non-BMP characters in toUpperCase and toLowerCase

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#6707]
Failing test: corelib/surrogate_pair_toUpper_test
This works on the VM.

**Comment by floitschG** [comment]
@sigmundch why did you remove the dart2js-area? What area should it be in?

**Comment by sigmundch** [comment]
oops, that was unintentional, I guess I made a mistake when using the issue tracker UI

**Comment by sigmundch** [comment]
we are tracking this directly in status files now.
