### ISSUE TITLE
Decimal data type

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#681]
[user feedback]
Please include decimal data type. Even if it will not work in Javascript, it will be better to contain it for compliles apps

**Comment by Lilyquist** [comment]
I'm amazed this isn't built into the language. This is my biggest disappointment as a newcomer to Dart. Dart is pitched as "batteries included" - but this gap makes that simply not true.

**Comment by matanlurey** [comment]
This looks unlikely to happen, and keeping this issue open for 8 years isn't doing favors.
