### ISSUE TITLE
analyzer: warn if public member returns private type

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#6865]
Scenario:

class _PrivateType {
}

_PrivateType getInfo() {
&nbsp;&nbsp;// do something
}

`getInfo` is public, but the return type is private to the library. Would be great to get a warning in this case.

**Comment by pq** [comment]
@bwilkerson I could have sworn there was an issue tracking a similar idea in the `linter` package; I know we've discussed it.  (Didn't you prototype something?) . In any event, it seems like this could be moved or merged there?

**Comment by bwilkerson** [comment]
I have a tool that does that and more. I don't have it in the form of a lint rule, but it could be converted easily enough if someone had the time.

**Comment by bwilkerson** [comment]
Personally, I don't care which issue tracker lint-related issues are in.

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#1054
