### ISSUE TITLE
It is a compile-time error if e refers to the name v or the name v=.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#6871]
See latest spec draft.

FAILED: dartc-none release_ia32 language/block_scope_test
Expected: pass 
Actual: fail

stdout:
(Ignoring unrecognized flag: --package-root=xcodebuild/ReleaseIA32/packages/)

stderr:
ERROR|RESOLVER|VARIABLE_REFERENCES_SAME_NAME_IN_INITIALIZER|file:/Users/scheglov/Source/Dart/dart/tests/language/block_scope_test.dart|8|13|3|Initializer of variable &quot;foo&quot; cannot refer to the name &quot;foo&quot;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;7: void testShadowingScope1() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8:   var foo = foo();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~~
ERROR|RESOLVER|VARIABLE_REFERENCES_SAME_NAME_IN_INITIALIZER|file:/Users/scheglov/Source/Dart/dart/tests/language/block_scope_test.dart|14|15|3|Initializer of variable &quot;foo&quot; cannot refer to the name &quot;foo&quot;
&nbsp;&nbsp;&nbsp;&nbsp;13:   {
&nbsp;&nbsp;&nbsp;&nbsp;14:     var foo = foo() + 444;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~~
ERROR|RESOLVER|VARIABLE_REFERENCES_SAME_NAME_IN_INITIALIZER|file:/Users/scheglov/Source/Dart/dart/tests/language/block_scope_test.dart|46|17|3|Initializer of variable &quot;foo&quot; cannot refer to the name &quot;foo&quot;
&nbsp;&nbsp;&nbsp;&nbsp;45:     if (true) {
&nbsp;&nbsp;&nbsp;&nbsp;46:       var foo = foo() + 444;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~~
ERROR|RESOLVER|VARIABLE_REFERENCES_SAME_NAME_IN_INITIALIZER|file:/Users/scheglov/Source/Dart/dart/tests/language/block_scope_test.dart|53|17|3|Initializer of variable &quot;bar&quot; cannot refer to the name &quot;bar&quot;
&nbsp;&nbsp;&nbsp;&nbsp;52:     if (true) {
&nbsp;&nbsp;&nbsp;&nbsp;53:       var bar = bar() + 444;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~~
Compilation failed with 4 problems.

Command line: xcodebuild/ReleaseIA32/analyzer/bin/dart_analyzer --ignore-unrecognized-flags --package-root=xcodebuild/ReleaseIA32/packages/ --error_format machine /Users/scheglov/Source/Dart/dart/tests/language/block_scope_test.dart

**Comment by natebosch** [comment]
I don't follow the problem - is this about a failing test? Is it still failing?

**Comment by scheglov** [comment]
Yes, this was about a failing test.
The test does not exist anymore, the issue is not referenced anywhere in SDK codebase.
So, I think we can close it as obsolete.
