### ISSUE TITLE
Make sure the isolate hidden class is constant

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#6892]
V8 optimizes function instantiations by moving constant functions into the hidden class.
for example function A() { this.foo = function() { return 499; }; }
Afaik this will move the function into the hidden class of the newly allocated object.
However if 'foo' changes this means that we have a map-transition. Normally this doesn't happen for dart2js generated code, but we should probably make sure that non-final statics don't have this problem:
&equals;&equals;&equals;
bar() =&gt; 499;
var foo = bar;
// later in code:
... foo = (() =&gt; 42);
&equals;&equals;&equals;

**Comment by karlklose** [comment]
@floitschG Could you update the status of this bug?

**Comment by floitschG** [comment]
Current version of dart2js seems to do the right thing. Deferred loading of libraries destroys the hidden map of global objects, but that's a different issue.

```
final x = (() { return 499; }) ();
final y = (() { return 42; }) ();

foo() {
  var sum = 0;
  for (int i = 0; i < 100000; i++) {
    sum += x;
    sum = sum & 0xFFFFFF;
  }
  return sum;
}

main() {
  for (int j = 0; j < 1000; j++) { foo(); }

  var sw = new Stopwatch()..start();
  for (int j = 0; j < 1000; j++) { foo(); }
  print(sw.elapsedMilliseconds);
  print(y);
  for (int j = 0; j < 1000; j++) { foo(); }
  sw.reset();
  for (int j = 0; j < 1000; j++) { foo(); }
  print(sw.elapsedMilliseconds);
}
```
