### ISSUE TITLE
VM fails language/built_in_identifier_prefix_test

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#6970]
FAILED: none-vm release_ia32 language/built_in_identifier_prefix_test
Expected: pass 
Actual: fail

stderr:
'file:///Users/ahe/Dart/all/dart/tests/language/built_in_identifier_prefix_test.dart': Error: line 45 pos 1: unexpected token 'abstract'
abstract.A \_abstract = new abstract.A();
^

Command line: xcodebuild/ReleaseIA32/dart --ignore-unrecognized-flags --package-root=xcodebuild/ReleaseIA32/packages/ /Users/ahe/Dart/all/dart/tests/language/built_in_identifier_prefix_test.dart

**Comment by mhausner** [comment]
Looking at the test and its comments, I'd say this is more an issue of an oversight in the language spec.

```
// From The Dart Programming Language Specification, section 11.30
// "Identifier Reference":
//
// "A built-in identifier is one of the identifiers produced by the
// production BUILT IN IDENTIFIER. It is a compile-time error if a
// built-in identifier is used as the declared name of a class, type
// parameter or type alias. It is a compile-time error to use a
// built-in identifier other than dynamic as a type annotation."
//
// Observation: it is not illegal to use a built-in identifier as a library
// prefix.
//
// Observation: it is not legal to use a built-in identifer as a type
// annotation. A type annotation is not fully defined in the
// specification, so we assume this means that the grammar production
// "type" cannot match a built-in identifier. Unfortunately, this
// doesn't prevent us from using built-in identifiers *in* type
// annotations. For example, "final abstract foo;" is illegal as
// "abstract" is used as a type annotation. However, "final
// abstract<dynamic> foo;" is not illegal because "abstract" is used
// as a typeName.
```

**Comment by mhausner** [comment]
In fact, the Spec has changed since this bug was filed. It now also expressly forbids to use built-in identifiers as prefixes.
