### ISSUE TITLE
Please update TestingDart2js wiki page with most recent instructions

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#6996]
Emily reports:

FYI: One note -- I ran the recommended tests (even on a clean
checkout), but still got a few failures (but the bots all seem to be
green), so perhaps that wiki page needs updating in some way?

$ ./tools/test.py -mrelease -cdart2js -rd8,drt --use-sdk --time -pcolor --report
FAILED: dart2js-d8 release_ia32 pkg/args/test/args_test
Expected: pass
Actual: fail
Unexpected compile-time error.

stdout:
pkg/args/test/args_test.dart:9:8: Error: Cannot read
&quot;xcodebuild/ReleaseIA32/packages/args/args.dart&quot; (OS Error: No such
file or directory, errno = 2).
import 'package:args/args.dart';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.

stderr:
Using snapshot /Users/efortuna/git-dart/dart/xcodebuild/ReleaseIA32/dart-sdk/bin/../lib/_internal/compiler/implementation/dart2js.dart.snapshot
test.dart: Compilation failed (step 1 of 2), exit code 1

Compilation command: xcodebuild/ReleaseIA32/dart-sdk/bin/dart2js
--allow-mock-compilation
--package-root=xcodebuild/ReleaseIA32/packages/
/Users/efortuna/git-dart/dart/pkg/args/test/args_test.dart
--out=/Users/efortuna/git-dart/dart/xcodebuild/ReleaseIA32/generated_tests/dart2js-d8/pkg_args_test_args_test/out.js

Command line: xcodebuild/ReleaseIA32/d8
/Users/efortuna/git-dart/dart/xcodebuild/ReleaseIA32/generated_tests/dart2js-d8/pkg_args_test_args_test/out.js

FAILED: dart2js-drt release_ia32 pkg/args/test/args_test
Expected: pass
Actual: fail
Unexpected compile-time error.

stdout:
pkg/args/test/args_test.dart:9:8: Error: Cannot read
&quot;xcodebuild/ReleaseIA32/packages/args/args.dart&quot; (OS Error: No such
file or directory, errno = 2).
import 'package:args/args.dart';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.

stderr:
Using snapshot /Users/efortuna/git-dart/dart/xcodebuild/ReleaseIA32/dart-sdk/bin/../lib/_internal/compiler/implementation/dart2js.dart.snapshot
test.dart: Compilation failed (step 1 of 2), exit code 1

Compilation command: xcodebuild/ReleaseIA32/dart-sdk/bin/dart2js
--package-root=xcodebuild/ReleaseIA32/packages/
--out=/Users/efortuna/git-dart/dart/xcodebuild/ReleaseIA32/generated_tests/dart2js-drt/pkg_args_test_args_test/test.js
/Users/efortuna/git-dart/dart/pkg/args/test/args_test.dart

Command line: python
/Users/efortuna/git-dart/dart/tools/testing/drt-trampoline.py
/Users/efortuna/git-dart/dart//client/tests/drt/DumpRenderTree.app/Contents/MacOS/DumpRenderTree
--no-timeout file:///Users/efortuna/git-dart/dart/xcodebuild/ReleaseIA32/generated_tests/dart2js-drt/pkg_args_test_args_test/../_Users_efortuna_git-dart_dart_pkg_args_test_args_test.dartdart2js-drt.html

FAILED: dart2js-drt release_ia32
language/closure_call_wrong_argument_count_negative_test
Expected: pass
Actual: timeout

stdout:
test.dart: Compilation finished  (step 1 of 2)

stderr:
test.dart: Compilation finished  (step 1 of 2)

Compilation command: xcodebuild/ReleaseIA32/dart-sdk/bin/dart2js
--package-root=xcodebuild/ReleaseIA32/packages/
--out=/Users/efortuna/git-dart/dart/xcodebuild/ReleaseIA32/generated_tests/dart2js-drt/tests_language_closure_call_wrong_argument_count_negative_test/test.js
/Users/efortuna/git-dart/dart/tests/language/closure_call_wrong_argument_count_negative_test.dart

Command line: python
/Users/efortuna/git-dart/dart/tools/testing/drt-trampoline.py
/Users/efortuna/git-dart/dart//client/tests/drt/DumpRenderTree.app/Contents/MacOS/DumpRenderTree
--no-timeout file:///Users/efortuna/git-dart/dart/xcodebuild/ReleaseIA32/generated_tests/dart2js-drt/tests_language_closure_call_wrong_argument_count_negative_test/../l_wrong_argument_count_negative_test.dartdart2js-drt.html

**Comment by srawlins** [comment]
Obsolete? [Here](https://github.com/dart-lang/sdk/wiki/Testing-Dart2js) are the current instructipns
