### ISSUE TITLE
dart2js: MetadataAnnotation does not extend Element

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#7007]
The other elements all extend Element, which makes Element.parseNode available.

MetadataAnnotation does not extend element, which means you have to use

(foo as PartialMetadataAnnotation).parseNode(compiler)

I'm not sure why this is the case.  It would be more convenient for programming against MetadataAnnotation if it was an Element.

**Comment by karlklose** [comment]
Fixed in r18129.
