### ISSUE TITLE
Inherited member with same name as enclosing class not shadowed by specification.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#7051]
Example:

---

class C {
&nbsp;D() { print(&quot;D&quot;); }
}

class D {
&nbsp;foo() { D(42); }
}

main() {
&nbsp;new D().foo();
}

---

According to the specification, the D-call in foo() should be rewritten to this.D(42) and print 42. This follows from the &quot;Unqualified invocation&quot; section in the specification&quot;, because &quot;D&quot; *is* declared in the current scope, but is not one of the listed cases, so it falls through to the &quot;otherwise&quot; case also covering where D is not declared.

Since having just one Scope is a goal, the &quot;D&quot; in foo() should refer to the enclosing class, and calling that is an error (as should a library prefix be, which the spec mentions as a problem). 
A solution could be adding a third &quot;dot&quot; for the case where the identifier is declared, and make it an error if it's not handled by the previous two dots.

**Comment by eernstg** [comment]
No milestone now: This will not block Dart 2.

We should add the missing case to the abovementioned list.

**Comment by lrhn** [comment]
That is actually already fixed:
```latex
item
If $id$ is a type literal, then $i$ is interpreted as a function expression invocation (\ref{functionExpressionInvocation}) with $(id)$ as the expression $e_f$.
\commentary{
The expression $(id)$ where $id$ is a type literal always evaluates to an instance of class \code{Type} which is not a function.
This ensures that a run-time error occurs when trying to call a type literal.
}
```
