### ISSUE TITLE
Assigning to final variable is a static warning, not error

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#7062]
final_for_in_variable_test/01: Fail
final_param_negative_test: Fail
final_var_negative_test: Fail
final_variable_assignment_test/01: Fail
final_variable_assignment_test/03: Fail
final_variable_assignment_test/04: Fail
final_variable_assignment_test/02: Fail
scope_negative_test: Fail
static_final_field2_negative_test: Fail

Spec

---

A final variable is a variable whose declaration includes the modifier final. 

It is a compile-time error if a final instance variable that has been initialized at its point of declaration  is  also initialized in a constructor. It is a compile-time error if a final instance variable that has is initialized by means of an initializing formal of a constructor is  also initialized elsewhere in the same constructor.

It is a compile-time error if a library, static or local variable v is final and v is not initialized at its point of declaration.

Attempting to assign to a final variable elsewhere will cause a NoSuchMethodError to be thrown, because no setter is defined for it. The assignment will also give rise to a static warning for the same reason. 

A constant variable is a variable whose declaration includes the modifier const. A constant variable is always implicitly final. A constant variable must be initialized to a compile-time constant or a compile-time error occurs.

---

**Comment by matanlurey** [comment]
It is an error in Dart2.
