### ISSUE TITLE
It is static warning to use unknown type in 'catch'

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#7098]
try_catch_on_syntax_test/01: Fail
try_catch_on_syntax_test/07: Fail
try_catch_syntax_test/08: Fail

Spec 0.13, try statement.
&quot;An on-catch clause of the form on T catch (p1, p2) s or on T s matches an object o if the type of o is a subtype of T.  It is a static warning if T does not denote a type available in the lexical scope of the catch clause.&quot;

**Comment by srawlins** [comment]
These are fixed.
