### ISSUE TITLE
fullParseUnit doesn't actually work

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#7178]
import 'tests/compiler/dart2js/parser_helper.dart';

void main() {
&nbsp;&nbsp;print(fullParseUnit(&quot;int i = 0;&quot;));
}

$ ./sdk/bin/dart test.dart
Unhandled exception:
Expect.isTrue(false, 'Not empty: [  ]') fails.
#­0      Expect._fail (bootstrap:655:5)
#­1      Expect.isTrue (bootstrap:494:10)
#­2      parseBodyCode (file:///.../dart/tests/compiler/dart2js/parser_helper.dart:51:16)
#­3      fullParseUnit (file:///.../dart/tests/compiler/dart2js/parser_helper.dart:89:23)
#­4      main (file:///.../dart/test.dart:4:22)

$ ./sdk/bin/dart --checked test.dart
Unhandled exception:
type 'TypeAnnotation' is not a subtype of type 'Modifiers' of 'modifiers'.
#­0      NodeListener.endTopLevelFields (file:///.../dart/sdk/lib/_internal/compiler/implementation/scanner/listener.dart:1192:34)
#­1      Parser.parseTopLevelMember (file:///.../dart/sdk/lib/_internal/compiler/implementation/scanner/parser.dart:652:33)
#­2      Parser.parseTopLevelDeclaration (file:///.../dart/sdk/lib/_internal/compiler/implementation/scanner/parser.dart:67:33)
#­3      Parser.parseUnit (file:///.../dart/sdk/lib/_internal/compiler/implementation/scanner/parser.dart:40:39)
#­4      fullParseUnit.&lt;anonymous closure&gt; (file:///.../dart/tests/compiler/dart2js/parser_helper.dart:89:68)
#­5      parseBodyCode (file:///.../dart/tests/compiler/dart2js/parser_helper.dart:47:31)
#­6      fullParseUnit (file:///.../dart/tests/compiler/dart2js/parser_helper.dart:89:23)
#­7      main (file:///.../dart/test.dart:4:22)

**Comment by karlklose** [comment]
Verified working as expected in 79a8654e5fb30dfce902636961d6a5ffb69e6f85
