### ISSUE TITLE
dart2js require factory redirection to a generative constructor

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#7236]
This program fails:

class A {
&nbsp;&nbsp;factory A() = B;
}

class B implements A {
&nbsp;&nbsp;factory B() = C;
}

class C implements B {
}

main() {
&nbsp;&nbsp;print(new A());
}

foo.dart:2:17: Internal error: redirecing to redirecting factory not implemented
&nbsp;&nbsp;factory A() = B;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

**Comment by karlklose** [comment]
Verified fixed in 79a8654e5fb30dfce902636961d6a5ffb69e6f85
