### ISSUE TITLE
dart2js: switch-related warnings are duplicated

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#7276]
Sometimes I see switch-related warnings duplicated. Maybe this is because the warnings are issued in the backend and we get them duplicated when we recompile? 

--
class C {
&nbsp;&nbsp;final id;
&nbsp;&nbsp;const C(this.id);
&nbsp;&nbsp;operator ==(var x) =&gt; true; 
}

main() {
&nbsp;&nbsp;switch (const C(0)) {
&nbsp;&nbsp;&nbsp;&nbsp;case const C(0): print('hest'); break;
&nbsp;&nbsp;}
}
--

leads to:

sdk/bin/dart2js -c -o../tmp/fusk.js ~/dart/hello/hello.dart
../../dart/hello/hello.dart:9:10: Warning: case expression value overrides 'operator=='.
&nbsp;&nbsp;&nbsp;&nbsp;case const C(0): print('hest'); break;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^
../../dart/hello/hello.dart:9:10: Warning: case expression value overrides 'operator=='.
&nbsp;&nbsp;&nbsp;&nbsp;case const C(0): print('hest'); break;

**Comment by karlklose** [comment]
Current output of the example is 
Hint: The class 'C' overrides 'operator==', but not 'get hashCode'.
  operator ==(var x) => true; 
  ^^^^^^^^^^^^^^^^^^
../../issue-7276.dart:9:10:
Error: 'case' expression type 'C' overrides 'operator =='.
    case const C(0): print('hest'); break;
         ^^^^^^^^^^
Error: Compilation failed.
