### ISSUE TITLE
dart2js: must check type of switch expression in checked mode

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#7289]
The following switches are supposed to fail in checked mode. The specification says:

Execution of a switch statement of the form  switch (e) ... proceeds as follows:

The statement var id = e; is evaluated, where id is a variable whose name is distinct from any other variable in the program.  In checked mode, it is a run time error if the value of e is not an instance of the same class as the constants e1 … en.

---
switch ('foo') {
&nbsp;&nbsp;case 0: ...
&nbsp;&nbsp;case 1: ...
}

switch (42) {
&nbsp;&nbsp;case 'foo': ...
&nbsp;&nbsp;case 'bar': ...
}

switch (true) {
&nbsp;&nbsp;case const MyConst(1): ...
&nbsp;&nbsp;case const MyConst(2): ...
}

**Comment by karlklose** [comment]
Will be obsolete with the new backend.
