### ISSUE TITLE
Triage test failures on opera

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#7413]
The following tests are failing on opera and need be triaged:

corelib/null_nosuchmethod_test

html/document_test/getCssCanvasContext
html/form_data_test
html/keyboard_event_test
html/xmldocument_2_test
html/element_test/eventListening
html/element_test/children

language/null_access_error_test
language/string_interpolate_null_test

**Comment by whesse** [comment]
Opera now uses the chrome renderer, and is no longer tested.
