### ISSUE TITLE
dart_analyzer should print errors for imports that import erroneous files (transitively)

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#7550]
When the Dart VM encounters an error loading an imported file, in addition to printing that error, it also prints errors for every import along the import chain that led to the file in question. This is useful; it shows the user how the errors they're seeing are related to their code.

It would be nice if the analyzer did this as well for errors or warnings it finds in transitively-imported files. This would also provide the invariant that if the analyzer reports any errors, it will report some errors for the file on which it's being run. This is useful when using it for error highlighting in editors other than the dart editor.

**Comment by srawlins** [comment]
@nex3 Is this still valid? Last comment was 3.5 years ago. Dart Editor is dead.

**Comment by nex3** [comment]
This wasn't an issue against the Dart editor, it was against the analyzer itself. However, now that most real-world code is in packages, it's less relevant to know the import chain leading to the error since generally all files in a package are analyzed, so I'm happy to close this.
