### ISSUE TITLE
ImmutableMap should not take O(N) to do a lookup

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#7559]
See the code:

&nbsp;&nbsp;V operator [\](K key) {
&nbsp;&nbsp;&nbsp;&nbsp;// TODO(hausner): Since the keys are sorted, we could do a binary
&nbsp;&nbsp;&nbsp;&nbsp;// search. But is it worth it?
&nbsp;&nbsp;&nbsp;&nbsp;for (int i = 0; i &lt; kvPairs_.length - 1; i += 2) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (key == kvPairs_[i]) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return kvPairs_[i+1];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return null;
&nbsp;&nbsp;}

O(N) lookup means you are better off not making const Maps, which is completely counter to the design of const.

**Comment by kodandersson** [comment]
Now that they are efficiently serialized, we can simply reuse the _LinkedHashMapMixin that we use for the default (mutable) maps, but redefining all mutating operations to throw the appropriate error.

**Comment by mhausner** [comment]
A long time ago we changed immutable maps to keep the entries ordered in source order, so a binary search (as suggested in the TODO comment in the code) does not work. Let's not make this more complicated than necessary.

**Comment by iposva-google** [comment]
As far as I understand Daniel was suggesting the use of the efficient ordered maps as an implementation of ImmutableMap. How best to do this is not entirely clear to me yet.

**Comment by jmesserly** [comment]
Yeah, the bug was more about the fact that key lookup is O(N), not the particular approach described in the TODO. O(N) doesn't match expectations about how Map lookup should work. The workaround is to avoid const maps and/or keep them small.

**Comment by mhausner** [comment]
Correct, that is not only a workaround but also good practice. Constant maps get evaluated at compile-time. If you have a large map, load times may suffer. (There is another open bug that complains that load time for a script with a > 2000 entry const map is too long.)
