### ISSUE TITLE
Find out why we get sometimes  "Gtk-WARNING **: cannot open display" warnings 

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#7564]
It seems that we get the &quot;Gtk-WARNING **: cannot open display&quot; error quite frequently on DRT runs.

For example:
http://chromegw.corp.google.com/i/client.dart/builders/dart2js-chrome-linux/builds/1994/steps/annotated_steps/logs/stdio

Currently we just rerun the test, but this approach just hides this flake. We need to find out why this happens.

**Comment by whesse** [comment]
This is still assumed to be happening, by the suppression in test_runner.dart.  Test that the issue has disappeared by removing the suppression code before closing.
