### ISSUE TITLE
dart2js: change JS AST printer to select local renamer dynamically

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#7614]
The current printer selects local renaming globally for printing.
I'm trying to aggregate functions into a larger JavaScript AST.
The global selection does not suit this - local renaming needs to be selected on a per-function basis within one call to prettyPrint.

An alternative is to ensure that local renaming can always be performed.

**Comment by karlklose** [comment]
@rakudrama Is this resolved?

**Comment by rakudrama** [comment]
Local renaming can always be performed.
We also now aggregate the entire program into a single AST.
There is a feature via a special comment to disable renaming in a given scope.
