### ISSUE TITLE
Dart2JS does not give a static warning if not implementing inherited method interface with inherited method.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#7641]
Example:

class C {
&nbsp;&nbsp;int foo(int x) =&gt; x;
}

abstract class D {
&nbsp;&nbsp;int foo(int x, [int y]);
}

class E extends C implements D {}

typedef int foo2(int x, [int y]);

main() {
&nbsp;&nbsp;D d = new E();
&nbsp;&nbsp;foo2 foo = d.foo;
&nbsp;&nbsp;print(foo(2,2));
}  

This should give a static warning since E is a non-static class that doesn't have a method matching the super-interface method D.foo. 
It has an inherited method of the same name, but it's not matching (spec, section 7.10).

Gilad: Should this be a compilation error instead?

**Comment by sigmundch** [comment]
now handled by CFE
