### ISSUE TITLE
Incorrect cascading operation in conditional expression

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#7689]
&nbsp;&nbsp;List&lt;Element&gt; get path1 {
&nbsp;&nbsp;&nbsp;&nbsp;return (parent == null) ? &lt;Element&gt;[this] : parent.path1..add(this);
&nbsp;&nbsp;}

Related to issue #7665 (filed against VM).

tests/language/cascade_2_test.dart

**Comment by lrhn** [comment]
Dart2js seems to do the right thing. As a dart2js bug, this seems fixed.
Whether we want to change the grammar is a different issue, but there is no current plan.
