### ISSUE TITLE
dart2js: timer interface is not supported

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#7728]
There is no implementation for the Timer interface in generated JavaScript code. When trying to use timers with dart2js, an exception with description: &quot;Timer interface not supported.&quot; occurs.

**Comment by karlklose** [comment]
Working as intended. We can simulate some of their functionality but they are not available on these platforms.

**Comment by floitschG** [comment]
We could keep this bug, for the jsshell. There are still lots of tests that are marked as failing because of it, and it should be feasible (if not trivial) to adapt the v8 code for jsshell.

**Comment by lrhn** [comment]
I'm pretty sure we can just copy the d8 preamble and use it for jsshell as well. At least the timer code is completely generic.
The reason I haven't done so yet is that that would leave use with no testing setting where timers are not available, so we would never test the "timers not available" code.

**Comment by floitschG** [comment]
I don't think we need the "timers not available" code tested.
I prefer having jsshell tested.
/cc @sigmundch what do you prefer?

**Comment by sigmundch** [comment]
It seems that we can get more value from having jsshell tested, so my preference is towards that too.

Since the extra code lives in a preamble, we could technically also have extra test-only preambles if we want to cover specific error-code functionality. How complex would it be to add a single test that uses a test-specific preamble? Is that worth the effort?

**Comment by floitschG** [comment]
I don't think it's worth the effort. Our customers run in the browser, and there timers exist.
Furthermore, we can always recommend to use our preambles when running outside the browser.

**Comment by sigmundch** [comment]
sgtm

**Comment by sigmundch** [comment]
(reopened to track adding timer support in the jsshell preamble, hopefully by simply coping it from the d8 preamble)
