### ISSUE TITLE
Python-style range() function and iterable

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#7775]
range() would be useful for for..in/.forEach() loops, constructing lists of integers, and in combinations with functions like zip().

The signature in Dart might be:

&nbsp;&nbsp;&nbsp;&nbsp;Iterable&lt;int&gt; range(int stop_or_start, [int stop, int step]);

or possibly named arguments for stop and step.

Usage:

&nbsp;&nbsp;&nbsp;&nbsp;new List.from(range(10)); // [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
&nbsp;&nbsp;&nbsp;&nbsp;new List.from(range(1, 11)); // [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
&nbsp;&nbsp;&nbsp;&nbsp;new List.from(range(1, 10, 2)); // [1, 3, 5, 7, 9]
&nbsp;&nbsp;&nbsp;&nbsp;new List.from(range(10, 0, -1)); // [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

See Python docs:
http://docs.python.org/3.2/library/functions.html#range

**Comment by Sunbreak** [comment]
Any progress?

**Comment by lrhn** [comment]
Thanks for reminding me of this issue.
We do not plan to add such functionality to the platform libraries. There is still no *canonical* approach, just a spread of different possible, and equally reasonable, approaches, so enshrining one of them in the platform libraries seems like the wrong signal to send.

If anywhere, such functionality could possibly go into `package:collection`.
Since we have added extension methods (and generator functions) since this issue was filed, it's much easier to make your own. It's just:
```dart
extension IntRange on int {
  /// A arithmetic sequence of numbers from [this] to, but not including [end].
  /// 
  /// The difference between two consecutive numbers is [stepSize].
  /// The [stepSize] must be positive (not negative or zero).
  ///
  /// The first number is always [this].
  /// If [this] is smaller than [end], the next number in the sequence is found by
  /// adding [stepSize] to the current number until reaching or exceeding [end].
  /// If [end] is smaller than [this], the next number in the sequence is found by
  /// subtracting [stepSize] from the current number until reaching or subceeding [end].
  Iterable<int> to(int end, [int stepSize = 1]) sync* {
    RangeError.checkValueInInterval(stepSize, 1, null, "stepSize");
    if (start <= end) {
      for (var i = this; i < end; i += stepSize) yield i;
    } else {
      for (var i = this; i > end; i -= stepSize) yield i;
    }
  }
}
```
(and that's the complete "validate inputs, work in both directions" version, you can be shorter if you know the use-case).

**Comment by Sunbreak** [comment]
> If anywhere, such functionality could possibly go into package:collection.

So a feature request for package:collection?

**Comment by lrhn** [comment]
Yes, yhat could potentially succeed. Likely not as an extension on `int`, but a `range` function seems reasonably.

**Comment by Sunbreak** [comment]
FYI: Google has a [`quiver` utility library](https://github.com/google/quiver-dart)

> # quiver.iterables
> concat, count, cycle, enumerate, merge, partition, `range`, and zip create, transform, or combine Iterables in different ways, similar to Python's itertools.

**Comment by fzyzcjy** [comment]
FYI: @lrhn provides a `range` that is as fast as `for(var i=0;i<10;++i)` here - https://github.com/dart-lang/sdk/issues/50280#issuecomment-1288679644
