### ISSUE TITLE
Make ArgParser library have a default "help" behavior

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#7806]
Looks like if you want to have a help message to print all the helpful documentation you wrote about the options your file takes, you need to explicitly add that with &quot;addFlag(&quot;help&quot;, abbr: 'h'... ) ... printUsage();&quot; etc In the python arg parsing library that help option and behavior is built in automatically by default. Can we have this behavior, too? :-)

**Comment by lrhn** [comment]
The argument parser is no longer in this repository.
