### ISSUE TITLE
Closures displayed in stack trace with extra argument

### ISSUE THREAD

**Issue by gbracha** [dart-lang/sdk#7864]
The stack trace displays  closures with an extra argument. Presumably this is an artifact of the underlying VM implementation, but this is not what a Dart programmer would expect. E.g.,

(String s) =&gt; 'string $t'

displays as

(dynamic, String)  =&gt; dynamic

rather than as

(String) =&gt; dynamic

**Comment by rmacnak-google** [comment]
class A {
  foo() {
    closure(String x) => "$x i";
    print(closure.runtimeType);
  }
}

main() {
  new A().foo();
}

prints (String) => dynamic
not (dynamic, String) => dynamic

This has probably been fixed for a long time.
