### ISSUE TITLE
Repeated stack traces in async code

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#7925]
fisk.dart:

import 'dart:async';

main() {
&nbsp;&nbsp;new Future.immediate(null).then((_) {
&nbsp;&nbsp;&nbsp;&nbsp;missing();
&nbsp;&nbsp;});
}

$ sdk/bin/dart2js fisk.dart &amp;&amp; ./xcodebuild/ReleaseIA32/d8 out.js
fisk.dart:5:5: Warning: cannot resolve missing
&nbsp;&nbsp;&nbsp;&nbsp;missing();
&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^
Dart file fisk.dart compiled to JavaScript: out.js
Uncaught Error: NoSuchMethodError : method not found: 'missing'
Receiver: &quot;&quot;
Arguments: []
Stack Trace:
NoSuchMethodError : method not found: 'missing'
Receiver: &quot;&quot;
Arguments: []
&nbsp;&nbsp;&nbsp;&nbsp;at $.throwNoSuchMethod (out.js:3437:11)
&nbsp;&nbsp;&nbsp;&nbsp;at main_anon.$$.main_anon.call$1 (out.js:2514:7)
&nbsp;&nbsp;&nbsp;&nbsp;at \_ThenFuture.$$._ThenFuture._onValue$1 (out.js:2391:26)
&nbsp;&nbsp;&nbsp;&nbsp;at \_ThenFuture.$$._ThenFuture._sendValue$1 (out.js:2397:21)
&nbsp;&nbsp;&nbsp;&nbsp;at \_FutureImpl__handleValue_anon.$$._FutureImpl__handleValue_anon.call$1 (out.js:2520:23)
&nbsp;&nbsp;&nbsp;&nbsp;at anon.$$.anon.call$0 (out.js:2526:21)
&nbsp;&nbsp;&nbsp;&nbsp;at \_IsolateContext.$$._IsolateContext.eval$1 (out.js:1444:21)
&nbsp;&nbsp;&nbsp;&nbsp;at \_IsolateEvent.$$._IsolateEvent.process$0 (out.js:1551:18)
&nbsp;&nbsp;&nbsp;&nbsp;at \_EventLoop.$$._EventLoop.runIteration$0 (out.js:1522:12)
&nbsp;&nbsp;&nbsp;&nbsp;at \_EventLoop.$$._EventLoop._runHelper$0 (out.js:1529:19)

out.js:2614: NoSuchMethodError : method not found: 'missing'
Receiver: &quot;&quot;
Arguments: []
&nbsp;&nbsp;&nbsp;&nbsp;throw $.$$throw(this.this_1.get$error());
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
NoSuchMethodError : method not found: 'missing'
Receiver: &quot;&quot;
Arguments: []
&nbsp;&nbsp;&nbsp;&nbsp;at AsyncError_throwDelayed_anon.$$.AsyncError_throwDelayed_anon.call$1 (out.js:2614:13)
&nbsp;&nbsp;&nbsp;&nbsp;at anon.$$.anon.call$0 (out.js:2526:21)
&nbsp;&nbsp;&nbsp;&nbsp;at \_IsolateContext.$$._IsolateContext.eval$1 (out.js:1444:21)
&nbsp;&nbsp;&nbsp;&nbsp;at \_IsolateEvent.$$._IsolateEvent.process$0 (out.js:1551:18)
&nbsp;&nbsp;&nbsp;&nbsp;at \_EventLoop.$$._EventLoop.runIteration$0 (out.js:1522:12)
&nbsp;&nbsp;&nbsp;&nbsp;at \_EventLoop.$$._EventLoop._runHelper$0 (out.js:1529:19)
&nbsp;&nbsp;&nbsp;&nbsp;at \_EventLoop.$$._EventLoop.run$0 (out.js:1535:12)
&nbsp;&nbsp;&nbsp;&nbsp;at $.startRootIsolate (out.js:2891:39)
&nbsp;&nbsp;&nbsp;&nbsp;at out.js:4335:7

This is what I expect:

out.js:3437: NoSuchMethodError : method not found: 'missing'
Receiver: &quot;&quot;
Arguments: []
&nbsp;&nbsp;throw $.$$throw($.NoSuchMethodError$(obj, name$, arguments$, $.CONSTANT5, ex
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
NoSuchMethodError : method not found: 'missing'
Receiver: &quot;&quot;
Arguments: []
&nbsp;&nbsp;&nbsp;&nbsp;at $.throwNoSuchMethod (out.js:3437:11)
&nbsp;&nbsp;&nbsp;&nbsp;at main_anon.$$.main_anon.call$1 (out.js:2514:7)
&nbsp;&nbsp;&nbsp;&nbsp;... possible implementation details

**Comment by lrhn** [comment]
Now also fixed for dart2js in comit 5363e5c9453b
