### ISSUE TITLE
Platform configuration

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#8046]
This is the meta-bug for &quot;platform configuration&quot; feature.

From the language meeting notes:

Lars: The top item to discuss is configuration. Gilad has a library object proposal. There's a few things we really want:
1. Want to make sure we can select platform-dependent implementation code. The system should be able to handle code that works different on client and server.
2. A way to to pass in constant values that can be compiled into the snapshot or execution.

**Comment by munificent** [comment]
You can handle this now using config-specific imports: #24581.
