### ISSUE TITLE
avoid nested deprecation errors

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#8131]
We currently get a deprecation warning/error for every deprecated symbol reachable from main. Would it be possible to only show the deprecation messages that are not covered by another deprecation message?

For example, in this code:

const deprecated = null;

@deprecated
bar() =&gt; null;

@deprecated
foo() =&gt; bar();

main() {
&nbsp;&nbsp;foo();
}

It would be great if the warning is only shown when calling 'foo', but not where 'foo' is calling 'bar'.

Another example is in dart:html. The 'on' getter is deprecated, and every class returned by 'on' is as well. If a program uses 'on', today they get an error for every one of those classes inside of 'dart:html'.

This is exposing errors from inside 'dart:html' are not relevant for the end user.

**Comment by srawlins** [comment]
This was fixed at some point:

https://dartpad.dartlang.org/5640611cccfdd4a47f4298a157ef4438
