### ISSUE TITLE
SecureSocket.initialize should be able to load in-memory certificate stores

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#8227]
Currently SecureSocket.initialize can only load certificate data from a file that's physically present on the filesystem. This makes it very awkward to configure SecureSocket, especially in programs distributed to third-party users. It would be preferable to be able to manipulate the certificate store in memory, especially for the relatively common use case of adding a few certificates to the store.

**Comment by whesse** [comment]
I am now working on adding SecurityContext.setTrustedCertificatesFromString , .setCertificateChainFromString, and .setPrivateKeyFromString, to supplement the existing methods (new in 1.13, with the shift to BoringSSL) that read these from files.

That will resolve this issue.  The issue about separate stores for separate isolates is already solved by BoringSSL in 1.13.

**Comment by whesse** [comment]
This issue is not dead, and should be fixed when possible.

**Comment by mit-mit** [comment]
@zanderso what is the status?

**Comment by zanderso** [comment]
This was fixed by the above commit.
