### ISSUE TITLE
Implement throwing of ArgumentError from API implementation code

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#8233]
In some cases the API implementation code (in runtime/vm/dart_api_impl.cc) needs to throw exceptions, most likely ArgumentError.

There is an implementation of that in https://codereview.chromium.org/12089071/, but it hits an ASSERT in debug mode.

**Comment by iposva-google** [comment]
Some of the corresponding API code has been cleaned in the meantime.
