### ISSUE TITLE
html/dromaeo_smoke_test is flaky

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#8257]
html/dromaeo_smoke_test seems to be flaky on firefox:

http://build.chromium.org/p/client.dart/builders/dart2js-ff-linux/builds/3950/steps/dart2js%20tests%20failures/logs/stdio
http://build.chromium.org/p/client.dart/builders/dart2js-ff-linux/builds/3948/steps/dart2js%20tests%20failures/logs/stdio

Marking it as flaky in status file.

@efortuna/blois: Could you look into this?

**Comment by srawlins** [comment]
This test doesn't exist anymore, right?

**Comment by bkonyi** [comment]
Looks like this test doesn't exist anymore. Closing.
