### ISSUE TITLE
dart2js: source maps breakpoint not accurate

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#8290]
Go to welcome screen, click Solar. Right click on index.html and run as JavaScript.

Open dev tools, click Sources.

Open/view solar.dart.

Scroll down to line 208, which should read:

&quot;Point pos = _calculatePos(x, y);&quot;

Click line 208.

ACTUAL BEHAVIOR:

The program stops, but line 210 is highlighted.

EXPECTED:

The program stops, on line 208.

Using editor Dart Editor version 0.3.2_r17657

**Comment by sigmundch** [comment]
I'm going to close this bug as stale, but feel free to reopen if you see issues.
