### ISSUE TITLE
PartialMetadataAnnotation.cachedNode should include "@"

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#8326]
From dart/tests/compiler/dart2js/metadata_test.dart:

&nbsp;&nbsp;// TODO(ahe): The node does not include &quot;@&quot;. Fix that.
&nbsp;&nbsp;Expect.stringEquals('@$node', yield);

**Comment by rakudrama** [comment]
Obsolete, dart2js no longer supports mirrors.
