### ISSUE TITLE
Improve error message for import of dart:io

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#8329]
Users of the dart2js option --output-type=dart (aka dart2dart) get a cryptic error message when trying to import libraries such as dart:io:

embiggen.dart:1:8: Error: library not found dart:io
import 'dart:io';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^

See issue #8174.

**Comment by karlklose** [comment]
dart2dart is no longer supported.
