### ISSUE TITLE
dart2js should not assign static mutable fields with functions.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#8430]
Currently static mutable fields that are initialized with static functions are directly assigned. This means that v8 includes the function in its map. When the static field is changed the isolate goes through a map-transition.

Example:
foo() =&gt; 499;
var x = foo;

main() {
&nbsp;&nbsp;x();
&nbsp;&nbsp;x = () =&gt; 42;  // Map transition for the isolate.
&nbsp;&nbsp;x();
}

**Comment by karlklose** [comment]
@floitschG Could you update the status of this bug?

**Comment by floitschG** [comment]
Doesn't seem to be an issue with the latest dart2js version.

```
staticFun() => 4222;

final x = (() { return 499; }) ();
var y = staticFun;

foo() {
  var sum = 0;
  for (int i = 0; i < 100000; i++) {
    sum += x;
    sum = sum & 0xFFFFFF;
  }
  return sum;
}

main() {
  for (int j = 0; j < 1000; j++) { foo(); }

  var sw = new Stopwatch()..start();
  for (int j = 0; j < 1000; j++) { foo(); }
  print(sw.elapsedMilliseconds);
  print(y());
  y = 421;
  print(y);
  for (int j = 0; j < 1000; j++) { foo(); }
  sw.reset();
  for (int j = 0; j < 1000; j++) { foo(); }
  print(sw.elapsedMilliseconds);
}
```
