### ISSUE TITLE
Bad diagnostic for duplicated imports

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#8464]
I changed sdk/lib/_internal/compiler/implementation/js_backend/js_backend.dart to import js.dart as jsAst, and added an this top-level field to js.dart:

const js = const jsAst.JsBuilder();

This resulted in this error message:

sdk/lib/_internal/compiler/implementation/js_backend/js_backend.dart:38:7: Warning: duplicated definition
const js = const jsAst.JsBuilder();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^
Error: duplicate definition

Turns out that we are saying:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compiler.reportError(import.prefix, 'duplicate definition');

Not:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compiler.withCurrentElement(importingLibrary, () {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compiler.reportError(import.prefix, 'duplicate definition');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});

In importLibrary in library_loader.dart. With that change, I get this error message:

sdk/lib/_internal/compiler/implementation/js_backend/js_backend.dart:38:7: Warning: duplicated definition
const js = const jsAst.JsBuilder();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^
sdk/lib/_internal/compiler/implementation/ssa/ssa.dart:10:27: Error: duplicate definition
import '../js/js.dart' as js;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^

Which is better, but still not good enough. I'd also like to know where the import declaration is, that is, where in ssa.dart is the import of js_backend.dart?

**Comment by johnniwinther** [comment]
This has been rendered obsolete by the change in prefix/non-prefix import semantics in https://codereview.chromium.org//27008003
