### ISSUE TITLE
Provide one canonical way to deprecate code, that does not require a package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#8476]
There are at least three ways I've seen to deprecate code (from the core libraries)

package meta's @­deprecated

/**
&nbsp;* @­deprecated
&nbsp;*/

/**
&nbsp;* Deprecated.
&nbsp;*/

I'd love to see a single, canonical way to mark code as deprecated, without requiring me to install a package.

Deprecation is common through API evolution.

**Comment by lrhn** [comment]
We now have `@deprecated` with `deprecated` declared in `dart:core`.
