### ISSUE TITLE
common functionality of "dart:io" should work in Dartium

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#8640]
Currently using 'dart:io' in dart code that runs in dartium gives you an error of the form:

&quot;Failed to load a file dart:io&quot;

Long ago we added support for importing dart:io in dart2js so we can use the common part that is platform independent (e.g. Path). 

Now we are hitting a similar issue in Dartium. We have a dartium extension that transitively imports dart:io. We don't expect all APIs to work, but basic path manipulation should work, path separators, etc.

**Comment by floitschG** [comment]
Dartium has been removed from the repository.
