### ISSUE TITLE
Unnecessary bailout for known num receiver

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#8648]
Consider this snippet from dart/samples/swarm/DataSource.dart:

&nbsp;&nbsp;static Section decode(Decoder decoder) {
&nbsp;&nbsp;&nbsp;&nbsp;final sectionId = decoder.readString();
&nbsp;&nbsp;&nbsp;&nbsp;final sectionTitle = decoder.readString();

&nbsp;&nbsp;&nbsp;&nbsp;final nSources = decoder.readInt();
&nbsp;&nbsp;&nbsp;&nbsp;final feeds = new ObservableList&lt;Feed&gt;();
&nbsp;&nbsp;&nbsp;&nbsp;for (int j=0; j &lt; nSources; j++) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;feeds.add(Feed.decode(decoder));
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return new Section(sectionId, sectionTitle, feeds);
&nbsp;&nbsp;}

This compiles to:

$.Section_decode = function(decoder) {
&nbsp;&nbsp;var sectionId, sectionTitle, nSources, feeds, j;
&nbsp;&nbsp;sectionId = decoder.readString$0();
&nbsp;&nbsp;sectionTitle = decoder.readString$0();
&nbsp;&nbsp;nSources = decoder.readInt$0();
&nbsp;&nbsp;if (typeof nSources !== &quot;number&quot;)
&nbsp;&nbsp;&nbsp;&nbsp;return $.Section_decode$bailout(1, decoder, sectionId, sectionTitle, nSources);
&nbsp;&nbsp;feeds = $.ObservableList$(null, $.Feed);
&nbsp;&nbsp;for (j = 0; j &lt; nSources; ++j)
&nbsp;&nbsp;&nbsp;&nbsp;feeds.add$1($.Feed_decode(decoder));
&nbsp;&nbsp;return $.Section$(sectionId, sectionTitle, feeds);
};

$.Section_decode$bailout = function(state0, decoder, sectionId, sectionTitle, nSources) {
&nbsp;&nbsp;var feeds, j;
&nbsp;&nbsp;feeds = $.ObservableList$(null, $.Feed);
&nbsp;&nbsp;for (j = 0; $.CONSTANT9.$lt(j, nSources); ++j)
&nbsp;&nbsp;&nbsp;&nbsp;feeds.add$1($.Feed_decode(decoder));
&nbsp;&nbsp;return $.Section$(sectionId, sectionTitle, feeds);
};

But it could be:

$.Section_decode = function(decoder) {
&nbsp;&nbsp;var sectionId, sectionTitle, nSources, feeds, j;
&nbsp;&nbsp;sectionId = decoder.readString$0();
&nbsp;&nbsp;sectionTitle = decoder.readString$0();
&nbsp;&nbsp;nSources = decoder.readInt$0();
&nbsp;&nbsp;if (typeof nSources !== &quot;number&quot;)
&nbsp;&nbsp;&nbsp;&nbsp;throw $.$$throw($.ArgumentError$(nSources));
&nbsp;&nbsp;feeds = $.ObservableList$(null, $.Feed);
&nbsp;&nbsp;for (j = 0; j &lt; nSources; ++j)
&nbsp;&nbsp;&nbsp;&nbsp;feeds.add$1($.Feed_decode(decoder));
&nbsp;&nbsp;return $.Section$(sectionId, sectionTitle, feeds);
};

**Comment by karlklose** [comment]
We do no longer generate bailout functions.
