### ISSUE TITLE
dart2js should not use windows.setTimeout with a delay of 0 to implement Future.immediate

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#8757]
Using windows.setTimeout with a delay of 0 doesn't do what we expect, as the next timer event may occur much later.

MDN recommends using windows.postMessage, see https://developer.mozilla.org/en/docs/DOM/window.setTimeout#Minimum_delay_and_timeout_nesting

This poses another problem as whatever message is posted might confuse user code.

It looks like a better alternative is to use MessageChannel, or an iframe.

**Comment by floitschG** [comment]
The code for microtasks doesn't use setTimeout anymore.
