### ISSUE TITLE
Provide a convenient way of working with the characters in strings

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#8782]
Particularly with the removal of splitChars(), we have no convenient mechanism for working with strings as if they consisted of characters. We have APIs that return different numbers, or ones that return strings that may or may not contain characters in the string.

So, instead of 
&nbsp;&nbsp;someString.first = &quot;a&quot;
we get to write
&nbsp;&nbsp;new String.fromCharCode(someString.runes.first) = &quot;a&quot;

or to iterate, instead of 
&nbsp;&nbsp;&nbsp;for (var each in someString.splitChars())
we get
&nbsp;&nbsp;&nbsp;for (var each in someString.runes.map((x) =&gt; new String.fromCharCode(x)))

These are both much longer and much less obvious, requiring users to worry about concepts like runes. Or, more likely, to write code that assumes the indexing operations always give valid characters, which will work until it doesn't.

It would be much nicer in general if we could treat strings as iterables and be able to ask for the first, iterate over the characters, map them, etc.

**Comment by floitschG** [comment]
Strings allow access to the individual codeunits as strings.
