### ISSUE TITLE
Many constructors can be generated dynamically

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#8827]
Given this class:

class Point {
&nbsp;&nbsp;var x;
&nbsp;&nbsp;var y;
&nbsp;&nbsp;Point(this.x, this.y);

&nbsp;&nbsp;operator +(Point other) {
&nbsp;&nbsp;&nbsp;&nbsp;return new Point(x + other.x, y + other.y);
&nbsp;&nbsp;}

&nbsp;&nbsp;String toString() =&gt; &quot;($x, $y)&quot;;
}

dart2js will generate:

$$.Point = {&quot;&quot;: &quot;Object;x&gt;,y&gt;&quot;,
&nbsp;&nbsp;toString$0: function() {
&nbsp;&nbsp;&nbsp;&nbsp;return &quot;(&quot; + $.S(this.x) + &quot;, &quot; + $.S(this.y) + &quot;)&quot;;
&nbsp;&nbsp;}
};
$.Point$ = function(x, y) {
&nbsp;&nbsp;return new $.Point(x, y);
};

The latter is the constructor, and it can be generated dynamically, or even:

$.Point$ = $.Point;

**Comment by karlklose** [comment]
Verified fixed in 79a8654e5fb30dfce902636961d6a5ffb69e6f85.
