### ISSUE TITLE
No way to globally capture exceptions

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#8875]
I would like a way to register a global exception handler, to capture exceptions that my code fails to catch. This can prevent my program from exiting due to buggy 3rd party libraries, misused Timers, or other unexpected circumstances.

Thanks!

**Comment by lrhn** [comment]
We now have `Isolate.current.addErrorListener` and `Isolate.current.setErrorsFatal` along with the `Zone` based solutions.
