### ISSUE TITLE
make Libraries first class

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#893]
[user feedback]
Please make Libraries first class. Let's modernize.

library CustomLib {
&nbsp;&nbsp;//members go here
}

**Comment by munificent** [comment]
"First-class libraries" has been a discussion topic for ages. There are a lot of really really cool reasons to do it, but also a lot of very complex implications. (I could be wrong, but as far as I know, the static typing story for them is still unsolved.)

It's also a nebulous topic. It's not clear is actually being proposed or requested. There's a spectrum between, roughly, C++ namespaces all the way to Newspeak-style libraries.

Given that, this isn't very actionable. I'm not going to say that we'll never have something akin to first class libraries, but this particular issue doesn't give us much to grab onto so I'm going to go ahead and close it.
