### ISSUE TITLE
Debugging utility

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#894]
[user feedback]
Hi Dart Team,

I haven't actually asked about this during the Hackathon, but the following is something nice to have.

A Debugging utility with these functionalities:
(1) Prints out where the printing occurs in code: file name, class name, function name, line number, etc (each of these information can be configured to be on/off).  For example, printDebug('Hi') may print out 'FileX.ClazzA.methodB:15: Hi', or just 'FileX:15:Hi', depending how it is configured by the dart program.

(2) Be able to configurate so that only print satements of a certain file/class/function is exposed.  For example, I can do 'expose: A, expose B.f1', and only print statements in class A and in class B's f1 method is exposed, and all other prints are hidden from console.

(3) IMPORTANT: When a print is specified to be not exposed (i.e., not used), then it is not compiled to javascript, or is completely ingored by an VM, as if the print statements are commented out.  We discovered that just having if checks and string concatentations, without actually printing to console, can cause a big performance downgrade.

(4) Have the debug output logged to a file somewhere.  This may be a but tricky to do though.

If you can let me (yiuyuho@) know when something like this is ready, that would be great =).
Thanks.

**Comment by sethladd** [comment]
The VM has a service protocol: https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md

The dart:developer library has a call to trigger the debugger: https://github.com/dart-lang/sdk/blob/master/sdk/lib/developer/developer.dart
