### ISSUE TITLE
Using type parameters can slow down your program with x10 

### ISSUE THREAD

**Issue by larsbak** [dart-lang/sdk#8972]
The code below has been created to measure the impact of using type parameters in &quot;new&quot; expressions. If such a new expression is combined with an &quot;is&quot; check the benchmark is 10 times slower. Please note complex also uses twice the heap memory. Canonicalization or caching of type information is needed to fix this.
//Lars

// Method used   Heap VmRSS Runtime
// complex           ~320MB  7.2 sec.
// complextWithCheck ~205MB 31.7 sec.
// simple            ~154MB  2.6 sec.
// simpleWithCheck   ~154MB  3.2 sec.

class B { B(); }
class A&lt;T&gt; { A(); }

class C&lt;S,T&gt; {
&nbsp;&nbsp;A&lt;T&gt; complex() =&gt; new A&lt;T&gt;();

&nbsp;&nbsp;A&lt;T&gt; complexWithCheck() {
&nbsp;&nbsp;&nbsp;&nbsp;var a = new A&lt;T&gt;();
&nbsp;&nbsp;&nbsp;&nbsp;return a is A&lt;T&gt; ? a : a;
&nbsp;&nbsp;}

&nbsp;&nbsp;B simple() =&gt; new B();

&nbsp;&nbsp;B simpleWithCheck() {
&nbsp;&nbsp;&nbsp;&nbsp;var b = new B();
&nbsp;&nbsp;&nbsp;&nbsp;return b is B ? b : b;
&nbsp;&nbsp;}
}

main() {
&nbsp;&nbsp;const int max = 10000000;
&nbsp;&nbsp;final a = new C&lt;B,B&gt;();
&nbsp;&nbsp;final c = new List(max);
&nbsp;&nbsp;for (int i = 0; i &lt; max; i++) c[i] = a.simple();
}

**Comment by fsc8000** [comment]
This can be closed as fixed.

simpleWithCheck:
real	0m1.111s
user	0m1.194s
sys	0m0.236s

complexWithCheck:
real	0m1.176s
user	0m1.278s
sys	0m0.244s
