### ISSUE TITLE
Single stepping does not stop at continue statements!

### ISSUE THREAD

**Issue by larsbak** [dart-lang/sdk#8976]
Single stepping stops at &quot;return&quot; but not at &quot;continue&quot;.
Must be a bug.
//Lars

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2|  for (int i = 0; i &lt; 1; i++) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1|    if (i == 0) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1|      print(&quot;yes&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|      continue;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|    }
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  }
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1|  return;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|}

**Comment by mhausner** [comment]
As designed.
