### ISSUE TITLE
Allow multiple parameters for the [] and []= operators.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#8980]
We could allow multiple parameters on the [] and []= operators, e.g.,

```dart
class Matrix2D<V> {
  V operator[](int x, int y);
  void operator[]=(V value, int x, int y);
}
```

That would allow multi-dimensional lookups and assignments with a good-looking syntax. Usage would be the expected:

```dart
matrix[2,4] = matrix[1,3] + 1;
```

Using the wrong number of parameters for an object would be a noSuchMethod call, just as for a similar methods.

The alternative is to write "get" and "set" methods, which isn't as readable.

The necessary grammar changes is to allow the same arguments between [] as between () in a call, and relax the requirements on arguments for operator[] and operator[]=. 
I put the value of operator[] first, so that it's possible to use named parameters, e.g. `foo[x:42, y:12] = 10`. 

We can also disallow optional parameters to begin with.

(This was not my idea, but I liked it when I heard it!)

**Comment by munificent** [comment]
Closing as duplicate of https://github.com/dart-lang/language/issues/2534.
