### ISSUE TITLE
StreamSubscription.cancel should fire the onDone callback

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#9026]
Currently, if a StreamSubscription is cancelled, there's no way for the callbacks listening on that subscription to know that it's been cancelled. A listener that's been cancelled is indistinguishable from a stream that's just taking a long time to emit its next value. This makes it easy for programmers to accidentally insert deadlocks in their code were an unsubscription causes a listener to wait forever.

I think the best solution here is to make StreamSubscription.cancel send an onDone event, as though the stream itself had closed.

The same issues are also present when unsubscribeOnError is set to true.

**Comment by nex3** [comment]
I no longer need this behavior.

**Comment by lukaspili** [comment]
Encountered this issue as well. Initial thought was that my broadcasted stream's source was not ending the stream properly when there was no more subscribers (as it was supposed to).

I think this behaviour can look like a bug for newcomers to dart streams like me, and should be documented on `cancel()` and/or `onDone()`.

**Comment by RodrigoBertotti** [comment]
I created a package called [StreamD](https://github.com/RodrigoBertotti/stream_d) that emits the `onDone` event even when `streamSubscription.cancel()` is called, it may be useful in some scenarios. The package is based on the default Dart Stream

**Comment by yosus** [comment]
I agree. The [docs ](https://api.flutter.dev/flutter/dart-async/StreamSubscription/onDone.html)should be amended as such, to make it clear that `onDone` is not called

`Replaces the done event handler of this subscription. This is not invoked when StreamSubscription `cancel()` is called.`
