### ISSUE TITLE
Change the paths returned for script urls

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#9031]
I have some pretty unfortunate logic in the Editor's debugger to recognize when a script's source should be requested from Dartium vs. read from the local file system. I'd like to clean that code up. Right now I look for scripts with path's similar to:

file:///Volumes/data/b/build/slave/dartium-mac-inc/build/src/xcodebuild/DerivedSources/Release/webkit/bindings/dart/dart/html/Element.dart

but I'd much rather the url was something that started with 'dart:'. In this case, maybe something like 'dart:html/Element.dart'.

**Comment by iposva-google** [comment]
Stale.
