### ISSUE TITLE
best case dart2js output 6.5X bigger than best case dart2dart

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#9150]
Output size of dart2dart: 44860
Output size of dart2dart + gzip: 11461
Output size of dart2dart + minify: 23743
Output size of dart2dart + minify + gzip: 8721
Output size of dart2js: 612234
Output size of dart2js + minify: 289840
Output size of dart2js + minify + gzip: 56496

Best case for Dart: 8721
Best case for Dart2Js: 56496

Please see attached.

original code from: https://github.com/sethladd/lawndart/tree/master/example/todo (using out/index.html_bootstrap.dart, which is generated by running build.dart)

This project uses:

\* dart:html
\* Web UI
\* Local storage
\* WebSQL
\* IndexedDB

I hope I got everything right here, please let me know if I missed something. If there's something else I can provide, please let me know. Thanks!

sethladd:~/Code/lawndart/example/todo/out (master)$ ~/Desktop/dart/dart-sdk/bin/dart --version
Dart VM version: 0.4.1.0_r19425 (Mon Mar  4 22:47:26 2013)

______
**Attachments:**
[index_dart.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-9150/comment-0/index_dart.dart) (0 Bytes)
[index_dart.js](https://storage.googleapis.com/google-code-attachments/dart/issue-9150/comment-0/index_dart.js) (597.88 KB)
[index_dart.minify.js](https://storage.googleapis.com/google-code-attachments/dart/issue-9150/comment-0/index_dart.minify.js) (283.05 KB)

**Comment by sigmundch** [comment]
we are now actively tracking code size in our dashboard to make sure we make steady progress on this.
