### ISSUE TITLE
Error message for part of

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#9155]
When importing files that have a 'part of' directerive instead of 'part', the error message given is:

&quot;Error: line 1 pos6: url expected&quot;.

This is obscure and hard to decipher.

I expect the error message to tell me that i'm not importing a library and to guide me to the correct file to import.

////////////////////////////////////////////////////////////////////////////////////
Editor: 0.4.1_r19425 (2013-03-04)
OS: Mac OS X - i386 (10.8.2)
JVM: 1.6.0_43
# projects: 8
# open dart files: 6
auto-run pub: true
mem max/total/free: 1497 / 557 / 174 MB
thread count: 44
analysis: 0 tasks, 27 libraries, 3 contexts
index: 105756 relationships and 0 attributes in 18543 elements in 275 resources stored in 3 MB on disk

SDK installed: true
Dartium installed: true

**Comment by iposva-google** [comment]
```
dart ~/dart/Bug9155.dart 
'file:///Users/iposva/dart/Bug9155.dart': error: line 3 pos 6: url expected
part of foo.bar;
     ^
```

**Comment by peter-ahe-google** [comment]
The OP said:

> I expect the error message to tell me that i'm not importing a library and to guide me to the correct file to import.

However, the quoted error message is unchanged.

**Comment by iposva-google** [comment]
Thank you for your concern. However there is no plan to fix this error message.
