### ISSUE TITLE
Boggle solver 2.1X slower on dart2js than Dart VM

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#9255]
Hi,

I hope this is a useful and real-life benchmark for the dart2js. I ported this to Dart and JavaScript, trying very hard to be line-by-line accurate. On my MBP, here are the times that I get:

(note: all times are averaged over 5 runs, each run loads, parses, and solves. This is the &quot;cold start&quot; test)

V8 + JS:
&nbsp;&nbsp;parse the dictionary: 275ms 
&nbsp;&nbsp;solve: 0.75ms

V8 + dart2js:
&nbsp;&nbsp;parse the dictionary: 700ms
&nbsp;&nbsp;solve: 5ms

Dart VM + Dart + Dartium:
&nbsp;&nbsp;parse the dictionary: 5000ms  (?!?)
&nbsp;&nbsp;solve: 1.5ms

Timings were derived with window.performance.now()

Dictionary has something like 17k words in it. The board is a classic 4x4 matrix.

You can find this code here:

Dart Solver: https://github.com/johnmccutchan/tilebasedwordsearch/blob/master/lib/solver.dart
Dart Trie: https://github.com/johnmccutchan/tilebasedwordsearch/blob/master/lib/trie.dart
Dart HTML file: https://github.com/johnmccutchan/tilebasedwordsearch/blob/master/web/solver/solver.html
Dart HTML script: https://github.com/johnmccutchan/tilebasedwordsearch/blob/master/web/solver/solver.dart

JS Solver: https://github.com/johnmccutchan/tilebasedwordsearch/blob/master/web/solver/solver.js
JS HTML file: https://github.com/johnmccutchan/tilebasedwordsearch/blob/master/web/solver/solver_js.html

To get the exact code as I tested it, get the tree at 
https://github.com/johnmccutchan/tilebasedwordsearch/tree/f42057320f958e0932ed3c9403c8c6752aa24ce9

(interestingly, the VM takes much longer to parse the dictionary file, but I think that's a separate bug)

**Comment by hartsantler** [comment]
what happened to this issue, its a type-defect and triaged?
why is the performance of map so bad with dart2js?

**Comment by sethladd** [comment]
This issue is really old... we'll have to measure again. There may not be a performance issue anymore.

**Comment by sigmundch** [comment]
There is some work happening on this, though. Traditionally Dart maps are implemetned by dart2js using multiple JS objects, so there is a possibility that the issue still exists. @hterkelsen is looking into making the map implementation faster by using ES6 maps whenever the keys of the map use the identity-hashcode, which should include int and string keys.

**Comment by karlklose** [comment]
@hterkelsen Is this still an issue?

**Comment by hterkelsen** [comment]
Yes, I have not enabled ES6 maps for Maps with identity-hashcode keys

**Comment by matanlurey** [comment]
I imagine this specific benchmark is not super important to us anymore
