### ISSUE TITLE
Looks like unwrapException is incorrectly deferred

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#9338]
FAILED: dart2js-ff release_ia32 dart2js_extra/deferred/deferred_constant_test
Expected: pass crash 
Actual: fail

stdout:

&nbsp;&nbsp;&lt;h1&gt; Running /e:/b/build/slave/dart2js-ff-win7-1-2/build/dart/tests/compiler/dart2js_extra/deferred/deferred_constant_test.dart &lt;/h1&gt;
&nbsp;&nbsp;&lt;script src=&quot;/root_dart/pkg/unittest/lib/test_controller.js&quot; type=&quot;text/javascript&quot;&gt;
&nbsp;&nbsp;&lt;/script&gt;
&nbsp;&nbsp;&lt;script onerror=&quot;externalError(null)&quot; src=&quot;/root_build/generated_tests/dart2js-ff/tests_compiler_dart2js_extra_deferred_deferred_constant_test/test.js&quot; type=&quot;text/javascript&quot;&gt;
&nbsp;&nbsp;&lt;/script&gt;
&nbsp;&nbsp;&lt;script src=&quot;/root_dart/pkg/browser/lib/dart.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;

&lt;script type=&quot;text/javascript&quot; async=&quot;&quot; src=&quot;http://127.0.0.1:51052/root_build/generated_tests/dart2js-ff/tests_compiler_dart2js_extra_deferred_deferred_constant_test/part.js&quot;&gt;&lt;/script&gt;&lt;pre&gt;PASS&lt;/pre&gt;&lt;pre&gt;Error: 

http://127.0.0.1:51052/root_build/generated_tests/dart2js-ff/tests_compiler_dart2js_extra_deferred_deferred_constant_test/test.js:1559:
TypeError: $.unwrapException is not a function

&lt;/pre&gt;&lt;pre&gt;FAIL&lt;/pre&gt;&lt;pre&gt;FAIL&lt;/pre&gt;

To retest, run:  e:\b\build\slave\dart2js-ff-win7-1-2\build\dart\tools\testing\bin\windows\dart.exe /e:/b/build/slave/dart2js-ff-win7-1-2/build/dart/tools/testing/dart/http_server.dart -p 51052 -c 51053 --build-directory=e:\b\build\slave\dart2js-ff-win7-1-2\build\dart\build\ReleaseIA32

Compilation command: build\ReleaseIA32\dart-sdk\bin\dart2js.bat &quot;--package-root=build/ReleaseIA32/packages/&quot; &quot;--out=e:/b/build/slave/dart2js-ff-win7-1-2/build/dart/build/ReleaseIA32/generated_tests/dart2js-ff/tests_compiler_dart2js_extra_deferred_deferred_constant_test/test.js&quot; &quot;/e:/b/build/slave/dart2js-ff-win7-1-2/build/dart/tests/compiler/dart2js_extra/deferred/deferred_constant_test.dart&quot;

Command line: python &quot;e:\b\build\slave\dart2js-ff-win7-1-2\build\dart\tools\testing\run_selenium.py&quot; &quot;--browser=ff&quot; &quot;--timeout=240&quot; &quot;--out=http://127.0.0.1:51052/root_build/generated_tests/dart2js-ff/dart2js_extra_deferred_deferred_constant_test.dartdart2js-ff.html?crossOriginPort=51053&quot;

**Comment by karlklose** [comment]
The test does not exist anymore, the other deferred_constant_tests are expected to (and currently seem to) pass, and the issue this blocked has been resolved. Please reopen, if this problem persists.
