### ISSUE TITLE
HttpRequest Global Listeners

### ISSUE THREAD

**Issue by giovannicandido** [dart-lang/sdk#9381]
Thats not exactly a problem, but a core feature or improvement. As a web developer I want be able to listen to all request across libraries, so I can attach behavior like security permission across client and server, or simply give a nice user feedback, or trying to connect again to the server. The point here is that I can't do this using Futures, because a Future is bonded to the caller and I can't listen everything. One workaround is to build a singleton class that wraps the HttpRequest class and construct the HttpRequest, attach you own listen before returning and them forwards the events to the outside world in a static or global way. But that is not global because other libraries will not be using my class they will use the HttpRequest and the custom class will not be able to catch this events.

There is a use case:

After all request the server send a custom HttpCode that mean the user does not have rights to do that call, and than a global listen can inspect for that request and make I nice message to the user telling this and giving he a option to login as a different user, or even disabling the button that has clicked. I'm not speaking about a web page I'm speaking about a only ajax application where you can't do this in the server because all UI is running on the client and you don't have page loads (the page load only once)
Another use case is, well we need give feedback to the users, and is simple but not likely write the same code across the code using futures, well you of course put that in a separate reusable class, but you still have to call this class everywhere, with global listen you attach that once and give the proper feedback. This two concepts listeners and Futures work very well together, you can still make your request and use the response latter and the specific code bonded with the caller can still runs as well the listener at the same time.

Maybe I just don't see how to do this in the HttpRequest class or any else class.
But here is a implementation for a custom class that wraps the HttpRequest class and is working, but as I said I can do this only for my code the other libraries do not know of the existence of this class, I will call it Ajax class:

/**
* A class for Ajax requests. This class can dispatch global events for the common [HttpRequest] events.
* This Class is a subclass of [HttpRequest] you can use this class as usual
*/
class Ajax implements HttpRequest {
&nbsp;&nbsp;// The stream methods to dispatch
&nbsp;&nbsp;static StreamController _onAbortStreamController = new StreamController.broadcast();
&nbsp;&nbsp;static StreamController _onErrorStreamController = new StreamController.broadcast();
&nbsp;&nbsp;static StreamController _onLoadStreamController = new StreamController.broadcast();
&nbsp;&nbsp;static StreamController _onLoadEndStreamController = new StreamController.broadcast();
&nbsp;&nbsp;static StreamController _onLoadStartStreamController = new StreamController.broadcast();
&nbsp;&nbsp;static StreamController _onProgressStreamController = new StreamController.broadcast();
&nbsp;&nbsp;/**
&nbsp;&nbsp;&nbsp;* Return a request that always have one listen to forward globally
&nbsp;&nbsp;&nbsp;* Dispatches the event for the world. All the events that this class support have to be added here
&nbsp;&nbsp;&nbsp;* This method always return a new HttpRequest
&nbsp;&nbsp;&nbsp;*/
&nbsp;&nbsp;factory Ajax(){
&nbsp;&nbsp;&nbsp;&nbsp;HttpRequest request = new HttpRequest();
&nbsp;&nbsp;&nbsp;&nbsp;request.onAbort.listen( (event) =&gt; _onAbortStreamController.add(event));
&nbsp;&nbsp;&nbsp;&nbsp;request.onError.listen( (event) =&gt; _onErrorStreamController.add(event));
&nbsp;&nbsp;&nbsp;&nbsp;request.onLoad.listen( (event) =&gt; _onLoadStreamController.add(event));
&nbsp;&nbsp;&nbsp;&nbsp;request.onLoadEnd.listen( (event) =&gt; _onLoadEndStreamController.add(event));
&nbsp;&nbsp;&nbsp;&nbsp;request.onLoadStart.listen( (event) =&gt; _onLoadStartStreamController.add(event));
&nbsp;&nbsp;&nbsp;&nbsp;request.onProgress.listen( (event) =&gt; _onProgressStreamController.add(event));

&nbsp;&nbsp;&nbsp;&nbsp;return request;
&nbsp;&nbsp;}
&nbsp;&nbsp;/**
&nbsp;&nbsp;&nbsp;* Ajax return HttpRequest so, the constructor is private
&nbsp;&nbsp;&nbsp;*/
&nbsp;&nbsp;Ajax._private(){

&nbsp;&nbsp;}

&nbsp;&nbsp;/// A global stream for onAbort
&nbsp;&nbsp;static Stream&lt;HttpRequestProgressEvent&gt; get onGlobalAbort =&gt; _onAbortStreamController.stream;
&nbsp;&nbsp;/// A global stream for onError
&nbsp;&nbsp;static Stream&lt;HttpRequestProgressEvent&gt; get onGlobalError =&gt; _onErrorStreamController.stream;
&nbsp;&nbsp;/// A global stream for handle onLoad
&nbsp;&nbsp;static Stream&lt;HttpRequestProgressEvent&gt; get onGlobalLoad =&gt; _onLoadStreamController.stream;
&nbsp;&nbsp;/// A global stream for handle onLoadEnd
&nbsp;&nbsp;static Stream&lt;HttpRequestProgressEvent&gt; get onGlobalLoadEnd =&gt; _onLoadEndStreamController.stream;
&nbsp;&nbsp;/// A global stream for handle onLoadStart
&nbsp;&nbsp;static Stream&lt;HttpRequestProgressEvent&gt; get onGlobalLoadStart =&gt; _onLoadStartStreamController.stream;
&nbsp;&nbsp;/// A global stream for handle onProgress
&nbsp;&nbsp;static Stream&lt;HttpRequestProgressEvent&gt; get onGlobalProgress =&gt; _onProgressStreamController.stream;

}

A exemple of how to use this class. Lets say we have a ExceptionView class that will inspect for errors or messages from the server and make a nice popup to the user (using the Notify class):

/**
&nbsp;* Classe para escuta de eventos globais e apresentacao de notificacoes genericas para o usuário.
&nbsp;* Essa classe usa [Notify] e [Ajax]
&nbsp;* A class for listen to global request Events and do nice user feedback. This class uses [Notify] and [Ajax]
&nbsp;* Date: 19/03/13
&nbsp;* Time: 18:22
&nbsp;*/
class ExceptionView {
&nbsp;&nbsp;static ExceptionView _instance;
&nbsp;&nbsp;factory ExceptionView(){
&nbsp;&nbsp;&nbsp;&nbsp;if(_instance == null){
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_instance = new ExceptionView._private();
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return _instance;
&nbsp;&nbsp;}
&nbsp;&nbsp;ExceptionView._private() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ajax.onGlobalError.listen(_onError);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ajax.onGlobalLoad.listen(_onSuccess);
//    HttpRequest.onErrorEvent.listen(_onError); // I can't do that
//   HttpRequest.onLoadEvent.listen(_onSuccess); // I can't do that
&nbsp;&nbsp;}
&nbsp;&nbsp;void _onError(HttpRequestProgressEvent event){
&nbsp;&nbsp;&nbsp;&nbsp;var target = event.target;
&nbsp;&nbsp;&nbsp;&nbsp;if(target.response == null){
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new Notify().msg(title: 'Erro ao processar requisição', message: '''Houve um erro desconhecido ao
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;processar a requisição. Código do Erro: ${t.status}''', useNotificationsApi: false);
&nbsp;&nbsp;&nbsp;&nbsp;}else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new Notify().msg(title: 'Erro ao processar requisição', message: target.responseText, useNotificationsApi: false);
&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;}
&nbsp;&nbsp;/**
&nbsp;&nbsp;* Display messages on the screen, if the message is not a Json message then display a error to the user.
&nbsp;&nbsp;* If the response is a json string and have the property &quot;message&quot; display a message to the user. If not do nothing,
&nbsp;&nbsp;* If the message have the property success with value false and the message property, display a error message
&nbsp;&nbsp;* to the user with the message property
&nbsp;&nbsp;*/
&nbsp;&nbsp;void _onSuccess(HttpRequestProgressEvent event){
&nbsp;&nbsp;&nbsp;&nbsp;Map result;
&nbsp;&nbsp;&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result = JSON.parse(event.target.responseText);
&nbsp;&nbsp;&nbsp;&nbsp;} catch(e){
&nbsp;&nbsp;&nbsp;&nbsp;/// If the response is not Json treat as Error, I don't use the Notifications API because the response can be a very
&nbsp;&nbsp;&nbsp;&nbsp;/// long server response like a Http Page.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new Notify().msg(title: 'Ocorreu um erro no servidor',message: event.target.responseText, useNotificationsApi: false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stay: true );
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;// Only show a message if there is a message property on the response and the message isn't empty
&nbsp;&nbsp;&nbsp;&nbsp;if(result != null &amp;&amp; result['message'] != null){
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(result['message'].trim() == &quot;&quot;){ // If message is a empty string do nothing
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// Verifica se existe uma propriedade success na resposta e formata-a o titulo de acordo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String title = result['success'] == true || result['success'] == null ? 'OK' : 'Error';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool stay = result['success'] == true || result['success'] == null ? false : true;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new Notify().msg(title: title, message: result['message'], stay: stay);
&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;}
}

I use Dart 0.4.2.8_r20259

Here is a post about this subject on google groups: https://groups.google.com/a/dartlang.org/d/topic/misc/-oQ6eYwuKdg/discussion

Sorry any wrong written but english is not my native language. 

Thank you for your time.

&nbsp;

**Comment by matanlurey** [comment]
Many libraries implement these type of indirections, we don't need to in the SDK.
