### ISSUE TITLE
VM debugger API support ignores isolateId parameters

### ISSUE THREAD

**Issue by tomball** [dart-lang/sdk#9537]
Most Dart Debugger protocol commands take an isolateId parameter, because spawnURI can load different source with the same URL.  However, none of the DbgMessage's Handle\*Cmd functions reference that parameter, and the related functions in debugger_api_impl.cc all use Isolate::Current().

**Comment by rmacnak-google** [comment]
Legacy debugging protocol removed in 6249c2bcf3cb4a2241dd27caf087f07ea05147b3.

C embedding API uses the current isolate which can be changed with Dart_EnterIsolate.
