### ISSUE TITLE
Grammar for multiline comments is ambiguous

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#9548]
The grammar for multiline comments is:
&nbsp;&nbsp;MULTI_LINE_COMMENT:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'/\*' (MULTI_LINE_COMMENT | ~ '\*/')* '*/'

The grammar is specified using &quot;a common variant of EBNF&quot;, but I'm unable to find a variant that specifies what &quot;~&quot; means in this usage. In Antlr grammars the ~ operator can only be applied to a single character, not to a string of length &gt; 1. I'll assume that works as a negative look-ahead that matches a single character.

In that case, a nested comment start can be matched by either MULTI_LINE_COMMENT or ~'\*/'\*. I.e., &quot;/\*/**/\*/&quot; can be matched in more than one way, so that the last '*/' is either part of the comment or not.

Suggested grammar:
&nbsp;&nbsp;MULTI_LINE_COMMENT:
&nbsp;&nbsp;&nbsp;&nbsp;'/\*' MULTI_LINE_COMMENT_BODY* '\*'+ '/'
&nbsp;&nbsp;MULTI_LINE_COMMENT_BODY:
&nbsp;&nbsp;&nbsp;&nbsp;('/'+ (~('\*' | '/') | '\*' MULTI_LINE_COMMENT_BODY* '\*'+ '/') | '*'* ~('*' | '/')

**Comment by eernstg** [comment]
No milestone now: This correction will be considered as part of a larger update of grammar related parts of the specification, based on [Dart.g](https://github.com/dart-lang/sdk/blob/master/docs/language/Dart.g).

**Comment by eernstg** [comment]
Closing: The syntax rules about multi-line comments are completely different today. They are used in Dart.g, and ANTLR parses essentially all language tests today, so I do not think there is anything to fix at this time.
