### ISSUE TITLE
dart2js: get rid of 'holders'

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#9556]
Types that are not instantiated but are used in type tests have 'holders'.
Instead of holders, the type should be generated. The generated type will be really small since it has no methods.

The interceptors should be used for primitive types.

**Comment by karlklose** [comment]
@rakudrama The comments containing TODOs refering to this bug seem to be completely out of sync - for example, there is no emitRuntimeTypeSupport anymore. I would like to close this issue and file a new one for the problem mentioned in your last comment (if that still is a problem).
