### ISSUE TITLE
add mapValues to Map<K, V>

### ISSUE THREAD

**Issue by polux** [dart-lang/sdk#9590]
I often find myself writing 

Map newMap = new Map();
m.forEach((k, v) {
&nbsp;&nbsp;newMap[k] = f(v);
});
...

It would be great if Map had a map or mapValues method instead:

Map newMap = m.mapValues(f);

**Comment by srawlins** [comment]
[Map.map](https://api.dartlang.org/dev/2.0.0-dev.47.0/dart-core/Map/map.html) has landed.
