### ISSUE TITLE
Unclear definition of self-referencing typedef

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#9592]
According to §15.3 it is 'a compile-time error if a typedef refers to itself  via a chain of references that does not include a class declaration.'

What 'include' means in this context is unclear. For instance, is this a valid typedef?

typedef F(List&lt;F&gt; list);

**Comment by sgrekhov** [comment]
All of the cases described above works now (produces compile-time errors). But the following cases still don't produce any errors in Dart (both checked and production modes) and dartanalyzer
typedef F1<F1>(F1 f);
typedef F2<F2>([F2 f]);
typedef F3<F3>({F3 f});

Tested on Dart VM version: 1.14.0-dev.1.0 (Wed Nov 18 18:17:16 2015) on "windows_x64"

**Comment by sgrekhov** [comment]
All of the cases listed the above are works now (produce compile-time erorrs). Tested on Dart VM version: 1.14.0-dev.1.0 (Wed Nov 18 18:17:16 2015) on "windows_x64"

**Comment by sgrekhov** [comment]
```dart
typedef F1<F1>(F1 f);
typedef F2<F2>([F2 f]);
typedef F3<F3>({F3 f});
```
The code above doesn't produce compile errors. I believe that it's according the spec but... Does it makes sense to allow typedefs like those above?

**Comment by munificent** [comment]
```dart
typedef F1<F1>(F1 f);
typedef F2<F2>([F2 f]);
typedef F3<F3>({F3 f});
```

These are OK, though confusing. They are declaring type parameters that shadow the name of the typedef itself.

Looks like the spec wording was tweaking and the implementations are doing the right thing, so I'm going to close this.
