### ISSUE TITLE
Performance difference with [] on typed arrays vs. typed array views

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#9596]
The attached example shows a performance degradation when using an array view.

In the view case, the optimizer is not able to eliminate the if-statement for the range check from the inlined body of Uint8ArrayView.[\]:

&nbsp;&nbsp;&nbsp;&nbsp;if (index &lt; 0 || index &gt;= length) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\_throwRangeError(index, length);
&nbsp;&nbsp;&nbsp;&nbsp;}

______
**Attachment:**
[uint8listview.dart](https://storage.googleapis.com/google-code-attachments/dart/issue-9596/comment-0/uint8listview.dart) (616 Bytes)

**Comment by iposva-google** [comment]
@fsc8000 Is this still an issue?

**Comment by fsc8000** [comment]
Yes, there is still a difference, but t is much smaller now though. I see around 30% depending on inlining/OSR instead of the original ~3x slowdown.

**Comment by fsc8000** [comment]
Closing as the original large slow-down seems fixed.
