### ISSUE TITLE
Dart embedder API returns isolate pointer, which can't be validated later

### ISSUE THREAD

**Issue by tomball** [dart-lang/sdk#9600]
The Dart embedder API (dart_api.h) defines a Dart_Isolate handle, which is used by several public-facing functions. Dart_Isolate is implemented as a cast of the memory address of the Isolate instance. Since the VM does not maintain an isolate list, it is possible to pass a handle to a deleted isolate as an unverifiable parameter to those functions.

**Comment by iposva-google** [comment]
Stale.
