### ISSUE TITLE
Flag missing hashCode

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#9671]
It would be great if teh analyzer/editor issued a warning whenever operator== is overriden but not hashCode (or the contrary).
////////////////////////////////////////////////////////////////////////////////////
Editor: 0.4.4_r20810 (2013-04-03)
OS: Linux - amd64 (3.2.5-gg1130)
JVM: 1.7.0-google-v5
# projects: 2
# open dart files: 17
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 943 / 943 / 694 MB
thread count: 22
analysis: 0 tasks, 169 libraries, 1 contexts
index: 216775 relationships and 0 attributes in 32368 elements in 754 resources stored in 6 MB on disk

SDK installed: true
Dartium installed: true
analysis engine: dartc

**Comment by srawlins** [comment]
Live reproduction: https://dartpad.dartlang.org/8d4c86ae4c25f3866de476afd8b6868d

**Comment by bwilkerson** [comment]
There is now a lint rule for this (`hash_and_equals`).
