### ISSUE TITLE
Crazy amount of Problems for a single syntax error

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#9714]
See attached screenshot:

Consider this code:

import 'dart:html';
import 'package:web_ui/web_ui.dart';

List&lt;String&gt; fruits = cont &lt;String&gt;['apples', 'bananas', 'pears'];

String defaultFruit = 'pears';

void main() {
&nbsp;&nbsp;var foo = 1;
&nbsp;&nbsp;var bar = (foo = 2);
&nbsp;&nbsp;print(bar);
}

(notice cont instead of const)

Am using Dart Editor version 0.1.2_r20838

---

**Attachment:**
[Screen Shot 2013-04-06 at 3.42.17 PM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-9714/comment-0/Screen Shot 2013-04-06 at 3.42.17 PM.png) (559.12 KB)

**Comment by srawlins** [comment]
This has been reduced to 4 warnings:

https://dartpad.dartlang.org/3da795e8e6e1e7f7fd900fe268cfeee9

```
[error] Expected to find ';' (/Users/srawlins/xx.dart, line 1, col 29)
[error] Expected a method, getter, setter or operator declaration (/Users/srawlins/xx.dart, line 1, col 35)
[error] Unexpected token '>' (/Users/srawlins/xx.dart, line 1, col 35)
[warning] Undefined name 'cont' (/Users/srawlins/xx.dart, line 1, col 23)
3 errors and 1 warning found.
```

Thus I think the original issue "Crazy amount of problems" has been solved. Of course there still isn't a great warning here... "

Seems like the analyzer should recover from an undefined name by just fast-forwarding to the next ';', avoiding all the following errors. New bug? Existing bug?

**Comment by pq** [comment]
Closing in favor of targeted follow-up issues.
