### ISSUE TITLE
Make mixins forward const constructors.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#9745]
Currently mixin application is specified as creating forwarding constructors for all generative constructors of the superclass.
The created constructors are not const constructors, making it impossible to create a const class with a mixin.

If the superclass constructor is a const constructor, and the mixin doesn't add any fields, please make the created constructor also a const constructor. That would make it possible to create a const class using a mixin:

&nbsp;&nbsp;class EmptyList&lt;E&gt; extends Object with ImmutableListMixin&lt;E&gt; {
&nbsp;&nbsp;&nbsp;&nbsp;int get length =&gt; 0;
&nbsp;&nbsp;&nbsp;&nbsp;int operator[](int i) { throw new RangeError.value(i); }
&nbsp;&nbsp;}

&nbsp;&nbsp;... return const EmptyList(); ... 

Not having const constructors makes mixins less useful.

**Comment by eernstg** [comment]
Issue #29396 was closed as a duplicate of this one; check out that issue for the example.

**Comment by eernstg** [comment]
Closing: As of 63c6851dd01514e9d9e6cb96da0430e15b66d576, constructor forwarding does just [that](https://github.com/dart-lang/sdk/issues/28492#issuecomment-274796650). Created #32223 to put this into the implementation pipeline.
