### ISSUE TITLE
assert/2 crashes but should be legal

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#9753]
[ed note: I think this message comes from the VM]

With just `assert(false)`, it opens up the debugger.
With `assert(false, "impossible")` it dies with this internal error (at runtime).

This "syntax error" happens at runtime. It does not prevent the code from running. I'm guessing that "Internal error" means to report it?

Anyway, it would be nice if assert() allowed an optional second parameter String message, since otherwise it's going to mean falling back to good old `assert(condition && "message")` like in C/C++. One advantage of having the message as an actual parameter instead of using the `&&` shim is to do something useful with it, like print it out (especially useful on the command line).

////////////////////////////////////////////////////////////////////////////////////
Editor: 0.4.4_r20810 (2013-04-03)
OS: Linux - amd64 (3.5.0-26-generic)
JVM: 1.7.0_15
# projects: 5
# open dart files: 2

auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 889 / 463 / 218 MB
thread count: 33
analysis: 0 tasks, 29 libraries, 6 contexts
index: 85962 relationships and 0 attributes in 15459 elements in 147 resources stored in 2 MB on disk

SDK installed: true
Dartium installed: true
analysis engine: dartc

---

**Attachment:**
[screenshot.png](https://storage.googleapis.com/google-code-attachments/dart/issue-9753/comment-0/screenshot.png) (116.36 KB)

**Comment by munificent** [comment]
We are adding messages to `assert()`: #24213
