### ISSUE TITLE
FR: Stream.merge()

### ISSUE THREAD

**Issue by alxhub** [dart-lang/sdk#9778]
dart:async should have an easy way to combine multiple streams into one.

Example implementation which supports pause/resume.

Stream merge(List&lt;Stream&gt; streams) {
&nbsp;&nbsp;int _open = streams.length;
&nbsp;&nbsp;var c = new StreamController();
&nbsp;&nbsp;for (var stream in streams) {
&nbsp;&nbsp;&nbsp;&nbsp;stream.listen(c.add)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..onError(c.addError)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..onDone(() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (--_open == 0) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c.close();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;}
&nbsp;&nbsp;return c.stream;
}

**Comment by zoechi** [comment]
Does StreamZip from dart:async do what you want? http://stackoverflow.com/questions/36571924/how-can-i-merge-multiple-streams-into-a-higher-level-stream

**Comment by lrhn** [comment]
Sounds like [StreamGroup.merge](https://www.dartdocs.org/documentation/async/1.11.1/async/StreamGroup/merge.html) from `package:async`.
