### ISSUE TITLE
Add shell script to SDK that runs Dartium in checked mode

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#9779]
New developers are confused by how to run Dartium in checked mode during development, especially if they aren't using Editor.

Suggest we include a way to run Dartium in checked mode via the SDK, perhaps through a shell script. I can imagine two scripts: dartium_developer_mode.sh and dartium_production_mode.sh

**Comment by kevmoo** [comment]
We don't care about Dartium any more...
