### ISSUE TITLE
Add a utility method to convert a StringLiteral into a Dart String

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#9781]
Once the Dart analyzer is being written in Dart, it would be useful to add a method on the StringLiteral class that converts it to a native Dart string.

**Comment by srawlins** [comment]
https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/dart/ast/ast.dart#L6938..L6942

```dart
abstract class StringLiteral extends Literal {
  /**
   * Return the value of the string literal, or `null` if the string is not a
   * constant string without any string interpolation.
   */
  String get stringValue;
}
```

Close?
