### ISSUE TITLE
Parser error with cascading

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#9823]
Not sure, but I think this is a parser error:

tests/language/crash_6725_test.dart:45:50: unexpected token '=='
&nbsp;&nbsp;if (new DateTime.now()..millisecondsSinceEpoch == 42) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^

**Comment by mhausner** [comment]
Not a bug.
