### ISSUE TITLE
Cannot parse const loop variable in for-in

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#9824]
tests/co19/src/Language/12_Statements/06_For_A01_t11.dart:59:17: unexpected token 'x'
&nbsp;&nbsp;for(const int x in const [1, 2, 3]) break; // 5675
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

**Comment by johnniwinther** [comment]
Fixed by https://codereview.chromium.org/1503063002/
