### ISSUE TITLE
dart2js: use type information to simplify type checks (guards and is checks)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#9836]
Hi, hope this is a useful report.

Consider this code:

main() {
&nbsp;&nbsp;var map = {};
&nbsp;&nbsp;map['fruits'] = ['apples', 'oranges'];

&nbsp;&nbsp;var fruits = map['fruits'];
&nbsp;&nbsp;if (fruits is! List) return;

&nbsp;&nbsp;for (var i = 0; i &lt; fruits.length; i++) {
&nbsp;&nbsp;&nbsp;&nbsp;print(fruits[i]);
&nbsp;&nbsp;}
}

My expectation is that if fruits is not a list, the for loop is never encountered, and that my manual type guard is sufficient.

However, here's the dart2js compiled code:

$.main = function() {
&nbsp;&nbsp;var map, fruits, i;
&nbsp;&nbsp;map = $.makeLiteralMap([]);
&nbsp;&nbsp;map.$indexSet(map, &quot;fruits&quot;, [&quot;apples&quot;, &quot;oranges&quot;]);
&nbsp;&nbsp;fruits = map.$index(map, &quot;fruits&quot;);
&nbsp;&nbsp;if (!(typeof fruits &equals;&equals;&equals; &quot;object&quot; &amp;&amp; fruits !== null &amp;&amp; (fruits.constructor &equals;&equals;&equals; Array || !!$.getInterceptor(fruits).$isList)))
&nbsp;&nbsp;&nbsp;&nbsp;return;
&nbsp;&nbsp;else if (typeof fruits !== &quot;object&quot; || fruits &equals;&equals;&equals; null || fruits.constructor !== Array &amp;&amp; !$.getInterceptor(fruits).$isJavaScriptIndexingBehavior)
&nbsp;&nbsp;&nbsp;&nbsp;return $.main$bailout(1, fruits);
&nbsp;&nbsp;for (i = 0; i &lt; fruits.length; ++i)
&nbsp;&nbsp;&nbsp;&nbsp;$.Primitives_printString($.toString$0(fruits[i]));
};

Shouldn't my manual type guard be sufficient? Can we drop the &quot;else if&quot; guard?

Thanks for taking a look!

**Comment by karlklose** [comment]
Verified fixed in 79a8654e5fb30dfce902636961d6a5ffb69e6f85.
