### ISSUE TITLE
Fixed length list doesn't have its length property inlined by dart2js

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#9849]
Consider this code:

final List colors = new List(3);

main() {
&nbsp;&nbsp;for (var i = 0; i &lt; colors.length; i++) {
&nbsp;&nbsp;&nbsp;&nbsp;print(colors[i]);
&nbsp;&nbsp;}
}

dart2js generates this:

$.main = function() {
&nbsp;&nbsp;var i;
&nbsp;&nbsp;for (var i = 0; i &lt; $.get$length$as($.get$colors()); ++i)
&nbsp;&nbsp;&nbsp;&nbsp;$.Primitives_printString($.toString$0($.$index$as($.get$colors(), i)));
};

Could it know the length of colors at compile time, and inline the number 3 ?

**Comment by karlklose** [comment]
Verified fixed in 79a8654e5fb30dfce902636961d6a5ffb69e6f85.
