### ISSUE TITLE
dart2js does not infer string when used with +

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#9867]
Consider this code:

class Person {
&nbsp;&nbsp;String name = 'Bob';
}

main() {
&nbsp;&nbsp;var p = new Person();
&nbsp;&nbsp;print(&quot;Your name is &quot; + p.name);
&nbsp;&nbsp;print(&quot;Your name is ${p.name}&quot;);
}

Generates this code:

$.main = function() {
&nbsp;&nbsp;var t1 = $.Person$().name;
&nbsp;&nbsp;$.Primitives_printString($.JSString_methods.$add(&quot;Your name is &quot;, t1));
&nbsp;&nbsp;$.Primitives_printString(&quot;Your name is &quot; + t1);
};

Shouldn't both lines use &quot;Your name is &quot; + t1 ?

**Comment by karlklose** [comment]
Verified fixed in 79a8654e5fb30dfce902636961d6a5ffb69e6f85.
Current output is:
    main: function() {
      P.print("Your name is Bob");
      P.print("Your name is Bob");
    }
