### ISSUE TITLE
Option in editor to warn if a type is omitted from methods or function signatures

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#9874]
A customer would like the editor (aka our tools) to warn them if they write the following:

void doStuff(msg) {
&nbsp;&nbsp;// ...
}

They point out that it's unclear if the developer omitted the type annotation for msg because of a bug, or if the developer truly meant to say &quot;dynamic&quot;. Bugs by omission can be detected early by our tools.

They are fine if this extra feedback is a user-selected option in the editor's preferences for &quot;warn on type annotation omission&quot; (naming up to you)

**Comment by srawlins** [comment]
Now that we have [linter](http://dart-lang.github.io/linter/), can we just use ["always specify types"](http://dart-lang.github.io/linter/lints/always_specify_types.html)?

**Comment by bwilkerson** [comment]
Yes.
